In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from lifelines import CoxPHFitter
from sklearn.preprocessing import MinMaxScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
response_OUS.isna().sum().sum()

0

In [4]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [5]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [6]:
# Check null values in D3
clinical_train.isnull().sum().sum()

0

In [7]:
clinical_train

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,OS,event_OS
0,54.238356,1,0,1,0,0,1,0.0,0,0.000000,...,0.029974,0.815962,0.000000,0.002035,0.140311,0.000062,0.009991,0.000370,114.312329,0
1,54.539726,0,0,0,0,1,0,0.0,1,27.404795,...,0.059728,0.707300,0.000000,0.008732,0.191058,0.000349,0.023402,0.000699,111.846575,0
2,59.019178,0,1,0,0,0,1,0.0,1,41.019178,...,0.039463,0.819828,0.000034,0.002518,0.126531,0.000000,0.009452,0.000414,49.479452,1
3,70.726027,0,0,0,0,1,0,0.0,1,37.500000,...,0.061133,0.716212,0.000000,0.003296,0.192388,0.000000,0.018879,0.000899,17.589041,1
4,67.865753,0,0,0,0,1,0,0.0,1,53.000000,...,0.058589,0.696493,0.000199,0.008968,0.202073,0.000399,0.029892,0.001395,66.739726,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,60.435616,0,0,1,0,0,1,1.0,0,0.000000,...,0.029444,0.804831,0.000000,0.001442,0.152626,0.000000,0.009734,0.000361,42.805479,0
135,68.794521,0,0,1,0,0,1,1.0,0,0.000000,...,0.046451,0.792151,0.000000,0.004094,0.142778,0.000079,0.011810,0.000630,42.739726,0
136,57.498630,0,0,1,0,0,1,1.0,1,39.498630,...,0.016316,0.832202,0.000000,0.000914,0.140582,0.000000,0.009137,0.000522,42.312329,0
137,65.684932,0,0,1,0,0,1,1.0,1,71.527397,...,0.038862,0.787588,0.000000,0.003144,0.156640,0.000054,0.011978,0.000705,42.246575,0
138,61.676712,0,0,1,0,0,1,1.0,0,2.250000,...,0.011577,0.830670,0.000000,0.000978,0.147644,0.000000,0.008642,0.000408,42.049315,0

## Test dataset: MAASTRO

In [8]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [9]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [10]:
rows_with_nan = response_MAASTRO[response_MAASTRO.isna().any(axis=1)]

print("Rows with NaN values:")
print(rows_with_nan)

Rows with NaN values:
    patient_id  OS  OS_event  LRC  LRC_event  DFS  DFS_event
10          11 NaN       NaN  NaN        NaN  NaN        NaN
20          21 NaN       NaN  NaN        NaN  NaN        NaN
31          32 NaN       NaN  NaN        NaN  NaN        NaN
51          52 NaN       NaN  NaN        NaN  NaN        NaN
83          84 NaN       NaN  NaN        NaN  NaN        NaN
86          87 NaN       NaN  NaN        NaN  NaN        NaN

In [11]:
# Assuming your data is stored in a list or a pandas DataFrame/Series
# Convert data to a set for faster membership checking
data_set = set(list(response_MAASTRO['patient_id']))

# Find numbers from 1 to 114 not present in data
missing_numbers = set(range(1, 115)) - data_set

# Convert missing_numbers back to a sorted list
missing_numbers_list = sorted(missing_numbers)

In [12]:
MAASTRO_D3

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_003_PET,LBP_012_PET,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET
0,1,55,0,0,1,0,0,1,1,1,...,0.000026,0.001181,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341
1,2,55,0,0,1,0,0,0,0,0,...,0.000056,0.002735,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335
2,3,55,0,0,1,0,0,0,0,1,...,0.000286,0.001888,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229
3,4,61,1,0,0,0,1,1,0,1,...,0.000160,0.003037,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240
4,6,70,0,0,1,0,0,1,1,1,...,0.000071,0.000881,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.000000,0.000544,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078
95,111,63,0,0,0,0,1,0,0,1,...,0.000109,0.000869,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489
96,112,63,0,0,1,0,0,1,1,1,...,0.000000,0.000734,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141
97,113,54,0,0,1,0,0,1,1,0,...,0.000114,0.001640,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038
98,114,62,0,0,0,1,0,1,0,0,...,0.000000,0.000225,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337

In [13]:
# Assuming your data is stored in a list or a pandas DataFrame/Series
# Convert data to a set for faster membership checking
data_set = set(list(MAASTRO_D3['patient_id']))

# Find numbers from 1 to 114 not present in data
missing_numbers = set(range(1, 115)) - data_set

# Convert missing_numbers back to a sorted list
missing_numbers_list = sorted(missing_numbers)

print("Numbers from 1 to 114 not present in data:", missing_numbers_list)

Numbers from 1 to 114 not present in data: [5, 9, 11, 21, 32, 36, 46, 52, 65, 76, 78, 81, 84, 87, 92]

In [14]:
# Assuming your data is stored in a list or a pandas DataFrame/Series
# Convert data to a set for faster membership checking
data_set = set(list(response_MAASTRO['patient_id']))

# Find numbers from 1 to 114 not present in data
missing_numbers = set(range(1, 115)) - data_set

# Convert missing_numbers back to a sorted list
missing_numbers_list = sorted(missing_numbers)

print("Numbers from 1 to 114 not present in data:", missing_numbers_list)

Numbers from 1 to 114 not present in data: []

In [15]:
# need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [16]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]

In [17]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [18]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [19]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [20]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]
lower, upper = np.percentile(y_MAASTRO['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 388)
y_train:  (139,)

(99, 390)

# Feature Selection: RENT

In [21]:
selected_features = ["hpv_related",
                    "uicc8_III-IV",
                    "shape_Sphericity",
                    "oropharynx",
                    "LBP_102_PET",
                    "pack_years"]

# Selecting features in the DataFrame
X_rent = X[selected_features]
X_new = X_rent.copy()

X_MAASTRO_rent = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_rent.copy()

# Standardization

In [22]:
original_X = X.copy()

In [23]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = MinMaxScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [24]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [25]:
X_new

,hpv_related,uicc8_III-IV,shape_Sphericity,oropharynx,LBP_102_PET,pack_years
0,0.0,0.0,0.761164,1,0.000000,0.000000
1,0.0,0.0,0.697049,0,0.000000,27.404795
2,0.0,1.0,0.565792,0,0.000034,41.019178
3,0.0,0.0,0.684364,0,0.000000,37.500000
4,0.0,0.0,0.503142,0,0.000199,53.000000
...,...,...,...,...,...,...
134,1.0,0.0,0.742102,1,0.000000,0.000000
135,1.0,1.0,0.722918,1,0.000000,0.000000
136,1.0,0.0,0.652963,1,0.000000,39.498630
137,1.0,1.0,0.724255,1,0.000000,71.527397
138,1.0,1.0,0.722633,1,0.000000,2.250000

In [26]:
X_new_std

,hpv_related,uicc8_III-IV,shape_Sphericity,oropharynx,LBP_102_PET,pack_years
0,0.0,0.0,0.828413,1,0.000000,0.000000
1,0.0,0.0,0.645006,0,0.000000,0.213981
2,0.0,1.0,0.269537,0,0.066875,0.320284
3,0.0,0.0,0.608721,0,0.000000,0.292806
4,0.0,0.0,0.090323,0,0.386334,0.413832
...,...,...,...,...,...,...
134,1.0,0.0,0.773882,1,0.000000,0.000000
135,1.0,1.0,0.719008,1,0.000000,0.000000
136,1.0,0.0,0.518897,1,0.000000,0.308411
137,1.0,1.0,0.722831,1,0.000000,0.558497
138,1.0,1.0,0.718191,1,0.000000,0.017568

In [27]:
MAASTRO_new

,hpv_related,uicc8_III-IV,shape_Sphericity,oropharynx,LBP_102_PET,pack_years
0,1,0,0.668072,1,0.000026,0
1,0,1,0.669961,1,0.000167,20
2,0,1,0.624081,1,0.000057,6
3,0,1,0.577624,0,0.000000,45
4,1,0,0.630933,1,0.000000,59
...,...,...,...,...,...,...
94,0,1,0.671754,0,0.000000,55
95,0,1,0.632189,0,0.000000,174
96,1,1,0.645548,1,0.000000,0
97,1,0,0.727488,1,0.000000,0
98,0,1,0.672838,0,0.000000,40

In [28]:
MAASTRO_new_std

,hpv_related,uicc8_III-IV,shape_Sphericity,oropharynx,LBP_102_PET,pack_years
0,1,0,0.562115,1,0.050863,0.000000
1,0,1,0.567520,1,0.324583,0.156163
2,0,1,0.436277,1,0.110937,0.046849
3,0,1,0.303383,0,0.000000,0.351367
4,1,0,0.455879,1,0.000000,0.460681
...,...,...,...,...,...,...
94,0,1,0.572648,0,0.000000,0.429449
95,0,1,0.459472,0,0.000000,1.358619
96,1,1,0.497683,1,0.000000,0.000000
97,1,0,0.732079,1,0.000000,0.000000
98,0,1,0.575748,0,0.000000,0.312326

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [29]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:32:13,813] A new study created in memory with name: no-name-96cdc9f5-5626-414c-b7cf-99271f515e1f

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-19 14:32:20,843] A new study created in memory with name: no-name-84a31b5d-2832-497e-8114-21738a1844f8

Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:20,821] Trial 0 finished with value: 0.7737571035318616 and parameters: {}. Best is trial 0 with value: 0.7737571035318616.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7737571035318616], datetime_start=datetime.datetime(2024, 4, 19, 14, 32, 14, 129765), datetime_complete=datetime.datetime(2024, 4, 19, 14, 32, 20, 820927), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7737571035318616

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.1373367791207223
Fold 2 IBS: 0.17153895698332644
Fold 3 IBS: 0.1822486408327174
Fold 4 IBS: 0.18669684505649792
Fold 5 IBS: 0.22978024900389654
[I 2024-04-19 14:32:21,460] Trial 0 finished with value: 0.1815202941994321 and parameters: {}. Best is trial 0 with value: 0.1815202941994321.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.1815202941994321], datetime_start=datetime.datetime(2024, 4, 19, 14, 32, 20, 917603), datetime_complete=datetime.datetime(2024, 4, 19, 14, 32, 21, 459802), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.1815202941994321

In [30]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [31]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.774
train_ibs:  0.182

#### Test

In [32]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [33]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.587
IBS score: 0.278

In [34]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [35]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [36]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:32:22,281] A new study created in memory with name: no-name-e15e6f54-9329-4e2b-a16e-ea0fbcc8de80

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-19 14:32:22,477] A new study created in memory with name: no-name-0a051025-b771-455a-b5aa-90daefab257d

Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6197183098591549
[I 2024-04-19 14:32:22,469] Trial 0 finished with value: 0.7182877718827688 and parameters: {}. Best is trial 0 with value: 0.7182877718827688.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7182877718827688], datetime_start=datetime.datetime(2024, 4, 19, 14, 32, 22, 324224), datetime_complete=datetime.datetime(2024, 4, 19, 14, 32, 22, 469446), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7182877718827688

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651763328038
Fold 2 IBS: 0.22157791469499552
Fold 3 IBS: 0.20453594133219627
Fold 4 IBS: 0.22473803349652854
Fold 5 IBS: 0.21812431436306018
[I 2024-04-19 14:32:22,752] Trial 0 finished with value: 0.2165905443040122 and parameters: {}. Best is trial 0 with value: 0.2165905443040122.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2165905443040122], datetime_start=datetime.datetime(2024, 4, 19, 14, 32, 22, 542854), datetime_complete=datetime.datetime(2024, 4, 19, 14, 32, 22, 752390), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2165905443040122

In [37]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [38]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.718
train_ibs:  0.217

#### Test

In [39]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [40]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.624

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [41]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [42]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:32:23,312] A new study created in memory with name: no-name-263a3dd1-f251-4425-a38a-45eedddf2932

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:23,963] Trial 0 finished with value: 0.7728642463890044 and parameters: {}. Best is trial 0 with value: 0.7728642463890044.

[I 2024-04-19 14:32:23,979] A new study created in memory with name: no-name-22dc7ff2-9844-417b-8b03-27546fb1ba5d

* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7728642463890044], datetime_start=datetime.datetime(2024, 4, 19, 14, 32, 23, 565255), datetime_complete=datetime.datetime(2024, 4, 19, 14, 32, 23, 963297), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7728642463890044

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.1379075778912209
Fold 2 IBS: 0.17350465565162979
Fold 3 IBS: 0.1804557018572776
Fold 4 IBS: 0.1850638089812166
Fold 5 IBS: 0.22818002965649326
[I 2024-04-19 14:32:24,556] Trial 0 finished with value: 0.18102235480756765 and parameters: {}. Best is trial 0 with value: 0.18102235480756765.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.18102235480756765], datetime_start=datetime.datetime(2024, 4, 19, 14, 32, 24, 56535), datetime_complete=datetime.datetime(2024, 4, 19, 14, 32, 24, 556138), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.18102235480756765

In [43]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [44]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.773
train_ibs:  0.181

#### Test

In [45]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [46]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.59

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.272

In [47]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [48]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:32:25,234] A new study created in memory with name: no-name-4f2c9e4c-4461-4e65-b289-cf50921e069f

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:25,878] Trial 0 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7728642463890044.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:26,441] Trial 1 finished with value: 0.7737300472548052 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.7737300472548052.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:27,057] Trial 2 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.7746229043976623.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:27,530] Trial 3 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.7746229043976623.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:28,082] Trial 4 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.7746229043976623.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:28,616] Trial 5 finished with value: 0.7719713892461472 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.7746229043976623.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:29,227] Trial 6 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.7746229043976623.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:29,976] Trial 7 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.7746229043976623.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:30,730] Trial 8 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.7746229043976623.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:31,473] Trial 9 finished with value: 0.7719713892461472 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.7746229043976623.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:32,271] Trial 10 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6220657276995305
[I 2024-04-19 14:32:32,469] Trial 11 finished with value: 0.7175731454432046 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:33,097] Trial 12 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6220657276995305
[I 2024-04-19 14:32:33,348] Trial 13 finished with value: 0.7175731454432046 and parameters: {'l1_ratio': 0.0031985064812224406}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:33,878] Trial 14 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.14354731809284052}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:34,530] Trial 15 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.14547377630010583}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:35,062] Trial 16 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.13463318817607284}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:35,669] Trial 17 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.2906031874230555}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:36,268] Trial 18 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.0668769468789637}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:36,730] Trial 19 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.9929341434741732}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:37,585] Trial 20 finished with value: 0.7737300472548052 and parameters: {'l1_ratio': 0.2388803760219412}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:38,327] Trial 21 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.10825799833043775}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:38,982] Trial 22 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.18602446416420754}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798

Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:39,509] Trial 23 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.35431593754643226}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:40,391] Trial 24 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.07543723109624823}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:41,428] Trial 25 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.19147826708277826}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:42,016] Trial 26 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.33104202854466025}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:42,869] Trial 27 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.07505393448412474}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:43,605] Trial 28 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.6010115468401365}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:44,257] Trial 29 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6220657276995305
[I 2024-04-19 14:32:44,446] Trial 30 finished with value: 0.7175731454432046 and parameters: {'l1_ratio': 0.0027141332606375745}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:45,112] Trial 31 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.1579645274939656}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:45,729] Trial 32 finished with value: 0.7737300472548052 and parameters: {'l1_ratio': 0.2608449305459508}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:46,402] Trial 33 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.12552692568198015}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:47,521] Trial 34 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.21553914253693035}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:49,013] Trial 35 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.09439236574935331}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:51,007] Trial 36 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.29481388667182873}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:52,191] Trial 37 finished with value: 0.7538217646091808 and parameters: {'l1_ratio': 0.047651823273698615}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:53,193] Trial 38 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.16359210228855003}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:54,239] Trial 39 finished with value: 0.7719713892461472 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:55,426] Trial 40 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.5204911496675979}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:56,024] Trial 41 finished with value: 0.7538217646091808 and parameters: {'l1_ratio': 0.04200500622093118}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:57,157] Trial 42 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.11857117314700913}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:58,919] Trial 43 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.059820186386939866}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:00,100] Trial 44 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.18479919582681775}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:00,950] Trial 45 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.2219487310959829}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:01,591] Trial 46 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.13015736427913677}. Best is trial 10 with value: 0.7754667862542024.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:02,201] Trial 47 finished with value: 0.7538217646091808 and parameters: {'l1_ratio': 0.03720658033263785}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:03,085] Trial 48 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.7991933234425521}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:03,783] Trial 49 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.2632769157799648}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:04,141] Trial 50 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.6064718647459368}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:04,606] Trial 51 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.09816171051292913}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:05,216] Trial 52 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.12357203892548647}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6220657276995305
[I 2024-04-19 14:33:05,423] Trial 53 finished with value: 0.7175731454432046 and parameters: {'l1_ratio': 0.001652964617927119}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:06,145] Trial 54 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.0766220227537334}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:07,224] Trial 55 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.15670482180909134}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:07,827] Trial 56 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.32494416118325853}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:09,222] Trial 57 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.20064052709441835}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:09,631] Trial 58 finished with value: 0.7538217646091808 and parameters: {'l1_ratio': 0.03543069839139975}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:10,142] Trial 59 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.3753081895637935}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:10,787] Trial 60 finished with value: 0.7737300472548052 and parameters: {'l1_ratio': 0.2515641590995168}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:11,509] Trial 61 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.09282939538737447}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:12,252] Trial 62 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.08233902168782571}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:12,972] Trial 63 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.1621764229968508}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:13,462] Trial 64 finished with value: 0.7538217646091808 and parameters: {'l1_ratio': 0.026306706519316374}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:14,010] Trial 65 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.11469461563448075}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:14,937] Trial 66 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.05986649514948058}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:15,606] Trial 67 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.18696496327091963}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:16,349] Trial 68 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.14296945203278355}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:17,481] Trial 69 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.06630548571341087}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801

Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:18,268] Trial 70 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.10412548590076268}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:19,306] Trial 71 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.06301381496313624}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:20,025] Trial 72 finished with value: 0.7538217646091808 and parameters: {'l1_ratio': 0.025824348211075238}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:20,725] Trial 73 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.14564596751709807}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:21,350] Trial 74 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.09670637129029576}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:21,818] Trial 75 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.22048173815246813}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:22,353] Trial 76 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.17754425251325626}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:22,787] Trial 77 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.12827875958613677}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6220657276995305
[I 2024-04-19 14:33:22,943] Trial 78 finished with value: 0.7175731454432046 and parameters: {'l1_ratio': 0.0003153084751211649}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:23,452] Trial 79 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.07236212705648226}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:23,813] Trial 80 finished with value: 0.7538217646091808 and parameters: {'l1_ratio': 0.04636997257316786}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:24,280] Trial 81 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.13080542832827352}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:24,878] Trial 82 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.10859231400863753}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:25,304] Trial 83 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.20355470234225564}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:25,782] Trial 84 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.08542356455512168}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:26,014] Trial 85 finished with value: 0.7577433332366318 and parameters: {'l1_ratio': 0.02206793050500999}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:26,525] Trial 86 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.13785633895492974}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:26,761] Trial 87 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.6914179079469647}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:27,841] Trial 88 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.16880465695640456}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:28,456] Trial 89 finished with value: 0.7737300472548052 and parameters: {'l1_ratio': 0.2793361602734755}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:28,923] Trial 90 finished with value: 0.7538217646091808 and parameters: {'l1_ratio': 0.0438769551206258}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:29,427] Trial 91 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.10782966184306192}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:29,954] Trial 92 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.09222986567277357}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:30,364] Trial 93 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.07390376521601023}. Best is trial 10 with value: 0.7754667862542024.

Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:30,931] Trial 94 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.23468019460709835}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:31,230] Trial 95 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.9190946752122768}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:31,743] Trial 96 finished with value: 0.7728642463890044 and parameters: {'l1_ratio': 0.754234381640172}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:32,397] Trial 97 finished with value: 0.7746229043976623 and parameters: {'l1_ratio': 0.15633016371179098}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:32,997] Trial 98 finished with value: 0.7754667862542024 and parameters: {'l1_ratio': 0.12505760343207817}. Best is trial 10 with value: 0.7754667862542024.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7946428571428571

[I 2024-04-19 14:33:33,385] A new study created in memory with name: no-name-3e3d3e45-8889-4778-9d66-8bfce5b9fa8f

Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:33,348] Trial 99 finished with value: 0.7577433332366318 and parameters: {'l1_ratio': 0.019632704912661635}. Best is trial 10 with value: 0.7754667862542024.


* Best trial for C-index:
 FrozenTrial(number=10, state=TrialState.COMPLETE, values=[0.7754667862542024], datetime_start=datetime.datetime(2024, 4, 19, 14, 32, 31, 478369), datetime_complete=datetime.datetime(2024, 4, 19, 14, 32, 32, 270806), params={'l1_ratio': 0.08382735104105443}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=10, value=None)


* Best Score for C-index:
 0.7754667862542024

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.13793266023897713
Fold 2 IBS: 0.17408534631677686
Fold 3 IBS: 0.18062108893239429
Fold 4 IBS: 0.18491291697007217
Fold 5 IBS: 0.228403425142968
[I 2024-04-19 14:33:33,994] Trial 0 finished with value: 0.18119108752023766 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.18119108752023766.
Fold 1 IBS: 0.13796360852494668
Fold 2 IBS: 0.174220731021994
Fold 3 IBS: 0.18098955706787243
Fold 4 IBS: 0.18492966881136322
Fold 5 IBS: 0.2285754429202737
[I 2024-04-19 14:33:34,911] Trial 1 finished with value: 0.18133580166929 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.18119108752023766.
Fold 1 IBS: 0.13800363064481616
Fold 2 IBS: 0.17417052794133223
Fold 3 IBS: 0.18096053274475865
Fold 4 IBS: 0.18494867121192474
Fold 5 IBS: 0.22864295136557042
[I 2024-04-19 14:33:36,105] Trial 2 finished with value: 0.18134526278168045 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.18119108752023766.
Fold 1 IBS: 0.13797806308082047
Fold 2 IBS: 0.17414625821225396
Fold 3 IBS: 0.18075805437853057
Fold 4 IBS: 0.18485053732787604
Fold 5 IBS: 0.22850681748289578
[I 2024-04-19 14:33:36,777] Trial 3 finished with value: 0.18124794609647538 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.18119108752023766.
Fold 1 IBS: 0.13791085944630208
Fold 2 IBS: 0.174212713286052
Fold 3 IBS: 0.18066077976383088
Fold 4 IBS: 0.18498637100836096
Fold 5 IBS: 0.2283124226217381
[I 2024-04-19 14:33:37,399] Trial 4 finished with value: 0.1812166292252568 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.18119108752023766.
Fold 1 IBS: 0.13799519453324544
Fold 2 IBS: 0.1742441014565425
Fold 3 IBS: 0.1808377812112087
Fold 4 IBS: 0.18491799807525963
Fold 5 IBS: 0.22855951911399647
[I 2024-04-19 14:33:38,059] Trial 5 finished with value: 0.18131091887805054 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.18119108752023766.
Fold 1 IBS: 0.1378680557947714
Fold 2 IBS: 0.17353587931603334
Fold 3 IBS: 0.18043072613846137
Fold 4 IBS: 0.18515240936219654
Fold 5 IBS: 0.22815475917185013
[I 2024-04-19 14:33:38,666] Trial 6 finished with value: 0.18102836595666255 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.18102836595666255.
Fold 1 IBS: 0.13794423911772474
Fold 2 IBS: 0.17412032532872865
Fold 3 IBS: 0.18060006223753394
Fold 4 IBS: 0.1848720359323417
Fold 5 IBS: 0.22838420090961717
[I 2024-04-19 14:33:39,432] Trial 7 finished with value: 0.18118417270518924 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.18102836595666255.
Fold 1 IBS: 0.13796637640436812
Fold 2 IBS: 0.17408360352046293
Fold 3 IBS: 0.18085790601858762
Fold 4 IBS: 0.18487097599423558
Fold 5 IBS: 0.22847318629975905
[I 2024-04-19 14:33:39,970] Trial 8 finished with value: 0.18125040964748268 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.18102836595666255.
Fold 1 IBS: 0.1379874174946584
Fold 2 IBS: 0.1742381287138269
Fold 3 IBS: 0.18087415108890428
Fold 4 IBS: 0.18492035720301703
Fold 5 IBS: 0.22857820418992655
[I 2024-04-19 14:33:40,518] Trial 9 finished with value: 0.18131965173806663 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.18102836595666255.
Fold 1 IBS: 0.13786569497067
Fold 2 IBS: 0.17352996185462738
Fold 3 IBS: 0.18043545570385894
Fold 4 IBS: 0.18502187318447574
Fold 5 IBS: 0.22815954296135244
[I 2024-04-19 14:33:41,275] Trial 10 finished with value: 0.1810025057349969 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13790951385441858
Fold 2 IBS: 0.1735090840190989
Fold 3 IBS: 0.18045215660964017
Fold 4 IBS: 0.18505646716712199
Fold 5 IBS: 0.22817644063879367
[I 2024-04-19 14:33:42,118] Trial 11 finished with value: 0.18102073245781466 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1379111996388794
Fold 2 IBS: 0.173512939790615
Fold 3 IBS: 0.18044907057970705
Fold 4 IBS: 0.18505007562685066
Fold 5 IBS: 0.22817331694145385
[I 2024-04-19 14:33:42,619] Trial 12 finished with value: 0.18101932051550118 and parameters: {'l1_ratio': 0.9948264745658929}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13790653184648335
Fold 2 IBS: 0.1738598340918989
Fold 3 IBS: 0.18057319735877958
Fold 4 IBS: 0.1849478602515839
Fold 5 IBS: 0.22824569049123583
[I 2024-04-19 14:33:43,180] Trial 13 finished with value: 0.18110662280799633 and parameters: {'l1_ratio': 0.8533914385368985}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13800486194803882
Fold 2 IBS: 0.17423395926359672
Fold 3 IBS: 0.18105152660628343
Fold 4 IBS: 0.1850302558425427
Fold 5 IBS: 0.22869972384144233
[I 2024-04-19 14:33:43,874] Trial 14 finished with value: 0.1814040655003808 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13789688269967307
Fold 2 IBS: 0.1738016697367806
Fold 3 IBS: 0.18058902783033173
Fold 4 IBS: 0.18498422138380072
Fold 5 IBS: 0.2282635347201283
[I 2024-04-19 14:33:44,392] Trial 15 finished with value: 0.18110706727414289 and parameters: {'l1_ratio': 0.8657755126546848}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1378992226186805
Fold 2 IBS: 0.17381578079670648
Fold 3 IBS: 0.18058656895939948
Fold 4 IBS: 0.18497542275825823
Fold 5 IBS: 0.2282592032945642
[I 2024-04-19 14:33:45,402] Trial 16 finished with value: 0.18110723968552175 and parameters: {'l1_ratio': 0.862740118448912}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13792071578244866
Fold 2 IBS: 0.1741752335137442
Fold 3 IBS: 0.1805969708728763
Fold 4 IBS: 0.1849947454664216
Fold 5 IBS: 0.22839098404344146
[I 2024-04-19 14:33:46,039] Trial 17 finished with value: 0.18121572993578644 and parameters: {'l1_ratio': 0.76987953123623}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13795117611958072
Fold 2 IBS: 0.17398041034682715
Fold 3 IBS: 0.18068437042207092
Fold 4 IBS: 0.18496340692567761
Fold 5 IBS: 0.22844722554497277
[I 2024-04-19 14:33:47,076] Trial 18 finished with value: 0.18120531787182584 and parameters: {'l1_ratio': 0.581032474189674}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13792169945434654
Fold 2 IBS: 0.17368774721780347
Fold 3 IBS: 0.1804914069482426
Fold 4 IBS: 0.1850948024743532
Fold 5 IBS: 0.22818948695796648
[I 2024-04-19 14:33:47,835] Trial 19 finished with value: 0.18107702861054245 and parameters: {'l1_ratio': 0.9055945264065801}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13796332009257747
Fold 2 IBS: 0.17404149808946942
Fold 3 IBS: 0.18074806935567903
Fold 4 IBS: 0.1849278081434482
Fold 5 IBS: 0.2283852213124929
[I 2024-04-19 14:33:48,511] Trial 20 finished with value: 0.18121318339873344 and parameters: {'l1_ratio': 0.6127580877814559}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13787983428074663
Fold 2 IBS: 0.1735653902245544
Fold 3 IBS: 0.1804071658643588
Fold 4 IBS: 0.1851077579349447
Fold 5 IBS: 0.22826534203289017
[I 2024-04-19 14:33:49,208] Trial 21 finished with value: 0.18104509806749894 and parameters: {'l1_ratio': 0.9632315494528705}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13791095860553992
Fold 2 IBS: 0.17351238851157522
Fold 3 IBS: 0.180449511758697
Fold 4 IBS: 0.18505098940257483
Fold 5 IBS: 0.22817376348068866
[I 2024-04-19 14:33:49,690] Trial 22 finished with value: 0.18101952235181512 and parameters: {'l1_ratio': 0.9951691504316933}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13791302294291952
Fold 2 IBS: 0.17413029829120566
Fold 3 IBS: 0.18061132305693833
Fold 4 IBS: 0.18487206484918556
Fold 5 IBS: 0.22827260416472628
[I 2024-04-19 14:33:50,231] Trial 23 finished with value: 0.18115986266099507 and parameters: {'l1_ratio': 0.7789068307771423}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1379028266188432
Fold 2 IBS: 0.1735733866446761
Fold 3 IBS: 0.1805258675985514
Fold 4 IBS: 0.18502073501393776
Fold 5 IBS: 0.22822266477544179
[I 2024-04-19 14:33:50,737] Trial 24 finished with value: 0.18104909613029005 and parameters: {'l1_ratio': 0.9307178174147255}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13789485967588697
Fold 2 IBS: 0.17402562935978472

Fold 3 IBS: 0.18049229992708363
Fold 4 IBS: 0.18494013824001135
Fold 5 IBS: 0.22830557629307754
[I 2024-04-19 14:33:51,209] Trial 25 finished with value: 0.18113170069916884 and parameters: {'l1_ratio': 0.8005553218104735}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.213325599353432
Fold 2 IBS: 0.2212085639150785
Fold 3 IBS: 0.2036351232281279
Fold 4 IBS: 0.2235475767704662
Fold 5 IBS: 0.22861135864913015
[I 2024-04-19 14:33:51,555] Trial 26 finished with value: 0.21806564438324694 and parameters: {'l1_ratio': 0.015423757551295547}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13792003960212768
Fold 2 IBS: 0.1736776905211753
Fold 3 IBS: 0.1804944373614312
Fold 4 IBS: 0.18510053497608653
Fold 5 IBS: 0.22819254258307953
[I 2024-04-19 14:33:52,033] Trial 27 finished with value: 0.18107704900878002 and parameters: {'l1_ratio': 0.9077523133880177}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13792418015491037
Fold 2 IBS: 0.17396605039149485
Fold 3 IBS: 0.180541011938223
Fold 4 IBS: 0.18503221879433474
Fold 5 IBS: 0.22821480166009356
[I 2024-04-19 14:33:52,592] Trial 28 finished with value: 0.1811356525878113 and parameters: {'l1_ratio': 0.8316172415345875}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13793601888105084
Fold 2 IBS: 0.17410068670998877
Fold 3 IBS: 0.18067405551668658
Fold 4 IBS: 0.1848947379076157
Fold 5 IBS: 0.22844302476951484
[I 2024-04-19 14:33:53,263] Trial 29 finished with value: 0.18120970475697135 and parameters: {'l1_ratio': 0.6466325528407055}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13794415630037835
Fold 2 IBS: 0.1740927499753946
Fold 3 IBS: 0.18055436624921242
Fold 4 IBS: 0.1849156902279191
Fold 5 IBS: 0.2283522097606267
[I 2024-04-19 14:33:53,973] Trial 30 finished with value: 0.18117183450270624 and parameters: {'l1_ratio': 0.7441634821999121}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13786917778784097
Fold 2 IBS: 0.17353869133205196
Fold 3 IBS: 0.1804284792396289
Fold 4 IBS: 0.18514815018161945
Fold 5 IBS: 0.22815248684347958
[I 2024-04-19 14:33:54,562] Trial 31 finished with value: 0.18102739707692417 and parameters: {'l1_ratio': 0.9790688580751187}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1378626795204398
Fold 2 IBS: 0.17352240237042718
Fold 3 IBS: 0.18044150024567115
Fold 4 IBS: 0.18503439372602826
Fold 5 IBS: 0.22816565817909742
[I 2024-04-19 14:33:55,037] Trial 32 finished with value: 0.18100532680833276 and parameters: {'l1_ratio': 0.9889797780923784}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13790569066522682
Fold 2 IBS: 0.17359075609315472
Fold 3 IBS: 0.1805206264818357
Fold 4 IBS: 0.1850099129874457
Fold 5 IBS: 0.22821737310295387
[I 2024-04-19 14:33:55,729] Trial 33 finished with value: 0.18104887186612334 and parameters: {'l1_ratio': 0.9268179725218418}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13790968047187457
Fold 2 IBS: 0.17350946512475326
Fold 3 IBS: 0.18045185155187704
Fold 4 IBS: 0.18505583538535667
Fold 5 IBS: 0.22817613183961044
[I 2024-04-19 14:33:56,440] Trial 34 finished with value: 0.1810205928746944 and parameters: {'l1_ratio': 0.9969901411211027}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1379336246748936
Fold 2 IBS: 0.17376808577763234
Fold 3 IBS: 0.18046720875884653
Fold 4 IBS: 0.18504900878959418
Fold 5 IBS: 0.22829538536642746
[I 2024-04-19 14:33:57,175] Trial 35 finished with value: 0.18110266267347883 and parameters: {'l1_ratio': 0.8886948463009224}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1379756941057544
Fold 2 IBS: 0.17429486649917353
Fold 3 IBS: 0.1810038691560261
Fold 4 IBS: 0.18486752028322764
Fold 5 IBS: 0.22867429745101678
[I 2024-04-19 14:33:58,417] Trial 36 finished with value: 0.18136324949903967 and parameters: {'l1_ratio': 0.2363544643091693}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.137937975149848
Fold 2 IBS: 0.17404892341293796
Fold 3 IBS: 0.18051590950733792
Fold 4 IBS: 0.18498481585034304
Fold 5 IBS: 0.22832719242123897
[I 2024-04-19 14:33:58,884] Trial 37 finished with value: 0.1811629632683412 and parameters: {'l1_ratio': 0.8153409684931796}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13792542193645532
Fold 2 IBS: 0.17429224467479904
Fold 3 IBS: 0.1806342342180895
Fold 4 IBS: 0.1849364286486253
Fold 5 IBS: 0.22841546839653507
[I 2024-04-19 14:33:59,553] Trial 38 finished with value: 0.18124075957490085 and parameters: {'l1_ratio': 0.7039737188855323}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13789081683421026
Fold 2 IBS: 0.17359264556038995
Fold 3 IBS: 0.1803852520800545
Fold 4 IBS: 0.18506616142851143
Fold 5 IBS: 0.2282449233682567
[I 2024-04-19 14:34:00,452] Trial 39 finished with value: 0.18103595985428456 and parameters: {'l1_ratio': 0.9474275487738926}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.137992603099069
Fold 2 IBS: 0.1740737097040066
Fold 3 IBS: 0.18090690390992803
Fold 4 IBS: 0.1848723527174609
Fold 5 IBS: 0.2285988985999584
[I 2024-04-19 14:34:01,351] Trial 40 finished with value: 0.1812888936060846 and parameters: {'l1_ratio': 0.3265779752401228}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13791028307790307
Fold 2 IBS: 0.17351084344596937
Fold 3 IBS: 0.18045074832990715
Fold 4 IBS: 0.18505355053253683
Fold 5 IBS: 0.22817501511991103
[I 2024-04-19 14:34:01,797] Trial 41 finished with value: 0.18102008810124548 and parameters: {'l1_ratio': 0.9961307790867789}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1378950773918187
Fold 2 IBS: 0.17360082174787844
Fold 3 IBS: 0.18053818888093162
Fold 4 IBS: 0.18505003910081666
Fold 5 IBS: 0.22823701880413255
[I 2024-04-19 14:34:02,539] Trial 42 finished with value: 0.18106422918511558 and parameters: {'l1_ratio': 0.9414327298927527}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.137930625173652
Fold 2 IBS: 0.17374993854601328
Fold 3 IBS: 0.18047267268558215
Fold 4 IBS: 0.18505935344799485
Fold 5 IBS: 0.2283004779230443
[I 2024-04-19 14:34:03,044] Trial 43 finished with value: 0.1811026135552573 and parameters: {'l1_ratio': 0.892460232405927}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13791127664502323
Fold 2 IBS: 0.17351311591377228
Fold 3 IBS: 0.18044892963466982
Fold 4 IBS: 0.1850497836967648
Fold 5 IBS: 0.22817317428569575
[I 2024-04-19 14:34:03,637] Trial 44 finished with value: 0.18101925603518518 and parameters: {'l1_ratio': 0.9947170440864863}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13789254175528176
Fold 2 IBS: 0.17359680413753034
Fold 3 IBS: 0.18054284432449405
Fold 4 IBS: 0.1850596331048199
Fold 5 IBS: 0.22824172205807267
[I 2024-04-19 14:34:03,971] Trial 45 finished with value: 0.18106670907603975 and parameters: {'l1_ratio': 0.9449914988675847}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13796823950972698
Fold 2 IBS: 0.17408259977256574
Fold 3 IBS: 0.18082402294017325
Fold 4 IBS: 0.1848895481731546
Fold 5 IBS: 0.22844742192081102
[I 2024-04-19 14:34:04,764] Trial 46 finished with value: 0.18124236646328631 and parameters: {'l1_ratio': 0.5222973322437542}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13791438533964587
Fold 2 IBS: 0.17390712679254872
Fold 3 IBS: 0.18055885063769977
Fold 4 IBS: 0.18491829586719113
Fold 5 IBS: 0.22823120855883072
[I 2024-04-19 14:34:05,229] Trial 47 finished with value: 0.18110597343918325 and parameters: {'l1_ratio': 0.8435655367687911}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13788289889575683
Fold 2 IBS: 0.173789148446806
Fold 3 IBS: 0.18046086818556742
Fold 4 IBS: 0.1850370012928587
Fold 5 IBS: 0.22828947637866864
[I 2024-04-19 14:34:06,270] Trial 48 finished with value: 0.1810918786399315 and parameters: {'l1_ratio': 0.8843614822650676}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13795645995482736
Fold 2 IBS: 0.17407030220357553
Fold 3 IBS: 0.18077604006423348
Fold 4 IBS: 0.18487808437412048
Fold 5 IBS: 0.22850912360467354
[I 2024-04-19 14:34:06,852] Trial 49 finished with value: 0.1812380020402861 and parameters: {'l1_ratio': 0.4477016529538363}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13788219087084894

Fold 2 IBS: 0.17357129267324153
Fold 3 IBS: 0.18040245924553208
Fold 4 IBS: 0.18509882657751178
Fold 5 IBS: 0.22826095590467202
[I 2024-04-19 14:34:07,354] Trial 50 finished with value: 0.18104314505436125 and parameters: {'l1_ratio': 0.9597969545716079}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13786776723073743
Fold 2 IBS: 0.17353515606724473
Fold 3 IBS: 0.18043130410415925
Fold 4 IBS: 0.18515350487684412
Fold 5 IBS: 0.2281553437132104
[I 2024-04-19 14:34:08,048] Trial 51 finished with value: 0.18102861519843919 and parameters: {'l1_ratio': 0.9812035738211817}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13786265403371792
Fold 2 IBS: 0.17352233847164902
Fold 3 IBS: 0.18044155135129256
Fold 4 IBS: 0.18503449960449686
Fold 5 IBS: 0.2281657098888555
[I 2024-04-19 14:34:08,889] Trial 52 finished with value: 0.1810053506700024 and parameters: {'l1_ratio': 0.9890190374631385}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13791454039317785
Fold 2 IBS: 0.17364439014522637
Fold 3 IBS: 0.18050447574294937
Fold 4 IBS: 0.18497649869057706
Fold 5 IBS: 0.22820266715419463
[I 2024-04-19 14:34:09,679] Trial 53 finished with value: 0.18104851442522504 and parameters: {'l1_ratio': 0.9149676191023512}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13790519906580018
Fold 2 IBS: 0.17385180397313912
Fold 3 IBS: 0.1805756341924187
Fold 4 IBS: 0.18495288041014202
Fold 5 IBS: 0.22824815249263225
[I 2024-04-19 14:34:10,471] Trial 54 finished with value: 0.18110673402682648 and parameters: {'l1_ratio': 0.8550812580612428}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1378812433135609
Fold 2 IBS: 0.17356891940046965
Fold 3 IBS: 0.18040435142055364
Fold 4 IBS: 0.1851024174427426
Fold 5 IBS: 0.2282627191829056
[I 2024-04-19 14:34:11,310] Trial 55 finished with value: 0.18104393015204648 and parameters: {'l1_ratio': 0.9611750711081389}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13791097009497597
Fold 2 IBS: 0.17351241478976487
Fold 3 IBS: 0.18044949072837055
Fold 4 IBS: 0.18505094584459586
Fold 5 IBS: 0.22817374219466074
[I 2024-04-19 14:34:12,044] Trial 56 finished with value: 0.18101951273047362 and parameters: {'l1_ratio': 0.9951528107059826}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13788524999537244
Fold 2 IBS: 0.1738047279092149
Fold 3 IBS: 0.18045617995194663
Fold 4 IBS: 0.18502812078410444
Fold 5 IBS: 0.22828510805156316
[I 2024-04-19 14:34:13,192] Trial 57 finished with value: 0.18109187733844032 and parameters: {'l1_ratio': 0.8811820737908999}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13793681718806175
Fold 2 IBS: 0.17426737449738763
Fold 3 IBS: 0.18056769261718
Fold 4 IBS: 0.1849394795536146
Fold 5 IBS: 0.22836441325493903
[I 2024-04-19 14:34:13,768] Trial 58 finished with value: 0.1812151554222366 and parameters: {'l1_ratio': 0.7520321837900704}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1379406389937348
Fold 2 IBS: 0.17406491110785213
Fold 3 IBS: 0.18051106968874261
Fold 4 IBS: 0.18497564182241605
Fold 5 IBS: 0.22832276030029658
[I 2024-04-19 14:34:14,327] Trial 59 finished with value: 0.18116300438260846 and parameters: {'l1_ratio': 0.8122695994027668}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13790414604258946
Fold 2 IBS: 0.17358138921048186
Fold 3 IBS: 0.18052345273871076
Fold 4 IBS: 0.1850157489720023
Fold 5 IBS: 0.22822022968111294
[I 2024-04-19 14:34:14,824] Trial 60 finished with value: 0.18104899332897945 and parameters: {'l1_ratio': 0.9289172271115684}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13790845019681341
Fold 2 IBS: 0.17350665103417973
Fold 3 IBS: 0.18045410427732989
Fold 4 IBS: 0.1850605006792082
Fold 5 IBS: 0.22817841228676444
[I 2024-04-19 14:34:15,519] Trial 61 finished with value: 0.18102162369485914 and parameters: {'l1_ratio': 0.9987491283812876}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1378817005424693
Fold 2 IBS: 0.17357006452131898
Fold 3 IBS: 0.18040343833893044
Fold 4 IBS: 0.18510068467181703
Fold 5 IBS: 0.22826186828482026
[I 2024-04-19 14:34:16,649] Trial 62 finished with value: 0.1810435512718712 and parameters: {'l1_ratio': 0.9605095980134556}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13790401393281745
Fold 2 IBS: 0.1735805879938954
Fold 3 IBS: 0.18052369450374434
Fold 4 IBS: 0.18501624817069998
Fold 5 IBS: 0.22822047405550389
[I 2024-04-19 14:34:17,359] Trial 63 finished with value: 0.1810490037313322 and parameters: {'l1_ratio': 0.9290972067882455}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13792161581221554
Fold 2 IBS: 0.1736872409797717
Fold 3 IBS: 0.1804915595037534
Fold 4 IBS: 0.18509509103280816
Fold 5 IBS: 0.22818964077294324
[I 2024-04-19 14:34:18,190] Trial 64 finished with value: 0.18107702962029842 and parameters: {'l1_ratio': 0.9057029281339216}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13791024024342313
Fold 2 IBS: 0.17351074547335404
Fold 3 IBS: 0.1804508267449766
Fold 4 IBS: 0.18505371293864986
Fold 5 IBS: 0.22817509449267465
[I 2024-04-19 14:34:18,933] Trial 65 finished with value: 0.18102012397861564 and parameters: {'l1_ratio': 0.9961918163568015}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1378952295042132
Fold 2 IBS: 0.17387079678880119
Fold 3 IBS: 0.18043630663438395
Fold 4 IBS: 0.1849904562194069
Fold 5 IBS: 0.2282665965744838
[I 2024-04-19 14:34:19,298] Trial 66 finished with value: 0.1810918771442578 and parameters: {'l1_ratio': 0.8679327325697542}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1378804562193431
Fold 2 IBS: 0.17356694799041184
Fold 3 IBS: 0.18040592347303006
Fold 4 IBS: 0.18510540055317679
Fold 5 IBS: 0.22826418420073974
[I 2024-04-19 14:34:20,003] Trial 67 finished with value: 0.1810445824873403 and parameters: {'l1_ratio': 0.962322768528202}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.137900275985138
Fold 2 IBS: 0.17405718360135403
Fold 3 IBS: 0.18063461518455132
Fold 4 IBS: 0.18491977018929617
Fold 5 IBS: 0.22829572773541013
[I 2024-04-19 14:34:20,793] Trial 68 finished with value: 0.18116151453914991 and parameters: {'l1_ratio': 0.7939772823121348}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13798979135615624
Fold 2 IBS: 0.17415302694169657
Fold 3 IBS: 0.18104312843017567
Fold 4 IBS: 0.1849408034890809
Fold 5 IBS: 0.2286982477265303
[I 2024-04-19 14:34:22,406] Trial 69 finished with value: 0.18136499958872795 and parameters: {'l1_ratio': 0.14881965141192482}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13791320540096477
Fold 2 IBS: 0.17363630291453575
Fold 3 IBS: 0.18050691425131224
Fold 4 IBS: 0.18498153685405525
Fold 5 IBS: 0.2282051272300028
[I 2024-04-19 14:34:23,155] Trial 70 finished with value: 0.1810486173301742 and parameters: {'l1_ratio': 0.9167361971953024}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13791073930574124
Fold 2 IBS: 0.17351188693489486
Fold 3 IBS: 0.18044991317515538
Fold 4 IBS: 0.18505182080978577
Fold 5 IBS: 0.22817416978144056
[I 2024-04-19 14:34:24,278] Trial 71 finished with value: 0.18101970600140355 and parameters: {'l1_ratio': 0.9954811289776649}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13787544771114663
Fold 2 IBS: 0.173554402077233
Fold 3 IBS: 0.1804159332008491
Fold 4 IBS: 0.18512439011074291
Fold 5 IBS: 0.2281398082382266
[I 2024-04-19 14:34:25,171] Trial 72 finished with value: 0.18102199626763965 and parameters: {'l1_ratio': 0.969689394291109}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13790974140149662
Fold 2 IBS: 0.17350960448889075
Fold 3 IBS: 0.18045173999905698
Fold 4 IBS: 0.18505560435523194
Fold 5 IBS: 0.2281760189196199
[I 2024-04-19 14:34:26,180] Trial 73 finished with value: 0.18102054183285923 and parameters: {'l1_ratio': 0.9969031847887592}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13789659702156837
Fold 2 IBS: 0.1735669355810498
Fold 3 IBS: 0.1805372774455812
Fold 4 IBS: 0.18504428781317384
Fold 5 IBS: 0.22823420162740052
[I 2024-04-19 14:34:26,887] Trial 74 finished with value: 0.18105585989775475 and parameters: {'l1_ratio': 0.9393125003039016}. Best is trial 10 with value: 0.1810025057349969.

Fold 1 IBS: 0.13791970599703723
Fold 2 IBS: 0.17393914521121956
Fold 3 IBS: 0.18054916751240824
Fold 4 IBS: 0.1848983099612984
Fold 5 IBS: 0.22822302198661337
[I 2024-04-19 14:34:28,210] Trial 75 finished with value: 0.18110587013371535 and parameters: {'l1_ratio': 0.8370336718415574}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13787810813920634
Fold 2 IBS: 0.1735610666479849
Fold 3 IBS: 0.18041061486837306
Fold 4 IBS: 0.18511430166207596
Fold 5 IBS: 0.22826855651506914
[I 2024-04-19 14:34:28,961] Trial 76 finished with value: 0.18104652956654188 and parameters: {'l1_ratio': 0.9657626483899301}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1379255107637513
Fold 2 IBS: 0.17371080968819347
Fold 3 IBS: 0.18048445804258714
Fold 4 IBS: 0.18508165661413198
Fold 5 IBS: 0.22818248171104508
[I 2024-04-19 14:34:29,564] Trial 77 finished with value: 0.1810769833639418 and parameters: {'l1_ratio': 0.9006818261629255}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1378720123661026
Fold 2 IBS: 0.1735457947223948
Fold 3 IBS: 0.18042280517629058
Fold 4 IBS: 0.18513742225611354
Fold 5 IBS: 0.2281467494978008
[I 2024-04-19 14:34:30,643] Trial 78 finished with value: 0.18102495680374048 and parameters: {'l1_ratio': 0.9748065148858099}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13790010175258297
Fold 2 IBS: 0.17357300666197642
Fold 3 IBS: 0.18053085667382024
Fold 4 IBS: 0.18503103483666586
Fold 5 IBS: 0.22822770871054612
[I 2024-04-19 14:34:31,725] Trial 79 finished with value: 0.18105254172711832 and parameters: {'l1_ratio': 0.9344581336642902}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13789096429340425
Fold 2 IBS: 0.17384256981099824
Fold 3 IBS: 0.1804447951992161
Fold 4 IBS: 0.18500654805194397
Fold 5 IBS: 0.22827450231124066
[I 2024-04-19 14:34:32,909] Trial 80 finished with value: 0.18109187593336065 and parameters: {'l1_ratio': 0.8735473184337763}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13785986016269916
Fold 2 IBS: 0.1735153332693075
Fold 3 IBS: 0.18044715529930483
Fold 4 IBS: 0.185046108514892
Fold 5 IBS: 0.2281713784862203
[I 2024-04-19 14:34:33,769] Trial 81 finished with value: 0.18100796714648476 and parameters: {'l1_ratio': 0.9933413183534464}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13787001102042606
Fold 2 IBS: 0.17354077951733027
Fold 3 IBS: 0.18042681097952906
Fold 4 IBS: 0.1851449875649971
Fold 5 IBS: 0.22815079982643266
[I 2024-04-19 14:34:35,289] Trial 82 finished with value: 0.18102667778174303 and parameters: {'l1_ratio': 0.9778121366594061}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13788681526703228
Fold 2 IBS: 0.17358287302258907
Fold 3 IBS: 0.18039323056397813
Fold 4 IBS: 0.18508130829533634
Fold 5 IBS: 0.22825235562926668
[I 2024-04-19 14:34:36,918] Trial 83 finished with value: 0.18103931655564048 and parameters: {'l1_ratio': 0.9531265568072592}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1379087696620537
Fold 2 IBS: 0.1735073817842158
Fold 3 IBS: 0.18045351926134834
Fold 4 IBS: 0.1850592891712994
Fold 5 IBS: 0.2281778200510141
[I 2024-04-19 14:34:37,985] Trial 84 finished with value: 0.18102135598598626 and parameters: {'l1_ratio': 0.9982917878866178}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13797463876569743
Fold 2 IBS: 0.17402790764907491
Fold 3 IBS: 0.18069122336360544
Fold 4 IBS: 0.1849269345009244
Fold 5 IBS: 0.2284587070120215
[I 2024-04-19 14:34:39,457] Trial 85 finished with value: 0.18121588225826474 and parameters: {'l1_ratio': 0.6558883596321712}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13791785566708792
Fold 2 IBS: 0.17366446827859344
Fold 3 IBS: 0.1804984227105793
Fold 4 IBS: 0.18496399080299583
Fold 5 IBS: 0.22819656165077237
[I 2024-04-19 14:34:41,205] Trial 86 finished with value: 0.18104825982200579 and parameters: {'l1_ratio': 0.9106043823704123}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13789594222813453
Fold 2 IBS: 0.1735656653719134
Fold 3 IBS: 0.18053660155285461
Fold 4 IBS: 0.18504676454786687
Fold 5 IBS: 0.22823541538087966
[I 2024-04-19 14:34:42,326] Trial 87 finished with value: 0.18105607781632982 and parameters: {'l1_ratio': 0.9402249366761615}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13787060601512283
Fold 2 IBS: 0.17354227058358476
Fold 3 IBS: 0.1804256198831564
Fold 4 IBS: 0.18514272941481907
Fold 5 IBS: 0.22814959542001734
[I 2024-04-19 14:34:43,559] Trial 88 finished with value: 0.18102616426334006 and parameters: {'l1_ratio': 0.9769166741506939}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1379314718384962
Fold 2 IBS: 0.1737550615826763
Fold 3 IBS: 0.18047113006632465
Fold 4 IBS: 0.18505643312624212
Fold 5 IBS: 0.22829904008770724
[I 2024-04-19 14:34:44,483] Trial 89 finished with value: 0.18110262734028928 and parameters: {'l1_ratio': 0.8913942205466193}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13791025292835288
Fold 2 IBS: 0.1736184127205228
Fold 3 IBS: 0.18051228357862278
Fold 4 IBS: 0.1849926823262066
Fold 5 IBS: 0.22820894265245978
[I 2024-04-19 14:34:45,806] Trial 90 finished with value: 0.181048514841233 and parameters: {'l1_ratio': 0.9206714853692884}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13790965515022766
Fold 2 IBS: 0.1735094072065089
Fold 3 IBS: 0.18045189791232527
Fold 4 IBS: 0.18505593139934895
Fold 5 IBS: 0.22817617876839846
[I 2024-04-19 14:34:47,041] Trial 91 finished with value: 0.18102061408736186 and parameters: {'l1_ratio': 0.9970262835434524}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13798888865034498
Fold 2 IBS: 0.17427186628498792
Fold 3 IBS: 0.18089330372403367
Fold 4 IBS: 0.18489866212533296
Fold 5 IBS: 0.22859088013050435
[I 2024-04-19 14:34:48,402] Trial 92 finished with value: 0.18132872018304078 and parameters: {'l1_ratio': 0.35853854987307665}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13788740423668533
Fold 2 IBS: 0.17358434518081028
Fold 3 IBS: 0.18039205581851767
Fold 4 IBS: 0.18507907789656752
Fold 5 IBS: 0.22825126121479689
[I 2024-04-19 14:34:49,471] Trial 93 finished with value: 0.18103882886947553 and parameters: {'l1_ratio': 0.9522835318913557}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13786950019658917
Fold 2 IBS: 0.1735394993408383
Fold 3 IBS: 0.18042783368641366
Fold 4 IBS: 0.1851469264064509
Fold 5 IBS: 0.2281518340235571
[I 2024-04-19 14:34:50,599] Trial 94 finished with value: 0.18102711873076982 and parameters: {'l1_ratio': 0.9785822096632106}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13789417217456812
Fold 2 IBS: 0.1735994180388029
Fold 3 IBS: 0.18053985060587027
Fold 4 IBS: 0.1850534637807441
Fold 5 IBS: 0.22823869749102452
[I 2024-04-19 14:34:51,705] Trial 95 finished with value: 0.181065120418202 and parameters: {'l1_ratio': 0.9427001816471338}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13790865153359402
Fold 2 IBS: 0.17350711157652798
Fold 3 IBS: 0.18045373557814506
Fold 4 IBS: 0.18505973714391466
Fold 5 IBS: 0.22817803903572034
[I 2024-04-19 14:34:53,131] Trial 96 finished with value: 0.1810214549735804 and parameters: {'l1_ratio': 0.9984608505316557}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13790277063172546
Fold 2 IBS: 0.17383716924526826
Fold 3 IBS: 0.1805800758812251
Fold 4 IBS: 0.18496205031105104
Fold 5 IBS: 0.2282526406963097
[I 2024-04-19 14:34:54,210] Trial 97 finished with value: 0.18110694135311592 and parameters: {'l1_ratio': 0.8581771735563917}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.13787102287279407
Fold 2 IBS: 0.1735433152067155
Fold 3 IBS: 0.18042478548391944
Fold 4 IBS: 0.1851411770310962
Fold 5 IBS: 0.22814875173235466
[I 2024-04-19 14:34:55,035] Trial 98 finished with value: 0.18102581046537597 and parameters: {'l1_ratio': 0.9762902653093}. Best is trial 10 with value: 0.1810025057349969.
Fold 1 IBS: 0.1379129034955581
Fold 2 IBS: 0.17363447383224223
Fold 3 IBS: 0.18050746580016352
Fold 4 IBS: 0.18498267634230386
Fold 5 IBS: 0.22820568369122693
[I 2024-04-19 14:34:55,796] Trial 99 finished with value: 0.18104864063229895 and parameters: {'l1_ratio': 0.9171370864067349}. Best is trial 10 with value: 0.1810025057349969.

* Best trial for IBS:
 FrozenTrial(number=10, state=TrialState.COMPLETE, values=[0.1810025057349969], datetime_start=datetime.datetime(2024, 4, 19, 14, 33, 40, 531788), datetime_complete=datetime.datetime(2024, 4, 19, 14, 33, 41, 274869), params={'l1_ratio': 0.9843563326681124}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=10, value=None)


* Best Score for IBS:
 0.1810025057349969

In [49]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [50]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.775
train_ibs:  0.181

#### Test

In [51]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [52]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.08382735104105443)

test_cindex : 0.588

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.9843563326681124)

test_ibs:  0.272

In [53]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [54]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:34:57,186] A new study created in memory with name: no-name-2aaf7a58-b731-4c9b-8a72-bf2c9619caa4

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:35:04,922] Trial 0 finished with value: 0.7439398371546546 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7439398371546546.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 14:35:10,673] Trial 1 finished with value: 0.7591482736873416 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7591482736873416.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.6854460093896714
[I 2024-04-19 14:35:16,312] Trial 2 finished with value: 0.7606119754868026 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:35:17,467] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:35:19,107] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.6854460093896714
[I 2024-04-19 14:35:26,034] Trial 5 finished with value: 0.7603758525566178 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6901408450704225
[I 2024-04-19 14:35:33,477] Trial 6 finished with value: 0.7405153318884403 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:35:37,283] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6830985915492958
[I 2024-04-19 14:35:52,730] Trial 8 finished with value: 0.5366197183098592 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:36:00,070] Trial 9 finished with value: 0.7507634649590724 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:36:00,694] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 26, 'oob_score': True, 'max_samples': 0.9607577284547746, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:36:04,677] Trial 11 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.11379276107227315, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14507778190604323, 'warm_start': False}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7531645569620253
Fold 5 C-index: 0.6784037558685446
[I 2024-04-19 14:36:10,386] Trial 12 finished with value: 0.759657659255699 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.8397501717174567, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1526809711702289, 'warm_start': False}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:36:21,687] Trial 13 finished with value: 0.7606747453515516 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.4777069141417742, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08255864378493685, 'warm_start': False}. Best is trial 13 with value: 0.7606747453515516.
Fold 1 C-index: 0.8441558441558441
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 14:36:29,349] Trial 14 finished with value: 0.8109248858865415 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 482, 'oob_score': True, 'max_samples': 0.433652139551181, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09639289018164084, 'warm_start': True}. Best is trial 14 with value: 0.8109248858865415.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8059071729957806

Fold 5 C-index: 0.7417840375586855
[I 2024-04-19 14:36:35,540] Trial 15 finished with value: 0.8120274196000707 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 480, 'oob_score': True, 'max_samples': 0.4470849120697906, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08807762154599924, 'warm_start': True}. Best is trial 15 with value: 0.8120274196000707.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:36:44,134] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.36871324569404207, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20791692251205332, 'warm_start': True}. Best is trial 15 with value: 0.8120274196000707.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 14:36:52,437] Trial 17 finished with value: 0.7976464367331724 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 493, 'oob_score': True, 'max_samples': 0.4399216700525951, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09373644341192987, 'warm_start': True}. Best is trial 15 with value: 0.8120274196000707.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:36:58,508] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.20703029814340784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 15 with value: 0.8120274196000707.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7605633802816901
[I 2024-04-19 14:37:02,812] Trial 19 finished with value: 0.8265809184741336 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 388, 'oob_score': True, 'max_samples': 0.5423771062394208, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004060792657387402, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 14:37:08,556] Trial 20 finished with value: 0.8129491526995407 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 367, 'oob_score': True, 'max_samples': 0.5530588908263404, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012087063184877466, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 14:37:13,535] Trial 21 finished with value: 0.8070713442754045 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 2, 'n_estimators': 395, 'oob_score': True, 'max_samples': 0.5331904924758448, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002825613326749862, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 14:37:18,796] Trial 22 finished with value: 0.811168575681622 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 345, 'oob_score': True, 'max_samples': 0.542464108386217, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.059334415549051514, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.7417840375586855
[I 2024-04-19 14:37:23,532] Trial 23 finished with value: 0.8039802018637243 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 413, 'oob_score': True, 'max_samples': 0.6910951920927286, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0023497522601186316, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.7276995305164319
[I 2024-04-19 14:37:30,128] Trial 24 finished with value: 0.8026197460945188 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 366, 'oob_score': True, 'max_samples': 0.7981951741169113, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05493240148875182, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 14:37:37,276] Trial 25 finished with value: 0.8088685620117511 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 438, 'oob_score': True, 'max_samples': 0.34586218128841145, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04420235989758884, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7511737089201878
[I 2024-04-19 14:37:41,650] Trial 26 finished with value: 0.8101588552729314 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 319, 'oob_score': True, 'max_samples': 0.5125743041583606, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12228642345499363, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7417840375586855
[I 2024-04-19 14:37:48,728] Trial 27 finished with value: 0.8083955122916929 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.4008125694786513, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06694268404263193, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:37:57,205] Trial 28 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 460, 'oob_score': True, 'max_samples': 0.28554491078673616, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18644610161808028, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.829004329004329
Fold 2 C-index: 0.8459821428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7827004219409283
Fold 5 C-index: 0.7300469483568075
[I 2024-04-19 14:38:04,278] Trial 29 finished with value: 0.7993114743141945 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': None, 'min_weight_fraction_leaf': 0.25087036098392035, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8058035714285714

Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.770042194092827
Fold 5 C-index: 0.7652582159624414
[I 2024-04-19 14:38:08,617] Trial 30 finished with value: 0.7825128767653189 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 1, 'n_estimators': 225, 'oob_score': True, 'max_samples': 0.5856012699634701, 'max_features': None, 'min_weight_fraction_leaf': 0.029048761893088054, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 14:38:13,552] Trial 31 finished with value: 0.810324693825082 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 339, 'oob_score': True, 'max_samples': 0.5365082685042595, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0654723504402752, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.7511737089201878
[I 2024-04-19 14:38:18,012] Trial 32 finished with value: 0.8080877103592699 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 338, 'oob_score': True, 'max_samples': 0.6504737764206872, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1172197135916975, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7464788732394366
[I 2024-04-19 14:38:21,866] Trial 33 finished with value: 0.8119151002837803 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 278, 'oob_score': True, 'max_samples': 0.5004197933079609, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004045278256424187, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8308823529411765
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 14:38:27,900] Trial 34 finished with value: 0.8022488262797298 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 7, 'n_estimators': 266, 'oob_score': True, 'max_samples': 0.7540080692642186, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0026126520645429994, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.859375
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.7065727699530516
[I 2024-04-19 14:38:33,582] Trial 35 finished with value: 0.8028133206434165 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.4869028387236237, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03356017213763633, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 14:38:38,655] Trial 36 finished with value: 0.8137930345560808 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.5806041358482964, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09878284329225405, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 14:38:46,736] Trial 37 finished with value: 0.8053811675645152 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 423, 'oob_score': True, 'max_samples': 0.5941013680617477, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18331972361078192, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 14:38:52,079] Trial 38 finished with value: 0.8130096314364901 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 377, 'oob_score': True, 'max_samples': 0.6475925530300135, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.125647509156449, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.7605633802816901
[I 2024-04-19 14:38:55,947] Trial 39 finished with value: 0.8102832688043693 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 372, 'oob_score': True, 'max_samples': 0.7528827145160659, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11956830452103788, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 14:39:00,621] Trial 40 finished with value: 0.8119854012611057 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 327, 'oob_score': True, 'max_samples': 0.6258126140944148, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13820665027837545, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 14:39:05,807] Trial 41 finished with value: 0.8120562955566836 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 427, 'oob_score': True, 'max_samples': 0.6430681875119886, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09513285163974278, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.7511737089201878
[I 2024-04-19 14:39:10,289] Trial 42 finished with value: 0.8106579156565784 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.6544563584865999, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16620722985299802, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7417840375586855
[I 2024-04-19 14:39:13,907] Trial 43 finished with value: 0.8128223261702938 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 380, 'oob_score': True, 'max_samples': 0.5833432046167292, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07744725117728736, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7605633802816901
[I 2024-04-19 14:39:19,616] Trial 44 finished with value: 0.8240002976181964 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 379, 'oob_score': True, 'max_samples': 0.5629090828815575, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.033267077598237715, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.

Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7746478873239436
[I 2024-04-19 14:39:21,215] Trial 45 finished with value: 0.8354299997280554 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 300, 'oob_score': False, 'max_samples': 0.7222470002244752, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02758707213523423, 'warm_start': True}. Best is trial 45 with value: 0.8354299997280554.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6854460093896714
[I 2024-04-19 14:39:27,196] Trial 46 finished with value: 0.7621782075607598 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.711033292420012, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03832673976162945, 'warm_start': False}. Best is trial 45 with value: 0.8354299997280554.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7699530516431925
[I 2024-04-19 14:39:28,889] Trial 47 finished with value: 0.8379758730182945 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 248, 'oob_score': False, 'max_samples': 0.811827965552719, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0397637496684009, 'warm_start': True}. Best is trial 47 with value: 0.8379758730182945.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.8504464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.6784037558685446
[I 2024-04-19 14:39:34,961] Trial 48 finished with value: 0.7783577371004157 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 239, 'oob_score': False, 'max_samples': 0.8593063971491026, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38812198780775825, 'warm_start': False}. Best is trial 47 with value: 0.8379758730182945.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.784037558685446
[I 2024-04-19 14:39:36,550] Trial 49 finished with value: 0.8372202579633127 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.8972484642218534, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0327604324021709, 'warm_start': True}. Best is trial 47 with value: 0.8379758730182945.
Fold 1 C-index: 0.8095238095238095
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7699530516431925
[I 2024-04-19 14:39:38,078] Trial 50 finished with value: 0.8253861622202813 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 187, 'oob_score': False, 'max_samples': 0.9096856594317103, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029307161033806137, 'warm_start': True}. Best is trial 47 with value: 0.8379758730182945.
Fold 1 C-index: 0.8095238095238095
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7793427230046949
[I 2024-04-19 14:39:39,307] Trial 51 finished with value: 0.8389765029741616 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 168, 'oob_score': False, 'max_samples': 0.8986357837935047, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024993977023469782, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7699530516431925
[I 2024-04-19 14:39:40,370] Trial 52 finished with value: 0.8245203613544803 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 183, 'oob_score': False, 'max_samples': 0.9124850953685916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04879452780445224, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7699530516431925
[I 2024-04-19 14:39:41,552] Trial 53 finished with value: 0.8337062595342356 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 103, 'oob_score': False, 'max_samples': 0.9694832891754099, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.015955854377574904, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7605633802816901
[I 2024-04-19 14:39:42,530] Trial 54 finished with value: 0.8352747469836732 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 102, 'oob_score': False, 'max_samples': 0.9935491799919282, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.020146928359000567, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.816017316017316
Fold 2 C-index: 0.8504464285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.715962441314554
[I 2024-04-19 14:39:43,142] Trial 55 finished with value: 0.8047552793747526 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.9708055320222673, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2886607381144328, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 14:39:45,588] Trial 56 finished with value: 0.7638417419837513 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 121, 'oob_score': False, 'max_samples': 0.8678517557171848, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07411749661885492, 'warm_start': False}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7652582159624414
[I 2024-04-19 14:39:46,415] Trial 57 finished with value: 0.8282529435054788 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 54, 'oob_score': False, 'max_samples': 0.9985441496885937, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01901125299992976, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:39:47,323] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 142, 'oob_score': False, 'max_samples': 0.8145341274347522, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7746478873239436
[I 2024-04-19 14:39:48,306] Trial 59 finished with value: 0.8318354232323248 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.9516241459944998, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05390302950490697, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.

Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7109704641350211
Fold 5 C-index: 0.6901408450704225
[I 2024-04-19 14:39:54,919] Trial 60 finished with value: 0.7386192570027899 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 212, 'oob_score': False, 'max_samples': 0.8830302677685383, 'max_features': None, 'min_weight_fraction_leaf': 0.02065339921258332, 'warm_start': False}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7652582159624414
[I 2024-04-19 14:39:55,611] Trial 61 finished with value: 0.8246763776662547 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.9409535283967405, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.047223304275625946, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7652582159624414
[I 2024-04-19 14:39:56,504] Trial 62 finished with value: 0.8368825259483523 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 80, 'oob_score': False, 'max_samples': 0.9909255399113079, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.060564401380638525, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.7464788732394366
[I 2024-04-19 14:39:56,679] Trial 63 finished with value: 0.7825978814514832 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 6, 'oob_score': False, 'max_samples': 0.7844442872738223, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07818306234119168, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.8095238095238095
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7511737089201878
[I 2024-04-19 14:39:57,133] Trial 64 finished with value: 0.8252017222471089 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 69, 'oob_score': False, 'max_samples': 0.9918256787191303, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10415283732963354, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7934272300469484
[I 2024-04-19 14:39:58,031] Trial 65 finished with value: 0.850810598717193 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 162, 'oob_score': False, 'max_samples': 0.9251279109757057, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.019010366401718107, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7699530516431925
[I 2024-04-19 14:39:58,833] Trial 66 finished with value: 0.8237692928027791 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 149, 'oob_score': False, 'max_samples': 0.8186797133263478, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0629749207386761, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7746478873239436
[I 2024-04-19 14:39:59,868] Trial 67 finished with value: 0.8469788396322564 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 201, 'oob_score': False, 'max_samples': 0.8893544255690964, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04237609813040883, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7793427230046949
[I 2024-04-19 14:40:00,727] Trial 68 finished with value: 0.8451838938706814 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 171, 'oob_score': False, 'max_samples': 0.8988316045578264, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04015517700521556, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.784037558685446
[I 2024-04-19 14:40:01,660] Trial 69 finished with value: 0.8136234170405224 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 174, 'oob_score': False, 'max_samples': 0.8890913885107056, 'max_features': None, 'min_weight_fraction_leaf': 0.08146316173254077, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7793427230046949
[I 2024-04-19 14:40:02,651] Trial 70 finished with value: 0.8417155531396825 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 200, 'oob_score': False, 'max_samples': 0.8475532039854673, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05203981948991963, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7793427230046949
[I 2024-04-19 14:40:03,681] Trial 71 finished with value: 0.8417864474352603 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 208, 'oob_score': False, 'max_samples': 0.8387359054999836, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.051012972615410906, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7746478873239436
[I 2024-04-19 14:40:04,546] Trial 72 finished with value: 0.8460911197571948 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 206, 'oob_score': False, 'max_samples': 0.8510701595136323, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04331038965359059, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 14:40:05,475] Trial 73 finished with value: 0.806078855349657 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 216, 'oob_score': False, 'max_samples': 0.843455667095306, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22468940578387384, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.784037558685446
[I 2024-04-19 14:40:06,641] Trial 74 finished with value: 0.8381298968476351 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 166, 'oob_score': False, 'max_samples': 0.7811372579146033, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04577888728654514, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.

Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7934272300469484
[I 2024-04-19 14:40:08,125] Trial 75 finished with value: 0.8445002610032812 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 202, 'oob_score': False, 'max_samples': 0.77879915845995, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.052692419697654425, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7699530516431925
[I 2024-04-19 14:40:09,146] Trial 76 finished with value: 0.8239275810893248 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 206, 'oob_score': False, 'max_samples': 0.9253437470676411, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09157034665642794, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7605633802816901
[I 2024-04-19 14:40:10,218] Trial 77 finished with value: 0.818559528099802 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 200, 'oob_score': False, 'max_samples': 0.8452233186529318, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10693595316796478, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7746478873239436
[I 2024-04-19 14:40:11,294] Trial 78 finished with value: 0.8345691951070127 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 225, 'oob_score': False, 'max_samples': 0.8663345910785444, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06998068246155405, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8028169014084507
[I 2024-04-19 14:40:12,306] Trial 79 finished with value: 0.8588740048767525 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 144, 'oob_score': False, 'max_samples': 0.9300001709197038, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.010539444733445168, 'warm_start': True}. Best is trial 79 with value: 0.8588740048767525.
Fold 1 C-index: 0.8095238095238095
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:40:16,974] Trial 80 finished with value: 0.7469622182087312 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.9306954403565874, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00944936004342359, 'warm_start': False}. Best is trial 79 with value: 0.8588740048767525.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.784037558685446
[I 2024-04-19 14:40:17,924] Trial 81 finished with value: 0.847042774426745 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.8321608537496396, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05291006399805884, 'warm_start': True}. Best is trial 79 with value: 0.8588740048767525.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7793427230046949
[I 2024-04-19 14:40:18,794] Trial 82 finished with value: 0.8452599254340548 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 129, 'oob_score': False, 'max_samples': 0.8309783929675763, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.057729619505577534, 'warm_start': True}. Best is trial 79 with value: 0.8588740048767525.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7511737089201878
[I 2024-04-19 14:40:19,752] Trial 83 finished with value: 0.8200841775307183 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 132, 'oob_score': False, 'max_samples': 0.7717196481942752, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0875767297078974, 'warm_start': True}. Best is trial 79 with value: 0.8588740048767525.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7699530516431925
[I 2024-04-19 14:40:21,035] Trial 84 finished with value: 0.8327260084004102 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 127, 'oob_score': False, 'max_samples': 0.8165695024214783, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06657177909241849, 'warm_start': True}. Best is trial 79 with value: 0.8588740048767525.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 14:40:22,504] Trial 85 finished with value: 0.8102640740650952 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 234, 'oob_score': False, 'max_samples': 0.8728473103783598, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.133559317330891, 'warm_start': True}. Best is trial 79 with value: 0.8588740048767525.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7981220657276995
[I 2024-04-19 14:40:23,651] Trial 86 finished with value: 0.8614689944763463 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 158, 'oob_score': False, 'max_samples': 0.9236490757653891, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.010422824460162315, 'warm_start': True}. Best is trial 86 with value: 0.8614689944763463.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7934272300469484
[I 2024-04-19 14:40:24,988] Trial 87 finished with value: 0.8622552628889608 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.9017137434558457, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009335947817559209, 'warm_start': True}. Best is trial 87 with value: 0.8622552628889608.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8028169014084507
[I 2024-04-19 14:40:25,915] Trial 88 finished with value: 0.8592718913040507 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 142, 'oob_score': False, 'max_samples': 0.9553890504349966, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01343493318439802, 'warm_start': True}. Best is trial 87 with value: 0.8622552628889608.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.812206572769953
[I 2024-04-19 14:40:27,564] Trial 89 finished with value: 0.8708692541993539 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 144, 'oob_score': False, 'max_samples': 0.9504102015210659, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.005622697057305325, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.

Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.812206572769953
[I 2024-04-19 14:40:29,579] Trial 90 finished with value: 0.8647159758569469 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.9549690830627591, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0017681714272393418, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8262910798122066
[I 2024-04-19 14:40:30,771] Trial 91 finished with value: 0.8684591568681477 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 158, 'oob_score': False, 'max_samples': 0.9467174603025613, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.000357919052720701, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8262910798122066
[I 2024-04-19 14:40:31,462] Trial 92 finished with value: 0.8685081321544648 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 158, 'oob_score': False, 'max_samples': 0.9591642670541899, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.001426642359487633, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8215962441314554
[I 2024-04-19 14:40:32,717] Trial 93 finished with value: 0.8693934390317173 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 156, 'oob_score': False, 'max_samples': 0.966922664758307, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009895599648824556, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8169014084507042
[I 2024-04-19 14:40:33,544] Trial 94 finished with value: 0.8649424341690841 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 140, 'oob_score': False, 'max_samples': 0.9609201057168953, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.001468170125009595, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8262910798122066
[I 2024-04-19 14:40:34,621] Trial 95 finished with value: 0.8676152750116076 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 142, 'oob_score': False, 'max_samples': 0.95795807976842, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009743899191851731, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8309859154929577
[I 2024-04-19 14:40:35,365] Trial 96 finished with value: 0.8651734364307645 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 119, 'oob_score': False, 'max_samples': 0.9538745845573819, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00012379416671484157, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8215962441314554
[I 2024-04-19 14:40:36,154] Trial 97 finished with value: 0.8631423511397136 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 112, 'oob_score': False, 'max_samples': 0.9736020641672304, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0007829840722098722, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8262910798122066
[I 2024-04-19 14:40:37,287] Trial 98 finished with value: 0.8649741754187209 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 116, 'oob_score': False, 'max_samples': 0.9730526944242506, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0006645944868734748, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.759493670886076

[I 2024-04-19 14:40:39,368] A new study created in memory with name: no-name-c7c3bbb7-6bf0-4595-8829-80f531ae85a7

Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:40:39,331] Trial 99 finished with value: 0.7497501026375315 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 114, 'oob_score': False, 'max_samples': 0.9633553447224135, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0004913833796426825, 'warm_start': False}. Best is trial 89 with value: 0.8708692541993539.


* Best trial for C-index:
 FrozenTrial(number=89, state=TrialState.COMPLETE, values=[0.8708692541993539], datetime_start=datetime.datetime(2024, 4, 19, 14, 40, 25, 962483), datetime_complete=datetime.datetime(2024, 4, 19, 14, 40, 27, 563975), params={'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 144, 'oob_score': False, 'max_samples': 0.9504102015210659, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.005622697057305325, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=89, value=None)


* Best Score for C-index:
 0.8708692541993539

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.15503862232024684
Fold 2 IBS: 0.20319522914269622
Fold 3 IBS: 0.16094379999407013
Fold 4 IBS: 0.21722873875655557
Fold 5 IBS: 0.21797473174077578
[I 2024-04-19 14:40:44,510] Trial 0 finished with value: 0.1908762243908689 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.1908762243908689.
Fold 1 IBS: 0.16023986534508597
Fold 2 IBS: 0.19395474779329328
Fold 3 IBS: 0.16031454555886046
Fold 4 IBS: 0.172975897394729
Fold 5 IBS: 0.21839987819842274
[I 2024-04-19 14:40:45,638] Trial 1 finished with value: 0.1811769868580783 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.1811769868580783.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-19 14:40:47,425] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.1811769868580783.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-19 14:40:51,909] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.1811769868580783.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-19 14:40:56,185] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.1811769868580783.
Fold 1 IBS: 0.14278358406907793
Fold 2 IBS: 0.19104640617810376
Fold 3 IBS: 0.15974893241908267
Fold 4 IBS: 0.18141967914714624
Fold 5 IBS: 0.22121445756197555
[I 2024-04-19 14:41:01,993] Trial 5 finished with value: 0.17924261187507723 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.17924261187507723.
Fold 1 IBS: 0.161597390642804
Fold 2 IBS: 0.18052431610529135
Fold 3 IBS: 0.1631233125564435
Fold 4 IBS: 0.20510649473259498
Fold 5 IBS: 0.21388060000563539
[I 2024-04-19 14:41:06,901] Trial 6 finished with value: 0.18484642280855385 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.17924261187507723.
Fold 1 IBS: 0.2050222602246388
Fold 2 IBS: 0.21196256700109892
Fold 3 IBS: 0.19801617201361535
Fold 4 IBS: 0.21703121438219325
Fold 5 IBS: 0.21483387012842806
[I 2024-04-19 14:41:12,795] Trial 7 finished with value: 0.20937321674999487 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.17924261187507723.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-19 14:41:23,310] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.17924261187507723.
Fold 1 IBS: 0.16227187704741966
Fold 2 IBS: 0.19895001932730885
Fold 3 IBS: 0.16307017198323448
Fold 4 IBS: 0.18243397369874165
Fold 5 IBS: 0.22211493856720746
[I 2024-04-19 14:41:25,452] Trial 9 finished with value: 0.18576819612478243 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.17924261187507723.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-19 14:41:35,906] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.17924261187507723.
Fold 1 IBS: 0.16167166624429669
Fold 2 IBS: 0.19975517981664714
Fold 3 IBS: 0.16217391101285217
Fold 4 IBS: 0.18340741460691287
Fold 5 IBS: 0.22014455054252774
[I 2024-04-19 14:41:38,485] Trial 11 finished with value: 0.1854305444446473 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12378097340613392}. Best is trial 5 with value: 0.17924261187507723.
Fold 1 IBS: 0.15436227307322545
Fold 2 IBS: 0.16812264606605484
Fold 3 IBS: 0.1668135896070915
Fold 4 IBS: 0.18231932534867584
Fold 5 IBS: 0.21206553267457903
[I 2024-04-19 14:41:39,029] Trial 12 finished with value: 0.17673667335392534 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.7642078791940475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13207155531457032}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.16382584729538796
Fold 2 IBS: 0.17521532591980685
Fold 3 IBS: 0.15763547423070334
Fold 4 IBS: 0.1717422819826182
Fold 5 IBS: 0.22893054225444412
[I 2024-04-19 14:41:39,564] Trial 13 finished with value: 0.17946989433659208 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 14, 'oob_score': False, 'max_samples': 0.8293737737164385, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09633845721802128}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.13679579990869306
Fold 2 IBS: 0.19651928520774983
Fold 3 IBS: 0.1694839231074501
Fold 4 IBS: 0.1999193220016897
Fold 5 IBS: 0.2267438646767405
[I 2024-04-19 14:41:44,104] Trial 14 finished with value: 0.18589243898046465 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.6604916334814492, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02382938621825248}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.15853645607219177
Fold 2 IBS: 0.20189929103624463
Fold 3 IBS: 0.1608119755898733
Fold 4 IBS: 0.1820464920885326
Fold 5 IBS: 0.21895053955870955
[I 2024-04-19 14:41:46,949] Trial 15 finished with value: 0.18444895086911037 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.9932150048245644, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2762403453179886}. Best is trial 12 with value: 0.17673667335392534.

Fold 1 IBS: 0.1593432071804868
Fold 2 IBS: 0.18470339624712676
Fold 3 IBS: 0.16698177556471644
Fold 4 IBS: 0.180792674404145
Fold 5 IBS: 0.20901591888190207
[I 2024-04-19 14:41:51,793] Trial 16 finished with value: 0.18016739445567542 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.3880731320622045, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14354526791362227}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.1431329027168723
Fold 2 IBS: 0.192606100465973
Fold 3 IBS: 0.16096025503705205
Fold 4 IBS: 0.1800427051718361
Fold 5 IBS: 0.22000275896336244
[I 2024-04-19 14:41:55,576] Trial 17 finished with value: 0.17934894447101918 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 250, 'oob_score': False, 'max_samples': 0.7684587619660335, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07846592181777899}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.15828497701664868
Fold 2 IBS: 0.19094047729173333
Fold 3 IBS: 0.16478431794285392
Fold 4 IBS: 0.18013393126296717
Fold 5 IBS: 0.21372814719524458
[I 2024-04-19 14:42:04,518] Trial 18 finished with value: 0.18157437014188954 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.6155156742664507, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.20223993640525578}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.145874799734907
Fold 2 IBS: 0.19006447697293846
Fold 3 IBS: 0.157631315791433
Fold 4 IBS: 0.1823508976780345
Fold 5 IBS: 0.22218523046185243
[I 2024-04-19 14:42:07,351] Trial 19 finished with value: 0.1796213441278331 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.9278494961686778, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0609880983110333}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.2139806105643647
Fold 2 IBS: 0.22113198382608237
Fold 3 IBS: 0.20548411196241553
Fold 4 IBS: 0.22540867568268688
Fold 5 IBS: 0.22093604111363307
[I 2024-04-19 14:42:07,905] Trial 20 finished with value: 0.2173882846298365 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 11, 'oob_score': False, 'max_samples': 0.20097738776716928, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15255459851620035}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.1428420485538219
Fold 2 IBS: 0.19500500641554602
Fold 3 IBS: 0.16115458912765243
Fold 4 IBS: 0.18061443281138267
Fold 5 IBS: 0.22224502464077223
[I 2024-04-19 14:42:11,965] Trial 21 finished with value: 0.18037222030983507 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 250, 'oob_score': False, 'max_samples': 0.785671932218293, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07161808244089383}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.14296405531408032
Fold 2 IBS: 0.19177179514644152
Fold 3 IBS: 0.15927758125915448
Fold 4 IBS: 0.1808847371851522
Fold 5 IBS: 0.22032216222106416
[I 2024-04-19 14:42:18,890] Trial 22 finished with value: 0.17904406622517854 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 399, 'oob_score': False, 'max_samples': 0.7749562798368443, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10178877697443975}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.14707704217070555
Fold 2 IBS: 0.19296053302861266
Fold 3 IBS: 0.15860815717511959
Fold 4 IBS: 0.1756673928184354
Fold 5 IBS: 0.2186190898465956
[I 2024-04-19 14:42:24,716] Trial 23 finished with value: 0.17858644300789375 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.61065075684492, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11274888594607943}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.1549849803727723
Fold 2 IBS: 0.19343051718377605
Fold 3 IBS: 0.16348725920313262
Fold 4 IBS: 0.1777777283451117
Fold 5 IBS: 0.2137533565000379
[I 2024-04-19 14:42:31,622] Trial 24 finished with value: 0.18068676832096614 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.4692800239107102, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12639289502798687}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.15718380108809815
Fold 2 IBS: 0.1976454051603366
Fold 3 IBS: 0.16226226891683035
Fold 4 IBS: 0.18080242684221
Fold 5 IBS: 0.2162799050847899
[I 2024-04-19 14:42:38,734] Trial 25 finished with value: 0.182834761418453 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 459, 'oob_score': False, 'max_samples': 0.8406026866609635, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.24993364534378779}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.15771873835489275
Fold 2 IBS: 0.19023382194650093
Fold 3 IBS: 0.16365929792020448
Fold 4 IBS: 0.1787939562959426
Fold 5 IBS: 0.2136831208204194
[I 2024-04-19 14:42:47,346] Trial 26 finished with value: 0.18081778706759205 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 387, 'oob_score': True, 'max_samples': 0.5944888086713157, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.18694537021299862}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.14099386282516427
Fold 2 IBS: 0.19582399906742431
Fold 3 IBS: 0.16050960774816828
Fold 4 IBS: 0.18223942802821255
Fold 5 IBS: 0.22402442658444502
[I 2024-04-19 14:42:54,991] Trial 27 finished with value: 0.18071826485068287 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 478, 'oob_score': False, 'max_samples': 0.7174807745789797, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03664484999616455}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.15580004521225302
Fold 2 IBS: 0.20254131551814122
Fold 3 IBS: 0.16107959686305065
Fold 4 IBS: 0.18098672789974116
Fold 5 IBS: 0.2176267905015391
[I 2024-04-19 14:43:00,793] Trial 28 finished with value: 0.18360689519894502 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 329, 'oob_score': False, 'max_samples': 0.9030031356045858, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2406109046286073}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.14071536776497978
Fold 2 IBS: 0.19819914620451093
Fold 3 IBS: 0.16575033532308145
Fold 4 IBS: 0.20889881217652972
Fold 5 IBS: 0.22299803183237982
[I 2024-04-19 14:43:07,600] Trial 29 finished with value: 0.18731233866029634 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 370, 'oob_score': False, 'max_samples': 0.7845045619974171, 'max_features': None, 'min_weight_fraction_leaf': 0.09855221444207077}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.16002774237581896
Fold 2 IBS: 0.18683558884573473
Fold 3 IBS: 0.16577275045657922
Fold 4 IBS: 0.18096610245297262
Fold 5 IBS: 0.21131585347597298
[I 2024-04-19 14:43:14,443] Trial 30 finished with value: 0.18098360752141568 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 432, 'oob_score': False, 'max_samples': 0.48499476459228075, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17165882318444542}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.14661984211302434
Fold 2 IBS: 0.19040617257347817
Fold 3 IBS: 0.15793510062766122
Fold 4 IBS: 0.17751570456376692

Fold 5 IBS: 0.2171431998129361
[I 2024-04-19 14:43:19,585] Trial 31 finished with value: 0.17792400393817337 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.6683617295863028, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11208498314187895}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.14711946655783312
Fold 2 IBS: 0.19006811981061228
Fold 3 IBS: 0.158033991341854
Fold 4 IBS: 0.17821885585463562
Fold 5 IBS: 0.21747675580865514
[I 2024-04-19 14:43:24,739] Trial 32 finished with value: 0.17818343787471802 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.6782402761258088, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10884764482583958}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.1474328186504624
Fold 2 IBS: 0.19259498221393614
Fold 3 IBS: 0.15795841613235134
Fold 4 IBS: 0.17745516090691443
Fold 5 IBS: 0.21625626652249946
[I 2024-04-19 14:43:30,009] Trial 33 finished with value: 0.17833952888523275 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 311, 'oob_score': False, 'max_samples': 0.6380124138892346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1189732582125783}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.15948385941427884
Fold 2 IBS: 0.18769199521863572
Fold 3 IBS: 0.16403388589269344
Fold 4 IBS: 0.18257947334659205
Fold 5 IBS: 0.21450637597218802
[I 2024-04-19 14:43:34,812] Trial 34 finished with value: 0.18165911796887763 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 293, 'oob_score': False, 'max_samples': 0.6726532177661799, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2251916436608714}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.1527840160148196
Fold 2 IBS: 0.19361784261961817
Fold 3 IBS: 0.16037241997963297
Fold 4 IBS: 0.17720989960942962
Fold 5 IBS: 0.21567737421089322
[I 2024-04-19 14:43:39,739] Trial 35 finished with value: 0.17993231048687872 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.6958024881475661, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15526578903551527}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.1495804224236111
Fold 2 IBS: 0.19664350123671276
Fold 3 IBS: 0.15980072072200688
Fold 4 IBS: 0.20836388088105945
Fold 5 IBS: 0.2175031377137174
[I 2024-04-19 14:43:45,995] Trial 36 finished with value: 0.18637833259542153 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 312, 'oob_score': False, 'max_samples': 0.5283332481798079, 'max_features': None, 'min_weight_fraction_leaf': 0.044978813116971286}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.17948718327518784
Fold 2 IBS: 0.1855219493025254
Fold 3 IBS: 0.17917885113266052
Fold 4 IBS: 0.1993029074636634
Fold 5 IBS: 0.21034029430841172
[I 2024-04-19 14:43:51,821] Trial 37 finished with value: 0.1907662370964898 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 358, 'oob_score': False, 'max_samples': 0.6276557954964254, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3061039000862159}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.15661598821174844
Fold 2 IBS: 0.18099374290546613
Fold 3 IBS: 0.16056570273038615
Fold 4 IBS: 0.173520384737327
Fold 5 IBS: 0.2112864793482218
[I 2024-04-19 14:43:53,263] Trial 38 finished with value: 0.17659645958662992 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 61, 'oob_score': False, 'max_samples': 0.5404961912265821, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13164371997111113}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.15279702941122428
Fold 2 IBS: 0.1852912041403366
Fold 3 IBS: 0.16254825455165697
Fold 4 IBS: 0.21563451624021923
Fold 5 IBS: 0.22173066711304368
[I 2024-04-19 14:43:54,939] Trial 39 finished with value: 0.18760033429129613 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 65, 'oob_score': True, 'max_samples': 0.5654897132978893, 'max_features': None, 'min_weight_fraction_leaf': 0.17578457681767043}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.21401738267348
Fold 2 IBS: 0.22212281068128384
Fold 3 IBS: 0.20411785316675118
Fold 4 IBS: 0.2250185725596484
Fold 5 IBS: 0.21786510844986806
[I 2024-04-19 14:43:56,037] Trial 40 finished with value: 0.2166283455062063 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 46, 'oob_score': False, 'max_samples': 0.4892253834151762, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.35210438834668367}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.15673635985911968
Fold 2 IBS: 0.18776720178111944
Fold 3 IBS: 0.1625245998152057
Fold 4 IBS: 0.17509766672928898
Fold 5 IBS: 0.2230481537229173
[I 2024-04-19 14:43:56,927] Trial 41 finished with value: 0.18103479638153022 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 37, 'oob_score': False, 'max_samples': 0.7211499367298436, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13945648129078753}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.16031145123847687
Fold 2 IBS: 0.18489487535508187
Fold 3 IBS: 0.16352949348257792
Fold 4 IBS: 0.1793312795010288
Fold 5 IBS: 0.21962028205847042
[I 2024-04-19 14:43:58,696] Trial 42 finished with value: 0.1815374763271272 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 105, 'oob_score': False, 'max_samples': 0.6618138034584838, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21012440108534947}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.21399267693312002
Fold 2 IBS: 0.2213254436436494
Fold 3 IBS: 0.20493733196399228
Fold 4 IBS: 0.22477485140199815
Fold 5 IBS: 0.21850002024759857
[I 2024-04-19 14:44:03,679] Trial 43 finished with value: 0.2167060648380717 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 313, 'oob_score': False, 'max_samples': 0.5559082679990999, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.15763333718597522
Fold 2 IBS: 0.18946498026638786
Fold 3 IBS: 0.1640954832662605
Fold 4 IBS: 0.18057851328055438
Fold 5 IBS: 0.21214817798156052
[I 2024-04-19 14:44:07,446] Trial 44 finished with value: 0.1807840983961477 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.3922116786764539, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12652167060168643}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.14574358301409038
Fold 2 IBS: 0.18520421873321122
Fold 3 IBS: 0.159750763477992
Fold 4 IBS: 0.17678570525615497
Fold 5 IBS: 0.21918320691794135
[I 2024-04-19 14:44:09,455] Trial 45 finished with value: 0.17733349547987798 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 73, 'oob_score': False, 'max_samples': 0.6437769166332294, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.055766377871647954}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.14276448775275122
Fold 2 IBS: 0.18930516812631212
Fold 3 IBS: 0.16189134421049114
Fold 4 IBS: 0.186974329188472
Fold 5 IBS: 0.221627633907641
[I 2024-04-19 14:44:11,281] Trial 46 finished with value: 0.1805125926371335 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.7501920619277364, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.005596142934225855}. Best is trial 38 with value: 0.17659645958662992.

Fold 1 IBS: 0.16189795049200065
Fold 2 IBS: 0.2002316521231612
Fold 3 IBS: 0.1632441421719029
Fold 4 IBS: 0.17861160833008888
Fold 5 IBS: 0.21900022601901006
[I 2024-04-19 14:44:14,099] Trial 47 finished with value: 0.18459711582723273 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 130, 'oob_score': True, 'max_samples': 0.5217274207107006, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0488148159561139}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.15250696953387413
Fold 2 IBS: 0.1814915271847653
Fold 3 IBS: 0.16047524829592633
Fold 4 IBS: 0.17246364113740187
Fold 5 IBS: 0.2120974321417849
[I 2024-04-19 14:44:15,558] Trial 48 finished with value: 0.1758069636587505 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.5834369548668846, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08607344906290776}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.18399137027492896
Fold 2 IBS: 0.14854679599542248
Fold 3 IBS: 0.16343617668803176
Fold 4 IBS: 0.2223773711931148
Fold 5 IBS: 0.22636174662264597
[I 2024-04-19 14:44:16,044] Trial 49 finished with value: 0.18894269215482878 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 4, 'oob_score': False, 'max_samples': 0.4550345699238961, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.022622499289481568}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.16455265902707955
Fold 2 IBS: 0.1965083208336287
Fold 3 IBS: 0.16451051522511953
Fold 4 IBS: 0.17728891078135361
Fold 5 IBS: 0.2163079500419723
[I 2024-04-19 14:44:17,726] Trial 50 finished with value: 0.18383367118183075 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 69, 'oob_score': False, 'max_samples': 0.5737944419595882, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08451392510353656}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15071625573830963
Fold 2 IBS: 0.18460734052017344
Fold 3 IBS: 0.16552122466638863
Fold 4 IBS: 0.17102996454525876
Fold 5 IBS: 0.21923820221488102
[I 2024-04-19 14:44:18,604] Trial 51 finished with value: 0.1782225975370023 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 30, 'oob_score': False, 'max_samples': 0.6706911247196152, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0605338406261604}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.1445887052296234
Fold 2 IBS: 0.19163667483807043
Fold 3 IBS: 0.15871016442813063
Fold 4 IBS: 0.18096361572381503
Fold 5 IBS: 0.22016081855184566
[I 2024-04-19 14:44:22,560] Trial 52 finished with value: 0.17921199575429703 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 175, 'oob_score': False, 'max_samples': 0.8167276513075985, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09508026921275371}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15128279716921353
Fold 2 IBS: 0.18421225825345372
Fold 3 IBS: 0.16094457240386933
Fold 4 IBS: 0.1747029882196963
Fold 5 IBS: 0.2159672551858531
[I 2024-04-19 14:44:24,315] Trial 53 finished with value: 0.1774219742464172 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.7026582320629128, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1408695751577253}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.14977274691350523
Fold 2 IBS: 0.18449090096080561
Fold 3 IBS: 0.15838810732867745
Fold 4 IBS: 0.17502499987124556
Fold 5 IBS: 0.2177331567520814
[I 2024-04-19 14:44:25,466] Trial 54 finished with value: 0.17708198236526304 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 71, 'oob_score': False, 'max_samples': 0.702094189676402, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13510300196836886}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.21391367727655866
Fold 2 IBS: 0.22130552686371494
Fold 3 IBS: 0.20466557365274923
Fold 4 IBS: 0.2251461971072556
Fold 5 IBS: 0.21815328818720434
[I 2024-04-19 14:44:26,957] Trial 55 finished with value: 0.21663685261749652 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 65, 'oob_score': False, 'max_samples': 0.30569308510483195, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16899129494126047}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.14794352047999373
Fold 2 IBS: 0.1867255826178164
Fold 3 IBS: 0.15781589234508472
Fold 4 IBS: 0.18074045637859848
Fold 5 IBS: 0.22374090490131107
[I 2024-04-19 14:44:28,992] Trial 56 finished with value: 0.1793932713445609 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 6, 'n_estimators': 112, 'oob_score': False, 'max_samples': 0.879444109988293, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13470054580065446}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.153486989472442
Fold 2 IBS: 0.1715548982083498
Fold 3 IBS: 0.16344271985956446
Fold 4 IBS: 0.17712008356884695
Fold 5 IBS: 0.21745433370738948
[I 2024-04-19 14:44:29,772] Trial 57 finished with value: 0.17661180496331857 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 23, 'oob_score': False, 'max_samples': 0.7282100656023017, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07655091511728596}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.16144209598905285
Fold 2 IBS: 0.1815896007749345
Fold 3 IBS: 0.1677595521888748
Fold 4 IBS: 0.17445285608860042
Fold 5 IBS: 0.21548852871481017
[I 2024-04-19 14:44:30,601] Trial 58 finished with value: 0.18014652675125456 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 25, 'oob_score': True, 'max_samples': 0.6004502714901225, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07832314685348683}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.214008383838558
Fold 2 IBS: 0.22125535334545718
Fold 3 IBS: 0.20441570884664864
Fold 4 IBS: 0.2248729650769993
Fold 5 IBS: 0.21859234574887557
[I 2024-04-19 14:44:31,691] Trial 59 finished with value: 0.21662895137130772 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 50, 'oob_score': False, 'max_samples': 0.8039035916436577, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4522260564219586}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15116058308414781
Fold 2 IBS: 0.19010685308448416
Fold 3 IBS: 0.15921555402954687
Fold 4 IBS: 0.1758241519699497
Fold 5 IBS: 0.21941180429322477
[I 2024-04-19 14:44:33,437] Trial 60 finished with value: 0.17914378929227065 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 90, 'oob_score': False, 'max_samples': 0.7454628587344282, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03520152790244757}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.1526413960796701
Fold 2 IBS: 0.18645852391414078
Fold 3 IBS: 0.15822345833190693
Fold 4 IBS: 0.17303496454957462
Fold 5 IBS: 0.21655753966687788
[I 2024-04-19 14:44:35,367] Trial 61 finished with value: 0.17738317650843405 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 82, 'oob_score': False, 'max_samples': 0.6289677761062582, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.059410727521315064}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.1590126948439196
Fold 2 IBS: 0.1898679222749424
Fold 3 IBS: 0.15920693723516843
Fold 4 IBS: 0.17226826221440894
Fold 5 IBS: 0.21733734946090885
[I 2024-04-19 14:44:37,242] Trial 62 finished with value: 0.17953863320586966 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.644088856909565, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05829996975014435}. Best is trial 48 with value: 0.1758069636587505.

Fold 1 IBS: 0.1528522544145544
Fold 2 IBS: 0.1883938076545454
Fold 3 IBS: 0.16059370160325126
Fold 4 IBS: 0.17447839059286202
Fold 5 IBS: 0.21675029793203757
[I 2024-04-19 14:44:39,938] Trial 63 finished with value: 0.17861369043945013 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 121, 'oob_score': False, 'max_samples': 0.5082465499234735, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0848024624668733}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.16166621880208873
Fold 2 IBS: 0.1731632023212488
Fold 3 IBS: 0.1700340266068216
Fold 4 IBS: 0.17478280891532624
Fold 5 IBS: 0.2135771701385966
[I 2024-04-19 14:44:40,637] Trial 64 finished with value: 0.17864468535681638 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.588577514842217, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029696753747332764}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15226980414323507
Fold 2 IBS: 0.1904347394866864
Fold 3 IBS: 0.1605337458277561
Fold 4 IBS: 0.17671108399046023
Fold 5 IBS: 0.21709095294853806
[I 2024-04-19 14:44:43,322] Trial 65 finished with value: 0.17940806527933517 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 151, 'oob_score': False, 'max_samples': 0.4391883761451292, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0019436716080326738}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15087935942359007
Fold 2 IBS: 0.18390851133540326
Fold 3 IBS: 0.16379719608490256
Fold 4 IBS: 0.17968412180473498
Fold 5 IBS: 0.2240244980954591
[I 2024-04-19 14:44:44,835] Trial 66 finished with value: 0.18045873734881798 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 40, 'oob_score': False, 'max_samples': 0.7609560416710082, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06842133552739199}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.1558074789577083
Fold 2 IBS: 0.18722632225085167
Fold 3 IBS: 0.16159655655925312
Fold 4 IBS: 0.16917480755091616
Fold 5 IBS: 0.21354958676323274
[I 2024-04-19 14:44:46,318] Trial 67 finished with value: 0.1774709504163924 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 54, 'oob_score': False, 'max_samples': 0.6267429736060568, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09105542838308342}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.17364872253614366
Fold 2 IBS: 0.15737339829303196
Fold 3 IBS: 0.16379208774353307
Fold 4 IBS: 0.23824328185876364
Fold 5 IBS: 0.24178798668037754
[I 2024-04-19 14:44:46,684] Trial 68 finished with value: 0.19496909542236995 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 3, 'oob_score': False, 'max_samples': 0.7228587248646963, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1890063288879738}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15966698806014762
Fold 2 IBS: 0.18791845126646142
Fold 3 IBS: 0.16261440793417092
Fold 4 IBS: 0.17667786489520682
Fold 5 IBS: 0.2152670823717742
[I 2024-04-19 14:44:48,459] Trial 69 finished with value: 0.1804289589055522 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.543209078895594, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05620109695773104}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.1570428068335575
Fold 2 IBS: 0.18826892481676916
Fold 3 IBS: 0.1597447797237805
Fold 4 IBS: 0.21802893791899966
Fold 5 IBS: 0.22665540976667467
[I 2024-04-19 14:44:50,574] Trial 70 finished with value: 0.1899481718119563 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 2, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.6952614611558205, 'max_features': None, 'min_weight_fraction_leaf': 0.01720171332096783}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15193941721605494
Fold 2 IBS: 0.16957357743067134
Fold 3 IBS: 0.16526614890964453
Fold 4 IBS: 0.1769941217403735
Fold 5 IBS: 0.21733382223407408
[I 2024-04-19 14:44:51,312] Trial 71 finished with value: 0.17622141750616366 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 20, 'oob_score': False, 'max_samples': 0.7017127863520985, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11111990363388535}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15471588553820462
Fold 2 IBS: 0.175595402237788
Fold 3 IBS: 0.16412303860759403
Fold 4 IBS: 0.16805347186108316
Fold 5 IBS: 0.22165913912193214
[I 2024-04-19 14:44:52,156] Trial 72 finished with value: 0.1768293874733204 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 27, 'oob_score': False, 'max_samples': 0.6470567310792946, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10917264390259916}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.1547285443273455
Fold 2 IBS: 0.1705821951734832
Fold 3 IBS: 0.16229298906840267
Fold 4 IBS: 0.17912777778208328
Fold 5 IBS: 0.22090115929133103
[I 2024-04-19 14:44:52,887] Trial 73 finished with value: 0.17752653312852912 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 21, 'oob_score': False, 'max_samples': 0.85019697586559, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15225633959052098}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.14815060765380272
Fold 2 IBS: 0.18241413181965807
Fold 3 IBS: 0.1606712671489576
Fold 4 IBS: 0.17842742048127724
Fold 5 IBS: 0.21697254526971396
[I 2024-04-19 14:44:54,302] Trial 74 finished with value: 0.17732719447468193 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 54, 'oob_score': False, 'max_samples': 0.8047800018974197, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10778874404043165}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.1469867890691063
Fold 2 IBS: 0.184688673863672
Fold 3 IBS: 0.16007700050509954
Fold 4 IBS: 0.1807947800022811
Fold 5 IBS: 0.2186358205264877
[I 2024-04-19 14:44:55,764] Trial 75 finished with value: 0.1782366127933293 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 57, 'oob_score': False, 'max_samples': 0.7983294757920592, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11423443734656469}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15062426985063293
Fold 2 IBS: 0.18275104221698302
Fold 3 IBS: 0.1625841691591965
Fold 4 IBS: 0.17732598337077415
Fold 5 IBS: 0.22160004933715005
[I 2024-04-19 14:44:56,955] Trial 76 finished with value: 0.1789771027869473 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 23, 'oob_score': False, 'max_samples': 0.8808289102754578, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10147448896528224}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.14079003455549632
Fold 2 IBS: 0.2125171943300117
Fold 3 IBS: 0.14779544612407422
Fold 4 IBS: 0.18350856296996673
Fold 5 IBS: 0.2890375336957307
[I 2024-04-19 14:44:57,289] Trial 77 finished with value: 0.19472975433505596 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 1, 'oob_score': False, 'max_samples': 0.9398626428958133, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12925472203884794}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15400882363151763
Fold 2 IBS: 0.18556210083481944
Fold 3 IBS: 0.16306339114640434
Fold 4 IBS: 0.1708618011653215
Fold 5 IBS: 0.21747945160392373
[I 2024-04-19 14:44:58,159] Trial 78 finished with value: 0.17819511367639734 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.73687467988926, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15265100902782777}. Best is trial 48 with value: 0.1758069636587505.

Fold 1 IBS: 0.14805872849452492
Fold 2 IBS: 0.1844394959428906
Fold 3 IBS: 0.1592084284475042
Fold 4 IBS: 0.18049902936533177
Fold 5 IBS: 0.21718793826468474
[I 2024-04-19 14:44:59,422] Trial 79 finished with value: 0.17787872410298725 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 50, 'oob_score': False, 'max_samples': 0.8221486447141937, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10873595340811325}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15361491788372222
Fold 2 IBS: 0.19642745280621465
Fold 3 IBS: 0.16095616456284817
Fold 4 IBS: 0.22665346294232952
Fold 5 IBS: 0.2385594621067867
[I 2024-04-19 14:45:00,314] Trial 80 finished with value: 0.19524229206038027 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 41, 'oob_score': False, 'max_samples': 0.7659640622029704, 'max_features': None, 'min_weight_fraction_leaf': 0.18307985478389613}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.14735125128835888
Fold 2 IBS: 0.17915060038924285
Fold 3 IBS: 0.15735531842391617
Fold 4 IBS: 0.17321978755547224
Fold 5 IBS: 0.21987213301468717
[I 2024-04-19 14:45:02,405] Trial 81 finished with value: 0.17538981813433546 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 100, 'oob_score': False, 'max_samples': 0.5785272262773831, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08332907721465231}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.15686372741336968
Fold 2 IBS: 0.16853213202759856
Fold 3 IBS: 0.16021812296349014
Fold 4 IBS: 0.17850429579193322
Fold 5 IBS: 0.21672769815568546
[I 2024-04-19 14:45:03,028] Trial 82 finished with value: 0.17616919527041544 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 15, 'oob_score': False, 'max_samples': 0.692337944685701, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12395808558776586}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.1619159012046828
Fold 2 IBS: 0.172967625777035
Fold 3 IBS: 0.16616817679060802
Fold 4 IBS: 0.17519719536230008
Fold 5 IBS: 0.2136815813112948
[I 2024-04-19 14:45:03,703] Trial 83 finished with value: 0.17798609608918414 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.5912315360628527, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16341574246423887}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.15219102989663316
Fold 2 IBS: 0.1931818826697778
Fold 3 IBS: 0.16363363156099103
Fold 4 IBS: 0.17684428624029014
Fold 5 IBS: 0.2238144077409702
[I 2024-04-19 14:45:04,648] Trial 84 finished with value: 0.18193304762173246 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 37, 'oob_score': False, 'max_samples': 0.70205360291002, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07361353921311417}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.14779347159431672
Fold 2 IBS: 0.18302126268994853
Fold 3 IBS: 0.15831126962954525
Fold 4 IBS: 0.17419982728982455
Fold 5 IBS: 0.22078364119120042
[I 2024-04-19 14:45:05,851] Trial 85 finished with value: 0.17682189447896707 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 100, 'oob_score': False, 'max_samples': 0.6895741253559994, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12125813943953494}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.15433137239477093
Fold 2 IBS: 0.1845089608942651
Fold 3 IBS: 0.15984805434510146
Fold 4 IBS: 0.17282358032069636
Fold 5 IBS: 0.21614898495352275
[I 2024-04-19 14:45:07,476] Trial 86 finished with value: 0.17753219058167133 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 103, 'oob_score': False, 'max_samples': 0.5659494458629141, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1223612964744446}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.15320761117765
Fold 2 IBS: 0.16911910783647088
Fold 3 IBS: 0.15873999775129646
Fold 4 IBS: 0.17780232042694763
Fold 5 IBS: 0.23317669899032065
[I 2024-04-19 14:45:08,279] Trial 87 finished with value: 0.17840914723653714 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.6525715451525812, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08433804187851579}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.14758802752060363
Fold 2 IBS: 0.18799906778249217
Fold 3 IBS: 0.15830210488322033
Fold 4 IBS: 0.17672037551964595
Fold 5 IBS: 0.21952158849614914
[I 2024-04-19 14:45:11,094] Trial 88 finished with value: 0.17802623284042224 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 142, 'oob_score': False, 'max_samples': 0.5095861562397511, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09677529418377355}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.15761250784722478
Fold 2 IBS: 0.1814054872245867
Fold 3 IBS: 0.16584233239405852
Fold 4 IBS: 0.16767018453439145
Fold 5 IBS: 0.22146798826374336
[I 2024-04-19 14:45:11,917] Trial 89 finished with value: 0.17879970005280094 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 32, 'oob_score': False, 'max_samples': 0.6769922636306419, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1451548892042033}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.14225743331275637
Fold 2 IBS: 0.19311487496624619
Fold 3 IBS: 0.1610077847000388
Fold 4 IBS: 0.2027754944511087
Fold 5 IBS: 0.2208802693629259
[I 2024-04-19 14:45:14,982] Trial 90 finished with value: 0.1840071713586152 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 165, 'oob_score': False, 'max_samples': 0.607664424098672, 'max_features': None, 'min_weight_fraction_leaf': 0.045915615112569044}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.14937090293105826
Fold 2 IBS: 0.1816257040714749
Fold 3 IBS: 0.15849883981566143
Fold 4 IBS: 0.17537352974098414
Fold 5 IBS: 0.21719851706081347
[I 2024-04-19 14:45:16,453] Trial 91 finished with value: 0.17641349872399845 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 62, 'oob_score': False, 'max_samples': 0.6967245615106861, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13205280276099104}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.1484194947660909
Fold 2 IBS: 0.18213568383529022
Fold 3 IBS: 0.15611185913104791
Fold 4 IBS: 0.17651662327051712
Fold 5 IBS: 0.21861518814139327
[I 2024-04-19 14:45:18,774] Trial 92 finished with value: 0.17635976982886786 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 119, 'oob_score': False, 'max_samples': 0.727101025098758, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1216006136267095}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.14859900392331132
Fold 2 IBS: 0.18369789790102672
Fold 3 IBS: 0.15609573510939495
Fold 4 IBS: 0.17628004615360646
Fold 5 IBS: 0.21935184075240627
[I 2024-04-19 14:45:21,151] Trial 93 finished with value: 0.17680490476794913 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 121, 'oob_score': False, 'max_samples': 0.7270159996917693, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12117072039376087}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.15296344734440717
Fold 2 IBS: 0.18695996166974396
Fold 3 IBS: 0.15774179335171973
Fold 4 IBS: 0.17295458943222297
Fold 5 IBS: 0.21759783800196422
[I 2024-04-19 14:45:23,322] Trial 94 finished with value: 0.1776435259600116 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 119, 'oob_score': False, 'max_samples': 0.7242593013645032, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14462066268912804}. Best is trial 81 with value: 0.17538981813433546.

Fold 1 IBS: 0.15162608620389867
Fold 2 IBS: 0.19121869268171396
Fold 3 IBS: 0.15836366628343707
Fold 4 IBS: 0.17826802865577213
Fold 5 IBS: 0.21920067113279704
[I 2024-04-19 14:45:25,673] Trial 95 finished with value: 0.17973542899152378 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 137, 'oob_score': False, 'max_samples': 0.772556078583092, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1631127999140187}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.16352525950573188
Fold 2 IBS: 0.18296538734873047
Fold 3 IBS: 0.16292268280332917
Fold 4 IBS: 0.18527611582158968
Fold 5 IBS: 0.2102778391441335
[I 2024-04-19 14:45:26,983] Trial 96 finished with value: 0.18099345692470292 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.7421638972276217, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27874856663178627}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.14512419897865786
Fold 2 IBS: 0.18937606809462942
Fold 3 IBS: 0.1579550636324128
Fold 4 IBS: 0.178991393386047
Fold 5 IBS: 0.21788411235607089
[I 2024-04-19 14:45:30,384] Trial 97 finished with value: 0.1778661672895636 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 194, 'oob_score': False, 'max_samples': 0.7192270960501082, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0897267677897641}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.1622971916445904
Fold 2 IBS: 0.200805063034386
Fold 3 IBS: 0.16315956100577864
Fold 4 IBS: 0.17924308868529154
Fold 5 IBS: 0.2205431637812717
[I 2024-04-19 14:45:32,621] Trial 98 finished with value: 0.18520961363026364 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 124, 'oob_score': False, 'max_samples': 0.7488605581621807, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13339402708275627}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.14463564057781775
Fold 2 IBS: 0.19495198337921166
Fold 3 IBS: 0.16337600930555288
Fold 4 IBS: 0.18532359128908554
Fold 5 IBS: 0.2233191921995693
[I 2024-04-19 14:45:34,019] Trial 99 finished with value: 0.18232128335024742 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 81, 'oob_score': False, 'max_samples': 0.7892849711265231, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07204462112879095}. Best is trial 81 with value: 0.17538981813433546.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.17538981813433546], datetime_start=datetime.datetime(2024, 4, 19, 14, 45, 0, 383562), datetime_complete=datetime.datetime(2024, 4, 19, 14, 45, 2, 403969), params={'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 100, 'oob_score': False, 'max_samples': 0.5785272262773831, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08332907721465231}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=81, value=None)


* Best Score for IBS:
 0.17538981813433546

In [55]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [56]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.871
train_ibs:  0.175

#### Test

In [57]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [58]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=14, max_features='auto', max_leaf_nodes=15,
                     max_samples=0.9504102015210659, min_samples_leaf=2,
                     min_samples_split=9,
                     min_weight_fraction_leaf=0.005622697057305325,
                     n_estimators=144, random_state=123, warm_start=True)

test_cindex:  0.618

RandomSurvivalForest(max_depth=6, max_leaf_nodes=10,
                     max_samples=0.5785272262773831, min_samples_leaf=8,
                     min_samples_split=11,
                     min_weight_fraction_leaf=0.08332907721465231,
                     random_state=123)

test_ibs:  0.223

In [59]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [60]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [61]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:45:35,658] A new study created in memory with name: no-name-e0468ef5-6aac-429a-b49f-ab478f5cd50e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:45:37,263] Trial 0 finished with value: 0.7766254315304948 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7766254315304948.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:45:41,338] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7766254315304948.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:45:50,718] Trial 2 finished with value: 0.7569164638091417 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7766254315304948.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:45:51,574] Trial 3 finished with value: 0.7635299204691358 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7766254315304948.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:45:54,191] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7766254315304948.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:45:57,178] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7766254315304948.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:45:59,055] Trial 6 finished with value: 0.7772891060912281 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.7772891060912281.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 14:46:03,727] Trial 7 finished with value: 0.7519117264565756 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.7772891060912281.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6291079812206573
[I 2024-04-19 14:46:03,974] Trial 8 finished with value: 0.7605913297992336 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.7772891060912281.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:46:13,850] Trial 9 finished with value: 0.7628491337417315 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.7772891060912281.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:46:17,433] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.7772891060912281.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.765625
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.6549295774647887
[I 2024-04-19 14:46:18,687] Trial 11 finished with value: 0.7715029724308078 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.7772891060912281.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6854460093896714
[I 2024-04-19 14:46:21,405] Trial 12 finished with value: 0.786055160528368 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:46:23,484] Trial 13 finished with value: 0.7678260059919524 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638831587887255, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:46:25,483] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:46:26,807] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 268, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.33571048327918607, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 12 with value: 0.786055160528368.

Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:46:29,322] Trial 16 finished with value: 0.7660839887017223 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6535355702555379, 'min_weight_fraction_leaf': 0.1906011147608997}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8333333333333334
Fold 2 C-index: 0.7834821428571429
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6314553990610329
[I 2024-04-19 14:46:31,184] Trial 17 finished with value: 0.7725320603816497 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.903993543626621, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.765625
Fold 3 C-index: 0.821078431372549
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6384976525821596
[I 2024-04-19 14:46:31,888] Trial 18 finished with value: 0.7707238158922624 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.38500398118655316, 'min_weight_fraction_leaf': 0.0735015574561402}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.7869198312236287
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:46:32,601] Trial 19 finished with value: 0.7702023650511113 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.639253673774636, 'min_weight_fraction_leaf': 0.037408326362835864}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.821078431372549
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:46:34,213] Trial 20 finished with value: 0.7705868341436966 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8892982712995542, 'min_weight_fraction_leaf': 0.18720118160246144}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 14:46:36,026] Trial 21 finished with value: 0.77730861210268 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7247491835588253, 'min_weight_fraction_leaf': 0.10612931382459131}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.7953586497890295
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:46:38,078] Trial 22 finished with value: 0.7727018170758798 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 447, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5833816310769062, 'min_weight_fraction_leaf': 0.10633258814265802}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:46:40,139] Trial 23 finished with value: 0.7784699433429022 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7310231778151053, 'min_weight_fraction_leaf': 0.013477785996217753}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 14:46:41,951] Trial 24 finished with value: 0.787567401918222 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 390, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7197381019543724, 'min_weight_fraction_leaf': 0.04604331935587166}. Best is trial 24 with value: 0.787567401918222.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 14:46:43,337] Trial 25 finished with value: 0.7919233215012451 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 313, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.876735501897294, 'min_weight_fraction_leaf': 0.04480374820150253}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 14:46:49,110] Trial 26 finished with value: 0.7554146737302354 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 318, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8701610988033271, 'min_weight_fraction_leaf': 0.06018738864873575}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 14:46:50,578] Trial 27 finished with value: 0.7556220783261358 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8371227222322273, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:46:51,652] Trial 28 finished with value: 0.7851334631812174 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 204, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9575314635792546, 'min_weight_fraction_leaf': 0.04083350928166579}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:46:53,508] Trial 29 finished with value: 0.780411221645176 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9279195082568442, 'min_weight_fraction_leaf': 0.07252328844834334}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:46:54,806] Trial 30 finished with value: 0.7755367694331334 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 225, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7131454297229517, 'min_weight_fraction_leaf': 0.09210752384530588}. Best is trial 25 with value: 0.7919233215012451.

Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:46:56,321] Trial 31 finished with value: 0.7852867552230053 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 204, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8438862458923003, 'min_weight_fraction_leaf': 0.03902180415717787}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:46:57,757] Trial 32 finished with value: 0.7827112716348635 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8332385731539106, 'min_weight_fraction_leaf': 0.027416055450601745}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:46:58,492] Trial 33 finished with value: 0.766409530310771 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 158, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8572071692366157, 'min_weight_fraction_leaf': 0.06748325843685211}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8095238095238095
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:46:59,655] Trial 34 finished with value: 0.7539146675785664 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 239, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.997814568983562, 'min_weight_fraction_leaf': 0.12436915097441914}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 14:47:01,353] Trial 35 finished with value: 0.7606421761235977 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 7, 'n_estimators': 139, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.912266890066162, 'min_weight_fraction_leaf': 0.24235302278015497}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 14:47:06,812] Trial 36 finished with value: 0.7520315960384705 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 339, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6967226649720313, 'min_weight_fraction_leaf': 0.048301638211746496}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6854460093896714
[I 2024-04-19 14:47:08,509] Trial 37 finished with value: 0.787043732021407 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7790217874657425, 'min_weight_fraction_leaf': 0.0860355981837791}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:47:09,933] Trial 38 finished with value: 0.7696677376359059 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 292, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.48791124460782864, 'min_weight_fraction_leaf': 0.0801615592088104}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 14:47:16,588] Trial 39 finished with value: 0.7536168626756364 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 364, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7898418765076363, 'min_weight_fraction_leaf': 0.11157601621505114}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 14:47:17,981] Trial 40 finished with value: 0.7635654829607169 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6333788332887427, 'min_weight_fraction_leaf': 0.16594433686505833}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:47:18,961] Trial 41 finished with value: 0.785989441806642 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 179, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7620488800258761, 'min_weight_fraction_leaf': 0.027676500905582244}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:47:19,763] Trial 42 finished with value: 0.7907671275288182 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 91, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7754857501009593, 'min_weight_fraction_leaf': 0.022639239663285127}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 14:47:20,346] Trial 43 finished with value: 0.8018034514086029 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 86, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9378855450065084, 'min_weight_fraction_leaf': 0.017387160098159254}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:47:20,835] Trial 44 finished with value: 0.7626036408663857 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 73, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7976715718652303, 'min_weight_fraction_leaf': 0.13247133428022156}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 14:47:21,247] Trial 45 finished with value: 0.765601201865858 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 82, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7559143250033664, 'min_weight_fraction_leaf': 0.08994451801308195}. Best is trial 43 with value: 0.8018034514086029.

Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7790178571428571
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 14:47:21,565] Trial 46 finished with value: 0.7898793033761585 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 15, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6678646968753718, 'min_weight_fraction_leaf': 0.05891279435507671}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.7987012987012987
Fold 2 C-index: 0.6941964285714286
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-19 14:47:21,845] Trial 47 finished with value: 0.7323875186349034 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 2, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6679397381454423, 'min_weight_fraction_leaf': 0.02148191909872358}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7254464285714286
Fold 3 C-index: 0.821078431372549
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.6408450704225352
[I 2024-04-19 14:47:22,511] Trial 48 finished with value: 0.7610259615240121 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 49, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9463412504225213, 'min_weight_fraction_leaf': 0.3399047172380002}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:47:23,238] Trial 49 finished with value: 0.7801271498891135 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 106, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5836783796663053, 'min_weight_fraction_leaf': 0.05902698170708356}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:47:23,665] Trial 50 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5323261217237781, 'min_weight_fraction_leaf': 0.2737091230315036}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8116883116883117
Fold 2 C-index: 0.6361607142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.5915492957746479
[I 2024-04-19 14:47:24,013] Trial 51 finished with value: 0.726916646231095 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 1, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8110439696436671, 'min_weight_fraction_leaf': 0.05105168315138192}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:47:24,540] Trial 52 finished with value: 0.7879600483607436 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 117, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7483106974669713, 'min_weight_fraction_leaf': 0.002297495788120843}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:47:25,308] Trial 53 finished with value: 0.7890625820742729 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 129, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7007511417838951, 'min_weight_fraction_leaf': 0.0013747037483597818}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:47:26,058] Trial 54 finished with value: 0.78448034520215 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 119, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6161650292854159, 'min_weight_fraction_leaf': 0.005195745122904563}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 14:47:26,744] Trial 55 finished with value: 0.7860694265550432 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 81, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6836250238686925, 'min_weight_fraction_leaf': 0.01968098833169956}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:47:27,547] Trial 56 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 133, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7500159556912651, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8376623376623377
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6408450704225352
[I 2024-04-19 14:47:27,909] Trial 57 finished with value: 0.7602738453726035 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 30, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8823994002805076, 'min_weight_fraction_leaf': 0.004687560117461877}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 14:47:29,665] Trial 58 finished with value: 0.7510126441539192 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 98, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6087241852990865, 'min_weight_fraction_leaf': 0.025994916170817187}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:47:30,585] Trial 59 finished with value: 0.7670460140976276 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 64, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6724790116541645, 'min_weight_fraction_leaf': 5.044215225983792e-05}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 14:47:31,456] Trial 60 finished with value: 0.7779774239312087 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 172, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8154018570576436, 'min_weight_fraction_leaf': 0.06061652770492859}. Best is trial 43 with value: 0.8018034514086029.

Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6901408450704225
[I 2024-04-19 14:47:31,990] Trial 61 finished with value: 0.7980460426767831 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 93, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7308291502564501, 'min_weight_fraction_leaf': 0.041167639802806265}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:47:32,540] Trial 62 finished with value: 0.7774861913192643 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 95, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.537144845100827, 'min_weight_fraction_leaf': 0.029116858539921832}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 14:47:33,014] Trial 63 finished with value: 0.7972972460998532 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 126, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7283633534707481, 'min_weight_fraction_leaf': 0.04541440737984728}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 14:47:33,154] Trial 64 finished with value: 0.7704534152840053 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 26, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7017441977663603, 'min_weight_fraction_leaf': 0.1020463678010651}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.829004329004329
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6314553990610329
[I 2024-04-19 14:47:33,820] Trial 65 finished with value: 0.773451973801563 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 137, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9333430776387115, 'min_weight_fraction_leaf': 0.4134291052499814}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:47:34,256] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 65, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8707697064569014, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:47:35,276] Trial 67 finished with value: 0.7876236479778057 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 155, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9023529495393777, 'min_weight_fraction_leaf': 0.07201355123747381}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:47:35,786] Trial 68 finished with value: 0.7852435105227362 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 46, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.22939188072225208, 'min_weight_fraction_leaf': 0.04126730233993369}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 14:47:36,286] Trial 69 finished with value: 0.8011773897065917 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 88, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7273515106813977, 'min_weight_fraction_leaf': 0.05284452070827268}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8333333333333334
Fold 2 C-index: 0.6897321428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7827004219409283
Fold 5 C-index: 0.636150234741784
[I 2024-04-19 14:47:39,163] Trial 70 finished with value: 0.7511283246138534 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 15, 'n_estimators': 88, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.834906956075858, 'min_weight_fraction_leaf': 0.05486511182190622}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.821078431372549
Fold 4 C-index: 0.7827004219409283
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:47:40,039] Trial 71 finished with value: 0.7749144347685427 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 128, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6455263748184987, 'min_weight_fraction_leaf': 0.01406965747820355}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:47:40,627] Trial 72 finished with value: 0.7819923966280138 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 59, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7308740974688083, 'min_weight_fraction_leaf': 0.040892682928865644}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8357843137254902
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:47:41,697] Trial 73 finished with value: 0.7775865438235133 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 184, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7768223340027555, 'min_weight_fraction_leaf': 0.07544218623936463}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 14:47:42,525] Trial 74 finished with value: 0.8014094733340589 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 105, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.970607413962485, 'min_weight_fraction_leaf': 0.03242680345175293}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7911392405063291
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 14:47:43,276] Trial 75 finished with value: 0.769099741673035 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 106, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9841844662150304, 'min_weight_fraction_leaf': 0.09823806741925431}. Best is trial 43 with value: 0.8018034514086029.

Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:47:43,712] Trial 76 finished with value: 0.7745536932985807 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 31, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9239434202011361, 'min_weight_fraction_leaf': 0.11933626233578211}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:47:44,057] Trial 77 finished with value: 0.7855277187618592 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 15, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9645534638498757, 'min_weight_fraction_leaf': 0.033013807411716084}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:47:44,653] Trial 78 finished with value: 0.7916652629625084 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 74, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.81446503479005, 'min_weight_fraction_leaf': 0.05858385951756177}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8095238095238095
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8308823529411765
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:47:45,323] Trial 79 finished with value: 0.7721250842108995 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 76, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8240784041644889, 'min_weight_fraction_leaf': 0.08113175369933603}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7869198312236287
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:47:46,207] Trial 80 finished with value: 0.7819334243122038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 165, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8621383905551123, 'min_weight_fraction_leaf': 0.017981219707984775}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6901408450704225
[I 2024-04-19 14:47:46,912] Trial 81 finished with value: 0.7894873545294875 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 94, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8902326274844327, 'min_weight_fraction_leaf': 0.05660051590199361}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8455882352941176
Fold 4 C-index: 0.7911392405063291
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 14:47:47,729] Trial 82 finished with value: 0.7796262249936361 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 58, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8021748345495684, 'min_weight_fraction_leaf': 0.06326319264983851}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 14:47:48,770] Trial 83 finished with value: 0.7815602149302321 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 108, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9670037749682452, 'min_weight_fraction_leaf': 0.04727227790003351}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8095238095238095
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7953586497890295
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:47:49,264] Trial 84 finished with value: 0.7673175282771336 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 42, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7396870843483736, 'min_weight_fraction_leaf': 0.08898518693898708}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.704225352112676
[I 2024-04-19 14:47:50,173] Trial 85 finished with value: 0.8041070984788672 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 70, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8476085844987526, 'min_weight_fraction_leaf': 0.03326421194628475}. Best is trial 85 with value: 0.8041070984788672.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6854460093896714
[I 2024-04-19 14:47:51,034] Trial 86 finished with value: 0.7870532410033658 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 144, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8496294339105882, 'min_weight_fraction_leaf': 0.035555616803382525}. Best is trial 85 with value: 0.8041070984788672.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.6986607142857143
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 14:47:55,681] Trial 87 finished with value: 0.7532383759959518 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 14, 'n_estimators': 264, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.93595530867521, 'min_weight_fraction_leaf': 0.016380716801170345}. Best is trial 85 with value: 0.8041070984788672.
Fold 1 C-index: 0.816017316017316
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.7742616033755274
Fold 5 C-index: 0.6408450704225352
[I 2024-04-19 14:47:56,686] Trial 88 finished with value: 0.7531225570667172 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 77, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9071908205264589, 'min_weight_fraction_leaf': 0.23418814674021785}. Best is trial 85 with value: 0.8041070984788672.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.7869198312236287
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:47:57,353] Trial 89 finished with value: 0.7814385432611918 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 124, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7706846873578284, 'min_weight_fraction_leaf': 0.048298161975799433}. Best is trial 85 with value: 0.8041070984788672.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:47:57,943] Trial 90 finished with value: 0.7721818359104285 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 89, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9998511806246988, 'min_weight_fraction_leaf': 0.07267615605976058}. Best is trial 85 with value: 0.8041070984788672.

Fold 1 C-index: 0.8246753246753247
Fold 2 C-index: 0.796875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:47:58,269] Trial 91 finished with value: 0.790008574683054 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 15, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7849096528006341, 'min_weight_fraction_leaf': 0.030415157337554115}. Best is trial 85 with value: 0.8041070984788672.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 14:47:58,793] Trial 92 finished with value: 0.8006289355074921 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 72, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7842305799006279, 'min_weight_fraction_leaf': 0.031581852960146074}. Best is trial 85 with value: 0.8041070984788672.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 14:47:59,613] Trial 93 finished with value: 0.8089579504713926 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 102, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8797548257330544, 'min_weight_fraction_leaf': 0.016155917164710452}. Best is trial 93 with value: 0.8089579504713926.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7089201877934272
[I 2024-04-19 14:48:00,269] Trial 94 finished with value: 0.8054066212296682 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 69, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8684665766132931, 'min_weight_fraction_leaf': 0.01520501163055084}. Best is trial 93 with value: 0.8089579504713926.
Fold 1 C-index: 0.8095238095238095
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7089201877934272
[I 2024-04-19 14:48:01,106] Trial 95 finished with value: 0.7970800167098396 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 103, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8814092235554671, 'min_weight_fraction_leaf': 0.011818046281800824}. Best is trial 93 with value: 0.8089579504713926.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 14:48:01,831] Trial 96 finished with value: 0.8016186976095158 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 110, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8863766024930939, 'min_weight_fraction_leaf': 0.016663029023952246}. Best is trial 93 with value: 0.8089579504713926.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8259803921568627
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:48:02,821] Trial 97 finished with value: 0.7746861990553852 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 112, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8530408080789232, 'min_weight_fraction_leaf': 0.012237463120232602}. Best is trial 93 with value: 0.8089579504713926.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 14:48:03,463] Trial 98 finished with value: 0.8160429569565227 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 68, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9554816381741302, 'min_weight_fraction_leaf': 0.026333169142875475}. Best is trial 98 with value: 0.8160429569565227.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.704225352112676
[I 2024-04-19 14:48:03,903] Trial 99 finished with value: 0.81059250622079 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 67, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9572705727248035, 'min_weight_fraction_leaf': 0.03267161037635903}. Best is trial 98 with value: 0.8160429569565227.

[I 2024-04-19 14:48:04,093] A new study created in memory with name: no-name-ff31bca3-235a-484a-b30e-5d29e8553af4

* Best trial for C-index:
 FrozenTrial(number=98, state=TrialState.COMPLETE, values=[0.8160429569565227], datetime_start=datetime.datetime(2024, 4, 19, 14, 48, 2, 875701), datetime_complete=datetime.datetime(2024, 4, 19, 14, 48, 3, 463538), params={'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 68, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9554816381741302, 'min_weight_fraction_leaf': 0.026333169142875475}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=98, value=None)


* Best Score for C-index:
 0.8160429569565227

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.15331808879740202
Fold 2 IBS: 0.222926809068137
Fold 3 IBS: 0.16873053393274628
Fold 4 IBS: 0.15901193437964076
Fold 5 IBS: 0.23009035684346238
[I 2024-04-19 14:48:09,376] Trial 0 finished with value: 0.18681554460427768 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.18681554460427768.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-19 14:48:18,500] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.18681554460427768.
Fold 1 IBS: 0.168869624633049
Fold 2 IBS: 0.2095319681530086
Fold 3 IBS: 0.17387462883519067
Fold 4 IBS: 0.17607018679729425
Fold 5 IBS: 0.21823846331824107
[I 2024-04-19 14:48:26,402] Trial 2 finished with value: 0.1893169743473567 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.18681554460427768.
Fold 1 IBS: 0.1702791557232537
Fold 2 IBS: 0.20661953446628545
Fold 3 IBS: 0.17493262806105533
Fold 4 IBS: 0.1766439453303021
Fold 5 IBS: 0.2175305564424761
[I 2024-04-19 14:48:29,126] Trial 3 finished with value: 0.18920116400467454 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.18681554460427768.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-19 14:48:36,188] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.18681554460427768.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-19 14:48:38,894] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.18681554460427768.
Fold 1 IBS: 0.15379016945716226
Fold 2 IBS: 0.22217988049119108
Fold 3 IBS: 0.16821042912650647
Fold 4 IBS: 0.15825490490421495
Fold 5 IBS: 0.23095581916469532
[I 2024-04-19 14:48:45,887] Trial 6 finished with value: 0.18667824062875404 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.18667824062875404.
Fold 1 IBS: 0.15797367672389057
Fold 2 IBS: 0.2105735852385178
Fold 3 IBS: 0.17043395686966864
Fold 4 IBS: 0.16710050505563723
Fold 5 IBS: 0.22255440287284375
[I 2024-04-19 14:48:49,941] Trial 7 finished with value: 0.1857272253521116 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.1706840906561748
Fold 2 IBS: 0.20832030276387237
Fold 3 IBS: 0.17670034233157944
Fold 4 IBS: 0.17781636300010176
Fold 5 IBS: 0.21997982323680884
[I 2024-04-19 14:48:50,929] Trial 8 finished with value: 0.19070018439770745 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.1823139020794423
Fold 2 IBS: 0.20738012964651717
Fold 3 IBS: 0.18186365068989283
Fold 4 IBS: 0.19310256206045615
Fold 5 IBS: 0.21422428265990107
[I 2024-04-19 14:48:58,954] Trial 9 finished with value: 0.19577690542724194 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.2139976337400846
Fold 2 IBS: 0.22078850566211056
Fold 3 IBS: 0.20468678510920732
Fold 4 IBS: 0.2246562137512858
Fold 5 IBS: 0.21763185598455237
[I 2024-04-19 14:49:01,425] Trial 10 finished with value: 0.21635219884944812 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 98, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.21752764504502275, 'min_weight_fraction_leaf': 0.20722772178871404}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.15257958360664922
Fold 2 IBS: 0.22451002050856136
Fold 3 IBS: 0.16796200044670512
Fold 4 IBS: 0.15943292856491
Fold 5 IBS: 0.2314772049086562
[I 2024-04-19 14:49:05,549] Trial 11 finished with value: 0.18719234760709638 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 296, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.17619400334161145
Fold 2 IBS: 0.20715079705418202
Fold 3 IBS: 0.17809607429453234
Fold 4 IBS: 0.18249119187305823
Fold 5 IBS: 0.21663453645181943
[I 2024-04-19 14:49:08,801] Trial 12 finished with value: 0.19211332060304068 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 214, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.2683866363584086, 'min_weight_fraction_leaf': 0.0005781139040304361}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.15947567965793366
Fold 2 IBS: 0.22354986457490156
Fold 3 IBS: 0.16956362213133028
Fold 4 IBS: 0.16329441120378663
Fold 5 IBS: 0.2292440849614746
[I 2024-04-19 14:49:16,344] Trial 13 finished with value: 0.18902553250588533 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638655338226161, 'min_weight_fraction_leaf': 0.16922765932800388}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.2139242004833309
Fold 2 IBS: 0.22063339342953675
Fold 3 IBS: 0.20543327096798636
Fold 4 IBS: 0.22521858786986126
Fold 5 IBS: 0.2170716312878449
[I 2024-04-19 14:49:21,237] Trial 14 finished with value: 0.21645621680771204 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.07318050492704681}. Best is trial 7 with value: 0.1857272253521116.

Fold 1 IBS: 0.21397899766980513
Fold 2 IBS: 0.22119491249175238
Fold 3 IBS: 0.20501286878802247
Fold 4 IBS: 0.2247338457207233
Fold 5 IBS: 0.21814874287282784
[I 2024-04-19 14:49:27,435] Trial 15 finished with value: 0.2166138735086262 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 14, 'max_depth': 15, 'n_estimators': 379, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.33528007217980527, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.1513347225448683
Fold 2 IBS: 0.2222444435875969
Fold 3 IBS: 0.16799009245760868
Fold 4 IBS: 0.15755653814584675
Fold 5 IBS: 0.23161411047983665
[I 2024-04-19 14:49:36,455] Trial 16 finished with value: 0.18614798144315142 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 493, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6536453784519287, 'min_weight_fraction_leaf': 0.03818486015953676}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.17617003718377808
Fold 2 IBS: 0.20294108117243945
Fold 3 IBS: 0.17742316755687063
Fold 4 IBS: 0.18785483606044212
Fold 5 IBS: 0.21375615024178732
[I 2024-04-19 14:49:44,930] Trial 17 finished with value: 0.19162905444306352 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 493, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8884180578214513, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.16865902885414047
Fold 2 IBS: 0.19944340022849147
Fold 3 IBS: 0.17297763434162985
Fold 4 IBS: 0.17989185130999089
Fold 5 IBS: 0.22524482271210727
[I 2024-04-19 14:49:45,871] Trial 18 finished with value: 0.189243347489272 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 23, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.635457264859255, 'min_weight_fraction_leaf': 0.18605021589393816}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.15424481414316563
Fold 2 IBS: 0.2212212157229542
Fold 3 IBS: 0.1683518141271408
Fold 4 IBS: 0.15823989006317227
Fold 5 IBS: 0.23060481783556233
[I 2024-04-19 14:49:49,742] Trial 19 finished with value: 0.18653251037839905 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 141, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6831327987735002, 'min_weight_fraction_leaf': 0.05567354271014018}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.17488320088597403
Fold 2 IBS: 0.2094654753630573
Fold 3 IBS: 0.17895757287032865
Fold 4 IBS: 0.18123361279768233
Fold 5 IBS: 0.21774048491415354
[I 2024-04-19 14:49:54,485] Trial 20 finished with value: 0.19245606936623919 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 242, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8746512426406728, 'min_weight_fraction_leaf': 0.1092354718367409}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.15378605399995207
Fold 2 IBS: 0.22093132354955883
Fold 3 IBS: 0.1679875038588519
Fold 4 IBS: 0.15750989935836693
Fold 5 IBS: 0.23209317117666156
[I 2024-04-19 14:49:56,908] Trial 21 finished with value: 0.18646159038867824 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 112, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6647253837986332, 'min_weight_fraction_leaf': 0.0514767164471617}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.15390173460785092
Fold 2 IBS: 0.22339921499689297
Fold 3 IBS: 0.16936165765323366
Fold 4 IBS: 0.15792320213465816
Fold 5 IBS: 0.23290418382799433
[I 2024-04-19 14:49:58,639] Trial 22 finished with value: 0.187497998644126 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 72, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7012203687886621, 'min_weight_fraction_leaf': 0.041265940360740716}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.16481494551087472
Fold 2 IBS: 0.21400919181835748
Fold 3 IBS: 0.17231389309603723
Fold 4 IBS: 0.17004175880120334
Fold 5 IBS: 0.22166234418445716
[I 2024-04-19 14:50:04,047] Trial 23 finished with value: 0.18856842668218599 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 332, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.44236466344473546, 'min_weight_fraction_leaf': 0.13411382575564806}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.14989033038186125
Fold 2 IBS: 0.22347622030948472
Fold 3 IBS: 0.16746937404638448
Fold 4 IBS: 0.15684196724060495
Fold 5 IBS: 0.23314467495929328
[I 2024-04-19 14:50:07,099] Trial 24 finished with value: 0.18616451338752574 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 157, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8787281207754778, 'min_weight_fraction_leaf': 0.04917014729703097}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.17524520008249128
Fold 2 IBS: 0.2069363358295505
Fold 3 IBS: 0.1781979071739044
Fold 4 IBS: 0.1818142113750091
Fold 5 IBS: 0.21708691401871724
[I 2024-04-19 14:50:09,847] Trial 25 finished with value: 0.19185611369593453 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 179, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8972910445185178, 'min_weight_fraction_leaf': 0.24231962244941954}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.1525093976343376
Fold 2 IBS: 0.2243407574335712
Fold 3 IBS: 0.16893011944691214
Fold 4 IBS: 0.15892740602279673
Fold 5 IBS: 0.23068081255511538
[I 2024-04-19 14:50:15,664] Trial 26 finished with value: 0.18707769861854662 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 248, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8529504122040699, 'min_weight_fraction_leaf': 0.09666572299489368}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.18231155824547537
Fold 2 IBS: 0.25824896647503714
Fold 3 IBS: 0.1689307270871101
Fold 4 IBS: 0.15329557771600297
Fold 5 IBS: 0.30065918160355315
[I 2024-04-19 14:50:16,422] Trial 27 finished with value: 0.21268920222543578 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 1, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9946457249155709, 'min_weight_fraction_leaf': 0.031166036698169683}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.1719212396011742
Fold 2 IBS: 0.2559012768635498
Fold 3 IBS: 0.16710877095920373
Fold 4 IBS: 0.16244867407963692
Fold 5 IBS: 0.23995002223176268
[I 2024-04-19 14:50:19,639] Trial 28 finished with value: 0.19946599674706547 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 160, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9484789033538706, 'min_weight_fraction_leaf': 0.16298179421858316}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.16403135832618315
Fold 2 IBS: 0.20899818717971916
Fold 3 IBS: 0.17288618041423
Fold 4 IBS: 0.1731834369538113
Fold 5 IBS: 0.2179090439033289
[I 2024-04-19 14:50:26,042] Trial 29 finished with value: 0.1874016413554545 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 337, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.73650015077135, 'min_weight_fraction_leaf': 0.08962850536510933}. Best is trial 7 with value: 0.1857272253521116.

Fold 1 IBS: 0.1585529260071
Fold 2 IBS: 0.218153010449042
Fold 3 IBS: 0.17021896151952115
Fold 4 IBS: 0.16343124711768475
Fold 5 IBS: 0.2311751417053347
[I 2024-04-19 14:50:28,933] Trial 30 finished with value: 0.18830625735973652 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 116, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8258632202024414, 'min_weight_fraction_leaf': 0.20241101766143602}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.15420880459120728
Fold 2 IBS: 0.22137976081415967
Fold 3 IBS: 0.16774275391760834
Fold 4 IBS: 0.15688252726853427
Fold 5 IBS: 0.23380379197752338
[I 2024-04-19 14:50:31,186] Trial 31 finished with value: 0.18680352771380657 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 108, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6146551753104116, 'min_weight_fraction_leaf': 0.03593211426266471}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.15579896140988755
Fold 2 IBS: 0.2222407852093063
Fold 3 IBS: 0.1692610730939769
Fold 4 IBS: 0.1606323064011862
Fold 5 IBS: 0.2308936445065212
[I 2024-04-19 14:50:35,136] Trial 32 finished with value: 0.1877653541241756 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 220, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7415269845526361, 'min_weight_fraction_leaf': 0.08044503719481133}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.1546873596354472
Fold 2 IBS: 0.22227957519958622
Fold 3 IBS: 0.1687522326739948
Fold 4 IBS: 0.15908052920324967
Fold 5 IBS: 0.2322216282397852
[I 2024-04-19 14:50:36,803] Trial 33 finished with value: 0.18740426499041263 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 77, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5078862514536379, 'min_weight_fraction_leaf': 0.057248685594014664}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.1355139041880366
Fold 2 IBS: 0.2329599823177983
Fold 3 IBS: 0.16632631710096546
Fold 4 IBS: 0.16103445768167077
Fold 5 IBS: 0.2330686919937605
[I 2024-04-19 14:50:43,690] Trial 34 finished with value: 0.18578067065644635 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 404, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.02890474097529236}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.15421148476075414
Fold 2 IBS: 0.2450546663166637
Fold 3 IBS: 0.16500281729172725
Fold 4 IBS: 0.15525641050084926
Fold 5 IBS: 0.23927895639791555
[I 2024-04-19 14:50:54,280] Trial 35 finished with value: 0.19176086705358197 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 417, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9010743484673644, 'min_weight_fraction_leaf': 0.025515731497252444}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.14579782574171335
Fold 2 IBS: 0.24019828814288097
Fold 3 IBS: 0.16528410789334966
Fold 4 IBS: 0.15647595192127317
Fold 5 IBS: 0.2362427262131217
[I 2024-04-19 14:51:02,431] Trial 36 finished with value: 0.18879977998246777 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 456, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.936140510899361, 'min_weight_fraction_leaf': 0.12300175093789192}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.16545965140525298
Fold 2 IBS: 0.20989079407877548
Fold 3 IBS: 0.17286590058344356
Fold 4 IBS: 0.17304528094098826
Fold 5 IBS: 0.2182125077630938
[I 2024-04-19 14:51:09,665] Trial 37 finished with value: 0.1878948269543108 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 496, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9929376104209421, 'min_weight_fraction_leaf': 0.08616912220218276}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.13319828194243652
Fold 2 IBS: 0.22067121132296855
Fold 3 IBS: 0.16980000428003392
Fold 4 IBS: 0.16339522222882116
Fold 5 IBS: 0.22988296728768715
[I 2024-04-19 14:51:16,624] Trial 38 finished with value: 0.18338953741238945 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 388, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8228713264596608, 'min_weight_fraction_leaf': 0.021895469287462357}. Best is trial 38 with value: 0.18338953741238945.
Fold 1 IBS: 0.13407560849543151
Fold 2 IBS: 0.2184148968621707
Fold 3 IBS: 0.17037492797043788
Fold 4 IBS: 0.16329611374791547
Fold 5 IBS: 0.2293623793340135
[I 2024-04-19 14:51:26,339] Trial 39 finished with value: 0.18310478528199378 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 395, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7898418765076363, 'min_weight_fraction_leaf': 0.020295911430938566}. Best is trial 39 with value: 0.18310478528199378.
Fold 1 IBS: 0.1304595556946257
Fold 2 IBS: 0.21558129315141517
Fold 3 IBS: 0.1721506143770424
Fold 4 IBS: 0.16618098384472219
Fold 5 IBS: 0.232949867879073
[I 2024-04-19 14:51:36,823] Trial 40 finished with value: 0.1834644629893757 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 395, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8371469247434516, 'min_weight_fraction_leaf': 0.015333852381823724}. Best is trial 39 with value: 0.18310478528199378.
Fold 1 IBS: 0.1325510554909969
Fold 2 IBS: 0.2176238888953884
Fold 3 IBS: 0.17146304984695035
Fold 4 IBS: 0.16383374018977762
Fold 5 IBS: 0.2308327762523128
[I 2024-04-19 14:51:46,204] Trial 41 finished with value: 0.18326090213508522 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 397, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8365147515392561, 'min_weight_fraction_leaf': 0.0016134071172678316}. Best is trial 39 with value: 0.18310478528199378.
Fold 1 IBS: 0.1314765695473778
Fold 2 IBS: 0.21139893346492042
Fold 3 IBS: 0.17223202101447635
Fold 4 IBS: 0.16376170833130235
Fold 5 IBS: 0.2321519720232104
[I 2024-04-19 14:51:58,619] Trial 42 finished with value: 0.18220424087625745 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 391, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8078708827436648, 'min_weight_fraction_leaf': 0.0013385721334536593}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13234737070073235
Fold 2 IBS: 0.21215429864404478
Fold 3 IBS: 0.17435282545530972
Fold 4 IBS: 0.16448123531500952
Fold 5 IBS: 0.23186786723530756
[I 2024-04-19 14:52:11,231] Trial 43 finished with value: 0.1830407194700808 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 390, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7924307971892496, 'min_weight_fraction_leaf': 0.00986096435937783}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14573824767156937
Fold 2 IBS: 0.2269412087537974
Fold 3 IBS: 0.16700435711423492
Fold 4 IBS: 0.16110065048481265
Fold 5 IBS: 0.2275276021025756
[I 2024-04-19 14:52:20,059] Trial 44 finished with value: 0.18566241322539798 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 352, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7911148199774719, 'min_weight_fraction_leaf': 0.020298655113375193}. Best is trial 42 with value: 0.18220424087625745.

Fold 1 IBS: 0.1350712935921733
Fold 2 IBS: 0.21575795396259614
Fold 3 IBS: 0.1719895889282686
Fold 4 IBS: 0.1639662174932425
Fold 5 IBS: 0.23179177468347978
[I 2024-04-19 14:52:31,498] Trial 45 finished with value: 0.18371536573195205 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 446, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7218458884001862, 'min_weight_fraction_leaf': 0.002908146688295732}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14405258172603636
Fold 2 IBS: 0.23510729165077407
Fold 3 IBS: 0.1652427330079092
Fold 4 IBS: 0.15610840831496184
Fold 5 IBS: 0.23462655467653304
[I 2024-04-19 14:52:38,196] Trial 46 finished with value: 0.1870275138752429 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 302, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7776896970279629, 'min_weight_fraction_leaf': 0.07225176694113553}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.21398697998771213
Fold 2 IBS: 0.22127076737509105
Fold 3 IBS: 0.204787245275916
Fold 4 IBS: 0.22464881989432967
Fold 5 IBS: 0.21857520577957465
[I 2024-04-19 14:52:47,250] Trial 47 finished with value: 0.21665380366252468 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 394, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5904360153291681, 'min_weight_fraction_leaf': 0.3242490493516816}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13680395735472003
Fold 2 IBS: 0.22883482339604239
Fold 3 IBS: 0.16837032388359582
Fold 4 IBS: 0.16000280315702775
Fold 5 IBS: 0.23281835611744003
[I 2024-04-19 14:52:57,699] Trial 48 finished with value: 0.1853660527817652 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 428, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8173484857489409, 'min_weight_fraction_leaf': 0.002401342777620552}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13753821864219098
Fold 2 IBS: 0.23322348156627426
Fold 3 IBS: 0.16650806858521439
Fold 4 IBS: 0.1593799860463597
Fold 5 IBS: 0.23477137343321255
[I 2024-04-19 14:53:05,117] Trial 49 finished with value: 0.18628422565465036 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 358, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7602887007952065, 'min_weight_fraction_leaf': 0.06926131111849082}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.15407248993307796
Fold 2 IBS: 0.22331629611552672
Fold 3 IBS: 0.1686714717607006
Fold 4 IBS: 0.15910078917701373
Fold 5 IBS: 0.2294913527439736
[I 2024-04-19 14:53:15,700] Trial 50 finished with value: 0.18693047994605855 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 472, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8011524070042025, 'min_weight_fraction_leaf': 0.11371575955383911}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.1292216590267733
Fold 2 IBS: 0.21535411859936704
Fold 3 IBS: 0.17364904066602752
Fold 4 IBS: 0.16832365810331645
Fold 5 IBS: 0.2341441204420188
[I 2024-04-19 14:53:25,063] Trial 51 finished with value: 0.18413851936750064 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 386, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8352773277741904, 'min_weight_fraction_leaf': 0.010409670541832795}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13661159522077607
Fold 2 IBS: 0.22298661504884923
Fold 3 IBS: 0.16890853299422418
Fold 4 IBS: 0.1613954589676683
Fold 5 IBS: 0.2291533277019588
[I 2024-04-19 14:53:36,169] Trial 52 finished with value: 0.1838111059866953 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 415, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8458630302918712, 'min_weight_fraction_leaf': 0.01883240853652938}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13285458221796065
Fold 2 IBS: 0.21324749338721247
Fold 3 IBS: 0.17437963072354587
Fold 4 IBS: 0.16754288596076145
Fold 5 IBS: 0.23216541507275276
[I 2024-04-19 14:53:44,615] Trial 53 finished with value: 0.18403800147244667 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 323, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7577087751903085, 'min_weight_fraction_leaf': 0.000926159316582905}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.21398748827861494
Fold 2 IBS: 0.2213335310951656
Fold 3 IBS: 0.20482302058163068
Fold 4 IBS: 0.2246762316540462
Fold 5 IBS: 0.218633693603778
[I 2024-04-19 14:53:55,291] Trial 54 finished with value: 0.2166907930426471 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 373, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6998643604561993, 'min_weight_fraction_leaf': 0.4522260564219586}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.15684384954039604
Fold 2 IBS: 0.21072872508349033
Fold 3 IBS: 0.1711788355891401
Fold 4 IBS: 0.16750388333602365
Fold 5 IBS: 0.2207016957578281
[I 2024-04-19 14:54:05,997] Trial 55 finished with value: 0.18539139786137562 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 432, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8588849365765647, 'min_weight_fraction_leaf': 0.05896276160735314}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13335973626684947
Fold 2 IBS: 0.21271799937980282
Fold 3 IBS: 0.1737325173775082
Fold 4 IBS: 0.16972405794405904
Fold 5 IBS: 0.2302689198189833
[I 2024-04-19 14:54:16,841] Trial 56 finished with value: 0.18396064615744057 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 346, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8050664718975571, 'min_weight_fraction_leaf': 0.026833183895911005}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13578108773552988
Fold 2 IBS: 0.22632586746444205
Fold 3 IBS: 0.17049332866303846
Fold 4 IBS: 0.16295298688829166
Fold 5 IBS: 0.23190382583631666
[I 2024-04-19 14:54:28,423] Trial 57 finished with value: 0.18549141931752372 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 466, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9066780831980561, 'min_weight_fraction_leaf': 0.04825981077573133}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.1683187097373053
Fold 2 IBS: 0.24961534223709086
Fold 3 IBS: 0.16725029953662748
Fold 4 IBS: 0.16137357744447564
Fold 5 IBS: 0.24019843915652014
[I 2024-04-19 14:54:35,951] Trial 58 finished with value: 0.1973512736224039 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 278, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7227803228076407, 'min_weight_fraction_leaf': 0.099078961783115}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.1783190622135976
Fold 2 IBS: 0.2019195895167403
Fold 3 IBS: 0.17861669574113284
Fold 4 IBS: 0.19082466174796836
Fold 5 IBS: 0.21301617946309295
[I 2024-04-19 14:54:45,669] Trial 59 finished with value: 0.1925392377365064 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 400, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9154352108935407, 'min_weight_fraction_leaf': 0.3795797400921996}. Best is trial 42 with value: 0.18220424087625745.

Fold 1 IBS: 0.2139754605574802
Fold 2 IBS: 0.22128037493850963
Fold 3 IBS: 0.2049770044390806
Fold 4 IBS: 0.22468785016066256
Fold 5 IBS: 0.21820838836670314
[I 2024-04-19 14:54:53,641] Trial 60 finished with value: 0.21662581569248723 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 373, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.36612707136592737, 'min_weight_fraction_leaf': 0.2583710069782479}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13013980993149055
Fold 2 IBS: 0.21254887098310069
Fold 3 IBS: 0.17298441817166582
Fold 4 IBS: 0.16679488873081466
Fold 5 IBS: 0.2331102795997352
[I 2024-04-19 14:55:02,719] Trial 61 finished with value: 0.18311565348336137 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 439, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.775335953046553, 'min_weight_fraction_leaf': 0.00045996407747498497}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13907195085309992
Fold 2 IBS: 0.21746762441111264
Fold 3 IBS: 0.16991510579967217
Fold 4 IBS: 0.15698374953129748
Fold 5 IBS: 0.23092538229655435
[I 2024-04-19 14:55:13,155] Trial 62 finished with value: 0.1828727625783473 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 434, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7787336396982455, 'min_weight_fraction_leaf': 0.017049830964679567}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.1461188072960583
Fold 2 IBS: 0.22297900373273485
Fold 3 IBS: 0.16819976748506882
Fold 4 IBS: 0.15627618251565928
Fold 5 IBS: 0.23056956630332018
[I 2024-04-19 14:55:23,913] Trial 63 finished with value: 0.18482866546656826 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 444, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.678914723196093, 'min_weight_fraction_leaf': 0.04051041185799438}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14922574781371922
Fold 2 IBS: 0.22336475015918203
Fold 3 IBS: 0.16766178110975566
Fold 4 IBS: 0.15767068769791207
Fold 5 IBS: 0.23077234127935545
[I 2024-04-19 14:55:32,780] Trial 64 finished with value: 0.1857390616119849 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 412, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7713563855654119, 'min_weight_fraction_leaf': 0.06466991810410304}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14196208017906697
Fold 2 IBS: 0.2203160952261016
Fold 3 IBS: 0.16893179777335507
Fold 4 IBS: 0.15654829756987573
Fold 5 IBS: 0.23125479899469772
[I 2024-04-19 14:55:44,402] Trial 65 finished with value: 0.18380261394861944 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 482, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.864019446775118, 'min_weight_fraction_leaf': 0.020950931739883927}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.21398363959846292
Fold 2 IBS: 0.2213068815502648
Fold 3 IBS: 0.20479920501202484
Fold 4 IBS: 0.22460863917083987
Fold 5 IBS: 0.2185893774573315
[I 2024-04-19 14:55:54,344] Trial 66 finished with value: 0.21665754855778477 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 435, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7911774756119411, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13566262450549949
Fold 2 IBS: 0.22523097017228863
Fold 3 IBS: 0.1692529598506911
Fold 4 IBS: 0.16290360566513454
Fold 5 IBS: 0.2327855372814568
[I 2024-04-19 14:56:03,280] Trial 67 finished with value: 0.18516713949501412 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 363, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7040452866645146, 'min_weight_fraction_leaf': 0.03968181972003887}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.16008903506031189
Fold 2 IBS: 0.20990936542664898
Fold 3 IBS: 0.1710695781803909
Fold 4 IBS: 0.1692741204721933
Fold 5 IBS: 0.2193567141991828
[I 2024-04-19 14:56:13,625] Trial 68 finished with value: 0.18593976266774556 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 458, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6460661483169103, 'min_weight_fraction_leaf': 0.05305571318039014}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14500196660262785
Fold 2 IBS: 0.22366958452892438
Fold 3 IBS: 0.16742407600195655
Fold 4 IBS: 0.1572461938806611
Fold 5 IBS: 0.23079281055431064
[I 2024-04-19 14:56:22,724] Trial 69 finished with value: 0.1848269263136961 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 383, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.741240523146211, 'min_weight_fraction_leaf': 0.014363934694956563}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.15565332542931426
Fold 2 IBS: 0.24424811320133
Fold 3 IBS: 0.16435796348117546
Fold 4 IBS: 0.1566817157931589
Fold 5 IBS: 0.2377253059342244
[I 2024-04-19 14:56:30,437] Trial 70 finished with value: 0.1917332847678406 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 309, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8177202192771716, 'min_weight_fraction_leaf': 0.14671642748692168}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13181210182662045
Fold 2 IBS: 0.21744681600276494
Fold 3 IBS: 0.17176144698256085
Fold 4 IBS: 0.16552083875779053
Fold 5 IBS: 0.23275188447099712
[I 2024-04-19 14:56:39,683] Trial 71 finished with value: 0.18385861760814678 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 395, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8752727565742746, 'min_weight_fraction_leaf': 0.013546840661669626}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13664759508087293
Fold 2 IBS: 0.22296192467878798
Fold 3 IBS: 0.16930394076001695
Fold 4 IBS: 0.16231046577236227
Fold 5 IBS: 0.2282230432378881
[I 2024-04-19 14:56:48,953] Trial 72 finished with value: 0.18388939390598566 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 411, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8300877285214284, 'min_weight_fraction_leaf': 0.000532465790500053}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.1346239998187586
Fold 2 IBS: 0.2204553274012152
Fold 3 IBS: 0.17118693884148742
Fold 4 IBS: 0.1634267645182296
Fold 5 IBS: 0.23111125243954722
[I 2024-04-19 14:56:57,435] Trial 73 finished with value: 0.1841608566038476 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 342, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8385554538360707, 'min_weight_fraction_leaf': 0.02810646380908776}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13390629681190472
Fold 2 IBS: 0.22698907202199678
Fold 3 IBS: 0.16758540501869873
Fold 4 IBS: 0.16229762462247163
Fold 5 IBS: 0.23484910404396492
[I 2024-04-19 14:57:07,007] Trial 74 finished with value: 0.18512550050380736 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 422, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7679190465908351, 'min_weight_fraction_leaf': 0.04679539158320054}. Best is trial 42 with value: 0.18220424087625745.

Fold 1 IBS: 0.1331805487459175
Fold 2 IBS: 0.21624338660783993
Fold 3 IBS: 0.1727837835092345
Fold 4 IBS: 0.16512709360909275
Fold 5 IBS: 0.23118212185240014
[I 2024-04-19 14:57:16,253] Trial 75 finished with value: 0.18370338686489696 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 388, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8812725582045702, 'min_weight_fraction_leaf': 0.014257699585348107}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14741275991375746
Fold 2 IBS: 0.22339111860096061
Fold 3 IBS: 0.16719852475388572
Fold 4 IBS: 0.1582361988967138
Fold 5 IBS: 0.23150079709187427
[I 2024-04-19 14:57:26,810] Trial 76 finished with value: 0.18554787985143836 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 446, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9673284169048014, 'min_weight_fraction_leaf': 0.07601195190861526}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13394514154804674
Fold 2 IBS: 0.22177341115829846
Fold 3 IBS: 0.1690998786333866
Fold 4 IBS: 0.1657199477195138
Fold 5 IBS: 0.2305753710893013
[I 2024-04-19 14:57:35,859] Trial 77 finished with value: 0.1842227500297094 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9168074120653801, 'min_weight_fraction_leaf': 0.03429632080601785}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.16413207966902973
Fold 2 IBS: 0.20870718072258884
Fold 3 IBS: 0.17225544487357397
Fold 4 IBS: 0.17091089695041697
Fold 5 IBS: 0.21843171590077987
[I 2024-04-19 14:57:46,047] Trial 78 finished with value: 0.18688746362327788 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 481, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6205262617833929, 'min_weight_fraction_leaf': 0.06370344940214184}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.1382247674913111
Fold 2 IBS: 0.2295727476203514
Fold 3 IBS: 0.1658109826697085
Fold 4 IBS: 0.159159006573788
Fold 5 IBS: 0.23538729964754349
[I 2024-04-19 14:57:55,613] Trial 79 finished with value: 0.18563096080054048 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 399, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5398413883194484, 'min_weight_fraction_leaf': 0.014909561272874527}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13345318600069242
Fold 2 IBS: 0.2165231635919131
Fold 3 IBS: 0.1731131915609491
Fold 4 IBS: 0.16900944810071544
Fold 5 IBS: 0.2316592394775838
[I 2024-04-19 14:58:05,806] Trial 80 finished with value: 0.18475164574637076 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 435, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7913828686899125, 'min_weight_fraction_leaf': 0.030163021360446518}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.1321868314739457
Fold 2 IBS: 0.21527742532287938
Fold 3 IBS: 0.17246309786070207
Fold 4 IBS: 0.16556602486759034
Fold 5 IBS: 0.23185115051411426
[I 2024-04-19 14:58:15,445] Trial 81 finished with value: 0.18346890600784635 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 385, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8625539830672827, 'min_weight_fraction_leaf': 0.012219864563902087}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13001719869154457
Fold 2 IBS: 0.2163459254145058
Fold 3 IBS: 0.1719780027952196
Fold 4 IBS: 0.16474752365476744
Fold 5 IBS: 0.23403653328857743
[I 2024-04-19 14:58:24,528] Trial 82 finished with value: 0.18342503676892297 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 380, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.853725608486768, 'min_weight_fraction_leaf': 0.0007996961404084738}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13578697454596114
Fold 2 IBS: 0.2246792962521539
Fold 3 IBS: 0.16863613920292866
Fold 4 IBS: 0.16184068798076107
Fold 5 IBS: 0.23375626030677646
[I 2024-04-19 14:58:34,791] Trial 83 finished with value: 0.18493987165771625 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 406, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7513579683315326, 'min_weight_fraction_leaf': 0.042687170612983744}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14484272608511417
Fold 2 IBS: 0.2275675689794216
Fold 3 IBS: 0.16879529591083986
Fold 4 IBS: 0.15869000696689647
Fold 5 IBS: 0.2309434178220489
[I 2024-04-19 14:58:44,142] Trial 84 finished with value: 0.18616780315286424 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 372, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.1443115068222393, 'min_weight_fraction_leaf': 0.00018702205865286415}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14630444194152487
Fold 2 IBS: 0.22324111246816955
Fold 3 IBS: 0.1684723371673193
Fold 4 IBS: 0.15748383644833983
Fold 5 IBS: 0.231655949614702
[I 2024-04-19 14:58:52,028] Trial 85 finished with value: 0.18543153552801112 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 329, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8089058835146683, 'min_weight_fraction_leaf': 0.031070527698653497}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.1336389770470042
Fold 2 IBS: 0.21912133230982853
Fold 3 IBS: 0.17125886949107771
Fold 4 IBS: 0.16302470803937694
Fold 5 IBS: 0.2310738851368272
[I 2024-04-19 14:59:02,778] Trial 86 finished with value: 0.18362355440482295 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 421, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7233398752849178, 'min_weight_fraction_leaf': 0.022456483517807643}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.15634749785775387
Fold 2 IBS: 0.20826490568132278
Fold 3 IBS: 0.1703584026567209
Fold 4 IBS: 0.16718116492468904
Fold 5 IBS: 0.22001159218206368
[I 2024-04-19 14:59:10,729] Trial 87 finished with value: 0.18443271266051003 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 353, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8238894970817884, 'min_weight_fraction_leaf': 0.05065759927412933}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14098048147522685
Fold 2 IBS: 0.23531327208330835
Fold 3 IBS: 0.16474065680610048
Fold 4 IBS: 0.1582355080734531
Fold 5 IBS: 0.23518291464789914
[I 2024-04-19 14:59:21,836] Trial 88 finished with value: 0.1868905666171976 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 455, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8446434140866994, 'min_weight_fraction_leaf': 0.08240102500283404}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13361909066838437
Fold 2 IBS: 0.22419453913237133
Fold 3 IBS: 0.17100752556815316
Fold 4 IBS: 0.1660035667866496
Fold 5 IBS: 0.2323807291125235
[I 2024-04-19 14:59:32,567] Trial 89 finished with value: 0.18544109025361638 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 428, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9488800447976891, 'min_weight_fraction_leaf': 0.000806200076917006}. Best is trial 42 with value: 0.18220424087625745.

Fold 1 IBS: 0.12988717417010312
Fold 2 IBS: 0.21111739221808115
Fold 3 IBS: 0.17281260544267968
Fold 4 IBS: 0.16744968489433068
Fold 5 IBS: 0.23530465742353276
[I 2024-04-19 14:59:39,462] Trial 90 finished with value: 0.18331430282974548 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 317, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7774148609541289, 'min_weight_fraction_leaf': 0.011005982719496389}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.12951620582034926
Fold 2 IBS: 0.210867217186133
Fold 3 IBS: 0.17327356003962616
Fold 4 IBS: 0.16765928672732763
Fold 5 IBS: 0.2351767398201044
[I 2024-04-19 14:59:48,162] Trial 91 finished with value: 0.1832986019187081 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 322, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7781808052399918, 'min_weight_fraction_leaf': 0.01374012670873183}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13365970503909627
Fold 2 IBS: 0.2203990045693183
Fold 3 IBS: 0.1719809794463351
Fold 4 IBS: 0.1659275988455526
Fold 5 IBS: 0.2310461126564287
[I 2024-04-19 14:59:54,476] Trial 92 finished with value: 0.1846026801113462 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 239, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7850185292906079, 'min_weight_fraction_leaf': 0.03722989027730587}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.12777378019441304
Fold 2 IBS: 0.2103658906995854
Fold 3 IBS: 0.17326068363598274
Fold 4 IBS: 0.1681953545772438
Fold 5 IBS: 0.2351533313692652
[I 2024-04-19 15:00:04,134] Trial 93 finished with value: 0.18294980809529804 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 328, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7779587706658339, 'min_weight_fraction_leaf': 0.009311683805295526}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14857803579143394
Fold 2 IBS: 0.20918836940525298
Fold 3 IBS: 0.1688618315206691
Fold 4 IBS: 0.16374621373038312
Fold 5 IBS: 0.22223318272254292
[I 2024-04-19 15:00:12,304] Trial 94 finished with value: 0.1825215266340564 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 288, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6743157809017337, 'min_weight_fraction_leaf': 0.022016337499591185}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14318063826069696
Fold 2 IBS: 0.20900427100439892
Fold 3 IBS: 0.16849069305388098
Fold 4 IBS: 0.1615555973109128
Fold 5 IBS: 0.2229893711651227
[I 2024-04-19 15:00:19,041] Trial 95 finished with value: 0.1810441141590025 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 288, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7098772062937373, 'min_weight_fraction_leaf': 0.012799049735992758}. Best is trial 95 with value: 0.1810441141590025.
Fold 1 IBS: 0.16025790354872743
Fold 2 IBS: 0.21063171316283893
Fold 3 IBS: 0.17113063455571145
Fold 4 IBS: 0.1694766923206728
Fold 5 IBS: 0.22010196737994892
[I 2024-04-19 15:00:25,722] Trial 96 finished with value: 0.1863197821935799 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 275, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6948087465011815, 'min_weight_fraction_leaf': 0.0592892883568545}. Best is trial 95 with value: 0.1810441141590025.
Fold 1 IBS: 0.18027221741116026
Fold 2 IBS: 0.20868443032134176
Fold 3 IBS: 0.1805960012942096
Fold 4 IBS: 0.19192844137806864
Fold 5 IBS: 0.21569000579227957
[I 2024-04-19 15:00:31,240] Trial 97 finished with value: 0.19543421923941198 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 20, 'max_depth': 14, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7271967081655182, 'min_weight_fraction_leaf': 0.02654927328611698}. Best is trial 95 with value: 0.1810441141590025.
Fold 1 IBS: 0.15658766261322524
Fold 2 IBS: 0.20896735975747097
Fold 3 IBS: 0.16973603267155693
Fold 4 IBS: 0.16879223967676366
Fold 5 IBS: 0.22161586321168347
[I 2024-04-19 15:00:37,215] Trial 98 finished with value: 0.18513983158614006 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6737745771706081, 'min_weight_fraction_leaf': 0.0434038722130365}. Best is trial 95 with value: 0.1810441141590025.
Fold 1 IBS: 0.1662721546014814
Fold 2 IBS: 0.2096645157784754
Fold 3 IBS: 0.1738820252882844
Fold 4 IBS: 0.17586626741763942
Fold 5 IBS: 0.2187259900953022
[I 2024-04-19 15:00:44,287] Trial 99 finished with value: 0.18888219063623657 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 305, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7500938622905841, 'min_weight_fraction_leaf': 0.10104599371859008}. Best is trial 95 with value: 0.1810441141590025.


* Best trial for IBS:
 FrozenTrial(number=95, state=TrialState.COMPLETE, values=[0.1810441141590025], datetime_start=datetime.datetime(2024, 4, 19, 15, 0, 12, 346605), datetime_complete=datetime.datetime(2024, 4, 19, 15, 0, 19, 40564), params={'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 288, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7098772062937373, 'min_weight_fraction_leaf': 0.012799049735992758}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=95, value=None)


* Best Score for IBS:
 0.1810441141590025

In [62]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [63]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.816
train_ibs:  0.181

#### Test

In [64]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [65]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=11, max_leaf_nodes=13,
                   max_samples=0.9554816381741302, min_samples_leaf=1,
                   min_samples_split=17,
                   min_weight_fraction_leaf=0.026333169142875475,
                   n_estimators=68, random_state=123, warm_start=True)

C-index score: 0.656

ExtraSurvivalTrees(max_depth=13, max_features=1, max_leaf_nodes=11,
                   max_samples=0.7098772062937373, min_samples_leaf=1,
                   min_samples_split=14,
                   min_weight_fraction_leaf=0.012799049735992758,
                   n_estimators=288, oob_score=True, random_state=123,
                   warm_start=True)

IBS: 0.214

In [66]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [67]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 15:00:46,610] A new study created in memory with name: no-name-9fad6079-e0b4-4e4c-85e9-eafebacf1bac

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:01:23,846] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:01:45,619] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:02:06,005] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:02:37,145] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:02:52,613] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:02:57,022] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:03:31,095] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:03:41,592] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:03:43,096] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.8376623376623377
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7236286919831224
Fold 5 C-index: 0.6690140845070423
[I 2024-04-19 15:05:13,950] Trial 9 finished with value: 0.7471201964999683 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 15:07:28,183] Trial 10 finished with value: 0.6769991466942861 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:09:57,526] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.803030303030303
Fold 2 C-index: 0.6986607142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 15:12:05,922] Trial 12 finished with value: 0.7331503156498502 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7471201964999683.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:13:10,887] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:14:38,806] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:15:54,274] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:16:46,885] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:18:32,821] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:20:51,787] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:20:57,497] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:21:48,408] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.6384976525821596
[I 2024-04-19 15:23:42,741] Trial 21 finished with value: 0.6596743990023763 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7362869198312236
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 15:25:28,863] Trial 22 finished with value: 0.7520782207516631 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:26:50,320] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:28:07,244] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.7520782207516631.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:28:52,500] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5558035714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5654008438818565
Fold 5 C-index: 0.636150234741784
[I 2024-04-19 15:30:31,495] Trial 26 finished with value: 0.5848042633437757 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:31:59,338] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:33:09,851] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:33:58,720] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:35:05,913] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.7075892857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6118143459915611
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 15:36:54,317] Trial 31 finished with value: 0.6975838362663174 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:38:47,850] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9113568740147856, 'learning_rate': 0.01936213758007274, 'dropout_rate': 0.1444594228310892, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 1.6183832787391992, 'min_weight_fraction_leaf': 0.4304319218036696, 'max_features': 'auto', 'min_impurity_decrease': 1.0277484189219154e-07, 'validation_fraction': 0.9117669993681574, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:40:21,693] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9728428556912192, 'learning_rate': 0.015742740923125064, 'dropout_rate': 0.30020186346124766, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 9.846141209805609, 'min_weight_fraction_leaf': 0.4958404435609285, 'max_features': 'auto', 'min_impurity_decrease': 2.2786499479002052e-07, 'validation_fraction': 0.8344453462672722, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:41:34,955] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.8496036715186095, 'learning_rate': 0.009253864701923034, 'dropout_rate': 0.22658656718653286, 'n_estimators': 403, 'criterion': 'friedman_mse', 'ccp_alpha': 0.641857272630336, 'min_weight_fraction_leaf': 0.43629024868714544, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9168532630851701, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:41:52,082] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.6806458891075314, 'learning_rate': 0.0016219483573201542, 'dropout_rate': 0.4078621112435248, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3706867126320781, 'max_features': None, 'min_impurity_decrease': 7.8587698841458e-07, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:43:20,016] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.9551502281749775, 'learning_rate': 0.026078126474550274, 'dropout_rate': 0.34789169882120996, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.40891402270131877, 'min_weight_fraction_leaf': 0.2325827619040188, 'max_features': 'auto', 'min_impurity_decrease': 7.145093229830912e-06, 'validation_fraction': 0.6747809687204889, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.7520782207516631.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:43:25,860] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.7371581418455209, 'learning_rate': 0.0145417341576766, 'dropout_rate': 0.16172130996739253, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.3174537146690439, 'max_features': None, 'min_impurity_decrease': 2.89190119114804e-07, 'validation_fraction': 0.9548743578197549, 'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:43:45,609] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.8063221166350547, 'learning_rate': 0.006424315075939495, 'dropout_rate': 0.7673236646699829, 'n_estimators': 329, 'criterion': 'friedman_mse', 'ccp_alpha': 9.162989248724866, 'min_weight_fraction_leaf': 0.14601082900734919, 'max_features': 'auto', 'min_impurity_decrease': 1.1529415174162498e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:45:08,989] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.8852748015168422, 'learning_rate': 0.02975783779377629, 'dropout_rate': 0.2673592786040255, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 1.1216454788806307, 'min_weight_fraction_leaf': 0.09194334498965648, 'max_features': 1, 'min_impurity_decrease': 8.588272604740831e-07, 'validation_fraction': 0.7628102853958754, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:46:05,480] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.5809866593286652, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.20816102573612866, 'n_estimators': 353, 'criterion': 'squared_error', 'ccp_alpha': 3.7898554763179284, 'min_weight_fraction_leaf': 0.4711996214427754, 'max_features': 'auto', 'min_impurity_decrease': 2.3584088371991464e-07, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5907172995780591
Fold 5 C-index: 0.5821596244131455
[I 2024-04-19 15:46:05,965] Trial 41 finished with value: 0.6152707311185872 and parameters: {'subsample': 0.9964498482283193, 'learning_rate': 0.004158109708816752, 'dropout_rate': 0.13644226542045526, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4011310798872364, 'max_features': 'auto', 'min_impurity_decrease': 1.0090377437612141e-07, 'validation_fraction': 0.9993318631652353, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:48:08,826] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.10858843727097561, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.415120560514267, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9524403904515271, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:48:54,358] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.919916216831853, 'learning_rate': 0.0016321845585985228, 'dropout_rate': 0.16429624388711278, 'n_estimators': 284, 'criterion': 'squared_error', 'ccp_alpha': 0.471921644995546, 'min_weight_fraction_leaf': 0.3704175909956657, 'max_features': 'auto', 'min_impurity_decrease': 0.0009050261380449993, 'validation_fraction': 0.8779568222622545, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:49:50,825] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.998598837606123, 'learning_rate': 0.015327765728784649, 'dropout_rate': 0.6859431566383477, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 1.2679892492803537, 'min_weight_fraction_leaf': 0.2706416993480579, 'max_features': 'auto', 'min_impurity_decrease': 8.738793222106795e-07, 'validation_fraction': 0.9744834265061879, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 15:51:18,348] Trial 45 finished with value: 0.7210598007254247 and parameters: {'subsample': 0.8612793275132423, 'learning_rate': 0.008591203396202965, 'dropout_rate': 0.20237082649972205, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 0.09266970930573763, 'min_weight_fraction_leaf': 0.4478112124993417, 'max_features': 0.1, 'min_impurity_decrease': 1.775469126785021e-07, 'validation_fraction': 0.798828420958444, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:51:33,025] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.8576868620948644, 'learning_rate': 0.021769927230194788, 'dropout_rate': 0.9694253886674298, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 1.9903431110600875, 'min_weight_fraction_leaf': 0.45430295635160706, 'max_features': 0.1, 'min_impurity_decrease': 2.0131584568637675e-06, 'validation_fraction': 0.7976029227783121, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:52:00,861] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7056873961179977, 'learning_rate': 0.00929853233926034, 'dropout_rate': 0.3140351257259953, 'n_estimators': 235, 'criterion': 'squared_error', 'ccp_alpha': 7.181314443016622, 'min_weight_fraction_leaf': 0.49464896810642006, 'max_features': 0.1, 'min_impurity_decrease': 2.1438208123963576e-05, 'validation_fraction': 0.6179698437276481, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:53:16,113] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.7837245323509484, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.21043558082214228, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.4617743734350054, 'min_weight_fraction_leaf': 0.45246089314517907, 'max_features': 0.1, 'min_impurity_decrease': 4.221379974644956e-07, 'validation_fraction': 0.863214331971344, 'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 7}. Best is trial 22 with value: 0.7520782207516631.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:53:55,642] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.6507081753968225, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.26780621294484797, 'n_estimators': 297, 'criterion': 'friedman_mse', 'ccp_alpha': 1.378218906104398, 'min_weight_fraction_leaf': 0.2916489694540698, 'max_features': 'log2', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6845184717076465, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:55:14,233] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.03353370774351387, 'dropout_rate': 0.3787195779305788, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.7561621193902213, 'min_weight_fraction_leaf': 0.47814765735031256, 'max_features': 0.1, 'min_impurity_decrease': 1.6961878462023105e-07, 'validation_fraction': 0.8310153288008191, 'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.8203463203463204
Fold 2 C-index: 0.7790178571428571
Fold 3 C-index: 0.821078431372549
Fold 4 C-index: 0.7827004219409283
Fold 5 C-index: 0.6596244131455399
[I 2024-04-19 15:57:15,032] Trial 51 finished with value: 0.772553488789639 and parameters: {'subsample': 0.9590755303360702, 'learning_rate': 0.001263628446733103, 'dropout_rate': 0.13293847894616523, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.012928318097826519, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 51 with value: 0.772553488789639.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7745535714285714
Fold 3 C-index: 0.8259803921568627
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.6643192488262911
[I 2024-04-19 15:58:58,592] Trial 52 finished with value: 0.7782542196646564 and parameters: {'subsample': 0.9309483691931049, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.1309992574789837, 'n_estimators': 478, 'criterion': 'squared_error', 'ccp_alpha': 0.036615235505588, 'min_weight_fraction_leaf': 0.4052806656624778, 'max_features': 'sqrt', 'min_impurity_decrease': 2.8184597843569143e-07, 'validation_fraction': 0.8992446934973449, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 52 with value: 0.7782542196646564.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:00:18,293] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.9119792149240027, 'learning_rate': 0.0011619738930768678, 'dropout_rate': 0.12019527221159815, 'n_estimators': 416, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.33436888398209985, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0912509934146174e-06, 'validation_fraction': 0.7204767494493249, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 52 with value: 0.7782542196646564.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:00:44,597] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.9422391559777883, 'learning_rate': 0.006469543850280348, 'dropout_rate': 0.8266353856620614, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.46449392886564433, 'min_weight_fraction_leaf': 0.20818644825744925, 'max_features': 'sqrt', 'min_impurity_decrease': 3.17346833824979e-07, 'validation_fraction': 0.8741639290304148, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 52 with value: 0.7782542196646564.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:01:56,827] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8715328822130523, 'learning_rate': 0.011790338191706525, 'dropout_rate': 0.23926982708415356, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 0.4008945876330496, 'min_weight_fraction_leaf': 0.44051010658711054, 'max_features': 'sqrt', 'min_impurity_decrease': 5.615119149330365e-07, 'validation_fraction': 0.7887577239921508, 'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 52 with value: 0.7782542196646564.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:03:34,477] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.8015434219726096, 'learning_rate': 0.04061736247319854, 'dropout_rate': 0.1937709311352404, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 1.037591557618962, 'min_weight_fraction_leaf': 0.41307911755286036, 'max_features': 'sqrt', 'min_impurity_decrease': 1.854323715915516e-06, 'validation_fraction': 0.907633472782051, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 52 with value: 0.7782542196646564.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.796875
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6690140845070423
[I 2024-04-19 16:04:11,948] Trial 57 finished with value: 0.781123328823093 and parameters: {'subsample': 0.47167111494444647, 'learning_rate': 0.018997287630538016, 'dropout_rate': 0.5891903890315894, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.007297661499282945, 'min_weight_fraction_leaf': 0.37949114392069716, 'max_features': 'sqrt', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.5599065409082953, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 57 with value: 0.781123328823093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:05:09,317] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.42473576655735995, 'learning_rate': 0.018900335501351662, 'dropout_rate': 0.6195846181212514, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.7489235673712139, 'min_weight_fraction_leaf': 0.37172290689803544, 'max_features': 'sqrt', 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.5649807819209639, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 57 with value: 0.781123328823093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:05:39,841] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.4705271187560865, 'learning_rate': 0.021814358601443318, 'dropout_rate': 0.7119170684357518, 'n_estimators': 374, 'criterion': 'squared_error', 'ccp_alpha': 1.429314535364776, 'min_weight_fraction_leaf': 0.3051539123714827, 'max_features': 'sqrt', 'min_impurity_decrease': 5.188349818876903e-07, 'validation_fraction': 0.4822753579684245, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 11}. Best is trial 57 with value: 0.781123328823093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:06:21,021] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.5340859352401606, 'learning_rate': 0.025149879907566695, 'dropout_rate': 0.6358545234388486, 'n_estimators': 393, 'criterion': 'squared_error', 'ccp_alpha': 0.8721071580406399, 'min_weight_fraction_leaf': 0.2617324012356312, 'max_features': 'sqrt', 'min_impurity_decrease': 3.1935923441647085e-07, 'validation_fraction': 0.41178016017445873, 'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 57 with value: 0.781123328823093.

Fold 1 C-index: 0.8484848484848485
Fold 2 C-index: 0.8236607142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7573839662447257
Fold 5 C-index: 0.6690140845070423
[I 2024-04-19 16:07:09,559] Trial 61 finished with value: 0.7834342129005446 and parameters: {'subsample': 0.319800669455551, 'learning_rate': 0.010928263297494037, 'dropout_rate': 0.5959135142579131, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 0.08369853910029246, 'min_weight_fraction_leaf': 0.3768225293955428, 'max_features': 'sqrt', 'min_impurity_decrease': 1.9022954194826543e-07, 'validation_fraction': 0.9463803671108196, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 61 with value: 0.7834342129005446.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8147321428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.687793427230047
[I 2024-04-19 16:08:04,915] Trial 62 finished with value: 0.7856240407595962 and parameters: {'subsample': 0.26730245398299407, 'learning_rate': 0.005570953859927015, 'dropout_rate': 0.5689698891552257, 'n_estimators': 425, 'criterion': 'squared_error', 'ccp_alpha': 0.022377389338332464, 'min_weight_fraction_leaf': 0.3409131872515221, 'max_features': 'sqrt', 'min_impurity_decrease': 1.85269269758306e-07, 'validation_fraction': 0.9450344863737145, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 62 with value: 0.7856240407595962.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:09:00,566] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.21664597025713805, 'learning_rate': 0.012813076208169889, 'dropout_rate': 0.5693919318511333, 'n_estimators': 425, 'criterion': 'squared_error', 'ccp_alpha': 0.4119356056831134, 'min_weight_fraction_leaf': 0.3347054705435437, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8279573515116132e-07, 'validation_fraction': 0.9497483584074397, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 62 with value: 0.7856240407595962.
Fold 1 C-index: 0.8484848484848485
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6737089201877934
[I 2024-04-19 16:10:07,384] Trial 64 finished with value: 0.786026040547988 and parameters: {'subsample': 0.34331456059062987, 'learning_rate': 0.005335751023510593, 'dropout_rate': 0.5293390090928782, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.0425951526045976, 'min_weight_fraction_leaf': 0.38936421852537745, 'max_features': 'sqrt', 'min_impurity_decrease': 3.017573951575898e-07, 'validation_fraction': 0.8901592560354066, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 64 with value: 0.786026040547988.
Fold 1 C-index: 0.8441558441558441
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6784037558685446
[I 2024-04-19 16:11:04,767] Trial 65 finished with value: 0.7897581704037714 and parameters: {'subsample': 0.3390231900132655, 'learning_rate': 0.005751881948804041, 'dropout_rate': 0.5630376022581163, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.002745627425376866, 'min_weight_fraction_leaf': 0.3871530270040246, 'max_features': 'sqrt', 'min_impurity_decrease': 6.694579707208464e-07, 'validation_fraction': 0.18033435762270877, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 65 with value: 0.7897581704037714.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:11:44,699] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.3211741793059686, 'learning_rate': 0.00520162993595177, 'dropout_rate': 0.5728129835100113, 'n_estimators': 358, 'criterion': 'squared_error', 'ccp_alpha': 0.3310950042218784, 'min_weight_fraction_leaf': 0.38274388203487975, 'max_features': 'sqrt', 'min_impurity_decrease': 2.724029141952152e-06, 'validation_fraction': 0.3085811036906729, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 6}. Best is trial 65 with value: 0.7897581704037714.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:12:51,596] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.23594984519111556, 'learning_rate': 0.005404142410171992, 'dropout_rate': 0.4929299984506029, 'n_estimators': 443, 'criterion': 'squared_error', 'ccp_alpha': 1.1937792228430404, 'min_weight_fraction_leaf': 0.3475526868546416, 'max_features': 'sqrt', 'min_impurity_decrease': 6.424725819821063e-07, 'validation_fraction': 0.2826913354575118, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 65 with value: 0.7897581704037714.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:13:58,639] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.34683185742787537, 'learning_rate': 0.09805784604547818, 'dropout_rate': 0.5384700399262299, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.7692354450958495, 'min_weight_fraction_leaf': 0.41749893021198126, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0616801934559534e-06, 'validation_fraction': 0.23471568192107903, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 65 with value: 0.7897581704037714.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:15:08,711] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.2861177658813064, 'learning_rate': 0.017944099553551186, 'dropout_rate': 0.43389463986071763, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 6.319375173875926, 'min_weight_fraction_leaf': 0.3792527429968225, 'max_features': 'sqrt', 'min_impurity_decrease': 1.496310137618593e-07, 'validation_fraction': 0.13907775132396938, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 15}. Best is trial 65 with value: 0.7897581704037714.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7869198312236287
Fold 5 C-index: 0.6737089201877934
[I 2024-04-19 16:16:09,545] Trial 70 finished with value: 0.7847059641860278 and parameters: {'subsample': 0.3774724270129156, 'learning_rate': 0.011124381782250005, 'dropout_rate': 0.650277108598025, 'n_estimators': 484, 'criterion': 'friedman_mse', 'ccp_alpha': 0.010159515082891972, 'min_weight_fraction_leaf': 0.362344472986224, 'max_features': 'sqrt', 'min_impurity_decrease': 2.747211987721928e-07, 'validation_fraction': 0.8434879817738963, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 65 with value: 0.7897581704037714.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:17:11,989] Trial 71 finished with value: 0.5 and parameters: {'subsample': 0.3772867510834654, 'learning_rate': 0.009873817799557231, 'dropout_rate': 0.638940448874788, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2585767773696627, 'min_weight_fraction_leaf': 0.3593001481583254, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6411726759754516e-07, 'validation_fraction': 0.892722402960641, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 65 with value: 0.7897581704037714.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7869198312236287
Fold 5 C-index: 0.6737089201877934
[I 2024-04-19 16:18:10,562] Trial 72 finished with value: 0.7900631070431706 and parameters: {'subsample': 0.42289594631245, 'learning_rate': 0.003999192670171843, 'dropout_rate': 0.5771575036069397, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.004870343735235726, 'min_weight_fraction_leaf': 0.3982179938524501, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0115746656852655e-07, 'validation_fraction': 0.8408360882819792, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 72 with value: 0.7900631070431706.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:18:54,554] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.4161743419322261, 'learning_rate': 0.01646575593094526, 'dropout_rate': 0.5934540934399337, 'n_estimators': 393, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6105529211816056, 'min_weight_fraction_leaf': 0.4064927557251237, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0373937877450991e-07, 'validation_fraction': 0.8429645916964783, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:20:00,157] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.3677729229747588, 'learning_rate': 0.006293476681503581, 'dropout_rate': 0.5119552573516976, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3244777939229942, 'min_weight_fraction_leaf': 0.33489971298250326, 'max_features': 'sqrt', 'min_impurity_decrease': 4.223038253919878e-07, 'validation_fraction': 0.7344816284775862, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:20:40,881] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.2903900357122111, 'learning_rate': 0.012973381912704278, 'dropout_rate': 0.6645294261386104, 'n_estimators': 433, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8094042116304128, 'min_weight_fraction_leaf': 0.3587496831264275, 'max_features': 'sqrt', 'min_impurity_decrease': 3.0390269391384854e-07, 'validation_fraction': 0.8568404234029825, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:21:19,332] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.44036493992983516, 'learning_rate': 0.003895017959761613, 'dropout_rate': 0.7235352189729908, 'n_estimators': 460, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3011411348311229, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'sqrt', 'min_impurity_decrease': 6.551998916484513e-07, 'validation_fraction': 0.35120610496528537, 'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:21:55,810] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.5030732468010138, 'learning_rate': 0.010318303683782707, 'dropout_rate': 0.55495865381036, 'n_estimators': 374, 'criterion': 'friedman_mse', 'ccp_alpha': 2.2261370357947867, 'min_weight_fraction_leaf': 0.3946892587694452, 'max_features': 'sqrt', 'min_impurity_decrease': 1.477390188984205e-07, 'validation_fraction': 0.8226290169133673, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:22:04,119] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.25891843939074943, 'learning_rate': 0.013618481172327222, 'dropout_rate': 0.5929458556614376, 'n_estimators': 163, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0768522145163504, 'min_weight_fraction_leaf': 0.42107281791067985, 'max_features': 'sqrt', 'min_impurity_decrease': 2.5818809372490893e-07, 'validation_fraction': 0.1709569658480536, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:23:19,991] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.12891422333306404, 'learning_rate': 0.007724344499863844, 'dropout_rate': 0.44904550180852654, 'n_estimators': 486, 'criterion': 'friedman_mse', 'ccp_alpha': 0.005965678681071493, 'min_weight_fraction_leaf': 0.3933038023418368, 'max_features': None, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.037974227411897016, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 19}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:24:14,046] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.3144678268216224, 'learning_rate': 0.003933423769250072, 'dropout_rate': 0.5376517061433939, 'n_estimators': 416, 'criterion': 'friedman_mse', 'ccp_alpha': 4.739756973970751, 'min_weight_fraction_leaf': 0.3656961834749051, 'max_features': 1, 'min_impurity_decrease': 0.000321859747788374, 'validation_fraction': 0.8934322384554279, 'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:25:04,694] Trial 81 finished with value: 0.5 and parameters: {'subsample': 0.3574265068335679, 'learning_rate': 0.0012397272499832656, 'dropout_rate': 0.6729323707765625, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.6406854872661993, 'min_weight_fraction_leaf': 0.3798799998701948, 'max_features': 'sqrt', 'min_impurity_decrease': 1.857443105250775e-07, 'validation_fraction': 0.9565934036182363, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.6737089201877934
[I 2024-04-19 16:26:17,197] Trial 82 finished with value: 0.7753168921014978 and parameters: {'subsample': 0.40555469208261735, 'learning_rate': 0.006717506934730347, 'dropout_rate': 0.6309816700892386, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.018184135202982572, 'min_weight_fraction_leaf': 0.34175759184922644, 'max_features': 'sqrt', 'min_impurity_decrease': 4.4229121687330197e-07, 'validation_fraction': 0.9310412285264067, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.5654008438818565
Fold 5 C-index: 0.6384976525821596
[I 2024-04-19 16:27:28,006] Trial 83 finished with value: 0.6925176672072417 and parameters: {'subsample': 0.4021210454834687, 'learning_rate': 0.00967440772841731, 'dropout_rate': 0.6168787838223372, 'n_estimators': 496, 'criterion': 'friedman_mse', 'ccp_alpha': 0.19967719155635735, 'min_weight_fraction_leaf': 0.3451328688427247, 'max_features': 'sqrt', 'min_impurity_decrease': 4.502255281481611e-07, 'validation_fraction': 0.9235910988376809, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:28:04,368] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.46939653554524097, 'learning_rate': 0.007513599522063374, 'dropout_rate': 0.821691123019113, 'n_estimators': 454, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5540358584093127, 'min_weight_fraction_leaf': 0.3037992576953221, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0775924853240628e-06, 'validation_fraction': 0.9688665543922645, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 72 with value: 0.7900631070431706.

Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7477678571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 16:28:50,491] Trial 85 finished with value: 0.7729809585587262 and parameters: {'subsample': 0.38573804052349686, 'learning_rate': 0.052741323552683156, 'dropout_rate': 0.6921135637698407, 'n_estimators': 500, 'criterion': 'friedman_mse', 'ccp_alpha': 0.01112533755039441, 'min_weight_fraction_leaf': 0.32360543928998425, 'max_features': 'sqrt', 'min_impurity_decrease': 1.376498986419818e-07, 'validation_fraction': 0.7732538542931726, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 10}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:29:36,736] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.4471491324763385, 'learning_rate': 0.08767662742937916, 'dropout_rate': 0.6433246180507093, 'n_estimators': 484, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5208204158471001, 'min_weight_fraction_leaf': 0.4258155364780357, 'max_features': 'log2', 'min_impurity_decrease': 3.3108218532416555e-07, 'validation_fraction': 0.9302527299193313, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:29:53,899] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.3059124344357447, 'learning_rate': 0.017000056781688845, 'dropout_rate': 0.5753138611140339, 'n_estimators': 266, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8939721870634515, 'min_weight_fraction_leaf': 0.39766156297021943, 'max_features': 'sqrt', 'min_impurity_decrease': 7.257875823452126e-07, 'validation_fraction': 0.8942531173715377, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:30:47,276] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.3390640822352382, 'learning_rate': 0.020951330544439258, 'dropout_rate': 0.5009856651818354, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 8.088457238075051, 'min_weight_fraction_leaf': 0.40810963176734805, 'max_features': 'sqrt', 'min_impurity_decrease': 2.329078771156988e-07, 'validation_fraction': 0.8535804780735345, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:31:28,527] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.501210787330669, 'learning_rate': 0.004039454116789691, 'dropout_rate': 0.5315084686509086, 'n_estimators': 403, 'criterion': 'friedman_mse', 'ccp_alpha': 0.262115769740312, 'min_weight_fraction_leaf': 0.3550762826973989, 'max_features': 'sqrt', 'min_impurity_decrease': 5.000296444465733e-07, 'validation_fraction': 0.6577544168504801, 'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:32:21,059] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.3969009416299629, 'learning_rate': 0.011038951399379136, 'dropout_rate': 0.5911491931771738, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 1.20306042705909, 'min_weight_fraction_leaf': 0.3395185145856917, 'max_features': 'sqrt', 'min_impurity_decrease': 1.3085362819964039e-06, 'validation_fraction': 0.9980112998955034, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7477678571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 16:33:03,956] Trial 91 finished with value: 0.7683617021461335 and parameters: {'subsample': 0.3710685773618577, 'learning_rate': 0.05060252500154345, 'dropout_rate': 0.7112267377565065, 'n_estimators': 500, 'criterion': 'friedman_mse', 'ccp_alpha': 0.038311453954747145, 'min_weight_fraction_leaf': 0.32399238617651593, 'max_features': 'sqrt', 'min_impurity_decrease': 1.2898230424577564e-07, 'validation_fraction': 0.76803640233329, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 10}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:33:37,436] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.24560298186792678, 'learning_rate': 0.05793741709178523, 'dropout_rate': 0.7425784246769499, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5955982791717448, 'min_weight_fraction_leaf': 0.32582543700307265, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0039386816564054e-07, 'validation_fraction': 0.8298125376468664, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 8}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:34:15,092] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.19114788292027068, 'learning_rate': 0.006759108786508056, 'dropout_rate': 0.6823186731821831, 'n_estimators': 435, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3763825346182167, 'min_weight_fraction_leaf': 0.36623610433160614, 'max_features': 'sqrt', 'min_impurity_decrease': 2.2785210161928306e-07, 'validation_fraction': 0.877327076579441, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.5907172995780591
Fold 5 C-index: 0.5985915492957746
[I 2024-04-19 16:35:03,594] Trial 94 finished with value: 0.6395846180049679 and parameters: {'subsample': 0.423015330597536, 'learning_rate': 0.0437490470487491, 'dropout_rate': 0.6521695143575769, 'n_estimators': 484, 'criterion': 'friedman_mse', 'ccp_alpha': 0.23680614346106993, 'min_weight_fraction_leaf': 0.37828079175958235, 'max_features': None, 'min_impurity_decrease': 1.3449106353124824e-07, 'validation_fraction': 0.7831338496745038, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:35:51,492] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.2663705028170775, 'learning_rate': 0.05047840916818071, 'dropout_rate': 0.6198131665729131, 'n_estimators': 467, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6518567922515498, 'min_weight_fraction_leaf': 0.3069519947028543, 'max_features': 'sqrt', 'min_impurity_decrease': 0.04760435998517946, 'validation_fraction': 0.8159365517337362, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 10}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7869198312236287
Fold 5 C-index: 0.6924882629107981
[I 2024-04-19 16:36:25,450] Trial 96 finished with value: 0.7912820517273182 and parameters: {'subsample': 0.38604321258984187, 'learning_rate': 0.05396213117321635, 'dropout_rate': 0.6934300990357392, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 0.030433464476024484, 'min_weight_fraction_leaf': 0.38729753243593296, 'max_features': 1, 'min_impurity_decrease': 3.7676942671090066e-07, 'validation_fraction': 0.9213195792266449, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 96 with value: 0.7912820517273182.

Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.5982142857142857
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:37:07,237] Trial 97 finished with value: 0.5469155844155844 and parameters: {'subsample': 0.334801811655963, 'learning_rate': 0.06226809094817951, 'dropout_rate': 0.5562831195117867, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.22723942954454154, 'min_weight_fraction_leaf': 0.3898326763187332, 'max_features': 1, 'min_impurity_decrease': 7.784668787793484e-05, 'validation_fraction': 0.9343491435456887, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 6}. Best is trial 96 with value: 0.7912820517273182.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:38:07,934] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.5704320380294472, 'learning_rate': 0.014236947521345914, 'dropout_rate': 0.46833983664280443, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.9743600736120059, 'min_weight_fraction_leaf': 0.4403782284758478, 'max_features': 1, 'min_impurity_decrease': 4.1978650730403767e-07, 'validation_fraction': 0.9737989432872376, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 96 with value: 0.7912820517273182.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-19 16:38:39,065] A new study created in memory with name: no-name-c74a1f0d-cb5a-4ad9-ac6c-611b04512009

Fold 5 C-index: 0.5
[I 2024-04-19 16:38:39,035] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.44973533951085454, 'learning_rate': 0.06941318862082362, 'dropout_rate': 0.6076064350817783, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 1.7029501932062083, 'min_weight_fraction_leaf': 0.4081649924422779, 'max_features': 1, 'min_impurity_decrease': 7.911599321468388e-07, 'validation_fraction': 0.9037866359790525, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 96 with value: 0.7912820517273182.


* Best trial for C-index:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.7912820517273182], datetime_start=datetime.datetime(2024, 4, 19, 16, 35, 51, 554846), datetime_complete=datetime.datetime(2024, 4, 19, 16, 36, 25, 449462), params={'subsample': 0.38604321258984187, 'learning_rate': 0.05396213117321635, 'dropout_rate': 0.6934300990357392, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 0.030433464476024484, 'min_weight_fraction_leaf': 0.38729753243593296, 'max_features': 1, 'min_impurity_decrease': 3.7676942671090066e-07, 'validation_fraction': 0.9213195792266449, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 7}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=96, value=None)


* Best Score for C-index:
 0.7912820517273182

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:39:06,105] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:39:22,145] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:39:38,969] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:40:05,899] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:40:14,968] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:40:17,175] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:40:41,304] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:40:49,249] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:40:50,141] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21260169564761522
Fold 2 IBS: 0.2208117276566402
Fold 3 IBS: 0.20334487960536277
Fold 4 IBS: 0.22388122768542051
Fold 5 IBS: 0.217665915754874
[I 2024-04-19 16:41:56,435] Trial 9 finished with value: 0.21566108926998254 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21360363678959007
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.20421474792063551
Fold 4 IBS: 0.22456346085174822
Fold 5 IBS: 0.21803455300047256
[I 2024-04-19 16:43:11,665] Trial 10 finished with value: 0.21637936117854983 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 16:44:47,626] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21383760159283438
Fold 2 IBS: 0.22154057816926387
Fold 3 IBS: 0.20441416271188637
Fold 4 IBS: 0.22468479705215127
Fold 5 IBS: 0.21808800811495244
[I 2024-04-19 16:46:01,802] Trial 12 finished with value: 0.2165130295282177 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-19 16:46:36,631] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:47:32,291] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:48:24,629] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:48:58,142] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:50:15,724] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:50:55,827] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:51:03,868] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:52:17,706] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21390574994112835
Fold 2 IBS: 0.22156131309595062
Fold 3 IBS: 0.2045078758011969
Fold 4 IBS: 0.22466878152435252
Fold 5 IBS: 0.21808456363125545
[I 2024-04-19 16:53:33,288] Trial 21 finished with value: 0.21654565679877677 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21250390766170438
Fold 2 IBS: 0.22090992293124842

Fold 3 IBS: 0.20322775423820424
Fold 4 IBS: 0.22409416642697289
Fold 5 IBS: 0.21764473279143468
[I 2024-04-19 16:54:47,275] Trial 22 finished with value: 0.2156760968099129 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 16:55:45,331] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:56:25,003] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:57:00,637] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:57:53,366] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:57:58,886] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:58:18,085] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:59:07,645] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 16:59:27,361] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21355264316168573
Fold 2 IBS: 0.22149663133331596
Fold 3 IBS: 0.2042721330591835
Fold 4 IBS: 0.2245750034693936
Fold 5 IBS: 0.21801491575167778
[I 2024-04-19 17:00:28,008] Trial 31 finished with value: 0.21638226535505134 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.2129290559388716
Fold 2 IBS: 0.22124897719545888
Fold 3 IBS: 0.20355672808732653
Fold 4 IBS: 0.2242978455111631
Fold 5 IBS: 0.21777645297475517
[I 2024-04-19 17:01:26,218] Trial 32 finished with value: 0.21596181194151506 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 17:02:11,091] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 17:02:58,702] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 17:03:09,334] Trial 35 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 17:04:12,992] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 17:04:14,897] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 17:04:46,611] Trial 38 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-19 17:05:29,199] Trial 39 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 17:06:08,998] Trial 40 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.2132255688615536
Fold 2 IBS: 0.22128032488867244
Fold 3 IBS: 0.20387628490474263
Fold 4 IBS: 0.22433695432297887
Fold 5 IBS: 0.21781307301495534
[I 2024-04-19 17:07:08,374] Trial 41 finished with value: 0.2161064411985806 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21292377393992548
Fold 2 IBS: 0.2210315141123993
Fold 3 IBS: 0.20354491815270298
Fold 4 IBS: 0.2240992473287711
Fold 5 IBS: 0.21771341609424547
[I 2024-04-19 17:08:12,196] Trial 42 finished with value: 0.21586257392560887 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 17:09:22,473] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 17:10:21,395] Trial 44 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21349094495081627
Fold 2 IBS: 0.22124593056297892
Fold 3 IBS: 0.204117127502029
Fold 4 IBS: 0.22430959830372146
Fold 5 IBS: 0.21795638009371607
[I 2024-04-19 17:11:23,853] Trial 45 finished with value: 0.21622399628265235 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 17:12:23,482] Trial 46 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 17:12:43,381] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 17:12:43,692] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 17:12:54,791] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 17:13:51,350] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21352229431826772
Fold 2 IBS: 0.22126527530151524
Fold 3 IBS: 0.20414449796344677
Fold 4 IBS: 0.22431579388786133
Fold 5 IBS: 0.2179677238529516
[I 2024-04-19 17:14:37,303] Trial 51 finished with value: 0.21624311706480853 and parameters: {'subsample': 0.8432391250804372, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.42932457769018856, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.012243529086999924, 'min_weight_fraction_leaf': 0.13427213537405694, 'max_features': 0.1, 'min_impurity_decrease': 7.107322942000855e-07, 'validation_fraction': 0.7779173644820415, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 17:16:01,507] Trial 52 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8647416200425169, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.27204051720793454, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.32951036616207574, 'min_weight_fraction_leaf': 0.0696136715803943, 'max_features': 0.1, 'min_impurity_decrease': 1.0411636207736935e-06, 'validation_fraction': 0.6649885450408526, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.2126658954267114
Fold 2 IBS: 0.22068287915798293
Fold 3 IBS: 0.20338530082480633
Fold 4 IBS: 0.22347723643576087
Fold 5 IBS: 0.21769588001309007
[I 2024-04-19 17:17:13,522] Trial 53 finished with value: 0.21558143837167032 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.35255575108470655, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.15399525160080688, 'max_features': 0.1, 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9519356083737385, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 17:19:54,229] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9637771314277555, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18483741622154692, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.16826656130652193, 'max_features': 0.1, 'min_impurity_decrease': 1.891916944791205e-07, 'validation_fraction': 0.9592695072789675, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 17:22:11,323] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.918589848048704, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.1366452847323028, 'n_estimators': 388, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.18967222528443176, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 18}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 17:25:40,509] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7513175598857118, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.35760497570906596, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.29279606045526263, 'max_features': 'auto', 'min_impurity_decrease': 1.1427991588661997e-07, 'validation_fraction': 0.9992935111116187, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 17:28:36,678] Trial 57 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9629672876565945, 'learning_rate': 0.03044321993695316, 'dropout_rate': 0.2654836627375681, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.3309371032482379, 'max_features': 0.1, 'min_impurity_decrease': 4.889527309942819e-07, 'validation_fraction': 0.8335980560573747, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 17:32:38,293] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9051869988846165, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.2230573971097521, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.46721256406858613, 'min_weight_fraction_leaf': 0.24217068500219807, 'max_features': 1, 'min_impurity_decrease': 3.3273145847446367e-06, 'validation_fraction': 0.9559266299158219, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 17:35:50,071] Trial 59 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.019139926132660745, 'dropout_rate': 0.3062756368166816, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.21472425517002308, 'max_features': 'auto', 'min_impurity_decrease': 3.097931869672697e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 17:37:25,262] Trial 60 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7996511669090498, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.47747471244727363, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2543538004837033, 'min_weight_fraction_leaf': 0.10444758350906072, 'max_features': 'log2', 'min_impurity_decrease': 1.4854430366731937e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 14}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-19 17:39:54,533] Trial 61 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8595582024746382, 'learning_rate': 0.009662456499934472, 'dropout_rate': 0.4098250163413181, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.2074917467600883, 'min_weight_fraction_leaf': 0.15724667461688366, 'max_features': 0.1, 'min_impurity_decrease': 7.257266102562462e-07, 'validation_fraction': 0.9258995897425243, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21325207586655212
Fold 2 IBS: 0.22108799107389968
Fold 3 IBS: 0.20389758437073804
Fold 4 IBS: 0.2241108961061006
Fold 5 IBS: 0.21791219598548248
[I 2024-04-19 17:41:56,878] Trial 62 finished with value: 0.21605214868055458 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.01537203137740326, 'dropout_rate': 0.5939902455485113, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.006733098283166955, 'max_features': 0.1, 'min_impurity_decrease': 1.7338007602824288e-07, 'validation_fraction': 0.7998452500875314, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 18:04:02,285] Trial 63 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9881778214681738, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.505857528523121, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.012712121434543151, 'max_features': 0.1, 'min_impurity_decrease': 1.7159806179406314e-07, 'validation_fraction': 0.8999002791146725, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.2125800253180546
Fold 2 IBS: 0.220545116087081
Fold 3 IBS: 0.20312883355084663
Fold 4 IBS: 0.22358482732038532
Fold 5 IBS: 0.21775488310537955
[I 2024-04-19 18:58:25,955] Trial 64 finished with value: 0.21551873707634944 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.04209806464905699, 'dropout_rate': 0.6515053075848445, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.04245308337653099, 'min_weight_fraction_leaf': 0.044350095557314374, 'max_features': 0.1, 'min_impurity_decrease': 4.491377932515504e-07, 'validation_fraction': 0.9610335014089881, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 64 with value: 0.21551873707634944.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 19:00:36,140] Trial 65 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9311291803826592, 'learning_rate': 0.04244875829612528, 'dropout_rate': 0.5880558715407225, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 1.1077392169505795, 'min_weight_fraction_leaf': 0.03983864282382592, 'max_features': 0.1, 'min_impurity_decrease': 2.999919245030034e-07, 'validation_fraction': 0.8593144487131367, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 64 with value: 0.21551873707634944.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 19:02:32,955] Trial 66 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9998769156045215, 'learning_rate': 0.05359198006915804, 'dropout_rate': 0.650983074619535, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.713342732410399, 'min_weight_fraction_leaf': 0.037327349410482574, 'max_features': 0.1, 'min_impurity_decrease': 4.636270239719423e-07, 'validation_fraction': 0.7909756969364712, 'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 18, 'max_depth': 19}. Best is trial 64 with value: 0.21551873707634944.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 19:04:30,790] Trial 67 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8945047973351204, 'learning_rate': 0.030289682188722505, 'dropout_rate': 0.6300169361769032, 'n_estimators': 452, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.0031545307195375498, 'max_features': 0.1, 'min_impurity_decrease': 1.5144854860302472e-07, 'validation_fraction': 0.9159589204002132, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 18}. Best is trial 64 with value: 0.21551873707634944.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 19:06:59,551] Trial 68 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9645805834192783, 'learning_rate': 0.023218721503037675, 'dropout_rate': 0.5615571763998418, 'n_estimators': 423, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997767788709036, 'min_weight_fraction_leaf': 0.05843575268694585, 'max_features': 0.1, 'min_impurity_decrease': 1.2087272488994307e-06, 'validation_fraction': 0.9686699003754374, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 64 with value: 0.21551873707634944.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 19:08:24,442] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.99887024513786, 'learning_rate': 0.08587936719454789, 'dropout_rate': 0.7428831629900855, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.030031923886697245, 'max_features': 'sqrt', 'min_impurity_decrease': 4.97276861765846e-07, 'validation_fraction': 0.8281891917990171, 'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 20}. Best is trial 64 with value: 0.21551873707634944.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 19:10:07,925] Trial 70 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.027338251310163056, 'dropout_rate': 0.7089882443645275, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.08410192190838273, 'max_features': 0.1, 'min_impurity_decrease': 1.0751704306840592e-07, 'validation_fraction': 0.7453979565756876, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 17}. Best is trial 64 with value: 0.21551873707634944.
Fold 1 IBS: 0.21378585210531365
Fold 2 IBS: 0.22151188719103732
Fold 3 IBS: 0.2043538062983644
Fold 4 IBS: 0.22466944012296305
Fold 5 IBS: 0.21807495402516008
[I 2024-04-19 19:12:07,271] Trial 71 finished with value: 0.21647918794856774 and parameters: {'subsample': 0.9414985144334991, 'learning_rate': 0.003968115896613653, 'dropout_rate': 0.5823696005202688, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.26779541644842847, 'max_features': 'auto', 'min_impurity_decrease': 2.7569586568543097e-07, 'validation_fraction': 0.9713376306080728, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 64 with value: 0.21551873707634944.
Fold 1 IBS: 0.21220418833650798
Fold 2 IBS: 0.22042207263837602
Fold 3 IBS: 0.20285738449953122
Fold 4 IBS: 0.22332862827581526
Fold 5 IBS: 0.21723149356958285
[I 2024-04-19 19:15:22,447] Trial 72 finished with value: 0.21520875346396268 and parameters: {'subsample': 0.9498773753497436, 'learning_rate': 0.009880743240604978, 'dropout_rate': 0.25030187864168324, 'n_estimators': 442, 'criterion': 'squared_error', 'ccp_alpha': 0.004793672160551997, 'min_weight_fraction_leaf': 0.05064701957266815, 'max_features': 'auto', 'min_impurity_decrease': 2.3215203093247524e-06, 'validation_fraction': 0.936460972995549, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 19:15:39,012] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.920760761939223, 'learning_rate': 0.016102732082041646, 'dropout_rate': 0.6213012350523704, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.06465519957873159, 'max_features': 'auto', 'min_impurity_decrease': 5.468956659515511e-06, 'validation_fraction': 0.8662757832984233, 'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 19:18:50,523] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8230892029035446, 'learning_rate': 0.05987785583368638, 'dropout_rate': 0.20192375679043018, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.370371857241124, 'min_weight_fraction_leaf': 0.05188888002939977, 'max_features': None, 'min_impurity_decrease': 2.7222990554600103e-06, 'validation_fraction': 0.9331744008199012, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 19:19:39,334] Trial 75 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.87711326947114, 'learning_rate': 0.011349868098961852, 'dropout_rate': 0.7982182448702262, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 1.194698393798027, 'min_weight_fraction_leaf': 0.015743638868849746, 'max_features': 'auto', 'min_impurity_decrease': 5.9734079360074814e-05, 'validation_fraction': 0.9957073825551704, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 18}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 19:23:38,762] Trial 76 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9717998493529779, 'learning_rate': 0.020285254602452306, 'dropout_rate': 0.16945167389703747, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.0962621052112238, 'max_features': 'auto', 'min_impurity_decrease': 6.135353898848802e-07, 'validation_fraction': 0.8995225231338432, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 19:26:50,582] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6527746876723795, 'learning_rate': 0.009617814274368723, 'dropout_rate': 0.23464360454432553, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.5872217111247551, 'min_weight_fraction_leaf': 0.12767889602965304, 'max_features': 1, 'min_impurity_decrease': 1.4509408420175117e-05, 'validation_fraction': 0.9291496186906082, 'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 5}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-19 19:29:56,924] Trial 78 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9412481314247185, 'learning_rate': 0.014013205775387057, 'dropout_rate': 0.13859848186436124, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.29419286253457877, 'min_weight_fraction_leaf': 0.052943967521367895, 'max_features': 0.1, 'min_impurity_decrease': 2.1434329740740177e-07, 'validation_fraction': 0.6158958959698865, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 19:33:21,056] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9126207967170201, 'learning_rate': 0.0011753775837182534, 'dropout_rate': 0.29054025396825206, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8367973848765441, 'min_weight_fraction_leaf': 0.0018798299029973327, 'max_features': 'auto', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.5338124134897904, 'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 12}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 19:34:40,520] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9710627523470323, 'learning_rate': 0.017685317600779724, 'dropout_rate': 0.3388723042222102, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.3004980772276427, 'max_features': 'log2', 'min_impurity_decrease': 1.0915642738877587e-06, 'validation_fraction': 0.8033655207154786, 'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21321043899438455
Fold 2 IBS: 0.2213401465932955
Fold 3 IBS: 0.20383192383279608
Fold 4 IBS: 0.22447154865937347
Fold 5 IBS: 0.21791922647063378
[I 2024-04-19 19:38:11,268] Trial 81 finished with value: 0.21615465691009667 and parameters: {'subsample': 0.9579178853393634, 'learning_rate': 0.006802404808842085, 'dropout_rate': 0.2523609841831704, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.2563778007434269, 'max_features': 'auto', 'min_impurity_decrease': 1.475357902881004e-06, 'validation_fraction': 0.9513185761421921, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 19:41:44,726] Trial 82 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9453987712590168, 'learning_rate': 0.009537962827339893, 'dropout_rate': 0.1892865857241059, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 0.2901659063159545, 'min_weight_fraction_leaf': 0.22662729175199345, 'max_features': 'auto', 'min_impurity_decrease': 2.05835958734699e-06, 'validation_fraction': 0.9745676430715979, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-19 19:43:41,522] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8909479551758591, 'learning_rate': 0.00450277377622531, 'dropout_rate': 0.6877929836754342, 'n_estimators': 492, 'criterion': 'squared_error', 'ccp_alpha': 0.6302736024968735, 'min_weight_fraction_leaf': 0.2701739605759479, 'max_features': 'auto', 'min_impurity_decrease': 3.5210043901131074e-07, 'validation_fraction': 0.8846072833938841, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.2139613284871823
Fold 2 IBS: 0.22156741247576545
Fold 3 IBS: 0.20450210614863562
Fold 4 IBS: 0.22472322474865014
Fold 5 IBS: 0.2181147167734584
[I 2024-04-19 19:47:11,705] Trial 84 finished with value: 0.21657375772673843 and parameters: {'subsample': 0.411624430892823, 'learning_rate': 0.013253369992371197, 'dropout_rate': 0.24027487512818702, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.214835028703023, 'min_weight_fraction_leaf': 0.17631296272227048, 'max_features': 'auto', 'min_impurity_decrease': 1.4523274478524455e-07, 'validation_fraction': 0.913099981360701, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.2129673111888308
Fold 2 IBS: 0.2209790270026334
Fold 3 IBS: 0.20363805672766896
Fold 4 IBS: 0.2240878382781251
Fold 5 IBS: 0.21772834196710608
[I 2024-04-19 19:50:10,209] Trial 85 finished with value: 0.21588011503287285 and parameters: {'subsample': 0.770335172495693, 'learning_rate': 0.007723843561328281, 'dropout_rate': 0.3134955782796943, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.20250430497823585, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.8427627969606453, 'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 19:52:12,190] Trial 86 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6258266362144153, 'learning_rate': 0.03629425342023726, 'dropout_rate': 0.2984129682976939, 'n_estimators': 373, 'criterion': 'squared_error', 'ccp_alpha': 0.9973471047062721, 'min_weight_fraction_leaf': 0.21352096515716423, 'max_features': 'sqrt', 'min_impurity_decrease': 7.922266013019743e-07, 'validation_fraction': 0.6826441761790084, 'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 6}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 19:55:13,887] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5620710546480945, 'learning_rate': 0.008505210809908712, 'dropout_rate': 0.3819983711228876, 'n_estimators': 452, 'criterion': 'squared_error', 'ccp_alpha': 0.4306337003019733, 'min_weight_fraction_leaf': 0.2041372504844265, 'max_features': 'auto', 'min_impurity_decrease': 0.0003255828305135596, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 19:57:49,484] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7762725560789899, 'learning_rate': 0.011111179381597284, 'dropout_rate': 0.3196243460718578, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 1.3457840140168202, 'min_weight_fraction_leaf': 0.026102976372990007, 'max_features': 0.1, 'min_impurity_decrease': 4.1842504540759167e-07, 'validation_fraction': 0.8468844412711507, 'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 8}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 20:00:02,560] Trial 89 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6969649633096852, 'learning_rate': 0.015358704013366007, 'dropout_rate': 0.5090990897137027, 'n_estimators': 428, 'criterion': 'squared_error', 'ccp_alpha': 1.5765552790097783, 'min_weight_fraction_leaf': 0.1967537060613447, 'max_features': 'auto', 'min_impurity_decrease': 2.1650730397688694e-07, 'validation_fraction': 0.8757107738634061, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 6}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 20:03:45,654] Trial 90 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7306151097727858, 'learning_rate': 0.0030759059571325367, 'dropout_rate': 0.20732155805323632, 'n_estimators': 439, 'criterion': 'squared_error', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.08382061902052879, 'max_features': 'auto', 'min_impurity_decrease': 6.014966438611826e-07, 'validation_fraction': 0.8287281797305409, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.213282442813215
Fold 2 IBS: 0.22113214368705078
Fold 3 IBS: 0.20394981416693883
Fold 4 IBS: 0.22428599721965942
Fold 5 IBS: 0.21790194149489853
[I 2024-04-19 20:07:15,696] Trial 91 finished with value: 0.21611046787635252 and parameters: {'subsample': 0.5185673050184334, 'learning_rate': 0.005831718220267968, 'dropout_rate': 0.2673714840258141, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.24422274988904982, 'max_features': 'auto', 'min_impurity_decrease': 9.079922261639684e-07, 'validation_fraction': 0.9411775770096612, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 20:08:27,060] Trial 92 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.978365732192231, 'learning_rate': 0.0076954842205835, 'dropout_rate': 0.23183821297416474, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 0.49211647913049955, 'min_weight_fraction_leaf': 0.23688053465240513, 'max_features': 'auto', 'min_impurity_decrease': 4.418613834721915e-06, 'validation_fraction': 0.9761923045843292, 'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 20:12:18,394] Trial 93 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.32126879099869027, 'learning_rate': 0.011783539264009723, 'dropout_rate': 0.2795436425709962, 'n_estimators': 492, 'criterion': 'squared_error', 'ccp_alpha': 0.20362952808416507, 'min_weight_fraction_leaf': 0.2585448454100403, 'max_features': 'auto', 'min_impurity_decrease': 2.0333609492231826e-06, 'validation_fraction': 0.9108508896652943, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 20:15:54,673] Trial 94 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9172531776495569, 'learning_rate': 0.01908907573521863, 'dropout_rate': 0.25483149782519043, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.6843293477116347, 'min_weight_fraction_leaf': 0.2228851842323061, 'max_features': None, 'min_impurity_decrease': 3.256681709458039e-06, 'validation_fraction': 0.9452356876786695, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 20:19:02,183] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8687843698527852, 'learning_rate': 0.0056488981484495914, 'dropout_rate': 0.33894348143511804, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 0.9601205383555245, 'min_weight_fraction_leaf': 0.2819750333077766, 'max_features': 'auto', 'min_impurity_decrease': 7.045012035510386e-06, 'validation_fraction': 0.9999690268176494, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 17}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.2136208609230697
Fold 2 IBS: 0.22134365318813834
Fold 3 IBS: 0.2042334222298263
Fold 4 IBS: 0.22441515929806466
Fold 5 IBS: 0.21802029480715251
[I 2024-04-19 20:22:24,324] Trial 96 finished with value: 0.21632667808925032 and parameters: {'subsample': 0.950254432591521, 'learning_rate': 0.0022102389630717766, 'dropout_rate': 0.1723932907588553, 'n_estimators': 454, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03063069674161246, 'min_weight_fraction_leaf': 0.04286122246886014, 'max_features': 0.1, 'min_impurity_decrease': 1.4068682575292907e-06, 'validation_fraction': 0.7629864192147846, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 20:24:40,194] Trial 97 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9794281118885965, 'learning_rate': 0.07256682880833759, 'dropout_rate': 0.31363079093592194, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.43382189055208925, 'min_weight_fraction_leaf': 0.23620687573013183, 'max_features': 'auto', 'min_impurity_decrease': 0.001290583661990368, 'validation_fraction': 0.8431515725718495, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 20:28:30,132] Trial 98 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9034099191841783, 'learning_rate': 0.022872500438115773, 'dropout_rate': 0.11590233860021854, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.23384794026040234, 'min_weight_fraction_leaf': 0.2938783217761457, 'max_features': 1, 'min_impurity_decrease': 2.598305776222351e-07, 'validation_fraction': 0.8923308676191493, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21161311616211623
Fold 2 IBS: 0.2200506929100543

Fold 3 IBS: 0.2023614521860876
Fold 4 IBS: 0.2231898890507258
Fold 5 IBS: 0.2170482819994517
[I 2024-04-19 20:30:13,859] Trial 99 finished with value: 0.2148526864616871 and parameters: {'subsample': 0.8333920238412017, 'learning_rate': 0.02538174390008161, 'dropout_rate': 0.4577965489047534, 'n_estimators': 399, 'criterion': 'squared_error', 'ccp_alpha': 0.004367047248614303, 'min_weight_fraction_leaf': 0.18072249935794454, 'max_features': 'auto', 'min_impurity_decrease': 4.472271308488144e-07, 'validation_fraction': 0.9580200141092102, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 99 with value: 0.2148526864616871.


* Best trial for IBS:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.2148526864616871], datetime_start=datetime.datetime(2024, 4, 19, 20, 28, 30, 138358), datetime_complete=datetime.datetime(2024, 4, 19, 20, 30, 13, 858991), params={'subsample': 0.8333920238412017, 'learning_rate': 0.02538174390008161, 'dropout_rate': 0.4577965489047534, 'n_estimators': 399, 'criterion': 'squared_error', 'ccp_alpha': 0.004367047248614303, 'min_weight_fraction_leaf': 0.18072249935794454, 'max_features': 'auto', 'min_impurity_decrease': 4.472271308488144e-07, 'validation_fraction': 0.9580200141092102, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 5}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=99, value=None)


* Best Score for IBS:
 0.2148526864616871

In [68]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [69]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.791
train_ibs:  0.215

#### Test

In [70]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [71]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.030433464476024484,
                                 criterion='squared_error',
                                 dropout_rate=0.6934300990357392,
                                 learning_rate=0.05396213117321635, max_depth=7,
                                 max_features=1, max_leaf_nodes=10,
                                 min_impurity_decrease=3.7676942671090066e-07,
                                 min_samples_leaf=11, min_samples_split=20,
                                 min_weight_fraction_leaf=0.38729753243593296,
                                 n_estimators=424, random_state=123,
                                 subsample=0.38604321258984187,
                                 validation_fraction=0.9213195792266449)

C-index score: 0.63

GradientBoostingSurvivalAnalysis(ccp_alpha=0.004367047248614303,
                                 criterion='squared_error',
                                 dropout_rate=0.4577965489047534,
                                 learning_rate=0.02538174390008161, max_depth=5,
                                 max_features='auto', max_leaf_nodes=17,
                                 min_impurity_decrease=4.472271308488144e-07,
                                 min_samples_leaf=14, min_samples_split=3,
                                 min_weight_fraction_leaf=0.18072249935794454,
                                 n_estimators=399, random_state=123,
                                 subsample=0.8333920238412017,
                                 validation_fraction=0.9580200141092102)

IBS: 0.22

In [72]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [73]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [74]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 20:30:49,325] A new study created in memory with name: no-name-5b32c148-d21d-4b53-bc25-cf1dd7a0ce02

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:30:51,457] Trial 0 finished with value: 0.7050413460251115 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.7050413460251115.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:31:11,533] Trial 1 finished with value: 0.7134801645905124 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.7134801645905124.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:31:15,488] Trial 2 finished with value: 0.7269000780104259 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.7269000780104259.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:31:20,858] Trial 3 finished with value: 0.7269000780104259 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 2 with value: 0.7269000780104259.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:31:29,249] Trial 4 finished with value: 0.7249661283661262 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 2 with value: 0.7269000780104259.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:31:39,060] Trial 5 finished with value: 0.7050413460251115 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 2 with value: 0.7269000780104259.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-19 20:31:43,365] Trial 6 finished with value: 0.6994075432082101 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 2 with value: 0.7269000780104259.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:31:44,274] Trial 7 finished with value: 0.7134801645905124 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 2 with value: 0.7269000780104259.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:31:49,249] Trial 8 finished with value: 0.7269000780104259 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 2 with value: 0.7269000780104259.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:32:04,921] Trial 9 finished with value: 0.7181184324408056 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 2 with value: 0.7269000780104259.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-19 20:32:14,113] Trial 10 finished with value: 0.6684464087544287 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7165502912345604, 'n_estimators': 322, 'learning_rate': 0.09279671898160717}. Best is trial 2 with value: 0.7269000780104259.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:32:16,666] Trial 11 finished with value: 0.730534035685945 and parameters: {'subsample': 0.1795750652194426, 'dropout_rate': 0.10580803679784617, 'n_estimators': 112, 'learning_rate': 0.08422813202882692}. Best is trial 11 with value: 0.730534035685945.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:32:17,868] Trial 12 finished with value: 0.7259927715393196 and parameters: {'subsample': 0.12126277795618136, 'dropout_rate': 0.11480483431808647, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.730534035685945.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:32:20,325] Trial 13 finished with value: 0.7258100102226663 and parameters: {'subsample': 0.11657241455516312, 'dropout_rate': 0.2649484511305312, 'n_estimators': 109, 'learning_rate': 0.08294176027144856}. Best is trial 11 with value: 0.730534035685945.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:32:22,967] Trial 14 finished with value: 0.7312863779849612 and parameters: {'subsample': 0.3151966174332776, 'dropout_rate': 0.683552108544888, 'n_estimators': 126, 'learning_rate': 0.0025916531369806137}. Best is trial 14 with value: 0.7312863779849612.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:32:23,525] Trial 15 finished with value: 0.7269000780104259 and parameters: {'subsample': 0.28095289945270646, 'dropout_rate': 0.7007560774287221, 'n_estimators': 18, 'learning_rate': 0.01041399690405663}. Best is trial 14 with value: 0.7312863779849612.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:32:25,948] Trial 16 finished with value: 0.7282645363369096 and parameters: {'subsample': 0.25470623831733574, 'dropout_rate': 0.7977734229949851, 'n_estimators': 110, 'learning_rate': 0.0022091115777638677}. Best is trial 14 with value: 0.7312863779849612.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:32:34,707] Trial 17 finished with value: 0.7354069860168252 and parameters: {'subsample': 0.1881702656764814, 'dropout_rate': 0.6004730897368156, 'n_estimators': 274, 'learning_rate': 0.036208666639295596}. Best is trial 17 with value: 0.7354069860168252.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:32:42,807] Trial 18 finished with value: 0.7332918666015815 and parameters: {'subsample': 0.3747153802011338, 'dropout_rate': 0.6128759072409393, 'n_estimators': 289, 'learning_rate': 0.023993239507840394}. Best is trial 17 with value: 0.7354069860168252.

Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:32:53,414] Trial 19 finished with value: 0.7263292167545311 and parameters: {'subsample': 0.38793667853472646, 'dropout_rate': 0.9886702916742889, 'n_estimators': 389, 'learning_rate': 0.03581156563064805}. Best is trial 17 with value: 0.7354069860168252.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:33:03,506] Trial 20 finished with value: 0.7189623142973457 and parameters: {'subsample': 0.40098308855786013, 'dropout_rate': 0.5777838682216713, 'n_estimators': 282, 'learning_rate': 0.018557750753843378}. Best is trial 17 with value: 0.7354069860168252.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:33:13,690] Trial 21 finished with value: 0.730552091174725 and parameters: {'subsample': 0.31007656442715725, 'dropout_rate': 0.6080226687634136, 'n_estimators': 314, 'learning_rate': 0.0016108337344105245}. Best is trial 17 with value: 0.7354069860168252.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:33:28,786] Trial 22 finished with value: 0.7363873781736879 and parameters: {'subsample': 0.19888785377279644, 'dropout_rate': 0.773304513209339, 'n_estimators': 419, 'learning_rate': 0.021483146767154602}. Best is trial 22 with value: 0.7363873781736879.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:33:43,684] Trial 23 finished with value: 0.7346557764420861 and parameters: {'subsample': 0.19640309314421656, 'dropout_rate': 0.7853619077403635, 'n_estimators': 421, 'learning_rate': 0.025180183341136995}. Best is trial 22 with value: 0.7363873781736879.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:33:57,397] Trial 24 finished with value: 0.7364800504554891 and parameters: {'subsample': 0.19720622899976611, 'dropout_rate': 0.7849086113594901, 'n_estimators': 403, 'learning_rate': 0.0384610579025747}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:34:12,152] Trial 25 finished with value: 0.7346557764420861 and parameters: {'subsample': 0.19253392231287075, 'dropout_rate': 0.80027131573048, 'n_estimators': 422, 'learning_rate': 0.04156964188672584}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:34:21,668] Trial 26 finished with value: 0.7346660509776773 and parameters: {'subsample': 0.10536268643700308, 'dropout_rate': 0.9033524027816504, 'n_estimators': 348, 'learning_rate': 0.03445494213524592}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:34:35,148] Trial 27 finished with value: 0.7279804711070639 and parameters: {'subsample': 0.19672913081172647, 'dropout_rate': 0.9861686560685959, 'n_estimators': 457, 'learning_rate': 0.013267250166921972}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:34:48,351] Trial 28 finished with value: 0.7269000780104259 and parameters: {'subsample': 0.6158659495764146, 'dropout_rate': 0.8483862066956513, 'n_estimators': 423, 'learning_rate': 0.041301762705626334}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-19 20:34:59,959] Trial 29 finished with value: 0.6994075432082101 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.767710047443791, 'n_estimators': 386, 'learning_rate': 0.06046208382653473}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:35:06,022] Trial 30 finished with value: 0.7269000780104259 and parameters: {'subsample': 0.42912384995164, 'dropout_rate': 0.5220600917153093, 'n_estimators': 231, 'learning_rate': 0.029890320834417453}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:35:15,817] Trial 31 finished with value: 0.733926485876608 and parameters: {'subsample': 0.10810163087825958, 'dropout_rate': 0.9271779254835972, 'n_estimators': 348, 'learning_rate': 0.03627883860525388}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:35:24,663] Trial 32 finished with value: 0.7317445215415783 and parameters: {'subsample': 0.1725048391764919, 'dropout_rate': 0.9006234235846082, 'n_estimators': 332, 'learning_rate': 0.04468035811091154}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:35:36,362] Trial 33 finished with value: 0.7347922867424088 and parameters: {'subsample': 0.24499669367542812, 'dropout_rate': 0.842378429990557, 'n_estimators': 388, 'learning_rate': 0.015910493614839247}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:35:52,320] Trial 34 finished with value: 0.7294121369840015 and parameters: {'subsample': 0.2345763946997951, 'dropout_rate': 0.7391843406056609, 'n_estimators': 456, 'learning_rate': 0.014993859160161504}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:36:06,331] Trial 35 finished with value: 0.7258100102226663 and parameters: {'subsample': 0.34740791626784456, 'dropout_rate': 0.43975685710717877, 'n_estimators': 391, 'learning_rate': 0.008837999659231398}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:36:23,783] Trial 36 finished with value: 0.7288193567188459 and parameters: {'subsample': 0.22469012581745307, 'dropout_rate': 0.8386599315571716, 'n_estimators': 489, 'learning_rate': 0.028075405474016223}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:36:40,732] Trial 37 finished with value: 0.7243971764543351 and parameters: {'subsample': 0.2930893821263537, 'dropout_rate': 0.6419633004375442, 'n_estimators': 443, 'learning_rate': 0.01948324726663577}. Best is trial 24 with value: 0.7364800504554891.

Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:36:48,727] Trial 38 finished with value: 0.7262438731307043 and parameters: {'subsample': 0.15641343956091833, 'dropout_rate': 0.4858948540883464, 'n_estimators': 255, 'learning_rate': 0.04752117784348376}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:37:01,672] Trial 39 finished with value: 0.7311218197063425 and parameters: {'subsample': 0.2348903699073315, 'dropout_rate': 0.7545555141153719, 'n_estimators': 382, 'learning_rate': 0.05598015324329953}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:37:09,117] Trial 40 finished with value: 0.7134801645905124 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.8306991111737034, 'n_estimators': 299, 'learning_rate': 0.01978847442977622}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:37:19,354] Trial 41 finished with value: 0.7310560626785602 and parameters: {'subsample': 0.14241027574272405, 'dropout_rate': 0.9316712114943406, 'n_estimators': 362, 'learning_rate': 0.03627583840893524}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:37:29,560] Trial 42 finished with value: 0.7346660509776773 and parameters: {'subsample': 0.10326693027833479, 'dropout_rate': 0.8701703361280347, 'n_estimators': 345, 'learning_rate': 0.03211779625836258}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:37:42,020] Trial 43 finished with value: 0.727858470573435 and parameters: {'subsample': 0.16256801974906646, 'dropout_rate': 0.9339744762032774, 'n_estimators': 412, 'learning_rate': 0.03904783367584303}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:37:54,076] Trial 44 finished with value: 0.734625944536553 and parameters: {'subsample': 0.33613208220676527, 'dropout_rate': 0.7287364748201348, 'n_estimators': 368, 'learning_rate': 0.026403058808242764}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:38:05,444] Trial 45 finished with value: 0.723100429332011 and parameters: {'subsample': 0.27057003847086775, 'dropout_rate': 0.295844522167053, 'n_estimators': 315, 'learning_rate': 0.04911179757768285}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:38:12,873] Trial 46 finished with value: 0.7269000780104259 and parameters: {'subsample': 0.4451355232202907, 'dropout_rate': 0.6541283222333161, 'n_estimators': 268, 'learning_rate': 0.033006145810578}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:38:17,880] Trial 47 finished with value: 0.728709761672542 and parameters: {'subsample': 0.22211223520536705, 'dropout_rate': 0.8703162942164708, 'n_estimators': 224, 'learning_rate': 0.008209618821055878}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:38:31,311] Trial 48 finished with value: 0.73021218082202 and parameters: {'subsample': 0.13838388586618308, 'dropout_rate': 0.9654294453083443, 'n_estimators': 445, 'learning_rate': 0.016421361393690662}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:38:48,619] Trial 49 finished with value: 0.7134801645905124 and parameters: {'subsample': 0.7668464497051921, 'dropout_rate': 0.8100358365823181, 'n_estimators': 497, 'learning_rate': 0.02323847007634191}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:39:00,688] Trial 50 finished with value: 0.7272825078020642 and parameters: {'subsample': 0.2645200844122574, 'dropout_rate': 0.8792454501205662, 'n_estimators': 400, 'learning_rate': 0.044915143453107126}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:39:10,955] Trial 51 finished with value: 0.7346660509776773 and parameters: {'subsample': 0.10366139779505672, 'dropout_rate': 0.855265004409347, 'n_estimators': 353, 'learning_rate': 0.03307858002044434}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:39:21,180] Trial 52 finished with value: 0.7319052228259333 and parameters: {'subsample': 0.14058021859676617, 'dropout_rate': 0.7059145910178407, 'n_estimators': 337, 'learning_rate': 0.03214950723318046}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:39:24,598] Trial 53 finished with value: 0.726612467058494 and parameters: {'subsample': 0.18647753030348274, 'dropout_rate': 0.8973718150195135, 'n_estimators': 165, 'learning_rate': 0.02177727520287163}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:39:34,470] Trial 54 finished with value: 0.7287755187003244 and parameters: {'subsample': 0.20614576673879711, 'dropout_rate': 0.9541550883992531, 'n_estimators': 370, 'learning_rate': 0.0278643565626658}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:39:42,802] Trial 55 finished with value: 0.7310560626785602 and parameters: {'subsample': 0.10922149417338406, 'dropout_rate': 0.8255398546066728, 'n_estimators': 304, 'learning_rate': 0.053343545412390905}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:39:52,935] Trial 56 finished with value: 0.730064167071065 and parameters: {'subsample': 0.16068157365098634, 'dropout_rate': 0.7816864337395739, 'n_estimators': 341, 'learning_rate': 0.03793989794780022}. Best is trial 24 with value: 0.7364800504554891.

Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:40:09,058] Trial 57 finished with value: 0.7214126656189308 and parameters: {'subsample': 0.24798896819819122, 'dropout_rate': 0.3879390994919589, 'n_estimators': 409, 'learning_rate': 0.06795033768066108}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:40:24,364] Trial 58 finished with value: 0.7243971764543351 and parameters: {'subsample': 0.2938069376499025, 'dropout_rate': 0.6895827577928959, 'n_estimators': 434, 'learning_rate': 0.012392235987901283}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:40:32,156] Trial 59 finished with value: 0.7269000780104259 and parameters: {'subsample': 0.5273734082595787, 'dropout_rate': 0.6142814989982612, 'n_estimators': 286, 'learning_rate': 0.04107183207053723}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:40:48,482] Trial 60 finished with value: 0.731383195833318 and parameters: {'subsample': 0.13533132756896432, 'dropout_rate': 0.7627599956001129, 'n_estimators': 465, 'learning_rate': 0.006049646926689202}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:40:58,932] Trial 61 finished with value: 0.7346660509776773 and parameters: {'subsample': 0.10701828114968492, 'dropout_rate': 0.8666101560532868, 'n_estimators': 358, 'learning_rate': 0.03229316615452055}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:41:07,832] Trial 62 finished with value: 0.7326834886777286 and parameters: {'subsample': 0.17635151219210132, 'dropout_rate': 0.8488248597093956, 'n_estimators': 326, 'learning_rate': 0.029144767138469883}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:41:18,501] Trial 63 finished with value: 0.7305071204319262 and parameters: {'subsample': 0.21422694019013236, 'dropout_rate': 0.902421961820965, 'n_estimators': 376, 'learning_rate': 0.03577631654988743}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:41:28,949] Trial 64 finished with value: 0.7346660509776773 and parameters: {'subsample': 0.1044235710102068, 'dropout_rate': 0.7851538132707552, 'n_estimators': 352, 'learning_rate': 0.03328559792119756}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:41:41,276] Trial 65 finished with value: 0.7330002062738579 and parameters: {'subsample': 0.13550391202338308, 'dropout_rate': 0.8108066009100184, 'n_estimators': 393, 'learning_rate': 0.030001036153430104}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:41:52,802] Trial 66 finished with value: 0.7330606850108072 and parameters: {'subsample': 0.10110624125186292, 'dropout_rate': 0.9957905427700171, 'n_estimators': 410, 'learning_rate': 0.023790759362737605}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:41:59,430] Trial 67 finished with value: 0.7354069860168252 and parameters: {'subsample': 0.1862385409778341, 'dropout_rate': 0.8842124187885858, 'n_estimators': 266, 'learning_rate': 0.017269760739365172}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:42:05,310] Trial 68 finished with value: 0.7238492259089409 and parameters: {'subsample': 0.3182589437686628, 'dropout_rate': 0.917951072434923, 'n_estimators': 258, 'learning_rate': 0.014515749929185761}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:42:10,685] Trial 69 finished with value: 0.7287535996910638 and parameters: {'subsample': 0.19584421844663516, 'dropout_rate': 0.9567866120521584, 'n_estimators': 238, 'learning_rate': 0.017843865496468762}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-19 20:42:18,683] Trial 70 finished with value: 0.6684464087544287 and parameters: {'subsample': 0.9847790608248583, 'dropout_rate': 0.1806794570956778, 'n_estimators': 267, 'learning_rate': 0.021486247232188352}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:42:23,378] Trial 71 finished with value: 0.7239443111885511 and parameters: {'subsample': 0.15660938617660758, 'dropout_rate': 0.8838298526710209, 'n_estimators': 213, 'learning_rate': 0.02669714184865344}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:42:31,897] Trial 72 finished with value: 0.7325804008372989 and parameters: {'subsample': 0.18221961371082168, 'dropout_rate': 0.8594610191936198, 'n_estimators': 308, 'learning_rate': 0.041596502412255404}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:42:35,726] Trial 73 finished with value: 0.7313422231078204 and parameters: {'subsample': 0.2481045906819338, 'dropout_rate': 0.7417712112091082, 'n_estimators': 171, 'learning_rate': 0.010922529623487548}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:42:45,265] Trial 74 finished with value: 0.7364195717185398 and parameters: {'subsample': 0.12902048808771427, 'dropout_rate': 0.8250957984468636, 'n_estimators': 327, 'learning_rate': 0.0056632449562852676}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:42:52,747] Trial 75 finished with value: 0.7305071204319262 and parameters: {'subsample': 0.21834059626142782, 'dropout_rate': 0.8190941234148006, 'n_estimators': 277, 'learning_rate': 0.006413601939862857}. Best is trial 24 with value: 0.7364800504554891.

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:43:01,828] Trial 76 finished with value: 0.7050413460251115 and parameters: {'subsample': 0.7049649344689567, 'dropout_rate': 0.5148028603600525, 'n_estimators': 294, 'learning_rate': 0.004486439552776535}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:43:06,632] Trial 77 finished with value: 0.7311706539696219 and parameters: {'subsample': 0.12652471090374667, 'dropout_rate': 0.7226081922493118, 'n_estimators': 189, 'learning_rate': 0.017746149319862653}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:43:16,699] Trial 78 finished with value: 0.730064167071065 and parameters: {'subsample': 0.15817153111318055, 'dropout_rate': 0.7941746266467619, 'n_estimators': 328, 'learning_rate': 0.013568161518421608}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:43:33,045] Trial 79 finished with value: 0.7243971764543351 and parameters: {'subsample': 0.2895725841840603, 'dropout_rate': 0.5707573707181093, 'n_estimators': 430, 'learning_rate': 0.020618690829549164}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:43:43,093] Trial 80 finished with value: 0.7339484048858689 and parameters: {'subsample': 0.2424133447509762, 'dropout_rate': 0.6672103733563493, 'n_estimators': 319, 'learning_rate': 0.047272852756699166}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:43:53,116] Trial 81 finished with value: 0.7317445215415783 and parameters: {'subsample': 0.17557426729891612, 'dropout_rate': 0.8309682894631459, 'n_estimators': 342, 'learning_rate': 0.033715796978277555}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:43:59,002] Trial 82 finished with value: 0.7354777392893656 and parameters: {'subsample': 0.1276105258513922, 'dropout_rate': 0.848808151795058, 'n_estimators': 243, 'learning_rate': 0.0244747299793845}. Best is trial 24 with value: 0.7364800504554891.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:44:04,708] Trial 83 finished with value: 0.73734585132129 and parameters: {'subsample': 0.20471187836593263, 'dropout_rate': 0.892001983552212, 'n_estimators': 237, 'learning_rate': 0.02617536005560058}. Best is trial 83 with value: 0.73734585132129.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:44:09,139] Trial 84 finished with value: 0.7257685852019538 and parameters: {'subsample': 0.20606444490021084, 'dropout_rate': 0.9407712911929249, 'n_estimators': 205, 'learning_rate': 0.02455478881568339}. Best is trial 83 with value: 0.73734585132129.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:44:14,957] Trial 85 finished with value: 0.725197723946059 and parameters: {'subsample': 0.23085615118977554, 'dropout_rate': 0.9212587882142669, 'n_estimators': 249, 'learning_rate': 0.009642250739189243}. Best is trial 83 with value: 0.73734585132129.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:44:20,530] Trial 86 finished with value: 0.726438625945524 and parameters: {'subsample': 0.2621763385729981, 'dropout_rate': 0.8915873469583229, 'n_estimators': 245, 'learning_rate': 0.025348535966907202}. Best is trial 83 with value: 0.73734585132129.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:44:25,303] Trial 87 finished with value: 0.7236245515240409 and parameters: {'subsample': 0.15366485952498626, 'dropout_rate': 0.9668984108793292, 'n_estimators': 224, 'learning_rate': 0.030376564352223474}. Best is trial 83 with value: 0.73734585132129.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:44:32,548] Trial 88 finished with value: 0.7327928016779574 and parameters: {'subsample': 0.12559758471238755, 'dropout_rate': 0.7597030608925517, 'n_estimators': 272, 'learning_rate': 0.015557371541293085}. Best is trial 83 with value: 0.73734585132129.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:44:35,269] Trial 89 finished with value: 0.7296901538294047 and parameters: {'subsample': 0.20092548673671964, 'dropout_rate': 0.9099237195470591, 'n_estimators': 143, 'learning_rate': 0.03883351083255216}. Best is trial 83 with value: 0.73734585132129.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:44:52,065] Trial 90 finished with value: 0.7283200188291008 and parameters: {'subsample': 0.17748628631400687, 'dropout_rate': 0.8389483056285977, 'n_estimators': 482, 'learning_rate': 0.02228782515461549}. Best is trial 83 with value: 0.73734585132129.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:44:58,372] Trial 91 finished with value: 0.7344973471325028 and parameters: {'subsample': 0.14257324181311806, 'dropout_rate': 0.8783017908098796, 'n_estimators': 258, 'learning_rate': 0.027061883543259335}. Best is trial 83 with value: 0.73734585132129.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:45:10,308] Trial 92 finished with value: 0.7355756898619996 and parameters: {'subsample': 0.12923025540393152, 'dropout_rate': 0.8012434889777345, 'n_estimators': 374, 'learning_rate': 0.035200609073618945}. Best is trial 83 with value: 0.73734585132129.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:45:22,572] Trial 93 finished with value: 0.7329022557012237 and parameters: {'subsample': 0.1254059598192928, 'dropout_rate': 0.7802727225161133, 'n_estimators': 377, 'learning_rate': 0.03616708163321947}. Best is trial 83 with value: 0.73734585132129.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 20:45:35,320] Trial 94 finished with value: 0.7292565729674421 and parameters: {'subsample': 0.1684155480062036, 'dropout_rate': 0.8134847130564093, 'n_estimators': 400, 'learning_rate': 0.01929728585088121}. Best is trial 83 with value: 0.73734585132129.

Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:45:41,064] Trial 95 finished with value: 0.7318072722532991 and parameters: {'subsample': 0.19478302132706196, 'dropout_rate': 0.840047225271219, 'n_estimators': 235, 'learning_rate': 0.04233641672127157}. Best is trial 83 with value: 0.73734585132129.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:45:48,930] Trial 96 finished with value: 0.7304040325914967 and parameters: {'subsample': 0.2324088772765509, 'dropout_rate': 0.7435048403980886, 'n_estimators': 286, 'learning_rate': 0.08791879465920027}. Best is trial 83 with value: 0.73734585132129.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:45:59,634] Trial 97 finished with value: 0.7328636959735352 and parameters: {'subsample': 0.14879998281460616, 'dropout_rate': 0.8533131389038322, 'n_estimators': 369, 'learning_rate': 0.03493249427581202}. Best is trial 83 with value: 0.73734585132129.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.6897321428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:46:12,695] Trial 98 finished with value: 0.7339248238193802 and parameters: {'subsample': 0.2720972336490123, 'dropout_rate': 0.8002484045704562, 'n_estimators': 416, 'learning_rate': 0.011912944017469534}. Best is trial 83 with value: 0.73734585132129.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7932489451476793

[I 2024-04-19 20:46:25,695] A new study created in memory with name: no-name-f9630321-41db-4c4b-9672-ff31a7be3569

Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 20:46:25,679] Trial 99 finished with value: 0.7329022557012237 and parameters: {'subsample': 0.12594500884563328, 'dropout_rate': 0.7742443333471122, 'n_estimators': 400, 'learning_rate': 0.029802971570306064}. Best is trial 83 with value: 0.73734585132129.


* Best trial for C-index:
 FrozenTrial(number=83, state=TrialState.COMPLETE, values=[0.73734585132129], datetime_start=datetime.datetime(2024, 4, 19, 20, 43, 59, 7064), datetime_complete=datetime.datetime(2024, 4, 19, 20, 44, 4, 707957), params={'subsample': 0.20471187836593263, 'dropout_rate': 0.892001983552212, 'n_estimators': 237, 'learning_rate': 0.02617536005560058}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=83, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.20471187836593263, 'dropout_rate': 0.892001983552212, 'n_estimators': 237, 'learning_rate': 0.02617536005560058}


* Best Score for C-index:
 0.73734585132129

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.18504584755520848
Fold 2 IBS: 0.24179973682352504
Fold 3 IBS: 0.16652277988504283
Fold 4 IBS: 0.16884354353720807
Fold 5 IBS: 0.23318480871469416
[I 2024-04-19 20:46:28,187] Trial 0 finished with value: 0.19907934330313573 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.19907934330313573.
Fold 1 IBS: 0.20370621643796663
Fold 2 IBS: 0.2887077060706083
Fold 3 IBS: 0.17786466393154174
Fold 4 IBS: 0.1729408126951147
Fold 5 IBS: 0.27370157532625616
[I 2024-04-19 20:46:48,610] Trial 1 finished with value: 0.22338419489229752 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.19907934330313573.
Fold 1 IBS: 0.19661103906383703
Fold 2 IBS: 0.2697617358478736
Fold 3 IBS: 0.17326819431573745
Fold 4 IBS: 0.16863180341613299
Fold 5 IBS: 0.26506003175161774
[I 2024-04-19 20:46:52,833] Trial 2 finished with value: 0.21466656087903974 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.19907934330313573.
Fold 1 IBS: 0.19558922476579008
Fold 2 IBS: 0.2588149025222109
Fold 3 IBS: 0.17441636128502397
Fold 4 IBS: 0.16640724372364674
Fold 5 IBS: 0.26786281926556355
[I 2024-04-19 20:46:58,025] Trial 3 finished with value: 0.21261811031244707 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.19907934330313573.
Fold 1 IBS: 0.1816397581958329
Fold 2 IBS: 0.2618588038036953
Fold 3 IBS: 0.17721609401514016
Fold 4 IBS: 0.15704827829145504
Fold 5 IBS: 0.26907192503413213
[I 2024-04-19 20:47:06,312] Trial 4 finished with value: 0.2093669718680511 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.19907934330313573.
Fold 1 IBS: 0.2034038137478441
Fold 2 IBS: 0.2925705333362545
Fold 3 IBS: 0.17735124415038447
Fold 4 IBS: 0.17296509678740618
Fold 5 IBS: 0.27369201709429525
[I 2024-04-19 20:47:16,335] Trial 5 finished with value: 0.22399654102323688 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.19907934330313573.
Fold 1 IBS: 0.1829350490073511
Fold 2 IBS: 0.2262263682377508
Fold 3 IBS: 0.16835041796328792
Fold 4 IBS: 0.17503140974461442
Fold 5 IBS: 0.21906832093288123
[I 2024-04-19 20:47:20,381] Trial 6 finished with value: 0.1943223131771771 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.1943223131771771.
Fold 1 IBS: 0.19214719797969118
Fold 2 IBS: 0.2128201614141725
Fold 3 IBS: 0.1799104773209782
Fold 4 IBS: 0.1935331143149517
Fold 5 IBS: 0.21130288993503846
[I 2024-04-19 20:47:21,442] Trial 7 finished with value: 0.1979427681929664 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 6 with value: 0.1943223131771771.
Fold 1 IBS: 0.18346229658054838
Fold 2 IBS: 0.23288837924539724
Fold 3 IBS: 0.1663728821856144
Fold 4 IBS: 0.16598021194530657
Fold 5 IBS: 0.2349628428332706
[I 2024-04-19 20:47:26,573] Trial 8 finished with value: 0.19673332255802745 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 6 with value: 0.1943223131771771.
Fold 1 IBS: 0.19774970561168884
Fold 2 IBS: 0.2786299873761071
Fold 3 IBS: 0.1786486599311063
Fold 4 IBS: 0.16750965676761465
Fold 5 IBS: 0.2758493284841276
[I 2024-04-19 20:47:41,509] Trial 9 finished with value: 0.21967746763412893 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 6 with value: 0.1943223131771771.
Fold 1 IBS: 0.20616654651074987
Fold 2 IBS: 0.22019853996541608
Fold 3 IBS: 0.19591847333365484
Fold 4 IBS: 0.21447109608248688
Fold 5 IBS: 0.21438910885653592
[I 2024-04-19 20:47:51,225] Trial 10 finished with value: 0.2102287529497687 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7165502912345604, 'n_estimators': 328, 'learning_rate': 0.0017980531969980576}. Best is trial 6 with value: 0.1943223131771771.
Fold 1 IBS: 0.21324112237551676
Fold 2 IBS: 0.22143258186383077
Fold 3 IBS: 0.20378357472890044
Fold 4 IBS: 0.22373613296613537
Fold 5 IBS: 0.21772180706762184
[I 2024-04-19 20:47:51,763] Trial 11 finished with value: 0.21598304380040104 and parameters: {'subsample': 0.8998204419591818, 'dropout_rate': 0.6187929667736369, 'n_estimators': 2, 'learning_rate': 0.024813147376298014}. Best is trial 6 with value: 0.1943223131771771.
Fold 1 IBS: 0.1719787063814147
Fold 2 IBS: 0.25932284309500886
Fold 3 IBS: 0.1747859367168122
Fold 4 IBS: 0.1538406898328061
Fold 5 IBS: 0.25993209358572184
[I 2024-04-19 20:47:54,764] Trial 12 finished with value: 0.2039720539223527 and parameters: {'subsample': 0.17298802250354745, 'dropout_rate': 0.35395926148542006, 'n_estimators': 128, 'learning_rate': 0.09635955935176935}. Best is trial 6 with value: 0.1943223131771771.
Fold 1 IBS: 0.1849916035399971
Fold 2 IBS: 0.24039544971574525
Fold 3 IBS: 0.16688927698647557
Fold 4 IBS: 0.16814850357459274
Fold 5 IBS: 0.23443367447671928
[I 2024-04-19 20:48:02,079] Trial 13 finished with value: 0.19897170165870598 and parameters: {'subsample': 0.6414918362778363, 'dropout_rate': 0.5102404640249664, 'n_estimators': 256, 'learning_rate': 0.025308024795270806}. Best is trial 6 with value: 0.1943223131771771.
Fold 1 IBS: 0.18996554769557059
Fold 2 IBS: 0.26310906741655254
Fold 3 IBS: 0.1696161311725289
Fold 4 IBS: 0.16782234342771377
Fold 5 IBS: 0.24860181666708753
[I 2024-04-19 20:48:11,163] Trial 14 finished with value: 0.20782298127589066 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.768620891017602, 'n_estimators': 312, 'learning_rate': 0.026902760400745393}. Best is trial 6 with value: 0.1943223131771771.
Fold 1 IBS: 0.19321966175510347
Fold 2 IBS: 0.2138366284189496
Fold 3 IBS: 0.18384784989653682
Fold 4 IBS: 0.1987526324659148
Fold 5 IBS: 0.2123771577134171
[I 2024-04-19 20:48:16,613] Trial 15 finished with value: 0.20040678604998435 and parameters: {'subsample': 0.3798617047048457, 'dropout_rate': 0.100140121466119, 'n_estimators': 197, 'learning_rate': 0.008731674325659935}. Best is trial 6 with value: 0.1943223131771771.
Fold 1 IBS: 0.18584089385312813
Fold 2 IBS: 0.21901068736015095
Fold 3 IBS: 0.17286431701323138
Fold 4 IBS: 0.18317360324022114
Fold 5 IBS: 0.21265408612681194
[I 2024-04-19 20:48:18,368] Trial 16 finished with value: 0.19470871751870872 and parameters: {'subsample': 0.6035924494363107, 'dropout_rate': 0.332014896687618, 'n_estimators': 82, 'learning_rate': 0.037172494063176964}. Best is trial 6 with value: 0.1943223131771771.
Fold 1 IBS: 0.20010520771107096
Fold 2 IBS: 0.21956626701115503
Fold 3 IBS: 0.18899260639729892
Fold 4 IBS: 0.20619749266109724
Fold 5 IBS: 0.2121283530705589
[I 2024-04-19 20:48:20,257] Trial 17 finished with value: 0.2053979853702362 and parameters: {'subsample': 0.8094511604072581, 'dropout_rate': 0.23930666550173862, 'n_estimators': 91, 'learning_rate': 0.01245288911484009}. Best is trial 6 with value: 0.1943223131771771.
Fold 1 IBS: 0.18851662955631182
Fold 2 IBS: 0.21809576090460475
Fold 3 IBS: 0.17603224910184836
Fold 4 IBS: 0.1881004433342156
Fold 5 IBS: 0.2117438685166712
[I 2024-04-19 20:48:21,640] Trial 18 finished with value: 0.19649779028273034 and parameters: {'subsample': 0.6274675013993541, 'dropout_rate': 0.36990641238997846, 'n_estimators': 62, 'learning_rate': 0.040936167372582745}. Best is trial 6 with value: 0.1943223131771771.
Fold 1 IBS: 0.18288921886481943

Fold 2 IBS: 0.23702435623432364
Fold 3 IBS: 0.16697210861216316
Fold 4 IBS: 0.17198409581987814
Fold 5 IBS: 0.22364920336459218
[I 2024-04-19 20:48:25,099] Trial 19 finished with value: 0.19650379657915532 and parameters: {'subsample': 0.94616158758761, 'dropout_rate': 0.24313988493838726, 'n_estimators': 141, 'learning_rate': 0.036212385990032875}. Best is trial 6 with value: 0.1943223131771771.
Fold 1 IBS: 0.21058362194373925
Fold 2 IBS: 0.2208749048733855
Fold 3 IBS: 0.20093998173069624
Fold 4 IBS: 0.22031976274251558
Fold 5 IBS: 0.21636016141313785
[I 2024-04-19 20:48:25,801] Trial 20 finished with value: 0.21381568654069488 and parameters: {'subsample': 0.7937505765635346, 'dropout_rate': 0.3783894910069867, 'n_estimators': 14, 'learning_rate': 0.017331004877487094}. Best is trial 6 with value: 0.1943223131771771.
Fold 1 IBS: 0.18490088311552955
Fold 2 IBS: 0.21922853233610462
Fold 3 IBS: 0.17159476456487668
Fold 4 IBS: 0.18133781317363565
Fold 5 IBS: 0.21348389863779368
[I 2024-04-19 20:48:27,552] Trial 21 finished with value: 0.19410917836558803 and parameters: {'subsample': 0.6018701078534102, 'dropout_rate': 0.4290238232276882, 'n_estimators': 76, 'learning_rate': 0.04303711764845179}. Best is trial 21 with value: 0.19410917836558803.
Fold 1 IBS: 0.18476462992612647
Fold 2 IBS: 0.22134858843461325
Fold 3 IBS: 0.17141031638154938
Fold 4 IBS: 0.18037477977395594
Fold 5 IBS: 0.21377569665688018
[I 2024-04-19 20:48:29,246] Trial 22 finished with value: 0.19433480223462504 and parameters: {'subsample': 0.6235304409656794, 'dropout_rate': 0.4271322077248344, 'n_estimators': 79, 'learning_rate': 0.04268913313203178}. Best is trial 21 with value: 0.19410917836558803.
Fold 1 IBS: 0.18606566228292287
Fold 2 IBS: 0.24730915095494646
Fold 3 IBS: 0.1672415110895381
Fold 4 IBS: 0.16811025251054668
Fold 5 IBS: 0.23720312056041618
[I 2024-04-19 20:48:32,748] Trial 23 finished with value: 0.20118593947967406 and parameters: {'subsample': 0.7037816108237962, 'dropout_rate': 0.5959323536885025, 'n_estimators': 161, 'learning_rate': 0.04301362895414934}. Best is trial 21 with value: 0.19410917836558803.
Fold 1 IBS: 0.2041640947226462
Fold 2 IBS: 0.218362551778165
Fold 3 IBS: 0.1936885780071303
Fold 4 IBS: 0.2120864361148367
Fold 5 IBS: 0.2137832388518742
[I 2024-04-19 20:48:33,757] Trial 24 finished with value: 0.20841697989493047 and parameters: {'subsample': 0.5875544800218236, 'dropout_rate': 0.4632082486701975, 'n_estimators': 41, 'learning_rate': 0.018479875063084884}. Best is trial 21 with value: 0.19410917836558803.
Fold 1 IBS: 0.18222273112402118
Fold 2 IBS: 0.23180717748362928
Fold 3 IBS: 0.16587334301145887
Fold 4 IBS: 0.1647076511556077
Fold 5 IBS: 0.22839039582517454
[I 2024-04-19 20:48:35,844] Trial 25 finished with value: 0.1946002597199783 and parameters: {'subsample': 0.38773396678724215, 'dropout_rate': 0.4329804656440586, 'n_estimators': 100, 'learning_rate': 0.061072087123819896}. Best is trial 21 with value: 0.19410917836558803.
Fold 1 IBS: 0.19910901798465677
Fold 2 IBS: 0.27728120469997763
Fold 3 IBS: 0.17446606964119182
Fold 4 IBS: 0.17045938432156774
Fold 5 IBS: 0.26520286071081134
[I 2024-04-19 20:48:39,334] Trial 26 finished with value: 0.21730370747164107 and parameters: {'subsample': 0.7684231964849592, 'dropout_rate': 0.2968233742660247, 'n_estimators': 150, 'learning_rate': 0.08672245073861398}. Best is trial 21 with value: 0.19410917836558803.
Fold 1 IBS: 0.1944586484956436
Fold 2 IBS: 0.2581702307598589
Fold 3 IBS: 0.1719431798049758
Fold 4 IBS: 0.16778188420573198
Fold 5 IBS: 0.2597757641522608
[I 2024-04-19 20:48:44,607] Trial 27 finished with value: 0.21042594148369426 and parameters: {'subsample': 0.5575591968816295, 'dropout_rate': 0.9861686560685959, 'n_estimators': 231, 'learning_rate': 0.046259935816584434}. Best is trial 21 with value: 0.19410917836558803.
Fold 1 IBS: 0.1903384749866202
Fold 2 IBS: 0.22123395348803251
Fold 3 IBS: 0.17845819697987828
Fold 4 IBS: 0.19215967212986193
Fold 5 IBS: 0.2108136377876802
[I 2024-04-19 20:48:46,166] Trial 28 finished with value: 0.19860078707441464 and parameters: {'subsample': 0.8541226838906435, 'dropout_rate': 0.419579278974342, 'n_estimators': 69, 'learning_rate': 0.031981052358301974}. Best is trial 21 with value: 0.19410917836558803.
Fold 1 IBS: 0.18628307630803698
Fold 2 IBS: 0.2445678359757702
Fold 3 IBS: 0.16748199511637585
Fold 4 IBS: 0.16805706721025007
Fold 5 IBS: 0.2384575268342041
[I 2024-04-19 20:48:48,773] Trial 29 finished with value: 0.20096950028892743 and parameters: {'subsample': 0.6608362060553402, 'dropout_rate': 0.5660018069698168, 'n_estimators': 117, 'learning_rate': 0.060104579126943766}. Best is trial 21 with value: 0.19410917836558803.
Fold 1 IBS: 0.19809782644554194
Fold 2 IBS: 0.21683339478808214
Fold 3 IBS: 0.18614488872723395
Fold 4 IBS: 0.20337037336449598
Fold 5 IBS: 0.21285534522071314
[I 2024-04-19 20:48:49,678] Trial 30 finished with value: 0.20346036570921341 and parameters: {'subsample': 0.44759264390342135, 'dropout_rate': 0.5218585837792835, 'n_estimators': 29, 'learning_rate': 0.04935159920819105}. Best is trial 21 with value: 0.19410917836558803.
Fold 1 IBS: 0.18010961243109413
Fold 2 IBS: 0.22002209988212504
Fold 3 IBS: 0.16613415685054703
Fold 4 IBS: 0.16281853327625456
Fold 5 IBS: 0.2285779138325109
[I 2024-04-19 20:48:52,083] Trial 31 finished with value: 0.19153246325450632 and parameters: {'subsample': 0.28768044353640015, 'dropout_rate': 0.39654154305543987, 'n_estimators': 100, 'learning_rate': 0.062795268442302}. Best is trial 31 with value: 0.19153246325450632.
Fold 1 IBS: 0.15572102060161774
Fold 2 IBS: 0.22487909753297428
Fold 3 IBS: 0.17301269254920784
Fold 4 IBS: 0.15221932966628127
Fold 5 IBS: 0.24261839553569944
[I 2024-04-19 20:48:54,822] Trial 32 finished with value: 0.18969010717715612 and parameters: {'subsample': 0.1066880026654645, 'dropout_rate': 0.388650843981022, 'n_estimators': 111, 'learning_rate': 0.07898352021589775}. Best is trial 32 with value: 0.18969010717715612.
Fold 1 IBS: 0.1552692655426757
Fold 2 IBS: 0.2494807347266247
Fold 3 IBS: 0.18476967459245383
Fold 4 IBS: 0.14920367529980044
Fold 5 IBS: 0.26509735416995417
[I 2024-04-19 20:48:59,486] Trial 33 finished with value: 0.20076414086630176 and parameters: {'subsample': 0.10147457155257031, 'dropout_rate': 0.29785480561038696, 'n_estimators': 167, 'learning_rate': 0.08309671894085195}. Best is trial 32 with value: 0.18969010717715612.
Fold 1 IBS: 0.17757266438180003
Fold 2 IBS: 0.2254008605258739
Fold 3 IBS: 0.1671383757748444
Fold 4 IBS: 0.15765483432331842
Fold 5 IBS: 0.2417138220594415
[I 2024-04-19 20:49:02,360] Trial 34 finished with value: 0.19389611141305563 and parameters: {'subsample': 0.2598375341023913, 'dropout_rate': 0.4875845201250979, 'n_estimators': 119, 'learning_rate': 0.06891023050179243}. Best is trial 32 with value: 0.18969010717715612.
Fold 1 IBS: 0.17750655741203547
Fold 2 IBS: 0.23294417699359715
Fold 3 IBS: 0.16720944909861712
Fold 4 IBS: 0.15661363354133565
Fold 5 IBS: 0.24371566762454233
[I 2024-04-19 20:49:05,177] Trial 35 finished with value: 0.19559789693402554 and parameters: {'subsample': 0.24430564869860838, 'dropout_rate': 0.482790654373228, 'n_estimators': 116, 'learning_rate': 0.07323789815752085}. Best is trial 32 with value: 0.18969010717715612.
Fold 1 IBS: 0.1749556156249844
Fold 2 IBS: 0.2718656773044295
Fold 3 IBS: 0.1899561982259789
Fold 4 IBS: 0.1581044216143112
Fold 5 IBS: 0.2902913665776648
[I 2024-04-19 20:49:24,219] Trial 36 finished with value: 0.21703465586947374 and parameters: {'subsample': 0.2903002729923087, 'dropout_rate': 0.19307763825679622, 'n_estimators': 421, 'learning_rate': 0.06679178163121803}. Best is trial 32 with value: 0.18969010717715612.
Fold 1 IBS: 0.15867360434847236
Fold 2 IBS: 0.22932225376968324
Fold 3 IBS: 0.17254991656231244
Fold 4 IBS: 0.15283427860440574
Fold 5 IBS: 0.24279455128438032
[I 2024-04-19 20:49:26,808] Trial 37 finished with value: 0.1912349209138508 and parameters: {'subsample': 0.1252086357008687, 'dropout_rate': 0.30415358234856127, 'n_estimators': 108, 'learning_rate': 0.08305297978970998}. Best is trial 32 with value: 0.18969010717715612.
Fold 1 IBS: 0.15857703127898515

Fold 2 IBS: 0.23713656312281833
Fold 3 IBS: 0.17740466135498015
Fold 4 IBS: 0.1517574044253124
Fold 5 IBS: 0.24956271874009428
[I 2024-04-19 20:49:29,902] Trial 38 finished with value: 0.19488767578443805 and parameters: {'subsample': 0.10156378066408653, 'dropout_rate': 0.1902831393399341, 'n_estimators': 130, 'learning_rate': 0.0809203613085993}. Best is trial 32 with value: 0.18969010717715612.
Fold 1 IBS: 0.1561439467936712
Fold 2 IBS: 0.27717325159462314
Fold 3 IBS: 0.19875491291198305
Fold 4 IBS: 0.15520552827330267
Fold 5 IBS: 0.294775445430319
[I 2024-04-19 20:49:39,462] Trial 39 finished with value: 0.21641061700077985 and parameters: {'subsample': 0.20957727998727788, 'dropout_rate': 0.3110709513012082, 'n_estimators': 292, 'learning_rate': 0.09169157361297478}. Best is trial 32 with value: 0.18969010717715612.
Fold 1 IBS: 0.16808550271889217
Fold 2 IBS: 0.26098102192038675
Fold 3 IBS: 0.17800963723631735
Fold 4 IBS: 0.15275950564941618
Fold 5 IBS: 0.2621296835607761
[I 2024-04-19 20:49:44,571] Trial 40 finished with value: 0.2043930702171577 and parameters: {'subsample': 0.1640492189996381, 'dropout_rate': 0.27073406810212547, 'n_estimators': 186, 'learning_rate': 0.06856134358762908}. Best is trial 32 with value: 0.18969010717715612.
Fold 1 IBS: 0.18015586134870834
Fold 2 IBS: 0.21628445939453125
Fold 3 IBS: 0.1674078463706746
Fold 4 IBS: 0.16920975052349935
Fold 5 IBS: 0.22007079934087276
[I 2024-04-19 20:49:45,980] Trial 41 finished with value: 0.19062574339565724 and parameters: {'subsample': 0.30022321849728534, 'dropout_rate': 0.3944154176211154, 'n_estimators': 61, 'learning_rate': 0.07748533567493679}. Best is trial 32 with value: 0.18969010717715612.
Fold 1 IBS: 0.18274060318899477
Fold 2 IBS: 0.21389629588979814
Fold 3 IBS: 0.17037218696220213
Fold 4 IBS: 0.1757036411926152
Fold 5 IBS: 0.21639549420581114
[I 2024-04-19 20:49:47,169] Trial 42 finished with value: 0.19182164428788429 and parameters: {'subsample': 0.2987546252230515, 'dropout_rate': 0.4908551245588177, 'n_estimators': 48, 'learning_rate': 0.07856398138275451}. Best is trial 32 with value: 0.18969010717715612.
Fold 1 IBS: 0.19188937703552297
Fold 2 IBS: 0.21383373568790653
Fold 3 IBS: 0.18335082620238055
Fold 4 IBS: 0.19589676406264575
Fold 5 IBS: 0.21265797173546291
[I 2024-04-19 20:49:48,007] Trial 43 finished with value: 0.19952573494478373 and parameters: {'subsample': 0.32827243840837517, 'dropout_rate': 0.3836769535493768, 'n_estimators': 24, 'learning_rate': 0.078468758976547}. Best is trial 32 with value: 0.18969010717715612.
Fold 1 IBS: 0.17096786699399136
Fold 2 IBS: 0.21688453290373846
Fold 3 IBS: 0.16869686554303537
Fold 4 IBS: 0.1705447534120572
Fold 5 IBS: 0.22064244079238
[I 2024-04-19 20:49:49,283] Trial 44 finished with value: 0.18954729192904046 and parameters: {'subsample': 0.16346851183132338, 'dropout_rate': 0.3546946718507976, 'n_estimators': 54, 'learning_rate': 0.08820456529149995}. Best is trial 44 with value: 0.18954729192904046.
Fold 1 IBS: 0.1664640074948659
Fold 2 IBS: 0.24109432679963266
Fold 3 IBS: 0.17049491695033356
Fold 4 IBS: 0.15343484740995175
Fold 5 IBS: 0.24581767657259815
[I 2024-04-19 20:49:51,528] Trial 45 finished with value: 0.1954611550454764 and parameters: {'subsample': 0.1696110752729381, 'dropout_rate': 0.3520021815509761, 'n_estimators': 97, 'learning_rate': 0.09911257552040509}. Best is trial 44 with value: 0.18954729192904046.
Fold 1 IBS: 0.1517961491470844
Fold 2 IBS: 0.2715130145734022
Fold 3 IBS: 0.2027314760665
Fold 4 IBS: 0.15058490216025472
Fold 5 IBS: 0.28504792886164954
[I 2024-04-19 20:49:58,352] Trial 46 finished with value: 0.21233469416177816 and parameters: {'subsample': 0.13151895785356355, 'dropout_rate': 0.19036485632322575, 'n_estimators': 226, 'learning_rate': 0.08888373882718631}. Best is trial 44 with value: 0.18954729192904046.
Fold 1 IBS: 0.17667154489356374
Fold 2 IBS: 0.21478410674831006
Fold 3 IBS: 0.17038871409194956
Fold 4 IBS: 0.17477396149550878
Fold 5 IBS: 0.21793833312725006
[I 2024-04-19 20:49:59,603] Trial 47 finished with value: 0.19091133207131644 and parameters: {'subsample': 0.2137675159022689, 'dropout_rate': 0.2694806865608844, 'n_estimators': 51, 'learning_rate': 0.0754642578657436}. Best is trial 44 with value: 0.18954729192904046.
Fold 1 IBS: 0.18114705751993532
Fold 2 IBS: 0.21228128254743872
Fold 3 IBS: 0.16957370387752638
Fold 4 IBS: 0.16913784084308722
Fold 5 IBS: 0.2191907790361041
[I 2024-04-19 20:50:00,892] Trial 48 finished with value: 0.19026613276481835 and parameters: {'subsample': 0.20661929343347396, 'dropout_rate': 0.14178876486778996, 'n_estimators': 55, 'learning_rate': 0.08511646998522475}. Best is trial 44 with value: 0.18954729192904046.
Fold 1 IBS: 0.21258428093968987
Fold 2 IBS: 0.22113727243807998
Fold 3 IBS: 0.2022608872283768
Fold 4 IBS: 0.22117551675302077
Fold 5 IBS: 0.21691772990244465
[I 2024-04-19 20:50:01,502] Trial 49 finished with value: 0.21481513745232245 and parameters: {'subsample': 0.20498987552162307, 'dropout_rate': 0.12711876811331263, 'n_estimators': 2, 'learning_rate': 0.0944416930670073}. Best is trial 44 with value: 0.18954729192904046.
Fold 1 IBS: 0.1774687665961881
Fold 2 IBS: 0.20718879492740863
Fold 3 IBS: 0.16976601924144055
Fold 4 IBS: 0.16971179362674763
Fold 5 IBS: 0.2181965734536657
[I 2024-04-19 20:50:02,862] Trial 50 finished with value: 0.18846638956909012 and parameters: {'subsample': 0.22472246171781585, 'dropout_rate': 0.15621212797233042, 'n_estimators': 51, 'learning_rate': 0.08625696931513883}. Best is trial 50 with value: 0.18846638956909012.
Fold 1 IBS: 0.17649775210999014
Fold 2 IBS: 0.21208708208235233
Fold 3 IBS: 0.16832644793195198
Fold 4 IBS: 0.16605616062711012
Fold 5 IBS: 0.22066954205499664
[I 2024-04-19 20:50:04,267] Trial 51 finished with value: 0.18872739696128024 and parameters: {'subsample': 0.20935443476920698, 'dropout_rate': 0.1640048569577055, 'n_estimators': 57, 'learning_rate': 0.08684177820080327}. Best is trial 50 with value: 0.18846638956909012.
Fold 1 IBS: 0.1895182652273222
Fold 2 IBS: 0.2128293157900086
Fold 3 IBS: 0.1831958536580358
Fold 4 IBS: 0.1911130368690319
Fold 5 IBS: 0.2136987890491093
[I 2024-04-19 20:50:05,138] Trial 52 finished with value: 0.19807105211870157 and parameters: {'subsample': 0.2350514728834408, 'dropout_rate': 0.15714932490159228, 'n_estimators': 25, 'learning_rate': 0.0869763188360061}. Best is trial 50 with value: 0.18846638956909012.
Fold 1 IBS: 0.17843533392704589
Fold 2 IBS: 0.2121384096165674
Fold 3 IBS: 0.16831601353602985
Fold 4 IBS: 0.17390767491418266
Fold 5 IBS: 0.21983243734873273
[I 2024-04-19 20:50:06,488] Trial 53 finished with value: 0.19052597386851172 and parameters: {'subsample': 0.3481442884627235, 'dropout_rate': 0.1029086996522931, 'n_estimators': 53, 'learning_rate': 0.09203385531929426}. Best is trial 50 with value: 0.18846638956909012.
Fold 1 IBS: 0.17410715429132662
Fold 2 IBS: 0.21192744969446828
Fold 3 IBS: 0.17273707802098714
Fold 4 IBS: 0.18012958665850648
Fold 5 IBS: 0.21899546007274423
[I 2024-04-19 20:50:07,605] Trial 54 finished with value: 0.19157934574760654 and parameters: {'subsample': 0.1594049099839162, 'dropout_rate': 0.10199866282299863, 'n_estimators': 41, 'learning_rate': 0.0920235860435986}. Best is trial 50 with value: 0.18846638956909012.
Fold 1 IBS: 0.21237912378993593
Fold 2 IBS: 0.22127036317672827
Fold 3 IBS: 0.20274135251224107
Fold 4 IBS: 0.22289091908290665
Fold 5 IBS: 0.21832650153791408
[I 2024-04-19 20:50:08,196] Trial 55 finished with value: 0.21552165201994522 and parameters: {'subsample': 0.33997355881965496, 'dropout_rate': 0.15105403923216587, 'n_estimators': 1, 'learning_rate': 0.09897459844160936}. Best is trial 50 with value: 0.18846638956909012.
Fold 1 IBS: 0.18240531518991723
Fold 2 IBS: 0.21988580602254618
Fold 3 IBS: 0.16650027745447143
Fold 4 IBS: 0.167977682227068
Fold 5 IBS: 0.22454015397577817
[I 2024-04-19 20:50:09,937] Trial 56 finished with value: 0.1922618469739562 and parameters: {'subsample': 0.42456755417504644, 'dropout_rate': 0.22331758866445284, 'n_estimators': 67, 'learning_rate': 0.08517018516431102}. Best is trial 50 with value: 0.18846638956909012.
Fold 1 IBS: 0.18156532286843066
Fold 2 IBS: 0.20721785466158654

Fold 3 IBS: 0.17387795485826352
Fold 4 IBS: 0.1782224770917523
Fold 5 IBS: 0.21493794996814689
[I 2024-04-19 20:50:11,046] Trial 57 finished with value: 0.19116431188963598 and parameters: {'subsample': 0.18843039521650953, 'dropout_rate': 0.14776012840756408, 'n_estimators': 37, 'learning_rate': 0.09198058884032197}. Best is trial 50 with value: 0.18846638956909012.
Fold 1 IBS: 0.1440428493085998
Fold 2 IBS: 0.28426158143656177
Fold 3 IBS: 0.20892275183393225
Fold 4 IBS: 0.15337755502728193
Fold 5 IBS: 0.3041208500039513
[I 2024-04-19 20:50:26,035] Trial 58 finished with value: 0.2189451175220654 and parameters: {'subsample': 0.12822221310185083, 'dropout_rate': 0.2189285380511568, 'n_estimators': 376, 'learning_rate': 0.09590977913604533}. Best is trial 50 with value: 0.18846638956909012.
Fold 1 IBS: 0.17451916697027026
Fold 2 IBS: 0.21534847665640164
Fold 3 IBS: 0.16679919906432278
Fold 4 IBS: 0.1591834938000388
Fold 5 IBS: 0.23021825829121667
[I 2024-04-19 20:50:28,149] Trial 59 finished with value: 0.18921371895645003 and parameters: {'subsample': 0.2243811475381035, 'dropout_rate': 0.18318350350649054, 'n_estimators': 87, 'learning_rate': 0.08171179734854472}. Best is trial 50 with value: 0.18846638956909012.
Fold 1 IBS: 0.1781336114892237
Fold 2 IBS: 0.2389188779897808
Fold 3 IBS: 0.1704809994445818
Fold 4 IBS: 0.15651832976720595
Fold 5 IBS: 0.2473084707651024
[I 2024-04-19 20:50:31,569] Trial 60 finished with value: 0.1982720578911789 and parameters: {'subsample': 0.22907930505965052, 'dropout_rate': 0.17979832028326875, 'n_estimators': 140, 'learning_rate': 0.07200825617838875}. Best is trial 50 with value: 0.18846638956909012.
Fold 1 IBS: 0.1662054631463899
Fold 2 IBS: 0.21217984440652868
Fold 3 IBS: 0.16612436812880285
Fold 4 IBS: 0.16201787549557836
Fold 5 IBS: 0.2324554936135338
[I 2024-04-19 20:50:33,337] Trial 61 finished with value: 0.1877966089581667 and parameters: {'subsample': 0.1471047604702049, 'dropout_rate': 0.12127120615536148, 'n_estimators': 76, 'learning_rate': 0.08961724346472337}. Best is trial 61 with value: 0.1877966089581667.
Fold 1 IBS: 0.1698523736718801
Fold 2 IBS: 0.2251346666933035
Fold 3 IBS: 0.16832003161507905
Fold 4 IBS: 0.15689522599593944
Fold 5 IBS: 0.23783705813855513
[I 2024-04-19 20:50:35,444] Trial 62 finished with value: 0.19160787122295145 and parameters: {'subsample': 0.14772403022947522, 'dropout_rate': 0.21942006452918061, 'n_estimators': 88, 'learning_rate': 0.08863877942092839}. Best is trial 61 with value: 0.1877966089581667.
Fold 1 IBS: 0.176103330028869
Fold 2 IBS: 0.21932987448822935
Fold 3 IBS: 0.16682952298857767
Fold 4 IBS: 0.16060306530215276
Fold 5 IBS: 0.22751188754096155
[I 2024-04-19 20:50:37,305] Trial 63 finished with value: 0.19007553606975805 and parameters: {'subsample': 0.19175914914583594, 'dropout_rate': 0.13007100493347473, 'n_estimators': 79, 'learning_rate': 0.08091596459369155}. Best is trial 61 with value: 0.1877966089581667.
Fold 1 IBS: 0.17396785196287354
Fold 2 IBS: 0.21710022040864746
Fold 3 IBS: 0.16666993438857236
Fold 4 IBS: 0.16042977044533668
Fold 5 IBS: 0.22838891779790255
[I 2024-04-19 20:50:39,289] Trial 64 finished with value: 0.18931133900066652 and parameters: {'subsample': 0.18513720759159225, 'dropout_rate': 0.16829691747505554, 'n_estimators': 81, 'learning_rate': 0.08176796291518887}. Best is trial 61 with value: 0.1877966089581667.
Fold 1 IBS: 0.198127146283598
Fold 2 IBS: 0.21319216426675125
Fold 3 IBS: 0.190868009907054
Fold 4 IBS: 0.20462469990888338
Fold 5 IBS: 0.21322563759802013
[I 2024-04-19 20:50:40,021] Trial 65 finished with value: 0.2040075315928614 and parameters: {'subsample': 0.25970949169604085, 'dropout_rate': 0.2498767573757012, 'n_estimators': 14, 'learning_rate': 0.08160140782879213}. Best is trial 61 with value: 0.1877966089581667.
Fold 1 IBS: 0.16465092730962427
Fold 2 IBS: 0.22937915050727528
Fold 3 IBS: 0.1684213477812377
Fold 4 IBS: 0.15579520990468107
Fold 5 IBS: 0.23290208063783222
[I 2024-04-19 20:50:41,948] Trial 66 finished with value: 0.19022974322813013 and parameters: {'subsample': 0.14303489443385625, 'dropout_rate': 0.17525266411324758, 'n_estimators': 80, 'learning_rate': 0.08891063679771807}. Best is trial 61 with value: 0.1877966089581667.
Fold 1 IBS: 0.16892555183567967
Fold 2 IBS: 0.2308031676699095
Fold 3 IBS: 0.17228652192108024
Fold 4 IBS: 0.15304003040552336
Fold 5 IBS: 0.2501137679561498
[I 2024-04-19 20:50:45,265] Trial 67 finished with value: 0.19503380795766853 and parameters: {'subsample': 0.17938135272872893, 'dropout_rate': 0.21454950772149037, 'n_estimators': 131, 'learning_rate': 0.07724515210484845}. Best is trial 61 with value: 0.1877966089581667.
Fold 1 IBS: 0.1675127176144366
Fold 2 IBS: 0.20952467017260845
Fold 3 IBS: 0.17116260932744334
Fold 4 IBS: 0.1685899836481178
Fold 5 IBS: 0.22313843702047945
[I 2024-04-19 20:50:47,712] Trial 68 finished with value: 0.18798568355661713 and parameters: {'subsample': 0.10599386046574193, 'dropout_rate': 0.3325568193202135, 'n_estimators': 90, 'learning_rate': 0.05618929029743286}. Best is trial 61 with value: 0.1877966089581667.
Fold 1 IBS: 0.20030482493477378
Fold 2 IBS: 0.2165273084088395
Fold 3 IBS: 0.19133969869352552
Fold 4 IBS: 0.20816952745697548
Fold 5 IBS: 0.21382140306170772
[I 2024-04-19 20:50:48,543] Trial 69 finished with value: 0.20603255251116437 and parameters: {'subsample': 0.2702239672209966, 'dropout_rate': 0.6742877948812134, 'n_estimators': 19, 'learning_rate': 0.05452181969732228}. Best is trial 61 with value: 0.1877966089581667.
Fold 1 IBS: 0.1759139311729982
Fold 2 IBS: 0.2200956984260826
Fold 3 IBS: 0.16545588547764598
Fold 4 IBS: 0.16111193509204783
Fold 5 IBS: 0.2278621241563732
[I 2024-04-19 20:50:50,637] Trial 70 finished with value: 0.19008791486502957 and parameters: {'subsample': 0.24079462753639905, 'dropout_rate': 0.26601085692359333, 'n_estimators': 87, 'learning_rate': 0.07126534715285147}. Best is trial 61 with value: 0.1877966089581667.
Fold 1 IBS: 0.15604260061546105
Fold 2 IBS: 0.22347272779646865
Fold 3 IBS: 0.1732185795270601
Fold 4 IBS: 0.1523511407164035
Fold 5 IBS: 0.24250717644624042
[I 2024-04-19 20:50:53,268] Trial 71 finished with value: 0.18951844502032672 and parameters: {'subsample': 0.10706800069060031, 'dropout_rate': 0.3264940831154918, 'n_estimators': 104, 'learning_rate': 0.08463588970645965}. Best is trial 61 with value: 0.1877966089581667.
Fold 1 IBS: 0.16260312195490847
Fold 2 IBS: 0.21994801422719953
Fold 3 IBS: 0.16665156416668908
Fold 4 IBS: 0.16412676795171277
Fold 5 IBS: 0.22353092697981328
[I 2024-04-19 20:50:55,098] Trial 72 finished with value: 0.18737207905606462 and parameters: {'subsample': 0.15148181951628686, 'dropout_rate': 0.33798461458879825, 'n_estimators': 67, 'learning_rate': 0.0856390028391666}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.15345048743889098
Fold 2 IBS: 0.26330504849543546
Fold 3 IBS: 0.1919248217211949
Fold 4 IBS: 0.1511017594136047
Fold 5 IBS: 0.2674377665720808
[I 2024-04-19 20:50:59,450] Trial 73 finished with value: 0.20544397672824136 and parameters: {'subsample': 0.12443812587999242, 'dropout_rate': 0.17151193643856824, 'n_estimators': 158, 'learning_rate': 0.09426547314708753}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.1606197828284215
Fold 2 IBS: 0.23145775038394745
Fold 3 IBS: 0.1671770811853298
Fold 4 IBS: 0.15446032364109463
Fold 5 IBS: 0.23723654797742197
[I 2024-04-19 20:51:01,870] Trial 74 finished with value: 0.19019029720324307 and parameters: {'subsample': 0.14512295293787505, 'dropout_rate': 0.32898219709005594, 'n_estimators': 97, 'learning_rate': 0.08453953251416191}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.1659988900038564
Fold 2 IBS: 0.21274636756634802
Fold 3 IBS: 0.17293832337574505
Fold 4 IBS: 0.16647295576875695
Fold 5 IBS: 0.2271402838864893
[I 2024-04-19 20:51:03,863] Trial 75 finished with value: 0.18905936412023916 and parameters: {'subsample': 0.10157535352629013, 'dropout_rate': 0.12066282948421611, 'n_estimators': 73, 'learning_rate': 0.0645436786648782}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.17367616435517544
Fold 2 IBS: 0.2078598489871464

Fold 3 IBS: 0.1719591027088269
Fold 4 IBS: 0.17385426627525688
Fold 5 IBS: 0.21855520290466832
[I 2024-04-19 20:51:05,602] Trial 76 finished with value: 0.1891809170462148 and parameters: {'subsample': 0.18365616131833243, 'dropout_rate': 0.1155429307750635, 'n_estimators': 72, 'learning_rate': 0.05783626801894725}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.17898577250628434
Fold 2 IBS: 0.21102095266397086
Fold 3 IBS: 0.17067626518890075
Fold 4 IBS: 0.17375281178548999
Fold 5 IBS: 0.2195689099935357
[I 2024-04-19 20:51:07,270] Trial 77 finished with value: 0.19080094242763632 and parameters: {'subsample': 0.22727717915712076, 'dropout_rate': 0.12580118134903598, 'n_estimators': 64, 'learning_rate': 0.06405563389298143}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.19199714074267124
Fold 2 IBS: 0.20991480713279673
Fold 3 IBS: 0.1840034657144547
Fold 4 IBS: 0.19623025088317492
Fold 5 IBS: 0.2126890719702477
[I 2024-04-19 20:51:08,304] Trial 78 finished with value: 0.19896694728866907 and parameters: {'subsample': 0.2683056852330482, 'dropout_rate': 0.12047994460179345, 'n_estimators': 36, 'learning_rate': 0.05150786812026068}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.1776141237788122
Fold 2 IBS: 0.22410395211987294
Fold 3 IBS: 0.1662206059704564
Fold 4 IBS: 0.16120075338902687
Fold 5 IBS: 0.23242897269911802
[I 2024-04-19 20:51:11,468] Trial 79 finished with value: 0.1923136815914573 and parameters: {'subsample': 0.3129985685757968, 'dropout_rate': 0.24493990209120758, 'n_estimators': 124, 'learning_rate': 0.05755022868467649}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.177756638968663
Fold 2 IBS: 0.2124589569806853
Fold 3 IBS: 0.17115288134507317
Fold 4 IBS: 0.1745676420679377
Fold 5 IBS: 0.21832006852740177
[I 2024-04-19 20:51:13,202] Trial 80 finished with value: 0.19085123757795217 and parameters: {'subsample': 0.15710506681411263, 'dropout_rate': 0.2041609905908715, 'n_estimators': 67, 'learning_rate': 0.059148941947772905}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.1708025340918918
Fold 2 IBS: 0.20856533268992664
Fold 3 IBS: 0.170279979439806
Fold 4 IBS: 0.16940269909769456
Fold 5 IBS: 0.22049399833679673
[I 2024-04-19 20:51:15,135] Trial 81 finished with value: 0.18790890873122315 and parameters: {'subsample': 0.18281175845257586, 'dropout_rate': 0.1012017949047196, 'n_estimators': 74, 'learning_rate': 0.06643513003436904}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.16631029007543371
Fold 2 IBS: 0.2144400866948897
Fold 3 IBS: 0.1712160282036271
Fold 4 IBS: 0.16659531726326116
Fold 5 IBS: 0.23040138035415272
[I 2024-04-19 20:51:17,521] Trial 82 finished with value: 0.1897926205182729 and parameters: {'subsample': 0.12207805270565139, 'dropout_rate': 0.10209768151557944, 'n_estimators': 90, 'learning_rate': 0.06468152770419036}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.17956658945107773
Fold 2 IBS: 0.2121960431953454
Fold 3 IBS: 0.16983572847179354
Fold 4 IBS: 0.17175256638322067
Fold 5 IBS: 0.21700984638487653
[I 2024-04-19 20:51:19,257] Trial 83 finished with value: 0.19007215477726278 and parameters: {'subsample': 0.19366735371220553, 'dropout_rate': 0.15181210014865276, 'n_estimators': 72, 'learning_rate': 0.05806096193257207}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.166359371961043
Fold 2 IBS: 0.2709782346033885
Fold 3 IBS: 0.18877212654252803
Fold 4 IBS: 0.1559336705703255
Fold 5 IBS: 0.28692631461010215
[I 2024-04-19 20:51:43,638] Trial 84 finished with value: 0.21379394365747745 and parameters: {'subsample': 0.2206408953935794, 'dropout_rate': 0.12447881723364125, 'n_estimators': 494, 'learning_rate': 0.04681041394034122}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.1600402000797763
Fold 2 IBS: 0.24764739616495174
Fold 3 IBS: 0.1755245117166778
Fold 4 IBS: 0.1516152588861126
Fold 5 IBS: 0.25188181127259907
[I 2024-04-19 20:51:47,126] Trial 85 finished with value: 0.19734183562402352 and parameters: {'subsample': 0.14387868032756806, 'dropout_rate': 0.19472140162379584, 'n_estimators': 143, 'learning_rate': 0.07478092235424887}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.18881073154370712
Fold 2 IBS: 0.21335175954848315
Fold 3 IBS: 0.1814086635026929
Fold 4 IBS: 0.19544673969609835
Fold 5 IBS: 0.21379456078645268
[I 2024-04-19 20:51:48,247] Trial 86 finished with value: 0.19856249101548684 and parameters: {'subsample': 0.16839945613858462, 'dropout_rate': 0.2820652576742986, 'n_estimators': 41, 'learning_rate': 0.051424878532569565}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.16545212452023114
Fold 2 IBS: 0.21474060902106143
Fold 3 IBS: 0.17001059322245546
Fold 4 IBS: 0.1632133585894077
Fold 5 IBS: 0.23136625065241098
[I 2024-04-19 20:51:50,921] Trial 87 finished with value: 0.18895658720111336 and parameters: {'subsample': 0.10089782668730003, 'dropout_rate': 0.1641658794801585, 'n_estimators': 110, 'learning_rate': 0.055839877149582766}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.16403399038616823
Fold 2 IBS: 0.21606009218944566
Fold 3 IBS: 0.1699213257138068
Fold 4 IBS: 0.16137242709678198
Fold 5 IBS: 0.23334960962234483
[I 2024-04-19 20:51:53,690] Trial 88 finished with value: 0.1889474890017095 and parameters: {'subsample': 0.10686928087310275, 'dropout_rate': 0.15994010072296855, 'n_estimators': 116, 'learning_rate': 0.056719762016297706}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.16194557252223743
Fold 2 IBS: 0.2400345851788657
Fold 3 IBS: 0.183888996572315
Fold 4 IBS: 0.151154660714223
Fold 5 IBS: 0.25669114686371075
[I 2024-04-19 20:51:57,627] Trial 89 finished with value: 0.19874299237027038 and parameters: {'subsample': 0.10061548797106971, 'dropout_rate': 0.8036886089440476, 'n_estimators': 174, 'learning_rate': 0.06646355584018333}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.16397830655145665
Fold 2 IBS: 0.22024440056377095
Fold 3 IBS: 0.17254798483884226
Fold 4 IBS: 0.1631382782467483
Fold 5 IBS: 0.23193172142205445
[I 2024-04-19 20:52:00,260] Trial 90 finished with value: 0.1903681383245745 and parameters: {'subsample': 0.11991820363328082, 'dropout_rate': 0.1570381515865438, 'n_estimators': 109, 'learning_rate': 0.05475769176859546}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.17552084601140616
Fold 2 IBS: 0.21320364860260557
Fold 3 IBS: 0.17121132438839562
Fold 4 IBS: 0.1749050885947761
Fold 5 IBS: 0.21770453366779963
[I 2024-04-19 20:52:01,796] Trial 91 finished with value: 0.1905090882529966 and parameters: {'subsample': 0.14392346893566635, 'dropout_rate': 0.13424195710822603, 'n_estimators': 60, 'learning_rate': 0.06217188889119802}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.1945949996158027
Fold 2 IBS: 0.21449066002184106
Fold 3 IBS: 0.18543756393379815
Fold 4 IBS: 0.20222713019273608
Fold 5 IBS: 0.21331898000325855
[I 2024-04-19 20:52:02,745] Trial 92 finished with value: 0.2020138667534873 and parameters: {'subsample': 0.1751306862349925, 'dropout_rate': 0.11284544145521876, 'n_estimators': 28, 'learning_rate': 0.055873505115263546}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.1669732384931042
Fold 2 IBS: 0.20952758484068784
Fold 3 IBS: 0.16977938923651129
Fold 4 IBS: 0.16604972511315036
Fold 5 IBS: 0.22458107308741776
[I 2024-04-19 20:52:05,200] Trial 93 finished with value: 0.1873822021541743 and parameters: {'subsample': 0.11691218466747766, 'dropout_rate': 0.23352417904700523, 'n_estimators': 100, 'learning_rate': 0.05216124197693256}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.1821583644972441
Fold 2 IBS: 0.21775880864733177
Fold 3 IBS: 0.1676516877589749
Fold 4 IBS: 0.17360358700403428
Fold 5 IBS: 0.2182723264339033
[I 2024-04-19 20:52:07,940] Trial 94 finished with value: 0.19188895486829766 and parameters: {'subsample': 0.5143282301365409, 'dropout_rate': 0.24062506493726504, 'n_estimators': 119, 'learning_rate': 0.03784083828401163}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.1690142088283897
Fold 2 IBS: 0.213061409666627

Fold 3 IBS: 0.17173452642164364
Fold 4 IBS: 0.16762247465250765
Fold 5 IBS: 0.22091059694529425
[I 2024-04-19 20:52:10,557] Trial 95 finished with value: 0.18846864330289245 and parameters: {'subsample': 0.10065734393653682, 'dropout_rate': 0.2062111700337662, 'n_estimators': 101, 'learning_rate': 0.04585397731547914}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.16562778981576426
Fold 2 IBS: 0.223748229420193
Fold 3 IBS: 0.1675280972549571
Fold 4 IBS: 0.16144268040337637
Fold 5 IBS: 0.23038430815699265
[I 2024-04-19 20:52:13,999] Trial 96 finished with value: 0.18974622101025668 and parameters: {'subsample': 0.13033143555307963, 'dropout_rate': 0.20726482372099408, 'n_estimators': 135, 'learning_rate': 0.05075481404832163}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.17077980003606147
Fold 2 IBS: 0.21379083665016999
Fold 3 IBS: 0.17002819541040814
Fold 4 IBS: 0.16800202659952168
Fold 5 IBS: 0.22092403331869154
[I 2024-04-19 20:52:16,366] Trial 97 finished with value: 0.18870497840297057 and parameters: {'subsample': 0.12133381213628103, 'dropout_rate': 0.22431909931509358, 'n_estimators': 101, 'learning_rate': 0.04671225079174805}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.17862513760570542
Fold 2 IBS: 0.2114260974274058
Fold 3 IBS: 0.17004396055088428
Fold 4 IBS: 0.1736839388403377
Fold 5 IBS: 0.2172760242952533
[I 2024-04-19 20:52:18,698] Trial 98 finished with value: 0.1902110317439173 and parameters: {'subsample': 0.2018069879822831, 'dropout_rate': 0.23214300194319348, 'n_estimators': 100, 'learning_rate': 0.039190225983096655}. Best is trial 72 with value: 0.18737207905606462.
Fold 1 IBS: 0.16711656806565794
Fold 2 IBS: 0.25608187589413206
Fold 3 IBS: 0.17951674459457387
Fold 4 IBS: 0.15438119939450232
Fold 5 IBS: 0.2640505557352486
[I 2024-04-19 20:52:27,712] Trial 99 finished with value: 0.20422938873682295 and parameters: {'subsample': 0.1578842324289164, 'dropout_rate': 0.28456384143301616, 'n_estimators': 278, 'learning_rate': 0.046839507262657405}. Best is trial 72 with value: 0.18737207905606462.


* Best trial for IBS:
 FrozenTrial(number=72, state=TrialState.COMPLETE, values=[0.18737207905606462], datetime_start=datetime.datetime(2024, 4, 19, 20, 50, 53, 278573), datetime_complete=datetime.datetime(2024, 4, 19, 20, 50, 55, 98417), params={'subsample': 0.15148181951628686, 'dropout_rate': 0.33798461458879825, 'n_estimators': 67, 'learning_rate': 0.0856390028391666}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=72, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.15148181951628686, 'dropout_rate': 0.33798461458879825, 'n_estimators': 67, 'learning_rate': 0.0856390028391666}


* Best Score for IBS:
 0.18737207905606462

In [75]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [76]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.737
train_ibs:  0.187

#### Test

In [77]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [78]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.892001983552212,
                                              learning_rate=0.02617536005560058,
                                              n_estimators=237,
                                              random_state=123,
                                              subsample=0.20471187836593263)

C-index score: 0.538

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.33798461458879825,
                                              learning_rate=0.0856390028391666,
                                              n_estimators=67, random_state=123,
                                              subsample=0.15148181951628686)

IBS: 0.215

In [79]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [80]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.871   1.0
ExtraSurvivalTrees               0.816   2.0
GradientBoosting                 0.791   3.0
CoxElastic                       0.775   4.0
CoxPH                            0.774   5.0
CoxLasso                         0.773   6.0
ComponentwiseGradientBoosting    0.737   7.0
CoxRidge                         0.718   8.0

In [81]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.175   1.0
CoxLasso                       0.181   3.0
CoxElastic                     0.181   3.0
ExtraSurvivalTrees             0.181   3.0
CoxPH                          0.182   5.0
ComponentwiseGradientBoosting  0.187   6.0
GradientBoosting               0.215   7.0
CoxRidge                       0.217   8.0

In [82]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ExtraSurvivalTrees               0.656   1.0
GradientBoosting                 0.630   2.0
CoxRidge                         0.624   3.0
Randomsurvivalforest             0.618   4.0
CoxLasso                         0.590   5.0
CoxElastic                       0.588   6.0
CoxPH                            0.587   7.0
ComponentwiseGradientBoosting    0.538   8.0

In [83]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.214   1.0
ComponentwiseGradientBoosting  0.215   2.0
GradientBoosting               0.220   3.0
CoxRidge                       0.221   4.0
Randomsurvivalforest           0.223   5.0
CoxLasso                       0.272   6.5
CoxElastic                     0.272   6.5
CoxPH                          0.278   8.0

In [84]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/os/minmax/rent/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_os_minmax_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [85]:
from datetime import date

current_date = date.today()
print(current_date)

2024-04-19