In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
 
from sklearn.preprocessing import MinMaxScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D3 
clinical_train.isnull().sum().sum()

0

### COX assumption in Train data

In [6]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic    p  -log2(p)
LBP_003_CT                                                       0.00 0.97      0.05
LBP_003_PET                                                      0.00 0.97      0.05
LBP_012_CT                                                       0.00 0.96      0.06
LBP_012_PET                                                      0.01 0.94      0.09
LBP_021_CT                                                       0.00 0.98      0.04
LBP_021_PET                                                      0.01 0.94      0.10
LBP_030_CT                                                       0.00 0.99      0.02
LBP_030_PET                                                      0.00 0.98      0.02
LBP_102_CT                                                       0.00 0.96      0.05
LBP_102_PET                                                      0.01 0.92      0.12
LBP_111_CT                                                       0.00 0.95      0.07
LBP_111_PET                                                      0.00 1.00      0.00
LBP_120_CT                                                       0.00 0.98      0.03
LBP_120_PET                                                      0.00 0.99      0.02
LBP_201_CT                                                       0.00 0.97      0.04
LBP_201_PET                                                      0.00 0.97      0.04
LBP_210_CT                                                       0.00 1.00      0.01
LBP_210_PET                                                      0.00 1.00      0.00
LBP_300_CT                                                       0.00 0.97      0.04
LBP_300_PET                                                      0.01 0.94      0.09
MTV                                                              0.00 0.98      0.04
SUVpeak                                                          0.00 0.98      0.02
TLG                                                              0.00 0.99      0.02
age                                                              0.00 0.97      0.05
cavum_oris                                                       0.00 0.99      0.02
charlson                                                         0.02 0.90      0.15
female                                                           0.00 0.96      0.06
first_order_10Percentile_CT                                      0.00 0.98      0.03
first_order_10Percentile_PET                                     0.00 1.00      0.01
first_order_90Percentile_CT                                      0.00 0.98      0.04
first_order_90Percentile_PET                                     0.00 0.99      0.01
first_order_Energy_CT                                            0.00 1.00      0.01
first_order_Energy_PET                                           0.00 0.99      0.02
first_order_Entropy_CT_b20                                       0.00 1.00      0.00
first_order_Entropy_CT_c16                                       0.00 1.00      0.00
first_order_Entropy_PET_b2                                       0.00 1.00      0.00
first_order_Entropy_PET_c04                                      0.00 1.00      0.00
first_order_InterquartileRange_CT                                0.00 0.97      0.04
first_order_InterquartileRange_PET                               0.00 0.99      0.01
first_order_Kurtosis_CT                                          0.00 0.95      0.08
first_order_Kurtosis_PET                                         0.00 0.97      0.04
first_order_Maximum_CT                                           0.00 0.99      0.02
first_order_Maximum_PET                                          0.00 0.99      0.02
first_order_MeanAbsoluteDeviation_CT                             0.00 0.99      0.02
first_order_MeanAbsoluteDeviation_PET                            0.00 0.99      0.02
first_order_Mean_CT                                              0.00 0.99      0.02
first_order_Mean_PET                                             0.00 1.00      0.00
first_order_Median_CT                                            0.00 0.98      0.03
first_order_Median_PET                                           0.00 0.99      0.01
first_order_Minimum_CT                                           0.00 0.99      0.01
first_order_Minimum_PET                                          0.01 0.94      0.09
first_order_Range_CT                                             0.00 0.99      0.01
first_order_Range_PET                                            0.00 0.99      0.02
first_order_RobustMeanAbsoluteDeviation_CT                       0.00 0.98      0.04
first_order_RobustMeanAbsoluteDeviation_PET                      0.00 1.00      0.00
first_order_RootMeanSquared_CT                                   0.00 0.98      0.03
first_order_RootMeanSquared_PET                                  0.00 0.99      0.01
first_order_Skewness_CT                                          0.00 0.98      0.03
first_order_Skewness_PET                                         0.00 1.00      0.00
first_order_TotalEnergy_CT                                       0.00 1.00      0.01
first_order_TotalEnergy_PET                                      0.00 0.99      0.02
first_order_Uniformity_CT_b20                                    0.00 0.97      0.05
first_order_Uniformity_CT_c16                                    0.00 0.99      0.01
first_order_Uniformity_PET_b2                                    0.00 1.00      0.00
first_order_Uniformity_PET_c04                                   0.00 1.00      0.00
first_order_Variance_CT                                          0.00 1.00      0.01
first_order_Variance_PET                                         0.00 1.00      0.01
glcm_Autocorrelation_d_1_CT_b20                                  0.00 0.98      0.03
glcm_Autocorrelation_d_1_CT_c16                                  0.00 0.99      0.01
glcm_Autocorrelation_d_1_PET_b2                                  0.00 0.99      0.01
glcm_Autocorrelation_d_1_PET_c04                                 0.00 0.99      0.01
glcm_ClusterProminence_d_1_CT_b20                                0.00 1.00      0.00
glcm_ClusterProminence_d_1_CT_c16                                0.00 0.98      0.03
glcm_ClusterProminence_d_1_PET_b2                                0.00 0.97      0.05
glcm_ClusterProminence_d_1_PET_c04                               0.00 0.97      0.05
glcm_ClusterShade_d_1_CT_b20                                     0.00 0.97      0.04
glcm_ClusterShade_d_1_CT_c16                                     0.00 1.00      0.01
glcm_ClusterShade_d_1_PET_b2                                     0.01 0.93      0.11
glcm_ClusterShade_d_1_PET_c04                                    0.00 1.00      0.00
glcm_ClusterTendency_d_1_CT_b20                                  0.00 0.99      0.01
glcm_ClusterTendency_d_1_CT_c16                                  0.00 0.99      0.02
glcm_ClusterTendency_d_1_PET_b2                                  0.00 0.99      0.01
glcm_ClusterTendency_d_1_PET_c04                                 0.00 0.99      0.01
glcm_Contrast_d_1_CT_b20                                         0.00 0.99      0.01
glcm_Contrast_d_1_CT_c16                                         0.00 0.99      0.02
glcm_Contrast_d_1_PET_b2                                         0.00 1.00      0.01
glcm_Contrast_d_1_PET_c04                                        0.00 0.99      0.01
glcm_Correlation_d_1_CT_b20                                      0.00 0.99      0.02
glcm_Correlation_d_1_CT_c16                                      0.00 0.95      0.07
glcm_Correlation_d_1_PET_b2                                      0.00 0.98      0.03
glcm_Correlation_d_1_PET_c04                                     0.00 0.99      0.02
glcm_DifferenceAverage_d_1_CT_b20                                0.00 1.00      0.00
glcm_DifferenceAverage_d_1_CT_c16                                0.00 1.00      0.00
glcm_DifferenceAverage_d_1_PET_b2                                0.00 1.00      0.01
glcm_DifferenceAverage_d_1_PET_c04                               0.00 1.00      0.01
glcm_DifferenceEntropy_d_1_CT_b20                                0.00 1.00      0.01
glcm_DifferenceEntropy_d_1_CT_c16                                0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_PET_b2                                0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_PET_c04                               0.00 0.99      0.01
glcm_DifferenceVariance_d_1_CT_b20                               0.00 1.00      0.01
glcm_DifferenceVariance_d_1_CT_c16                               0.00 0.98      0.03
glcm_DifferenceVariance_d_1_PET_b2                               0.00 0.99      0.02
glcm_DifferenceVariance_d_1_PET_c04                              0.00 0.98      0.02
glcm_Id_d_1_CT_b20                                               0.00 0.99      0.02
glcm_Id_d_1_CT_c16                                               0.00 1.00      0.00
glcm_Id_d_1_PET_b2                                               0.00 1.00      0.01
glcm_Id_d_1_PET_c04                                              0.00 1.00      0.00
glcm_Idm_d_1_CT_b20                                              0.00 0.99      0.02
glcm_Idm_d_1_CT_c16                                              0.00 1.00      0.00
glcm_Idm_d_1_PET_b2                                              0.00 1.00      0.01
glcm_Idm_d_1_PET_c04                                             0.00 1.00      0.01
glcm_Idmn_d_1_CT_b20                                             0.00 1.00      0.00
glcm_Idmn_d_1_CT_c16                                             0.00 0.99      0.01
glcm_Idmn_d_1_PET_b2                                             0.00 1.00      0.01
glcm_Idmn_d_1_PET_c04                                            0.00 0.99      0.01
glcm_Idn_d_1_CT_b20                                              0.00 0.98      0.03
glcm_Idn_d_1_CT_c16                                              0.00 1.00      0.00
glcm_Idn_d_1_PET_b2                                              0.00 0.99      0.01
glcm_Idn_d_1_PET_c04                                             0.00 1.00      0.01
glcm_Imc1_d_1_CT_b20                                             0.00 1.00      0.00
glcm_Imc1_d_1_CT_c16                                             0.01 0.94      0.10
glcm_Imc1_d_1_PET_b2                                             0.00 0.99      0.01
glcm_Imc1_d_1_PET_c04                                            0.00 0.99      0.01
glcm_Imc2_d_1_CT_b20                                             0.00 1.00      0.01
glcm_Imc2_d_1_CT_c16                                             0.00 0.98      0.02
glcm_Imc2_d_1_PET_b2                                             0.00 0.99      0.02
glcm_Imc2_d_1_PET_c04                                            0.00 0.98      0.02
glcm_InverseVariance_d_1_CT_b20                                  0.00 1.00      0.00
glcm_InverseVariance_d_1_CT_c16                                  0.00 0.99      0.01
glcm_InverseVariance_d_1_PET_b2                                  0.00 1.00      0.01
glcm_InverseVariance_d_1_PET_c04                                 0.00 1.00      0.01
glcm_JointAverage_d_1_CT_b20                                     0.00 1.00      0.00
glcm_JointAverage_d_1_CT_c16                                     0.00 0.99      0.02
glcm_JointAverage_d_1_PET_b2                                     0.00 1.00      0.01
glcm_JointAverage_d_1_PET_c04                                    0.00 0.99      0.01
glcm_JointEnergy_d_1_CT_b20                                      0.00 0.97      0.04
glcm_JointEnergy_d_1_CT_c16                                      0.00 1.00      0.00
glcm_JointEnergy_d_1_PET_b2                                      0.00 1.00      0.00
glcm_JointEnergy_d_1_PET_c04                                     0.00 0.98      0.03
glcm_JointEntropy_d_1_CT_b20                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_CT_c16                                     0.00 0.99      0.02
glcm_JointEntropy_d_1_PET_b2                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_PET_c04                                    0.00 0.99      0.01
glcm_MCC_d_1_CT_b20                                              0.00 0.97      0.04
glcm_MCC_d_1_CT_c16                                              0.00 0.95      0.07
glcm_MCC_d_1_PET_b2                                              0.00 0.99      0.01
glcm_MCC_d_1_PET_c04                                             0.00 0.98      0.02
glcm_MaximumProbability_d_1_CT_b20                               0.00 0.96      0.06
glcm_MaximumProbability_d_1_CT_c16                               0.00 1.00      0.00
glcm_MaximumProbability_d_1_PET_b2                               0.00 0.99      0.01
glcm_MaximumProbability_d_1_PET_c04                              0.00 0.99      0.01
glcm_SumAverage_d_1_CT_b20                                       0.00 1.00      0.00
glcm_SumAverage_d_1_CT_c16                                       0.00 0.99      0.02
glcm_SumAverage_d_1_PET_b2                                       0.00 1.00      0.01
glcm_SumAverage_d_1_PET_c04                                      0.00 0.99      0.01
glcm_SumEntropy_d_1_CT_b20                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_CT_c16                                       0.00 0.99      0.01
glcm_SumEntropy_d_1_PET_b2                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_PET_c04                                      0.00 0.99      0.02
glcm_SumSquares_d_1_CT_b20                                       0.00 0.99      0.01
glcm_SumSquares_d_1_CT_c16                                       0.00 0.99      0.02
glcm_SumSquares_d_1_PET_b2                                       0.00 0.99      0.01
glcm_SumSquares_d_1_PET_c04                                      0.00 0.99      0.01
gldm_DependenceEntropy_d_1_CT_b20                                0.00 0.96      0.06
gldm_DependenceEntropy_d_1_CT_c16                                0.00 0.96      0.06
gldm_DependenceEntropy_d_1_PET_b2                                0.00 0.97      0.04
gldm_DependenceEntropy_d_1_PET_c04                               0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.00 1.00      0.00
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.00 1.00      0.00
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.00 1.00      0.01
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.00 0.97      0.04
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00 0.99      0.01
gldm_DependenceNonUniformity_d_1_CT_c16                          0.00 0.99      0.02
gldm_DependenceNonUniformity_d_1_PET_b2                          0.00 0.98      0.03
gldm_DependenceNonUniformity_d_1_PET_c04                         0.00 1.00      0.01
gldm_DependenceVariance_d_1_CT_b20                               0.00 0.97      0.05
gldm_DependenceVariance_d_1_CT_c16                               0.00 0.99      0.01
gldm_DependenceVariance_d_1_PET_b2                               0.00 0.99      0.01
gldm_DependenceVariance_d_1_PET_c04                              0.00 0.99      0.02
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.00 1.00      0.00
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.00 0.99      0.01
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.00 0.97      0.04
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00 0.99      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00 1.00      0.01
gldm_GrayLevelVariance_d_1_CT_c16                                0.00 0.99      0.02
gldm_GrayLevelVariance_d_1_PET_b2                                0.00 0.99      0.01
gldm_GrayLevelVariance_d_1_PET_c04                               0.00 1.00      0.00
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.00 0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00 1.00      0.01
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.00 0.98      0.03
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00 0.99      0.01
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 1.00      0.01
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 1.00      0.00
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 0.98      0.03
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 1.00      0.00
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.97      0.05
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.98      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.00 0.99      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.00 1.00      0.00
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.00 0.97      0.04
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00 0.98      0.02
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.00 0.97      0.04
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00 1.00      0.00
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.99      0.01
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.99      0.01
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 0.99      0.02
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.98      0.02
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.99      0.01
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.99      0.01
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.97      0.05
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.99      0.02
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.00 0.96      0.05
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.01 0.93      0.10
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00 0.99      0.01
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.00 0.99      0.02
glrlm_GrayLevelNonUniformity_CT_b20                              0.00 1.00      0.00
glrlm_GrayLevelNonUniformity_CT_c16                              0.00 0.99      0.02
glrlm_GrayLevelNonUniformity_PET_b2                              0.00 0.98      0.02
glrlm_GrayLevelNonUniformity_PET_c04                             0.00 1.00      0.00
glrlm_GrayLevelVariance_CT_b20                                   0.00 1.00      0.00
glrlm_GrayLevelVariance_CT_c16                                   0.00 1.00      0.01
glrlm_GrayLevelVariance_PET_b2                                   0.00 0.99      0.01

In [7]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index([], dtype='object')

In [8]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic    p  -log2(p)
LBP_003_CT                                                       0.00 0.95      0.07
LBP_003_PET                                                      0.08 0.77      0.37
LBP_012_CT                                                       0.00 0.95      0.07
LBP_012_PET                                                      0.18 0.67      0.57
LBP_021_CT                                                       0.15 0.69      0.53
LBP_021_PET                                                      0.01 0.94      0.09
LBP_030_CT                                                       0.00 0.99      0.01
LBP_030_PET                                                      0.03 0.86      0.21
LBP_102_CT                                                       0.02 0.89      0.17
LBP_102_PET                                                      0.69 0.41      1.30
LBP_111_CT                                                       0.01 0.93      0.11
LBP_111_PET                                                      0.00 0.98      0.03
LBP_120_CT                                                       0.01 0.92      0.12
LBP_120_PET                                                      0.01 0.91      0.14
LBP_201_CT                                                       0.04 0.84      0.25
LBP_201_PET                                                      1.08 0.30      1.74
LBP_210_CT                                                       0.13 0.72      0.47
LBP_210_PET                                                      0.06 0.81      0.30
LBP_300_CT                                                       0.03 0.87      0.19
LBP_300_PET                                                      0.23 0.63      0.67
MTV                                                              0.00 0.98      0.03
SUVpeak                                                          0.01 0.91      0.14
TLG                                                              0.00 0.97      0.05
age                                                              0.11 0.74      0.43
cavum_oris                                                       0.35 0.55      0.85
charlson                                                         1.37 0.24      2.05
female                                                           2.09 0.15      2.76
first_order_10Percentile_CT                                      0.16 0.69      0.54
first_order_10Percentile_PET                                     0.00 0.96      0.06
first_order_90Percentile_CT                                      0.28 0.60      0.74
first_order_90Percentile_PET                                     0.01 0.94      0.08
first_order_Energy_CT                                            0.00 0.95      0.07
first_order_Energy_PET                                           0.02 0.89      0.17
first_order_Entropy_CT_b20                                       0.00 0.95      0.08
first_order_Entropy_CT_c16                                       0.01 0.94      0.09
first_order_Entropy_PET_b2                                       0.00 0.99      0.01
first_order_Entropy_PET_c04                                      0.00 0.99      0.02
first_order_InterquartileRange_CT                                0.00 0.99      0.02
first_order_InterquartileRange_PET                               0.04 0.85      0.23
first_order_Kurtosis_CT                                          0.00 0.95      0.07
first_order_Kurtosis_PET                                         0.00 0.97      0.04
first_order_Maximum_CT                                           0.04 0.83      0.26
first_order_Maximum_PET                                          0.01 0.92      0.11
first_order_MeanAbsoluteDeviation_CT                             0.01 0.92      0.11
first_order_MeanAbsoluteDeviation_PET                            0.00 0.97      0.04
first_order_Mean_CT                                              0.01 0.93      0.11
first_order_Mean_PET                                             0.01 0.92      0.11
first_order_Median_CT                                            0.20 0.65      0.61
first_order_Median_PET                                           0.01 0.93      0.11
first_order_Minimum_CT                                           0.00 0.99      0.01
first_order_Minimum_PET                                          0.02 0.88      0.19
first_order_Range_CT                                             0.03 0.87      0.20
first_order_Range_PET                                            0.01 0.93      0.10
first_order_RobustMeanAbsoluteDeviation_CT                       0.18 0.67      0.57
first_order_RobustMeanAbsoluteDeviation_PET                      0.02 0.88      0.18
first_order_RootMeanSquared_CT                                   0.01 0.91      0.13
first_order_RootMeanSquared_PET                                  0.01 0.93      0.11
first_order_Skewness_CT                                          0.04 0.84      0.25
first_order_Skewness_PET                                         0.00 0.99      0.02
first_order_TotalEnergy_CT                                       0.00 0.95      0.07
first_order_TotalEnergy_PET                                      0.02 0.89      0.17
first_order_Uniformity_CT_b20                                    0.00 0.97      0.04
first_order_Uniformity_CT_c16                                    0.00 0.97      0.04
first_order_Uniformity_PET_b2                                    0.02 0.90      0.15
first_order_Uniformity_PET_c04                                   0.01 0.93      0.10
first_order_Variance_CT                                          0.00 1.00      0.00
first_order_Variance_PET                                         0.00 0.95      0.07
glcm_Autocorrelation_d_1_CT_b20                                  0.00 0.97      0.05
glcm_Autocorrelation_d_1_CT_c16                                  0.00 1.00      0.01
glcm_Autocorrelation_d_1_PET_b2                                  0.00 0.98      0.03
glcm_Autocorrelation_d_1_PET_c04                                 0.00 0.95      0.07
glcm_ClusterProminence_d_1_CT_b20                                0.03 0.86      0.22
glcm_ClusterProminence_d_1_CT_c16                                0.01 0.93      0.11
glcm_ClusterProminence_d_1_PET_b2                                0.02 0.88      0.19
glcm_ClusterProminence_d_1_PET_c04                               0.03 0.86      0.22
glcm_ClusterShade_d_1_CT_b20                                     0.11 0.74      0.42
glcm_ClusterShade_d_1_CT_c16                                     0.02 0.89      0.16
glcm_ClusterShade_d_1_PET_b2                                     0.00 0.99      0.01
glcm_ClusterShade_d_1_PET_c04                                    0.06 0.81      0.31
glcm_ClusterTendency_d_1_CT_b20                                  0.00 0.96      0.06
glcm_ClusterTendency_d_1_CT_c16                                  0.01 0.91      0.14
glcm_ClusterTendency_d_1_PET_b2                                  0.00 0.95      0.08
glcm_ClusterTendency_d_1_PET_c04                                 0.08 0.78      0.36
glcm_Contrast_d_1_CT_b20                                         0.00 0.98      0.02
glcm_Contrast_d_1_CT_c16                                         0.02 0.89      0.17
glcm_Contrast_d_1_PET_b2                                         0.00 0.97      0.04
glcm_Contrast_d_1_PET_c04                                        0.00 0.98      0.04
glcm_Correlation_d_1_CT_b20                                      0.05 0.82      0.28
glcm_Correlation_d_1_CT_c16                                      0.29 0.59      0.77
glcm_Correlation_d_1_PET_b2                                      0.00 0.97      0.04
glcm_Correlation_d_1_PET_c04                                     0.00 0.96      0.05
glcm_DifferenceAverage_d_1_CT_b20                                0.01 0.92      0.13
glcm_DifferenceAverage_d_1_CT_c16                                0.00 0.95      0.08
glcm_DifferenceAverage_d_1_PET_b2                                0.00 0.96      0.06
glcm_DifferenceAverage_d_1_PET_c04                               0.00 0.98      0.03
glcm_DifferenceEntropy_d_1_CT_b20                                0.01 0.93      0.10
glcm_DifferenceEntropy_d_1_CT_c16                                0.00 0.97      0.05
glcm_DifferenceEntropy_d_1_PET_b2                                0.00 0.95      0.07
glcm_DifferenceEntropy_d_1_PET_c04                               0.00 0.97      0.04
glcm_DifferenceVariance_d_1_CT_b20                               0.00 0.98      0.03
glcm_DifferenceVariance_d_1_CT_c16                               0.02 0.88      0.18
glcm_DifferenceVariance_d_1_PET_b2                               0.00 1.00      0.00
glcm_DifferenceVariance_d_1_PET_c04                              0.00 0.99      0.02
glcm_Id_d_1_CT_b20                                               0.05 0.83      0.27
glcm_Id_d_1_CT_c16                                               0.00 0.96      0.05
glcm_Id_d_1_PET_b2                                               0.01 0.93      0.11
glcm_Id_d_1_PET_c04                                              0.00 0.96      0.06
glcm_Idm_d_1_CT_b20                                              0.05 0.83      0.27
glcm_Idm_d_1_CT_c16                                              0.00 0.97      0.04
glcm_Idm_d_1_PET_b2                                              0.01 0.94      0.09
glcm_Idm_d_1_PET_c04                                             0.00 0.97      0.05
glcm_Idmn_d_1_CT_b20                                             0.02 0.90      0.15
glcm_Idmn_d_1_CT_c16                                             0.02 0.90      0.15
glcm_Idmn_d_1_PET_b2                                             0.01 0.93      0.11
glcm_Idmn_d_1_PET_c04                                            0.00 0.98      0.03
glcm_Idn_d_1_CT_b20                                              0.00 0.99      0.01
glcm_Idn_d_1_CT_c16                                              0.00 0.96      0.06
glcm_Idn_d_1_PET_b2                                              0.00 0.99      0.02
glcm_Idn_d_1_PET_c04                                             0.00 0.97      0.04
glcm_Imc1_d_1_CT_b20                                             0.04 0.85      0.24
glcm_Imc1_d_1_CT_c16                                             0.34 0.56      0.84
glcm_Imc1_d_1_PET_b2                                             0.00 0.99      0.02
glcm_Imc1_d_1_PET_c04                                            0.00 0.96      0.07
glcm_Imc2_d_1_CT_b20                                             0.09 0.77      0.38
glcm_Imc2_d_1_CT_c16                                             0.13 0.72      0.48
glcm_Imc2_d_1_PET_b2                                             0.01 0.94      0.09
glcm_Imc2_d_1_PET_c04                                            0.01 0.93      0.11
glcm_InverseVariance_d_1_CT_b20                                  0.18 0.67      0.58
glcm_InverseVariance_d_1_CT_c16                                  0.01 0.91      0.14
glcm_InverseVariance_d_1_PET_b2                                  0.03 0.87      0.20
glcm_InverseVariance_d_1_PET_c04                                 0.01 0.91      0.13
glcm_JointAverage_d_1_CT_b20                                     0.00 0.98      0.02
glcm_JointAverage_d_1_CT_c16                                     0.00 0.97      0.04
glcm_JointAverage_d_1_PET_b2                                     0.00 0.99      0.01
glcm_JointAverage_d_1_PET_c04                                    0.01 0.93      0.10
glcm_JointEnergy_d_1_CT_b20                                      0.01 0.93      0.11
glcm_JointEnergy_d_1_CT_c16                                      0.00 1.00      0.01
glcm_JointEnergy_d_1_PET_b2                                      0.03 0.86      0.22
glcm_JointEnergy_d_1_PET_c04                                     0.02 0.90      0.16
glcm_JointEntropy_d_1_CT_b20                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_CT_c16                                     0.02 0.90      0.15
glcm_JointEntropy_d_1_PET_b2                                     0.00 0.97      0.05
glcm_JointEntropy_d_1_PET_c04                                    0.00 0.99      0.01
glcm_MCC_d_1_CT_b20                                              0.00 0.96      0.06
glcm_MCC_d_1_CT_c16                                              0.01 0.94      0.08
glcm_MCC_d_1_PET_b2                                              0.00 1.00      0.00
glcm_MCC_d_1_PET_c04                                             0.00 0.99      0.01
glcm_MaximumProbability_d_1_CT_b20                               0.01 0.92      0.11
glcm_MaximumProbability_d_1_CT_c16                               0.02 0.89      0.17
glcm_MaximumProbability_d_1_PET_b2                               0.04 0.85      0.23
glcm_MaximumProbability_d_1_PET_c04                              0.00 0.95      0.07
glcm_SumAverage_d_1_CT_b20                                       0.00 0.98      0.02
glcm_SumAverage_d_1_CT_c16                                       0.00 0.97      0.04
glcm_SumAverage_d_1_PET_b2                                       0.00 0.99      0.01
glcm_SumAverage_d_1_PET_c04                                      0.01 0.93      0.10
glcm_SumEntropy_d_1_CT_b20                                       0.00 0.95      0.08
glcm_SumEntropy_d_1_CT_c16                                       0.01 0.91      0.14
glcm_SumEntropy_d_1_PET_b2                                       0.00 0.96      0.05
glcm_SumEntropy_d_1_PET_c04                                      0.00 0.98      0.03
glcm_SumSquares_d_1_CT_b20                                       0.00 0.96      0.05
glcm_SumSquares_d_1_CT_c16                                       0.01 0.93      0.11
glcm_SumSquares_d_1_PET_b2                                       0.00 0.95      0.08
glcm_SumSquares_d_1_PET_c04                                      0.08 0.78      0.36
gldm_DependenceEntropy_d_1_CT_b20                                0.11 0.74      0.44
gldm_DependenceEntropy_d_1_CT_c16                                0.05 0.83      0.27
gldm_DependenceEntropy_d_1_PET_b2                                0.00 0.97      0.04
gldm_DependenceEntropy_d_1_PET_c04                               0.00 0.95      0.07
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.10 0.75      0.42
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.00 0.99      0.02
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.01 0.92      0.12
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.01 0.93      0.10
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00 0.99      0.01
gldm_DependenceNonUniformity_d_1_CT_c16                          0.01 0.93      0.10
gldm_DependenceNonUniformity_d_1_PET_b2                          0.01 0.90      0.15
gldm_DependenceNonUniformity_d_1_PET_c04                         0.00 0.99      0.01
gldm_DependenceVariance_d_1_CT_b20                               0.52 0.47      1.09
gldm_DependenceVariance_d_1_CT_c16                               0.17 0.68      0.55
gldm_DependenceVariance_d_1_PET_b2                               0.07 0.80      0.33
gldm_DependenceVariance_d_1_PET_c04                              0.07 0.78      0.35
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.00 0.97      0.05
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.01 0.94      0.09
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.00 0.97      0.04
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00 1.00      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00 1.00      0.00
gldm_GrayLevelVariance_d_1_CT_c16                                0.00 1.00      0.00
gldm_GrayLevelVariance_d_1_PET_b2                                0.00 0.94      0.08
gldm_GrayLevelVariance_d_1_PET_c04                               0.05 0.83      0.27
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.00 0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00 0.99      0.02
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00 0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00 0.95      0.07
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.02 0.88      0.18
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.03 0.86      0.22
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.01 0.92      0.11
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00 0.98      0.03
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.96      0.06
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.03 0.86      0.22
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.01 0.94      0.09
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.95      0.07
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.03 0.86      0.22
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.99      0.02
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.95      0.08
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.06 0.81      0.30
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.03 0.86      0.21
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00 0.98      0.02
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00 0.94      0.08
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.02 0.89      0.17
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.01 0.91      0.13
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00 0.99      0.01
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.07 0.79      0.33
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00 0.96      0.06
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.99      0.02
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.97      0.04
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.02 0.89      0.16
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.01 0.92      0.13
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.01 0.94      0.08
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.03 0.86      0.22
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.22 0.64      0.65
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 1.00      0.00
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.00 0.96      0.05
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.00 0.95      0.08
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00 0.96      0.06
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.00 1.00      0.01
glrlm_GrayLevelNonUniformity_CT_b20                              0.00 0.95      0.07
glrlm_GrayLevelNonUniformity_CT_c16                              0.06 0.81      0.30
glrlm_GrayLevelNonUniformity_PET_b2                              0.00 0.99      0.02
glrlm_GrayLevelNonUniformity_PET_c04                             0.00 0.99      0.01
glrlm_GrayLevelVariance_CT_b20                                   0.00 0.95      0.08
glrlm_GrayLevelVariance_CT_c16                                   0.00 0.96      0.06
glrlm_GrayLevelVariance_PET_b2                                   0.00 0.96      0.06

In [9]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['hpv_related'], dtype='object')

## Test dataset: MAASTRO

In [10]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [11]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [12]:
# Need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [13]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,OS,OS_event
0,1,55,0,0,1,0,0,1,1,1,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,44.43,1.0
3,4,61,1,0,0,0,1,1,0,1,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,37.20,1.0
4,6,70,0,0,1,0,0,1,1,1,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,19.00,1.0
95,111,63,0,0,0,0,1,0,0,1,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [14]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [15]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [16]:
# Set X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# Set y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [17]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [18]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 388)
y_train:  (139,)

In [19]:
# Change the name of a column 'OS_event' in the clincial_test 
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [20]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 390)

# Standardization

In [21]:
# Copy the original X for later 
original_X = X.copy()

In [22]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

## Standardize the data but not the categorical columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']
### Separate the categorical and non-categorical columns
X_categorical = X[categorical_columns]
X_numeric = X.drop(categorical_columns, axis=1)
X_numeric_columns = X_numeric.columns
X_numeric_index = X_numeric.index

### Standardize non-categorical and then concat with the categorical
scaler = MinMaxScaler()  
X_numeric_std = scaler.fit_transform(X_numeric)
X_numeric_std = pd.DataFrame(X_numeric_std, columns=X_numeric_columns, index=X_numeric_index)
X_std = pd.concat([X_categorical, X_numeric_std], axis=1)

## Sort the order of the columns as it was in the clinical train 
X_std = X_std[original_X.columns]

In [23]:
# Divide the X_MAASTRO into numerical part and categorical part 
X_MAASTRO_categorical = X_MAASTRO[categorical_columns]
X_MAASTRO_numeric = X_MAASTRO.drop(categorical_columns, axis=1)

# Save the column name and index of the numeric part
X_MAASTRO_numeric_columns = X_MAASTRO_numeric.columns
X_MAASTRO_numeric_index = X_MAASTRO_numeric.index

In [24]:
# Standardize the numeric part 
X_MAASTRO_numeric_std = scaler.transform(X_MAASTRO_numeric)

# Change the standardized part into a dataframe 
X_MAASTRO_numeric_std = pd.DataFrame(X_MAASTRO_numeric_std, columns=X_MAASTRO_numeric_columns, index=X_MAASTRO_numeric_index)

# Concat the standardized part with the categorical part 
X_MAASTRO_std = pd.concat([X_MAASTRO_categorical, X_MAASTRO_numeric_std], axis=1)

# Change the column order of X_MAASTRO_std
X_MAASTRO_std = X_MAASTRO_std[original_X.columns]

In [25]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = X_MAASTRO_std

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [26]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:53:48,120] A new study created in memory with name: no-name-8f1e04fa-16b2-4215-b806-8c65b0b56f36

  0%|          | 0/1 [00:00<?, ?it/s]

[W 2024-04-17 13:53:49,183] Trial 0 failed with parameters: {} because of the following error: ValueError('search direction contains NaN or infinite values').
Traceback (most recent call last):
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/var/folders/64/jkqp6xyx2hj50dmd2pqfm3780000gn/T/ipykernel_1517/32179911.py", line 62, in objective
    model.fit(X_train_std, y_train)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/linear_model/coxph.py", line 454, in fit
    raise ValueError("search direction contains NaN or infinite values")
ValueError: search direction contains NaN or infinite values
[W 2024-04-17 13:53:49,186] Trial 0 failed with value None.

ValueError: search direction contains NaN or infinite values

In [26]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {}

In [27]:
# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

NameError: name 'study_cindex' is not defined

In [28]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

NameError: name 'study_cindex' is not defined

#### Test

In [29]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

ValueError: no field of name event_OS

In [30]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

ValueError: search direction contains NaN or infinite values

In [32]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [31]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

NameError: name 'c_index' is not defined

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [33]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 14:01:42,790] A new study created in memory with name: no-name-9b0c2716-39a2-417a-88e4-66699919e8bb

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6517857142857143

[I 2024-04-17 14:01:43,346] A new study created in memory with name: no-name-2b6dc097-180b-401a-a63d-731d90cca5f3

Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6150234741784038
[I 2024-04-17 14:01:43,325] Trial 0 finished with value: 0.6960713495758277 and parameters: {}. Best is trial 0 with value: 0.6960713495758277.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6960713495758277], datetime_start=datetime.datetime(2024, 4, 17, 14, 1, 42, 922366), datetime_complete=datetime.datetime(2024, 4, 17, 14, 1, 43, 324666), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6960713495758277

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652072992826
Fold 2 IBS: 0.22157791642234437
Fold 3 IBS: 0.2045359451344516
Fold 4 IBS: 0.2247380389083103
Fold 5 IBS: 0.21812431485322203
[I 2024-04-17 14:01:43,892] Trial 0 finished with value: 0.21659054720965135 and parameters: {}. Best is trial 0 with value: 0.21659054720965135.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054720965135], datetime_start=datetime.datetime(2024, 4, 17, 14, 1, 43, 379668), datetime_complete=datetime.datetime(2024, 4, 17, 14, 1, 43, 892319), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054720965135

In [34]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [35]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.696
train_ibs:  0.217

#### Test

In [36]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [37]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.593

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [38]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [39]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 14:01:44,613] A new study created in memory with name: no-name-13d33125-4795-476a-847b-f4d7874a82a9

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.5822784810126582

[I 2024-04-17 14:01:46,409] A new study created in memory with name: no-name-ac91f595-5a65-4e79-8cd8-864ba972939d

Fold 5 C-index: 0.6291079812206573
[I 2024-04-17 14:01:46,400] Trial 0 finished with value: 0.6184757263656853 and parameters: {}. Best is trial 0 with value: 0.6184757263656853.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6184757263656853], datetime_start=datetime.datetime(2024, 4, 17, 14, 1, 44, 647228), datetime_complete=datetime.datetime(2024, 4, 17, 14, 1, 46, 399936), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6184757263656853

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2762585395331656
Fold 2 IBS: 0.41353531040721364
Fold 3 IBS: 0.21815599710209907
Fold 4 IBS: 0.36183670595627526
Fold 5 IBS: 0.291246720935057
[I 2024-04-17 14:01:48,670] Trial 0 finished with value: 0.3122066547867622 and parameters: {}. Best is trial 0 with value: 0.3122066547867622.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.3122066547867622], datetime_start=datetime.datetime(2024, 4, 17, 14, 1, 46, 435226), datetime_complete=datetime.datetime(2024, 4, 17, 14, 1, 48, 669628), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.3122066547867622

In [40]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [41]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.618
train_ibs:  0.312

#### Test

In [42]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [43]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.557

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.393

In [44]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [45]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 14:01:49,805] A new study created in memory with name: no-name-b1372a9b-c946-4d10-9663-5359881a9223

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 14:01:51,624] Trial 0 finished with value: 0.6773681368769489 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6773681368769489.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:01:53,297] Trial 1 finished with value: 0.704948844843696 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.704948844843696.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 14:01:54,697] Trial 2 finished with value: 0.7168975318777895 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.7168975318777895.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:01:56,030] Trial 3 finished with value: 0.6969880742293515 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.7168975318777895.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 14:01:57,416] Trial 4 finished with value: 0.6754602810345681 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.7168975318777895.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 14:01:58,776] Trial 5 finished with value: 0.7022559046714685 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.7168975318777895.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6033755274261603
Fold 5 C-index: 0.6384976525821596
[I 2024-04-17 14:02:00,726] Trial 6 finished with value: 0.6356374956909943 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.7168975318777895.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 14:02:02,239] Trial 7 finished with value: 0.6783341602901555 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.7168975318777895.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:02:03,841] Trial 8 finished with value: 0.699629173822238 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.7168975318777895.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:02:05,932] Trial 9 finished with value: 0.700473055678778 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.7168975318777895.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:02:07,268] Trial 10 finished with value: 0.7493352460597199 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.7493352460597199.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.607981220657277
[I 2024-04-17 14:02:07,724] Trial 11 finished with value: 0.7014035381652944 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.7493352460597199.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:02:09,650] Trial 12 finished with value: 0.7493352460597199 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 10 with value: 0.7493352460597199.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.607981220657277
[I 2024-04-17 14:02:10,546] Trial 13 finished with value: 0.7014035381652944 and parameters: {'l1_ratio': 0.0031985064812224406}. Best is trial 10 with value: 0.7493352460597199.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:02:12,362] Trial 14 finished with value: 0.740787009223372 and parameters: {'l1_ratio': 0.14354731809284052}. Best is trial 10 with value: 0.7493352460597199.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:02:14,189] Trial 15 finished with value: 0.740787009223372 and parameters: {'l1_ratio': 0.14547377630010583}. Best is trial 10 with value: 0.7493352460597199.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:02:15,694] Trial 16 finished with value: 0.743411468097831 and parameters: {'l1_ratio': 0.13463318817607284}. Best is trial 10 with value: 0.7493352460597199.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:02:17,677] Trial 17 finished with value: 0.704948844843696 and parameters: {'l1_ratio': 0.2906031874230555}. Best is trial 10 with value: 0.7493352460597199.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 14:02:19,051] Trial 18 finished with value: 0.7492430260731338 and parameters: {'l1_ratio': 0.0668769468789637}. Best is trial 10 with value: 0.7493352460597199.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.5401785714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.5864978902953587
Fold 5 C-index: 0.6338028169014085
[I 2024-04-17 14:02:21,578] Trial 19 finished with value: 0.6259053795345915 and parameters: {'l1_ratio': 0.9929341434741732}. Best is trial 10 with value: 0.7493352460597199.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 14:02:23,482] Trial 20 finished with value: 0.714936747564064 and parameters: {'l1_ratio': 0.2388803760219412}. Best is trial 10 with value: 0.7493352460597199.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:02:25,036] Trial 21 finished with value: 0.7502742131958702 and parameters: {'l1_ratio': 0.08499433228302328}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:02:26,330] Trial 22 finished with value: 0.7454597874255621 and parameters: {'l1_ratio': 0.10159828709381563}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 14:02:28,260] Trial 23 finished with value: 0.7141808530167444 and parameters: {'l1_ratio': 0.20450032756347597}. Best is trial 21 with value: 0.7502742131958702.

Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:02:30,329] Trial 24 finished with value: 0.7030047012483983 and parameters: {'l1_ratio': 0.3389201479305571}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:02:31,336] Trial 25 finished with value: 0.7197133973202241 and parameters: {'l1_ratio': 0.03981317955666948}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7136150234741784
[I 2024-04-17 14:02:33,580] Trial 26 finished with value: 0.7179464053324209 and parameters: {'l1_ratio': 0.18783928730207888}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 14:02:35,776] Trial 27 finished with value: 0.6944857569115589 and parameters: {'l1_ratio': 0.58416616744615}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:02:36,871] Trial 28 finished with value: 0.7463940695891317 and parameters: {'l1_ratio': 0.09146853847676947}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6329113924050633
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 14:02:38,987] Trial 29 finished with value: 0.6577033184462946 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:02:41,467] Trial 30 finished with value: 0.7020876531215089 and parameters: {'l1_ratio': 0.32170963481394405}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:02:42,844] Trial 31 finished with value: 0.7402491116059384 and parameters: {'l1_ratio': 0.05275796625098443}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 14:02:44,331] Trial 32 finished with value: 0.7483962789235697 and parameters: {'l1_ratio': 0.0791864451035049}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 14:02:46,829] Trial 33 finished with value: 0.7129442220007016 and parameters: {'l1_ratio': 0.25343564520474016}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:02:48,612] Trial 34 finished with value: 0.7187585459393242 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.607981220657277
[I 2024-04-17 14:02:49,148] Trial 35 finished with value: 0.7014035381652944 and parameters: {'l1_ratio': 0.0013526982279536137}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:02:50,675] Trial 36 finished with value: 0.7445208202894118 and parameters: {'l1_ratio': 0.09706877268604626}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7136150234741784
[I 2024-04-17 14:02:52,965] Trial 37 finished with value: 0.7159856210186955 and parameters: {'l1_ratio': 0.2167882288335798}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:02:55,351] Trial 38 finished with value: 0.7030047012483983 and parameters: {'l1_ratio': 0.3752900822742875}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 14:02:59,019] Trial 39 finished with value: 0.7102051718351807 and parameters: {'l1_ratio': 0.26752967499719527}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7136150234741784
[I 2024-04-17 14:03:02,422] Trial 40 finished with value: 0.7023509899510786 and parameters: {'l1_ratio': 0.46667819693088786}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 14:03:03,610] Trial 41 finished with value: 0.7474112017941263 and parameters: {'l1_ratio': 0.07419373672571489}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:03:05,243] Trial 42 finished with value: 0.743411468097831 and parameters: {'l1_ratio': 0.12846918174516112}. Best is trial 21 with value: 0.7502742131958702.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:03:06,381] Trial 43 finished with value: 0.752101352502297 and parameters: {'l1_ratio': 0.059820186386939866}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.607981220657277
[I 2024-04-17 14:03:06,832] Trial 44 finished with value: 0.7014035381652944 and parameters: {'l1_ratio': 0.03834194526153677}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:03:08,593] Trial 45 finished with value: 0.7170488632169832 and parameters: {'l1_ratio': 0.18074152502476082}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 14:03:10,538] Trial 46 finished with value: 0.6712061241861693 and parameters: {'l1_ratio': 0.7690246429558334}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:03:12,292] Trial 47 finished with value: 0.7408140655004283 and parameters: {'l1_ratio': 0.1426102255542931}. Best is trial 43 with value: 0.752101352502297.

Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:03:14,370] Trial 48 finished with value: 0.6935197334983524 and parameters: {'l1_ratio': 0.5683872043393509}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 14:03:15,297] Trial 49 finished with value: 0.7383711773336379 and parameters: {'l1_ratio': 0.0514525901144702}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:03:16,622] Trial 50 finished with value: 0.7452847173975508 and parameters: {'l1_ratio': 0.12351557584006105}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 14:03:17,838] Trial 51 finished with value: 0.7474112017941263 and parameters: {'l1_ratio': 0.07032343110985169}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.607981220657277
[I 2024-04-17 14:03:18,601] Trial 52 finished with value: 0.7014035381652944 and parameters: {'l1_ratio': 0.005167331735789121}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:03:20,627] Trial 53 finished with value: 0.7197389380961869 and parameters: {'l1_ratio': 0.16504314926261965}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:03:21,892] Trial 54 finished with value: 0.7444793952686993 and parameters: {'l1_ratio': 0.10321051349529076}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 14:03:22,763] Trial 55 finished with value: 0.7187744301840737 and parameters: {'l1_ratio': 0.04169711383715152}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 14:03:24,598] Trial 56 finished with value: 0.7187707811775093 and parameters: {'l1_ratio': 0.19981963411080123}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:03:26,696] Trial 57 finished with value: 0.6863128967287333 and parameters: {'l1_ratio': 0.6276685535082955}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:03:28,044] Trial 58 finished with value: 0.7493352460597199 and parameters: {'l1_ratio': 0.08447678342494082}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:03:29,299] Trial 59 finished with value: 0.7453722524115565 and parameters: {'l1_ratio': 0.11509359234200214}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:03:31,399] Trial 60 finished with value: 0.704948844843696 and parameters: {'l1_ratio': 0.29621442168304435}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:03:32,582] Trial 61 finished with value: 0.7502742131958702 and parameters: {'l1_ratio': 0.08497028745341434}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:03:34,382] Trial 62 finished with value: 0.7188731372303861 and parameters: {'l1_ratio': 0.15739252073995053}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.607981220657277
[I 2024-04-17 14:03:34,851] Trial 63 finished with value: 0.7014035381652944 and parameters: {'l1_ratio': 0.02931853901814066}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 14:03:36,171] Trial 64 finished with value: 0.7483962789235697 and parameters: {'l1_ratio': 0.07975046133911966}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 14:03:38,137] Trial 65 finished with value: 0.7168975318777895 and parameters: {'l1_ratio': 0.22542644123292493}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.607981220657277
[I 2024-04-17 14:03:38,593] Trial 66 finished with value: 0.7014035381652944 and parameters: {'l1_ratio': 0.00048544157642338437}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:03:39,680] Trial 67 finished with value: 0.7453722524115565 and parameters: {'l1_ratio': 0.1159733377880855}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:03:40,505] Trial 68 finished with value: 0.7402491116059384 and parameters: {'l1_ratio': 0.0540869519102236}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:03:41,926] Trial 69 finished with value: 0.740787009223372 and parameters: {'l1_ratio': 0.14881965141192482}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:03:43,154] Trial 70 finished with value: 0.7473744617459944 and parameters: {'l1_ratio': 0.09041852064378501}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8059071729957806

Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 14:03:44,826] Trial 71 finished with value: 0.7501819932092839 and parameters: {'l1_ratio': 0.06301381496313624}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.607981220657277
[I 2024-04-17 14:03:45,419] Trial 72 finished with value: 0.7014035381652944 and parameters: {'l1_ratio': 0.0340472217885377}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 14:03:46,559] Trial 73 finished with value: 0.7501358832159909 and parameters: {'l1_ratio': 0.06389320707816884}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7136150234741784
[I 2024-04-17 14:03:48,275] Trial 74 finished with value: 0.7179464053324209 and parameters: {'l1_ratio': 0.18938838973363886}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.607981220657277
[I 2024-04-17 14:03:48,691] Trial 75 finished with value: 0.7014035381652944 and parameters: {'l1_ratio': 0.02819907046014241}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 14:03:49,823] Trial 76 finished with value: 0.7474112017941263 and parameters: {'l1_ratio': 0.0743853222702239}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:03:50,874] Trial 77 finished with value: 0.7462651095544135 and parameters: {'l1_ratio': 0.12024290825772173}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.5848214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6118143459915611
Fold 5 C-index: 0.6525821596244131
[I 2024-04-17 14:03:52,820] Trial 78 finished with value: 0.6463651045354688 and parameters: {'l1_ratio': 0.9506480490309224}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:03:54,311] Trial 79 finished with value: 0.740787009223372 and parameters: {'l1_ratio': 0.1455390266902418}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:03:55,532] Trial 80 finished with value: 0.7455012124462745 and parameters: {'l1_ratio': 0.09373925408571145}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:03:56,633] Trial 81 finished with value: 0.7511209603454343 and parameters: {'l1_ratio': 0.06132165438458675}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.607981220657277
[I 2024-04-17 14:03:57,179] Trial 82 finished with value: 0.7014035381652944 and parameters: {'l1_ratio': 0.02279319013579669}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:03:58,074] Trial 83 finished with value: 0.7393562544630813 and parameters: {'l1_ratio': 0.05852400259230922}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:03:59,116] Trial 84 finished with value: 0.7454597874255621 and parameters: {'l1_ratio': 0.10138597597823001}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 14:04:00,221] Trial 85 finished with value: 0.7501358832159909 and parameters: {'l1_ratio': 0.06414002592761575}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:04:02,528] Trial 86 finished with value: 0.6969880742293515 and parameters: {'l1_ratio': 0.5196302291802515}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:04:03,808] Trial 87 finished with value: 0.7393562544630813 and parameters: {'l1_ratio': 0.05831646243450877}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:04:05,721] Trial 88 finished with value: 0.7187585459393242 and parameters: {'l1_ratio': 0.16880465695640456}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:04:07,287] Trial 89 finished with value: 0.743411468097831 and parameters: {'l1_ratio': 0.13243185316732858}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.607981220657277
[I 2024-04-17 14:04:08,058] Trial 90 finished with value: 0.7014035381652944 and parameters: {'l1_ratio': 0.022278513803798784}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 14:04:09,525] Trial 91 finished with value: 0.7483501689302765 and parameters: {'l1_ratio': 0.07622143203826334}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:04:11,495] Trial 92 finished with value: 0.7444793952686993 and parameters: {'l1_ratio': 0.10762431424950807}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 14:04:12,450] Trial 93 finished with value: 0.7178354630479236 and parameters: {'l1_ratio': 0.04520110851903156}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:04:14,238] Trial 94 finished with value: 0.743411468097831 and parameters: {'l1_ratio': 0.13494384716526905}. Best is trial 43 with value: 0.752101352502297.

Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 14:04:16,273] Trial 95 finished with value: 0.7139563554072013 and parameters: {'l1_ratio': 0.24418020562852596}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 14:04:18,921] Trial 96 finished with value: 0.6710696138858466 and parameters: {'l1_ratio': 0.754234381640172}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.607981220657277
[I 2024-04-17 14:04:19,605] Trial 97 finished with value: 0.7014035381652944 and parameters: {'l1_ratio': 0.01713710143549492}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:04:21,169] Trial 98 finished with value: 0.7483134288821447 and parameters: {'l1_ratio': 0.08684686130814945}. Best is trial 43 with value: 0.752101352502297.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6919831223628692

[I 2024-04-17 14:04:24,027] A new study created in memory with name: no-name-05e2ff2f-ecd8-4467-b60a-e7c4a02bed0a

Fold 5 C-index: 0.7136150234741784
[I 2024-04-17 14:04:24,013] Trial 99 finished with value: 0.7159856210186955 and parameters: {'l1_ratio': 0.20156005904597973}. Best is trial 43 with value: 0.752101352502297.


* Best trial for C-index:
 FrozenTrial(number=43, state=TrialState.COMPLETE, values=[0.752101352502297], datetime_start=datetime.datetime(2024, 4, 17, 14, 3, 5, 259531), datetime_complete=datetime.datetime(2024, 4, 17, 14, 3, 6, 381054), params={'l1_ratio': 0.059820186386939866}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=43, value=None)


* Best Score for C-index:
 0.752101352502297

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23319617401585882
Fold 2 IBS: 0.2720478160503878
Fold 3 IBS: 0.18773271416384826
Fold 4 IBS: 0.30237953710866655
Fold 5 IBS: 0.24453961696981222
[I 2024-04-17 14:04:27,251] Trial 0 finished with value: 0.24797917166171474 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.24797917166171474.
Fold 1 IBS: 0.22124305499591704
Fold 2 IBS: 0.19534257636536786
Fold 3 IBS: 0.17162097803640342
Fold 4 IBS: 0.2408830724554311
Fold 5 IBS: 0.2453146645229908
[I 2024-04-17 14:04:29,738] Trial 1 finished with value: 0.21488086927522207 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.21488086927522207.
Fold 1 IBS: 0.21986380244426754
Fold 2 IBS: 0.18751626253306222
Fold 3 IBS: 0.1683760112880067
Fold 4 IBS: 0.23382875689539379
Fold 5 IBS: 0.24543070744537998
[I 2024-04-17 14:04:32,477] Trial 2 finished with value: 0.21100310812122203 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.21100310812122203.
Fold 1 IBS: 0.22530813457798554
Fold 2 IBS: 0.23985523024064012
Fold 3 IBS: 0.18242919435278718
Fold 4 IBS: 0.2774185022364898
Fold 5 IBS: 0.24425065377054328
[I 2024-04-17 14:04:34,864] Trial 3 finished with value: 0.2338523430356892 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.21100310812122203.
Fold 1 IBS: 0.2347296681371931
Fold 2 IBS: 0.27722675882220355
Fold 3 IBS: 0.18836366449541334
Fold 4 IBS: 0.3068374021169365
Fold 5 IBS: 0.24509782560930143
[I 2024-04-17 14:04:37,264] Trial 4 finished with value: 0.2504510638362096 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.21100310812122203.
Fold 1 IBS: 0.22293361118280394
Fold 2 IBS: 0.2160633740671744
Fold 3 IBS: 0.17826775625033303
Fold 4 IBS: 0.25866474020707436
Fold 5 IBS: 0.24499341998048318
[I 2024-04-17 14:04:39,135] Trial 5 finished with value: 0.2241845803375738 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.21100310812122203.
Fold 1 IBS: 0.26806388604200726
Fold 2 IBS: 0.38763095664099456
Fold 3 IBS: 0.2118644866950204
Fold 4 IBS: 0.3498247285074405
Fold 5 IBS: 0.28502743121528207
[I 2024-04-17 14:04:42,350] Trial 6 finished with value: 0.30048229782014896 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.21100310812122203.
Fold 1 IBS: 0.2323179687455634
Fold 2 IBS: 0.2693979056237844
Fold 3 IBS: 0.1874684205316553
Fold 4 IBS: 0.29998819573997487
Fold 5 IBS: 0.24438964273198266
[I 2024-04-17 14:04:44,366] Trial 7 finished with value: 0.24671242667459214 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.21100310812122203.
Fold 1 IBS: 0.2236982403876851
Fold 2 IBS: 0.22626639473984037
Fold 3 IBS: 0.18031371025208312
Fold 4 IBS: 0.26688315670483215
Fold 5 IBS: 0.2447484652503953
[I 2024-04-17 14:04:46,789] Trial 8 finished with value: 0.22838199346696722 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.21100310812122203.
Fold 1 IBS: 0.22227379221232357
Fold 2 IBS: 0.2107356343803977
Fold 3 IBS: 0.1769192777475148
Fold 4 IBS: 0.25436864019010635
Fold 5 IBS: 0.24502804319784335
[I 2024-04-17 14:04:49,449] Trial 9 finished with value: 0.22186507754563714 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.21100310812122203.
Fold 1 IBS: 0.2129463812203201
Fold 2 IBS: 0.17902356187340251
Fold 3 IBS: 0.15485991055153503
Fold 4 IBS: 0.22272119256311154
Fold 5 IBS: 0.23936486046567432
[I 2024-04-17 14:04:50,917] Trial 10 finished with value: 0.2017831813348087 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.2017831813348087.
Fold 1 IBS: 0.21382659040463048
Fold 2 IBS: 0.22148595749598324
Fold 3 IBS: 0.20426912270507494
Fold 4 IBS: 0.22443405210312942
Fold 5 IBS: 0.21807545517223684
[I 2024-04-17 14:04:51,759] Trial 11 finished with value: 0.21641823557621098 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.2017831813348087.
Fold 1 IBS: 0.2129474570264946
Fold 2 IBS: 0.1790198373695293
Fold 3 IBS: 0.1548456158925064
Fold 4 IBS: 0.22272321521005942
Fold 5 IBS: 0.23935683728303248
[I 2024-04-17 14:04:53,432] Trial 12 finished with value: 0.20177859255632447 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 12 with value: 0.20177859255632447.
Fold 1 IBS: 0.21393744117591726
Fold 2 IBS: 0.22155359094225296
Fold 3 IBS: 0.20446611923553368
Fold 4 IBS: 0.2246585074253488
Fold 5 IBS: 0.21811146661915368
[I 2024-04-17 14:04:54,258] Trial 13 finished with value: 0.21654542507964125 and parameters: {'l1_ratio': 0.0031985064812224406}. Best is trial 12 with value: 0.20177859255632447.
Fold 1 IBS: 0.21603232254065566
Fold 2 IBS: 0.1820959807088709
Fold 3 IBS: 0.16238146550950408
Fold 4 IBS: 0.2213677079774726
Fold 5 IBS: 0.243532392337011
[I 2024-04-17 14:04:56,210] Trial 14 finished with value: 0.20508197381470286 and parameters: {'l1_ratio': 0.14354731809284052}. Best is trial 12 with value: 0.20177859255632447.
Fold 1 IBS: 0.21617304332454848
Fold 2 IBS: 0.18220158436637002
Fold 3 IBS: 0.16255926952706493
Fold 4 IBS: 0.22132517505641738
Fold 5 IBS: 0.2436258431016821
[I 2024-04-17 14:04:58,194] Trial 15 finished with value: 0.20517698307521653 and parameters: {'l1_ratio': 0.14547377630010583}. Best is trial 12 with value: 0.20177859255632447.
Fold 1 IBS: 0.21231637063372336
Fold 2 IBS: 0.18164057533206407
Fold 3 IBS: 0.161525605118578
Fold 4 IBS: 0.2215654271709976
Fold 5 IBS: 0.24307095988188995
[I 2024-04-17 14:04:59,621] Trial 16 finished with value: 0.2040237876274506 and parameters: {'l1_ratio': 0.13463318817607284}. Best is trial 12 with value: 0.20177859255632447.
Fold 1 IBS: 0.22130704015817207
Fold 2 IBS: 0.19599521853993107
Fold 3 IBS: 0.17183053462831532
Fold 4 IBS: 0.24142516378110354
Fold 5 IBS: 0.24529753411365637
[I 2024-04-17 14:05:02,424] Trial 17 finished with value: 0.2151710982442357 and parameters: {'l1_ratio': 0.2906031874230555}. Best is trial 12 with value: 0.20177859255632447.
Fold 1 IBS: 0.21315564664732486
Fold 2 IBS: 0.17851912079796547
Fold 3 IBS: 0.1518224626657105
Fold 4 IBS: 0.22311785563045095
Fold 5 IBS: 0.23771901333939063
[I 2024-04-17 14:05:03,979] Trial 18 finished with value: 0.2008668198161685 and parameters: {'l1_ratio': 0.0668769468789637}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.2710370663024401
Fold 2 IBS: 0.4026735138445333
Fold 3 IBS: 0.2169098328868869
Fold 4 IBS: 0.35407038829490145
Fold 5 IBS: 0.28934324037393866
[I 2024-04-17 14:05:07,088] Trial 19 finished with value: 0.3068068083405401 and parameters: {'l1_ratio': 0.9929377968859474}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.2201647914879968
Fold 2 IBS: 0.18861802124841268
Fold 3 IBS: 0.1690733813041967
Fold 4 IBS: 0.23522840906954484
Fold 5 IBS: 0.2455738333546015
[I 2024-04-17 14:05:09,230] Trial 20 finished with value: 0.21173168729295053 and parameters: {'l1_ratio': 0.2388879688839749}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.2129319565663817
Fold 2 IBS: 0.17907369702739578
Fold 3 IBS: 0.1550548632255737
Fold 4 IBS: 0.2226940888727378
Fold 5 IBS: 0.23947210702622065
[I 2024-04-17 14:05:10,758] Trial 21 finished with value: 0.20184534254366193 and parameters: {'l1_ratio': 0.08499433228302328}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21309473032660628
Fold 2 IBS: 0.17859061442813107
Fold 3 IBS: 0.1527710770412278
Fold 4 IBS: 0.22300171840240904
Fold 5 IBS: 0.23820440063213308
[I 2024-04-17 14:05:12,199] Trial 22 finished with value: 0.20113250816610145 and parameters: {'l1_ratio': 0.07181511589086235}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21394752018271163
Fold 2 IBS: 0.22155984053473785
Fold 3 IBS: 0.20448410920226484
Fold 4 IBS: 0.22467899930368537
Fold 5 IBS: 0.21811477262492757
[I 2024-04-17 14:05:12,963] Trial 23 finished with value: 0.21655704836966544 and parameters: {'l1_ratio': 0.002373744016739676}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21917543621788252
Fold 2 IBS: 0.18595005298243208
Fold 3 IBS: 0.16697150894907292
Fold 4 IBS: 0.23122445726154786
Fold 5 IBS: 0.2451799072707026
[I 2024-04-17 14:05:15,985] Trial 24 finished with value: 0.2097002725363276 and parameters: {'l1_ratio': 0.20495632796046423}. Best is trial 18 with value: 0.2008668198161685.

Fold 1 IBS: 0.2221108936643162
Fold 2 IBS: 0.20885782840870798
Fold 3 IBS: 0.17639576636612675
Fold 4 IBS: 0.2528487413751459
Fold 5 IBS: 0.24504093281223158
[I 2024-04-17 14:05:18,187] Trial 25 finished with value: 0.2210508325253057 and parameters: {'l1_ratio': 0.3804525958179419}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.22184847487832438
Fold 2 IBS: 0.20142756420193844
Fold 3 IBS: 0.17402347225400805
Fold 4 IBS: 0.24644450737871842
Fold 5 IBS: 0.24508143306535538
[I 2024-04-17 14:05:20,212] Trial 26 finished with value: 0.21776509035566893 and parameters: {'l1_ratio': 0.3312072877416866}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21311137028824936
Fold 2 IBS: 0.17856484843900755
Fold 3 IBS: 0.1525270521037473
Fold 4 IBS: 0.22303338768090442
Fold 5 IBS: 0.23806978656509353
[I 2024-04-17 14:05:21,867] Trial 27 finished with value: 0.20106128901540044 and parameters: {'l1_ratio': 0.07046652721581821}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21844773475595716
Fold 2 IBS: 0.18444218627044073
Fold 3 IBS: 0.16557736274753285
Fold 4 IBS: 0.22864102398597672
Fold 5 IBS: 0.24483225516130377
[I 2024-04-17 14:05:24,054] Trial 28 finished with value: 0.20838811258424225 and parameters: {'l1_ratio': 0.1840952093317843}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.25066340493869116
Fold 2 IBS: 0.3174221248044298
Fold 3 IBS: 0.19816972599706975
Fold 4 IBS: 0.342738802492841
Fold 5 IBS: 0.25781481320802024
[I 2024-04-17 14:05:26,542] Trial 29 finished with value: 0.27336177428821035 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21291906935404045
Fold 2 IBS: 0.1791190115346229
Fold 3 IBS: 0.15522188573508042
Fold 4 IBS: 0.22266989983925514
Fold 5 IBS: 0.23960810776929167
[I 2024-04-17 14:05:28,355] Trial 30 finished with value: 0.2019075948464581 and parameters: {'l1_ratio': 0.08603677952870634}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21291899831738517
Fold 2 IBS: 0.17911927008472106
Fold 3 IBS: 0.15522280994767398
Fold 4 IBS: 0.22266976657241033
Fold 5 IBS: 0.2396086448189118
[I 2024-04-17 14:05:29,994] Trial 31 finished with value: 0.20190789794822045 and parameters: {'l1_ratio': 0.08604252528991772}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21331260426276627
Fold 2 IBS: 0.17846368872898274
Fold 3 IBS: 0.20337816599720163
Fold 4 IBS: 0.2234196569662346
Fold 5 IBS: 0.23651597053316226
[I 2024-04-17 14:05:31,593] Trial 32 finished with value: 0.2110180172976695 and parameters: {'l1_ratio': 0.05413792748818495}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.2205622355473379
Fold 2 IBS: 0.19118660022317355
Fold 3 IBS: 0.17007044840381522
Fold 4 IBS: 0.23733103473739742
Fold 5 IBS: 0.2455245604653374
[I 2024-04-17 14:05:34,208] Trial 33 finished with value: 0.2129349758754123 and parameters: {'l1_ratio': 0.2566838840408022}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21779094962027895
Fold 2 IBS: 0.1836613581532476
Fold 3 IBS: 0.16471308268452628
Fold 4 IBS: 0.227041878606904
Fold 5 IBS: 0.24455367763318844
[I 2024-04-17 14:05:36,464] Trial 34 finished with value: 0.20755218933962905 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.22179701896886528
Fold 2 IBS: 0.20008816420700645
Fold 3 IBS: 0.1734894263923368
Fold 4 IBS: 0.24517908859605195
Fold 5 IBS: 0.24517469123950064
[I 2024-04-17 14:05:38,590] Trial 35 finished with value: 0.21714567788075226 and parameters: {'l1_ratio': 0.32128045438633224}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.2279017074419827
Fold 2 IBS: 0.2543866463932655
Fold 3 IBS: 0.18515208177160694
Fold 4 IBS: 0.28823581968106154
Fold 5 IBS: 0.2440261329080437
[I 2024-04-17 14:05:40,655] Trial 36 finished with value: 0.2399404776391921 and parameters: {'l1_ratio': 0.6172315661000776}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21338795904340613
Fold 2 IBS: 0.22124115795820734
Fold 3 IBS: 0.2035065925484928
Fold 4 IBS: 0.22356587195301283
Fold 5 IBS: 0.23600499271048425
[I 2024-04-17 14:05:41,516] Trial 37 finished with value: 0.2195413148427207 and parameters: {'l1_ratio': 0.04801404782828531}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21240615199229343
Fold 2 IBS: 0.1812776878566297
Fold 3 IBS: 0.16077147404116307
Fold 4 IBS: 0.2217266770594019
Fold 5 IBS: 0.2426545786940871
[I 2024-04-17 14:05:42,932] Trial 38 finished with value: 0.203767313928715 and parameters: {'l1_ratio': 0.12741289352512636}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.2413452101214366
Fold 2 IBS: 0.3016752419623636
Fold 3 IBS: 0.19303627353885622
Fold 4 IBS: 0.32863433758383254
Fold 5 IBS: 0.2507175338789153
[I 2024-04-17 14:05:45,001] Trial 39 finished with value: 0.26308171941708086 and parameters: {'l1_ratio': 0.8205172079302314}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.22404461800890876
Fold 2 IBS: 0.2298860981924741
Fold 3 IBS: 0.18087477208002387
Fold 4 IBS: 0.26976512717667345
Fold 5 IBS: 0.24462580108205037
[I 2024-04-17 14:05:46,960] Trial 40 finished with value: 0.2298392833080261 and parameters: {'l1_ratio': 0.500826687812378}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21267151010544696
Fold 2 IBS: 0.18007364463031444
Fold 3 IBS: 0.15809879847874864
Fold 4 IBS: 0.2222099335543383
Fold 5 IBS: 0.24115713609671294
[I 2024-04-17 14:05:48,304] Trial 41 finished with value: 0.20284220457311225 and parameters: {'l1_ratio': 0.10603433048484937}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21326820814792824
Fold 2 IBS: 0.17845788560887857
Fold 3 IBS: 0.2033028519879679
Fold 4 IBS: 0.22333391523195667
Fold 5 IBS: 0.23684391237806512
[I 2024-04-17 14:05:49,406] Trial 42 finished with value: 0.2110413546709593 and parameters: {'l1_ratio': 0.05774346219526162}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21896078053419774
Fold 2 IBS: 0.1854947773866486
Fold 3 IBS: 0.16655486860858235
Fold 4 IBS: 0.23046754947486525
Fold 5 IBS: 0.24509606013409294
[I 2024-04-17 14:05:51,236] Trial 43 finished with value: 0.20931480722767737 and parameters: {'l1_ratio': 0.198736894847987}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21350684441899329
Fold 2 IBS: 0.22130424968273632
Fold 3 IBS: 0.20371073885002086
Fold 4 IBS: 0.22379831102796238
Fold 5 IBS: 0.21797472906379273
[I 2024-04-17 14:05:51,808] Trial 44 finished with value: 0.2160589746087011 and parameters: {'l1_ratio': 0.03834194526153677}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.22016608094972548
Fold 2 IBS: 0.18862896916382166
Fold 3 IBS: 0.1690764339617248
Fold 4 IBS: 0.2352351755112734
Fold 5 IBS: 0.24557412968257636
[I 2024-04-17 14:05:54,240] Trial 45 finished with value: 0.21173615785382432 and parameters: {'l1_ratio': 0.23894554600108853}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.2123720350895215
Fold 2 IBS: 0.18141595354738255
Fold 3 IBS: 0.16105991177743523
Fold 4 IBS: 0.2216652688437062
Fold 5 IBS: 0.24281556136353583
[I 2024-04-17 14:05:55,854] Trial 46 finished with value: 0.20386574612431624 and parameters: {'l1_ratio': 0.13015736427913677}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.2175196616030877
Fold 2 IBS: 0.1833595127613165
Fold 3 IBS: 0.1643216316529183
Fold 4 IBS: 0.22634718370109888
Fold 5 IBS: 0.24440990723027528
[I 2024-04-17 14:05:58,359] Trial 47 finished with value: 0.20719157938973934 and parameters: {'l1_ratio': 0.16677168223888103}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21362509257874715
Fold 2 IBS: 0.22136942542250884
Fold 3 IBS: 0.20391566735078337
Fold 4 IBS: 0.2240316584656222
Fold 5 IBS: 0.21801142480275917
[I 2024-04-17 14:05:59,369] Trial 48 finished with value: 0.21619065372408416 and parameters: {'l1_ratio': 0.02870863056222428}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.2211560275763035
Fold 2 IBS: 0.1946315812418001
Fold 3 IBS: 0.17136486380096252
Fold 4 IBS: 0.24027497044744414
Fold 5 IBS: 0.24534609532590004
[I 2024-04-17 14:06:01,378] Trial 49 finished with value: 0.2145547076784821 and parameters: {'l1_ratio': 0.2812514184757371}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21288381590174127

Fold 2 IBS: 0.17924877983428975
Fold 3 IBS: 0.15567707272771852
Fold 4 IBS: 0.2226038541672197
Fold 5 IBS: 0.2397992044615501
[I 2024-04-17 14:06:02,947] Trial 50 finished with value: 0.20204254541850383 and parameters: {'l1_ratio': 0.08888770157152942}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21291457138917422
Fold 2 IBS: 0.17913575834791912
Fold 3 IBS: 0.15528122977388406
Fold 4 IBS: 0.22266146298499728
Fold 5 IBS: 0.23963978155367013
[I 2024-04-17 14:06:04,364] Trial 51 finished with value: 0.20192656080992893 and parameters: {'l1_ratio': 0.08640058638065554}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21391337640728592
Fold 2 IBS: 0.22153873711066766
Fold 3 IBS: 0.20442321900503796
Fold 4 IBS: 0.22460963712975426
Fold 5 IBS: 0.21810359465534626
[I 2024-04-17 14:06:05,079] Trial 52 finished with value: 0.21651771286161842 and parameters: {'l1_ratio': 0.005167331735789121}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21248124198638288
Fold 2 IBS: 0.1809441107049435
Fold 3 IBS: 0.16005576477413258
Fold 4 IBS: 0.2218624121724541
Fold 5 IBS: 0.2422852764907414
[I 2024-04-17 14:06:06,998] Trial 53 finished with value: 0.2035257612257309 and parameters: {'l1_ratio': 0.12136911238264614}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.2132498778556957
Fold 2 IBS: 0.17846222676846352
Fold 3 IBS: 0.20327183166416016
Fold 4 IBS: 0.2232986008591792
Fold 5 IBS: 0.2369820702911338
[I 2024-04-17 14:06:08,555] Trial 54 finished with value: 0.21105292148772645 and parameters: {'l1_ratio': 0.0592315975439801}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21933971676941494
Fold 2 IBS: 0.18629088252212572
Fold 3 IBS: 0.16727681311724263
Fold 4 IBS: 0.231823020835789
Fold 5 IBS: 0.24524603750514107
[I 2024-04-17 14:06:10,544] Trial 55 finished with value: 0.2099952941499427 and parameters: {'l1_ratio': 0.20970200483263288}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21681359763108385
Fold 2 IBS: 0.182691018345185
Fold 3 IBS: 0.16336223013467824
Fold 4 IBS: 0.2247453870448566
Fold 5 IBS: 0.2440164374613718
[I 2024-04-17 14:06:12,323] Trial 56 finished with value: 0.2063257341234351 and parameters: {'l1_ratio': 0.1548493027013797}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.2128524842175768
Fold 2 IBS: 0.17937109224886033
Fold 3 IBS: 0.15606116705963377
Fold 4 IBS: 0.22254530826359195
Fold 5 IBS: 0.24000370237343205
[I 2024-04-17 14:06:13,590] Trial 57 finished with value: 0.20216675083261898 and parameters: {'l1_ratio': 0.09142057696060495}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21393155358673963
Fold 2 IBS: 0.22154994804335068
Fold 3 IBS: 0.20445561655733968
Fold 4 IBS: 0.22464654367500733
Fold 5 IBS: 0.21810953789921522
[I 2024-04-17 14:06:14,184] Trial 58 finished with value: 0.21653863995233052 and parameters: {'l1_ratio': 0.003680241884233326}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21757167281104353
Fold 2 IBS: 0.18340988971127498
Fold 3 IBS: 0.1643986941955976
Fold 4 IBS: 0.22648750154044597
Fold 5 IBS: 0.24443849377049748
[I 2024-04-17 14:06:17,043] Trial 59 finished with value: 0.2072612504057719 and parameters: {'l1_ratio': 0.16780279170674894}. Best is trial 18 with value: 0.2008668198161685.
Fold 1 IBS: 0.21320422527763
Fold 2 IBS: 0.17848371678143582
Fold 3 IBS: 0.1509958970112002
Fold 4 IBS: 0.22321086819156385
Fold 5 IBS: 0.2373339126309244
[I 2024-04-17 14:06:19,472] Trial 60 finished with value: 0.20064572397855085 and parameters: {'l1_ratio': 0.06293656423966822}. Best is trial 60 with value: 0.20064572397855085.
Fold 1 IBS: 0.21326816051917621
Fold 2 IBS: 0.1784578899468205
Fold 3 IBS: 0.2033027713289076
Fold 4 IBS: 0.22333382340679941
Fold 5 IBS: 0.2368442597524319
[I 2024-04-17 14:06:20,796] Trial 61 finished with value: 0.21104138099082714 and parameters: {'l1_ratio': 0.057747329303917946}. Best is trial 60 with value: 0.20064572397855085.
Fold 1 IBS: 0.212388865655838
Fold 2 IBS: 0.1813452050020976
Fold 3 IBS: 0.16091921727748376
Fold 4 IBS: 0.22169554231611166
Fold 5 IBS: 0.24273642542674917
[I 2024-04-17 14:06:22,165] Trial 62 finished with value: 0.203817051135656 and parameters: {'l1_ratio': 0.1288035774956832}. Best is trial 60 with value: 0.20064572397855085.
Fold 1 IBS: 0.2135927868242579
Fold 2 IBS: 0.2213513763273778
Fold 3 IBS: 0.20385949333815853
Fold 4 IBS: 0.2239676927699918
Fold 5 IBS: 0.21800133751870943
[I 2024-04-17 14:06:22,869] Trial 63 finished with value: 0.2161545373556991 and parameters: {'l1_ratio': 0.031341784934853144}. Best is trial 60 with value: 0.20064572397855085.
Fold 1 IBS: 0.21312332563208244
Fold 2 IBS: 0.17854978718227474
Fold 3 IBS: 0.15235211612530092
Fold 4 IBS: 0.22305616660902167
Fold 5 IBS: 0.23797739605224139
[I 2024-04-17 14:06:24,151] Trial 64 finished with value: 0.2010117583201842 and parameters: {'l1_ratio': 0.06949745299223785}. Best is trial 60 with value: 0.20064572397855085.
Fold 1 IBS: 0.2126530852398332
Fold 2 IBS: 0.18014846233943388
Fold 3 IBS: 0.15830619509632318
Fold 4 IBS: 0.22217605449263395
Fold 5 IBS: 0.24126720120438155
[I 2024-04-17 14:06:25,707] Trial 65 finished with value: 0.20291019967452115 and parameters: {'l1_ratio': 0.10752060338581235}. Best is trial 60 with value: 0.20064572397855085.
Fold 1 IBS: 0.21322310797004118
Fold 2 IBS: 0.17847344701960138
Fold 3 IBS: 0.15066906040554107
Fold 4 IBS: 0.22324711796345564
Fold 5 IBS: 0.23718674945240215
[I 2024-04-17 14:06:26,984] Trial 66 finished with value: 0.20055989656220827 and parameters: {'l1_ratio': 0.061404353232731274}. Best is trial 66 with value: 0.20055989656220827.
Fold 1 IBS: 0.21322321379721054
Fold 2 IBS: 0.17847340107725734
Fold 3 IBS: 0.15066725070452952
Fold 4 IBS: 0.22324732127445093
Fold 5 IBS: 0.23718593210284838
[I 2024-04-17 14:06:28,296] Trial 67 finished with value: 0.20055942379125935 and parameters: {'l1_ratio': 0.06139576512612678}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21359832688372174
Fold 2 IBS: 0.22135445849051635
Fold 3 IBS: 0.20386911651453757
Fold 4 IBS: 0.22397865065696132
Fold 5 IBS: 0.21800306403268466
[I 2024-04-17 14:06:28,933] Trial 68 finished with value: 0.2161607233156843 and parameters: {'l1_ratio': 0.030890299618081655}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21315902568839687
Fold 2 IBS: 0.17851583093556594
Fold 3 IBS: 0.1517651959109836
Fold 4 IBS: 0.22312431399049368
Fold 5 IBS: 0.23769169328924936
[I 2024-04-17 14:06:30,450] Trial 69 finished with value: 0.2008512119629379 and parameters: {'l1_ratio': 0.06660292916212401}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.2196183098044082
Fold 2 IBS: 0.1870628715604574
Fold 3 IBS: 0.16794309653287717
Fold 4 IBS: 0.23305632761939007
Fold 5 IBS: 0.24538123846337712
[I 2024-04-17 14:06:32,512] Trial 70 finished with value: 0.21061236879610198 and parameters: {'l1_ratio': 0.22052672364775155}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21304341983575212
Fold 2 IBS: 0.1787223217899053
Fold 3 IBS: 0.15351783506585148
Fold 4 IBS: 0.22290432289521236
Fold 5 IBS: 0.23862239569404045
[I 2024-04-17 14:06:33,931] Trial 71 finished with value: 0.20136205905615237 and parameters: {'l1_ratio': 0.07597204675116165}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.2160961465388752
Fold 2 IBS: 0.18214748357240507
Fold 3 IBS: 0.16246222323230824
Fold 4 IBS: 0.22134783092149465
Fold 5 IBS: 0.24357684931221296
[I 2024-04-17 14:06:35,458] Trial 72 finished with value: 0.20512610671545922 and parameters: {'l1_ratio': 0.14444722286364392}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21317749798855237
Fold 2 IBS: 0.1785015942493445
Fold 3 IBS: 0.15145173217674743
Fold 4 IBS: 0.22315965026274687
Fold 5 IBS: 0.23754390247275517
[I 2024-04-17 14:06:36,761] Trial 73 finished with value: 0.20076687543002927 and parameters: {'l1_ratio': 0.06510476886297618}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21366524955204116
Fold 2 IBS: 0.221392118036643
Fold 3 IBS: 0.20398569008250478
Fold 4 IBS: 0.22411139538284872
Fold 5 IBS: 0.21802402953589606
[I 2024-04-17 14:06:37,386] Trial 74 finished with value: 0.21623569651798674 and parameters: {'l1_ratio': 0.025434169209416865}. Best is trial 67 with value: 0.20055942379125935.

Fold 1 IBS: 0.21259655700787974
Fold 2 IBS: 0.18039944493647472
Fold 3 IBS: 0.1589252310578863
Fold 4 IBS: 0.222072416000144
Fold 5 IBS: 0.241661207289443
[I 2024-04-17 14:06:38,818] Trial 75 finished with value: 0.20313097125836554 and parameters: {'l1_ratio': 0.11207878786036493}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.22873164551885083
Fold 2 IBS: 0.25827504276603214
Fold 3 IBS: 0.18576751518696263
Fold 4 IBS: 0.29089203152617116
Fold 5 IBS: 0.24404412926480487
[I 2024-04-17 14:06:40,727] Trial 76 finished with value: 0.2415420728525643 and parameters: {'l1_ratio': 0.6334118819748745}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21881866142814044
Fold 2 IBS: 0.18509685664403197
Fold 3 IBS: 0.1661913004537431
Fold 4 IBS: 0.22979234244317298
Fold 5 IBS: 0.245004247042372
[I 2024-04-17 14:06:42,475] Trial 77 finished with value: 0.20898068160229205 and parameters: {'l1_ratio': 0.19328346899350535}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21397379871655176
Fold 2 IBS: 0.22157621387433188
Fold 3 IBS: 0.20453107516266142
Fold 4 IBS: 0.22473249248730018
Fold 5 IBS: 0.2181234173277182
[I 2024-04-17 14:06:43,127] Trial 78 finished with value: 0.2165873995137127 and parameters: {'l1_ratio': 0.000222925957880378}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.2131569274760627
Fold 2 IBS: 0.1785172296288421
Fold 3 IBS: 0.1518008137576641
Fold 4 IBS: 0.223120303477209
Fold 5 IBS: 0.23770886619745266
[I 2024-04-17 14:06:44,333] Trial 79 finished with value: 0.20086082810744613 and parameters: {'l1_ratio': 0.06677308139858411}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21342721748614316
Fold 2 IBS: 0.2212617254274244
Fold 3 IBS: 0.2035737979831843
Fold 4 IBS: 0.2236423893192769
Fold 5 IBS: 0.23578369794013027
[I 2024-04-17 14:06:45,386] Trial 80 finished with value: 0.21953776563123178 and parameters: {'l1_ratio': 0.04482155998263057}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21316276247404545
Fold 2 IBS: 0.17851316866887432
Fold 3 IBS: 0.15170235918980302
Fold 4 IBS: 0.22313145809439658
Fold 5 IBS: 0.23766159200884612
[I 2024-04-17 14:06:46,792] Trial 81 finished with value: 0.20083426808719312 and parameters: {'l1_ratio': 0.06629988890455243}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.2126800740778418
Fold 2 IBS: 0.18003778384606195
Fold 3 IBS: 0.15800110811754128
Fold 4 IBS: 0.22222569732763972
Fold 5 IBS: 0.24110698556173998
[I 2024-04-17 14:06:48,161] Trial 82 finished with value: 0.20281032978616498 and parameters: {'l1_ratio': 0.1053434067700839}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21315924235154216
Fold 2 IBS: 0.17851566052218618
Fold 3 IBS: 0.1517615343582603
Fold 4 IBS: 0.22312472815689283
Fold 5 IBS: 0.23768995376444235
[I 2024-04-17 14:06:49,405] Trial 83 finished with value: 0.20085022383066478 and parameters: {'l1_ratio': 0.06658535887783114}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.22343862435154385
Fold 2 IBS: 0.2209574836202106
Fold 3 IBS: 0.1794171617110954
Fold 4 IBS: 0.2627203687096123
Fold 5 IBS: 0.24489679554074012
[I 2024-04-17 14:06:51,275] Trial 84 finished with value: 0.22628608678664044 and parameters: {'l1_ratio': 0.4519551909198334}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21636044914067834
Fold 2 IBS: 0.18235079096066326
Fold 3 IBS: 0.1627989901628386
Fold 4 IBS: 0.22126584402505664
Fold 5 IBS: 0.24374801423357093
[I 2024-04-17 14:06:52,784] Trial 85 finished with value: 0.20530481770456155 and parameters: {'l1_ratio': 0.14816637238539104}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.2136166883950133
Fold 2 IBS: 0.22136471234608174
Fold 3 IBS: 0.20390104038848716
Fold 4 IBS: 0.22401500254081996
Fold 5 IBS: 0.2180087961155602
[I 2024-04-17 14:06:53,414] Trial 86 finished with value: 0.21618124795719246 and parameters: {'l1_ratio': 0.029393727526044834}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21324927245917927
Fold 2 IBS: 0.17846219671903268
Fold 3 IBS: 0.20327080790258534
Fold 4 IBS: 0.22329743539079078
Fold 5 IBS: 0.23698667533161966
[I 2024-04-17 14:06:54,512] Trial 87 finished with value: 0.21105327756064157 and parameters: {'l1_ratio': 0.05928074118047624}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21264990197196965
Fold 2 IBS: 0.1801647703835533
Fold 3 IBS: 0.15834204784556283
Fold 4 IBS: 0.2221702061396011
Fold 5 IBS: 0.24134197536721713
[I 2024-04-17 14:06:55,901] Trial 88 finished with value: 0.20293378034158077 and parameters: {'l1_ratio': 0.10777735840905577}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.2179545724388578
Fold 2 IBS: 0.18381171478211178
Fold 3 IBS: 0.16492987233897197
Fold 4 IBS: 0.22745152215388198
Fold 5 IBS: 0.24463266949835824
[I 2024-04-17 14:06:57,946] Trial 89 finished with value: 0.20775607024243636 and parameters: {'l1_ratio': 0.17500504138198647}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.2137104919401524
Fold 2 IBS: 0.22141725893723155
Fold 3 IBS: 0.2040644819320662
Fold 4 IBS: 0.22420076644947398
Fold 5 IBS: 0.21803841274582553
[I 2024-04-17 14:06:58,564] Trial 90 finished with value: 0.21628628240094994 and parameters: {'l1_ratio': 0.021744450528692623}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21314771646882436
Fold 2 IBS: 0.17852777210295465
Fold 3 IBS: 0.1519583405547345
Fold 4 IBS: 0.22310270538133525
Fold 5 IBS: 0.23778264920161854
[I 2024-04-17 14:06:59,950] Trial 91 finished with value: 0.20090383674189347 and parameters: {'l1_ratio': 0.0675199916123736}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.2130264423261163
Fold 2 IBS: 0.17876858618774902
Fold 3 IBS: 0.15376080963201502
Fold 4 IBS: 0.2228721827790508
Fold 5 IBS: 0.23876333896390106
[I 2024-04-17 14:07:01,306] Trial 92 finished with value: 0.20143827197776645 and parameters: {'l1_ratio': 0.07734697426284909}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21340277300833616
Fold 2 IBS: 0.22124888828203926
Fold 3 IBS: 0.20353192814819707
Fold 4 IBS: 0.22359471777899492
Fold 5 IBS: 0.2359182866206741
[I 2024-04-17 14:07:02,102] Trial 93 finished with value: 0.2195393187676483 and parameters: {'l1_ratio': 0.04680954592634572}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.2399443893350763
Fold 2 IBS: 0.2971650494657127
Fold 3 IBS: 0.19192987549192025
Fold 4 IBS: 0.3248073802523104
Fold 5 IBS: 0.24946679457477972
[I 2024-04-17 14:07:04,158] Trial 94 finished with value: 0.26066269782395984 and parameters: {'l1_ratio': 0.8032167564300166}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21243946624681576
Fold 2 IBS: 0.18114674839717246
Fold 3 IBS: 0.1604298652562691
Fold 4 IBS: 0.22178679872282575
Fold 5 IBS: 0.24249198715730028
[I 2024-04-17 14:07:05,539] Trial 95 finished with value: 0.20365897315607667 and parameters: {'l1_ratio': 0.1247320863293277}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21285614722155644
Fold 2 IBS: 0.1793584287694947
Fold 3 IBS: 0.15601660220860303
Fold 4 IBS: 0.22255214549921334
Fold 5 IBS: 0.23997963128871252
[I 2024-04-17 14:07:06,856] Trial 96 finished with value: 0.202152590997516 and parameters: {'l1_ratio': 0.09112450054935031}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21600900540200474
Fold 2 IBS: 0.1820786421345026
Fold 3 IBS: 0.16234974188260967
Fold 4 IBS: 0.2213751806300156
Fold 5 IBS: 0.24351603447641942
[I 2024-04-17 14:07:08,402] Trial 97 finished with value: 0.2050657209051104 and parameters: {'l1_ratio': 0.1432091829571755}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.22481215171730473
Fold 2 IBS: 0.2364713094239816
Fold 3 IBS: 0.18181376412507486
Fold 4 IBS: 0.2749243307488906
Fold 5 IBS: 0.24437674617866936
[I 2024-04-17 14:07:10,389] Trial 98 finished with value: 0.23247966043878426 and parameters: {'l1_ratio': 0.5347630317469527}. Best is trial 67 with value: 0.20055942379125935.
Fold 1 IBS: 0.21322861566098025
Fold 2 IBS: 0.17847169861756956
Fold 3 IBS: 0.15057499169301836
Fold 4 IBS: 0.22325770135734585

Fold 5 IBS: 0.23714440999389041
[I 2024-04-17 14:07:11,573] Trial 99 finished with value: 0.20053548346456088 and parameters: {'l1_ratio': 0.06095737868847135}. Best is trial 99 with value: 0.20053548346456088.


* Best trial for IBS:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.20053548346456088], datetime_start=datetime.datetime(2024, 4, 17, 14, 7, 10, 394598), datetime_complete=datetime.datetime(2024, 4, 17, 14, 7, 11, 572989), params={'l1_ratio': 0.06095737868847135}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=99, value=None)


* Best Score for IBS:
 0.20053548346456088

In [46]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [47]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.752
train_ibs:  0.201

#### Test

In [48]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [49]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.059820186386939866)

test_cindex : 0.593

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.06095737868847135)

test_ibs:  0.22

In [50]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [51]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 14:07:11,900] A new study created in memory with name: no-name-1c356d48-dc03-44cc-8704-726c3f1e99f5

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 14:08:09,057] Trial 0 finished with value: 0.7366032203169602 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 14:08:18,254] Trial 1 finished with value: 0.7181620567966567 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 14:08:28,455] Trial 2 finished with value: 0.7150860129299454 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:08:30,590] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:08:33,571] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7276995305164319
[I 2024-04-17 14:08:51,725] Trial 5 finished with value: 0.7100749491193421 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 14:09:45,400] Trial 6 finished with value: 0.727952663180055 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:09:49,631] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6056338028169014
[I 2024-04-17 14:10:03,068] Trial 8 finished with value: 0.5211267605633803 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:10:13,833] Trial 9 finished with value: 0.7080431320407382 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:10:14,780] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 14:10:47,681] Trial 11 finished with value: 0.7380484783177279 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.4182289452010553, 'max_features': None, 'min_weight_fraction_leaf': 0.14354804402122565, 'warm_start': False}. Best is trial 11 with value: 0.7380484783177279.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7136150234741784
[I 2024-04-17 14:11:36,080] Trial 12 finished with value: 0.7438602547617209 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.4617373338142137, 'max_features': None, 'min_weight_fraction_leaf': 0.1776774219107311, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7136150234741784
[I 2024-04-17 14:12:06,603] Trial 13 finished with value: 0.7433165908059199 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 490, 'oob_score': True, 'max_samples': 0.430322282186733, 'max_features': None, 'min_weight_fraction_leaf': 0.1716937452680298, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:12:12,809] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 485, 'oob_score': True, 'max_samples': 0.4652312819220314, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3866899818434614, 'warm_start': True}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:12:26,807] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 491, 'oob_score': True, 'max_samples': 0.27229846028530913, 'max_features': None, 'min_weight_fraction_leaf': 0.20648604556011108, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.

Fold 1 C-index: 0.6038961038961039
Fold 2 C-index: 0.7165178571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6032863849765259
[I 2024-04-17 14:12:31,262] Trial 16 finished with value: 0.6633327721070438 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.36871324569404207, 'max_features': None, 'min_weight_fraction_leaf': 0.1048543527585735, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:12:43,400] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.1424705672746025, 'max_features': None, 'min_weight_fraction_leaf': 0.20205510510599584, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 14:12:50,011] Trial 18 finished with value: 0.7335541813688149 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 492, 'oob_score': True, 'max_samples': 0.5392320730567087, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07958856082174798, 'warm_start': True}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.6645021645021645
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.6740196078431373
Fold 4 C-index: 0.6772151898734177
Fold 5 C-index: 0.5892018779342723
[I 2024-04-17 14:12:50,865] Trial 19 finished with value: 0.6638449108877411 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.5137509360533721, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16593096906146954, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:13:03,450] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 436, 'oob_score': True, 'max_samples': 0.8114307622571267, 'max_features': None, 'min_weight_fraction_leaf': 0.41597694280469266, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7136150234741784
[I 2024-04-17 14:13:34,761] Trial 21 finished with value: 0.7398700280611442 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 392, 'oob_score': True, 'max_samples': 0.3990347915810166, 'max_features': None, 'min_weight_fraction_leaf': 0.14443114491291786, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:13:47,100] Trial 22 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 18, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.21351240485158024, 'max_features': None, 'min_weight_fraction_leaf': 0.2441929681165364, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 14:14:12,662] Trial 23 finished with value: 0.7271164711934142 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.3756805451824067, 'max_features': None, 'min_weight_fraction_leaf': 0.13775089899883528, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:14:28,716] Trial 24 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.36406078817327137, 'max_features': None, 'min_weight_fraction_leaf': 0.1822392883483817, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:14:40,991] Trial 25 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.4837577457111593, 'max_features': None, 'min_weight_fraction_leaf': 0.27111099648458864, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7981220657276995
[I 2024-04-17 14:14:48,251] Trial 26 finished with value: 0.7952997362091728 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 17, 'n_estimators': 320, 'oob_score': True, 'max_samples': 0.425133711322363, 'max_features': None, 'min_weight_fraction_leaf': 0.07929595127017089, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.7370892018779343
[I 2024-04-17 14:14:53,182] Trial 27 finished with value: 0.7439785302441695 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 17, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.5634050049825258, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07348058796691775, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 14:14:56,761] Trial 28 finished with value: 0.7606780234987396 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 221, 'oob_score': True, 'max_samples': 0.5671295227568508, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002810616935067567, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7981220657276995
[I 2024-04-17 14:15:00,643] Trial 29 finished with value: 0.7861497989039858 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 222, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06647154253337151, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7981220657276995
[I 2024-04-17 14:15:04,098] Trial 30 finished with value: 0.7826158421682422 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 215, 'oob_score': True, 'max_samples': 0.670660906330469, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008496584402552174, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8571428571428571

Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.812206572769953
[I 2024-04-17 14:15:07,004] Trial 31 finished with value: 0.7936613975238874 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 215, 'oob_score': True, 'max_samples': 0.7258118850709611, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.020186907613437947, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.8169014084507042
[I 2024-04-17 14:15:09,148] Trial 32 finished with value: 0.7892741864327053 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 149, 'oob_score': True, 'max_samples': 0.7060378252364139, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04618667534698639, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8403755868544601
[I 2024-04-17 14:15:11,229] Trial 33 finished with value: 0.8006493236932368 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 155, 'oob_score': True, 'max_samples': 0.7605972338377621, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.046274896708941554, 'warm_start': True}. Best is trial 33 with value: 0.8006493236932368.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8450704225352113
[I 2024-04-17 14:15:13,838] Trial 34 finished with value: 0.7998566890977854 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 151, 'oob_score': True, 'max_samples': 0.7633408434752601, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04380970481841874, 'warm_start': True}. Best is trial 33 with value: 0.8006493236932368.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8356807511737089
[I 2024-04-17 14:15:15,182] Trial 35 finished with value: 0.803331848306836 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.7948212261000067, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10423395463781872, 'warm_start': True}. Best is trial 35 with value: 0.803331848306836.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8497652582159625
[I 2024-04-17 14:15:16,310] Trial 36 finished with value: 0.81388019672447 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.8091332552149437, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10837446978579603, 'warm_start': True}. Best is trial 36 with value: 0.81388019672447.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8403755868544601
[I 2024-04-17 14:15:17,301] Trial 37 finished with value: 0.8138484554748331 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 101, 'oob_score': False, 'max_samples': 0.8220720793755758, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09608472875949194, 'warm_start': True}. Best is trial 36 with value: 0.81388019672447.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8075117370892019
[I 2024-04-17 14:15:18,225] Trial 38 finished with value: 0.794834129497761 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.8537902740382926, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09525205057743304, 'warm_start': True}. Best is trial 36 with value: 0.81388019672447.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.863849765258216
[I 2024-04-17 14:15:19,239] Trial 39 finished with value: 0.8134528027162501 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.9833072699349469, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10393928454601242, 'warm_start': True}. Best is trial 36 with value: 0.81388019672447.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8591549295774648
[I 2024-04-17 14:15:20,564] Trial 40 finished with value: 0.8193359257510359 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 79, 'oob_score': False, 'max_samples': 0.9974049101283982, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11156682941225779, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.8309859154929577
[I 2024-04-17 14:15:21,635] Trial 41 finished with value: 0.8034774490599819 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.9999220055692117, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12045420312726329, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8450704225352113
[I 2024-04-17 14:15:22,719] Trial 42 finished with value: 0.809391720026152 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.9881165529835445, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12443985149382927, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.8685446009389671
[I 2024-04-17 14:15:23,531] Trial 43 finished with value: 0.8118099200814217 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 42, 'oob_score': False, 'max_samples': 0.9912995656748597, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12253835631192889, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8013392857142857
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7535211267605634
[I 2024-04-17 14:15:24,073] Trial 44 finished with value: 0.7512725179741098 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 13, 'oob_score': False, 'max_samples': 0.9192360586272437, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09432875921172784, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.8169014084507042
[I 2024-04-17 14:15:24,826] Trial 45 finished with value: 0.7805310602984772 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 35, 'oob_score': False, 'max_samples': 0.8671059553512112, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22329822046282632, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.

Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 14:15:26,250] Trial 46 finished with value: 0.7374183107739604 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 123, 'oob_score': False, 'max_samples': 0.9536184653009308, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1531269560181571, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8873239436619719
[I 2024-04-17 14:15:27,181] Trial 47 finished with value: 0.821440909099989 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 45, 'oob_score': False, 'max_samples': 0.8733003039936599, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12467981297687225, 'warm_start': True}. Best is trial 47 with value: 0.821440909099989.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8873239436619719
[I 2024-04-17 14:15:28,591] Trial 48 finished with value: 0.8304915258944628 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.8813820217761629, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06296378903734845, 'warm_start': True}. Best is trial 48 with value: 0.8304915258944628.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 14:15:30,223] Trial 49 finished with value: 0.8329500051937337 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 106, 'oob_score': False, 'max_samples': 0.8805367238926652, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.057195379787481515, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 14:15:31,657] Trial 50 finished with value: 0.8314528643350888 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.9009010945275224, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.054961351160765004, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 14:15:33,735] Trial 51 finished with value: 0.8313163540347663 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 183, 'oob_score': False, 'max_samples': 0.8934638023278324, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03450702765653768, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8779342723004695
[I 2024-04-17 14:15:35,799] Trial 52 finished with value: 0.8320214536162119 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 180, 'oob_score': False, 'max_samples': 0.8797580746407682, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.024666679991640003, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 14:15:37,575] Trial 53 finished with value: 0.829623312030853 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 118, 'oob_score': False, 'max_samples': 0.8886913182351664, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.038639798107064416, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8873239436619719
[I 2024-04-17 14:15:40,100] Trial 54 finished with value: 0.8269793471449424 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 178, 'oob_score': False, 'max_samples': 0.8943965597615428, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02658068365989562, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8873239436619719
[I 2024-04-17 14:15:41,668] Trial 55 finished with value: 0.8314821925869167 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 126, 'oob_score': False, 'max_samples': 0.9394960211783968, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03414063784444427, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8779342723004695
[I 2024-04-17 14:15:44,331] Trial 56 finished with value: 0.8291458931503687 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 249, 'oob_score': False, 'max_samples': 0.9464163990983746, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05957529961744705, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8967136150234741
[I 2024-04-17 14:15:46,583] Trial 57 finished with value: 0.837497279418745 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.8375194335284916, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.028965413024752612, 'warm_start': True}. Best is trial 57 with value: 0.837497279418745.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8732394366197183
[I 2024-04-17 14:15:48,924] Trial 58 finished with value: 0.8257460337171384 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 195, 'oob_score': False, 'max_samples': 0.8473410457317984, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023049662318096596, 'warm_start': True}. Best is trial 57 with value: 0.837497279418745.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 14:15:51,542] Trial 59 finished with value: 0.8490112951451346 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 186, 'oob_score': False, 'max_samples': 0.9190157687794943, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.013504221373780535, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 14:15:54,776] Trial 60 finished with value: 0.8462284069610924 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 259, 'oob_score': False, 'max_samples': 0.9302291542086784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0020986391606638635, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.

Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9248826291079812
[I 2024-04-17 14:15:58,034] Trial 61 finished with value: 0.8471575518568665 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 243, 'oob_score': False, 'max_samples': 0.9319335934099356, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0028492650677599558, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9154929577464789
[I 2024-04-17 14:16:01,725] Trial 62 finished with value: 0.8424040571187227 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 251, 'oob_score': False, 'max_samples': 0.9488273152669577, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.006993125885435061, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9248826291079812
[I 2024-04-17 14:16:05,508] Trial 63 finished with value: 0.8459918151364014 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 275, 'oob_score': False, 'max_samples': 0.9558680489418835, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00656722209863304, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9342723004694836
[I 2024-04-17 14:16:09,795] Trial 64 finished with value: 0.8560377835959099 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.9511852166403515, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.006787286025552868, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9342723004694836
[I 2024-04-17 14:16:13,801] Trial 65 finished with value: 0.8543281008735688 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.959702372838177, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0021045537516321865, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9436619718309859
[I 2024-04-17 14:16:18,243] Trial 66 finished with value: 0.846986714506221 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.9606657832305625, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009645713200115154, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 14:16:22,651] Trial 67 finished with value: 0.8422965637980504 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 282, 'oob_score': False, 'max_samples': 0.9696946680213249, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0015463863160716843, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9389671361502347
[I 2024-04-17 14:16:27,884] Trial 68 finished with value: 0.8400810425063071 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 305, 'oob_score': False, 'max_samples': 0.9226346461200242, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.013757163062800108, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:16:30,519] Trial 69 finished with value: 0.735120849138696 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.9207461742012929, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3619470610261025, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 14:16:32,993] Trial 70 finished with value: 0.7199549229649882 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 280, 'oob_score': False, 'max_samples': 0.9621462391123464, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4708820505432424, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9248826291079812
[I 2024-04-17 14:16:36,818] Trial 71 finished with value: 0.8477117723943335 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 248, 'oob_score': False, 'max_samples': 0.95365805085536, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.006547106868712814, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9248826291079812
[I 2024-04-17 14:16:41,369] Trial 72 finished with value: 0.8468137779836808 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.9218265096398339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.002129212342459046, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9014084507042254
[I 2024-04-17 14:16:45,595] Trial 73 finished with value: 0.8355677775332243 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.7855691032277902, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.015061828643737101, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9061032863849765
[I 2024-04-17 14:16:48,448] Trial 74 finished with value: 0.8441728577198884 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9254876714681857, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0812631651455817, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 14:16:52,844] Trial 75 finished with value: 0.8362371866524855 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.9681737785400921, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0015964899054660966, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.

Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.92018779342723
[I 2024-04-17 14:16:56,603] Trial 76 finished with value: 0.84313576068201 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.8305113746650353, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0426275461746545, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9389671361502347
[I 2024-04-17 14:17:00,552] Trial 77 finished with value: 0.8568403814547748 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.9144336511700586, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01595057842588041, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9061032863849765
[I 2024-04-17 14:17:04,175] Trial 78 finished with value: 0.8419192289956712 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9116776901842412, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07343560570014901, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 14:17:08,042] Trial 79 finished with value: 0.8328178212078037 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 203, 'oob_score': False, 'max_samples': 0.8605744759700164, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023396832105227285, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 14:17:10,675] Trial 80 finished with value: 0.7687749931412297 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.969349688986363, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2986900237576432, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9342723004694836
[I 2024-04-17 14:17:14,318] Trial 81 finished with value: 0.8508482566919376 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.9412070505938585, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01576257355000931, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.92018779342723
[I 2024-04-17 14:17:18,575] Trial 82 finished with value: 0.8416282042647364 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 292, 'oob_score': False, 'max_samples': 0.9068065686971891, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.016797956013047826, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8732394366197183
[I 2024-04-17 14:17:21,774] Trial 83 finished with value: 0.8318825303180803 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 334, 'oob_score': False, 'max_samples': 0.6153744430709406, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04832190639289941, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9248826291079812
[I 2024-04-17 14:17:25,329] Trial 84 finished with value: 0.8433724935297382 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.9399975078027157, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0345364942691951, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9107981220657277
[I 2024-04-17 14:17:28,778] Trial 85 finished with value: 0.8358557576420413 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9737845589861637, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01634294636489071, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9107981220657277
[I 2024-04-17 14:17:33,189] Trial 86 finished with value: 0.8377019506647049 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.8518058828861286, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05107482426381401, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 14:17:47,709] Trial 87 finished with value: 0.7178329643580474 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 291, 'oob_score': False, 'max_samples': 0.9965938454935799, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.034448975293513207, 'warm_start': False}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9154929577464789
[I 2024-04-17 14:17:52,534] Trial 88 finished with value: 0.8457089722953801 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 335, 'oob_score': False, 'max_samples': 0.9085692767397662, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0697346803584661, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.92018779342723
[I 2024-04-17 14:17:58,300] Trial 89 finished with value: 0.836101128647378 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 375, 'oob_score': False, 'max_samples': 0.7981108690303841, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012687139847991694, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9389671361502347
[I 2024-04-17 14:18:01,469] Trial 90 finished with value: 0.858196741029675 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 233, 'oob_score': False, 'max_samples': 0.9399104719362167, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04454154696608814, 'warm_start': True}. Best is trial 90 with value: 0.858196741029675.

Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9389671361502347
[I 2024-04-17 14:18:04,353] Trial 91 finished with value: 0.8594063157686616 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 228, 'oob_score': False, 'max_samples': 0.9393175331158453, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0004448382541777079, 'warm_start': True}. Best is trial 91 with value: 0.8594063157686616.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 14:18:07,203] Trial 92 finished with value: 0.8504093975391417 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 236, 'oob_score': False, 'max_samples': 0.9511651006370562, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023794967159176263, 'warm_start': True}. Best is trial 91 with value: 0.8594063157686616.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9342723004694836
[I 2024-04-17 14:18:10,217] Trial 93 finished with value: 0.8507722251285642 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 232, 'oob_score': False, 'max_samples': 0.9393138993988948, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04166845875792434, 'warm_start': True}. Best is trial 91 with value: 0.8594063157686616.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9342723004694836
[I 2024-04-17 14:18:13,312] Trial 94 finished with value: 0.864047670519609 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 230, 'oob_score': False, 'max_samples': 0.9847467855272036, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04749646122417352, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9107981220657277
[I 2024-04-17 14:18:16,005] Trial 95 finished with value: 0.8462994805857642 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 226, 'oob_score': False, 'max_samples': 0.9851260930666599, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0877741788827067, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9154929577464789
[I 2024-04-17 14:18:18,294] Trial 96 finished with value: 0.8456767787505284 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 203, 'oob_score': False, 'max_samples': 0.9046678790431277, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05908913791760474, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.8169014084507042
[I 2024-04-17 14:18:20,030] Trial 97 finished with value: 0.7824887018130806 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.9994611759628653, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04096131539525037, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 14:18:32,238] Trial 98 finished with value: 0.7022847020297285 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 210, 'oob_score': False, 'max_samples': 0.9435261125804136, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.025743264975163525, 'warm_start': False}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9240506329113924

[I 2024-04-17 14:18:34,369] A new study created in memory with name: no-name-da2286b9-d6ae-4737-8635-852d42543ac6

Fold 5 C-index: 0.9061032863849765
[I 2024-04-17 14:18:34,332] Trial 99 finished with value: 0.8374434398307532 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.8689674666549045, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04663818112580286, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.864047670519609], datetime_start=datetime.datetime(2024, 4, 17, 14, 18, 10, 223885), datetime_complete=datetime.datetime(2024, 4, 17, 14, 18, 13, 312024), params={'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 230, 'oob_score': False, 'max_samples': 0.9847467855272036, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04749646122417352, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=94, value=None)


* Best Score for C-index:
 0.864047670519609

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.18324615167630967
Fold 2 IBS: 0.1973414798718171
Fold 3 IBS: 0.16795049053724004
Fold 4 IBS: 0.18912813741469703
Fold 5 IBS: 0.2061164871654968
[I 2024-04-17 14:19:26,894] Trial 0 finished with value: 0.18875654933311214 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20345329363741022
Fold 2 IBS: 0.1866704968763983
Fold 3 IBS: 0.18211060269283327
Fold 4 IBS: 0.18446935355917493
Fold 5 IBS: 0.20613420199922336
[I 2024-04-17 14:19:29,394] Trial 1 finished with value: 0.19256758975300803 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-17 14:19:30,897] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-17 14:19:36,592] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-17 14:19:40,457] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20630791540283333
Fold 2 IBS: 0.18077183063689325
Fold 3 IBS: 0.18637698687972554
Fold 4 IBS: 0.15939882886870535
Fold 5 IBS: 0.2113504541273204
[I 2024-04-17 14:19:50,846] Trial 5 finished with value: 0.18884120318309558 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.18286701090322455
Fold 2 IBS: 0.18771259904008297
Fold 3 IBS: 0.1679729459105892
Fold 4 IBS: 0.19488974663997188
Fold 5 IBS: 0.2131586526955741
[I 2024-04-17 14:20:22,096] Trial 6 finished with value: 0.18932019103788852 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20907943912609248
Fold 2 IBS: 0.2142874391649597
Fold 3 IBS: 0.20035786531447508
Fold 4 IBS: 0.22002960031246824
Fold 5 IBS: 0.21626779318082703
[I 2024-04-17 14:20:28,551] Trial 7 finished with value: 0.2120044274197645 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-17 14:20:39,764] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20357073593273053
Fold 2 IBS: 0.18780891594621849
Fold 3 IBS: 0.18460304549691883
Fold 4 IBS: 0.1856640301109529
Fold 5 IBS: 0.20794919209811308
[I 2024-04-17 14:20:42,431] Trial 9 finished with value: 0.19391918391698676 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-17 14:20:56,346] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27033688725897076}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20470418186342312
Fold 2 IBS: 0.20409550521820866
Fold 3 IBS: 0.19035125570755929
Fold 4 IBS: 0.20279707515139048
Fold 5 IBS: 0.2139020077116487
[I 2024-04-17 14:21:08,248] Trial 11 finished with value: 0.203170005130446 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.751058151425702, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008231293935378081}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20586437433035337
Fold 2 IBS: 0.18045352650478874
Fold 3 IBS: 0.18471158232105125
Fold 4 IBS: 0.1564532839984733
Fold 5 IBS: 0.21278485149213985
[I 2024-04-17 14:21:25,911] Trial 12 finished with value: 0.1880535237293613 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.9944667777599061, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10294337889507951}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.21738156589672325
Fold 2 IBS: 0.18148498524761636
Fold 3 IBS: 0.20328771782225072
Fold 4 IBS: 0.16200397997147525
Fold 5 IBS: 0.20246860054845137
[I 2024-04-17 14:23:46,940] Trial 13 finished with value: 0.1933253698973034 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.9694270540157217, 'max_features': None, 'min_weight_fraction_leaf': 0.1530029930440125}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.19707033841317873
Fold 2 IBS: 0.1876771636325187
Fold 3 IBS: 0.1818736950861829
Fold 4 IBS: 0.179566358950222
Fold 5 IBS: 0.2109513215570391
[I 2024-04-17 14:23:57,146] Trial 14 finished with value: 0.19142777552782828 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.7631177214580046, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21229864789095249}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.22655147877004286
Fold 2 IBS: 0.18326284905513224
Fold 3 IBS: 0.2097169134350128
Fold 4 IBS: 0.16586651259722404
Fold 5 IBS: 0.20952385709991683
[I 2024-04-17 14:25:03,409] Trial 15 finished with value: 0.19898432219146575 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 180, 'oob_score': False, 'max_samples': 0.9970673523205843, 'max_features': None, 'min_weight_fraction_leaf': 0.09604984749674861}. Best is trial 12 with value: 0.1880535237293613.

Fold 1 IBS: 0.20378808796262518
Fold 2 IBS: 0.19365995427708668
Fold 3 IBS: 0.1882413702928391
Fold 4 IBS: 0.19759396434280763
Fold 5 IBS: 0.21553362503994042
[I 2024-04-17 14:25:13,947] Trial 16 finished with value: 0.19976340038305979 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.8184724465806228, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.31376919111755797}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.20035161627096812
Fold 2 IBS: 0.18410251599192942
Fold 3 IBS: 0.18211883476245105
Fold 4 IBS: 0.18801743258981968
Fold 5 IBS: 0.21327804714656015
[I 2024-04-17 14:25:20,184] Trial 17 finished with value: 0.19357368935234567 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.3060837787360696, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.005619770510688432}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.19808389265211931
Fold 2 IBS: 0.18205953021252363
Fold 3 IBS: 0.185875813422921
Fold 4 IBS: 0.17434571756518558
Fold 5 IBS: 0.212414509617453
[I 2024-04-17 14:25:32,844] Trial 18 finished with value: 0.19055589269404052 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 397, 'oob_score': True, 'max_samples': 0.680642613858846, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12812974712655775}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.19002039864329462
Fold 2 IBS: 0.18942385941547232
Fold 3 IBS: 0.18799087691719493
Fold 4 IBS: 0.18284504372921612
Fold 5 IBS: 0.20840823704233402
[I 2024-04-17 14:26:06,668] Trial 19 finished with value: 0.1917376831495024 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.8923233540949727, 'max_features': None, 'min_weight_fraction_leaf': 0.22336599579981053}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.20241484728756806
Fold 2 IBS: 0.19065053491089928
Fold 3 IBS: 0.18779471719312824
Fold 4 IBS: 0.19480082717000774
Fold 5 IBS: 0.21868104809372813
[I 2024-04-17 14:26:14,124] Trial 20 finished with value: 0.19886839493106628 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.7871968885021372, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.34030385853489}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.20741632570728089
Fold 2 IBS: 0.1780845098687536
Fold 3 IBS: 0.1846122378972077
Fold 4 IBS: 0.1564868201189816
Fold 5 IBS: 0.21131308248390057
[I 2024-04-17 14:26:25,428] Trial 21 finished with value: 0.18758259521522488 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 304, 'oob_score': False, 'max_samples': 0.6541307441098512, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06381773403573333}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.21885274316469258
Fold 2 IBS: 0.17828077601342465
Fold 3 IBS: 0.1880861120963736
Fold 4 IBS: 0.15017691808187725
Fold 5 IBS: 0.208661756520607
[I 2024-04-17 14:26:40,574] Trial 22 finished with value: 0.18881166117539502 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.6139693116960656, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04453049413403026}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.19871040202258342
Fold 2 IBS: 0.184765649243245
Fold 3 IBS: 0.18498703463344066
Fold 4 IBS: 0.18599311903171908
Fold 5 IBS: 0.21143993706602787
[I 2024-04-17 14:26:46,123] Trial 23 finished with value: 0.1931792283994032 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 247, 'oob_score': False, 'max_samples': 0.4478983539583735, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1193442431038026}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.20038924075539685
Fold 2 IBS: 0.18852724912576502
Fold 3 IBS: 0.1847265574388743
Fold 4 IBS: 0.19388302387911258
Fold 5 IBS: 0.21617210096544462
[I 2024-04-17 14:26:54,379] Trial 24 finished with value: 0.1967396344329187 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.4295396819868078, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16813485936717243}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.23819448878865138
Fold 2 IBS: 0.18859860435971892
Fold 3 IBS: 0.19682793240255014
Fold 4 IBS: 0.15957526364066002
Fold 5 IBS: 0.20198931781322124
[I 2024-04-17 14:29:43,735] Trial 25 finished with value: 0.19703712140096036 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.7297972378004723, 'max_features': None, 'min_weight_fraction_leaf': 0.04981104107775003}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.2010034177138824
Fold 2 IBS: 0.182735296255063
Fold 3 IBS: 0.18466236755017185
Fold 4 IBS: 0.17246211363358033
Fold 5 IBS: 0.21643410204328975
[I 2024-04-17 14:29:50,725] Trial 26 finished with value: 0.19145945943919745 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.8472363371748154, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10973545356505882}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.1964328885601889
Fold 2 IBS: 0.18809613601862848
Fold 3 IBS: 0.1818420692920181
Fold 4 IBS: 0.17399619732336324
Fold 5 IBS: 0.2111836724460323
[I 2024-04-17 14:30:02,486] Trial 27 finished with value: 0.19031019272804622 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.9331113837900542, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2386001330983712}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.19854249756198333
Fold 2 IBS: 0.18810793646188287
Fold 3 IBS: 0.18308123282699756
Fold 4 IBS: 0.18681900970293147
Fold 5 IBS: 0.21245937503700765
[I 2024-04-17 14:30:10,984] Trial 28 finished with value: 0.19380201031816058 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.5883566242401418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1845919041664691}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.19840416643063166
Fold 2 IBS: 0.18537155668553762
Fold 3 IBS: 0.18344052151498125
Fold 4 IBS: 0.17492059658908363
Fold 5 IBS: 0.21086762605161444
[I 2024-04-17 14:30:21,440] Trial 29 finished with value: 0.19060089345436973 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 376, 'oob_score': False, 'max_samples': 0.6774353138386819, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.22252593046960736
Fold 2 IBS: 0.1888838348535354
Fold 3 IBS: 0.19671883214571217
Fold 4 IBS: 0.162697984958246
Fold 5 IBS: 0.1971675681434196
[I 2024-04-17 14:30:56,836] Trial 30 finished with value: 0.19359883011410411 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.49064978844124546, 'max_features': None, 'min_weight_fraction_leaf': 0.04202783134992163}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.218645817549917
Fold 2 IBS: 0.17984916123604971
Fold 3 IBS: 0.18930240115766292
Fold 4 IBS: 0.1502748627436339
Fold 5 IBS: 0.20680109594224744
[I 2024-04-17 14:31:10,488] Trial 31 finished with value: 0.18897466772590218 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.6145656696996076, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.028279638075097074}. Best is trial 21 with value: 0.18758259521522488.

Fold 1 IBS: 0.20444739845582136
Fold 2 IBS: 0.17446698341767913
Fold 3 IBS: 0.1910994493903993
Fold 4 IBS: 0.1668825886510828
Fold 5 IBS: 0.21103427734544067
[I 2024-04-17 14:31:19,085] Trial 32 finished with value: 0.18958613945208463 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.6325115094238634, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0760629688237641}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.21394095082970305
Fold 2 IBS: 0.18957239420831615
Fold 3 IBS: 0.18237897227425182
Fold 4 IBS: 0.17846689832832333
Fold 5 IBS: 0.2185435449686763
[I 2024-04-17 14:31:20,164] Trial 33 finished with value: 0.19658055212185413 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 19, 'oob_score': False, 'max_samples': 0.7088178154422675, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12510702348081404}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.21814598296546053
Fold 2 IBS: 0.1806418667764422
Fold 3 IBS: 0.185193327742374
Fold 4 IBS: 0.14930927407248543
Fold 5 IBS: 0.20730315585697304
[I 2024-04-17 14:31:35,634] Trial 34 finished with value: 0.18811872148274703 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 323, 'oob_score': True, 'max_samples': 0.5179281521096981, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03287535020826214}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.20068393107082932
Fold 2 IBS: 0.18004564547293722
Fold 3 IBS: 0.1813279250878163
Fold 4 IBS: 0.16606271502196493
Fold 5 IBS: 0.2133678565084531
[I 2024-04-17 14:31:44,707] Trial 35 finished with value: 0.1882976146324002 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 263, 'oob_score': True, 'max_samples': 0.5205069556471076, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08931012896561974}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.19921865381139617
Fold 2 IBS: 0.1879147544934006
Fold 3 IBS: 0.18415951307165418
Fold 4 IBS: 0.17928295771289782
Fold 5 IBS: 0.21187622162524927
[I 2024-04-17 14:31:50,977] Trial 36 finished with value: 0.19249042014291962 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 211, 'oob_score': True, 'max_samples': 0.34556748843479757, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08517804478502394}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.20689459020742101
Fold 2 IBS: 0.18578195800005948
Fold 3 IBS: 0.18062395532410724
Fold 4 IBS: 0.16979980454141178
Fold 5 IBS: 0.20913380244139584
[I 2024-04-17 14:31:58,487] Trial 37 finished with value: 0.19044682210287905 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 257, 'oob_score': True, 'max_samples': 0.19350535662381702, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02562193860216446}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.20164172687027268
Fold 2 IBS: 0.179042406474406
Fold 3 IBS: 0.18484112426907948
Fold 4 IBS: 0.15977140249838878
Fold 5 IBS: 0.2120612409546842
[I 2024-04-17 14:32:08,582] Trial 38 finished with value: 0.18747158021336624 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 289, 'oob_score': True, 'max_samples': 0.5607171176186949, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06539515726225846}. Best is trial 38 with value: 0.18747158021336624.
Fold 1 IBS: 0.20421151305171514
Fold 2 IBS: 0.17932735612158596
Fold 3 IBS: 0.17928162605465459
Fold 4 IBS: 0.16526541395746405
Fold 5 IBS: 0.2090081959308534
[I 2024-04-17 14:32:18,691] Trial 39 finished with value: 0.18741882102325463 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 316, 'oob_score': True, 'max_samples': 0.3617667691015132, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.052772428028015156}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2022159312451902
Fold 2 IBS: 0.1848488680529207
Fold 3 IBS: 0.17740255174053524
Fold 4 IBS: 0.1726825614136245
Fold 5 IBS: 0.213121743730351
[I 2024-04-17 14:32:27,555] Trial 40 finished with value: 0.19005433123652432 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.3736866960473132, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05524155311927098}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.22304701735374977
Fold 2 IBS: 0.19262749474927982
Fold 3 IBS: 0.18617094771467074
Fold 4 IBS: 0.16090440652263122
Fold 5 IBS: 0.2060830161959264
[I 2024-04-17 14:32:41,325] Trial 41 finished with value: 0.1937665765072516 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.26471791598500466, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008610506287772067}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.19780135900892157
Fold 2 IBS: 0.1857789376740191
Fold 3 IBS: 0.1799971131723769
Fold 4 IBS: 0.1804099527573313
Fold 5 IBS: 0.21177881228015194
[I 2024-04-17 14:32:52,384] Trial 42 finished with value: 0.19115323497856015 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.5034748057992058, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13666482964507704}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.21400092589198996
Fold 2 IBS: 0.2214210103976947
Fold 3 IBS: 0.2048692155883072
Fold 4 IBS: 0.22463234501283708
Fold 5 IBS: 0.2185873987821863
[I 2024-04-17 14:32:58,110] Trial 43 finished with value: 0.21670217913460305 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.4788775563231737, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20231241634002334
Fold 2 IBS: 0.18036495206092895
Fold 3 IBS: 0.1818599860701185
Fold 4 IBS: 0.16340196628946066
Fold 5 IBS: 0.21378560467248073
[I 2024-04-17 14:33:08,790] Trial 44 finished with value: 0.18834498508660244 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 296, 'oob_score': True, 'max_samples': 0.5506248755449263, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0721857441783233}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.1973845412708107
Fold 2 IBS: 0.18124870301190693
Fold 3 IBS: 0.1810814354603528
Fold 4 IBS: 0.1707551433320944
Fold 5 IBS: 0.2119250973889522
[I 2024-04-17 14:33:20,595] Trial 45 finished with value: 0.18847898409282343 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 348, 'oob_score': True, 'max_samples': 0.5775224127982328, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10537693884726008}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.21070983930823925
Fold 2 IBS: 0.18608759362092114
Fold 3 IBS: 0.18204123382213788
Fold 4 IBS: 0.16642669368966861
Fold 5 IBS: 0.21219350314332874
[I 2024-04-17 14:33:34,429] Trial 46 finished with value: 0.19149177271685913 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.26128950045955984, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02835891103553452}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20296038593675553
Fold 2 IBS: 0.1835795355330322
Fold 3 IBS: 0.18270515601508316
Fold 4 IBS: 0.17696688246148076
Fold 5 IBS: 0.2124434684430158
[I 2024-04-17 14:33:42,231] Trial 47 finished with value: 0.19173108567787348 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 286, 'oob_score': True, 'max_samples': 0.39724110016399944, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06776177948204519}. Best is trial 39 with value: 0.18741882102325463.

Fold 1 IBS: 0.21397545241919333
Fold 2 IBS: 0.22060585341756236
Fold 3 IBS: 0.20519466411613427
Fold 4 IBS: 0.2248054198587066
Fold 5 IBS: 0.21758241895615993
[I 2024-04-17 14:33:50,499] Trial 48 finished with value: 0.2164327617535513 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.1840472657347053, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20733215663048163
Fold 2 IBS: 0.19840873877308707
Fold 3 IBS: 0.1896647344947966
Fold 4 IBS: 0.2057146078926162
Fold 5 IBS: 0.2152447795126918
[I 2024-04-17 14:33:55,585] Trial 49 finished with value: 0.20327300346073468 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 187, 'oob_score': True, 'max_samples': 0.4611544071310423, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02536063881705921}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.204879944056226
Fold 2 IBS: 0.18198982906903266
Fold 3 IBS: 0.1813060638484819
Fold 4 IBS: 0.16283844353857155
Fold 5 IBS: 0.21363299219754156
[I 2024-04-17 14:34:04,679] Trial 50 finished with value: 0.18892945454197077 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 270, 'oob_score': True, 'max_samples': 0.5416005248904892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0034087820600749476}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2004109367454522
Fold 2 IBS: 0.18404020643987526
Fold 3 IBS: 0.18234193379348762
Fold 4 IBS: 0.17143012200567861
Fold 5 IBS: 0.21239169444633466
[I 2024-04-17 14:34:12,999] Trial 51 finished with value: 0.19012297868616568 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.5290774243115414, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09439815236719598}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20363791714493526
Fold 2 IBS: 0.18084498958548437
Fold 3 IBS: 0.1865787886727044
Fold 4 IBS: 0.15958133230330762
Fold 5 IBS: 0.21346890098280094
[I 2024-04-17 14:34:23,752] Trial 52 finished with value: 0.18882238573784652 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 268, 'oob_score': True, 'max_samples': 0.646747773042784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08961848913350215}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20381819322938977
Fold 2 IBS: 0.18114674744033232
Fold 3 IBS: 0.18113417018982886
Fold 4 IBS: 0.1618949090102553
Fold 5 IBS: 0.21456765862332783
[I 2024-04-17 14:34:40,728] Trial 53 finished with value: 0.18851233569862683 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 359, 'oob_score': True, 'max_samples': 0.5080082016246513, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06630490839370301}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2042758448261322
Fold 2 IBS: 0.18877763887578689
Fold 3 IBS: 0.18209755324442445
Fold 4 IBS: 0.19391559310720333
Fold 5 IBS: 0.2159060762300408
[I 2024-04-17 14:34:49,571] Trial 54 finished with value: 0.1969945412567175 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 321, 'oob_score': True, 'max_samples': 0.38392655290485045, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1447625548982195}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2034151090750003
Fold 2 IBS: 0.18176049250213502
Fold 3 IBS: 0.1857336365331899
Fold 4 IBS: 0.1788179124206326
Fold 5 IBS: 0.2129610073834551
[I 2024-04-17 14:34:58,719] Trial 55 finished with value: 0.1925376315828826 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 286, 'oob_score': True, 'max_samples': 0.5872802927086659, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.046825551317268566}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20422176706868694
Fold 2 IBS: 0.1924062351097664
Fold 3 IBS: 0.18544969707631245
Fold 4 IBS: 0.1984840238620755
Fold 5 IBS: 0.21497590518150314
[I 2024-04-17 14:35:05,608] Trial 56 finished with value: 0.19910752565966888 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 251, 'oob_score': True, 'max_samples': 0.4154965081431159, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18037694403417448}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2059789858573675
Fold 2 IBS: 0.1967683996639164
Fold 3 IBS: 0.18831908034352698
Fold 4 IBS: 0.20147608897626476
Fold 5 IBS: 0.21654528774605497
[I 2024-04-17 14:35:11,243] Trial 57 finished with value: 0.20181756851742616 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.7776350329623957, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3781865060679536}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20703604925067237
Fold 2 IBS: 0.18243435974189295
Fold 3 IBS: 0.18268181766890698
Fold 4 IBS: 0.20149520002925903
Fold 5 IBS: 0.21479477144824155
[I 2024-04-17 14:35:13,990] Trial 58 finished with value: 0.1976884396277946 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 89, 'oob_score': True, 'max_samples': 0.32208030951555616, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11116699744055775}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.21121978023043514
Fold 2 IBS: 0.17834386764399476
Fold 3 IBS: 0.18431619963737042
Fold 4 IBS: 0.15794559160168345
Fold 5 IBS: 0.211915583151784
[I 2024-04-17 14:35:29,531] Trial 59 finished with value: 0.18874820445305357 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 354, 'oob_score': True, 'max_samples': 0.706317491452594, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06164379588338738}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.1966264720209345
Fold 2 IBS: 0.18597478555674649
Fold 3 IBS: 0.1786448987547083
Fold 4 IBS: 0.16171860015636114
Fold 5 IBS: 0.20668689381001223
[I 2024-04-17 14:36:22,418] Trial 60 finished with value: 0.18593033005975254 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.4446079220615766, 'max_features': None, 'min_weight_fraction_leaf': 0.09271318262887082}. Best is trial 60 with value: 0.18593033005975254.
Fold 1 IBS: 0.2024856806183152
Fold 2 IBS: 0.18195716111018798
Fold 3 IBS: 0.18480931433897935
Fold 4 IBS: 0.16237325049629045
Fold 5 IBS: 0.20714210552628523
[I 2024-04-17 14:37:17,729] Trial 61 finished with value: 0.18775350241801164 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 306, 'oob_score': True, 'max_samples': 0.44685465277095665, 'max_features': None, 'min_weight_fraction_leaf': 0.08682673693183435}. Best is trial 60 with value: 0.18593033005975254.
Fold 1 IBS: 0.2284531812120082
Fold 2 IBS: 0.1948622570457934
Fold 3 IBS: 0.18812485157230974
Fold 4 IBS: 0.16088214458625358
Fold 5 IBS: 0.20190289439703843
[I 2024-04-17 14:38:47,814] Trial 62 finished with value: 0.19484506576268068 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.4515303316200064, 'max_features': None, 'min_weight_fraction_leaf': 0.037039554766136004}. Best is trial 60 with value: 0.18593033005975254.
Fold 1 IBS: 0.2252402779389061
Fold 2 IBS: 0.1862300882985594
Fold 3 IBS: 0.18602106947089103
Fold 4 IBS: 0.17312433407761857
Fold 5 IBS: 0.1889042172268272
[I 2024-04-17 14:40:15,824] Trial 63 finished with value: 0.19190399740256042 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.41265009702186795, 'max_features': None, 'min_weight_fraction_leaf': 0.016364606682246152}. Best is trial 60 with value: 0.18593033005975254.

Fold 1 IBS: 0.18697650055709675
Fold 2 IBS: 0.18964751614322145
Fold 3 IBS: 0.17157067951262514
Fold 4 IBS: 0.17048079186700552
Fold 5 IBS: 0.20812563312237994
[I 2024-04-17 14:40:54,681] Trial 64 finished with value: 0.18536022424046578 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.36087148528744895, 'max_features': None, 'min_weight_fraction_leaf': 0.10501492814170305}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.185980269157479
Fold 2 IBS: 0.18929665176523391
Fold 3 IBS: 0.17261558628019577
Fold 4 IBS: 0.17528863593015434
Fold 5 IBS: 0.20987976574068176
[I 2024-04-17 14:41:25,926] Trial 65 finished with value: 0.18661218177474898 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.35503340896452096, 'max_features': None, 'min_weight_fraction_leaf': 0.10944245403951429}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18694115431926822
Fold 2 IBS: 0.1908501583998164
Fold 3 IBS: 0.17205632092618067
Fold 4 IBS: 0.18203552427470343
Fold 5 IBS: 0.21326387492637428
[I 2024-04-17 14:41:57,403] Trial 66 finished with value: 0.1890294065692686 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.3614405881665075, 'max_features': None, 'min_weight_fraction_leaf': 0.12510407630083206}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.21397879618526044
Fold 2 IBS: 0.22095626300254492
Fold 3 IBS: 0.2049272671362546
Fold 4 IBS: 0.2246487203312697
Fold 5 IBS: 0.21797754042983516
[I 2024-04-17 14:42:06,693] Trial 67 finished with value: 0.21649771741703297 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 388, 'oob_score': True, 'max_samples': 0.277566908191509, 'max_features': None, 'min_weight_fraction_leaf': 0.16326642133899677}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18701806869001636
Fold 2 IBS: 0.19002615779169066
Fold 3 IBS: 0.17109529332077666
Fold 4 IBS: 0.17558286313646593
Fold 5 IBS: 0.20866467885193285
[I 2024-04-17 14:42:40,626] Trial 68 finished with value: 0.1864774123581765 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.3339648956191334, 'max_features': None, 'min_weight_fraction_leaf': 0.10534737249789848}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.213990042339758
Fold 2 IBS: 0.22081844148187832
Fold 3 IBS: 0.2049164994171005
Fold 4 IBS: 0.22451019970461408
Fold 5 IBS: 0.2178161153197119
[I 2024-04-17 14:42:48,139] Trial 69 finished with value: 0.21641025965261257 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.22058879264036, 'max_features': None, 'min_weight_fraction_leaf': 0.14500630501117967}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.21397438613021721
Fold 2 IBS: 0.22116611565870514
Fold 3 IBS: 0.20499774371165358
Fold 4 IBS: 0.22471498188046043
Fold 5 IBS: 0.21823664145637212
[I 2024-04-17 14:42:54,857] Trial 70 finished with value: 0.21661797376748168 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 383, 'oob_score': False, 'max_samples': 0.34596416260173934, 'max_features': None, 'min_weight_fraction_leaf': 0.2703111919415455}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18924036720156343
Fold 2 IBS: 0.18779280930051329
Fold 3 IBS: 0.17209448151288856
Fold 4 IBS: 0.17958207486087677
Fold 5 IBS: 0.211566257073253
[I 2024-04-17 14:43:22,550] Trial 71 finished with value: 0.18805519798981898 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.31453931029426085, 'max_features': None, 'min_weight_fraction_leaf': 0.1045230982104525}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.19657952397027323
Fold 2 IBS: 0.19022838128535594
Fold 3 IBS: 0.1708771341601037
Fold 4 IBS: 0.17168544722624235
Fold 5 IBS: 0.20713375074665116
[I 2024-04-17 14:43:53,152] Trial 72 finished with value: 0.1873008474777253 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 372, 'oob_score': False, 'max_samples': 0.2926475761323768, 'max_features': None, 'min_weight_fraction_leaf': 0.07798192572483449}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.19885306195698255
Fold 2 IBS: 0.18210548225096054
Fold 3 IBS: 0.17731375226506932
Fold 4 IBS: 0.16883406032672896
Fold 5 IBS: 0.20809348652266163
[I 2024-04-17 14:44:18,144] Trial 73 finished with value: 0.18703996866448058 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 368, 'oob_score': False, 'max_samples': 0.2870778190236743, 'max_features': None, 'min_weight_fraction_leaf': 0.05561809788206867}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.193787788585605
Fold 2 IBS: 0.18733247875335163
Fold 3 IBS: 0.17837994780791747
Fold 4 IBS: 0.1744246643744868
Fold 5 IBS: 0.21343920626735596
[I 2024-04-17 14:44:41,796] Trial 74 finished with value: 0.1894728171577434 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.22588589287949842, 'max_features': None, 'min_weight_fraction_leaf': 0.05443689708608288}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18723429594597044
Fold 2 IBS: 0.18527389087754653
Fold 3 IBS: 0.17197014707614233
Fold 4 IBS: 0.1772724521433817
Fold 5 IBS: 0.21429754155065364
[I 2024-04-17 14:45:05,371] Trial 75 finished with value: 0.1872096655187389 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.2998143519691557, 'max_features': None, 'min_weight_fraction_leaf': 0.1075330144825516}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.1941066110336133
Fold 2 IBS: 0.18509351343143435
Fold 3 IBS: 0.17110131699959152
Fold 4 IBS: 0.18270444973194716
Fold 5 IBS: 0.21156937371299012
[I 2024-04-17 14:45:24,254] Trial 76 finished with value: 0.1889150529819153 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 399, 'oob_score': False, 'max_samples': 0.28316698675748087, 'max_features': None, 'min_weight_fraction_leaf': 0.12059869029554741}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.21397695237476239
Fold 2 IBS: 0.22118615223089322
Fold 3 IBS: 0.2050313552835387
Fold 4 IBS: 0.2247532956416355
Fold 5 IBS: 0.21820980850510233
[I 2024-04-17 14:45:31,249] Trial 77 finished with value: 0.21663151280718643 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 371, 'oob_score': False, 'max_samples': 0.3371898508848934, 'max_features': None, 'min_weight_fraction_leaf': 0.2048303246846501}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.195733817221237
Fold 2 IBS: 0.18784802284526486
Fold 3 IBS: 0.1763445138354909
Fold 4 IBS: 0.17500708454376265
Fold 5 IBS: 0.20952700605055732
[I 2024-04-17 14:46:05,244] Trial 78 finished with value: 0.18889208889926254 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.29504437594758753, 'max_features': None, 'min_weight_fraction_leaf': 0.07587622273136602}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.21396670472446544
Fold 2 IBS: 0.22085379157505564
Fold 3 IBS: 0.20493941845669997
Fold 4 IBS: 0.22470262306501207
Fold 5 IBS: 0.21714959439503256
[I 2024-04-17 14:46:14,455] Trial 79 finished with value: 0.21632242644325314 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.13307661238331164, 'max_features': None, 'min_weight_fraction_leaf': 0.11597487641803922}. Best is trial 64 with value: 0.18536022424046578.

Fold 1 IBS: 0.2139852535910293
Fold 2 IBS: 0.22079135086710738
Fold 3 IBS: 0.2049571432154721
Fold 4 IBS: 0.22449984942587378
Fold 5 IBS: 0.21784420818016068
[I 2024-04-17 14:46:25,314] Trial 80 finished with value: 0.21641556105592863 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 401, 'oob_score': False, 'max_samples': 0.23317876663764808, 'max_features': None, 'min_weight_fraction_leaf': 0.13195032778351135}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18698963922132994
Fold 2 IBS: 0.19117908340974094
Fold 3 IBS: 0.1716425830420473
Fold 4 IBS: 0.1706227695034198
Fold 5 IBS: 0.20890166136319582
[I 2024-04-17 14:46:57,469] Trial 81 finished with value: 0.1858671473079468 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.3619448678095568, 'max_features': None, 'min_weight_fraction_leaf': 0.10057070644705586}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.1890967403784016
Fold 2 IBS: 0.18652324224983566
Fold 3 IBS: 0.17238080905282963
Fold 4 IBS: 0.16710329314707312
Fold 5 IBS: 0.209650785925764
[I 2024-04-17 14:47:29,248] Trial 82 finished with value: 0.18495097415078082 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.3624030825154118, 'max_features': None, 'min_weight_fraction_leaf': 0.09714741335387223}. Best is trial 82 with value: 0.18495097415078082.
Fold 1 IBS: 0.1869379635607008
Fold 2 IBS: 0.1840979377124555
Fold 3 IBS: 0.1723208864840007
Fold 4 IBS: 0.16624305438296152
Fold 5 IBS: 0.20739680918357425
[I 2024-04-17 14:48:07,479] Trial 83 finished with value: 0.18339933026473856 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 368, 'oob_score': False, 'max_samples': 0.39234117831739307, 'max_features': None, 'min_weight_fraction_leaf': 0.09956600887465704}. Best is trial 83 with value: 0.18339933026473856.
Fold 1 IBS: 0.1886542770417182
Fold 2 IBS: 0.18606078762892803
Fold 3 IBS: 0.17038230752313355
Fold 4 IBS: 0.1646204973275064
Fold 5 IBS: 0.20651428479641726
[I 2024-04-17 14:48:51,106] Trial 84 finished with value: 0.1832464308635407 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.3902292236281065, 'max_features': None, 'min_weight_fraction_leaf': 0.0959966989881746}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19155628917728368
Fold 2 IBS: 0.1801885982714529
Fold 3 IBS: 0.17804730003931615
Fold 4 IBS: 0.1693620308491127
Fold 5 IBS: 0.20783919776163526
[I 2024-04-17 14:49:19,594] Trial 85 finished with value: 0.18539868321976014 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 340, 'oob_score': False, 'max_samples': 0.3968957116262019, 'max_features': None, 'min_weight_fraction_leaf': 0.095219664847033}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18538493455740376
Fold 2 IBS: 0.18576229943013492
Fold 3 IBS: 0.17402978107752123
Fold 4 IBS: 0.18507755128123915
Fold 5 IBS: 0.21358478244911275
[I 2024-04-17 14:49:39,290] Trial 86 finished with value: 0.18876786975908236 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 353, 'oob_score': False, 'max_samples': 0.38638292055767265, 'max_features': None, 'min_weight_fraction_leaf': 0.17872796639110672}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19006306497707842
Fold 2 IBS: 0.1859568983552553
Fold 3 IBS: 0.17526064526770588
Fold 4 IBS: 0.16110281294560094
Fold 5 IBS: 0.20520872126963988
[I 2024-04-17 14:50:17,064] Trial 87 finished with value: 0.18351842856305606 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.4051015506296675, 'max_features': None, 'min_weight_fraction_leaf': 0.09713693453540154}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19767011171898427
Fold 2 IBS: 0.17964734520295073
Fold 3 IBS: 0.1836195742480708
Fold 4 IBS: 0.1667956970154799
Fold 5 IBS: 0.2070890710759274
[I 2024-04-17 14:50:47,199] Trial 88 finished with value: 0.1869643598522826 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.4334251281469186, 'max_features': None, 'min_weight_fraction_leaf': 0.09492515708957672}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18447989656323524
Fold 2 IBS: 0.1882071335854152
Fold 3 IBS: 0.17009416602918556
Fold 4 IBS: 0.18175070837886942
Fold 5 IBS: 0.21200575266539284
[I 2024-04-17 14:51:11,349] Trial 89 finished with value: 0.18730753144441964 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 334, 'oob_score': False, 'max_samples': 0.40662933261411155, 'max_features': None, 'min_weight_fraction_leaf': 0.14538592818664145}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18291200990480525
Fold 2 IBS: 0.18829799983042705
Fold 3 IBS: 0.174582652991839
Fold 4 IBS: 0.1734065332761776
Fold 5 IBS: 0.2073726719246909
[I 2024-04-17 14:51:52,184] Trial 90 finished with value: 0.18531437358558794 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.46906936332717275, 'max_features': None, 'min_weight_fraction_leaf': 0.1301923106019002}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18483018153750577
Fold 2 IBS: 0.18822465780769382
Fold 3 IBS: 0.1731074140071581
Fold 4 IBS: 0.17188948389568984
Fold 5 IBS: 0.20714468645851628
[I 2024-04-17 14:52:33,397] Trial 91 finished with value: 0.18503928474131276 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.47678737384020253, 'max_features': None, 'min_weight_fraction_leaf': 0.1325172709355868}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18950832462950518
Fold 2 IBS: 0.18701656820376608
Fold 3 IBS: 0.17893499023469356
Fold 4 IBS: 0.17722915182580176
Fold 5 IBS: 0.20663881973138198
[I 2024-04-17 14:53:10,440] Trial 92 finished with value: 0.18786557092502973 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 359, 'oob_score': False, 'max_samples': 0.49169288583702514, 'max_features': None, 'min_weight_fraction_leaf': 0.13392414841790756}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19861247726074407
Fold 2 IBS: 0.17973057843635412
Fold 3 IBS: 0.185421278409284
Fold 4 IBS: 0.16412850305110133
Fold 5 IBS: 0.20541831001893
[I 2024-04-17 14:54:07,778] Trial 93 finished with value: 0.1866622294352827 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.4745011682049886, 'max_features': None, 'min_weight_fraction_leaf': 0.09685737891379577}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19722640593255503
Fold 2 IBS: 0.18658267818572852
Fold 3 IBS: 0.17931575780016162
Fold 4 IBS: 0.15937059058391914
Fold 5 IBS: 0.20605274303785986
[I 2024-04-17 14:54:52,488] Trial 94 finished with value: 0.1857096351080448 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 338, 'oob_score': False, 'max_samples': 0.4244190509544878, 'max_features': None, 'min_weight_fraction_leaf': 0.08390492642221409}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18486260175817798
Fold 2 IBS: 0.18637157071560814
Fold 3 IBS: 0.17201029045136673
Fold 4 IBS: 0.18278192459752535
Fold 5 IBS: 0.21486338860156232
[I 2024-04-17 14:55:14,228] Trial 95 finished with value: 0.1881779552248481 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 382, 'oob_score': False, 'max_samples': 0.3768152460146832, 'max_features': None, 'min_weight_fraction_leaf': 0.16125627455265384}. Best is trial 84 with value: 0.1832464308635407.

Fold 1 IBS: 0.19987889711029083
Fold 2 IBS: 0.18568352389906653
Fold 3 IBS: 0.18380646487398802
Fold 4 IBS: 0.16033813976360883
Fold 5 IBS: 0.20642365546571148
[I 2024-04-17 14:56:01,366] Trial 96 finished with value: 0.18722613622253315 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 363, 'oob_score': False, 'max_samples': 0.4255182801365352, 'max_features': None, 'min_weight_fraction_leaf': 0.08056036420837291}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19365837237754394
Fold 2 IBS: 0.183435405665406
Fold 3 IBS: 0.18008910470800357
Fold 4 IBS: 0.17339462295545943
Fold 5 IBS: 0.20781358095494984
[I 2024-04-17 14:56:30,093] Trial 97 finished with value: 0.18767821733227258 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.4693979321374093, 'max_features': None, 'min_weight_fraction_leaf': 0.1201270975782226}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18503478594867145
Fold 2 IBS: 0.1888913820526276
Fold 3 IBS: 0.1708577577733008
Fold 4 IBS: 0.18063206055766248
Fold 5 IBS: 0.214156204168513
[I 2024-04-17 14:56:50,522] Trial 98 finished with value: 0.18791443810015507 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.3850920531360686, 'max_features': None, 'min_weight_fraction_leaf': 0.1315399576273898}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.20344124949745349
Fold 2 IBS: 0.18698507294354125
Fold 3 IBS: 0.1879934856478453
Fold 4 IBS: 0.1880278288749208
Fold 5 IBS: 0.2133922668795308
[I 2024-04-17 14:56:56,905] Trial 99 finished with value: 0.19596798076865835 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 353, 'oob_score': False, 'max_samples': 0.40653139828572354, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08424550739812792}. Best is trial 84 with value: 0.1832464308635407.


* Best trial for IBS:
 FrozenTrial(number=84, state=TrialState.COMPLETE, values=[0.1832464308635407], datetime_start=datetime.datetime(2024, 4, 17, 14, 48, 7, 488575), datetime_complete=datetime.datetime(2024, 4, 17, 14, 48, 51, 105092), params={'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.3902292236281065, 'max_features': None, 'min_weight_fraction_leaf': 0.0959966989881746}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=84, value=None)


* Best Score for IBS:
 0.1832464308635407

In [52]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [53]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.864
train_ibs:  0.183

#### Test

In [54]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

In [55]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=11, max_features='auto', max_leaf_nodes=15,
                     max_samples=0.9847467855272036, min_samples_leaf=4,
                     min_samples_split=7,
                     min_weight_fraction_leaf=0.04749646122417352,
                     n_estimators=230, random_state=123, warm_start=True)

test_cindex:  0.629

RandomSurvivalForest(max_depth=2, max_features=None, max_leaf_nodes=7,
                     max_samples=0.3902292236281065, min_samples_leaf=4,
                     min_samples_split=5,
                     min_weight_fraction_leaf=0.0959966989881746,
                     n_estimators=344, random_state=123)

test_ibs:  0.205

In [56]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [57]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [58]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 14:57:09,051] A new study created in memory with name: no-name-53e40924-058f-4cb9-a4d6-af1f47522cec

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 14:57:10,623] Trial 0 finished with value: 0.7784578545189774 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7784578545189774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:57:14,462] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7784578545189774.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 14:57:22,682] Trial 2 finished with value: 0.7601142724144229 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7784578545189774.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 14:57:23,536] Trial 3 finished with value: 0.802961090796227 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:57:26,407] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:57:29,858] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 14:57:31,858] Trial 6 finished with value: 0.7670018279196149 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.6150234741784038
[I 2024-04-17 14:57:36,174] Trial 7 finished with value: 0.6820130047188975 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 14:57:36,617] Trial 8 finished with value: 0.7996535923726207 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.5539906103286385
[I 2024-04-17 14:57:45,897] Trial 9 finished with value: 0.6684380652697066 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:57:47,314] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.25578614141973877, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.6450892857142857
Fold 3 C-index: 0.7524509803921569
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.6737089201877934
[I 2024-04-17 14:57:47,662] Trial 11 finished with value: 0.7252477001554444 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 4, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.15140395801593098}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7276995305164319
[I 2024-04-17 14:57:48,273] Trial 12 finished with value: 0.7795687852038334 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 63, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.16694541300368826}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7276995305164319
[I 2024-04-17 14:57:49,173] Trial 13 finished with value: 0.7859770734903794 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8757004183768704, 'min_weight_fraction_leaf': 0.12942492296949484}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:57:50,167] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.2319873930301426}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:57:50,669] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6967810217991331, 'min_weight_fraction_leaf': 0.40889055344541997}. Best is trial 3 with value: 0.802961090796227.

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 14:57:51,430] Trial 16 finished with value: 0.7903520467896392 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 95, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.884183184043622, 'min_weight_fraction_leaf': 0.10581506507448754}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:57:52,663] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 226, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.37217752523657055, 'min_weight_fraction_leaf': 0.19947678741058694}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 14:57:53,511] Trial 18 finished with value: 0.7422562391542786 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 21, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6674013857794929, 'min_weight_fraction_leaf': 0.0023155280568105674}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 14:57:54,570] Trial 19 finished with value: 0.7919172217583121 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 177, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8783131293076132, 'min_weight_fraction_leaf': 0.35588501080184637}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 14:57:55,238] Trial 20 finished with value: 0.7884100418072868 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 88, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7140167187076433, 'min_weight_fraction_leaf': 0.28881891871571913}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 14:57:56,714] Trial 21 finished with value: 0.7828532818336494 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8819344617828546, 'min_weight_fraction_leaf': 0.3430677365625254}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:57:57,733] Trial 22 finished with value: 0.7949143304625697 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 165, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8606079420302547, 'min_weight_fraction_leaf': 0.37164871595060495}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:57:58,614] Trial 23 finished with value: 0.5 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8095519124644711, 'min_weight_fraction_leaf': 0.44720270469880896}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:57:59,825] Trial 24 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 226, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6043934042800692, 'min_weight_fraction_leaf': 0.3984329214033346}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.7181372549019608
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6455399061032864
[I 2024-04-17 14:58:00,444] Trial 25 finished with value: 0.7173359925057237 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 77, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9355023621313151, 'min_weight_fraction_leaf': 0.21828153747802176}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6338028169014085
[I 2024-04-17 14:58:04,507] Trial 26 finished with value: 0.75455954833675 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 172, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7429676103800898, 'min_weight_fraction_leaf': 0.2902550218399806}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 14:58:04,964] Trial 27 finished with value: 0.7870695134161543 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 32, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8169136436840319, 'min_weight_fraction_leaf': 0.07430019929598344}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:58:05,820] Trial 28 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 110, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6203838276523786, 'min_weight_fraction_leaf': 0.49397030324411406}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 14:58:07,737] Trial 29 finished with value: 0.7664099905509458 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7463806142458222, 'min_weight_fraction_leaf': 0.12619621560869665}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 14:58:08,979] Trial 30 finished with value: 0.7959507907686649 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 209, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9444316884960255, 'min_weight_fraction_leaf': 0.10548580221002543}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8235294117647058

Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 14:58:10,315] Trial 31 finished with value: 0.8023701302106281 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 209, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9175308644810205, 'min_weight_fraction_leaf': 0.1088935662786611}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 14:58:11,577] Trial 32 finished with value: 0.7950579336258078 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 211, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9467713628420997, 'min_weight_fraction_leaf': 0.08138167552522578}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 14:58:13,043] Trial 33 finished with value: 0.8061356825263047 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.937124800917338, 'min_weight_fraction_leaf': 0.10798501652350923}. Best is trial 33 with value: 0.8061356825263047.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 14:58:16,011] Trial 34 finished with value: 0.8069410046551562 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9924586053612823, 'min_weight_fraction_leaf': 0.037167307803865623}. Best is trial 34 with value: 0.8069410046551562.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8309859154929577
[I 2024-04-17 14:58:20,186] Trial 35 finished with value: 0.8337706480426819 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 307, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.99537727544732, 'min_weight_fraction_leaf': 0.04956730948759107}. Best is trial 35 with value: 0.8337706480426819.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 14:58:30,965] Trial 36 finished with value: 0.7482461120884926 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 316, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9947891025922952, 'min_weight_fraction_leaf': 0.040945703784245044}. Best is trial 35 with value: 0.8337706480426819.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8591549295774648
[I 2024-04-17 14:58:36,441] Trial 37 finished with value: 0.847904896492382 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 401, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.989290011992841, 'min_weight_fraction_leaf': 0.02856480473176247}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8544600938967136
[I 2024-04-17 14:58:41,687] Trial 38 finished with value: 0.8469659293562317 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 388, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9932170620443503, 'min_weight_fraction_leaf': 0.050004592573005685}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 14:58:57,145] Trial 39 finished with value: 0.7495415406312282 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 394, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9915601275040028, 'min_weight_fraction_leaf': 0.03663352433082424}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8403755868544601
[I 2024-04-17 14:59:03,125] Trial 40 finished with value: 0.8357412545967835 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 497, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.49205438109527067, 'min_weight_fraction_leaf': 0.02508749840989511}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8403755868544601
[I 2024-04-17 14:59:09,282] Trial 41 finished with value: 0.8293587936722526 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 500, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.47059202334413597, 'min_weight_fraction_leaf': 0.028824885734288947}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 14:59:16,367] Trial 42 finished with value: 0.8460265073711295 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 485, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.47951227685883335, 'min_weight_fraction_leaf': 0.013760080445973905}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.812206572769953
[I 2024-04-17 14:59:21,694] Trial 43 finished with value: 0.818279225092199 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 388, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.3956943544905941, 'min_weight_fraction_leaf': 0.06238579527271516}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8544600938967136
[I 2024-04-17 14:59:27,592] Trial 44 finished with value: 0.8360856192344845 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 443, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4206894066469547, 'min_weight_fraction_leaf': 0.022459821558201455}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.8967136150234741
[I 2024-04-17 14:59:36,121] Trial 45 finished with value: 0.8420095331119368 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 445, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5190626877291048, 'min_weight_fraction_leaf': 0.009502780876316706}. Best is trial 37 with value: 0.847904896492382.

Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8028169014084507
[I 2024-04-17 14:59:41,923] Trial 46 finished with value: 0.8220544611789512 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 451, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.517469689795079, 'min_weight_fraction_leaf': 0.07841045931780831}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 15:00:04,825] Trial 47 finished with value: 0.7254847827232809 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 414, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.32086266244117334, 'min_weight_fraction_leaf': 0.01763716368072068}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8450704225352113
[I 2024-04-17 15:00:11,974] Trial 48 finished with value: 0.8350464295509287 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 460, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4023308297410664, 'min_weight_fraction_leaf': 0.003079257502260936}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8497652582159625
[I 2024-04-17 15:00:17,851] Trial 49 finished with value: 0.8397048390094625 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 368, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5566958033733842, 'min_weight_fraction_leaf': 0.05919578966108157}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.812206572769953
[I 2024-04-17 15:00:22,557] Trial 50 finished with value: 0.8168300522124603 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 355, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5346285785794207, 'min_weight_fraction_leaf': 0.05949010437559907}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 15:00:30,380] Trial 51 finished with value: 0.8426559761897272 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 422, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4307713618159553, 'min_weight_fraction_leaf': 0.0006143407440005848}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.863849765258216
[I 2024-04-17 15:00:37,143] Trial 52 finished with value: 0.8261414109558636 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 383, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.2944027889978438, 'min_weight_fraction_leaf': 0.0025196302934173548}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 15:00:42,293] Trial 53 finished with value: 0.7977685626836676 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 414, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.17582352730772366, 'min_weight_fraction_leaf': 0.061407856338507316}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7276995305164319
[I 2024-04-17 15:00:47,285] Trial 54 finished with value: 0.7531047646128582 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 473, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.44561277075368966, 'min_weight_fraction_leaf': 0.08811499948097072}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9248826291079812
[I 2024-04-17 15:00:55,973] Trial 55 finished with value: 0.8665875045053596 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 423, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5744229763504507, 'min_weight_fraction_leaf': 0.016027842870494274}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 15:01:00,596] Trial 56 finished with value: 0.6951645058986333 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 434, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.35399595847912424, 'min_weight_fraction_leaf': 0.015257524234107825}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8779342723004695
[I 2024-04-17 15:01:07,521] Trial 57 finished with value: 0.8481318045459971 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6103451470664683, 'min_weight_fraction_leaf': 0.047571291705527236}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 15:01:11,991] Trial 58 finished with value: 0.7701604423354131 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 412, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.59366729390164, 'min_weight_fraction_leaf': 0.14674774348708902}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 15:01:35,983] Trial 59 finished with value: 0.758267844731695 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 477, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6716331483015671, 'min_weight_fraction_leaf': 0.04950449980370537}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 15:01:43,526] Trial 60 finished with value: 0.8025306955794198 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6374430422021584, 'min_weight_fraction_leaf': 0.16819923331696962}. Best is trial 55 with value: 0.8665875045053596.

Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.8779342723004695
[I 2024-04-17 15:01:53,357] Trial 61 finished with value: 0.8267317399171535 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 429, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.49232023541877573, 'min_weight_fraction_leaf': 0.00145953757858059}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.8497652582159625
[I 2024-04-17 15:01:57,808] Trial 62 finished with value: 0.8414621270800418 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 402, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4565775326135385, 'min_weight_fraction_leaf': 0.0216071430745067}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8779342723004695
[I 2024-04-17 15:02:07,802] Trial 63 finished with value: 0.8515511699906788 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 485, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.574595322070414, 'min_weight_fraction_leaf': 0.04569685903621326}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8544600938967136
[I 2024-04-17 15:02:16,696] Trial 64 finished with value: 0.8397072520072715 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 487, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5869227943626324, 'min_weight_fraction_leaf': 0.04476269499363313}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 15:02:22,453] Trial 65 finished with value: 0.8070528716762316 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 461, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5714061896889552, 'min_weight_fraction_leaf': 0.09443804061211797}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 15:02:30,074] Trial 66 finished with value: 0.8117060028439325 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 428, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4269898374784659, 'min_weight_fraction_leaf': 0.06693452124581281}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.812206572769953
[I 2024-04-17 15:02:34,925] Trial 67 finished with value: 0.8090148375189878 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 375, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8415815579585453, 'min_weight_fraction_leaf': 0.03102886731531589}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 15:02:40,378] Trial 68 finished with value: 0.724330800854678 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 482, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6969921866106945, 'min_weight_fraction_leaf': 0.08996201441410404}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.8685446009389671
[I 2024-04-17 15:02:46,672] Trial 69 finished with value: 0.8410235474195836 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 464, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6336109184394701, 'min_weight_fraction_leaf': 0.04462823296429158}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 15:02:51,963] Trial 70 finished with value: 0.7949235593846933 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 352, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9130147369001846, 'min_weight_fraction_leaf': 0.25717771363652614}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.92018779342723
[I 2024-04-17 15:03:00,533] Trial 71 finished with value: 0.8504560046599232 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 447, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5168055835891595, 'min_weight_fraction_leaf': 0.012986169067804712}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8967136150234741
[I 2024-04-17 15:03:07,247] Trial 72 finished with value: 0.8519584263631383 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 439, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5366958727104124, 'min_weight_fraction_leaf': 0.016031857840163272}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8028169014084507
[I 2024-04-17 15:03:13,650] Trial 73 finished with value: 0.8207791294121825 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 447, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5266040099828285, 'min_weight_fraction_leaf': 0.07379071659454789}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.92018779342723
[I 2024-04-17 15:03:21,070] Trial 74 finished with value: 0.8657901849373276 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 401, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.556218611994605, 'min_weight_fraction_leaf': 0.026708566480428787}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.812206572769953
[I 2024-04-17 15:03:25,758] Trial 75 finished with value: 0.8181142885767413 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 396, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.569175138136116, 'min_weight_fraction_leaf': 0.049779903595510204}. Best is trial 55 with value: 0.8665875045053596.

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7136150234741784
[I 2024-04-17 15:03:44,963] Trial 76 finished with value: 0.7457830837322044 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 333, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.61013169816922, 'min_weight_fraction_leaf': 0.032654970370419666}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 15:03:50,748] Trial 77 finished with value: 0.813252260011932 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 407, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6556499931697389, 'min_weight_fraction_leaf': 0.11468485034119792}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 15:03:55,761] Trial 78 finished with value: 0.8054529568030716 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 440, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5407839514816556, 'min_weight_fraction_leaf': 0.13017998804408376}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9362745098039216
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 15:04:03,562] Trial 79 finished with value: 0.8680221676184047 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 373, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9631780533456042, 'min_weight_fraction_leaf': 0.022603700176597446}. Best is trial 79 with value: 0.8680221676184047.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 15:04:08,688] Trial 80 finished with value: 0.796736053008863 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 10, 'n_estimators': 453, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5088492830088868, 'min_weight_fraction_leaf': 0.02502911966074306}. Best is trial 79 with value: 0.8680221676184047.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.946078431372549
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 15:04:15,731] Trial 81 finished with value: 0.882207251893772 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 372, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9615950289600182, 'min_weight_fraction_leaf': 0.03679139394563669}. Best is trial 81 with value: 0.882207251893772.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.946078431372549
Fold 4 C-index: 0.9620253164556962
Fold 5 C-index: 0.9436619718309859
[I 2024-04-17 15:04:22,539] Trial 82 finished with value: 0.8858022781309804 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 336, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.965941994806725, 'min_weight_fraction_leaf': 0.017267854864073284}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9436619718309859
[I 2024-04-17 15:04:29,988] Trial 83 finished with value: 0.8652682964140128 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 339, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9609090906034798, 'min_weight_fraction_leaf': 0.01406330393712882}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9389671361502347
[I 2024-04-17 15:04:38,343] Trial 84 finished with value: 0.8614808250890755 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9134206211086566, 'min_weight_fraction_leaf': 0.01387175275139686}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8873239436619719
[I 2024-04-17 15:04:42,626] Trial 85 finished with value: 0.8498449433258773 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 327, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9573743509441937, 'min_weight_fraction_leaf': 0.037220356101627605}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8028169014084507
[I 2024-04-17 15:04:48,399] Trial 86 finished with value: 0.8063147993763705 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 373, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9691139339019299, 'min_weight_fraction_leaf': 0.013557733109048805}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 15:04:53,846] Trial 87 finished with value: 0.8606583123370746 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 335, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9145533784322645, 'min_weight_fraction_leaf': 0.07241658060725681}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 15:05:09,994] Trial 88 finished with value: 0.7577736506359624 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 296, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.91048505123246, 'min_weight_fraction_leaf': 0.07341369185217136}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 15:05:13,870] Trial 89 finished with value: 0.7985598378397373 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 274, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8690506465331735, 'min_weight_fraction_leaf': 0.189066433472832}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 15:05:17,677] Trial 90 finished with value: 0.7685681160339142 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 335, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8972668164493001, 'min_weight_fraction_leaf': 0.31515481216778163}. Best is trial 82 with value: 0.8858022781309804.

Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9483568075117371
[I 2024-04-17 15:05:24,587] Trial 91 finished with value: 0.862597275251046 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 363, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9707802904512073, 'min_weight_fraction_leaf': 0.024021851910904807}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9389671361502347
[I 2024-04-17 15:05:31,689] Trial 92 finished with value: 0.8605776934106274 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 363, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9280981755055671, 'min_weight_fraction_leaf': 0.023404006766994168}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9154929577464789
[I 2024-04-17 15:05:37,888] Trial 93 finished with value: 0.8582896374728435 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 320, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8499587877144377, 'min_weight_fraction_leaf': 0.03127381290624083}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.9014084507042254
[I 2024-04-17 15:05:45,193] Trial 94 finished with value: 0.8665655880498362 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9666217297893754, 'min_weight_fraction_leaf': 0.058324374733458}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9313725490196079
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.8873239436619719
[I 2024-04-17 15:05:51,354] Trial 95 finished with value: 0.8664219797791237 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 351, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9706033105898769, 'min_weight_fraction_leaf': 0.06930608338875063}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 15:05:54,967] Trial 96 finished with value: 0.7713977049757649 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 342, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9653170534920801, 'min_weight_fraction_leaf': 0.05657719832813177}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8497652582159625
[I 2024-04-17 15:05:59,566] Trial 97 finished with value: 0.8459290116474474 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 303, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9660782335192536, 'min_weight_fraction_leaf': 0.10022719516204912}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9248826291079812
[I 2024-04-17 15:06:05,780] Trial 98 finished with value: 0.8772114347448893 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 348, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9470976294421786, 'min_weight_fraction_leaf': 0.037342531882997666}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9071729957805907

[I 2024-04-17 15:06:12,111] A new study created in memory with name: no-name-e672eda1-edbd-4e54-acbc-bd94e670896d

Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 15:06:12,097] Trial 99 finished with value: 0.8535852615977915 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 344, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9441404618918096, 'min_weight_fraction_leaf': 0.08095118320482457}. Best is trial 82 with value: 0.8858022781309804.


* Best trial for C-index:
 FrozenTrial(number=82, state=TrialState.COMPLETE, values=[0.8858022781309804], datetime_start=datetime.datetime(2024, 4, 17, 15, 4, 15, 737821), datetime_complete=datetime.datetime(2024, 4, 17, 15, 4, 22, 538015), params={'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 336, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.965941994806725, 'min_weight_fraction_leaf': 0.017267854864073284}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=82, value=None)


* Best Score for C-index:
 0.8858022781309804

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.19573874032428965
Fold 2 IBS: 0.19215300245103015
Fold 3 IBS: 0.18577123192698092
Fold 4 IBS: 0.18877405090465085
Fold 5 IBS: 0.2108069355911196
[I 2024-04-17 15:06:18,987] Trial 0 finished with value: 0.19464879223961423 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.19464879223961423.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-17 15:06:28,693] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.19464879223961423.
Fold 1 IBS: 0.18661490821092397
Fold 2 IBS: 0.18849796485994302
Fold 3 IBS: 0.16935693688351927
Fold 4 IBS: 0.16616413385030462
Fold 5 IBS: 0.21353095384309942
[I 2024-04-17 15:06:38,010] Trial 2 finished with value: 0.18483297952955807 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.18461528870168228
Fold 2 IBS: 0.19204843106240665
Fold 3 IBS: 0.16690491265843854
Fold 4 IBS: 0.1668314734874405
Fold 5 IBS: 0.21495543742143608
[I 2024-04-17 15:06:41,065] Trial 3 finished with value: 0.18507110866628082 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-17 15:06:48,176] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-17 15:06:52,049] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.19873722451693057
Fold 2 IBS: 0.19705874496937723
Fold 3 IBS: 0.1849295300703863
Fold 4 IBS: 0.19065127758534944
Fold 5 IBS: 0.21038780527035808
[I 2024-04-17 15:07:00,157] Trial 6 finished with value: 0.1963529164824803 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.2092186818635856
Fold 2 IBS: 0.2146879015458582
Fold 3 IBS: 0.2003062385248317
Fold 4 IBS: 0.21667734530345348
Fold 5 IBS: 0.2164099945650469
[I 2024-04-17 15:07:05,350] Trial 7 finished with value: 0.2114600323605552 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.18257976996986042
Fold 2 IBS: 0.19411505967038614
Fold 3 IBS: 0.17136720904530045
Fold 4 IBS: 0.17268722966186423
Fold 5 IBS: 0.21366089922807047
[I 2024-04-17 15:07:06,505] Trial 8 finished with value: 0.18688203351509633 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.21317294453259816
Fold 2 IBS: 0.21979053165324058
Fold 3 IBS: 0.20367290529718618
Fold 4 IBS: 0.22322856514743522
Fold 5 IBS: 0.21829561184880927
[I 2024-04-17 15:07:16,679] Trial 9 finished with value: 0.2156321116958539 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.2139727346768592
Fold 2 IBS: 0.2213120202940904
Fold 3 IBS: 0.20503568053719107
Fold 4 IBS: 0.2245613118501098
Fold 5 IBS: 0.21766314539351875
[I 2024-04-17 15:07:28,593] Trial 10 finished with value: 0.21650897855035384 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.194147789023279, 'min_weight_fraction_leaf': 0.20179400484263296}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.19343732165265656
Fold 2 IBS: 0.18906543074097565
Fold 3 IBS: 0.17814248070868705
Fold 4 IBS: 0.17824816439818994
Fold 5 IBS: 0.2121006857387383
[I 2024-04-17 15:07:31,179] Trial 11 finished with value: 0.1901988166478495 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 111, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9547450918366839, 'min_weight_fraction_leaf': 0.13052158247107556}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.1889048827611632
Fold 2 IBS: 0.19557019296937925
Fold 3 IBS: 0.1711785441540699
Fold 4 IBS: 0.1739105142666198
Fold 5 IBS: 0.21378813670908908
[I 2024-04-17 15:07:34,781] Trial 12 finished with value: 0.18867045417206424 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 176, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6665600668811549, 'min_weight_fraction_leaf': 0.07739259194541037}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.21602403915542812
Fold 2 IBS: 0.22135942967444958
Fold 3 IBS: 0.207522129090302
Fold 4 IBS: 0.22681102026289354
Fold 5 IBS: 0.2196363896884173
[I 2024-04-17 15:07:35,394] Trial 13 finished with value: 0.21827060157429812 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 2, 'n_estimators': 7, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.33474644057405917, 'min_weight_fraction_leaf': 0.1768405475625161}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.1908749026630227
Fold 2 IBS: 0.1928239743663976
Fold 3 IBS: 0.16705801079598037
Fold 4 IBS: 0.15060359337075535
Fold 5 IBS: 0.22085198243745763
[I 2024-04-17 15:07:38,829] Trial 14 finished with value: 0.18444249272672272 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 142, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8615610863035676, 'min_weight_fraction_leaf': 0.00662188941038383}. Best is trial 14 with value: 0.18444249272672272.

Fold 1 IBS: 0.18383586845275063
Fold 2 IBS: 0.2000835973214874
Fold 3 IBS: 0.15349960014749967
Fold 4 IBS: 0.13669669509253474
Fold 5 IBS: 0.23424660843190576
[I 2024-04-17 15:07:48,368] Trial 15 finished with value: 0.18167247388923563 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 264, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9163782618183121, 'min_weight_fraction_leaf': 0.0023088139988564262}. Best is trial 15 with value: 0.18167247388923563.
Fold 1 IBS: 0.1860236953856494
Fold 2 IBS: 0.2016030715036904
Fold 3 IBS: 0.155469005191737
Fold 4 IBS: 0.13731033566044606
Fold 5 IBS: 0.22747010982683524
[I 2024-04-17 15:07:57,935] Trial 16 finished with value: 0.1815752435136716 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8957765840335672, 'min_weight_fraction_leaf': 0.010191311991891749}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.17998535045197436
Fold 2 IBS: 0.18813498335112747
Fold 3 IBS: 0.17047606760378545
Fold 4 IBS: 0.18020967518371683
Fold 5 IBS: 0.21407585022837167
[I 2024-04-17 15:08:04,034] Trial 17 finished with value: 0.18657638536379517 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 246, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9042785918294833, 'min_weight_fraction_leaf': 0.42038595995868033}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.21392851730727483
Fold 2 IBS: 0.2203112302740686
Fold 3 IBS: 0.20531706619567533
Fold 4 IBS: 0.22509036885374237
Fold 5 IBS: 0.21706040157641074
[I 2024-04-17 15:08:11,725] Trial 18 finished with value: 0.21634151684143438 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 312, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.22508105757456376}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.1780064255903332
Fold 2 IBS: 0.1911276300331187
Fold 3 IBS: 0.16786438905278223
Fold 4 IBS: 0.1726113214449123
Fold 5 IBS: 0.21667391270579664
[I 2024-04-17 15:08:17,264] Trial 19 finished with value: 0.18525673576538862 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 240, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6895543806821031, 'min_weight_fraction_leaf': 0.3097789443945588}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.17575403131452658
Fold 2 IBS: 0.20366539827290087
Fold 3 IBS: 0.1659331777904529
Fold 4 IBS: 0.16662123172048018
Fold 5 IBS: 0.2231823176617039
[I 2024-04-17 15:08:25,094] Trial 20 finished with value: 0.18703123135201288 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 352, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8867517870122669, 'min_weight_fraction_leaf': 0.3678346055590361}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18848376456042643
Fold 2 IBS: 0.18922500536261308
Fold 3 IBS: 0.1744885363823047
Fold 4 IBS: 0.16595205181867084
Fold 5 IBS: 0.2141373046342922
[I 2024-04-17 15:08:27,611] Trial 21 finished with value: 0.18645733255166147 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 112, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8638184920383039, 'min_weight_fraction_leaf': 0.006217904257385862}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18773929580856016
Fold 2 IBS: 0.18598260697487606
Fold 3 IBS: 0.16906412373747556
Fold 4 IBS: 0.16368622468310087
Fold 5 IBS: 0.21228289069902992
[I 2024-04-17 15:08:33,945] Trial 22 finished with value: 0.18375102838060853 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 286, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9916304513453179, 'min_weight_fraction_leaf': 0.04142928400152037}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18853550770642435
Fold 2 IBS: 0.18431558910147325
Fold 3 IBS: 0.1692342266159003
Fold 4 IBS: 0.161355478193544
Fold 5 IBS: 0.21536507583817294
[I 2024-04-17 15:08:40,315] Trial 23 finished with value: 0.18376117549110296 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.971566349397283, 'min_weight_fraction_leaf': 0.048431151398292585}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18850231376560317
Fold 2 IBS: 0.18839766190435636
Fold 3 IBS: 0.17219466449743842
Fold 4 IBS: 0.169776646003973
Fold 5 IBS: 0.21215306500728826
[I 2024-04-17 15:08:44,687] Trial 24 finished with value: 0.18620487023573185 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 213, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9955995613709457, 'min_weight_fraction_leaf': 0.09809641655746978}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.1921961203281156
Fold 2 IBS: 0.18453047987592264
Fold 3 IBS: 0.16816775310750728
Fold 4 IBS: 0.16025534556804477
Fold 5 IBS: 0.21319844694890142
[I 2024-04-17 15:08:51,792] Trial 25 finished with value: 0.18366962916569834 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 358, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8862362117578689, 'min_weight_fraction_leaf': 0.041224153446454304}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.17583280457561398
Fold 2 IBS: 0.22475673220665077
Fold 3 IBS: 0.15629098950451684
Fold 4 IBS: 0.1521771664224135
Fold 5 IBS: 0.23338728904188227
[I 2024-04-17 15:09:04,763] Trial 26 finished with value: 0.1884889963502155 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 360, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7252723068238901, 'min_weight_fraction_leaf': 0.16863579271898874}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.20101808740413787
Fold 2 IBS: 0.19364223596866614
Fold 3 IBS: 0.1581801817697089
Fold 4 IBS: 0.13490957896358
Fold 5 IBS: 0.22061607552916476
[I 2024-04-17 15:09:26,895] Trial 27 finished with value: 0.18167323192705154 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 380, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.845241798302616, 'min_weight_fraction_leaf': 0.027493332139652292}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18622176253816625
Fold 2 IBS: 0.1999255042061287
Fold 3 IBS: 0.15584044840112993
Fold 4 IBS: 0.13526516764544533
Fold 5 IBS: 0.22802733572495915
[I 2024-04-17 15:09:44,697] Trial 28 finished with value: 0.18105604370316586 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 388, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8292254352883182, 'min_weight_fraction_leaf': 0.0850371679063824}. Best is trial 28 with value: 0.18105604370316586.
Fold 1 IBS: 0.17657957905072683
Fold 2 IBS: 0.22919795735904133
Fold 3 IBS: 0.15929222778603266
Fold 4 IBS: 0.15524572509143825
Fold 5 IBS: 0.23445783766810277
[I 2024-04-17 15:09:55,524] Trial 29 finished with value: 0.19095466539106837 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 388, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7274266056837884, 'min_weight_fraction_leaf': 0.10433587359666342}. Best is trial 28 with value: 0.18105604370316586.

Fold 1 IBS: 0.18973195855840097
Fold 2 IBS: 0.19901752012782084
Fold 3 IBS: 0.1553163395473765
Fold 4 IBS: 0.13719070606611738
Fold 5 IBS: 0.22779776404493374
[I 2024-04-17 15:10:08,166] Trial 30 finished with value: 0.18181085766892985 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 305, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8220971907615917, 'min_weight_fraction_leaf': 0.076444606879153}. Best is trial 28 with value: 0.18105604370316586.
Fold 1 IBS: 0.2164877455822723
Fold 2 IBS: 0.18827035681808446
Fold 3 IBS: 0.16565039781780372
Fold 4 IBS: 0.1417428766421557
Fold 5 IBS: 0.21575647924950747
[I 2024-04-17 15:10:36,046] Trial 31 finished with value: 0.18558157122196473 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 394, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9184090898444338, 'min_weight_fraction_leaf': 0.024048041704110457}. Best is trial 28 with value: 0.18105604370316586.
Fold 1 IBS: 0.19225590417182326
Fold 2 IBS: 0.19791478229895018
Fold 3 IBS: 0.15389649317000442
Fold 4 IBS: 0.13656122267395734
Fold 5 IBS: 0.2252432881883185
[I 2024-04-17 15:10:49,502] Trial 32 finished with value: 0.18117433810061073 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 339, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8398341558075527, 'min_weight_fraction_leaf': 0.07586243370778376}. Best is trial 28 with value: 0.18105604370316586.
Fold 1 IBS: 0.190099017520626
Fold 2 IBS: 0.19508386306537273
Fold 3 IBS: 0.15693141894064483
Fold 4 IBS: 0.1365814363126798
Fold 5 IBS: 0.2242513991199539
[I 2024-04-17 15:11:03,034] Trial 33 finished with value: 0.18058942699185546 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 328, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7393625680125055, 'min_weight_fraction_leaf': 0.0754095802252665}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1755388893326841
Fold 2 IBS: 0.22138923578766054
Fold 3 IBS: 0.15690295668954182
Fold 4 IBS: 0.1534002161724209
Fold 5 IBS: 0.23198506769187896
[I 2024-04-17 15:11:12,677] Trial 34 finished with value: 0.18784327313483729 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 327, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6411042409555412, 'min_weight_fraction_leaf': 0.1529713735680485}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18263254865306666
Fold 2 IBS: 0.20049141147500113
Fold 3 IBS: 0.1589092797218102
Fold 4 IBS: 0.13938245171749084
Fold 5 IBS: 0.22964090743188564
[I 2024-04-17 15:11:29,685] Trial 35 finished with value: 0.1822113197998509 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 437, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7381816364515512, 'min_weight_fraction_leaf': 0.09309533777806683}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.20497295855599004
Fold 2 IBS: 0.20576214803730022
Fold 3 IBS: 0.19198391113255453
Fold 4 IBS: 0.20085090326245184
Fold 5 IBS: 0.21341213707903006
[I 2024-04-17 15:11:36,315] Trial 36 finished with value: 0.2033964116134653 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 329, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6138083294843051, 'min_weight_fraction_leaf': 0.0629620770536272}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.19527602912356506
Fold 2 IBS: 0.19485558505510198
Fold 3 IBS: 0.18174564019749553
Fold 4 IBS: 0.1886871891677721
Fold 5 IBS: 0.21159832776451956
[I 2024-04-17 15:11:45,040] Trial 37 finished with value: 0.19443255426169087 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 415, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5042351390354268, 'min_weight_fraction_leaf': 0.11525786573963492}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.2123324981539864
Fold 2 IBS: 0.21873675502636114
Fold 3 IBS: 0.2026801887391686
Fold 4 IBS: 0.2224371860221609
Fold 5 IBS: 0.2175210624415119
[I 2024-04-17 15:11:49,491] Trial 38 finished with value: 0.21474153807663776 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 215, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7775660926270328, 'min_weight_fraction_leaf': 0.20133705660393178}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.21396615975925184
Fold 2 IBS: 0.22136475473478168
Fold 3 IBS: 0.2049150370158522
Fold 4 IBS: 0.22458804795980403
Fold 5 IBS: 0.21835431962555002
[I 2024-04-17 15:12:00,273] Trial 39 finished with value: 0.21663766381904798 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 8, 'n_estimators': 461, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.3933070032512962, 'min_weight_fraction_leaf': 0.26079682823609596}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.19711707736031672
Fold 2 IBS: 0.19196214561471756
Fold 3 IBS: 0.18237907022466343
Fold 4 IBS: 0.1838407369325067
Fold 5 IBS: 0.21066154976207546
[I 2024-04-17 15:12:07,192] Trial 40 finished with value: 0.19319211597885597 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 338, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7923253229666314, 'min_weight_fraction_leaf': 0.06421109758861666}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18187508975758154
Fold 2 IBS: 0.20470571701119905
Fold 3 IBS: 0.15462214843892588
Fold 4 IBS: 0.13791700485858222
Fold 5 IBS: 0.23199241229585657
[I 2024-04-17 15:12:16,813] Trial 41 finished with value: 0.18222247447242906 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 287, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9487776860553198, 'min_weight_fraction_leaf': 0.0012764688125286236}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18083474896839194
Fold 2 IBS: 0.20655297055486127
Fold 3 IBS: 0.1560859878078812
Fold 4 IBS: 0.13735104264690487
Fold 5 IBS: 0.2318981646914065
[I 2024-04-17 15:12:31,000] Trial 42 finished with value: 0.18254458293388914 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 410, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9263396365475575, 'min_weight_fraction_leaf': 0.07533198780818874}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.179220247667936
Fold 2 IBS: 0.20803479971941155
Fold 3 IBS: 0.15642984958925052
Fold 4 IBS: 0.1381823380575358
Fold 5 IBS: 0.23098585177667733
[I 2024-04-17 15:12:39,354] Trial 43 finished with value: 0.18257061736216224 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8260902726928496, 'min_weight_fraction_leaf': 0.12086835806486591}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.20295458389503712
Fold 2 IBS: 0.18760128987987226
Fold 3 IBS: 0.16259754916275176
Fold 4 IBS: 0.13943881701142766
Fold 5 IBS: 0.21929671791406735
[I 2024-04-17 15:12:49,818] Trial 44 finished with value: 0.18237779157263123 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 269, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.755115496265169, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 33 with value: 0.18058942699185546.

Fold 1 IBS: 0.21196016007242774
Fold 2 IBS: 0.21737810285668177
Fold 3 IBS: 0.20221519268515586
Fold 4 IBS: 0.21985834792032022
Fold 5 IBS: 0.21707100228614096
[I 2024-04-17 15:12:53,990] Trial 45 finished with value: 0.21369656116414532 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 226, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5998350649536632, 'min_weight_fraction_leaf': 0.05464331917294846}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18076053104236317
Fold 2 IBS: 0.2172100382529918
Fold 3 IBS: 0.15472808053026357
Fold 4 IBS: 0.14511587127121353
Fold 5 IBS: 0.2339666086051307
[I 2024-04-17 15:12:59,694] Trial 46 finished with value: 0.18635622594039253 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 185, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8402810693773478, 'min_weight_fraction_leaf': 0.144161655351996}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18818806948138703
Fold 2 IBS: 0.18585276291120573
Fold 3 IBS: 0.16931029735325712
Fold 4 IBS: 0.16495818665843412
Fold 5 IBS: 0.21221551295471194
[I 2024-04-17 15:13:05,383] Trial 47 finished with value: 0.1841049658717992 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 294, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9302813606785956, 'min_weight_fraction_leaf': 0.08930568525499841}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18928681061078317
Fold 2 IBS: 0.19449353516562573
Fold 3 IBS: 0.15782262613968703
Fold 4 IBS: 0.13927270133528777
Fold 5 IBS: 0.22728509464662824
[I 2024-04-17 15:13:19,221] Trial 48 finished with value: 0.1816321535796024 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 374, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7058374194287877, 'min_weight_fraction_leaf': 0.021185992511726287}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.20695865791961138
Fold 2 IBS: 0.18446003189676
Fold 3 IBS: 0.1637203264374506
Fold 4 IBS: 0.14167171912108306
Fold 5 IBS: 0.21852048251093703
[I 2024-04-17 15:13:35,771] Trial 49 finished with value: 0.18306624357716844 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 371, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6944137175640025, 'min_weight_fraction_leaf': 0.023748345961229673}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.20395296501568036
Fold 2 IBS: 0.20356332435883023
Fold 3 IBS: 0.19198232817565247
Fold 4 IBS: 0.20503408115744123
Fold 5 IBS: 0.212977623601451
[I 2024-04-17 15:13:46,466] Trial 50 finished with value: 0.20350206446181107 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 475, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5323261217237781, 'min_weight_fraction_leaf': 0.1282263128781066}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1892478776386835
Fold 2 IBS: 0.1985691975751118
Fold 3 IBS: 0.1551366953595447
Fold 4 IBS: 0.13797047291334816
Fold 5 IBS: 0.2247976743236853
[I 2024-04-17 15:13:58,577] Trial 51 finished with value: 0.18114438356207468 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 336, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7991896596470566, 'min_weight_fraction_leaf': 0.020902281449632076}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18966875407315306
Fold 2 IBS: 0.20026668125593905
Fold 3 IBS: 0.1581902551783595
Fold 4 IBS: 0.1446898271378981
Fold 5 IBS: 0.22398935878186912
[I 2024-04-17 15:14:10,603] Trial 52 finished with value: 0.18336097528544376 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 340, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7963262944115481, 'min_weight_fraction_leaf': 0.06178807863600248}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1808545696000534
Fold 2 IBS: 0.2092001659472061
Fold 3 IBS: 0.1569134957561024
Fold 4 IBS: 0.14354275776617909
Fold 5 IBS: 0.23138632547295945
[I 2024-04-17 15:14:20,626] Trial 53 finished with value: 0.1843794629085001 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 310, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6795691608327338, 'min_weight_fraction_leaf': 0.028449876548026755}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18963311160047724
Fold 2 IBS: 0.20900009168815242
Fold 3 IBS: 0.15966211681395587
Fold 4 IBS: 0.14477830095268193
Fold 5 IBS: 0.2227272285777302
[I 2024-04-17 15:14:33,933] Trial 54 finished with value: 0.18516016992659953 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 373, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8793032020733721, 'min_weight_fraction_leaf': 0.07859078488282405}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1844153405050917
Fold 2 IBS: 0.20329447035960194
Fold 3 IBS: 0.156445527494686
Fold 4 IBS: 0.1385632327057539
Fold 5 IBS: 0.2286479785748904
[I 2024-04-17 15:14:45,995] Trial 55 finished with value: 0.18227330992800478 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 343, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7615617181298988, 'min_weight_fraction_leaf': 0.0463333928046309}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.21398416445233792
Fold 2 IBS: 0.22128642959017203
Fold 3 IBS: 0.20479170826088208
Fold 4 IBS: 0.22465474077969866
Fold 5 IBS: 0.21866500422066165
[I 2024-04-17 15:14:54,746] Trial 56 finished with value: 0.21667640946075045 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 397, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7048250986458913, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.19154362908633138
Fold 2 IBS: 0.19025716940029977
Fold 3 IBS: 0.164641271809976
Fold 4 IBS: 0.1535983543533534
Fold 5 IBS: 0.21130984092669008
[I 2024-04-17 15:15:02,650] Trial 57 finished with value: 0.18227005311533012 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 325, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6509352527427404, 'min_weight_fraction_leaf': 0.01668177754116703}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1834614522490023
Fold 2 IBS: 0.20274762979546487
Fold 3 IBS: 0.1558259112444169
Fold 4 IBS: 0.13699785208498225
Fold 5 IBS: 0.227941946402463
[I 2024-04-17 15:15:15,358] Trial 58 finished with value: 0.18139495835526587 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 361, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8149000200033439, 'min_weight_fraction_leaf': 0.1073613839314761}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18264043127662102
Fold 2 IBS: 0.20563295068882514
Fold 3 IBS: 0.15774830297383735
Fold 4 IBS: 0.1409283130574975
Fold 5 IBS: 0.2302026151594693
[I 2024-04-17 15:15:30,311] Trial 59 finished with value: 0.18343052263125006 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 433, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.806842099370764, 'min_weight_fraction_leaf': 0.11194912742691053}. Best is trial 33 with value: 0.18058942699185546.

Fold 1 IBS: 0.1940353275621495
Fold 2 IBS: 0.19268012360689624
Fold 3 IBS: 0.18110607070067974
Fold 4 IBS: 0.18845548212963192
Fold 5 IBS: 0.2126254989546211
[I 2024-04-17 15:15:37,337] Trial 60 finished with value: 0.1937805005907957 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 305, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8575527275336559, 'min_weight_fraction_leaf': 0.18982981109623043}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1881809892682945
Fold 2 IBS: 0.19390719781855054
Fold 3 IBS: 0.1588739037458674
Fold 4 IBS: 0.1367801254919651
Fold 5 IBS: 0.2266847482237021
[I 2024-04-17 15:15:50,638] Trial 61 finished with value: 0.18088539290967592 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7615189086372551, 'min_weight_fraction_leaf': 0.04095649181576018}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1876754810451395
Fold 2 IBS: 0.19768374549602719
Fold 3 IBS: 0.15918815613876297
Fold 4 IBS: 0.13767028389195304
Fold 5 IBS: 0.22732368447379522
[I 2024-04-17 15:16:03,889] Trial 62 finished with value: 0.18190827020913558 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 354, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7661278291112643, 'min_weight_fraction_leaf': 0.08934183246037483}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18158763535398614
Fold 2 IBS: 0.2058728330109782
Fold 3 IBS: 0.15634716717840097
Fold 4 IBS: 0.1393411349809578
Fold 5 IBS: 0.2305445348222664
[I 2024-04-17 15:16:19,066] Trial 63 finished with value: 0.18273866106931788 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 411, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8238233376692735, 'min_weight_fraction_leaf': 0.05246336243742043}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.17660125627972975
Fold 2 IBS: 0.19950632480062638
Fold 3 IBS: 0.16593947035609424
Fold 4 IBS: 0.1676045776632834
Fold 5 IBS: 0.2238259008995345
[I 2024-04-17 15:16:30,429] Trial 64 finished with value: 0.18669550599985366 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 396, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8942985122180038, 'min_weight_fraction_leaf': 0.3739424140604035}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.17841559751185995
Fold 2 IBS: 0.2181576301923148
Fold 3 IBS: 0.15699607135742621
Fold 4 IBS: 0.14279995324086395
Fold 5 IBS: 0.23321351389303
[I 2024-04-17 15:16:41,625] Trial 65 finished with value: 0.185916553239099 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 321, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8550412886514629, 'min_weight_fraction_leaf': 0.157443472337933}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.21396919511710527
Fold 2 IBS: 0.22118312582133598
Fold 3 IBS: 0.20498660484161652
Fold 4 IBS: 0.22465182954726737
Fold 5 IBS: 0.218115813183982
[I 2024-04-17 15:16:49,553] Trial 66 finished with value: 0.21658131370226147 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 452, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.30029194568874296, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18873872659716473
Fold 2 IBS: 0.18791922078055107
Fold 3 IBS: 0.16453860462735764
Fold 4 IBS: 0.15207602931399142
Fold 5 IBS: 0.20920273391154215
[I 2024-04-17 15:16:59,016] Trial 67 finished with value: 0.18049506304612142 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 363, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7471014922297948, 'min_weight_fraction_leaf': 0.03879604091198421}. Best is trial 67 with value: 0.18049506304612142.
Fold 1 IBS: 0.18615572700917984
Fold 2 IBS: 0.1920922899342238
Fold 3 IBS: 0.1645126632956227
Fold 4 IBS: 0.15374635033745812
Fold 5 IBS: 0.21328354527729806
[I 2024-04-17 15:17:08,238] Trial 68 finished with value: 0.1819581151707565 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7411630198194591, 'min_weight_fraction_leaf': 0.0741944771835793}. Best is trial 67 with value: 0.18049506304612142.
Fold 1 IBS: 0.19221322343005157
Fold 2 IBS: 0.18747725704463866
Fold 3 IBS: 0.16271946974327306
Fold 4 IBS: 0.14893868190888562
Fold 5 IBS: 0.21053329237786875
[I 2024-04-17 15:17:18,604] Trial 69 finished with value: 0.18037638490094354 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 344, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873531668221723, 'min_weight_fraction_leaf': 0.03743740450038523}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.19123449448406776
Fold 2 IBS: 0.18634187192427262
Fold 3 IBS: 0.16568962439316362
Fold 4 IBS: 0.14733219858236207
Fold 5 IBS: 0.2124042387639548
[I 2024-04-17 15:17:28,575] Trial 70 finished with value: 0.18060048562956416 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 342, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7884602797651743, 'min_weight_fraction_leaf': 0.03984902133772039}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.19415415468436753
Fold 2 IBS: 0.1861415676999523
Fold 3 IBS: 0.16573890197473515
Fold 4 IBS: 0.14488999289270504
Fold 5 IBS: 0.2125204407894076
[I 2024-04-17 15:17:39,539] Trial 71 finished with value: 0.18068901160823353 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 343, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7819431269555398, 'min_weight_fraction_leaf': 0.03595825517448436}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.18984009710041735
Fold 2 IBS: 0.18778536549020883
Fold 3 IBS: 0.16555752286430367
Fold 4 IBS: 0.15132302702120518
Fold 5 IBS: 0.21187635057748866
[I 2024-04-17 15:17:51,093] Trial 72 finished with value: 0.18127647261072471 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 379, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7158237789595601, 'min_weight_fraction_leaf': 0.038892933150377174}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.19217054361716007
Fold 2 IBS: 0.18605477551854072
Fold 3 IBS: 0.1657195529075007
Fold 4 IBS: 0.1499033271314654
Fold 5 IBS: 0.21296314297306798
[I 2024-04-17 15:18:00,648] Trial 73 finished with value: 0.18136226842954697 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 348, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7776848187295278, 'min_weight_fraction_leaf': 0.041701970157165584}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.1919591413798442
Fold 2 IBS: 0.18680709380802085
Fold 3 IBS: 0.16611125142067912
Fold 4 IBS: 0.14880604710483025
Fold 5 IBS: 0.20779386416865475
[I 2024-04-17 15:18:09,667] Trial 74 finished with value: 0.18029547957640585 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 297, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7429251540613239, 'min_weight_fraction_leaf': 0.034122782806489685}. Best is trial 74 with value: 0.18029547957640585.

Fold 1 IBS: 0.20438643925191893
Fold 2 IBS: 0.1844312624795873
Fold 3 IBS: 0.17002168747641047
Fold 4 IBS: 0.14791525733420058
Fold 5 IBS: 0.21362624602582111
[I 2024-04-17 15:18:19,425] Trial 75 finished with value: 0.18407617851358768 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 296, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6651148142523113, 'min_weight_fraction_leaf': 0.0005666053087619444}. Best is trial 74 with value: 0.18029547957640585.
Fold 1 IBS: 0.19306514020322818
Fold 2 IBS: 0.1842925536567217
Fold 3 IBS: 0.16281493341095712
Fold 4 IBS: 0.15026196851923793
Fold 5 IBS: 0.20907571723485416
[I 2024-04-17 15:18:27,634] Trial 76 finished with value: 0.1799020626049998 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 273, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6121072626884605, 'min_weight_fraction_leaf': 0.0375652827686181}. Best is trial 76 with value: 0.1799020626049998.
Fold 1 IBS: 0.19533191990808643
Fold 2 IBS: 0.18454077801628752
Fold 3 IBS: 0.16320484107502187
Fold 4 IBS: 0.14544314028091127
Fold 5 IBS: 0.2072692252418508
[I 2024-04-17 15:18:38,187] Trial 77 finished with value: 0.17915798090443158 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 275, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6024939881120506, 'min_weight_fraction_leaf': 0.03546615930788915}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.18979383260600338
Fold 2 IBS: 0.18481018797624196
Fold 3 IBS: 0.16409936588525315
Fold 4 IBS: 0.1553259082203432
Fold 5 IBS: 0.21243305321372438
[I 2024-04-17 15:18:46,794] Trial 78 finished with value: 0.18129246958031323 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 242, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6205262617833929, 'min_weight_fraction_leaf': 0.06309017855153265}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.1918516718483265
Fold 2 IBS: 0.18449081490872005
Fold 3 IBS: 0.1634428327969914
Fold 4 IBS: 0.14997364872576785
Fold 5 IBS: 0.20763662708758918
[I 2024-04-17 15:18:54,515] Trial 79 finished with value: 0.17947911907347897 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 273, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5944767216434486, 'min_weight_fraction_leaf': 0.03643432579651321}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.19348005656430173
Fold 2 IBS: 0.18296399211241365
Fold 3 IBS: 0.16491035077279387
Fold 4 IBS: 0.1455645707584685
Fold 5 IBS: 0.21079082139142424
[I 2024-04-17 15:19:02,750] Trial 80 finished with value: 0.1795419583198804 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 281, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5738838339262928, 'min_weight_fraction_leaf': 0.01238447949116667}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.19385166663658865
Fold 2 IBS: 0.1878440819583883
Fold 3 IBS: 0.165800948446184
Fold 4 IBS: 0.1476511958697635
Fold 5 IBS: 0.21025560153134265
[I 2024-04-17 15:19:10,502] Trial 81 finished with value: 0.1810806988884534 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 274, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5619354088357825, 'min_weight_fraction_leaf': 0.01565582556320865}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.18524833693093437
Fold 2 IBS: 0.19165170252652822
Fold 3 IBS: 0.16392769525776144
Fold 4 IBS: 0.15846496418540476
Fold 5 IBS: 0.2094683241817906
[I 2024-04-17 15:19:16,627] Trial 82 finished with value: 0.1817522046164839 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 232, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.4638072011147492, 'min_weight_fraction_leaf': 0.05201742843067371}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.19237185503026552
Fold 2 IBS: 0.18676559841777626
Fold 3 IBS: 0.16407017518328942
Fold 4 IBS: 0.1449765914249507
Fold 5 IBS: 0.20892364253609055
[I 2024-04-17 15:19:24,178] Trial 83 finished with value: 0.1794215725184745 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 275, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5992998998564371, 'min_weight_fraction_leaf': 0.011892575602326625}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.19394142912089907
Fold 2 IBS: 0.18287172537269059
Fold 3 IBS: 0.16363670208229797
Fold 4 IBS: 0.14366900591399753
Fold 5 IBS: 0.20892071259321834
[I 2024-04-17 15:19:31,975] Trial 84 finished with value: 0.1786079150166207 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 255, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5921978094028723, 'min_weight_fraction_leaf': 0.010779734440848038}. Best is trial 84 with value: 0.1786079150166207.
Fold 1 IBS: 0.1934701576048722
Fold 2 IBS: 0.18356601291714442
Fold 3 IBS: 0.16350384856124178
Fold 4 IBS: 0.14362897455716736
Fold 5 IBS: 0.20935617313715904
[I 2024-04-17 15:19:38,658] Trial 85 finished with value: 0.17870503335551696 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 250, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.595683013252236, 'min_weight_fraction_leaf': 0.005599104949055786}. Best is trial 84 with value: 0.1786079150166207.
Fold 1 IBS: 0.191846570784011
Fold 2 IBS: 0.18680840183499514
Fold 3 IBS: 0.1640377893844091
Fold 4 IBS: 0.14812980552665286
Fold 5 IBS: 0.21175031324864774
[I 2024-04-17 15:19:45,716] Trial 86 finished with value: 0.18051457615574318 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 254, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5360572837412131, 'min_weight_fraction_leaf': 0.01185351158382457}. Best is trial 84 with value: 0.1786079150166207.
Fold 1 IBS: 0.19147665396547064
Fold 2 IBS: 0.18176345202270439
Fold 3 IBS: 0.16414261135311045
Fold 4 IBS: 0.15299647769153543
Fold 5 IBS: 0.2087010317651242
[I 2024-04-17 15:19:53,221] Trial 87 finished with value: 0.17981604535958903 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 281, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5878837691778286, 'min_weight_fraction_leaf': 0.008079079463688634}. Best is trial 84 with value: 0.1786079150166207.
Fold 1 IBS: 0.1914457217244506
Fold 2 IBS: 0.18052086391051203
Fold 3 IBS: 0.16215789222067095
Fold 4 IBS: 0.15081933866613106
Fold 5 IBS: 0.20784710369879605
[I 2024-04-17 15:20:00,462] Trial 88 finished with value: 0.1785581840441121 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 279, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5945245081220258, 'min_weight_fraction_leaf': 0.006841645987133443}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19147665396547064
Fold 2 IBS: 0.18176345202270439
Fold 3 IBS: 0.16414261135311045
Fold 4 IBS: 0.15299647769153543
Fold 5 IBS: 0.2087010317651242
[I 2024-04-17 15:20:08,014] Trial 89 finished with value: 0.17981604535958903 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 281, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.585692212182858, 'min_weight_fraction_leaf': 0.0008838182441561699}. Best is trial 88 with value: 0.1785581840441121.

Fold 1 IBS: 0.19250257566167933
Fold 2 IBS: 0.18261531719008467
Fold 3 IBS: 0.16180974496548703
Fold 4 IBS: 0.14890218044290915
Fold 5 IBS: 0.2130135609453814
[I 2024-04-17 15:20:13,466] Trial 90 finished with value: 0.1797686758411083 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 202, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5935532822743834, 'min_weight_fraction_leaf': 0.007362099342399538}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19466401388017032
Fold 2 IBS: 0.18486336673650017
Fold 3 IBS: 0.16588446237479346
Fold 4 IBS: 0.1465134541216928
Fold 5 IBS: 0.21287370502296324
[I 2024-04-17 15:20:18,788] Trial 91 finished with value: 0.18095980042722398 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 197, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5826023797451899, 'min_weight_fraction_leaf': 0.00862038165347273}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19077050579200147
Fold 2 IBS: 0.18831329801859226
Fold 3 IBS: 0.16406961249991853
Fold 4 IBS: 0.14929003357858256
Fold 5 IBS: 0.21018706108863028
[I 2024-04-17 15:20:26,159] Trial 92 finished with value: 0.18052610219554502 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 252, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5070555008286651, 'min_weight_fraction_leaf': 0.009333694056201223}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.1942451581816268
Fold 2 IBS: 0.1830703742457603
Fold 3 IBS: 0.16097178413138724
Fold 4 IBS: 0.14654845241459755
Fold 5 IBS: 0.2121967833645088
[I 2024-04-17 15:20:33,559] Trial 93 finished with value: 0.17940651046757616 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 221, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5934768503177845, 'min_weight_fraction_leaf': 0.014878777313562812}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19736082973729024
Fold 2 IBS: 0.18309515782891686
Fold 3 IBS: 0.16366471911833752
Fold 4 IBS: 0.14526303100181923
Fold 5 IBS: 0.21417837651704477
[I 2024-04-17 15:20:39,348] Trial 94 finished with value: 0.18071242284068173 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 165, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6349033637819771, 'min_weight_fraction_leaf': 0.019343000331144743}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.18578897328440416
Fold 2 IBS: 0.19239898124845878
Fold 3 IBS: 0.1616809082216946
Fold 4 IBS: 0.15362867068252217
Fold 5 IBS: 0.21229660365479858
[I 2024-04-17 15:20:46,442] Trial 95 finished with value: 0.18115882741837566 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 217, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5448232910672774, 'min_weight_fraction_leaf': 0.025610081517443647}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.18377286728444794
Fold 2 IBS: 0.18906137730159184
Fold 3 IBS: 0.162592162450128
Fold 4 IBS: 0.15646349234384718
Fold 5 IBS: 0.21273640937582883
[I 2024-04-17 15:20:53,675] Trial 96 finished with value: 0.18092526175116874 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 200, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5166375602788441, 'min_weight_fraction_leaf': 0.01004295110119176}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19320716981789404
Fold 2 IBS: 0.1833817504678623
Fold 3 IBS: 0.16276222353530903
Fold 4 IBS: 0.15005917812838457
Fold 5 IBS: 0.21149567165602431
[I 2024-04-17 15:20:59,730] Trial 97 finished with value: 0.18018119872109484 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 230, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5810941412605699, 'min_weight_fraction_leaf': 0.028715470907523112}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19665218645247226
Fold 2 IBS: 0.18461786549962422
Fold 3 IBS: 0.16585865869273442
Fold 4 IBS: 0.14468826763530046
Fold 5 IBS: 0.20808627775303898
[I 2024-04-17 15:21:06,527] Trial 98 finished with value: 0.17998065120663406 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 246, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.558904433592998, 'min_weight_fraction_leaf': 0.0007593749444425981}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19225977892006962
Fold 2 IBS: 0.19011577254533654
Fold 3 IBS: 0.1738613054687569
Fold 4 IBS: 0.1638041351036002
Fold 5 IBS: 0.2130479662700931
[I 2024-04-17 15:21:10,170] Trial 99 finished with value: 0.18661779166157128 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 137, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4718103481231686, 'min_weight_fraction_leaf': 0.013594026171513878}. Best is trial 88 with value: 0.1785581840441121.


* Best trial for IBS:
 FrozenTrial(number=88, state=TrialState.COMPLETE, values=[0.1785581840441121], datetime_start=datetime.datetime(2024, 4, 17, 15, 19, 53, 227580), datetime_complete=datetime.datetime(2024, 4, 17, 15, 20, 0, 461097), params={'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 279, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5945245081220258, 'min_weight_fraction_leaf': 0.006841645987133443}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=88, value=None)


* Best Score for IBS:
 0.1785581840441121

In [59]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [60]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.886
train_ibs:  0.179

#### Test

In [61]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [62]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=9, max_features=None, max_leaf_nodes=14,
                   max_samples=0.965941994806725, min_samples_split=7,
                   min_weight_fraction_leaf=0.017267854864073284,
                   n_estimators=336, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.662

ExtraSurvivalTrees(max_depth=9, max_features=0.1, max_leaf_nodes=20,
                   max_samples=0.5945245081220258, min_samples_leaf=4,
                   min_samples_split=12,
                   min_weight_fraction_leaf=0.006841645987133443,
                   n_estimators=279, oob_score=True, random_state=123,
                   warm_start=True)

IBS: 0.2

In [63]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [64]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 15:21:16,969] A new study created in memory with name: no-name-93146a56-b3f2-489d-8d88-b620f932a289

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:22:08,466] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:22:32,530] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:23:02,746] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:24:08,181] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:24:33,614] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:24:39,961] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:25:14,330] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:25:23,680] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:25:25,071] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 15:27:22,374] Trial 9 finished with value: 0.7375077219334873 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 15:30:23,553] Trial 10 finished with value: 0.6769991466942861 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:33:47,317] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.715962441314554
[I 2024-04-17 15:36:43,196] Trial 12 finished with value: 0.7180894810070741 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:38:04,375] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:39:46,404] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:41:42,691] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:42:39,084] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:44:46,326] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:47:36,295] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:47:47,144] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:49:10,346] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.6384976525821596
[I 2024-04-17 15:51:48,183] Trial 21 finished with value: 0.6596743990023763 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8236607142857143
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.7447257383966245
Fold 5 C-index: 0.6830985915492958
[I 2024-04-17 15:54:11,534] Trial 22 finished with value: 0.7577518089481858 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:56:04,503] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:58:21,491] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.7577518089481858.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:59:33,957] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5654008438818565
Fold 5 C-index: 0.5821596244131455
[I 2024-04-17 16:01:26,855] Trial 26 finished with value: 0.5295120936590003 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:03:19,940] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:05:03,936] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:06:10,637] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:07:51,143] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.7075892857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6118143459915611
Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 16:10:52,706] Trial 31 finished with value: 0.6975838362663174 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:13:40,646] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9113568740147856, 'learning_rate': 0.01936213758007274, 'dropout_rate': 0.1444594228310892, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 1.6183832787391992, 'min_weight_fraction_leaf': 0.4304319218036696, 'max_features': 'auto', 'min_impurity_decrease': 1.0277484189219154e-07, 'validation_fraction': 0.9117669993681574, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:16:10,081] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9728428556912192, 'learning_rate': 0.015742740923125064, 'dropout_rate': 0.30020186346124766, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 9.846141209805609, 'min_weight_fraction_leaf': 0.4958404435609285, 'max_features': 'auto', 'min_impurity_decrease': 2.2786499479002052e-07, 'validation_fraction': 0.8344453462672722, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:17:46,923] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.8496036715186095, 'learning_rate': 0.009253864701923034, 'dropout_rate': 0.22658656718653286, 'n_estimators': 403, 'criterion': 'friedman_mse', 'ccp_alpha': 0.641857272630336, 'min_weight_fraction_leaf': 0.43629024868714544, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9168532630851701, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:18:16,068] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.6806458891075314, 'learning_rate': 0.0016219483573201542, 'dropout_rate': 0.4078621112435248, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3706867126320781, 'max_features': None, 'min_impurity_decrease': 7.8587698841458e-07, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:20:48,779] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.9551502281749775, 'learning_rate': 0.026078126474550274, 'dropout_rate': 0.34789169882120996, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.40891402270131877, 'min_weight_fraction_leaf': 0.2325827619040188, 'max_features': 'auto', 'min_impurity_decrease': 7.145093229830912e-06, 'validation_fraction': 0.6747809687204889, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:21:02,337] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.7371581418455209, 'learning_rate': 0.0145417341576766, 'dropout_rate': 0.16172130996739253, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.3174537146690439, 'max_features': None, 'min_impurity_decrease': 2.89190119114804e-07, 'validation_fraction': 0.9548743578197549, 'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:21:57,117] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.8063221166350547, 'learning_rate': 0.006424315075939495, 'dropout_rate': 0.7673236646699829, 'n_estimators': 329, 'criterion': 'friedman_mse', 'ccp_alpha': 9.162989248724866, 'min_weight_fraction_leaf': 0.14601082900734919, 'max_features': 'auto', 'min_impurity_decrease': 1.1529415174162498e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:23:43,831] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.8852748015168422, 'learning_rate': 0.02975783779377629, 'dropout_rate': 0.2673592786040255, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 1.1216454788806307, 'min_weight_fraction_leaf': 0.09194334498965648, 'max_features': 1, 'min_impurity_decrease': 8.588272604740831e-07, 'validation_fraction': 0.7628102853958754, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:25:05,997] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.5809866593286652, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.20816102573612866, 'n_estimators': 353, 'criterion': 'squared_error', 'ccp_alpha': 3.7898554763179284, 'min_weight_fraction_leaf': 0.4711996214427754, 'max_features': 'auto', 'min_impurity_decrease': 2.3584088371991464e-07, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5907172995780591
Fold 5 C-index: 0.5821596244131455
[I 2024-04-17 16:25:06,501] Trial 41 finished with value: 0.6152707311185872 and parameters: {'subsample': 0.9964498482283193, 'learning_rate': 0.004158109708816752, 'dropout_rate': 0.13644226542045526, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4011310798872364, 'max_features': 'auto', 'min_impurity_decrease': 1.0090377437612141e-07, 'validation_fraction': 0.9993318631652353, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:27:40,441] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.10858843727097561, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.415120560514267, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9524403904515271, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:28:40,389] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.919916216831853, 'learning_rate': 0.0016321845585985228, 'dropout_rate': 0.16429624388711278, 'n_estimators': 284, 'criterion': 'squared_error', 'ccp_alpha': 0.471921644995546, 'min_weight_fraction_leaf': 0.3704175909956657, 'max_features': 'auto', 'min_impurity_decrease': 0.0009050261380449993, 'validation_fraction': 0.8779568222622545, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:30:11,594] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.998598837606123, 'learning_rate': 0.015327765728784649, 'dropout_rate': 0.6859431566383477, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 1.2679892492803537, 'min_weight_fraction_leaf': 0.2706416993480579, 'max_features': 'auto', 'min_impurity_decrease': 8.738793222106795e-07, 'validation_fraction': 0.9744834265061879, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 16:31:38,668] Trial 45 finished with value: 0.7169525524273146 and parameters: {'subsample': 0.8612793275132423, 'learning_rate': 0.008591203396202965, 'dropout_rate': 0.20237082649972205, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 0.09266970930573763, 'min_weight_fraction_leaf': 0.4478112124993417, 'max_features': 0.1, 'min_impurity_decrease': 1.775469126785021e-07, 'validation_fraction': 0.798828420958444, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:31:50,586] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.8576868620948644, 'learning_rate': 0.021769927230194788, 'dropout_rate': 0.9694253886674298, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 1.9903431110600875, 'min_weight_fraction_leaf': 0.45430295635160706, 'max_features': 0.1, 'min_impurity_decrease': 2.0131584568637675e-06, 'validation_fraction': 0.7976029227783121, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:32:17,898] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7056873961179977, 'learning_rate': 0.00929853233926034, 'dropout_rate': 0.3140351257259953, 'n_estimators': 235, 'criterion': 'squared_error', 'ccp_alpha': 7.181314443016622, 'min_weight_fraction_leaf': 0.49464896810642006, 'max_features': 0.1, 'min_impurity_decrease': 2.1438208123963576e-05, 'validation_fraction': 0.6179698437276481, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:33:50,200] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.7837245323509484, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.21043558082214228, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.4617743734350054, 'min_weight_fraction_leaf': 0.45246089314517907, 'max_features': 0.1, 'min_impurity_decrease': 4.221379974644956e-07, 'validation_fraction': 0.863214331971344, 'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 7}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:34:34,360] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.6507081753968225, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.26780621294484797, 'n_estimators': 297, 'criterion': 'friedman_mse', 'ccp_alpha': 1.378218906104398, 'min_weight_fraction_leaf': 0.2916489694540698, 'max_features': 'log2', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6845184717076465, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:35:51,216] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.03353370774351387, 'dropout_rate': 0.3787195779305788, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.7561621193902213, 'min_weight_fraction_leaf': 0.47814765735031256, 'max_features': 0.1, 'min_impurity_decrease': 1.6961878462023105e-07, 'validation_fraction': 0.8310153288008191, 'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.6244131455399061
[I 2024-04-17 16:37:50,889] Trial 51 finished with value: 0.6982448681347772 and parameters: {'subsample': 0.9590755303360702, 'learning_rate': 0.001263628446733103, 'dropout_rate': 0.13293847894616523, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.012928318097826519, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6338028169014085
[I 2024-04-17 16:39:50,091] Trial 52 finished with value: 0.7007875648598147 and parameters: {'subsample': 0.9309483691931049, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.1309992574789837, 'n_estimators': 478, 'criterion': 'squared_error', 'ccp_alpha': 0.036615235505588, 'min_weight_fraction_leaf': 0.4052806656624778, 'max_features': 'sqrt', 'min_impurity_decrease': 2.8184597843569143e-07, 'validation_fraction': 0.8992446934973449, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:41:23,181] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.9119792149240027, 'learning_rate': 0.0011619738930768678, 'dropout_rate': 0.12019527221159815, 'n_estimators': 416, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.33436888398209985, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0912509934146174e-06, 'validation_fraction': 0.7204767494493249, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:41:55,438] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.9422391559777883, 'learning_rate': 0.006469543850280348, 'dropout_rate': 0.8266353856620614, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.46449392886564433, 'min_weight_fraction_leaf': 0.20818644825744925, 'max_features': 'sqrt', 'min_impurity_decrease': 3.17346833824979e-07, 'validation_fraction': 0.8741639290304148, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:43:27,874] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8715328822130523, 'learning_rate': 0.011790338191706525, 'dropout_rate': 0.23926982708415356, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 0.4008945876330496, 'min_weight_fraction_leaf': 0.44051010658711054, 'max_features': 'sqrt', 'min_impurity_decrease': 5.615119149330365e-07, 'validation_fraction': 0.7887577239921508, 'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:45:26,444] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.8015434219726096, 'learning_rate': 0.04061736247319854, 'dropout_rate': 0.1937709311352404, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 1.037591557618962, 'min_weight_fraction_leaf': 0.41307911755286036, 'max_features': 'sqrt', 'min_impurity_decrease': 1.854323715915516e-06, 'validation_fraction': 0.907633472782051, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 16:46:06,393] Trial 57 finished with value: 0.694941105261048 and parameters: {'subsample': 0.47167111494444647, 'learning_rate': 0.018997287630538016, 'dropout_rate': 0.5891903890315894, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.007297661499282945, 'min_weight_fraction_leaf': 0.37949114392069716, 'max_features': 'sqrt', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.5599065409082953, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:47:53,332] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.8972461919118405, 'learning_rate': 0.09671804411942064, 'dropout_rate': 0.10627978332234836, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.7590888481670788, 'min_weight_fraction_leaf': 0.25730821949204663, 'max_features': 'sqrt', 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.9487716255435797, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:49:27,396] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.8358264770513102, 'learning_rate': 0.022823901724539096, 'dropout_rate': 0.28631447973846014, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.429314535364776, 'min_weight_fraction_leaf': 0.3051539123714827, 'max_features': None, 'min_impurity_decrease': 5.131055724938468e-07, 'validation_fraction': 0.8437837761372522, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:50:22,485] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.22299455896998305, 'learning_rate': 0.0056069075336912105, 'dropout_rate': 0.3357871821335161, 'n_estimators': 376, 'criterion': 'squared_error', 'ccp_alpha': 2.523299286625464, 'min_weight_fraction_leaf': 0.339521597129798, 'max_features': 'sqrt', 'min_impurity_decrease': 2.9638541699067996e-07, 'validation_fraction': 0.6410967521884806, 'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:52:06,807] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.010928263297494037, 'dropout_rate': 0.1843386992247676, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.22729228144381666, 'min_weight_fraction_leaf': 0.4037400789999268, 'max_features': 1, 'min_impurity_decrease': 1.310082490250357e-07, 'validation_fraction': 0.9622895789424137, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 16:53:40,272] Trial 62 finished with value: 0.7272773109470696 and parameters: {'subsample': 0.9756177414915416, 'learning_rate': 0.00487963758524286, 'dropout_rate': 0.14510716910347804, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.023608499803350655, 'min_weight_fraction_leaf': 0.22961838496572504, 'max_features': 0.1, 'min_impurity_decrease': 1.6297128321880156e-07, 'validation_fraction': 0.8969787245486088, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:55:10,117] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.9288654416933328, 'learning_rate': 0.013829624766460978, 'dropout_rate': 0.13653478929605453, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 0.7247405887368557, 'min_weight_fraction_leaf': 0.22479730957902153, 'max_features': 0.1, 'min_impurity_decrease': 5.575423017349267e-07, 'validation_fraction': 0.8936351824952593, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:56:41,140] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.3944303299889498, 'learning_rate': 0.005756823204408979, 'dropout_rate': 0.2327252655551748, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.30460031424817835, 'min_weight_fraction_leaf': 0.1885535376775951, 'max_features': 0.1, 'min_impurity_decrease': 3.354219995894836e-07, 'validation_fraction': 0.9295137020256315, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 16:58:26,390] Trial 65 finished with value: 0.7220969706866847 and parameters: {'subsample': 0.8628229894737177, 'learning_rate': 0.008827661920605995, 'dropout_rate': 0.19214391420812213, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.002774143765696062, 'min_weight_fraction_leaf': 0.19849959041931706, 'max_features': 0.1, 'min_impurity_decrease': 2.5741032571081618e-06, 'validation_fraction': 0.81580153800389, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:00:23,619] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.7758851752296808, 'learning_rate': 0.009751888770788269, 'dropout_rate': 0.19122550095328222, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.898614500640199, 'min_weight_fraction_leaf': 0.15180913487925937, 'max_features': 0.1, 'min_impurity_decrease': 2.693782393576339e-06, 'validation_fraction': 0.8022828972461258, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 6}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:02:03,017] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8737277188190908, 'learning_rate': 0.017575803118928604, 'dropout_rate': 0.24650681062055632, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 1.184288941522344, 'min_weight_fraction_leaf': 0.20306006951316619, 'max_features': 0.1, 'min_impurity_decrease': 1.2046523007672827e-06, 'validation_fraction': 0.7485906145710193, 'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:03:21,192] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.819932305524277, 'learning_rate': 0.09136620662883123, 'dropout_rate': 0.21544296697082643, 'n_estimators': 401, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5667792373547914, 'min_weight_fraction_leaf': 0.24594914856187006, 'max_features': 0.1, 'min_impurity_decrease': 7.18785237781598e-07, 'validation_fraction': 0.8633504402260139, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:04:26,066] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.5360295416604122, 'learning_rate': 0.026072943824179864, 'dropout_rate': 0.15995252701068877, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 6.315803860540386, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': 0.1, 'min_impurity_decrease': 4.676506095993518e-06, 'validation_fraction': 0.8221337964376644, 'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:05:26,592] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.7391884515801697, 'learning_rate': 0.0131539926632262, 'dropout_rate': 0.4370458221877003, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.3030856819564138, 'min_weight_fraction_leaf': 0.04227011624339991, 'max_features': 'log2', 'min_impurity_decrease': 4.094308088527539e-05, 'validation_fraction': 0.7311035029930464, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 17:07:09,067] Trial 71 finished with value: 0.7057455222887223 and parameters: {'subsample': 0.8958059912610585, 'learning_rate': 0.00404243977738313, 'dropout_rate': 0.13685925262610546, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.27174017051065336, 'max_features': 0.1, 'min_impurity_decrease': 1.6903767334797878e-07, 'validation_fraction': 0.893021390165449, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6601731601731602
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 17:08:58,593] Trial 72 finished with value: 0.7255383448051743 and parameters: {'subsample': 0.9033994568982797, 'learning_rate': 0.008576558002904872, 'dropout_rate': 0.1796601786158867, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.0049265702435675185, 'min_weight_fraction_leaf': 0.2698684133835347, 'max_features': 0.1, 'min_impurity_decrease': 2.520131654025212e-07, 'validation_fraction': 0.9039347234285049, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:10:34,098] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.9030072931863139, 'learning_rate': 0.00868732713600762, 'dropout_rate': 0.2744775845272275, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.8157217970730618, 'min_weight_fraction_leaf': 0.2706425923382264, 'max_features': 0.1, 'min_impurity_decrease': 1.5060083036338323e-07, 'validation_fraction': 0.8429645916964783, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:10:42,468] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.8551098377950185, 'learning_rate': 0.017852326043636436, 'dropout_rate': 0.18670893655691517, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.3282745678695592, 'min_weight_fraction_leaf': 0.2216310042184134, 'max_features': 0.1, 'min_impurity_decrease': 0.00020700246413734948, 'validation_fraction': 0.7700706578571286, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:11:53,357] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.8885953564344566, 'learning_rate': 0.003923453373901735, 'dropout_rate': 0.25497810906198315, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 4.774324490228468, 'min_weight_fraction_leaf': 0.26023745967507866, 'max_features': 0.1, 'min_impurity_decrease': 1.0309115243736615e-07, 'validation_fraction': 0.9298417275031959, 'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:13:31,592] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9671878335188347, 'learning_rate': 0.010137963140872869, 'dropout_rate': 0.1720967582787876, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.6017992226500892, 'min_weight_fraction_leaf': 0.2343670795832099, 'max_features': 0.1, 'min_impurity_decrease': 4.1389285578024635e-07, 'validation_fraction': 0.4666209889121972, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:15:01,613] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.7817997136792754, 'learning_rate': 0.052009701795490706, 'dropout_rate': 0.21878505744240392, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 2.226175878213271, 'min_weight_fraction_leaf': 0.11673456101680679, 'max_features': 0.1, 'min_impurity_decrease': 2.278338706941225e-07, 'validation_fraction': 0.8870735397490029, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:16:05,861] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.85971117635256, 'learning_rate': 0.020702169760542934, 'dropout_rate': 0.10184607865359452, 'n_estimators': 351, 'criterion': 'squared_error', 'ccp_alpha': 1.1613144933398152, 'min_weight_fraction_leaf': 0.28827493961902323, 'max_features': 0.1, 'min_impurity_decrease': 1.0554012317973208e-06, 'validation_fraction': 0.7800831726807022, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:17:17,056] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.7085303006120247, 'learning_rate': 0.007203573027836778, 'dropout_rate': 0.3309372439616984, 'n_estimators': 405, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7098465234455584, 'min_weight_fraction_leaf': 0.16909333970802584, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9874471393466349, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:19:07,071] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.43152853207212877, 'learning_rate': 0.012535821130981227, 'dropout_rate': 0.28829477813771426, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.29587735180979763, 'min_weight_fraction_leaf': 0.1932252614573767, 'max_features': None, 'min_impurity_decrease': 2.607076310858583e-06, 'validation_fraction': 0.2486636150723724, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 17:21:03,677] Trial 81 finished with value: 0.7232266055095437 and parameters: {'subsample': 0.9310152909641193, 'learning_rate': 0.004901464536992707, 'dropout_rate': 0.14649845200705908, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 0.0401224705257143, 'min_weight_fraction_leaf': 0.2140884860716641, 'max_features': 0.1, 'min_impurity_decrease': 3.294643059864092e-07, 'validation_fraction': 0.9215349695607397, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:23:01,695] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.9804673759889536, 'learning_rate': 0.003705242334357205, 'dropout_rate': 0.15221754469070822, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 0.6905373562188476, 'min_weight_fraction_leaf': 0.214345215244296, 'max_features': 0.1, 'min_impurity_decrease': 1.535249456479472e-07, 'validation_fraction': 0.9202835513583518, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:24:48,150] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9176538987097111, 'learning_rate': 0.0076523566881114835, 'dropout_rate': 0.22968230522988387, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.20240849843431086, 'min_weight_fraction_leaf': 0.2383259127009152, 'max_features': 0.1, 'min_impurity_decrease': 4.399657878596901e-07, 'validation_fraction': 0.9767059181287342, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:26:21,728] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.8255635604133957, 'learning_rate': 0.0036977258275946636, 'dropout_rate': 0.20402072590631012, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.5198465206932167, 'min_weight_fraction_leaf': 0.15653086076945935, 'max_features': 0.1, 'min_impurity_decrease': 7.178610075896741e-07, 'validation_fraction': 0.8482804900297096, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7745098039215687

Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 17:28:47,799] Trial 85 finished with value: 0.7189891256993891 and parameters: {'subsample': 0.8918331608196582, 'learning_rate': 0.015605784733698558, 'dropout_rate': 0.14750634204389826, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.011637416243612385, 'min_weight_fraction_leaf': 0.30357930249568654, 'max_features': 'auto', 'min_impurity_decrease': 2.429626863306918e-07, 'validation_fraction': 0.9997678373401905, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:30:51,903] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.10092948452566086, 'learning_rate': 0.01532810679048379, 'dropout_rate': 0.17099114695337342, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.876197483648788, 'min_weight_fraction_leaf': 0.3015328988188304, 'max_features': 'auto', 'min_impurity_decrease': 1.6482137590771691e-06, 'validation_fraction': 0.9342270075718234, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:31:35,518] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.5929593460046293, 'learning_rate': 0.016822571784752067, 'dropout_rate': 0.19867600397015794, 'n_estimators': 263, 'criterion': 'squared_error', 'ccp_alpha': 0.23496207633721847, 'min_weight_fraction_leaf': 0.24832976306734728, 'max_features': 'auto', 'min_impurity_decrease': 1.6608380458349677e-05, 'validation_fraction': 0.9659857207632909, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:33:34,549] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9310702721088772, 'learning_rate': 0.009959700506785971, 'dropout_rate': 0.2555430411709441, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 8.088457238075051, 'min_weight_fraction_leaf': 0.22631747365745694, 'max_features': 'auto', 'min_impurity_decrease': 2.710852350800199e-07, 'validation_fraction': 0.7056533437856146, 'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:35:22,800] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.975612460964084, 'learning_rate': 0.012850444381300855, 'dropout_rate': 0.11846749927359909, 'n_estimators': 425, 'criterion': 'squared_error', 'ccp_alpha': 1.425464889112629, 'min_weight_fraction_leaf': 0.1784633449883898, 'max_features': 'auto', 'min_impurity_decrease': 5.921522228604161e-07, 'validation_fraction': 0.9996319172531741, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:36:52,962] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.34045768877643007, 'learning_rate': 0.0581528234960663, 'dropout_rate': 0.15210696274519644, 'n_estimators': 488, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9372956395735829, 'min_weight_fraction_leaf': 0.13514216761654674, 'max_features': 1, 'min_impurity_decrease': 3.412090206574042e-07, 'validation_fraction': 0.5798720476990769, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 17:38:33,580] Trial 91 finished with value: 0.7299130919568267 and parameters: {'subsample': 0.8979069506313946, 'learning_rate': 0.008101193305888026, 'dropout_rate': 0.14427259297048306, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.05667376231617895, 'min_weight_fraction_leaf': 0.2662831727524566, 'max_features': 'auto', 'min_impurity_decrease': 2.2001283077718922e-07, 'validation_fraction': 0.8878992829265958, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:40:10,890] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.8025284770642525, 'learning_rate': 0.008198746448650564, 'dropout_rate': 0.17658024519117366, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.4944517626406935, 'min_weight_fraction_leaf': 0.281932786781083, 'max_features': 'auto', 'min_impurity_decrease': 2.092935799209152e-07, 'validation_fraction': 0.8240961218884286, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:42:01,949] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.866078324832748, 'learning_rate': 0.011107826666625974, 'dropout_rate': 0.15001558634639325, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.20618034747646607, 'min_weight_fraction_leaf': 0.26022589277342434, 'max_features': 'auto', 'min_impurity_decrease': 1.2653383309827397e-07, 'validation_fraction': 0.8676712222376753, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:43:26,046] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.8418316701841008, 'learning_rate': 0.006152062924759251, 'dropout_rate': 0.2291019421217302, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.6324588657889718, 'min_weight_fraction_leaf': 0.4804568203093911, 'max_features': 'auto', 'min_impurity_decrease': 9.38303925215205e-07, 'validation_fraction': 0.9086059943821162, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:45:17,914] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.87747934958027, 'learning_rate': 0.0012139304758565887, 'dropout_rate': 0.12498646666495616, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.3715046104772777, 'min_weight_fraction_leaf': 0.208961689017974, 'max_features': 'auto', 'min_impurity_decrease': 2.382313770891545e-07, 'validation_fraction': 0.3818872933371859, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.6446078431372549
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 17:46:50,446] Trial 96 finished with value: 0.696510102322911 and parameters: {'subsample': 0.94218553177403, 'learning_rate': 0.020033817173644677, 'dropout_rate': 0.3058190228136884, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.030434277972844224, 'min_weight_fraction_leaf': 0.19188954018236168, 'max_features': 'auto', 'min_impurity_decrease': 3.679493950049724e-07, 'validation_fraction': 0.9459755275340084, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:47:09,365] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.9071107405480169, 'learning_rate': 0.013884656270412483, 'dropout_rate': 0.8479620532477699, 'n_estimators': 452, 'criterion': 'squared_error', 'ccp_alpha': 1.069614033248094, 'min_weight_fraction_leaf': 0.32699666489884094, 'max_features': 'log2', 'min_impurity_decrease': 5.25058355616678e-07, 'validation_fraction': 0.8836386308311208, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:48:19,937] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.9531544060001753, 'learning_rate': 0.008555926298082998, 'dropout_rate': 0.20235805532585233, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 0.7543795415309705, 'min_weight_fraction_leaf': 0.30398885673134707, 'max_features': 'auto', 'min_impurity_decrease': 1.0466185221530527e-07, 'validation_fraction': 0.9694358139640935, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.5654008438818565

[I 2024-04-17 17:49:39,810] A new study created in memory with name: no-name-7317c39e-28fa-4810-bbec-7f13a113aa87

Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 17:49:39,788] Trial 99 finished with value: 0.6663823683373736 and parameters: {'subsample': 0.9976459171012907, 'learning_rate': 0.024328086787534252, 'dropout_rate': 0.36361374787631456, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.004395791161995251, 'min_weight_fraction_leaf': 0.353628504086837, 'max_features': 'auto', 'min_impurity_decrease': 1.5812750205075571e-07, 'validation_fraction': 0.8128875839784486, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.


* Best trial for C-index:
 FrozenTrial(number=22, state=TrialState.COMPLETE, values=[0.7577518089481858], datetime_start=datetime.datetime(2024, 4, 17, 15, 51, 48, 191661), datetime_complete=datetime.datetime(2024, 4, 17, 15, 54, 11, 533154), params={'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=22, value=None)


* Best Score for C-index:
 0.7577518089481858

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 17:50:10,162] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 17:50:22,985] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 17:50:39,285] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 17:51:15,273] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 17:51:28,841] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 17:51:32,819] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 17:51:52,981] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 17:51:57,594] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 17:51:58,269] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21278960135067226
Fold 2 IBS: 0.22075148425471117
Fold 3 IBS: 0.20356154640252785
Fold 4 IBS: 0.22366437810992945
Fold 5 IBS: 0.2175108694850557
[I 2024-04-17 17:52:56,258] Trial 9 finished with value: 0.2156555759205793 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21360363678959007
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.20421474792063551
Fold 4 IBS: 0.22456346085174822
Fold 5 IBS: 0.21803455300047256
[I 2024-04-17 17:54:23,563] Trial 10 finished with value: 0.21637936117854983 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 17:55:49,328] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.2138334609344149
Fold 2 IBS: 0.22151322501680365
Fold 3 IBS: 0.20446062477316612
Fold 4 IBS: 0.2246559027106978
Fold 5 IBS: 0.2180563962052136
[I 2024-04-17 17:57:05,200] Trial 12 finished with value: 0.2165039219280592 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-17 17:57:37,028] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 17:58:46,106] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 17:59:34,567] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 18:00:00,327] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 18:01:03,211] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 18:01:33,514] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 18:01:39,728] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 18:02:36,298] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21367586546116044
Fold 2 IBS: 0.22153601357644734
Fold 3 IBS: 0.20438542163118117
Fold 4 IBS: 0.22463472155111044
Fold 5 IBS: 0.2180079529732588
[I 2024-04-17 18:03:43,336] Trial 21 finished with value: 0.21644799503863163 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21300133805358812
Fold 2 IBS: 0.22092783506924327

Fold 3 IBS: 0.20392740109457028
Fold 4 IBS: 0.22400556985244785
Fold 5 IBS: 0.2175786554209321
[I 2024-04-17 18:13:40,631] Trial 22 finished with value: 0.2158881598981563 and parameters: {'subsample': 0.7705970564002892, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2556338272384969, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.1819352198113874, 'max_features': 'auto', 'min_impurity_decrease': 2.8455032461612084e-06, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 18:23:32,342] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7836311463570909, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.19187858926690976, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.1238520089163157, 'max_features': 'auto', 'min_impurity_decrease': 3.0522262999316147e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 18:40:13,770] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7587811397980595, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.38790491264114013, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.9382331620898647, 'min_weight_fraction_leaf': 0.3092505738893419, 'max_features': 'auto', 'min_impurity_decrease': 1.835773315341181e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 19:20:17,203] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.7972724799167636, 'min_weight_fraction_leaf': 0.06342723550175844, 'max_features': 'auto', 'min_impurity_decrease': 4.2810579358018096e-07, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 20:05:27,963] Trial 26 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.926412059695023, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.5288432021501348, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.3654495948602763, 'max_features': 1, 'min_impurity_decrease': 5.7767867868391535e-06, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 20:05:29,788] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.7199879736775374, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 20:05:34,245] Trial 28 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5982471609501279, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.7580627673470397, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.17979234805851085, 'max_features': 0.1, 'min_impurity_decrease': 2.8766461228225205e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 21:06:30,256] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.1613885275758775, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:07:34,233] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.3265580511017444, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 2.031090116944395e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.2132673053926921
Fold 2 IBS: 0.22138150435074114
Fold 3 IBS: 0.20416936232206076
Fold 4 IBS: 0.224409146213765
Fold 5 IBS: 0.2177869543616682
[I 2024-04-17 22:17:03,011] Trial 31 finished with value: 0.2162028545281854 and parameters: {'subsample': 0.9344383405023591, 'learning_rate': 0.006524518316879135, 'dropout_rate': 0.26649573367142365, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 4.351117867352206e-06, 'validation_fraction': 0.9601957444024036, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21250908818560812
Fold 2 IBS: 0.22112061913596615
Fold 3 IBS: 0.20357254804690844
Fold 4 IBS: 0.22431509484129145
Fold 5 IBS: 0.21754679795245008
[I 2024-04-17 22:17:37,316] Trial 32 finished with value: 0.2158128296324448 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2287495679714313, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.23002205018404465, 'max_features': 'auto', 'min_impurity_decrease': 5.685341128394722e-05, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:17:56,143] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9177537861930692, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.3914970241753336, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.0507266620441584, 'min_weight_fraction_leaf': 0.23926229900744406, 'max_features': 'auto', 'min_impurity_decrease': 0.00011709565626556463, 'validation_fraction': 0.8393388494663446, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:18:16,663] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6819681800793775, 'learning_rate': 0.014932417117098078, 'dropout_rate': 0.2500240325464975, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 1.9765936590363733, 'min_weight_fraction_leaf': 0.13771184392949654, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9172090645295194, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:18:24,462] Trial 35 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7476638601677043, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.30101053387291227, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 0.44652508735115226, 'min_weight_fraction_leaf': 0.10093795447298021, 'max_features': None, 'min_impurity_decrease': 4.406156675878729e-05, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:18:49,088] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.42230497047334825, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.26995461743933613, 'max_features': 'auto', 'min_impurity_decrease': 1.3215601521076594e-05, 'validation_fraction': 0.7818001985604904, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:18:52,565] Trial 37 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.21915428448310503, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 1.4358936193715688, 'min_weight_fraction_leaf': 0.23268483668726153, 'max_features': None, 'min_impurity_decrease': 0.00032393590103416044, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:19:05,751] Trial 38 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8672504967337782, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.7673236646699829, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6556730327214771, 'min_weight_fraction_leaf': 0.18834697224411925, 'max_features': 'auto', 'min_impurity_decrease': 0.00023363839115037033, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:19:22,647] Trial 39 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8156280794845335, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.3466374755180119, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.2802748909834897, 'max_features': 1, 'min_impurity_decrease': 0.001895508491501562, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:19:43,821] Trial 40 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.518652974052727, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 3.416581893752396, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 1.186294852384206e-05, 'validation_fraction': 0.6514426016998515, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21343873621972445
Fold 2 IBS: 0.22049446029877326
Fold 3 IBS: 0.20337828484272225
Fold 4 IBS: 0.22303639527565466
Fold 5 IBS: 0.21729676723732877
[I 2024-04-17 22:20:19,531] Trial 41 finished with value: 0.21552892877484067 and parameters: {'subsample': 0.9932038385002909, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.1573621124822965, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.13954813567569782, 'max_features': 'auto', 'min_impurity_decrease': 7.535700463117119e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.2131030184453258
Fold 2 IBS: 0.22050327285628324
Fold 3 IBS: 0.2033673824751969
Fold 4 IBS: 0.22363217726195525
Fold 5 IBS: 0.21724767258898225
[I 2024-04-17 22:20:55,437] Trial 42 finished with value: 0.2155707047255487 and parameters: {'subsample': 0.964697700266936, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.18073816214366334, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327291371346121, 'min_weight_fraction_leaf': 0.1501825213718253, 'max_features': 'auto', 'min_impurity_decrease': 7.389724453793971e-07, 'validation_fraction': 0.9438929489105444, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:21:37,819] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9828290729869368, 'learning_rate': 0.005440117267094092, 'dropout_rate': 0.16429624388711278, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.1638059032250418, 'min_weight_fraction_leaf': 0.14400744495905113, 'max_features': 'auto', 'min_impurity_decrease': 7.160819992467899e-07, 'validation_fraction': 0.8682784817018523, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:22:12,695] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9992871622667048, 'learning_rate': 0.012272887594565313, 'dropout_rate': 0.11965546339368549, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.5504303626596221, 'min_weight_fraction_leaf': 0.10316812300893248, 'max_features': 'auto', 'min_impurity_decrease': 2.2780695231073978e-06, 'validation_fraction': 0.8946516967835402, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:22:21,901] Trial 45 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8888336111822305, 'learning_rate': 0.022080051602678542, 'dropout_rate': 0.2121382569959027, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.41647456900543567, 'min_weight_fraction_leaf': 0.045210542223651826, 'max_features': 0.1, 'min_impurity_decrease': 2.0256548340178764e-07, 'validation_fraction': 0.943601584155436, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21368294038898764
Fold 2 IBS: 0.22138561655450684
Fold 3 IBS: 0.2042880559361189
Fold 4 IBS: 0.22453830345531042
Fold 5 IBS: 0.21794750132893198
[I 2024-04-17 22:22:46,958] Trial 46 finished with value: 0.21636848353277113 and parameters: {'subsample': 0.7744813929591432, 'learning_rate': 0.008102046534903828, 'dropout_rate': 0.1797794592098615, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.08495175216102194, 'min_weight_fraction_leaf': 0.15177154165796414, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1313197537973378e-06, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:23:03,297] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7017637733903979, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.7022058348677743, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 1.7224181899716802, 'min_weight_fraction_leaf': 0.18604464195331838, 'max_features': 'auto', 'min_impurity_decrease': 6.985840903306681e-07, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:23:03,462] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5605970169273662, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.10447148486096186, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.2080122998414906, 'max_features': None, 'min_impurity_decrease': 2.1520342389791543e-07, 'validation_fraction': 0.9548943163211767, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:23:10,323] Trial 49 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8470287699338075, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.1456275761236044, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2223686585045759, 'min_weight_fraction_leaf': 0.12204787996041808, 'max_features': 'log2', 'min_impurity_decrease': 0.0008845692122216605, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-17 22:23:30,308] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9497672382316631, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.23703345601437922, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 0.4773369462462276, 'min_weight_fraction_leaf': 0.25645611863450213, 'max_features': 'auto', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.7876099760634406, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21305615407340403
Fold 2 IBS: 0.22124588111973337
Fold 3 IBS: 0.20390302508767316
Fold 4 IBS: 0.22446365006496424
Fold 5 IBS: 0.21777819332443837
[I 2024-04-17 22:24:01,084] Trial 51 finished with value: 0.21608938073404263 and parameters: {'subsample': 0.9480276186148049, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.2856033525481214, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.22461792037583256, 'max_features': 'auto', 'min_impurity_decrease': 3.3864756991240473e-06, 'validation_fraction': 0.959807845534086, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21352169783850614
Fold 2 IBS: 0.22120550026908148
Fold 3 IBS: 0.20396949286236565
Fold 4 IBS: 0.22452441731877534
Fold 5 IBS: 0.2178146994022686
[I 2024-04-17 22:24:33,157] Trial 52 finished with value: 0.21620716153819944 and parameters: {'subsample': 0.9690886547521121, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.29098664360409054, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.03660199451993653, 'min_weight_fraction_leaf': 0.17297727640490082, 'max_features': 'auto', 'min_impurity_decrease': 3.049559112525484e-06, 'validation_fraction': 0.9718410393680599, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:25:02,230] Trial 53 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8920228452074053, 'learning_rate': 0.010335997729310374, 'dropout_rate': 0.32661371595674515, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.2945173805852883, 'max_features': 'auto', 'min_impurity_decrease': 7.833227343851573e-07, 'validation_fraction': 0.9011349602609936, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:25:31,349] Trial 54 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9472264097624746, 'learning_rate': 0.01762169753824272, 'dropout_rate': 0.1508637651435515, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.4362560228385305, 'min_weight_fraction_leaf': 0.22035807288061335, 'max_features': 'auto', 'min_impurity_decrease': 0.015305241535958306, 'validation_fraction': 0.9995106443638909, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:25:55,839] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.809323041898869, 'learning_rate': 0.0040826970179266685, 'dropout_rate': 0.36065535241543395, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.5126136571072866, 'min_weight_fraction_leaf': 0.2002957617254777, 'max_features': 'auto', 'min_impurity_decrease': 2.0868015436948727e-05, 'validation_fraction': 0.8814649292460881, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:26:14,429] Trial 56 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.2818850250060197, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.23297170241739207, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 2.3897427065099115, 'min_weight_fraction_leaf': 0.2552507873943692, 'max_features': 'auto', 'min_impurity_decrease': 1.4962235814136573e-06, 'validation_fraction': 0.5010775717552909, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:26:34,382] Trial 57 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8654402967188083, 'learning_rate': 0.0010994123129714779, 'dropout_rate': 0.5925056825473531, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 3.0806403612284923, 'min_weight_fraction_leaf': 0.3388560781293413, 'max_features': 'auto', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.9457965904141827, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:26:57,952] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.02418028639032989, 'dropout_rate': 0.20247794507096373, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 6.734647887782943, 'min_weight_fraction_leaf': 0.13686113855005327, 'max_features': 1, 'min_impurity_decrease': 5.6056583988076206e-05, 'validation_fraction': 0.7164235243058807, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:27:15,109] Trial 59 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5273941310970662, 'learning_rate': 0.013269545795309803, 'dropout_rate': 0.27120464223149515, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.08408118413163579, 'max_features': 0.1, 'min_impurity_decrease': 4.3252557742868694e-07, 'validation_fraction': 0.8195507001084924, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:27:29,841] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4687193173806922, 'learning_rate': 0.0299620116966956, 'dropout_rate': 0.40652994108993334, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 1.7110338383890442, 'min_weight_fraction_leaf': 0.1707925110352551, 'max_features': 'auto', 'min_impurity_decrease': 2.777282902745793e-06, 'validation_fraction': 0.8559576979556259, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:28:00,445] Trial 61 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9319260511303565, 'learning_rate': 0.006981217524957076, 'dropout_rate': 0.2694290399109642, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.2266262530125842, 'min_weight_fraction_leaf': 0.2262208916321135, 'max_features': 'auto', 'min_impurity_decrease': 6.393438969585487e-06, 'validation_fraction': 0.968342815685117, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21261827944826023
Fold 2 IBS: 0.2212835131478303
Fold 3 IBS: 0.20384635335083123
Fold 4 IBS: 0.22428599240586905
Fold 5 IBS: 0.21722666261844198
[I 2024-04-17 22:28:29,441] Trial 62 finished with value: 0.21585216019424655 and parameters: {'subsample': 0.9972198040262032, 'learning_rate': 0.008659221224759001, 'dropout_rate': 0.18470289302046516, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.022476866600004634, 'min_weight_fraction_leaf': 0.1963819185824203, 'max_features': 'auto', 'min_impurity_decrease': 3.745982455886227e-06, 'validation_fraction': 0.9275220875852723, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:28:39,592] Trial 63 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9899309662352432, 'learning_rate': 0.018451257515222523, 'dropout_rate': 0.8555425487679464, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.19157478425569488, 'max_features': 'auto', 'min_impurity_decrease': 1.0767504332570267e-06, 'validation_fraction': 0.9184663621892178, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:29:05,293] Trial 64 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9658825052862857, 'learning_rate': 0.010845363858236992, 'dropout_rate': 0.13571080979315037, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.3681339382709387, 'min_weight_fraction_leaf': 0.15534331606940482, 'max_features': 'log2', 'min_impurity_decrease': 8.60046486145071e-06, 'validation_fraction': 0.9205869937759958, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21299720012323184
Fold 2 IBS: 0.22115174939969934
Fold 3 IBS: 0.2038040121811597
Fold 4 IBS: 0.2242157275656328
Fold 5 IBS: 0.21734625390047366
[I 2024-04-17 22:29:37,207] Trial 65 finished with value: 0.21590298863403948 and parameters: {'subsample': 0.9661607708539444, 'learning_rate': 0.008868026173365113, 'dropout_rate': 0.17835638219464384, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.002725826040487267, 'min_weight_fraction_leaf': 0.0025378122397684832, 'max_features': 'auto', 'min_impurity_decrease': 1.7045397927378775e-05, 'validation_fraction': 0.7413345803433677, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:30:03,834] Trial 66 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9998769833869746, 'learning_rate': 0.003967598379054899, 'dropout_rate': 0.17654958266634313, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 0.8981368148483696, 'min_weight_fraction_leaf': 0.03518122515344503, 'max_features': 'auto', 'min_impurity_decrease': 7.140027633149786e-05, 'validation_fraction': 0.6362228335648394, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:30:27,134] Trial 67 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8945386029541793, 'learning_rate': 0.01494075298406419, 'dropout_rate': 0.209071801122636, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 1.1837261226658302, 'min_weight_fraction_leaf': 0.10443241497369499, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5552258602982892e-05, 'validation_fraction': 0.7259068897097584, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-17 22:31:08,291] Trial 68 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.843502945752621, 'learning_rate': 0.02075147594960792, 'dropout_rate': 0.16252263519114862, 'n_estimators': 490, 'criterion': 'friedman_mse', 'ccp_alpha': 8.846039028998158, 'min_weight_fraction_leaf': 0.057901034918407895, 'max_features': 'auto', 'min_impurity_decrease': 3.057918866616863e-07, 'validation_fraction': 0.6846740503948187, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:31:36,203] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.01037165919107231, 'dropout_rate': 0.19004731427008625, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.34303232955200197, 'min_weight_fraction_leaf': 0.3579731281150166, 'max_features': 'auto', 'min_impurity_decrease': 0.00014344627836102727, 'validation_fraction': 0.7769648880006281, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:32:07,400] Trial 70 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6499145948799803, 'learning_rate': 0.008667614598934925, 'dropout_rate': 0.2379061541841675, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.6762661413605899, 'min_weight_fraction_leaf': 0.2053436289550881, 'max_features': None, 'min_impurity_decrease': 2.7112245092072337e-05, 'validation_fraction': 0.5272974695233066, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21365379061917414
Fold 2 IBS: 0.22138264547298084
Fold 3 IBS: 0.2043021502572646
Fold 4 IBS: 0.22456249898531583
Fold 5 IBS: 0.2178752609515109
[I 2024-04-17 22:32:41,448] Trial 71 finished with value: 0.21635526925724924 and parameters: {'subsample': 0.9554665295189709, 'learning_rate': 0.004772306432110387, 'dropout_rate': 0.30773217080297294, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.06024274183448569, 'min_weight_fraction_leaf': 0.019537053946387287, 'max_features': 'auto', 'min_impurity_decrease': 3.603782675882374e-06, 'validation_fraction': 0.8818766703918308, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21009179135163386
Fold 2 IBS: 0.21999119714274143
Fold 3 IBS: 0.2019997974702572
Fold 4 IBS: 0.22308677215739936
Fold 5 IBS: 0.2164934631302429
[I 2024-04-17 22:33:18,158] Trial 72 finished with value: 0.21433260425045497 and parameters: {'subsample': 0.9233416329717381, 'learning_rate': 0.01307164167481496, 'dropout_rate': 0.12211037740366137, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.004815836437462028, 'min_weight_fraction_leaf': 0.2452551786385524, 'max_features': 'auto', 'min_impurity_decrease': 1.5300590715832769e-06, 'validation_fraction': 0.974284387349558, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 72 with value: 0.21433260425045497.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:33:25,157] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.916509573532907, 'learning_rate': 0.01366625897147706, 'dropout_rate': 0.10211108319082117, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.35137810274202946, 'min_weight_fraction_leaf': 0.0067953600457776875, 'max_features': 'auto', 'min_impurity_decrease': 5.253021283264037e-07, 'validation_fraction': 0.9862680394354211, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 72 with value: 0.21433260425045497.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:33:54,740] Trial 74 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.98093897605085, 'learning_rate': 0.01711555655405715, 'dropout_rate': 0.13243922080536136, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.7083433911466146, 'min_weight_fraction_leaf': 0.24361782259873882, 'max_features': 'auto', 'min_impurity_decrease': 1.0928587879200682e-06, 'validation_fraction': 0.8125486143795312, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 72 with value: 0.21433260425045497.
Fold 1 IBS: 0.20063679042123642
Fold 2 IBS: 0.2148812250636474
Fold 3 IBS: 0.19380589049848737
Fold 4 IBS: 0.21616853881208678
Fold 5 IBS: 0.21227770638433743
[I 2024-04-17 22:34:19,422] Trial 75 finished with value: 0.20755403023595909 and parameters: {'subsample': 0.8646743646205938, 'learning_rate': 0.08843409287484169, 'dropout_rate': 0.1693875032679634, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.008810810992982535, 'min_weight_fraction_leaf': 0.29044798941528627, 'max_features': 'auto', 'min_impurity_decrease': 5.157320437854681e-06, 'validation_fraction': 0.7489142536117352, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:34:42,443] Trial 76 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8704877196117842, 'learning_rate': 0.0916936247639216, 'dropout_rate': 0.13042337037884444, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.2722270315020332, 'max_features': 'auto', 'min_impurity_decrease': 1.6370541352867706e-06, 'validation_fraction': 0.9218092808039015, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:35:01,759] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7865219593038091, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.25073094184082545, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.2846220433570537, 'min_weight_fraction_leaf': 0.32348748582358233, 'max_features': 1, 'min_impurity_decrease': 2.1196884133822008e-06, 'validation_fraction': 0.854746843935587, 'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:35:16,201] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.74450491092411, 'learning_rate': 0.08426314282635561, 'dropout_rate': 0.21845035750510394, 'n_estimators': 300, 'criterion': 'squared_error', 'ccp_alpha': 0.3013998603131079, 'min_weight_fraction_leaf': 0.28488038648314357, 'max_features': 'auto', 'min_impurity_decrease': 4.969807589794284e-06, 'validation_fraction': 0.5953526855291732, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:35:42,109] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9257604896060708, 'learning_rate': 0.07449175092046981, 'dropout_rate': 0.10061598571006734, 'n_estimators': 422, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8368147401670278, 'min_weight_fraction_leaf': 0.3103740193108716, 'max_features': 0.1, 'min_impurity_decrease': 1.5059537626102993e-07, 'validation_fraction': 0.8973370541013407, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560958
[I 2024-04-17 22:36:10,078] Trial 80 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8235918523200412, 'learning_rate': 0.04033855340571721, 'dropout_rate': 0.16425961502490374, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 1.694844319118747, 'min_weight_fraction_leaf': 0.2647465108562044, 'max_features': 'log2', 'min_impurity_decrease': 2.9198051926565164e-07, 'validation_fraction': 0.9949359598698552, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21270616661412084
Fold 2 IBS: 0.22114894326985232
Fold 3 IBS: 0.2033654110159561
Fold 4 IBS: 0.2242783032190139
Fold 5 IBS: 0.21754308206787823
[I 2024-04-17 22:36:53,336] Trial 81 finished with value: 0.21580838123736426 and parameters: {'subsample': 0.9683433550626522, 'learning_rate': 0.008693963960519305, 'dropout_rate': 0.1932014858120802, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.2888444623370858, 'max_features': 'auto', 'min_impurity_decrease': 1.789620202740983e-05, 'validation_fraction': 0.938473425448535, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:37:32,472] Trial 82 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9762052388738753, 'learning_rate': 0.06401898097796113, 'dropout_rate': 0.19741538666007516, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.534138531195614, 'min_weight_fraction_leaf': 0.24700237584705395, 'max_features': 'auto', 'min_impurity_decrease': 7.152609841250385e-06, 'validation_fraction': 0.9388911144407316, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:38:14,054] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8945279252278314, 'learning_rate': 0.012088994568921815, 'dropout_rate': 0.154422708294762, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.1988546603429769, 'min_weight_fraction_leaf': 0.2902454191677818, 'max_features': 'auto', 'min_impurity_decrease': 3.133577694489401e-05, 'validation_fraction': 0.8395709442103857, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:38:42,649] Trial 84 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9340088491306221, 'learning_rate': 0.020145328722091006, 'dropout_rate': 0.23069098430626017, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.5566102523015541, 'min_weight_fraction_leaf': 0.3043408977845187, 'max_features': 'auto', 'min_impurity_decrease': 5.245144153489441e-06, 'validation_fraction': 0.961947672530741, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:39:13,524] Trial 85 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8559905830599279, 'learning_rate': 0.003151086314395833, 'dropout_rate': 0.12604720621824386, 'n_estimators': 401, 'criterion': 'squared_error', 'ccp_alpha': 1.0429257766218587, 'min_weight_fraction_leaf': 0.13299714491615983, 'max_features': 'auto', 'min_impurity_decrease': 9.411442401014158e-06, 'validation_fraction': 0.9351152476505527, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:39:37,636] Trial 86 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.998032487033103, 'learning_rate': 0.015189890476328648, 'dropout_rate': 0.1929808152262999, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.25850792206277284, 'min_weight_fraction_leaf': 0.19547135211860373, 'max_features': 'sqrt', 'min_impurity_decrease': 7.182497909387456e-07, 'validation_fraction': 0.9008555229787725, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:39:56,212] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.586845457594135, 'learning_rate': 0.007791310814930576, 'dropout_rate': 0.2576203464314456, 'n_estimators': 376, 'criterion': 'squared_error', 'ccp_alpha': 0.5970165508324569, 'min_weight_fraction_leaf': 0.3246889883811851, 'max_features': 'auto', 'min_impurity_decrease': 1.2915207513275362e-06, 'validation_fraction': 0.7941466165973634, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:40:15,434] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9047974654661481, 'learning_rate': 0.053489441535809173, 'dropout_rate': 0.15111205819257206, 'n_estimators': 351, 'criterion': 'squared_error', 'ccp_alpha': 0.8515398041309932, 'min_weight_fraction_leaf': 0.21790404115359022, 'max_features': 'auto', 'min_impurity_decrease': 2.7145979471070252e-06, 'validation_fraction': 0.8752408074269059, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:40:43,746] Trial 89 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8838515048108662, 'learning_rate': 0.01150450588881658, 'dropout_rate': 0.3106345257277401, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 5.474477626804302, 'min_weight_fraction_leaf': 0.181177839559219, 'max_features': 'auto', 'min_impurity_decrease': 1.2718861827092477e-05, 'validation_fraction': 0.9760648785366552, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 9}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-17 22:41:21,113] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.960313946457138, 'learning_rate': 0.02326628275454888, 'dropout_rate': 0.2094619744215954, 'n_estimators': 470, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.16213094006522927, 'max_features': None, 'min_impurity_decrease': 8.384298759153104e-07, 'validation_fraction': 0.8362867621481024, 'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21278867450434957
Fold 2 IBS: 0.22123796611209143
Fold 3 IBS: 0.20385360063526636
Fold 4 IBS: 0.22428500781668678
Fold 5 IBS: 0.2173590980603734
[I 2024-04-17 22:41:53,967] Trial 91 finished with value: 0.21590486942575354 and parameters: {'subsample': 0.974845880068985, 'learning_rate': 0.008764883268716819, 'dropout_rate': 0.18635760945321272, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.2754894562810546, 'max_features': 'auto', 'min_impurity_decrease': 4.2012810231263196e-05, 'validation_fraction': 0.6282967667391103, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:42:27,438] Trial 92 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9396947823626011, 'learning_rate': 0.004368164180849998, 'dropout_rate': 0.1759357421598699, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.25915463409396067, 'min_weight_fraction_leaf': 0.25965914250337996, 'max_features': 'auto', 'min_impurity_decrease': 8.321039301525785e-05, 'validation_fraction': 0.6636818720897245, 'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.20443254583780004
Fold 2 IBS: 0.21704992653232766
Fold 3 IBS: 0.20021814328282203
Fold 4 IBS: 0.21936269502578284
Fold 5 IBS: 0.2126381390950113
[I 2024-04-17 22:42:59,804] Trial 93 finished with value: 0.2107402899547488 and parameters: {'subsample': 0.9636218550527925, 'learning_rate': 0.08324257203844727, 'dropout_rate': 0.22319965814002635, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.04690043062719928, 'min_weight_fraction_leaf': 0.23684277621975902, 'max_features': 'auto', 'min_impurity_decrease': 1.548140174949508e-05, 'validation_fraction': 0.7388312145266367, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:43:30,639] Trial 94 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9216100363199584, 'learning_rate': 0.08937987875028564, 'dropout_rate': 0.2226719596812821, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.5370821041135924, 'min_weight_fraction_leaf': 0.23931318130410523, 'max_features': 'auto', 'min_impurity_decrease': 1.9804047777777935e-05, 'validation_fraction': 0.9344757106941509, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:44:05,495] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9505720618597318, 'learning_rate': 0.08804335553847131, 'dropout_rate': 0.2858426054482697, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.3311905561863823, 'min_weight_fraction_leaf': 0.1453679981012504, 'max_features': 'auto', 'min_impurity_decrease': 9.665752514196455e-06, 'validation_fraction': 0.5743893910381555, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:44:34,367] Trial 96 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9806046119279813, 'learning_rate': 0.08726220388438458, 'dropout_rate': 0.2508258253233333, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.0842424782139257, 'min_weight_fraction_leaf': 0.2509877726726459, 'max_features': 'auto', 'min_impurity_decrease': 4.132954919887874e-06, 'validation_fraction': 0.7662521699162499, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:44:56,304] Trial 97 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9139721535827401, 'learning_rate': 0.0956243686002578, 'dropout_rate': 0.11551248506043046, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 0.20602145594384874, 'min_weight_fraction_leaf': 0.21288677009944212, 'max_features': 1, 'min_impurity_decrease': 5.099166934714435e-07, 'validation_fraction': 0.6982085459927765, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:45:28,385] Trial 98 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.881458897433829, 'learning_rate': 0.0818716069302554, 'dropout_rate': 0.1602397729595261, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.7476516282703678, 'min_weight_fraction_leaf': 0.29398452840523387, 'max_features': 'auto', 'min_impurity_decrease': 2.2015056170379928e-06, 'validation_fraction': 0.9116047571236726, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.20960061935285024
Fold 2 IBS: 0.21745644638172798

Fold 3 IBS: 0.20030580413616672
Fold 4 IBS: 0.21827950204883104
Fold 5 IBS: 0.2160767264619057
[I 2024-04-17 22:45:52,843] Trial 99 finished with value: 0.21234381967629634 and parameters: {'subsample': 0.7984456569855936, 'learning_rate': 0.07921297533010697, 'dropout_rate': 0.36361374787631456, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.004455045338579978, 'min_weight_fraction_leaf': 0.23447872920034368, 'max_features': 0.1, 'min_impurity_decrease': 0.00015837847703956763, 'validation_fraction': 0.4378698142708704, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 75 with value: 0.20755403023595909.


* Best trial for IBS:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.20755403023595909], datetime_start=datetime.datetime(2024, 4, 17, 22, 33, 54, 742948), datetime_complete=datetime.datetime(2024, 4, 17, 22, 34, 19, 421779), params={'subsample': 0.8646743646205938, 'learning_rate': 0.08843409287484169, 'dropout_rate': 0.1693875032679634, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.008810810992982535, 'min_weight_fraction_leaf': 0.29044798941528627, 'max_features': 'auto', 'min_impurity_decrease': 5.157320437854681e-06, 'validation_fraction': 0.7489142536117352, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for IBS:
 0.20755403023595909

In [65]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [66]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.758
train_ibs:  0.208

#### Test

In [67]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [68]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.0339977959383996,
                                 criterion='squared_error',
                                 dropout_rate=0.2075412325353082,
                                 learning_rate=0.010706280861824496,
                                 max_features='auto', max_leaf_nodes=17,
                                 min_impurity_decrease=3.3602815261835675e-07,
                                 min_samples_leaf=13, min_samples_split=18,
                                 min_weight_fraction_leaf=0.4472167339801619,
                                 n_estimators=445, random_state=123,
                                 subsample=0.9030031356045858,
                                 validation_fraction=0.9350158433232643)

C-index score: 0.618

GradientBoostingSurvivalAnalysis(ccp_alpha=0.008810810992982535,
                                 criterion='squared_error',
                                 dropout_rate=0.1693875032679634,
                                 learning_rate=0.08843409287484169,
                                 max_features='auto', max_leaf_nodes=15,
                                 min_impurity_decrease=5.157320437854681e-06,
                                 min_samples_leaf=16, min_samples_split=20,
                                 min_weight_fraction_leaf=0.29044798941528627,
                                 n_estimators=403, random_state=123,
                                 subsample=0.8646743646205938,
                                 validation_fraction=0.7489142536117352)

IBS: 0.213

In [69]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [70]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [71]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 22:46:06,640] A new study created in memory with name: no-name-26c53158-c38e-44a8-8424-aaf19edb515e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 22:46:09,913] Trial 0 finished with value: 0.6910479019846645 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6910479019846645.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 22:46:23,073] Trial 1 finished with value: 0.7003616274748606 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.7003616274748606.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:46:27,483] Trial 2 finished with value: 0.6929052134111557 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 1 with value: 0.7003616274748606.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:46:32,798] Trial 3 finished with value: 0.724056185019592 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.724056185019592.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6338028169014085
[I 2024-04-17 22:46:40,077] Trial 4 finished with value: 0.7376235478145617 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.7376235478145617.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 22:46:50,741] Trial 5 finished with value: 0.6807800448418073 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.7376235478145617.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-17 22:46:55,371] Trial 6 finished with value: 0.6218282519980552 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.7376235478145617.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:46:56,494] Trial 7 finished with value: 0.7063036409639951 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.7376235478145617.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:47:01,548] Trial 8 finished with value: 0.7034285136403383 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.7376235478145617.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:47:13,557] Trial 9 finished with value: 0.732582679622036 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.7376235478145617.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6244131455399061
[I 2024-04-17 22:47:20,762] Trial 10 finished with value: 0.7429519914904485 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.7429519914904485.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 22:47:28,620] Trial 11 finished with value: 0.7578368561966351 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 22:47:36,464] Trial 12 finished with value: 0.7569981116078905 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5821596244131455
[I 2024-04-17 22:47:46,364] Trial 13 finished with value: 0.679353493107157 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 22:47:55,259] Trial 14 finished with value: 0.749409400058829 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6338028169014085
[I 2024-04-17 22:48:03,225] Trial 15 finished with value: 0.7385141687349667 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6291079812206573
[I 2024-04-17 22:48:14,451] Trial 16 finished with value: 0.7362041554818657 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:48:26,991] Trial 17 finished with value: 0.7409160129553694 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 416, 'learning_rate': 0.08639690405722114}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:48:33,457] Trial 18 finished with value: 0.7258097057604546 and parameters: {'subsample': 0.35801092912005106, 'dropout_rate': 0.33602353085084236, 'n_estimators': 256, 'learning_rate': 0.08307767561539126}. Best is trial 11 with value: 0.7578368561966351.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6431924882629108
[I 2024-04-17 22:48:36,655] Trial 19 finished with value: 0.7498564411015384 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7254192287154788, 'n_estimators': 117, 'learning_rate': 0.09614402133777997}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6291079812206573
[I 2024-04-17 22:48:47,506] Trial 20 finished with value: 0.7393879721615869 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 423, 'learning_rate': 0.07788582119853761}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:48:47,852] Trial 21 finished with value: 0.7545878237395219 and parameters: {'subsample': 0.11001094780860332, 'dropout_rate': 0.7075879968118339, 'n_estimators': 12, 'learning_rate': 0.09417886707495288}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:48:48,664] Trial 22 finished with value: 0.7403430565000599 and parameters: {'subsample': 0.18302526270385422, 'dropout_rate': 0.6797578358009322, 'n_estimators': 31, 'learning_rate': 0.09016744377002948}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6431924882629108
[I 2024-04-17 22:48:55,928] Trial 23 finished with value: 0.7481749025482574 and parameters: {'subsample': 0.1529963084044875, 'dropout_rate': 0.8293972968657299, 'n_estimators': 311, 'learning_rate': 0.06523678593976207}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:48:58,729] Trial 24 finished with value: 0.731816561897616 and parameters: {'subsample': 0.3073558694541275, 'dropout_rate': 0.9639676260548358, 'n_estimators': 125, 'learning_rate': 0.07736898361535043}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:49:00,380] Trial 25 finished with value: 0.7477787580534085 and parameters: {'subsample': 0.21578783290493656, 'dropout_rate': 0.5515081710932523, 'n_estimators': 71, 'learning_rate': 0.09163056701298726}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:49:05,985] Trial 26 finished with value: 0.7329553833640622 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.5707562654379044, 'n_estimators': 245, 'learning_rate': 0.08146277028320098}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.5686274509803921
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.5821596244131455
[I 2024-04-17 22:49:06,108] Trial 27 finished with value: 0.6059434170514184 and parameters: {'subsample': 0.1001314126580015, 'dropout_rate': 0.3060837787360696, 'n_estimators': 1, 'learning_rate': 0.04133902891970489}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:49:14,260] Trial 28 finished with value: 0.7060259162377409 and parameters: {'subsample': 0.6088999383640823, 'dropout_rate': 0.7802936418316316, 'n_estimators': 338, 'learning_rate': 0.09352800640830385}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-17 22:49:17,810] Trial 29 finished with value: 0.6218282519980552 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.610605952426544, 'n_estimators': 152, 'learning_rate': 0.06046208382653473}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6291079812206573
[I 2024-04-17 22:49:28,373] Trial 30 finished with value: 0.7390734907879098 and parameters: {'subsample': 0.21797436717278929, 'dropout_rate': 0.3892024351052794, 'n_estimators': 397, 'learning_rate': 0.016814619253793885}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6291079812206573
[I 2024-04-17 22:49:30,017] Trial 31 finished with value: 0.7425573843453327 and parameters: {'subsample': 0.10830219177461477, 'dropout_rate': 0.7768877489025441, 'n_estimators': 68, 'learning_rate': 0.09722683608012687}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6431924882629108
[I 2024-04-17 22:49:32,985] Trial 32 finished with value: 0.7429560831447768 and parameters: {'subsample': 0.15588315806842334, 'dropout_rate': 0.6551652950459309, 'n_estimators': 108, 'learning_rate': 0.09562148866507592}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6384976525821596
[I 2024-04-17 22:49:35,674] Trial 33 finished with value: 0.743511073775853 and parameters: {'subsample': 0.1012520200640222, 'dropout_rate': 0.4719384012768436, 'n_estimators': 111, 'learning_rate': 0.06992697841465893}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5821596244131455
[I 2024-04-17 22:49:35,900] Trial 34 finished with value: 0.6767560905097546 and parameters: {'subsample': 0.23419761201309758, 'dropout_rate': 0.7502886634089525, 'n_estimators': 5, 'learning_rate': 0.09138289420097837}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6431924882629108
[I 2024-04-17 22:49:42,338] Trial 35 finished with value: 0.7455170212139054 and parameters: {'subsample': 0.16710472630778297, 'dropout_rate': 0.19242557819860076, 'n_estimators': 232, 'learning_rate': 0.07939676038919927}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:49:49,961] Trial 36 finished with value: 0.7318384809068768 and parameters: {'subsample': 0.3081019716032447, 'dropout_rate': 0.13691793360905996, 'n_estimators': 293, 'learning_rate': 0.07158461284458016}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:49:52,443] Trial 37 finished with value: 0.738030177953935 and parameters: {'subsample': 0.14181352785814252, 'dropout_rate': 0.8374055765137145, 'n_estimators': 82, 'learning_rate': 0.08398598098613289}. Best is trial 11 with value: 0.7578368561966351.

Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:49:56,758] Trial 38 finished with value: 0.7354820326889244 and parameters: {'subsample': 0.2970535696343537, 'dropout_rate': 0.7091602048988066, 'n_estimators': 169, 'learning_rate': 0.09438730372563073}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-17 22:50:01,868] Trial 39 finished with value: 0.7335993436418959 and parameters: {'subsample': 0.1910177201515783, 'dropout_rate': 0.4352656711347185, 'n_estimators': 207, 'learning_rate': 0.0757363212737669}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:50:08,841] Trial 40 finished with value: 0.7334484804878368 and parameters: {'subsample': 0.43117832251264454, 'dropout_rate': 0.8887286631915676, 'n_estimators': 280, 'learning_rate': 0.09984768675953848}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 22:50:18,589] Trial 41 finished with value: 0.749409400058829 and parameters: {'subsample': 0.11354699347645357, 'dropout_rate': 0.7196312595837677, 'n_estimators': 354, 'learning_rate': 0.0993939723603888}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6338028169014085
[I 2024-04-17 22:50:27,426] Trial 42 finished with value: 0.7409198605859304 and parameters: {'subsample': 0.24882413471290432, 'dropout_rate': 0.6179277873601648, 'n_estimators': 333, 'learning_rate': 0.08984125931331685}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.647887323943662
[I 2024-04-17 22:50:37,549] Trial 43 finished with value: 0.7490481126566253 and parameters: {'subsample': 0.13840274528511398, 'dropout_rate': 0.5150829397648921, 'n_estimators': 389, 'learning_rate': 0.09476936625957498}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6244131455399061
[I 2024-04-17 22:50:45,673] Trial 44 finished with value: 0.7436084335839718 and parameters: {'subsample': 0.18909638843168197, 'dropout_rate': 0.6096685459085539, 'n_estimators': 326, 'learning_rate': 0.08737738737724529}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 22:50:56,937] Trial 45 finished with value: 0.6747194387812013 and parameters: {'subsample': 0.7937809606966539, 'dropout_rate': 0.7991522227764232, 'n_estimators': 457, 'learning_rate': 0.09942602881439196}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-17 22:51:03,407] Trial 46 finished with value: 0.7523954959137257 and parameters: {'subsample': 0.13247691307003695, 'dropout_rate': 0.9617844883175679, 'n_estimators': 280, 'learning_rate': 0.08270395057427368}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:51:09,710] Trial 47 finished with value: 0.6915173855527396 and parameters: {'subsample': 0.619857351115649, 'dropout_rate': 0.9881262828291445, 'n_estimators': 272, 'learning_rate': 0.06526882953305241}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6291079812206573
[I 2024-04-17 22:51:14,080] Trial 48 finished with value: 0.7412560841935114 and parameters: {'subsample': 0.14527182024086607, 'dropout_rate': 0.9466636735140487, 'n_estimators': 188, 'learning_rate': 0.08225479287446368}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6338028169014085
[I 2024-04-17 22:51:19,134] Trial 49 finished with value: 0.7454122904692762 and parameters: {'subsample': 0.2440040247899254, 'dropout_rate': 0.9115238723368767, 'n_estimators': 220, 'learning_rate': 0.07376951860699396}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:51:20,106] Trial 50 finished with value: 0.7258316247697152 and parameters: {'subsample': 0.32908238366786347, 'dropout_rate': 0.14501343490387253, 'n_estimators': 40, 'learning_rate': 0.08609095161059174}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.647887323943662
[I 2024-04-17 22:51:27,185] Trial 51 finished with value: 0.7452899695835157 and parameters: {'subsample': 0.12360178179157141, 'dropout_rate': 0.2907738661938799, 'n_estimators': 286, 'learning_rate': 0.09324382188616191}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6244131455399061
[I 2024-04-17 22:51:35,724] Trial 52 finished with value: 0.7489114638870021 and parameters: {'subsample': 0.18962767594906982, 'dropout_rate': 0.7442400087777848, 'n_estimators': 355, 'learning_rate': 0.08833261128186533}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6291079812206573
[I 2024-04-17 22:51:43,109] Trial 53 finished with value: 0.7443776089829439 and parameters: {'subsample': 0.16547142164523715, 'dropout_rate': 0.8459665445183797, 'n_estimators': 315, 'learning_rate': 0.09523720259996994}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6173708920187794
[I 2024-04-17 22:51:49,129] Trial 54 finished with value: 0.7323407198419652 and parameters: {'subsample': 0.20042122380027189, 'dropout_rate': 0.19730482465563026, 'n_estimators': 253, 'learning_rate': 0.09072394766717834}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.647887323943662
[I 2024-04-17 22:51:58,249] Trial 55 finished with value: 0.7484553323914698 and parameters: {'subsample': 0.12858391151022835, 'dropout_rate': 0.6956787703371105, 'n_estimators': 374, 'learning_rate': 0.08421672175719253}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:52:01,798] Trial 56 finished with value: 0.7387479650687808 and parameters: {'subsample': 0.2685907604060433, 'dropout_rate': 0.6555870719053609, 'n_estimators': 152, 'learning_rate': 0.09614265602434488}. Best is trial 11 with value: 0.7578368561966351.

Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6525821596244131
[I 2024-04-17 22:52:09,298] Trial 57 finished with value: 0.7428264940394869 and parameters: {'subsample': 0.10164071286601614, 'dropout_rate': 0.8146315434168232, 'n_estimators': 300, 'learning_rate': 0.04821654031564312}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6244131455399061
[I 2024-04-17 22:52:17,819] Trial 58 finished with value: 0.7402140292169316 and parameters: {'subsample': 0.22603053112615312, 'dropout_rate': 0.8725919027760111, 'n_estimators': 348, 'learning_rate': 0.08101852437894388}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6384976525821596
[I 2024-04-17 22:52:23,430] Trial 59 finished with value: 0.739165710774496 and parameters: {'subsample': 0.1571083370161221, 'dropout_rate': 0.5065802886056728, 'n_estimators': 241, 'learning_rate': 0.08919375774647993}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-17 22:52:29,712] Trial 60 finished with value: 0.6169262912137415 and parameters: {'subsample': 0.9718433307655755, 'dropout_rate': 0.42437170065267305, 'n_estimators': 268, 'learning_rate': 0.03136696153263342}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.647887323943662
[I 2024-04-17 22:52:38,947] Trial 61 finished with value: 0.7466968154058492 and parameters: {'subsample': 0.1260542958713624, 'dropout_rate': 0.7384550058579352, 'n_estimators': 374, 'learning_rate': 0.09993066293153147}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6431924882629108
[I 2024-04-17 22:52:46,390] Trial 62 finished with value: 0.7422353949845876 and parameters: {'subsample': 0.12568839753835293, 'dropout_rate': 0.7084359203973501, 'n_estimators': 317, 'learning_rate': 0.09698813007839849}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6431924882629108
[I 2024-04-17 22:52:55,217] Trial 63 finished with value: 0.7499386978247109 and parameters: {'subsample': 0.17061699509381995, 'dropout_rate': 0.579634336629214, 'n_estimators': 348, 'learning_rate': 0.09226234368890407}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6291079812206573
[I 2024-04-17 22:53:04,743] Trial 64 finished with value: 0.7432232346900737 and parameters: {'subsample': 0.20929995946112884, 'dropout_rate': 0.5781721293046993, 'n_estimators': 388, 'learning_rate': 0.09172480890284726}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6338028169014085
[I 2024-04-17 22:53:14,458] Trial 65 finished with value: 0.7499120938428694 and parameters: {'subsample': 0.16588120363297115, 'dropout_rate': 0.6318137534184929, 'n_estimators': 413, 'learning_rate': 0.0851682963224982}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6291079812206573
[I 2024-04-17 22:53:24,494] Trial 66 finished with value: 0.7494461784130175 and parameters: {'subsample': 0.17881900681359358, 'dropout_rate': 0.6390505829045154, 'n_estimators': 425, 'learning_rate': 0.08521265600328277}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:53:35,469] Trial 67 finished with value: 0.7353568848161964 and parameters: {'subsample': 0.28375464967821434, 'dropout_rate': 0.5798555765478142, 'n_estimators': 450, 'learning_rate': 0.0792599150241583}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6431924882629108
[I 2024-04-17 22:53:47,655] Trial 68 finished with value: 0.7505095590806057 and parameters: {'subsample': 0.17246440371575278, 'dropout_rate': 0.5379574212145599, 'n_estimators': 496, 'learning_rate': 0.0582375351466085}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6244131455399061
[I 2024-04-17 22:53:59,443] Trial 69 finished with value: 0.7384115331897521 and parameters: {'subsample': 0.24391235635800318, 'dropout_rate': 0.11222457805329318, 'n_estimators': 460, 'learning_rate': 0.05452181969732228}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 22:54:11,537] Trial 70 finished with value: 0.7508899001990462 and parameters: {'subsample': 0.16295598134783293, 'dropout_rate': 0.3688737151375503, 'n_estimators': 490, 'learning_rate': 0.008127880939407618}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:54:23,585] Trial 71 finished with value: 0.7016969119087365 and parameters: {'subsample': 0.5300843058226148, 'dropout_rate': 0.37302270062524434, 'n_estimators': 487, 'learning_rate': 0.005163036601524486}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 22:54:36,194] Trial 72 finished with value: 0.7518288673351965 and parameters: {'subsample': 0.1692242541864251, 'dropout_rate': 0.27390250295819696, 'n_estimators': 492, 'learning_rate': 0.05844738151237265}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6338028169014085
[I 2024-04-17 22:54:48,293] Trial 73 finished with value: 0.7417221406464011 and parameters: {'subsample': 0.2094489579875526, 'dropout_rate': 0.27746452988576586, 'n_estimators': 482, 'learning_rate': 0.03794909926307588}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 22:54:59,265] Trial 74 finished with value: 0.7522671714757962 and parameters: {'subsample': 0.14173161828601824, 'dropout_rate': 0.34578330340113894, 'n_estimators': 446, 'learning_rate': 0.021415863721666734}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 22:55:11,524] Trial 75 finished with value: 0.7523379247483366 and parameters: {'subsample': 0.14282140433982918, 'dropout_rate': 0.34163132072065266, 'n_estimators': 497, 'learning_rate': 0.01726784994899718}. Best is trial 11 with value: 0.7578368561966351.

Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-17 22:55:22,218] Trial 76 finished with value: 0.7457043264801018 and parameters: {'subsample': 0.14505723432466983, 'dropout_rate': 0.33640108131081775, 'n_estimators': 441, 'learning_rate': 0.014112503011090724}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 22:55:33,922] Trial 77 finished with value: 0.7542924839022628 and parameters: {'subsample': 0.1001659932429099, 'dropout_rate': 0.23298042188674664, 'n_estimators': 471, 'learning_rate': 0.012190788763402582}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 22:55:44,628] Trial 78 finished with value: 0.7562313492067275 and parameters: {'subsample': 0.10230071936873004, 'dropout_rate': 0.225939626529641, 'n_estimators': 437, 'learning_rate': 0.020469297475297545}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-17 22:55:57,086] Trial 79 finished with value: 0.744394388170672 and parameters: {'subsample': 0.13086573156448753, 'dropout_rate': 0.23010672708268798, 'n_estimators': 472, 'learning_rate': 0.022759616277590038}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 22:56:09,308] Trial 80 finished with value: 0.755431305368709 and parameters: {'subsample': 0.10249576304451584, 'dropout_rate': 0.16367998598156797, 'n_estimators': 437, 'learning_rate': 0.0220582687732976}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 22:56:21,870] Trial 81 finished with value: 0.7552406825142739 and parameters: {'subsample': 0.11441080339464722, 'dropout_rate': 0.17989222885623662, 'n_estimators': 431, 'learning_rate': 0.020627527568966752}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 22:56:33,068] Trial 82 finished with value: 0.7555534469253755 and parameters: {'subsample': 0.10250395385843634, 'dropout_rate': 0.16998763447097437, 'n_estimators': 434, 'learning_rate': 0.026567245480083886}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 22:56:44,249] Trial 83 finished with value: 0.7547020148032307 and parameters: {'subsample': 0.10238580933194333, 'dropout_rate': 0.1712104968362131, 'n_estimators': 412, 'learning_rate': 0.02749553773005476}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 22:56:56,146] Trial 84 finished with value: 0.7545113919487956 and parameters: {'subsample': 0.11638836417739662, 'dropout_rate': 0.16852281331394028, 'n_estimators': 432, 'learning_rate': 0.02766985807404104}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6431924882629108
[I 2024-04-17 22:57:07,174] Trial 85 finished with value: 0.750667988390189 and parameters: {'subsample': 0.11690337184402229, 'dropout_rate': 0.17252909629358576, 'n_estimators': 409, 'learning_rate': 0.030567817735319754}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 22:57:18,244] Trial 86 finished with value: 0.7555995569186684 and parameters: {'subsample': 0.10738500337253638, 'dropout_rate': 0.16175532782229793, 'n_estimators': 435, 'learning_rate': 0.02728342377694924}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 22:57:27,836] Trial 87 finished with value: 0.7544946102073303 and parameters: {'subsample': 0.10086721195892911, 'dropout_rate': 0.21279153426095176, 'n_estimators': 395, 'learning_rate': 0.026659487543042606}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.647887323943662
[I 2024-04-17 22:57:37,956] Trial 88 finished with value: 0.751344209461285 and parameters: {'subsample': 0.18947988356837192, 'dropout_rate': 0.1335168028640485, 'n_estimators': 406, 'learning_rate': 0.03494382428828734}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 22:57:48,756] Trial 89 finished with value: 0.7350924061823955 and parameters: {'subsample': 0.40382580794586076, 'dropout_rate': 0.1201628528883074, 'n_estimators': 434, 'learning_rate': 0.02061509892812536}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 22:58:00,189] Trial 90 finished with value: 0.6910479019846645 and parameters: {'subsample': 0.7057881652016033, 'dropout_rate': 0.15793109190925908, 'n_estimators': 456, 'learning_rate': 0.026295382955541846}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6431924882629108
[I 2024-04-17 22:58:09,410] Trial 91 finished with value: 0.7462797342392766 and parameters: {'subsample': 0.11822625430798545, 'dropout_rate': 0.17190241341715598, 'n_estimators': 381, 'learning_rate': 0.026859386112940725}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.647887323943662
[I 2024-04-17 22:58:21,155] Trial 92 finished with value: 0.7570901931251763 and parameters: {'subsample': 0.14284948904984637, 'dropout_rate': 0.199513812143727, 'n_estimators': 433, 'learning_rate': 0.01852147571794441}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-17 22:58:32,955] Trial 93 finished with value: 0.7525492402507283 and parameters: {'subsample': 0.14744810434088404, 'dropout_rate': 0.19817204830627644, 'n_estimators': 422, 'learning_rate': 0.018312929952124843}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6197183098591549
[I 2024-04-17 22:58:42,995] Trial 94 finished with value: 0.7432070462668608 and parameters: {'subsample': 0.1979961223009301, 'dropout_rate': 0.10511761502180378, 'n_estimators': 399, 'learning_rate': 0.023924049194694444}. Best is trial 11 with value: 0.7578368561966351.

Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-17 22:58:53,859] Trial 95 finished with value: 0.7465701273459027 and parameters: {'subsample': 0.14868254540814063, 'dropout_rate': 0.2580974163537797, 'n_estimators': 438, 'learning_rate': 0.013743877668222288}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6572769953051644
[I 2024-04-17 22:59:05,729] Trial 96 finished with value: 0.7546288485328815 and parameters: {'subsample': 0.10076826375657509, 'dropout_rate': 0.1470863277012879, 'n_estimators': 465, 'learning_rate': 0.033174590996939146}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.647887323943662
[I 2024-04-17 22:59:16,138] Trial 97 finished with value: 0.7467872514651981 and parameters: {'subsample': 0.22570028642335044, 'dropout_rate': 0.13308489668184068, 'n_estimators': 461, 'learning_rate': 0.034011937387859015}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.647887323943662
[I 2024-04-17 22:59:25,345] Trial 98 finished with value: 0.7489000989056703 and parameters: {'subsample': 0.12082568982911768, 'dropout_rate': 0.2162449552251571, 'n_estimators': 424, 'learning_rate': 0.029566697998844583}. Best is trial 11 with value: 0.7578368561966351.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7848101265822784

[I 2024-04-17 22:59:33,021] A new study created in memory with name: no-name-b6e4a658-fa82-441b-9e79-60ee3ecdd395

Fold 5 C-index: 0.5821596244131455
[I 2024-04-17 22:59:33,018] Trial 99 finished with value: 0.6641836751799862 and parameters: {'subsample': 0.9104218782867626, 'dropout_rate': 0.1532151629764999, 'n_estimators': 367, 'learning_rate': 0.019014789800096056}. Best is trial 11 with value: 0.7578368561966351.


* Best trial for C-index:
 FrozenTrial(number=11, state=TrialState.COMPLETE, values=[0.7578368561966351], datetime_start=datetime.datetime(2024, 4, 17, 22, 47, 20, 764574), datetime_complete=datetime.datetime(2024, 4, 17, 22, 47, 28, 620754), params={'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=11, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}


* Best Score for C-index:
 0.7578368561966351

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1847779538599067
Fold 2 IBS: 0.263946415780978
Fold 3 IBS: 0.1617903636180167
Fold 4 IBS: 0.2600787216130082
Fold 5 IBS: 0.23318480871469416
[I 2024-04-17 22:59:35,285] Trial 0 finished with value: 0.22075565271732076 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.22075565271732076.
Fold 1 IBS: 0.2037089559640635
Fold 2 IBS: 0.3014080683205247
Fold 3 IBS: 0.17042892249188574
Fold 4 IBS: 0.31585465097929083
Fold 5 IBS: 0.27370157532625616
[I 2024-04-17 22:59:45,910] Trial 1 finished with value: 0.25302043461640417 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.22075565271732076.
Fold 1 IBS: 0.19557918611245576
Fold 2 IBS: 0.30090488415559263
Fold 3 IBS: 0.16537429721694968
Fold 4 IBS: 0.31368208313434126
Fold 5 IBS: 0.26490979029895373
[I 2024-04-17 22:59:49,294] Trial 2 finished with value: 0.2480900481836586 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.22075565271732076.
Fold 1 IBS: 0.19984939300509375
Fold 2 IBS: 0.29867185430046916
Fold 3 IBS: 0.16607224064552437
Fold 4 IBS: 0.3111838587606932
Fold 5 IBS: 0.26803683949365764
[I 2024-04-17 22:59:53,329] Trial 3 finished with value: 0.24876283724108764 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.22075565271732076.
Fold 1 IBS: 0.19806663470810904
Fold 2 IBS: 0.3006292211879915
Fold 3 IBS: 0.18442862706750995
Fold 4 IBS: 0.31309802900565875
Fold 5 IBS: 0.2690055063230848
[I 2024-04-17 22:59:58,727] Trial 4 finished with value: 0.25304560365847084 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.22075565271732076.
Fold 1 IBS: 0.20340848876726622
Fold 2 IBS: 0.3014078956744048
Fold 3 IBS: 0.16987803315182726
Fold 4 IBS: 0.31585217062420684
Fold 5 IBS: 0.27369201709429525
[I 2024-04-17 23:00:06,045] Trial 5 finished with value: 0.25284772106240005 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.22075565271732076.
Fold 1 IBS: 0.1829350490073511
Fold 2 IBS: 0.22574908076349612
Fold 3 IBS: 0.16688500534550946
Fold 4 IBS: 0.2247124094692705
Fold 5 IBS: 0.21906832093288123
[I 2024-04-17 23:00:09,599] Trial 6 finished with value: 0.2038699731037017 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2038699731037017.
Fold 1 IBS: 0.19276024391446897
Fold 2 IBS: 0.20303779786155224
Fold 3 IBS: 0.17884668693475606
Fold 4 IBS: 0.20856968304886764
Fold 5 IBS: 0.211118754013436
[I 2024-04-17 23:00:10,523] Trial 7 finished with value: 0.1988666331546162 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.1988666331546162.
Fold 1 IBS: 0.1841169774595709
Fold 2 IBS: 0.27502505757765827
Fold 3 IBS: 0.1610534980201046
Fold 4 IBS: 0.26090944510806957
Fold 5 IBS: 0.2349744292756046
[I 2024-04-17 23:00:14,657] Trial 8 finished with value: 0.22321588148820157 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.1988666331546162.
Fold 1 IBS: 0.20447408484228785
Fold 2 IBS: 0.3014080117730072
Fold 3 IBS: 0.1827239722426296
Fold 4 IBS: 0.3158524280280044
Fold 5 IBS: 0.2759459715593507
[I 2024-04-17 23:00:24,375] Trial 9 finished with value: 0.2560808936890559 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.1988666331546162.
Fold 1 IBS: 0.2133785145028611
Fold 2 IBS: 0.22091211268741265
Fold 3 IBS: 0.20387901759065918
Fold 4 IBS: 0.22439199408788554
Fold 5 IBS: 0.21780913258638765
[I 2024-04-17 23:00:24,907] Trial 10 finished with value: 0.21607415429104124 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.1988666331546162.
Fold 1 IBS: 0.2133947249090869
Fold 2 IBS: 0.22105802807283764
Fold 3 IBS: 0.2036691246434108
Fold 4 IBS: 0.2235759745187941
Fold 5 IBS: 0.21777799603810094
[I 2024-04-17 23:00:25,093] Trial 11 finished with value: 0.2158951696364461 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.1988666331546162.
Fold 1 IBS: 0.1871476120615594
Fold 2 IBS: 0.297403850587758
Fold 3 IBS: 0.16628475832893205
Fold 4 IBS: 0.29551249022601284
Fold 5 IBS: 0.25346374715090736
[I 2024-04-17 23:00:27,140] Trial 12 finished with value: 0.23996249167103395 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.1988666331546162.
Fold 1 IBS: 0.19280005315897206
Fold 2 IBS: 0.2974213595064474
Fold 3 IBS: 0.17117639615033295
Fold 4 IBS: 0.30578737203308676
Fold 5 IBS: 0.25431185381872007
[I 2024-04-17 23:00:33,112] Trial 13 finished with value: 0.24429940693351188 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.1988666331546162.
Fold 1 IBS: 0.19784216344977562
Fold 2 IBS: 0.20506180854560294
Fold 3 IBS: 0.18635045949578385
Fold 4 IBS: 0.21499223626865088
Fold 5 IBS: 0.21149042228501566
[I 2024-04-17 23:00:34,896] Trial 14 finished with value: 0.20314741800896577 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.1988666331546162.
Fold 1 IBS: 0.21018321888989736
Fold 2 IBS: 0.21734365927334173
Fold 3 IBS: 0.2002074655533131
Fold 4 IBS: 0.22182505250939247
Fold 5 IBS: 0.21659611545289936
[I 2024-04-17 23:00:36,343] Trial 15 finished with value: 0.21323110233576878 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.1988666331546162.
Fold 1 IBS: 0.20391190961670738
Fold 2 IBS: 0.2103474992415337
Fold 3 IBS: 0.19339791850328025
Fold 4 IBS: 0.21877297557249897
Fold 5 IBS: 0.21360848363027263
[I 2024-04-17 23:00:37,526] Trial 16 finished with value: 0.20800775731285856 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.1988666331546162.
Fold 1 IBS: 0.18288342929944057
Fold 2 IBS: 0.23926430161132384
Fold 3 IBS: 0.16665249308120655
Fold 4 IBS: 0.2362841280803267
Fold 5 IBS: 0.22353483274970617
[I 2024-04-17 23:00:40,009] Trial 17 finished with value: 0.20972383696440078 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.1988666331546162.
Fold 1 IBS: 0.18018919937365419
Fold 2 IBS: 0.24024111720982294
Fold 3 IBS: 0.16259174822496847
Fold 4 IBS: 0.2269350843065675
Fold 5 IBS: 0.22295397631420336
[I 2024-04-17 23:00:46,723] Trial 18 finished with value: 0.20658222508584329 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.1988666331546162.
Fold 1 IBS: 0.1935512869399998
Fold 2 IBS: 0.2023431594465361

Fold 3 IBS: 0.17922415923275167
Fold 4 IBS: 0.19961166444241396
Fold 5 IBS: 0.2127622739815413
[I 2024-04-17 23:00:47,780] Trial 19 finished with value: 0.19749850880864858 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.19749850880864858.
Fold 1 IBS: 0.19305215087556077
Fold 2 IBS: 0.20472965504337676
Fold 3 IBS: 0.18181949060531688
Fold 4 IBS: 0.20360622014004007
Fold 5 IBS: 0.2121793073792273
[I 2024-04-17 23:00:48,643] Trial 20 finished with value: 0.19907736480870436 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.19749850880864858.
Fold 1 IBS: 0.19833784424473092
Fold 2 IBS: 0.20382011576839348
Fold 3 IBS: 0.18744984999694703
Fold 4 IBS: 0.20772318144526708
Fold 5 IBS: 0.21281298574694904
[I 2024-04-17 23:00:49,325] Trial 21 finished with value: 0.20202879544045751 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.19749850880864858.
Fold 1 IBS: 0.21319234752616703
Fold 2 IBS: 0.22073279019144837
Fold 3 IBS: 0.20313821183683503
Fold 4 IBS: 0.22386245547893124
Fold 5 IBS: 0.2175077980822652
[I 2024-04-17 23:00:49,463] Trial 22 finished with value: 0.21568672062312938 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 19 with value: 0.19749850880864858.
Fold 1 IBS: 0.17400701570449942
Fold 2 IBS: 0.23421543573086082
Fold 3 IBS: 0.16538387853791114
Fold 4 IBS: 0.2264150887892661
Fold 5 IBS: 0.22634511933036935
[I 2024-04-17 23:00:52,308] Trial 23 finished with value: 0.20527330761858137 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 19 with value: 0.19749850880864858.
Fold 1 IBS: 0.18497779963313724
Fold 2 IBS: 0.2124184957753865
Fold 3 IBS: 0.16839399220873313
Fold 4 IBS: 0.21192615623352185
Fold 5 IBS: 0.21327382867550682
[I 2024-04-17 23:00:53,464] Trial 24 finished with value: 0.19819805450525713 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 19 with value: 0.19749850880864858.
Fold 1 IBS: 0.18189492677344996
Fold 2 IBS: 0.2613406847101467
Fold 3 IBS: 0.16154029812386547
Fold 4 IBS: 0.2530341774375341
Fold 5 IBS: 0.22930188107334332
[I 2024-04-17 23:00:54,812] Trial 25 finished with value: 0.21742239362366794 and parameters: {'subsample': 0.41513882888547626, 'dropout_rate': 0.92193566363172, 'n_estimators': 70, 'learning_rate': 0.08579428551722094}. Best is trial 19 with value: 0.19749850880864858.
Fold 1 IBS: 0.1921045157085937
Fold 2 IBS: 0.2985918938567073
Fold 3 IBS: 0.16263813544153358
Fold 4 IBS: 0.3060194232926818
Fold 5 IBS: 0.2556802208583101
[I 2024-04-17 23:00:57,699] Trial 26 finished with value: 0.2430068378315653 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.9863699266040719, 'n_estimators': 150, 'learning_rate': 0.06722393082067463}. Best is trial 19 with value: 0.19749850880864858.
Fold 1 IBS: 0.19646939037669842
Fold 2 IBS: 0.30140793076134154
Fold 3 IBS: 0.26381780438053754
Fold 4 IBS: 0.31584892020864663
Fold 5 IBS: 0.2814970895229344
[I 2024-04-17 23:01:06,346] Trial 27 finished with value: 0.2718082270500317 and parameters: {'subsample': 0.26021450312326855, 'dropout_rate': 0.9019594475838296, 'n_estimators': 422, 'learning_rate': 0.06071884280131438}. Best is trial 19 with value: 0.19749850880864858.
Fold 1 IBS: 0.19493667651956206
Fold 2 IBS: 0.30021973088050485
Fold 3 IBS: 0.16582318707762056
Fold 4 IBS: 0.3115140810699333
Fold 5 IBS: 0.26099002390515563
[I 2024-04-17 23:01:10,894] Trial 28 finished with value: 0.2466967398905553 and parameters: {'subsample': 0.5971669636685615, 'dropout_rate': 0.7292365612928325, 'n_estimators': 236, 'learning_rate': 0.046726352221374515}. Best is trial 19 with value: 0.19749850880864858.
Fold 1 IBS: 0.18413484665538984
Fold 2 IBS: 0.28472280021030205
Fold 3 IBS: 0.1618866066703668
Fold 4 IBS: 0.27166544473365584
Fold 5 IBS: 0.23947299482188275
[I 2024-04-17 23:01:12,816] Trial 29 finished with value: 0.22837653861831947 and parameters: {'subsample': 0.3457177033536965, 'dropout_rate': 0.528113503868086, 'n_estimators': 97, 'learning_rate': 0.08423642007181871}. Best is trial 19 with value: 0.19749850880864858.
Fold 1 IBS: 0.17756993100315643
Fold 2 IBS: 0.2710755621921181
Fold 3 IBS: 0.1654736116211466
Fold 4 IBS: 0.27771782206219214
Fold 5 IBS: 0.2400789372188414
[I 2024-04-17 23:01:15,458] Trial 30 finished with value: 0.22638317281949094 and parameters: {'subsample': 0.21287332299822773, 'dropout_rate': 0.8300645798351977, 'n_estimators': 136, 'learning_rate': 0.05802531255595394}. Best is trial 19 with value: 0.19749850880864858.
Fold 1 IBS: 0.19050436524338793
Fold 2 IBS: 0.20209650753431752
Fold 3 IBS: 0.181359327071659
Fold 4 IBS: 0.2005509184205595
Fold 5 IBS: 0.21277066690496657
[I 2024-04-17 23:01:16,309] Trial 31 finished with value: 0.1974563570349781 and parameters: {'subsample': 0.15465256682910847, 'dropout_rate': 0.7665254119155692, 'n_estimators': 42, 'learning_rate': 0.04796619662341173}. Best is trial 31 with value: 0.1974563570349781.
Fold 1 IBS: 0.18363851821684718
Fold 2 IBS: 0.20534906897611818
Fold 3 IBS: 0.1685235180391207
Fold 4 IBS: 0.19688025059149128
Fold 5 IBS: 0.21579783554620208
[I 2024-04-17 23:01:17,760] Trial 32 finished with value: 0.19403783827395588 and parameters: {'subsample': 0.10342193656652618, 'dropout_rate': 0.9389584836732486, 'n_estimators': 75, 'learning_rate': 0.04909887443838165}. Best is trial 32 with value: 0.19403783827395588.
Fold 1 IBS: 0.17633321289346446
Fold 2 IBS: 0.2063386999253905
Fold 3 IBS: 0.1676484189308507
Fold 4 IBS: 0.19295415889277637
Fold 5 IBS: 0.21917398826666037
[I 2024-04-17 23:01:19,379] Trial 33 finished with value: 0.19248969578182845 and parameters: {'subsample': 0.10120824695002664, 'dropout_rate': 0.9165491191113839, 'n_estimators': 84, 'learning_rate': 0.05193153712447138}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.18003029087313457
Fold 2 IBS: 0.20914688939867088
Fold 3 IBS: 0.16851247465102737
Fold 4 IBS: 0.200950943755068
Fold 5 IBS: 0.22126247257255793
[I 2024-04-17 23:01:21,177] Trial 34 finished with value: 0.19598061425009175 and parameters: {'subsample': 0.10905456354152472, 'dropout_rate': 0.9451805114606486, 'n_estimators': 91, 'learning_rate': 0.05207614347752842}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.17630742777777872
Fold 2 IBS: 0.2182082050243597
Fold 3 IBS: 0.16713840695895524
Fold 4 IBS: 0.21298858101935
Fold 5 IBS: 0.22201428796093178
[I 2024-04-17 23:01:23,081] Trial 35 finished with value: 0.19933138174827508 and parameters: {'subsample': 0.17308722579917013, 'dropout_rate': 0.9390389172524675, 'n_estimators': 99, 'learning_rate': 0.05193224978956916}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.18155202440051973
Fold 2 IBS: 0.2978567269479215
Fold 3 IBS: 0.18808242508230796
Fold 4 IBS: 0.3057406134678402
Fold 5 IBS: 0.2596078960214409
[I 2024-04-17 23:01:26,293] Trial 36 finished with value: 0.24656793718400608 and parameters: {'subsample': 0.24636821244258503, 'dropout_rate': 0.8485718080776316, 'n_estimators': 163, 'learning_rate': 0.06778534734243152}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.17446609221673717
Fold 2 IBS: 0.21306149526018467
Fold 3 IBS: 0.16769059733524244
Fold 4 IBS: 0.1953725863754498
Fold 5 IBS: 0.21879812303827226
[I 2024-04-17 23:01:27,923] Trial 37 finished with value: 0.19387777884517726 and parameters: {'subsample': 0.15429797417017294, 'dropout_rate': 0.871289081950897, 'n_estimators': 82, 'learning_rate': 0.05621431261796065}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.1954595504512237
Fold 2 IBS: 0.27763799195839783

Fold 3 IBS: 0.20869306183993658
Fold 4 IBS: 0.2876834849903573
Fold 5 IBS: 0.260862853203865
[I 2024-04-17 23:01:31,677] Trial 38 finished with value: 0.2460673884887561 and parameters: {'subsample': 0.10046511631289198, 'dropout_rate': 0.13272164755980653, 'n_estimators': 190, 'learning_rate': 0.07288612365177065}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.1788954662501559
Fold 2 IBS: 0.21738007419174768
Fold 3 IBS: 0.1657365992847256
Fold 4 IBS: 0.2125458822624607
Fold 5 IBS: 0.21793178152730097
[I 2024-04-17 23:01:33,315] Trial 39 finished with value: 0.1984979607032782 and parameters: {'subsample': 0.28738627010698314, 'dropout_rate': 0.24659691996802535, 'n_estimators': 81, 'learning_rate': 0.05575307634287385}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.19475848336187018
Fold 2 IBS: 0.3014022588392375
Fold 3 IBS: 0.2564843618229486
Fold 4 IBS: 0.3158339295030901
Fold 5 IBS: 0.2800940398069323
[I 2024-04-17 23:01:38,520] Trial 40 finished with value: 0.26971461466681573 and parameters: {'subsample': 0.2196209854488279, 'dropout_rate': 0.8597472474868767, 'n_estimators': 266, 'learning_rate': 0.08018822574072365}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.17592203805054932
Fold 2 IBS: 0.22685049445374852
Fold 3 IBS: 0.16482663428946007
Fold 4 IBS: 0.21316493607740014
Fold 5 IBS: 0.22495628402533796
[I 2024-04-17 23:01:40,804] Trial 41 finished with value: 0.20114407737929918 and parameters: {'subsample': 0.15918724130737896, 'dropout_rate': 0.9393332900965488, 'n_estimators': 120, 'learning_rate': 0.04841825850619165}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.1980224806278271
Fold 2 IBS: 0.20435364792822924
Fold 3 IBS: 0.184191088948508
Fold 4 IBS: 0.2041195497135472
Fold 5 IBS: 0.21268264966779557
[I 2024-04-17 23:01:41,434] Trial 42 finished with value: 0.20067388337718142 and parameters: {'subsample': 0.16397191403724043, 'dropout_rate': 0.8873994799930136, 'n_estimators': 30, 'learning_rate': 0.05142027008972084}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.1770404964795337
Fold 2 IBS: 0.2081158599176227
Fold 3 IBS: 0.16955859095049686
Fold 4 IBS: 0.20000312869458858
Fold 5 IBS: 0.21905197131277165
[I 2024-04-17 23:01:43,760] Trial 43 finished with value: 0.1947540094710027 and parameters: {'subsample': 0.13727427562372588, 'dropout_rate': 0.9473923885297466, 'n_estimators': 120, 'learning_rate': 0.034859476003996887}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.178758668066492
Fold 2 IBS: 0.2511663629340603
Fold 3 IBS: 0.1635419138410169
Fold 4 IBS: 0.24742615199461634
Fold 5 IBS: 0.22859734482940727
[I 2024-04-17 23:01:47,059] Trial 44 finished with value: 0.21389808833311857 and parameters: {'subsample': 0.24871495896102216, 'dropout_rate': 0.9420213833292455, 'n_estimators': 171, 'learning_rate': 0.03623572468577923}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.17775433582557923
Fold 2 IBS: 0.20705429886041607
Fold 3 IBS: 0.1680707010174613
Fold 4 IBS: 0.19256085002863513
Fold 5 IBS: 0.21833461038929466
[I 2024-04-17 23:01:49,174] Trial 45 finished with value: 0.19275495922427727 and parameters: {'subsample': 0.12895481090794836, 'dropout_rate': 0.8658974225549187, 'n_estimators': 111, 'learning_rate': 0.03400538573985265}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.1768986689147144
Fold 2 IBS: 0.24194669631597285
Fold 3 IBS: 0.1630959029148099
Fold 4 IBS: 0.22964817670101217
Fold 5 IBS: 0.22460311349674383
[I 2024-04-17 23:01:53,583] Trial 46 finished with value: 0.20723851166865065 and parameters: {'subsample': 0.2920977508464094, 'dropout_rate': 0.8730810852113111, 'n_estimators': 227, 'learning_rate': 0.024992652172925307}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.17917425563988487
Fold 2 IBS: 0.20764488365058395
Fold 3 IBS: 0.16904388143410598
Fold 4 IBS: 0.20055534983225448
Fold 5 IBS: 0.21483503680247057
[I 2024-04-17 23:01:55,664] Trial 47 finished with value: 0.19425068147185995 and parameters: {'subsample': 0.19162805374994693, 'dropout_rate': 0.8162910503157447, 'n_estimators': 109, 'learning_rate': 0.032184194399474765}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.20766818337246878
Fold 2 IBS: 0.2164138767253405
Fold 3 IBS: 0.19813459740356623
Fold 4 IBS: 0.21903402821643847
Fold 5 IBS: 0.21576032136246706
[I 2024-04-17 23:01:56,025] Trial 48 finished with value: 0.2114022014160562 and parameters: {'subsample': 0.18809150708221256, 'dropout_rate': 0.8083274170680138, 'n_estimators': 15, 'learning_rate': 0.02914145779215542}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.18043408016295348
Fold 2 IBS: 0.206890945465221
Fold 3 IBS: 0.1703622490446351
Fold 4 IBS: 0.20392369396130702
Fold 5 IBS: 0.21404071715258913
[I 2024-04-17 23:01:59,065] Trial 49 finished with value: 0.19513033715734115 and parameters: {'subsample': 0.23097773865937118, 'dropout_rate': 0.7318369699591691, 'n_estimators': 154, 'learning_rate': 0.021849831903106007}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.1826390710895078
Fold 2 IBS: 0.27127138772715403
Fold 3 IBS: 0.1610039587054136
Fold 4 IBS: 0.25964245609594094
Fold 5 IBS: 0.23302801050017735
[I 2024-04-17 23:02:02,765] Trial 50 finished with value: 0.22151697682363874 and parameters: {'subsample': 0.4595274856269892, 'dropout_rate': 0.6653750711126717, 'n_estimators': 191, 'learning_rate': 0.03429513147318532}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.17571158086393768
Fold 2 IBS: 0.2120018372376048
Fold 3 IBS: 0.16540701074175532
Fold 4 IBS: 0.19218046775352365
Fold 5 IBS: 0.21922968325354208
[I 2024-04-17 23:02:05,080] Trial 51 finished with value: 0.19290611597007273 and parameters: {'subsample': 0.143043777223833, 'dropout_rate': 0.8778173673033168, 'n_estimators': 121, 'learning_rate': 0.03677745297416694}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.1729007979420915
Fold 2 IBS: 0.223877299314666
Fold 3 IBS: 0.1660641251374206
Fold 4 IBS: 0.2054507789948194
Fold 5 IBS: 0.22141924345320563
[I 2024-04-17 23:02:07,329] Trial 52 finished with value: 0.19794244896844063 and parameters: {'subsample': 0.1845320204522508, 'dropout_rate': 0.8341272076393323, 'n_estimators': 113, 'learning_rate': 0.04516532814370416}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.18520284875355825
Fold 2 IBS: 0.2014457891736768
Fold 3 IBS: 0.17520379777253434
Fold 4 IBS: 0.19632330375818646
Fold 5 IBS: 0.21421948603976507
[I 2024-04-17 23:02:09,127] Trial 53 finished with value: 0.19447904509954417 and parameters: {'subsample': 0.12325844466931249, 'dropout_rate': 0.7595596235399676, 'n_estimators': 87, 'learning_rate': 0.030561316890500942}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.18887323678772702
Fold 2 IBS: 0.2056091420012348
Fold 3 IBS: 0.1757370567501019
Fold 4 IBS: 0.21223577666819357
Fold 5 IBS: 0.21130993422322
[I 2024-04-17 23:02:10,472] Trial 54 finished with value: 0.19875302928609545 and parameters: {'subsample': 0.7050102269043423, 'dropout_rate': 0.873844933200248, 'n_estimators': 69, 'learning_rate': 0.03597481024435141}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.17503398121566102
Fold 2 IBS: 0.25267941739045047
Fold 3 IBS: 0.1633075850131711
Fold 4 IBS: 0.22784517572577997
Fold 5 IBS: 0.23801893402451083
[I 2024-04-17 23:02:13,135] Trial 55 finished with value: 0.2113770186739147 and parameters: {'subsample': 0.14291027871231018, 'dropout_rate': 0.8279545994461043, 'n_estimators': 139, 'learning_rate': 0.05683357071551504}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.18020430099890192
Fold 2 IBS: 0.21744610951618717
Fold 3 IBS: 0.165933340079953
Fold 4 IBS: 0.21052533877664711
Fold 5 IBS: 0.21620880344903598
[I 2024-04-17 23:02:17,098] Trial 56 finished with value: 0.19806357856414505 and parameters: {'subsample': 0.3156187940318943, 'dropout_rate': 0.9002135137734953, 'n_estimators': 205, 'learning_rate': 0.019506157375919604}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.18398341233838497
Fold 2 IBS: 0.20533839861761072

Fold 3 IBS: 0.17179274184779897
Fold 4 IBS: 0.2023020604730602
Fold 5 IBS: 0.2128803187935294
[I 2024-04-17 23:02:19,347] Trial 57 finished with value: 0.19525938641407686 and parameters: {'subsample': 0.19884444626823589, 'dropout_rate': 0.9684246803707619, 'n_estimators': 118, 'learning_rate': 0.026224807564343304}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.18634017428875163
Fold 2 IBS: 0.20505752506714692
Fold 3 IBS: 0.17286198702629046
Fold 4 IBS: 0.20624864465648918
Fold 5 IBS: 0.21236763215388685
[I 2024-04-17 23:02:20,742] Trial 58 finished with value: 0.196575192638513 and parameters: {'subsample': 0.2794210355838312, 'dropout_rate': 0.997636560541779, 'n_estimators': 72, 'learning_rate': 0.037726737290476445}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.1875362464105871
Fold 2 IBS: 0.288164546870249
Fold 3 IBS: 0.1621145927481335
Fold 4 IBS: 0.2830875800570508
Fold 5 IBS: 0.2422970627653835
[I 2024-04-17 23:02:24,211] Trial 59 finished with value: 0.2326400057702808 and parameters: {'subsample': 0.5470621650242197, 'dropout_rate': 0.8079545528980361, 'n_estimators': 176, 'learning_rate': 0.044322171808807036}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.18410784358976434
Fold 2 IBS: 0.21661269177414494
Fold 3 IBS: 0.16960820618378158
Fold 4 IBS: 0.21569700753916463
Fold 5 IBS: 0.21515333910690376
[I 2024-04-17 23:02:25,325] Trial 60 finished with value: 0.20023581763875184 and parameters: {'subsample': 0.7965581751399381, 'dropout_rate': 0.7509400758041676, 'n_estimators': 57, 'learning_rate': 0.06368989490142424}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.1843629215514338
Fold 2 IBS: 0.20263824486632107
Fold 3 IBS: 0.1732152981806017
Fold 4 IBS: 0.19734080447144994
Fold 5 IBS: 0.21442565189239396
[I 2024-04-17 23:02:27,012] Trial 61 finished with value: 0.19439658419244008 and parameters: {'subsample': 0.1269710185700214, 'dropout_rate': 0.8714824214767224, 'n_estimators': 88, 'learning_rate': 0.03184637726883731}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.18068028892554505
Fold 2 IBS: 0.20439810985618923
Fold 3 IBS: 0.17033748042070163
Fold 4 IBS: 0.1956408850567068
Fold 5 IBS: 0.21651813060169744
[I 2024-04-17 23:02:29,053] Trial 62 finished with value: 0.19351497897216804 and parameters: {'subsample': 0.1321001318040067, 'dropout_rate': 0.8699979553961193, 'n_estimators': 102, 'learning_rate': 0.03247222972419392}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.18985910175479057
Fold 2 IBS: 0.2027700104103004
Fold 3 IBS: 0.17959538976836867
Fold 4 IBS: 0.20107008346395067
Fold 5 IBS: 0.21233336813457207
[I 2024-04-17 23:02:31,207] Trial 63 finished with value: 0.19712559070639646 and parameters: {'subsample': 0.17591255501827835, 'dropout_rate': 0.6944061769173018, 'n_estimators': 109, 'learning_rate': 0.018467874297370027}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.18045608629037713
Fold 2 IBS: 0.21655067700019678
Fold 3 IBS: 0.16563363985598384
Fold 4 IBS: 0.1982931938564886
Fold 5 IBS: 0.2248249452262124
[I 2024-04-17 23:02:33,775] Trial 64 finished with value: 0.19715170844585175 and parameters: {'subsample': 0.10180662017343259, 'dropout_rate': 0.9185816235026883, 'n_estimators': 135, 'learning_rate': 0.04046432704910907}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.20622329821480295
Fold 2 IBS: 0.21380118589836336
Fold 3 IBS: 0.196998602804711
Fold 4 IBS: 0.2173941903507175
Fold 5 IBS: 0.2152256658420065
[I 2024-04-17 23:02:34,231] Trial 65 finished with value: 0.20992858862212022 and parameters: {'subsample': 0.14855496217493377, 'dropout_rate': 0.4372403856305817, 'n_estimators': 20, 'learning_rate': 0.028324652112030977}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.19988783351932785
Fold 2 IBS: 0.2078623669989986
Fold 3 IBS: 0.18987313974543615
Fold 4 IBS: 0.2139254755617486
Fold 5 IBS: 0.21387838926859795
[I 2024-04-17 23:02:36,215] Trial 66 finished with value: 0.2050854410188218 and parameters: {'subsample': 0.2296805090328249, 'dropout_rate': 0.8524469177912155, 'n_estimators': 104, 'learning_rate': 0.010314405754448575}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.18826747667311725
Fold 2 IBS: 0.20326053972134195
Fold 3 IBS: 0.1797144461989464
Fold 4 IBS: 0.20003166654306653
Fold 5 IBS: 0.2138613210088349
[I 2024-04-17 23:02:37,121] Trial 67 finished with value: 0.19702709002906144 and parameters: {'subsample': 0.12586922470198358, 'dropout_rate': 0.8098158363332936, 'n_estimators': 45, 'learning_rate': 0.048871341147939125}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.19676351886661209
Fold 2 IBS: 0.3013922757934974
Fold 3 IBS: 0.2494745450662166
Fold 4 IBS: 0.3157095173191865
Fold 5 IBS: 0.2791109594754344
[I 2024-04-17 23:02:44,522] Trial 68 finished with value: 0.2684901633041894 and parameters: {'subsample': 0.20097784419045336, 'dropout_rate': 0.9149766027210128, 'n_estimators': 371, 'learning_rate': 0.05424358653464354}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.18611976781509423
Fold 2 IBS: 0.20215078868717412
Fold 3 IBS: 0.1752838026612279
Fold 4 IBS: 0.19808981020732633
Fold 5 IBS: 0.21133103033267556
[I 2024-04-17 23:02:46,094] Trial 69 finished with value: 0.19459503994069963 and parameters: {'subsample': 0.1801408905253987, 'dropout_rate': 0.5837231539532588, 'n_estimators': 75, 'learning_rate': 0.032998812098473745}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.17858463530922195
Fold 2 IBS: 0.20570977209671032
Fold 3 IBS: 0.17114759169234645
Fold 4 IBS: 0.19880856976607322
Fold 5 IBS: 0.21500654897954963
[I 2024-04-17 23:02:49,185] Trial 70 finished with value: 0.1938514235687803 and parameters: {'subsample': 0.15364118293351353, 'dropout_rate': 0.8876713295518913, 'n_estimators': 162, 'learning_rate': 0.02239169386387187}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.18676058523830077
Fold 2 IBS: 0.20284561295971917
Fold 3 IBS: 0.1750975099630274
Fold 4 IBS: 0.19963509190553194
Fold 5 IBS: 0.21300011553708917
[I 2024-04-17 23:02:51,726] Trial 71 finished with value: 0.1954677831207337 and parameters: {'subsample': 0.15420379455486916, 'dropout_rate': 0.9662474202068589, 'n_estimators': 128, 'learning_rate': 0.02116217856925002}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.19488609106457092
Fold 2 IBS: 0.2070348585891667
Fold 3 IBS: 0.1859896291376138
Fold 4 IBS: 0.20606908252814746
Fold 5 IBS: 0.21390747143926966
[I 2024-04-17 23:02:54,614] Trial 72 finished with value: 0.20157742655175373 and parameters: {'subsample': 0.10367358827918892, 'dropout_rate': 0.8901402491105642, 'n_estimators': 148, 'learning_rate': 0.010503273483871027}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.1767344581008312
Fold 2 IBS: 0.22078122381951953
Fold 3 IBS: 0.17000845699244813
Fold 4 IBS: 0.21354630091828136
Fold 5 IBS: 0.22908560109272857
[I 2024-04-17 23:02:56,483] Trial 73 finished with value: 0.20203120818476172 and parameters: {'subsample': 0.1331021166214576, 'dropout_rate': 0.9231827819914536, 'n_estimators': 98, 'learning_rate': 0.06031671282082033}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.17763656773516312
Fold 2 IBS: 0.21033263067538902
Fold 3 IBS: 0.16868790722334437
Fold 4 IBS: 0.2097662281952136
Fold 5 IBS: 0.21552040618270604
[I 2024-04-17 23:02:59,722] Trial 74 finished with value: 0.19638874800236322 and parameters: {'subsample': 0.2239726260516216, 'dropout_rate': 0.8432392233077666, 'n_estimators': 162, 'learning_rate': 0.0237257450761158}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.17729166501926566
Fold 2 IBS: 0.21565486761125868
Fold 3 IBS: 0.1666331300212957
Fold 4 IBS: 0.20700114074596712
Fold 5 IBS: 0.22259358175704866
[I 2024-04-17 23:03:01,423] Trial 75 finished with value: 0.1978348770309672 and parameters: {'subsample': 0.1675265902042259, 'dropout_rate': 0.2979389867392314, 'n_estimators': 82, 'learning_rate': 0.06420186915210298}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.18820944938685744
Fold 2 IBS: 0.20183447993468964

Fold 3 IBS: 0.1768709426358127
Fold 4 IBS: 0.20632982470382874
Fold 5 IBS: 0.21191906114054931
[I 2024-04-17 23:03:02,664] Trial 76 finished with value: 0.19703275156034755 and parameters: {'subsample': 0.25000396058466057, 'dropout_rate': 0.7775320006294101, 'n_estimators': 59, 'learning_rate': 0.03885240695529241}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.1745666770118572
Fold 2 IBS: 0.21506035715623517
Fold 3 IBS: 0.16458221931869077
Fold 4 IBS: 0.1938397936924758
Fold 5 IBS: 0.22380597224810042
[I 2024-04-17 23:03:04,706] Trial 77 finished with value: 0.19437100388547188 and parameters: {'subsample': 0.12833873816913505, 'dropout_rate': 0.8893706747993337, 'n_estimators': 107, 'learning_rate': 0.045535008082138985}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.19104172238595335
Fold 2 IBS: 0.20300694345738796
Fold 3 IBS: 0.17899313349281026
Fold 4 IBS: 0.20435155111555744
Fold 5 IBS: 0.21197899174341994
[I 2024-04-17 23:03:07,159] Trial 78 finished with value: 0.1978744684390258 and parameters: {'subsample': 0.2013271079398013, 'dropout_rate': 0.9492917365085763, 'n_estimators': 129, 'learning_rate': 0.01640494051713736}. Best is trial 33 with value: 0.19248969578182845.
Fold 1 IBS: 0.17847983698841616
Fold 2 IBS: 0.20634217083753054
Fold 3 IBS: 0.17179581952764147
Fold 4 IBS: 0.18836864616697346
Fold 5 IBS: 0.21547899219232516
[I 2024-04-17 23:03:07,885] Trial 79 finished with value: 0.19209309314257733 and parameters: {'subsample': 0.16017435596427068, 'dropout_rate': 0.863277599430235, 'n_estimators': 35, 'learning_rate': 0.0983514933405076}. Best is trial 79 with value: 0.19209309314257733.
Fold 1 IBS: 0.1804819602416447
Fold 2 IBS: 0.20577113313994072
Fold 3 IBS: 0.1731894322248581
Fold 4 IBS: 0.18861309361627912
Fold 5 IBS: 0.21441291060745551
[I 2024-04-17 23:03:08,555] Trial 80 finished with value: 0.1924937059660356 and parameters: {'subsample': 0.16014761585568627, 'dropout_rate': 0.8631031345765605, 'n_estimators': 32, 'learning_rate': 0.09940427582722745}. Best is trial 79 with value: 0.19209309314257733.
Fold 1 IBS: 0.20284354748120811
Fold 2 IBS: 0.2109982844511359
Fold 3 IBS: 0.19345180897627695
Fold 4 IBS: 0.21155658834787067
Fold 5 IBS: 0.21307464616649413
[I 2024-04-17 23:03:08,818] Trial 81 finished with value: 0.20638497508459713 and parameters: {'subsample': 0.1594690874266902, 'dropout_rate': 0.8593767204550611, 'n_estimators': 9, 'learning_rate': 0.09991530821170493}. Best is trial 79 with value: 0.19209309314257733.
Fold 1 IBS: 0.17936702153116413
Fold 2 IBS: 0.20621593102359562
Fold 3 IBS: 0.169643711748918
Fold 4 IBS: 0.18797766224106235
Fold 5 IBS: 0.21743568896340468
[I 2024-04-17 23:03:09,628] Trial 82 finished with value: 0.19212800310162897 and parameters: {'subsample': 0.11698930466481196, 'dropout_rate': 0.9061468990111938, 'n_estimators': 37, 'learning_rate': 0.09517961504898727}. Best is trial 79 with value: 0.19209309314257733.
Fold 1 IBS: 0.18180599003433068
Fold 2 IBS: 0.20554915644790753
Fold 3 IBS: 0.1727878887721897
Fold 4 IBS: 0.19256961573906226
Fold 5 IBS: 0.21302978158870178
[I 2024-04-17 23:03:10,260] Trial 83 finished with value: 0.1931484865164384 and parameters: {'subsample': 0.14359941719091987, 'dropout_rate': 0.796344400633666, 'n_estimators': 30, 'learning_rate': 0.09396682273966606}. Best is trial 79 with value: 0.19209309314257733.
Fold 1 IBS: 0.17899011756364228
Fold 2 IBS: 0.2050307480083848
Fold 3 IBS: 0.1723369822191308
Fold 4 IBS: 0.19166297360261195
Fold 5 IBS: 0.21622340733775047
[I 2024-04-17 23:03:11,054] Trial 84 finished with value: 0.19284884574630407 and parameters: {'subsample': 0.12422116231823523, 'dropout_rate': 0.781705337639682, 'n_estimators': 36, 'learning_rate': 0.08925030240880304}. Best is trial 79 with value: 0.19209309314257733.
Fold 1 IBS: 0.18194511139519967
Fold 2 IBS: 0.20233920385309936
Fold 3 IBS: 0.17507640712010392
Fold 4 IBS: 0.19350480720379395
Fold 5 IBS: 0.21440982373830925
[I 2024-04-17 23:03:11,710] Trial 85 finished with value: 0.19345507066210121 and parameters: {'subsample': 0.11925181974750909, 'dropout_rate': 0.7916274114203559, 'n_estimators': 31, 'learning_rate': 0.08948657682906}. Best is trial 79 with value: 0.19209309314257733.
Fold 1 IBS: 0.17999169443613056
Fold 2 IBS: 0.20566409347367404
Fold 3 IBS: 0.17040063965883434
Fold 4 IBS: 0.1880634220187218
Fold 5 IBS: 0.21743058198653598
[I 2024-04-17 23:03:12,489] Trial 86 finished with value: 0.19231008631477936 and parameters: {'subsample': 0.11687428058758571, 'dropout_rate': 0.7807697182191684, 'n_estimators': 38, 'learning_rate': 0.09170790851476382}. Best is trial 79 with value: 0.19209309314257733.
Fold 1 IBS: 0.18273039416545048
Fold 2 IBS: 0.21743582844748702
Fold 3 IBS: 0.16725519202715744
Fold 4 IBS: 0.21706925177285633
Fold 5 IBS: 0.21498870202901188
[I 2024-04-17 23:03:13,296] Trial 87 finished with value: 0.19989587368839262 and parameters: {'subsample': 0.5999896702644302, 'dropout_rate': 0.7437944076961742, 'n_estimators': 40, 'learning_rate': 0.09301462697446011}. Best is trial 79 with value: 0.19209309314257733.
Fold 1 IBS: 0.1890318755585093
Fold 2 IBS: 0.20319075344834858
Fold 3 IBS: 0.17770715064542125
Fold 4 IBS: 0.19531132175825155
Fold 5 IBS: 0.21222351277372872
[I 2024-04-17 23:03:13,825] Trial 88 finished with value: 0.19549292283685188 and parameters: {'subsample': 0.17660279820138589, 'dropout_rate': 0.7159223581536494, 'n_estimators': 24, 'learning_rate': 0.09526954468640439}. Best is trial 79 with value: 0.19209309314257733.
Fold 1 IBS: 0.2120854693639085
Fold 2 IBS: 0.22005799950366126
Fold 3 IBS: 0.20308800355774437
Fold 4 IBS: 0.22384977655644536
Fold 5 IBS: 0.21721317410121718
[I 2024-04-17 23:03:13,943] Trial 89 finished with value: 0.21525888461659531 and parameters: {'subsample': 0.26699502893511096, 'dropout_rate': 0.7833030959022801, 'n_estimators': 1, 'learning_rate': 0.09997219743483908}. Best is trial 79 with value: 0.19209309314257733.
Fold 1 IBS: 0.19928540770054018
Fold 2 IBS: 0.2082232070387051
Fold 3 IBS: 0.18860370095201415
Fold 4 IBS: 0.21049559795305975
Fold 5 IBS: 0.2120052504162639
[I 2024-04-17 23:03:14,295] Trial 90 finished with value: 0.2037226328121166 and parameters: {'subsample': 0.21201641774364122, 'dropout_rate': 0.6429162720033311, 'n_estimators': 14, 'learning_rate': 0.08638091361117765}. Best is trial 79 with value: 0.19209309314257733.
Fold 1 IBS: 0.1816542131972094
Fold 2 IBS: 0.20247472567836128
Fold 3 IBS: 0.17478138596389525
Fold 4 IBS: 0.1932046418694245
Fold 5 IBS: 0.21451059979963286
[I 2024-04-17 23:03:14,951] Trial 91 finished with value: 0.19332511330170465 and parameters: {'subsample': 0.11927630700839865, 'dropout_rate': 0.8019588934302221, 'n_estimators': 31, 'learning_rate': 0.09081487966621639}. Best is trial 79 with value: 0.19209309314257733.
Fold 1 IBS: 0.17667019793149416
Fold 2 IBS: 0.20907304259340798
Fold 3 IBS: 0.1660319239121804
Fold 4 IBS: 0.18781699109868358
Fold 5 IBS: 0.21905466708668733
[I 2024-04-17 23:03:15,935] Trial 92 finished with value: 0.1917293645244907 and parameters: {'subsample': 0.11041827858907698, 'dropout_rate': 0.6986980791099663, 'n_estimators': 49, 'learning_rate': 0.09046566569192395}. Best is trial 92 with value: 0.1917293645244907.
Fold 1 IBS: 0.17668812259748876
Fold 2 IBS: 0.20430036118707598
Fold 3 IBS: 0.16971113494257217
Fold 4 IBS: 0.19525938064768616
Fold 5 IBS: 0.21699804570549705
[I 2024-04-17 23:03:17,225] Trial 93 finished with value: 0.19259140901606403 and parameters: {'subsample': 0.10194660745034816, 'dropout_rate': 0.7000283515805, 'n_estimators': 50, 'learning_rate': 0.08117384472031508}. Best is trial 92 with value: 0.1917293645244907.
Fold 1 IBS: 0.1767580130391722
Fold 2 IBS: 0.20420345242091179
Fold 3 IBS: 0.16978019107115092
Fold 4 IBS: 0.19527642655231894
Fold 5 IBS: 0.2169193104863786
[I 2024-04-17 23:03:18,289] Trial 94 finished with value: 0.1925874787139865 and parameters: {'subsample': 0.1016990942499561, 'dropout_rate': 0.6965055530253588, 'n_estimators': 50, 'learning_rate': 0.08077924912008731}. Best is trial 92 with value: 0.1917293645244907.
Fold 1 IBS: 0.17744463644990852
Fold 2 IBS: 0.20310842140997196

Fold 3 IBS: 0.17010139853511608
Fold 4 IBS: 0.19439133210270948
Fold 5 IBS: 0.21636761888494468
[I 2024-04-17 23:03:19,307] Trial 95 finished with value: 0.19228268147653013 and parameters: {'subsample': 0.10055429139334193, 'dropout_rate': 0.6908936589981939, 'n_estimators': 48, 'learning_rate': 0.0808620829739847}. Best is trial 92 with value: 0.1917293645244907.
Fold 1 IBS: 0.1754714248610337
Fold 2 IBS: 0.20687976993404011
Fold 3 IBS: 0.16871962448033315
Fold 4 IBS: 0.19607070549360459
Fold 5 IBS: 0.21890017771558762
[I 2024-04-17 23:03:20,433] Trial 96 finished with value: 0.19320834049691987 and parameters: {'subsample': 0.10090387348188092, 'dropout_rate': 0.6677531118459461, 'n_estimators': 54, 'learning_rate': 0.08353446450876525}. Best is trial 92 with value: 0.1917293645244907.
Fold 1 IBS: 0.17182683311298752
Fold 2 IBS: 0.21978092295865811
Fold 3 IBS: 0.16495094446781117
Fold 4 IBS: 0.19846916545417698
Fold 5 IBS: 0.2208904472271583
[I 2024-04-17 23:03:21,773] Trial 97 finished with value: 0.19518366264415843 and parameters: {'subsample': 0.17285098125974277, 'dropout_rate': 0.7058983050961053, 'n_estimators': 66, 'learning_rate': 0.07766176016693337}. Best is trial 92 with value: 0.1917293645244907.
Fold 1 IBS: 0.17559243986421477
Fold 2 IBS: 0.21078220340049159
Fold 3 IBS: 0.1673161047769047
Fold 4 IBS: 0.18705337038762296
Fold 5 IBS: 0.220586652513671
[I 2024-04-17 23:03:22,649] Trial 98 finished with value: 0.192266154188581 and parameters: {'subsample': 0.1175023864573252, 'dropout_rate': 0.6888884496517775, 'n_estimators': 43, 'learning_rate': 0.09779581745888394}. Best is trial 92 with value: 0.1917293645244907.
Fold 1 IBS: 0.17500693936788922
Fold 2 IBS: 0.20707616102569537
Fold 3 IBS: 0.1682084493290222
Fold 4 IBS: 0.19297864858716038
Fold 5 IBS: 0.21934843533672232
[I 2024-04-17 23:03:24,066] Trial 99 finished with value: 0.1925237267292979 and parameters: {'subsample': 0.10073226802781729, 'dropout_rate': 0.6050256408630418, 'n_estimators': 46, 'learning_rate': 0.09781892407403846}. Best is trial 92 with value: 0.1917293645244907.


* Best trial for IBS:
 FrozenTrial(number=92, state=TrialState.COMPLETE, values=[0.1917293645244907], datetime_start=datetime.datetime(2024, 4, 17, 23, 3, 14, 952864), datetime_complete=datetime.datetime(2024, 4, 17, 23, 3, 15, 935003), params={'subsample': 0.11041827858907698, 'dropout_rate': 0.6986980791099663, 'n_estimators': 49, 'learning_rate': 0.09046566569192395}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=92, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.11041827858907698, 'dropout_rate': 0.6986980791099663, 'n_estimators': 49, 'learning_rate': 0.09046566569192395}


* Best Score for IBS:
 0.1917293645244907

In [72]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [73]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.758
train_ibs:  0.192

#### Test

In [74]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [75]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.10580803679784617,
                                              learning_rate=0.08933703080421439,
                                              n_estimators=324,
                                              random_state=123,
                                              subsample=0.11557957726835853)

C-index score: 0.663

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.6986980791099663,
                                              learning_rate=0.09046566569192395,
                                              n_estimators=49, random_state=123,
                                              subsample=0.11041827858907698)

IBS: 0.206

In [76]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [77]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
ExtraSurvivalTrees               0.886   1.0
Randomsurvivalforest             0.864   2.0
GradientBoosting                 0.758   3.5
ComponentwiseGradientBoosting    0.758   3.5
CoxElastic                       0.752   5.0
CoxRidge                         0.696   6.0
CoxLasso                         0.618   7.0

In [78]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.179   1.0
Randomsurvivalforest           0.183   2.0
ComponentwiseGradientBoosting  0.192   3.0
CoxElastic                     0.201   4.0
GradientBoosting               0.208   5.0
CoxRidge                       0.217   6.0
CoxLasso                       0.312   7.0

In [79]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ComponentwiseGradientBoosting    0.663   1.0
ExtraSurvivalTrees               0.662   2.0
Randomsurvivalforest             0.629   3.0
GradientBoosting                 0.618   4.0
CoxRidge                         0.593   5.5
CoxElastic                       0.593   5.5
CoxLasso                         0.557   7.0

In [80]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.200   1.0
Randomsurvivalforest           0.205   2.0
ComponentwiseGradientBoosting  0.206   3.0
GradientBoosting               0.213   4.0
CoxElastic                     0.220   5.0
CoxRidge                       0.221   6.0
CoxLasso                       0.393   7.0

In [81]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/os/minmax/no_selection/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_os_minmax_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [82]:
from datetime import date

current_date = date.today()
print(current_date)

2024-04-17