In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
 
from sklearn.preprocessing import MinMaxScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

## Test dataset: MAASTRO

In [5]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [6]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [7]:
# need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [8]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,OS,OS_event
0,1,55,0,0,1,0,0,1,1,1,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,44.43,1.0
3,4,61,1,0,0,0,1,1,0,1,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,37.20,1.0
4,6,70,0,0,1,0,0,1,1,1,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,19.00,1.0
95,111,63,0,0,0,0,1,0,0,1,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [9]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [10]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [11]:
# Set X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# Set y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [12]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [13]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 388)
y_train:  (139,)

In [14]:
# Change the name of a column 'OS_event' in the clincial_test 
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [15]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 390)

## Feature Selection

### COX PLSR

In [16]:
# Choose features from the result of Cox PLSR in R
selected_features = [
"glcm_ClusterShade_d_1_PET_b2",
"shape_MajorAxisLength",
"gldm_DependenceEntropy_d_1_PET_c04",
"ngtdm_Strength_d_1_CT_b20",
"LBP_120_PET",
"glcm_ClusterProminence_d_1_PET_b2"
]

In [17]:
X_plsr = X.loc[:, selected_features]
X_new = X_plsr.copy()

In [18]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, selected_features]

# Standardization

In [19]:
# Copy the original X for later 
original_X = X.copy()

In [20]:
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Standardize X_new, the new data with the selected features only 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = MinMaxScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [21]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [22]:
X_new

,glcm_ClusterShade_d_1_PET_b2,shape_MajorAxisLength,gldm_DependenceEntropy_d_1_PET_c04,ngtdm_Strength_d_1_CT_b20,LBP_120_PET,glcm_ClusterProminence_d_1_PET_b2
0,10.600998,42.073251,6.795642,4.288423,0.140311,434.830466
1,1.734460,24.613845,6.637753,9.401886,0.191058,19.257701
2,1.761780,48.030294,6.894124,3.973266,0.126531,29.527599
3,0.159909,25.589900,6.578202,8.266749,0.192388,1.515103
4,-0.177915,34.684750,6.800483,4.402019,0.202073,10.006413
...,...,...,...,...,...,...
134,9.578449,33.069705,6.662260,1.177483,0.152626,109.970854
135,-0.557128,41.043692,6.874148,4.537614,0.142778,12.574172
136,28.029294,36.618802,6.659339,3.036865,0.140582,386.172283
137,0.111923,45.870392,6.812758,2.379513,0.156640,15.793118
138,-0.088922,30.363259,6.758582,4.195099,0.147644,154.318527

In [23]:
X_new_std

,glcm_ClusterShade_d_1_PET_b2,shape_MajorAxisLength,gldm_DependenceEntropy_d_1_PET_c04,ngtdm_Strength_d_1_CT_b20,LBP_120_PET,glcm_ClusterProminence_d_1_PET_b2
0,0.248118,0.350904,0.865889,0.098124,0.174091,0.052658
1,0.222288,0.123069,0.788611,0.227868,0.456736,0.002252
2,0.222368,0.428640,0.914091,0.090128,0.097341,0.003498
3,0.217702,0.135806,0.759464,0.199066,0.464144,0.000100
4,0.216717,0.254489,0.868259,0.101007,0.518081,0.001130
...,...,...,...,...,...,...
134,0.245139,0.233413,0.800606,0.019191,0.242682,0.013255
135,0.215613,0.337469,0.904313,0.104447,0.187835,0.001442
136,0.298890,0.279727,0.799176,0.066369,0.175602,0.046756
137,0.217562,0.400455,0.874266,0.049690,0.265036,0.001832
138,0.216977,0.198096,0.847750,0.095756,0.214934,0.018634

In [24]:
MAASTRO_new

,glcm_ClusterShade_d_1_PET_b2,shape_MajorAxisLength,gldm_DependenceEntropy_d_1_PET_c04,ngtdm_Strength_d_1_CT_b20,LBP_120_PET,glcm_ClusterProminence_d_1_PET_b2
0,-6.132486,50.002093,6.814563,1.344991,0.122209,479.762323
1,11.365721,41.753334,6.154990,9.021133,0.128976,93.366330
2,18.556645,44.375483,6.673632,4.686304,0.137282,393.917369
3,6.670130,46.115989,6.577609,8.227208,0.171595,81.628434
4,6.613032,54.394967,6.735323,3.416011,0.128134,61.795989
...,...,...,...,...,...,...
94,467.061873,34.218615,6.559987,8.997680,0.137194,19154.348390
95,34.619690,51.046869,6.579052,3.803795,0.137620,368.948026
96,4.698589,50.417953,6.675182,3.847965,0.115099,33.083289
97,20.628059,44.901412,6.636306,2.686505,0.117654,404.363216
98,23.257105,36.574294,6.421117,7.690637,0.156924,249.469840

In [25]:
MAASTRO_new_std

,glcm_ClusterShade_d_1_PET_b2,shape_MajorAxisLength,gldm_DependenceEntropy_d_1_PET_c04,ngtdm_Strength_d_1_CT_b20,LBP_120_PET,glcm_ClusterProminence_d_1_PET_b2
0,0.199371,0.454371,0.875150,0.023441,0.073271,0.058108
1,0.250346,0.346729,0.552325,0.218207,0.110963,0.011241
2,0.271294,0.380947,0.806172,0.108220,0.157221,0.047695
3,0.236667,0.403660,0.759174,0.198063,0.348334,0.009817
4,0.236501,0.511695,0.836366,0.075989,0.106269,0.007412
...,...,...,...,...,...,...
94,1.577870,0.248406,0.750549,0.217612,0.156731,2.323190
95,0.318089,0.468005,0.759880,0.085828,0.159105,0.044667
96,0.230923,0.459798,0.806930,0.086949,0.033672,0.003929
97,0.277329,0.387810,0.787903,0.057479,0.047900,0.048962
98,0.284988,0.279146,0.682580,0.184448,0.266623,0.030175

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [26]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:53:17,347] A new study created in memory with name: no-name-daccdf6c-ea10-46cf-b7ff-49dfb00b062c

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6877637130801688

[I 2024-04-17 13:53:25,068] A new study created in memory with name: no-name-7d0df791-cd39-4438-a2ff-7f247158aafc

Fold 5 C-index: 0.7370892018779343
[I 2024-04-17 13:53:25,059] Trial 0 finished with value: 0.7221538653954912 and parameters: {}. Best is trial 0 with value: 0.7221538653954912.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7221538653954912], datetime_start=datetime.datetime(2024, 4, 17, 13, 53, 17, 422050), datetime_complete=datetime.datetime(2024, 4, 17, 13, 53, 25, 59293), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7221538653954912

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.18540223318183244
Fold 2 IBS: 0.15964445582496828
Fold 3 IBS: 0.141452621684816
Fold 4 IBS: 0.21107747669358115
Fold 5 IBS: 0.16928388234449362
[I 2024-04-17 13:53:25,674] Trial 0 finished with value: 0.17337213394593828 and parameters: {}. Best is trial 0 with value: 0.17337213394593828.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.17337213394593828], datetime_start=datetime.datetime(2024, 4, 17, 13, 53, 25, 127808), datetime_complete=datetime.datetime(2024, 4, 17, 13, 53, 25, 674125), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.17337213394593828

In [27]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [28]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.722
train_ibs:  0.173

#### Test

In [29]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [30]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.58
IBS score: 0.246

In [31]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [32]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [33]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:53:25,997] A new study created in memory with name: no-name-9725a503-fa26-4847-95a3-2040c5af6357

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6017316017316018

[I 2024-04-17 13:53:26,253] A new study created in memory with name: no-name-7fec3fdc-2b79-4332-a277-3ee19e1f25c5

Fold 2 C-index: 0.734375
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 13:53:26,232] Trial 0 finished with value: 0.6781791996649223 and parameters: {}. Best is trial 0 with value: 0.6781791996649223.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6781791996649223], datetime_start=datetime.datetime(2024, 4, 17, 13, 53, 26, 34621), datetime_complete=datetime.datetime(2024, 4, 17, 13, 53, 26, 231741), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6781791996649223

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652137310474
Fold 2 IBS: 0.22157791529947765
Fold 3 IBS: 0.2045359462877086
Fold 4 IBS: 0.2247380399747716
Fold 5 IBS: 0.21812431382491174
[I 2024-04-17 13:53:26,478] Trial 0 finished with value: 0.2165905473519949 and parameters: {}. Best is trial 0 with value: 0.2165905473519949.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2165905473519949], datetime_start=datetime.datetime(2024, 4, 17, 13, 53, 26, 292719), datetime_complete=datetime.datetime(2024, 4, 17, 13, 53, 26, 478062), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2165905473519949

In [34]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [35]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.678
train_ibs:  0.217

#### Test

In [36]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [37]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.563

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [38]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [39]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:53:26,752] A new study created in memory with name: no-name-35354e6d-f4b9-40cd-93b0-87204ce6ff31

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697

[I 2024-04-17 13:53:27,221] A new study created in memory with name: no-name-ff59cec0-15eb-4f3e-a6a7-84fa9ca9bb87

Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:27,211] Trial 0 finished with value: 0.723941851655977 and parameters: {}. Best is trial 0 with value: 0.723941851655977.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.723941851655977], datetime_start=datetime.datetime(2024, 4, 17, 13, 53, 26, 794990), datetime_complete=datetime.datetime(2024, 4, 17, 13, 53, 27, 211453), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.723941851655977

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.18681207190116883
Fold 2 IBS: 0.15997942375885582
Fold 3 IBS: 0.14332080814949552
Fold 4 IBS: 0.20639363524620555
Fold 5 IBS: 0.16928556717267654
[I 2024-04-17 13:53:27,834] Trial 0 finished with value: 0.17315830124568046 and parameters: {}. Best is trial 0 with value: 0.17315830124568046.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.17315830124568046], datetime_start=datetime.datetime(2024, 4, 17, 13, 53, 27, 264542), datetime_complete=datetime.datetime(2024, 4, 17, 13, 53, 27, 833680), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.17315830124568046

In [40]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [41]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.724
train_ibs:  0.173

#### Test

In [42]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [43]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.579

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.245

In [44]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [45]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:53:28,278] A new study created in memory with name: no-name-d70d43ea-0d1b-4495-903e-14e73722822b

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:28,851] Trial 0 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:29,420] Trial 1 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:30,137] Trial 2 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:30,718] Trial 3 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:31,283] Trial 4 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:31,860] Trial 5 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:32,594] Trial 6 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:33,204] Trial 7 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:33,893] Trial 8 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:34,433] Trial 9 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:34,936] Trial 10 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 13:53:35,113] Trial 11 finished with value: 0.6818827456832424 and parameters: {'l1_ratio': 0.046971505265140434}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:35,748] Trial 12 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.21309581087335225}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:36,233] Trial 13 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.743964055575976}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:36,852] Trial 14 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.21599024455432275}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:37,416] Trial 15 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.820763570686791}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:38,216] Trial 16 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.5880713606511995}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:38,944] Trial 17 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.35870521424355084}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 13:53:39,063] Trial 18 finished with value: 0.6818827456832424 and parameters: {'l1_ratio': 0.039318771596377255}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:39,528] Trial 19 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.608409044915716}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:39,946] Trial 20 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.8744063907908842}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:40,370] Trial 21 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.26843065456411686}. Best is trial 0 with value: 0.723941851655977.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:40,771] Trial 22 finished with value: 0.7373347087988342 and parameters: {'l1_ratio': 0.13361135845786085}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:41,137] Trial 23 finished with value: 0.7165554880196134 and parameters: {'l1_ratio': 0.1124690541840564}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666

Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:41,626] Trial 24 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.3109747602700048}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:41,956] Trial 25 finished with value: 0.7373347087988342 and parameters: {'l1_ratio': 0.1309253064678097}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 13:53:42,122] Trial 26 finished with value: 0.6818827456832424 and parameters: {'l1_ratio': 0.015423757551295547}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:42,453] Trial 27 finished with value: 0.7373347087988342 and parameters: {'l1_ratio': 0.13017778313580006}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:42,735] Trial 28 finished with value: 0.7165554880196134 and parameters: {'l1_ratio': 0.10987868244329208}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:43,138] Trial 29 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.1399312072140513}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:43,631] Trial 30 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.17458699667056254}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:44,102] Trial 31 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.31121577107848636}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 13:53:44,248] Trial 32 finished with value: 0.6818827456832424 and parameters: {'l1_ratio': 0.08393007425738182}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:44,740] Trial 33 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.4740179166026411}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:45,104] Trial 34 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:45,626] Trial 35 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.2553877674181744}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:46,035] Trial 36 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.6686552770982201}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:46,414] Trial 37 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.8013809955909406}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:46,879] Trial 38 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.5437498383698247}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 13:53:47,018] Trial 39 finished with value: 0.6818827456832424 and parameters: {'l1_ratio': 0.0023714148387815603}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:47,429] Trial 40 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.42198151846766346}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:47,975] Trial 41 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.17633522029243162}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 13:53:48,108] Trial 42 finished with value: 0.6818827456832424 and parameters: {'l1_ratio': 0.0851252681288473}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:48,610] Trial 43 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.3006592764471451}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:49,167] Trial 44 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.2203711638730681}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:49,794] Trial 45 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.3759578634505477}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:50,166] Trial 46 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.14098610478707835}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 13:53:50,305] Trial 47 finished with value: 0.6818827456832424 and parameters: {'l1_ratio': 0.07895395391701968}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921

Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:50,613] Trial 48 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.908082736959313}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:51,082] Trial 49 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.26037470874224194}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 13:53:51,178] Trial 50 finished with value: 0.6818827456832424 and parameters: {'l1_ratio': 0.05069122998976218}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:51,617] Trial 51 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.22379278863088314}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:52,012] Trial 52 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.14229901072820175}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:52,421] Trial 53 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.19230387435474083}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:52,833] Trial 54 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.345644991925916}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:53,236] Trial 55 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.6652563487214879}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:53,618] Trial 56 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.7369259786535977}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:53,994] Trial 57 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.46406203413996905}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:54,257] Trial 58 finished with value: 0.7165554880196134 and parameters: {'l1_ratio': 0.11484965098723925}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 13:53:54,378] Trial 59 finished with value: 0.6818827456832424 and parameters: {'l1_ratio': 0.052591155581544424}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:54,833] Trial 60 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.538619577607128}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:55,211] Trial 61 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.7032880546105915}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:55,565] Trial 62 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.5847127251338408}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:56,046] Trial 63 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.24447601455789592}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:56,434] Trial 64 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.6201168782546553}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:56,794] Trial 65 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.7837628488756702}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:57,243] Trial 66 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.18386577371914814}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:57,610] Trial 67 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.5263632668185755}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:58,076] Trial 68 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.28873834416394456}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:58,448] Trial 69 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.6341758093781796}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:58,697] Trial 70 finished with value: 0.7165554880196134 and parameters: {'l1_ratio': 0.1189292037971658}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:59,071] Trial 71 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.7454942005071483}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714

Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:59,415] Trial 72 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.8571396880601414}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:53:59,815] Trial 73 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.4205381824199277}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:00,197] Trial 74 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.7162439318067315}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:00,589] Trial 75 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.496401817555526}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:01,053] Trial 76 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.5769015270738125}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:01,443] Trial 77 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.15178520348131963}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:01,822] Trial 78 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.9506480490309224}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 13:54:01,930] Trial 79 finished with value: 0.6818827456832424 and parameters: {'l1_ratio': 0.0766888130996658}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:02,378] Trial 80 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.32436808611254997}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:02,827] Trial 81 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.45722535174750273}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:03,338] Trial 82 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.4010770810266266}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:03,869] Trial 83 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.19997587104433373}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:04,240] Trial 84 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.16021619194238065}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:04,722] Trial 85 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.23132694721869404}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:05,376] Trial 86 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.3377706138410058}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:06,173] Trial 87 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.27581481727595525}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 13:54:06,325] Trial 88 finished with value: 0.6818827456832424 and parameters: {'l1_ratio': 0.02485670599524037}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:06,934] Trial 89 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.6482385902695216}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:07,351] Trial 90 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.7810079344708123}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:07,803] Trial 91 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.9740258234842947}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:08,264] Trial 92 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.3614784347876684}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:08,689] Trial 93 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.8669748575444413}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:09,130] Trial 94 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.8380792386865554}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:09,548] Trial 95 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.9190946752122768}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666

Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:10,336] Trial 96 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.21118012879425513}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:10,875] Trial 97 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.5651333347885639}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:11,257] Trial 98 finished with value: 0.7165554880196134 and parameters: {'l1_ratio': 0.11291352716923464}. Best is trial 22 with value: 0.7373347087988342.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714

[I 2024-04-17 13:54:11,863] A new study created in memory with name: no-name-7bef2b46-5ced-4f22-a23c-427306032294

Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:54:11,847] Trial 99 finished with value: 0.723941851655977 and parameters: {'l1_ratio': 0.44991898320121043}. Best is trial 22 with value: 0.7373347087988342.


* Best trial for C-index:
 FrozenTrial(number=22, state=TrialState.COMPLETE, values=[0.7373347087988342], datetime_start=datetime.datetime(2024, 4, 17, 13, 53, 40, 380663), datetime_complete=datetime.datetime(2024, 4, 17, 13, 53, 40, 770891), params={'l1_ratio': 0.13361135845786085}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=22, value=None)


* Best Score for C-index:
 0.7373347087988342

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1868661895573752
Fold 2 IBS: 0.15996581586464073
Fold 3 IBS: 0.14278778872716694
Fold 4 IBS: 0.20633899833847044
Fold 5 IBS: 0.16915346219645436
[I 2024-04-17 13:54:12,493] Trial 0 finished with value: 0.17302245093682153 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.17302245093682153.
Fold 1 IBS: 0.18676120750172592
Fold 2 IBS: 0.1599465668277593
Fold 3 IBS: 0.14259238633160734
Fold 4 IBS: 0.2064408820565228
Fold 5 IBS: 0.16905998197764482
[I 2024-04-17 13:54:13,308] Trial 1 finished with value: 0.172960204939052 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.172960204939052.
Fold 1 IBS: 0.1867403860040557
Fold 2 IBS: 0.15994744082172474
Fold 3 IBS: 0.1425754033421998
Fold 4 IBS: 0.20637932090081745
Fold 5 IBS: 0.16905210993741496
[I 2024-04-17 13:54:14,202] Trial 2 finished with value: 0.17293893220124254 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.17293893220124254.
Fold 1 IBS: 0.18680963647015578
Fold 2 IBS: 0.15995030268376617
Fold 3 IBS: 0.14273222903119562
Fold 4 IBS: 0.2062936986667965
Fold 5 IBS: 0.16911511599860876
[I 2024-04-17 13:54:14,787] Trial 3 finished with value: 0.17298019657010455 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.17293893220124254.
Fold 1 IBS: 0.18679676359916936
Fold 2 IBS: 0.15997515319708033
Fold 3 IBS: 0.1428473611971911
Fold 4 IBS: 0.20627171770380617
Fold 5 IBS: 0.16915721822319033
[I 2024-04-17 13:54:15,281] Trial 4 finished with value: 0.17300964278408745 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.17293893220124254.
Fold 1 IBS: 0.18676005389839692
Fold 2 IBS: 0.15995824157288097
Fold 3 IBS: 0.14269552617098905
Fold 4 IBS: 0.2064021774226325
Fold 5 IBS: 0.16908836755106818
[I 2024-04-17 13:54:15,877] Trial 5 finished with value: 0.1729808733231935 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.17293893220124254.
Fold 1 IBS: 0.18686754682437312
Fold 2 IBS: 0.15999928138619124
Fold 3 IBS: 0.14322124984235676
Fold 4 IBS: 0.2063489201075349
Fold 5 IBS: 0.16927671718657228
[I 2024-04-17 13:54:16,305] Trial 6 finished with value: 0.17314274306940564 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.17293893220124254.
Fold 1 IBS: 0.1867768229257146
Fold 2 IBS: 0.15997588418399866
Fold 3 IBS: 0.14282035178052344
Fold 4 IBS: 0.20655730908274933
Fold 5 IBS: 0.16914726657517878
[I 2024-04-17 13:54:16,815] Trial 7 finished with value: 0.17305552690963294 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.17293893220124254.
Fold 1 IBS: 0.18679956013252214
Fold 2 IBS: 0.15995813739997725
Fold 3 IBS: 0.14272451366918626
Fold 4 IBS: 0.20646955244144158
Fold 5 IBS: 0.16909810635700875
[I 2024-04-17 13:54:17,274] Trial 8 finished with value: 0.1730099740000272 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.17293893220124254.
Fold 1 IBS: 0.1867606773938843
Fold 2 IBS: 0.15996210772432068
Fold 3 IBS: 0.14258994478518658
Fold 4 IBS: 0.2063175043876006
Fold 5 IBS: 0.1690815049089574
[I 2024-04-17 13:54:17,960] Trial 9 finished with value: 0.1729423478399899 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.17293893220124254.
Fold 1 IBS: 0.21346651498752892
Fold 2 IBS: 0.21990748108155225
Fold 3 IBS: 0.20362393157229508
Fold 4 IBS: 0.22347692289778548
Fold 5 IBS: 0.21686310308510806
[I 2024-04-17 13:54:18,207] Trial 10 finished with value: 0.21546759072485394 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.17293893220124254.
Fold 1 IBS: 0.18669546902301165
Fold 2 IBS: 0.1599660727206874
Fold 3 IBS: 0.14253186389227998
Fold 4 IBS: 0.22178582224871302
Fold 5 IBS: 0.169031867497828
[I 2024-04-17 13:54:18,808] Trial 11 finished with value: 0.17600221907650399 and parameters: {'l1_ratio': 0.18301335955800116}. Best is trial 2 with value: 0.17293893220124254.
Fold 1 IBS: 0.18676168064672133
Fold 2 IBS: 0.15994667805842722
Fold 3 IBS: 0.14259278906567027
Fold 4 IBS: 0.2064392362360934
Fold 5 IBS: 0.16905989854334588
[I 2024-04-17 13:54:19,448] Trial 12 finished with value: 0.1729600565100516 and parameters: {'l1_ratio': 0.28611999835587154}. Best is trial 2 with value: 0.17293893220124254.
Fold 1 IBS: 0.21389296471406388
Fold 2 IBS: 0.22130510757001606
Fold 3 IBS: 0.2043867498186638
Fold 4 IBS: 0.22453231966644496
Fold 5 IBS: 0.21791758402037706
[I 2024-04-17 13:54:19,643] Trial 13 finished with value: 0.21640694515791314 and parameters: {'l1_ratio': 0.014325649412238406}. Best is trial 2 with value: 0.17293893220124254.
Fold 1 IBS: 0.18679886599628595
Fold 2 IBS: 0.1599505365286294
Fold 3 IBS: 0.14262289745821705
Fold 4 IBS: 0.2064189503757376
Fold 5 IBS: 0.16906306214931685
[I 2024-04-17 13:54:20,187] Trial 14 finished with value: 0.17297086250163737 and parameters: {'l1_ratio': 0.3277105303044846}. Best is trial 2 with value: 0.17293893220124254.
Fold 1 IBS: 0.1867076801341563
Fold 2 IBS: 0.15996894238076312
Fold 3 IBS: 0.1425422498459224
Fold 4 IBS: 0.2218160928871927
Fold 5 IBS: 0.1690480369510625
[I 2024-04-17 13:54:20,732] Trial 15 finished with value: 0.17601660043981943 and parameters: {'l1_ratio': 0.18135478190888005}. Best is trial 2 with value: 0.17293893220124254.
Fold 1 IBS: 0.18680280187639753
Fold 2 IBS: 0.15994694260637132
Fold 3 IBS: 0.14263026863740672
Fold 4 IBS: 0.20651341201162382
Fold 5 IBS: 0.16907298949741628
[I 2024-04-17 13:54:21,248] Trial 16 finished with value: 0.17299328292584315 and parameters: {'l1_ratio': 0.3806540284396491}. Best is trial 2 with value: 0.17293893220124254.
Fold 1 IBS: 0.18681831598811202
Fold 2 IBS: 0.1599484977856513
Fold 3 IBS: 0.14274643574837875
Fold 4 IBS: 0.20637162586328658
Fold 5 IBS: 0.16912300251221968
[I 2024-04-17 13:54:21,750] Trial 17 finished with value: 0.17300157557952967 and parameters: {'l1_ratio': 0.5854846197588475}. Best is trial 2 with value: 0.17293893220124254.
Fold 1 IBS: 0.18674014871231262
Fold 2 IBS: 0.15994872259075169
Fold 3 IBS: 0.14256963058566904
Fold 4 IBS: 0.20633756450731985
Fold 5 IBS: 0.16904733722514012
[I 2024-04-17 13:54:22,384] Trial 18 finished with value: 0.17292868072423867 and parameters: {'l1_ratio': 0.19281755699206077}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18676227388127814
Fold 2 IBS: 0.15995522899217765
Fold 3 IBS: 0.142588196032883
Fold 4 IBS: 0.22194462246585384
Fold 5 IBS: 0.1690383417036643
[I 2024-04-17 13:54:22,858] Trial 19 finished with value: 0.17605773261517138 and parameters: {'l1_ratio': 0.17426806258681068}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.21332927742907742
Fold 2 IBS: 0.21945561149844744
Fold 3 IBS: 0.2033778641427009
Fold 4 IBS: 0.22313519543854282
Fold 5 IBS: 0.1690307548779105
[I 2024-04-17 13:54:23,120] Trial 20 finished with value: 0.2056657406773358 and parameters: {'l1_ratio': 0.10500472511016506}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18673950200757877
Fold 2 IBS: 0.15994548904771902
Fold 3 IBS: 0.14257432747124374
Fold 4 IBS: 0.2064213254785528
Fold 5 IBS: 0.16905576218767066
[I 2024-04-17 13:54:23,667] Trial 21 finished with value: 0.17294728123855302 and parameters: {'l1_ratio': 0.24670414658951376}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18679286422244654
Fold 2 IBS: 0.15994626397447234
Fold 3 IBS: 0.14261780423903359
Fold 4 IBS: 0.20650009968976674
Fold 5 IBS: 0.16906969179558917
[I 2024-04-17 13:54:24,227] Trial 22 finished with value: 0.17298534478426167 and parameters: {'l1_ratio': 0.35582819415097905}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18676632694958373
Fold 2 IBS: 0.15995412483796081
Fold 3 IBS: 0.14269470130234996
Fold 4 IBS: 0.20649180193347896
Fold 5 IBS: 0.16908140830755142
[I 2024-04-17 13:54:24,740] Trial 23 finished with value: 0.17299767266618496 and parameters: {'l1_ratio': 0.45587715553173785}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.21380214946259238
Fold 2 IBS: 0.22100825737110247
Fold 3 IBS: 0.2042245080158085
Fold 4 IBS: 0.22430834958295479
Fold 5 IBS: 0.2176929520562481
[I 2024-04-17 13:54:24,896] Trial 24 finished with value: 0.21620724329774124 and parameters: {'l1_ratio': 0.02961969462146219}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18675883141711333

Fold 2 IBS: 0.1599533681552424
Fold 3 IBS: 0.14259090976811764
Fold 4 IBS: 0.20659528870793864
Fold 5 IBS: 0.16904567727688483
[I 2024-04-17 13:54:25,433] Trial 25 finished with value: 0.17298881506505936 and parameters: {'l1_ratio': 0.20598575943102115}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.1867621854676154
Fold 2 IBS: 0.21905770902812544
Fold 3 IBS: 0.1424912290744978
Fold 4 IBS: 0.2228340751658362
Fold 5 IBS: 0.16902994874028374
[I 2024-04-17 13:54:25,844] Trial 26 finished with value: 0.18803502949527173 and parameters: {'l1_ratio': 0.12316751626230191}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.1868026995869248
Fold 2 IBS: 0.15994854915214712
Fold 3 IBS: 0.14272592027891043
Fold 4 IBS: 0.20632188062704743
Fold 5 IBS: 0.16910368615510618
[I 2024-04-17 13:54:26,289] Trial 27 finished with value: 0.17298054716002717 and parameters: {'l1_ratio': 0.5534318442311428}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18691464080387576
Fold 2 IBS: 0.1599861726253772
Fold 3 IBS: 0.1432751220377267
Fold 4 IBS: 0.2064057863583784
Fold 5 IBS: 0.1692666953168727
[I 2024-04-17 13:54:26,779] Trial 28 finished with value: 0.17316968342844613 and parameters: {'l1_ratio': 0.964957522585106}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18672581737496946
Fold 2 IBS: 0.15995319631740107
Fold 3 IBS: 0.14266450108689702
Fold 4 IBS: 0.20644880611675095
Fold 5 IBS: 0.1690724986461687
[I 2024-04-17 13:54:27,400] Trial 29 finished with value: 0.17297296390843744 and parameters: {'l1_ratio': 0.40090232939660136}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18680020995019758
Fold 2 IBS: 0.15995784464855545
Fold 3 IBS: 0.14252543437474566
Fold 4 IBS: 0.2066259399825968
Fold 5 IBS: 0.16904892647511827
[I 2024-04-17 13:54:27,935] Trial 30 finished with value: 0.17299167108624275 and parameters: {'l1_ratio': 0.257028590425107}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18675810700898846
Fold 2 IBS: 0.15994986611475617
Fold 3 IBS: 0.14258995643996386
Fold 4 IBS: 0.20635670876427667
Fold 5 IBS: 0.1690524789888656
[I 2024-04-17 13:54:28,485] Trial 31 finished with value: 0.17294142346337016 and parameters: {'l1_ratio': 0.24354183082267372}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18672307419042228
Fold 2 IBS: 0.1599616016075338
Fold 3 IBS: 0.14255955032287204
Fold 4 IBS: 0.2066238663636
Fold 5 IBS: 0.16905483450457537
[I 2024-04-17 13:54:29,037] Trial 32 finished with value: 0.1729845853978007 and parameters: {'l1_ratio': 0.3181420486246476}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18670373767153858
Fold 2 IBS: 0.159965163234698
Fold 3 IBS: 0.1425437949134886
Fold 4 IBS: 0.20650951707987625
Fold 5 IBS: 0.16905875089665723
[I 2024-04-17 13:54:29,577] Trial 33 finished with value: 0.17295619275925173 and parameters: {'l1_ratio': 0.23307206606812525}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18674983779005522
Fold 2 IBS: 0.21903253303513168
Fold 3 IBS: 0.14257717110584478
Fold 4 IBS: 0.2228150162737803
Fold 5 IBS: 0.16903212717370278
[I 2024-04-17 13:54:30,053] Trial 34 finished with value: 0.18804133707570295 and parameters: {'l1_ratio': 0.12430185157472462}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18679735255924765
Fold 2 IBS: 0.15995273764966647
Fold 3 IBS: 0.14262212994561033
Fold 4 IBS: 0.206367184437722
Fold 5 IBS: 0.16905825241651545
[I 2024-04-17 13:54:30,649] Trial 35 finished with value: 0.17295953140175238 and parameters: {'l1_ratio': 0.30291141626976853}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.21360358296318518
Fold 2 IBS: 0.22035773798524907
Fold 3 IBS: 0.20386939280646724
Fold 4 IBS: 0.22381718400143805
Fold 5 IBS: 0.21720194935523124
[I 2024-04-17 13:54:30,913] Trial 36 finished with value: 0.21576996942231416 and parameters: {'l1_ratio': 0.0621169013771031}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18687202609385434
Fold 2 IBS: 0.1599780893652368
Fold 3 IBS: 0.14306364566364524
Fold 4 IBS: 0.20639557218868843
Fold 5 IBS: 0.16922215470570198
[I 2024-04-17 13:54:31,435] Trial 37 finished with value: 0.17310629760342539 and parameters: {'l1_ratio': 0.8808567522730943}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18686087014227165
Fold 2 IBS: 0.15997299901698991
Fold 3 IBS: 0.142783387452689
Fold 4 IBS: 0.20653562044688795
Fold 5 IBS: 0.16914035411624267
[I 2024-04-17 13:54:31,886] Trial 38 finished with value: 0.17305864623501624 and parameters: {'l1_ratio': 0.6547958328594672}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.1867830818680625
Fold 2 IBS: 0.15995840881631296
Fold 3 IBS: 0.1427100303434209
Fold 4 IBS: 0.20643132174835274
Fold 5 IBS: 0.1690928772673314
[I 2024-04-17 13:54:32,357] Trial 39 finished with value: 0.1729951440086961 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18678673689574316
Fold 2 IBS: 0.15994995178068142
Fold 3 IBS: 0.1427121826284293
Fold 4 IBS: 0.2066266625729167
Fold 5 IBS: 0.16909603870640944
[I 2024-04-17 13:54:32,912] Trial 40 finished with value: 0.173034314516836 and parameters: {'l1_ratio': 0.5204911496675979}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18672791922051463
Fold 2 IBS: 0.15994280385542795
Fold 3 IBS: 0.14256445806151927
Fold 4 IBS: 0.20646164244305487
Fold 5 IBS: 0.1690578127324842
[I 2024-04-17 13:54:33,584] Trial 41 finished with value: 0.1729509272626002 and parameters: {'l1_ratio': 0.2487114029200893}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.1867776722379695
Fold 2 IBS: 0.159960596833252
Fold 3 IBS: 0.14250421511510256
Fold 4 IBS: 0.22223210670704854
Fold 5 IBS: 0.16903322384663125
[I 2024-04-17 13:54:34,219] Trial 42 finished with value: 0.17610156294800078 and parameters: {'l1_ratio': 0.158152112406621}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18670283086979825
Fold 2 IBS: 0.15996302597150083
Fold 3 IBS: 0.14254240695410758
Fold 4 IBS: 0.20649990369893384
Fold 5 IBS: 0.16904508219328518
[I 2024-04-17 13:54:34,782] Trial 43 finished with value: 0.17295064993752512 and parameters: {'l1_ratio': 0.25330979530211034}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.1868085229322418
Fold 2 IBS: 0.1599499385520203
Fold 3 IBS: 0.14263052817055896
Fold 4 IBS: 0.20644812699385984
Fold 5 IBS: 0.16906694314360626
[I 2024-04-17 13:54:35,365] Trial 44 finished with value: 0.17298081195845744 and parameters: {'l1_ratio': 0.35236523507192163}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.1867868254618817
Fold 2 IBS: 0.15995258777188834
Fold 3 IBS: 0.14261363847845182
Fold 4 IBS: 0.2063519331991475
Fold 5 IBS: 0.16905547651641803
[I 2024-04-17 13:54:36,008] Trial 45 finished with value: 0.17295209228555747 and parameters: {'l1_ratio': 0.2813735448422236}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.1867228975675035
Fold 2 IBS: 0.1599449094443941
Fold 3 IBS: 0.14256077223455058
Fold 4 IBS: 0.20640468549497032
Fold 5 IBS: 0.16905201888294835
[I 2024-04-17 13:54:36,585] Trial 46 finished with value: 0.17293705672487336 and parameters: {'l1_ratio': 0.21133087403092338}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.1867601306431928
Fold 2 IBS: 0.15995756929794386
Fold 3 IBS: 0.14248915322270914
Fold 4 IBS: 0.2224291230165344
Fold 5 IBS: 0.16903412387246397
[I 2024-04-17 13:54:37,102] Trial 47 finished with value: 0.17613402001056883 and parameters: {'l1_ratio': 0.14689060454959396}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18672888972886512
Fold 2 IBS: 0.15994632041165827
Fold 3 IBS: 0.142565885784354
Fold 4 IBS: 0.20638386355310326
Fold 5 IBS: 0.16905095800845443
[I 2024-04-17 13:54:37,695] Trial 48 finished with value: 0.17293518349728704 and parameters: {'l1_ratio': 0.2104218212893374}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18677259986944292
Fold 2 IBS: 0.15995501997664238
Fold 3 IBS: 0.1426023534932353
Fold 4 IBS: 0.20658378677931316
Fold 5 IBS: 0.16904643935207933
[I 2024-04-17 13:54:38,354] Trial 49 finished with value: 0.17299203989414264 and parameters: {'l1_ratio': 0.22187899691193877}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.21352326647714406
Fold 2 IBS: 0.22009402956493965
Fold 3 IBS: 0.2037255970693216
Fold 4 IBS: 0.22361792827602495
Fold 5 IBS: 0.2170033925764105
[I 2024-04-17 13:54:38,516] Trial 50 finished with value: 0.21559284279276816 and parameters: {'l1_ratio': 0.07490766272435717}. Best is trial 18 with value: 0.17292868072423867.

Fold 1 IBS: 0.1866852379146352
Fold 2 IBS: 0.15996364584054212
Fold 3 IBS: 0.1425282230084562
Fold 4 IBS: 0.20650615759914515
Fold 5 IBS: 0.16903803143148782
[I 2024-04-17 13:54:39,023] Trial 51 finished with value: 0.1729442591588533 and parameters: {'l1_ratio': 0.19981378826499338}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18671846261344824
Fold 2 IBS: 0.15995769465172532
Fold 3 IBS: 0.142658428921506
Fold 4 IBS: 0.20633429419471444
Fold 5 IBS: 0.16906120645256603
[I 2024-04-17 13:54:39,502] Trial 52 finished with value: 0.172946017366792 and parameters: {'l1_ratio': 0.3452970797066381}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18671705987357146
Fold 2 IBS: 0.15995096644959964
Fold 3 IBS: 0.14265643907324752
Fold 4 IBS: 0.20647937397834248
Fold 5 IBS: 0.16907415897564054
[I 2024-04-17 13:54:40,081] Trial 53 finished with value: 0.1729755996700803 and parameters: {'l1_ratio': 0.4031499425622821}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18679074698599088
Fold 2 IBS: 0.15995350920131526
Fold 3 IBS: 0.1426169789355311
Fold 4 IBS: 0.20633834628055567
Fold 5 IBS: 0.1690547889938907
[I 2024-04-17 13:54:40,657] Trial 54 finished with value: 0.17295087407945672 and parameters: {'l1_ratio': 0.28064631846257876}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.1867463601932655
Fold 2 IBS: 0.1599543338673819
Fold 3 IBS: 0.14257381141653938
Fold 4 IBS: 0.22240320765809127
Fold 5 IBS: 0.16903655709685952
[I 2024-04-17 13:54:41,219] Trial 55 finished with value: 0.17614285404642752 and parameters: {'l1_ratio': 0.14838221554204722}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18672011602629054
Fold 2 IBS: 0.15994425441901783
Fold 3 IBS: 0.14255839888175348
Fold 4 IBS: 0.20641435718195195
Fold 5 IBS: 0.16905251179622788
[I 2024-04-17 13:54:41,793] Trial 56 finished with value: 0.17293792766104832 and parameters: {'l1_ratio': 0.21175532665904176}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.2137541511647891
Fold 2 IBS: 0.22085119422786118
Fold 3 IBS: 0.20413871619502766
Fold 4 IBS: 0.22418980829254215
Fold 5 IBS: 0.21757424723197413
[I 2024-04-17 13:54:41,950] Trial 57 finished with value: 0.21610162342243883 and parameters: {'l1_ratio': 0.03759223081536048}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.21334168827426356
Fold 2 IBS: 0.2194965205110477
Fold 3 IBS: 0.20340013005164836
Fold 4 IBS: 0.22316614319597683
Fold 5 IBS: 0.1690264925991334
[I 2024-04-17 13:54:42,200] Trial 58 finished with value: 0.205686194926414 and parameters: {'l1_ratio': 0.1031119583790047}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18674848994832194
Fold 2 IBS: 0.1599506793205106
Fold 3 IBS: 0.14257619054801285
Fold 4 IBS: 0.20662217879513364
Fold 5 IBS: 0.16904587047558323
[I 2024-04-17 13:54:42,813] Trial 59 finished with value: 0.17298868181751245 and parameters: {'l1_ratio': 0.19166442226507888}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.1867509339803746
Fold 2 IBS: 0.1599525689704384
Fold 3 IBS: 0.1425785340799205
Fold 4 IBS: 0.2219188019035257
Fold 5 IBS: 0.16904034629956374
[I 2024-04-17 13:54:43,342] Trial 60 finished with value: 0.1760482370467646 and parameters: {'l1_ratio': 0.17569752567226016}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18676406362337208
Fold 2 IBS: 0.1599449170088975
Fold 3 IBS: 0.1425943763829456
Fold 4 IBS: 0.2064803871082879
Fold 5 IBS: 0.1690641052857188
[I 2024-04-17 13:54:43,909] Trial 61 finished with value: 0.17296956988184436 and parameters: {'l1_ratio': 0.30956803263011495}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.1867153447108369
Fold 2 IBS: 0.1599429838573411
Fold 3 IBS: 0.14255365006191104
Fold 4 IBS: 0.20643372365433002
Fold 5 IBS: 0.1690534990696979
[I 2024-04-17 13:54:44,492] Trial 62 finished with value: 0.17293984027082338 and parameters: {'l1_ratio': 0.2126094804151801}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.21397561614046637
Fold 2 IBS: 0.22157496164549337
Fold 3 IBS: 0.20453433037396324
Fold 4 IBS: 0.22473581306383664
Fold 5 IBS: 0.21812207390141106
[I 2024-04-17 13:54:44,675] Trial 63 finished with value: 0.21658855902503413 and parameters: {'l1_ratio': 0.0001565943113469026}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18673122158537334
Fold 2 IBS: 0.15994686944426512
Fold 3 IBS: 0.14256787599841309
Fold 4 IBS: 0.20637576560495385
Fold 5 IBS: 0.16905054553303903
[I 2024-04-17 13:54:45,305] Trial 64 finished with value: 0.1729344556332089 and parameters: {'l1_ratio': 0.21007001516035143}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18669780490919063
Fold 2 IBS: 0.15996530782282395
Fold 3 IBS: 0.1425386940211959
Fold 4 IBS: 0.2064946447314357
Fold 5 IBS: 0.16903879895874035
[I 2024-04-17 13:54:45,908] Trial 65 finished with value: 0.1729470500886773 and parameters: {'l1_ratio': 0.21534277271664481}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18672538076673204
Fold 2 IBS: 0.21898125790269088
Fold 3 IBS: 0.14255677991636978
Fold 4 IBS: 0.2227761972577091
Fold 5 IBS: 0.1690364590857202
[I 2024-04-17 13:54:46,345] Trial 66 finished with value: 0.1880152149858444 and parameters: {'l1_ratio': 0.12660673179193976}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18675913988025794
Fold 2 IBS: 0.1599460807424429
Fold 3 IBS: 0.1425906264759012
Fold 4 IBS: 0.20644807554304356
Fold 5 IBS: 0.1690603466794342
[I 2024-04-17 13:54:46,904] Trial 67 finished with value: 0.17296085386421595 and parameters: {'l1_ratio': 0.2866077961206585}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.2133630930324542
Fold 2 IBS: 0.2195670542503704
Fold 3 IBS: 0.20343852533759244
Fold 4 IBS: 0.2232194973453443
Fold 5 IBS: 0.16903816091491383
[I 2024-04-17 13:54:47,161] Trial 68 finished with value: 0.205725266176135 and parameters: {'l1_ratio': 0.09983720565359593}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.21361109470041614
Fold 2 IBS: 0.22038238408335992
Fold 3 IBS: 0.20388283666360013
Fold 4 IBS: 0.22383580205760992
Fold 5 IBS: 0.21722052079082244
[I 2024-04-17 13:54:47,341] Trial 69 finished with value: 0.21578652765916168 and parameters: {'l1_ratio': 0.06091042988884951}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.1866870043927766
Fold 2 IBS: 0.15996689971130262
Fold 3 IBS: 0.14252527405516024
Fold 4 IBS: 0.22228475953408947
Fold 5 IBS: 0.16902851559582083
[I 2024-04-17 13:54:47,860] Trial 70 finished with value: 0.17609849065782995 and parameters: {'l1_ratio': 0.15515999803586045}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18676921065876798
Fold 2 IBS: 0.15995422281013105
Fold 3 IBS: 0.1425994598173851
Fold 4 IBS: 0.20659483626895356
Fold 5 IBS: 0.169047034113534
[I 2024-04-17 13:54:48,420] Trial 71 finished with value: 0.1729929527337543 and parameters: {'l1_ratio': 0.22240048942792168}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18673480344768517
Fold 2 IBS: 0.15994251219885613
Fold 3 IBS: 0.14257029891334594
Fold 4 IBS: 0.20648313537948174
Fold 5 IBS: 0.16906043361128523
[I 2024-04-17 13:54:48,966] Trial 72 finished with value: 0.17295823671013083 and parameters: {'l1_ratio': 0.26866999820988513}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18679725376227976
Fold 2 IBS: 0.15996211268160504
Fold 3 IBS: 0.1425186225355426
Fold 4 IBS: 0.20651691232055727
Fold 5 IBS: 0.1690348255928204
[I 2024-04-17 13:54:49,485] Trial 73 finished with value: 0.17296594537856103 and parameters: {'l1_ratio': 0.18517017376813233}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18673156846557407
Fold 2 IBS: 0.15994536539791487
Fold 3 IBS: 0.14256788258071057
Fold 4 IBS: 0.20640995684465066
Fold 5 IBS: 0.1690536688822931
[I 2024-04-17 13:54:50,182] Trial 74 finished with value: 0.17294168843422866 and parameters: {'l1_ratio': 0.22834813984576677}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18677757042347043
Fold 2 IBS: 0.1599455358197121
Fold 3 IBS: 0.14260536734616092
Fold 4 IBS: 0.20649053496610562

Fold 5 IBS: 0.1690668050271532
[I 2024-04-17 13:54:50,739] Trial 75 finished with value: 0.17297716271652047 and parameters: {'l1_ratio': 0.3322062680413627}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.1867408748601879
Fold 2 IBS: 0.15994581208577285
Fold 3 IBS: 0.14257549749383414
Fold 4 IBS: 0.20641655143511087
Fold 5 IBS: 0.16905551947916622
[I 2024-04-17 13:54:51,336] Trial 76 finished with value: 0.17294685107081437 and parameters: {'l1_ratio': 0.24646821685745576}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18681510818488462
Fold 2 IBS: 0.15994983711626284
Fold 3 IBS: 0.14264073138627673
Fold 4 IBS: 0.2064729778773398
Fold 5 IBS: 0.16907082628621445
[I 2024-04-17 13:54:51,845] Trial 77 finished with value: 0.17298989617019567 and parameters: {'l1_ratio': 0.37780650608149935}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18678429972013402
Fold 2 IBS: 0.1599593596060318
Fold 3 IBS: 0.14251390432650685
Fold 4 IBS: 0.20651309270451174
Fold 5 IBS: 0.16904121212417045
[I 2024-04-17 13:54:52,452] Trial 78 finished with value: 0.17296237369627096 and parameters: {'l1_ratio': 0.2023464147015755}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18691386322804465
Fold 2 IBS: 0.1599755632806487
Fold 3 IBS: 0.14296038823021529
Fold 4 IBS: 0.20655856052294275
Fold 5 IBS: 0.16919145726556284
[I 2024-04-17 13:54:52,942] Trial 79 finished with value: 0.17311996650548284 and parameters: {'l1_ratio': 0.8187818034877232}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18674808054988584
Fold 2 IBS: 0.1599553648847266
Fold 3 IBS: 0.14257547442731106
Fold 4 IBS: 0.22261931757044287
Fold 5 IBS: 0.1690342561938152
[I 2024-04-17 13:54:53,436] Trial 80 finished with value: 0.1761864987252363 and parameters: {'l1_ratio': 0.13584666187495015}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18670763142249389
Fold 2 IBS: 0.15996588141585255
Fold 3 IBS: 0.14254711280014465
Fold 4 IBS: 0.20649592304880146
Fold 5 IBS: 0.1690580580417602
[I 2024-04-17 13:54:53,958] Trial 81 finished with value: 0.17295492134581056 and parameters: {'l1_ratio': 0.23241912817578397}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18670605936069584
Fold 2 IBS: 0.15994381684430017
Fold 3 IBS: 0.1425410867985419
Fold 4 IBS: 0.22208081589628303
Fold 5 IBS: 0.1690459154093862
[I 2024-04-17 13:54:54,402] Trial 82 finished with value: 0.17606353886184142 and parameters: {'l1_ratio': 0.1666794184876383}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18679876899549688
Fold 2 IBS: 0.15995307029893563
Fold 3 IBS: 0.1426233353838265
Fold 4 IBS: 0.20636227384703648
Fold 5 IBS: 0.16905800429199458
[I 2024-04-17 13:54:54,975] Trial 83 finished with value: 0.172959090563458 and parameters: {'l1_ratio': 0.30263400230777016}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.1867420081256436
Fold 2 IBS: 0.15994416123952337
Fold 3 IBS: 0.14257643368684197
Fold 4 IBS: 0.20645804108117308
Fold 5 IBS: 0.16905915823733839
[I 2024-04-17 13:54:55,539] Trial 84 finished with value: 0.17295596047410408 and parameters: {'l1_ratio': 0.2673404151521415}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18675790729697006
Fold 2 IBS: 0.15995315069795393
Fold 3 IBS: 0.1425901204192233
Fold 4 IBS: 0.20659830294136008
Fold 5 IBS: 0.16904583975595425
[I 2024-04-17 13:54:56,072] Trial 85 finished with value: 0.17298906422229232 and parameters: {'l1_ratio': 0.20612008493094605}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18670860090435054
Fold 2 IBS: 0.1599661285182496
Fold 3 IBS: 0.1425479389675819
Fold 4 IBS: 0.2064925395560149
Fold 5 IBS: 0.1690578856199561
[I 2024-04-17 13:54:56,590] Trial 86 finished with value: 0.17295461871323062 and parameters: {'l1_ratio': 0.23225708281667076}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18680511925897542
Fold 2 IBS: 0.15996527448049788
Fold 3 IBS: 0.1425251207940094
Fold 4 IBS: 0.22203832476141622
Fold 5 IBS: 0.16903081158876682
[I 2024-04-17 13:54:57,093] Trial 87 finished with value: 0.17607293017673314 and parameters: {'l1_ratio': 0.1690558546146364}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.21338435365667233
Fold 2 IBS: 0.21963708654648761
Fold 3 IBS: 0.2034766542554685
Fold 4 IBS: 0.22327246620200447
Fold 5 IBS: 0.16903054617194357
[I 2024-04-17 13:54:57,337] Trial 88 finished with value: 0.20576022136651528 and parameters: {'l1_ratio': 0.09657147565001947}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.21321630318836232
Fold 2 IBS: 0.2190827976489657
Fold 3 IBS: 0.1425010586901241
Fold 4 IBS: 0.2228530671474543
Fold 5 IBS: 0.1690277430872935
[I 2024-04-17 13:54:57,672] Trial 89 finished with value: 0.19333619395243998 and parameters: {'l1_ratio': 0.12203537991798863}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18672912272347972
Fold 2 IBS: 0.15995735025404567
Fold 3 IBS: 0.1426679214385542
Fold 4 IBS: 0.20636169023690956
Fold 5 IBS: 0.16906523497889492
[I 2024-04-17 13:54:58,188] Trial 90 finished with value: 0.1729562639263768 and parameters: {'l1_ratio': 0.37059012200883457}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.1867082302688339
Fold 2 IBS: 0.15996440234436507
Fold 3 IBS: 0.14254700259166336
Fold 4 IBS: 0.206532980209896
Fold 5 IBS: 0.16906145361575067
[I 2024-04-17 13:54:58,692] Trial 91 finished with value: 0.1729628138061018 and parameters: {'l1_ratio': 0.252338224947083}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18669398451349434
Fold 2 IBS: 0.15996566461261122
Fold 3 IBS: 0.14253049868041948
Fold 4 IBS: 0.221781798655499
Fold 5 IBS: 0.1690321718906604
[I 2024-04-17 13:54:59,191] Trial 92 finished with value: 0.17600082367053688 and parameters: {'l1_ratio': 0.18323352084544692}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18670026569781004
Fold 2 IBS: 0.15995806163962945
Fold 3 IBS: 0.1425398666308366
Fold 4 IBS: 0.2066544632122072
Fold 5 IBS: 0.16905428936634426
[I 2024-04-17 13:54:59,757] Trial 93 finished with value: 0.17298138930936552 and parameters: {'l1_ratio': 0.29852575744843785}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18680772446926244
Fold 2 IBS: 0.15996620057934244
Fold 3 IBS: 0.1427366300576049
Fold 4 IBS: 0.2065737851893281
Fold 5 IBS: 0.16912577827865485
[I 2024-04-17 13:55:00,276] Trial 94 finished with value: 0.17304202371483854 and parameters: {'l1_ratio': 0.6295215241210127}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18672774029053996
Fold 2 IBS: 0.1599500202324944
Fold 3 IBS: 0.14266580918689437
Fold 4 IBS: 0.2065217072361749
Fold 5 IBS: 0.1690794416124486
[I 2024-04-17 13:55:00,762] Trial 95 finished with value: 0.17298894371171042 and parameters: {'l1_ratio': 0.43169420498915206}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18670202054044988
Fold 2 IBS: 0.1599661486075984
Fold 3 IBS: 0.14254228785879886
Fold 4 IBS: 0.20648013919191285
Fold 5 IBS: 0.1690558667126187
[I 2024-04-17 13:55:01,375] Trial 96 finished with value: 0.17294929258227573 and parameters: {'l1_ratio': 0.21467991649736204}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18674453738223726
Fold 2 IBS: 0.15997127556247773
Fold 3 IBS: 0.1426748603095701
Fold 4 IBS: 0.20630775611116833
Fold 5 IBS: 0.16909432453627676
[I 2024-04-17 13:55:01,839] Trial 97 finished with value: 0.17295855078034603 and parameters: {'l1_ratio': 0.4965881146918674}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18672966665920834
Fold 2 IBS: 0.1599680195947923
Fold 3 IBS: 0.1425659258287614
Fold 4 IBS: 0.2065010432764141
Fold 5 IBS: 0.1690613441089276
[I 2024-04-17 13:55:02,375] Trial 98 finished with value: 0.17296519989362075 and parameters: {'l1_ratio': 0.26962542881106183}. Best is trial 18 with value: 0.17292868072423867.
Fold 1 IBS: 0.18677230401806189
Fold 2 IBS: 0.15994429881184896
Fold 3 IBS: 0.14260089427579897
Fold 4 IBS: 0.20650888972705944
Fold 5 IBS: 0.16906773323004987
[I 2024-04-17 13:55:02,848] Trial 99 finished with value: 0.17297882401256381 and parameters: {'l1_ratio': 0.33333552241213293}. Best is trial 18 with value: 0.17292868072423867.


* Best trial for IBS:
 FrozenTrial(number=18, state=TrialState.COMPLETE, values=[0.17292868072423867], datetime_start=datetime.datetime(2024, 4, 17, 13, 54, 21, 753340), datetime_complete=datetime.datetime(2024, 4, 17, 13, 54, 22, 384422), params={'l1_ratio': 0.19281755699206077}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=18, value=None)


* Best Score for IBS:
 0.17292868072423867

In [46]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [47]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.737
train_ibs:  0.173

#### Test

In [48]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [49]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.13361135845786085)

test_cindex : 0.579

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.19281755699206077)

test_ibs:  0.244

In [50]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [51]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:55:03,224] A new study created in memory with name: no-name-a87dbcff-274c-4777-b76b-f82c305dc85d

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7194092827004219
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 13:55:07,700] Trial 0 finished with value: 0.6931507094077359 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6931507094077359.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:55:10,594] Trial 1 finished with value: 0.664770691376763 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.6931507094077359.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7370892018779343
[I 2024-04-17 13:55:12,850] Trial 2 finished with value: 0.6621069409870627 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.6931507094077359.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:55:13,585] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.6931507094077359.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:55:15,091] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.6931507094077359.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 13:55:19,104] Trial 5 finished with value: 0.6779264121814303 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.6931507094077359.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:55:23,644] Trial 6 finished with value: 0.700588684922096 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 6 with value: 0.700588684922096.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:55:25,940] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 6 with value: 0.700588684922096.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6455399061032864
[I 2024-04-17 13:55:31,961] Trial 8 finished with value: 0.5291079812206573 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 6 with value: 0.700588684922096.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 13:55:35,133] Trial 9 finished with value: 0.6738408207089056 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 6 with value: 0.700588684922096.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:55:35,546] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 19, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.40740851493126695, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 6 with value: 0.700588684922096.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:55:40,125] Trial 11 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.11379276107227315, 'max_features': None, 'min_weight_fraction_leaf': 0.14354804402122565, 'warm_start': False}. Best is trial 6 with value: 0.700588684922096.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:55:46,259] Trial 12 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.4725186573284777, 'max_features': None, 'min_weight_fraction_leaf': 0.42991693404730996, 'warm_start': False}. Best is trial 6 with value: 0.700588684922096.
Fold 1 C-index: 0.6515151515151515
Fold 2 C-index: 0.7165178571428571
Fold 3 C-index: 0.7132352941176471
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:55:49,514] Trial 13 finished with value: 0.7156653203875434 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 140, 'oob_score': True, 'max_samples': 0.765021860726683, 'max_features': None, 'min_weight_fraction_leaf': 0.20108807339664914, 'warm_start': False}. Best is trial 13 with value: 0.7156653203875434.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.8215962441314554
[I 2024-04-17 13:55:51,212] Trial 14 finished with value: 0.7670453047262116 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 133, 'oob_score': True, 'max_samples': 0.7873021337102564, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0992244164616675, 'warm_start': True}. Best is trial 14 with value: 0.7670453047262116.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7362869198312236
Fold 5 C-index: 0.7370892018779343
[I 2024-04-17 13:55:52,257] Trial 15 finished with value: 0.7167611041482995 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 96, 'oob_score': True, 'max_samples': 0.8147833133306369, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20648604556011108, 'warm_start': True}. Best is trial 14 with value: 0.7670453047262116.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7790178571428571
Fold 3 C-index: 0.7524509803921569
Fold 4 C-index: 0.7658227848101266

Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 13:55:52,477] Trial 16 finished with value: 0.71335747695973 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 5, 'oob_score': True, 'max_samples': 0.8484814588885312, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08082385841318356, 'warm_start': True}. Best is trial 14 with value: 0.7670453047262116.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7489451476793249
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 13:55:53,423] Trial 17 finished with value: 0.7416632023804188 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 106, 'oob_score': True, 'max_samples': 0.9817072304699028, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16544550098450153, 'warm_start': True}. Best is trial 14 with value: 0.7670453047262116.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7531645569620253
Fold 5 C-index: 0.715962441314554
[I 2024-04-17 13:55:54,465] Trial 18 finished with value: 0.7185357383362427 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 118, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13294582901895255, 'warm_start': True}. Best is trial 14 with value: 0.7670453047262116.
Fold 1 C-index: 0.551948051948052
Fold 2 C-index: 0.8058035714285714
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.7151898734177216
Fold 5 C-index: 0.7347417840375586
[I 2024-04-17 13:55:55,953] Trial 19 finished with value: 0.6958503816565768 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 172, 'oob_score': True, 'max_samples': 0.9945705745432233, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09964492104707659, 'warm_start': True}. Best is trial 14 with value: 0.7670453047262116.
Fold 1 C-index: 0.461038961038961
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.6887254901960784
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6784037558685446
[I 2024-04-17 13:55:56,818] Trial 20 finished with value: 0.6677716010349422 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 13, 'n_estimators': 73, 'oob_score': True, 'max_samples': 0.8673418291441284, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.37827446502466894, 'warm_start': True}. Best is trial 14 with value: 0.7670453047262116.
Fold 1 C-index: 0.577922077922078
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7573839662447257
Fold 5 C-index: 0.7065727699530516
[I 2024-04-17 13:55:57,857] Trial 21 finished with value: 0.7189149785102456 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 112, 'oob_score': True, 'max_samples': 0.9624638447657676, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1580984841046789, 'warm_start': True}. Best is trial 14 with value: 0.7670453047262116.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8415178571428571
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7658227848101266
Fold 5 C-index: 0.7347417840375586
[I 2024-04-17 13:55:58,225] Trial 22 finished with value: 0.740952772440278 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 18, 'oob_score': True, 'max_samples': 0.9336744347879812, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19282610776605333, 'warm_start': True}. Best is trial 14 with value: 0.7670453047262116.
Fold 1 C-index: 0.49134199134199136
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7083333333333334
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 13:55:58,612] Trial 23 finished with value: 0.6684018307196459 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 18, 'oob_score': True, 'max_samples': 0.6843026151576985, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2504370920378234, 'warm_start': True}. Best is trial 14 with value: 0.7670453047262116.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 13:55:59,267] Trial 24 finished with value: 0.7434113057936508 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 17, 'n_estimators': 50, 'oob_score': True, 'max_samples': 0.8174924759139053, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17673091249808245, 'warm_start': True}. Best is trial 14 with value: 0.7670453047262116.
Fold 1 C-index: 0.5541125541125541
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7616033755274262
Fold 5 C-index: 0.8028169014084507
[I 2024-04-17 13:56:00,678] Trial 25 finished with value: 0.7502997034645882 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 17, 'n_estimators': 152, 'oob_score': True, 'max_samples': 0.8163265721117412, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06849397634897472, 'warm_start': True}. Best is trial 14 with value: 0.7670453047262116.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8028169014084507
[I 2024-04-17 13:56:01,925] Trial 26 finished with value: 0.7487338038020764 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 147, 'oob_score': True, 'max_samples': 0.7987089088395859, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06306617081281016, 'warm_start': True}. Best is trial 14 with value: 0.7670453047262116.
Fold 1 C-index: 0.5497835497835498
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 13:56:03,093] Trial 27 finished with value: 0.7342982138073142 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.5634050049825258, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06193755475145393, 'warm_start': True}. Best is trial 14 with value: 0.7670453047262116.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.8873239436619719
[I 2024-04-17 13:56:04,944] Trial 28 finished with value: 0.7915105019543921 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.7727096519936921, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0024931985043791516, 'warm_start': True}. Best is trial 28 with value: 0.7915105019543921.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.892018779342723
[I 2024-04-17 13:56:06,776] Trial 29 finished with value: 0.799822596707527 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.7056652079362958, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.026345150872286907, 'warm_start': True}. Best is trial 29 with value: 0.799822596707527.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.9530516431924883
[I 2024-04-17 13:56:09,037] Trial 30 finished with value: 0.851299492105956 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.6631327005651165, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00847594664917167, 'warm_start': True}. Best is trial 30 with value: 0.851299492105956.

Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.9196428571428571
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.9530516431924883
[I 2024-04-17 13:56:11,226] Trial 31 finished with value: 0.8523610530939875 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.6917950833213685, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014219617355821348, 'warm_start': True}. Best is trial 31 with value: 0.8523610530939875.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.9577464788732394
[I 2024-04-17 13:56:13,283] Trial 32 finished with value: 0.8558046095227017 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.6989079603987141, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.002593434028385796, 'warm_start': True}. Best is trial 32 with value: 0.8558046095227017.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.9577464788732394
[I 2024-04-17 13:56:15,490] Trial 33 finished with value: 0.8585166034111662 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 240, 'oob_score': True, 'max_samples': 0.7016833563123557, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0036872257494900695, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.9241071428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.9530516431924883
[I 2024-04-17 13:56:18,459] Trial 34 finished with value: 0.8558074748157256 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 263, 'oob_score': True, 'max_samples': 0.6910288008391462, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.002603698082551933, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.9014084507042254
[I 2024-04-17 13:56:19,790] Trial 35 finished with value: 0.8177085193305185 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.5238363272523311, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.041799651789036885, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.9375
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.9530516431924883
[I 2024-04-17 13:56:22,639] Trial 36 finished with value: 0.8505523319070087 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 259, 'oob_score': True, 'max_samples': 0.724237890668036, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00052334394504433, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5454545454545454
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 13:56:23,670] Trial 37 finished with value: 0.733859213631481 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.6371011098146326, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11859692006794731, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.9436619718309859
[I 2024-04-17 13:56:25,411] Trial 38 finished with value: 0.8362275633198546 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 199, 'oob_score': True, 'max_samples': 0.7232503826207304, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03848776735248283, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8262910798122066
[I 2024-04-17 13:56:26,919] Trial 39 finished with value: 0.7597067836518876 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.5584624909113933, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08967073948160842, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.9107981220657277
[I 2024-04-17 13:56:30,009] Trial 40 finished with value: 0.8309446706525849 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 379, 'oob_score': True, 'max_samples': 0.607278485396856, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04155251574281492, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.9483568075117371
[I 2024-04-17 13:56:32,018] Trial 41 finished with value: 0.85214623925552 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.6690093343557978, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0003192455560591511, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.9483568075117371
[I 2024-04-17 13:56:33,997] Trial 42 finished with value: 0.8467391742430939 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 287, 'oob_score': True, 'max_samples': 0.6639084643312236, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.019294035262792286, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 13:56:35,656] Trial 43 finished with value: 0.8314396030620873 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 248, 'oob_score': True, 'max_samples': 0.7360516271563652, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04743667366589978, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 13:56:37,002] Trial 44 finished with value: 0.7943515969006121 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 199, 'oob_score': True, 'max_samples': 0.5217504280521564, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023790326622755653, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.9196428571428571
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9577464788732394
[I 2024-04-17 13:56:38,806] Trial 45 finished with value: 0.858177966805776 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.6173302704405927, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.004564788835653925, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.

Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 13:56:42,569] Trial 46 finished with value: 0.6762276330652522 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.6100893889898196, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07562714072579024, 'warm_start': False}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8685446009389671
[I 2024-04-17 13:56:43,796] Trial 47 finished with value: 0.7744419982291364 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 185, 'oob_score': True, 'max_samples': 0.40267068080663715, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05355885736190555, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 13:56:46,951] Trial 48 finished with value: 0.6784412963713825 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 216, 'oob_score': True, 'max_samples': 0.6305585750969265, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12051150535583259, 'warm_start': False}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:56:49,087] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 352, 'oob_score': True, 'max_samples': 0.47504880011624273, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2712244893485633, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5411255411255411
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:56:50,035] Trial 50 finished with value: 0.69361080912697 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 290, 'oob_score': False, 'max_samples': 0.5740352571014607, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024440880080963855, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.9330357142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.9530516431924883
[I 2024-04-17 13:56:51,811] Trial 51 finished with value: 0.8541957426660188 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 248, 'oob_score': True, 'max_samples': 0.6907208173599281, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0005202431833000948, 'warm_start': True}. Best is trial 33 with value: 0.8585166034111662.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.9375
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.9624413145539906
[I 2024-04-17 13:56:53,623] Trial 52 finished with value: 0.8597273622329205 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 263, 'oob_score': True, 'max_samples': 0.7584215651701504, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.022333215255147722, 'warm_start': True}. Best is trial 52 with value: 0.8597273622329205.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.9436619718309859
[I 2024-04-17 13:56:55,394] Trial 53 finished with value: 0.8405346486395981 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 256, 'oob_score': True, 'max_samples': 0.7517953767858645, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.037721052762769186, 'warm_start': True}. Best is trial 52 with value: 0.8597273622329205.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.92018779342723
[I 2024-04-17 13:56:57,751] Trial 54 finished with value: 0.8241941103740157 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 332, 'oob_score': True, 'max_samples': 0.8728583594558254, 'max_features': None, 'min_weight_fraction_leaf': 0.08522439198860146, 'warm_start': True}. Best is trial 52 with value: 0.8597273622329205.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.9330357142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.9624413145539906
[I 2024-04-17 13:56:59,607] Trial 55 finished with value: 0.8578052786699212 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.7650676429659583, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024547925384238677, 'warm_start': True}. Best is trial 52 with value: 0.8597273622329205.
Fold 1 C-index: 0.5411255411255411
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.5735294117647058
Fold 4 C-index: 0.6476793248945147
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 13:57:03,567] Trial 56 finished with value: 0.6316125631357584 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 276, 'oob_score': True, 'max_samples': 0.7512159481758783, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2306800956380543, 'warm_start': False}. Best is trial 52 with value: 0.8597273622329205.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.9196428571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.9342723004694836
[I 2024-04-17 13:57:05,085] Trial 57 finished with value: 0.8344693576064115 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 210, 'oob_score': True, 'max_samples': 0.8396231620676111, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05399922924530472, 'warm_start': True}. Best is trial 52 with value: 0.8597273622329205.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 13:57:07,250] Trial 58 finished with value: 0.7950421867153643 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 325, 'oob_score': True, 'max_samples': 0.9084872617838455, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10056372049643875, 'warm_start': True}. Best is trial 52 with value: 0.8597273622329205.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:57:09,142] Trial 59 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 299, 'oob_score': True, 'max_samples': 0.781109548070449, 'max_features': None, 'min_weight_fraction_leaf': 0.4460944453318119, 'warm_start': True}. Best is trial 52 with value: 0.8597273622329205.
Fold 1 C-index: 0.5497835497835498
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 13:57:13,069] Trial 60 finished with value: 0.6530313591424673 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 269, 'oob_score': True, 'max_samples': 0.13319246988341354, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.027601337763597054, 'warm_start': False}. Best is trial 52 with value: 0.8597273622329205.

Fold 1 C-index: 0.5541125541125541
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.9577464788732394
[I 2024-04-17 13:57:14,982] Trial 61 finished with value: 0.8356094054341618 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 245, 'oob_score': True, 'max_samples': 0.7063246200486797, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014922531876931325, 'warm_start': True}. Best is trial 52 with value: 0.8597273622329205.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.9330357142857143
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.9624413145539906
[I 2024-04-17 13:57:16,504] Trial 62 finished with value: 0.863026999118745 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 214, 'oob_score': True, 'max_samples': 0.6368459764866431, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0017616520072358624, 'warm_start': True}. Best is trial 62 with value: 0.863026999118745.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.8779342723004695
[I 2024-04-17 13:57:17,746] Trial 63 finished with value: 0.7904983685478923 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.6460289611890819, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06957709194995769, 'warm_start': True}. Best is trial 62 with value: 0.863026999118745.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.92018779342723
[I 2024-04-17 13:57:19,219] Trial 64 finished with value: 0.8242149414912726 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 211, 'oob_score': True, 'max_samples': 0.5943942085410625, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03608199905782723, 'warm_start': True}. Best is trial 62 with value: 0.863026999118745.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.8873239436619719
[I 2024-04-17 13:57:20,959] Trial 65 finished with value: 0.7986763659985138 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 265, 'oob_score': True, 'max_samples': 0.6282156254684211, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05453776899332265, 'warm_start': True}. Best is trial 62 with value: 0.863026999118745.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.9375
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9624413145539906
[I 2024-04-17 13:57:22,983] Trial 66 finished with value: 0.8650417549635456 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 286, 'oob_score': True, 'max_samples': 0.7543381305861245, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.016331978956231737, 'warm_start': True}. Best is trial 66 with value: 0.8650417549635456.
Fold 1 C-index: 0.45021645021645024
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.6887254901960784
Fold 4 C-index: 0.6983122362869199
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 13:57:25,523] Trial 67 finished with value: 0.6697186086463953 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.7578295007706223, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3355807148136194, 'warm_start': True}. Best is trial 66 with value: 0.8650417549635456.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.9436619718309859
[I 2024-04-17 13:57:28,244] Trial 68 finished with value: 0.8414712027779393 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 409, 'oob_score': True, 'max_samples': 0.7980948481366319, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.017460996084981972, 'warm_start': True}. Best is trial 66 with value: 0.8650417549635456.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8356807511737089
[I 2024-04-17 13:57:30,136] Trial 69 finished with value: 0.7665253794592279 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.5233711058599282, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07260048680906032, 'warm_start': True}. Best is trial 66 with value: 0.8650417549635456.
Fold 1 C-index: 0.551948051948052
Fold 2 C-index: 0.8504464285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.8591549295774648
[I 2024-04-17 13:57:31,389] Trial 70 finished with value: 0.7859162359533677 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 311, 'oob_score': False, 'max_samples': 0.835844635111363, 'max_features': None, 'min_weight_fraction_leaf': 0.14010515265451262, 'warm_start': True}. Best is trial 66 with value: 0.8650417549635456.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.9196428571428571
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.9577464788732394
[I 2024-04-17 13:57:32,898] Trial 71 finished with value: 0.8541877401051993 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.736113827911723, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.032932913391902074, 'warm_start': True}. Best is trial 66 with value: 0.8650417549635456.
Fold 1 C-index: 0.5541125541125541
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.9577464788732394
[I 2024-04-17 13:57:34,573] Trial 72 finished with value: 0.8382390015764163 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 237, 'oob_score': True, 'max_samples': 0.6721721251553224, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.012722659243551515, 'warm_start': True}. Best is trial 66 with value: 0.8650417549635456.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.9196428571428571
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.9483568075117371
[I 2024-04-17 13:57:36,768] Trial 73 finished with value: 0.852968343125837 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 283, 'oob_score': True, 'max_samples': 0.7067242004030547, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.002798840412579947, 'warm_start': True}. Best is trial 66 with value: 0.8650417549635456.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.9061032863849765
[I 2024-04-17 13:57:38,078] Trial 74 finished with value: 0.824691169762772 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 181, 'oob_score': True, 'max_samples': 0.5841362104288059, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04423638358847913, 'warm_start': True}. Best is trial 66 with value: 0.8650417549635456.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.9330357142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.9624413145539906
[I 2024-04-17 13:57:39,930] Trial 75 finished with value: 0.859422289110461 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 260, 'oob_score': True, 'max_samples': 0.7762562426777766, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02707798966426385, 'warm_start': True}. Best is trial 66 with value: 0.8650417549635456.

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.9248826291079812
[I 2024-04-17 13:57:41,776] Trial 76 finished with value: 0.832427856756732 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 262, 'oob_score': True, 'max_samples': 0.8835812085262204, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06134139850886937, 'warm_start': True}. Best is trial 66 with value: 0.8650417549635456.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.9389671361502347
[I 2024-04-17 13:57:43,642] Trial 77 finished with value: 0.841283445216528 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 277, 'oob_score': True, 'max_samples': 0.7794118627973103, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02273424703617286, 'warm_start': True}. Best is trial 66 with value: 0.8650417549635456.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.8779342723004695
[I 2024-04-17 13:57:45,678] Trial 78 finished with value: 0.7888813581073527 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 321, 'oob_score': True, 'max_samples': 0.8112148722278497, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09206156242995645, 'warm_start': True}. Best is trial 66 with value: 0.8650417549635456.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.9530516431924883
[I 2024-04-17 13:57:47,716] Trial 79 finished with value: 0.8486585335361069 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 300, 'oob_score': True, 'max_samples': 0.6453872670164413, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02861397815678767, 'warm_start': True}. Best is trial 66 with value: 0.8650417549635456.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 13:57:55,141] Trial 80 finished with value: 0.664632855970635 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 483, 'oob_score': True, 'max_samples': 0.739751964888177, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10386652069615948, 'warm_start': False}. Best is trial 66 with value: 0.8650417549635456.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.9330357142857143
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.9577464788732394
[I 2024-04-17 13:57:56,853] Trial 81 finished with value: 0.8580101292449749 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 234, 'oob_score': True, 'max_samples': 0.7176128038233716, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011547364903702078, 'warm_start': True}. Best is trial 66 with value: 0.8650417549635456.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.9375
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.9624413145539906
[I 2024-04-17 13:57:58,660] Trial 82 finished with value: 0.8615028019830439 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 256, 'oob_score': True, 'max_samples': 0.7206104191217548, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011804762894689113, 'warm_start': True}. Best is trial 66 with value: 0.8650417549635456.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.9375
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9765258215962441
[I 2024-04-17 13:58:00,068] Trial 83 finished with value: 0.8687682952563186 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 200, 'oob_score': True, 'max_samples': 0.7677985157963092, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014187732139247584, 'warm_start': True}. Best is trial 83 with value: 0.8687682952563186.
Fold 1 C-index: 0.5541125541125541
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.9154929577464789
[I 2024-04-17 13:58:01,741] Trial 84 finished with value: 0.8198230454275098 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 222, 'oob_score': True, 'max_samples': 0.7142194405899176, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05190567347245874, 'warm_start': True}. Best is trial 83 with value: 0.8687682952563186.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.9375
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.971830985915493
[I 2024-04-17 13:58:03,148] Trial 85 finished with value: 0.8704974839901114 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 195, 'oob_score': True, 'max_samples': 0.8265187125779403, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.012312929606053803, 'warm_start': True}. Best is trial 85 with value: 0.8704974839901114.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8591549295774648
[I 2024-04-17 13:58:04,513] Trial 86 finished with value: 0.7831866242582869 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 196, 'oob_score': True, 'max_samples': 0.8522602689268013, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.035801117735038884, 'warm_start': True}. Best is trial 85 with value: 0.8704974839901114.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.9196428571428571
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.9389671361502347
[I 2024-04-17 13:58:05,319] Trial 87 finished with value: 0.8360449430262389 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 203, 'oob_score': False, 'max_samples': 0.8269084615266215, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0458571199390998, 'warm_start': True}. Best is trial 85 with value: 0.8704974839901114.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.8967136150234741
[I 2024-04-17 13:58:06,504] Trial 88 finished with value: 0.8244688056587002 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 160, 'oob_score': True, 'max_samples': 0.7963514319659221, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.010407019829843949, 'warm_start': True}. Best is trial 85 with value: 0.8704974839901114.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8370535714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.9107981220657277
[I 2024-04-17 13:58:07,877] Trial 89 finished with value: 0.8073473965876079 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 189, 'oob_score': True, 'max_samples': 0.6758583929811339, 'max_features': None, 'min_weight_fraction_leaf': 0.06265314502868645, 'warm_start': True}. Best is trial 85 with value: 0.8704974839901114.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.9014084507042254
[I 2024-04-17 13:58:09,481] Trial 90 finished with value: 0.8123128167456872 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 177, 'oob_score': True, 'max_samples': 0.8905311600876464, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08079152043866945, 'warm_start': True}. Best is trial 85 with value: 0.8704974839901114.

Fold 1 C-index: 0.5541125541125541
Fold 2 C-index: 0.9375
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9624413145539906
[I 2024-04-17 13:58:10,611] Trial 91 finished with value: 0.8616223895188636 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 131, 'oob_score': True, 'max_samples': 0.7266430770419074, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.013145118534161632, 'warm_start': True}. Best is trial 85 with value: 0.8704974839901114.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.9375
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.971830985915493
[I 2024-04-17 13:58:11,647] Trial 92 finished with value: 0.8644099626754865 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 131, 'oob_score': True, 'max_samples': 0.7699875152510853, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.015679420027177773, 'warm_start': True}. Best is trial 85 with value: 0.8704974839901114.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.9285714285714286
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9671361502347418
[I 2024-04-17 13:58:12,416] Trial 93 finished with value: 0.8686824414525693 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 88, 'oob_score': True, 'max_samples': 0.7651642719285108, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.015231193541847668, 'warm_start': True}. Best is trial 85 with value: 0.8704974839901114.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.9285714285714286
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.971830985915493
[I 2024-04-17 13:58:13,440] Trial 94 finished with value: 0.8608926466581706 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.7836438921572607, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.022517783878002184, 'warm_start': True}. Best is trial 85 with value: 0.8704974839901114.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.9530516431924883
[I 2024-04-17 13:58:14,458] Trial 95 finished with value: 0.8400224438873589 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.8092059079884016, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01709605690231171, 'warm_start': True}. Best is trial 85 with value: 0.8704974839901114.
Fold 1 C-index: 0.551948051948052
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 13:58:15,220] Trial 96 finished with value: 0.7151359994961533 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 19, 'n_estimators': 103, 'oob_score': True, 'max_samples': 0.7433249138555309, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.036843628657681815, 'warm_start': True}. Best is trial 85 with value: 0.8704974839901114.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.9196428571428571
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.9624413145539906
[I 2024-04-17 13:58:15,968] Trial 97 finished with value: 0.8586387449678327 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 86, 'oob_score': True, 'max_samples': 0.7631066149705504, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01334758804769574, 'warm_start': True}. Best is trial 85 with value: 0.8704974839901114.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 13:58:17,072] Trial 98 finished with value: 0.6784765410645692 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 55, 'oob_score': True, 'max_samples': 0.7837842684959005, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04494912001288324, 'warm_start': False}. Best is trial 85 with value: 0.8704974839901114.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8734177215189873

[I 2024-04-17 13:58:18,206] A new study created in memory with name: no-name-a01d4a28-b83b-48c5-800a-3e3533175c59

Fold 5 C-index: 0.9248826291079812
[I 2024-04-17 13:58:18,196] Trial 99 finished with value: 0.8306589242124831 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 141, 'oob_score': True, 'max_samples': 0.8538091970661471, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05465543261124461, 'warm_start': True}. Best is trial 85 with value: 0.8704974839901114.


* Best trial for C-index:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.8704974839901114], datetime_start=datetime.datetime(2024, 4, 17, 13, 58, 1, 746373), datetime_complete=datetime.datetime(2024, 4, 17, 13, 58, 3, 147911), params={'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 195, 'oob_score': True, 'max_samples': 0.8265187125779403, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.012312929606053803, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=85, value=None)


* Best Score for C-index:
 0.8704974839901114

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.19757631318398647
Fold 2 IBS: 0.1936155943711696
Fold 3 IBS: 0.17772439744425161
Fold 4 IBS: 0.16516670984739804
Fold 5 IBS: 0.18542222028242625
[I 2024-04-17 13:58:22,799] Trial 0 finished with value: 0.1839010470258464 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.1839010470258464.
Fold 1 IBS: 0.2125499429976963
Fold 2 IBS: 0.18754286365926276
Fold 3 IBS: 0.18821274904657284
Fold 4 IBS: 0.18251023024083166
Fold 5 IBS: 0.19561361602576738
[I 2024-04-17 13:58:23,895] Trial 1 finished with value: 0.1932858803940262 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 0 with value: 0.1839010470258464.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-17 13:58:24,694] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 0 with value: 0.1839010470258464.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-17 13:58:27,744] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 0 with value: 0.1839010470258464.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-17 13:58:30,225] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 0 with value: 0.1839010470258464.
Fold 1 IBS: 0.2282153162904868
Fold 2 IBS: 0.18124005290910364
Fold 3 IBS: 0.19037313393116712
Fold 4 IBS: 0.17290558282293772
Fold 5 IBS: 0.18131843994152572
[I 2024-04-17 13:58:34,078] Trial 5 finished with value: 0.19081050517904422 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 0 with value: 0.1839010470258464.
Fold 1 IBS: 0.23245389032674732
Fold 2 IBS: 0.19623207478964957
Fold 3 IBS: 0.18592392826979878
Fold 4 IBS: 0.19675905992259593
Fold 5 IBS: 0.1927841686980754
[I 2024-04-17 13:58:37,363] Trial 6 finished with value: 0.2008306244013734 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 0 with value: 0.1839010470258464.
Fold 1 IBS: 0.21685833795861092
Fold 2 IBS: 0.21762942137075017
Fold 3 IBS: 0.20376357441614318
Fold 4 IBS: 0.22103528745396656
Fold 5 IBS: 0.21469951567345374
[I 2024-04-17 13:58:41,356] Trial 7 finished with value: 0.2147972273745849 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 0 with value: 0.1839010470258464.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-17 13:58:47,632] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 0 with value: 0.1839010470258464.
Fold 1 IBS: 0.20795232622138007
Fold 2 IBS: 0.1893631069049647
Fold 3 IBS: 0.19032951979948623
Fold 4 IBS: 0.18704684004244632
Fold 5 IBS: 0.19693016115883294
[I 2024-04-17 13:58:49,116] Trial 9 finished with value: 0.19432439082542205 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 0 with value: 0.1839010470258464.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-17 13:58:56,112] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27033688725897076}. Best is trial 0 with value: 0.1839010470258464.
Fold 1 IBS: 0.2100911902057935
Fold 2 IBS: 0.2136273715855562
Fold 3 IBS: 0.20254225595442774
Fold 4 IBS: 0.20876890014504462
Fold 5 IBS: 0.20117795223350374
[I 2024-04-17 13:59:00,132] Trial 11 finished with value: 0.20724153402486517 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.751058151425702, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008231293935378081}. Best is trial 0 with value: 0.1839010470258464.
Fold 1 IBS: 0.2296480179491222
Fold 2 IBS: 0.18367177103181279
Fold 3 IBS: 0.1920491086184665
Fold 4 IBS: 0.1718555311555952
Fold 5 IBS: 0.18298922167710202
[I 2024-04-17 13:59:04,268] Trial 12 finished with value: 0.19204273008641976 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.9944667777599061, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10294337889507951}. Best is trial 0 with value: 0.1839010470258464.
Fold 1 IBS: 0.2018497135220332
Fold 2 IBS: 0.1553617299179047
Fold 3 IBS: 0.1906654866771308
Fold 4 IBS: 0.16126857092304636
Fold 5 IBS: 0.17165622063118316
[I 2024-04-17 13:59:09,129] Trial 13 finished with value: 0.17616034433425964 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.7506280278256608, 'max_features': None, 'min_weight_fraction_leaf': 0.17802395769468754}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.20021444048400025
Fold 2 IBS: 0.19285629910326904
Fold 3 IBS: 0.18385194929019555
Fold 4 IBS: 0.16184724258290872
Fold 5 IBS: 0.1813467135923723
[I 2024-04-17 13:59:14,585] Trial 14 finished with value: 0.18402332901054916 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 421, 'oob_score': False, 'max_samples': 0.7898381756004584, 'max_features': None, 'min_weight_fraction_leaf': 0.20922982958953967}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.20869031308617586
Fold 2 IBS: 0.15117289634479442
Fold 3 IBS: 0.19305310001124065
Fold 4 IBS: 0.16314142458650782
Fold 5 IBS: 0.1705932132024561
[I 2024-04-17 13:59:19,972] Trial 15 finished with value: 0.17733018944623496 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.7059524688478641, 'max_features': None, 'min_weight_fraction_leaf': 0.15226079706942128}. Best is trial 13 with value: 0.17616034433425964.

Fold 1 IBS: 0.23357335015951022
Fold 2 IBS: 0.1434880786569596
Fold 3 IBS: 0.19904518249376676
Fold 4 IBS: 0.16326560759199357
Fold 5 IBS: 0.16490838291406798
[I 2024-04-17 13:59:26,284] Trial 16 finished with value: 0.18085612036325963 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.8672735056922112, 'max_features': None, 'min_weight_fraction_leaf': 0.1240628386604349}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.2139729133686712
Fold 2 IBS: 0.22124242270782168
Fold 3 IBS: 0.20488026153087194
Fold 4 IBS: 0.22461419937481336
Fold 5 IBS: 0.2186104104246879
[I 2024-04-17 13:59:31,232] Trial 17 finished with value: 0.21666404148137325 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.4295671282480755, 'max_features': None, 'min_weight_fraction_leaf': 0.3016103171783554}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.233902737619287
Fold 2 IBS: 0.18034082214938632
Fold 3 IBS: 0.19919937722516895
Fold 4 IBS: 0.16345655093490655
Fold 5 IBS: 0.1726671265687199
[I 2024-04-17 13:59:38,704] Trial 18 finished with value: 0.18991332289949375 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 398, 'oob_score': True, 'max_samples': 0.6155156742664507, 'max_features': None, 'min_weight_fraction_leaf': 0.014279110100291703}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21739695485627053
Fold 2 IBS: 0.1893550939927779
Fold 3 IBS: 0.1904175992476902
Fold 4 IBS: 0.18295775459085295
Fold 5 IBS: 0.18900433725133364
[I 2024-04-17 13:59:41,382] Trial 19 finished with value: 0.19382634798778503 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 201, 'oob_score': False, 'max_samples': 0.810533870510241, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16269343116139728}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.22999480799482466
Fold 2 IBS: 0.18631651787082243
Fold 3 IBS: 0.19057033450126984
Fold 4 IBS: 0.1757821711602906
Fold 5 IBS: 0.18460821160169077
[I 2024-04-17 13:59:48,155] Trial 20 finished with value: 0.19345440862577967 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.9796879018569671, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15145999404321092}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.2355034576469301
Fold 2 IBS: 0.14321926432085194
Fold 3 IBS: 0.19904930323796566
Fold 4 IBS: 0.16321477130171202
Fold 5 IBS: 0.16474717715648202
[I 2024-04-17 13:59:54,265] Trial 21 finished with value: 0.18114679473278833 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.8734190579277047, 'max_features': None, 'min_weight_fraction_leaf': 0.10796776799958208}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.22508165158372606
Fold 2 IBS: 0.1771545732007252
Fold 3 IBS: 0.1997830135764283
Fold 4 IBS: 0.1630435062225716
Fold 5 IBS: 0.17276635675398527
[I 2024-04-17 13:59:59,316] Trial 22 finished with value: 0.1875658202674873 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 379, 'oob_score': False, 'max_samples': 0.757532156434341, 'max_features': None, 'min_weight_fraction_leaf': 0.13109574406399355}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.20035821903362086
Fold 2 IBS: 0.19309180992934658
Fold 3 IBS: 0.18478486746515346
Fold 4 IBS: 0.1617405754034111
Fold 5 IBS: 0.18120076967673399
[I 2024-04-17 14:00:05,409] Trial 23 finished with value: 0.18423524830165322 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 446, 'oob_score': False, 'max_samples': 0.9033408110333553, 'max_features': None, 'min_weight_fraction_leaf': 0.23974104380133898}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21009142432329225
Fold 2 IBS: 0.18044589851273088
Fold 3 IBS: 0.195746991709859
Fold 4 IBS: 0.16305239593245105
Fold 5 IBS: 0.17283197168460374
[I 2024-04-17 14:00:10,123] Trial 24 finished with value: 0.18443373643258737 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 327, 'oob_score': False, 'max_samples': 0.6718319233339587, 'max_features': None, 'min_weight_fraction_leaf': 0.05123993497376386}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.2140323508660924
Fold 2 IBS: 0.185669358114302
Fold 3 IBS: 0.1988944328449939
Fold 4 IBS: 0.16342534585941004
Fold 5 IBS: 0.1766582611752558
[I 2024-04-17 14:00:15,340] Trial 25 finished with value: 0.1877359497720108 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 390, 'oob_score': False, 'max_samples': 0.8069748547417218, 'max_features': None, 'min_weight_fraction_leaf': 0.1798548570607717}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21128576610933253
Fold 2 IBS: 0.15075346168150194
Fold 3 IBS: 0.19353960547239776
Fold 4 IBS: 0.1633661332680657
Fold 5 IBS: 0.16956736943370437
[I 2024-04-17 14:00:23,371] Trial 26 finished with value: 0.17770246719300045 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 497, 'oob_score': True, 'max_samples': 0.6057707120854023, 'max_features': None, 'min_weight_fraction_leaf': 0.12407158281730171}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21398911502506177
Fold 2 IBS: 0.22111137693103425
Fold 3 IBS: 0.20492072860328456
Fold 4 IBS: 0.2247096500410391
Fold 5 IBS: 0.21870049286707827
[I 2024-04-17 14:00:27,137] Trial 27 finished with value: 0.21668627269349958 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 252, 'oob_score': True, 'max_samples': 0.41744632759744454, 'max_features': None, 'min_weight_fraction_leaf': 0.2432850333525734}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21398925110290773
Fold 2 IBS: 0.22146985987522272
Fold 3 IBS: 0.20479673171574342
Fold 4 IBS: 0.22463667964194062
Fold 5 IBS: 0.21855108417295457
[I 2024-04-17 14:00:34,668] Trial 28 finished with value: 0.2166887213017538 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 499, 'oob_score': True, 'max_samples': 0.5995515717767183, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.32952757983019043}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.19737086171611992
Fold 2 IBS: 0.19396277268269155
Fold 3 IBS: 0.1776295959110612
Fold 4 IBS: 0.16464023627008964
Fold 5 IBS: 0.18542628739792386
[I 2024-04-17 14:00:40,614] Trial 29 finished with value: 0.1838059507955772 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 370, 'oob_score': True, 'max_samples': 0.703578614293525, 'max_features': None, 'min_weight_fraction_leaf': 0.21510951321325295}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.22701205699790405
Fold 2 IBS: 0.1864179416956087
Fold 3 IBS: 0.18895461988448575
Fold 4 IBS: 0.1692788261335548
Fold 5 IBS: 0.17663740832557842
[I 2024-04-17 14:00:47,839] Trial 30 finished with value: 0.18966017060742635 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 450, 'oob_score': True, 'max_samples': 0.48117992276336774, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03971915358024672}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.22216243174993294
Fold 2 IBS: 0.14571311993331576
Fold 3 IBS: 0.1967761477781634
Fold 4 IBS: 0.16305270732378244
Fold 5 IBS: 0.16672611903805418
[I 2024-04-17 14:00:54,236] Trial 31 finished with value: 0.17888610516464976 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 473, 'oob_score': False, 'max_samples': 0.7258236905140616, 'max_features': None, 'min_weight_fraction_leaf': 0.12112865983693538}. Best is trial 13 with value: 0.17616034433425964.

Fold 1 IBS: 0.2137371773904688
Fold 2 IBS: 0.14754581156917576
Fold 3 IBS: 0.19507773705994372
Fold 4 IBS: 0.163288198777688
Fold 5 IBS: 0.16776329561114334
[I 2024-04-17 14:01:00,788] Trial 32 finished with value: 0.17748244408168393 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 414, 'oob_score': True, 'max_samples': 0.7181306651480585, 'max_features': None, 'min_weight_fraction_leaf': 0.13587869431214727}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.19767026532023416
Fold 2 IBS: 0.19261585838585468
Fold 3 IBS: 0.1783911196474173
Fold 4 IBS: 0.16382095692225104
Fold 5 IBS: 0.18359776371304465
[I 2024-04-17 14:01:08,233] Trial 33 finished with value: 0.18321919279776036 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 414, 'oob_score': True, 'max_samples': 0.6267475337287517, 'max_features': None, 'min_weight_fraction_leaf': 0.18192025362012787}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.24387786989040464
Fold 2 IBS: 0.18426413378671008
Fold 3 IBS: 0.19609951431971906
Fold 4 IBS: 0.16273577015342508
Fold 5 IBS: 0.17455402746092397
[I 2024-04-17 14:01:15,542] Trial 34 finished with value: 0.1923062631222366 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 362, 'oob_score': True, 'max_samples': 0.6846402676013689, 'max_features': None, 'min_weight_fraction_leaf': 0.07988947619522271}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.19931160042749377
Fold 2 IBS: 0.18644497939161941
Fold 3 IBS: 0.18081623345367076
Fold 4 IBS: 0.1644184948175443
Fold 5 IBS: 0.1846863854832651
[I 2024-04-17 14:01:18,055] Trial 35 finished with value: 0.18313553871471866 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 140, 'oob_score': True, 'max_samples': 0.5307784970654135, 'max_features': None, 'min_weight_fraction_leaf': 0.15235331771930077}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.1998677585504934
Fold 2 IBS: 0.18979631166628672
Fold 3 IBS: 0.18601144590013044
Fold 4 IBS: 0.16186832003028767
Fold 5 IBS: 0.1784017687121209
[I 2024-04-17 14:01:25,395] Trial 36 finished with value: 0.18318912097186382 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 443, 'oob_score': True, 'max_samples': 0.6410929172717122, 'max_features': None, 'min_weight_fraction_leaf': 0.09754506806309649}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21120934961441562
Fold 2 IBS: 0.1918923912382808
Fold 3 IBS: 0.19521091971844187
Fold 4 IBS: 0.18696949316361353
Fold 5 IBS: 0.1972193521893067
[I 2024-04-17 14:01:26,030] Trial 37 finished with value: 0.1965003011848117 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 22, 'oob_score': True, 'max_samples': 0.5746134765921079, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14868360924763024}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.20686400989809292
Fold 2 IBS: 0.18016945061784004
Fold 3 IBS: 0.17892970554607882
Fold 4 IBS: 0.1733170311908194
Fold 5 IBS: 0.18653331455484856
[I 2024-04-17 14:01:32,921] Trial 38 finished with value: 0.18516270236153595 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 392, 'oob_score': True, 'max_samples': 0.5203696980450719, 'max_features': None, 'min_weight_fraction_leaf': 0.17475297471263174}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.2001580791425211
Fold 2 IBS: 0.18763919207948893
Fold 3 IBS: 0.17659812951719953
Fold 4 IBS: 0.1666966104396291
Fold 5 IBS: 0.18533328097625879
[I 2024-04-17 14:01:39,279] Trial 39 finished with value: 0.1832850584310195 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 339, 'oob_score': True, 'max_samples': 0.7366117184440497, 'max_features': None, 'min_weight_fraction_leaf': 0.23606155804183482}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21401121610173135
Fold 2 IBS: 0.22048930634855285
Fold 3 IBS: 0.20513775480444385
Fold 4 IBS: 0.2247010341335635
Fold 5 IBS: 0.21773020620724054
[I 2024-04-17 14:01:44,794] Trial 40 finished with value: 0.2164139035191064 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 308, 'oob_score': True, 'max_samples': 0.23889817954390774, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07880882141692147}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21680188850827423
Fold 2 IBS: 0.14770357740600118
Fold 3 IBS: 0.19530256380032265
Fold 4 IBS: 0.16311319110329872
Fold 5 IBS: 0.16740558371305028
[I 2024-04-17 14:01:52,863] Trial 41 finished with value: 0.1780653609061894 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 468, 'oob_score': False, 'max_samples': 0.70131497146519, 'max_features': None, 'min_weight_fraction_leaf': 0.12825576246377854}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.19975754407329396
Fold 2 IBS: 0.15833342694308195
Fold 3 IBS: 0.18887961053953017
Fold 4 IBS: 0.16100543729480274
Fold 5 IBS: 0.17340788178957556
[I 2024-04-17 14:01:59,036] Trial 42 finished with value: 0.17627678012805686 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 409, 'oob_score': False, 'max_samples': 0.7795573310870321, 'max_features': None, 'min_weight_fraction_leaf': 0.19406692239705875}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21397625776785953
Fold 2 IBS: 0.22129500425261062
Fold 3 IBS: 0.20478438279309738
Fold 4 IBS: 0.22464161104046773
Fold 5 IBS: 0.2186014117099136
[I 2024-04-17 14:02:05,387] Trial 43 finished with value: 0.21665973351278978 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 405, 'oob_score': False, 'max_samples': 0.8297480471210651, 'max_features': None, 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.1999320192468163
Fold 2 IBS: 0.19212659128252202
Fold 3 IBS: 0.18384842383476616
Fold 4 IBS: 0.16208165124595328
Fold 5 IBS: 0.18022875569265706
[I 2024-04-17 14:02:16,707] Trial 44 finished with value: 0.18364348826054297 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 434, 'oob_score': False, 'max_samples': 0.7697989204400967, 'max_features': None, 'min_weight_fraction_leaf': 0.20113914786891474}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21921396222838868
Fold 2 IBS: 0.19920546355038837
Fold 3 IBS: 0.1927346515710331
Fold 4 IBS: 0.19745882945766802
Fold 5 IBS: 0.20336752676350664
[I 2024-04-17 14:02:24,334] Trial 45 finished with value: 0.20239608671419695 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.6543709124655812, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22547277453373687}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21546329067488545
Fold 2 IBS: 0.1962612612488198
Fold 3 IBS: 0.19110368242458967
Fold 4 IBS: 0.1921960404314738
Fold 5 IBS: 0.19974074420313917
[I 2024-04-17 14:02:34,990] Trial 46 finished with value: 0.19895300379658157 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 498, 'oob_score': False, 'max_samples': 0.5805803688246316, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18292363939929962}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.1987804113604285
Fold 2 IBS: 0.19446393366259412
Fold 3 IBS: 0.1807905269873362
Fold 4 IBS: 0.16191522431299366
Fold 5 IBS: 0.18414342559628924
[I 2024-04-17 14:02:41,928] Trial 47 finished with value: 0.18401870438392837 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 271, 'oob_score': True, 'max_samples': 0.9479166380117069, 'max_features': None, 'min_weight_fraction_leaf': 0.26866450708603773}. Best is trial 13 with value: 0.17616034433425964.

Fold 1 IBS: 0.21398467576624647
Fold 2 IBS: 0.22137341375753541
Fold 3 IBS: 0.204866353457904
Fold 4 IBS: 0.2246611229640241
Fold 5 IBS: 0.21854516772012514
[I 2024-04-17 14:02:47,524] Trial 48 finished with value: 0.21668614673316702 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 313, 'oob_score': False, 'max_samples': 0.7858952696573706, 'max_features': None, 'min_weight_fraction_leaf': 0.39308816597832114}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21227701143752029
Fold 2 IBS: 0.19801412173527871
Fold 3 IBS: 0.19081561304604946
Fold 4 IBS: 0.19186135351143677
Fold 5 IBS: 0.19928102321132793
[I 2024-04-17 14:02:50,572] Trial 49 finished with value: 0.1984498245883226 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 17, 'n_estimators': 187, 'oob_score': False, 'max_samples': 0.8459565404966409, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2662542463539984}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21521241664947327
Fold 2 IBS: 0.1471041102569012
Fold 3 IBS: 0.19553058874897247
Fold 4 IBS: 0.1632386137150279
Fold 5 IBS: 0.16777271857485507
[I 2024-04-17 14:03:05,400] Trial 50 finished with value: 0.177771689589046 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.7258380868475101, 'max_features': None, 'min_weight_fraction_leaf': 0.14147922592542847}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21502905496581015
Fold 2 IBS: 0.1472241004168946
Fold 3 IBS: 0.19536863247684147
Fold 4 IBS: 0.16327930192089166
Fold 5 IBS: 0.16795806619032208
[I 2024-04-17 14:03:15,356] Trial 51 finished with value: 0.177771831194152 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 411, 'oob_score': True, 'max_samples': 0.7257736324727647, 'max_features': None, 'min_weight_fraction_leaf': 0.1422738010196732}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.23148489655179888
Fold 2 IBS: 0.17401568540246776
Fold 3 IBS: 0.1990268592376547
Fold 4 IBS: 0.16141096164079868
Fold 5 IBS: 0.16919005915653737
[I 2024-04-17 14:03:24,884] Trial 52 finished with value: 0.1870256923978515 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 352, 'oob_score': True, 'max_samples': 0.6714166864042788, 'max_features': None, 'min_weight_fraction_leaf': 0.09681637347519291}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21497857301860723
Fold 2 IBS: 0.18508403414630628
Fold 3 IBS: 0.19680160554269266
Fold 4 IBS: 0.16207792697308493
Fold 5 IBS: 0.17679183388216824
[I 2024-04-17 14:03:35,664] Trial 53 finished with value: 0.18714679471257184 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.7716838745445642, 'max_features': None, 'min_weight_fraction_leaf': 0.1650827581457044}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.20015447059796845
Fold 2 IBS: 0.1768563012999109
Fold 3 IBS: 0.17814469733017224
Fold 4 IBS: 0.16747713035390124
Fold 5 IBS: 0.18373399266477275
[I 2024-04-17 14:03:46,443] Trial 54 finished with value: 0.1812733184493451 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 481, 'oob_score': True, 'max_samples': 0.6155351113478028, 'max_features': None, 'min_weight_fraction_leaf': 0.19212667987455512}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.22360034596184747
Fold 2 IBS: 0.18325265548667552
Fold 3 IBS: 0.1924900798759495
Fold 4 IBS: 0.17861287950397367
Fold 5 IBS: 0.1860557295153586
[I 2024-04-17 14:03:53,115] Trial 55 finished with value: 0.19280233806876096 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 394, 'oob_score': False, 'max_samples': 0.8991394692357875, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11441831084016102}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.22233529134197932
Fold 2 IBS: 0.1864052240012748
Fold 3 IBS: 0.19270013269510625
Fold 4 IBS: 0.17986174343946498
Fold 5 IBS: 0.1874914423491104
[I 2024-04-17 14:04:02,197] Trial 56 finished with value: 0.19375876676538717 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.8115396566227338, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14245877204357915}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21738996927525128
Fold 2 IBS: 0.18170840377591088
Fold 3 IBS: 0.1985757388676358
Fold 4 IBS: 0.1629780673633381
Fold 5 IBS: 0.17595464890263746
[I 2024-04-17 14:04:14,172] Trial 57 finished with value: 0.1873213656369547 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 455, 'oob_score': False, 'max_samples': 0.6955818921396308, 'max_features': None, 'min_weight_fraction_leaf': 0.06327330225827416}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.1968108032607562
Fold 2 IBS: 0.1950011090621009
Fold 3 IBS: 0.1769783125666974
Fold 4 IBS: 0.16325239204774064
Fold 5 IBS: 0.18560872618875196
[I 2024-04-17 14:04:21,749] Trial 58 finished with value: 0.18353026862520944 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 14, 'n_estimators': 328, 'oob_score': False, 'max_samples': 0.7474032265937102, 'max_features': None, 'min_weight_fraction_leaf': 0.2021462196205936}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.20678122001798754
Fold 2 IBS: 0.18163828297832504
Fold 3 IBS: 0.17896798716651813
Fold 4 IBS: 0.17463482089006063
Fold 5 IBS: 0.18691149531801468
[I 2024-04-17 14:04:34,627] Trial 59 finished with value: 0.1857867612741812 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 383, 'oob_score': True, 'max_samples': 0.49436966830864176, 'max_features': None, 'min_weight_fraction_leaf': 0.16652068514149343}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21400080043067396
Fold 2 IBS: 0.17886618001187188
Fold 3 IBS: 0.19548224648731521
Fold 4 IBS: 0.16308432593218936
Fold 5 IBS: 0.173672235836244
[I 2024-04-17 14:04:44,498] Trial 60 finished with value: 0.1850211577396589 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.6379580051387054, 'max_features': None, 'min_weight_fraction_leaf': 0.13427711936808312}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.21367164996489554
Fold 2 IBS: 0.14764039965857687
Fold 3 IBS: 0.19507955211676606
Fold 4 IBS: 0.16329555337518017
Fold 5 IBS: 0.1680338712528808
[I 2024-04-17 14:04:58,434] Trial 61 finished with value: 0.1775442052736599 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 409, 'oob_score': True, 'max_samples': 0.725131324450598, 'max_features': None, 'min_weight_fraction_leaf': 0.14144944414579388}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.22689406354128247
Fold 2 IBS: 0.14519937197322072
Fold 3 IBS: 0.19695685549750297
Fold 4 IBS: 0.16297693181132278
Fold 5 IBS: 0.1664266440432608
[I 2024-04-17 14:05:10,684] Trial 62 finished with value: 0.17969077337331793 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 356, 'oob_score': True, 'max_samples': 0.7205224319255107, 'max_features': None, 'min_weight_fraction_leaf': 0.09415069723492202}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.19540597076307947
Fold 2 IBS: 0.16647296246472013
Fold 3 IBS: 0.18290166077114245
Fold 4 IBS: 0.16135361859636888
Fold 5 IBS: 0.17947373396602923
[I 2024-04-17 14:05:23,597] Trial 63 finished with value: 0.17712158931226804 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.7963033908324706, 'max_features': None, 'min_weight_fraction_leaf': 0.2232661473947734}. Best is trial 13 with value: 0.17616034433425964.

Fold 1 IBS: 0.20061974377556896
Fold 2 IBS: 0.19195992762207684
Fold 3 IBS: 0.18557737837059887
Fold 4 IBS: 0.1615581866550213
Fold 5 IBS: 0.1802485594679016
[I 2024-04-17 14:05:33,709] Trial 64 finished with value: 0.18399275917823352 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.8450605263280312, 'max_features': None, 'min_weight_fraction_leaf': 0.22089138895350868}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.2193229187697933
Fold 2 IBS: 0.1890601235291585
Fold 3 IBS: 0.17894888493273703
Fold 4 IBS: 0.1832473653779553
Fold 5 IBS: 0.18959401711872684
[I 2024-04-17 14:05:45,468] Trial 65 finished with value: 0.19203466194567417 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 459, 'oob_score': True, 'max_samples': 0.79560619712759, 'max_features': None, 'min_weight_fraction_leaf': 0.2983981973123606}. Best is trial 13 with value: 0.17616034433425964.
Fold 1 IBS: 0.1973652117598853
Fold 2 IBS: 0.16133734808725428
Fold 3 IBS: 0.1860188181684556
Fold 4 IBS: 0.16094971597516788
Fold 5 IBS: 0.17477266072929365
[I 2024-04-17 14:05:55,716] Trial 66 finished with value: 0.17608875094401136 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 379, 'oob_score': True, 'max_samples': 0.7505526916491491, 'max_features': None, 'min_weight_fraction_leaf': 0.1907905531669951}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.21738318394156014
Fold 2 IBS: 0.19777968507644822
Fold 3 IBS: 0.19216752966742992
Fold 4 IBS: 0.19624134279024388
Fold 5 IBS: 0.20249254713459963
[I 2024-04-17 14:06:04,307] Trial 67 finished with value: 0.20121285772205635 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 372, 'oob_score': False, 'max_samples': 0.7589036659852416, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2535346760757169}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.21576575627827482
Fold 2 IBS: 0.1905111975176887
Fold 3 IBS: 0.19136149158328228
Fold 4 IBS: 0.18354983626330543
Fold 5 IBS: 0.19064321829246467
[I 2024-04-17 14:06:15,738] Trial 68 finished with value: 0.1943662999870032 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 402, 'oob_score': True, 'max_samples': 0.8681854344564763, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19086546666216386}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.20166585075272875
Fold 2 IBS: 0.1559348866757421
Fold 3 IBS: 0.19122336476455978
Fold 4 IBS: 0.16168476409130025
Fold 5 IBS: 0.17082159234143593
[I 2024-04-17 14:06:29,390] Trial 69 finished with value: 0.17626609172515337 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 442, 'oob_score': True, 'max_samples': 0.89084585297461, 'max_features': None, 'min_weight_fraction_leaf': 0.2132975662833954}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.21697363419914148
Fold 2 IBS: 0.1881862035246597
Fold 3 IBS: 0.1913206243059484
Fold 4 IBS: 0.1837756001140405
Fold 5 IBS: 0.19133990757107303
[I 2024-04-17 14:06:37,195] Trial 70 finished with value: 0.19431919394297262 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 383, 'oob_score': False, 'max_samples': 0.9434679187201547, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2127044139948369}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.19526838115899492
Fold 2 IBS: 0.16697167773208538
Fold 3 IBS: 0.183501184872782
Fold 4 IBS: 0.1614814328947456
Fold 5 IBS: 0.1777670276529462
[I 2024-04-17 14:06:48,465] Trial 71 finished with value: 0.1769979408623108 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 440, 'oob_score': True, 'max_samples': 0.825366469947641, 'max_features': None, 'min_weight_fraction_leaf': 0.2292198103181077}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.19516829512210526
Fold 2 IBS: 0.16722140762550936
Fold 3 IBS: 0.18271712940703935
Fold 4 IBS: 0.1615760242859721
Fold 5 IBS: 0.1777670276529462
[I 2024-04-17 14:06:59,226] Trial 72 finished with value: 0.17688997681871443 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 440, 'oob_score': True, 'max_samples': 0.8229986799018543, 'max_features': None, 'min_weight_fraction_leaf': 0.229539817793811}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.1951839815402131
Fold 2 IBS: 0.1694064589869334
Fold 3 IBS: 0.18172885351607668
Fold 4 IBS: 0.16192337358548992
Fold 5 IBS: 0.17863799768606292
[I 2024-04-17 14:07:09,913] Trial 73 finished with value: 0.17737613306295522 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 441, 'oob_score': True, 'max_samples': 0.8892847600836129, 'max_features': None, 'min_weight_fraction_leaf': 0.2531141428184007}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.20348133125024223
Fold 2 IBS: 0.18970504784515507
Fold 3 IBS: 0.18968853534774247
Fold 4 IBS: 0.16157933346784964
Fold 5 IBS: 0.17913757713932416
[I 2024-04-17 14:07:21,695] Trial 74 finished with value: 0.18471836501006272 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 477, 'oob_score': True, 'max_samples': 0.9436443471097903, 'max_features': None, 'min_weight_fraction_leaf': 0.23267793339764808}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.2226498619370068
Fold 2 IBS: 0.1916305505797115
Fold 3 IBS: 0.18020346871870882
Fold 4 IBS: 0.18764172157457235
Fold 5 IBS: 0.19002468083565763
[I 2024-04-17 14:07:34,234] Trial 75 finished with value: 0.19443005672913144 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.8203079000294053, 'max_features': None, 'min_weight_fraction_leaf': 0.3160611948377179}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.19555999085345324
Fold 2 IBS: 0.1735957231932253
Fold 3 IBS: 0.17865691731710068
Fold 4 IBS: 0.16381238023089173
Fold 5 IBS: 0.18276980487615635
[I 2024-04-17 14:07:48,662] Trial 76 finished with value: 0.17887896329416547 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 429, 'oob_score': True, 'max_samples': 0.9230656101538035, 'max_features': None, 'min_weight_fraction_leaf': 0.2876366361326956}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.20005556499731925
Fold 2 IBS: 0.1942827201368873
Fold 3 IBS: 0.1820463166593903
Fold 4 IBS: 0.16218714717245683
Fold 5 IBS: 0.18197713274911398
[I 2024-04-17 14:08:01,979] Trial 77 finished with value: 0.18410977634303355 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 398, 'oob_score': True, 'max_samples': 0.8345748563174094, 'max_features': None, 'min_weight_fraction_leaf': 0.22675006501053274}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.2068103765228335
Fold 2 IBS: 0.18596057744368405
Fold 3 IBS: 0.1933968711802695
Fold 4 IBS: 0.16248025766663907
Fold 5 IBS: 0.17676409570560397
[I 2024-04-17 14:08:10,993] Trial 78 finished with value: 0.18508243570380603 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 365, 'oob_score': False, 'max_samples': 0.8707184626909048, 'max_features': None, 'min_weight_fraction_leaf': 0.20642990518940413}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.21127615042427794
Fold 2 IBS: 0.18543264117706332
Fold 3 IBS: 0.17698553411146528
Fold 4 IBS: 0.17716044047793994
Fold 5 IBS: 0.18786674171180937
[I 2024-04-17 14:08:25,325] Trial 79 finished with value: 0.1877443015805112 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 464, 'oob_score': True, 'max_samples': 0.7877355588868098, 'max_features': None, 'min_weight_fraction_leaf': 0.2813492342192726}. Best is trial 66 with value: 0.17608875094401136.

Fold 1 IBS: 0.1988695369031691
Fold 2 IBS: 0.1592183696636372
Fold 3 IBS: 0.18909487165615965
Fold 4 IBS: 0.1617555101933038
Fold 5 IBS: 0.17352826725754153
[I 2024-04-17 14:08:38,613] Trial 80 finished with value: 0.17649331113476227 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.9998847588095947, 'max_features': None, 'min_weight_fraction_leaf': 0.25095162112847785}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.19645044238241818
Fold 2 IBS: 0.16241201741450556
Fold 3 IBS: 0.18710685872515703
Fold 4 IBS: 0.16169268484725988
Fold 5 IBS: 0.17397072132591115
[I 2024-04-17 14:08:53,881] Trial 81 finished with value: 0.17632654493905037 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 486, 'oob_score': False, 'max_samples': 0.9930359732247087, 'max_features': None, 'min_weight_fraction_leaf': 0.2547008743105544}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.197189519357203
Fold 2 IBS: 0.1608371384633388
Fold 3 IBS: 0.1878491621294288
Fold 4 IBS: 0.16143473593632804
Fold 5 IBS: 0.17331170969010815
[I 2024-04-17 14:09:06,083] Trial 82 finished with value: 0.17612445311528135 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 486, 'oob_score': False, 'max_samples': 0.9712179094738045, 'max_features': None, 'min_weight_fraction_leaf': 0.24985939335853485}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.19891646864315543
Fold 2 IBS: 0.15919675300396055
Fold 3 IBS: 0.1891004305442232
Fold 4 IBS: 0.16174107291604187
Fold 5 IBS: 0.17353925917013155
[I 2024-04-17 14:09:17,300] Trial 83 finished with value: 0.17649879685550254 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 482, 'oob_score': False, 'max_samples': 0.9990287360438184, 'max_features': None, 'min_weight_fraction_leaf': 0.25075466549671227}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.1972285686929121
Fold 2 IBS: 0.16081654157806777
Fold 3 IBS: 0.18785873443521617
Fold 4 IBS: 0.16141451127123055
Fold 5 IBS: 0.17332937023055142
[I 2024-04-17 14:09:29,199] Trial 84 finished with value: 0.17612954524159558 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 488, 'oob_score': False, 'max_samples': 0.9705741542652172, 'max_features': None, 'min_weight_fraction_leaf': 0.24907395461892565}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.20054722957350618
Fold 2 IBS: 0.19200515812226812
Fold 3 IBS: 0.18666968426337407
Fold 4 IBS: 0.1618915730301812
Fold 5 IBS: 0.17950335698727213
[I 2024-04-17 14:09:42,412] Trial 85 finished with value: 0.18412340039532032 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.9842582259592431, 'max_features': None, 'min_weight_fraction_leaf': 0.2448325036410401}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.1969798650015029
Fold 2 IBS: 0.16192155850626727
Fold 3 IBS: 0.18773339939955946
Fold 4 IBS: 0.16172672110661893
Fold 5 IBS: 0.17360224754914635
[I 2024-04-17 14:09:54,458] Trial 86 finished with value: 0.17639275831261897 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 488, 'oob_score': False, 'max_samples': 0.9989706742007066, 'max_features': None, 'min_weight_fraction_leaf': 0.25722244315287085}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.19806873923512658
Fold 2 IBS: 0.19874163553540372
Fold 3 IBS: 0.1801149383563415
Fold 4 IBS: 0.1621541804872036
Fold 5 IBS: 0.1839041432358545
[I 2024-04-17 14:10:06,908] Trial 87 finished with value: 0.18459672736998597 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.9656415499780244, 'max_features': None, 'min_weight_fraction_leaf': 0.27399716580289313}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.219406913977765
Fold 2 IBS: 0.20062414615647167
Fold 3 IBS: 0.19221950087772705
Fold 4 IBS: 0.19754325197766578
Fold 5 IBS: 0.2030244119357496
[I 2024-04-17 14:10:18,145] Trial 88 finished with value: 0.20256364498507579 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.9609030746789898, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3428416570898345}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.21125097521204014
Fold 2 IBS: 0.19575799767720786
Fold 3 IBS: 0.19120186417724755
Fold 4 IBS: 0.19211323694403595
Fold 5 IBS: 0.20051393821318178
[I 2024-04-17 14:10:30,037] Trial 89 finished with value: 0.19816760244474266 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.9690404458624944, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3118003486826688}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.2114330194757469
Fold 2 IBS: 0.19271648100978275
Fold 3 IBS: 0.19102135879502236
Fold 4 IBS: 0.18585261774352427
Fold 5 IBS: 0.19496887651782704
[I 2024-04-17 14:10:41,749] Trial 90 finished with value: 0.19519847070838064 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 463, 'oob_score': False, 'max_samples': 0.918311445123319, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2584960755951598}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.19574597139230826
Fold 2 IBS: 0.16357753367201014
Fold 3 IBS: 0.18629796740893412
Fold 4 IBS: 0.1613630942800501
Fold 5 IBS: 0.1750848096532262
[I 2024-04-17 14:10:52,698] Trial 91 finished with value: 0.17641387528130575 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 482, 'oob_score': False, 'max_samples': 0.9999807976849742, 'max_features': None, 'min_weight_fraction_leaf': 0.26262033713833505}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.19467097803077046
Fold 2 IBS: 0.16847792993673655
Fold 3 IBS: 0.18262762178344658
Fold 4 IBS: 0.16179371592374298
Fold 5 IBS: 0.17837783807061375
[I 2024-04-17 14:11:03,402] Trial 92 finished with value: 0.17718961674906208 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.9288461996687204, 'max_features': None, 'min_weight_fraction_leaf': 0.26236657974239985}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.20109394754424403
Fold 2 IBS: 0.1561123457610324
Fold 3 IBS: 0.19081330407459937
Fold 4 IBS: 0.162077057047143
Fold 5 IBS: 0.17115470858940157
[I 2024-04-17 14:11:14,390] Trial 93 finished with value: 0.1762502726032841 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 453, 'oob_score': False, 'max_samples': 0.9996611931075011, 'max_features': None, 'min_weight_fraction_leaf': 0.23962783953304242}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.1981243327384098
Fold 2 IBS: 0.19801462532494277
Fold 3 IBS: 0.18093161301215324
Fold 4 IBS: 0.16198967622025126
Fold 5 IBS: 0.1843165234006585
[I 2024-04-17 14:11:26,544] Trial 94 finished with value: 0.1846753541392831 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.978777496163836, 'max_features': None, 'min_weight_fraction_leaf': 0.2779109118730444}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.19513141185956973
Fold 2 IBS: 0.17299985336751447
Fold 3 IBS: 0.17918414049475095
Fold 4 IBS: 0.1636804231827974
Fold 5 IBS: 0.18295602986144133
[I 2024-04-17 14:11:39,046] Trial 95 finished with value: 0.17879037175321477 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 466, 'oob_score': False, 'max_samples': 0.9505111776893093, 'max_features': None, 'min_weight_fraction_leaf': 0.2968827704796035}. Best is trial 66 with value: 0.17608875094401136.

Fold 1 IBS: 0.21699983642473847
Fold 2 IBS: 0.1805792093648495
Fold 3 IBS: 0.19889294656533302
Fold 4 IBS: 0.16428998762771174
Fold 5 IBS: 0.1730153178538409
[I 2024-04-17 14:11:49,871] Trial 96 finished with value: 0.18675545956729472 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 455, 'oob_score': False, 'max_samples': 0.8861866003038187, 'max_features': None, 'min_weight_fraction_leaf': 0.1745416008237794}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.2003194720733052
Fold 2 IBS: 0.19331059374319456
Fold 3 IBS: 0.1850267553757519
Fold 4 IBS: 0.16128969084563635
Fold 5 IBS: 0.1810956383532238
[I 2024-04-17 14:12:02,274] Trial 97 finished with value: 0.18420843007822235 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 490, 'oob_score': False, 'max_samples': 0.9073993416752635, 'max_features': None, 'min_weight_fraction_leaf': 0.2391920086525829}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.20834798318830036
Fold 2 IBS: 0.184424223448752
Fold 3 IBS: 0.19576996727758844
Fold 4 IBS: 0.1634587750184799
Fold 5 IBS: 0.17594137571279114
[I 2024-04-17 14:12:13,101] Trial 98 finished with value: 0.18558846492918238 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.9369413743869643, 'max_features': None, 'min_weight_fraction_leaf': 0.2123600530231811}. Best is trial 66 with value: 0.17608875094401136.
Fold 1 IBS: 0.21893157439150177
Fold 2 IBS: 0.1795707940831498
Fold 3 IBS: 0.19954729191139106
Fold 4 IBS: 0.1648080231638112
Fold 5 IBS: 0.17221613259754537
[I 2024-04-17 14:12:26,047] Trial 99 finished with value: 0.18701476322947985 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 473, 'oob_score': False, 'max_samples': 0.9782939600366111, 'max_features': None, 'min_weight_fraction_leaf': 0.19188506457133597}. Best is trial 66 with value: 0.17608875094401136.


* Best trial for IBS:
 FrozenTrial(number=66, state=TrialState.COMPLETE, values=[0.17608875094401136], datetime_start=datetime.datetime(2024, 4, 17, 14, 5, 45, 477607), datetime_complete=datetime.datetime(2024, 4, 17, 14, 5, 55, 715233), params={'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 379, 'oob_score': True, 'max_samples': 0.7505526916491491, 'max_features': None, 'min_weight_fraction_leaf': 0.1907905531669951}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=66, value=None)


* Best Score for IBS:
 0.17608875094401136

In [52]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [53]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.87
train_ibs:  0.176

#### Test

In [54]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [55]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=14, max_leaf_nodes=20,
                     max_samples=0.8265187125779403, min_samples_leaf=2,
                     min_samples_split=3,
                     min_weight_fraction_leaf=0.012312929606053803,
                     n_estimators=195, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.557

RandomSurvivalForest(max_depth=1, max_features=None, max_leaf_nodes=2,
                     max_samples=0.7505526916491491, min_samples_leaf=10,
                     min_samples_split=7,
                     min_weight_fraction_leaf=0.1907905531669951,
                     n_estimators=379, oob_score=True, random_state=123)

test_ibs:  0.23

In [56]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [57]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [58]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 14:12:29,593] A new study created in memory with name: no-name-dfcab69a-dd09-4fe7-9c46-363c0fb1cad9

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5367965367965368
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 14:12:32,412] Trial 0 finished with value: 0.67885353707116 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.67885353707116.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:12:37,628] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.67885353707116.
Fold 1 C-index: 0.5411255411255411
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.5735294117647058
Fold 4 C-index: 0.6434599156118144
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 14:12:47,950] Trial 2 finished with value: 0.6287063070337455 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.67885353707116.
Fold 1 C-index: 0.48484848484848486
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6729957805907173
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 14:12:48,900] Trial 3 finished with value: 0.6555534469253754 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.67885353707116.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:12:52,556] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.67885353707116.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:12:56,970] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.67885353707116.
Fold 1 C-index: 0.5367965367965368
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 14:12:59,485] Trial 6 finished with value: 0.6775877142863499 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.67885353707116.
Fold 1 C-index: 0.5454545454545454
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.5882352941176471
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 14:13:05,120] Trial 7 finished with value: 0.6339635471281173 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.67885353707116.
Fold 1 C-index: 0.3787878787878788
Fold 2 C-index: 0.7254464285714286
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.647887323943662
[I 2024-04-17 14:13:05,491] Trial 8 finished with value: 0.619461308141954 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.67885353707116.
Fold 1 C-index: 0.44372294372294374
Fold 2 C-index: 0.7433035714285714
Fold 3 C-index: 0.5269607843137255
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.5985915492957746
[I 2024-04-17 14:13:16,727] Trial 9 finished with value: 0.6004904532965069 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.67885353707116.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:13:21,776] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.67885353707116.
Fold 1 C-index: 0.5281385281385281
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 14:13:24,172] Trial 11 finished with value: 0.6611227196432958 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.67885353707116.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:13:27,154] Trial 12 finished with value: 0.6897845011357434 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.6897845011357434.
Fold 1 C-index: 0.5454545454545454
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 14:13:30,452] Trial 13 finished with value: 0.6651197290696047 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.6897845011357434.
Fold 1 C-index: 0.5411255411255411
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.6384976525821596
[I 2024-04-17 14:13:32,974] Trial 14 finished with value: 0.6600913940512589 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.6897845011357434.
Fold 1 C-index: 0.5281385281385281
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.6029411764705882

Fold 4 C-index: 0.6729957805907173
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 14:13:34,649] Trial 15 finished with value: 0.6503984303733 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.6897845011357434.
Fold 1 C-index: 0.4675324675324675
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.6642156862745098
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6267605633802817
[I 2024-04-17 14:13:37,565] Trial 16 finished with value: 0.6363743624850707 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.6897845011357434.
Fold 1 C-index: 0.5411255411255411
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.6291079812206573
[I 2024-04-17 14:13:39,348] Trial 17 finished with value: 0.6651885599456074 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.6897845011357434.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:13:42,441] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.6897845011357434.
Fold 1 C-index: 0.5497835497835498
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6525821596244131
[I 2024-04-17 14:13:44,836] Trial 19 finished with value: 0.6648253827779511 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.6897845011357434.
Fold 1 C-index: 0.3333333333333333
Fold 2 C-index: 0.6986607142857143
Fold 3 C-index: 0.5024509803921569
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.5446009389671361
[I 2024-04-17 14:13:45,162] Trial 20 finished with value: 0.5537838769399719 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.6897845011357434.
Fold 1 C-index: 0.5281385281385281
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 14:13:47,551] Trial 21 finished with value: 0.6779197072028053 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.6897845011357434.
Fold 1 C-index: 0.5324675324675324
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 14:13:49,931] Trial 22 finished with value: 0.6791507486558376 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.6897845011357434.
Fold 1 C-index: 0.5411255411255411
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7276995305164319
[I 2024-04-17 14:13:52,357] Trial 23 finished with value: 0.7034082260434603 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.7034082260434603.
Fold 1 C-index: 0.5411255411255411
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 14:13:54,912] Trial 24 finished with value: 0.6759832548961496 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.7034082260434603.
Fold 1 C-index: 0.5411255411255411
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 14:13:57,235] Trial 25 finished with value: 0.6876500102058685 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.7034082260434603.
Fold 1 C-index: 0.5281385281385281
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.5833333333333334
Fold 4 C-index: 0.6518987341772152
Fold 5 C-index: 0.6525821596244131
[I 2024-04-17 14:14:10,002] Trial 26 finished with value: 0.6322976939118408 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 497, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7226268366017338, 'min_weight_fraction_leaf': 0.14724522382749441}. Best is trial 23 with value: 0.7034082260434603.
Fold 1 C-index: 0.5411255411255411
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 14:14:12,635] Trial 27 finished with value: 0.6613637214882063 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.0910755188453143}. Best is trial 23 with value: 0.7034082260434603.
Fold 1 C-index: 0.5064935064935064
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.6772151898734177
Fold 5 C-index: 0.6173708920187794
[I 2024-04-17 14:14:15,130] Trial 28 finished with value: 0.6465079344838635 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 465, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9159590537617217, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.7034082260434603.
Fold 1 C-index: 0.5411255411255411
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 14:14:17,295] Trial 29 finished with value: 0.6757883993643488 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 352, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8201511224658254, 'min_weight_fraction_leaf': 0.10380226349432521}. Best is trial 23 with value: 0.7034082260434603.

Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 14:14:19,146] Trial 30 finished with value: 0.7271348075932751 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 278, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.05879574792157449}. Best is trial 30 with value: 0.7271348075932751.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 14:14:20,951] Trial 31 finished with value: 0.7200396968216938 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 281, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6298966865274057, 'min_weight_fraction_leaf': 0.05405927482118079}. Best is trial 30 with value: 0.7271348075932751.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 14:14:22,662] Trial 32 finished with value: 0.7225524296981147 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.722056772295139, 'min_weight_fraction_leaf': 0.06665303212999554}. Best is trial 30 with value: 0.7271348075932751.
Fold 1 C-index: 0.5541125541125541
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 14:14:24,314] Trial 33 finished with value: 0.6789722225702871 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 295, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7504103077643619, 'min_weight_fraction_leaf': 0.07228058521385833}. Best is trial 30 with value: 0.7271348075932751.
Fold 1 C-index: 0.5497835497835498
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 14:14:25,720] Trial 34 finished with value: 0.6854600433100192 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 218, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.699719011795045, 'min_weight_fraction_leaf': 0.1126902739511941}. Best is trial 30 with value: 0.7271348075932751.
Fold 1 C-index: 0.5454545454545454
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.647887323943662
[I 2024-04-17 14:14:29,036] Trial 35 finished with value: 0.6737422135420887 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 282, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6215694472638225, 'min_weight_fraction_leaf': 0.16733609036803293}. Best is trial 30 with value: 0.7271348075932751.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.620253164556962
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 14:14:34,793] Trial 36 finished with value: 0.6780093226613001 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 211, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5190557919565845, 'min_weight_fraction_leaf': 0.05223373774757657}. Best is trial 30 with value: 0.7271348075932751.
Fold 1 C-index: 0.5324675324675324
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.6740196078431373
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.6455399061032864
[I 2024-04-17 14:14:36,142] Trial 37 finished with value: 0.6681525461122064 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 20, 'max_depth': 9, 'n_estimators': 168, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8268387836003009, 'min_weight_fraction_leaf': 0.12103866621890363}. Best is trial 30 with value: 0.7271348075932751.
Fold 1 C-index: 0.4935064935064935
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.6314553990610329
[I 2024-04-17 14:14:37,810] Trial 38 finished with value: 0.6504635163357227 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 231, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6034576762401722, 'min_weight_fraction_leaf': 0.22096529439752421}. Best is trial 30 with value: 0.7271348075932751.
Fold 1 C-index: 0.5324675324675324
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.5784313725490197
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 14:14:43,122] Trial 39 finished with value: 0.6344743819422776 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 184, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5204645655829614, 'min_weight_fraction_leaf': 0.07994626083099707}. Best is trial 30 with value: 0.7271348075932751.
Fold 1 C-index: 0.5086580086580087
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6476793248945147
Fold 5 C-index: 0.6455399061032864
[I 2024-04-17 14:14:43,979] Trial 40 finished with value: 0.6501338512925066 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 128, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7462583966462045, 'min_weight_fraction_leaf': 0.027601004831219272}. Best is trial 30 with value: 0.7271348075932751.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 14:14:45,711] Trial 41 finished with value: 0.728922062066208 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6676760673731118, 'min_weight_fraction_leaf': 0.0019860067692131778}. Best is trial 41 with value: 0.728922062066208.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 14:14:47,666] Trial 42 finished with value: 0.7436927877765476 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6725672668712916, 'min_weight_fraction_leaf': 0.06134016294643}. Best is trial 42 with value: 0.7436927877765476.
Fold 1 C-index: 0.47186147186147187
Fold 2 C-index: 0.8236607142857143
Fold 3 C-index: 0.6348039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6220657276995305
[I 2024-04-17 14:14:49,896] Trial 43 finished with value: 0.6471872278425626 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 292, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6659953080114266, 'min_weight_fraction_leaf': 0.27764552944355786}. Best is trial 42 with value: 0.7436927877765476.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7370892018779343
[I 2024-04-17 14:14:51,801] Trial 44 finished with value: 0.7086848356662232 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 235, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5606440507914384, 'min_weight_fraction_leaf': 0.06554582209581696}. Best is trial 42 with value: 0.7436927877765476.

Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.9014084507042254
[I 2024-04-17 14:14:53,703] Trial 45 finished with value: 0.7970134288662547 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7853496457812107, 'min_weight_fraction_leaf': 0.015745612245557046}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.8544600938967136
[I 2024-04-17 14:14:55,977] Trial 46 finished with value: 0.7557433442347262 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 338, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7702604596394105, 'min_weight_fraction_leaf': 0.02501102546800585}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.620253164556962
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 14:15:03,950] Trial 47 finished with value: 0.6732047599911616 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 324, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8009854768869007, 'min_weight_fraction_leaf': 0.025373757162150387}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 14:15:07,943] Trial 48 finished with value: 0.720574863642924 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 349, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8411222155096425, 'min_weight_fraction_leaf': 0.017066098728681686}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:15:09,446] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7862703089830011, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5454545454545454
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 14:15:11,228] Trial 50 finished with value: 0.6676560596118056 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 340, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9256153933677993, 'min_weight_fraction_leaf': 0.09137439262228633}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 14:15:13,576] Trial 51 finished with value: 0.736251631157009 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 305, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7596824539947467, 'min_weight_fraction_leaf': 0.000670113766949549}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 14:15:15,425] Trial 52 finished with value: 0.7354077493004689 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 307, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7565523755943866, 'min_weight_fraction_leaf': 0.001209423245957089}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7934272300469484
[I 2024-04-17 14:15:17,421] Trial 53 finished with value: 0.7398933607057632 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 310, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7756976482706517, 'min_weight_fraction_leaf': 0.0027520837779243523}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 14:15:18,974] Trial 54 finished with value: 0.7188139336594943 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 311, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8566678440227903, 'min_weight_fraction_leaf': 0.01791863650884245}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5454545454545454
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 14:15:21,538] Trial 55 finished with value: 0.6929498613899604 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 367, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7725323189107755, 'min_weight_fraction_leaf': 0.019452268966692284}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5411255411255411
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 14:15:23,496] Trial 56 finished with value: 0.6992813863255801 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 310, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7688395360539757, 'min_weight_fraction_leaf': 0.005571180329296155}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5281385281385281
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 14:15:25,014] Trial 57 finished with value: 0.6782510730349289 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 246, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9448775455684517, 'min_weight_fraction_leaf': 0.036857426127981874}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 14:15:27,398] Trial 58 finished with value: 0.7159826635073875 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 332, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.807128845169363, 'min_weight_fraction_leaf': 0.023090942429416207}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.45021645021645024
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.5392156862745098
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.6455399061032864
[I 2024-04-17 14:15:34,732] Trial 59 finished with value: 0.5918037816351844 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 268, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8650646337642922, 'min_weight_fraction_leaf': 0.3787205021140745}. Best is trial 45 with value: 0.7970134288662547.

Fold 1 C-index: 0.5454545454545454
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 14:15:37,282] Trial 60 finished with value: 0.6862866911298792 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 389, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6818880964224125, 'min_weight_fraction_leaf': 0.0018347061200580522}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 14:15:39,819] Trial 61 finished with value: 0.7217976230427988 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 305, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6554294995128163, 'min_weight_fraction_leaf': 0.0014805441558574176}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 14:15:41,687] Trial 62 finished with value: 0.7261813306904311 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 331, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7068945551972836, 'min_weight_fraction_leaf': 0.0471966257969742}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.8450704225352113
[I 2024-04-17 14:15:43,376] Trial 63 finished with value: 0.7554824204029655 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 246, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7529500816371295, 'min_weight_fraction_leaf': 0.02910429255325864}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 14:15:45,232] Trial 64 finished with value: 0.710734974673511 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 267, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7463963494099692, 'min_weight_fraction_leaf': 0.08777543884999463}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5324675324675324
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 14:15:46,894] Trial 65 finished with value: 0.6734077713080078 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 242, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8394430489620498, 'min_weight_fraction_leaf': 0.03076971959361917}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:15:48,423] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 198, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7915007773377514, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5541125541125541
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 14:15:50,670] Trial 67 finished with value: 0.7069049904358573 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 362, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7607620684769181, 'min_weight_fraction_leaf': 0.04953971688069396}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.8262910798122066
[I 2024-04-17 14:15:52,732] Trial 68 finished with value: 0.7520536850131225 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 302, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9040757011419633, 'min_weight_fraction_leaf': 0.03826836458325407}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5497835497835498
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 14:15:54,215] Trial 69 finished with value: 0.6746296195912359 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 256, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8913688790986706, 'min_weight_fraction_leaf': 0.13685126813510495}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 14:15:55,775] Trial 70 finished with value: 0.7381301587475619 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 225, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9599749661171925, 'min_weight_fraction_leaf': 0.07414948735188238}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5497835497835498
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 14:15:57,138] Trial 71 finished with value: 0.6807331525537167 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 213, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9624371907306613, 'min_weight_fraction_leaf': 0.07579885780751126}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 14:15:58,510] Trial 72 finished with value: 0.7260623339191266 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 226, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.90619488796257, 'min_weight_fraction_leaf': 0.04090874965478827}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 14:16:00,630] Trial 73 finished with value: 0.723635909695407 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 272, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9986589602152622, 'min_weight_fraction_leaf': 0.09945017391346132}. Best is trial 45 with value: 0.7970134288662547.
Fold 1 C-index: 0.5324675324675324
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6983122362869199
Fold 5 C-index: 0.6431924882629108
[I 2024-04-17 14:16:02,783] Trial 74 finished with value: 0.6690171404791029 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 4, 'n_estimators': 346, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8599309261230235, 'min_weight_fraction_leaf': 0.06418871784580109}. Best is trial 45 with value: 0.7970134288662547.

Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.892018779342723
[I 2024-04-17 14:16:04,735] Trial 75 finished with value: 0.8066418664177124 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 322, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.939348623311968, 'min_weight_fraction_leaf': 0.013770059968835775}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6244725738396625
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 14:16:11,819] Trial 76 finished with value: 0.6843712728207054 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 251, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9549609248901629, 'min_weight_fraction_leaf': 0.05530759600321531}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.8262910798122066
[I 2024-04-17 14:16:13,841] Trial 77 finished with value: 0.7511827468795261 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 325, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9456485642471004, 'min_weight_fraction_leaf': 0.017776168429430098}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 14:16:16,146] Trial 78 finished with value: 0.7022576241877811 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 396, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9138554243369036, 'min_weight_fraction_leaf': 0.017870831315026477}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 14:16:18,034] Trial 79 finished with value: 0.7196773215274862 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 322, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.2170140247726947, 'min_weight_fraction_leaf': 0.034912430485325455}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 14:16:20,400] Trial 80 finished with value: 0.7252043971448446 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 375, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9370484740281054, 'min_weight_fraction_leaf': 0.016487708088064205}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8732394366197183
[I 2024-04-17 14:16:22,233] Trial 81 finished with value: 0.7753936977309603 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 298, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9710027965398979, 'min_weight_fraction_leaf': 0.04627785510237033}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.8450704225352113
[I 2024-04-17 14:16:24,061] Trial 82 finished with value: 0.7575307397306966 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8855193457389139, 'min_weight_fraction_leaf': 0.0460980308037279}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.8356807511737089
[I 2024-04-17 14:16:26,113] Trial 83 finished with value: 0.7556528054583962 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 292, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8844309504688548, 'min_weight_fraction_leaf': 0.046387872204142526}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 14:16:28,165] Trial 84 finished with value: 0.7772716320032608 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8792707950506881, 'min_weight_fraction_leaf': 0.04488356654168772}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.863849765258216
[I 2024-04-17 14:16:31,101] Trial 85 finished with value: 0.7708695265979777 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 359, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8836822536355798, 'min_weight_fraction_leaf': 0.0480309932879798}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5324675324675324
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 14:16:33,499] Trial 86 finished with value: 0.6622568561371615 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 359, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8811783338875734, 'min_weight_fraction_leaf': 0.1118738038959745}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 14:16:36,260] Trial 87 finished with value: 0.7362250271751677 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 337, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9760642709624288, 'min_weight_fraction_leaf': 0.08377856147430485}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6244725738396625
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 14:16:43,611] Trial 88 finished with value: 0.6814748389590686 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 279, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8230704559905697, 'min_weight_fraction_leaf': 0.05126819815172205}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.8967136150234741
[I 2024-04-17 14:16:45,988] Trial 89 finished with value: 0.7857885838576666 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 353, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8752846245116854, 'min_weight_fraction_leaf': 0.032016255982835515}. Best is trial 75 with value: 0.8066418664177124.

Fold 1 C-index: 0.45021645021645024
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.6740196078431373
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.636150234741784
[I 2024-04-17 14:16:48,362] Trial 90 finished with value: 0.6390799710376702 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 401, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8849026790155812, 'min_weight_fraction_leaf': 0.3366829694821827}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8873239436619719
[I 2024-04-17 14:16:50,576] Trial 91 finished with value: 0.7894220313532633 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 348, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8500000644098663, 'min_weight_fraction_leaf': 0.03053235325014577}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.8497652582159625
[I 2024-04-17 14:16:52,565] Trial 92 finished with value: 0.7585135448853686 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8476334634737903, 'min_weight_fraction_leaf': 0.046622022494450605}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.8028169014084507
[I 2024-04-17 14:16:54,552] Trial 93 finished with value: 0.7445927428897944 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8455750731942565, 'min_weight_fraction_leaf': 0.06524519728888992}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5411255411255411
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 14:16:56,552] Trial 94 finished with value: 0.695922813443762 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 378, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9225576370707903, 'min_weight_fraction_leaf': 0.029245754796617354}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.892018779342723
[I 2024-04-17 14:16:58,654] Trial 95 finished with value: 0.7858841214324916 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 342, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8110671670500872, 'min_weight_fraction_leaf': 0.013728828472087104}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.8215962441314554
[I 2024-04-17 14:17:02,048] Trial 96 finished with value: 0.7529557736318405 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 414, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8133087048241824, 'min_weight_fraction_leaf': 0.05640226202871867}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.8075117370892019
[I 2024-04-17 14:17:04,707] Trial 97 finished with value: 0.7446107087140275 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 349, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.836177804274538, 'min_weight_fraction_leaf': 0.011425066446188471}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 14:17:07,233] Trial 98 finished with value: 0.7234676581454476 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 367, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.859666686519719, 'min_weight_fraction_leaf': 0.09637215666794255}. Best is trial 75 with value: 0.8066418664177124.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8284313725490197

[I 2024-04-17 14:17:09,374] A new study created in memory with name: no-name-dae3f542-b310-4e3c-bf36-04314acc8136

Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.9014084507042254
[I 2024-04-17 14:17:09,365] Trial 99 finished with value: 0.794253829629552 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 388, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9951192293719923, 'min_weight_fraction_leaf': 0.03842087910487978}. Best is trial 75 with value: 0.8066418664177124.


* Best trial for C-index:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.8066418664177124], datetime_start=datetime.datetime(2024, 4, 17, 14, 16, 2, 796523), datetime_complete=datetime.datetime(2024, 4, 17, 14, 16, 4, 734667), params={'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 322, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.939348623311968, 'min_weight_fraction_leaf': 0.013770059968835775}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=75, value=None)


* Best Score for C-index:
 0.8066418664177124

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21248119233358653
Fold 2 IBS: 0.21038743152294045
Fold 3 IBS: 0.19836936358391483
Fold 4 IBS: 0.2121453324625378
Fold 5 IBS: 0.20766684608827324
[I 2024-04-17 14:17:16,678] Trial 0 finished with value: 0.2082100331982506 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.2082100331982506.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-17 14:17:27,732] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.2082100331982506.
Fold 1 IBS: 0.21358423069385488
Fold 2 IBS: 0.2171368704546139
Fold 3 IBS: 0.20244114686594236
Fold 4 IBS: 0.22099003026502276
Fold 5 IBS: 0.2149454390590579
[I 2024-04-17 14:17:37,186] Trial 2 finished with value: 0.21381954346769833 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.2082100331982506.
Fold 1 IBS: 0.2158815847420206
Fold 2 IBS: 0.2183995799412274
Fold 3 IBS: 0.20289347863184387
Fold 4 IBS: 0.22141189466262293
Fold 5 IBS: 0.2154593629129115
[I 2024-04-17 14:17:40,315] Trial 3 finished with value: 0.21480918017812525 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.2082100331982506.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-17 14:17:48,512] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.2082100331982506.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-17 14:17:53,036] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.2082100331982506.
Fold 1 IBS: 0.21270521063149314
Fold 2 IBS: 0.20916104165586866
Fold 3 IBS: 0.19822618334010167
Fold 4 IBS: 0.21108620481871532
Fold 5 IBS: 0.20795064843047556
[I 2024-04-17 14:18:01,337] Trial 6 finished with value: 0.20782585777533086 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.20782585777533086.
Fold 1 IBS: 0.21314868217795427
Fold 2 IBS: 0.21504653371331275
Fold 3 IBS: 0.20131090179810066
Fold 4 IBS: 0.21884873864323393
Fold 5 IBS: 0.21287701855711352
[I 2024-04-17 14:18:05,966] Trial 7 finished with value: 0.21224637497794302 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.20782585777533086.
Fold 1 IBS: 0.21749637805339772
Fold 2 IBS: 0.21874289684418877
Fold 3 IBS: 0.20360468559183004
Fold 4 IBS: 0.22044978021753558
Fold 5 IBS: 0.21626581381130522
[I 2024-04-17 14:18:06,903] Trial 8 finished with value: 0.21531191090365148 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.20782585777533086.
Fold 1 IBS: 0.2144810892981476
Fold 2 IBS: 0.2202392769761441
Fold 3 IBS: 0.20442280099784663
Fold 4 IBS: 0.22360434778905447
Fold 5 IBS: 0.21781511014485863
[I 2024-04-17 14:18:16,991] Trial 9 finished with value: 0.21611252504121028 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.20782585777533086.
Fold 1 IBS: 0.21397612241164576
Fold 2 IBS: 0.2207394210478338
Fold 3 IBS: 0.20537940251283027
Fold 4 IBS: 0.22474853253260105
Fold 5 IBS: 0.2174222289467434
[I 2024-04-17 14:18:25,406] Trial 10 finished with value: 0.21645314149033087 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.20782585777533086.
Fold 1 IBS: 0.2145914513723979
Fold 2 IBS: 0.22099926084538404
Fold 3 IBS: 0.20506955856764672
Fold 4 IBS: 0.22361737691445446
Fold 5 IBS: 0.21759444095282165
[I 2024-04-17 14:18:32,935] Trial 11 finished with value: 0.21637441773054097 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.20782585777533086.
Fold 1 IBS: 0.21156101952879808
Fold 2 IBS: 0.20699115547663727
Fold 3 IBS: 0.19537265513429608
Fold 4 IBS: 0.20870922118323088
Fold 5 IBS: 0.2038227083902476
[I 2024-04-17 14:18:42,358] Trial 12 finished with value: 0.20529135194264198 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.20529135194264198.
Fold 1 IBS: 0.2114084084143655
Fold 2 IBS: 0.21406871624250745
Fold 3 IBS: 0.20034672638645803
Fold 4 IBS: 0.21681061839443988
Fold 5 IBS: 0.21215988721811266
[I 2024-04-17 14:18:50,995] Trial 13 finished with value: 0.2109588713311767 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638831587887255, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 12 with value: 0.20529135194264198.
Fold 1 IBS: 0.2139646814364898
Fold 2 IBS: 0.22074056096749928
Fold 3 IBS: 0.20501656315227804
Fold 4 IBS: 0.22494601314735585
Fold 5 IBS: 0.21705148409657263
[I 2024-04-17 14:18:58,405] Trial 14 finished with value: 0.21634386056003913 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 12 with value: 0.20529135194264198.

Fold 1 IBS: 0.21400643269593325
Fold 2 IBS: 0.22111219981278188
Fold 3 IBS: 0.20502803908063474
Fold 4 IBS: 0.22484462106669664
Fold 5 IBS: 0.21822466700224044
[I 2024-04-17 14:19:03,157] Trial 15 finished with value: 0.21664319193165743 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 268, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.33571048327918607, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 12 with value: 0.20529135194264198.
Fold 1 IBS: 0.2138464900898722
Fold 2 IBS: 0.21809048025098424
Fold 3 IBS: 0.2025170680698759
Fold 4 IBS: 0.2200889428680337
Fold 5 IBS: 0.21567933932122524
[I 2024-04-17 14:19:12,025] Trial 16 finished with value: 0.21404446411999825 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6535355702555379, 'min_weight_fraction_leaf': 0.1906011147608997}. Best is trial 12 with value: 0.20529135194264198.
Fold 1 IBS: 0.21643310338217073
Fold 2 IBS: 0.21832124884123452
Fold 3 IBS: 0.2016125854612668
Fold 4 IBS: 0.22008390468826433
Fold 5 IBS: 0.21572923648551015
[I 2024-04-17 14:19:19,772] Trial 17 finished with value: 0.2144360157716893 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.903993543626621, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 12 with value: 0.20529135194264198.
Fold 1 IBS: 0.21780562607455248
Fold 2 IBS: 0.21385345986985954
Fold 3 IBS: 0.20470914324123285
Fold 4 IBS: 0.2212317325016444
Fold 5 IBS: 0.21873216749873234
[I 2024-04-17 14:19:21,088] Trial 18 finished with value: 0.21526642583720434 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.38500398118655316, 'min_weight_fraction_leaf': 0.0735015574561402}. Best is trial 12 with value: 0.20529135194264198.
Fold 1 IBS: 0.21335593925062546
Fold 2 IBS: 0.20722258810994426
Fold 3 IBS: 0.19753069096281653
Fold 4 IBS: 0.2121515869109296
Fold 5 IBS: 0.204726484772429
[I 2024-04-17 14:19:24,026] Trial 19 finished with value: 0.206997458001349 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.639253673774636, 'min_weight_fraction_leaf': 0.037408326362835864}. Best is trial 12 with value: 0.20529135194264198.
Fold 1 IBS: 0.21447172690027855
Fold 2 IBS: 0.21684370275289988
Fold 3 IBS: 0.2029416644088936
Fold 4 IBS: 0.21993826223435464
Fold 5 IBS: 0.21466392564478698
[I 2024-04-17 14:19:26,502] Trial 20 finished with value: 0.21377185638824275 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 107, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.870001537215989, 'min_weight_fraction_leaf': 0.18720118160246144}. Best is trial 12 with value: 0.20529135194264198.
Fold 1 IBS: 0.21537054802074476
Fold 2 IBS: 0.21313770141976873
Fold 3 IBS: 0.20079655830012413
Fold 4 IBS: 0.217827370399139
Fold 5 IBS: 0.21181397873274432
[I 2024-04-17 14:19:29,089] Trial 21 finished with value: 0.21178923137450417 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 1, 'n_estimators': 112, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6547034385443382, 'min_weight_fraction_leaf': 0.022958663817377156}. Best is trial 12 with value: 0.20529135194264198.
Fold 1 IBS: 0.21456652066311602
Fold 2 IBS: 0.21246124312082745
Fold 3 IBS: 0.19886673192068516
Fold 4 IBS: 0.21256756661890872
Fold 5 IBS: 0.20843068814380536
[I 2024-04-17 14:19:33,474] Trial 22 finished with value: 0.20937855009346854 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 201, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5833816310769062, 'min_weight_fraction_leaf': 0.08761267626836403}. Best is trial 12 with value: 0.20529135194264198.
Fold 1 IBS: 0.21105964405756275
Fold 2 IBS: 0.2057317276958647
Fold 3 IBS: 0.19689611465276838
Fold 4 IBS: 0.20984422570677488
Fold 5 IBS: 0.20512732845751036
[I 2024-04-17 14:19:39,632] Trial 23 finished with value: 0.2057318081140962 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.693714188909504, 'min_weight_fraction_leaf': 0.04814654754133644}. Best is trial 12 with value: 0.20529135194264198.
Fold 1 IBS: 0.21195015168487022
Fold 2 IBS: 0.2119234536093663
Fold 3 IBS: 0.19847769173529137
Fold 4 IBS: 0.21274514988826962
Fold 5 IBS: 0.2089886913961379
[I 2024-04-17 14:19:45,434] Trial 24 finished with value: 0.20881702766278706 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 305, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7182027160168346, 'min_weight_fraction_leaf': 0.11241212838535851}. Best is trial 12 with value: 0.20529135194264198.
Fold 1 IBS: 0.21349689344423325
Fold 2 IBS: 0.2162120556377347
Fold 3 IBS: 0.20136792584923635
Fold 4 IBS: 0.21882848595335036
Fold 5 IBS: 0.2112037229515142
[I 2024-04-17 14:19:49,373] Trial 25 finished with value: 0.21222181676721377 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 192, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8660190406659193, 'min_weight_fraction_leaf': 0.052542863913365906}. Best is trial 12 with value: 0.20529135194264198.
Fold 1 IBS: 0.21224802813948693
Fold 2 IBS: 0.2050946133513614
Fold 3 IBS: 0.19573995462676186
Fold 4 IBS: 0.20879824946163916
Fold 5 IBS: 0.19939523023669037
[I 2024-04-17 14:19:52,081] Trial 26 finished with value: 0.20425521516318793 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 90, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6854834832485976, 'min_weight_fraction_leaf': 0.047587407578096305}. Best is trial 26 with value: 0.20425521516318793.
Fold 1 IBS: 0.21397802626412638
Fold 2 IBS: 0.21987836593324728
Fold 3 IBS: 0.20356949883468797
Fold 4 IBS: 0.22763857782762026
Fold 5 IBS: 0.21155883506935327
[I 2024-04-17 14:19:52,581] Trial 27 finished with value: 0.21532466078580703 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 1, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7212015096110397, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 26 with value: 0.20425521516318793.
Fold 1 IBS: 0.2108723675124373
Fold 2 IBS: 0.2090675378652074
Fold 3 IBS: 0.19770303110415205
Fold 4 IBS: 0.21091262079440584
Fold 5 IBS: 0.20680733022547865
[I 2024-04-17 14:20:01,638] Trial 28 finished with value: 0.20707257750033628 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 311, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9083034221162584, 'min_weight_fraction_leaf': 0.09921236864939234}. Best is trial 26 with value: 0.20425521516318793.
Fold 1 IBS: 0.21401699892351544
Fold 2 IBS: 0.2083284426349582
Fold 3 IBS: 0.1959720585436569
Fold 4 IBS: 0.21150545724713277
Fold 5 IBS: 0.2062900310796903
[I 2024-04-17 14:20:06,896] Trial 29 finished with value: 0.20722259768579074 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 152, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8243229528598196, 'min_weight_fraction_leaf': 0.07380010921145075}. Best is trial 26 with value: 0.20425521516318793.

Fold 1 IBS: 0.21665779732794135
Fold 2 IBS: 0.21751925717564152
Fold 3 IBS: 0.20412907220401041
Fold 4 IBS: 0.22210633190682874
Fold 5 IBS: 0.2174194451267344
[I 2024-04-17 14:20:08,995] Trial 30 finished with value: 0.21556638074823126 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 70, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7243285885837822, 'min_weight_fraction_leaf': 0.23757381247487194}. Best is trial 26 with value: 0.20425521516318793.
Fold 1 IBS: 0.2122445676054173
Fold 2 IBS: 0.20252464884312424
Fold 3 IBS: 0.19700770961640962
Fold 4 IBS: 0.21086302691479805
Fold 5 IBS: 0.2027758259164211
[I 2024-04-17 14:20:11,284] Trial 31 finished with value: 0.20508315577923408 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 104, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5027680639009462, 'min_weight_fraction_leaf': 0.033491153572433416}. Best is trial 26 with value: 0.20425521516318793.
Fold 1 IBS: 0.21458159025116183
Fold 2 IBS: 0.18618628658490788
Fold 3 IBS: 0.18410473535666472
Fold 4 IBS: 0.18167897454218124
Fold 5 IBS: 0.1877716894201685
[I 2024-04-17 14:20:13,477] Trial 32 finished with value: 0.19086465523101687 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 77, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4912593914756933, 'min_weight_fraction_leaf': 0.049709108014099376}. Best is trial 32 with value: 0.19086465523101687.
Fold 1 IBS: 0.20988318137607284
Fold 2 IBS: 0.19480030559189146
Fold 3 IBS: 0.19293632214054066
Fold 4 IBS: 0.19963537034068066
Fold 5 IBS: 0.19638737706451784
[I 2024-04-17 14:20:15,592] Trial 33 finished with value: 0.1987285113027407 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 77, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4931327579020774, 'min_weight_fraction_leaf': 0.08249498380174695}. Best is trial 32 with value: 0.19086465523101687.
Fold 1 IBS: 0.213198818950961
Fold 2 IBS: 0.20801376955380324
Fold 3 IBS: 0.19717120093513008
Fold 4 IBS: 0.2106815432523966
Fold 5 IBS: 0.20517594816724247
[I 2024-04-17 14:20:17,184] Trial 34 finished with value: 0.20684825617190666 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 56, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.47714851450031615, 'min_weight_fraction_leaf': 0.12235127154965937}. Best is trial 32 with value: 0.19086465523101687.
Fold 1 IBS: 0.21195546195161735
Fold 2 IBS: 0.1982876851475981
Fold 3 IBS: 0.19369197508910804
Fold 4 IBS: 0.2002290415858739
Fold 5 IBS: 0.20324265832692906
[I 2024-04-17 14:20:19,416] Trial 35 finished with value: 0.2014813644202253 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 78, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.40775507666228156, 'min_weight_fraction_leaf': 0.08067516272261369}. Best is trial 32 with value: 0.19086465523101687.
Fold 1 IBS: 0.21394499397566413
Fold 2 IBS: 0.1980231575262069
Fold 3 IBS: 0.19103766936701025
Fold 4 IBS: 0.20333394839110547
Fold 5 IBS: 0.20180332403784956
[I 2024-04-17 14:20:23,168] Trial 36 finished with value: 0.20162861865956727 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 150, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4333586034409188, 'min_weight_fraction_leaf': 0.08749997472034485}. Best is trial 32 with value: 0.19086465523101687.
Fold 1 IBS: 0.21379124356323242
Fold 2 IBS: 0.19961073567492635
Fold 3 IBS: 0.19233325043309252
Fold 4 IBS: 0.2070357548750355
Fold 5 IBS: 0.20235604079158176
[I 2024-04-17 14:20:27,065] Trial 37 finished with value: 0.20302540506757366 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 156, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.41776721388108495, 'min_weight_fraction_leaf': 0.09527517651100648}. Best is trial 32 with value: 0.19086465523101687.
Fold 1 IBS: 0.21398577893503162
Fold 2 IBS: 0.22064095047357135
Fold 3 IBS: 0.20491398942840974
Fold 4 IBS: 0.22460319006915389
Fold 5 IBS: 0.2182534716040152
[I 2024-04-17 14:20:31,549] Trial 38 finished with value: 0.21647947610203638 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 139, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.2557072729470229, 'min_weight_fraction_leaf': 0.1659883805019821}. Best is trial 32 with value: 0.19086465523101687.
Fold 1 IBS: 0.21798320896704232
Fold 2 IBS: 0.22039306962169963
Fold 3 IBS: 0.20211667151590265
Fold 4 IBS: 0.22270453608057889
Fold 5 IBS: 0.21792303696265794
[I 2024-04-17 14:20:32,899] Trial 39 finished with value: 0.21622410462957625 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 32, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5306614406047745, 'min_weight_fraction_leaf': 0.13298431324999377}. Best is trial 32 with value: 0.19086465523101687.
Fold 1 IBS: 0.21395752476932736
Fold 2 IBS: 0.22119595621504493
Fold 3 IBS: 0.2045128123279183
Fold 4 IBS: 0.22467760675287063
Fold 5 IBS: 0.21858568555966454
[I 2024-04-17 14:20:35,070] Trial 40 finished with value: 0.21658591712496517 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 68, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.41941074995931904, 'min_weight_fraction_leaf': 0.29836509500876923}. Best is trial 32 with value: 0.19086465523101687.
Fold 1 IBS: 0.21355763011220788
Fold 2 IBS: 0.19988572647090427
Fold 3 IBS: 0.19140056556575982
Fold 4 IBS: 0.20604994096582308
Fold 5 IBS: 0.20242975121019796
[I 2024-04-17 14:20:39,894] Trial 41 finished with value: 0.20266472286497858 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4194662016160864, 'min_weight_fraction_leaf': 0.0945543359564518}. Best is trial 32 with value: 0.19086465523101687.
Fold 1 IBS: 0.21524181148556584
Fold 2 IBS: 0.20189381099543147
Fold 3 IBS: 0.19334224052360618
Fold 4 IBS: 0.2057676286065371
Fold 5 IBS: 0.20335546927493187
[I 2024-04-17 14:20:45,241] Trial 42 finished with value: 0.20392019217721452 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 224, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.3337156285310832, 'min_weight_fraction_leaf': 0.07533227903119888}. Best is trial 32 with value: 0.19086465523101687.
Fold 1 IBS: 0.21472960290810852
Fold 2 IBS: 0.20495777947784552
Fold 3 IBS: 0.19334614273976217
Fold 4 IBS: 0.20790813178292486
Fold 5 IBS: 0.2044500294070785
[I 2024-04-17 14:20:50,050] Trial 43 finished with value: 0.2050783372631439 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 186, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4575451197058098, 'min_weight_fraction_leaf': 0.11169179035709566}. Best is trial 32 with value: 0.19086465523101687.
Fold 1 IBS: 0.2158794028535924
Fold 2 IBS: 0.21504986941538556
Fold 3 IBS: 0.20270427563664198
Fold 4 IBS: 0.22084692246578624
Fold 5 IBS: 0.2148293684806663
[I 2024-04-17 14:20:55,678] Trial 44 finished with value: 0.2138619677704145 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 135, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.2814027607307883, 'min_weight_fraction_leaf': 0.06661592288945298}. Best is trial 32 with value: 0.19086465523101687.

Fold 1 IBS: 0.21630497223947837
Fold 2 IBS: 0.21958595298061412
Fold 3 IBS: 0.2035980172089794
Fold 4 IBS: 0.22215871269338675
Fold 5 IBS: 0.21643846186486954
[I 2024-04-17 14:20:58,930] Trial 45 finished with value: 0.21561722339746564 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 83, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.373726821058381, 'min_weight_fraction_leaf': 0.16389807799685063}. Best is trial 32 with value: 0.19086465523101687.
Fold 1 IBS: 0.21673865025266792
Fold 2 IBS: 0.21875173944717735
Fold 3 IBS: 0.20270337232862157
Fold 4 IBS: 0.22216669834462083
Fold 5 IBS: 0.2153324381929384
[I 2024-04-17 14:21:05,573] Trial 46 finished with value: 0.2151385797132052 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 162, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.5931574194958598, 'min_weight_fraction_leaf': 0.10038958944964108}. Best is trial 32 with value: 0.19086465523101687.
Fold 1 IBS: 0.21425547959245314
Fold 2 IBS: 0.17913931487252532
Fold 3 IBS: 0.1827920444200652
Fold 4 IBS: 0.18063025873191016
Fold 5 IBS: 0.17463369521553437
[I 2024-04-17 14:21:10,756] Trial 47 finished with value: 0.18629015856649767 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 133, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5303267586481767, 'min_weight_fraction_leaf': 0.022660091227809553}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.21724421014099518
Fold 2 IBS: 0.21655207424415854
Fold 3 IBS: 0.20264659710591693
Fold 4 IBS: 0.21838526568910469
Fold 5 IBS: 0.21475353458308485
[I 2024-04-17 14:21:14,601] Trial 48 finished with value: 0.21391633635265203 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 15, 'n_estimators': 122, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5204127209393646, 'min_weight_fraction_leaf': 0.021578575324599072}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.22739937804557755
Fold 2 IBS: 0.18431471901385207
Fold 3 IBS: 0.18012618979399134
Fold 4 IBS: 0.18756570696252242
Fold 5 IBS: 0.1725238813700449
[I 2024-04-17 14:21:16,663] Trial 49 finished with value: 0.19038597503719765 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 36, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6144379769217915, 'min_weight_fraction_leaf': 0.024114325813589327}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.2197395556342832
Fold 2 IBS: 0.1937382674133319
Fold 3 IBS: 0.18029510035200738
Fold 4 IBS: 0.18672723627142604
Fold 5 IBS: 0.17049654328619293
[I 2024-04-17 14:21:18,446] Trial 50 finished with value: 0.1901993405914483 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 33, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5534076553978717, 'min_weight_fraction_leaf': 0.01616361085327083}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.23319385988704497
Fold 2 IBS: 0.210982597300221
Fold 3 IBS: 0.19774226291559951
Fold 4 IBS: 0.22406644894993408
Fold 5 IBS: 0.2931537858846279
[I 2024-04-17 14:21:18,863] Trial 51 finished with value: 0.23182779098748546 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 1, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6069889428677941, 'min_weight_fraction_leaf': 0.013656251098304456}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.2266668946976624
Fold 2 IBS: 0.18963552238309106
Fold 3 IBS: 0.18051221840726392
Fold 4 IBS: 0.18522422599615693
Fold 5 IBS: 0.17887683418309638
[I 2024-04-17 14:21:20,502] Trial 52 finished with value: 0.19218313913345414 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 32, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5442816975043767, 'min_weight_fraction_leaf': 0.026294613707118428}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.21953127005312545
Fold 2 IBS: 0.17660827175886934
Fold 3 IBS: 0.18523201623096552
Fold 4 IBS: 0.18352435834165376
Fold 5 IBS: 0.17835495665559334
[I 2024-04-17 14:21:22,382] Trial 53 finished with value: 0.18865017460804148 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 45, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5061817732587037, 'min_weight_fraction_leaf': 0.025558074536998467}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.21616791542963654
Fold 2 IBS: 0.21766254858123116
Fold 3 IBS: 0.20421463942561668
Fold 4 IBS: 0.22239183846889607
Fold 5 IBS: 0.21417571285693626
[I 2024-04-17 14:21:23,849] Trial 54 finished with value: 0.21492253095246333 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 37, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.54402407939955, 'min_weight_fraction_leaf': 0.026013653686766648}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.21790300982066516
Fold 2 IBS: 0.2193033932764569
Fold 3 IBS: 0.20035454038213896
Fold 4 IBS: 0.22437896923278455
Fold 5 IBS: 0.21511604839179552
[I 2024-04-17 14:21:24,880] Trial 55 finished with value: 0.2154111922207682 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 20, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6195893286059789, 'min_weight_fraction_leaf': 0.05760460401228498}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.21579888642292963
Fold 2 IBS: 0.18682829052428385
Fold 3 IBS: 0.17987624260307564
Fold 4 IBS: 0.18080359496605097
Fold 5 IBS: 0.1752287221395638
[I 2024-04-17 14:21:26,990] Trial 56 finished with value: 0.1877071473311808 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 49, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5621125579936055, 'min_weight_fraction_leaf': 0.005571180329296155}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.2144889691580323
Fold 2 IBS: 0.2045329558262454
Fold 3 IBS: 0.19835367474914084
Fold 4 IBS: 0.20759499583493934
Fold 5 IBS: 0.20217397482103724
[I 2024-04-17 14:21:29,606] Trial 57 finished with value: 0.20542891407787903 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 54, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5739031977586767, 'min_weight_fraction_leaf': 0.004939537955850866}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.21400965955750983
Fold 2 IBS: 0.22205799929879846
Fold 3 IBS: 0.20413607793640554
Fold 4 IBS: 0.22497530189875292
Fold 5 IBS: 0.2179500012878666
[I 2024-04-17 14:21:32,384] Trial 58 finished with value: 0.21662580799586667 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 47, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4704068362199769, 'min_weight_fraction_leaf': 0.47632691903364677}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.23380456901007218
Fold 2 IBS: 0.18349308056039232
Fold 3 IBS: 0.19245969028055376
Fold 4 IBS: 0.20171081312247313
Fold 5 IBS: 0.19476486041859586
[I 2024-04-17 14:21:33,448] Trial 59 finished with value: 0.20124660267841749 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 13, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5669659293302698, 'min_weight_fraction_leaf': 5.5757627675220856e-05}. Best is trial 47 with value: 0.18629015856649767.

Fold 1 IBS: 0.21412261619089062
Fold 2 IBS: 0.20096170300523308
Fold 3 IBS: 0.19768334815553634
Fold 4 IBS: 0.20413083791991032
Fold 5 IBS: 0.2016512104175567
[I 2024-04-17 14:21:37,423] Trial 60 finished with value: 0.2037099431378254 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 91, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6341864022990672, 'min_weight_fraction_leaf': 0.04110019733163659}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.2176747793322257
Fold 2 IBS: 0.18204974561603254
Fold 3 IBS: 0.18642286195176436
Fold 4 IBS: 0.18175695168041173
Fold 5 IBS: 0.17167476077067825
[I 2024-04-17 14:21:39,468] Trial 61 finished with value: 0.18791581987022252 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 42, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5223779429597124, 'min_weight_fraction_leaf': 0.028146458835394832}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.21906116090138647
Fold 2 IBS: 0.18792138243056994
Fold 3 IBS: 0.18468916582720363
Fold 4 IBS: 0.18261106474464395
Fold 5 IBS: 0.18504685968161946
[I 2024-04-17 14:21:41,873] Trial 62 finished with value: 0.1918659267170847 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 56, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5120489274663694, 'min_weight_fraction_leaf': 0.05250679926753399}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.22163549052077466
Fold 2 IBS: 0.18230995073139705
Fold 3 IBS: 0.18613556261331868
Fold 4 IBS: 0.17944262802334593
Fold 5 IBS: 0.17107486619395224
[I 2024-04-17 14:21:43,617] Trial 63 finished with value: 0.18811969961655772 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 40, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.665257654686778, 'min_weight_fraction_leaf': 0.01435300323524109}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.23430008894929114
Fold 2 IBS: 0.1751028543590701
Fold 3 IBS: 0.1897232055243738
Fold 4 IBS: 0.17662233340108044
Fold 5 IBS: 0.1662251263199977
[I 2024-04-17 14:21:44,639] Trial 64 finished with value: 0.18839472171076266 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 19, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.677529909567254, 'min_weight_fraction_leaf': 0.01726993356385148}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.21406666459142548
Fold 2 IBS: 0.22270644856242683
Fold 3 IBS: 0.20420835233416298
Fold 4 IBS: 0.22610657684097313
Fold 5 IBS: 0.21906418743097011
[I 2024-04-17 14:21:45,534] Trial 65 finished with value: 0.21723044595199167 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 19, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6715407064962379, 'min_weight_fraction_leaf': 0.40019809578387655}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.2769733128360554
Fold 2 IBS: 0.2210712949212365
Fold 3 IBS: 0.1932168167867407
Fold 4 IBS: 0.21854802782654795
Fold 5 IBS: 0.22799031591884192
[I 2024-04-17 14:21:46,104] Trial 66 finished with value: 0.2275599536578845 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 2, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.5586046084196257, 'min_weight_fraction_leaf': 0.014725871284849179}. Best is trial 47 with value: 0.18629015856649767.
Fold 1 IBS: 0.21273230386018424
Fold 2 IBS: 0.18027814092139516
Fold 3 IBS: 0.18519021861267726
Fold 4 IBS: 0.17640951428670412
Fold 5 IBS: 0.17020747033922073
[I 2024-04-17 14:21:49,546] Trial 67 finished with value: 0.1849635296040363 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 96, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7411556645965716, 'min_weight_fraction_leaf': 0.03847734725391379}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.2110409510363906
Fold 2 IBS: 0.20107725277197525
Fold 3 IBS: 0.1969184032708582
Fold 4 IBS: 0.2077888694989155
Fold 5 IBS: 0.20013423910527522
[I 2024-04-17 14:21:53,375] Trial 68 finished with value: 0.20339194313668293 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 100, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7066898222776274, 'min_weight_fraction_leaf': 0.03745361850095254}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.20884063255341523
Fold 2 IBS: 0.1829444796698714
Fold 3 IBS: 0.18714666841495323
Fold 4 IBS: 0.17824707698930234
Fold 5 IBS: 0.17625439750165767
[I 2024-04-17 14:21:57,155] Trial 69 finished with value: 0.18668665102583995 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 122, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.748646515380685, 'min_weight_fraction_leaf': 0.0602477478443642}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.2105504283668898
Fold 2 IBS: 0.18257256262761098
Fold 3 IBS: 0.18765781156141634
Fold 4 IBS: 0.1779807779677816
Fold 5 IBS: 0.17769930437301143
[I 2024-04-17 14:22:01,675] Trial 70 finished with value: 0.18729217697934203 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 124, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7518788669264722, 'min_weight_fraction_leaf': 0.06198689550343181}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21420250177979033
Fold 2 IBS: 0.1866521031717368
Fold 3 IBS: 0.18613660226732462
Fold 4 IBS: 0.18009980525274344
Fold 5 IBS: 0.17591026889481626
[I 2024-04-17 14:22:06,079] Trial 71 finished with value: 0.1886002562732823 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 131, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7488013751681131, 'min_weight_fraction_leaf': 0.05998689716677624}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21644716563271307
Fold 2 IBS: 0.18390033649834056
Fold 3 IBS: 0.18847673547847435
Fold 4 IBS: 0.18248656254217968
Fold 5 IBS: 0.18106941399383106
[I 2024-04-17 14:22:09,630] Trial 72 finished with value: 0.19047604282910774 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 120, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.795640838016473, 'min_weight_fraction_leaf': 0.06309958970984873}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21835991672410568
Fold 2 IBS: 0.17757788503517372
Fold 3 IBS: 0.1897261802535648
Fold 4 IBS: 0.17160898160650764
Fold 5 IBS: 0.16974347462650047
[I 2024-04-17 14:22:11,862] Trial 73 finished with value: 0.18540328764917047 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 67, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8324564791189543, 'min_weight_fraction_leaf': 0.03876245188158168}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.22439173796628295
Fold 2 IBS: 0.1796449344210749
Fold 3 IBS: 0.1872215544211083
Fold 4 IBS: 0.1723142732967454
Fold 5 IBS: 0.17036622006874097
[I 2024-04-17 14:22:13,832] Trial 74 finished with value: 0.18678774403479054 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 62, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8277974219460319, 'min_weight_fraction_leaf': 0.03549627911477489}. Best is trial 67 with value: 0.1849635296040363.

Fold 1 IBS: 0.21702643850803088
Fold 2 IBS: 0.17804524130728247
Fold 3 IBS: 0.18851531925648804
Fold 4 IBS: 0.17648057689338645
Fold 5 IBS: 0.17154746817991223
[I 2024-04-17 14:22:15,850] Trial 75 finished with value: 0.18632300882902003 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 66, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8255984813979496, 'min_weight_fraction_leaf': 0.040756159127064116}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.2113961496484921
Fold 2 IBS: 0.1821449835808232
Fold 3 IBS: 0.18903595168291273
Fold 4 IBS: 0.17765728598189454
Fold 5 IBS: 0.17855049104288342
[I 2024-04-17 14:22:18,503] Trial 76 finished with value: 0.18775697238740122 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 93, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7596730681206731, 'min_weight_fraction_leaf': 0.042262604872317644}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.22246208708666573
Fold 2 IBS: 0.17689409269788126
Fold 3 IBS: 0.18712786970947148
Fold 4 IBS: 0.18228926264331374
Fold 5 IBS: 0.17657065314495285
[I 2024-04-17 14:22:20,494] Trial 77 finished with value: 0.18906879305645702 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 63, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.858162290497981, 'min_weight_fraction_leaf': 0.06939369344295301}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21510602228050169
Fold 2 IBS: 0.2198888124214069
Fold 3 IBS: 0.20374671256065052
Fold 4 IBS: 0.2224759893984314
Fold 5 IBS: 0.21701286452165527
[I 2024-04-17 14:22:26,673] Trial 78 finished with value: 0.21564608023652915 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 217, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8286287108747691, 'min_weight_fraction_leaf': 0.22239260679340933}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21581682999529425
Fold 2 IBS: 0.18177795307121625
Fold 3 IBS: 0.18524392675012674
Fold 4 IBS: 0.177083297282869
Fold 5 IBS: 0.1755558422553125
[I 2024-04-17 14:22:32,346] Trial 79 finished with value: 0.18709556987096373 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 164, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9249295507960844, 'min_weight_fraction_leaf': 0.046550766241629}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21215405533807097
Fold 2 IBS: 0.21000885311421788
Fold 3 IBS: 0.19815978772163764
Fold 4 IBS: 0.2118334094288967
Fold 5 IBS: 0.20727368563885215
[I 2024-04-17 14:22:36,857] Trial 80 finished with value: 0.20788595824833508 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 165, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9328430641308777, 'min_weight_fraction_leaf': 0.11265460650799373}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21152073301749758
Fold 2 IBS: 0.18061785000622
Fold 3 IBS: 0.1890530167283906
Fold 4 IBS: 0.17793635003500358
Fold 5 IBS: 0.172792671536701
[I 2024-04-17 14:22:40,377] Trial 81 finished with value: 0.18638412426476253 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 113, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8427814851326104, 'min_weight_fraction_leaf': 0.042920800159017565}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21194653141784214
Fold 2 IBS: 0.18224818294891776
Fold 3 IBS: 0.18727105796707924
Fold 4 IBS: 0.17818054838244235
Fold 5 IBS: 0.17785708081948454
[I 2024-04-17 14:22:44,448] Trial 82 finished with value: 0.1875006803071532 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 144, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8391639495890854, 'min_weight_fraction_leaf': 0.054006381492254375}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21535225261800472
Fold 2 IBS: 0.21598984456911946
Fold 3 IBS: 0.1989617082866624
Fold 4 IBS: 0.21488453581222672
Fold 5 IBS: 0.21394181157175768
[I 2024-04-17 14:22:47,883] Trial 83 finished with value: 0.2118260305715542 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 117, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8973399725033426, 'min_weight_fraction_leaf': 0.2777305993178613}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21566258015091944
Fold 2 IBS: 0.18284059632192065
Fold 3 IBS: 0.1857289869444882
Fold 4 IBS: 0.17609564397129115
Fold 5 IBS: 0.18049448970782342
[I 2024-04-17 14:22:51,551] Trial 84 finished with value: 0.18816445941928855 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 102, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9651700261608529, 'min_weight_fraction_leaf': 0.042369618547887504}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21107165494794433
Fold 2 IBS: 0.18488254527745138
Fold 3 IBS: 0.18587822106638013
Fold 4 IBS: 0.18233030674085207
Fold 5 IBS: 0.18188327120113776
[I 2024-04-17 14:22:56,873] Trial 85 finished with value: 0.18920919984675313 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 175, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.778013262769834, 'min_weight_fraction_leaf': 0.07179192114605096}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21315999911197117
Fold 2 IBS: 0.2071209080117046
Fold 3 IBS: 0.19785500876600776
Fold 4 IBS: 0.2098415595743567
Fold 5 IBS: 0.20832756775760256
[I 2024-04-17 14:23:00,189] Trial 86 finished with value: 0.20726100864432856 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 123, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.739636215236867, 'min_weight_fraction_leaf': 0.08520616426995853}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.2177364176416788
Fold 2 IBS: 0.19309448032961318
Fold 3 IBS: 0.19277404488888836
Fold 4 IBS: 0.1982291099894136
Fold 5 IBS: 0.19789842311843042
[I 2024-04-17 14:23:02,437] Trial 87 finished with value: 0.19994649519360488 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 83, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8120695870979759, 'min_weight_fraction_leaf': 0.12555286653951156}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21624404113568266
Fold 2 IBS: 0.18635613379270805
Fold 3 IBS: 0.18967588957148593
Fold 4 IBS: 0.1932423253455397
Fold 5 IBS: 0.18949167103332232
[I 2024-04-17 14:23:05,483] Trial 88 finished with value: 0.19500201217574772 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 108, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8900700832548645, 'min_weight_fraction_leaf': 0.10570416936432725}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.2152632872423301
Fold 2 IBS: 0.21366245501437117
Fold 3 IBS: 0.20021700883286153
Fold 4 IBS: 0.21771243420506461
Fold 5 IBS: 0.2124582597362233
[I 2024-04-17 14:23:08,915] Trial 89 finished with value: 0.21186268900617017 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 131, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9361758018600508, 'min_weight_fraction_leaf': 0.038936351001670394}. Best is trial 67 with value: 0.1849635296040363.

Fold 1 IBS: 0.22037856887965046
Fold 2 IBS: 0.18002949433356782
Fold 3 IBS: 0.18406495584411262
Fold 4 IBS: 0.1773755631460241
Fold 5 IBS: 0.1758543766206012
[I 2024-04-17 14:23:11,035] Trial 90 finished with value: 0.18754059176479126 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 66, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9979754136756178, 'min_weight_fraction_leaf': 0.06231875931942612}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21238270350650948
Fold 2 IBS: 0.18322172515976223
Fold 3 IBS: 0.18710380027472065
Fold 4 IBS: 0.17995136154962357
Fold 5 IBS: 0.1745804020860065
[I 2024-04-17 14:23:14,899] Trial 91 finished with value: 0.18744799851532448 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 140, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.843460806052546, 'min_weight_fraction_leaf': 0.05180823692642744}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21278994784170352
Fold 2 IBS: 0.18479535663694688
Fold 3 IBS: 0.1860640610092116
Fold 4 IBS: 0.18540456914053857
Fold 5 IBS: 0.18515953301007973
[I 2024-04-17 14:23:18,532] Trial 92 finished with value: 0.19084269352769606 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 144, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8538695418461669, 'min_weight_fraction_leaf': 0.08076705779168918}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21872009463419034
Fold 2 IBS: 0.18452355680565485
Fold 3 IBS: 0.1832314893378785
Fold 4 IBS: 0.17292384315292994
Fold 5 IBS: 0.16909005451672793
[I 2024-04-17 14:23:23,345] Trial 93 finished with value: 0.18569780768947633 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 174, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7881162614459546, 'min_weight_fraction_leaf': 0.03406843816502406}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.2159618275035358
Fold 2 IBS: 0.18350433073580202
Fold 3 IBS: 0.18377701483788939
Fold 4 IBS: 0.17211828145058145
Fold 5 IBS: 0.17116506358250472
[I 2024-04-17 14:23:29,725] Trial 94 finished with value: 0.18530530362206268 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 254, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8056257308841542, 'min_weight_fraction_leaf': 0.035772282793839066}. Best is trial 67 with value: 0.1849635296040363.
Fold 1 IBS: 0.21515177114558817
Fold 2 IBS: 0.1816485230518495
Fold 3 IBS: 0.18393189697670614
Fold 4 IBS: 0.17287010563149305
Fold 5 IBS: 0.17065466892903086
[I 2024-04-17 14:23:37,625] Trial 95 finished with value: 0.18485139314693355 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 283, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8750989298883327, 'min_weight_fraction_leaf': 0.033928724445100075}. Best is trial 95 with value: 0.18485139314693355.
Fold 1 IBS: 0.21571409652728732
Fold 2 IBS: 0.1833338606629635
Fold 3 IBS: 0.1829353893657255
Fold 4 IBS: 0.17124853151262076
Fold 5 IBS: 0.1705033290037184
[I 2024-04-17 14:23:44,035] Trial 96 finished with value: 0.1847470414144631 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 270, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8792554548020176, 'min_weight_fraction_leaf': 0.03248712490564588}. Best is trial 96 with value: 0.1847470414144631.
Fold 1 IBS: 0.21285673042987568
Fold 2 IBS: 0.18027821429985305
Fold 3 IBS: 0.18414157733228365
Fold 4 IBS: 0.17332257855704428
Fold 5 IBS: 0.16997721935674265
[I 2024-04-17 14:23:49,705] Trial 97 finished with value: 0.18411526399515984 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 271, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8748007063265831, 'min_weight_fraction_leaf': 0.030472659040326068}. Best is trial 97 with value: 0.18411526399515984.
Fold 1 IBS: 0.21100143752868192
Fold 2 IBS: 0.18965432165387422
Fold 3 IBS: 0.19076398112784826
Fold 4 IBS: 0.19586492264276503
Fold 5 IBS: 0.18675805733294548
[I 2024-04-17 14:23:55,656] Trial 98 finished with value: 0.19480854405722298 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 285, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8842886539438466, 'min_weight_fraction_leaf': 0.007780463910348246}. Best is trial 97 with value: 0.18411526399515984.
Fold 1 IBS: 0.21235843118367126
Fold 2 IBS: 0.18059650920741668
Fold 3 IBS: 0.1835568611733814
Fold 4 IBS: 0.17296436224547088
Fold 5 IBS: 0.17026379829375063
[I 2024-04-17 14:24:00,852] Trial 99 finished with value: 0.18394799242073817 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8754219619832959, 'min_weight_fraction_leaf': 0.031831116281223065}. Best is trial 99 with value: 0.18394799242073817.


* Best trial for IBS:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.18394799242073817], datetime_start=datetime.datetime(2024, 4, 17, 14, 23, 55, 664483), datetime_complete=datetime.datetime(2024, 4, 17, 14, 24, 0, 851317), params={'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8754219619832959, 'min_weight_fraction_leaf': 0.031831116281223065}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=99, value=None)


* Best Score for IBS:
 0.18394799242073817

In [59]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [60]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.807
train_ibs:  0.184

#### Test

In [61]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [62]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=7, max_features=None, max_leaf_nodes=10,
                   max_samples=0.939348623311968, min_samples_split=5,
                   min_weight_fraction_leaf=0.013770059968835775,
                   n_estimators=322, random_state=123, warm_start=True)

C-index score: 0.58

ExtraSurvivalTrees(max_depth=18, max_features=None, max_leaf_nodes=20,
                   max_samples=0.8754219619832959, min_samples_leaf=2,
                   min_samples_split=15,
                   min_weight_fraction_leaf=0.031831116281223065,
                   n_estimators=259, random_state=123, warm_start=True)

IBS: 0.228

In [63]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [64]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 14:24:03,253] A new study created in memory with name: no-name-39844da6-1e3c-407f-8d9f-cd25da1023b3

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:24:42,190] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:25:03,883] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:25:23,557] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:25:56,913] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:26:12,080] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:26:15,259] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:26:48,667] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:26:57,764] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:26:59,092] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6038961038961039
Fold 2 C-index: 0.7075892857142857
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 14:28:23,117] Trial 9 finished with value: 0.6713230131312481 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6713230131312481.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6737089201877934
[I 2024-04-17 14:30:34,461] Trial 10 finished with value: 0.568075117370892 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6713230131312481.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:32:59,226] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6713230131312481.
Fold 1 C-index: 0.6558441558441559
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.6887254901960784
Fold 4 C-index: 0.7109704641350211
Fold 5 C-index: 0.6924882629107981
[I 2024-04-17 14:35:04,906] Trial 12 finished with value: 0.7009449603314964 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.7009449603314964.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:36:04,757] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:37:25,018] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:38:40,120] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:39:34,342] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:41:17,200] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:43:37,474] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:43:42,873] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:44:33,562] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:46:31,237] Trial 21 finished with value: 0.5 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.43506493506493504
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.6029411764705882
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.6431924882629108
[I 2024-04-17 14:48:11,843] Trial 22 finished with value: 0.6019607868674626 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:49:42,769] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:50:57,168] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:51:47,419] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:53:33,120] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:55:12,450] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:56:26,803] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:57:18,399] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:58:18,455] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:00:23,155] Trial 31 finished with value: 0.5 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:02:42,371] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:04:05,927] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:06:02,120] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:06:23,264] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:08:10,103] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:08:13,363] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 12 with value: 0.7009449603314964.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:08:52,364] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:10:05,396] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:11:58,297] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:11:58,622] Trial 41 finished with value: 0.5 and parameters: {'subsample': 0.7314932964129175, 'learning_rate': 0.01409866469899027, 'dropout_rate': 0.25927237673806974, 'n_estimators': 1, 'criterion': 'friedman_mse', 'ccp_alpha': 6.422443003379805, 'min_weight_fraction_leaf': 0.2592502890556771, 'max_features': None, 'min_impurity_decrease': 0.00046889459087331233, 'validation_fraction': 0.7339745526007295, 'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:12:29,365] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.8635261303914503, 'learning_rate': 0.06618063570768928, 'dropout_rate': 0.21701156680188333, 'n_estimators': 236, 'criterion': 'friedman_mse', 'ccp_alpha': 8.230119285920345, 'min_weight_fraction_leaf': 0.3447746516166785, 'max_features': None, 'min_impurity_decrease': 1.9832896573105213e-05, 'validation_fraction': 0.6587210926816298, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:13:10,765] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5792270906384994, 'learning_rate': 0.007569574313996779, 'dropout_rate': 0.13009999428832833, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 8.544754247040371, 'min_weight_fraction_leaf': 0.37715746272334727, 'max_features': None, 'min_impurity_decrease': 9.019275478873865e-05, 'validation_fraction': 0.8415757140495828, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 10}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:13:23,476] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.7872457012118046, 'learning_rate': 0.042999799171261954, 'dropout_rate': 0.3684859430701791, 'n_estimators': 164, 'criterion': 'friedman_mse', 'ccp_alpha': 9.884609761552603, 'min_weight_fraction_leaf': 0.4563543800389965, 'max_features': None, 'min_impurity_decrease': 2.2080377939848e-07, 'validation_fraction': 0.5674038323356935, 'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 16}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:14:10,233] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.9436582561003044, 'learning_rate': 0.01524983211078064, 'dropout_rate': 0.588577514842217, 'n_estimators': 401, 'criterion': 'friedman_mse', 'ccp_alpha': 6.651892060576439, 'min_weight_fraction_leaf': 0.4018557625407492, 'max_features': 0.1, 'min_impurity_decrease': 1.8062826429116324e-06, 'validation_fraction': 0.9542863654309715, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 9}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:14:26,944] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5165290285700016, 'learning_rate': 0.02319868205399652, 'dropout_rate': 0.9694253886674298, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 9.048241205043816, 'min_weight_fraction_leaf': 0.3115196264589247, 'max_features': 'log2', 'min_impurity_decrease': 0.001644356047914736, 'validation_fraction': 0.8846679916016404, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:15:36,886] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5904822223880848, 'learning_rate': 0.0069795680561797555, 'dropout_rate': 0.27413800857922854, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 7.181314443016622, 'min_weight_fraction_leaf': 0.2227662317014242, 'max_features': 'auto', 'min_impurity_decrease': 5.579254342230346e-06, 'validation_fraction': 0.6898188497269258, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 11}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:15:59,177] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.8377698389118777, 'learning_rate': 0.030447501600320594, 'dropout_rate': 0.4343069730937482, 'n_estimators': 237, 'criterion': 'squared_error', 'ccp_alpha': 0.44229350847698845, 'min_weight_fraction_leaf': 0.27384255345855457, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0799788619370968e-06, 'validation_fraction': 0.8690312650846541, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:16:48,077] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.9014143402771908, 'learning_rate': 0.019069047730291548, 'dropout_rate': 0.15628654397338398, 'n_estimators': 297, 'criterion': 'squared_error', 'ccp_alpha': 1.222549263924274, 'min_weight_fraction_leaf': 0.37835008934172737, 'max_features': 'auto', 'min_impurity_decrease': 2.3869690244810263e-06, 'validation_fraction': 0.6110159828303156, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 12}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:18:34,449] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.6722013360862389, 'learning_rate': 0.0011637610610685928, 'dropout_rate': 0.11834255517896833, 'n_estimators': 417, 'criterion': 'friedman_mse', 'ccp_alpha': 1.772659436678572, 'min_weight_fraction_leaf': 0.33123579278860354, 'max_features': 'auto', 'min_impurity_decrease': 3.3297622395273564e-07, 'validation_fraction': 0.8157407077160861, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 8}. Best is trial 12 with value: 0.7009449603314964.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:19:05,685] Trial 51 finished with value: 0.5 and parameters: {'subsample': 0.4606648159054066, 'learning_rate': 0.09644321475547749, 'dropout_rate': 0.676921980791406, 'n_estimators': 324, 'criterion': 'friedman_mse', 'ccp_alpha': 5.698109912526597, 'min_weight_fraction_leaf': 0.009454723617732017, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0003194574130234848, 'validation_fraction': 0.20910739088327182, 'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 12}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5865800865800865
Fold 2 C-index: 0.6897321428571429
Fold 3 C-index: 0.5759803921568627
Fold 4 C-index: 0.6434599156118144
Fold 5 C-index: 0.687793427230047
[I 2024-04-17 15:19:14,691] Trial 52 finished with value: 0.6367091928871907 and parameters: {'subsample': 0.6307630032474463, 'learning_rate': 0.0797433994002493, 'dropout_rate': 0.9019406028516623, 'n_estimators': 258, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03710606902460499, 'min_weight_fraction_leaf': 0.14235013403546368, 'max_features': 'sqrt', 'min_impurity_decrease': 4.622343656719489e-05, 'validation_fraction': 0.3406032150791013, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5324675324675324
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.5735294117647058
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 15:19:19,998] Trial 53 finished with value: 0.6328777926023161 and parameters: {'subsample': 0.539345983620747, 'learning_rate': 0.08646200679648029, 'dropout_rate': 0.9293661770435817, 'n_estimators': 197, 'criterion': 'friedman_mse', 'ccp_alpha': 0.009820569816943125, 'min_weight_fraction_leaf': 0.15776506745071406, 'max_features': 'sqrt', 'min_impurity_decrease': 6.243547110770978e-05, 'validation_fraction': 0.3297138181787256, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 14}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:19:25,173] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.4122659993128194, 'learning_rate': 0.09006054356742435, 'dropout_rate': 0.901466608466225, 'n_estimators': 166, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3662685742538932, 'min_weight_fraction_leaf': 0.12759593111970943, 'max_features': 'sqrt', 'min_impurity_decrease': 5.659382809466258e-05, 'validation_fraction': 0.3370466013536922, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.564935064935065
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.6053921568627451
Fold 4 C-index: 0.6413502109704642
Fold 5 C-index: 0.6572769953051644
[I 2024-04-17 15:19:28,637] Trial 55 finished with value: 0.632183742757545 and parameters: {'subsample': 0.6260529149480705, 'learning_rate': 0.07808142247997509, 'dropout_rate': 0.8859792395781099, 'n_estimators': 117, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03680304263373871, 'min_weight_fraction_leaf': 0.15390921956023235, 'max_features': 'sqrt', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.4043604570150481, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:19:31,082] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.5524483139580307, 'learning_rate': 0.08198533807055247, 'dropout_rate': 0.8800223988178697, 'n_estimators': 94, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0376723781883062, 'min_weight_fraction_leaf': 0.15089096313689324, 'max_features': 'sqrt', 'min_impurity_decrease': 0.015875756958720868, 'validation_fraction': 0.38909071963160285, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5541125541125541
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.6772151898734177
Fold 5 C-index: 0.715962441314554
[I 2024-04-17 15:19:34,270] Trial 57 finished with value: 0.6609216224942789 and parameters: {'subsample': 0.6446884806787394, 'learning_rate': 0.07439616301612664, 'dropout_rate': 0.8376763566011604, 'n_estimators': 113, 'criterion': 'friedman_mse', 'ccp_alpha': 0.0019590724667788023, 'min_weight_fraction_leaf': 0.0986277853305848, 'max_features': 'sqrt', 'min_impurity_decrease': 0.004365976632712866, 'validation_fraction': 0.2924600276956252, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:19:37,864] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.6423260507022313, 'learning_rate': 0.07516712250657744, 'dropout_rate': 0.8518170622435416, 'n_estimators': 133, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3772772529422126, 'min_weight_fraction_leaf': 0.09954476156869702, 'max_features': 'sqrt', 'min_impurity_decrease': 0.004081914358688746, 'validation_fraction': 0.242274730848875, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 17}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:19:39,848] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.6146398017512089, 'learning_rate': 0.08413268603433857, 'dropout_rate': 0.9896948217651667, 'n_estimators': 117, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6490219824891021, 'min_weight_fraction_leaf': 0.04711645707058228, 'max_features': 'sqrt', 'min_impurity_decrease': 0.09391541518055696, 'validation_fraction': 0.29122938147036764, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:19:41,062] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.5217757238489257, 'learning_rate': 0.07729331447459753, 'dropout_rate': 0.8185319122493209, 'n_estimators': 50, 'criterion': 'friedman_mse', 'ccp_alpha': 2.0686972692115084, 'min_weight_fraction_leaf': 0.1487993981072714, 'max_features': 'sqrt', 'min_impurity_decrease': 0.028708552959260614, 'validation_fraction': 0.4826444492816219, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 20}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:19:42,538] Trial 61 finished with value: 0.5238095238095238 and parameters: {'subsample': 0.485306121877392, 'learning_rate': 0.06315283699607928, 'dropout_rate': 0.9519769662065143, 'n_estimators': 75, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20870781527834906, 'min_weight_fraction_leaf': 0.1836611388422435, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002778067217850893, 'validation_fraction': 0.39604524665390706, 'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.5931372549019608
Fold 4 C-index: 0.6687763713080169
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 15:19:46,750] Trial 62 finished with value: 0.643254851941587 and parameters: {'subsample': 0.5848702586582711, 'learning_rate': 0.09009755516528982, 'dropout_rate': 0.9302311429720538, 'n_estimators': 173, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022768311155810905, 'min_weight_fraction_leaf': 0.20509075115334974, 'max_features': 'sqrt', 'min_impurity_decrease': 0.014963412670553608, 'validation_fraction': 0.29673629821162695, 'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 12 with value: 0.7009449603314964.

Fold 1 C-index: 0.5411255411255411
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.5735294117647058
Fold 4 C-index: 0.6392405063291139
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 15:19:52,037] Trial 63 finished with value: 0.6253682937218065 and parameters: {'subsample': 0.5819456155674311, 'learning_rate': 0.09995278469443522, 'dropout_rate': 0.9161995789859271, 'n_estimators': 190, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.2002766970955306, 'max_features': 'sqrt', 'min_impurity_decrease': 0.005901055993127604, 'validation_fraction': 0.1597978704290923, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:20:00,492] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.5496070230514682, 'learning_rate': 0.08913644315840567, 'dropout_rate': 0.7565492519865015, 'n_estimators': 191, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.1101645933578981, 'max_features': 'sqrt', 'min_impurity_decrease': 0.011706217732829045, 'validation_fraction': 0.2688406336636883, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:20:04,562] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.7163728996237841, 'learning_rate': 0.0708083560785101, 'dropout_rate': 0.8534911667933335, 'n_estimators': 137, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9229393860301199, 'min_weight_fraction_leaf': 0.15421008767110625, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0010758648175384798, 'validation_fraction': 0.32657179911263323, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:20:13,720] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.43194182415924004, 'learning_rate': 0.08223509355569698, 'dropout_rate': 0.803684610677954, 'n_estimators': 213, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3356652825773984, 'min_weight_fraction_leaf': 0.2121752597589217, 'max_features': 'sqrt', 'min_impurity_decrease': 0.053988919449682586, 'validation_fraction': 0.36619068156997725, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:20:18,933] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.6041418257183064, 'learning_rate': 0.08984094713256173, 'dropout_rate': 0.8718519455115071, 'n_estimators': 174, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3667875604937267, 'min_weight_fraction_leaf': 0.050051018429414146, 'max_features': 'sqrt', 'min_impurity_decrease': 0.01027373150561059, 'validation_fraction': 0.45149861009303155, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 17}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:20:21,909] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.3022825214052564, 'learning_rate': 0.07824769804951595, 'dropout_rate': 0.9313919650462837, 'n_estimators': 121, 'criterion': 'friedman_mse', 'ccp_alpha': 0.40623725070669264, 'min_weight_fraction_leaf': 0.16816531721286487, 'max_features': 'sqrt', 'min_impurity_decrease': 0.024253534295398595, 'validation_fraction': 0.3009904783068915, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 14}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:20:25,119] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.35774854447983384, 'learning_rate': 0.07322674855756099, 'dropout_rate': 0.9896560378160989, 'n_estimators': 154, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8631583382158398, 'min_weight_fraction_leaf': 0.1959735670046889, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0003534142585555415, 'validation_fraction': 0.17340071972196938, 'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 18}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.5980392156862745
Fold 4 C-index: 0.6645569620253164
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 15:20:36,493] Trial 70 finished with value: 0.6514080228113872 and parameters: {'subsample': 0.6746725084701881, 'learning_rate': 0.08669975728908877, 'dropout_rate': 0.8348482401305211, 'n_estimators': 228, 'criterion': 'friedman_mse', 'ccp_alpha': 0.010117181990116787, 'min_weight_fraction_leaf': 0.23858294454529286, 'max_features': 1, 'min_impurity_decrease': 0.00018359304704764845, 'validation_fraction': 0.4347052214290571, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.6986607142857143
Fold 3 C-index: 0.6127450980392157
Fold 4 C-index: 0.6476793248945147
Fold 5 C-index: 0.6737089201877934
[I 2024-04-17 15:20:53,453] Trial 71 finished with value: 0.6391129240355602 and parameters: {'subsample': 0.633636210924881, 'learning_rate': 0.09296916220506257, 'dropout_rate': 0.7065335836233497, 'n_estimators': 230, 'criterion': 'friedman_mse', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.23541548544178648, 'max_features': 1, 'min_impurity_decrease': 0.00015303057249446608, 'validation_fraction': 0.42970051809000703, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 13}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.6078431372549019
Fold 4 C-index: 0.6561181434599156
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 15:21:06,588] Trial 72 finished with value: 0.6482288911042463 and parameters: {'subsample': 0.6853746436050964, 'learning_rate': 0.08859322103096448, 'dropout_rate': 0.7234474037831898, 'n_estimators': 232, 'criterion': 'friedman_mse', 'ccp_alpha': 0.004791445009673343, 'min_weight_fraction_leaf': 0.2365811563451999, 'max_features': 1, 'min_impurity_decrease': 0.0001544669413945096, 'validation_fraction': 0.43537478311701233, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 14}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:21:21,797] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.6722496235113209, 'learning_rate': 0.09257317546450888, 'dropout_rate': 0.7044418490831124, 'n_estimators': 247, 'criterion': 'friedman_mse', 'ccp_alpha': 0.351372518707486, 'min_weight_fraction_leaf': 0.2463939877671016, 'max_features': 1, 'min_impurity_decrease': 0.0001879057329471303, 'validation_fraction': 0.43701163012490485, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:21:33,380] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.7383972516702114, 'learning_rate': 0.09459808665220469, 'dropout_rate': 0.7357242981314874, 'n_estimators': 220, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7139433405649337, 'min_weight_fraction_leaf': 0.2274999600824757, 'max_features': 1, 'min_impurity_decrease': 0.000201911951557214, 'validation_fraction': 0.5369429051692747, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 13}. Best is trial 12 with value: 0.7009449603314964.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:21:46,935] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.6550632497667626, 'learning_rate': 0.08636682204359185, 'dropout_rate': 0.834596998299348, 'n_estimators': 290, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0534335086500939, 'min_weight_fraction_leaf': 0.2687815035423252, 'max_features': 1, 'min_impurity_decrease': 0.0007791279544191282, 'validation_fraction': 0.47622063790171204, 'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 13}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:22:08,672] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.6956589651832868, 'learning_rate': 0.09993221455236687, 'dropout_rate': 0.604557635768925, 'n_estimators': 267, 'criterion': 'friedman_mse', 'ccp_alpha': 0.32366698378279035, 'min_weight_fraction_leaf': 0.22852271185714598, 'max_features': 1, 'min_impurity_decrease': 0.00012221513723000485, 'validation_fraction': 0.37729195525908027, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:22:24,904] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.5615307910508487, 'learning_rate': 0.052009701795490706, 'dropout_rate': 0.6362590921244992, 'n_estimators': 234, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5870242559119005, 'min_weight_fraction_leaf': 0.26216996832415673, 'max_features': 1, 'min_impurity_decrease': 0.0006379302854199427, 'validation_fraction': 0.5145804207390895, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:22:37,560] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.7749637362062449, 'learning_rate': 0.08013416535587958, 'dropout_rate': 0.7696992583170289, 'n_estimators': 226, 'criterion': 'friedman_mse', 'ccp_alpha': 1.4931675844467045, 'min_weight_fraction_leaf': 0.28488038648314357, 'max_features': 1, 'min_impurity_decrease': 1.1996462524709698e-05, 'validation_fraction': 0.4222260644953216, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 12}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:22:54,861] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.6377688007531392, 'learning_rate': 0.09219000400220487, 'dropout_rate': 0.711423764998236, 'n_estimators': 254, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8315019491161123, 'min_weight_fraction_leaf': 0.2984420272502294, 'max_features': 1, 'min_impurity_decrease': 0.055421093979288065, 'validation_fraction': 0.278273132194713, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:23:10,180] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.6893371649971846, 'learning_rate': 0.08567904199902317, 'dropout_rate': 0.5338147112087412, 'n_estimators': 205, 'criterion': 'friedman_mse', 'ccp_alpha': 1.165054266906994, 'min_weight_fraction_leaf': 0.21298952946900213, 'max_features': 1, 'min_impurity_decrease': 0.0001260722921249151, 'validation_fraction': 0.45582753109790985, 'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5497835497835498
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.5980392156862745
Fold 4 C-index: 0.6476793248945147
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 15:23:14,482] Trial 81 finished with value: 0.6408785870869523 and parameters: {'subsample': 0.5396136111349831, 'learning_rate': 0.0882900872606242, 'dropout_rate': 0.9491096943609815, 'n_estimators': 185, 'criterion': 'friedman_mse', 'ccp_alpha': 0.025376297537854163, 'min_weight_fraction_leaf': 0.1837894396105955, 'max_features': 0.1, 'min_impurity_decrease': 1.6212673288099085e-05, 'validation_fraction': 0.3433923998205047, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 14}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:23:21,319] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.5917915026473667, 'learning_rate': 0.08863340789888571, 'dropout_rate': 0.7935335410767765, 'n_estimators': 183, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2451713250089625, 'min_weight_fraction_leaf': 0.18539900454440145, 'max_features': 0.1, 'min_impurity_decrease': 4.211728052333228e-05, 'validation_fraction': 0.35692706431850046, 'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 14}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:23:28,829] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.6232517813933866, 'learning_rate': 0.09665095022410278, 'dropout_rate': 0.9493162570988356, 'n_estimators': 282, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5023689971661962, 'min_weight_fraction_leaf': 0.240455361999192, 'max_features': 0.1, 'min_impurity_decrease': 1.9412964459961256e-05, 'validation_fraction': 0.25595559465053885, 'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 13}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:23:36,778] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.569720941376756, 'learning_rate': 0.08286370318701235, 'dropout_rate': 0.907687571540407, 'n_estimators': 249, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2086783018051136, 'min_weight_fraction_leaf': 0.25047421780109286, 'max_features': 0.1, 'min_impurity_decrease': 3.504018354510704e-05, 'validation_fraction': 0.2094040706416179, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5541125541125541
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6176470588235294
Fold 4 C-index: 0.6687763713080169
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 15:24:16,524] Trial 85 finished with value: 0.6528867072445277 and parameters: {'subsample': 0.6624562638269229, 'learning_rate': 0.061131653047197136, 'dropout_rate': 0.5775982322012432, 'n_estimators': 361, 'criterion': 'friedman_mse', 'ccp_alpha': 0.011637416243612385, 'min_weight_fraction_leaf': 0.13583349805266917, 'max_features': 'log2', 'min_impurity_decrease': 8.797907046701511e-05, 'validation_fraction': 0.31582894823702046, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 14}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:24:52,547] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.4973317638503055, 'learning_rate': 0.0659431035616299, 'dropout_rate': 0.6405809917794909, 'n_estimators': 362, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6244979273697576, 'min_weight_fraction_leaf': 0.17751416241613996, 'max_features': 'log2', 'min_impurity_decrease': 0.00023562615313221216, 'validation_fraction': 0.30728577861687745, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 12}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:25:04,253] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.6662017148025364, 'learning_rate': 0.09246176756843613, 'dropout_rate': 0.49308788025511585, 'n_estimators': 174, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9037351892935591, 'min_weight_fraction_leaf': 0.20080985872402782, 'max_features': 'log2', 'min_impurity_decrease': 7.958671865020276e-05, 'validation_fraction': 0.4092864595893532, 'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 14}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:25:37,933] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.7380689890682415, 'learning_rate': 0.056308496457800124, 'dropout_rate': 0.5603965994296136, 'n_estimators': 324, 'criterion': 'squared_error', 'ccp_alpha': 3.7623047606174946, 'min_weight_fraction_leaf': 0.2364232304159405, 'max_features': 'log2', 'min_impurity_decrease': 1.2521652441561236e-05, 'validation_fraction': 0.5650290936693902, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 10}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:25:49,416] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.5969783100706753, 'learning_rate': 0.059162712436384324, 'dropout_rate': 0.677538135219951, 'n_estimators': 202, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2625520900597902, 'min_weight_fraction_leaf': 0.07831654848847301, 'max_features': 1, 'min_impurity_decrease': 0.0017338932614573632, 'validation_fraction': 0.4970479006211754, 'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 19}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:25:54,097] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.7215866781729683, 'learning_rate': 0.07073008964456817, 'dropout_rate': 0.8278768039209315, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 1.2032785273426603, 'min_weight_fraction_leaf': 0.21181006764078292, 'max_features': 0.1, 'min_impurity_decrease': 0.00013229688924125003, 'validation_fraction': 0.3655882354727123, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 13}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7254464285714286
Fold 3 C-index: 0.6053921568627451
Fold 4 C-index: 0.6476793248945147
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 15:26:04,786] Trial 91 finished with value: 0.6573339704566894 and parameters: {'subsample': 0.6477788309467406, 'learning_rate': 0.08076212617294082, 'dropout_rate': 0.8633905140318229, 'n_estimators': 258, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03758554130837055, 'min_weight_fraction_leaf': 0.13651865626965198, 'max_features': 'log2', 'min_impurity_decrease': 0.00027970894503354685, 'validation_fraction': 0.2247100576906358, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:26:14,209] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.6771049120933288, 'learning_rate': 0.07315741967522373, 'dropout_rate': 0.8445074715492404, 'n_estimators': 225, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4944517626406935, 'min_weight_fraction_leaf': 0.1184082493933322, 'max_features': 'log2', 'min_impurity_decrease': 7.750220976268371e-05, 'validation_fraction': 0.19451944185649944, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 18}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.6038961038961039
Fold 2 C-index: 0.734375
Fold 3 C-index: 0.5955882352941176
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6784037558685446
[I 2024-04-17 15:26:42,472] Trial 93 finished with value: 0.6532543067754664 and parameters: {'subsample': 0.6505500153064129, 'learning_rate': 0.08654339186340826, 'dropout_rate': 0.5745925865215216, 'n_estimators': 275, 'criterion': 'friedman_mse', 'ccp_alpha': 0.047807663978973236, 'min_weight_fraction_leaf': 0.136489495904176, 'max_features': 'log2', 'min_impurity_decrease': 0.0002641221564851182, 'validation_fraction': 0.2408847633168184, 'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:27:27,278] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.7012302994106524, 'learning_rate': 0.0873504637597572, 'dropout_rate': 0.5757406522578052, 'n_estimators': 368, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2587455822944095, 'min_weight_fraction_leaf': 0.13398291863789996, 'max_features': 'log2', 'min_impurity_decrease': 0.0005534052287963433, 'validation_fraction': 0.10270342506098418, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:27:50,635] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.5127618092801665, 'learning_rate': 0.08384427466663882, 'dropout_rate': 0.5058793394143734, 'n_estimators': 243, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7322974839526843, 'min_weight_fraction_leaf': 0.09262430293253904, 'max_features': 'log2', 'min_impurity_decrease': 0.00026275691727371505, 'validation_fraction': 0.2472767544216788, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 16}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:27:57,092] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.6536001293390361, 'learning_rate': 0.04349529821528992, 'dropout_rate': 0.9720052755589177, 'n_estimators': 267, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4988100514516513, 'min_weight_fraction_leaf': 0.10650916945086954, 'max_features': 'log2', 'min_impurity_decrease': 0.0004580089101794125, 'validation_fraction': 0.14860028600342867, 'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:28:34,708] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8201377508003859, 'learning_rate': 0.07484918411261762, 'dropout_rate': 0.4589748112758904, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2095747499942474, 'min_weight_fraction_leaf': 0.13909615068684844, 'max_features': 'log2', 'min_impurity_decrease': 7.164726662755731e-06, 'validation_fraction': 0.21607934102384135, 'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 12 with value: 0.7009449603314964.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:29:37,186] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.6065708061937459, 'learning_rate': 0.08041917263682534, 'dropout_rate': 0.6279615163020066, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 4.816291450322713, 'min_weight_fraction_leaf': 0.06066967160312424, 'max_features': 'log2', 'min_impurity_decrease': 0.00133622731461499, 'validation_fraction': 0.28071612591266815, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 12 with value: 0.7009449603314964.

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.6518987341772152

[I 2024-04-17 15:29:56,865] A new study created in memory with name: no-name-6a7bda6d-5f5c-453e-a5d9-241e60fd0570

Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 15:29:56,840] Trial 99 finished with value: 0.6540503130132586 and parameters: {'subsample': 0.5661700202304125, 'learning_rate': 0.06087517452189459, 'dropout_rate': 0.8763596048422365, 'n_estimators': 348, 'criterion': 'friedman_mse', 'ccp_alpha': 0.00450750764408793, 'min_weight_fraction_leaf': 0.12064410328201632, 'max_features': 'log2', 'min_impurity_decrease': 0.00340706496696601, 'validation_fraction': 0.22016450918063038, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 12 with value: 0.7009449603314964.


* Best trial for C-index:
 FrozenTrial(number=12, state=TrialState.COMPLETE, values=[0.7009449603314964], datetime_start=datetime.datetime(2024, 4, 17, 14, 32, 59, 233518), datetime_complete=datetime.datetime(2024, 4, 17, 14, 35, 4, 904132), params={'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=12, value=None)


* Best Score for C-index:
 0.7009449603314964

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:30:36,465] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:30:59,558] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:31:19,700] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:31:51,554] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:32:07,306] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:32:11,483] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:32:43,856] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:32:53,086] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:32:54,251] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21289961742980223
Fold 2 IBS: 0.220397807801691
Fold 3 IBS: 0.20379332289533966
Fold 4 IBS: 0.22348079897234485
Fold 5 IBS: 0.21719846241849655
[I 2024-04-17 15:34:22,848] Trial 9 finished with value: 0.21555400190353485 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247338226585746
Fold 5 IBS: 0.21791117307504204
[I 2024-04-17 15:36:35,034] Trial 10 finished with value: 0.2165470764383947 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 15:39:08,303] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21383808681402278
Fold 2 IBS: 0.22138677258044845
Fold 3 IBS: 0.20443908338231795
Fold 4 IBS: 0.2245553545604933
Fold 5 IBS: 0.21797484701863495
[I 2024-04-17 15:41:08,398] Trial 12 finished with value: 0.21643882887118346 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:42:02,916] Trial 13 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:43:20,414] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 15:44:42,257] Trial 15 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:45:33,079] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 15:47:18,375] Trial 17 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:49:56,853] Trial 18 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 15:50:02,407] Trial 19 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 15:50:54,072] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:52:45,983] Trial 21 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21423082304332894
Fold 2 IBS: 0.2215468348412658

Fold 3 IBS: 0.20440638818033266
Fold 4 IBS: 0.22461321358008154
Fold 5 IBS: 0.21776452807621957
[I 2024-04-17 15:54:30,069] Trial 22 finished with value: 0.21651235754424572 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:55:52,702] Trial 23 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 15:57:07,542] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 15:57:52,177] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-17 15:59:27,544] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:01:03,381] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:02:21,136] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:03:16,761] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:04:29,247] Trial 30 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:06:40,063] Trial 31 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:08:52,170] Trial 32 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:10:16,233] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:12:05,218] Trial 34 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 16:12:27,630] Trial 35 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:14:18,346] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:14:27,346] Trial 37 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:15:07,803] Trial 38 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:16:10,146] Trial 39 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:17:50,918] Trial 40 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:17:53,978] Trial 41 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.41224803024885526, 'learning_rate': 0.09721348083632597, 'dropout_rate': 0.9241643058958111, 'n_estimators': 129, 'criterion': 'squared_error', 'ccp_alpha': 2.2133753625306447, 'min_weight_fraction_leaf': 0.16640609118138397, 'max_features': 'auto', 'min_impurity_decrease': 0.0002542406113550312, 'validation_fraction': 0.7538708381604038, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21555400190353485.
Fold 1 IBS: 0.21236705544513235
Fold 2 IBS: 0.21875236257355538
Fold 3 IBS: 0.20239836545993783
Fold 4 IBS: 0.2211027457782356
Fold 5 IBS: 0.21551434757162988
[I 2024-04-17 16:18:01,006] Trial 42 finished with value: 0.2140269753656982 and parameters: {'subsample': 0.35070731793187043, 'learning_rate': 0.0889199108857109, 'dropout_rate': 0.7930596249666158, 'n_estimators': 170, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.13549403283131412, 'max_features': 'auto', 'min_impurity_decrease': 0.0003409042283428851, 'validation_fraction': 0.6733131712125798, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21302338675916235
Fold 2 IBS: 0.2204951673829029
Fold 3 IBS: 0.20340516890638374
Fold 4 IBS: 0.22299839737369245
Fold 5 IBS: 0.21712483023889287
[I 2024-04-17 16:18:06,092] Trial 43 finished with value: 0.21540939013220686 and parameters: {'subsample': 0.3231310200459757, 'learning_rate': 0.08532676992229105, 'dropout_rate': 0.9830655186757621, 'n_estimators': 221, 'criterion': 'squared_error', 'ccp_alpha': 0.09650145381128158, 'min_weight_fraction_leaf': 0.14110886582173582, 'max_features': 'auto', 'min_impurity_decrease': 0.0009050261380449993, 'validation_fraction': 0.6783049588847002, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:18:10,899] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.24849699972703826, 'learning_rate': 0.08739840427890608, 'dropout_rate': 0.9925112981171803, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 1.2571847442990605, 'min_weight_fraction_leaf': 0.13620319457876867, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.5876510269738553, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:18:16,474] Trial 45 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3318702090173651, 'learning_rate': 0.07586797225450398, 'dropout_rate': 0.8497789449117059, 'n_estimators': 173, 'criterion': 'squared_error', 'ccp_alpha': 0.5917691619818423, 'min_weight_fraction_leaf': 0.08618114150024489, 'max_features': 0.1, 'min_impurity_decrease': 0.0016598371209328522, 'validation_fraction': 0.6904472538348748, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21410998122699587
Fold 2 IBS: 0.22078360401293498
Fold 3 IBS: 0.20412160384104278
Fold 4 IBS: 0.22370345338648254
Fold 5 IBS: 0.21753088942319893
[I 2024-04-17 16:18:37,925] Trial 46 finished with value: 0.216049906378131 and parameters: {'subsample': 0.20300726471398084, 'learning_rate': 0.06556278818328212, 'dropout_rate': 0.6583556273751558, 'n_estimators': 269, 'criterion': 'squared_error', 'ccp_alpha': 0.035125731139090524, 'min_weight_fraction_leaf': 0.11903373712074695, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0053131293269521145, 'validation_fraction': 0.6381563767592378, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 10}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:18:53,154] Trial 47 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.20183494822608436, 'learning_rate': 0.06414735150009691, 'dropout_rate': 0.6707032744996033, 'n_estimators': 237, 'criterion': 'squared_error', 'ccp_alpha': 1.7366717899847348, 'min_weight_fraction_leaf': 0.05232229834701613, 'max_features': 'sqrt', 'min_impurity_decrease': 0.005672070865045171, 'validation_fraction': 0.6499098781754827, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:18:53,696] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.13006934817821147, 'learning_rate': 0.08612185554489837, 'dropout_rate': 0.6756325054993555, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 0.4425281303204141, 'min_weight_fraction_leaf': 0.10964817695475461, 'max_features': 'sqrt', 'min_impurity_decrease': 0.004062817881585773, 'validation_fraction': 0.5688864305777253, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 16}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 16:19:13,718] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.33602671953730506, 'learning_rate': 0.07824126069740887, 'dropout_rate': 0.5923973592579648, 'n_estimators': 257, 'criterion': 'friedman_mse', 'ccp_alpha': 6.690790687192069, 'min_weight_fraction_leaf': 0.14774984135060626, 'max_features': 'sqrt', 'min_impurity_decrease': 0.03704176040681205, 'validation_fraction': 0.6820188354768179, 'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 16}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-17 16:19:23,719] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.19385864173691314, 'learning_rate': 0.09215264236760946, 'dropout_rate': 0.733161412020914, 'n_estimators': 203, 'criterion': 'squared_error', 'ccp_alpha': 1.2508898705574658, 'min_weight_fraction_leaf': 0.22137337791033967, 'max_features': 'log2', 'min_impurity_decrease': 0.0017972027056153627, 'validation_fraction': 0.5182986243456443, 'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21323416776916915
Fold 2 IBS: 0.22027638750918743
Fold 3 IBS: 0.20378389610194775
Fold 4 IBS: 0.2231263929810833
Fold 5 IBS: 0.21703009653441707
[I 2024-04-17 16:19:35,914] Trial 51 finished with value: 0.21549018817916094 and parameters: {'subsample': 0.44466807647771756, 'learning_rate': 0.07411253330779041, 'dropout_rate': 0.852957455245773, 'n_estimators': 278, 'criterion': 'squared_error', 'ccp_alpha': 0.04662709874852084, 'min_weight_fraction_leaf': 0.033756448345697854, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005490171175145664, 'validation_fraction': 0.60644713330814, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 10}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-17 16:19:50,294] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.44026049288958646, 'learning_rate': 0.07102079283153598, 'dropout_rate': 0.8226439881838766, 'n_estimators': 284, 'criterion': 'squared_error', 'ccp_alpha': 0.4231397533219673, 'min_weight_fraction_leaf': 0.02162594546979682, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00048087482036303337, 'validation_fraction': 0.47429426477667547, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 10}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 16:19:55,053] Trial 53 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.5470632496005966, 'learning_rate': 0.08121404539850874, 'dropout_rate': 0.924340026246979, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.9469189653801711, 'min_weight_fraction_leaf': 0.05158469307244298, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00011526715555982563, 'validation_fraction': 0.6168848087885894, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 10}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:20:03,649] Trial 54 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.3688959255616368, 'learning_rate': 0.06182269383773231, 'dropout_rate': 0.8576989493652414, 'n_estimators': 223, 'criterion': 'squared_error', 'ccp_alpha': 0.36587462989090075, 'min_weight_fraction_leaf': 0.10803788143070453, 'max_features': 'sqrt', 'min_impurity_decrease': 0.01165267023362922, 'validation_fraction': 0.725390018130978, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 12}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21247032282389539
Fold 2 IBS: 0.21957502944154075

Fold 3 IBS: 0.20308486363078354
Fold 4 IBS: 0.222059251031902
Fold 5 IBS: 0.21620441591377326
[I 2024-04-17 16:20:06,141] Trial 55 finished with value: 0.214678776568379 and parameters: {'subsample': 0.28519589682406243, 'learning_rate': 0.07016205075701004, 'dropout_rate': 0.97279711727528, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.03767053942294234, 'min_weight_fraction_leaf': 0.19525087957715356, 'max_features': None, 'min_impurity_decrease': 0.0005802162560770055, 'validation_fraction': 0.5528235183342366, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 9}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 16:20:08,854] Trial 56 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.26773896940389147, 'learning_rate': 0.06921569697149174, 'dropout_rate': 0.8881309233047333, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.038045796431561, 'min_weight_fraction_leaf': 0.18820180543929732, 'max_features': None, 'min_impurity_decrease': 0.00038256951320814127, 'validation_fraction': 0.6258093429791418, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 9}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.2120846335150566
Fold 2 IBS: 0.21891874238265077
Fold 3 IBS: 0.20272547880855785
Fold 4 IBS: 0.22095782884796475
Fold 5 IBS: 0.21550024118162706
[I 2024-04-17 16:20:12,030] Trial 57 finished with value: 0.21403738494717142 and parameters: {'subsample': 0.5115552806382975, 'learning_rate': 0.09026835311917919, 'dropout_rate': 0.999883998488218, 'n_estimators': 177, 'criterion': 'squared_error', 'ccp_alpha': 0.0019565672907827097, 'min_weight_fraction_leaf': 0.14546770914101587, 'max_features': None, 'min_impurity_decrease': 0.0007887878519824229, 'validation_fraction': 0.4025335749287196, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 11}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:20:15,392] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5101245568251691, 'learning_rate': 0.09991388448994469, 'dropout_rate': 0.9990279523552323, 'n_estimators': 172, 'criterion': 'squared_error', 'ccp_alpha': 1.591129954664127, 'min_weight_fraction_leaf': 0.25730821949204663, 'max_features': None, 'min_impurity_decrease': 0.0007055188006025684, 'validation_fraction': 0.38233654755589974, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 11}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:20:18,817] Trial 59 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4501810759078234, 'learning_rate': 0.09014157432025599, 'dropout_rate': 0.9516313979969981, 'n_estimators': 142, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.15151576580198423, 'max_features': None, 'min_impurity_decrease': 0.0013426494479847767, 'validation_fraction': 0.5450270278789356, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 12}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:20:20,561] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.579007585807969, 'learning_rate': 0.08192675699738983, 'dropout_rate': 0.9660886118706938, 'n_estimators': 76, 'criterion': 'squared_error', 'ccp_alpha': 7.88888123252141, 'min_weight_fraction_leaf': 0.008728666661365764, 'max_features': None, 'min_impurity_decrease': 0.0028766216637662574, 'validation_fraction': 0.3036373435969706, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 8}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21326778548091258
Fold 2 IBS: 0.22053220854684613
Fold 3 IBS: 0.20380164536758041
Fold 4 IBS: 0.22336733226784056
Fold 5 IBS: 0.21719549082984269
[I 2024-04-17 16:20:26,298] Trial 61 finished with value: 0.21563289249860446 and parameters: {'subsample': 0.30449130256278656, 'learning_rate': 0.055355273587469084, 'dropout_rate': 0.8928309703218442, 'n_estimators': 186, 'criterion': 'squared_error', 'ccp_alpha': 0.08369853910029246, 'min_weight_fraction_leaf': 0.11508344687061026, 'max_features': None, 'min_impurity_decrease': 0.000210671641721914, 'validation_fraction': 0.45554589506530657, 'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 10}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20452163012450403
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:20:32,975] Trial 62 finished with value: 0.21658768518328042 and parameters: {'subsample': 0.3025120873150708, 'learning_rate': 0.07342016070525725, 'dropout_rate': 0.9141243082248947, 'n_estimators': 190, 'criterion': 'squared_error', 'ccp_alpha': 0.3085585847153933, 'min_weight_fraction_leaf': 0.05278741780689797, 'max_features': None, 'min_impurity_decrease': 0.0002283893553011328, 'validation_fraction': 0.4737898169099122, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.2125182088042726
Fold 2 IBS: 0.2199620020459421
Fold 3 IBS: 0.203221183693572
Fold 4 IBS: 0.22231704953397807
Fold 5 IBS: 0.21641688593171754
[I 2024-04-17 16:20:37,132] Trial 63 finished with value: 0.21488706600189644 and parameters: {'subsample': 0.37311864934327277, 'learning_rate': 0.05553009641281944, 'dropout_rate': 0.8888593565288243, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 0.017289191017379774, 'min_weight_fraction_leaf': 0.19527401204771364, 'max_features': None, 'min_impurity_decrease': 0.0001096717667633038, 'validation_fraction': 0.4352454741413325, 'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 13}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-17 16:20:42,729] Trial 64 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3685882966530518, 'learning_rate': 0.046188816933768084, 'dropout_rate': 0.7886267581004315, 'n_estimators': 154, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.19843850007623726, 'max_features': None, 'min_impurity_decrease': 0.00010239126912738009, 'validation_fraction': 0.41723077112625445, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 14}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:20:45,146] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.41880313860363394, 'learning_rate': 0.08265647858392106, 'dropout_rate': 0.9648142368443644, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 1.3445862634570662, 'min_weight_fraction_leaf': 0.22361796119697314, 'max_features': None, 'min_impurity_decrease': 0.0005542897353392731, 'validation_fraction': 0.5744804181846727, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:20:49,476] Trial 66 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.49624202157362907, 'learning_rate': 0.04172325575959995, 'dropout_rate': 0.871655087593486, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 0.343721568588375, 'min_weight_fraction_leaf': 0.18161893538206386, 'max_features': None, 'min_impurity_decrease': 0.0011338716061792269, 'validation_fraction': 0.2878946538079263, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 13}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 16:21:00,192] Trial 67 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5856185588208113, 'learning_rate': 0.09086172721039212, 'dropout_rate': 0.8164237696410702, 'n_estimators': 221, 'criterion': 'squared_error', 'ccp_alpha': 0.6256844698265926, 'min_weight_fraction_leaf': 0.26535372077198716, 'max_features': None, 'min_impurity_decrease': 7.565115546949388e-05, 'validation_fraction': 0.5122395551882285, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 15}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:21:03,103] Trial 68 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.2467985568162121, 'learning_rate': 0.057495825742752735, 'dropout_rate': 0.948897708223703, 'n_estimators': 80, 'criterion': 'squared_error', 'ccp_alpha': 0.836423863595016, 'min_weight_fraction_leaf': 0.2016865702702404, 'max_features': 1, 'min_impurity_decrease': 0.00014709785049637543, 'validation_fraction': 0.3435228185533405, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 11}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-17 16:21:06,571] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3683907667244704, 'learning_rate': 0.04925473793257295, 'dropout_rate': 0.983361051195631, 'n_estimators': 121, 'criterion': 'friedman_mse', 'ccp_alpha': 0.30419922755720963, 'min_weight_fraction_leaf': 0.15795422563312395, 'max_features': 'log2', 'min_impurity_decrease': 0.00227510239332475, 'validation_fraction': 0.6729773804596019, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 7}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.2135530885265667
Fold 2 IBS: 0.2204379862071457
Fold 3 IBS: 0.20371190217011262
Fold 4 IBS: 0.22282137338129246
Fold 5 IBS: 0.21698648591022543
[I 2024-04-17 16:21:12,553] Trial 70 finished with value: 0.2155021672390686 and parameters: {'subsample': 0.47174672965805187, 'learning_rate': 0.07756212042281545, 'dropout_rate': 0.8947828086582618, 'n_estimators': 159, 'criterion': 'squared_error', 'ccp_alpha': 0.010117163878638499, 'min_weight_fraction_leaf': 0.13364179423030076, 'max_features': 0.1, 'min_impurity_decrease': 0.0003544840078672131, 'validation_fraction': 0.24148167837250611, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 12}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21361539645297695
Fold 2 IBS: 0.22050074025949046
Fold 3 IBS: 0.20378280358653636
Fold 4 IBS: 0.22324690400390013
Fold 5 IBS: 0.21724383933425112
[I 2024-04-17 16:21:18,345] Trial 71 finished with value: 0.215677936727431 and parameters: {'subsample': 0.47138901086033913, 'learning_rate': 0.07864926394977687, 'dropout_rate': 0.9020513889972946, 'n_estimators': 161, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.13852368682483512, 'max_features': 0.1, 'min_impurity_decrease': 0.00031475948588749843, 'validation_fraction': 0.12515005750836544, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 12}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.2133016376946462
Fold 2 IBS: 0.2203105312501883
Fold 3 IBS: 0.2035827108714646
Fold 4 IBS: 0.22236028020462778
Fold 5 IBS: 0.21697892600466775
[I 2024-04-17 16:21:23,599] Trial 72 finished with value: 0.2153068172051189 and parameters: {'subsample': 0.5255362068628915, 'learning_rate': 0.07365043020696545, 'dropout_rate': 0.8141011559715361, 'n_estimators': 138, 'criterion': 'squared_error', 'ccp_alpha': 0.004930778059163435, 'min_weight_fraction_leaf': 0.09509698905679675, 'max_features': 0.1, 'min_impurity_decrease': 5.0891036603243695e-05, 'validation_fraction': 0.7120614628858244, 'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 15}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:21:28,524] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5103654975077662, 'learning_rate': 0.07362702236158067, 'dropout_rate': 0.8288576610980297, 'n_estimators': 135, 'criterion': 'squared_error', 'ccp_alpha': 0.7457615629726265, 'min_weight_fraction_leaf': 0.09793565863488876, 'max_features': 0.1, 'min_impurity_decrease': 6.190832907901987e-05, 'validation_fraction': 0.23641756111292292, 'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:21:31,534] Trial 74 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.39038865506106857, 'learning_rate': 0.08374918541053789, 'dropout_rate': 0.7885533433411948, 'n_estimators': 95, 'criterion': 'squared_error', 'ccp_alpha': 0.3244686894413328, 'min_weight_fraction_leaf': 0.06883839667635416, 'max_features': 0.1, 'min_impurity_decrease': 3.880773145201731e-05, 'validation_fraction': 0.17064029325824026, 'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 17}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21347063863618027
Fold 2 IBS: 0.21976102794878072
Fold 3 IBS: 0.20328761404924367
Fold 4 IBS: 0.22212251166675062
Fold 5 IBS: 0.21654104415594377
[I 2024-04-17 16:21:36,295] Trial 75 finished with value: 0.21503656729137982 and parameters: {'subsample': 0.4404072237856687, 'learning_rate': 0.08768623666788541, 'dropout_rate': 0.7161665686732999, 'n_estimators': 116, 'criterion': 'squared_error', 'ccp_alpha': 0.008766279109539603, 'min_weight_fraction_leaf': 0.12844710013372065, 'max_features': 0.1, 'min_impurity_decrease': 0.0008096076350961149, 'validation_fraction': 0.7095638378813804, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 14}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:21:38,034] Trial 76 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.42818585232165945, 'learning_rate': 0.08788907212896865, 'dropout_rate': 0.756456190966956, 'n_estimators': 53, 'criterion': 'squared_error', 'ccp_alpha': 1.8760975866788443, 'min_weight_fraction_leaf': 0.09966712300105006, 'max_features': 0.1, 'min_impurity_decrease': 0.0009103627320844871, 'validation_fraction': 0.7114551948072033, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 14}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676

Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:21:41,785] Trial 77 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5357913465602108, 'learning_rate': 0.09509164545595872, 'dropout_rate': 0.8459672741379245, 'n_estimators': 117, 'criterion': 'squared_error', 'ccp_alpha': 1.0998319625381408, 'min_weight_fraction_leaf': 0.12634401560860808, 'max_features': 0.1, 'min_impurity_decrease': 0.0005815784991320142, 'validation_fraction': 0.7883874326786836, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 15}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:21:58,234] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3505708388377867, 'learning_rate': 0.09232934356399627, 'dropout_rate': 0.7064261992556284, 'n_estimators': 241, 'criterion': 'squared_error', 'ccp_alpha': 1.4069544530658797, 'min_weight_fraction_leaf': 0.17625429093645273, 'max_features': 0.1, 'min_impurity_decrease': 1.9076132907505136e-05, 'validation_fraction': 0.5551947365374761, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 13}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 16:22:08,365] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4036409903049816, 'learning_rate': 0.08030642230759226, 'dropout_rate': 0.9354395501769928, 'n_estimators': 300, 'criterion': 'squared_error', 'ccp_alpha': 0.556504773922715, 'min_weight_fraction_leaf': 0.1597211921392478, 'max_features': None, 'min_impurity_decrease': 0.0001455746253506426, 'validation_fraction': 0.7347578294643111, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 16}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:22:16,562] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.30999641663270167, 'learning_rate': 0.06866254006727997, 'dropout_rate': 0.8054489851974701, 'n_estimators': 202, 'criterion': 'squared_error', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.07098378926612457, 'max_features': 0.1, 'min_impurity_decrease': 0.00043860272739027503, 'validation_fraction': 0.4190220573640747, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 17}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21363073791486997
Fold 2 IBS: 0.22058050553005382
Fold 3 IBS: 0.20377395172532642
Fold 4 IBS: 0.22330647301910436
Fold 5 IBS: 0.21720975225522307
[I 2024-04-17 16:22:22,221] Trial 81 finished with value: 0.2157002840889155 and parameters: {'subsample': 0.4704045630129737, 'learning_rate': 0.07505426720977328, 'dropout_rate': 0.8817593622083013, 'n_estimators': 182, 'criterion': 'squared_error', 'ccp_alpha': 0.02600052444611894, 'min_weight_fraction_leaf': 0.14103187131269806, 'max_features': 0.1, 'min_impurity_decrease': 0.00030001253381256257, 'validation_fraction': 0.5964000439698339, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 14}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-17 16:22:25,933] Trial 82 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.48371666945699127, 'learning_rate': 0.08434329610660093, 'dropout_rate': 0.9653291206549236, 'n_estimators': 163, 'criterion': 'squared_error', 'ccp_alpha': 0.29610453027488637, 'min_weight_fraction_leaf': 0.12405942241301957, 'max_features': 0.1, 'min_impurity_decrease': 0.0010561038940215, 'validation_fraction': 0.6681453129943384, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 11}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:22:33,217] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4538478856905483, 'learning_rate': 0.07241568125404713, 'dropout_rate': 0.8674471919194727, 'n_estimators': 144, 'criterion': 'squared_error', 'ccp_alpha': 0.7193130400245684, 'min_weight_fraction_leaf': 0.09940224933718715, 'max_features': 0.1, 'min_impurity_decrease': 0.00019013078610243545, 'validation_fraction': 0.8319046751482848, 'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 12}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:22:36,345] Trial 84 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5179690920534118, 'learning_rate': 0.08825611530005263, 'dropout_rate': 0.9102202842589198, 'n_estimators': 109, 'criterion': 'squared_error', 'ccp_alpha': 0.26065674008658557, 'min_weight_fraction_leaf': 0.03710746644896608, 'max_features': 0.1, 'min_impurity_decrease': 7.65572475366024e-05, 'validation_fraction': 0.7154236424490046, 'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:22:45,418] Trial 85 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5718194253054419, 'learning_rate': 0.06270695695517213, 'dropout_rate': 0.8366747342445848, 'n_estimators': 219, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0637247669291705, 'min_weight_fraction_leaf': 0.19175173333029477, 'max_features': 1, 'min_impurity_decrease': 0.0007321926999053314, 'validation_fraction': 0.39201738009456427, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 12}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:22:52,377] Trial 86 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4249491957783117, 'learning_rate': 0.07695400191141402, 'dropout_rate': 0.7733490931790423, 'n_estimators': 160, 'criterion': 'squared_error', 'ccp_alpha': 0.4748348053420634, 'min_weight_fraction_leaf': 0.16517397511566376, 'max_features': None, 'min_impurity_decrease': 0.00040121314940430694, 'validation_fraction': 0.24357301443038443, 'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 14}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21373563271406953
Fold 2 IBS: 0.22048157419716008
Fold 3 IBS: 0.2037267682203083
Fold 4 IBS: 0.22303170698269073
Fold 5 IBS: 0.21739809016951547
[I 2024-04-17 16:22:55,110] Trial 87 finished with value: 0.21567475445674883 and parameters: {'subsample': 0.38348783834226524, 'learning_rate': 0.0793547597378264, 'dropout_rate': 0.7272102647058043, 'n_estimators': 89, 'criterion': 'squared_error', 'ccp_alpha': 0.017246795895510786, 'min_weight_fraction_leaf': 0.13236333491617097, 'max_features': 0.1, 'min_impurity_decrease': 0.0014231297685165889, 'validation_fraction': 0.1693397043647827, 'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:22:57,972] Trial 88 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.2356204199087344, 'learning_rate': 0.08572931850629258, 'dropout_rate': 0.9375454683955085, 'n_estimators': 134, 'criterion': 'squared_error', 'ccp_alpha': 0.8300633961611433, 'min_weight_fraction_leaf': 0.14572184662388235, 'max_features': 'log2', 'min_impurity_decrease': 4.31679989671411e-05, 'validation_fraction': 0.7551454721856719, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 13}. Best is trial 42 with value: 0.2140269753656982.

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:22:59,200] Trial 89 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.28396267269938413, 'learning_rate': 0.09422611340750953, 'dropout_rate': 0.9812607710537841, 'n_estimators': 60, 'criterion': 'squared_error', 'ccp_alpha': 5.986001210354111, 'min_weight_fraction_leaf': 0.09373826202704161, 'max_features': None, 'min_impurity_decrease': 0.0024778007971021196, 'validation_fraction': 0.4942203533463335, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 15}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:23:05,530] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.34315707421518604, 'learning_rate': 0.0714208876769115, 'dropout_rate': 0.8958643066482037, 'n_estimators': 196, 'criterion': 'squared_error', 'ccp_alpha': 4.2432534087318325, 'min_weight_fraction_leaf': 0.17839980873796596, 'max_features': 'auto', 'min_impurity_decrease': 0.00012570024782537014, 'validation_fraction': 0.6998593704236655, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 10}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:23:10,443] Trial 91 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5507384139289075, 'learning_rate': 0.06813771862992257, 'dropout_rate': 0.639177636011812, 'n_estimators': 111, 'criterion': 'squared_error', 'ccp_alpha': 0.2912928045662663, 'min_weight_fraction_leaf': 0.2443729408200548, 'max_features': 'auto', 'min_impurity_decrease': 0.000610050864074699, 'validation_fraction': 0.6097029089873313, 'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:23:18,802] Trial 92 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6246551418792153, 'learning_rate': 0.08932828865905112, 'dropout_rate': 0.5714262605395246, 'n_estimators': 129, 'criterion': 'squared_error', 'ccp_alpha': 0.5937696015199216, 'min_weight_fraction_leaf': 0.20821682842735198, 'max_features': 'auto', 'min_impurity_decrease': 0.0002646927518569625, 'validation_fraction': 0.6586984296854638, 'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21382202791716384
Fold 2 IBS: 0.2215100170086786
Fold 3 IBS: 0.2044823687989679
Fold 4 IBS: 0.2246430524349763
Fold 5 IBS: 0.2180728346747391
[I 2024-04-17 16:23:24,452] Trial 93 finished with value: 0.21650606016690516 and parameters: {'subsample': 0.5894360760855065, 'learning_rate': 0.07644221461500457, 'dropout_rate': 0.8034847980077001, 'n_estimators': 166, 'criterion': 'squared_error', 'ccp_alpha': 0.1654677445504837, 'min_weight_fraction_leaf': 0.2772836093463316, 'max_features': 'auto', 'min_impurity_decrease': 0.010232842586686604, 'validation_fraction': 0.633862605716626, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:23:32,550] Trial 94 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6601719379374948, 'learning_rate': 0.08588087375934735, 'dropout_rate': 0.45228686233395415, 'n_estimators': 141, 'criterion': 'squared_error', 'ccp_alpha': 0.5296746287854353, 'min_weight_fraction_leaf': 0.2338199679846539, 'max_features': 'auto', 'min_impurity_decrease': 0.0008837203061990415, 'validation_fraction': 0.544120095808288, 'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:23:36,733] Trial 95 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6048174342537938, 'learning_rate': 0.05250138378992597, 'dropout_rate': 0.9532511078869237, 'n_estimators': 187, 'criterion': 'squared_error', 'ccp_alpha': 0.9561607223624694, 'min_weight_fraction_leaf': 0.0021904102718047214, 'max_features': 0.1, 'min_impurity_decrease': 0.0032614524269182358, 'validation_fraction': 0.5984602035656514, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:24:11,249] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4927912853138996, 'learning_rate': 0.06143096328684317, 'dropout_rate': 0.5049016318515295, 'n_estimators': 327, 'criterion': 'squared_error', 'ccp_alpha': 0.2069188078264839, 'min_weight_fraction_leaf': 0.3146087285283485, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0018176543409729549, 'validation_fraction': 0.6963880623685521, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 2}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:24:18,259] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4416099817015848, 'learning_rate': 0.06699119880094322, 'dropout_rate': 0.8589265165944443, 'n_estimators': 212, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4809477915615623, 'min_weight_fraction_leaf': 0.11776293456430083, 'max_features': None, 'min_impurity_decrease': 0.0003426033467208877, 'validation_fraction': 0.6447436835662406, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:24:24,102] Trial 98 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3265620062539155, 'learning_rate': 0.09774225011064523, 'dropout_rate': 0.9212638432930371, 'n_estimators': 229, 'criterion': 'squared_error', 'ccp_alpha': 1.1558162384791095, 'min_weight_fraction_leaf': 0.083645633119833, 'max_features': 'auto', 'min_impurity_decrease': 0.00017449971388743598, 'validation_fraction': 0.08209633948082096, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 14}. Best is trial 42 with value: 0.2140269753656982.
Fold 1 IBS: 0.21367511721031107
Fold 2 IBS: 0.22057216081116154
Fold 3 IBS: 0.20387850516813327
Fold 4 IBS: 0.2235522251064066
Fold 5 IBS: 0.21749827828801818
[I 2024-04-17 16:24:27,138] Trial 99 finished with value: 0.21583525731680614 and parameters: {'subsample': 0.35661958503382174, 'learning_rate': 0.08114550105389129, 'dropout_rate': 0.9746573244803898, 'n_estimators': 152, 'criterion': 'squared_error', 'ccp_alpha': 0.004367620204038796, 'min_weight_fraction_leaf': 0.15549747451851947, 'max_features': 1, 'min_impurity_decrease': 0.0005352617473147676, 'validation_fraction': 0.7917183714936656, 'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 42 with value: 0.2140269753656982.


* Best trial for IBS:
 FrozenTrial(number=42, state=TrialState.COMPLETE, values=[0.2140269753656982], datetime_start=datetime.datetime(2024, 4, 17, 16, 17, 53, 986315), datetime_complete=datetime.datetime(2024, 4, 17, 16, 18, 1, 5055), params={'subsample': 0.35070731793187043, 'learning_rate': 0.0889199108857109, 'dropout_rate': 0.7930596249666158, 'n_estimators': 170, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.13549403283131412, 'max_features': 'auto', 'min_impurity_decrease': 0.0003409042283428851, 'validation_fraction': 0.6733131712125798, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 1}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=42, value=None)


* Best Score for IBS:
 0.2140269753656982

In [65]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [66]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.701
train_ibs:  0.214

#### Test

In [67]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [68]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.058133567268478875,
                                 criterion='squared_error',
                                 dropout_rate=0.2527776031497929,
                                 learning_rate=0.0012227187192111223,
                                 max_depth=1, max_features='auto',
                                 max_leaf_nodes=20,
                                 min_impurity_decrease=1.5094636128058346e-06,
                                 min_samples_leaf=15, min_samples_split=20,
                                 min_weight_fraction_leaf=0.2151989029549357,
                                 n_estimators=489, random_state=123,
                                 subsample=0.873850481285158,
                                 validation_fraction=0.9945176333416724)

C-index score: 0.583

GradientBoostingSurvivalAnalysis(ccp_alpha=0.0025776361420084756,
                                 criterion='squared_error',
                                 dropout_rate=0.7930596249666158,
                                 learning_rate=0.0889199108857109, max_depth=1,
                                 max_features='auto', max_leaf_nodes=13,
                                 min_impurity_decrease=0.0003409042283428851,
                                 min_samples_leaf=11, min_samples_split=17,
                                 min_weight_fraction_leaf=0.13549403283131412,
                                 n_estimators=170, random_state=123,
                                 subsample=0.35070731793187043,
                                 validation_fraction=0.6733131712125798)

IBS: 0.22

In [69]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [70]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [71]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 16:24:53,983] A new study created in memory with name: no-name-21fba87b-a508-427d-ac80-d4432bc785f6

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:24:55,696] Trial 0 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:25:08,884] Trial 1 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6818827456832424.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:25:11,075] Trial 2 finished with value: 0.6835924284055832 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6835924284055832.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:25:14,086] Trial 3 finished with value: 0.685290607677292 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:25:19,014] Trial 4 finished with value: 0.6759722485730059 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:25:24,723] Trial 5 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:25:27,147] Trial 6 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:25:27,633] Trial 7 finished with value: 0.6746157479750681 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:25:30,808] Trial 8 finished with value: 0.6798073700784549 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:25:39,469] Trial 9 finished with value: 0.680651251934995 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:25:45,685] Trial 10 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.10867980814121556, 'n_estimators': 299, 'learning_rate': 0.09279671898160717}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 16:25:47,285] Trial 11 finished with value: 0.6667972182470939 and parameters: {'subsample': 0.1795750652194426, 'dropout_rate': 0.10580803679784617, 'n_estimators': 112, 'learning_rate': 0.08422813202882692}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:25:49,216] Trial 12 finished with value: 0.6798073700784549 and parameters: {'subsample': 0.5633377352680137, 'dropout_rate': 0.6475328937135156, 'n_estimators': 154, 'learning_rate': 0.07678177586157726}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 16:25:49,481] Trial 13 finished with value: 0.6628623687679904 and parameters: {'subsample': 0.34368472607946177, 'dropout_rate': 0.25833211803671624, 'n_estimators': 15, 'learning_rate': 0.09787137975576479}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:25:55,642] Trial 14 finished with value: 0.6817681543921805 and parameters: {'subsample': 0.5653316479631305, 'dropout_rate': 0.7248360093802153, 'n_estimators': 357, 'learning_rate': 0.0025916531369806137}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.6176470588235294
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6572769953051644
[I 2024-04-17 16:25:59,674] Trial 15 finished with value: 0.6579880575789855 and parameters: {'subsample': 0.1099871062179299, 'dropout_rate': 0.242092283972966, 'n_estimators': 233, 'learning_rate': 0.07488286755529167}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:26:00,559] Trial 16 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8679250280350448, 'dropout_rate': 0.4014363979414328, 'n_estimators': 77, 'learning_rate': 0.08820363883892024}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:26:06,363] Trial 17 finished with value: 0.681566028087113 and parameters: {'subsample': 0.4245336871732628, 'dropout_rate': 0.7574099126710454, 'n_estimators': 332, 'learning_rate': 0.07034672050620883}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:26:08,369] Trial 18 finished with value: 0.6809023535263796 and parameters: {'subsample': 0.638246795227134, 'dropout_rate': 0.5396578860589929, 'n_estimators': 153, 'learning_rate': 0.03707183063684802}. Best is trial 3 with value: 0.685290607677292.

Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 16:26:16,045] Trial 19 finished with value: 0.6767159078821401 and parameters: {'subsample': 0.29012679930776175, 'dropout_rate': 0.9852143001156547, 'n_estimators': 431, 'learning_rate': 0.08210359937920125}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:26:21,310] Trial 20 finished with value: 0.677983096065052 and parameters: {'subsample': 0.44973550553153746, 'dropout_rate': 0.19350037184585095, 'n_estimators': 278, 'learning_rate': 0.06348170552170027}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:26:22,687] Trial 21 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.667372178807538, 'dropout_rate': 0.36603272989428826, 'n_estimators': 112, 'learning_rate': 0.05516383832376384}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:26:24,130] Trial 22 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.7960419673182305, 'dropout_rate': 0.3539915665574968, 'n_estimators': 120, 'learning_rate': 0.06250695787201324}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:26:26,941] Trial 23 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.6063567872725675, 'dropout_rate': 0.47887634861607953, 'n_estimators': 188, 'learning_rate': 0.07688060266264754}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:26:29,934] Trial 24 finished with value: 0.6798073700784549 and parameters: {'subsample': 0.5865885943550803, 'dropout_rate': 0.5020521283337119, 'n_estimators': 202, 'learning_rate': 0.07843305822424082}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:26:33,658] Trial 25 finished with value: 0.6798073700784549 and parameters: {'subsample': 0.5053446410165011, 'dropout_rate': 0.6092923496256029, 'n_estimators': 239, 'learning_rate': 0.09925386589416407}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:26:36,028] Trial 26 finished with value: 0.6813909580591018 and parameters: {'subsample': 0.3924282214545649, 'dropout_rate': 0.4440649262457573, 'n_estimators': 173, 'learning_rate': 0.07011494417593515}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:26:41,603] Trial 27 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.6197521950022414, 'dropout_rate': 0.3060837787360696, 'n_estimators': 300, 'learning_rate': 0.08017847706620543}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:26:42,405] Trial 28 finished with value: 0.6809242725356404 and parameters: {'subsample': 0.5161450412501711, 'dropout_rate': 0.18804677832052086, 'n_estimators': 65, 'learning_rate': 0.09231293760058511}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:26:45,342] Trial 29 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8380245105926873, 'dropout_rate': 0.45350868086867785, 'n_estimators': 208, 'learning_rate': 0.0447877315763909}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:26:46,934] Trial 30 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.6962630201185729, 'dropout_rate': 0.597261944110978, 'n_estimators': 133, 'learning_rate': 0.06130486663588129}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:26:52,546] Trial 31 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.6187725536932623, 'dropout_rate': 0.3248983076116168, 'n_estimators': 302, 'learning_rate': 0.08382719550880821}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:26:56,512] Trial 32 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.6056168109838697, 'dropout_rate': 0.28573224989166746, 'n_estimators': 239, 'learning_rate': 0.07152820566341186}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:27:01,140] Trial 33 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.732016975088592, 'dropout_rate': 0.18929573521650445, 'n_estimators': 263, 'learning_rate': 0.09100790585604185}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:27:09,827] Trial 34 finished with value: 0.6826610115350376 and parameters: {'subsample': 0.43375535505076457, 'dropout_rate': 0.41505341602344753, 'n_estimators': 394, 'learning_rate': 0.07793989395721299}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:27:12,612] Trial 35 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.5569157191573885, 'dropout_rate': 0.3018810977786677, 'n_estimators': 188, 'learning_rate': 0.06425431080414915}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:27:18,140] Trial 36 finished with value: 0.6809023535263796 and parameters: {'subsample': 0.6450729471075142, 'dropout_rate': 0.5106134876297652, 'n_estimators': 311, 'learning_rate': 0.08606496987545095}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:27:23,079] Trial 37 finished with value: 0.6817681543921805 and parameters: {'subsample': 0.5281749327154567, 'dropout_rate': 0.22419700447180674, 'n_estimators': 273, 'learning_rate': 0.05811248339099579}. Best is trial 3 with value: 0.685290607677292.

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:27:25,606] Trial 38 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.7039903023611291, 'dropout_rate': 0.14386816981770942, 'n_estimators': 169, 'learning_rate': 0.06713918754706011}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:27:28,916] Trial 39 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.7663158695971513, 'dropout_rate': 0.33285705454120956, 'n_estimators': 220, 'learning_rate': 0.01715036845928685}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 16:27:30,421] Trial 40 finished with value: 0.6767429641591964 and parameters: {'subsample': 0.31730828518004417, 'dropout_rate': 0.46733862273672266, 'n_estimators': 95, 'learning_rate': 0.04708154395285013}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:27:36,065] Trial 41 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.6230064622726968, 'dropout_rate': 0.3148196375868446, 'n_estimators': 296, 'learning_rate': 0.08308040602674299}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:27:44,729] Trial 42 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.5933488605206542, 'dropout_rate': 0.3820789039517273, 'n_estimators': 394, 'learning_rate': 0.07445458331927284}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:27:51,965] Trial 43 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.4606432488462373, 'dropout_rate': 0.2786479783062687, 'n_estimators': 333, 'learning_rate': 0.0801991442813798}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:27:56,338] Trial 44 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.5348095844660177, 'dropout_rate': 0.4340397394120413, 'n_estimators': 251, 'learning_rate': 0.08616226822658307}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:27:58,243] Trial 45 finished with value: 0.6817681543921805 and parameters: {'subsample': 0.666837199857335, 'dropout_rate': 0.595231610987382, 'n_estimators': 141, 'learning_rate': 0.09506674568274746}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:28:01,583] Trial 46 finished with value: 0.6798563453647719 and parameters: {'subsample': 0.3807668512890516, 'dropout_rate': 0.14648424644002478, 'n_estimators': 195, 'learning_rate': 0.0733443829767497}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 16:28:08,034] Trial 47 finished with value: 0.6731600321371356 and parameters: {'subsample': 0.21976423116418442, 'dropout_rate': 0.3374130310457442, 'n_estimators': 316, 'learning_rate': 0.08898267827090169}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:28:14,795] Trial 48 finished with value: 0.6817681543921805 and parameters: {'subsample': 0.48891631968092664, 'dropout_rate': 0.5018315422341659, 'n_estimators': 356, 'learning_rate': 0.06836286397965652}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:28:20,178] Trial 49 finished with value: 0.6817681543921805 and parameters: {'subsample': 0.5695570911186879, 'dropout_rate': 0.22067572971153276, 'n_estimators': 288, 'learning_rate': 0.08106134303716513}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:28:23,319] Trial 50 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9551649622007263, 'dropout_rate': 0.5571547785822807, 'n_estimators': 222, 'learning_rate': 0.05079062021594498}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:28:27,802] Trial 51 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.6054944676858314, 'dropout_rate': 0.28182083618940296, 'n_estimators': 251, 'learning_rate': 0.07111908423599263}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:28:30,026] Trial 52 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.6220572017819829, 'dropout_rate': 0.3887451337215885, 'n_estimators': 163, 'learning_rate': 0.07587933970953503}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:28:34,853] Trial 53 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.6980710586407621, 'dropout_rate': 0.1397087664288492, 'n_estimators': 261, 'learning_rate': 0.05812877448698524}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:28:38,378] Trial 54 finished with value: 0.6809242725356404 and parameters: {'subsample': 0.5459051320198332, 'dropout_rate': 0.2446648314616106, 'n_estimators': 226, 'learning_rate': 0.08325409585686223}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:28:40,968] Trial 55 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.6482273932744342, 'dropout_rate': 0.3043202923113223, 'n_estimators': 190, 'learning_rate': 0.06642592382340154}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:28:44,663] Trial 56 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.4787679191151204, 'dropout_rate': 0.4160182435503422, 'n_estimators': 241, 'learning_rate': 0.0722357767585615}. Best is trial 3 with value: 0.685290607677292.

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:28:51,109] Trial 57 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.763164039562245, 'dropout_rate': 0.3415405018395574, 'n_estimators': 337, 'learning_rate': 0.07865387944100838}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:04,726] Trial 58 finished with value: 0.6817681543921805 and parameters: {'subsample': 0.5835260048785766, 'dropout_rate': 0.10298344023638806, 'n_estimators': 498, 'learning_rate': 0.08786981290657159}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:06,724] Trial 59 finished with value: 0.6835924284055832 and parameters: {'subsample': 0.5099367261455727, 'dropout_rate': 0.26726818616272724, 'n_estimators': 150, 'learning_rate': 0.09455925686030078}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:07,801] Trial 60 finished with value: 0.6797907293600272 and parameters: {'subsample': 0.4138516219497396, 'dropout_rate': 0.1764206104382695, 'n_estimators': 90, 'learning_rate': 0.09296321490969779}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:09,834] Trial 61 finished with value: 0.680651251934995 and parameters: {'subsample': 0.5204119570932995, 'dropout_rate': 0.2599697783209648, 'n_estimators': 151, 'learning_rate': 0.09890058565388585}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:12,262] Trial 62 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.5999966617909035, 'dropout_rate': 0.21031894128840656, 'n_estimators': 175, 'learning_rate': 0.09524835361847858}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:13,812] Trial 63 finished with value: 0.681544109077852 and parameters: {'subsample': 0.4607479239232764, 'dropout_rate': 0.28423802172986995, 'n_estimators': 125, 'learning_rate': 0.08428677255032978}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:16,874] Trial 64 finished with value: 0.6835924284055832 and parameters: {'subsample': 0.5011668927166437, 'dropout_rate': 0.3643887110810526, 'n_estimators': 213, 'learning_rate': 0.07598390742974098}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:17,342] Trial 65 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.4948760774015971, 'dropout_rate': 0.35601807750263204, 'n_estimators': 35, 'learning_rate': 0.07580836911442358}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:20,024] Trial 66 finished with value: 0.6835924284055832 and parameters: {'subsample': 0.5554234397254031, 'dropout_rate': 0.4718660486655542, 'n_estimators': 199, 'learning_rate': 0.08937919040626628}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:22,891] Trial 67 finished with value: 0.6767786585938611 and parameters: {'subsample': 0.4096809973919435, 'dropout_rate': 0.538191234195087, 'n_estimators': 207, 'learning_rate': 0.09002545106611622}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:24,653] Trial 68 finished with value: 0.677644459459662 and parameters: {'subsample': 0.3525849296382457, 'dropout_rate': 0.4293847767908171, 'n_estimators': 144, 'learning_rate': 0.09499534704354534}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:27,113] Trial 69 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.5514213326112003, 'dropout_rate': 0.46258815859314956, 'n_estimators': 185, 'learning_rate': 0.08021755383279987}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:29,083] Trial 70 finished with value: 0.680651251934995 and parameters: {'subsample': 0.45248968989367067, 'dropout_rate': 0.698386166108241, 'n_estimators': 166, 'learning_rate': 0.088143725095398}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:32,337] Trial 71 finished with value: 0.6835924284055832 and parameters: {'subsample': 0.5239437059877121, 'dropout_rate': 0.3844943177047123, 'n_estimators': 218, 'learning_rate': 0.08559928043602821}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:35,286] Trial 72 finished with value: 0.6835924284055832 and parameters: {'subsample': 0.5046098977332493, 'dropout_rate': 0.48915052676215426, 'n_estimators': 207, 'learning_rate': 0.0779026719512303}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:38,197] Trial 73 finished with value: 0.6835924284055832 and parameters: {'subsample': 0.5143285837169232, 'dropout_rate': 0.4897295709766447, 'n_estimators': 210, 'learning_rate': 0.08652001828713105}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:41,353] Trial 74 finished with value: 0.6798073700784549 and parameters: {'subsample': 0.5042033412071256, 'dropout_rate': 0.5650002131033008, 'n_estimators': 204, 'learning_rate': 0.09636765694772595}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:44,713] Trial 75 finished with value: 0.680651251934995 and parameters: {'subsample': 0.47528935902723296, 'dropout_rate': 0.5154917592158309, 'n_estimators': 219, 'learning_rate': 0.09149969949618142}. Best is trial 3 with value: 0.685290607677292.

Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:48,406] Trial 76 finished with value: 0.6798073700784549 and parameters: {'subsample': 0.4366656158555708, 'dropout_rate': 0.48748361925745526, 'n_estimators': 235, 'learning_rate': 0.08597573328838677}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:50,405] Trial 77 finished with value: 0.6835924284055832 and parameters: {'subsample': 0.523671066304713, 'dropout_rate': 0.3761096589684117, 'n_estimators': 154, 'learning_rate': 0.029827647172968506}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:53,482] Trial 78 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.5710027294699892, 'dropout_rate': 0.4021464650828461, 'n_estimators': 211, 'learning_rate': 0.09231478660893762}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:55,039] Trial 79 finished with value: 0.6813419827727847 and parameters: {'subsample': 0.37898661890392304, 'dropout_rate': 0.5221384018433558, 'n_estimators': 132, 'learning_rate': 0.07759078251395858}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:57,480] Trial 80 finished with value: 0.6835924284055832 and parameters: {'subsample': 0.5460768682823519, 'dropout_rate': 0.45409449858121087, 'n_estimators': 180, 'learning_rate': 0.09991058510656695}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:29:58,804] Trial 81 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.5223910781830629, 'dropout_rate': 0.37779493665958497, 'n_estimators': 109, 'learning_rate': 0.020627527568966752}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:00,880] Trial 82 finished with value: 0.6835924284055832 and parameters: {'subsample': 0.5088619883285522, 'dropout_rate': 0.4815558405473531, 'n_estimators': 156, 'learning_rate': 0.03716222560820146}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:03,288] Trial 83 finished with value: 0.680651251934995 and parameters: {'subsample': 0.4746482589598728, 'dropout_rate': 0.8379931546434596, 'n_estimators': 198, 'learning_rate': 0.04141072046999219}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:05,693] Trial 84 finished with value: 0.6835924284055832 and parameters: {'subsample': 0.5337022551326389, 'dropout_rate': 0.4348112174734818, 'n_estimators': 175, 'learning_rate': 0.012952645712495638}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:08,504] Trial 85 finished with value: 0.6815170528007958 and parameters: {'subsample': 0.44070801461626546, 'dropout_rate': 0.40624398961075375, 'n_estimators': 192, 'learning_rate': 0.08140186499491554}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:11,842] Trial 86 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.5652265206493202, 'dropout_rate': 0.48656754097262767, 'n_estimators': 230, 'learning_rate': 0.030125414298292744}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:13,830] Trial 87 finished with value: 0.6835924284055832 and parameters: {'subsample': 0.49735266876195916, 'dropout_rate': 0.36528044617922684, 'n_estimators': 156, 'learning_rate': 0.007190805934355407}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:16,664] Trial 88 finished with value: 0.6798073700784549 and parameters: {'subsample': 0.4662242542489278, 'dropout_rate': 0.5877703043222041, 'n_estimators': 213, 'learning_rate': 0.08561927634728315}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:18,434] Trial 89 finished with value: 0.6778465857647294 and parameters: {'subsample': 0.4222032879676648, 'dropout_rate': 0.6436774805198799, 'n_estimators': 138, 'learning_rate': 0.025056796383218}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:22,263] Trial 90 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.5855988120641501, 'dropout_rate': 0.4426221285300397, 'n_estimators': 248, 'learning_rate': 0.06518989749555333}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:24,747] Trial 91 finished with value: 0.6835924284055832 and parameters: {'subsample': 0.5424022568824938, 'dropout_rate': 0.4577195962320949, 'n_estimators': 180, 'learning_rate': 0.09963495159379607}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:27,340] Trial 92 finished with value: 0.6826120362487205 and parameters: {'subsample': 0.5159046736777665, 'dropout_rate': 0.41313451667073453, 'n_estimators': 181, 'learning_rate': 0.09763912849112785}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:30,345] Trial 93 finished with value: 0.6835924284055832 and parameters: {'subsample': 0.5556150423237545, 'dropout_rate': 0.38142393531669605, 'n_estimators': 201, 'learning_rate': 0.09336028362208391}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:32,749] Trial 94 finished with value: 0.6798073700784549 and parameters: {'subsample': 0.4935612338074942, 'dropout_rate': 0.5306326676271426, 'n_estimators': 167, 'learning_rate': 0.09030174203794443}. Best is trial 3 with value: 0.685290607677292.

Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:35,959] Trial 95 finished with value: 0.6835924284055832 and parameters: {'subsample': 0.5328250867403286, 'dropout_rate': 0.4979538933663357, 'n_estimators': 218, 'learning_rate': 0.07322014463628317}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:37,885] Trial 96 finished with value: 0.6805856359302502 and parameters: {'subsample': 0.40063832299597363, 'dropout_rate': 0.46864006625246213, 'n_estimators': 150, 'learning_rate': 0.08791879465920027}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:39,942] Trial 97 finished with value: 0.6827485465490433 and parameters: {'subsample': 0.640459544752755, 'dropout_rate': 0.45245588083445903, 'n_estimators': 163, 'learning_rate': 0.06926468341598366}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:43,899] Trial 98 finished with value: 0.6798073700784549 and parameters: {'subsample': 0.570026761128418, 'dropout_rate': 0.5736716127617499, 'n_estimators': 260, 'learning_rate': 0.09754411449482195}. Best is trial 3 with value: 0.685290607677292.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6919831223628692

[I 2024-04-17 16:30:45,365] A new study created in memory with name: no-name-ad8b76e2-a168-4c70-b474-fba4b06a16f5

Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:30:45,355] Trial 99 finished with value: 0.6825349167933434 and parameters: {'subsample': 0.45257163985495624, 'dropout_rate': 0.16548983181326787, 'n_estimators': 118, 'learning_rate': 0.06084663657286539}. Best is trial 3 with value: 0.685290607677292.


* Best trial for C-index:
 FrozenTrial(number=3, state=TrialState.COMPLETE, values=[0.685290607677292], datetime_start=datetime.datetime(2024, 4, 17, 16, 25, 11, 84369), datetime_complete=datetime.datetime(2024, 4, 17, 16, 25, 14, 85828), params={'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=3, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}


* Best Score for C-index:
 0.685290607677292

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.20699145898488328
Fold 2 IBS: 0.17398504678460716
Fold 3 IBS: 0.17941516378878425
Fold 4 IBS: 0.18574687834833697
Fold 5 IBS: 0.18173433993297286
[I 2024-04-17 16:30:46,796] Trial 0 finished with value: 0.1855745775679169 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.1855745775679169.
Fold 1 IBS: 0.2598653641576557
Fold 2 IBS: 0.14405564144070007
Fold 3 IBS: 0.20375887707083012
Fold 4 IBS: 0.17332481564998092
Fold 5 IBS: 0.18939660101154807
[I 2024-04-17 16:30:58,220] Trial 1 finished with value: 0.19408025986614297 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.1855745775679169.
Fold 1 IBS: 0.22204126162913193
Fold 2 IBS: 0.14721065174421064
Fold 3 IBS: 0.17190310904258285
Fold 4 IBS: 0.16837131361863242
Fold 5 IBS: 0.17214316314558759
[I 2024-04-17 16:31:00,401] Trial 2 finished with value: 0.1763338998360291 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.22699350773409555
Fold 2 IBS: 0.1486913616806106
Fold 3 IBS: 0.17363903503348682
Fold 4 IBS: 0.1666785484666208
Fold 5 IBS: 0.17268194636213283
[I 2024-04-17 16:31:03,436] Trial 3 finished with value: 0.17773687985538933 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.22698187907505807
Fold 2 IBS: 0.15456573437606289
Fold 3 IBS: 0.1782258150658699
Fold 4 IBS: 0.17019091511460324
Fold 5 IBS: 0.17336598933755937
[I 2024-04-17 16:31:07,962] Trial 4 finished with value: 0.18066606659383072 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.24286751759123798
Fold 2 IBS: 0.13961470295815073
Fold 3 IBS: 0.18274858229327934
Fold 4 IBS: 0.16567161538132347
Fold 5 IBS: 0.17907301065878306
[I 2024-04-17 16:31:13,467] Trial 5 finished with value: 0.18199508577655493 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.20536666173028972
Fold 2 IBS: 0.1863679002739335
Fold 3 IBS: 0.18577930152623862
Fold 4 IBS: 0.19639298047406575
Fold 5 IBS: 0.1898279603879094
[I 2024-04-17 16:31:15,844] Trial 6 finished with value: 0.19274696087848736 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.20951855034420333
Fold 2 IBS: 0.20942639806578886
Fold 3 IBS: 0.19567566708337242
Fold 4 IBS: 0.2121643931263611
Fold 5 IBS: 0.20311456720022866
[I 2024-04-17 16:31:16,419] Trial 7 finished with value: 0.20597991516399086 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.2083565880528289
Fold 2 IBS: 0.17061986838569568
Fold 3 IBS: 0.1792813312193894
Fold 4 IBS: 0.18646340702949077
Fold 5 IBS: 0.18012399881710475
[I 2024-04-17 16:31:19,355] Trial 8 finished with value: 0.18496903870090192 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.2453650325508943
Fold 2 IBS: 0.13987376499547402
Fold 3 IBS: 0.1875811945998944
Fold 4 IBS: 0.1663972005841367
Fold 5 IBS: 0.18044532744257358
[I 2024-04-17 16:31:27,763] Trial 9 finished with value: 0.1839325040345946 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.254602279977166
Fold 2 IBS: 0.14210916696659623
Fold 3 IBS: 0.19719027687169022
Fold 4 IBS: 0.17058006540228302
Fold 5 IBS: 0.18642832498419037
[I 2024-04-17 16:31:33,125] Trial 10 finished with value: 0.19018202284038516 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7165502912345604, 'n_estimators': 322, 'learning_rate': 0.09279671898160717}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.21267747395291475
Fold 2 IBS: 0.1797346458343791
Fold 3 IBS: 0.18219857610201282
Fold 4 IBS: 0.18537817547227017
Fold 5 IBS: 0.18350531379625157
[I 2024-04-17 16:31:34,643] Trial 11 finished with value: 0.1886988370315657 and parameters: {'subsample': 0.1795750652194426, 'dropout_rate': 0.10580803679784617, 'n_estimators': 112, 'learning_rate': 0.08422813202882692}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.21912874498827617
Fold 2 IBS: 0.15253215902434156
Fold 3 IBS: 0.17280593575903333
Fold 4 IBS: 0.17082136953844937
Fold 5 IBS: 0.1722522947226452
[I 2024-04-17 16:31:36,797] Trial 12 finished with value: 0.17750810080654916 and parameters: {'subsample': 0.5633377352680137, 'dropout_rate': 0.116240995441794, 'n_estimators': 154, 'learning_rate': 0.07678177586157726}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.21129448269457998
Fold 2 IBS: 0.2133936700533369
Fold 3 IBS: 0.19980319832637722
Fold 4 IBS: 0.21886671520299167
Fold 5 IBS: 0.21140702227991878
[I 2024-04-17 16:31:37,110] Trial 13 finished with value: 0.21095301771144087 and parameters: {'subsample': 0.6274731079176695, 'dropout_rate': 0.2633881561505452, 'n_estimators': 9, 'learning_rate': 0.09813277258027844}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.21295934659081597
Fold 2 IBS: 0.218875136891448
Fold 3 IBS: 0.20295435763177502
Fold 4 IBS: 0.22261548129230588
Fold 5 IBS: 0.21575248876153205
[I 2024-04-17 16:31:38,460] Trial 14 finished with value: 0.21463136223357537 and parameters: {'subsample': 0.9169251037774164, 'dropout_rate': 0.6789786764252524, 'n_estimators': 117, 'learning_rate': 0.0025916531369806137}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.21693164642819102
Fold 2 IBS: 0.1559547198023968
Fold 3 IBS: 0.17530211434956908
Fold 4 IBS: 0.17499328585121726
Fold 5 IBS: 0.1741709522820765
[I 2024-04-17 16:31:40,552] Trial 15 finished with value: 0.17947054374269014 and parameters: {'subsample': 0.33872251665241143, 'dropout_rate': 0.242092283972966, 'n_estimators': 152, 'learning_rate': 0.07488286755529167}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.23159082196184075
Fold 2 IBS: 0.1490165975029478
Fold 3 IBS: 0.1926390747572761
Fold 4 IBS: 0.17184452964911004
Fold 5 IBS: 0.17996064670394146
[I 2024-04-17 16:31:45,277] Trial 16 finished with value: 0.18501033411502324 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.4014363979414328, 'n_estimators': 271, 'learning_rate': 0.08033475203870699}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.20609253677203068
Fold 2 IBS: 0.18407479100083193
Fold 3 IBS: 0.18348842244691083
Fold 4 IBS: 0.19462861291265277
Fold 5 IBS: 0.1861636032106156
[I 2024-04-17 16:31:46,076] Trial 17 finished with value: 0.19088959326860838 and parameters: {'subsample': 0.6074303801147299, 'dropout_rate': 0.5499199074879557, 'n_estimators': 56, 'learning_rate': 0.0882379235542871}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.2452261540770616
Fold 2 IBS: 0.14071425995567274
Fold 3 IBS: 0.19216150847378008
Fold 4 IBS: 0.16747154879452197
Fold 5 IBS: 0.18048369589553903
[I 2024-04-17 16:31:52,601] Trial 18 finished with value: 0.1852114334393151 and parameters: {'subsample': 0.4086378048663586, 'dropout_rate': 0.7506280278256608, 'n_estimators': 373, 'learning_rate': 0.06684013681192397}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.21196381752117047

Fold 2 IBS: 0.16123008298113736
Fold 3 IBS: 0.1745013121861096
Fold 4 IBS: 0.17691114823310736
Fold 5 IBS: 0.17502712003769116
[I 2024-04-17 16:31:55,357] Trial 19 finished with value: 0.17992669619184318 and parameters: {'subsample': 0.8350722272141606, 'dropout_rate': 0.9887344422073516, 'n_estimators': 235, 'learning_rate': 0.036212385990032875}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.21495078894573805
Fold 2 IBS: 0.15700881753658336
Fold 3 IBS: 0.17277259067356457
Fold 4 IBS: 0.17353617304957153
Fold 5 IBS: 0.17316931509430378
[I 2024-04-17 16:31:57,584] Trial 20 finished with value: 0.17828753705995226 and parameters: {'subsample': 0.5568571093279632, 'dropout_rate': 0.19350037184585095, 'n_estimators': 161, 'learning_rate': 0.06348170552170027}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.2324916714901111
Fold 2 IBS: 0.14281050488656433
Fold 3 IBS: 0.17495112113541136
Fold 4 IBS: 0.16606234750928592
Fold 5 IBS: 0.17362532167442254
[I 2024-04-17 16:32:00,910] Trial 21 finished with value: 0.17798819333915905 and parameters: {'subsample': 0.4821375662037144, 'dropout_rate': 0.12395834975058428, 'n_estimators': 207, 'learning_rate': 0.08144338081292316}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.24099362019793116
Fold 2 IBS: 0.13974474679139898
Fold 3 IBS: 0.18162403889708043
Fold 4 IBS: 0.1661592087879784
Fold 5 IBS: 0.17766065572393927
[I 2024-04-17 16:32:06,467] Trial 22 finished with value: 0.18123645407966565 and parameters: {'subsample': 0.5493353037248992, 'dropout_rate': 0.1985722794075393, 'n_estimators': 295, 'learning_rate': 0.0731306585050806}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.20726258843038542
Fold 2 IBS: 0.1834975176878167
Fold 3 IBS: 0.1819468290240784
Fold 4 IBS: 0.18765956127237737
Fold 5 IBS: 0.18403269145570506
[I 2024-04-17 16:32:07,505] Trial 23 finished with value: 0.18887983757407262 and parameters: {'subsample': 0.399790727585547, 'dropout_rate': 0.3459910568541636, 'n_estimators': 79, 'learning_rate': 0.076058791235313}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.23107421299782002
Fold 2 IBS: 0.14233696972946888
Fold 3 IBS: 0.17490908281615294
Fold 4 IBS: 0.16543484134211936
Fold 5 IBS: 0.1734977374925131
[I 2024-04-17 16:32:09,982] Trial 24 finished with value: 0.17745056887561486 and parameters: {'subsample': 0.5698970382547612, 'dropout_rate': 0.15859366222014767, 'n_estimators': 173, 'learning_rate': 0.09887491833757632}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.22885094388635085
Fold 2 IBS: 0.14320902134574187
Fold 3 IBS: 0.17237509072478785
Fold 4 IBS: 0.16586182092687266
Fold 5 IBS: 0.17262779891390698
[I 2024-04-17 16:32:11,981] Trial 25 finished with value: 0.17658493515953205 and parameters: {'subsample': 0.665019529307733, 'dropout_rate': 0.3125521697439868, 'n_estimators': 152, 'learning_rate': 0.09931680042445917}. Best is trial 2 with value: 0.1763338998360291.
Fold 1 IBS: 0.2234603424384201
Fold 2 IBS: 0.14652289240661065
Fold 3 IBS: 0.1716474185289319
Fold 4 IBS: 0.16756965500432858
Fold 5 IBS: 0.1717525459362228
[I 2024-04-17 16:32:13,598] Trial 26 finished with value: 0.1761905708629028 and parameters: {'subsample': 0.6817267275162041, 'dropout_rate': 0.4868646496386122, 'n_estimators': 130, 'learning_rate': 0.09970917701467895}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.21366522210506902
Fold 2 IBS: 0.22082209653016688
Fold 3 IBS: 0.20401533995056864
Fold 4 IBS: 0.22392310956104527
Fold 5 IBS: 0.21735135918845064
[I 2024-04-17 16:32:13,926] Trial 27 finished with value: 0.2159554254670601 and parameters: {'subsample': 0.8401134505394738, 'dropout_rate': 0.4943715411560561, 'n_estimators': 1, 'learning_rate': 0.08927722869002894}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.20990516163188194
Fold 2 IBS: 0.16568640542103
Fold 3 IBS: 0.176054273976982
Fold 4 IBS: 0.17795625503394366
Fold 5 IBS: 0.17704554682584575
[I 2024-04-17 16:32:14,927] Trial 28 finished with value: 0.18132952857793666 and parameters: {'subsample': 0.6724534462130075, 'dropout_rate': 0.4516124038493412, 'n_estimators': 84, 'learning_rate': 0.09349846171107849}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.2242308148972475
Fold 2 IBS: 0.14680754045921177
Fold 3 IBS: 0.17162815968225198
Fold 4 IBS: 0.16750372080355963
Fold 5 IBS: 0.17175217560249612
[I 2024-04-17 16:32:16,623] Trial 29 finished with value: 0.17638448228895337 and parameters: {'subsample': 0.8085924634786621, 'dropout_rate': 0.36446031497367243, 'n_estimators': 131, 'learning_rate': 0.09914929677456026}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.21827083266571
Fold 2 IBS: 0.15216247637094932
Fold 3 IBS: 0.17213301803864015
Fold 4 IBS: 0.17147300765047852
Fold 5 IBS: 0.1723540600385396
[I 2024-04-17 16:32:18,272] Trial 30 finished with value: 0.17727867895286353 and parameters: {'subsample': 0.8739790489864521, 'dropout_rate': 0.6179059483957562, 'n_estimators': 123, 'learning_rate': 0.08710235470926556}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22535152456499746
Fold 2 IBS: 0.14522921425429433
Fold 3 IBS: 0.1716924219329359
Fold 4 IBS: 0.16706258125017212
Fold 5 IBS: 0.1717735923195651
[I 2024-04-17 16:32:20,106] Trial 31 finished with value: 0.17622186686439298 and parameters: {'subsample': 0.7710592138861083, 'dropout_rate': 0.33376763019975975, 'n_estimators': 140, 'learning_rate': 0.0966134056021341}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.21630562038160175
Fold 2 IBS: 0.1548443499733191
Fold 3 IBS: 0.17268712981915182
Fold 4 IBS: 0.17220978822210045
Fold 5 IBS: 0.1731037547587704
[I 2024-04-17 16:32:21,455] Trial 32 finished with value: 0.1778301286309887 and parameters: {'subsample': 0.7878845579666447, 'dropout_rate': 0.43803789551315775, 'n_estimators': 110, 'learning_rate': 0.09293168350158995}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.20975351657747907
Fold 2 IBS: 0.16617518400034192
Fold 3 IBS: 0.17622793305258935
Fold 4 IBS: 0.17932944649136498
Fold 5 IBS: 0.17739383212522375
[I 2024-04-17 16:32:22,429] Trial 33 finished with value: 0.1817759824493998 and parameters: {'subsample': 0.7288853323630606, 'dropout_rate': 0.32555691791675817, 'n_estimators': 78, 'learning_rate': 0.09972132432487302}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.23845602984630887
Fold 2 IBS: 0.1395835565472375
Fold 3 IBS: 0.1779815227189946
Fold 4 IBS: 0.16500487784612677
Fold 5 IBS: 0.17608566884269808
[I 2024-04-17 16:32:25,875] Trial 34 finished with value: 0.17942233116027315 and parameters: {'subsample': 0.7994099796262722, 'dropout_rate': 0.5051054684842515, 'n_estimators': 234, 'learning_rate': 0.08372350582280848}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.23531008266294468
Fold 2 IBS: 0.1402860809209235
Fold 3 IBS: 0.17543981307192968
Fold 4 IBS: 0.16495800586097556
Fold 5 IBS: 0.17460015637877416
[I 2024-04-17 16:32:28,805] Trial 35 finished with value: 0.1781188277791095 and parameters: {'subsample': 0.9526830717705748, 'dropout_rate': 0.4092982178841962, 'n_estimators': 195, 'learning_rate': 0.09258102126609677}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.20895124565871223
Fold 2 IBS: 0.16706645406511925
Fold 3 IBS: 0.1763202651653379
Fold 4 IBS: 0.18141296537076823
Fold 5 IBS: 0.1768982597928194
[I 2024-04-17 16:32:30,507] Trial 36 finished with value: 0.1821298380105514 and parameters: {'subsample': 0.7083391301049273, 'dropout_rate': 0.5847496282810936, 'n_estimators': 130, 'learning_rate': 0.057302100136983544}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.20677994533848554
Fold 2 IBS: 0.19785887366630206
Fold 3 IBS: 0.1921188823150778
Fold 4 IBS: 0.20604540095326113
Fold 5 IBS: 0.19893621460567157
[I 2024-04-17 16:32:31,200] Trial 37 finished with value: 0.2003478633757596 and parameters: {'subsample': 0.764407857184374, 'dropout_rate': 0.2814822188533228, 'n_estimators': 39, 'learning_rate': 0.0689591635236842}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.212167631883015
Fold 2 IBS: 0.16060247820717258

Fold 3 IBS: 0.174539339955922
Fold 4 IBS: 0.17677411321719771
Fold 5 IBS: 0.1748171030684222
[I 2024-04-17 16:32:32,335] Trial 38 finished with value: 0.1797801332663459 and parameters: {'subsample': 0.9000660387308665, 'dropout_rate': 0.3720991365773877, 'n_estimators': 92, 'learning_rate': 0.09484943844583128}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.23312185694951
Fold 2 IBS: 0.14152754442207624
Fold 3 IBS: 0.1738623702033595
Fold 4 IBS: 0.16517162749120218
Fold 5 IBS: 0.17320335516077462
[I 2024-04-17 16:32:34,919] Trial 39 finished with value: 0.1773773508453845 and parameters: {'subsample': 0.6998122574699481, 'dropout_rate': 0.47645352742973207, 'n_estimators': 189, 'learning_rate': 0.08850670895881207}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.20655830218659368
Fold 2 IBS: 0.17492142020744073
Fold 3 IBS: 0.17992637231108904
Fold 4 IBS: 0.18738850901139598
Fold 5 IBS: 0.1819660108644699
[I 2024-04-17 16:32:36,517] Trial 40 finished with value: 0.18615212291619784 and parameters: {'subsample': 0.8406191237107015, 'dropout_rate': 0.43361484605585743, 'n_estimators': 133, 'learning_rate': 0.045212500321497075}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22966360900455243
Fold 2 IBS: 0.14279903212706183
Fold 3 IBS: 0.17256219277204068
Fold 4 IBS: 0.1656780759779458
Fold 5 IBS: 0.17273590388549376
[I 2024-04-17 16:32:38,604] Trial 41 finished with value: 0.1766877627534189 and parameters: {'subsample': 0.6545867028783894, 'dropout_rate': 0.3148196375868446, 'n_estimators': 155, 'learning_rate': 0.09939124867465118}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.23922276903577103
Fold 2 IBS: 0.1395989503454006
Fold 3 IBS: 0.1784064097322522
Fold 4 IBS: 0.16524425283984973
Fold 5 IBS: 0.1761731989413162
[I 2024-04-17 16:32:41,821] Trial 42 finished with value: 0.17972911617891793 and parameters: {'subsample': 0.6077455199146518, 'dropout_rate': 0.29690092987631916, 'n_estimators': 213, 'learning_rate': 0.09469533749810218}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.220971469758285
Fold 2 IBS: 0.14916418095169007
Fold 3 IBS: 0.17184192978219048
Fold 4 IBS: 0.16904227632160218
Fold 5 IBS: 0.1719291483531034
[I 2024-04-17 16:32:43,677] Trial 43 finished with value: 0.17658980103337424 and parameters: {'subsample': 0.7542207061218751, 'dropout_rate': 0.35937532714464887, 'n_estimators': 141, 'learning_rate': 0.08476172362159548}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.23141032648201657
Fold 2 IBS: 0.14143559962190408
Fold 3 IBS: 0.17420365996423157
Fold 4 IBS: 0.16537152448495646
Fold 5 IBS: 0.1734243263574113
[I 2024-04-17 16:32:46,081] Trial 44 finished with value: 0.177169087382104 and parameters: {'subsample': 0.6602399410777265, 'dropout_rate': 0.526533685849216, 'n_estimators': 180, 'learning_rate': 0.09044220125547665}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.21089629592068382
Fold 2 IBS: 0.16311544425084537
Fold 3 IBS: 0.17696242879909388
Fold 4 IBS: 0.17900213824107597
Fold 5 IBS: 0.1747829258180319
[I 2024-04-17 16:32:47,395] Trial 45 finished with value: 0.18095184660594615 and parameters: {'subsample': 0.512461735008288, 'dropout_rate': 0.222619518161984, 'n_estimators': 106, 'learning_rate': 0.08056458289540327}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.27045896704568695
Fold 2 IBS: 0.1504597410024135
Fold 3 IBS: 0.2210681143612087
Fold 4 IBS: 0.1813809212299576
Fold 5 IBS: 0.1960364099872972
[I 2024-04-17 16:32:56,935] Trial 46 finished with value: 0.20388083072531282 and parameters: {'subsample': 0.7139239778563963, 'dropout_rate': 0.5818755510743238, 'n_estimators': 454, 'learning_rate': 0.09655662037102167}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.21243133782539717
Fold 2 IBS: 0.2173319836660306
Fold 3 IBS: 0.20215221842233996
Fold 4 IBS: 0.22143925395243713
Fold 5 IBS: 0.21461159252802586
[I 2024-04-17 16:32:57,773] Trial 47 finished with value: 0.2135932772788461 and parameters: {'subsample': 0.7961983953812717, 'dropout_rate': 0.40128211336371056, 'n_estimators': 57, 'learning_rate': 0.008209618821055878}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.20726103408293178
Fold 2 IBS: 0.19680406269003028
Fold 3 IBS: 0.1901536501268376
Fold 4 IBS: 0.20426757968820353
Fold 5 IBS: 0.19703629593512692
[I 2024-04-17 16:32:58,550] Trial 48 finished with value: 0.19910452450462604 and parameters: {'subsample': 0.4480446411548331, 'dropout_rate': 0.35454373515562776, 'n_estimators': 30, 'learning_rate': 0.09966705832526779}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.23344132250682764
Fold 2 IBS: 0.14104271406676636
Fold 3 IBS: 0.17439318006369528
Fold 4 IBS: 0.16518743131122318
Fold 5 IBS: 0.17373056152102573
[I 2024-04-17 16:33:02,770] Trial 49 finished with value: 0.17755904189390764 and parameters: {'subsample': 0.6248758897631537, 'dropout_rate': 0.28451028248810417, 'n_estimators': 241, 'learning_rate': 0.07106208153632024}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.24033581884255786
Fold 2 IBS: 0.1395255146300706
Fold 3 IBS: 0.17897308458636763
Fold 4 IBS: 0.16530966979607722
Fold 5 IBS: 0.17705888722973134
[I 2024-04-17 16:33:07,340] Trial 50 finished with value: 0.18024059501696094 and parameters: {'subsample': 0.69032927908463, 'dropout_rate': 0.45869054223097094, 'n_estimators': 265, 'learning_rate': 0.07733338601813798}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22218795257767343
Fold 2 IBS: 0.14793858363580561
Fold 3 IBS: 0.17175281501638456
Fold 4 IBS: 0.16836085198617823
Fold 5 IBS: 0.1718148638232818
[I 2024-04-17 16:33:09,579] Trial 51 finished with value: 0.17641101340786475 and parameters: {'subsample': 0.7456087330777196, 'dropout_rate': 0.363867238566337, 'n_estimators': 148, 'learning_rate': 0.08411450332352723}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.2293659448966561
Fold 2 IBS: 0.142536099663412
Fold 3 IBS: 0.1723971956594217
Fold 4 IBS: 0.16580026536433384
Fold 5 IBS: 0.17216122916628113
[I 2024-04-17 16:33:11,977] Trial 52 finished with value: 0.17645214695002093 and parameters: {'subsample': 0.7643062130653864, 'dropout_rate': 0.33327541035398606, 'n_estimators': 168, 'learning_rate': 0.08975519100689601}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22705241375124105
Fold 2 IBS: 0.14397977379200616
Fold 3 IBS: 0.17186091572172785
Fold 4 IBS: 0.1664740613475492
Fold 5 IBS: 0.17191285531085046
[I 2024-04-17 16:33:14,315] Trial 53 finished with value: 0.17625600398467495 and parameters: {'subsample': 0.7657092499953465, 'dropout_rate': 0.388073212110474, 'n_estimators': 165, 'learning_rate': 0.08531238875572147}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.23801849166901898
Fold 2 IBS: 0.13974226443313773
Fold 3 IBS: 0.17704076263784937
Fold 4 IBS: 0.16499887520451978
Fold 5 IBS: 0.17606636361253997
[I 2024-04-17 16:33:17,953] Trial 54 finished with value: 0.17917335151141317 and parameters: {'subsample': 0.8715811821904071, 'dropout_rate': 0.4139504225119564, 'n_estimators': 225, 'learning_rate': 0.08524581996646284}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.21981951699528887
Fold 2 IBS: 0.15083130133789377
Fold 3 IBS: 0.17181106729493356
Fold 4 IBS: 0.17011433806468415
Fold 5 IBS: 0.17209676643948307
[I 2024-04-17 16:33:20,277] Trial 55 finished with value: 0.17693459802645667 and parameters: {'subsample': 0.8290338817278318, 'dropout_rate': 0.377041536347971, 'n_estimators': 141, 'learning_rate': 0.08033100358982499}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.21162339977268962
Fold 2 IBS: 0.16244254257403562
Fold 3 IBS: 0.1745839098413702
Fold 4 IBS: 0.1778575194248137
Fold 5 IBS: 0.17464656519817862
[I 2024-04-17 16:33:21,377] Trial 56 finished with value: 0.18023078736221754 and parameters: {'subsample': 0.7361786730569395, 'dropout_rate': 0.5194091093440398, 'n_estimators': 94, 'learning_rate': 0.09141885676618033}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.21994039279819877
Fold 2 IBS: 0.15605132678390646
Fold 3 IBS: 0.17940151889555797

Fold 4 IBS: 0.17323719207666877
Fold 5 IBS: 0.17391114418369052
[I 2024-04-17 16:33:24,462] Trial 57 finished with value: 0.1805083149476045 and parameters: {'subsample': 0.2888110376335854, 'dropout_rate': 0.2571472416667656, 'n_estimators': 198, 'learning_rate': 0.06361079949574666}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22563954492676833
Fold 2 IBS: 0.1450864819710421
Fold 3 IBS: 0.17178934906165097
Fold 4 IBS: 0.16674907181784904
Fold 5 IBS: 0.17189804627761335
[I 2024-04-17 16:33:26,968] Trial 58 finished with value: 0.17623249881098477 and parameters: {'subsample': 0.9511535444605486, 'dropout_rate': 0.48062274276704253, 'n_estimators': 176, 'learning_rate': 0.0781546863079734}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.2269672945175514
Fold 2 IBS: 0.1439593010574543
Fold 3 IBS: 0.1719657542477086
Fold 4 IBS: 0.16659339591616157
Fold 5 IBS: 0.17212797426047644
[I 2024-04-17 16:33:30,061] Trial 59 finished with value: 0.17632274399987047 and parameters: {'subsample': 0.8979645377949864, 'dropout_rate': 0.5768632327111922, 'n_estimators': 178, 'learning_rate': 0.07969151784270986}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.21664995294949152
Fold 2 IBS: 0.15372291880223368
Fold 3 IBS: 0.17230583736771898
Fold 4 IBS: 0.17189313852790084
Fold 5 IBS: 0.17252505742307372
[I 2024-04-17 16:33:32,360] Trial 60 finished with value: 0.17741938101408375 and parameters: {'subsample': 0.9884109141685877, 'dropout_rate': 0.637508474870143, 'n_estimators': 175, 'learning_rate': 0.059610187538618985}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.21374733877305443
Fold 2 IBS: 0.15820770019614663
Fold 3 IBS: 0.17341764371934124
Fold 4 IBS: 0.17461167573402683
Fold 5 IBS: 0.1738536057912688
[I 2024-04-17 16:33:33,845] Trial 61 finished with value: 0.17876759284276758 and parameters: {'subsample': 0.9385043395696651, 'dropout_rate': 0.5737179605562639, 'n_estimators': 121, 'learning_rate': 0.07650795161561112}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.24102205183118242
Fold 2 IBS: 0.13948977142197166
Fold 3 IBS: 0.18015869582558547
Fold 4 IBS: 0.16544166007413685
Fold 5 IBS: 0.1776261899798061
[I 2024-04-17 16:33:37,300] Trial 62 finished with value: 0.1807476738265365 and parameters: {'subsample': 0.956119151430744, 'dropout_rate': 0.4775564435628733, 'n_estimators': 220, 'learning_rate': 0.09553024374832882}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22137035194978408
Fold 2 IBS: 0.14863870017751157
Fold 3 IBS: 0.17164326002161873
Fold 4 IBS: 0.16910163237693532
Fold 5 IBS: 0.1717872906084157
[I 2024-04-17 16:33:39,326] Trial 63 finished with value: 0.17650824702685305 and parameters: {'subsample': 0.9050888299599831, 'dropout_rate': 0.6950717308072746, 'n_estimators': 165, 'learning_rate': 0.07306389448816682}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.215341873895602
Fold 2 IBS: 0.15528344138799516
Fold 3 IBS: 0.17296592505431693
Fold 4 IBS: 0.17391159594060562
Fold 5 IBS: 0.17315756010217245
[I 2024-04-17 16:33:41,833] Trial 64 finished with value: 0.17813207927613842 and parameters: {'subsample': 0.873629733066705, 'dropout_rate': 0.5471100859946817, 'n_estimators': 190, 'learning_rate': 0.05155862028520672}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.20562616168800332
Fold 2 IBS: 0.18080180686096697
Fold 3 IBS: 0.18250981397531046
Fold 4 IBS: 0.19269646743566266
Fold 5 IBS: 0.18578560628765675
[I 2024-04-17 16:33:42,650] Trial 65 finished with value: 0.18948397124952002 and parameters: {'subsample': 0.8223519048537484, 'dropout_rate': 0.6177242914250525, 'n_estimators': 66, 'learning_rate': 0.0782361555335954}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.23344131930867112
Fold 2 IBS: 0.14076131729555805
Fold 3 IBS: 0.1744918091229416
Fold 4 IBS: 0.16507876153936366
Fold 5 IBS: 0.17392005828328344
[I 2024-04-17 16:33:46,325] Trial 66 finished with value: 0.17753865310996356 and parameters: {'subsample': 0.9294868979803856, 'dropout_rate': 0.7872235459612831, 'n_estimators': 259, 'learning_rate': 0.06592303138240745}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.2494424222741009
Fold 2 IBS: 0.14054369895001292
Fold 3 IBS: 0.18913190307110606
Fold 4 IBS: 0.16775222137862159
Fold 5 IBS: 0.18295216797801261
[I 2024-04-17 16:33:51,586] Trial 67 finished with value: 0.1859644827303708 and parameters: {'subsample': 0.864958411317202, 'dropout_rate': 0.4582890129088557, 'n_estimators': 302, 'learning_rate': 0.08635943820759996}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.21254615512537808
Fold 2 IBS: 0.16024183489202581
Fold 3 IBS: 0.17397647763268065
Fold 4 IBS: 0.1760532496236163
Fold 5 IBS: 0.17448290531704327
[I 2024-04-17 16:33:52,878] Trial 68 finished with value: 0.17946012451814883 and parameters: {'subsample': 0.9964676670058447, 'dropout_rate': 0.4963358031814581, 'n_estimators': 108, 'learning_rate': 0.08228372469332425}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.23852173825600562
Fold 2 IBS: 0.13962292932481354
Fold 3 IBS: 0.177320766632515
Fold 4 IBS: 0.1650734057350259
Fold 5 IBS: 0.175899752244383
[I 2024-04-17 16:33:55,774] Trial 69 finished with value: 0.17928771843854863 and parameters: {'subsample': 0.7789376872249791, 'dropout_rate': 0.42196718970972413, 'n_estimators': 204, 'learning_rate': 0.09614511231134394}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.2135114870245484
Fold 2 IBS: 0.15852260109133978
Fold 3 IBS: 0.17376162188190616
Fold 4 IBS: 0.1752611815425655
Fold 5 IBS: 0.17392314573248985
[I 2024-04-17 16:33:57,385] Trial 70 finished with value: 0.17899600745456995 and parameters: {'subsample': 0.8996191269443969, 'dropout_rate': 0.39404060428392723, 'n_estimators': 129, 'learning_rate': 0.07169090674374563}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.2243795236931168
Fold 2 IBS: 0.1466497543595969
Fold 3 IBS: 0.1716380810373381
Fold 4 IBS: 0.16744531272594104
Fold 5 IBS: 0.1717533532469541
[I 2024-04-17 16:33:59,292] Trial 71 finished with value: 0.1763732050125894 and parameters: {'subsample': 0.8054160281437949, 'dropout_rate': 0.3844943177047123, 'n_estimators': 150, 'learning_rate': 0.0866783400619895}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22805066315514058
Fold 2 IBS: 0.14364807229055407
Fold 3 IBS: 0.17221157403939713
Fold 4 IBS: 0.1662216586825225
Fold 5 IBS: 0.17210383561121542
[I 2024-04-17 16:34:01,547] Trial 72 finished with value: 0.17644716075576594 and parameters: {'subsample': 0.8198273398598465, 'dropout_rate': 0.44476879971466654, 'n_estimators': 164, 'learning_rate': 0.08820768682018797}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.23291220045708516
Fold 2 IBS: 0.14073497554150244
Fold 3 IBS: 0.17421158449478344
Fold 4 IBS: 0.16522021899598976
Fold 5 IBS: 0.17361418662459446
[I 2024-04-17 16:34:03,879] Trial 73 finished with value: 0.17733863322279106 and parameters: {'subsample': 0.8508871210663617, 'dropout_rate': 0.522228201630752, 'n_estimators': 182, 'learning_rate': 0.09227846651675198}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.2057301360625177
Fold 2 IBS: 0.19202491210765432
Fold 3 IBS: 0.18757621092891694
Fold 4 IBS: 0.2000592938853696
Fold 5 IBS: 0.1940683131947395
[I 2024-04-17 16:34:05,757] Trial 74 finished with value: 0.19589177323583962 and parameters: {'subsample': 0.5840478635087837, 'dropout_rate': 0.47583191531076013, 'n_estimators': 144, 'learning_rate': 0.02502249046663426}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.21451302375402034
Fold 2 IBS: 0.15784790225774195
Fold 3 IBS: 0.17340674527510866
Fold 4 IBS: 0.17404337360343058
Fold 5 IBS: 0.17404251770595028
[I 2024-04-17 16:34:07,501] Trial 75 finished with value: 0.17877071251925036 and parameters: {'subsample': 0.7947612771730971, 'dropout_rate': 0.3923026930926209, 'n_estimators': 120, 'learning_rate': 0.07881433115939485}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.20982512625958663
Fold 2 IBS: 0.16617217058209455
Fold 3 IBS: 0.17625415627928298
Fold 4 IBS: 0.1791366154841858

Fold 5 IBS: 0.1765257577906424
[I 2024-04-17 16:34:08,624] Trial 76 finished with value: 0.18158276527915845 and parameters: {'subsample': 0.5342916507439118, 'dropout_rate': 0.3308474569541405, 'n_estimators': 95, 'learning_rate': 0.08239604675369354}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22661340611062414
Fold 2 IBS: 0.14452172357008383
Fold 3 IBS: 0.17205945064331313
Fold 4 IBS: 0.16641683545014102
Fold 5 IBS: 0.17205875073324323
[I 2024-04-17 16:34:10,636] Trial 77 finished with value: 0.17633403330148104 and parameters: {'subsample': 0.9609879844906213, 'dropout_rate': 0.5631110327938873, 'n_estimators': 162, 'learning_rate': 0.08696726514452227}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22066984449071184
Fold 2 IBS: 0.14951880841845128
Fold 3 IBS: 0.17164572765928524
Fold 4 IBS: 0.16909515800883118
Fold 5 IBS: 0.1718206369393307
[I 2024-04-17 16:34:12,649] Trial 78 finished with value: 0.17655003510332207 and parameters: {'subsample': 0.9657507176780757, 'dropout_rate': 0.5642371591874461, 'n_estimators': 158, 'learning_rate': 0.07502680885149458}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.23548497218871195
Fold 2 IBS: 0.14020645525121206
Fold 3 IBS: 0.17527423452107635
Fold 4 IBS: 0.16497241118911346
Fold 5 IBS: 0.17484872233348417
[I 2024-04-17 16:34:15,491] Trial 79 finished with value: 0.1781573590967196 and parameters: {'subsample': 0.9141705516890372, 'dropout_rate': 0.5992784824546663, 'n_estimators': 208, 'learning_rate': 0.08683841460062944}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22252611456965762
Fold 2 IBS: 0.1476105011244213
Fold 3 IBS: 0.17160044447727665
Fold 4 IBS: 0.16815097870075643
Fold 5 IBS: 0.17175282415971235
[I 2024-04-17 16:34:17,825] Trial 80 finished with value: 0.17632817260636488 and parameters: {'subsample': 0.9716921761173107, 'dropout_rate': 0.6418351618434336, 'n_estimators': 181, 'learning_rate': 0.06928273603865487}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22653231529236906
Fold 2 IBS: 0.14446459441288495
Fold 3 IBS: 0.1720652769876484
Fold 4 IBS: 0.166483490226234
Fold 5 IBS: 0.17209979803255637
[I 2024-04-17 16:34:20,006] Trial 81 finished with value: 0.17632909499033855 and parameters: {'subsample': 0.9689678539659375, 'dropout_rate': 0.6464561367949138, 'n_estimators': 175, 'learning_rate': 0.08058602280439785}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22231969777678973
Fold 2 IBS: 0.14778370230536084
Fold 3 IBS: 0.17159756892750871
Fold 4 IBS: 0.16826216202182384
Fold 5 IBS: 0.17175205234137023
[I 2024-04-17 16:34:22,277] Trial 82 finished with value: 0.17634303667457069 and parameters: {'subsample': 0.9660360510204188, 'dropout_rate': 0.6739123438291792, 'n_estimators': 184, 'learning_rate': 0.0676930977156915}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22025159969224237
Fold 2 IBS: 0.1496613549016541
Fold 3 IBS: 0.1717064867152483
Fold 4 IBS: 0.16944459424038685
Fold 5 IBS: 0.17188356135894564
[I 2024-04-17 16:34:24,354] Trial 83 finished with value: 0.17658951938169548 and parameters: {'subsample': 0.9321851317697277, 'dropout_rate': 0.6421886730626755, 'n_estimators': 169, 'learning_rate': 0.0692402614218835}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.2364897434951826
Fold 2 IBS: 0.13994879890598236
Fold 3 IBS: 0.17659868364041395
Fold 4 IBS: 0.16496040165699907
Fold 5 IBS: 0.1752900349711059
[I 2024-04-17 16:34:27,897] Trial 84 finished with value: 0.1786575325339368 and parameters: {'subsample': 0.9786122340724046, 'dropout_rate': 0.7324870896925375, 'n_estimators': 250, 'learning_rate': 0.07415029684729806}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.23588158055257782
Fold 2 IBS: 0.14010868539487115
Fold 3 IBS: 0.17562436970117234
Fold 4 IBS: 0.16497220453282727
Fold 5 IBS: 0.17496361488768616
[I 2024-04-17 16:34:31,469] Trial 85 finished with value: 0.17831009101382694 and parameters: {'subsample': 0.894189759121279, 'dropout_rate': 0.7978689461447146, 'n_estimators': 226, 'learning_rate': 0.08012355962323038}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.2223336635433896
Fold 2 IBS: 0.14780826206916475
Fold 3 IBS: 0.17159804233360632
Fold 4 IBS: 0.16830828819459812
Fold 5 IBS: 0.17175524146701648
[I 2024-04-17 16:34:34,207] Trial 86 finished with value: 0.17636069952155503 and parameters: {'subsample': 0.9411071762105223, 'dropout_rate': 0.6030017566724772, 'n_estimators': 195, 'learning_rate': 0.06372583418560197}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22787968588042387
Fold 2 IBS: 0.1436894565280871
Fold 3 IBS: 0.17220776840799487
Fold 4 IBS: 0.1661860004018252
Fold 5 IBS: 0.17231098268581801
[I 2024-04-17 16:34:36,376] Trial 87 finished with value: 0.1764547787808298 and parameters: {'subsample': 0.9207567689512542, 'dropout_rate': 0.6548673906828214, 'n_estimators': 177, 'learning_rate': 0.08254545432373704}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.2064310860163468
Fold 2 IBS: 0.17491957004195025
Fold 3 IBS: 0.17978435867953457
Fold 4 IBS: 0.18718946210865692
Fold 5 IBS: 0.1816266875697772
[I 2024-04-17 16:34:38,012] Trial 88 finished with value: 0.18599023288325314 and parameters: {'subsample': 0.9976238902918372, 'dropout_rate': 0.5485257105058164, 'n_estimators': 132, 'learning_rate': 0.045566841887675485}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.24891305016375334
Fold 2 IBS: 0.140553629293993
Fold 3 IBS: 0.18921438358074627
Fold 4 IBS: 0.16753133907240803
Fold 5 IBS: 0.18298545511825753
[I 2024-04-17 16:34:45,067] Trial 89 finished with value: 0.18583957144583163 and parameters: {'subsample': 0.8835892243349359, 'dropout_rate': 0.5042874145972731, 'n_estimators': 368, 'learning_rate': 0.07052339167561635}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22686044920935344
Fold 2 IBS: 0.14432659589444627
Fold 3 IBS: 0.17211832787041553
Fold 4 IBS: 0.16636806408422647
Fold 5 IBS: 0.17211804416287588
[I 2024-04-17 16:34:47,084] Trial 90 finished with value: 0.17635829624426352 and parameters: {'subsample': 0.9695079821200411, 'dropout_rate': 0.5255096070146712, 'n_estimators': 158, 'learning_rate': 0.09001725352481478}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22758422029482903
Fold 2 IBS: 0.1437836580438883
Fold 3 IBS: 0.17223906445478718
Fold 4 IBS: 0.16614610411711694
Fold 5 IBS: 0.17221648872820144
[I 2024-04-17 16:34:49,886] Trial 91 finished with value: 0.17639390712776457 and parameters: {'subsample': 0.9579718594238708, 'dropout_rate': 0.6775366635657634, 'n_estimators': 217, 'learning_rate': 0.06664847064654782}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22709329799231787
Fold 2 IBS: 0.14407546383517908
Fold 3 IBS: 0.17215999222303177
Fold 4 IBS: 0.16633749349940583
Fold 5 IBS: 0.17218291227451066
[I 2024-04-17 16:34:52,202] Trial 92 finished with value: 0.17636983196488903 and parameters: {'subsample': 0.9728149641045305, 'dropout_rate': 0.705777224556913, 'n_estimators': 186, 'learning_rate': 0.07678251960249231}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22131429180481454
Fold 2 IBS: 0.14879094025381526
Fold 3 IBS: 0.17386499626524998
Fold 4 IBS: 0.17168372643231497
Fold 5 IBS: 0.1723081864224461
[I 2024-04-17 16:34:54,885] Trial 93 finished with value: 0.17759242823572818 and parameters: {'subsample': 0.4627070216098863, 'dropout_rate': 0.6594916211585667, 'n_estimators': 204, 'learning_rate': 0.05960185123908448}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.21433841773070403
Fold 2 IBS: 0.15734065007033193
Fold 3 IBS: 0.17318840600408164
Fold 4 IBS: 0.17397346638174685
Fold 5 IBS: 0.17349019364747378
[I 2024-04-17 16:34:56,605] Trial 94 finished with value: 0.17846622676686763 and parameters: {'subsample': 0.9398263780869235, 'dropout_rate': 0.6300012976898713, 'n_estimators': 140, 'learning_rate': 0.06812195526403411}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.2142509355371671
Fold 2 IBS: 0.1562217909132044
Fold 3 IBS: 0.1731932397279527
Fold 4 IBS: 0.174454617050015

Fold 5 IBS: 0.17342217216926453
[I 2024-04-17 16:34:58,779] Trial 95 finished with value: 0.17830855107952073 and parameters: {'subsample': 0.8589098741489217, 'dropout_rate': 0.598749764600434, 'n_estimators': 173, 'learning_rate': 0.05521411192630663}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.22565089304118113
Fold 2 IBS: 0.1447600949880749
Fold 3 IBS: 0.17360701432529962
Fold 4 IBS: 0.16815975301993338
Fold 5 IBS: 0.1721202735830799
[I 2024-04-17 16:35:01,113] Trial 96 finished with value: 0.17685960579151377 and parameters: {'subsample': 0.5148697353905858, 'dropout_rate': 0.5688549493582022, 'n_estimators': 186, 'learning_rate': 0.07351393012072571}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.2552690555238246
Fold 2 IBS: 0.14242222735539223
Fold 3 IBS: 0.19832205398740438
Fold 4 IBS: 0.17003726248759515
Fold 5 IBS: 0.18703961727390805
[I 2024-04-17 16:35:07,903] Trial 97 finished with value: 0.19061804332562488 and parameters: {'subsample': 0.640459544752755, 'dropout_rate': 0.6732325125506005, 'n_estimators': 390, 'learning_rate': 0.07861564278128286}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.24402421110757114
Fold 2 IBS: 0.13971151780081725
Fold 3 IBS: 0.18305520872685443
Fold 4 IBS: 0.16589531431563193
Fold 5 IBS: 0.1792555846328399
[I 2024-04-17 16:35:10,874] Trial 98 finished with value: 0.18238836731674293 and parameters: {'subsample': 0.681282738429498, 'dropout_rate': 0.7310803049616198, 'n_estimators': 232, 'learning_rate': 0.09771327455148511}. Best is trial 26 with value: 0.1761905708629028.
Fold 1 IBS: 0.21750121843717718
Fold 2 IBS: 0.15319578783249826
Fold 3 IBS: 0.17215212503731323
Fold 4 IBS: 0.17138790509504098
Fold 5 IBS: 0.17243300922671206
[I 2024-04-17 16:35:12,287] Trial 99 finished with value: 0.17733400912574834 and parameters: {'subsample': 0.9999285344615276, 'dropout_rate': 0.4284947251241432, 'n_estimators': 114, 'learning_rate': 0.0939688786565343}. Best is trial 26 with value: 0.1761905708629028.


* Best trial for IBS:
 FrozenTrial(number=26, state=TrialState.COMPLETE, values=[0.1761905708629028], datetime_start=datetime.datetime(2024, 4, 17, 16, 32, 11, 986257), datetime_complete=datetime.datetime(2024, 4, 17, 16, 32, 13, 598438), params={'subsample': 0.6817267275162041, 'dropout_rate': 0.4868646496386122, 'n_estimators': 130, 'learning_rate': 0.09970917701467895}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=26, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.6817267275162041, 'dropout_rate': 0.4868646496386122, 'n_estimators': 130, 'learning_rate': 0.09970917701467895}


* Best Score for IBS:
 0.1761905708629028

In [72]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [73]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.685
train_ibs:  0.176

#### Test

In [74]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [75]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.15371010694861154,
                                              learning_rate=0.07406154516747154,
                                              n_estimators=200,
                                              random_state=123,
                                              subsample=0.494715020211662)

C-index score: 0.58

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.4868646496386122,
                                              learning_rate=0.09970917701467895,
                                              n_estimators=130,
                                              random_state=123,
                                              subsample=0.6817267275162041)

IBS: 0.228

In [76]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [77]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.870   1.0
ExtraSurvivalTrees               0.807   2.0
CoxElastic                       0.737   3.0
CoxLasso                         0.724   4.0
CoxPH                            0.722   5.0
GradientBoosting                 0.701   6.0
ComponentwiseGradientBoosting    0.685   7.0
CoxRidge                         0.678   8.0

In [78]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
CoxPH                          0.173   2.0
CoxLasso                       0.173   2.0
CoxElastic                     0.173   2.0
Randomsurvivalforest           0.176   4.5
ComponentwiseGradientBoosting  0.176   4.5
ExtraSurvivalTrees             0.184   6.0
GradientBoosting               0.214   7.0
CoxRidge                       0.217   8.0

In [79]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
GradientBoosting                 0.583   1.0
CoxPH                            0.580   3.0
ExtraSurvivalTrees               0.580   3.0
ComponentwiseGradientBoosting    0.580   3.0
CoxLasso                         0.579   5.5
CoxElastic                       0.579   5.5
CoxRidge                         0.563   7.0
Randomsurvivalforest             0.557   8.0

In [80]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
GradientBoosting               0.220   1.0
CoxRidge                       0.221   2.0
ExtraSurvivalTrees             0.228   3.5
ComponentwiseGradientBoosting  0.228   3.5
Randomsurvivalforest           0.230   5.0
CoxElastic                     0.244   6.0
CoxLasso                       0.245   7.0
CoxPH                          0.246   8.0

In [81]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/os/minmax/plsr/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_os_minmax_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [82]:
from datetime import date

current_date = date.today()
print(current_date)

2024-04-17