In [38]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import RobustScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

In [39]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [40]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [41]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [42]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

In [43]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

### COX assumption in Train data

In [44]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                test_statistic      p  -log2(p)
MTV                       0.07   0.80      0.33
SUVpeak                   0.17   0.68      0.56
TLG                       0.38   0.54      0.90
age                       0.09   0.77      0.38
cavum_oris                0.00   0.99      0.02
charlson                  1.66   0.20      2.34
female                    2.67   0.10      3.29
histgrade_high            0.13   0.72      0.48
hpv_related              12.67 <0.005     11.39
hypopharynx               0.00   0.99      0.01
larynx                    0.00   0.98      0.03
oropharynx                0.00   0.98      0.02
pack_years                0.06   0.81      0.31
uicc8_III-IV              0.09   0.76      0.39

In [45]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['hpv_related'], dtype='object')

In [46]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                test_statistic    p  -log2(p)
MTV                       0.59 0.44      1.17
SUVpeak                   0.01 0.91      0.14
TLG                       0.00 0.96      0.06
age                       0.43 0.51      0.97
cavum_oris                0.41 0.52      0.94
charlson                  0.87 0.35      1.51
female                    2.39 0.12      3.04
histgrade_high            0.11 0.74      0.44
hpv_related               6.46 0.01      6.51
hypopharynx               0.04 0.84      0.25
larynx                    0.97 0.33      1.62
oropharynx                0.85 0.36      1.49
pack_years                0.00 0.99      0.01
uicc8_III-IV              0.00 0.95      0.07

In [47]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['hpv_related'], dtype='object')

###### penalizer values essentially result in same result

## Test dataset: MAASTRO

In [48]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [49]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [50]:
# need to choose patient_id from MAASTRO_D1 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [51]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG,OS,OS_event
0,1,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342,44.43,1.0
3,4,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979,37.20,1.0
4,6,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782,19.00,1.0
95,111,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212,72.07,0.0

In [52]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [53]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, OS, OS_event]
Index: []

In [54]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [55]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [56]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 14)
y_train:  (139,)

In [57]:
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [58]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 16)

In [59]:
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X.values, i) 
                          for i in range(len(X.columns))] 

vif_data

           feature        VIF
0              age   1.136852
1           female   1.197250
2       cavum_oris   7.993011
3       oropharynx  60.199385
4      hypopharynx  11.118710
5           larynx  14.183474
6   histgrade_high   1.150479
7      hpv_related   4.309385
8         charlson   1.302350
9       pack_years   1.647441
10    uicc8_III-IV   2.026695
11         SUVpeak   2.157147
12             MTV   5.247552
13             TLG   6.368452

# Standardization

In [60]:
original_X = X.copy()

In [61]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

## Standardize the data but not the categorical columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']
### Separate the categorical and non-categorical columns
X_categorical = X[categorical_columns]
X_numeric = X.drop(categorical_columns, axis=1)
X_numeric_columns = X_numeric.columns
X_numeric_index = X_numeric.index

### Standardize non-categorical and then concat with the categorical
scaler = RobustScaler()  
X_numeric_std = scaler.fit_transform(X_numeric)
X_numeric_std = pd.DataFrame(X_numeric_std, columns=X_numeric_columns, index=X_numeric_index)
X_std = pd.concat([X_categorical, X_numeric_std], axis=1)

## Sort the order of the columns as it was in the clinical train 
X_std = X_std[original_X.columns]

In [68]:
# Standardize X_MAASTRO 
MAASTRO_new = X_MAASTRO.copy()
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[X_new.columns]

In [69]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = MAASTRO_new_std

In [70]:
X_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,54.238356,1,0,1,0,0,1,0.0,0,0.000000,0.0,14.473272,7.934,86.228420
1,54.539726,0,0,0,0,1,0,0.0,1,27.404795,0.0,5.044678,1.656,7.040100
2,59.019178,0,1,0,0,0,1,0.0,1,41.019178,1.0,7.839043,14.502,83.569669
3,70.726027,0,0,0,0,1,0,0.0,1,37.500000,0.0,2.880631,2.440,5.567091
4,67.865753,0,0,0,0,1,0,0.0,1,53.000000,0.0,5.402006,3.668,16.150550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,60.435616,0,0,1,0,0,1,1.0,0,0.000000,0.0,9.290139,3.650,26.280140
135,68.794521,0,0,1,0,0,1,1.0,0,0.000000,1.0,7.172883,18.967,101.754834
136,57.498630,0,0,1,0,0,1,1.0,1,39.498630,0.0,13.873187,6.370,66.273201
137,65.684932,0,0,1,0,0,1,1.0,1,71.527397,1.0,7.507419,12.443,71.832443
138,61.676712,0,0,1,0,0,1,1.0,0,2.250000,1.0,13.053465,7.983,78.647696

In [71]:
X_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,-0.497635,1,0,1,0,0,1,0.0,0,-0.747766,0.0,0.600320,0.075008,0.231096
1,-0.473435,0,0,0,0,1,0,0.0,1,0.159774,0.0,-0.690705,-0.466877,-0.387041
2,-0.113739,0,1,0,0,0,1,0.0,1,0.610629,1.0,-0.308082,0.641923,0.210342
3,0.826312,0,0,0,0,1,0,0.0,1,0.494088,0.0,-0.987020,-0.399206,-0.398539
4,0.596634,0,0,0,0,1,0,0.0,1,1.007387,0.0,-0.641777,-0.293211,-0.315926
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,0.000000,0,0,1,0,0,1,1.0,0,-0.747766,0.0,-0.109388,-0.294765,-0.236855
135,0.671213,0,0,1,0,0,1,1.0,0,-0.747766,1.0,-0.399297,1.027319,0.352293
136,-0.235838,0,0,1,0,0,1,1.0,1,0.560275,0.0,0.518153,-0.059989,0.075327
137,0.421516,0,0,1,0,0,1,1.0,1,1.620942,1.0,-0.353490,0.464201,0.118722
138,0.099659,0,0,1,0,0,1,1.0,0,-0.673255,1.0,0.405911,0.079237,0.171921

In [72]:
MAASTRO_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623
1,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700
2,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342
3,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979
4,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782
95,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868
96,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274
97,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492
98,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212

In [73]:
MAASTRO_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,-0.436476,0,0,1,0,0,1,1,1,-0.747766,0,0.732497,1.361702,1.615732
1,-0.436476,0,0,1,0,0,0,0,0,-0.085444,1,-0.172482,-0.121272,-0.153327
2,-0.436476,0,0,1,0,0,0,0,1,-0.549070,1,0.463784,0.062665,0.140609
3,0.045320,1,0,0,0,1,1,0,1,0.742458,1,-0.199405,0.072763,-0.076742
4,0.768012,0,0,1,0,0,1,1,1,1.206084,0,-0.041772,0.705364,0.398213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0.446816,1,0,0,0,1,0,0,0,1.073619,1,2.909606,-0.082431,0.685886
95,0.205918,0,0,0,0,1,0,0,1,5.014436,1,0.404287,0.010099,0.098289
96,0.205918,0,0,1,0,0,1,1,1,-0.747766,1,-0.156713,0.812913,0.358846
97,-0.516775,0,0,1,0,0,1,1,0,-0.747766,0,0.560744,0.251694,0.363804
98,0.125619,0,0,0,1,0,1,0,0,0.576878,1,0.044615,-0.308144,-0.219112

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [74]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:40:38,225] A new study created in memory with name: no-name-82791b90-4757-4adf-b3b6-28f4fa620c06

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143

[I 2024-04-13 23:40:38,884] A new study created in memory with name: no-name-c2b11e71-9d6c-4db6-b768-d1d4fa4d48f4

Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:38,878] Trial 0 finished with value: 0.7580581707147598 and parameters: {}. Best is trial 0 with value: 0.7580581707147598.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7580581707147598], datetime_start=datetime.datetime(2024, 4, 13, 23, 40, 38, 311308), datetime_complete=datetime.datetime(2024, 4, 13, 23, 40, 38, 878696), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7580581707147598

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.18224790157453513
Fold 2 IBS: 0.17936185172891464
Fold 3 IBS: 0.1578324465205439
Fold 4 IBS: 0.14729407963908342
Fold 5 IBS: 0.2737533899229805
[I 2024-04-13 23:40:39,606] Trial 0 finished with value: 0.18809793387721152 and parameters: {}. Best is trial 0 with value: 0.18809793387721152.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.18809793387721152], datetime_start=datetime.datetime(2024, 4, 13, 23, 40, 38, 943353), datetime_complete=datetime.datetime(2024, 4, 13, 23, 40, 39, 606298), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.18809793387721152

In [75]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [76]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.758
train_ibs:  0.188

#### Test

In [77]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [78]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.585
IBS score: 0.288

In [79]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [80]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [81]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:40:40,755] A new study created in memory with name: no-name-ae8ca3ad-ddce-4148-9ad4-06f5d677c144

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-13 23:40:41,053] A new study created in memory with name: no-name-53e2c304-0a0d-4613-84a6-7cc8eed07a3e

Fold 1 C-index: 0.5606060606060606
Fold 2 C-index: 0.6763392857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6197183098591549
[I 2024-04-13 23:40:41,047] Trial 0 finished with value: 0.708041591995394 and parameters: {}. Best is trial 0 with value: 0.708041591995394.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.708041591995394], datetime_start=datetime.datetime(2024, 4, 13, 23, 40, 40, 816017), datetime_complete=datetime.datetime(2024, 4, 13, 23, 40, 41, 47007), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.708041591995394

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652057302996
Fold 2 IBS: 0.22157790931615212
Fold 3 IBS: 0.20453593725187927
Fold 4 IBS: 0.22473802829011877
Fold 5 IBS: 0.21812431395361034
[I 2024-04-13 23:40:41,444] Trial 0 finished with value: 0.21659054187695811 and parameters: {}. Best is trial 0 with value: 0.21659054187695811.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054187695811], datetime_start=datetime.datetime(2024, 4, 13, 23, 40, 41, 86848), datetime_complete=datetime.datetime(2024, 4, 13, 23, 40, 41, 444419), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054187695811

In [82]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [83]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.708
train_ibs:  0.217

#### Test

In [84]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [85]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.576

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [86]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [87]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:40:42,207] A new study created in memory with name: no-name-02f296cd-5db8-460d-8200-473dfcbc04fe

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848

[I 2024-04-13 23:40:43,034] A new study created in memory with name: no-name-87518a9e-8c7f-4a9b-b8d1-9bc4410ad949

Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:43,015] Trial 0 finished with value: 0.7590875381579397 and parameters: {}. Best is trial 0 with value: 0.7590875381579397.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7590875381579397], datetime_start=datetime.datetime(2024, 4, 13, 23, 40, 42, 233966), datetime_complete=datetime.datetime(2024, 4, 13, 23, 40, 43, 14966), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7590875381579397

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.1825535042004205
Fold 2 IBS: 0.17773002786634848
Fold 3 IBS: 0.15619742941827763
Fold 4 IBS: 0.14485273175547853
Fold 5 IBS: 0.27153624181650643
[I 2024-04-13 23:40:43,991] Trial 0 finished with value: 0.18657398701140632 and parameters: {}. Best is trial 0 with value: 0.18657398701140632.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.18657398701140632], datetime_start=datetime.datetime(2024, 4, 13, 23, 40, 43, 68993), datetime_complete=datetime.datetime(2024, 4, 13, 23, 40, 43, 991283), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.18657398701140632

In [88]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [89]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.759
train_ibs:  0.187

#### Test

In [90]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [91]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.591

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.284

In [92]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [93]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:40:44,586] A new study created in memory with name: no-name-96bae138-8d2f-416c-b302-4b506e626927

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:45,441] Trial 0 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7573018238722253.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:46,349] Trial 1 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.7573018238722253.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:47,251] Trial 2 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.7573018238722253.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:48,000] Trial 3 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.7573018238722253.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:48,791] Trial 4 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 4 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:49,509] Trial 5 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 4 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:50,459] Trial 6 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:51,466] Trial 7 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:52,241] Trial 8 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:52,947] Trial 9 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:53,775] Trial 10 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:54,497] Trial 11 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:55,212] Trial 12 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9946087870438435}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:56,013] Trial 13 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8521165717679541}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:56,837] Trial 14 finished with value: 0.7555650848728281 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:57,577] Trial 15 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8659212232095017}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:58,282] Trial 16 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8592866247617579}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:58,950] Trial 17 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.8140829029918109}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:40:59,673] Trial 18 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.5819463953201167}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:00,370] Trial 19 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9535087433508003}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:01,682] Trial 20 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.7540198302114602}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:02,690] Trial 21 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9453140545316446}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:03,504] Trial 22 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9952149413953396}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:04,228] Trial 23 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8898693182098678}. Best is trial 6 with value: 0.7590875381579397.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:04,933] Trial 24 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.7805647035680947}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:05,646] Trial 25 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9368557715647121}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:06,415] Trial 26 finished with value: 0.7217769320973337 and parameters: {'l1_ratio': 0.015423757551295547}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:07,250] Trial 27 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.6022588122254688}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:07,985] Trial 28 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.6499747968454208}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:08,737] Trial 29 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9010792166439672}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:09,622] Trial 30 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.8107108448948633}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:10,467] Trial 31 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9790160904460925}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:11,199] Trial 32 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9889509715055751}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:11,964] Trial 33 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9033942188713268}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:12,674] Trial 34 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9969906676119189}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:13,401] Trial 35 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9145273991086058}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:14,207] Trial 36 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.23789482035414378}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:14,860] Trial 37 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.7342815000174964}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:15,543] Trial 38 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8450450825036032}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:16,221] Trial 39 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.35153102114871604}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:16,982] Trial 40 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.6762726602177129}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:17,895] Trial 41 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9440922341009589}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:18,713] Trial 42 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9508021678872735}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:19,513] Trial 43 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.8119687552544277}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:20,335] Trial 44 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9305771147376857}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:21,082] Trial 45 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8746070404800059}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:21,856] Trial 46 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.4933969994831382}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:22,685] Trial 47 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9991045282580079}. Best is trial 6 with value: 0.7590875381579397.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:23,516] Trial 48 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.7768768486379835}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:24,333] Trial 49 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.8386679916089912}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:25,110] Trial 50 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.945704027694845}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:25,827] Trial 51 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.947113067248926}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:26,475] Trial 52 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8871531144268382}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:27,128] Trial 53 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9647303296134437}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:27,795] Trial 54 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9101963565788189}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:28,482] Trial 55 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8584736152002521}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:29,149] Trial 56 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9583038567719465}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:29,801] Trial 57 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9088458560426897}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:30,647] Trial 58 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.5410039830059447}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:31,543] Trial 59 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.7776014045307951}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:32,420] Trial 60 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.8320809461721039}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:33,240] Trial 61 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.995042831172216}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:34,026] Trial 62 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9833336524256188}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:34,808] Trial 63 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9260812672003349}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:35,520] Trial 64 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9651321290795338}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:36,244] Trial 65 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8891583365337647}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:37,041] Trial 66 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9944626215764547}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:37,876] Trial 67 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.44627959226748903}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:38,715] Trial 68 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8787453958599145}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:39,651] Trial 69 finished with value: 0.7564579420156853 and parameters: {'l1_ratio': 0.14881965141192482}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:40,643] Trial 70 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.926199751086326}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:41,663] Trial 71 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9583211281444385}. Best is trial 6 with value: 0.7590875381579397.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:42,728] Trial 72 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9675780206021779}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:43,677] Trial 73 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9201870333114552}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:44,510] Trial 74 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9984463773526076}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:45,347] Trial 75 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9354982366369866}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:46,091] Trial 76 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8824734629144222}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:47,033] Trial 77 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.8236759033518168}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:48,018] Trial 78 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9749829000406383}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:49,044] Trial 79 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.7120921418578845}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:50,097] Trial 80 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8582408686713943}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:50,984] Trial 81 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9078718287578732}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:51,792] Trial 82 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9409357128568329}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:52,558] Trial 83 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9704105127362406}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:53,463] Trial 84 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9065123247915838}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:54,315] Trial 85 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.33218847491866843}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:55,241] Trial 86 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9333679653567835}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:56,018] Trial 87 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9645334149932889}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:56,843] Trial 88 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8034397848038504}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:57,754] Trial 89 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8595909063527372}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:58,536] Trial 90 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.6264569387493186}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:41:59,337] Trial 91 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9744891524849301}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:42:00,084] Trial 92 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9467672077926574}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:42:01,197] Trial 93 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9007179824941103}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:42:02,214] Trial 94 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9821745786347279}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:42:03,159] Trial 95 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9991107887307169}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359

Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:42:04,062] Trial 96 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9480329728505581}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:42:04,934] Trial 97 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9253945573892306}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:42:05,822] Trial 98 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8888191592108757}. Best is trial 6 with value: 0.7590875381579397.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8088235294117647

[I 2024-04-13 23:42:06,762] A new study created in memory with name: no-name-35d33586-5152-426d-bc57-435f9e33d9ab

Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:42:06,750] Trial 99 finished with value: 0.7590875381579397 and parameters: {'l1_ratio': 0.9790522544395087}. Best is trial 6 with value: 0.7590875381579397.


* Best trial for C-index:
 FrozenTrial(number=6, state=TrialState.COMPLETE, values=[0.7590875381579397], datetime_start=datetime.datetime(2024, 4, 13, 23, 40, 49, 514697), datetime_complete=datetime.datetime(2024, 4, 13, 23, 40, 50, 459639), params={'l1_ratio': 0.980766121964777}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=6, value=None)


* Best Score for C-index:
 0.7590875381579397

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1826077931498605
Fold 2 IBS: 0.17807036541987384
Fold 3 IBS: 0.15601223631782776
Fold 4 IBS: 0.14500598472390383
Fold 5 IBS: 0.27109809628569953
[I 2024-04-13 23:42:08,075] Trial 0 finished with value: 0.18655889517943308 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.18655889517943308.
Fold 1 IBS: 0.18280515480908568
Fold 2 IBS: 0.1787673748211404
Fold 3 IBS: 0.15594917775011002
Fold 4 IBS: 0.14527384594992757
Fold 5 IBS: 0.2706297038179428
[I 2024-04-13 23:42:09,141] Trial 1 finished with value: 0.1866850514296413 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.18655889517943308.
Fold 1 IBS: 0.18283959551120751
Fold 2 IBS: 0.1789034782187268
Fold 3 IBS: 0.15588280754342965
Fold 4 IBS: 0.14527339338927314
Fold 5 IBS: 0.27072271225104416
[I 2024-04-13 23:42:10,181] Trial 2 finished with value: 0.18672439738273625 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.18655889517943308.
Fold 1 IBS: 0.18269083703715247
Fold 2 IBS: 0.17824151958848677
Fold 3 IBS: 0.15591457667393618
Fold 4 IBS: 0.1450741932721901
Fold 5 IBS: 0.27085142141636576
[I 2024-04-13 23:42:11,238] Trial 3 finished with value: 0.18655450959762626 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.18264122351301076
Fold 2 IBS: 0.17793323720343782
Fold 3 IBS: 0.15606781105767853
Fold 4 IBS: 0.1450418706099519
Fold 5 IBS: 0.2711998560306844
[I 2024-04-13 23:42:12,247] Trial 4 finished with value: 0.18657679968295268 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.18273472482340478
Fold 2 IBS: 0.17849445214976406
Fold 3 IBS: 0.1559818560483452
Fold 4 IBS: 0.14507911058700038
Fold 5 IBS: 0.27078842497022654
[I 2024-04-13 23:42:13,179] Trial 5 finished with value: 0.1866157137157482 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.18256372550264655
Fold 2 IBS: 0.17773389449462526
Fold 3 IBS: 0.15616448253246193
Fold 4 IBS: 0.14482775962569494
Fold 5 IBS: 0.27148365638963884
[I 2024-04-13 23:42:14,047] Trial 6 finished with value: 0.18655470370901353 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.18261547842865086
Fold 2 IBS: 0.1780753319527246
Fold 3 IBS: 0.15602522531456955
Fold 4 IBS: 0.1449828710481812
Fold 5 IBS: 0.27128073363460226
[I 2024-04-13 23:42:14,899] Trial 7 finished with value: 0.1865959280757457 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.1827123362621636
Fold 2 IBS: 0.17837050421207892
Fold 3 IBS: 0.15583552785635008
Fold 4 IBS: 0.1450759945544246
Fold 5 IBS: 0.2709306611894222
[I 2024-04-13 23:42:15,783] Trial 8 finished with value: 0.1865850048148879 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.1827292055902861
Fold 2 IBS: 0.17851083900885975
Fold 3 IBS: 0.1560101543281866
Fold 4 IBS: 0.14519530556508764
Fold 5 IBS: 0.2708128541442532
[I 2024-04-13 23:42:16,777] Trial 9 finished with value: 0.18665167172733463 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.18286486394723134
Fold 2 IBS: 0.1792310976114425
Fold 3 IBS: 0.15588001568840515
Fold 4 IBS: 0.1453148922429175
Fold 5 IBS: 0.2706220414188599
[I 2024-04-13 23:42:17,968] Trial 10 finished with value: 0.1867825821817713 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.1825568821237114
Fold 2 IBS: 0.17773034227790271
Fold 3 IBS: 0.15618648198666146
Fold 4 IBS: 0.14505552012180328
Fold 5 IBS: 0.2715154031827299
[I 2024-04-13 23:42:19,244] Trial 11 finished with value: 0.18660892593856176 and parameters: {'l1_ratio': 0.9935631508087679}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.18255820325733113
Fold 2 IBS: 0.1777309748441187
Fold 3 IBS: 0.15618221767233847
Fold 4 IBS: 0.14484221858596472
Fold 5 IBS: 0.2715073487517354
[I 2024-04-13 23:42:20,695] Trial 12 finished with value: 0.18656419262229768 and parameters: {'l1_ratio': 0.9910674734971466}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.18257281403004313
Fold 2 IBS: 0.17790102012629783
Fold 3 IBS: 0.15609543461674957
Fold 4 IBS: 0.14500923820856282
Fold 5 IBS: 0.2713481413847956
[I 2024-04-13 23:42:22,061] Trial 13 finished with value: 0.18658532967328978 and parameters: {'l1_ratio': 0.8136827928100274}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.18268186044575005
Fold 2 IBS: 0.1782368910627946
Fold 3 IBS: 0.15599980462494384
Fold 4 IBS: 0.14509835029657453
Fold 5 IBS: 0.27090744603747197
[I 2024-04-13 23:42:23,375] Trial 14 finished with value: 0.18658487049350703 and parameters: {'l1_ratio': 0.5610548123801923}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.21391557848213757
Fold 2 IBS: 0.22107139399267756
Fold 3 IBS: 0.20388855432802175
Fold 4 IBS: 0.2238984364143001
Fold 5 IBS: 0.21804094926996068
[I 2024-04-13 23:42:23,860] Trial 15 finished with value: 0.21616298249741953 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.1826073057876505
Fold 2 IBS: 0.17789486944473148
Fold 3 IBS: 0.15600571215562362
Fold 4 IBS: 0.1450421598802711
Fold 5 IBS: 0.27140586485094165
[I 2024-04-13 23:42:24,942] Trial 16 finished with value: 0.18659118242384368 and parameters: {'l1_ratio': 0.8335637155569282}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.18265207028923378
Fold 2 IBS: 0.1782240508887139
Fold 3 IBS: 0.1560752996102591
Fold 4 IBS: 0.14496850030350425
Fold 5 IBS: 0.27106123442885116
[I 2024-04-13 23:42:25,846] Trial 17 finished with value: 0.18659623110411244 and parameters: {'l1_ratio': 0.589082129474626}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.1825758123483651
Fold 2 IBS: 0.17790278288421968
Fold 3 IBS: 0.15610737777200306
Fold 4 IBS: 0.1450002257293421
Fold 5 IBS: 0.2713272267953035
[I 2024-04-13 23:42:26,977] Trial 18 finished with value: 0.1865826851058467 and parameters: {'l1_ratio': 0.8081045010661086}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.18255781612803482
Fold 2 IBS: 0.17775661540925888
Fold 3 IBS: 0.15618056272784828
Fold 4 IBS: 0.14493967906143967
Fold 5 IBS: 0.2714397145636379
[I 2024-04-13 23:42:28,049] Trial 19 finished with value: 0.18657487757804392 and parameters: {'l1_ratio': 0.905414835186219}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.18276788070669217
Fold 2 IBS: 0.17876955777187067
Fold 3 IBS: 0.15593932696722562
Fold 4 IBS: 0.14525554204792893
Fold 5 IBS: 0.2705870482958834
[I 2024-04-13 23:42:29,304] Trial 20 finished with value: 0.18666387115792016 and parameters: {'l1_ratio': 0.282446306369455}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.1826292311863998
Fold 2 IBS: 0.1780731250924807
Fold 3 IBS: 0.15592933059438857
Fold 4 IBS: 0.14494924586279895
Fold 5 IBS: 0.2712099044203729
[I 2024-04-13 23:42:30,368] Trial 21 finished with value: 0.18655816743128817 and parameters: {'l1_ratio': 0.6687519605744899}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.1826456455540683
Fold 2 IBS: 0.17822054674191645
Fold 3 IBS: 0.15589121960853056
Fold 4 IBS: 0.14498619942351398
Fold 5 IBS: 0.27110225490762296
[I 2024-04-13 23:42:31,500] Trial 22 finished with value: 0.18656917324713046 and parameters: {'l1_ratio': 0.5970376666049447}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.18270355785732506
Fold 2 IBS: 0.17835011666713502
Fold 3 IBS: 0.15590347673243007
Fold 4 IBS: 0.14513026934956216
Fold 5 IBS: 0.2707902815005553
[I 2024-04-13 23:42:32,562] Trial 23 finished with value: 0.1865755404214015 and parameters: {'l1_ratio': 0.49943326007438504}. Best is trial 3 with value: 0.18655450959762626.
Fold 1 IBS: 0.18256570571526617
Fold 2 IBS: 0.17775394526166216
Fold 3 IBS: 0.15611801528074948
Fold 4 IBS: 0.14491658439365018
Fold 5 IBS: 0.2714004283737716
[I 2024-04-13 23:42:34,027] Trial 24 finished with value: 0.1865509358050199 and parameters: {'l1_ratio': 0.8894962894093121}. Best is trial 24 with value: 0.1865509358050199.

Fold 1 IBS: 0.18256466387128126
Fold 2 IBS: 0.17775325710813536
Fold 3 IBS: 0.1561219585406359
Fold 4 IBS: 0.14491963112125805
Fold 5 IBS: 0.27139257235325287
[I 2024-04-13 23:42:35,675] Trial 25 finished with value: 0.1865504165989127 and parameters: {'l1_ratio': 0.891573855041803}. Best is trial 25 with value: 0.1865504165989127.
Fold 1 IBS: 0.18255235052419533
Fold 2 IBS: 0.17775294056676047
Fold 3 IBS: 0.15620082583229222
Fold 4 IBS: 0.1449556806578617
Fold 5 IBS: 0.27147732185473183
[I 2024-04-13 23:42:36,544] Trial 26 finished with value: 0.1865878238871683 and parameters: {'l1_ratio': 0.9167426588025347}. Best is trial 25 with value: 0.1865504165989127.
Fold 1 IBS: 0.1825905733374704
Fold 2 IBS: 0.1779132401664048
Fold 3 IBS: 0.15602721625065713
Fold 4 IBS: 0.14493665338556005
Fold 5 IBS: 0.27118662677252925
[I 2024-04-13 23:42:37,619] Trial 27 finished with value: 0.1865308619825243 and parameters: {'l1_ratio': 0.7760895212945972}. Best is trial 27 with value: 0.1865308619825243.
Fold 1 IBS: 0.18259510410824747
Fold 2 IBS: 0.1779158605579818
Fold 3 IBS: 0.15600961871022026
Fold 4 IBS: 0.14492296417051917
Fold 5 IBS: 0.2711700267229019
[I 2024-04-13 23:42:38,592] Trial 28 finished with value: 0.18652271485397415 and parameters: {'l1_ratio': 0.7683363738804736}. Best is trial 28 with value: 0.18652271485397415.
Fold 1 IBS: 0.18260502327795294
Fold 2 IBS: 0.17792156862922004
Fold 3 IBS: 0.15597308893072398
Fold 4 IBS: 0.1448929746657141
Fold 5 IBS: 0.27131788816514085
[I 2024-04-13 23:42:39,507] Trial 29 finished with value: 0.18654210873375038 and parameters: {'l1_ratio': 0.7517868604245541}. Best is trial 28 with value: 0.18652271485397415.
Fold 1 IBS: 0.18261185966792842
Fold 2 IBS: 0.17792546861457925
Fold 3 IBS: 0.1559478314411275
Fold 4 IBS: 0.14487238618511716
Fold 5 IBS: 0.27128892727672954
[I 2024-04-13 23:42:40,504] Trial 30 finished with value: 0.1865292946370964 and parameters: {'l1_ratio': 0.7408200982006781}. Best is trial 28 with value: 0.18652271485397415.
Fold 1 IBS: 0.18260640478664936
Fold 2 IBS: 0.1779223553277648
Fold 3 IBS: 0.1559687388506135
Fold 4 IBS: 0.14488880689218891
Fold 5 IBS: 0.2713089474458942
[I 2024-04-13 23:42:41,545] Trial 31 finished with value: 0.18653905066062212 and parameters: {'l1_ratio': 0.7495457082237318}. Best is trial 28 with value: 0.18652271485397415.
Fold 1 IBS: 0.18260044044998908
Fold 2 IBS: 0.1779189548999425
Fold 3 IBS: 0.15598876836804357
Fold 4 IBS: 0.14490673396503878
Fold 5 IBS: 0.271116995233997
[I 2024-04-13 23:42:42,418] Trial 32 finished with value: 0.1865063785834022 and parameters: {'l1_ratio': 0.7593137056556459}. Best is trial 32 with value: 0.1865063785834022.
Fold 1 IBS: 0.18265728450948712
Fold 2 IBS: 0.1780879405343523
Fold 3 IBS: 0.15603240641991406
Fold 4 IBS: 0.14506061652334484
Fold 5 IBS: 0.2710100897320731
[I 2024-04-13 23:42:43,408] Trial 33 finished with value: 0.18656966754383428 and parameters: {'l1_ratio': 0.6296883388353313}. Best is trial 32 with value: 0.1865063785834022.
Fold 1 IBS: 0.18260744869089177
Fold 2 IBS: 0.17789494533880745
Fold 3 IBS: 0.1560051822726103
Fold 4 IBS: 0.14504178133449344
Fold 5 IBS: 0.271404971298842
[I 2024-04-13 23:42:45,236] Trial 34 finished with value: 0.18659086578712897 and parameters: {'l1_ratio': 0.8333143946457621}. Best is trial 32 with value: 0.1865063785834022.
Fold 1 IBS: 0.18260218250678387
Fold 2 IBS: 0.17791994681343937
Fold 3 IBS: 0.1559820235274813
Fold 4 IBS: 0.1449014726138657
Fold 5 IBS: 0.2711046941240053
[I 2024-04-13 23:42:46,723] Trial 35 finished with value: 0.18650206391711513 and parameters: {'l1_ratio': 0.7564356164034841}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18263288769442884
Fold 2 IBS: 0.1780750075236745
Fold 3 IBS: 0.15591532136396322
Fold 4 IBS: 0.1449383451726754
Fold 5 IBS: 0.27118646968934473
[I 2024-04-13 23:42:47,844] Trial 36 finished with value: 0.1865496062888173 and parameters: {'l1_ratio': 0.663616886799847}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18260634698152806
Fold 2 IBS: 0.1780694866529748
Fold 3 IBS: 0.1560177552647166
Fold 4 IBS: 0.14501031825127617
Fold 5 IBS: 0.271108205076365
[I 2024-04-13 23:42:48,859] Trial 37 finished with value: 0.18656242244537213 and parameters: {'l1_ratio': 0.698722290315196}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18261471841377233
Fold 2 IBS: 0.17792708168972424
Fold 3 IBS: 0.15593685585915681
Fold 4 IBS: 0.14486387069535547
Fold 5 IBS: 0.2712705422014972
[I 2024-04-13 23:42:49,691] Trial 38 finished with value: 0.1865226137719012 and parameters: {'l1_ratio': 0.7363242745539392}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18270049082437242
Fold 2 IBS: 0.17838629622856075
Fold 3 IBS: 0.15588852212674353
Fold 4 IBS: 0.14498903541953606
Fold 5 IBS: 0.2707307707193594
[I 2024-04-13 23:42:50,573] Trial 39 finished with value: 0.18653902306371442 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18265931861303897
Fold 2 IBS: 0.17808894731772362
Fold 3 IBS: 0.15602550063653403
Fold 4 IBS: 0.1450569411225568
Fold 5 IBS: 0.27099709343198
[I 2024-04-13 23:42:51,787] Trial 40 finished with value: 0.1865655602243667 and parameters: {'l1_ratio': 0.6271343434971994}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18259818996573102
Fold 2 IBS: 0.1779176631083521
Fold 3 IBS: 0.15599747669249583
Fold 4 IBS: 0.1449135333292124
Fold 5 IBS: 0.2711328833536287
[I 2024-04-13 23:42:52,650] Trial 41 finished with value: 0.186511949289884 and parameters: {'l1_ratio': 0.7630628561460056}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18259908262003
Fold 2 IBS: 0.17788910060215926
Fold 3 IBS: 0.15604349323005412
Fold 4 IBS: 0.1448668507410439
Fold 5 IBS: 0.27126611032588266
[I 2024-04-13 23:42:53,605] Trial 42 finished with value: 0.186532927503834 and parameters: {'l1_ratio': 0.8517057718383786}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18260461043195175
Fold 2 IBS: 0.1780684294409142
Fold 3 IBS: 0.15602438616618725
Fold 4 IBS: 0.14501552298992504
Fold 5 IBS: 0.27112032898792693
[I 2024-04-13 23:42:54,701] Trial 43 finished with value: 0.186566655603381 and parameters: {'l1_ratio': 0.7014092758549647}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18258229036773355
Fold 2 IBS: 0.17790840249644024
Fold 3 IBS: 0.15609303633939484
Fold 4 IBS: 0.14496176309738446
Fold 5 IBS: 0.27124475352946376
[I 2024-04-13 23:42:56,008] Trial 44 finished with value: 0.18655804916608337 and parameters: {'l1_ratio': 0.7906814170029204}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18254282829908444
Fold 2 IBS: 0.1777441491434789
Fold 3 IBS: 0.15607180629323938
Fold 4 IBS: 0.14499589876555957
Fold 5 IBS: 0.27136418580413185
[I 2024-04-13 23:42:57,044] Trial 45 finished with value: 0.1865437736610988 and parameters: {'l1_ratio': 0.9476344366724742}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18274634493575245
Fold 2 IBS: 0.17859084086447638
Fold 3 IBS: 0.15595647133160537
Fold 4 IBS: 0.14514851388018493
Fold 5 IBS: 0.2707146198458692
[I 2024-04-13 23:42:58,064] Trial 46 finished with value: 0.18663135817157767 and parameters: {'l1_ratio': 0.3799368247494892}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.1825966650993097
Fold 2 IBS: 0.17788780098578713
Fold 3 IBS: 0.15605241378870088
Fold 4 IBS: 0.1448737205592962
Fold 5 IBS: 0.27128240254790376
[I 2024-04-13 23:42:59,174] Trial 47 finished with value: 0.18653860059619953 and parameters: {'l1_ratio': 0.8560900496369801}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18267428116550555
Fold 2 IBS: 0.17825384324132565
Fold 3 IBS: 0.15604231742061372
Fold 4 IBS: 0.1450093239188165
Fold 5 IBS: 0.27095818750925765
[I 2024-04-13 23:43:00,174] Trial 48 finished with value: 0.1865875906511038 and parameters: {'l1_ratio': 0.5265762047062671}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18263598232827086
Fold 2 IBS: 0.17793038939700137
Fold 3 IBS: 0.15608580855545337
Fold 4 IBS: 0.1450541305070894
Fold 5 IBS: 0.2712326804790455
[I 2024-04-13 23:43:01,114] Trial 49 finished with value: 0.18658779825337207 and parameters: {'l1_ratio': 0.7272181182543819}. Best is trial 35 with value: 0.18650206391711513.

Fold 1 IBS: 0.18265222584925453
Fold 2 IBS: 0.17808199968168006
Fold 3 IBS: 0.156072645532077
Fold 4 IBS: 0.14510246717123726
Fold 5 IBS: 0.2710827089951062
[I 2024-04-13 23:43:01,950] Trial 50 finished with value: 0.18659840944587103 and parameters: {'l1_ratio': 0.644904156608236}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18259512317265011
Fold 2 IBS: 0.17791587155937344
Fold 3 IBS: 0.15600954469632755
Fold 4 IBS: 0.1449229065237299
Fold 5 IBS: 0.271169892694163
[I 2024-04-13 23:43:02,852] Trial 51 finished with value: 0.1865226677292488 and parameters: {'l1_ratio': 0.7683040387171605}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.1825875510915538
Fold 2 IBS: 0.17791148348938352
Fold 3 IBS: 0.15607292551131957
Fold 4 IBS: 0.14494580024908724
Fold 5 IBS: 0.2712079998274259
[I 2024-04-13 23:43:03,875] Trial 52 finished with value: 0.186545152033754 and parameters: {'l1_ratio': 0.7813477291140531}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18260206568919854
Fold 2 IBS: 0.17806687626054624
Fold 3 IBS: 0.15603402262709326
Fold 4 IBS: 0.14502315213994488
Fold 5 IBS: 0.2711381236036925
[I 2024-04-13 23:43:04,829] Trial 53 finished with value: 0.18657284806409508 and parameters: {'l1_ratio': 0.7053825469318116}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18259512034983572
Fold 2 IBS: 0.17791586993044323
Fold 3 IBS: 0.1560095556553266
Fold 4 IBS: 0.1449229150593207
Fold 5 IBS: 0.27116991253941714
[I 2024-04-13 23:43:05,890] Trial 54 finished with value: 0.18652267470686867 and parameters: {'l1_ratio': 0.7683088263332946}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18259003141805677
Fold 2 IBS: 0.17790039252663728
Fold 3 IBS: 0.15607692318295216
Fold 4 IBS: 0.14489243195917012
Fold 5 IBS: 0.27131485005927564
[I 2024-04-13 23:43:06,760] Trial 55 finished with value: 0.18655492582921837 and parameters: {'l1_ratio': 0.8683145385798297}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18253287557965775
Fold 2 IBS: 0.17774121888183927
Fold 3 IBS: 0.15608822122830202
Fold 4 IBS: 0.14500770107942268
Fold 5 IBS: 0.2713940109126726
[I 2024-04-13 23:43:07,594] Trial 56 finished with value: 0.1865528055363789 and parameters: {'l1_ratio': 0.9565210309518093}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.1826739921772433
Fold 2 IBS: 0.1782327953229638
Fold 3 IBS: 0.15601952163575447
Fold 4 IBS: 0.14491959041209293
Fold 5 IBS: 0.2709569771072874
[I 2024-04-13 23:43:08,542] Trial 57 finished with value: 0.18656057533106837 and parameters: {'l1_ratio': 0.5698097387877163}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18256623821410956
Fold 2 IBS: 0.17789713164410773
Fold 3 IBS: 0.15598989290567442
Fold 4 IBS: 0.1450308541116605
Fold 5 IBS: 0.2713940232386377
[I 2024-04-13 23:43:09,501] Trial 58 finished with value: 0.18657562802283797 and parameters: {'l1_ratio': 0.8261754098039634}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.1825780419732591
Fold 2 IBS: 0.17790411258054287
Fold 3 IBS: 0.1560988033792726
Fold 4 IBS: 0.14499347611370034
Fold 5 IBS: 0.271311403041274
[I 2024-04-13 23:43:10,498] Trial 59 finished with value: 0.18657716741760977 and parameters: {'l1_ratio': 0.8039312033287387}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.1826439389453551
Fold 2 IBS: 0.1780967261969656
Fold 3 IBS: 0.15592351362320525
Fold 4 IBS: 0.14501182383067596
Fold 5 IBS: 0.27114124931725775
[I 2024-04-13 23:43:11,957] Trial 60 finished with value: 0.18656345038269193 and parameters: {'l1_ratio': 0.6078526800926836}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18260200200895516
Fold 2 IBS: 0.17791984355309753
Fold 3 IBS: 0.15598272227744672
Fold 4 IBS: 0.1449020177792042
Fold 5 IBS: 0.271105968766373
[I 2024-04-13 23:43:13,220] Trial 61 finished with value: 0.1865025108770153 and parameters: {'l1_ratio': 0.7567329100345977}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18262555893597973
Fold 2 IBS: 0.17807978604749874
Fold 3 IBS: 0.15599761583001612
Fold 4 IBS: 0.1449606510346468
Fold 5 IBS: 0.27123341926513783
[I 2024-04-13 23:43:14,242] Trial 62 finished with value: 0.18657940622265587 and parameters: {'l1_ratio': 0.6740065631356977}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.182606504127136
Fold 2 IBS: 0.17792241184414653
Fold 3 IBS: 0.15596835590051092
Fold 4 IBS: 0.14488850724866006
Fold 5 IBS: 0.2713083046094194
[I 2024-04-13 23:43:15,257] Trial 63 finished with value: 0.18653881674597458 and parameters: {'l1_ratio': 0.7493850495525394}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18264961921833872
Fold 2 IBS: 0.17806614111079438
Fold 3 IBS: 0.15603861871555444
Fold 4 IBS: 0.14502675602680407
Fold 5 IBS: 0.27114652904760167
[I 2024-04-13 23:43:16,350] Trial 64 finished with value: 0.18658553282381868 and parameters: {'l1_ratio': 0.7072739496248137}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18257929185190555
Fold 2 IBS: 0.17790485659359095
Fold 3 IBS: 0.15609390518871175
Fold 4 IBS: 0.14499642741321403
Fold 5 IBS: 0.2713025313476947
[I 2024-04-13 23:43:17,693] Trial 65 finished with value: 0.18657540247902338 and parameters: {'l1_ratio': 0.8016089506133643}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18261839399332477
Fold 2 IBS: 0.17792914730647472
Fold 3 IBS: 0.156091209455771
Fold 4 IBS: 0.14485282129875804
Fold 5 IBS: 0.2712469116576971
[I 2024-04-13 23:43:19,048] Trial 66 finished with value: 0.18654769674240515 and parameters: {'l1_ratio': 0.7306200042269332}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18290299925564293
Fold 2 IBS: 0.1792304034161154
Fold 3 IBS: 0.15591863557993318
Fold 4 IBS: 0.14535196616602902
Fold 5 IBS: 0.27068927638978635
[I 2024-04-13 23:43:20,378] Trial 67 finished with value: 0.18681865616150137 and parameters: {'l1_ratio': 0.10022359348974141}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18254748408716528
Fold 2 IBS: 0.1777496564689295
Fold 3 IBS: 0.1560327532217117
Fold 4 IBS: 0.14496982207992248
Fold 5 IBS: 0.2715099493796385
[I 2024-04-13 23:43:21,732] Trial 68 finished with value: 0.18656193304747348 and parameters: {'l1_ratio': 0.9269387738672743}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.182571402242274
Fold 2 IBS: 0.17789739175374703
Fold 3 IBS: 0.15609640102099168
Fold 4 IBS: 0.14489777585536825
Fold 5 IBS: 0.2713621836203841
[I 2024-04-13 23:43:23,210] Trial 69 finished with value: 0.186565030898553 and parameters: {'l1_ratio': 0.8782443299620215}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18259661763003168
Fold 2 IBS: 0.17791675848863062
Fold 3 IBS: 0.15600357401532022
Fold 4 IBS: 0.14491825531285316
Fold 5 IBS: 0.2711591005336789
[I 2024-04-13 23:43:24,508] Trial 70 finished with value: 0.18651886119610292 and parameters: {'l1_ratio': 0.7657032474347231}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18259550630806595
Fold 2 IBS: 0.17791609259897664
Fold 3 IBS: 0.1560080573735181
Fold 4 IBS: 0.1449217480455881
Fold 5 IBS: 0.2711672160922506
[I 2024-04-13 23:43:25,659] Trial 71 finished with value: 0.1865217240836799 and parameters: {'l1_ratio': 0.7676547527055263}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.1826103040342354
Fold 2 IBS: 0.17789645982884686
Fold 3 IBS: 0.1559945961684207
Fold 4 IBS: 0.1450342162261091
Fold 5 IBS: 0.2713871117725687
[I 2024-04-13 23:43:26,699] Trial 72 finished with value: 0.18658453760603616 and parameters: {'l1_ratio': 0.8283602200413122}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18263054171011894
Fold 2 IBS: 0.17807379806998933
Fold 3 IBS: 0.15592424772307428
Fold 4 IBS: 0.14494534692919375
Fold 5 IBS: 0.2712014624894224
[I 2024-04-13 23:43:27,762] Trial 73 finished with value: 0.18655507938435972 and parameters: {'l1_ratio': 0.6669068824882646}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18259756877112734
Fold 2 IBS: 0.17791730591950367
Fold 3 IBS: 0.15599988513195312
Fold 4 IBS: 0.14491538082016628
Fold 5 IBS: 0.27115241618312463
[I 2024-04-13 23:43:29,118] Trial 74 finished with value: 0.186516511365175 and parameters: {'l1_ratio': 0.764103938636392}. Best is trial 35 with value: 0.18650206391711513.

Fold 1 IBS: 0.18263920187061838
Fold 2 IBS: 0.17793214078682978
Fold 3 IBS: 0.15607474994700646
Fold 4 IBS: 0.14504733776578016
Fold 5 IBS: 0.27121251621018866
[I 2024-04-13 23:43:30,109] Trial 75 finished with value: 0.1865811893160847 and parameters: {'l1_ratio': 0.7224568234068146}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18258278766661878
Fold 2 IBS: 0.17790869369486004
Fold 3 IBS: 0.15609113733434268
Fold 4 IBS: 0.1449602564495217
Fold 5 IBS: 0.271241259157135
[I 2024-04-13 23:43:31,240] Trial 76 finished with value: 0.18655682686049563 and parameters: {'l1_ratio': 0.7897917878683155}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18261361359526307
Fold 2 IBS: 0.17807420709146848
Fold 3 IBS: 0.15598991959182848
Fold 4 IBS: 0.14498845457625684
Fold 5 IBS: 0.2710575111288036
[I 2024-04-13 23:43:32,743] Trial 77 finished with value: 0.1865447411967241 and parameters: {'l1_ratio': 0.6876396731724712}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18257237966970608
Fold 2 IBS: 0.17789297386681607
Fold 3 IBS: 0.15601892799541855
Fold 4 IBS: 0.1448479090110257
Fold 5 IBS: 0.27122114867790426
[I 2024-04-13 23:43:34,022] Trial 78 finished with value: 0.18651066784417414 and parameters: {'l1_ratio': 0.8398240259716396}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18257312217558308
Fold 2 IBS: 0.17789340600755935
Fold 3 IBS: 0.1560159183869135
Fold 4 IBS: 0.1448456076981029
Fold 5 IBS: 0.2712156447517945
[I 2024-04-13 23:43:35,297] Trial 79 finished with value: 0.18650873980399066 and parameters: {'l1_ratio': 0.8383912960822442}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18256977965886267
Fold 2 IBS: 0.17789144409965163
Fold 3 IBS: 0.15602956647462518
Fold 4 IBS: 0.14485609572588304
Fold 5 IBS: 0.27124058375777826
[I 2024-04-13 23:43:36,401] Trial 80 finished with value: 0.18651749394336017 and parameters: {'l1_ratio': 0.8449224726749075}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18259038269457917
Fold 2 IBS: 0.17789085679905822
Fold 3 IBS: 0.15603364428516814
Fold 4 IBS: 0.14485923267723833
Fold 5 IBS: 0.2712480248780176
[I 2024-04-13 23:43:37,992] Trial 81 finished with value: 0.18652442826681231 and parameters: {'l1_ratio': 0.8468909053193819}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18256031962482996
Fold 2 IBS: 0.1777582860921083
Fold 3 IBS: 0.15617130522699668
Fold 4 IBS: 0.1449323249867451
Fold 5 IBS: 0.27142251033858944
[I 2024-04-13 23:43:38,998] Trial 82 finished with value: 0.1865689492538539 and parameters: {'l1_ratio': 0.9003177038972877}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18257157990052622
Fold 2 IBS: 0.17790029285630973
Fold 3 IBS: 0.15610023843139556
Fold 4 IBS: 0.14501497721189124
Fold 5 IBS: 0.27135674935605486
[I 2024-04-13 23:43:39,911] Trial 83 finished with value: 0.18658876755123552 and parameters: {'l1_ratio': 0.8159996028892195}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18259304509220228
Fold 2 IBS: 0.177885849858798
Fold 3 IBS: 0.15606579263243814
Fold 4 IBS: 0.14488390213233518
Fold 5 IBS: 0.2713095854443406
[I 2024-04-13 23:43:40,918] Trial 84 finished with value: 0.18654763503202282 and parameters: {'l1_ratio': 0.8627261744599716}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18253346278445426
Fold 2 IBS: 0.17773879177853158
Fold 3 IBS: 0.15612274881531948
Fold 4 IBS: 0.14501817435168232
Fold 5 IBS: 0.2714390803235105
[I 2024-04-13 23:43:42,636] Trial 85 finished with value: 0.18657045161069963 and parameters: {'l1_ratio': 0.9644549421727473}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18254700104248853
Fold 2 IBS: 0.1777493311093386
Fold 3 IBS: 0.15603471122846077
Fold 4 IBS: 0.14497122344721164
Fold 5 IBS: 0.2715132257462872
[I 2024-04-13 23:43:43,979] Trial 86 finished with value: 0.18656309851475733 and parameters: {'l1_ratio': 0.9279582829113568}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18256816211776075
Fold 2 IBS: 0.17775556526835995
Fold 3 IBS: 0.15610872555929686
Fold 4 IBS: 0.14490729844047365
Fold 5 IBS: 0.27138358830963555
[I 2024-04-13 23:43:45,167] Trial 87 finished with value: 0.18654466793910535 and parameters: {'l1_ratio': 0.8846279552662787}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18257361984019055
Fold 2 IBS: 0.17789369532446375
Fold 3 IBS: 0.1560139023954499
Fold 4 IBS: 0.14484405557232002
Fold 5 IBS: 0.2712119574813984
[I 2024-04-13 23:43:46,203] Trial 88 finished with value: 0.18650744612276454 and parameters: {'l1_ratio': 0.8374339336742708}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.1826109992484247
Fold 2 IBS: 0.1778968429287058
Fold 3 IBS: 0.15599191470394527
Fold 4 IBS: 0.14503229949634017
Fold 5 IBS: 0.27138258554752587
[I 2024-04-13 23:43:47,422] Trial 89 finished with value: 0.18658292838498833 and parameters: {'l1_ratio': 0.8271133787248023}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.1825900245295082
Fold 2 IBS: 0.17789051119345606
Fold 3 IBS: 0.15603499495829004
Fold 4 IBS: 0.1448602715841623
Fold 5 IBS: 0.2712504916044707
[I 2024-04-13 23:43:48,573] Trial 90 finished with value: 0.18652525877397746 and parameters: {'l1_ratio': 0.8475446409215555}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18257885011739453
Fold 2 IBS: 0.17790459824697225
Fold 3 IBS: 0.1560956065642241
Fold 4 IBS: 0.1449910067333207
Fold 5 IBS: 0.2713056133430456
[I 2024-04-13 23:43:49,879] Trial 91 finished with value: 0.18657513500099143 and parameters: {'l1_ratio': 0.802414274344876}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18260485232352794
Fold 2 IBS: 0.17792147118965307
Fold 3 IBS: 0.15597374878942546
Fold 4 IBS: 0.14489349046456787
Fold 5 IBS: 0.2713189945851966
[I 2024-04-13 23:43:50,974] Trial 92 finished with value: 0.1865425114704742 and parameters: {'l1_ratio': 0.7520650732596027}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.1825879472008187
Fold 2 IBS: 0.17791171409258655
Fold 3 IBS: 0.1560374252018288
Fold 4 IBS: 0.14494460114488
Fold 5 IBS: 0.27120519818522604
[I 2024-04-13 23:43:52,342] Trial 93 finished with value: 0.18653737716506805 and parameters: {'l1_ratio': 0.7806547095350453}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18255587242439678
Fold 2 IBS: 0.177755297600418
Fold 3 IBS: 0.15618784345904438
Fold 4 IBS: 0.1449454249911839
Fold 5 IBS: 0.27145323589382225
[I 2024-04-13 23:43:53,347] Trial 94 finished with value: 0.18657953487377305 and parameters: {'l1_ratio': 0.9094578869039874}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18257138163154452
Fold 2 IBS: 0.17790017594323906
Fold 3 IBS: 0.15610101382606154
Fold 4 IBS: 0.1450155660607068
Fold 5 IBS: 0.2713581320007205
[I 2024-04-13 23:43:54,428] Trial 95 finished with value: 0.1865892538924545 and parameters: {'l1_ratio': 0.8163728851029237}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18264895736760994
Fold 2 IBS: 0.17808037531913928
Fold 3 IBS: 0.1560705163836381
Fold 4 IBS: 0.1451112689518779
Fold 5 IBS: 0.27110353187847
[I 2024-04-13 23:43:55,474] Trial 96 finished with value: 0.18660292998014705 and parameters: {'l1_ratio': 0.6492222212914176}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18259080536703365
Fold 2 IBS: 0.1779008314230045
Fold 3 IBS: 0.15607406600273618
Fold 4 IBS: 0.1448902368573108
Fold 5 IBS: 0.2713246432628468
[I 2024-04-13 23:43:56,461] Trial 97 finished with value: 0.1865561165825864 and parameters: {'l1_ratio': 0.8668741091612653}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.18275889152713756
Fold 2 IBS: 0.17867783075564533
Fold 3 IBS: 0.15593064933156395
Fold 4 IBS: 0.14517387604270754
Fold 5 IBS: 0.27063972757368043
[I 2024-04-13 23:43:58,301] Trial 98 finished with value: 0.18663619504614698 and parameters: {'l1_ratio': 0.3410246190042779}. Best is trial 35 with value: 0.18650206391711513.
Fold 1 IBS: 0.1826021994142825
Fold 2 IBS: 0.17791995648272838
Fold 3 IBS: 0.1559819580914199
Fold 4 IBS: 0.14490142155939173
Fold 5 IBS: 0.2711045747536779
[I 2024-04-13 23:44:00,463] Trial 99 finished with value: 0.1865020220603001 and parameters: {'l1_ratio': 0.7564077859143797}. Best is trial 99 with value: 0.1865020220603001.


* Best trial for IBS:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.1865020220603001], datetime_start=datetime.datetime(2024, 4, 13, 23, 43, 58, 307587), datetime_complete=datetime.datetime(2024, 4, 13, 23, 44, 0, 462839), params={'l1_ratio': 0.7564077859143797}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=99, value=None)


* Best Score for IBS:
 0.1865020220603001

In [94]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [95]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.759
train_ibs:  0.187

#### Test

In [96]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [97]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.980766121964777)

test_cindex : 0.591

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.7564077859143797)

test_ibs:  0.284

In [98]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [99]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:44:02,979] A new study created in memory with name: no-name-2a332b85-577b-4da3-81b0-b310285f748b

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6408450704225352
[I 2024-04-13 23:44:34,402] Trial 0 finished with value: 0.7372744686944293 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7372744686944293.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:44:41,951] Trial 1 finished with value: 0.74027341750814 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.74027341750814.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6619718309859155
[I 2024-04-13 23:44:47,847] Trial 2 finished with value: 0.7431341569351123 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 23:44:50,329] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 23:44:53,774] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:45:05,625] Trial 5 finished with value: 0.7299704758481619 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.75
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:45:16,621] Trial 6 finished with value: 0.7171141106323402 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 23:45:22,564] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6126760563380281
[I 2024-04-13 23:45:36,544] Trial 8 finished with value: 0.5225352112676056 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:45:44,027] Trial 9 finished with value: 0.7250144025097357 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 23:45:44,654] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 26, 'oob_score': True, 'max_samples': 0.9607577284547746, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6713615023474179
[I 2024-04-13 23:45:49,190] Trial 11 finished with value: 0.7414728561808361 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1579906038170908, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:45:53,183] Trial 12 finished with value: 0.7380805853192668 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 147, 'oob_score': False, 'max_samples': 0.8619834498485652, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1611753146667314, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 23:45:55,769] Trial 13 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.10013306718236009, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1567471583060459, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7464788732394366
[I 2024-04-13 23:45:58,438] Trial 14 finished with value: 0.8012393138587386 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 204, 'oob_score': True, 'max_samples': 0.8364130211722378, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1306449501762567, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7370892018779343
[I 2024-04-13 23:46:01,423] Trial 15 finished with value: 0.7949512064262649 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 197, 'oob_score': True, 'max_samples': 0.9835664616143871, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0921839163034627, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.

Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8755274261603375
Fold 5 C-index: 0.7230046948356808
[I 2024-04-13 23:46:02,873] Trial 16 finished with value: 0.7913196149300414 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2, 'n_estimators': 62, 'oob_score': True, 'max_samples': 0.9622193970781673, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07748782870655765, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8839662447257384
Fold 5 C-index: 0.7417840375586855
[I 2024-04-13 23:46:04,853] Trial 17 finished with value: 0.7952544618554078 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 127, 'oob_score': True, 'max_samples': 0.8172323984404596, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10327357472994507, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 23:46:06,234] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.525862463381169, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7089201877934272
[I 2024-04-13 23:46:06,613] Trial 19 finished with value: 0.7740929694743747 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.8094383772852811, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2171861810731355, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8713080168776371
Fold 5 C-index: 0.704225352112676
[I 2024-04-13 23:46:08,375] Trial 20 finished with value: 0.7896403509052692 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 131, 'oob_score': True, 'max_samples': 0.7024632981250558, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11709282828400099, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7276995305164319
[I 2024-04-13 23:46:10,795] Trial 21 finished with value: 0.7918532818563494 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 183, 'oob_score': True, 'max_samples': 0.8592332834187432, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09213353726970255, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7323943661971831
[I 2024-04-13 23:46:13,746] Trial 22 finished with value: 0.7987506334970494 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.9966124899846646, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.006871014098231751, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7230046948356808
[I 2024-04-13 23:46:17,342] Trial 23 finished with value: 0.7965507033377867 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.8404793290892639, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0023497522601186316, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7511737089201878
[I 2024-04-13 23:46:20,388] Trial 24 finished with value: 0.8010124032513863 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 228, 'oob_score': True, 'max_samples': 0.8944464461493312, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.003220931076182737, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-13 23:46:24,923] Trial 25 finished with value: 0.8009100471985094 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 244, 'oob_score': True, 'max_samples': 0.9947609548616138, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04884572997850131, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7511737089201878
[I 2024-04-13 23:46:29,891] Trial 26 finished with value: 0.8019323166712997 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.8936722563667562, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05058696770992366, 'warm_start': True}. Best is trial 26 with value: 0.8019323166712997.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7370892018779343
[I 2024-04-13 23:46:35,271] Trial 27 finished with value: 0.7848754931720334 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 351, 'oob_score': True, 'max_samples': 0.7589607003643692, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05616441169904532, 'warm_start': True}. Best is trial 26 with value: 0.8019323166712997.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.6502347417840375
[I 2024-04-13 23:46:41,478] Trial 28 finished with value: 0.7687300510570361 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.47643241204116027, 'max_features': None, 'min_weight_fraction_leaf': 0.21228506833672414, 'warm_start': True}. Best is trial 26 with value: 0.8019323166712997.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7136150234741784
[I 2024-04-13 23:46:49,407] Trial 29 finished with value: 0.791216072808157 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18639977321756945, 'warm_start': True}. Best is trial 26 with value: 0.8019323166712997.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7981220657276995
[I 2024-04-13 23:46:55,281] Trial 30 finished with value: 0.8141045941707695 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.8995699838431843, 'max_features': None, 'min_weight_fraction_leaf': 0.048019257453591285, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7981220657276995
[I 2024-04-13 23:47:01,295] Trial 31 finished with value: 0.8102976168343801 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 317, 'oob_score': True, 'max_samples': 0.8965443067001324, 'max_features': None, 'min_weight_fraction_leaf': 0.04869831874272522, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-13 23:47:07,162] Trial 32 finished with value: 0.8044151254239035 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 317, 'oob_score': True, 'max_samples': 0.7822231835771817, 'max_features': None, 'min_weight_fraction_leaf': 0.05953475058332531, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.755868544600939
[I 2024-04-13 23:47:12,037] Trial 33 finished with value: 0.8002008917150547 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.7587808099894491, 'max_features': None, 'min_weight_fraction_leaf': 0.06414988767677843, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7699530516431925
[I 2024-04-13 23:47:18,208] Trial 34 finished with value: 0.802539604149412 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 392, 'oob_score': True, 'max_samples': 0.9277369756073641, 'max_features': None, 'min_weight_fraction_leaf': 0.13073113131665734, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7746478873239436
[I 2024-04-13 23:47:26,329] Trial 35 finished with value: 0.8025908514105005 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.9215912670469352, 'max_features': None, 'min_weight_fraction_leaf': 0.12213968035691111, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7652582159624414
[I 2024-04-13 23:47:33,345] Trial 36 finished with value: 0.8030592181442181 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 422, 'oob_score': True, 'max_samples': 0.7521477069490586, 'max_features': None, 'min_weight_fraction_leaf': 0.028614277170057895, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7652582159624414
[I 2024-04-13 23:47:37,406] Trial 37 finished with value: 0.7924417951105628 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 285, 'oob_score': True, 'max_samples': 0.6723788047810191, 'max_features': None, 'min_weight_fraction_leaf': 0.027521497544371276, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7652582159624414
[I 2024-04-13 23:47:45,490] Trial 38 finished with value: 0.8059128596008007 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 452, 'oob_score': True, 'max_samples': 0.7390641925180915, 'max_features': None, 'min_weight_fraction_leaf': 0.0747020966452816, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6455399061032864
[I 2024-04-13 23:47:54,429] Trial 39 finished with value: 0.770986545074277 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 482, 'oob_score': True, 'max_samples': 0.6220569630425845, 'max_features': None, 'min_weight_fraction_leaf': 0.2635408988115671, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7652582159624414
[I 2024-04-13 23:47:59,923] Trial 40 finished with value: 0.8014911829899953 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 314, 'oob_score': True, 'max_samples': 0.5663987587631532, 'max_features': None, 'min_weight_fraction_leaf': 0.07499456126338316, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7652582159624414
[I 2024-04-13 23:48:09,206] Trial 41 finished with value: 0.8059128596008007 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 439, 'oob_score': True, 'max_samples': 0.7534073290864295, 'max_features': None, 'min_weight_fraction_leaf': 0.03371263169436823, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.755868544600939
[I 2024-04-13 23:48:16,021] Trial 42 finished with value: 0.8004185708465463 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.7191743052052858, 'max_features': None, 'min_weight_fraction_leaf': 0.03134587591441676, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-13 23:48:22,233] Trial 43 finished with value: 0.8044421817009597 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.7630755401354222, 'max_features': None, 'min_weight_fraction_leaf': 0.08864460050779976, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7605633802816901
[I 2024-04-13 23:48:31,307] Trial 44 finished with value: 0.7970569598688273 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 434, 'oob_score': True, 'max_samples': 0.6530853458961033, 'max_features': None, 'min_weight_fraction_leaf': 0.0960200605067859, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7746478873239436
[I 2024-04-13 23:48:35,007] Trial 45 finished with value: 0.8063373500099402 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 369, 'oob_score': False, 'max_samples': 0.7241711356177275, 'max_features': None, 'min_weight_fraction_leaf': 0.03945374601794358, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-13 23:48:50,639] Trial 46 finished with value: 0.7213832269889107 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.7253224444871529, 'max_features': None, 'min_weight_fraction_leaf': 0.03678143977799287, 'warm_start': False}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7605633802816901
[I 2024-04-13 23:48:54,994] Trial 47 finished with value: 0.7895586843791148 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 408, 'oob_score': False, 'max_samples': 0.3630824057039081, 'max_features': None, 'min_weight_fraction_leaf': 0.07375724144112171, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.636150234741784
[I 2024-04-13 23:49:07,820] Trial 48 finished with value: 0.7518177358789349 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 470, 'oob_score': False, 'max_samples': 0.8664880785038714, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.38812198780775825, 'warm_start': False}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7276995305164319
[I 2024-04-13 23:49:11,408] Trial 49 finished with value: 0.79501517952681 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 442, 'oob_score': False, 'max_samples': 0.8009921187460273, 'max_features': None, 'min_weight_fraction_leaf': 0.14468128914092981, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7605633802816901
[I 2024-04-13 23:49:13,738] Trial 50 finished with value: 0.8025838944631485 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.5979222342836801, 'max_features': None, 'min_weight_fraction_leaf': 0.010569144430309353, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7746478873239436
[I 2024-04-13 23:49:17,097] Trial 51 finished with value: 0.8027595552556749 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.737951588098304, 'max_features': None, 'min_weight_fraction_leaf': 0.08276842957644326, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.784037558685446
[I 2024-04-13 23:49:24,962] Trial 52 finished with value: 0.8046323522601799 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.88848382237019, 'max_features': None, 'min_weight_fraction_leaf': 0.10800154944324664, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7323943661971831
[I 2024-04-13 23:49:28,689] Trial 53 finished with value: 0.800061200877051 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 421, 'oob_score': False, 'max_samples': 0.9477043092007602, 'max_features': None, 'min_weight_fraction_leaf': 0.1769969783833071, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7887323943661971
[I 2024-04-13 23:49:33,546] Trial 54 finished with value: 0.8075268254192226 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 296, 'oob_score': True, 'max_samples': 0.8862399763900326, 'max_features': None, 'min_weight_fraction_leaf': 0.04347302641797581, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7605633802816901
[I 2024-04-13 23:49:38,809] Trial 55 finished with value: 0.8100342825585477 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.8308423379101402, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04184905264916955, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6713615023474179
[I 2024-04-13 23:49:52,086] Trial 56 finished with value: 0.7307990843706159 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 282, 'oob_score': True, 'max_samples': 0.8390380366939857, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04576803383695833, 'warm_start': False}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.755868544600939
[I 2024-04-13 23:49:55,703] Trial 57 finished with value: 0.8035130393589224 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.862792308947798, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06959281888785387, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 23:50:00,706] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.9167198766277185, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-13 23:50:07,558] Trial 59 finished with value: 0.8154047485458795 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 260, 'oob_score': True, 'max_samples': 0.960673091645226, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.016185485823452278, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6666666666666666
[I 2024-04-13 23:50:19,757] Trial 60 finished with value: 0.7281182409672728 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 259, 'oob_score': True, 'max_samples': 0.9694253886674298, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.017099050018490658, 'warm_start': False}. Best is trial 59 with value: 0.8154047485458795.

Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7652582159624414
[I 2024-04-13 23:50:27,891] Trial 61 finished with value: 0.8091270566720341 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.8024635915627699, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04437120929765639, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7699530516431925
[I 2024-04-13 23:50:32,920] Trial 62 finished with value: 0.8100170485218674 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.8255198768266782, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04384835034305919, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7699530516431925
[I 2024-04-13 23:50:37,884] Trial 63 finished with value: 0.8116391962302029 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 247, 'oob_score': True, 'max_samples': 0.8867126274469075, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018776766987265683, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7699530516431925
[I 2024-04-13 23:50:42,139] Trial 64 finished with value: 0.805082894192702 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 247, 'oob_score': True, 'max_samples': 0.822935057311086, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012420915832592992, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7887323943661971
[I 2024-04-13 23:50:45,421] Trial 65 finished with value: 0.8127164933462323 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 210, 'oob_score': True, 'max_samples': 0.9479411108137946, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.019799142307208247, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7887323943661971
[I 2024-04-13 23:50:47,854] Trial 66 finished with value: 0.8152263609296293 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 166, 'oob_score': True, 'max_samples': 0.9503349354445524, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02249332834269111, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.784037558685446
[I 2024-04-13 23:50:50,970] Trial 67 finished with value: 0.8117067729375418 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 168, 'oob_score': True, 'max_samples': 0.947093672368275, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01713780998356157, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.784037558685446
[I 2024-04-13 23:50:54,443] Trial 68 finished with value: 0.8089947790490772 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.944193226589343, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002610024525408112, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7934272300469484
[I 2024-04-13 23:50:58,509] Trial 69 finished with value: 0.816613418694436 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 185, 'oob_score': True, 'max_samples': 0.9994241275208928, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018458075829861618, 'warm_start': True}. Best is trial 69 with value: 0.816613418694436.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7887323943661971
[I 2024-04-13 23:51:04,374] Trial 70 finished with value: 0.8107505717647113 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 212, 'oob_score': True, 'max_samples': 0.9759466742205646, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.020962084356569866, 'warm_start': True}. Best is trial 69 with value: 0.816613418694436.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7887323943661971
[I 2024-04-13 23:51:08,230] Trial 71 finished with value: 0.809906689908171 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 213, 'oob_score': True, 'max_samples': 0.9691411143781642, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.019131120871457744, 'warm_start': True}. Best is trial 69 with value: 0.816613418694436.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7934272300469484
[I 2024-04-13 23:51:11,733] Trial 72 finished with value: 0.8163018383661023 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 172, 'oob_score': True, 'max_samples': 0.9857485121561103, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.019949674867014808, 'warm_start': True}. Best is trial 69 with value: 0.816613418694436.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7934272300469484
[I 2024-04-13 23:51:15,742] Trial 73 finished with value: 0.8209526975590314 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 179, 'oob_score': True, 'max_samples': 0.9999465776424662, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0037053086158703695, 'warm_start': True}. Best is trial 73 with value: 0.8209526975590314.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.784037558685446
[I 2024-04-13 23:51:22,038] Trial 74 finished with value: 0.8089728600398164 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 161, 'oob_score': True, 'max_samples': 0.9451824063260522, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.006367895628996485, 'warm_start': True}. Best is trial 73 with value: 0.8209526975590314.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7887323943661971
[I 2024-04-13 23:51:27,641] Trial 75 finished with value: 0.8193500558621478 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 188, 'oob_score': True, 'max_samples': 0.9983757102481674, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.00202750601418214, 'warm_start': True}. Best is trial 73 with value: 0.8209526975590314.

Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7746478873239436
[I 2024-04-13 23:51:34,464] Trial 76 finished with value: 0.8120677808474076 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 190, 'oob_score': True, 'max_samples': 0.992384429953266, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06509728021815406, 'warm_start': True}. Best is trial 73 with value: 0.8209526975590314.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8028169014084507
[I 2024-04-13 23:51:37,969] Trial 77 finished with value: 0.8245454518214682 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 138, 'oob_score': True, 'max_samples': 0.994249602929978, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.003950036087865894, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7934272300469484
[I 2024-04-13 23:51:42,834] Trial 78 finished with value: 0.8200379214069133 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 139, 'oob_score': True, 'max_samples': 0.9921516335417828, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0013870857819101067, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-13 23:51:46,028] Trial 79 finished with value: 0.8145453138629154 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 131, 'oob_score': True, 'max_samples': 0.9936071962591497, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.001248251048872611, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.6807511737089202
[I 2024-04-13 23:51:51,742] Trial 80 finished with value: 0.7350889356536794 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 104, 'oob_score': True, 'max_samples': 0.9980073532203214, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.027351555411740894, 'warm_start': False}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7793427230046949
[I 2024-04-13 23:51:55,243] Trial 81 finished with value: 0.814530945119259 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 134, 'oob_score': True, 'max_samples': 0.974317190473141, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008552111924736726, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.784037558685446
[I 2024-04-13 23:51:57,614] Trial 82 finished with value: 0.818405951458202 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 73, 'oob_score': True, 'max_samples': 0.9200032426792089, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004694893977022773, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.784037558685446
[I 2024-04-13 23:51:59,572] Trial 83 finished with value: 0.816209618379516 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 77, 'oob_score': True, 'max_samples': 0.9644628063092593, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05687217713082389, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7699530516431925
[I 2024-04-13 23:52:01,321] Trial 84 finished with value: 0.8122353006098141 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 43, 'oob_score': True, 'max_samples': 0.925618686700756, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002296274259735591, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.784037558685446
[I 2024-04-13 23:52:04,021] Trial 85 finished with value: 0.8104992933979698 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 80, 'oob_score': True, 'max_samples': 0.912496637320817, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06207048371618876, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7887323943661971
[I 2024-04-13 23:52:07,709] Trial 86 finished with value: 0.8114849995979849 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 146, 'oob_score': True, 'max_samples': 0.97217788579977, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03336570424835292, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.784037558685446
[I 2024-04-13 23:52:10,449] Trial 87 finished with value: 0.8229024307173397 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 90, 'oob_score': True, 'max_samples': 0.9977866104840274, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05743230682168733, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.784037558685446
[I 2024-04-13 23:52:13,050] Trial 88 finished with value: 0.8163898256753228 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 87, 'oob_score': True, 'max_samples': 0.9290745100371565, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.055244525623157625, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7034313725490197
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.755868544600939
[I 2024-04-13 23:52:15,480] Trial 89 finished with value: 0.7348861423976064 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.16405866867269464, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03211514251936686, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.715962441314554
[I 2024-04-13 23:52:16,873] Trial 90 finished with value: 0.7889841593617299 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 44, 'oob_score': True, 'max_samples': 0.9275901377744842, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2513921457170648, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.

Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7793427230046949
[I 2024-04-13 23:52:19,412] Trial 91 finished with value: 0.8154508585391724 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.9984694614507701, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05353258404318052, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8713080168776371
Fold 5 C-index: 0.704225352112676
[I 2024-04-13 23:52:21,725] Trial 92 finished with value: 0.7935889758097764 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.9795045559078126, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.30990393575918357, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7934272300469484
[I 2024-04-13 23:52:24,192] Trial 93 finished with value: 0.8139388966416563 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 93, 'oob_score': True, 'max_samples': 0.9084682802153162, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.056428548931904784, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7699530516431925
[I 2024-04-13 23:52:26,356] Trial 94 finished with value: 0.8132041893160448 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 62, 'oob_score': True, 'max_samples': 0.9288744492993337, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08347470326932997, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7652582159624414
[I 2024-04-13 23:52:31,253] Trial 95 finished with value: 0.8036708753502536 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 181, 'oob_score': True, 'max_samples': 0.9612484718465076, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09744509645373221, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7887323943661971
[I 2024-04-13 23:52:34,420] Trial 96 finished with value: 0.8082626231905751 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 146, 'oob_score': True, 'max_samples': 0.8773134009465923, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0004414494070137942, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7981220657276995
[I 2024-04-13 23:52:37,351] Trial 97 finished with value: 0.825818370590428 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.9995515317027949, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.032175807966512454, 'warm_start': True}. Best is trial 97 with value: 0.825818370590428.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.6924882629107981
[I 2024-04-13 23:52:40,458] Trial 98 finished with value: 0.7931972050153308 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 121, 'oob_score': True, 'max_samples': 0.9818733759466801, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.34016797358596224, 'warm_start': True}. Best is trial 97 with value: 0.825818370590428.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.869198312236287

[I 2024-04-13 23:52:48,236] A new study created in memory with name: no-name-ce8fa432-dbef-47e5-b9c5-388b99c77538

Fold 5 C-index: 0.6948356807511737
[I 2024-04-13 23:52:48,215] Trial 99 finished with value: 0.733396625437319 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 111, 'oob_score': True, 'max_samples': 0.9114919789954895, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.031714611388828556, 'warm_start': False}. Best is trial 97 with value: 0.825818370590428.


* Best trial for C-index:
 FrozenTrial(number=97, state=TrialState.COMPLETE, values=[0.825818370590428], datetime_start=datetime.datetime(2024, 4, 13, 23, 52, 34, 457285), datetime_complete=datetime.datetime(2024, 4, 13, 23, 52, 37, 350769), params={'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.9995515317027949, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.032175807966512454, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=97, value=None)


* Best Score for C-index:
 0.825818370590428

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1750328804590392
Fold 2 IBS: 0.2457909346263125
Fold 3 IBS: 0.16304371295824233
Fold 4 IBS: 0.15636010174832157
Fold 5 IBS: 0.23719057610640573
[I 2024-04-13 23:53:03,938] Trial 0 finished with value: 0.19548364117966427 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.19548364117966427.
Fold 1 IBS: 0.18431216543925236
Fold 2 IBS: 0.20449576284397977
Fold 3 IBS: 0.1734496564138547
Fold 4 IBS: 0.1702249879841256
Fold 5 IBS: 0.22320286146192567
[I 2024-04-13 23:53:07,821] Trial 1 finished with value: 0.19113708682862765 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.19113708682862765.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-13 23:53:09,710] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.19113708682862765.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-13 23:53:17,569] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.19113708682862765.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-13 23:53:26,846] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.19113708682862765.
Fold 1 IBS: 0.18112177909144025
Fold 2 IBS: 0.21559325389144568
Fold 3 IBS: 0.16126717086083114
Fold 4 IBS: 0.14612944369048034
Fold 5 IBS: 0.2233514487463136
[I 2024-04-13 23:53:38,068] Trial 5 finished with value: 0.1854926192561022 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.1741078934640366
Fold 2 IBS: 0.20103465197964324
Fold 3 IBS: 0.16459803471117013
Fold 4 IBS: 0.16185722968286678
Fold 5 IBS: 0.2275095895598425
[I 2024-04-13 23:53:53,814] Trial 6 finished with value: 0.18582147987951186 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.2112963873415951
Fold 2 IBS: 0.2163217730619842
Fold 3 IBS: 0.20084732748350573
Fold 4 IBS: 0.218588755276252
Fold 5 IBS: 0.21598442308805077
[I 2024-04-13 23:54:12,610] Trial 7 finished with value: 0.21260773325027754 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-13 23:54:45,780] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.184925661127663
Fold 2 IBS: 0.2085223967682221
Fold 3 IBS: 0.17516209049302708
Fold 4 IBS: 0.17855956510549414
Fold 5 IBS: 0.2209085976393104
[I 2024-04-13 23:54:53,936] Trial 9 finished with value: 0.19361566222674337 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-13 23:55:21,317] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.18095919781067835
Fold 2 IBS: 0.20577163118124792
Fold 3 IBS: 0.1716987840867246
Fold 4 IBS: 0.17502946521027946
Fold 5 IBS: 0.2198343004178619
[I 2024-04-13 23:55:37,553] Trial 11 finished with value: 0.19065867574135845 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.9878564362760905, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3071027733658521}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.17390057719337093
Fold 2 IBS: 0.20052745262326843
Fold 3 IBS: 0.1641107464885408
Fold 4 IBS: 0.161310620284919
Fold 5 IBS: 0.22799428371541863
[I 2024-04-13 23:55:50,631] Trial 12 finished with value: 0.18556873606110355 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.831375598136572, 'max_features': None, 'min_weight_fraction_leaf': 0.34616445768228626}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.18027770462477655
Fold 2 IBS: 0.21277323191047734
Fold 3 IBS: 0.16455120069297058
Fold 4 IBS: 0.1566383560604833
Fold 5 IBS: 0.22277178793167127
[I 2024-04-13 23:56:02,026] Trial 13 finished with value: 0.1874024562440758 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 172, 'oob_score': False, 'max_samples': 0.7780367789894055, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12012408817397843}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.19012850590013755
Fold 2 IBS: 0.2508215358616786
Fold 3 IBS: 0.16250392476408873
Fold 4 IBS: 0.13720938920743592
Fold 5 IBS: 0.2363581833511397
[I 2024-04-13 23:56:24,909] Trial 14 finished with value: 0.1954043078168961 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.8286563887351183, 'max_features': None, 'min_weight_fraction_leaf': 0.09422981531813096}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.18457894361619234
Fold 2 IBS: 0.20704365739729078
Fold 3 IBS: 0.17241207107928186
Fold 4 IBS: 0.17174770550689625
Fold 5 IBS: 0.21936818212879036
[I 2024-04-13 23:56:45,429] Trial 15 finished with value: 0.1910301119456903 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.6817544899569143, 'max_features': 'auto', 'min_weight_fraction_leaf': 2.174000731099135e-05}. Best is trial 5 with value: 0.1854926192561022.

Fold 1 IBS: 0.1827776694681521
Fold 2 IBS: 0.20934680739331213
Fold 3 IBS: 0.16890212120236864
Fold 4 IBS: 0.1686588011660482
Fold 5 IBS: 0.2195767733572381
[I 2024-04-13 23:56:57,199] Trial 16 finished with value: 0.18985243451742384 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 259, 'oob_score': False, 'max_samples': 0.9684217810899436, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24786833673530304}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.2140210250926074
Fold 2 IBS: 0.22165374242688704
Fold 3 IBS: 0.20482992077952775
Fold 4 IBS: 0.2248506856151436
Fold 5 IBS: 0.21866286292181575
[I 2024-04-13 23:57:02,937] Trial 17 finished with value: 0.2168036473671963 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.6340112818214192, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3527363076520275}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.21398207456199575
Fold 2 IBS: 0.2210878885925555
Fold 3 IBS: 0.20500084248625938
Fold 4 IBS: 0.22467759051518113
Fold 5 IBS: 0.21837641563069746
[I 2024-04-13 23:57:16,738] Trial 18 finished with value: 0.21662496235733783 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 295, 'oob_score': True, 'max_samples': 0.3978019017721025, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4936228322884221}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.17751239261549384
Fold 2 IBS: 0.25254123379304744
Fold 3 IBS: 0.17260860317747417
Fold 4 IBS: 0.15329948726148748
Fold 5 IBS: 0.23725228156825823
[I 2024-04-13 23:57:18,324] Trial 19 finished with value: 0.1986427996831522 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 10, 'oob_score': False, 'max_samples': 0.7744054221786105, 'max_features': None, 'min_weight_fraction_leaf': 0.15294426956488405}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.2140058010941674
Fold 2 IBS: 0.22070271305097472
Fold 3 IBS: 0.20512571269324692
Fold 4 IBS: 0.2244581340346379
Fold 5 IBS: 0.2175740773836072
[I 2024-04-13 23:57:26,706] Trial 20 finished with value: 0.21637328765132682 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.20097738776716928, 'max_features': None, 'min_weight_fraction_leaf': 0.3111340864325056}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.17301280315188314
Fold 2 IBS: 0.19545931456517315
Fold 3 IBS: 0.1650054298323013
Fold 4 IBS: 0.1623577222774968
Fold 5 IBS: 0.22550368553678712
[I 2024-04-13 23:57:42,756] Trial 21 finished with value: 0.1842677910727283 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.8774254573678859, 'max_features': None, 'min_weight_fraction_leaf': 0.38285115003898385}. Best is trial 21 with value: 0.1842677910727283.
Fold 1 IBS: 0.17215244177111103
Fold 2 IBS: 0.18853820269712923
Fold 3 IBS: 0.16580216324267041
Fold 4 IBS: 0.16693346335577489
Fold 5 IBS: 0.22851547915283357
[I 2024-04-13 23:57:59,530] Trial 22 finished with value: 0.1843883500439038 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.8533162629857436, 'max_features': None, 'min_weight_fraction_leaf': 0.39473610054688535}. Best is trial 21 with value: 0.1842677910727283.
Fold 1 IBS: 0.17177605757487213
Fold 2 IBS: 0.1873134062038458
Fold 3 IBS: 0.16528873750502146
Fold 4 IBS: 0.16415554447420388
Fold 5 IBS: 0.22606704734165115
[I 2024-04-13 23:58:25,287] Trial 23 finished with value: 0.1829201586199189 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.9248759152889626, 'max_features': None, 'min_weight_fraction_leaf': 0.41894325026727597}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17276619506594362
Fold 2 IBS: 0.18752575408286087
Fold 3 IBS: 0.1660506832687537
Fold 4 IBS: 0.16535591796486823
Fold 5 IBS: 0.2269916388177798
[I 2024-04-13 23:58:51,755] Trial 24 finished with value: 0.18373803784004125 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.911762237036045, 'max_features': None, 'min_weight_fraction_leaf': 0.4145963396824019}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1791579050529914
Fold 2 IBS: 0.18710203409403112
Fold 3 IBS: 0.17160657333121804
Fold 4 IBS: 0.1730776073587778
Fold 5 IBS: 0.23520287606237242
[I 2024-04-13 23:59:22,582] Trial 25 finished with value: 0.18922939917987816 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.9270259482202138, 'max_features': None, 'min_weight_fraction_leaf': 0.44717127940994156}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17277943380976452
Fold 2 IBS: 0.20056722047631442
Fold 3 IBS: 0.1648928002543546
Fold 4 IBS: 0.16219739373996186
Fold 5 IBS: 0.22641514420706116
[I 2024-04-13 23:59:58,823] Trial 26 finished with value: 0.18537039849749132 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.9129740059593043, 'max_features': None, 'min_weight_fraction_leaf': 0.3870919920523195}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17240759648455306
Fold 2 IBS: 0.18549219526338728
Fold 3 IBS: 0.16616481950290676
Fold 4 IBS: 0.16561034850301004
Fold 5 IBS: 0.22653216582265312
[I 2024-04-14 00:00:29,385] Trial 27 finished with value: 0.18324142511530206 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 380, 'oob_score': False, 'max_samples': 0.9882040097907008, 'max_features': None, 'min_weight_fraction_leaf': 0.45340256450947913}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.173798138626336
Fold 2 IBS: 0.18532321108542035
Fold 3 IBS: 0.1668142641939112
Fold 4 IBS: 0.16714200768594834
Fold 5 IBS: 0.2276860831891378
[I 2024-04-14 00:01:02,262] Trial 28 finished with value: 0.18415274095615075 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.9741542767559068, 'max_features': None, 'min_weight_fraction_leaf': 0.450638299943646}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.213981238234591
Fold 2 IBS: 0.22129600200231184
Fold 3 IBS: 0.20476687908413987
Fold 4 IBS: 0.22462916295400534
Fold 5 IBS: 0.21851703166023365
[I 2024-04-14 00:01:23,008] Trial 29 finished with value: 0.21663806278705633 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 393, 'oob_score': False, 'max_samples': 0.773357424692515, 'max_features': None, 'min_weight_fraction_leaf': 0.4837438075147879}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17449266503317365
Fold 2 IBS: 0.19742695190345053
Fold 3 IBS: 0.16471477798087575
Fold 4 IBS: 0.16267147593706363
Fold 5 IBS: 0.22648735220891497
[I 2024-04-14 00:01:42,535] Trial 30 finished with value: 0.18515864461269568 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 377, 'oob_score': False, 'max_samples': 0.9986438777088522, 'max_features': None, 'min_weight_fraction_leaf': 0.42773069772809913}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18186563850382112
Fold 2 IBS: 0.18838226339150496
Fold 3 IBS: 0.1747206639662102
Fold 4 IBS: 0.17560736221213202
Fold 5 IBS: 0.23404857262959045
[I 2024-04-14 00:02:08,029] Trial 31 finished with value: 0.19092490014065175 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 454, 'oob_score': False, 'max_samples': 0.939658841329532, 'max_features': None, 'min_weight_fraction_leaf': 0.4524256463348925}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.21398563901141657
Fold 2 IBS: 0.22134596740550985
Fold 3 IBS: 0.2048025990579434
Fold 4 IBS: 0.22461415055237854
Fold 5 IBS: 0.21851803782809134
[I 2024-04-14 00:02:29,848] Trial 32 finished with value: 0.21665327877106794 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.7396444271446992, 'max_features': None, 'min_weight_fraction_leaf': 0.4501495537267681}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19337121417130673
Fold 2 IBS: 0.19511882700454072
Fold 3 IBS: 0.18642967451701625
Fold 4 IBS: 0.1895345717679471
Fold 5 IBS: 0.21856358775020004
[I 2024-04-14 00:02:55,209] Trial 33 finished with value: 0.19660357504220216 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.9933327757837453, 'max_features': None, 'min_weight_fraction_leaf': 0.49338351231891625}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21397810999123087
Fold 2 IBS: 0.22130875696604183
Fold 3 IBS: 0.2047621585928816
Fold 4 IBS: 0.2246288907097577
Fold 5 IBS: 0.21863208708031015
[I 2024-04-14 00:03:15,946] Trial 34 finished with value: 0.21666200066804442 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.8938554646810188, 'max_features': None, 'min_weight_fraction_leaf': 0.45754449369723726}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21397501954215553
Fold 2 IBS: 0.22130442891193944
Fold 3 IBS: 0.20482836466241144
Fold 4 IBS: 0.22464430529398755
Fold 5 IBS: 0.22545436387504872
[I 2024-04-14 00:03:38,800] Trial 35 finished with value: 0.2180412964571085 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.8179898225635556, 'max_features': None, 'min_weight_fraction_leaf': 0.406528295392146}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18423128002886327
Fold 2 IBS: 0.20075733721613034
Fold 3 IBS: 0.17640819175973563
Fold 4 IBS: 0.18326652441136565
Fold 5 IBS: 0.21536169700367772
[I 2024-04-14 00:03:58,090] Trial 36 finished with value: 0.1920050060839545 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.9504880220263004, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3678752707538403}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398603848843456
Fold 2 IBS: 0.2212516593844012
Fold 3 IBS: 0.20480476599516775
Fold 4 IBS: 0.22467106118379263
Fold 5 IBS: 0.2186056754258949
[I 2024-04-14 00:04:14,154] Trial 37 finished with value: 0.2166638400955382 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 402, 'oob_score': False, 'max_samples': 0.6134779412492984, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42910258289196446}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1736188003490057
Fold 2 IBS: 0.19364285777259932
Fold 3 IBS: 0.1647798135113072
Fold 4 IBS: 0.1633666298088931
Fold 5 IBS: 0.22711044098051275
[I 2024-04-14 00:04:29,193] Trial 38 finished with value: 0.18450370848446362 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.7324083825350811, 'max_features': None, 'min_weight_fraction_leaf': 0.3267902150060746}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17613246987510892
Fold 2 IBS: 0.25370396104689813
Fold 3 IBS: 0.16470531172106329
Fold 4 IBS: 0.15671091985566343
Fold 5 IBS: 0.23754782764703308
[I 2024-04-14 00:04:49,075] Trial 39 finished with value: 0.19776009802915337 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.8998447540408812, 'max_features': None, 'min_weight_fraction_leaf': 0.26335636534084506}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139718451769373
Fold 2 IBS: 0.22132290174406308
Fold 3 IBS: 0.2049379534123754
Fold 4 IBS: 0.2246651821236489
Fold 5 IBS: 0.21845691499847839
[I 2024-04-14 00:05:03,622] Trial 40 finished with value: 0.21667095949110057 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.5051356852082238, 'max_features': None, 'min_weight_fraction_leaf': 0.46950692236254693}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1736115784806322
Fold 2 IBS: 0.19708658583278066
Fold 3 IBS: 0.1647004041861114
Fold 4 IBS: 0.16193266728653144
Fold 5 IBS: 0.2269439330088383
[I 2024-04-14 00:05:16,895] Trial 41 finished with value: 0.1848550337589788 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 313, 'oob_score': False, 'max_samples': 0.8766530642885175, 'max_features': None, 'min_weight_fraction_leaf': 0.37480517219328874}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17445559716534967
Fold 2 IBS: 0.20736534205005006
Fold 3 IBS: 0.16501326377011497
Fold 4 IBS: 0.16209455350644228
Fold 5 IBS: 0.22737252886994871
[I 2024-04-14 00:05:36,048] Trial 42 finished with value: 0.18726025707238114 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 430, 'oob_score': False, 'max_samples': 0.9712277852430382, 'max_features': None, 'min_weight_fraction_leaf': 0.4047116771034673}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19485182356242944
Fold 2 IBS: 0.1960274570730997
Fold 3 IBS: 0.18423026068342546
Fold 4 IBS: 0.18829121228006515
Fold 5 IBS: 0.23411274191187137
[I 2024-04-14 00:05:54,564] Trial 43 finished with value: 0.19950269910217824 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.8817254098792388, 'max_features': None, 'min_weight_fraction_leaf': 0.43343991639669144}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1712641582188513
Fold 2 IBS: 0.18994637490008684
Fold 3 IBS: 0.16479726253163554
Fold 4 IBS: 0.1632404230753816
Fold 5 IBS: 0.22572502599434202
[I 2024-04-14 00:06:13,853] Trial 44 finished with value: 0.18299464894405942 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.9374671457275974, 'max_features': None, 'min_weight_fraction_leaf': 0.41455323262354377}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19234550794011246
Fold 2 IBS: 0.200986097128332
Fold 3 IBS: 0.1855643390306468
Fold 4 IBS: 0.1932590693758762
Fold 5 IBS: 0.21341012086817227
[I 2024-04-14 00:06:34,090] Trial 45 finished with value: 0.19711302686862794 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.9378530595799813, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.42089417671131313}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398691344914347
Fold 2 IBS: 0.22137599652455153
Fold 3 IBS: 0.20479386291855103
Fold 4 IBS: 0.2246023464574881
Fold 5 IBS: 0.21853103069298896
[I 2024-04-14 00:06:54,799] Trial 46 finished with value: 0.2166580300085446 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 470, 'oob_score': False, 'max_samples': 0.7938991773051969, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4697812825251582}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1747444583541159
Fold 2 IBS: 0.23713516882516442
Fold 3 IBS: 0.16640805876585935
Fold 4 IBS: 0.1610873512530414
Fold 5 IBS: 0.234167489152576
[I 2024-04-14 00:07:17,205] Trial 47 finished with value: 0.1947085052701514 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.9498935746233631, 'max_features': None, 'min_weight_fraction_leaf': 0.33913737671094774}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.21398162469590376
Fold 2 IBS: 0.22136781149843104
Fold 3 IBS: 0.20480753036595514
Fold 4 IBS: 0.22461586717115936
Fold 5 IBS: 0.21858421480458282
[I 2024-04-14 00:07:33,919] Trial 48 finished with value: 0.21667140970720644 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 459, 'oob_score': False, 'max_samples': 0.8399357435042919, 'max_features': None, 'min_weight_fraction_leaf': 0.43949783817145754}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18607291644289184
Fold 2 IBS: 0.1997166990883884
Fold 3 IBS: 0.17871196581310303
Fold 4 IBS: 0.1866755623669813
Fold 5 IBS: 0.21401906861191788
[I 2024-04-14 00:07:52,573] Trial 49 finished with value: 0.19303924246465648 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 6, 'n_estimators': 480, 'oob_score': False, 'max_samples': 0.9976678104279734, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4100286247036702}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398689006749297
Fold 2 IBS: 0.22138730674766524
Fold 3 IBS: 0.20483789730275198
Fold 4 IBS: 0.22469041440834978
Fold 5 IBS: 0.21866425238172585
[I 2024-04-14 00:08:05,662] Trial 50 finished with value: 0.21671335218159715 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.7082075481455445, 'max_features': None, 'min_weight_fraction_leaf': 0.35750036696317244}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17354922029359332
Fold 2 IBS: 0.20364062415291528
Fold 3 IBS: 0.1656072740863152
Fold 4 IBS: 0.1629843663853799
Fold 5 IBS: 0.22805293589620068
[I 2024-04-14 00:08:15,778] Trial 51 finished with value: 0.18676688416288084 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.9128659910136828, 'max_features': None, 'min_weight_fraction_leaf': 0.3781612359397365}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1713164651684285
Fold 2 IBS: 0.1908535842776438
Fold 3 IBS: 0.16501795349457885
Fold 4 IBS: 0.16355225040434904
Fold 5 IBS: 0.22558632701889753
[I 2024-04-14 00:08:33,362] Trial 52 finished with value: 0.18326531607277957 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 434, 'oob_score': False, 'max_samples': 0.8747189140359779, 'max_features': None, 'min_weight_fraction_leaf': 0.39127818009875937}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1944075620870496
Fold 2 IBS: 0.19446392844340746
Fold 3 IBS: 0.18592909130830435
Fold 4 IBS: 0.18840569735760734
Fold 5 IBS: 0.23475202007425236
[I 2024-04-14 00:08:53,386] Trial 53 finished with value: 0.19959165985412422 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 435, 'oob_score': False, 'max_samples': 0.9590363563278936, 'max_features': None, 'min_weight_fraction_leaf': 0.47102290336229075}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398291231618569
Fold 2 IBS: 0.22130196765397775
Fold 3 IBS: 0.20479880441504156
Fold 4 IBS: 0.22463025012599544
Fold 5 IBS: 0.21857716931098428
[I 2024-04-14 00:09:09,334] Trial 54 finished with value: 0.21665822076443692 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.8049999889328818, 'max_features': None, 'min_weight_fraction_leaf': 0.41366841406796956}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19752377093956933
Fold 2 IBS: 0.20161258811122215
Fold 3 IBS: 0.18853359622298724
Fold 4 IBS: 0.19729854245931258
Fold 5 IBS: 0.21444154842475172
[I 2024-04-14 00:09:24,093] Trial 55 finished with value: 0.1998820092315686 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 390, 'oob_score': False, 'max_samples': 0.8604557082726361, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.39803093257208977}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18353091887871
Fold 2 IBS: 0.20136616660184192
Fold 3 IBS: 0.17417121851089504
Fold 4 IBS: 0.1806079641160692
Fold 5 IBS: 0.21629928891489889
[I 2024-04-14 00:09:43,066] Trial 56 finished with value: 0.191195111404483 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.9140825717192246, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.33142873928622046}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.176153787215779
Fold 2 IBS: 0.255503897064317
Fold 3 IBS: 0.16322193569881852
Fold 4 IBS: 0.15492145863817686
Fold 5 IBS: 0.23637436039500087
[I 2024-04-14 00:10:01,550] Trial 57 finished with value: 0.19723508780241844 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 17, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.846572289034959, 'max_features': None, 'min_weight_fraction_leaf': 0.1892509778618988}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21396974144117978
Fold 2 IBS: 0.22126810284573772
Fold 3 IBS: 0.20478519546942675
Fold 4 IBS: 0.22462583298910568
Fold 5 IBS: 0.2186668640880457
[I 2024-04-14 00:10:19,398] Trial 58 finished with value: 0.21666314736669912 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 407, 'oob_score': True, 'max_samples': 0.9616810596485048, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4994697733211825}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17564136184525772
Fold 2 IBS: 0.25480558879113324
Fold 3 IBS: 0.1643534207862224
Fold 4 IBS: 0.1574357976027508
Fold 5 IBS: 0.24128856654900457
[I 2024-04-14 00:10:22,957] Trial 59 finished with value: 0.19870494711487374 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.9304423548229083, 'max_features': None, 'min_weight_fraction_leaf': 0.30249606930327194}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21397063753981885
Fold 2 IBS: 0.22120321030131956
Fold 3 IBS: 0.20498353734020044
Fold 4 IBS: 0.22465541176579787
Fold 5 IBS: 0.21817456614748645
[I 2024-04-14 00:10:41,292] Trial 60 finished with value: 0.21659747261892465 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 459, 'oob_score': False, 'max_samples': 0.2967533381027988, 'max_features': None, 'min_weight_fraction_leaf': 0.45702707568744816}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1723055398262932
Fold 2 IBS: 0.19143168367074548
Fold 4 IBS: 0.16377185203308486
Fold 5 IBS: 0.22590801582391506
[I 2024-04-14 00:12:52,450] Trial 61 finished with value: 0.18367366623128167 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 331, 'oob_score': False, 'max_samples': 0.8753600395959259, 'max_features': None, 'min_weight_fraction_leaf': 0.3908186672612388}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1734277654013816
Fold 2 IBS: 0.20401881796514246
Fold 3 IBS: 0.16490921556493102
Fold 4 IBS: 0.1622125526423405
Fold 5 IBS: 0.2282204138485982
[I 2024-04-14 00:13:40,397] Trial 62 finished with value: 0.18655775308447872 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.8863444595022553, 'max_features': None, 'min_weight_fraction_leaf': 0.3630397965166024}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17425299200408814
Fold 2 IBS: 0.19784814184405533
Fold 3 IBS: 0.16448226706235544
Fold 4 IBS: 0.16221744449574835
Fold 5 IBS: 0.22561034364497506
[I 2024-04-14 00:30:51,416] Trial 63 finished with value: 0.18488223781024446 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 419, 'oob_score': False, 'max_samples': 0.9774803581744468, 'max_features': None, 'min_weight_fraction_leaf': 0.422237244496606}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.17214163753608527
Fold 2 IBS: 0.19020363580055616
Fold 3 IBS: 0.16550959046326688
Fold 4 IBS: 0.16526794959392554
Fold 5 IBS: 0.22833087784482511
[I 2024-04-14 00:31:00,844] Trial 64 finished with value: 0.1842907382477318 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 359, 'oob_score': False, 'max_samples': 0.8662053800926933, 'max_features': None, 'min_weight_fraction_leaf': 0.39542258978805284}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139792007492792
Fold 2 IBS: 0.22131668306329724
Fold 3 IBS: 0.20481655835559517
Fold 4 IBS: 0.22465389902940344
Fold 5 IBS: 0.2186107338002615
[I 2024-04-14 00:31:19,191] Trial 65 finished with value: 0.21667541499956733 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 370, 'oob_score': False, 'max_samples': 0.8126605473414451, 'max_features': None, 'min_weight_fraction_leaf': 0.4432122195886301}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139839404571568
Fold 2 IBS: 0.22128662025715748
Fold 3 IBS: 0.20475660906152154
Fold 4 IBS: 0.22463254345676723
Fold 5 IBS: 0.2185879578955235
[I 2024-04-14 00:31:49,227] Trial 66 finished with value: 0.2166495342256253 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.7628822009195562, 'max_features': None, 'min_weight_fraction_leaf': 0.4806954217012357}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17446682144724857
Fold 2 IBS: 0.20343226965949585
Fold 3 IBS: 0.16509877229395598
Fold 4 IBS: 0.16272402121276544
Fold 5 IBS: 0.22837609800630052
[I 2024-04-14 00:32:07,153] Trial 67 finished with value: 0.18681959652395327 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.9273407143986389, 'max_features': None, 'min_weight_fraction_leaf': 0.3829484376044615}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139737017543663
Fold 2 IBS: 0.22132584453552323
Fold 3 IBS: 0.20489534413800095
Fold 4 IBS: 0.22458301458145777
Fold 5 IBS: 0.21855108631457426
[I 2024-04-14 00:32:27,649] Trial 68 finished with value: 0.21666579826478452 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 442, 'oob_score': False, 'max_samples': 0.4560255505580615, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.43542376867133237}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18183019653099627
Fold 2 IBS: 0.20776625174627097
Fold 3 IBS: 0.16953634624872876
Fold 4 IBS: 0.170118714579068
Fold 5 IBS: 0.21958622926343907
[I 2024-04-14 00:32:49,449] Trial 69 finished with value: 0.18976754767370063 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 389, 'oob_score': True, 'max_samples': 0.970602689136413, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.263156524754376}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398228747656492
Fold 2 IBS: 0.22137876391118777
Fold 3 IBS: 0.20476882960361822
Fold 4 IBS: 0.22463276305816607
Fold 5 IBS: 0.21856497560430035
[I 2024-04-14 00:33:09,959] Trial 70 finished with value: 0.21666552393076746 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 465, 'oob_score': False, 'max_samples': 0.9012147144740991, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.46397187987790006}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17367631623248717
Fold 2 IBS: 0.18729177749490242
Fold 3 IBS: 0.16716923559227603
Fold 4 IBS: 0.16896965253402357
Fold 5 IBS: 0.22871507732594165
[I 2024-04-14 00:33:23,006] Trial 71 finished with value: 0.1851644118359262 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.8369240734764914, 'max_features': None, 'min_weight_fraction_leaf': 0.3894108977238639}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17623676574788
Fold 2 IBS: 0.18722146882244894
Fold 3 IBS: 0.16923825257873615
Fold 4 IBS: 0.17041309974033034
Fold 5 IBS: 0.2308208580988099
[I 2024-04-14 00:33:37,797] Trial 72 finished with value: 0.1867860889976411 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.8867920327737324, 'max_features': None, 'min_weight_fraction_leaf': 0.4157314879593541}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17466534845952894
Fold 2 IBS: 0.21319655330881065
Fold 3 IBS: 0.165618296143337
Fold 4 IBS: 0.1624164693292741
Fold 5 IBS: 0.22901894445979137
[I 2024-04-14 00:33:49,629] Trial 73 finished with value: 0.1889831223401484 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.9448081876116871, 'max_features': None, 'min_weight_fraction_leaf': 0.37829799509574824}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19283001171526404
Fold 2 IBS: 0.25233074235756864
Fold 3 IBS: 0.16531718816798083
Fold 4 IBS: 0.1371287117522084
Fold 5 IBS: 0.23777310085766115
[I 2024-04-14 00:34:04,541] Trial 74 finished with value: 0.1970759509701366 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 322, 'oob_score': False, 'max_samples': 0.8560145872964813, 'max_features': None, 'min_weight_fraction_leaf': 0.028106730951250714}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1765526886203159
Fold 2 IBS: 0.24189641128474174
Fold 3 IBS: 0.16693060419975347
Fold 4 IBS: 0.16161303135180896
Fold 5 IBS: 0.2376375116037371
[I 2024-04-14 00:34:15,239] Trial 75 finished with value: 0.19692604941207142 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 227, 'oob_score': False, 'max_samples': 0.9957860072135883, 'max_features': None, 'min_weight_fraction_leaf': 0.34756145962819307}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1751244271301782
Fold 2 IBS: 0.24107670158411845
Fold 3 IBS: 0.16626442192082944
Fold 4 IBS: 0.16107692991176065
Fold 5 IBS: 0.23441060343413975
[I 2024-04-14 00:34:26,615] Trial 76 finished with value: 0.1955906167962053 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 273, 'oob_score': False, 'max_samples': 0.9214268543378774, 'max_features': None, 'min_weight_fraction_leaf': 0.32041444551979115}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398382567775925
Fold 2 IBS: 0.22132197857579206
Fold 3 IBS: 0.20483550783639218
Fold 4 IBS: 0.22469410346846014
Fold 5 IBS: 0.2185234061706301
[I 2024-04-14 00:34:43,197] Trial 77 finished with value: 0.21667176434580676 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 419, 'oob_score': False, 'max_samples': 0.5629198845457468, 'max_features': None, 'min_weight_fraction_leaf': 0.4816802580265169}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139815287454151
Fold 2 IBS: 0.22144251355248706
Fold 3 IBS: 0.20476517865000235
Fold 4 IBS: 0.22461967295013774
Fold 5 IBS: 0.21859926137399327
[I 2024-04-14 00:35:01,102] Trial 78 finished with value: 0.21668163105440713 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 481, 'oob_score': False, 'max_samples': 0.8709125293011857, 'max_features': None, 'min_weight_fraction_leaf': 0.4500024716514146}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21393847873679495
Fold 2 IBS: 0.2206352907056855
Fold 3 IBS: 0.2052031401141122
Fold 4 IBS: 0.22465935825676747
Fold 5 IBS: 0.2170322205916447
[I 2024-04-14 00:35:16,220] Trial 79 finished with value: 0.21629369768100096 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.12074719353470553, 'max_features': None, 'min_weight_fraction_leaf': 0.40382275005132695}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.21398666839515476
Fold 2 IBS: 0.22133561292920703
Fold 3 IBS: 0.20476084552868884
Fold 4 IBS: 0.22460858228328426
Fold 5 IBS: 0.21850495327987215
[I 2024-04-14 00:35:38,837] Trial 80 finished with value: 0.2166393324832414 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 442, 'oob_score': True, 'max_samples': 0.7543724309332009, 'max_features': None, 'min_weight_fraction_leaf': 0.43164085935118673}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1718240887458899
Fold 2 IBS: 0.191437443203446
Fold 3 IBS: 0.16491345446124533
Fold 4 IBS: 0.16398408770898562
Fold 5 IBS: 0.22656733476064983
[I 2024-04-14 00:35:54,403] Trial 81 finished with value: 0.18374528177604332 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 355, 'oob_score': False, 'max_samples': 0.8723363913158229, 'max_features': None, 'min_weight_fraction_leaf': 0.39397540986506063}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17374604878476174
Fold 2 IBS: 0.19798109455852192
Fold 3 IBS: 0.16401735622550842
Fold 4 IBS: 0.1619573282383729
Fold 5 IBS: 0.22581911344299607
[I 2024-04-14 00:36:09,469] Trial 82 finished with value: 0.1847041882500322 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.8247493235113283, 'max_features': None, 'min_weight_fraction_leaf': 0.3601096556690917}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17340750457612014
Fold 2 IBS: 0.1865209431926325
Fold 3 IBS: 0.16660200760670268
Fold 4 IBS: 0.16731704053628665
Fold 5 IBS: 0.23067593415026993
[I 2024-04-14 00:36:24,001] Trial 83 finished with value: 0.1849046860124024 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.8997196592880778, 'max_features': None, 'min_weight_fraction_leaf': 0.42074986147139254}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17452011364531658
Fold 2 IBS: 0.21400766260887688
Fold 3 IBS: 0.16568783150449218
Fold 4 IBS: 0.16229140988658286
Fold 5 IBS: 0.22955502465730293
[I 2024-04-14 00:36:40,427] Trial 84 finished with value: 0.1892124084605143 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.9496964476824827, 'max_features': None, 'min_weight_fraction_leaf': 0.37072364798951474}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17525073412789557
Fold 2 IBS: 0.2105659370926584
Fold 3 IBS: 0.16602025501429193
Fold 4 IBS: 0.1622139028904671
Fold 5 IBS: 0.22956434629388905
[I 2024-04-14 00:36:51,875] Trial 85 finished with value: 0.18872303508384042 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.9768787275271766, 'max_features': None, 'min_weight_fraction_leaf': 0.389212711709705}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139824234419341
Fold 2 IBS: 0.22136539954988055
Fold 3 IBS: 0.204822165703736
Fold 4 IBS: 0.22464122963551408
Fold 5 IBS: 0.2185219969232711
[I 2024-04-14 00:37:05,674] Trial 86 finished with value: 0.21666664305086716 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 367, 'oob_score': False, 'max_samples': 0.7799819637825093, 'max_features': None, 'min_weight_fraction_leaf': 0.4000713988176814}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.20027780376461612
Fold 2 IBS: 0.20307340294666915
Fold 3 IBS: 0.19102009672018105
Fold 4 IBS: 0.20003685084746606
Fold 5 IBS: 0.21421965519619954
[I 2024-04-14 00:37:22,813] Trial 87 finished with value: 0.20172556189502638 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.9292189383035607, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4390757544239005}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398570828038652
Fold 2 IBS: 0.22140151761658128
Fold 3 IBS: 0.2048003761944947
Fold 4 IBS: 0.22459594623574206
Fold 5 IBS: 0.21853396569713832
[I 2024-04-14 00:37:42,888] Trial 88 finished with value: 0.2166635028048686 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 488, 'oob_score': False, 'max_samples': 0.7896863299148335, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.45607963249620537}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17203791887421
Fold 2 IBS: 0.18726791026590833
Fold 3 IBS: 0.16576625757294128
Fold 4 IBS: 0.16530852151519143
Fold 5 IBS: 0.22888342314880578
[I 2024-04-14 00:38:01,934] Trial 89 finished with value: 0.18385280627541137 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.8904926128857917, 'max_features': None, 'min_weight_fraction_leaf': 0.4120116856268681}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1940772853656249
Fold 2 IBS: 0.2004241668146479
Fold 3 IBS: 0.18634724520921406
Fold 4 IBS: 0.19496657142921314
Fold 5 IBS: 0.21367459762057212
[I 2024-04-14 00:38:20,821] Trial 90 finished with value: 0.19789797328785444 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.9106880455831121, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.40976298541889333}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1926191075437479
Fold 2 IBS: 0.19415079186842468
Fold 3 IBS: 0.18487947833584825
Fold 4 IBS: 0.18641681431445226
Fold 5 IBS: 0.23439208959229954
[I 2024-04-14 00:38:38,236] Trial 91 finished with value: 0.1984916563309545 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 436, 'oob_score': False, 'max_samples': 0.8647633953620859, 'max_features': None, 'min_weight_fraction_leaf': 0.42597944887100797}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17236214134250716
Fold 2 IBS: 0.19455412228125918
Fold 3 IBS: 0.16427712812224537
Fold 4 IBS: 0.162949090773761
Fold 5 IBS: 0.2259494780328012
[I 2024-04-14 00:38:56,889] Trial 92 finished with value: 0.18401839211051477 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.8900467044086138, 'max_features': None, 'min_weight_fraction_leaf': 0.3893348459268057}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17257330060839252
Fold 2 IBS: 0.18644424300898413
Fold 3 IBS: 0.167229764854462
Fold 4 IBS: 0.16728718203115409
Fold 5 IBS: 0.22779364161313018
[I 2024-04-14 00:39:18,509] Trial 93 finished with value: 0.18426562642322458 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 454, 'oob_score': False, 'max_samples': 0.951027581141039, 'max_features': None, 'min_weight_fraction_leaf': 0.44280477596355444}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17363154839056466
Fold 2 IBS: 0.22743622651322085
Fold 3 IBS: 0.1659053390876856
Fold 4 IBS: 0.1617200646570578
Fold 5 IBS: 0.2317058059728232
[I 2024-04-14 00:39:37,891] Trial 94 finished with value: 0.1920797969242704 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.8997870199007337, 'max_features': None, 'min_weight_fraction_leaf': 0.3407068895244753}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1742039929754336
Fold 2 IBS: 0.22427050607023472
Fold 3 IBS: 0.1662296675861061
Fold 4 IBS: 0.16181525206129235
Fold 5 IBS: 0.2312628649338052
[I 2024-04-14 00:39:54,570] Trial 95 finished with value: 0.1915564567253744 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.9777582543649842, 'max_features': None, 'min_weight_fraction_leaf': 0.37055856104990403}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.18206223269633873
Fold 2 IBS: 0.18820585180072097
Fold 3 IBS: 0.17369714014143833
Fold 4 IBS: 0.1751220212365198
Fold 5 IBS: 0.22437209861320465
[I 2024-04-14 00:40:12,030] Trial 96 finished with value: 0.1886918688976445 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.8430407084230132, 'max_features': None, 'min_weight_fraction_leaf': 0.41419337591128474}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17261810934600746
Fold 2 IBS: 0.19291443628076307
Fold 3 IBS: 0.16469348295311864
Fold 4 IBS: 0.16293280131529528
Fold 5 IBS: 0.2265701418039605
[I 2024-04-14 00:40:30,651] Trial 97 finished with value: 0.183945794339829 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 499, 'oob_score': False, 'max_samples': 0.8784577990568653, 'max_features': None, 'min_weight_fraction_leaf': 0.3938564682169779}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1806635839384418
Fold 2 IBS: 0.18847632703053457
Fold 3 IBS: 0.17326431415814442
Fold 4 IBS: 0.17486447351236495
Fold 5 IBS: 0.2258002518864047
[I 2024-04-14 00:40:52,285] Trial 98 finished with value: 0.18861379010517812 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.8075349562887142, 'max_features': None, 'min_weight_fraction_leaf': 0.3942015894342152}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17457318039218142
Fold 2 IBS: 0.19576662913389825
Fold 3 IBS: 0.1643932476316186
Fold 4 IBS: 0.16120104626761333
Fold 5 IBS: 0.22682167562644817
[I 2024-04-14 00:41:02,726] Trial 99 finished with value: 0.18455115581035195 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 185, 'oob_score': True, 'max_samples': 0.8213734885898443, 'max_features': None, 'min_weight_fraction_leaf': 0.35155796421429664}. Best is trial 23 with value: 0.1829201586199189.


* Best trial for IBS:
 FrozenTrial(number=23, state=TrialState.COMPLETE, values=[0.1829201586199189], datetime_start=datetime.datetime(2024, 4, 13, 23, 57, 59, 662816), datetime_complete=datetime.datetime(2024, 4, 13, 23, 58, 25, 284566), params={'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.9248759152889626, 'max_features': None, 'min_weight_fraction_leaf': 0.41894325026727597}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=23, value=None)


* Best Score for IBS:
 0.1829201586199189

In [100]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [101]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.826
train_ibs:  0.183

#### Test

In [102]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

In [103]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=19, max_features='log2', max_leaf_nodes=15,
                     max_samples=0.9995515317027949, min_samples_split=18,
                     min_weight_fraction_leaf=0.032175807966512454,
                     n_estimators=115, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.653

RandomSurvivalForest(max_depth=20, max_features=None, max_leaf_nodes=13,
                     max_samples=0.9248759152889626, min_samples_split=2,
                     min_weight_fraction_leaf=0.41894325026727597,
                     n_estimators=396, random_state=123)

test_ibs:  0.206

In [104]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [105]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [106]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 00:41:07,401] A new study created in memory with name: no-name-fe9cf7fd-4e66-498c-866c-28295458ccbd

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 00:41:10,055] Trial 0 finished with value: 0.7836129950691764 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:41:18,196] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:41:33,929] Trial 2 finished with value: 0.7556152507681301 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:41:35,257] Trial 3 finished with value: 0.7717160075913865 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:41:40,886] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:41:47,855] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:41:51,340] Trial 6 finished with value: 0.7781769130770997 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:41:59,918] Trial 7 finished with value: 0.7508462032035622 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 00:42:00,655] Trial 8 finished with value: 0.7684324398125025 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:42:21,997] Trial 9 finished with value: 0.7552175391299489 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:42:27,919] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:42:31,301] Trial 11 finished with value: 0.7698273464882801 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 00:42:35,860] Trial 12 finished with value: 0.7914452579440178 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 00:42:40,398] Trial 13 finished with value: 0.7653468723507815 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:42:44,192] Trial 14 finished with value: 0.7661538756898894 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.78125

Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:42:46,852] Trial 15 finished with value: 0.7684393821468035 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8013392857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6267605633802817
[I 2024-04-14 00:42:50,990] Trial 16 finished with value: 0.77051229268592 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:42:53,610] Trial 17 finished with value: 0.7723249788334919 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:42:58,030] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:43:01,494] Trial 19 finished with value: 0.765551411653658 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:43:02,238] Trial 20 finished with value: 0.7391209661793047 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 00:43:05,677] Trial 21 finished with value: 0.7817887210557736 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 00:43:09,726] Trial 22 finished with value: 0.7809862642199459 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:43:12,860] Trial 23 finished with value: 0.7759304206293289 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 357, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4155863532247274, 'min_weight_fraction_leaf': 0.07928484585286968}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 00:43:17,083] Trial 24 finished with value: 0.7747196235015181 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 459, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7479661339947506, 'min_weight_fraction_leaf': 0.00901469432212705}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 00:43:21,351] Trial 25 finished with value: 0.780898135887688 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.895337843232826, 'min_weight_fraction_leaf': 0.09625756753241399}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:43:33,880] Trial 26 finished with value: 0.7535362780827659 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 291, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5901308628926357, 'min_weight_fraction_leaf': 0.04311046725313979}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:43:36,071] Trial 27 finished with value: 0.7700615298551389 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 00:43:39,398] Trial 28 finished with value: 0.7607683592529704 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 19, 'max_depth': 14, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7294475749114913, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 00:43:47,067] Trial 29 finished with value: 0.783702202780981 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 453, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8499447592488185, 'min_weight_fraction_leaf': 0.11187426524781394}. Best is trial 12 with value: 0.7914452579440178.

Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:43:54,776] Trial 30 finished with value: 0.7671596620665804 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 459, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.23846812660748434}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:44:03,979] Trial 31 finished with value: 0.7712482704957379 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 500, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9319495980432307, 'min_weight_fraction_leaf': 0.028814153765248245}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:44:11,928] Trial 32 finished with value: 0.7875856659621985 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 459, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.83936093173654, 'min_weight_fraction_leaf': 0.10465149498791723}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 00:44:20,151] Trial 33 finished with value: 0.7854274383297459 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 478, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8110657459614115, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 00:44:29,083] Trial 34 finished with value: 0.7875712972185422 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8312111470897382, 'min_weight_fraction_leaf': 0.11396804804122496}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:44:37,512] Trial 35 finished with value: 0.7805626784012362 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 474, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8317242802235407, 'min_weight_fraction_leaf': 0.17026413245531302}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:44:53,421] Trial 36 finished with value: 0.7392301426964731 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 397, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.919159658755392, 'min_weight_fraction_leaf': 0.12417590138595275}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 00:45:01,525] Trial 37 finished with value: 0.7733460193912409 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 478, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9384999627665201, 'min_weight_fraction_leaf': 0.21309962076960762}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 00:45:07,727] Trial 38 finished with value: 0.7639313460923033 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 345, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7810779808078776, 'min_weight_fraction_leaf': 0.2883645958901683}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:45:25,399] Trial 39 finished with value: 0.7557517610684528 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 438, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7126142286152415, 'min_weight_fraction_leaf': 0.051535007757158066}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:45:33,105] Trial 40 finished with value: 0.7815020978326014 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 469, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6423525258918861, 'min_weight_fraction_leaf': 0.12542889840419838}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 00:45:40,381] Trial 41 finished with value: 0.7864193339372411 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 449, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8300934016687722, 'min_weight_fraction_leaf': 0.10960380301974583}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:45:47,773] Trial 42 finished with value: 0.7880709509204418 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 420, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8078708827436648, 'min_weight_fraction_leaf': 0.0742644879267989}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 00:45:54,982] Trial 43 finished with value: 0.7828465399677109 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 413, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7812921734334815, 'min_weight_fraction_leaf': 0.07650726650715535}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 00:46:02,399] Trial 44 finished with value: 0.7803513206203079 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 19, 'n_estimators': 440, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9997498444523031, 'min_weight_fraction_leaf': 0.1566845549254962}. Best is trial 12 with value: 0.7914452579440178.

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 00:46:10,998] Trial 45 finished with value: 0.7788761410494602 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 498, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9223521852303842, 'min_weight_fraction_leaf': 0.059273843380186375}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:46:18,942] Trial 46 finished with value: 0.7685371916964001 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 454, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9500103809873137, 'min_weight_fraction_leaf': 0.03660618092052255}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 00:46:35,879] Trial 47 finished with value: 0.742317931200098 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 388, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8574312076294325, 'min_weight_fraction_leaf': 0.08931620844737977}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:46:43,149] Trial 48 finished with value: 0.7716977304949759 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 422, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.755266816507861, 'min_weight_fraction_leaf': 0.020812961475463188}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:46:46,094] Trial 49 finished with value: 0.7845202124432327 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 134, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.814593864444954, 'min_weight_fraction_leaf': 0.09888902748696558}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:46:52,959] Trial 50 finished with value: 0.7773994153326739 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 18, 'n_estimators': 367, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6864757488123517, 'min_weight_fraction_leaf': 0.0622709472266257}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 00:47:01,111] Trial 51 finished with value: 0.7857905817313229 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 477, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8138857282473038, 'min_weight_fraction_leaf': 0.139261908142962}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:47:09,804] Trial 52 finished with value: 0.7754721899619019 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 483, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.897591154770797, 'min_weight_fraction_leaf': 0.18036745341019644}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:47:18,239] Trial 53 finished with value: 0.7716977304949759 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 445, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8040300125345899, 'min_weight_fraction_leaf': 0.13782166853114988}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:47:26,525] Trial 54 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 469, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8778737344226841, 'min_weight_fraction_leaf': 0.4522260564219586}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:47:30,674] Trial 55 finished with value: 0.7758270084642879 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 223, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7446102701098806, 'min_weight_fraction_leaf': 0.0765135926752003}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 00:47:37,836] Trial 56 finished with value: 0.7744763834479156 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 431, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.957871319428308, 'min_weight_fraction_leaf': 0.15347039261632256}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:47:46,043] Trial 57 finished with value: 0.7699442097541136 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 490, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6651987019932437, 'min_weight_fraction_leaf': 0.1066939379481781}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 00:48:01,953] Trial 58 finished with value: 0.7510997177927557 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 415, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8492110159158694, 'min_weight_fraction_leaf': 0.1370897749041413}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:48:07,974] Trial 59 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 291, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.3278490557085546, 'min_weight_fraction_leaf': 0.20658865997161166}. Best is trial 12 with value: 0.7914452579440178.

Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6502347417840375
[I 2024-04-14 00:48:16,113] Trial 60 finished with value: 0.7646046839942156 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 464, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6191277619189391, 'min_weight_fraction_leaf': 0.2714828861387636}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:48:25,032] Trial 61 finished with value: 0.7875908032299939 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 482, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8197782912980647, 'min_weight_fraction_leaf': 0.11182880406892551}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:48:32,579] Trial 62 finished with value: 0.7867469213734538 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 447, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7728729369504425, 'min_weight_fraction_leaf': 0.08684392452952273}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 00:48:39,730] Trial 63 finished with value: 0.7798808652133927 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 446, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7730739126088626, 'min_weight_fraction_leaf': 0.08638346674570552}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:48:46,483] Trial 64 finished with value: 0.7930563544969358 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 397, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7094023899138029, 'min_weight_fraction_leaf': 0.016985502713105286}. Best is trial 64 with value: 0.7930563544969358.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 00:48:53,358] Trial 65 finished with value: 0.7782230230703928 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 399, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5432894752024745, 'min_weight_fraction_leaf': 0.021766672705799798}. Best is trial 64 with value: 0.7930563544969358.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:48:56,796] Trial 66 finished with value: 0.7938811826372392 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7228780771138192, 'min_weight_fraction_leaf': 0.0031520648190986253}. Best is trial 66 with value: 0.7938811826372392.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:48:59,759] Trial 67 finished with value: 0.7920349896145755 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7208856143139186, 'min_weight_fraction_leaf': 0.000720456341576893}. Best is trial 66 with value: 0.7938811826372392.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:49:02,631] Trial 68 finished with value: 0.794041883921594 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7036950154527627, 'min_weight_fraction_leaf': 0.005216408266220198}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 00:49:05,429] Trial 69 finished with value: 0.7859079077910682 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 323, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7175215556344815, 'min_weight_fraction_leaf': 0.011727820970865974}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 00:49:16,001] Trial 70 finished with value: 0.751088073319086 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 347, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7068868150575319, 'min_weight_fraction_leaf': 0.04275053996657477}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:49:19,471] Trial 71 finished with value: 0.7894658722092704 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 377, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6765833323968065, 'min_weight_fraction_leaf': 0.0056539519960706885}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:49:22,218] Trial 72 finished with value: 0.7914342067886004 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 303, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6657543859502482, 'min_weight_fraction_leaf': 0.0007645303007875817}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:49:25,143] Trial 73 finished with value: 0.7939687176512447 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 295, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6645384838575977, 'min_weight_fraction_leaf': 0.0006629495375479764}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:49:28,203] Trial 74 finished with value: 0.7929417632058738 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 292, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6089504598680775, 'min_weight_fraction_leaf': 0.009816745037317486}. Best is trial 68 with value: 0.794041883921594.

Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:49:30,901] Trial 75 finished with value: 0.7886490466297866 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.532426516857448, 'min_weight_fraction_leaf': 0.0002663514949337425}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:49:33,682] Trial 76 finished with value: 0.7801220886659336 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6123538402148698, 'min_weight_fraction_leaf': 0.019649932961991672}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:49:36,140] Trial 77 finished with value: 0.7814522179558544 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5811927471801297, 'min_weight_fraction_leaf': 0.04878077669029726}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 00:49:38,934] Trial 78 finished with value: 0.7845818837754068 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 306, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6462796252211019, 'min_weight_fraction_leaf': 0.03369012476405811}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 00:49:41,728] Trial 79 finished with value: 0.7787001559323222 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5164947678000329, 'min_weight_fraction_leaf': 0.01622265318172269}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:49:44,220] Trial 80 finished with value: 0.7818525173809616 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 243, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6235631347306672, 'min_weight_fraction_leaf': 0.031552173049052425}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:49:46,948] Trial 81 finished with value: 0.7905684059227995 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 341, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6646517878972749, 'min_weight_fraction_leaf': 0.003319138338666917}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 00:49:49,813] Trial 82 finished with value: 0.7915344293360062 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 352, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6559993331175135, 'min_weight_fraction_leaf': 0.0007051454739791334}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:49:52,852] Trial 83 finished with value: 0.784834519027793 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6078088154987048, 'min_weight_fraction_leaf': 0.05269795093090639}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:49:55,217] Trial 84 finished with value: 0.7876737917407194 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 252, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.56420075442896, 'min_weight_fraction_leaf': 0.0001867103765655385}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 00:49:57,688] Trial 85 finished with value: 0.7941830791944973 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7030590704740037, 'min_weight_fraction_leaf': 0.020016091327628317}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 00:50:00,170] Trial 86 finished with value: 0.7910103136701933 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7300691279502551, 'min_weight_fraction_leaf': 0.02642103208266877}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:50:02,359] Trial 87 finished with value: 0.7870370369739819 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6972914076775041, 'min_weight_fraction_leaf': 0.042431862202902404}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 00:50:10,793] Trial 88 finished with value: 0.7393760229419569 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 270, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.592229960198248, 'min_weight_fraction_leaf': 0.016246248347428313}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:50:13,723] Trial 89 finished with value: 0.7766334763698508 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.45159856922443276, 'min_weight_fraction_leaf': 0.05921570024221322}. Best is trial 85 with value: 0.7941830791944973.

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:50:16,624] Trial 90 finished with value: 0.7708838065283327 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 335, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7242276540625545, 'min_weight_fraction_leaf': 0.34283486638092503}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:50:19,710] Trial 91 finished with value: 0.7895419037726438 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6583630297112304, 'min_weight_fraction_leaf': 0.013827947129714684}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:50:22,895] Trial 92 finished with value: 0.7920954683515248 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 297, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7515631882154823, 'min_weight_fraction_leaf': 0.028988151290404485}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:50:26,473] Trial 93 finished with value: 0.7937492188401966 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 304, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7381814767748153, 'min_weight_fraction_leaf': 0.030278173261689908}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:50:29,404] Trial 94 finished with value: 0.7930758605083875 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 298, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6942749611849839, 'min_weight_fraction_leaf': 0.02829541014533638}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:50:31,771] Trial 95 finished with value: 0.7862754612128648 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 262, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.750467494063393, 'min_weight_fraction_leaf': 0.03084864174659612}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:50:34,553] Trial 96 finished with value: 0.7937809600898336 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6916627249534713, 'min_weight_fraction_leaf': 0.0642170412166308}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:50:37,180] Trial 97 finished with value: 0.7922100596425867 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6847338071332475, 'min_weight_fraction_leaf': 0.06422450776206082}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:50:39,689] Trial 98 finished with value: 0.7896281650393346 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 275, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6945703344834594, 'min_weight_fraction_leaf': 0.06929480157264988}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8607594936708861

[I 2024-04-14 00:50:41,808] A new study created in memory with name: no-name-08e762da-21b2-4004-b38c-0320c336d6fc

Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 00:50:41,788] Trial 99 finished with value: 0.7912614087353609 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 194, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6926648599741109, 'min_weight_fraction_leaf': 0.05098663692788332}. Best is trial 85 with value: 0.7941830791944973.


* Best trial for C-index:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.7941830791944973], datetime_start=datetime.datetime(2024, 4, 14, 0, 49, 55, 223201), datetime_complete=datetime.datetime(2024, 4, 14, 0, 49, 57, 686852), params={'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7030590704740037, 'min_weight_fraction_leaf': 0.020016091327628317}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=85, value=None)


* Best Score for C-index:
 0.7941830791944973

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16943133784699038
Fold 2 IBS: 0.217110921492143
Fold 3 IBS: 0.16458005935948244
Fold 4 IBS: 0.15978141365273868
Fold 5 IBS: 0.23006411985790817
[I 2024-04-14 00:50:52,302] Trial 0 finished with value: 0.18819357044185253 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-14 00:51:08,185] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.1920088773895634
Fold 2 IBS: 0.20722305192399237
Fold 3 IBS: 0.1843664308419076
Fold 4 IBS: 0.19578634061172853
Fold 5 IBS: 0.21729770324619507
[I 2024-04-14 00:51:22,767] Trial 2 finished with value: 0.1993364808026774 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.19258828625505786
Fold 2 IBS: 0.2045422331943319
Fold 3 IBS: 0.1853898388957368
Fold 4 IBS: 0.19796057104495973
Fold 5 IBS: 0.21730311317672968
[I 2024-04-14 00:51:27,324] Trial 3 finished with value: 0.1995568085133632 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-14 00:51:38,727] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-14 00:51:44,732] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.17108054547230092
Fold 2 IBS: 0.21332710542268465
Fold 3 IBS: 0.1636503921602676
Fold 4 IBS: 0.1601897971404523
Fold 5 IBS: 0.23011170771684802
[I 2024-04-14 00:51:57,696] Trial 6 finished with value: 0.1876719095825107 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.1802257330412862
Fold 2 IBS: 0.20553844032632104
Fold 3 IBS: 0.17516423786860197
Fold 4 IBS: 0.18156654611164302
Fold 5 IBS: 0.21889734913100833
[I 2024-04-14 00:52:05,681] Trial 7 finished with value: 0.1922784612957721 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.19324605458737515
Fold 2 IBS: 0.20063316435414258
Fold 3 IBS: 0.18395193632306783
Fold 4 IBS: 0.19657870618224477
Fold 5 IBS: 0.2180785905917539
[I 2024-04-14 00:52:07,355] Trial 8 finished with value: 0.19849769040771686 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.19947118578728948
Fold 2 IBS: 0.2128915375997729
Fold 3 IBS: 0.19180552923211425
Fold 4 IBS: 0.21059003168383789
Fold 5 IBS: 0.2166615073888468
[I 2024-04-14 00:52:25,778] Trial 9 finished with value: 0.20628395833837226 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.21397612241164576
Fold 2 IBS: 0.2207394210478338
Fold 3 IBS: 0.20537940251283027
Fold 4 IBS: 0.22474853253260105
Fold 5 IBS: 0.2174222289467434
[I 2024-04-14 00:52:39,264] Trial 10 finished with value: 0.21645314149033087 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.2015386647704584
Fold 2 IBS: 0.21349515547127124
Fold 3 IBS: 0.19259186402255285
Fold 4 IBS: 0.21338933172129262
Fold 5 IBS: 0.21568498079724013
[I 2024-04-14 00:52:49,690] Trial 11 finished with value: 0.20733999935656305 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.16481288780890282
Fold 2 IBS: 0.2210169243096472
Fold 3 IBS: 0.1621024154551832
Fold 4 IBS: 0.1533029510139564
Fold 5 IBS: 0.23439416692917028
[I 2024-04-14 00:53:04,978] Trial 12 finished with value: 0.18712586910337198 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.17402283336818236
Fold 2 IBS: 0.2087374728480146
Fold 3 IBS: 0.17174698691539156
Fold 4 IBS: 0.17261429502370135
Fold 5 IBS: 0.22300398757472922
[I 2024-04-14 00:53:21,202] Trial 13 finished with value: 0.19002511514600381 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638831587887255, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.2139646814364898
Fold 2 IBS: 0.22074056096749928
Fold 3 IBS: 0.20501656315227804
Fold 4 IBS: 0.22494601314735585
Fold 5 IBS: 0.21705148409657263
[I 2024-04-14 00:53:34,295] Trial 14 finished with value: 0.21634386056003913 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 12 with value: 0.18712586910337198.

Fold 1 IBS: 0.21400643269593325
Fold 2 IBS: 0.22111219981278188
Fold 3 IBS: 0.20502803908063474
Fold 4 IBS: 0.22484462106669664
Fold 5 IBS: 0.21822466700224044
[I 2024-04-14 00:53:42,401] Trial 15 finished with value: 0.21664319193165743 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 268, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.33571048327918607, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.17764770478002706
Fold 2 IBS: 0.20867663392001196
Fold 3 IBS: 0.17428317770837892
Fold 4 IBS: 0.17942136638629663
Fold 5 IBS: 0.2202481090473258
[I 2024-04-14 00:53:56,867] Trial 16 finished with value: 0.19205539836840807 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6535355702555379, 'min_weight_fraction_leaf': 0.1906011147608997}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.1745416753225377
Fold 2 IBS: 0.21000021208635342
Fold 3 IBS: 0.16747801651861197
Fold 4 IBS: 0.1665050437548392
Fold 5 IBS: 0.2259884313484794
[I 2024-04-14 00:54:08,679] Trial 17 finished with value: 0.18890267580616435 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.903993543626621, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.18877375960277615
Fold 2 IBS: 0.2104175503296011
Fold 3 IBS: 0.17887147368827228
Fold 4 IBS: 0.20070265473963897
Fold 5 IBS: 0.21455512687410158
[I 2024-04-14 00:54:09,890] Trial 18 finished with value: 0.19866411304687803 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.38500398118655316, 'min_weight_fraction_leaf': 0.0735015574561402}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.1693931134036931
Fold 2 IBS: 0.21423273576779828
Fold 3 IBS: 0.16523484371479388
Fold 4 IBS: 0.16359614521845625
Fold 5 IBS: 0.23143820702196424
[I 2024-04-14 00:54:13,620] Trial 19 finished with value: 0.18877900902534114 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.639253673774636, 'min_weight_fraction_leaf': 0.037408326362835864}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.17421547013270003
Fold 2 IBS: 0.2050823834385182
Fold 3 IBS: 0.17114430210298628
Fold 4 IBS: 0.17339485761183707
Fold 5 IBS: 0.22351478015249363
[I 2024-04-14 00:54:23,423] Trial 20 finished with value: 0.18947035868770704 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8892982712995542, 'min_weight_fraction_leaf': 0.18720118160246144}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.17111493042801526
Fold 2 IBS: 0.2137721819185777
Fold 3 IBS: 0.16456471169620251
Fold 4 IBS: 0.16449227846347558
Fold 5 IBS: 0.22864796656377134
[I 2024-04-14 00:54:35,135] Trial 21 finished with value: 0.1885184138140085 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7247491835588253, 'min_weight_fraction_leaf': 0.10612931382459131}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.16532773770032788
Fold 2 IBS: 0.2186442284652855
Fold 3 IBS: 0.16460826885307955
Fold 4 IBS: 0.15506743410900792
Fold 5 IBS: 0.23319986958345387
[I 2024-04-14 00:54:44,863] Trial 22 finished with value: 0.18736950774223093 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8844026166095639, 'min_weight_fraction_leaf': 0.08688290860444149}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.16301700829191232
Fold 2 IBS: 0.219030517452768
Fold 3 IBS: 0.1623853390492206
Fold 4 IBS: 0.1532916510108008
Fold 5 IBS: 0.23013904250092193
[I 2024-04-14 00:54:57,306] Trial 23 finished with value: 0.1855727116611247 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 451, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.882373739187446, 'min_weight_fraction_leaf': 0.012868164547398506}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.16304988087529812
Fold 2 IBS: 0.22094207521693815
Fold 3 IBS: 0.161348064662482
Fold 4 IBS: 0.15096714326145844
Fold 5 IBS: 0.23463058158669606
[I 2024-04-14 00:55:10,038] Trial 24 finished with value: 0.18618754912057453 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8872409155608235, 'min_weight_fraction_leaf': 0.04604331935587166}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.1737150468913634
Fold 2 IBS: 0.2064240961037397
Fold 3 IBS: 0.17070043959096043
Fold 4 IBS: 0.17215340254727685
Fold 5 IBS: 0.22073392460374922
[I 2024-04-14 00:55:23,380] Trial 25 finished with value: 0.1887453819474179 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 455, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9949818354422626, 'min_weight_fraction_leaf': 0.04193971879336897}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.17192147575817168
Fold 2 IBS: 0.2125807619877445
Fold 3 IBS: 0.1691262873841453
Fold 4 IBS: 0.16885171298035456
Fold 5 IBS: 0.2265576203614483
[I 2024-04-14 00:55:38,572] Trial 26 finished with value: 0.18980757169437287 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8751983869140558, 'min_weight_fraction_leaf': 0.14849424791584837}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.16246717022558158
Fold 2 IBS: 0.22278551957594211
Fold 3 IBS: 0.15990422558540457
Fold 4 IBS: 0.1487070056469065
Fold 5 IBS: 0.23422547394882334
[I 2024-04-14 00:55:52,775] Trial 27 finished with value: 0.18561787899653162 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8371227222322273, 'min_weight_fraction_leaf': 0.027289624478908987}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.1654696844792975
Fold 2 IBS: 0.2234990134256156
Fold 3 IBS: 0.15946196024021897
Fold 4 IBS: 0.14893349177557935
Fold 5 IBS: 0.2381082176321455
[I 2024-04-14 00:55:58,753] Trial 28 finished with value: 0.18709447351057137 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 204, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8312285602471605, 'min_weight_fraction_leaf': 0.04077685648220064}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.17845647167398127
Fold 2 IBS: 0.2130730563466517
Fold 3 IBS: 0.1730128250957027
Fold 4 IBS: 0.1775098861437066
Fold 5 IBS: 0.22205252382699645
[I 2024-04-14 00:56:10,284] Trial 29 finished with value: 0.19282095261740773 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7271017134796036, 'min_weight_fraction_leaf': 0.1096845451205721}. Best is trial 23 with value: 0.1855727116611247.

Fold 1 IBS: 0.16792251267623906
Fold 2 IBS: 0.2174484716230587
Fold 3 IBS: 0.16273781989489802
Fold 4 IBS: 0.1558940391227505
Fold 5 IBS: 0.23222422254692077
[I 2024-04-14 00:56:23,693] Trial 30 finished with value: 0.18724541317277338 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 455, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7293028765390641, 'min_weight_fraction_leaf': 0.08037045697723012}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.16646920043412164
Fold 2 IBS: 0.22144555868438975
Fold 3 IBS: 0.1612585234507463
Fold 4 IBS: 0.15276461377317607
Fold 5 IBS: 0.23760424924495455
[I 2024-04-14 00:56:30,912] Trial 31 finished with value: 0.18790842911747765 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 209, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8386292091834852, 'min_weight_fraction_leaf': 0.04730132529579094}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.16030007033105986
Fold 2 IBS: 0.22398118562940655
Fold 3 IBS: 0.15846297307347587
Fold 4 IBS: 0.1470891139577854
Fold 5 IBS: 0.23657286223224763
[I 2024-04-14 00:56:37,802] Trial 32 finished with value: 0.18528124104479504 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 206, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9163496831204196, 'min_weight_fraction_leaf': 0.030126739530685447}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.172937674157177
Fold 2 IBS: 0.24427201483908298
Fold 3 IBS: 0.15582695988286352
Fold 4 IBS: 0.14290514986885272
Fold 5 IBS: 0.24818545842857834
[I 2024-04-14 00:56:43,013] Trial 33 finished with value: 0.1928254514353109 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 160, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9201437866465091, 'min_weight_fraction_leaf': 0.07060844824971078}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16533026201292797
Fold 2 IBS: 0.22263639369462013
Fold 3 IBS: 0.16342873596728688
Fold 4 IBS: 0.16226909673388507
Fold 5 IBS: 0.22835592740970792
[I 2024-04-14 00:56:47,717] Trial 34 finished with value: 0.18840408316368557 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 115, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.023639916096884216}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.1768239075644783
Fold 2 IBS: 0.2081027487281694
Fold 3 IBS: 0.17413951134311367
Fold 4 IBS: 0.17907108232142022
Fold 5 IBS: 0.2215257917188389
[I 2024-04-14 00:57:03,141] Trial 35 finished with value: 0.1919326083352041 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 429, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8401348549146568, 'min_weight_fraction_leaf': 0.24235302278015497}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.1940843114270721
Fold 2 IBS: 0.2056845420523829
Fold 3 IBS: 0.18788157295828922
Fold 4 IBS: 0.20006428856720795
Fold 5 IBS: 0.2177170857082032
[I 2024-04-14 00:57:09,900] Trial 36 finished with value: 0.20108636014263107 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 236, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6624062812925291, 'min_weight_fraction_leaf': 0.1276665161224413}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.17340674788508836
Fold 2 IBS: 0.24768190748122734
Fold 3 IBS: 0.16867891640678653
Fold 4 IBS: 0.1616763611285437
Fold 5 IBS: 0.23877880170969434
[I 2024-04-14 00:57:19,798] Trial 37 finished with value: 0.19804454692226806 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6, 'n_estimators': 305, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7790217874657425, 'min_weight_fraction_leaf': 0.062396376437804296}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16624738684053258
Fold 2 IBS: 0.21973229478344297
Fold 3 IBS: 0.16383689986898148
Fold 4 IBS: 0.1555626613940214
Fold 5 IBS: 0.23337565279263775
[I 2024-04-14 00:57:33,845] Trial 38 finished with value: 0.18775097913592323 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9337822506368412, 'min_weight_fraction_leaf': 0.09676916841079641}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.19406740130079023
Fold 2 IBS: 0.2080998067364733
Fold 3 IBS: 0.18690687392991395
Fold 4 IBS: 0.1983924325024786
Fold 5 IBS: 0.21669307860788134
[I 2024-04-14 00:57:46,088] Trial 39 finished with value: 0.20083191861550748 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 336, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8439046690156142, 'min_weight_fraction_leaf': 0.1681587492068492}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.1754231584570973
Fold 2 IBS: 0.20862733191088295
Fold 3 IBS: 0.17201575641485803
Fold 4 IBS: 0.17247754688839995
Fold 5 IBS: 0.22441791937181546
[I 2024-04-14 00:57:50,942] Trial 40 finished with value: 0.19059234260861074 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 166, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.49205438109527067, 'min_weight_fraction_leaf': 0.05363435608897611}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16687091698705347
Fold 2 IBS: 0.22145067973996654
Fold 3 IBS: 0.16083193542269436
Fold 4 IBS: 0.15145269120336982
Fold 5 IBS: 0.23763053320077898
[I 2024-04-14 00:57:56,977] Trial 41 finished with value: 0.18764735131077265 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 213, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8160068596533434, 'min_weight_fraction_leaf': 0.051128939929752766}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16440787739420146
Fold 2 IBS: 0.22051774173279667
Fold 3 IBS: 0.15866302088929105
Fold 4 IBS: 0.1505697309482162
Fold 5 IBS: 0.2344294950935966
[I 2024-04-14 00:58:02,653] Trial 42 finished with value: 0.18571757321162038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 179, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8502001595263011, 'min_weight_fraction_leaf': 0.025832096901499825}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.166093032959539
Fold 2 IBS: 0.22071181466302323
Fold 3 IBS: 0.16315038997597892
Fold 4 IBS: 0.1615108085837709
Fold 5 IBS: 0.22986943061414675
[I 2024-04-14 00:58:06,266] Trial 43 finished with value: 0.18826709535929176 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 86, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7462221833323165, 'min_weight_fraction_leaf': 0.019530073851423135}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.17856291254676518
Fold 2 IBS: 0.20622912686970393
Fold 3 IBS: 0.1728547352397574
Fold 4 IBS: 0.17474142784909633
Fold 5 IBS: 0.22146523571485058
[I 2024-04-14 00:58:11,918] Trial 44 finished with value: 0.19077068764403465 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 183, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9478697073891121, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 32 with value: 0.18528124104479504.

Fold 1 IBS: 0.16512803721910052
Fold 2 IBS: 0.21893230349393553
Fold 3 IBS: 0.1593836385256823
Fold 4 IBS: 0.15058205502042205
Fold 5 IBS: 0.23336241815587846
[I 2024-04-14 00:58:20,946] Trial 45 finished with value: 0.18547769048300378 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6931500413934508, 'min_weight_fraction_leaf': 0.021457257714753555}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.1659546836323674
Fold 2 IBS: 0.2153197227930472
Fold 3 IBS: 0.16360867863772716
Fold 4 IBS: 0.15557836846786757
Fold 5 IBS: 0.233640633124344
[I 2024-04-14 00:58:29,409] Trial 46 finished with value: 0.18682041733107066 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7831947572035725, 'min_weight_fraction_leaf': 0.01931405227872043}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.2065277829489426
Fold 2 IBS: 0.216421790160963
Fold 3 IBS: 0.1977088009136629
Fold 4 IBS: 0.21668719017242724
Fold 5 IBS: 0.21616573903460984
[I 2024-04-14 00:58:36,580] Trial 47 finished with value: 0.21070226064612113 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 239, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6100992136402282, 'min_weight_fraction_leaf': 0.2926129328054348}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16819818157316316
Fold 2 IBS: 0.21738390622648787
Fold 3 IBS: 0.16156044111171175
Fold 4 IBS: 0.15316407589462896
Fold 5 IBS: 0.24011367020312108
[I 2024-04-14 00:58:41,588] Trial 48 finished with value: 0.18808405500182257 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 123, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6791860734720297, 'min_weight_fraction_leaf': 0.003213779418364194}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.17209598869991036
Fold 2 IBS: 0.21187077120599623
Fold 3 IBS: 0.16727613640288252
Fold 4 IBS: 0.16695787846814034
Fold 5 IBS: 0.2272726675718586
[I 2024-04-14 00:58:46,131] Trial 49 finished with value: 0.1890946884697576 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 134, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8621088667656548, 'min_weight_fraction_leaf': 0.1270208206498544}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.18268255673834424
Fold 2 IBS: 0.2116406133958206
Fold 3 IBS: 0.17317749084487088
Fold 4 IBS: 0.18115159425862645
Fold 5 IBS: 0.21966339609454685
[I 2024-04-14 00:58:49,559] Trial 50 finished with value: 0.19366313026644183 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 90, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5323261217237781, 'min_weight_fraction_leaf': 0.07395605063366822}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16168497854927735
Fold 2 IBS: 0.22270197197696373
Fold 3 IBS: 0.15969319515722263
Fold 4 IBS: 0.14836469505004918
Fold 5 IBS: 0.23398522053840312
[I 2024-04-14 00:59:04,372] Trial 51 finished with value: 0.18528601225438318 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9098861737626865, 'min_weight_fraction_leaf': 0.03317554027209381}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16283944924818344
Fold 2 IBS: 0.2217235758500272
Fold 3 IBS: 0.15875960819361015
Fold 4 IBS: 0.1480062250468594
Fold 5 IBS: 0.23242571799847053
[I 2024-04-14 00:59:18,313] Trial 52 finished with value: 0.18475091526743012 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6920435785662685, 'min_weight_fraction_leaf': 0.023623022439616993}. Best is trial 52 with value: 0.18475091526743012.
Fold 1 IBS: 0.16156116277380467
Fold 2 IBS: 0.21645044154721294
Fold 3 IBS: 0.15680725082067987
Fold 4 IBS: 0.1463271703292176
Fold 5 IBS: 0.23173369241683808
[I 2024-04-14 00:59:32,577] Trial 53 finished with value: 0.18257594357755064 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7048480399273186, 'min_weight_fraction_leaf': 0.0010291888027469595}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16345657480280432
Fold 2 IBS: 0.21941864722007984
Fold 3 IBS: 0.1609004507368225
Fold 4 IBS: 0.15232912028765422
Fold 5 IBS: 0.2304650281766842
[I 2024-04-14 00:59:44,626] Trial 54 finished with value: 0.185313964244809 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 436, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6831651026874692, 'min_weight_fraction_leaf': 0.003203141018784241}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.21398942294707132
Fold 2 IBS: 0.22147230949301053
Fold 3 IBS: 0.20481071402497053
Fold 4 IBS: 0.22464130383350117
Fold 5 IBS: 0.21857501052674366
[I 2024-04-14 00:59:59,812] Trial 55 finished with value: 0.21669775216505943 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6865690783108706, 'min_weight_fraction_leaf': 0.38949341979712204}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.21399089065449398
Fold 2 IBS: 0.2214447680813218
Fold 3 IBS: 0.20479456577543795
Fold 4 IBS: 0.22461278604587448
Fold 5 IBS: 0.21855736344590462
[I 2024-04-14 01:00:14,194] Trial 56 finished with value: 0.21668007480060658 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.602520835973954, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17871648336439458
Fold 2 IBS: 0.20746679738869533
Fold 3 IBS: 0.17495717299824248
Fold 4 IBS: 0.1821696732464211
Fold 5 IBS: 0.22029130965865304
[I 2024-04-14 01:00:26,182] Trial 57 finished with value: 0.19272028733128133 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 15, 'n_estimators': 433, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6950911045016969, 'min_weight_fraction_leaf': 0.06162344008829474}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17152567449091236
Fold 2 IBS: 0.2132707954363787
Fold 3 IBS: 0.16577002064558846
Fold 4 IBS: 0.16352941407058058
Fold 5 IBS: 0.2293168915362626
[I 2024-04-14 01:00:36,836] Trial 58 finished with value: 0.18868255923594454 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 410, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6159821240459256, 'min_weight_fraction_leaf': 0.08195171278424525}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17647106232629753
Fold 2 IBS: 0.20824417376602933
Fold 3 IBS: 0.1723553183748716
Fold 4 IBS: 0.1736062035933313
Fold 5 IBS: 0.22224901748255857
[I 2024-04-14 01:00:51,269] Trial 59 finished with value: 0.19058515510861768 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 377, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.525386145731032, 'min_weight_fraction_leaf': 0.000152340144876216}. Best is trial 53 with value: 0.18257594357755064.

Fold 1 IBS: 0.17342492293804432
Fold 2 IBS: 0.2110732537830341
Fold 3 IBS: 0.16831819527481992
Fold 4 IBS: 0.16873369129336893
Fold 5 IBS: 0.22655614890084055
[I 2024-04-14 01:01:09,607] Trial 60 finished with value: 0.18962124243802156 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5735294094022945, 'min_weight_fraction_leaf': 0.10077092974890593}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16275315104094723
Fold 2 IBS: 0.22028966274589679
Fold 3 IBS: 0.16253743592400494
Fold 4 IBS: 0.15352895984062664
Fold 5 IBS: 0.23021227496706434
[I 2024-04-14 01:01:21,415] Trial 61 finished with value: 0.18586429690370798 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7582468632632998, 'min_weight_fraction_leaf': 0.014165988553227182}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16187634732795245
Fold 2 IBS: 0.21936803684113038
Fold 3 IBS: 0.1608633743218315
Fold 4 IBS: 0.15050003762977443
Fold 5 IBS: 0.23315135185396704
[I 2024-04-14 01:01:34,604] Trial 62 finished with value: 0.18515182959493115 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 446, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9688682344495251, 'min_weight_fraction_leaf': 0.03803430028119831}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16803000111589547
Fold 2 IBS: 0.21883335722590105
Fold 3 IBS: 0.16153399726646753
Fold 4 IBS: 0.15499454989097905
Fold 5 IBS: 0.23015675492479587
[I 2024-04-14 01:01:47,858] Trial 63 finished with value: 0.18670973208480782 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 476, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4289211196547223, 'min_weight_fraction_leaf': 0.03483517796766671}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16353133471191258
Fold 2 IBS: 0.22078931633305934
Fold 3 IBS: 0.16232987702451745
Fold 4 IBS: 0.1497770751049068
Fold 5 IBS: 0.23519973886423967
[I 2024-04-14 01:02:03,503] Trial 64 finished with value: 0.18632546840772718 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 483, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9928124170835537, 'min_weight_fraction_leaf': 0.0546315910617156}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16705858086425657
Fold 2 IBS: 0.21688710748739626
Fold 3 IBS: 0.16302480802361138
Fold 4 IBS: 0.16043857461543376
Fold 5 IBS: 0.22735018728687206
[I 2024-04-14 01:02:14,529] Trial 65 finished with value: 0.186951851655514 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 346, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.700753371069358, 'min_weight_fraction_leaf': 0.034080382470936726}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.2139764009793113
Fold 2 IBS: 0.22128743928758063
Fold 3 IBS: 0.20478422039927321
Fold 4 IBS: 0.22461901938020365
Fold 5 IBS: 0.21866318582772845
[I 2024-04-14 01:02:26,436] Trial 66 finished with value: 0.21666605317481946 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 440, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9697511853457705, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17803507005686864
Fold 2 IBS: 0.20584595762292543
Fold 3 IBS: 0.17289828813524646
Fold 4 IBS: 0.177343485740087
Fold 5 IBS: 0.22038680074032185
[I 2024-04-14 01:02:40,733] Trial 67 finished with value: 0.19090192045908988 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 493, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8083420047439778, 'min_weight_fraction_leaf': 0.0005690362936050055}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.18517903096649513
Fold 2 IBS: 0.2068570229240262
Fold 3 IBS: 0.1787293688926839
Fold 4 IBS: 0.18812296323512723
Fold 5 IBS: 0.2160660198664728
[I 2024-04-14 01:02:52,558] Trial 68 finished with value: 0.19499088117696103 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.22939188072225208, 'min_weight_fraction_leaf': 0.06709563455447608}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.18645916216015707
Fold 2 IBS: 0.20636548084294315
Fold 3 IBS: 0.17885851202915032
Fold 4 IBS: 0.18718410387690065
Fold 5 IBS: 0.21792963761071232
[I 2024-04-14 01:03:03,192] Trial 69 finished with value: 0.19535937930397268 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9134125139788976, 'min_weight_fraction_leaf': 0.09022342402306419}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1757749566349244
Fold 2 IBS: 0.2608203853544215
Fold 3 IBS: 0.1687965292943309
Fold 4 IBS: 0.16154593350334548
Fold 5 IBS: 0.2409053655581546
[I 2024-04-14 01:03:13,788] Trial 70 finished with value: 0.20156863406903539 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 374, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9558804805474729, 'min_weight_fraction_leaf': 0.038804497461907755}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1641556888310035
Fold 2 IBS: 0.21756591667129618
Fold 3 IBS: 0.16214425980311192
Fold 4 IBS: 0.1527006421467362
Fold 5 IBS: 0.23008748551996394
[I 2024-04-14 01:03:26,681] Trial 71 finished with value: 0.18533079859442234 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 449, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6369371661585259, 'min_weight_fraction_leaf': 0.01592906514292467}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16591246996228284
Fold 2 IBS: 0.2157266700943674
Fold 3 IBS: 0.1639704528415932
Fold 4 IBS: 0.15917069749386206
Fold 5 IBS: 0.22728835985586845
[I 2024-04-14 01:03:38,050] Trial 72 finished with value: 0.18641373004959477 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 423, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6355486112323981, 'min_weight_fraction_leaf': 0.016225042494993316}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16466547332455966
Fold 2 IBS: 0.21692658302629209
Fold 3 IBS: 0.1589302212774401
Fold 4 IBS: 0.14980038348586724
Fold 5 IBS: 0.23137411159828591
[I 2024-04-14 01:03:49,921] Trial 73 finished with value: 0.184339354542489 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 452, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5876918007096606, 'min_weight_fraction_leaf': 0.01373372285606849}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16792178126681906
Fold 2 IBS: 0.21606101236454162
Fold 3 IBS: 0.16289143446225338
Fold 4 IBS: 0.15694953508014142
Fold 5 IBS: 0.2316203069237443
[I 2024-04-14 01:04:01,880] Trial 74 finished with value: 0.18708881401949995 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 451, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5762811196680634, 'min_weight_fraction_leaf': 0.04721403021162478}. Best is trial 53 with value: 0.18257594357755064.

Fold 1 IBS: 0.16278536069617075
Fold 2 IBS: 0.22061911570320727
Fold 3 IBS: 0.15948095174532076
Fold 4 IBS: 0.1500453215492157
Fold 5 IBS: 0.23108140998200039
[I 2024-04-14 01:04:15,333] Trial 75 finished with value: 0.18480243193518295 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6487943567829829, 'min_weight_fraction_leaf': 0.011079149496446542}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1649931201311961
Fold 2 IBS: 0.2191098546301487
Fold 3 IBS: 0.1604180424655896
Fold 4 IBS: 0.15133070246635846
Fold 5 IBS: 0.23270813963892614
[I 2024-04-14 01:04:32,435] Trial 76 finished with value: 0.18571197186644378 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 496, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6611270444897925, 'min_weight_fraction_leaf': 0.03472791790328323}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17454705567490922
Fold 2 IBS: 0.20946654124798095
Fold 3 IBS: 0.17107052561345987
Fold 4 IBS: 0.17205506925206807
Fold 5 IBS: 0.22301050367917757
[I 2024-04-14 01:04:45,001] Trial 77 finished with value: 0.19002993909351912 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 468, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5365605521283588, 'min_weight_fraction_leaf': 0.11295942956753599}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.18204012108405643
Fold 2 IBS: 0.2063716852750058
Fold 3 IBS: 0.17875146851232082
Fold 4 IBS: 0.18921011660617745
Fold 5 IBS: 0.2162548711235392
[I 2024-04-14 01:04:55,972] Trial 78 finished with value: 0.19452565252021997 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 427, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5917795612536799, 'min_weight_fraction_leaf': 0.2198684675175928}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17845532120437899
Fold 2 IBS: 0.20772503338895465
Fold 3 IBS: 0.17421627745462215
Fold 4 IBS: 0.18019949439245914
Fold 5 IBS: 0.22083458875793646
[I 2024-04-14 01:05:09,696] Trial 79 finished with value: 0.19228614303967032 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.49597522186369347, 'min_weight_fraction_leaf': 0.06112532202305438}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16158996672320755
Fold 2 IBS: 0.21729610032334276
Fold 3 IBS: 0.157796999636179
Fold 4 IBS: 0.1472728675908385
Fold 5 IBS: 0.23183976837586612
[I 2024-04-14 01:05:20,873] Trial 80 finished with value: 0.18315914052988677 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 395, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6281972616252203, 'min_weight_fraction_leaf': 0.00848688046818526}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16157863775376022
Fold 2 IBS: 0.22087534780676452
Fold 3 IBS: 0.15999281456554124
Fold 4 IBS: 0.14853123619761843
Fold 5 IBS: 0.23150501980376892
[I 2024-04-14 01:05:32,177] Trial 81 finished with value: 0.18449661122549066 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7386940991152582, 'min_weight_fraction_leaf': 0.01046274314610217}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16352260586628395
Fold 2 IBS: 0.22200502430399466
Fold 3 IBS: 0.15886916219783537
Fold 4 IBS: 0.14807572814886177
Fold 5 IBS: 0.2339085838911687
[I 2024-04-14 01:05:42,736] Trial 82 finished with value: 0.1852762208816289 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7162267948855195, 'min_weight_fraction_leaf': 0.032010312646594104}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16546027653935427
Fold 2 IBS: 0.2211659942343032
Fold 3 IBS: 0.16100661860428056
Fold 4 IBS: 0.15097334931915155
Fold 5 IBS: 0.2358306721546786
[I 2024-04-14 01:05:53,009] Trial 83 finished with value: 0.18688738217035364 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 387, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7326293257583885, 'min_weight_fraction_leaf': 0.04562346387387325}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16285220423552985
Fold 2 IBS: 0.2188473500308101
Fold 3 IBS: 0.1599688920049345
Fold 4 IBS: 0.14885881691304034
Fold 5 IBS: 0.23161635394463342
[I 2024-04-14 01:06:02,464] Trial 84 finished with value: 0.18442872342578964 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 356, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7090996631118544, 'min_weight_fraction_leaf': 0.011358284348193259}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16285549245105505
Fold 2 IBS: 0.21942277067272614
Fold 3 IBS: 0.15946829525657427
Fold 4 IBS: 0.14838517247840774
Fold 5 IBS: 0.23122387168068076
[I 2024-04-14 01:06:12,384] Trial 85 finished with value: 0.1842711205078888 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 368, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7186868789202818, 'min_weight_fraction_leaf': 0.01496729486923688}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16128591165678588
Fold 2 IBS: 0.21980011323918688
Fold 3 IBS: 0.15937248726208542
Fold 4 IBS: 0.1486127266622536
Fold 5 IBS: 0.2323048878882266
[I 2024-04-14 01:06:22,636] Trial 86 finished with value: 0.18427522534170765 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7543993526497688, 'min_weight_fraction_leaf': 0.013808236520630852}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16094110571393064
Fold 2 IBS: 0.21986993252478362
Fold 3 IBS: 0.1588596843743244
Fold 4 IBS: 0.14614051224869679
Fold 5 IBS: 0.23352782586558365
[I 2024-04-14 01:06:33,362] Trial 87 finished with value: 0.1838678121454638 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7599338110461693, 'min_weight_fraction_leaf': 0.01151287364248438}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16095650535504896
Fold 2 IBS: 0.21964363350705826
Fold 3 IBS: 0.15886397081421852
Fold 4 IBS: 0.14614666331841772
Fold 5 IBS: 0.23313729954057164
[I 2024-04-14 01:06:45,726] Trial 88 finished with value: 0.183749614507063 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 360, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7606093640745762, 'min_weight_fraction_leaf': 0.010471830721284079}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16110829576026084
Fold 2 IBS: 0.21851253412110366
Fold 3 IBS: 0.15675512925824683
Fold 4 IBS: 0.14727139463073632
Fold 5 IBS: 0.23209620967854572
[I 2024-04-14 01:06:58,447] Trial 89 finished with value: 0.18314871268977867 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7587282239351308, 'min_weight_fraction_leaf': 0.008176941543787496}. Best is trial 53 with value: 0.18257594357755064.

Fold 1 IBS: 0.18162653052097805
Fold 2 IBS: 0.20612651784753333
Fold 3 IBS: 0.1771784733434652
Fold 4 IBS: 0.18941755917999278
Fold 5 IBS: 0.21614311489575638
[I 2024-04-14 01:07:10,179] Trial 90 finished with value: 0.19409843915754516 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7635642567316503, 'min_weight_fraction_leaf': 0.280081595660318}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16186089564069253
Fold 2 IBS: 0.21899259491528042
Fold 3 IBS: 0.15921485444738478
Fold 4 IBS: 0.148193042465612
Fold 5 IBS: 0.23190417972474658
[I 2024-04-14 01:07:22,010] Trial 91 finished with value: 0.18403311343874326 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 323, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.789178452265885, 'min_weight_fraction_leaf': 0.011545143067658635}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16265353400501528
Fold 2 IBS: 0.2175575638863236
Fold 3 IBS: 0.16133894389326223
Fold 4 IBS: 0.15458872962543557
Fold 5 IBS: 0.229228321655463
[I 2024-04-14 01:07:33,464] Trial 92 finished with value: 0.18507341861309995 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 320, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7985486683510279, 'min_weight_fraction_leaf': 0.007901199895383132}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1620791424844971
Fold 2 IBS: 0.21900011819041879
Fold 3 IBS: 0.15920401655120014
Fold 4 IBS: 0.14637781084518398
Fold 5 IBS: 0.23282788799260146
[I 2024-04-14 01:07:45,116] Trial 93 finished with value: 0.1838977952127803 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 341, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7705275977783406, 'min_weight_fraction_leaf': 0.013704505872889598}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1793411990654569
Fold 2 IBS: 0.20613622174736498
Fold 3 IBS: 0.17275187695258565
Fold 4 IBS: 0.17818980825839892
Fold 5 IBS: 0.22022859697507743
[I 2024-04-14 01:07:56,043] Trial 94 finished with value: 0.19132954059977678 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 325, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7755480125040337, 'min_weight_fraction_leaf': 0.05063148942960361}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1610317396130936
Fold 2 IBS: 0.2202627419888432
Fold 3 IBS: 0.15951569709008712
Fold 4 IBS: 0.1458873166232896
Fold 5 IBS: 0.23482464408960785
[I 2024-04-14 01:08:07,919] Trial 95 finished with value: 0.18430442788098428 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 350, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7576152916362451, 'min_weight_fraction_leaf': 0.023770792047509592}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17066297262534935
Fold 2 IBS: 0.22975974207949945
Fold 3 IBS: 0.1519444360637532
Fold 4 IBS: 0.13950104633987118
Fold 5 IBS: 0.2439409705061117
[I 2024-04-14 01:08:20,697] Trial 96 finished with value: 0.18716183352291696 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7560665367452727, 'min_weight_fraction_leaf': 0.02298285611760403}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.18361848353136237
Fold 2 IBS: 0.2052929877088459
Fold 3 IBS: 0.17656731308943907
Fold 4 IBS: 0.18399483123099875
Fold 5 IBS: 0.21866940095388543
[I 2024-04-14 01:08:31,774] Trial 97 finished with value: 0.1936286033029063 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 294, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7936215885628722, 'min_weight_fraction_leaf': 0.0702592146341984}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16102070948187022
Fold 2 IBS: 0.22255035648510013
Fold 3 IBS: 0.1611617777057763
Fold 4 IBS: 0.14597987975871002
Fold 5 IBS: 0.23595320519699498
[I 2024-04-14 01:08:43,380] Trial 98 finished with value: 0.18533318572569035 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.817957524711727, 'min_weight_fraction_leaf': 0.0008689368092096427}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16218129609850532
Fold 2 IBS: 0.21864999525446885
Fold 3 IBS: 0.1599823914541389
Fold 4 IBS: 0.14944190039573815
Fold 5 IBS: 0.23537346983323632
[I 2024-04-14 01:08:53,917] Trial 99 finished with value: 0.1851258106072175 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 310, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7505423882418932, 'min_weight_fraction_leaf': 0.027516392549616332}. Best is trial 53 with value: 0.18257594357755064.


* Best trial for IBS:
 FrozenTrial(number=53, state=TrialState.COMPLETE, values=[0.18257594357755064], datetime_start=datetime.datetime(2024, 4, 14, 0, 59, 18, 322205), datetime_complete=datetime.datetime(2024, 4, 14, 0, 59, 32, 576112), params={'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7048480399273186, 'min_weight_fraction_leaf': 0.0010291888027469595}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=53, value=None)


* Best Score for IBS:
 0.18257594357755064

In [107]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [108]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.794
train_ibs:  0.183

#### Test

In [109]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [110]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=12, max_features=None, max_leaf_nodes=6,
                   max_samples=0.7030590704740037, min_samples_leaf=6,
                   min_samples_split=13,
                   min_weight_fraction_leaf=0.020016091327628317,
                   n_estimators=273, random_state=123, warm_start=True)

C-index score: 0.618

ExtraSurvivalTrees(max_depth=13, max_features='log2', max_leaf_nodes=6,
                   max_samples=0.7048480399273186, min_samples_leaf=1,
                   min_samples_split=12,
                   min_weight_fraction_leaf=0.0010291888027469595,
                   n_estimators=485, random_state=123, warm_start=True)

IBS: 0.215

In [111]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [112]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 01:08:58,194] A new study created in memory with name: no-name-51d6e374-5a0a-4860-94b4-751b2d541d3d

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:09:51,644] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:10:20,463] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:10:48,855] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:11:33,605] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:11:51,067] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:11:55,492] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:12:39,699] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:12:52,213] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:12:53,913] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6450892857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6314553990610329
[I 2024-04-14 01:14:48,426] Trial 9 finished with value: 0.7334874350516556 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 01:17:39,807] Trial 10 finished with value: 0.685844917453683 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:20:50,136] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 01:23:28,489] Trial 12 finished with value: 0.703856671925322 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:24:47,980] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:26:34,265] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:28:11,930] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:29:15,365] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:31:31,158] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:34:37,186] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:34:44,054] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:35:50,102] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 01:38:10,965] Trial 21 finished with value: 0.5772199484787512 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.5892018779342723
[I 2024-04-14 01:40:20,440] Trial 22 finished with value: 0.7242619704042982 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:42:04,682] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:43:38,506] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:44:35,429] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 01:46:33,696] Trial 26 finished with value: 0.5421550134138162 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:48:32,597] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:50:06,779] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:51:13,276] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:52:30,759] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 01:54:58,351] Trial 31 finished with value: 0.6331023014199277 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:57:21,406] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:58:56,077] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:01:12,839] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:01:41,001] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:03:44,664] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:03:48,258] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:04:32,588] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:05:42,536] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:30:44,751] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 02:30:45,055] Trial 41 finished with value: 0.669385375890579 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 02:30:54,141] Trial 42 finished with value: 0.7134801645905124 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:31:03,525] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8842674505407576, 'learning_rate': 0.01661025860323942, 'dropout_rate': 0.11585930219083569, 'n_estimators': 137, 'criterion': 'squared_error', 'ccp_alpha': 1.1648976852393267, 'min_weight_fraction_leaf': 0.2628710582683432, 'max_features': 'auto', 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.8573418806492034, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:38:05,988] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9369906738516638, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.2600301660425801, 'n_estimators': 236, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.44828046137677974, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.723434155611114, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:38:16,118] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.8508184042922002, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 1.5950934322255128, 'min_weight_fraction_leaf': 0.3672741344156673, 'max_features': 0.1, 'min_impurity_decrease': 9.999645993471922e-07, 'validation_fraction': 0.894831925816593, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:38:25,703] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.007318845785810312, 'dropout_rate': 0.9694253886674298, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.0041987442036233, 'min_weight_fraction_leaf': 0.41002460147990016, 'max_features': 'log2', 'min_impurity_decrease': 2.595046469962732e-06, 'validation_fraction': 0.8313632450390351, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:39:06,380] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7881603947064, 'learning_rate': 0.024308371272538112, 'dropout_rate': 0.11931202058020746, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.46145706703279166, 'min_weight_fraction_leaf': 0.14638041253524992, 'max_features': 'sqrt', 'min_impurity_decrease': 3.124298610650395e-07, 'validation_fraction': 0.885979815139411, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:56:23,203] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9116990829700251, 'learning_rate': 0.0012697805220829685, 'dropout_rate': 0.2528872202970577, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.33510432917217986, 'max_features': None, 'min_impurity_decrease': 1.0186154127552982e-07, 'validation_fraction': 0.9531390028399015, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:57:15,745] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.9503333802028551, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 420, 'criterion': 'friedman_mse', 'ccp_alpha': 6.6082653368298185, 'min_weight_fraction_leaf': 0.22522458248307622, 'max_features': 'auto', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6535676180999174, 'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:57:18,846] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.02150329631555176, 'dropout_rate': 0.3666232473259417, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 1.3133337630740611, 'min_weight_fraction_leaf': 0.47565429586146185, 'max_features': 'auto', 'min_impurity_decrease': 1.8633023596687113e-06, 'validation_fraction': 0.8119058063801081, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 02:58:02,655] Trial 51 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9947653262192967, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.1592738913883298, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'auto', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:58:04,151] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9838263913881168, 'learning_rate': 0.007162813008405933, 'dropout_rate': 0.17395958025907304, 'n_estimators': 17, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.37395658840830287, 'max_features': 'auto', 'min_impurity_decrease': 1.9340874733278664e-07, 'validation_fraction': 0.9673436129299916, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.578125
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 02:58:17,756] Trial 53 finished with value: 0.7035675756915192 and parameters: {'subsample': 0.8832560354405471, 'learning_rate': 0.013515333982145643, 'dropout_rate': 0.1066966218862955, 'n_estimators': 115, 'criterion': 'squared_error', 'ccp_alpha': 0.00962522783777093, 'min_weight_fraction_leaf': 0.3102859232383388, 'max_features': 'auto', 'min_impurity_decrease': 5.129651522544754e-07, 'validation_fraction': 0.9977392300861776, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:58:27,418] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8839401595086688, 'learning_rate': 0.013720158661514745, 'dropout_rate': 0.11547001021095907, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.9585348267499517, 'min_weight_fraction_leaf': 0.31281161202556473, 'max_features': 'auto', 'min_impurity_decrease': 5.50189997369896e-07, 'validation_fraction': 0.9994238437001496, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:58:29,349] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8309421840852462, 'learning_rate': 0.011311223505622352, 'dropout_rate': 0.20419816136861105, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 0.3986990587399982, 'min_weight_fraction_leaf': 0.2039350020074899, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8756039908972886, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:00:51,354] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.72294472419416, 'learning_rate': 0.030529655796453406, 'dropout_rate': 0.1042670173421051, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.0260576154507228, 'min_weight_fraction_leaf': 0.26869875361297285, 'max_features': 1, 'min_impurity_decrease': 1.0882152569265186e-06, 'validation_fraction': 0.9043438819355977, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:00:59,863] Trial 57 finished with value: 0.5 and parameters: {'subsample': 0.781561535505851, 'learning_rate': 0.019599111388603693, 'dropout_rate': 0.28746581622574, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.6775249385492055, 'min_weight_fraction_leaf': 0.4147367845229429, 'max_features': 'auto', 'min_impurity_decrease': 5.608534822955176e-07, 'validation_fraction': 0.5838562151808616, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:01:16,250] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.4443705051573945, 'learning_rate': 0.04030629833839253, 'dropout_rate': 0.24216293738207553, 'n_estimators': 164, 'criterion': 'squared_error', 'ccp_alpha': 0.7497240498249881, 'min_weight_fraction_leaf': 0.33754637584813874, 'max_features': 0.1, 'min_impurity_decrease': 3.445912059389303e-07, 'validation_fraction': 0.7729698485030033, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:03:14,625] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9301898151121387, 'learning_rate': 0.014811565508437466, 'dropout_rate': 0.1837704285299646, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.302647558909275, 'max_features': 'log2', 'min_impurity_decrease': 4.132096543200702e-07, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:03:56,528] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.2779429418662181, 'learning_rate': 0.005013007250233982, 'dropout_rate': 0.14183557134552166, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 1.322729891908786, 'min_weight_fraction_leaf': 0.2834981878637842, 'max_features': 'auto', 'min_impurity_decrease': 1.9418303906939395e-06, 'validation_fraction': 0.8435510786021796, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:04:00,399] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.009978939472425662, 'dropout_rate': 0.2238557425834033, 'n_estimators': 70, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.4432436454062534, 'max_features': 'auto', 'min_impurity_decrease': 1.92080140518381e-07, 'validation_fraction': 0.9540853929856796, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 03:04:22,074] Trial 62 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9949849995633986, 'learning_rate': 0.00590733686751327, 'dropout_rate': 0.15426665038628304, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.022717462020606087, 'min_weight_fraction_leaf': 0.3771525913161122, 'max_features': 'auto', 'min_impurity_decrease': 1.6541961435697376e-07, 'validation_fraction': 0.998924391459097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:04:25,060] Trial 63 finished with value: 0.7163384910196757 and parameters: {'subsample': 0.8686583129899306, 'learning_rate': 0.001290161829137394, 'dropout_rate': 0.1898785022640528, 'n_estimators': 58, 'criterion': 'squared_error', 'ccp_alpha': 0.018078806214999348, 'min_weight_fraction_leaf': 0.3861329521141052, 'max_features': 'auto', 'min_impurity_decrease': 8.327527140717665e-07, 'validation_fraction': 0.932887892507485, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:04:30,616] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.8645070165323501, 'learning_rate': 0.09405807235270042, 'dropout_rate': 0.18802779859574847, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.35251200695718055, 'max_features': 'auto', 'min_impurity_decrease': 9.420976138154327e-07, 'validation_fraction': 0.9231276840562984, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:04:39,593] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.903563418868777, 'learning_rate': 0.0016217786521075337, 'dropout_rate': 0.27304642297183634, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.35075027656676333, 'min_weight_fraction_leaf': 0.46836556984836597, 'max_features': 'auto', 'min_impurity_decrease': 0.00018567504305581884, 'validation_fraction': 0.8837902558696593, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:07:03,360] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8164719060956207, 'learning_rate': 0.012803396580721372, 'dropout_rate': 0.13161439171907266, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.8927340743616367, 'min_weight_fraction_leaf': 0.24360172036034505, 'max_features': 'sqrt', 'min_impurity_decrease': 5.724092120969544e-07, 'validation_fraction': 0.9783741103646215, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:07:05,675] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8652614464897083, 'learning_rate': 0.017792589526001042, 'dropout_rate': 0.4308859881762669, 'n_estimators': 45, 'criterion': 'friedman_mse', 'ccp_alpha': 2.352310671798754, 'min_weight_fraction_leaf': 0.4527437444308926, 'max_features': 'auto', 'min_impurity_decrease': 3.132340488371029e-07, 'validation_fraction': 0.6922946122950581, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6948051948051948
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:07:38,658] Trial 68 finished with value: 0.6328510949834479 and parameters: {'subsample': 0.1828808967076968, 'learning_rate': 0.009763210879301733, 'dropout_rate': 0.227818798660288, 'n_estimators': 235, 'criterion': 'squared_error', 'ccp_alpha': 0.29598676708348526, 'min_weight_fraction_leaf': 0.4165856705288462, 'max_features': 'auto', 'min_impurity_decrease': 1.2512174866550223e-06, 'validation_fraction': 0.4611449164937295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:07:41,375] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7498611166680669, 'learning_rate': 0.04820609879441119, 'dropout_rate': 0.32090257654334975, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.7413034944146035, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': None, 'min_impurity_decrease': 2.3700234556978203e-06, 'validation_fraction': 0.8668588900403627, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:09:34,869] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.911088145674265, 'learning_rate': 0.0228629548900178, 'dropout_rate': 0.1866548676915602, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.2482267223936536, 'min_weight_fraction_leaf': 0.22078244504185224, 'max_features': 'auto', 'min_impurity_decrease': 4.8419433611640654e-06, 'validation_fraction': 0.9040102661274384, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:09:35,454] Trial 71 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9622573373756947, 'learning_rate': 0.005576631516276089, 'dropout_rate': 0.8462757993963043, 'n_estimators': 10, 'criterion': 'squared_error', 'ccp_alpha': 0.027818996011453684, 'min_weight_fraction_leaf': 0.38504148100809776, 'max_features': 'auto', 'min_impurity_decrease': 1.41859363723174e-07, 'validation_fraction': 0.9482945382047324, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 03:09:36,392] Trial 72 finished with value: 0.685844917453683 and parameters: {'subsample': 0.950430822794731, 'learning_rate': 0.0053064296987160465, 'dropout_rate': 0.7234474037831898, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.00479380572002332, 'min_weight_fraction_leaf': 0.3972455103663686, 'max_features': 'auto', 'min_impurity_decrease': 1.366202506746777e-07, 'validation_fraction': 0.9693127617967663, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:10:02,483] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.885575181084042, 'learning_rate': 0.003536949776399335, 'dropout_rate': 0.9088405719505623, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.35670027635353807, 'min_weight_fraction_leaf': 0.35822108217683835, 'max_features': 'auto', 'min_impurity_decrease': 4.2499433142234475e-07, 'validation_fraction': 0.20224553600156958, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:10:03,613] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.5836393594321302, 'learning_rate': 0.009340590354270865, 'dropout_rate': 0.8412829433501265, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 0.6246646628477466, 'min_weight_fraction_leaf': 0.42429330054001607, 'max_features': 'auto', 'min_impurity_decrease': 2.8316890658493217e-07, 'validation_fraction': 0.9340639943674915, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:10:12,219] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.5200735929114648, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.128072187563372, 'n_estimators': 99, 'criterion': 'squared_error', 'ccp_alpha': 0.9318541971101635, 'min_weight_fraction_leaf': 0.329634418869288, 'max_features': 'auto', 'min_impurity_decrease': 7.061217543698309e-07, 'validation_fraction': 0.7955814541363518, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:11:14,321] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9312152381840203, 'learning_rate': 0.011963342113513162, 'dropout_rate': 0.640126219035525, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.3025319765337648, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 1.4007647974844957e-07, 'validation_fraction': 0.7443065618057785, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:11:17,358] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.9689893891792536, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.5468452572744673, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.5979952840890602, 'min_weight_fraction_leaf': 0.25434486774085874, 'max_features': 1, 'min_impurity_decrease': 2.595814783640358e-07, 'validation_fraction': 0.9726620416567261, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:13:45,557] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.8595097382714689, 'learning_rate': 0.0034833775412467377, 'dropout_rate': 0.10127265486770577, 'n_estimators': 473, 'criterion': 'friedman_mse', 'ccp_alpha': 1.4812955313687048, 'min_weight_fraction_leaf': 0.3131777562301877, 'max_features': 'auto', 'min_impurity_decrease': 1.0290395334568972e-07, 'validation_fraction': 0.8280705957992395, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:14:04,811] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.8015344520335466, 'learning_rate': 0.0012723432779221475, 'dropout_rate': 0.8831816560103296, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 1.8162144553916222, 'min_weight_fraction_leaf': 0.34854584327537885, 'max_features': 'log2', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9186131425355593, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:14:51,361] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.8367376204446394, 'learning_rate': 0.007364213642980483, 'dropout_rate': 0.702176827465796, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.3004980772276427, 'max_features': 'auto', 'min_impurity_decrease': 7.124034486377485e-07, 'validation_fraction': 0.9461272730178157, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 03:14:51,931] Trial 81 finished with value: 0.6684464087544287 and parameters: {'subsample': 0.9965174069194047, 'learning_rate': 0.007618988907310126, 'dropout_rate': 0.16198782693693461, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.025916849299345394, 'min_weight_fraction_leaf': 0.38961846335957595, 'max_features': 'auto', 'min_impurity_decrease': 1.766837964281054e-07, 'validation_fraction': 0.9399776044267211, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:14:52,597] Trial 82 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9646485447558332, 'learning_rate': 0.006224947240679894, 'dropout_rate': 0.16886094857249775, 'n_estimators': 12, 'criterion': 'squared_error', 'ccp_alpha': 0.017707201149411784, 'min_weight_fraction_leaf': 0.38368758581534546, 'max_features': 'auto', 'min_impurity_decrease': 2.2084017063206466e-07, 'validation_fraction': 0.38434645874984097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:14:54,382] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9674120427099258, 'learning_rate': 0.012634880227471968, 'dropout_rate': 0.24105562803816832, 'n_estimators': 36, 'criterion': 'squared_error', 'ccp_alpha': 0.49986991060004404, 'min_weight_fraction_leaf': 0.4028329566858333, 'max_features': 'auto', 'min_impurity_decrease': 3.7732222209322964e-07, 'validation_fraction': 0.29115286333596435, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:17:24,697] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.9187525025568754, 'learning_rate': 0.004160535799768975, 'dropout_rate': 0.2015650563323303, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.3706545282616189, 'max_features': 'auto', 'min_impurity_decrease': 1.4899460740955453e-06, 'validation_fraction': 0.39196940849585504, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:17:25,518] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.8968529080615669, 'learning_rate': 0.017670564382826763, 'dropout_rate': 0.2745425858009699, 'n_estimators': 16, 'criterion': 'squared_error', 'ccp_alpha': 1.0637247669291705, 'min_weight_fraction_leaf': 0.3822449692929958, 'max_features': 'auto', 'min_impurity_decrease': 2.3419797764275672e-07, 'validation_fraction': 0.5434611145938996, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:17:28,602] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.9428961007941905, 'learning_rate': 0.011402694667743098, 'dropout_rate': 0.134159592794598, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.23936333725455253, 'min_weight_fraction_leaf': 0.27268436275419344, 'max_features': 'sqrt', 'min_impurity_decrease': 4.779762823701413e-07, 'validation_fraction': 0.3558315208173153, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:17:31,140] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.9642091284813806, 'learning_rate': 0.009067059593875184, 'dropout_rate': 0.8053771471721777, 'n_estimators': 81, 'criterion': 'squared_error', 'ccp_alpha': 0.2360450448272922, 'min_weight_fraction_leaf': 0.36130355929034824, 'max_features': 'auto', 'min_impurity_decrease': 1.6608380458349677e-05, 'validation_fraction': 0.48901442871881995, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:17:34,249] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9166952579476793, 'learning_rate': 0.027428474441345257, 'dropout_rate': 0.9942411221597407, 'n_estimators': 142, 'criterion': 'squared_error', 'ccp_alpha': 0.736661694905559, 'min_weight_fraction_leaf': 0.3421577371226225, 'max_features': 'auto', 'min_impurity_decrease': 1.3101245725982968e-07, 'validation_fraction': 0.9819335319333689, 'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:19:30,960] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.38730242337646104, 'learning_rate': 0.020510559401054396, 'dropout_rate': 0.1637660735943165, 'n_estimators': 425, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5135760709608489, 'min_weight_fraction_leaf': 0.2338348901049672, 'max_features': None, 'min_impurity_decrease': 8.646658253890459e-07, 'validation_fraction': 0.2693385873685563, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:19:42,924] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.3351416528138606, 'learning_rate': 0.001130725657308556, 'dropout_rate': 0.21238181902547987, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 1.098484581242824, 'min_weight_fraction_leaf': 0.45624128176873047, 'max_features': 'auto', 'min_impurity_decrease': 2.8288075937135275e-07, 'validation_fraction': 0.8654647894710668, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:19:44,114] Trial 91 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.973859764718155, 'learning_rate': 0.006991850627181431, 'dropout_rate': 0.17031167363762192, 'n_estimators': 24, 'criterion': 'squared_error', 'ccp_alpha': 0.03873428305932247, 'min_weight_fraction_leaf': 0.38456389013049225, 'max_features': 'auto', 'min_impurity_decrease': 2.1057313400290866e-07, 'validation_fraction': 0.9606810926219381, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:19:45,344] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.8803056919201186, 'learning_rate': 0.005845639334984173, 'dropout_rate': 0.17652933801835793, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.20706720697578515, 'min_weight_fraction_leaf': 0.43161442258073124, 'max_features': 'auto', 'min_impurity_decrease': 2.0676851144372516e-07, 'validation_fraction': 0.9025757365890354, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:19:45,869] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.9733203192391623, 'learning_rate': 0.014432394643112474, 'dropout_rate': 0.2300740953304724, 'n_estimators': 4, 'criterion': 'squared_error', 'ccp_alpha': 0.46903049977228617, 'min_weight_fraction_leaf': 0.404652010953728, 'max_features': 'auto', 'min_impurity_decrease': 5.086967260434284e-07, 'validation_fraction': 0.9736018036138772, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:19:47,693] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.9359287316154687, 'learning_rate': 0.003576820689332409, 'dropout_rate': 0.14182769534201045, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 0.850632602885982, 'min_weight_fraction_leaf': 0.41989514755999646, 'max_features': 'auto', 'min_impurity_decrease': 3.640599784132377e-07, 'validation_fraction': 0.9231910021785822, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5558035714285714
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:19:50,582] Trial 95 finished with value: 0.5701693113224804 and parameters: {'subsample': 0.8441489229564334, 'learning_rate': 0.010686672701851392, 'dropout_rate': 0.12427113599249004, 'n_estimators': 52, 'criterion': 'squared_error', 'ccp_alpha': 0.13095957774357525, 'min_weight_fraction_leaf': 0.208662917753807, 'max_features': 'auto', 'min_impurity_decrease': 0.04760435998517946, 'validation_fraction': 0.9999851977461973, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 03:19:57,181] Trial 96 finished with value: 0.7453020253507325 and parameters: {'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 96 with value: 0.7453020253507325.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:20:04,192] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8890132762537363, 'learning_rate': 0.016000147782265963, 'dropout_rate': 0.33412474584068513, 'n_estimators': 102, 'criterion': 'squared_error', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.3259150375155791, 'max_features': 1, 'min_impurity_decrease': 1.4118150039086305e-07, 'validation_fraction': 0.6283958723553874, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 96 with value: 0.7453020253507325.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:20:11,006] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8159517170308073, 'learning_rate': 0.008130653433584725, 'dropout_rate': 0.29126647641167647, 'n_estimators': 92, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.48045734256987266, 'max_features': 1, 'min_impurity_decrease': 1.030784288757872e-07, 'validation_fraction': 0.4049740702980035, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 18}. Best is trial 96 with value: 0.7453020253507325.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7083333333333334

[I 2024-04-14 03:20:11,919] A new study created in memory with name: no-name-7e2b38b2-38f7-479d-a4fd-30f955e00648

Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 03:20:11,869] Trial 99 finished with value: 0.7038145684617871 and parameters: {'subsample': 0.9036420036324795, 'learning_rate': 0.013060448266216875, 'dropout_rate': 0.37151966270502923, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.004512555601867606, 'min_weight_fraction_leaf': 0.43840629474088344, 'max_features': 1, 'min_impurity_decrease': 2.1305992007975229e-07, 'validation_fraction': 0.8858148503753556, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 16}. Best is trial 96 with value: 0.7453020253507325.


* Best trial for C-index:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.7453020253507325], datetime_start=datetime.datetime(2024, 4, 14, 3, 19, 50, 589594), datetime_complete=datetime.datetime(2024, 4, 14, 3, 19, 57, 178229), params={'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=96, value=None)


* Best Score for C-index:
 0.7453020253507325

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:20:55,618] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:21:20,149] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:21:43,473] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:22:20,932] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:22:36,742] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:22:40,471] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:23:19,250] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:23:31,772] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:23:33,257] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21302115522395498
Fold 2 IBS: 0.22130101345683229
Fold 3 IBS: 0.20356574496128135
Fold 4 IBS: 0.22373082985786685
Fold 5 IBS: 0.21796021556320513
[I 2024-04-14 03:25:25,959] Trial 9 finished with value: 0.21591579181262813 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21360017884301727
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.2041609124821885
Fold 4 IBS: 0.22443190447044095
Fold 5 IBS: 0.21803455300047256
[I 2024-04-14 03:28:35,960] Trial 10 finished with value: 0.2163415912252844 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 03:32:35,347] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21383968411387158
Fold 2 IBS: 0.22156451448592526
Fold 3 IBS: 0.20440536466519849
Fold 4 IBS: 0.22459255869133457
Fold 5 IBS: 0.2180987264506579
[I 2024-04-14 03:35:52,639] Trial 12 finished with value: 0.21650016968139757 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-14 03:37:27,613] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:40:17,403] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:42:48,544] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:44:12,630] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:47:19,739] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:49:00,957] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:49:18,085] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:52:14,005] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21394946003688667
Fold 2 IBS: 0.22157225472001127
Fold 3 IBS: 0.20452938396094716
Fold 4 IBS: 0.2247371055371081
Fold 5 IBS: 0.21809210037899657
[I 2024-04-14 03:55:24,537] Trial 21 finished with value: 0.21657606092679 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21275233971420443
Fold 2 IBS: 0.22141006773816166

Fold 3 IBS: 0.20334575604936503
Fold 4 IBS: 0.2231342747566171
Fold 5 IBS: 0.2179288192033457
[I 2024-04-14 03:59:02,323] Trial 22 finished with value: 0.21571425149233878 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 04:02:11,454] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:04:07,585] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:05:58,245] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:08:44,888] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:09:00,951] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:09:58,641] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:12:14,231] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 04:13:12,114] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.2136950219225832
Fold 2 IBS: 0.2215362190250608
Fold 3 IBS: 0.2044185685149852
Fold 4 IBS: 0.22472904052923362
Fold 5 IBS: 0.21803316635813036
[I 2024-04-14 04:16:05,276] Trial 31 finished with value: 0.21648240326999862 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.2130097385063184
Fold 2 IBS: 0.2214475600367709
Fold 3 IBS: 0.2035963921195872
Fold 4 IBS: 0.2235395355788286
Fold 5 IBS: 0.2179179888442139
[I 2024-04-14 04:19:01,371] Trial 32 finished with value: 0.21590224301714384 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:21:16,710] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 04:23:44,766] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:24:16,228] Trial 35 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:27:23,585] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:27:29,436] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:29:11,502] Trial 38 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 04:31:15,471] Trial 39 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 04:33:07,228] Trial 40 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.2133737249398968
Fold 2 IBS: 0.22149810300618933
Fold 3 IBS: 0.20392418223551953
Fold 4 IBS: 0.22395780771096238
Fold 5 IBS: 0.21807108026974395
[I 2024-04-14 04:36:00,660] Trial 41 finished with value: 0.21616497963246242 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21306226677867723
Fold 2 IBS: 0.22147749486211882
Fold 3 IBS: 0.20359544985689815
Fold 4 IBS: 0.22359166073512057
Fold 5 IBS: 0.21793202518042964
[I 2024-04-14 04:39:06,039] Trial 42 finished with value: 0.21593177948264888 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 04:42:24,830] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:44:50,965] Trial 44 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21378011659547358
Fold 2 IBS: 0.22145278135911364
Fold 3 IBS: 0.20436255304908924
Fold 4 IBS: 0.22448271516750193
Fold 5 IBS: 0.2180782304104917
[I 2024-04-14 04:47:10,878] Trial 45 finished with value: 0.21643127931633402 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:49:32,027] Trial 46 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 04:50:29,662] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 04:50:30,649] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 04:51:03,489] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 04:53:42,369] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21307969652873227
Fold 2 IBS: 0.22136886746037693
Fold 3 IBS: 0.203621499145842
Fold 4 IBS: 0.22363894843965748
Fold 5 IBS: 0.2179296735036949
[I 2024-04-14 04:56:38,950] Trial 51 finished with value: 0.2159277370156607 and parameters: {'subsample': 0.9914941239177857, 'learning_rate': 0.004643220694148276, 'dropout_rate': 0.14631717824203036, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3402340557764622, 'max_features': 'auto', 'min_impurity_decrease': 1.0669017189349294e-07, 'validation_fraction': 0.9630345477132441, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:59:44,222] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9520094582202872, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.13770242385086745, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.3347369286285409, 'max_features': 'auto', 'min_impurity_decrease': 1.8037977074379283e-07, 'validation_fraction': 0.9590095104838449, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21174315691146667
Fold 2 IBS: 0.22136281903923083
Fold 3 IBS: 0.2023927630992915
Fold 4 IBS: 0.2219411019366781
Fold 5 IBS: 0.21777624808878387
[I 2024-04-14 05:02:18,512] Trial 53 finished with value: 0.2150432178150902 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.1897783294507234, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.29880213170319914, 'max_features': 'auto', 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9964423942006735, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:04:49,903] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9951759842961662, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18641432881009587, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.29477236360216774, 'max_features': 'auto', 'min_impurity_decrease': 5.718312774105514e-07, 'validation_fraction': 0.9994814833877664, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:07:03,312] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9027683411994925, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.13472529918097312, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.36938177041618503, 'max_features': 'auto', 'min_impurity_decrease': 1.1016843774656315e-07, 'validation_fraction': 0.898549324711475, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 05:09:12,408] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8324789538052517, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.2217299975485909, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.33106978438275647, 'max_features': 'auto', 'min_impurity_decrease': 2.9232848365940597e-07, 'validation_fraction': 0.848519914422397, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:11:57,417] Trial 57 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8682011777139672, 'learning_rate': 0.031239466455985663, 'dropout_rate': 0.17322401428734607, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.2621422129699527, 'max_features': 'auto', 'min_impurity_decrease': 1.0096192890009967e-07, 'validation_fraction': 0.7861749990571634, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:15:14,742] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.10699123414946089, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 0.4695790047970817, 'min_weight_fraction_leaf': 0.4208497987584031, 'max_features': 1, 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.9248722131485942, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:17:21,817] Trial 59 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.0011610373238817896, 'dropout_rate': 0.2835746645760172, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.2971262516319784, 'max_features': 0.1, 'min_impurity_decrease': 5.673772193709774e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 05:19:06,903] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7689457925126264, 'learning_rate': 0.01938137369688937, 'dropout_rate': 0.23766423890937624, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2523293803401735, 'min_weight_fraction_leaf': 0.31705920833651274, 'max_features': 'auto', 'min_impurity_decrease': 1.09574587374673e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 05:21:41,283] Trial 61 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.005150255907863737, 'dropout_rate': 0.2646601381824477, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.24335809438237638, 'max_features': 'auto', 'min_impurity_decrease': 1.670100349442241e-07, 'validation_fraction': 0.9537438642784446, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21260039171576678
Fold 2 IBS: 0.22127522100059224
Fold 3 IBS: 0.2031294211565798
Fold 4 IBS: 0.22304748515979766
Fold 5 IBS: 0.21785716148870096
[I 2024-04-14 05:24:49,838] Trial 62 finished with value: 0.2155819361042875 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.009577802680942944, 'dropout_rate': 0.19576464123878148, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.2712475429741565, 'max_features': 'auto', 'min_impurity_decrease': 2.6031567647465433e-06, 'validation_fraction': 0.9664234509760701, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 05:27:57,438] Trial 63 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9678670791375591, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.19439757224953633, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.2664239609493312, 'max_features': 'auto', 'min_impurity_decrease': 4.0390121021586725e-07, 'validation_fraction': 0.8804884805212966, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21315225506544797
Fold 2 IBS: 0.22120521782494593
Fold 3 IBS: 0.20370415696975244
Fold 4 IBS: 0.22392954297429343
Fold 5 IBS: 0.21800569131579653
[I 2024-04-14 05:31:26,381] Trial 64 finished with value: 0.21599937283004728 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.008241701765086935, 'dropout_rate': 0.16204590972071856, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.042747030615862165, 'min_weight_fraction_leaf': 0.20867683262863126, 'max_features': 'log2', 'min_impurity_decrease': 1.1622062475943789e-06, 'validation_fraction': 0.9709487288557038, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 05:33:52,536] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8687566763675275, 'learning_rate': 0.010290863736545098, 'dropout_rate': 0.20090531278751475, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 1.1077392169505795, 'min_weight_fraction_leaf': 0.35267930800388836, 'max_features': 'auto', 'min_impurity_decrease': 2.9695254103704335e-06, 'validation_fraction': 0.9981673914604385, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 05:34:13,521] Trial 66 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9104313304151431, 'learning_rate': 0.014815622348446418, 'dropout_rate': 0.1415896279444537, 'n_estimators': 149, 'criterion': 'squared_error', 'ccp_alpha': 0.7060910424624821, 'min_weight_fraction_leaf': 0.2796836959018326, 'max_features': 'auto', 'min_impurity_decrease': 5.127880425748818e-06, 'validation_fraction': 0.916501041728546, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:36:35,769] Trial 67 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.802369464636257, 'learning_rate': 0.00417552385002208, 'dropout_rate': 0.3370707390697732, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.22284347226729986, 'max_features': 'sqrt', 'min_impurity_decrease': 7.319926345244562e-07, 'validation_fraction': 0.8373361504171383, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 14}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:39:33,607] Trial 68 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9271983184882995, 'learning_rate': 0.026761786505961737, 'dropout_rate': 0.23198968531289843, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997767788709036, 'min_weight_fraction_leaf': 0.3246047057302614, 'max_features': 'auto', 'min_impurity_decrease': 2.8105707733985375e-07, 'validation_fraction': 0.6390547838628696, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:41:48,919] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9669065339055751, 'learning_rate': 0.010765506871731714, 'dropout_rate': 0.30527953045505896, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': 'auto', 'min_impurity_decrease': 6.006710681053735e-05, 'validation_fraction': 0.8784198437522095, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 05:43:07,517] Trial 70 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.041826568167709126, 'dropout_rate': 0.5905404972480945, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.3744309428528772, 'max_features': None, 'min_impurity_decrease': 1.5635679037041744e-07, 'validation_fraction': 0.9186076475421031, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21310093398309657
Fold 2 IBS: 0.22107852954082238
Fold 3 IBS: 0.20363684344049715
Fold 4 IBS: 0.2235062321376155
Fold 5 IBS: 0.2179952952989321
[I 2024-04-14 05:46:30,290] Trial 71 finished with value: 0.21586356688019276 and parameters: {'subsample': 0.9998892193300933, 'learning_rate': 0.008268552307118088, 'dropout_rate': 0.18133086892644865, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.1936286226601749, 'max_features': 'log2', 'min_impurity_decrease': 9.627538760330365e-07, 'validation_fraction': 0.9695063743987746, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.2124258387603463
Fold 2 IBS: 0.22057958449066262
Fold 3 IBS: 0.20279757841484652
Fold 4 IBS: 0.222180058336135
Fold 5 IBS: 0.21771098701395403
[I 2024-04-14 05:49:57,376] Trial 72 finished with value: 0.21513880940318889 and parameters: {'subsample': 0.9765713621264592, 'learning_rate': 0.00878714781905863, 'dropout_rate': 0.12511582109542432, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.004831359506118816, 'min_weight_fraction_leaf': 0.1603532575763104, 'max_features': 'log2', 'min_impurity_decrease': 4.6121007580567444e-07, 'validation_fraction': 0.9726077921006634, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560958
[I 2024-04-14 05:53:03,711] Trial 73 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9999531614476969, 'learning_rate': 0.017515788008347112, 'dropout_rate': 0.12067593932125548, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.1608125340894365, 'max_features': 'log2', 'min_impurity_decrease': 4.330904032345818e-07, 'validation_fraction': 0.9762008597583516, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 05:56:19,993] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9378736061625563, 'learning_rate': 0.00962248608121305, 'dropout_rate': 0.17315149200510316, 'n_estimators': 491, 'criterion': 'squared_error', 'ccp_alpha': 0.370371857241124, 'min_weight_fraction_leaf': 0.11427286298314121, 'max_features': 'log2', 'min_impurity_decrease': 7.393622885050152e-07, 'validation_fraction': 0.9760588067950509, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:59:13,273] Trial 75 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8548930681972974, 'learning_rate': 0.05554512018944124, 'dropout_rate': 0.14951765413144097, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.3275069627126754, 'min_weight_fraction_leaf': 0.12844710013372065, 'max_features': 'log2', 'min_impurity_decrease': 1.0058881333640878e-06, 'validation_fraction': 0.9013416300485078, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-14 06:02:31,388] Trial 76 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9721782395774373, 'learning_rate': 0.003194443723182592, 'dropout_rate': 0.12011548645109148, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'log2', 'min_impurity_decrease': 1.507827148373076e-06, 'validation_fraction': 0.9325305665153546, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:05:46,107] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8921532985730489, 'learning_rate': 0.021931279910218017, 'dropout_rate': 0.19284931428290142, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.5905545096948588, 'min_weight_fraction_leaf': 0.07057220045251793, 'max_features': 'log2', 'min_impurity_decrease': 1.637559261311236e-05, 'validation_fraction': 0.8150762480319586, 'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 06:08:23,261] Trial 78 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7443996478445325, 'learning_rate': 0.0869328686638194, 'dropout_rate': 0.25883194688905886, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.9915392376256854, 'min_weight_fraction_leaf': 0.18968885272282524, 'max_features': 'log2', 'min_impurity_decrease': 3.9150597642462115e-06, 'validation_fraction': 0.4642012910381656, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-14 06:10:39,498] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9257604896060708, 'learning_rate': 0.01335084153769065, 'dropout_rate': 0.10072101837872541, 'n_estimators': 393, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28871198232416817, 'min_weight_fraction_leaf': 0.17483536292771176, 'max_features': 'log2', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9982218331650979, 'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 06:11:56,885] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.977148848015456, 'learning_rate': 0.004307663599041434, 'dropout_rate': 0.15920080431792163, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.20378735965998926, 'max_features': 1, 'min_impurity_decrease': 1.424247746508587e-06, 'validation_fraction': 0.8670066304726413, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21299867857890398
Fold 2 IBS: 0.2214477278201705
Fold 3 IBS: 0.20356620117857893
Fold 4 IBS: 0.22350168421901248
Fold 5 IBS: 0.21792379994243102
[I 2024-04-14 06:14:54,931] Trial 81 finished with value: 0.2158876183478194 and parameters: {'subsample': 0.9579178853393634, 'learning_rate': 0.007273589951884828, 'dropout_rate': 0.2054590932290375, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.02521700237735763, 'min_weight_fraction_leaf': 0.23721821844476393, 'max_features': 'auto', 'min_impurity_decrease': 2.628308399801263e-07, 'validation_fraction': 0.945876154428725, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21281996790006147
Fold 2 IBS: 0.22144914962179446
Fold 3 IBS: 0.2034201419570034
Fold 4 IBS: 0.22330541406123097
Fold 5 IBS: 0.21789799579435803
[I 2024-04-14 06:18:07,056] Trial 82 finished with value: 0.21577853386688967 and parameters: {'subsample': 0.9374850920793417, 'learning_rate': 0.009537962827339893, 'dropout_rate': 0.2311360143359113, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.01786403260693046, 'min_weight_fraction_leaf': 0.30128352038824946, 'max_features': 'auto', 'min_impurity_decrease': 2.672883759599648e-07, 'validation_fraction': 0.9419164447228301, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 06:21:07,574] Trial 83 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.6438413298708685, 'learning_rate': 0.008698584299413689, 'dropout_rate': 0.2878607631400676, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.42714757621714333, 'min_weight_fraction_leaf': 0.2701739605759479, 'max_features': 0.1, 'min_impurity_decrease': 4.793545557946714e-07, 'validation_fraction': 0.9339252824355873, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 06:24:02,753] Trial 84 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.411624430892823, 'learning_rate': 0.016064279530571223, 'dropout_rate': 0.2326295808813899, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.7147702528804116, 'min_weight_fraction_leaf': 0.23638615893438736, 'max_features': 'auto', 'min_impurity_decrease': 3.019646046469693e-07, 'validation_fraction': 0.8979947940782089, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 06:26:39,839] Trial 85 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9376269876567488, 'learning_rate': 0.019091747704160993, 'dropout_rate': 0.20706945781506403, 'n_estimators': 439, 'criterion': 'squared_error', 'ccp_alpha': 0.16619718561211044, 'min_weight_fraction_leaf': 0.15561996067062303, 'max_features': 'auto', 'min_impurity_decrease': 2.429626863306918e-07, 'validation_fraction': 0.9731668294064385, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:29:51,702] Trial 86 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8785484469699407, 'learning_rate': 0.012070502053282707, 'dropout_rate': 0.2505427438802027, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.1270526375680832, 'min_weight_fraction_leaf': 0.25781248698190756, 'max_features': 'sqrt', 'min_impurity_decrease': 2.2713997001011194e-06, 'validation_fraction': 0.943859242495053, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 06:32:04,703] Trial 87 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9090955901211109, 'learning_rate': 0.006929208749359209, 'dropout_rate': 0.49308788025511585, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.32252019630070927, 'min_weight_fraction_leaf': 0.3051832272732572, 'max_features': 'log2', 'min_impurity_decrease': 7.049454515025671e-07, 'validation_fraction': 0.37837273453407844, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:35:03,299] Trial 88 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9447987915285996, 'learning_rate': 0.014159070275535094, 'dropout_rate': 0.18102387516231752, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.5935000311483954, 'min_weight_fraction_leaf': 0.2151508441811604, 'max_features': 'auto', 'min_impurity_decrease': 3.72786238165322e-07, 'validation_fraction': 0.898328514849679, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21292314886383587
Fold 2 IBS: 0.2213935582997429
Fold 3 IBS: 0.20349492943164285
Fold 4 IBS: 0.2234443788901035
Fold 5 IBS: 0.2178743294294726
[I 2024-04-14 06:37:14,306] Trial 89 finished with value: 0.21582606898295956 and parameters: {'subsample': 0.9777744983689288, 'learning_rate': 0.01038357183462239, 'dropout_rate': 0.27697802684175754, 'n_estimators': 425, 'criterion': 'squared_error', 'ccp_alpha': 0.019074305728520667, 'min_weight_fraction_leaf': 0.2917659918820059, 'max_features': 'auto', 'min_impurity_decrease': 1.3598537758171917e-07, 'validation_fraction': 0.855835665987138, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:38:00,790] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9728383671704387, 'learning_rate': 0.009918951595706415, 'dropout_rate': 0.8458602043820649, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.8331973858915148, 'min_weight_fraction_leaf': 0.2921200274675525, 'max_features': 'auto', 'min_impurity_decrease': 1.4263141271201017e-07, 'validation_fraction': 0.6746483744961582, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21336618881179586
Fold 2 IBS: 0.22114294232267198
Fold 3 IBS: 0.20384999569236736
Fold 4 IBS: 0.22375343637403386
Fold 5 IBS: 0.21796174726134912
[I 2024-04-14 06:40:15,917] Trial 91 finished with value: 0.21601486209244367 and parameters: {'subsample': 0.2845120808216636, 'learning_rate': 0.007013602341022412, 'dropout_rate': 0.2673714840258141, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.03785557112751456, 'min_weight_fraction_leaf': 0.28289624505615074, 'max_features': 'auto', 'min_impurity_decrease': 2.167221721970957e-07, 'validation_fraction': 0.8389190675336428, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 06:41:10,790] Trial 92 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5328328014893517, 'learning_rate': 0.012214946715626797, 'dropout_rate': 0.21822342387423224, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 0.2716052866202, 'min_weight_fraction_leaf': 0.2516221825059295, 'max_features': 'auto', 'min_impurity_decrease': 5.164764561896499e-07, 'validation_fraction': 0.9118535684017283, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:43:38,270] Trial 93 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9215121808289675, 'learning_rate': 0.023968389847749173, 'dropout_rate': 0.3096195311954267, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.526845938693122, 'min_weight_fraction_leaf': 0.23408949316338243, 'max_features': 'auto', 'min_impurity_decrease': 3.3639036073651944e-07, 'validation_fraction': 0.9394031242668214, 'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:45:28,349] Trial 94 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9794737431495151, 'learning_rate': 0.002207391632430766, 'dropout_rate': 0.355864908714743, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.25602285176947265, 'min_weight_fraction_leaf': 0.1982598024964269, 'max_features': 'auto', 'min_impurity_decrease': 7.85301346539494e-07, 'validation_fraction': 0.8716461599738365, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:47:19,647] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8243603473818633, 'learning_rate': 0.016754070407166113, 'dropout_rate': 0.18244406164714, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 0.969239817362121, 'min_weight_fraction_leaf': 0.27320139306393876, 'max_features': None, 'min_impurity_decrease': 1.4323978100998562e-07, 'validation_fraction': 0.7967240220364479, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:49:37,759] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9567077577297926, 'learning_rate': 0.009321682904042736, 'dropout_rate': 0.24495589575382673, 'n_estimators': 489, 'criterion': 'friedman_mse', 'ccp_alpha': 5.08611115752829, 'min_weight_fraction_leaf': 0.30649414543812215, 'max_features': 'auto', 'min_impurity_decrease': 1.2053286940776505e-06, 'validation_fraction': 0.7556909999934059, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 06:51:52,728] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8987436119584659, 'learning_rate': 0.0203626546956988, 'dropout_rate': 0.12954890528084062, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 1.5784834259170004, 'min_weight_fraction_leaf': 0.2550731647118252, 'max_features': 'auto', 'min_impurity_decrease': 1.890730180714205e-06, 'validation_fraction': 0.9772741387306807, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 06:53:30,421] Trial 98 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9426449416232375, 'learning_rate': 0.005258427870498378, 'dropout_rate': 0.29094318599258845, 'n_estimators': 452, 'criterion': 'squared_error', 'ccp_alpha': 0.5297744472721807, 'min_weight_fraction_leaf': 0.2938783217761457, 'max_features': 1, 'min_impurity_decrease': 2.1824147145190313e-07, 'validation_fraction': 0.5403544212495923, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21192565389705484
Fold 2 IBS: 0.22123776935159062

Fold 3 IBS: 0.20237857642828805
Fold 4 IBS: 0.22105646622231043
Fold 5 IBS: 0.21749535106188492
[I 2024-04-14 06:54:50,186] Trial 99 finished with value: 0.21481876339222578 and parameters: {'subsample': 0.8569271041566342, 'learning_rate': 0.01377474153403631, 'dropout_rate': 0.2044520049398774, 'n_estimators': 378, 'criterion': 'squared_error', 'ccp_alpha': 0.004422201299274769, 'min_weight_fraction_leaf': 0.13940114558509004, 'max_features': 'auto', 'min_impurity_decrease': 0.00015837847703956763, 'validation_fraction': 0.9580200141092102, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 99 with value: 0.21481876339222578.


* Best trial for IBS:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.21481876339222578], datetime_start=datetime.datetime(2024, 4, 14, 6, 53, 30, 434188), datetime_complete=datetime.datetime(2024, 4, 14, 6, 54, 50, 184938), params={'subsample': 0.8569271041566342, 'learning_rate': 0.01377474153403631, 'dropout_rate': 0.2044520049398774, 'n_estimators': 378, 'criterion': 'squared_error', 'ccp_alpha': 0.004422201299274769, 'min_weight_fraction_leaf': 0.13940114558509004, 'max_features': 'auto', 'min_impurity_decrease': 0.00015837847703956763, 'validation_fraction': 0.9580200141092102, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=99, value=None)


* Best Score for IBS:
 0.21481876339222578

In [113]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [114]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.745
train_ibs:  0.215

#### Test

In [115]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [116]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03063070291051248,
                                 criterion='squared_error',
                                 dropout_rate=0.2576884847115747,
                                 learning_rate=0.007359366951045268,
                                 max_depth=16, max_features=1,
                                 max_leaf_nodes=16,
                                 min_impurity_decrease=1.3903906488794697e-07,
                                 min_samples_leaf=14, min_samples_split=20,
                                 min_weight_fraction_leaf=0.38180626899357545,
                                 n_estimators=96, random_state=123,
                                 subsample=0.8938290428827321,
                                 validation_fraction=0.9577535215137098)

C-index score: 0.603

GradientBoostingSurvivalAnalysis(ccp_alpha=0.004422201299274769,
                                 criterion='squared_error',
                                 dropout_rate=0.2044520049398774,
                                 learning_rate=0.01377474153403631, max_depth=2,
                                 max_features='auto', max_leaf_nodes=17,
                                 min_impurity_decrease=0.00015837847703956763,
                                 min_samples_leaf=13, min_samples_split=13,
                                 min_weight_fraction_leaf=0.13940114558509004,
                                 n_estimators=378, random_state=123,
                                 subsample=0.8569271041566342,
                                 validation_fraction=0.9580200141092102)

IBS: 0.22

In [117]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [118]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [119]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 06:55:08,165] A new study created in memory with name: no-name-495c7a63-0fe8-440c-b676-092766ee119f

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 06:55:09,890] Trial 0 finished with value: 0.6977253889205401 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6977253889205401.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 06:55:22,202] Trial 1 finished with value: 0.7034787818269984 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.7034787818269984.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5892018779342723
[I 2024-04-14 06:55:24,678] Trial 2 finished with value: 0.7153490626059659 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.7153490626059659.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 06:55:28,126] Trial 3 finished with value: 0.7223120302514108 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.7223120302514108.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 06:55:33,284] Trial 4 finished with value: 0.7238431644720645 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.7238431644720645.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 06:55:39,555] Trial 5 finished with value: 0.7109786332562491 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.7238431644720645.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 06:55:42,279] Trial 6 finished with value: 0.6514945071044511 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.7238431644720645.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 06:55:42,866] Trial 7 finished with value: 0.7239354741231976 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.7239354741231976.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5892018779342723
[I 2024-04-14 06:55:46,289] Trial 8 finished with value: 0.7131543210729892 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.7239354741231976.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 06:55:56,933] Trial 9 finished with value: 0.7140932882091393 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.7239354741231976.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 06:55:57,487] Trial 10 finished with value: 0.63080934443503 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.7239354741231976.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 06:56:06,286] Trial 11 finished with value: 0.7357141900910189 and parameters: {'subsample': 0.1913192016083392, 'dropout_rate': 0.10580803679784617, 'n_estimators': 350, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.7357141900910189.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 06:56:12,995] Trial 12 finished with value: 0.7325506495163585 and parameters: {'subsample': 0.11615582976955166, 'dropout_rate': 0.7007608116967414, 'n_estimators': 331, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.7357141900910189.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 06:56:19,906] Trial 13 finished with value: 0.731758014920907 and parameters: {'subsample': 0.10945381685168351, 'dropout_rate': 0.6867275669911717, 'n_estimators': 339, 'learning_rate': 0.09914998942829482}. Best is trial 11 with value: 0.7357141900910189.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 06:56:29,429] Trial 14 finished with value: 0.7368189957793195 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.11481632908368056, 'n_estimators': 368, 'learning_rate': 0.09979016703322471}. Best is trial 14 with value: 0.7368189957793195.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 06:56:39,592] Trial 15 finished with value: 0.7303431307854347 and parameters: {'subsample': 0.2573538556854503, 'dropout_rate': 0.10003457463463547, 'n_estimators': 383, 'learning_rate': 0.08616677729964022}. Best is trial 14 with value: 0.7368189957793195.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 06:56:50,391] Trial 16 finished with value: 0.7265868996101659 and parameters: {'subsample': 0.25470623831733574, 'dropout_rate': 0.27661215111082393, 'n_estimators': 422, 'learning_rate': 0.08463638125592773}. Best is trial 14 with value: 0.7368189957793195.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 06:56:57,172] Trial 17 finished with value: 0.724101223010801 and parameters: {'subsample': 0.35034822789543474, 'dropout_rate': 0.22654987460299786, 'n_estimators': 274, 'learning_rate': 0.08749976591807801}. Best is trial 14 with value: 0.7368189957793195.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 06:57:10,122] Trial 18 finished with value: 0.7367263234975185 and parameters: {'subsample': 0.17338914531900965, 'dropout_rate': 0.10279957341799587, 'n_estimators': 430, 'learning_rate': 0.09062397105934869}. Best is trial 14 with value: 0.7368189957793195.

Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 06:57:21,610] Trial 19 finished with value: 0.7204404397458104 and parameters: {'subsample': 0.38793667853472646, 'dropout_rate': 0.19484380744875768, 'n_estimators': 431, 'learning_rate': 0.07766040270665416}. Best is trial 14 with value: 0.7368189957793195.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 06:57:32,204] Trial 20 finished with value: 0.7272820872866885 and parameters: {'subsample': 0.179916923106687, 'dropout_rate': 0.323440617921801, 'n_estimators': 420, 'learning_rate': 0.09611961349165574}. Best is trial 14 with value: 0.7368189957793195.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 06:57:39,031] Trial 21 finished with value: 0.7338967345556677 and parameters: {'subsample': 0.19858154566104463, 'dropout_rate': 0.12395834975058428, 'n_estimators': 298, 'learning_rate': 0.08901916938853777}. Best is trial 14 with value: 0.7368189957793195.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 06:57:49,643] Trial 22 finished with value: 0.7359509229387472 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.10643415732680922, 'n_estimators': 396, 'learning_rate': 0.09968716719340712}. Best is trial 14 with value: 0.7368189957793195.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 06:58:04,016] Trial 23 finished with value: 0.7363381208412958 and parameters: {'subsample': 0.15413466511556917, 'dropout_rate': 0.21660809046095283, 'n_estimators': 457, 'learning_rate': 0.09933817834131231}. Best is trial 14 with value: 0.7368189957793195.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 06:58:21,542] Trial 24 finished with value: 0.7238431644720645 and parameters: {'subsample': 0.30544113046891047, 'dropout_rate': 0.20371878824956227, 'n_estimators': 454, 'learning_rate': 0.08005513521016759}. Best is trial 14 with value: 0.7368189957793195.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 06:58:37,394] Trial 25 finished with value: 0.7252676427140654 and parameters: {'subsample': 0.1790685473632615, 'dropout_rate': 0.3125521697439868, 'n_estimators': 497, 'learning_rate': 0.06561616332479822}. Best is trial 14 with value: 0.7368189957793195.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 06:58:50,735] Trial 26 finished with value: 0.7213794068819606 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.18828718249814755, 'n_estimators': 445, 'learning_rate': 0.09159744779453571}. Best is trial 14 with value: 0.7368189957793195.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 06:59:01,829] Trial 27 finished with value: 0.7171808868849733 and parameters: {'subsample': 0.6112509825166255, 'dropout_rate': 0.40559980290717995, 'n_estimators': 397, 'learning_rate': 0.08120908697251955}. Best is trial 14 with value: 0.7368189957793195.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 06:59:09,447] Trial 28 finished with value: 0.7184843404046654 and parameters: {'subsample': 0.2938296716842279, 'dropout_rate': 0.26416975802050124, 'n_estimators': 322, 'learning_rate': 0.04170498496430571}. Best is trial 14 with value: 0.7368189957793195.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5892018779342723
[I 2024-04-14 06:59:24,471] Trial 29 finished with value: 0.7056099511961544 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.16679503727256115, 'n_estimators': 460, 'learning_rate': 0.06046208382653473}. Best is trial 14 with value: 0.7368189957793195.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 06:59:26,073] Trial 30 finished with value: 0.7291381025497283 and parameters: {'subsample': 0.15827114191159963, 'dropout_rate': 0.3577780272974884, 'n_estimators': 93, 'learning_rate': 0.09309734904742954}. Best is trial 14 with value: 0.7368189957793195.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 06:59:37,002] Trial 31 finished with value: 0.7392556970923672 and parameters: {'subsample': 0.11064620189433105, 'dropout_rate': 0.15342904765910464, 'n_estimators': 388, 'learning_rate': 0.09783639957138997}. Best is trial 31 with value: 0.7392556970923672.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 06:59:47,443] Trial 32 finished with value: 0.7308334165284129 and parameters: {'subsample': 0.22410329223330416, 'dropout_rate': 0.20572401274937915, 'n_estimators': 377, 'learning_rate': 0.09969780723284132}. Best is trial 31 with value: 0.7392556970923672.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 06:59:59,007] Trial 33 finished with value: 0.7384722939727764 and parameters: {'subsample': 0.14640475436912043, 'dropout_rate': 0.1507092326492242, 'n_estimators': 413, 'learning_rate': 0.09226059022887965}. Best is trial 31 with value: 0.7392556970923672.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:00:08,781] Trial 34 finished with value: 0.72550151026877 and parameters: {'subsample': 0.31478192981222664, 'dropout_rate': 0.15397827471979936, 'n_estimators': 399, 'learning_rate': 0.07454136223949474}. Best is trial 31 with value: 0.7392556970923672.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:00:13,142] Trial 35 finished with value: 0.728104050133968 and parameters: {'subsample': 0.13601165715515998, 'dropout_rate': 0.9994277775666256, 'n_estimators': 305, 'learning_rate': 0.06729526522019186}. Best is trial 31 with value: 0.7392556970923672.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:00:17,089] Trial 36 finished with value: 0.7265379243238487 and parameters: {'subsample': 0.22911289122229545, 'dropout_rate': 0.4530898888808027, 'n_estimators': 245, 'learning_rate': 0.08050749814976943}. Best is trial 31 with value: 0.7392556970923672.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:00:24,901] Trial 37 finished with value: 0.7273576151963564 and parameters: {'subsample': 0.23336829927913705, 'dropout_rate': 0.2952229459608166, 'n_estimators': 360, 'learning_rate': 0.09223298883775308}. Best is trial 31 with value: 0.7392556970923672.

Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 07:00:38,462] Trial 38 finished with value: 0.7392579690671386 and parameters: {'subsample': 0.1004921614604077, 'dropout_rate': 0.15002677709758214, 'n_estimators': 487, 'learning_rate': 0.07111278775588788}. Best is trial 38 with value: 0.7392579690671386.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 07:00:49,694] Trial 39 finished with value: 0.7336093452113662 and parameters: {'subsample': 0.10773591528998765, 'dropout_rate': 0.5393862022989122, 'n_estimators': 483, 'learning_rate': 0.06892741183938003}. Best is trial 38 with value: 0.7392579690671386.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.57981220657277
[I 2024-04-14 07:01:03,329] Trial 40 finished with value: 0.7139024372208567 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.2544582949021301, 'n_estimators': 477, 'learning_rate': 0.07255507912086517}. Best is trial 38 with value: 0.7392579690671386.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 07:01:14,196] Trial 41 finished with value: 0.7374699828066528 and parameters: {'subsample': 0.14194354159565575, 'dropout_rate': 0.1501352513897693, 'n_estimators': 422, 'learning_rate': 0.08234434575799052}. Best is trial 38 with value: 0.7392579690671386.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 07:01:23,953] Trial 42 finished with value: 0.7384233186864593 and parameters: {'subsample': 0.15763741513918444, 'dropout_rate': 0.15087385776783127, 'n_estimators': 414, 'learning_rate': 0.08346628188440174}. Best is trial 38 with value: 0.7392579690671386.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:01:31,981] Trial 43 finished with value: 0.710001581103762 and parameters: {'subsample': 0.4366974432637313, 'dropout_rate': 0.6176715828207425, 'n_estimators': 413, 'learning_rate': 0.0749828252775806}. Best is trial 38 with value: 0.7392579690671386.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 07:01:42,483] Trial 44 finished with value: 0.7317406424149263 and parameters: {'subsample': 0.20687829540668393, 'dropout_rate': 0.15714686923807566, 'n_estimators': 437, 'learning_rate': 0.08219953849099317}. Best is trial 38 with value: 0.7392579690671386.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 07:01:54,809] Trial 45 finished with value: 0.7262722258549605 and parameters: {'subsample': 0.2792935667325966, 'dropout_rate': 0.24331740964347165, 'n_estimators': 475, 'learning_rate': 0.08480097149357464}. Best is trial 38 with value: 0.7392579690671386.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 07:02:08,468] Trial 46 finished with value: 0.7273138285363254 and parameters: {'subsample': 0.14733538385910072, 'dropout_rate': 0.35470237229730606, 'n_estimators': 493, 'learning_rate': 0.024992652172925307}. Best is trial 38 with value: 0.7392579690671386.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5845070422535211
[I 2024-04-14 07:02:10,163] Trial 47 finished with value: 0.7046709840600043 and parameters: {'subsample': 0.7961983953812717, 'dropout_rate': 0.16311184556872857, 'n_estimators': 124, 'learning_rate': 0.06075496741689693}. Best is trial 38 with value: 0.7392579690671386.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 07:02:19,571] Trial 48 finished with value: 0.7287866887463912 and parameters: {'subsample': 0.34144042025991617, 'dropout_rate': 0.13548266989675564, 'n_estimators': 405, 'learning_rate': 0.09470650104023656}. Best is trial 38 with value: 0.7392579690671386.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 07:02:26,782] Trial 49 finished with value: 0.7289308389768653 and parameters: {'subsample': 0.14597541430985023, 'dropout_rate': 0.23852613883547508, 'n_estimators': 348, 'learning_rate': 0.00524351186486742}. Best is trial 38 with value: 0.7392579690671386.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:02:35,085] Trial 50 finished with value: 0.7290844422908307 and parameters: {'subsample': 0.2637037889296351, 'dropout_rate': 0.18212774316848332, 'n_estimators': 380, 'learning_rate': 0.07091191895753794}. Best is trial 38 with value: 0.7392579690671386.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 07:02:43,390] Trial 51 finished with value: 0.7410604650943183 and parameters: {'subsample': 0.10877157891355023, 'dropout_rate': 0.13472564587766026, 'n_estimators': 376, 'learning_rate': 0.0867883907233602}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 07:02:52,215] Trial 52 finished with value: 0.7316772983849531 and parameters: {'subsample': 0.12801991613896832, 'dropout_rate': 0.7442400087777848, 'n_estimators': 443, 'learning_rate': 0.084987099665577}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 07:03:00,356] Trial 53 finished with value: 0.7326796095510766 and parameters: {'subsample': 0.2015645198917214, 'dropout_rate': 0.14305216156966635, 'n_estimators': 326, 'learning_rate': 0.07766159645743378}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:03:08,408] Trial 54 finished with value: 0.7316455571353162 and parameters: {'subsample': 0.16788044888145837, 'dropout_rate': 0.286749356789714, 'n_estimators': 368, 'learning_rate': 0.09458711655652817}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 07:03:20,039] Trial 55 finished with value: 0.7383628399495099 and parameters: {'subsample': 0.1100561249826089, 'dropout_rate': 0.14313561042877954, 'n_estimators': 462, 'learning_rate': 0.08410741033483923}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 07:03:29,723] Trial 56 finished with value: 0.7327822450962913 and parameters: {'subsample': 0.11006703955833959, 'dropout_rate': 0.7925598471459256, 'n_estimators': 475, 'learning_rate': 0.08854535742748029}. Best is trial 51 with value: 0.7410604650943183.

Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 07:03:41,353] Trial 57 finished with value: 0.738360426951701 and parameters: {'subsample': 0.1014901283219039, 'dropout_rate': 0.2235949596375214, 'n_estimators': 461, 'learning_rate': 0.0881587620581028}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 07:03:55,603] Trial 58 finished with value: 0.7263212011412776 and parameters: {'subsample': 0.24320654336182101, 'dropout_rate': 0.13169727370993536, 'n_estimators': 498, 'learning_rate': 0.045315493692864625}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 07:04:07,565] Trial 59 finished with value: 0.7319769229674398 and parameters: {'subsample': 0.1900794906966089, 'dropout_rate': 0.1869703436333725, 'n_estimators': 435, 'learning_rate': 0.09081872354240247}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:04:15,885] Trial 60 finished with value: 0.686400061734608 and parameters: {'subsample': 0.9718433307655755, 'dropout_rate': 0.32093111789316053, 'n_estimators': 388, 'learning_rate': 0.07862160019848999}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 07:04:28,153] Trial 61 finished with value: 0.7384308689520639 and parameters: {'subsample': 0.12882195706257474, 'dropout_rate': 0.21187670493262437, 'n_estimators': 464, 'learning_rate': 0.08758752344722985}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 07:04:38,388] Trial 62 finished with value: 0.73777519695215 and parameters: {'subsample': 0.16369022366144187, 'dropout_rate': 0.10133300137412488, 'n_estimators': 414, 'learning_rate': 0.09607579314517165}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 07:04:49,742] Trial 63 finished with value: 0.7365115096590509 and parameters: {'subsample': 0.12981868141271946, 'dropout_rate': 0.2161238244173747, 'n_estimators': 460, 'learning_rate': 0.08488134506373123}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 07:05:02,826] Trial 64 finished with value: 0.7309209515424187 and parameters: {'subsample': 0.20674713796490957, 'dropout_rate': 0.17894367570301797, 'n_estimators': 445, 'learning_rate': 0.06370517497251836}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 07:05:13,044] Trial 65 finished with value: 0.7346698631396674 and parameters: {'subsample': 0.17437708919233869, 'dropout_rate': 0.13283899373874214, 'n_estimators': 423, 'learning_rate': 0.055286035079886685}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 07:05:19,916] Trial 66 finished with value: 0.7366017689430429 and parameters: {'subsample': 0.10061392809244056, 'dropout_rate': 0.2678407014821981, 'n_estimators': 353, 'learning_rate': 0.08631265557653064}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 07:05:30,370] Trial 67 finished with value: 0.7392747508086039 and parameters: {'subsample': 0.13867857765824754, 'dropout_rate': 0.19821734950227032, 'n_estimators': 468, 'learning_rate': 0.09718879653823487}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 07:05:33,896] Trial 68 finished with value: 0.7299405593855559 and parameters: {'subsample': 0.2136752721808981, 'dropout_rate': 0.19368508991907174, 'n_estimators': 234, 'learning_rate': 0.09248683985172498}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 07:05:36,116] Trial 69 finished with value: 0.7300747977111071 and parameters: {'subsample': 0.14770159834920188, 'dropout_rate': 0.2171136462939891, 'n_estimators': 165, 'learning_rate': 0.09657505225482878}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:05:40,128] Trial 70 finished with value: 0.7289698509997687 and parameters: {'subsample': 0.1845699557749264, 'dropout_rate': 0.3475400251481891, 'n_estimators': 277, 'learning_rate': 0.09618689118249349}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 07:05:49,141] Trial 71 finished with value: 0.7339774510916216 and parameters: {'subsample': 0.13276359767315843, 'dropout_rate': 0.126177095583756, 'n_estimators': 453, 'learning_rate': 0.08965899902356336}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:06:00,258] Trial 72 finished with value: 0.7250096553962191 and parameters: {'subsample': 0.6645973739616917, 'dropout_rate': 0.16690115404695816, 'n_estimators': 481, 'learning_rate': 0.0766981265100805}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 07:06:10,003] Trial 73 finished with value: 0.7402654175010577 and parameters: {'subsample': 0.12714509943041594, 'dropout_rate': 0.10793448746897147, 'n_estimators': 463, 'learning_rate': 0.08698337152585485}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:06:17,935] Trial 74 finished with value: 0.728104050133968 and parameters: {'subsample': 0.24371021363397027, 'dropout_rate': 0.23256717429451723, 'n_estimators': 437, 'learning_rate': 0.0915729943471081}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 07:06:25,617] Trial 75 finished with value: 0.7377942506683868 and parameters: {'subsample': 0.17056204626421365, 'dropout_rate': 0.10312737577336992, 'n_estimators': 410, 'learning_rate': 0.08764659206767361}. Best is trial 51 with value: 0.7410604650943183.

Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 07:06:32,469] Trial 76 finished with value: 0.7375552458458869 and parameters: {'subsample': 0.12790172867011254, 'dropout_rate': 0.1947593690298242, 'n_estimators': 392, 'learning_rate': 0.0969953909619116}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 07:06:42,802] Trial 77 finished with value: 0.7347430294100168 and parameters: {'subsample': 0.15423300180834287, 'dropout_rate': 0.16483077075231417, 'n_estimators': 499, 'learning_rate': 0.08206359367138327}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:06:51,902] Trial 78 finished with value: 0.727989458842906 and parameters: {'subsample': 0.21999534819959804, 'dropout_rate': 0.2539855149337225, 'n_estimators': 468, 'learning_rate': 0.09351224375763018}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 07:07:03,462] Trial 79 finished with value: 0.7322919593533129 and parameters: {'subsample': 0.18881665826930866, 'dropout_rate': 0.11969883784225349, 'n_estimators': 486, 'learning_rate': 0.0983514933405076}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:07:10,560] Trial 80 finished with value: 0.7256450671809915 and parameters: {'subsample': 0.27266264130024365, 'dropout_rate': 0.2991854672986574, 'n_estimators': 427, 'learning_rate': 0.08987459960526713}. Best is trial 51 with value: 0.7410604650943183.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 07:07:18,628] Trial 81 finished with value: 0.7421283922651867 and parameters: {'subsample': 0.12062136787385529, 'dropout_rate': 0.1337822012086785, 'n_estimators': 453, 'learning_rate': 0.08418081739857108}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 07:07:25,194] Trial 82 finished with value: 0.7334820663869042 and parameters: {'subsample': 0.13237878784188012, 'dropout_rate': 0.5095499192980961, 'n_estimators': 447, 'learning_rate': 0.08606354944780388}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:07:30,222] Trial 83 finished with value: 0.714066231932083 and parameters: {'subsample': 0.5178718065036161, 'dropout_rate': 0.6202793429199533, 'n_estimators': 406, 'learning_rate': 0.08326951711100943}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 07:07:35,475] Trial 84 finished with value: 0.7392919848452842 and parameters: {'subsample': 0.12341768738919337, 'dropout_rate': 0.16306347512784541, 'n_estimators': 375, 'learning_rate': 0.07962536751157849}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 07:07:40,435] Trial 85 finished with value: 0.7402770619747276 and parameters: {'subsample': 0.12118278185713931, 'dropout_rate': 0.17197290927780626, 'n_estimators': 378, 'learning_rate': 0.07985681264048913}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 07:07:44,022] Trial 86 finished with value: 0.7341213706345113 and parameters: {'subsample': 0.11834182325001122, 'dropout_rate': 0.11543197286879031, 'n_estimators': 311, 'learning_rate': 0.07886648694976499}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 07:07:48,629] Trial 87 finished with value: 0.7349359242392236 and parameters: {'subsample': 0.1012857675641469, 'dropout_rate': 0.1761750394725029, 'n_estimators': 369, 'learning_rate': 0.07362452387296685}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 07:07:52,717] Trial 88 finished with value: 0.7346721351144389 and parameters: {'subsample': 0.1578776535843909, 'dropout_rate': 0.153546694778028, 'n_estimators': 343, 'learning_rate': 0.07090149258027206}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 07:07:57,533] Trial 89 finished with value: 0.7338358035235034 and parameters: {'subsample': 0.19014674893298988, 'dropout_rate': 0.12644736222760672, 'n_estimators': 337, 'learning_rate': 0.09408608409945746}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 07:08:02,774] Trial 90 finished with value: 0.7347942766711054 and parameters: {'subsample': 0.14225944353309414, 'dropout_rate': 0.19167046909399793, 'n_estimators': 381, 'learning_rate': 0.07562521433321283}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 07:08:09,626] Trial 91 finished with value: 0.7347481666778123 and parameters: {'subsample': 0.1236120722919856, 'dropout_rate': 0.21878400876418375, 'n_estimators': 472, 'learning_rate': 0.08065009195395337}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:08:14,414] Trial 92 finished with value: 0.7309652418561551 and parameters: {'subsample': 0.17035433638735875, 'dropout_rate': 0.16900791541445045, 'n_estimators': 400, 'learning_rate': 0.0888813659208175}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:08:20,285] Trial 93 finished with value: 0.7109819732606247 and parameters: {'subsample': 0.4627070216098863, 'dropout_rate': 0.41200689746521035, 'n_estimators': 487, 'learning_rate': 0.09141176161017327}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 07:08:24,446] Trial 94 finished with value: 0.7403041182517839 and parameters: {'subsample': 0.12383891957673894, 'dropout_rate': 0.14121056788914568, 'n_estimators': 357, 'learning_rate': 0.08077924912008731}. Best is trial 81 with value: 0.7421283922651867.

Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 07:08:28,515] Trial 95 finished with value: 0.7385505975109213 and parameters: {'subsample': 0.10071428193828441, 'dropout_rate': 0.14314928221851414, 'n_estimators': 367, 'learning_rate': 0.07958498250189203}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 07:08:32,551] Trial 96 finished with value: 0.7394895646470715 and parameters: {'subsample': 0.10102196595624133, 'dropout_rate': 0.13583996617457794, 'n_estimators': 367, 'learning_rate': 0.08022437007277267}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 07:08:35,327] Trial 97 finished with value: 0.7365846759294004 and parameters: {'subsample': 0.12140419288895511, 'dropout_rate': 0.12396889967727803, 'n_estimators': 320, 'learning_rate': 0.06907410849558558}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 07:08:38,264] Trial 98 finished with value: 0.7300551506766177 and parameters: {'subsample': 0.20225000399878262, 'dropout_rate': 0.2025730936752311, 'n_estimators': 354, 'learning_rate': 0.07650750171476361}. Best is trial 81 with value: 0.7421283922651867.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8270042194092827

[I 2024-04-14 07:08:41,699] A new study created in memory with name: no-name-7c20c28e-897e-4181-a3f0-baa3b286b25b

Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 07:08:41,691] Trial 99 finished with value: 0.7331628974869093 and parameters: {'subsample': 0.15236116347767978, 'dropout_rate': 0.10074830298734014, 'n_estimators': 377, 'learning_rate': 0.07240471107473832}. Best is trial 81 with value: 0.7421283922651867.


* Best trial for C-index:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.7421283922651867], datetime_start=datetime.datetime(2024, 4, 14, 7, 7, 10, 574984), datetime_complete=datetime.datetime(2024, 4, 14, 7, 7, 18, 627209), params={'subsample': 0.12062136787385529, 'dropout_rate': 0.1337822012086785, 'n_estimators': 453, 'learning_rate': 0.08418081739857108}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=81, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.12062136787385529, 'dropout_rate': 0.1337822012086785, 'n_estimators': 453, 'learning_rate': 0.08418081739857108}


* Best Score for C-index:
 0.7421283922651867

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.18191546612592868
Fold 2 IBS: 0.26310028998515617
Fold 3 IBS: 0.18814227634676636
Fold 4 IBS: 0.2600787216130082
Fold 5 IBS: 0.2862534249599788
[I 2024-04-14 07:08:42,313] Trial 0 finished with value: 0.23589803580616767 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.23589803580616767.
Fold 1 IBS: 0.19477842709399526
Fold 2 IBS: 0.33585467034844974
Fold 3 IBS: 0.2564064122417441
Fold 4 IBS: 0.31585465097929083
Fold 5 IBS: 0.3346621734008407
[I 2024-04-14 07:08:46,918] Trial 1 finished with value: 0.2875112668128641 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.23589803580616767.
Fold 1 IBS: 0.18569108861856007
Fold 2 IBS: 0.3170284338043526
Fold 3 IBS: 0.22221204677621223
Fold 4 IBS: 0.3134867222721067
Fold 5 IBS: 0.318112239873901
[I 2024-04-14 07:08:47,865] Trial 2 finished with value: 0.2713061062690265 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.23589803580616767.
Fold 1 IBS: 0.18757841906804187
Fold 2 IBS: 0.2744158909032906
Fold 3 IBS: 0.19390640381715618
Fold 4 IBS: 0.3101579246089399
Fold 5 IBS: 0.30416055917814844
[I 2024-04-14 07:08:49,216] Trial 3 finished with value: 0.2540438395151154 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.23589803580616767.
Fold 1 IBS: 0.19024106063290575
Fold 2 IBS: 0.2739332035692553
Fold 3 IBS: 0.20104372436141404
Fold 4 IBS: 0.3117607641557728
Fold 5 IBS: 0.3106952297046889
[I 2024-04-14 07:08:51,138] Trial 4 finished with value: 0.25753479648480737 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.23589803580616767.
Fold 1 IBS: 0.19655131280896998
Fold 2 IBS: 0.35873186378942534
Fold 3 IBS: 0.2487057043839742
Fold 4 IBS: 0.3158522648325735
Fold 5 IBS: 0.33303440977618637
[I 2024-04-14 07:08:53,604] Trial 5 finished with value: 0.29057511111822587 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.23589803580616767.
Fold 1 IBS: 0.18179422925156355
Fold 2 IBS: 0.24562585746615054
Fold 3 IBS: 0.1790352186021763
Fold 4 IBS: 0.2247124094692705
Fold 5 IBS: 0.26384906315554474
[I 2024-04-14 07:08:55,149] Trial 6 finished with value: 0.21900335558894116 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.21900335558894116.
Fold 1 IBS: 0.19144049533406649
Fold 2 IBS: 0.19622654693258687
Fold 3 IBS: 0.17391683143642855
Fold 4 IBS: 0.20821474922858893
Fold 5 IBS: 0.22268390330614618
[I 2024-04-14 07:08:55,455] Trial 7 finished with value: 0.1984965052475634 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.1984965052475634.
Fold 1 IBS: 0.1780625230924574
Fold 2 IBS: 0.26190411625918514
Fold 3 IBS: 0.18796726365168887
Fold 4 IBS: 0.2585427064308324
Fold 5 IBS: 0.28637486173098226
[I 2024-04-14 07:08:57,029] Trial 8 finished with value: 0.23457029423302922 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.1984965052475634.
Fold 1 IBS: 0.19621371442321145
Fold 2 IBS: 0.35195819088040897
Fold 3 IBS: 0.24699877344059387
Fold 4 IBS: 0.3158535148468704
Fold 5 IBS: 0.3310531653716596
[I 2024-04-14 07:09:01,176] Trial 9 finished with value: 0.28841547179254884 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.1984965052475634.
Fold 1 IBS: 0.2133785145028611
Fold 2 IBS: 0.22061489336319529
Fold 3 IBS: 0.20362695967633807
Fold 4 IBS: 0.22439199408788554
Fold 5 IBS: 0.21797086899651574
[I 2024-04-14 07:09:01,362] Trial 10 finished with value: 0.21599664612535915 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.1984965052475634.
Fold 1 IBS: 0.21140722062572354
Fold 2 IBS: 0.2175205541289278
Fold 3 IBS: 0.20085795429817382
Fold 4 IBS: 0.22325500430754436
Fold 5 IBS: 0.21757915509214396
[I 2024-04-14 07:09:01,482] Trial 11 finished with value: 0.2141239776905027 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.1984965052475634.
Fold 1 IBS: 0.1767148503035389
Fold 2 IBS: 0.21029457306414306
Fold 3 IBS: 0.15765503108211493
Fold 4 IBS: 0.18586645084237963
Fold 5 IBS: 0.24860898979761326
[I 2024-04-14 07:09:01,784] Trial 12 finished with value: 0.19582797901795795 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.19582797901795795.
Fold 1 IBS: 0.17052221525029193
Fold 2 IBS: 0.22729482430021758
Fold 3 IBS: 0.1673504891506748
Fold 4 IBS: 0.19559092696865898
Fold 5 IBS: 0.26804500329598874
[I 2024-04-14 07:09:02,233] Trial 13 finished with value: 0.20576069179316642 and parameters: {'subsample': 0.11029739529314715, 'dropout_rate': 0.695526957994077, 'n_estimators': 86, 'learning_rate': 0.09856277651579823}. Best is trial 12 with value: 0.19582797901795795.
Fold 1 IBS: 0.1844316926925378
Fold 2 IBS: 0.1969252223356601
Fold 3 IBS: 0.16856989570022482
Fold 4 IBS: 0.20505123126837044
Fold 5 IBS: 0.2313380799916739
[I 2024-04-14 07:09:02,647] Trial 14 finished with value: 0.19726322439769342 and parameters: {'subsample': 0.2888452381430052, 'dropout_rate': 0.6348327022941171, 'n_estimators': 79, 'learning_rate': 0.035476350988955505}. Best is trial 12 with value: 0.19582797901795795.
Fold 1 IBS: 0.1939825611695674
Fold 2 IBS: 0.1959924545216754
Fold 3 IBS: 0.17782328275008508
Fold 4 IBS: 0.20206503674044463
Fold 5 IBS: 0.21880678866904518
[I 2024-04-14 07:09:03,224] Trial 15 finished with value: 0.19773402477016355 and parameters: {'subsample': 0.10269051002372756, 'dropout_rate': 0.8088719290273756, 'n_estimators': 112, 'learning_rate': 0.017180301525687395}. Best is trial 12 with value: 0.19582797901795795.
Fold 1 IBS: 0.18398195467450307
Fold 2 IBS: 0.2797728059137602
Fold 3 IBS: 0.19800795391901946
Fold 4 IBS: 0.30955628079132463
Fold 5 IBS: 0.30415407494094404
[I 2024-04-14 07:09:04,965] Trial 16 finished with value: 0.2550946140479103 and parameters: {'subsample': 0.25470623831733574, 'dropout_rate': 0.9733961081825167, 'n_estimators': 297, 'learning_rate': 0.03997706212314965}. Best is trial 12 with value: 0.19582797901795795.
Fold 1 IBS: 0.17148010729752342
Fold 2 IBS: 0.23317938592686835
Fold 3 IBS: 0.18094677716821608
Fold 4 IBS: 0.2557553881502778
Fold 5 IBS: 0.2786672271348463
[I 2024-04-14 07:09:05,407] Trial 17 finished with value: 0.22400577713554637 and parameters: {'subsample': 0.23334399376891685, 'dropout_rate': 0.6004730897368156, 'n_estimators': 87, 'learning_rate': 0.0909119567062787}. Best is trial 12 with value: 0.19582797901795795.
Fold 1 IBS: 0.18932195182672787
Fold 2 IBS: 0.20137924152724188
Fold 3 IBS: 0.1710353245229665
Fold 4 IBS: 0.20644405343553995
Fold 5 IBS: 0.22832789778096593
[I 2024-04-14 07:09:07,624] Trial 18 finished with value: 0.19930169381868842 and parameters: {'subsample': 0.3572229112225692, 'dropout_rate': 0.8096950255181005, 'n_estimators': 336, 'learning_rate': 0.006932799991015107}. Best is trial 12 with value: 0.19582797901795795.
Fold 1 IBS: 0.17542314717984364

Fold 2 IBS: 0.250374844169466
Fold 3 IBS: 0.18845162054668713
Fold 4 IBS: 0.28514869201474047
Fold 5 IBS: 0.29666844679611676
[I 2024-04-14 07:09:08,325] Trial 19 finished with value: 0.23921335014137082 and parameters: {'subsample': 0.1754785939282794, 'dropout_rate': 0.5719526157391092, 'n_estimators': 131, 'learning_rate': 0.08478060933651231}. Best is trial 12 with value: 0.19582797901795795.
Fold 1 IBS: 0.19434502454492755
Fold 2 IBS: 0.1976087722642088
Fold 3 IBS: 0.1772542498943357
Fold 4 IBS: 0.20956005678120226
Fold 5 IBS: 0.2202624636892423
[I 2024-04-14 07:09:08,617] Trial 20 finished with value: 0.19980611343478333 and parameters: {'subsample': 0.361226391737001, 'dropout_rate': 0.6283466334631026, 'n_estimators': 54, 'learning_rate': 0.03263327531246306}. Best is trial 12 with value: 0.19582797901795795.
Fold 1 IBS: 0.18948383515874043
Fold 2 IBS: 0.19401132917288091
Fold 3 IBS: 0.17320106539943225
Fold 4 IBS: 0.19815111909120867
Fold 5 IBS: 0.21924291552130318
[I 2024-04-14 07:09:09,290] Trial 21 finished with value: 0.19481805286871307 and parameters: {'subsample': 0.11012156245795512, 'dropout_rate': 0.793085993952307, 'n_estimators': 130, 'learning_rate': 0.01797338959196447}. Best is trial 21 with value: 0.19481805286871307.
Fold 1 IBS: 0.19284579995382992
Fold 2 IBS: 0.19517308445618253
Fold 3 IBS: 0.17518377279077765
Fold 4 IBS: 0.20389779789144694
Fold 5 IBS: 0.21948493152066514
[I 2024-04-14 07:09:10,023] Trial 22 finished with value: 0.19731707732258044 and parameters: {'subsample': 0.1830572315385881, 'dropout_rate': 0.786165129132064, 'n_estimators': 144, 'learning_rate': 0.013501142877011159}. Best is trial 21 with value: 0.19481805286871307.
Fold 1 IBS: 0.19726190891670253
Fold 2 IBS: 0.19891320105779894
Fold 3 IBS: 0.18088523657264932
Fold 4 IBS: 0.2112825600628919
Fold 5 IBS: 0.21966870842493044
[I 2024-04-14 07:09:10,346] Trial 23 finished with value: 0.20160232300699463 and parameters: {'subsample': 0.3039209180899198, 'dropout_rate': 0.8966891093723605, 'n_estimators': 64, 'learning_rate': 0.022822393540623813}. Best is trial 21 with value: 0.19481805286871307.
Fold 1 IBS: 0.2083974172979913
Fold 2 IBS: 0.21193785719474711
Fold 3 IBS: 0.1972128646665502
Fold 4 IBS: 0.21801768735792346
Fold 5 IBS: 0.216641441324927
[I 2024-04-14 07:09:10,496] Trial 24 finished with value: 0.2104414535684278 and parameters: {'subsample': 0.16995877045762384, 'dropout_rate': 0.9809691028743897, 'n_estimators': 14, 'learning_rate': 0.035027030745893334}. Best is trial 21 with value: 0.19481805286871307.
Fold 1 IBS: 0.17663767477180056
Fold 2 IBS: 0.25426914371237164
Fold 3 IBS: 0.18187912252487032
Fold 4 IBS: 0.25782400883973755
Fold 5 IBS: 0.28459887983359555
[I 2024-04-14 07:09:11,843] Trial 25 finished with value: 0.23104176593647513 and parameters: {'subsample': 0.41958256857066095, 'dropout_rate': 0.7657593559129287, 'n_estimators': 239, 'learning_rate': 0.02831114796721752}. Best is trial 21 with value: 0.19481805286871307.
Fold 1 IBS: 0.17224988248136103
Fold 2 IBS: 0.2125885562527134
Fold 3 IBS: 0.1582683768408667
Fold 4 IBS: 0.1902099551487742
Fold 5 IBS: 0.26011689817316147
[I 2024-04-14 07:09:12,660] Trial 26 finished with value: 0.19868673377937535 and parameters: {'subsample': 0.10346374278075587, 'dropout_rate': 0.5486757716887805, 'n_estimators': 150, 'learning_rate': 0.043730082755646243}. Best is trial 21 with value: 0.19481805286871307.
Fold 1 IBS: 0.19876837678812564
Fold 2 IBS: 0.20418641786054653
Fold 3 IBS: 0.18338578392747787
Fold 4 IBS: 0.215276598554588
Fold 5 IBS: 0.22084893392843669
[I 2024-04-14 07:09:13,059] Trial 27 finished with value: 0.20449322221183497 and parameters: {'subsample': 0.6109570826636859, 'dropout_rate': 0.6340112818214192, 'n_estimators': 82, 'learning_rate': 0.01527484183303061}. Best is trial 21 with value: 0.19481805286871307.
Fold 1 IBS: 0.18768762330147049
Fold 2 IBS: 0.19249130341931311
Fold 3 IBS: 0.16942053048216418
Fold 4 IBS: 0.19921125845262694
Fold 5 IBS: 0.2235096560544172
[I 2024-04-14 07:09:13,306] Trial 28 finished with value: 0.1944640743419984 and parameters: {'subsample': 0.19308358356170718, 'dropout_rate': 0.8528818052986153, 'n_estimators': 43, 'learning_rate': 0.06152638329235058}. Best is trial 28 with value: 0.1944640743419984.
Fold 1 IBS: 0.1871186469399865
Fold 2 IBS: 0.28953917082010144
Fold 3 IBS: 0.2144966242790554
Fold 4 IBS: 0.281436730908271
Fold 5 IBS: 0.29745101956320974
[I 2024-04-14 07:09:13,858] Trial 29 finished with value: 0.2540084385021248 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.8719606601118175, 'n_estimators': 119, 'learning_rate': 0.06046208382653473}. Best is trial 28 with value: 0.1944640743419984.
Fold 1 IBS: 0.1859376660321566
Fold 2 IBS: 0.1920531965583335
Fold 3 IBS: 0.1680178374799907
Fold 4 IBS: 0.19034424910236208
Fold 5 IBS: 0.2264698653874547
[I 2024-04-14 07:09:14,080] Trial 30 finished with value: 0.19256456291205953 and parameters: {'subsample': 0.18864766647252834, 'dropout_rate': 0.7457374535389898, 'n_estimators': 36, 'learning_rate': 0.08393461228282456}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.18649701163497567
Fold 2 IBS: 0.19200876697915328
Fold 3 IBS: 0.16853805537116084
Fold 4 IBS: 0.1964675494903989
Fold 5 IBS: 0.22345523410688511
[I 2024-04-14 07:09:14,293] Trial 31 finished with value: 0.19339332351651475 and parameters: {'subsample': 0.20560405879546245, 'dropout_rate': 0.749066869494496, 'n_estimators': 33, 'learning_rate': 0.08258106415108862}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.1865690811345996
Fold 2 IBS: 0.1979208359048134
Fold 3 IBS: 0.16905878712162326
Fold 4 IBS: 0.19532810709121484
Fold 5 IBS: 0.22443372836825123
[I 2024-04-14 07:09:14,505] Trial 32 finished with value: 0.1946621079241005 and parameters: {'subsample': 0.20865481434209837, 'dropout_rate': 0.9375828570319886, 'n_estimators': 34, 'learning_rate': 0.08178034772321156}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.18964681452213286
Fold 2 IBS: 0.19765591637263505
Fold 3 IBS: 0.17202623126332936
Fold 4 IBS: 0.20051933650588374
Fold 5 IBS: 0.22430988403143287
[I 2024-04-14 07:09:14,704] Trial 33 finished with value: 0.19683163653908275 and parameters: {'subsample': 0.2168480318433285, 'dropout_rate': 0.9521690859578895, 'n_estimators': 31, 'learning_rate': 0.07844718228135915}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.21090274047455626
Fold 2 IBS: 0.21716447141326967
Fold 3 IBS: 0.2010765628376112
Fold 4 IBS: 0.2229675808917173
Fold 5 IBS: 0.21745351707728755
[I 2024-04-14 07:09:14,824] Trial 34 finished with value: 0.2139129745388884 and parameters: {'subsample': 0.31478192981222664, 'dropout_rate': 0.848622612247815, 'n_estimators': 3, 'learning_rate': 0.06689378845283211}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.1714429028813647
Fold 2 IBS: 0.25454400951236356
Fold 3 IBS: 0.16017679711327407
Fold 4 IBS: 0.2720434211291048
Fold 5 IBS: 0.27848200073315255
[I 2024-04-14 07:09:15,305] Trial 35 finished with value: 0.22733782627385196 and parameters: {'subsample': 0.20278402237166407, 'dropout_rate': 0.9396446195304613, 'n_estimators': 102, 'learning_rate': 0.08215694552676671}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.21674071412272186
Fold 2 IBS: 0.34883122359725394
Fold 3 IBS: 0.2517809703465256
Fold 4 IBS: 0.31586034333441254
Fold 5 IBS: 0.3338780856980731
[I 2024-04-14 07:09:18,155] Trial 36 finished with value: 0.2934182674197974 and parameters: {'subsample': 0.43092545164422086, 'dropout_rate': 0.9206229134988069, 'n_estimators': 421, 'learning_rate': 0.07030607135872165}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.1868172748714748
Fold 2 IBS: 0.19937355611353516
Fold 3 IBS: 0.16910944354669227
Fold 4 IBS: 0.19657770369603558
Fold 5 IBS: 0.22421196136373575
[I 2024-04-14 07:09:18,377] Trial 37 finished with value: 0.1952179879182947 and parameters: {'subsample': 0.2449768831095508, 'dropout_rate': 0.47096246897520044, 'n_estimators': 35, 'learning_rate': 0.07677405503763898}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.18862243211172083

Fold 2 IBS: 0.25964476688146426
Fold 3 IBS: 0.18481687137574168
Fold 4 IBS: 0.2961768422814036
Fold 5 IBS: 0.30148765224499835
[I 2024-04-14 07:09:19,527] Trial 38 finished with value: 0.24614971297906574 and parameters: {'subsample': 0.15910316352149195, 'dropout_rate': 0.13272164755980653, 'n_estimators': 182, 'learning_rate': 0.08686981422611556}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.1813402582893099
Fold 2 IBS: 0.2113066790483602
Fold 3 IBS: 0.16446340065812048
Fold 4 IBS: 0.20822632431489052
Fold 5 IBS: 0.2441580840500885
[I 2024-04-14 07:09:19,846] Trial 39 finished with value: 0.2018989492721539 and parameters: {'subsample': 0.4058461621623634, 'dropout_rate': 0.2877671506289493, 'n_estimators': 59, 'learning_rate': 0.06001166712014448}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.19118996884076425
Fold 2 IBS: 0.20718847221902204
Fold 3 IBS: 0.17518785992514377
Fold 4 IBS: 0.2115822426561496
Fold 5 IBS: 0.22955436013927263
[I 2024-04-14 07:09:20,046] Trial 40 finished with value: 0.20294058075607047 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.848005884147651, 'n_estimators': 30, 'learning_rate': 0.06871059914008888}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.18178619308456562
Fold 2 IBS: 0.25802503503444707
Fold 3 IBS: 0.18908701441812012
Fold 4 IBS: 0.290929517675254
Fold 5 IBS: 0.29866193077420544
[I 2024-04-14 07:09:20,874] Trial 41 finished with value: 0.24369793819731847 and parameters: {'subsample': 0.1380589941340242, 'dropout_rate': 0.7708057295158887, 'n_estimators': 160, 'learning_rate': 0.08007875163059544}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.1713274122343276
Fold 2 IBS: 0.22046858618533138
Fold 3 IBS: 0.16505251102725912
Fold 4 IBS: 0.2211659875685668
Fold 5 IBS: 0.2613158380731253
[I 2024-04-14 07:09:21,425] Trial 42 finished with value: 0.20786606701772206 and parameters: {'subsample': 0.2181107608614251, 'dropout_rate': 0.7421362715853929, 'n_estimators': 110, 'learning_rate': 0.05508006032150162}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.17389002177275337
Fold 2 IBS: 0.2169919473601099
Fold 3 IBS: 0.1666486084445536
Fold 4 IBS: 0.21538765552217393
Fold 5 IBS: 0.2587714224868807
[I 2024-04-14 07:09:21,761] Trial 43 finished with value: 0.2063379311172943 and parameters: {'subsample': 0.28227992587423506, 'dropout_rate': 0.831582460425349, 'n_estimators': 67, 'learning_rate': 0.07360032042159523}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.2101877849855094
Fold 2 IBS: 0.2157240608276721
Fold 3 IBS: 0.20033990134300678
Fold 4 IBS: 0.2223897009915399
Fold 5 IBS: 0.21720128825895105
[I 2024-04-14 07:09:21,881] Trial 44 finished with value: 0.21316854728133589 and parameters: {'subsample': 0.32972616511915975, 'dropout_rate': 0.8857245834157494, 'n_estimators': 3, 'learning_rate': 0.08874156440032684}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.18707490634201712
Fold 2 IBS: 0.1959612058864246
Fold 3 IBS: 0.168909751043593
Fold 4 IBS: 0.19543985194747746
Fold 5 IBS: 0.22504471490934772
[I 2024-04-14 07:09:22,114] Trial 45 finished with value: 0.19448608602577197 and parameters: {'subsample': 0.14850991093249144, 'dropout_rate': 0.9938044416238512, 'n_estimators': 40, 'learning_rate': 0.06481263841101634}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.18592958458094214
Fold 2 IBS: 0.20456937200017422
Fold 3 IBS: 0.16716622826236813
Fold 4 IBS: 0.198063960078033
Fold 5 IBS: 0.23071419873700186
[I 2024-04-14 07:09:22,355] Trial 46 finished with value: 0.19728866873170386 and parameters: {'subsample': 0.2547529651425039, 'dropout_rate': 0.9809605793842167, 'n_estimators': 43, 'learning_rate': 0.0653065231667134}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.1944834206345543
Fold 2 IBS: 0.19561912501452164
Fold 3 IBS: 0.17759629119092987
Fold 4 IBS: 0.20114355370919754
Fold 5 IBS: 0.21959621793601977
[I 2024-04-14 07:09:22,535] Trial 47 finished with value: 0.19768772169704463 and parameters: {'subsample': 0.15739655842271733, 'dropout_rate': 0.9941084219066949, 'n_estimators': 24, 'learning_rate': 0.07507931202120034}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.19002832142253948
Fold 2 IBS: 0.30576467594791223
Fold 3 IBS: 0.2256407725140963
Fold 4 IBS: 0.3053871996450421
Fold 5 IBS: 0.31193338266907056
[I 2024-04-14 07:09:22,980] Trial 48 finished with value: 0.2677508704397321 and parameters: {'subsample': 0.6906215266335154, 'dropout_rate': 0.9296300409161108, 'n_estimators': 98, 'learning_rate': 0.0947019025153978}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.17787069025103155
Fold 2 IBS: 0.25127145283813046
Fold 3 IBS: 0.18844659611156775
Fold 4 IBS: 0.2904958784969488
Fold 5 IBS: 0.29173093033822267
[I 2024-04-14 07:09:24,198] Trial 49 finished with value: 0.23996310960718023 and parameters: {'subsample': 0.19811356959246476, 'dropout_rate': 0.6684584785701166, 'n_estimators': 212, 'learning_rate': 0.04897928524498507}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.1769357943415864
Fold 2 IBS: 0.2206415356733729
Fold 3 IBS: 0.15723675018280892
Fold 4 IBS: 0.21015082861978582
Fold 5 IBS: 0.2612946546308608
[I 2024-04-14 07:09:24,600] Trial 50 finished with value: 0.20525191268968296 and parameters: {'subsample': 0.2701993001587857, 'dropout_rate': 0.42732372125147283, 'n_estimators': 77, 'learning_rate': 0.06413782503205746}. Best is trial 30 with value: 0.19256456291205953.
Fold 1 IBS: 0.18183264013562694
Fold 2 IBS: 0.19643849680263026
Fold 3 IBS: 0.15991616748331106
Fold 4 IBS: 0.18400871098745145
Fold 5 IBS: 0.23970824098034635
[I 2024-04-14 07:09:24,879] Trial 51 finished with value: 0.19238085127787322 and parameters: {'subsample': 0.13998481122782022, 'dropout_rate': 0.8168182799095703, 'n_estimators': 51, 'learning_rate': 0.0819505231553438}. Best is trial 51 with value: 0.19238085127787322.
Fold 1 IBS: 0.1822279451111492
Fold 2 IBS: 0.19715896869921573
Fold 3 IBS: 0.16081108078709924
Fold 4 IBS: 0.18506469415070312
Fold 5 IBS: 0.2383128959201429
[I 2024-04-14 07:09:25,142] Trial 52 finished with value: 0.19271511693366206 and parameters: {'subsample': 0.14345324700268666, 'dropout_rate': 0.7442400087777848, 'n_estimators': 46, 'learning_rate': 0.08435127702570852}. Best is trial 51 with value: 0.19238085127787322.
Fold 1 IBS: 0.18178838556684568
Fold 2 IBS: 0.19773592188186828
Fold 3 IBS: 0.16030410601076267
Fold 4 IBS: 0.18448213970392377
Fold 5 IBS: 0.24011312495322523
[I 2024-04-14 07:09:25,407] Trial 53 finished with value: 0.19288473562332514 and parameters: {'subsample': 0.13964896243645, 'dropout_rate': 0.7424993700422279, 'n_estimators': 46, 'learning_rate': 0.08638988299605001}. Best is trial 51 with value: 0.19238085127787322.
Fold 1 IBS: 0.17650403518912341
Fold 2 IBS: 0.20838500766071552
Fold 3 IBS: 0.15658056697028772
Fold 4 IBS: 0.1805483831894876
Fold 5 IBS: 0.2562334019519448
[I 2024-04-14 07:09:25,726] Trial 54 finished with value: 0.1956502789923118 and parameters: {'subsample': 0.1368770345305162, 'dropout_rate': 0.7360834701628225, 'n_estimators': 60, 'learning_rate': 0.09331104334798723}. Best is trial 51 with value: 0.19238085127787322.
Fold 1 IBS: 0.19823432238232527
Fold 2 IBS: 0.20097978124740748
Fold 3 IBS: 0.18213083793605467
Fold 4 IBS: 0.2077151814098448
Fold 5 IBS: 0.21594355485802158
[I 2024-04-14 07:09:25,887] Trial 55 finished with value: 0.20100073556673076 and parameters: {'subsample': 0.1903641230347021, 'dropout_rate': 0.6679774520894655, 'n_estimators': 17, 'learning_rate': 0.08536373227593207}. Best is trial 51 with value: 0.19238085127787322.
Fold 1 IBS: 0.173171818910379
Fold 2 IBS: 0.23733408470219555
Fold 3 IBS: 0.16668710954347973
Fold 4 IBS: 0.22231010155232855
Fold 5 IBS: 0.2829596898026159
[I 2024-04-14 07:09:26,356] Trial 56 finished with value: 0.21649256090219976 and parameters: {'subsample': 0.12843882398290832, 'dropout_rate': 0.702800498762675, 'n_estimators': 93, 'learning_rate': 0.0975771627622756}. Best is trial 51 with value: 0.19238085127787322.
Fold 1 IBS: 0.20359149862308057
Fold 2 IBS: 0.3520195208530071

Fold 3 IBS: 0.2551066308112034
Fold 4 IBS: 0.3158543420372131
Fold 5 IBS: 0.33439926479054727
[I 2024-04-14 07:09:27,993] Trial 57 finished with value: 0.29219425142301025 and parameters: {'subsample': 0.842164102951203, 'dropout_rate': 0.8246529447682569, 'n_estimators': 282, 'learning_rate': 0.08992583695045304}. Best is trial 51 with value: 0.19238085127787322.
Fold 1 IBS: 0.17469063190030448
Fold 2 IBS: 0.20638575044774324
Fold 3 IBS: 0.16866002115533307
Fold 4 IBS: 0.20823295748943074
Fold 5 IBS: 0.25213746425655137
[I 2024-04-14 07:09:28,348] Trial 58 finished with value: 0.20202136504987261 and parameters: {'subsample': 0.23552611614332428, 'dropout_rate': 0.7535089906852777, 'n_estimators': 69, 'learning_rate': 0.07090539770564733}. Best is trial 51 with value: 0.19238085127787322.
Fold 1 IBS: 0.17707132653006127
Fold 2 IBS: 0.19800059918930474
Fold 3 IBS: 0.1627930805552266
Fold 4 IBS: 0.1867302808015111
Fold 5 IBS: 0.23127888217137144
[I 2024-04-14 07:09:28,613] Trial 59 finished with value: 0.19117483384949502 and parameters: {'subsample': 0.10355122058653286, 'dropout_rate': 0.5065802886056728, 'n_estimators': 45, 'learning_rate': 0.08322655251020356}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.1765116381272553
Fold 2 IBS: 0.24533770198915344
Fold 3 IBS: 0.17194022008581694
Fold 4 IBS: 0.25066486137113536
Fold 5 IBS: 0.28987460961867784
[I 2024-04-14 07:09:29,261] Trial 60 finished with value: 0.22686580623840777 and parameters: {'subsample': 0.12859834397393607, 'dropout_rate': 0.5984231091150927, 'n_estimators': 124, 'learning_rate': 0.0826716864344153}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.17579986201104505
Fold 2 IBS: 0.19875704930254437
Fold 3 IBS: 0.16386635274712696
Fold 4 IBS: 0.19144645973645064
Fold 5 IBS: 0.24400608214232047
[I 2024-04-14 07:09:29,526] Trial 61 finished with value: 0.19477516118789748 and parameters: {'subsample': 0.18378443928783764, 'dropout_rate': 0.6847698405578488, 'n_estimators': 47, 'learning_rate': 0.0995625379911529}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.20795061957170788
Fold 2 IBS: 0.2103212995660668
Fold 3 IBS: 0.19504625374917958
Fold 4 IBS: 0.21629972493109345
Fold 5 IBS: 0.21662523710100248
[I 2024-04-14 07:09:29,656] Trial 62 finished with value: 0.20924862698381003 and parameters: {'subsample': 0.1642381993531164, 'dropout_rate': 0.5005572319684436, 'n_estimators': 7, 'learning_rate': 0.08614725890436385}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.17471399774282512
Fold 2 IBS: 0.19836537806402427
Fold 3 IBS: 0.1592283472512604
Fold 4 IBS: 0.18440220662967685
Fold 5 IBS: 0.24282536457245457
[I 2024-04-14 07:09:29,947] Trial 63 finished with value: 0.19190705885204823 and parameters: {'subsample': 0.11028092263315001, 'dropout_rate': 0.36613701266026133, 'n_estimators': 51, 'learning_rate': 0.09155025795176149}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.17854675428138903
Fold 2 IBS: 0.22849141237714657
Fold 3 IBS: 0.15748809609535688
Fold 4 IBS: 0.19437330834956829
Fold 5 IBS: 0.2581876010144353
[I 2024-04-14 07:09:30,383] Trial 64 finished with value: 0.2034174344235792 and parameters: {'subsample': 0.10614662658405183, 'dropout_rate': 0.2852655711045659, 'n_estimators': 82, 'learning_rate': 0.0938163244271768}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.24024348875931384
Fold 2 IBS: 0.27377983310200044
Fold 3 IBS: 0.22238393240964788
Fold 4 IBS: 0.31698735839730535
Fold 5 IBS: 0.32822588539573977
[I 2024-04-14 07:09:32,828] Trial 65 finished with value: 0.27632409961280147 and parameters: {'subsample': 0.1306714749591642, 'dropout_rate': 0.4273423604806174, 'n_estimators': 329, 'learning_rate': 0.09032011342921194}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.19863870400386216
Fold 2 IBS: 0.1987579171180134
Fold 3 IBS: 0.18130663545911738
Fold 4 IBS: 0.20364968504636385
Fold 5 IBS: 0.2197206986802174
[I 2024-04-14 07:09:33,001] Trial 66 finished with value: 0.20041472806151486 and parameters: {'subsample': 0.1017893323393367, 'dropout_rate': 0.36532662757886314, 'n_estimators': 20, 'learning_rate': 0.07820998017572371}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.18103361650271182
Fold 2 IBS: 0.19855703033353816
Fold 3 IBS: 0.16013139506331628
Fold 4 IBS: 0.18596664196754747
Fold 5 IBS: 0.24315977568570993
[I 2024-04-14 07:09:33,285] Trial 67 finished with value: 0.19376969191056473 and parameters: {'subsample': 0.16372133567677494, 'dropout_rate': 0.7902254492239386, 'n_estimators': 53, 'learning_rate': 0.08332275821846265}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.2850831613639166
Fold 2 IBS: 0.26892227577223704
Fold 3 IBS: 0.2363369155775152
Fold 4 IBS: 0.31695507285237556
Fold 5 IBS: 0.34217432625213434
[I 2024-04-14 07:09:37,827] Trial 68 finished with value: 0.28989435036363576 and parameters: {'subsample': 0.22479533825123915, 'dropout_rate': 0.5139587975431332, 'n_estimators': 496, 'learning_rate': 0.08818419098969824}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.1762382193346444
Fold 2 IBS: 0.23199782394027949
Fold 3 IBS: 0.16037826897188484
Fold 4 IBS: 0.220561391958633
Fold 5 IBS: 0.26314279055824796
[I 2024-04-14 07:09:38,209] Trial 69 finished with value: 0.21046369895273792 and parameters: {'subsample': 0.5148995455795784, 'dropout_rate': 0.19943479176984602, 'n_estimators': 74, 'learning_rate': 0.08005201510043004}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.26274322226378616
Fold 2 IBS: 0.2694139114949855
Fold 3 IBS: 0.23887549868212288
Fold 4 IBS: 0.31627659208022935
Fold 5 IBS: 0.34049944108002783
[I 2024-04-14 07:09:41,700] Trial 70 finished with value: 0.28556173312023037 and parameters: {'subsample': 0.3325686216549225, 'dropout_rate': 0.33073010150287574, 'n_estimators': 408, 'learning_rate': 0.09603868783036132}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.17758040949221734
Fold 2 IBS: 0.1991847326141
Fold 3 IBS: 0.16182828360149087
Fold 4 IBS: 0.1858504316385888
Fold 5 IBS: 0.23703872548816368
[I 2024-04-14 07:09:41,992] Trial 71 finished with value: 0.19229651656691216 and parameters: {'subsample': 0.17146234139613467, 'dropout_rate': 0.7920309619755586, 'n_estimators': 55, 'learning_rate': 0.07616058145546846}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.19954289903519767
Fold 2 IBS: 0.20122879160400253
Fold 3 IBS: 0.18280283878065334
Fold 4 IBS: 0.20635911223922979
Fold 5 IBS: 0.2174737112990298
[I 2024-04-14 07:09:42,156] Trial 72 finished with value: 0.20148147059162264 and parameters: {'subsample': 0.17371587358229135, 'dropout_rate': 0.7248814494354893, 'n_estimators': 18, 'learning_rate': 0.07588888357001285}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.17031427179914732
Fold 2 IBS: 0.23840113097493454
Fold 3 IBS: 0.16686669725397943
Fold 4 IBS: 0.21606309518802289
Fold 5 IBS: 0.2771914896258906
[I 2024-04-14 07:09:42,632] Trial 73 finished with value: 0.21376733696839495 and parameters: {'subsample': 0.12442057265320816, 'dropout_rate': 0.7989616015094136, 'n_estimators': 98, 'learning_rate': 0.09144212631020684}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.18082546076157244
Fold 2 IBS: 0.19752132932608696
Fold 3 IBS: 0.1585068218708836
Fold 4 IBS: 0.18240261342073597
Fold 5 IBS: 0.24415333111871762
[I 2024-04-14 07:09:42,930] Trial 74 finished with value: 0.1926819112995993 and parameters: {'subsample': 0.14959718922766996, 'dropout_rate': 0.6128365123041772, 'n_estimators': 55, 'learning_rate': 0.08515869222210819}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.17988419561927504
Fold 2 IBS: 0.20022145027704685
Fold 3 IBS: 0.15905400163678868
Fold 4 IBS: 0.18214341179690471
Fold 5 IBS: 0.24276365407902326
[I 2024-04-14 07:09:43,224] Trial 75 finished with value: 0.19281334268180772 and parameters: {'subsample': 0.14369667182015958, 'dropout_rate': 0.5938982817402997, 'n_estimators': 54, 'learning_rate': 0.08627357467527212}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.1728005567449944
Fold 2 IBS: 0.20534027070212435
Fold 3 IBS: 0.15867228978225206
Fold 4 IBS: 0.18848191148564863
Fold 5 IBS: 0.23799991270019671
[I 2024-04-14 07:09:43,549] Trial 76 finished with value: 0.19265898828304323 and parameters: {'subsample': 0.10276916658169194, 'dropout_rate': 0.5286695930277079, 'n_estimators': 61, 'learning_rate': 0.07981224473589257}. Best is trial 59 with value: 0.19117483384949502.

Fold 1 IBS: 0.17853617145991055
Fold 2 IBS: 0.23588977410981765
Fold 3 IBS: 0.17081488781421916
Fold 4 IBS: 0.24289477474679425
Fold 5 IBS: 0.28857319241201684
[I 2024-04-14 07:09:44,317] Trial 77 finished with value: 0.22334176010855167 and parameters: {'subsample': 0.1001112939764896, 'dropout_rate': 0.5294003335641392, 'n_estimators': 143, 'learning_rate': 0.07314679264092239}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.1730450127166568
Fold 2 IBS: 0.22530630658873543
Fold 3 IBS: 0.17489061746957146
Fold 4 IBS: 0.23969480123538525
Fold 5 IBS: 0.2693371680473364
[I 2024-04-14 07:09:44,745] Trial 78 finished with value: 0.21645478121153708 and parameters: {'subsample': 0.23957179565357356, 'dropout_rate': 0.6270507767383827, 'n_estimators': 86, 'learning_rate': 0.07993068148087899}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.17256525203087672
Fold 2 IBS: 0.2519685332759536
Fold 3 IBS: 0.16589925362123678
Fold 4 IBS: 0.27773403389520596
Fold 5 IBS: 0.2896021371021762
[I 2024-04-14 07:09:45,343] Trial 79 finished with value: 0.23155384198508985 and parameters: {'subsample': 0.18453917241249337, 'dropout_rate': 0.47379203880156634, 'n_estimators': 116, 'learning_rate': 0.08385517472949379}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.1720253282071838
Fold 2 IBS: 0.21746484875729274
Fold 3 IBS: 0.1712357282335674
Fold 4 IBS: 0.2138576232485894
Fold 5 IBS: 0.2615403647627114
[I 2024-04-14 07:09:45,695] Trial 80 finished with value: 0.20722477864186892 and parameters: {'subsample': 0.29509125144368054, 'dropout_rate': 0.5684281368443235, 'n_estimators': 69, 'learning_rate': 0.07743720581934077}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.17797099104565192
Fold 2 IBS: 0.2049729301103048
Fold 3 IBS: 0.15815961807896167
Fold 4 IBS: 0.18282291675345463
Fold 5 IBS: 0.2519117558395593
[I 2024-04-14 07:09:46,011] Trial 81 finished with value: 0.19516764236558645 and parameters: {'subsample': 0.16482120614781579, 'dropout_rate': 0.5826714973132355, 'n_estimators': 59, 'learning_rate': 0.0879184080643733}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.1764880590226288
Fold 2 IBS: 0.20861439357470712
Fold 3 IBS: 0.1571957906654321
Fold 4 IBS: 0.18917668304489865
Fold 5 IBS: 0.24072845452989503
[I 2024-04-14 07:09:46,293] Trial 82 finished with value: 0.19444067616751232 and parameters: {'subsample': 0.14718156379275937, 'dropout_rate': 0.4448483633938144, 'n_estimators': 50, 'learning_rate': 0.09203598530595626}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.1880397915487657
Fold 2 IBS: 0.19421006716736253
Fold 3 IBS: 0.17667951278772712
Fold 4 IBS: 0.19824208634892582
Fold 5 IBS: 0.2178957184744346
[I 2024-04-14 07:09:46,496] Trial 83 finished with value: 0.19501343526544315 and parameters: {'subsample': 0.12284023779840478, 'dropout_rate': 0.6476275669201562, 'n_estimators': 29, 'learning_rate': 0.07326095872963352}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.20413477260568658
Fold 2 IBS: 0.20628264662636958
Fold 3 IBS: 0.1893473999864673
Fold 4 IBS: 0.21386015294745056
Fold 5 IBS: 0.21399028237028508
[I 2024-04-14 07:09:46,637] Trial 84 finished with value: 0.20552305090725181 and parameters: {'subsample': 0.21134190762160027, 'dropout_rate': 0.5567382402929217, 'n_estimators': 11, 'learning_rate': 0.08110153150296379}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.17587670778938672
Fold 2 IBS: 0.22570133341641482
Fold 3 IBS: 0.1659660767292409
Fold 4 IBS: 0.22120064304420697
Fold 5 IBS: 0.2769497649406215
[I 2024-04-14 07:09:47,146] Trial 85 finished with value: 0.2131389051839742 and parameters: {'subsample': 0.14806351050183664, 'dropout_rate': 0.6149446045067376, 'n_estimators': 101, 'learning_rate': 0.08391803239741359}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.17006567975801537
Fold 2 IBS: 0.22022970958875818
Fold 3 IBS: 0.15491404700338782
Fold 4 IBS: 0.19748233278253216
Fold 5 IBS: 0.2623788255348162
[I 2024-04-14 07:09:47,534] Trial 86 finished with value: 0.20101411893350196 and parameters: {'subsample': 0.1162347620742266, 'dropout_rate': 0.39584016755465, 'n_estimators': 74, 'learning_rate': 0.08896516723494885}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.21793375869039305
Fold 2 IBS: 0.27427816143096984
Fold 3 IBS: 0.2201021199788434
Fold 4 IBS: 0.3156923774497063
Fold 5 IBS: 0.31941987812400724
[I 2024-04-14 07:09:49,063] Trial 87 finished with value: 0.26948525913478394 and parameters: {'subsample': 0.18209157782114205, 'dropout_rate': 0.5333391729912997, 'n_estimators': 246, 'learning_rate': 0.0855474705320666}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.18521935367890635
Fold 2 IBS: 0.20299111093385552
Fold 3 IBS: 0.1668791557210782
Fold 4 IBS: 0.19437668249744794
Fold 5 IBS: 0.22611959162465575
[I 2024-04-14 07:09:49,288] Trial 88 finished with value: 0.19511717889118876 and parameters: {'subsample': 0.25638329157118156, 'dropout_rate': 0.4936159979023032, 'n_estimators': 36, 'learning_rate': 0.08008237304635227}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.17492737724358662
Fold 2 IBS: 0.22141355761367326
Fold 3 IBS: 0.16028206905266676
Fold 4 IBS: 0.19801069630453896
Fold 5 IBS: 0.2511268636362302
[I 2024-04-14 07:09:49,606] Trial 89 finished with value: 0.20115211277013914 and parameters: {'subsample': 0.4532242111026491, 'dropout_rate': 0.20622130457783389, 'n_estimators': 59, 'learning_rate': 0.09589661247428635}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.1805048850129975
Fold 2 IBS: 0.23766403292194122
Fold 3 IBS: 0.17265478461328518
Fold 4 IBS: 0.24783375218430656
Fold 5 IBS: 0.28872954486994845
[I 2024-04-14 07:09:50,146] Trial 90 finished with value: 0.2254773999204958 and parameters: {'subsample': 0.15361325337241027, 'dropout_rate': 0.6506455634739128, 'n_estimators': 108, 'learning_rate': 0.09238128680910679}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.18097047831466379
Fold 2 IBS: 0.1978585555591598
Fold 3 IBS: 0.15907518047476168
Fold 4 IBS: 0.1827721107122706
Fold 5 IBS: 0.24198812197521227
[I 2024-04-14 07:09:50,424] Trial 91 finished with value: 0.19253288940721364 and parameters: {'subsample': 0.1432282673487409, 'dropout_rate': 0.8183226404415131, 'n_estimators': 51, 'learning_rate': 0.08664791800231085}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.17907274758734698
Fold 2 IBS: 0.19760075903382937
Fold 3 IBS: 0.1622260628784586
Fold 4 IBS: 0.1988588323340847
Fold 5 IBS: 0.23670886496621701
[I 2024-04-14 07:09:50,691] Trial 92 finished with value: 0.19489345335998737 and parameters: {'subsample': 0.19872684166077792, 'dropout_rate': 0.7704130712392967, 'n_estimators': 49, 'learning_rate': 0.0872036544275856}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.16967569215287862
Fold 2 IBS: 0.2220117775772572
Fold 3 IBS: 0.16019133132211866
Fold 4 IBS: 0.18863491488036963
Fold 5 IBS: 0.2605704476575703
[I 2024-04-14 07:09:51,133] Trial 93 finished with value: 0.20021683271803886 and parameters: {'subsample': 0.11721170982680422, 'dropout_rate': 0.8292751774119739, 'n_estimators': 88, 'learning_rate': 0.07682062564006235}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.1933892130888468
Fold 2 IBS: 0.19490293513473347
Fold 3 IBS: 0.17460705197053256
Fold 4 IBS: 0.1981667806850248
Fold 5 IBS: 0.22210242000490543
[I 2024-04-14 07:09:51,327] Trial 94 finished with value: 0.19663368017680863 and parameters: {'subsample': 0.1467546146620329, 'dropout_rate': 0.8633953337405998, 'n_estimators': 25, 'learning_rate': 0.08415515793075032}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.18335973424068747
Fold 2 IBS: 0.19197660336018857
Fold 3 IBS: 0.1680525621061901
Fold 4 IBS: 0.1918774157261858
Fold 5 IBS: 0.22356033855765228
[I 2024-04-14 07:09:51,570] Trial 95 finished with value: 0.19176533079818087 and parameters: {'subsample': 0.1009194735110214, 'dropout_rate': 0.8104031329230592, 'n_estimators': 40, 'learning_rate': 0.0720140485106917}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.1844205471381469
Fold 2 IBS: 0.19216691081953086

Fold 3 IBS: 0.16930034966284252
Fold 4 IBS: 0.19375258458530342
Fold 5 IBS: 0.22229018790927785
[I 2024-04-14 07:09:51,809] Trial 96 finished with value: 0.1923861160230203 and parameters: {'subsample': 0.10083687177713299, 'dropout_rate': 0.7805004063112455, 'n_estimators': 39, 'learning_rate': 0.06965774462731136}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.17683525286958884
Fold 2 IBS: 0.20779746239024227
Fold 3 IBS: 0.16051519951980997
Fold 4 IBS: 0.1820487332247056
Fold 5 IBS: 0.24023463248444205
[I 2024-04-14 07:09:52,146] Trial 97 finished with value: 0.19348625609775777 and parameters: {'subsample': 0.11856796934732222, 'dropout_rate': 0.9061069634081566, 'n_estimators': 66, 'learning_rate': 0.07017890475325032}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.21295907660299157
Fold 2 IBS: 0.2203245730751611
Fold 3 IBS: 0.2033231161410431
Fold 4 IBS: 0.22329249185147954
Fold 5 IBS: 0.2178623396577444
[I 2024-04-14 07:09:52,262] Trial 98 finished with value: 0.21555231946568396 and parameters: {'subsample': 0.10344827187205913, 'dropout_rate': 0.8073316342927881, 'n_estimators': 1, 'learning_rate': 0.07541193698734891}. Best is trial 59 with value: 0.19117483384949502.
Fold 1 IBS: 0.19334198407402758
Fold 2 IBS: 0.1947343245781043
Fold 3 IBS: 0.1732707758548748
Fold 4 IBS: 0.19816792260325986
Fold 5 IBS: 0.22209113423248766
[I 2024-04-14 07:09:52,472] Trial 99 finished with value: 0.19632122826855083 and parameters: {'subsample': 0.16627355226158874, 'dropout_rate': 0.8244331340380346, 'n_estimators': 32, 'learning_rate': 0.06858051471883178}. Best is trial 59 with value: 0.19117483384949502.


* Best trial for IBS:
 FrozenTrial(number=59, state=TrialState.COMPLETE, values=[0.19117483384949502], datetime_start=datetime.datetime(2024, 4, 14, 7, 9, 28, 350317), datetime_complete=datetime.datetime(2024, 4, 14, 7, 9, 28, 612932), params={'subsample': 0.10355122058653286, 'dropout_rate': 0.5065802886056728, 'n_estimators': 45, 'learning_rate': 0.08322655251020356}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=59, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.10355122058653286, 'dropout_rate': 0.5065802886056728, 'n_estimators': 45, 'learning_rate': 0.08322655251020356}


* Best Score for IBS:
 0.19117483384949502

In [120]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [121]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.742
train_ibs:  0.191

#### Test

In [122]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [123]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.1337822012086785,
                                              learning_rate=0.08418081739857108,
                                              n_estimators=453,
                                              random_state=123,
                                              subsample=0.12062136787385529)

C-index score: 0.541

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.5065802886056728,
                                              learning_rate=0.08322655251020356,
                                              n_estimators=45, random_state=123,
                                              subsample=0.10355122058653286)

IBS: 0.249

In [124]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [125]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.826   1.0
ExtraSurvivalTrees               0.794   2.0
CoxLasso                         0.759   3.5
CoxElastic                       0.759   3.5
CoxPH                            0.758   5.0
GradientBoosting                 0.745   6.0
ComponentwiseGradientBoosting    0.742   7.0
CoxRidge                         0.708   8.0

In [126]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.183   1.5
ExtraSurvivalTrees             0.183   1.5
CoxLasso                       0.187   3.5
CoxElastic                     0.187   3.5
CoxPH                          0.188   5.0
ComponentwiseGradientBoosting  0.191   6.0
GradientBoosting               0.215   7.0
CoxRidge                       0.217   8.0

In [127]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.653   1.0
ExtraSurvivalTrees               0.618   2.0
GradientBoosting                 0.603   3.0
CoxLasso                         0.591   4.5
CoxElastic                       0.591   4.5
CoxPH                            0.585   6.0
CoxRidge                         0.576   7.0
ComponentwiseGradientBoosting    0.541   8.0

In [128]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
Randomsurvivalforest           0.206   1.0
ExtraSurvivalTrees             0.215   2.0
GradientBoosting               0.220   3.0
CoxRidge                       0.221   4.0
ComponentwiseGradientBoosting  0.249   5.0
CoxLasso                       0.284   6.5
CoxElastic                     0.284   6.5
CoxPH                          0.288   8.0

In [129]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/os/robust/no_selection/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


# Modify the file names to match the desired format
modified_file_names = ['d1_os_robust_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [130]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-14