In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import RobustScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

## Test dataset: MAASTRO

In [6]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [7]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [8]:
# need to choose patient_id from MAASTRO_D1 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [9]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]

In [10]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [11]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, OS, OS_event]
Index: []

In [12]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [13]:
# Set lower, upper time point and times for IBS calculation later 

# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]
lower, upper = np.percentile(y_MAASTRO['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 14)
y_train:  (139,)

(99, 16)

# Feature Selection: PLSR

In [14]:
selected_features = [
"hpv_related",
"oropharynx",
"uicc8_III-IV",
"cavum_oris",
"charlson"      
]

# Selecting features in the DataFrame
X_plsr = X[selected_features]
X_new = X_plsr.copy()

In [15]:
X_MAASTRO_plsr = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_plsr.copy()
# No need to standardize since all selected columns are binary
X_new_std = X_new
MAASTRO_new_std = MAASTRO_new

# Standardization

In [18]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)
"""
# Do the standardization for the numeric part 
scaler = RobustScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 

# All the columns are binary meaning no scaler needed 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]
"""

'\n# Do the standardization for the numeric part \nscaler = RobustScaler() \nX_new_numeric_columns = X_new_numeric.columns\nX_new_numeric_index = X_new_numeric.index \n\n# All the columns are binary meaning no scaler needed \nX_new_numeric_std = scaler.fit_transform(X_new_numeric)\nX_new_numeric_std = pd.DataFrame(X_new_numeric_std,\n                                 columns=X_new_numeric_columns, \n                                 index=X_new_numeric_index)\nX_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)\n\n# Change the order of the X_new_std \nX_new_std = X_new_std[X_new.columns]\n'

In [19]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
"""
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]
"""

'\nMAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns\nMAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns\nMAASTRO_new_numeric_index = MAASTRO_new_numeric.index \nMAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)\nMAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,\n                                 columns=MAASTRO_new_numeric_columns, \n                                 index=MAASTRO_new_numeric_index)\nMAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)\n\n# Change the order of the X_new_std \nMAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]\n'

In [20]:
X_new

     hpv_related  oropharynx  uicc8_III-IV  cavum_oris  charlson
0            0.0           1           0.0           0         0
1            0.0           0           0.0           0         1
2            0.0           0           1.0           1         1
3            0.0           0           0.0           0         1
4            0.0           0           0.0           0         1
..           ...         ...           ...         ...       ...
134          1.0           1           0.0           0         0
135          1.0           1           1.0           0         0
136          1.0           1           0.0           0         1
137          1.0           1           1.0           0         1
138          1.0           1           1.0           0         0

[139 rows x 5 columns]

In [21]:
X_new_std

     hpv_related  oropharynx  uicc8_III-IV  cavum_oris  charlson
0            0.0           1           0.0           0         0
1            0.0           0           0.0           0         1
2            0.0           0           1.0           1         1
3            0.0           0           0.0           0         1
4            0.0           0           0.0           0         1
..           ...         ...           ...         ...       ...
134          1.0           1           0.0           0         0
135          1.0           1           1.0           0         0
136          1.0           1           0.0           0         1
137          1.0           1           1.0           0         1
138          1.0           1           1.0           0         0

[139 rows x 5 columns]

In [22]:
MAASTRO_new

    hpv_related  oropharynx  uicc8_III-IV  cavum_oris  charlson
0             1           1             0           0         1
1             0           1             1           0         0
2             0           1             1           0         1
3             0           0             1           0         1
4             1           1             0           0         1
..          ...         ...           ...         ...       ...
94            0           0             1           0         0
95            0           0             1           0         1
96            1           1             1           0         1
97            1           1             0           0         0
98            0           0             1           0         0

[99 rows x 5 columns]

In [23]:
MAASTRO_new_std

    hpv_related  oropharynx  uicc8_III-IV  cavum_oris  charlson
0             1           1             0           0         1
1             0           1             1           0         0
2             0           1             1           0         1
3             0           0             1           0         1
4             1           1             0           0         1
..          ...         ...           ...         ...       ...
94            0           0             1           0         0
95            0           0             1           0         1
96            1           1             1           0         1
97            1           1             0           0         0
98            0           0             1           0         0

[99 rows x 5 columns]

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [24]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 19:36:57,803] A new study created in memory with name: no-name-95f42188-ca37-4374-841d-e8df9d6430be
python(44932) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666

[I 2024-04-14 19:37:11,029] A new study created in memory with name: no-name-e92ebe9a-505c-4bba-9eb5-a598f79b550e

Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:11,009] Trial 0 finished with value: 0.7428869028324144 and parameters: {}. Best is trial 0 with value: 0.7428869028324144.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7428869028324144], datetime_start=datetime.datetime(2024, 4, 14, 19, 36, 58, 120433), datetime_complete=datetime.datetime(2024, 4, 14, 19, 37, 11, 7860), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7428869028324144

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.1559351021475166
Fold 2 IBS: 0.20199327049535848
Fold 3 IBS: 0.14988167065458602
Fold 4 IBS: 0.15052551170060235
Fold 5 IBS: 0.2607666311501383
[I 2024-04-14 19:37:11,846] Trial 0 finished with value: 0.18382043722964034 and parameters: {}. Best is trial 0 with value: 0.18382043722964034.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.18382043722964034], datetime_start=datetime.datetime(2024, 4, 14, 19, 37, 11, 159313), datetime_complete=datetime.datetime(2024, 4, 14, 19, 37, 11, 845925), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.18382043722964034

In [25]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [26]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.743
train_ibs:  0.184

#### Test

In [27]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [28]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.583
IBS score: 0.266

In [29]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [30]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [31]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 19:37:12,266] A new study created in memory with name: no-name-71bd0862-2d25-431a-b406-065ceaf72d5e

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8016877637130801

[I 2024-04-14 19:37:12,636] A new study created in memory with name: no-name-e3431652-53f2-4407-8736-41f417e0985b

Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 19:37:12,630] Trial 0 finished with value: 0.7182877718827688 and parameters: {}. Best is trial 0 with value: 0.7182877718827688.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7182877718827688], datetime_start=datetime.datetime(2024, 4, 14, 19, 37, 12, 311303), datetime_complete=datetime.datetime(2024, 4, 14, 19, 37, 12, 629390), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7182877718827688

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651763328032
Fold 2 IBS: 0.2215779146949956
Fold 3 IBS: 0.20453594133219627
Fold 4 IBS: 0.22473803324306438
Fold 5 IBS: 0.2181243143630602
[I 2024-04-14 19:37:12,909] Trial 0 finished with value: 0.21659054425331936 and parameters: {}. Best is trial 0 with value: 0.21659054425331936.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054425331936], datetime_start=datetime.datetime(2024, 4, 14, 19, 37, 12, 674703), datetime_complete=datetime.datetime(2024, 4, 14, 19, 37, 12, 908970), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054425331936

In [32]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [33]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.718
train_ibs:  0.217

#### Test

In [34]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [35]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.624

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [36]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [37]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 19:37:13,254] A new study created in memory with name: no-name-5f35a973-0264-49ad-81d2-962c1206c73b

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312

[I 2024-04-14 19:37:14,387] A new study created in memory with name: no-name-3ed29f8d-91d8-4f40-b5eb-4480d1427464

Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:14,373] Trial 0 finished with value: 0.7428869028324144 and parameters: {}. Best is trial 0 with value: 0.7428869028324144.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7428869028324144], datetime_start=datetime.datetime(2024, 4, 14, 19, 37, 13, 294769), datetime_complete=datetime.datetime(2024, 4, 14, 19, 37, 14, 372877), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7428869028324144

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.15606861576698203
Fold 2 IBS: 0.20309895455300028
Fold 3 IBS: 0.14946560041623583
Fold 4 IBS: 0.14998880386341362
Fold 5 IBS: 0.25859361321320185
[I 2024-04-14 19:37:15,703] Trial 0 finished with value: 0.18344311756256673 and parameters: {}. Best is trial 0 with value: 0.18344311756256673.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.18344311756256673], datetime_start=datetime.datetime(2024, 4, 14, 19, 37, 14, 587593), datetime_complete=datetime.datetime(2024, 4, 14, 19, 37, 15, 702918), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.18344311756256673

In [38]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [39]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.743
train_ibs:  0.183

#### Test

In [40]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [41]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.583

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.261

In [42]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [43]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 19:37:16,309] A new study created in memory with name: no-name-b7f8ae0a-e4e9-48c7-ba9f-30a0e4739fb8

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:17,166] Trial 0 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.739315474260986.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:18,160] Trial 1 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.739315474260986.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:19,082] Trial 2 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.739315474260986.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:19,742] Trial 3 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.739315474260986.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:20,352] Trial 4 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.739315474260986.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:20,966] Trial 5 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.739315474260986.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:21,575] Trial 6 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:22,136] Trial 7 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:22,636] Trial 8 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:23,272] Trial 9 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:23,791] Trial 10 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:24,301] Trial 11 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:24,737] Trial 12 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9946087870438435}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:25,224] Trial 13 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8521165717679541}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:25,937] Trial 14 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:26,436] Trial 15 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8659212232095017}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:26,923] Trial 16 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8592866247617579}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:27,453] Trial 17 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8140829029918109}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:28,154] Trial 18 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.5819463953201167}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:28,652] Trial 19 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9535087433508003}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:29,144] Trial 20 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.7540198302114602}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:29,651] Trial 21 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9453140545316446}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:30,174] Trial 22 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9952149413953396}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:30,659] Trial 23 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8898693182098678}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666

Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:31,296] Trial 24 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.7805647035680947}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:31,799] Trial 25 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9368557715647121}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:32,082] Trial 26 finished with value: 0.715225727602829 and parameters: {'l1_ratio': 0.015423757551295547}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:32,641] Trial 27 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.6022588122254688}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:33,190] Trial 28 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.6499747968454208}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:33,658] Trial 29 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9010792166439672}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:34,151] Trial 30 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8107108448948633}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:34,625] Trial 31 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9790160904460925}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:35,268] Trial 32 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9889509715055751}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:35,850] Trial 33 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9033942188713268}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:36,334] Trial 34 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9969906676119189}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:37,052] Trial 35 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9145273991086058}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:38,520] Trial 36 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.23789482035414378}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:40,430] Trial 37 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.7342815000174964}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:42,209] Trial 38 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8450450825036032}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:43,139] Trial 39 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.35153102114871604}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:44,320] Trial 40 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.6762726602177129}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:45,824] Trial 41 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9960924020280132}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:46,611] Trial 42 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9419682443206}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:47,430] Trial 43 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8119687552544277}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:48,315] Trial 44 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9393661793057178}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:49,206] Trial 45 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8746070404800059}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:49,815] Trial 46 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.5222973322437542}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:50,505] Trial 47 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9991045282580079}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666

Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:51,292] Trial 48 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8342998569224302}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:51,845] Trial 49 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9586049921503356}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:52,475] Trial 50 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.7809764372372684}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:53,102] Trial 51 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9560467332727327}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:53,700] Trial 52 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8871531144268382}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:54,337] Trial 53 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9749546357535185}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:54,856] Trial 54 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9264665304817092}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:55,537] Trial 55 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8741716481315738}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:56,105] Trial 56 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9205924860520386}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:56,913] Trial 57 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9671155748865983}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:57,588] Trial 58 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.7734026256905541}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:58,360] Trial 59 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.15285260431247993}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:59,101] Trial 60 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8375350400183244}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:37:59,652] Trial 61 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.995048907748274}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:00,432] Trial 62 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9606263381935579}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:01,414] Trial 63 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9260812672003349}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:02,047] Trial 64 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9736478178069808}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:02,622] Trial 65 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.899070827241155}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:03,221] Trial 66 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9959964244174173}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:03,951] Trial 67 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.43329817685084393}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:04,583] Trial 68 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9055362014378469}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:05,192] Trial 69 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8608260360215402}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:05,801] Trial 70 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9697682359048108}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:06,383] Trial 71 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9940302754420428}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666

Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:07,021] Trial 72 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.934572235423216}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:07,938] Trial 73 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9761228165714378}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:08,549] Trial 74 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9393512015259131}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:09,158] Trial 75 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8983627760064841}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:09,962] Trial 76 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.95102012660963}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:10,605] Trial 77 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9984372771650676}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:11,200] Trial 78 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8666138485043473}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:11,745] Trial 79 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8187818034877232}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:12,510] Trial 80 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9162507146228802}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:13,980] Trial 81 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.993288871834262}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:14,726] Trial 82 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9709436318882778}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:15,486] Trial 83 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.949679359462661}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:16,796] Trial 84 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9983144318120931}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:18,502] Trial 85 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.31300862881884994}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:20,516] Trial 86 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8921804846680484}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:21,394] Trial 87 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9247695361648618}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:22,143] Trial 88 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9715160254919811}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:22,877] Trial 89 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9414194979079367}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:23,610] Trial 90 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.8858346202736684}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:24,433] Trial 91 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9744891524849301}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:25,119] Trial 92 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9865774864165617}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:25,882] Trial 93 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9524898984193365}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:26,592] Trial 94 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9224222442084746}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:27,380] Trial 95 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9991107887307169}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666

Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:28,244] Trial 96 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.6030924300037979}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:29,091] Trial 97 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.9579083665678496}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:29,765] Trial 98 finished with value: 0.739315474260986 and parameters: {'l1_ratio': 0.9177595130244339}. Best is trial 6 with value: 0.7428869028324144.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8122362869198312

[I 2024-04-14 19:38:30,481] A new study created in memory with name: no-name-26ccb6d4-ba3a-49c9-bac8-bf0101cdc658

Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:38:30,435] Trial 99 finished with value: 0.7428869028324144 and parameters: {'l1_ratio': 0.977800413857822}. Best is trial 6 with value: 0.7428869028324144.


* Best trial for C-index:
 FrozenTrial(number=6, state=TrialState.COMPLETE, values=[0.7428869028324144], datetime_start=datetime.datetime(2024, 4, 14, 19, 37, 20, 970556), datetime_complete=datetime.datetime(2024, 4, 14, 19, 37, 21, 575458), params={'l1_ratio': 0.980766121964777}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=6, value=None)


* Best Score for C-index:
 0.7428869028324144

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.15597895981533158
Fold 2 IBS: 0.2032925960225151
Fold 3 IBS: 0.14940311636030415
Fold 4 IBS: 0.14997720075183757
Fold 5 IBS: 0.25849972609225597
[I 2024-04-14 19:38:31,277] Trial 0 finished with value: 0.18343031980844887 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.18343031980844887.
Fold 1 IBS: 0.15583301273157582
Fold 2 IBS: 0.20371525425477433
Fold 3 IBS: 0.1492910084197231
Fold 4 IBS: 0.1499540199957421
Fold 5 IBS: 0.25844150966558693
[I 2024-04-14 19:38:31,979] Trial 1 finished with value: 0.18344696101348043 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.18343031980844887.
Fold 1 IBS: 0.1558054908902288
Fold 2 IBS: 0.20367466951648294
Fold 3 IBS: 0.14925365786585554
Fold 4 IBS: 0.1499837506928614
Fold 5 IBS: 0.2583180749629356
[I 2024-04-14 19:38:32,724] Trial 2 finished with value: 0.18340712878567283 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.15593114287305346
Fold 2 IBS: 0.20343575700372682
Fold 3 IBS: 0.14934957724863757
Fold 4 IBS: 0.14996873346564243
Fold 5 IBS: 0.2585450532148558
[I 2024-04-14 19:38:33,846] Trial 3 finished with value: 0.1834460527611832 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.15598389619453035
Fold 2 IBS: 0.20334939871035934
Fold 3 IBS: 0.1493812385233986
Fold 4 IBS: 0.14994317244379538
Fold 5 IBS: 0.2585784811545638
[I 2024-04-14 19:38:34,862] Trial 4 finished with value: 0.18344723740532948 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.15588501225624993
Fold 2 IBS: 0.20361745668119696
Fold 3 IBS: 0.1493302907837216
Fold 4 IBS: 0.14994694894968416
Fold 5 IBS: 0.25833538643574944
[I 2024-04-14 19:38:35,619] Trial 5 finished with value: 0.1834230190213204 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.1560658581317939
Fold 2 IBS: 0.2030325243883039
Fold 3 IBS: 0.14945354675822212
Fold 4 IBS: 0.1499807140924041
Fold 5 IBS: 0.25854358236581865
[I 2024-04-14 19:38:36,343] Trial 6 finished with value: 0.18341524514730853 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.15597507049738674
Fold 2 IBS: 0.2033146786989837
Fold 3 IBS: 0.14939315543537887
Fold 4 IBS: 0.14996985845022637
Fold 5 IBS: 0.258458033468073
[I 2024-04-14 19:38:37,042] Trial 7 finished with value: 0.18342215931000974 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.15590669862985204
Fold 2 IBS: 0.20353558621686352
Fold 3 IBS: 0.14931449730434546
Fold 4 IBS: 0.149954552294271
Fold 5 IBS: 0.25842483139634287
[I 2024-04-14 19:38:37,700] Trial 8 finished with value: 0.18342723316833498 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.1558739818862727
Fold 2 IBS: 0.20360923663160205
Fold 3 IBS: 0.14933186675317195
Fold 4 IBS: 0.14995930724613665
Fold 5 IBS: 0.25836281963841007
[I 2024-04-14 19:38:38,463] Trial 9 finished with value: 0.1834274424311187 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.15574062650282042
Fold 2 IBS: 0.20383359372578994
Fold 3 IBS: 0.14923708429502133
Fold 4 IBS: 0.14996970389992792
Fold 5 IBS: 0.25833049322015267
[I 2024-04-14 19:38:39,383] Trial 10 finished with value: 0.18342230032874246 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.15604091083579266
Fold 2 IBS: 0.20314579253093068
Fold 3 IBS: 0.14945174885990323
Fold 4 IBS: 0.14995330251021624
Fold 5 IBS: 0.2585835171160045
[I 2024-04-14 19:38:40,098] Trial 11 finished with value: 0.18343505437056945 and parameters: {'l1_ratio': 0.9201080639320232}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.15606722688062222
Fold 2 IBS: 0.2030218825636363
Fold 3 IBS: 0.14945953036711979
Fold 4 IBS: 0.14998472708445607
Fold 5 IBS: 0.2585684097386317
[I 2024-04-14 19:38:40,759] Trial 12 finished with value: 0.18342035532689321 and parameters: {'l1_ratio': 0.9902263164082913}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.21261163843103506
Fold 2 IBS: 0.20384807344422726
Fold 3 IBS: 0.14922835418372785
Fold 4 IBS: 0.2221640184483064
Fold 5 IBS: 0.25832231278262047
[I 2024-04-14 19:38:41,668] Trial 13 finished with value: 0.20923487945798339 and parameters: {'l1_ratio': 0.03319766496089682}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.15581634707189593
Fold 2 IBS: 0.20365408004349134
Fold 3 IBS: 0.14926251575917882
Fold 4 IBS: 0.14998415981025415
Fold 5 IBS: 0.258341485079683
[I 2024-04-14 19:38:42,873] Trial 14 finished with value: 0.18341171755290064 and parameters: {'l1_ratio': 0.2507045659058569}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.15579791662774334
Fold 2 IBS: 0.203727782040231
Fold 3 IBS: 0.14928319311552893
Fold 4 IBS: 0.14996823356502753
Fold 5 IBS: 0.25844640731477525
[I 2024-04-14 19:38:43,743] Trial 15 finished with value: 0.1834447065326612 and parameters: {'l1_ratio': 0.21932062545639627}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.15579335093016478
Fold 2 IBS: 0.20377405853128128
Fold 3 IBS: 0.14926655283541665
Fold 4 IBS: 0.14995482423323797
Fold 5 IBS: 0.258380391071715
[I 2024-04-14 19:38:44,433] Trial 16 finished with value: 0.18343383552036316 and parameters: {'l1_ratio': 0.21303081021895065}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.15576433669273143
Fold 2 IBS: 0.20378292356483202
Fold 3 IBS: 0.14925888910858673
Fold 4 IBS: 0.14997248997935356
Fold 5 IBS: 0.25839032654644867
[I 2024-04-14 19:38:45,737] Trial 17 finished with value: 0.18343379317839048 and parameters: {'l1_ratio': 0.1360825059390146}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.155851756139795
Fold 2 IBS: 0.20357983427895904
Fold 3 IBS: 0.14929369701315354
Fold 4 IBS: 0.14998496271051845
Fold 5 IBS: 0.2584209941277035
[I 2024-04-14 19:38:46,706] Trial 18 finished with value: 0.1834262488540259 and parameters: {'l1_ratio': 0.33883882709417557}. Best is trial 2 with value: 0.18340712878567283.
Fold 1 IBS: 0.15578160959562942
Fold 2 IBS: 0.20372162707211955
Fold 3 IBS: 0.1492329142531989
Fold 4 IBS: 0.14998370058821278
Fold 5 IBS: 0.25826488197433084
[I 2024-04-14 19:38:47,645] Trial 19 finished with value: 0.1833969466966983 and parameters: {'l1_ratio': 0.16922934881357457}. Best is trial 19 with value: 0.1833969466966983.
Fold 1 IBS: 0.15575996372669093
Fold 2 IBS: 0.20371452112407956
Fold 3 IBS: 0.14923415707276474
Fold 4 IBS: 0.1499484431237521
Fold 5 IBS: 0.2582856764364099
[I 2024-04-14 19:38:48,958] Trial 20 finished with value: 0.18338855229673945 and parameters: {'l1_ratio': 0.1423518953289899}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15576772887716966
Fold 2 IBS: 0.20382331096111436
Fold 3 IBS: 0.14924568898553875
Fold 4 IBS: 0.14995353556533214
Fold 5 IBS: 0.2583243572291732
[I 2024-04-14 19:38:49,959] Trial 21 finished with value: 0.18342292432366558 and parameters: {'l1_ratio': 0.15851211780160945}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.21323440578670969
Fold 2 IBS: 0.2211578410336095
Fold 3 IBS: 0.20350919884756077
Fold 4 IBS: 0.22333773453211395
Fold 5 IBS: 0.2583584900686643
[I 2024-04-14 19:38:50,495] Trial 22 finished with value: 0.2239195340537316 and parameters: {'l1_ratio': 0.017642396239323233}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15574575136974173
Fold 2 IBS: 0.2037548412828985
Fold 3 IBS: 0.14921707955733088
Fold 4 IBS: 0.14998676395146007
Fold 5 IBS: 0.25844172572657503
[I 2024-04-14 19:38:51,752] Trial 23 finished with value: 0.18342923237760123 and parameters: {'l1_ratio': 0.11584529180573493}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15584578108499492
Fold 2 IBS: 0.20363137878048446
Fold 3 IBS: 0.1492743918977784
Fold 4 IBS: 0.14997039522219519
Fold 5 IBS: 0.2583455776300846
[I 2024-04-14 19:38:52,597] Trial 24 finished with value: 0.18341350492310748 and parameters: {'l1_ratio': 0.32801060112613456}. Best is trial 20 with value: 0.18338855229673945.

Fold 1 IBS: 0.15577733180113215
Fold 2 IBS: 0.20379916407629925
Fold 3 IBS: 0.14925543189757615
Fold 4 IBS: 0.14995672855687775
Fold 5 IBS: 0.25835503611862165
[I 2024-04-14 19:38:53,712] Trial 25 finished with value: 0.18342873849010138 and parameters: {'l1_ratio': 0.17588003272672872}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15593227509866808
Fold 2 IBS: 0.2034241332673039
Fold 3 IBS: 0.1493537500026694
Fold 4 IBS: 0.14997183886083232
Fold 5 IBS: 0.258367389632833
[I 2024-04-14 19:38:54,706] Trial 26 finished with value: 0.18340987737246134 and parameters: {'l1_ratio': 0.5552319424045261}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1557499836690634
Fold 2 IBS: 0.20378366477860374
Fold 3 IBS: 0.1492561074293218
Fold 4 IBS: 0.14998282474592273
Fold 5 IBS: 0.25840110329481447
[I 2024-04-14 19:38:55,896] Trial 27 finished with value: 0.18343473678354522 and parameters: {'l1_ratio': 0.09486155085202524}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15583314063018197
Fold 2 IBS: 0.20365510135869136
Fold 3 IBS: 0.14926429452486586
Fold 4 IBS: 0.1499711267564603
Fold 5 IBS: 0.25832110807480474
[I 2024-04-14 19:38:56,867] Trial 28 finished with value: 0.18340895426900086 and parameters: {'l1_ratio': 0.2971200597851562}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.21329462490971163
Fold 2 IBS: 0.22119130824194871
Fold 3 IBS: 0.20359234470129114
Fold 4 IBS: 0.22345128700784309
Fold 5 IBS: 0.25837178135557415
[I 2024-04-14 19:38:57,480] Trial 29 finished with value: 0.22398026924327374 and parameters: {'l1_ratio': 0.016175696683504215}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15586799559154701
Fold 2 IBS: 0.2036651912575384
Fold 3 IBS: 0.14931246900743725
Fold 4 IBS: 0.14994372328846145
Fold 5 IBS: 0.2584789996762911
[I 2024-04-14 19:38:58,406] Trial 30 finished with value: 0.18345367576425503 and parameters: {'l1_ratio': 0.37920157808076954}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15582834724925793
Fold 2 IBS: 0.2036210141602969
Fold 3 IBS: 0.14927609231285227
Fold 4 IBS: 0.1499876894538338
Fold 5 IBS: 0.25838243393993426
[I 2024-04-14 19:38:59,226] Trial 31 finished with value: 0.18341911542323502 and parameters: {'l1_ratio': 0.27896453916563607}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15580022454185705
Fold 2 IBS: 0.20366377138850097
Fold 3 IBS: 0.14925690780166592
Fold 4 IBS: 0.14994698244385204
Fold 5 IBS: 0.2583419482536246
[I 2024-04-14 19:39:00,111] Trial 32 finished with value: 0.1834019668859001 and parameters: {'l1_ratio': 0.2095216872782623}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15578842830153408
Fold 2 IBS: 0.20371061423132236
Fold 3 IBS: 0.14923797532479652
Fold 4 IBS: 0.14998279473200257
Fold 5 IBS: 0.258276128321278
[I 2024-04-14 19:39:01,218] Trial 33 finished with value: 0.18339918818218673 and parameters: {'l1_ratio': 0.18615282992049867}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15577176421290118
Fold 2 IBS: 0.20369701155072142
Fold 3 IBS: 0.14924239746434378
Fold 4 IBS: 0.14994610310429346
Fold 5 IBS: 0.25830292121327303
[I 2024-04-14 19:39:01,946] Trial 34 finished with value: 0.18339203950910657 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15575427353927898
Fold 2 IBS: 0.2037997958706089
Fold 3 IBS: 0.1492512683673749
Fold 4 IBS: 0.14997314142713544
Fold 5 IBS: 0.2583729812651386
[I 2024-04-14 19:39:02,854] Trial 35 finished with value: 0.18343029209390735 and parameters: {'l1_ratio': 0.1124492938815673}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15573436657656425
Fold 2 IBS: 0.20382784066430323
Fold 3 IBS: 0.14923792784539103
Fold 4 IBS: 0.149976586631437
Fold 5 IBS: 0.2583446522294691
[I 2024-04-14 19:39:03,777] Trial 36 finished with value: 0.18342427478943293 and parameters: {'l1_ratio': 0.06400764935532122}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1558967923573674
Fold 2 IBS: 0.20349952186594109
Fold 3 IBS: 0.14932656071343783
Fold 4 IBS: 0.14997915956167798
Fold 5 IBS: 0.25849489737394626
[I 2024-04-14 19:39:04,529] Trial 37 finished with value: 0.1834393863744741 and parameters: {'l1_ratio': 0.4544709824843894}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1559347451303693
Fold 2 IBS: 0.20352658840408683
Fold 3 IBS: 0.14936286967394197
Fold 4 IBS: 0.14997862330299344
Fold 5 IBS: 0.2584056908221546
[I 2024-04-14 19:39:05,194] Trial 38 finished with value: 0.1834417034667092 and parameters: {'l1_ratio': 0.5638551523074651}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1557767576879577
Fold 2 IBS: 0.20372165568230738
Fold 3 IBS: 0.1492321090909767
Fold 4 IBS: 0.14998743476013834
Fold 5 IBS: 0.2582699173457584
[I 2024-04-14 19:39:05,931] Trial 39 finished with value: 0.1833975749134277 and parameters: {'l1_ratio': 0.15486970537243167}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1558226086483556
Fold 2 IBS: 0.20366860684500282
Fold 3 IBS: 0.14925805101815573
Fold 4 IBS: 0.14997401213658354
Fold 5 IBS: 0.2583105636890924
[I 2024-04-14 19:39:06,724] Trial 40 finished with value: 0.183406768467438 and parameters: {'l1_ratio': 0.2705989592091768}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1557905344091982
Fold 2 IBS: 0.2037422663841641
Fold 3 IBS: 0.14927704046594772
Fold 4 IBS: 0.14996898312489426
Fold 5 IBS: 0.2584319172562683
[I 2024-04-14 19:39:07,585] Trial 41 finished with value: 0.18344214832809452 and parameters: {'l1_ratio': 0.19914364599736756}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1557694811582906
Fold 2 IBS: 0.20377814564276825
Fold 3 IBS: 0.14926139209642528
Fold 4 IBS: 0.1499705783615814
Fold 5 IBS: 0.2583934453016945
[I 2024-04-14 19:39:09,335] Trial 42 finished with value: 0.18343460851215201 and parameters: {'l1_ratio': 0.1492560051574724}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15572050459317852
Fold 2 IBS: 0.20379111879949569
Fold 3 IBS: 0.1492512698887495
Fold 4 IBS: 0.14998926082035974
Fold 5 IBS: 0.2584034154023656
[I 2024-04-14 19:39:10,707] Trial 43 finished with value: 0.18343111390082978 and parameters: {'l1_ratio': 0.05986467498849006}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1560063137589114
Fold 2 IBS: 0.20330052983262073
Fold 3 IBS: 0.14939798322675926
Fold 4 IBS: 0.1499845969745628
Fold 5 IBS: 0.2586077708651151
[I 2024-04-14 19:39:11,454] Trial 44 finished with value: 0.18345943893159386 and parameters: {'l1_ratio': 0.7906814170029204}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1557835118707029
Fold 2 IBS: 0.2037064735186497
Fold 3 IBS: 0.14923878716059516
Fold 4 IBS: 0.14998819287577145
Fold 5 IBS: 0.25828845179660087
[I 2024-04-14 19:39:12,626] Trial 45 finished with value: 0.183401083444464 and parameters: {'l1_ratio': 0.17092332278727848}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1558539148780302
Fold 2 IBS: 0.20369506119214298
Fold 3 IBS: 0.14930069704236967
Fold 4 IBS: 0.14999024051118645
Fold 5 IBS: 0.25844978052406126
[I 2024-04-14 19:39:13,631] Trial 46 finished with value: 0.18345793882955813 and parameters: {'l1_ratio': 0.34291267707472417}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15580766768502927
Fold 2 IBS: 0.20372440519538415
Fold 3 IBS: 0.14928544554384432
Fold 4 IBS: 0.14996374542241206
Fold 5 IBS: 0.25844446888517436
[I 2024-04-14 19:39:14,861] Trial 47 finished with value: 0.18344514654636884 and parameters: {'l1_ratio': 0.23971145636476637}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15573602106486217
Fold 2 IBS: 0.20384899820580285
Fold 3 IBS: 0.14923087006198274
Fold 4 IBS: 0.14996685979761454
Fold 5 IBS: 0.2583095090214919
[I 2024-04-14 19:39:15,914] Trial 48 finished with value: 0.18341845163035084 and parameters: {'l1_ratio': 0.07576619298975869}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1557519656668267
Fold 2 IBS: 0.20373976060972468
Fold 3 IBS: 0.14922362623581362
Fold 4 IBS: 0.14998850456430507

Fold 5 IBS: 0.25827441995750067
[I 2024-04-14 19:39:16,914] Trial 49 finished with value: 0.18339565540683417 and parameters: {'l1_ratio': 0.12800717752404614}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1559506098053721
Fold 2 IBS: 0.20340059121058518
Fold 3 IBS: 0.14936286253930137
Fold 4 IBS: 0.14996377611498785
Fold 5 IBS: 0.25856927039958344
[I 2024-04-14 19:39:17,671] Trial 50 finished with value: 0.18344942201396602 and parameters: {'l1_ratio': 0.6064718647459368}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15576156555090212
Fold 2 IBS: 0.20380449209393783
Fold 3 IBS: 0.1492509630045684
Fold 4 IBS: 0.14996600991812406
Fold 5 IBS: 0.258359822482897
[I 2024-04-14 19:39:18,517] Trial 51 finished with value: 0.18342857061008588 and parameters: {'l1_ratio': 0.13419493306849467}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15578899165132407
Fold 2 IBS: 0.20370609452211966
Fold 3 IBS: 0.1492397213464959
Fold 4 IBS: 0.14998412861997532
Fold 5 IBS: 0.2582831313445645
[I 2024-04-14 19:39:19,347] Trial 52 finished with value: 0.1834004134968959 and parameters: {'l1_ratio': 0.18670313432961141}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1558089713289535
Fold 2 IBS: 0.20371449798564392
Fold 3 IBS: 0.14928899672752668
Fold 4 IBS: 0.14996662793181625
Fold 5 IBS: 0.2584585267659898
[I 2024-04-14 19:39:20,393] Trial 53 finished with value: 0.18344752414798604 and parameters: {'l1_ratio': 0.2412139378963527}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.21198119977272017
Fold 2 IBS: 0.20379494735596548
Fold 3 IBS: 0.14924922382938025
Fold 4 IBS: 0.14999056147624618
Fold 5 IBS: 0.2584004210036399
[I 2024-04-14 19:39:21,259] Trial 54 finished with value: 0.19468327068759042 and parameters: {'l1_ratio': 0.049710484522964365}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15575153796718177
Fold 2 IBS: 0.20379543422141436
Fold 3 IBS: 0.1492522902285724
Fold 4 IBS: 0.14997696924964551
Fold 5 IBS: 0.25838114388305855
[I 2024-04-14 19:39:22,291] Trial 55 finished with value: 0.1834314751099745 and parameters: {'l1_ratio': 0.10303941107874341}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15584356201547359
Fold 2 IBS: 0.20370037878819028
Fold 3 IBS: 0.14929751737478916
Fold 4 IBS: 0.14995092742683536
Fold 5 IBS: 0.2584529237448296
[I 2024-04-14 19:39:23,036] Trial 56 finished with value: 0.1834490618700236 and parameters: {'l1_ratio': 0.31434375129697084}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.21370793277713512
Fold 2 IBS: 0.22142417063305755
Fold 3 IBS: 0.2041640228435366
Fold 4 IBS: 0.22423097794946661
Fold 5 IBS: 0.21806949186048394
[I 2024-04-14 19:39:23,288] Trial 57 finished with value: 0.216319319212736 and parameters: {'l1_ratio': 0.00626942071754627}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15577295184162926
Fold 2 IBS: 0.20375086755999267
Fold 3 IBS: 0.1492713695843009
Fold 4 IBS: 0.14997872721086566
Fold 5 IBS: 0.25843417453003104
[I 2024-04-14 19:39:23,982] Trial 58 finished with value: 0.18344161814536392 and parameters: {'l1_ratio': 0.15192623956115894}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15587906000389287
Fold 2 IBS: 0.20354011104582403
Fold 3 IBS: 0.14931061626297198
Fold 4 IBS: 0.1499783454635224
Fold 5 IBS: 0.25845170431931297
[I 2024-04-14 19:39:24,567] Trial 59 finished with value: 0.18343196741910484 and parameters: {'l1_ratio': 0.4091948126121967}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1558609340592013
Fold 2 IBS: 0.2035943229528476
Fold 3 IBS: 0.14928940954432687
Fold 4 IBS: 0.149972523412601
Fold 5 IBS: 0.25838796032831185
[I 2024-04-14 19:39:25,138] Trial 60 finished with value: 0.18342103005945773 and parameters: {'l1_ratio': 0.3646848571309331}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.155784624556773
Fold 2 IBS: 0.20378960052161374
Fold 3 IBS: 0.14925988616899905
Fold 4 IBS: 0.14995513522324627
Fold 5 IBS: 0.2583637552497283
[I 2024-04-14 19:39:25,887] Trial 61 finished with value: 0.18343060034407205 and parameters: {'l1_ratio': 0.19325889604358418}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15578139372040056
Fold 2 IBS: 0.20376693984926825
Fold 3 IBS: 0.14926716410476426
Fold 4 IBS: 0.14996617606320273
Fold 5 IBS: 0.25840065792439476
[I 2024-04-14 19:39:26,525] Trial 62 finished with value: 0.1834364663324061 and parameters: {'l1_ratio': 0.1795195929804743}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1558172164668176
Fold 2 IBS: 0.20371355147448864
Fold 3 IBS: 0.14929043362140773
Fold 4 IBS: 0.14996104818166525
Fold 5 IBS: 0.2584523034146357
[I 2024-04-14 19:39:27,123] Trial 63 finished with value: 0.183446910631803 and parameters: {'l1_ratio': 0.2630534260085968}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15580117059486442
Fold 2 IBS: 0.20370992983882577
Fold 3 IBS: 0.14928961805239593
Fold 4 IBS: 0.149973456170789
Fold 5 IBS: 0.25827475050220344
[I 2024-04-14 19:39:27,719] Trial 64 finished with value: 0.1834097850318157 and parameters: {'l1_ratio': 0.22183266059344736}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15574829163357679
Fold 2 IBS: 0.2037966333956865
Fold 3 IBS: 0.1492513070237359
Fold 4 IBS: 0.1499788890003805
Fold 5 IBS: 0.258381951961939
[I 2024-04-14 19:39:28,455] Trial 65 finished with value: 0.18343141460306372 and parameters: {'l1_ratio': 0.09405034481579448}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1557804454865891
Fold 2 IBS: 0.20373088334476958
Fold 3 IBS: 0.14922932468829048
Fold 4 IBS: 0.14998095397887168
Fold 5 IBS: 0.25827488868245874
[I 2024-04-14 19:39:29,111] Trial 66 finished with value: 0.1833992992361959 and parameters: {'l1_ratio': 0.16820756800241202}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15575366711968575
Fold 2 IBS: 0.20383340047168272
Fold 3 IBS: 0.1492395207991231
Fold 4 IBS: 0.14996024680330056
Fold 5 IBS: 0.2583203089493079
[I 2024-04-14 19:39:29,806] Trial 67 finished with value: 0.18342142882862 and parameters: {'l1_ratio': 0.12039637319943594}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15576812198624987
Fold 2 IBS: 0.20375334580898916
Fold 3 IBS: 0.1492697382438792
Fold 4 IBS: 0.14998135879176797
Fold 5 IBS: 0.25823547344179726
[I 2024-04-14 19:39:30,442] Trial 68 finished with value: 0.1834016076545367 and parameters: {'l1_ratio': 0.1387391900546993}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.21191410815121156
Fold 2 IBS: 0.20387928689012916
Fold 3 IBS: 0.14921794763854568
Fold 4 IBS: 0.1499634216539744
Fold 5 IBS: 0.2582701140074118
[I 2024-04-14 19:39:31,071] Trial 69 finished with value: 0.1946489756682545 and parameters: {'l1_ratio': 0.05151617560740002}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15580172874956572
Fold 2 IBS: 0.20375622605224003
Fold 3 IBS: 0.1492740235585164
Fold 4 IBS: 0.14995459390822927
Fold 5 IBS: 0.2583980733925219
[I 2024-04-14 19:39:31,875] Trial 70 finished with value: 0.18343692913221465 and parameters: {'l1_ratio': 0.23498298021944547}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15577880735781205
Fold 2 IBS: 0.20378747658848254
Fold 3 IBS: 0.1492596895691118
Fold 4 IBS: 0.14996008373667327
Fold 5 IBS: 0.2583720216960297
[I 2024-04-14 19:39:32,518] Trial 71 finished with value: 0.18343161578962186 and parameters: {'l1_ratio': 0.17718671969605376}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15578573217890054
Fold 2 IBS: 0.20377243435085682
Fold 3 IBS: 0.1492661134217644
Fold 4 IBS: 0.14996008802554453
Fold 5 IBS: 0.2583874260403338
[I 2024-04-14 19:39:33,131] Trial 72 finished with value: 0.18343435880348002 and parameters: {'l1_ratio': 0.19536143239126275}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15582919564015235
Fold 2 IBS: 0.20368843744671147
Fold 3 IBS: 0.14930051704962918
Fold 4 IBS: 0.1499615916716544
Fold 5 IBS: 0.25828176295490674
[I 2024-04-14 19:39:33,721] Trial 73 finished with value: 0.18341230095261082 and parameters: {'l1_ratio': 0.29099637885547636}. Best is trial 20 with value: 0.18338855229673945.

Fold 1 IBS: 0.155770270853787
Fold 2 IBS: 0.2038112348603604
Fold 3 IBS: 0.14925011059126453
Fold 4 IBS: 0.1499571439080442
Fold 5 IBS: 0.2583420369748923
[I 2024-04-14 19:39:34,469] Trial 74 finished with value: 0.18342615943766968 and parameters: {'l1_ratio': 0.15972883385367564}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1557419327917984
Fold 2 IBS: 0.20382367358834794
Fold 3 IBS: 0.14924077240178815
Fold 4 IBS: 0.1499727299623822
Fold 5 IBS: 0.2583452614865245
[I 2024-04-14 19:39:35,153] Trial 75 finished with value: 0.18342487404616822 and parameters: {'l1_ratio': 0.08437435159842996}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1557574196299789
Fold 2 IBS: 0.20380442913464988
Fold 3 IBS: 0.14925020504696107
Fold 4 IBS: 0.14996898997211272
Fold 5 IBS: 0.25836304268220334
[I 2024-04-14 19:39:35,802] Trial 76 finished with value: 0.1834288172931812 and parameters: {'l1_ratio': 0.12266833298630989}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1560353319844586
Fold 2 IBS: 0.20321026934805225
Fold 3 IBS: 0.14942786205231945
Fold 4 IBS: 0.14998513255137258
Fold 5 IBS: 0.25868178893441646
[I 2024-04-14 19:39:36,373] Trial 77 finished with value: 0.18346807697412384 and parameters: {'l1_ratio': 0.8849752339534017}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15579152322383225
Fold 2 IBS: 0.20377938826442293
Fold 3 IBS: 0.14926462684651776
Fold 4 IBS: 0.14995325839616958
Fold 5 IBS: 0.25837272291117086
[I 2024-04-14 19:39:36,995] Trial 78 finished with value: 0.18343230392842266 and parameters: {'l1_ratio': 0.2123223081502063}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.21242951549282743
Fold 2 IBS: 0.20378889129473682
Fold 3 IBS: 0.1491988675723336
Fold 4 IBS: 0.22182094038699415
Fold 5 IBS: 0.2584126958464924
[I 2024-04-14 19:39:37,513] Trial 79 finished with value: 0.2091301821186769 and parameters: {'l1_ratio': 0.03788566593802617}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1558161586380566
Fold 2 IBS: 0.20372233493321995
Fold 3 IBS: 0.14928729969468124
Fold 4 IBS: 0.1499585095274326
Fold 5 IBS: 0.2584398990270279
[I 2024-04-14 19:39:38,109] Trial 80 finished with value: 0.18344484036408365 and parameters: {'l1_ratio': 0.2616172081569606}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.155778605108574
Fold 2 IBS: 0.20374549049206664
Fold 3 IBS: 0.14927411370935553
Fold 4 IBS: 0.1499766156278091
Fold 5 IBS: 0.2584375651134556
[I 2024-04-14 19:39:38,820] Trial 81 finished with value: 0.18344247801025218 and parameters: {'l1_ratio': 0.16661469402903906}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.1557840086894038
Fold 2 IBS: 0.20374611012064278
Fold 3 IBS: 0.14927473390373425
Fold 4 IBS: 0.14997234554271038
Fold 5 IBS: 0.2584317946313189
[I 2024-04-14 19:39:39,414] Trial 82 finished with value: 0.183441798577562 and parameters: {'l1_ratio': 0.1819349943089408}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15576731109151923
Fold 2 IBS: 0.20375969328245494
Fold 3 IBS: 0.1492674119609397
Fold 4 IBS: 0.1499794572275434
Fold 5 IBS: 0.25842529184630225
[I 2024-04-14 19:39:40,228] Trial 83 finished with value: 0.1834398330817519 and parameters: {'l1_ratio': 0.13816225644611677}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15574656085621202
Fold 2 IBS: 0.20374899847661632
Fold 3 IBS: 0.14921937034332175
Fold 4 IBS: 0.14998852420363923
Fold 5 IBS: 0.2582635679653585
[I 2024-04-14 19:39:40,925] Trial 84 finished with value: 0.18339340436902957 and parameters: {'l1_ratio': 0.11629671992988347}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15573660133859643
Fold 2 IBS: 0.20381098433607797
Fold 3 IBS: 0.1492442154583292
Fold 4 IBS: 0.14998175254480858
Fold 5 IBS: 0.2583687136820322
[I 2024-04-14 19:39:41,667] Trial 85 finished with value: 0.18342845347196887 and parameters: {'l1_ratio': 0.06472900797688938}. Best is trial 20 with value: 0.18338855229673945.
Fold 1 IBS: 0.15574289959687965
Fold 2 IBS: 0.20374834834583788
Fold 3 IBS: 0.14921903487119692
Fold 4 IBS: 0.14994685146781978
Fold 5 IBS: 0.2582678367863849
[I 2024-04-14 19:39:42,520] Trial 86 finished with value: 0.1833849942136238 and parameters: {'l1_ratio': 0.10632357947706075}. Best is trial 86 with value: 0.1833849942136238.
Fold 1 IBS: 0.15573887477259646
Fold 2 IBS: 0.20375277368044192
Fold 3 IBS: 0.14921675161676784
Fold 4 IBS: 0.1499479516683372
Fold 5 IBS: 0.2582638196974307
[I 2024-04-14 19:39:43,447] Trial 87 finished with value: 0.18338403428711483 and parameters: {'l1_ratio': 0.09684969311230943}. Best is trial 87 with value: 0.18338403428711483.
Fold 1 IBS: 0.15574990365181854
Fold 2 IBS: 0.20380723062526393
Fold 3 IBS: 0.1492479278231253
Fold 4 IBS: 0.14997339461722806
Fold 5 IBS: 0.25836483006525846
[I 2024-04-14 19:39:44,195] Trial 88 finished with value: 0.18342865735653885 and parameters: {'l1_ratio': 0.10224464259508911}. Best is trial 87 with value: 0.18338403428711483.
Fold 1 IBS: 0.15572996950002735
Fold 2 IBS: 0.20375588442607562
Fold 3 IBS: 0.14921414346900794
Fold 4 IBS: 0.14995323296371982
Fold 5 IBS: 0.25826616544212616
[I 2024-04-14 19:39:45,028] Trial 89 finished with value: 0.1833838791601914 and parameters: {'l1_ratio': 0.07359843376418071}. Best is trial 89 with value: 0.1833838791601914.
Fold 1 IBS: 0.21274810244784795
Fold 2 IBS: 0.2038753665249399
Fold 3 IBS: 0.14921787951283644
Fold 4 IBS: 0.22242112666182298
Fold 5 IBS: 0.25828176381006374
[I 2024-04-14 19:39:45,686] Trial 90 finished with value: 0.20930884779150222 and parameters: {'l1_ratio': 0.029727146621198505}. Best is trial 89 with value: 0.1833838791601914.
Fold 1 IBS: 0.1557331618984166
Fold 2 IBS: 0.20375138334342008
Fold 3 IBS: 0.14921634181963098
Fold 4 IBS: 0.14995278988807065
Fold 5 IBS: 0.2582471364809873
[I 2024-04-14 19:39:46,679] Trial 91 finished with value: 0.18338016268610513 and parameters: {'l1_ratio': 0.08085767241718195}. Best is trial 91 with value: 0.18338016268610513.
Fold 1 IBS: 0.15572938080956836
Fold 2 IBS: 0.20377808366336267
Fold 3 IBS: 0.14920574676927073
Fold 4 IBS: 0.14998850893124419
Fold 5 IBS: 0.25841742801912265
[I 2024-04-14 19:39:47,472] Trial 92 finished with value: 0.1834238296385137 and parameters: {'l1_ratio': 0.07940734840231775}. Best is trial 91 with value: 0.18338016268610513.
Fold 1 IBS: 0.15574727178931516
Fold 2 IBS: 0.2037438630266394
Fold 3 IBS: 0.14922138324149495
Fold 4 IBS: 0.14999007069205877
Fold 5 IBS: 0.25827161324411285
[I 2024-04-14 19:39:48,285] Trial 93 finished with value: 0.18339484039872425 and parameters: {'l1_ratio': 0.11669578529426201}. Best is trial 91 with value: 0.18338016268610513.
Fold 1 IBS: 0.21354880300373746
Fold 2 IBS: 0.22133379218456828
Fold 3 IBS: 0.203943619274544
Fold 4 IBS: 0.2239307169486995
Fold 5 IBS: 0.2180373391186634
[I 2024-04-14 19:39:48,511] Trial 94 finished with value: 0.2161588541060425 and parameters: {'l1_ratio': 0.010054556527488337}. Best is trial 91 with value: 0.18338016268610513.
Fold 1 IBS: 0.1557536740440776
Fold 2 IBS: 0.2038044160990985
Fold 3 IBS: 0.1492495629541694
Fold 4 IBS: 0.14997174492033263
Fold 5 IBS: 0.2583661720108683
[I 2024-04-14 19:39:49,250] Trial 95 finished with value: 0.1834291140057093 and parameters: {'l1_ratio': 0.11211062027912054}. Best is trial 91 with value: 0.18338016268610513.
Fold 1 IBS: 0.21268603256610363
Fold 2 IBS: 0.20379857906260862
Fold 3 IBS: 0.14919459806912896
Fold 4 IBS: 0.22230417762267327
Fold 5 IBS: 0.258399930527199
[I 2024-04-14 19:39:49,891] Trial 96 finished with value: 0.20927666356954272 and parameters: {'l1_ratio': 0.03130126720626662}. Best is trial 91 with value: 0.18338016268610513.
Fold 1 IBS: 0.15573804459462937
Fold 2 IBS: 0.203833704486332
Fold 3 IBS: 0.14923656945625802
Fold 4 IBS: 0.14997153880138128
Fold 5 IBS: 0.25833236285235145
[I 2024-04-14 19:39:50,960] Trial 97 finished with value: 0.1834224440381904 and parameters: {'l1_ratio': 0.07652911995809211}. Best is trial 91 with value: 0.18338016268610513.
Fold 1 IBS: 0.15574668360525826
Fold 2 IBS: 0.20380893426069813
Fold 3 IBS: 0.14924674962163134
Fold 4 IBS: 0.14997515226095015

Fold 5 IBS: 0.25836485244918367
[I 2024-04-14 19:39:52,534] Trial 98 finished with value: 0.1834284744395443 and parameters: {'l1_ratio': 0.09329088990333982}. Best is trial 91 with value: 0.18338016268610513.
Fold 1 IBS: 0.15575909807747473
Fold 2 IBS: 0.20382343894822838
Fold 3 IBS: 0.14924391721221436
Fold 4 IBS: 0.14996024903228422
Fold 5 IBS: 0.2583316574046228
[I 2024-04-14 19:39:53,690] Trial 99 finished with value: 0.1834236721349649 and parameters: {'l1_ratio': 0.13255336571837883}. Best is trial 91 with value: 0.18338016268610513.


* Best trial for IBS:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.18338016268610513], datetime_start=datetime.datetime(2024, 4, 14, 19, 39, 45, 691359), datetime_complete=datetime.datetime(2024, 4, 14, 19, 39, 46, 675796), params={'l1_ratio': 0.08085767241718195}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=91, value=None)


* Best Score for IBS:
 0.18338016268610513

In [44]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [45]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.743
train_ibs:  0.183

#### Test

In [46]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [47]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.980766121964777)

test_cindex : 0.583

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.08085767241718195)

test_ibs:  0.261

In [48]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [49]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 19:39:54,306] A new study created in memory with name: no-name-9cb1aab7-4e3d-4e44-97d6-aeb4860e172d

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 19:39:59,757] Trial 0 finished with value: 0.7331704503062509 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7331704503062509.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6808035714285714
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:40:03,652] Trial 1 finished with value: 0.7418310764029108 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7418310764029108.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 19:40:07,138] Trial 2 finished with value: 0.7379384522573516 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.7418310764029108.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:40:08,345] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.7418310764029108.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:40:10,108] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.7418310764029108.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6450892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:40:16,331] Trial 5 finished with value: 0.7345418867193549 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 1 with value: 0.7418310764029108.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 19:40:22,257] Trial 6 finished with value: 0.7338631373066578 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 1 with value: 0.7418310764029108.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:40:25,163] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 1 with value: 0.7418310764029108.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 19:40:33,962] Trial 8 finished with value: 0.5225352112676056 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 1 with value: 0.7418310764029108.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6450892857142857
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:40:38,933] Trial 9 finished with value: 0.7344053764190323 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 1 with value: 0.7418310764029108.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:40:39,640] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 1 with value: 0.7418310764029108.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:40:42,491] Trial 11 finished with value: 0.7424488479649303 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.9250608990121825, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1579906038170908, 'warm_start': False}. Best is trial 11 with value: 0.7424488479649303.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6986607142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 19:40:45,298] Trial 12 finished with value: 0.7413441979127182 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.8206827027986038, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13254323337687263, 'warm_start': False}. Best is trial 11 with value: 0.7424488479649303.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 19:40:48,061] Trial 13 finished with value: 0.734036251172052 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 133, 'oob_score': False, 'max_samples': 0.7775116009432976, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12513018019176592, 'warm_start': False}. Best is trial 11 with value: 0.7424488479649303.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 19:40:48,696] Trial 14 finished with value: 0.7558530252568458 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 24, 'oob_score': True, 'max_samples': 0.9813960031366438, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17965973103920196, 'warm_start': True}. Best is trial 14 with value: 0.7558530252568458.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8137254901960784

Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 19:40:49,414] Trial 15 finished with value: 0.7438195723110067 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 27, 'oob_score': True, 'max_samples': 0.9916308141555894, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2038091856577342, 'warm_start': True}. Best is trial 14 with value: 0.7558530252568458.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 19:40:49,756] Trial 16 finished with value: 0.759486772674677 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 4, 'oob_score': True, 'max_samples': 0.963206401785182, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3769624693898471, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:40:50,078] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 4, 'oob_score': True, 'max_samples': 0.8329573156617618, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4008311644348986, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:40:51,196] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 85, 'oob_score': True, 'max_samples': 0.47391133230646465, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4020665653496426, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 19:40:52,332] Trial 19 finished with value: 0.759486772674677 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 90, 'oob_score': True, 'max_samples': 0.9921798679470297, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.46346901790248546, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:40:53,481] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.8574334183065578, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4896330430869841, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7254464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 19:40:53,953] Trial 21 finished with value: 0.6934464087544288 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 1, 'oob_score': True, 'max_samples': 0.9633491027812254, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4261304054731167, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:40:54,763] Trial 22 finished with value: 0.7349357922961401 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 4, 'n_estimators': 53, 'oob_score': True, 'max_samples': 0.99250387101638, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4434337597091712, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 19:40:56,860] Trial 23 finished with value: 0.7537983845785513 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.8789049992214865, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.36029972130711063, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 19:40:58,077] Trial 24 finished with value: 0.7537983845785513 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 6, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.7237939945566421, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2725759062495923, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:40:58,756] Trial 25 finished with value: 0.7349357922961401 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 42, 'oob_score': True, 'max_samples': 0.9877117183420746, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4599057696289769, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 19:40:59,991] Trial 26 finished with value: 0.759486772674677 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 116, 'oob_score': True, 'max_samples': 0.8023553778463413, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3621577705261356, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:41:02,257] Trial 27 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 14, 'n_estimators': 221, 'oob_score': True, 'max_samples': 0.66806796151318, 'max_features': None, 'min_weight_fraction_leaf': 0.3764724626650927, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 19:41:03,600] Trial 28 finished with value: 0.7537983845785513 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 129, 'oob_score': True, 'max_samples': 0.8120930081506583, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.32865371629032114, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 19:41:04,410] Trial 29 finished with value: 0.7537983845785513 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 13, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.8897315800713117, 'max_features': None, 'min_weight_fraction_leaf': 0.39230357940953764, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801

Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 19:41:05,978] Trial 30 finished with value: 0.7465362511720519 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 180, 'oob_score': True, 'max_samples': 0.6961599111587151, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2262327581176415, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:41:06,529] Trial 31 finished with value: 0.7349357922961401 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 26, 'oob_score': True, 'max_samples': 0.9351480862025267, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.45180415400387103, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 19:41:07,466] Trial 32 finished with value: 0.7465362511720519 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 67, 'oob_score': True, 'max_samples': 0.7750602970780608, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.19946128153618847, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 19:41:08,662] Trial 33 finished with value: 0.7537983845785513 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 108, 'oob_score': True, 'max_samples': 0.904598278080337, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2886071113440874, 'warm_start': True}. Best is trial 16 with value: 0.759486772674677.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 19:41:09,039] Trial 34 finished with value: 0.761356973379799 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 18, 'oob_score': True, 'max_samples': 0.8593654200136214, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3531212123048779, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 19:41:11,101] Trial 35 finished with value: 0.7537983845785513 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 238, 'oob_score': True, 'max_samples': 0.7404879344210553, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.343035504953959, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:41:12,531] Trial 36 finished with value: 0.5 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 139, 'oob_score': True, 'max_samples': 0.8584237819092821, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42460235628506837, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 19:41:13,650] Trial 37 finished with value: 0.7537983845785513 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 5, 'n_estimators': 92, 'oob_score': True, 'max_samples': 0.786858086813807, 'max_features': None, 'min_weight_fraction_leaf': 0.37086369027970506, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:41:14,379] Trial 38 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 52, 'oob_score': True, 'max_samples': 0.4603478379387248, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3248016924945531, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:41:17,812] Trial 39 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 366, 'oob_score': True, 'max_samples': 0.557809593420317, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4722027681725063, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 19:41:23,491] Trial 40 finished with value: 0.7537983845785513 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 6, 'n_estimators': 497, 'oob_score': True, 'max_samples': 0.9374719555021139, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3501609303990359, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 19:41:23,969] Trial 41 finished with value: 0.7446853731768076 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 27, 'oob_score': True, 'max_samples': 0.9997621190375989, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24204027236563277, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 19:41:24,569] Trial 42 finished with value: 0.7547834617079947 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 25, 'oob_score': True, 'max_samples': 0.9022831983250785, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09372912390737731, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 19:41:25,194] Trial 43 finished with value: 0.7446853731768076 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 17, 'oob_score': True, 'max_samples': 0.9547992033037935, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.303233393814669, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 19:41:26,644] Trial 44 finished with value: 0.7556492625737956 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 4, 'n_estimators': 58, 'oob_score': True, 'max_samples': 0.8499888326690761, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17875687755892225, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:41:26,916] Trial 45 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 1, 'oob_score': False, 'max_samples': 0.8994612932002628, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.41528932779202743, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.

Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 19:41:29,420] Trial 46 finished with value: 0.7367418788776796 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.9469136308003847, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08451392510353656, 'warm_start': False}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:41:29,817] Trial 47 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 41, 'oob_score': False, 'max_samples': 0.34782177830462335, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2595813339569079, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 19:41:32,062] Trial 48 finished with value: 0.755565204047226 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 92, 'oob_score': True, 'max_samples': 0.7922619769630517, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38369267838589155, 'warm_start': False}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 19:41:33,960] Trial 49 finished with value: 0.7529900138551021 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 205, 'oob_score': True, 'max_samples': 0.6409304439956861, 'max_features': None, 'min_weight_fraction_leaf': 0.15134617591787042, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:41:35,722] Trial 50 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 5, 'n_estimators': 326, 'oob_score': False, 'max_samples': 0.1200736185519305, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27943476819749063, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 19:41:36,442] Trial 51 finished with value: 0.7465362511720519 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 4, 'n_estimators': 63, 'oob_score': True, 'max_samples': 0.8458270116342224, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.19310157737710282, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 19:41:37,032] Trial 52 finished with value: 0.7547834617079947 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 42, 'oob_score': True, 'max_samples': 0.8507019813193493, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1808663218628661, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 19:41:37,884] Trial 53 finished with value: 0.7520587802861303 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 73, 'oob_score': True, 'max_samples': 0.9679111167279874, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17295394725107877, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 19:41:38,384] Trial 54 finished with value: 0.746628471158638 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 16, 'max_depth': 4, 'n_estimators': 13, 'oob_score': True, 'max_samples': 0.9283004136977027, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22799683925880057, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:41:39,912] Trial 55 finished with value: 0.5 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 161, 'oob_score': True, 'max_samples': 0.8780579878617739, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49861627174233597, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 19:41:41,408] Trial 56 finished with value: 0.736060517985051 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 57, 'oob_score': True, 'max_samples': 0.8290506761239742, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14164122045469035, 'warm_start': False}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:41:44,436] Trial 57 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 99, 'oob_score': True, 'max_samples': 0.7449756055418523, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.435624877164536, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 19:41:44,990] Trial 58 finished with value: 0.7558530252568458 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 30, 'oob_score': True, 'max_samples': 0.9713821605937195, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10056372049643875, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 19:41:45,647] Trial 59 finished with value: 0.7587525697121423 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 36, 'oob_score': False, 'max_samples': 0.9696024433843103, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03643237048087339, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.671875
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 19:41:48,270] Trial 60 finished with value: 0.7309581780774679 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 113, 'oob_score': False, 'max_samples': 0.9694253886674298, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04495926077068571, 'warm_start': False}. Best is trial 34 with value: 0.761356973379799.

Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 19:41:48,955] Trial 61 finished with value: 0.759330842764341 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 36, 'oob_score': False, 'max_samples': 0.9235579938038777, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.009200599621329394, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:41:49,338] Trial 62 finished with value: 0.7611817207595855 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 12, 'oob_score': False, 'max_samples': 0.920841981519704, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0076381811472743845, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6584821428571429
Fold 3 C-index: 0.8308823529411765
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 19:41:49,642] Trial 63 finished with value: 0.733555965721675 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.9159780159013478, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0333557271017943, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.8357843137254902
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 19:41:50,083] Trial 64 finished with value: 0.7564315475821604 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 40, 'oob_score': False, 'max_samples': 0.8095308987472059, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.007342641264516863, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:41:50,677] Trial 65 finished with value: 0.7596341067059411 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 86, 'oob_score': False, 'max_samples': 0.8928592506860374, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06540238651589841, 'warm_start': True}. Best is trial 34 with value: 0.761356973379799.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 19:41:52,549] Trial 66 finished with value: 0.761971037766798 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 276, 'oob_score': False, 'max_samples': 0.875525534108882, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05598038754628913, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:41:54,244] Trial 67 finished with value: 0.7596882192600536 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.8580921501948504, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07620913876610864, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:41:56,666] Trial 68 finished with value: 0.759541886719355 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 286, 'oob_score': False, 'max_samples': 0.869177820651192, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06587908562068191, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:41:58,423] Trial 69 finished with value: 0.759541886719355 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 273, 'oob_score': False, 'max_samples': 0.873529090347612, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06984084344596554, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 19:42:00,045] Trial 70 finished with value: 0.761971037766798 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 269, 'oob_score': False, 'max_samples': 0.8820171063200395, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0673901747723447, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:42:01,761] Trial 71 finished with value: 0.7597804392466398 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 275, 'oob_score': False, 'max_samples': 0.8822989725674244, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08124455460554207, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:42:03,476] Trial 72 finished with value: 0.7596882192600536 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 292, 'oob_score': False, 'max_samples': 0.7720551066614997, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06990219691156445, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:42:04,939] Trial 73 finished with value: 0.7597804392466398 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.7613588857743, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1179869524535094, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:42:06,054] Trial 74 finished with value: 0.7596882192600536 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.7167578977945623, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11891098596119909, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:42:07,408] Trial 75 finished with value: 0.7597804392466398 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 312, 'oob_score': False, 'max_samples': 0.7725108946207656, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10519254832032532, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.

Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7388392857142857
Fold 3 C-index: 0.8357843137254902
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 19:42:08,794] Trial 76 finished with value: 0.7519211518745815 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 313, 'oob_score': False, 'max_samples': 0.8220505788572211, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02499460437724283, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:42:10,025] Trial 77 finished with value: 0.7596882192600536 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.6728072298556524, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1058506154786779, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 19:42:11,824] Trial 78 finished with value: 0.7569635378381891 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 358, 'oob_score': False, 'max_samples': 0.7566207077388571, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1317336953631299, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:42:13,337] Trial 79 finished with value: 0.7597804392466398 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 241, 'oob_score': False, 'max_samples': 0.8293945673457133, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08524248823793595, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6450892857142857
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:42:21,622] Trial 80 finished with value: 0.7335614945624922 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 386, 'oob_score': False, 'max_samples': 0.8217977389156857, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0517177920739731, 'warm_start': False}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:42:22,770] Trial 81 finished with value: 0.7597804392466398 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 223, 'oob_score': False, 'max_samples': 0.8399947901043594, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08055091905376485, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7522321428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 19:42:24,041] Trial 82 finished with value: 0.7570557578247753 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.7663872412325988, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11433856368181138, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:42:25,119] Trial 83 finished with value: 0.7597804392466398 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 235, 'oob_score': False, 'max_samples': 0.7902705902143992, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09022602974283915, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 19:42:26,632] Trial 84 finished with value: 0.761971037766798 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 331, 'oob_score': False, 'max_samples': 0.8316950157003011, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.059067127483247016, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:42:27,911] Trial 85 finished with value: 0.7611817207595855 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.891821519703517, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.058138112465755704, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:42:29,275] Trial 86 finished with value: 0.7610294783037448 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.9110941034569532, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.020486414920423718, 'warm_start': True}. Best is trial 66 with value: 0.761971037766798.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7745535714285714
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 19:42:30,800] Trial 87 finished with value: 0.7675561382635033 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.9105043646354579, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.017319664815564358, 'warm_start': True}. Best is trial 87 with value: 0.7675561382635033.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 19:42:32,108] Trial 88 finished with value: 0.7638463797121954 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 335, 'oob_score': False, 'max_samples': 0.9097218792939679, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0217773467989361, 'warm_start': True}. Best is trial 87 with value: 0.7675561382635033.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:42:33,701] Trial 89 finished with value: 0.7610294783037448 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.9010084088906871, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.022429345676983223, 'warm_start': True}. Best is trial 87 with value: 0.7675561382635033.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8455882352941176
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 19:42:35,379] Trial 90 finished with value: 0.7676436732775089 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 383, 'oob_score': False, 'max_samples': 0.9468704007518776, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0019108636952937536, 'warm_start': True}. Best is trial 90 with value: 0.7676436732775089.

Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8455882352941176
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 19:42:37,180] Trial 91 finished with value: 0.7676436732775089 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 378, 'oob_score': False, 'max_samples': 0.9413238805942125, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0005122460718665865, 'warm_start': True}. Best is trial 90 with value: 0.7676436732775089.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 19:42:38,894] Trial 92 finished with value: 0.7678055586446316 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 386, 'oob_score': False, 'max_samples': 0.9384116837859996, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0048114797475199145, 'warm_start': True}. Best is trial 92 with value: 0.7678055586446316.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 19:42:40,798] Trial 93 finished with value: 0.7702347096920747 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 393, 'oob_score': False, 'max_samples': 0.939974221909062, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.010097497494874971, 'warm_start': True}. Best is trial 93 with value: 0.7702347096920747.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 19:42:42,357] Trial 94 finished with value: 0.7678055586446316 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.9549630702741684, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0020846992882196727, 'warm_start': True}. Best is trial 93 with value: 0.7702347096920747.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.8357843137254902
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 19:42:44,463] Trial 95 finished with value: 0.7564315475821604 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 406, 'oob_score': False, 'max_samples': 0.9545169393465973, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04198943168135364, 'warm_start': True}. Best is trial 93 with value: 0.7702347096920747.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 19:42:46,477] Trial 96 finished with value: 0.7678055586446316 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 438, 'oob_score': False, 'max_samples': 0.9403928798168232, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00010587722949467054, 'warm_start': True}. Best is trial 93 with value: 0.7702347096920747.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8357843137254902
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 19:42:49,259] Trial 97 finished with value: 0.768741208192543 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 445, 'oob_score': False, 'max_samples': 0.999363247843076, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0006706641568989577, 'warm_start': True}. Best is trial 93 with value: 0.7702347096920747.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 19:42:51,703] Trial 98 finished with value: 0.7688176920511312 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 446, 'oob_score': False, 'max_samples': 0.9429309479671992, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0006631695149465866, 'warm_start': True}. Best is trial 93 with value: 0.7702347096920747.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6361607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8122362869198312

[I 2024-04-14 19:42:59,534] A new study created in memory with name: no-name-e1015c8b-34dd-480e-b268-7562bf2cfba4

Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 19:42:59,518] Trial 99 finished with value: 0.7193082428152706 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.9977495771805275, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00163386282116997, 'warm_start': False}. Best is trial 93 with value: 0.7702347096920747.


* Best trial for C-index:
 FrozenTrial(number=93, state=TrialState.COMPLETE, values=[0.7702347096920747], datetime_start=datetime.datetime(2024, 4, 14, 19, 42, 38, 902765), datetime_complete=datetime.datetime(2024, 4, 14, 19, 42, 40, 797755), params={'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 393, 'oob_score': False, 'max_samples': 0.939974221909062, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.010097497494874971, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=93, value=None)


* Best Score for C-index:
 0.7702347096920747

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1721791040244176
Fold 2 IBS: 0.24981115406752974
Fold 3 IBS: 0.1683445849341811
Fold 4 IBS: 0.16146382394536785
Fold 5 IBS: 0.2391847197432734
[I 2024-04-14 19:43:06,027] Trial 0 finished with value: 0.19819667734295393 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.19819667734295393.
Fold 1 IBS: 0.16482604989342142
Fold 2 IBS: 0.21581253800357983
Fold 3 IBS: 0.16699881856428236
Fold 4 IBS: 0.16440986014201406
Fold 5 IBS: 0.23162680179385794
[I 2024-04-14 19:43:07,539] Trial 1 finished with value: 0.18873481367943112 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.18873481367943112.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-14 19:43:08,734] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.18873481367943112.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-14 19:43:12,463] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.18873481367943112.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-14 19:43:15,259] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.18873481367943112.
Fold 1 IBS: 0.1633169715781561
Fold 2 IBS: 0.2286429933624903
Fold 3 IBS: 0.16038419163533107
Fold 4 IBS: 0.15253074708780856
Fold 5 IBS: 0.24130582898026634
[I 2024-04-14 19:43:19,029] Trial 5 finished with value: 0.18923614652881046 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.18873481367943112.
Fold 1 IBS: 0.17445065086357187
Fold 2 IBS: 0.20169165392996158
Fold 3 IBS: 0.1676627544854519
Fold 4 IBS: 0.16837072421930846
Fold 5 IBS: 0.22456017434999712
[I 2024-04-14 19:43:23,243] Trial 6 finished with value: 0.18734719156965818 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 6 with value: 0.18734719156965818.
Fold 1 IBS: 0.20945429478851235
Fold 2 IBS: 0.2185474344233027
Fold 3 IBS: 0.20196436557401284
Fold 4 IBS: 0.22049391513257874
Fold 5 IBS: 0.21750410599944
[I 2024-04-14 19:43:28,177] Trial 7 finished with value: 0.2135928231835693 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 6 with value: 0.18734719156965818.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-14 19:43:35,568] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 6 with value: 0.18734719156965818.
Fold 1 IBS: 0.16356878259670907
Fold 2 IBS: 0.22112965343815635
Fold 3 IBS: 0.16742609043713622
Fold 4 IBS: 0.16472360664251884
Fold 5 IBS: 0.22929149033580973
[I 2024-04-14 19:43:36,965] Trial 9 finished with value: 0.18922792469006605 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 6 with value: 0.18734719156965818.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-14 19:43:47,643] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3251129986182119}. Best is trial 6 with value: 0.18734719156965818.
Fold 1 IBS: 0.16317735132086997
Fold 2 IBS: 0.21873425674568509
Fold 3 IBS: 0.16186125964347403
Fold 4 IBS: 0.15499561158614922
Fold 5 IBS: 0.23769349502861606
[I 2024-04-14 19:43:50,109] Trial 11 finished with value: 0.18729239486495888 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 134, 'oob_score': False, 'max_samples': 0.9878564362760905, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1462958538133259}. Best is trial 11 with value: 0.18729239486495888.
Fold 1 IBS: 0.16384025869342003
Fold 2 IBS: 0.22214126345881852
Fold 3 IBS: 0.1677707083524635
Fold 4 IBS: 0.164089203043008
Fold 5 IBS: 0.23094931094702037
[I 2024-04-14 19:43:52,896] Trial 12 finished with value: 0.18975814889894607 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.9971022097505926, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.00536038995271218}. Best is trial 11 with value: 0.18729239486495888.
Fold 1 IBS: 0.17024096435877972
Fold 2 IBS: 0.2062666308265926
Fold 3 IBS: 0.17044115748999258
Fold 4 IBS: 0.1769239021266453
Fold 5 IBS: 0.21749058837248067
[I 2024-04-14 19:43:57,157] Trial 13 finished with value: 0.18827264863489818 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 272, 'oob_score': False, 'max_samples': 0.8614642794676799, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3325259434945655}. Best is trial 11 with value: 0.18729239486495888.
Fold 1 IBS: 0.17413428691557456
Fold 2 IBS: 0.24724916313481402
Fold 3 IBS: 0.15277854094807228
Fold 4 IBS: 0.1524225594658355
Fold 5 IBS: 0.25065276840394085
[I 2024-04-14 19:43:59,743] Trial 14 finished with value: 0.19544746377364747 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.8213409911746509, 'max_features': None, 'min_weight_fraction_leaf': 0.13714866618764465}. Best is trial 11 with value: 0.18729239486495888.
Fold 1 IBS: 0.16294963111946004
Fold 2 IBS: 0.22474136247403792
Fold 3 IBS: 0.1702024898510158
Fold 4 IBS: 0.16485953033184528
Fold 5 IBS: 0.2362616502570034
[I 2024-04-14 19:44:00,277] Trial 15 finished with value: 0.1918029328066725 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 14, 'oob_score': False, 'max_samples': 0.9975584771785205, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.26414549823157507}. Best is trial 11 with value: 0.18729239486495888.

Fold 1 IBS: 0.19351607416920746
Fold 2 IBS: 0.20968940705829933
Fold 3 IBS: 0.19048536469298225
Fold 4 IBS: 0.209563612116214
Fold 5 IBS: 0.21661436376539073
[I 2024-04-14 19:44:04,598] Trial 16 finished with value: 0.20397376436041875 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.7722654699481682, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3669134924898976}. Best is trial 11 with value: 0.18729239486495888.
Fold 1 IBS: 0.17423741105557677
Fold 2 IBS: 0.2440599897427602
Fold 3 IBS: 0.15183171873292833
Fold 4 IBS: 0.15092526263284642
Fold 5 IBS: 0.250213848099463
[I 2024-04-14 19:44:07,883] Trial 17 finished with value: 0.19425364605271495 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 222, 'oob_score': False, 'max_samples': 0.8763218642348055, 'max_features': None, 'min_weight_fraction_leaf': 0.10349210655575972}. Best is trial 11 with value: 0.18729239486495888.
Fold 1 IBS: 0.2139627024749741
Fold 2 IBS: 0.22146728689550518
Fold 3 IBS: 0.20478239234239476
Fold 4 IBS: 0.22467133313079304
Fold 5 IBS: 0.21869132455154827
[I 2024-04-14 19:44:10,428] Trial 18 finished with value: 0.21671500787904305 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 152, 'oob_score': True, 'max_samples': 0.9455451604023817, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4936228322884221}. Best is trial 11 with value: 0.18729239486495888.
Fold 1 IBS: 0.1643069539349635
Fold 2 IBS: 0.22213943006648498
Fold 3 IBS: 0.16852392248181794
Fold 4 IBS: 0.1646666687935281
Fold 5 IBS: 0.22992450502893874
[I 2024-04-14 19:44:16,451] Trial 19 finished with value: 0.18991229606114665 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 17, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.7692459385299205, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2222565686889418}. Best is trial 11 with value: 0.18729239486495888.
Fold 1 IBS: 0.15885797376869606
Fold 2 IBS: 0.23374063420040264
Fold 3 IBS: 0.15470217784505635
Fold 4 IBS: 0.14815309699704077
Fold 5 IBS: 0.24470405952391927
[I 2024-04-14 19:44:20,465] Trial 20 finished with value: 0.188031588467023 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 246, 'oob_score': False, 'max_samples': 0.23419761201309758, 'max_features': None, 'min_weight_fraction_leaf': 0.004060792657387402}. Best is trial 11 with value: 0.18729239486495888.
Fold 1 IBS: 0.1616286602806275
Fold 2 IBS: 0.2336597463795636
Fold 3 IBS: 0.15642264339303977
Fold 4 IBS: 0.14966385897831577
Fold 5 IBS: 0.24303693723031747
[I 2024-04-14 19:44:25,260] Trial 21 finished with value: 0.18888236925237284 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 246, 'oob_score': False, 'max_samples': 0.21656015915486512, 'max_features': None, 'min_weight_fraction_leaf': 0.015286692831410549}. Best is trial 11 with value: 0.18729239486495888.
Fold 1 IBS: 0.1660720568814824
Fold 2 IBS: 0.20447636975342975
Fold 3 IBS: 0.1661747334542292
Fold 4 IBS: 0.16686013673743083
Fold 5 IBS: 0.224234611060096
[I 2024-04-14 19:44:27,442] Trial 22 finished with value: 0.18556358157733363 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 106, 'oob_score': False, 'max_samples': 0.40943259633635787, 'max_features': None, 'min_weight_fraction_leaf': 0.1676688812597935}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16764619931486452
Fold 2 IBS: 0.22056474579491334
Fold 3 IBS: 0.16692746206989154
Fold 4 IBS: 0.16433074121900554
Fold 5 IBS: 0.2287879400979916
[I 2024-04-14 19:44:29,041] Trial 23 finished with value: 0.1896514176993333 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 101, 'oob_score': False, 'max_samples': 0.4478983539583735, 'max_features': None, 'min_weight_fraction_leaf': 0.16595892771629966}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.21398562800180138
Fold 2 IBS: 0.22117745041730547
Fold 3 IBS: 0.20508511294577014
Fold 4 IBS: 0.2247604766503128
Fold 5 IBS: 0.21854918422128822
[I 2024-04-14 19:44:31,600] Trial 24 finished with value: 0.21671157044729564 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 183, 'oob_score': False, 'max_samples': 0.35998225257262595, 'max_features': None, 'min_weight_fraction_leaf': 0.26440000043761985}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.17037411966032096
Fold 2 IBS: 0.24435131242456135
Fold 3 IBS: 0.15664707059259603
Fold 4 IBS: 0.15419318854521333
Fold 5 IBS: 0.25283340416414174
[I 2024-04-14 19:44:32,574] Trial 25 finished with value: 0.19567981907736667 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 57, 'oob_score': False, 'max_samples': 0.6219587265298226, 'max_features': None, 'min_weight_fraction_leaf': 0.11011642963163945}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.17718514912766248
Fold 2 IBS: 0.2011592509190946
Fold 3 IBS: 0.17405998833849592
Fold 4 IBS: 0.18289934444006586
Fold 5 IBS: 0.21549878359171917
[I 2024-04-14 19:44:35,320] Trial 26 finished with value: 0.19016050328340758 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 117, 'oob_score': True, 'max_samples': 0.4704864355905733, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19118494144345455}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.1786587738249695
Fold 2 IBS: 0.19562176059755393
Fold 3 IBS: 0.16733270848160875
Fold 4 IBS: 0.17986063897649807
Fold 5 IBS: 0.22367550741009004
[I 2024-04-14 19:44:35,852] Trial 27 finished with value: 0.18902987785814404 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 17, 'oob_score': False, 'max_samples': 0.8147112594793872, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3061403148713857}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.17570195062265112
Fold 2 IBS: 0.21136844789052558
Fold 3 IBS: 0.167445842168042
Fold 4 IBS: 0.16446798073728175
Fold 5 IBS: 0.22990440135246132
[I 2024-04-14 19:44:37,843] Trial 28 finished with value: 0.18977772455419237 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 134, 'oob_score': False, 'max_samples': 0.9449907956381309, 'max_features': None, 'min_weight_fraction_leaf': 0.36972858742462633}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.17403114585512655
Fold 2 IBS: 0.24368757236250776
Fold 3 IBS: 0.16621771227939117
Fold 4 IBS: 0.16250139429019367
Fold 5 IBS: 0.23987222083609044
[I 2024-04-14 19:44:38,970] Trial 29 finished with value: 0.1972620091246619 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 71, 'oob_score': False, 'max_samples': 0.6940172473906272, 'max_features': None, 'min_weight_fraction_leaf': 0.23692450684000754}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.1630142352247382
Fold 2 IBS: 0.22728608304259312
Fold 3 IBS: 0.1666788821168739
Fold 4 IBS: 0.15855077910296253
Fold 5 IBS: 0.2373930570784106
[I 2024-04-14 19:44:43,076] Trial 30 finished with value: 0.1905846073131157 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 314, 'oob_score': False, 'max_samples': 0.7453152670297452, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06191197972928188}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.21404975323703124
Fold 2 IBS: 0.2205041987281292
Fold 3 IBS: 0.20488054190742694
Fold 4 IBS: 0.22471044107839244

Fold 5 IBS: 0.21779182387746962
[I 2024-04-14 19:44:47,008] Trial 31 finished with value: 0.21638735176568988 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 248, 'oob_score': False, 'max_samples': 0.2509419638006214, 'max_features': None, 'min_weight_fraction_leaf': 0.13797627619743888}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.15911475932841543
Fold 2 IBS: 0.22969020074696483
Fold 3 IBS: 0.1598944330555651
Fold 4 IBS: 0.1560912834375737
Fold 5 IBS: 0.2346999284506904
[I 2024-04-14 19:44:52,704] Trial 32 finished with value: 0.1878981210038419 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 380, 'oob_score': False, 'max_samples': 0.12343238195577959, 'max_features': None, 'min_weight_fraction_leaf': 0.03450750693525531}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.21394148197836613
Fold 2 IBS: 0.22067757909573427
Fold 3 IBS: 0.20511748334724234
Fold 4 IBS: 0.22476919051011507
Fold 5 IBS: 0.21701496679132304
[I 2024-04-14 19:44:58,345] Trial 33 finished with value: 0.21630414034455617 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.11044321584012254, 'max_features': None, 'min_weight_fraction_leaf': 0.18426184423657163}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.1598146503831995
Fold 2 IBS: 0.23265140271708343
Fold 3 IBS: 0.16301696516802167
Fold 4 IBS: 0.15598673436853022
Fold 5 IBS: 0.23590658374788934
[I 2024-04-14 19:45:05,628] Trial 34 finished with value: 0.1894752672769448 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 455, 'oob_score': False, 'max_samples': 0.16134042468975496, 'max_features': None, 'min_weight_fraction_leaf': 0.037123340431425796}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.18786314273179544
Fold 2 IBS: 0.20756109680937782
Fold 3 IBS: 0.184684634599511
Fold 4 IBS: 0.19954641476544047
Fold 5 IBS: 0.21505147608669153
[I 2024-04-14 19:45:12,024] Trial 35 finished with value: 0.19894135299856325 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 344, 'oob_score': True, 'max_samples': 0.3338536090461608, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.145282911837548}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.21401187229320304
Fold 2 IBS: 0.2212817027159044
Fold 3 IBS: 0.20482418946265074
Fold 4 IBS: 0.2247487687892312
Fold 5 IBS: 0.21860456212203577
[I 2024-04-14 19:45:15,976] Trial 36 finished with value: 0.21669421907660502 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 300, 'oob_score': False, 'max_samples': 0.6243798791794624, 'max_features': None, 'min_weight_fraction_leaf': 0.43719302942751936}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16757826249304836
Fold 2 IBS: 0.24316130468019417
Fold 3 IBS: 0.15576888387610602
Fold 4 IBS: 0.15393424883607262
Fold 5 IBS: 0.24890132975943594
[I 2024-04-14 19:45:19,629] Trial 37 finished with value: 0.19386880592897143 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 186, 'oob_score': False, 'max_samples': 0.5146379046763427, 'max_features': None, 'min_weight_fraction_leaf': 0.0974667988156572}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16214855666872544
Fold 2 IBS: 0.22774006233883332
Fold 3 IBS: 0.1578208349096569
Fold 4 IBS: 0.14647317363842172
Fold 5 IBS: 0.24386804029948206
[I 2024-04-14 19:45:28,842] Trial 38 finished with value: 0.1876101335710239 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 370, 'oob_score': True, 'max_samples': 0.5855895781328831, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04242176381500584}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.21404887574264217
Fold 2 IBS: 0.22164972288814289
Fold 3 IBS: 0.20479584595284833
Fold 4 IBS: 0.2247325493493859
Fold 5 IBS: 0.21863036539786423
[I 2024-04-14 19:45:36,625] Trial 39 finished with value: 0.2167714718661767 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 188, 'oob_score': True, 'max_samples': 0.5985019901901072, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3800666789685449}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.17720824253249776
Fold 2 IBS: 0.20402589705335855
Fold 3 IBS: 0.17544149591953978
Fold 4 IBS: 0.18761285677765993
Fold 5 IBS: 0.2160990851450146
[I 2024-04-14 19:45:50,430] Trial 40 finished with value: 0.19207751548561414 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 346, 'oob_score': True, 'max_samples': 0.5145175410716147, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21384217310108927}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16167461415419127
Fold 2 IBS: 0.2256887510602269
Fold 3 IBS: 0.16289696088424346
Fold 4 IBS: 0.1540480433250373
Fold 5 IBS: 0.24056519513238092
[I 2024-04-14 19:46:01,781] Trial 41 finished with value: 0.18897471291121598 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 375, 'oob_score': True, 'max_samples': 0.3977971397305835, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04894981383757005}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16516743799349495
Fold 2 IBS: 0.2129554010371747
Fold 3 IBS: 0.16874064582708792
Fold 4 IBS: 0.16903173522314716
Fold 5 IBS: 0.22719988629220628
[I 2024-04-14 19:46:13,749] Trial 42 finished with value: 0.1886190212746222 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.2827702441629814, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08308116721819075}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16223586627529668
Fold 2 IBS: 0.22570072343848516
Fold 3 IBS: 0.1675776255826153
Fold 4 IBS: 0.16102551024836761
Fold 5 IBS: 0.23619977499040912
[I 2024-04-14 19:46:23,266] Trial 43 finished with value: 0.1905479001070348 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 410, 'oob_score': True, 'max_samples': 0.9098463098016105, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.029645532030189103}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.2140047418512639
Fold 2 IBS: 0.22055100501762692
Fold 3 IBS: 0.20533788038138034
Fold 4 IBS: 0.2248951144952754
Fold 5 IBS: 0.21728296118328563
[I 2024-04-14 19:46:27,147] Trial 44 finished with value: 0.21641434058576645 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.17280669754784292, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1199846676803585}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.1634103907666942
Fold 2 IBS: 0.23102191380850567
Fold 3 IBS: 0.15918757841565323
Fold 4 IBS: 0.1493495043577147
Fold 5 IBS: 0.24316110181740416
[I 2024-04-14 19:46:35,960] Trial 45 finished with value: 0.18922609783319438 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.9524611560431974, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07650075747004571}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.1701123662293373
Fold 2 IBS: 0.2391803060696165
Fold 3 IBS: 0.16606727189886572
Fold 4 IBS: 0.16087539310137902
Fold 5 IBS: 0.24015383648060643
[I 2024-04-14 19:46:37,589] Trial 46 finished with value: 0.19527783475596097 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.5640373194184523, 'max_features': None, 'min_weight_fraction_leaf': 0.16484643351840603}. Best is trial 22 with value: 0.18556358157733363.

Fold 1 IBS: 0.16258340227838988
Fold 2 IBS: 0.226804416564432
Fold 3 IBS: 0.16270125876160801
Fold 4 IBS: 0.15497094833655034
Fold 5 IBS: 0.2395972513875397
[I 2024-04-14 19:46:46,520] Trial 47 finished with value: 0.189331455465704 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 325, 'oob_score': False, 'max_samples': 0.8252659010917025, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.054586859539885686}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.21399426337349062
Fold 2 IBS: 0.22211586414919254
Fold 3 IBS: 0.2044981281283501
Fold 4 IBS: 0.22515630305409148
Fold 5 IBS: 0.2177243240610341
[I 2024-04-14 19:46:47,748] Trial 48 finished with value: 0.21669777655323177 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 15, 'n_estimators': 40, 'oob_score': False, 'max_samples': 0.3940370420761242, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2832260599418074}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.17505036221669337
Fold 2 IBS: 0.2144445309210188
Fold 3 IBS: 0.16747532433970305
Fold 4 IBS: 0.1662370979337671
Fold 5 IBS: 0.22766311846905452
[I 2024-04-14 19:46:52,784] Trial 49 finished with value: 0.19017408677604736 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 219, 'oob_score': True, 'max_samples': 0.8805727386313965, 'max_features': None, 'min_weight_fraction_leaf': 0.34264283218926966}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.2139873582342635
Fold 2 IBS: 0.2214523809538181
Fold 3 IBS: 0.20482724639419506
Fold 4 IBS: 0.22464827329549164
Fold 5 IBS: 0.21855415606596498
[I 2024-04-14 19:47:03,484] Trial 50 finished with value: 0.21669388298874667 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 487, 'oob_score': False, 'max_samples': 0.6532040261396448, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.43311102480390473}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16016354947861794
Fold 2 IBS: 0.23402038693940122
Fold 3 IBS: 0.1604585222804134
Fold 4 IBS: 0.1538922232914839
Fold 5 IBS: 0.24685601772720406
[I 2024-04-14 19:47:06,114] Trial 51 finished with value: 0.19107813994342412 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 125, 'oob_score': False, 'max_samples': 0.1549634736034469, 'max_features': None, 'min_weight_fraction_leaf': 0.00638853676525547}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.15996206468361504
Fold 2 IBS: 0.24095802341361755
Fold 3 IBS: 0.16282820723281588
Fold 4 IBS: 0.15496362482602746
Fold 5 IBS: 0.24279661703937971
[I 2024-04-14 19:47:12,133] Trial 52 finished with value: 0.1923017074390911 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 436, 'oob_score': False, 'max_samples': 0.20518879692063885, 'max_features': None, 'min_weight_fraction_leaf': 0.026446076127470894}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.163113807074275
Fold 2 IBS: 0.23004648717313594
Fold 3 IBS: 0.1636829802697649
Fold 4 IBS: 0.15942199086312836
Fold 5 IBS: 0.234343062002557
[I 2024-04-14 19:47:16,399] Trial 53 finished with value: 0.19012166547657222 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 264, 'oob_score': False, 'max_samples': 0.2883774379709209, 'max_features': None, 'min_weight_fraction_leaf': 0.08878968611302902}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16821375876652414
Fold 2 IBS: 0.20909335536480053
Fold 3 IBS: 0.1656855826471394
Fold 4 IBS: 0.1698864227342694
Fold 5 IBS: 0.2224263396927871
[I 2024-04-14 19:47:21,721] Trial 54 finished with value: 0.18706109184110414 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.12235204522531054, 'max_features': None, 'min_weight_fraction_leaf': 0.045073877849215044}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.2139359562926612
Fold 2 IBS: 0.22044462159092962
Fold 3 IBS: 0.2054289395562046
Fold 4 IBS: 0.2251175559978818
Fold 5 IBS: 0.2170621520664841
[I 2024-04-14 19:47:26,760] Trial 55 finished with value: 0.2163978451008323 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.10258755436222192, 'max_features': None, 'min_weight_fraction_leaf': 0.1196506804332561}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16309233502415232
Fold 2 IBS: 0.23239427912223481
Fold 3 IBS: 0.16056850939927042
Fold 4 IBS: 0.1504567074187112
Fold 5 IBS: 0.24294301263254217
[I 2024-04-14 19:47:31,413] Trial 56 finished with value: 0.18989096871938219 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 290, 'oob_score': False, 'max_samples': 0.9878371070478413, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.043901809513721884}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.17018612601575592
Fold 2 IBS: 0.2528691014702244
Fold 3 IBS: 0.15848942755627668
Fold 4 IBS: 0.15564831749728644
Fold 5 IBS: 0.24710634895038136
[I 2024-04-14 19:47:36,095] Trial 57 finished with value: 0.196859864297985 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 352, 'oob_score': False, 'max_samples': 0.7122361397492003, 'max_features': None, 'min_weight_fraction_leaf': 0.079137279026645}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.21399695514170172
Fold 2 IBS: 0.22100422006381243
Fold 3 IBS: 0.2049851768878292
Fold 4 IBS: 0.22448572037744208
Fold 5 IBS: 0.21761178111689095
[I 2024-04-14 19:47:41,475] Trial 58 finished with value: 0.2164167707175353 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.1961692755390605, 'max_features': None, 'min_weight_fraction_leaf': 0.15133431270867928}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.21394135456137173
Fold 2 IBS: 0.22080493336783602
Fold 3 IBS: 0.20510260143523074
Fold 4 IBS: 0.22472172806034704
Fold 5 IBS: 0.2170275702268238
[I 2024-04-14 19:47:50,755] Trial 59 finished with value: 0.21631963753032188 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.12799174630174012, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1754033280220313}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16376459115127115
Fold 2 IBS: 0.21850669115119073
Fold 3 IBS: 0.1685246620630375
Fold 4 IBS: 0.16366401523229912
Fold 5 IBS: 0.23096920333342844
[I 2024-04-14 19:47:55,722] Trial 60 finished with value: 0.1890858325862454 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.25798861239570026, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06442316108260773}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.1631637582077473
Fold 2 IBS: 0.22831713004104454
Fold 3 IBS: 0.15245055534544877
Fold 4 IBS: 0.14807334361924981
Fold 5 IBS: 0.2519807939610184
[I 2024-04-14 19:47:58,378] Trial 61 finished with value: 0.18879711623490175 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 160, 'oob_score': False, 'max_samples': 0.24840080708129753, 'max_features': None, 'min_weight_fraction_leaf': 0.01870015402484912}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.1562454960680839
Fold 2 IBS: 0.22907544770423122
Fold 3 IBS: 0.15839585485356264
Fold 4 IBS: 0.15222071105834722
Fold 5 IBS: 0.24215573859766668
[I 2024-04-14 19:48:02,857] Trial 62 finished with value: 0.18761864965637834 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 232, 'oob_score': False, 'max_samples': 0.1382069042909675, 'max_features': None, 'min_weight_fraction_leaf': 0.0017694898308935176}. Best is trial 22 with value: 0.18556358157733363.

Fold 1 IBS: 0.2139502037041144
Fold 2 IBS: 0.2205253410474416
Fold 3 IBS: 0.20539138240116334
Fold 4 IBS: 0.22483265303988334
Fold 5 IBS: 0.21729817764200712
[I 2024-04-14 19:48:07,885] Trial 63 finished with value: 0.21639955156692198 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.14304382305903557, 'max_features': None, 'min_weight_fraction_leaf': 0.212666616348277}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16044995955528968
Fold 2 IBS: 0.23495388944522017
Fold 3 IBS: 0.15877526237480574
Fold 4 IBS: 0.15187995834572193
Fold 5 IBS: 0.2443346149864615
[I 2024-04-14 19:48:09,775] Trial 64 finished with value: 0.19007873694149982 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 103, 'oob_score': False, 'max_samples': 0.1750738410149462, 'max_features': None, 'min_weight_fraction_leaf': 0.0010292476215893534}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.17075637369663388
Fold 2 IBS: 0.19923093228294542
Fold 3 IBS: 0.1671117827300966
Fold 4 IBS: 0.17186298497368924
Fold 5 IBS: 0.22143706205774313
[I 2024-04-14 19:48:12,866] Trial 65 finished with value: 0.18607982714822166 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 15, 'n_estimators': 201, 'oob_score': False, 'max_samples': 0.4654353108417944, 'max_features': None, 'min_weight_fraction_leaf': 0.03779148075779278}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.2139901459008269
Fold 2 IBS: 0.22133666053756276
Fold 3 IBS: 0.2048727630433836
Fold 4 IBS: 0.224637123699267
Fold 5 IBS: 0.218689751349768
[I 2024-04-14 19:48:16,399] Trial 66 finished with value: 0.21670528890616167 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 233, 'oob_score': False, 'max_samples': 0.46781511608424425, 'max_features': None, 'min_weight_fraction_leaf': 0.24478885418546475}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.17283774801274088
Fold 2 IBS: 0.2044877358445136
Fold 3 IBS: 0.17162020223137242
Fold 4 IBS: 0.17978961615895203
Fold 5 IBS: 0.2189142211109713
[I 2024-04-14 19:48:19,374] Trial 67 finished with value: 0.18952990467171005 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 15, 'n_estimators': 201, 'oob_score': False, 'max_samples': 0.4524261086082003, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06793692890197423}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.21330556803378428
Fold 2 IBS: 0.2210505465685446
Fold 3 IBS: 0.20489395271164582
Fold 4 IBS: 0.22442089955184039
Fold 5 IBS: 0.21817981460981392
[I 2024-04-14 19:48:22,298] Trial 68 finished with value: 0.21637015629512582 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 14, 'n_estimators': 233, 'oob_score': False, 'max_samples': 0.3352798600247622, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1282382911765231}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16553509019420026
Fold 2 IBS: 0.24566075848705443
Fold 3 IBS: 0.1519976248770693
Fold 4 IBS: 0.15150763771382852
Fold 5 IBS: 0.25158637988892396
[I 2024-04-14 19:48:24,715] Trial 69 finished with value: 0.19325749823221527 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 169, 'oob_score': False, 'max_samples': 0.41787534882724175, 'max_features': None, 'min_weight_fraction_leaf': 0.021697910377065484}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16903571815805093
Fold 2 IBS: 0.2453299016274049
Fold 3 IBS: 0.16734662411777887
Fold 4 IBS: 0.16080113944997831
Fold 5 IBS: 0.23657928382859628
[I 2024-04-14 19:48:28,574] Trial 70 finished with value: 0.19581853343636185 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 1, 'n_estimators': 264, 'oob_score': False, 'max_samples': 0.5580773849100643, 'max_features': None, 'min_weight_fraction_leaf': 0.10415283732963354}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16622146115870642
Fold 2 IBS: 0.22729793055918623
Fold 3 IBS: 0.15189129901742832
Fold 4 IBS: 0.1441825171340755
Fold 5 IBS: 0.2526283497410172
[I 2024-04-14 19:48:30,861] Trial 71 finished with value: 0.1884443115220827 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 139, 'oob_score': False, 'max_samples': 0.4939065022247407, 'max_features': None, 'min_weight_fraction_leaf': 0.03364426370922935}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16744065129586116
Fold 2 IBS: 0.2381354703793748
Fold 3 IBS: 0.1537302136245761
Fold 4 IBS: 0.14508981380488656
Fold 5 IBS: 0.2519468617889
[I 2024-04-14 19:48:34,073] Trial 72 finished with value: 0.19126860217871972 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 200, 'oob_score': False, 'max_samples': 0.7909055234106888, 'max_features': None, 'min_weight_fraction_leaf': 0.0523338629614294}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.21399326584276038
Fold 2 IBS: 0.2211987915262927
Fold 3 IBS: 0.2049762399313692
Fold 4 IBS: 0.22478898811822795
Fold 5 IBS: 0.21822723385960904
[I 2024-04-14 19:48:38,043] Trial 73 finished with value: 0.21663690385565185 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 296, 'oob_score': False, 'max_samples': 0.3699008423329501, 'max_features': None, 'min_weight_fraction_leaf': 0.46459770155785113}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16506349028170553
Fold 2 IBS: 0.2312096711391036
Fold 3 IBS: 0.1526008981711376
Fold 4 IBS: 0.14382488189606932
Fold 5 IBS: 0.2505496136469191
[I 2024-04-14 19:48:44,122] Trial 74 finished with value: 0.18864971102698705 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.8463910108748924, 'max_features': None, 'min_weight_fraction_leaf': 0.043388453189220355}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.16329782174146956
Fold 2 IBS: 0.22422237964749445
Fold 3 IBS: 0.15377905457377064
Fold 4 IBS: 0.14367864281487125
Fold 5 IBS: 0.24781664059000055
[I 2024-04-14 19:48:46,290] Trial 75 finished with value: 0.18655890787352128 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 90, 'oob_score': True, 'max_samples': 0.18789909807087368, 'max_features': None, 'min_weight_fraction_leaf': 0.01330052525350338}. Best is trial 22 with value: 0.18556358157733363.
Fold 1 IBS: 0.1569332985958496
Fold 2 IBS: 0.20639078236871464
Fold 3 IBS: 0.15859389827426748
Fold 4 IBS: 0.1435153999531124
Fold 5 IBS: 0.23899953055738138
[I 2024-04-14 19:48:48,011] Trial 76 finished with value: 0.18088658194986512 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 88, 'oob_score': True, 'max_samples': 0.22393267024094543, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.017121900234687792}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.16223942235781622
Fold 2 IBS: 0.2096878774780893
Fold 3 IBS: 0.15750365738280075
Fold 4 IBS: 0.1465917290363536
Fold 5 IBS: 0.24028098477170756
[I 2024-04-14 19:48:49,963] Trial 77 finished with value: 0.18326073420535352 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 80, 'oob_score': True, 'max_samples': 0.28422260446203074, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.020765930335976655}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.16102829769758178
Fold 2 IBS: 0.20989894975620071
Fold 3 IBS: 0.15655819861444253
Fold 4 IBS: 0.14175192913705156
Fold 5 IBS: 0.24689317672150432
[I 2024-04-14 19:48:51,867] Trial 78 finished with value: 0.1832261103853562 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 79, 'oob_score': True, 'max_samples': 0.27965148697014836, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012018332064289436}. Best is trial 76 with value: 0.18088658194986512.

Fold 1 IBS: 0.16122065792349757
Fold 2 IBS: 0.21325686305320374
Fold 3 IBS: 0.15822275060218324
Fold 4 IBS: 0.14281519984729882
Fold 5 IBS: 0.2458841078408022
[I 2024-04-14 19:48:53,905] Trial 79 finished with value: 0.18427991585339712 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.2969951845956973, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01531063774064334}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.16590885354349483
Fold 2 IBS: 0.20627975780151778
Fold 3 IBS: 0.15178945005683334
Fold 4 IBS: 0.14741838302275773
Fold 5 IBS: 0.24237922921628863
[I 2024-04-14 19:48:54,991] Trial 80 finished with value: 0.18275513472817845 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 36, 'oob_score': True, 'max_samples': 0.29124216175839035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0229768556573917}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.1695808561508793
Fold 2 IBS: 0.2014426800075063
Fold 3 IBS: 0.1543329383239821
Fold 4 IBS: 0.1449674215064345
Fold 5 IBS: 0.24522129645961216
[I 2024-04-14 19:48:56,046] Trial 81 finished with value: 0.18310903848968288 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 33, 'oob_score': True, 'max_samples': 0.29924425058857335, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012819061064505918}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.16622765979535892
Fold 2 IBS: 0.20341132953218405
Fold 3 IBS: 0.15461462816531457
Fold 4 IBS: 0.1431395563006843
Fold 5 IBS: 0.24726535998750532
[I 2024-04-14 19:48:57,107] Trial 82 finished with value: 0.18293170675620946 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 41, 'oob_score': True, 'max_samples': 0.2961374568273018, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01621066134918547}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.16438041697335104
Fold 2 IBS: 0.20313554807637968
Fold 3 IBS: 0.15391318815454252
Fold 4 IBS: 0.14786564349967488
Fold 5 IBS: 0.23775555331101014
[I 2024-04-14 19:48:58,055] Trial 83 finished with value: 0.18141007000299164 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 37, 'oob_score': True, 'max_samples': 0.29981415333579375, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.018729609584575767}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.16394377593751092
Fold 2 IBS: 0.20579467344856633
Fold 3 IBS: 0.15372914247075592
Fold 4 IBS: 0.14761699676177267
Fold 5 IBS: 0.23865555267690905
[I 2024-04-14 19:48:58,979] Trial 84 finished with value: 0.181948028259103 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 36, 'oob_score': True, 'max_samples': 0.3017480446788485, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.019289820322851866}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.21339944995283341
Fold 2 IBS: 0.21153141377216542
Fold 3 IBS: 0.18182065421440285
Fold 4 IBS: 0.16308427966737357
Fold 5 IBS: 0.27951234980434003
[I 2024-04-14 19:48:59,348] Trial 85 finished with value: 0.20986962948222304 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 3, 'oob_score': True, 'max_samples': 0.2920443343855117, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.017025217851269515}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.1665574150467071
Fold 2 IBS: 0.20488065824531929
Fold 3 IBS: 0.1530561472794258
Fold 4 IBS: 0.1488071287011282
Fold 5 IBS: 0.24126996355310584
[I 2024-04-14 19:49:00,508] Trial 86 finished with value: 0.18291426256513726 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 38, 'oob_score': True, 'max_samples': 0.31757594799046623, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.026194659390786308}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.16765387835452555
Fold 2 IBS: 0.20762798928767523
Fold 3 IBS: 0.16107418871127413
Fold 4 IBS: 0.1607167218799866
Fold 5 IBS: 0.2328739778425261
[I 2024-04-14 19:49:01,804] Trial 87 finished with value: 0.18598935121519752 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 39, 'oob_score': True, 'max_samples': 0.3194900702418095, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06117823073643203}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.16792517192085746
Fold 2 IBS: 0.21845276258409768
Fold 3 IBS: 0.16120251780888378
Fold 4 IBS: 0.15057485231359496
Fold 5 IBS: 0.23691656801585256
[I 2024-04-14 19:49:03,107] Trial 88 finished with value: 0.18701437452865732 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 58, 'oob_score': True, 'max_samples': 0.22027481519144942, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.027667290090775745}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.16304891022593504
Fold 2 IBS: 0.20294972313075998
Fold 3 IBS: 0.149150717179815
Fold 4 IBS: 0.14194814547979753
Fold 5 IBS: 0.25338207184312045
[I 2024-04-14 19:49:03,812] Trial 89 finished with value: 0.1820959135718856 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 25, 'oob_score': True, 'max_samples': 0.2672783462130933, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.011426765042299836}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.1651795538936671
Fold 2 IBS: 0.21528961139682032
Fold 3 IBS: 0.15122623144530856
Fold 4 IBS: 0.14297951507716183
Fold 5 IBS: 0.25018428823814626
[I 2024-04-14 19:49:04,702] Trial 90 finished with value: 0.1849718400102208 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 25, 'oob_score': True, 'max_samples': 0.3503716063756287, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008340346579465377}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.16414530979140596
Fold 2 IBS: 0.2129454238885234
Fold 3 IBS: 0.15821416765649643
Fold 4 IBS: 0.14671356164125562
Fold 5 IBS: 0.24266284790997616
[I 2024-04-14 19:49:06,169] Trial 91 finished with value: 0.1849362621775315 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 56, 'oob_score': True, 'max_samples': 0.2640691495143511, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02709442480382904}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.16722812060618147
Fold 2 IBS: 0.20565238941396002
Fold 3 IBS: 0.15401798803283714
Fold 4 IBS: 0.14166761407836384
Fold 5 IBS: 0.2512380992817082
[I 2024-04-14 19:49:07,009] Trial 92 finished with value: 0.18396084228261014 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 28, 'oob_score': True, 'max_samples': 0.31250047876579456, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.001157833302075896}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.1765068897519493
Fold 2 IBS: 0.19892064044066762
Fold 3 IBS: 0.1701853434133269
Fold 4 IBS: 0.1835356321703431
Fold 5 IBS: 0.23162501541906158
[I 2024-04-14 19:49:07,462] Trial 93 finished with value: 0.1921547042390697 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 7, 'oob_score': True, 'max_samples': 0.23584599751527596, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.056343929661211364}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.1647217978899619
Fold 2 IBS: 0.21445826307327692
Fold 3 IBS: 0.15722293363583975
Fold 4 IBS: 0.1451667000531094
Fold 5 IBS: 0.24245921079250485
[I 2024-04-14 19:49:08,923] Trial 94 finished with value: 0.18480578108893858 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 64, 'oob_score': True, 'max_samples': 0.3763271403124307, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.022861083152228893}. Best is trial 76 with value: 0.18088658194986512.

Fold 1 IBS: 0.16758785531637785
Fold 2 IBS: 0.19991680056926603
Fold 3 IBS: 0.16807972276243374
Fold 4 IBS: 0.16678300610940044
Fold 5 IBS: 0.23011961493856892
[I 2024-04-14 19:49:09,871] Trial 95 finished with value: 0.18649739993920939 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 40, 'oob_score': True, 'max_samples': 0.3130463719118361, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07417173322008858}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.16071713586864783
Fold 2 IBS: 0.2134228435221808
Fold 3 IBS: 0.15838796300027969
Fold 4 IBS: 0.14827158241140817
Fold 5 IBS: 0.24299630373240863
[I 2024-04-14 19:49:11,528] Trial 96 finished with value: 0.18475916570698503 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 85, 'oob_score': True, 'max_samples': 0.3412497541587062, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03298774651032421}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.1724826972547329
Fold 2 IBS: 0.20049292782151487
Fold 3 IBS: 0.1668074277144485
Fold 4 IBS: 0.17104794336879076
Fold 5 IBS: 0.22186332660894248
[I 2024-04-14 19:49:12,196] Trial 97 finished with value: 0.1865388645536859 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 20, 'oob_score': True, 'max_samples': 0.27330026426608234, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09183301982276526}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.1610968151083729
Fold 2 IBS: 0.20761550845451657
Fold 3 IBS: 0.15498910197327745
Fold 4 IBS: 0.14138818260816924
Fold 5 IBS: 0.24479385779941917
[I 2024-04-14 19:49:13,419] Trial 98 finished with value: 0.18197669318875107 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 52, 'oob_score': True, 'max_samples': 0.23116448578470986, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.011263218066570437}. Best is trial 76 with value: 0.18088658194986512.
Fold 1 IBS: 0.16112572314859905
Fold 2 IBS: 0.20414975482924475
Fold 3 IBS: 0.15678773132628818
Fold 4 IBS: 0.14288000457695058
Fold 5 IBS: 0.240790683879485
[I 2024-04-14 19:49:14,564] Trial 99 finished with value: 0.1811467795521135 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.22541557635877402, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012026219823922669}. Best is trial 76 with value: 0.18088658194986512.


* Best trial for IBS:
 FrozenTrial(number=76, state=TrialState.COMPLETE, values=[0.18088658194986512], datetime_start=datetime.datetime(2024, 4, 14, 19, 48, 46, 295721), datetime_complete=datetime.datetime(2024, 4, 14, 19, 48, 48, 10955), params={'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 88, 'oob_score': True, 'max_samples': 0.22393267024094543, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.017121900234687792}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=76, value=None)


* Best Score for IBS:
 0.18088658194986512

In [50]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [51]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.77
train_ibs:  0.181

#### Test

In [52]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [53]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=18, max_features='auto', max_leaf_nodes=10,
                     max_samples=0.939974221909062, min_samples_leaf=1,
                     min_samples_split=2,
                     min_weight_fraction_leaf=0.010097497494874971,
                     n_estimators=393, random_state=123, warm_start=True)

test_cindex:  0.579

RandomSurvivalForest(max_depth=20, max_features='auto', max_leaf_nodes=12,
                     max_samples=0.22393267024094543, min_samples_leaf=1,
                     min_samples_split=5,
                     min_weight_fraction_leaf=0.017121900234687792,
                     n_estimators=88, oob_score=True, random_state=123)

test_ibs:  0.226

In [54]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [55]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 19:49:16,413] A new study created in memory with name: no-name-5ef5a1ca-2bc5-4309-af72-8bc22eaa320b

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:49:17,752] Trial 0 finished with value: 0.7597804392466398 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7597804392466398.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:49:21,005] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7597804392466398.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 19:49:27,201] Trial 2 finished with value: 0.7370345439590771 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7597804392466398.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:49:27,772] Trial 3 finished with value: 0.753163133679216 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7597804392466398.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:49:30,171] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7597804392466398.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:49:32,853] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7597804392466398.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:49:34,201] Trial 6 finished with value: 0.7606462401124408 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7075892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:49:38,552] Trial 7 finished with value: 0.7454566175284519 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:49:38,889] Trial 8 finished with value: 0.7478219959437121 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:49:47,320] Trial 9 finished with value: 0.7440882297099458 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:49:50,448] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 19:49:51,897] Trial 11 finished with value: 0.7537983845785513 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:49:54,064] Trial 12 finished with value: 0.759541886719355 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 19:49:55,998] Trial 13 finished with value: 0.7465362511720519 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6381530978163132, 'min_weight_fraction_leaf': 0.10302250602390595}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:49:57,393] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3469585144995889, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:49:59,427] Trial 15 finished with value: 0.7596882192600536 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07436726243220565}. Best is trial 6 with value: 0.7606462401124408.

Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 19:50:00,964] Trial 16 finished with value: 0.7529245811519311 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.18687423911629308}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:50:01,959] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 194, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5688392530311949, 'min_weight_fraction_leaf': 0.3862403774000863}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:50:02,955] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.053773653856063974}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:50:03,561] Trial 19 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4078786025735315, 'min_weight_fraction_leaf': 0.21750931502909437}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 19:50:04,825] Trial 20 finished with value: 0.7438115697501873 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 17, 'n_estimators': 310, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8887988952213425, 'min_weight_fraction_leaf': 0.16483895863649992}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:50:06,676] Trial 21 finished with value: 0.7597804392466398 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 416, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7050862172818282, 'min_weight_fraction_leaf': 0.08156751747114571}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.7953586497890295
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:50:08,503] Trial 22 finished with value: 0.7518488584148224 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6873159527855055, 'min_weight_fraction_leaf': 0.10600930066685874}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:50:10,090] Trial 23 finished with value: 0.7596341067059411 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 402, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7520476640032678, 'min_weight_fraction_leaf': 0.026133687064519517}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 19:50:12,020] Trial 24 finished with value: 0.7567536159668814 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 495, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6024395198214296, 'min_weight_fraction_leaf': 0.08798190753066505}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7522321428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 19:50:13,599] Trial 25 finished with value: 0.7544583552273727 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 345, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5051852313982056, 'min_weight_fraction_leaf': 0.041451106877202853}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:50:21,011] Trial 26 finished with value: 0.7493880467023354 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 420, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8886621644072936, 'min_weight_fraction_leaf': 0.0035978786324019686}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8013392857142857
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 19:50:22,825] Trial 27 finished with value: 0.7568826380006612 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 455, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6958071775717595, 'min_weight_fraction_leaf': 0.07985515374767188}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 19:50:25,449] Trial 28 finished with value: 0.7537983845785513 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 387, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7457497824878886, 'min_weight_fraction_leaf': 0.28691956257494355}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 19:50:27,888] Trial 29 finished with value: 0.7537983845785513 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 233, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5262281274916285, 'min_weight_fraction_leaf': 0.23367475592947387}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 19:50:29,698] Trial 30 finished with value: 0.7556492625737956 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 422, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.17141436902843765}. Best is trial 6 with value: 0.7606462401124408.

Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:50:31,311] Trial 31 finished with value: 0.7596341067059411 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6970733166357045, 'min_weight_fraction_leaf': 0.07324922325860758}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 19:50:33,079] Trial 32 finished with value: 0.7438115697501873 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 469, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6157808495580706, 'min_weight_fraction_leaf': 0.13900695202371743}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 19:50:34,517] Trial 33 finished with value: 0.7558878151010806 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6706256259076719, 'min_weight_fraction_leaf': 0.05122337879361083}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 19:50:35,676] Trial 34 finished with value: 0.7413444945718445 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 8, 'n_estimators': 310, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.44340967834421907, 'min_weight_fraction_leaf': 0.1132416945663157}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6986607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:50:41,692] Trial 35 finished with value: 0.7462683058401403 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 438, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7392941262204207, 'min_weight_fraction_leaf': 0.07143546687962354}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:50:43,109] Trial 36 finished with value: 0.759541886719355 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 343, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5718211055422164, 'min_weight_fraction_leaf': 0.031273022066618646}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:50:44,234] Trial 37 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 286, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8114429313181915, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6986607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:50:51,660] Trial 38 finished with value: 0.7454025049743394 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 404, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9318415222011842, 'min_weight_fraction_leaf': 0.1258251040331416}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:50:53,670] Trial 39 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.47421993354730063, 'min_weight_fraction_leaf': 0.3676238651442645}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 19:50:59,278] Trial 40 finished with value: 0.7379384522573516 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 359, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.725638711091912, 'min_weight_fraction_leaf': 0.02769996827495938}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:51:00,979] Trial 41 finished with value: 0.7596341067059411 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 397, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7620488800258761, 'min_weight_fraction_leaf': 0.017180973100849848}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:51:03,599] Trial 42 finished with value: 0.759541886719355 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 433, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6441007132003778, 'min_weight_fraction_leaf': 0.04861985853985053}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:51:05,740] Trial 43 finished with value: 0.7597804392466398 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 378, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.837257142849845, 'min_weight_fraction_leaf': 0.08692387981680186}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:51:07,425] Trial 44 finished with value: 0.7596882192600536 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8111104576151525, 'min_weight_fraction_leaf': 0.09332862560646599}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:51:09,245] Trial 45 finished with value: 0.7586760858535542 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.848529004532656, 'min_weight_fraction_leaf': 0.1271042405403624}. Best is trial 6 with value: 0.7606462401124408.

Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7522321428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 19:51:11,804] Trial 46 finished with value: 0.7553241560931735 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 328, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9536851743400435, 'min_weight_fraction_leaf': 0.07410234932874653}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:51:13,226] Trial 47 finished with value: 0.7439037897367735 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 260, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6129189577633727, 'min_weight_fraction_leaf': 0.15658175921432554}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 19:51:14,324] Trial 48 finished with value: 0.7529245811519311 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 294, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7951103985237526, 'min_weight_fraction_leaf': 0.1837566151788837}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7075892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 19:51:16,044] Trial 49 finished with value: 0.7452371187174038 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 364, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7080934318210295, 'min_weight_fraction_leaf': 0.09141458717620242}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6986607142857143
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:51:18,020] Trial 50 finished with value: 0.743409979410977 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 102, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9214017108859701, 'min_weight_fraction_leaf': 0.06184229191560099}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:51:20,461] Trial 51 finished with value: 0.7597804392466398 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 369, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8287860439562158, 'min_weight_fraction_leaf': 0.10365698865478705}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:51:22,658] Trial 52 finished with value: 0.7597804392466398 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 422, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8654005382995846, 'min_weight_fraction_leaf': 0.1088013426319471}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:51:24,485] Trial 53 finished with value: 0.7606462401124408 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8515204271859051, 'min_weight_fraction_leaf': 0.10905539760862093}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 19:51:26,540] Trial 54 finished with value: 0.7465362511720519 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8316123706602427, 'min_weight_fraction_leaf': 0.269559930992602}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 19:51:28,096] Trial 55 finished with value: 0.7529900138551021 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 347, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7909267578508004, 'min_weight_fraction_leaf': 0.1254194071550389}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:51:30,853] Trial 56 finished with value: 0.7586760858535542 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 381, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9959190331366914, 'min_weight_fraction_leaf': 0.14411936935146374}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 19:51:31,804] Trial 57 finished with value: 0.7556492625737956 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 237, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9071711796590676, 'min_weight_fraction_leaf': 0.19124895856824803}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:51:33,476] Trial 58 finished with value: 0.7439037897367735 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 441, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.25101710783133363, 'min_weight_fraction_leaf': 0.014702357749232158}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 19:51:35,286] Trial 59 finished with value: 0.7587525697121423 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 488, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9526828940033613, 'min_weight_fraction_leaf': 0.059916841927935324}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:51:36,983] Trial 60 finished with value: 0.7597804392466398 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 416, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7853627491038009, 'min_weight_fraction_leaf': 0.0960436023545811}. Best is trial 6 with value: 0.7606462401124408.

Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 19:51:38,525] Trial 61 finished with value: 0.7465362511720519 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 17, 'n_estimators': 395, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8546449585352289, 'min_weight_fraction_leaf': 0.10836673754932567}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 19:51:40,115] Trial 62 finished with value: 0.7556492625737956 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 423, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8786562726993296, 'min_weight_fraction_leaf': 0.15815135458296745}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:51:41,941] Trial 63 finished with value: 0.7596882192600536 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 459, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8664901703822724, 'min_weight_fraction_leaf': 0.10968985930739895}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:51:43,595] Trial 64 finished with value: 0.759541886719355 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 431, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.828180439036628, 'min_weight_fraction_leaf': 0.038016310448538676}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:51:45,194] Trial 65 finished with value: 0.7597804392466398 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 372, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7589558689327429, 'min_weight_fraction_leaf': 0.08476349190135238}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 19:51:46,718] Trial 66 finished with value: 0.7529900138551021 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 335, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9024169420207223, 'min_weight_fraction_leaf': 0.21431206347457127}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:51:50,165] Trial 67 finished with value: 0.7530168011385173 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 320, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7803848710092787, 'min_weight_fraction_leaf': 0.14055981195476105}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 19:51:56,316] Trial 68 finished with value: 0.7484412417214086 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 356, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7165777449789041, 'min_weight_fraction_leaf': 0.3156969322156432}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:51:58,199] Trial 69 finished with value: 0.754028934545017 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 17, 'max_depth': 19, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6653770429436661, 'min_weight_fraction_leaf': 0.05933435856243416}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7522321428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 19:51:59,990] Trial 70 finished with value: 0.7525804209550723 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9535816352031423, 'min_weight_fraction_leaf': 0.11937655271111346}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:52:02,090] Trial 71 finished with value: 0.7596882192600536 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 420, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8138337037127499, 'min_weight_fraction_leaf': 0.10272989638909304}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:52:03,908] Trial 72 finished with value: 0.7606462401124408 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 447, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7781911785650986, 'min_weight_fraction_leaf': 0.09791144330783928}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:52:05,800] Trial 73 finished with value: 0.7606462401124408 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8576897775126526, 'min_weight_fraction_leaf': 0.13422490267346368}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 19:52:07,582] Trial 74 finished with value: 0.7537983845785513 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3955573155668488, 'min_weight_fraction_leaf': 0.17476113203320584}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:52:09,209] Trial 75 finished with value: 0.7596341067059411 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 446, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7346624761726477, 'min_weight_fraction_leaf': 0.06978588900181996}. Best is trial 6 with value: 0.7606462401124408.

Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:52:10,921] Trial 76 finished with value: 0.7597804392466398 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 496, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8396098265832754, 'min_weight_fraction_leaf': 0.08297131757155839}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 19:52:12,532] Trial 77 finished with value: 0.7556492625737956 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 469, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7682246223715693, 'min_weight_fraction_leaf': 0.13557807408303377}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:52:14,353] Trial 78 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 459, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6784931009472821, 'min_weight_fraction_leaf': 0.41218066030994116}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:52:17,960] Trial 79 finished with value: 0.7480269638487982 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 194, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5398413883194484, 'min_weight_fraction_leaf': 0.04272788226824275}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:52:19,758] Trial 80 finished with value: 0.7606462401124408 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6376420427637578, 'min_weight_fraction_leaf': 0.007015294478473044}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:52:21,372] Trial 81 finished with value: 0.7606462401124408 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 395, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6256931920117493, 'min_weight_fraction_leaf': 0.026793821003154}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:52:23,468] Trial 82 finished with value: 0.7606462401124408 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 440, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5969801889274812, 'min_weight_fraction_leaf': 0.01336570195397994}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:52:25,071] Trial 83 finished with value: 0.7606462401124408 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 438, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6344475422611754, 'min_weight_fraction_leaf': 0.017743647233239998}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 19:52:27,494] Trial 84 finished with value: 0.7567536159668814 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 447, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6315664798972117, 'min_weight_fraction_leaf': 0.0002591684486010562}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:52:29,982] Trial 85 finished with value: 0.7606462401124408 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 397, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5832368332412179, 'min_weight_fraction_leaf': 0.01806090756202245}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 19:52:32,116] Trial 86 finished with value: 0.7606462401124408 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 433, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5742390537943783, 'min_weight_fraction_leaf': 0.0145500592730439}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:52:33,863] Trial 87 finished with value: 0.754028934545017 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5855640642780402, 'min_weight_fraction_leaf': 0.021531554151645475}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 19:52:35,957] Trial 88 finished with value: 0.7530168011385173 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.49167204142030657, 'min_weight_fraction_leaf': 0.008483181145014932}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:52:38,462] Trial 89 finished with value: 0.7439037897367735 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 484, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5207326560927987, 'min_weight_fraction_leaf': 0.03366959268432272}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:52:40,225] Trial 90 finished with value: 0.7596341067059411 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5525058622907164, 'min_weight_fraction_leaf': 0.0219040269126344}. Best is trial 6 with value: 0.7606462401124408.

Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7522321428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 19:52:41,781] Trial 91 finished with value: 0.7579215586905761 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 434, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.571371180284527, 'min_weight_fraction_leaf': 0.008038044143132653}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7522321428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 19:52:43,284] Trial 92 finished with value: 0.7579215586905761 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5962788387203706, 'min_weight_fraction_leaf': 0.02999725535573721}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 19:52:44,942] Trial 93 finished with value: 0.7567536159668814 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6262212139240014, 'min_weight_fraction_leaf': 0.04812254429903915}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:52:46,734] Trial 94 finished with value: 0.7596341067059411 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.653624455385833, 'min_weight_fraction_leaf': 0.014742863338136129}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7522321428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 19:52:48,493] Trial 95 finished with value: 0.7579215586905761 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 430, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5390943359154825, 'min_weight_fraction_leaf': 0.03993575550341874}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 19:52:49,961] Trial 96 finished with value: 0.7567536159668814 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 399, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6129055694607113, 'min_weight_fraction_leaf': 0.012670933406412491}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 19:52:51,819] Trial 97 finished with value: 0.7439037897367735 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 438, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5820199194457903, 'min_weight_fraction_leaf': 0.026044942802397338}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6986607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 19:52:58,636] Trial 98 finished with value: 0.7471341067059412 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 466, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6589059776754134, 'min_weight_fraction_leaf': 0.0009585381077292406}. Best is trial 6 with value: 0.7606462401124408.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7522321428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8080168776371308

[I 2024-04-14 19:53:02,037] A new study created in memory with name: no-name-0366bb17-67d1-4faa-8205-9ef496686bbe

Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 19:53:02,019] Trial 99 finished with value: 0.7579215586905761 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 412, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4622293227685943, 'min_weight_fraction_leaf': 0.055389524648486746}. Best is trial 6 with value: 0.7606462401124408.


* Best trial for C-index:
 FrozenTrial(number=6, state=TrialState.COMPLETE, values=[0.7606462401124408], datetime_start=datetime.datetime(2024, 4, 14, 19, 49, 32, 863824), datetime_complete=datetime.datetime(2024, 4, 14, 19, 49, 34, 200247), params={'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=6, value=None)


* Best Score for C-index:
 0.7606462401124408

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16288138036147135
Fold 2 IBS: 0.22502147963154592
Fold 3 IBS: 0.16084750871908832
Fold 4 IBS: 0.153905071277276
Fold 5 IBS: 0.24085852935514676
[I 2024-04-14 19:53:06,981] Trial 0 finished with value: 0.18870279386890568 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.18870279386890568.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-14 19:53:13,675] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.18870279386890568.
Fold 1 IBS: 0.17149260378332234
Fold 2 IBS: 0.2080018472108657
Fold 3 IBS: 0.16804448110313522
Fold 4 IBS: 0.16836325797231982
Fold 5 IBS: 0.22800181350901766
[I 2024-04-14 19:53:19,768] Trial 2 finished with value: 0.18878080071573217 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.18870279386890568.
Fold 1 IBS: 0.17254508685748612
Fold 2 IBS: 0.20152882144812936
Fold 3 IBS: 0.16870056605308822
Fold 4 IBS: 0.1700909861228134
Fold 5 IBS: 0.22546168740018147
[I 2024-04-14 19:53:22,024] Trial 3 finished with value: 0.18766542957633972 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 3 with value: 0.18766542957633972.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-14 19:53:27,628] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 3 with value: 0.18766542957633972.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-14 19:53:30,343] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 3 with value: 0.18766542957633972.
Fold 1 IBS: 0.16245470063298256
Fold 2 IBS: 0.22297382074993694
Fold 3 IBS: 0.16203424613292677
Fold 4 IBS: 0.15407750256980196
Fold 5 IBS: 0.24155633383068228
[I 2024-04-14 19:53:35,862] Trial 6 finished with value: 0.18861932078326613 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 3 with value: 0.18766542957633972.
Fold 1 IBS: 0.16524980386156615
Fold 2 IBS: 0.2144692422844728
Fold 3 IBS: 0.16170554584026708
Fold 4 IBS: 0.15498969057806736
Fold 5 IBS: 0.24022133342012852
[I 2024-04-14 19:53:39,481] Trial 7 finished with value: 0.1873271231969004 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 7 with value: 0.1873271231969004.
Fold 1 IBS: 0.17068699302094284
Fold 2 IBS: 0.20138087999260362
Fold 3 IBS: 0.1724392451209917
Fold 4 IBS: 0.16997374719003946
Fold 5 IBS: 0.22864137051941913
[I 2024-04-14 19:53:40,221] Trial 8 finished with value: 0.18862444716879936 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 7 with value: 0.1873271231969004.
Fold 1 IBS: 0.17901663675354515
Fold 2 IBS: 0.20640270560713972
Fold 3 IBS: 0.1784689276584596
Fold 4 IBS: 0.189390893277579
Fold 5 IBS: 0.21680540160164022
[I 2024-04-14 19:53:46,844] Trial 9 finished with value: 0.19401691297967272 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 7 with value: 0.1873271231969004.
Fold 1 IBS: 0.2139976337400846
Fold 2 IBS: 0.22078850566211056
Fold 3 IBS: 0.20468678510920732
Fold 4 IBS: 0.2246562137512858
Fold 5 IBS: 0.21763185598455237
[I 2024-04-14 19:53:49,063] Trial 10 finished with value: 0.21635219884944812 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 98, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.21752764504502275, 'min_weight_fraction_leaf': 0.20722772178871404}. Best is trial 7 with value: 0.1873271231969004.
Fold 1 IBS: 0.16350533586159224
Fold 2 IBS: 0.22265514746117346
Fold 3 IBS: 0.16433373059394119
Fold 4 IBS: 0.16164658914965607
Fold 5 IBS: 0.2341832643780835
[I 2024-04-14 19:53:51,615] Trial 11 finished with value: 0.1892648134888893 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 194, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9798332536002032, 'min_weight_fraction_leaf': 0.13345925232590167}. Best is trial 7 with value: 0.1873271231969004.
Fold 1 IBS: 0.17236924756773409
Fold 2 IBS: 0.20289758579085762
Fold 3 IBS: 0.16935840385923984
Fold 4 IBS: 0.17013503088738427
Fold 5 IBS: 0.22513795305342799
[I 2024-04-14 19:53:53,641] Trial 12 finished with value: 0.18797964423172875 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 147, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9875774209352016, 'min_weight_fraction_leaf': 0.0015197051201851358}. Best is trial 7 with value: 0.1873271231969004.
Fold 1 IBS: 0.17149769325088668
Fold 2 IBS: 0.20842629431452472
Fold 3 IBS: 0.17144770617084998
Fold 4 IBS: 0.17205495938516502
Fold 5 IBS: 0.22793624380373065
[I 2024-04-14 19:53:57,938] Trial 13 finished with value: 0.19027257938503142 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8757004183768704, 'min_weight_fraction_leaf': 0.1752876802164367}. Best is trial 7 with value: 0.1873271231969004.
Fold 1 IBS: 0.16672985545755176
Fold 2 IBS: 0.2248257442315419
Fold 3 IBS: 0.17003447615006512
Fold 4 IBS: 0.16497816894317469
Fold 5 IBS: 0.24261615038813292
[I 2024-04-14 19:53:58,561] Trial 14 finished with value: 0.19383687903409325 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 24, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9015509519801813, 'min_weight_fraction_leaf': 0.07318050492704681}. Best is trial 7 with value: 0.1873271231969004.

Fold 1 IBS: 0.21402571838297463
Fold 2 IBS: 0.22150578362269344
Fold 3 IBS: 0.20486719358762567
Fold 4 IBS: 0.2246713507127308
Fold 5 IBS: 0.21875361315084252
[I 2024-04-14 19:54:01,973] Trial 15 finished with value: 0.2167647318913734 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 236, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6848920852575429, 'min_weight_fraction_leaf': 0.4149613316617927}. Best is trial 7 with value: 0.1873271231969004.
Fold 1 IBS: 0.213946792040553
Fold 2 IBS: 0.22131646588785617
Fold 3 IBS: 0.2048369428447834
Fold 4 IBS: 0.22482793804845522
Fold 5 IBS: 0.21889228866802798
[I 2024-04-14 19:54:03,642] Trial 16 finished with value: 0.21676408549793513 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 122, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.34623136307464575, 'min_weight_fraction_leaf': 0.10031974876705246}. Best is trial 7 with value: 0.1873271231969004.
Fold 1 IBS: 0.16658836379072653
Fold 2 IBS: 0.20662850247137693
Fold 3 IBS: 0.17037173900043134
Fold 4 IBS: 0.17197475760611058
Fold 5 IBS: 0.22566925173714572
[I 2024-04-14 19:54:08,195] Trial 17 finished with value: 0.18824652292115823 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 334, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.873523510010664, 'min_weight_fraction_leaf': 0.042960149453325644}. Best is trial 7 with value: 0.1873271231969004.
Fold 1 IBS: 0.213919779138921
Fold 2 IBS: 0.22049682976286125
Fold 3 IBS: 0.20515526931206013
Fold 4 IBS: 0.2251195030683997
Fold 5 IBS: 0.217073190065496
[I 2024-04-14 19:54:12,873] Trial 18 finished with value: 0.21635291426954764 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 267, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.18699867385795615}. Best is trial 7 with value: 0.1873271231969004.
Fold 1 IBS: 0.17245726039257062
Fold 2 IBS: 0.20663140550444542
Fold 3 IBS: 0.1717675992929485
Fold 4 IBS: 0.1740905672175271
Fold 5 IBS: 0.2236420845930405
[I 2024-04-14 19:54:15,407] Trial 19 finished with value: 0.18971778340010642 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 177, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7125469453628018, 'min_weight_fraction_leaf': 0.1364050255575767}. Best is trial 7 with value: 0.1873271231969004.
Fold 1 IBS: 0.1787290356305373
Fold 2 IBS: 0.20652817223360212
Fold 3 IBS: 0.17756715294410516
Fold 4 IBS: 0.18776208467832742
Fold 5 IBS: 0.2183034887476173
[I 2024-04-14 19:54:20,261] Trial 20 finished with value: 0.19377798684683786 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 3, 'n_estimators': 373, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9366887134798574, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 7 with value: 0.1873271231969004.
Fold 1 IBS: 0.1717520134609293
Fold 2 IBS: 0.20159941778075263
Fold 3 IBS: 0.16913999789527254
Fold 4 IBS: 0.16919765901426329
Fold 5 IBS: 0.226559605906839
[I 2024-04-14 19:54:22,059] Trial 21 finished with value: 0.18764973881161134 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 124, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9816279883818305, 'min_weight_fraction_leaf': 0.0038003409523026145}. Best is trial 7 with value: 0.1873271231969004.
Fold 1 IBS: 0.17258505369397767
Fold 2 IBS: 0.2057880316380233
Fold 3 IBS: 0.17143375707838115
Fold 4 IBS: 0.1720045053097036
Fold 5 IBS: 0.227597459409273
[I 2024-04-14 19:54:23,103] Trial 22 finished with value: 0.18988176142587174 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 72, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8351213511998469, 'min_weight_fraction_leaf': 0.030861194304502102}. Best is trial 7 with value: 0.1873271231969004.
Fold 1 IBS: 0.17178832078858
Fold 2 IBS: 0.20571154056794394
Fold 3 IBS: 0.16517272388697435
Fold 4 IBS: 0.1650492455082524
Fold 5 IBS: 0.22847652045936664
[I 2024-04-14 19:54:25,002] Trial 23 finished with value: 0.18723967024222346 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 138, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9681854285530797, 'min_weight_fraction_leaf': 0.09741404912478352}. Best is trial 23 with value: 0.18723967024222346.
Fold 1 IBS: 0.17130089602121504
Fold 2 IBS: 0.21118692772080155
Fold 3 IBS: 0.16490129954788263
Fold 4 IBS: 0.16285741829324882
Fold 5 IBS: 0.23075749345878824
[I 2024-04-14 19:54:28,720] Trial 24 finished with value: 0.1882008070083873 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 235, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9972878267649227, 'min_weight_fraction_leaf': 0.030860618207937125}. Best is trial 23 with value: 0.18723967024222346.
Fold 1 IBS: 0.16365417841742477
Fold 2 IBS: 0.23371310522615105
Fold 3 IBS: 0.1603690699267377
Fold 4 IBS: 0.14944615804095296
Fold 5 IBS: 0.24751521163828638
[I 2024-04-14 19:54:31,121] Trial 25 finished with value: 0.19093954464991056 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 89, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9125256795505968, 'min_weight_fraction_leaf': 0.05643055281185064}. Best is trial 23 with value: 0.18723967024222346.
Fold 1 IBS: 0.16352518928925952
Fold 2 IBS: 0.22416799287229902
Fold 3 IBS: 0.16054214216397628
Fold 4 IBS: 0.1615230609981379
Fold 5 IBS: 0.24372081909113055
[I 2024-04-14 19:54:31,726] Trial 26 finished with value: 0.19069584088296068 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 14, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9416396746350906, 'min_weight_fraction_leaf': 0.0036682972713528504}. Best is trial 23 with value: 0.18723967024222346.
Fold 1 IBS: 0.17285240060934456
Fold 2 IBS: 0.25812584629196295
Fold 3 IBS: 0.16675837403554275
Fold 4 IBS: 0.16130761423636222
Fold 5 IBS: 0.24228147693934293
[I 2024-04-14 19:54:34,035] Trial 27 finished with value: 0.2002651424225111 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 128, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8463896691565567, 'min_weight_fraction_leaf': 0.09344601939713111}. Best is trial 23 with value: 0.18723967024222346.
Fold 1 IBS: 0.17679082416105418
Fold 2 IBS: 0.20620403904700962
Fold 3 IBS: 0.1744428454670958
Fold 4 IBS: 0.18276004991295816
Fold 5 IBS: 0.22023846642742292
[I 2024-04-14 19:54:39,026] Trial 28 finished with value: 0.19208724500310814 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 301, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7221545658945444, 'min_weight_fraction_leaf': 0.23579505170114406}. Best is trial 23 with value: 0.18723967024222346.
Fold 1 IBS: 0.16267741658550489
Fold 2 IBS: 0.22186709552582579
Fold 3 IBS: 0.16270206493307304
Fold 4 IBS: 0.15519174541469966
Fold 5 IBS: 0.23958156790456925
[I 2024-04-14 19:54:44,084] Trial 29 finished with value: 0.1884039780727345 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 376, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6027835966097373, 'min_weight_fraction_leaf': 0.08962850536510933}. Best is trial 23 with value: 0.18723967024222346.

Fold 1 IBS: 0.2042662673434637
Fold 2 IBS: 0.21546039940178915
Fold 3 IBS: 0.19877151930321105
Fold 4 IBS: 0.218842890661761
Fold 5 IBS: 0.21704441300512034
[I 2024-04-14 19:54:47,085] Trial 30 finished with value: 0.21087709794306903 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 225, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.36648983755402775, 'min_weight_fraction_leaf': 0.17141436902843765}. Best is trial 23 with value: 0.18723967024222346.
Fold 1 IBS: 0.1727569377514147
Fold 2 IBS: 0.20374901180658242
Fold 3 IBS: 0.1692787734812299
Fold 4 IBS: 0.17063432820059057
Fold 5 IBS: 0.22515507125242631
[I 2024-04-14 19:54:49,430] Trial 31 finished with value: 0.18831482449844877 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 160, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7936940810190021, 'min_weight_fraction_leaf': 0.11944690515416108}. Best is trial 23 with value: 0.18723967024222346.
Fold 1 IBS: 0.17082516696861785
Fold 2 IBS: 0.20295887736813245
Fold 3 IBS: 0.1668456486497358
Fold 4 IBS: 0.16592654826154385
Fold 5 IBS: 0.22885049649670794
[I 2024-04-14 19:54:51,198] Trial 32 finished with value: 0.1870813475489476 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9467713628420997, 'min_weight_fraction_leaf': 0.03489941118533926}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.1706715395415048
Fold 2 IBS: 0.20898054756591636
Fold 3 IBS: 0.16886955650664365
Fold 4 IBS: 0.16515229339965767
Fold 5 IBS: 0.2314079265770464
[I 2024-04-14 19:54:52,254] Trial 33 finished with value: 0.18901637271815375 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 61, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9498414139143342, 'min_weight_fraction_leaf': 0.04865140621428596}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.17103167433031471
Fold 2 IBS: 0.2030313908469882
Fold 3 IBS: 0.16583409411336883
Fold 4 IBS: 0.1661857007458151
Fold 5 IBS: 0.2298570818005873
[I 2024-04-14 19:54:53,962] Trial 34 finished with value: 0.18718798836741482 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 107, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9978445403969509, 'min_weight_fraction_leaf': 0.06869132605254595}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.17217111100183696
Fold 2 IBS: 0.24389043432820226
Fold 3 IBS: 0.15345474592628888
Fold 4 IBS: 0.14840660180701543
Fold 5 IBS: 0.2505732652999061
[I 2024-04-14 19:54:58,097] Trial 35 finished with value: 0.1936992316726499 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 212, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9010743484673644, 'min_weight_fraction_leaf': 0.06420550431132266}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.17202914792486312
Fold 2 IBS: 0.201511770770304
Fold 3 IBS: 0.16751802827864132
Fold 4 IBS: 0.1667331032267069
Fold 5 IBS: 0.22858904276194644
[I 2024-04-14 19:55:00,242] Trial 36 finished with value: 0.18727621859249238 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 114, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8497230302094902, 'min_weight_fraction_leaf': 0.09974189651559592}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.17154274345206488
Fold 2 IBS: 0.2042709148480455
Fold 3 IBS: 0.16882729591291185
Fold 4 IBS: 0.16783737461514397
Fold 5 IBS: 0.22979500554230825
[I 2024-04-14 19:55:02,947] Trial 37 finished with value: 0.1884546668740949 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 96, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8552885702354539, 'min_weight_fraction_leaf': 0.10528820328094213}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.17198049279085617
Fold 2 IBS: 0.20626929697309102
Fold 3 IBS: 0.17342459694538206
Fold 4 IBS: 0.1711099961198407
Fold 5 IBS: 0.22718442959457683
[I 2024-04-14 19:55:04,209] Trial 38 finished with value: 0.18999376248474936 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 48, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.48791124460782864, 'min_weight_fraction_leaf': 0.07693041038736904}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.17230455820716886
Fold 2 IBS: 0.2069420182920684
Fold 3 IBS: 0.17195104742134099
Fold 4 IBS: 0.17365780625055713
Fold 5 IBS: 0.22369498897645682
[I 2024-04-14 19:55:07,554] Trial 39 finished with value: 0.18971008382951843 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 172, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7439004429227261, 'min_weight_fraction_leaf': 0.16257556751528263}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.16296670037907784
Fold 2 IBS: 0.22295350237012948
Fold 3 IBS: 0.1662355848056459
Fold 4 IBS: 0.16240030106404307
Fold 5 IBS: 0.23451703679905014
[I 2024-04-14 19:55:09,324] Trial 40 finished with value: 0.18981462508358932 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 134, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9417029986331577, 'min_weight_fraction_leaf': 0.2152683276906891}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.17188888453692766
Fold 2 IBS: 0.20303252833977858
Fold 3 IBS: 0.16822403328182475
Fold 4 IBS: 0.16777474522389854
Fold 5 IBS: 0.2290423740149922
[I 2024-04-14 19:55:10,717] Trial 41 finished with value: 0.18799251307948434 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 101, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8269291103971079, 'min_weight_fraction_leaf': 0.07582105133614225}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.17121550059681617
Fold 2 IBS: 0.20790206937533623
Fold 3 IBS: 0.1668381456663272
Fold 4 IBS: 0.16071709474305798
Fold 5 IBS: 0.23196736347746094
[I 2024-04-14 19:55:12,057] Trial 42 finished with value: 0.1877280347717997 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 71, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9963323778595055, 'min_weight_fraction_leaf': 0.02801213278786406}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.17541419559580299
Fold 2 IBS: 0.20518977794279628
Fold 3 IBS: 0.1725911452266295
Fold 4 IBS: 0.17732674945760188
Fold 5 IBS: 0.22175437726499223
[I 2024-04-14 19:55:14,638] Trial 43 finished with value: 0.19045524909756456 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 192, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9066582336292186, 'min_weight_fraction_leaf': 0.27764552944355786}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.16302656081487943
Fold 2 IBS: 0.2217085086192639
Fold 3 IBS: 0.16209313197314365
Fold 4 IBS: 0.15645966638573766
Fold 5 IBS: 0.2373770474498472
[I 2024-04-14 19:55:17,500] Trial 44 finished with value: 0.18813298304857434 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 150, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9497581198045654, 'min_weight_fraction_leaf': 0.11873435420263456}. Best is trial 32 with value: 0.1870813475489476.

Fold 1 IBS: 0.16460134502827933
Fold 2 IBS: 0.21567665564125096
Fold 3 IBS: 0.15786962924361955
Fold 4 IBS: 0.1457081538984672
Fold 5 IBS: 0.2517810541892506
[I 2024-04-14 19:55:18,150] Trial 45 finished with value: 0.18712736760017354 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 34, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8844796228624537, 'min_weight_fraction_leaf': 0.024268316111900768}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.17197178823708986
Fold 2 IBS: 0.19954592203746543
Fold 3 IBS: 0.17248894130385498
Fold 4 IBS: 0.17214941944677983
Fold 5 IBS: 0.22837206144180622
[I 2024-04-14 19:55:19,140] Trial 46 finished with value: 0.18890562649339926 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 39, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7992034162550746, 'min_weight_fraction_leaf': 0.1530059334514427}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.1657885121201458
Fold 2 IBS: 0.23161845430561107
Fold 3 IBS: 0.17200585629274692
Fold 4 IBS: 0.15847652061812695
Fold 5 IBS: 0.23165392992827155
[I 2024-04-14 19:55:19,553] Trial 47 finished with value: 0.19190865465298046 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 3, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6727571273801307, 'min_weight_fraction_leaf': 0.03077202359944741}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.17161131895230355
Fold 2 IBS: 0.20223985394938673
Fold 3 IBS: 0.167457491887336
Fold 4 IBS: 0.16646080523716994
Fold 5 IBS: 0.22842863205029554
[I 2024-04-14 19:55:21,715] Trial 48 finished with value: 0.18723962041529835 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 108, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8719740550505432, 'min_weight_fraction_leaf': 0.018114098368037818}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.16093378897298652
Fold 2 IBS: 0.22751164214294142
Fold 3 IBS: 0.1623680558940554
Fold 4 IBS: 0.15458953319227192
Fold 5 IBS: 0.25015101774340615
[I 2024-04-14 19:55:23,268] Trial 49 finished with value: 0.19111080758913226 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 73, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6074542393026403, 'min_weight_fraction_leaf': 0.023009366671032244}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.1694739778959831
Fold 2 IBS: 0.20386943516274234
Fold 3 IBS: 0.17026694940813641
Fold 4 IBS: 0.17457142885044863
Fold 5 IBS: 0.22676840954278688
[I 2024-04-14 19:55:24,129] Trial 50 finished with value: 0.18899004017201945 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 37, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8896541801657883, 'min_weight_fraction_leaf': 0.058128514801969955}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.17244707352433503
Fold 2 IBS: 0.2024388863661349
Fold 3 IBS: 0.1667867519265173
Fold 4 IBS: 0.1685964125633003
Fold 5 IBS: 0.22827662839586493
[I 2024-04-14 19:55:26,374] Trial 51 finished with value: 0.18770915055523046 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 109, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7525236194817052, 'min_weight_fraction_leaf': 0.08933210580193499}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.172704620037584
Fold 2 IBS: 0.2043138297690377
Fold 3 IBS: 0.1698068863994041
Fold 4 IBS: 0.1701038142937065
Fold 5 IBS: 0.229377745396016
[I 2024-04-14 19:55:28,211] Trial 52 finished with value: 0.18926137917914965 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 88, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8161265516097091, 'min_weight_fraction_leaf': 0.012876902678362334}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.17274067282549094
Fold 2 IBS: 0.20403646367236186
Fold 3 IBS: 0.169350498945671
Fold 4 IBS: 0.1696387117077005
Fold 5 IBS: 0.22564047329483214
[I 2024-04-14 19:55:30,985] Trial 53 finished with value: 0.1882813640892113 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 145, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8719640181408611, 'min_weight_fraction_leaf': 0.04969213392863425}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.2051724571723132
Fold 2 IBS: 0.21553724713921085
Fold 3 IBS: 0.19783466839969524
Fold 4 IBS: 0.21633489903056458
Fold 5 IBS: 0.21690552605171004
[I 2024-04-14 19:55:32,649] Trial 54 finished with value: 0.2103569595586988 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 112, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9573598153717632, 'min_weight_fraction_leaf': 0.4522260564219586}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.17224409005316513
Fold 2 IBS: 0.20392889020709162
Fold 3 IBS: 0.1670519041751036
Fold 4 IBS: 0.16707728062542598
Fold 5 IBS: 0.22769216266909473
[I 2024-04-14 19:55:34,949] Trial 55 finished with value: 0.1875988655459762 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 173, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9130603026739327, 'min_weight_fraction_leaf': 0.12040122254898125}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.1609484594250459
Fold 2 IBS: 0.2251530280908215
Fold 3 IBS: 0.16442707751604788
Fold 4 IBS: 0.15376833452331376
Fold 5 IBS: 0.243454280659294
[I 2024-04-14 19:55:36,274] Trial 56 finished with value: 0.1895502360429046 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 54, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8583550875234618, 'min_weight_fraction_leaf': 0.07165710507302428}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.17136047590199913
Fold 2 IBS: 0.2531927468881135
Fold 3 IBS: 0.15261860992642878
Fold 4 IBS: 0.15320347382964614
Fold 5 IBS: 0.25551481809023974
[I 2024-04-14 19:55:37,715] Trial 57 finished with value: 0.19717802492728548 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 82, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7727343581454843, 'min_weight_fraction_leaf': 0.1036605645426078}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.16888238559367455
Fold 2 IBS: 0.20234514243319376
Fold 3 IBS: 0.1700034483164381
Fold 4 IBS: 0.16864882503077103
Fold 5 IBS: 0.23103545941838788
[I 2024-04-14 19:55:38,237] Trial 58 finished with value: 0.18818305215849307 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 20, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9681682457727072, 'min_weight_fraction_leaf': 0.01753271094481916}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.1735526275061309
Fold 2 IBS: 0.20039544957772867
Fold 3 IBS: 0.17394440393409036
Fold 4 IBS: 0.1884347942462772
Fold 5 IBS: 0.21633246499235992
[I 2024-04-14 19:55:40,542] Trial 59 finished with value: 0.1905319480513174 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 118, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9232603866316391, 'min_weight_fraction_leaf': 0.3787205021140745}. Best is trial 32 with value: 0.1870813475489476.

Fold 1 IBS: 0.1721755182324898
Fold 2 IBS: 0.20424076197040372
Fold 3 IBS: 0.17136470654034283
Fold 4 IBS: 0.1728480603669238
Fold 5 IBS: 0.22380784968166043
[I 2024-04-14 19:55:43,075] Trial 60 finished with value: 0.18888737935836414 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 144, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8749347745790171, 'min_weight_fraction_leaf': 0.1938967869214744}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.16566184498778544
Fold 2 IBS: 0.21468910294737692
Fold 3 IBS: 0.16148400541808713
Fold 4 IBS: 0.15479932358755302
Fold 5 IBS: 0.24070319617381242
[I 2024-04-14 19:55:47,032] Trial 61 finished with value: 0.18746749462292298 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 275, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.996093391336487, 'min_weight_fraction_leaf': 0.042496619692871725}. Best is trial 32 with value: 0.1870813475489476.
Fold 1 IBS: 0.16220784542940764
Fold 2 IBS: 0.21591352496153995
Fold 3 IBS: 0.1612401017994063
Fold 4 IBS: 0.15281096286225648
Fold 5 IBS: 0.24104997442286566
[I 2024-04-14 19:55:52,863] Trial 62 finished with value: 0.18664448189509522 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 307, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9777662223708034, 'min_weight_fraction_leaf': 0.03897833366491754}. Best is trial 62 with value: 0.18664448189509522.
Fold 1 IBS: 0.16086751346672098
Fold 2 IBS: 0.21653173654274255
Fold 3 IBS: 0.16098956528344432
Fold 4 IBS: 0.1525339376640402
Fold 5 IBS: 0.24203899684465358
[I 2024-04-14 19:55:58,441] Trial 63 finished with value: 0.18659234996032031 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 334, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9630534259899874, 'min_weight_fraction_leaf': 0.0005575713195467152}. Best is trial 63 with value: 0.18659234996032031.
Fold 1 IBS: 0.1648170695384265
Fold 2 IBS: 0.2055786264964724
Fold 3 IBS: 0.1702883442554507
Fold 4 IBS: 0.1723685793586588
Fold 5 IBS: 0.22536672704307512
[I 2024-04-14 19:56:04,114] Trial 64 finished with value: 0.18768386933841671 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 343, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9660852881060265, 'min_weight_fraction_leaf': 0.0027197203828310604}. Best is trial 63 with value: 0.18659234996032031.
Fold 1 IBS: 0.1615317277264539
Fold 2 IBS: 0.21875294093814557
Fold 3 IBS: 0.16131773348319814
Fold 4 IBS: 0.15118367627623489
Fold 5 IBS: 0.23940756614310663
[I 2024-04-14 19:56:08,611] Trial 65 finished with value: 0.18643872891342783 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 298, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9998876734254035, 'min_weight_fraction_leaf': 0.015037452722512641}. Best is trial 65 with value: 0.18643872891342783.
Fold 1 IBS: 0.1590358040893782
Fold 2 IBS: 0.2177544200869057
Fold 3 IBS: 0.16160797528366663
Fold 4 IBS: 0.1509962553606222
Fold 5 IBS: 0.23864008260067665
[I 2024-04-14 19:56:12,359] Trial 66 finished with value: 0.1856069074842499 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 285, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9283799116645701, 'min_weight_fraction_leaf': 0.017379391355936087}. Best is trial 66 with value: 0.1856069074842499.
Fold 1 IBS: 0.16113727302275194
Fold 2 IBS: 0.2171722704645362
Fold 3 IBS: 0.16164776332326802
Fold 4 IBS: 0.15161795237094333
Fold 5 IBS: 0.24121918794104485
[I 2024-04-14 19:56:16,580] Trial 67 finished with value: 0.18655888942450885 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 301, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9297170195636226, 'min_weight_fraction_leaf': 0.03968181972003887}. Best is trial 66 with value: 0.1856069074842499.
Fold 1 IBS: 0.1590681651602398
Fold 2 IBS: 0.20925009706814965
Fold 3 IBS: 0.16108191332793284
Fold 4 IBS: 0.15467154290979152
Fold 5 IBS: 0.23549668307013616
[I 2024-04-14 19:56:20,860] Trial 68 finished with value: 0.18391368030725 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 289, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9252428240847322, 'min_weight_fraction_leaf': 0.039853224378856605}. Best is trial 68 with value: 0.18391368030725.
Fold 1 IBS: 0.1596108290720611
Fold 2 IBS: 0.20906505015571958
Fold 3 IBS: 0.16100946752473116
Fold 4 IBS: 0.1545881863522362
Fold 5 IBS: 0.23521521879317997
[I 2024-04-14 19:56:26,045] Trial 69 finished with value: 0.1838977503795856 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 296, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.919863043439366, 'min_weight_fraction_leaf': 0.04085459253165534}. Best is trial 69 with value: 0.1838977503795856.
Fold 1 IBS: 0.167408143493023
Fold 2 IBS: 0.20519677206576897
Fold 3 IBS: 0.17019247330813192
Fold 4 IBS: 0.17264632825081294
Fold 5 IBS: 0.225345131222298
[I 2024-04-14 19:56:30,966] Trial 70 finished with value: 0.18815776966800696 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 293, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9259766802695595, 'min_weight_fraction_leaf': 0.05160393661353003}. Best is trial 69 with value: 0.1838977503795856.
Fold 1 IBS: 0.15880207732088816
Fold 2 IBS: 0.20946096328395983
Fold 3 IBS: 0.16110934503368426
Fold 4 IBS: 0.154318673204618
Fold 5 IBS: 0.23577533927325173
[I 2024-04-14 19:56:35,772] Trial 71 finished with value: 0.1838932796232804 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 327, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9320776906248162, 'min_weight_fraction_leaf': 0.0423665939791711}. Best is trial 71 with value: 0.1838932796232804.
Fold 1 IBS: 0.15774989669036726
Fold 2 IBS: 0.20863553181930303
Fold 3 IBS: 0.16080748265949016
Fold 4 IBS: 0.15395691888959737
Fold 5 IBS: 0.23513011565881622
[I 2024-04-14 19:56:40,219] Trial 72 finished with value: 0.18325598914351482 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 323, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9327683828924904, 'min_weight_fraction_leaf': 0.0006993958841116053}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.15817381095165498
Fold 2 IBS: 0.21017701262411825
Fold 3 IBS: 0.16124399676176918
Fold 4 IBS: 0.15393048223027442
Fold 5 IBS: 0.23614767432136982
[I 2024-04-14 19:56:44,771] Trial 73 finished with value: 0.18393459537783732 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 334, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9039578233356079, 'min_weight_fraction_leaf': 0.0006622619625605787}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.15844398605810295
Fold 2 IBS: 0.2088879294429569
Fold 3 IBS: 0.16100452749453584
Fold 4 IBS: 0.15427755614199504
Fold 5 IBS: 0.23555010945870636
[I 2024-04-14 19:56:49,470] Trial 74 finished with value: 0.1836328217192594 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 287, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9193346683757525, 'min_weight_fraction_leaf': 0.009807625309946924}. Best is trial 72 with value: 0.18325598914351482.

Fold 1 IBS: 0.1695148548794243
Fold 2 IBS: 0.20771576818012474
Fold 3 IBS: 0.17158831703903973
Fold 4 IBS: 0.17124188587680744
Fold 5 IBS: 0.22438039278811733
[I 2024-04-14 19:56:54,984] Trial 75 finished with value: 0.18888824375270272 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 401, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.23979984596241344, 'min_weight_fraction_leaf': 0.013866964013846085}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.1594524165745049
Fold 2 IBS: 0.20755017478644808
Fold 3 IBS: 0.16071222223169898
Fold 4 IBS: 0.15521955079153346
Fold 5 IBS: 0.23506958218150567
[I 2024-04-14 19:56:58,722] Trial 76 finished with value: 0.18360078931313822 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 256, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8241791480617434, 'min_weight_fraction_leaf': 0.013254563155871342}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.16355594340055996
Fold 2 IBS: 0.20830166494109534
Fold 3 IBS: 0.16203985367834664
Fold 4 IBS: 0.1576126878107317
Fold 5 IBS: 0.23397383011201245
[I 2024-04-14 19:57:03,104] Trial 77 finished with value: 0.1850967959885492 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 254, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8144241301111692, 'min_weight_fraction_leaf': 0.0580732335192009}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.1680295297571241
Fold 2 IBS: 0.20739275112211095
Fold 3 IBS: 0.1707509681015335
Fold 4 IBS: 0.17270299917603468
Fold 5 IBS: 0.22500888014162232
[I 2024-04-14 19:57:09,278] Trial 78 finished with value: 0.1887770256596851 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 320, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8252996885793923, 'min_weight_fraction_leaf': 0.0580204941848831}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.2140121461627958
Fold 2 IBS: 0.2214593672376525
Fold 3 IBS: 0.20481275748989913
Fold 4 IBS: 0.22467686957468572
Fold 5 IBS: 0.2188282174455177
[I 2024-04-14 19:57:13,411] Trial 79 finished with value: 0.21675787158211018 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 256, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7245414962641552, 'min_weight_fraction_leaf': 0.4970767359615762}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.1668311107860829
Fold 2 IBS: 0.2107161033034672
Fold 3 IBS: 0.1644380683891753
Fold 4 IBS: 0.16147621470670248
Fold 5 IBS: 0.23185682414878234
[I 2024-04-14 19:57:20,243] Trial 80 finished with value: 0.18706366426684204 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 354, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8033138015435407, 'min_weight_fraction_leaf': 0.0789898761862941}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.16640688664691272
Fold 2 IBS: 0.2035031363635675
Fold 3 IBS: 0.16942780115588968
Fold 4 IBS: 0.17256110638343697
Fold 5 IBS: 0.2247284402720098
[I 2024-04-14 19:57:24,101] Trial 81 finished with value: 0.18732547416436335 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 248, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9036605914476872, 'min_weight_fraction_leaf': 0.009782638120179038}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.1606560371047693
Fold 2 IBS: 0.20765632006606874
Fold 3 IBS: 0.16128344742128642
Fold 4 IBS: 0.1551500396786509
Fold 5 IBS: 0.2367504839071054
[I 2024-04-14 19:57:29,148] Trial 82 finished with value: 0.18429926563557616 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 278, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8407437547279819, 'min_weight_fraction_leaf': 0.032890817802186216}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.16061546669295226
Fold 2 IBS: 0.2069527331213602
Fold 3 IBS: 0.16129026139536623
Fold 4 IBS: 0.15473595906047966
Fold 5 IBS: 0.23633726319479723
[I 2024-04-14 19:57:34,502] Trial 83 finished with value: 0.1839863366929911 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 319, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8400806811513046, 'min_weight_fraction_leaf': 0.032992732656338765}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.16828621048887643
Fold 2 IBS: 0.20723555661411283
Fold 3 IBS: 0.1703578468840236
Fold 4 IBS: 0.1722715655818399
Fold 5 IBS: 0.2252623452665455
[I 2024-04-14 19:57:39,319] Trial 84 finished with value: 0.18868270496707965 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 318, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8935494873413659, 'min_weight_fraction_leaf': 0.04068369354674561}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.16032365556845304
Fold 2 IBS: 0.20881858733162714
Fold 3 IBS: 0.1613921827592968
Fold 4 IBS: 0.15459570751913745
Fold 5 IBS: 0.23599570646880205
[I 2024-04-14 19:57:44,151] Trial 85 finished with value: 0.18422516792946328 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 369, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8335076408393859, 'min_weight_fraction_leaf': 0.02391558383408241}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.1598921950774077
Fold 2 IBS: 0.21503193379279878
Fold 3 IBS: 0.16251391585302402
Fold 4 IBS: 0.15350421304962064
Fold 5 IBS: 0.23926901809648338
[I 2024-04-14 19:57:50,939] Trial 86 finished with value: 0.1860422551738669 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 378, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7843159116533064, 'min_weight_fraction_leaf': 0.0019316276354356642}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.1668283194321918
Fold 2 IBS: 0.2045367783381026
Fold 3 IBS: 0.17012503011793936
Fold 4 IBS: 0.17267031943181582
Fold 5 IBS: 0.22485246529276243
[I 2024-04-14 19:57:57,788] Trial 87 finished with value: 0.18780258252256238 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 393, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.874770740979965, 'min_weight_fraction_leaf': 0.02360889254176365}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.168468932743281
Fold 2 IBS: 0.21156046926431354
Fold 3 IBS: 0.16471854927231455
Fold 4 IBS: 0.1619709280441082
Fold 5 IBS: 0.23282020521343166
[I 2024-04-14 19:58:03,903] Trial 88 finished with value: 0.18790781690748978 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 325, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8372519222674444, 'min_weight_fraction_leaf': 0.08617294004215245}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.1587140216984096
Fold 2 IBS: 0.21065532831396502
Fold 3 IBS: 0.1612228090179556
Fold 4 IBS: 0.15414512096748872
Fold 5 IBS: 0.23585066875911664
[I 2024-04-14 19:58:09,600] Trial 89 finished with value: 0.1841175897513871 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 367, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9048759473037471, 'min_weight_fraction_leaf': 0.030001832503526914}. Best is trial 72 with value: 0.18325598914351482.

Fold 1 IBS: 0.16101381323581304
Fold 2 IBS: 0.22142678208246622
Fold 3 IBS: 0.16844591442133142
Fold 4 IBS: 0.16830133032697386
Fold 5 IBS: 0.22922568736706048
[I 2024-04-14 19:58:14,733] Trial 90 finished with value: 0.189682705486729 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 349, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.910485345327682, 'min_weight_fraction_leaf': 0.062300725609488405}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.16292721447506833
Fold 2 IBS: 0.21021704812030823
Fold 3 IBS: 0.16179671957605893
Fold 4 IBS: 0.15591862948847224
Fold 5 IBS: 0.23423617657961798
[I 2024-04-14 19:58:19,410] Trial 91 finished with value: 0.18501915764790514 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 363, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8522953614641384, 'min_weight_fraction_leaf': 0.044755036059723474}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.15833298012906172
Fold 2 IBS: 0.2095962104709589
Fold 3 IBS: 0.16070557364406327
Fold 4 IBS: 0.15448329084786291
Fold 5 IBS: 0.23481206790032882
[I 2024-04-14 19:58:24,826] Trial 92 finished with value: 0.18358602459845513 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 437, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8895227739240147, 'min_weight_fraction_leaf': 0.03150724852085034}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.16494285608568818
Fold 2 IBS: 0.20599742738883736
Fold 3 IBS: 0.17036721164958477
Fold 4 IBS: 0.17198396109146744
Fold 5 IBS: 0.22573462947013373
[I 2024-04-14 19:58:29,070] Trial 93 finished with value: 0.18780521713714232 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 334, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9352680119783262, 'min_weight_fraction_leaf': 0.030053763621747047}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.16318118583606941
Fold 2 IBS: 0.21437568713191882
Fold 3 IBS: 0.1609868603656891
Fold 4 IBS: 0.1538737391898903
Fold 5 IBS: 0.23812690174755421
[I 2024-04-14 19:58:34,872] Trial 94 finished with value: 0.1861088748542244 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 409, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8870097669829586, 'min_weight_fraction_leaf': 0.05063797663684119}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.1640497703828138
Fold 2 IBS: 0.21065587435587158
Fold 3 IBS: 0.1624592319488002
Fold 4 IBS: 0.15799315870466263
Fold 5 IBS: 0.2318997771923817
[I 2024-04-14 19:58:43,264] Trial 95 finished with value: 0.185411562516906 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 500, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8655959526377726, 'min_weight_fraction_leaf': 0.06889585971018593}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.15944185935693655
Fold 2 IBS: 0.21763400030598737
Fold 3 IBS: 0.16064036816042457
Fold 4 IBS: 0.15115996514489285
Fold 5 IBS: 0.2412331423778717
[I 2024-04-14 19:58:48,189] Trial 96 finished with value: 0.18602186706922258 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 311, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9507935143867366, 'min_weight_fraction_leaf': 0.00821946415181404}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.17347644411130606
Fold 2 IBS: 0.20777857092215826
Fold 3 IBS: 0.17312851455030265
Fold 4 IBS: 0.17763647399478028
Fold 5 IBS: 0.2228238718151694
[I 2024-04-14 19:58:54,424] Trial 97 finished with value: 0.1909687750787433 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2, 'n_estimators': 427, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8971136068679096, 'min_weight_fraction_leaf': 0.03153074921869038}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.1742803056332576
Fold 2 IBS: 0.23144131020959882
Fold 3 IBS: 0.16842059771268747
Fold 4 IBS: 0.16366116815829992
Fold 5 IBS: 0.23179813165644966
[I 2024-04-14 19:59:00,404] Trial 98 finished with value: 0.1939203026740587 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 450, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9123964149540856, 'min_weight_fraction_leaf': 0.3369223245204542}. Best is trial 72 with value: 0.18325598914351482.
Fold 1 IBS: 0.1736131799316684
Fold 2 IBS: 0.20746310773664414
Fold 3 IBS: 0.17250208364898265
Fold 4 IBS: 0.17609418158362627
Fold 5 IBS: 0.2239829744342374
[I 2024-04-14 19:59:04,244] Trial 99 finished with value: 0.19073110546703176 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 237, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.49281648155563273, 'min_weight_fraction_leaf': 0.08009752236637466}. Best is trial 72 with value: 0.18325598914351482.


* Best trial for IBS:
 FrozenTrial(number=72, state=TrialState.COMPLETE, values=[0.18325598914351482], datetime_start=datetime.datetime(2024, 4, 14, 19, 56, 35, 785377), datetime_complete=datetime.datetime(2024, 4, 14, 19, 56, 40, 218978), params={'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 323, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9327683828924904, 'min_weight_fraction_leaf': 0.0006993958841116053}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=72, value=None)


* Best Score for IBS:
 0.18325598914351482

In [56]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [57]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.761
train_ibs:  0.183

#### Test

In [58]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [59]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=14, max_features='log2', max_leaf_nodes=4,
                   max_samples=0.5693797534575991, min_samples_leaf=7,
                   min_samples_split=4,
                   min_weight_fraction_leaf=0.001344032287160346,
                   n_estimators=424, random_state=123, warm_start=True)

C-index score: 0.608

ExtraSurvivalTrees(max_depth=2, max_features=1, max_leaf_nodes=14,
                   max_samples=0.9327683828924904, min_samples_split=18,
                   min_weight_fraction_leaf=0.0006993958841116053,
                   n_estimators=323, random_state=123)

IBS: 0.213

In [60]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [61]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 19:59:06,441] A new study created in memory with name: no-name-3a814310-8b86-43e7-94fa-2e401bf26b2b

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:59:36,946] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:59:51,314] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:00:07,207] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:00:33,194] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:00:42,577] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:00:44,824] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:01:10,362] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:01:19,349] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:01:20,193] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 20:02:20,970] Trial 9 finished with value: 0.7251347360205367 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 20:03:48,606] Trial 10 finished with value: 0.685844917453683 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:05:25,695] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 20:06:50,429] Trial 12 finished with value: 0.7178121706956011 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:07:34,998] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:08:32,296] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:09:28,340] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:10:07,197] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:11:18,842] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:12:59,374] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:13:04,754] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:13:41,970] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 20:15:02,173] Trial 21 finished with value: 0.5772199484787512 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 20:16:11,828] Trial 22 finished with value: 0.7074432574939246 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:17:16,161] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:18:37,547] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:19:13,086] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5558035714285714
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 20:20:20,737] Trial 26 finished with value: 0.5351043762575453 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:21:59,216] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:23:08,571] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:23:50,195] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:24:38,055] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 20:26:00,778] Trial 31 finished with value: 0.6331023014199277 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:27:29,060] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:28:15,975] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:29:32,035] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:29:47,643] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:31:01,231] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:31:04,407] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:31:36,463] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:32:23,276] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:33:38,791] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 20:33:39,132] Trial 41 finished with value: 0.669385375890579 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 20:33:47,829] Trial 42 finished with value: 0.7134801645905124 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:33:57,712] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8842674505407576, 'learning_rate': 0.01661025860323942, 'dropout_rate': 0.11585930219083569, 'n_estimators': 137, 'criterion': 'squared_error', 'ccp_alpha': 1.1648976852393267, 'min_weight_fraction_leaf': 0.2628710582683432, 'max_features': 'auto', 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.8573418806492034, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:34:20,107] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9369906738516638, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.2600301660425801, 'n_estimators': 236, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.44828046137677974, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.723434155611114, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:34:32,760] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.8508184042922002, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 1.5950934322255128, 'min_weight_fraction_leaf': 0.3672741344156673, 'max_features': 0.1, 'min_impurity_decrease': 9.999645993471922e-07, 'validation_fraction': 0.894831925816593, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:34:46,114] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.007318845785810312, 'dropout_rate': 0.9694253886674298, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.0041987442036233, 'min_weight_fraction_leaf': 0.41002460147990016, 'max_features': 'log2', 'min_impurity_decrease': 2.595046469962732e-06, 'validation_fraction': 0.8313632450390351, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:35:35,325] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7881603947064, 'learning_rate': 0.024308371272538112, 'dropout_rate': 0.11931202058020746, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.46145706703279166, 'min_weight_fraction_leaf': 0.14638041253524992, 'max_features': 'sqrt', 'min_impurity_decrease': 3.124298610650395e-07, 'validation_fraction': 0.885979815139411, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:35:51,575] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9116990829700251, 'learning_rate': 0.0012697805220829685, 'dropout_rate': 0.2528872202970577, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.33510432917217986, 'max_features': None, 'min_impurity_decrease': 1.0186154127552982e-07, 'validation_fraction': 0.9531390028399015, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 4}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:36:27,648] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.9503333802028551, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 420, 'criterion': 'friedman_mse', 'ccp_alpha': 6.6082653368298185, 'min_weight_fraction_leaf': 0.22522458248307622, 'max_features': 'auto', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6535676180999174, 'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:36:30,199] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.02150329631555176, 'dropout_rate': 0.3666232473259417, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 1.3133337630740611, 'min_weight_fraction_leaf': 0.47565429586146185, 'max_features': 'auto', 'min_impurity_decrease': 1.8633023596687113e-06, 'validation_fraction': 0.8119058063801081, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 20:36:30,579] Trial 51 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9947653262192967, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.1592738913883298, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'auto', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:36:30,977] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9838263913881168, 'learning_rate': 0.007162813008405933, 'dropout_rate': 0.17395958025907304, 'n_estimators': 17, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.37395658840830287, 'max_features': 'auto', 'min_impurity_decrease': 1.9340874733278664e-07, 'validation_fraction': 0.9673436129299916, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 20:36:38,533] Trial 53 finished with value: 0.7066921324762583 and parameters: {'subsample': 0.8832560354405471, 'learning_rate': 0.013515333982145643, 'dropout_rate': 0.1066966218862955, 'n_estimators': 115, 'criterion': 'squared_error', 'ccp_alpha': 0.00962522783777093, 'min_weight_fraction_leaf': 0.3102859232383388, 'max_features': 'auto', 'min_impurity_decrease': 5.129651522544754e-07, 'validation_fraction': 0.9977392300861776, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:36:44,876] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8839401595086688, 'learning_rate': 0.013720158661514745, 'dropout_rate': 0.11547001021095907, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.9585348267499517, 'min_weight_fraction_leaf': 0.31281161202556473, 'max_features': 'auto', 'min_impurity_decrease': 5.50189997369896e-07, 'validation_fraction': 0.9994238437001496, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:36:46,653] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8309421840852462, 'learning_rate': 0.011311223505622352, 'dropout_rate': 0.20419816136861105, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 0.3986990587399982, 'min_weight_fraction_leaf': 0.2039350020074899, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8756039908972886, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:38:25,750] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.72294472419416, 'learning_rate': 0.030529655796453406, 'dropout_rate': 0.1042670173421051, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.0260576154507228, 'min_weight_fraction_leaf': 0.26869875361297285, 'max_features': 1, 'min_impurity_decrease': 1.0882152569265186e-06, 'validation_fraction': 0.9043438819355977, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:38:32,139] Trial 57 finished with value: 0.5 and parameters: {'subsample': 0.781561535505851, 'learning_rate': 0.019599111388603693, 'dropout_rate': 0.28746581622574, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.6775249385492055, 'min_weight_fraction_leaf': 0.4147367845229429, 'max_features': 'auto', 'min_impurity_decrease': 5.608534822955176e-07, 'validation_fraction': 0.5838562151808616, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:38:42,678] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.4443705051573945, 'learning_rate': 0.04030629833839253, 'dropout_rate': 0.24216293738207553, 'n_estimators': 164, 'criterion': 'squared_error', 'ccp_alpha': 0.7497240498249881, 'min_weight_fraction_leaf': 0.33754637584813874, 'max_features': 0.1, 'min_impurity_decrease': 3.445912059389303e-07, 'validation_fraction': 0.7729698485030033, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:40:02,235] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9301898151121387, 'learning_rate': 0.014811565508437466, 'dropout_rate': 0.1837704285299646, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.302647558909275, 'max_features': 'log2', 'min_impurity_decrease': 4.132096543200702e-07, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:40:33,662] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.2779429418662181, 'learning_rate': 0.005013007250233982, 'dropout_rate': 0.14183557134552166, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 1.322729891908786, 'min_weight_fraction_leaf': 0.2834981878637842, 'max_features': 'auto', 'min_impurity_decrease': 1.9418303906939395e-06, 'validation_fraction': 0.8435510786021796, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:40:36,493] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.009978939472425662, 'dropout_rate': 0.2238557425834033, 'n_estimators': 70, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.4432436454062534, 'max_features': 'auto', 'min_impurity_decrease': 1.92080140518381e-07, 'validation_fraction': 0.9540853929856796, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 20:40:48,382] Trial 62 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9949849995633986, 'learning_rate': 0.00590733686751327, 'dropout_rate': 0.15426665038628304, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.022717462020606087, 'min_weight_fraction_leaf': 0.3771525913161122, 'max_features': 'auto', 'min_impurity_decrease': 1.6541961435697376e-07, 'validation_fraction': 0.998924391459097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 20:40:50,196] Trial 63 finished with value: 0.715358098862813 and parameters: {'subsample': 0.8686583129899306, 'learning_rate': 0.001290161829137394, 'dropout_rate': 0.1898785022640528, 'n_estimators': 58, 'criterion': 'squared_error', 'ccp_alpha': 0.018078806214999348, 'min_weight_fraction_leaf': 0.3861329521141052, 'max_features': 'auto', 'min_impurity_decrease': 8.327527140717665e-07, 'validation_fraction': 0.932887892507485, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:40:53,522] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.8645070165323501, 'learning_rate': 0.09405807235270042, 'dropout_rate': 0.18802779859574847, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.35251200695718055, 'max_features': 'auto', 'min_impurity_decrease': 9.420976138154327e-07, 'validation_fraction': 0.9231276840562984, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:40:59,094] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.903563418868777, 'learning_rate': 0.0016217786521075337, 'dropout_rate': 0.27304642297183634, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.35075027656676333, 'min_weight_fraction_leaf': 0.46836556984836597, 'max_features': 'auto', 'min_impurity_decrease': 0.00018567504305581884, 'validation_fraction': 0.8837902558696593, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:42:41,419] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8164719060956207, 'learning_rate': 0.012803396580721372, 'dropout_rate': 0.13161439171907266, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.8927340743616367, 'min_weight_fraction_leaf': 0.24360172036034505, 'max_features': 'sqrt', 'min_impurity_decrease': 5.724092120969544e-07, 'validation_fraction': 0.9783741103646215, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:42:42,650] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8652614464897083, 'learning_rate': 0.017792589526001042, 'dropout_rate': 0.4308859881762669, 'n_estimators': 45, 'criterion': 'friedman_mse', 'ccp_alpha': 2.352310671798754, 'min_weight_fraction_leaf': 0.4527437444308926, 'max_features': 'auto', 'min_impurity_decrease': 3.132340488371029e-07, 'validation_fraction': 0.6922946122950581, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:43:05,253] Trial 68 finished with value: 0.6289549910873441 and parameters: {'subsample': 0.1828808967076968, 'learning_rate': 0.009763210879301733, 'dropout_rate': 0.227818798660288, 'n_estimators': 235, 'criterion': 'squared_error', 'ccp_alpha': 0.29598676708348526, 'min_weight_fraction_leaf': 0.4165856705288462, 'max_features': 'auto', 'min_impurity_decrease': 1.2512174866550223e-06, 'validation_fraction': 0.4611449164937295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:43:06,745] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7498611166680669, 'learning_rate': 0.04820609879441119, 'dropout_rate': 0.32090257654334975, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.7413034944146035, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': None, 'min_impurity_decrease': 2.3700234556978203e-06, 'validation_fraction': 0.8668588900403627, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:44:22,538] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.911088145674265, 'learning_rate': 0.0228629548900178, 'dropout_rate': 0.1866548676915602, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.2482267223936536, 'min_weight_fraction_leaf': 0.22078244504185224, 'max_features': 'auto', 'min_impurity_decrease': 4.8419433611640654e-06, 'validation_fraction': 0.9040102661274384, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 20:44:22,931] Trial 71 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9622573373756947, 'learning_rate': 0.005576631516276089, 'dropout_rate': 0.8462757993963043, 'n_estimators': 10, 'criterion': 'squared_error', 'ccp_alpha': 0.027818996011453684, 'min_weight_fraction_leaf': 0.38504148100809776, 'max_features': 'auto', 'min_impurity_decrease': 1.41859363723174e-07, 'validation_fraction': 0.9482945382047324, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 20:44:23,429] Trial 72 finished with value: 0.685844917453683 and parameters: {'subsample': 0.950430822794731, 'learning_rate': 0.0053064296987160465, 'dropout_rate': 0.7234474037831898, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.00479380572002332, 'min_weight_fraction_leaf': 0.3972455103663686, 'max_features': 'auto', 'min_impurity_decrease': 1.366202506746777e-07, 'validation_fraction': 0.9693127617967663, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:44:38,813] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.885575181084042, 'learning_rate': 0.003536949776399335, 'dropout_rate': 0.9088405719505623, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.35670027635353807, 'min_weight_fraction_leaf': 0.35822108217683835, 'max_features': 'auto', 'min_impurity_decrease': 4.2499433142234475e-07, 'validation_fraction': 0.20224553600156958, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:44:39,385] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.5836393594321302, 'learning_rate': 0.009340590354270865, 'dropout_rate': 0.8412829433501265, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 0.6246646628477466, 'min_weight_fraction_leaf': 0.42429330054001607, 'max_features': 'auto', 'min_impurity_decrease': 2.8316890658493217e-07, 'validation_fraction': 0.9340639943674915, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:44:44,410] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.5200735929114648, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.128072187563372, 'n_estimators': 99, 'criterion': 'squared_error', 'ccp_alpha': 0.9318541971101635, 'min_weight_fraction_leaf': 0.329634418869288, 'max_features': 'auto', 'min_impurity_decrease': 7.061217543698309e-07, 'validation_fraction': 0.7955814541363518, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:45:24,664] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9312152381840203, 'learning_rate': 0.011963342113513162, 'dropout_rate': 0.640126219035525, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.3025319765337648, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 1.4007647974844957e-07, 'validation_fraction': 0.7443065618057785, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:45:26,551] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.9689893891792536, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.5468452572744673, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.5979952840890602, 'min_weight_fraction_leaf': 0.25434486774085874, 'max_features': 1, 'min_impurity_decrease': 2.595814783640358e-07, 'validation_fraction': 0.9726620416567261, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:46:57,008] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.8595097382714689, 'learning_rate': 0.0034833775412467377, 'dropout_rate': 0.10127265486770577, 'n_estimators': 473, 'criterion': 'friedman_mse', 'ccp_alpha': 1.4812955313687048, 'min_weight_fraction_leaf': 0.3131777562301877, 'max_features': 'auto', 'min_impurity_decrease': 1.0290395334568972e-07, 'validation_fraction': 0.8280705957992395, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:47:09,505] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.8015344520335466, 'learning_rate': 0.0012723432779221475, 'dropout_rate': 0.8831816560103296, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 1.8162144553916222, 'min_weight_fraction_leaf': 0.34854584327537885, 'max_features': 'log2', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9186131425355593, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:47:38,194] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.8367376204446394, 'learning_rate': 0.007364213642980483, 'dropout_rate': 0.702176827465796, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.3004980772276427, 'max_features': 'auto', 'min_impurity_decrease': 7.124034486377485e-07, 'validation_fraction': 0.9461272730178157, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 20:47:38,484] Trial 81 finished with value: 0.6684464087544287 and parameters: {'subsample': 0.9965174069194047, 'learning_rate': 0.007618988907310126, 'dropout_rate': 0.16198782693693461, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.025916849299345394, 'min_weight_fraction_leaf': 0.38961846335957595, 'max_features': 'auto', 'min_impurity_decrease': 1.766837964281054e-07, 'validation_fraction': 0.9399776044267211, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 20:47:38,865] Trial 82 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9646485447558332, 'learning_rate': 0.006224947240679894, 'dropout_rate': 0.16886094857249775, 'n_estimators': 12, 'criterion': 'squared_error', 'ccp_alpha': 0.017707201149411784, 'min_weight_fraction_leaf': 0.38368758581534546, 'max_features': 'auto', 'min_impurity_decrease': 2.2084017063206466e-07, 'validation_fraction': 0.38434645874984097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:47:39,805] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9674120427099258, 'learning_rate': 0.012634880227471968, 'dropout_rate': 0.24105562803816832, 'n_estimators': 36, 'criterion': 'squared_error', 'ccp_alpha': 0.49986991060004404, 'min_weight_fraction_leaf': 0.4028329566858333, 'max_features': 'auto', 'min_impurity_decrease': 3.7732222209322964e-07, 'validation_fraction': 0.29115286333596435, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:49:12,301] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.9187525025568754, 'learning_rate': 0.004160535799768975, 'dropout_rate': 0.2015650563323303, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.3706545282616189, 'max_features': 'auto', 'min_impurity_decrease': 1.4899460740955453e-06, 'validation_fraction': 0.39196940849585504, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:49:12,832] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.8968529080615669, 'learning_rate': 0.017670564382826763, 'dropout_rate': 0.2745425858009699, 'n_estimators': 16, 'criterion': 'squared_error', 'ccp_alpha': 1.0637247669291705, 'min_weight_fraction_leaf': 0.3822449692929958, 'max_features': 'auto', 'min_impurity_decrease': 2.3419797764275672e-07, 'validation_fraction': 0.5434611145938996, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:49:16,547] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.9428961007941905, 'learning_rate': 0.011402694667743098, 'dropout_rate': 0.134159592794598, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.23936333725455253, 'min_weight_fraction_leaf': 0.27268436275419344, 'max_features': 'sqrt', 'min_impurity_decrease': 4.779762823701413e-07, 'validation_fraction': 0.3558315208173153, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:49:19,003] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.9642091284813806, 'learning_rate': 0.009067059593875184, 'dropout_rate': 0.8053771471721777, 'n_estimators': 81, 'criterion': 'squared_error', 'ccp_alpha': 0.2360450448272922, 'min_weight_fraction_leaf': 0.36130355929034824, 'max_features': 'auto', 'min_impurity_decrease': 1.6608380458349677e-05, 'validation_fraction': 0.48901442871881995, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:49:21,399] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9166952579476793, 'learning_rate': 0.027428474441345257, 'dropout_rate': 0.9942411221597407, 'n_estimators': 142, 'criterion': 'squared_error', 'ccp_alpha': 0.736661694905559, 'min_weight_fraction_leaf': 0.3421577371226225, 'max_features': 'auto', 'min_impurity_decrease': 1.3101245725982968e-07, 'validation_fraction': 0.9819335319333689, 'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:50:36,281] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.38730242337646104, 'learning_rate': 0.020510559401054396, 'dropout_rate': 0.1637660735943165, 'n_estimators': 425, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5135760709608489, 'min_weight_fraction_leaf': 0.2338348901049672, 'max_features': None, 'min_impurity_decrease': 8.646658253890459e-07, 'validation_fraction': 0.2693385873685563, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:50:44,185] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.3351416528138606, 'learning_rate': 0.001130725657308556, 'dropout_rate': 0.21238181902547987, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 1.098484581242824, 'min_weight_fraction_leaf': 0.45624128176873047, 'max_features': 'auto', 'min_impurity_decrease': 2.8288075937135275e-07, 'validation_fraction': 0.8654647894710668, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 20:50:44,926] Trial 91 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.973859764718155, 'learning_rate': 0.006991850627181431, 'dropout_rate': 0.17031167363762192, 'n_estimators': 24, 'criterion': 'squared_error', 'ccp_alpha': 0.03873428305932247, 'min_weight_fraction_leaf': 0.38456389013049225, 'max_features': 'auto', 'min_impurity_decrease': 2.1057313400290866e-07, 'validation_fraction': 0.9606810926219381, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:50:45,718] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.8803056919201186, 'learning_rate': 0.005845639334984173, 'dropout_rate': 0.17652933801835793, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.20706720697578515, 'min_weight_fraction_leaf': 0.43161442258073124, 'max_features': 'auto', 'min_impurity_decrease': 2.0676851144372516e-07, 'validation_fraction': 0.9025757365890354, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:50:46,421] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.9733203192391623, 'learning_rate': 0.014432394643112474, 'dropout_rate': 0.2300740953304724, 'n_estimators': 4, 'criterion': 'squared_error', 'ccp_alpha': 0.46903049977228617, 'min_weight_fraction_leaf': 0.404652010953728, 'max_features': 'auto', 'min_impurity_decrease': 5.086967260434284e-07, 'validation_fraction': 0.9736018036138772, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:50:47,413] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.9359287316154687, 'learning_rate': 0.003576820689332409, 'dropout_rate': 0.14182769534201045, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 0.850632602885982, 'min_weight_fraction_leaf': 0.41989514755999646, 'max_features': 'auto', 'min_impurity_decrease': 3.640599784132377e-07, 'validation_fraction': 0.9231910021785822, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5558035714285714
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 20:50:49,032] Trial 95 finished with value: 0.5701693113224804 and parameters: {'subsample': 0.8441489229564334, 'learning_rate': 0.010686672701851392, 'dropout_rate': 0.12427113599249004, 'n_estimators': 52, 'criterion': 'squared_error', 'ccp_alpha': 0.13095957774357525, 'min_weight_fraction_leaf': 0.208662917753807, 'max_features': 'auto', 'min_impurity_decrease': 0.04760435998517946, 'validation_fraction': 0.9999851977461973, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7251347360205367.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6220657276995305
[I 2024-04-14 20:50:52,709] Trial 96 finished with value: 0.7413160056482762 and parameters: {'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 96 with value: 0.7413160056482762.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:50:56,458] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8890132762537363, 'learning_rate': 0.016000147782265963, 'dropout_rate': 0.33412474584068513, 'n_estimators': 102, 'criterion': 'squared_error', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.3259150375155791, 'max_features': 1, 'min_impurity_decrease': 1.4118150039086305e-07, 'validation_fraction': 0.6283958723553874, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 96 with value: 0.7413160056482762.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:50:59,772] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8159517170308073, 'learning_rate': 0.008130653433584725, 'dropout_rate': 0.29126647641167647, 'n_estimators': 92, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.48045734256987266, 'max_features': 1, 'min_impurity_decrease': 1.030784288757872e-07, 'validation_fraction': 0.4049740702980035, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 18}. Best is trial 96 with value: 0.7413160056482762.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.5
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481

[I 2024-04-14 20:51:00,274] A new study created in memory with name: no-name-da61d498-41c7-47b9-8497-e01751a864f4

Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 20:51:00,241] Trial 99 finished with value: 0.6765410203044572 and parameters: {'subsample': 0.9036420036324795, 'learning_rate': 0.013060448266216875, 'dropout_rate': 0.37151966270502923, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.004512555601867606, 'min_weight_fraction_leaf': 0.43840629474088344, 'max_features': 1, 'min_impurity_decrease': 2.1305992007975229e-07, 'validation_fraction': 0.8858148503753556, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 16}. Best is trial 96 with value: 0.7413160056482762.


* Best trial for C-index:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.7413160056482762], datetime_start=datetime.datetime(2024, 4, 14, 20, 50, 49, 37680), datetime_complete=datetime.datetime(2024, 4, 14, 20, 50, 52, 708649), params={'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=96, value=None)


* Best Score for C-index:
 0.7413160056482762

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 20:51:29,294] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 20:51:42,986] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 20:51:57,144] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 20:52:21,235] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 20:52:28,760] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 20:52:31,129] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 20:52:54,048] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 20:53:00,030] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 20:53:00,784] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21300832282956317
Fold 2 IBS: 0.2213261650256521
Fold 3 IBS: 0.2035838809535175
Fold 4 IBS: 0.22376838886860287
Fold 5 IBS: 0.21793551354488228
[I 2024-04-14 20:53:58,285] Trial 9 finished with value: 0.21592445424444356 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21592445424444356.
Fold 1 IBS: 0.21360017884301727
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.2041609124821885
Fold 4 IBS: 0.22443190447044095
Fold 5 IBS: 0.21803455300047256
[I 2024-04-14 20:55:24,448] Trial 10 finished with value: 0.2163415912252844 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21592445424444356.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 20:57:00,195] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21592445424444356.
Fold 1 IBS: 0.2138392374140203
Fold 2 IBS: 0.22156449267228215
Fold 3 IBS: 0.20440421917640686
Fold 4 IBS: 0.22459155969877373
Fold 5 IBS: 0.2180987264506579
[I 2024-04-14 20:58:27,415] Trial 12 finished with value: 0.21649964708242822 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21592445424444356.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-14 20:59:10,605] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21592445424444356.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 21:00:33,239] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21592445424444356.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 21:01:50,899] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21592445424444356.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 21:02:24,164] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21592445424444356.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:03:46,238] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21592445424444356.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:04:33,761] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21592445424444356.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:04:40,156] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21592445424444356.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:06:00,817] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21592445424444356.
Fold 1 IBS: 0.21394946003688667
Fold 2 IBS: 0.22157225472001127
Fold 3 IBS: 0.20452938396094716
Fold 4 IBS: 0.2247371055371081
Fold 5 IBS: 0.21809210037899657
[I 2024-04-14 21:07:19,990] Trial 21 finished with value: 0.21657606092679 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21592445424444356.
Fold 1 IBS: 0.21273266882835087
Fold 2 IBS: 0.2214154340077775

Fold 3 IBS: 0.2033329236940595
Fold 4 IBS: 0.22311599409323163
Fold 5 IBS: 0.21791022310639455
[I 2024-04-14 21:08:45,610] Trial 22 finished with value: 0.2157014487459628 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 21:09:59,922] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:10:45,135] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:11:27,801] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:12:34,799] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 21:12:41,476] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 21:13:06,030] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 21:14:07,072] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 21:14:34,138] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.2136950219225832
Fold 2 IBS: 0.2215362190250608
Fold 3 IBS: 0.2044185685149852
Fold 4 IBS: 0.22472904052923362
Fold 5 IBS: 0.21803316635813036
[I 2024-04-14 21:15:43,972] Trial 31 finished with value: 0.21648240326999862 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.2130097385063184
Fold 2 IBS: 0.22144791559015894
Fold 3 IBS: 0.20359640314421312
Fold 4 IBS: 0.2235395355788286
Fold 5 IBS: 0.21789545644168284
[I 2024-04-14 21:16:54,987] Trial 32 finished with value: 0.21589780985224039 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:17:53,803] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 21:18:55,434] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 21:19:10,394] Trial 35 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 21:20:22,631] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 21:20:24,956] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 21:21:01,672] Trial 38 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 21:21:50,724] Trial 39 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 21:22:40,576] Trial 40 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21336832511750178
Fold 2 IBS: 0.22149081759520453
Fold 3 IBS: 0.20392451903804681
Fold 4 IBS: 0.22395780771096238
Fold 5 IBS: 0.21799037217752354
[I 2024-04-14 21:23:57,694] Trial 41 finished with value: 0.2161463683278478 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21306489361720754
Fold 2 IBS: 0.22145919146004972
Fold 3 IBS: 0.2036498304361267
Fold 4 IBS: 0.2236086309233099
Fold 5 IBS: 0.21790465020510716
[I 2024-04-14 21:25:14,359] Trial 42 finished with value: 0.21593743932836024 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 21:26:33,608] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 21:27:31,222] Trial 44 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21364745831179702
Fold 2 IBS: 0.22144755001547356
Fold 3 IBS: 0.20423263258612678
Fold 4 IBS: 0.2243145355361801
Fold 5 IBS: 0.21807902714883393
[I 2024-04-14 21:28:23,182] Trial 45 finished with value: 0.21634424071968228 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 21:29:17,204] Trial 46 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 21:29:38,384] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 21:29:38,724] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 21:29:50,797] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 21:30:52,846] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21307969652873227
Fold 2 IBS: 0.22136886746037693
Fold 3 IBS: 0.203621499145842
Fold 4 IBS: 0.22363894843965748
Fold 5 IBS: 0.2179296735036949
[I 2024-04-14 21:32:21,665] Trial 51 finished with value: 0.2159277370156607 and parameters: {'subsample': 0.9914941239177857, 'learning_rate': 0.004643220694148276, 'dropout_rate': 0.14631717824203036, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3402340557764622, 'max_features': 'auto', 'min_impurity_decrease': 1.0669017189349294e-07, 'validation_fraction': 0.9630345477132441, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:33:28,622] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9520094582202872, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.13770242385086745, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.3347369286285409, 'max_features': 'auto', 'min_impurity_decrease': 1.8037977074379283e-07, 'validation_fraction': 0.9590095104838449, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 22 with value: 0.2157014487459628.
Fold 1 IBS: 0.21174315691146667
Fold 2 IBS: 0.22137600200037952
Fold 3 IBS: 0.20240438380881318
Fold 4 IBS: 0.22194891399880726
Fold 5 IBS: 0.21777686189712414
[I 2024-04-14 21:34:28,561] Trial 53 finished with value: 0.21504986372331816 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.1897783294507234, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.29880213170319914, 'max_features': 'auto', 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9964423942006735, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:35:27,920] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9951759842961662, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18641432881009587, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.29477236360216774, 'max_features': 'auto', 'min_impurity_decrease': 5.718312774105514e-07, 'validation_fraction': 0.9994814833877664, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:36:18,698] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9027683411994925, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.13472529918097312, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.36938177041618503, 'max_features': 'auto', 'min_impurity_decrease': 1.1016843774656315e-07, 'validation_fraction': 0.898549324711475, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 21:37:07,219] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8324789538052517, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.2217299975485909, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.33106978438275647, 'max_features': 'auto', 'min_impurity_decrease': 2.9232848365940597e-07, 'validation_fraction': 0.848519914422397, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:38:22,151] Trial 57 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8682011777139672, 'learning_rate': 0.031239466455985663, 'dropout_rate': 0.17322401428734607, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.2621422129699527, 'max_features': 'auto', 'min_impurity_decrease': 1.0096192890009967e-07, 'validation_fraction': 0.7861749990571634, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:39:39,344] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.10699123414946089, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 0.4695790047970817, 'min_weight_fraction_leaf': 0.4208497987584031, 'max_features': 1, 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.9248722131485942, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:40:29,110] Trial 59 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.0011610373238817896, 'dropout_rate': 0.2835746645760172, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.2971262516319784, 'max_features': 0.1, 'min_impurity_decrease': 5.673772193709774e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 21:41:08,939] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7689457925126264, 'learning_rate': 0.01938137369688937, 'dropout_rate': 0.23766423890937624, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2523293803401735, 'min_weight_fraction_leaf': 0.31705920833651274, 'max_features': 'auto', 'min_impurity_decrease': 1.09574587374673e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 21:42:10,012] Trial 61 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.005150255907863737, 'dropout_rate': 0.2646601381824477, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.24335809438237638, 'max_features': 'auto', 'min_impurity_decrease': 1.670100349442241e-07, 'validation_fraction': 0.9537438642784446, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21260039171576678
Fold 2 IBS: 0.22127522100059224
Fold 3 IBS: 0.2031294211565798
Fold 4 IBS: 0.22304748515979766
Fold 5 IBS: 0.21785716148870096
[I 2024-04-14 21:43:24,431] Trial 62 finished with value: 0.2155819361042875 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.009577802680942944, 'dropout_rate': 0.19576464123878148, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.2712475429741565, 'max_features': 'auto', 'min_impurity_decrease': 2.6031567647465433e-06, 'validation_fraction': 0.9664234509760701, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 21:44:40,811] Trial 63 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9678670791375591, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.19439757224953633, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.2664239609493312, 'max_features': 'auto', 'min_impurity_decrease': 4.0390121021586725e-07, 'validation_fraction': 0.8804884805212966, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.2129098178904263
Fold 2 IBS: 0.22124298510703908
Fold 3 IBS: 0.20345731597513111
Fold 4 IBS: 0.22352496018475762
Fold 5 IBS: 0.21795154431301125
[I 2024-04-14 21:46:07,778] Trial 64 finished with value: 0.21581732469407305 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.008241701765086935, 'dropout_rate': 0.16204590972071856, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.042747030615862165, 'min_weight_fraction_leaf': 0.20867683262863126, 'max_features': 'log2', 'min_impurity_decrease': 1.1622062475943789e-06, 'validation_fraction': 0.9709487288557038, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 21:47:31,365] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9189183326723824, 'learning_rate': 0.011096659410828054, 'dropout_rate': 0.15744491147958184, 'n_estimators': 493, 'criterion': 'squared_error', 'ccp_alpha': 1.1124245211667088, 'min_weight_fraction_leaf': 0.21730511044745757, 'max_features': 'log2', 'min_impurity_decrease': 4.00127934674698e-06, 'validation_fraction': 0.998233299727277, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 21:48:52,676] Trial 66 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9998769156045215, 'learning_rate': 0.008782667792366316, 'dropout_rate': 0.12972298735589705, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.7134499429690735, 'min_weight_fraction_leaf': 0.19311178079767077, 'max_features': 'log2', 'min_impurity_decrease': 1.142816958470248e-06, 'validation_fraction': 0.9729459657934212, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 21:49:49,028] Trial 67 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8640185330574577, 'learning_rate': 0.015997347081349804, 'dropout_rate': 0.18369926136498038, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.3491418081323188, 'max_features': 'log2', 'min_impurity_decrease': 2.9677822215329938e-06, 'validation_fraction': 0.9116952163053982, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 21:50:44,525] Trial 68 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8052124560044422, 'learning_rate': 0.027698938792055094, 'dropout_rate': 0.3183724976622295, 'n_estimators': 459, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2920470355270516, 'min_weight_fraction_leaf': 0.16901934601360036, 'max_features': 'log2', 'min_impurity_decrease': 7.18785237781598e-07, 'validation_fraction': 0.6390547838628696, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 21:51:38,097] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.022661198063658503, 'dropout_rate': 0.15177883474257473, 'n_estimators': 422, 'criterion': 'squared_error', 'ccp_alpha': 5.781491720141274, 'min_weight_fraction_leaf': 0.3709922257167516, 'max_features': 'sqrt', 'min_impurity_decrease': 7.4830347845666965e-06, 'validation_fraction': 0.8281891917990171, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:51:51,590] Trial 70 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.0031189928817958587, 'dropout_rate': 0.5905404972480945, 'n_estimators': 296, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.3188535514715946, 'max_features': 'log2', 'min_impurity_decrease': 1.1928111158414438e-06, 'validation_fraction': 0.8771634368243094, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21281861880669364
Fold 2 IBS: 0.22147036875244297
Fold 3 IBS: 0.2034171767501767
Fold 4 IBS: 0.2233060629612114
Fold 5 IBS: 0.21789594373420879
[I 2024-04-14 21:53:11,104] Trial 71 finished with value: 0.2157816342009467 and parameters: {'subsample': 0.9303280421214478, 'learning_rate': 0.00867928513859834, 'dropout_rate': 0.2114071609099808, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.2830289864785245, 'max_features': 'auto', 'min_impurity_decrease': 2.8309589446706505e-07, 'validation_fraction': 0.9341930519363522, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21264377959603953
Fold 2 IBS: 0.221456908694238
Fold 3 IBS: 0.20325172949881257
Fold 4 IBS: 0.2230893111299857
Fold 5 IBS: 0.21786749174522294
[I 2024-04-14 21:54:38,647] Trial 72 finished with value: 0.21566184413285977 and parameters: {'subsample': 0.9301573375470014, 'learning_rate': 0.011204053201905661, 'dropout_rate': 0.23553989617782028, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.004820830813732985, 'min_weight_fraction_leaf': 0.2737805456341038, 'max_features': 'auto', 'min_impurity_decrease': 3.6620964530112787e-07, 'validation_fraction': 0.9737030143041076, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 21:54:46,735] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9298981705927085, 'learning_rate': 0.010195438618282406, 'dropout_rate': 0.23585972620145051, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.27451237461517963, 'max_features': 'auto', 'min_impurity_decrease': 4.330904032345818e-07, 'validation_fraction': 0.9203017882586108, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:55:55,953] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8776896116214433, 'learning_rate': 0.014494378748744683, 'dropout_rate': 0.28898081809802034, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.37345543486587357, 'min_weight_fraction_leaf': 0.20816976567601184, 'max_features': 'auto', 'min_impurity_decrease': 2.611979113511538e-07, 'validation_fraction': 0.9762608022070116, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 21:57:14,365] Trial 75 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8972316596616344, 'learning_rate': 0.019330707767774714, 'dropout_rate': 0.34962098273262876, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 1.2014771498456696, 'min_weight_fraction_leaf': 0.2901314285672209, 'max_features': 'auto', 'min_impurity_decrease': 5.9734079360074814e-05, 'validation_fraction': 0.8483032778113153, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 21:58:52,387] Trial 76 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9427845846760775, 'learning_rate': 0.040991201384238105, 'dropout_rate': 0.2075245331259492, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': None, 'min_impurity_decrease': 1.507827148373076e-06, 'validation_fraction': 0.934389124127465, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613

Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 21:59:52,179] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6527746876723795, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.2556920821676466, 'n_estimators': 442, 'criterion': 'squared_error', 'ccp_alpha': 0.5896250392603071, 'min_weight_fraction_leaf': 0.22988050749684658, 'max_features': 1, 'min_impurity_decrease': 1.4995945809430595e-05, 'validation_fraction': 0.8950354974332698, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 22:01:07,205] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7443996478445325, 'learning_rate': 0.0869328686638194, 'dropout_rate': 0.1812306278517568, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.2911423302160594, 'min_weight_fraction_leaf': 0.2568526167512072, 'max_features': 'auto', 'min_impurity_decrease': 6.881976645342321e-07, 'validation_fraction': 0.4642012910381656, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 22:02:00,731] Trial 79 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9711804489125221, 'learning_rate': 0.008977463652006058, 'dropout_rate': 0.10045868399742758, 'n_estimators': 408, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8456191926639984, 'min_weight_fraction_leaf': 0.28189763106059557, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9982937136983077, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 22:02:53,679] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8535702305805324, 'learning_rate': 0.013008132772511784, 'dropout_rate': 0.23306750004092583, 'n_estimators': 442, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.3004980772276427, 'max_features': 'auto', 'min_impurity_decrease': 5.501302028342128e-06, 'validation_fraction': 0.8033655207154786, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21328441825357652
Fold 2 IBS: 0.22144767701711832
Fold 3 IBS: 0.2038537340831823
Fold 4 IBS: 0.22389243027837222
Fold 5 IBS: 0.2179733655894191
[I 2024-04-14 22:03:55,205] Trial 81 finished with value: 0.2160903250443337 and parameters: {'subsample': 0.9784145478438975, 'learning_rate': 0.00415560855116564, 'dropout_rate': 0.16880106444935875, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.025432112194026565, 'min_weight_fraction_leaf': 0.32661813483692875, 'max_features': 'auto', 'min_impurity_decrease': 4.1696350773463576e-07, 'validation_fraction': 0.9618626661496192, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21313529710939624
Fold 2 IBS: 0.2214959526155037
Fold 3 IBS: 0.2037228525189486
Fold 4 IBS: 0.2236990075239477
Fold 5 IBS: 0.2179583294148407
[I 2024-04-14 22:05:20,380] Trial 82 finished with value: 0.2160022878365274 and parameters: {'subsample': 0.9292256563323309, 'learning_rate': 0.005938788819943272, 'dropout_rate': 0.20112867357024375, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.01786403260693046, 'min_weight_fraction_leaf': 0.2694686872154886, 'max_features': 'auto', 'min_impurity_decrease': 1.4936787149467238e-07, 'validation_fraction': 0.9322976146952479, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 22:06:40,799] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.997030710636302, 'learning_rate': 0.017347504146358047, 'dropout_rate': 0.12875284011164154, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.42770746896829764, 'min_weight_fraction_leaf': 0.30582130984370137, 'max_features': 'auto', 'min_impurity_decrease': 3.0720666780466816e-07, 'validation_fraction': 0.9763733963887893, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 22:07:35,451] Trial 84 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9699238743776749, 'learning_rate': 0.009959638401621597, 'dropout_rate': 0.305574256636177, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.262145494050454, 'min_weight_fraction_leaf': 0.23583033266274414, 'max_features': 'auto', 'min_impurity_decrease': 7.781008937605048e-07, 'validation_fraction': 0.8657748182811282, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 22:08:42,724] Trial 85 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9039638029331271, 'learning_rate': 0.0037679534600800306, 'dropout_rate': 0.15830961459250859, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 0.9670160633661875, 'min_weight_fraction_leaf': 0.22273143316885707, 'max_features': 'auto', 'min_impurity_decrease': 1.549053164841614e-07, 'validation_fraction': 0.9112741324892579, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 22:10:09,540] Trial 86 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9330830727147826, 'learning_rate': 0.00786307119428408, 'dropout_rate': 0.2679588154714714, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.6251717679448328, 'min_weight_fraction_leaf': 0.34273533762708086, 'max_features': 'auto', 'min_impurity_decrease': 1.94114481416941e-06, 'validation_fraction': 0.9710286882527703, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 22:10:24,418] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8202668472614781, 'learning_rate': 0.012273440310927393, 'dropout_rate': 0.49308788025511585, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.2337543925553926, 'min_weight_fraction_leaf': 0.2565004395308679, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00023480828622143336, 'validation_fraction': 0.37837273453407844, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616

Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 22:11:06,904] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8800231052433968, 'learning_rate': 0.015424283294721588, 'dropout_rate': 0.20093805843087115, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 1.351539840282731, 'min_weight_fraction_leaf': 0.28958635214901884, 'max_features': 'auto', 'min_impurity_decrease': 2.329078771156988e-07, 'validation_fraction': 0.939344740485312, 'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 22:11:59,117] Trial 89 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9819209167757807, 'learning_rate': 0.020219241696711625, 'dropout_rate': 0.2428130031440519, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.5765552790097783, 'min_weight_fraction_leaf': 0.18311512377308206, 'max_features': 'auto', 'min_impurity_decrease': 5.126619309081385e-07, 'validation_fraction': 0.8909484827188601, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 22:12:14,746] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6196341847942087, 'learning_rate': 0.006689654877596743, 'dropout_rate': 0.8458602043820649, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.5932807780543458, 'min_weight_fraction_leaf': 0.20408203732171998, 'max_features': None, 'min_impurity_decrease': 0.0012769637169882761, 'validation_fraction': 0.8340062857341481, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21354560132435954
Fold 2 IBS: 0.22152311434279084
Fold 3 IBS: 0.20412218095893767
Fold 4 IBS: 0.22420753466621227
Fold 5 IBS: 0.21802246276346793
[I 2024-04-14 22:13:20,416] Trial 91 finished with value: 0.21628417881115364 and parameters: {'subsample': 0.9519061011910324, 'learning_rate': 0.003286435592844394, 'dropout_rate': 0.21804174357954037, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.037605992845398076, 'min_weight_fraction_leaf': 0.2518132577788482, 'max_features': 'auto', 'min_impurity_decrease': 2.167221721970957e-07, 'validation_fraction': 0.9509830628877887, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 14}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21222590917260145
Fold 2 IBS: 0.2211170346259358
Fold 3 IBS: 0.2029194189164158
Fold 4 IBS: 0.22266285863270807
Fold 5 IBS: 0.21782239050085989
[I 2024-04-14 22:14:37,240] Trial 92 finished with value: 0.21534952236970423 and parameters: {'subsample': 0.5328328014893517, 'learning_rate': 0.007580646944168386, 'dropout_rate': 0.1248497169759688, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.04676515809970792, 'min_weight_fraction_leaf': 0.24126121445524454, 'max_features': 'auto', 'min_impurity_decrease': 1.41179952896197e-07, 'validation_fraction': 0.9803593350541797, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 12}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 22:15:56,326] Trial 93 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5074494668833536, 'learning_rate': 0.010358551431621075, 'dropout_rate': 0.11851429853955366, 'n_estimators': 492, 'criterion': 'squared_error', 'ccp_alpha': 0.386541225183722, 'min_weight_fraction_leaf': 0.28001284523923786, 'max_features': 'auto', 'min_impurity_decrease': 1.2653383309827397e-07, 'validation_fraction': 0.979813726530939, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 22:16:59,661] Trial 94 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.4696467705452906, 'learning_rate': 0.012513597466310221, 'dropout_rate': 0.1368992177740068, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.8568623495412244, 'min_weight_fraction_leaf': 0.3103128063965126, 'max_features': 'auto', 'min_impurity_decrease': 3.640599784132377e-07, 'validation_fraction': 0.9107078483961247, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 12}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.2139569271309933
Fold 2 IBS: 0.22156821226652648
Fold 3 IBS: 0.20452582851473292
Fold 4 IBS: 0.22472267440670798
Fold 5 IBS: 0.21811252849652027
[I 2024-04-14 22:18:40,651] Trial 95 finished with value: 0.21657723416309618 and parameters: {'subsample': 0.5795813627066926, 'learning_rate': 0.0011500826880246348, 'dropout_rate': 0.15371309107333708, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.12848433868181566, 'min_weight_fraction_leaf': 0.2390619554248597, 'max_features': 'auto', 'min_impurity_decrease': 2.9339240471384527e-07, 'validation_fraction': 0.9999690268176494, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 22:20:15,887] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5510219457804204, 'learning_rate': 0.017505885682568743, 'dropout_rate': 0.1723932907588553, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5519118282179587, 'min_weight_fraction_leaf': 0.27203175602825513, 'max_features': 'log2', 'min_impurity_decrease': 1.4367172438359607e-07, 'validation_fraction': 0.6783354896202222, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-14 22:21:14,074] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.529148797369217, 'learning_rate': 0.009070651237536868, 'dropout_rate': 0.22319654132501116, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 1.0614519036494967, 'min_weight_fraction_leaf': 0.14961516639891254, 'max_features': 'auto', 'min_impurity_decrease': 1.3572955342683883e-06, 'validation_fraction': 0.9307441942928913, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 11}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 22:22:33,080] Trial 98 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9166190498458621, 'learning_rate': 0.005876010120169104, 'dropout_rate': 0.1928526990947004, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.2351987698633502, 'min_weight_fraction_leaf': 0.24763944144203606, 'max_features': 1, 'min_impurity_decrease': 3.0003509704748335e-06, 'validation_fraction': 0.5403544212495923, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.

Fold 1 IBS: 0.21238785610218208
Fold 2 IBS: 0.22059792873287004
Fold 3 IBS: 0.203108199891751
Fold 4 IBS: 0.22281747983911723
Fold 5 IBS: 0.21781150295379875
[I 2024-04-14 22:23:31,653] Trial 99 finished with value: 0.21534459350394383 and parameters: {'subsample': 0.24286963781937687, 'learning_rate': 0.01358129947690588, 'dropout_rate': 0.25496540816023416, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.004367160733265784, 'min_weight_fraction_leaf': 0.2624099419664444, 'max_features': 'auto', 'min_impurity_decrease': 5.321953542697131e-07, 'validation_fraction': 0.9620562032012763, 'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 53 with value: 0.21504986372331816.


* Best trial for IBS:
 FrozenTrial(number=53, state=TrialState.COMPLETE, values=[0.21504986372331816], datetime_start=datetime.datetime(2024, 4, 14, 21, 33, 28, 630810), datetime_complete=datetime.datetime(2024, 4, 14, 21, 34, 28, 558478), params={'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.1897783294507234, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.29880213170319914, 'max_features': 'auto', 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9964423942006735, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=53, value=None)


* Best Score for IBS:
 0.21504986372331816

In [62]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [63]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.741
train_ibs:  0.215

#### Test

In [64]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [65]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03063070291051248,
                                 criterion='squared_error',
                                 dropout_rate=0.2576884847115747,
                                 learning_rate=0.007359366951045268,
                                 max_depth=16, max_features=1,
                                 max_leaf_nodes=16,
                                 min_impurity_decrease=1.3903906488794697e-07,
                                 min_samples_leaf=14, min_samples_split=20,
                                 min_weight_fraction_leaf=0.38180626899357545,
                                 n_estimators=96, random_state=123,
                                 subsample=0.8938290428827321,
                                 validation_fraction=0.9577535215137098)

C-index score: 0.59

GradientBoostingSurvivalAnalysis(ccp_alpha=0.009625013743012712,
                                 criterion='squared_error',
                                 dropout_rate=0.1897783294507234,
                                 learning_rate=0.015420772490455037,
                                 max_features='auto', max_leaf_nodes=14,
                                 min_impurity_decrease=5.869825897765074e-07,
                                 min_samples_leaf=13, min_samples_split=20,
                                 min_weight_fraction_leaf=0.29880213170319914,
                                 n_estimators=430, random_state=123,
                                 subsample=0.9101431135071837,
                                 validation_fraction=0.9964423942006735)

IBS: 0.22

In [66]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [67]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 22:23:45,506] A new study created in memory with name: no-name-bb7530df-fceb-4e0a-b6ac-edbcf8ab2de0

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 22:23:46,956] Trial 0 finished with value: 0.6849872959240584 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6849872959240584.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 22:23:54,379] Trial 1 finished with value: 0.6943010214142545 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.6943010214142545.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:23:55,950] Trial 2 finished with value: 0.7047272149390397 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.7047272149390397.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:23:57,621] Trial 3 finished with value: 0.7370651170158657 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.7370651170158657.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:24:00,501] Trial 4 finished with value: 0.7386446556207208 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.7386446556207208.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 22:24:03,976] Trial 5 finished with value: 0.6747194387812013 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.7386446556207208.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 22:24:05,319] Trial 6 finished with value: 0.6218282519980552 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.7386446556207208.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:24:05,569] Trial 7 finished with value: 0.7119313465917007 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.7386446556207208.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:24:07,206] Trial 8 finished with value: 0.7129523231641478 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.7386446556207208.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:24:11,611] Trial 9 finished with value: 0.7370651170158657 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.7386446556207208.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:24:15,140] Trial 10 finished with value: 0.7417735896527203 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.7417735896527203.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:24:19,140] Trial 11 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:24:22,440] Trial 12 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 22:24:27,164] Trial 13 finished with value: 0.679353493107157 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:24:30,301] Trial 14 finished with value: 0.7471552201530218 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:24:33,340] Trial 15 finished with value: 0.7386446556207208 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:24:38,767] Trial 16 finished with value: 0.7435051913843221 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:24:45,413] Trial 17 finished with value: 0.7405283204790691 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 416, 'learning_rate': 0.08639690405722114}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:24:49,285] Trial 18 finished with value: 0.7405283204790691 and parameters: {'subsample': 0.35801092912005106, 'dropout_rate': 0.33602353085084236, 'n_estimators': 256, 'learning_rate': 0.08307767561539126}. Best is trial 11 with value: 0.7476247037210969.

Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:24:50,457] Trial 19 finished with value: 0.7458931019894951 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7254192287154788, 'n_estimators': 117, 'learning_rate': 0.09614402133777997}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:24:57,001] Trial 20 finished with value: 0.7369130538891191 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 423, 'learning_rate': 0.07788582119853761}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:25:01,584] Trial 21 finished with value: 0.7471552201530218 and parameters: {'subsample': 0.11062421192073678, 'dropout_rate': 0.7075879968118339, 'n_estimators': 348, 'learning_rate': 0.09588015704350664}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:25:04,663] Trial 22 finished with value: 0.7430832504560521 and parameters: {'subsample': 0.17037433318378448, 'dropout_rate': 0.764223918656215, 'n_estimators': 305, 'learning_rate': 0.09979249643444077}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:25:08,670] Trial 23 finished with value: 0.7435051913843221 and parameters: {'subsample': 0.1882001920901971, 'dropout_rate': 0.5767392416088596, 'n_estimators': 339, 'learning_rate': 0.09228487500058613}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:25:12,333] Trial 24 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.10032123431548137, 'dropout_rate': 0.9684931648209879, 'n_estimators': 388, 'learning_rate': 0.0802723125714484}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:25:17,528] Trial 25 finished with value: 0.7370651170158657 and parameters: {'subsample': 0.4133596270549855, 'dropout_rate': 0.9814337999737701, 'n_estimators': 405, 'learning_rate': 0.07897720038644866}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:25:20,458] Trial 26 finished with value: 0.7351814521575173 and parameters: {'subsample': 0.29436693962013616, 'dropout_rate': 0.30720738642318285, 'n_estimators': 245, 'learning_rate': 0.06349383809213646}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 22:25:27,255] Trial 27 finished with value: 0.6169262912137415 and parameters: {'subsample': 0.9555788020080305, 'dropout_rate': 0.6087801618108066, 'n_estimators': 456, 'learning_rate': 0.06676860919367211}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:25:31,301] Trial 28 finished with value: 0.6944593577961825 and parameters: {'subsample': 0.6088999383640823, 'dropout_rate': 0.8192295755232234, 'n_estimators': 384, 'learning_rate': 0.08078072275147408}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 22:25:34,295] Trial 29 finished with value: 0.6218282519980552 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.41533846889329507, 'n_estimators': 322, 'learning_rate': 0.0892538312157202}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:25:39,468] Trial 30 finished with value: 0.7386446556207208 and parameters: {'subsample': 0.21797436717278929, 'dropout_rate': 0.16903977002361698, 'n_estimators': 283, 'learning_rate': 0.044040119088987244}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:25:43,614] Trial 31 finished with value: 0.7471552201530218 and parameters: {'subsample': 0.12927234629827838, 'dropout_rate': 0.9690972067181969, 'n_estimators': 383, 'learning_rate': 0.09233052029041879}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:25:48,663] Trial 32 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.10197013154249483, 'dropout_rate': 0.9006234235846082, 'n_estimators': 449, 'learning_rate': 0.09214772080187031}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:25:53,442] Trial 33 finished with value: 0.7413516487244503 and parameters: {'subsample': 0.16421336528135802, 'dropout_rate': 0.9268713272970187, 'n_estimators': 453, 'learning_rate': 0.07794503671868204}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:25:58,210] Trial 34 finished with value: 0.7374300800969993 and parameters: {'subsample': 0.23087858755854718, 'dropout_rate': 0.8311198269799329, 'n_estimators': 477, 'learning_rate': 0.07104054321866782}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:25:59,525] Trial 35 finished with value: 0.7387528807289458 and parameters: {'subsample': 0.29440822025230656, 'dropout_rate': 0.9999753567840282, 'n_estimators': 232, 'learning_rate': 0.09340164470114515}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:26:06,977] Trial 36 finished with value: 0.7471552201530218 and parameters: {'subsample': 0.1472825644233607, 'dropout_rate': 0.45922216511134195, 'n_estimators': 490, 'learning_rate': 0.07364671948774787}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:26:14,063] Trial 37 finished with value: 0.7374300800969993 and parameters: {'subsample': 0.22877221290518623, 'dropout_rate': 0.5102437401048863, 'n_estimators': 437, 'learning_rate': 0.059207327336158105}. Best is trial 11 with value: 0.7476247037210969.

Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:26:18,939] Trial 38 finished with value: 0.7387528807289458 and parameters: {'subsample': 0.3297325755614151, 'dropout_rate': 0.8867789132968811, 'n_estimators': 392, 'learning_rate': 0.08480908032505553}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:26:20,527] Trial 39 finished with value: 0.7386446556207208 and parameters: {'subsample': 0.1910828860959901, 'dropout_rate': 0.29848665859072016, 'n_estimators': 145, 'learning_rate': 0.06892741183938003}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:26:20,884] Trial 40 finished with value: 0.7375058945927193 and parameters: {'subsample': 0.43117832251264454, 'dropout_rate': 0.7942402623613096, 'n_estimators': 44, 'learning_rate': 0.09083529332655457}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:26:24,407] Trial 41 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.10471436370118233, 'dropout_rate': 0.9432108264211424, 'n_estimators': 354, 'learning_rate': 0.0993939723603888}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:26:27,365] Trial 42 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.10319905773816981, 'dropout_rate': 0.9428165272301137, 'n_estimators': 279, 'learning_rate': 0.09477321051183016}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:26:30,797] Trial 43 finished with value: 0.7421442833199018 and parameters: {'subsample': 0.1582430717253308, 'dropout_rate': 0.8684114133163081, 'n_estimators': 331, 'learning_rate': 0.0844262120808547}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 22:26:30,938] Trial 44 finished with value: 0.679353493107157 and parameters: {'subsample': 0.24718870034059304, 'dropout_rate': 0.9241820789065098, 'n_estimators': 3, 'learning_rate': 0.08951219679204844}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 22:26:35,687] Trial 45 finished with value: 0.6690856359642999 and parameters: {'subsample': 0.7937809606966539, 'dropout_rate': 0.20601602290044557, 'n_estimators': 362, 'learning_rate': 0.02274904980797578}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:26:39,020] Trial 46 finished with value: 0.7456639194073714 and parameters: {'subsample': 0.13247691307003695, 'dropout_rate': 0.14648424644002478, 'n_estimators': 281, 'learning_rate': 0.07635421514953118}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:26:44,250] Trial 47 finished with value: 0.7430832504560521 and parameters: {'subsample': 0.19598228689905128, 'dropout_rate': 0.8586094153719108, 'n_estimators': 399, 'learning_rate': 0.09648686804984326}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:26:49,613] Trial 48 finished with value: 0.7047272149390397 and parameters: {'subsample': 0.5990656023377149, 'dropout_rate': 0.6550794807592543, 'n_estimators': 447, 'learning_rate': 0.08106775275829065}. Best is trial 11 with value: 0.7476247037210969.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:26:55,095] Trial 49 finished with value: 0.7493563054526986 and parameters: {'subsample': 0.13799461538888846, 'dropout_rate': 0.1304931000922671, 'n_estimators': 359, 'learning_rate': 0.00524351186486742}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:26:58,370] Trial 50 finished with value: 0.7449652532571724 and parameters: {'subsample': 0.1529571356866799, 'dropout_rate': 0.14501343490387253, 'n_estimators': 301, 'learning_rate': 0.023141608428246342}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:27:03,357] Trial 51 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.10888451531029869, 'dropout_rate': 0.10128192473325, 'n_estimators': 363, 'learning_rate': 0.016769783329425858}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:27:07,353] Trial 52 finished with value: 0.7449652532571724 and parameters: {'subsample': 0.14224718402288763, 'dropout_rate': 0.1997659122884034, 'n_estimators': 326, 'learning_rate': 0.008126360906098393}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:27:11,638] Trial 53 finished with value: 0.7401834990061763 and parameters: {'subsample': 0.18971475239825097, 'dropout_rate': 0.1414997888592217, 'n_estimators': 348, 'learning_rate': 0.038233197313525535}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:27:18,667] Trial 54 finished with value: 0.7471552201530218 and parameters: {'subsample': 0.12864360307628528, 'dropout_rate': 0.36067606478019143, 'n_estimators': 373, 'learning_rate': 0.0316002312907681}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:27:27,606] Trial 55 finished with value: 0.7386446556207208 and parameters: {'subsample': 0.2525262633304453, 'dropout_rate': 0.9592599560119247, 'n_estimators': 417, 'learning_rate': 0.09948550089347807}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:27:30,159] Trial 56 finished with value: 0.7383309398006759 and parameters: {'subsample': 0.3223739530260814, 'dropout_rate': 0.894947947927084, 'n_estimators': 217, 'learning_rate': 0.0015084656987339184}. Best is trial 49 with value: 0.7493563054526986.

Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:27:34,568] Trial 57 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.10148833491313695, 'dropout_rate': 0.2670376806268556, 'n_estimators': 316, 'learning_rate': 0.053463562739806146}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:27:38,507] Trial 58 finished with value: 0.7479478547484731 and parameters: {'subsample': 0.17872819351209274, 'dropout_rate': 0.1335365954180555, 'n_estimators': 337, 'learning_rate': 0.08721652357667357}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:27:44,285] Trial 59 finished with value: 0.7421442833199018 and parameters: {'subsample': 0.2043399893861393, 'dropout_rate': 0.12886471937635585, 'n_estimators': 400, 'learning_rate': 0.08701040020718107}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:27:50,569] Trial 60 finished with value: 0.7488868218846234 and parameters: {'subsample': 0.17457340821606482, 'dropout_rate': 0.18502656442051676, 'n_estimators': 429, 'learning_rate': 0.08213219643921225}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:27:56,412] Trial 61 finished with value: 0.7471552201530218 and parameters: {'subsample': 0.1662338114342265, 'dropout_rate': 0.17195154455331807, 'n_estimators': 427, 'learning_rate': 0.08185683196425496}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:28:02,700] Trial 62 finished with value: 0.7471552201530218 and parameters: {'subsample': 0.17731922081856494, 'dropout_rate': 0.21607087781335657, 'n_estimators': 461, 'learning_rate': 0.08786770724775964}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:28:09,714] Trial 63 finished with value: 0.7475771610812918 and parameters: {'subsample': 0.21781522049624352, 'dropout_rate': 0.12276711586758451, 'n_estimators': 500, 'learning_rate': 0.09118455693410299}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:28:13,075] Trial 64 finished with value: 0.7422160841921494 and parameters: {'subsample': 0.2850132930490832, 'dropout_rate': 0.18074824646328208, 'n_estimators': 338, 'learning_rate': 0.07661938974233341}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:28:17,715] Trial 65 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.13908451765026308, 'dropout_rate': 0.280049930891542, 'n_estimators': 378, 'learning_rate': 0.08363527913963492}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:28:20,015] Trial 66 finished with value: 0.7387528807289458 and parameters: {'subsample': 0.2544490852713979, 'dropout_rate': 0.2411579312577909, 'n_estimators': 259, 'learning_rate': 0.09694888056744547}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:28:22,963] Trial 67 finished with value: 0.7449652532571724 and parameters: {'subsample': 0.1722029600635453, 'dropout_rate': 0.18237545459400176, 'n_estimators': 295, 'learning_rate': 0.07443960818187423}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:28:29,692] Trial 68 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.13159369266339868, 'dropout_rate': 0.12430378766843754, 'n_estimators': 438, 'learning_rate': 0.06314273229683151}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:28:36,361] Trial 69 finished with value: 0.7387528807289458 and parameters: {'subsample': 0.5184165764096695, 'dropout_rate': 0.10168264284677, 'n_estimators': 389, 'learning_rate': 0.09373727173694862}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:28:41,802] Trial 70 finished with value: 0.7387528807289458 and parameters: {'subsample': 0.39304488763961287, 'dropout_rate': 0.22104414349916188, 'n_estimators': 410, 'learning_rate': 0.008127880939407618}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:28:46,839] Trial 71 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.11721243365128992, 'dropout_rate': 0.151117463899618, 'n_estimators': 357, 'learning_rate': 0.0971977426901038}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:28:49,849] Trial 72 finished with value: 0.736491112960849 and parameters: {'subsample': 0.15436173050572216, 'dropout_rate': 0.9298516938780148, 'n_estimators': 320, 'learning_rate': 0.086493193389562}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:28:54,542] Trial 73 finished with value: 0.7391616818286011 and parameters: {'subsample': 0.2094489579875526, 'dropout_rate': 0.978787724111281, 'n_estimators': 469, 'learning_rate': 0.08976652279422788}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:28:59,404] Trial 74 finished with value: 0.748046644649367 and parameters: {'subsample': 0.10099983845623818, 'dropout_rate': 0.1686608344062563, 'n_estimators': 350, 'learning_rate': 0.09207251950740498}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:29:03,299] Trial 75 finished with value: 0.7449652532571724 and parameters: {'subsample': 0.17967352503044318, 'dropout_rate': 0.16445711630909418, 'n_estimators': 336, 'learning_rate': 0.04605320680222661}. Best is trial 49 with value: 0.7493563054526986.

Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:29:08,510] Trial 76 finished with value: 0.7471552201530218 and parameters: {'subsample': 0.12850189742120152, 'dropout_rate': 0.1891599553477682, 'n_estimators': 375, 'learning_rate': 0.09404919893163159}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:29:11,682] Trial 77 finished with value: 0.7422160841921494 and parameters: {'subsample': 0.2356475368993836, 'dropout_rate': 0.24010466678021705, 'n_estimators': 310, 'learning_rate': 0.08165018266253268}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:29:18,559] Trial 78 finished with value: 0.7370651170158657 and parameters: {'subsample': 0.45394942851314213, 'dropout_rate': 0.4054839154204395, 'n_estimators': 432, 'learning_rate': 0.07011018430873495}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:29:21,815] Trial 79 finished with value: 0.6854567794921336 and parameters: {'subsample': 0.6745068465882641, 'dropout_rate': 0.33030778568800034, 'n_estimators': 292, 'learning_rate': 0.07938177550787616}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:29:26,679] Trial 80 finished with value: 0.7413516487244503 and parameters: {'subsample': 0.1453895993801854, 'dropout_rate': 0.5106971439764427, 'n_estimators': 366, 'learning_rate': 0.09047157356678896}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:29:29,695] Trial 81 finished with value: 0.7471552201530218 and parameters: {'subsample': 0.1136504365574562, 'dropout_rate': 0.9958610361391691, 'n_estimators': 347, 'learning_rate': 0.09975593691434016}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:29:33,449] Trial 82 finished with value: 0.7493563054526986 and parameters: {'subsample': 0.10914386929043639, 'dropout_rate': 0.12260128817598166, 'n_estimators': 353, 'learning_rate': 0.09238695535991932}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:29:40,142] Trial 83 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.10238580933194333, 'dropout_rate': 0.1264876965495307, 'n_estimators': 392, 'learning_rate': 0.08470401575076288}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:29:47,922] Trial 84 finished with value: 0.7471552201530218 and parameters: {'subsample': 0.15764470199290342, 'dropout_rate': 0.1588238041970289, 'n_estimators': 407, 'learning_rate': 0.09278563316479198}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:29:53,983] Trial 85 finished with value: 0.7417735896527203 and parameters: {'subsample': 0.17960817945047752, 'dropout_rate': 0.10316041974947594, 'n_estimators': 343, 'learning_rate': 0.08834563603650687}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:29:58,995] Trial 86 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.13115321312655376, 'dropout_rate': 0.12818229734637995, 'n_estimators': 323, 'learning_rate': 0.09520849662997415}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:30:05,631] Trial 87 finished with value: 0.7435051913843221 and parameters: {'subsample': 0.20388210646634392, 'dropout_rate': 0.21339862288737763, 'n_estimators': 444, 'learning_rate': 0.08526241345397692}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:30:07,987] Trial 88 finished with value: 0.7449652532571724 and parameters: {'subsample': 0.1491268020720009, 'dropout_rate': 0.1944964369732728, 'n_estimators': 275, 'learning_rate': 0.09129688316938651}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 22:30:11,767] Trial 89 finished with value: 0.679353493107157 and parameters: {'subsample': 0.9978393557214087, 'dropout_rate': 0.15686046224939765, 'n_estimators': 368, 'learning_rate': 0.0974544622654325}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:30:17,978] Trial 90 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.11995083680675664, 'dropout_rate': 0.6827081606721607, 'n_estimators': 482, 'learning_rate': 0.06614579056733322}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:30:21,555] Trial 91 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.11786147948434998, 'dropout_rate': 0.8455038743047455, 'n_estimators': 354, 'learning_rate': 0.09519741582696505}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:30:24,025] Trial 92 finished with value: 0.7415444070705967 and parameters: {'subsample': 0.18742417757708363, 'dropout_rate': 0.9563831045376199, 'n_estimators': 332, 'learning_rate': 0.08803586418553142}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:30:27,774] Trial 93 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.1011638329698273, 'dropout_rate': 0.7918184490441242, 'n_estimators': 385, 'learning_rate': 0.05811339903898594}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:30:30,666] Trial 94 finished with value: 0.7422430732207954 and parameters: {'subsample': 0.16543188380194923, 'dropout_rate': 0.1260789509040807, 'n_estimators': 305, 'learning_rate': 0.0361385364575488}. Best is trial 49 with value: 0.7493563054526986.

Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:30:34,530] Trial 95 finished with value: 0.7476247037210969 and parameters: {'subsample': 0.10060134083448845, 'dropout_rate': 0.9043479128274928, 'n_estimators': 419, 'learning_rate': 0.09751969757071219}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 22:30:37,861] Trial 96 finished with value: 0.7418211322925254 and parameters: {'subsample': 0.14153308588476268, 'dropout_rate': 0.6036895992649407, 'n_estimators': 353, 'learning_rate': 0.09253453047348954}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 22:30:39,789] Trial 97 finished with value: 0.7422160841921494 and parameters: {'subsample': 0.22570028642335044, 'dropout_rate': 0.1437665485108484, 'n_estimators': 244, 'learning_rate': 0.08000293307081133}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 22:30:44,582] Trial 98 finished with value: 0.7471552201530218 and parameters: {'subsample': 0.1292535361085004, 'dropout_rate': 0.17248976561011353, 'n_estimators': 401, 'learning_rate': 0.08321504947219541}. Best is trial 49 with value: 0.7493563054526986.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8291139240506329

[I 2024-04-14 22:30:49,313] A new study created in memory with name: no-name-7c0c674c-5617-48cd-8942-071af6dd340f

Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 22:30:49,270] Trial 99 finished with value: 0.7390042308840747 and parameters: {'subsample': 0.16025895184861239, 'dropout_rate': 0.11338489207123346, 'n_estimators': 378, 'learning_rate': 0.02710910036350006}. Best is trial 49 with value: 0.7493563054526986.


* Best trial for C-index:
 FrozenTrial(number=49, state=TrialState.COMPLETE, values=[0.7493563054526986], datetime_start=datetime.datetime(2024, 4, 14, 22, 26, 49, 619339), datetime_complete=datetime.datetime(2024, 4, 14, 22, 26, 55, 94796), params={'subsample': 0.13799461538888846, 'dropout_rate': 0.1304931000922671, 'n_estimators': 359, 'learning_rate': 0.00524351186486742}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=49, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.13799461538888846, 'dropout_rate': 0.1304931000922671, 'n_estimators': 359, 'learning_rate': 0.00524351186486742}


* Best Score for C-index:
 0.7493563054526986

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.18504584755520848
Fold 2 IBS: 0.263946415780978
Fold 3 IBS: 0.1617903636180167
Fold 4 IBS: 0.2600787216130082
Fold 5 IBS: 0.23318480871469416
[I 2024-04-14 22:30:50,031] Trial 0 finished with value: 0.22080923145638112 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.20370621643796663
Fold 2 IBS: 0.3014080683205247
Fold 3 IBS: 0.17042892249188574
Fold 4 IBS: 0.31585465097929083
Fold 5 IBS: 0.27370157532625616
[I 2024-04-14 22:30:56,838] Trial 1 finished with value: 0.2530198867111848 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.19309554280636426
Fold 2 IBS: 0.30090488415559263
Fold 3 IBS: 0.1653332066108254
Fold 4 IBS: 0.31368208313434126
Fold 5 IBS: 0.26490979029895373
[I 2024-04-14 22:30:58,060] Trial 2 finished with value: 0.24758510140121545 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.19319694714307042
Fold 2 IBS: 0.29867185430046916
Fold 3 IBS: 0.16607224064552437
Fold 4 IBS: 0.31117164271618164
Fold 5 IBS: 0.26803683949365764
[I 2024-04-14 22:30:59,460] Trial 3 finished with value: 0.24742990485978064 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.16913764081029461
Fold 2 IBS: 0.3006292211879915
Fold 3 IBS: 0.18407613385349988
Fold 4 IBS: 0.31302577428347006
Fold 5 IBS: 0.26908387741821566
[I 2024-04-14 22:31:01,842] Trial 4 finished with value: 0.24719052951069434 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.2034038137478441
Fold 2 IBS: 0.3014078956744048
Fold 3 IBS: 0.16987803315182726
Fold 4 IBS: 0.31585217062420684
Fold 5 IBS: 0.27369201709429525
[I 2024-04-14 22:31:04,738] Trial 5 finished with value: 0.2528467860585156 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.1829350490073511
Fold 2 IBS: 0.22574908076349612
Fold 3 IBS: 0.16688500534550946
Fold 4 IBS: 0.2247124094692705
Fold 5 IBS: 0.21906832093288123
[I 2024-04-14 22:31:05,966] Trial 6 finished with value: 0.2038699731037017 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2038699731037017.
Fold 1 IBS: 0.19171533392644077
Fold 2 IBS: 0.20303779786155224
Fold 3 IBS: 0.17884668693475606
Fold 4 IBS: 0.20856968304886764
Fold 5 IBS: 0.211118754013436
[I 2024-04-14 22:31:06,282] Trial 7 finished with value: 0.19865765115701053 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.18287719589591964
Fold 2 IBS: 0.27502505757765827
Fold 3 IBS: 0.1610534980201046
Fold 4 IBS: 0.26090944510806957
Fold 5 IBS: 0.2349744292756046
[I 2024-04-14 22:31:08,389] Trial 8 finished with value: 0.22296792517547134 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.19395518943031972
Fold 2 IBS: 0.3014080117730072
Fold 3 IBS: 0.1827239722426296
Fold 4 IBS: 0.31585254695670684
Fold 5 IBS: 0.2759459715593507
[I 2024-04-14 22:31:13,805] Trial 9 finished with value: 0.2539771383924028 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.2133785145028611
Fold 2 IBS: 0.22091211268741265
Fold 3 IBS: 0.20387901759065918
Fold 4 IBS: 0.22439199408788554
Fold 5 IBS: 0.21780913258638765
[I 2024-04-14 22:31:14,053] Trial 10 finished with value: 0.21607415429104124 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.2133947249090869
Fold 2 IBS: 0.22105802807283764
Fold 3 IBS: 0.2036691246434108
Fold 4 IBS: 0.22430544465380128
Fold 5 IBS: 0.21777799603810094
[I 2024-04-14 22:31:14,211] Trial 11 finished with value: 0.2160410636634475 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.1800964651509932
Fold 2 IBS: 0.297403850587758
Fold 3 IBS: 0.16597777897100402
Fold 4 IBS: 0.29519467653629033
Fold 5 IBS: 0.25346374715090736
[I 2024-04-14 22:31:14,804] Trial 12 finished with value: 0.23842730367939055 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.19280005315897206
Fold 2 IBS: 0.2974213595064474
Fold 3 IBS: 0.17117639615033295
Fold 4 IBS: 0.30578737203308676
Fold 5 IBS: 0.25431185381872007
[I 2024-04-14 22:31:17,366] Trial 13 finished with value: 0.24429940693351188 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.19784216344977562
Fold 2 IBS: 0.20506180854560294
Fold 3 IBS: 0.18635045949578385
Fold 4 IBS: 0.21499223626865088
Fold 5 IBS: 0.21149042228501566
[I 2024-04-14 22:31:17,907] Trial 14 finished with value: 0.20314741800896577 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.20999702532392847
Fold 2 IBS: 0.21734365927334173
Fold 3 IBS: 0.20020119375698603
Fold 4 IBS: 0.22202144488912645
Fold 5 IBS: 0.21659611545289936
[I 2024-04-14 22:31:18,295] Trial 15 finished with value: 0.21323188773925641 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.2039212844188623
Fold 2 IBS: 0.2103474992415337
Fold 3 IBS: 0.19339791850328025
Fold 4 IBS: 0.21877297557249897
Fold 5 IBS: 0.21360848363027263
[I 2024-04-14 22:31:18,603] Trial 16 finished with value: 0.20800963227328956 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.18288342929944057
Fold 2 IBS: 0.23926430161132384
Fold 3 IBS: 0.16665249308120655
Fold 4 IBS: 0.2362841280803267
Fold 5 IBS: 0.22353483274970617
[I 2024-04-14 22:31:19,433] Trial 17 finished with value: 0.20972383696440078 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.1773954201959245
Fold 2 IBS: 0.24024111720982294
Fold 3 IBS: 0.16255955996419777
Fold 4 IBS: 0.22670032118705843
Fold 5 IBS: 0.22295397631420336
[I 2024-04-14 22:31:22,486] Trial 18 finished with value: 0.2059700789742414 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.18919742505073658
Fold 2 IBS: 0.2023431594465361

Fold 3 IBS: 0.1783999568257794
Fold 4 IBS: 0.20099313441590488
Fold 5 IBS: 0.2127622739815413
[I 2024-04-14 22:31:22,850] Trial 19 finished with value: 0.19673918994409964 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.19673918994409964.
Fold 1 IBS: 0.1881299300179791
Fold 2 IBS: 0.20500626401911293
Fold 3 IBS: 0.1819421294378562
Fold 4 IBS: 0.20497765873828705
Fold 5 IBS: 0.21298081915188694
[I 2024-04-14 22:31:23,138] Trial 20 finished with value: 0.19860736027302442 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.19673918994409964.
Fold 1 IBS: 0.19533105622634891
Fold 2 IBS: 0.20393569161683953
Fold 3 IBS: 0.18712698518091442
Fold 4 IBS: 0.20944879242499856
Fold 5 IBS: 0.21303933620208118
[I 2024-04-14 22:31:23,365] Trial 21 finished with value: 0.20177637233023654 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.19673918994409964.
Fold 1 IBS: 0.21319234752616703
Fold 2 IBS: 0.22073279019144837
Fold 3 IBS: 0.20313821183683503
Fold 4 IBS: 0.22386245547893124
Fold 5 IBS: 0.2175077980822652
[I 2024-04-14 22:31:23,671] Trial 22 finished with value: 0.21568672062312938 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 19 with value: 0.19673918994409964.
Fold 1 IBS: 0.15947091624866147
Fold 2 IBS: 0.23404935664444218
Fold 3 IBS: 0.16544541971054122
Fold 4 IBS: 0.22513140435765808
Fold 5 IBS: 0.22623410400791188
[I 2024-04-14 22:31:24,733] Trial 23 finished with value: 0.20206624019384298 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 19 with value: 0.19673918994409964.
Fold 1 IBS: 0.1848253360970415
Fold 2 IBS: 0.2124184957753865
Fold 3 IBS: 0.16839399220873313
Fold 4 IBS: 0.21192615623352185
Fold 5 IBS: 0.21327382867550682
[I 2024-04-14 22:31:25,187] Trial 24 finished with value: 0.19816756179803793 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 19 with value: 0.19673918994409964.
Fold 1 IBS: 0.15808443361920083
Fold 2 IBS: 0.24219622203257674
Fold 3 IBS: 0.16256464789472305
Fold 4 IBS: 0.23653257592708457
Fold 5 IBS: 0.22681115607844332
[I 2024-04-14 22:31:25,828] Trial 25 finished with value: 0.20523780711040568 and parameters: {'subsample': 0.2217965007715769, 'dropout_rate': 0.9319520966822452, 'n_estimators': 72, 'learning_rate': 0.08579428551722094}. Best is trial 19 with value: 0.19673918994409964.
Fold 1 IBS: 0.14950720275635843
Fold 2 IBS: 0.26530090228580633
Fold 3 IBS: 0.1700810206983489
Fold 4 IBS: 0.25166164142649533
Fold 5 IBS: 0.2483973392158414
[I 2024-04-14 22:31:27,044] Trial 26 finished with value: 0.21698962127657007 and parameters: {'subsample': 0.10665946004649053, 'dropout_rate': 0.89397617546164, 'n_estimators': 150, 'learning_rate': 0.06722393082067463}. Best is trial 19 with value: 0.19673918994409964.
Fold 1 IBS: 0.18839464619446405
Fold 2 IBS: 0.30140803928325294
Fold 3 IBS: 0.22433072883146754
Fold 4 IBS: 0.31585395754581636
Fold 5 IBS: 0.2797698955233327
[I 2024-04-14 22:31:30,332] Trial 27 finished with value: 0.26195145347566673 and parameters: {'subsample': 0.4014627938715816, 'dropout_rate': 0.9861686560685959, 'n_estimators': 422, 'learning_rate': 0.06071884280131438}. Best is trial 19 with value: 0.19673918994409964.
Fold 1 IBS: 0.176637190372941
Fold 2 IBS: 0.30118368099824544
Fold 3 IBS: 0.18513777511883225
Fold 4 IBS: 0.3144539433370043
Fold 5 IBS: 0.2716451561242865
[I 2024-04-14 22:31:31,985] Trial 28 finished with value: 0.24981154919026188 and parameters: {'subsample': 0.301636198347479, 'dropout_rate': 0.7753950220583815, 'n_estimators': 236, 'learning_rate': 0.06152638329235058}. Best is trial 19 with value: 0.19673918994409964.
Fold 1 IBS: 0.15685750496894918
Fold 2 IBS: 0.27878081773997115
Fold 3 IBS: 0.17248578887873575
Fold 4 IBS: 0.2539391679955545
Fold 5 IBS: 0.2452014901267099
[I 2024-04-14 22:31:32,539] Trial 29 finished with value: 0.2214529539419841 and parameters: {'subsample': 0.17398784645198978, 'dropout_rate': 0.8349232147406402, 'n_estimators': 104, 'learning_rate': 0.08423642007181871}. Best is trial 19 with value: 0.19673918994409964.
Fold 1 IBS: 0.17423988141491098
Fold 2 IBS: 0.2150591443763459
Fold 3 IBS: 0.16669819924456905
Fold 4 IBS: 0.20813620881754796
Fold 5 IBS: 0.2152415677746221
[I 2024-04-14 22:31:32,990] Trial 30 finished with value: 0.19587500032559918 and parameters: {'subsample': 0.2381729579870052, 'dropout_rate': 0.9172391219359199, 'n_estimators': 82, 'learning_rate': 0.0483156944073118}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.1740208764857199
Fold 2 IBS: 0.22025554342589576
Fold 3 IBS: 0.1652689721096754
Fold 4 IBS: 0.21461975112376203
Fold 5 IBS: 0.2171510836061579
[I 2024-04-14 22:31:33,445] Trial 31 finished with value: 0.1982632453502422 and parameters: {'subsample': 0.2464163054601055, 'dropout_rate': 0.9271779254835972, 'n_estimators': 86, 'learning_rate': 0.04992642229657319}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.16992243256545633
Fold 2 IBS: 0.2547310774727292
Fold 3 IBS: 0.16316330053037192
Fold 4 IBS: 0.25196509736947087
Fold 5 IBS: 0.2308172007465473
[I 2024-04-14 22:31:34,090] Trial 32 finished with value: 0.21411982173691513 and parameters: {'subsample': 0.24679846818428344, 'dropout_rate': 0.9480531765532226, 'n_estimators': 129, 'learning_rate': 0.049309899563523385}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.17848705131694004
Fold 2 IBS: 0.23321850467354452
Fold 3 IBS: 0.16319852386981645
Fold 4 IBS: 0.22262857181662868
Fold 5 IBS: 0.22049811308495956
[I 2024-04-14 22:31:34,576] Trial 33 finished with value: 0.20360615295237783 and parameters: {'subsample': 0.42833421982844316, 'dropout_rate': 0.906441247519853, 'n_estimators': 84, 'learning_rate': 0.056987153621534996}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.1642762275903523
Fold 2 IBS: 0.2806746771173498
Fold 3 IBS: 0.1691018741121368
Fold 4 IBS: 0.27559620938851886
Fold 5 IBS: 0.24182314885255943
[I 2024-04-14 22:31:35,513] Trial 34 finished with value: 0.22629442741218347 and parameters: {'subsample': 0.25579443215975756, 'dropout_rate': 0.8350558435468665, 'n_estimators': 171, 'learning_rate': 0.04823191358053747}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.19115300176695646
Fold 2 IBS: 0.2031631168773369
Fold 3 IBS: 0.18087340046201708
Fold 4 IBS: 0.20788519828061772
Fold 5 IBS: 0.21287267911359212
[I 2024-04-14 22:31:35,692] Trial 35 finished with value: 0.19918947930010406 and parameters: {'subsample': 0.29314602479486707, 'dropout_rate': 0.9999658564779634, 'n_estimators': 26, 'learning_rate': 0.06920924038817856}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.17935029536671768
Fold 2 IBS: 0.2798133275191118
Fold 3 IBS: 0.16138201658108425
Fold 4 IBS: 0.277856543310019
Fold 5 IBS: 0.24341238821271485
[I 2024-04-14 22:31:36,484] Trial 36 finished with value: 0.22836291419792953 and parameters: {'subsample': 0.4392643760586835, 'dropout_rate': 0.24408912236765595, 'n_estimators': 113, 'learning_rate': 0.07650775910789946}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.18802170117548192
Fold 2 IBS: 0.29447369912211585
Fold 3 IBS: 0.16266230787828062
Fold 4 IBS: 0.29458389650118244
Fold 5 IBS: 0.24838156146814955
[I 2024-04-14 22:31:37,511] Trial 37 finished with value: 0.23762463322904206 and parameters: {'subsample': 0.5507574128502895, 'dropout_rate': 0.8608568379956052, 'n_estimators': 155, 'learning_rate': 0.05621431261796065}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.1540827000103615
Fold 2 IBS: 0.24758664089597135

Fold 3 IBS: 0.1675187073192873
Fold 4 IBS: 0.2315629911368222
Fold 5 IBS: 0.2332838201025736
[I 2024-04-14 22:31:38,710] Trial 38 finished with value: 0.20680697189300318 and parameters: {'subsample': 0.1710779175611994, 'dropout_rate': 0.9288534916051375, 'n_estimators': 197, 'learning_rate': 0.036023800474466655}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.1876140504745091
Fold 2 IBS: 0.20563381823568802
Fold 3 IBS: 0.17202903977012926
Fold 4 IBS: 0.2067894022485534
Fold 5 IBS: 0.21264550977192898
[I 2024-04-14 22:31:39,050] Trial 39 finished with value: 0.19694236410016178 and parameters: {'subsample': 0.3537909584345821, 'dropout_rate': 0.8744094300062906, 'n_estimators': 59, 'learning_rate': 0.04711870419619728}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.18448495606229867
Fold 2 IBS: 0.2155619099375562
Fold 3 IBS: 0.16824012001923247
Fold 4 IBS: 0.21346674211873537
Fold 5 IBS: 0.21402742087944407
[I 2024-04-14 22:31:39,463] Trial 40 finished with value: 0.19915622980345335 and parameters: {'subsample': 0.5732763428296245, 'dropout_rate': 0.7404989505064663, 'n_estimators': 54, 'learning_rate': 0.06660232733235426}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.17781363182607124
Fold 2 IBS: 0.22058844209659448
Fold 3 IBS: 0.16475547422493897
Fold 4 IBS: 0.2110634058418947
Fold 5 IBS: 0.2168150295367869
[I 2024-04-14 22:31:40,028] Trial 41 finished with value: 0.19820719670525724 and parameters: {'subsample': 0.34578757734799925, 'dropout_rate': 0.8788853441122854, 'n_estimators': 88, 'learning_rate': 0.04884047076787994}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.19934378150393145
Fold 2 IBS: 0.20617849037504465
Fold 3 IBS: 0.18774021509648142
Fold 4 IBS: 0.2147474654986803
Fold 5 IBS: 0.21293011575902263
[I 2024-04-14 22:31:40,262] Trial 42 finished with value: 0.20418801364663208 and parameters: {'subsample': 0.33789987815376404, 'dropout_rate': 0.8931341216565075, 'n_estimators': 23, 'learning_rate': 0.053894376446114514}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.18421572142692189
Fold 2 IBS: 0.21736385138879288
Fold 3 IBS: 0.16616190015704765
Fold 4 IBS: 0.21550013923018563
Fold 5 IBS: 0.21436791137771027
[I 2024-04-14 22:31:40,602] Trial 43 finished with value: 0.19952190471613168 and parameters: {'subsample': 0.4717598415162009, 'dropout_rate': 0.8680039169028084, 'n_estimators': 62, 'learning_rate': 0.05991231847439593}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.17539665412153915
Fold 2 IBS: 0.25381664475540106
Fold 3 IBS: 0.1619572164973234
Fold 4 IBS: 0.23626024469184084
Fold 5 IBS: 0.22868290366690983
[I 2024-04-14 22:31:41,358] Trial 44 finished with value: 0.21122273274660283 and parameters: {'subsample': 0.36128738430802604, 'dropout_rate': 0.5057702042743903, 'n_estimators': 130, 'learning_rate': 0.04652228012350071}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.20613463001830643
Fold 2 IBS: 0.21473355306575914
Fold 3 IBS: 0.19696939756848034
Fold 4 IBS: 0.21874826917004528
Fold 5 IBS: 0.21482113981948242
[I 2024-04-14 22:31:41,510] Trial 45 finished with value: 0.21028139792841474 and parameters: {'subsample': 0.2970668004862915, 'dropout_rate': 0.9580002968235438, 'n_estimators': 15, 'learning_rate': 0.03400538573985265}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.18897693890389555
Fold 2 IBS: 0.20370655370424656
Fold 3 IBS: 0.17722251041165302
Fold 4 IBS: 0.20953413853445993
Fold 5 IBS: 0.21135257825095138
[I 2024-04-14 22:31:41,980] Trial 46 finished with value: 0.1981585439610413 and parameters: {'subsample': 0.4307326273437892, 'dropout_rate': 0.8662614128615587, 'n_estimators': 91, 'learning_rate': 0.024992652172925307}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.20071819295605858
Fold 2 IBS: 0.2086370761903522
Fold 3 IBS: 0.1904492084139519
Fold 4 IBS: 0.21575539811202984
Fold 5 IBS: 0.21321105137650911
[I 2024-04-14 22:31:42,244] Trial 47 finished with value: 0.20575418540978033 and parameters: {'subsample': 0.5154202245870623, 'dropout_rate': 0.1240463473883398, 'n_estimators': 45, 'learning_rate': 0.023064794253730755}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.18048095982061635
Fold 2 IBS: 0.27262037995538513
Fold 3 IBS: 0.16097222600974445
Fold 4 IBS: 0.26356669635519725
Fold 5 IBS: 0.2346987328575458
[I 2024-04-14 22:31:43,945] Trial 48 finished with value: 0.2224677989996978 and parameters: {'subsample': 0.44240771735087686, 'dropout_rate': 0.8146600917967612, 'n_estimators': 248, 'learning_rate': 0.027044032224784076}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.18622697726531617
Fold 2 IBS: 0.20908058542212124
Fold 3 IBS: 0.17211482996183064
Fold 4 IBS: 0.21230414733090214
Fold 5 IBS: 0.2122281184103048
[I 2024-04-14 22:31:44,542] Trial 49 finished with value: 0.19839093167809502 and parameters: {'subsample': 0.6192069938222724, 'dropout_rate': 0.7271924315071985, 'n_estimators': 108, 'learning_rate': 0.02713079119975165}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.19550920546936468
Fold 2 IBS: 0.2037003767996933
Fold 3 IBS: 0.18432731614014047
Fold 4 IBS: 0.212376370905737
Fold 5 IBS: 0.21187299127420448
[I 2024-04-14 22:31:44,989] Trial 50 finished with value: 0.201557252117828 and parameters: {'subsample': 0.42222123825287444, 'dropout_rate': 0.6843290787742734, 'n_estimators': 72, 'learning_rate': 0.021363342350747383}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.1794600896917236
Fold 2 IBS: 0.22659761438995338
Fold 3 IBS: 0.1640761174187251
Fold 4 IBS: 0.2146280369395022
Fold 5 IBS: 0.21799604842142337
[I 2024-04-14 22:31:45,524] Trial 51 finished with value: 0.2005515813722655 and parameters: {'subsample': 0.3815255992575082, 'dropout_rate': 0.8803510576670203, 'n_estimators': 84, 'learning_rate': 0.05293830590274953}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.1900696466121789
Fold 2 IBS: 0.20266890508091306
Fold 3 IBS: 0.17679359544219617
Fold 4 IBS: 0.20816897343639296
Fold 5 IBS: 0.211695434354964
[I 2024-04-14 22:31:45,868] Trial 52 finished with value: 0.19787931098532902 and parameters: {'subsample': 0.3455946574392862, 'dropout_rate': 0.856113989682693, 'n_estimators': 49, 'learning_rate': 0.04652943750756749}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.18911731395783155
Fold 2 IBS: 0.20443523655436316
Fold 3 IBS: 0.17622135117863388
Fold 4 IBS: 0.20991490347987604
Fold 5 IBS: 0.21109130258008857
[I 2024-04-14 22:31:46,176] Trial 53 finished with value: 0.19815602155015866 and parameters: {'subsample': 0.4762788816560454, 'dropout_rate': 0.9385939481808312, 'n_estimators': 50, 'learning_rate': 0.04558051262695099}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.19694023473217756
Fold 2 IBS: 0.20505243224752875
Fold 3 IBS: 0.1858092435952595
Fold 4 IBS: 0.2137729836807142
Fold 5 IBS: 0.21206622874303588
[I 2024-04-14 22:31:46,447] Trial 54 finished with value: 0.20272822459974318 and parameters: {'subsample': 0.4782217418644513, 'dropout_rate': 0.9509150296349711, 'n_estimators': 37, 'learning_rate': 0.03727579170963399}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.21341121907065255
Fold 2 IBS: 0.22096269082327033
Fold 3 IBS: 0.20378224032590944
Fold 4 IBS: 0.22438363532649475
Fold 5 IBS: 0.21769864168746642
[I 2024-04-14 22:31:46,638] Trial 55 finished with value: 0.2160476854467587 and parameters: {'subsample': 0.7256048258456533, 'dropout_rate': 0.8378164810986685, 'n_estimators': 1, 'learning_rate': 0.044094398715112365}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.20397199032894792
Fold 2 IBS: 0.21333179025694868
Fold 3 IBS: 0.19601933314081957
Fold 4 IBS: 0.21783865017482698
Fold 5 IBS: 0.21523864792857939
[I 2024-04-14 22:31:46,864] Trial 56 finished with value: 0.2092800823660245 and parameters: {'subsample': 0.27433038550604805, 'dropout_rate': 0.7483350749905161, 'n_estimators': 19, 'learning_rate': 0.03223361260912044}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.17797518141236637
Fold 2 IBS: 0.30095875442079584

Fold 3 IBS: 0.17328317089014492
Fold 4 IBS: 0.31394529707721386
Fold 5 IBS: 0.2667682961494491
[I 2024-04-14 22:31:48,747] Trial 57 finished with value: 0.246586139989994 and parameters: {'subsample': 0.32826887806420246, 'dropout_rate': 0.9933561701936838, 'n_estimators': 283, 'learning_rate': 0.046115905841529976}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.20860918635569756
Fold 2 IBS: 0.21590342208816954
Fold 3 IBS: 0.19882549664838997
Fold 4 IBS: 0.22138259267967494
Fold 5 IBS: 0.21576315984193745
[I 2024-04-14 22:31:48,995] Trial 58 finished with value: 0.2120967715227739 and parameters: {'subsample': 0.5286310530837229, 'dropout_rate': 0.922313337459929, 'n_estimators': 41, 'learning_rate': 0.009368892992001188}. Best is trial 30 with value: 0.19587500032559918.
Fold 1 IBS: 0.1663205709204324
Fold 2 IBS: 0.20742615729931974
Fold 3 IBS: 0.1673944010677237
Fold 4 IBS: 0.19548723363098827
Fold 5 IBS: 0.2186581694007046
[I 2024-04-14 22:31:49,522] Trial 59 finished with value: 0.19105730646383373 and parameters: {'subsample': 0.14522006252948272, 'dropout_rate': 0.8084628917187764, 'n_estimators': 98, 'learning_rate': 0.04113440174073067}. Best is trial 59 with value: 0.19105730646383373.
Fold 1 IBS: 0.16117650325339278
Fold 2 IBS: 0.21351492846176584
Fold 3 IBS: 0.16790832857732013
Fold 4 IBS: 0.20248462536753253
Fold 5 IBS: 0.2226271677744071
[I 2024-04-14 22:31:50,296] Trial 60 finished with value: 0.1935423106868837 and parameters: {'subsample': 0.1375263612764897, 'dropout_rate': 0.9630819399302621, 'n_estimators': 126, 'learning_rate': 0.038980835478226394}. Best is trial 59 with value: 0.19105730646383373.
Fold 1 IBS: 0.1622238548874084
Fold 2 IBS: 0.2153492354086125
Fold 3 IBS: 0.16668306576889522
Fold 4 IBS: 0.20447025486823542
Fold 5 IBS: 0.2229048849127981
[I 2024-04-14 22:31:51,003] Trial 61 finished with value: 0.19432625916918994 and parameters: {'subsample': 0.1453463480776829, 'dropout_rate': 0.953864668987802, 'n_estimators': 127, 'learning_rate': 0.039832085240492705}. Best is trial 59 with value: 0.19105730646383373.
Fold 1 IBS: 0.1615085444490529
Fold 2 IBS: 0.21280732853120748
Fold 3 IBS: 0.16798831114022095
Fold 4 IBS: 0.20244470473337003
Fold 5 IBS: 0.2221523908949394
[I 2024-04-14 22:31:51,701] Trial 62 finished with value: 0.19338025594975816 and parameters: {'subsample': 0.14066257057329762, 'dropout_rate': 0.9632873028037965, 'n_estimators': 123, 'learning_rate': 0.03896306944108657}. Best is trial 59 with value: 0.19105730646383373.
Fold 1 IBS: 0.1524542002808089
Fold 2 IBS: 0.24712395719209537
Fold 3 IBS: 0.1677733186320986
Fold 4 IBS: 0.2313334849805865
Fold 5 IBS: 0.23607256585826236
[I 2024-04-14 22:31:52,764] Trial 63 finished with value: 0.20695150538877036 and parameters: {'subsample': 0.1426549697589047, 'dropout_rate': 0.9638280829839427, 'n_estimators': 188, 'learning_rate': 0.03969772372560614}. Best is trial 59 with value: 0.19105730646383373.
Fold 1 IBS: 0.16836107951350868
Fold 2 IBS: 0.2048338141551325
Fold 3 IBS: 0.16796262405852924
Fold 4 IBS: 0.19189449470941825
Fold 5 IBS: 0.21802767161924483
[I 2024-04-14 22:31:53,514] Trial 64 finished with value: 0.1902159368111667 and parameters: {'subsample': 0.106249473229961, 'dropout_rate': 0.9681316166382135, 'n_estimators': 131, 'learning_rate': 0.030226818337871844}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.1573696139909046
Fold 2 IBS: 0.21658100256379523
Fold 3 IBS: 0.1669193410955854
Fold 4 IBS: 0.20278984815041393
Fold 5 IBS: 0.22763346152543187
[I 2024-04-14 22:31:54,403] Trial 65 finished with value: 0.1942586534652262 and parameters: {'subsample': 0.1144681666605449, 'dropout_rate': 0.963417150597045, 'n_estimators': 165, 'learning_rate': 0.03499600145878021}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.1607864851475262
Fold 2 IBS: 0.2210080840578067
Fold 3 IBS: 0.1672886367162655
Fold 4 IBS: 0.2058457363775423
Fold 5 IBS: 0.22291522523477608
[I 2024-04-14 22:31:55,298] Trial 66 finished with value: 0.1955688335067834 and parameters: {'subsample': 0.17064612247272437, 'dropout_rate': 0.9642741963211559, 'n_estimators': 167, 'learning_rate': 0.031330157632667756}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.15589374989121602
Fold 2 IBS: 0.2398772408994035
Fold 3 IBS: 0.16654537260781332
Fold 4 IBS: 0.22441081675091715
Fold 5 IBS: 0.2304699550245595
[I 2024-04-14 22:31:57,125] Trial 67 finished with value: 0.2034394270347819 and parameters: {'subsample': 0.16784124502480896, 'dropout_rate': 0.9713467590653315, 'n_estimators': 217, 'learning_rate': 0.03044244925114121}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.15847724935942206
Fold 2 IBS: 0.213715494992415
Fold 3 IBS: 0.16839554202533402
Fold 4 IBS: 0.20155333432021763
Fold 5 IBS: 0.22399284502071562
[I 2024-04-14 22:31:58,174] Trial 68 finished with value: 0.19322689314362085 and parameters: {'subsample': 0.13054539900322654, 'dropout_rate': 0.9598884753479205, 'n_estimators': 173, 'learning_rate': 0.0300620877911956}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.17954496727861366
Fold 2 IBS: 0.20013335262558954
Fold 3 IBS: 0.1771322799417373
Fold 4 IBS: 0.19991988414452683
Fold 5 IBS: 0.21351873958129258
[I 2024-04-14 22:31:59,111] Trial 69 finished with value: 0.194049844714352 and parameters: {'subsample': 0.12193944370235084, 'dropout_rate': 0.4356182142942594, 'n_estimators': 128, 'learning_rate': 0.019042871107947605}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.16948456698908557
Fold 2 IBS: 0.21179762484308082
Fold 3 IBS: 0.1677662965087696
Fold 4 IBS: 0.20288658707974364
Fold 5 IBS: 0.21599589897958885
[I 2024-04-14 22:32:01,003] Trial 70 finished with value: 0.19358619488005369 and parameters: {'subsample': 0.21005954690725723, 'dropout_rate': 0.4017496839974698, 'n_estimators': 217, 'learning_rate': 0.018781164544059318}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.1755340968987496
Fold 2 IBS: 0.20039433624372796
Fold 3 IBS: 0.1746955455578228
Fold 4 IBS: 0.19769443545676826
Fold 5 IBS: 0.2137725087983668
[I 2024-04-14 22:32:02,228] Trial 71 finished with value: 0.19241818459108712 and parameters: {'subsample': 0.12150207835118919, 'dropout_rate': 0.404743294331685, 'n_estimators': 160, 'learning_rate': 0.017842586853197118}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.16768917330206082
Fold 2 IBS: 0.21374339292258804
Fold 3 IBS: 0.16712109993758623
Fold 4 IBS: 0.20311081266749148
Fold 5 IBS: 0.2175590615372682
[I 2024-04-14 22:32:04,046] Trial 72 finished with value: 0.19384470807339893 and parameters: {'subsample': 0.19835526151825625, 'dropout_rate': 0.41975221358020426, 'n_estimators': 214, 'learning_rate': 0.020368145855491026}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.16653478714643596
Fold 2 IBS: 0.20923660149038684
Fold 3 IBS: 0.16900305660948403
Fold 4 IBS: 0.19780712502938338
Fold 5 IBS: 0.2170541345014937
[I 2024-04-14 22:32:05,730] Trial 73 finished with value: 0.19192714095543678 and parameters: {'subsample': 0.18597033136891927, 'dropout_rate': 0.34059920799501153, 'n_estimators': 212, 'learning_rate': 0.019033409402898407}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.192972438508827
Fold 2 IBS: 0.20489540686699761
Fold 3 IBS: 0.18523214050134193
Fold 4 IBS: 0.20894804047542004
Fold 5 IBS: 0.21329684038572339
[I 2024-04-14 22:32:06,758] Trial 74 finished with value: 0.201068973347662 and parameters: {'subsample': 0.22190512901259024, 'dropout_rate': 0.34578330340113894, 'n_estimators': 145, 'learning_rate': 0.010330354467404046}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.16532848192208155
Fold 2 IBS: 0.20701415878454602
Fold 3 IBS: 0.169129851599109
Fold 4 IBS: 0.19620847271377465
Fold 5 IBS: 0.21759689469052418
[I 2024-04-14 22:32:08,391] Trial 75 finished with value: 0.19105557194200706 and parameters: {'subsample': 0.13935769447624002, 'dropout_rate': 0.34163132072065266, 'n_estimators': 225, 'learning_rate': 0.017783172194203254}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.1770274136026659
Fold 2 IBS: 0.20226661180784963

Fold 3 IBS: 0.17533541667082073
Fold 4 IBS: 0.199151824633538
Fold 5 IBS: 0.2141302634338856
[I 2024-04-14 22:32:10,181] Trial 76 finished with value: 0.19358230602975196 and parameters: {'subsample': 0.13636686599390602, 'dropout_rate': 0.34829268282242476, 'n_estimators': 184, 'learning_rate': 0.015139043821359926}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.18026729871669211
Fold 2 IBS: 0.20071841061297166
Fold 3 IBS: 0.1764058988174647
Fold 4 IBS: 0.19883957499746607
Fold 5 IBS: 0.21357839204133217
[I 2024-04-14 22:32:12,940] Trial 77 finished with value: 0.19396191503718535 and parameters: {'subsample': 0.10015980621116063, 'dropout_rate': 0.2813897195542503, 'n_estimators': 233, 'learning_rate': 0.01050391580021415}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.18544854409101208
Fold 2 IBS: 0.20152802428953787
Fold 3 IBS: 0.17908634512845192
Fold 4 IBS: 0.20415170947503194
Fold 5 IBS: 0.21252533091673242
[I 2024-04-14 22:32:17,929] Trial 78 finished with value: 0.19654799078015323 and parameters: {'subsample': 0.18859893789423166, 'dropout_rate': 0.21771512626556933, 'n_estimators': 274, 'learning_rate': 0.007723103513253874}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.18275611003849945
Fold 2 IBS: 0.2025429216694758
Fold 3 IBS: 0.17766183485455728
Fold 4 IBS: 0.20182306722144183
Fold 5 IBS: 0.21275469760679688
[I 2024-04-14 22:32:21,746] Trial 79 finished with value: 0.19550772627815424 and parameters: {'subsample': 0.15431805687340738, 'dropout_rate': 0.32430993530183283, 'n_estimators': 139, 'learning_rate': 0.01723756742723814}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.16030204740092704
Fold 2 IBS: 0.2807606389241063
Fold 3 IBS: 0.17154875694724958
Fold 4 IBS: 0.2707285853504448
Fold 5 IBS: 0.2456625614250786
[I 2024-04-14 22:36:00,537] Trial 80 finished with value: 0.2258005180095613 and parameters: {'subsample': 0.18570770869083006, 'dropout_rate': 0.5750641085558709, 'n_estimators': 312, 'learning_rate': 0.02905506183474561}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.17734558498559858
Fold 2 IBS: 0.2010691923653617
Fold 3 IBS: 0.1755379538650146
Fold 4 IBS: 0.19902670495002875
Fold 5 IBS: 0.21342098166645496
[I 2024-04-14 22:36:01,978] Trial 81 finished with value: 0.1932800835664917 and parameters: {'subsample': 0.13419741958833545, 'dropout_rate': 0.363815904550201, 'n_estimators': 187, 'learning_rate': 0.014612491747122166}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.16126511638102448
Fold 2 IBS: 0.20793764016198746
Fold 3 IBS: 0.1687833161918799
Fold 4 IBS: 0.19625559094672473
Fold 5 IBS: 0.22066894110762483
[I 2024-04-14 22:36:03,506] Trial 82 finished with value: 0.19098212095784828 and parameters: {'subsample': 0.12749421130877828, 'dropout_rate': 0.3030682971243237, 'n_estimators': 200, 'learning_rate': 0.022999558442137975}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.16000111747768347
Fold 2 IBS: 0.20742102529324782
Fold 3 IBS: 0.16932365314069026
Fold 4 IBS: 0.19406391982942828
Fold 5 IBS: 0.2208475848172689
[I 2024-04-14 22:36:04,485] Trial 83 finished with value: 0.19033146011166374 and parameters: {'subsample': 0.12299732882636906, 'dropout_rate': 0.30391105025548604, 'n_estimators': 196, 'learning_rate': 0.024073405973415507}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.1726231119730025
Fold 2 IBS: 0.20049213048483003
Fold 3 IBS: 0.17386770708947033
Fold 4 IBS: 0.19672651623630838
Fold 5 IBS: 0.21446455551583918
[I 2024-04-14 22:36:05,868] Trial 84 finished with value: 0.19163480425989007 and parameters: {'subsample': 0.11977767956854013, 'dropout_rate': 0.30901503082110426, 'n_estimators': 237, 'learning_rate': 0.012932520370436334}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.1967735415428373
Fold 2 IBS: 0.20820540083242867
Fold 3 IBS: 0.18845177217554876
Fold 4 IBS: 0.21040410614313654
Fold 5 IBS: 0.21402282818808288
[I 2024-04-14 22:36:06,881] Trial 85 finished with value: 0.20357152977640683 and parameters: {'subsample': 0.10305168886482788, 'dropout_rate': 0.288654155635312, 'n_estimators': 203, 'learning_rate': 0.0059623290732174}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.15952838094056798
Fold 2 IBS: 0.2223283925131949
Fold 3 IBS: 0.16422728539782225
Fold 4 IBS: 0.20711830921858443
Fold 5 IBS: 0.22404975230770474
[I 2024-04-14 22:36:08,128] Trial 86 finished with value: 0.19545042407557486 and parameters: {'subsample': 0.15890286291592118, 'dropout_rate': 0.2108684762752061, 'n_estimators': 236, 'learning_rate': 0.023768909202473255}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.1625667084316242
Fold 2 IBS: 0.24098465058199242
Fold 3 IBS: 0.16415939911794075
Fold 4 IBS: 0.22578884018029105
Fold 5 IBS: 0.22811323749830875
[I 2024-04-14 22:36:09,397] Trial 87 finished with value: 0.20432256716203145 and parameters: {'subsample': 0.21807170285073196, 'dropout_rate': 0.31620016519121263, 'n_estimators': 251, 'learning_rate': 0.024942567173816082}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.18389417579867634
Fold 2 IBS: 0.20165531347636226
Fold 3 IBS: 0.18008890881068318
Fold 4 IBS: 0.20259203963444586
Fold 5 IBS: 0.21293052817121202
[I 2024-04-14 22:36:10,075] Trial 88 finished with value: 0.19623219317827595 and parameters: {'subsample': 0.1221887120201574, 'dropout_rate': 0.37529360435703, 'n_estimators': 159, 'learning_rate': 0.01319541685226847}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.16366069464809394
Fold 2 IBS: 0.21183472990774582
Fold 3 IBS: 0.16761695039975635
Fold 4 IBS: 0.19939570901024828
Fold 5 IBS: 0.21869188852080415
[I 2024-04-14 22:36:11,109] Trial 89 finished with value: 0.1922399944973297 and parameters: {'subsample': 0.1762820880034347, 'dropout_rate': 0.47098525495206545, 'n_estimators': 201, 'learning_rate': 0.02184530906874206}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.1716281051039538
Fold 2 IBS: 0.22199215860528365
Fold 3 IBS: 0.165481102615718
Fold 4 IBS: 0.21249740968693015
Fold 5 IBS: 0.21748195562561318
[I 2024-04-14 22:36:12,291] Trial 90 finished with value: 0.19781614632749975 and parameters: {'subsample': 0.26859331465546027, 'dropout_rate': 0.47107793466358483, 'n_estimators': 251, 'learning_rate': 0.017891285187923354}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.16570341323102877
Fold 2 IBS: 0.21761441257892505
Fold 3 IBS: 0.1664688478260182
Fold 4 IBS: 0.20687636440305984
Fold 5 IBS: 0.22088813576073069
[I 2024-04-14 22:36:13,343] Trial 91 finished with value: 0.1955102347599525 and parameters: {'subsample': 0.19128280275364642, 'dropout_rate': 0.5195895386469269, 'n_estimators': 226, 'learning_rate': 0.021475030026110894}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.16446136464918665
Fold 2 IBS: 0.23494077709141967
Fold 3 IBS: 0.16456639736313086
Fold 4 IBS: 0.22144060281419167
Fold 5 IBS: 0.22444572856761727
[I 2024-04-14 22:36:14,220] Trial 92 finished with value: 0.20197097409710923 and parameters: {'subsample': 0.23478374095430143, 'dropout_rate': 0.3183531712972294, 'n_estimators': 202, 'learning_rate': 0.028063718655758272}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.20538334536250388
Fold 2 IBS: 0.21441651426353076
Fold 3 IBS: 0.19659802232447027
Fold 4 IBS: 0.21834283950152306
Fold 5 IBS: 0.21564453826827162
[I 2024-04-14 22:36:15,031] Trial 93 finished with value: 0.21007705194405993 and parameters: {'subsample': 0.15763834357075507, 'dropout_rate': 0.24055144901119302, 'n_estimators': 179, 'learning_rate': 0.0030765931463296557}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.15794046444960894
Fold 2 IBS: 0.20987991773256162
Fold 3 IBS: 0.1687579379565712
Fold 4 IBS: 0.19595643731952928
Fold 5 IBS: 0.22282302220804331
[I 2024-04-14 22:36:15,890] Trial 94 finished with value: 0.19107155593326286 and parameters: {'subsample': 0.11922497325858486, 'dropout_rate': 0.29242800071492053, 'n_estimators': 199, 'learning_rate': 0.025656679548214177}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.1597197071500515

Fold 2 IBS: 0.21889413864524473
Fold 3 IBS: 0.1662261526779113
Fold 4 IBS: 0.20442135797401353
Fold 5 IBS: 0.22263086768420076
[I 2024-04-14 22:36:16,779] Trial 95 finished with value: 0.19437844482628436 and parameters: {'subsample': 0.17622533543010202, 'dropout_rate': 0.28294415276733026, 'n_estimators': 203, 'learning_rate': 0.025913269794610564}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.15207446196056826
Fold 2 IBS: 0.2109806041455053
Fold 3 IBS: 0.16768998617571493
Fold 4 IBS: 0.20401212700679955
Fold 5 IBS: 0.22643513205900653
[I 2024-04-14 22:36:18,139] Trial 96 finished with value: 0.19223846226951893 and parameters: {'subsample': 0.10119718770512731, 'dropout_rate': 0.19203824608920522, 'n_estimators': 258, 'learning_rate': 0.022376583667374196}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.14951781740699113
Fold 2 IBS: 0.21438676990941416
Fold 3 IBS: 0.16787377142612836
Fold 4 IBS: 0.206298769650207
Fold 5 IBS: 0.22782687152412864
[I 2024-04-14 22:36:19,526] Trial 97 finished with value: 0.19318079998337384 and parameters: {'subsample': 0.108365990566983, 'dropout_rate': 0.15584264631746048, 'n_estimators': 263, 'learning_rate': 0.02328047856789987}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.1626418159823062
Fold 2 IBS: 0.2382242521768894
Fold 3 IBS: 0.16381710593621363
Fold 4 IBS: 0.23343469478996873
Fold 5 IBS: 0.22867013034703715
[I 2024-04-14 22:36:23,494] Trial 98 finished with value: 0.20535759984648302 and parameters: {'subsample': 0.20022983572584738, 'dropout_rate': 0.1769400156060556, 'n_estimators': 296, 'learning_rate': 0.021541989117784145}. Best is trial 64 with value: 0.1902159368111667.
Fold 1 IBS: 0.16625310610088093
Fold 2 IBS: 0.21110678177799694
Fold 3 IBS: 0.16727220115619695
Fold 4 IBS: 0.19673688931314903
Fold 5 IBS: 0.21801243779434598
[I 2024-04-14 22:36:24,800] Trial 99 finished with value: 0.19187628322851397 and parameters: {'subsample': 0.15336625195275522, 'dropout_rate': 0.26691259962523883, 'n_estimators': 260, 'learning_rate': 0.016562409556053825}. Best is trial 64 with value: 0.1902159368111667.


* Best trial for IBS:
 FrozenTrial(number=64, state=TrialState.COMPLETE, values=[0.1902159368111667], datetime_start=datetime.datetime(2024, 4, 14, 22, 31, 52, 777028), datetime_complete=datetime.datetime(2024, 4, 14, 22, 31, 53, 513848), params={'subsample': 0.106249473229961, 'dropout_rate': 0.9681316166382135, 'n_estimators': 131, 'learning_rate': 0.030226818337871844}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=64, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.106249473229961, 'dropout_rate': 0.9681316166382135, 'n_estimators': 131, 'learning_rate': 0.030226818337871844}


* Best Score for IBS:
 0.1902159368111667

In [68]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [69]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.749
train_ibs:  0.19

#### Test

In [70]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [71]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.1304931000922671,
                                              learning_rate=0.00524351186486742,
                                              n_estimators=359,
                                              random_state=123,
                                              subsample=0.13799461538888846)

C-index score: 0.596

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.9681316166382135,
                                              learning_rate=0.030226818337871844,
                                              n_estimators=131,
                                              random_state=123,
                                              subsample=0.106249473229961)

IBS: 0.204

In [72]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [73]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.770   1.0
ExtraSurvivalTrees               0.761   2.0
ComponentwiseGradientBoosting    0.749   3.0
CoxPH                            0.743   5.0
CoxLasso                         0.743   5.0
CoxElastic                       0.743   5.0
GradientBoosting                 0.741   7.0
CoxRidge                         0.718   8.0

In [74]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.181   1.0
CoxLasso                       0.183   3.0
CoxElastic                     0.183   3.0
ExtraSurvivalTrees             0.183   3.0
CoxPH                          0.184   5.0
ComponentwiseGradientBoosting  0.190   6.0
GradientBoosting               0.215   7.0
CoxRidge                       0.217   8.0

In [75]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
CoxRidge                         0.624   1.0
ExtraSurvivalTrees               0.608   2.0
ComponentwiseGradientBoosting    0.596   3.0
GradientBoosting                 0.590   4.0
CoxPH                            0.583   6.0
CoxLasso                         0.583   6.0
CoxElastic                       0.583   6.0
Randomsurvivalforest             0.579   8.0

In [76]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ComponentwiseGradientBoosting  0.204   1.0
ExtraSurvivalTrees             0.213   2.0
GradientBoosting               0.220   3.0
CoxRidge                       0.221   4.0
Randomsurvivalforest           0.226   5.0
CoxLasso                       0.261   6.5
CoxElastic                     0.261   6.5
CoxPH                          0.266   8.0

In [77]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/os/robust/plsr/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_os_robust_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [78]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-14