In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
 
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import MinMaxScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

## Test dataset: MAASTRO

In [6]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [7]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [8]:
# need to choose patient_id from MAASTRO_D1 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [9]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]

In [10]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [11]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, DFS, DFS_event]
Index: []

In [12]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [13]:
# Set lower, upper time point and times for IBS calculation later 

# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 14)
y_train:  (139,)

(99, 16)

# Feature Selection: PLSR

In [14]:
selected_features = ["hpv_related",
"MTV",
"TLG"]

# Selecting features in the DataFrame
X_plsr = X[selected_features]
X_new = X_plsr.copy()

In [15]:
X_MAASTRO_plsr = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_plsr.copy()

# Standardization

In [16]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = MinMaxScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [17]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [18]:
X_new

     hpv_related     MTV         TLG
0            0.0   7.934   86.228420
1            0.0   1.656    7.040100
2            0.0  14.502   83.569669
3            0.0   2.440    5.567091
4            0.0   3.668   16.150550
..           ...     ...         ...
134          1.0   3.650   26.280140
135          1.0  18.967  101.754834
136          1.0   6.370   66.273201
137          1.0  12.443   71.832443
138          1.0   7.983   78.647696

[139 rows x 3 columns]

In [19]:
X_new_std

     hpv_related       MTV       TLG
0            0.0  0.074159  0.044798
1            0.0  0.008512  0.001900
2            0.0  0.142839  0.043358
3            0.0  0.016710  0.001102
4            0.0  0.029551  0.006835
..           ...       ...       ...
134          1.0  0.029363  0.012323
135          1.0  0.189529  0.053209
136          1.0  0.057805  0.033988
137          1.0  0.121309  0.037000
138          1.0  0.074672  0.040692

[139 rows x 3 columns]

In [20]:
MAASTRO_new

    hpv_related     MTV         TLG
0             1  22.841  263.611623
1             0   5.660   36.980700
2             0   7.791   74.636342
3             0   7.908   46.791979
4             1  15.237  107.637514
..          ...     ...         ...
94            0   6.110  144.490782
95            0   7.182   69.214868
96            1  16.483  102.594274
97            1   9.981  103.229492
98            0   3.495   28.553212

[99 rows x 3 columns]

In [21]:
MAASTRO_new_std

    hpv_related       MTV       TLG
0             1  0.230038  0.140892
1             0  0.050381  0.018119
2             0  0.072664  0.038519
3             0  0.073887  0.023434
4             1  0.150525  0.056396
..          ...       ...       ...
94            0  0.055086  0.076361
95            0  0.066296  0.035582
96            1  0.163554  0.053664
97            1  0.095564  0.054008
98            0  0.027742  0.013554

[99 rows x 3 columns]

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [22]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-21 15:25:05,071] A new study created in memory with name: no-name-cdde94f2-c1d2-4a52-8808-4c6b18341b57

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5976408912188729
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5796089385474861
[I 2024-04-21 15:25:12,039] Trial 0 finished with value: 0.6070507562635831 and parameters: {}. Best is trial 0 with value: 0.6070507562635831.

[I 2024-04-21 15:25:12,073] A new study created in memory with name: no-name-b9b435e0-b925-49a1-badd-b281e810a3aa

* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6070507562635831], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 5, 186900), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 12, 28054), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6070507562635831

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21982586172503096
Fold 2 IBS: 0.24550424387449332
Fold 3 IBS: 0.26385879041290594
[I 2024-04-21 15:25:12,453] Trial 0 finished with value: 0.24306296533747673 and parameters: {}. Best is trial 0 with value: 0.24306296533747673.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.24306296533747673], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 12, 116547), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 12, 453001), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.24306296533747673

In [23]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [24]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.607
train_ibs:  0.243

#### Test

In [25]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [26]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.59
IBS score: 0.234

In [27]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [28]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [29]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-21 15:25:12,986] A new study created in memory with name: no-name-b8de0ba0-66cb-45c8-9b10-fdd02692115b

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:13,221] Trial 0 finished with value: 0.6362006994356976 and parameters: {}. Best is trial 0 with value: 0.6362006994356976.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6362006994356976], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 13, 19470), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 13, 220918), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6362006994356976

[I 2024-04-21 15:25:13,245] A new study created in memory with name: no-name-5b323f9e-c4f8-471e-9f95-c9bef24e894f

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2482021655785998
Fold 2 IBS: 0.23351868144825097
Fold 3 IBS: 0.23466234443937334
[I 2024-04-21 15:25:13,550] Trial 0 finished with value: 0.23879439715540807 and parameters: {}. Best is trial 0 with value: 0.23879439715540807.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23879439715540807], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 13, 431622), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 13, 550276), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23879439715540807

In [30]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [31]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.636
train_ibs:  0.239

#### Test

In [32]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [33]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.598

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.224

In [34]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [35]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-21 15:25:13,656] A new study created in memory with name: no-name-32ad5aba-1462-47f3-9efd-c0b91b99fc67

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6422764227642277

[I 2024-04-21 15:25:14,077] A new study created in memory with name: no-name-d3b93549-e3b6-406a-8572-351a6a13a12c

Fold 3 C-index: 0.5837988826815642
[I 2024-04-21 15:25:14,070] Trial 0 finished with value: 0.6087791428812316 and parameters: {}. Best is trial 0 with value: 0.6087791428812316.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6087791428812316], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 13, 679103), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 14, 70519), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6087791428812316

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21898009161324816
Fold 2 IBS: 0.24562349467127004
Fold 3 IBS: 0.2629861328703854
[I 2024-04-21 15:25:14,394] Trial 0 finished with value: 0.24252990638496788 and parameters: {}. Best is trial 0 with value: 0.24252990638496788.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.24252990638496788], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 14, 164784), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 14, 394611), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.24252990638496788

In [36]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [37]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.609
train_ibs:  0.243

#### Test

In [38]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [39]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.593

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.232

In [40]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [41]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-21 15:25:14,895] A new study created in memory with name: no-name-fdd42267-bebe-4d90-a863-4e5e9a35f5e2

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:15,393] Trial 0 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6088555989530549.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:15,917] Trial 1 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.6088555989530549.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:16,152] Trial 2 finished with value: 0.6289923114933647 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.6289923114933647.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:16,867] Trial 3 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.6289923114933647.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:17,149] Trial 4 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.6289923114933647.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:17,474] Trial 5 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.6289923114933647.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6422764227642277
Fold 3 C-index: 0.5837988826815642
[I 2024-04-21 15:25:17,737] Trial 6 finished with value: 0.6087791428812316 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.6289923114933647.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:18,145] Trial 7 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.6289923114933647.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:18,502] Trial 8 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.6289923114933647.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:18,815] Trial 9 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.6289923114933647.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:18,897] Trial 10 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:19,075] Trial 11 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:19,165] Trial 12 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.025939717088620355}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:19,317] Trial 13 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.0025191055037027087}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:19,463] Trial 14 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.15900067485379482}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:19,598] Trial 15 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.1213682619339952}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:20,020] Trial 16 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.30518868850921266}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:20,140] Trial 17 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.11162673131638613}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:20,310] Trial 18 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.013344377881091008}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6422764227642277
Fold 3 C-index: 0.5837988826815642
[I 2024-04-21 15:25:20,623] Trial 19 finished with value: 0.6087791428812316 and parameters: {'l1_ratio': 0.9929341434741732}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:20,787] Trial 20 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.1806311047916896}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:20,881] Trial 21 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.06565731081729745}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:20,962] Trial 22 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.008429638096868723}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:21,039] Trial 23 finished with value: 0.6289923114933647 and parameters: {'l1_ratio': 0.24389588645587149}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:21,128] Trial 24 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.1025708411093254}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:21,677] Trial 25 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.3494311223571795}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:21,732] Trial 26 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.0598106560546561}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:21,835] Trial 27 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.19910623958858176}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:22,008] Trial 28 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.07142032899162687}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5837988826815642
[I 2024-04-21 15:25:22,343] Trial 29 finished with value: 0.6093211483012858 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464

Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:22,443] Trial 30 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.15231655278527506}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:22,586] Trial 31 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.0001723511450560239}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:22,731] Trial 32 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.0473931206575884}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:22,965] Trial 33 finished with value: 0.6289923114933647 and parameters: {'l1_ratio': 0.2534799377437118}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:23,102] Trial 34 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.12430185157472462}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:23,216] Trial 35 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.0009479795841882948}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:23,766] Trial 36 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.5793735611392209}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:23,943] Trial 37 finished with value: 0.6289923114933647 and parameters: {'l1_ratio': 0.220551710761538}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:24,574] Trial 38 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.32410119150750666}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:24,710] Trial 39 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.07488457934228292}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:24,876] Trial 40 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.16556951896887107}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:25,016] Trial 41 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.15008650546009802}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:25,201] Trial 42 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.04366601513381256}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:25,417] Trial 43 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.09720582697625535}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:25,606] Trial 44 finished with value: 0.6289923114933647 and parameters: {'l1_ratio': 0.2536082593840988}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:25,761] Trial 45 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.13894954709696175}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:26,202] Trial 46 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.4747378721140501}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:26,520] Trial 47 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.618829628364638}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:26,949] Trial 48 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.7991933234425521}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:27,090] Trial 49 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.03508195559073847}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:27,443] Trial 50 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.41653985858071785}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:27,693] Trial 51 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.09816171051292913}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:27,947] Trial 52 finished with value: 0.6289923114933647 and parameters: {'l1_ratio': 0.20020629946656002}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:28,031] Trial 53 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.1091323067315102}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:28,186] Trial 54 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.03798782823940462}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:28,273] Trial 55 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.18281945819705311}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:28,629] Trial 56 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.2895661505336109}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:28,739] Trial 57 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.07840444337261462}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:28,878] Trial 58 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.027673983348324674}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:29,153] Trial 59 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.1264665057616935}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031

Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:29,437] Trial 60 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.3710951445084463}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:29,513] Trial 61 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.07721905510381082}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:29,660] Trial 62 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.11884515996214214}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:29,744] Trial 63 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.00011148973239315241}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:29,876] Trial 64 finished with value: 0.6289923114933647 and parameters: {'l1_ratio': 0.21634984134813867}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:29,916] Trial 65 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.17541393828845275}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:29,988] Trial 66 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.037319852426914844}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:30,068] Trial 67 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.06434997351422382}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:30,205] Trial 68 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.13921996265017877}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:30,284] Trial 69 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.09746923422041515}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:30,639] Trial 70 finished with value: 0.629805319623446 and parameters: {'l1_ratio': 0.26868177587060027}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:30,753] Trial 71 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.02057185869692991}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:30,834] Trial 72 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.05598844997575726}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:30,956] Trial 73 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.006561320677402893}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:31,059] Trial 74 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.06629870836595636}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:31,225] Trial 75 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.16176755222380412}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:31,383] Trial 76 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.0866692864610644}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:31,478] Trial 77 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.029464881346925948}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6422764227642277
Fold 3 C-index: 0.5837988826815642
[I 2024-04-21 15:25:31,792] Trial 78 finished with value: 0.6087791428812316 and parameters: {'l1_ratio': 0.9506480490309224}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:31,969] Trial 79 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.1268927577771748}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:32,041] Trial 80 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.057501284732385145}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:32,184] Trial 81 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.18209596703559636}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:32,272] Trial 82 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.10351586133705698}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:32,377] Trial 83 finished with value: 0.6289923114933647 and parameters: {'l1_ratio': 0.23222800408014205}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:32,434] Trial 84 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.15040297597782104}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:32,497] Trial 85 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.018881178379131947}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:32,621] Trial 86 finished with value: 0.6289923114933647 and parameters: {'l1_ratio': 0.2038955062031032}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:32,808] Trial 87 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.7154780543949217}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:32,949] Trial 88 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.044065867684715945}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464

Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:33,064] Trial 89 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.08336215710985845}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:33,502] Trial 90 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.3183868446462055}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:33,640] Trial 91 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.11362080640422634}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:34,059] Trial 92 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.0018586415353247909}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:34,211] Trial 93 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.04802041530154244}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:34,339] Trial 94 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.14175715025037502}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:34,486] Trial 95 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.08131817869791044}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6002621231979031
Fold 2 C-index: 0.6439024390243903
Fold 3 C-index: 0.5824022346368715
[I 2024-04-21 15:25:34,859] Trial 96 finished with value: 0.6088555989530549 and parameters: {'l1_ratio': 0.5383062255971662}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:34,968] Trial 97 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.022969122173270434}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464

[I 2024-04-21 15:25:35,245] A new study created in memory with name: no-name-e604abbd-b85e-49f8-94a0-e63add67e4c2

Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:35,095] Trial 98 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.1210885749971614}. Best is trial 10 with value: 0.6362006994356976.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.6414634146341464
Fold 3 C-index: 0.6452513966480447
[I 2024-04-21 15:25:35,225] Trial 99 finished with value: 0.6362006994356976 and parameters: {'l1_ratio': 0.06082079700852272}. Best is trial 10 with value: 0.6362006994356976.


* Best trial for C-index:
 FrozenTrial(number=10, state=TrialState.COMPLETE, values=[0.6362006994356976], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 18, 832485), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 18, 897384), params={'l1_ratio': 0.08382735104105443}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=10, value=None)


* Best Score for C-index:
 0.6362006994356976

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21891659231556765
Fold 2 IBS: 0.2455924070393307
Fold 3 IBS: 0.26301515558906174
[I 2024-04-21 15:25:35,781] Trial 0 finished with value: 0.2425080516479867 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.2425080516479867.
Fold 1 IBS: 0.21889054291177298
Fold 2 IBS: 0.2455635247663104
Fold 3 IBS: 0.26304811968040404
[I 2024-04-21 15:25:36,268] Trial 1 finished with value: 0.24250072911949583 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.24250072911949583.
Fold 1 IBS: 0.21895472678213304
Fold 2 IBS: 0.23221962165887086
Fold 3 IBS: 0.22942631702566313
[I 2024-04-21 15:25:36,687] Trial 2 finished with value: 0.226866888488889 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.226866888488889.
Fold 1 IBS: 0.21891679087351235
Fold 2 IBS: 0.24558427223442533
Fold 3 IBS: 0.2630251207037027
[I 2024-04-21 15:25:37,077] Trial 3 finished with value: 0.24250872793721348 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.226866888488889.
Fold 1 IBS: 0.21897255021725548
Fold 2 IBS: 0.24559947821010486
Fold 3 IBS: 0.263046006984661
[I 2024-04-21 15:25:37,474] Trial 4 finished with value: 0.24253934513734046 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.226866888488889.
Fold 1 IBS: 0.2189490144313865
Fold 2 IBS: 0.24557220080819356
Fold 3 IBS: 0.26301290513096265
[I 2024-04-21 15:25:37,996] Trial 5 finished with value: 0.2425113734568476 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.226866888488889.
Fold 1 IBS: 0.21898523352737695
Fold 2 IBS: 0.24562505925770464
Fold 3 IBS: 0.2630440669039647
[I 2024-04-21 15:25:38,432] Trial 6 finished with value: 0.2425514532296821 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.226866888488889.
Fold 1 IBS: 0.21895849050491337
Fold 2 IBS: 0.24559308162773968
Fold 3 IBS: 0.26299876467845595
[I 2024-04-21 15:25:38,793] Trial 7 finished with value: 0.24251677893703635 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.226866888488889.
Fold 1 IBS: 0.21895934390684613
Fold 2 IBS: 0.24557776011701152
Fold 3 IBS: 0.26305209753929243
[I 2024-04-21 15:25:39,265] Trial 8 finished with value: 0.24252973385438334 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.226866888488889.
Fold 1 IBS: 0.2189330898868572
Fold 2 IBS: 0.24557015167285284
Fold 3 IBS: 0.26302115315894214
[I 2024-04-21 15:25:39,701] Trial 9 finished with value: 0.24250813157288406 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.226866888488889.
Fold 1 IBS: 0.245825117520884
Fold 2 IBS: 0.23291265557090599
Fold 3 IBS: 0.23247784834171215
[I 2024-04-21 15:25:39,925] Trial 10 finished with value: 0.23707187381116737 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.226866888488889.
Fold 1 IBS: 0.24783528462962082
Fold 2 IBS: 0.23341966084859592
Fold 3 IBS: 0.23432142953338797
[I 2024-04-21 15:25:40,045] Trial 11 finished with value: 0.23852545833720154 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 2 with value: 0.226866888488889.
Fold 1 IBS: 0.24582743258131212
Fold 2 IBS: 0.2329132018971575
Fold 3 IBS: 0.23247994834306654
[I 2024-04-21 15:25:40,234] Trial 12 finished with value: 0.2370735276071787 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 2 with value: 0.226866888488889.
Fold 1 IBS: 0.24322012872378054
Fold 2 IBS: 0.2323626188745429
Fold 3 IBS: 0.23014740050790347
[I 2024-04-21 15:25:40,476] Trial 13 finished with value: 0.23524338270207565 and parameters: {'l1_ratio': 0.18977351772466045}. Best is trial 2 with value: 0.226866888488889.
Fold 1 IBS: 0.21894488299509893
Fold 2 IBS: 0.2321666749601908
Fold 3 IBS: 0.2291374640215852
[I 2024-04-21 15:25:40,761] Trial 14 finished with value: 0.22674967399229162 and parameters: {'l1_ratio': 0.24249236510312352}. Best is trial 14 with value: 0.22674967399229162.
Fold 1 IBS: 0.2189439373757576
Fold 2 IBS: 0.23222810196880844
Fold 3 IBS: 0.2294713172309668
[I 2024-04-21 15:25:40,908] Trial 15 finished with value: 0.22688111885851095 and parameters: {'l1_ratio': 0.2245403429070307}. Best is trial 14 with value: 0.22674967399229162.
Fold 1 IBS: 0.21890909377193352
Fold 2 IBS: 0.24556364038862155
Fold 3 IBS: 0.26305301925270935
[I 2024-04-21 15:25:41,250] Trial 16 finished with value: 0.24250858447108814 and parameters: {'l1_ratio': 0.31408489302885545}. Best is trial 14 with value: 0.22674967399229162.
Fold 1 IBS: 0.24419829597143936
Fold 2 IBS: 0.23255310298798373
Fold 3 IBS: 0.23101496958022502
[I 2024-04-21 15:25:41,353] Trial 17 finished with value: 0.23592212284654937 and parameters: {'l1_ratio': 0.14799833455264066}. Best is trial 14 with value: 0.22674967399229162.
Fold 1 IBS: 0.21891688064831638
Fold 2 IBS: 0.24556556008344424
Fold 3 IBS: 0.2630437690629398
[I 2024-04-21 15:25:41,593] Trial 18 finished with value: 0.24250873659823347 and parameters: {'l1_ratio': 0.33883882709417557}. Best is trial 14 with value: 0.22674967399229162.
Fold 1 IBS: 0.21891309221009225
Fold 2 IBS: 0.24558515556359342
Fold 3 IBS: 0.26301888350105285
[I 2024-04-21 15:25:41,778] Trial 19 finished with value: 0.24250571042491284 and parameters: {'l1_ratio': 0.5476641842948985}. Best is trial 14 with value: 0.22674967399229162.
Fold 1 IBS: 0.21890096439236395
Fold 2 IBS: 0.2322045751118648
Fold 3 IBS: 0.22934565334326143
[I 2024-04-21 15:25:42,045] Trial 20 finished with value: 0.2268170642824967 and parameters: {'l1_ratio': 0.2312342395344777}. Best is trial 14 with value: 0.22674967399229162.
Fold 1 IBS: 0.2189196381951186
Fold 2 IBS: 0.2321857592214092
Fold 3 IBS: 0.22924322979403272
[I 2024-04-21 15:25:42,303] Trial 21 finished with value: 0.22678287573685352 and parameters: {'l1_ratio': 0.23674640483253295}. Best is trial 14 with value: 0.22674967399229162.
Fold 1 IBS: 0.24477108744218268
Fold 2 IBS: 0.23267393967734226
Fold 3 IBS: 0.23152714645186104
[I 2024-04-21 15:25:42,490] Trial 22 finished with value: 0.23632405785712865 and parameters: {'l1_ratio': 0.12469232350040972}. Best is trial 14 with value: 0.22674967399229162.
Fold 1 IBS: 0.2481306169043636
Fold 2 IBS: 0.23349922628650474
Fold 3 IBS: 0.23459575029809773
[I 2024-04-21 15:25:42,602] Trial 23 finished with value: 0.23874186449632204 and parameters: {'l1_ratio': 0.002373744016739676}. Best is trial 14 with value: 0.22674967399229162.
Fold 1 IBS: 0.21895148224095196
Fold 2 IBS: 0.23210310271688758
Fold 3 IBS: 0.228769481407295
[I 2024-04-21 15:25:42,714] Trial 24 finished with value: 0.22660802212171152 and parameters: {'l1_ratio': 0.2629237523336605}. Best is trial 24 with value: 0.22660802212171152.
Fold 1 IBS: 0.21892527246376875
Fold 2 IBS: 0.24557086091997762
Fold 3 IBS: 0.2630154839517302
[I 2024-04-21 15:25:43,102] Trial 25 finished with value: 0.24250387244515884 and parameters: {'l1_ratio': 0.38971525832834536}. Best is trial 24 with value: 0.22660802212171152.
Fold 1 IBS: 0.218909960263056
Fold 2 IBS: 0.2455617751568139
Fold 3 IBS: 0.2630624179481748
[I 2024-04-21 15:25:43,515] Trial 26 finished with value: 0.24251138445601492 and parameters: {'l1_ratio': 0.2911123931485357}. Best is trial 24 with value: 0.22660802212171152.
Fold 1 IBS: 0.21896585874889246
Fold 2 IBS: 0.24557716697306697
Fold 3 IBS: 0.26305638089393735
[I 2024-04-21 15:25:44,109] Trial 27 finished with value: 0.2425331355386323 and parameters: {'l1_ratio': 0.48333206147305935}. Best is trial 24 with value: 0.22660802212171152.
Fold 1 IBS: 0.21900554426011593
Fold 2 IBS: 0.24562794867933807
Fold 3 IBS: 0.2630278911715625
[I 2024-04-21 15:25:44,485] Trial 28 finished with value: 0.24255379470367214 and parameters: {'l1_ratio': 0.964957522585106}. Best is trial 24 with value: 0.22660802212171152.
Fold 1 IBS: 0.24406480041539425
Fold 2 IBS: 0.23252589743909294
Fold 3 IBS: 0.23089604500266644
[I 2024-04-21 15:25:44,705] Trial 29 finished with value: 0.23582891428571787 and parameters: {'l1_ratio': 0.15354880795613854}. Best is trial 24 with value: 0.22660802212171152.
Fold 1 IBS: 0.21890963454615525
Fold 2 IBS: 0.24559056453619868
Fold 3 IBS: 0.26300353443872865
[I 2024-04-21 15:25:45,050] Trial 30 finished with value: 0.2425012445070275 and parameters: {'l1_ratio': 0.6348147138790865}. Best is trial 24 with value: 0.22660802212171152.

Fold 1 IBS: 0.21894937247316976
Fold 2 IBS: 0.23216324724813026
Fold 3 IBS: 0.22911825601359082
[I 2024-04-21 15:25:45,389] Trial 31 finished with value: 0.2267436252449636 and parameters: {'l1_ratio': 0.24354183082267372}. Best is trial 24 with value: 0.22660802212171152.
Fold 1 IBS: 0.2189566427690494
Fold 2 IBS: 0.23209930485435273
Fold 3 IBS: 0.228746636487385
[I 2024-04-21 15:25:45,713] Trial 32 finished with value: 0.22660086137026236 and parameters: {'l1_ratio': 0.2642152854612092}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21891978310822555
Fold 2 IBS: 0.24556530074358474
Fold 3 IBS: 0.26304588207154045
[I 2024-04-21 15:25:46,102] Trial 33 finished with value: 0.24251032197445024 and parameters: {'l1_ratio': 0.33967020776393025}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.24589708567420382
Fold 2 IBS: 0.2329296825292241
Fold 3 IBS: 0.23254315558382643
[I 2024-04-21 15:25:46,254] Trial 34 finished with value: 0.2371233079290848 and parameters: {'l1_ratio': 0.08112681909214389}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21890868412928888
Fold 2 IBS: 0.24557882838131642
Fold 3 IBS: 0.26303602392632586
[I 2024-04-21 15:25:46,695] Trial 35 finished with value: 0.24250784547897705 and parameters: {'l1_ratio': 0.4341659024174019}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21888994231185213
Fold 2 IBS: 0.24556140618764627
Fold 3 IBS: 0.22871610228112088
[I 2024-04-21 15:25:47,052] Trial 36 finished with value: 0.23105581692687313 and parameters: {'l1_ratio': 0.26594584591028053}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21896190989676748
Fold 2 IBS: 0.2456116675546444
Fold 3 IBS: 0.26301354178921615
[I 2024-04-21 15:25:47,411] Trial 37 finished with value: 0.242529039746876 and parameters: {'l1_ratio': 0.8808567522730943}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21895754998614994
Fold 2 IBS: 0.24557058616582222
Fold 3 IBS: 0.2629980444536941
[I 2024-04-21 15:25:47,729] Trial 38 finished with value: 0.24250872686855543 and parameters: {'l1_ratio': 0.3508465542445811}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21895002640016462
Fold 2 IBS: 0.23210417246343334
Fold 3 IBS: 0.22877589695244058
[I 2024-04-21 15:25:47,842] Trial 39 finished with value: 0.22661003193867954 and parameters: {'l1_ratio': 0.2625615461404867}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.24333081215129593
Fold 2 IBS: 0.2323831160597395
Fold 3 IBS: 0.2302451273663712
[I 2024-04-21 15:25:47,988] Trial 40 finished with value: 0.2353196851924689 and parameters: {'l1_ratio': 0.18491433848820432}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21893797456626102
Fold 2 IBS: 0.24556458991173594
Fold 3 IBS: 0.2630273228694891
[I 2024-04-21 15:25:48,398] Trial 41 finished with value: 0.242509962449162 and parameters: {'l1_ratio': 0.27936373110641877}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.2432157326447752
Fold 2 IBS: 0.23236181054034483
Fold 3 IBS: 0.23014352133760274
[I 2024-04-21 15:25:48,608] Trial 42 finished with value: 0.23524035484090758 and parameters: {'l1_ratio': 0.18996723622963846}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21890887888738583
Fold 2 IBS: 0.24557080925507563
Fold 3 IBS: 0.2630035838513831
[I 2024-04-21 15:25:49,113] Trial 43 finished with value: 0.24249442399794818 and parameters: {'l1_ratio': 0.38464261521176535}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21891334899911483
Fold 2 IBS: 0.24557838634997198
Fold 3 IBS: 0.26303913325411415
[I 2024-04-21 15:25:49,543] Trial 44 finished with value: 0.24251028953440032 and parameters: {'l1_ratio': 0.435688560352882}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21891957039912485
Fold 2 IBS: 0.24556643312878587
Fold 3 IBS: 0.26301262700743466
[I 2024-04-21 15:25:49,898] Trial 45 finished with value: 0.2424995435117818 and parameters: {'l1_ratio': 0.27471603880544293}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.24533517280355624
Fold 2 IBS: 0.2327991620220987
Fold 3 IBS: 0.23203459593803638
[I 2024-04-21 15:25:50,100] Trial 46 finished with value: 0.23672297692123045 and parameters: {'l1_ratio': 0.10251039057202885}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21893280750883953
Fold 2 IBS: 0.23217584415630635
Fold 3 IBS: 0.2291885252128933
[I 2024-04-21 15:25:50,408] Trial 47 finished with value: 0.22676572562601308 and parameters: {'l1_ratio': 0.23971145636476637}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.24670877708646244
Fold 2 IBS: 0.23312773382118598
Fold 3 IBS: 0.2332832714624095
[I 2024-04-21 15:25:50,612] Trial 48 finished with value: 0.23770659412335263 and parameters: {'l1_ratio': 0.051408713626916375}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.24375129939983414
Fold 2 IBS: 0.23246348226527688
Fold 3 IBS: 0.23061741585006398
[I 2024-04-21 15:25:50,821] Trial 49 finished with value: 0.23561073250505835 and parameters: {'l1_ratio': 0.16676706255464557}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21890497415474824
Fold 2 IBS: 0.24556400820817817
Fold 3 IBS: 0.2630500135728724
[I 2024-04-21 15:25:51,297] Trial 50 finished with value: 0.2425063319785996 and parameters: {'l1_ratio': 0.31297686520002327}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21889883195807033
Fold 2 IBS: 0.23226776010896008
Fold 3 IBS: 0.22967764214420874
[I 2024-04-21 15:25:51,558] Trial 51 finished with value: 0.22694807807041306 and parameters: {'l1_ratio': 0.21371107202512796}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.2188974729319725
Fold 2 IBS: 0.23214703395118885
Fold 3 IBS: 0.22902648255614236
[I 2024-04-21 15:25:51,994] Trial 52 finished with value: 0.22669032981310122 and parameters: {'l1_ratio': 0.24858156861253838}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21893025057488688
Fold 2 IBS: 0.24556723969374808
Fold 3 IBS: 0.26303709755292115
[I 2024-04-21 15:25:52,392] Trial 53 finished with value: 0.24251152927385203 and parameters: {'l1_ratio': 0.3665102818801312}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21894833398230043
Fold 2 IBS: 0.23210541511282615
Fold 3 IBS: 0.22878333894602132
[I 2024-04-21 15:25:52,731] Trial 54 finished with value: 0.22661236268038265 and parameters: {'l1_ratio': 0.2621416607802236}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21889451149261874
Fold 2 IBS: 0.24556555747001052
Fold 3 IBS: 0.2630374621850909
[I 2024-04-21 15:25:53,092] Trial 55 finished with value: 0.24249917704924004 and parameters: {'l1_ratio': 0.30843162634864413}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.24471726213970674
Fold 2 IBS: 0.23266230766097026
Fold 3 IBS: 0.23147888471898853
[I 2024-04-21 15:25:53,250] Trial 56 finished with value: 0.23628615150655516 and parameters: {'l1_ratio': 0.1268480789564704}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21894502975239288
Fold 2 IBS: 0.24557841278686554
Fold 3 IBS: 0.2629925231719874
[I 2024-04-21 15:25:53,601] Trial 57 finished with value: 0.2425053219037486 and parameters: {'l1_ratio': 0.5325693164673471}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21892288463257814
Fold 2 IBS: 0.23230664653566638
Fold 3 IBS: 0.22987395014177436
[I 2024-04-21 15:25:53,872] Trial 58 finished with value: 0.22703449377000628 and parameters: {'l1_ratio': 0.20358877999989625}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21891266166453766
Fold 2 IBS: 0.24557457391604903
Fold 3 IBS: 0.26305847662832016
[I 2024-04-21 15:25:54,448] Trial 59 finished with value: 0.24251523740296896 and parameters: {'l1_ratio': 0.40918916980418296}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.2189223100267671
Fold 2 IBS: 0.24558504535442385
Fold 3 IBS: 0.26304223552974276
[I 2024-04-21 15:25:54,827] Trial 60 finished with value: 0.2425165303036446 and parameters: {'l1_ratio': 0.6097637962339882}. Best is trial 32 with value: 0.22660086137026236.

Fold 1 IBS: 0.21890808627959837
Fold 2 IBS: 0.23213940206823228
Fold 3 IBS: 0.22898273858596468
[I 2024-04-21 15:25:55,087] Trial 61 finished with value: 0.2266767423112651 and parameters: {'l1_ratio': 0.2509987424471442}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.2189327422200517
Fold 2 IBS: 0.2321168151680432
Fold 3 IBS: 0.2288510963012281
[I 2024-04-21 15:25:55,331] Trial 62 finished with value: 0.22663355122977435 and parameters: {'l1_ratio': 0.2583320804553656}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21891885714464457
Fold 2 IBS: 0.2455627740838971
Fold 3 IBS: 0.26306013872994455
[I 2024-04-21 15:25:55,659] Trial 63 finished with value: 0.24251392331949542 and parameters: {'l1_ratio': 0.31674043696628806}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.2188939137960474
Fold 2 IBS: 0.2455632189245959
Fold 3 IBS: 0.26305060285149834
[I 2024-04-21 15:25:56,075] Trial 64 finished with value: 0.2425025785240472 and parameters: {'l1_ratio': 0.2870503281463987}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.2189519729468331
Fold 2 IBS: 0.2321027419813593
Fold 3 IBS: 0.22876731609112294
[I 2024-04-21 15:25:56,313] Trial 65 finished with value: 0.2266073436731051 and parameters: {'l1_ratio': 0.2630460498391791}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21891120074079745
Fold 2 IBS: 0.2455723926103661
Fold 3 IBS: 0.26302037141829465
[I 2024-04-21 15:25:56,665] Trial 66 finished with value: 0.24250132158981938 and parameters: {'l1_ratio': 0.46426529471939754}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.244088207130504
Fold 2 IBS: 0.23253064079214175
Fold 3 IBS: 0.23091688483078673
[I 2024-04-21 15:25:56,833] Trial 67 finished with value: 0.23584524425114417 and parameters: {'l1_ratio': 0.1525722736469284}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21888707946973474
Fold 2 IBS: 0.2322765885466841
Fold 3 IBS: 0.22972270531650124
[I 2024-04-21 15:25:57,093] Trial 68 finished with value: 0.22696212444430666 and parameters: {'l1_ratio': 0.21137203538629853}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21894357789382746
Fold 2 IBS: 0.2455660544658262
Fold 3 IBS: 0.2630467717981642
[I 2024-04-21 15:25:57,281] Trial 69 finished with value: 0.2425188013859393 and parameters: {'l1_ratio': 0.37060481780267773}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21891959924774157
Fold 2 IBS: 0.24556531715186466
Fold 3 IBS: 0.26304574823437205
[I 2024-04-21 15:25:57,688] Trial 70 finished with value: 0.24251022154465943 and parameters: {'l1_ratio': 0.3396174296305137}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21892387239431504
Fold 2 IBS: 0.23212326070380618
Fold 3 IBS: 0.22888900633623246
[I 2024-04-21 15:25:57,975] Trial 71 finished with value: 0.22664537981145125 and parameters: {'l1_ratio': 0.25621107544333105}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21889840407278496
Fold 2 IBS: 0.2455606461643076
Fold 3 IBS: 0.2286807856031843
[I 2024-04-21 15:25:58,343] Trial 72 finished with value: 0.23104661194675893 and parameters: {'l1_ratio': 0.2679536442218774}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.24359626406945853
Fold 2 IBS: 0.23243339690751869
Fold 3 IBS: 0.23047996230001466
[I 2024-04-21 15:25:58,514] Trial 73 finished with value: 0.23550320775899727 and parameters: {'l1_ratio': 0.17340125429163866}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.218954750644896
Fold 2 IBS: 0.24556532491746483
Fold 3 IBS: 0.26302711183086436
[I 2024-04-21 15:25:58,984] Trial 74 finished with value: 0.24251572913107508 and parameters: {'l1_ratio': 0.30477980586445486}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21893755264930134
Fold 2 IBS: 0.23223308542661739
Fold 3 IBS: 0.229497611229389
[I 2024-04-21 15:25:59,252] Trial 75 finished with value: 0.2268894164351026 and parameters: {'l1_ratio': 0.2231492021641171}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21894180327607415
Fold 2 IBS: 0.2321102007495
Fold 3 IBS: 0.22881189501081337
[I 2024-04-21 15:25:59,494] Trial 76 finished with value: 0.22662129967879585 and parameters: {'l1_ratio': 0.26053319815147713}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21889185604968606
Fold 2 IBS: 0.2455669094952381
Fold 3 IBS: 0.26302060383484316
[I 2024-04-21 15:25:59,934] Trial 77 finished with value: 0.2424931231265891 and parameters: {'l1_ratio': 0.3299795421200875}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.24683271644249152
Fold 2 IBS: 0.23315891297268768
Fold 3 IBS: 0.2333968605160962
[I 2024-04-21 15:26:00,071] Trial 78 finished with value: 0.23779616331042516 and parameters: {'l1_ratio': 0.04698635860228753}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21894008734088294
Fold 2 IBS: 0.24560836518299253
Fold 3 IBS: 0.26301831886736393
[I 2024-04-21 15:26:00,466] Trial 79 finished with value: 0.24252225713041312 and parameters: {'l1_ratio': 0.8187818034877232}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21894805814098459
Fold 2 IBS: 0.24556510862191305
Fold 3 IBS: 0.2630353661645127
[I 2024-04-21 15:26:00,951] Trial 80 finished with value: 0.2425161776424701 and parameters: {'l1_ratio': 0.281973373419343}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21892299503496238
Fold 2 IBS: 0.23212389666393982
Fold 3 IBS: 0.22889273157732482
[I 2024-04-21 15:26:01,220] Trial 81 finished with value: 0.2266465410920757 and parameters: {'l1_ratio': 0.2560030562864504}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.24313453197971605
Fold 2 IBS: 0.23234695942638736
Fold 3 IBS: 0.23007190017728124
[I 2024-04-21 15:26:01,383] Trial 82 finished with value: 0.23518446386112823 and parameters: {'l1_ratio': 0.19355546096550508}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.2444792572615075
Fold 2 IBS: 0.23261155500080904
Fold 3 IBS: 0.2312658109382058
[I 2024-04-21 15:26:01,518] Trial 83 finished with value: 0.2361188744001741 and parameters: {'l1_ratio': 0.13646481491576934}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.2189039423628095
Fold 2 IBS: 0.23213763446845526
Fold 3 IBS: 0.2289725556636217
[I 2024-04-21 15:26:01,972] Trial 84 finished with value: 0.2266713774982955 and parameters: {'l1_ratio': 0.2515628209564072}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21894125157602182
Fold 2 IBS: 0.23223020146998352
Fold 3 IBS: 0.2294824081444247
[I 2024-04-21 15:26:02,234] Trial 85 finished with value: 0.22688462039681 and parameters: {'l1_ratio': 0.22395315628811555}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21889960057879093
Fold 2 IBS: 0.24556908942823744
Fold 3 IBS: 0.26300992485615077
[I 2024-04-21 15:26:02,693] Trial 86 finished with value: 0.2424928716210597 and parameters: {'l1_ratio': 0.3554707892663437}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.24521371802044664
Fold 2 IBS: 0.23277169698507086
Fold 3 IBS: 0.2319250768225345
[I 2024-04-21 15:26:02,901] Trial 87 finished with value: 0.23663683060935067 and parameters: {'l1_ratio': 0.10722433482405311}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21892190007453446
Fold 2 IBS: 0.24556861719012865
Fold 3 IBS: 0.2630009287253599
[I 2024-04-21 15:26:03,296] Trial 88 finished with value: 0.24249714866334102 and parameters: {'l1_ratio': 0.2959097962395273}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.2432675786687388
Fold 2 IBS: 0.2323713718841526
Fold 3 IBS: 0.23018928229827332
[I 2024-04-21 15:26:03,512] Trial 89 finished with value: 0.2352760776170549 and parameters: {'l1_ratio': 0.1876861065403984}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21895887271070524
Fold 2 IBS: 0.24556185628082458
Fold 3 IBS: 0.228736714500993
[I 2024-04-21 15:26:03,951] Trial 90 finished with value: 0.23108581449750762 and parameters: {'l1_ratio': 0.2647770828148817}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21893921621260432
Fold 2 IBS: 0.2321120923041292
Fold 3 IBS: 0.22882313691098313
[I 2024-04-21 15:26:04,241] Trial 91 finished with value: 0.22662481514257218 and parameters: {'l1_ratio': 0.2599011543676667}. Best is trial 32 with value: 0.22660086137026236.

Fold 1 IBS: 0.21893945488667282
Fold 2 IBS: 0.23223160338889062
Fold 3 IBS: 0.2294898030921103
[I 2024-04-21 15:26:04,523] Trial 92 finished with value: 0.2268869537892246 and parameters: {'l1_ratio': 0.22356196803322456}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21893250057128685
Fold 2 IBS: 0.24557020193906345
Fold 3 IBS: 0.2629944903726767
[I 2024-04-21 15:26:05,012] Trial 93 finished with value: 0.24249906429434231 and parameters: {'l1_ratio': 0.3205225122913358}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21889573176979435
Fold 2 IBS: 0.24556088584584557
Fold 3 IBS: 0.22869199339355947
[I 2024-04-21 15:26:05,453] Trial 94 finished with value: 0.2310495370030665 and parameters: {'l1_ratio': 0.2673157462027858}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21892742643407362
Fold 2 IBS: 0.24556805640379833
Fold 3 IBS: 0.26300533791524255
[I 2024-04-21 15:26:05,962] Trial 95 finished with value: 0.2425002735843715 and parameters: {'l1_ratio': 0.2973678683312579}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21896051325312885
Fold 2 IBS: 0.24556770231407868
Fold 3 IBS: 0.26304101269381486
[I 2024-04-21 15:26:06,423] Trial 96 finished with value: 0.2425230760870075 and parameters: {'l1_ratio': 0.4010528315259956}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21892742360112982
Fold 2 IBS: 0.23217990839477484
Fold 3 IBS: 0.22921101194713464
[I 2024-04-21 15:26:06,693] Trial 97 finished with value: 0.22677278131434644 and parameters: {'l1_ratio': 0.23849086753139553}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.24386404542085144
Fold 2 IBS: 0.23248568799153085
Fold 3 IBS: 0.2307175155405036
[I 2024-04-21 15:26:06,911] Trial 98 finished with value: 0.23568908298429528 and parameters: {'l1_ratio': 0.16198328427791897}. Best is trial 32 with value: 0.22660086137026236.
Fold 1 IBS: 0.21892556682863287
Fold 2 IBS: 0.23230455427600938
Fold 3 IBS: 0.2298635275408564
[I 2024-04-21 15:26:07,125] Trial 99 finished with value: 0.2270312162151662 and parameters: {'l1_ratio': 0.20412184854106702}. Best is trial 32 with value: 0.22660086137026236.


* Best trial for IBS:
 FrozenTrial(number=32, state=TrialState.COMPLETE, values=[0.22660086137026236], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 45, 396556), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 45, 713487), params={'l1_ratio': 0.2642152854612092}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=32, value=None)


* Best Score for IBS:
 0.22660086137026236

In [42]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [43]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.636
train_ibs:  0.227

#### Test

In [44]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [45]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.08382735104105443)

test_cindex : 0.598

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.2642152854612092)

test_ibs:  0.232

In [46]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [ ]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-21 15:26:07,448] A new study created in memory with name: no-name-d3525581-d9b7-4d70-8a44-c1b8eeadcb62

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6363040629095675
Fold 2 C-index: 0.5813008130081301
Fold 3 C-index: 0.5181564245810056
[I 2024-04-21 15:26:10,221] Trial 0 finished with value: 0.5785871001662345 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.5785871001662345.
Fold 1 C-index: 0.627129750982962
Fold 2 C-index: 0.5804878048780487
Fold 3 C-index: 0.5705307262569832
[I 2024-04-21 15:26:12,154] Trial 1 finished with value: 0.5927160940393313 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.5927160940393313.
Fold 1 C-index: 0.627129750982962
Fold 2 C-index: 0.5682926829268292
Fold 3 C-index: 0.5614525139664804
[I 2024-04-21 15:26:14,020] Trial 2 finished with value: 0.5856249826254238 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.5927160940393313.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:14,800] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.5927160940393313.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:16,105] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.5927160940393313.
Fold 1 C-index: 0.6408912188728703
Fold 2 C-index: 0.6170731707317073
Fold 3 C-index: 0.5935754189944135
[I 2024-04-21 15:26:18,861] Trial 5 finished with value: 0.6171799361996637 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.6171799361996637.
Fold 1 C-index: 0.6598951507208388
Fold 2 C-index: 0.6089430894308943
Fold 3 C-index: 0.547486033519553
[I 2024-04-21 15:26:22,117] Trial 6 finished with value: 0.6054414245570954 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.6171799361996637.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:23,705] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.6171799361996637.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.35528455284552846
Fold 3 C-index: 0.4504189944134078
[I 2024-04-21 15:26:28,694] Trial 8 finished with value: 0.46384963152405784 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.6171799361996637.
Fold 1 C-index: 0.6435124508519003
Fold 2 C-index: 0.6544715447154471
Fold 3 C-index: 0.611731843575419
[I 2024-04-21 15:26:30,709] Trial 9 finished with value: 0.6365719463809222 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 9 with value: 0.6365719463809222.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:31,142] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.9610671372536813, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 9 with value: 0.6365719463809222.
Fold 1 C-index: 0.6487549148099607
Fold 2 C-index: 0.5520325203252032
Fold 3 C-index: 0.5677374301675978
[I 2024-04-21 15:26:32,106] Trial 11 finished with value: 0.5895082884342538 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 109, 'oob_score': False, 'max_samples': 0.11379276107227315, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018098423978521135, 'warm_start': False}. Best is trial 9 with value: 0.6365719463809222.
Fold 1 C-index: 0.6304062909567497
Fold 2 C-index: 0.6178861788617886
Fold 3 C-index: 0.590782122905028
[I 2024-04-21 15:26:35,754] Trial 12 finished with value: 0.6130248642411887 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 498, 'oob_score': False, 'max_samples': 0.8392165520631284, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08506650508113567, 'warm_start': False}. Best is trial 9 with value: 0.6365719463809222.
Fold 1 C-index: 0.6415465268676278
Fold 2 C-index: 0.4195121951219512
Fold 3 C-index: 0.49511173184357543
[I 2024-04-21 15:26:38,553] Trial 13 finished with value: 0.5187234846110514 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.4760095384782845, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.008606277463368957, 'warm_start': False}. Best is trial 9 with value: 0.6365719463809222.
Fold 1 C-index: 0.6349934469200524
Fold 2 C-index: 0.8130081300813008
Fold 3 C-index: 0.6033519553072626
[I 2024-04-21 15:26:39,742] Trial 14 finished with value: 0.6837845107695385 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 192, 'oob_score': True, 'max_samples': 0.7873021337102564, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1584235940276062, 'warm_start': True}. Best is trial 14 with value: 0.6837845107695385.
Fold 1 C-index: 0.6245085190039319
Fold 2 C-index: 0.8390243902439024
Fold 3 C-index: 0.5928770949720671
[I 2024-04-21 15:26:40,774] Trial 15 finished with value: 0.6854700014066338 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.8107341403225247, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16866630138034366, 'warm_start': True}. Best is trial 15 with value: 0.6854700014066338.
Fold 1 C-index: 0.6231979030144168
Fold 2 C-index: 0.8390243902439024
Fold 3 C-index: 0.6019553072625698
[I 2024-04-21 15:26:41,713] Trial 16 finished with value: 0.6880592001736296 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.8029947290400248, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16939069998793121, 'warm_start': True}. Best is trial 16 with value: 0.6880592001736296.

Fold 1 C-index: 0.6192660550458715
Fold 2 C-index: 0.7967479674796748
Fold 3 C-index: 0.6522346368715084
[I 2024-04-21 15:26:42,445] Trial 17 finished with value: 0.6894162197990182 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 110, 'oob_score': True, 'max_samples': 0.8260002438359659, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20020395152945147, 'warm_start': True}. Best is trial 17 with value: 0.6894162197990182.
Fold 1 C-index: 0.6304062909567497
Fold 2 C-index: 0.767479674796748
Fold 3 C-index: 0.6319832402234636
[I 2024-04-21 15:26:42,770] Trial 18 finished with value: 0.6766230686589871 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 23, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 17 with value: 0.6894162197990182.
Fold 1 C-index: 0.6349934469200524
Fold 2 C-index: 0.8
Fold 3 C-index: 0.638268156424581
[I 2024-04-21 15:26:43,520] Trial 19 finished with value: 0.6910872011148778 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 111, 'oob_score': True, 'max_samples': 0.7105420171094243, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21389275171746558, 'warm_start': True}. Best is trial 19 with value: 0.6910872011148778.
Fold 1 C-index: 0.6363040629095675
Fold 2 C-index: 0.7682926829268293
Fold 3 C-index: 0.6466480446927374
[I 2024-04-21 15:26:44,051] Trial 20 finished with value: 0.6837482635097114 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.692576219550904, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22890213634380396, 'warm_start': True}. Best is trial 19 with value: 0.6910872011148778.
Fold 1 C-index: 0.6218872870249017
Fold 2 C-index: 0.8008130081300813
Fold 3 C-index: 0.6641061452513967
[I 2024-04-21 15:26:44,783] Trial 21 finished with value: 0.6956021468021265 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 112, 'oob_score': True, 'max_samples': 0.8608150048906333, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20514613946240096, 'warm_start': True}. Best is trial 21 with value: 0.6956021468021265.
Fold 1 C-index: 0.6441677588466579
Fold 2 C-index: 0.8040650406504065
Fold 3 C-index: 0.6396648044692738
[I 2024-04-21 15:26:45,623] Trial 22 finished with value: 0.6959658679887794 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.8622025014471517, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.26012317640885374, 'warm_start': True}. Best is trial 22 with value: 0.6959658679887794.

In [ ]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [ ]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

#### Test

In [ ]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [ ]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

In [ ]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [ ]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

In [ ]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [ ]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

#### Test

In [ ]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [ ]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

In [ ]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [ ]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

In [ ]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [ ]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

#### Test

In [ ]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [ ]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

In [ ]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [ ]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

In [ ]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [ ]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

#### Test

In [ ]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [ ]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

In [ ]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [ ]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

In [ ]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

In [ ]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

In [ ]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

In [ ]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/dfs/minmax/plsr/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_dfs_minmax_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [ ]:
from datetime import date
today = date.today()
print("Date: ", today)