In [1]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
 
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from datetime import datetime
from sklearn.preprocessing import MinMaxScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

In [6]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

### COX assumption in Train data

In [7]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                test_statistic    p  -log2(p)
MTV                       0.00 0.95      0.08
SUVpeak                   0.29 0.59      0.76
TLG                       0.22 0.64      0.65
age                       1.60 0.21      2.28
cavum_oris                0.00 1.00      0.01
charlson                  0.07 0.79      0.34
female                    0.17 0.68      0.56
histgrade_high            1.26 0.26      1.93
hpv_related               4.31 0.04      4.72
hypopharynx               0.00 0.99      0.01
larynx                    0.00 0.98      0.02
oropharynx                0.00 0.99      0.02
pack_years                0.71 0.40      1.32
uicc8_III-IV              0.45 0.50      0.99

In [8]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['hpv_related'], dtype='object')

In [9]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                test_statistic    p  -log2(p)
MTV                       0.02 0.88      0.18
SUVpeak                   0.56 0.46      1.13
TLG                       0.06 0.81      0.30
age                       1.58 0.21      2.26
cavum_oris                0.08 0.77      0.37
charlson                  0.03 0.86      0.22
female                    0.35 0.56      0.85
histgrade_high            0.95 0.33      1.60
hpv_related               3.02 0.08      3.60
hypopharynx               0.10 0.75      0.41
larynx                    1.46 0.23      2.14
oropharynx                0.96 0.33      1.61
pack_years                0.39 0.53      0.92
uicc8_III-IV              0.08 0.78      0.36

In [10]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index([], dtype='object')

###### penalizer values essentially result in same result

## Test dataset: MAASTRO

In [11]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [12]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [13]:
# need to choose patient_id from MAASTRO_D1 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [14]:
# Merge MAASTRO_D1 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG,DFS,DFS_event
0,1,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342,8.83,1.0
3,4,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979,19.73,1.0
4,6,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782,13.27,1.0
95,111,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212,72.07,0.0

In [15]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [16]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, DFS, DFS_event]
Index: []

In [17]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [18]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [19]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 14)
y_train:  (139,)

In [20]:
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [21]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 16)

In [22]:
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X.values, i) 
                          for i in range(len(X.columns))] 

vif_data

           feature        VIF
0              age   1.136852
1           female   1.197250
2       cavum_oris   7.993011
3       oropharynx  60.199385
4      hypopharynx  11.118710
5           larynx  14.183474
6   histgrade_high   1.150479
7      hpv_related   4.309385
8         charlson   1.302350
9       pack_years   1.647441
10    uicc8_III-IV   2.026695
11         SUVpeak   2.157147
12             MTV   5.247552
13             TLG   6.368452

# Standardization

In [23]:
original_X = X.copy()

In [24]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

## Standardize the data but not the categorical columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

### Separate the categorical and non-categorical columns
X_categorical = X[categorical_columns]
X_numeric = X.drop(categorical_columns, axis=1)
X_numeric_columns = X_numeric.columns
X_numeric_index = X_numeric.index

### Standardize non-categorical and then concat with the categorical
scaler = MinMaxScaler()  
X_numeric_std = scaler.fit_transform(X_numeric)
X_numeric_std = pd.DataFrame(X_numeric_std, columns=X_numeric_columns, index=X_numeric_index)
X_std = pd.concat([X_categorical, X_numeric_std], axis=1)

## Sort the order of the columns as it was in the clinical train 
X_std = X_std[original_X.columns]

In [25]:
# Standardize X_MAASTRO 
MAASTRO_new = X_MAASTRO.copy()
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [26]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = MAASTRO_new_std

In [27]:
X_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,54.238356,1,0,1,0,0,1,0.0,0,0.000000,0.0,14.473272,7.934,86.228420
1,54.539726,0,0,0,0,1,0,0.0,1,27.404795,0.0,5.044678,1.656,7.040100
2,59.019178,0,1,0,0,0,1,0.0,1,41.019178,1.0,7.839043,14.502,83.569669
3,70.726027,0,0,0,0,1,0,0.0,1,37.500000,0.0,2.880631,2.440,5.567091
4,67.865753,0,0,0,0,1,0,0.0,1,53.000000,0.0,5.402006,3.668,16.150550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,60.435616,0,0,1,0,0,1,1.0,0,0.000000,0.0,9.290139,3.650,26.280140
135,68.794521,0,0,1,0,0,1,1.0,0,0.000000,1.0,7.172883,18.967,101.754834
136,57.498630,0,0,1,0,0,1,1.0,1,39.498630,0.0,13.873187,6.370,66.273201
137,65.684932,0,0,1,0,0,1,1.0,1,71.527397,1.0,7.507419,12.443,71.832443
138,61.676712,0,0,1,0,0,1,1.0,0,2.250000,1.0,13.053465,7.983,78.647696

In [28]:
X_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,0.365347,1,0,1,0,0,1,0.0,0,0.000000,0.0,0.435155,0.074159,0.044798
1,0.373041,0,0,0,0,1,0,0.0,1,0.213981,0.0,0.089331,0.008512,0.001900
2,0.487409,0,1,0,0,0,1,0.0,1,0.320284,1.0,0.191823,0.142839,0.043358
3,0.786304,0,0,0,0,1,0,0.0,1,0.292806,0.0,0.009957,0.016710,0.001102
4,0.713276,0,0,0,0,1,0,0.0,1,0.413832,0.0,0.102437,0.029551,0.006835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,0.523573,0,0,1,0,0,1,1.0,0,0.000000,0.0,0.245047,0.029363,0.012323
135,0.736989,0,0,1,0,0,1,1.0,0,0.000000,1.0,0.167389,0.189529,0.053209
136,0.448587,0,0,1,0,0,1,1.0,1,0.308411,0.0,0.413145,0.057805,0.033988
137,0.657597,0,0,1,0,0,1,1.0,1,0.558497,1.0,0.179660,0.121309,0.037000
138,0.555260,0,0,1,0,0,1,1.0,0,0.017568,1.0,0.383079,0.074672,0.040692

In [29]:
MAASTRO_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623
1,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700
2,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342
3,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979
4,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782
95,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868
96,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274
97,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492
98,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212

In [30]:
MAASTRO_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,0.384793,0,0,1,0,0,1,1,1,0.000000,0,0.470560,0.230038,0.140892
1,0.384793,0,0,1,0,0,0,0,0,0.156163,1,0.228146,0.050381,0.018119
2,0.384793,0,0,1,0,0,0,0,1,0.046849,1,0.398581,0.072664,0.038519
3,0.537983,1,0,0,0,1,1,0,1,0.351367,1,0.220934,0.073887,0.023434
4,0.767767,0,0,1,0,0,1,1,1,0.460681,0,0.263159,0.150525,0.056396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0.665641,1,0,0,0,1,0,0,0,0.429449,1,1.053738,0.055086,0.076361
95,0.589046,0,0,0,0,1,0,0,1,1.358619,1,0.382644,0.066296,0.035582
96,0.589046,0,0,1,0,0,1,1,1,0.000000,1,0.232370,0.163554,0.053664
97,0.359261,0,0,1,0,0,1,1,0,0.000000,0,0.424553,0.095564,0.054008
98,0.563514,0,0,0,1,0,1,0,0,0.312326,1,0.286299,0.027742,0.013554

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [141]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min-max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-21 16:14:53,526] A new study created in memory with name: no-name-b63464ab-cda0-4ae6-8e3e-00d88dad8d21

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-21 16:14:53,711] A new study created in memory with name: no-name-c3ff4653-f8d3-4dd7-a6fc-eb9ce2f996f3

Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-21 16:14:53,707] Trial 0 finished with value: 0.6371137109369622 and parameters: {}. Best is trial 0 with value: 0.6371137109369622.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6371137109369622], datetime_start=datetime.datetime(2024, 4, 21, 16, 14, 53, 550947), datetime_complete=datetime.datetime(2024, 4, 21, 16, 14, 53, 707231), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6371137109369622

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.5623041979949875
Fold 2 IBS: 0.2636542638834043
Fold 3 IBS: 0.18152300182294628
Fold 4 IBS: 0.2906666179111608
Fold 5 IBS: 0.21154504298347718
[I 2024-04-21 16:14:53,922] Trial 0 finished with value: 0.3019386249191952 and parameters: {}. Best is trial 0 with value: 0.3019386249191952.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.3019386249191952], datetime_start=datetime.datetime(2024, 4, 21, 16, 14, 53, 736569), datetime_complete=datetime.datetime(2024, 4, 21, 16, 14, 53, 922084), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.3019386249191952

In [142]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [143]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.637
train_ibs:  0.302

#### Test

In [144]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [145]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.563
IBS score: 0.277

In [110]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [37]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [38]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-21 15:25:11,352] A new study created in memory with name: no-name-e74760c2-91ad-4d90-91df-a360eeaaf53d

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-21 15:25:11,589] A new study created in memory with name: no-name-ce04d780-b487-474d-8f6d-1dc31b26c0b2

Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:11,580] Trial 0 finished with value: 0.6059844970067908 and parameters: {}. Best is trial 0 with value: 0.6059844970067908.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6059844970067908], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 11, 422127), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 11, 580543), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6059844970067908

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24820216468962097
Fold 2 IBS: 0.23351868202031184
Fold 3 IBS: 0.2346623445671507
[I 2024-04-21 15:25:11,973] Trial 0 finished with value: 0.23879439709236117 and parameters: {}. Best is trial 0 with value: 0.23879439709236117.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23879439709236117], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 11, 645357), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 11, 972844), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23879439709236117

In [39]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [40]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.606
train_ibs:  0.239

#### Test

In [41]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [42]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.657

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.224

In [43]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [44]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-21 15:25:12,387] A new study created in memory with name: no-name-f3005775-a7f2-4eb1-95ed-0cfdbfb84c3c

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.580602883355177
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5391061452513967
[I 2024-04-21 15:25:12,794] Trial 0 finished with value: 0.5943745542509716 and parameters: {}. Best is trial 0 with value: 0.5943745542509716.

[I 2024-04-21 15:25:12,809] A new study created in memory with name: no-name-5843031f-2827-4335-85be-9a4d0b6ca9a9

* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5943745542509716], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 12, 420904), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 12, 794511), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5943745542509716

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2475305706612343
Fold 2 IBS: 0.27754301055956615
Fold 3 IBS: 0.2912429350332853
[I 2024-04-21 15:25:13,580] Trial 0 finished with value: 0.2721055054180286 and parameters: {}. Best is trial 0 with value: 0.2721055054180286.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2721055054180286], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 12, 863581), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 13, 580162), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2721055054180286

In [45]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [46]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.594
train_ibs:  0.272

#### Test

In [47]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [48]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.562

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.275

In [49]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [50]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-21 15:25:14,202] A new study created in memory with name: no-name-c2f73ef5-90fb-47ea-b30f-878fa351aa83

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5391061452513967
[I 2024-04-21 15:25:14,941] Trial 0 finished with value: 0.5948114262474767 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.5948114262474767.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:15,437] Trial 1 finished with value: 0.593386100851058 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.5948114262474767.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:15,841] Trial 2 finished with value: 0.593386100851058 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.5948114262474767.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5349162011173184
[I 2024-04-21 15:25:16,169] Trial 3 finished with value: 0.593851650199289 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.5948114262474767.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5391061452513967
[I 2024-04-21 15:25:16,701] Trial 4 finished with value: 0.5948114262474767 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.5948114262474767.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5349162011173184
[I 2024-04-21 15:25:17,026] Trial 5 finished with value: 0.593851650199289 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.5948114262474767.
Fold 1 C-index: 0.580602883355177
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5391061452513967
[I 2024-04-21 15:25:17,371] Trial 6 finished with value: 0.5943745542509716 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.5948114262474767.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5391061452513967
[I 2024-04-21 15:25:17,718] Trial 7 finished with value: 0.5948114262474767 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.5948114262474767.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5349162011173184
[I 2024-04-21 15:25:18,155] Trial 8 finished with value: 0.593851650199289 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.5948114262474767.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:18,549] Trial 9 finished with value: 0.593386100851058 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.5948114262474767.
Fold 1 C-index: 0.580602883355177
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5391061452513967
[I 2024-04-21 15:25:18,824] Trial 10 finished with value: 0.5943745542509716 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.5948114262474767.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5391061452513967
[I 2024-04-21 15:25:19,150] Trial 11 finished with value: 0.5948114262474767 and parameters: {'l1_ratio': 0.748312136386636}. Best is trial 0 with value: 0.5948114262474767.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5391061452513967
[I 2024-04-21 15:25:19,500] Trial 12 finished with value: 0.5948114262474767 and parameters: {'l1_ratio': 0.7236736559681478}. Best is trial 0 with value: 0.5948114262474767.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5391061452513967
[I 2024-04-21 15:25:19,692] Trial 13 finished with value: 0.5948114262474767 and parameters: {'l1_ratio': 0.8178071080614558}. Best is trial 0 with value: 0.5948114262474767.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:19,740] Trial 14 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:19,786] Trial 15 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:19,867] Trial 16 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:19,999] Trial 17 finished with value: 0.6046738810172759 and parameters: {'l1_ratio': 0.11003847364978746}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:20,058] Trial 18 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.013108986184265342}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6650406504065041
Fold 3 C-index: 0.5321229050279329
[I 2024-04-21 15:25:20,429] Trial 19 finished with value: 0.5934625569228813 and parameters: {'l1_ratio': 0.16450025006472974}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:20,842] Trial 20 finished with value: 0.592949228854553 and parameters: {'l1_ratio': 0.31242295912387974}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:21,014] Trial 21 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.009015851251424588}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:21,127] Trial 22 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.09946730166659407}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:21,346] Trial 23 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.097070668839174}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:21,522] Trial 24 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.003961536626516845}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6650406504065041
Fold 3 C-index: 0.5321229050279329
[I 2024-04-21 15:25:22,004] Trial 25 finished with value: 0.5934625569228813 and parameters: {'l1_ratio': 0.16505373442336413}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:22,102] Trial 26 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.08165843528332521}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:22,717] Trial 27 finished with value: 0.593386100851058 and parameters: {'l1_ratio': 0.23486060149415236}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6650406504065041
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:23,244] Trial 28 finished with value: 0.5939281062711123 and parameters: {'l1_ratio': 0.1937546523322504}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:23,345] Trial 29 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.06519122510965338}. Best is trial 14 with value: 0.6059844970067908.

Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:23,724] Trial 30 finished with value: 0.593386100851058 and parameters: {'l1_ratio': 0.32170963481394405}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:23,871] Trial 31 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.00017291237040205354}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:24,220] Trial 32 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.04949751601433792}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:24,507] Trial 33 finished with value: 0.6046738810172759 and parameters: {'l1_ratio': 0.13696846267017276}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.6650406504065041
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:25,200] Trial 34 finished with value: 0.5934912342746071 and parameters: {'l1_ratio': 0.23026639169144428}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:25,389] Trial 35 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.05526024492024897}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:25,834] Trial 36 finished with value: 0.592949228854553 and parameters: {'l1_ratio': 0.24757612519478245}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5349162011173184
[I 2024-04-21 15:25:26,240] Trial 37 finished with value: 0.593414778202784 and parameters: {'l1_ratio': 0.5802102856643269}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:26,503] Trial 38 finished with value: 0.6046738810172759 and parameters: {'l1_ratio': 0.14305756694715926}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:26,687] Trial 39 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.04032884745061077}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:27,135] Trial 40 finished with value: 0.593386100851058 and parameters: {'l1_ratio': 0.34910397599316756}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:27,216] Trial 41 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.008382180368166157}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:27,342] Trial 42 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.03862793461981657}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6650406504065041
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:27,733] Trial 43 finished with value: 0.5939281062711123 and parameters: {'l1_ratio': 0.19870775751647682}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.580602883355177
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:28,004] Trial 44 finished with value: 0.6042370090207708 and parameters: {'l1_ratio': 0.11619277653730493}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:28,121] Trial 45 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.007238804895064288}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6650406504065041
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:28,507] Trial 46 finished with value: 0.5939281062711123 and parameters: {'l1_ratio': 0.273865152709055}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5845347313237221
Fold 2 C-index: 0.6650406504065041
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:28,859] Trial 47 finished with value: 0.5943649782676172 and parameters: {'l1_ratio': 0.18156172380394398}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5391061452513967
[I 2024-04-21 15:25:29,013] Trial 48 finished with value: 0.5948114262474767 and parameters: {'l1_ratio': 0.908082736959313}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5349162011173184
[I 2024-04-21 15:25:29,328] Trial 49 finished with value: 0.593851650199289 and parameters: {'l1_ratio': 0.4933979873331958}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5363128491620112
[I 2024-04-21 15:25:29,676] Trial 50 finished with value: 0.5943171995475199 and parameters: {'l1_ratio': 0.6064718647459368}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.580602883355177
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:29,899] Trial 51 finished with value: 0.6042370090207708 and parameters: {'l1_ratio': 0.10686725480797975}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:30,007] Trial 52 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.06557055334205064}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:30,126] Trial 53 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.09167431992169013}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:30,302] Trial 54 finished with value: 0.6046738810172759 and parameters: {'l1_ratio': 0.13863039144986744}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:30,463] Trial 55 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.02864140027406609}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5349162011173184
[I 2024-04-21 15:25:30,841] Trial 56 finished with value: 0.593851650199289 and parameters: {'l1_ratio': 0.41317185267728007}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:31,141] Trial 57 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.08229770898581358}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:31,396] Trial 58 finished with value: 0.6046738810172759 and parameters: {'l1_ratio': 0.1330922821158574}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:31,506] Trial 59 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.04196538011952014}. Best is trial 14 with value: 0.6059844970067908.

Fold 1 C-index: 0.5845347313237221
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:31,976] Trial 60 finished with value: 0.5938229728475631 and parameters: {'l1_ratio': 0.1853725643519477}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:32,064] Trial 61 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.08688025702675667}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:32,180] Trial 62 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.09349654471318652}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:32,273] Trial 63 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.0001097120972090599}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:32,634] Trial 64 finished with value: 0.5708928759188088 and parameters: {'l1_ratio': 0.15413141534587613}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:32,755] Trial 65 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.06327633939255814}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:32,952] Trial 66 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.027504342819642588}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:33,191] Trial 67 finished with value: 0.6046738810172759 and parameters: {'l1_ratio': 0.11126451530539334}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:33,272] Trial 68 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.06537356552973814}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:33,723] Trial 69 finished with value: 0.593386100851058 and parameters: {'l1_ratio': 0.20208776696636627}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5349162011173184
[I 2024-04-21 15:25:34,043] Trial 70 finished with value: 0.593851650199289 and parameters: {'l1_ratio': 0.4570201684006047}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:34,217] Trial 71 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.022206439212478044}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:34,362] Trial 72 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.002342226617928215}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:34,487] Trial 73 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.0466136597694819}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.580602883355177
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:34,614] Trial 74 finished with value: 0.6042370090207708 and parameters: {'l1_ratio': 0.11906254745628259}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:34,669] Trial 75 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.062323588043760585}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6650406504065041
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:35,006] Trial 76 finished with value: 0.5939281062711123 and parameters: {'l1_ratio': 0.16084149502889192}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:35,194] Trial 77 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.030512999704924812}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:35,313] Trial 78 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.07425220280123235}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:35,489] Trial 79 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.10460005447621551}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6650406504065041
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:35,975] Trial 80 finished with value: 0.5939281062711123 and parameters: {'l1_ratio': 0.2731215798765113}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:36,136] Trial 81 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.027516043740990127}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:36,248] Trial 82 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.00042949850645819347}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:36,497] Trial 83 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.08273310068402617}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.580602883355177
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:36,795] Trial 84 finished with value: 0.6042370090207708 and parameters: {'l1_ratio': 0.12445343324361885}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:36,954] Trial 85 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.049279746339309594}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5349162011173184
[I 2024-04-21 15:25:37,447] Trial 86 finished with value: 0.593851650199289 and parameters: {'l1_ratio': 0.5322933555815866}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:37,662] Trial 87 finished with value: 0.5708928759188088 and parameters: {'l1_ratio': 0.15992139719278914}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6650406504065041
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:38,183] Trial 88 finished with value: 0.5939281062711123 and parameters: {'l1_ratio': 0.21149835349378876}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:38,297] Trial 89 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.026852632676124952}. Best is trial 14 with value: 0.6059844970067908.

Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:38,470] Trial 90 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.0842555119419376}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:38,574] Trial 91 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.05988260944597094}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:38,708] Trial 92 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.01834508792198858}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.583224115334207
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5377094972067039
[I 2024-04-21 15:25:39,141] Trial 93 finished with value: 0.5947827488957508 and parameters: {'l1_ratio': 0.6547273520711029}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:39,274] Trial 94 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.09419075388633558}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:39,546] Trial 95 finished with value: 0.6046738810172759 and parameters: {'l1_ratio': 0.13587736999274164}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:39,717] Trial 96 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.04667719156676619}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:39,854] Trial 97 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.0720912083360898}. Best is trial 14 with value: 0.6059844970067908.
Fold 1 C-index: 0.581913499344692
Fold 2 C-index: 0.6634146341463415
Fold 3 C-index: 0.5391061452513967
[I 2024-04-21 15:25:40,218] Trial 98 finished with value: 0.5948114262474767 and parameters: {'l1_ratio': 0.7667338152719219}. Best is trial 14 with value: 0.6059844970067908.

[I 2024-04-21 15:25:40,736] A new study created in memory with name: no-name-75baecac-ee38-4a58-ad29-098b94ef4490

Fold 1 C-index: 0.5845347313237221
Fold 2 C-index: 0.6650406504065041
Fold 3 C-index: 0.5335195530726257
[I 2024-04-21 15:25:40,713] Trial 99 finished with value: 0.5943649782676172 and parameters: {'l1_ratio': 0.17739621879747836}. Best is trial 14 with value: 0.6059844970067908.


* Best trial for C-index:
 FrozenTrial(number=14, state=TrialState.COMPLETE, values=[0.6059844970067908], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 19, 694284), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 19, 740613), params={'l1_ratio': 0.1015556329868651}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=14, value=None)


* Best Score for C-index:
 0.6059844970067908

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2475783479188048
Fold 2 IBS: 0.2775672556954279
Fold 3 IBS: 0.2911897513240198
[I 2024-04-21 15:25:41,260] Trial 0 finished with value: 0.2721117849794175 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.2721117849794175.
Fold 1 IBS: 0.24760277316282148
Fold 2 IBS: 0.2775696953239809
Fold 3 IBS: 0.29138596286076807
[I 2024-04-21 15:25:41,784] Trial 1 finished with value: 0.2721861437825235 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.2721117849794175.
Fold 1 IBS: 0.24759599016705242
Fold 2 IBS: 0.27757543143620833
Fold 3 IBS: 0.291488754490802
[I 2024-04-21 15:25:42,252] Trial 2 finished with value: 0.27222005869802096 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.2721117849794175.
Fold 1 IBS: 0.247511526612108
Fold 2 IBS: 0.277573566272216
Fold 3 IBS: 0.2913565288303236
[I 2024-04-21 15:25:42,889] Trial 3 finished with value: 0.2721472072382159 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.2721117849794175.
Fold 1 IBS: 0.24755162271723735
Fold 2 IBS: 0.2775360909267776
Fold 3 IBS: 0.2912251418150679
[I 2024-04-21 15:25:43,458] Trial 4 finished with value: 0.2721042851530276 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 4 with value: 0.2721042851530276.
Fold 1 IBS: 0.2475713308227544
Fold 2 IBS: 0.2775780089636332
Fold 3 IBS: 0.2913227730829704
[I 2024-04-21 15:25:43,811] Trial 5 finished with value: 0.27215737095645265 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 4 with value: 0.2721042851530276.
Fold 1 IBS: 0.247446479156002
Fold 2 IBS: 0.27750102395616694
Fold 3 IBS: 0.2912035620570929
[I 2024-04-21 15:25:43,969] Trial 6 finished with value: 0.2720503550564206 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.2720503550564206.
Fold 1 IBS: 0.24754162110469918
Fold 2 IBS: 0.2775446016671604
Fold 3 IBS: 0.2911702475526491
[I 2024-04-21 15:25:44,388] Trial 7 finished with value: 0.27208549010816957 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.2720503550564206.
Fold 1 IBS: 0.2475764874369932
Fold 2 IBS: 0.27756775220311675
Fold 3 IBS: 0.29133771676247844
[I 2024-04-21 15:25:44,770] Trial 8 finished with value: 0.2721606521341961 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.2720503550564206.
Fold 1 IBS: 0.24755505828864996
Fold 2 IBS: 0.2775734532698608
Fold 3 IBS: 0.2913694147036409
[I 2024-04-21 15:25:45,259] Trial 9 finished with value: 0.27216597542071724 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.2720503550564206.
Fold 1 IBS: 0.2474626000660151
Fold 2 IBS: 0.27750897936096286
Fold 3 IBS: 0.2912104412253918
[I 2024-04-21 15:25:45,716] Trial 10 finished with value: 0.27206067355078994 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.2720503550564206.
Fold 1 IBS: 0.2475181810323072
Fold 2 IBS: 0.2775369512862885
Fold 3 IBS: 0.29123780203497546
[I 2024-04-21 15:25:46,163] Trial 11 finished with value: 0.27209764478452375 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 6 with value: 0.2720503550564206.
Fold 1 IBS: 0.24750643284188054
Fold 2 IBS: 0.2775312073997618
Fold 3 IBS: 0.29123137700010815
[I 2024-04-21 15:25:46,481] Trial 12 finished with value: 0.27208967241391685 and parameters: {'l1_ratio': 0.9946087870438435}. Best is trial 6 with value: 0.2720503550564206.
Fold 1 IBS: 0.24747956485525696
Fold 2 IBS: 0.27749800401273705
Fold 3 IBS: 0.2912596373095107
[I 2024-04-21 15:25:47,097] Trial 13 finished with value: 0.2720790687258349 and parameters: {'l1_ratio': 0.8521165717679541}. Best is trial 6 with value: 0.2720503550564206.
Fold 1 IBS: 0.24496967026285116
Fold 2 IBS: 0.23356610048169366
Fold 3 IBS: 0.2323892687921577
[I 2024-04-21 15:25:47,330] Trial 14 finished with value: 0.23697501317890082 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24794918102136296
Fold 2 IBS: 0.23350376180433238
Fold 3 IBS: 0.23448835780444954
[I 2024-04-21 15:25:47,424] Trial 15 finished with value: 0.2386471002100483 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24804939207125096
Fold 2 IBS: 0.23350936067764158
Fold 3 IBS: 0.23455734158570998
[I 2024-04-21 15:25:47,945] Trial 16 finished with value: 0.23870536477820084 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24661315390886676
Fold 2 IBS: 0.23359052005404113
Fold 3 IBS: 0.23223532311235423
[I 2024-04-21 15:25:48,221] Trial 17 finished with value: 0.23747966569175402 and parameters: {'l1_ratio': 0.11003847364978746}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24717159980374817
Fold 2 IBS: 0.23374160205481923
Fold 3 IBS: 0.29149867618987485
[I 2024-04-21 15:25:48,597] Trial 18 finished with value: 0.2574706260161474 and parameters: {'l1_ratio': 0.15220682101947353}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.2467269149666229
Fold 2 IBS: 0.23361256581047035
Fold 3 IBS: 0.23211070630095051
[I 2024-04-21 15:25:48,920] Trial 19 finished with value: 0.23748339569268126 and parameters: {'l1_ratio': 0.11710798977210826}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.2475684751939961
Fold 2 IBS: 0.2775475968580825
Fold 3 IBS: 0.2914437052531203
[I 2024-04-21 15:25:49,354] Trial 20 finished with value: 0.2721865924350663 and parameters: {'l1_ratio': 0.29988463458080117}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24669397187093034
Fold 2 IBS: 0.23360610215630487
Fold 3 IBS: 0.23214605228018448
[I 2024-04-21 15:25:49,652] Trial 21 finished with value: 0.23748204210247323 and parameters: {'l1_ratio': 0.11508371095417902}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24667929077325496
Fold 2 IBS: 0.23360332015237673
Fold 3 IBS: 0.23216155476334913
[I 2024-04-21 15:25:49,925] Trial 22 finished with value: 0.2374813885629936 and parameters: {'l1_ratio': 0.11420070168439711}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.2474587516637719
Fold 2 IBS: 0.2775589041881551
Fold 3 IBS: 0.2915046380910308
[I 2024-04-21 15:25:50,248] Trial 23 finished with value: 0.27217409798098596 and parameters: {'l1_ratio': 0.18733039331670132}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24569528934710916
Fold 2 IBS: 0.23350570053284836
Fold 3 IBS: 0.23290632230782404
[I 2024-04-21 15:25:50,306] Trial 24 finished with value: 0.23736910406259384 and parameters: {'l1_ratio': 0.07487957149895594}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24619115608105352
Fold 2 IBS: 0.23348251326094407
Fold 3 IBS: 0.2332582499287658
[I 2024-04-21 15:25:50,426] Trial 25 finished with value: 0.23764397309025445 and parameters: {'l1_ratio': 0.05812303479405819}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.2475594361091732
Fold 2 IBS: 0.27754937901408794
Fold 3 IBS: 0.29151193683737187
[I 2024-04-21 15:25:50,833] Trial 26 finished with value: 0.272206917320211 and parameters: {'l1_ratio': 0.2568276858262908}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24762289024645948
Fold 2 IBS: 0.27756193255680495
Fold 3 IBS: 0.2914012007324846
[I 2024-04-21 15:25:51,350] Trial 27 finished with value: 0.27219534117858296 and parameters: {'l1_ratio': 0.36016360216180404}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24598245448291567
Fold 2 IBS: 0.2334905618485584
Fold 3 IBS: 0.23311032450982982
[I 2024-04-21 15:25:51,595] Trial 28 finished with value: 0.23752778028043464 and parameters: {'l1_ratio': 0.06504022598354287}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24758835452850023
Fold 2 IBS: 0.2775739591426081
Fold 3 IBS: 0.29151151723994334
[I 2024-04-21 15:25:52,230] Trial 29 finished with value: 0.2722246103036839 and parameters: {'l1_ratio': 0.20877066654824122}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24759347886084915
Fold 2 IBS: 0.2775603357397062
Fold 3 IBS: 0.29142175114548113
[I 2024-04-21 15:25:52,709] Trial 30 finished with value: 0.27219185524867884 and parameters: {'l1_ratio': 0.32822576323651137}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.2451755933923424
Fold 2 IBS: 0.2335456200565373
Fold 3 IBS: 0.23253614322389976
[I 2024-04-21 15:25:52,861] Trial 31 finished with value: 0.2370857855575932 and parameters: {'l1_ratio': 0.09370523812126882}. Best is trial 14 with value: 0.23697501317890082.

Fold 1 IBS: 0.24607115587517053
Fold 2 IBS: 0.23348684240516673
Fold 3 IBS: 0.23317323279498642
[I 2024-04-21 15:25:53,085] Trial 32 finished with value: 0.2375770770251079 and parameters: {'l1_ratio': 0.06207691234646743}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24738945648035607
Fold 2 IBS: 0.2775781942344326
Fold 3 IBS: 0.2915640914550656
[I 2024-04-21 15:25:53,488] Trial 33 finished with value: 0.27217724738995147 and parameters: {'l1_ratio': 0.1778000985129503}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24758657901222147
Fold 2 IBS: 0.2775716626924408
Fold 3 IBS: 0.29144638579336674
[I 2024-04-21 15:25:54,103] Trial 34 finished with value: 0.272201542499343 and parameters: {'l1_ratio': 0.2432080643136032}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.2456010316322291
Fold 2 IBS: 0.23351172313511426
Fold 3 IBS: 0.2328392623441898
[I 2024-04-21 15:25:54,287] Trial 35 finished with value: 0.23731733903717775 and parameters: {'l1_ratio': 0.0781938668087461}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24751493655132142
Fold 2 IBS: 0.2775535088116977
Fold 3 IBS: 0.29133698387190915
[I 2024-04-21 15:25:54,666] Trial 36 finished with value: 0.27213514307830944 and parameters: {'l1_ratio': 0.6135978360967259}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24797976686266673
Fold 2 IBS: 0.2335054270188128
Fold 3 IBS: 0.23450942155648277
[I 2024-04-21 15:25:54,843] Trial 37 finished with value: 0.23866487181265408 and parameters: {'l1_ratio': 0.005751876941250428}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.2475663745544894
Fold 2 IBS: 0.2775503051249946
Fold 3 IBS: 0.29148169762944004
[I 2024-04-21 15:25:55,297] Trial 38 finished with value: 0.27219945910297466 and parameters: {'l1_ratio': 0.2782368811918279}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24757346095024782
Fold 2 IBS: 0.2775726953613922
Fold 3 IBS: 0.2913986724966485
[I 2024-04-21 15:25:55,971] Trial 39 finished with value: 0.27218160960276283 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24719834120851203
Fold 2 IBS: 0.2337551392358374
Fold 3 IBS: 0.291524212484905
[I 2024-04-21 15:25:56,522] Trial 40 finished with value: 0.2574925643097515 and parameters: {'l1_ratio': 0.15549610906776162}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24551190973973402
Fold 2 IBS: 0.23351790656902519
Fold 3 IBS: 0.23277581814677029
[I 2024-04-21 15:25:56,628] Trial 41 finished with value: 0.2372685448185098 and parameters: {'l1_ratio': 0.08136739029868036}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24601780475826787
Fold 2 IBS: 0.23348902619832615
Fold 3 IBS: 0.2331354018625747
[I 2024-04-21 15:25:56,788] Trial 42 finished with value: 0.2375474109397229 and parameters: {'l1_ratio': 0.06385505584641477}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24756779009848057
Fold 2 IBS: 0.27756581648901146
Fold 3 IBS: 0.29149124666102455
[I 2024-04-21 15:25:57,157] Trial 43 finished with value: 0.27220828441617223 and parameters: {'l1_ratio': 0.20525410621927148}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24607136706190472
Fold 2 IBS: 0.23348683407938348
Fold 3 IBS: 0.23317338250676925
[I 2024-04-21 15:25:57,344] Trial 44 finished with value: 0.23757719454935247 and parameters: {'l1_ratio': 0.062069898702991955}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24755101981451594
Fold 2 IBS: 0.2775504038714022
Fold 3 IBS: 0.29131804590463817
[I 2024-04-21 15:25:57,542] Trial 45 finished with value: 0.2721398231968521 and parameters: {'l1_ratio': 0.532905188903257}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24685149854894914
Fold 2 IBS: 0.2336404451779515
Fold 3 IBS: 0.23196774442240134
[I 2024-04-21 15:25:57,790] Trial 46 finished with value: 0.23748656271643398 and parameters: {'l1_ratio': 0.1254563689732125}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24670387265759017
Fold 2 IBS: 0.23347282521237706
Fold 3 IBS: 0.23362018702837714
[I 2024-04-21 15:25:57,984] Trial 47 finished with value: 0.2379322949661148 and parameters: {'l1_ratio': 0.04190802967369129}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24750566965816903
Fold 2 IBS: 0.27753670073954073
Fold 3 IBS: 0.2911932118152079
[I 2024-04-21 15:25:58,602] Trial 48 finished with value: 0.2720785274043059 and parameters: {'l1_ratio': 0.7991933234425521}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24720775523797953
Fold 2 IBS: 0.23375917627383053
Fold 3 IBS: 0.2915316770731494
[I 2024-04-21 15:25:58,973] Trial 49 finished with value: 0.2574995361949865 and parameters: {'l1_ratio': 0.15646697998241815}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.2476180609580652
Fold 2 IBS: 0.27758178024566654
Fold 3 IBS: 0.29151138761748346
[I 2024-04-21 15:25:59,387] Trial 50 finished with value: 0.27223707627373844 and parameters: {'l1_ratio': 0.2311229033161103}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24513387582577661
Fold 2 IBS: 0.23354955022239637
Fold 3 IBS: 0.23250639283027147
[I 2024-04-21 15:25:59,508] Trial 51 finished with value: 0.23706327295948149 and parameters: {'l1_ratio': 0.0952769568727201}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24521744152241143
Fold 2 IBS: 0.23354178818435592
Fold 3 IBS: 0.2325659833262152
[I 2024-04-21 15:25:59,706] Trial 52 finished with value: 0.23710840434432753 and parameters: {'l1_ratio': 0.09213795991301221}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.2450430306626575
Fold 2 IBS: 0.2335584923188984
Fold 3 IBS: 0.23244159846826234
[I 2024-04-21 15:25:59,925] Trial 53 finished with value: 0.2370143738166061 and parameters: {'l1_ratio': 0.09873222275108921}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24765834579276555
Fold 2 IBS: 0.23349013175487296
Fold 3 IBS: 0.23428707809417262
[I 2024-04-21 15:26:00,050] Trial 54 finished with value: 0.2384785185472704 and parameters: {'l1_ratio': 0.014355604105719719}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24714783423490283
Fold 2 IBS: 0.2337321806384242
Fold 3 IBS: 0.2914796529019882
[I 2024-04-21 15:26:00,894] Trial 55 finished with value: 0.2574532225917717 and parameters: {'l1_ratio': 0.14988520088645998}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24659477623538592
Fold 2 IBS: 0.2335874555047629
Fold 3 IBS: 0.23225362558827872
[I 2024-04-21 15:26:01,372] Trial 56 finished with value: 0.23747861910947585 and parameters: {'l1_ratio': 0.10901575657394012}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24510271833983027
Fold 2 IBS: 0.2335525576924476
Fold 3 IBS: 0.23248417133543547
[I 2024-04-21 15:26:01,498] Trial 57 finished with value: 0.23704648245590443 and parameters: {'l1_ratio': 0.09645695145244038}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.2474593683378399
Fold 2 IBS: 0.27755929856843004
Fold 3 IBS: 0.2915052040623337
[I 2024-04-21 15:26:01,881] Trial 58 finished with value: 0.2721746236562012 and parameters: {'l1_ratio': 0.18741877628597015}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24760257536612676
Fold 2 IBS: 0.2775712998608791
Fold 3 IBS: 0.2914466043663091
[I 2024-04-21 15:26:02,204] Trial 59 finished with value: 0.272206826531105 and parameters: {'l1_ratio': 0.3077528204548513}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.2470642606908587
Fold 2 IBS: 0.23347417674705356
Fold 3 IBS: 0.23387313502310988
[I 2024-04-21 15:26:02,438] Trial 60 finished with value: 0.2381371908203407 and parameters: {'l1_ratio': 0.03112545574826081}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24526697284593751
Fold 2 IBS: 0.2335373949546581
Fold 3 IBS: 0.232601298239489
[I 2024-04-21 15:26:02,596] Trial 61 finished with value: 0.23713522201336157 and parameters: {'l1_ratio': 0.09029485779881515}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24695696299341027
Fold 2 IBS: 0.23366826295459048
Fold 3 IBS: 0.2318377766741749
[I 2024-04-21 15:26:02,905] Trial 62 finished with value: 0.23748766754072523 and parameters: {'l1_ratio': 0.1332805801778762}. Best is trial 14 with value: 0.23697501317890082.

Fold 1 IBS: 0.2473183008519733
Fold 2 IBS: 0.27759486992242516
Fold 3 IBS: 0.291502575182032
[I 2024-04-21 15:26:03,406] Trial 63 finished with value: 0.27213858198547686 and parameters: {'l1_ratio': 0.16894030439294788}. Best is trial 14 with value: 0.23697501317890082.
Fold 1 IBS: 0.24493635179953974
Fold 2 IBS: 0.23356967109590185
Fold 3 IBS: 0.2323655010409278
[I 2024-04-21 15:26:03,550] Trial 64 finished with value: 0.2369571746454565 and parameters: {'l1_ratio': 0.10284788949385718}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.24696479523533535
Fold 2 IBS: 0.23347315466846255
Fold 3 IBS: 0.23380345340130332
[I 2024-04-21 15:26:03,740] Trial 65 finished with value: 0.23808046776836708 and parameters: {'l1_ratio': 0.0340532859434732}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.246526863328302
Fold 2 IBS: 0.23357681176987877
Fold 3 IBS: 0.2323193467368943
[I 2024-04-21 15:26:04,128] Trial 66 finished with value: 0.2374743406116917 and parameters: {'l1_ratio': 0.10537525071455828}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.2474994445187203
Fold 2 IBS: 0.2775012966878595
Fold 3 IBS: 0.29126780201044417
[I 2024-04-21 15:26:04,510] Trial 67 finished with value: 0.2720895144056747 and parameters: {'l1_ratio': 0.9415445204645163}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.2474955897496583
Fold 2 IBS: 0.27757643628123
Fold 3 IBS: 0.29153840913863716
[I 2024-04-21 15:26:04,993] Trial 68 finished with value: 0.2722034783898418 and parameters: {'l1_ratio': 0.19274629781515906}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.24754860779178292
Fold 2 IBS: 0.2775419138014422
Fold 3 IBS: 0.2915022497644126
[I 2024-04-21 15:26:05,563] Trial 69 finished with value: 0.27219759045254593 and parameters: {'l1_ratio': 0.2546833801481847}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.2475704476759538
Fold 2 IBS: 0.27758360420782124
Fold 3 IBS: 0.2913817348041993
[I 2024-04-21 15:26:05,886] Trial 70 finished with value: 0.2721785955626581 and parameters: {'l1_ratio': 0.3962928615206238}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.24512635796943133
Fold 2 IBS: 0.23355027022242372
Fold 3 IBS: 0.23250103123906704
[I 2024-04-21 15:26:05,987] Trial 71 finished with value: 0.2370592198103074 and parameters: {'l1_ratio': 0.09556119121157595}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.24702194230733449
Fold 2 IBS: 0.23368792102409217
Fold 3 IBS: 0.23175212114793928
[I 2024-04-21 15:26:06,262] Trial 72 finished with value: 0.23748732815978865 and parameters: {'l1_ratio': 0.13856661036628432}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.24504760290977554
Fold 2 IBS: 0.2335580296267965
Fold 3 IBS: 0.23244485981525828
[I 2024-04-21 15:26:06,510] Trial 73 finished with value: 0.23701683078394345 and parameters: {'l1_ratio': 0.0985572389661225}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.247622442964432
Fold 2 IBS: 0.27758873179232824
Fold 3 IBS: 0.2915471894283837
[I 2024-04-21 15:26:07,054] Trial 74 finished with value: 0.27225278806171466 and parameters: {'l1_ratio': 0.21485370482135757}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.24706743783289078
Fold 2 IBS: 0.23347421741117236
Fold 3 IBS: 0.2338753591045014
[I 2024-04-21 15:26:07,247] Trial 75 finished with value: 0.23813900478285485 and parameters: {'l1_ratio': 0.0310325245273472}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.24697294531652034
Fold 2 IBS: 0.23367297812589458
Fold 3 IBS: 0.23181680214733535
[I 2024-04-21 15:26:07,535] Trial 76 finished with value: 0.2374875751965834 and parameters: {'l1_ratio': 0.13456522687735725}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.2451496065859234
Fold 2 IBS: 0.2335480552796174
Fold 3 IBS: 0.23251761140232857
[I 2024-04-21 15:26:07,924] Trial 77 finished with value: 0.23707175775595646 and parameters: {'l1_ratio': 0.09468319729710768}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.24819112799225704
Fold 2 IBS: 0.23351797709022562
Fold 3 IBS: 0.23465476555338033
[I 2024-04-21 15:26:08,084] Trial 78 finished with value: 0.238787956878621 and parameters: {'l1_ratio': 0.00028261452557712397}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.24756536242110982
Fold 2 IBS: 0.2775254550561171
Fold 3 IBS: 0.29122154707582254
[I 2024-04-21 15:26:08,487] Trial 79 finished with value: 0.27210412151768315 and parameters: {'l1_ratio': 0.6293194462395442}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.2463223150740645
Fold 2 IBS: 0.23347869170696725
Fold 3 IBS: 0.23335104803930945
[I 2024-04-21 15:26:08,682] Trial 80 finished with value: 0.2377173516067804 and parameters: {'l1_ratio': 0.05387220371310491}. Best is trial 64 with value: 0.2369571746454565.
Fold 1 IBS: 0.24490921266158192
Fold 2 IBS: 0.23357263295980923
Fold 3 IBS: 0.23234614117978847
[I 2024-04-21 15:26:08,799] Trial 81 finished with value: 0.23694266226705987 and parameters: {'l1_ratio': 0.10390511312334547}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.24737467027948265
Fold 2 IBS: 0.2775754728772538
Fold 3 IBS: 0.29155059245223564
[I 2024-04-21 15:26:09,270] Trial 82 finished with value: 0.2721669118696574 and parameters: {'l1_ratio': 0.17589099833735905}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.2454404272949783
Fold 2 IBS: 0.23352321343803709
Fold 3 IBS: 0.23272490776933166
[I 2024-04-21 15:26:09,487] Trial 83 finished with value: 0.23722951616744903 and parameters: {'l1_ratio': 0.08394125567619622}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.24684361341151592
Fold 2 IBS: 0.23363854095667064
Fold 3 IBS: 0.23197706854513706
[I 2024-04-21 15:26:09,788] Trial 84 finished with value: 0.2374864076377745 and parameters: {'l1_ratio': 0.12490382219180804}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.24660034899578073
Fold 2 IBS: 0.23358837615686487
Fold 3 IBS: 0.2322480994899165
[I 2024-04-21 15:26:10,275] Trial 85 finished with value: 0.2374789415475207 and parameters: {'l1_ratio': 0.1093241352013806}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.24653008690309594
Fold 2 IBS: 0.23347454312560126
Fold 3 IBS: 0.23349776320402013
[I 2024-04-21 15:26:10,600] Trial 86 finished with value: 0.23783413107757245 and parameters: {'l1_ratio': 0.04728480024208365}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.2456810795850353
Fold 2 IBS: 0.23350657468639185
Fold 3 IBS: 0.23289621556325818
[I 2024-04-21 15:26:10,840] Trial 87 finished with value: 0.23736128994489514 and parameters: {'l1_ratio': 0.07537647863353086}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.2472245144601754
Fold 2 IBS: 0.23376652269547107
Fold 3 IBS: 0.2915449835608955
[I 2024-04-21 15:26:11,239] Trial 88 finished with value: 0.25751200690551396 and parameters: {'l1_ratio': 0.15822244628922566}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.24759099709076263
Fold 2 IBS: 0.2775719797539367
Fold 3 IBS: 0.29148382623833047
[I 2024-04-21 15:26:11,656] Trial 89 finished with value: 0.2722156010276766 and parameters: {'l1_ratio': 0.22599376030766483}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.24710472877858003
Fold 2 IBS: 0.23347473154923457
Fold 3 IBS: 0.23390145576491345
[I 2024-04-21 15:26:11,848] Trial 90 finished with value: 0.2381603053642427 and parameters: {'l1_ratio': 0.029944471655637434}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.2453014053145266
Fold 2 IBS: 0.23353443148911976
Fold 3 IBS: 0.23262584323343194
[I 2024-04-21 15:26:12,069] Trial 91 finished with value: 0.23715389334569278 and parameters: {'l1_ratio': 0.08902124154273042}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.2465143102403363
Fold 2 IBS: 0.23357495102057432
Fold 3 IBS: 0.23233120462032641
[I 2024-04-21 15:26:12,361] Trial 92 finished with value: 0.23747348862707898 and parameters: {'l1_ratio': 0.10472364545419789}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.247079445589322
Fold 2 IBS: 0.23370701222545656
Fold 3 IBS: 0.2316731033230198
[I 2024-04-21 15:26:12,721] Trial 93 finished with value: 0.23748652037926613 and parameters: {'l1_ratio': 0.14353879734168012}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.24617974355195016
Fold 2 IBS: 0.2334828905184152
Fold 3 IBS: 0.2332501690072579
[I 2024-04-21 15:26:12,879] Trial 94 finished with value: 0.23763760102587442 and parameters: {'l1_ratio': 0.058496378462167015}. Best is trial 81 with value: 0.23694266226705987.

Fold 1 IBS: 0.24751890505038296
Fold 2 IBS: 0.277581505409534
Fold 3 IBS: 0.2915607477694774
[I 2024-04-21 15:26:13,400] Trial 95 finished with value: 0.27222038607646476 and parameters: {'l1_ratio': 0.19634020969378}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.24673406364790046
Fold 2 IBS: 0.2336140106263108
Fold 3 IBS: 0.23210292905826285
[I 2024-04-21 15:26:13,664] Trial 96 finished with value: 0.23748366777749133 and parameters: {'l1_ratio': 0.11755546648562562}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.2473348142267078
Fold 2 IBS: 0.2775518986735307
Fold 3 IBS: 0.2915166637703804
[I 2024-04-21 15:26:14,113] Trial 97 finished with value: 0.2721344588902063 and parameters: {'l1_ratio': 0.17092443812719485}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.24756210841779558
Fold 2 IBS: 0.2775473570094509
Fold 3 IBS: 0.2914778967125745
[I 2024-04-21 15:26:14,701] Trial 98 finished with value: 0.2721957873799403 and parameters: {'l1_ratio': 0.27733084712575967}. Best is trial 81 with value: 0.23694266226705987.
Fold 1 IBS: 0.24752711857707846
Fold 2 IBS: 0.23348519393689426
Fold 3 IBS: 0.2341959873809719
[I 2024-04-21 15:26:14,829] Trial 99 finished with value: 0.2384027666316482 and parameters: {'l1_ratio': 0.017957946995767693}. Best is trial 81 with value: 0.23694266226705987.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.23694266226705987], datetime_start=datetime.datetime(2024, 4, 21, 15, 26, 8, 689312), datetime_complete=datetime.datetime(2024, 4, 21, 15, 26, 8, 798999), params={'l1_ratio': 0.10390511312334547}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=81, value=None)


* Best Score for IBS:
 0.23694266226705987

In [51]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [52]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.606
train_ibs:  0.237

#### Test

In [53]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [54]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.1015556329868651)

test_cindex : 0.657

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.10390511312334547)

test_ibs:  0.219

In [55]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [56]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-21 15:26:15,269] A new study created in memory with name: no-name-52926fcb-c3c9-4067-a49b-bf5a9cfd7abb

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.5349593495934959
Fold 3 C-index: 0.5495810055865922
[I 2024-04-21 15:26:18,179] Trial 0 finished with value: 0.5646589301015322 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.5646589301015322.
Fold 1 C-index: 0.6081258191349934
Fold 2 C-index: 0.5414634146341464
Fold 3 C-index: 0.5614525139664804
[I 2024-04-21 15:26:19,924] Trial 1 finished with value: 0.5703472492452067 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.5703472492452067.
Fold 1 C-index: 0.6159895150720839
Fold 2 C-index: 0.5447154471544715
Fold 3 C-index: 0.5558659217877095
[I 2024-04-21 15:26:21,943] Trial 2 finished with value: 0.5721902946714216 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 2 with value: 0.5721902946714216.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:23,027] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 2 with value: 0.5721902946714216.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:24,314] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 2 with value: 0.5721902946714216.
Fold 1 C-index: 0.6186107470511141
Fold 2 C-index: 0.5333333333333333
Fold 3 C-index: 0.5614525139664804
[I 2024-04-21 15:26:27,171] Trial 5 finished with value: 0.571132198116976 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 2 with value: 0.5721902946714216.
Fold 1 C-index: 0.6186107470511141
Fold 2 C-index: 0.5203252032520326
Fold 3 C-index: 0.5544692737430168
[I 2024-04-21 15:26:30,471] Trial 6 finished with value: 0.5644684080153878 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 2 with value: 0.5721902946714216.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:32,216] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 2 with value: 0.5721902946714216.
Fold 1 C-index: 0.6009174311926605
Fold 2 C-index: 0.41544715447154473
Fold 3 C-index: 0.50768156424581
[I 2024-04-21 15:26:36,459] Trial 8 finished with value: 0.5080153833033384 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 2 with value: 0.5721902946714216.
Fold 1 C-index: 0.6068152031454783
Fold 2 C-index: 0.5170731707317073
Fold 3 C-index: 0.5740223463687151
[I 2024-04-21 15:26:38,736] Trial 9 finished with value: 0.565970240081967 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 2 with value: 0.5721902946714216.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:39,033] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 26, 'oob_score': True, 'max_samples': 0.9607577284547746, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 2 with value: 0.5721902946714216.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:40,187] Trial 11 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.11379276107227315, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14507778190604323, 'warm_start': False}. Best is trial 2 with value: 0.5721902946714216.
Fold 1 C-index: 0.6055045871559633
Fold 2 C-index: 0.5430894308943089
Fold 3 C-index: 0.5460893854748603
[I 2024-04-21 15:26:42,076] Trial 12 finished with value: 0.5648944678417108 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.8397501717174567, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1526809711702289, 'warm_start': False}. Best is trial 2 with value: 0.5721902946714216.
Fold 1 C-index: 0.6107470511140236
Fold 2 C-index: 0.551219512195122
Fold 3 C-index: 0.5572625698324022
[I 2024-04-21 15:26:45,170] Trial 13 finished with value: 0.5730763777138493 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.4777069141417742, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08255864378493685, 'warm_start': False}. Best is trial 13 with value: 0.5730763777138493.
Fold 1 C-index: 0.6199213630406291
Fold 2 C-index: 0.7723577235772358
Fold 3 C-index: 0.702513966480447
[I 2024-04-21 15:26:47,795] Trial 14 finished with value: 0.6982643510327705 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 482, 'oob_score': True, 'max_samples': 0.433652139551181, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09639289018164084, 'warm_start': True}. Best is trial 14 with value: 0.6982643510327705.
Fold 1 C-index: 0.617300131061599
Fold 2 C-index: 0.7707317073170732
Fold 3 C-index: 0.7011173184357542
[I 2024-04-21 15:26:50,056] Trial 15 finished with value: 0.6963830522714755 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 480, 'oob_score': True, 'max_samples': 0.4470849120697906, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08807762154599924, 'warm_start': True}. Best is trial 14 with value: 0.6982643510327705.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:53,058] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.36871324569404207, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20791692251205332, 'warm_start': True}. Best is trial 14 with value: 0.6982643510327705.
Fold 1 C-index: 0.6146788990825688

Fold 2 C-index: 0.7707317073170732
Fold 3 C-index: 0.6815642458100558
[I 2024-04-21 15:26:55,634] Trial 17 finished with value: 0.6889916174032326 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 493, 'oob_score': True, 'max_samples': 0.4399216700525951, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09373644341192987, 'warm_start': True}. Best is trial 14 with value: 0.6982643510327705.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:58,461] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.20703029814340784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.6982643510327705.
Fold 1 C-index: 0.6041939711664482
Fold 2 C-index: 0.8373983739837398
Fold 3 C-index: 0.7793296089385475
[I 2024-04-21 15:27:00,486] Trial 19 finished with value: 0.7403073180295786 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 388, 'oob_score': True, 'max_samples': 0.5423771062394208, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004060792657387402, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6146788990825688
Fold 2 C-index: 0.7252032520325203
Fold 3 C-index: 0.6822625698324022
[I 2024-04-21 15:27:02,380] Trial 20 finished with value: 0.6740482403158304 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 367, 'oob_score': True, 'max_samples': 0.5530588908263404, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012087063184877466, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6146788990825688
Fold 2 C-index: 0.7804878048780488
Fold 3 C-index: 0.7192737430167597
[I 2024-04-21 15:27:05,161] Trial 21 finished with value: 0.7048134823257923 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 448, 'oob_score': True, 'max_samples': 0.3827398795249307, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06653459871996206, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.617300131061599
Fold 2 C-index: 0.7983739837398374
Fold 3 C-index: 0.744413407821229
[I 2024-04-21 15:27:07,420] Trial 22 finished with value: 0.7200291742075552 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 418, 'oob_score': True, 'max_samples': 0.35978174093007026, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004515640558089534, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6081258191349934
Fold 2 C-index: 0.7886178861788617
Fold 3 C-index: 0.7374301675977654
[I 2024-04-21 15:27:09,766] Trial 23 finished with value: 0.7113912909705401 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 413, 'oob_score': True, 'max_samples': 0.3390588888758544, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0023497522601186316, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6251638269986893
Fold 2 C-index: 0.7707317073170732
Fold 3 C-index: 0.7081005586592178
[I 2024-04-21 15:27:11,418] Trial 24 finished with value: 0.7013320309916602 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 416, 'oob_score': True, 'max_samples': 0.29362935445915617, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.000915194069883368, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6304062909567497
Fold 2 C-index: 0.7642276422764228
Fold 3 C-index: 0.6843575418994413
[I 2024-04-21 15:27:13,057] Trial 25 finished with value: 0.692997158377538 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.18218723946592258, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.039270222540159716, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:27:15,152] Trial 26 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 401, 'oob_score': True, 'max_samples': 0.5349306463888053, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4461128531136588, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6199213630406291
Fold 2 C-index: 0.734959349593496
Fold 3 C-index: 0.6745810055865922
[I 2024-04-21 15:27:17,283] Trial 27 finished with value: 0.6764872394069057 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 385, 'oob_score': True, 'max_samples': 0.3608316225627856, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13032023790041442, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.617300131061599
Fold 2 C-index: 0.7837398373983739
Fold 3 C-index: 0.723463687150838
[I 2024-04-21 15:27:19,025] Trial 28 finished with value: 0.7081678852036036 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.5360953547457009, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05407339588540153, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6146788990825688
Fold 2 C-index: 0.7382113821138211
Fold 3 C-index: 0.6787709497206704
[I 2024-04-21 15:27:20,883] Trial 29 finished with value: 0.6772204103056868 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 364, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19553674711816893, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6055045871559633
Fold 2 C-index: 0.734959349593496
Fold 3 C-index: 0.6703910614525139
[I 2024-04-21 15:27:22,486] Trial 30 finished with value: 0.6702849994006578 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 228, 'oob_score': True, 'max_samples': 0.7514461300183424, 'max_features': None, 'min_weight_fraction_leaf': 0.2486312042554125, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6225425950196593
Fold 2 C-index: 0.7772357723577236
Fold 3 C-index: 0.696927374301676
[I 2024-04-21 15:27:24,458] Trial 31 finished with value: 0.6989019138930196 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 327, 'oob_score': True, 'max_samples': 0.5378271292843333, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04816560919159098, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6199213630406291
Fold 2 C-index: 0.8146341463414634
Fold 3 C-index: 0.7472067039106145
[I 2024-04-21 15:27:26,406] Trial 32 finished with value: 0.727254071097569 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 429, 'oob_score': True, 'max_samples': 0.5141459077997168, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.006554858278593208, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6133682830930537
Fold 2 C-index: 0.7804878048780488
Fold 3 C-index: 0.729050279329609
[I 2024-04-21 15:27:28,598] Trial 33 finished with value: 0.7076354557669037 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 433, 'oob_score': True, 'max_samples': 0.2992801747664094, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0013400478952701146, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.

Fold 1 C-index: 0.6225425950196593
Fold 2 C-index: 0.7398373983739838
Fold 3 C-index: 0.6857541899441341
[I 2024-04-21 15:27:30,509] Trial 34 finished with value: 0.6827113944459257 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 378, 'oob_score': True, 'max_samples': 0.3921322757689111, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11898813720646406, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.7967479674796748
Fold 3 C-index: 0.7402234636871509
[I 2024-04-21 15:27:33,136] Trial 35 finished with value: 0.715469288763778 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 419, 'oob_score': True, 'max_samples': 0.6846754529760358, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03214075386929217, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6146788990825688
Fold 2 C-index: 0.7609756097560976
Fold 3 C-index: 0.6983240223463687
[I 2024-04-21 15:27:35,597] Trial 36 finished with value: 0.6913261770616783 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 457, 'oob_score': True, 'max_samples': 0.8220079592879557, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1754861578915471, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6159895150720839
Fold 2 C-index: 0.7430894308943089
Fold 3 C-index: 0.672486033519553
[I 2024-04-21 15:27:36,772] Trial 37 finished with value: 0.6771883264953154 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.6757775079647574, 'max_features': None, 'min_weight_fraction_leaf': 0.033797338412273614, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6225425950196593
Fold 2 C-index: 0.7821138211382114
Fold 3 C-index: 0.7094972067039106
[I 2024-04-21 15:27:39,001] Trial 38 finished with value: 0.7047178742872604 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 431, 'oob_score': True, 'max_samples': 0.6351516064838247, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06707868557855305, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6186107470511141
Fold 2 C-index: 0.7333333333333333
Fold 3 C-index: 0.6787709497206704
[I 2024-04-21 15:27:40,779] Trial 39 finished with value: 0.6769050100350392 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 9, 'n_estimators': 346, 'oob_score': True, 'max_samples': 0.5878528984279388, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.028983205480309443, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6290956749672346
Fold 2 C-index: 0.7479674796747967
Fold 3 C-index: 0.702513966480447
[I 2024-04-21 15:27:42,826] Trial 40 finished with value: 0.6931923737074928 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.49697249076491434, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11000653668285652, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6159895150720839
Fold 2 C-index: 0.8130081300813008
Fold 3 C-index: 0.7304469273743017
[I 2024-04-21 15:27:45,275] Trial 41 finished with value: 0.7198148575092288 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 408, 'oob_score': True, 'max_samples': 0.767837172322005, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0003299582276431708, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
Fold 1 C-index: 0.6251638269986893
Fold 2 C-index: 0.8097560975609757
Fold 3 C-index: 0.723463687150838
[I 2024-04-21 15:27:47,376] Trial 42 finished with value: 0.7194612039035011 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 397, 'oob_score': True, 'max_samples': 0.732528301981742, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.038466017647751684, 'warm_start': True}. Best is trial 19 with value: 0.7403073180295786.
[W 2024-04-21 15:27:48,479] Trial 43 failed with parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 388, 'oob_score': True, 'max_samples': 0.8547543598751837, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05935178764224234, 'warm_start': True} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/var/folders/64/jkqp6xyx2hj50dmd2pqfm3780000gn/T/ipykernel_41701/1474426952.py", line 56, in objective
    model.fit(X_train, y_train)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/ensemble/forest.py", line 167, in fit
    self._set_oob_score_and_attributes(X, (event, time))
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/ensemble/forest.py", line 182, in _set_oob_score_and_attributes
    unsampled_indices = _generate_unsampled_indices(estimator.random_state, n_samples, n_samples_bootstrap)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 136, in _generate_unsampled_indices
    sample_indices = _generate_sample_indices(
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 128, in _generate_sample_indices
    sample_indices = random_instance.randint(0, n_samples, n_samples_bootstrap)
  File "mtrand.pyx", line 765, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1228, in numpy.random._bounded_integers._rand_int64
  File "<__array_function__ internals>", line 179, in prod
KeyboardInterrupt
[W 2024-04-21 15:27:48,484] Trial 43 failed with value None.

KeyboardInterrupt:

In [ ]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [ ]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

#### Test

In [ ]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

In [ ]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

In [ ]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [ ]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [ ]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

In [ ]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [ ]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

#### Test

In [ ]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [ ]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

In [ ]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [ ]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

In [ ]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [ ]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

#### Test

In [ ]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [ ]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

In [ ]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

### Example

In [61]:
# Min Max Standardization
excluded_columns = ['female', 
                    'cavum_oris',
                    'oropharynx',
                    'hypopharynx',
                    'larynx',
                    'histgrade_high',
                    'hpv_related',
                    'charlson',
                    'uicc8_III-IV'
                   ]
excluded_columns = set(excluded_columns).intersection(X.columns)

scaler = MinMaxScaler() 
X_train_included = X.drop(excluded_columns, axis=1)
X_test_included = X.drop(excluded_columns, axis=1)

In [63]:
X_train_included_std = scaler.fit_transform(X_train_included)
X_test_included_std = scaler.transform(X_test_included)

# Concatenation
X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
X_train_std = pd.concat([X_train_std_df, X[excluded_columns]], axis=1)

X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
X_test_std = pd.concat([X_test_std_df, X[excluded_columns]], axis=1)

In [84]:
X_std = X_train_std[X.columns]
MAASTRO_std = MAASTRO_new_std[X.columns]

In [85]:
model_with_standardization = ComponentwiseGradientBoostingSurvivalAnalysis().fit(X_std, y)

In [106]:
model_with_standardization.score(X_std, y)

0.6724952741020794

In [86]:
model_with_standardization.score(MAASTRO_std, y_MAASTRO)

0.6006072315760419

In [94]:
lower, upper = np.percentile(y["time"], [10, 90])    
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in model_with_standardization.predict_survival_function(X_std)])
train_ibs = integrated_brier_score(y, y, surv_prob, times)

In [95]:
train_ibs

0.20730354536745163

In [98]:
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in model_with_standardization.predict_survival_function(MAASTRO_std)])
test_ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)

In [99]:
test_ibs

0.2229850398004809

In [87]:
model_without_standardization = ComponentwiseGradientBoostingSurvivalAnalysis().fit(X, y)

In [107]:
model_without_standardization.score(X, y)

0.6704473850031506

In [88]:
model_without_standardization.score(MAASTRO_std, y_MAASTRO)

0.6008832459287883

In [102]:
lower, upper = np.percentile(y["time"], [10, 90])    
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in model_without_standardization.predict_survival_function(X)])
train_ibs = integrated_brier_score(y, y, surv_prob, times)

In [103]:
train_ibs

0.20732804667906002

In [104]:
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in model_without_standardization.predict_survival_function(MAASTRO_std)])
test_ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)

In [105]:
test_ibs

0.21451862790761217

#### Train

In [45]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [46]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-29 14:32:34,845] A new study created in memory with name: no-name-96dde80c-105e-46ae-9f07-22e63893577c

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:32:35,208] Trial 0 finished with value: 0.5917375988906803 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.5917375988906803.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:32:37,808] Trial 1 finished with value: 0.5925959679893928 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.5925959679893928.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:32:38,327] Trial 2 finished with value: 0.6169187787301008 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6169187787301008.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:32:39,032] Trial 3 finished with value: 0.6118852688880276 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 2 with value: 0.6169187787301008.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:32:40,113] Trial 4 finished with value: 0.6163104260787672 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 2 with value: 0.6169187787301008.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:32:41,418] Trial 5 finished with value: 0.5917375988906803 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 2 with value: 0.6169187787301008.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:32:41,971] Trial 6 finished with value: 0.5836524925077017 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 2 with value: 0.6169187787301008.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:32:42,090] Trial 7 finished with value: 0.6285089200658984 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.6285089200658984.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:32:42,776] Trial 8 finished with value: 0.6199796693684592 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.6285089200658984.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:32:44,744] Trial 9 finished with value: 0.6333466042580751 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6330472103004292
[I 2024-04-29 14:32:46,663] Trial 10 finished with value: 0.596178251045648 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.9974588415748801, 'n_estimators': 496, 'learning_rate': 0.0017980531969980576}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.592274678111588
[I 2024-04-29 14:32:46,714] Trial 11 finished with value: 0.6187057282661599 and parameters: {'subsample': 0.26668511746186646, 'dropout_rate': 0.7360931942627206, 'n_estimators': 2, 'learning_rate': 0.034819034386896125}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5872093023255814
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.630901287553648
[I 2024-04-29 14:32:48,181] Trial 12 finished with value: 0.6275955068409018 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.7296362277562352, 'n_estimators': 362, 'learning_rate': 0.09635955935176935}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:32:48,256] Trial 13 finished with value: 0.6040881965002421 and parameters: {'subsample': 0.33530776187821976, 'dropout_rate': 0.6940092509565362, 'n_estimators': 15, 'learning_rate': 0.03991849491763092}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:32:49,525] Trial 14 finished with value: 0.6263386100235417 and parameters: {'subsample': 0.3893805243616632, 'dropout_rate': 0.9730279893705664, 'n_estimators': 363, 'learning_rate': 0.01791870825658054}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5717131474103586
Fold 2 C-index: 0.5930232558139535
Fold 3 C-index: 0.6702127659574468
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6072961373390557
[I 2024-04-29 14:32:49,789] Trial 15 finished with value: 0.6230498217604368 and parameters: {'subsample': 0.10918709550572847, 'dropout_rate': 0.8305759135888928, 'n_estimators': 98, 'learning_rate': 0.09120122964379646}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:32:50,738] Trial 16 finished with value: 0.6076290717588975 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8492264743849203, 'n_estimators': 287, 'learning_rate': 0.04598722598855341}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:32:52,741] Trial 17 finished with value: 0.6250869303273767 and parameters: {'subsample': 0.4155100194114116, 'dropout_rate': 0.6305980452911516, 'n_estimators': 434, 'learning_rate': 0.01332075085976523}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5484496124031008
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:32:52,993] Trial 18 finished with value: 0.6191623819104469 and parameters: {'subsample': 0.2404909215582987, 'dropout_rate': 0.5949219817214475, 'n_estimators': 94, 'learning_rate': 0.02957852949596903}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5358565737051793

Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:32:53,948] Trial 19 finished with value: 0.5944615128482231 and parameters: {'subsample': 0.94616158758761, 'dropout_rate': 0.8841892013974624, 'n_estimators': 299, 'learning_rate': 0.04531699534196399}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:32:55,685] Trial 20 finished with value: 0.6302458290642766 and parameters: {'subsample': 0.6004927729383457, 'dropout_rate': 0.7859448591953863, 'n_estimators': 423, 'learning_rate': 0.08455215126922011}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:32:57,496] Trial 21 finished with value: 0.6302458290642766 and parameters: {'subsample': 0.5907627994085279, 'dropout_rate': 0.7677146901506173, 'n_estimators': 429, 'learning_rate': 0.08378033085212148}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:32:59,246] Trial 22 finished with value: 0.6199796693684592 and parameters: {'subsample': 0.6130365812268096, 'dropout_rate': 0.7878993761899368, 'n_estimators': 428, 'learning_rate': 0.08137284055580261}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6191489361702127
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:33:01,062] Trial 23 finished with value: 0.5874895850106695 and parameters: {'subsample': 0.8371790397595579, 'dropout_rate': 0.7781194596096047, 'n_estimators': 436, 'learning_rate': 0.08296216960279851}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:02,527] Trial 24 finished with value: 0.6020037585864978 and parameters: {'subsample': 0.5744248017807753, 'dropout_rate': 0.9473848068987546, 'n_estimators': 408, 'learning_rate': 0.08493915002955284}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:04,372] Trial 25 finished with value: 0.6333466042580751 and parameters: {'subsample': 0.4835195206554261, 'dropout_rate': 0.9095533698822077, 'n_estimators': 466, 'learning_rate': 0.09925386589416407}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:06,264] Trial 26 finished with value: 0.6257420415204326 and parameters: {'subsample': 0.4706115922650663, 'dropout_rate': 0.939206446437569, 'n_estimators': 478, 'learning_rate': 0.09970843320100516}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:33:07,391] Trial 27 finished with value: 0.5994044786276908 and parameters: {'subsample': 0.8537275557988595, 'dropout_rate': 0.8629244963372316, 'n_estimators': 329, 'learning_rate': 0.062452263137606254}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:08,815] Trial 28 finished with value: 0.6333466042580751 and parameters: {'subsample': 0.4580922583745428, 'dropout_rate': 0.915420568483159, 'n_estimators': 390, 'learning_rate': 0.09257491837484622}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:10,661] Trial 29 finished with value: 0.6234923301564214 and parameters: {'subsample': 0.4088139678446021, 'dropout_rate': 0.9229802088935769, 'n_estimators': 461, 'learning_rate': 0.09313551007868115}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:12,083] Trial 30 finished with value: 0.6333466042580751 and parameters: {'subsample': 0.46403188552946023, 'dropout_rate': 0.9028550420583699, 'n_estimators': 387, 'learning_rate': 0.09108366527308882}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:13,477] Trial 31 finished with value: 0.6302458290642766 and parameters: {'subsample': 0.5275316461752884, 'dropout_rate': 0.9028506099828228, 'n_estimators': 384, 'learning_rate': 0.0914502447084542}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:15,401] Trial 32 finished with value: 0.6324955404282878 and parameters: {'subsample': 0.4596662729139495, 'dropout_rate': 0.8271972707746725, 'n_estimators': 458, 'learning_rate': 0.09956618331863945}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:16,392] Trial 33 finished with value: 0.6287838666154896 and parameters: {'subsample': 0.33490575688432245, 'dropout_rate': 0.9909646276822889, 'n_estimators': 319, 'learning_rate': 0.07575532507259901}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:17,826] Trial 34 finished with value: 0.5917375988906803 and parameters: {'subsample': 0.6914435886010033, 'dropout_rate': 0.9179007604906197, 'n_estimators': 394, 'learning_rate': 0.06458467646946925}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:33:20,444] Trial 35 finished with value: 0.6334445170830234 and parameters: {'subsample': 0.44531889703598726, 'dropout_rate': 0.24256424325009796, 'n_estimators': 466, 'learning_rate': 0.07769390620391867}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:23,422] Trial 36 finished with value: 0.617895231454715 and parameters: {'subsample': 0.5482914616062043, 'dropout_rate': 0.17394652066354216, 'n_estimators': 500, 'learning_rate': 0.07698745430230036}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:26,017] Trial 37 finished with value: 0.6169729695275832 and parameters: {'subsample': 0.2919869892037661, 'dropout_rate': 0.27240135656739795, 'n_estimators': 465, 'learning_rate': 0.06866137066822686}. Best is trial 35 with value: 0.6334445170830234.

Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.5872093023255814
Fold 3 C-index: 0.6574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6223175965665236
[I 2024-04-29 14:33:28,761] Trial 38 finished with value: 0.6255980953653896 and parameters: {'subsample': 0.21215961579513323, 'dropout_rate': 0.10587583963863223, 'n_estimators': 461, 'learning_rate': 0.08947938084969637}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:33:31,396] Trial 39 finished with value: 0.6218543757472259 and parameters: {'subsample': 0.5197301963671256, 'dropout_rate': 0.443442876832168, 'n_estimators': 479, 'learning_rate': 0.05598015324329953}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:33:32,868] Trial 40 finished with value: 0.6319236045354948 and parameters: {'subsample': 0.4333162275483842, 'dropout_rate': 0.3134382757783408, 'n_estimators': 333, 'learning_rate': 0.06938556641513953}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:33:34,671] Trial 41 finished with value: 0.6266004106191451 and parameters: {'subsample': 0.4580197074902786, 'dropout_rate': 0.4905332360753627, 'n_estimators': 399, 'learning_rate': 0.08759534101843505}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:35,516] Trial 42 finished with value: 0.6202355503747491 and parameters: {'subsample': 0.5015921178319339, 'dropout_rate': 0.3744428196464323, 'n_estimators': 237, 'learning_rate': 0.09512438255680897}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6072961373390557
[I 2024-04-29 14:33:36,892] Trial 43 finished with value: 0.628490128140645 and parameters: {'subsample': 0.36451654530625793, 'dropout_rate': 0.9623620551781862, 'n_estimators': 368, 'learning_rate': 0.07868097391060797}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:38,685] Trial 44 finished with value: 0.6234606726991399 and parameters: {'subsample': 0.4393477685625992, 'dropout_rate': 0.8826594435645295, 'n_estimators': 439, 'learning_rate': 0.09609837580585855}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:40,226] Trial 45 finished with value: 0.6040881965002421 and parameters: {'subsample': 0.6664141085861768, 'dropout_rate': 0.6955826237235475, 'n_estimators': 379, 'learning_rate': 0.0730581077647751}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:33:41,878] Trial 46 finished with value: 0.6234090278693236 and parameters: {'subsample': 0.3158405134078406, 'dropout_rate': 0.8137330326312415, 'n_estimators': 409, 'learning_rate': 0.05378014293554952}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:33:42,280] Trial 47 finished with value: 0.6266004106191451 and parameters: {'subsample': 0.3784498077489041, 'dropout_rate': 0.5395824878315594, 'n_estimators': 144, 'learning_rate': 0.08923404889365179}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:33:43,951] Trial 48 finished with value: 0.6226295695456755 and parameters: {'subsample': 0.55325915712633, 'dropout_rate': 0.19701471782839963, 'n_estimators': 356, 'learning_rate': 0.05861896898090731}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:46,215] Trial 49 finished with value: 0.6302458290642766 and parameters: {'subsample': 0.4901311086166668, 'dropout_rate': 0.7204182616763216, 'n_estimators': 486, 'learning_rate': 0.04897928524498507}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:48,287] Trial 50 finished with value: 0.6233848026678022 and parameters: {'subsample': 0.41708075313112536, 'dropout_rate': 0.633091953438621, 'n_estimators': 450, 'learning_rate': 0.09949481545474731}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:50,209] Trial 51 finished with value: 0.6333466042580751 and parameters: {'subsample': 0.48466115285788897, 'dropout_rate': 0.8401417311455619, 'n_estimators': 465, 'learning_rate': 0.0981096791431336}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:52,316] Trial 52 finished with value: 0.6302458290642766 and parameters: {'subsample': 0.49512310203124366, 'dropout_rate': 0.8609586862191965, 'n_estimators': 498, 'learning_rate': 0.09450261609212947}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:54,247] Trial 53 finished with value: 0.6302458290642766 and parameters: {'subsample': 0.5578892677025309, 'dropout_rate': 0.9007833762106524, 'n_estimators': 477, 'learning_rate': 0.0871679443055628}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:55,695] Trial 54 finished with value: 0.6213836035477381 and parameters: {'subsample': 0.521710382050243, 'dropout_rate': 0.9736948300445848, 'n_estimators': 411, 'learning_rate': 0.08075559248658083}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:57,537] Trial 55 finished with value: 0.6210297462230827 and parameters: {'subsample': 0.38327187982719807, 'dropout_rate': 0.8417918999407158, 'n_estimators': 447, 'learning_rate': 0.04074088877140331}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:33:59,300] Trial 56 finished with value: 0.6257420415204326 and parameters: {'subsample': 0.45737775071266046, 'dropout_rate': 0.9963237289189165, 'n_estimators': 473, 'learning_rate': 0.09195935060664122}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881

Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:34:00,208] Trial 57 finished with value: 0.6250036280402789 and parameters: {'subsample': 0.34184923620281193, 'dropout_rate': 0.7514083736999361, 'n_estimators': 275, 'learning_rate': 0.0962753174063995}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:01,459] Trial 58 finished with value: 0.6199796693684592 and parameters: {'subsample': 0.6322857938769479, 'dropout_rate': 0.8098457293410719, 'n_estimators': 349, 'learning_rate': 0.008015117479355321}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:03,032] Trial 59 finished with value: 0.6218808100528699 and parameters: {'subsample': 0.41099901538954614, 'dropout_rate': 0.9376522301752482, 'n_estimators': 422, 'learning_rate': 0.08582237707487823}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:04,039] Trial 60 finished with value: 0.617895231454715 and parameters: {'subsample': 0.5834238782297296, 'dropout_rate': 0.8847381836936404, 'n_estimators': 310, 'learning_rate': 0.07200825617838875}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:05,911] Trial 61 finished with value: 0.6324955404282878 and parameters: {'subsample': 0.468074975245373, 'dropout_rate': 0.8078749939892612, 'n_estimators': 450, 'learning_rate': 0.09987183274298513}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:07,793] Trial 62 finished with value: 0.6279328027857023 and parameters: {'subsample': 0.4459929498180515, 'dropout_rate': 0.8446120740546745, 'n_estimators': 455, 'learning_rate': 0.0981375837099892}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:09,451] Trial 63 finished with value: 0.6272629540679612 and parameters: {'subsample': 0.49475976591218823, 'dropout_rate': 0.9246389934003018, 'n_estimators': 427, 'learning_rate': 0.0921893290190942}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:11,245] Trial 64 finished with value: 0.6232061773724616 and parameters: {'subsample': 0.39362353258382193, 'dropout_rate': 0.41432754919668213, 'n_estimators': 386, 'learning_rate': 0.09435530424930684}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:13,246] Trial 65 finished with value: 0.6302458290642766 and parameters: {'subsample': 0.518365083594319, 'dropout_rate': 0.8821466697143764, 'n_estimators': 487, 'learning_rate': 0.08945126736418482}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:15,061] Trial 66 finished with value: 0.6325861479843109 and parameters: {'subsample': 0.4293752760449414, 'dropout_rate': 0.9469712074728804, 'n_estimators': 469, 'learning_rate': 0.09719398976668467}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:34:15,785] Trial 67 finished with value: 0.6310725407057076 and parameters: {'subsample': 0.35395021550175254, 'dropout_rate': 0.9596421474388831, 'n_estimators': 252, 'learning_rate': 0.08133521219022932}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:17,723] Trial 68 finished with value: 0.6202355503747491 and parameters: {'subsample': 0.5489809203214004, 'dropout_rate': 0.9481455402573654, 'n_estimators': 473, 'learning_rate': 0.025894154109747592}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:19,437] Trial 69 finished with value: 0.620834200995146 and parameters: {'subsample': 0.30408705791464463, 'dropout_rate': 0.9179794531827897, 'n_estimators': 443, 'learning_rate': 0.09733555388420824}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:20,935] Trial 70 finished with value: 0.6325861479843109 and parameters: {'subsample': 0.4242133168164634, 'dropout_rate': 0.9976976182810481, 'n_estimators': 415, 'learning_rate': 0.03629572257612829}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:22,431] Trial 71 finished with value: 0.6272629540679612 and parameters: {'subsample': 0.43604903349867147, 'dropout_rate': 0.9851375372329585, 'n_estimators': 417, 'learning_rate': 0.034353732853907054}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:23,876] Trial 72 finished with value: 0.6333466042580751 and parameters: {'subsample': 0.47706659622991343, 'dropout_rate': 0.9008022632021113, 'n_estimators': 399, 'learning_rate': 0.01863914574567756}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:25,329] Trial 73 finished with value: 0.6333466042580751 and parameters: {'subsample': 0.4676279726411465, 'dropout_rate': 0.9032542276803975, 'n_estimators': 400, 'learning_rate': 0.01836490073600064}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:26,479] Trial 74 finished with value: 0.6333466042580751 and parameters: {'subsample': 0.47477829709492614, 'dropout_rate': 0.8953820065852706, 'n_estimators': 342, 'learning_rate': 0.021234912943109197}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:27,822] Trial 75 finished with value: 0.6302458290642766 and parameters: {'subsample': 0.5097860993166521, 'dropout_rate': 0.8641455655860409, 'n_estimators': 373, 'learning_rate': 0.028718757370599077}. Best is trial 35 with value: 0.6334445170830234.

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:29,221] Trial 76 finished with value: 0.6333466042580751 and parameters: {'subsample': 0.47979947406257184, 'dropout_rate': 0.9138368438312081, 'n_estimators': 393, 'learning_rate': 0.01502937554803389}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:30,779] Trial 77 finished with value: 0.6199796693684592 and parameters: {'subsample': 0.6220199290489004, 'dropout_rate': 0.7976756811047483, 'n_estimators': 398, 'learning_rate': 0.009084837049577743}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:34:33,105] Trial 78 finished with value: 0.6334445170830234 and parameters: {'subsample': 0.39884438832836855, 'dropout_rate': 0.3250540209025817, 'n_estimators': 433, 'learning_rate': 0.01988051594267265}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:34:35,909] Trial 79 finished with value: 0.626345915292467 and parameters: {'subsample': 0.3906558958520373, 'dropout_rate': 0.26000337891521685, 'n_estimators': 486, 'learning_rate': 0.021858681096337092}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:34:38,307] Trial 80 finished with value: 0.6218543757472259 and parameters: {'subsample': 0.5443059841954937, 'dropout_rate': 0.1835064275776629, 'n_estimators': 435, 'learning_rate': 0.007039353779474462}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:40,679] Trial 81 finished with value: 0.6143543561960596 and parameters: {'subsample': 0.4564377289174783, 'dropout_rate': 0.24002660459981268, 'n_estimators': 404, 'learning_rate': 0.019319330961316435}. Best is trial 35 with value: 0.6334445170830234.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:34:43,114] Trial 82 finished with value: 0.6350560371865749 and parameters: {'subsample': 0.40435140119451696, 'dropout_rate': 0.23864048613297553, 'n_estimators': 433, 'learning_rate': 0.014343382745774179}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:34:45,375] Trial 83 finished with value: 0.6240645464711742 and parameters: {'subsample': 0.36424955055836916, 'dropout_rate': 0.30041751871331024, 'n_estimators': 437, 'learning_rate': 0.0132539347530204}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:34:45,501] Trial 84 finished with value: 0.6040028120958567 and parameters: {'subsample': 0.4046689152865726, 'dropout_rate': 0.2340209828405782, 'n_estimators': 44, 'learning_rate': 0.005007580249064832}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:47,996] Trial 85 finished with value: 0.6209960066485134 and parameters: {'subsample': 0.5181815818508807, 'dropout_rate': 0.32148056607373166, 'n_estimators': 460, 'learning_rate': 0.011648288546854551}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:51,049] Trial 86 finished with value: 0.6143543561960596 and parameters: {'subsample': 0.5671560026388924, 'dropout_rate': 0.11543197286879031, 'n_estimators': 499, 'learning_rate': 0.0019109664805944098}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:34:53,302] Trial 87 finished with value: 0.61859179490006 and parameters: {'subsample': 0.24920265996756033, 'dropout_rate': 0.34774464146830886, 'n_estimators': 421, 'learning_rate': 0.026901258886905404}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:34:55,879] Trial 88 finished with value: 0.6135938999222954 and parameters: {'subsample': 0.4943440128451418, 'dropout_rate': 0.222071576280154, 'n_estimators': 443, 'learning_rate': 0.01594898461275984}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.5965665236051502
[I 2024-04-29 14:34:56,952] Trial 89 finished with value: 0.6170691724539284 and parameters: {'subsample': 0.2786955541147986, 'dropout_rate': 0.15309169128935907, 'n_estimators': 201, 'learning_rate': 0.06684757681864811}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:34:59,630] Trial 90 finished with value: 0.6239149888164098 and parameters: {'subsample': 0.3273226096595392, 'dropout_rate': 0.277207761195596, 'n_estimators': 463, 'learning_rate': 0.024904881231941737}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:35:01,144] Trial 91 finished with value: 0.6287838666154896 and parameters: {'subsample': 0.44490630989112295, 'dropout_rate': 0.8278144789069045, 'n_estimators': 380, 'learning_rate': 0.017915781887921894}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:35:02,901] Trial 92 finished with value: 0.6302458290642766 and parameters: {'subsample': 0.5335568400090591, 'dropout_rate': 0.5225799541853409, 'n_estimators': 363, 'learning_rate': 0.022672766075045335}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:35:05,197] Trial 93 finished with value: 0.6333466042580751 and parameters: {'subsample': 0.47052351080612836, 'dropout_rate': 0.8754379214508952, 'n_estimators': 430, 'learning_rate': 0.019127674637257917}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6844106463878327

Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:35:07,070] Trial 94 finished with value: 0.6255854590187028 and parameters: {'subsample': 0.3774803839472145, 'dropout_rate': 0.6077423641129287, 'n_estimators': 406, 'learning_rate': 0.09359381482770471}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:35:08,651] Trial 95 finished with value: 0.625756779045118 and parameters: {'subsample': 0.40938214652287497, 'dropout_rate': 0.8542391168526382, 'n_estimators': 392, 'learning_rate': 0.08776843236920487}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:35:10,403] Trial 96 finished with value: 0.6272629540679612 and parameters: {'subsample': 0.4894586888171735, 'dropout_rate': 0.9311184812667763, 'n_estimators': 453, 'learning_rate': 0.05103531864914151}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:35:13,203] Trial 97 finished with value: 0.6342049733567876 and parameters: {'subsample': 0.44784152937760985, 'dropout_rate': 0.21386812329800664, 'n_estimators': 478, 'learning_rate': 0.03184901175247192}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:35:16,113] Trial 98 finished with value: 0.6265172353188821 and parameters: {'subsample': 0.44221803773137186, 'dropout_rate': 0.2002801186536965, 'n_estimators': 484, 'learning_rate': 0.037970790455906664}. Best is trial 82 with value: 0.6350560371865749.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6692015209125475

[I 2024-04-29 14:35:18,929] A new study created in memory with name: no-name-3e53f11e-2af4-4ce3-a3ef-c5ffb3af39fe

Fold 5 C-index: 0.6051502145922747
[I 2024-04-29 14:35:18,923] Trial 99 finished with value: 0.6211578870286691 and parameters: {'subsample': 0.3512761007533375, 'dropout_rate': 0.15422135440933893, 'n_estimators': 472, 'learning_rate': 0.042005059802142454}. Best is trial 82 with value: 0.6350560371865749.


* Best trial for C-index:
 FrozenTrial(number=82, state=TrialState.COMPLETE, values=[0.6350560371865749], datetime_start=datetime.datetime(2024, 4, 29, 14, 34, 40, 681081), datetime_complete=datetime.datetime(2024, 4, 29, 14, 34, 43, 114011), params={'subsample': 0.40435140119451696, 'dropout_rate': 0.23864048613297553, 'n_estimators': 433, 'learning_rate': 0.014343382745774179}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=82, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.40435140119451696, 'dropout_rate': 0.23864048613297553, 'n_estimators': 433, 'learning_rate': 0.014343382745774179}


* Best Score for C-index:
 0.6350560371865749

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2768605959166274
Fold 2 IBS: 0.3002240901900513
Fold 3 IBS: 0.20816241232849142
Fold 4 IBS: 0.25164204958791786
Fold 5 IBS: 0.23049650269649638
[I 2024-04-29 14:35:19,286] Trial 0 finished with value: 0.2534771301439169 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2534771301439169.
Fold 1 IBS: 0.3314083926697305
Fold 2 IBS: 0.3801225465459666
Fold 3 IBS: 0.26584323394581666
Fold 4 IBS: 0.307376218934207
Fold 5 IBS: 0.339376702626222
[I 2024-04-29 14:35:22,027] Trial 1 finished with value: 0.32482541894438854 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2534771301439169.
Fold 1 IBS: 0.30929438977780943
Fold 2 IBS: 0.3776592383257721
Fold 3 IBS: 0.23149355642930963
Fold 4 IBS: 0.28349306932088597
Fold 5 IBS: 0.3100934076743383
[I 2024-04-29 14:35:22,570] Trial 2 finished with value: 0.3024067323056231 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2534771301439169.
Fold 1 IBS: 0.3109416169448545
Fold 2 IBS: 0.3783699302877189
Fold 3 IBS: 0.23826415829830536
Fold 4 IBS: 0.29863634239497205
Fold 5 IBS: 0.2671809615732079
[I 2024-04-29 14:35:23,283] Trial 3 finished with value: 0.29867860189981177 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2534771301439169.
Fold 1 IBS: 0.3175766748007208
Fold 2 IBS: 0.3791283849019784
Fold 3 IBS: 0.2495340925559205
Fold 4 IBS: 0.3130079481566267
Fold 5 IBS: 0.28457009062304117
[I 2024-04-29 14:35:24,381] Trial 4 finished with value: 0.3087634382076575 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2534771301439169.
Fold 1 IBS: 0.3332145305423825
Fold 2 IBS: 0.38011990649983673
Fold 3 IBS: 0.25198997521142397
Fold 4 IBS: 0.3079558871281474
Fold 5 IBS: 0.33923818447315957
[I 2024-04-29 14:35:25,703] Trial 5 finished with value: 0.32250369677099006 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2534771301439169.
Fold 1 IBS: 0.2583770894605203
Fold 2 IBS: 0.2538208871784848
Fold 3 IBS: 0.20728964004289857
Fold 4 IBS: 0.24061910572279663
Fold 5 IBS: 0.21760040361445157
[I 2024-04-29 14:35:26,279] Trial 6 finished with value: 0.23554142520383037 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.23554142520383037.
Fold 1 IBS: 0.24449081430179984
Fold 2 IBS: 0.23006896862415954
Fold 3 IBS: 0.21843183660549986
Fold 4 IBS: 0.23796076829109816
Fold 5 IBS: 0.21471613571364556
[I 2024-04-29 14:35:26,410] Trial 7 finished with value: 0.2291337047072406 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.2291337047072406.
Fold 1 IBS: 0.2749667055201454
Fold 2 IBS: 0.31722578035710736
Fold 3 IBS: 0.2145310231981918
Fold 4 IBS: 0.2588310393109894
Fold 5 IBS: 0.22610047650933945
[I 2024-04-29 14:35:27,122] Trial 8 finished with value: 0.2583310049791547 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.2291337047072406.
Fold 1 IBS: 0.31868958253133545
Fold 2 IBS: 0.38012170435921
Fold 3 IBS: 0.2744945823733866
Fold 4 IBS: 0.3364877264983839
Fold 5 IBS: 0.3390266035749277
[I 2024-04-29 14:35:29,074] Trial 9 finished with value: 0.32976403986744873 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.2291337047072406.
Fold 1 IBS: 0.2470353461515696
Fold 2 IBS: 0.23180355778544998
Fold 3 IBS: 0.22856182093970995
Fold 4 IBS: 0.24171407848753257
Fold 5 IBS: 0.22906264846898927
[I 2024-04-29 14:35:29,166] Trial 10 finished with value: 0.2356354903666503 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.2291337047072406.
Fold 1 IBS: 0.24687652993070414
Fold 2 IBS: 0.23195400682301584
Fold 3 IBS: 0.22803828196828552
Fold 4 IBS: 0.24151517366938874
Fold 5 IBS: 0.22870297189521768
[I 2024-04-29 14:35:29,221] Trial 11 finished with value: 0.23541739285732238 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.2291337047072406.
Fold 1 IBS: 0.2559176517311384
Fold 2 IBS: 0.2408424701387146
Fold 3 IBS: 0.2057974255759873
Fold 4 IBS: 0.25799863691485025
Fold 5 IBS: 0.2015907866160034
[I 2024-04-29 14:35:29,380] Trial 12 finished with value: 0.2324293941953388 and parameters: {'subsample': 0.11320521666185814, 'dropout_rate': 0.7125180266624932, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.2291337047072406.
Fold 1 IBS: 0.2800922811587031
Fold 2 IBS: 0.2924642339967005
Fold 3 IBS: 0.20705019878210726
Fold 4 IBS: 0.27577799477915027
Fold 5 IBS: 0.20539603146722382
[I 2024-04-29 14:35:29,616] Trial 13 finished with value: 0.252156148036777 and parameters: {'subsample': 0.11038782630303162, 'dropout_rate': 0.695526957994077, 'n_estimators': 86, 'learning_rate': 0.09856277651579823}. Best is trial 7 with value: 0.2291337047072406.
Fold 1 IBS: 0.2783478728038267
Fold 2 IBS: 0.3342314139254011
Fold 3 IBS: 0.23173311781309966
Fold 4 IBS: 0.2616408969360102
Fold 5 IBS: 0.21705815477853624
[I 2024-04-29 14:35:29,831] Trial 14 finished with value: 0.2646022912513748 and parameters: {'subsample': 0.29524115835831166, 'dropout_rate': 0.6355856554810184, 'n_estimators': 79, 'learning_rate': 0.09964553963945819}. Best is trial 7 with value: 0.2291337047072406.
Fold 1 IBS: 0.29329022035532154
Fold 2 IBS: 0.37074771501252135
Fold 3 IBS: 0.252613714528157
Fold 4 IBS: 0.2785331342980155
Fold 5 IBS: 0.2610562316562823
[I 2024-04-29 14:35:30,148] Trial 15 finished with value: 0.29124820317005956 and parameters: {'subsample': 0.3113782463318137, 'dropout_rate': 0.8117973140879879, 'n_estimators': 122, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.2291337047072406.
Fold 1 IBS: 0.3012315390796449
Fold 2 IBS: 0.3772310185796683
Fold 3 IBS: 0.2381438544324291
Fold 4 IBS: 0.2870422224970586
Fold 5 IBS: 0.2890780663430509
[I 2024-04-29 14:35:31,113] Trial 16 finished with value: 0.29854534018637036 and parameters: {'subsample': 0.3629956613085432, 'dropout_rate': 0.9733961081825167, 'n_estimators': 297, 'learning_rate': 0.040259456601039204}. Best is trial 7 with value: 0.2291337047072406.
Fold 1 IBS: 0.24563146104041864
Fold 2 IBS: 0.22906388180636858
Fold 3 IBS: 0.22565127774252322
Fold 4 IBS: 0.24035367525184353
Fold 5 IBS: 0.22514199878139385
[I 2024-04-29 14:35:31,258] Trial 17 finished with value: 0.23316845892450955 and parameters: {'subsample': 0.2104307286176502, 'dropout_rate': 0.6004730897368156, 'n_estimators': 44, 'learning_rate': 0.01245288911484009}. Best is trial 7 with value: 0.2291337047072406.
Fold 1 IBS: 0.3038447457237408
Fold 2 IBS: 0.3787167644577537
Fold 3 IBS: 0.24112393055308448
Fold 4 IBS: 0.28857911886790805
Fold 5 IBS: 0.3052906347214811
[I 2024-04-29 14:35:32,496] Trial 18 finished with value: 0.30351103886479364 and parameters: {'subsample': 0.39635847792734874, 'dropout_rate': 0.7904615013324701, 'n_estimators': 336, 'learning_rate': 0.03935603162728128}. Best is trial 7 with value: 0.2291337047072406.
Fold 1 IBS: 0.30796444109430066
Fold 2 IBS: 0.373115983039534

Fold 3 IBS: 0.2420883508635342
Fold 4 IBS: 0.28861669986805133
Fold 5 IBS: 0.26850778872891123
[I 2024-04-29 14:35:32,844] Trial 19 finished with value: 0.2960586527188663 and parameters: {'subsample': 0.19625604601881638, 'dropout_rate': 0.9930703343219778, 'n_estimators': 132, 'learning_rate': 0.08681602954259124}. Best is trial 7 with value: 0.2291337047072406.
Fold 1 IBS: 0.2449490755369921
Fold 2 IBS: 0.23136100805221904
Fold 3 IBS: 0.21231495466727224
Fold 4 IBS: 0.23604030462642991
Fold 5 IBS: 0.2158097056778787
[I 2024-04-29 14:35:32,998] Trial 20 finished with value: 0.2280950097121584 and parameters: {'subsample': 0.6102628884762309, 'dropout_rate': 0.5558690358940764, 'n_estimators': 52, 'learning_rate': 0.04127909023805986}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.2456074604293363
Fold 2 IBS: 0.23302758221566516
Fold 3 IBS: 0.21178731577318305
Fold 4 IBS: 0.23616214029004035
Fold 5 IBS: 0.21454946703754782
[I 2024-04-29 14:35:33,160] Trial 21 finished with value: 0.22822679314915453 and parameters: {'subsample': 0.6362748427966717, 'dropout_rate': 0.5537934605115938, 'n_estimators': 57, 'learning_rate': 0.042594274103339054}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.2468352225471468
Fold 2 IBS: 0.23163047416289245
Fold 3 IBS: 0.22806067269720692
Fold 4 IBS: 0.24153941398634782
Fold 5 IBS: 0.22872743236025306
[I 2024-04-29 14:35:33,226] Trial 22 finished with value: 0.2353586431507694 and parameters: {'subsample': 0.6446807593774737, 'dropout_rate': 0.5405657270190689, 'n_estimators': 2, 'learning_rate': 0.041924521216552206}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.24415137088179711
Fold 2 IBS: 0.22896418157002804
Fold 3 IBS: 0.21651253910004936
Fold 4 IBS: 0.23617149577931876
Fold 5 IBS: 0.21884026812506485
[I 2024-04-29 14:35:33,477] Trial 23 finished with value: 0.2289279710912516 and parameters: {'subsample': 0.845000450042138, 'dropout_rate': 0.6011576435519733, 'n_estimators': 75, 'learning_rate': 0.02050909287157107}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.24747507514656247
Fold 2 IBS: 0.2346759853394555
Fold 3 IBS: 0.21005912454576894
Fold 4 IBS: 0.2359349333618713
Fold 5 IBS: 0.21558923969214738
[I 2024-04-29 14:35:33,957] Trial 24 finished with value: 0.22874687161716115 and parameters: {'subsample': 0.8816354096299833, 'dropout_rate': 0.4736976824144059, 'n_estimators': 151, 'learning_rate': 0.01744685233233402}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.2450399699116292
Fold 2 IBS: 0.23054691370598748
Fold 3 IBS: 0.21341569101253346
Fold 4 IBS: 0.2356596516944834
Fold 5 IBS: 0.21687516831926096
[I 2024-04-29 14:35:34,405] Trial 25 finished with value: 0.2283074789287789 and parameters: {'subsample': 0.8615354277037236, 'dropout_rate': 0.33002777578250453, 'n_estimators': 150, 'learning_rate': 0.013287182579533728}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.24416031536301983
Fold 2 IBS: 0.22858297659141266
Fold 3 IBS: 0.2191858171765639
Fold 4 IBS: 0.23688569851759222
Fold 5 IBS: 0.21943435460803837
[I 2024-04-29 14:35:35,195] Trial 26 finished with value: 0.22964983245132536 and parameters: {'subsample': 0.6105109961473616, 'dropout_rate': 0.2968233742660247, 'n_estimators': 223, 'learning_rate': 0.006055302272548541}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.25128908338088746
Fold 2 IBS: 0.24070947293140157
Fold 3 IBS: 0.20725991587536327
Fold 4 IBS: 0.23777584314425831
Fold 5 IBS: 0.21163665570734816
[I 2024-04-29 14:35:35,496] Trial 27 finished with value: 0.22973419420785177 and parameters: {'subsample': 0.8398584734126338, 'dropout_rate': 0.14675521376839798, 'n_estimators': 105, 'learning_rate': 0.03331972458281015}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.24455525449021756
Fold 2 IBS: 0.2298216068086644
Fold 3 IBS: 0.21460108895763946
Fold 4 IBS: 0.23573240564215303
Fold 5 IBS: 0.21780387720772504
[I 2024-04-29 14:35:36,038] Trial 28 finished with value: 0.2285028466212799 and parameters: {'subsample': 0.9559728467548972, 'dropout_rate': 0.2751676654520265, 'n_estimators': 172, 'learning_rate': 0.0105021530498218}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.2808254177062342
Fold 2 IBS: 0.3187168367886179
Fold 3 IBS: 0.20984521157536817
Fold 4 IBS: 0.2580444564862806
Fold 5 IBS: 0.22506586042479979
[I 2024-04-29 14:35:36,369] Trial 29 finished with value: 0.2584995565962601 and parameters: {'subsample': 0.5790219222156496, 'dropout_rate': 0.3815154452983834, 'n_estimators': 117, 'learning_rate': 0.06046208382653473}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.26146402605521446
Fold 2 IBS: 0.2604755187725914
Fold 3 IBS: 0.20837603514686806
Fold 4 IBS: 0.24215594077513308
Fold 5 IBS: 0.2154703228797978
[I 2024-04-29 14:35:36,786] Trial 30 finished with value: 0.23758836872592098 and parameters: {'subsample': 0.767234520408729, 'dropout_rate': 0.3183736233152148, 'n_estimators': 140, 'learning_rate': 0.03323495442553544}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.2522239742075012
Fold 2 IBS: 0.24255312804089282
Fold 3 IBS: 0.20708197928091748
Fold 4 IBS: 0.23776524444696442
Fold 5 IBS: 0.21549378665148
[I 2024-04-29 14:35:37,874] Trial 31 finished with value: 0.23102362252555117 and parameters: {'subsample': 0.9488701920274671, 'dropout_rate': 0.2254080891043035, 'n_estimators': 250, 'learning_rate': 0.013875386268940266}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.24414628501312183
Fold 2 IBS: 0.22888264504244957
Fold 3 IBS: 0.21650445345502967
Fold 4 IBS: 0.23608118249922197
Fold 5 IBS: 0.21917014151931988
[I 2024-04-29 14:35:38,408] Trial 32 finished with value: 0.22895694150582857 and parameters: {'subsample': 0.9076317444937305, 'dropout_rate': 0.42686358838527455, 'n_estimators': 172, 'learning_rate': 0.008816482293041801}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.24681969500828446
Fold 2 IBS: 0.2336419199276687
Fold 3 IBS: 0.21132588678606373
Fold 4 IBS: 0.23595592967491638
Fold 5 IBS: 0.21284470130032399
[I 2024-04-29 14:35:38,674] Trial 33 finished with value: 0.22811762653945147 and parameters: {'subsample': 0.8017872389711715, 'dropout_rate': 0.10331660131014647, 'n_estimators': 93, 'learning_rate': 0.027997278046075002}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.24599845940787407
Fold 2 IBS: 0.23332028669109128
Fold 3 IBS: 0.2129316728460386
Fold 4 IBS: 0.23638229490553092
Fold 5 IBS: 0.21390593413557019
[I 2024-04-29 14:35:38,933] Trial 34 finished with value: 0.22850772959722102 and parameters: {'subsample': 0.7061901100242275, 'dropout_rate': 0.20729522975477116, 'n_estimators': 92, 'learning_rate': 0.026577796841169156}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.24656043671364655
Fold 2 IBS: 0.23328040131519792
Fold 3 IBS: 0.21172898259165365
Fold 4 IBS: 0.23619794635763308
Fold 5 IBS: 0.21253604448197963
[I 2024-04-29 14:35:39,101] Trial 35 finished with value: 0.22806076229202218 and parameters: {'subsample': 0.7854455042547966, 'dropout_rate': 0.1092492198220138, 'n_estimators': 56, 'learning_rate': 0.04607205194818506}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.2441206397848643
Fold 2 IBS: 0.22868252456635438
Fold 3 IBS: 0.2180489664073654
Fold 4 IBS: 0.2364152502429355
Fold 5 IBS: 0.21869060841408625
[I 2024-04-29 14:35:39,211] Trial 36 finished with value: 0.22919159788312116 and parameters: {'subsample': 0.801658788675615, 'dropout_rate': 0.14186038312840116, 'n_estimators': 31, 'learning_rate': 0.04850024622187401}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.24881676462270133
Fold 2 IBS: 0.23749791223755973
Fold 3 IBS: 0.2100876629202238
Fold 4 IBS: 0.23866806950142685
Fold 5 IBS: 0.20878260429623374
[I 2024-04-29 14:35:39,373] Trial 37 finished with value: 0.22877060271562905 and parameters: {'subsample': 0.6849019118508213, 'dropout_rate': 0.11688266636616183, 'n_estimators': 56, 'learning_rate': 0.059207327336158105}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.24493766598617653
Fold 2 IBS: 0.22922896427700137
Fold 3 IBS: 0.22295058319940333
Fold 4 IBS: 0.23865852277308305
Fold 5 IBS: 0.2238677521863841
[I 2024-04-29 14:35:39,451] Trial 38 finished with value: 0.2319286976844097 and parameters: {'subsample': 0.5343048414802583, 'dropout_rate': 0.19601280460519543, 'n_estimators': 15, 'learning_rate': 0.04722630186483913}. Best is trial 35 with value: 0.22806076229202218.

Fold 1 IBS: 0.2616929141865961
Fold 2 IBS: 0.2584746420928571
Fold 3 IBS: 0.20509225002521414
Fold 4 IBS: 0.24255128592615663
Fold 5 IBS: 0.22016369088716634
[I 2024-04-29 14:35:39,641] Trial 39 finished with value: 0.23759495662359806 and parameters: {'subsample': 0.7913354503723935, 'dropout_rate': 0.49942804580714845, 'n_estimators': 66, 'learning_rate': 0.06892741183938003}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.3274822159175251
Fold 2 IBS: 0.3801203890074418
Fold 3 IBS: 0.26275327867621484
Fold 4 IBS: 0.302592865334411
Fold 5 IBS: 0.33915386361994393
[I 2024-04-29 14:35:41,875] Trial 40 finished with value: 0.3224205225111073 and parameters: {'subsample': 0.635202567294034, 'dropout_rate': 0.4193126238717278, 'n_estimators': 434, 'learning_rate': 0.053435359182960426}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.25431839807904555
Fold 2 IBS: 0.24584941441284566
Fold 3 IBS: 0.20889578185906552
Fold 4 IBS: 0.239073073530296
Fold 5 IBS: 0.21275686117869264
[I 2024-04-29 14:35:42,171] Trial 41 finished with value: 0.23217870581198907 and parameters: {'subsample': 0.7315314599934812, 'dropout_rate': 0.33224239773242314, 'n_estimators': 101, 'learning_rate': 0.03777413553882145}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.2443668662999125
Fold 2 IBS: 0.22867870278338076
Fold 3 IBS: 0.2211232640334732
Fold 4 IBS: 0.23767674164163644
Fold 5 IBS: 0.22271749968567037
[I 2024-04-29 14:35:42,301] Trial 42 finished with value: 0.23091261488881468 and parameters: {'subsample': 0.82650038857956, 'dropout_rate': 0.18555759267297461, 'n_estimators': 35, 'learning_rate': 0.02608194255715347}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.2626440400830599
Fold 2 IBS: 0.2630532526108297
Fold 3 IBS: 0.20441668348273825
Fold 4 IBS: 0.2433831864421931
Fold 5 IBS: 0.20941768510904926
[I 2024-04-29 14:35:42,863] Trial 43 finished with value: 0.23658296954557403 and parameters: {'subsample': 0.8952564086208508, 'dropout_rate': 0.1126846582513547, 'n_estimators': 157, 'learning_rate': 0.03163676738840634}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.24628209505769977
Fold 2 IBS: 0.23440209397754888
Fold 3 IBS: 0.21067803793281697
Fold 4 IBS: 0.2355725157877382
Fold 5 IBS: 0.2132418823497649
[I 2024-04-29 14:35:43,070] Trial 44 finished with value: 0.22803532502111373 and parameters: {'subsample': 0.5795803547524322, 'dropout_rate': 0.5020020877800176, 'n_estimators': 58, 'learning_rate': 0.04508416432006209}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24646841424639185
Fold 2 IBS: 0.23494203153877122
Fold 3 IBS: 0.21680295045475645
Fold 4 IBS: 0.2374364966485224
Fold 5 IBS: 0.21234937060345063
[I 2024-04-29 14:35:43,264] Trial 45 finished with value: 0.22959985269837851 and parameters: {'subsample': 0.4516370662115133, 'dropout_rate': 0.5117124736526378, 'n_estimators': 60, 'learning_rate': 0.04549371134509104}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2610919362878939
Fold 2 IBS: 0.27327898146555113
Fold 3 IBS: 0.21291441021241067
Fold 4 IBS: 0.24530522158050516
Fold 5 IBS: 0.21542887019124304
[I 2024-04-29 14:35:43,519] Trial 46 finished with value: 0.2416038839475208 and parameters: {'subsample': 0.5661925665028334, 'dropout_rate': 0.5977238330260896, 'n_estimators': 92, 'learning_rate': 0.055230119616596}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24496260438533862
Fold 2 IBS: 0.22886463375138208
Fold 3 IBS: 0.22263342876186504
Fold 4 IBS: 0.23833436614084785
Fold 5 IBS: 0.22331753158076026
[I 2024-04-29 14:35:43,612] Trial 47 finished with value: 0.2316225129240388 and parameters: {'subsample': 0.5998601417579749, 'dropout_rate': 0.24102802507424348, 'n_estimators': 21, 'learning_rate': 0.036540031044914836}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.261848587799392
Fold 2 IBS: 0.2648214455301418
Fold 3 IBS: 0.20522241806043479
Fold 4 IBS: 0.2433546645055163
Fold 5 IBS: 0.21681398901882623
[I 2024-04-29 14:35:43,820] Trial 48 finished with value: 0.23841222098286222 and parameters: {'subsample': 0.6657704432105864, 'dropout_rate': 0.6604314111556595, 'n_estimators': 75, 'learning_rate': 0.06459360749932624}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.3071583266729974
Fold 2 IBS: 0.3685586406230107
Fold 3 IBS: 0.21626612698917821
Fold 4 IBS: 0.2766138855055833
Fold 5 IBS: 0.3012016555519753
[I 2024-04-29 14:35:44,446] Trial 49 finished with value: 0.293959727068549 and parameters: {'subsample': 0.7166925637726277, 'dropout_rate': 0.54808904609971, 'n_estimators': 196, 'learning_rate': 0.050582517363759134}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2444731467435483
Fold 2 IBS: 0.22879646813369328
Fold 3 IBS: 0.2210258388621463
Fold 4 IBS: 0.23592305173732264
Fold 5 IBS: 0.21775702820399423
[I 2024-04-29 14:35:44,591] Trial 50 finished with value: 0.22959510673614095 and parameters: {'subsample': 0.45392641686402563, 'dropout_rate': 0.7747773432024949, 'n_estimators': 38, 'learning_rate': 0.04279349075928138}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24478210628351707
Fold 2 IBS: 0.22991874549737382
Fold 3 IBS: 0.21487735714716685
Fold 4 IBS: 0.23588285466765815
Fold 5 IBS: 0.21746648657682394
[I 2024-04-29 14:35:44,923] Trial 51 finished with value: 0.22858551003450794 and parameters: {'subsample': 0.7656121855045271, 'dropout_rate': 0.375068943812752, 'n_estimators': 111, 'learning_rate': 0.016769783329425858}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24468538246820604
Fold 2 IBS: 0.2301295721629543
Fold 3 IBS: 0.21518340253303478
Fold 4 IBS: 0.2367247112712219
Fold 5 IBS: 0.21590312061571182
[I 2024-04-29 14:35:45,109] Trial 52 finished with value: 0.22852523781022577 and parameters: {'subsample': 0.5283099260705277, 'dropout_rate': 0.4459698952011236, 'n_estimators': 65, 'learning_rate': 0.029503976615238153}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24787916127154758
Fold 2 IBS: 0.23655810320457568
Fold 3 IBS: 0.21110453268750512
Fold 4 IBS: 0.23683011999309916
Fold 5 IBS: 0.21310847610766678
[I 2024-04-29 14:35:45,469] Trial 53 finished with value: 0.22909607865287884 and parameters: {'subsample': 0.621714533336511, 'dropout_rate': 0.5710584887618361, 'n_estimators': 126, 'learning_rate': 0.022931541302205247}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24567839096993888
Fold 2 IBS: 0.23192043305621807
Fold 3 IBS: 0.21234656017895226
Fold 4 IBS: 0.2356195507498038
Fold 5 IBS: 0.21611589261124906
[I 2024-04-29 14:35:45,661] Trial 54 finished with value: 0.2283361655132324 and parameters: {'subsample': 0.8665361291675531, 'dropout_rate': 0.516751702930278, 'n_estimators': 49, 'learning_rate': 0.04574441234267258}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24709397032165614
Fold 2 IBS: 0.2318764553746983
Fold 3 IBS: 0.22940450057193468
Fold 4 IBS: 0.24181001885715006
Fold 5 IBS: 0.2291865592533899
[I 2024-04-29 14:35:45,732] Trial 55 finished with value: 0.23587430087576583 and parameters: {'subsample': 0.6765664077905448, 'dropout_rate': 0.1702432687938276, 'n_estimators': 1, 'learning_rate': 0.03468041430213696}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2468443721703389
Fold 2 IBS: 0.23158247134692211
Fold 3 IBS: 0.22817904711832715
Fold 4 IBS: 0.24148474730599456
Fold 5 IBS: 0.22873951850065025
[I 2024-04-29 14:35:45,967] Trial 56 finished with value: 0.2353660312884466 and parameters: {'subsample': 0.811177007139624, 'dropout_rate': 0.632872623933352, 'n_estimators': 83, 'learning_rate': 0.0010113076162487182}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2749040444434231
Fold 2 IBS: 0.29429406285090515
Fold 3 IBS: 0.20432119960061182
Fold 4 IBS: 0.25032553338857244
Fold 5 IBS: 0.23674737796263365
[I 2024-04-29 14:35:46,433] Trial 57 finished with value: 0.25211844364922925 and parameters: {'subsample': 0.9253779282961316, 'dropout_rate': 0.3427793946355077, 'n_estimators': 146, 'learning_rate': 0.04111081928368819}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24436658975493045
Fold 2 IBS: 0.2287764416900902
Fold 3 IBS: 0.22153502379107096
Fold 4 IBS: 0.2379699903876509
Fold 5 IBS: 0.2232100120140441
[I 2024-04-29 14:35:46,533] Trial 58 finished with value: 0.23117161152755733 and parameters: {'subsample': 0.7540288161572106, 'dropout_rate': 0.47146280673615026, 'n_estimators': 16, 'learning_rate': 0.05327358123897698}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2740664401762801

Fold 2 IBS: 0.29801343453883344
Fold 3 IBS: 0.2043575111283917
Fold 4 IBS: 0.2501181480642662
Fold 5 IBS: 0.23960609341954714
[I 2024-04-29 14:35:46,827] Trial 59 finished with value: 0.2532323254654637 and parameters: {'subsample': 0.8600220350417078, 'dropout_rate': 0.576594985075754, 'n_estimators': 104, 'learning_rate': 0.05792943581299736}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24480616451538592
Fold 2 IBS: 0.22872598499241903
Fold 3 IBS: 0.2219822920031368
Fold 4 IBS: 0.23824537864597717
Fold 5 IBS: 0.22249061216421565
[I 2024-04-29 14:35:46,963] Trial 60 finished with value: 0.23125008646422693 and parameters: {'subsample': 0.5182083766842418, 'dropout_rate': 0.4100731778926394, 'n_estimators': 43, 'learning_rate': 0.02007445129499992}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24539384312264087
Fold 2 IBS: 0.23153532791807438
Fold 3 IBS: 0.21353666453704093
Fold 4 IBS: 0.23579597885526882
Fold 5 IBS: 0.21608070606317314
[I 2024-04-29 14:35:47,128] Trial 61 finished with value: 0.22846850409923963 and parameters: {'subsample': 0.7829524883654503, 'dropout_rate': 0.5388959028671209, 'n_estimators': 50, 'learning_rate': 0.043359766095211465}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2533851762393821
Fold 2 IBS: 0.24506114619217786
Fold 3 IBS: 0.20658443243769956
Fold 4 IBS: 0.23808316450473532
Fold 5 IBS: 0.21558687933632653
[I 2024-04-29 14:35:47,351] Trial 62 finished with value: 0.23174015974206424 and parameters: {'subsample': 0.8656066856115973, 'dropout_rate': 0.5107274904127561, 'n_estimators': 75, 'learning_rate': 0.04870569191108665}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24405592866004802
Fold 2 IBS: 0.22846266285853914
Fold 3 IBS: 0.21899162201770456
Fold 4 IBS: 0.2368164868731481
Fold 5 IBS: 0.22097472262657702
[I 2024-04-29 14:35:47,451] Trial 63 finished with value: 0.22986028460720337 and parameters: {'subsample': 0.9789957818744204, 'dropout_rate': 0.2734750870094943, 'n_estimators': 26, 'learning_rate': 0.04571758103210779}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2451022402661718
Fold 2 IBS: 0.23080272461410362
Fold 3 IBS: 0.21330122526921597
Fold 4 IBS: 0.23563338973693668
Fold 5 IBS: 0.21694071741449433
[I 2024-04-29 14:35:47,603] Trial 64 finished with value: 0.2283560594601845 and parameters: {'subsample': 0.9302718983949787, 'dropout_rate': 0.6335692022283583, 'n_estimators': 54, 'learning_rate': 0.037760595601604025}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2642933182458483
Fold 2 IBS: 0.2658498498276432
Fold 3 IBS: 0.2116982440756998
Fold 4 IBS: 0.24506113764442827
Fold 5 IBS: 0.21718707923619715
[I 2024-04-29 14:35:47,980] Trial 65 finished with value: 0.24081792580596334 and parameters: {'subsample': 0.6588981766919912, 'dropout_rate': 0.4423885330532031, 'n_estimators': 123, 'learning_rate': 0.040116287481324946}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.26009221234465346
Fold 2 IBS: 0.26078531266026933
Fold 3 IBS: 0.20773749142110037
Fold 4 IBS: 0.2457065520074137
Fold 5 IBS: 0.21236037866452573
[I 2024-04-29 14:35:48,225] Trial 66 finished with value: 0.23733638941959256 and parameters: {'subsample': 0.5808486801439944, 'dropout_rate': 0.48256162650557577, 'n_estimators': 90, 'learning_rate': 0.052155520636334114}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24437074823927857
Fold 2 IBS: 0.22935760885041248
Fold 3 IBS: 0.2170175983624056
Fold 4 IBS: 0.23606651129250766
Fold 5 IBS: 0.2177845607094601
[I 2024-04-29 14:35:49,545] Trial 67 finished with value: 0.22891940549081288 and parameters: {'subsample': 0.702990561632221, 'dropout_rate': 0.10592939732110414, 'n_estimators': 302, 'learning_rate': 0.0056229342096923395}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2466935204804018
Fold 2 IBS: 0.2339662916203766
Fold 3 IBS: 0.21083279971205854
Fold 4 IBS: 0.23579250149515904
Fold 5 IBS: 0.21525221921249774
[I 2024-04-29 14:35:49,748] Trial 68 finished with value: 0.22850746650409876 and parameters: {'subsample': 0.8239336526093479, 'dropout_rate': 0.5274135506893471, 'n_estimators': 71, 'learning_rate': 0.03557646010123462}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.28507333848732747
Fold 2 IBS: 0.3252413337531
Fold 3 IBS: 0.20566983412389228
Fold 4 IBS: 0.25670993322500185
Fold 5 IBS: 0.25900020491353004
[I 2024-04-29 14:35:50,505] Trial 69 finished with value: 0.2663389289005703 and parameters: {'subsample': 0.8808396396294945, 'dropout_rate': 0.6742877948812134, 'n_estimators': 238, 'learning_rate': 0.029325454860253307}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2920069133722312
Fold 2 IBS: 0.3626243333711413
Fold 3 IBS: 0.22221199428330596
Fold 4 IBS: 0.27306086902663984
Fold 5 IBS: 0.23741998401274642
[I 2024-04-29 14:35:52,877] Trial 70 finished with value: 0.27746481881321294 and parameters: {'subsample': 0.4873818326074257, 'dropout_rate': 0.15119955197352622, 'n_estimators': 408, 'learning_rate': 0.023541674092857016}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24493356955392379
Fold 2 IBS: 0.23050872370673717
Fold 3 IBS: 0.21371417423433742
Fold 4 IBS: 0.2356522131783576
Fold 5 IBS: 0.2171375628231989
[I 2024-04-29 14:35:53,049] Trial 71 finished with value: 0.22838924869931096 and parameters: {'subsample': 0.9335706836821853, 'dropout_rate': 0.6365161405004507, 'n_estimators': 51, 'learning_rate': 0.03876859911078692}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24693899311005157
Fold 2 IBS: 0.2340616584235904
Fold 3 IBS: 0.21052855254379477
Fold 4 IBS: 0.23584976078274889
Fold 5 IBS: 0.21572428813152353
[I 2024-04-29 14:35:53,238] Trial 72 finished with value: 0.22862065059834183 and parameters: {'subsample': 0.9848053710770828, 'dropout_rate': 0.5715851379156515, 'n_estimators': 58, 'learning_rate': 0.04374797044989356}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24447489901688546
Fold 2 IBS: 0.2296722494938454
Fold 3 IBS: 0.21498381975341666
Fold 4 IBS: 0.23587466620140568
Fold 5 IBS: 0.21797656968477105
[I 2024-04-29 14:35:53,389] Trial 73 finished with value: 0.22859644083006486 and parameters: {'subsample': 0.9104698751711979, 'dropout_rate': 0.739811425028012, 'n_estimators': 37, 'learning_rate': 0.04782757254981085}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24532547419152104
Fold 2 IBS: 0.22981823242225843
Fold 3 IBS: 0.22475169777446155
Fold 4 IBS: 0.23951680460704583
Fold 5 IBS: 0.22584710499446298
[I 2024-04-29 14:35:53,516] Trial 74 finished with value: 0.23305186279794995 and parameters: {'subsample': 0.8485937239868786, 'dropout_rate': 0.6128365123041772, 'n_estimators': 15, 'learning_rate': 0.030934773504669423}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.25214068889953933
Fold 2 IBS: 0.24314423409870542
Fold 3 IBS: 0.20692957087019428
Fold 4 IBS: 0.23762083078015286
Fold 5 IBS: 0.21537871145500534
[I 2024-04-29 14:35:53,813] Trial 75 finished with value: 0.23104280722071943 and parameters: {'subsample': 0.874075972617653, 'dropout_rate': 0.6830589963062559, 'n_estimators': 95, 'learning_rate': 0.036632353035241025}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2885500958375556
Fold 2 IBS: 0.33713783177081075
Fold 3 IBS: 0.2080113263772693
Fold 4 IBS: 0.26085919512987243
Fold 5 IBS: 0.26256191260602996
[I 2024-04-29 14:35:54,238] Trial 76 finished with value: 0.2714240723443076 and parameters: {'subsample': 0.7253619411932841, 'dropout_rate': 0.5662037880248826, 'n_estimators': 134, 'learning_rate': 0.056703880585207284}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.26531215810663883
Fold 2 IBS: 0.2739216076563925
Fold 3 IBS: 0.20565763481179405
Fold 4 IBS: 0.2446949993380001
Fold 5 IBS: 0.22306124037124647
[I 2024-04-29 14:35:54,573] Trial 77 finished with value: 0.24252952805681435 and parameters: {'subsample': 0.7836762120375689, 'dropout_rate': 0.649173726264939, 'n_estimators': 112, 'learning_rate': 0.04570223320690589}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.25247131611254575
Fold 2 IBS: 0.2509692790737629
Fold 3 IBS: 0.2109337973291775

Fold 4 IBS: 0.24223018529288326
Fold 5 IBS: 0.2066465684530942
[I 2024-04-29 14:35:54,830] Trial 78 finished with value: 0.23265022925229273 and parameters: {'subsample': 0.5484457169084019, 'dropout_rate': 0.22015964511958286, 'n_estimators': 83, 'learning_rate': 0.04941919385503316}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.28546627650696904
Fold 2 IBS: 0.3380677593689487
Fold 3 IBS: 0.21408985974371417
Fold 4 IBS: 0.26162509079926033
Fold 5 IBS: 0.2504196235788123
[I 2024-04-29 14:35:55,384] Trial 79 finished with value: 0.2699337219995409 and parameters: {'subsample': 0.5921521465840234, 'dropout_rate': 0.8749042812122334, 'n_estimators': 188, 'learning_rate': 0.04027300903668814}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24411324640618776
Fold 2 IBS: 0.22881097302349013
Fold 3 IBS: 0.21633320784409502
Fold 4 IBS: 0.23612144672296592
Fold 5 IBS: 0.21873565619800778
[I 2024-04-29 14:35:55,539] Trial 80 finished with value: 0.22882290603894934 and parameters: {'subsample': 0.8321289633684164, 'dropout_rate': 0.13334783894055188, 'n_estimators': 46, 'learning_rate': 0.03407537230836163}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24540792487214372
Fold 2 IBS: 0.2314200189900434
Fold 3 IBS: 0.2126167544982379
Fold 4 IBS: 0.235617389355653
Fold 5 IBS: 0.2165825487208054
[I 2024-04-29 14:35:55,699] Trial 81 finished with value: 0.2283289272873767 and parameters: {'subsample': 0.9266778798763943, 'dropout_rate': 0.6145124904031225, 'n_estimators': 54, 'learning_rate': 0.03991026622771782}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24732083334073524
Fold 2 IBS: 0.2346590960252153
Fold 3 IBS: 0.2101429652953674
Fold 4 IBS: 0.23593988436512947
Fold 5 IBS: 0.21558138329304583
[I 2024-04-29 14:35:55,923] Trial 82 finished with value: 0.22872883246389866 and parameters: {'subsample': 0.9636349207972594, 'dropout_rate': 0.6099626227240922, 'n_estimators': 62, 'learning_rate': 0.0423482369242382}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24408103344991997
Fold 2 IBS: 0.2284652372564656
Fold 3 IBS: 0.21965268714371197
Fold 4 IBS: 0.2368706951143239
Fold 5 IBS: 0.2215677871615078
[I 2024-04-29 14:35:56,046] Trial 83 finished with value: 0.23012748802518584 and parameters: {'subsample': 0.9023792261032295, 'dropout_rate': 0.48350845312530477, 'n_estimators': 29, 'learning_rate': 0.03851620016496923}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24523312723646656
Fold 2 IBS: 0.229723185613947
Fold 3 IBS: 0.22442843425225606
Fold 4 IBS: 0.23930507373382764
Fold 5 IBS: 0.22561689675231322
[I 2024-04-29 14:35:56,132] Trial 84 finished with value: 0.23286134351776208 and parameters: {'subsample': 0.9391372286735271, 'dropout_rate': 0.7005454311271853, 'n_estimators': 11, 'learning_rate': 0.045305296045874244}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24514941845894628
Fold 2 IBS: 0.23097426677943256
Fold 3 IBS: 0.21321839312515653
Fold 4 IBS: 0.23563650043298243
Fold 5 IBS: 0.21670537224711836
[I 2024-04-29 14:35:56,354] Trial 85 finished with value: 0.22833679020872721 and parameters: {'subsample': 0.9188818471752946, 'dropout_rate': 0.5869758072966066, 'n_estimators': 72, 'learning_rate': 0.028543718810406207}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.25886281543552475
Fold 2 IBS: 0.26338319019366113
Fold 3 IBS: 0.2053357366233571
Fold 4 IBS: 0.24336719841646393
Fold 5 IBS: 0.21558389164602595
[I 2024-04-29 14:35:56,577] Trial 86 finished with value: 0.23730656646300657 and parameters: {'subsample': 0.6386231758661289, 'dropout_rate': 0.522971912916216, 'n_estimators': 75, 'learning_rate': 0.06372583418560197}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2468019261172534
Fold 2 IBS: 0.2342724356566972
Fold 3 IBS: 0.21212945370032552
Fold 4 IBS: 0.23659694358347488
Fold 5 IBS: 0.21298659442972162
[I 2024-04-29 14:35:56,893] Trial 87 finished with value: 0.22855747069749452 and parameters: {'subsample': 0.7409902497244855, 'dropout_rate': 0.17971650523934474, 'n_estimators': 98, 'learning_rate': 0.027607893218644312}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2448599637452654
Fold 2 IBS: 0.22925873433048327
Fold 3 IBS: 0.22339962740453295
Fold 4 IBS: 0.23887003822749
Fold 5 IBS: 0.22470824073899348
[I 2024-04-29 14:35:57,035] Trial 88 finished with value: 0.23221932088935304 and parameters: {'subsample': 0.8101290439908051, 'dropout_rate': 0.5917406044901371, 'n_estimators': 39, 'learning_rate': 0.016023124054934286}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2990358132388687
Fold 2 IBS: 0.35550002289261556
Fold 3 IBS: 0.2096416948430116
Fold 4 IBS: 0.26691356382775616
Fold 5 IBS: 0.29193034786438615
[I 2024-04-29 14:35:57,567] Trial 89 finished with value: 0.28460428853332764 and parameters: {'subsample': 0.8934780494874477, 'dropout_rate': 0.50429459388671, 'n_estimators': 167, 'learning_rate': 0.051328475679993595}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2444634114478406
Fold 2 IBS: 0.22873896519824297
Fold 3 IBS: 0.2214969120611723
Fold 4 IBS: 0.23798659904444042
Fold 5 IBS: 0.22279656121126928
[I 2024-04-29 14:35:57,786] Trial 90 finished with value: 0.23109648979259312 and parameters: {'subsample': 0.6967117016542083, 'dropout_rate': 0.3097379426434701, 'n_estimators': 69, 'learning_rate': 0.012434019189597075}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24453756267895457
Fold 2 IBS: 0.22977129635442958
Fold 3 IBS: 0.21467262819163188
Fold 4 IBS: 0.23574771791591095
Fold 5 IBS: 0.21779378123830742
[I 2024-04-29 14:35:57,946] Trial 91 finished with value: 0.2285045972758469 and parameters: {'subsample': 0.9592909657623098, 'dropout_rate': 0.5559687770984751, 'n_estimators': 55, 'learning_rate': 0.03281448767126785}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2448622243481283
Fold 2 IBS: 0.22926245527695382
Fold 3 IBS: 0.22333078529517822
Fold 4 IBS: 0.23877318349086224
Fold 5 IBS: 0.22462691105284333
[I 2024-04-29 14:35:58,046] Trial 92 finished with value: 0.2321711118927932 and parameters: {'subsample': 0.9289126274604125, 'dropout_rate': 0.61884162547743, 'n_estimators': 25, 'learning_rate': 0.025353206012461764}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24429768830990348
Fold 2 IBS: 0.2292610757271472
Fold 3 IBS: 0.21559372721619988
Fold 4 IBS: 0.23590179734873248
Fold 5 IBS: 0.21849540768276
[I 2024-04-29 14:35:58,262] Trial 93 finished with value: 0.22870993925694857 and parameters: {'subsample': 0.99766016156918, 'dropout_rate': 0.7289005942140083, 'n_estimators': 86, 'learning_rate': 0.019127674637257917}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2548640585518277
Fold 2 IBS: 0.24785183907056615
Fold 3 IBS: 0.2060404843167762
Fold 4 IBS: 0.23866534196898706
Fold 5 IBS: 0.2161965792726532
[I 2024-04-29 14:35:58,404] Trial 94 finished with value: 0.23272366063616207 and parameters: {'subsample': 0.8491923109717385, 'dropout_rate': 0.5907106869962908, 'n_estimators': 48, 'learning_rate': 0.08077924912008731}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.247964240607889
Fold 2 IBS: 0.23558193799294086
Fold 3 IBS: 0.2095095112618413
Fold 4 IBS: 0.23611478264375485
Fold 5 IBS: 0.21551534963732294
[I 2024-04-29 14:35:58,590] Trial 95 finished with value: 0.2289371644287498 and parameters: {'subsample': 0.923503338243996, 'dropout_rate': 0.463751241810311, 'n_estimators': 67, 'learning_rate': 0.041087576650381284}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.25774907324467555
Fold 2 IBS: 0.25376517599272247
Fold 3 IBS: 0.20521030031845763
Fold 4 IBS: 0.2404312511654509
Fold 5 IBS: 0.2181295574157114
[I 2024-04-29 14:35:58,919] Trial 96 finished with value: 0.23505707162740358 and parameters: {'subsample': 0.8864859061357513, 'dropout_rate': 0.6526794957298698, 'n_estimators': 112, 'learning_rate': 0.03744789889024919}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.3021531065142074
Fold 2 IBS: 0.3694524880571037
Fold 3 IBS: 0.22691139951124034
Fold 4 IBS: 0.27705217082938327
Fold 5 IBS: 0.2847637022430958
[I 2024-04-29 14:35:59,647] Trial 97 finished with value: 0.29206657343100606 and parameters: {'subsample': 0.5606440507914384, 'dropout_rate': 0.5315723430073316, 'n_estimators': 214, 'learning_rate': 0.04657699840791667}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24422005227775972

Fold 2 IBS: 0.22944440424173224
Fold 3 IBS: 0.21764182536227877
Fold 4 IBS: 0.23713790468486956
Fold 5 IBS: 0.21744623337572327
[I 2024-04-29 14:35:59,771] Trial 98 finished with value: 0.22917808398847272 and parameters: {'subsample': 0.46010644553945257, 'dropout_rate': 0.40281973549646954, 'n_estimators': 31, 'learning_rate': 0.055235910359091894}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2909450482261993
Fold 2 IBS: 0.3516283845294826
Fold 3 IBS: 0.21788174414850223
Fold 4 IBS: 0.2658523928608872
Fold 5 IBS: 0.2652199027303657
[I 2024-04-29 14:36:00,764] Trial 99 finished with value: 0.27830549449908737 and parameters: {'subsample': 0.6151719208120995, 'dropout_rate': 0.631184962372188, 'n_estimators': 278, 'learning_rate': 0.0298041816907381}. Best is trial 44 with value: 0.22803532502111373.


* Best trial for IBS:
 FrozenTrial(number=44, state=TrialState.COMPLETE, values=[0.22803532502111373], datetime_start=datetime.datetime(2024, 4, 29, 14, 35, 42, 864303), datetime_complete=datetime.datetime(2024, 4, 29, 14, 35, 43, 70422), params={'subsample': 0.5795803547524322, 'dropout_rate': 0.5020020877800176, 'n_estimators': 58, 'learning_rate': 0.04508416432006209}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=44, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.5795803547524322, 'dropout_rate': 0.5020020877800176, 'n_estimators': 58, 'learning_rate': 0.04508416432006209}


* Best Score for IBS:
 0.22803532502111373

In [48]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.635
train_ibs:  0.228

#### Test

In [49]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [50]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.23864048613297553,
                                              learning_rate=0.014343382745774179,
                                              n_estimators=433,
                                              random_state=123,
                                              subsample=0.40435140119451696)

C-index score: 0.605

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.5020020877800176,
                                              learning_rate=0.04508416432006209,
                                              n_estimators=58, random_state=123,
                                              subsample=0.5795803547524322)

IBS: 0.218

# Component-Wise Gradient boosting without standardization

In [51]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [52]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-29 14:38:27,715] A new study created in memory with name: no-name-e33cba35-66a9-45d4-b93a-df351c65ce8e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:38:28,050] Trial 0 finished with value: 0.5917375988906803 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.5917375988906803.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:38:30,598] Trial 1 finished with value: 0.5925959679893928 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.5925959679893928.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:38:31,096] Trial 2 finished with value: 0.6222419726464506 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6222419726464506.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:38:31,765] Trial 3 finished with value: 0.6118852688880276 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 2 with value: 0.6222419726464506.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:38:32,803] Trial 4 finished with value: 0.6163104260787672 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 2 with value: 0.6222419726464506.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:38:34,136] Trial 5 finished with value: 0.5917375988906803 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 2 with value: 0.6222419726464506.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:38:34,675] Trial 6 finished with value: 0.5836524925077017 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 2 with value: 0.6222419726464506.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:38:34,781] Trial 7 finished with value: 0.6247066386970771 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.6247066386970771.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:38:35,455] Trial 8 finished with value: 0.6199796693684592 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.6247066386970771.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:38:37,390] Trial 9 finished with value: 0.6333466042580751 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6330472103004292
[I 2024-04-29 14:38:39,278] Trial 10 finished with value: 0.596178251045648 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.9974588415748801, 'n_estimators': 496, 'learning_rate': 0.0017980531969980576}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.592274678111588
[I 2024-04-29 14:38:39,310] Trial 11 finished with value: 0.6187057282661599 and parameters: {'subsample': 0.26668511746186646, 'dropout_rate': 0.7360931942627206, 'n_estimators': 2, 'learning_rate': 0.034819034386896125}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5872093023255814
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.630901287553648
[I 2024-04-29 14:38:40,740] Trial 12 finished with value: 0.6283559631146661 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.7296362277562352, 'n_estimators': 362, 'learning_rate': 0.09635955935176935}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6137339055793991
[I 2024-04-29 14:38:42,232] Trial 13 finished with value: 0.62871433893819 and parameters: {'subsample': 0.11481740539741192, 'dropout_rate': 0.8143837692949045, 'n_estimators': 375, 'learning_rate': 0.09856704475293049}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5910852713178295
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6137339055793991
[I 2024-04-29 14:38:43,632] Trial 14 finished with value: 0.626856543166532 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.991801242062042, 'n_estimators': 396, 'learning_rate': 0.0996464364883083}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6072961373390557
[I 2024-04-29 14:38:45,276] Trial 15 finished with value: 0.6206310700763243 and parameters: {'subsample': 0.36734933589686725, 'dropout_rate': 0.8581965907935476, 'n_estimators': 420, 'learning_rate': 0.08616677729964022}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6330472103004292
[I 2024-04-29 14:38:46,240] Trial 16 finished with value: 0.596178251045648 and parameters: {'subsample': 0.9777827337837477, 'dropout_rate': 0.8624909152762912, 'n_estimators': 305, 'learning_rate': 0.011371764710793174}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:38:48,309] Trial 17 finished with value: 0.5994044786276908 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 447, 'learning_rate': 0.08402672203878299}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:38:49,525] Trial 18 finished with value: 0.6199796693684592 and parameters: {'subsample': 0.6148729728232628, 'dropout_rate': 0.766406147708081, 'n_estimators': 336, 'learning_rate': 0.04272374654273895}. Best is trial 9 with value: 0.6333466042580751.

Fold 1 C-index: 0.5756972111553785
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6158798283261803
[I 2024-04-29 14:38:51,227] Trial 19 finished with value: 0.6196817959296925 and parameters: {'subsample': 0.22885402329391685, 'dropout_rate': 0.9124770129751191, 'n_estimators': 437, 'learning_rate': 0.08677016135502642}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:38:52,209] Trial 20 finished with value: 0.6243190417978524 and parameters: {'subsample': 0.40774041307597547, 'dropout_rate': 0.6345542498709749, 'n_estimators': 282, 'learning_rate': 0.021614670145549512}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6137339055793991
[I 2024-04-29 14:38:53,609] Trial 21 finished with value: 0.6306157632546769 and parameters: {'subsample': 0.11067251758166385, 'dropout_rate': 0.7529813828952502, 'n_estimators': 357, 'learning_rate': 0.09466535337155975}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5717131474103586
Fold 2 C-index: 0.5872093023255814
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6137339055793991
[I 2024-04-29 14:38:55,230] Trial 22 finished with value: 0.6172171379023202 and parameters: {'subsample': 0.18321671152313473, 'dropout_rate': 0.781722125377478, 'n_estimators': 401, 'learning_rate': 0.0893304658757237}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:38:57,203] Trial 23 finished with value: 0.6310135906069662 and parameters: {'subsample': 0.3134015115862535, 'dropout_rate': 0.819015524461123, 'n_estimators': 460, 'learning_rate': 0.09323355252515839}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:38:59,035] Trial 24 finished with value: 0.6215357071701687 and parameters: {'subsample': 0.33235389014851724, 'dropout_rate': 0.9473848068987546, 'n_estimators': 465, 'learning_rate': 0.07580264884510589}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:39:00,291] Trial 25 finished with value: 0.6234606726991399 and parameters: {'subsample': 0.43641547451080515, 'dropout_rate': 0.7209469369114437, 'n_estimators': 334, 'learning_rate': 0.06405829078612202}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:39:02,111] Trial 26 finished with value: 0.6215946572689102 and parameters: {'subsample': 0.3195947405521616, 'dropout_rate': 0.9185990093310807, 'n_estimators': 460, 'learning_rate': 0.08061881908160574}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5756972111553785
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.5879828326180258
[I 2024-04-29 14:39:04,335] Trial 27 finished with value: 0.6132513329582745 and parameters: {'subsample': 0.21170559570821973, 'dropout_rate': 0.8368873118701377, 'n_estimators': 497, 'learning_rate': 0.09047506415972556}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:39:06,098] Trial 28 finished with value: 0.6302458290642766 and parameters: {'subsample': 0.5982716836408275, 'dropout_rate': 0.6659228306382265, 'n_estimators': 412, 'learning_rate': 0.09311864950099345}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:39:07,342] Trial 29 finished with value: 0.6255924838656682 and parameters: {'subsample': 0.28951917928546445, 'dropout_rate': 0.5890093843634112, 'n_estimators': 323, 'learning_rate': 0.06030328222321476}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5872093023255814
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6137339055793991
[I 2024-04-29 14:39:09,394] Trial 30 finished with value: 0.6227677016049565 and parameters: {'subsample': 0.16933761215258794, 'dropout_rate': 0.7011912658052524, 'n_estimators': 456, 'learning_rate': 0.049069254157529336}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:39:11,206] Trial 31 finished with value: 0.6302458290642766 and parameters: {'subsample': 0.6187725536932623, 'dropout_rate': 0.665568074915336, 'n_estimators': 418, 'learning_rate': 0.09405100139041776}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:39:12,733] Trial 32 finished with value: 0.6293947652344893 and parameters: {'subsample': 0.5610949707508698, 'dropout_rate': 0.79145297673865, 'n_estimators': 395, 'learning_rate': 0.07982352619429185}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:39:15,174] Trial 33 finished with value: 0.6324955404282878 and parameters: {'subsample': 0.4450156970414007, 'dropout_rate': 0.5069872995126141, 'n_estimators': 480, 'learning_rate': 0.06601805985192355}. Best is trial 9 with value: 0.6333466042580751.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:39:17,696] Trial 34 finished with value: 0.6341217980565247 and parameters: {'subsample': 0.45815942201743926, 'dropout_rate': 0.5051054684842515, 'n_estimators': 483, 'learning_rate': 0.05659773901482257}. Best is trial 34 with value: 0.6341217980565247.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:39:20,159] Trial 35 finished with value: 0.6258399543453808 and parameters: {'subsample': 0.4630994189387855, 'dropout_rate': 0.43975685710717877, 'n_estimators': 473, 'learning_rate': 0.05444087336650833}. Best is trial 34 with value: 0.6341217980565247.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:39:20,515] Trial 36 finished with value: 0.6222419726464506 and parameters: {'subsample': 0.5179091035612071, 'dropout_rate': 0.49155216598172585, 'n_estimators': 129, 'learning_rate': 0.06746790032863402}. Best is trial 34 with value: 0.6341217980565247.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:39:23,236] Trial 37 finished with value: 0.6265414605204036 and parameters: {'subsample': 0.4069798680259253, 'dropout_rate': 0.3069232179349009, 'n_estimators': 478, 'learning_rate': 0.04780416659794717}. Best is trial 34 with value: 0.6341217980565247.

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:39:25,829] Trial 38 finished with value: 0.6342049733567876 and parameters: {'subsample': 0.5453560802294278, 'dropout_rate': 0.4972898985304796, 'n_estimators': 497, 'learning_rate': 0.07067813603949202}. Best is trial 38 with value: 0.6342049733567876.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:39:27,943] Trial 39 finished with value: 0.5917375988906803 and parameters: {'subsample': 0.6942999178388414, 'dropout_rate': 0.5085280680660397, 'n_estimators': 437, 'learning_rate': 0.06892741183938003}. Best is trial 38 with value: 0.6342049733567876.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:39:30,525] Trial 40 finished with value: 0.6342049733567876 and parameters: {'subsample': 0.5413010064104317, 'dropout_rate': 0.36258476627571945, 'n_estimators': 479, 'learning_rate': 0.05679057110376962}. Best is trial 38 with value: 0.6342049733567876.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:39:33,396] Trial 41 finished with value: 0.6311041981629891 and parameters: {'subsample': 0.5534750932074091, 'dropout_rate': 0.3978806729388474, 'n_estimators': 499, 'learning_rate': 0.0584838167040163}. Best is trial 38 with value: 0.6342049733567876.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:39:35,782] Trial 42 finished with value: 0.6361135462969584 and parameters: {'subsample': 0.4849906311710536, 'dropout_rate': 0.13661676516072546, 'n_estimators': 432, 'learning_rate': 0.06911254892370094}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:39:38,177] Trial 43 finished with value: 0.635063469442335 and parameters: {'subsample': 0.49688960157673584, 'dropout_rate': 0.13091523357680807, 'n_estimators': 432, 'learning_rate': 0.07109870809092152}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:39:40,994] Trial 44 finished with value: 0.6145311500507 and parameters: {'subsample': 0.658681123840967, 'dropout_rate': 0.12176369536773762, 'n_estimators': 427, 'learning_rate': 0.0727532931890621}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:39:42,887] Trial 45 finished with value: 0.5972768190532227 and parameters: {'subsample': 0.7634152448919623, 'dropout_rate': 0.19472233140546097, 'n_estimators': 376, 'learning_rate': 0.057439215177340436}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:39:43,845] Trial 46 finished with value: 0.6311041981629891 and parameters: {'subsample': 0.5118389988631302, 'dropout_rate': 0.212300133020975, 'n_estimators': 249, 'learning_rate': 0.07148211059963555}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:39:46,260] Trial 47 finished with value: 0.6187536005534275 and parameters: {'subsample': 0.5811516637829063, 'dropout_rate': 0.33162472953612, 'n_estimators': 432, 'learning_rate': 0.06366543830537712}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:39:48,261] Trial 48 finished with value: 0.6298308830820082 and parameters: {'subsample': 0.38974920537599356, 'dropout_rate': 0.11434042688093632, 'n_estimators': 393, 'learning_rate': 0.07791994426884381}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:39:51,225] Trial 49 finished with value: 0.6258399543453808 and parameters: {'subsample': 0.48393328639574085, 'dropout_rate': 0.25940607837958385, 'n_estimators': 499, 'learning_rate': 0.043368630996759236}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:39:51,612] Trial 50 finished with value: 0.6222419726464506 and parameters: {'subsample': 0.5411531862260708, 'dropout_rate': 0.4326780653706334, 'n_estimators': 143, 'learning_rate': 0.05227600540304314}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:39:51,826] Trial 51 finished with value: 0.6111174438519207 and parameters: {'subsample': 0.48269225781594943, 'dropout_rate': 0.18601220610700475, 'n_estimators': 84, 'learning_rate': 0.03837723204348136}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:39:54,315] Trial 52 finished with value: 0.6302458290642766 and parameters: {'subsample': 0.6400507235683557, 'dropout_rate': 0.5565339805013417, 'n_estimators': 476, 'learning_rate': 0.056537985421675416}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:39:56,788] Trial 53 finished with value: 0.6311631482617306 and parameters: {'subsample': 0.42934735248116007, 'dropout_rate': 0.26389388446583406, 'n_estimators': 442, 'learning_rate': 0.06124948532913528}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:39:59,314] Trial 54 finished with value: 0.634972861886312 and parameters: {'subsample': 0.5133496105759869, 'dropout_rate': 0.1495897230999219, 'n_estimators': 452, 'learning_rate': 0.07001607460750953}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:02,235] Trial 55 finished with value: 0.6217712004469631 and parameters: {'subsample': 0.5750421640979936, 'dropout_rate': 0.15105403923216587, 'n_estimators': 451, 'learning_rate': 0.06853125607362928}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:05,138] Trial 56 finished with value: 0.5925959679893928 and parameters: {'subsample': 0.7051453552878142, 'dropout_rate': 0.21843395076903116, 'n_estimators': 486, 'learning_rate': 0.07116533495268493}. Best is trial 42 with value: 0.6361135462969584.

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:06,881] Trial 57 finished with value: 0.6345925702560125 and parameters: {'subsample': 0.5233438932381355, 'dropout_rate': 0.3762710862713907, 'n_estimators': 379, 'learning_rate': 0.07586937026396535}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:08,586] Trial 58 finished with value: 0.6345925702560125 and parameters: {'subsample': 0.5277795525684075, 'dropout_rate': 0.37345315628940196, 'n_estimators': 376, 'learning_rate': 0.07559246299662443}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:10,350] Trial 59 finished with value: 0.6342049733567876 and parameters: {'subsample': 0.5100214722051727, 'dropout_rate': 0.28657996747107134, 'n_estimators': 375, 'learning_rate': 0.08274267892478711}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:11,242] Trial 60 finished with value: 0.5917375988906803 and parameters: {'subsample': 0.7562626107679946, 'dropout_rate': 0.15353349182553722, 'n_estimators': 239, 'learning_rate': 0.07607638430182652}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:12,942] Trial 61 finished with value: 0.6349801671552372 and parameters: {'subsample': 0.5325046387013413, 'dropout_rate': 0.3593053139030924, 'n_estimators': 352, 'learning_rate': 0.07531580657341323}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:14,563] Trial 62 finished with value: 0.6152127252947721 and parameters: {'subsample': 0.5971920761184659, 'dropout_rate': 0.38067468287763806, 'n_estimators': 354, 'learning_rate': 0.07434044809181034}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:16,067] Trial 63 finished with value: 0.6247587473772718 and parameters: {'subsample': 0.3653320381947933, 'dropout_rate': 0.22755460535835598, 'n_estimators': 317, 'learning_rate': 0.08418894138741267}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:18,057] Trial 64 finished with value: 0.6345925702560125 and parameters: {'subsample': 0.5234445718064461, 'dropout_rate': 0.465330741888738, 'n_estimators': 409, 'learning_rate': 0.07848298496979106}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:20,190] Trial 65 finished with value: 0.6288817794404379 and parameters: {'subsample': 0.494517686727131, 'dropout_rate': 0.3393352106689162, 'n_estimators': 408, 'learning_rate': 0.07909809863774273}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:21,788] Trial 66 finished with value: 0.6028621276852103 and parameters: {'subsample': 0.6265275246180745, 'dropout_rate': 0.4036021612767674, 'n_estimators': 348, 'learning_rate': 0.08783881908904274}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:23,042] Trial 67 finished with value: 0.6333466042580751 and parameters: {'subsample': 0.4261425486884364, 'dropout_rate': 0.45441713161198816, 'n_estimators': 302, 'learning_rate': 0.0755695835335528}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:25,134] Trial 68 finished with value: 0.6227054395770131 and parameters: {'subsample': 0.5256374815520721, 'dropout_rate': 0.17546789850888253, 'n_estimators': 387, 'learning_rate': 0.08283841190519067}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:27,008] Trial 69 finished with value: 0.6325861479843109 and parameters: {'subsample': 0.46878596564826375, 'dropout_rate': 0.30667170647870656, 'n_estimators': 371, 'learning_rate': 0.06541641608816408}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:29,395] Trial 70 finished with value: 0.6358239257160992 and parameters: {'subsample': 0.5827484852995268, 'dropout_rate': 0.10427268883013434, 'n_estimators': 419, 'learning_rate': 0.07876865968361957}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:31,655] Trial 71 finished with value: 0.6127436379867401 and parameters: {'subsample': 0.5853860288378935, 'dropout_rate': 0.14713067451462233, 'n_estimators': 412, 'learning_rate': 0.07714701288303102}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:33,755] Trial 72 finished with value: 0.6321195571722262 and parameters: {'subsample': 0.5133497129011574, 'dropout_rate': 0.12905263242584386, 'n_estimators': 385, 'learning_rate': 0.08145129398164956}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:35,453] Trial 73 finished with value: 0.6358239257160992 and parameters: {'subsample': 0.5600876237212229, 'dropout_rate': 0.10664219314531707, 'n_estimators': 343, 'learning_rate': 0.07324769460521192}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:37,172] Trial 74 finished with value: 0.6040881965002421 and parameters: {'subsample': 0.6503894154974534, 'dropout_rate': 0.17675021425997176, 'n_estimators': 347, 'learning_rate': 0.06298116345261415}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.6996197718631179

Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:38,387] Trial 75 finished with value: 0.6358239257160992 and parameters: {'subsample': 0.5701616531852751, 'dropout_rate': 0.11490212240638177, 'n_estimators': 281, 'learning_rate': 0.07280941125087963}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6574468085106383
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:39,166] Trial 76 finished with value: 0.6149166013392197 and parameters: {'subsample': 0.6831917512544952, 'dropout_rate': 0.10087042858262829, 'n_estimators': 213, 'learning_rate': 0.06939450458519471}. Best is trial 42 with value: 0.6361135462969584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:40,463] Trial 77 finished with value: 0.6375260533756737 and parameters: {'subsample': 0.6041281149368098, 'dropout_rate': 0.13043751886361774, 'n_estimators': 295, 'learning_rate': 0.0731628945269444}. Best is trial 77 with value: 0.6375260533756737.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6659574468085107
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:41,621] Trial 78 finished with value: 0.6392354863041735 and parameters: {'subsample': 0.6113433675015852, 'dropout_rate': 0.1372634977863254, 'n_estimators': 274, 'learning_rate': 0.07265284090996345}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:42,873] Trial 79 finished with value: 0.6358239257160992 and parameters: {'subsample': 0.6069092743582164, 'dropout_rate': 0.10461839299581534, 'n_estimators': 276, 'learning_rate': 0.07296683177143021}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:44,046] Trial 80 finished with value: 0.6278045172868113 and parameters: {'subsample': 0.7248759711569909, 'dropout_rate': 0.13139739731503716, 'n_estimators': 277, 'learning_rate': 0.08588738056338155}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:45,337] Trial 81 finished with value: 0.6358239257160992 and parameters: {'subsample': 0.6088186152513346, 'dropout_rate': 0.10107473249244987, 'n_estimators': 291, 'learning_rate': 0.07355397482275858}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:46,674] Trial 82 finished with value: 0.6358312309850245 and parameters: {'subsample': 0.6167580525516468, 'dropout_rate': 0.10180193249834459, 'n_estimators': 291, 'learning_rate': 0.07277758399963459}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:47,992] Trial 83 finished with value: 0.634972861886312 and parameters: {'subsample': 0.6106572542891939, 'dropout_rate': 0.1057062840470816, 'n_estimators': 300, 'learning_rate': 0.0664752021482888}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:49,131] Trial 84 finished with value: 0.5925959679893928 and parameters: {'subsample': 0.7899622418563101, 'dropout_rate': 0.16730056351280853, 'n_estimators': 264, 'learning_rate': 0.07378952529856436}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:50,305] Trial 85 finished with value: 0.6349801671552372 and parameters: {'subsample': 0.5587642283775051, 'dropout_rate': 0.20529355154590012, 'n_estimators': 282, 'learning_rate': 0.08118501451564682}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:51,282] Trial 86 finished with value: 0.5917375988906803 and parameters: {'subsample': 0.6716581049558615, 'dropout_rate': 0.24245908097267627, 'n_estimators': 237, 'learning_rate': 0.07364310163601318}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6574468085106383
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:40:52,917] Trial 87 finished with value: 0.637533358644599 and parameters: {'subsample': 0.6342924934527452, 'dropout_rate': 0.10157165664947933, 'n_estimators': 292, 'learning_rate': 0.06662565512194621}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:54,070] Trial 88 finished with value: 0.6337342011573 and parameters: {'subsample': 0.6350482367083102, 'dropout_rate': 0.13320160378818602, 'n_estimators': 266, 'learning_rate': 0.06729827262173783}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:55,720] Trial 89 finished with value: 0.6225760825185448 and parameters: {'subsample': 0.5718986244511678, 'dropout_rate': 0.16842402850180557, 'n_estimators': 335, 'learning_rate': 0.025056796383218}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:57,406] Trial 90 finished with value: 0.6020037585864978 and parameters: {'subsample': 0.7147405584008215, 'dropout_rate': 0.19399377780533764, 'n_estimators': 315, 'learning_rate': 0.059660645167501136}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:40:58,735] Trial 91 finished with value: 0.6358239257160992 and parameters: {'subsample': 0.6099968232758255, 'dropout_rate': 0.10431630765889505, 'n_estimators': 291, 'learning_rate': 0.07290399695772522}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:41:00,028] Trial 92 finished with value: 0.6264161351189943 and parameters: {'subsample': 0.6594008607972726, 'dropout_rate': 0.12066678289098301, 'n_estimators': 293, 'learning_rate': 0.06367939232377062}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6574468085106383
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:41:01,117] Trial 93 finished with value: 0.637533358644599 and parameters: {'subsample': 0.5967653060783058, 'dropout_rate': 0.10238879647369425, 'n_estimators': 248, 'learning_rate': 0.07962091480647304}. Best is trial 78 with value: 0.6392354863041735.

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:41:02,259] Trial 94 finished with value: 0.6242358664975894 and parameters: {'subsample': 0.5829225965792446, 'dropout_rate': 0.14162083461988964, 'n_estimators': 254, 'learning_rate': 0.08989544431739743}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:41:03,081] Trial 95 finished with value: 0.6337342011573 and parameters: {'subsample': 0.6351244505153065, 'dropout_rate': 0.15809573640216013, 'n_estimators': 229, 'learning_rate': 0.07979187896116087}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6702127659574468
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:41:04,116] Trial 96 finished with value: 0.6179354053698489 and parameters: {'subsample': 0.6772636468652146, 'dropout_rate': 0.12157170556109578, 'n_estimators': 265, 'learning_rate': 0.07759811094477673}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:41:04,803] Trial 97 finished with value: 0.6208380384671717 and parameters: {'subsample': 0.5606440507914384, 'dropout_rate': 0.23794763386225515, 'n_estimators': 201, 'learning_rate': 0.08548943695542902}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6201716738197425
[I 2024-04-29 14:41:06,236] Trial 98 finished with value: 0.6209960066485134 and parameters: {'subsample': 0.5932641277864622, 'dropout_rate': 0.1939895143131861, 'n_estimators': 310, 'learning_rate': 0.07127865453535114}. Best is trial 78 with value: 0.6392354863041735.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6482889733840305

[I 2024-04-29 14:41:07,681] A new study created in memory with name: no-name-2655df24-7914-44b6-8512-c255b795601e

Fold 5 C-index: 0.6244635193133047
[I 2024-04-29 14:41:07,678] Trial 99 finished with value: 0.6247140074594197 and parameters: {'subsample': 0.6252722390084534, 'dropout_rate': 0.16317995421555712, 'n_estimators': 324, 'learning_rate': 0.06507270713965135}. Best is trial 78 with value: 0.6392354863041735.


* Best trial for C-index:
 FrozenTrial(number=78, state=TrialState.COMPLETE, values=[0.6392354863041735], datetime_start=datetime.datetime(2024, 4, 29, 14, 40, 40, 465713), datetime_complete=datetime.datetime(2024, 4, 29, 14, 40, 41, 621678), params={'subsample': 0.6113433675015852, 'dropout_rate': 0.1372634977863254, 'n_estimators': 274, 'learning_rate': 0.07265284090996345}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=78, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.6113433675015852, 'dropout_rate': 0.1372634977863254, 'n_estimators': 274, 'learning_rate': 0.07265284090996345}


* Best Score for C-index:
 0.6392354863041735

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2768605959166274
Fold 2 IBS: 0.3002240901900513
Fold 3 IBS: 0.20816241232849142
Fold 4 IBS: 0.25164204958791786
Fold 5 IBS: 0.23049650269649638
[I 2024-04-29 14:41:07,995] Trial 0 finished with value: 0.2534771301439169 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2534771301439169.
Fold 1 IBS: 0.3314083926697305
Fold 2 IBS: 0.3801225465459666
Fold 3 IBS: 0.26584323394581666
Fold 4 IBS: 0.307376218934207
Fold 5 IBS: 0.339376702626222
[I 2024-04-29 14:41:10,729] Trial 1 finished with value: 0.32482541894438854 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2534771301439169.
Fold 1 IBS: 0.30929438977780943
Fold 2 IBS: 0.3776592383257721
Fold 3 IBS: 0.23149355642930963
Fold 4 IBS: 0.2817930937252389
Fold 5 IBS: 0.3100934076743383
[I 2024-04-29 14:41:11,467] Trial 2 finished with value: 0.3020667371864937 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2534771301439169.
Fold 1 IBS: 0.3109416169448545
Fold 2 IBS: 0.3783699302877189
Fold 3 IBS: 0.23826415829830536
Fold 4 IBS: 0.2985696556063963
Fold 5 IBS: 0.2671809615732079
[I 2024-04-29 14:41:12,210] Trial 3 finished with value: 0.29866526454209663 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2534771301439169.
Fold 1 IBS: 0.3175766748007208
Fold 2 IBS: 0.3791283849019784
Fold 3 IBS: 0.2495340925559205
Fold 4 IBS: 0.3120588562921934
Fold 5 IBS: 0.28457009062304117
[I 2024-04-29 14:41:13,283] Trial 4 finished with value: 0.3085736198347709 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2534771301439169.
Fold 1 IBS: 0.3332145305423825
Fold 2 IBS: 0.38011990649983673
Fold 3 IBS: 0.25198997521142397
Fold 4 IBS: 0.3079558871281474
Fold 5 IBS: 0.33923818447315957
[I 2024-04-29 14:41:14,570] Trial 5 finished with value: 0.32250369677099006 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2534771301439169.
Fold 1 IBS: 0.2583770894605203
Fold 2 IBS: 0.2538208871784848
Fold 3 IBS: 0.20728964004289857
Fold 4 IBS: 0.24061910572279663
Fold 5 IBS: 0.21760040361445157
[I 2024-04-29 14:41:15,136] Trial 6 finished with value: 0.23554142520383037 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.23554142520383037.
Fold 1 IBS: 0.24449081430179984
Fold 2 IBS: 0.23006896862415954
Fold 3 IBS: 0.21843183660549986
Fold 4 IBS: 0.2386186364141431
Fold 5 IBS: 0.21471613571364556
[I 2024-04-29 14:41:15,249] Trial 7 finished with value: 0.22926527833184956 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.22926527833184956.
Fold 1 IBS: 0.2749667055201454
Fold 2 IBS: 0.31722578035710736
Fold 3 IBS: 0.2145310231981918
Fold 4 IBS: 0.2588310393109894
Fold 5 IBS: 0.22610047650933945
[I 2024-04-29 14:41:15,914] Trial 8 finished with value: 0.2583310049791547 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.22926527833184956.
Fold 1 IBS: 0.31868958253133545
Fold 2 IBS: 0.38012170435921
Fold 3 IBS: 0.2744945823733866
Fold 4 IBS: 0.3364877264983839
Fold 5 IBS: 0.3390266035749277
[I 2024-04-29 14:41:17,793] Trial 9 finished with value: 0.32976403986744873 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.22926527833184956.
Fold 1 IBS: 0.2470353461515696
Fold 2 IBS: 0.23180355778544998
Fold 3 IBS: 0.22856182093970995
Fold 4 IBS: 0.24171407848753257
Fold 5 IBS: 0.22906264846898927
[I 2024-04-29 14:41:17,873] Trial 10 finished with value: 0.2356354903666503 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.22926527833184956.
Fold 1 IBS: 0.24687652993070414
Fold 2 IBS: 0.23195400682301584
Fold 3 IBS: 0.22803828196828552
Fold 4 IBS: 0.24151517366938874
Fold 5 IBS: 0.22870297189521768
[I 2024-04-29 14:41:17,916] Trial 11 finished with value: 0.23541739285732238 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.22926527833184956.
Fold 1 IBS: 0.2559176517311384
Fold 2 IBS: 0.2408424701387146
Fold 3 IBS: 0.2057974255759873
Fold 4 IBS: 0.25662445768595
Fold 5 IBS: 0.2015907866160034
[I 2024-04-29 14:41:18,060] Trial 12 finished with value: 0.23215455834955873 and parameters: {'subsample': 0.11320521666185814, 'dropout_rate': 0.7125180266624932, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.22926527833184956.
Fold 1 IBS: 0.2800922811587031
Fold 2 IBS: 0.29247713883649645
Fold 3 IBS: 0.20705019878210726
Fold 4 IBS: 0.275614717185453
Fold 5 IBS: 0.20539603146722382
[I 2024-04-29 14:41:18,281] Trial 13 finished with value: 0.25212607348599675 and parameters: {'subsample': 0.11038782630303162, 'dropout_rate': 0.695526957994077, 'n_estimators': 86, 'learning_rate': 0.09856277651579823}. Best is trial 7 with value: 0.22926527833184956.
Fold 1 IBS: 0.2783478728038267
Fold 2 IBS: 0.3342314139254011
Fold 3 IBS: 0.23173311781309966
Fold 4 IBS: 0.2616408969360102
Fold 5 IBS: 0.21705815477853624
[I 2024-04-29 14:41:18,486] Trial 14 finished with value: 0.2646022912513748 and parameters: {'subsample': 0.29524115835831166, 'dropout_rate': 0.6355856554810184, 'n_estimators': 79, 'learning_rate': 0.09964553963945819}. Best is trial 7 with value: 0.22926527833184956.
Fold 1 IBS: 0.29329022035532154
Fold 2 IBS: 0.37074771501252135
Fold 3 IBS: 0.252613714528157
Fold 4 IBS: 0.27635584162827065
Fold 5 IBS: 0.2610562316562823
[I 2024-04-29 14:41:18,793] Trial 15 finished with value: 0.2908127446361106 and parameters: {'subsample': 0.3113782463318137, 'dropout_rate': 0.8117973140879879, 'n_estimators': 122, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.22926527833184956.
Fold 1 IBS: 0.3012315390796449
Fold 2 IBS: 0.3772310185796683
Fold 3 IBS: 0.2381438544324291
Fold 4 IBS: 0.2861940167516203
Fold 5 IBS: 0.2890780663430509
[I 2024-04-29 14:41:19,686] Trial 16 finished with value: 0.29837569903728267 and parameters: {'subsample': 0.3629956613085432, 'dropout_rate': 0.9733961081825167, 'n_estimators': 297, 'learning_rate': 0.040259456601039204}. Best is trial 7 with value: 0.22926527833184956.
Fold 1 IBS: 0.24563146104041864
Fold 2 IBS: 0.22906388180636858
Fold 3 IBS: 0.22565127774252322
Fold 4 IBS: 0.24034510101757345
Fold 5 IBS: 0.22514199878139385
[I 2024-04-29 14:41:19,806] Trial 17 finished with value: 0.23316674407765553 and parameters: {'subsample': 0.2104307286176502, 'dropout_rate': 0.6004730897368156, 'n_estimators': 44, 'learning_rate': 0.01245288911484009}. Best is trial 7 with value: 0.22926527833184956.
Fold 1 IBS: 0.3038447457237408
Fold 2 IBS: 0.3787167644577537
Fold 3 IBS: 0.24112393055308448
Fold 4 IBS: 0.2886953743417636
Fold 5 IBS: 0.3052906347214811
[I 2024-04-29 14:41:21,013] Trial 18 finished with value: 0.3035342899595648 and parameters: {'subsample': 0.39635847792734874, 'dropout_rate': 0.7904615013324701, 'n_estimators': 336, 'learning_rate': 0.03935603162728128}. Best is trial 7 with value: 0.22926527833184956.
Fold 1 IBS: 0.30796444109430066
Fold 2 IBS: 0.373115983039534
Fold 3 IBS: 0.2420883508635342

Fold 4 IBS: 0.28714816670838966
Fold 5 IBS: 0.26850778872891123
[I 2024-04-29 14:41:21,342] Trial 19 finished with value: 0.29576494608693393 and parameters: {'subsample': 0.19625604601881638, 'dropout_rate': 0.9930703343219778, 'n_estimators': 132, 'learning_rate': 0.08681602954259124}. Best is trial 7 with value: 0.22926527833184956.
Fold 1 IBS: 0.2449490755369921
Fold 2 IBS: 0.23136100805221904
Fold 3 IBS: 0.21231495466727224
Fold 4 IBS: 0.23604030462642991
Fold 5 IBS: 0.2158097056778787
[I 2024-04-29 14:41:21,477] Trial 20 finished with value: 0.2280950097121584 and parameters: {'subsample': 0.6102628884762309, 'dropout_rate': 0.5558690358940764, 'n_estimators': 52, 'learning_rate': 0.04127909023805986}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.2456074604293363
Fold 2 IBS: 0.23302758221566516
Fold 3 IBS: 0.21178731577318305
Fold 4 IBS: 0.23616214029004035
Fold 5 IBS: 0.21454946703754782
[I 2024-04-29 14:41:21,625] Trial 21 finished with value: 0.22822679314915453 and parameters: {'subsample': 0.6362748427966717, 'dropout_rate': 0.5537934605115938, 'n_estimators': 57, 'learning_rate': 0.042594274103339054}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.2468352225471468
Fold 2 IBS: 0.23163047416289245
Fold 3 IBS: 0.22806067269720692
Fold 4 IBS: 0.24153941398634782
Fold 5 IBS: 0.22872743236025306
[I 2024-04-29 14:41:21,674] Trial 22 finished with value: 0.2353586431507694 and parameters: {'subsample': 0.6446807593774737, 'dropout_rate': 0.5405657270190689, 'n_estimators': 2, 'learning_rate': 0.041924521216552206}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.24415137088179711
Fold 2 IBS: 0.22896418157002804
Fold 3 IBS: 0.21651253910004936
Fold 4 IBS: 0.23617149577931876
Fold 5 IBS: 0.21884026812506485
[I 2024-04-29 14:41:21,862] Trial 23 finished with value: 0.2289279710912516 and parameters: {'subsample': 0.845000450042138, 'dropout_rate': 0.6011576435519733, 'n_estimators': 75, 'learning_rate': 0.02050909287157107}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.24747507514656247
Fold 2 IBS: 0.2346759853394555
Fold 3 IBS: 0.21005912454576894
Fold 4 IBS: 0.2359349333618713
Fold 5 IBS: 0.21558923969214738
[I 2024-04-29 14:41:22,288] Trial 24 finished with value: 0.22874687161716115 and parameters: {'subsample': 0.8816354096299833, 'dropout_rate': 0.4736976824144059, 'n_estimators': 151, 'learning_rate': 0.01744685233233402}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.2450399699116292
Fold 2 IBS: 0.23054691370598748
Fold 3 IBS: 0.21341569101253346
Fold 4 IBS: 0.2356596516944834
Fold 5 IBS: 0.21687516831926096
[I 2024-04-29 14:41:22,721] Trial 25 finished with value: 0.2283074789287789 and parameters: {'subsample': 0.8615354277037236, 'dropout_rate': 0.33002777578250453, 'n_estimators': 150, 'learning_rate': 0.013287182579533728}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.24416031536301983
Fold 2 IBS: 0.22858297659141266
Fold 3 IBS: 0.2191858171765639
Fold 4 IBS: 0.23688569851759222
Fold 5 IBS: 0.21943435460803837
[I 2024-04-29 14:41:23,504] Trial 26 finished with value: 0.22964983245132536 and parameters: {'subsample': 0.6105109961473616, 'dropout_rate': 0.2968233742660247, 'n_estimators': 223, 'learning_rate': 0.006055302272548541}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.25128908338088746
Fold 2 IBS: 0.24070947293140157
Fold 3 IBS: 0.20725991587536327
Fold 4 IBS: 0.23777584314425831
Fold 5 IBS: 0.21163665570734816
[I 2024-04-29 14:41:23,790] Trial 27 finished with value: 0.22973419420785177 and parameters: {'subsample': 0.8398584734126338, 'dropout_rate': 0.14675521376839798, 'n_estimators': 105, 'learning_rate': 0.03331972458281015}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.24455525449021756
Fold 2 IBS: 0.2298216068086644
Fold 3 IBS: 0.21460108895763946
Fold 4 IBS: 0.23573240564215303
Fold 5 IBS: 0.21780387720772504
[I 2024-04-29 14:41:24,328] Trial 28 finished with value: 0.2285028466212799 and parameters: {'subsample': 0.9559728467548972, 'dropout_rate': 0.2751676654520265, 'n_estimators': 172, 'learning_rate': 0.0105021530498218}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.2808254177062342
Fold 2 IBS: 0.3187168367886179
Fold 3 IBS: 0.20984521157536817
Fold 4 IBS: 0.2580444564862806
Fold 5 IBS: 0.22506586042479979
[I 2024-04-29 14:41:24,646] Trial 29 finished with value: 0.2584995565962601 and parameters: {'subsample': 0.5790219222156496, 'dropout_rate': 0.3815154452983834, 'n_estimators': 117, 'learning_rate': 0.06046208382653473}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.26146402605521446
Fold 2 IBS: 0.2604755187725914
Fold 3 IBS: 0.20837603514686806
Fold 4 IBS: 0.24215594077513308
Fold 5 IBS: 0.2154703228797978
[I 2024-04-29 14:41:25,050] Trial 30 finished with value: 0.23758836872592098 and parameters: {'subsample': 0.767234520408729, 'dropout_rate': 0.3183736233152148, 'n_estimators': 140, 'learning_rate': 0.03323495442553544}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.2522239742075012
Fold 2 IBS: 0.24255312804089282
Fold 3 IBS: 0.20708197928091748
Fold 4 IBS: 0.23776524444696442
Fold 5 IBS: 0.21549378665148
[I 2024-04-29 14:41:25,988] Trial 31 finished with value: 0.23102362252555117 and parameters: {'subsample': 0.9488701920274671, 'dropout_rate': 0.2254080891043035, 'n_estimators': 250, 'learning_rate': 0.013875386268940266}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.24414628501312183
Fold 2 IBS: 0.22888264504244957
Fold 3 IBS: 0.21650445345502967
Fold 4 IBS: 0.23608118249922197
Fold 5 IBS: 0.21917014151931988
[I 2024-04-29 14:41:26,511] Trial 32 finished with value: 0.22895694150582857 and parameters: {'subsample': 0.9076317444937305, 'dropout_rate': 0.42686358838527455, 'n_estimators': 172, 'learning_rate': 0.008816482293041801}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.24681969500828446
Fold 2 IBS: 0.2336419199276687
Fold 3 IBS: 0.21132588678606373
Fold 4 IBS: 0.23595592967491638
Fold 5 IBS: 0.21284470130032399
[I 2024-04-29 14:41:26,763] Trial 33 finished with value: 0.22811762653945147 and parameters: {'subsample': 0.8017872389711715, 'dropout_rate': 0.10331660131014647, 'n_estimators': 93, 'learning_rate': 0.027997278046075002}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.24599845940787407
Fold 2 IBS: 0.23332028669109128
Fold 3 IBS: 0.2129316728460386
Fold 4 IBS: 0.23638229490553092
Fold 5 IBS: 0.21390593413557019
[I 2024-04-29 14:41:27,011] Trial 34 finished with value: 0.22850772959722102 and parameters: {'subsample': 0.7061901100242275, 'dropout_rate': 0.20729522975477116, 'n_estimators': 92, 'learning_rate': 0.026577796841169156}. Best is trial 20 with value: 0.2280950097121584.
Fold 1 IBS: 0.24656043671364655
Fold 2 IBS: 0.23328040131519792
Fold 3 IBS: 0.21172898259165365
Fold 4 IBS: 0.23619794635763308
Fold 5 IBS: 0.21253604448197963
[I 2024-04-29 14:41:27,158] Trial 35 finished with value: 0.22806076229202218 and parameters: {'subsample': 0.7854455042547966, 'dropout_rate': 0.1092492198220138, 'n_estimators': 56, 'learning_rate': 0.04607205194818506}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.2441206397848643
Fold 2 IBS: 0.22868252456635438
Fold 3 IBS: 0.2180489664073654
Fold 4 IBS: 0.2364152502429355
Fold 5 IBS: 0.21869060841408625
[I 2024-04-29 14:41:27,251] Trial 36 finished with value: 0.22919159788312116 and parameters: {'subsample': 0.801658788675615, 'dropout_rate': 0.14186038312840116, 'n_estimators': 31, 'learning_rate': 0.04850024622187401}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.24881676462270133
Fold 2 IBS: 0.23749791223755973
Fold 3 IBS: 0.2100876629202238
Fold 4 IBS: 0.23866806950142685
Fold 5 IBS: 0.20878260429623374
[I 2024-04-29 14:41:27,398] Trial 37 finished with value: 0.22877060271562905 and parameters: {'subsample': 0.6849019118508213, 'dropout_rate': 0.11688266636616183, 'n_estimators': 56, 'learning_rate': 0.059207327336158105}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.24493766598617653
Fold 2 IBS: 0.22922896427700137
Fold 3 IBS: 0.22295058319940333
Fold 4 IBS: 0.23865852277308305
Fold 5 IBS: 0.2238677521863841
[I 2024-04-29 14:41:27,464] Trial 38 finished with value: 0.2319286976844097 and parameters: {'subsample': 0.5343048414802583, 'dropout_rate': 0.19601280460519543, 'n_estimators': 15, 'learning_rate': 0.04722630186483913}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.2616929141865961
Fold 2 IBS: 0.2584746420928571
Fold 3 IBS: 0.20509225002521414
Fold 4 IBS: 0.24255128592615663

Fold 5 IBS: 0.22016369088716634
[I 2024-04-29 14:41:27,627] Trial 39 finished with value: 0.23759495662359806 and parameters: {'subsample': 0.7913354503723935, 'dropout_rate': 0.49942804580714845, 'n_estimators': 66, 'learning_rate': 0.06892741183938003}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.3274822159175251
Fold 2 IBS: 0.3801203890074418
Fold 3 IBS: 0.26275327867621484
Fold 4 IBS: 0.302592865334411
Fold 5 IBS: 0.33915386361994393
[I 2024-04-29 14:41:29,753] Trial 40 finished with value: 0.3224205225111073 and parameters: {'subsample': 0.635202567294034, 'dropout_rate': 0.4193126238717278, 'n_estimators': 434, 'learning_rate': 0.053435359182960426}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.25431839807904555
Fold 2 IBS: 0.24584941441284566
Fold 3 IBS: 0.20889578185906552
Fold 4 IBS: 0.239073073530296
Fold 5 IBS: 0.21275686117869264
[I 2024-04-29 14:41:30,032] Trial 41 finished with value: 0.23217870581198907 and parameters: {'subsample': 0.7315314599934812, 'dropout_rate': 0.33224239773242314, 'n_estimators': 101, 'learning_rate': 0.03777413553882145}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.2443668662999125
Fold 2 IBS: 0.22867870278338076
Fold 3 IBS: 0.2211232640334732
Fold 4 IBS: 0.23767674164163644
Fold 5 IBS: 0.22271749968567037
[I 2024-04-29 14:41:30,144] Trial 42 finished with value: 0.23091261488881468 and parameters: {'subsample': 0.82650038857956, 'dropout_rate': 0.18555759267297461, 'n_estimators': 35, 'learning_rate': 0.02608194255715347}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.2626440400830599
Fold 2 IBS: 0.2630532526108297
Fold 3 IBS: 0.20441668348273825
Fold 4 IBS: 0.2433831864421931
Fold 5 IBS: 0.20941768510904926
[I 2024-04-29 14:41:30,647] Trial 43 finished with value: 0.23658296954557403 and parameters: {'subsample': 0.8952564086208508, 'dropout_rate': 0.1126846582513547, 'n_estimators': 157, 'learning_rate': 0.03163676738840634}. Best is trial 35 with value: 0.22806076229202218.
Fold 1 IBS: 0.24628209505769977
Fold 2 IBS: 0.23440209397754888
Fold 3 IBS: 0.21067803793281697
Fold 4 IBS: 0.2355725157877382
Fold 5 IBS: 0.2132418823497649
[I 2024-04-29 14:41:30,795] Trial 44 finished with value: 0.22803532502111373 and parameters: {'subsample': 0.5795803547524322, 'dropout_rate': 0.5020020877800176, 'n_estimators': 58, 'learning_rate': 0.04508416432006209}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24646841424639185
Fold 2 IBS: 0.23494203153877122
Fold 3 IBS: 0.21680295045475645
Fold 4 IBS: 0.2374364966485224
Fold 5 IBS: 0.21234937060345063
[I 2024-04-29 14:41:30,952] Trial 45 finished with value: 0.22959985269837851 and parameters: {'subsample': 0.4516370662115133, 'dropout_rate': 0.5117124736526378, 'n_estimators': 60, 'learning_rate': 0.04549371134509104}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2610919362878939
Fold 2 IBS: 0.27327898146555113
Fold 3 IBS: 0.21291441021241067
Fold 4 IBS: 0.24530522158050516
Fold 5 IBS: 0.21542887019124304
[I 2024-04-29 14:41:31,181] Trial 46 finished with value: 0.2416038839475208 and parameters: {'subsample': 0.5661925665028334, 'dropout_rate': 0.5977238330260896, 'n_estimators': 92, 'learning_rate': 0.055230119616596}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24496260438533862
Fold 2 IBS: 0.22886463375138208
Fold 3 IBS: 0.22263342876186504
Fold 4 IBS: 0.23833436614084785
Fold 5 IBS: 0.22331753158076026
[I 2024-04-29 14:41:31,257] Trial 47 finished with value: 0.2316225129240388 and parameters: {'subsample': 0.5998601417579749, 'dropout_rate': 0.24102802507424348, 'n_estimators': 21, 'learning_rate': 0.036540031044914836}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.261848587799392
Fold 2 IBS: 0.2648214455301418
Fold 3 IBS: 0.20522241806043479
Fold 4 IBS: 0.2433546645055163
Fold 5 IBS: 0.21681398901882623
[I 2024-04-29 14:41:31,439] Trial 48 finished with value: 0.23841222098286222 and parameters: {'subsample': 0.6657704432105864, 'dropout_rate': 0.6604314111556595, 'n_estimators': 75, 'learning_rate': 0.06459360749932624}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.3071583266729974
Fold 2 IBS: 0.3685586406230107
Fold 3 IBS: 0.21626612698917821
Fold 4 IBS: 0.2766138855055833
Fold 5 IBS: 0.3012016555519753
[I 2024-04-29 14:41:32,029] Trial 49 finished with value: 0.293959727068549 and parameters: {'subsample': 0.7166925637726277, 'dropout_rate': 0.54808904609971, 'n_estimators': 196, 'learning_rate': 0.050582517363759134}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2444731467435483
Fold 2 IBS: 0.22879646813369328
Fold 3 IBS: 0.2210258388621463
Fold 4 IBS: 0.23592305173732264
Fold 5 IBS: 0.21775702820399423
[I 2024-04-29 14:41:32,136] Trial 50 finished with value: 0.22959510673614095 and parameters: {'subsample': 0.45392641686402563, 'dropout_rate': 0.7747773432024949, 'n_estimators': 38, 'learning_rate': 0.04279349075928138}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24478210628351707
Fold 2 IBS: 0.22991874549737382
Fold 3 IBS: 0.21487735714716685
Fold 4 IBS: 0.23588285466765815
Fold 5 IBS: 0.21746648657682394
[I 2024-04-29 14:41:32,554] Trial 51 finished with value: 0.22858551003450794 and parameters: {'subsample': 0.7656121855045271, 'dropout_rate': 0.375068943812752, 'n_estimators': 111, 'learning_rate': 0.016769783329425858}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24468538246820604
Fold 2 IBS: 0.2301295721629543
Fold 3 IBS: 0.21518340253303478
Fold 4 IBS: 0.2367247112712219
Fold 5 IBS: 0.21590312061571182
[I 2024-04-29 14:41:32,745] Trial 52 finished with value: 0.22852523781022577 and parameters: {'subsample': 0.5283099260705277, 'dropout_rate': 0.4459698952011236, 'n_estimators': 65, 'learning_rate': 0.029503976615238153}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24787916127154758
Fold 2 IBS: 0.23655810320457568
Fold 3 IBS: 0.21110453268750512
Fold 4 IBS: 0.23683011999309916
Fold 5 IBS: 0.21310847610766678
[I 2024-04-29 14:41:33,108] Trial 53 finished with value: 0.22909607865287884 and parameters: {'subsample': 0.621714533336511, 'dropout_rate': 0.5710584887618361, 'n_estimators': 126, 'learning_rate': 0.022931541302205247}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24567839096993888
Fold 2 IBS: 0.23192043305621807
Fold 3 IBS: 0.21234656017895226
Fold 4 IBS: 0.2356195507498038
Fold 5 IBS: 0.21611589261124906
[I 2024-04-29 14:41:33,245] Trial 54 finished with value: 0.2283361655132324 and parameters: {'subsample': 0.8665361291675531, 'dropout_rate': 0.516751702930278, 'n_estimators': 49, 'learning_rate': 0.04574441234267258}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24709397032165614
Fold 2 IBS: 0.2318764553746983
Fold 3 IBS: 0.22940450057193468
Fold 4 IBS: 0.24181001885715006
Fold 5 IBS: 0.2291865592533899
[I 2024-04-29 14:41:33,288] Trial 55 finished with value: 0.23587430087576583 and parameters: {'subsample': 0.6765664077905448, 'dropout_rate': 0.1702432687938276, 'n_estimators': 1, 'learning_rate': 0.03468041430213696}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2468443721703389
Fold 2 IBS: 0.23158247134692211
Fold 3 IBS: 0.22817904711832715
Fold 4 IBS: 0.24148474730599456
Fold 5 IBS: 0.22873951850065025
[I 2024-04-29 14:41:33,497] Trial 56 finished with value: 0.2353660312884466 and parameters: {'subsample': 0.811177007139624, 'dropout_rate': 0.632872623933352, 'n_estimators': 83, 'learning_rate': 0.0010113076162487182}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2749040444434231
Fold 2 IBS: 0.29429406285090515
Fold 3 IBS: 0.20432119960061182
Fold 4 IBS: 0.25032553338857244
Fold 5 IBS: 0.23674737796263365
[I 2024-04-29 14:41:33,930] Trial 57 finished with value: 0.25211844364922925 and parameters: {'subsample': 0.9253779282961316, 'dropout_rate': 0.3427793946355077, 'n_estimators': 146, 'learning_rate': 0.04111081928368819}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24436658975493045
Fold 2 IBS: 0.2287764416900902
Fold 3 IBS: 0.22153502379107096
Fold 4 IBS: 0.2379699903876509
Fold 5 IBS: 0.2232100120140441
[I 2024-04-29 14:41:34,010] Trial 58 finished with value: 0.23117161152755733 and parameters: {'subsample': 0.7540288161572106, 'dropout_rate': 0.47146280673615026, 'n_estimators': 16, 'learning_rate': 0.05327358123897698}. Best is trial 44 with value: 0.22803532502111373.

Fold 1 IBS: 0.2740664401762801
Fold 2 IBS: 0.29801343453883344
Fold 3 IBS: 0.2043575111283917
Fold 4 IBS: 0.2501181480642662
Fold 5 IBS: 0.23960609341954714
[I 2024-04-29 14:41:34,285] Trial 59 finished with value: 0.2532323254654637 and parameters: {'subsample': 0.8600220350417078, 'dropout_rate': 0.576594985075754, 'n_estimators': 104, 'learning_rate': 0.05792943581299736}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24480616451538592
Fold 2 IBS: 0.22872598499241903
Fold 3 IBS: 0.2219822920031368
Fold 4 IBS: 0.23824537864597717
Fold 5 IBS: 0.22249061216421565
[I 2024-04-29 14:41:34,412] Trial 60 finished with value: 0.23125008646422693 and parameters: {'subsample': 0.5182083766842418, 'dropout_rate': 0.4100731778926394, 'n_estimators': 43, 'learning_rate': 0.02007445129499992}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24539384312264087
Fold 2 IBS: 0.23153532791807438
Fold 3 IBS: 0.21353666453704093
Fold 4 IBS: 0.23579597885526882
Fold 5 IBS: 0.21608070606317314
[I 2024-04-29 14:41:34,554] Trial 61 finished with value: 0.22846850409923963 and parameters: {'subsample': 0.7829524883654503, 'dropout_rate': 0.5388959028671209, 'n_estimators': 50, 'learning_rate': 0.043359766095211465}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2533851762393821
Fold 2 IBS: 0.24506114619217786
Fold 3 IBS: 0.20658443243769956
Fold 4 IBS: 0.23808316450473532
Fold 5 IBS: 0.21558687933632653
[I 2024-04-29 14:41:34,749] Trial 62 finished with value: 0.23174015974206424 and parameters: {'subsample': 0.8656066856115973, 'dropout_rate': 0.5107274904127561, 'n_estimators': 75, 'learning_rate': 0.04870569191108665}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24405592866004802
Fold 2 IBS: 0.22846266285853914
Fold 3 IBS: 0.21899162201770456
Fold 4 IBS: 0.2368164868731481
Fold 5 IBS: 0.22097472262657702
[I 2024-04-29 14:41:34,844] Trial 63 finished with value: 0.22986028460720337 and parameters: {'subsample': 0.9789957818744204, 'dropout_rate': 0.2734750870094943, 'n_estimators': 26, 'learning_rate': 0.04571758103210779}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2451022402661718
Fold 2 IBS: 0.23080272461410362
Fold 3 IBS: 0.21330122526921597
Fold 4 IBS: 0.23563338973693668
Fold 5 IBS: 0.21694071741449433
[I 2024-04-29 14:41:35,006] Trial 64 finished with value: 0.2283560594601845 and parameters: {'subsample': 0.9302718983949787, 'dropout_rate': 0.6335692022283583, 'n_estimators': 54, 'learning_rate': 0.037760595601604025}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2642933182458483
Fold 2 IBS: 0.2658498498276432
Fold 3 IBS: 0.2116982440756998
Fold 4 IBS: 0.24506113764442827
Fold 5 IBS: 0.21718707923619715
[I 2024-04-29 14:41:35,342] Trial 65 finished with value: 0.24081792580596334 and parameters: {'subsample': 0.6588981766919912, 'dropout_rate': 0.4423885330532031, 'n_estimators': 123, 'learning_rate': 0.040116287481324946}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.26009221234465346
Fold 2 IBS: 0.26078531266026933
Fold 3 IBS: 0.20773749142110037
Fold 4 IBS: 0.2457065520074137
Fold 5 IBS: 0.21236037866452573
[I 2024-04-29 14:41:35,585] Trial 66 finished with value: 0.23733638941959256 and parameters: {'subsample': 0.5808486801439944, 'dropout_rate': 0.48256162650557577, 'n_estimators': 90, 'learning_rate': 0.052155520636334114}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24437074823927857
Fold 2 IBS: 0.22935760885041248
Fold 3 IBS: 0.2170175983624056
Fold 4 IBS: 0.23606651129250766
Fold 5 IBS: 0.2177845607094601
[I 2024-04-29 14:41:37,041] Trial 67 finished with value: 0.22891940549081288 and parameters: {'subsample': 0.702990561632221, 'dropout_rate': 0.10592939732110414, 'n_estimators': 302, 'learning_rate': 0.0056229342096923395}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2466935204804018
Fold 2 IBS: 0.2339662916203766
Fold 3 IBS: 0.21083279971205854
Fold 4 IBS: 0.23579250149515904
Fold 5 IBS: 0.21525221921249774
[I 2024-04-29 14:41:37,239] Trial 68 finished with value: 0.22850746650409876 and parameters: {'subsample': 0.8239336526093479, 'dropout_rate': 0.5274135506893471, 'n_estimators': 71, 'learning_rate': 0.03557646010123462}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.28507333848732747
Fold 2 IBS: 0.3252413337531
Fold 3 IBS: 0.20566983412389228
Fold 4 IBS: 0.25670993322500185
Fold 5 IBS: 0.25900020491353004
[I 2024-04-29 14:41:38,037] Trial 69 finished with value: 0.2663389289005703 and parameters: {'subsample': 0.8808396396294945, 'dropout_rate': 0.6742877948812134, 'n_estimators': 238, 'learning_rate': 0.029325454860253307}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2920069133722312
Fold 2 IBS: 0.3626243333711413
Fold 3 IBS: 0.22221199428330596
Fold 4 IBS: 0.2730312567075167
Fold 5 IBS: 0.23741998401274642
[I 2024-04-29 14:41:40,355] Trial 70 finished with value: 0.27745889634938836 and parameters: {'subsample': 0.4873818326074257, 'dropout_rate': 0.15119955197352622, 'n_estimators': 408, 'learning_rate': 0.023541674092857016}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24493356955392379
Fold 2 IBS: 0.23050872370673717
Fold 3 IBS: 0.21371417423433742
Fold 4 IBS: 0.2356522131783576
Fold 5 IBS: 0.2171375628231989
[I 2024-04-29 14:41:40,491] Trial 71 finished with value: 0.22838924869931096 and parameters: {'subsample': 0.9335706836821853, 'dropout_rate': 0.6365161405004507, 'n_estimators': 51, 'learning_rate': 0.03876859911078692}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24693899311005157
Fold 2 IBS: 0.2340616584235904
Fold 3 IBS: 0.21052855254379477
Fold 4 IBS: 0.23584976078274889
Fold 5 IBS: 0.21572428813152353
[I 2024-04-29 14:41:40,645] Trial 72 finished with value: 0.22862065059834183 and parameters: {'subsample': 0.9848053710770828, 'dropout_rate': 0.5715851379156515, 'n_estimators': 58, 'learning_rate': 0.04374797044989356}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24447489901688546
Fold 2 IBS: 0.2296722494938454
Fold 3 IBS: 0.21498381975341666
Fold 4 IBS: 0.23587466620140568
Fold 5 IBS: 0.21797656968477105
[I 2024-04-29 14:41:40,749] Trial 73 finished with value: 0.22859644083006486 and parameters: {'subsample': 0.9104698751711979, 'dropout_rate': 0.739811425028012, 'n_estimators': 37, 'learning_rate': 0.04782757254981085}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24532547419152104
Fold 2 IBS: 0.22981823242225843
Fold 3 IBS: 0.22475169777446155
Fold 4 IBS: 0.23951680460704583
Fold 5 IBS: 0.22584710499446298
[I 2024-04-29 14:41:40,818] Trial 74 finished with value: 0.23305186279794995 and parameters: {'subsample': 0.8485937239868786, 'dropout_rate': 0.6128365123041772, 'n_estimators': 15, 'learning_rate': 0.030934773504669423}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.25214068889953933
Fold 2 IBS: 0.24314423409870542
Fold 3 IBS: 0.20692957087019428
Fold 4 IBS: 0.23762083078015286
Fold 5 IBS: 0.21537871145500534
[I 2024-04-29 14:41:41,055] Trial 75 finished with value: 0.23104280722071943 and parameters: {'subsample': 0.874075972617653, 'dropout_rate': 0.6830589963062559, 'n_estimators': 95, 'learning_rate': 0.036632353035241025}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2885500958375556
Fold 2 IBS: 0.33713783177081075
Fold 3 IBS: 0.2080113263772693
Fold 4 IBS: 0.26085919512987243
Fold 5 IBS: 0.26256191260602996
[I 2024-04-29 14:41:41,425] Trial 76 finished with value: 0.2714240723443076 and parameters: {'subsample': 0.7253619411932841, 'dropout_rate': 0.5662037880248826, 'n_estimators': 134, 'learning_rate': 0.056703880585207284}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.26531215810663883
Fold 2 IBS: 0.2739216076563925
Fold 3 IBS: 0.20565763481179405
Fold 4 IBS: 0.2446949993380001
Fold 5 IBS: 0.22306124037124647
[I 2024-04-29 14:41:41,712] Trial 77 finished with value: 0.24252952805681435 and parameters: {'subsample': 0.7836762120375689, 'dropout_rate': 0.649173726264939, 'n_estimators': 112, 'learning_rate': 0.04570223320690589}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.25247131611254575
Fold 2 IBS: 0.2509692790737629

Fold 3 IBS: 0.2109337973291775
Fold 4 IBS: 0.24223018529288326
Fold 5 IBS: 0.2066465684530942
[I 2024-04-29 14:41:41,942] Trial 78 finished with value: 0.23265022925229273 and parameters: {'subsample': 0.5484457169084019, 'dropout_rate': 0.22015964511958286, 'n_estimators': 83, 'learning_rate': 0.04941919385503316}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.28546627650696904
Fold 2 IBS: 0.3380677593689487
Fold 3 IBS: 0.21408985974371417
Fold 4 IBS: 0.26162509079926033
Fold 5 IBS: 0.2504196235788123
[I 2024-04-29 14:41:42,443] Trial 79 finished with value: 0.2699337219995409 and parameters: {'subsample': 0.5921521465840234, 'dropout_rate': 0.8749042812122334, 'n_estimators': 188, 'learning_rate': 0.04027300903668814}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24411324640618776
Fold 2 IBS: 0.22881097302349013
Fold 3 IBS: 0.21633320784409502
Fold 4 IBS: 0.23612144672296592
Fold 5 IBS: 0.21873565619800778
[I 2024-04-29 14:41:42,579] Trial 80 finished with value: 0.22882290603894934 and parameters: {'subsample': 0.8321289633684164, 'dropout_rate': 0.13334783894055188, 'n_estimators': 46, 'learning_rate': 0.03407537230836163}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24540792487214372
Fold 2 IBS: 0.2314200189900434
Fold 3 IBS: 0.2126167544982379
Fold 4 IBS: 0.235617389355653
Fold 5 IBS: 0.2165825487208054
[I 2024-04-29 14:41:42,721] Trial 81 finished with value: 0.2283289272873767 and parameters: {'subsample': 0.9266778798763943, 'dropout_rate': 0.6145124904031225, 'n_estimators': 54, 'learning_rate': 0.03991026622771782}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24732083334073524
Fold 2 IBS: 0.2346590960252153
Fold 3 IBS: 0.2101429652953674
Fold 4 IBS: 0.23593988436512947
Fold 5 IBS: 0.21558138329304583
[I 2024-04-29 14:41:42,881] Trial 82 finished with value: 0.22872883246389866 and parameters: {'subsample': 0.9636349207972594, 'dropout_rate': 0.6099626227240922, 'n_estimators': 62, 'learning_rate': 0.0423482369242382}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24408103344991997
Fold 2 IBS: 0.2284652372564656
Fold 3 IBS: 0.21965268714371197
Fold 4 IBS: 0.2368706951143239
Fold 5 IBS: 0.2215677871615078
[I 2024-04-29 14:41:42,980] Trial 83 finished with value: 0.23012748802518584 and parameters: {'subsample': 0.9023792261032295, 'dropout_rate': 0.48350845312530477, 'n_estimators': 29, 'learning_rate': 0.03851620016496923}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24523312723646656
Fold 2 IBS: 0.229723185613947
Fold 3 IBS: 0.22442843425225606
Fold 4 IBS: 0.23930507373382764
Fold 5 IBS: 0.22561689675231322
[I 2024-04-29 14:41:43,040] Trial 84 finished with value: 0.23286134351776208 and parameters: {'subsample': 0.9391372286735271, 'dropout_rate': 0.7005454311271853, 'n_estimators': 11, 'learning_rate': 0.045305296045874244}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24514941845894628
Fold 2 IBS: 0.23097426677943256
Fold 3 IBS: 0.21321839312515653
Fold 4 IBS: 0.23563650043298243
Fold 5 IBS: 0.21670537224711836
[I 2024-04-29 14:41:43,219] Trial 85 finished with value: 0.22833679020872721 and parameters: {'subsample': 0.9188818471752946, 'dropout_rate': 0.5869758072966066, 'n_estimators': 72, 'learning_rate': 0.028543718810406207}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.25886281543552475
Fold 2 IBS: 0.26338319019366113
Fold 3 IBS: 0.2053357366233571
Fold 4 IBS: 0.24336719841646393
Fold 5 IBS: 0.21558389164602595
[I 2024-04-29 14:41:43,409] Trial 86 finished with value: 0.23730656646300657 and parameters: {'subsample': 0.6386231758661289, 'dropout_rate': 0.522971912916216, 'n_estimators': 75, 'learning_rate': 0.06372583418560197}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2468019261172534
Fold 2 IBS: 0.2342724356566972
Fold 3 IBS: 0.21212945370032552
Fold 4 IBS: 0.23659694358347488
Fold 5 IBS: 0.21298659442972162
[I 2024-04-29 14:41:43,674] Trial 87 finished with value: 0.22855747069749452 and parameters: {'subsample': 0.7409902497244855, 'dropout_rate': 0.17971650523934474, 'n_estimators': 98, 'learning_rate': 0.027607893218644312}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2448599637452654
Fold 2 IBS: 0.22925873433048327
Fold 3 IBS: 0.22339962740453295
Fold 4 IBS: 0.23887003822749
Fold 5 IBS: 0.22470824073899348
[I 2024-04-29 14:41:43,784] Trial 88 finished with value: 0.23221932088935304 and parameters: {'subsample': 0.8101290439908051, 'dropout_rate': 0.5917406044901371, 'n_estimators': 39, 'learning_rate': 0.016023124054934286}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2990358132388687
Fold 2 IBS: 0.35550002289261556
Fold 3 IBS: 0.2096416948430116
Fold 4 IBS: 0.26691356382775616
Fold 5 IBS: 0.29193034786438615
[I 2024-04-29 14:41:44,266] Trial 89 finished with value: 0.28460428853332764 and parameters: {'subsample': 0.8934780494874477, 'dropout_rate': 0.50429459388671, 'n_estimators': 167, 'learning_rate': 0.051328475679993595}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2444634114478406
Fold 2 IBS: 0.22873896519824297
Fold 3 IBS: 0.2214969120611723
Fold 4 IBS: 0.23798659904444042
Fold 5 IBS: 0.22279656121126928
[I 2024-04-29 14:41:44,445] Trial 90 finished with value: 0.23109648979259312 and parameters: {'subsample': 0.6967117016542083, 'dropout_rate': 0.3097379426434701, 'n_estimators': 69, 'learning_rate': 0.012434019189597075}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24453756267895457
Fold 2 IBS: 0.22977129635442958
Fold 3 IBS: 0.21467262819163188
Fold 4 IBS: 0.23574771791591095
Fold 5 IBS: 0.21779378123830742
[I 2024-04-29 14:41:44,588] Trial 91 finished with value: 0.2285045972758469 and parameters: {'subsample': 0.9592909657623098, 'dropout_rate': 0.5559687770984751, 'n_estimators': 55, 'learning_rate': 0.03281448767126785}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2448622243481283
Fold 2 IBS: 0.22926245527695382
Fold 3 IBS: 0.22333078529517822
Fold 4 IBS: 0.23877318349086224
Fold 5 IBS: 0.22462691105284333
[I 2024-04-29 14:41:44,676] Trial 92 finished with value: 0.2321711118927932 and parameters: {'subsample': 0.9289126274604125, 'dropout_rate': 0.61884162547743, 'n_estimators': 25, 'learning_rate': 0.025353206012461764}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24429768830990348
Fold 2 IBS: 0.2292610757271472
Fold 3 IBS: 0.21559372721619988
Fold 4 IBS: 0.23590179734873248
Fold 5 IBS: 0.21849540768276
[I 2024-04-29 14:41:44,883] Trial 93 finished with value: 0.22870993925694857 and parameters: {'subsample': 0.99766016156918, 'dropout_rate': 0.7289005942140083, 'n_estimators': 86, 'learning_rate': 0.019127674637257917}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2548640585518277
Fold 2 IBS: 0.24785183907056615
Fold 3 IBS: 0.2060404843167762
Fold 4 IBS: 0.23866534196898706
Fold 5 IBS: 0.2161965792726532
[I 2024-04-29 14:41:45,070] Trial 94 finished with value: 0.23272366063616207 and parameters: {'subsample': 0.8491923109717385, 'dropout_rate': 0.5907106869962908, 'n_estimators': 48, 'learning_rate': 0.08077924912008731}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.247964240607889
Fold 2 IBS: 0.23558193799294086
Fold 3 IBS: 0.2095095112618413
Fold 4 IBS: 0.23611478264375485
Fold 5 IBS: 0.21551534963732294
[I 2024-04-29 14:41:45,250] Trial 95 finished with value: 0.2289371644287498 and parameters: {'subsample': 0.923503338243996, 'dropout_rate': 0.463751241810311, 'n_estimators': 67, 'learning_rate': 0.041087576650381284}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.25774907324467555
Fold 2 IBS: 0.25376517599272247
Fold 3 IBS: 0.20521030031845763
Fold 4 IBS: 0.2404312511654509
Fold 5 IBS: 0.2181295574157114
[I 2024-04-29 14:41:45,531] Trial 96 finished with value: 0.23505707162740358 and parameters: {'subsample': 0.8864859061357513, 'dropout_rate': 0.6526794957298698, 'n_estimators': 112, 'learning_rate': 0.03744789889024919}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.3021531065142074
Fold 2 IBS: 0.3694524880571037
Fold 3 IBS: 0.22691139951124034
Fold 4 IBS: 0.27705217082938327

Fold 5 IBS: 0.2847637022430958
[I 2024-04-29 14:41:46,208] Trial 97 finished with value: 0.29206657343100606 and parameters: {'subsample': 0.5606440507914384, 'dropout_rate': 0.5315723430073316, 'n_estimators': 214, 'learning_rate': 0.04657699840791667}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.24422005227775972
Fold 2 IBS: 0.22944440424173224
Fold 3 IBS: 0.21764182536227877
Fold 4 IBS: 0.23713790468486956
Fold 5 IBS: 0.21744623337572327
[I 2024-04-29 14:41:46,302] Trial 98 finished with value: 0.22917808398847272 and parameters: {'subsample': 0.46010644553945257, 'dropout_rate': 0.40281973549646954, 'n_estimators': 31, 'learning_rate': 0.055235910359091894}. Best is trial 44 with value: 0.22803532502111373.
Fold 1 IBS: 0.2909450482261993
Fold 2 IBS: 0.3516283845294826
Fold 3 IBS: 0.21788174414850225
Fold 4 IBS: 0.2658523928608872
Fold 5 IBS: 0.2652199027303657
[I 2024-04-29 14:41:47,295] Trial 99 finished with value: 0.27830549449908737 and parameters: {'subsample': 0.6151719208120995, 'dropout_rate': 0.631184962372188, 'n_estimators': 278, 'learning_rate': 0.0298041816907381}. Best is trial 44 with value: 0.22803532502111373.


* Best trial for IBS:
 FrozenTrial(number=44, state=TrialState.COMPLETE, values=[0.22803532502111373], datetime_start=datetime.datetime(2024, 4, 29, 14, 41, 30, 648581), datetime_complete=datetime.datetime(2024, 4, 29, 14, 41, 30, 795562), params={'subsample': 0.5795803547524322, 'dropout_rate': 0.5020020877800176, 'n_estimators': 58, 'learning_rate': 0.04508416432006209}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=44, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.5795803547524322, 'dropout_rate': 0.5020020877800176, 'n_estimators': 58, 'learning_rate': 0.04508416432006209}


* Best Score for IBS:
 0.22803532502111373

In [53]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.639
train_ibs:  0.228

In [54]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [55]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(dropout_rate=0.1372634977863254,
                                 learning_rate=0.07265284090996345,
                                 n_estimators=274, random_state=123,
                                 subsample=0.6113433675015852)

C-index score: 0.626

GradientBoostingSurvivalAnalysis(dropout_rate=0.5020020877800176,
                                 learning_rate=0.04508416432006209,
                                 n_estimators=58, random_state=123,
                                 subsample=0.5795803547524322)

IBS: 0.227

## Results

In [ ]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

In [ ]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

In [ ]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

In [ ]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

In [ ]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/dfs/minmax/no_selection/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_dfs_minmax_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [ ]:
from datetime import date
today = date.today()
print("Date: ", today)