In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
 
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
from sklearn.preprocessing import MinMaxScaler
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

In [6]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

## Test dataset: MAASTRO

In [7]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [8]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [9]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [10]:
# Merge MAASTRO_D1 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG,DFS,DFS_event
0,1,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342,8.83,1.0
3,4,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979,19.73,1.0
4,6,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782,13.27,1.0
95,111,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212,72.07,0.0

In [11]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [12]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, DFS, DFS_event]
Index: []

In [13]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

In [14]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [15]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 14)
y_train:  (139,)

In [16]:
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [17]:
# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 16)

# Feature Selection: RENT

In [18]:
# Choose features from the result of RENT 
selected_features = ["hpv_related",
"pack_years",
"uicc8_III-IV",
"oropharynx",
"cavum_oris",
"TLG"]

In [19]:
X_rent = X.loc[:, selected_features]
X_new = X_rent.copy()

In [20]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, selected_features]

# Standardization

In [21]:
# Copy the original X for later 
original_X = X.copy()

In [22]:
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Standardize X_new, the new data with the selected features only 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = MinMaxScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [23]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [24]:
X_new

     hpv_related  pack_years  uicc8_III-IV  oropharynx  cavum_oris         TLG
0            0.0    0.000000           0.0           1           0   86.228420
1            0.0   27.404795           0.0           0           0    7.040100
2            0.0   41.019178           1.0           0           1   83.569669
3            0.0   37.500000           0.0           0           0    5.567091
4            0.0   53.000000           0.0           0           0   16.150550
..           ...         ...           ...         ...         ...         ...
134          1.0    0.000000           0.0           1           0   26.280140
135          1.0    0.000000           1.0           1           0  101.754834
136          1.0   39.498630           0.0           1           0   66.273201
137          1.0   71.527397           1.0           1           0   71.832443
138          1.0    2.250000           1.0           1           0   78.647696

[139 rows x 6 columns]

In [25]:
X_new_std

     hpv_related  pack_years  uicc8_III-IV  oropharynx  cavum_oris       TLG
0            0.0    0.000000           0.0           1           0  0.044798
1            0.0    0.213981           0.0           0           0  0.001900
2            0.0    0.320284           1.0           0           1  0.043358
3            0.0    0.292806           0.0           0           0  0.001102
4            0.0    0.413832           0.0           0           0  0.006835
..           ...         ...           ...         ...         ...       ...
134          1.0    0.000000           0.0           1           0  0.012323
135          1.0    0.000000           1.0           1           0  0.053209
136          1.0    0.308411           0.0           1           0  0.033988
137          1.0    0.558497           1.0           1           0  0.037000
138          1.0    0.017568           1.0           1           0  0.040692

[139 rows x 6 columns]

In [26]:
MAASTRO_new

    hpv_related  pack_years  uicc8_III-IV  oropharynx  cavum_oris         TLG
0             1           0             0           1           0  263.611623
1             0          20             1           1           0   36.980700
2             0           6             1           1           0   74.636342
3             0          45             1           0           0   46.791979
4             1          59             0           1           0  107.637514
..          ...         ...           ...         ...         ...         ...
94            0          55             1           0           0  144.490782
95            0         174             1           0           0   69.214868
96            1           0             1           1           0  102.594274
97            1           0             0           1           0  103.229492
98            0          40             1           0           0   28.553212

[99 rows x 6 columns]

In [27]:
MAASTRO_new_std

    hpv_related  pack_years  uicc8_III-IV  oropharynx  cavum_oris       TLG
0             1    0.000000             0           1           0  0.140892
1             0    0.156163             1           1           0  0.018119
2             0    0.046849             1           1           0  0.038519
3             0    0.351367             1           0           0  0.023434
4             1    0.460681             0           1           0  0.056396
..          ...         ...           ...         ...         ...       ...
94            0    0.429449             1           0           0  0.076361
95            0    1.358619             1           0           0  0.035582
96            1    0.000000             1           1           0  0.053664
97            1    0.000000             0           1           0  0.054008
98            0    0.312326             1           0           0  0.013554

[99 rows x 6 columns]

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [28]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-21 15:25:08,208] A new study created in memory with name: no-name-e4162761-c4a2-467c-84ee-9005227794ac

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-21 15:25:16,484] A new study created in memory with name: no-name-fccd146a-9501-4a8a-9e5b-fc2fcd73ddd4

Fold 1 C-index: 0.6133682830930537
Fold 2 C-index: 0.6227642276422765
Fold 3 C-index: 0.6131284916201117
[I 2024-04-21 15:25:16,472] Trial 0 finished with value: 0.6164203341184806 and parameters: {}. Best is trial 0 with value: 0.6164203341184806.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6164203341184806], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 8, 387200), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 16, 471962), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6164203341184806

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2355656884101745
Fold 2 IBS: 0.2671397537816044
Fold 3 IBS: 0.2762799722045483
[I 2024-04-21 15:25:16,800] Trial 0 finished with value: 0.25966180479877576 and parameters: {}. Best is trial 0 with value: 0.25966180479877576.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.25966180479877576], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 16, 530454), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 16, 799999), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.25966180479877576

In [29]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [30]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.616
train_ibs:  0.26

#### Test

In [31]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [32]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.532
IBS score: 0.263

In [33]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [34]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis

#### Train

In [35]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-21 15:25:17,155] A new study created in memory with name: no-name-b834cd84-31de-47fb-ac11-aae709eeba48

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:17,425] Trial 0 finished with value: 0.6059844970067908 and parameters: {}. Best is trial 0 with value: 0.6059844970067908.

[I 2024-04-21 15:25:17,574] A new study created in memory with name: no-name-eb9525ac-33db-4980-97cf-bcf730cc0660

* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6059844970067908], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 17, 281391), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 17, 425465), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6059844970067908

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.248202164689621
Fold 2 IBS: 0.23351868202031184
Fold 3 IBS: 0.23466234456715074
[I 2024-04-21 15:25:17,747] Trial 0 finished with value: 0.2387943970923612 and parameters: {}. Best is trial 0 with value: 0.2387943970923612.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2387943970923612], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 17, 612512), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 17, 747830), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2387943970923612

In [36]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [37]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.606
train_ibs:  0.239

#### Test

In [38]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [39]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.657

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.224

In [40]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [41]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-21 15:25:18,081] A new study created in memory with name: no-name-0313f019-aca4-430c-a6ad-7642b1d7a80e

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-21 15:25:18,506] A new study created in memory with name: no-name-88d32562-87b8-443d-9cf3-d9ce493653c6

Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:18,485] Trial 0 finished with value: 0.6170483715937126 and parameters: {}. Best is trial 0 with value: 0.6170483715937126.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6170483715937126], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 18, 201099), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 18, 485734), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6170483715937126

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2346940354758586
Fold 2 IBS: 0.26624900431153087
Fold 3 IBS: 0.27552592538937937
[I 2024-04-21 15:25:18,813] Trial 0 finished with value: 0.2588229883922563 and parameters: {}. Best is trial 0 with value: 0.2588229883922563.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2588229883922563], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 18, 545394), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 18, 813811), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2588229883922563

In [42]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [43]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.617
train_ibs:  0.259

#### Test

In [44]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [45]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.534

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.26

In [46]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [47]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-21 15:25:19,511] A new study created in memory with name: no-name-5da1e29c-e722-464d-91b7-54467928f2d8

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6145251396648045
[I 2024-04-21 15:25:19,821] Trial 0 finished with value: 0.6150332620571423 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6150332620571423.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:20,268] Trial 1 finished with value: 0.6154988114053732 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.6154988114053732.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6195121951219512
Fold 3 C-index: 0.6145251396648045
[I 2024-04-21 15:25:20,604] Trial 2 finished with value: 0.6144912566370881 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.6154988114053732.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6145251396648045
[I 2024-04-21 15:25:20,922] Trial 3 finished with value: 0.6150332620571423 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.6154988114053732.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6145251396648045
[I 2024-04-21 15:25:21,312] Trial 4 finished with value: 0.6150332620571423 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.6154988114053732.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6145251396648045
[I 2024-04-21 15:25:21,672] Trial 5 finished with value: 0.6150332620571423 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.6154988114053732.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:21,985] Trial 6 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:22,344] Trial 7 finished with value: 0.6154988114053732 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:22,655] Trial 8 finished with value: 0.6154988114053732 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:23,080] Trial 9 finished with value: 0.6154988114053732 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:23,390] Trial 10 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:23,724] Trial 11 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:24,029] Trial 12 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.9946087870438435}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:24,324] Trial 13 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.8521165717679541}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:24,430] Trial 14 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:24,546] Trial 15 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.8659212232095017}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:24,781] Trial 16 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.8592866247617579}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6227642276422765
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:25,128] Trial 17 finished with value: 0.6160408168254273 and parameters: {'l1_ratio': 0.8140829029918109}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6145251396648045
[I 2024-04-21 15:25:25,350] Trial 18 finished with value: 0.6150332620571423 and parameters: {'l1_ratio': 0.5819463953201167}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:25,531] Trial 19 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9535087433508003}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:25,848] Trial 20 finished with value: 0.6154988114053732 and parameters: {'l1_ratio': 0.7540198302114602}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:26,090] Trial 21 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9453140545316446}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:26,197] Trial 22 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.9952149413953396}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:26,476] Trial 23 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.8898693182098678}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6145251396648045
[I 2024-04-21 15:25:26,809] Trial 24 finished with value: 0.6150332620571423 and parameters: {'l1_ratio': 0.7805647035680947}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:27,126] Trial 25 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9368557715647121}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:27,227] Trial 26 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.015423757551295547}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6145251396648045
[I 2024-04-21 15:25:27,514] Trial 27 finished with value: 0.6150332620571423 and parameters: {'l1_ratio': 0.6022588122254688}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6145251396648045
[I 2024-04-21 15:25:27,665] Trial 28 finished with value: 0.6150332620571423 and parameters: {'l1_ratio': 0.6499747968454208}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:27,882] Trial 29 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9010792166439672}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6227642276422765

Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:28,132] Trial 30 finished with value: 0.6160408168254273 and parameters: {'l1_ratio': 0.8107108448948633}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:28,357] Trial 31 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9790160904460925}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:28,637] Trial 32 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.9889509715055751}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:28,901] Trial 33 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9033942188713268}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:29,073] Trial 34 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.9969906676119189}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:29,177] Trial 35 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9145273991086058}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6195121951219512
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:29,442] Trial 36 finished with value: 0.6149568059853191 and parameters: {'l1_ratio': 0.23789482035414378}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:29,733] Trial 37 finished with value: 0.6154988114053732 and parameters: {'l1_ratio': 0.7342815000174964}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6227642276422765
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:30,089] Trial 38 finished with value: 0.6160408168254273 and parameters: {'l1_ratio': 0.8450450825036032}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6195121951219512
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:30,444] Trial 39 finished with value: 0.6149568059853191 and parameters: {'l1_ratio': 0.35153102114871604}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:30,749] Trial 40 finished with value: 0.6154988114053732 and parameters: {'l1_ratio': 0.6762726602177129}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:31,011] Trial 41 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.9960924020280132}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:31,300] Trial 42 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9419682443206}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6227642276422765
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:31,668] Trial 43 finished with value: 0.6160408168254273 and parameters: {'l1_ratio': 0.8119687552544277}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:32,030] Trial 44 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9393661793057178}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:32,265] Trial 45 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.8746070404800059}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:32,546] Trial 46 finished with value: 0.6154988114053732 and parameters: {'l1_ratio': 0.5222973322437542}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:32,864] Trial 47 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.9991045282580079}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6227642276422765
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:33,330] Trial 48 finished with value: 0.6160408168254273 and parameters: {'l1_ratio': 0.8342998569224302}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:33,637] Trial 49 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9586049921503356}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:33,929] Trial 50 finished with value: 0.6154988114053732 and parameters: {'l1_ratio': 0.7809764372372684}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:34,217] Trial 51 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9178859871913544}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:34,507] Trial 52 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9692519722503415}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:34,914] Trial 53 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.8799376033579454}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:35,205] Trial 54 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.964683441203964}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:35,381] Trial 55 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9169143930593655}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:35,629] Trial 56 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.9952154563525832}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:35,960] Trial 57 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.8660532692979819}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:36,295] Trial 58 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9491266276974554}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6145251396648045
[I 2024-04-21 15:25:36,746] Trial 59 finished with value: 0.6150332620571423 and parameters: {'l1_ratio': 0.774295562739}. Best is trial 6 with value: 0.6170483715937126.

Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:37,144] Trial 60 finished with value: 0.6154988114053732 and parameters: {'l1_ratio': 0.44336532883350177}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:37,474] Trial 61 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.9987484929578901}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:37,859] Trial 62 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9218987193310377}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:38,185] Trial 63 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9694662142422218}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:38,522] Trial 64 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.8909918905821402}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:38,935] Trial 65 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9607766127341739}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6227642276422765
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:39,286] Trial 66 finished with value: 0.6160408168254273 and parameters: {'l1_ratio': 0.8498302770173363}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.5858453473132372
Fold 2 C-index: 0.5959349593495935
Fold 3 C-index: 0.6361731843575419
[I 2024-04-21 15:25:39,438] Trial 67 finished with value: 0.6059844970067908 and parameters: {'l1_ratio': 0.10022359348974141}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:39,615] Trial 68 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9243124300404254}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:39,959] Trial 69 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.9982048868245822}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:40,249] Trial 70 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.898135499064906}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:40,612] Trial 71 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9742981579943621}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:40,943] Trial 72 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.997829731344606}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:41,231] Trial 73 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9360980716938021}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:41,580] Trial 74 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9653162527053213}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6227642276422765
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:41,958] Trial 75 finished with value: 0.6160408168254273 and parameters: {'l1_ratio': 0.8304219935585806}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:42,268] Trial 76 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.8925974024167355}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:42,549] Trial 77 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9375278120070856}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:42,890] Trial 78 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9792586524774783}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:43,176] Trial 79 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.8755402820615074}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6211382113821138
Fold 3 C-index: 0.6145251396648045
[I 2024-04-21 15:25:43,692] Trial 80 finished with value: 0.6150332620571423 and parameters: {'l1_ratio': 0.6145619662639121}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:43,955] Trial 81 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.993288871834262}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:44,232] Trial 82 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9471747900593323}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.6195121951219512
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:44,647] Trial 83 finished with value: 0.6149568059853191 and parameters: {'l1_ratio': 0.3246399629887613}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:44,942] Trial 84 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.9983010139212501}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:45,241] Trial 85 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.9118503720236073}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:45,393] Trial 86 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9775614329151197}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:45,873] Trial 87 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9520399890196546}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:46,206] Trial 88 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9235274594446929}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:46,516] Trial 89 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9685024745287089}. Best is trial 6 with value: 0.6170483715937126.

Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:46,795] Trial 90 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9422178795675016}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:47,080] Trial 91 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.9970000626274429}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:47,209] Trial 92 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.975498238789646}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:47,427] Trial 93 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9016605560866012}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:47,743] Trial 94 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.9857781741672843}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:48,071] Trial 95 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9554374334386161}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:48,359] Trial 96 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9237538021205675}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:48,686] Trial 97 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.8627303870405888}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439
Fold 3 C-index: 0.61731843575419
[I 2024-04-21 15:25:49,052] Trial 98 finished with value: 0.6170483715937126 and parameters: {'l1_ratio': 0.9984834791124654}. Best is trial 6 with value: 0.6170483715937126.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.624390243902439

[I 2024-04-21 15:25:49,335] A new study created in memory with name: no-name-70ba162d-b5aa-405f-a12b-50f803b1afd0

Fold 3 C-index: 0.6159217877094972
[I 2024-04-21 15:25:49,325] Trial 99 finished with value: 0.6165828222454817 and parameters: {'l1_ratio': 0.9394431138304249}. Best is trial 6 with value: 0.6170483715937126.


* Best trial for C-index:
 FrozenTrial(number=6, state=TrialState.COMPLETE, values=[0.6170483715937126], datetime_start=datetime.datetime(2024, 4, 21, 15, 25, 21, 684431), datetime_complete=datetime.datetime(2024, 4, 21, 15, 25, 21, 985770), params={'l1_ratio': 0.980766121964777}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=6, value=None)


* Best Score for C-index:
 0.6170483715937126

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23473409848474064
Fold 2 IBS: 0.2663519308805431
Fold 3 IBS: 0.27544027165720775
[I 2024-04-21 15:25:49,822] Trial 0 finished with value: 0.2588421003408305 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.2588421003408305.
Fold 1 IBS: 0.2347851072225522
Fold 2 IBS: 0.26649444200923805
Fold 3 IBS: 0.27536225844316686
[I 2024-04-21 15:25:50,026] Trial 1 finished with value: 0.2588806025583191 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.2588421003408305.
Fold 1 IBS: 0.23477613617094562
Fold 2 IBS: 0.2665369346579824
Fold 3 IBS: 0.27529647061703955
[I 2024-04-21 15:25:50,298] Trial 2 finished with value: 0.25886984714865585 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.2588421003408305.
Fold 1 IBS: 0.23475056402886055
Fold 2 IBS: 0.2663605641564437
Fold 3 IBS: 0.2754062161248344
[I 2024-04-21 15:25:50,587] Trial 3 finished with value: 0.25883911477004623 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 3 with value: 0.25883911477004623.
Fold 1 IBS: 0.23467527091511511
Fold 2 IBS: 0.2662982505874473
Fold 3 IBS: 0.2754761834438986
[I 2024-04-21 15:25:50,912] Trial 4 finished with value: 0.25881656831548705 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 4 with value: 0.25881656831548705.
Fold 1 IBS: 0.23474554544346837
Fold 2 IBS: 0.2664091128296705
Fold 3 IBS: 0.2753589390190489
[I 2024-04-21 15:25:51,344] Trial 5 finished with value: 0.2588378657640626 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 4 with value: 0.25881656831548705.
Fold 1 IBS: 0.23468461896317638
Fold 2 IBS: 0.26623862583341046
Fold 3 IBS: 0.2755012571484589
[I 2024-04-21 15:25:51,668] Trial 6 finished with value: 0.25880816731501527 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.25880816731501527.
Fold 1 IBS: 0.23472526620758974
Fold 2 IBS: 0.2663428267100243
Fold 3 IBS: 0.27542115543542023
[I 2024-04-21 15:25:52,007] Trial 7 finished with value: 0.2588297494510114 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.25880816731501527.
Fold 1 IBS: 0.23474717038203619
Fold 2 IBS: 0.26641608979044373
Fold 3 IBS: 0.27541419437678605
[I 2024-04-21 15:25:52,360] Trial 8 finished with value: 0.25885915151642197 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.25880816731501527.
Fold 1 IBS: 0.23476990532639808
Fold 2 IBS: 0.2664294338557476
Fold 3 IBS: 0.27535946450587845
[I 2024-04-21 15:25:52,778] Trial 9 finished with value: 0.2588529345626747 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.25880816731501527.
Fold 1 IBS: 0.23468640184239498
Fold 2 IBS: 0.2662405919664645
Fold 3 IBS: 0.27550592760358994
[I 2024-04-21 15:25:53,093] Trial 10 finished with value: 0.2588109738041498 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.25880816731501527.
Fold 1 IBS: 0.23469269863651593
Fold 2 IBS: 0.26624753173829313
Fold 3 IBS: 0.2755224230790607
[I 2024-04-21 15:25:53,406] Trial 11 finished with value: 0.25882088448462326 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 6 with value: 0.25880816731501527.
Fold 1 IBS: 0.2346914292873277
Fold 2 IBS: 0.2662461332451029
Fold 3 IBS: 0.2755190976335112
[I 2024-04-21 15:25:53,788] Trial 12 finished with value: 0.25881888672198056 and parameters: {'l1_ratio': 0.9946087870438435}. Best is trial 6 with value: 0.25880816731501527.
Fold 1 IBS: 0.23469082022812363
Fold 2 IBS: 0.26624073925895325
Fold 3 IBS: 0.27546158227699385
[I 2024-04-21 15:25:54,110] Trial 13 finished with value: 0.2587977139213569 and parameters: {'l1_ratio': 0.8521165717679541}. Best is trial 13 with value: 0.2587977139213569.
Fold 1 IBS: 0.23472595993374964
Fold 2 IBS: 0.26627508743849304
Fold 3 IBS: 0.27543994995615584
[I 2024-04-21 15:25:54,412] Trial 14 finished with value: 0.25881366577613285 and parameters: {'l1_ratio': 0.788973690956328}. Best is trial 13 with value: 0.2587977139213569.
Fold 1 IBS: 0.24794927309564146
Fold 2 IBS: 0.23350376180433238
Fold 3 IBS: 0.23448850197985444
[I 2024-04-21 15:25:54,616] Trial 15 finished with value: 0.23864717895994278 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 15 with value: 0.23864717895994278.
Fold 1 IBS: 0.24804942548172718
Fold 2 IBS: 0.23350936067764158
Fold 3 IBS: 0.23455739379518475
[I 2024-04-21 15:25:54,826] Trial 16 finished with value: 0.2387053933181845 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 15 with value: 0.23864717895994278.
Fold 1 IBS: 0.23483217146692734
Fold 2 IBS: 0.23358836811298572
Fold 3 IBS: 0.23224800470326978
[I 2024-04-21 15:25:55,068] Trial 17 finished with value: 0.2335561814277276 and parameters: {'l1_ratio': 0.10932144510738274}. Best is trial 17 with value: 0.2335561814277276.
Fold 1 IBS: 0.24775585550251275
Fold 2 IBS: 0.23349430286781642
Fold 3 IBS: 0.23435463178906024
[I 2024-04-21 15:25:55,179] Trial 18 finished with value: 0.23853493005312978 and parameters: {'l1_ratio': 0.011714640510308684}. Best is trial 17 with value: 0.2335561814277276.
Fold 1 IBS: 0.23484517445597713
Fold 2 IBS: 0.23368000930016264
Fold 3 IBS: 0.2317857538396266
[I 2024-04-21 15:25:55,408] Trial 19 finished with value: 0.23343697919858877 and parameters: {'l1_ratio': 0.13646083820247495}. Best is trial 19 with value: 0.23343697919858877.
Fold 1 IBS: 0.23479967166241372
Fold 2 IBS: 0.23375406255975917
Fold 3 IBS: 0.27534273928388425
[I 2024-04-21 15:25:55,785] Trial 20 finished with value: 0.24796549116868571 and parameters: {'l1_ratio': 0.15523641724239506}. Best is trial 19 with value: 0.23343697919858877.
Fold 1 IBS: 0.23481900475608203
Fold 2 IBS: 0.23361621561693346
Fold 3 IBS: 0.2320909624908396
[I 2024-04-21 15:25:55,993] Trial 21 finished with value: 0.23350872762128505 and parameters: {'l1_ratio': 0.11823498162817822}. Best is trial 19 with value: 0.23343697919858877.
Fold 1 IBS: 0.23481254346009803
Fold 2 IBS: 0.2337054564943581
Fold 3 IBS: 0.23167907273588145
[I 2024-04-21 15:25:56,179] Trial 22 finished with value: 0.2333990242301125 and parameters: {'l1_ratio': 0.14313904173799127}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.2347644843136288
Fold 2 IBS: 0.26647838411852237
Fold 3 IBS: 0.27535789319238063
[I 2024-04-21 15:25:56,576] Trial 23 finished with value: 0.2588669205415106 and parameters: {'l1_ratio': 0.3089940117272187}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.23484530214411364
Fold 2 IBS: 0.23359558764535163
Fold 3 IBS: 0.23220546579822846
[I 2024-04-21 15:25:56,806] Trial 24 finished with value: 0.23354878519589792 and parameters: {'l1_ratio': 0.11170670396215233}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.2348025544331013
Fold 2 IBS: 0.2665023080072285
Fold 3 IBS: 0.27529765538917167
[I 2024-04-21 15:25:57,345] Trial 25 finished with value: 0.25886750594316715 and parameters: {'l1_ratio': 0.19181174078235141}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.2347917125307118
Fold 2 IBS: 0.26650035132935157
Fold 3 IBS: 0.2753731639954983
[I 2024-04-21 15:25:57,859] Trial 26 finished with value: 0.25888840928518725 and parameters: {'l1_ratio': 0.28944064364755884}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.24514482576284527
Fold 2 IBS: 0.23354850303159883
Fold 3 IBS: 0.23251414632828762
[I 2024-04-21 15:25:58,010] Trial 27 finished with value: 0.23706915837424392 and parameters: {'l1_ratio': 0.09486155085202524}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.23478053535071955
Fold 2 IBS: 0.266436742053418
Fold 3 IBS: 0.2753391750318968
[I 2024-04-21 15:25:58,464] Trial 28 finished with value: 0.25885215081201146 and parameters: {'l1_ratio': 0.355721226193779}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.23479145481003383
Fold 2 IBS: 0.2664958988036003
Fold 3 IBS: 0.27532169352764796
[I 2024-04-21 15:25:58,679] Trial 29 finished with value: 0.25886968238042735 and parameters: {'l1_ratio': 0.23271632728278846}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.24552325962647156
Fold 2 IBS: 0.23351709027069006
Fold 3 IBS: 0.2327838650416477
[I 2024-04-21 15:25:58,796] Trial 30 finished with value: 0.23727473831293644 and parameters: {'l1_ratio': 0.08095994824614713}. Best is trial 22 with value: 0.2333990242301125.

Fold 1 IBS: 0.2348104041085494
Fold 2 IBS: 0.23376543958174895
Fold 3 IBS: 0.27527567501120154
[I 2024-04-21 15:25:59,456] Trial 31 finished with value: 0.2479505062338333 and parameters: {'l1_ratio': 0.1579645274939656}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.24563910984618026
Fold 2 IBS: 0.23350922477194183
Fold 3 IBS: 0.2328663289034261
[I 2024-04-21 15:25:59,592] Trial 32 finished with value: 0.2373382211738494 and parameters: {'l1_ratio': 0.07684886259117436}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.23479516478212306
Fold 2 IBS: 0.2664992242022518
Fold 3 IBS: 0.2753277945392883
[I 2024-04-21 15:25:59,965] Trial 33 finished with value: 0.25887406117455436 and parameters: {'l1_ratio': 0.23415745415458256}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.23479939719335377
Fold 2 IBS: 0.2665513823773548
Fold 3 IBS: 0.2752742404283745
[I 2024-04-21 15:26:00,442] Trial 34 finished with value: 0.25887500666636104 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.23479593906681928
Fold 2 IBS: 0.26650193434276426
Fold 3 IBS: 0.27535351041577555
[I 2024-04-21 15:26:00,830] Trial 35 finished with value: 0.258883794608453 and parameters: {'l1_ratio': 0.26121589681254564}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.2346990720278052
Fold 2 IBS: 0.266382666674454
Fold 3 IBS: 0.27537329985542797
[I 2024-04-21 15:26:01,198] Trial 36 finished with value: 0.2588183461858957 and parameters: {'l1_ratio': 0.5738294011539888}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.23478866297710238
Fold 2 IBS: 0.2664418738910959
Fold 3 IBS: 0.2753180747179889
[I 2024-04-21 15:26:01,526] Trial 37 finished with value: 0.2588495371953958 and parameters: {'l1_ratio': 0.32195558993682993}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.23481198471168419
Fold 2 IBS: 0.2336537340940777
Fold 3 IBS: 0.23190401929009258
[I 2024-04-21 15:26:01,802] Trial 38 finished with value: 0.23345657936528483 and parameters: {'l1_ratio': 0.12924933848123416}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.2464061952303328
Fold 2 IBS: 0.233476738331668
Fold 3 IBS: 0.23341031436505963
[I 2024-04-21 15:26:02,176] Trial 39 finished with value: 0.2377644159756868 and parameters: {'l1_ratio': 0.05119125808793289}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.2347322469205458
Fold 2 IBS: 0.26639950026341086
Fold 3 IBS: 0.2753829287605991
[I 2024-04-21 15:26:02,530] Trial 40 finished with value: 0.25883822531485196 and parameters: {'l1_ratio': 0.46667819693088786}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.23484874923876825
Fold 2 IBS: 0.23363588577917496
Fold 3 IBS: 0.23198995691713836
[I 2024-04-21 15:26:02,787] Trial 41 finished with value: 0.23349153064502723 and parameters: {'l1_ratio': 0.12412937534135207}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.2348335870257797
Fold 2 IBS: 0.26652981882140186
Fold 3 IBS: 0.27534792903426136
[I 2024-04-21 15:26:03,246] Trial 42 finished with value: 0.25890377829381434 and parameters: {'l1_ratio': 0.20198264459545257}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.23484608500127974
Fold 2 IBS: 0.2336807926424927
Fold 3 IBS: 0.23178236193988255
[I 2024-04-21 15:26:03,703] Trial 43 finished with value: 0.23343641319455166 and parameters: {'l1_ratio': 0.13667059187980826}. Best is trial 22 with value: 0.2333990242301125.
Fold 1 IBS: 0.23482446197982748
Fold 2 IBS: 0.23371651645385033
Fold 3 IBS: 0.23163479226057265
[I 2024-04-21 15:26:04,010] Trial 44 finished with value: 0.23339192356475014 and parameters: {'l1_ratio': 0.14596143165584644}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23477614696002713
Fold 2 IBS: 0.2664841945511667
Fold 3 IBS: 0.27532088467960913
[I 2024-04-21 15:26:04,583] Trial 45 finished with value: 0.25886040873026767 and parameters: {'l1_ratio': 0.2527240915200468}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.24643633537286866
Fold 2 IBS: 0.23347612897146527
Fold 3 IBS: 0.23343159933937943
[I 2024-04-21 15:26:04,779] Trial 46 finished with value: 0.2377813545612378 and parameters: {'l1_ratio': 0.05023511566990503}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23477525373227695
Fold 2 IBS: 0.26643163344219195
Fold 3 IBS: 0.27532967044691575
[I 2024-04-21 15:26:05,254] Trial 47 finished with value: 0.2588455192071282 and parameters: {'l1_ratio': 0.35248057601054456}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23476690491679741
Fold 2 IBS: 0.26637746346179186
Fold 3 IBS: 0.2753625404931506
[I 2024-04-21 15:26:05,697] Trial 48 finished with value: 0.25883563629057993 and parameters: {'l1_ratio': 0.5683872043393509}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.2348238082184369
Fold 2 IBS: 0.2665213040932897
Fold 3 IBS: 0.2753323629617131
[I 2024-04-21 15:26:06,137] Trial 49 finished with value: 0.25889249175781326 and parameters: {'l1_ratio': 0.1987283636106525}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23473636427452876
Fold 2 IBS: 0.2664002191289912
Fold 3 IBS: 0.27534225803357737
[I 2024-04-21 15:26:06,368] Trial 50 finished with value: 0.25882628047903244 and parameters: {'l1_ratio': 0.41653985858071785}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23480690474901025
Fold 2 IBS: 0.23370041513901296
Fold 3 IBS: 0.23169965752835228
[I 2024-04-21 15:26:06,505] Trial 51 finished with value: 0.2334023258054585 and parameters: {'l1_ratio': 0.14183721427538332}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23484283004742346
Fold 2 IBS: 0.23373444688420764
Fold 3 IBS: 0.27531302945498776
[I 2024-04-21 15:26:06,859] Trial 52 finished with value: 0.2479634354622063 and parameters: {'l1_ratio': 0.15044618112071562}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.24593269545587565
Fold 2 IBS: 0.23349284313651228
Fold 3 IBS: 0.23307499253994252
[I 2024-04-21 15:26:07,012] Trial 53 finished with value: 0.23750017704411017 and parameters: {'l1_ratio': 0.0667174095350363}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.2348011000490973
Fold 2 IBS: 0.23369534885447318
Fold 3 IBS: 0.231720608547874
[I 2024-04-21 15:26:07,502] Trial 54 finished with value: 0.23340568581714816 and parameters: {'l1_ratio': 0.1405187919481887}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23478985145889408
Fold 2 IBS: 0.2665465410870717
Fold 3 IBS: 0.27529691038561227
[I 2024-04-21 15:26:08,109] Trial 55 finished with value: 0.25887776764385934 and parameters: {'l1_ratio': 0.2086746007040772}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.2469881209714872
Fold 2 IBS: 0.2334733505509666
Fold 3 IBS: 0.2338198014146704
[I 2024-04-21 15:26:08,256] Trial 56 finished with value: 0.23809375764570806 and parameters: {'l1_ratio': 0.03336339020705319}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23474773738142976
Fold 2 IBS: 0.2663616943480966
Fold 3 IBS: 0.27539168891589677
[I 2024-04-21 15:26:08,627] Trial 57 finished with value: 0.2588337068818077 and parameters: {'l1_ratio': 0.6246196826499275}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23476834073913752
Fold 2 IBS: 0.26647941341844134
Fold 3 IBS: 0.2753345707271058
[I 2024-04-21 15:26:09,028] Trial 58 finished with value: 0.2588607749615615 and parameters: {'l1_ratio': 0.2782928757778683}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.234827084332468
Fold 2 IBS: 0.2665213418016132
Fold 3 IBS: 0.27530289160619037
[I 2024-04-21 15:26:09,486] Trial 59 finished with value: 0.2588837725800905 and parameters: {'l1_ratio': 0.16237687761548197}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.24512433202377
Fold 2 IBS: 0.23355045975352584
Fold 3 IBS: 0.2324995293141986
[I 2024-04-21 15:26:09,722] Trial 60 finished with value: 0.23705810703049815 and parameters: {'l1_ratio': 0.09563582787054106}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23483491426129846
Fold 2 IBS: 0.2336715761347104
Fold 3 IBS: 0.2318227391892567
[I 2024-04-21 15:26:10,000] Trial 61 finished with value: 0.23344307652842186 and parameters: {'l1_ratio': 0.1341844068122397}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23484031731529492
Fold 2 IBS: 0.23367605774790026

Fold 3 IBS: 0.23180297598443284
[I 2024-04-21 15:26:10,208] Trial 62 finished with value: 0.23343978368254267 and parameters: {'l1_ratio': 0.1353983864614466}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23483079874607005
Fold 2 IBS: 0.26652602618535026
Fold 3 IBS: 0.2753254849410966
[I 2024-04-21 15:26:10,658] Trial 63 finished with value: 0.25889410329083895 and parameters: {'l1_ratio': 0.18115928546231233}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23477620358633983
Fold 2 IBS: 0.26653699057323416
Fold 3 IBS: 0.27529658173184485
[I 2024-04-21 15:26:11,118] Trial 64 finished with value: 0.2588699252971396 and parameters: {'l1_ratio': 0.22695367981271147}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.2480626735498199
Fold 2 IBS: 0.233510131896554
Fold 3 IBS: 0.23456650236966592
[I 2024-04-21 15:26:11,329] Trial 65 finished with value: 0.23871310260534662 and parameters: {'l1_ratio': 0.0035938285281735816}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.24518497786590263
Fold 2 IBS: 0.23354474657852609
Fold 3 IBS: 0.2325427822907461
[I 2024-04-21 15:26:11,525] Trial 66 finished with value: 0.2370908355783916 and parameters: {'l1_ratio': 0.09335110741849806}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23466403848084919
Fold 2 IBS: 0.26629477613832025
Fold 3 IBS: 0.27551523238653625
[I 2024-04-21 15:26:11,976] Trial 67 finished with value: 0.2588246823352352 and parameters: {'l1_ratio': 0.9415445204645163}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.2470070684664227
Fold 2 IBS: 0.2334735294705445
Fold 3 IBS: 0.23383307874981005
[I 2024-04-21 15:26:12,131] Trial 68 finished with value: 0.23810455889559243 and parameters: {'l1_ratio': 0.03280449994087342}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23481551448114804
Fold 2 IBS: 0.23370816142945794
Fold 3 IBS: 0.2316681332569597
[I 2024-04-21 15:26:12,404] Trial 69 finished with value: 0.23339726972252187 and parameters: {'l1_ratio': 0.14383350405011416}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.2347653956887006
Fold 2 IBS: 0.2664792013907181
Fold 3 IBS: 0.2753594051717435
[I 2024-04-21 15:26:12,841] Trial 70 finished with value: 0.2588680007503874 and parameters: {'l1_ratio': 0.3094657031792244}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23485241031354429
Fold 2 IBS: 0.2336863234803954
Fold 3 IBS: 0.23175861686627613
[I 2024-04-21 15:26:13,108] Trial 71 finished with value: 0.23343245022007195 and parameters: {'l1_ratio': 0.1381436558135113}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23481207440194132
Fold 2 IBS: 0.2665093012224204
Fold 3 IBS: 0.2752949804603786
[I 2024-04-21 15:26:13,522] Trial 72 finished with value: 0.25887211869491344 and parameters: {'l1_ratio': 0.175588223484464}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23482446444257327
Fold 2 IBS: 0.23358432323415948
Fold 3 IBS: 0.23227247182050878
[I 2024-04-21 15:26:13,746] Trial 73 finished with value: 0.23356041983241385 and parameters: {'l1_ratio': 0.10795908288820114}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.2347853438144495
Fold 2 IBS: 0.26649244550587775
Fold 3 IBS: 0.27533605558730817
[I 2024-04-21 15:26:14,297] Trial 74 finished with value: 0.25887128163587847 and parameters: {'l1_ratio': 0.25660818935660473}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23480326314934155
Fold 2 IBS: 0.26650463174270655
Fold 3 IBS: 0.27531892760828597
[I 2024-04-21 15:26:14,613] Trial 75 finished with value: 0.25887560750011135 and parameters: {'l1_ratio': 0.21334924033117392}. Best is trial 44 with value: 0.23339192356475014.
Fold 1 IBS: 0.23483459744640195
Fold 2 IBS: 0.23372633402906268
Fold 3 IBS: 0.23159644585141867
[I 2024-04-21 15:26:14,846] Trial 76 finished with value: 0.23338579244229443 and parameters: {'l1_ratio': 0.148430294230284}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.2460905431860563
Fold 2 IBS: 0.23348608801368279
Fold 3 IBS: 0.23318696046897952
[I 2024-04-21 15:26:14,986] Trial 77 finished with value: 0.23758786388957287 and parameters: {'l1_ratio': 0.06143342737712405}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.23480690867034612
Fold 2 IBS: 0.23376167947874238
Fold 3 IBS: 0.2753536574010024
[I 2024-04-21 15:26:15,381] Trial 78 finished with value: 0.2479740818500303 and parameters: {'l1_ratio': 0.15706674869335466}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.2470319622266241
Fold 2 IBS: 0.23347379145706826
Fold 3 IBS: 0.2338505172289508
[I 2024-04-21 15:26:15,590] Trial 79 finished with value: 0.23811875697088106 and parameters: {'l1_ratio': 0.0320721973924826}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.23479843743543932
Fold 2 IBS: 0.26655204894730267
Fold 3 IBS: 0.27529090827817837
[I 2024-04-21 15:26:15,964] Trial 80 finished with value: 0.25888046488697347 and parameters: {'l1_ratio': 0.19051870705239962}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.23485469726775882
Fold 2 IBS: 0.23368836220886696
Fold 3 IBS: 0.23174995242326565
[I 2024-04-21 15:26:16,221] Trial 81 finished with value: 0.2334310039666305 and parameters: {'l1_ratio': 0.13868321936912303}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.2453019648244486
Fold 2 IBS: 0.23353438045658678
Fold 3 IBS: 0.23262619517820748
[I 2024-04-21 15:26:16,366] Trial 82 finished with value: 0.23715418015308096 and parameters: {'l1_ratio': 0.08899908226049766}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.23481860585542136
Fold 2 IBS: 0.2336159675413509
Fold 3 IBS: 0.23209228374605523
[I 2024-04-21 15:26:16,633] Trial 83 finished with value: 0.2335089523809425 and parameters: {'l1_ratio': 0.11815873417629193}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.23480775168420118
Fold 2 IBS: 0.23376258142531567
Fold 3 IBS: 0.27527134165000894
[I 2024-04-21 15:26:16,968] Trial 84 finished with value: 0.24794722491984192 and parameters: {'l1_ratio': 0.1572824432204206}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.23482409486637457
Fold 2 IBS: 0.2665250484819261
Fold 3 IBS: 0.27529334453247856
[I 2024-04-21 15:26:17,325] Trial 85 finished with value: 0.2588808292935931 and parameters: {'l1_ratio': 0.24594453766515667}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.23478104469414793
Fold 2 IBS: 0.2665376267222967
Fold 3 IBS: 0.275346624847794
[I 2024-04-21 15:26:17,672] Trial 86 finished with value: 0.25888843208807955 and parameters: {'l1_ratio': 0.18522222449905654}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.24575442727622215
Fold 2 IBS: 0.233502189150189
Fold 3 IBS: 0.23294834791650568
[I 2024-04-21 15:26:17,787] Trial 87 finished with value: 0.23740165478097228 and parameters: {'l1_ratio': 0.07282109873107166}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.23481996172152034
Fold 2 IBS: 0.2665195748895867
Fold 3 IBS: 0.27534628712098363
[I 2024-04-21 15:26:18,212] Trial 88 finished with value: 0.25889527457736355 and parameters: {'l1_ratio': 0.21943516763985854}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.23479882861563786
Fold 2 IBS: 0.23369339965036792
Fold 3 IBS: 0.23172874173719832
[I 2024-04-21 15:26:18,456] Trial 89 finished with value: 0.23340699000106802 and parameters: {'l1_ratio': 0.14000874992379664}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.23474658712673388
Fold 2 IBS: 0.2662935871325075
Fold 3 IBS: 0.27546709909949857
[I 2024-04-21 15:26:18,901] Trial 90 finished with value: 0.2588357577862466 and parameters: {'l1_ratio': 0.7135825642664739}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.23481731074720227
Fold 2 IBS: 0.23370981339371713
Fold 3 IBS: 0.23166148772583728
[I 2024-04-21 15:26:19,176] Trial 91 finished with value: 0.23339620395558555 and parameters: {'l1_ratio': 0.14425627268819907}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.2348339401171321
Fold 2 IBS: 0.23358931737615787
Fold 3 IBS: 0.232242330398703
[I 2024-04-21 15:26:19,418] Trial 92 finished with value: 0.23355519596399765 and parameters: {'l1_ratio': 0.10963839085617028}. Best is trial 76 with value: 0.23338579244229443.

Fold 1 IBS: 0.2348257704648675
Fold 2 IBS: 0.23371776516511056
Fold 3 IBS: 0.23162986604946367
[I 2024-04-21 15:26:19,652] Trial 93 finished with value: 0.23339113389314725 and parameters: {'l1_ratio': 0.14627730195216693}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.2347731747732103
Fold 2 IBS: 0.2664837509593949
Fold 3 IBS: 0.27534257012209273
[I 2024-04-21 15:26:20,066] Trial 94 finished with value: 0.25886649861823263 and parameters: {'l1_ratio': 0.2805355157099492}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.23479173519216437
Fold 2 IBS: 0.26654502917897166
Fold 3 IBS: 0.2753460124405024
[I 2024-04-21 15:26:20,519] Trial 95 finished with value: 0.2588942589372128 and parameters: {'l1_ratio': 0.1698600904432433}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.23483114844334693
Fold 2 IBS: 0.2665278621878695
Fold 3 IBS: 0.27534435129009815
[I 2024-04-21 15:26:21,048] Trial 96 finished with value: 0.2589011206404382 and parameters: {'l1_ratio': 0.20122595144424574}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.24638887210763485
Fold 2 IBS: 0.2334771106149688
Fold 3 IBS: 0.23339807729613374
[I 2024-04-21 15:26:21,353] Trial 97 finished with value: 0.23775468667291247 and parameters: {'l1_ratio': 0.05174249044776433}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.23471133753313767
Fold 2 IBS: 0.26633307437155707
Fold 3 IBS: 0.27547757475203233
[I 2024-04-21 15:26:21,801] Trial 98 finished with value: 0.258840662218909 and parameters: {'l1_ratio': 0.7667338152719219}. Best is trial 76 with value: 0.23338579244229443.
Fold 1 IBS: 0.23482123176462388
Fold 2 IBS: 0.23371346343534358
Fold 3 IBS: 0.23164689807524572
[I 2024-04-21 15:26:22,034] Trial 99 finished with value: 0.23339386442507107 and parameters: {'l1_ratio': 0.14518680993099253}. Best is trial 76 with value: 0.23338579244229443.


* Best trial for IBS:
 FrozenTrial(number=76, state=TrialState.COMPLETE, values=[0.23338579244229443], datetime_start=datetime.datetime(2024, 4, 21, 15, 26, 14, 640688), datetime_complete=datetime.datetime(2024, 4, 21, 15, 26, 14, 846359), params={'l1_ratio': 0.148430294230284}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=76, value=None)


* Best Score for IBS:
 0.23338579244229443

In [48]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [49]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.617
train_ibs:  0.233

#### Test

In [50]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [51]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.980766121964777)

test_cindex : 0.534

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.148430294230284)

test_ibs:  0.26

In [52]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [53]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-21 15:26:22,733] A new study created in memory with name: no-name-d26ef0b5-4029-4ee2-983b-3aa2379c9762

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5950196592398427
Fold 2 C-index: 0.5609756097560976
Fold 3 C-index: 0.5551675977653632
[I 2024-04-21 15:26:25,797] Trial 0 finished with value: 0.5703876222537678 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.5703876222537678.
Fold 1 C-index: 0.6225425950196593
Fold 2 C-index: 0.5650406504065041
Fold 3 C-index: 0.5991620111731844
[I 2024-04-21 15:26:27,601] Trial 1 finished with value: 0.5955817521997826 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.5955817521997826.
Fold 1 C-index: 0.6186107470511141
Fold 2 C-index: 0.5747967479674797
Fold 3 C-index: 0.590782122905028
[I 2024-04-21 15:26:29,514] Trial 2 finished with value: 0.5947298726412072 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.5955817521997826.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:30,556] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.5955817521997826.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:32,006] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.5955817521997826.
Fold 1 C-index: 0.6238532110091743
Fold 2 C-index: 0.5536585365853659
Fold 3 C-index: 0.5991620111731844
[I 2024-04-21 15:26:34,848] Trial 5 finished with value: 0.5922245862559082 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 1 with value: 0.5955817521997826.
Fold 1 C-index: 0.6225425950196593
Fold 2 C-index: 0.551219512195122
Fold 3 C-index: 0.5544692737430168
[I 2024-04-21 15:26:37,413] Trial 6 finished with value: 0.5760771269859327 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 1 with value: 0.5955817521997826.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:39,031] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 1 with value: 0.5955817521997826.
Fold 1 C-index: 0.6192660550458715
Fold 2 C-index: 0.47560975609756095
Fold 3 C-index: 0.6089385474860335
[I 2024-04-21 15:26:43,128] Trial 8 finished with value: 0.5679381195431553 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 1 with value: 0.5955817521997826.
Fold 1 C-index: 0.6199213630406291
Fold 2 C-index: 0.5552845528455285
Fold 3 C-index: 0.5991620111731844
[I 2024-04-21 15:26:45,259] Trial 9 finished with value: 0.5914559756864474 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 1 with value: 0.5955817521997826.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:45,671] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 1 with value: 0.5955817521997826.
Fold 1 C-index: 0.6225425950196593
Fold 2 C-index: 0.5739837398373984
Fold 3 C-index: 0.5831005586592178
[I 2024-04-21 15:26:46,668] Trial 11 finished with value: 0.5932089645054252 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.9250608990121825, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1579906038170908, 'warm_start': False}. Best is trial 1 with value: 0.5955817521997826.
Fold 1 C-index: 0.6258191349934469
Fold 2 C-index: 0.5926829268292683
Fold 3 C-index: 0.6424581005586593
[I 2024-04-21 15:26:47,753] Trial 12 finished with value: 0.6203200541271249 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.8206827027986038, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13254323337687263, 'warm_start': False}. Best is trial 12 with value: 0.6203200541271249.
Fold 1 C-index: 0.6245085190039319
Fold 2 C-index: 0.583739837398374
Fold 3 C-index: 0.6431564245810056
[I 2024-04-21 15:26:48,875] Trial 13 finished with value: 0.6171349269944372 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 114, 'oob_score': False, 'max_samples': 0.765021860726683, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12214947430735827, 'warm_start': False}. Best is trial 12 with value: 0.6203200541271249.
Fold 1 C-index: 0.6264744429882044
Fold 2 C-index: 0.7634146341463415
Fold 3 C-index: 0.6948324022346368
[I 2024-04-21 15:26:49,559] Trial 14 finished with value: 0.6949071597897275 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.7873021337102564, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1076897288755021, 'warm_start': True}. Best is trial 14 with value: 0.6949071597897275.
Fold 1 C-index: 0.617300131061599
Fold 2 C-index: 0.6780487804878049
Fold 3 C-index: 0.6864525139664804
[I 2024-04-21 15:26:49,922] Trial 15 finished with value: 0.6606004751719614 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 42, 'oob_score': True, 'max_samples': 0.8219485202814404, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20648604556011108, 'warm_start': True}. Best is trial 14 with value: 0.6949071597897275.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:50,163] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 4, 'oob_score': True, 'max_samples': 0.44827686549014745, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.37909912926450273, 'warm_start': True}. Best is trial 14 with value: 0.6949071597897275.

Fold 1 C-index: 0.6114023591087812
Fold 2 C-index: 0.6780487804878049
Fold 3 C-index: 0.6717877094972067
[I 2024-04-21 15:26:50,841] Trial 17 finished with value: 0.6537462830312643 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 96, 'oob_score': True, 'max_samples': 0.9817072304699028, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.209156403415012, 'warm_start': True}. Best is trial 14 with value: 0.6949071597897275.
Fold 1 C-index: 0.6055045871559633
Fold 2 C-index: 0.6577235772357723
Fold 3 C-index: 0.6962290502793296
[I 2024-04-21 15:26:51,122] Trial 18 finished with value: 0.6531524048903551 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 6, 'n_estimators': 21, 'oob_score': True, 'max_samples': 0.8351211325657262, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07958856082174798, 'warm_start': True}. Best is trial 14 with value: 0.6949071597897275.
Fold 1 C-index: 0.6114023591087812
Fold 2 C-index: 0.7113821138211383
Fold 3 C-index: 0.6543296089385475
[I 2024-04-21 15:26:51,953] Trial 19 finished with value: 0.659038027289489 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 15, 'n_estimators': 107, 'oob_score': True, 'max_samples': 0.5143079809712325, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19980770969993192, 'warm_start': True}. Best is trial 14 with value: 0.6949071597897275.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:52,487] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 71, 'oob_score': True, 'max_samples': 0.7054267555421955, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.40207966674745593, 'warm_start': True}. Best is trial 14 with value: 0.6949071597897275.
Fold 1 C-index: 0.6055045871559633
Fold 2 C-index: 0.6861788617886179
Fold 3 C-index: 0.6585195530726257
[I 2024-04-21 15:26:53,169] Trial 21 finished with value: 0.650067667339069 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 116, 'oob_score': True, 'max_samples': 0.49624070607442805, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1920550526614133, 'warm_start': True}. Best is trial 14 with value: 0.6949071597897275.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
[I 2024-04-21 15:26:54,165] Trial 22 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 15, 'n_estimators': 151, 'oob_score': True, 'max_samples': 0.39123396977027813, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2550741014663508, 'warm_start': True}. Best is trial 14 with value: 0.6949071597897275.
Fold 1 C-index: 0.6146788990825688
Fold 2 C-index: 0.6682926829268293
Fold 3 C-index: 0.6543296089385475
[I 2024-04-21 15:26:54,511] Trial 23 finished with value: 0.6457670636493152 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 18, 'n_estimators': 41, 'oob_score': True, 'max_samples': 0.5459185695485101, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07940861604666782, 'warm_start': True}. Best is trial 14 with value: 0.6949071597897275.
Fold 1 C-index: 0.6238532110091743
Fold 2 C-index: 0.6967479674796748
Fold 3 C-index: 0.7004189944134078
[I 2024-04-21 15:26:55,199] Trial 24 finished with value: 0.673673390967419 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 69, 'oob_score': True, 'max_samples': 0.8507034089909646, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16402002225933776, 'warm_start': True}. Best is trial 14 with value: 0.6949071597897275.
Fold 1 C-index: 0.6212319790301442
Fold 2 C-index: 0.6967479674796748
Fold 3 C-index: 0.6941340782122905
[I 2024-04-21 15:26:55,849] Trial 25 finished with value: 0.6707046749073697 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.8482944825985398, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16293488683594895, 'warm_start': True}. Best is trial 14 with value: 0.6949071597897275.
Fold 1 C-index: 0.6146788990825688
Fold 2 C-index: 0.7634146341463415
Fold 3 C-index: 0.723463687150838
[I 2024-04-21 15:26:56,435] Trial 26 finished with value: 0.7005190734599159 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.9945975063825754, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08974480297156207, 'warm_start': True}. Best is trial 26 with value: 0.7005190734599159.
Fold 1 C-index: 0.5596330275229358
Fold 2 C-index: 0.724390243902439
Fold 3 C-index: 0.710195530726257
[I 2024-04-21 15:26:56,687] Trial 27 finished with value: 0.6647396007172106 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 1, 'oob_score': True, 'max_samples': 0.9934388263821101, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09241260440070255, 'warm_start': True}. Best is trial 26 with value: 0.7005190734599159.
Fold 1 C-index: 0.5950196592398427
Fold 2 C-index: 0.8113821138211382
Fold 3 C-index: 0.6501396648044693
[I 2024-04-21 15:26:58,143] Trial 28 finished with value: 0.6855138126218167 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 231, 'oob_score': True, 'max_samples': 0.8793200647776942, 'max_features': None, 'min_weight_fraction_leaf': 0.008942344809432207, 'warm_start': True}. Best is trial 26 with value: 0.7005190734599159.
Fold 1 C-index: 0.6363040629095675
Fold 2 C-index: 0.7764227642276422
Fold 3 C-index: 0.7171787709497207
[I 2024-04-21 15:26:59,675] Trial 29 finished with value: 0.7099685326956435 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 234, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': None, 'min_weight_fraction_leaf': 0.0460508358538211, 'warm_start': True}. Best is trial 29 with value: 0.7099685326956435.
Fold 1 C-index: 0.627129750982962
Fold 2 C-index: 0.7902439024390244
Fold 3 C-index: 0.7458100558659218
[I 2024-04-21 15:27:00,681] Trial 30 finished with value: 0.7210612364293026 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 148, 'oob_score': True, 'max_samples': 0.646484146236542, 'max_features': None, 'min_weight_fraction_leaf': 0.04151182856170796, 'warm_start': True}. Best is trial 30 with value: 0.7210612364293026.
Fold 1 C-index: 0.6212319790301442
Fold 2 C-index: 0.7837398373983739
Fold 3 C-index: 0.7604748603351955
[I 2024-04-21 15:27:01,691] Trial 31 finished with value: 0.7218155589212379 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 152, 'oob_score': True, 'max_samples': 0.7048122615891188, 'max_features': None, 'min_weight_fraction_leaf': 0.054241002029643964, 'warm_start': True}. Best is trial 31 with value: 0.7218155589212379.
Fold 1 C-index: 0.6304062909567497
Fold 2 C-index: 0.7886178861788617
Fold 3 C-index: 0.75768156424581
[I 2024-04-21 15:27:02,659] Trial 32 finished with value: 0.7255685804604738 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 155, 'oob_score': True, 'max_samples': 0.682998409656429, 'max_features': None, 'min_weight_fraction_leaf': 0.0532160332117876, 'warm_start': True}. Best is trial 32 with value: 0.7255685804604738.
Fold 1 C-index: 0.6212319790301442
Fold 2 C-index: 0.7886178861788617
Fold 3 C-index: 0.7891061452513967
[I 2024-04-21 15:27:03,489] Trial 33 finished with value: 0.7329853368201342 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 146, 'oob_score': True, 'max_samples': 0.6935015483404495, 'max_features': None, 'min_weight_fraction_leaf': 0.04762956572438005, 'warm_start': True}. Best is trial 33 with value: 0.7329853368201342.

Fold 1 C-index: 0.6166448230668414
Fold 2 C-index: 0.7926829268292683
Fold 3 C-index: 0.7751396648044693
[I 2024-04-21 15:27:04,244] Trial 34 finished with value: 0.7281558049001932 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 151, 'oob_score': True, 'max_samples': 0.6774051136290056, 'max_features': None, 'min_weight_fraction_leaf': 0.060182724928068816, 'warm_start': True}. Best is trial 33 with value: 0.7329853368201342.
Fold 1 C-index: 0.6192660550458715
Fold 2 C-index: 0.7910569105691057
Fold 3 C-index: 0.7751396648044693
[I 2024-04-21 15:27:05,450] Trial 35 finished with value: 0.7284875434731489 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 185, 'oob_score': True, 'max_samples': 0.6055530408056076, 'max_features': None, 'min_weight_fraction_leaf': 0.0011544170931962194, 'warm_start': True}. Best is trial 33 with value: 0.7329853368201342.
Fold 1 C-index: 0.6264744429882044
Fold 2 C-index: 0.7959349593495935
Fold 3 C-index: 0.7779329608938548
[I 2024-04-21 15:27:06,996] Trial 36 finished with value: 0.7334474544105509 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 206, 'oob_score': True, 'max_samples': 0.584890323622532, 'max_features': None, 'min_weight_fraction_leaf': 0.00052334394504433, 'warm_start': True}. Best is trial 36 with value: 0.7334474544105509.
Fold 1 C-index: 0.6264744429882044
Fold 2 C-index: 0.7926829268292683
Fold 3 C-index: 0.7807262569832403
[I 2024-04-21 15:27:08,142] Trial 37 finished with value: 0.7332945422669045 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 195, 'oob_score': True, 'max_samples': 0.5879329018852981, 'max_features': None, 'min_weight_fraction_leaf': 0.001556188988868873, 'warm_start': True}. Best is trial 36 with value: 0.7334474544105509.
Fold 1 C-index: 0.6159895150720839
Fold 2 C-index: 0.7878048780487805
Fold 3 C-index: 0.7821229050279329
[I 2024-04-21 15:27:09,438] Trial 38 finished with value: 0.7286390993829324 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 201, 'oob_score': True, 'max_samples': 0.5753917338753415, 'max_features': None, 'min_weight_fraction_leaf': 0.00253133570244603, 'warm_start': True}. Best is trial 36 with value: 0.7334474544105509.
Fold 1 C-index: 0.6094364351245085
Fold 2 C-index: 0.8048780487804879
Fold 3 C-index: 0.7779329608938548
[I 2024-04-21 15:27:11,725] Trial 39 finished with value: 0.7307491482662837 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 339, 'oob_score': True, 'max_samples': 0.5584624909113933, 'max_features': None, 'min_weight_fraction_leaf': 0.003909561743223998, 'warm_start': True}. Best is trial 36 with value: 0.7334474544105509.
Fold 1 C-index: 0.6133682830930537
Fold 2 C-index: 0.7804878048780488
Fold 3 C-index: 0.7206703910614525
[I 2024-04-21 15:27:13,286] Trial 40 finished with value: 0.7048421596775182 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 348, 'oob_score': True, 'max_samples': 0.356068505843076, 'max_features': None, 'min_weight_fraction_leaf': 0.029813810847214628, 'warm_start': True}. Best is trial 36 with value: 0.7334474544105509.
Fold 1 C-index: 0.6055045871559633
Fold 2 C-index: 0.8113821138211382
Fold 3 C-index: 0.7779329608938548
[I 2024-04-21 15:27:15,311] Trial 41 finished with value: 0.7316065539569854 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 390, 'oob_score': True, 'max_samples': 0.5654301302936586, 'max_features': None, 'min_weight_fraction_leaf': 0.00031507999865499616, 'warm_start': True}. Best is trial 36 with value: 0.7334474544105509.
Fold 1 C-index: 0.6028833551769331
Fold 2 C-index: 0.8097560975609757
Fold 3 C-index: 0.776536312849162
[I 2024-04-21 15:27:17,314] Trial 42 finished with value: 0.7297252551956902 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 390, 'oob_score': True, 'max_samples': 0.5349014778461011, 'max_features': None, 'min_weight_fraction_leaf': 0.01891365155764928, 'warm_start': True}. Best is trial 36 with value: 0.7334474544105509.
Fold 1 C-index: 0.6146788990825688
Fold 2 C-index: 0.7983739837398374
Fold 3 C-index: 0.7416201117318436
[I 2024-04-21 15:27:18,990] Trial 43 finished with value: 0.7182243315180833 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 314, 'oob_score': True, 'max_samples': 0.44141064550009307, 'max_features': None, 'min_weight_fraction_leaf': 0.030665383146069217, 'warm_start': True}. Best is trial 36 with value: 0.7334474544105509.
Fold 1 C-index: 0.617300131061599
Fold 2 C-index: 0.7991869918699187
Fold 3 C-index: 0.7960893854748603
[I 2024-04-21 15:27:21,387] Trial 44 finished with value: 0.7375255028021259 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 387, 'oob_score': True, 'max_samples': 0.637204151161286, 'max_features': None, 'min_weight_fraction_leaf': 0.0698334924574171, 'warm_start': True}. Best is trial 44 with value: 0.7375255028021259.
Fold 1 C-index: 0.617300131061599
Fold 2 C-index: 0.7902439024390244
Fold 3 C-index: 0.7625698324022346
[I 2024-04-21 15:27:22,996] Trial 45 finished with value: 0.723371288634286 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 480, 'oob_score': False, 'max_samples': 0.7455680507825904, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07098367259486094, 'warm_start': True}. Best is trial 44 with value: 0.7375255028021259.
Fold 1 C-index: 0.6304062909567497
Fold 2 C-index: 0.5382113821138211
Fold 3 C-index: 0.5600558659217877
[I 2024-04-21 15:27:26,762] Trial 46 finished with value: 0.5762245129974528 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.6519822948941599, 'max_features': None, 'min_weight_fraction_leaf': 0.1067722201468298, 'warm_start': False}. Best is trial 44 with value: 0.7375255028021259.
Fold 1 C-index: 0.6264744429882044
Fold 2 C-index: 0.6934959349593496
Fold 3 C-index: 0.7108938547486033
[I 2024-04-21 15:27:27,715] Trial 47 finished with value: 0.6769547442320524 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 272, 'oob_score': False, 'max_samples': 0.6088653618119219, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13730219295844726, 'warm_start': True}. Best is trial 44 with value: 0.7375255028021259.
Fold 1 C-index: 0.617300131061599
Fold 2 C-index: 0.5390243902439025
Fold 3 C-index: 0.5670391061452514
[I 2024-04-21 15:27:32,121] Trial 48 finished with value: 0.5744545424835844 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 427, 'oob_score': True, 'max_samples': 0.6267676578020946, 'max_features': None, 'min_weight_fraction_leaf': 0.025295495584211264, 'warm_start': False}. Best is trial 44 with value: 0.7375255028021259.
Fold 1 C-index: 0.6159895150720839
Fold 2 C-index: 0.791869918699187
Fold 3 C-index: 0.7779329608938548
[I 2024-04-21 15:27:33,288] Trial 49 finished with value: 0.7285974648883752 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 242, 'oob_score': True, 'max_samples': 0.49484120005373133, 'max_features': None, 'min_weight_fraction_leaf': 0.03922165249204643, 'warm_start': True}. Best is trial 44 with value: 0.7375255028021259.
Fold 1 C-index: 0.6107470511140236
Fold 2 C-index: 0.6813008130081301
Fold 3 C-index: 0.6682960893854749
[I 2024-04-21 15:27:34,389] Trial 50 finished with value: 0.6534479845025428 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 292, 'oob_score': False, 'max_samples': 0.747810115137022, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2829198778336303, 'warm_start': True}. Best is trial 44 with value: 0.7375255028021259.

Fold 1 C-index: 0.6107470511140236
Fold 2 C-index: 0.8065040650406504
Fold 3 C-index: 0.7988826815642458
[I 2024-04-21 15:27:36,310] Trial 51 finished with value: 0.7387112659063066 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 325, 'oob_score': True, 'max_samples': 0.5771867200889673, 'max_features': None, 'min_weight_fraction_leaf': 0.0005060870308750869, 'warm_start': True}. Best is trial 51 with value: 0.7387112659063066.
Fold 1 C-index: 0.6199213630406291
Fold 2 C-index: 0.7959349593495935
Fold 3 C-index: 0.755586592178771
[I 2024-04-21 15:27:38,278] Trial 52 finished with value: 0.7238143048563312 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 384, 'oob_score': True, 'max_samples': 0.5725363198754724, 'max_features': None, 'min_weight_fraction_leaf': 0.06586567967665147, 'warm_start': True}. Best is trial 51 with value: 0.7387112659063066.
Fold 1 C-index: 0.6277850589777195
Fold 2 C-index: 0.7926829268292683
Fold 3 C-index: 0.7472067039106145
[I 2024-04-21 15:27:40,343] Trial 53 finished with value: 0.7225582299058675 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 423, 'oob_score': True, 'max_samples': 0.47688240099064616, 'max_features': None, 'min_weight_fraction_leaf': 0.02101748540029501, 'warm_start': True}. Best is trial 51 with value: 0.7387112659063066.
Fold 1 C-index: 0.598951507208388
Fold 2 C-index: 0.832520325203252
Fold 3 C-index: 0.8058659217877095
[I 2024-04-21 15:27:42,335] Trial 54 finished with value: 0.7457792513997831 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 325, 'oob_score': True, 'max_samples': 0.6365524404665521, 'max_features': None, 'min_weight_fraction_leaf': 4.7917122108652585e-05, 'warm_start': True}. Best is trial 54 with value: 0.7457792513997831.
Fold 1 C-index: 0.6225425950196593
Fold 2 C-index: 0.7894308943089431
Fold 3 C-index: 0.8100558659217877
[I 2024-04-21 15:27:43,793] Trial 55 finished with value: 0.74067645175013 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 210, 'oob_score': True, 'max_samples': 0.6549727075663738, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.040740563230871996, 'warm_start': True}. Best is trial 54 with value: 0.7457792513997831.
Fold 1 C-index: 0.6133682830930537
[W 2024-04-21 15:27:45,949] Trial 56 failed with parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.6379731816103813, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09674438375991072, 'warm_start': False} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/var/folders/64/jkqp6xyx2hj50dmd2pqfm3780000gn/T/ipykernel_41708/1474426952.py", line 56, in objective
    model.fit(X_train, y_train)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/ensemble/forest.py", line 167, in fit
    self._set_oob_score_and_attributes(X, (event, time))
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/ensemble/forest.py", line 182, in _set_oob_score_and_attributes
    unsampled_indices = _generate_unsampled_indices(estimator.random_state, n_samples, n_samples_bootstrap)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 136, in _generate_unsampled_indices
    sample_indices = _generate_sample_indices(
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 127, in _generate_sample_indices
    random_instance = check_random_state(random_state)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py", line 1226, in check_random_state
    return np.random.RandomState(seed)
  File "mtrand.pyx", line 184, in numpy.random.mtrand.RandomState.__init__
  File "_mt19937.pyx", line 130, in numpy.random._mt19937.MT19937.__init__
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
KeyboardInterrupt
[W 2024-04-21 15:27:45,975] Trial 56 failed with value None.

KeyboardInterrupt:

In [ ]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [ ]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

#### Test

In [ ]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [ ]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

In [ ]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [ ]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [ ]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

In [ ]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [ ]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

#### Test

In [ ]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [ ]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

In [ ]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [ ]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

In [ ]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [ ]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

#### Test

In [ ]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [ ]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

In [ ]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [ ]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [ ]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

In [ ]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [ ]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

#### Test

In [ ]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [ ]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

In [ ]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

# Results

In [ ]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

In [ ]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

In [ ]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

In [ ]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

In [ ]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/dfs/minmax/rent/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_dfs_minmax_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [ ]:
from datetime import date
today = date.today()
print("Date: ", today)