In [1]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

In [6]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

### COX assumption in Train data

In [7]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                test_statistic    p  -log2(p)
MTV                       0.00 0.95      0.08
SUVpeak                   0.29 0.59      0.76
TLG                       0.22 0.64      0.65
age                       1.60 0.21      2.28
cavum_oris                0.00 1.00      0.01
charlson                  0.07 0.79      0.34
female                    0.17 0.68      0.56
histgrade_high            1.26 0.26      1.93
hpv_related               4.31 0.04      4.72
hypopharynx               0.00 0.99      0.01
larynx                    0.00 0.98      0.02
oropharynx                0.00 0.99      0.02
pack_years                0.71 0.40      1.32
uicc8_III-IV              0.45 0.50      0.99

In [8]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['hpv_related'], dtype='object')

In [9]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                test_statistic    p  -log2(p)
MTV                       0.02 0.88      0.18
SUVpeak                   0.56 0.46      1.13
TLG                       0.06 0.81      0.30
age                       1.58 0.21      2.26
cavum_oris                0.08 0.77      0.37
charlson                  0.03 0.86      0.22
female                    0.35 0.56      0.85
histgrade_high            0.95 0.33      1.60
hpv_related               3.02 0.08      3.60
hypopharynx               0.10 0.75      0.41
larynx                    1.46 0.23      2.14
oropharynx                0.96 0.33      1.61
pack_years                0.39 0.53      0.92
uicc8_III-IV              0.08 0.78      0.36

In [10]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index([], dtype='object')

###### penalizer values essentially result in same result

## Test dataset: MAASTRO

In [11]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [12]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [13]:
# need to choose patient_id from MAASTRO_D1 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [14]:
# Merge MAASTRO_D1 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG,DFS,DFS_event
0,1,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342,8.83,1.0
3,4,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979,19.73,1.0
4,6,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782,13.27,1.0
95,111,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212,72.07,0.0

In [15]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [16]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, DFS, DFS_event]
Index: []

In [17]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [18]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [19]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 14)
y_train:  (139,)

In [20]:
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [21]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 16)

In [22]:
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X.values, i) 
                          for i in range(len(X.columns))] 

vif_data

           feature        VIF
0              age   1.136852
1           female   1.197250
2       cavum_oris   7.993011
3       oropharynx  60.199385
4      hypopharynx  11.118710
5           larynx  14.183474
6   histgrade_high   1.150479
7      hpv_related   4.309385
8         charlson   1.302350
9       pack_years   1.647441
10    uicc8_III-IV   2.026695
11         SUVpeak   2.157147
12             MTV   5.247552
13             TLG   6.368452

# Standardization

In [23]:
original_X = X.copy()

In [24]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

## Standardize the data but not the categorical columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']
### Separate the categorical and non-categorical columns
X_categorical = X[categorical_columns]
X_numeric = X.drop(categorical_columns, axis=1)
X_numeric_columns = X_numeric.columns
X_numeric_index = X_numeric.index

### Standardize non-categorical and then concat with the categorical
scaler = StandardScaler()  
X_numeric_std = scaler.fit_transform(X_numeric)
X_numeric_std = pd.DataFrame(X_numeric_std, columns=X_numeric_columns, index=X_numeric_index)
X_std = pd.concat([X_categorical, X_numeric_std], axis=1)

## Sort the order of the columns as it was in the clinical train 
X_std = X_std[original_X.columns]

In [25]:
# Standardize X_MAASTRO 
MAASTRO_new = X_MAASTRO.copy()
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns

MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new = MAASTRO_new[original_X.columns]
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [26]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = MAASTRO_new_std

In [27]:
X_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,54.238356,1,0,1,0,0,1,0.0,0,0.000000,0.0,14.473272,7.934,86.228420
1,54.539726,0,0,0,0,1,0,0.0,1,27.404795,0.0,5.044678,1.656,7.040100
2,59.019178,0,1,0,0,0,1,0.0,1,41.019178,1.0,7.839043,14.502,83.569669
3,70.726027,0,0,0,0,1,0,0.0,1,37.500000,0.0,2.880631,2.440,5.567091
4,67.865753,0,0,0,0,1,0,0.0,1,53.000000,0.0,5.402006,3.668,16.150550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,60.435616,0,0,1,0,0,1,1.0,0,0.000000,0.0,9.290139,3.650,26.280140
135,68.794521,0,0,1,0,0,1,1.0,0,0.000000,1.0,7.172883,18.967,101.754834
136,57.498630,0,0,1,0,0,1,1.0,1,39.498630,0.0,13.873187,6.370,66.273201
137,65.684932,0,0,1,0,0,1,1.0,1,71.527397,1.0,7.507419,12.443,71.832443
138,61.676712,0,0,1,0,0,1,1.0,0,2.250000,1.0,13.053465,7.983,78.647696

In [28]:
X_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,-0.776210,1,0,1,0,0,1,0.0,0,-1.101176,0.0,0.646616,-0.296907,-0.179158
1,-0.737256,0,0,0,0,1,0,0.0,1,0.105775,0.0,-1.098689,-0.763433,-0.587333
2,-0.158251,0,1,0,0,0,1,0.0,1,0.705374,1.0,-0.581431,0.191169,-0.192863
3,1.354953,0,0,0,0,1,0,0.0,1,0.550384,0.0,-1.499271,-0.705173,-0.594926
4,0.985240,0,0,0,0,1,0,0.0,1,1.233028,0.0,-1.032545,-0.613919,-0.540373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,0.024835,0,0,1,0,0,1,1.0,0,-1.101176,0.0,-0.312822,-0.615257,-0.488161
135,1.105290,0,0,1,0,0,1,1.0,0,-1.101176,1.0,-0.704742,0.522969,-0.099128
136,-0.354794,0,0,1,0,0,1,1.0,1,0.638406,0.0,0.535536,-0.413130,-0.282017
137,0.703351,0,0,1,0,0,1,1.0,1,2.049005,1.0,-0.642817,0.038162,-0.253362
138,0.185257,0,0,1,0,0,1,1.0,0,-1.002083,1.0,0.383799,-0.293266,-0.218233

In [29]:
MAASTRO_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623
1,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700
2,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342
3,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979
4,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782
95,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868
96,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274
97,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492
98,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212

In [30]:
MAASTRO_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,-0.677762,0,0,1,0,0,1,1,1,-1.101176,0,0.825303,0.810851,0.735160
1,-0.677762,0,0,1,0,0,0,0,0,-0.220344,1,-0.398117,-0.465891,-0.433005
2,-0.677762,0,0,1,0,0,0,0,1,-0.836927,1,0.462036,-0.307534,-0.238909
3,0.097786,1,0,0,0,1,1,0,1,0.880696,1,-0.434513,-0.298839,-0.382433
4,1.261108,0,0,1,0,0,1,1,1,1.497278,0,-0.221413,0.245788,-0.068806
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0.744076,1,0,0,0,1,0,0,0,1.321112,1,3.768483,-0.432451,0.121154
95,0.356302,0,0,0,0,1,0,0,1,6.562062,1,0.381603,-0.352789,-0.266854
96,0.356302,0,0,1,0,0,1,1,1,-1.101176,1,-0.376799,0.338380,-0.094801
97,-0.807020,0,0,1,0,0,1,1,0,-1.101176,0,0.593113,-0.144792,-0.091527
98,0.227044,0,0,0,1,0,1,0,0,0.660488,1,-0.104629,-0.626775,-0.476444

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [31]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 14:54:46,837] A new study created in memory with name: no-name-af5fee8b-78ba-4338-a224-b0dfdabd9f04

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115

[I 2024-04-18 14:54:47,625] A new study created in memory with name: no-name-a521de8b-3391-4d78-8d0c-46a133926e20

Fold 5 C-index: 0.630901287553648
[I 2024-04-18 14:54:47,560] Trial 0 finished with value: 0.6371137109369622 and parameters: {}. Best is trial 0 with value: 0.6371137109369622.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6371137109369622], datetime_start=datetime.datetime(2024, 4, 18, 14, 54, 47, 10222), datetime_complete=datetime.datetime(2024, 4, 18, 14, 54, 47, 559979), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6371137109369622

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.25671409350000196
Fold 2 IBS: 0.2656989046953461
Fold 3 IBS: 0.168829941254425
Fold 4 IBS: 0.2959795071877819
Fold 5 IBS: 0.21043512284090152
[I 2024-04-18 14:54:48,246] Trial 0 finished with value: 0.23953151389569127 and parameters: {}. Best is trial 0 with value: 0.23953151389569127.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23953151389569127], datetime_start=datetime.datetime(2024, 4, 18, 14, 54, 47, 770980), datetime_complete=datetime.datetime(2024, 4, 18, 14, 54, 48, 246092), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23953151389569127

In [32]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [33]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.637
train_ibs:  0.24

#### Test

In [34]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [35]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.563
IBS score: 0.291

In [36]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [37]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [38]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 14:54:58,523] A new study created in memory with name: no-name-f14e65c3-a16f-42c8-bee3-5b47322d63f2

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-18 14:54:58,774] A new study created in memory with name: no-name-08615c4d-ab7f-407f-a5ce-58ca9c968131

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.5038759689922481
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.48859315589353614
Fold 5 C-index: 0.6652360515021459
[I 2024-04-18 14:54:58,717] Trial 0 finished with value: 0.5709459687352447 and parameters: {}. Best is trial 0 with value: 0.5709459687352447.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5709459687352447], datetime_start=datetime.datetime(2024, 4, 18, 14, 54, 58, 551214), datetime_complete=datetime.datetime(2024, 4, 18, 14, 54, 58, 716900), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5709459687352447

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709637048833
Fold 2 IBS: 0.2320398857267834
Fold 3 IBS: 0.22898186411767818
Fold 4 IBS: 0.24197478791371138
Fold 5 IBS: 0.22939558350833852
[I 2024-04-18 14:54:59,244] Trial 0 finished with value: 0.23592784352739998 and parameters: {}. Best is trial 0 with value: 0.23592784352739998.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592784352739998], datetime_start=datetime.datetime(2024, 4, 18, 14, 54, 58, 946721), datetime_complete=datetime.datetime(2024, 4, 18, 14, 54, 59, 243800), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592784352739998

In [39]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [40]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.571
train_ibs:  0.236

#### Test

In [41]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [42]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.532

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [43]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [44]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 14:55:02,203] A new study created in memory with name: no-name-74ab9955-04eb-4629-bf12-d411dc2fb323

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901

[I 2024-04-18 14:55:02,923] A new study created in memory with name: no-name-caa674f8-256d-4eee-9802-b3b4ab29a764

Fold 5 C-index: 0.630901287553648
[I 2024-04-18 14:55:02,857] Trial 0 finished with value: 0.635556441914194 and parameters: {}. Best is trial 0 with value: 0.635556441914194.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.635556441914194], datetime_start=datetime.datetime(2024, 4, 18, 14, 55, 2, 231877), datetime_complete=datetime.datetime(2024, 4, 18, 14, 55, 2, 857005), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.635556441914194

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2612135612445686
Fold 2 IBS: 0.26335163677719536
Fold 3 IBS: 0.17031007633731787
Fold 4 IBS: 0.29553230790913454
Fold 5 IBS: 0.21015944157044716
[I 2024-04-18 14:55:03,939] Trial 0 finished with value: 0.24011340476773274 and parameters: {}. Best is trial 0 with value: 0.24011340476773274.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.24011340476773274], datetime_start=datetime.datetime(2024, 4, 18, 14, 55, 3, 20064), datetime_complete=datetime.datetime(2024, 4, 18, 14, 55, 3, 938929), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.24011340476773274

In [45]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [46]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.636
train_ibs:  0.24

#### Test

In [47]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [48]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.566

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.288

In [49]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [50]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 14:55:04,846] A new study created in memory with name: no-name-fbfbb8d4-b39e-40ef-8cc1-60d3e26342d5

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 14:55:05,799] Trial 0 finished with value: 0.635556441914194 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.635556441914194.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:06,356] Trial 1 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.6371752672866707.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:06,993] Trial 2 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 14:55:07,737] Trial 3 finished with value: 0.6363168981879583 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 14:55:08,424] Trial 4 finished with value: 0.6363168981879583 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:09,194] Trial 5 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 14:55:09,896] Trial 6 finished with value: 0.635556441914194 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 14:55:10,632] Trial 7 finished with value: 0.635556441914194 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:11,264] Trial 8 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:11,887] Trial 9 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5171102661596958
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:55:12,225] Trial 10 finished with value: 0.5577793558325144 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:12,814] Trial 11 finished with value: 0.6283220949542085 and parameters: {'l1_ratio': 0.19077404209371474}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:13,607] Trial 12 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.22959915831444896}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.6652360515021459
[I 2024-04-18 14:55:13,821] Trial 13 finished with value: 0.5638800790025962 and parameters: {'l1_ratio': 0.0058200831877644466}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:14,440] Trial 14 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.24133971598258583}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:55:14,839] Trial 15 finished with value: 0.5904789756043776 and parameters: {'l1_ratio': 0.13928512472646692}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:15,530] Trial 16 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.31408489302885545}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:16,269] Trial 17 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.33349610072100666}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.49429657794676807
Fold 5 C-index: 0.6652360515021459
[I 2024-04-18 14:55:16,531] Trial 18 finished with value: 0.5676823603714174 and parameters: {'l1_ratio': 0.02687428103103129}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 14:55:17,045] Trial 19 finished with value: 0.6363168981879583 and parameters: {'l1_ratio': 0.5542002488722811}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:55:17,482] Trial 20 finished with value: 0.5904789756043776 and parameters: {'l1_ratio': 0.15523641724239506}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:18,100] Trial 21 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.2367517986971607}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:19,184] Trial 22 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.23191244143423032}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:55:19,584] Trial 23 finished with value: 0.5904789756043776 and parameters: {'l1_ratio': 0.1060695846119758}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287

Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:20,255] Trial 24 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.3752730935447346}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:20,574] Trial 25 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.26085123056535237}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:21,098] Trial 26 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.43696099753129897}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:21,572] Trial 27 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.21250409802134868}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5133079847908745
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:55:21,727] Trial 28 finished with value: 0.5737519672878338 and parameters: {'l1_ratio': 0.08134203106106797}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:22,373] Trial 29 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.3247289168735353}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 14:55:22,990] Trial 30 finished with value: 0.635556441914194 and parameters: {'l1_ratio': 0.6348147138790865}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:23,602] Trial 31 finished with value: 0.6283220949542085 and parameters: {'l1_ratio': 0.1843746877946028}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:24,350] Trial 32 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.26577028718850243}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 14:55:24,795] Trial 33 finished with value: 0.635556441914194 and parameters: {'l1_ratio': 0.8602844507263662}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:25,395] Trial 34 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.3405221875209412}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:25,915] Trial 35 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.26075493998526766}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 14:55:26,403] Trial 36 finished with value: 0.6363168981879583 and parameters: {'l1_ratio': 0.5257040386795849}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:26,864] Trial 37 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.4544709824843894}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:27,329] Trial 38 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.3839618929933269}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:55:27,723] Trial 39 finished with value: 0.5904789756043776 and parameters: {'l1_ratio': 0.1406969106839306}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5133079847908745
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:55:28,089] Trial 40 finished with value: 0.5737519672878338 and parameters: {'l1_ratio': 0.08116923674338555}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:28,897] Trial 41 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.2461752244867114}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:29,549] Trial 42 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.23146255358066037}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:30,218] Trial 43 finished with value: 0.6283220949542085 and parameters: {'l1_ratio': 0.1838829985579825}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:31,206] Trial 44 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.29021963736591927}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:31,987] Trial 45 finished with value: 0.6372368236363792 and parameters: {'l1_ratio': 0.2076317823708102}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:32,781] Trial 46 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.36287527192740016}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:55:33,236] Trial 47 finished with value: 0.5904789756043776 and parameters: {'l1_ratio': 0.11756243140033039}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.6254980079681275

Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5019011406844106
Fold 5 C-index: 0.6609442060085837
[I 2024-04-18 14:55:33,458] Trial 48 finished with value: 0.5683449038202336 and parameters: {'l1_ratio': 0.04487776284637307}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:34,218] Trial 49 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.2881440462226219}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:34,951] Trial 50 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.41653985858071785}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:35,724] Trial 51 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.2114115848967811}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:55:36,182] Trial 52 finished with value: 0.5904789756043776 and parameters: {'l1_ratio': 0.15322809726098252}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:36,960] Trial 53 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.21396708129018127}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:37,356] Trial 54 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.3062366799021071}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:37,659] Trial 55 finished with value: 0.5870454992095278 and parameters: {'l1_ratio': 0.1673143167422667}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 14:55:38,221] Trial 56 finished with value: 0.6347812481157444 and parameters: {'l1_ratio': 0.8182548665223563}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5019011406844106
Fold 5 C-index: 0.6609442060085837
[I 2024-04-18 14:55:38,424] Trial 57 finished with value: 0.5691417165692376 and parameters: {'l1_ratio': 0.051214731918134304}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:55:38,872] Trial 58 finished with value: 0.5904789756043776 and parameters: {'l1_ratio': 0.11974885016372433}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:39,554] Trial 59 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.23436300069175692}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 14:55:40,192] Trial 60 finished with value: 0.6363168981879583 and parameters: {'l1_ratio': 0.5892984254164416}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:40,843] Trial 61 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.23045954620674977}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:41,489] Trial 62 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.27241383857518625}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:42,218] Trial 63 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.3480104949533249}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:42,558] Trial 64 finished with value: 0.6283220949542085 and parameters: {'l1_ratio': 0.187237328085752}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:43,125] Trial 65 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.3071430647320003}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.467680608365019
Fold 5 C-index: 0.6652360515021459
[I 2024-04-18 14:55:43,311] Trial 66 finished with value: 0.5623591664550677 and parameters: {'l1_ratio': 0.0023101685703384167}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:43,945] Trial 67 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.25230715399707315}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:55:44,545] Trial 68 finished with value: 0.5904789756043776 and parameters: {'l1_ratio': 0.14877611066370214}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:45,131] Trial 69 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.4830392795338827}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.532319391634981
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:55:45,364] Trial 70 finished with value: 0.5608211809275714 and parameters: {'l1_ratio': 0.10184568307568467}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:46,111] Trial 71 finished with value: 0.6363784545376667 and parameters: {'l1_ratio': 0.21523887035665049}. Best is trial 2 with value: 0.6380336363853832.

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:46,885] Trial 72 finished with value: 0.6372368236363792 and parameters: {'l1_ratio': 0.20506460082233327}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:47,596] Trial 73 finished with value: 0.5870454992095278 and parameters: {'l1_ratio': 0.16922103364824678}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:48,165] Trial 74 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.23027763982881144}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:48,781] Trial 75 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.32239534272396714}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:49,179] Trial 76 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.28141817074948894}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:49,681] Trial 77 finished with value: 0.6283220949542085 and parameters: {'l1_ratio': 0.19328346899350535}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:50,372] Trial 78 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.2417634530203663}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 14:55:51,059] Trial 79 finished with value: 0.635556441914194 and parameters: {'l1_ratio': 0.9846333768922103}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:51,697] Trial 80 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.4042447145528881}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:52,381] Trial 81 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.230931910912554}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:55:52,858] Trial 82 finished with value: 0.5904789756043776 and parameters: {'l1_ratio': 0.13458727768127696}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:53,586] Trial 83 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.2715619674514067}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:54,237] Trial 84 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.3545115239935991}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:54,563] Trial 85 finished with value: 0.5870454992095278 and parameters: {'l1_ratio': 0.17612140627240536}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:55,232] Trial 86 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.3032070880652719}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:56,088] Trial 87 finished with value: 0.6372368236363792 and parameters: {'l1_ratio': 0.2176472112572884}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:56,902] Trial 88 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.2512110188135617}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:57,593] Trial 89 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.32819689403302466}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5171102661596958
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:55:57,905] Trial 90 finished with value: 0.5577793558325144 and parameters: {'l1_ratio': 0.08626372564369841}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:58,593] Trial 91 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.23466336846152977}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:59,241] Trial 92 finished with value: 0.6372368236363792 and parameters: {'l1_ratio': 0.20115084415210166}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:59,762] Trial 93 finished with value: 0.5870454992095278 and parameters: {'l1_ratio': 0.16096168010437928}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:56:00,113] Trial 94 finished with value: 0.5904789756043776 and parameters: {'l1_ratio': 0.12768980084916554}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115

Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:56:00,652] Trial 95 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.28458507950255774}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:56:01,248] Trial 96 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.26782540652964665}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:56:01,942] Trial 97 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.22853223596798222}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:56:02,493] Trial 98 finished with value: 0.6283220949542085 and parameters: {'l1_ratio': 0.1876351954660234}. Best is trial 2 with value: 0.6380336363853832.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745

[I 2024-04-18 14:56:03,276] A new study created in memory with name: no-name-091d831e-3fbe-4aa8-8a6c-03f827d99c41

Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:56:03,226] Trial 99 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.25083269958967586}. Best is trial 2 with value: 0.6380336363853832.


* Best trial for C-index:
 FrozenTrial(number=2, state=TrialState.COMPLETE, values=[0.6380336363853832], datetime_start=datetime.datetime(2024, 4, 18, 14, 55, 6, 419507), datetime_complete=datetime.datetime(2024, 4, 18, 14, 55, 6, 993319), params={'l1_ratio': 0.22692876841884668}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=2, value=None)


* Best Score for C-index:
 0.6380336363853832

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.25928666566134556
Fold 2 IBS: 0.2633235500953682
Fold 3 IBS: 0.1703452680482903
Fold 4 IBS: 0.2954820759487805
Fold 5 IBS: 0.2100027239709883
[I 2024-04-18 14:56:04,040] Trial 0 finished with value: 0.23968805674495455 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.23968805674495455.
Fold 1 IBS: 0.2584786536006208
Fold 2 IBS: 0.26323896642742395
Fold 3 IBS: 0.17025549969200326
Fold 4 IBS: 0.29530473742584673
Fold 5 IBS: 0.20967534920375316
[I 2024-04-18 14:56:04,982] Trial 1 finished with value: 0.23939064126992954 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.23939064126992954.
Fold 1 IBS: 0.2583088882294021
Fold 2 IBS: 0.2631695969400213
Fold 3 IBS: 0.1701909536443265
Fold 4 IBS: 0.2952670408466882
Fold 5 IBS: 0.20960920881776335
[I 2024-04-18 14:56:05,763] Trial 2 finished with value: 0.2393091376956403 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.2393091376956403.
Fold 1 IBS: 0.2590615959999675
Fold 2 IBS: 0.2632947287001669
Fold 3 IBS: 0.17033502420267774
Fold 4 IBS: 0.2954114004498061
Fold 5 IBS: 0.2098635386672121
[I 2024-04-18 14:56:06,493] Trial 3 finished with value: 0.23959325760396605 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.2393091376956403.
Fold 1 IBS: 0.259288850942299
Fold 2 IBS: 0.2631625563303711
Fold 3 IBS: 0.17032764728400432
Fold 4 IBS: 0.29550148544231647
Fold 5 IBS: 0.20998569403871825
[I 2024-04-18 14:56:07,190] Trial 4 finished with value: 0.2396532468075418 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.2393091376956403.
Fold 1 IBS: 0.25884147985455497
Fold 2 IBS: 0.26318868665575607
Fold 3 IBS: 0.1702354059106438
Fold 4 IBS: 0.29537679061149685
Fold 5 IBS: 0.20975134176662266
[I 2024-04-18 14:56:07,916] Trial 5 finished with value: 0.23947874095981486 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.2393091376956403.
Fold 1 IBS: 0.2612002243992095
Fold 2 IBS: 0.2633132318861241
Fold 3 IBS: 0.1703189483779546
Fold 4 IBS: 0.29559566686885
Fold 5 IBS: 0.210176813149458
[I 2024-04-18 14:56:08,634] Trial 6 finished with value: 0.2401209769363192 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.2393091376956403.
Fold 1 IBS: 0.2592847278806919
Fold 2 IBS: 0.26329016062191973
Fold 3 IBS: 0.17035477734302934
Fold 4 IBS: 0.29547306450816285
Fold 5 IBS: 0.20999087918710638
[I 2024-04-18 14:56:09,284] Trial 7 finished with value: 0.23967872190818204 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.2393091376956403.
Fold 1 IBS: 0.25885993801818064
Fold 2 IBS: 0.26323357813582987
Fold 3 IBS: 0.170283173243351
Fold 4 IBS: 0.29539468359271887
Fold 5 IBS: 0.20985754885387886
[I 2024-04-18 14:56:09,841] Trial 8 finished with value: 0.23952578436879185 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.2393091376956403.
Fold 1 IBS: 0.25865979857020843
Fold 2 IBS: 0.26325183516941664
Fold 3 IBS: 0.17026623600548113
Fold 4 IBS: 0.29532099321234373
Fold 5 IBS: 0.20975582619303001
[I 2024-04-18 14:56:10,658] Trial 9 finished with value: 0.23945093783009597 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.2393091376956403.
Fold 1 IBS: 0.257457494208612
Fold 2 IBS: 0.23303747227481786
Fold 3 IBS: 0.2263434041794141
Fold 4 IBS: 0.25352427678609724
Fold 5 IBS: 0.22384280144878846
[I 2024-04-18 14:56:10,983] Trial 10 finished with value: 0.23884108977954593 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.23884108977954593.
Fold 1 IBS: 0.24677716992668078
Fold 2 IBS: 0.23218628652788684
Fold 3 IBS: 0.22851411451112547
Fold 4 IBS: 0.2439660695904672
Fold 5 IBS: 0.22829549039603042
[I 2024-04-18 14:56:11,301] Trial 11 finished with value: 0.23594782619043814 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 11 with value: 0.23594782619043814.
Fold 1 IBS: 0.246315004814085
Fold 2 IBS: 0.23235039924351616
Fold 3 IBS: 0.2280299705876315
Fold 4 IBS: 0.24609402456739027
Fold 5 IBS: 0.22721466341890903
[I 2024-04-18 14:56:11,596] Trial 12 finished with value: 0.2360008125263064 and parameters: {'l1_ratio': 0.025939717088620355}. Best is trial 11 with value: 0.23594782619043814.
Fold 1 IBS: 0.24706623595532676
Fold 2 IBS: 0.23209388134055065
Fold 3 IBS: 0.22880502408645176
Fold 4 IBS: 0.2427202955154775
Fold 5 IBS: 0.22897234943010128
[I 2024-04-18 14:56:11,908] Trial 13 finished with value: 0.23593155726558157 and parameters: {'l1_ratio': 0.004533947374774427}. Best is trial 13 with value: 0.23593155726558157.
Fold 1 IBS: 0.2579550498986484
Fold 2 IBS: 0.23384073823231852
Fold 3 IBS: 0.2248371878508547
Fold 4 IBS: 0.29518909071999977
Fold 5 IBS: 0.20956259644617872
[I 2024-04-18 14:56:12,456] Trial 14 finished with value: 0.2442769326296 and parameters: {'l1_ratio': 0.15622422014607515}. Best is trial 13 with value: 0.23593155726558157.
Fold 1 IBS: 0.2469888021350035
Fold 2 IBS: 0.23211797907083867
Fold 3 IBS: 0.22872778610490166
Fold 4 IBS: 0.24304638306334886
Fold 5 IBS: 0.22879093318076077
[I 2024-04-18 14:56:12,972] Trial 15 finished with value: 0.23593437671097067 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 13 with value: 0.23593155726558157.
Fold 1 IBS: 0.2584781783522448
Fold 2 IBS: 0.263229604528837
Fold 3 IBS: 0.17025897501140402
Fold 4 IBS: 0.2953013785701624
Fold 5 IBS: 0.2096716833054188
[I 2024-04-18 14:56:13,638] Trial 16 finished with value: 0.2393879639536134 and parameters: {'l1_ratio': 0.28499627491162527}. Best is trial 13 with value: 0.23593155726558157.
Fold 1 IBS: 0.25795548228452814
Fold 2 IBS: 0.2338458917730229
Fold 3 IBS: 0.2248286957624461
Fold 4 IBS: 0.29519181441779363
Fold 5 IBS: 0.20956537907635112
[I 2024-04-18 14:56:14,153] Trial 17 finished with value: 0.2442774526628284 and parameters: {'l1_ratio': 0.15671420368983202}. Best is trial 13 with value: 0.23593155726558157.
Fold 1 IBS: 0.261204105356839
Fold 2 IBS: 0.26332427210850395
Fold 3 IBS: 0.1703163743393094
Fold 4 IBS: 0.2955983865414881
Fold 5 IBS: 0.2101801314683885
[I 2024-04-18 14:56:14,847] Trial 18 finished with value: 0.24012465396290578 and parameters: {'l1_ratio': 0.9862904274960449}. Best is trial 13 with value: 0.23593155726558157.
Fold 1 IBS: 0.25777489401850406
Fold 2 IBS: 0.23348903924443717
Fold 3 IBS: 0.22544904347943215
Fold 4 IBS: 0.29514101098188517
Fold 5 IBS: 0.2222589036391499
[I 2024-04-18 14:56:15,315] Trial 19 finished with value: 0.2468225782726817 and parameters: {'l1_ratio': 0.12363244492728864}. Best is trial 13 with value: 0.23593155726558157.
Fold 1 IBS: 0.2586410303505766
Fold 2 IBS: 0.2632333459595827
Fold 3 IBS: 0.17018025144769677
Fold 4 IBS: 0.2953075346666337
Fold 5 IBS: 0.20969547701589433
[I 2024-04-18 14:56:16,230] Trial 20 finished with value: 0.2394115278880768 and parameters: {'l1_ratio': 0.31598698424339017}. Best is trial 13 with value: 0.23593155726558157.
Fold 1 IBS: 0.24689262950983412
Fold 2 IBS: 0.23214851936812245
Fold 3 IBS: 0.2286313052708946
Fold 4 IBS: 0.24345979585872496
Fold 5 IBS: 0.2285657751173891
[I 2024-04-18 14:56:16,495] Trial 21 finished with value: 0.23593960502499303 and parameters: {'l1_ratio': 0.009107838351343097}. Best is trial 13 with value: 0.23593155726558157.
Fold 1 IBS: 0.24692491253780563
Fold 2 IBS: 0.23213817608256435
Fold 3 IBS: 0.22866380628370392
Fold 4 IBS: 0.24332017125681685
Fold 5 IBS: 0.22864135460310697
[I 2024-04-18 14:56:16,743] Trial 22 finished with value: 0.2359376841527995 and parameters: {'l1_ratio': 0.008242879725625268}. Best is trial 13 with value: 0.23593155726558157.
Fold 1 IBS: 0.2575698335623983
Fold 2 IBS: 0.2331901541766588
Fold 3 IBS: 0.22602551446163294
Fold 4 IBS: 0.25485867164802684
Fold 5 IBS: 0.22326574087786558
[I 2024-04-18 14:56:17,381] Trial 23 finished with value: 0.2389819829453165 and parameters: {'l1_ratio': 0.097070668839174}. Best is trial 13 with value: 0.23593155726558157.
Fold 1 IBS: 0.25817532388954584
Fold 2 IBS: 0.2342479359191175
Fold 3 IBS: 0.17019189199363485
Fold 4 IBS: 0.29522461192319094
Fold 5 IBS: 0.2096137586672045
[I 2024-04-18 14:56:17,994] Trial 24 finished with value: 0.23349070447853873 and parameters: {'l1_ratio': 0.19621932764719313}. Best is trial 24 with value: 0.23349070447853873.

Fold 1 IBS: 0.2581741896656467
Fold 2 IBS: 0.23423392261218143
Fold 3 IBS: 0.17019839315276927
Fold 4 IBS: 0.29521831555599
Fold 5 IBS: 0.20960746005873962
[I 2024-04-18 14:56:18,726] Trial 25 finished with value: 0.2334864562090654 and parameters: {'l1_ratio': 0.1947967380354304}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2581804446131643
Fold 2 IBS: 0.26312711872028444
Fold 3 IBS: 0.17016174202858292
Fold 4 IBS: 0.2952515096149463
Fold 5 IBS: 0.20957188290681883
[I 2024-04-18 14:56:19,653] Trial 26 finished with value: 0.23925853957675933 and parameters: {'l1_ratio': 0.20309774849254153}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2586569332512195
Fold 2 IBS: 0.26321104962903547
Fold 3 IBS: 0.17023659190799084
Fold 4 IBS: 0.2953030694659617
Fold 5 IBS: 0.20971134084981743
[I 2024-04-18 14:56:20,494] Trial 27 finished with value: 0.23942379702080502 and parameters: {'l1_ratio': 0.3465220894892909}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2583041140659522
Fold 2 IBS: 0.26308955521046357
Fold 3 IBS: 0.1702202373007998
Fold 4 IBS: 0.29524061688729253
Fold 5 IBS: 0.20963986541534058
[I 2024-04-18 14:56:21,181] Trial 28 finished with value: 0.23929887777596975 and parameters: {'l1_ratio': 0.21934403647104328}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2575054596245966
Fold 2 IBS: 0.2331107320975842
Fold 3 IBS: 0.2261887394524967
Fold 4 IBS: 0.25417748457123296
Fold 5 IBS: 0.2235599978739551
[I 2024-04-18 14:56:21,596] Trial 29 finished with value: 0.23890848272397308 and parameters: {'l1_ratio': 0.09015744575196827}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2592757323762763
Fold 2 IBS: 0.263358556407359
Fold 3 IBS: 0.17039257398605911
Fold 4 IBS: 0.2954248037947119
Fold 5 IBS: 0.2099326114599191
[I 2024-04-18 14:56:22,293] Trial 30 finished with value: 0.2396768556048651 and parameters: {'l1_ratio': 0.6348147138790865}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24501441167875285
Fold 2 IBS: 0.23294768670440577
Fold 3 IBS: 0.22653862544473966
Fold 4 IBS: 0.25268991017458164
Fold 5 IBS: 0.224205488281777
[I 2024-04-18 14:56:22,587] Trial 31 finished with value: 0.23627922445685137 and parameters: {'l1_ratio': 0.0761252280999188}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2584647946063864
Fold 2 IBS: 0.26325226568073795
Fold 3 IBS: 0.17020330995037394
Fold 4 IBS: 0.29530137903201886
Fold 5 IBS: 0.20965999382803807
[I 2024-04-18 14:56:23,531] Trial 32 finished with value: 0.23937634861951107 and parameters: {'l1_ratio': 0.2602538967266796}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2578724939296399
Fold 2 IBS: 0.23373140442867688
Fold 3 IBS: 0.22502043844065006
Fold 4 IBS: 0.29520764821782114
Fold 5 IBS: 0.22154037256533254
[I 2024-04-18 14:56:23,991] Trial 33 finished with value: 0.2466744715164241 and parameters: {'l1_ratio': 0.1459177416425643}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2581800460599142
Fold 2 IBS: 0.2631206311661825
Fold 3 IBS: 0.1701697056068703
Fold 4 IBS: 0.29524920783417336
Fold 5 IBS: 0.2095693518433803
[I 2024-04-18 14:56:24,844] Trial 34 finished with value: 0.2392577885021041 and parameters: {'l1_ratio': 0.20253416404215124}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2586638122654988
Fold 2 IBS: 0.26331748912672
Fold 3 IBS: 0.17020944869129045
Fold 4 IBS: 0.2953420202122848
Fold 5 IBS: 0.20975332413564218
[I 2024-04-18 14:56:25,614] Trial 35 finished with value: 0.2394572188862872 and parameters: {'l1_ratio': 0.3641939496945483}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2593000205850041
Fold 2 IBS: 0.26327681686695853
Fold 3 IBS: 0.17037656113679422
Fold 4 IBS: 0.2955227107064083
Fold 5 IBS: 0.21008274982714245
[I 2024-04-18 14:56:26,340] Trial 36 finished with value: 0.23971177182446152 and parameters: {'l1_ratio': 0.8532956215563254}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2588582163360468
Fold 2 IBS: 0.2633361447527151
Fold 3 IBS: 0.17032247056479866
Fold 4 IBS: 0.2953545203206865
Fold 5 IBS: 0.20981219805950027
[I 2024-04-18 14:56:27,010] Trial 37 finished with value: 0.23953671000674945 and parameters: {'l1_ratio': 0.4544709824843894}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2590636675962133
Fold 2 IBS: 0.2633400960030677
Fold 3 IBS: 0.17030047503223564
Fold 4 IBS: 0.2954249013796121
Fold 5 IBS: 0.20988176002124198
[I 2024-04-18 14:56:27,872] Trial 38 finished with value: 0.23960218000647412 and parameters: {'l1_ratio': 0.5638551523074651}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24541595800162058
Fold 2 IBS: 0.23273895391085198
Fold 3 IBS: 0.22701879861452107
Fold 4 IBS: 0.250598583218343
Fold 5 IBS: 0.22512631575124106
[I 2024-04-18 14:56:28,226] Trial 39 finished with value: 0.23617972189931552 and parameters: {'l1_ratio': 0.058421265873771916}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2583305085566678
Fold 2 IBS: 0.2631538446380793
Fold 3 IBS: 0.1702339296886924
Fold 4 IBS: 0.29527364580797366
Fold 5 IBS: 0.20962774365405973
[I 2024-04-18 14:56:28,929] Trial 40 finished with value: 0.23932393446909456 and parameters: {'l1_ratio': 0.25081706392064096}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2456618209847643
Fold 2 IBS: 0.2326225367808612
Fold 3 IBS: 0.22730432583282548
Fold 4 IBS: 0.2493331039306684
Fold 5 IBS: 0.2256945086733135
[I 2024-04-18 14:56:29,245] Trial 41 finished with value: 0.23612325924048658 and parameters: {'l1_ratio': 0.04864377855727854}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.25806442919324785
Fold 2 IBS: 0.23409727529538923
Fold 3 IBS: 0.22442944964922773
Fold 4 IBS: 0.2952383355971998
Fold 5 IBS: 0.2095420454795139
[I 2024-04-18 14:56:29,809] Trial 42 finished with value: 0.2442743070429157 and parameters: {'l1_ratio': 0.18110513751886953}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2471709592155539
Fold 2 IBS: 0.23206231060648824
Fold 3 IBS: 0.22890778151732213
Fold 4 IBS: 0.2422848870584035
Fold 5 IBS: 0.22921740022660034
[I 2024-04-18 14:56:30,135] Trial 43 finished with value: 0.23592866772487361 and parameters: {'l1_ratio': 0.0018849190134430063}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2576948977516574
Fold 2 IBS: 0.23330981632029615
Fold 3 IBS: 0.22578783918017697
Fold 4 IBS: 0.29517621524079757
Fold 5 IBS: 0.2228446840961743
[I 2024-04-18 14:56:30,733] Trial 44 finished with value: 0.24696269051782052 and parameters: {'l1_ratio': 0.1075954803740661}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24714514142196814
Fold 2 IBS: 0.2320700149210683
Fold 3 IBS: 0.2288825411893914
Fold 4 IBS: 0.24239128075295482
Fold 5 IBS: 0.2291569833261593
[I 2024-04-18 14:56:31,085] Trial 45 finished with value: 0.23592919232230836 and parameters: {'l1_ratio': 0.0025318355521207446}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24566451873617254
Fold 2 IBS: 0.23262130453455437
Fold 3 IBS: 0.22730742184577432
Fold 4 IBS: 0.2493192825986509
Fold 5 IBS: 0.22570075825218863
[I 2024-04-18 14:56:31,390] Trial 46 finished with value: 0.23612265719346817 and parameters: {'l1_ratio': 0.048540572572095486}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.25786981403513226
Fold 2 IBS: 0.23369112829150981
Fold 3 IBS: 0.22508947035494425
Fold 4 IBS: 0.29518528983137904
Fold 5 IBS: 0.22165449014901262
[I 2024-04-18 14:56:32,004] Trial 47 finished with value: 0.24669803853239552 and parameters: {'l1_ratio': 0.14216244461773375}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2593000585097057
Fold 2 IBS: 0.26336439795943434
Fold 3 IBS: 0.17041046099830415
Fold 4 IBS: 0.2954849220837216
Fold 5 IBS: 0.2100676956508001
[I 2024-04-18 14:56:32,721] Trial 48 finished with value: 0.2397255070403932 and parameters: {'l1_ratio': 0.7991933234425521}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2453280407450905
Fold 2 IBS: 0.23278262288719045
Fold 3 IBS: 0.2269151044396179
Fold 4 IBS: 0.25105420454226557
Fold 5 IBS: 0.22492386913460186
[I 2024-04-18 14:56:33,169] Trial 49 finished with value: 0.23620076834975326 and parameters: {'l1_ratio': 0.062104731980637026}. Best is trial 25 with value: 0.2334864562090654.

Fold 1 IBS: 0.2588397617421469
Fold 2 IBS: 0.2631556097356599
Fold 3 IBS: 0.1702461973514651
Fold 4 IBS: 0.29536682726214786
Fold 5 IBS: 0.20979634151542792
[I 2024-04-18 14:56:33,685] Trial 50 finished with value: 0.23948094752136956 and parameters: {'l1_ratio': 0.41653985858071785}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24700943918161714
Fold 2 IBS: 0.23211153171381074
Fold 3 IBS: 0.2287483556972372
Fold 4 IBS: 0.24295867311349534
Fold 5 IBS: 0.22883924884787327
[I 2024-04-18 14:56:34,185] Trial 51 finished with value: 0.2359334497108067 and parameters: {'l1_ratio': 0.006012844952470507}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.25776772949132926
Fold 2 IBS: 0.23341820114233583
Fold 3 IBS: 0.22558059996519
Fold 4 IBS: 0.29517332645907624
Fold 5 IBS: 0.22248441822949994
[I 2024-04-18 14:56:34,626] Trial 52 finished with value: 0.24688485505748625 and parameters: {'l1_ratio': 0.11725216969950066}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24720349836184546
Fold 2 IBS: 0.23205267311848418
Fold 3 IBS: 0.22893950672870006
Fold 4 IBS: 0.24215168750377097
Fold 5 IBS: 0.229293549126052
[I 2024-04-18 14:56:34,960] Trial 53 finished with value: 0.23592818296777054 and parameters: {'l1_ratio': 0.001075229365676048}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.25806511189064085
Fold 2 IBS: 0.23410666621182655
Fold 3 IBS: 0.22441508051199738
Fold 4 IBS: 0.29524258807947035
Fold 5 IBS: 0.209546773496333
[I 2024-04-18 14:56:35,625] Trial 54 finished with value: 0.24427524403805365 and parameters: {'l1_ratio': 0.182035855830944}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24620748593524058
Fold 2 IBS: 0.2323917679039056
Fold 3 IBS: 0.2279138577381615
Fold 4 IBS: 0.24661039201731955
Fold 5 IBS: 0.22696366099437518
[I 2024-04-18 14:56:35,892] Trial 55 finished with value: 0.2360174329178005 and parameters: {'l1_ratio': 0.02938428666851548}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2590571667763178
Fold 2 IBS: 0.2631831145189391
Fold 3 IBS: 0.17036996821696263
Fold 4 IBS: 0.295449340421704
Fold 5 IBS: 0.20987254280754203
[I 2024-04-18 14:56:36,670] Trial 56 finished with value: 0.23958642654829312 and parameters: {'l1_ratio': 0.5225566990974848}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2586279318211083
Fold 2 IBS: 0.2632893522043685
Fold 3 IBS: 0.1702367690598675
Fold 4 IBS: 0.2953229131546113
Fold 5 IBS: 0.2096951840663908
[I 2024-04-18 14:56:37,428] Trial 57 finished with value: 0.23943443006126927 and parameters: {'l1_ratio': 0.29294935679922524}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2574582062660456
Fold 2 IBS: 0.23304661683052016
Fold 3 IBS: 0.22632387640883322
Fold 4 IBS: 0.25360714634352743
Fold 5 IBS: 0.22380687704752514
[I 2024-04-18 14:56:37,838] Trial 58 finished with value: 0.23884854457929033 and parameters: {'l1_ratio': 0.08461517033810452}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24577923602450374
Fold 2 IBS: 0.2325697809986212
Fold 3 IBS: 0.22743832272047246
Fold 4 IBS: 0.24873449128626834
Fold 5 IBS: 0.22596677854073466
[I 2024-04-18 14:56:38,137] Trial 59 finished with value: 0.2360977219141201 and parameters: {'l1_ratio': 0.04422974988756807}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24714535572117732
Fold 2 IBS: 0.23206995076094003
Fold 3 IBS: 0.22888275094473667
Fold 4 IBS: 0.2423903950683377
Fold 5 IBS: 0.22915748480391185
[I 2024-04-18 14:56:38,422] Trial 60 finished with value: 0.2359291874598207 and parameters: {'l1_ratio': 0.002526449432011457}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24717881487169782
Fold 2 IBS: 0.23205997652430213
Fold 3 IBS: 0.2289154494575896
Fold 4 IBS: 0.2422526384732057
Fold 5 IBS: 0.2292357839043396
[I 2024-04-18 14:56:38,786] Trial 61 finished with value: 0.23592853264622696 and parameters: {'l1_ratio': 0.001688868406892038}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.25777456207280486
Fold 2 IBS: 0.2334849211914573
Fold 3 IBS: 0.22545660988938254
Fold 4 IBS: 0.29513828336153736
Fold 5 IBS: 0.22227180863088633
[I 2024-04-18 14:56:39,252] Trial 62 finished with value: 0.24682523702921372 and parameters: {'l1_ratio': 0.12325998169278211}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24724263667876553
Fold 2 IBS: 0.23204118721148972
Fold 3 IBS: 0.22897753920191508
Fold 4 IBS: 0.2419928003082502
Fold 5 IBS: 0.22938514602530122
[I 2024-04-18 14:56:39,694] Trial 63 finished with value: 0.23592786188514436 and parameters: {'l1_ratio': 0.0001095683325790717}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24580281735925577
Fold 2 IBS: 0.23255939890762214
Fold 3 IBS: 0.22746504802087728
Fold 4 IBS: 0.24861501728513483
Fold 5 IBS: 0.2260215234809037
[I 2024-04-18 14:56:39,986] Trial 64 finished with value: 0.23609276101075874 and parameters: {'l1_ratio': 0.04336209464697771}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24496955761826142
Fold 2 IBS: 0.23297252621885917
Fold 3 IBS: 0.22648397241449436
Fold 4 IBS: 0.2529245440766507
Fold 5 IBS: 0.22410329555909628
[I 2024-04-18 14:56:40,216] Trial 65 finished with value: 0.23629077917747238 and parameters: {'l1_ratio': 0.07825022735560312}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.25832470230790905
Fold 2 IBS: 0.2632753193929414
Fold 3 IBS: 0.17014595374563993
Fold 4 IBS: 0.2952374634126515
Fold 5 IBS: 0.20965647928294437
[I 2024-04-18 14:56:41,039] Trial 66 finished with value: 0.23932798362841723 and parameters: {'l1_ratio': 0.2395995188877933}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2579691973499271
Fold 2 IBS: 0.23393967961754028
Fold 3 IBS: 0.22467636216325282
Fold 4 IBS: 0.2951615087488376
Fold 5 IBS: 0.20954005948456939
[I 2024-04-18 14:56:41,646] Trial 67 finished with value: 0.24425736147282545 and parameters: {'l1_ratio': 0.16569971745336035}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2576309924804744
Fold 2 IBS: 0.2332425221328016
Fold 3 IBS: 0.22592031322290856
Fold 4 IBS: 0.2552929824240862
Fold 5 IBS: 0.22307830597828515
[I 2024-04-18 14:56:41,928] Trial 68 finished with value: 0.2390330232477112 and parameters: {'l1_ratio': 0.10165988450733253}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24585325588793078
Fold 2 IBS: 0.23253742744188402
Fold 3 IBS: 0.22752200107144235
Fold 4 IBS: 0.2483603808352044
Fold 5 IBS: 0.2261386843871377
[I 2024-04-18 14:56:42,167] Trial 69 finished with value: 0.23608234992471985 and parameters: {'l1_ratio': 0.04152685755182929}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2577853492923015
Fold 2 IBS: 0.23354339968531593
Fold 3 IBS: 0.2253500828444279
Fold 4 IBS: 0.29517571275928367
Fold 5 IBS: 0.2220908418766383
[I 2024-04-18 14:56:42,599] Trial 70 finished with value: 0.24678907729159344 and parameters: {'l1_ratio': 0.12856771291547148}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24671317123963757
Fold 2 IBS: 0.23220775403458754
Fold 3 IBS: 0.22844851284815765
Fold 4 IBS: 0.2442512540129185
Fold 5 IBS: 0.2281456989793243
[I 2024-04-18 14:56:42,848] Trial 71 finished with value: 0.23595327822292508 and parameters: {'l1_ratio': 0.014054723613335375}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24715538482106636
Fold 2 IBS: 0.2320669520524302
Fold 3 IBS: 0.228892562722732
Fold 4 IBS: 0.24234899351635072
Fold 5 IBS: 0.22918095390049126
[I 2024-04-18 14:56:43,059] Trial 72 finished with value: 0.2359289694026141 and parameters: {'l1_ratio': 0.0022746897051719155}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24508336609706044
Fold 2 IBS: 0.23291011477294957
Fold 3 IBS: 0.22662225749955509
Fold 4 IBS: 0.2523293770407191
Fold 5 IBS: 0.22436287499677243
[I 2024-04-18 14:56:43,370] Trial 73 finished with value: 0.23626159808141134 and parameters: {'l1_ratio': 0.07291898183365575}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24716783890128394
Fold 2 IBS: 0.23206323902690706
Fold 3 IBS: 0.22890473421132906
Fold 4 IBS: 0.2422977124869007
Fold 5 IBS: 0.22921009817578195
[I 2024-04-18 14:56:43,713] Trial 74 finished with value: 0.23592872456044053 and parameters: {'l1_ratio': 0.00196289332002613}. Best is trial 25 with value: 0.2334864562090654.

Fold 1 IBS: 0.24584401855708746
Fold 2 IBS: 0.2325414275047241
Fold 3 IBS: 0.22751159212227245
Fold 4 IBS: 0.24840692200101858
Fold 5 IBS: 0.22611722092615838
[I 2024-04-18 14:56:44,114] Trial 75 finished with value: 0.23608423622225222 and parameters: {'l1_ratio': 0.041860881790211954}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2575693918073802
Fold 2 IBS: 0.23318555218134743
Fold 3 IBS: 0.2260348499439707
Fold 4 IBS: 0.2548199486345508
Fold 5 IBS: 0.22328245681576514
[I 2024-04-18 14:56:44,450] Trial 76 finished with value: 0.2389784398766029 and parameters: {'l1_ratio': 0.09666857918599614}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24621378571183025
Fold 2 IBS: 0.2323893088410591
Fold 3 IBS: 0.2279206974111101
Fold 4 IBS: 0.24657993346599297
Fold 5 IBS: 0.22697836138616592
[I 2024-04-18 14:56:44,694] Trial 77 finished with value: 0.23601641736323167 and parameters: {'l1_ratio': 0.029179515489863375}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24515926720385264
Fold 2 IBS: 0.23286960436936704
Fold 3 IBS: 0.226713763555825
Fold 4 IBS: 0.25193294789651705
Fold 5 IBS: 0.22453649954805538
[I 2024-04-18 14:56:44,930] Trial 78 finished with value: 0.23624241651472344 and parameters: {'l1_ratio': 0.06947225601081389}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2586566240198199
Fold 2 IBS: 0.2632052452857438
Fold 3 IBS: 0.17023856085957753
Fold 4 IBS: 0.29530095238237863
Fold 5 IBS: 0.2097090611640873
[I 2024-04-18 14:56:45,536] Trial 79 finished with value: 0.23942208874232143 and parameters: {'l1_ratio': 0.3456077688118052}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2583012676142828
Fold 2 IBS: 0.2632787485709589
Fold 3 IBS: 0.1702337305641015
Fold 4 IBS: 0.29522665907116297
Fold 5 IBS: 0.20963524590866928
[I 2024-04-18 14:56:46,202] Trial 80 finished with value: 0.2393351303458351 and parameters: {'l1_ratio': 0.21575119575453156}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24716664157501697
Fold 2 IBS: 0.23206359547797753
Fold 3 IBS: 0.2289035646651779
Fold 4 IBS: 0.24230263628495638
Fold 5 IBS: 0.22920729624327144
[I 2024-04-18 14:56:46,549] Trial 81 finished with value: 0.23592874684928006 and parameters: {'l1_ratio': 0.001992828994379018}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24622656057882436
Fold 2 IBS: 0.2323843358491779
Fold 3 IBS: 0.22793455320156988
Fold 4 IBS: 0.2465182452819206
Fold 5 IBS: 0.22700817382612848
[I 2024-04-18 14:56:46,934] Trial 82 finished with value: 0.23601437374752426 and parameters: {'l1_ratio': 0.028765413863974496}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24720726923505193
Fold 2 IBS: 0.2320515614547704
Fold 3 IBS: 0.22894317707932135
Fold 4 IBS: 0.24213631596335491
Fold 5 IBS: 0.22930237403701298
[I 2024-04-18 14:56:47,247] Trial 83 finished with value: 0.2359281395539023 and parameters: {'l1_ratio': 0.0009818005093678698}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24535119370858682
Fold 2 IBS: 0.23277101541970105
Fold 3 IBS: 0.22694249238245365
Fold 4 IBS: 0.2509340503616924
Fold 5 IBS: 0.22497714237202
[I 2024-04-18 14:56:47,535] Trial 84 finished with value: 0.2361951788488908 and parameters: {'l1_ratio': 0.06112470356187916}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2590662457599128
Fold 2 IBS: 0.2632838803135698
Fold 3 IBS: 0.17027929187063326
Fold 4 IBS: 0.29540046182052804
Fold 5 IBS: 0.2099473350909589
[I 2024-04-18 14:56:48,224] Trial 85 finished with value: 0.2395954429711206 and parameters: {'l1_ratio': 0.6114164712527408}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2579467906434232
Fold 2 IBS: 0.23375200627898624
Fold 3 IBS: 0.22498545012967805
Fold 4 IBS: 0.29521869674395795
Fold 5 IBS: 0.22148276041779444
[I 2024-04-18 14:56:48,502] Trial 86 finished with value: 0.24667714084276798 and parameters: {'l1_ratio': 0.14784709080509192}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24625488688190167
Fold 2 IBS: 0.23237337350509504
Fold 3 IBS: 0.22796520990352226
Fold 4 IBS: 0.24638182997503408
Fold 5 IBS: 0.2270742902889714
[I 2024-04-18 14:56:49,002] Trial 87 finished with value: 0.2360099181109049 and parameters: {'l1_ratio': 0.02785261554877598}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2576912400169719
Fold 2 IBS: 0.2332778182184736
Fold 3 IBS: 0.2258504564237316
Fold 4 IBS: 0.25557924208296035
Fold 5 IBS: 0.22295478158652415
[I 2024-04-18 14:56:49,373] Trial 88 finished with value: 0.2390707076657323 and parameters: {'l1_ratio': 0.10476761307303795}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2453770685135699
Fold 2 IBS: 0.2327581344596889
Fold 3 IBS: 0.22697303238441535
Fold 4 IBS: 0.2507999077373787
Fold 5 IBS: 0.2250367134213846
[I 2024-04-18 14:56:49,604] Trial 89 finished with value: 0.2361889713032875 and parameters: {'l1_ratio': 0.060037961746263864}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.25806341181098436
Fold 2 IBS: 0.23408357480215167
Fold 3 IBS: 0.22445048077493784
Fold 4 IBS: 0.29523207893721365
Fold 5 IBS: 0.20953508149024236
[I 2024-04-18 14:56:50,241] Trial 90 finished with value: 0.24427292556310598 and parameters: {'l1_ratio': 0.17974993883420748}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24720085339965214
Fold 2 IBS: 0.23205345350290732
Fold 3 IBS: 0.22893693150757327
Fold 4 IBS: 0.24216247741439448
Fold 5 IBS: 0.22928735919270862
[I 2024-04-18 14:56:50,556] Trial 91 finished with value: 0.23592821500344718 and parameters: {'l1_ratio': 0.0011408120158167287}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.2465413587080954
Fold 2 IBS: 0.23226733887489562
Fold 3 IBS: 0.22827011331369979
Fold 4 IBS: 0.2450323667252596
Fold 5 IBS: 0.22774371860135448
[I 2024-04-18 14:56:50,929] Trial 92 finished with value: 0.23597097924466098 and parameters: {'l1_ratio': 0.019022323287451147}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.25745710257879606
Fold 2 IBS: 0.23303268265231353
Fold 3 IBS: 0.22635365790131748
Fold 4 IBS: 0.25348071872473327
Fold 5 IBS: 0.22386169029119862
[I 2024-04-18 14:56:51,369] Trial 93 finished with value: 0.2388371704296718 and parameters: {'l1_ratio': 0.08341497376742937}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24616952502455516
Fold 2 IBS: 0.23240667970453416
Fold 3 IBS: 0.22787254775057164
Fold 4 IBS: 0.24679445012379184
Fold 5 IBS: 0.22687509824065333
[I 2024-04-18 14:56:51,666] Trial 94 finished with value: 0.23602366016882126 and parameters: {'l1_ratio': 0.03062610350332001}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24716530749569518
Fold 2 IBS: 0.23206399277052694
Fold 3 IBS: 0.2289022613856028
Fold 4 IBS: 0.2423081240416975
Fold 5 IBS: 0.22920417429274312
[I 2024-04-18 14:56:51,960] Trial 95 finished with value: 0.2359287719972531 and parameters: {'l1_ratio': 0.002026193844250578}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24541085033299498
Fold 2 IBS: 0.23274146082590866
Fold 3 IBS: 0.2270127970467499
Fold 4 IBS: 0.25062500405613364
Fold 5 IBS: 0.2251145429923477
[I 2024-04-18 14:56:52,260] Trial 96 finished with value: 0.236180931050827 and parameters: {'l1_ratio': 0.05863246762890938}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.25886039220855744
Fold 2 IBS: 0.2632453803333324
Fold 3 IBS: 0.17027950349503823
Fold 4 IBS: 0.2953966301957461
Fold 5 IBS: 0.20980843275330252
[I 2024-04-18 14:56:52,895] Trial 97 finished with value: 0.2395180677971953 and parameters: {'l1_ratio': 0.48367344869866996}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.24633448197963384
Fold 2 IBS: 0.23234304003465076
Fold 3 IBS: 0.22805086356088017
Fold 4 IBS: 0.24600128934525153
Fold 5 IBS: 0.2272601560987221
[I 2024-04-18 14:56:53,342] Trial 98 finished with value: 0.23599796620382768 and parameters: {'l1_ratio': 0.02532697337919661}. Best is trial 25 with value: 0.2334864562090654.
Fold 1 IBS: 0.25847169827304656
Fold 2 IBS: 0.2631084395294338
Fold 3 IBS: 0.17017383309403655
Fold 4 IBS: 0.2952592192183339
Fold 5 IBS: 0.20961210639565234
[I 2024-04-18 14:56:54,055] Trial 99 finished with value: 0.23932505930210066 and parameters: {'l1_ratio': 0.2699934528985048}. Best is trial 25 with value: 0.2334864562090654.


* Best trial for IBS:
 FrozenTrial(number=25, state=TrialState.COMPLETE, values=[0.2334864562090654], datetime_start=datetime.datetime(2024, 4, 18, 14, 56, 18, 26185), datetime_complete=datetime.datetime(2024, 4, 18, 14, 56, 18, 726176), params={'l1_ratio': 0.1947967380354304}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=25, value=None)


* Best Score for IBS:
 0.2334864562090654

In [51]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [52]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.638
train_ibs:  0.233

#### Test

In [53]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [54]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.22692876841884668)

test_cindex : 0.524

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.1947967380354304)

test_ibs:  0.235

In [55]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [56]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 14:56:54,453] A new study created in memory with name: no-name-92426e07-506a-49c7-957b-aac296c21a18

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6201550387596899
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.6673003802281369
Fold 5 C-index: 0.6072961373390557
[I 2024-04-18 14:57:01,043] Trial 0 finished with value: 0.6187977301006736 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6187977301006736.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6094420600858369
[I 2024-04-18 14:57:05,171] Trial 1 finished with value: 0.6237488136710192 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6266094420600858
[I 2024-04-18 14:57:07,832] Trial 2 finished with value: 0.6229733658988998 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 14:57:09,045] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 14:57:10,719] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6137339055793991
[I 2024-04-18 14:57:16,798] Trial 5 finished with value: 0.6218270216571679 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6094420600858369
[I 2024-04-18 14:57:22,769] Trial 6 finished with value: 0.5995723609793941 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 14:57:26,553] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5214592274678111
[I 2024-04-18 14:57:35,480] Trial 8 finished with value: 0.5042918454935622 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:57:40,142] Trial 9 finished with value: 0.6124941831608247 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 14:57:40,914] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.6051502145922747
[I 2024-04-18 14:57:43,762] Trial 11 finished with value: 0.6129332218211435 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.9250608990121825, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1579906038170908, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:57:46,976] Trial 12 finished with value: 0.6382167482744471 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.8206827027986038, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13254323337687263, 'warm_start': False}. Best is trial 12 with value: 0.6382167482744471.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6201550387596899
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6051502145922747
[I 2024-04-18 14:57:49,229] Trial 13 finished with value: 0.6155259268666031 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 114, 'oob_score': False, 'max_samples': 0.765021860726683, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12214947430735827, 'warm_start': False}. Best is trial 12 with value: 0.6382167482744471.
Fold 1 C-index: 0.5597609561752988
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.8021276595744681
Fold 4 C-index: 0.6406844106463878
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:57:49,889] Trial 14 finished with value: 0.661274162121231 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 24, 'oob_score': True, 'max_samples': 0.7873021337102564, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11396669613812715, 'warm_start': True}. Best is trial 14 with value: 0.661274162121231.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.687984496124031
Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:57:50,511] Trial 15 finished with value: 0.6815364844139735 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 32, 'oob_score': True, 'max_samples': 0.8219485202814404, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20648604556011108, 'warm_start': True}. Best is trial 15 with value: 0.6815364844139735.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 14:57:51,224] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 4, 'oob_score': True, 'max_samples': 0.44827686549014745, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.37909912926450273, 'warm_start': True}. Best is trial 15 with value: 0.6815364844139735.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6759656652360515
[I 2024-04-18 14:57:52,323] Trial 17 finished with value: 0.6895409260222489 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.9817072304699028, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2138706147057923, 'warm_start': True}. Best is trial 17 with value: 0.6895409260222489.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6824034334763949
[I 2024-04-18 14:57:53,647] Trial 18 finished with value: 0.6896987117465925 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 4, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2171200473956938, 'warm_start': True}. Best is trial 18 with value: 0.6896987117465925.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6647286821705426
Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:57:54,585] Trial 19 finished with value: 0.6732099075929641 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 101, 'oob_score': True, 'max_samples': 0.9946585698860816, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.42883326307517006, 'warm_start': True}. Best is trial 18 with value: 0.6896987117465925.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:57:55,731] Trial 20 finished with value: 0.6878047367558022 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 106, 'oob_score': True, 'max_samples': 0.9966629158836573, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2545762438232687, 'warm_start': True}. Best is trial 18 with value: 0.6896987117465925.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6695278969957081
[I 2024-04-18 14:57:59,447] Trial 21 finished with value: 0.6895651366973921 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 103, 'oob_score': True, 'max_samples': 0.9639969186184459, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2437877730150368, 'warm_start': True}. Best is trial 18 with value: 0.6896987117465925.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6609442060085837
[I 2024-04-18 14:58:02,092] Trial 22 finished with value: 0.6910745957879284 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 72, 'oob_score': True, 'max_samples': 0.8676148902984393, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22395371756309795, 'warm_start': True}. Best is trial 22 with value: 0.6910745957879284.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:58:04,787] Trial 23 finished with value: 0.6847876876921578 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 144, 'oob_score': True, 'max_samples': 0.8696699974194458, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27355128284391594, 'warm_start': True}. Best is trial 22 with value: 0.6910745957879284.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6952789699570815
[I 2024-04-18 14:58:05,984] Trial 24 finished with value: 0.7028777296239799 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 71, 'oob_score': True, 'max_samples': 0.8666873301180216, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18247394618931245, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:58:06,946] Trial 25 finished with value: 0.6862431761238705 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 59, 'oob_score': True, 'max_samples': 0.694473183989708, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17899438960638397, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:58:09,040] Trial 26 finished with value: 0.6908180514604075 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.8603105664937221, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08974480297156207, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:58:11,060] Trial 27 finished with value: 0.690879607810116 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 9, 'n_estimators': 211, 'oob_score': True, 'max_samples': 0.8480603313960683, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07826883989461175, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.6824034334763949
[I 2024-04-18 14:58:12,459] Trial 28 finished with value: 0.6834080957400726 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.5100409687730639, 'max_features': None, 'min_weight_fraction_leaf': 0.08406288592069039, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.703862660944206
[I 2024-04-18 14:58:17,043] Trial 29 finished with value: 0.6995571701409032 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': None, 'min_weight_fraction_leaf': 0.06357526719965571, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6824034334763949
[I 2024-04-18 14:58:20,374] Trial 30 finished with value: 0.6883010388853158 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.6919164029113454, 'max_features': None, 'min_weight_fraction_leaf': 0.18416154592106396, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6952789699570815
[I 2024-04-18 14:58:24,265] Trial 31 finished with value: 0.6991838537239718 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 15, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.7425407774406056, 'max_features': None, 'min_weight_fraction_leaf': 0.06755614270828253, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7510729613733905
[I 2024-04-18 14:58:29,143] Trial 32 finished with value: 0.71347233498625 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 482, 'oob_score': True, 'max_samples': 0.7213418356032232, 'max_features': None, 'min_weight_fraction_leaf': 0.005268431893676387, 'warm_start': True}. Best is trial 32 with value: 0.71347233498625.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7553648068669528
[I 2024-04-18 14:58:33,145] Trial 33 finished with value: 0.7143454416096479 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 497, 'oob_score': True, 'max_samples': 0.7317060450615778, 'max_features': None, 'min_weight_fraction_leaf': 0.00636445969534791, 'warm_start': True}. Best is trial 33 with value: 0.7143454416096479.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7253218884120172
[I 2024-04-18 14:58:37,669] Trial 34 finished with value: 0.7093070296808943 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 499, 'oob_score': True, 'max_samples': 0.6498478551106737, 'max_features': None, 'min_weight_fraction_leaf': 0.0026718173907039787, 'warm_start': True}. Best is trial 33 with value: 0.7143454416096479.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7682403433476395
[I 2024-04-18 14:58:41,374] Trial 35 finished with value: 0.7184092367318795 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.5526064129655602, 'max_features': None, 'min_weight_fraction_leaf': 0.003679699406838821, 'warm_start': True}. Best is trial 35 with value: 0.7184092367318795.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7725321888412017
[I 2024-04-18 14:58:45,488] Trial 36 finished with value: 0.7185651249826217 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 460, 'oob_score': True, 'max_samples': 0.5549344736260913, 'max_features': None, 'min_weight_fraction_leaf': 0.00052334394504433, 'warm_start': True}. Best is trial 36 with value: 0.7185651249826217.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7811158798283262
[I 2024-04-18 14:58:49,619] Trial 37 finished with value: 0.7202887446059156 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.5814176605200219, 'max_features': None, 'min_weight_fraction_leaf': 0.0015943254569678817, 'warm_start': True}. Best is trial 37 with value: 0.7202887446059156.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.776824034334764
[I 2024-04-18 14:58:53,461] Trial 38 finished with value: 0.7226139021582083 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.5457909141571613, 'max_features': None, 'min_weight_fraction_leaf': 0.03880080650528065, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7682403433476395
[I 2024-04-18 14:58:56,800] Trial 39 finished with value: 0.7201288515882028 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 364, 'oob_score': True, 'max_samples': 0.5368476716627143, 'max_features': None, 'min_weight_fraction_leaf': 0.038081261852135145, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7553648068669528
[I 2024-04-18 14:58:59,914] Trial 40 finished with value: 0.716032831744537 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 358, 'oob_score': True, 'max_samples': 0.40952146090981767, 'max_features': None, 'min_weight_fraction_leaf': 0.04061975291171849, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7424892703862661
[I 2024-04-18 14:59:03,365] Trial 41 finished with value: 0.712624555224156 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.551415472983159, 'max_features': None, 'min_weight_fraction_leaf': 0.03862016225559219, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7682403433476395
[I 2024-04-18 14:59:06,496] Trial 42 finished with value: 0.7192603005616668 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 443, 'oob_score': True, 'max_samples': 0.5470571389584655, 'max_features': None, 'min_weight_fraction_leaf': 0.040547589426843215, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7424892703862661
[I 2024-04-18 14:59:08,655] Trial 43 finished with value: 0.7117951103449232 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 323, 'oob_score': True, 'max_samples': 0.39343893459960555, 'max_features': None, 'min_weight_fraction_leaf': 0.037197106766703916, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7124463519313304
[I 2024-04-18 14:59:12,588] Trial 44 finished with value: 0.7068156485149109 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 426, 'oob_score': True, 'max_samples': 0.5037446232500291, 'max_features': None, 'min_weight_fraction_leaf': 0.10143753014282131, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7939914163090128
[I 2024-04-18 14:59:14,528] Trial 45 finished with value: 0.7377598119861252 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 383, 'oob_score': False, 'max_samples': 0.6224391250822676, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.051293485724493715, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.

Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6180257510729614
[I 2024-04-18 14:59:20,527] Trial 46 finished with value: 0.6313385118971416 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 397, 'oob_score': False, 'max_samples': 0.6010576387757552, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14147922592542847, 'warm_start': False}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7682403433476395
[I 2024-04-18 14:59:22,220] Trial 47 finished with value: 0.7280606226030029 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.5032144797599873, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05574216570821283, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6266094420600858
[I 2024-04-18 14:59:27,268] Trial 48 finished with value: 0.6202653504726628 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 335, 'oob_score': False, 'max_samples': 0.6362652522405036, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.058749933389336956, 'warm_start': False}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6609442060085837
[I 2024-04-18 14:59:28,719] Trial 49 finished with value: 0.6868378352014417 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 378, 'oob_score': False, 'max_samples': 0.32446222096768196, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09999547019922148, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7510729613733905
[I 2024-04-18 14:59:30,070] Trial 50 finished with value: 0.7215489646378563 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 293, 'oob_score': False, 'max_samples': 0.49077652431354474, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.022511395342881692, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7424892703862661
[I 2024-04-18 14:59:31,333] Trial 51 finished with value: 0.7197673695887684 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.4799716025166624, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023356353978444662, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7424892703862661
[I 2024-04-18 14:59:32,634] Trial 52 finished with value: 0.7119295230662075 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 308, 'oob_score': False, 'max_samples': 0.4430397101533895, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05546859752674148, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.776824034334764
[I 2024-04-18 14:59:34,168] Trial 53 finished with value: 0.732052822868799 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.37699411471825023, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03181683271115842, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7381974248927039
[I 2024-04-18 14:59:35,184] Trial 54 finished with value: 0.7103906994788739 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 248, 'oob_score': False, 'max_samples': 0.35484298072023907, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02439879662210201, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 14:59:36,523] Trial 55 finished with value: 0.6658561927484276 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 340, 'oob_score': False, 'max_samples': 0.2601632974909122, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11812720872048674, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6137339055793991
[I 2024-04-18 14:59:40,986] Trial 56 finished with value: 0.6329785159428548 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 293, 'oob_score': False, 'max_samples': 0.5939163004492594, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07594467100316221, 'warm_start': False}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.721030042918455
[I 2024-04-18 14:59:42,519] Trial 57 finished with value: 0.7077567855050916 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 413, 'oob_score': False, 'max_samples': 0.417605389677477, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.022567886933550586, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7124463519313304
[I 2024-04-18 14:59:44,038] Trial 58 finished with value: 0.7084014179141025 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.36734352262627257, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0555217518283616, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 14:59:45,345] Trial 59 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.4820175814461636, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3544232433893524, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 14:59:51,854] Trial 60 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.13319246988341354, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1478483729810709, 'warm_start': False}. Best is trial 45 with value: 0.7377598119861252.

Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6695278969957081
[I 2024-04-18 14:59:53,426] Trial 61 finished with value: 0.694601867113741 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 365, 'oob_score': False, 'max_samples': 0.5242841615310458, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04056647502046609, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7725321888412017
[I 2024-04-18 14:59:55,013] Trial 62 finished with value: 0.7295239835677936 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 349, 'oob_score': False, 'max_samples': 0.5989938697881527, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02024218059654313, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7811158798283262
[I 2024-04-18 14:59:56,610] Trial 63 finished with value: 0.7265215450419994 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.5800886465458086, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01592409160248775, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7124463519313304
[I 2024-04-18 14:59:57,996] Trial 64 finished with value: 0.7057723563934031 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 352, 'oob_score': False, 'max_samples': 0.6306540419871571, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10134985371919171, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7982832618025751
[I 2024-04-18 14:59:59,053] Trial 65 finished with value: 0.744372793830748 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.48772656128152925, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02153233090954807, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.776824034334764
[I 2024-04-18 15:00:00,743] Trial 66 finished with value: 0.7304619470428545 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 384, 'oob_score': False, 'max_samples': 0.6592301391256026, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07213010958136569, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7725321888412017
[I 2024-04-18 15:00:02,104] Trial 67 finished with value: 0.7303245206618084 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.658332776835216, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0786225535507252, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7854077253218884
[I 2024-04-18 15:00:03,443] Trial 68 finished with value: 0.7350033461568455 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 324, 'oob_score': False, 'max_samples': 0.782951240419168, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07188437817902898, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.721030042918455
[I 2024-04-18 15:00:04,603] Trial 69 finished with value: 0.7114104838920958 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.7726300856584892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12841953214236906, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7253218884120172
[I 2024-04-18 15:00:05,825] Trial 70 finished with value: 0.7184151776246746 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.8023071029509282, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.088091229553206, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7682403433476395
[I 2024-04-18 15:00:06,922] Trial 71 finished with value: 0.7295204026438793 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.6597094598339149, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07494346044667374, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7854077253218884
[I 2024-04-18 15:00:08,270] Trial 72 finished with value: 0.7297450090921587 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.6507521187970767, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06813374716595723, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7896995708154506
[I 2024-04-18 15:00:09,788] Trial 73 finished with value: 0.7321026717878453 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.6812499544043293, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07039581398771254, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7467811158798283
[I 2024-04-18 15:00:10,790] Trial 74 finished with value: 0.7171593761887324 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 255, 'oob_score': False, 'max_samples': 0.6687532229099372, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0936898450129986, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7939914163090128
[I 2024-04-18 15:00:12,101] Trial 75 finished with value: 0.7369777367618064 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.706380565345059, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06787811748332337, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.

Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7339055793991416
[I 2024-04-18 15:00:13,338] Trial 76 finished with value: 0.7179195356062753 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.7085639969790332, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11414897284280093, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7381974248927039
[I 2024-04-18 15:00:14,647] Trial 77 finished with value: 0.7216353576071407 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.7541985504150174, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07972201398799938, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6763565891472868
Fold 3 C-index: 0.7851063829787234
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.6416309012875536
[I 2024-04-18 15:00:15,798] Trial 78 finished with value: 0.6803721565923366 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.7127152729708048, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.29205538265571684, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:00:17,487] Trial 79 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.6228120642786297, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.41958947955878745, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.6137339055793991
[I 2024-04-18 15:00:22,041] Trial 80 finished with value: 0.6172257451314318 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6720088970814889, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10386652069615948, 'warm_start': False}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7896995708154506
[I 2024-04-18 15:00:23,280] Trial 81 finished with value: 0.7320120642318223 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 297, 'oob_score': False, 'max_samples': 0.7369273672792999, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06782159792325793, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7811158798283262
[I 2024-04-18 15:00:24,312] Trial 82 finished with value: 0.730229494509787 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.7952406802041782, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05094662429126583, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6738197424892703
[I 2024-04-18 15:00:25,609] Trial 83 finished with value: 0.6953812091002576 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 326, 'oob_score': False, 'max_samples': 0.7368333705955264, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1694628542086393, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7939914163090128
[I 2024-04-18 15:00:26,654] Trial 84 finished with value: 0.7392553812380884 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.8406178075999796, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06813421705074371, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.776824034334764
[I 2024-04-18 15:00:27,897] Trial 85 finished with value: 0.7302622700611123 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 293, 'oob_score': False, 'max_samples': 0.8306089170227028, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06578521283153765, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7939914163090128
[I 2024-04-18 15:00:29,115] Trial 86 finished with value: 0.7405771840680274 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 270, 'oob_score': False, 'max_samples': 0.9236490757653891, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04839348178619321, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7939914163090128
[I 2024-04-18 15:00:30,396] Trial 87 finished with value: 0.7440030583377307 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 276, 'oob_score': False, 'max_samples': 0.9426505941387808, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0458571199390998, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:00:31,227] Trial 88 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 270, 'oob_score': False, 'max_samples': 0.9045286625545784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4978507265200673, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.776824034334764
[I 2024-04-18 15:00:32,144] Trial 89 finished with value: 0.7387263199915111 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 210, 'oob_score': False, 'max_samples': 0.9605688356486618, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04938248319171276, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7854077253218884
[I 2024-04-18 15:00:32,997] Trial 90 finished with value: 0.7357164327756954 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 191, 'oob_score': False, 'max_samples': 0.9509590620645423, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04691631766264469, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7854077253218884
[I 2024-04-18 15:00:33,830] Trial 91 finished with value: 0.7350355708782796 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 186, 'oob_score': False, 'max_samples': 0.9470927951745665, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04725901659642619, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.721030042918455
[I 2024-04-18 15:00:34,768] Trial 92 finished with value: 0.7237357652900573 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 199, 'oob_score': False, 'max_samples': 0.9504866379214324, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.053094099292765956, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.776824034334764
[I 2024-04-18 15:00:35,719] Trial 93 finished with value: 0.7350688972594961 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 198, 'oob_score': False, 'max_samples': 0.8969936953129258, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04367753331224559, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7017167381974249
[I 2024-04-18 15:00:36,629] Trial 94 finished with value: 0.7024901375378925 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 173, 'oob_score': False, 'max_samples': 0.9151949478759466, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012193068752189541, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7725321888412017
[I 2024-04-18 15:00:37,715] Trial 95 finished with value: 0.7365314105381744 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 180, 'oob_score': False, 'max_samples': 0.8802646337989153, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04987709925035067, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8154506437768241
[I 2024-04-18 15:00:38,757] Trial 96 finished with value: 0.7521018842180724 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.8757809738336038, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.026360410334294093, 'warm_start': True}. Best is trial 96 with value: 0.7521018842180724.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8111587982832618
[I 2024-04-18 15:00:39,693] Trial 97 finished with value: 0.7529735758912052 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 168, 'oob_score': False, 'max_samples': 0.9745319440587786, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02941204455344467, 'warm_start': True}. Best is trial 97 with value: 0.7529735758912052.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.5968992248062015
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6223175965665236
[I 2024-04-18 15:00:42,767] Trial 98 finished with value: 0.6180562707587932 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 163, 'oob_score': False, 'max_samples': 0.9694692468947707, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.027994915902686063, 'warm_start': False}. Best is trial 97 with value: 0.7529735758912052.

[I 2024-04-18 15:00:44,214] A new study created in memory with name: no-name-628981f8-5b03-4478-935f-4a6d61ae02b3

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8283261802575107
[I 2024-04-18 15:00:44,159] Trial 99 finished with value: 0.7595658029056476 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.9313711932374781, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011633867937315842, 'warm_start': True}. Best is trial 99 with value: 0.7595658029056476.


* Best trial for C-index:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.7595658029056476], datetime_start=datetime.datetime(2024, 4, 18, 15, 0, 42, 837810), datetime_complete=datetime.datetime(2024, 4, 18, 15, 0, 44, 159120), params={'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.9313711932374781, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011633867937315842, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=99, value=None)


* Best Score for C-index:
 0.7595658029056476

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24174212688781635
Fold 2 IBS: 0.22837556031637174
Fold 3 IBS: 0.21925199037851104
Fold 4 IBS: 0.23387858646882115
Fold 5 IBS: 0.21192783289424028
[I 2024-04-18 15:00:50,510] Trial 0 finished with value: 0.2270352193891521 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.2270352193891521.
Fold 1 IBS: 0.24144275735387236
Fold 2 IBS: 0.22079642625239382
Fold 3 IBS: 0.2195858644892306
Fold 4 IBS: 0.2328787523585072
Fold 5 IBS: 0.21468068071692512
[I 2024-04-18 15:00:52,602] Trial 1 finished with value: 0.2258768962341858 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.2258768962341858.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-18 15:00:54,099] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.2258768962341858.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-18 15:00:59,428] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.2258768962341858.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-18 15:01:04,722] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.2258768962341858.
Fold 1 IBS: 0.2492022721662945
Fold 2 IBS: 0.2248156215657013
Fold 3 IBS: 0.21773271752809326
Fold 4 IBS: 0.2287247859937131
Fold 5 IBS: 0.21591178374347977
[I 2024-04-18 15:01:19,922] Trial 5 finished with value: 0.22727743619945642 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.2258768962341858.
Fold 1 IBS: 0.24345429173373118
Fold 2 IBS: 0.22177590887724122
Fold 3 IBS: 0.21900257819310728
Fold 4 IBS: 0.2300708478315454
Fold 5 IBS: 0.20857620825948778
[I 2024-04-18 15:01:24,661] Trial 6 finished with value: 0.2245759669790226 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24553997148168735
Fold 2 IBS: 0.23209632831596824
Fold 3 IBS: 0.22914599492354287
Fold 4 IBS: 0.24151189951584615
Fold 5 IBS: 0.22920646238220327
[I 2024-04-18 15:01:29,924] Trial 7 finished with value: 0.23550013132384956 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-18 15:01:38,030] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.23795187102456028
Fold 2 IBS: 0.22068804877472178
Fold 3 IBS: 0.21736841990005548
Fold 4 IBS: 0.23483534153305224
Fold 5 IBS: 0.2166813748058101
[I 2024-04-18 15:01:39,745] Trial 9 finished with value: 0.22550501120764 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24645571521465787
Fold 2 IBS: 0.23214351218858914
Fold 3 IBS: 0.23029990468218745
Fold 4 IBS: 0.24091247880712954
Fold 5 IBS: 0.22969387017589088
[I 2024-04-18 15:01:49,230] Trial 10 finished with value: 0.235901096213691 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3251129986182119}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.23821763800269524
Fold 2 IBS: 0.2206989405701499
Fold 3 IBS: 0.2183298733900689
Fold 4 IBS: 0.23435319377188557
Fold 5 IBS: 0.21624993612827711
[I 2024-04-18 15:01:51,345] Trial 11 finished with value: 0.22556991637261534 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 133, 'oob_score': False, 'max_samples': 0.9904090680670613, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17706129541113583}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.2390269025799132
Fold 2 IBS: 0.22093723784955296
Fold 3 IBS: 0.21614331470726378
Fold 4 IBS: 0.23568779668901688
Fold 5 IBS: 0.21706838561267935
[I 2024-04-18 15:01:54,299] Trial 12 finished with value: 0.2257727274876852 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.9777827337837477, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3324053831839262}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.28429571858174646
Fold 2 IBS: 0.291976143238516
Fold 3 IBS: 0.25971605676138104
Fold 4 IBS: 0.2911448075888225
Fold 5 IBS: 0.2421484554746106
[I 2024-04-18 15:01:55,204] Trial 13 finished with value: 0.27385623632901535 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.8358240113413322, 'max_features': None, 'min_weight_fraction_leaf': 0.0035697594234744834}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24072003207164025
Fold 2 IBS: 0.22931923287626255
Fold 3 IBS: 0.2206971081552678
Fold 4 IBS: 0.23441816780813163
Fold 5 IBS: 0.21155006913932226
[I 2024-04-18 15:01:59,670] Trial 14 finished with value: 0.22734092201012487 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.8213409911746509, 'max_features': None, 'min_weight_fraction_leaf': 0.2466431683648488}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24011905153998128
Fold 2 IBS: 0.22518763981988726
Fold 3 IBS: 0.22165869139663433
Fold 4 IBS: 0.2375480054269681
Fold 5 IBS: 0.21939984365433624
[I 2024-04-18 15:02:02,804] Trial 15 finished with value: 0.22878264636756143 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 15, 'n_estimators': 187, 'oob_score': False, 'max_samples': 0.8537410313073572, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3655886525927784}. Best is trial 6 with value: 0.2245759669790226.

Fold 1 IBS: 0.2392961564663636
Fold 2 IBS: 0.2209141876561904
Fold 3 IBS: 0.2197843622003885
Fold 4 IBS: 0.23449432140937404
Fold 5 IBS: 0.21510746016776658
[I 2024-04-18 15:02:04,630] Trial 16 finished with value: 0.2259192975800166 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 20, 'max_depth': 9, 'n_estimators': 101, 'oob_score': False, 'max_samples': 0.8978246151361277, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12075256052520705}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.23788710888494208
Fold 2 IBS: 0.22243680052846054
Fold 3 IBS: 0.21523716494988468
Fold 4 IBS: 0.2354635803357212
Fold 5 IBS: 0.21631738782405596
[I 2024-04-18 15:02:09,703] Trial 17 finished with value: 0.2254684085046129 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.741685896826822, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27799606575272795}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.23869855628325998
Fold 2 IBS: 0.22242767695758497
Fold 3 IBS: 0.2157055296703147
Fold 4 IBS: 0.23576281546540628
Fold 5 IBS: 0.2157448032649353
[I 2024-04-18 15:02:15,635] Trial 18 finished with value: 0.22566787632830027 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.7546903089061138, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2742435840937791}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24632840137946754
Fold 2 IBS: 0.23215399476522983
Fold 3 IBS: 0.22955396254585125
Fold 4 IBS: 0.24150521854716006
Fold 5 IBS: 0.23021366118499692
[I 2024-04-18 15:02:21,540] Trial 19 finished with value: 0.23595104768454114 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.6099910227680899, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3749437552159898}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24666575342744318
Fold 2 IBS: 0.23213825794648577
Fold 3 IBS: 0.2295175914696922
Fold 4 IBS: 0.24160807083199934
Fold 5 IBS: 0.23035609618327466
[I 2024-04-18 15:02:25,811] Trial 20 finished with value: 0.236057153971779 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.7619585591959509, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4532041395885572}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24238904514874957
Fold 2 IBS: 0.23445593643522006
Fold 3 IBS: 0.22631622026231327
Fold 4 IBS: 0.24260320628868504
Fold 5 IBS: 0.21291028085045807
[I 2024-04-18 15:02:32,558] Trial 21 finished with value: 0.2317349377970852 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 398, 'oob_score': False, 'max_samples': 0.9187552595429349, 'max_features': None, 'min_weight_fraction_leaf': 0.21197947565921343}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.23815659783121731
Fold 2 IBS: 0.22207749230002619
Fold 3 IBS: 0.21752970637890848
Fold 4 IBS: 0.23583123734864406
Fold 5 IBS: 0.2164629406223946
[I 2024-04-18 15:02:37,436] Trial 22 finished with value: 0.22601159489623815 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 295, 'oob_score': False, 'max_samples': 0.8060035003385533, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3067334006568516}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.2365247351332946
Fold 2 IBS: 0.22050557618201566
Fold 3 IBS: 0.21512045407281427
Fold 4 IBS: 0.2337779971213356
Fold 5 IBS: 0.2161481181306821
[I 2024-04-18 15:02:43,083] Trial 23 finished with value: 0.22441537612802845 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9051753762122661, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.23816787952025506}. Best is trial 23 with value: 0.22441537612802845.
Fold 1 IBS: 0.23561339472694814
Fold 2 IBS: 0.22133586039163214
Fold 3 IBS: 0.21447786302348743
Fold 4 IBS: 0.23400436966113364
Fold 5 IBS: 0.21612644313403398
[I 2024-04-18 15:02:47,304] Trial 24 finished with value: 0.22431158618744704 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 243, 'oob_score': False, 'max_samples': 0.9299177072569818, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2520392540669227}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.23734053455594875
Fold 2 IBS: 0.22238136978606352
Fold 3 IBS: 0.217109879798544
Fold 4 IBS: 0.23602786050229949
Fold 5 IBS: 0.21660878345157603
[I 2024-04-18 15:02:51,433] Trial 25 finished with value: 0.22589368561888637 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 239, 'oob_score': False, 'max_samples': 0.9932624357183849, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.36562561378195096}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.23719982212029692
Fold 2 IBS: 0.22044726520696664
Fold 3 IBS: 0.21486784959214336
Fold 4 IBS: 0.23273159700220875
Fold 5 IBS: 0.21646579110319986
[I 2024-04-18 15:02:55,303] Trial 26 finished with value: 0.2243424650049631 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 174, 'oob_score': True, 'max_samples': 0.9058902641802971, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.23696300699805542}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.2437963229547316
Fold 2 IBS: 0.22276653565660226
Fold 3 IBS: 0.21454006940897422
Fold 4 IBS: 0.23541573435802962
Fold 5 IBS: 0.2144905314321996
[I 2024-04-18 15:02:59,729] Trial 27 finished with value: 0.22620183876210748 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 164, 'oob_score': True, 'max_samples': 0.9377046402810433, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14696574200200033}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.2466592970927268
Fold 2 IBS: 0.2322006384871181
Fold 3 IBS: 0.2298545910321478
Fold 4 IBS: 0.24133288058090815
Fold 5 IBS: 0.230048552619906
[I 2024-04-18 15:03:04,483] Trial 28 finished with value: 0.23601919196256138 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 227, 'oob_score': True, 'max_samples': 0.26154064534881144, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22590607990715106}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.23758412825426514
Fold 2 IBS: 0.22297538914957787
Fold 3 IBS: 0.21638228130409853
Fold 4 IBS: 0.2349760943144391
Fold 5 IBS: 0.21663197350890054
[I 2024-04-18 15:03:08,148] Trial 29 finished with value: 0.22570997330625625 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 191, 'oob_score': True, 'max_samples': 0.6859458752534023, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24558091355365722}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.24245047612298046
Fold 2 IBS: 0.22271929119513714
Fold 3 IBS: 0.2181117133635492
Fold 4 IBS: 0.23245730057613723
Fold 5 IBS: 0.2186082238373671
[I 2024-04-18 15:03:10,890] Trial 30 finished with value: 0.22686940101903424 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 132, 'oob_score': True, 'max_samples': 0.4388997479034245, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11470501817805681}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.2399850896709501
Fold 2 IBS: 0.23006555677291446
Fold 3 IBS: 0.2217715118746403
Fold 4 IBS: 0.23484827509541154
Fold 5 IBS: 0.21133378408198586
[I 2024-04-18 15:03:15,072] Trial 31 finished with value: 0.22760084349918044 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 260, 'oob_score': False, 'max_samples': 0.8683795773714846, 'max_features': None, 'min_weight_fraction_leaf': 0.25607534090715667}. Best is trial 24 with value: 0.22431158618744704.

Fold 1 IBS: 0.2370347091364531
Fold 2 IBS: 0.21865616933268361
Fold 3 IBS: 0.2136904590169095
Fold 4 IBS: 0.2330616724900941
Fold 5 IBS: 0.21522492222501335
[I 2024-04-18 15:03:21,541] Trial 32 finished with value: 0.22353358644023075 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.8040571874379057, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18786523282060735}. Best is trial 32 with value: 0.22353358644023075.
Fold 1 IBS: 0.2369596498960518
Fold 2 IBS: 0.21919381104819285
Fold 3 IBS: 0.21367435784125732
Fold 4 IBS: 0.2331924481484345
Fold 5 IBS: 0.21510595787220624
[I 2024-04-18 15:03:27,377] Trial 33 finished with value: 0.22362524496122854 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 309, 'oob_score': True, 'max_samples': 0.7910445247744765, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18809103319338225}. Best is trial 32 with value: 0.22353358644023075.
Fold 1 IBS: 0.23672523561114803
Fold 2 IBS: 0.21905100495993393
Fold 3 IBS: 0.21428207375878827
Fold 4 IBS: 0.23334334259045397
Fold 5 IBS: 0.21462924819781068
[I 2024-04-18 15:03:35,515] Trial 34 finished with value: 0.22360618102362695 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 377, 'oob_score': True, 'max_samples': 0.7912137176760294, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18558593432482404}. Best is trial 32 with value: 0.22353358644023075.
Fold 1 IBS: 0.23686591677724925
Fold 2 IBS: 0.21880215905099826
Fold 3 IBS: 0.21348650762243437
Fold 4 IBS: 0.23350536986447867
Fold 5 IBS: 0.21453876729002655
[I 2024-04-18 15:03:42,723] Trial 35 finished with value: 0.22343974412103745 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 370, 'oob_score': True, 'max_samples': 0.7882412474357445, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18410738872353652}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.23712660831229618
Fold 2 IBS: 0.21936207956912226
Fold 3 IBS: 0.21377037949196134
Fold 4 IBS: 0.2353853780161964
Fold 5 IBS: 0.21604409087841447
[I 2024-04-18 15:03:49,822] Trial 36 finished with value: 0.22433770725359814 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 389, 'oob_score': True, 'max_samples': 0.6319734188794576, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18057866445401774}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.23985764041755697
Fold 2 IBS: 0.2203910722203549
Fold 3 IBS: 0.21615232998036504
Fold 4 IBS: 0.2324242099038112
Fold 5 IBS: 0.21377035023694235
[I 2024-04-18 15:03:57,192] Trial 37 finished with value: 0.2245191205518061 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 372, 'oob_score': True, 'max_samples': 0.7747419667382262, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14511659298967997}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.24676336973074187
Fold 2 IBS: 0.22400017565703165
Fold 3 IBS: 0.22050607510658007
Fold 4 IBS: 0.23160175255798512
Fold 5 IBS: 0.21460046142043543
[I 2024-04-18 15:04:06,450] Trial 38 finished with value: 0.22749436689455482 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 474, 'oob_score': True, 'max_samples': 0.708969650791409, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07841760859950192}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.24122790903542682
Fold 2 IBS: 0.22126564420108252
Fold 3 IBS: 0.21500814519153294
Fold 4 IBS: 0.23088715452854772
Fold 5 IBS: 0.21505297571279228
[I 2024-04-18 15:04:15,019] Trial 39 finished with value: 0.22468836573387643 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 436, 'oob_score': True, 'max_samples': 0.5567914809570165, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10107929772200888}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.2512512194499984
Fold 2 IBS: 0.23384119436207942
Fold 3 IBS: 0.21986209620007618
Fold 4 IBS: 0.2324052704281404
Fold 5 IBS: 0.21614780773365797
[I 2024-04-18 15:04:20,748] Trial 40 finished with value: 0.23070151763479047 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 313, 'oob_score': True, 'max_samples': 0.6360911606111228, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04797053004225782}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.2364825751273401
Fold 2 IBS: 0.21926467455871407
Fold 3 IBS: 0.21319128346432453
Fold 4 IBS: 0.2332830275103288
Fold 5 IBS: 0.21513344099462875
[I 2024-04-18 15:04:27,680] Trial 41 finished with value: 0.2234710003310673 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.7910648434560368, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.19044184409775022}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.23657216849211188
Fold 2 IBS: 0.21805180183232972
Fold 3 IBS: 0.2134098718971707
Fold 4 IBS: 0.2326760577782485
Fold 5 IBS: 0.21489772695679377
[I 2024-04-18 15:04:32,882] Trial 42 finished with value: 0.22312152539133093 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 363, 'oob_score': True, 'max_samples': 0.8069030132321051, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.19162190380727356}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23945616928698815
Fold 2 IBS: 0.22072840117287257
Fold 3 IBS: 0.2138390608089632
Fold 4 IBS: 0.23224317279049148
Fold 5 IBS: 0.21446628607960228
[I 2024-04-18 15:04:38,323] Trial 43 finished with value: 0.22414661802778352 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 354, 'oob_score': True, 'max_samples': 0.7256599857619218, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1528479024949021}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23649706067068324
Fold 2 IBS: 0.21941209208908452
Fold 3 IBS: 0.21295847947231347
Fold 4 IBS: 0.23594218559775645
Fold 5 IBS: 0.21615807717067265
[I 2024-04-18 15:04:48,332] Trial 44 finished with value: 0.2241935790001021 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 424, 'oob_score': True, 'max_samples': 0.6735879050942102, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2020053940682765}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23693251190244155
Fold 2 IBS: 0.2213288517310521
Fold 3 IBS: 0.21494689188039331
Fold 4 IBS: 0.23415254475273511
Fold 5 IBS: 0.21682890772894134
[I 2024-04-18 15:05:06,817] Trial 45 finished with value: 0.2248379415991127 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.5054965069088588, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16858288066901586}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.24197332198213933
Fold 2 IBS: 0.22046487286415592
Fold 3 IBS: 0.21586457052819402
Fold 4 IBS: 0.23223394094427516
Fold 5 IBS: 0.2132292438608055
[I 2024-04-18 15:05:17,238] Trial 46 finished with value: 0.224753190035914 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 454, 'oob_score': True, 'max_samples': 0.8105930895493332, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12622439487788628}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23556816618505033
Fold 2 IBS: 0.21943285786800518
Fold 3 IBS: 0.21472972925457443
Fold 4 IBS: 0.23233131562389348

Fold 5 IBS: 0.21452585999296125
[I 2024-04-18 15:05:22,695] Trial 47 finished with value: 0.22331758578489697 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 332, 'oob_score': True, 'max_samples': 0.8648447148686852, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19908924320632904}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23571677073756844
Fold 2 IBS: 0.21862106487993588
Fold 3 IBS: 0.21456356649548577
Fold 4 IBS: 0.23300957311771886
Fold 5 IBS: 0.2147097776323396
[I 2024-04-18 15:05:28,943] Trial 48 finished with value: 0.2233241505726097 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 339, 'oob_score': True, 'max_samples': 0.85048001681846, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21469064698337334}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23559067856645097
Fold 2 IBS: 0.21873875911929633
Fold 3 IBS: 0.21444282499967143
Fold 4 IBS: 0.2331433841346366
Fold 5 IBS: 0.21521373828133133
[I 2024-04-18 15:05:34,921] Trial 49 finished with value: 0.22342587702027733 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 349, 'oob_score': True, 'max_samples': 0.8608777099735355, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21409963196930723}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2354720485014348
Fold 2 IBS: 0.21908483698682585
Fold 3 IBS: 0.21419738362473992
Fold 4 IBS: 0.23286928627582323
Fold 5 IBS: 0.21554847437687882
[I 2024-04-18 15:05:40,675] Trial 50 finished with value: 0.2234344059531405 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 331, 'oob_score': True, 'max_samples': 0.8624774255144273, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2109347249153205}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23627193006876482
Fold 2 IBS: 0.21852946709881008
Fold 3 IBS: 0.2148469504923258
Fold 4 IBS: 0.23351001052284076
Fold 5 IBS: 0.21507169524249345
[I 2024-04-18 15:05:46,622] Trial 51 finished with value: 0.22364601068504694 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 339, 'oob_score': True, 'max_samples': 0.8695358762760744, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21582255489884755}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23548356533028544
Fold 2 IBS: 0.218725010588746
Fold 3 IBS: 0.21451762386354145
Fold 4 IBS: 0.23286275629435157
Fold 5 IBS: 0.21475783585840155
[I 2024-04-18 15:05:52,378] Trial 52 finished with value: 0.22326935838706521 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 348, 'oob_score': True, 'max_samples': 0.8462587816411291, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21547666896690265}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23613634094238448
Fold 2 IBS: 0.21848749437898204
Fold 3 IBS: 0.21292409617818456
Fold 4 IBS: 0.23567681901169757
Fold 5 IBS: 0.21518372968081823
[I 2024-04-18 15:05:58,053] Trial 53 finished with value: 0.22368169603841337 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.9631487042826314, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2887922839794046}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23665761244588207
Fold 2 IBS: 0.22117302572817424
Fold 3 IBS: 0.21340438192039934
Fold 4 IBS: 0.2344340217943337
Fold 5 IBS: 0.21637287825154097
[I 2024-04-18 15:06:03,758] Trial 54 finished with value: 0.2244083840280661 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 286, 'oob_score': True, 'max_samples': 0.8464063284466049, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2697118114658599}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23609369849161851
Fold 2 IBS: 0.22007777901922662
Fold 3 IBS: 0.215855484457008
Fold 4 IBS: 0.23438134550311407
Fold 5 IBS: 0.21573946841596092
[I 2024-04-18 15:06:09,097] Trial 55 finished with value: 0.2244295551773856 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 271, 'oob_score': True, 'max_samples': 0.879833085890255, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21383320692792412}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.24222956946122723
Fold 2 IBS: 0.22137697302616127
Fold 3 IBS: 0.21626516807485707
Fold 4 IBS: 0.23437496001734787
Fold 5 IBS: 0.21368603534260622
[I 2024-04-18 15:06:15,386] Trial 56 finished with value: 0.22558654118443994 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 354, 'oob_score': True, 'max_samples': 0.9448123317517924, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15922434069943384}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23566710868723995
Fold 2 IBS: 0.21815687589456226
Fold 3 IBS: 0.21374824567704823
Fold 4 IBS: 0.23516414343276787
Fold 5 IBS: 0.2155717168434672
[I 2024-04-18 15:06:22,749] Trial 57 finished with value: 0.2236616181070171 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 409, 'oob_score': True, 'max_samples': 0.8302783773614499, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2212917621096384}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23597677041833393
Fold 2 IBS: 0.21966309894338662
Fold 3 IBS: 0.2147789356113197
Fold 4 IBS: 0.2346364915456495
Fold 5 IBS: 0.21544052695772373
[I 2024-04-18 15:06:28,610] Trial 58 finished with value: 0.22409916469528265 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.8822727605099482, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.26404114905990445}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23687443879472495
Fold 2 IBS: 0.2196115034471744
Fold 3 IBS: 0.2144316176908922
Fold 4 IBS: 0.23394500800067253
Fold 5 IBS: 0.21552843402248026
[I 2024-04-18 15:06:33,176] Trial 59 finished with value: 0.22407820039118884 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 299, 'oob_score': True, 'max_samples': 0.9619605093804899, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3043109475953167}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23648824629467255
Fold 2 IBS: 0.22035324074970292
Fold 3 IBS: 0.21311491690305986
Fold 4 IBS: 0.23558874827891282
Fold 5 IBS: 0.2147764365302421
[I 2024-04-18 15:06:39,935] Trial 60 finished with value: 0.22406431775131805 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 389, 'oob_score': True, 'max_samples': 0.7432259190596778, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23401215359777172}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23534762568590942
Fold 2 IBS: 0.21918131507767896
Fold 3 IBS: 0.21348843313052338
Fold 4 IBS: 0.2345139591305208
Fold 5 IBS: 0.2147806291992252
[I 2024-04-18 15:06:46,002] Trial 61 finished with value: 0.22346239244477153 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 356, 'oob_score': True, 'max_samples': 0.8400984283316736, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20744391800378348}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23683459238973079
Fold 2 IBS: 0.2190589139081263
Fold 3 IBS: 0.21251768095507126
Fold 4 IBS: 0.23333473964097387
Fold 5 IBS: 0.21540218190074592
[I 2024-04-18 15:06:52,695] Trial 62 finished with value: 0.22342962175892964 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 413, 'oob_score': True, 'max_samples': 0.7146112288426298, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1673008720099634}. Best is trial 42 with value: 0.22312152539133093.

Fold 1 IBS: 0.24251844789708726
Fold 2 IBS: 0.2210411248095999
Fold 3 IBS: 0.2174884582534811
Fold 4 IBS: 0.23327796476633547
Fold 5 IBS: 0.21325865662478627
[I 2024-04-18 15:07:00,107] Trial 63 finished with value: 0.225516930470258 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 440, 'oob_score': True, 'max_samples': 0.8434390256503708, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13262761517233745}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.24154578994370174
Fold 2 IBS: 0.22210454661611326
Fold 3 IBS: 0.21614753754341642
Fold 4 IBS: 0.23303912664616094
Fold 5 IBS: 0.21337979688122055
[I 2024-04-18 15:07:07,098] Trial 64 finished with value: 0.2252433595261226 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 421, 'oob_score': True, 'max_samples': 0.9071936553420485, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1668837494665743}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23578396984973268
Fold 2 IBS: 0.21982751985915058
Fold 3 IBS: 0.2127907655486023
Fold 4 IBS: 0.23611774962723142
Fold 5 IBS: 0.21593645923354832
[I 2024-04-18 15:07:13,452] Trial 65 finished with value: 0.22409129282365306 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 407, 'oob_score': True, 'max_samples': 0.7091534179771193, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22490980526604287}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2465390297659536
Fold 2 IBS: 0.23217413632394113
Fold 3 IBS: 0.22957331555813507
Fold 4 IBS: 0.24145493115068345
Fold 5 IBS: 0.23026954015536694
[I 2024-04-18 15:07:18,590] Trial 66 finished with value: 0.236002190590816 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 320, 'oob_score': True, 'max_samples': 0.7513910467079336, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4904781810386246}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2360357412254428
Fold 2 IBS: 0.2187126930774909
Fold 3 IBS: 0.21351408679377545
Fold 4 IBS: 0.2329566459809213
Fold 5 IBS: 0.2152135771982376
[I 2024-04-18 15:07:24,112] Trial 67 finished with value: 0.22328654885517357 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 342, 'oob_score': True, 'max_samples': 0.8253291108475478, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20313220519951403}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.24065133829818755
Fold 2 IBS: 0.22649622349010287
Fold 3 IBS: 0.22286450107823114
Fold 4 IBS: 0.23931283464708142
Fold 5 IBS: 0.22158590387862978
[I 2024-04-18 15:07:30,012] Trial 68 finished with value: 0.23018216027844657 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.23482143077480938, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10469307170592539}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23857197966111204
Fold 2 IBS: 0.21969954436291245
Fold 3 IBS: 0.21312219615211478
Fold 4 IBS: 0.23141791617263682
Fold 5 IBS: 0.21602934314344477
[I 2024-04-18 15:07:37,648] Trial 69 finished with value: 0.22376819589844418 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 347, 'oob_score': True, 'max_samples': 0.5927472377062504, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1379977256731293}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23885528352241767
Fold 2 IBS: 0.21953869680569335
Fold 3 IBS: 0.2148775976903492
Fold 4 IBS: 0.23345908200176593
Fold 5 IBS: 0.21438276633195175
[I 2024-04-18 15:07:56,512] Trial 70 finished with value: 0.22422268527043557 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 470, 'oob_score': True, 'max_samples': 0.8292047043164549, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16367930540263453}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23680915897690014
Fold 2 IBS: 0.22008714306330915
Fold 3 IBS: 0.21622674732020958
Fold 4 IBS: 0.23269848004964874
Fold 5 IBS: 0.21476478864691187
[I 2024-04-18 15:08:06,407] Trial 71 finished with value: 0.2241172636113959 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.886809939325558, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2018241978642696}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23602132741932083
Fold 2 IBS: 0.21929352463181243
Fold 3 IBS: 0.21479463231545
Fold 4 IBS: 0.23487972856446335
Fold 5 IBS: 0.21569292472186188
[I 2024-04-18 15:08:11,321] Trial 72 finished with value: 0.22413642753058172 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.8633059632266107, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24563240525389668}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23756080896385787
Fold 2 IBS: 0.2198709901179539
Fold 3 IBS: 0.21607716703164753
Fold 4 IBS: 0.23444739602719725
Fold 5 IBS: 0.21515728419865568
[I 2024-04-18 15:08:15,977] Trial 73 finished with value: 0.22462272926786242 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.9365960110126715, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20402438062021583}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2439734659304091
Fold 2 IBS: 0.2178765152434605
Fold 3 IBS: 0.21637058574280912
Fold 4 IBS: 0.23265790035339595
Fold 5 IBS: 0.21509688786020262
[I 2024-04-18 15:08:17,228] Trial 74 finished with value: 0.22519507102605546 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 68, 'oob_score': True, 'max_samples': 0.7690209890280151, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17482878175722952}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.24167367619307714
Fold 2 IBS: 0.2321091666317781
Fold 3 IBS: 0.2254096772934718
Fold 4 IBS: 0.2412558098040841
Fold 5 IBS: 0.2112087474135227
[I 2024-04-18 15:08:24,068] Trial 75 finished with value: 0.23033141546718677 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 383, 'oob_score': True, 'max_samples': 0.9185869784489429, 'max_features': None, 'min_weight_fraction_leaf': 0.22786656653980156}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23643423760441268
Fold 2 IBS: 0.2189682190598761
Fold 3 IBS: 0.21316331155747148
Fold 4 IBS: 0.23551095785015766
Fold 5 IBS: 0.21530716431950858
[I 2024-04-18 15:08:30,121] Trial 76 finished with value: 0.22387677807828527 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 360, 'oob_score': True, 'max_samples': 0.8145758924117495, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.25894296074467726}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23649835615235615
Fold 2 IBS: 0.2202998367772717
Fold 3 IBS: 0.215849186186392
Fold 4 IBS: 0.23189510546241013
Fold 5 IBS: 0.21421820558824664
[I 2024-04-18 15:08:35,622] Trial 77 finished with value: 0.22375213803333532 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 325, 'oob_score': True, 'max_samples': 0.8574304723771203, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.19219578753985594}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23543043862820737
Fold 2 IBS: 0.21941172237656087
Fold 3 IBS: 0.21510969675644945
Fold 4 IBS: 0.23449274572109305

Fold 5 IBS: 0.21423498837277127
[I 2024-04-18 15:08:41,346] Trial 78 finished with value: 0.22373591837101642 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 346, 'oob_score': True, 'max_samples': 0.8854068847594949, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23765891161800223}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23570867974207424
Fold 2 IBS: 0.22060193373952594
Fold 3 IBS: 0.2144464193518562
Fold 4 IBS: 0.23476296957407278
Fold 5 IBS: 0.21578644913062256
[I 2024-04-18 15:08:46,084] Trial 79 finished with value: 0.22426129030763034 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.9991782770608287, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2796131771286568}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.25860616056552466
Fold 2 IBS: 0.247606837719613
Fold 3 IBS: 0.2319726248414201
Fold 4 IBS: 0.21372331996096558
Fold 5 IBS: 0.22292533572909917
[I 2024-04-18 15:08:46,430] Trial 80 finished with value: 0.23496685576332452 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 2, 'oob_score': True, 'max_samples': 0.7266137530392617, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15138133095624934}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2424425528776856
Fold 2 IBS: 0.23603790633519647
Fold 3 IBS: 0.22385508599506115
Fold 4 IBS: 0.2408498337269256
Fold 5 IBS: 0.21319653378514064
[I 2024-04-18 15:08:52,641] Trial 81 finished with value: 0.2312763825440019 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 367, 'oob_score': True, 'max_samples': 0.7784763388289013, 'max_features': None, 'min_weight_fraction_leaf': 0.1797361326491144}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2359333065359587
Fold 2 IBS: 0.2177740535675139
Fold 3 IBS: 0.21340554055264466
Fold 4 IBS: 0.23325957841825662
Fold 5 IBS: 0.21578220466559705
[I 2024-04-18 15:08:59,586] Trial 82 finished with value: 0.22323093674799416 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 415, 'oob_score': True, 'max_samples': 0.8175962542874978, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19766586115305992}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23601034698653564
Fold 2 IBS: 0.21748305842766855
Fold 3 IBS: 0.21304430322253315
Fold 4 IBS: 0.23308271498728148
Fold 5 IBS: 0.21565089781052826
[I 2024-04-18 15:09:06,526] Trial 83 finished with value: 0.22305426428690941 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 414, 'oob_score': True, 'max_samples': 0.8141450872491632, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1970991647731129}. Best is trial 83 with value: 0.22305426428690941.
Fold 1 IBS: 0.23612684478177634
Fold 2 IBS: 0.21748810056111387
Fold 3 IBS: 0.21296826834994675
Fold 4 IBS: 0.23300146461188564
Fold 5 IBS: 0.21553229839714166
[I 2024-04-18 15:09:14,917] Trial 84 finished with value: 0.22302339534037285 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.8096737689830545, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19628098798162147}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23647255696644645
Fold 2 IBS: 0.21812077297319524
Fold 3 IBS: 0.21276820303695784
Fold 4 IBS: 0.23345302877262153
Fold 5 IBS: 0.2159040770659359
[I 2024-04-18 15:09:24,187] Trial 85 finished with value: 0.22334372776303138 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 459, 'oob_score': True, 'max_samples': 0.811352649827629, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20105461655472903}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23613729090343752
Fold 2 IBS: 0.2179346998491405
Fold 3 IBS: 0.2129644243629255
Fold 4 IBS: 0.23394201782485338
Fold 5 IBS: 0.21572915695093184
[I 2024-04-18 15:09:31,714] Trial 86 finished with value: 0.22334151797825771 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 488, 'oob_score': True, 'max_samples': 0.8015324404528672, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19820833818823205}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23651644370953373
Fold 2 IBS: 0.2183132341743879
Fold 3 IBS: 0.2134129991132886
Fold 4 IBS: 0.2346203263183014
Fold 5 IBS: 0.21491522745649771
[I 2024-04-18 15:09:41,237] Trial 87 finished with value: 0.22355564615440188 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 496, 'oob_score': True, 'max_samples': 0.7613285087560672, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19051696011006752}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23671103316078027
Fold 2 IBS: 0.22284517298984777
Fold 3 IBS: 0.21466085140706787
Fold 4 IBS: 0.23693276256284146
Fold 5 IBS: 0.21629400773876842
[I 2024-04-18 15:09:48,720] Trial 88 finished with value: 0.22548876557186115 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 474, 'oob_score': True, 'max_samples': 0.6860019496673433, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2438001190871077}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.2463868285065531
Fold 2 IBS: 0.23214573353925852
Fold 3 IBS: 0.22952063623082164
Fold 4 IBS: 0.24149813996015929
Fold 5 IBS: 0.23026213720056213
[I 2024-04-18 15:09:56,313] Trial 89 finished with value: 0.23596269508747097 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 485, 'oob_score': True, 'max_samples': 0.8149680975480039, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.41549217555832835}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23557602986231588
Fold 2 IBS: 0.21894288091688477
Fold 3 IBS: 0.21263728838237342
Fold 4 IBS: 0.23680776315197954
Fold 5 IBS: 0.2158104954061969
[I 2024-04-18 15:10:03,493] Trial 90 finished with value: 0.22395489154395012 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 441, 'oob_score': True, 'max_samples': 0.7816843286867342, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.226633406438448}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.2361593385752497
Fold 2 IBS: 0.2180829122586363
Fold 3 IBS: 0.21264954315727935
Fold 4 IBS: 0.2333718311494117
Fold 5 IBS: 0.21516322407038282
[I 2024-04-18 15:10:11,045] Trial 91 finished with value: 0.22308536984219202 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 456, 'oob_score': True, 'max_samples': 0.8383779120700723, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19824639992469062}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23813486363436617
Fold 2 IBS: 0.21841882418390748
Fold 3 IBS: 0.21525721526950065
Fold 4 IBS: 0.23385192469312954
Fold 5 IBS: 0.2144863105931356
[I 2024-04-18 15:10:18,644] Trial 92 finished with value: 0.2240298276748079 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 448, 'oob_score': True, 'max_samples': 0.8371843344422779, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1793365451149834}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23656447575349918
Fold 2 IBS: 0.21820038163639136
Fold 3 IBS: 0.21281675876104583
Fold 4 IBS: 0.23387434885160996
Fold 5 IBS: 0.2155591110547076
[I 2024-04-18 15:10:26,308] Trial 93 finished with value: 0.22340301521145078 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 464, 'oob_score': True, 'max_samples': 0.7957196161977251, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19569167078239133}. Best is trial 84 with value: 0.22302339534037285.

Fold 1 IBS: 0.2364707434109151
Fold 2 IBS: 0.21910149125141531
Fold 3 IBS: 0.21420284080337593
Fold 4 IBS: 0.23438012728527638
Fold 5 IBS: 0.21479897289302796
[I 2024-04-18 15:10:32,950] Trial 94 finished with value: 0.22379083512880213 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 430, 'oob_score': True, 'max_samples': 0.892312681224388, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2167154554420358}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23950861114017571
Fold 2 IBS: 0.22006606579763324
Fold 3 IBS: 0.2159169717512573
Fold 4 IBS: 0.2336883258166932
Fold 5 IBS: 0.21371153072549798
[I 2024-04-18 15:10:40,640] Trial 95 finished with value: 0.22457830104625148 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 481, 'oob_score': True, 'max_samples': 0.8276360496389354, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15723641146991377}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23621930342339553
Fold 2 IBS: 0.2197693683012021
Fold 3 IBS: 0.212549877635375
Fold 4 IBS: 0.2356582021089957
Fold 5 IBS: 0.21528103181762887
[I 2024-04-18 15:10:45,769] Trial 96 finished with value: 0.22389555665731944 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.7367464108563165, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23193902254984444}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.24624060350675028
Fold 2 IBS: 0.2322034277468248
Fold 3 IBS: 0.22948763066493197
Fold 4 IBS: 0.24145111666189772
Fold 5 IBS: 0.23035506563166086
[I 2024-04-18 15:10:53,865] Trial 97 finished with value: 0.23594756884241314 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.521538664132392, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3938564682169779}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.24008462634911135
Fold 2 IBS: 0.23017081780056728
Fold 3 IBS: 0.22347056715802682
Fold 4 IBS: 0.2395816781582648
Fold 5 IBS: 0.21173964829758143
[I 2024-04-18 15:11:01,649] Trial 98 finished with value: 0.22900946755271034 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 448, 'oob_score': True, 'max_samples': 0.916008923653836, 'max_features': None, 'min_weight_fraction_leaf': 0.25397155497290275}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23762169677462724
Fold 2 IBS: 0.21844353189407748
Fold 3 IBS: 0.2134302825507703
Fold 4 IBS: 0.2336034074556809
Fold 5 IBS: 0.2145271402918729
[I 2024-04-18 15:11:07,912] Trial 99 finished with value: 0.22352521179340573 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.7611936700803305, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1748800349642079}. Best is trial 84 with value: 0.22302339534037285.


* Best trial for IBS:
 FrozenTrial(number=84, state=TrialState.COMPLETE, values=[0.22302339534037285], datetime_start=datetime.datetime(2024, 4, 18, 15, 9, 6, 558068), datetime_complete=datetime.datetime(2024, 4, 18, 15, 9, 14, 917064), params={'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.8096737689830545, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19628098798162147}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=84, value=None)


* Best Score for IBS:
 0.22302339534037285

In [57]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [58]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.76
train_ibs:  0.223

#### Test

In [59]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

In [60]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=5, max_leaf_nodes=8,
                     max_samples=0.9313711932374781, min_samples_split=12,
                     min_weight_fraction_leaf=0.011633867937315842,
                     n_estimators=214, random_state=123, warm_start=True)

test_cindex:  0.633

RandomSurvivalForest(max_depth=6, max_features='log2', max_leaf_nodes=20,
                     max_samples=0.8096737689830545, min_samples_leaf=2,
                     min_samples_split=11,
                     min_weight_fraction_leaf=0.19628098798162147,
                     n_estimators=453, oob_score=True, random_state=123)

test_ibs:  0.216

In [61]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [62]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [63]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 15:11:10,019] A new study created in memory with name: no-name-f1f54b3e-d4d5-4893-9d83-9134843f50a9

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6695278969957081
[I 2024-04-18 15:11:11,281] Trial 0 finished with value: 0.6810141068632278 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:11:13,531] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6223175965665236
[I 2024-04-18 15:11:18,896] Trial 2 finished with value: 0.6582254660871222 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 15:11:19,520] Trial 3 finished with value: 0.6744438961941063 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:11:21,447] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:11:24,323] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6609442060085837
[I 2024-04-18 15:11:25,674] Trial 6 finished with value: 0.6859283885370657 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6266094420600858
[I 2024-04-18 15:11:28,883] Trial 7 finished with value: 0.6556068669162063 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6545064377682404
[I 2024-04-18 15:11:29,154] Trial 8 finished with value: 0.6654991867539214 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.5987124463519313
[I 2024-04-18 15:11:36,266] Trial 9 finished with value: 0.6603853489169398 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:11:38,809] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6787072243346007
Fold 5 C-index: 0.628755364806867
[I 2024-04-18 15:11:40,021] Trial 11 finished with value: 0.6617606716684828 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6781115879828327
[I 2024-04-18 15:11:41,958] Trial 12 finished with value: 0.6867027610976928 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6437768240343348
[I 2024-04-18 15:11:43,362] Trial 13 finished with value: 0.6726878143099698 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638831587887255, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:11:44,629] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:11:45,539] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 268, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.33571048327918607, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 12 with value: 0.6867027610976928.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.6825095057034221
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 15:11:47,088] Trial 16 finished with value: 0.6718042314769685 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6535355702555379, 'min_weight_fraction_leaf': 0.1906011147608997}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.6453488372093024
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6825095057034221
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 15:11:48,375] Trial 17 finished with value: 0.6672980040406395 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.903993543626621, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.6375968992248062
Fold 3 C-index: 0.7978723404255319
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6373390557939914
[I 2024-04-18 15:11:49,042] Trial 18 finished with value: 0.6795670368174951 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.38500398118655316, 'min_weight_fraction_leaf': 0.0735015574561402}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 15:11:49,638] Trial 19 finished with value: 0.6806917145768351 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.639253673774636, 'min_weight_fraction_leaf': 0.037408326362835864}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6437768240343348
[I 2024-04-18 15:11:50,881] Trial 20 finished with value: 0.6744556768014014 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8892982712995542, 'min_weight_fraction_leaf': 0.18720118160246144}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 15:11:52,223] Trial 21 finished with value: 0.6816626070383462 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7247491835588253, 'min_weight_fraction_leaf': 0.10612931382459131}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 15:11:53,524] Trial 22 finished with value: 0.6768203176157102 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 447, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5833816310769062, 'min_weight_fraction_leaf': 0.10633258814265802}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6781115879828327
[I 2024-04-18 15:11:54,884] Trial 23 finished with value: 0.6861561520662033 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7310231778151053, 'min_weight_fraction_leaf': 0.013477785996217753}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 15:11:55,819] Trial 24 finished with value: 0.6783926045851235 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8534877389255904, 'min_weight_fraction_leaf': 0.013359081882411139}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6437768240343348
[I 2024-04-18 15:11:57,351] Trial 25 finished with value: 0.6823606592762896 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4743026143351115, 'min_weight_fraction_leaf': 0.05557982163590168}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.5965665236051502
[I 2024-04-18 15:12:04,559] Trial 26 finished with value: 0.6371432881239313 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 410, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6941935959294678, 'min_weight_fraction_leaf': 0.026806923014800983}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.6863117870722434
Fold 5 C-index: 0.6609442060085837
[I 2024-04-18 15:12:05,868] Trial 27 finished with value: 0.6759366077958741 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 443, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5973500072561096, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7553648068669528
[I 2024-04-18 15:12:06,745] Trial 28 finished with value: 0.7175262582650991 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 204, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8562851117410581, 'min_weight_fraction_leaf': 0.07014867084326157}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7725321888412017
[I 2024-04-18 15:12:07,691] Trial 29 finished with value: 0.7156180788739028 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 206, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9207564519428275, 'min_weight_fraction_leaf': 0.07367160474295377}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7510729613733905
[I 2024-04-18 15:12:08,449] Trial 30 finished with value: 0.7115365161329625 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 207, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9237987532624947, 'min_weight_fraction_leaf': 0.08837761097303978}. Best is trial 28 with value: 0.7175262582650991.

Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7682403433476395
[I 2024-04-18 15:12:09,542] Trial 31 finished with value: 0.7161536582914563 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 207, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9402340730195752, 'min_weight_fraction_leaf': 0.07589392630375186}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.721030042918455
[I 2024-04-18 15:12:10,584] Trial 32 finished with value: 0.6961121726190391 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 207, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.855896173949004, 'min_weight_fraction_leaf': 0.08857520431614199}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7639484978540773
[I 2024-04-18 15:12:11,600] Trial 33 finished with value: 0.7153131837982872 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 199, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9327283887206919, 'min_weight_fraction_leaf': 0.07569748402462002}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.6375968992248062
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.6787072243346007
Fold 5 C-index: 0.6802575107296137
[I 2024-04-18 15:12:12,453] Trial 34 finished with value: 0.6664666881360952 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 156, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.835970866549261, 'min_weight_fraction_leaf': 0.23372934022685896}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7081545064377682
[I 2024-04-18 15:12:14,214] Trial 35 finished with value: 0.6882634234693772 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 162, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9271457960024162, 'min_weight_fraction_leaf': 0.130853317292017}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.5736434108527132
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6180257510729614
[I 2024-04-18 15:12:16,821] Trial 36 finished with value: 0.6191913617370259 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 124, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9489017093297756, 'min_weight_fraction_leaf': 0.05781516413223613}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.7124463519313304
[I 2024-04-18 15:12:18,054] Trial 37 finished with value: 0.6833092043963852 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8743715114186904, 'min_weight_fraction_leaf': 0.16627394422836966}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.721030042918455
[I 2024-04-18 15:12:18,916] Trial 38 finished with value: 0.6876697416391948 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 182, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.817264125566284, 'min_weight_fraction_leaf': 0.11814667951535995}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.5697674418604651
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6051502145922747
[I 2024-04-18 15:12:21,245] Trial 39 finished with value: 0.6172171145531613 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 102, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9887286618847455, 'min_weight_fraction_leaf': 0.07199443797246757}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.6787072243346007
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 15:12:22,689] Trial 40 finished with value: 0.66414330845729 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 285, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7565046460320802, 'min_weight_fraction_leaf': 0.24430703768925296}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7381974248927039
[I 2024-04-18 15:12:23,770] Trial 41 finished with value: 0.7066368021144237 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9048172691384212, 'min_weight_fraction_leaf': 0.08914857859645303}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8154506437768241
[I 2024-04-18 15:12:25,791] Trial 42 finished with value: 0.743465329768543 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9365468593171198, 'min_weight_fraction_leaf': 0.041208379854996445}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-18 15:12:27,931] Trial 43 finished with value: 0.6963198668263061 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 181, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8038316611821256, 'min_weight_fraction_leaf': 0.04529341869060194}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7982832618025751
[I 2024-04-18 15:12:32,723] Trial 44 finished with value: 0.7313319298416705 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 236, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9992719988890266, 'min_weight_fraction_leaf': 0.06592612651601726}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6569767441860465
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6459227467811158
[I 2024-04-18 15:12:38,574] Trial 45 finished with value: 0.6673320498489252 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 236, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9991832238100966, 'min_weight_fraction_leaf': 0.2989643862163749}. Best is trial 42 with value: 0.743465329768543.

Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7939914163090128
[I 2024-04-18 15:12:40,985] Trial 46 finished with value: 0.7383725397721712 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 132, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9470561026828803, 'min_weight_fraction_leaf': 0.03640088498403455}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6630901287553648
[I 2024-04-18 15:12:43,996] Trial 47 finished with value: 0.6598696288076124 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 89, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9628659202725078, 'min_weight_fraction_leaf': 0.03266964081324999}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.721030042918455
[I 2024-04-18 15:12:47,219] Trial 48 finished with value: 0.6843049998761438 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 269, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8730259684417422, 'min_weight_fraction_leaf': 0.1266834798944097}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6298449612403101
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6330472103004292
[I 2024-04-18 15:12:47,971] Trial 49 finished with value: 0.6590145940458656 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 136, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.957708632958839, 'min_weight_fraction_leaf': 0.027911042382701867}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.7167381974248928
[I 2024-04-18 15:12:48,722] Trial 50 finished with value: 0.6897778948683545 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 175, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7837469252671783, 'min_weight_fraction_leaf': 0.1078843272541912}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8154506437768241
[I 2024-04-18 15:12:49,629] Trial 51 finished with value: 0.7441605217818494 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 222, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9978368210677339, 'min_weight_fraction_leaf': 0.05105168315138192}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7982832618025751
[I 2024-04-18 15:12:50,179] Trial 52 finished with value: 0.7320707671648804 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 81, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9693702623323143, 'min_weight_fraction_leaf': 0.05796340800499559}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8068669527896996
[I 2024-04-18 15:12:50,655] Trial 53 finished with value: 0.724572062991922 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 76, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9970270850713104, 'min_weight_fraction_leaf': 0.05198230424362128}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7896995708154506
[I 2024-04-18 15:12:51,096] Trial 54 finished with value: 0.7259167134190326 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 66, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9784142102515536, 'min_weight_fraction_leaf': 0.03905401729625176}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.703862660944206
[I 2024-04-18 15:12:51,539] Trial 55 finished with value: 0.7020258748504518 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 54, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9639066574288683, 'min_weight_fraction_leaf': 0.021327695456537624}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:12:52,056] Trial 56 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 25, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8965627067300803, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5876494023904383
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6781115879828327
[I 2024-04-18 15:12:52,272] Trial 57 finished with value: 0.6762686514862031 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 7, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.22469228024982557, 'min_weight_fraction_leaf': 0.05372431175834813}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.7167381974248928
[I 2024-04-18 15:12:52,793] Trial 58 finished with value: 0.6970396573100552 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 77, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5320477532151755, 'min_weight_fraction_leaf': 0.03900243908413086}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6137339055793991
[I 2024-04-18 15:12:53,745] Trial 59 finished with value: 0.6519459902471118 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 55, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9630384668147912, 'min_weight_fraction_leaf': 6.788603062825999e-05}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.6634980988593155
Fold 5 C-index: 0.6158798283261803
[I 2024-04-18 15:12:54,350] Trial 60 finished with value: 0.6413474338179449 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 143, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9882157961126447, 'min_weight_fraction_leaf': 0.38500894227855625}. Best is trial 51 with value: 0.7441605217818494.

Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.776824034334764
[I 2024-04-18 15:12:54,758] Trial 61 finished with value: 0.7225416362930333 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 66, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9943656688034969, 'min_weight_fraction_leaf': 0.04800870002967368}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7081545064377682
[I 2024-04-18 15:12:55,339] Trial 62 finished with value: 0.6897163220843844 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 107, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8946150126733304, 'min_weight_fraction_leaf': 0.10247641006595459}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7639484978540773
[I 2024-04-18 15:12:55,688] Trial 63 finished with value: 0.7196656386882508 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 38, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9438677546925018, 'min_weight_fraction_leaf': 0.024050857269544722}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7896995708154506
[I 2024-04-18 15:12:56,373] Trial 64 finished with value: 0.7327012293133587 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 125, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9946117477834561, 'min_weight_fraction_leaf': 0.056485434742474354}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7896995708154506
[I 2024-04-18 15:12:57,053] Trial 65 finished with value: 0.7433456281236541 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 122, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9063260887192888, 'min_weight_fraction_leaf': 0.012665422708896507}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:12:57,631] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 128, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8260977181471251, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7682403433476395
[I 2024-04-18 15:12:58,697] Trial 67 finished with value: 0.7327922342641481 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9104970128937423, 'min_weight_fraction_leaf': 0.007706755525859518}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7510729613733905
[I 2024-04-18 15:12:59,932] Trial 68 finished with value: 0.7224161877505806 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 295, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9198568568859149, 'min_weight_fraction_leaf': 0.00978704762960042}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7339055793991416
[I 2024-04-18 15:13:01,261] Trial 69 finished with value: 0.7244476068280288 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8797241290258244, 'min_weight_fraction_leaf': 0.01678703277254251}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6437768240343348
[I 2024-04-18 15:13:02,198] Trial 70 finished with value: 0.6745315468327391 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 253, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9113946680361682, 'min_weight_fraction_leaf': 0.03227851293056033}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7124463519313304
[I 2024-04-18 15:13:03,060] Trial 71 finished with value: 0.7075849752369485 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 219, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9418428735851675, 'min_weight_fraction_leaf': 0.06227247952613971}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7381974248927039
[I 2024-04-18 15:13:03,643] Trial 72 finished with value: 0.7027360570907633 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 171, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8489781434967721, 'min_weight_fraction_leaf': 0.08925369909603265}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8497854077253219
[I 2024-04-18 15:13:04,669] Trial 73 finished with value: 0.7683176307777926 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 274, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9666978302306899, 'min_weight_fraction_leaf': 0.0007431171546460995}. Best is trial 73 with value: 0.7683176307777926.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8111587982832618
[I 2024-04-18 15:13:05,825] Trial 74 finished with value: 0.753464799313606 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 253, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8740760642487182, 'min_weight_fraction_leaf': 0.01305076334530337}. Best is trial 73 with value: 0.7683176307777926.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7639484978540773
[I 2024-04-18 15:13:07,010] Trial 75 finished with value: 0.7267661356567718 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 275, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4065884568013973, 'min_weight_fraction_leaf': 0.00029874484326093687}. Best is trial 73 with value: 0.7683176307777926.

Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6137339055793991
[I 2024-04-18 15:13:11,845] Trial 76 finished with value: 0.6416338194920268 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 331, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8799754466378142, 'min_weight_fraction_leaf': 0.01810709499481526}. Best is trial 73 with value: 0.7683176307777926.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8412017167381974
[I 2024-04-18 15:13:12,993] Trial 77 finished with value: 0.7543780132055444 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9240429179776719, 'min_weight_fraction_leaf': 0.012643822634965579}. Best is trial 73 with value: 0.7683176307777926.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6909871244635193
[I 2024-04-18 15:13:14,470] Trial 78 finished with value: 0.6958045178573318 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7594151082635523, 'min_weight_fraction_leaf': 0.015234469209567447}. Best is trial 73 with value: 0.7683176307777926.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8497854077253219
[I 2024-04-18 15:13:15,594] Trial 79 finished with value: 0.7697774108186687 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 250, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8442545000898158, 'min_weight_fraction_leaf': 0.0004457953818449434}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8369098712446352
[I 2024-04-18 15:13:16,334] Trial 80 finished with value: 0.7583547716816389 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 193, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8057269821925708, 'min_weight_fraction_leaf': 0.032477063707157354}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7982832618025751
[I 2024-04-18 15:13:17,132] Trial 81 finished with value: 0.7385651919069479 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.832112782603648, 'min_weight_fraction_leaf': 0.04071400179748555}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8283261802575107
[I 2024-04-18 15:13:18,108] Trial 82 finished with value: 0.7510098175054138 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 246, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7294416952085367, 'min_weight_fraction_leaf': 0.02743234620004307}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8412017167381974
[I 2024-04-18 15:13:19,139] Trial 83 finished with value: 0.759259943171113 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 190, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8005603713498318, 'min_weight_fraction_leaf': 0.024887842810569518}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8197424892703863
[I 2024-04-18 15:13:20,031] Trial 84 finished with value: 0.7468373768005192 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6978238625237797, 'min_weight_fraction_leaf': 0.027202826299221203}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-18 15:13:20,788] Trial 85 finished with value: 0.6834829872526711 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 189, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7435224088611663, 'min_weight_fraction_leaf': 0.026900856768979266}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8454935622317596
[I 2024-04-18 15:13:21,548] Trial 86 finished with value: 0.7730627016264678 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 219, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6969352508494835, 'min_weight_fraction_leaf': 0.0016027914654294685}. Best is trial 86 with value: 0.7730627016264678.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8412017167381974
[I 2024-04-18 15:13:22,619] Trial 87 finished with value: 0.7744609253176357 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 262, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6910931457501369, 'min_weight_fraction_leaf': 0.0034957148487665163}. Best is trial 87 with value: 0.7744609253176357.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.5736434108527132
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6437768240343348
[I 2024-04-18 15:13:26,944] Trial 88 finished with value: 0.62249459003292 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 264, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6571074060623916, 'min_weight_fraction_leaf': 0.002587756834995009}. Best is trial 87 with value: 0.7744609253176357.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8025751072961373
[I 2024-04-18 15:13:28,345] Trial 89 finished with value: 0.7474274777067873 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 305, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6947330701336499, 'min_weight_fraction_leaf': 0.01811060590765391}. Best is trial 87 with value: 0.7744609253176357.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6180257510729614
[I 2024-04-18 15:13:29,227] Trial 90 finished with value: 0.6534956129908318 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7833034071663476, 'min_weight_fraction_leaf': 0.2732759857764308}. Best is trial 87 with value: 0.7744609253176357.

Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8025751072961373
[I 2024-04-18 15:13:30,468] Trial 91 finished with value: 0.7442871889568908 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 301, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6338574910210881, 'min_weight_fraction_leaf': 0.018245084195721045}. Best is trial 87 with value: 0.7744609253176357.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8454935622317596
[I 2024-04-18 15:13:31,573] Trial 92 finished with value: 0.7783542380855362 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7127170027641319, 'min_weight_fraction_leaf': 0.007255594364833751}. Best is trial 92 with value: 0.7783542380855362.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8497854077253219
[I 2024-04-18 15:13:32,780] Trial 93 finished with value: 0.773012031469599 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 275, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7126345666181687, 'min_weight_fraction_leaf': 0.01132491050397371}. Best is trial 92 with value: 0.7783542380855362.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8669527896995708
[I 2024-04-18 15:13:33,775] Trial 94 finished with value: 0.7914071396177732 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8020091028727125, 'min_weight_fraction_leaf': 0.002435943155287043}. Best is trial 94 with value: 0.7914071396177732.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8540772532188842
[I 2024-04-18 15:13:34,820] Trial 95 finished with value: 0.7656779799204749 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.805459261539753, 'min_weight_fraction_leaf': 0.0014206283717166004}. Best is trial 94 with value: 0.7914071396177732.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8583690987124464
[I 2024-04-18 15:13:35,943] Trial 96 finished with value: 0.7792303748029571 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 317, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.803528354509956, 'min_weight_fraction_leaf': 0.0027490549087902}. Best is trial 94 with value: 0.7914071396177732.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7939914163090128
[I 2024-04-18 15:13:37,116] Trial 97 finished with value: 0.7488547526042695 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6615256729229535, 'min_weight_fraction_leaf': 0.003268318092994542}. Best is trial 94 with value: 0.7914071396177732.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7939914163090128
[I 2024-04-18 15:13:38,488] Trial 98 finished with value: 0.7498258990394505 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 279, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6157099383260888, 'min_weight_fraction_leaf': 0.0006747748712030638}. Best is trial 94 with value: 0.7914071396177732.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7452471482889734

[I 2024-04-18 15:13:39,759] A new study created in memory with name: no-name-a98582e8-b3cb-4bff-9e74-eaace8e7e231

Fold 5 C-index: 0.6909871244635193
[I 2024-04-18 15:13:39,739] Trial 99 finished with value: 0.6972890739296207 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 345, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7082106596673203, 'min_weight_fraction_leaf': 0.047918273005709944}. Best is trial 94 with value: 0.7914071396177732.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.7914071396177732], datetime_start=datetime.datetime(2024, 4, 18, 15, 13, 32, 787947), datetime_complete=datetime.datetime(2024, 4, 18, 15, 13, 33, 775035), params={'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8020091028727125, 'min_weight_fraction_leaf': 0.002435943155287043}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=94, value=None)


* Best Score for C-index:
 0.7914071396177732

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2376731560632284
Fold 2 IBS: 0.21418439969357622
Fold 3 IBS: 0.20583073428188067
Fold 4 IBS: 0.22566432866025307
Fold 5 IBS: 0.20768742813444407
[I 2024-04-18 15:13:43,893] Trial 0 finished with value: 0.2182080093666765 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-18 15:13:50,608] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.23822850327226391
Fold 2 IBS: 0.2206236163074506
Fold 3 IBS: 0.21714095783489826
Fold 4 IBS: 0.231585384136663
Fold 5 IBS: 0.21839284596456812
[I 2024-04-18 15:13:55,765] Trial 2 finished with value: 0.2251942615031688 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.23969391295516015
Fold 2 IBS: 0.22269581058919702
Fold 3 IBS: 0.21715327615258315
Fold 4 IBS: 0.23305972993486937
Fold 5 IBS: 0.21933565152070564
[I 2024-04-18 15:13:57,417] Trial 3 finished with value: 0.22638767623050304 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-18 15:14:01,227] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-18 15:14:03,365] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.23749741627181767
Fold 2 IBS: 0.21452695445742026
Fold 3 IBS: 0.2056873183383438
Fold 4 IBS: 0.22461247201663356
Fold 5 IBS: 0.20853691895247092
[I 2024-04-18 15:14:08,713] Trial 6 finished with value: 0.21817221600733724 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24029204437738358
Fold 2 IBS: 0.21830289871526046
Fold 3 IBS: 0.21554373414859246
Fold 4 IBS: 0.22777980675313916
Fold 5 IBS: 0.2123884851749296
[I 2024-04-18 15:14:11,538] Trial 7 finished with value: 0.22286139383386105 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24089922857013013
Fold 2 IBS: 0.22202813660146767
Fold 3 IBS: 0.21893220102332406
Fold 4 IBS: 0.2316324273038109
Fold 5 IBS: 0.2195150868165958
[I 2024-04-18 15:14:12,287] Trial 8 finished with value: 0.2266014160630657 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24074052614629513
Fold 2 IBS: 0.2266612039122537
Fold 3 IBS: 0.22147987410714284
Fold 4 IBS: 0.23635902242741375
Fold 5 IBS: 0.22338299988114635
[I 2024-04-18 15:14:18,847] Trial 9 finished with value: 0.22972472529485036 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24645397072894554
Fold 2 IBS: 0.23215165796624326
Fold 3 IBS: 0.2300072528605466
Fold 4 IBS: 0.24106162740477477
Fold 5 IBS: 0.23037976132987092
[I 2024-04-18 15:14:24,131] Trial 10 finished with value: 0.23601085405807623 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24194872801906908
Fold 2 IBS: 0.22653162527123616
Fold 3 IBS: 0.2214231768945529
Fold 4 IBS: 0.23736843207524794
Fold 5 IBS: 0.22258083713853571
[I 2024-04-18 15:14:29,115] Trial 11 finished with value: 0.22997055987972836 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24166386224310335
Fold 2 IBS: 0.21668275898081935
Fold 3 IBS: 0.21053766058256898
Fold 4 IBS: 0.22332329218058097
Fold 5 IBS: 0.20507124091541545
[I 2024-04-18 15:14:35,620] Trial 12 finished with value: 0.21945576298049763 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2351797092055412
Fold 2 IBS: 0.21809509235620259
Fold 3 IBS: 0.20720090287111972
Fold 4 IBS: 0.2272337876903696
Fold 5 IBS: 0.21352749156724554
[I 2024-04-18 15:14:40,226] Trial 13 finished with value: 0.22024739673809574 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6381530978163132, 'min_weight_fraction_leaf': 0.10302250602390595}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24709076537787542
Fold 2 IBS: 0.23229758763044567
Fold 3 IBS: 0.22965399450652796
Fold 4 IBS: 0.2411751364309486
Fold 5 IBS: 0.23019081700505956
[I 2024-04-18 15:14:43,705] Trial 14 finished with value: 0.23608166019017146 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3469585144995889, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 6 with value: 0.21817221600733724.

Fold 1 IBS: 0.2400719537573894
Fold 2 IBS: 0.21389198803292667
Fold 3 IBS: 0.20731598881412483
Fold 4 IBS: 0.2254024226576354
Fold 5 IBS: 0.2076527894088986
[I 2024-04-18 15:14:48,485] Trial 15 finished with value: 0.21886702853419499 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07436726243220565}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23503018438204812
Fold 2 IBS: 0.2154046167742676
Fold 3 IBS: 0.20556392106742435
Fold 4 IBS: 0.22806516746710437
Fold 5 IBS: 0.2112562209054064
[I 2024-04-18 15:14:52,542] Trial 16 finished with value: 0.2190640221192502 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.18687423911629308}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24669394452893645
Fold 2 IBS: 0.2321566246385927
Fold 3 IBS: 0.22939614692957794
Fold 4 IBS: 0.24141885307467398
Fold 5 IBS: 0.2302911553756569
[I 2024-04-18 15:14:54,854] Trial 17 finished with value: 0.23599134490948756 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 194, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5688392530311949, 'min_weight_fraction_leaf': 0.3862403774000863}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24801473011738637
Fold 2 IBS: 0.23336726698773866
Fold 3 IBS: 0.22984121679333408
Fold 4 IBS: 0.24176299307832128
Fold 5 IBS: 0.23015950059445994
[I 2024-04-18 15:14:55,371] Trial 18 finished with value: 0.23662914151424808 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.053773653856063974}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2464616995792693
Fold 2 IBS: 0.23218447499282707
Fold 3 IBS: 0.2297960999906114
Fold 4 IBS: 0.24126238252144364
Fold 5 IBS: 0.2299756977580421
[I 2024-04-18 15:14:56,990] Trial 19 finished with value: 0.2359360709684387 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4078786025735315, 'min_weight_fraction_leaf': 0.21750931502909437}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2356021274854339
Fold 2 IBS: 0.21736519916854574
Fold 3 IBS: 0.20646952344066247
Fold 4 IBS: 0.2281727318804719
Fold 5 IBS: 0.21322795644159553
[I 2024-04-18 15:15:00,622] Trial 20 finished with value: 0.22016750768334195 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 17, 'n_estimators': 310, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8887988952213425, 'min_weight_fraction_leaf': 0.16483895863649992}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2390208829210001
Fold 2 IBS: 0.21477636398758923
Fold 3 IBS: 0.2077575615094621
Fold 4 IBS: 0.22444376825518106
Fold 5 IBS: 0.20787997219697457
[I 2024-04-18 15:15:05,691] Trial 21 finished with value: 0.21877570977404143 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 416, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7050862172818282, 'min_weight_fraction_leaf': 0.08156751747114571}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2371332546390252
Fold 2 IBS: 0.21451079091509603
Fold 3 IBS: 0.20658616237101907
Fold 4 IBS: 0.2261028080781042
Fold 5 IBS: 0.20871606880123938
[I 2024-04-18 15:15:10,736] Trial 22 finished with value: 0.21860981696089682 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6873159527855055, 'min_weight_fraction_leaf': 0.10600930066685874}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24192493047866456
Fold 2 IBS: 0.21692042280147458
Fold 3 IBS: 0.20634554837219973
Fold 4 IBS: 0.22627161207172614
Fold 5 IBS: 0.20726148438799455
[I 2024-04-18 15:15:16,193] Trial 23 finished with value: 0.21974479962241192 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 459, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6015263103836297, 'min_weight_fraction_leaf': 0.028083898670301616}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23659856282659097
Fold 2 IBS: 0.2153141906947614
Fold 3 IBS: 0.2047151307497504
Fold 4 IBS: 0.22602716181430646
Fold 5 IBS: 0.21120163992617527
[I 2024-04-18 15:15:22,280] Trial 24 finished with value: 0.21877133720231692 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 495, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5266956821498789, 'min_weight_fraction_leaf': 0.09390422583252539}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23844194453158782
Fold 2 IBS: 0.22105165705465776
Fold 3 IBS: 0.2170232482052371
Fold 4 IBS: 0.23092368220074286
Fold 5 IBS: 0.2182289218147539
[I 2024-04-18 15:15:26,973] Trial 25 finished with value: 0.22513389076139587 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8933482791661949, 'min_weight_fraction_leaf': 0.13197369292803862}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23843041914620997
Fold 2 IBS: 0.21493453665123136
Fold 3 IBS: 0.2090168989775049
Fold 4 IBS: 0.2254910625046002
Fold 5 IBS: 0.20756991091332164
[I 2024-04-18 15:15:31,780] Trial 26 finished with value: 0.21908856563857357 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 347, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7414002668859774, 'min_weight_fraction_leaf': 0.026829572042154526}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2509863618363121
Fold 2 IBS: 0.22583805299486692
Fold 3 IBS: 0.21561349580190237
Fold 4 IBS: 0.23472261674578385
Fold 5 IBS: 0.20529371711830646
[I 2024-04-18 15:15:36,378] Trial 27 finished with value: 0.22649084889943433 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8390104664094136, 'min_weight_fraction_leaf': 0.10855414664475099}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2365772151298969
Fold 2 IBS: 0.22063815968102357
Fold 3 IBS: 0.2096147193508314
Fold 4 IBS: 0.23073997606593633
Fold 5 IBS: 0.21495122402474376
[I 2024-04-18 15:15:39,423] Trial 28 finished with value: 0.22250425885048636 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7007032081941286, 'min_weight_fraction_leaf': 0.26392524970352815}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24016407858058467
Fold 2 IBS: 0.2226945998414404
Fold 3 IBS: 0.1982935820263817
Fold 4 IBS: 0.22729610646127874
Fold 5 IBS: 0.20737931045192012
[I 2024-04-18 15:15:44,743] Trial 29 finished with value: 0.21916553547232112 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 410, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5262281274916285, 'min_weight_fraction_leaf': 0.17911878131541542}. Best is trial 6 with value: 0.21817221600733724.

Fold 1 IBS: 0.24654710532719232
Fold 2 IBS: 0.23226075421028072
Fold 3 IBS: 0.22941657391206893
Fold 4 IBS: 0.24156072638580853
Fold 5 IBS: 0.23017807225897458
[I 2024-04-18 15:15:46,952] Trial 30 finished with value: 0.235992646418865 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 225, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.46244718326068934, 'min_weight_fraction_leaf': 0.23846812660748434}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23751141455085345
Fold 2 IBS: 0.2151581315756588
Fold 3 IBS: 0.20565940925991258
Fold 4 IBS: 0.22542469872025206
Fold 5 IBS: 0.21030193870732267
[I 2024-04-18 15:15:52,593] Trial 31 finished with value: 0.2188111185627999 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5225620293165905, 'min_weight_fraction_leaf': 0.08868790596579997}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2381102203756688
Fold 2 IBS: 0.21526872502739017
Fold 3 IBS: 0.20815181349325143
Fold 4 IBS: 0.22568325207479042
Fold 5 IBS: 0.20752434700582614
[I 2024-04-18 15:15:57,192] Trial 32 finished with value: 0.2189476715953854 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 469, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6456061991595886, 'min_weight_fraction_leaf': 0.06162501081375873}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23538871189809704
Fold 2 IBS: 0.2182700935995022
Fold 3 IBS: 0.20730561342400977
Fold 4 IBS: 0.22803214159636556
Fold 5 IBS: 0.21291133753496125
[I 2024-04-18 15:16:02,512] Trial 33 finished with value: 0.22038157961058716 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 448, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.3962727024860553, 'min_weight_fraction_leaf': 0.11192391268789204}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23769165649579538
Fold 2 IBS: 0.21962693726644614
Fold 3 IBS: 0.21516823698710888
Fold 4 IBS: 0.22823472000435138
Fold 5 IBS: 0.21587988525872873
[I 2024-04-18 15:16:08,151] Trial 34 finished with value: 0.22332028720248612 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.48343209841746304, 'min_weight_fraction_leaf': 0.037167307803865623}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23862457868154657
Fold 2 IBS: 0.2142812234274352
Fold 3 IBS: 0.2071122831600512
Fold 4 IBS: 0.22647037485357482
Fold 5 IBS: 0.20820984278000723
[I 2024-04-18 15:16:13,103] Trial 35 finished with value: 0.218939660580523 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 394, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6000897439208172, 'min_weight_fraction_leaf': 0.0750146307727606}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23527534950071421
Fold 2 IBS: 0.21770457187441952
Fold 3 IBS: 0.20717349733261567
Fold 4 IBS: 0.22755601352686636
Fold 5 IBS: 0.21265069320216293
[I 2024-04-18 15:16:17,928] Trial 36 finished with value: 0.22007202508735574 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 442, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6131815692772876, 'min_weight_fraction_leaf': 0.1532744134723093}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24634031246577748
Fold 2 IBS: 0.23214260646544588
Fold 3 IBS: 0.2295950257561111
Fold 4 IBS: 0.24153927533138653
Fold 5 IBS: 0.2302443599910423
[I 2024-04-18 15:16:23,246] Trial 37 finished with value: 0.23597231600195262 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7619772249693068, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24216929138044868
Fold 2 IBS: 0.2271496608003459
Fold 3 IBS: 0.2224602263879355
Fold 4 IBS: 0.23789330129911662
Fold 5 IBS: 0.22532476564253662
[I 2024-04-18 15:16:28,975] Trial 38 finished with value: 0.23099944910207665 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 430, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6857951951640623, 'min_weight_fraction_leaf': 0.32409862457821353}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24627778387618462
Fold 2 IBS: 0.2322366961912888
Fold 3 IBS: 0.2296783065766575
Fold 4 IBS: 0.241413702842104
Fold 5 IBS: 0.2304581252108405
[I 2024-04-18 15:16:34,027] Trial 39 finished with value: 0.23601292293941506 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 481, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.2617193500766202, 'min_weight_fraction_leaf': 0.4166327790117036}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24943554696253312
Fold 2 IBS: 0.2275875045421105
Fold 3 IBS: 0.21215397389232193
Fold 4 IBS: 0.22982351135831186
Fold 5 IBS: 0.20097345883924955
[I 2024-04-18 15:16:37,916] Trial 40 finished with value: 0.22399479911890538 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 340, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5581919117237532, 'min_weight_fraction_leaf': 0.017165868694093697}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23914122142491184
Fold 2 IBS: 0.2147947351479995
Fold 3 IBS: 0.20776744684188206
Fold 4 IBS: 0.22457253880359845
Fold 5 IBS: 0.20865162921459607
[I 2024-04-18 15:16:42,770] Trial 41 finished with value: 0.2189855142865976 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 416, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7054883344953605, 'min_weight_fraction_leaf': 0.0896503362548107}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24271681884333898
Fold 2 IBS: 0.21620524856789322
Fold 3 IBS: 0.20723319617238797
Fold 4 IBS: 0.22507744594615037
Fold 5 IBS: 0.20484080364572635
[I 2024-04-18 15:16:47,096] Trial 42 finished with value: 0.21921470263509937 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 390, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8078708827436648, 'min_weight_fraction_leaf': 0.0480179528132343}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23614234446632862
Fold 2 IBS: 0.2146862138202214
Fold 3 IBS: 0.20617547040696596
Fold 4 IBS: 0.226976210049578
Fold 5 IBS: 0.2094767772998351
[I 2024-04-18 15:16:52,113] Trial 43 finished with value: 0.21869140320858582 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 434, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7262220752056259, 'min_weight_fraction_leaf': 0.12503295394556485}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23675493441717185
Fold 2 IBS: 0.2143052777671278
Fold 3 IBS: 0.20680963951540962
Fold 4 IBS: 0.22648948216139728
Fold 5 IBS: 0.20900398384520574
[I 2024-04-18 15:16:56,201] Trial 44 finished with value: 0.21867266354126244 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7563092184910359, 'min_weight_fraction_leaf': 0.12319485729503299}. Best is trial 6 with value: 0.21817221600733724.

Fold 1 IBS: 0.23579057506686668
Fold 2 IBS: 0.21781214726067985
Fold 3 IBS: 0.2066254011517932
Fold 4 IBS: 0.22753811203645144
Fold 5 IBS: 0.2131782901601682
[I 2024-04-18 15:17:00,604] Trial 45 finished with value: 0.22018890513519188 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 367, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7526038702156265, 'min_weight_fraction_leaf': 0.19723066794982302}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23864304620933718
Fold 2 IBS: 0.2216376067444548
Fold 3 IBS: 0.21798786862601383
Fold 4 IBS: 0.2317000936375164
Fold 5 IBS: 0.21855619191514636
[I 2024-04-18 15:17:05,258] Trial 46 finished with value: 0.2257049614264937 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 306, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8402191071167949, 'min_weight_fraction_leaf': 0.12410909471677475}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23563878904947858
Fold 2 IBS: 0.21424725828314625
Fold 3 IBS: 0.20539301573051336
Fold 4 IBS: 0.22686230831823445
Fold 5 IBS: 0.21106465433851035
[I 2024-04-18 15:17:08,303] Trial 47 finished with value: 0.2186412051439766 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 7, 'n_estimators': 256, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9648698685623813, 'min_weight_fraction_leaf': 0.16386048493715183}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23608296665281833
Fold 2 IBS: 0.21410238497896242
Fold 3 IBS: 0.20759570708434993
Fold 4 IBS: 0.22790237489945422
Fold 5 IBS: 0.21118066940259758
[I 2024-04-18 15:17:10,628] Trial 48 finished with value: 0.2193728206036365 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 188, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.964673069944489, 'min_weight_fraction_leaf': 0.15970031084197556}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23586798809596576
Fold 2 IBS: 0.2171901907305398
Fold 3 IBS: 0.20638917135134097
Fold 4 IBS: 0.22790269105933317
Fold 5 IBS: 0.2131331876876173
[I 2024-04-18 15:17:13,444] Trial 49 finished with value: 0.2200966457849594 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 257, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9370518091082483, 'min_weight_fraction_leaf': 0.2212372080269228}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23566720165017685
Fold 2 IBS: 0.21702158501775817
Fold 3 IBS: 0.20777305870793225
Fold 4 IBS: 0.2289923684746406
Fold 5 IBS: 0.2123285283685948
[I 2024-04-18 15:17:15,334] Trial 50 finished with value: 0.22035654844382052 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 131, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7996006309622741, 'min_weight_fraction_leaf': 0.17451620167795343}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23643320426918235
Fold 2 IBS: 0.21452872036487017
Fold 3 IBS: 0.2061667514710548
Fold 4 IBS: 0.22716532577885723
Fold 5 IBS: 0.2093136543684702
[I 2024-04-18 15:17:19,584] Trial 51 finished with value: 0.21872153125048693 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 369, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7348857113190044, 'min_weight_fraction_leaf': 0.12368563758615428}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23641193294091017
Fold 2 IBS: 0.21396216666253828
Fold 3 IBS: 0.205078775294875
Fold 4 IBS: 0.22790849339614294
Fold 5 IBS: 0.2096794545069518
[I 2024-04-18 15:17:23,147] Trial 52 finished with value: 0.21860816456028367 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 326, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8372294381144086, 'min_weight_fraction_leaf': 0.13938540553402562}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23760005782394428
Fold 2 IBS: 0.21366875869042135
Fold 3 IBS: 0.2069623183595147
Fold 4 IBS: 0.22721569193756555
Fold 5 IBS: 0.20902507159737838
[I 2024-04-18 15:17:26,607] Trial 53 finished with value: 0.21889437968176484 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 281, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.918667808078992, 'min_weight_fraction_leaf': 0.14156648297373461}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23620472019948477
Fold 2 IBS: 0.21446966517909544
Fold 3 IBS: 0.20562206377402104
Fold 4 IBS: 0.22725639394503946
Fold 5 IBS: 0.20996519098311808
[I 2024-04-18 15:17:29,383] Trial 54 finished with value: 0.21870360681615178 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8358880541378728, 'min_weight_fraction_leaf': 0.1455563484516374}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23778194706641292
Fold 2 IBS: 0.21478977024089968
Fold 3 IBS: 0.20765830208854946
Fold 4 IBS: 0.22627231039017479
Fold 5 IBS: 0.2078669168201539
[I 2024-04-18 15:17:33,000] Trial 55 finished with value: 0.21887384932123818 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 323, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7851303591277253, 'min_weight_fraction_leaf': 0.06284510067118923}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.238318805600092
Fold 2 IBS: 0.22036985262615907
Fold 3 IBS: 0.2165992463216147
Fold 4 IBS: 0.2309266992996685
Fold 5 IBS: 0.21739689485405828
[I 2024-04-18 15:17:37,701] Trial 56 finished with value: 0.2247222997403185 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 355, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8589971174200165, 'min_weight_fraction_leaf': 0.005571180329296155}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23762260324765577
Fold 2 IBS: 0.21419387527655073
Fold 3 IBS: 0.20857668730339252
Fold 4 IBS: 0.22634390477297547
Fold 5 IBS: 0.20826155026277154
[I 2024-04-18 15:17:41,853] Trial 57 finished with value: 0.2189997241726692 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 293, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9941137040048004, 'min_weight_fraction_leaf': 0.10935256889677493}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24142086672900914
Fold 2 IBS: 0.2243832837390074
Fold 3 IBS: 0.20244005121729616
Fold 4 IBS: 0.22860275074756728
Fold 5 IBS: 0.20676442441603726
[I 2024-04-18 15:17:45,820] Trial 58 finished with value: 0.22072227536978345 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 341, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6659973923607253, 'min_weight_fraction_leaf': 0.19865253699408333}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23558756630217798
Fold 2 IBS: 0.21872232455633453
Fold 3 IBS: 0.20756590838487826
Fold 4 IBS: 0.2282798830709085
Fold 5 IBS: 0.21390900413228608
[I 2024-04-18 15:17:48,741] Trial 59 finished with value: 0.2208129372893171 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 271, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9225473764084263, 'min_weight_fraction_leaf': 0.28011468219630264}. Best is trial 6 with value: 0.21817221600733724.

Fold 1 IBS: 0.23905204688392212
Fold 2 IBS: 0.2187928517163343
Fold 3 IBS: 0.2102452041922602
Fold 4 IBS: 0.22890896945323644
Fold 5 IBS: 0.21433456345556318
[I 2024-04-18 15:17:49,789] Trial 60 finished with value: 0.22226672714026327 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 74, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9528336631358474, 'min_weight_fraction_leaf': 0.23484468684942653}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23541239037810044
Fold 2 IBS: 0.2157600681640186
Fold 3 IBS: 0.20665073702737224
Fold 4 IBS: 0.22705259747647938
Fold 5 IBS: 0.2114858383168534
[I 2024-04-18 15:17:55,160] Trial 61 finished with value: 0.21927232627256482 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 397, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6192920945584268, 'min_weight_fraction_leaf': 0.13261707538267872}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23553068478795697
Fold 2 IBS: 0.21690255883493398
Fold 3 IBS: 0.20634487576033259
Fold 4 IBS: 0.227390495160599
Fold 5 IBS: 0.21190307127879016
[I 2024-04-18 15:18:00,509] Trial 62 finished with value: 0.21961433716452256 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 444, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7228469890997942, 'min_weight_fraction_leaf': 0.16736170087898403}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23652120509947278
Fold 2 IBS: 0.21376852115432401
Fold 3 IBS: 0.20590736185366215
Fold 4 IBS: 0.22699281211564268
Fold 5 IBS: 0.2094937208444956
[I 2024-04-18 15:18:04,874] Trial 63 finished with value: 0.2185367242135195 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 380, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6675371718016896, 'min_weight_fraction_leaf': 0.10480172755123676}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23556228893011497
Fold 2 IBS: 0.22097929403924785
Fold 3 IBS: 0.20991652841690608
Fold 4 IBS: 0.2296617728771541
Fold 5 IBS: 0.21512411988151653
[I 2024-04-18 15:18:08,331] Trial 64 finished with value: 0.22224880082898793 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 3, 'n_estimators': 369, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6610936151946805, 'min_weight_fraction_leaf': 0.09922302854842845}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23828246171159492
Fold 2 IBS: 0.21557851298857106
Fold 3 IBS: 0.20938151683259248
Fold 4 IBS: 0.22533438744263723
Fold 5 IBS: 0.20920540651145889
[I 2024-04-18 15:18:10,852] Trial 65 finished with value: 0.21955645709737087 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 242, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.823446469666347, 'min_weight_fraction_leaf': 0.07059854704611815}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2364200039869531
Fold 2 IBS: 0.21438646307876086
Fold 3 IBS: 0.20573630300522222
Fold 4 IBS: 0.22702368533407957
Fold 5 IBS: 0.20961076514490226
[I 2024-04-18 15:18:15,359] Trial 66 finished with value: 0.2186354441099836 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 379, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5869176122888681, 'min_weight_fraction_leaf': 0.05075696238467242}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23639124735172928
Fold 2 IBS: 0.2145484268675974
Fold 3 IBS: 0.20522813470743728
Fold 4 IBS: 0.22671398387649164
Fold 5 IBS: 0.20934855998582716
[I 2024-04-18 15:18:21,853] Trial 67 finished with value: 0.21844607055781656 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 326, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6356340227566255, 'min_weight_fraction_leaf': 0.03968181972003887}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23657271370449404
Fold 2 IBS: 0.21804029729496446
Fold 3 IBS: 0.21045719072119984
Fold 4 IBS: 0.2270147984171555
Fold 5 IBS: 0.213512706028707
[I 2024-04-18 15:18:27,255] Trial 68 finished with value: 0.22111954123330416 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 315, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.574503516485792, 'min_weight_fraction_leaf': 0.0441948101443752}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23598252320933685
Fold 2 IBS: 0.21474373579441428
Fold 3 IBS: 0.20474033641872114
Fold 4 IBS: 0.22554630026453992
Fold 5 IBS: 0.21094491625082956
[I 2024-04-18 15:18:32,534] Trial 69 finished with value: 0.21839156238756835 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 330, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5838727235518294, 'min_weight_fraction_leaf': 0.024189353275833377}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23541761150477072
Fold 2 IBS: 0.21830744523559634
Fold 3 IBS: 0.2065414367985132
Fold 4 IBS: 0.22779205930266125
Fold 5 IBS: 0.21304401731614925
[I 2024-04-18 15:18:37,110] Trial 70 finished with value: 0.22022051403153814 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 335, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5116435605570427, 'min_weight_fraction_leaf': 0.025472119814750907}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2358050847465658
Fold 2 IBS: 0.21505617907633484
Fold 3 IBS: 0.20632041460134462
Fold 4 IBS: 0.2262324750390269
Fold 5 IBS: 0.20987569816898008
[I 2024-04-18 15:18:42,875] Trial 71 finished with value: 0.21865797032645046 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 385, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6369371661585259, 'min_weight_fraction_leaf': 0.011093571416785707}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23555223944807405
Fold 2 IBS: 0.21551046958229766
Fold 3 IBS: 0.2060538064107946
Fold 4 IBS: 0.2274823152167951
Fold 5 IBS: 0.21116980752977293
[I 2024-04-18 15:18:51,415] Trial 72 finished with value: 0.21915372763754687 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 407, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5939045307255605, 'min_weight_fraction_leaf': 0.034792886918428814}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23670318238684077
Fold 2 IBS: 0.2153132925145203
Fold 3 IBS: 0.20537237654935647
Fold 4 IBS: 0.2261310221764691
Fold 5 IBS: 0.21018749868962947
[I 2024-04-18 15:18:59,219] Trial 73 finished with value: 0.2187414744633632 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 304, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5785149488517107, 'min_weight_fraction_leaf': 0.05575349496200409}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23543448543686032
Fold 2 IBS: 0.21561006254005735
Fold 3 IBS: 0.20561005286053105
Fold 4 IBS: 0.22653019867698856
Fold 5 IBS: 0.21093122079808987
[I 2024-04-18 15:19:14,054] Trial 74 finished with value: 0.2188232040625054 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 327, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5392437858799007, 'min_weight_fraction_leaf': 0.020895543222114732}. Best is trial 6 with value: 0.21817221600733724.

Fold 1 IBS: 0.23749669116970254
Fold 2 IBS: 0.21417891364052918
Fold 3 IBS: 0.2066472918191204
Fold 4 IBS: 0.22577332010612122
Fold 5 IBS: 0.20791194308464916
[I 2024-04-18 15:19:20,271] Trial 75 finished with value: 0.2184016319640245 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 346, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6413926717278569, 'min_weight_fraction_leaf': 0.0007388507314896667}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23958121408927258
Fold 2 IBS: 0.21329051656876732
Fold 3 IBS: 0.20685348469946407
Fold 4 IBS: 0.2243628744610485
Fold 5 IBS: 0.2076885994354418
[I 2024-04-18 15:19:26,337] Trial 76 finished with value: 0.21835533785079883 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 356, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6743039221296488, 'min_weight_fraction_leaf': 0.07601195190861526}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24100163497067753
Fold 2 IBS: 0.21650889905387713
Fold 3 IBS: 0.21047274820869846
Fold 4 IBS: 0.22336649691832314
Fold 5 IBS: 0.20606715188435837
[I 2024-04-18 15:19:32,503] Trial 77 finished with value: 0.2194833862071869 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 358, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.632010203513251, 'min_weight_fraction_leaf': 0.001409785112660406}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23901813243753778
Fold 2 IBS: 0.21420034022703563
Fold 3 IBS: 0.20592138789952324
Fold 4 IBS: 0.2261656080238036
Fold 5 IBS: 0.20847447185713558
[I 2024-04-18 15:19:37,522] Trial 78 finished with value: 0.21875598808900715 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 323, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6857241761843896, 'min_weight_fraction_leaf': 0.0754366403965388}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23824458885708127
Fold 2 IBS: 0.21347939433681554
Fold 3 IBS: 0.2058991068238864
Fold 4 IBS: 0.2257803593854211
Fold 5 IBS: 0.20757894565473192
[I 2024-04-18 15:19:42,845] Trial 79 finished with value: 0.21819647901158726 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6608586112588376, 'min_weight_fraction_leaf': 0.08475815384047584}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2388143640724499
Fold 2 IBS: 0.21348020253653477
Fold 3 IBS: 0.20624726345211883
Fold 4 IBS: 0.22435505289042332
Fold 5 IBS: 0.208351275464022
[I 2024-04-18 15:19:48,406] Trial 80 finished with value: 0.2182496316831098 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 349, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5516495369043533, 'min_weight_fraction_leaf': 0.03371312562357193}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24069746455152283
Fold 2 IBS: 0.21539743059063785
Fold 3 IBS: 0.20826874922746164
Fold 4 IBS: 0.22473981003915017
Fold 5 IBS: 0.20649625442496652
[I 2024-04-18 15:19:53,825] Trial 81 finished with value: 0.21911994176674782 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 347, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6667332489251124, 'min_weight_fraction_leaf': 0.03652699788238737}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23772500283463666
Fold 2 IBS: 0.21351832416489283
Fold 3 IBS: 0.20551287071766666
Fold 4 IBS: 0.22528179451336483
Fold 5 IBS: 0.20855127007502566
[I 2024-04-18 15:19:58,786] Trial 82 finished with value: 0.2181178524611173 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 348, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4957463321896789, 'min_weight_fraction_leaf': 0.06535039686542465}. Best is trial 82 with value: 0.2181178524611173.
Fold 1 IBS: 0.24006097861784914
Fold 2 IBS: 0.21351296780007356
Fold 3 IBS: 0.20665204769701515
Fold 4 IBS: 0.22153407083328364
Fold 5 IBS: 0.20571739381784554
[I 2024-04-18 15:20:03,468] Trial 83 finished with value: 0.21749549175321342 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 351, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.44903497421134486, 'min_weight_fraction_leaf': 0.018023565445760347}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.24023569962199984
Fold 2 IBS: 0.21363622543199387
Fold 3 IBS: 0.2069585793435229
Fold 4 IBS: 0.2235635832191918
Fold 5 IBS: 0.2050944469518296
[I 2024-04-18 15:20:07,779] Trial 84 finished with value: 0.21789770691370763 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 354, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.44193402534807985, 'min_weight_fraction_leaf': 0.01787990099131466}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23894349587532945
Fold 2 IBS: 0.21620007594047472
Fold 3 IBS: 0.20751928103028916
Fold 4 IBS: 0.22372208334469412
Fold 5 IBS: 0.20582866480542367
[I 2024-04-18 15:20:12,236] Trial 85 finished with value: 0.2184427201992422 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 355, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.3945684829871626, 'min_weight_fraction_leaf': 0.018652438671265613}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23559845633067017
Fold 2 IBS: 0.21576618470285996
Fold 3 IBS: 0.20576607771200886
Fold 4 IBS: 0.22613316143073034
Fold 5 IBS: 0.21134237173993053
[I 2024-04-18 15:20:17,479] Trial 86 finished with value: 0.21892125038323998 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 397, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.44101859255864206, 'min_weight_fraction_leaf': 0.08385023506766573}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23685696539925846
Fold 2 IBS: 0.21480550862098527
Fold 3 IBS: 0.20596316091401243
Fold 4 IBS: 0.22582554770569668
Fold 5 IBS: 0.2089870418983674
[I 2024-04-18 15:20:23,287] Trial 87 finished with value: 0.2184876449076641 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 420, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.49032987293693886, 'min_weight_fraction_leaf': 0.06537420951395731}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.2372362315378745
Fold 2 IBS: 0.2141070051769487
Fold 3 IBS: 0.20515302733265592
Fold 4 IBS: 0.2254353766941232
Fold 5 IBS: 0.20982062489373873
[I 2024-04-18 15:20:27,749] Trial 88 finished with value: 0.2183504531270682 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 299, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.45867249639615437, 'min_weight_fraction_leaf': 0.055491708389874855}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23930793105990758
Fold 2 IBS: 0.21398355058184887
Fold 3 IBS: 0.2034152708638187
Fold 4 IBS: 0.22450497150068674
Fold 5 IBS: 0.20720970388342935
[I 2024-04-18 15:20:32,672] Trial 89 finished with value: 0.21768428557793826 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 294, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4321447624251241, 'min_weight_fraction_leaf': 0.05093978805292204}. Best is trial 83 with value: 0.21749549175321342.

Fold 1 IBS: 0.23843719064657817
Fold 2 IBS: 0.22064066243477068
Fold 3 IBS: 0.216117076423818
Fold 4 IBS: 0.23057174337958733
Fold 5 IBS: 0.21778600564999445
[I 2024-04-18 15:20:38,175] Trial 90 finished with value: 0.22471053570694974 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 274, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.42143690848778903, 'min_weight_fraction_leaf': 0.05305541913345835}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23636584853089593
Fold 2 IBS: 0.2160409129934387
Fold 3 IBS: 0.20518796152371307
Fold 4 IBS: 0.22686151762465062
Fold 5 IBS: 0.21138354158709388
[I 2024-04-18 15:20:43,146] Trial 91 finished with value: 0.21916795645195847 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 307, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.37885824272597207, 'min_weight_fraction_leaf': 0.0831355986175214}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23869477691909374
Fold 2 IBS: 0.21407356247574796
Fold 3 IBS: 0.2063518174852807
Fold 4 IBS: 0.22368052234862068
Fold 5 IBS: 0.20756617101134753
[I 2024-04-18 15:20:47,793] Trial 92 finished with value: 0.2180733700480181 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4717145746375765, 'min_weight_fraction_leaf': 0.031712424866108854}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23869477691909374
Fold 2 IBS: 0.21407356247574796
Fold 3 IBS: 0.2063518174852807
Fold 4 IBS: 0.2237085330935343
Fold 5 IBS: 0.20694772259468203
[I 2024-04-18 15:20:52,647] Trial 93 finished with value: 0.21795528251366775 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4672728524116875, 'min_weight_fraction_leaf': 0.011059612031062777}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23858095515316086
Fold 2 IBS: 0.21975164781209036
Fold 3 IBS: 0.21722961929030632
Fold 4 IBS: 0.23057130141512497
Fold 5 IBS: 0.21784545833330082
[I 2024-04-18 15:20:58,181] Trial 94 finished with value: 0.22479579640079664 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 315, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.34867843816025107, 'min_weight_fraction_leaf': 0.013031969056652583}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23786209898582975
Fold 2 IBS: 0.2150246994268266
Fold 3 IBS: 0.20529156517436606
Fold 4 IBS: 0.2250763776849818
Fold 5 IBS: 0.20845810397098258
[I 2024-04-18 15:21:03,031] Trial 95 finished with value: 0.21834256904859733 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 294, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4856085412705134, 'min_weight_fraction_leaf': 0.030125050021992245}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.25267952707924435
Fold 2 IBS: 0.22364036179533292
Fold 3 IBS: 0.21566522864655932
Fold 4 IBS: 0.2292360749986461
Fold 5 IBS: 0.20654056894732276
[I 2024-04-18 15:21:07,532] Trial 96 finished with value: 0.22555235229342108 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 286, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.432713162272765, 'min_weight_fraction_leaf': 0.038949501159838834}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23908189486059475
Fold 2 IBS: 0.21347457197868566
Fold 3 IBS: 0.2065066620897382
Fold 4 IBS: 0.22345877259235025
Fold 5 IBS: 0.20703900436678677
[I 2024-04-18 15:21:11,743] Trial 97 finished with value: 0.21791218117763114 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 245, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5036752163248778, 'min_weight_fraction_leaf': 0.009154320648984412}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.24118706264822834
Fold 2 IBS: 0.21292192130006443
Fold 3 IBS: 0.20750976633197557
Fold 4 IBS: 0.22523921978728415
Fold 5 IBS: 0.20766529155252064
[I 2024-04-18 15:21:14,555] Trial 98 finished with value: 0.21890465232401463 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 175, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5009566699282665, 'min_weight_fraction_leaf': 0.011093124694056673}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23852012019920124
Fold 2 IBS: 0.2149463648078171
Fold 3 IBS: 0.20528180370133903
Fold 4 IBS: 0.22528602680304402
Fold 5 IBS: 0.20818529472185981
[I 2024-04-18 15:21:18,376] Trial 99 finished with value: 0.21844392204665222 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 241, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4667379070625426, 'min_weight_fraction_leaf': 0.04638622319247108}. Best is trial 83 with value: 0.21749549175321342.


* Best trial for IBS:
 FrozenTrial(number=83, state=TrialState.COMPLETE, values=[0.21749549175321342], datetime_start=datetime.datetime(2024, 4, 18, 15, 19, 58, 836903), datetime_complete=datetime.datetime(2024, 4, 18, 15, 20, 3, 467582), params={'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 351, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.44903497421134486, 'min_weight_fraction_leaf': 0.018023565445760347}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=83, value=None)


* Best Score for IBS:
 0.21749549175321342

In [64]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [65]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.791
train_ibs:  0.217

#### Test

In [66]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [67]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=13, max_features=None, max_leaf_nodes=16,
                   max_samples=0.8020091028727125, min_samples_leaf=1,
                   min_samples_split=5,
                   min_weight_fraction_leaf=0.002435943155287043,
                   n_estimators=277, random_state=123, warm_start=True)

C-index score: 0.584

ExtraSurvivalTrees(max_depth=6, max_features='auto', max_leaf_nodes=16,
                   max_samples=0.44903497421134486, min_samples_leaf=4,
                   min_samples_split=9,
                   min_weight_fraction_leaf=0.018023565445760347,
                   n_estimators=351, oob_score=True, random_state=123)

IBS: 0.223

In [68]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [69]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 15:21:20,989] A new study created in memory with name: no-name-c762fb50-0b55-44f9-b26b-e074962e3a33

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:21:45,037] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:21:59,450] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:22:14,690] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:22:50,784] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:22:59,563] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:23:01,700] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:23:22,732] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:23:28,466] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:23:29,095] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6115879828326181
[I 2024-04-18 15:24:23,768] Trial 9 finished with value: 0.6015092457236193 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6015092457236193.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5
Fold 5 C-index: 0.592274678111588
[I 2024-04-18 15:25:44,683] Trial 10 finished with value: 0.5915509861883201 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6015092457236193.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:27:26,914] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6015092457236193.
Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6234042553191489
Fold 4 C-index: 0.5950570342205324
Fold 5 C-index: 0.6051502145922747
[I 2024-04-18 15:28:43,300] Trial 12 finished with value: 0.6059172111077464 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.6059172111077464.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:29:26,477] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:30:34,567] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:31:25,431] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:32:06,952] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:33:47,708] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:36:50,924] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:36:56,068] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:37:49,987] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:39:24,999] Trial 21 finished with value: 0.5 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5756972111553785
Fold 2 C-index: 0.6182170542635659
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.6596958174904943
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 15:40:31,940] Trial 22 finished with value: 0.6190116704947725 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:41:30,417] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:42:23,650] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:43:04,077] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:44:32,845] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:46:19,623] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:47:29,732] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:48:19,404] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:49:29,917] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:53:10,415] Trial 31 finished with value: 0.5071713147410358 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:55:39,094] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:57:26,871] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:00:34,905] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:01:09,162] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:04:53,697] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:04:59,045] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.6190116704947725.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:06:21,971] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:08:55,867] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:12:41,053] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.592274678111588
[I 2024-04-18 16:12:41,722] Trial 41 finished with value: 0.6039152174760968 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 16:13:05,063] Trial 42 finished with value: 0.624004230389207 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 42 with value: 0.624004230389207.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:13:06,348] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8735505723796891, 'learning_rate': 0.013455915558851193, 'dropout_rate': 0.11585930219083569, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 1.1546454041172216, 'min_weight_fraction_leaf': 0.4571018098895751, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8650432234384267, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 42 with value: 0.624004230389207.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:14:39,848] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9479336661285427, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.25335630680617827, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.4126953497238681, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.9438667820963776, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 42 with value: 0.624004230389207.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.6106382978723405
Fold 4 C-index: 0.6520912547528517
Fold 5 C-index: 0.6502145922746781
[I 2024-04-18 16:15:01,192] Trial 45 finished with value: 0.6250855089268532 and parameters: {'subsample': 0.5852424762732177, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.027804703729289008, 'min_weight_fraction_leaf': 0.262143273989599, 'max_features': 0.1, 'min_impurity_decrease': 9.467252666446998e-07, 'validation_fraction': 0.7243304021069044, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 45 with value: 0.6250855089268532.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:15:06,149] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.9097609675058456, 'learning_rate': 0.0647255784094387, 'dropout_rate': 0.9694253886674298, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 1.980441868470768, 'min_weight_fraction_leaf': 0.14203864492290658, 'max_features': 0.1, 'min_impurity_decrease': 2.8410487814192134e-06, 'validation_fraction': 0.7106683919659889, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 45 with value: 0.6250855089268532.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:15:42,816] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7952252972868074, 'learning_rate': 0.06333641179361332, 'dropout_rate': 0.20821540657294882, 'n_estimators': 172, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.38084444238994586, 'max_features': 0.1, 'min_impurity_decrease': 9.138461248752069e-07, 'validation_fraction': 0.8268165634838988, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 45 with value: 0.6250855089268532.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:15:53,533] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.5738829075301064, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.10579627176846597, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 0.443834316760607, 'min_weight_fraction_leaf': 0.2606631581830996, 'max_features': 0.1, 'min_impurity_decrease': 1.7788082392529892e-06, 'validation_fraction': 0.9003040994071866, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 17}. Best is trial 45 with value: 0.6250855089268532.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:15:54,716] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.84002245104845, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.17475217298119933, 'n_estimators': 9, 'criterion': 'friedman_mse', 'ccp_alpha': 1.370081088125734, 'min_weight_fraction_leaf': 0.21302024967189928, 'max_features': 0.1, 'min_impurity_decrease': 5.682612317450774e-06, 'validation_fraction': 0.8796670771312719, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 45 with value: 0.6250855089268532.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:15:59,097] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.9569410534968725, 'learning_rate': 0.07076395585024155, 'dropout_rate': 0.1405973314616702, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 1.7468603849227415, 'min_weight_fraction_leaf': 0.34344615267586504, 'max_features': 'log2', 'min_impurity_decrease': 1.89164645743038e-07, 'validation_fraction': 0.9611752371540778, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 45 with value: 0.6250855089268532.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 16:16:21,697] Trial 51 finished with value: 0.6344575916797196 and parameters: {'subsample': 0.4994582407940605, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.25361909697654017, 'n_estimators': 129, 'criterion': 'squared_error', 'ccp_alpha': 0.012243801070742757, 'min_weight_fraction_leaf': 0.30447335075613347, 'max_features': 'sqrt', 'min_impurity_decrease': 2.4617573739462015e-07, 'validation_fraction': 0.6627564435796373, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6520912547528517
Fold 5 C-index: 0.5815450643776824
[I 2024-04-18 16:16:39,633] Trial 52 finished with value: 0.6158557441321629 and parameters: {'subsample': 0.44756554166704604, 'learning_rate': 0.008555924871488166, 'dropout_rate': 0.22725206143365784, 'n_estimators': 109, 'criterion': 'squared_error', 'ccp_alpha': 0.03659945835027755, 'min_weight_fraction_leaf': 0.3136607614940329, 'max_features': 'sqrt', 'min_impurity_decrease': 2.38579101418113e-07, 'validation_fraction': 0.7452334109475507, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:17:01,718] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.45456603531105677, 'learning_rate': 0.057410108721501936, 'dropout_rate': 0.26583914946975784, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.4512041233232864, 'min_weight_fraction_leaf': 0.322074381929077, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0763963055081505e-06, 'validation_fraction': 0.6719316415566533, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:17:15,605] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.3984239460158819, 'learning_rate': 0.04823958197178553, 'dropout_rate': 0.37643214321044394, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 1.035069386526868, 'min_weight_fraction_leaf': 0.3013557556478156, 'max_features': 'sqrt', 'min_impurity_decrease': 2.871532477136697e-07, 'validation_fraction': 0.7420090012406269, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 9}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:17:36,312] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.5149754707590405, 'learning_rate': 0.006385731999605383, 'dropout_rate': 0.6373222391006226, 'n_estimators': 162, 'criterion': 'squared_error', 'ccp_alpha': 0.40074886285106287, 'min_weight_fraction_leaf': 0.22397272730341306, 'max_features': 'sqrt', 'min_impurity_decrease': 4.865634973369653e-07, 'validation_fraction': 0.7914357885759697, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:18:30,321] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.3411127486659095, 'learning_rate': 0.0223321562225781, 'dropout_rate': 0.23958844776950744, 'n_estimators': 188, 'criterion': 'squared_error', 'ccp_alpha': 1.2616701535027603, 'min_weight_fraction_leaf': 0.2741716094683543, 'max_features': 'sqrt', 'min_impurity_decrease': 2.219911700968688e-06, 'validation_fraction': 0.6090555519050711, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6596958174904943
Fold 5 C-index: 0.6180257510729614
[I 2024-04-18 16:18:36,064] Trial 57 finished with value: 0.6424069440095804 and parameters: {'subsample': 0.569175138136116, 'learning_rate': 0.09542136158814303, 'dropout_rate': 0.43613571687055647, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.0019473494055538935, 'min_weight_fraction_leaf': 0.36743918461462793, 'max_features': 'sqrt', 'min_impurity_decrease': 5.255459802548745e-07, 'validation_fraction': 0.7087056989518657, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 20}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:18:41,025] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.5648293474899495, 'learning_rate': 0.09980513755713626, 'dropout_rate': 0.5821753276684661, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.7470877807882045, 'min_weight_fraction_leaf': 0.33458212087172423, 'max_features': 'sqrt', 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.5649807819209639, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:19:04,968] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.43657835102234843, 'learning_rate': 0.08992223472821356, 'dropout_rate': 0.45063277335330026, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.8838088337816697, 'min_weight_fraction_leaf': 0.3051539123714827, 'max_features': 'sqrt', 'min_impurity_decrease': 6.123519561880064e-07, 'validation_fraction': 0.7025023924419704, 'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 20}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:19:14,685] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.49892638282698937, 'learning_rate': 0.0441252798316586, 'dropout_rate': 0.5171243893297963, 'n_estimators': 89, 'criterion': 'squared_error', 'ccp_alpha': 7.88888123252141, 'min_weight_fraction_leaf': 0.3630725265151832, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6800306990539567e-07, 'validation_fraction': 0.8258586719391796, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:19:23,145] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.2369113884490353, 'learning_rate': 0.08271570541393714, 'dropout_rate': 0.21451691891174118, 'n_estimators': 40, 'criterion': 'squared_error', 'ccp_alpha': 0.2307646041947069, 'min_weight_fraction_leaf': 0.26954907827809993, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1677029771075378e-06, 'validation_fraction': 0.7413035176238272, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 57 with value: 0.6424069440095804.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.6178707224334601
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 16:19:58,737] Trial 62 finished with value: 0.6243825724756604 and parameters: {'subsample': 0.5324319523145695, 'learning_rate': 0.01643486305639612, 'dropout_rate': 0.3264939129108728, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.022616672247981386, 'min_weight_fraction_leaf': 0.24162423168473884, 'max_features': 'sqrt', 'min_impurity_decrease': 5.949284725634976e-07, 'validation_fraction': 0.7732655768872577, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6254752851711026
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 16:20:18,474] Trial 63 finished with value: 0.6275044157901222 and parameters: {'subsample': 0.5420606625212961, 'learning_rate': 0.018319064135809617, 'dropout_rate': 0.3312179790226355, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 0.017289191017379774, 'min_weight_fraction_leaf': 0.2368022589799896, 'max_features': 'sqrt', 'min_impurity_decrease': 4.941106122111233e-07, 'validation_fraction': 0.7618939807885664, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:20:42,659] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.5922191157066728, 'learning_rate': 0.017442858716414014, 'dropout_rate': 0.3280178810362676, 'n_estimators': 137, 'criterion': 'squared_error', 'ccp_alpha': 0.3667438715407871, 'min_weight_fraction_leaf': 0.19573629323082295, 'max_features': 'sqrt', 'min_impurity_decrease': 5.391394394336536e-07, 'validation_fraction': 0.6858072881143848, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:21:52,090] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.48392926174632367, 'learning_rate': 0.04244875829612528, 'dropout_rate': 0.3644612457920643, 'n_estimators': 225, 'criterion': 'squared_error', 'ccp_alpha': 0.8992306864937782, 'min_weight_fraction_leaf': 0.2385628804937077, 'max_features': 'sqrt', 'min_impurity_decrease': 3.55046666349273e-07, 'validation_fraction': 0.6309388168212643, 'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:21:59,236] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.5415215192588256, 'learning_rate': 0.032278253162939315, 'dropout_rate': 0.2844754557689118, 'n_estimators': 60, 'criterion': 'squared_error', 'ccp_alpha': 1.407601455379467, 'min_weight_fraction_leaf': 0.2510619510668375, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00014974488025406402, 'validation_fraction': 0.7825933436627104, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:22:39,356] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.6358167678362362, 'learning_rate': 0.052737313658130634, 'dropout_rate': 0.4387694424787056, 'n_estimators': 188, 'criterion': 'squared_error', 'ccp_alpha': 2.352310671798754, 'min_weight_fraction_leaf': 0.4545757099622538, 'max_features': None, 'min_impurity_decrease': 1.818488684973112e-07, 'validation_fraction': 0.5736474971004745, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 13}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:24:05,037] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.5249117222273245, 'learning_rate': 0.02490094836729529, 'dropout_rate': 0.3029637523703682, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.761492090851228, 'min_weight_fraction_leaf': 0.4129240385085172, 'max_features': 1, 'min_impurity_decrease': 7.239759479397451e-07, 'validation_fraction': 0.845785642913146, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:24:31,777] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.4231153746657399, 'learning_rate': 0.08902302640166725, 'dropout_rate': 0.40768620718532717, 'n_estimators': 166, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2840361129928317, 'min_weight_fraction_leaf': 0.1815547729555989, 'max_features': 'sqrt', 'min_impurity_decrease': 2.2923196091933695e-06, 'validation_fraction': 0.7183772506352457, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 12}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.5680851063829787
Fold 4 C-index: 0.6863117870722434
Fold 5 C-index: 0.5643776824034334
[I 2024-04-18 16:24:39,323] Trial 70 finished with value: 0.6131109792873616 and parameters: {'subsample': 0.33926313482601156, 'learning_rate': 0.019557263454050858, 'dropout_rate': 0.49890266623764207, 'n_estimators': 82, 'criterion': 'squared_error', 'ccp_alpha': 0.010011659094920826, 'min_weight_fraction_leaf': 0.2259853620596431, 'max_features': 0.1, 'min_impurity_decrease': 1.094279318090133e-06, 'validation_fraction': 0.6723348434604305, 'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.6155378486055777
Fold 2 C-index: 0.6337209302325582
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.5793991416309013
[I 2024-04-18 16:24:56,160] Trial 71 finished with value: 0.6343473918763494 and parameters: {'subsample': 0.37769079309242687, 'learning_rate': 0.00898995266126416, 'dropout_rate': 0.18684567840646416, 'n_estimators': 111, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.2872834031528035, 'max_features': 'sqrt', 'min_impurity_decrease': 2.080456918420355e-07, 'validation_fraction': 0.7690867806326959, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:25:14,398] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.37701900413921136, 'learning_rate': 0.016833919347681435, 'dropout_rate': 0.18636370764084237, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 0.6310212945452622, 'min_weight_fraction_leaf': 0.2884483320093426, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0402177319970213e-07, 'validation_fraction': 0.7660591402491591, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:25:37,958] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.5806779434269143, 'learning_rate': 0.009384484820913017, 'dropout_rate': 0.2682030763817523, 'n_estimators': 135, 'criterion': 'squared_error', 'ccp_alpha': 0.3563872779387915, 'min_weight_fraction_leaf': 0.259787767977606, 'max_features': 'sqrt', 'min_impurity_decrease': 4.1043899443022785e-07, 'validation_fraction': 0.8108999742101972, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 9}. Best is trial 57 with value: 0.6424069440095804.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:25:54,575] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.6195349553052544, 'learning_rate': 0.01136765941654159, 'dropout_rate': 0.12372380197953392, 'n_estimators': 99, 'criterion': 'squared_error', 'ccp_alpha': 1.1402294929472836, 'min_weight_fraction_leaf': 0.37161644050250525, 'max_features': 'log2', 'min_impurity_decrease': 1.932478849268343e-07, 'validation_fraction': 0.7239713755732545, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5278884462151394
Fold 2 C-index: 0.5872093023255814
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.5722433460076045
Fold 5 C-index: 0.5493562231759657
[I 2024-04-18 16:26:25,075] Trial 75 finished with value: 0.5681905273746455 and parameters: {'subsample': 0.481615373319732, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.3420562942089014, 'n_estimators': 159, 'criterion': 'squared_error', 'ccp_alpha': 0.008766214931211122, 'min_weight_fraction_leaf': 0.47835629989654377, 'max_features': 'sqrt', 'min_impurity_decrease': 5.88233573662372e-07, 'validation_fraction': 0.8876968664466519, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:26:57,346] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.5506572145582509, 'learning_rate': 0.005104240606853081, 'dropout_rate': 0.19147377223567788, 'n_estimators': 146, 'criterion': 'squared_error', 'ccp_alpha': 0.6753331414033272, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'sqrt', 'min_impurity_decrease': 1.568348033519598e-07, 'validation_fraction': 0.6381650425348908, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:27:05,908] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.256547470779639, 'learning_rate': 0.02789039050974412, 'dropout_rate': 0.2363063686780326, 'n_estimators': 69, 'criterion': 'squared_error', 'ccp_alpha': 0.32932872552363307, 'min_weight_fraction_leaf': 0.34020173052241, 'max_features': 'sqrt', 'min_impurity_decrease': 3.0905215746242485e-07, 'validation_fraction': 0.8500050308736237, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 12}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:27:11,628] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.17121169705944425, 'learning_rate': 0.022303437932065042, 'dropout_rate': 0.16630563053057534, 'n_estimators': 52, 'criterion': 'squared_error', 'ccp_alpha': 0.9868372140949613, 'min_weight_fraction_leaf': 0.28173667841308647, 'max_features': None, 'min_impurity_decrease': 1.436695348567125e-06, 'validation_fraction': 0.7954229312058925, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:27:17,019] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.6599350427093886, 'learning_rate': 0.013036654559152646, 'dropout_rate': 0.8831816560103296, 'n_estimators': 93, 'criterion': 'squared_error', 'ccp_alpha': 1.6751129651593017, 'min_weight_fraction_leaf': 0.441581660587461, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.7645264662223318, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:28:08,251] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.29977879304875465, 'learning_rate': 0.006859503090223374, 'dropout_rate': 0.3089173374536066, 'n_estimators': 202, 'criterion': 'friedman_mse', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.20378735965998926, 'max_features': 1, 'min_impurity_decrease': 5.0310685705020145e-06, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6137339055793991
[I 2024-04-18 16:28:26,338] Trial 81 finished with value: 0.6360661153873227 and parameters: {'subsample': 0.4294410193691395, 'learning_rate': 0.010148818964253115, 'dropout_rate': 0.23189880344496897, 'n_estimators': 114, 'criterion': 'squared_error', 'ccp_alpha': 0.025429683198128432, 'min_weight_fraction_leaf': 0.30380613582651383, 'max_features': 'sqrt', 'min_impurity_decrease': 2.4552322822660376e-07, 'validation_fraction': 0.7348375063409944, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:28:44,991] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.41270161792979404, 'learning_rate': 0.02035005618998148, 'dropout_rate': 0.2741217489218166, 'n_estimators': 114, 'criterion': 'squared_error', 'ccp_alpha': 0.243253320453856, 'min_weight_fraction_leaf': 0.2674089734554558, 'max_features': 'sqrt', 'min_impurity_decrease': 4.57052340801651e-07, 'validation_fraction': 0.6937562552377796, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:29:35,061] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.5052537047036201, 'learning_rate': 0.010871661810425969, 'dropout_rate': 0.21433250003236387, 'n_estimators': 180, 'criterion': 'squared_error', 'ccp_alpha': 0.6352435481431712, 'min_weight_fraction_leaf': 0.24349664772118904, 'max_features': 'sqrt', 'min_impurity_decrease': 8.314878942494555e-07, 'validation_fraction': 0.6632105320618724, 'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:30:07,927] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.46801301624877634, 'learning_rate': 0.007281884918593935, 'dropout_rate': 0.386804997704391, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 0.2606549578206887, 'min_weight_fraction_leaf': 0.2996691407738805, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5246790132091148e-07, 'validation_fraction': 0.818415857489097, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6180257510729614
[I 2024-04-18 16:30:34,805] Trial 85 finished with value: 0.6408591126992382 and parameters: {'subsample': 0.5964612356115859, 'learning_rate': 0.015720448140553796, 'dropout_rate': 0.13380585132498796, 'n_estimators': 123, 'criterion': 'squared_error', 'ccp_alpha': 0.011079581402843635, 'min_weight_fraction_leaf': 0.3295331769680571, 'max_features': 'sqrt', 'min_impurity_decrease': 3.208077039170617e-07, 'validation_fraction': 0.919249699407904, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 11}. Best is trial 57 with value: 0.6424069440095804.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:30:59,215] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.3685613574811818, 'learning_rate': 0.014486753241218515, 'dropout_rate': 0.11824930345826798, 'n_estimators': 125, 'criterion': 'squared_error', 'ccp_alpha': 0.6245182410574106, 'min_weight_fraction_leaf': 0.35109736831509497, 'max_features': 'sqrt', 'min_impurity_decrease': 2.86238317813556e-07, 'validation_fraction': 0.7634725122712285, 'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 11}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:31:01,674] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.6044611085530311, 'learning_rate': 0.01765378612903628, 'dropout_rate': 0.1306535468432557, 'n_estimators': 29, 'criterion': 'squared_error', 'ccp_alpha': 3.8278844875001683, 'min_weight_fraction_leaf': 0.3290577310546589, 'max_features': 'sqrt', 'min_impurity_decrease': 1.3023259584270306e-07, 'validation_fraction': 0.7251193103463489, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:31:12,103] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.7305989887750208, 'learning_rate': 0.07565138947019595, 'dropout_rate': 0.16203184683029326, 'n_estimators': 76, 'criterion': 'squared_error', 'ccp_alpha': 0.8448837855218826, 'min_weight_fraction_leaf': 0.3098036049135862, 'max_features': 'sqrt', 'min_impurity_decrease': 2.1424217279362014e-07, 'validation_fraction': 0.8675111855922717, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:31:26,160] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.5376836855244629, 'learning_rate': 0.0401442321523931, 'dropout_rate': 0.24626353925068137, 'n_estimators': 101, 'criterion': 'squared_error', 'ccp_alpha': 6.012071113382355, 'min_weight_fraction_leaf': 0.3790584148504035, 'max_features': 'sqrt', 'min_impurity_decrease': 5.180798001423693e-07, 'validation_fraction': 0.6163739621016452, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:31:54,006] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.5603501314738726, 'learning_rate': 0.07155480696569975, 'dropout_rate': 0.19017023137156536, 'n_estimators': 129, 'criterion': 'squared_error', 'ccp_alpha': 0.25113716915357387, 'min_weight_fraction_leaf': 0.29008477768989605, 'max_features': 'log2', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8289185301981673, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 12}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.5965665236051502
[I 2024-04-18 16:32:28,927] Trial 91 finished with value: 0.6369144725686089 and parameters: {'subsample': 0.5200014916305844, 'learning_rate': 0.004782889478178922, 'dropout_rate': 0.14625013043369223, 'n_estimators': 149, 'criterion': 'squared_error', 'ccp_alpha': 0.037948504220536555, 'min_weight_fraction_leaf': 0.32163517901334265, 'max_features': 0.1, 'min_impurity_decrease': 4.203506068959824e-07, 'validation_fraction': 0.928897907788923, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:32:55,162] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.516333042411373, 'learning_rate': 0.0032327242416098677, 'dropout_rate': 0.10130537225057253, 'n_estimators': 113, 'criterion': 'squared_error', 'ccp_alpha': 0.4942608677057209, 'min_weight_fraction_leaf': 0.31821001183548514, 'max_features': 0.1, 'min_impurity_decrease': 3.888780909297809e-07, 'validation_fraction': 0.9024177997549866, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5677290836653387
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6051502145922747
[I 2024-04-18 16:33:53,462] Trial 93 finished with value: 0.6306456063981358 and parameters: {'subsample': 0.4359031361693476, 'learning_rate': 0.004895517972361572, 'dropout_rate': 0.1441526685325705, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 0.047810054628039236, 'min_weight_fraction_leaf': 0.36100788200483613, 'max_features': 0.1, 'min_impurity_decrease': 7.26101398801591e-07, 'validation_fraction': 0.917180608138582, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:34:27,922] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.43676774220572834, 'learning_rate': 0.0014283823252091835, 'dropout_rate': 0.14353500981177236, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 0.23509570298593757, 'min_weight_fraction_leaf': 0.35954699845952287, 'max_features': 0.1, 'min_impurity_decrease': 9.183247049719965e-07, 'validation_fraction': 0.9236151177312523, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:34:42,256] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.5903496783457474, 'learning_rate': 0.005099830953329844, 'dropout_rate': 0.162877773773529, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 1.2276086602633303, 'min_weight_fraction_leaf': 0.29823606696595584, 'max_features': 0.1, 'min_impurity_decrease': 1.9705823014691884e-06, 'validation_fraction': 0.6868552600932708, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:35:34,805] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.48032209804466314, 'learning_rate': 0.009204991859439446, 'dropout_rate': 0.22878123115737428, 'n_estimators': 176, 'criterion': 'squared_error', 'ccp_alpha': 0.49661607876323316, 'min_weight_fraction_leaf': 0.335851906616388, 'max_features': 0.1, 'min_impurity_decrease': 6.786376565092662e-07, 'validation_fraction': 0.1680801488969631, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.5234042553191489
Fold 4 C-index: 0.5532319391634981
Fold 5 C-index: 0.5
[I 2024-04-18 16:36:16,323] Trial 97 finished with value: 0.5331566962608705 and parameters: {'subsample': 0.35982713220118606, 'learning_rate': 0.012532616836197621, 'dropout_rate': 0.2558374395640585, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.16939533233444498, 'min_weight_fraction_leaf': 0.22889025888481507, 'max_features': 0.1, 'min_impurity_decrease': 1.3919863121994274e-06, 'validation_fraction': 0.42127972174310685, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 57 with value: 0.6424069440095804.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:36:38,064] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.3929305772442687, 'learning_rate': 0.006887776697371318, 'dropout_rate': 0.19837547852725088, 'n_estimators': 102, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9847646950448454, 'min_weight_fraction_leaf': 0.2740519671350756, 'max_features': 0.1, 'min_impurity_decrease': 3.145177514431871e-06, 'validation_fraction': 0.9698443216047068, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.6330798479087453

[I 2024-04-18 16:36:58,651] A new study created in memory with name: no-name-8b1ce166-78cd-4c29-a0f4-7ecf79f8507c

Fold 5 C-index: 0.6223175965665236
[I 2024-04-18 16:36:58,631] Trial 99 finished with value: 0.6324701656733438 and parameters: {'subsample': 0.5315382628188576, 'learning_rate': 0.06087517452189459, 'dropout_rate': 0.3597460411167791, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 0.004509101673084638, 'min_weight_fraction_leaf': 0.3464439813387543, 'max_features': 0.1, 'min_impurity_decrease': 0.006030292379694477, 'validation_fraction': 0.5851189485426918, 'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.


* Best trial for C-index:
 FrozenTrial(number=57, state=TrialState.COMPLETE, values=[0.6424069440095804], datetime_start=datetime.datetime(2024, 4, 18, 16, 18, 30, 331060), datetime_complete=datetime.datetime(2024, 4, 18, 16, 18, 36, 63719), params={'subsample': 0.569175138136116, 'learning_rate': 0.09542136158814303, 'dropout_rate': 0.43613571687055647, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.0019473494055538935, 'min_weight_fraction_leaf': 0.36743918461462793, 'max_features': 'sqrt', 'min_impurity_decrease': 5.255459802548745e-07, 'validation_fraction': 0.7087056989518657, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 20}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=57, value=None)


* Best Score for C-index:
 0.6424069440095804

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:39:04,403] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:40:39,723] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:41:55,410] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 16:44:01,076] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:44:56,291] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:45:10,943] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:47:18,839] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:47:48,705] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:47:52,934] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.2468985899268434
Fold 2 IBS: 0.23174237938551043
Fold 3 IBS: 0.22871218710228966
Fold 4 IBS: 0.24178909744475294
Fold 5 IBS: 0.22900564758396305
[I 2024-04-18 16:52:51,718] Trial 9 finished with value: 0.23562958028867192 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24711653291675975
Fold 2 IBS: 0.23202162954629
Fold 3 IBS: 0.2289556964425975
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293716647928885
[I 2024-04-18 17:02:32,201] Trial 10 finished with value: 0.23588805903156138 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 17:13:01,745] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24719666836842055
Fold 2 IBS: 0.23199892761841134
Fold 3 IBS: 0.2289405059322678
Fold 4 IBS: 0.24195423740028718
Fold 5 IBS: 0.22934315929810337
[I 2024-04-18 17:21:29,170] Trial 12 finished with value: 0.23588669972349807 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 17:25:46,277] Trial 13 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 17:31:51,921] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 17:37:06,220] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 17:40:53,106] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 17:48:26,308] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 17:58:15,101] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 17:58:37,167] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 18:02:21,585] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 18:10:33,819] Trial 21 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24675967400526397
Fold 2 IBS: 0.23120128338106113

Fold 3 IBS: 0.22848569735194738
Fold 4 IBS: 0.24150141767716396
Fold 5 IBS: 0.22845766625525668
[I 2024-04-18 18:17:53,601] Trial 22 finished with value: 0.23528114773413863 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 18:24:05,603] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-18 18:29:36,596] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 18:33:19,457] Trial 25 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 18:40:19,148] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 18:47:37,879] Trial 27 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 18:54:27,094] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 18:58:15,549] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 19:03:02,989] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24723811107199292
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 19:13:09,180] Trial 31 finished with value: 0.23592604563741132 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 19:20:24,811] Trial 32 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 19:24:07,498] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:48:55,552] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:50:13,040] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:54:56,137] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:55:04,589] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:57:18,633] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 21:00:25,816] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:05:18,831] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.2472010209971281
Fold 2 IBS: 0.23197319933729893
Fold 3 IBS: 0.22887452934644678
Fold 4 IBS: 0.24191861956639799
Fold 5 IBS: 0.2293015642651888
[I 2024-04-18 21:05:19,797] Trial 41 finished with value: 0.23585378670249213 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.2459047520616606
Fold 2 IBS: 0.23020388607917422
Fold 3 IBS: 0.22657568837307415
Fold 4 IBS: 0.24022980115273948
Fold 5 IBS: 0.22694242307333995
[I 2024-04-18 21:05:52,627] Trial 42 finished with value: 0.2339713101479977 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:05:54,441] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8735505723796891, 'learning_rate': 0.013455915558851193, 'dropout_rate': 0.11585930219083569, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 1.1546454041172216, 'min_weight_fraction_leaf': 0.4571018098895751, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8650432234384267, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:07:17,374] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9479336661285427, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.25335630680617827, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.4126953497238681, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.9438667820963776, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24678393645753394
Fold 2 IBS: 0.23045362112354736
Fold 3 IBS: 0.22798640772703402
Fold 4 IBS: 0.24133177588235574
Fold 5 IBS: 0.22819468131537443
[I 2024-04-18 21:07:45,006] Trial 45 finished with value: 0.2349500845011691 and parameters: {'subsample': 0.5852424762732177, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.027804703729289008, 'min_weight_fraction_leaf': 0.262143273989599, 'max_features': 0.1, 'min_impurity_decrease': 9.467252666446998e-07, 'validation_fraction': 0.7243304021069044, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:07:51,862] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.0647255784094387, 'dropout_rate': 0.9694253886674298, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 1.980441868470768, 'min_weight_fraction_leaf': 0.3747732962598691, 'max_features': 0.1, 'min_impurity_decrease': 2.6164901943280044e-07, 'validation_fraction': 0.7149599360255287, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:08:40,390] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.45583884600027197, 'learning_rate': 0.06333641179361332, 'dropout_rate': 0.19790330487666663, 'n_estimators': 172, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.3462595663974316, 'max_features': 0.1, 'min_impurity_decrease': 9.138461248752069e-07, 'validation_fraction': 0.6499098781754827, 'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:08:53,621] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.584713932884162, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.10579627176846597, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 0.443834316760607, 'min_weight_fraction_leaf': 0.26066789839492466, 'max_features': 0.1, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.5884862057231304, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 21:08:55,111] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5232490206634685, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 9, 'criterion': 'friedman_mse', 'ccp_alpha': 1.370081088125734, 'min_weight_fraction_leaf': 0.3097478284829108, 'max_features': 0.1, 'min_impurity_decrease': 2.368978679128857e-06, 'validation_fraction': 0.8421492954769574, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 21:08:59,298] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.07076395585024155, 'dropout_rate': 0.14893065487391582, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 1.7468603849227415, 'min_weight_fraction_leaf': 0.4771102452497172, 'max_features': 'log2', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.6959936026682685, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24710183923742374
Fold 2 IBS: 0.23175516862597736
Fold 3 IBS: 0.22872726460533319
Fold 4 IBS: 0.24175918635636237
Fold 5 IBS: 0.22914324520488263
[I 2024-04-18 21:09:27,388] Trial 51 finished with value: 0.23569734080599586 and parameters: {'subsample': 0.7946888792311653, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.2196446942108301, 'n_estimators': 129, 'criterion': 'squared_error', 'ccp_alpha': 0.012243801070742757, 'min_weight_fraction_leaf': 0.22002902120871776, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0321764873923598e-06, 'validation_fraction': 0.8872414026388215, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.2467504042903887
Fold 2 IBS: 0.23152649383902565
Fold 3 IBS: 0.2284064999332893
Fold 4 IBS: 0.2415574346408676
Fold 5 IBS: 0.22865959236570862
[I 2024-04-18 21:09:48,176] Trial 52 finished with value: 0.23538008501385596 and parameters: {'subsample': 0.7293363088819711, 'learning_rate': 0.021613492744160495, 'dropout_rate': 0.21988140341808987, 'n_estimators': 109, 'criterion': 'squared_error', 'ccp_alpha': 0.03659945835027755, 'min_weight_fraction_leaf': 0.21454208459463384, 'max_features': 'sqrt', 'min_impurity_decrease': 4.968003047339178e-07, 'validation_fraction': 0.7452334109475507, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:10:12,946] Trial 53 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7286313887376499, 'learning_rate': 0.057410108721501936, 'dropout_rate': 0.285096973056326, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.4512041233232864, 'min_weight_fraction_leaf': 0.2260580293041923, 'max_features': 'sqrt', 'min_impurity_decrease': 9.58735442301899e-07, 'validation_fraction': 0.810021403108459, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:10:34,678] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6569229035185145, 'learning_rate': 0.04372807230380943, 'dropout_rate': 0.21137526606647042, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 1.035069386526868, 'min_weight_fraction_leaf': 0.15200254659099177, 'max_features': 'sqrt', 'min_impurity_decrease': 3.9827268139860795e-07, 'validation_fraction': 0.7420090012406269, 'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:11:18,360] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.804828042321909, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.23926982708415356, 'n_estimators': 162, 'criterion': 'squared_error', 'ccp_alpha': 0.40074886285106287, 'min_weight_fraction_leaf': 0.2779066644542128, 'max_features': 'sqrt', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:12:14,552] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6106355356441384, 'learning_rate': 0.0175381503002972, 'dropout_rate': 0.1840399348615831, 'n_estimators': 188, 'criterion': 'squared_error', 'ccp_alpha': 1.2616701535027603, 'min_weight_fraction_leaf': 0.21267322167989086, 'max_features': 'sqrt', 'min_impurity_decrease': 4.6036201699627165e-06, 'validation_fraction': 0.6710340937437342, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:12:22,684] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7251306188899954, 'learning_rate': 0.031631325965124225, 'dropout_rate': 0.36858678707018233, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.8632300312068857, 'min_weight_fraction_leaf': 0.25226351016663784, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8530056448822852e-06, 'validation_fraction': 0.6117070368402964, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 20}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.2456293079267213
Fold 2 IBS: 0.23038922499302464
Fold 3 IBS: 0.22713476978355554
Fold 4 IBS: 0.24079478344550373
Fold 5 IBS: 0.22706044770206701
[I 2024-04-18 21:12:52,863] Trial 58 finished with value: 0.23420170677017443 and parameters: {'subsample': 0.8372135933826973, 'learning_rate': 0.0933118263896949, 'dropout_rate': 0.2698372192490325, 'n_estimators': 138, 'criterion': 'squared_error', 'ccp_alpha': 0.03851666886580376, 'min_weight_fraction_leaf': 0.19014956845126402, 'max_features': 'sqrt', 'min_impurity_decrease': 5.557667048245938e-07, 'validation_fraction': 0.8240957175887902, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:13:58,356] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8351680604992443, 'learning_rate': 0.09222489059205219, 'dropout_rate': 0.32342587723509275, 'n_estimators': 216, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.20200402270044698, 'max_features': None, 'min_impurity_decrease': 5.478860708687417e-07, 'validation_fraction': 0.7661283095999878, 'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:14:29,181] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9139271726204243, 'learning_rate': 0.09814896745797415, 'dropout_rate': 0.2791298710059678, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.7777615027127565, 'min_weight_fraction_leaf': 0.18715715168296215, 'max_features': 'sqrt', 'min_impurity_decrease': 2.755622066697515e-07, 'validation_fraction': 0.8258586719391796, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 10}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:14:44,370] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7785463441250284, 'learning_rate': 0.08303647143365385, 'dropout_rate': 0.22635143149642775, 'n_estimators': 90, 'criterion': 'squared_error', 'ccp_alpha': 0.3409580267399826, 'min_weight_fraction_leaf': 0.13431472354808824, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1489427281229002e-06, 'validation_fraction': 0.7271755608042784, 'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24566332108161124
Fold 2 IBS: 0.2296487832881736
Fold 3 IBS: 0.22657619429377132
Fold 4 IBS: 0.2401398958324181
Fold 5 IBS: 0.22612790182462805
[I 2024-04-18 21:15:10,198] Trial 62 finished with value: 0.23363121926412048 and parameters: {'subsample': 0.8243414389621114, 'learning_rate': 0.09071124103540035, 'dropout_rate': 0.27251764057548483, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.022616672247981386, 'min_weight_fraction_leaf': 0.2309588671101351, 'max_features': 'sqrt', 'min_impurity_decrease': 5.801680351688828e-07, 'validation_fraction': 0.7943107726663929, 'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 62 with value: 0.23363121926412048.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 21:15:27,147] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8543251428514922, 'learning_rate': 0.09031916747519456, 'dropout_rate': 0.4465947499448344, 'n_estimators': 113, 'criterion': 'squared_error', 'ccp_alpha': 0.31975094212728505, 'min_weight_fraction_leaf': 0.2681954377550372, 'max_features': 'sqrt', 'min_impurity_decrease': 5.414928507269899e-07, 'validation_fraction': 0.7758979815787878, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 62 with value: 0.23363121926412048.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:16:19,026] Trial 64 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8301134299030771, 'learning_rate': 0.089407762408853, 'dropout_rate': 0.2603466948459836, 'n_estimators': 184, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.1898937646969936, 'max_features': 'sqrt', 'min_impurity_decrease': 1.69586486321652e-07, 'validation_fraction': 0.7972553997617144, 'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 62 with value: 0.23363121926412048.
Fold 1 IBS: 0.245287081913879
Fold 2 IBS: 0.2284909088203171
Fold 3 IBS: 0.22546650692785086
Fold 4 IBS: 0.2392357717231768
Fold 5 IBS: 0.2267792173870292
[I 2024-04-18 21:16:58,015] Trial 65 finished with value: 0.2330518973544506 and parameters: {'subsample': 0.7342676747848801, 'learning_rate': 0.09901078905928126, 'dropout_rate': 0.18564802790799603, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 0.0027779871092218425, 'min_weight_fraction_leaf': 0.23644250991622312, 'max_features': 1, 'min_impurity_decrease': 2.467126073460528e-06, 'validation_fraction': 0.6850220941695035, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.2289818680697771
Fold 4 IBS: 0.24197477145927113

Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 21:17:40,977] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7279386202897999, 'learning_rate': 0.09984676062907398, 'dropout_rate': 0.12777796849617917, 'n_estimators': 154, 'criterion': 'squared_error', 'ccp_alpha': 1.4111498627316026, 'min_weight_fraction_leaf': 0.23517339076530247, 'max_features': 1, 'min_impurity_decrease': 0.00014974488025406402, 'validation_fraction': 0.6772907402354433, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:17:46,449] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8919877355885673, 'learning_rate': 0.08526801927485488, 'dropout_rate': 0.1968183597819077, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 2.319190851430798, 'min_weight_fraction_leaf': 0.15676195463630516, 'max_features': 1, 'min_impurity_decrease': 2.2029012366645964e-06, 'validation_fraction': 0.8599691724113316, 'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:46:12,940] Trial 68 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6777349272083631, 'learning_rate': 0.09580178908012703, 'dropout_rate': 0.17115105391870955, 'n_estimators': 231, 'criterion': 'squared_error', 'ccp_alpha': 1.05959995392391, 'min_weight_fraction_leaf': 0.09188917533116, 'max_features': 1, 'min_impurity_decrease': 6.249998507081008e-07, 'validation_fraction': 0.8273349120190413, 'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 21:46:56,850] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7597991740864205, 'learning_rate': 0.08587936719454789, 'dropout_rate': 0.3768812120719428, 'n_estimators': 171, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2840361129928317, 'min_weight_fraction_leaf': 0.18119508212683702, 'max_features': 1, 'min_impurity_decrease': 3.259077755824971e-06, 'validation_fraction': 0.5558704457196845, 'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.2457156227613367
Fold 2 IBS: 0.2288747857381832
Fold 3 IBS: 0.225909093321197
Fold 4 IBS: 0.23949137658530797
Fold 5 IBS: 0.22670374234424326
[I 2024-04-18 21:47:12,888] Trial 70 finished with value: 0.23333892415005364 and parameters: {'subsample': 0.9323981201987828, 'learning_rate': 0.07861759448846455, 'dropout_rate': 0.12174461012962215, 'n_estimators': 89, 'criterion': 'squared_error', 'ccp_alpha': 0.010268271623930566, 'min_weight_fraction_leaf': 0.29906629929043166, 'max_features': 0.1, 'min_impurity_decrease': 1.3730886680414553e-06, 'validation_fraction': 0.7403543339118751, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.2460308029540508
Fold 2 IBS: 0.23075747711272837
Fold 3 IBS: 0.22719882472016173
Fold 4 IBS: 0.24096869520763853
Fold 5 IBS: 0.22665684264377603
[I 2024-04-18 21:47:54,842] Trial 71 finished with value: 0.2343225285276711 and parameters: {'subsample': 0.942796279417179, 'learning_rate': 0.07656513395335908, 'dropout_rate': 0.12688691191107251, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.30325824379899113, 'max_features': 0.1, 'min_impurity_decrease': 1.7123721653367992e-06, 'validation_fraction': 0.7399374904297116, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-18 21:48:12,654] Trial 72 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.958795520357544, 'learning_rate': 0.07365043020696545, 'dropout_rate': 0.12090349350270674, 'n_estimators': 86, 'criterion': 'squared_error', 'ccp_alpha': 0.739835755767842, 'min_weight_fraction_leaf': 0.29749032069002146, 'max_features': 0.1, 'min_impurity_decrease': 1.3599018494932217e-06, 'validation_fraction': 0.7791089756643332, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:50:20,038] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9298981705927085, 'learning_rate': 0.08058367392340021, 'dropout_rate': 0.16799910589376849, 'n_estimators': 271, 'criterion': 'squared_error', 'ccp_alpha': 0.3563872779387915, 'min_weight_fraction_leaf': 0.3350043101424622, 'max_features': 0.1, 'min_impurity_decrease': 5.28840107794154e-06, 'validation_fraction': 0.7118987767425609, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 21:50:54,854] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8916344680923031, 'learning_rate': 0.08793435060481841, 'dropout_rate': 0.10110413499313342, 'n_estimators': 142, 'criterion': 'squared_error', 'ccp_alpha': 0.955935636717823, 'min_weight_fraction_leaf': 0.3070562089185398, 'max_features': 0.1, 'min_impurity_decrease': 1.6710911545904498e-05, 'validation_fraction': 0.9115868102366969, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 12}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24452621315746922
Fold 2 IBS: 0.22810872891299785
Fold 3 IBS: 0.2241439542595457
Fold 4 IBS: 0.23949321798155498
Fold 5 IBS: 0.2257119410390271
[I 2024-04-18 21:51:30,081] Trial 75 finished with value: 0.23239681107011897 and parameters: {'subsample': 0.9998829056403309, 'learning_rate': 0.09420039979456486, 'dropout_rate': 0.1333613034046263, 'n_estimators': 141, 'criterion': 'squared_error', 'ccp_alpha': 0.008911991304216094, 'min_weight_fraction_leaf': 0.2444025476799629, 'max_features': 0.1, 'min_impurity_decrease': 2.4912576060277585e-06, 'validation_fraction': 0.6909543967814417, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:51:38,402] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9458222668472541, 'learning_rate': 0.07906848506975149, 'dropout_rate': 0.14266874960530737, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.6031748128205076, 'min_weight_fraction_leaf': 0.2411911402976509, 'max_features': 0.1, 'min_impurity_decrease': 2.563792903899382e-06, 'validation_fraction': 0.6884030004704251, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:52:14,187] Trial 77 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9912462777341369, 'learning_rate': 0.09452937387896818, 'dropout_rate': 0.13177704633811047, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 1.5888723787914292, 'min_weight_fraction_leaf': 0.2769591062921376, 'max_features': 0.1, 'min_impurity_decrease': 9.102476550268499e-06, 'validation_fraction': 0.6136526230702399, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 75 with value: 0.23239681107011897.

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:53:15,791] Trial 78 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9982285661999424, 'learning_rate': 0.09191504218778693, 'dropout_rate': 0.15698726385072695, 'n_estimators': 197, 'criterion': 'squared_error', 'ccp_alpha': 0.24807516981478814, 'min_weight_fraction_leaf': 0.20156232220196313, 'max_features': 0.1, 'min_impurity_decrease': 1.657879625668623e-05, 'validation_fraction': 0.743279291715464, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 11}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24690614034739003
Fold 2 IBS: 0.23156150181893284
Fold 3 IBS: 0.22844484931909595
Fold 4 IBS: 0.24167312234765576
Fold 5 IBS: 0.22876368497640898
[I 2024-04-18 21:53:24,052] Trial 79 finished with value: 0.23546985976189672 and parameters: {'subsample': 0.8578713422305235, 'learning_rate': 0.0970337469468135, 'dropout_rate': 0.8831816560103296, 'n_estimators': 120, 'criterion': 'squared_error', 'ccp_alpha': 0.00580501385319391, 'min_weight_fraction_leaf': 0.3274569717263011, 'max_features': 0.1, 'min_impurity_decrease': 1.7968062948599964e-06, 'validation_fraction': 0.567470377276655, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 14}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:53:33,798] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9640129259774958, 'learning_rate': 0.07781759349237542, 'dropout_rate': 0.684566586558272, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 0.7103134936897181, 'min_weight_fraction_leaf': 0.2530944848473559, 'max_features': 0.1, 'min_impurity_decrease': 4.17669457184032e-06, 'validation_fraction': 0.6634556365644301, 'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:54:17,578] Trial 81 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9095916255797919, 'learning_rate': 0.06970654000824406, 'dropout_rate': 0.18983665066947678, 'n_estimators': 161, 'criterion': 'squared_error', 'ccp_alpha': 0.23038409491076217, 'min_weight_fraction_leaf': 0.36124689664050524, 'max_features': 0.1, 'min_impurity_decrease': 7.661014914528512e-07, 'validation_fraction': 0.8089217409847281, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 12}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:54:50,797] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9338187920159751, 'learning_rate': 0.09334088664924992, 'dropout_rate': 0.16946680359086888, 'n_estimators': 139, 'criterion': 'squared_error', 'ccp_alpha': 0.528502047033471, 'min_weight_fraction_leaf': 0.22951409277417695, 'max_features': 'log2', 'min_impurity_decrease': 2.9556370206003056e-07, 'validation_fraction': 0.8432783558982909, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:55:02,434] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.883398032137881, 'learning_rate': 0.05042245528279666, 'dropout_rate': 0.12497508422054361, 'n_estimators': 76, 'criterion': 'squared_error', 'ccp_alpha': 0.19969398360318116, 'min_weight_fraction_leaf': 0.2656518803329823, 'max_features': 0.1, 'min_impurity_decrease': 1.4194947389027638e-06, 'validation_fraction': 0.633183021479895, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:55:52,786] Trial 84 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8552741665580803, 'learning_rate': 0.06709189419275205, 'dropout_rate': 0.23596409865551865, 'n_estimators': 177, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.2944874209342843, 'max_features': None, 'min_impurity_decrease': 7.691172257857441e-07, 'validation_fraction': 0.6968576998921013, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:56:12,034] Trial 85 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8223616874820779, 'learning_rate': 0.08843920709680371, 'dropout_rate': 0.10332840309562857, 'n_estimators': 98, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9490091297259651, 'min_weight_fraction_leaf': 0.24536912526579052, 'max_features': 0.1, 'min_impurity_decrease': 3.7435209342302184e-07, 'validation_fraction': 0.8704001971002521, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:57:15,050] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9096448812228937, 'learning_rate': 0.07363090940287254, 'dropout_rate': 0.1771840613769105, 'n_estimators': 199, 'criterion': 'squared_error', 'ccp_alpha': 1.2822592490338325, 'min_weight_fraction_leaf': 0.4080356436151848, 'max_features': 1, 'min_impurity_decrease': 3.0373401514275998e-06, 'validation_fraction': 0.49985049424795125, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.2466123733468312
Fold 2 IBS: 0.2308311526549613
Fold 3 IBS: 0.2278158354955089
Fold 4 IBS: 0.24119742239323982
Fold 5 IBS: 0.22757911535557646
[I 2024-04-18 21:57:21,265] Trial 87 finished with value: 0.23480717984922356 and parameters: {'subsample': 0.9651104076885627, 'learning_rate': 0.08682198289446316, 'dropout_rate': 0.26100822710445604, 'n_estimators': 52, 'criterion': 'squared_error', 'ccp_alpha': 0.017727608136126588, 'min_weight_fraction_leaf': 0.2841999178157146, 'max_features': 0.1, 'min_impurity_decrease': 1.0918108718029517e-06, 'validation_fraction': 0.7910600961676841, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:57:27,981] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9779973422636488, 'learning_rate': 0.08293741938674638, 'dropout_rate': 0.3068106697632987, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.5807061908097002, 'min_weight_fraction_leaf': 0.28610769971029604, 'max_features': 0.1, 'min_impurity_decrease': 0.08546129120562182, 'validation_fraction': 0.7618563886319779, 'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:57:31,101] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9483409389571185, 'learning_rate': 0.08684995291290751, 'dropout_rate': 0.261199231115212, 'n_estimators': 33, 'criterion': 'squared_error', 'ccp_alpha': 0.262026471967215, 'min_weight_fraction_leaf': 0.30628737845191195, 'max_features': 0.1, 'min_impurity_decrease': 6.315494653924259e-06, 'validation_fraction': 0.7881463591488752, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 21:57:56,662] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9683729112775776, 'learning_rate': 0.09017482809200965, 'dropout_rate': 0.3433400840232137, 'n_estimators': 130, 'criterion': 'squared_error', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.008931419075771496, 'max_features': 0.1, 'min_impurity_decrease': 1.8289805873296154e-06, 'validation_fraction': 0.7322157194498431, 'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:58:17,844] Trial 91 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9249680605301084, 'learning_rate': 0.09924448444168336, 'dropout_rate': 0.20864759543371797, 'n_estimators': 111, 'criterion': 'squared_error', 'ccp_alpha': 5.764943688998855, 'min_weight_fraction_leaf': 0.26522934614572513, 'max_features': 0.1, 'min_impurity_decrease': 1.0288742383976442e-06, 'validation_fraction': 0.8977628160008819, 'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.2451397278492685
Fold 2 IBS: 0.2300786103624261
Fold 3 IBS: 0.22666393768691476
Fold 4 IBS: 0.24040348182140334
Fold 5 IBS: 0.2268793016048305
[I 2024-04-18 21:58:31,097] Trial 92 finished with value: 0.23383301186496866 and parameters: {'subsample': 0.873531926988483, 'learning_rate': 0.061855558095227366, 'dropout_rate': 0.15093910401977667, 'n_estimators': 81, 'criterion': 'squared_error', 'ccp_alpha': 0.04541226279610616, 'min_weight_fraction_leaf': 0.33303097856460795, 'max_features': 'log2', 'min_impurity_decrease': 2.092935799209152e-07, 'validation_fraction': 0.8296323120743014, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24512293945752534
Fold 2 IBS: 0.23019011787590957
Fold 3 IBS: 0.22745233212008534
Fold 4 IBS: 0.2407062153709357
Fold 5 IBS: 0.22743511430929209
[I 2024-04-18 21:58:43,747] Trial 93 finished with value: 0.23418134382674963 and parameters: {'subsample': 0.8748499727077871, 'learning_rate': 0.061988251437343184, 'dropout_rate': 0.13470215178905942, 'n_estimators': 79, 'criterion': 'squared_error', 'ccp_alpha': 0.04707905003515399, 'min_weight_fraction_leaf': 0.3395270240874814, 'max_features': 'log2', 'min_impurity_decrease': 1.9022958194070687e-07, 'validation_fraction': 0.8312538979092482, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:58:57,106] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7897088889184067, 'learning_rate': 0.0614181390618931, 'dropout_rate': 0.14297431919224673, 'n_estimators': 82, 'criterion': 'squared_error', 'ccp_alpha': 0.4431921498459426, 'min_weight_fraction_leaf': 0.3709400302504709, 'max_features': 'log2', 'min_impurity_decrease': 2.0363582833272814e-07, 'validation_fraction': 0.8286157671013741, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:59:03,547] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8731203767321374, 'learning_rate': 0.05536040983667881, 'dropout_rate': 0.1240871979011556, 'n_estimators': 51, 'criterion': 'squared_error', 'ccp_alpha': 0.7753599411924459, 'min_weight_fraction_leaf': 0.33956869589479877, 'max_features': 'log2', 'min_impurity_decrease': 1.5672686530530854e-07, 'validation_fraction': 0.8067764812355601, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:59:06,504] Trial 96 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8504494801502642, 'learning_rate': 0.049177216429585946, 'dropout_rate': 0.16179906586528384, 'n_estimators': 25, 'criterion': 'squared_error', 'ccp_alpha': 0.2411230962228951, 'min_weight_fraction_leaf': 0.33128063878378733, 'max_features': 'log2', 'min_impurity_decrease': 1.3361955454797523e-07, 'validation_fraction': 0.18910891405175134, 'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 11}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:59:23,659] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9456655169820907, 'learning_rate': 0.09471262982827017, 'dropout_rate': 0.1384749743969657, 'n_estimators': 95, 'criterion': 'squared_error', 'ccp_alpha': 1.0633542811136496, 'min_weight_fraction_leaf': 0.31666557556149805, 'max_features': 'log2', 'min_impurity_decrease': 4.764875181793167e-07, 'validation_fraction': 0.7602248674870157, 'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:59:34,406] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8985855612192725, 'learning_rate': 0.04236620589530157, 'dropout_rate': 0.10133681434331297, 'n_estimators': 71, 'criterion': 'friedman_mse', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.3508714202084142, 'max_features': 'log2', 'min_impurity_decrease': 2.1425287177415118e-07, 'validation_fraction': 0.846288087406783, 'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24494631432468708
Fold 2 IBS: 0.228838334401351
Fold 3 IBS: 0.22532457276154536
Fold 4 IBS: 0.24000051436574654
Fold 5 IBS: 0.22609554166201715
[I 2024-04-18 21:59:54,895] Trial 99 finished with value: 0.23304105550306944 and parameters: {'subsample': 0.9788274478205877, 'learning_rate': 0.06087517452189459, 'dropout_rate': 0.18468364581870436, 'n_estimators': 106, 'criterion': 'squared_error', 'ccp_alpha': 0.004542076222843278, 'min_weight_fraction_leaf': 0.30062558075883816, 'max_features': 'log2', 'min_impurity_decrease': 3.1109850934465047e-07, 'validation_fraction': 0.8728143595545029, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 75 with value: 0.23239681107011897.


* Best trial for IBS:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.23239681107011897], datetime_start=datetime.datetime(2024, 4, 18, 21, 50, 54, 860408), datetime_complete=datetime.datetime(2024, 4, 18, 21, 51, 30, 79703), params={'subsample': 0.9998829056403309, 'learning_rate': 0.09420039979456486, 'dropout_rate': 0.1333613034046263, 'n_estimators': 141, 'criterion': 'squared_error', 'ccp_alpha': 0.008911991304216094, 'min_weight_fraction_leaf': 0.2444025476799629, 'max_features': 0.1, 'min_impurity_decrease': 2.4912576060277585e-06, 'validation_fraction': 0.6909543967814417, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 14}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for IBS:
 0.23239681107011897

In [70]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [71]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.642
train_ibs:  0.232

#### Test

In [72]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [73]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.0019473494055538935,
                                 criterion='squared_error',
                                 dropout_rate=0.43613571687055647,
                                 learning_rate=0.09542136158814303,
                                 max_depth=20, max_features='sqrt',
                                 max_leaf_nodes=20,
                                 min_impurity_decrease=5.255459802548745e-07,
                                 min_samples_leaf=15, min_samples_split=10,
                                 min_weight_fraction_leaf=0.36743918461462793,
                                 n_estimators=66, random_state=123,
                                 subsample=0.569175138136116,
                                 validation_fraction=0.7087056989518657)

C-index score: 0.669

GradientBoostingSurvivalAnalysis(ccp_alpha=0.008911991304216094,
                                 criterion='squared_error',
                                 dropout_rate=0.1333613034046263,
                                 learning_rate=0.09420039979456486,
                                 max_depth=14, max_features=0.1,
                                 max_leaf_nodes=19,
                                 min_impurity_decrease=2.4912576060277585e-06,
                                 min_samples_leaf=17, min_samples_split=7,
                                 min_weight_fraction_leaf=0.2444025476799629,
                                 n_estimators=141, random_state=123,
                                 subsample=0.9998829056403309,
                                 validation_fraction=0.6909543967814417)

IBS: 0.224

In [74]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [75]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [76]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 22:00:04,159] A new study created in memory with name: no-name-823aea2a-1111-461e-a63b-5e50f3fc9011

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.4903100775193798
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5057034220532319
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 22:00:08,691] Trial 0 finished with value: 0.5414721792067407 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.5414721792067407.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.48643410852713176
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.49809885931558934
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 22:00:45,543] Trial 1 finished with value: 0.540034441959475 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.5414721792067407.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.5399239543726235
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 22:00:53,005] Trial 2 finished with value: 0.5643251101800817 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.5643251101800817.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 22:01:03,184] Trial 3 finished with value: 0.574635947709478 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.574635947709478.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 22:01:19,161] Trial 4 finished with value: 0.5794459521273788 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.5794459521273788.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.4941860465116279
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.4866920152091255
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 22:01:37,488] Trial 5 finished with value: 0.5507685637055392 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.5794459521273788.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.4828897338403042
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 22:01:46,268] Trial 6 finished with value: 0.5384598291610544 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.5794459521273788.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.501937984496124
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.5513307984790875
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 22:01:47,983] Trial 7 finished with value: 0.5732290603476148 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.5794459521273788.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.4941860465116279
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.5437262357414449
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 22:01:58,167] Trial 8 finished with value: 0.5643030673864711 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.5794459521273788.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.5399239543726235
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 22:02:25,007] Trial 9 finished with value: 0.5684630647993727 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.5794459521273788.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6437768240343348
[I 2024-04-18 22:02:44,861] Trial 10 finished with value: 0.5922563526057931 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.5922563526057931.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 22:03:07,879] Trial 11 finished with value: 0.5972470551408596 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.5972470551408596.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 22:03:30,053] Trial 12 finished with value: 0.5979858924640695 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5437262357414449
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 22:03:55,563] Trial 13 finished with value: 0.551485498639995 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 22:04:16,409] Trial 14 finished with value: 0.5962220814679517 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 22:04:36,037] Trial 15 finished with value: 0.5867615582410682 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 22:05:10,020] Trial 16 finished with value: 0.596276332548735 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:05:42,564] Trial 17 finished with value: 0.583607379652599 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 416, 'learning_rate': 0.08639690405722114}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 22:05:56,949] Trial 18 finished with value: 0.5762771630010592 and parameters: {'subsample': 0.35801092912005106, 'dropout_rate': 0.33602353085084236, 'n_estimators': 256, 'learning_rate': 0.08307767561539126}. Best is trial 12 with value: 0.5979858924640695.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5368217054263565
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.5513307984790875
Fold 5 C-index: 0.6523605150214592
[I 2024-04-18 22:06:01,796] Trial 19 finished with value: 0.5915543288002149 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7254192287154788, 'n_estimators': 117, 'learning_rate': 0.09614402133777997}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:06:36,305] Trial 20 finished with value: 0.589307741317726 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 423, 'learning_rate': 0.07788582119853761}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 22:07:12,793] Trial 21 finished with value: 0.5931617945031985 and parameters: {'subsample': 0.19686631492543752, 'dropout_rate': 0.12395834975058428, 'n_estimators': 431, 'learning_rate': 0.09000255639604265}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:07:34,672] Trial 22 finished with value: 0.5908581289146253 and parameters: {'subsample': 0.19525739351764543, 'dropout_rate': 0.10643415732680922, 'n_estimators': 323, 'learning_rate': 0.06478804138779268}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5290697674418605
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 22:08:03,591] Trial 23 finished with value: 0.5919736769442203 and parameters: {'subsample': 0.15450687211748398, 'dropout_rate': 0.342599622069399, 'n_estimators': 392, 'learning_rate': 0.09234244435311825}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:08:40,178] Trial 24 finished with value: 0.5853095073121735 and parameters: {'subsample': 0.29008587221754845, 'dropout_rate': 0.19210379926904825, 'n_estimators': 454, 'learning_rate': 0.08024945981885076}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6266094420600858
[I 2024-04-18 22:09:02,230] Trial 25 finished with value: 0.587363096170067 and parameters: {'subsample': 0.21578783290493656, 'dropout_rate': 0.2822107476217279, 'n_estimators': 332, 'learning_rate': 0.08776715920115916}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 22:09:18,110] Trial 26 finished with value: 0.5774863486807005 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.18335657306839728, 'n_estimators': 256, 'learning_rate': 0.09286780169440613}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:09:31,940] Trial 27 finished with value: 0.594201251727122 and parameters: {'subsample': 0.10030892385244675, 'dropout_rate': 0.9861686560685959, 'n_estimators': 297, 'learning_rate': 0.08003642459794733}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.6266094420600858
[I 2024-04-18 22:10:02,569] Trial 28 finished with value: 0.5850886087746433 and parameters: {'subsample': 0.23131169694169362, 'dropout_rate': 0.3042175373602061, 'n_estimators': 406, 'learning_rate': 0.04374297627981539}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.4941860465116279
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.4828897338403042
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 22:10:27,749] Trial 29 finished with value: 0.5376846353626048 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.41533846889329507, 'n_estimators': 380, 'learning_rate': 0.06046208382653473}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 22:10:39,471] Trial 30 finished with value: 0.5720644930478034 and parameters: {'subsample': 0.6390994990700434, 'dropout_rate': 0.10222887607777774, 'n_estimators': 221, 'learning_rate': 0.06770814359693789}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 22:11:00,079] Trial 31 finished with value: 0.5954284257998059 and parameters: {'subsample': 0.1336497656957349, 'dropout_rate': 0.6098507275286059, 'n_estimators': 348, 'learning_rate': 0.0939707622741704}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5329457364341085
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:11:15,706] Trial 32 finished with value: 0.5951533522633796 and parameters: {'subsample': 0.15588315806842334, 'dropout_rate': 0.7593875960500018, 'n_estimators': 294, 'learning_rate': 0.09970434470207828}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:11:38,095] Trial 33 finished with value: 0.595146647457943 and parameters: {'subsample': 0.10347108713547758, 'dropout_rate': 0.5342377484455041, 'n_estimators': 347, 'learning_rate': 0.09966997282956479}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5116279069767442
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:12:06,075] Trial 34 finished with value: 0.5788302275035859 and parameters: {'subsample': 0.3167716223614056, 'dropout_rate': 0.8012579754947401, 'n_estimators': 446, 'learning_rate': 0.07104054321866782}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5174418604651163
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:12:42,970] Trial 35 finished with value: 0.5889201444185013 and parameters: {'subsample': 0.22304468774944994, 'dropout_rate': 0.4749638754214781, 'n_estimators': 477, 'learning_rate': 0.07779786082060516}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5038759689922481
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5475285171102662
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:13:05,943] Trial 36 finished with value: 0.5732420923450362 and parameters: {'subsample': 0.4230483880556907, 'dropout_rate': 0.6944967906024405, 'n_estimators': 391, 'learning_rate': 0.09077666915244978}. Best is trial 12 with value: 0.5979858924640695.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6781115879828327
[I 2024-04-18 22:13:06,598] Trial 37 finished with value: 0.63135676757979 and parameters: {'subsample': 0.1424992712803435, 'dropout_rate': 0.6198740536882945, 'n_estimators': 1, 'learning_rate': 0.08398598098613289}. Best is trial 37 with value: 0.63135676757979.

Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5058139534883721
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5475285171102662
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 22:13:08,471] Trial 38 finished with value: 0.5665453464947222 and parameters: {'subsample': 0.597471300203124, 'dropout_rate': 0.15312457379192773, 'n_estimators': 37, 'learning_rate': 0.07288612365177065}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:13:15,334] Trial 39 finished with value: 0.5881779733940009 and parameters: {'subsample': 0.17215875631487781, 'dropout_rate': 0.6293987146215918, 'n_estimators': 145, 'learning_rate': 0.08371618852440825}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 22:13:18,773] Trial 40 finished with value: 0.5820533946975239 and parameters: {'subsample': 0.33004672052129247, 'dropout_rate': 0.20013020077502125, 'n_estimators': 78, 'learning_rate': 0.07578217914391777}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5290697674418605
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:13:33,554] Trial 41 finished with value: 0.5936904151416452 and parameters: {'subsample': 0.13920009866686117, 'dropout_rate': 0.5923290762620612, 'n_estimators': 271, 'learning_rate': 0.09516471833885605}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 22:13:34,461] Trial 42 finished with value: 0.565657502346639 and parameters: {'subsample': 0.22185909007062088, 'dropout_rate': 0.853010053901898, 'n_estimators': 11, 'learning_rate': 0.08740674182799704}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6523605150214592
[I 2024-04-18 22:13:47,080] Trial 43 finished with value: 0.5998762865309453 and parameters: {'subsample': 0.13421045557943173, 'dropout_rate': 0.5150829397648921, 'n_estimators': 228, 'learning_rate': 0.006702943154240477}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:13:56,176] Trial 44 finished with value: 0.5779032936424611 and parameters: {'subsample': 0.25449616410110676, 'dropout_rate': 0.5049439370252674, 'n_estimators': 189, 'learning_rate': 0.007119241465501089}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:14:07,973] Trial 45 finished with value: 0.5904162809346173 and parameters: {'subsample': 0.17980086021893574, 'dropout_rate': 0.39439456568180375, 'n_estimators': 227, 'learning_rate': 0.02274904980797578}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:14:16,202] Trial 46 finished with value: 0.5965801095303067 and parameters: {'subsample': 0.14856562452608105, 'dropout_rate': 0.14648424644002478, 'n_estimators': 162, 'learning_rate': 0.04259250433811888}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.48643410852713176
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.4828897338403042
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 22:14:23,544] Trial 47 finished with value: 0.5369926168644181 and parameters: {'subsample': 0.7961983953812717, 'dropout_rate': 0.15017371456135958, 'n_estimators': 160, 'learning_rate': 0.01376987004902146}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6609442060085837
[I 2024-04-18 22:14:27,382] Trial 48 finished with value: 0.5908436882461612 and parameters: {'subsample': 0.14493162606630633, 'dropout_rate': 0.44830388011009914, 'n_estimators': 85, 'learning_rate': 0.03672397035187217}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.5475285171102662
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 22:14:32,838] Trial 49 finished with value: 0.5667226549986356 and parameters: {'subsample': 0.4235760499946536, 'dropout_rate': 0.65292936198785, 'n_estimators': 139, 'learning_rate': 0.05684588422528724}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5077519379844961
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:14:44,410] Trial 50 finished with value: 0.5779828880188095 and parameters: {'subsample': 0.30029853603695367, 'dropout_rate': 0.5816689926238804, 'n_estimators': 225, 'learning_rate': 0.020916921414752154}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6437768240343348
[I 2024-04-18 22:15:01,034] Trial 51 finished with value: 0.5915749234442246 and parameters: {'subsample': 0.18401478686425216, 'dropout_rate': 0.2217853163499991, 'n_estimators': 270, 'learning_rate': 0.032598924975559634}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:15:05,095] Trial 52 finished with value: 0.599720398280203 and parameters: {'subsample': 0.13390348864926618, 'dropout_rate': 0.15484825866880525, 'n_estimators': 84, 'learning_rate': 0.04371115277682905}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6781115879828327
[I 2024-04-18 22:15:05,860] Trial 53 finished with value: 0.6207103797470904 and parameters: {'subsample': 0.12235314965386802, 'dropout_rate': 0.1478101637219833, 'n_estimators': 1, 'learning_rate': 0.041570702878220435}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5058139534883721
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.4828897338403042
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 22:15:06,657] Trial 54 finished with value: 0.5536175898407298 and parameters: {'subsample': 0.2539491548387999, 'dropout_rate': 0.28234046664682466, 'n_estimators': 6, 'learning_rate': 0.04893045633977665}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6609442060085837
[I 2024-04-18 22:15:08,513] Trial 55 finished with value: 0.6021211718901636 and parameters: {'subsample': 0.12858391151022835, 'dropout_rate': 0.14695739557349807, 'n_estimators': 34, 'learning_rate': 0.028223638004184034}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 22:15:10,549] Trial 56 finished with value: 0.598709441432703 and parameters: {'subsample': 0.12293085444555393, 'dropout_rate': 0.17046822828495412, 'n_estimators': 42, 'learning_rate': 0.03742998693070783}. Best is trial 37 with value: 0.63135676757979.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6523605150214592
[I 2024-04-18 22:15:12,946] Trial 57 finished with value: 0.5953324380051054 and parameters: {'subsample': 0.13165605060453595, 'dropout_rate': 0.26532370684967627, 'n_estimators': 50, 'learning_rate': 0.027674127121206808}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 22:15:14,689] Trial 58 finished with value: 0.5805328727937157 and parameters: {'subsample': 0.18148699271416946, 'dropout_rate': 0.307915219237495, 'n_estimators': 31, 'learning_rate': 0.03841271808558363}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:15:17,806] Trial 59 finished with value: 0.5867655630080388 and parameters: {'subsample': 0.24273484737555662, 'dropout_rate': 0.21859795446897298, 'n_estimators': 69, 'learning_rate': 0.05034803052192743}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 22:15:22,383] Trial 60 finished with value: 0.591865504838211 and parameters: {'subsample': 0.19761961284300866, 'dropout_rate': 0.17402152287454367, 'n_estimators': 107, 'learning_rate': 0.016155707598120267}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6523605150214592
[I 2024-04-18 22:15:23,840] Trial 61 finished with value: 0.6079665191789317 and parameters: {'subsample': 0.12076638616972253, 'dropout_rate': 0.12979706486015408, 'n_estimators': 26, 'learning_rate': 0.03852780382652911}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5135658914728682
Fold 3 C-index: 0.6
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 22:15:25,096] Trial 62 finished with value: 0.6039307938390213 and parameters: {'subsample': 0.12752059074063649, 'dropout_rate': 0.13481678665768507, 'n_estimators': 20, 'learning_rate': 0.03920983589104347}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.6523605150214592
[I 2024-04-18 22:15:26,735] Trial 63 finished with value: 0.5967507353057343 and parameters: {'subsample': 0.17061852792553495, 'dropout_rate': 0.13675743099141846, 'n_estimators': 24, 'learning_rate': 0.046402660479387105}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 22:15:29,366] Trial 64 finished with value: 0.5977681938899491 and parameters: {'subsample': 0.10239548318381814, 'dropout_rate': 0.2093418651620836, 'n_estimators': 57, 'learning_rate': 0.030766854101693296}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.6824034334763949
[I 2024-04-18 22:15:30,111] Trial 65 finished with value: 0.586205914123693 and parameters: {'subsample': 0.15251763596408438, 'dropout_rate': 0.25082823877608584, 'n_estimators': 2, 'learning_rate': 0.04136280459623167}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5213178294573644
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 22:15:31,375] Trial 66 finished with value: 0.5765525333937067 and parameters: {'subsample': 0.20579084104478235, 'dropout_rate': 0.12857769711965278, 'n_estimators': 21, 'learning_rate': 0.055957669840987476}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.4941860465116279
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.5399239543726235
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 22:15:37,447] Trial 67 finished with value: 0.5503753804826748 and parameters: {'subsample': 0.5503593470275019, 'dropout_rate': 0.5615241586842935, 'n_estimators': 92, 'learning_rate': 0.03456763249247782}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 22:25:05,155] Trial 68 finished with value: 0.5827959563657445 and parameters: {'subsample': 0.274718935279992, 'dropout_rate': 0.1723138429739745, 'n_estimators': 65, 'learning_rate': 0.028166010533709714}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5135658914728682
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 22:25:07,424] Trial 69 finished with value: 0.5870182127903497 and parameters: {'subsample': 0.12142049805751742, 'dropout_rate': 0.3609738421036419, 'n_estimators': 18, 'learning_rate': 0.04687193560312446}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.5321888412017167
[I 2024-04-18 22:25:12,512] Trial 70 finished with value: 0.5193423500899208 and parameters: {'subsample': 0.9847790608248583, 'dropout_rate': 0.24025513443895555, 'n_estimators': 104, 'learning_rate': 0.0021036426334471022}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6523605150214592
[I 2024-04-18 22:28:51,107] Trial 71 finished with value: 0.5995897263381911 and parameters: {'subsample': 0.13170222725644498, 'dropout_rate': 0.16550433981033863, 'n_estimators': 42, 'learning_rate': 0.039561341659875196}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 22:28:54,958] Trial 72 finished with value: 0.5900298222985038 and parameters: {'subsample': 0.160838482936524, 'dropout_rate': 0.12480379066545255, 'n_estimators': 39, 'learning_rate': 0.039535937434286454}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 22:28:57,900] Trial 73 finished with value: 0.6030918944822881 and parameters: {'subsample': 0.12728321578525587, 'dropout_rate': 0.1969664778701767, 'n_estimators': 54, 'learning_rate': 0.04552133352914019}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.628755364806867
[I 2024-04-18 22:28:58,404] Trial 74 finished with value: 0.5929943005515866 and parameters: {'subsample': 0.10178757052019492, 'dropout_rate': 0.1951569386634276, 'n_estimators': 1, 'learning_rate': 0.03471229822615198}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:29:01,424] Trial 75 finished with value: 0.5892939784659881 and parameters: {'subsample': 0.20162501497067287, 'dropout_rate': 0.10356365273510501, 'n_estimators': 66, 'learning_rate': 0.05347623469115433}. Best is trial 37 with value: 0.63135676757979.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5213178294573644
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6652360515021459
[I 2024-04-18 22:29:02,898] Trial 76 finished with value: 0.5870986548528105 and parameters: {'subsample': 0.23139451639538283, 'dropout_rate': 0.13256773774941386, 'n_estimators': 27, 'learning_rate': 0.044078110901801554}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5329457364341085
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:29:07,347] Trial 77 finished with value: 0.591187750388056 and parameters: {'subsample': 0.16191322993552076, 'dropout_rate': 0.6856752604387412, 'n_estimators': 119, 'learning_rate': 0.04583800458269524}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.6523605150214592
[I 2024-04-18 22:29:09,145] Trial 78 finished with value: 0.593105320264596 and parameters: {'subsample': 0.12733543825091032, 'dropout_rate': 0.9900767600312439, 'n_estimators': 51, 'learning_rate': 0.026910589748387836}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:29:12,731] Trial 79 finished with value: 0.589916457528815 and parameters: {'subsample': 0.18786627625450017, 'dropout_rate': 0.5251572824640953, 'n_estimators': 93, 'learning_rate': 0.051290021622959724}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6148936170212767
Fold 4 C-index: 0.5513307984790875
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:29:13,654] Trial 80 finished with value: 0.590197324192409 and parameters: {'subsample': 0.1422086968036336, 'dropout_rate': 0.20536997014739714, 'n_estimators': 15, 'learning_rate': 0.03033250133418161}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 22:29:34,925] Trial 81 finished with value: 0.6092048498523867 and parameters: {'subsample': 0.11921977089043945, 'dropout_rate': 0.15558429144079824, 'n_estimators': 33, 'learning_rate': 0.03984522243485958}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5368217054263565
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 22:29:38,092] Trial 82 finished with value: 0.60099528849762 and parameters: {'subsample': 0.11420456581142766, 'dropout_rate': 0.15651542057076778, 'n_estimators': 75, 'learning_rate': 0.041031886450036636}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:29:40,650] Trial 83 finished with value: 0.597152469266156 and parameters: {'subsample': 0.10303416517243406, 'dropout_rate': 0.23061864152005623, 'n_estimators': 54, 'learning_rate': 0.0593266874161474}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.6523605150214592
[I 2024-04-18 22:29:41,906] Trial 84 finished with value: 0.5926471562194734 and parameters: {'subsample': 0.1674416275176765, 'dropout_rate': 0.18546792851820132, 'n_estimators': 26, 'learning_rate': 0.033956115926652305}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.6437768240343348
[I 2024-04-18 22:29:44,871] Trial 85 finished with value: 0.5935162416416391 and parameters: {'subsample': 0.12121085338849227, 'dropout_rate': 0.11817143408437573, 'n_estimators': 73, 'learning_rate': 0.04034343833377516}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.6523605150214592
[I 2024-04-18 22:29:45,853] Trial 86 finished with value: 0.5884042418513178 and parameters: {'subsample': 0.16617232973504614, 'dropout_rate': 0.2713143116483331, 'n_estimators': 13, 'learning_rate': 0.06372583418560197}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5213178294573644
Fold 3 C-index: 0.5851063829787234
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:29:48,149] Trial 87 finished with value: 0.5861189117812811 and parameters: {'subsample': 0.2195978762494979, 'dropout_rate': 0.15221617849643043, 'n_estimators': 60, 'learning_rate': 0.03627566017772645}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5174418604651163
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 22:29:50,049] Trial 88 finished with value: 0.5758512293200602 and parameters: {'subsample': 0.19615925432601466, 'dropout_rate': 0.30655459857082823, 'n_estimators': 37, 'learning_rate': 0.04847424533205698}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6781115879828327
[I 2024-04-18 22:33:28,667] Trial 89 finished with value: 0.6097367836372334 and parameters: {'subsample': 0.14717384189634317, 'dropout_rate': 0.6341129182316576, 'n_estimators': 1, 'learning_rate': 0.025056796383218}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.4941860465116279
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5475285171102662
Fold 5 C-index: 0.5987124463519313
[I 2024-04-18 22:33:29,785] Trial 90 finished with value: 0.546320546523035 and parameters: {'subsample': 0.7057881652016033, 'dropout_rate': 0.6342049040842007, 'n_estimators': 15, 'learning_rate': 0.022668222323417826}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6781115879828327
[I 2024-04-18 22:33:30,568] Trial 91 finished with value: 0.6097367836372334 and parameters: {'subsample': 0.149613840112514, 'dropout_rate': 0.7288388803855724, 'n_estimators': 1, 'learning_rate': 0.011785937005545404}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.5399239543726235
Fold 5 C-index: 0.6866952789699571
[I 2024-04-18 22:33:32,461] Trial 92 finished with value: 0.5761352735652505 and parameters: {'subsample': 0.15241027914587268, 'dropout_rate': 0.7619837691630014, 'n_estimators': 3, 'learning_rate': 0.025484894493085195}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 22:33:34,116] Trial 93 finished with value: 0.5977536329856958 and parameters: {'subsample': 0.11869326699224907, 'dropout_rate': 0.7223163929602235, 'n_estimators': 31, 'learning_rate': 0.019118301911996212}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:33:36,350] Trial 94 finished with value: 0.5886007754750857 and parameters: {'subsample': 0.17996207646485962, 'dropout_rate': 0.8138324696840598, 'n_estimators': 46, 'learning_rate': 0.01451213678834245}. Best is trial 37 with value: 0.63135676757979.

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 22:33:37,560] Trial 95 finished with value: 0.5777605360198019 and parameters: {'subsample': 0.2409742009832413, 'dropout_rate': 0.5605189266690069, 'n_estimators': 15, 'learning_rate': 0.04192341774078394}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.5399239543726235
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 22:33:38,699] Trial 96 finished with value: 0.5528527019406988 and parameters: {'subsample': 0.4635260660937965, 'dropout_rate': 0.6619132363391337, 'n_estimators': 29, 'learning_rate': 0.029339793383740494}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.4790874524714829
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 22:33:39,369] Trial 97 finished with value: 0.5715312708576208 and parameters: {'subsample': 0.14702908889996077, 'dropout_rate': 0.9263488734601075, 'n_estimators': 8, 'learning_rate': 0.03184901175247192}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6781115879828327
[I 2024-04-18 22:33:40,005] Trial 98 finished with value: 0.6207103797470904 and parameters: {'subsample': 0.11968735000960715, 'dropout_rate': 0.6124712019686478, 'n_estimators': 1, 'learning_rate': 0.01020340328195169}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.4828897338403042

[I 2024-04-18 22:33:41,623] A new study created in memory with name: no-name-484875ed-9d73-4cef-bfc7-8c6eca3a4399

Fold 5 C-index: 0.5321888412017167
[I 2024-04-18 22:33:41,528] Trial 99 finished with value: 0.5208632626374493 and parameters: {'subsample': 0.9104218782867626, 'dropout_rate': 0.6501075757985869, 'n_estimators': 36, 'learning_rate': 0.011689828263226825}. Best is trial 37 with value: 0.63135676757979.


* Best trial for C-index:
 FrozenTrial(number=37, state=TrialState.COMPLETE, values=[0.63135676757979], datetime_start=datetime.datetime(2024, 4, 18, 22, 13, 5, 949497), datetime_complete=datetime.datetime(2024, 4, 18, 22, 13, 6, 598261), params={'subsample': 0.1424992712803435, 'dropout_rate': 0.6198740536882945, 'n_estimators': 1, 'learning_rate': 0.08398598098613289}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=37, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.1424992712803435, 'dropout_rate': 0.6198740536882945, 'n_estimators': 1, 'learning_rate': 0.08398598098613289}


* Best Score for C-index:
 0.63135676757979

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2768605959166274
Fold 2 IBS: 0.3036581885611299
Fold 3 IBS: 0.2644264860571975
Fold 4 IBS: 0.32963467189257545
Fold 5 IBS: 0.23049650269649638
[I 2024-04-18 22:33:46,879] Trial 0 finished with value: 0.2810152890248053 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2810152890248053.
Fold 1 IBS: 0.3314083926697305
Fold 2 IBS: 0.46023211461621694
Fold 3 IBS: 0.32275947223526036
Fold 4 IBS: 0.4515037346386999
Fold 5 IBS: 0.339376702626222
[I 2024-04-18 22:34:55,276] Trial 1 finished with value: 0.38105608335722596 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2810152890248053.
Fold 1 IBS: 0.30914429913017866
Fold 2 IBS: 0.37637524794948946
Fold 3 IBS: 0.30561411095953644
Fold 4 IBS: 0.40555008411689025
Fold 5 IBS: 0.3100934076743383
[I 2024-04-18 22:35:33,748] Trial 2 finished with value: 0.3413554299660866 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2810152890248053.
Fold 1 IBS: 0.3078899769382786
Fold 2 IBS: 0.3570988873609887
Fold 3 IBS: 0.30353910653723143
Fold 4 IBS: 0.3775897770259243
Fold 5 IBS: 0.26650386822263317
[I 2024-04-18 22:36:13,205] Trial 3 finished with value: 0.32252432321701124 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2810152890248053.
Fold 1 IBS: 0.3071251323809744
Fold 2 IBS: 0.3567178250196466
Fold 3 IBS: 0.3031246933521742
Fold 4 IBS: 0.37684901476947935
Fold 5 IBS: 0.2812461385031304
[I 2024-04-18 22:36:49,281] Trial 4 finished with value: 0.325012560805081 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2810152890248053.
Fold 1 IBS: 0.3328867486409142
Fold 2 IBS: 0.45737609071385643
Fold 3 IBS: 0.32083565149957505
Fold 4 IBS: 0.4401276385445964
Fold 5 IBS: 0.33923818447315957
[I 2024-04-18 23:25:33,602] Trial 5 finished with value: 0.37809286277442034 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2810152890248053.
Fold 1 IBS: 0.2583770894605203
Fold 2 IBS: 0.2857814818985479
Fold 3 IBS: 0.24143226956074204
Fold 4 IBS: 0.30853367074254323
Fold 5 IBS: 0.21760040361445157
[I 2024-04-18 23:29:37,596] Trial 6 finished with value: 0.262344983055361 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.262344983055361.
Fold 1 IBS: 0.24415178034005855
Fold 2 IBS: 0.2412707825406151
Fold 3 IBS: 0.21941757155402425
Fold 4 IBS: 0.27688615792099336
Fold 5 IBS: 0.2141593818792363
[I 2024-04-18 23:29:39,884] Trial 7 finished with value: 0.2391771348469855 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.2391771348469855.
Fold 1 IBS: 0.27394902748358135
Fold 2 IBS: 0.3097473739416778
Fold 3 IBS: 0.2682616149917311
Fold 4 IBS: 0.3262312283344766
Fold 5 IBS: 0.22610047650933945
[I 2024-04-18 23:29:50,177] Trial 8 finished with value: 0.28085794425216126 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.2391771348469855.
Fold 1 IBS: 0.3196633503952017
Fold 2 IBS: 0.4318764254294795
Fold 3 IBS: 0.321823329544855
Fold 4 IBS: 0.43690868751139156
Fold 5 IBS: 0.3390240231257648
[I 2024-04-18 23:30:21,071] Trial 9 finished with value: 0.36985916320133855 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.2391771348469855.
Fold 1 IBS: 0.2470353461515696
Fold 2 IBS: 0.23221934841922323
Fold 3 IBS: 0.22841230778724064
Fold 4 IBS: 0.24273812909212658
Fold 5 IBS: 0.22906264846898927
[I 2024-04-18 23:30:22,797] Trial 10 finished with value: 0.23589355598382986 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.24639976969987745
Fold 2 IBS: 0.2328507694823116
Fold 3 IBS: 0.22670631441579872
Fold 4 IBS: 0.24561898332733612
Fold 5 IBS: 0.2279748608955893
[I 2024-04-18 23:30:23,589] Trial 11 finished with value: 0.23591013956418264 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.2664418388990431
Fold 2 IBS: 0.3076016489022325
Fold 3 IBS: 0.2511706524883229
Fold 4 IBS: 0.32493196485209064
Fold 5 IBS: 0.22893310831832445
[I 2024-04-18 23:30:26,219] Trial 12 finished with value: 0.27581584269200266 and parameters: {'subsample': 0.9876601507615164, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.24713256528114305
Fold 2 IBS: 0.23213446241221616
Fold 3 IBS: 0.2286782010734839
Fold 4 IBS: 0.24238367574605638
Fold 5 IBS: 0.22921606612925213
[I 2024-04-18 23:30:27,283] Trial 13 finished with value: 0.2359089941284303 and parameters: {'subsample': 0.9944701185331792, 'dropout_rate': 0.7324371247382785, 'n_estimators': 3, 'learning_rate': 0.007730532223257889}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.2460480333299105
Fold 2 IBS: 0.2333029913205398
Fold 3 IBS: 0.22563981627052881
Fold 4 IBS: 0.2475014172884343
Fold 5 IBS: 0.22734769412071507
[I 2024-04-18 23:30:30,526] Trial 14 finished with value: 0.23596799046602568 and parameters: {'subsample': 0.8637836787170821, 'dropout_rate': 0.9788958362896205, 'n_estimators': 102, 'learning_rate': 0.0025916531369806137}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.24714716184302893
Fold 2 IBS: 0.2321229892475288
Fold 3 IBS: 0.22871157501774905
Fold 4 IBS: 0.24233260209817745
Fold 5 IBS: 0.22923879535204342
[I 2024-04-18 23:30:32,138] Trial 15 finished with value: 0.23591062471170554 and parameters: {'subsample': 0.8912920435266729, 'dropout_rate': 0.7994004963170612, 'n_estimators': 13, 'learning_rate': 0.0015537236853158376}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.24208391446019598
Fold 2 IBS: 0.24552873023414953
Fold 3 IBS: 0.21615177172009897
Fold 4 IBS: 0.2836663096106123
Fold 5 IBS: 0.19981149683121197
[I 2024-04-18 23:30:47,421] Trial 16 finished with value: 0.23744844457125375 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.6131361144829893, 'n_estimators': 293, 'learning_rate': 0.013100752673181311}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.24467502714898698
Fold 2 IBS: 0.2504720380729549
Fold 3 IBS: 0.21921183874778383
Fold 4 IBS: 0.2878362340249696
Fold 5 IBS: 0.21723190275107537
[I 2024-04-18 23:30:51,209] Trial 17 finished with value: 0.2438854081491541 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.7574099126710454, 'n_estimators': 99, 'learning_rate': 0.019073860081206092}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.3152189136909896
Fold 2 IBS: 0.3920103489205586
Fold 3 IBS: 0.30682995710043187
Fold 4 IBS: 0.4113666139306873
Fold 5 IBS: 0.3181338792632784
[I 2024-04-18 23:31:09,541] Trial 18 finished with value: 0.34871194258118915 and parameters: {'subsample': 0.6236867669661592, 'dropout_rate': 0.6302368809248846, 'n_estimators': 336, 'learning_rate': 0.036281627766329455}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.24405534422992964

Fold 2 IBS: 0.2437305585877217
Fold 3 IBS: 0.21828441799894427
Fold 4 IBS: 0.2799082411268824
Fold 5 IBS: 0.21959930006866285
[I 2024-04-18 23:31:14,790] Trial 19 finished with value: 0.24111557240242817 and parameters: {'subsample': 0.8350722272141606, 'dropout_rate': 0.8386110478636641, 'n_estimators': 135, 'learning_rate': 0.010447042153984048}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.24417441965516398
Fold 2 IBS: 0.24564410329045724
Fold 3 IBS: 0.21829558699624546
Fold 4 IBS: 0.2845284621600695
Fold 5 IBS: 0.21885186859083686
[I 2024-04-18 23:31:17,287] Trial 20 finished with value: 0.2422988881385546 and parameters: {'subsample': 0.9152086021979481, 'dropout_rate': 0.5638508730252081, 'n_estimators': 61, 'learning_rate': 0.025428571362532227}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.24431477640484145
Fold 2 IBS: 0.23832316205108614
Fold 3 IBS: 0.2199227079522707
Fold 4 IBS: 0.26746257866946227
Fold 5 IBS: 0.22278659465478365
[I 2024-04-18 23:31:18,393] Trial 21 finished with value: 0.23856196394648882 and parameters: {'subsample': 0.9876175410749531, 'dropout_rate': 0.7387107106890588, 'n_estimators': 10, 'learning_rate': 0.0915186980655547}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.24707774299572138
Fold 2 IBS: 0.23218198150193028
Fold 3 IBS: 0.2285598045634303
Fold 4 IBS: 0.24258368657346763
Fold 5 IBS: 0.22911150630384836
[I 2024-04-18 23:31:19,348] Trial 22 finished with value: 0.2359029443876796 and parameters: {'subsample': 0.9679638847412821, 'dropout_rate': 0.9652576957064382, 'n_estimators': 3, 'learning_rate': 0.011571896947341447}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.24487878718886483
Fold 2 IBS: 0.23532181689847897
Fold 3 IBS: 0.22201557977642464
Fold 4 IBS: 0.2570183569407285
Fold 5 IBS: 0.22485776117736853
[I 2024-04-18 23:31:21,310] Trial 23 finished with value: 0.23681846039637308 and parameters: {'subsample': 0.7931060031639795, 'dropout_rate': 0.9411511760643292, 'n_estimators': 57, 'learning_rate': 0.01062718851618137}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.24403670148675838
Fold 2 IBS: 0.24223364988710452
Fold 3 IBS: 0.21845924499763789
Fold 4 IBS: 0.279196657769385
Fold 5 IBS: 0.2203261920914245
[I 2024-04-18 23:31:24,399] Trial 24 finished with value: 0.24085048924646207 and parameters: {'subsample': 0.9243004910961382, 'dropout_rate': 0.9913003691121219, 'n_estimators': 79, 'learning_rate': 0.016125098954827808}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.24618974338886382
Fold 2 IBS: 0.23313778002320648
Fold 3 IBS: 0.2260416174218011
Fold 4 IBS: 0.24681513068094763
Fold 5 IBS: 0.22760978874314033
[I 2024-04-18 23:31:29,637] Trial 25 finished with value: 0.23595881205159186 and parameters: {'subsample': 0.9425097879944919, 'dropout_rate': 0.8139553387854312, 'n_estimators': 145, 'learning_rate': 0.0015979940238253754}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.2444130138276249
Fold 2 IBS: 0.23687884421940758
Fold 3 IBS: 0.21900474110511073
Fold 4 IBS: 0.26888806300140844
Fold 5 IBS: 0.2212840692114483
[I 2024-04-18 23:31:31,398] Trial 26 finished with value: 0.238093746273 and parameters: {'subsample': 0.6130521767650078, 'dropout_rate': 0.8782240363652423, 'n_estimators': 40, 'learning_rate': 0.0280143656951303}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.24721216491085363
Fold 2 IBS: 0.2320749312708999
Fold 3 IBS: 0.22888868997237302
Fold 4 IBS: 0.24212068284463673
Fold 5 IBS: 0.22933501266948728
[I 2024-04-18 23:31:32,115] Trial 27 finished with value: 0.2359262963336501 and parameters: {'subsample': 0.8024452866861593, 'dropout_rate': 0.5697175944982166, 'n_estimators': 1, 'learning_rate': 0.008104176065195496}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.24889335981085395
Fold 2 IBS: 0.2673218765378427
Fold 3 IBS: 0.22670206817754796
Fold 4 IBS: 0.2968936675128609
Fold 5 IBS: 0.21543543368622456
[I 2024-04-18 23:31:34,946] Trial 28 finished with value: 0.251049281145066 and parameters: {'subsample': 0.9476383316901545, 'dropout_rate': 0.9202134126426975, 'n_estimators': 82, 'learning_rate': 0.03545838957871889}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.2720525145261858
Fold 2 IBS: 0.31870499403119734
Fold 3 IBS: 0.26105898631942787
Fold 4 IBS: 0.33185488572398314
Fold 5 IBS: 0.23317063248839265
[I 2024-04-18 23:31:40,626] Trial 29 finished with value: 0.28336840261783736 and parameters: {'subsample': 0.8172428268344349, 'dropout_rate': 0.6596547404563864, 'n_estimators': 135, 'learning_rate': 0.04277746375706198}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.2761531309772859
Fold 2 IBS: 0.32510637150743643
Fold 3 IBS: 0.2682669211740448
Fold 4 IBS: 0.33963451842444786
Fold 5 IBS: 0.2364410411429924
[I 2024-04-18 23:32:01,216] Trial 30 finished with value: 0.2891203966452415 and parameters: {'subsample': 0.6953833217742003, 'dropout_rate': 0.7925892402831108, 'n_estimators': 382, 'learning_rate': 0.016814619253793885}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.24437346638193375
Fold 2 IBS: 0.24809602612766993
Fold 3 IBS: 0.21855136644720624
Fold 4 IBS: 0.2866827581756651
Fold 5 IBS: 0.21822088891100944
[I 2024-04-18 23:32:02,381] Trial 31 finished with value: 0.24318490120869685 and parameters: {'subsample': 0.9887925631922994, 'dropout_rate': 0.7031781510804408, 'n_estimators': 21, 'learning_rate': 0.08218105202110261}. Best is trial 10 with value: 0.23589355598382986.
Fold 1 IBS: 0.24695294065609724
Fold 2 IBS: 0.2322988147048431
Fold 3 IBS: 0.22820772428264585
Fold 4 IBS: 0.24307061585222153
Fold 5 IBS: 0.22893297475400232
[I 2024-04-18 23:32:03,171] Trial 32 finished with value: 0.23589261404996203 and parameters: {'subsample': 0.9922647074026966, 'dropout_rate': 0.47616773854130245, 'n_estimators': 1, 'learning_rate': 0.05979612003272131}. Best is trial 32 with value: 0.23589261404996203.
Fold 1 IBS: 0.2476747139905699
Fold 2 IBS: 0.26152193913651633
Fold 3 IBS: 0.22390156495510927
Fold 4 IBS: 0.29352478760908135
Fold 5 IBS: 0.21565619654457668
[I 2024-04-18 23:32:05,042] Trial 33 finished with value: 0.2484558404471707 and parameters: {'subsample': 0.8936171990601475, 'dropout_rate': 0.48095898939081394, 'n_estimators': 41, 'learning_rate': 0.0647797242442408}. Best is trial 32 with value: 0.23589261404996203.
Fold 1 IBS: 0.26805389799297435
Fold 2 IBS: 0.2919949258751166
Fold 3 IBS: 0.25301549067505064
Fold 4 IBS: 0.31831114893579937
Fold 5 IBS: 0.2169518752150579
[I 2024-04-18 23:32:08,779] Trial 34 finished with value: 0.26966546773879974 and parameters: {'subsample': 0.7765244111454901, 'dropout_rate': 0.3308751491306201, 'n_estimators': 89, 'learning_rate': 0.05980650009912425}. Best is trial 32 with value: 0.23589261404996203.
Fold 1 IBS: 0.24440199703501042
Fold 2 IBS: 0.24477719190279862
Fold 3 IBS: 0.21848340947344844
Fold 4 IBS: 0.2865534574745412
Fold 5 IBS: 0.21845432317275515
[I 2024-04-18 23:32:10,837] Trial 35 finished with value: 0.24253407581171077 and parameters: {'subsample': 0.8510303927273637, 'dropout_rate': 0.43975685710717877, 'n_estimators': 38, 'learning_rate': 0.0447014121888437}. Best is trial 32 with value: 0.23589261404996203.
Fold 1 IBS: 0.29681016467029026
Fold 2 IBS: 0.35960899753454084
Fold 3 IBS: 0.2840070960799603
Fold 4 IBS: 0.38476969178723275
Fold 5 IBS: 0.28735305262786964
[I 2024-04-18 23:32:14,912] Trial 36 finished with value: 0.32250980053997874 and parameters: {'subsample': 0.9336341570118644, 'dropout_rate': 0.5097227054150352, 'n_estimators': 114, 'learning_rate': 0.07348660660982469}. Best is trial 32 with value: 0.23589261404996203.
Fold 1 IBS: 0.24638552364805086
Fold 2 IBS: 0.2327002090911556
Fold 3 IBS: 0.22649089798022476
Fold 4 IBS: 0.24594653141315126
Fold 5 IBS: 0.2279213456421312
[I 2024-04-18 23:32:16,255] Trial 37 finished with value: 0.23588890155494274 and parameters: {'subsample': 0.729556736844599, 'dropout_rate': 0.2935849832576356, 'n_estimators': 27, 'learning_rate': 0.00715235038239253}. Best is trial 37 with value: 0.23588890155494274.
Fold 1 IBS: 0.3011666858680603

Fold 2 IBS: 0.3406669967514771
Fold 3 IBS: 0.29615252460210995
Fold 4 IBS: 0.3505624068968957
Fold 5 IBS: 0.23184246606960945
[I 2024-04-18 23:32:23,971] Trial 38 finished with value: 0.3040782160376305 and parameters: {'subsample': 0.708815775769025, 'dropout_rate': 0.10689409878635497, 'n_estimators': 159, 'learning_rate': 0.0802388198308747}. Best is trial 37 with value: 0.23588890155494274.
Fold 1 IBS: 0.25341663037436557
Fold 2 IBS: 0.2663073173733578
Fold 3 IBS: 0.24497687658347134
Fold 4 IBS: 0.2972154484829737
Fold 5 IBS: 0.20528323840152937
[I 2024-04-18 23:32:35,760] Trial 39 finished with value: 0.25343990224313956 and parameters: {'subsample': 0.36375004083294554, 'dropout_rate': 0.27268583127450263, 'n_estimators': 225, 'learning_rate': 0.021705015906159475}. Best is trial 37 with value: 0.23588890155494274.
Fold 1 IBS: 0.33133311685803907
Fold 2 IBS: 0.42148486722189815
Fold 3 IBS: 0.3206482058467423
Fold 4 IBS: 0.4376453570735614
Fold 5 IBS: 0.33886660696535603
[I 2024-04-18 23:33:07,349] Trial 40 finished with value: 0.3699956307931194 and parameters: {'subsample': 0.7510781797151287, 'dropout_rate': 0.21707792452970792, 'n_estimators': 434, 'learning_rate': 0.055335087602794375}. Best is trial 37 with value: 0.23588890155494274.
Fold 1 IBS: 0.2462106809164557
Fold 2 IBS: 0.2331243903707238
Fold 3 IBS: 0.22614128761520072
Fold 4 IBS: 0.24666313537445325
Fold 5 IBS: 0.2276528450088092
[I 2024-04-18 23:33:08,843] Trial 41 finished with value: 0.23595846785712854 and parameters: {'subsample': 0.9994962321376948, 'dropout_rate': 0.3647829672830819, 'n_estimators': 26, 'learning_rate': 0.008723160424208539}. Best is trial 37 with value: 0.23588890155494274.
Fold 1 IBS: 0.24512249992867371
Fold 2 IBS: 0.23509922071133063
Fold 3 IBS: 0.22277600942630935
Fold 4 IBS: 0.2554780571817978
Fold 5 IBS: 0.22536233397483377
[I 2024-04-18 23:33:11,902] Trial 42 finished with value: 0.23676762424458908 and parameters: {'subsample': 0.9492063543789401, 'dropout_rate': 0.41939872707204956, 'n_estimators': 73, 'learning_rate': 0.00733657096185676}. Best is trial 37 with value: 0.23588890155494274.
Fold 1 IBS: 0.24670133258309646
Fold 2 IBS: 0.23251456779612564
Fold 3 IBS: 0.22755075757628432
Fold 4 IBS: 0.24405650167841753
Fold 5 IBS: 0.22854789089690666
[I 2024-04-18 23:33:13,086] Trial 43 finished with value: 0.2358742101061661 and parameters: {'subsample': 0.8874201305461583, 'dropout_rate': 0.3224525901926356, 'n_estimators': 21, 'learning_rate': 0.00522962456018495}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.24538743550990788
Fold 2 IBS: 0.2341527503079008
Fold 3 IBS: 0.22382899413816876
Fold 4 IBS: 0.25179478906288727
Fold 5 IBS: 0.226077357854119
[I 2024-04-18 23:33:15,008] Trial 44 finished with value: 0.23624826537459676 and parameters: {'subsample': 0.8399392954831866, 'dropout_rate': 0.3089648723925339, 'n_estimators': 30, 'learning_rate': 0.0146430213630084}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.24416814732311165
Fold 2 IBS: 0.2376218728656808
Fold 3 IBS: 0.21859520488516038
Fold 4 IBS: 0.2711722484009573
Fold 5 IBS: 0.22008916818892793
[I 2024-04-18 23:33:17,445] Trial 45 finished with value: 0.2383293283327676 and parameters: {'subsample': 0.6254432766833774, 'dropout_rate': 0.20605074414647256, 'n_estimators': 62, 'learning_rate': 0.02032739682603954}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.24419621442699488
Fold 2 IBS: 0.23899704573138628
Fold 3 IBS: 0.21949292056949207
Fold 4 IBS: 0.26952223680790083
Fold 5 IBS: 0.22226710785885384
[I 2024-04-18 23:33:25,594] Trial 46 finished with value: 0.23889510507892558 and parameters: {'subsample': 0.8933787784410182, 'dropout_rate': 0.41405872988824116, 'n_estimators': 185, 'learning_rate': 0.005324846818189877}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.2503426870392702
Fold 2 IBS: 0.2715857034872607
Fold 3 IBS: 0.2288524471113775
Fold 4 IBS: 0.29888685360638795
Fold 5 IBS: 0.21516028195530693
[I 2024-04-18 23:33:29,899] Trial 47 finished with value: 0.25296559463992063 and parameters: {'subsample': 0.9543835338738109, 'dropout_rate': 0.38121816019927157, 'n_estimators': 112, 'learning_rate': 0.028320301257635242}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.24450806608848413
Fold 2 IBS: 0.24132052294867634
Fold 3 IBS: 0.2185655896439941
Fold 4 IBS: 0.2863463639912083
Fold 5 IBS: 0.2170266158034414
[I 2024-04-18 23:33:31,169] Trial 48 finished with value: 0.24155343169516086 and parameters: {'subsample': 0.7425330998250799, 'dropout_rate': 0.2692347531668027, 'n_estimators': 26, 'learning_rate': 0.06849968533920064}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.24406970637041742
Fold 2 IBS: 0.24087248315325072
Fold 3 IBS: 0.2187681330062307
Fold 4 IBS: 0.27485731113206907
Fold 5 IBS: 0.22120131755308844
[I 2024-04-18 23:33:45,754] Trial 49 finished with value: 0.23995379024301128 and parameters: {'subsample': 0.8714238967617893, 'dropout_rate': 0.19029008649249018, 'n_estimators': 272, 'learning_rate': 0.0042532443315512185}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.24480202411627042
Fold 2 IBS: 0.23496712199068545
Fold 3 IBS: 0.22106054633434477
Fold 4 IBS: 0.258169297321763
Fold 5 IBS: 0.22363829858336287
[I 2024-04-18 23:33:47,991] Trial 50 finished with value: 0.23652745766928535 and parameters: {'subsample': 0.5648208725708822, 'dropout_rate': 0.31763894587759, 'n_estimators': 55, 'learning_rate': 0.01336633327566714}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.24721819443583026
Fold 2 IBS: 0.2320636315691942
Fold 3 IBS: 0.2289130591741104
Fold 4 IBS: 0.2420738281881168
Fold 5 IBS: 0.22935104470554402
[I 2024-04-18 23:33:48,774] Trial 51 finished with value: 0.23592395161455912 and parameters: {'subsample': 0.9761183542077582, 'dropout_rate': 0.47494974073701446, 'n_estimators': 1, 'learning_rate': 0.005753506203418891}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.24710941900289157
Fold 2 IBS: 0.2321551391824316
Fold 3 IBS: 0.2286124677729673
Fold 4 IBS: 0.2424443026100186
Fold 5 IBS: 0.22918068976754735
[I 2024-04-18 23:33:50,340] Trial 52 finished with value: 0.2359004036671713 and parameters: {'subsample': 0.9258572211418972, 'dropout_rate': 0.6686833790034257, 'n_estimators': 26, 'learning_rate': 0.0010699775114741997}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.24615308230018643
Fold 2 IBS: 0.23321270366470354
Fold 3 IBS: 0.22596068060949545
Fold 4 IBS: 0.24672097362458617
Fold 5 IBS: 0.22754935200148452
[I 2024-04-18 23:33:51,969] Trial 53 finished with value: 0.2359193584400912 and parameters: {'subsample': 0.9162208855469669, 'dropout_rate': 0.6153131171812123, 'n_estimators': 22, 'learning_rate': 0.010981108062656215}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.2467450234155993
Fold 2 IBS: 0.23249313253024528
Fold 3 IBS: 0.22761658982414376
Fold 4 IBS: 0.24396444598696068
Fold 5 IBS: 0.22858290430440578
[I 2024-04-18 23:33:54,880] Trial 54 finished with value: 0.235880419212271 and parameters: {'subsample': 0.8980287306702492, 'dropout_rate': 0.6749412020020009, 'n_estimators': 71, 'learning_rate': 0.0014613641424149099}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.2466451072573627
Fold 2 IBS: 0.23259400840690642
Fold 3 IBS: 0.22734124374755907
Fold 4 IBS: 0.2444294035408416
Fold 5 IBS: 0.22841450091284304
[I 2024-04-18 23:33:57,450] Trial 55 finished with value: 0.23588485277310256 and parameters: {'subsample': 0.9042403029762364, 'dropout_rate': 0.6795988379330651, 'n_estimators': 71, 'learning_rate': 0.0017687374067057358}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.25152307259000567
Fold 2 IBS: 0.26886044711089885
Fold 3 IBS: 0.23320448533748767
Fold 4 IBS: 0.29256078009248476
Fold 5 IBS: 0.21255091044062638
[I 2024-04-18 23:34:00,397] Trial 56 finished with value: 0.2517399391143007 and parameters: {'subsample': 0.6636895171886583, 'dropout_rate': 0.5849631299891761, 'n_estimators': 72, 'learning_rate': 0.048748059727556955}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.24538048832033543

Fold 2 IBS: 0.2342449746737762
Fold 3 IBS: 0.22345226599611065
Fold 4 IBS: 0.25187779626804524
Fold 5 IBS: 0.2258572613233101
[I 2024-04-18 23:34:04,336] Trial 57 finished with value: 0.23616255731631552 and parameters: {'subsample': 0.772073129968633, 'dropout_rate': 0.518660275195612, 'n_estimators': 102, 'learning_rate': 0.004505670695986405}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.24573008555077389
Fold 2 IBS: 0.25605624624517975
Fold 3 IBS: 0.22153729289324992
Fold 4 IBS: 0.2905183614616067
Fold 5 IBS: 0.21572267525691174
[I 2024-04-18 23:34:09,228] Trial 58 finished with value: 0.2459129322815444 and parameters: {'subsample': 0.8237089546855147, 'dropout_rate': 0.7587802984045586, 'n_estimators': 127, 'learning_rate': 0.018008460652548762}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.24965385253523084
Fold 2 IBS: 0.26782842078574676
Fold 3 IBS: 0.22744721139319166
Fold 4 IBS: 0.2973096991465234
Fold 5 IBS: 0.215052600743126
[I 2024-04-18 23:34:11,407] Trial 59 finished with value: 0.25145835692076374 and parameters: {'subsample': 0.8855834921222737, 'dropout_rate': 0.6580325054997542, 'n_estimators': 51, 'learning_rate': 0.05996611425438985}. Best is trial 43 with value: 0.2358742101061661.
Fold 1 IBS: 0.24650346363302494
Fold 2 IBS: 0.23274481332755917
Fold 3 IBS: 0.22687835752575877
Fold 4 IBS: 0.24485722577307495
Fold 5 IBS: 0.22814453974439758
[I 2024-04-18 23:34:14,733] Trial 60 finished with value: 0.23582568000076307 and parameters: {'subsample': 0.8598282710038444, 'dropout_rate': 0.5399911630954195, 'n_estimators': 89, 'learning_rate': 0.001796599584343632}. Best is trial 60 with value: 0.23582568000076307.
Fold 1 IBS: 0.24561097666641696
Fold 2 IBS: 0.23410092706333283
Fold 3 IBS: 0.224172698528213
Fold 4 IBS: 0.25013951940521706
Fold 5 IBS: 0.22636562662405763
[I 2024-04-18 23:34:17,606] Trial 61 finished with value: 0.2360779496574475 and parameters: {'subsample': 0.8512053373901911, 'dropout_rate': 0.699558841730268, 'n_estimators': 87, 'learning_rate': 0.004475997054871918}. Best is trial 60 with value: 0.23582568000076307.
Fold 1 IBS: 0.24575869976167436
Fold 2 IBS: 0.23376889775290438
Fold 3 IBS: 0.22484646957676496
Fold 4 IBS: 0.24946140989384566
Fold 5 IBS: 0.22679730153781066
[I 2024-04-18 23:34:19,395] Trial 62 finished with value: 0.2361265557046 and parameters: {'subsample': 0.9004071512442877, 'dropout_rate': 0.533965465216628, 'n_estimators': 42, 'learning_rate': 0.008063325824300017}. Best is trial 60 with value: 0.23582568000076307.
Fold 1 IBS: 0.24695463372324497
Fold 2 IBS: 0.23217102433880304
Fold 3 IBS: 0.22807881498593
Fold 4 IBS: 0.24274935203757034
Fold 5 IBS: 0.22882039167477905
[I 2024-04-18 23:34:21,982] Trial 63 finished with value: 0.23575484335206545 and parameters: {'subsample': 0.4247294944318666, 'dropout_rate': 0.6002264330792718, 'n_estimators': 68, 'learning_rate': 0.0010409494020346382}. Best is trial 63 with value: 0.23575484335206545.
Fold 1 IBS: 0.24699115016166104
Fold 2 IBS: 0.23213549219560273
Fold 3 IBS: 0.22806974971268926
Fold 4 IBS: 0.2427424602948447
Fold 5 IBS: 0.22881312452527605
[I 2024-04-18 23:34:25,153] Trial 64 finished with value: 0.23575039537801476 and parameters: {'subsample': 0.3327668023935959, 'dropout_rate': 0.5859713629786553, 'n_estimators': 67, 'learning_rate': 0.0010753248107221922}. Best is trial 64 with value: 0.23575039537801476.
Fold 1 IBS: 0.24397332665791008
Fold 2 IBS: 0.23960765795875047
Fold 3 IBS: 0.2181660657975107
Fold 4 IBS: 0.2738964696607533
Fold 5 IBS: 0.21673018525451
[I 2024-04-18 23:34:31,783] Trial 65 finished with value: 0.2384747410658869 and parameters: {'subsample': 0.40423854941963694, 'dropout_rate': 0.6268313618227959, 'n_estimators': 152, 'learning_rate': 0.011092025632183563}. Best is trial 64 with value: 0.23575039537801476.
Fold 1 IBS: 0.24682875125418852
Fold 2 IBS: 0.2320905123005285
Fold 3 IBS: 0.22756365885647575
Fold 4 IBS: 0.24316718745743052
Fold 5 IBS: 0.2284307684070383
[I 2024-04-18 23:34:36,029] Trial 66 finished with value: 0.23561617565513232 and parameters: {'subsample': 0.2744145799483132, 'dropout_rate': 0.5949114240141219, 'n_estimators': 95, 'learning_rate': 0.0011942747286573076}. Best is trial 66 with value: 0.23561617565513232.
Fold 1 IBS: 0.24585358080104355
Fold 2 IBS: 0.23191115337248244
Fold 3 IBS: 0.2254811518510156
Fold 4 IBS: 0.24563335142750262
Fold 5 IBS: 0.22648510088255686
[I 2024-04-18 23:34:43,709] Trial 67 finished with value: 0.2350728676669202 and parameters: {'subsample': 0.20716048027091108, 'dropout_rate': 0.5839771925302427, 'n_estimators': 121, 'learning_rate': 0.0028146141277055245}. Best is trial 67 with value: 0.2350728676669202.
Fold 1 IBS: 0.242688856664224
Fold 2 IBS: 0.2341483674104651
Fold 3 IBS: 0.21735334110497712
Fold 4 IBS: 0.2683824593501316
Fold 5 IBS: 0.21584460069224443
[I 2024-04-18 23:34:49,604] Trial 68 finished with value: 0.23568352504440843 and parameters: {'subsample': 0.21037226487765542, 'dropout_rate': 0.5931415199503954, 'n_estimators': 118, 'learning_rate': 0.014364352223381463}. Best is trial 67 with value: 0.2350728676669202.
Fold 1 IBS: 0.24254586310974702
Fold 2 IBS: 0.2382950738399994
Fold 3 IBS: 0.21640113171610487
Fold 4 IBS: 0.28088309927027616
Fold 5 IBS: 0.21083784964279198
[I 2024-04-18 23:34:56,579] Trial 69 finished with value: 0.23779260351578388 and parameters: {'subsample': 0.2067896097979073, 'dropout_rate': 0.5573861746714913, 'n_estimators': 165, 'learning_rate': 0.01455202944945218}. Best is trial 67 with value: 0.2350728676669202.
Fold 1 IBS: 0.24425233463784904
Fold 2 IBS: 0.23336044448243864
Fold 3 IBS: 0.21907848043877534
Fold 4 IBS: 0.2613243293217671
Fold 5 IBS: 0.2192390798705987
[I 2024-04-18 23:35:01,778] Trial 70 finished with value: 0.23545093375028575 and parameters: {'subsample': 0.23153885041315644, 'dropout_rate': 0.5741019353713505, 'n_estimators': 122, 'learning_rate': 0.009923171060300233}. Best is trial 67 with value: 0.2350728676669202.
Fold 1 IBS: 0.2456531354894997
Fold 2 IBS: 0.23216408778928357
Fold 3 IBS: 0.22348958840743677
Fold 4 IBS: 0.24865336031817822
Fold 5 IBS: 0.22479013304533763
[I 2024-04-18 23:35:06,521] Trial 71 finished with value: 0.23495006100994717 and parameters: {'subsample': 0.23770487958735337, 'dropout_rate': 0.590408480763586, 'n_estimators': 120, 'learning_rate': 0.004398956819814096}. Best is trial 71 with value: 0.23495006100994717.
Fold 1 IBS: 0.24365383016916878
Fold 2 IBS: 0.23467208433661763
Fold 3 IBS: 0.21762820773663644
Fold 4 IBS: 0.2709725321963135
Fold 5 IBS: 0.21560530251886934
[I 2024-04-18 23:35:14,825] Trial 72 finished with value: 0.23650639139152113 and parameters: {'subsample': 0.2303035262246087, 'dropout_rate': 0.5920655737274476, 'n_estimators': 179, 'learning_rate': 0.0092756416460868}. Best is trial 71 with value: 0.23495006100994717.
Fold 1 IBS: 0.24398550324722584
Fold 2 IBS: 0.23870159946854466
Fold 3 IBS: 0.21767772235146357
Fold 4 IBS: 0.2719853636295347
Fold 5 IBS: 0.2161567678150744
[I 2024-04-18 23:35:20,003] Trial 73 finished with value: 0.23770139130236861 and parameters: {'subsample': 0.30080934872613274, 'dropout_rate': 0.5968230134839615, 'n_estimators': 130, 'learning_rate': 0.012651460851393464}. Best is trial 71 with value: 0.23495006100994717.
Fold 1 IBS: 0.24544363176287115
Fold 2 IBS: 0.23186813783920515
Fold 3 IBS: 0.2238397627974613
Fold 4 IBS: 0.24630567843085105
Fold 5 IBS: 0.2252615318321823
[I 2024-04-18 23:35:25,361] Trial 74 finished with value: 0.2345437485325142 and parameters: {'subsample': 0.15858809327496406, 'dropout_rate': 0.6425163290669973, 'n_estimators': 123, 'learning_rate': 0.0035986310883102616}. Best is trial 74 with value: 0.2345437485325142.
Fold 1 IBS: 0.2409953060405485
Fold 2 IBS: 0.2338664570065229
Fold 3 IBS: 0.21289052826657778
Fold 4 IBS: 0.2636207085450133
Fold 5 IBS: 0.21391233999546092
[I 2024-04-18 23:35:29,898] Trial 75 finished with value: 0.23305706797082468 and parameters: {'subsample': 0.13063026342128392, 'dropout_rate': 0.6439373471603412, 'n_estimators': 118, 'learning_rate': 0.015549369526274576}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.24401190869478254

Fold 2 IBS: 0.2529774991711212
Fold 3 IBS: 0.21798102587116244
Fold 4 IBS: 0.28642688588297865
Fold 5 IBS: 0.20087748432833774
[I 2024-04-18 23:35:39,027] Trial 76 finished with value: 0.24045496078967651 and parameters: {'subsample': 0.13339093977454577, 'dropout_rate': 0.6259305242495848, 'n_estimators': 202, 'learning_rate': 0.022676239872402745}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.24182560868531242
Fold 2 IBS: 0.23430921754204745
Fold 3 IBS: 0.2151702621237061
Fold 4 IBS: 0.2684686047912394
Fold 5 IBS: 0.21317672567604404
[I 2024-04-18 23:35:43,429] Trial 77 finished with value: 0.23459008376366985 and parameters: {'subsample': 0.16428958972668722, 'dropout_rate': 0.6517748140985425, 'n_estimators': 114, 'learning_rate': 0.017289869718512596}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.2418289889586624
Fold 2 IBS: 0.2345753984919539
Fold 3 IBS: 0.2151340980306673
Fold 4 IBS: 0.2689894032140322
Fold 5 IBS: 0.2130069635490081
[I 2024-04-18 23:35:48,363] Trial 78 finished with value: 0.23470697044886477 and parameters: {'subsample': 0.16220102058409236, 'dropout_rate': 0.6468866461481853, 'n_estimators': 116, 'learning_rate': 0.017226092659069384}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.24224755002721127
Fold 2 IBS: 0.24507566129527972
Fold 3 IBS: 0.21982149863472963
Fold 4 IBS: 0.2850946848358408
Fold 5 IBS: 0.20349135287100426
[I 2024-04-18 23:35:55,349] Trial 79 finished with value: 0.23914614953281316 and parameters: {'subsample': 0.15823642648482594, 'dropout_rate': 0.6470860202773677, 'n_estimators': 145, 'learning_rate': 0.02467340542221106}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.24204819606861552
Fold 2 IBS: 0.2340789180064429
Fold 3 IBS: 0.21521625682676918
Fold 4 IBS: 0.2679241658196752
Fold 5 IBS: 0.2141497036256051
[I 2024-04-18 23:35:59,184] Trial 80 finished with value: 0.2346834480694216 and parameters: {'subsample': 0.17044682867420902, 'dropout_rate': 0.7484783932749066, 'n_estimators': 101, 'learning_rate': 0.019108019389439585}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.2423406221227764
Fold 2 IBS: 0.23429076054168968
Fold 3 IBS: 0.21723247050423042
Fold 4 IBS: 0.2678027920022474
Fold 5 IBS: 0.21477498745385726
[I 2024-04-18 23:36:03,190] Trial 81 finished with value: 0.2352883265249602 and parameters: {'subsample': 0.17269253292488324, 'dropout_rate': 0.6978963768336157, 'n_estimators': 100, 'learning_rate': 0.01830089944445084}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.24167124270127566
Fold 2 IBS: 0.23459449897134113
Fold 3 IBS: 0.21500140362388406
Fold 4 IBS: 0.27069971679318666
Fold 5 IBS: 0.21215135400859567
[I 2024-04-18 23:36:07,872] Trial 82 finished with value: 0.23482364321965665 and parameters: {'subsample': 0.16900215073957406, 'dropout_rate': 0.7608463831575316, 'n_estimators': 112, 'learning_rate': 0.01886838062042759}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.24193933826897965
Fold 2 IBS: 0.24043513615493647
Fold 3 IBS: 0.21739533841904826
Fold 4 IBS: 0.28138848489705925
Fold 5 IBS: 0.20557406224157113
[I 2024-04-18 23:36:11,996] Trial 83 finished with value: 0.23734647199631892 and parameters: {'subsample': 0.1668059835263093, 'dropout_rate': 0.7702080030429564, 'n_estimators': 107, 'learning_rate': 0.02985109005795814}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.24037436688458258
Fold 2 IBS: 0.23976190708385922
Fold 3 IBS: 0.2109801162603971
Fold 4 IBS: 0.2775744038556514
Fold 5 IBS: 0.20795752939570003
[I 2024-04-18 23:36:17,602] Trial 84 finished with value: 0.23532966469603805 and parameters: {'subsample': 0.13165224724353475, 'dropout_rate': 0.7386262352112213, 'n_estimators': 141, 'learning_rate': 0.020017054539186743}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.24079003060248225
Fold 2 IBS: 0.23651158007905765
Fold 3 IBS: 0.21307880447642372
Fold 4 IBS: 0.273862505632481
Fold 5 IBS: 0.2061309262819707
[I 2024-04-18 23:36:25,096] Trial 85 finished with value: 0.23407476941448305 and parameters: {'subsample': 0.10429701737738069, 'dropout_rate': 0.6970217549939637, 'n_estimators': 166, 'learning_rate': 0.016662450071906556}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.24767774097715334
Fold 2 IBS: 0.25845773458202503
Fold 3 IBS: 0.22498240845827072
Fold 4 IBS: 0.29052019818825936
Fold 5 IBS: 0.19734641092074756
[I 2024-04-18 23:36:32,016] Trial 86 finished with value: 0.2437968986252912 and parameters: {'subsample': 0.10980460939286994, 'dropout_rate': 0.8185273091852364, 'n_estimators': 166, 'learning_rate': 0.032088412051010595}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.2542905709368716
Fold 2 IBS: 0.27185091122188726
Fold 3 IBS: 0.23911220712335526
Fold 4 IBS: 0.2958046990258895
Fold 5 IBS: 0.201366917052397
[I 2024-04-18 23:36:42,346] Trial 87 finished with value: 0.25248506107208013 and parameters: {'subsample': 0.1831618256380861, 'dropout_rate': 0.7230887774542047, 'n_estimators': 225, 'learning_rate': 0.026532495211645406}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.2419728771440963
Fold 2 IBS: 0.24098929129286123
Fold 3 IBS: 0.2142471878905125
Fold 4 IBS: 0.2790764032142103
Fold 5 IBS: 0.20512932598998815
[I 2024-04-18 23:36:48,238] Trial 88 finished with value: 0.2362830171063337 and parameters: {'subsample': 0.13846005454738466, 'dropout_rate': 0.8582453434967141, 'n_estimators': 151, 'learning_rate': 0.020785721197187607}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.24119514388111657
Fold 2 IBS: 0.23766279028225837
Fold 3 IBS: 0.2141317931063352
Fold 4 IBS: 0.2765813224475712
Fold 5 IBS: 0.20463118712233022
[I 2024-04-18 23:36:56,750] Trial 89 finished with value: 0.23484044736792234 and parameters: {'subsample': 0.10124933971066932, 'dropout_rate': 0.6436774805198799, 'n_estimators': 187, 'learning_rate': 0.016177501168922623}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.2426311524824023
Fold 2 IBS: 0.24051379090664218
Fold 3 IBS: 0.21502561048551827
Fold 4 IBS: 0.28159382341812705
Fold 5 IBS: 0.20493007694227627
[I 2024-04-18 23:37:05,807] Trial 90 finished with value: 0.2369388908469932 and parameters: {'subsample': 0.11530416326703274, 'dropout_rate': 0.64376918141961, 'n_estimators': 198, 'learning_rate': 0.016308934803063346}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.24197347666958682
Fold 2 IBS: 0.24269046191433988
Fold 3 IBS: 0.2180335190174739
Fold 4 IBS: 0.28342013143259076
Fold 5 IBS: 0.20611645005250342
[I 2024-04-18 23:37:11,457] Trial 91 finished with value: 0.23844680781729893 and parameters: {'subsample': 0.193909818367753, 'dropout_rate': 0.7750740975886313, 'n_estimators': 137, 'learning_rate': 0.023173067205740642}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.2440041248555191
Fold 2 IBS: 0.23737326223559216
Fold 3 IBS: 0.21831244459001756
Fold 4 IBS: 0.2782944855385824
Fold 5 IBS: 0.21323711550660657
[I 2024-04-18 23:37:15,838] Trial 92 finished with value: 0.23824428654526356 and parameters: {'subsample': 0.24559627285416097, 'dropout_rate': 0.6807870441474847, 'n_estimators': 121, 'learning_rate': 0.01650605336008776}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.2581869719226125
Fold 2 IBS: 0.28177393533322864
Fold 3 IBS: 0.24934057506061358
Fold 4 IBS: 0.30276360094922405
Fold 5 IBS: 0.20401435323140485
[I 2024-04-18 23:37:23,465] Trial 93 finished with value: 0.2592158872994167 and parameters: {'subsample': 0.15795195942808782, 'dropout_rate': 0.7419378663939628, 'n_estimators': 184, 'learning_rate': 0.03850422888765595}. Best is trial 75 with value: 0.23305706797082468.
Fold 1 IBS: 0.2422586399813171
Fold 2 IBS: 0.23188785562122197
Fold 3 IBS: 0.21757132358412323
Fold 4 IBS: 0.2527323335795541
Fold 5 IBS: 0.21706143322649907
[I 2024-04-18 23:37:27,942] Trial 94 finished with value: 0.23230231719854308 and parameters: {'subsample': 0.10168659289889766, 'dropout_rate': 0.641812724307286, 'n_estimators': 110, 'learning_rate': 0.01230597296655908}. Best is trial 94 with value: 0.23230231719854308.

Fold 1 IBS: 0.2406863202827842
Fold 2 IBS: 0.23719290727766623
Fold 3 IBS: 0.2139880463961989
Fold 4 IBS: 0.27307427524352845
Fold 5 IBS: 0.20542783875690165
[I 2024-04-18 23:37:34,384] Trial 95 finished with value: 0.2340738775914159 and parameters: {'subsample': 0.10055421726352921, 'dropout_rate': 0.6367468591731635, 'n_estimators': 156, 'learning_rate': 0.018320625747593914}. Best is trial 94 with value: 0.23230231719854308.
Fold 1 IBS: 0.24069365191467598
Fold 2 IBS: 0.23733770317855976
Fold 3 IBS: 0.21411919366368914
Fold 4 IBS: 0.2733885091832182
Fold 5 IBS: 0.20523810100634188
[I 2024-04-18 23:37:41,518] Trial 96 finished with value: 0.234155431789297 and parameters: {'subsample': 0.10430327789057646, 'dropout_rate': 0.7150842017502997, 'n_estimators': 156, 'learning_rate': 0.01849431229569403}. Best is trial 94 with value: 0.23230231719854308.
Fold 1 IBS: 0.2423826523606692
Fold 2 IBS: 0.24154153546303617
Fold 3 IBS: 0.21418809053102322
Fold 4 IBS: 0.27998173014531524
Fold 5 IBS: 0.20495637481577925
[I 2024-04-18 23:37:48,906] Trial 97 finished with value: 0.23661007666316464 and parameters: {'subsample': 0.1428225879209601, 'dropout_rate': 0.7167166818784789, 'n_estimators': 172, 'learning_rate': 0.01861684391577064}. Best is trial 94 with value: 0.23230231719854308.
Fold 1 IBS: 0.2418304508492176
Fold 2 IBS: 0.24918413312862123
Fold 3 IBS: 0.22032148450080077
Fold 4 IBS: 0.2852802019079207
Fold 5 IBS: 0.20232028974485772
[I 2024-04-18 23:37:55,719] Trial 98 finished with value: 0.2397873120262836 and parameters: {'subsample': 0.11745988564765689, 'dropout_rate': 0.7879431754217474, 'n_estimators': 154, 'learning_rate': 0.026117089776837927}. Best is trial 94 with value: 0.23230231719854308.
Fold 1 IBS: 0.24152341097849725
Fold 2 IBS: 0.23609231408399306
Fold 3 IBS: 0.21481426887995939
Fold 4 IBS: 0.27444529029274434
Fold 5 IBS: 0.20990881255066746
[I 2024-04-18 23:38:00,460] Trial 99 finished with value: 0.2353568193571723 and parameters: {'subsample': 0.14580294508047148, 'dropout_rate': 0.6973459717354432, 'n_estimators': 112, 'learning_rate': 0.022253830402466566}. Best is trial 94 with value: 0.23230231719854308.


* Best trial for IBS:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.23230231719854308], datetime_start=datetime.datetime(2024, 4, 18, 23, 37, 23, 470703), datetime_complete=datetime.datetime(2024, 4, 18, 23, 37, 27, 941836), params={'subsample': 0.10168659289889766, 'dropout_rate': 0.641812724307286, 'n_estimators': 110, 'learning_rate': 0.01230597296655908}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=94, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.10168659289889766, 'dropout_rate': 0.641812724307286, 'n_estimators': 110, 'learning_rate': 0.01230597296655908}


* Best Score for IBS:
 0.23230231719854308

In [77]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [78]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.631
train_ibs:  0.232

#### Test

In [79]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [80]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.6198740536882945,
                                              learning_rate=0.08398598098613289,
                                              n_estimators=1, random_state=123,
                                              subsample=0.1424992712803435)

C-index score: 0.52

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.641812724307286,
                                              learning_rate=0.01230597296655908,
                                              n_estimators=110,
                                              random_state=123,
                                              subsample=0.10168659289889766)

IBS: 0.235

In [81]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [82]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
ExtraSurvivalTrees               0.791   1.0
Randomsurvivalforest             0.760   2.0
GradientBoosting                 0.642   3.0
CoxElastic                       0.638   4.0
CoxPH                            0.637   5.0
CoxLasso                         0.636   6.0
ComponentwiseGradientBoosting    0.631   7.0
CoxRidge                         0.571   8.0

In [83]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.217   1.0
Randomsurvivalforest           0.223   2.0
GradientBoosting               0.232   3.5
ComponentwiseGradientBoosting  0.232   3.5
CoxElastic                     0.233   5.0
CoxRidge                       0.236   6.0
CoxPH                          0.240   7.5
CoxLasso                       0.240   7.5

In [84]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
GradientBoosting                 0.669   1.0
Randomsurvivalforest             0.633   2.0
ExtraSurvivalTrees               0.584   3.0
CoxLasso                         0.566   4.0
CoxPH                            0.563   5.0
CoxRidge                         0.532   6.0
CoxElastic                       0.524   7.0
ComponentwiseGradientBoosting    0.520   8.0

In [85]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
Randomsurvivalforest           0.216   1.0
ExtraSurvivalTrees             0.223   2.0
GradientBoosting               0.224   3.0
CoxRidge                       0.229   4.0
CoxElastic                     0.235   5.5
ComponentwiseGradientBoosting  0.235   5.5
CoxLasso                       0.288   7.0
CoxPH                          0.291   8.0

In [86]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/dfs/standard/no_selection/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_dfs_standard_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [87]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-18