In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
from sklearn.preprocessing import StandardScaler
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D1 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

## Test dataset: MAASTRO

In [6]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [7]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [8]:
# need to choose patient_id from MAASTRO_D1 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [9]:
# Merge MAASTRO_D1 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]

In [10]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [11]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, DFS, DFS_event]
Index: []

In [12]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [13]:
# Set lower, upper time point and times for IBS calculation later 

# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 14)
y_train:  (139,)

(99, 16)

# Feature Selection: PLSR

In [14]:
selected_features = [ "hpv_related" ,           
"oropharynx",              
"cavum_oris"]

# Selecting features in the DataFrame
X_rent = X[selected_features]

In [15]:
# Selecting features in the DataFrame
X_rent = X[selected_features]
X_new = X_rent.copy()

X_MAASTRO_rent = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_rent.copy()

# Standardization

In [16]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)
""" 
# Do the standardization for the numeric part 
scaler = StandardScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)
"""
# Change the order of the X_new_std 
X_new_std = X_new

' \n# Do the standardization for the numeric part \nscaler = StandardScaler() \nX_new_numeric_columns = X_new_numeric.columns\nX_new_numeric_index = X_new_numeric.index \nX_new_numeric_std = scaler.fit_transform(X_new_numeric)\nX_new_numeric_std = pd.DataFrame(X_new_numeric_std,\n                                 columns=X_new_numeric_columns, \n                                 index=X_new_numeric_index)\nX_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)\n'

In [17]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)
"""
# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns

MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)
 """
# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new

'\n# Do the standardization for the numeric part \nMAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns\n\nMAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns\nMAASTRO_new_numeric_index = MAASTRO_new_numeric.index \nMAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)\nMAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,\n                                 columns=MAASTRO_new_numeric_columns, \n                                 index=MAASTRO_new_numeric_index)\nMAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)\n '

In [18]:
X_new

     hpv_related  oropharynx  cavum_oris
0            0.0           1           0
1            0.0           0           0
2            0.0           0           1
3            0.0           0           0
4            0.0           0           0
..           ...         ...         ...
134          1.0           1           0
135          1.0           1           0
136          1.0           1           0
137          1.0           1           0
138          1.0           1           0

[139 rows x 3 columns]

In [19]:
X_new_std

     hpv_related  oropharynx  cavum_oris
0            0.0           1           0
1            0.0           0           0
2            0.0           0           1
3            0.0           0           0
4            0.0           0           0
..           ...         ...         ...
134          1.0           1           0
135          1.0           1           0
136          1.0           1           0
137          1.0           1           0
138          1.0           1           0

[139 rows x 3 columns]

In [20]:
MAASTRO_new

    hpv_related  oropharynx  cavum_oris
0             1           1           0
1             0           1           0
2             0           1           0
3             0           0           0
4             1           1           0
..          ...         ...         ...
94            0           0           0
95            0           0           0
96            1           1           0
97            1           1           0
98            0           0           0

[99 rows x 3 columns]

In [21]:
MAASTRO_new_std

    hpv_related  oropharynx  cavum_oris
0             1           1           0
1             0           1           0
2             0           1           0
3             0           0           0
4             1           1           0
..          ...         ...         ...
94            0           0           0
95            0           0           0
96            1           1           0
97            1           1           0
98            0           0           0

[99 rows x 3 columns]

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [22]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:20:05,757] A new study created in memory with name: no-name-3fd8d94c-0803-484d-bc1e-dba7f3afc3e1

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-13 17:20:12,957] A new study created in memory with name: no-name-96b0de4f-d3b7-48e8-9e16-6f8f36004f7e

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:12,933] Trial 0 finished with value: 0.6327052496375349 and parameters: {}. Best is trial 0 with value: 0.6327052496375349.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6327052496375349], datetime_start=datetime.datetime(2024, 4, 13, 17, 20, 5, 841735), datetime_complete=datetime.datetime(2024, 4, 13, 17, 20, 12, 933244), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6327052496375349

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.23087000581287248
Fold 2 IBS: 0.23998071068865376
Fold 3 IBS: 0.1971849102359433
Fold 4 IBS: 0.235686306455164
Fold 5 IBS: 0.21379155522848114
[I 2024-04-13 17:20:13,311] Trial 0 finished with value: 0.22350269768422293 and parameters: {}. Best is trial 0 with value: 0.22350269768422293.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.22350269768422293], datetime_start=datetime.datetime(2024, 4, 13, 17, 20, 12, 997714), datetime_complete=datetime.datetime(2024, 4, 13, 17, 20, 13, 311354), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.22350269768422293

In [23]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [24]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.633
train_ibs:  0.224

#### Test

In [25]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [26]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.55
IBS score: 0.235

In [27]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [28]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [29]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:20:13,580] A new study created in memory with name: no-name-9b869c0f-75ae-4811-82e2-9f6725709552

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5891472868217055

[I 2024-04-13 17:20:13,742] A new study created in memory with name: no-name-99bea0dd-2f86-4a2a-a2d6-2722cbf01711

Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:20:13,733] Trial 0 finished with value: 0.6224122715764377 and parameters: {}. Best is trial 0 with value: 0.6224122715764377.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6224122715764377], datetime_start=datetime.datetime(2024, 4, 13, 17, 20, 13, 618891), datetime_complete=datetime.datetime(2024, 4, 13, 17, 20, 13, 733099), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6224122715764377

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709767921887
Fold 2 IBS: 0.2320398826136388
Fold 3 IBS: 0.22898186436633558
Fold 4 IBS: 0.2419747678451801
Fold 5 IBS: 0.22939559031800452
[I 2024-04-13 17:20:13,965] Trial 0 finished with value: 0.23592784056447558 and parameters: {}. Best is trial 0 with value: 0.23592784056447558.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592784056447558], datetime_start=datetime.datetime(2024, 4, 13, 17, 20, 13, 777577), datetime_complete=datetime.datetime(2024, 4, 13, 17, 20, 13, 965400), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592784056447558

In [30]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [31]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.622
train_ibs:  0.236

#### Test

In [32]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [33]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.653

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [34]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [35]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:20:14,283] A new study created in memory with name: no-name-ec26436a-9889-4db2-b30e-cc7f073b9230

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596

[I 2024-04-13 17:20:14,753] A new study created in memory with name: no-name-bd98633b-4601-40b2-876d-34c6ae090373

Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:14,738] Trial 0 finished with value: 0.6327052496375349 and parameters: {}. Best is trial 0 with value: 0.6327052496375349.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6327052496375349], datetime_start=datetime.datetime(2024, 4, 13, 17, 20, 14, 392651), datetime_complete=datetime.datetime(2024, 4, 13, 17, 20, 14, 737937), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6327052496375349

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.23062952029645012
Fold 2 IBS: 0.23878423422778727
Fold 3 IBS: 0.1979953785766009
Fold 4 IBS: 0.23468273038135695
Fold 5 IBS: 0.21326774090755368
[I 2024-04-13 17:20:15,263] Trial 0 finished with value: 0.22307192087794978 and parameters: {}. Best is trial 0 with value: 0.22307192087794978.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.22307192087794978], datetime_start=datetime.datetime(2024, 4, 13, 17, 20, 14, 843961), datetime_complete=datetime.datetime(2024, 4, 13, 17, 20, 15, 263563), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.22307192087794978

In [36]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [37]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.633
train_ibs:  0.223

#### Test

In [38]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [39]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.55

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.233

In [40]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [41]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:20:15,693] A new study created in memory with name: no-name-0ac634e7-7256-4168-a279-a92b0303ecee

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:16,133] Trial 0 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:16,512] Trial 1 finished with value: 0.6289029682687136 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 17:20:16,712] Trial 2 finished with value: 0.6320453311126435 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:17,283] Trial 3 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:17,764] Trial 4 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:18,261] Trial 5 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:18,910] Trial 6 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:19,630] Trial 7 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:20,117] Trial 8 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:20,532] Trial 9 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:20,987] Trial 10 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:20:21,133] Trial 11 finished with value: 0.6255130467702362 and parameters: {'l1_ratio': 0.046971505265140434}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:21,547] Trial 12 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.6978253640763652}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:21,995] Trial 13 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.6189362712539238}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:22,455] Trial 14 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.8403787283021946}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:22,947] Trial 15 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.5892251114089379}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:23,376] Trial 16 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.8361111870922124}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:23,920] Trial 17 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.5632480038685016}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:24,591] Trial 18 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.8081045010661086}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:25,117] Trial 19 finished with value: 0.6316161465632874 and parameters: {'l1_ratio': 0.2466600496841937}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:20:25,289] Trial 20 finished with value: 0.6255130467702362 and parameters: {'l1_ratio': 0.10500472511016506}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:25,819] Trial 21 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.7501344475278824}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:26,538] Trial 22 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.5339346419626306}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:27,046] Trial 23 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.651954326927192}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372

Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:27,574] Trial 24 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.7602371709740536}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:28,264] Trial 25 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.891573855041803}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:28,875] Trial 26 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.4514399534035586}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:29,393] Trial 27 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.7284175098086105}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:29,963] Trial 28 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.355721226193779}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:30,460] Trial 29 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.5124352690792928}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:30,979] Trial 30 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.32170963481394405}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:31,392] Trial 31 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.4334765079491672}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:31,801] Trial 32 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.581548935880325}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:32,271] Trial 33 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.6422195303308569}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 17:20:32,446] Trial 34 finished with value: 0.6214070332403031 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:32,837] Trial 35 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.8983450253651932}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:33,284] Trial 36 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.3943060631899279}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:33,703] Trial 37 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.46903042572039566}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:34,084] Trial 38 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.6738682445636226}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:34,470] Trial 39 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.5561256026976026}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:34,825] Trial 40 finished with value: 0.6289029682687136 and parameters: {'l1_ratio': 0.2705989592091768}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:35,162] Trial 41 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.99261984708271}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:35,574] Trial 42 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.9083039816187142}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:36,008] Trial 43 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.7920713619669932}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:36,426] Trial 44 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.7077516866147374}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:36,891] Trial 45 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.6219684827438303}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:37,445] Trial 46 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.4178465972493743}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:37,974] Trial 47 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.9577161849732151}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682

Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:38,463] Trial 48 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.5033132688848968}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:39,057] Trial 49 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.355745098499332}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:39,548] Trial 50 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.8449632453631055}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:40,113] Trial 51 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.694004713951571}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:40,637] Trial 52 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.6121081658495826}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:41,153] Trial 53 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.7990342906716027}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:41,706] Trial 54 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.5474260308302842}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:42,201] Trial 55 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.7712926485836892}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:42,654] Trial 56 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.7329250131846973}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:20:42,814] Trial 57 finished with value: 0.6255130467702362 and parameters: {'l1_ratio': 0.00626942071754627}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:43,281] Trial 58 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.8461943668832637}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:43,825] Trial 59 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.6708667050740342}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:44,294] Trial 60 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.5892984254164416}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:44,720] Trial 61 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.4577454793817965}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:45,247] Trial 62 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.4924380381712026}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:45,750] Trial 63 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.3587531258584616}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:46,422] Trial 64 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.5219785666979393}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:46,821] Trial 65 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.9353466793687859}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:47,211] Trial 66 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.6424070828813235}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:47,775] Trial 67 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.40415149689429103}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:48,210] Trial 68 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.4815837722056875}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 17:20:48,466] Trial 69 finished with value: 0.6320453311126435 and parameters: {'l1_ratio': 0.18942581039571943}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:48,889] Trial 70 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.6007277058746872}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:49,661] Trial 71 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.32352616765183406}. Best is trial 0 with value: 0.6327052496375349.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:50,307] Trial 72 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.5361265642692665}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:50,852] Trial 73 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.3796269138019179}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:51,618] Trial 74 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.43581852872250365}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:52,174] Trial 75 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.32135077216239705}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:52,668] Trial 76 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.8699901712014488}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:53,139] Trial 77 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.572539076693189}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:53,662] Trial 78 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.7137725030269256}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:54,069] Trial 79 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.6730374637561107}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:54,693] Trial 80 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.4341496355436359}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:55,323] Trial 81 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.9803940872126982}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:55,733] Trial 82 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.9264056126409378}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:56,254] Trial 83 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.7683796178412482}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:56,744] Trial 84 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.8235387450207625}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:57,206] Trial 85 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.9506921827356869}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:57,678] Trial 86 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.98214917883562}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:58,166] Trial 87 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.8656704304875099}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:58,587] Trial 88 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.6331500999394808}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:59,147] Trial 89 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.48030963905812396}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:20:59,763] Trial 90 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.38516094729925343}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:21:00,512] Trial 91 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.7340814512914156}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:21:01,185] Trial 92 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.6912771460404372}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:21:01,773] Trial 93 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.6547273520711029}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:21:02,390] Trial 94 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.7853713756543309}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:21:02,856] Trial 95 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.7539180027651575}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682

Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:21:03,350] Trial 96 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.5197292065429215}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:21:03,796] Trial 97 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.5540404299908688}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:21:04,251] Trial 98 finished with value: 0.6289029682687136 and parameters: {'l1_ratio': 0.2932989360807968}. Best is trial 0 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596

[I 2024-04-13 17:21:04,788] A new study created in memory with name: no-name-5e4a8f3a-c5e3-4483-8cf1-56b312057009

Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:21:04,780] Trial 99 finished with value: 0.6327052496375349 and parameters: {'l1_ratio': 0.45768497644566286}. Best is trial 0 with value: 0.6327052496375349.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6327052496375349], datetime_start=datetime.datetime(2024, 4, 13, 17, 20, 15, 726719), datetime_complete=datetime.datetime(2024, 4, 13, 17, 20, 16, 133082), params={'l1_ratio': 0.6964995386793018}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=0, value=None)


* Best Score for C-index:
 0.6327052496375349

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2316547290662942
Fold 2 IBS: 0.23879236312745447
Fold 3 IBS: 0.19825571013048512
Fold 4 IBS: 0.2346684603917355
Fold 5 IBS: 0.21323103060583587
[I 2024-04-13 17:21:05,420] Trial 0 finished with value: 0.22332045866436104 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.22332045866436104.
Fold 1 IBS: 0.2328215420107209
Fold 2 IBS: 0.2387376694592152
Fold 3 IBS: 0.19855864371824158
Fold 4 IBS: 0.23535239124869783
Fold 5 IBS: 0.21321676645113197
[I 2024-04-13 17:21:06,159] Trial 1 finished with value: 0.2237374025776015 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.22332045866436104.
Fold 1 IBS: 0.23290719466305726
Fold 2 IBS: 0.22910469892979343
Fold 3 IBS: 0.19851761912519322
Fold 4 IBS: 0.23645133312318467
Fold 5 IBS: 0.22509043345132884
[I 2024-04-13 17:21:06,607] Trial 2 finished with value: 0.22441425585851152 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.22332045866436104.
Fold 1 IBS: 0.23206755817203836
Fold 2 IBS: 0.23873323687105907
Fold 3 IBS: 0.1983541360826436
Fold 4 IBS: 0.2347449149188972
Fold 5 IBS: 0.21320847412012783
[I 2024-04-13 17:21:07,124] Trial 3 finished with value: 0.22342166403295324 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.22332045866436104.
Fold 1 IBS: 0.23155855520957822
Fold 2 IBS: 0.23871941814125694
Fold 3 IBS: 0.1982139743671387
Fold 4 IBS: 0.23469525002945413
Fold 5 IBS: 0.21324804747539547
[I 2024-04-13 17:21:07,651] Trial 4 finished with value: 0.2232870490445647 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 4 with value: 0.2232870490445647.
Fold 1 IBS: 0.23242328361194084
Fold 2 IBS: 0.23874928396799122
Fold 3 IBS: 0.19849011487986754
Fold 4 IBS: 0.23470059325664727
Fold 5 IBS: 0.21322024259752015
[I 2024-04-13 17:21:08,231] Trial 5 finished with value: 0.22351670366279341 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 4 with value: 0.2232870490445647.
Fold 1 IBS: 0.23069034477712952
Fold 2 IBS: 0.23876043872935654
Fold 3 IBS: 0.19801779688743174
Fold 4 IBS: 0.23466743633273304
Fold 5 IBS: 0.21325798252866898
[I 2024-04-13 17:21:08,680] Trial 6 finished with value: 0.22307879985106394 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.22307879985106394.
Fold 1 IBS: 0.23163744471349698
Fold 2 IBS: 0.2387722080774997
Fold 3 IBS: 0.1982778094970434
Fold 4 IBS: 0.23465425543621984
Fold 5 IBS: 0.21322202566254672
[I 2024-04-13 17:21:09,205] Trial 7 finished with value: 0.22331274867736134 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.22307879985106394.
Fold 1 IBS: 0.23221560478131467
Fold 2 IBS: 0.2387896421276315
Fold 3 IBS: 0.19842808517108654
Fold 4 IBS: 0.23472024698580712
Fold 5 IBS: 0.2132377952828413
[I 2024-04-13 17:21:09,807] Trial 8 finished with value: 0.22347827486973623 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.22307879985106394.
Fold 1 IBS: 0.23248669442414677
Fold 2 IBS: 0.23876723087780677
Fold 3 IBS: 0.19847868490611703
Fold 4 IBS: 0.23472393442783127
Fold 5 IBS: 0.2132304211651849
[I 2024-04-13 17:21:10,474] Trial 9 finished with value: 0.2235373931602173 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.22307879985106394.
Fold 1 IBS: 0.2306788466120957
Fold 2 IBS: 0.23876494820012045
Fold 3 IBS: 0.19801355051511602
Fold 4 IBS: 0.23467033603972356
Fold 5 IBS: 0.21325983163918494
[I 2024-04-13 17:21:10,981] Trial 10 finished with value: 0.22307750260124815 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 10 with value: 0.22307750260124815.
Fold 1 IBS: 0.23063817003870443
Fold 2 IBS: 0.23878085920341557
Fold 3 IBS: 0.19799855993933504
Fold 4 IBS: 0.23468055997364717
Fold 5 IBS: 0.21326635667830884
[I 2024-04-13 17:21:11,595] Trial 11 finished with value: 0.22307290116668219 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.23064569510566146
Fold 2 IBS: 0.23877792062323275
Fold 3 IBS: 0.19800132945142582
Fold 4 IBS: 0.2346786702572194
Fold 5 IBS: 0.21326515149323388
[I 2024-04-13 17:21:12,198] Trial 12 finished with value: 0.22307375338615465 and parameters: {'l1_ratio': 0.9948264745658929}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.24643469174541094
Fold 2 IBS: 0.23148021582094833
Fold 3 IBS: 0.227884675320131
Fold 4 IBS: 0.2409180412762552
Fold 5 IBS: 0.22859248040903205
[I 2024-04-13 17:21:12,369] Trial 13 finished with value: 0.23506202091435552 and parameters: {'l1_ratio': 0.03152521162798527}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.2309986387651438
Fold 2 IBS: 0.23875243295269555
Fold 3 IBS: 0.1981374876474908
Fold 4 IBS: 0.2346822160378666
Fold 5 IBS: 0.21325725314346233
[I 2024-04-13 17:21:12,859] Trial 14 finished with value: 0.22316560570933186 and parameters: {'l1_ratio': 0.8887005110166508}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.2311365411470601
Fold 2 IBS: 0.2388008772704612
Fold 3 IBS: 0.19811068599600212
Fold 4 IBS: 0.2347314827338906
Fold 5 IBS: 0.2132301552578521
[I 2024-04-13 17:21:13,303] Trial 15 finished with value: 0.22320194848105324 and parameters: {'l1_ratio': 0.8435258665171791}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.23127505917693061
Fold 2 IBS: 0.2387436308857557
Fold 3 IBS: 0.19816889242045746
Fold 4 IBS: 0.23469462086384277
Fold 5 IBS: 0.21325596128747457
[I 2024-04-13 17:21:13,753] Trial 16 finished with value: 0.2232276329268922 and parameters: {'l1_ratio': 0.8046771700892117}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.23067563932750743
Fold 2 IBS: 0.2387662051315322
Fold 3 IBS: 0.19801236674184536
Fold 4 IBS: 0.23467114428831543
Fold 5 IBS: 0.2132603470606553
[I 2024-04-13 17:21:14,183] Trial 17 finished with value: 0.22307714050997113 and parameters: {'l1_ratio': 0.9853615392538034}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.2313214938002544
Fold 2 IBS: 0.2387244637914586
Fold 3 IBS: 0.1981885527916936
Fold 4 IBS: 0.2346821217175109
Fold 5 IBS: 0.21324801149133257
[I 2024-04-13 17:21:14,766] Trial 18 finished with value: 0.22323292871845002 and parameters: {'l1_ratio': 0.7922918930288001}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.2318903097346124
Fold 2 IBS: 0.23874057763843634
Fold 3 IBS: 0.19833008181007974
Fold 4 IBS: 0.23473739222323015
Fold 5 IBS: 0.2132099063476489
[I 2024-04-13 17:21:15,277] Trial 19 finished with value: 0.22338165355080147 and parameters: {'l1_ratio': 0.608409044915716}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.2310222588914642
Fold 2 IBS: 0.23874286416427298
Fold 3 IBS: 0.19814726845787722
Fold 4 IBS: 0.23467605383811255
Fold 5 IBS: 0.2132533289562371
[I 2024-04-13 17:21:15,689] Trial 20 finished with value: 0.2231683548615928 and parameters: {'l1_ratio': 0.8818811135844746}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.2307235787135728
Fold 2 IBS: 0.23874762432555396
Fold 3 IBS: 0.1980300686813725
Fold 4 IBS: 0.23465905289941497
Fold 5 IBS: 0.213252636837511
[I 2024-04-13 17:21:16,190] Trial 21 finished with value: 0.22308259229148503 and parameters: {'l1_ratio': 0.9705260458283718}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.23091653045479615
Fold 2 IBS: 0.23878551264792028
Fold 3 IBS: 0.1981036296130983
Fold 4 IBS: 0.2347035207436795
Fold 5 IBS: 0.21322165731814066
[I 2024-04-13 17:21:16,700] Trial 22 finished with value: 0.22314617015552698 and parameters: {'l1_ratio': 0.9130757617488995}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.23066729117484178
Fold 2 IBS: 0.2387694748544311
Fold 3 IBS: 0.19800928697034662
Fold 4 IBS: 0.23467324684699373
Fold 5 IBS: 0.2132616878871229
[I 2024-04-13 17:21:17,393] Trial 23 finished with value: 0.22307619754674723 and parameters: {'l1_ratio': 0.9879856951002318}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.23134603183771546
Fold 2 IBS: 0.23882383627428538
Fold 3 IBS: 0.19819897198785263
Fold 4 IBS: 0.23467549186963482
Fold 5 IBS: 0.2132437951818833
[I 2024-04-13 17:21:17,835] Trial 24 finished with value: 0.22325762543027433 and parameters: {'l1_ratio': 0.7858694646230915}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.2309246612486822

Fold 2 IBS: 0.23878224953918464
Fold 3 IBS: 0.19810697263118887
Fold 4 IBS: 0.23470141904586134
Fold 5 IBS: 0.21322019839910245
[I 2024-04-13 17:21:18,266] Trial 25 finished with value: 0.2231471001728039 and parameters: {'l1_ratio': 0.9106143729430608}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.23147019321082243
Fold 2 IBS: 0.23875695226908134
Fold 3 IBS: 0.19827506796402766
Fold 4 IBS: 0.23471962211441358
Fold 5 IBS: 0.21321402952933738
[I 2024-04-13 17:21:18,693] Trial 26 finished with value: 0.22328717301753645 and parameters: {'l1_ratio': 0.7417169602645222}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.23178762835502842
Fold 2 IBS: 0.23881660346673023
Fold 3 IBS: 0.19834944165203136
Fold 4 IBS: 0.23470201310790353
Fold 5 IBS: 0.2132448151903195
[I 2024-04-13 17:21:19,294] Trial 27 finished with value: 0.22338010035440262 and parameters: {'l1_ratio': 0.6494728799686162}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.23114672443723577
Fold 2 IBS: 0.238796697408482
Fold 3 IBS: 0.1981149430392922
Fold 4 IBS: 0.23472878650839757
Fold 5 IBS: 0.21322828290508086
[I 2024-04-13 17:21:19,995] Trial 28 finished with value: 0.2232030868596977 and parameters: {'l1_ratio': 0.8405678753809458}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.24681577366790722
Fold 2 IBS: 0.2317412878211876
Fold 3 IBS: 0.22840186854482916
Fold 4 IBS: 0.24141264790241582
Fold 5 IBS: 0.228969546862956
[I 2024-04-13 17:21:20,196] Trial 29 finished with value: 0.23546822495985914 and parameters: {'l1_ratio': 0.016175696683504215}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.2308945559388779
Fold 2 IBS: 0.23879431784725663
Fold 3 IBS: 0.19809460532461504
Fold 4 IBS: 0.23470919211310667
Fold 5 IBS: 0.21322559451017153
[I 2024-04-13 17:21:20,743] Trial 30 finished with value: 0.22314365314680557 and parameters: {'l1_ratio': 0.9197818493705627}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.2306720583643118
Fold 2 IBS: 0.23876760802592362
Fold 3 IBS: 0.19801104541073894
Fold 4 IBS: 0.23467204640058156
Fold 5 IBS: 0.2132609223445184
[I 2024-04-13 17:21:21,332] Trial 31 finished with value: 0.22307673610921483 and parameters: {'l1_ratio': 0.9864858075876226}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.23085968599623202
Fold 2 IBS: 0.2388082404807708
Fold 3 IBS: 0.1980803261410641
Fold 4 IBS: 0.2347181599773867
Fold 5 IBS: 0.21323073680430754
[I 2024-04-13 17:21:21,789] Trial 32 finished with value: 0.22313942987995222 and parameters: {'l1_ratio': 0.930580777401446}. Best is trial 11 with value: 0.22307290116668219.
Fold 1 IBS: 0.23063530165122484
Fold 2 IBS: 0.23878197873881626
Fold 3 IBS: 0.19799750470502983
Fold 4 IBS: 0.23468127992034005
Fold 5 IBS: 0.21326681583784948
[I 2024-04-13 17:21:22,214] Trial 33 finished with value: 0.2230725761706521 and parameters: {'l1_ratio': 0.9981458715067252}. Best is trial 33 with value: 0.2230725761706521.
Fold 1 IBS: 0.2330183342896255
Fold 2 IBS: 0.22970151009454903
Fold 3 IBS: 0.2242521178238971
Fold 4 IBS: 0.23758031969643498
Fold 5 IBS: 0.22599528980577538
[I 2024-04-13 17:21:22,439] Trial 34 finished with value: 0.2301095143420564 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 33 with value: 0.2230725761706521.
Fold 1 IBS: 0.23116204125130754
Fold 2 IBS: 0.23879040189644446
Fold 3 IBS: 0.1981213526904051
Fold 4 IBS: 0.23472472566073613
Fold 5 IBS: 0.2132254631282137
[I 2024-04-13 17:21:22,892] Trial 35 finished with value: 0.2232047969254214 and parameters: {'l1_ratio': 0.8361501509216206}. Best is trial 33 with value: 0.2230725761706521.
Fold 1 IBS: 0.23140605323886237
Fold 2 IBS: 0.23878411611082423
Fold 3 IBS: 0.19824511675498196
Fold 4 IBS: 0.23473710590366892
Fold 5 IBS: 0.2132251157725004
[I 2024-04-13 17:21:23,369] Trial 36 finished with value: 0.22327950155616758 and parameters: {'l1_ratio': 0.7585399538372601}. Best is trial 33 with value: 0.2230725761706521.
Fold 1 IBS: 0.23085214628784584
Fold 2 IBS: 0.2388112463606855
Fold 3 IBS: 0.19807724164243268
Fold 4 IBS: 0.23472009619143797
Fold 5 IBS: 0.2132320835918739
[I 2024-04-13 17:21:23,821] Trial 37 finished with value: 0.22313856281485517 and parameters: {'l1_ratio': 0.9329443285783949}. Best is trial 33 with value: 0.2230725761706521.
Fold 1 IBS: 0.23109147925137938
Fold 2 IBS: 0.23882481263298547
Fold 3 IBS: 0.19808419549989795
Fold 4 IBS: 0.2346579194878223
Fold 5 IBS: 0.21324177750624332
[I 2024-04-13 17:21:24,457] Trial 38 finished with value: 0.2231800368756657 and parameters: {'l1_ratio': 0.86237399701415}. Best is trial 33 with value: 0.2230725761706521.
Fold 1 IBS: 0.23204421303914705
Fold 2 IBS: 0.23874381520230406
Fold 3 IBS: 0.19834270493845588
Fold 4 IBS: 0.23475176570278664
Fold 5 IBS: 0.21321320684957837
[I 2024-04-13 17:21:25,114] Trial 39 finished with value: 0.22341914114645442 and parameters: {'l1_ratio': 0.5561256026976026}. Best is trial 33 with value: 0.2230725761706521.
Fold 1 IBS: 0.23063018219239556
Fold 2 IBS: 0.2387839760677504
Fold 3 IBS: 0.1979956219427225
Fold 4 IBS: 0.23468256436302337
Fold 5 IBS: 0.2132676350242507
[I 2024-04-13 17:21:25,776] Trial 40 finished with value: 0.2230719959180285 and parameters: {'l1_ratio': 0.9997874437591321}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23064141876045197
Fold 2 IBS: 0.2387795908327171
Fold 3 IBS: 0.19799975538704814
Fold 4 IBS: 0.23467974431827732
Fold 5 IBS: 0.2132658364831047
[I 2024-04-13 17:21:26,319] Trial 41 finished with value: 0.22307326915631984 and parameters: {'l1_ratio': 0.9961900756119856}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23081101986865452
Fold 2 IBS: 0.23882345107205474
Fold 3 IBS: 0.19806256955653523
Fold 4 IBS: 0.23472924051943386
Fold 5 IBS: 0.21323848741970272
[I 2024-04-13 17:21:26,868] Trial 42 finished with value: 0.2231329536872762 and parameters: {'l1_ratio': 0.9443407701485187}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23102814135283042
Fold 2 IBS: 0.23874047741599919
Fold 3 IBS: 0.19814970717392716
Fold 4 IBS: 0.23467451683200813
Fold 5 IBS: 0.2132523502079907
[I 2024-04-13 17:21:27,415] Trial 43 finished with value: 0.2231690385965511 and parameters: {'l1_ratio': 0.8801957740543597}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23270129101822348
Fold 2 IBS: 0.23876296150699639
Fold 3 IBS: 0.19852077686215444
Fold 4 IBS: 0.23472909342001627
Fold 5 IBS: 0.21322717675482078
[I 2024-04-13 17:21:28,098] Trial 44 finished with value: 0.22358825991244227 and parameters: {'l1_ratio': 0.32069521455978856}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23080629694709126
Fold 2 IBS: 0.23882516857028577
Fold 3 IBS: 0.19806080813596688
Fold 4 IBS: 0.23473034517892913
Fold 5 IBS: 0.21323925594219084
[I 2024-04-13 17:21:28,655] Trial 45 finished with value: 0.22313237495489274 and parameters: {'l1_ratio': 0.9457262757621758}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2306615536976216
Fold 2 IBS: 0.2387717204559571
Fold 3 IBS: 0.19800717152462505
Fold 4 IBS: 0.2346746908712946
Fold 5 IBS: 0.21326260877626954
[I 2024-04-13 17:21:29,151] Trial 46 finished with value: 0.22307554906515356 and parameters: {'l1_ratio': 0.9897957181801997}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23166142979396365
Fold 2 IBS: 0.238789701304281
Fold 3 IBS: 0.19825863065064692
Fold 4 IBS: 0.23466658328558748
Fold 5 IBS: 0.21322983845712504
[I 2024-04-13 17:21:29,723] Trial 47 finished with value: 0.22332123669832077 and parameters: {'l1_ratio': 0.6949407631028973}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23124988839958377
Fold 2 IBS: 0.23875409693086874
Fold 3 IBS: 0.19815826648148055
Fold 4 IBS: 0.2347013703861862
Fold 5 IBS: 0.21326025463021092
[I 2024-04-13 17:21:30,216] Trial 48 finished with value: 0.22322477536566604 and parameters: {'l1_ratio': 0.8115205184716434}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23064186143324203
Fold 2 IBS: 0.23877941797164778
Fold 3 IBS: 0.1979999183036993
Fold 4 IBS: 0.23467963315624418
Fold 5 IBS: 0.21326576558837756
[I 2024-04-13 17:21:30,695] Trial 49 finished with value: 0.22307331929064217 and parameters: {'l1_ratio': 0.9960487809029945}. Best is trial 40 with value: 0.2230719959180285.

Fold 1 IBS: 0.23103357095404822
Fold 2 IBS: 0.23873849199860037
Fold 3 IBS: 0.1981519591601307
Fold 4 IBS: 0.2346730973202225
Fold 5 IBS: 0.2132514462936442
[I 2024-04-13 17:21:31,270] Trial 50 finished with value: 0.22316971314532918 and parameters: {'l1_ratio': 0.8786447363305766}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23079344247298086
Fold 2 IBS: 0.23882983880964445
Fold 3 IBS: 0.1980560175062932
Fold 4 IBS: 0.23473334901576678
Fold 5 IBS: 0.21324134583800086
[I 2024-04-13 17:21:31,746] Trial 51 finished with value: 0.22313079872853722 and parameters: {'l1_ratio': 0.9495136153828908}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23077282357670065
Fold 2 IBS: 0.2388373168564218
Fold 3 IBS: 0.1980483437764446
Fold 4 IBS: 0.23464655857618702
Fold 5 IBS: 0.21324469257518483
[I 2024-04-13 17:21:32,206] Trial 52 finished with value: 0.22310994707218773 and parameters: {'l1_ratio': 0.9556391205035538}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2306624851542776
Fold 2 IBS: 0.23877135597986893
Fold 3 IBS: 0.19800751489218144
Fold 4 IBS: 0.23467445649567764
Fold 5 IBS: 0.21326245930829615
[I 2024-04-13 17:21:32,640] Trial 53 finished with value: 0.22307565436606036 and parameters: {'l1_ratio': 0.9895015064884438}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2309497485446885
Fold 2 IBS: 0.23877216390842518
Fold 3 IBS: 0.19811730091227647
Fold 4 IBS: 0.23469492327455696
Fold 5 IBS: 0.2132653461596034
[I 2024-04-13 17:21:33,089] Trial 54 finished with value: 0.22315989655991011 and parameters: {'l1_ratio': 0.9030866889112058}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23309789866041658
Fold 2 IBS: 0.230169476496387
Fold 3 IBS: 0.22510924714608654
Fold 4 IBS: 0.23838288662217333
Fold 5 IBS: 0.2266408524704772
[I 2024-04-13 17:21:33,446] Trial 55 finished with value: 0.23068007227910817 and parameters: {'l1_ratio': 0.132679519787263}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23064438791121233
Fold 2 IBS: 0.23877843124967865
Fold 3 IBS: 0.19800084823339736
Fold 4 IBS: 0.2346789986248601
Fold 5 IBS: 0.21326536091111886
[I 2024-04-13 17:21:33,904] Trial 56 finished with value: 0.22307360538605345 and parameters: {'l1_ratio': 0.9952429820612867}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23111532547029018
Fold 2 IBS: 0.2388158750445625
Fold 3 IBS: 0.19809329713186574
Fold 4 IBS: 0.23465163805215056
Fold 5 IBS: 0.21323779971216103
[I 2024-04-13 17:21:34,376] Trial 57 finished with value: 0.223182787082206 and parameters: {'l1_ratio': 0.8558109499183804}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23220133604200707
Fold 2 IBS: 0.23879622544588944
Fold 3 IBS: 0.19842040242325182
Fold 4 IBS: 0.23472489775453784
Fold 5 IBS: 0.21324073928985926
[I 2024-04-13 17:21:34,986] Trial 58 finished with value: 0.22347672019110912 and parameters: {'l1_ratio': 0.48369134769003763}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2307762528274104
Fold 2 IBS: 0.23883607425745756
Fold 3 IBS: 0.1980496191397845
Fold 4 IBS: 0.23464568620326
Fold 5 IBS: 0.2132441364289312
[I 2024-04-13 17:21:35,408] Trial 59 finished with value: 0.22311035377136873 and parameters: {'l1_ratio': 0.9546160040478635}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.230938990367231
Fold 2 IBS: 0.23877649215328814
Fold 3 IBS: 0.1981128693361661
Fold 4 IBS: 0.23469771090189115
Fold 5 IBS: 0.21321762451331458
[I 2024-04-13 17:21:35,893] Trial 60 finished with value: 0.2231487374543782 and parameters: {'l1_ratio': 0.9063024922478452}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23063322212592727
Fold 2 IBS: 0.23878279017829054
Fold 3 IBS: 0.19799673983299865
Fold 4 IBS: 0.2346818017397961
Fold 5 IBS: 0.21326714864026686
[I 2024-04-13 17:21:36,344] Trial 61 finished with value: 0.2230723405034559 and parameters: {'l1_ratio': 0.9988121553290725}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23065654756645257
Fold 2 IBS: 0.2387736787529193
Fold 3 IBS: 0.19800532653160335
Fold 4 IBS: 0.23467594247033702
Fold 5 IBS: 0.21326341186428185
[I 2024-04-13 17:21:36,770] Trial 62 finished with value: 0.22307498143711882 and parameters: {'l1_ratio': 0.9913793723218413}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23076991655346588
Fold 2 IBS: 0.23872934456888112
Fold 3 IBS: 0.19804726291414101
Fold 4 IBS: 0.2346472978625157
Fold 5 IBS: 0.21324516388160986
[I 2024-04-13 17:21:37,275] Trial 63 finished with value: 0.2230877971561227 and parameters: {'l1_ratio': 0.956507797023033}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2324403093738486
Fold 2 IBS: 0.23874123266597813
Fold 3 IBS: 0.19849944078301013
Fold 4 IBS: 0.23469489651223363
Fold 5 IBS: 0.21321664012267086
[I 2024-04-13 17:21:37,730] Trial 64 finished with value: 0.2235185038915483 and parameters: {'l1_ratio': 0.4203674682694325}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23064130004554592
Fold 2 IBS: 0.238779637188866
Fold 3 IBS: 0.19799971169744734
Fold 4 IBS: 0.23467977412860969
Fold 5 IBS: 0.21326585549496468
[I 2024-04-13 17:21:38,146] Trial 65 finished with value: 0.22307325571108674 and parameters: {'l1_ratio': 0.9962279731597624}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2309235521807706
Fold 2 IBS: 0.238782694800754
Fold 3 IBS: 0.19810651650612987
Fold 4 IBS: 0.23470170582767214
Fold 5 IBS: 0.2132203974681341
[I 2024-04-13 17:21:38,613] Trial 66 finished with value: 0.22314697335669215 and parameters: {'l1_ratio': 0.9109494856026517}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23077612845532672
Fold 2 IBS: 0.23883611933183843
Fold 3 IBS: 0.19804957287863054
Fold 4 IBS: 0.23464571784776067
Fold 5 IBS: 0.21324415660251592
[I 2024-04-13 17:21:39,004] Trial 67 finished with value: 0.22311033902321445 and parameters: {'l1_ratio': 0.9546530799943637}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23116624497320032
Fold 2 IBS: 0.23878867228820283
Fold 3 IBS: 0.1981231132132957
Fold 4 IBS: 0.2347236698178255
Fold 5 IBS: 0.21322468848948706
[I 2024-04-13 17:21:39,459] Trial 68 finished with value: 0.22320527775640228 and parameters: {'l1_ratio': 0.8349442476611082}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23100642138328256
Fold 2 IBS: 0.23874928274331292
Fold 3 IBS: 0.1981407083080134
Fold 4 IBS: 0.23468018731123838
Fold 5 IBS: 0.21325596118834803
[I 2024-04-13 17:21:39,876] Trial 69 finished with value: 0.22316651218683908 and parameters: {'l1_ratio': 0.886444299803612}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23087184644894335
Fold 2 IBS: 0.23880338750206123
Fold 3 IBS: 0.1980853048199452
Fold 4 IBS: 0.23471503401637117
Fold 5 IBS: 0.2132296506121318
[I 2024-04-13 17:21:40,315] Trial 70 finished with value: 0.22314104467989054 and parameters: {'l1_ratio': 0.9267890524797322}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2306483084623203
Fold 2 IBS: 0.2387768995719815
Fold 3 IBS: 0.19800229165952932
Fold 4 IBS: 0.2346780136535556
Fold 5 IBS: 0.2132647327436488
[I 2024-04-13 17:21:40,832] Trial 71 finished with value: 0.22307404921820712 and parameters: {'l1_ratio': 0.9939946276609194}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23063620348705863
Fold 2 IBS: 0.23878162678592738
Fold 3 IBS: 0.19799783644987456
Fold 4 IBS: 0.23468105358743857
Fold 5 IBS: 0.21326667148939826
[I 2024-04-13 17:21:41,285] Trial 72 finished with value: 0.2230726783599395 and parameters: {'l1_ratio': 0.9978571437760119}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23074453051089996
Fold 2 IBS: 0.23873936978619145
Fold 3 IBS: 0.1980378350396427
Fold 4 IBS: 0.2346537446064961
Fold 5 IBS: 0.2132492522617273
[I 2024-04-13 17:21:41,720] Trial 73 finished with value: 0.2230849464409915 and parameters: {'l1_ratio': 0.9641473708025002}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23063250553903744
Fold 2 IBS: 0.23878306975417768
Fold 3 IBS: 0.19799647629420533
Fold 4 IBS: 0.23468198152947942
Fold 5 IBS: 0.21326726330572976
[I 2024-04-13 17:21:42,296] Trial 74 finished with value: 0.22307225928452593 and parameters: {'l1_ratio': 0.9990419168427266}. Best is trial 40 with value: 0.2230719959180285.

Fold 1 IBS: 0.2308833739728706
Fold 2 IBS: 0.23879879077117747
Fold 3 IBS: 0.19809001921386574
Fold 4 IBS: 0.23471207316639198
Fold 5 IBS: 0.21322759479315892
[I 2024-04-13 17:21:42,823] Trial 75 finished with value: 0.22314237038349294 and parameters: {'l1_ratio': 0.9232248440809541}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23073384996338173
Fold 2 IBS: 0.23874357988596578
Fold 3 IBS: 0.19803387434188405
Fold 4 IBS: 0.23465645199769555
Fold 5 IBS: 0.21325097847391167
[I 2024-04-13 17:21:43,275] Trial 76 finished with value: 0.22308374693256777 and parameters: {'l1_ratio': 0.9673906281038791}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23096554530535066
Fold 2 IBS: 0.23876579972169462
Fold 3 IBS: 0.19812381484611113
Fold 4 IBS: 0.2346908244723955
Fold 5 IBS: 0.2132627355802848
[I 2024-04-13 17:21:43,670] Trial 77 finished with value: 0.22316174398516733 and parameters: {'l1_ratio': 0.8983978427418612}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23085103490594788
Fold 2 IBS: 0.23881168924131652
Fold 3 IBS: 0.1980767871290289
Fold 4 IBS: 0.23472038147142332
Fold 5 IBS: 0.21323228203130404
[I 2024-04-13 17:21:44,109] Trial 78 finished with value: 0.2231384349558041 and parameters: {'l1_ratio': 0.9332935461138596}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23124053273102269
Fold 2 IBS: 0.2387579798120943
Fold 3 IBS: 0.19815432250321982
Fold 4 IBS: 0.234703874512215
Fold 5 IBS: 0.21326184757677794
[I 2024-04-13 17:21:44,524] Trial 79 finished with value: 0.22322371142706596 and parameters: {'l1_ratio': 0.8140878863137256}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2310720165750356
Fold 2 IBS: 0.23883209019722523
Fold 3 IBS: 0.19807678061080497
Fold 4 IBS: 0.23466303466995742
Fold 5 IBS: 0.2132450342774329
[I 2024-04-13 17:21:44,968] Trial 80 finished with value: 0.22317779126609122 and parameters: {'l1_ratio': 0.8677900254919308}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2307377793123743
Fold 2 IBS: 0.23874203153315715
Fold 3 IBS: 0.1980353310717638
Fold 4 IBS: 0.23465545629244827
Fold 5 IBS: 0.21325034361379966
[I 2024-04-13 17:21:45,382] Trial 81 finished with value: 0.22308418836470864 and parameters: {'l1_ratio': 0.9661954209859951}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2307109770096607
Fold 2 IBS: 0.23875235788302188
Fold 3 IBS: 0.19802540390262335
Fold 4 IBS: 0.23466224026460886
Fold 5 IBS: 0.21325466920117092
[I 2024-04-13 17:21:45,839] Trial 82 finished with value: 0.22308112965221713 and parameters: {'l1_ratio': 0.9743950815911203}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2307207268596017
Fold 2 IBS: 0.23874874653024028
Fold 3 IBS: 0.1980290125897776
Fold 4 IBS: 0.23465977457502607
Fold 5 IBS: 0.2132530969942173
[I 2024-04-13 17:21:46,242] Trial 83 finished with value: 0.22308227150977258 and parameters: {'l1_ratio': 0.9713994850760806}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2306347354289038
Fold 2 IBS: 0.23878219969795192
Fold 3 IBS: 0.19799729642961258
Fold 4 IBS: 0.23468142201429476
Fold 5 IBS: 0.21326690646136584
[I 2024-04-13 17:21:46,772] Trial 84 finished with value: 0.22307251200642578 and parameters: {'l1_ratio': 0.9983272193741751}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23085453065345085
Fold 2 IBS: 0.23881029603061216
Fold 3 IBS: 0.19807821689134084
Fold 4 IBS: 0.23471948404133425
Fold 5 IBS: 0.21323165778744188
[I 2024-04-13 17:21:47,346] Trial 85 finished with value: 0.22313883708083598 and parameters: {'l1_ratio': 0.9321958279027125}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23216434823661716
Fold 2 IBS: 0.23880004238211033
Fold 3 IBS: 0.19840173136425923
Fold 4 IBS: 0.2347163845336292
Fold 5 IBS: 0.21324092349349894
[I 2024-04-13 17:21:47,859] Trial 86 finished with value: 0.223464686002023 and parameters: {'l1_ratio': 0.5322933555815866}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2314179062441613
Fold 2 IBS: 0.23879815190856019
Fold 3 IBS: 0.19822961671714784
Fold 4 IBS: 0.2346559761283841
Fold 5 IBS: 0.21323140197856585
[I 2024-04-13 17:21:48,294] Trial 87 finished with value: 0.22326661059536385 and parameters: {'l1_ratio': 0.7675230034738174}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2306433234920411
Fold 2 IBS: 0.238778846991712
Fold 3 IBS: 0.19800045642578065
Fold 4 IBS: 0.23467926597583047
Fold 5 IBS: 0.2132655314159108
[I 2024-04-13 17:21:48,735] Trial 88 finished with value: 0.223073484860255 and parameters: {'l1_ratio': 0.995582341820056}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23184661470385673
Fold 2 IBS: 0.23879272470770813
Fold 3 IBS: 0.1982711048648117
Fold 4 IBS: 0.2346851816336428
Fold 5 IBS: 0.2132341342249423
[I 2024-04-13 17:21:49,182] Trial 89 finished with value: 0.22336595202699233 and parameters: {'l1_ratio': 0.6363685228271639}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23081465950809646
Fold 2 IBS: 0.23882212692949262
Fold 3 IBS: 0.1980639274328951
Fold 4 IBS: 0.23472838886293468
Fold 5 IBS: 0.21323789492698264
[I 2024-04-13 17:21:49,565] Trial 90 finished with value: 0.22313339953208028 and parameters: {'l1_ratio': 0.9432752485258721}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2307089792458117
Fold 2 IBS: 0.23875314314968904
Fold 3 IBS: 0.1980246648290744
Fold 4 IBS: 0.23466274519212826
Fold 5 IBS: 0.2132549911652494
[I 2024-04-13 17:21:50,023] Trial 91 finished with value: 0.22308090471639058 and parameters: {'l1_ratio': 0.9750107074324023}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23065136552498858
Fold 2 IBS: 0.23877570482139518
Fold 3 IBS: 0.1980034174924842
Fold 4 IBS: 0.23467724535299936
Fold 5 IBS: 0.2132642427630697
[I 2024-04-13 17:21:50,511] Trial 92 finished with value: 0.2230743951909874 and parameters: {'l1_ratio': 0.9930229637338166}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23095589718432086
Fold 2 IBS: 0.23876968799828915
Fold 3 IBS: 0.19811983538945535
Fold 4 IBS: 0.234693328673171
Fold 5 IBS: 0.21326433052363414
[I 2024-04-13 17:21:51,091] Trial 93 finished with value: 0.2231606159537741 and parameters: {'l1_ratio': 0.9012569742389078}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23088217972508343
Fold 2 IBS: 0.23879926817895214
Fold 3 IBS: 0.1980895296491999
Fold 4 IBS: 0.23471238067224312
Fold 5 IBS: 0.2132278082986223
[I 2024-04-13 17:21:51,533] Trial 94 finished with value: 0.22314223330482016 and parameters: {'l1_ratio': 0.9235937887433313}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23063186561559076
Fold 2 IBS: 0.2387833194028455
Fold 3 IBS: 0.19799624096273494
Fold 4 IBS: 0.23468214207372903
Fold 5 IBS: 0.21326736569711519
[I 2024-04-13 17:21:52,007] Trial 95 finished with value: 0.22307218675040308 and parameters: {'l1_ratio': 0.9992471693779538}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2306341884512633
Fold 2 IBS: 0.23878241313521054
Fold 3 IBS: 0.1979970952420453
Fold 4 IBS: 0.23468155927121168
Fold 5 IBS: 0.2132669940000888
[I 2024-04-13 17:21:52,473] Trial 96 finished with value: 0.22307245001996395 and parameters: {'l1_ratio': 0.998502453937228}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23080518697371297
Fold 2 IBS: 0.23882557209029476
Fold 3 IBS: 0.19806039426913125
Fold 4 IBS: 0.23473060471569493
Fold 5 IBS: 0.21323943650725616
[I 2024-04-13 17:21:52,898] Trial 97 finished with value: 0.22313223891121803 and parameters: {'l1_ratio': 0.9460523630235538}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.23269444514634482
Fold 2 IBS: 0.23871202018460064
Fold 3 IBS: 0.19843816091329575
Fold 4 IBS: 0.23469457584659964
Fold 5 IBS: 0.2132091355855683
[I 2024-04-13 17:21:53,404] Trial 98 finished with value: 0.22354966753528185 and parameters: {'l1_ratio': 0.3410246190042779}. Best is trial 40 with value: 0.2230719959180285.
Fold 1 IBS: 0.2307432067442748
Fold 2 IBS: 0.2387398918427547
Fold 3 IBS: 0.19803734395585235
Fold 4 IBS: 0.23465408032329596
Fold 5 IBS: 0.21324946630943659
[I 2024-04-13 17:21:53,952] Trial 99 finished with value: 0.22308479783512286 and parameters: {'l1_ratio': 0.964548404109892}. Best is trial 40 with value: 0.2230719959180285.


* Best trial for IBS:
 FrozenTrial(number=40, state=TrialState.COMPLETE, values=[0.2230719959180285], datetime_start=datetime.datetime(2024, 4, 13, 17, 21, 25, 119253), datetime_complete=datetime.datetime(2024, 4, 13, 17, 21, 25, 776451), params={'l1_ratio': 0.9997874437591321}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=40, value=None)


* Best Score for IBS:
 0.2230719959180285

In [42]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [43]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.633
train_ibs:  0.223

#### Test

In [44]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [45]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.6964995386793018)

test_cindex : 0.55

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.9997874437591321)

test_ibs:  0.233

In [46]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [47]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:21:54,417] A new study created in memory with name: no-name-03d57495-0bbc-4ea9-a150-8984fb80bd2e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:21:59,309] Trial 0 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6255130467702362.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:22:03,374] Trial 1 finished with value: 0.6294058722016631 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.6294058722016631.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:22:06,169] Trial 2 finished with value: 0.6263714158689486 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.6294058722016631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:22:07,611] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.6294058722016631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:22:09,436] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.6294058722016631.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:22:14,165] Trial 5 finished with value: 0.6327052496375349 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:22:19,700] Trial 6 finished with value: 0.6263714158689486 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.6327052496375349.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:22:22,368] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.6327052496375349.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:22:30,262] Trial 8 finished with value: 0.5206008583690986 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:22:34,051] Trial 9 finished with value: 0.6327052496375349 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 5 with value: 0.6327052496375349.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:22:34,558] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 5 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:22:36,299] Trial 11 finished with value: 0.6114286538928541 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 109, 'oob_score': False, 'max_samples': 0.9866547731576396, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018098423978521135, 'warm_start': False}. Best is trial 5 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:22:42,585] Trial 12 finished with value: 0.6294058722016631 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 498, 'oob_score': False, 'max_samples': 0.8392165520631284, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08506650508113567, 'warm_start': False}. Best is trial 5 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:22:48,534] Trial 13 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.4760095384782845, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.008606277463368957, 'warm_start': False}. Best is trial 5 with value: 0.6327052496375349.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:22:50,358] Trial 14 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 192, 'oob_score': True, 'max_samples': 0.8364130211722378, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1584235940276062, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976

Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:22:51,825] Trial 15 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.834513235692611, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1695220400209786, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:22:52,822] Trial 16 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.5394490956397513, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1315336313225035, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:22:53,209] Trial 17 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 20, 'oob_score': True, 'max_samples': 0.6922766834241219, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.20705158222188405, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:22:55,909] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 348, 'oob_score': True, 'max_samples': 0.3744826915652821, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:22:57,309] Trial 19 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 4, 'n_estimators': 147, 'oob_score': True, 'max_samples': 0.8010473327367074, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0953270257747095, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:22:59,016] Trial 20 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 220, 'oob_score': True, 'max_samples': 0.5607581032340154, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05900586545553409, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:23:00,889] Trial 21 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 232, 'oob_score': True, 'max_samples': 0.5547798318935973, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0587391455650732, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:23:02,650] Trial 22 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 234, 'oob_score': True, 'max_samples': 0.5018093912461808, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07918224002301208, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:23:04,226] Trial 23 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.6685665866756954, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1646443106442519, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:23:04,971] Trial 24 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 79, 'oob_score': True, 'max_samples': 0.4244864901081151, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05731140536615822, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:23:06,381] Trial 25 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 172, 'oob_score': True, 'max_samples': 0.1861830169994726, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12518612267711432, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:23:07,851] Trial 26 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 198, 'oob_score': True, 'max_samples': 0.5745565830775333, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20026675175735062, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:23:09,725] Trial 27 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 254, 'oob_score': True, 'max_samples': 0.40242880638289025, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.057405573871064736, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:23:10,903] Trial 28 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 142, 'oob_score': True, 'max_samples': 0.7778458290979987, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2537267186473678, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:23:13,201] Trial 29 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 312, 'oob_score': True, 'max_samples': 0.7069732604894606, 'max_features': None, 'min_weight_fraction_leaf': 0.14297562243940504, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:23:13,963] Trial 30 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 87, 'oob_score': True, 'max_samples': 0.5224151807092315, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18579705931910293, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:23:15,757] Trial 31 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 234, 'oob_score': True, 'max_samples': 0.4804335394063386, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08439084251159173, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:23:17,581] Trial 32 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 272, 'oob_score': True, 'max_samples': 0.5288432021501348, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09654248715305006, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:23:19,338] Trial 33 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 222, 'oob_score': True, 'max_samples': 0.3317175390522439, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06274147809898706, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:23:20,893] Trial 34 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 181, 'oob_score': True, 'max_samples': 0.7346747574511208, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12318470964348038, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:23:22,658] Trial 35 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 251, 'oob_score': True, 'max_samples': 0.6409649823357615, 'max_features': None, 'min_weight_fraction_leaf': 0.041799651789036885, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:23:25,478] Trial 36 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.3445095149903548, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22859210147015824, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:23:27,280] Trial 37 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.584816568591167, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10561254608921847, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:23:28,648] Trial 38 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 150, 'oob_score': True, 'max_samples': 0.4401699854815214, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15157705783308448, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:23:31,493] Trial 39 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.24954610099274321, 'max_features': None, 'min_weight_fraction_leaf': 0.07712372544162568, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:23:34,313] Trial 40 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 12, 'n_estimators': 395, 'oob_score': True, 'max_samples': 0.9043304933469648, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.001667064486576518, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:23:36,085] Trial 41 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 250, 'oob_score': True, 'max_samples': 0.38328368617019903, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04019270953967638, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:23:37,866] Trial 42 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 261, 'oob_score': True, 'max_samples': 0.2755450531148367, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06643718664508559, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:23:40,200] Trial 43 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 286, 'oob_score': True, 'max_samples': 0.6305639851800665, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.030621206130462944, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:23:42,431] Trial 44 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 232, 'oob_score': True, 'max_samples': 0.4005082288778946, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11527878914787343, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:23:43,985] Trial 45 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 326, 'oob_score': False, 'max_samples': 0.4850045749679899, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04442341421119787, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:23:48,141] Trial 46 finished with value: 0.6099077413453257 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 212, 'oob_score': True, 'max_samples': 0.9856992496851368, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07695708954271245, 'warm_start': False}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 17:23:48,972] Trial 47 finished with value: 0.6109819234664691 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 189, 'oob_score': False, 'max_samples': 0.5068348574187561, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10756373104546446, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:23:53,276] Trial 48 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.28962267207477743, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.491438551581221, 'warm_start': False}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:23:55,677] Trial 49 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 276, 'oob_score': True, 'max_samples': 0.5477829518864415, 'max_features': None, 'min_weight_fraction_leaf': 0.001251640832049719, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:23:56,414] Trial 50 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.2126094758362771, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.028637316817413615, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:23:58,748] Trial 51 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.6890482667198663, 'max_features': None, 'min_weight_fraction_leaf': 0.13959325703296158, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:24:00,928] Trial 52 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.8735377984745137, 'max_features': None, 'min_weight_fraction_leaf': 0.17813118988310606, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:24:03,043] Trial 53 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 261, 'oob_score': True, 'max_samples': 0.7585633072953784, 'max_features': None, 'min_weight_fraction_leaf': 0.057157832614666865, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:24:04,535] Trial 54 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.618744480512109, 'max_features': None, 'min_weight_fraction_leaf': 0.13987984175376147, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:24:06,340] Trial 55 finished with value: 0.5 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 205, 'oob_score': True, 'max_samples': 0.5754560082388536, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2886607381144328, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:24:13,479] Trial 56 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 384, 'oob_score': True, 'max_samples': 0.7182532763821678, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22913660624836418, 'warm_start': False}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:24:16,263] Trial 57 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 317, 'oob_score': True, 'max_samples': 0.8232445639619075, 'max_features': None, 'min_weight_fraction_leaf': 0.15250792948632785, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:24:18,713] Trial 58 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 221, 'oob_score': True, 'max_samples': 0.4343405889356382, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09315166736149717, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:24:20,609] Trial 59 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 353, 'oob_score': False, 'max_samples': 0.6650848327490035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0724126516226486, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:24:26,966] Trial 60 finished with value: 0.6327052496375349 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 284, 'oob_score': True, 'max_samples': 0.46127084399117657, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01866906312241065, 'warm_start': False}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:24:29,428] Trial 61 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 240, 'oob_score': True, 'max_samples': 0.5478917760806427, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08550635145616804, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:24:31,436] Trial 62 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 191, 'oob_score': True, 'max_samples': 0.49829003878823974, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05359730355302367, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:24:33,560] Trial 63 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 224, 'oob_score': True, 'max_samples': 0.4106598704313081, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11661215979866671, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:24:36,105] Trial 64 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 263, 'oob_score': True, 'max_samples': 0.4594553940752336, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09664165020494415, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:24:38,357] Trial 65 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 166, 'oob_score': True, 'max_samples': 0.3661142067993075, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.37972904898901283, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:24:41,422] Trial 66 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 244, 'oob_score': True, 'max_samples': 0.5725179686151356, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07993392819622973, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:24:44,262] Trial 67 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 309, 'oob_score': True, 'max_samples': 0.6013681444653132, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.19762987851837188, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:24:46,139] Trial 68 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 204, 'oob_score': True, 'max_samples': 0.7928304448119687, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13254439670881907, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:24:48,847] Trial 69 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 337, 'oob_score': True, 'max_samples': 0.5120955514961736, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1631151242503615, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:24:52,842] Trial 70 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 461, 'oob_score': True, 'max_samples': 0.8828095925545719, 'max_features': None, 'min_weight_fraction_leaf': 0.03611145294853056, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:24:56,471] Trial 71 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 1, 'n_estimators': 280, 'oob_score': True, 'max_samples': 0.528495961897175, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1007517689780663, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:24:58,969] Trial 72 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 268, 'oob_score': True, 'max_samples': 0.47662176448580856, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06337980306280333, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:00,394] Trial 73 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 1, 'n_estimators': 179, 'oob_score': True, 'max_samples': 0.6530716069933915, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09023938031045833, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:25:02,798] Trial 74 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 296, 'oob_score': True, 'max_samples': 0.43719761276009056, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11024034763232116, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:04,846] Trial 75 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 233, 'oob_score': True, 'max_samples': 0.5604011462068712, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01575491008809269, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:06,940] Trial 76 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 250, 'oob_score': True, 'max_samples': 0.6070216667631669, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05029121345451096, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:08,135] Trial 77 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 215, 'oob_score': False, 'max_samples': 0.6960162417635966, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14309898286507516, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:25:12,425] Trial 78 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 194, 'oob_score': True, 'max_samples': 0.5323796891868864, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11852730503092285, 'warm_start': False}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:14,298] Trial 79 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 152, 'oob_score': True, 'max_samples': 0.3540620199926714, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07431828685832398, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:25:16,855] Trial 80 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 1, 'n_estimators': 257, 'oob_score': True, 'max_samples': 0.3888272103322673, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18181277227524917, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:19,039] Trial 81 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 225, 'oob_score': True, 'max_samples': 0.7417909490707818, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12371623352128643, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:21,382] Trial 82 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 237, 'oob_score': True, 'max_samples': 0.851682015655634, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09002144362320269, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:22,991] Trial 83 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 184, 'oob_score': True, 'max_samples': 0.9368992805301779, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06498217831863393, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:25,720] Trial 84 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 275, 'oob_score': True, 'max_samples': 0.7290774594260993, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10497678490347764, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:25:27,567] Trial 85 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 210, 'oob_score': True, 'max_samples': 0.4908092331516611, 'max_features': None, 'min_weight_fraction_leaf': 0.12954225715860762, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:29,225] Trial 86 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 176, 'oob_score': True, 'max_samples': 0.7667311063234076, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04387678699248633, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:25:30,385] Trial 87 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 199, 'oob_score': False, 'max_samples': 0.31686697311123163, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1684558553526867, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:25:33,070] Trial 88 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': True, 'max_samples': 0.6925667732312957, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15228621959965946, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:25:39,674] Trial 89 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 306, 'oob_score': True, 'max_samples': 0.41410668235902465, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.027627831657693384, 'warm_start': False}. Best is trial 14 with value: 0.6400441700740036.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:40,914] Trial 90 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.8146976876746325, 'max_features': None, 'min_weight_fraction_leaf': 0.07522082999302818, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:43,313] Trial 91 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 248, 'oob_score': True, 'max_samples': 0.4541487022955591, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03953268928913775, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:45,685] Trial 92 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 268, 'oob_score': True, 'max_samples': 0.37430078621530505, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05901220850245173, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:48,067] Trial 93 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 232, 'oob_score': True, 'max_samples': 0.5126914112379174, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04896176901470056, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:50,265] Trial 94 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 254, 'oob_score': True, 'max_samples': 0.5863445968021647, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08256437422919713, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:25:50,530] Trial 95 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 4, 'oob_score': True, 'max_samples': 0.30534098323418335, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09649899801653052, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:25:52,353] Trial 96 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.6329052510076999, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03157068386507741, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:53,787] Trial 97 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 163, 'oob_score': True, 'max_samples': 0.3933851223956673, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06789925388895984, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:25:56,540] Trial 98 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.47371815766318826, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2700070087662135, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605

[I 2024-04-13 17:25:59,504] A new study created in memory with name: no-name-48d3b35f-72f5-4e1c-9b1e-3135730a03a8

Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:25:59,488] Trial 99 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.5575728362061352, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.006981928835051832, 'warm_start': True}. Best is trial 14 with value: 0.6400441700740036.


* Best trial for C-index:
 FrozenTrial(number=14, state=TrialState.COMPLETE, values=[0.6400441700740036], datetime_start=datetime.datetime(2024, 4, 13, 17, 22, 48, 555506), datetime_complete=datetime.datetime(2024, 4, 13, 17, 22, 50, 357025), params={'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 192, 'oob_score': True, 'max_samples': 0.8364130211722378, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1584235940276062, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=14, value=None)


* Best Score for C-index:
 0.6400441700740036

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23710564089221847
Fold 2 IBS: 0.23121846181319633
Fold 3 IBS: 0.21096016309303992
Fold 4 IBS: 0.21573826614239536
Fold 5 IBS: 0.212324521064434
[I 2024-04-13 17:26:06,670] Trial 0 finished with value: 0.2214694106010568 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.2214694106010568.
Fold 1 IBS: 0.24060152167027965
Fold 2 IBS: 0.2209950314538435
Fold 3 IBS: 0.21669243635771532
Fold 4 IBS: 0.2221683056573396
Fold 5 IBS: 0.21282722042726435
[I 2024-04-13 17:26:08,122] Trial 1 finished with value: 0.22265690311328848 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 0 with value: 0.2214694106010568.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-13 17:26:09,217] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 0 with value: 0.2214694106010568.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-13 17:26:15,118] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 0 with value: 0.2214694106010568.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-13 17:26:20,334] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 0 with value: 0.2214694106010568.
Fold 1 IBS: 0.240474329891996
Fold 2 IBS: 0.22155473094407582
Fold 3 IBS: 0.21564809212096914
Fold 4 IBS: 0.22050153338190698
Fold 5 IBS: 0.21178926016759325
[I 2024-04-13 17:26:27,530] Trial 5 finished with value: 0.22199358930130822 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 0 with value: 0.2214694106010568.
Fold 1 IBS: 0.2312739566337048
Fold 2 IBS: 0.2245939082552946
Fold 3 IBS: 0.2136532587019048
Fold 4 IBS: 0.22200238801297023
Fold 5 IBS: 0.21237756902288815
[I 2024-04-13 17:26:33,254] Trial 6 finished with value: 0.22078021612535254 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 6 with value: 0.22078021612535254.
Fold 1 IBS: 0.24604679315308237
Fold 2 IBS: 0.23150801657368342
Fold 3 IBS: 0.22873718114898342
Fold 4 IBS: 0.24074389684473219
Fold 5 IBS: 0.22922261981206593
[I 2024-04-13 17:26:39,440] Trial 7 finished with value: 0.23525170150650948 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 6 with value: 0.22078021612535254.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-13 17:26:48,301] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 6 with value: 0.22078021612535254.
Fold 1 IBS: 0.24017479738345834
Fold 2 IBS: 0.22123482083132343
Fold 3 IBS: 0.21712707002799697
Fold 4 IBS: 0.22255635069810478
Fold 5 IBS: 0.213223331444723
[I 2024-04-13 17:26:50,339] Trial 9 finished with value: 0.2228632740771213 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 6 with value: 0.22078021612535254.
Fold 1 IBS: 0.24645571521465787
Fold 2 IBS: 0.23214351218858914
Fold 3 IBS: 0.23029990468218745
Fold 4 IBS: 0.24091247880712954
Fold 5 IBS: 0.22969387017589088
[I 2024-04-13 17:27:00,826] Trial 10 finished with value: 0.235901096213691 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3251129986182119}. Best is trial 6 with value: 0.22078021612535254.
Fold 1 IBS: 0.23075443031786103
Fold 2 IBS: 0.22895608042965515
Fold 3 IBS: 0.20833641967903235
Fold 4 IBS: 0.21681150467342705
Fold 5 IBS: 0.21244552210534107
[I 2024-04-13 17:27:06,552] Trial 11 finished with value: 0.21946079144106329 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.9485893528798968, 'max_features': None, 'min_weight_fraction_leaf': 0.34713111632234195}. Best is trial 11 with value: 0.21946079144106329.
Fold 1 IBS: 0.23344487135294223
Fold 2 IBS: 0.23050526816052078
Fold 3 IBS: 0.20832332242657933
Fold 4 IBS: 0.21590053898759287
Fold 5 IBS: 0.21263061844676548
[I 2024-04-13 17:27:10,841] Trial 12 finished with value: 0.22016092387488015 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.9971022097505926, 'max_features': None, 'min_weight_fraction_leaf': 0.3422783618261815}. Best is trial 11 with value: 0.21946079144106329.
Fold 1 IBS: 0.2288284550270388
Fold 2 IBS: 0.2277892234940571
Fold 3 IBS: 0.20901447524788325
Fold 4 IBS: 0.2180727445158178
Fold 5 IBS: 0.2121093678428414
[I 2024-04-13 17:27:17,491] Trial 13 finished with value: 0.2191628532255277 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 359, 'oob_score': False, 'max_samples': 0.9753664612895862, 'max_features': None, 'min_weight_fraction_leaf': 0.3730417406708304}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.24635125096148527
Fold 2 IBS: 0.2321556898765135
Fold 3 IBS: 0.22957786422127407
Fold 4 IBS: 0.24149504120826637
Fold 5 IBS: 0.23018283527932148
[I 2024-04-13 17:27:24,297] Trial 14 finished with value: 0.23595253630937213 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 397, 'oob_score': False, 'max_samples': 0.8183874600354049, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4786542417148672}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.22872048998258357
Fold 2 IBS: 0.2269374970210941
Fold 3 IBS: 0.2097409816613026
Fold 4 IBS: 0.2191695216894948
Fold 5 IBS: 0.21208737647112036
[I 2024-04-13 17:27:35,232] Trial 15 finished with value: 0.2193311733651191 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.9974444650419153, 'max_features': None, 'min_weight_fraction_leaf': 0.3896873411108393}. Best is trial 13 with value: 0.2191628532255277.

Fold 1 IBS: 0.2463530160956001
Fold 2 IBS: 0.23214245101943368
Fold 3 IBS: 0.22953570528793116
Fold 4 IBS: 0.2415165937767366
Fold 5 IBS: 0.23022709164530664
[I 2024-04-13 17:27:45,332] Trial 16 finished with value: 0.23595497156500161 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 477, 'oob_score': False, 'max_samples': 0.8047347883829389, 'max_features': None, 'min_weight_fraction_leaf': 0.41678116745501104}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.23510851547899966
Fold 2 IBS: 0.23223859248797624
Fold 3 IBS: 0.211706502863085
Fold 4 IBS: 0.21589791970606395
Fold 5 IBS: 0.21264558675590398
[I 2024-04-13 17:27:53,279] Trial 17 finished with value: 0.22151942345840578 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.9861686560685959, 'max_features': None, 'min_weight_fraction_leaf': 0.27567242746210224}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.24562274273263757
Fold 2 IBS: 0.23189274965155487
Fold 3 IBS: 0.22903635869810743
Fold 4 IBS: 0.24034942697941203
Fold 5 IBS: 0.2284553966575398
[I 2024-04-13 17:28:03,415] Trial 18 finished with value: 0.23507133494385032 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 17, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.759991620647303, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3734338881063671}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.2463636193796079
Fold 2 IBS: 0.23213115029519132
Fold 3 IBS: 0.22952748745211635
Fold 4 IBS: 0.2415122328458159
Fold 5 IBS: 0.230262569601828
[I 2024-04-13 17:28:11,353] Trial 19 finished with value: 0.2359594119149119 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 497, 'oob_score': False, 'max_samples': 0.8767429551432542, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.444790790880338}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.23610750301132755
Fold 2 IBS: 0.22287570967658063
Fold 3 IBS: 0.21496817791118686
Fold 4 IBS: 0.2244407948307909
Fold 5 IBS: 0.21255297899472933
[I 2024-04-13 17:28:17,727] Trial 20 finished with value: 0.22218903288492306 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 383, 'oob_score': False, 'max_samples': 0.20097738776716928, 'max_features': None, 'min_weight_fraction_leaf': 0.004060792657387402}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.2290670360457516
Fold 2 IBS: 0.22650138158218347
Fold 3 IBS: 0.21008304592241248
Fold 4 IBS: 0.21986746016357092
Fold 5 IBS: 0.21210536547841657
[I 2024-04-13 17:28:23,359] Trial 21 finished with value: 0.21952485783846704 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.9434662367457268, 'max_features': None, 'min_weight_fraction_leaf': 0.3773094481790897}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.2343438749630534
Fold 2 IBS: 0.2305538954932155
Fold 3 IBS: 0.20919220448300507
Fold 4 IBS: 0.21604529963958907
Fold 5 IBS: 0.21260186109118895
[I 2024-04-13 17:28:28,466] Trial 22 finished with value: 0.22054742713401038 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 233, 'oob_score': False, 'max_samples': 0.9113480482028802, 'max_features': None, 'min_weight_fraction_leaf': 0.30206147175923537}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.23084750055196906
Fold 2 IBS: 0.22662934169294
Fold 3 IBS: 0.20890138358823498
Fold 4 IBS: 0.22025699438841206
Fold 5 IBS: 0.21204173405192056
[I 2024-04-13 17:28:31,777] Trial 23 finished with value: 0.21973539085469534 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 15, 'n_estimators': 156, 'oob_score': False, 'max_samples': 0.9984717815952416, 'max_features': None, 'min_weight_fraction_leaf': 0.3929216118974511}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.23409973904222836
Fold 2 IBS: 0.23035264277150014
Fold 3 IBS: 0.208282675129283
Fold 4 IBS: 0.21615711253021055
Fold 5 IBS: 0.21237842930713094
[I 2024-04-13 17:28:39,100] Trial 24 finished with value: 0.22025411975607062 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 20, 'n_estimators': 329, 'oob_score': False, 'max_samples': 0.7767264188245335, 'max_features': None, 'min_weight_fraction_leaf': 0.2652560803793845}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.2463698727656445
Fold 2 IBS: 0.23214505556134526
Fold 3 IBS: 0.22956506982981237
Fold 4 IBS: 0.24151543156540123
Fold 5 IBS: 0.23019775660536843
[I 2024-04-13 17:28:46,238] Trial 25 finished with value: 0.23595863726551433 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 395, 'oob_score': False, 'max_samples': 0.8697776201657986, 'max_features': None, 'min_weight_fraction_leaf': 0.4913568614350199}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.2300364363624842
Fold 2 IBS: 0.22906487298535058
Fold 3 IBS: 0.20847378907385164
Fold 4 IBS: 0.216762282002948
Fold 5 IBS: 0.21230319973522532
[I 2024-04-13 17:28:56,831] Trial 26 finished with value: 0.21932811603197194 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 466, 'oob_score': True, 'max_samples': 0.9282714267189663, 'max_features': None, 'min_weight_fraction_leaf': 0.33933635944598195}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.2362924079122604
Fold 2 IBS: 0.22408707961692345
Fold 3 IBS: 0.21724236047990236
Fold 4 IBS: 0.22723714276402557
Fold 5 IBS: 0.21618073730625445
[I 2024-04-13 17:29:07,380] Trial 27 finished with value: 0.22420794561587326 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 461, 'oob_score': True, 'max_samples': 0.6324699344250437, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23093055841389884}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.24629569670119159
Fold 2 IBS: 0.2321452147356561
Fold 3 IBS: 0.22960376548746728
Fold 4 IBS: 0.2414905593027405
Fold 5 IBS: 0.23029207863586967
[I 2024-04-13 17:29:17,616] Trial 28 finished with value: 0.23596546297258505 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 456, 'oob_score': True, 'max_samples': 0.8341821328471759, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.44110828591386614}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.238549447254171
Fold 2 IBS: 0.23137271211204738
Fold 3 IBS: 0.21321823786375582
Fold 4 IBS: 0.2157297179290463
Fold 5 IBS: 0.21232243961907313
[I 2024-04-13 17:29:26,375] Trial 29 finished with value: 0.22223851095561872 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 374, 'oob_score': True, 'max_samples': 0.716636954602222, 'max_features': None, 'min_weight_fraction_leaf': 0.17164020141757397}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.23072168366604612
Fold 2 IBS: 0.2246986265412802
Fold 3 IBS: 0.21374564304391405
Fold 4 IBS: 0.2220632735514522
Fold 5 IBS: 0.2122389737326309
[I 2024-04-13 17:29:36,976] Trial 30 finished with value: 0.22069364010706466 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 411, 'oob_score': True, 'max_samples': 0.7300918540502069, 'max_features': None, 'min_weight_fraction_leaf': 0.29796281363998794}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.23198995000201283
Fold 2 IBS: 0.23040390845701422
Fold 3 IBS: 0.20858290048781583
Fold 4 IBS: 0.21610831133671127
Fold 5 IBS: 0.21254883205285036
[I 2024-04-13 17:29:44,319] Trial 31 finished with value: 0.21992678046728092 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 355, 'oob_score': False, 'max_samples': 0.9241493874348927, 'max_features': None, 'min_weight_fraction_leaf': 0.32406400911639355}. Best is trial 13 with value: 0.2191628532255277.

Fold 1 IBS: 0.22938449208506656
Fold 2 IBS: 0.22753082201660127
Fold 3 IBS: 0.20896337795479314
Fold 4 IBS: 0.21837680226854744
Fold 5 IBS: 0.21213517485483555
[I 2024-04-13 17:29:51,847] Trial 32 finished with value: 0.21927813383596878 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.9502203520505428, 'max_features': None, 'min_weight_fraction_leaf': 0.3660826370427841}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.2293305571674784
Fold 2 IBS: 0.2249056666416748
Fold 3 IBS: 0.21231192754080194
Fold 4 IBS: 0.2211259092827611
Fold 5 IBS: 0.2121489087663462
[I 2024-04-13 17:29:59,643] Trial 33 finished with value: 0.2199645938798125 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 308, 'oob_score': True, 'max_samples': 0.9355742306337576, 'max_features': None, 'min_weight_fraction_leaf': 0.3786258067333896}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.2463075108908765
Fold 2 IBS: 0.23213183628105669
Fold 3 IBS: 0.2295827900483688
Fold 4 IBS: 0.24151217219624668
Fold 5 IBS: 0.23032213125840695
[I 2024-04-13 17:30:09,331] Trial 34 finished with value: 0.23597128813499113 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.8812582176596271, 'max_features': None, 'min_weight_fraction_leaf': 0.45382706167727727}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.23907524909546954
Fold 2 IBS: 0.22759470054362013
Fold 3 IBS: 0.22354714163690584
Fold 4 IBS: 0.23410338480858017
Fold 5 IBS: 0.22027274960032137
[I 2024-04-13 17:30:14,327] Trial 35 finished with value: 0.2289186451369794 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.9651771091701671, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4100330462773345}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.24649894155677088
Fold 2 IBS: 0.2323492094119428
Fold 3 IBS: 0.22953618747854265
Fold 4 IBS: 0.24130141550867246
Fold 5 IBS: 0.23039432771337162
[I 2024-04-13 17:30:19,299] Trial 36 finished with value: 0.2360160163338601 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.4049732582664851, 'max_features': None, 'min_weight_fraction_leaf': 0.32200684761419274}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.24120747984170096
Fold 2 IBS: 0.22656467784556786
Fold 3 IBS: 0.22703359168272252
Fold 4 IBS: 0.23831265381859482
Fold 5 IBS: 0.22305834683775516
[I 2024-04-13 17:30:20,105] Trial 37 finished with value: 0.23123535000526826 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 22, 'oob_score': True, 'max_samples': 0.6134779412492984, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2516998532059925}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.23741471105571757
Fold 2 IBS: 0.2269485026573901
Fold 3 IBS: 0.22180183860532596
Fold 4 IBS: 0.23253236547606118
Fold 5 IBS: 0.21696146982805112
[I 2024-04-13 17:30:26,105] Trial 38 finished with value: 0.2271317775245092 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 263, 'oob_score': True, 'max_samples': 0.7910915339765465, 'max_features': None, 'min_weight_fraction_leaf': 0.36142483869019976}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.23935994444040118
Fold 2 IBS: 0.22854221616795026
Fold 3 IBS: 0.22504302362733838
Fold 4 IBS: 0.2351640647193704
Fold 5 IBS: 0.21927313841178442
[I 2024-04-13 17:30:35,032] Trial 39 finished with value: 0.22947647747336894 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 361, 'oob_score': True, 'max_samples': 0.8447512001644242, 'max_features': None, 'min_weight_fraction_leaf': 0.3970447302293817}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.2447580666792238
Fold 2 IBS: 0.231285046324017
Fold 3 IBS: 0.22824761810470237
Fold 4 IBS: 0.24054681499119981
Fold 5 IBS: 0.22759253051342168
[I 2024-04-13 17:30:43,713] Trial 40 finished with value: 0.23448601532251293 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 419, 'oob_score': True, 'max_samples': 0.899593747229425, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4346397998835263}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.23165620125728817
Fold 2 IBS: 0.2294316527496784
Fold 3 IBS: 0.2081603800537754
Fold 4 IBS: 0.21619400177602466
Fold 5 IBS: 0.21251964829332573
[I 2024-04-13 17:30:49,204] Trial 41 finished with value: 0.21959237682601848 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 300, 'oob_score': False, 'max_samples': 0.9453879649245928, 'max_features': None, 'min_weight_fraction_leaf': 0.3392081711525814}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.23198693256280964
Fold 2 IBS: 0.23047030553531472
Fold 3 IBS: 0.20797845601684767
Fold 4 IBS: 0.21602933655083825
Fold 5 IBS: 0.2125304364451398
[I 2024-04-13 17:30:54,681] Trial 42 finished with value: 0.21979909342219 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 328, 'oob_score': False, 'max_samples': 0.9975258705511094, 'max_features': None, 'min_weight_fraction_leaf': 0.34901686716334607}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.2289961170217228
Fold 2 IBS: 0.22477807251695273
Fold 3 IBS: 0.21330141647448275
Fold 4 IBS: 0.22284065832072095
Fold 5 IBS: 0.21244532018854143
[I 2024-04-13 17:31:00,943] Trial 43 finished with value: 0.22047231690448413 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.9449690907163976, 'max_features': None, 'min_weight_fraction_leaf': 0.39619704366997405}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.24621363097383236
Fold 2 IBS: 0.23220881964959503
Fold 3 IBS: 0.2294308453629481
Fold 4 IBS: 0.24150717056282334
Fold 5 IBS: 0.23022626196628526
[I 2024-04-13 17:31:09,303] Trial 44 finished with value: 0.2359173457030968 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 480, 'oob_score': False, 'max_samples': 0.4857787919376175, 'max_features': None, 'min_weight_fraction_leaf': 0.30423546678307434}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.24662232447971752
Fold 2 IBS: 0.2321314020337297
Fold 3 IBS: 0.22958960821506147
Fold 4 IBS: 0.24155434892499247
Fold 5 IBS: 0.2303219287986657
[I 2024-04-13 17:31:13,849] Trial 45 finished with value: 0.23604392249043338 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.8488113248277745, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4595802969756738}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.23071077670816129
Fold 2 IBS: 0.22871402337720798
Fold 3 IBS: 0.20840405511331822
Fold 4 IBS: 0.2168375035587375
Fold 5 IBS: 0.21230636792226085
[I 2024-04-13 17:31:20,379] Trial 46 finished with value: 0.21939454533593716 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 376, 'oob_score': False, 'max_samples': 0.9594631721362962, 'max_features': None, 'min_weight_fraction_leaf': 0.3562440896390543}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.24297296103341184
Fold 2 IBS: 0.230337344741508
Fold 3 IBS: 0.2270788974956496
Fold 4 IBS: 0.23855140992974458
Fold 5 IBS: 0.22614504010134673
[I 2024-04-13 17:31:36,906] Trial 47 finished with value: 0.23301713066033214 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 442, 'oob_score': True, 'max_samples': 0.9033097502472579, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4200237787501997}. Best is trial 13 with value: 0.2191628532255277.

Fold 1 IBS: 0.22927545380946876
Fold 2 IBS: 0.2276310370401933
Fold 3 IBS: 0.20885917650739413
Fold 4 IBS: 0.21808141368878975
Fold 5 IBS: 0.21215244703182187
[I 2024-04-13 17:31:46,431] Trial 48 finished with value: 0.21919990561553354 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 408, 'oob_score': False, 'max_samples': 0.9576806605170014, 'max_features': None, 'min_weight_fraction_leaf': 0.365900430347092}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.23920717494427576
Fold 2 IBS: 0.22840267598061034
Fold 3 IBS: 0.2254393339269583
Fold 4 IBS: 0.23467057175960346
Fold 5 IBS: 0.221637000000393
[I 2024-04-13 17:31:54,531] Trial 49 finished with value: 0.22987135132236816 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 19, 'n_estimators': 403, 'oob_score': False, 'max_samples': 0.6731598118016386, 'max_features': None, 'min_weight_fraction_leaf': 0.31987775470527335}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.23683232768125542
Fold 2 IBS: 0.2315718721769584
Fold 3 IBS: 0.2104660067769253
Fold 4 IBS: 0.2158330449187009
Fold 5 IBS: 0.21238979358328372
[I 2024-04-13 17:32:06,872] Trial 50 finished with value: 0.22141860902742475 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 18, 'n_estimators': 475, 'oob_score': True, 'max_samples': 0.7521831979714033, 'max_features': None, 'min_weight_fraction_leaf': 0.1067722201468298}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.23077430642524385
Fold 2 IBS: 0.22873954776764854
Fold 3 IBS: 0.20837956906194102
Fold 4 IBS: 0.21684171703494232
Fold 5 IBS: 0.21220715304406854
[I 2024-04-13 17:32:13,420] Trial 51 finished with value: 0.21938845866676884 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 17, 'n_estimators': 372, 'oob_score': False, 'max_samples': 0.9646978932451642, 'max_features': None, 'min_weight_fraction_leaf': 0.3581661535727259}. Best is trial 13 with value: 0.2191628532255277.
Fold 1 IBS: 0.2285304077741007
Fold 2 IBS: 0.227680311651727
Fold 3 IBS: 0.20910975601612422
Fold 4 IBS: 0.2182106263433914
Fold 5 IBS: 0.21211781896147444
[I 2024-04-13 17:32:21,130] Trial 52 finished with value: 0.21912978414936357 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 17, 'n_estimators': 436, 'oob_score': False, 'max_samples': 0.9698923398783661, 'max_features': None, 'min_weight_fraction_leaf': 0.37270846532946805}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.2307969145305897
Fold 2 IBS: 0.224630465654909
Fold 3 IBS: 0.21751379235187968
Fold 4 IBS: 0.2261417739308358
Fold 5 IBS: 0.21296097710487227
[I 2024-04-13 17:32:29,846] Trial 53 finished with value: 0.22240878471461728 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 16, 'n_estimators': 432, 'oob_score': False, 'max_samples': 0.8906009440806762, 'max_features': None, 'min_weight_fraction_leaf': 0.38139576469447645}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.2294729818570165
Fold 2 IBS: 0.22454829337724005
Fold 3 IBS: 0.2138098650907876
Fold 4 IBS: 0.2234623421909036
Fold 5 IBS: 0.2121761154942592
[I 2024-04-13 17:32:43,328] Trial 54 finished with value: 0.22069391960204138 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 15, 'n_estimators': 499, 'oob_score': False, 'max_samples': 0.985119821161648, 'max_features': None, 'min_weight_fraction_leaf': 0.4076526567758978}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.23707348790530808
Fold 2 IBS: 0.22253966693162772
Fold 3 IBS: 0.21581894666343945
Fold 4 IBS: 0.2237440410491447
Fold 5 IBS: 0.21437109511994074
[I 2024-04-13 17:32:52,310] Trial 55 finished with value: 0.22270944753389213 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 14, 'n_estimators': 445, 'oob_score': False, 'max_samples': 0.8193534401148852, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2746668514333212}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.235756986833974
Fold 2 IBS: 0.224244565517461
Fold 3 IBS: 0.2175793180075382
Fold 4 IBS: 0.22725808312148096
Fold 5 IBS: 0.21605718915015537
[I 2024-04-13 17:33:02,076] Trial 56 finished with value: 0.22417922852612193 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 471, 'oob_score': False, 'max_samples': 0.917224914229477, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3368617147169173}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.23129858090643257
Fold 2 IBS: 0.22473405333550617
Fold 3 IBS: 0.2178611421568171
Fold 4 IBS: 0.22714197135979539
Fold 5 IBS: 0.21490068722839423
[I 2024-04-13 17:33:09,153] Trial 57 finished with value: 0.22318728699738907 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 391, 'oob_score': False, 'max_samples': 0.8613777908129843, 'max_features': None, 'min_weight_fraction_leaf': 0.3781865060679536}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.23171749491468677
Fold 2 IBS: 0.22511049318712992
Fold 3 IBS: 0.2190029030861206
Fold 4 IBS: 0.228916338429264
Fold 5 IBS: 0.21500851557401363
[I 2024-04-13 17:33:16,563] Trial 58 finished with value: 0.22395114903824295 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 19, 'n_estimators': 415, 'oob_score': False, 'max_samples': 0.9742608056088158, 'max_features': None, 'min_weight_fraction_leaf': 0.428695993396167}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.2440964208305481
Fold 2 IBS: 0.23087936991744745
Fold 3 IBS: 0.22791822259675562
Fold 4 IBS: 0.2392794148291197
Fold 5 IBS: 0.2271439184632146
[I 2024-04-13 17:33:26,797] Trial 59 finished with value: 0.23386346932741714 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 489, 'oob_score': False, 'max_samples': 0.9990197021306215, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4769511774545844}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.22977919457951582
Fold 2 IBS: 0.2267324469737437
Fold 3 IBS: 0.20984392990166148
Fold 4 IBS: 0.21922210925929497
Fold 5 IBS: 0.21218097474667974
[I 2024-04-13 17:33:35,845] Trial 60 finished with value: 0.21955173109217913 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 293, 'oob_score': True, 'max_samples': 0.9242078088406601, 'max_features': None, 'min_weight_fraction_leaf': 0.3620598664011142}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.22983873979360755
Fold 2 IBS: 0.22809430081247825
Fold 3 IBS: 0.20867513282723377
Fold 4 IBS: 0.2178902876289017
Fold 5 IBS: 0.21220918503634395
[I 2024-04-13 17:33:44,201] Trial 61 finished with value: 0.21934152921971303 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 17, 'n_estimators': 367, 'oob_score': False, 'max_samples': 0.9672074550481354, 'max_features': None, 'min_weight_fraction_leaf': 0.3633559602881267}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.22886133373590128
Fold 2 IBS: 0.22528817676645765
Fold 3 IBS: 0.21130169331181411
Fold 4 IBS: 0.2207542799735636
Fold 5 IBS: 0.2121226134968308
[I 2024-04-13 17:33:50,866] Trial 62 finished with value: 0.21966561945691349 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 17, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.9626468637928342, 'max_features': None, 'min_weight_fraction_leaf': 0.39382644245190934}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.23169106397744893
Fold 2 IBS: 0.22989923944907484
Fold 3 IBS: 0.20872003781202453
Fold 4 IBS: 0.21633306620328155
Fold 5 IBS: 0.21247209699966987
[I 2024-04-13 17:33:59,889] Trial 63 finished with value: 0.21982310088829995 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 15, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.882533230432937, 'max_features': None, 'min_weight_fraction_leaf': 0.3093704494130224}. Best is trial 52 with value: 0.21912978414936357.

Fold 1 IBS: 0.2460267923298924
Fold 2 IBS: 0.2322217659737921
Fold 3 IBS: 0.22995325803591157
Fold 4 IBS: 0.24129229641724947
Fold 5 IBS: 0.23023978177796017
[I 2024-04-13 17:34:07,950] Trial 64 finished with value: 0.23594677890696114 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 401, 'oob_score': False, 'max_samples': 0.26967029716304014, 'max_features': None, 'min_weight_fraction_leaf': 0.33799253233948007}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.23418590920687307
Fold 2 IBS: 0.2318005678098793
Fold 3 IBS: 0.21076727004417795
Fold 4 IBS: 0.21591612664228851
Fold 5 IBS: 0.21267569020316077
[I 2024-04-13 17:34:16,470] Trial 65 finished with value: 0.22106911278127592 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.9287628030071836, 'max_features': None, 'min_weight_fraction_leaf': 0.28493652832607064}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.2289454424873699
Fold 2 IBS: 0.22770436417673726
Fold 3 IBS: 0.20897650309336188
Fold 4 IBS: 0.21814622246053275
Fold 5 IBS: 0.21211426815959838
[I 2024-04-13 17:34:23,145] Trial 66 finished with value: 0.21917736007552002 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 363, 'oob_score': False, 'max_samples': 0.9764571730689154, 'max_features': None, 'min_weight_fraction_leaf': 0.3743995960325977}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.24656153388565236
Fold 2 IBS: 0.23216347940396093
Fold 3 IBS: 0.2295702540108625
Fold 4 IBS: 0.24148049631887164
Fold 5 IBS: 0.23027283885328792
[I 2024-04-13 17:34:31,573] Trial 67 finished with value: 0.23600972049452706 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 314, 'oob_score': False, 'max_samples': 0.8171360496640728, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.41261888231807}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.23844688423266766
Fold 2 IBS: 0.22777522278563664
Fold 3 IBS: 0.22439060115528578
Fold 4 IBS: 0.2339121172097385
Fold 5 IBS: 0.22154182471836034
[I 2024-04-13 17:34:42,394] Trial 68 finished with value: 0.22921333002033778 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 443, 'oob_score': True, 'max_samples': 0.9024078961973323, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38624317500999844}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.24637361658681872
Fold 2 IBS: 0.23214420036260003
Fold 3 IBS: 0.2295877763806785
Fold 4 IBS: 0.2414890583211359
Fold 5 IBS: 0.23019028080236717
[I 2024-04-13 17:34:50,151] Trial 69 finished with value: 0.23595698649072006 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 384, 'oob_score': False, 'max_samples': 0.8654027533485461, 'max_features': None, 'min_weight_fraction_leaf': 0.4584979310068393}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.23705561730520205
Fold 2 IBS: 0.23200229627648258
Fold 3 IBS: 0.21337957602870322
Fold 4 IBS: 0.21582287980146625
Fold 5 IBS: 0.21267917043091045
[I 2024-04-13 17:34:59,220] Trial 70 finished with value: 0.22218790796855287 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 276, 'oob_score': True, 'max_samples': 0.9457205320184687, 'max_features': None, 'min_weight_fraction_leaf': 0.21974391325851378}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.22994847148886466
Fold 2 IBS: 0.22836020964598355
Fold 3 IBS: 0.20845378814946247
Fold 4 IBS: 0.2173705486077374
Fold 5 IBS: 0.21211664963952806
[I 2024-04-13 17:35:08,953] Trial 71 finished with value: 0.21924993350631525 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 17, 'n_estimators': 365, 'oob_score': False, 'max_samples': 0.9752409546083229, 'max_features': None, 'min_weight_fraction_leaf': 0.3681466195294743}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.23034962220097707
Fold 2 IBS: 0.22893057733100194
Fold 3 IBS: 0.20852114768496927
Fold 4 IBS: 0.2171306555971299
Fold 5 IBS: 0.21216304960576798
[I 2024-04-13 17:35:18,125] Trial 72 finished with value: 0.21941901048396922 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 357, 'oob_score': False, 'max_samples': 0.9840323261760491, 'max_features': None, 'min_weight_fraction_leaf': 0.3682031227418097}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.22984287220843466
Fold 2 IBS: 0.2245649288448129
Fold 3 IBS: 0.21641947124136057
Fold 4 IBS: 0.22609375578030488
Fold 5 IBS: 0.21366152417444512
[I 2024-04-13 17:35:25,993] Trial 73 finished with value: 0.22211651044987163 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 333, 'oob_score': False, 'max_samples': 0.9341828308830519, 'max_features': None, 'min_weight_fraction_leaf': 0.4020916766045328}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.23089506350847586
Fold 2 IBS: 0.22910739250465695
Fold 3 IBS: 0.20835880034250132
Fold 4 IBS: 0.2165417131620222
Fold 5 IBS: 0.21244143924706554
[I 2024-04-13 17:35:35,675] Trial 74 finished with value: 0.21946888175294438 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.9153654204994741, 'max_features': None, 'min_weight_fraction_leaf': 0.3273278583647327}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.23013405485913616
Fold 2 IBS: 0.2246734201070483
Fold 3 IBS: 0.21671470486549357
Fold 4 IBS: 0.225981300795259
Fold 5 IBS: 0.2127007096062536
[I 2024-04-13 17:35:44,451] Trial 75 finished with value: 0.22204083804663816 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.9986424824799667, 'max_features': None, 'min_weight_fraction_leaf': 0.4275657158584251}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.2303654822181394
Fold 2 IBS: 0.2302001727604011
Fold 3 IBS: 0.20833759474681893
Fold 4 IBS: 0.2163285108788938
Fold 5 IBS: 0.21243274553927705
[I 2024-04-13 17:35:58,126] Trial 76 finished with value: 0.21953290122870603 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.969766471739292, 'max_features': None, 'min_weight_fraction_leaf': 0.34623464338648247}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.22823198964797548
Fold 2 IBS: 0.22640124422155133
Fold 3 IBS: 0.2103132521962655
Fold 4 IBS: 0.21977858019653704
Fold 5 IBS: 0.2120757684794319
[I 2024-04-13 17:36:13,239] Trial 77 finished with value: 0.21936016694835225 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 429, 'oob_score': True, 'max_samples': 0.9449653112529804, 'max_features': None, 'min_weight_fraction_leaf': 0.37326034436604005}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.2405606399902856
Fold 2 IBS: 0.22890617826047416
Fold 3 IBS: 0.22490809263090283
Fold 4 IBS: 0.23624110361820103
Fold 5 IBS: 0.22289885082425212
[I 2024-04-13 17:36:23,508] Trial 78 finished with value: 0.23070297306482318 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.881299877205238, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.38777099620068023}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.24609176539254898
Fold 2 IBS: 0.23214059222769437
Fold 3 IBS: 0.2303670544118798
Fold 4 IBS: 0.24109539870263558

Fold 5 IBS: 0.22999822825894972
[I 2024-04-13 17:36:38,194] Trial 79 finished with value: 0.23593860779874168 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 473, 'oob_score': False, 'max_samples': 0.12074719353470553, 'max_features': None, 'min_weight_fraction_leaf': 0.44663557696688005}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.23023691170508595
Fold 2 IBS: 0.22831549805589474
Fold 3 IBS: 0.2085077533226
Fold 4 IBS: 0.2170371467540854
Fold 5 IBS: 0.21209842650340235
[I 2024-04-13 17:36:54,019] Trial 80 finished with value: 0.21923914726821367 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 487, 'oob_score': True, 'max_samples': 0.8362923410326437, 'max_features': None, 'min_weight_fraction_leaf': 0.3136324910319987}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.23023691170508595
Fold 2 IBS: 0.22831549805589474
Fold 3 IBS: 0.2085077533226
Fold 4 IBS: 0.2170371467540854
Fold 5 IBS: 0.21216056027529856
[I 2024-04-13 17:37:07,914] Trial 81 finished with value: 0.21925157402259293 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 487, 'oob_score': True, 'max_samples': 0.8372878416798057, 'max_features': None, 'min_weight_fraction_leaf': 0.3095547258115551}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.23467048085738737
Fold 2 IBS: 0.22851039672474774
Fold 3 IBS: 0.21028895948882712
Fold 4 IBS: 0.21603518063498692
Fold 5 IBS: 0.21242752804562468
[I 2024-04-13 17:37:10,898] Trial 82 finished with value: 0.22038650915031477 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 18, 'n_estimators': 87, 'oob_score': True, 'max_samples': 0.8511644808475658, 'max_features': None, 'min_weight_fraction_leaf': 0.2887570182684522}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.2295542064063645
Fold 2 IBS: 0.22575807775037599
Fold 3 IBS: 0.2112801496744051
Fold 4 IBS: 0.21928049775968628
Fold 5 IBS: 0.21196794509982722
[I 2024-04-13 17:37:24,159] Trial 83 finished with value: 0.21956817533813183 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.7869795122068599, 'max_features': None, 'min_weight_fraction_leaf': 0.31148586190184374}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.23500705847036343
Fold 2 IBS: 0.23174457153914016
Fold 3 IBS: 0.2107800467406234
Fold 4 IBS: 0.2158362715844479
Fold 5 IBS: 0.21255850361976295
[I 2024-04-13 17:37:37,374] Trial 84 finished with value: 0.2211852903908676 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 17, 'n_estimators': 488, 'oob_score': True, 'max_samples': 0.8351011052500579, 'max_features': None, 'min_weight_fraction_leaf': 0.2557797888802188}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.2307950411499353
Fold 2 IBS: 0.22891006413818357
Fold 3 IBS: 0.2085724600199988
Fold 4 IBS: 0.21691305836697047
Fold 5 IBS: 0.21232461100958616
[I 2024-04-13 17:37:49,415] Trial 85 finished with value: 0.21950304693693487 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 17, 'n_estimators': 467, 'oob_score': True, 'max_samples': 0.9012285266745327, 'max_features': None, 'min_weight_fraction_leaf': 0.32881031780503733}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.24619346078815524
Fold 2 IBS: 0.2322342162414191
Fold 3 IBS: 0.22948858145693177
Fold 4 IBS: 0.2414785647201697
Fold 5 IBS: 0.23011858091486492
[I 2024-04-13 17:38:00,782] Trial 86 finished with value: 0.23590268082430815 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 14, 'n_estimators': 402, 'oob_score': True, 'max_samples': 0.4921141678264287, 'max_features': None, 'min_weight_fraction_leaf': 0.3495892866973941}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.237071616112785
Fold 2 IBS: 0.2220909826824254
Fold 3 IBS: 0.21548526044540245
Fold 4 IBS: 0.22304514312184096
Fold 5 IBS: 0.2139947073511313
[I 2024-04-13 17:38:16,853] Trial 87 finished with value: 0.22233754194271702 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 456, 'oob_score': True, 'max_samples': 0.9477012881941371, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3137067576453535}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.2405322806454223
Fold 2 IBS: 0.22939401883056637
Fold 3 IBS: 0.2261032920529568
Fold 4 IBS: 0.23671644225651622
Fold 5 IBS: 0.22335223489109088
[I 2024-04-13 17:38:28,441] Trial 88 finished with value: 0.23121965373531048 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.7498185413414304, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3347164944537476}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.2331088042403945
Fold 2 IBS: 0.23102266891533038
Fold 3 IBS: 0.20926364188127358
Fold 4 IBS: 0.21593860604588774
Fold 5 IBS: 0.21273620728772516
[I 2024-04-13 17:38:38,042] Trial 89 finished with value: 0.2204139856741223 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 355, 'oob_score': True, 'max_samples': 0.9222911949734702, 'max_features': None, 'min_weight_fraction_leaf': 0.29918760567574354}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.2316086319798783
Fold 2 IBS: 0.22458742009482022
Fold 3 IBS: 0.21557295791424702
Fold 4 IBS: 0.22458100457345162
Fold 5 IBS: 0.21292659624486548
[I 2024-04-13 17:38:48,655] Trial 90 finished with value: 0.22185532216145254 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.808719161852227, 'max_features': None, 'min_weight_fraction_leaf': 0.34738725721619684}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.22892463946224906
Fold 2 IBS: 0.22810032423301724
Fold 3 IBS: 0.20875251418558335
Fold 4 IBS: 0.21785205785652928
Fold 5 IBS: 0.21209914517762535
[I 2024-04-13 17:39:03,882] Trial 91 finished with value: 0.21914573618300084 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 481, 'oob_score': True, 'max_samples': 0.9790772063684505, 'max_features': None, 'min_weight_fraction_leaf': 0.3771674578363462}. Best is trial 52 with value: 0.21912978414936357.
Fold 1 IBS: 0.22923089340480196
Fold 2 IBS: 0.22826543988733006
Fold 3 IBS: 0.20829704920881292
Fold 4 IBS: 0.2174028085764398
Fold 5 IBS: 0.2121232709956769
[I 2024-04-13 17:39:18,047] Trial 92 finished with value: 0.21906389241461235 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 482, 'oob_score': True, 'max_samples': 0.9732130654966473, 'max_features': None, 'min_weight_fraction_leaf': 0.36798680886807317}. Best is trial 92 with value: 0.21906389241461235.
Fold 1 IBS: 0.228876402684237
Fold 2 IBS: 0.22807479818718465
Fold 3 IBS: 0.20877603781381152
Fold 4 IBS: 0.21785235368618108
Fold 5 IBS: 0.2121294638065887
[I 2024-04-13 17:39:31,420] Trial 93 finished with value: 0.2191418112356006 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 480, 'oob_score': True, 'max_samples': 0.9776478005148914, 'max_features': None, 'min_weight_fraction_leaf': 0.37351156914593764}. Best is trial 92 with value: 0.21906389241461235.
Fold 1 IBS: 0.2289738919666464
Fold 2 IBS: 0.22809665315273175
Fold 3 IBS: 0.208742811639039
Fold 4 IBS: 0.21784133005923847
Fold 5 IBS: 0.2121755877414973
[I 2024-04-13 17:39:47,190] Trial 94 finished with value: 0.21916605491183055 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 485, 'oob_score': True, 'max_samples': 0.9785302091936966, 'max_features': None, 'min_weight_fraction_leaf': 0.37164326118603397}. Best is trial 92 with value: 0.21906389241461235.

Fold 1 IBS: 0.22909260836646478
Fold 2 IBS: 0.22503544485507979
Fold 3 IBS: 0.2120598829609088
Fold 4 IBS: 0.2214716876773108
Fold 5 IBS: 0.2120467826247585
[I 2024-04-13 17:40:02,851] Trial 95 finished with value: 0.21994128129690454 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 487, 'oob_score': True, 'max_samples': 0.9807024729491963, 'max_features': None, 'min_weight_fraction_leaf': 0.4007304758915286}. Best is trial 92 with value: 0.21906389241461235.
Fold 1 IBS: 0.22894596533673903
Fold 2 IBS: 0.22806686188441844
Fold 3 IBS: 0.20882278342889127
Fold 4 IBS: 0.21784782165652053
Fold 5 IBS: 0.21215769756945996
[I 2024-04-13 17:40:17,983] Trial 96 finished with value: 0.21916822597520583 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 477, 'oob_score': True, 'max_samples': 0.9808378834140379, 'max_features': None, 'min_weight_fraction_leaf': 0.37233589571707304}. Best is trial 92 with value: 0.21906389241461235.
Fold 1 IBS: 0.22864056914060796
Fold 2 IBS: 0.22567190054746059
Fold 3 IBS: 0.21109913701303015
Fold 4 IBS: 0.22041058948855438
Fold 5 IBS: 0.21204863633596038
[I 2024-04-13 17:40:33,076] Trial 97 finished with value: 0.21957416650512268 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 476, 'oob_score': True, 'max_samples': 0.9578231644402846, 'max_features': None, 'min_weight_fraction_leaf': 0.3844120114082838}. Best is trial 92 with value: 0.21906389241461235.
Fold 1 IBS: 0.2293195297011079
Fold 2 IBS: 0.2246748965867151
Fold 3 IBS: 0.2139794375882074
Fold 4 IBS: 0.22385649374477914
Fold 5 IBS: 0.21219600912813064
[I 2024-04-13 17:40:49,536] Trial 98 finished with value: 0.22080527334978806 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 449, 'oob_score': True, 'max_samples': 0.9992624986697489, 'max_features': None, 'min_weight_fraction_leaf': 0.4154605899979289}. Best is trial 92 with value: 0.21906389241461235.
Fold 1 IBS: 0.23572712394145517
Fold 2 IBS: 0.2249351510860775
Fold 3 IBS: 0.21878857139791
Fold 4 IBS: 0.22841907150494864
Fold 5 IBS: 0.2169792237419154
[I 2024-04-13 17:41:04,587] Trial 99 finished with value: 0.22496982833446136 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 462, 'oob_score': True, 'max_samples': 0.9797722450833973, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.37145215838780027}. Best is trial 92 with value: 0.21906389241461235.


* Best trial for IBS:
 FrozenTrial(number=92, state=TrialState.COMPLETE, values=[0.21906389241461235], datetime_start=datetime.datetime(2024, 4, 13, 17, 39, 3, 891814), datetime_complete=datetime.datetime(2024, 4, 13, 17, 39, 18, 46337), params={'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 482, 'oob_score': True, 'max_samples': 0.9732130654966473, 'max_features': None, 'min_weight_fraction_leaf': 0.36798680886807317}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=92, value=None)


* Best Score for IBS:
 0.21906389241461235

In [48]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [49]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.64
train_ibs:  0.219

#### Test

In [50]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [51]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=7, max_features='log2', max_leaf_nodes=13,
                     max_samples=0.8364130211722378, min_samples_split=12,
                     min_weight_fraction_leaf=0.1584235940276062,
                     n_estimators=192, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.653

RandomSurvivalForest(max_depth=18, max_features=None, max_leaf_nodes=19,
                     max_samples=0.9732130654966473, min_samples_leaf=10,
                     min_samples_split=20,
                     min_weight_fraction_leaf=0.36798680886807317,
                     n_estimators=482, oob_score=True, random_state=123)

test_ibs:  0.221

In [52]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [53]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:41:09,361] A new study created in memory with name: no-name-92961422-218c-4a9f-9f55-f8068cb451be

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:41:11,587] Trial 0 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:41:16,947] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:41:28,988] Trial 2 finished with value: 0.6263714158689486 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:41:30,053] Trial 3 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:41:35,515] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:41:40,743] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:41:44,078] Trial 6 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:41:51,214] Trial 7 finished with value: 0.6327052496375349 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:41:51,629] Trial 8 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:42:04,697] Trial 9 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:42:09,206] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:42:11,518] Trial 11 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:42:14,768] Trial 12 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:42:18,264] Trial 13 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6381530978163132, 'min_weight_fraction_leaf': 0.10302250602390595}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:42:20,407] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 281, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605

Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:42:23,187] Trial 15 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 402, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.0788882352604838}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:42:24,483] Trial 16 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 175, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:42:26,862] Trial 17 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3978019017721025, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:42:27,831] Trial 18 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5667572863003578, 'min_weight_fraction_leaf': 0.053773653856063974}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:42:28,722] Trial 19 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8783131293076132, 'min_weight_fraction_leaf': 0.13992862488743474}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:42:30,039] Trial 20 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 17, 'n_estimators': 220, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7012814108158212, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:42:32,597] Trial 21 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 374, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3492295439800804, 'min_weight_fraction_leaf': 0.004002668882656523}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:42:35,690] Trial 22 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 438, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.2735505878006093, 'min_weight_fraction_leaf': 0.02034264731151425}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:42:38,603] Trial 23 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 357, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.10422955406821338, 'min_weight_fraction_leaf': 0.07933617912675625}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:42:41,739] Trial 24 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 297, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5051938039336281, 'min_weight_fraction_leaf': 0.09390422583252539}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:42:45,718] Trial 25 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 411, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.23358380819437038, 'min_weight_fraction_leaf': 0.041451106877202853}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:43:03,736] Trial 26 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 477, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.36395775357357807, 'min_weight_fraction_leaf': 0.0035978786324019686}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:43:05,496] Trial 27 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 240, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5974919246808656, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:43:08,833] Trial 28 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 385, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.739801663402643, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:43:15,940] Trial 29 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 426, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5046913061224547, 'min_weight_fraction_leaf': 0.11407935861476001}. Best is trial 0 with value: 0.6400441700740036.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:43:18,123] Trial 30 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 309, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4344347067743851, 'min_weight_fraction_leaf': 0.0387114670088218}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:43:21,701] Trial 31 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8427320867975694, 'min_weight_fraction_leaf': 0.0012002559281581464}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:43:25,556] Trial 32 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 465, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9808404276622668, 'min_weight_fraction_leaf': 0.07184966377496652}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:43:28,784] Trial 33 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 496, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9303271782787866, 'min_weight_fraction_leaf': 0.028477275726533316}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:43:32,367] Trial 34 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 453, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6312992616509612, 'min_weight_fraction_leaf': 0.06758485504462494}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:43:43,226] Trial 35 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 412, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.17523937322026623, 'min_weight_fraction_leaf': 0.001991979546060226}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:43:45,567] Trial 36 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 343, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9277737816606868, 'min_weight_fraction_leaf': 0.05180816408895112}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:43:49,842] Trial 37 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 476, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.3059372996954189, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:44:05,016] Trial 38 finished with value: 0.6263714158689486 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 432, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.4628956333550614, 'min_weight_fraction_leaf': 0.11874543876837246}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:44:08,136] Trial 39 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 20, 'max_depth': 8, 'n_estimators': 395, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8024160875701349, 'min_weight_fraction_leaf': 0.027944400245624588}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:44:30,760] Trial 40 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 369, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.728974464962463, 'min_weight_fraction_leaf': 0.09284956196560273}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:44:40,166] Trial 41 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6981495003424107, 'min_weight_fraction_leaf': 0.07079627708821945}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:44:43,583] Trial 42 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 327, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6573273104690629, 'min_weight_fraction_leaf': 0.030942411229831823}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:44:46,392] Trial 43 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 454, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5403936129300264, 'min_weight_fraction_leaf': 0.05843279203334233}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:44:48,853] Trial 44 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 280, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6062182794632219, 'min_weight_fraction_leaf': 0.138856218221347}. Best is trial 0 with value: 0.6400441700740036.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:44:54,199] Trial 45 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 358, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.780056204088303, 'min_weight_fraction_leaf': 0.17168647303929763}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:44:57,222] Trial 46 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6747669908477258, 'min_weight_fraction_leaf': 0.08818933939003902}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:45:00,000] Trial 47 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 390, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8363120085238097, 'min_weight_fraction_leaf': 0.22794946012510622}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:45:02,120] Trial 48 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 325, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5448469588986423, 'min_weight_fraction_leaf': 0.2832181123598866}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:45:04,797] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7418230490601051, 'min_weight_fraction_leaf': 0.3739970568853183}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:45:07,710] Trial 50 finished with value: 0.6114286538928541 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 102, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9367011308862865, 'min_weight_fraction_leaf': 0.018529589211825702}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:45:10,165] Trial 51 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 374, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.35977771985958523, 'min_weight_fraction_leaf': 0.0010440357673676408}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:45:12,349] Trial 52 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 354, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.38920782663893977, 'min_weight_fraction_leaf': 0.04875309501818556}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:45:15,123] Trial 53 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.31765492887041474, 'min_weight_fraction_leaf': 0.01713427143635258}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:45:18,319] Trial 54 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.21378093391243902, 'min_weight_fraction_leaf': 0.04557421419016047}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:45:20,462] Trial 55 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 301, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4305373711163092, 'min_weight_fraction_leaf': 0.016793338568499322}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:45:23,531] Trial 56 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 421, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5805526102988088, 'min_weight_fraction_leaf': 0.10421218889572839}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:45:25,460] Trial 57 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 275, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4770196650724934, 'min_weight_fraction_leaf': 0.07920646014917873}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:45:27,807] Trial 58 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 250, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5162091119888677, 'min_weight_fraction_leaf': 0.059745779160964435}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:45:30,980] Trial 59 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 371, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8807017299056661, 'min_weight_fraction_leaf': 0.034077896149816454}. Best is trial 0 with value: 0.6400441700740036.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:45:34,131] Trial 60 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 177, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6191277619189391, 'min_weight_fraction_leaf': 0.12602348681377346}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:45:36,898] Trial 61 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 325, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.33527695120089496, 'min_weight_fraction_leaf': 0.15871412580315153}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:45:39,548] Trial 62 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 312, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.2763702211381745, 'min_weight_fraction_leaf': 0.016344799789515387}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:45:43,240] Trial 63 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 345, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.39403389452783044, 'min_weight_fraction_leaf': 0.09615238271513343}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:45:46,331] Trial 64 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5110325740215397, 'min_weight_fraction_leaf': 0.20810908390966434}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:45:48,630] Trial 65 finished with value: 0.5 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 298, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.15143321369170815, 'min_weight_fraction_leaf': 0.08101347835467446}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:46:01,436] Trial 66 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 460, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.41850776172456805, 'min_weight_fraction_leaf': 0.039877946679433944}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:46:03,242] Trial 67 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 224, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6907602501190309, 'min_weight_fraction_leaf': 0.0005757624534238597}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:46:06,037] Trial 68 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 361, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.978346026643418, 'min_weight_fraction_leaf': 0.10874641657738363}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:46:09,384] Trial 69 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 486, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7571532010383348, 'min_weight_fraction_leaf': 0.12896255279692895}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:46:12,633] Trial 70 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.828577068018564, 'min_weight_fraction_leaf': 0.05969000310939712}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:46:28,917] Trial 71 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 468, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.36300065184674374, 'min_weight_fraction_leaf': 0.010160251124285868}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:46:47,363] Trial 72 finished with value: 0.6294058722016631 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.2803818022320134, 'min_weight_fraction_leaf': 0.025164308775071552}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:47:00,480] Trial 73 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 413, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4605773995165404, 'min_weight_fraction_leaf': 0.04242499179419398}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:47:13,545] Trial 74 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 396, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.3440151344115863, 'min_weight_fraction_leaf': 0.011482994731569423}. Best is trial 0 with value: 0.6400441700740036.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:47:31,557] Trial 75 finished with value: 0.6297934691008878 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 446, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.2464217309205179, 'min_weight_fraction_leaf': 0.06825353783264658}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:47:45,425] Trial 76 finished with value: 0.6327052496375349 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 341, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6461352623185277, 'min_weight_fraction_leaf': 0.029703233664296}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:47:48,892] Trial 77 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 431, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5807187837064285, 'min_weight_fraction_leaf': 0.05444283946272303}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:47:53,262] Trial 78 finished with value: 0.5 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.31086035343824814, 'min_weight_fraction_leaf': 0.4401997700779695}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:47:56,834] Trial 79 finished with value: 0.6255130467702362 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 382, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7186094232020824, 'min_weight_fraction_leaf': 0.2650073040584992}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:48:00,933] Trial 80 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 460, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.41708293125709267, 'min_weight_fraction_leaf': 0.0076148694238355906}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:48:03,633] Trial 81 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3746652810811203, 'min_weight_fraction_leaf': 0.03652699788238737}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:48:06,522] Trial 82 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 307, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.48564994828411556, 'min_weight_fraction_leaf': 0.02504257601455709}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:48:09,399] Trial 83 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 362, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4331285105903118, 'min_weight_fraction_leaf': 0.08464574654429634}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:48:11,673] Trial 84 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 267, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.519895026448905, 'min_weight_fraction_leaf': 0.0004238400911233467}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:48:15,005] Trial 85 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.44419701540817913, 'min_weight_fraction_leaf': 0.32253916192374105}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:48:17,697] Trial 86 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 337, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5500005822642177, 'min_weight_fraction_leaf': 0.04705771133755361}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:48:33,152] Trial 87 finished with value: 0.6263714158689486 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 393, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9010861253895607, 'min_weight_fraction_leaf': 0.017750029831929325}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:48:35,694] Trial 88 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 324, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.32523609771716305, 'min_weight_fraction_leaf': 0.06971633665620264}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:48:39,640] Trial 89 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 487, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3894011095751425, 'min_weight_fraction_leaf': 0.03767718160513212}. Best is trial 0 with value: 0.6400441700740036.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:48:42,290] Trial 90 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4122398769760413, 'min_weight_fraction_leaf': 0.09800066602665285}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:48:45,837] Trial 91 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 494, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8265695539504441, 'min_weight_fraction_leaf': 0.025177059275512198}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:48:49,235] Trial 92 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7651765763966663, 'min_weight_fraction_leaf': 0.005201466976579}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:48:52,110] Trial 93 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 374, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7959927941173858, 'min_weight_fraction_leaf': 0.05070338518930715}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:48:56,206] Trial 94 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8507320381877586, 'min_weight_fraction_leaf': 0.011503520796752535}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:48:56,685] Trial 95 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 4, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9600279792440479, 'min_weight_fraction_leaf': 0.03367032142692865}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:48:59,165] Trial 96 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 354, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.2974210309573564, 'min_weight_fraction_leaf': 0.062469639916921435}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:49:03,090] Trial 97 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 452, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.3495546782421727, 'min_weight_fraction_leaf': 0.07777844405633945}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:49:06,796] Trial 98 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8574699980157217, 'min_weight_fraction_leaf': 0.022156188394288144}. Best is trial 0 with value: 0.6400441700740036.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605

[I 2024-04-13 17:49:12,866] A new study created in memory with name: no-name-118754e8-01a8-4d63-bed8-04161ef6e658

Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:49:12,853] Trial 99 finished with value: 0.6400441700740036 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 432, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6726803650215809, 'min_weight_fraction_leaf': 0.00974112473731428}. Best is trial 0 with value: 0.6400441700740036.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6400441700740036], datetime_start=datetime.datetime(2024, 4, 13, 17, 41, 9, 412039), datetime_complete=datetime.datetime(2024, 4, 13, 17, 41, 11, 586049), params={'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=0, value=None)


* Best Score for C-index:
 0.6400441700740036

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23997275846693625
Fold 2 IBS: 0.22108393977891452
Fold 3 IBS: 0.21606012791284884
Fold 4 IBS: 0.22053597926904406
Fold 5 IBS: 0.21178646423226072
[I 2024-04-13 17:49:22,185] Trial 0 finished with value: 0.2218878539320009 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.2218878539320009.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-13 17:49:36,246] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.2218878539320009.
Fold 1 IBS: 0.23840825390377368
Fold 2 IBS: 0.22076254534344314
Fold 3 IBS: 0.21622074468231264
Fold 4 IBS: 0.22075139390838644
Fold 5 IBS: 0.21241185997012732
[I 2024-04-13 17:49:49,741] Trial 2 finished with value: 0.22171095956160863 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 2 with value: 0.22171095956160863.
Fold 1 IBS: 0.23992852955055313
Fold 2 IBS: 0.22030284197827907
Fold 3 IBS: 0.2167812683110058
Fold 4 IBS: 0.22130784972928808
Fold 5 IBS: 0.21275964397131183
[I 2024-04-13 17:49:53,744] Trial 3 finished with value: 0.22221602670808757 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 2 with value: 0.22171095956160863.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-13 17:50:04,150] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 2 with value: 0.22171095956160863.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-13 17:50:10,930] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 2 with value: 0.22171095956160863.
Fold 1 IBS: 0.2386987514309957
Fold 2 IBS: 0.22124293651714386
Fold 3 IBS: 0.2159229545506137
Fold 4 IBS: 0.22045927943413013
Fold 5 IBS: 0.21218833315205302
[I 2024-04-13 17:50:22,771] Trial 6 finished with value: 0.2217024510169873 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.2217024510169873.
Fold 1 IBS: 0.23793930397141175
Fold 2 IBS: 0.23029372087836114
Fold 3 IBS: 0.21096502098859912
Fold 4 IBS: 0.22716805709097435
Fold 5 IBS: 0.21386133488199716
[I 2024-04-13 17:50:32,818] Trial 7 finished with value: 0.2240454875622687 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.2217024510169873.
Fold 1 IBS: 0.23952161295008306
Fold 2 IBS: 0.22074815212743634
Fold 3 IBS: 0.2181519227310518
Fold 4 IBS: 0.22171734127551448
Fold 5 IBS: 0.2138051223752562
[I 2024-04-13 17:50:34,852] Trial 8 finished with value: 0.22278883029186836 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.2217024510169873.
Fold 1 IBS: 0.23610311791724742
Fold 2 IBS: 0.22400283618905314
Fold 3 IBS: 0.2175254146961614
Fold 4 IBS: 0.22705858817890487
Fold 5 IBS: 0.21727581666213597
[I 2024-04-13 17:50:52,322] Trial 9 finished with value: 0.22439315472870058 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.2217024510169873.
Fold 1 IBS: 0.24645397072894554
Fold 2 IBS: 0.23215165796624326
Fold 3 IBS: 0.2300072528605466
Fold 4 IBS: 0.24106162740477477
Fold 5 IBS: 0.23037976132987092
[I 2024-04-13 17:51:07,817] Trial 10 finished with value: 0.23601085405807623 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.2217024510169873.
Fold 1 IBS: 0.2380577744988373
Fold 2 IBS: 0.22150209136752336
Fold 3 IBS: 0.2154935331518127
Fold 4 IBS: 0.22134595695357384
Fold 5 IBS: 0.21324174364958426
[I 2024-04-13 17:51:22,283] Trial 11 finished with value: 0.2219282199242663 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5984844746626113, 'min_weight_fraction_leaf': 0.17791648432241353}. Best is trial 6 with value: 0.2217024510169873.
Fold 1 IBS: 0.24643308507994965
Fold 2 IBS: 0.2322372818196016
Fold 3 IBS: 0.22952228536510255
Fold 4 IBS: 0.24141204433890703
Fold 5 IBS: 0.2302909694346764
[I 2024-04-13 17:51:37,535] Trial 12 finished with value: 0.23597913320764743 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 19, 'max_depth': 17, 'n_estimators': 500, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.338060458067936, 'min_weight_fraction_leaf': 0.0011234542028401434}. Best is trial 6 with value: 0.2217024510169873.
Fold 1 IBS: 0.238422865726539
Fold 2 IBS: 0.22101251907428893
Fold 3 IBS: 0.21588566991407085
Fold 4 IBS: 0.22116274139789427
Fold 5 IBS: 0.21285018999682823
[I 2024-04-13 17:51:50,636] Trial 13 finished with value: 0.22186679722192423 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 414, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6381530978163132, 'min_weight_fraction_leaf': 0.08367124779488641}. Best is trial 6 with value: 0.2217024510169873.
Fold 1 IBS: 0.24701577391863036
Fold 2 IBS: 0.23230505352976336
Fold 3 IBS: 0.22966861474411024
Fold 4 IBS: 0.24119910588298787
Fold 5 IBS: 0.2302068610532859
[I 2024-04-13 17:52:01,223] Trial 14 finished with value: 0.23607908182575552 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3469585144995889, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 6 with value: 0.2217024510169873.

Fold 1 IBS: 0.24210795588726058
Fold 2 IBS: 0.22961940772494766
Fold 3 IBS: 0.22669860735520306
Fold 4 IBS: 0.23729718316247136
Fold 5 IBS: 0.2231739521594384
[I 2024-04-13 17:52:13,558] Trial 15 finished with value: 0.23177942125786424 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 444, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9428730581718685, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 6 with value: 0.2217024510169873.
Fold 1 IBS: 0.2408714177608528
Fold 2 IBS: 0.22026414334476938
Fold 3 IBS: 0.217507350735527
Fold 4 IBS: 0.22166159005588842
Fold 5 IBS: 0.21240016442428503
[I 2024-04-13 17:52:17,147] Trial 16 finished with value: 0.2225409332642645 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 95, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7030814376640919, 'min_weight_fraction_leaf': 0.05613261324966139}. Best is trial 6 with value: 0.2217024510169873.
Fold 1 IBS: 0.24645111963751493
Fold 2 IBS: 0.23237285753877376
Fold 3 IBS: 0.22968973585936545
Fold 4 IBS: 0.24137058825160115
Fold 5 IBS: 0.2303228327069798
[I 2024-04-13 17:52:27,871] Trial 17 finished with value: 0.23604142679884701 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 375, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.3978019017721025, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 6 with value: 0.2217024510169873.
Fold 1 IBS: 0.24664983190598763
Fold 2 IBS: 0.23213277428578397
Fold 3 IBS: 0.22987993514894178
Fold 4 IBS: 0.24111453814189612
Fold 5 IBS: 0.2302956712616906
[I 2024-04-13 17:52:39,353] Trial 18 finished with value: 0.23601455014886003 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 267, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.2119407965774867, 'min_weight_fraction_leaf': 0.15014313701199353}. Best is trial 6 with value: 0.2217024510169873.
Fold 1 IBS: 0.23822310442012146
Fold 2 IBS: 0.22082389042808778
Fold 3 IBS: 0.21617819266873767
Fold 4 IBS: 0.22083570661740062
Fold 5 IBS: 0.212520406059525
[I 2024-04-13 17:52:52,701] Trial 19 finished with value: 0.22171626003877448 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 472, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8783131293076132, 'min_weight_fraction_leaf': 0.21750931502909437}. Best is trial 6 with value: 0.2217024510169873.
Fold 1 IBS: 0.23978115079543136
Fold 2 IBS: 0.22102693456765662
Fold 3 IBS: 0.21595187304093874
Fold 4 IBS: 0.2216906034184558
Fold 5 IBS: 0.21334747365533774
[I 2024-04-13 17:53:00,110] Trial 20 finished with value: 0.22235960709556407 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2, 'n_estimators': 193, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6674617762374991, 'min_weight_fraction_leaf': 0.052244964480646444}. Best is trial 6 with value: 0.2217024510169873.
Fold 1 IBS: 0.2382145836204124
Fold 2 IBS: 0.22082487384773727
Fold 3 IBS: 0.2161214252427926
Fold 4 IBS: 0.220810091101422
Fold 5 IBS: 0.2125097218973879
[I 2024-04-13 17:53:17,426] Trial 21 finished with value: 0.22169613914195044 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 471, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8656522342617734, 'min_weight_fraction_leaf': 0.21629222136444232}. Best is trial 21 with value: 0.22169613914195044.
Fold 1 IBS: 0.23897001456838665
Fold 2 IBS: 0.22066064867637594
Fold 3 IBS: 0.21660585791774262
Fold 4 IBS: 0.22051607231812967
Fold 5 IBS: 0.21217050567263934
[I 2024-04-13 17:53:30,312] Trial 22 finished with value: 0.22178461983065484 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 393, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8782949389210797, 'min_weight_fraction_leaf': 0.10639376509069082}. Best is trial 21 with value: 0.22169613914195044.
Fold 1 IBS: 0.2461833124213814
Fold 2 IBS: 0.2322166915132466
Fold 3 IBS: 0.22949308941273586
Fold 4 IBS: 0.241516737163154
Fold 5 IBS: 0.23029034478689933
[I 2024-04-13 17:53:46,948] Trial 23 finished with value: 0.23594003505948344 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 462, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5056803131468767, 'min_weight_fraction_leaf': 0.3244245165936095}. Best is trial 21 with value: 0.22169613914195044.
Fold 1 IBS: 0.2386378728537682
Fold 2 IBS: 0.22083624121798048
Fold 3 IBS: 0.2165611416409781
Fold 4 IBS: 0.22064291533845887
Fold 5 IBS: 0.21235909927444557
[I 2024-04-13 17:54:03,951] Trial 24 finished with value: 0.2218074540651262 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 403, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7003319970220903, 'min_weight_fraction_leaf': 0.047584473773486055}. Best is trial 21 with value: 0.22169613914195044.
Fold 1 IBS: 0.23769841560901694
Fold 2 IBS: 0.22263565230199767
Fold 3 IBS: 0.2159523247720378
Fold 4 IBS: 0.22331292990002805
Fold 5 IBS: 0.2149422333995474
[I 2024-04-13 17:54:18,949] Trial 25 finished with value: 0.2229083111965256 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 332, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.561451151560548, 'min_weight_fraction_leaf': 0.18672275104960895}. Best is trial 21 with value: 0.22169613914195044.
Fold 1 IBS: 0.24059178271871356
Fold 2 IBS: 0.22497825519345405
Fold 3 IBS: 0.2133474325838035
Fold 4 IBS: 0.22147997830337118
Fold 5 IBS: 0.21185037383003746
[I 2024-04-13 17:54:39,491] Trial 26 finished with value: 0.22244956452587594 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8698062652605099, 'min_weight_fraction_leaf': 0.0035978786324019686}. Best is trial 21 with value: 0.22169613914195044.
Fold 1 IBS: 0.2298828186510494
Fold 2 IBS: 0.2245612386148357
Fold 3 IBS: 0.2130968579334625
Fold 4 IBS: 0.22141977946879637
Fold 5 IBS: 0.21229775404752127
[I 2024-04-13 17:54:55,278] Trial 27 finished with value: 0.22025168974313308 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 496, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6441923486210742, 'min_weight_fraction_leaf': 0.2659216548836133}. Best is trial 27 with value: 0.22025168974313308.
Fold 1 IBS: 0.24609960245004317
Fold 2 IBS: 0.23225967287717042
Fold 3 IBS: 0.2298297971391293
Fold 4 IBS: 0.2413340686846366
Fold 5 IBS: 0.23044245186759124
[I 2024-04-13 17:55:11,086] Trial 28 finished with value: 0.23599311860371414 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.2888110376335854, 'min_weight_fraction_leaf': 0.26419215603415697}. Best is trial 27 with value: 0.22025168974313308.
Fold 1 IBS: 0.24654144834713274
Fold 2 IBS: 0.23221509293429085
Fold 3 IBS: 0.22963285440381911
Fold 4 IBS: 0.24146763585190242
Fold 5 IBS: 0.23032358873869438
[I 2024-04-13 17:55:21,787] Trial 29 finished with value: 0.2360361240551679 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 345, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7417740935442027, 'min_weight_fraction_leaf': 0.3780502719609262}. Best is trial 27 with value: 0.22025168974313308.

Fold 1 IBS: 0.23399276619717632
Fold 2 IBS: 0.23002127894114327
Fold 3 IBS: 0.20843753875222787
Fold 4 IBS: 0.2160171050438523
Fold 5 IBS: 0.21248159379191128
[I 2024-04-13 17:55:31,817] Trial 30 finished with value: 0.2201900565452622 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 9, 'n_estimators': 287, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.2917886569515737}. Best is trial 30 with value: 0.2201900565452622.
Fold 1 IBS: 0.23076757571589473
Fold 2 IBS: 0.22736450708093134
Fold 3 IBS: 0.20888035387329829
Fold 4 IBS: 0.21707897025702066
Fold 5 IBS: 0.2122428672001695
[I 2024-04-13 17:55:44,684] Trial 31 finished with value: 0.2192668548254629 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 9, 'n_estimators': 279, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8304907299557232, 'min_weight_fraction_leaf': 0.3083299613298841}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23389366678580145
Fold 2 IBS: 0.23007022354116088
Fold 3 IBS: 0.20839772380360666
Fold 4 IBS: 0.21600844316385961
Fold 5 IBS: 0.21248710352942624
[I 2024-04-13 17:55:56,237] Trial 32 finished with value: 0.22017143216477097 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 289, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8351362154448183, 'min_weight_fraction_leaf': 0.2883964436727561}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23523991245669582
Fold 2 IBS: 0.23160081895726226
Fold 3 IBS: 0.20994078999828586
Fold 4 IBS: 0.21581282926237855
Fold 5 IBS: 0.21270823549734744
[I 2024-04-13 17:56:07,762] Trial 33 finished with value: 0.22106051723439396 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 4, 'n_estimators': 293, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9298270958993008, 'min_weight_fraction_leaf': 0.2927743558887993}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.2380334840404153
Fold 2 IBS: 0.23101613011787694
Fold 3 IBS: 0.21117756551671693
Fold 4 IBS: 0.21593109271870062
Fold 5 IBS: 0.21253693365307608
[I 2024-04-13 17:56:16,619] Trial 34 finished with value: 0.22173904120935717 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 9, 'n_estimators': 227, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8100986476692471, 'min_weight_fraction_leaf': 0.24668962137163852}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23082146385971022
Fold 2 IBS: 0.22679484325063592
Fold 3 IBS: 0.20874387504191425
Fold 4 IBS: 0.2178351493089424
Fold 5 IBS: 0.21228836544710597
[I 2024-04-13 17:56:24,634] Trial 35 finished with value: 0.21929673938166178 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 146, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8309627620865592, 'min_weight_fraction_leaf': 0.3113092317574124}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23136978668344663
Fold 2 IBS: 0.2264910957098203
Fold 3 IBS: 0.2095321513717733
Fold 4 IBS: 0.21982415491836196
Fold 5 IBS: 0.21208864981338652
[I 2024-04-13 17:56:35,930] Trial 36 finished with value: 0.21986116769935773 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9924114953330869, 'min_weight_fraction_leaf': 0.3946993143283221}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23174624896672005
Fold 2 IBS: 0.22499630512935664
Fold 3 IBS: 0.21173878050164205
Fold 4 IBS: 0.22309383190840693
Fold 5 IBS: 0.21235020456199796
[I 2024-04-13 17:56:43,248] Trial 37 finished with value: 0.22078507421362473 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 6, 'n_estimators': 127, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9792759365378422, 'min_weight_fraction_leaf': 0.4051080539105396}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23246886466109667
Fold 2 IBS: 0.22859653963377102
Fold 3 IBS: 0.20795507869907404
Fold 4 IBS: 0.2165560139537624
Fold 5 IBS: 0.21239722445149095
[I 2024-04-13 17:56:51,526] Trial 38 finished with value: 0.219594744279839 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 165, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9227000475052555, 'min_weight_fraction_leaf': 0.3260292304488785}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.24629763079781522
Fold 2 IBS: 0.23208919211802334
Fold 3 IBS: 0.2294752706495272
Fold 4 IBS: 0.24172547405770814
Fold 5 IBS: 0.23043024168937096
[I 2024-04-13 17:57:00,098] Trial 39 finished with value: 0.236003561862489 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 152, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9281582518574856, 'min_weight_fraction_leaf': 0.49358612050712003}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.24281434838528432
Fold 2 IBS: 0.23018021733893113
Fold 3 IBS: 0.22771922762259986
Fold 4 IBS: 0.23901289774297646
Fold 5 IBS: 0.2248964344098646
[I 2024-04-13 17:57:09,936] Trial 40 finished with value: 0.23292462509993123 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 5, 'n_estimators': 197, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.749612172223078, 'min_weight_fraction_leaf': 0.36054792667782315}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23318702062761634
Fold 2 IBS: 0.229731072689849
Fold 3 IBS: 0.20876600223899328
Fold 4 IBS: 0.21624679099372182
Fold 5 IBS: 0.212502469797693
[I 2024-04-13 17:57:19,749] Trial 41 finished with value: 0.22008667126957468 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 8, 'n_estimators': 227, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9225322063829279, 'min_weight_fraction_leaf': 0.32198436987841994}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23438085534095307
Fold 2 IBS: 0.23091599393335854
Fold 3 IBS: 0.209084228396876
Fold 4 IBS: 0.21593292494409402
Fold 5 IBS: 0.21261067000506706
[I 2024-04-13 17:57:30,263] Trial 42 finished with value: 0.22058493452406971 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 223, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9955179033205579, 'min_weight_fraction_leaf': 0.3292966390754162}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23757150559112203
Fold 2 IBS: 0.22736153902988895
Fold 3 IBS: 0.22390981569636476
Fold 4 IBS: 0.23514610429476115
Fold 5 IBS: 0.2175649546397977
[I 2024-04-13 17:57:39,516] Trial 43 finished with value: 0.22831078385038692 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 173, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9246956257041772, 'min_weight_fraction_leaf': 0.4235416518034208}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23568021047515897
Fold 2 IBS: 0.23033484869429421
Fold 3 IBS: 0.21135773063498697
Fold 4 IBS: 0.21608721730274752
Fold 5 IBS: 0.2123432523639648
[I 2024-04-13 17:57:44,688] Trial 44 finished with value: 0.22116065189423048 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 94, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9558398688120386, 'min_weight_fraction_leaf': 0.3104353906286901}. Best is trial 31 with value: 0.2192668548254629.

Fold 1 IBS: 0.23270396069165322
Fold 2 IBS: 0.2247705563008025
Fold 3 IBS: 0.21879972765768144
Fold 4 IBS: 0.22790183002628017
Fold 5 IBS: 0.21399863217460155
[I 2024-04-13 17:57:56,764] Trial 45 finished with value: 0.22363494137020376 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 227, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9009043234203283, 'min_weight_fraction_leaf': 0.3924440977020272}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23543434584536324
Fold 2 IBS: 0.22537115951414122
Fold 3 IBS: 0.22058241697244674
Fold 4 IBS: 0.23241260728025231
Fold 5 IBS: 0.21519591350899975
[I 2024-04-13 17:58:03,527] Trial 46 finished with value: 0.22579928862424067 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 10, 'n_estimators': 125, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.795904872323232, 'min_weight_fraction_leaf': 0.3519793806338487}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.24340591869617542
Fold 2 IBS: 0.2288903212847643
Fold 3 IBS: 0.2268425893190363
Fold 4 IBS: 0.24187762977351737
Fold 5 IBS: 0.22315374562451212
[I 2024-04-13 17:58:04,789] Trial 47 finished with value: 0.2328340409396011 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 5, 'n_estimators': 15, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9933453642283873, 'min_weight_fraction_leaf': 0.44447707744068815}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23864889142422424
Fold 2 IBS: 0.2268311243938173
Fold 3 IBS: 0.22166156299233114
Fold 4 IBS: 0.23271200912521686
Fold 5 IBS: 0.22038701017751205
[I 2024-04-13 17:58:12,187] Trial 48 finished with value: 0.22804811962262034 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 170, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8378361070632359, 'min_weight_fraction_leaf': 0.3447974537754096}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23258725480561077
Fold 2 IBS: 0.22959770732858972
Fold 3 IBS: 0.20850116118213752
Fold 4 IBS: 0.21628184950315082
Fold 5 IBS: 0.21248797958209828
[I 2024-04-13 17:58:22,196] Trial 49 finished with value: 0.2198911904803174 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 249, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9049798703019389, 'min_weight_fraction_leaf': 0.318162596564374}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.22978423930616157
Fold 2 IBS: 0.22721250482102875
Fold 3 IBS: 0.2095782052744145
Fold 4 IBS: 0.21870612046998
Fold 5 IBS: 0.21219127895203863
[I 2024-04-13 17:58:32,378] Trial 50 finished with value: 0.2194944697647247 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 12, 'n_estimators': 244, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9638393862913052, 'min_weight_fraction_leaf': 0.37804583710334605}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23010466764866047
Fold 2 IBS: 0.22540892638330684
Fold 3 IBS: 0.21118697128643413
Fold 4 IBS: 0.22022127836503555
Fold 5 IBS: 0.2121435085628499
[I 2024-04-13 17:58:44,776] Trial 51 finished with value: 0.2198130704492574 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 263, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.957889367228467, 'min_weight_fraction_leaf': 0.3829451569622122}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.22990079412936107
Fold 2 IBS: 0.22612131328177204
Fold 3 IBS: 0.2104343119628084
Fold 4 IBS: 0.21977913710055086
Fold 5 IBS: 0.21218607011994875
[I 2024-04-13 17:59:02,885] Trial 52 finished with value: 0.2196843253188882 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 12, 'n_estimators': 257, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9597996448193084, 'min_weight_fraction_leaf': 0.3867132080448901}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.2361419967357782
Fold 2 IBS: 0.22543979570559589
Fold 3 IBS: 0.2198096369544081
Fold 4 IBS: 0.23050335538715153
Fold 5 IBS: 0.21936301156134108
[I 2024-04-13 17:59:19,616] Trial 53 finished with value: 0.22625155926885493 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 12, 'n_estimators': 248, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.956269762303755, 'min_weight_fraction_leaf': 0.3750396638248944}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23217407305696658
Fold 2 IBS: 0.22511251974099128
Fold 3 IBS: 0.21901068037427557
Fold 4 IBS: 0.22806987833987846
Fold 5 IBS: 0.21419787399633064
[I 2024-04-13 17:59:33,125] Trial 54 finished with value: 0.2237130051016885 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 279, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9591379905348352, 'min_weight_fraction_leaf': 0.41820247068929195}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.24655978591469624
Fold 2 IBS: 0.2321448953434245
Fold 3 IBS: 0.22954946656961903
Fold 4 IBS: 0.24151512467905287
Fold 5 IBS: 0.23030192974020455
[I 2024-04-13 17:59:47,872] Trial 55 finished with value: 0.23601424044939945 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 310, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8942672627638196, 'min_weight_fraction_leaf': 0.46159240098850357}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.2340572942926832
Fold 2 IBS: 0.22528485370357115
Fold 3 IBS: 0.21845300504720178
Fold 4 IBS: 0.22878462852462372
Fold 5 IBS: 0.21633919568430207
[I 2024-04-13 17:59:58,210] Trial 56 finished with value: 0.2245837954504764 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 209, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8507558408038323, 'min_weight_fraction_leaf': 0.37687430535673583}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.2393407381848937
Fold 2 IBS: 0.22177631559699643
Fold 3 IBS: 0.2166274115633526
Fold 4 IBS: 0.22351389743882497
Fold 5 IBS: 0.21410203062579447
[I 2024-04-13 18:00:05,448] Trial 57 finished with value: 0.22307207868197249 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 11, 'n_estimators': 138, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.78804761889219, 'min_weight_fraction_leaf': 0.24643230344782854}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.24332900933356533
Fold 2 IBS: 0.23002892200411612
Fold 3 IBS: 0.22858436877019095
Fold 4 IBS: 0.2406068838645859
Fold 5 IBS: 0.22856452325048848
[I 2024-04-13 18:00:11,607] Trial 58 finished with value: 0.23422274144458935 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 87, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7242363756488351, 'min_weight_fraction_leaf': 0.3485279903797199}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.2466822127747243
Fold 2 IBS: 0.23214579479086797
Fold 3 IBS: 0.22955767053072515
Fold 4 IBS: 0.24156088702682812
Fold 5 IBS: 0.2302851796867127
[I 2024-04-13 18:00:29,222] Trial 59 finished with value: 0.23604634896197166 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 12, 'n_estimators': 262, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8153261150111123, 'min_weight_fraction_leaf': 0.4455122122074657}. Best is trial 31 with value: 0.2192668548254629.

Fold 1 IBS: 0.23666005092979583
Fold 2 IBS: 0.22960088648063198
Fold 3 IBS: 0.21026693389077333
Fold 4 IBS: 0.21605391871068125
Fold 5 IBS: 0.21236821700846553
[I 2024-04-13 18:00:35,959] Trial 60 finished with value: 0.2209900014040696 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 74, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9576577192543246, 'min_weight_fraction_leaf': 0.3073603256015917}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23135626316866256
Fold 2 IBS: 0.22645553110407532
Fold 3 IBS: 0.20966122609641344
Fold 4 IBS: 0.21984941434508204
Fold 5 IBS: 0.21202533188860895
[I 2024-04-13 18:00:46,898] Trial 61 finished with value: 0.21986955332056848 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 182, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.99214746221766, 'min_weight_fraction_leaf': 0.39027279105902624}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23496623648597323
Fold 2 IBS: 0.22579051032417302
Fold 3 IBS: 0.22067358866115777
Fold 4 IBS: 0.23164759127137816
Fold 5 IBS: 0.217906635426577
[I 2024-04-13 18:00:57,665] Trial 62 finished with value: 0.22619691243385182 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 211, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8935056044223977, 'min_weight_fraction_leaf': 0.40507097655941476}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23182233799611301
Fold 2 IBS: 0.2285742874149463
Fold 3 IBS: 0.20815588614657485
Fold 4 IBS: 0.216789947048027
Fold 5 IBS: 0.2122471094315031
[I 2024-04-13 18:01:05,138] Trial 63 finished with value: 0.21951791360743286 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 157, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.958747079942306, 'min_weight_fraction_leaf': 0.3451653476521068}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23417615428373165
Fold 2 IBS: 0.22488556964938433
Fold 3 IBS: 0.21780313515409852
Fold 4 IBS: 0.22923158189296422
Fold 5 IBS: 0.21478067211419993
[I 2024-04-13 18:01:13,168] Trial 64 finished with value: 0.22417542261887574 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 155, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.769464442687724, 'min_weight_fraction_leaf': 0.33622762448826665}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.238235872270308
Fold 2 IBS: 0.22731352763704052
Fold 3 IBS: 0.2224156955784485
Fold 4 IBS: 0.23547249372835422
Fold 5 IBS: 0.22236993583403908
[I 2024-04-13 18:01:21,470] Trial 65 finished with value: 0.22916150500963806 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 118, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8587315367454188, 'min_weight_fraction_leaf': 0.36011153566364434}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23621521316037963
Fold 2 IBS: 0.2316891149722665
Fold 3 IBS: 0.21121087106800113
Fold 4 IBS: 0.21593902840359736
Fold 5 IBS: 0.2126273538521914
[I 2024-04-13 18:01:38,940] Trial 66 finished with value: 0.2215363162912872 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 239, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9069497098443018, 'min_weight_fraction_leaf': 0.2772702088742331}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23853943883289327
Fold 2 IBS: 0.22167996982401592
Fold 3 IBS: 0.21556213260502416
Fold 4 IBS: 0.22199870468610983
Fold 5 IBS: 0.213282398525894
[I 2024-04-13 18:01:53,095] Trial 67 finished with value: 0.22221252889478743 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 272, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9610375795497859, 'min_weight_fraction_leaf': 0.29900999686535323}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23158092089398447
Fold 2 IBS: 0.22461575577682472
Fold 3 IBS: 0.21780530081964466
Fold 4 IBS: 0.22723538390693565
Fold 5 IBS: 0.21359631775884283
[I 2024-04-13 18:02:00,607] Trial 68 finished with value: 0.22296673583124646 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 149, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8751836338203831, 'min_weight_fraction_leaf': 0.37307770762977893}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.24658883679050714
Fold 2 IBS: 0.2321911716479223
Fold 3 IBS: 0.22947308489861604
Fold 4 IBS: 0.2414078728483683
Fold 5 IBS: 0.23026870227551022
[I 2024-04-13 18:02:14,651] Trial 69 finished with value: 0.2359859336921848 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 315, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6078285481908889, 'min_weight_fraction_leaf': 0.33614701852974804}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23673015699911315
Fold 2 IBS: 0.23197590892037398
Fold 3 IBS: 0.2132240118160762
Fold 4 IBS: 0.21577973561950578
Fold 5 IBS: 0.21270416323290017
[I 2024-04-13 18:02:28,743] Trial 70 finished with value: 0.22208279531759384 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 15, 'n_estimators': 298, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.933967732917093, 'min_weight_fraction_leaf': 0.23280294231923104}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.2304287176270365
Fold 2 IBS: 0.22433284861711553
Fold 3 IBS: 0.21344509034298922
Fold 4 IBS: 0.22669252542763177
Fold 5 IBS: 0.21243211513223034
[I 2024-04-13 18:02:34,737] Trial 71 finished with value: 0.22146625942940065 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 110, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9772500056032768, 'min_weight_fraction_leaf': 0.41015256052927934}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.2466339298189497
Fold 2 IBS: 0.23218831261562073
Fold 3 IBS: 0.22934216715640737
Fold 4 IBS: 0.2414951085687376
Fold 5 IBS: 0.23034238737602417
[I 2024-04-13 18:02:43,167] Trial 72 finished with value: 0.2360003811071479 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 163, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5190754520109059, 'min_weight_fraction_leaf': 0.39116262094490645}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.2315151028915978
Fold 2 IBS: 0.22501231177690922
Fold 3 IBS: 0.21839890097940556
Fold 4 IBS: 0.22894774135978258
Fold 5 IBS: 0.21535464150696176
[I 2024-04-13 18:02:51,275] Trial 73 finished with value: 0.22384573970293137 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 181, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9986409990671044, 'min_weight_fraction_leaf': 0.4380739434200745}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23095713854460032
Fold 2 IBS: 0.22691891582601215
Fold 3 IBS: 0.2095972941184841
Fold 4 IBS: 0.21921176644344303
Fold 5 IBS: 0.21218268698233814
[I 2024-04-13 18:02:59,614] Trial 74 finished with value: 0.21977356038297557 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 191, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9392514631162905, 'min_weight_fraction_leaf': 0.3639267238452427}. Best is trial 31 with value: 0.2192668548254629.

Fold 1 IBS: 0.2395442223429733
Fold 2 IBS: 0.22912945601230464
Fold 3 IBS: 0.22469665996463767
Fold 4 IBS: 0.23655575742859675
Fold 5 IBS: 0.2229792723639496
[I 2024-04-13 18:03:10,011] Trial 75 finished with value: 0.23058107362249242 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 243, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8260830230779004, 'min_weight_fraction_leaf': 0.36247953138659794}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.2370931245618715
Fold 2 IBS: 0.22434008390481244
Fold 3 IBS: 0.2177837484984773
Fold 4 IBS: 0.22722248718170873
Fold 5 IBS: 0.21608148066710028
[I 2024-04-13 18:03:18,033] Trial 76 finished with value: 0.22450418496279406 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 208, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9353287569377416, 'min_weight_fraction_leaf': 0.3382522395489986}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.2331435603914225
Fold 2 IBS: 0.2304195088660915
Fold 3 IBS: 0.20860214990406267
Fold 4 IBS: 0.21605891363735868
Fold 5 IBS: 0.21249726723856147
[I 2024-04-13 18:03:30,309] Trial 77 finished with value: 0.22014428000749936 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 343, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8806708361762731, 'min_weight_fraction_leaf': 0.3052727956121554}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23058355327630498
Fold 2 IBS: 0.22640854825774276
Fold 3 IBS: 0.21010693676231826
Fold 4 IBS: 0.21884203346417352
Fold 5 IBS: 0.21216047131796373
[I 2024-04-13 18:03:40,918] Trial 78 finished with value: 0.21962030861570064 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 260, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9066976988109772, 'min_weight_fraction_leaf': 0.3577399516263571}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23884494271853401
Fold 2 IBS: 0.22138655476926786
Fold 3 IBS: 0.21598050597455556
Fold 4 IBS: 0.2221035799307165
Fold 5 IBS: 0.21338575482566965
[I 2024-04-13 18:03:47,739] Trial 79 finished with value: 0.2223402676437487 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 9, 'n_estimators': 192, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9156992568192303, 'min_weight_fraction_leaf': 0.27262250316613845}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23266914384513093
Fold 2 IBS: 0.22785140587976258
Fold 3 IBS: 0.2088002464575267
Fold 4 IBS: 0.21729610048673104
Fold 5 IBS: 0.21212031225876643
[I 2024-04-13 18:03:53,502] Trial 80 finished with value: 0.21974744178558353 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 136, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8633707802030953, 'min_weight_fraction_leaf': 0.324162512890376}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23139823018403677
Fold 2 IBS: 0.22760446541776114
Fold 3 IBS: 0.20923976306713915
Fold 4 IBS: 0.2175415498382573
Fold 5 IBS: 0.2121475147822062
[I 2024-04-13 18:03:59,316] Trial 81 finished with value: 0.21958630465788015 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 134, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.85739975561835, 'min_weight_fraction_leaf': 0.3194639487730314}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23259368199854583
Fold 2 IBS: 0.2278272792913496
Fold 3 IBS: 0.20916748919930642
Fold 4 IBS: 0.2167455123491002
Fold 5 IBS: 0.21228003828290398
[I 2024-04-13 18:04:02,195] Trial 82 finished with value: 0.2197228002242412 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 56, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.848217914402437, 'min_weight_fraction_leaf': 0.3131942572097646}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.24839165612497463
Fold 2 IBS: 0.23379368014096644
Fold 3 IBS: 0.23063160575161995
Fold 4 IBS: 0.24985357080259854
Fold 5 IBS: 0.22912633851915687
[I 2024-04-13 18:04:02,995] Trial 83 finished with value: 0.2383593702678633 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 13, 'n_estimators': 2, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4499919256607343, 'min_weight_fraction_leaf': 0.28268107499718625}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.2315368684415362
Fold 2 IBS: 0.2252363208821146
Fold 3 IBS: 0.2122814574987705
Fold 4 IBS: 0.2198208515657548
Fold 5 IBS: 0.21206477336564636
[I 2024-04-13 18:04:04,890] Trial 84 finished with value: 0.22018805435076452 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 14, 'n_estimators': 36, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8020351012837847, 'min_weight_fraction_leaf': 0.3182765919728577}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.24692079968665137
Fold 2 IBS: 0.2320630334218079
Fold 3 IBS: 0.22992264108912713
Fold 4 IBS: 0.24101322887374907
Fold 5 IBS: 0.22924723193176946
[I 2024-04-13 18:04:09,023] Trial 85 finished with value: 0.23583338700062098 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 99, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10698873156508726, 'min_weight_fraction_leaf': 0.3514482159983338}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23154670818329032
Fold 2 IBS: 0.22469800099537704
Fold 3 IBS: 0.21246842375790229
Fold 4 IBS: 0.21927198628389874
Fold 5 IBS: 0.21210837779190325
[I 2024-04-13 18:04:10,748] Trial 86 finished with value: 0.22001869940247434 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 35, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6760922617749208, 'min_weight_fraction_leaf': 0.26369371635828887}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.2348780197917542
Fold 2 IBS: 0.22837411264463117
Fold 3 IBS: 0.21078528612533182
Fold 4 IBS: 0.2163876456034622
Fold 5 IBS: 0.21217001268543254
[I 2024-04-13 18:04:13,383] Trial 87 finished with value: 0.22051901537012236 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 50, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8922493791626227, 'min_weight_fraction_leaf': 0.307611266267913}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.2387701359246918
Fold 2 IBS: 0.2251544804479686
Fold 3 IBS: 0.22017759492331138
Fold 4 IBS: 0.23125232432988965
Fold 5 IBS: 0.21965822863088086
[I 2024-04-13 18:04:16,668] Trial 88 finished with value: 0.22700255285134846 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 66, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8256459477084612, 'min_weight_fraction_leaf': 0.3294401758895406}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23368119907254972
Fold 2 IBS: 0.2286029376097039
Fold 3 IBS: 0.20855265438220547
Fold 4 IBS: 0.21647371023180684
Fold 5 IBS: 0.21230329633222164
[I 2024-04-13 18:04:22,209] Trial 89 finished with value: 0.21992275952569754 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 10, 'n_estimators': 142, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8511203569957244, 'min_weight_fraction_leaf': 0.2975531136108974}. Best is trial 31 with value: 0.2192668548254629.

Fold 1 IBS: 0.23800441993348706
Fold 2 IBS: 0.22767850269903261
Fold 3 IBS: 0.2237206426833651
Fold 4 IBS: 0.23428835882497379
Fold 5 IBS: 0.2187778931045527
[I 2024-04-13 18:04:31,619] Trial 90 finished with value: 0.22849396344908227 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 302, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7414077144426384, 'min_weight_fraction_leaf': 0.3433264918658795}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23257608160494517
Fold 2 IBS: 0.22777477042423552
Fold 3 IBS: 0.2089356907749039
Fold 4 IBS: 0.2174045202478247
Fold 5 IBS: 0.21222141483842463
[I 2024-04-13 18:04:40,257] Trial 91 finished with value: 0.2197824955780668 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 133, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8625575224781323, 'min_weight_fraction_leaf': 0.32053602948874793}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.2324253705182325
Fold 2 IBS: 0.23016497647030884
Fold 3 IBS: 0.20839779156207727
Fold 4 IBS: 0.21614629844488611
Fold 5 IBS: 0.21260489621574127
[I 2024-04-13 18:04:56,324] Trial 92 finished with value: 0.2199478666422492 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 281, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9160325574342332, 'min_weight_fraction_leaf': 0.3159565444755686}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23178013550308801
Fold 2 IBS: 0.22462868986961665
Fold 3 IBS: 0.2177797114195952
Fold 4 IBS: 0.2278626520333656
Fold 5 IBS: 0.21384330468850063
[I 2024-04-13 18:05:01,151] Trial 93 finished with value: 0.22317889870283322 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 114, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8441277661599853, 'min_weight_fraction_leaf': 0.36551654882450735}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23513601012773258
Fold 2 IBS: 0.2266902735641256
Fold 3 IBS: 0.22195837532102577
Fold 4 IBS: 0.23374466818767123
Fold 5 IBS: 0.21682553994708048
[I 2024-04-13 18:05:07,124] Trial 94 finished with value: 0.22687097342952717 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 11, 'n_estimators': 166, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7746974345753173, 'min_weight_fraction_leaf': 0.3528680857698217}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23339947264585928
Fold 2 IBS: 0.23072019782974088
Fold 3 IBS: 0.20865529566147864
Fold 4 IBS: 0.21596806483754896
Fold 5 IBS: 0.21260775281211636
[I 2024-04-13 18:05:16,415] Trial 95 finished with value: 0.2202701567573488 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 235, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9720361135317509, 'min_weight_fraction_leaf': 0.33235719868685154}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.2353200684057001
Fold 2 IBS: 0.23101075835067414
Fold 3 IBS: 0.20989509615963461
Fold 4 IBS: 0.21580502299232518
Fold 5 IBS: 0.21260973047340737
[I 2024-04-13 18:05:32,465] Trial 96 finished with value: 0.2209281352763483 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 14, 'n_estimators': 258, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8791242238153729, 'min_weight_fraction_leaf': 0.2876125763845704}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.24031215676448495
Fold 2 IBS: 0.2220710049155521
Fold 3 IBS: 0.21694847626640162
Fold 4 IBS: 0.22306707307651202
Fold 5 IBS: 0.2140567864789993
[I 2024-04-13 18:05:39,562] Trial 97 finished with value: 0.22329109950039 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 105, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8079421034412063, 'min_weight_fraction_leaf': 0.2561896927724311}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23244287094821106
Fold 2 IBS: 0.22983181954771942
Fold 3 IBS: 0.20861647834664757
Fold 4 IBS: 0.21622494301078155
Fold 5 IBS: 0.21254708847137146
[I 2024-04-13 18:05:47,346] Trial 98 finished with value: 0.21993264006494623 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 218, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9449672415035856, 'min_weight_fraction_leaf': 0.32814491703340787}. Best is trial 31 with value: 0.2192668548254629.
Fold 1 IBS: 0.23770399905470235
Fold 2 IBS: 0.22269007383430658
Fold 3 IBS: 0.2160064356769886
Fold 4 IBS: 0.22413546698429898
Fold 5 IBS: 0.2143004278166216
[I 2024-04-13 18:06:01,654] Trial 99 finished with value: 0.22296728067338362 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 324, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8900335731402472, 'min_weight_fraction_leaf': 0.3016386039249824}. Best is trial 31 with value: 0.2192668548254629.


* Best trial for IBS:
 FrozenTrial(number=31, state=TrialState.COMPLETE, values=[0.2192668548254629], datetime_start=datetime.datetime(2024, 4, 13, 17, 55, 31, 838529), datetime_complete=datetime.datetime(2024, 4, 13, 17, 55, 44, 680700), params={'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 9, 'n_estimators': 279, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8304907299557232, 'min_weight_fraction_leaf': 0.3083299613298841}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=31, value=None)


* Best Score for IBS:
 0.2192668548254629

In [54]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [55]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.64
train_ibs:  0.219

#### Test

In [56]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [57]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=12, max_features='log2', max_leaf_nodes=7,
                   max_samples=0.7641958651588321, min_samples_leaf=5,
                   min_samples_split=15,
                   min_weight_fraction_leaf=0.09124586522674999,
                   n_estimators=360, random_state=123, warm_start=True)

C-index score: 0.654

ExtraSurvivalTrees(max_depth=9, max_features=None, max_leaf_nodes=20,
                   max_samples=0.8304907299557232, min_samples_leaf=12,
                   min_samples_split=8,
                   min_weight_fraction_leaf=0.3083299613298841,
                   n_estimators=279, random_state=123)

IBS: 0.222

In [58]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [59]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 18:06:07,464] A new study created in memory with name: no-name-a0c92d7a-b6ab-4dd8-a18b-c3eb35a71b0b

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:07:09,404] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:07:45,401] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:08:25,255] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:09:30,364] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:09:58,483] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:10:05,700] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:11:03,298] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:11:18,750] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:11:20,533] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 18:13:31,502] Trial 9 finished with value: 0.6202663488296567 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6202663488296567.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 18:16:53,366] Trial 10 finished with value: 0.59752708180585 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6202663488296567.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:20:57,434] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6202663488296567.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 18:24:02,427] Trial 12 finished with value: 0.6214070332403031 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.6214070332403031.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:26:09,653] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 12 with value: 0.6214070332403031.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:28:21,214] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 12 with value: 0.6214070332403031.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:30:18,743] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 12 with value: 0.6214070332403031.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:31:47,754] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 12 with value: 0.6214070332403031.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:34:31,685] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 12 with value: 0.6214070332403031.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:37:56,468] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 12 with value: 0.6214070332403031.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:38:07,543] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.6214070332403031.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:39:33,294] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 12 with value: 0.6214070332403031.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:42:20,524] Trial 21 finished with value: 0.5 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.6214070332403031.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 18:44:48,451] Trial 22 finished with value: 0.6366905799047093 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:46:51,820] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:48:46,401] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:49:47,852] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:52:07,245] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:54:22,761] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:56:15,089] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:57:35,945] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:59:16,165] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:02:27,595] Trial 31 finished with value: 0.5 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:05:41,402] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:07:48,218] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:10:36,422] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:11:12,051] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:13:50,386] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:13:55,722] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.6366905799047093.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:14:59,570] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:16:40,735] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:19:49,564] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:19:50,364] Trial 41 finished with value: 0.5 and parameters: {'subsample': 0.7314932964129175, 'learning_rate': 0.01409866469899027, 'dropout_rate': 0.25927237673806974, 'n_estimators': 1, 'criterion': 'friedman_mse', 'ccp_alpha': 6.422443003379805, 'min_weight_fraction_leaf': 0.2592502890556771, 'max_features': None, 'min_impurity_decrease': 0.00046889459087331233, 'validation_fraction': 0.7339745526007295, 'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:20:44,989] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.8635261303914503, 'learning_rate': 0.06618063570768928, 'dropout_rate': 0.21701156680188333, 'n_estimators': 236, 'criterion': 'friedman_mse', 'ccp_alpha': 8.230119285920345, 'min_weight_fraction_leaf': 0.3447746516166785, 'max_features': None, 'min_impurity_decrease': 1.9832896573105213e-05, 'validation_fraction': 0.6587210926816298, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:22:03,385] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5792270906384994, 'learning_rate': 0.007569574313996779, 'dropout_rate': 0.13009999428832833, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 8.544754247040371, 'min_weight_fraction_leaf': 0.37715746272334727, 'max_features': None, 'min_impurity_decrease': 9.019275478873865e-05, 'validation_fraction': 0.8415757140495828, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 10}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:22:26,039] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.7872457012118046, 'learning_rate': 0.042999799171261954, 'dropout_rate': 0.3684859430701791, 'n_estimators': 164, 'criterion': 'friedman_mse', 'ccp_alpha': 9.884609761552603, 'min_weight_fraction_leaf': 0.4563543800389965, 'max_features': None, 'min_impurity_decrease': 2.2080377939848e-07, 'validation_fraction': 0.5674038323356935, 'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 16}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:23:56,098] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.9436582561003044, 'learning_rate': 0.01524983211078064, 'dropout_rate': 0.588577514842217, 'n_estimators': 401, 'criterion': 'friedman_mse', 'ccp_alpha': 6.651892060576439, 'min_weight_fraction_leaf': 0.4018557625407492, 'max_features': 0.1, 'min_impurity_decrease': 1.8062826429116324e-06, 'validation_fraction': 0.9542863654309715, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 9}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:24:29,540] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5165290285700016, 'learning_rate': 0.02319868205399652, 'dropout_rate': 0.9694253886674298, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 9.048241205043816, 'min_weight_fraction_leaf': 0.3115196264589247, 'max_features': 'log2', 'min_impurity_decrease': 0.001644356047914736, 'validation_fraction': 0.8846679916016404, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:26:43,467] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5904822223880848, 'learning_rate': 0.0069795680561797555, 'dropout_rate': 0.27413800857922854, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 7.181314443016622, 'min_weight_fraction_leaf': 0.2227662317014242, 'max_features': 'auto', 'min_impurity_decrease': 5.579254342230346e-06, 'validation_fraction': 0.6898188497269258, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 11}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:27:26,950] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.8377698389118777, 'learning_rate': 0.030447501600320594, 'dropout_rate': 0.4343069730937482, 'n_estimators': 237, 'criterion': 'squared_error', 'ccp_alpha': 0.44229350847698845, 'min_weight_fraction_leaf': 0.27384255345855457, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0799788619370968e-06, 'validation_fraction': 0.8690312650846541, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:28:57,108] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.9014143402771908, 'learning_rate': 0.019069047730291548, 'dropout_rate': 0.15628654397338398, 'n_estimators': 297, 'criterion': 'squared_error', 'ccp_alpha': 1.222549263924274, 'min_weight_fraction_leaf': 0.37835008934172737, 'max_features': 'auto', 'min_impurity_decrease': 2.3869690244810263e-06, 'validation_fraction': 0.6110159828303156, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 12}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:31:59,376] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.6722013360862389, 'learning_rate': 0.0011637610610685928, 'dropout_rate': 0.11834255517896833, 'n_estimators': 417, 'criterion': 'friedman_mse', 'ccp_alpha': 1.772659436678572, 'min_weight_fraction_leaf': 0.33123579278860354, 'max_features': 'auto', 'min_impurity_decrease': 3.3297622395273564e-07, 'validation_fraction': 0.8157407077160861, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 8}. Best is trial 22 with value: 0.6366905799047093.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:32:50,488] Trial 51 finished with value: 0.5 and parameters: {'subsample': 0.4606648159054066, 'learning_rate': 0.09644321475547749, 'dropout_rate': 0.676921980791406, 'n_estimators': 324, 'criterion': 'friedman_mse', 'ccp_alpha': 5.698109912526597, 'min_weight_fraction_leaf': 0.009454723617732017, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0003194574130234848, 'validation_fraction': 0.20910739088327182, 'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 12}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 19:33:08,922] Trial 52 finished with value: 0.6255130467702362 and parameters: {'subsample': 0.6307630032474463, 'learning_rate': 0.0797433994002493, 'dropout_rate': 0.9019406028516623, 'n_estimators': 258, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03710606902460499, 'min_weight_fraction_leaf': 0.14235013403546368, 'max_features': 'sqrt', 'min_impurity_decrease': 4.622343656719489e-05, 'validation_fraction': 0.3406032150791013, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 19:33:18,816] Trial 53 finished with value: 0.6255130467702362 and parameters: {'subsample': 0.539345983620747, 'learning_rate': 0.08646200679648029, 'dropout_rate': 0.9293661770435817, 'n_estimators': 197, 'criterion': 'friedman_mse', 'ccp_alpha': 0.009820569816943125, 'min_weight_fraction_leaf': 0.15776506745071406, 'max_features': 'sqrt', 'min_impurity_decrease': 6.243547110770978e-05, 'validation_fraction': 0.3297138181787256, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 14}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:33:26,981] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.4122659993128194, 'learning_rate': 0.09006054356742435, 'dropout_rate': 0.901466608466225, 'n_estimators': 166, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3662685742538932, 'min_weight_fraction_leaf': 0.12759593111970943, 'max_features': 'sqrt', 'min_impurity_decrease': 5.659382809466258e-05, 'validation_fraction': 0.3370466013536922, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 19:33:32,334] Trial 55 finished with value: 0.6255130467702362 and parameters: {'subsample': 0.6260529149480705, 'learning_rate': 0.07808142247997509, 'dropout_rate': 0.8859792395781099, 'n_estimators': 117, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03680304263373871, 'min_weight_fraction_leaf': 0.15390921956023235, 'max_features': 'sqrt', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.4043604570150481, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:33:36,410] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.5524483139580307, 'learning_rate': 0.08198533807055247, 'dropout_rate': 0.8800223988178697, 'n_estimators': 94, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0376723781883062, 'min_weight_fraction_leaf': 0.15089096313689324, 'max_features': 'sqrt', 'min_impurity_decrease': 0.015875756958720868, 'validation_fraction': 0.38909071963160285, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 19:33:42,591] Trial 57 finished with value: 0.6255130467702362 and parameters: {'subsample': 0.6446884806787394, 'learning_rate': 0.07439616301612664, 'dropout_rate': 0.8376763566011604, 'n_estimators': 113, 'criterion': 'friedman_mse', 'ccp_alpha': 0.0019590724667788023, 'min_weight_fraction_leaf': 0.0986277853305848, 'max_features': 'sqrt', 'min_impurity_decrease': 0.004365976632712866, 'validation_fraction': 0.2924600276956252, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 19:33:49,965] Trial 58 finished with value: 0.6255130467702362 and parameters: {'subsample': 0.6423260507022313, 'learning_rate': 0.07516712250657744, 'dropout_rate': 0.8518170622435416, 'n_estimators': 133, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03768433016684238, 'min_weight_fraction_leaf': 0.09954476156869702, 'max_features': 'sqrt', 'min_impurity_decrease': 0.004081914358688746, 'validation_fraction': 0.242274730848875, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:33:57,549] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.6313527280713852, 'learning_rate': 0.07469156983454199, 'dropout_rate': 0.8380696670936053, 'n_estimators': 127, 'criterion': 'friedman_mse', 'ccp_alpha': 1.4184145643663044, 'min_weight_fraction_leaf': 0.0913313918585067, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0025087626578683365, 'validation_fraction': 0.26275660413903207, 'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 18}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:34:01,462] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.4899715679037606, 'learning_rate': 0.08278768973820787, 'dropout_rate': 0.992625712289238, 'n_estimators': 132, 'criterion': 'friedman_mse', 'ccp_alpha': 0.780319688242447, 'min_weight_fraction_leaf': 0.05601295998326855, 'max_features': 'sqrt', 'min_impurity_decrease': 0.006171355893400138, 'validation_fraction': 0.15179914485999124, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:34:04,101] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.5647418864957664, 'learning_rate': 0.07640237660362989, 'dropout_rate': 0.8293392238511903, 'n_estimators': 57, 'criterion': 'friedman_mse', 'ccp_alpha': 0.34104023788856364, 'min_weight_fraction_leaf': 0.11082557950347653, 'max_features': 'sqrt', 'min_impurity_decrease': 0.03299388350893509, 'validation_fraction': 0.29672119808264846, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 14}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 19:34:13,819] Trial 62 finished with value: 0.6255130467702362 and parameters: {'subsample': 0.6552905903951805, 'learning_rate': 0.06170857832596589, 'dropout_rate': 0.9172603113615274, 'n_estimators': 198, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022327899810791578, 'min_weight_fraction_leaf': 0.19463783622716474, 'max_features': 'sqrt', 'min_impurity_decrease': 0.004071612344743456, 'validation_fraction': 0.4617616369790887, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 22 with value: 0.6366905799047093.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 19:34:23,166] Trial 63 finished with value: 0.6255130467702362 and parameters: {'subsample': 0.6420495134496952, 'learning_rate': 0.06185668684644146, 'dropout_rate': 0.9308017143391651, 'n_estimators': 189, 'criterion': 'friedman_mse', 'ccp_alpha': 0.01772246444701126, 'min_weight_fraction_leaf': 0.14858144219209024, 'max_features': 'sqrt', 'min_impurity_decrease': 0.006413978206952479, 'validation_fraction': 0.4573337116459055, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:34:28,420] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.7206174974383536, 'learning_rate': 0.07120510712435991, 'dropout_rate': 0.8677214246146783, 'n_estimators': 108, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.18961845192414215, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0033282739313507514, 'validation_fraction': 0.3614380631172813, 'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 19}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:34:43,915] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.6105091065926775, 'learning_rate': 0.08767419024484444, 'dropout_rate': 0.7880471835416791, 'n_estimators': 196, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3506207140220197, 'min_weight_fraction_leaf': 0.10172415487869317, 'max_features': 'sqrt', 'min_impurity_decrease': 0.009840588760709439, 'validation_fraction': 0.2977145351524674, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:34:49,094] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.5340685241756573, 'learning_rate': 0.08113813382931176, 'dropout_rate': 0.9434904367282861, 'n_estimators': 130, 'criterion': 'friedman_mse', 'ccp_alpha': 2.1199418624752697, 'min_weight_fraction_leaf': 0.05169650096231847, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0008128235375355284, 'validation_fraction': 0.19733165541401854, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:34:54,373] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.6767365190828926, 'learning_rate': 0.07213981007236235, 'dropout_rate': 0.7387196544237248, 'n_estimators': 80, 'criterion': 'friedman_mse', 'ccp_alpha': 1.180714931483077, 'min_weight_fraction_leaf': 0.14383497802961723, 'max_features': 'sqrt', 'min_impurity_decrease': 0.04710428475886704, 'validation_fraction': 0.40605710059384686, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:35:07,423] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.6004082518210413, 'learning_rate': 0.06340317341687904, 'dropout_rate': 0.9070774837957682, 'n_estimators': 215, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8384553433567888, 'min_weight_fraction_leaf': 0.11899223768430772, 'max_features': 'sqrt', 'min_impurity_decrease': 0.09702377150815918, 'validation_fraction': 0.4673773191730136, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:35:20,072] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.4378828858098471, 'learning_rate': 0.0788657154233329, 'dropout_rate': 0.8371785524461405, 'n_estimators': 180, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2966500702352536, 'min_weight_fraction_leaf': 0.16726136138557446, 'max_features': 'sqrt', 'min_impurity_decrease': 0.014840919191244958, 'validation_fraction': 0.2600297681189202, 'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 14}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 19:35:29,028] Trial 70 finished with value: 0.6255130467702362 and parameters: {'subsample': 0.5054245248434457, 'learning_rate': 0.05664397779437874, 'dropout_rate': 0.7920729765121403, 'n_estimators': 150, 'criterion': 'friedman_mse', 'ccp_alpha': 0.010011742969492199, 'min_weight_fraction_leaf': 0.18265274886909785, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0010885957415164504, 'validation_fraction': 0.3811235784631798, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 19:35:38,026] Trial 71 finished with value: 0.6255130467702362 and parameters: {'subsample': 0.6416858273001564, 'learning_rate': 0.06107775921157192, 'dropout_rate': 0.9347312864694259, 'n_estimators': 191, 'criterion': 'friedman_mse', 'ccp_alpha': 0.027213352242787005, 'min_weight_fraction_leaf': 0.13680933065250028, 'max_features': 'sqrt', 'min_impurity_decrease': 0.003995629767679058, 'validation_fraction': 0.42606237321970863, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:35:46,027] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.3591116754460494, 'learning_rate': 0.06792524373901658, 'dropout_rate': 0.9989845748279984, 'n_estimators': 229, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6275806036925962, 'min_weight_fraction_leaf': 0.15278521297259517, 'max_features': 'sqrt', 'min_impurity_decrease': 0.007066387223730836, 'validation_fraction': 0.5099919934942065, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 18}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:35:50,636] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.7281069973444152, 'learning_rate': 0.0505383884977625, 'dropout_rate': 0.9573624985629287, 'n_estimators': 119, 'criterion': 'friedman_mse', 'ccp_alpha': 0.35435044814394473, 'min_weight_fraction_leaf': 0.06203488789157514, 'max_features': 'sqrt', 'min_impurity_decrease': 0.012268472781848647, 'validation_fraction': 0.46277806656837184, 'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:36:08,217] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.6592686859120654, 'learning_rate': 0.08477062088519764, 'dropout_rate': 0.9141184833083784, 'n_estimators': 256, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9817440429236465, 'min_weight_fraction_leaf': 0.20743996783548818, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00020700246413734948, 'validation_fraction': 0.3219875777100156, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.6366905799047093.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 19:36:16,417] Trial 75 finished with value: 0.6255130467702362 and parameters: {'subsample': 0.6239289807636171, 'learning_rate': 0.09160620724399501, 'dropout_rate': 0.862865764569774, 'n_estimators': 142, 'criterion': 'friedman_mse', 'ccp_alpha': 0.008766296551629273, 'min_weight_fraction_leaf': 0.10666049474531145, 'max_features': 'sqrt', 'min_impurity_decrease': 0.024377357430725458, 'validation_fraction': 0.47538341743898427, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 19}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:36:26,403] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.5711271995599372, 'learning_rate': 0.09979329409197489, 'dropout_rate': 0.8920744137986102, 'n_estimators': 178, 'criterion': 'friedman_mse', 'ccp_alpha': 1.4307783476924183, 'min_weight_fraction_leaf': 0.15451731850146455, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0017554249707113384, 'validation_fraction': 0.4343585752618071, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:36:27,878] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.697199647373898, 'learning_rate': 0.074280940040388, 'dropout_rate': 0.9250538844515723, 'n_estimators': 37, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5989686567916193, 'min_weight_fraction_leaf': 0.19160290292716264, 'max_features': 1, 'min_impurity_decrease': 0.004145110091110191, 'validation_fraction': 0.2850178770185197, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:36:42,040] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.28502877880016236, 'learning_rate': 0.07948420710363319, 'dropout_rate': 0.7171249658802559, 'n_estimators': 163, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2505380847035784, 'min_weight_fraction_leaf': 0.07021234431254411, 'max_features': 'sqrt', 'min_impurity_decrease': 0.001759899427446006, 'validation_fraction': 0.17599099797509504, 'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:37:01,414] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.534978533515904, 'learning_rate': 0.06490308080441287, 'dropout_rate': 0.8028970877233504, 'n_estimators': 214, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5575687879157971, 'min_weight_fraction_leaf': 0.09658983274661984, 'max_features': 0.1, 'min_impurity_decrease': 0.0005581314004004992, 'validation_fraction': 0.37047800007928566, 'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 13}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:37:05,205] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.6564133603328495, 'learning_rate': 0.06933495615579725, 'dropout_rate': 0.9705895024426787, 'n_estimators': 111, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0215944551623608, 'min_weight_fraction_leaf': 0.1275656485346715, 'max_features': 'log2', 'min_impurity_decrease': 0.008439619963309579, 'validation_fraction': 0.32527694273185015, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 19:37:15,340] Trial 81 finished with value: 0.6255130467702362 and parameters: {'subsample': 0.5116468030155126, 'learning_rate': 0.05616939530632608, 'dropout_rate': 0.8135200688991977, 'n_estimators': 142, 'criterion': 'friedman_mse', 'ccp_alpha': 0.025980722802984177, 'min_weight_fraction_leaf': 0.16623837776992983, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0013954132074950293, 'validation_fraction': 0.25362643016371256, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:37:24,423] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.48868172264944576, 'learning_rate': 0.05823852494985946, 'dropout_rate': 0.853687773985988, 'n_estimators': 148, 'criterion': 'friedman_mse', 'ccp_alpha': 0.24418107147562967, 'min_weight_fraction_leaf': 0.18537653704292398, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0028766621031853638, 'validation_fraction': 0.39209558742166345, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:37:36,385] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.6022927595613617, 'learning_rate': 0.05354614892921439, 'dropout_rate': 0.8853627709418257, 'n_estimators': 196, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7541768756467706, 'min_weight_fraction_leaf': 0.17329719015777695, 'max_features': 'sqrt', 'min_impurity_decrease': 0.005101634830757751, 'validation_fraction': 0.3691098535907937, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:37:41,401] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.5843451864592325, 'learning_rate': 0.061819610662325906, 'dropout_rate': 0.7866362037010749, 'n_estimators': 88, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2107629767608731, 'min_weight_fraction_leaf': 0.11548105249354518, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0010596722332266606, 'validation_fraction': 0.5494971378892398, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 14}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 19:37:48,209] Trial 85 finished with value: 0.6255130467702362 and parameters: {'subsample': 0.7089904516785119, 'learning_rate': 0.0853116842897305, 'dropout_rate': 0.9519985585984506, 'n_estimators': 157, 'criterion': 'friedman_mse', 'ccp_alpha': 0.011421239281947375, 'min_weight_fraction_leaf': 0.03988696998928426, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00011883609046827607, 'validation_fraction': 0.23144010928966902, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:37:58,337] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.7503694464992061, 'learning_rate': 0.048548415044312336, 'dropout_rate': 0.9171915209703789, 'n_estimators': 176, 'criterion': 'friedman_mse', 'ccp_alpha': 1.271942449314106, 'min_weight_fraction_leaf': 0.1392949851626346, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002640856486248246, 'validation_fraction': 0.10269695538564061, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 22 with value: 0.6366905799047093.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:38:24,341] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.5437831368993375, 'learning_rate': 0.0717111764324178, 'dropout_rate': 0.8572690816373921, 'n_estimators': 266, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4406949539909599, 'min_weight_fraction_leaf': 0.2352743784376736, 'max_features': 1, 'min_impurity_decrease': 1.6608380458349677e-05, 'validation_fraction': 0.5007434073260012, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:39:04,039] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.6395282340023848, 'learning_rate': 0.07801234910780097, 'dropout_rate': 0.696802829250291, 'n_estimators': 284, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8443943368429427, 'min_weight_fraction_leaf': 0.22207753656444, 'max_features': 'sqrt', 'min_impurity_decrease': 0.01967980241469254, 'validation_fraction': 0.339661057519412, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 14}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:39:08,576] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.4654379983366346, 'learning_rate': 0.04066937477372409, 'dropout_rate': 0.6115098731193679, 'n_estimators': 71, 'criterion': 'friedman_mse', 'ccp_alpha': 3.986146557923886, 'min_weight_fraction_leaf': 0.20394078159962206, 'max_features': 0.1, 'min_impurity_decrease': 0.0418530929615832, 'validation_fraction': 0.4494060376503764, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 18}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:39:28,866] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.7826838968834279, 'learning_rate': 0.05896551467608257, 'dropout_rate': 0.8191461437766966, 'n_estimators': 243, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5623558961067616, 'min_weight_fraction_leaf': 0.08382061902052879, 'max_features': 'sqrt', 'min_impurity_decrease': 4.1472189799877446e-05, 'validation_fraction': 0.41347794055506315, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 17}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 19:39:39,223] Trial 91 finished with value: 0.6255130467702362 and parameters: {'subsample': 0.6462754738201302, 'learning_rate': 0.06264501502966024, 'dropout_rate': 0.9319534079828476, 'n_estimators': 185, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03883743352167904, 'min_weight_fraction_leaf': 0.13749220517380364, 'max_features': 'sqrt', 'min_impurity_decrease': 0.005176333365456589, 'validation_fraction': 0.43321725508522685, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:39:49,459] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.6245017598838927, 'learning_rate': 0.05223313925328833, 'dropout_rate': 0.972634493352539, 'n_estimators': 227, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2023055537951245, 'min_weight_fraction_leaf': 0.18224603324116453, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0038742072375087468, 'validation_fraction': 0.38467146650840556, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:40:00,884] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.6900934408197936, 'learning_rate': 0.06130707063718977, 'dropout_rate': 0.9315558205441057, 'n_estimators': 190, 'criterion': 'friedman_mse', 'ccp_alpha': 1.658876974248122, 'min_weight_fraction_leaf': 0.15652737127126845, 'max_features': 'sqrt', 'min_impurity_decrease': 0.010222009375471406, 'validation_fraction': 0.2781040159577803, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:40:15,230] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.6731843823366407, 'learning_rate': 0.056330107387120805, 'dropout_rate': 0.8985134268506789, 'n_estimators': 201, 'criterion': 'friedman_mse', 'ccp_alpha': 0.44319051819946925, 'min_weight_fraction_leaf': 0.19853554103226972, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0022623785454057447, 'validation_fraction': 0.48383661408092105, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:40:24,158] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.5605205244965837, 'learning_rate': 0.0750903815895453, 'dropout_rate': 0.8778024671921699, 'n_estimators': 170, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0383824634688337, 'min_weight_fraction_leaf': 0.12503016203804573, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0010575758528701183, 'validation_fraction': 0.31351905096003563, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:40:33,797] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.5095341352345704, 'learning_rate': 0.06691503490509686, 'dropout_rate': 0.7690425263859633, 'n_estimators': 104, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2101208988154396, 'min_weight_fraction_leaf': 0.1787335747215643, 'max_features': 'log2', 'min_impurity_decrease': 0.004228349042929313, 'validation_fraction': 0.4261490270758175, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:40:39,121] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.5910644784028829, 'learning_rate': 0.0879596097935973, 'dropout_rate': 0.8479620532477699, 'n_estimators': 122, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6358453463243561, 'min_weight_fraction_leaf': 0.14358733901983556, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0078050368440759086, 'validation_fraction': 0.517743317659864, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 13}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:40:43,940] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.608684505499584, 'learning_rate': 0.060407014521304134, 'dropout_rate': 0.9396028513209457, 'n_estimators': 143, 'criterion': 'friedman_mse', 'ccp_alpha': 4.816291450322713, 'min_weight_fraction_leaf': 0.16478820889905052, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0002856747999232316, 'validation_fraction': 0.3507522608515191, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.6366905799047093.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6361702127659574

Fold 4 C-index: 0.6901140684410646

[I 2024-04-13 19:40:49,139] A new study created in memory with name: no-name-cd84c24d-4a40-4af4-92b7-7392bffc3d54

Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 19:40:49,051] Trial 99 finished with value: 0.6255130467702362 and parameters: {'subsample': 0.6253019866669791, 'learning_rate': 0.06557979031750596, 'dropout_rate': 0.9813586516936328, 'n_estimators': 154, 'criterion': 'friedman_mse', 'ccp_alpha': 0.0043889365132810075, 'min_weight_fraction_leaf': 0.09609004964664367, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0001273994901202443, 'validation_fraction': 0.3989276425568442, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 12}. Best is trial 22 with value: 0.6366905799047093.


* Best trial for C-index:
 FrozenTrial(number=22, state=TrialState.COMPLETE, values=[0.6366905799047093], datetime_start=datetime.datetime(2024, 4, 13, 18, 42, 20, 536558), datetime_complete=datetime.datetime(2024, 4, 13, 18, 44, 48, 450531), params={'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=22, value=None)


* Best Score for C-index:
 0.6366905799047093

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:41:52,243] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:59:27,936] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:59:48,097] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:11:42,491] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:11:56,597] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:12:00,886] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:12:42,442] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:12:54,966] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:12:56,683] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24690923469557213
Fold 2 IBS: 0.23182238905217495
Fold 3 IBS: 0.2285987001735128
Fold 4 IBS: 0.2418504619353947
Fold 5 IBS: 0.22912536619668747
[I 2024-04-13 20:14:58,805] Trial 9 finished with value: 0.2356612304106684 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24712823654556054
Fold 2 IBS: 0.23202162954629
Fold 3 IBS: 0.2289556964425975
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293716647928885
[I 2024-04-13 20:17:44,064] Trial 10 finished with value: 0.23589039975732154 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:21:03,735] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24718195196902024
Fold 2 IBS: 0.23200446795592708
Fold 3 IBS: 0.22891569844215137
Fold 4 IBS: 0.24196654798277129
Fold 5 IBS: 0.22934988593028413
[I 2024-04-13 20:23:51,266] Trial 12 finished with value: 0.23588371045603082 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:25:14,682] Trial 13 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:27:12,838] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:29:09,076] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:30:22,250] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:32:58,694] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:36:42,916] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:36:54,631] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:38:27,907] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:41:19,090] Trial 21 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24702512382365985
Fold 2 IBS: 0.23198508661941047

Fold 3 IBS: 0.22897914247716272
Fold 4 IBS: 0.24195497018980475
Fold 5 IBS: 0.22901705337186837
[I 2024-04-13 20:43:38,657] Trial 22 finished with value: 0.2357922752963812 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:45:33,331] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-13 20:47:11,487] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:48:13,699] Trial 25 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:50:19,351] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:52:43,620] Trial 27 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:54:31,404] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:55:49,156] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:57:22,141] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:00:02,617] Trial 31 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:02:31,030] Trial 32 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:04:19,423] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:06:42,197] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:07:10,452] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:09:21,157] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:09:24,961] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:10:11,260] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:11:24,956] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:13:27,608] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:13:28,142] Trial 41 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7314932964129175, 'learning_rate': 0.06126836199228298, 'dropout_rate': 0.6009623836467423, 'n_estimators': 1, 'criterion': 'friedman_mse', 'ccp_alpha': 6.422443003379805, 'min_weight_fraction_leaf': 0.14099100597772682, 'max_features': None, 'min_impurity_decrease': 1.882542748267277e-07, 'validation_fraction': 0.6170272320913348, 'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 16}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:14:09,448] Trial 42 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8635261303914503, 'learning_rate': 0.06727114513082214, 'dropout_rate': 0.7366139728168559, 'n_estimators': 395, 'criterion': 'friedman_mse', 'ccp_alpha': 8.230119285920345, 'min_weight_fraction_leaf': 0.06117153911000457, 'max_features': None, 'min_impurity_decrease': 1.0163404021987342e-07, 'validation_fraction': 0.5892719805211213, 'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 12}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:14:30,742] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5917837324222421, 'learning_rate': 0.07677639470486043, 'dropout_rate': 0.6540407298297898, 'n_estimators': 267, 'criterion': 'friedman_mse', 'ccp_alpha': 7.999755841792516, 'min_weight_fraction_leaf': 0.1234177143796907, 'max_features': None, 'min_impurity_decrease': 2.6950765707390887e-07, 'validation_fraction': 0.6834480664638882, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 15}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113

Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:15:04,304] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5628832155203615, 'learning_rate': 0.05692286295358468, 'dropout_rate': 0.683156188511181, 'n_estimators': 343, 'criterion': 'friedman_mse', 'ccp_alpha': 9.07255185322531, 'min_weight_fraction_leaf': 0.21518215373385774, 'max_features': None, 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.8420815814864784, 'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:15:14,446] Trial 45 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9436582561003044, 'learning_rate': 0.07482848784358435, 'dropout_rate': 0.8595747969120033, 'n_estimators': 234, 'criterion': 'friedman_mse', 'ccp_alpha': 6.651892060576439, 'min_weight_fraction_leaf': 0.2683040344709196, 'max_features': 0.1, 'min_impurity_decrease': 1.0869564056313473e-06, 'validation_fraction': 0.24169365303117274, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 17}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:16:15,826] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7926386339965603, 'learning_rate': 0.04494919809887656, 'dropout_rate': 0.5508151660317097, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 7.689336580765509, 'min_weight_fraction_leaf': 0.45989566737272536, 'max_features': 'log2', 'min_impurity_decrease': 2.6697065515373604e-06, 'validation_fraction': 0.8846679916016404, 'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:18:04,551] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.014896067061395554, 'dropout_rate': 0.2633018587468259, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 7.181314443016622, 'min_weight_fraction_leaf': 0.03913915278835507, 'max_features': 'auto', 'min_impurity_decrease': 0.005232582706920709, 'validation_fraction': 0.7147730789425082, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 1}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:20:46,135] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8377698389118777, 'learning_rate': 0.06226660070906978, 'dropout_rate': 0.1056182843660703, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 0.44229350847698845, 'min_weight_fraction_leaf': 0.1633521636265725, 'max_features': 'sqrt', 'min_impurity_decrease': 3.9197624656370194e-07, 'validation_fraction': 0.4430754961687528, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:20:56,780] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6565892800933851, 'learning_rate': 0.04926496948677629, 'dropout_rate': 0.9570755199206264, 'n_estimators': 292, 'criterion': 'squared_error', 'ccp_alpha': 1.222549263924274, 'min_weight_fraction_leaf': 0.3785998785229164, 'max_features': 'auto', 'min_impurity_decrease': 1.743578448308132e-07, 'validation_fraction': 0.5611863747613905, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 8}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:21:27,243] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9666694740311942, 'learning_rate': 0.007024381419952416, 'dropout_rate': 0.8273591432253491, 'n_estimators': 396, 'criterion': 'friedman_mse', 'ccp_alpha': 5.806875798658877, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'auto', 'min_impurity_decrease': 1.8152678988271224e-06, 'validation_fraction': 0.9568242099019991, 'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2356612304106684.
Fold 1 IBS: 0.2441832785441588
Fold 2 IBS: 0.22959853104297975
Fold 3 IBS: 0.22452342307022877
Fold 4 IBS: 0.23799411429644288
Fold 5 IBS: 0.22598049548305768
[I 2024-04-13 21:22:38,780] Trial 51 finished with value: 0.23245596848737357 and parameters: {'subsample': 0.7104684936493832, 'learning_rate': 0.04239876363366693, 'dropout_rate': 0.2080402615060769, 'n_estimators': 324, 'criterion': 'friedman_mse', 'ccp_alpha': 0.012687949334646564, 'min_weight_fraction_leaf': 0.34409642600595886, 'max_features': None, 'min_impurity_decrease': 0.00011584908890219409, 'validation_fraction': 0.7396320573342624, 'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 51 with value: 0.23245596848737357.
Fold 1 IBS: 0.24465267938306104
Fold 2 IBS: 0.2300839346861558
Fold 3 IBS: 0.2254150879382416
Fold 4 IBS: 0.23959190294516122
Fold 5 IBS: 0.2267627237800045
[I 2024-04-13 21:23:59,020] Trial 52 finished with value: 0.23330126574652485 and parameters: {'subsample': 0.7282332832430487, 'learning_rate': 0.041065306650715123, 'dropout_rate': 0.22493298448196636, 'n_estimators': 360, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03660969414009822, 'min_weight_fraction_leaf': 0.3328853390951717, 'max_features': None, 'min_impurity_decrease': 8.730593060447977e-05, 'validation_fraction': 0.511315939537615, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 51 with value: 0.23245596848737357.
Fold 1 IBS: 0.24409383011392588
Fold 2 IBS: 0.22985559763226046
Fold 3 IBS: 0.22492651034581543
Fold 4 IBS: 0.2383736851389709
Fold 5 IBS: 0.2263186092615892
[I 2024-04-13 21:25:15,648] Trial 53 finished with value: 0.23271364649851237 and parameters: {'subsample': 0.9058299105076961, 'learning_rate': 0.03856444601466266, 'dropout_rate': 0.21174088432309426, 'n_estimators': 365, 'criterion': 'friedman_mse', 'ccp_alpha': 0.009687416363929249, 'min_weight_fraction_leaf': 0.3350876304644993, 'max_features': None, 'min_impurity_decrease': 0.00017141043064387303, 'validation_fraction': 0.6597345864306108, 'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 51 with value: 0.23245596848737357.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:26:29,941] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7201717463783591, 'learning_rate': 0.041930127592932714, 'dropout_rate': 0.24101103069538096, 'n_estimators': 374, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4353555437174279, 'min_weight_fraction_leaf': 0.33394996198154614, 'max_features': None, 'min_impurity_decrease': 0.0001787497964946924, 'validation_fraction': 0.6617398896293162, 'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 51 with value: 0.23245596848737357.
Fold 1 IBS: 0.2450814535846959
Fold 2 IBS: 0.23028445900367908
Fold 3 IBS: 0.22591210927558555
Fold 4 IBS: 0.23993584814719002
Fold 5 IBS: 0.22706252921508846
[I 2024-04-13 21:27:41,995] Trial 55 finished with value: 0.2336552798452478 and parameters: {'subsample': 0.5887322566034815, 'learning_rate': 0.03248154248395621, 'dropout_rate': 0.20419816136861105, 'n_estimators': 357, 'criterion': 'friedman_mse', 'ccp_alpha': 0.036799960796019306, 'min_weight_fraction_leaf': 0.30861253825639257, 'max_features': None, 'min_impurity_decrease': 0.0005802162560770055, 'validation_fraction': 0.4978860670989092, 'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 13}. Best is trial 51 with value: 0.23245596848737357.

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:29:05,913] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.48190513355031883, 'learning_rate': 0.030884976740502446, 'dropout_rate': 0.19804020971050568, 'n_estimators': 358, 'criterion': 'friedman_mse', 'ccp_alpha': 1.843725001532687, 'min_weight_fraction_leaf': 0.3039444677981973, 'max_features': None, 'min_impurity_decrease': 0.0014301881576558163, 'validation_fraction': 0.5010775717552909, 'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 13}. Best is trial 51 with value: 0.23245596848737357.
Fold 1 IBS: 0.24492508105172847
Fold 2 IBS: 0.23019092753434325
Fold 3 IBS: 0.22573510086260665
Fold 4 IBS: 0.2391183990980785
Fold 5 IBS: 0.22690712026893198
[I 2024-04-13 21:30:03,557] Trial 57 finished with value: 0.23337532576313777 and parameters: {'subsample': 0.5929773161110014, 'learning_rate': 0.04128024006165322, 'dropout_rate': 0.27816840703775114, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 0.001958444069204389, 'min_weight_fraction_leaf': 0.3388560781293413, 'max_features': None, 'min_impurity_decrease': 0.00034774045403606013, 'validation_fraction': 0.37272081704418564, 'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 11}. Best is trial 51 with value: 0.23245596848737357.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:30:55,573] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5814163971605758, 'learning_rate': 0.03967356155524602, 'dropout_rate': 0.37053124106539015, 'n_estimators': 326, 'criterion': 'friedman_mse', 'ccp_alpha': 1.1290458552711713, 'min_weight_fraction_leaf': 0.33818487614204046, 'max_features': None, 'min_impurity_decrease': 0.0004319270103990114, 'validation_fraction': 0.38233654755589974, 'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 11}. Best is trial 51 with value: 0.23245596848737357.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:31:28,081] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.630241053567805, 'learning_rate': 0.033612247565387714, 'dropout_rate': 0.29046802884345424, 'n_estimators': 245, 'criterion': 'friedman_mse', 'ccp_alpha': 1.509647377699394, 'min_weight_fraction_leaf': 0.3051539123714827, 'max_features': None, 'min_impurity_decrease': 0.00010781319545209248, 'validation_fraction': 0.4724196718141148, 'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 13}. Best is trial 51 with value: 0.23245596848737357.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:32:03,239] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5252504918131944, 'learning_rate': 0.053047621189064184, 'dropout_rate': 0.4438561248393662, 'n_estimators': 284, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7898775223638228, 'min_weight_fraction_leaf': 0.26588730244254855, 'max_features': None, 'min_impurity_decrease': 0.0029449800740360805, 'validation_fraction': 0.5487455955256682, 'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 10}. Best is trial 51 with value: 0.23245596848737357.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:33:05,615] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6829213185685771, 'learning_rate': 0.0405326971879444, 'dropout_rate': 0.22285780967302807, 'n_estimators': 316, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3409580267399826, 'min_weight_fraction_leaf': 0.35983027921962374, 'max_features': None, 'min_impurity_decrease': 0.00029844012701594943, 'validation_fraction': 0.3497508740827745, 'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 51 with value: 0.23245596848737357.
Fold 1 IBS: 0.24403672417888006
Fold 2 IBS: 0.2299051384034548
Fold 3 IBS: 0.22636337051192545
Fold 4 IBS: 0.23895198108324023
Fold 5 IBS: 0.22541977460172705
[I 2024-04-13 21:34:14,084] Trial 62 finished with value: 0.23293539775584554 and parameters: {'subsample': 0.4499665729841832, 'learning_rate': 0.04965052762201275, 'dropout_rate': 0.14531613306580554, 'n_estimators': 355, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022760178955567784, 'min_weight_fraction_leaf': 0.4112920453824419, 'max_features': None, 'min_impurity_decrease': 0.0005818136783417115, 'validation_fraction': 0.27041706488261363, 'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 15}. Best is trial 51 with value: 0.23245596848737357.
Fold 1 IBS: 0.24371096343267418
Fold 2 IBS: 0.22945155594141736
Fold 3 IBS: 0.2254858381051734
Fold 4 IBS: 0.238248853988965
Fold 5 IBS: 0.2252090650138416
[I 2024-04-13 21:35:24,971] Trial 63 finished with value: 0.2324212552964143 and parameters: {'subsample': 0.38928742192747917, 'learning_rate': 0.048781242977699715, 'dropout_rate': 0.13345731559321464, 'n_estimators': 356, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017414333014397508, 'min_weight_fraction_leaf': 0.4053224848913279, 'max_features': None, 'min_impurity_decrease': 0.0005725956539451149, 'validation_fraction': 0.31265661774106646, 'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 15}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:36:39,248] Trial 64 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4200175469943458, 'learning_rate': 0.049219804091505205, 'dropout_rate': 0.1248560971179666, 'n_estimators': 355, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.38932779603337203, 'max_features': None, 'min_impurity_decrease': 0.0005490892264805161, 'validation_fraction': 0.26717204824424134, 'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 15}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24465361052671478
Fold 2 IBS: 0.22999636126712925
Fold 3 IBS: 0.22623195196948692
Fold 4 IBS: 0.2390677083280353
Fold 5 IBS: 0.2263973146972269
[I 2024-04-13 21:37:32,162] Trial 65 finished with value: 0.23326938935771863 and parameters: {'subsample': 0.30987261109709896, 'learning_rate': 0.04324945527987548, 'dropout_rate': 0.16818749325997642, 'n_estimators': 300, 'criterion': 'friedman_mse', 'ccp_alpha': 0.0027463880859729187, 'min_weight_fraction_leaf': 0.40708599810540314, 'max_features': None, 'min_impurity_decrease': 7.506341342181269e-05, 'validation_fraction': 0.1821737852195971, 'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 15}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:38:24,076] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.2962078547369203, 'learning_rate': 0.04375884603815911, 'dropout_rate': 0.17314117987651884, 'n_estimators': 300, 'criterion': 'friedman_mse', 'ccp_alpha': 0.33407834617795895, 'min_weight_fraction_leaf': 0.4095123427137558, 'max_features': None, 'min_impurity_decrease': 7.750972045939015e-05, 'validation_fraction': 0.19894041322000677, 'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 15}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:39:22,904] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3366291337803353, 'learning_rate': 0.03684138433344805, 'dropout_rate': 0.1328866027244634, 'n_estimators': 319, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0074500878262913, 'min_weight_fraction_leaf': 0.40650496560519606, 'max_features': None, 'min_impurity_decrease': 0.00018562329660606072, 'validation_fraction': 0.1720340754780943, 'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 16}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:40:05,394] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4450176007008625, 'learning_rate': 0.04784142690732847, 'dropout_rate': 0.153807672858356, 'n_estimators': 267, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2696939703383896, 'min_weight_fraction_leaf': 0.3653736992064919, 'max_features': None, 'min_impurity_decrease': 0.0014776114523938442, 'validation_fraction': 0.29258004349979183, 'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 14}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:41:01,476] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3666675234442451, 'learning_rate': 0.05248287486132479, 'dropout_rate': 0.2652812310924476, 'n_estimators': 334, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3303787719881447, 'min_weight_fraction_leaf': 0.41691378448447686, 'max_features': None, 'min_impurity_decrease': 4.603062388379122e-05, 'validation_fraction': 0.116665327527883, 'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 16}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24446188554482282
Fold 2 IBS: 0.229934680254825
Fold 3 IBS: 0.22603770905478635
Fold 4 IBS: 0.23890649403490072
Fold 5 IBS: 0.22617603082666815
[I 2024-04-13 21:42:25,868] Trial 70 finished with value: 0.23310335994320058 and parameters: {'subsample': 0.2551243661006305, 'learning_rate': 0.042698731919565254, 'dropout_rate': 0.17708030287838689, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 0.01016231791970967, 'min_weight_fraction_leaf': 0.3476974778528604, 'max_features': None, 'min_impurity_decrease': 0.00011180738606945234, 'validation_fraction': 0.17099050866103735, 'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 9}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:43:46,283] Trial 71 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.24689041847430485, 'learning_rate': 0.04358166405048827, 'dropout_rate': 0.17412851657113523, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7153384638781166, 'min_weight_fraction_leaf': 0.34762950533646686, 'max_features': None, 'min_impurity_decrease': 0.000274938253591491, 'validation_fraction': 0.17716020108176356, 'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 9}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24634817291570002
Fold 2 IBS: 0.23125042971654539
Fold 3 IBS: 0.22783263124852096
Fold 4 IBS: 0.24101785651487861
Fold 5 IBS: 0.22730807602759556
[I 2024-04-13 21:45:08,993] Trial 72 finished with value: 0.2347514332846481 and parameters: {'subsample': 0.20543845944193098, 'learning_rate': 0.03864372932977664, 'dropout_rate': 0.11840222611587381, 'n_estimators': 366, 'criterion': 'friedman_mse', 'ccp_alpha': 0.004871842257553653, 'min_weight_fraction_leaf': 0.3302762566362194, 'max_features': None, 'min_impurity_decrease': 0.00012159152288221719, 'validation_fraction': 0.08316707822664748, 'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:46:03,089] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.36362897262123617, 'learning_rate': 0.0466898869537212, 'dropout_rate': 0.23183990677770777, 'n_estimators': 309, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3526051124724592, 'min_weight_fraction_leaf': 0.3774480998404598, 'max_features': None, 'min_impurity_decrease': 2.136697551209761e-05, 'validation_fraction': 0.21036268881006748, 'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 9}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:46:47,387] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.14287575456369844, 'learning_rate': 0.05758410298075975, 'dropout_rate': 0.18642839189095065, 'n_estimators': 280, 'criterion': 'friedman_mse', 'ccp_alpha': 0.945997306146382, 'min_weight_fraction_leaf': 0.44492960801904347, 'max_features': None, 'min_impurity_decrease': 7.574310223848395e-05, 'validation_fraction': 0.3180065806138139, 'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 11}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:47:55,536] Trial 75 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.2612827980842807, 'learning_rate': 0.050583492379628156, 'dropout_rate': 0.15887572212300521, 'n_estimators': 350, 'criterion': 'friedman_mse', 'ccp_alpha': 0.660060295863499, 'min_weight_fraction_leaf': 0.39673327474406117, 'max_features': None, 'min_impurity_decrease': 0.0002150512046112236, 'validation_fraction': 0.14959683881099872, 'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 17}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:49:04,235] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.31603749132267567, 'learning_rate': 0.042976963949622915, 'dropout_rate': 0.3128927296402447, 'n_estimators': 373, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3041177671849155, 'min_weight_fraction_leaf': 0.42154005341926515, 'max_features': None, 'min_impurity_decrease': 0.0010300158338537816, 'validation_fraction': 0.3980505214516428, 'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 14}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:50:03,178] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4154623638615923, 'learning_rate': 0.035777132641457245, 'dropout_rate': 0.1349241219856284, 'n_estimators': 327, 'criterion': 'friedman_mse', 'ccp_alpha': 2.2297958017051442, 'min_weight_fraction_leaf': 0.3448011819631375, 'max_features': 1, 'min_impurity_decrease': 0.00012102044847110188, 'validation_fraction': 0.2825377749559769, 'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 13, 'max_depth': 8}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:50:56,684] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38353946327089455, 'learning_rate': 0.04627201780375246, 'dropout_rate': 0.10185034849810722, 'n_estimators': 296, 'criterion': 'friedman_mse', 'ccp_alpha': 1.4077536708792413, 'min_weight_fraction_leaf': 0.37826406364062987, 'max_features': None, 'min_impurity_decrease': 4.870590304744988e-05, 'validation_fraction': 0.3211844074125865, 'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 10}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24551697513707202
Fold 2 IBS: 0.2303259588455767
Fold 3 IBS: 0.22662101843621418
Fold 4 IBS: 0.2394168423767029
Fold 5 IBS: 0.22718986074333442
[I 2024-04-13 22:03:56,331] Trial 79 finished with value: 0.23381413110778007 and parameters: {'subsample': 0.4449351033565357, 'learning_rate': 0.05447197006738063, 'dropout_rate': 0.23794160839522802, 'n_estimators': 390, 'criterion': 'friedman_mse', 'ccp_alpha': 0.005852023084282856, 'min_weight_fraction_leaf': 0.2890173575842872, 'max_features': 0.1, 'min_impurity_decrease': 0.0003555696904571874, 'validation_fraction': 0.26443832286557944, 'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 22:04:12,238] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.20383502291319894, 'learning_rate': 0.02780706859206665, 'dropout_rate': 0.27983087398596906, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 1.6916863016677515, 'min_weight_fraction_leaf': 0.47859231517906975, 'max_features': 'log2', 'min_impurity_decrease': 1.8445702497046605e-05, 'validation_fraction': 0.344978836338552, 'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 20}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24722689818509755
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 22:08:23,406] Trial 81 finished with value: 0.23592380306003227 and parameters: {'subsample': 0.5379584715419702, 'learning_rate': 0.034527554656602295, 'dropout_rate': 0.21050195368089006, 'n_estimators': 351, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2262605763493303, 'min_weight_fraction_leaf': 0.31238542278030906, 'max_features': None, 'min_impurity_decrease': 0.0020367175616912664, 'validation_fraction': 0.22899050862315146, 'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 13}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.2458304708692943
Fold 2 IBS: 0.23075200195351697
Fold 3 IBS: 0.22700648039937887
Fold 4 IBS: 0.24055952170010625
Fold 5 IBS: 0.22735488116274
[I 2024-04-13 22:10:55,039] Trial 82 finished with value: 0.23430067121700726 and parameters: {'subsample': 0.24189405617649756, 'learning_rate': 0.03164839631111216, 'dropout_rate': 0.19574946831489617, 'n_estimators': 368, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017869100661901054, 'min_weight_fraction_leaf': 0.3191559012930328, 'max_features': None, 'min_impurity_decrease': 0.0006327281949208176, 'validation_fraction': 0.3822451504972247, 'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 22:11:36,141] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.49331792217893045, 'learning_rate': 0.04073930152300266, 'dropout_rate': 0.17030068647533225, 'n_estimators': 341, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6352987263197191, 'min_weight_fraction_leaf': 0.3594715721681696, 'max_features': None, 'min_impurity_decrease': 0.0004856971946332966, 'validation_fraction': 0.09216929322181575, 'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 15}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 22:13:16,509] Trial 84 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6180141688948121, 'learning_rate': 0.038324998483237754, 'dropout_rate': 0.20730035105493883, 'n_estimators': 405, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5471380822999251, 'min_weight_fraction_leaf': 0.3001738075255795, 'max_features': None, 'min_impurity_decrease': 0.00014004892507513448, 'validation_fraction': 0.04405670567880415, 'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 22:19:12,012] Trial 85 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5700906311498587, 'learning_rate': 0.0513614266599738, 'dropout_rate': 0.14643147801614054, 'n_estimators': 312, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9174104874385317, 'min_weight_fraction_leaf': 0.3423886587364037, 'max_features': None, 'min_impurity_decrease': 8.058773072616773e-05, 'validation_fraction': 0.43111617135843205, 'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 13}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22894153584247162
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 22:19:36,968] Trial 86 finished with value: 0.23591977706686965 and parameters: {'subsample': 0.33984072464441006, 'learning_rate': 0.03312668547451033, 'dropout_rate': 0.18213730145860418, 'n_estimators': 252, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2306612709254075, 'min_weight_fraction_leaf': 0.3266097794825797, 'max_features': 'sqrt', 'min_impurity_decrease': 3.321369243251985e-05, 'validation_fraction': 0.15270296676384593, 'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 22:20:53,619] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7413587764330115, 'learning_rate': 0.045095802930980394, 'dropout_rate': 0.2560729134591171, 'n_estimators': 419, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8929682317237783, 'min_weight_fraction_leaf': 0.3727689822353215, 'max_features': None, 'min_impurity_decrease': 0.0002400099639669012, 'validation_fraction': 0.46923180557229993, 'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 22:21:42,186] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7764947091272626, 'learning_rate': 0.024999884978950046, 'dropout_rate': 0.12510026440333066, 'n_estimators': 378, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5015287062120017, 'min_weight_fraction_leaf': 0.38816104284678477, 'max_features': None, 'min_impurity_decrease': 0.0010655641565921175, 'validation_fraction': 0.7362458905800392, 'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 11}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.2447908773407523
Fold 2 IBS: 0.22981720276762455
Fold 3 IBS: 0.22555047669038344

Fold 4 IBS: 0.23880006092678727
Fold 5 IBS: 0.22633462320742237
[I 2024-04-13 22:22:39,095] Trial 89 finished with value: 0.233058648186594 and parameters: {'subsample': 0.2799652441361268, 'learning_rate': 0.041598274959482893, 'dropout_rate': 0.21483185460780047, 'n_estimators': 350, 'criterion': 'friedman_mse', 'ccp_alpha': 0.019001072018239806, 'min_weight_fraction_leaf': 0.27872060184788355, 'max_features': None, 'min_impurity_decrease': 0.01806689386438656, 'validation_fraction': 0.5765746087299453, 'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 15}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 22:23:15,120] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3053150575440778, 'learning_rate': 0.041388830250024856, 'dropout_rate': 0.22636227135917808, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 4.2585705811284145, 'min_weight_fraction_leaf': 0.24750178915181942, 'max_features': 1, 'min_impurity_decrease': 0.025274592411577392, 'validation_fraction': 0.6339447015601792, 'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 15}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24706523546154605
Fold 2 IBS: 0.23193218368090493
Fold 3 IBS: 0.2288616104314252
Fold 4 IBS: 0.24190221791173394
Fold 5 IBS: 0.22935997262885255
[I 2024-04-13 22:24:07,976] Trial 91 finished with value: 0.2358242440228925 and parameters: {'subsample': 0.26619549982524504, 'learning_rate': 0.048102060289746965, 'dropout_rate': 0.2522424316463819, 'n_estimators': 355, 'criterion': 'friedman_mse', 'ccp_alpha': 0.21474387868829267, 'min_weight_fraction_leaf': 0.27937702899018346, 'max_features': None, 'min_impurity_decrease': 0.08577320044011032, 'validation_fraction': 0.5842085976616191, 'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 14}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24607047920103023
Fold 2 IBS: 0.23112294075059506
Fold 3 IBS: 0.227760852661791
Fold 4 IBS: 0.2407171081968645
Fold 5 IBS: 0.2275990495400623
[I 2024-04-13 22:40:16,494] Trial 92 finished with value: 0.23465408607006863 and parameters: {'subsample': 0.22075145299324112, 'learning_rate': 0.036887428058422954, 'dropout_rate': 0.1531280655999614, 'n_estimators': 362, 'criterion': 'friedman_mse', 'ccp_alpha': 0.04688040088867627, 'min_weight_fraction_leaf': 0.30961511636905925, 'max_features': None, 'min_impurity_decrease': 0.02787067945956367, 'validation_fraction': 0.5048541650731201, 'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 22:56:01,974] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.16094848371903808, 'learning_rate': 0.04227885526043482, 'dropout_rate': 0.20880693024495112, 'n_estimators': 344, 'criterion': 'friedman_mse', 'ccp_alpha': 0.524885830873201, 'min_weight_fraction_leaf': 0.32684137984745537, 'max_features': None, 'min_impurity_decrease': 0.010232842586686604, 'validation_fraction': 0.6754312720048001, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 16}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 23:06:24,618] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5134438904191061, 'learning_rate': 0.03822796411772697, 'dropout_rate': 0.3453048757566427, 'n_estimators': 384, 'criterion': 'friedman_mse', 'ccp_alpha': 3.8282410742130915, 'min_weight_fraction_leaf': 0.2962261021501572, 'max_features': None, 'min_impurity_decrease': 0.05716954715745521, 'validation_fraction': 0.5255511336808235, 'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 15}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 23:07:20,117] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5954864607420102, 'learning_rate': 0.055160621849637936, 'dropout_rate': 0.27196662325754906, 'n_estimators': 333, 'criterion': 'friedman_mse', 'ccp_alpha': 1.1613761648258012, 'min_weight_fraction_leaf': 0.35026970416267483, 'max_features': None, 'min_impurity_decrease': 0.0003736471212282148, 'validation_fraction': 0.7021251312388388, 'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24723204829173134
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 23:31:39,125] Trial 96 finished with value: 0.23592483308135898 and parameters: {'subsample': 0.5510219457804204, 'learning_rate': 0.029243702660761338, 'dropout_rate': 0.19617884294815183, 'n_estimators': 399, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2324820197458385, 'min_weight_fraction_leaf': 0.40136990286172886, 'max_features': 'log2', 'min_impurity_decrease': 0.0007034420703111356, 'validation_fraction': 0.5713168788990091, 'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 18}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 23:32:08,676] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.28192957557396703, 'learning_rate': 0.045046312468018934, 'dropout_rate': 0.16839562480195472, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8105966033923179, 'min_weight_fraction_leaf': 0.43814533313895254, 'max_features': 0.1, 'min_impurity_decrease': 1.4215110944250721e-05, 'validation_fraction': 0.6261759888458043, 'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 13, 'max_depth': 14}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 23:32:34,820] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4601934339044744, 'learning_rate': 0.04987160544275287, 'dropout_rate': 0.24112756672861368, 'n_estimators': 286, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5270101568996688, 'min_weight_fraction_leaf': 0.3579416265643403, 'max_features': None, 'min_impurity_decrease': 6.090845173254468e-05, 'validation_fraction': 0.5403544212495923, 'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 11}. Best is trial 63 with value: 0.2324212552964143.
Fold 1 IBS: 0.24477031403936528
Fold 2 IBS: 0.22978448760731757
Fold 3 IBS: 0.22522763519849992
Fold 4 IBS: 0.23833858164774593
Fold 5 IBS: 0.22629005756964554
[I 2024-04-13 23:33:11,724] Trial 99 finished with value: 0.23288221521251487 and parameters: {'subsample': 0.6473842724309151, 'learning_rate': 0.06087517452189459, 'dropout_rate': 0.33045873392194897, 'n_estimators': 360, 'criterion': 'friedman_mse', 'ccp_alpha': 0.0043895707088205125, 'min_weight_fraction_leaf': 0.2732581278903203, 'max_features': None, 'min_impurity_decrease': 0.00015837847703956763, 'validation_fraction': 0.47783011710610246, 'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 63 with value: 0.2324212552964143.


* Best trial for IBS:
 FrozenTrial(number=63, state=TrialState.COMPLETE, values=[0.2324212552964143], datetime_start=datetime.datetime(2024, 4, 13, 21, 34, 14, 93371), datetime_complete=datetime.datetime(2024, 4, 13, 21, 35, 24, 970313), params={'subsample': 0.38928742192747917, 'learning_rate': 0.048781242977699715, 'dropout_rate': 0.13345731559321464, 'n_estimators': 356, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017414333014397508, 'min_weight_fraction_leaf': 0.4053224848913279, 'max_features': None, 'min_impurity_decrease': 0.0005725956539451149, 'validation_fraction': 0.31265661774106646, 'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 15}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=63, value=None)


* Best Score for IBS:
 0.2324212552964143

In [60]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [61]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.637
train_ibs:  0.232

#### Test

In [62]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [63]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.0339977959383996,
                                 criterion='squared_error',
                                 dropout_rate=0.2075412325353082,
                                 learning_rate=0.010706280861824496,
                                 max_features='auto', max_leaf_nodes=17,
                                 min_impurity_decrease=3.3602815261835675e-07,
                                 min_samples_leaf=13, min_samples_split=18,
                                 min_weight_fraction_leaf=0.4472167339801619,
                                 n_estimators=445, random_state=123,
                                 subsample=0.9030031356045858,
                                 validation_fraction=0.9350158433232643)

C-index score: 0.598

GradientBoostingSurvivalAnalysis(ccp_alpha=0.017414333014397508,
                                 dropout_rate=0.13345731559321464,
                                 learning_rate=0.048781242977699715,
                                 max_depth=15, max_leaf_nodes=3,
                                 min_impurity_decrease=0.0005725956539451149,
                                 min_samples_leaf=9,
                                 min_weight_fraction_leaf=0.4053224848913279,
                                 n_estimators=356, random_state=123,
                                 subsample=0.38928742192747917,
                                 validation_fraction=0.31265661774106646)

IBS: 0.225

In [64]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [65]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:33:36,401] A new study created in memory with name: no-name-779cef0b-e214-4e85-882e-5d4f63cbf3fc

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:33:37,576] Trial 0 finished with value: 0.5707331394084487 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.5707331394084487.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:33:48,399] Trial 1 finished with value: 0.6251284857796179 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.6251284857796179.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:33:50,111] Trial 2 finished with value: 0.6204832369875521 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 1 with value: 0.6251284857796179.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:33:52,534] Trial 3 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.6431476182223032.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:33:56,537] Trial 4 finished with value: 0.635614253582005 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 3 with value: 0.6431476182223032.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:34:04,051] Trial 5 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 3 with value: 0.6431476182223032.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:34:08,995] Trial 6 finished with value: 0.5996304778114905 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 3 with value: 0.6431476182223032.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:34:09,972] Trial 7 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 3 with value: 0.6431476182223032.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:34:13,211] Trial 8 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:34:26,956] Trial 9 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:34:31,462] Trial 10 finished with value: 0.5707331394084487 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.6778199652121663, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 23:34:34,319] Trial 11 finished with value: 0.6400441700740036 and parameters: {'subsample': 0.17655470263317158, 'dropout_rate': 0.10580803679784617, 'n_estimators': 204, 'learning_rate': 0.09608989358701946}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:34:41,849] Trial 12 finished with value: 0.6363747098557692 and parameters: {'subsample': 0.39986209847733967, 'dropout_rate': 0.10700980007959371, 'n_estimators': 355, 'learning_rate': 0.02877877178380152}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:34:42,213] Trial 13 finished with value: 0.5788182457914274 and parameters: {'subsample': 0.594643030037878, 'dropout_rate': 0.6099528852471552, 'n_estimators': 15, 'learning_rate': 0.0892647381229508}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:34:43,215] Trial 14 finished with value: 0.6363747098557692 and parameters: {'subsample': 0.3726679355750928, 'dropout_rate': 0.7689021030636845, 'n_estimators': 107, 'learning_rate': 0.03282776599169483}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 23:34:47,544] Trial 15 finished with value: 0.6400441700740036 and parameters: {'subsample': 0.10947320270339439, 'dropout_rate': 0.242092283972966, 'n_estimators': 230, 'learning_rate': 0.08023901493015002}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:34:52,028] Trial 16 finished with value: 0.5707331394084487 and parameters: {'subsample': 0.8632868473778619, 'dropout_rate': 0.9733961081825167, 'n_estimators': 331, 'learning_rate': 0.013069354206479845}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:34:53,840] Trial 17 finished with value: 0.6272561453540859 and parameters: {'subsample': 0.4556692711704965, 'dropout_rate': 0.23930666550173862, 'n_estimators': 127, 'learning_rate': 0.041730425770475255}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:03,563] Trial 18 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.601630412385837, 'dropout_rate': 0.5512790465731392, 'n_estimators': 427, 'learning_rate': 0.08290595444475028}. Best is trial 8 with value: 0.6491050650308138.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:07,916] Trial 19 finished with value: 0.6363747098557692 and parameters: {'subsample': 0.2686289669767903, 'dropout_rate': 0.3156718779160812, 'n_estimators': 285, 'learning_rate': 0.018369564224062086}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:10,363] Trial 20 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.28937249949982, 'dropout_rate': 0.7859448591953863, 'n_estimators': 233, 'learning_rate': 0.03672900617406294}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:10,525] Trial 21 finished with value: 0.6077155841944692 and parameters: {'subsample': 0.3639181650802924, 'dropout_rate': 0.6772408952174084, 'n_estimators': 12, 'learning_rate': 0.04252080121155724}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:11,055] Trial 22 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.5149122937090506, 'dropout_rate': 0.601617279441232, 'n_estimators': 66, 'learning_rate': 0.06423372451420546}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:11,512] Trial 23 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.4275507217783913, 'dropout_rate': 0.7215772163704696, 'n_estimators': 62, 'learning_rate': 0.04186582141545488}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:12,981] Trial 24 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.4566463648207183, 'dropout_rate': 0.7652919670925054, 'n_estimators': 151, 'learning_rate': 0.005884276359196396}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:13,703] Trial 25 finished with value: 0.6017581373859585 and parameters: {'subsample': 0.5925015817340794, 'dropout_rate': 0.44504433936564963, 'n_estimators': 83, 'learning_rate': 0.026204108503990506}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:16,575] Trial 26 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.6559444529599051, 'dropout_rate': 0.1582828699291536, 'n_estimators': 212, 'learning_rate': 0.05989417278353722}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:18,165] Trial 27 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.4394017474959951, 'dropout_rate': 0.8368873118701377, 'n_estimators': 165, 'learning_rate': 0.046259935816584434}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:19,519] Trial 28 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.3267564321862687, 'dropout_rate': 0.7291568383909645, 'n_estimators': 134, 'learning_rate': 0.03545838957871889}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:22,752] Trial 29 finished with value: 0.5962311473765761 and parameters: {'subsample': 0.8319631853959568, 'dropout_rate': 0.528113503868086, 'n_estimators': 254, 'learning_rate': 0.07315643033020765}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 23:35:23,579] Trial 30 finished with value: 0.6400441700740036 and parameters: {'subsample': 0.22248927440469807, 'dropout_rate': 0.3577780272974884, 'n_estimators': 93, 'learning_rate': 0.0544249783905717}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:24,094] Trial 31 finished with value: 0.6251284857796179 and parameters: {'subsample': 0.535323742807898, 'dropout_rate': 0.6722613761503513, 'n_estimators': 47, 'learning_rate': 0.04487728063080395}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:24,579] Trial 32 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.4068628433881887, 'dropout_rate': 0.6071613278382735, 'n_estimators': 41, 'learning_rate': 0.03833735325599645}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:25,199] Trial 33 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.4454871520496557, 'dropout_rate': 0.592239032207121, 'n_estimators': 53, 'learning_rate': 0.018821254613206193}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:25,372] Trial 34 finished with value: 0.5788182457914274 and parameters: {'subsample': 0.41106853506178415, 'dropout_rate': 0.5015077979320226, 'n_estimators': 4, 'learning_rate': 0.03454841952404757}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:28,269] Trial 35 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.5194087535769674, 'dropout_rate': 0.43975685710717877, 'n_estimators': 189, 'learning_rate': 0.0691928914987717}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:29,714] Trial 36 finished with value: 0.635614253582005 and parameters: {'subsample': 0.3124223656013892, 'dropout_rate': 0.30580364309060193, 'n_estimators': 140, 'learning_rate': 0.0578679533531951}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:30,422] Trial 37 finished with value: 0.6251284857796179 and parameters: {'subsample': 0.6717390205543079, 'dropout_rate': 0.8374055765137145, 'n_estimators': 81, 'learning_rate': 0.04898260553853576}. Best is trial 8 with value: 0.6491050650308138.

Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:30,725] Trial 38 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.5612204028878727, 'dropout_rate': 0.18449641578783965, 'n_estimators': 33, 'learning_rate': 0.02899926217525038}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:35,429] Trial 39 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.48668081608198116, 'dropout_rate': 0.40937505489688286, 'n_estimators': 309, 'learning_rate': 0.022700017751066785}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:44,052] Trial 40 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.6428532968219703, 'dropout_rate': 0.6249935701630456, 'n_estimators': 424, 'learning_rate': 0.03780302746223373}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:35:51,728] Trial 41 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.7295749266530551, 'dropout_rate': 0.7165305407252128, 'n_estimators': 413, 'learning_rate': 0.039592272388087955}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:36:02,419] Trial 42 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.6548482397413888, 'dropout_rate': 0.5630685079734132, 'n_estimators': 471, 'learning_rate': 0.05065056559629298}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:36:13,817] Trial 43 finished with value: 0.6251284857796179 and parameters: {'subsample': 0.7768572076205417, 'dropout_rate': 0.5614281957092329, 'n_estimators': 494, 'learning_rate': 0.030996179607105413}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:36:23,036] Trial 44 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.6460870792332496, 'dropout_rate': 0.6152802506070036, 'n_estimators': 463, 'learning_rate': 0.05329978319294245}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:36:31,468] Trial 45 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.7024372745211345, 'dropout_rate': 0.5142189569679463, 'n_estimators': 435, 'learning_rate': 0.03913357217798214}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:36:37,557] Trial 46 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.6185295847670816, 'dropout_rate': 0.6440432680736468, 'n_estimators': 367, 'learning_rate': 0.04870495977890464}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:36:43,751] Trial 47 finished with value: 0.6204832369875521 and parameters: {'subsample': 0.5578315215185016, 'dropout_rate': 0.4920372374286372, 'n_estimators': 380, 'learning_rate': 0.06366543830537712}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:36:52,688] Trial 48 finished with value: 0.5962311473765761 and parameters: {'subsample': 0.7976481334592018, 'dropout_rate': 0.5758773874350814, 'n_estimators': 473, 'learning_rate': 0.05060453035324914}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:36:59,170] Trial 49 finished with value: 0.6458607965168767 and parameters: {'subsample': 0.39488181545222456, 'dropout_rate': 0.6359210409003455, 'n_estimators': 391, 'learning_rate': 0.03864407021296164}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:37:06,837] Trial 50 finished with value: 0.5707331394084487 and parameters: {'subsample': 0.909123929884357, 'dropout_rate': 0.7179576394062643, 'n_estimators': 452, 'learning_rate': 0.023279967423464543}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:37:15,284] Trial 51 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.6706034446528428, 'dropout_rate': 0.6182685320681295, 'n_estimators': 472, 'learning_rate': 0.05447338758285781}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:37:23,754] Trial 52 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.6524352275411408, 'dropout_rate': 0.5301665580486874, 'n_estimators': 452, 'learning_rate': 0.04401241131920049}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:37:32,644] Trial 53 finished with value: 0.6272561453540859 and parameters: {'subsample': 0.6204606961452624, 'dropout_rate': 0.46780215836415273, 'n_estimators': 424, 'learning_rate': 0.032742321783898694}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:37:38,876] Trial 54 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.7050102269043423, 'dropout_rate': 0.6352524310451082, 'n_estimators': 399, 'learning_rate': 0.051658023292561604}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:37:43,722] Trial 55 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.5624698352149905, 'dropout_rate': 0.6958652470065004, 'n_estimators': 344, 'learning_rate': 0.04701408378460388}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:37:53,362] Trial 56 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.4863429993933853, 'dropout_rate': 0.5679702328831667, 'n_estimators': 497, 'learning_rate': 0.04167635501159456}. Best is trial 8 with value: 0.6491050650308138.

Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:38:00,991] Trial 57 finished with value: 0.6458607965168767 and parameters: {'subsample': 0.41269771991453474, 'dropout_rate': 0.6539321659179622, 'n_estimators': 454, 'learning_rate': 0.02830027760315705}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:38:12,538] Trial 58 finished with value: 0.6390878881503429 and parameters: {'subsample': 0.3615440262477045, 'dropout_rate': 0.755530540160593, 'n_estimators': 477, 'learning_rate': 0.05780911160579933}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:38:13,737] Trial 59 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.5896150646835115, 'dropout_rate': 0.5922068417469362, 'n_estimators': 114, 'learning_rate': 0.018070356982517948}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:38:14,086] Trial 60 finished with value: 0.5962311473765761 and parameters: {'subsample': 0.5068584278157959, 'dropout_rate': 0.9224216816906449, 'n_estimators': 30, 'learning_rate': 0.03723183452431825}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:38:25,091] Trial 61 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.6392706567247387, 'dropout_rate': 0.527343929202009, 'n_estimators': 443, 'learning_rate': 0.04401168668124027}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:38:36,234] Trial 62 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.7088402661678433, 'dropout_rate': 0.552143526427045, 'n_estimators': 466, 'learning_rate': 0.04219427278188604}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:38:47,579] Trial 63 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.7589498820980889, 'dropout_rate': 0.8020490821702424, 'n_estimators': 414, 'learning_rate': 0.052420722603359365}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:38:57,901] Trial 64 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.6473079994139183, 'dropout_rate': 0.6152474995585913, 'n_estimators': 453, 'learning_rate': 0.04583676048948297}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:39:02,966] Trial 65 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.6846677817489052, 'dropout_rate': 0.6879401461492454, 'n_estimators': 283, 'learning_rate': 0.03382070460852527}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:39:06,016] Trial 66 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.5918939085006366, 'dropout_rate': 0.539109702083595, 'n_estimators': 228, 'learning_rate': 0.05673379744638146}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:39:11,985] Trial 67 finished with value: 0.6363747098557692 and parameters: {'subsample': 0.4590303067651391, 'dropout_rate': 0.47857137008309014, 'n_estimators': 321, 'learning_rate': 0.040868864102181136}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:39:21,626] Trial 68 finished with value: 0.6451003402431125 and parameters: {'subsample': 0.34113543420990194, 'dropout_rate': 0.583662202262188, 'n_estimators': 405, 'learning_rate': 0.06149997621532806}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:39:24,049] Trial 69 finished with value: 0.6363747098557692 and parameters: {'subsample': 0.5435873046283142, 'dropout_rate': 0.4121656640905552, 'n_estimators': 165, 'learning_rate': 0.036220665067931965}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:39:36,114] Trial 70 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.4235353727507699, 'dropout_rate': 0.6150703832488551, 'n_estimators': 485, 'learning_rate': 0.02615065009590716}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:39:45,733] Trial 71 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.6330695390211, 'dropout_rate': 0.5302936766820593, 'n_estimators': 445, 'learning_rate': 0.04370378852042028}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:39:54,802] Trial 72 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.6423344010160772, 'dropout_rate': 0.5077344544211906, 'n_estimators': 435, 'learning_rate': 0.04832644511001666}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:40:05,850] Trial 73 finished with value: 0.6251284857796179 and parameters: {'subsample': 0.7411423065306171, 'dropout_rate': 0.4579173769551922, 'n_estimators': 462, 'learning_rate': 0.044226923174061794}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:40:06,377] Trial 74 finished with value: 0.6251284857796179 and parameters: {'subsample': 0.5795310927875241, 'dropout_rate': 0.6637054334480605, 'n_estimators': 60, 'learning_rate': 0.037392696463935504}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:40:16,169] Trial 75 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.6231091890906411, 'dropout_rate': 0.5157039561559064, 'n_estimators': 435, 'learning_rate': 0.030282630300113928}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202

Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:40:16,524] Trial 76 finished with value: 0.6251284857796179 and parameters: {'subsample': 0.6898585170694536, 'dropout_rate': 0.7481622269151432, 'n_estimators': 25, 'learning_rate': 0.04582329330895257}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:40:17,654] Trial 77 finished with value: 0.6251284857796179 and parameters: {'subsample': 0.6589290992687837, 'dropout_rate': 0.5572658176798183, 'n_estimators': 95, 'learning_rate': 0.052931151991814716}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:40:27,405] Trial 78 finished with value: 0.6363747098557692 and parameters: {'subsample': 0.46834229485114176, 'dropout_rate': 0.429631338031958, 'n_estimators': 383, 'learning_rate': 0.032202689680192964}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:40:38,217] Trial 79 finished with value: 0.6390878881503429 and parameters: {'subsample': 0.3769351471954966, 'dropout_rate': 0.6999089179072037, 'n_estimators': 485, 'learning_rate': 0.0983514933405076}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:40:39,208] Trial 80 finished with value: 0.6251284857796179 and parameters: {'subsample': 0.5281582871848369, 'dropout_rate': 0.5891367221611725, 'n_estimators': 78, 'learning_rate': 0.05031218110364598}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:40:50,371] Trial 81 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.6480642801190936, 'dropout_rate': 0.6053280458813253, 'n_estimators': 447, 'learning_rate': 0.04464769089454443}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:40:58,969] Trial 82 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.7209165270466638, 'dropout_rate': 0.6325340630503089, 'n_estimators': 416, 'learning_rate': 0.04023050667588096}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:41:10,393] Trial 83 finished with value: 0.6272561453540859 and parameters: {'subsample': 0.6086075893769479, 'dropout_rate': 0.48675681267093857, 'n_estimators': 440, 'learning_rate': 0.04378797612914602}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:41:21,646] Trial 84 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.6753877002371835, 'dropout_rate': 0.5366877004359798, 'n_estimators': 467, 'learning_rate': 0.047847545148808304}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:41:31,690] Trial 85 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.571138387225725, 'dropout_rate': 0.6589858409130451, 'n_estimators': 455, 'learning_rate': 0.034530559468632094}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:41:45,483] Trial 86 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.7652147042143009, 'dropout_rate': 0.6203852259223259, 'n_estimators': 499, 'learning_rate': 0.0599851282673949}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:41:56,426] Trial 87 finished with value: 0.5962311473765761 and parameters: {'subsample': 0.7923253229666314, 'dropout_rate': 0.5724846304903072, 'n_estimators': 424, 'learning_rate': 0.055175670187957014}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:42:08,477] Trial 88 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.6439761733246515, 'dropout_rate': 0.7975478875011615, 'n_estimators': 482, 'learning_rate': 0.04647359430999269}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:42:16,533] Trial 89 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.4401149996145284, 'dropout_rate': 0.5506051943756223, 'n_estimators': 368, 'learning_rate': 0.06775564820375699}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:42:22,080] Trial 90 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.543990022664088, 'dropout_rate': 0.7372227229262217, 'n_estimators': 259, 'learning_rate': 0.038495574809833996}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:42:26,570] Trial 91 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.5891813549261178, 'dropout_rate': 0.5338275204621425, 'n_estimators': 226, 'learning_rate': 0.05760948367516523}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:42:31,539] Trial 92 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.6183176923865654, 'dropout_rate': 0.6039701521641775, 'n_estimators': 242, 'learning_rate': 0.05016873963129125}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:42:36,633] Trial 93 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.5066180882957838, 'dropout_rate': 0.5416510497202602, 'n_estimators': 217, 'learning_rate': 0.055793792245630074}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:42:39,840] Trial 94 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.5991598497964263, 'dropout_rate': 0.5086845153494503, 'n_estimators': 187, 'learning_rate': 0.042282366872098825}. Best is trial 8 with value: 0.6491050650308138.

Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:42:46,467] Trial 95 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.6670112606224763, 'dropout_rate': 0.5751132917648296, 'n_estimators': 277, 'learning_rate': 0.05234531708437644}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:42:52,829] Trial 96 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.6930426646484223, 'dropout_rate': 0.47668030429656294, 'n_estimators': 303, 'learning_rate': 0.06413325090254297}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:43:03,749] Trial 97 finished with value: 0.6491050650308138 and parameters: {'subsample': 0.633679212064872, 'dropout_rate': 0.645505605908421, 'n_estimators': 427, 'learning_rate': 0.04017248667654109}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:43:06,921] Trial 98 finished with value: 0.6431476182223032 and parameters: {'subsample': 0.4757270854500776, 'dropout_rate': 0.6829939651805278, 'n_estimators': 202, 'learning_rate': 0.026117089776837927}. Best is trial 8 with value: 0.6491050650308138.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7110266159695817

[I 2024-04-13 23:43:20,757] A new study created in memory with name: no-name-0d5fc5f1-9ab1-49b9-8b57-0c20ad2625a4

Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 23:43:20,720] Trial 99 finished with value: 0.6332135921625967 and parameters: {'subsample': 0.7242901139385333, 'dropout_rate': 0.6220690500322777, 'n_estimators': 459, 'learning_rate': 0.05686105294349177}. Best is trial 8 with value: 0.6491050650308138.


* Best trial for C-index:
 FrozenTrial(number=8, state=TrialState.COMPLETE, values=[0.6491050650308138], datetime_start=datetime.datetime(2024, 4, 13, 23, 34, 9, 979187), datetime_complete=datetime.datetime(2024, 4, 13, 23, 34, 13, 211110), params={'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=8, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}


* Best Score for C-index:
 0.6491050650308138

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.33204135480847696
Fold 2 IBS: 0.3002240901900513
Fold 3 IBS: 0.20462334557503573
Fold 4 IBS: 0.30580587124119196
Fold 5 IBS: 0.23485452221223108
[I 2024-04-13 23:43:23,351] Trial 0 finished with value: 0.2755098368053974 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2755098368053974.
Fold 1 IBS: 0.438688717666397
Fold 2 IBS: 0.3801225465459666
Fold 3 IBS: 0.24946340121253377
Fold 4 IBS: 0.39959109056476794
Fold 5 IBS: 0.3393770219007293
[I 2024-04-13 23:43:40,313] Trial 1 finished with value: 0.3614485555780789 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2755098368053974.
Fold 1 IBS: 0.4315096337658256
Fold 2 IBS: 0.3776778541908041
Fold 3 IBS: 0.22263340421035796
Fold 4 IBS: 0.3902157350041201
Fold 5 IBS: 0.3178971275982833
[I 2024-04-13 23:43:44,248] Trial 2 finished with value: 0.3479867509538782 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2755098368053974.
Fold 1 IBS: 0.425080537090733
Fold 2 IBS: 0.37860170930815124
Fold 3 IBS: 0.22686506139273063
Fold 4 IBS: 0.38566459719779295
Fold 5 IBS: 0.295613940707801
[I 2024-04-13 23:43:48,825] Trial 3 finished with value: 0.34236516913944176 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2755098368053974.
Fold 1 IBS: 0.43185699534066735
Fold 2 IBS: 0.37913413238687227
Fold 3 IBS: 0.22192375393969796
Fold 4 IBS: 0.3880815084911554
Fold 5 IBS: 0.3190891372073374
[I 2024-04-13 23:43:55,660] Trial 4 finished with value: 0.34801710547314607 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2755098368053974.
Fold 1 IBS: 0.4386669700318796
Fold 2 IBS: 0.38011990649983673
Fold 3 IBS: 0.24438584436680064
Fold 4 IBS: 0.3994470903731338
Fold 5 IBS: 0.33926274268349155
[I 2024-04-13 23:44:16,358] Trial 5 finished with value: 0.36037651079102845 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2755098368053974.
Fold 1 IBS: 0.2794872976889588
Fold 2 IBS: 0.2538208871784848
Fold 3 IBS: 0.205008241167859
Fold 4 IBS: 0.27570075552285517
Fold 5 IBS: 0.21845857053531406
[I 2024-04-13 23:44:29,597] Trial 6 finished with value: 0.24649515041869438 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.24649515041869438.
Fold 1 IBS: 0.24915948548968164
Fold 2 IBS: 0.2302034675508859
Fold 3 IBS: 0.21084506052977753
Fold 4 IBS: 0.24885470763433226
Fold 5 IBS: 0.21606041862742953
[I 2024-04-13 23:44:31,500] Trial 7 finished with value: 0.23102462796642137 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.23102462796642137.
Fold 1 IBS: 0.3429979817785824
Fold 2 IBS: 0.31722578035710736
Fold 3 IBS: 0.2009405070625271
Fold 4 IBS: 0.31601089170554875
Fold 5 IBS: 0.23185258245805143
[I 2024-04-13 23:44:39,041] Trial 8 finished with value: 0.2818055486723634 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.23102462796642137.
Fold 1 IBS: 0.43867652836581517
Fold 2 IBS: 0.3801217046198566
Fold 3 IBS: 0.24224939413296123
Fold 4 IBS: 0.39844965084427214
Fold 5 IBS: 0.3392206222392749
[I 2024-04-13 23:44:54,341] Trial 9 finished with value: 0.359743580040436 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.23102462796642137.
Fold 1 IBS: 0.24730140504189943
Fold 2 IBS: 0.23180355778544998
Fold 3 IBS: 0.22856182093970995
Fold 4 IBS: 0.2418371724471656
Fold 5 IBS: 0.22906264846898927
[I 2024-04-13 23:44:54,908] Trial 10 finished with value: 0.23571332093664282 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.23102462796642137.
Fold 1 IBS: 0.24749253260906404
Fold 2 IBS: 0.2310684912926093
Fold 3 IBS: 0.2272817268275755
Fold 4 IBS: 0.24147843009882622
Fold 5 IBS: 0.2279748608955893
[I 2024-04-13 23:44:55,242] Trial 11 finished with value: 0.23505920834473287 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.23102462796642137.
Fold 1 IBS: 0.27080715264387495
Fold 2 IBS: 0.2437835485391531
Fold 3 IBS: 0.1922945696153197
Fold 4 IBS: 0.2589170285026893
Fold 5 IBS: 0.20717300826273477
[I 2024-04-13 23:44:56,036] Trial 12 finished with value: 0.2345950615127544 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.23102462796642137.
Fold 1 IBS: 0.33668482784982595
Fold 2 IBS: 0.2905368560473815
Fold 3 IBS: 0.19732612731134846
Fold 4 IBS: 0.2884891406941597
Fold 5 IBS: 0.21748304468583132
[I 2024-04-13 23:44:57,678] Trial 13 finished with value: 0.2661039993177094 and parameters: {'subsample': 0.11029739529314715, 'dropout_rate': 0.695526957994077, 'n_estimators': 86, 'learning_rate': 0.09856277651579823}. Best is trial 7 with value: 0.23102462796642137.
Fold 1 IBS: 0.2549410662182252
Fold 2 IBS: 0.23428861100564943
Fold 3 IBS: 0.2047940514719884
Fold 4 IBS: 0.25270078617729763
Fold 5 IBS: 0.21208958331576488
[I 2024-04-13 23:44:59,232] Trial 14 finished with value: 0.23176281963778508 and parameters: {'subsample': 0.2888452381430052, 'dropout_rate': 0.6348327022941171, 'n_estimators': 79, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.23102462796642137.
Fold 1 IBS: 0.28189573565796106
Fold 2 IBS: 0.25932840520328204
Fold 3 IBS: 0.19751292322289765
Fold 4 IBS: 0.2725813302406989
Fold 5 IBS: 0.20983160846272528
[I 2024-04-13 23:45:02,958] Trial 15 finished with value: 0.24423000055751296 and parameters: {'subsample': 0.32891259566342446, 'dropout_rate': 0.6388722348302586, 'n_estimators': 122, 'learning_rate': 0.03807733004403891}. Best is trial 7 with value: 0.23102462796642137.
Fold 1 IBS: 0.27443043293599
Fold 2 IBS: 0.25484061727206003
Fold 3 IBS: 0.2000299036746026
Fold 4 IBS: 0.26917457395666483
Fold 5 IBS: 0.20934851632854126
[I 2024-04-13 23:45:09,592] Trial 16 finished with value: 0.24156480883357173 and parameters: {'subsample': 0.29945411212460843, 'dropout_rate': 0.9733961081825167, 'n_estimators': 297, 'learning_rate': 0.014532233272531826}. Best is trial 7 with value: 0.23102462796642137.
Fold 1 IBS: 0.2582955951769707
Fold 2 IBS: 0.2407574422177071
Fold 3 IBS: 0.20377678813744876
Fold 4 IBS: 0.26188502931982066
Fold 5 IBS: 0.21154646761783352
[I 2024-04-13 23:45:10,954] Trial 17 finished with value: 0.23525226449395617 and parameters: {'subsample': 0.37863334389246234, 'dropout_rate': 0.8194299873110976, 'n_estimators': 84, 'learning_rate': 0.040307073448257416}. Best is trial 7 with value: 0.23102462796642137.
Fold 1 IBS: 0.31627632082743784
Fold 2 IBS: 0.2920220307019899
Fold 3 IBS: 0.19347272646330485
Fold 4 IBS: 0.2813870324304434
Fold 5 IBS: 0.21734938082729036
[I 2024-04-13 23:45:22,839] Trial 18 finished with value: 0.26010149825009327 and parameters: {'subsample': 0.2055441703314718, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.01953752974380749}. Best is trial 7 with value: 0.23102462796642137.
Fold 1 IBS: 0.29861653808311434
Fold 2 IBS: 0.27744112646651514

Fold 3 IBS: 0.20009290904253257
Fold 4 IBS: 0.28092759525531996
Fold 5 IBS: 0.21555828062484997
[I 2024-04-13 23:45:25,523] Trial 19 finished with value: 0.2545272898944664 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.7998935816367629, 'n_estimators': 131, 'learning_rate': 0.04079002339855972}. Best is trial 7 with value: 0.23102462796642137.
Fold 1 IBS: 0.24742760026708696
Fold 2 IBS: 0.2311742087522739
Fold 3 IBS: 0.22734687420564928
Fold 4 IBS: 0.24147435145154503
Fold 5 IBS: 0.22814574868105966
[I 2024-04-13 23:45:26,530] Trial 20 finished with value: 0.23511375667152298 and parameters: {'subsample': 0.6102628884762309, 'dropout_rate': 0.5558690358940764, 'n_estimators': 48, 'learning_rate': 0.0034226676404933015}. Best is trial 7 with value: 0.23102462796642137.
Fold 1 IBS: 0.27050739789833333
Fold 2 IBS: 0.24284075769568764
Fold 3 IBS: 0.19210934491496381
Fold 4 IBS: 0.259467083338547
Fold 5 IBS: 0.20779310091666192
[I 2024-04-13 23:45:27,430] Trial 21 finished with value: 0.23454353695283875 and parameters: {'subsample': 0.12738816083359764, 'dropout_rate': 0.7742825171252221, 'n_estimators': 57, 'learning_rate': 0.08673794745524574}. Best is trial 7 with value: 0.23102462796642137.
Fold 1 IBS: 0.24749320497174018
Fold 2 IBS: 0.23154197470280394
Fold 3 IBS: 0.2278418900120989
Fold 4 IBS: 0.24082982484835605
Fold 5 IBS: 0.22827524465447274
[I 2024-04-13 23:45:27,762] Trial 22 finished with value: 0.23519642783789435 and parameters: {'subsample': 0.20663471307580814, 'dropout_rate': 0.8016407608161659, 'n_estimators': 2, 'learning_rate': 0.08137015989745504}. Best is trial 7 with value: 0.23102462796642137.
Fold 1 IBS: 0.24759227271750348
Fold 2 IBS: 0.23010356570600843
Fold 3 IBS: 0.20601963734196574
Fold 4 IBS: 0.24604446024468743
Fold 5 IBS: 0.21325005289873636
[I 2024-04-13 23:45:29,019] Trial 23 finished with value: 0.22860199778178028 and parameters: {'subsample': 0.21259697531002625, 'dropout_rate': 0.6509847985550554, 'n_estimators': 75, 'learning_rate': 0.031886867609049595}. Best is trial 23 with value: 0.22860199778178028.
Fold 1 IBS: 0.27751011741692005
Fold 2 IBS: 0.2565277449075757
Fold 3 IBS: 0.20123674301321395
Fold 4 IBS: 0.2692623877580692
Fold 5 IBS: 0.21091447302330993
[I 2024-04-13 23:45:31,346] Trial 24 finished with value: 0.24309029322381775 and parameters: {'subsample': 0.3929738978931362, 'dropout_rate': 0.6092000919348152, 'n_estimators': 147, 'learning_rate': 0.030479994950545524}. Best is trial 23 with value: 0.22860199778178028.
Fold 1 IBS: 0.26734873193456016
Fold 2 IBS: 0.24775453990595805
Fold 3 IBS: 0.19275465524761207
Fold 4 IBS: 0.26657540418861736
Fold 5 IBS: 0.20968611981379473
[I 2024-04-13 23:45:33,014] Trial 25 finished with value: 0.23682389021810848 and parameters: {'subsample': 0.23396025152395997, 'dropout_rate': 0.49509302871236605, 'n_estimators': 96, 'learning_rate': 0.04499564959136668}. Best is trial 23 with value: 0.22860199778178028.
Fold 1 IBS: 0.3553622239464456
Fold 2 IBS: 0.32847067376735734
Fold 3 IBS: 0.20203816899940336
Fold 4 IBS: 0.32245009880671494
Fold 5 IBS: 0.24193443571762782
[I 2024-04-13 23:45:37,593] Trial 26 finished with value: 0.29005112024750984 and parameters: {'subsample': 0.42563505024475556, 'dropout_rate': 0.6062045777257039, 'n_estimators': 232, 'learning_rate': 0.031418842977266874}. Best is trial 23 with value: 0.22860199778178028.
Fold 1 IBS: 0.251661660333038
Fold 2 IBS: 0.23125850860672617
Fold 3 IBS: 0.2083621505220673
Fold 4 IBS: 0.2484315019673435
Fold 5 IBS: 0.21429255728004415
[I 2024-04-13 23:45:40,202] Trial 27 finished with value: 0.23080127574184384 and parameters: {'subsample': 0.32607132010429724, 'dropout_rate': 0.6723032923283258, 'n_estimators': 147, 'learning_rate': 0.01527484183303061}. Best is trial 23 with value: 0.22860199778178028.
Fold 1 IBS: 0.2500360101463795
Fold 2 IBS: 0.22974539714022793
Fold 3 IBS: 0.20428025181071852
Fold 4 IBS: 0.24447111173831731
Fold 5 IBS: 0.21372516704179043
[I 2024-04-13 23:45:43,871] Trial 28 finished with value: 0.22845158757548673 and parameters: {'subsample': 0.1840228724328097, 'dropout_rate': 0.419579278974342, 'n_estimators': 170, 'learning_rate': 0.014116661098438898}. Best is trial 28 with value: 0.22845158757548673.
Fold 1 IBS: 0.24758886760507734
Fold 2 IBS: 0.22784767716854676
Fold 3 IBS: 0.2101889371854947
Fold 4 IBS: 0.24109531001625487
Fold 5 IBS: 0.2175177343576791
[I 2024-04-13 23:45:47,745] Trial 29 finished with value: 0.22884770526661055 and parameters: {'subsample': 0.19212816347958056, 'dropout_rate': 0.3068043306406363, 'n_estimators': 159, 'learning_rate': 0.01031951442340065}. Best is trial 28 with value: 0.22845158757548673.
Fold 1 IBS: 0.25001913613281557
Fold 2 IBS: 0.23039785521396558
Fold 3 IBS: 0.20451786763816956
Fold 4 IBS: 0.2451081739729858
Fold 5 IBS: 0.21227670228596018
[I 2024-04-13 23:45:54,853] Trial 30 finished with value: 0.22846394704877934 and parameters: {'subsample': 0.17778102677388338, 'dropout_rate': 0.2809270090158051, 'n_estimators': 261, 'learning_rate': 0.009631865511153408}. Best is trial 28 with value: 0.22845158757548673.
Fold 1 IBS: 0.2504523677490507
Fold 2 IBS: 0.23087022137721483
Fold 3 IBS: 0.2038615485655167
Fold 4 IBS: 0.2457273018009804
Fold 5 IBS: 0.2121909367482916
[I 2024-04-13 23:46:01,660] Trial 31 finished with value: 0.22862047524821083 and parameters: {'subsample': 0.1797531932209046, 'dropout_rate': 0.30283127336732385, 'n_estimators': 261, 'learning_rate': 0.009985717986808182}. Best is trial 28 with value: 0.22845158757548673.
Fold 1 IBS: 0.24931402097948377
Fold 2 IBS: 0.22826295259095022
Fold 3 IBS: 0.20678669219087892
Fold 4 IBS: 0.24396833176813434
Fold 5 IBS: 0.2138328801243431
[I 2024-04-13 23:46:08,384] Trial 32 finished with value: 0.22843297553075806 and parameters: {'subsample': 0.17815172611405986, 'dropout_rate': 0.19820838677193905, 'n_estimators': 259, 'learning_rate': 0.008634030517259063}. Best is trial 32 with value: 0.22843297553075806.
Fold 1 IBS: 0.29701233243197284
Fold 2 IBS: 0.270231611974512
Fold 3 IBS: 0.19049940921075864
Fold 4 IBS: 0.27160140637972685
Fold 5 IBS: 0.2142651904008718
[I 2024-04-13 23:46:17,747] Trial 33 finished with value: 0.24872199007956844 and parameters: {'subsample': 0.1577485562363863, 'dropout_rate': 0.10331660131014647, 'n_estimators': 304, 'learning_rate': 0.0210128714959623}. Best is trial 32 with value: 0.22843297553075806.
Fold 1 IBS: 0.3915204150849391
Fold 2 IBS: 0.36147515377643835
Fold 3 IBS: 0.20064343193197381
Fold 4 IBS: 0.3340446713841052
Fold 5 IBS: 0.25305223743637506
[I 2024-04-13 23:46:32,663] Trial 34 finished with value: 0.3081471819227663 and parameters: {'subsample': 0.23624930855983892, 'dropout_rate': 0.20775318407232737, 'n_estimators': 394, 'learning_rate': 0.024734341677464432}. Best is trial 32 with value: 0.22843297553075806.
Fold 1 IBS: 0.24522006490130083
Fold 2 IBS: 0.22668843141936051
Fold 3 IBS: 0.21367659034541614
Fold 4 IBS: 0.23850305651991696
Fold 5 IBS: 0.2175145545548679
[I 2024-04-13 23:46:39,470] Trial 35 finished with value: 0.2283205395481725 and parameters: {'subsample': 0.10818964549110582, 'dropout_rate': 0.41333391397459407, 'n_estimators': 227, 'learning_rate': 0.0074463878641165306}. Best is trial 35 with value: 0.2283205395481725.
Fold 1 IBS: 0.24542436080640773
Fold 2 IBS: 0.22672701362073244
Fold 3 IBS: 0.21447468315815593
Fold 4 IBS: 0.23837573866817297
Fold 5 IBS: 0.21806014702885101
[I 2024-04-13 23:46:46,084] Trial 36 finished with value: 0.22861238865646402 and parameters: {'subsample': 0.10993892506507363, 'dropout_rate': 0.3894614153751503, 'n_estimators': 224, 'learning_rate': 0.007147825017669125}. Best is trial 35 with value: 0.2283205395481725.
Fold 1 IBS: 0.2511845078946935
Fold 2 IBS: 0.23180283930705464
Fold 3 IBS: 0.20746237920570623
Fold 4 IBS: 0.24801271337009315
Fold 5 IBS: 0.2139901578515215
[I 2024-04-13 23:46:50,872] Trial 37 finished with value: 0.2304905195258138 and parameters: {'subsample': 0.2685641218495365, 'dropout_rate': 0.43696212688443054, 'n_estimators': 187, 'learning_rate': 0.012559284238570403}. Best is trial 35 with value: 0.2283205395481725.
Fold 1 IBS: 0.25053447223261954

Fold 2 IBS: 0.22880211437250084
Fold 3 IBS: 0.21667863719519237
Fold 4 IBS: 0.24569786120287057
Fold 5 IBS: 0.21931283432048648
[I 2024-04-13 23:47:00,798] Trial 38 finished with value: 0.23220518386473396 and parameters: {'subsample': 0.8179022915704841, 'dropout_rate': 0.20055274347191668, 'n_estimators': 291, 'learning_rate': 0.0051143659180973786}. Best is trial 35 with value: 0.2283205395481725.
Fold 1 IBS: 0.26500588084271626
Fold 2 IBS: 0.2496186566002033
Fold 3 IBS: 0.19950871157267466
Fold 4 IBS: 0.2614732856346855
Fold 5 IBS: 0.20949395998492829
[I 2024-04-13 23:47:07,715] Trial 39 finished with value: 0.23702009892704162 and parameters: {'subsample': 0.2526181938471094, 'dropout_rate': 0.3392786150742839, 'n_estimators': 238, 'learning_rate': 0.01715036845928685}. Best is trial 35 with value: 0.2283205395481725.
Fold 1 IBS: 0.4382567475612011
Fold 2 IBS: 0.37999055787836866
Fold 3 IBS: 0.22265235718715823
Fold 4 IBS: 0.3930613813755423
Fold 5 IBS: 0.33609063559283936
[I 2024-04-13 23:47:18,573] Trial 40 finished with value: 0.3540103359190219 and parameters: {'subsample': 0.15944804004491664, 'dropout_rate': 0.27073406810212547, 'n_estimators': 333, 'learning_rate': 0.06226770474646314}. Best is trial 35 with value: 0.2283205395481725.
Fold 1 IBS: 0.28152849839541655
Fold 2 IBS: 0.2545286333592507
Fold 3 IBS: 0.19234750509989884
Fold 4 IBS: 0.2630717386686808
Fold 5 IBS: 0.21216597606677742
[I 2024-04-13 23:47:25,095] Trial 41 finished with value: 0.24072847031800482 and parameters: {'subsample': 0.18181822565939465, 'dropout_rate': 0.43553443317958906, 'n_estimators': 199, 'learning_rate': 0.025413107786565976}. Best is trial 35 with value: 0.2283205395481725.
Fold 1 IBS: 0.24571037937042498
Fold 2 IBS: 0.22635359433608726
Fold 3 IBS: 0.20745222612372416
Fold 4 IBS: 0.24017018073599916
Fold 5 IBS: 0.21488107024998954
[I 2024-04-13 23:47:33,251] Trial 42 finished with value: 0.22691349016324502 and parameters: {'subsample': 0.10546817166769537, 'dropout_rate': 0.20053315040919772, 'n_estimators': 266, 'learning_rate': 0.00817524541991685}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.24591064556684636
Fold 2 IBS: 0.22612356025861727
Fold 3 IBS: 0.21060787444090603
Fold 4 IBS: 0.24028660840060187
Fold 5 IBS: 0.2155841011799811
[I 2024-04-13 23:47:40,609] Trial 43 finished with value: 0.22770255796939054 and parameters: {'subsample': 0.10624406975534348, 'dropout_rate': 0.2089585148278673, 'n_estimators': 267, 'learning_rate': 0.007599140820939515}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.24599334364859082
Fold 2 IBS: 0.22779653069916664
Fold 3 IBS: 0.21912581140326973
Fold 4 IBS: 0.23919718355603165
Fold 5 IBS: 0.22187670758213998
[I 2024-04-13 23:47:51,237] Trial 44 finished with value: 0.23079791537783975 and parameters: {'subsample': 0.10233749777995137, 'dropout_rate': 0.2191008565811059, 'n_estimators': 275, 'learning_rate': 0.0036849186959919096}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.24631681758606133
Fold 2 IBS: 0.22720455150425728
Fold 3 IBS: 0.2057455076298845
Fold 4 IBS: 0.24271300044647753
Fold 5 IBS: 0.21347713059840326
[I 2024-04-13 23:48:04,736] Trial 45 finished with value: 0.22709140155301683 and parameters: {'subsample': 0.12780258661132204, 'dropout_rate': 0.1364453651373193, 'n_estimators': 322, 'learning_rate': 0.007381844735412125}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.24875085820305656
Fold 2 IBS: 0.22954720799549846
Fold 3 IBS: 0.2017419764156177
Fold 4 IBS: 0.24706024604140195
Fold 5 IBS: 0.21010879631931492
[I 2024-04-13 23:48:21,961] Trial 46 finished with value: 0.22744181699497795 and parameters: {'subsample': 0.13177981801698313, 'dropout_rate': 0.14284670342565597, 'n_estimators': 401, 'learning_rate': 0.00787209521098964}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.3156744028476985
Fold 2 IBS: 0.28146203271905673
Fold 3 IBS: 0.19375039085924045
Fold 4 IBS: 0.2787271581349383
Fold 5 IBS: 0.21589347487469396
[I 2024-04-13 23:48:39,561] Trial 47 finished with value: 0.2571014918871256 and parameters: {'subsample': 0.1450840854014047, 'dropout_rate': 0.1240463473883398, 'n_estimators': 374, 'learning_rate': 0.02011782838490002}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.2454168408764117
Fold 2 IBS: 0.22682505090330082
Fold 3 IBS: 0.21362709794751095
Fold 4 IBS: 0.23869763085159104
Fold 5 IBS: 0.21907551564038233
[I 2024-04-13 23:49:03,272] Trial 48 finished with value: 0.22872842724383938 and parameters: {'subsample': 0.10042316432797058, 'dropout_rate': 0.16337818772447354, 'n_estimators': 442, 'learning_rate': 0.0033749212923804726}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.42745617028975175
Fold 2 IBS: 0.37570039517153353
Fold 3 IBS: 0.22014408464458143
Fold 4 IBS: 0.3873874647493942
Fold 5 IBS: 0.31702968518629243
[I 2024-04-13 23:49:22,873] Trial 49 finished with value: 0.34554356000831066 and parameters: {'subsample': 0.8328091381107422, 'dropout_rate': 0.16408825200228094, 'n_estimators': 434, 'learning_rate': 0.02713079119975165}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.2468535445653203
Fold 2 IBS: 0.23003286891604965
Fold 3 IBS: 0.224886405760629
Fold 4 IBS: 0.2404668708453428
Fold 5 IBS: 0.22631729595892
[I 2024-04-13 23:49:34,249] Trial 50 finished with value: 0.23371139720925233 and parameters: {'subsample': 0.13644564047629415, 'dropout_rate': 0.2433114690276776, 'n_estimators': 324, 'learning_rate': 0.0012042113877892037}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.25023479455761943
Fold 2 IBS: 0.2310840551168622
Fold 3 IBS: 0.20159526532541247
Fold 4 IBS: 0.24873987374532885
Fold 5 IBS: 0.20995314021115602
[I 2024-04-13 23:49:51,304] Trial 51 finished with value: 0.2283214257912758 and parameters: {'subsample': 0.1451065517959904, 'dropout_rate': 0.13281868996655108, 'n_estimators': 370, 'learning_rate': 0.008764317844543684}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.24770483943090296
Fold 2 IBS: 0.22815242784602002
Fold 3 IBS: 0.20552694813143532
Fold 4 IBS: 0.24403576460349585
Fold 5 IBS: 0.2124444939463062
[I 2024-04-13 23:50:13,826] Trial 52 finished with value: 0.2275728947916321 and parameters: {'subsample': 0.1422341825682819, 'dropout_rate': 0.13443731168536988, 'n_estimators': 411, 'learning_rate': 0.006416729279467577}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.3244272234839289
Fold 2 IBS: 0.30905014529165137
Fold 3 IBS: 0.19607862035172605
Fold 4 IBS: 0.29823547114113413
Fold 5 IBS: 0.22201344017607522
[I 2024-04-13 23:50:34,556] Trial 53 finished with value: 0.2699609800889031 and parameters: {'subsample': 0.28961587037388425, 'dropout_rate': 0.17080890697328677, 'n_estimators': 390, 'learning_rate': 0.017522751035627598}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.2866093141506934
Fold 2 IBS: 0.2735084131085338
Fold 3 IBS: 0.1935161200513423
Fold 4 IBS: 0.27621358024338066
Fold 5 IBS: 0.21221685091184428
[I 2024-04-13 23:50:52,939] Trial 54 finished with value: 0.2484128556931589 and parameters: {'subsample': 0.237184813568233, 'dropout_rate': 0.10253675186978671, 'n_estimators': 424, 'learning_rate': 0.01323845566705048}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.2598876412187553
Fold 2 IBS: 0.23929883151924908
Fold 3 IBS: 0.2073825077947124
Fold 4 IBS: 0.2619461852433115
Fold 5 IBS: 0.21243569691216088
[I 2024-04-13 23:51:22,979] Trial 55 finished with value: 0.2361901725376378 and parameters: {'subsample': 0.5460014539035196, 'dropout_rate': 0.23641780255892914, 'n_estimators': 490, 'learning_rate': 0.006365632367636946}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.24693792268612214
Fold 2 IBS: 0.23022292796283825
Fold 3 IBS: 0.22538751520779968
Fold 4 IBS: 0.24049743149880234
Fold 5 IBS: 0.22664251464072452
[I 2024-04-13 23:51:44,793] Trial 56 finished with value: 0.23393766239925737 and parameters: {'subsample': 0.13632374216691295, 'dropout_rate': 0.3516255709716011, 'n_estimators': 350, 'learning_rate': 0.0010068155155122573}. Best is trial 42 with value: 0.22691349016324502.

Fold 1 IBS: 0.34134749646168555
Fold 2 IBS: 0.28827179155308336
Fold 3 IBS: 0.19590174214457132
Fold 4 IBS: 0.28445727552826344
Fold 5 IBS: 0.22199440951018173
[I 2024-04-13 23:52:09,634] Trial 57 finished with value: 0.26639454303955706 and parameters: {'subsample': 0.10155250151178148, 'dropout_rate': 0.14123222013912567, 'n_estimators': 414, 'learning_rate': 0.022298480882720552}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.2863065192864519
Fold 2 IBS: 0.26424025716713934
Fold 3 IBS: 0.19541748908639128
Fold 4 IBS: 0.2691426806122312
Fold 5 IBS: 0.2099161899818892
[I 2024-04-13 23:52:38,765] Trial 58 finished with value: 0.24500462722682056 and parameters: {'subsample': 0.21440673626087092, 'dropout_rate': 0.18587113896354301, 'n_estimators': 463, 'learning_rate': 0.011794289021626232}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.30737769969344786
Fold 2 IBS: 0.2819266445413722
Fold 3 IBS: 0.20367604257377533
Fold 4 IBS: 0.2939360165255638
Fold 5 IBS: 0.22273939895538755
[I 2024-04-13 23:52:55,919] Trial 59 finished with value: 0.2619311604579094 and parameters: {'subsample': 0.6869904791039767, 'dropout_rate': 0.2464069453849117, 'n_estimators': 319, 'learning_rate': 0.017380424119431928}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.24880285323032775
Fold 2 IBS: 0.22870407443840166
Fold 3 IBS: 0.21566045458849387
Fold 4 IBS: 0.24357480346195495
Fold 5 IBS: 0.2182020161026041
[I 2024-04-13 23:53:05,591] Trial 60 finished with value: 0.23098884036435646 and parameters: {'subsample': 0.33570885814531926, 'dropout_rate': 0.3205444735734634, 'n_estimators': 242, 'learning_rate': 0.006028621878826597}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.2487155111133283
Fold 2 IBS: 0.22949872294672422
Fold 3 IBS: 0.2035425400688826
Fold 4 IBS: 0.2461285561648815
Fold 5 IBS: 0.2113836727254846
[I 2024-04-13 23:53:24,059] Trial 61 finished with value: 0.22785380060386023 and parameters: {'subsample': 0.1456943337269374, 'dropout_rate': 0.12862608329560662, 'n_estimators': 362, 'learning_rate': 0.007946581292465029}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.2468451918207057
Fold 2 IBS: 0.22785324387443248
Fold 3 IBS: 0.20437883038947072
Fold 4 IBS: 0.24465963538482155
Fold 5 IBS: 0.21201625046537095
[I 2024-04-13 23:53:44,151] Trial 62 finished with value: 0.22715063038696023 and parameters: {'subsample': 0.13189680355730937, 'dropout_rate': 0.14381942335847084, 'n_estimators': 352, 'learning_rate': 0.007644339182401895}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.26037589071793116
Fold 2 IBS: 0.2409182308040599
Fold 3 IBS: 0.19459685503725593
Fold 4 IBS: 0.25913807203834066
Fold 5 IBS: 0.2078494117268647
[I 2024-04-13 23:54:11,653] Trial 63 finished with value: 0.23257569206489048 and parameters: {'subsample': 0.1577827807784178, 'dropout_rate': 0.14019323422610555, 'n_estimators': 348, 'learning_rate': 0.01282334906134907}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.32042825824300675
Fold 2 IBS: 0.30331732576589393
Fold 3 IBS: 0.2028701232075291
Fold 4 IBS: 0.3031911429026533
Fold 5 IBS: 0.2220057865464384
[I 2024-04-13 23:54:47,785] Trial 64 finished with value: 0.2703625273331043 and parameters: {'subsample': 0.5970590048806756, 'dropout_rate': 0.10091042267523331, 'n_estimators': 399, 'learning_rate': 0.016026997408142868}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.4373826443936739
Fold 2 IBS: 0.37994346292505504
Fold 3 IBS: 0.2244159849865619
Fold 4 IBS: 0.39234744387174997
Fold 5 IBS: 0.3245718346694051
[I 2024-04-13 23:55:06,248] Trial 65 finished with value: 0.3517322741692892 and parameters: {'subsample': 0.20384822734500213, 'dropout_rate': 0.1753124903220859, 'n_estimators': 282, 'learning_rate': 0.07323117366677331}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.24854522831885975
Fold 2 IBS: 0.22918200182046933
Fold 3 IBS: 0.21156713800955596
Fold 4 IBS: 0.24361562503840706
Fold 5 IBS: 0.21583974190753438
[I 2024-04-13 23:55:22,970] Trial 66 finished with value: 0.22974994701896528 and parameters: {'subsample': 0.2627740542414409, 'dropout_rate': 0.23082894031848544, 'n_estimators': 309, 'learning_rate': 0.00607726277679603}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.2672836201480413
Fold 2 IBS: 0.2465897373564461
Fold 3 IBS: 0.20419824479069407
Fold 4 IBS: 0.26800656457228855
Fold 5 IBS: 0.20968632965435935
[I 2024-04-13 23:55:47,042] Trial 67 finished with value: 0.23915289930436584 and parameters: {'subsample': 0.4590303067651391, 'dropout_rate': 0.15401943770179283, 'n_estimators': 355, 'learning_rate': 0.010943270936943354}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.4382291948040959
Fold 2 IBS: 0.3799308926378767
Fold 3 IBS: 0.2234347347253886
Fold 4 IBS: 0.39319362926131585
Fold 5 IBS: 0.3368477026481669
[I 2024-04-13 23:56:15,839] Trial 68 finished with value: 0.35432723081536877 and parameters: {'subsample': 0.12850946033563157, 'dropout_rate': 0.27323505641877777, 'n_estimators': 382, 'learning_rate': 0.0582375351466085}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.24681848431447984
Fold 2 IBS: 0.22731716231648874
Fold 3 IBS: 0.20950788191611258
Fold 4 IBS: 0.24150494243763188
Fold 5 IBS: 0.21596803874310377
[I 2024-04-13 23:56:45,928] Trial 69 finished with value: 0.22822330194556337 and parameters: {'subsample': 0.15927279480740877, 'dropout_rate': 0.12856802672660578, 'n_estimators': 404, 'learning_rate': 0.004618738631617413}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.3584960797239168
Fold 2 IBS: 0.3482420578645979
Fold 3 IBS: 0.19736606512902105
Fold 4 IBS: 0.3158150618186097
Fold 5 IBS: 0.2402069105494223
[I 2024-04-13 23:57:13,703] Trial 70 finished with value: 0.2920252350171135 and parameters: {'subsample': 0.21479109855618878, 'dropout_rate': 0.20470428224010428, 'n_estimators': 454, 'learning_rate': 0.01921363015498352}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.2471625944479363
Fold 2 IBS: 0.22737774631359664
Fold 3 IBS: 0.21148742983312904
Fold 4 IBS: 0.24195448390129415
Fold 5 IBS: 0.21596960425948844
[I 2024-04-13 23:57:37,700] Trial 71 finished with value: 0.22879037175108893 and parameters: {'subsample': 0.16534957302626394, 'dropout_rate': 0.12653510056900763, 'n_estimators': 362, 'learning_rate': 0.005163036601524486}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.24624110133586674
Fold 2 IBS: 0.22778421809180469
Fold 3 IBS: 0.21815521269148272
Fold 4 IBS: 0.2390293595187005
Fold 5 IBS: 0.22092620155196344
[I 2024-04-13 23:58:07,955] Trial 72 finished with value: 0.23042721863796362 and parameters: {'subsample': 0.14633237743440433, 'dropout_rate': 0.12085719568903015, 'n_estimators': 407, 'learning_rate': 0.0027056306331127407}. Best is trial 42 with value: 0.22691349016324502.
Fold 1 IBS: 0.24734171164877342
Fold 2 IBS: 0.2277918873424644
Fold 3 IBS: 0.20380892197452097
Fold 4 IBS: 0.24398069100524872
Fold 5 IBS: 0.2109928488438333
[I 2024-04-13 23:58:31,661] Trial 73 finished with value: 0.22678321216296818 and parameters: {'subsample': 0.12488556497083315, 'dropout_rate': 0.1843983682623982, 'n_estimators': 336, 'learning_rate': 0.008496468222489865}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.24857585851153177
Fold 2 IBS: 0.22860248358858373
Fold 3 IBS: 0.2021709069861488
Fold 4 IBS: 0.24560372000057007
Fold 5 IBS: 0.20984331761813893
[I 2024-04-13 23:58:57,684] Trial 74 finished with value: 0.22695925734099465 and parameters: {'subsample': 0.12411723145114135, 'dropout_rate': 0.18647337396554847, 'n_estimators': 339, 'learning_rate': 0.00930143211690881}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.2616497719231744
Fold 2 IBS: 0.23595707512709246
Fold 3 IBS: 0.19586186769392996
Fold 4 IBS: 0.25485197045773256
Fold 5 IBS: 0.20715562085606642
[I 2024-04-13 23:59:26,750] Trial 75 finished with value: 0.23109526121159915 and parameters: {'subsample': 0.12013197285327108, 'dropout_rate': 0.18927633202069064, 'n_estimators': 336, 'learning_rate': 0.013970650394253638}. Best is trial 73 with value: 0.22678321216296818.

Fold 1 IBS: 0.2516786101504664
Fold 2 IBS: 0.23193557799297
Fold 3 IBS: 0.2020826885904135
Fold 4 IBS: 0.2483972146162672
Fold 5 IBS: 0.21142555143785993
[I 2024-04-13 23:59:48,750] Trial 76 finished with value: 0.2291039285575954 and parameters: {'subsample': 0.19559175095913203, 'dropout_rate': 0.2574951907974749, 'n_estimators': 291, 'learning_rate': 0.009548871684798064}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.2510429600435854
Fold 2 IBS: 0.23108092412295983
Fold 3 IBS: 0.19844353160525516
Fold 4 IBS: 0.2500563460692217
Fold 5 IBS: 0.2091974778010016
[I 2024-04-14 00:00:20,945] Trial 77 finished with value: 0.2279642479284047 and parameters: {'subsample': 0.12666944775373173, 'dropout_rate': 0.15754313237114592, 'n_estimators': 314, 'learning_rate': 0.011285222373789037}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.43814619870094235
Fold 2 IBS: 0.3800895010536585
Fold 3 IBS: 0.2274262329574573
Fold 4 IBS: 0.3941020392267966
Fold 5 IBS: 0.33339250777944723
[I 2024-04-14 00:00:45,114] Trial 78 finished with value: 0.35463129594366044 and parameters: {'subsample': 0.23957179565357356, 'dropout_rate': 0.21407164781770574, 'n_estimators': 274, 'learning_rate': 0.080452264349966}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.43624861477664817
Fold 2 IBS: 0.3794979388146489
Fold 3 IBS: 0.2169552396661707
Fold 4 IBS: 0.389481288050362
Fold 5 IBS: 0.3266780618137039
[I 2024-04-14 00:01:11,306] Trial 79 finished with value: 0.34977222862430674 and parameters: {'subsample': 0.1720183428969368, 'dropout_rate': 0.29976037307257597, 'n_estimators': 343, 'learning_rate': 0.0482295806079972}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.2656985931641012
Fold 2 IBS: 0.2361469068563165
Fold 3 IBS: 0.19326410445555722
Fold 4 IBS: 0.25423695035434046
Fold 5 IBS: 0.20730871871046694
[I 2024-04-14 00:01:31,623] Trial 80 finished with value: 0.23133105470815646 and parameters: {'subsample': 0.11599498022791074, 'dropout_rate': 0.1835064275776629, 'n_estimators': 328, 'learning_rate': 0.014875814643670153}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.24836364869743052
Fold 2 IBS: 0.22903785259334367
Fold 3 IBS: 0.20184079897959148
Fold 4 IBS: 0.24673237045676014
Fold 5 IBS: 0.21054697499515101
[I 2024-04-14 00:01:59,443] Trial 81 finished with value: 0.22730432914445536 and parameters: {'subsample': 0.1328748101882397, 'dropout_rate': 0.15020420514666022, 'n_estimators': 379, 'learning_rate': 0.008129525267159664}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.25356005431143686
Fold 2 IBS: 0.23790839881322354
Fold 3 IBS: 0.19971304250143398
Fold 4 IBS: 0.2550500741447767
Fold 5 IBS: 0.20908209209770443
[I 2024-04-14 00:02:27,771] Trial 82 finished with value: 0.23106273237371505 and parameters: {'subsample': 0.19251963469569744, 'dropout_rate': 0.22435105549812553, 'n_estimators': 384, 'learning_rate': 0.009199696538971921}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.24721137434879123
Fold 2 IBS: 0.2277177727439934
Fold 3 IBS: 0.21624035182438833
Fold 4 IBS: 0.24060583383310236
Fold 5 IBS: 0.21984159095028194
[I 2024-04-14 00:02:54,783] Trial 83 finished with value: 0.23032338474011146 and parameters: {'subsample': 0.22053341370142673, 'dropout_rate': 0.16077453354260268, 'n_estimators': 373, 'learning_rate': 0.0032657378369701376}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.25190257382118786
Fold 2 IBS: 0.22970704205415776
Fold 3 IBS: 0.1995388190314435
Fold 4 IBS: 0.24715654268566026
Fold 5 IBS: 0.20886724708744814
[I 2024-04-14 00:03:12,695] Trial 84 finished with value: 0.22743444493597947 and parameters: {'subsample': 0.12175720267456154, 'dropout_rate': 0.19061190917539914, 'n_estimators': 300, 'learning_rate': 0.011532780368979095}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.2854321317828565
Fold 2 IBS: 0.25855830670478186
Fold 3 IBS: 0.19394033066984562
Fold 4 IBS: 0.2692250185411938
Fold 5 IBS: 0.2095890812583913
[I 2024-04-14 00:03:29,829] Trial 85 finished with value: 0.24334897379141385 and parameters: {'subsample': 0.17110933223687563, 'dropout_rate': 0.18633623264832536, 'n_estimators': 304, 'learning_rate': 0.018703016610125554}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.38934925856777464
Fold 2 IBS: 0.34050489060251865
Fold 3 IBS: 0.1976788695967614
Fold 4 IBS: 0.32081780591446596
Fold 5 IBS: 0.2596518201771411
[I 2024-04-14 00:03:44,381] Trial 86 finished with value: 0.3016005289717324 and parameters: {'subsample': 0.13774960600386282, 'dropout_rate': 0.9466587881139311, 'n_estimators': 339, 'learning_rate': 0.02849613435548784}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.3822133896414867
Fold 2 IBS: 0.3173957205840391
Fold 3 IBS: 0.1997113490145668
Fold 4 IBS: 0.30396106886966784
Fold 5 IBS: 0.24279996056942643
[I 2024-04-14 00:03:58,888] Trial 87 finished with value: 0.28921629773583735 and parameters: {'subsample': 0.12287054496519728, 'dropout_rate': 0.14873022495784902, 'n_estimators': 291, 'learning_rate': 0.03538673247962338}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.318896329228849
Fold 2 IBS: 0.29573875785827497
Fold 3 IBS: 0.1925130077158576
Fold 4 IBS: 0.28759748577056043
Fold 5 IBS: 0.22157064417955286
[I 2024-04-14 00:04:15,718] Trial 88 finished with value: 0.26326324495061904 and parameters: {'subsample': 0.1882422629604682, 'dropout_rate': 0.10131575489267997, 'n_estimators': 320, 'learning_rate': 0.022549603940793018}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.3204484783671696
Fold 2 IBS: 0.30741441787988666
Fold 3 IBS: 0.19664836638772384
Fold 4 IBS: 0.2947376389692221
Fold 5 IBS: 0.2265076315567486
[I 2024-04-14 00:04:41,585] Trial 89 finished with value: 0.2691513066321502 and parameters: {'subsample': 0.2784113819760329, 'dropout_rate': 0.2694378413440396, 'n_estimators': 422, 'learning_rate': 0.015651366276015686}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.43797559838054884
Fold 2 IBS: 0.3800546423933688
Fold 3 IBS: 0.22129892256804878
Fold 4 IBS: 0.39285441653125025
Fold 5 IBS: 0.33258857807579945
[I 2024-04-14 00:05:01,626] Trial 90 finished with value: 0.35295443158980316 and parameters: {'subsample': 0.15354464196370737, 'dropout_rate': 0.17416657003120134, 'n_estimators': 357, 'learning_rate': 0.06614579056733322}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.24557768129315147
Fold 2 IBS: 0.22663165629607482
Fold 3 IBS: 0.21105669403716193
Fold 4 IBS: 0.24046321354966144
Fold 5 IBS: 0.21574371089362898
[I 2024-04-14 00:05:12,890] Trial 91 finished with value: 0.2278945912139357 and parameters: {'subsample': 0.11567190359134964, 'dropout_rate': 0.2091071989886196, 'n_estimators': 258, 'learning_rate': 0.0075233960912519365}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.2501882692353764
Fold 2 IBS: 0.23100957842338574
Fold 3 IBS: 0.20077518922452336
Fold 4 IBS: 0.24641884102401967
Fold 5 IBS: 0.20882017529084623
[I 2024-04-14 00:05:26,683] Trial 92 finished with value: 0.22744241063963028 and parameters: {'subsample': 0.12580555624562473, 'dropout_rate': 0.23050601347984928, 'n_estimators': 277, 'learning_rate': 0.012274276683640775}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.24703592060421473
Fold 2 IBS: 0.2299246646801071
Fold 3 IBS: 0.20219572878353445
Fold 4 IBS: 0.2454875291199802
Fold 5 IBS: 0.20934537642373102
[I 2024-04-14 00:05:42,412] Trial 93 finished with value: 0.2267978439223135 and parameters: {'subsample': 0.10167742455948861, 'dropout_rate': 0.24790382813824574, 'n_estimators': 303, 'learning_rate': 0.012114249342293028}. Best is trial 73 with value: 0.22678321216296818.
Fold 1 IBS: 0.24450877946296679
Fold 2 IBS: 0.22723137239013744
Fold 3 IBS: 0.2057442021216515
Fold 4 IBS: 0.24405113251664048
Fold 5 IBS: 0.21162919945520395
[I 2024-04-14 00:05:52,810] Trial 94 finished with value: 0.22663293718932 and parameters: {'subsample': 0.10169425103438497, 'dropout_rate': 0.5306326676271426, 'n_estimators': 247, 'learning_rate': 0.011681836804668841}. Best is trial 94 with value: 0.22663293718932.

Fold 1 IBS: 0.2454644157433154
Fold 2 IBS: 0.22775053358291678
Fold 3 IBS: 0.2049318513399491
Fold 4 IBS: 0.2454285245252791
Fold 5 IBS: 0.2103931376534002
[I 2024-04-14 00:06:05,907] Trial 95 finished with value: 0.2267936925689721 and parameters: {'subsample': 0.10055426267247433, 'dropout_rate': 0.579432905612242, 'n_estimators': 302, 'learning_rate': 0.0104996623949856}. Best is trial 94 with value: 0.22663293718932.
Fold 1 IBS: 0.24407421958765746
Fold 2 IBS: 0.2265178165506223
Fold 3 IBS: 0.21047140976758358
Fold 4 IBS: 0.2402148711696357
Fold 5 IBS: 0.2148373578953299
[I 2024-04-14 00:06:12,260] Trial 96 finished with value: 0.2272231349941658 and parameters: {'subsample': 0.10098443363009074, 'dropout_rate': 0.890178865177957, 'n_estimators': 211, 'learning_rate': 0.010469983994091473}. Best is trial 94 with value: 0.22663293718932.
Fold 1 IBS: 0.2529705416500711
Fold 2 IBS: 0.2321605213728353
Fold 3 IBS: 0.20271441494189463
Fold 4 IBS: 0.24981162098044993
Fold 5 IBS: 0.21147653043408748
[I 2024-04-14 00:06:19,730] Trial 97 finished with value: 0.22982672587586772 and parameters: {'subsample': 0.16671626326210792, 'dropout_rate': 0.49736674936409375, 'n_estimators': 206, 'learning_rate': 0.014756380025867107}. Best is trial 94 with value: 0.22663293718932.
Fold 1 IBS: 0.25944634779264236
Fold 2 IBS: 0.23699919542864675
Fold 3 IBS: 0.19685805197042452
Fold 4 IBS: 0.25721972847859986
Fold 5 IBS: 0.20618066854539327
[I 2024-04-14 00:06:29,107] Trial 98 finished with value: 0.23134079844314134 and parameters: {'subsample': 0.10477160896696115, 'dropout_rate': 0.8208452021185543, 'n_estimators': 247, 'learning_rate': 0.02064219419178417}. Best is trial 94 with value: 0.22663293718932.
Fold 1 IBS: 0.24777487221289704
Fold 2 IBS: 0.23020666301505102
Fold 3 IBS: 0.22552139389205975
Fold 4 IBS: 0.24123597073786415
Fold 5 IBS: 0.2265621500902118
[I 2024-04-14 00:06:36,218] Trial 99 finished with value: 0.23426020998961677 and parameters: {'subsample': 0.943000862554646, 'dropout_rate': 0.5592184037912078, 'n_estimators': 212, 'learning_rate': 0.0017462982219379483}. Best is trial 94 with value: 0.22663293718932.


* Best trial for IBS:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.22663293718932], datetime_start=datetime.datetime(2024, 4, 14, 0, 5, 42, 467127), datetime_complete=datetime.datetime(2024, 4, 14, 0, 5, 52, 809739), params={'subsample': 0.10169425103438497, 'dropout_rate': 0.5306326676271426, 'n_estimators': 247, 'learning_rate': 0.011681836804668841}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=94, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.10169425103438497, 'dropout_rate': 0.5306326676271426, 'n_estimators': 247, 'learning_rate': 0.011681836804668841}


* Best Score for IBS:
 0.22663293718932

In [66]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [67]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.649
train_ibs:  0.227

#### Test

In [68]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [69]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.5443165878852756,
                                              learning_rate=0.03191386107427406,
                                              n_estimators=213,
                                              random_state=123,
                                              subsample=0.4877764869966794)

C-index score: 0.602

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.5306326676271426,
                                              learning_rate=0.011681836804668841,
                                              n_estimators=247,
                                              random_state=123,
                                              subsample=0.10169425103438497)

IBS: 0.224

In [70]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [71]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
ComponentwiseGradientBoosting    0.649   1.0
Randomsurvivalforest             0.640   2.5
ExtraSurvivalTrees               0.640   2.5
GradientBoosting                 0.637   4.0
CoxPH                            0.633   6.0
CoxLasso                         0.633   6.0
CoxElastic                       0.633   6.0
CoxRidge                         0.622   8.0

In [72]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.219   1.5
ExtraSurvivalTrees             0.219   1.5
CoxLasso                       0.223   3.5
CoxElastic                     0.223   3.5
CoxPH                          0.224   5.0
ComponentwiseGradientBoosting  0.227   6.0
GradientBoosting               0.232   7.0
CoxRidge                       0.236   8.0

In [73]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ExtraSurvivalTrees               0.654   1.0
CoxRidge                         0.653   2.5
Randomsurvivalforest             0.653   2.5
ComponentwiseGradientBoosting    0.602   4.0
GradientBoosting                 0.598   5.0
CoxPH                            0.550   7.0
CoxLasso                         0.550   7.0
CoxElastic                       0.550   7.0

In [74]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
Randomsurvivalforest           0.221   1.0
ExtraSurvivalTrees             0.222   2.0
ComponentwiseGradientBoosting  0.224   3.0
GradientBoosting               0.225   4.0
CoxRidge                       0.229   5.0
CoxLasso                       0.233   6.5
CoxElastic                     0.233   6.5
CoxPH                          0.235   8.0

In [75]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/dfs/standard/plsr/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_dfs_standard_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [76]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-14