In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
from sklearn.preprocessing import StandardScaler
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

In [6]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

## Test dataset: MAASTRO

In [7]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [8]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [9]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [10]:
# Merge MAASTRO_D1 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG,DFS,DFS_event
0,1,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342,8.83,1.0
3,4,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979,19.73,1.0
4,6,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782,13.27,1.0
95,111,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212,72.07,0.0

In [11]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [12]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, DFS, DFS_event]
Index: []

In [13]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

In [14]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [15]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 14)
y_train:  (139,)

In [16]:
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [17]:
# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 16)

# Feature Selection: RENT

In [18]:
# Choose features from the result of RENT 
selected_features = ["hpv_related",
"pack_years",
"uicc8_III-IV",
"oropharynx",
"cavum_oris",
"TLG"]

In [19]:
X_rent = X.loc[:, selected_features]
X_new = X_rent.copy()

In [20]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, selected_features]

# Standardization

In [21]:
# Copy the original X for later 
original_X = X.copy()

In [22]:
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Standardize X_new, the new data with the selected features only 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = StandardScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [43]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order  
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[X_new.columns]

In [44]:
X_new

     hpv_related  pack_years  uicc8_III-IV  oropharynx  cavum_oris         TLG
0            0.0    0.000000           0.0           1           0   86.228420
1            0.0   27.404795           0.0           0           0    7.040100
2            0.0   41.019178           1.0           0           1   83.569669
3            0.0   37.500000           0.0           0           0    5.567091
4            0.0   53.000000           0.0           0           0   16.150550
..           ...         ...           ...         ...         ...         ...
134          1.0    0.000000           0.0           1           0   26.280140
135          1.0    0.000000           1.0           1           0  101.754834
136          1.0   39.498630           0.0           1           0   66.273201
137          1.0   71.527397           1.0           1           0   71.832443
138          1.0    2.250000           1.0           1           0   78.647696

[139 rows x 6 columns]

In [45]:
X_new_std

     hpv_related  pack_years  uicc8_III-IV  oropharynx  cavum_oris       TLG
0            0.0   -1.101176           0.0           1           0 -0.179158
1            0.0    0.105775           0.0           0           0 -0.587333
2            0.0    0.705374           1.0           0           1 -0.192863
3            0.0    0.550384           0.0           0           0 -0.594926
4            0.0    1.233028           0.0           0           0 -0.540373
..           ...         ...           ...         ...         ...       ...
134          1.0   -1.101176           0.0           1           0 -0.488161
135          1.0   -1.101176           1.0           1           0 -0.099128
136          1.0    0.638406           0.0           1           0 -0.282017
137          1.0    2.049005           1.0           1           0 -0.253362
138          1.0   -1.002083           1.0           1           0 -0.218233

[139 rows x 6 columns]

In [46]:
MAASTRO_new

    hpv_related  pack_years  uicc8_III-IV  oropharynx  cavum_oris         TLG
0             1           0             0           1           0  263.611623
1             0          20             1           1           0   36.980700
2             0           6             1           1           0   74.636342
3             0          45             1           0           0   46.791979
4             1          59             0           1           0  107.637514
..          ...         ...           ...         ...         ...         ...
94            0          55             1           0           0  144.490782
95            0         174             1           0           0   69.214868
96            1           0             1           1           0  102.594274
97            1           0             0           1           0  103.229492
98            0          40             1           0           0   28.553212

[99 rows x 6 columns]

In [47]:
MAASTRO_new_std

    hpv_related  pack_years  uicc8_III-IV  oropharynx  cavum_oris       TLG
0             1   -1.101176             0           1           0  0.735160
1             0   -0.220344             1           1           0 -0.433005
2             0   -0.836927             1           1           0 -0.238909
3             0    0.880696             1           0           0 -0.382433
4             1    1.497278             0           1           0 -0.068806
..          ...         ...           ...         ...         ...       ...
94            0    1.321112             1           0           0  0.121154
95            0    6.562062             1           0           0 -0.266854
96            1   -1.101176             1           1           0 -0.094801
97            1   -1.101176             0           1           0 -0.091527
98            0    0.660488             1           0           0 -0.476444

[99 rows x 6 columns]

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [48]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:20:39,423] A new study created in memory with name: no-name-18927288-354f-429f-83b7-85a73f109e97

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7446808510638298

[I 2024-04-13 17:20:40,007] A new study created in memory with name: no-name-90d4e377-b179-471f-8f1b-bb5cbe239754

Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:20:39,981] Trial 0 finished with value: 0.6380043211913705 and parameters: {}. Best is trial 0 with value: 0.6380043211913705.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6380043211913705], datetime_start=datetime.datetime(2024, 4, 13, 17, 20, 39, 496844), datetime_complete=datetime.datetime(2024, 4, 13, 17, 20, 39, 981288), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6380043211913705

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.23694732382610154
Fold 2 IBS: 0.2615158118717558
Fold 3 IBS: 0.17590965994359087
Fold 4 IBS: 0.28365588891632393
Fold 5 IBS: 0.19620686095559536
[I 2024-04-13 17:20:40,529] Trial 0 finished with value: 0.2308471091026735 and parameters: {}. Best is trial 0 with value: 0.2308471091026735.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2308471091026735], datetime_start=datetime.datetime(2024, 4, 13, 17, 20, 40, 42810), datetime_complete=datetime.datetime(2024, 4, 13, 17, 20, 40, 529211), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2308471091026735

In [49]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [50]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.638
train_ibs:  0.231

#### Test

In [51]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [52]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.532
IBS score: 0.276

In [53]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [54]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis

#### Train

In [55]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:20:40,888] A new study created in memory with name: no-name-604f00eb-3bbc-49d7-896b-9fa4e41eb42a

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-13 17:20:41,257] A new study created in memory with name: no-name-e3a499b9-e314-4faf-a9ac-76b725d18c0d

Fold 1 C-index: 0.651394422310757
Fold 2 C-index: 0.5038759689922481
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.5722433460076045
Fold 5 C-index: 0.6716738197424893
[I 2024-04-13 17:20:41,242] Trial 0 finished with value: 0.591752405027641 and parameters: {}. Best is trial 0 with value: 0.591752405027641.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.591752405027641], datetime_start=datetime.datetime(2024, 4, 13, 17, 20, 41, 3839), datetime_complete=datetime.datetime(2024, 4, 13, 17, 20, 41, 242133), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.591752405027641

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2472470958068372
Fold 2 IBS: 0.2320398857267834
Fold 3 IBS: 0.22898186411767818
Fold 4 IBS: 0.2419747806817174
Fold 5 IBS: 0.22939558343033542
[I 2024-04-13 17:20:41,548] Trial 0 finished with value: 0.23592784195267033 and parameters: {}. Best is trial 0 with value: 0.23592784195267033.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592784195267033], datetime_start=datetime.datetime(2024, 4, 13, 17, 20, 41, 298898), datetime_complete=datetime.datetime(2024, 4, 13, 17, 20, 41, 548647), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592784195267033

In [56]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [57]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.592
train_ibs:  0.236

#### Test

In [58]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [59]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.532

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [60]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [61]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:20:41,798] A new study created in memory with name: no-name-c8ff8980-f896-4996-8f73-ad11a41f5237

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979

[I 2024-04-13 17:20:42,443] A new study created in memory with name: no-name-7b64e401-238b-42af-b73e-7d9ec657d82c

Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:20:42,432] Trial 0 finished with value: 0.6361121278097317 and parameters: {}. Best is trial 0 with value: 0.6361121278097317.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6361121278097317], datetime_start=datetime.datetime(2024, 4, 13, 17, 20, 41, 882255), datetime_complete=datetime.datetime(2024, 4, 13, 17, 20, 42, 431962), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6361121278097317

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.23871402060708521
Fold 2 IBS: 0.2596185745944766
Fold 3 IBS: 0.17748888379055622
Fold 4 IBS: 0.28227578624047067
Fold 5 IBS: 0.1962887806623178
[I 2024-04-13 17:20:43,149] Trial 0 finished with value: 0.2308772091789813 and parameters: {}. Best is trial 0 with value: 0.2308772091789813.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2308772091789813], datetime_start=datetime.datetime(2024, 4, 13, 17, 20, 42, 518845), datetime_complete=datetime.datetime(2024, 4, 13, 17, 20, 43, 149409), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2308772091789813

In [62]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [63]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.636
train_ibs:  0.231

#### Test

In [64]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [65]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.532

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.273

In [66]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [67]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:20:43,535] A new study created in memory with name: no-name-8e600e3d-7e40-4083-a1dd-c24fdc8890d6

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:44,214] Trial 0 finished with value: 0.6369704969084441 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6369704969084441.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:44,766] Trial 1 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:45,377] Trial 2 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:45,888] Trial 3 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:20:46,601] Trial 4 finished with value: 0.6361121278097317 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:47,133] Trial 5 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:20:47,723] Trial 6 finished with value: 0.6361121278097317 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:48,214] Trial 7 finished with value: 0.6369704969084441 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:48,685] Trial 8 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:49,424] Trial 9 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6738197424892703
[I 2024-04-13 17:20:49,702] Trial 10 finished with value: 0.5893527440629118 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6738197424892703
[I 2024-04-13 17:20:49,979] Trial 11 finished with value: 0.5893527440629118 and parameters: {'l1_ratio': 0.10435988842665224}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:50,690] Trial 12 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.25848394608656616}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:51,712] Trial 13 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.23216328271690467}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:52,416] Trial 14 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.2652121201325421}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6781115879828327
[I 2024-04-13 17:20:52,606] Trial 15 finished with value: 0.5918047386596321 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:53,197] Trial 16 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3314184925703805}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:20:53,669] Trial 17 finished with value: 0.601131279816274 and parameters: {'l1_ratio': 0.16511694733206428}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:54,391] Trial 18 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.5300759780628291}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6781115879828327
[I 2024-04-13 17:20:54,617] Trial 19 finished with value: 0.5918047386596321 and parameters: {'l1_ratio': 0.013522847250075798}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:55,496] Trial 20 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3350080673295819}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:56,066] Trial 21 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.5622777690744459}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:56,689] Trial 22 finished with value: 0.6369704969084441 and parameters: {'l1_ratio': 0.6142440731136383}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:20:57,253] Trial 23 finished with value: 0.6361121278097317 and parameters: {'l1_ratio': 0.9648087073666172}. Best is trial 1 with value: 0.6377673096574481.

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:20:57,822] Trial 24 finished with value: 0.6361121278097317 and parameters: {'l1_ratio': 0.8723606880092448}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:58,428] Trial 25 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.45903747271503514}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:58,990] Trial 26 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3527001258697712}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:20:59,721] Trial 27 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.2175973137668402}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:21:00,598] Trial 28 finished with value: 0.6361121278097317 and parameters: {'l1_ratio': 0.7920074897193529}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6738197424892703
[I 2024-04-13 17:21:01,089] Trial 29 finished with value: 0.5829782420708799 and parameters: {'l1_ratio': 0.14781871454712675}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:01,920] Trial 30 finished with value: 0.6369704969084441 and parameters: {'l1_ratio': 0.6162788229000025}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:02,711] Trial 31 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4322560553491173}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:03,328] Trial 32 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.30185645201254085}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:03,838] Trial 33 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.40867968097270496}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:04,419] Trial 34 finished with value: 0.6369704969084441 and parameters: {'l1_ratio': 0.7174451665900385}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:05,120] Trial 35 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.5201794471554237}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:05,894] Trial 36 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3800893344068792}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:06,630] Trial 37 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.5802102856643269}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:07,235] Trial 38 finished with value: 0.6369704969084441 and parameters: {'l1_ratio': 0.6666890374280088}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:07,811] Trial 39 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:21:08,168] Trial 40 finished with value: 0.601131279816274 and parameters: {'l1_ratio': 0.17007639815117948}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:08,690] Trial 41 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4992600487858923}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:09,371] Trial 42 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.2894997540853173}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:10,147] Trial 43 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.5024054682243081}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:10,693] Trial 44 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3698144203724919}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:11,427] Trial 45 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.22141233389455595}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:12,053] Trial 46 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4178465972493743}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6738197424892703
[I 2024-04-13 17:21:12,241] Trial 47 finished with value: 0.5893527440629118 and parameters: {'l1_ratio': 0.0952901303384813}. Best is trial 1 with value: 0.6377673096574481.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:12,819] Trial 48 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.2832727302146274}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:13,306] Trial 49 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4677828429786992}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:13,833] Trial 50 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.556147470734502}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:14,343] Trial 51 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.31930961135854485}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:15,119] Trial 52 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3886372387612496}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:15,627] Trial 53 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.26061119856794585}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:16,217] Trial 54 finished with value: 0.6369704969084441 and parameters: {'l1_ratio': 0.6304504906551746}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:16,992] Trial 55 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4869847395037336}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:17,546] Trial 56 finished with value: 0.6342789375644248 and parameters: {'l1_ratio': 0.1862640519869659}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:18,036] Trial 57 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.34898186807163273}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6738197424892703
[I 2024-04-13 17:21:18,282] Trial 58 finished with value: 0.5829782420708799 and parameters: {'l1_ratio': 0.11769937506203332}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6781115879828327
[I 2024-04-13 17:21:18,453] Trial 59 finished with value: 0.5910442823858679 and parameters: {'l1_ratio': 0.06523230107443478}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:19,095] Trial 60 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.2345707271406993}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:19,838] Trial 61 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.258296456199544}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:20,479] Trial 62 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3222521276999822}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:21,051] Trial 63 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.40747183637529244}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:21,638] Trial 64 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.5570688422893437}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:22,141] Trial 65 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4504253602444891}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:22,664] Trial 66 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3573380304686857}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:23,117] Trial 67 finished with value: 0.6342789375644248 and parameters: {'l1_ratio': 0.19666171911917596}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:23,576] Trial 68 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.5898520290794558}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:24,060] Trial 69 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.5309516840655302}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:24,816] Trial 70 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.30580237662531445}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5741444866920152

Fold 5 C-index: 0.6738197424892703
[I 2024-04-13 17:21:25,283] Trial 71 finished with value: 0.5829782420708799 and parameters: {'l1_ratio': 0.1381436558135113}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:25,908] Trial 72 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.2402568598141997}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:26,596] Trial 73 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.20788143179679744}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:27,248] Trial 74 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.276728046657098}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:28,008] Trial 75 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.39507755210064815}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:28,570] Trial 76 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4272641967164084}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:21:28,945] Trial 77 finished with value: 0.601131279816274 and parameters: {'l1_ratio': 0.17128029248290985}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:29,599] Trial 78 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.33271678442035657}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:21:30,125] Trial 79 finished with value: 0.6361121278097317 and parameters: {'l1_ratio': 0.8187818034877232}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:30,620] Trial 80 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4787836393459479}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:31,259] Trial 81 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.2460391402634371}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:31,782] Trial 82 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.27442817886960813}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:32,304] Trial 83 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.29831539736785984}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:32,823] Trial 84 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.36350600901840513}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:33,388] Trial 85 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.5227482533345278}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:33,965] Trial 86 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.22044483068588858}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:21:34,409] Trial 87 finished with value: 0.6361121278097317 and parameters: {'l1_ratio': 0.651694927149534}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:35,064] Trial 88 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.43715641771561975}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:35,562] Trial 89 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.34066733493052015}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6738197424892703
[I 2024-04-13 17:21:35,786] Trial 90 finished with value: 0.5829782420708799 and parameters: {'l1_ratio': 0.1471264475550338}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:36,325] Trial 91 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3125345869026389}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:36,939] Trial 92 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.25455321985978263}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:37,431] Trial 93 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3866503941335897}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:37,949] Trial 94 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3729002078855825}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677

Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:38,369] Trial 95 finished with value: 0.6342789375644248 and parameters: {'l1_ratio': 0.18828253927666083}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:38,872] Trial 96 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.2655247695209814}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:39,382] Trial 97 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.2914829616875309}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:39,822] Trial 98 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.5068920377583492}. Best is trial 1 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979

[I 2024-04-13 17:21:40,353] A new study created in memory with name: no-name-bc8571e5-cade-409b-8f96-ad02af53c663

Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:21:40,331] Trial 99 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.40924791833229884}. Best is trial 1 with value: 0.6377673096574481.


* Best trial for C-index:
 FrozenTrial(number=1, state=TrialState.COMPLETE, values=[0.6377673096574481], datetime_start=datetime.datetime(2024, 4, 13, 17, 20, 44, 225330), datetime_complete=datetime.datetime(2024, 4, 13, 17, 20, 44, 765808), params={'l1_ratio': 0.28621072101688444}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=1, value=None)


* Best Score for C-index:
 0.6377673096574481

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23853069630534515
Fold 2 IBS: 0.25960504236444576
Fold 3 IBS: 0.1775955517345451
Fold 4 IBS: 0.28223154751356766
Fold 5 IBS: 0.19619977069315225
[I 2024-04-13 17:21:40,989] Trial 0 finished with value: 0.2308325217222112 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.2308325217222112.
Fold 1 IBS: 0.23827865105409132
Fold 2 IBS: 0.2596310519913947
Fold 3 IBS: 0.1775086410031393
Fold 4 IBS: 0.2822719285379554
Fold 5 IBS: 0.19605618940477867
[I 2024-04-13 17:21:41,655] Trial 1 finished with value: 0.23074929239827185 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.23074929239827185.
Fold 1 IBS: 0.23823724218535663
Fold 2 IBS: 0.2595408458083622
Fold 3 IBS: 0.17747364999597456
Fold 4 IBS: 0.28222578521701225
Fold 5 IBS: 0.19604077768278652
[I 2024-04-13 17:21:42,377] Trial 2 finished with value: 0.23070366017789845 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.23070366017789845.
Fold 1 IBS: 0.23839197259372139
Fold 2 IBS: 0.25967329870415723
Fold 3 IBS: 0.17748541867867343
Fold 4 IBS: 0.2821968463203081
Fold 5 IBS: 0.19615201416871744
[I 2024-04-13 17:21:43,009] Trial 3 finished with value: 0.23077991009311552 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.23070366017789845.
Fold 1 IBS: 0.2385088873394981
Fold 2 IBS: 0.2596680162892128
Fold 3 IBS: 0.17756162788490124
Fold 4 IBS: 0.2822636126674558
Fold 5 IBS: 0.1962110483274308
[I 2024-04-13 17:21:43,479] Trial 4 finished with value: 0.23084263850169978 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.23070366017789845.
Fold 1 IBS: 0.23828257284171744
Fold 2 IBS: 0.25968432519218443
Fold 3 IBS: 0.17755889227558116
Fold 4 IBS: 0.2822497953991683
Fold 5 IBS: 0.1961067642553863
[I 2024-04-13 17:21:44,040] Trial 5 finished with value: 0.23077646999280751 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.23070366017789845.
Fold 1 IBS: 0.23870082473326937
Fold 2 IBS: 0.2597516883111438
Fold 3 IBS: 0.17750079843052377
Fold 4 IBS: 0.2822496129706515
Fold 5 IBS: 0.19628692035653753
[I 2024-04-13 17:21:44,571] Trial 6 finished with value: 0.23089796896042522 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.23070366017789845.
Fold 1 IBS: 0.2385175805700174
Fold 2 IBS: 0.25974108147238056
Fold 3 IBS: 0.17760888813511022
Fold 4 IBS: 0.28220505295636117
Fold 5 IBS: 0.19619884638820917
[I 2024-04-13 17:21:45,076] Trial 7 finished with value: 0.2308542899044157 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.23070366017789845.
Fold 1 IBS: 0.23833287103304163
Fold 2 IBS: 0.25958528583980456
Fold 3 IBS: 0.17760028805011469
Fold 4 IBS: 0.28228224455741163
Fold 5 IBS: 0.19612930584962066
[I 2024-04-13 17:21:45,624] Trial 8 finished with value: 0.23078599906599867 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.23070366017789845.
Fold 1 IBS: 0.23828131122643098
Fold 2 IBS: 0.25953673457040594
Fold 3 IBS: 0.17748365110084524
Fold 4 IBS: 0.28228094322007996
Fold 5 IBS: 0.19609737064529273
[I 2024-04-13 17:21:46,197] Trial 9 finished with value: 0.23073600215261095 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.23070366017789845.
Fold 1 IBS: 0.2444025699552539
Fold 2 IBS: 0.23303747227481786
Fold 3 IBS: 0.2263434041794141
Fold 4 IBS: 0.25075671489797596
Fold 5 IBS: 0.22382214172199857
[I 2024-04-13 17:21:46,448] Trial 10 finished with value: 0.23567246060589206 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.23070366017789845.
Fold 1 IBS: 0.2383382321927193
Fold 2 IBS: 0.23411651318027732
Fold 3 IBS: 0.17744505515132453
Fold 4 IBS: 0.2821991578232202
Fold 5 IBS: 0.22053417541532527
[I 2024-04-13 17:21:46,926] Trial 11 finished with value: 0.23052662675257327 and parameters: {'l1_ratio': 0.18301335955800116}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.24544308102513637
Fold 2 IBS: 0.2326018679624026
Fold 3 IBS: 0.2273564682768081
Fold 4 IBS: 0.24675847415933483
Fold 5 IBS: 0.2257803181023451
[I 2024-04-13 17:21:47,252] Trial 12 finished with value: 0.23558804190520538 and parameters: {'l1_ratio': 0.0469133649279421}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23825049346012003
Fold 2 IBS: 0.2595734265443487
Fold 3 IBS: 0.17743211519341678
Fold 4 IBS: 0.2822481120060233
Fold 5 IBS: 0.1960236280633533
[I 2024-04-13 17:21:47,926] Trial 13 finished with value: 0.23070555505345242 and parameters: {'l1_ratio': 0.2094262397934587}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2382638331693799
Fold 2 IBS: 0.2596333768451858
Fold 3 IBS: 0.1774289894289328
Fold 4 IBS: 0.28228989893051276
Fold 5 IBS: 0.19603612032038772
[I 2024-04-13 17:21:48,456] Trial 14 finished with value: 0.2307304437388798 and parameters: {'l1_ratio': 0.23856005198520522}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23836263770441501
Fold 2 IBS: 0.2338392321912897
Fold 3 IBS: 0.2248396719599461
Fold 4 IBS: 0.2822439876248427
Fold 5 IBS: 0.22123376812718554
[I 2024-04-13 17:21:48,848] Trial 15 finished with value: 0.24010385952153582 and parameters: {'l1_ratio': 0.15608110273200437}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2470671668473734
Fold 2 IBS: 0.2320867709556846
Fold 3 IBS: 0.2288280130014508
Fold 4 IBS: 0.2423425105898583
Fold 5 IBS: 0.22902389669525264
[I 2024-04-13 17:21:49,088] Trial 16 finished with value: 0.23586967161792396 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2382395116163472
Fold 2 IBS: 0.25968343609843514
Fold 3 IBS: 0.17753520918974414
Fold 4 IBS: 0.28229105358697465
Fold 5 IBS: 0.1960674725611347
[I 2024-04-13 17:21:49,648] Trial 17 finished with value: 0.23076333661052714 and parameters: {'l1_ratio': 0.32086883765249574}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23834828068336109
Fold 2 IBS: 0.23385827741010454
Fold 3 IBS: 0.22480833897622854
Fold 4 IBS: 0.2822590209948766
Fold 5 IBS: 0.22118316148354777
[I 2024-04-13 17:21:50,037] Trial 18 finished with value: 0.24009141590962368 and parameters: {'l1_ratio': 0.15789337100394196}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23828580382744274
Fold 2 IBS: 0.25958665538414855
Fold 3 IBS: 0.17748238818279957
Fold 4 IBS: 0.28223156052744575
Fold 5 IBS: 0.19608172249710148
[I 2024-04-13 17:21:50,718] Trial 19 finished with value: 0.2307336260837876 and parameters: {'l1_ratio': 0.3381410862240941}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2383963751149618
Fold 2 IBS: 0.25968279273910205
Fold 3 IBS: 0.17748125417192523
Fold 4 IBS: 0.2822089087102482
Fold 5 IBS: 0.1961531307290865
[I 2024-04-13 17:21:51,332] Trial 20 finished with value: 0.23078449229306477 and parameters: {'l1_ratio': 0.554172957371549}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23825603123374042
Fold 2 IBS: 0.25961786136166226
Fold 3 IBS: 0.177492218722578
Fold 4 IBS: 0.2822929137993049
Fold 5 IBS: 0.19602030814335497
[I 2024-04-13 17:21:51,987] Trial 21 finished with value: 0.2307358666521281 and parameters: {'l1_ratio': 0.19684000937901808}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23841457403189506
Fold 2 IBS: 0.23334813372629445
Fold 3 IBS: 0.22571372812743812
Fold 4 IBS: 0.253608871498741
Fold 5 IBS: 0.2226973678222159
[I 2024-04-13 17:21:52,319] Trial 22 finished with value: 0.2347565350413169 and parameters: {'l1_ratio': 0.1109953828357226}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2382732843740578
Fold 2 IBS: 0.2596054213193499
Fold 3 IBS: 0.17751529096840307
Fold 4 IBS: 0.2822639472653789
Fold 5 IBS: 0.19605472458747528
[I 2024-04-13 17:21:52,909] Trial 23 finished with value: 0.23074253370293302 and parameters: {'l1_ratio': 0.2844104194762936}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2382569989785515
Fold 2 IBS: 0.2596311571087987
Fold 3 IBS: 0.17752170046658475
Fold 4 IBS: 0.28229549165057727
Fold 5 IBS: 0.19602858886855956
[I 2024-04-13 17:21:53,524] Trial 24 finished with value: 0.23074678741461435 and parameters: {'l1_ratio': 0.21736087814603194}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2382779953213314

Fold 2 IBS: 0.25952948642752294
Fold 3 IBS: 0.177487100453673
Fold 4 IBS: 0.2822763910223109
Fold 5 IBS: 0.19609653824017242
[I 2024-04-13 17:21:54,215] Trial 25 finished with value: 0.23073350229300216 and parameters: {'l1_ratio': 0.3907387218790935}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23840827161015396
Fold 2 IBS: 0.23355936404836403
Fold 3 IBS: 0.22532134089726802
Fold 4 IBS: 0.255508907355416
Fold 5 IBS: 0.22202737809913756
[I 2024-04-13 17:21:54,756] Trial 26 finished with value: 0.2349650524020679 and parameters: {'l1_ratio': 0.1300237528586279}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.24653102709732444
Fold 2 IBS: 0.23223780537994812
Fold 3 IBS: 0.2283578731101423
Fold 4 IBS: 0.24357460867753347
Fold 5 IBS: 0.22793004138059744
[I 2024-04-13 17:21:55,015] Trial 27 finished with value: 0.23572627112910913 and parameters: {'l1_ratio': 0.016560941611969082}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23824318488831972
Fold 2 IBS: 0.2595704105161684
Fold 3 IBS: 0.17746007695580615
Fold 4 IBS: 0.2822566361306353
Fold 5 IBS: 0.19603371154298713
[I 2024-04-13 17:21:55,765] Trial 28 finished with value: 0.23071280400678332 and parameters: {'l1_ratio': 0.2323879352867463}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23862610842256465
Fold 2 IBS: 0.2597195349547512
Fold 3 IBS: 0.17756906644829723
Fold 4 IBS: 0.282256695122676
Fold 5 IBS: 0.19625604914396
[I 2024-04-13 17:21:56,337] Trial 29 finished with value: 0.2308854908184498 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2384560923014063
Fold 2 IBS: 0.25959884519610543
Fold 3 IBS: 0.17750679173345604
Fold 4 IBS: 0.2822478121417067
Fold 5 IBS: 0.1961801262509122
[I 2024-04-13 17:21:56,811] Trial 30 finished with value: 0.23079793352471736 and parameters: {'l1_ratio': 0.6348147138790865}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23822347168507343
Fold 2 IBS: 0.25967753859520465
Fold 3 IBS: 0.17740968123814693
Fold 4 IBS: 0.28218797923574673
Fold 5 IBS: 0.19604041703159916
[I 2024-04-13 17:21:57,410] Trial 31 finished with value: 0.2307078175571542 and parameters: {'l1_ratio': 0.24301949765959763}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23825145871160824
Fold 2 IBS: 0.25958261568288626
Fold 3 IBS: 0.1774109311165143
Fold 4 IBS: 0.2822308571592976
Fold 5 IBS: 0.19605973287307493
[I 2024-04-13 17:21:57,957] Trial 32 finished with value: 0.23070711910867625 and parameters: {'l1_ratio': 0.2771705397587284}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23829661972975932
Fold 2 IBS: 0.2596105036930275
Fold 3 IBS: 0.17747009980042794
Fold 4 IBS: 0.282247639232608
Fold 5 IBS: 0.19607551997689754
[I 2024-04-13 17:21:58,518] Trial 33 finished with value: 0.23074007648654407 and parameters: {'l1_ratio': 0.3424168652020052}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23823627371791842
Fold 2 IBS: 0.2595169901276311
Fold 3 IBS: 0.17747660332572063
Fold 4 IBS: 0.2823103841939179
Fold 5 IBS: 0.19605973451453435
[I 2024-04-13 17:21:59,063] Trial 34 finished with value: 0.23071999717594446 and parameters: {'l1_ratio': 0.2951976698217895}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23830234994770244
Fold 2 IBS: 0.25969124944030086
Fold 3 IBS: 0.17748512605613018
Fold 4 IBS: 0.2822405814632256
Fold 5 IBS: 0.19612690992605133
[I 2024-04-13 17:21:59,648] Trial 35 finished with value: 0.2307692433666821 and parameters: {'l1_ratio': 0.46507828503665327}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.24456205951617097
Fold 2 IBS: 0.23296442350352287
Fold 3 IBS: 0.22650174529807288
Fold 4 IBS: 0.25008183548598095
Fold 5 IBS: 0.22411546918807257
[I 2024-04-13 17:21:59,875] Trial 36 finished with value: 0.23564510659836407 and parameters: {'l1_ratio': 0.07755657280239842}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23828323507993712
Fold 2 IBS: 0.23407073541900272
Fold 3 IBS: 0.22447026354125355
Fold 4 IBS: 0.28229144825101876
Fold 5 IBS: 0.22064444428817837
[I 2024-04-13 17:22:00,282] Trial 37 finished with value: 0.2399520253158781 and parameters: {'l1_ratio': 0.17848273757304806}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2384112152469431
Fold 2 IBS: 0.25971332962157734
Fold 3 IBS: 0.1774672540959717
Fold 4 IBS: 0.2822307301040042
Fold 5 IBS: 0.1961568404689594
[I 2024-04-13 17:22:00,850] Trial 38 finished with value: 0.23079587390749112 and parameters: {'l1_ratio': 0.5638551523074651}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23826041196804346
Fold 2 IBS: 0.25967498927275817
Fold 3 IBS: 0.1775054071561385
Fold 4 IBS: 0.28225223519500087
Fold 5 IBS: 0.1960921258072252
[I 2024-04-13 17:22:01,907] Trial 39 finished with value: 0.2307570338798332 and parameters: {'l1_ratio': 0.3832648927387554}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23823284995415112
Fold 2 IBS: 0.25952800528744685
Fold 3 IBS: 0.17743415369617566
Fold 4 IBS: 0.2822016919559932
Fold 5 IBS: 0.19605223482813244
[I 2024-04-13 17:22:02,631] Trial 40 finished with value: 0.23068978714437988 and parameters: {'l1_ratio': 0.2708674623103233}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2382580791806496
Fold 2 IBS: 0.25957148194689567
Fold 3 IBS: 0.1775343676245042
Fold 4 IBS: 0.28224105314272707
Fold 5 IBS: 0.19605052762024486
[I 2024-04-13 17:22:03,245] Trial 41 finished with value: 0.23073110190300428 and parameters: {'l1_ratio': 0.27936373110641877}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23831352770817377
Fold 2 IBS: 0.2595791940922782
Fold 3 IBS: 0.17752680310613772
Fold 4 IBS: 0.28217183370706866
Fold 5 IBS: 0.19611451671678543
[I 2024-04-13 17:22:03,855] Trial 42 finished with value: 0.23074117506608877 and parameters: {'l1_ratio': 0.43790265266220185}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23822288676867945
Fold 2 IBS: 0.2596862690925872
Fold 3 IBS: 0.17744964228816754
Fold 4 IBS: 0.2823110654890714
Fold 5 IBS: 0.19604949633788746
[I 2024-04-13 17:22:04,440] Trial 43 finished with value: 0.23074387199527857 and parameters: {'l1_ratio': 0.2676447705343407}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2440202775985651
Fold 2 IBS: 0.2332225678136369
Fold 3 IBS: 0.22596017738096333
Fold 4 IBS: 0.2524617951325859
Fold 5 IBS: 0.22312996003542582
[I 2024-04-13 17:22:04,707] Trial 44 finished with value: 0.2357589555922354 and parameters: {'l1_ratio': 0.0999082078311416}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2382663833150322
Fold 2 IBS: 0.23410954388448005
Fold 3 IBS: 0.22441068489849617
Fold 4 IBS: 0.28219406126837626
Fold 5 IBS: 0.22055083783827648
[I 2024-04-13 17:22:05,082] Trial 45 finished with value: 0.23990630224093223 and parameters: {'l1_ratio': 0.1823213526207641}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23827990238175367
Fold 2 IBS: 0.25956305698327636
Fold 3 IBS: 0.1774240336211294
Fold 4 IBS: 0.2821833836997101
Fold 5 IBS: 0.19608534601621494
[I 2024-04-13 17:22:05,598] Trial 46 finished with value: 0.23070714454041688 and parameters: {'l1_ratio': 0.36287527192740016}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2450315757930325
Fold 2 IBS: 0.23276289711925324
Fold 3 IBS: 0.22696172225863143
Fold 4 IBS: 0.24822492863583584
Fold 5 IBS: 0.22499363382941687
[I 2024-04-13 17:22:05,807] Trial 47 finished with value: 0.23559495152723398 and parameters: {'l1_ratio': 0.06043968036093836}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.238424339338857
Fold 2 IBS: 0.23353886114087868
Fold 3 IBS: 0.22535828027108665
Fold 4 IBS: 0.2553264640069366
Fold 5 IBS: 0.222089513379149
[I 2024-04-13 17:22:06,076] Trial 48 finished with value: 0.23494749162738157 and parameters: {'l1_ratio': 0.12815433124902784}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23826195007559983
Fold 2 IBS: 0.2595845756336795
Fold 3 IBS: 0.17745907967140545
Fold 4 IBS: 0.2822237411480396
Fold 5 IBS: 0.1960687624745446
[I 2024-04-13 17:22:06,714] Trial 49 finished with value: 0.2307196218006538 and parameters: {'l1_ratio': 0.3040571335627061}. Best is trial 11 with value: 0.23052662675257327.

Fold 1 IBS: 0.23827868339846203
Fold 2 IBS: 0.2596821730405745
Fold 3 IBS: 0.17756293006089313
Fold 4 IBS: 0.2822444645932325
Fold 5 IBS: 0.19610579077429535
[I 2024-04-13 17:22:07,608] Trial 50 finished with value: 0.2307748083734915 and parameters: {'l1_ratio': 0.4213768319549068}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2382464870836125
Fold 2 IBS: 0.25967360063640943
Fold 3 IBS: 0.1774624054675995
Fold 4 IBS: 0.28227392623025543
Fold 5 IBS: 0.1960803495449635
[I 2024-04-13 17:22:08,588] Trial 51 finished with value: 0.23074735379256808 and parameters: {'l1_ratio': 0.34963290492960153}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23827088067211144
Fold 2 IBS: 0.2596602575419221
Fold 3 IBS: 0.1774195775513413
Fold 4 IBS: 0.2823011257998262
Fold 5 IBS: 0.19603821377613406
[I 2024-04-13 17:22:09,290] Trial 52 finished with value: 0.23073801106826702 and parameters: {'l1_ratio': 0.24071415288105377}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23828168514487272
Fold 2 IBS: 0.25956695743466374
Fold 3 IBS: 0.17742216602455352
Fold 4 IBS: 0.28218604976152584
Fold 5 IBS: 0.19608580187375024
[I 2024-04-13 17:22:09,931] Trial 53 finished with value: 0.23070853204787323 and parameters: {'l1_ratio': 0.36360752022547593}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.238294733249048
Fold 2 IBS: 0.2596788452199852
Fold 3 IBS: 0.17746088574091626
Fold 4 IBS: 0.28220408359220717
Fold 5 IBS: 0.19602907521941607
[I 2024-04-13 17:22:10,593] Trial 54 finished with value: 0.23073352460431457 and parameters: {'l1_ratio': 0.20238121759682073}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23833681649196628
Fold 2 IBS: 0.2337585965176437
Fold 3 IBS: 0.22497430342023567
Fold 4 IBS: 0.2823029694310131
Fold 5 IBS: 0.22145258665923265
[I 2024-04-13 17:22:11,083] Trial 55 finished with value: 0.2401650545040183 and parameters: {'l1_ratio': 0.14846548743335022}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2382375305544653
Fold 2 IBS: 0.2596794430127953
Fold 3 IBS: 0.17753747945649379
Fold 4 IBS: 0.2822883273978336
Fold 5 IBS: 0.19607053477987552
[I 2024-04-13 17:22:11,835] Trial 56 finished with value: 0.23076266304029272 and parameters: {'l1_ratio': 0.32016422260450667}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23822500690154738
Fold 2 IBS: 0.25969053274951925
Fold 3 IBS: 0.17744719736067155
Fold 4 IBS: 0.28218892166855203
Fold 5 IBS: 0.1960500404872928
[I 2024-04-13 17:22:12,411] Trial 57 finished with value: 0.2307203398335166 and parameters: {'l1_ratio': 0.26827959112701677}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23825488018261387
Fold 2 IBS: 0.25956696074880387
Fold 3 IBS: 0.17743582076443523
Fold 4 IBS: 0.28224369402571314
Fold 5 IBS: 0.19602282007151944
[I 2024-04-13 17:22:13,011] Trial 58 finished with value: 0.23070483515861712 and parameters: {'l1_ratio': 0.2087143524863812}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.24586559310323913
Fold 2 IBS: 0.2324504640062385
Fold 3 IBS: 0.227752867843992
Fold 4 IBS: 0.24540655296382105
Fold 5 IBS: 0.22660356529882444
[I 2024-04-13 17:22:13,264] Trial 59 finished with value: 0.23561580864322304 and parameters: {'l1_ratio': 0.03427351944073184}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23839959180655976
Fold 2 IBS: 0.23379118611429014
Fold 3 IBS: 0.22491950275409414
Fold 4 IBS: 0.2822047539210434
Fold 5 IBS: 0.22136324694740747
[I 2024-04-13 17:22:13,692] Trial 60 finished with value: 0.240135656308679 and parameters: {'l1_ratio': 0.15153237667790176}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23829908507870515
Fold 2 IBS: 0.25967281476342735
Fold 3 IBS: 0.17746462759688814
Fold 4 IBS: 0.2821996013411701
Fold 5 IBS: 0.19602831243051622
[I 2024-04-13 17:22:14,288] Trial 61 finished with value: 0.2307328882421414 and parameters: {'l1_ratio': 0.20170394643611322}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23823797821296822
Fold 2 IBS: 0.2595574842786361
Fold 3 IBS: 0.17750565321773304
Fold 4 IBS: 0.2822292957171656
Fold 5 IBS: 0.1960499933526478
[I 2024-04-13 17:22:15,029] Trial 62 finished with value: 0.23071608095583013 and parameters: {'l1_ratio': 0.25091898395551493}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23860160296607877
Fold 2 IBS: 0.25972354404157494
Fold 3 IBS: 0.17763927082582362
Fold 4 IBS: 0.2822769776416314
Fold 5 IBS: 0.1962359284651879
[I 2024-04-13 17:22:15,652] Trial 63 finished with value: 0.23089546478805936 and parameters: {'l1_ratio': 0.8104603968178263}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23825021097965876
Fold 2 IBS: 0.2596788485984968
Fold 3 IBS: 0.1774952564073126
Fold 4 IBS: 0.28220087573373853
Fold 5 IBS: 0.1960363661609839
[I 2024-04-13 17:22:16,245] Trial 64 finished with value: 0.2307323115760381 and parameters: {'l1_ratio': 0.22252929097646643}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23828227494434698
Fold 2 IBS: 0.2596032755877773
Fold 3 IBS: 0.17743246522576295
Fold 4 IBS: 0.28225310254930097
Fold 5 IBS: 0.1960640636706385
[I 2024-04-13 17:22:16,853] Trial 65 finished with value: 0.23072703639556535 and parameters: {'l1_ratio': 0.3113178298133137}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23831875493684893
Fold 2 IBS: 0.2340198537048159
Fold 3 IBS: 0.22454936926937621
Fold 4 IBS: 0.28225512595481783
Fold 5 IBS: 0.22076933099683768
[I 2024-04-13 17:22:17,324] Trial 66 finished with value: 0.23998248697253932 and parameters: {'l1_ratio': 0.1734873563393906}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2384038627871801
Fold 2 IBS: 0.2334595686142334
Fold 3 IBS: 0.2255034117230987
Fold 4 IBS: 0.2546166376216724
Fold 5 IBS: 0.22233549248886197
[I 2024-04-13 17:22:17,685] Trial 67 finished with value: 0.23486379464700935 and parameters: {'l1_ratio': 0.1209712072559032}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23824765185435012
Fold 2 IBS: 0.2595840037333315
Fold 3 IBS: 0.1774113460493227
Fold 4 IBS: 0.2822728756180611
Fold 5 IBS: 0.196024334056087
[I 2024-04-13 17:22:18,423] Trial 68 finished with value: 0.23070804226223046 and parameters: {'l1_ratio': 0.21350339416514866}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23838090413223822
Fold 2 IBS: 0.25968781642098754
Fold 3 IBS: 0.1775419381827875
Fold 4 IBS: 0.28223013898602517
Fold 5 IBS: 0.19613827800029415
[I 2024-04-13 17:22:19,055] Trial 69 finished with value: 0.2307958151444665 and parameters: {'l1_ratio': 0.5081502795228482}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2382887040431639
Fold 2 IBS: 0.259696575114081
Fold 3 IBS: 0.17755252975403274
Fold 4 IBS: 0.2822581960435861
Fold 5 IBS: 0.19610829910083222
[I 2024-04-13 17:22:19,652] Trial 70 finished with value: 0.2307808608111392 and parameters: {'l1_ratio': 0.42601015876688964}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2382730756994312
Fold 2 IBS: 0.259638273343699
Fold 3 IBS: 0.177458878130806
Fold 4 IBS: 0.2822854186483169
Fold 5 IBS: 0.1960446647316661
[I 2024-04-13 17:22:20,342] Trial 71 finished with value: 0.23074006211078385 and parameters: {'l1_ratio': 0.2621754712465273}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23827318215359342
Fold 2 IBS: 0.2596657131208537
Fold 3 IBS: 0.17741645335050807
Fold 4 IBS: 0.28230485258533744
Fold 5 IBS: 0.1960389091025016
[I 2024-04-13 17:22:20,980] Trial 72 finished with value: 0.23073982206255886 and parameters: {'l1_ratio': 0.24143741350834794}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23829199162258888
Fold 2 IBS: 0.25957334542448113
Fold 3 IBS: 0.1775446572252669
Fold 4 IBS: 0.2822068983352747
Fold 5 IBS: 0.19608848398332152
[I 2024-04-13 17:22:21,605] Trial 73 finished with value: 0.2307410753181866 and parameters: {'l1_ratio': 0.3678947938408584}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23826248118835852
Fold 2 IBS: 0.2595514958501382
Fold 3 IBS: 0.17750893568952494
Fold 4 IBS: 0.28219786020975113
Fold 5 IBS: 0.19607342114250242
[I 2024-04-13 17:22:22,226] Trial 74 finished with value: 0.23071883881605504 and parameters: {'l1_ratio': 0.32924392494574417}. Best is trial 11 with value: 0.23052662675257327.

Fold 1 IBS: 0.2382502485563302
Fold 2 IBS: 0.2595485996036999
Fold 3 IBS: 0.17746018132291239
Fold 4 IBS: 0.2822062570392265
Fold 5 IBS: 0.1960634245460156
[I 2024-04-13 17:22:22,908] Trial 75 finished with value: 0.23070574221363693 and parameters: {'l1_ratio': 0.30001813220952506}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23822428734846307
Fold 2 IBS: 0.25967158095524584
Fold 3 IBS: 0.17749156392799154
Fold 4 IBS: 0.2822924257486092
Fold 5 IBS: 0.1960563339011874
[I 2024-04-13 17:22:23,537] Trial 76 finished with value: 0.2307472383762994 and parameters: {'l1_ratio': 0.2909349888639582}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2383174526414789
Fold 2 IBS: 0.2340216951026572
Fold 3 IBS: 0.22454648654604933
Fold 4 IBS: 0.2822564696089534
Fold 5 IBS: 0.22076476775707285
[I 2024-04-13 17:22:23,930] Trial 77 finished with value: 0.2399813743312423 and parameters: {'l1_ratio': 0.17366740919648238}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2382903433024643
Fold 2 IBS: 0.2596671603914918
Fold 3 IBS: 0.17749407873652623
Fold 4 IBS: 0.2822894071617963
Fold 5 IBS: 0.19605577033448687
[I 2024-04-13 17:22:24,650] Trial 78 finished with value: 0.2307593519853531 and parameters: {'l1_ratio': 0.2902299664320334}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23870351696602685
Fold 2 IBS: 0.2597590816455321
Fold 3 IBS: 0.17749836645096384
Fold 4 IBS: 0.2822542164730236
Fold 5 IBS: 0.1962877085139332
[I 2024-04-13 17:22:25,197] Trial 79 finished with value: 0.2309005780098959 and parameters: {'l1_ratio': 0.9846333768922103}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.2382769108668134
Fold 2 IBS: 0.25952711557653596
Fold 3 IBS: 0.17748822876610543
Fold 4 IBS: 0.282274902011681
Fold 5 IBS: 0.19609626602283745
[I 2024-04-13 17:22:25,761] Trial 80 finished with value: 0.23073268464879462 and parameters: {'l1_ratio': 0.3902700180909926}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23823984706839887
Fold 2 IBS: 0.2595181643095513
Fold 3 IBS: 0.17748650907286578
Fold 4 IBS: 0.2822113572003521
Fold 5 IBS: 0.19603815122046894
[I 2024-04-13 17:22:26,396] Trial 81 finished with value: 0.23069880577432741 and parameters: {'l1_ratio': 0.22429069761903586}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23825247060563567
Fold 2 IBS: 0.2596211849474185
Fold 3 IBS: 0.17752785265773713
Fold 4 IBS: 0.28228871393082855
Fold 5 IBS: 0.19602732617229335
[I 2024-04-13 17:22:26,966] Trial 82 finished with value: 0.23074350966278265 and parameters: {'l1_ratio': 0.2161910150719893}. Best is trial 11 with value: 0.23052662675257327.
Fold 1 IBS: 0.23828875697684615
Fold 2 IBS: 0.23418883088811007
Fold 3 IBS: 0.177402122053757
Fold 4 IBS: 0.28224933926828205
Fold 5 IBS: 0.1960160748970222
[I 2024-04-13 17:22:27,500] Trial 83 finished with value: 0.2256290248168035 and parameters: {'l1_ratio': 0.19024288598618477}. Best is trial 83 with value: 0.2256290248168035.
Fold 1 IBS: 0.2440459256930621
Fold 2 IBS: 0.23320969728351543
Fold 3 IBS: 0.2259860340294181
Fold 4 IBS: 0.25234367205772823
Fold 5 IBS: 0.22317590045800728
[I 2024-04-13 17:22:27,797] Trial 84 finished with value: 0.23575224590434624 and parameters: {'l1_ratio': 0.09878034756331294}. Best is trial 83 with value: 0.2256290248168035.
Fold 1 IBS: 0.2383006089142088
Fold 2 IBS: 0.23417127557415163
Fold 3 IBS: 0.17741230437668923
Fold 4 IBS: 0.28223720269500263
Fold 5 IBS: 0.19601388013455798
[I 2024-04-13 17:22:28,334] Trial 85 finished with value: 0.22562705433892205 and parameters: {'l1_ratio': 0.18847962263376228}. Best is trial 85 with value: 0.22562705433892205.
Fold 1 IBS: 0.23830684554088327
Fold 2 IBS: 0.2341620969960407
Fold 3 IBS: 0.17741768805823716
Fold 4 IBS: 0.2822307860072465
Fold 5 IBS: 0.19602665604739247
[I 2024-04-13 17:22:28,892] Trial 86 finished with value: 0.22562881452996003 and parameters: {'l1_ratio': 0.18755985158472394}. Best is trial 85 with value: 0.22562705433892205.
Fold 1 IBS: 0.2383713602678578
Fold 2 IBS: 0.23382776608092645
Fold 3 IBS: 0.22485862065315657
Fold 4 IBS: 0.28223479755022685
Fold 5 IBS: 0.22126443049897626
[I 2024-04-13 17:22:29,276] Trial 87 finished with value: 0.2401113950102288 and parameters: {'l1_ratio': 0.15499256311359408}. Best is trial 85 with value: 0.22562705433892205.
Fold 1 IBS: 0.244571163491602
Fold 2 IBS: 0.2329603258117732
Fold 3 IBS: 0.22651075361652342
Fold 4 IBS: 0.2500439785184719
Fold 5 IBS: 0.22413229104993382
[I 2024-04-13 17:22:29,525] Trial 88 finished with value: 0.2356437024976609 and parameters: {'l1_ratio': 0.07720595475575143}. Best is trial 85 with value: 0.22562705433892205.
Fold 1 IBS: 0.23830105012634853
Fold 2 IBS: 0.23417062489637996
Fold 3 IBS: 0.1774126846636031
Fold 4 IBS: 0.2822367494337344
Fold 5 IBS: 0.19601379733668595
[I 2024-04-13 17:22:30,063] Trial 89 finished with value: 0.22562698129135036 and parameters: {'l1_ratio': 0.18841437122569446}. Best is trial 89 with value: 0.22562698129135036.
Fold 1 IBS: 0.2384183476399384
Fold 2 IBS: 0.23354576604972327
Fold 3 IBS: 0.22534581339731838
Fold 4 IBS: 0.2553879592228015
Fold 5 IBS: 0.22206852185239961
[I 2024-04-13 17:22:30,347] Trial 90 finished with value: 0.23495328163243623 and parameters: {'l1_ratio': 0.12878334502439942}. Best is trial 89 with value: 0.22562698129135036.
Fold 1 IBS: 0.23825878525948455
Fold 2 IBS: 0.2596546524821176
Fold 3 IBS: 0.1774758963436283
Fold 4 IBS: 0.282310891578555
Fold 5 IBS: 0.19602365800661248
[I 2024-04-13 17:22:31,104] Trial 91 finished with value: 0.23074477673407962 and parameters: {'l1_ratio': 0.1996901076359157}. Best is trial 89 with value: 0.22562698129135036.
Fold 1 IBS: 0.23827895374779864
Fold 2 IBS: 0.234076962041264
Fold 3 IBS: 0.22446066072779772
Fold 4 IBS: 0.2822957812603086
Fold 5 IBS: 0.22062933088602982
[I 2024-04-13 17:22:31,532] Trial 92 finished with value: 0.23994833773263977 and parameters: {'l1_ratio': 0.17909694344985752}. Best is trial 89 with value: 0.22562698129135036.
Fold 1 IBS: 0.2382363974654644
Fold 2 IBS: 0.2595455834944431
Fold 3 IBS: 0.17747096272098573
Fold 4 IBS: 0.2822290074721146
Fold 5 IBS: 0.196041326899436
[I 2024-04-13 17:22:32,156] Trial 93 finished with value: 0.2307046556104888 and parameters: {'l1_ratio': 0.22748753841579025}. Best is trial 89 with value: 0.22562698129135036.
Fold 1 IBS: 0.2382370605736805
Fold 2 IBS: 0.2595587078898
Fold 3 IBS: 0.17746352172293553
Fold 4 IBS: 0.28223793008880294
Fold 5 IBS: 0.19603028815811466
[I 2024-04-13 17:22:32,768] Trial 94 finished with value: 0.23070550168666673 and parameters: {'l1_ratio': 0.22904851448580726}. Best is trial 89 with value: 0.22562698129135036.
Fold 1 IBS: 0.23829046604852439
Fold 2 IBS: 0.23418629022092435
Fold 3 IBS: 0.17740358644893975
Fold 4 IBS: 0.2822475937781621
Fold 5 IBS: 0.19601577905624662
[I 2024-04-13 17:22:33,247] Trial 95 finished with value: 0.22562874311055942 and parameters: {'l1_ratio': 0.18998736785279743}. Best is trial 89 with value: 0.22562698129135036.
Fold 1 IBS: 0.23837179959706578
Fold 2 IBS: 0.23371181881040734
Fold 3 IBS: 0.22505390257312657
Fold 4 IBS: 0.2568497305735669
Fold 5 IBS: 0.221583030985924
[I 2024-04-13 17:22:33,581] Trial 96 finished with value: 0.2351140565080181 and parameters: {'l1_ratio': 0.14408889259090077}. Best is trial 89 with value: 0.22562698129135036.
Fold 1 IBS: 0.23833745314860671
Fold 2 IBS: 0.23411763249050704
Fold 3 IBS: 0.17744437029047816
Fold 4 IBS: 0.28219997351776366
Fold 5 IBS: 0.22053150347455958
[I 2024-04-13 17:22:34,058] Trial 97 finished with value: 0.230526186584383 and parameters: {'l1_ratio': 0.18312457612701535}. Best is trial 89 with value: 0.22562698129135036.
Fold 1 IBS: 0.24416026974246688
Fold 2 IBS: 0.23315311824155785
Fold 3 IBS: 0.22610106752420508
Fold 4 IBS: 0.25182345629762026
Fold 5 IBS: 0.22338159719364972
[I 2024-04-13 17:22:34,297] Trial 98 finished with value: 0.23572390179989994 and parameters: {'l1_ratio': 0.09384008436653912}. Best is trial 89 with value: 0.22562698129135036.
Fold 1 IBS: 0.24527405804087385
Fold 2 IBS: 0.23266632429669107
Fold 3 IBS: 0.22719533269311562
Fold 4 IBS: 0.2473426739078257
Fold 5 IBS: 0.22545533809046342
[I 2024-04-13 17:22:34,504] Trial 99 finished with value: 0.2355867454057939 and parameters: {'l1_ratio': 0.05231480035751657}. Best is trial 89 with value: 0.22562698129135036.


* Best trial for IBS:
 FrozenTrial(number=89, state=TrialState.COMPLETE, values=[0.22562698129135036], datetime_start=datetime.datetime(2024, 4, 13, 17, 22, 29, 531272), datetime_complete=datetime.datetime(2024, 4, 13, 17, 22, 30, 62918), params={'l1_ratio': 0.18841437122569446}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=89, value=None)


* Best Score for IBS:
 0.22562698129135036

In [68]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [69]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.638
train_ibs:  0.226

#### Test

In [70]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [71]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.28621072101688444)

test_cindex : 0.532

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.18841437122569446)

test_ibs:  0.234

In [72]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [73]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:22:34,860] A new study created in memory with name: no-name-a861b805-48a7-405b-9456-93fee82b8251

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.575107296137339
[I 2024-04-13 17:22:39,450] Trial 0 finished with value: 0.6177885807850675 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6177885807850675.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:22:43,040] Trial 1 finished with value: 0.6402989429173871 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.6402989429173871.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.6008583690987125
[I 2024-04-13 17:22:46,762] Trial 2 finished with value: 0.6393357242915708 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.6402989429173871.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:22:47,920] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.6402989429173871.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:22:49,540] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.6402989429173871.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 17:22:54,462] Trial 5 finished with value: 0.6471658831186169 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6863117870722434
Fold 5 C-index: 0.6115879828326181
[I 2024-04-13 17:22:59,801] Trial 6 finished with value: 0.6344921146735147 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:23:02,314] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:23:09,196] Trial 8 finished with value: 0.5180257510729614 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.5968992248062015
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.5944206008583691
[I 2024-04-13 17:23:13,051] Trial 9 finished with value: 0.6262562593650948 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:23:13,496] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.6673003802281369
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 17:23:15,432] Trial 11 finished with value: 0.640537452234508 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11629432582260082, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.647410358565737
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.674468085106383
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6158798283261803
[I 2024-04-13 17:23:16,893] Trial 12 finished with value: 0.6472725256821195 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.8064195611120726, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10227389828304193, 'warm_start': False}. Best is trial 12 with value: 0.6472725256821195.
Fold 1 C-index: 0.6354581673306773
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.575107296137339
[I 2024-04-13 17:23:17,154] Trial 13 finished with value: 0.6354800902960902 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 7, 'oob_score': False, 'max_samples': 0.4941394758404661, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.008606277463368957, 'warm_start': False}. Best is trial 12 with value: 0.6472725256821195.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 17:23:18,096] Trial 14 finished with value: 0.7002369632470599 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 120, 'oob_score': True, 'max_samples': 0.8364130211722378, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10429920715486261, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6453488372093024

Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:23:19,144] Trial 15 finished with value: 0.6757811535432272 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 120, 'oob_score': True, 'max_samples': 0.9847369290686088, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17574628605071868, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 17:23:20,399] Trial 16 finished with value: 0.6771580986582885 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.962365055520953, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19037781478052387, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.6416309012875536
[I 2024-04-13 17:23:21,759] Trial 17 finished with value: 0.6714707475493069 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 180, 'oob_score': True, 'max_samples': 0.8699768148803853, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20705158222188405, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6195219123505976
Fold 2 C-index: 0.6414728682170543
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:23:22,332] Trial 18 finished with value: 0.6567223411334931 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 58, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.7425531914893617
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6373390557939914
[I 2024-04-13 17:23:23,446] Trial 19 finished with value: 0.671915912796344 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 153, 'oob_score': True, 'max_samples': 0.7093777033655436, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07770947342327489, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6195219123505976
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6502145922746781
[I 2024-04-13 17:23:24,159] Trial 20 finished with value: 0.68201262766852 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 89, 'oob_score': True, 'max_samples': 0.8574334183065578, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16825759122066408, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7425531914893617
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6459227467811158
[I 2024-04-13 17:23:25,248] Trial 21 finished with value: 0.6828780051799364 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 65, 'oob_score': True, 'max_samples': 0.8574739496774684, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1580984841046789, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 17:23:26,040] Trial 22 finished with value: 0.6954786045995129 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 67, 'oob_score': True, 'max_samples': 0.8339758748294697, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14609188473654175, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6824034334763949
[I 2024-04-13 17:23:26,405] Trial 23 finished with value: 0.6999767612780623 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 21, 'oob_score': True, 'max_samples': 0.7847143847565936, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13226034227314248, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6872340425531915
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6545064377682404
[I 2024-04-13 17:23:26,738] Trial 24 finished with value: 0.6577607816323275 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.7775916898124314, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.25150584936274806, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6545064377682404
[I 2024-04-13 17:23:27,131] Trial 25 finished with value: 0.6783623065010328 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 33, 'oob_score': True, 'max_samples': 0.6669213410828165, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13486370381501434, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6974248927038627
[I 2024-04-13 17:23:28,051] Trial 26 finished with value: 0.7005252977723723 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 91, 'oob_score': True, 'max_samples': 0.5349306463888053, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06566365555656244, 'warm_start': True}. Best is trial 26 with value: 0.7005252977723723.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7124463519313304
[I 2024-04-13 17:23:29,120] Trial 27 finished with value: 0.7061005790200177 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 90, 'oob_score': True, 'max_samples': 0.5366581083873809, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06208957998994368, 'warm_start': True}. Best is trial 27 with value: 0.7061005790200177.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6845493562231759
[I 2024-04-13 17:23:31,157] Trial 28 finished with value: 0.6887400143879626 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 224, 'oob_score': True, 'max_samples': 0.41379803894855116, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07805190635410612, 'warm_start': True}. Best is trial 27 with value: 0.7061005790200177.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.7253218884120172
[I 2024-04-13 17:23:32,473] Trial 29 finished with value: 0.7116053815973882 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 164, 'oob_score': True, 'max_samples': 0.5248192039443108, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0554252254423035, 'warm_start': True}. Best is trial 29 with value: 0.7116053815973882.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 17:23:33,709] Trial 30 finished with value: 0.7010446660346952 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 169, 'oob_score': True, 'max_samples': 0.5345414788093061, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03755841239520112, 'warm_start': True}. Best is trial 29 with value: 0.7116053815973882.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.7017167381974249
[I 2024-04-13 17:23:34,958] Trial 31 finished with value: 0.7000756268928836 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 171, 'oob_score': True, 'max_samples': 0.5019192620095752, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.050771418210883164, 'warm_start': True}. Best is trial 29 with value: 0.7116053815973882.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 17:23:36,398] Trial 32 finished with value: 0.7177295061567273 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 223, 'oob_score': True, 'max_samples': 0.563642711374241, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05266275392679234, 'warm_start': True}. Best is trial 32 with value: 0.7177295061567273.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 17:23:38,004] Trial 33 finished with value: 0.7049756930439305 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 234, 'oob_score': True, 'max_samples': 0.35232498791610145, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00379084860293024, 'warm_start': True}. Best is trial 32 with value: 0.7177295061567273.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.703862660944206
[I 2024-04-13 17:23:39,874] Trial 34 finished with value: 0.7010699790361788 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.3828093578201666, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0026062845432726807, 'warm_start': True}. Best is trial 32 with value: 0.7177295061567273.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.7042553191489361
Fold 4 C-index: 0.6825095057034221
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:23:41,910] Trial 35 finished with value: 0.6556598127697459 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 212, 'oob_score': True, 'max_samples': 0.26793001302903535, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0862146443224848, 'warm_start': True}. Best is trial 32 with value: 0.7177295061567273.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 17:23:45,033] Trial 36 finished with value: 0.7288309903966594 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 341, 'oob_score': True, 'max_samples': 0.3445095149903548, 'max_features': None, 'min_weight_fraction_leaf': 0.00052334394504433, 'warm_start': True}. Best is trial 36 with value: 0.7288309903966594.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8369098712446352
[I 2024-04-13 17:23:48,088] Trial 37 finished with value: 0.7549756456347672 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.5874006073245895, 'max_features': None, 'min_weight_fraction_leaf': 0.051378997578725064, 'warm_start': True}. Best is trial 37 with value: 0.7549756456347672.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7982832618025751
[I 2024-04-13 17:23:51,044] Trial 38 finished with value: 0.7411193039013269 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 378, 'oob_score': True, 'max_samples': 0.42872870036644545, 'max_features': None, 'min_weight_fraction_leaf': 0.03685839885089406, 'warm_start': True}. Best is trial 37 with value: 0.7549756456347672.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:23:54,083] Trial 39 finished with value: 0.7764777161516213 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.5898221765815288, 'max_features': None, 'min_weight_fraction_leaf': 0.0280794008099322, 'warm_start': True}. Best is trial 39 with value: 0.7764777161516213.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.8154506437768241
[I 2024-04-13 17:23:57,506] Trial 40 finished with value: 0.7453537247989861 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.44424040796819986, 'max_features': None, 'min_weight_fraction_leaf': 0.029813810847214628, 'warm_start': True}. Best is trial 39 with value: 0.7764777161516213.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 17:24:00,092] Trial 41 finished with value: 0.767706324749998 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.42993466896213306, 'max_features': None, 'min_weight_fraction_leaf': 0.02699423331352132, 'warm_start': True}. Best is trial 39 with value: 0.7764777161516213.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8369098712446352
[I 2024-04-13 17:24:03,235] Trial 42 finished with value: 0.7558493030880561 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.43835115795914964, 'max_features': None, 'min_weight_fraction_leaf': 0.03261747288898426, 'warm_start': True}. Best is trial 39 with value: 0.7764777161516213.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.871244635193133
[I 2024-04-13 17:24:06,734] Trial 43 finished with value: 0.7805052982197098 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.6182013697142779, 'max_features': None, 'min_weight_fraction_leaf': 0.02680908937928254, 'warm_start': True}. Best is trial 43 with value: 0.7805052982197098.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7893617021276595
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7467811158798283
[I 2024-04-13 17:24:10,479] Trial 44 finished with value: 0.7199270020227763 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 478, 'oob_score': True, 'max_samples': 0.6260162353120974, 'max_features': None, 'min_weight_fraction_leaf': 0.09652293104879651, 'warm_start': True}. Best is trial 43 with value: 0.7805052982197098.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:24:12,511] Trial 45 finished with value: 0.7876297777014609 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.6932069026339767, 'max_features': None, 'min_weight_fraction_leaf': 0.02673421337104168, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.5858369098712446
[I 2024-04-13 17:24:20,713] Trial 46 finished with value: 0.6175266138918902 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 421, 'oob_score': False, 'max_samples': 0.713175685335591, 'max_features': None, 'min_weight_fraction_leaf': 0.02263809195586287, 'warm_start': False}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 17:24:22,857] Trial 47 finished with value: 0.7024716099360828 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.6640283145362862, 'max_features': None, 'min_weight_fraction_leaf': 0.11937729206282155, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:24:28,456] Trial 48 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.4725841795598701, 'max_features': None, 'min_weight_fraction_leaf': 0.38812198780775825, 'warm_start': False}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:24:30,526] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.2076878129262199, 'max_features': None, 'min_weight_fraction_leaf': 0.4820963556426466, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.6492248062015504
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.6825095057034221
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 17:24:32,490] Trial 50 finished with value: 0.649042644861519 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.679318106876105, 'max_features': None, 'min_weight_fraction_leaf': 0.2758707435072836, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 17:24:34,323] Trial 51 finished with value: 0.7637338414488053 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 394, 'oob_score': False, 'max_samples': 0.5821155504207499, 'max_features': None, 'min_weight_fraction_leaf': 0.02422764197259524, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 17:24:36,581] Trial 52 finished with value: 0.7637338414488053 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.5780114655400654, 'max_features': None, 'min_weight_fraction_leaf': 0.019612908407631094, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.759656652360515
[I 2024-04-13 17:24:39,601] Trial 53 finished with value: 0.7330142244474321 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 445, 'oob_score': False, 'max_samples': 0.58647202928343, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.014895484544909543, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 17:24:41,796] Trial 54 finished with value: 0.7502209765566825 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.7451532491332802, 'max_features': None, 'min_weight_fraction_leaf': 0.08067250770106202, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8583690987124464
[I 2024-04-13 17:24:43,181] Trial 55 finished with value: 0.7747108750614803 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.6202755843283627, 'max_features': None, 'min_weight_fraction_leaf': 0.022470717574527028, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.6007751937984496
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.5836909871244635
[I 2024-04-13 17:24:47,866] Trial 56 finished with value: 0.617244798143204 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.6429003803329312, 'max_features': None, 'min_weight_fraction_leaf': 0.22757335863523978, 'warm_start': False}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8326180257510729
[I 2024-04-13 17:24:49,079] Trial 57 finished with value: 0.7539260229172815 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 267, 'oob_score': False, 'max_samples': 0.6226007657277326, 'max_features': None, 'min_weight_fraction_leaf': 0.038788044099769756, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 17:24:50,636] Trial 58 finished with value: 0.7099977128256824 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 361, 'oob_score': False, 'max_samples': 0.6932738670326789, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10056372049643875, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8454935622317596
[I 2024-04-13 17:24:52,230] Trial 59 finished with value: 0.7596304057836407 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 290, 'oob_score': False, 'max_samples': 0.7323761414424763, 'max_features': None, 'min_weight_fraction_leaf': 0.06672040150433087, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6234042553191489
Fold 4 C-index: 0.6977186311787072
Fold 5 C-index: 0.5815450643776824
[I 2024-04-13 17:25:00,627] Trial 60 finished with value: 0.6241729860798608 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.4903074221697629, 'max_features': None, 'min_weight_fraction_leaf': 0.11959785503226739, 'warm_start': False}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:25:02,471] Trial 61 finished with value: 0.7804185419955325 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.5775531242934729, 'max_features': None, 'min_weight_fraction_leaf': 0.014771588904444915, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:25:04,354] Trial 62 finished with value: 0.7818313762245508 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 430, 'oob_score': False, 'max_samples': 0.6120312661504053, 'max_features': None, 'min_weight_fraction_leaf': 0.01656914948618143, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8583690987124464
[I 2024-04-13 17:25:06,229] Trial 63 finished with value: 0.7763007762144775 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 433, 'oob_score': False, 'max_samples': 0.6357815970769084, 'max_features': None, 'min_weight_fraction_leaf': 0.04354887768929718, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8454935622317596
[I 2024-04-13 17:25:08,240] Trial 64 finished with value: 0.7579098162543703 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 429, 'oob_score': False, 'max_samples': 0.6127459487402497, 'max_features': None, 'min_weight_fraction_leaf': 0.04650833605121199, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8283261802575107
[I 2024-04-13 17:25:10,349] Trial 65 finished with value: 0.7444188242864717 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.6523889675617967, 'max_features': None, 'min_weight_fraction_leaf': 0.06842934943082835, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:25:12,815] Trial 66 finished with value: 0.7867565440912282 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 434, 'oob_score': False, 'max_samples': 0.6881590145066517, 'max_features': None, 'min_weight_fraction_leaf': 0.011806153077869749, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8798283261802575
[I 2024-04-13 17:25:15,385] Trial 67 finished with value: 0.7896209612521833 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 433, 'oob_score': False, 'max_samples': 0.7631123974277301, 'max_features': None, 'min_weight_fraction_leaf': 0.0022885590177692122, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:25:17,521] Trial 68 finished with value: 0.7837247575028984 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 459, 'oob_score': False, 'max_samples': 0.7615347181121479, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0024769456224402846, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8583690987124464
[I 2024-04-13 17:25:19,720] Trial 69 finished with value: 0.7778975587933437 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 417, 'oob_score': False, 'max_samples': 0.7726300856584892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01088116997697249, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:25:21,869] Trial 70 finished with value: 0.7838043518792469 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.9016742863309287, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.007729052885137196, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.871244635193133
[I 2024-04-13 17:25:23,877] Trial 71 finished with value: 0.7838875271795097 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.9017461575502412, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0068241563825637295, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:25:26,331] Trial 72 finished with value: 0.7790161865505592 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 495, 'oob_score': False, 'max_samples': 0.9009406869567084, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0021418267435436436, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.871244635193133
[I 2024-04-13 17:25:28,387] Trial 73 finished with value: 0.7830148443991681 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 456, 'oob_score': False, 'max_samples': 0.9085841532130327, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0030802629542528654, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8755364806866953
[I 2024-04-13 17:25:30,780] Trial 74 finished with value: 0.7831886272554539 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 455, 'oob_score': False, 'max_samples': 0.9228420326396749, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.005019150622141426, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:25:32,924] Trial 75 finished with value: 0.7757963034243145 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.9457439444265902, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0018763322411427912, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8111587982832618
[I 2024-04-13 17:25:35,280] Trial 76 finished with value: 0.7417173037889626 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'max_samples': 0.8983343226238335, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06474782967395624, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:25:37,643] Trial 77 finished with value: 0.7632234783399822 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 459, 'oob_score': False, 'max_samples': 0.8332435855398501, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.048186815269347504, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:25:39,694] Trial 78 finished with value: 0.7813702683223316 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.9259409338032202, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0014115169159075848, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6414728682170543
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 17:25:41,981] Trial 79 finished with value: 0.6518913485226081 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.8671236023505134, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.34696749792453063, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.5852713178294574
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 17:25:50,103] Trial 80 finished with value: 0.6287361870740857 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.7963493279897067, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03726915892555499, 'warm_start': False}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:25:51,904] Trial 81 finished with value: 0.7898421579172852 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 435, 'oob_score': False, 'max_samples': 0.9937352645069003, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.014733302673387358, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:25:53,733] Trial 82 finished with value: 0.787557081185243 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 441, 'oob_score': False, 'max_samples': 0.9926689295251143, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012807159371837533, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:25:56,085] Trial 83 finished with value: 0.7827942427178591 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 441, 'oob_score': False, 'max_samples': 0.9750237459208526, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01606804819012205, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8111587982832618
[I 2024-04-13 17:25:58,081] Trial 84 finished with value: 0.7401126651112803 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 364, 'oob_score': False, 'max_samples': 0.9913824226489636, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08946868256617803, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8454935622317596
[I 2024-04-13 17:26:01,007] Trial 85 finished with value: 0.7636828908699766 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 419, 'oob_score': False, 'max_samples': 0.9447103169089868, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0557070761228824, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:26:04,037] Trial 86 finished with value: 0.7779481019633775 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 486, 'oob_score': False, 'max_samples': 0.9606973339596948, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03905413442222396, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7382978723404255
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.6759656652360515
[I 2024-04-13 17:26:06,418] Trial 87 finished with value: 0.6830016680735692 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.883088751579364, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0725768406343007, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8583690987124464
[I 2024-04-13 17:26:08,430] Trial 88 finished with value: 0.7756663092990286 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.8207971016698734, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012051717505267413, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8540772532188842
[I 2024-04-13 17:26:10,612] Trial 89 finished with value: 0.7675503095124208 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.9996188810038052, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.030894883442076228, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.

Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.8111587982832618
[I 2024-04-13 17:26:13,473] Trial 90 finished with value: 0.7444043407354559 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 413, 'oob_score': False, 'max_samples': 0.7655917999374031, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.059853014276037855, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8798283261802575
[I 2024-04-13 17:26:17,212] Trial 91 finished with value: 0.7880273357541754 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.8546671993080971, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00043463511590633407, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7723404255319148
Fold 4 C-index: 0.7433460076045627
Fold 5 C-index: 0.703862660944206
[I 2024-04-13 17:26:20,101] Trial 92 finished with value: 0.7014810841424285 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 470, 'oob_score': False, 'max_samples': 0.9327128334728044, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.013208403993555372, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:26:24,157] Trial 93 finished with value: 0.7802990266542915 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.8426290761275549, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.030993362135028464, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8540772532188842
[I 2024-04-13 17:26:26,928] Trial 94 finished with value: 0.7714547788810922 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 392, 'oob_score': False, 'max_samples': 0.9169001665130876, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04427068760850137, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:26:29,966] Trial 95 finished with value: 0.7826429100639786 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 464, 'oob_score': False, 'max_samples': 0.9695736653081121, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02200415575270175, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.6394422310756972
Fold 2 C-index: 0.6647286821705426
Fold 3 C-index: 0.7042553191489361
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:26:32,245] Trial 96 finished with value: 0.6667466867766902 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.8866673994678815, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00010254419006395848, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6749049429657795
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:26:34,355] Trial 97 finished with value: 0.6585055548372436 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 18, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.743952091363973, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012121939934777472, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5775193798449613
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6115879828326181
[I 2024-04-13 17:26:42,126] Trial 98 finished with value: 0.627071900642681 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.8087130156519865, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.032634018282811726, 'warm_start': False}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.825531914893617

[I 2024-04-13 17:26:44,426] A new study created in memory with name: no-name-aa8797dd-f3b6-4e7e-8ee4-f79ee04e889f

Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8154506437768241
[I 2024-04-13 17:26:44,397] Trial 99 finished with value: 0.7500076372617474 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 452, 'oob_score': False, 'max_samples': 0.6902938777535903, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04784650401125385, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.


* Best trial for C-index:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.7898421579172852], datetime_start=datetime.datetime(2024, 4, 13, 17, 25, 50, 112168), datetime_complete=datetime.datetime(2024, 4, 13, 17, 25, 51, 875091), params={'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 435, 'oob_score': False, 'max_samples': 0.9937352645069003, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.014733302673387358, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=81, value=None)


* Best Score for C-index:
 0.7898421579172852

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23819032549148034
Fold 2 IBS: 0.23121788001563107
Fold 3 IBS: 0.21979369823749267
Fold 4 IBS: 0.2318228322973839
Fold 5 IBS: 0.21024821548260486
[I 2024-04-13 17:26:50,823] Trial 0 finished with value: 0.22625459030491854 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.22625459030491854.
Fold 1 IBS: 0.2327303554970621
Fold 2 IBS: 0.22773051352570262
Fold 3 IBS: 0.21684304094654686
Fold 4 IBS: 0.2287850855661341
Fold 5 IBS: 0.21336280816660322
[I 2024-04-13 17:26:52,462] Trial 1 finished with value: 0.22389036074040977 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.22389036074040977.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-13 17:26:53,596] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.22389036074040977.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-13 17:26:57,860] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.22389036074040977.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-13 17:27:01,170] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.22389036074040977.
Fold 1 IBS: 0.24195276719924078
Fold 2 IBS: 0.23158306192048977
Fold 3 IBS: 0.21085268504232352
Fold 4 IBS: 0.22590092577347623
Fold 5 IBS: 0.2158343974194969
[I 2024-04-13 17:27:05,722] Trial 5 finished with value: 0.22522476747100542 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.22389036074040977.
Fold 1 IBS: 0.23967841421337877
Fold 2 IBS: 0.22235525504764858
Fold 3 IBS: 0.21859475882848345
Fold 4 IBS: 0.2286576795074638
Fold 5 IBS: 0.2076537454704683
[I 2024-04-13 17:27:10,007] Trial 6 finished with value: 0.22338797061348856 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 6 with value: 0.22338797061348856.
Fold 1 IBS: 0.24345153214227594
Fold 2 IBS: 0.23065480198027405
Fold 3 IBS: 0.22931062857448625
Fold 4 IBS: 0.2384177765763348
Fold 5 IBS: 0.22787014183210574
[I 2024-04-13 17:27:16,182] Trial 7 finished with value: 0.2339409762210954 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 6 with value: 0.22338797061348856.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-13 17:27:25,208] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 6 with value: 0.22338797061348856.
Fold 1 IBS: 0.2320102439831575
Fold 2 IBS: 0.22451454416835206
Fold 3 IBS: 0.2177950757126267
Fold 4 IBS: 0.22911956144415363
Fold 5 IBS: 0.2109401120435157
[I 2024-04-13 17:27:27,928] Trial 9 finished with value: 0.2228759074703611 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 9 with value: 0.2228759074703611.
Fold 1 IBS: 0.246587342303552
Fold 2 IBS: 0.23212002973319837
Fold 3 IBS: 0.22961274657990574
Fold 4 IBS: 0.2413253549165465
Fold 5 IBS: 0.22920684798460136
[I 2024-04-13 17:27:31,511] Trial 10 finished with value: 0.2357704643035608 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1655981152594652}. Best is trial 9 with value: 0.2228759074703611.
Fold 1 IBS: 0.26024444970570754
Fold 2 IBS: 0.2216356331948992
Fold 3 IBS: 0.20646208866549096
Fold 4 IBS: 0.2236987194979317
Fold 5 IBS: 0.20823816667941644
[I 2024-04-13 17:27:31,820] Trial 11 finished with value: 0.22405581154868917 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.9904090680670613, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.31430530876132207}. Best is trial 9 with value: 0.2228759074703611.
Fold 1 IBS: 0.23302253676596166
Fold 2 IBS: 0.22350006799707825
Fold 3 IBS: 0.2117261996244006
Fold 4 IBS: 0.23014872528096708
Fold 5 IBS: 0.21131996892731336
[I 2024-04-13 17:27:35,798] Trial 12 finished with value: 0.2219434997191442 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.9777827337837477, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3324053831839262}. Best is trial 12 with value: 0.2219434997191442.
Fold 1 IBS: 0.2334167482692937
Fold 2 IBS: 0.22462815107178444
Fold 3 IBS: 0.21415254610318984
Fold 4 IBS: 0.22735181638107305
Fold 5 IBS: 0.20943018161274876
[I 2024-04-13 17:27:38,887] Trial 13 finished with value: 0.221795888687618 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 143, 'oob_score': False, 'max_samples': 0.9736995438315953, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21818725312797213}. Best is trial 13 with value: 0.221795888687618.
Fold 1 IBS: 0.23281845581582267
Fold 2 IBS: 0.22270871101965733
Fold 3 IBS: 0.21190072211209907
Fold 4 IBS: 0.22954507565286003
Fold 5 IBS: 0.2097789741690662
[I 2024-04-13 17:27:42,615] Trial 14 finished with value: 0.22135038775390106 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 160, 'oob_score': False, 'max_samples': 0.8117746868873079, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2645968579224677}. Best is trial 14 with value: 0.22135038775390106.
Fold 1 IBS: 0.23363330111712122
Fold 2 IBS: 0.22772251294499274
Fold 3 IBS: 0.21313363370892885
Fold 4 IBS: 0.2311943990289551
Fold 5 IBS: 0.2118872809428859
[I 2024-04-13 17:27:47,017] Trial 15 finished with value: 0.22351422554857675 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.8199794929905286, 'max_features': 'auto', 'min_weight_fraction_leaf': 9.233281859852283e-05}. Best is trial 14 with value: 0.22135038775390106.

Fold 1 IBS: 0.23309849867702975
Fold 2 IBS: 0.2238801862611814
Fold 3 IBS: 0.20957498925944693
Fold 4 IBS: 0.22916161954772554
Fold 5 IBS: 0.20966367383054058
[I 2024-04-13 17:27:51,536] Trial 16 finished with value: 0.22107579351518486 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 246, 'oob_score': False, 'max_samples': 0.7702473623171299, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.25854433873892946}. Best is trial 16 with value: 0.22107579351518486.
Fold 1 IBS: 0.23207571367115706
Fold 2 IBS: 0.22301648270111882
Fold 3 IBS: 0.20929958475920116
Fold 4 IBS: 0.22683443304818943
Fold 5 IBS: 0.20959031967828567
[I 2024-04-13 17:28:00,518] Trial 17 finished with value: 0.2201633067715904 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.7723653893351333, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26653765665911155}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.2463404995719331
Fold 2 IBS: 0.2321448856668435
Fold 3 IBS: 0.22959259113294117
Fold 4 IBS: 0.2415266314104949
Fold 5 IBS: 0.23024189043397938
[I 2024-04-13 17:28:10,125] Trial 18 finished with value: 0.2359692996432384 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 469, 'oob_score': True, 'max_samples': 0.7546903089061138, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38366131019449645}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.23303888011332288
Fold 2 IBS: 0.22300960933547007
Fold 3 IBS: 0.20920134919025463
Fold 4 IBS: 0.22816759153382105
Fold 5 IBS: 0.21046314793606172
[I 2024-04-13 17:28:16,119] Trial 19 finished with value: 0.22077611562178606 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 349, 'oob_score': False, 'max_samples': 0.6166062996487705, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13117892225993338}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.23835822553986638
Fold 2 IBS: 0.22799957337023416
Fold 3 IBS: 0.2255839289968672
Fold 4 IBS: 0.2347799777347254
Fold 5 IBS: 0.22413835268072815
[I 2024-04-13 17:28:24,250] Trial 20 finished with value: 0.23017201166448426 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.36221293246103303, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11290492399019064}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.23174517627510863
Fold 2 IBS: 0.22311183326872192
Fold 3 IBS: 0.2134752532935891
Fold 4 IBS: 0.22849974415037372
Fold 5 IBS: 0.21356235141371618
[I 2024-04-13 17:28:32,215] Trial 21 finished with value: 0.22207887168030188 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.6196799597483587, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2567596687243825}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.2332544171438238
Fold 2 IBS: 0.22319768331574052
Fold 3 IBS: 0.20996383118108564
Fold 4 IBS: 0.22670496467093834
Fold 5 IBS: 0.2102618867189479
[I 2024-04-13 17:28:38,826] Trial 22 finished with value: 0.22067655660610724 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 1, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.4546238642538813, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13974116057386782}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.2310699507275024
Fold 2 IBS: 0.22303094537287663
Fold 3 IBS: 0.21098495554623686
Fold 4 IBS: 0.22669642139137772
Fold 5 IBS: 0.2112926777812192
[I 2024-04-13 17:28:46,544] Trial 23 finished with value: 0.22061499016384256 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.4478983539583735, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1193442431038026}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.2322016436936384
Fold 2 IBS: 0.22349336637777067
Fold 3 IBS: 0.21006996461569238
Fold 4 IBS: 0.22527052958323776
Fold 5 IBS: 0.21049333696088765
[I 2024-04-13 17:28:53,849] Trial 24 finished with value: 0.2203057682462454 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.46113861699976405, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.020430563448902872}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.22991354874075207
Fold 2 IBS: 0.22444368768443465
Fold 3 IBS: 0.21207565297554787
Fold 4 IBS: 0.2262663752096743
Fold 5 IBS: 0.21145135976011514
[I 2024-04-13 17:29:01,593] Trial 25 finished with value: 0.22083012487410478 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 418, 'oob_score': False, 'max_samples': 0.2381911851795994, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.036226389884873186}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.23060883914260805
Fold 2 IBS: 0.22297755155674684
Fold 3 IBS: 0.2101589513975745
Fold 4 IBS: 0.22604712726802575
Fold 5 IBS: 0.21099290824592037
[I 2024-04-13 17:29:11,241] Trial 26 finished with value: 0.22015707552217512 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 440, 'oob_score': True, 'max_samples': 0.4704864355905733, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0010277467041755056}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23046923596128613
Fold 2 IBS: 0.2240015491036018
Fold 3 IBS: 0.21086502402097726
Fold 4 IBS: 0.226142024960214
Fold 5 IBS: 0.21088248515587224
[I 2024-04-13 17:29:20,328] Trial 27 finished with value: 0.22047206384039025 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 396, 'oob_score': True, 'max_samples': 0.27394238361068307, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.013617435329595393}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23471452628920897
Fold 2 IBS: 0.22673547857955847
Fold 3 IBS: 0.21103982953561207
Fold 4 IBS: 0.22446765617728826
Fold 5 IBS: 0.21450015223615418
[I 2024-04-13 17:29:32,350] Trial 28 finished with value: 0.2222915285635644 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.48498687769327536, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0641292220811886}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23136991564996087
Fold 2 IBS: 0.22204971565032036
Fold 3 IBS: 0.21300464981609682
Fold 4 IBS: 0.22675182096688823
Fold 5 IBS: 0.21182202421691915
[I 2024-04-13 17:29:43,805] Trial 29 finished with value: 0.22099962526003708 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.3571755626038756, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03807390698388844}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24606642350611257
Fold 2 IBS: 0.2321923882606996
Fold 3 IBS: 0.22988609347650055
Fold 4 IBS: 0.2412002464153435
Fold 5 IBS: 0.23034386795139541
[I 2024-04-13 17:29:52,797] Trial 30 finished with value: 0.2359378039220103 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.2172618637182342, 'max_features': None, 'min_weight_fraction_leaf': 0.19986328912293344}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23160771794643292
Fold 2 IBS: 0.22646129177037175
Fold 3 IBS: 0.21045869707390338
Fold 4 IBS: 0.22410007258120104

Fold 5 IBS: 0.2108108318582224
[I 2024-04-13 17:30:01,967] Trial 31 finished with value: 0.2206877222460263 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 396, 'oob_score': True, 'max_samples': 0.2868712535426494, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.021231453689495153}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24659836091991297
Fold 2 IBS: 0.23212875696426277
Fold 3 IBS: 0.23013831975076382
Fold 4 IBS: 0.24109773536375373
Fold 5 IBS: 0.22997643124737513
[I 2024-04-13 17:30:09,051] Trial 32 finished with value: 0.23598792084921366 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 323, 'oob_score': True, 'max_samples': 0.15457524910822473, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004932622259272009}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23197141083929648
Fold 2 IBS: 0.22199313349588728
Fold 3 IBS: 0.2125662998256947
Fold 4 IBS: 0.2269154171060468
Fold 5 IBS: 0.2125401699948321
[I 2024-04-13 17:30:19,989] Trial 33 finished with value: 0.22119728625235147 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 470, 'oob_score': True, 'max_samples': 0.3835202498388115, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09218354615163335}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23217381359662775
Fold 2 IBS: 0.22448808064455156
Fold 3 IBS: 0.20986169319903394
Fold 4 IBS: 0.22593776518550224
Fold 5 IBS: 0.210892650964984
[I 2024-04-13 17:30:28,862] Trial 34 finished with value: 0.22067080071813988 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 408, 'oob_score': True, 'max_samples': 0.5426821039862857, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04500199428375251}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23289853012973177
Fold 2 IBS: 0.228024993142558
Fold 3 IBS: 0.21255692441217353
Fold 4 IBS: 0.22694758734723536
Fold 5 IBS: 0.21091359093683118
[I 2024-04-13 17:30:38,842] Trial 35 finished with value: 0.22226832519370596 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 445, 'oob_score': True, 'max_samples': 0.6981514158760593, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16320167359786183}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2350546735426517
Fold 2 IBS: 0.236789743880471
Fold 3 IBS: 0.22212188563214683
Fold 4 IBS: 0.23185305826049626
Fold 5 IBS: 0.21752491954865782
[I 2024-04-13 17:30:49,427] Trial 36 finished with value: 0.22866885617288474 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 490, 'oob_score': True, 'max_samples': 0.49714834826170234, 'max_features': None, 'min_weight_fraction_leaf': 0.09979466708192791}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24022913171172267
Fold 2 IBS: 0.22874946375008556
Fold 3 IBS: 0.21290965440875198
Fold 4 IBS: 0.22557654547485015
Fold 5 IBS: 0.21565985272908825
[I 2024-04-13 17:30:57,675] Trial 37 finished with value: 0.22462492961489972 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 378, 'oob_score': True, 'max_samples': 0.6134779412492984, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.053624327533504934}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2325547869295493
Fold 2 IBS: 0.225529082398541
Fold 3 IBS: 0.21138715556254012
Fold 4 IBS: 0.22282613113953292
Fold 5 IBS: 0.21014751804243587
[I 2024-04-13 17:31:05,331] Trial 38 finished with value: 0.22048893481451987 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.29184797119319694, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.017087153731481407}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23561025683041087
Fold 2 IBS: 0.22941932225139652
Fold 3 IBS: 0.21631460646944745
Fold 4 IBS: 0.23234709305478357
Fold 5 IBS: 0.21076474347276042
[I 2024-04-13 17:31:15,070] Trial 39 finished with value: 0.22489120441575977 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.40430675587035536, 'max_features': None, 'min_weight_fraction_leaf': 0.08714563166723727}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24678613059437637
Fold 2 IBS: 0.2321725909539564
Fold 3 IBS: 0.22944195803388415
Fold 4 IBS: 0.24150527562231744
Fold 5 IBS: 0.230370380894624
[I 2024-04-13 17:31:19,677] Trial 40 finished with value: 0.23605526721983167 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.5739995513235784, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.41526515128052643}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23321286691758872
Fold 2 IBS: 0.2279849928934213
Fold 3 IBS: 0.2117308992197816
Fold 4 IBS: 0.2242204616828136
Fold 5 IBS: 0.20935348900548092
[I 2024-04-13 17:31:32,384] Trial 41 finished with value: 0.22130054194381726 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 333, 'oob_score': True, 'max_samples': 0.315246808599681, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02048652160594618}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2316766890229806
Fold 2 IBS: 0.22411125621421446
Fold 3 IBS: 0.21036674914110157
Fold 4 IBS: 0.22434994497665503
Fold 5 IBS: 0.21106333692808993
[I 2024-04-13 17:31:44,468] Trial 42 finished with value: 0.22031359525660835 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 8, 'n_estimators': 372, 'oob_score': True, 'max_samples': 0.26574428925186755, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.019168305255890875}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2459242180260377
Fold 2 IBS: 0.23217022029472845
Fold 3 IBS: 0.2300031028267955
Fold 4 IBS: 0.24121482096141833
Fold 5 IBS: 0.23030067078583316
[I 2024-04-13 17:31:54,647] Trial 43 finished with value: 0.23592260657896263 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 415, 'oob_score': True, 'max_samples': 0.22277971365249755, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24631410665989734
Fold 2 IBS: 0.23210802473720302
Fold 3 IBS: 0.2302521611117555
Fold 4 IBS: 0.2410435305102926
Fold 5 IBS: 0.23003859251113234
[I 2024-04-13 17:32:04,319] Trial 44 finished with value: 0.23595128310605612 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 360, 'oob_score': True, 'max_samples': 0.1383644314551697, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0686728787591377}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24617592132985935
Fold 2 IBS: 0.2322080714687311
Fold 3 IBS: 0.2295331673330916
Fold 4 IBS: 0.2414957007697489
Fold 5 IBS: 0.23031590144856742
[I 2024-04-13 17:32:14,064] Trial 45 finished with value: 0.23594575246999966 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 459, 'oob_score': True, 'max_samples': 0.5172890166610269, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30571763583075945}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23995673698361222
Fold 2 IBS: 0.22972034149382584
Fold 3 IBS: 0.2273789621853455
Fold 4 IBS: 0.2372388025033728
Fold 5 IBS: 0.2259009708948768
[I 2024-04-13 17:32:22,182] Trial 46 finished with value: 0.23203916281220663 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.1873692143114088, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03681920016521466}. Best is trial 26 with value: 0.22015707552217512.

Fold 1 IBS: 0.23103878287252402
Fold 2 IBS: 0.22628918231285983
Fold 3 IBS: 0.2133979486579942
Fold 4 IBS: 0.22430579562693312
Fold 5 IBS: 0.21153361401748674
[I 2024-04-13 17:32:32,978] Trial 47 finished with value: 0.22131306469755957 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 475, 'oob_score': False, 'max_samples': 0.43491671167283275, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07826676341691717}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2461442212529148
Fold 2 IBS: 0.23226781881803804
Fold 3 IBS: 0.22981312479103597
Fold 4 IBS: 0.24139414747597257
Fold 5 IBS: 0.2304782442201671
[I 2024-04-13 17:32:44,432] Trial 48 finished with value: 0.23601951131162568 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 19, 'max_depth': 6, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.2751094610735481, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24643065427838096
Fold 2 IBS: 0.23223464296746826
Fold 3 IBS: 0.22968175844773792
Fold 4 IBS: 0.2413651638178947
Fold 5 IBS: 0.23015719969071047
[I 2024-04-13 17:32:54,217] Trial 49 finished with value: 0.23597388384043844 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 406, 'oob_score': True, 'max_samples': 0.3426311861680858, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.37411897805446126}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23653547645771292
Fold 2 IBS: 0.23891649468883286
Fold 3 IBS: 0.22623605262377863
Fold 4 IBS: 0.23760952706404054
Fold 5 IBS: 0.21274600173139968
[I 2024-04-13 17:33:00,720] Trial 50 finished with value: 0.23040871051315293 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 14, 'n_estimators': 300, 'oob_score': False, 'max_samples': 0.91240298039898, 'max_features': None, 'min_weight_fraction_leaf': 0.0023139662763776523}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23205733305111126
Fold 2 IBS: 0.22540170926715883
Fold 3 IBS: 0.21136019029919015
Fold 4 IBS: 0.2235188735459925
Fold 5 IBS: 0.2104011228556449
[I 2024-04-13 17:33:09,214] Trial 51 finished with value: 0.22054784580381953 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 8, 'n_estimators': 365, 'oob_score': True, 'max_samples': 0.28310200045220396, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.018168221852795943}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2467425883724255
Fold 2 IBS: 0.23229207390802017
Fold 3 IBS: 0.229806458577059
Fold 4 IBS: 0.24117087537338566
Fold 5 IBS: 0.23029838496464933
[I 2024-04-13 17:33:16,786] Trial 52 finished with value: 0.23606207623910797 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.31519339436661903, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.23722810776929834}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23448850473409952
Fold 2 IBS: 0.22628680170858836
Fold 3 IBS: 0.2110553567502054
Fold 4 IBS: 0.2248272006707438
Fold 5 IBS: 0.21045438124734223
[I 2024-04-13 17:33:25,865] Trial 53 finished with value: 0.22142244902219588 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 343, 'oob_score': True, 'max_samples': 0.25208751122540896, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.028071010742289564}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2457543637764612
Fold 2 IBS: 0.23215641755689168
Fold 3 IBS: 0.23000347609635255
Fold 4 IBS: 0.24126499095998308
Fold 5 IBS: 0.2304832070970648
[I 2024-04-13 17:33:38,411] Trial 54 finished with value: 0.23593249109735065 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 431, 'oob_score': True, 'max_samples': 0.1944118385287112, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00865239972784028}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2468623556579978
Fold 2 IBS: 0.23219151424480894
Fold 3 IBS: 0.23027924136404326
Fold 4 IBS: 0.24093725814526556
Fold 5 IBS: 0.22930915051617384
[I 2024-04-13 17:33:46,407] Trial 55 finished with value: 0.23591590398565784 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 275, 'oob_score': True, 'max_samples': 0.10569714025611779, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.058450491403396476}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24642872356499093
Fold 2 IBS: 0.23205942594736154
Fold 3 IBS: 0.22994434058519342
Fold 4 IBS: 0.24150107878356789
Fold 5 IBS: 0.23008272411407127
[I 2024-04-13 17:33:47,693] Trial 56 finished with value: 0.23600325859903698 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 51, 'oob_score': False, 'max_samples': 0.569633571031224, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.28766369733548897}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2464642877720641
Fold 2 IBS: 0.23233994540501388
Fold 3 IBS: 0.22968667048933009
Fold 4 IBS: 0.24135786670781292
Fold 5 IBS: 0.23035458313442783
[I 2024-04-13 17:33:52,682] Trial 57 finished with value: 0.2360406707017298 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 215, 'oob_score': True, 'max_samples': 0.40454378901615895, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.23177764488631825}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23328570910599059
Fold 2 IBS: 0.22482997301632762
Fold 3 IBS: 0.21090048079749318
Fold 4 IBS: 0.2254130957827992
Fold 5 IBS: 0.21047905455719065
[I 2024-04-13 17:34:00,622] Trial 58 finished with value: 0.2209816626519603 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 355, 'oob_score': False, 'max_samples': 0.4555194020493191, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.045806106324310286}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24638937856742066
Fold 2 IBS: 0.23217903444274132
Fold 3 IBS: 0.22957970746983006
Fold 4 IBS: 0.24149329059953806
Fold 5 IBS: 0.23023771602212853
[I 2024-04-13 17:34:07,846] Trial 59 finished with value: 0.23597582542033174 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.6547993209148422, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3347027531859703}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2306118363998221
Fold 2 IBS: 0.22306141635246116
Fold 3 IBS: 0.21072669348877712
Fold 4 IBS: 0.22625181384713736
Fold 5 IBS: 0.21133732898704416
[I 2024-04-13 17:34:18,849] Trial 60 finished with value: 0.22039781781504839 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 478, 'oob_score': True, 'max_samples': 0.48271442117986096, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.178446120167478}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2311701429638268
Fold 2 IBS: 0.22477774454018215
Fold 3 IBS: 0.21109067313133456
Fold 4 IBS: 0.22467051654837508
Fold 5 IBS: 0.2120682587473275
[I 2024-04-13 17:34:32,016] Trial 61 finished with value: 0.22075546718620923 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 477, 'oob_score': True, 'max_samples': 0.5026627705946465, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14529793469682825}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2461928599463436
Fold 2 IBS: 0.23221691568783104
Fold 3 IBS: 0.22947567562670096
Fold 4 IBS: 0.24151671023331148

Fold 5 IBS: 0.23018854152461504
[I 2024-04-13 17:34:42,658] Trial 62 finished with value: 0.23591814060376043 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.4677262455345284, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2827349986373208}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24652405780792855
Fold 2 IBS: 0.2322152403880562
Fold 3 IBS: 0.22946718005561817
Fold 4 IBS: 0.2414651127800749
Fold 5 IBS: 0.23031058287471998
[I 2024-04-13 17:34:55,573] Trial 63 finished with value: 0.23599643478127957 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 499, 'oob_score': True, 'max_samples': 0.36524236153301975, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.19147391488941964}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23373423023692633
Fold 2 IBS: 0.22521393950806748
Fold 3 IBS: 0.2191306507991317
Fold 4 IBS: 0.23014767984329243
Fold 5 IBS: 0.22006146132051893
[I 2024-04-13 17:35:09,933] Trial 64 finished with value: 0.2256575923415874 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 426, 'oob_score': True, 'max_samples': 0.341317344596171, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.024163948190701435}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23110813901378655
Fold 2 IBS: 0.22625593796332996
Fold 3 IBS: 0.21344254276833136
Fold 4 IBS: 0.22403890746089866
Fold 5 IBS: 0.21112293233311893
[I 2024-04-13 17:35:24,764] Trial 65 finished with value: 0.2211936919078931 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 484, 'oob_score': True, 'max_samples': 0.4293920185141239, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10772017538104399}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23510485461556999
Fold 2 IBS: 0.2248386961406159
Fold 3 IBS: 0.20438305318368702
Fold 4 IBS: 0.22161474102841908
Fold 5 IBS: 0.20865703395071367
[I 2024-04-13 17:35:36,030] Trial 66 finished with value: 0.2189196757838011 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.7277222032902713, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00012424788420031775}. Best is trial 66 with value: 0.2189196757838011.
Fold 1 IBS: 0.23501226850054138
Fold 2 IBS: 0.22471431254299942
Fold 3 IBS: 0.20593000096178582
Fold 4 IBS: 0.22343494979422188
Fold 5 IBS: 0.20949072806237073
[I 2024-04-13 17:35:47,060] Trial 67 finished with value: 0.21971645197238385 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.7290936220221548, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07569575991727365}. Best is trial 66 with value: 0.2189196757838011.
Fold 1 IBS: 0.23233804701309263
Fold 2 IBS: 0.22733944531132327
Fold 3 IBS: 0.2130366337153433
Fold 4 IBS: 0.22697606576675997
Fold 5 IBS: 0.21055795261271074
[I 2024-04-13 17:36:01,062] Trial 68 finished with value: 0.222049628883846 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 465, 'oob_score': False, 'max_samples': 0.738982857579614, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17948323116159026}. Best is trial 66 with value: 0.2189196757838011.
Fold 1 IBS: 0.23738739866957145
Fold 2 IBS: 0.22468686012438713
Fold 3 IBS: 0.20171388324594125
Fold 4 IBS: 0.22142509500072
Fold 5 IBS: 0.20594012888505892
[I 2024-04-13 17:36:14,046] Trial 69 finished with value: 0.21823067318513573 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.7966473717734156, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.000754910732434978}. Best is trial 69 with value: 0.21823067318513573.
Fold 1 IBS: 0.23640466205485558
Fold 2 IBS: 0.22511627601864978
Fold 3 IBS: 0.20496467553113637
Fold 4 IBS: 0.22127678503888615
Fold 5 IBS: 0.20729334433212973
[I 2024-04-13 17:36:28,980] Trial 70 finished with value: 0.21901114859513152 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.7903378056871502, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0691368647018997}. Best is trial 69 with value: 0.21823067318513573.
Fold 1 IBS: 0.23750818984851968
Fold 2 IBS: 0.22426265927695213
Fold 3 IBS: 0.2016674228960865
Fold 4 IBS: 0.2211677375711476
Fold 5 IBS: 0.20609431335638406
[I 2024-04-13 17:36:42,045] Trial 71 finished with value: 0.21814006458981802 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.785271119394671, 'max_features': 'log2', 'min_weight_fraction_leaf': 8.074256882937306e-05}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23838492585055007
Fold 2 IBS: 0.22507214558163305
Fold 3 IBS: 0.20143767144413025
Fold 4 IBS: 0.22268918756548908
Fold 5 IBS: 0.2068563072044347
[I 2024-04-13 17:36:53,741] Trial 72 finished with value: 0.2188880475292474 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.8036876381737409, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0015918352811246476}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23843558191669362
Fold 2 IBS: 0.22493582433312012
Fold 3 IBS: 0.20129183641750387
Fold 4 IBS: 0.22279078455344045
Fold 5 IBS: 0.20681700555549176
[I 2024-04-13 17:37:04,676] Trial 73 finished with value: 0.21885420655524995 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.7999498893948669, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0005099629334644618}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23664162395062918
Fold 2 IBS: 0.2241356454982757
Fold 3 IBS: 0.20519783897054078
Fold 4 IBS: 0.22110736731436786
Fold 5 IBS: 0.2073382645860624
[I 2024-04-13 17:37:14,207] Trial 74 finished with value: 0.21888414806397516 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.8194617003412593, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0712695999375732}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23537805440745527
Fold 2 IBS: 0.22434344368362777
Fold 3 IBS: 0.20738548248880273
Fold 4 IBS: 0.22180433731709842
Fold 5 IBS: 0.20889031390025767
[I 2024-04-13 17:37:23,623] Trial 75 finished with value: 0.21956032635944833 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.8133524942001209, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08127549167715468}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23545525573147905
Fold 2 IBS: 0.22153659942623385
Fold 3 IBS: 0.2075449303933778
Fold 4 IBS: 0.2231528926555171
Fold 5 IBS: 0.2079749514693718
[I 2024-04-13 17:37:32,472] Trial 76 finished with value: 0.2191329259351959 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 405, 'oob_score': False, 'max_samples': 0.8231686578176318, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05240500541214905}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23575461528483777
Fold 2 IBS: 0.22187847432867439
Fold 3 IBS: 0.20868891108618615
Fold 4 IBS: 0.22380403297644932
Fold 5 IBS: 0.2079961384411151
[I 2024-04-13 17:37:40,866] Trial 77 finished with value: 0.21962443442345253 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 406, 'oob_score': False, 'max_samples': 0.8554946968969933, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.052809045001292264}. Best is trial 71 with value: 0.21814006458981802.

Fold 1 IBS: 0.24217247193439537
Fold 2 IBS: 0.2278793635566358
Fold 3 IBS: 0.20080078124083145
Fold 4 IBS: 0.22310960096298033
Fold 5 IBS: 0.2079672399605948
[I 2024-04-13 17:37:49,907] Trial 78 finished with value: 0.22038589153108754 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 418, 'oob_score': False, 'max_samples': 0.7742508336660989, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.033857990321958055}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2355555064593619
Fold 2 IBS: 0.22224942419207222
Fold 3 IBS: 0.20877935998830383
Fold 4 IBS: 0.22444536984656233
Fold 5 IBS: 0.2081228365598182
[I 2024-04-13 17:38:00,161] Trial 79 finished with value: 0.21983049940922367 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.8561349620215079, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0005195865801855532}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.24241429583579838
Fold 2 IBS: 0.22789447806360993
Fold 3 IBS: 0.20467685675034264
Fold 4 IBS: 0.22288907337161928
Fold 5 IBS: 0.20750330171816853
[I 2024-04-13 17:38:11,678] Trial 80 finished with value: 0.22107560114790772 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.7908246314613915, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04549184809342783}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23643091434190627
Fold 2 IBS: 0.2245035140221752
Fold 3 IBS: 0.2054229767526827
Fold 4 IBS: 0.22079340395882704
Fold 5 IBS: 0.20720357309992168
[I 2024-04-13 17:38:22,363] Trial 81 finished with value: 0.2188708764351026 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.82389908631297, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06682100879850736}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23784943286734053
Fold 2 IBS: 0.22299626441699782
Fold 3 IBS: 0.2051875205309834
Fold 4 IBS: 0.2219151954315832
Fold 5 IBS: 0.20639160499029274
[I 2024-04-13 17:38:31,576] Trial 82 finished with value: 0.21886800364743958 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 433, 'oob_score': False, 'max_samples': 0.907696191161797, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0649269059958972}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23481648213378556
Fold 2 IBS: 0.22399470395223586
Fold 3 IBS: 0.20839589700096056
Fold 4 IBS: 0.2246777750739523
Fold 5 IBS: 0.21000594947142526
[I 2024-04-13 17:38:42,161] Trial 83 finished with value: 0.22037816152647194 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.9163341718713127, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12259108267136748}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2334939533679607
Fold 2 IBS: 0.22607705247059665
Fold 3 IBS: 0.20757402674496309
Fold 4 IBS: 0.22531097361703065
Fold 5 IBS: 0.2109776338102316
[I 2024-04-13 17:38:52,968] Trial 84 finished with value: 0.22068672800215655 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.6964735539602778, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0983502057538686}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.24168961801227365
Fold 2 IBS: 0.22720531732946742
Fold 3 IBS: 0.2073627488337626
Fold 4 IBS: 0.22321443955217113
Fold 5 IBS: 0.20933627466281343
[I 2024-04-13 17:39:04,253] Trial 85 finished with value: 0.22176167967809762 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.8852611846969818, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06716376200543844}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2501102112818779
Fold 2 IBS: 0.23109915986172933
Fold 3 IBS: 0.2015627722369633
Fold 4 IBS: 0.22179451257247865
Fold 5 IBS: 0.21066046744033398
[I 2024-04-13 17:39:15,509] Trial 86 finished with value: 0.2230454246786766 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 471, 'oob_score': False, 'max_samples': 0.9556515545432857, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.032457057200294154}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23570787321457648
Fold 2 IBS: 0.22130640184705208
Fold 3 IBS: 0.2058533403920595
Fold 4 IBS: 0.2271720358186151
Fold 5 IBS: 0.20822086095930034
[I 2024-04-13 17:39:26,021] Trial 87 finished with value: 0.21965210244632072 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 486, 'oob_score': False, 'max_samples': 0.8392358634429405, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012615689337359539}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23506041233177796
Fold 2 IBS: 0.22676854768655463
Fold 3 IBS: 0.21426008705017613
Fold 4 IBS: 0.22869053791418748
Fold 5 IBS: 0.21289985376952034
[I 2024-04-13 17:39:37,746] Trial 88 finished with value: 0.22353588775044334 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.8803049631865397, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14660532598550163}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23714953265947813
Fold 2 IBS: 0.22436316613074966
Fold 3 IBS: 0.2020631925894465
Fold 4 IBS: 0.22124274581523004
Fold 5 IBS: 0.20620465624668038
[I 2024-04-13 17:39:49,125] Trial 89 finished with value: 0.21820465868831693 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 456, 'oob_score': False, 'max_samples': 0.7896846867879517, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03627962366130027}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23580014606596647
Fold 2 IBS: 0.2218875639554552
Fold 3 IBS: 0.20867976067748017
Fold 4 IBS: 0.22627294211995028
Fold 5 IBS: 0.20840927695622002
[I 2024-04-13 17:40:00,944] Trial 90 finished with value: 0.22020993795501442 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 463, 'oob_score': False, 'max_samples': 0.93720899494118, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03869745358932866}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2354589984552326
Fold 2 IBS: 0.22524001219031592
Fold 3 IBS: 0.20569095963108802
Fold 4 IBS: 0.22140761560731112
Fold 5 IBS: 0.20777808554956137
[I 2024-04-13 17:40:11,927] Trial 91 finished with value: 0.2191151342867018 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 452, 'oob_score': False, 'max_samples': 0.7965806938790612, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06322946729450632}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.24160797692372046
Fold 2 IBS: 0.22877573588171754
Fold 3 IBS: 0.20349956847846673
Fold 4 IBS: 0.22172366432250362
Fold 5 IBS: 0.20728746219361785
[I 2024-04-13 17:40:22,505] Trial 92 finished with value: 0.22057888156000524 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.7550788603038648, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01093866522527464}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23805383943188022
Fold 2 IBS: 0.22443950723251976
Fold 3 IBS: 0.20085521312077026
Fold 4 IBS: 0.22152045897596737

Fold 5 IBS: 0.2069805372099246
[I 2024-04-13 17:40:33,938] Trial 93 finished with value: 0.21836991119421248 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 436, 'oob_score': False, 'max_samples': 0.7876680525303928, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02818336790921719}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2481959844323671
Fold 2 IBS: 0.23173657169109757
Fold 3 IBS: 0.20201510994966232
Fold 4 IBS: 0.22255626189257152
Fold 5 IBS: 0.21061654425734486
[I 2024-04-13 17:40:47,870] Trial 94 finished with value: 0.22302409444460863 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 436, 'oob_score': False, 'max_samples': 0.8362507108284499, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.027504161893380293}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23915650996574608
Fold 2 IBS: 0.2234245394350635
Fold 3 IBS: 0.21293758807164273
Fold 4 IBS: 0.23523772004345975
Fold 5 IBS: 0.21283134069782997
[I 2024-04-13 17:40:59,476] Trial 95 finished with value: 0.2247175396427484 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.8837943797775261, 'max_features': None, 'min_weight_fraction_leaf': 0.012755690371205977}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23636458888864972
Fold 2 IBS: 0.22548005093935128
Fold 3 IBS: 0.20289781330297618
Fold 4 IBS: 0.22194388354495065
Fold 5 IBS: 0.20659782587399886
[I 2024-04-13 17:41:09,612] Trial 96 finished with value: 0.2186568325099853 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.7047963450216371, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.042649479114857974}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2368435830144382
Fold 2 IBS: 0.22787196721859507
Fold 3 IBS: 0.21053102229260984
Fold 4 IBS: 0.22497427988410976
Fold 5 IBS: 0.21388075327377432
[I 2024-04-13 17:41:18,999] Trial 97 finished with value: 0.2228203211367054 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 391, 'oob_score': False, 'max_samples': 0.695234381023326, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08812518101550153}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23461443359372502
Fold 2 IBS: 0.22206420895541035
Fold 3 IBS: 0.20600949221006296
Fold 4 IBS: 0.2225105168375799
Fold 5 IBS: 0.20798613510831773
[I 2024-04-13 17:41:31,008] Trial 98 finished with value: 0.21863695734101918 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 429, 'oob_score': False, 'max_samples': 0.7518465351355723, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04566737589752622}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23487790054634475
Fold 2 IBS: 0.22192356266132915
Fold 3 IBS: 0.206872333232792
Fold 4 IBS: 0.22206365342237452
Fold 5 IBS: 0.20811521327808374
[I 2024-04-13 17:41:42,953] Trial 99 finished with value: 0.21877053262818486 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 426, 'oob_score': False, 'max_samples': 0.7658401698686866, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04554148579618334}. Best is trial 71 with value: 0.21814006458981802.


* Best trial for IBS:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.21814006458981802], datetime_start=datetime.datetime(2024, 4, 13, 17, 36, 28, 990733), datetime_complete=datetime.datetime(2024, 4, 13, 17, 36, 42, 44381), params={'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.785271119394671, 'max_features': 'log2', 'min_weight_fraction_leaf': 8.074256882937306e-05}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=71, value=None)


* Best Score for IBS:
 0.21814006458981802

In [74]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [75]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.79
train_ibs:  0.218

#### Test

In [76]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [77]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=20, max_features='auto', max_leaf_nodes=12,
                     max_samples=0.9937352645069003, min_samples_leaf=1,
                     min_samples_split=5,
                     min_weight_fraction_leaf=0.014733302673387358,
                     n_estimators=435, random_state=123, warm_start=True)

test_cindex:  0.603

RandomSurvivalForest(max_depth=13, max_features='log2', max_leaf_nodes=3,
                     max_samples=0.785271119394671, min_samples_leaf=4,
                     min_samples_split=2,
                     min_weight_fraction_leaf=8.074256882937306e-05,
                     n_estimators=444, random_state=123)

test_ibs:  0.215

In [78]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [79]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [80]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:41:48,733] A new study created in memory with name: no-name-c76c2f86-4499-4904-983f-5c30a19cf1c2

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7382978723404255
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6909871244635193
[I 2024-04-13 17:41:51,051] Trial 0 finished with value: 0.6851000777443397 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:41:56,260] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.674468085106383
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:42:07,235] Trial 2 finished with value: 0.6471738109279814 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.647410358565737
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 17:42:08,132] Trial 3 finished with value: 0.6721233889975948 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:42:11,890] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:42:17,357] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:42:20,248] Trial 6 finished with value: 0.6775544862150437 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.575107296137339
[I 2024-04-13 17:42:26,521] Trial 7 finished with value: 0.6410571220283957 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:42:26,892] Trial 8 finished with value: 0.6602715482412723 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:42:41,730] Trial 9 finished with value: 0.6387388839144454 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:42:48,399] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6155378486055777
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 17:42:51,501] Trial 11 finished with value: 0.6702180836908557 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6995708154506438
[I 2024-04-13 17:42:55,414] Trial 12 finished with value: 0.6881534529891422 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 17:42:59,418] Trial 13 finished with value: 0.6646828847295456 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6298449612403101
Fold 3 C-index: 0.7
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 17:43:02,362] Trial 14 finished with value: 0.6594415746090991 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7212765957446808

Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6158798283261803
[I 2024-04-13 17:43:04,406] Trial 15 finished with value: 0.6707959967448854 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.6977186311787072
Fold 5 C-index: 0.6094420600858369
[I 2024-04-13 17:43:08,090] Trial 16 finished with value: 0.656032749497523 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.5717131474103586
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7510638297872341
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:43:11,329] Trial 17 finished with value: 0.6664734494891689 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:43:15,272] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6502145922746781
[I 2024-04-13 17:43:17,961] Trial 19 finished with value: 0.6644257554322603 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 17:43:18,484] Trial 20 finished with value: 0.6567802711331774 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 17:43:21,417] Trial 21 finished with value: 0.6792348679372288 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6824034334763949
[I 2024-04-13 17:43:25,039] Trial 22 finished with value: 0.686029107776449 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6866952789699571
[I 2024-04-13 17:43:28,185] Trial 23 finished with value: 0.6906324467750945 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6180257510729614
[I 2024-04-13 17:43:31,804] Trial 24 finished with value: 0.6711203403150813 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7017167381974249
[I 2024-04-13 17:43:35,162] Trial 25 finished with value: 0.6858499860979521 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.572961373390558
[I 2024-04-13 17:43:50,578] Trial 26 finished with value: 0.6413704991472602 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6569767441860465
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 17:43:53,994] Trial 27 finished with value: 0.675049805218149 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.5836653386454184
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.7042553191489361
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.6673819742489271
[I 2024-04-13 17:43:56,390] Trial 28 finished with value: 0.6584670168145277 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6354581673306773
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 17:43:58,032] Trial 29 finished with value: 0.655897752553135 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.6906324467750945.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6763565891472868
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 17:44:01,014] Trial 30 finished with value: 0.6821700950953665 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7017167381974249
[I 2024-04-13 17:44:03,983] Trial 31 finished with value: 0.6850747922995026 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6357896182918609, 'min_weight_fraction_leaf': 0.043457520259011145}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 17:44:06,768] Trial 32 finished with value: 0.6748268325865853 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.48963031975436294, 'min_weight_fraction_leaf': 0.054624644214656966}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6414728682170543
Fold 3 C-index: 0.7297872340425532
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 17:44:13,317] Trial 33 finished with value: 0.6546886869454311 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.527493679418052, 'min_weight_fraction_leaf': 0.11101292483370524}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 17:44:19,430] Trial 34 finished with value: 0.6855672055264954 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9202590430146967, 'min_weight_fraction_leaf': 0.07949057080337707}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 17:44:34,779] Trial 35 finished with value: 0.6957388726363694 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 474, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.678814039070356, 'min_weight_fraction_leaf': 0.028560781966745094}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.625968992248062
Fold 3 C-index: 0.674468085106383
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6008583690987125
[I 2024-04-13 17:44:55,273] Trial 36 finished with value: 0.6460431015306448 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 487, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7202769479752608, 'min_weight_fraction_leaf': 0.1272251175690979}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6531007751937985
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:45:01,653] Trial 37 finished with value: 0.6535992249876296 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 466, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8198785636142412, 'min_weight_fraction_leaf': 0.029014014591284436}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6337209302325582
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 17:45:06,569] Trial 38 finished with value: 0.655251518254536 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 437, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.002361340929773935}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.6787072243346007
Fold 5 C-index: 0.6180257510729614
[I 2024-04-13 17:45:17,958] Trial 39 finished with value: 0.645723528384093 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 397, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7691351859887788, 'min_weight_fraction_leaf': 0.06720870867946066}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:45:22,690] Trial 40 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 344, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5982912816250927, 'min_weight_fraction_leaf': 0.4492877633512613}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 17:45:25,837] Trial 41 finished with value: 0.6880044461642689 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6598304746211209, 'min_weight_fraction_leaf': 0.053447973833735035}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7510638297872341
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7081545064377682
[I 2024-04-13 17:45:33,620] Trial 42 finished with value: 0.7030860499704138 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 473, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5313336913856148, 'min_weight_fraction_leaf': 0.025352461449765364}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:45:41,755] Trial 43 finished with value: 0.679926602167664 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 482, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5364184962117242, 'min_weight_fraction_leaf': 0.05972934366832378}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:45:48,832] Trial 44 finished with value: 0.6845185041435788 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.687551258169526, 'min_weight_fraction_leaf': 0.09604207143003154}. Best is trial 42 with value: 0.7030860499704138.

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7425531914893617
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.723175965665236
[I 2024-04-13 17:45:51,336] Trial 45 finished with value: 0.6928271133771465 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 144, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5586473886674701, 'min_weight_fraction_leaf': 0.021758007763963413}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 17:45:53,868] Trial 46 finished with value: 0.6806840283474052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 138, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.4276865318481037, 'min_weight_fraction_leaf': 0.017191498668975277}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6298449612403101
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.6863117870722434
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 17:45:57,922] Trial 47 finished with value: 0.6406747019951217 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 93, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.36005786284820956, 'min_weight_fraction_leaf': 0.022894100109012182}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7124463519313304
[I 2024-04-13 17:46:01,415] Trial 48 finished with value: 0.6975026836324872 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 223, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.94082830351897, 'min_weight_fraction_leaf': 0.0031941216647066936}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:46:04,687] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 212, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5011407247227364, 'min_weight_fraction_leaf': 0.358441712753887}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6453488372093024
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 17:46:07,413] Trial 50 finished with value: 0.6804367470765946 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 171, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9312077054760161, 'min_weight_fraction_leaf': 0.12266310822518021}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 17:46:09,981] Trial 51 finished with value: 0.6746377989463979 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 170, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.957889367228467, 'min_weight_fraction_leaf': 0.0007314361594816486}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.759656652360515
[I 2024-04-13 17:46:13,701] Trial 52 finished with value: 0.7033308262791091 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 242, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8076761414867076, 'min_weight_fraction_leaf': 0.02370651531262462}. Best is trial 52 with value: 0.7033308262791091.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 17:46:16,693] Trial 53 finished with value: 0.6854416959540812 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 195, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7882374110234983, 'min_weight_fraction_leaf': 0.07355615073523727}. Best is trial 52 with value: 0.7033308262791091.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6995708154506438
[I 2024-04-13 17:46:20,408] Trial 54 finished with value: 0.6912653578936234 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 236, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8462634635234857, 'min_weight_fraction_leaf': 0.027695920994629177}. Best is trial 52 with value: 0.7033308262791091.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8068669527896996
[I 2024-04-13 17:46:23,979] Trial 55 finished with value: 0.7304019052983591 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 237, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8431949607994742, 'min_weight_fraction_leaf': 0.019689561001487742}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6995708154506438
[I 2024-04-13 17:46:28,670] Trial 56 finished with value: 0.6852121772640821 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 288, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8359750908740874, 'min_weight_fraction_leaf': 0.09275039490290456}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7339055793991416
[I 2024-04-13 17:46:34,600] Trial 57 finished with value: 0.7080313014605807 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 278, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.912592990524893, 'min_weight_fraction_leaf': 0.0210885099116659}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.6354581673306773
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 17:46:38,957] Trial 58 finished with value: 0.6555053283777668 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 292, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9091926669480035, 'min_weight_fraction_leaf': 0.2526413207446905}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5515021459227468
[I 2024-04-13 17:46:47,222] Trial 59 finished with value: 0.612482459269093 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 235, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.943040394432692, 'min_weight_fraction_leaf': 0.040329046437081434}. Best is trial 55 with value: 0.7304019052983591.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6995708154506438
[I 2024-04-13 17:46:51,280] Trial 60 finished with value: 0.6883778093095436 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 275, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.879697866755957, 'min_weight_fraction_leaf': 0.055451281420183546}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7553191489361702
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7081545064377682
[I 2024-04-13 17:46:53,820] Trial 61 finished with value: 0.6882180229986123 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 131, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.801988873777292, 'min_weight_fraction_leaf': 0.017439688996287176}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7360515021459227
[I 2024-04-13 17:46:55,368] Trial 62 finished with value: 0.7109694649252425 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 79, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8617770804754492, 'min_weight_fraction_leaf': 0.014415763584492182}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7317596566523605
[I 2024-04-13 17:46:56,461] Trial 63 finished with value: 0.7183475356629161 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 59, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8664901703822724, 'min_weight_fraction_leaf': 0.0002705850447878577}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8133047210300429
[I 2024-04-13 17:46:57,722] Trial 64 finished with value: 0.7483307845911831 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 54, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8662742964997368, 'min_weight_fraction_leaf': 0.0017689713740798967}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6957364341085271
Fold 3 C-index: 0.7510638297872341
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7060085836909872
[I 2024-04-13 17:46:58,844] Trial 65 finished with value: 0.6998208548490268 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 61, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9996385846525305, 'min_weight_fraction_leaf': 0.04725744918321939}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:46:59,351] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 9, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8621588892289783, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5796812749003984
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6716738197424893
[I 2024-04-13 17:47:00,107] Trial 67 finished with value: 0.6849489036736089 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 36, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8924168531245312, 'min_weight_fraction_leaf': 0.07024991347750792}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.6075697211155379
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.7382978723404255
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 17:47:01,829] Trial 68 finished with value: 0.6860272317441234 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 94, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7570760952920621, 'min_weight_fraction_leaf': 0.08592463964216505}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7661596958174905
Fold 5 C-index: 0.6759656652360515
[I 2024-04-13 17:47:03,004] Trial 69 finished with value: 0.6949112962080065 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 62, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9037622964369387, 'min_weight_fraction_leaf': 0.014330365794333477}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6909871244635193
[I 2024-04-13 17:47:03,977] Trial 70 finished with value: 0.6910631381543316 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 34, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8093114050677033, 'min_weight_fraction_leaf': 0.03979626985401667}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6724806201550387
Fold 3 C-index: 0.7425531914893617
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7017167381974249
[I 2024-04-13 17:47:05,157] Trial 71 finished with value: 0.6957600898208183 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 70, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9952461586716469, 'min_weight_fraction_leaf': 0.05244870419935619}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8154506437768241
[I 2024-04-13 17:47:07,018] Trial 72 finished with value: 0.732867519325721 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 117, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9729286202250643, 'min_weight_fraction_leaf': 0.0007501905752557436}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 17:47:09,348] Trial 73 finished with value: 0.7128904943815512 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 116, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9537142578281173, 'min_weight_fraction_leaf': 0.012418975853445025}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7467811158798283
[I 2024-04-13 17:47:11,473] Trial 74 finished with value: 0.7191746692395198 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9697396627525858, 'min_weight_fraction_leaf': 0.011122539757406865}. Best is trial 64 with value: 0.7483307845911831.

Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7965779467680608
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 17:47:13,593] Trial 75 finished with value: 0.7129593862942667 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 117, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9611088438541834, 'min_weight_fraction_leaf': 0.00026629033599147274}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.5643776824034334
[I 2024-04-13 17:47:19,342] Trial 76 finished with value: 0.6073724889462218 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 108, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9582643703114411, 'min_weight_fraction_leaf': 0.015367528693973603}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7424892703862661
[I 2024-04-13 17:47:21,803] Trial 77 finished with value: 0.7128288110450078 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 126, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9494217636188305, 'min_weight_fraction_leaf': 0.0016737005937686057}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8111587982832618
[I 2024-04-13 17:47:23,722] Trial 78 finished with value: 0.7319548991462254 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 123, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9642227434197009, 'min_weight_fraction_leaf': 0.0021058685030657335}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7553191489361702
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 17:47:25,940] Trial 79 finished with value: 0.6999093844652243 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 117, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9695872781720767, 'min_weight_fraction_leaf': 0.03777743761503083}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.7103004291845494
[I 2024-04-13 17:47:29,110] Trial 80 finished with value: 0.6889680415739856 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 159, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9748962504778398, 'min_weight_fraction_leaf': 0.06439560013397327}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7424892703862661
[I 2024-04-13 17:47:31,831] Trial 81 finished with value: 0.7112568044975542 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 124, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9489094481266604, 'min_weight_fraction_leaf': 0.00837226306600549}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7489270386266095
[I 2024-04-13 17:47:34,064] Trial 82 finished with value: 0.7151598166699424 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 103, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8869701624411807, 'min_weight_fraction_leaf': 0.0009826312409484343}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.703862660944206
[I 2024-04-13 17:47:36,134] Trial 83 finished with value: 0.70260361739942 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 91, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9252815070211524, 'min_weight_fraction_leaf': 0.034454055596569985}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 17:47:38,312] Trial 84 finished with value: 0.664443908687675 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 19, 'n_estimators': 108, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8873964455419806, 'min_weight_fraction_leaf': 0.0001876274131405089}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.725531914893617
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 17:47:41,084] Trial 85 finished with value: 0.6873669920373484 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 151, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9765072725804504, 'min_weight_fraction_leaf': 0.013004742095931136}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6716738197424893
[I 2024-04-13 17:47:43,226] Trial 86 finished with value: 0.6868914200866229 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 78, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8698782711480478, 'min_weight_fraction_leaf': 0.03289779563895275}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6995708154506438
[I 2024-04-13 17:47:44,805] Trial 87 finished with value: 0.6948891539842074 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 50, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8345993194987964, 'min_weight_fraction_leaf': 0.051343068837458844}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.5910852713178295
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.5579399141630901
[I 2024-04-13 17:47:52,924] Trial 88 finished with value: 0.6097028070712147 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 194, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.924420980029357, 'min_weight_fraction_leaf': 0.010350197621313917}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6337209302325582
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.6749049429657795
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 17:47:53,786] Trial 89 finished with value: 0.6469835494137881 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 16, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9991858125788121, 'min_weight_fraction_leaf': 0.28976495050632306}. Best is trial 64 with value: 0.7483307845911831.

Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8175965665236051
[I 2024-04-13 17:47:57,308] Trial 90 finished with value: 0.729087779708108 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 168, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9119141145095422, 'min_weight_fraction_leaf': 0.03045835615518719}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8261802575107297
[I 2024-04-13 17:48:00,595] Trial 91 finished with value: 0.7301061688113683 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 172, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8965986548546552, 'min_weight_fraction_leaf': 0.032382398081057265}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6453488372093024
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 17:48:03,933] Trial 92 finished with value: 0.6654765723248192 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 175, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.25077855422842626, 'min_weight_fraction_leaf': 0.030475090955934078}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7808510638297872
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8218884120171673
[I 2024-04-13 17:48:07,398] Trial 93 finished with value: 0.723349516226648 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 184, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9007665079653875, 'min_weight_fraction_leaf': 0.04421727446740081}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8347639484978541
[I 2024-04-13 17:48:10,467] Trial 94 finished with value: 0.721176946423143 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 178, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.904130167714226, 'min_weight_fraction_leaf': 0.047285012436125234}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.7145922746781116
[I 2024-04-13 17:48:14,016] Trial 95 finished with value: 0.6926264721782838 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 184, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8559824051953817, 'min_weight_fraction_leaf': 0.10749281596606977}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7893617021276595
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.8369098712446352
[I 2024-04-13 17:48:17,006] Trial 96 finished with value: 0.7234863166632615 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 157, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9080663630381983, 'min_weight_fraction_leaf': 0.04614615882777642}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7553648068669528
[I 2024-04-13 17:48:19,758] Trial 97 finished with value: 0.7052353107898245 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 158, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9058530674494015, 'min_weight_fraction_leaf': 0.07474995134491569}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7680851063829788
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.7145922746781116
[I 2024-04-13 17:48:23,558] Trial 98 finished with value: 0.6808130386420753 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 205, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9313032187014408, 'min_weight_fraction_leaf': 0.16576392984791938}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8060836501901141

[I 2024-04-13 17:48:26,560] A new study created in memory with name: no-name-a952b83a-5a83-44f3-9efe-90e2af801107

Fold 5 C-index: 0.8240343347639485
[I 2024-04-13 17:48:26,527] Trial 99 finished with value: 0.7281519399606781 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 144, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9026987353436134, 'min_weight_fraction_leaf': 0.044978112106174015}. Best is trial 64 with value: 0.7483307845911831.


* Best trial for C-index:
 FrozenTrial(number=64, state=TrialState.COMPLETE, values=[0.7483307845911831], datetime_start=datetime.datetime(2024, 4, 13, 17, 46, 56, 466230), datetime_complete=datetime.datetime(2024, 4, 13, 17, 46, 57, 721488), params={'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 54, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8662742964997368, 'min_weight_fraction_leaf': 0.0017689713740798967}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=64, value=None)


* Best Score for C-index:
 0.7483307845911831

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23871639392045876
Fold 2 IBS: 0.22089740641981764
Fold 3 IBS: 0.20855935712684537
Fold 4 IBS: 0.22380699271581075
Fold 5 IBS: 0.20613806594659023
[I 2024-04-13 17:48:36,888] Trial 0 finished with value: 0.21962364322590452 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-13 17:48:51,146] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.2374084409354485
Fold 2 IBS: 0.21892351729489093
Fold 3 IBS: 0.21059085303920796
Fold 4 IBS: 0.22616820231302934
Fold 5 IBS: 0.21204655703132755
[I 2024-04-13 17:49:03,906] Trial 2 finished with value: 0.22102751412278088 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.23741407895783967
Fold 2 IBS: 0.21927599702285203
Fold 3 IBS: 0.21030069175680202
Fold 4 IBS: 0.22586626034487578
Fold 5 IBS: 0.21193073251533748
[I 2024-04-13 17:49:08,494] Trial 3 finished with value: 0.2209575521195414 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-13 17:49:18,166] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-13 17:49:23,467] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.23795541765613862
Fold 2 IBS: 0.21992985069618104
Fold 3 IBS: 0.2077002925377932
Fold 4 IBS: 0.2240482117618494
Fold 5 IBS: 0.20618770446779255
[I 2024-04-13 17:49:34,387] Trial 6 finished with value: 0.21916429542395094 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.23973193218549388
Fold 2 IBS: 0.21988145192818526
Fold 3 IBS: 0.20667039410505023
Fold 4 IBS: 0.22443830719746974
Fold 5 IBS: 0.20774030799163096
[I 2024-04-13 17:49:41,996] Trial 7 finished with value: 0.21969247868156602 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.2351732133658275
Fold 2 IBS: 0.22119237000388278
Fold 3 IBS: 0.21167563307535375
Fold 4 IBS: 0.22835359884410014
Fold 5 IBS: 0.21499909110450102
[I 2024-04-13 17:49:43,736] Trial 8 finished with value: 0.22227878127873302 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.23678701345213632
Fold 2 IBS: 0.2224692190085653
Fold 3 IBS: 0.2128128925717937
Fold 4 IBS: 0.22932300899141547
Fold 5 IBS: 0.21680976991247256
[I 2024-04-13 17:49:58,317] Trial 9 finished with value: 0.22364038078727666 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.24645397072894554
Fold 2 IBS: 0.23215165796624326
Fold 3 IBS: 0.2300072528605466
Fold 4 IBS: 0.24106162740477477
Fold 5 IBS: 0.23037976132987092
[I 2024-04-13 17:50:11,522] Trial 10 finished with value: 0.23601085405807623 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.2407112632523052
Fold 2 IBS: 0.22449406567870364
Fold 3 IBS: 0.21923219608031602
Fold 4 IBS: 0.23410601748321572
Fold 5 IBS: 0.22172302798577018
[I 2024-04-13 17:50:22,059] Trial 11 finished with value: 0.22805331409606217 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.2426583592791501
Fold 2 IBS: 0.22250934168617267
Fold 3 IBS: 0.2073988772356009
Fold 4 IBS: 0.22320546282719067
Fold 5 IBS: 0.20374832919376581
[I 2024-04-13 17:50:39,028] Trial 12 finished with value: 0.219904074044376 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.23681056601352704
Fold 2 IBS: 0.21942788812788447
Fold 3 IBS: 0.20647992664043885
Fold 4 IBS: 0.2235208106455191
Fold 5 IBS: 0.20836329684199373
[I 2024-04-13 17:50:50,970] Trial 13 finished with value: 0.21892049765387264 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6381530978163132, 'min_weight_fraction_leaf': 0.10302250602390595}. Best is trial 13 with value: 0.21892049765387264.
Fold 1 IBS: 0.24709076537787542
Fold 2 IBS: 0.23229758763044567
Fold 3 IBS: 0.22965399450652796
Fold 4 IBS: 0.2411751364309486
Fold 5 IBS: 0.23019081700505956
[I 2024-04-13 17:51:00,689] Trial 14 finished with value: 0.23608166019017146 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3469585144995889, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 13 with value: 0.21892049765387264.

Fold 1 IBS: 0.2364263642187732
Fold 2 IBS: 0.21964078635235235
Fold 3 IBS: 0.20489859443298694
Fold 4 IBS: 0.22388210534010178
Fold 5 IBS: 0.2090644999060323
[I 2024-04-13 17:51:13,887] Trial 15 finished with value: 0.2187824700500493 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6285201358789383, 'min_weight_fraction_leaf': 0.19381386025401764}. Best is trial 15 with value: 0.2187824700500493.
Fold 1 IBS: 0.24660428287886507
Fold 2 IBS: 0.2321257226396559
Fold 3 IBS: 0.22935330291437783
Fold 4 IBS: 0.24160728594857112
Fold 5 IBS: 0.23025975275058844
[I 2024-04-13 17:51:18,862] Trial 16 finished with value: 0.2359900694264117 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 175, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6923965021963807, 'min_weight_fraction_leaf': 0.35612645124522524}. Best is trial 15 with value: 0.2187824700500493.
Fold 1 IBS: 0.23684403651136585
Fold 2 IBS: 0.21959841448705122
Fold 3 IBS: 0.2056560421573172
Fold 4 IBS: 0.2233658304235327
Fold 5 IBS: 0.20846802289450317
[I 2024-04-13 17:51:29,650] Trial 17 finished with value: 0.21878646929475404 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 386, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6497544745873196, 'min_weight_fraction_leaf': 0.18481627132564235}. Best is trial 15 with value: 0.2187824700500493.
Fold 1 IBS: 0.23687920380677704
Fold 2 IBS: 0.21931414244607947
Fold 3 IBS: 0.20607205787956004
Fold 4 IBS: 0.22297392805924535
Fold 5 IBS: 0.2081887101022801
[I 2024-04-13 17:51:42,046] Trial 18 finished with value: 0.2186856084587884 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 20, 'n_estimators': 306, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8990048819755062, 'min_weight_fraction_leaf': 0.2019796911225918}. Best is trial 18 with value: 0.2186856084587884.
Fold 1 IBS: 0.23948146297755277
Fold 2 IBS: 0.22291910324934316
Fold 3 IBS: 0.21703121250088622
Fold 4 IBS: 0.23627081582775644
Fold 5 IBS: 0.2207432460911561
[I 2024-04-13 17:51:46,620] Trial 19 finished with value: 0.22728916812933891 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 111, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8794499855344343, 'min_weight_fraction_leaf': 0.4027720168515806}. Best is trial 18 with value: 0.2186856084587884.
Fold 1 IBS: 0.23688471445852777
Fold 2 IBS: 0.21913272259306837
Fold 3 IBS: 0.2059111669673491
Fold 4 IBS: 0.22283459872246641
Fold 5 IBS: 0.20816131265171223
[I 2024-04-13 17:51:59,295] Trial 20 finished with value: 0.21858490307862474 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 311, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9051233789152774, 'min_weight_fraction_leaf': 0.2509729370060225}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.23689478020829297
Fold 2 IBS: 0.21939083507476845
Fold 3 IBS: 0.20544637636114435
Fold 4 IBS: 0.22331937617631895
Fold 5 IBS: 0.20823609391962125
[I 2024-04-13 17:52:09,773] Trial 21 finished with value: 0.2186574923480292 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 307, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8936004056067098, 'min_weight_fraction_leaf': 0.2584106737011842}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.23702655392249034
Fold 2 IBS: 0.21934691338037202
Fold 3 IBS: 0.20599414039818612
Fold 4 IBS: 0.2232183658358969
Fold 5 IBS: 0.20818608847087738
[I 2024-04-13 17:52:21,400] Trial 22 finished with value: 0.21875441240156457 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 315, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9078735647156028, 'min_weight_fraction_leaf': 0.25581625155530263}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.2370523143627765
Fold 2 IBS: 0.2196008201014214
Fold 3 IBS: 0.2036559885615786
Fold 4 IBS: 0.22413209063537776
Fold 5 IBS: 0.20904466830379478
[I 2024-04-13 17:52:30,811] Trial 23 finished with value: 0.21869717639298983 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 233, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8927030957052547, 'min_weight_fraction_leaf': 0.2990139029425277}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.24203440231995213
Fold 2 IBS: 0.22554360580458416
Fold 3 IBS: 0.20628337998076055
Fold 4 IBS: 0.2289849237284239
Fold 5 IBS: 0.20599130514353636
[I 2024-04-13 17:52:42,551] Trial 24 finished with value: 0.22176752339545142 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 19, 'n_estimators': 295, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8693046937847292, 'min_weight_fraction_leaf': 0.24639043366252525}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.23623063868086489
Fold 2 IBS: 0.22005171287892328
Fold 3 IBS: 0.20422974897888901
Fold 4 IBS: 0.2262320541568372
Fold 5 IBS: 0.21001474317155738
[I 2024-04-13 17:52:51,102] Trial 25 finished with value: 0.21935177957341434 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 231, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.996738340265135, 'min_weight_fraction_leaf': 0.3690600107806249}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.23675440837764497
Fold 2 IBS: 0.22076702165491713
Fold 3 IBS: 0.20849128508971132
Fold 4 IBS: 0.22924365118701112
Fold 5 IBS: 0.2124099236622402
[I 2024-04-13 17:53:04,522] Trial 26 finished with value: 0.22153325799430493 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 1, 'n_estimators': 318, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7243128593918586, 'min_weight_fraction_leaf': 0.2941984778571687}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.2371660771729202
Fold 2 IBS: 0.2191483603239057
Fold 3 IBS: 0.20641747737853533
Fold 4 IBS: 0.22240690608445848
Fold 5 IBS: 0.20799076460934937
[I 2024-04-13 17:53:16,985] Trial 27 finished with value: 0.21862591711383378 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 261, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8361953498806727, 'min_weight_fraction_leaf': 0.22280258441739995}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.2463193986283167
Fold 2 IBS: 0.23207829291467785
Fold 3 IBS: 0.22966403015817585
Fold 4 IBS: 0.24154609978869193
Fold 5 IBS: 0.23030134578230163
[I 2024-04-13 17:53:22,215] Trial 28 finished with value: 0.2359818334544328 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 114, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8280204053136692, 'min_weight_fraction_leaf': 0.4367390598534441}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.23713924585846832
Fold 2 IBS: 0.21931758118462666
Fold 3 IBS: 0.20367479460476934
Fold 4 IBS: 0.22408618002403552
Fold 5 IBS: 0.20895070313530809
[I 2024-04-13 17:53:33,012] Trial 29 finished with value: 0.21863370096144158 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 260, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7271476705971293, 'min_weight_fraction_leaf': 0.23367475592947387}. Best is trial 20 with value: 0.21858490307862474.

Fold 1 IBS: 0.23738806550248728
Fold 2 IBS: 0.21993578889192347
Fold 3 IBS: 0.21089498091706652
Fold 4 IBS: 0.2272048730326933
Fold 5 IBS: 0.2132773803587104
[I 2024-04-13 17:53:43,167] Trial 30 finished with value: 0.2217402177405762 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 206, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7311100810851326, 'min_weight_fraction_leaf': 0.16969817682654836}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.2371472983744441
Fold 2 IBS: 0.2192317816045922
Fold 3 IBS: 0.2066273024000569
Fold 4 IBS: 0.2223268600858535
Fold 5 IBS: 0.20805506169911736
[I 2024-04-13 17:53:54,940] Trial 31 finished with value: 0.21867766083281284 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 3, 'n_estimators': 259, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8479425058967354, 'min_weight_fraction_leaf': 0.22878903104829593}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.24223910593371958
Fold 2 IBS: 0.2264118903341529
Fold 3 IBS: 0.20731329208194677
Fold 4 IBS: 0.2287610862946042
Fold 5 IBS: 0.20611174516637162
[I 2024-04-13 17:54:16,039] Trial 32 finished with value: 0.22216742396215902 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 339, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9446205451617458, 'min_weight_fraction_leaf': 0.2661809737444116}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.2370219997072243
Fold 2 IBS: 0.2193941053757161
Fold 3 IBS: 0.20373501168298777
Fold 4 IBS: 0.22393480585520856
Fold 5 IBS: 0.208682475587371
[I 2024-04-13 17:54:27,461] Trial 33 finished with value: 0.21855367964170153 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 275, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7377604544275241, 'min_weight_fraction_leaf': 0.22731537286697645}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23710344518730503
Fold 2 IBS: 0.2193601565250112
Fold 3 IBS: 0.20377799030194124
Fold 4 IBS: 0.2240022784938735
Fold 5 IBS: 0.20864844068886612
[I 2024-04-13 17:54:40,517] Trial 34 finished with value: 0.21857846223939942 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 271, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7374664327129382, 'min_weight_fraction_leaf': 0.23191073374208002}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23764750710635235
Fold 2 IBS: 0.22052485431514102
Fold 3 IBS: 0.2086989128573178
Fold 4 IBS: 0.22954355044719715
Fold 5 IBS: 0.21248255472686303
[I 2024-04-13 17:54:49,148] Trial 35 finished with value: 0.22177947589057428 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 212, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8058295418292518, 'min_weight_fraction_leaf': 0.3249726897940118}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23783380527100748
Fold 2 IBS: 0.2211380677742572
Fold 3 IBS: 0.21185207127663558
Fold 4 IBS: 0.22796138018690684
Fold 5 IBS: 0.2144294358021491
[I 2024-04-13 17:55:01,392] Trial 36 finished with value: 0.22264295206219123 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 279, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.5117163187171705, 'min_weight_fraction_leaf': 0.1607072150760065}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23677886144704816
Fold 2 IBS: 0.21955413132469867
Fold 3 IBS: 0.2059952807810265
Fold 4 IBS: 0.22795770153840889
Fold 5 IBS: 0.21078869878851952
[I 2024-04-13 17:55:09,784] Trial 37 finished with value: 0.22021493477594034 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 166, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5977432205420752, 'min_weight_fraction_leaf': 0.2121573650483426}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.24300840277727823
Fold 2 IBS: 0.22638067512276036
Fold 3 IBS: 0.20873415213457244
Fold 4 IBS: 0.22741267505514887
Fold 5 IBS: 0.20459574979480916
[I 2024-04-13 17:55:22,535] Trial 38 finished with value: 0.2220263309769138 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6852629549788185, 'min_weight_fraction_leaf': 0.11814667951535995}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23763664595441686
Fold 2 IBS: 0.21963674238171244
Fold 3 IBS: 0.20765975936600614
Fold 4 IBS: 0.22271331629056146
Fold 5 IBS: 0.20771351346868874
[I 2024-04-13 17:55:28,121] Trial 39 finished with value: 0.21907199549227713 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 131, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9480058935053208, 'min_weight_fraction_leaf': 0.07199443797246757}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23944651370037162
Fold 2 IBS: 0.22439860558737096
Fold 3 IBS: 0.21824376490286634
Fold 4 IBS: 0.2342014368701815
Fold 5 IBS: 0.22112013449236526
[I 2024-04-13 17:55:41,161] Trial 40 finished with value: 0.22748209111063114 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 228, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7703151429728522, 'min_weight_fraction_leaf': 0.3250233317588423}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23712006600581267
Fold 2 IBS: 0.21925666827113804
Fold 3 IBS: 0.20438121866317888
Fold 4 IBS: 0.22426221223278658
Fold 5 IBS: 0.2089755505545177
[I 2024-04-13 17:55:53,303] Trial 41 finished with value: 0.21879914314548676 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 252, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7128779131299335, 'min_weight_fraction_leaf': 0.22502514085583183}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23636287267696218
Fold 2 IBS: 0.21965157568819133
Fold 3 IBS: 0.20429145447374908
Fold 4 IBS: 0.2262599855613196
Fold 5 IBS: 0.21087596893375274
[I 2024-04-13 17:56:06,764] Trial 42 finished with value: 0.21948837146679495 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5, 'n_estimators': 276, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7533545355944256, 'min_weight_fraction_leaf': 0.27846129528158403}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.2366430134802846
Fold 2 IBS: 0.2194294067711963
Fold 3 IBS: 0.20575727644969144
Fold 4 IBS: 0.22313820960120131
Fold 5 IBS: 0.20834548638251957
[I 2024-04-13 17:56:23,342] Trial 43 finished with value: 0.21866267853697866 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 338, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8281942894155514, 'min_weight_fraction_leaf': 0.2362690293240371}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.2372930246571929
Fold 2 IBS: 0.22118755709584256
Fold 3 IBS: 0.21148108493389597
Fold 4 IBS: 0.22832759817438522
Fold 5 IBS: 0.21477380864590534
[I 2024-04-13 17:56:38,279] Trial 44 finished with value: 0.2226126147014444 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 244, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7654866467245561, 'min_weight_fraction_leaf': 0.1765984915124157}. Best is trial 33 with value: 0.21855367964170153.

Fold 1 IBS: 0.24647150063770518
Fold 2 IBS: 0.2324005238674857
Fold 3 IBS: 0.2295165680261027
Fold 4 IBS: 0.2413350176086155
Fold 5 IBS: 0.23048981014618952
[I 2024-04-13 17:56:47,249] Trial 45 finished with value: 0.2360426840572197 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 184, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.42889080150309455, 'min_weight_fraction_leaf': 0.30395190085793466}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23684554782082465
Fold 2 IBS: 0.21919333404974234
Fold 3 IBS: 0.2053013505980981
Fold 4 IBS: 0.22292477589597334
Fold 5 IBS: 0.20836678612341789
[I 2024-04-13 17:57:01,359] Trial 46 finished with value: 0.21852635889761127 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 6, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8006072320599792, 'min_weight_fraction_leaf': 0.13827431215955044}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2399589768301317
Fold 2 IBS: 0.21880138930071588
Fold 3 IBS: 0.20629667242484592
Fold 4 IBS: 0.22636534251393303
Fold 5 IBS: 0.20974876234700723
[I 2024-04-13 17:57:03,342] Trial 47 finished with value: 0.22023422868332676 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 5, 'n_estimators': 31, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9475835682044488, 'min_weight_fraction_leaf': 0.14470027059329618}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23734004410610962
Fold 2 IBS: 0.22033178260287098
Fold 3 IBS: 0.21077176125721195
Fold 4 IBS: 0.22656543896147213
Fold 5 IBS: 0.21330307068589224
[I 2024-04-13 17:57:16,295] Trial 48 finished with value: 0.2216624195227114 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 284, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7986195780539649, 'min_weight_fraction_leaf': 0.04617548779812293}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23625124939716474
Fold 2 IBS: 0.21928917010690835
Fold 3 IBS: 0.2063591757019585
Fold 4 IBS: 0.22331625230525182
Fold 5 IBS: 0.20765154418716986
[I 2024-04-13 17:57:34,607] Trial 49 finished with value: 0.21857347833969065 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 424, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6815323326726881, 'min_weight_fraction_leaf': 0.09131723435674605}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2371187672752822
Fold 2 IBS: 0.21915942871564578
Fold 3 IBS: 0.20721255481618547
Fold 4 IBS: 0.22373050792840368
Fold 5 IBS: 0.20722944561545947
[I 2024-04-13 17:57:56,813] Trial 50 finished with value: 0.21889014087019532 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 475, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5949002626903728, 'min_weight_fraction_leaf': 0.09564369461405195}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23657837413281252
Fold 2 IBS: 0.21921373961408827
Fold 3 IBS: 0.20641430152871024
Fold 4 IBS: 0.22325153046230709
Fold 5 IBS: 0.20771396879094767
[I 2024-04-13 17:58:14,587] Trial 51 finished with value: 0.21863438290577314 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 418, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6711715875812826, 'min_weight_fraction_leaf': 0.12567164193121433}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2357343048159532
Fold 2 IBS: 0.21949424689270622
Fold 3 IBS: 0.2062245962595048
Fold 4 IBS: 0.22302319513557203
Fold 5 IBS: 0.2082914380694619
[I 2024-04-13 17:58:31,620] Trial 52 finished with value: 0.21855355623463962 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 436, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8355484780724112, 'min_weight_fraction_leaf': 0.06356770563405467}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23588775448783578
Fold 2 IBS: 0.21960499379966134
Fold 3 IBS: 0.20560863855751482
Fold 4 IBS: 0.22328194893439646
Fold 5 IBS: 0.20844111520648279
[I 2024-04-13 17:58:53,178] Trial 53 finished with value: 0.21856489019717823 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 3, 'n_estimators': 445, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7933316926807014, 'min_weight_fraction_leaf': 0.0745088611285212}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2459142809877375
Fold 2 IBS: 0.23209907466514498
Fold 3 IBS: 0.23006719908315112
Fold 4 IBS: 0.2412636990636345
Fold 5 IBS: 0.22997918328901845
[I 2024-04-13 17:59:23,641] Trial 54 finished with value: 0.23586468741773733 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 471, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.1465843595834484, 'min_weight_fraction_leaf': 0.0717996537719882}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23562563262770414
Fold 2 IBS: 0.22039354813161444
Fold 3 IBS: 0.20584972692935538
Fold 4 IBS: 0.22772502361054814
Fold 5 IBS: 0.21102864376883282
[I 2024-04-13 17:59:44,955] Trial 55 finished with value: 0.220124515013611 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 2, 'n_estimators': 447, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6195893286059789, 'min_weight_fraction_leaf': 0.020919354828291575}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23563295735954615
Fold 2 IBS: 0.21981277016407383
Fold 3 IBS: 0.204989658791369
Fold 4 IBS: 0.22532191283924616
Fold 5 IBS: 0.20939381856897557
[I 2024-04-13 18:00:05,829] Trial 56 finished with value: 0.21903022354464213 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 446, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6675798400299233, 'min_weight_fraction_leaf': 0.05410607583171402}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.235618718908947
Fold 2 IBS: 0.21973289084248274
Fold 3 IBS: 0.20557239685044001
Fold 4 IBS: 0.2237231663542185
Fold 5 IBS: 0.20836154108703234
[I 2024-04-13 18:00:27,616] Trial 57 finished with value: 0.21860174280862413 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2, 'n_estimators': 415, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5287318340211359, 'min_weight_fraction_leaf': 0.07961343183750659}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.236519319875315
Fold 2 IBS: 0.21950443141544193
Fold 3 IBS: 0.2063407204825024
Fold 4 IBS: 0.22283999560765866
Fold 5 IBS: 0.2081772921338352
[I 2024-04-13 18:00:49,694] Trial 58 finished with value: 0.21867635190295065 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 378, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.803287559716288, 'min_weight_fraction_leaf': 0.027007649016910218}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2354748473353207
Fold 2 IBS: 0.21970210525532657
Fold 3 IBS: 0.20440838433289102
Fold 4 IBS: 0.22472430202794327
Fold 5 IBS: 0.20891913786948146
[I 2024-04-13 18:01:11,679] Trial 59 finished with value: 0.2186457553641926 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 3, 'n_estimators': 489, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7473762466460354, 'min_weight_fraction_leaf': 0.1132881773249865}. Best is trial 46 with value: 0.21852635889761127.

Fold 1 IBS: 0.2427874690307322
Fold 2 IBS: 0.22051307489638503
Fold 3 IBS: 0.21103171261194614
Fold 4 IBS: 0.22387533549578809
Fold 5 IBS: 0.2083271491005745
[I 2024-04-13 18:01:15,710] Trial 60 finished with value: 0.22130694822708522 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 74, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7017596527420207, 'min_weight_fraction_leaf': 0.09966382421080089}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23644800149579903
Fold 2 IBS: 0.2195369287078321
Fold 3 IBS: 0.20653996690015303
Fold 4 IBS: 0.22236489358251474
Fold 5 IBS: 0.20806793260763023
[I 2024-04-13 18:01:39,699] Trial 61 finished with value: 0.21859154465878583 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 357, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8453989714566266, 'min_weight_fraction_leaf': 0.0854881672929427}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23643029999972073
Fold 2 IBS: 0.21967560573705663
Fold 3 IBS: 0.20695855958876064
Fold 4 IBS: 0.22295379459110656
Fold 5 IBS: 0.20740851343462946
[I 2024-04-13 18:01:59,243] Trial 62 finished with value: 0.2186853546702548 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 405, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7864119714099438, 'min_weight_fraction_leaf': 0.03355471126999637}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23662020640249384
Fold 2 IBS: 0.22044682985730565
Fold 3 IBS: 0.2110430430738999
Fold 4 IBS: 0.22659401764816547
Fold 5 IBS: 0.21345170889609122
[I 2024-04-13 18:02:19,055] Trial 63 finished with value: 0.22163116117559117 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 452, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9253967049917359, 'min_weight_fraction_leaf': 0.13189925217057735}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23588117694688576
Fold 2 IBS: 0.21950400748600946
Fold 3 IBS: 0.20743744610362147
Fold 4 IBS: 0.2227219004724267
Fold 5 IBS: 0.20797214307427977
[I 2024-04-13 18:02:40,098] Trial 64 finished with value: 0.21870333481664464 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 18, 'max_depth': 10, 'n_estimators': 435, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8760174816172069, 'min_weight_fraction_leaf': 0.19634298369623576}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.24293657429451518
Fold 2 IBS: 0.22609344656173974
Fold 3 IBS: 0.20815359502812622
Fold 4 IBS: 0.22908562033306976
Fold 5 IBS: 0.20580516572696153
[I 2024-04-13 18:02:56,301] Trial 65 finished with value: 0.2224148803888825 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 390, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8550412886514629, 'min_weight_fraction_leaf': 0.06484834781781368}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.246326123904824
Fold 2 IBS: 0.2321429620809124
Fold 3 IBS: 0.2296037213979481
Fold 4 IBS: 0.24153389713884624
Fold 5 IBS: 0.2302471952197853
[I 2024-04-13 18:03:14,920] Trial 66 finished with value: 0.23597077994846322 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 462, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7546667172212993, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23707512834232153
Fold 2 IBS: 0.21930013195726877
Fold 3 IBS: 0.20789588893960737
Fold 4 IBS: 0.22277962404199228
Fold 5 IBS: 0.20734369610194425
[I 2024-04-13 18:03:30,513] Trial 67 finished with value: 0.21887889387662685 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 430, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8170420213592718, 'min_weight_fraction_leaf': 0.1494978367406185}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2462463594686935
Fold 2 IBS: 0.23217393417283155
Fold 3 IBS: 0.229993630453562
Fold 4 IBS: 0.24115987912128561
Fold 5 IBS: 0.23020109107235417
[I 2024-04-13 18:03:44,516] Trial 68 finished with value: 0.23595497885774538 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 368, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.22939188072225208, 'min_weight_fraction_leaf': 0.10857553018551594}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2368310555074388
Fold 2 IBS: 0.21920878877902486
Fold 3 IBS: 0.20679480272253697
Fold 4 IBS: 0.22280458336806014
Fold 5 IBS: 0.2080990839318608
[I 2024-04-13 18:03:56,089] Trial 69 finished with value: 0.21874766286178432 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 302, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9150371780503119, 'min_weight_fraction_leaf': 0.15865717014764769}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23586697340396454
Fold 2 IBS: 0.22032829223579578
Fold 3 IBS: 0.20643967315282094
Fold 4 IBS: 0.22766226779737594
Fold 5 IBS: 0.21151359247240697
[I 2024-04-13 18:04:05,684] Trial 70 finished with value: 0.22036215981247284 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 15, 'n_estimators': 327, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6977835794345164, 'min_weight_fraction_leaf': 0.269542416852923}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2364558746726569
Fold 2 IBS: 0.2194623320684367
Fold 3 IBS: 0.20706917788988619
Fold 4 IBS: 0.22248122115912292
Fold 5 IBS: 0.20803169557605336
[I 2024-04-13 18:04:19,272] Trial 71 finished with value: 0.21870006027323124 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 366, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8654671343704606, 'min_weight_fraction_leaf': 0.07738198203736042}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23647397626404196
Fold 2 IBS: 0.2193778137976921
Fold 3 IBS: 0.2067575067362915
Fold 4 IBS: 0.22269242363774733
Fold 5 IBS: 0.20796186727425015
[I 2024-04-13 18:04:31,949] Trial 72 finished with value: 0.2186527175420046 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 4, 'n_estimators': 350, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8467228912812281, 'min_weight_fraction_leaf': 0.09173299321647771}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23670700550925744
Fold 2 IBS: 0.2192987886199061
Fold 3 IBS: 0.20442982953084754
Fold 4 IBS: 0.223141013709078
Fold 5 IBS: 0.2083234731520686
[I 2024-04-13 18:04:50,343] Trial 73 finished with value: 0.21838002210423152 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 291, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7842377375661996, 'min_weight_fraction_leaf': 0.04843949872109438}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23699285632626652
Fold 2 IBS: 0.2193550533373929
Fold 3 IBS: 0.20452511359216702
Fold 4 IBS: 0.2231256237020124
Fold 5 IBS: 0.2084643072267637
[I 2024-04-13 18:05:02,487] Trial 74 finished with value: 0.2184925908369205 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7811091062956046, 'min_weight_fraction_leaf': 0.04068939245007144}. Best is trial 73 with value: 0.21838002210423152.

Fold 1 IBS: 0.23757083460058645
Fold 2 IBS: 0.21936835681341144
Fold 3 IBS: 0.2050586023900099
Fold 4 IBS: 0.2231460133461373
Fold 5 IBS: 0.20844072705559955
[I 2024-04-13 18:05:10,423] Trial 75 finished with value: 0.21871690684114892 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 220, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7803578114864529, 'min_weight_fraction_leaf': 0.017478919548903803}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23640141704565878
Fold 2 IBS: 0.2197885256064894
Fold 3 IBS: 0.20318516882698215
Fold 4 IBS: 0.22544681939994865
Fold 5 IBS: 0.20897452087659646
[I 2024-04-13 18:05:23,826] Trial 76 finished with value: 0.21875929035113512 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 3, 'n_estimators': 293, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7310311308084682, 'min_weight_fraction_leaf': 0.053169984941233435}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23741868189676912
Fold 2 IBS: 0.21959001344865917
Fold 3 IBS: 0.20405006070074652
Fold 4 IBS: 0.2243018125512366
Fold 5 IBS: 0.20899734290866995
[I 2024-04-13 18:05:38,885] Trial 77 finished with value: 0.21887158230121626 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 268, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.643528798832142, 'min_weight_fraction_leaf': 0.0035897778567450314}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.2371288491562036
Fold 2 IBS: 0.21921237425444545
Fold 3 IBS: 0.20589294929880203
Fold 4 IBS: 0.22345690243536823
Fold 5 IBS: 0.20790079002157127
[I 2024-04-13 18:05:49,553] Trial 78 finished with value: 0.21871837303327815 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 242, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7399586324559952, 'min_weight_fraction_leaf': 0.036709963240196763}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23718809155484707
Fold 2 IBS: 0.22092106114932006
Fold 3 IBS: 0.21060969393168538
Fold 4 IBS: 0.22820373722606627
Fold 5 IBS: 0.21420368130993808
[I 2024-04-13 18:05:58,205] Trial 79 finished with value: 0.22222525303437135 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 194, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7825507541105653, 'min_weight_fraction_leaf': 0.06153431383484739}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23685165015175644
Fold 2 IBS: 0.22068620321605817
Fold 3 IBS: 0.21160479990748687
Fold 4 IBS: 0.2270351319118709
Fold 5 IBS: 0.21394471822408284
[I 2024-04-13 18:06:21,069] Trial 80 finished with value: 0.22202450068225105 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 3, 'n_estimators': 498, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8206233780498613, 'min_weight_fraction_leaf': 0.01586721934758055}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23680935988687354
Fold 2 IBS: 0.21919210664973693
Fold 3 IBS: 0.2062865708031109
Fold 4 IBS: 0.22287903889466332
Fold 5 IBS: 0.20798592164828278
[I 2024-04-13 18:06:31,586] Trial 81 finished with value: 0.2186305995765335 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 286, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9683267170659943, 'min_weight_fraction_leaf': 0.24820532660386305}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.24167770220133805
Fold 2 IBS: 0.2258829783356682
Fold 3 IBS: 0.20506103877881593
Fold 4 IBS: 0.22848023645111828
Fold 5 IBS: 0.20603856384248168
[I 2024-04-13 18:06:45,185] Trial 82 finished with value: 0.22142810392188444 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 320, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8081851033669109, 'min_weight_fraction_leaf': 0.2131921119494233}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.237582647636615
Fold 2 IBS: 0.21884473486373132
Fold 3 IBS: 0.20742387029349543
Fold 4 IBS: 0.22292165310774673
Fold 5 IBS: 0.2070931524860315
[I 2024-04-13 18:06:54,666] Trial 83 finished with value: 0.21877321167752398 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 267, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8844309504688548, 'min_weight_fraction_leaf': 0.04798854332402432}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.241147785841093
Fold 2 IBS: 0.22383836423992348
Fold 3 IBS: 0.2177963735816699
Fold 4 IBS: 0.23542582564536244
Fold 5 IBS: 0.21963595295530872
[I 2024-04-13 18:07:05,306] Trial 84 finished with value: 0.2275688604526715 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 251, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6787600211894828, 'min_weight_fraction_leaf': 0.30903976828584095}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23734464582042714
Fold 2 IBS: 0.21899391617714345
Fold 3 IBS: 0.2064153028397821
Fold 4 IBS: 0.2224135340583663
Fold 5 IBS: 0.20678778466052464
[I 2024-04-13 18:07:16,137] Trial 85 finished with value: 0.21839103671124876 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 302, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7180827163665513, 'min_weight_fraction_leaf': 0.13602688437706084}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23705812324052997
Fold 2 IBS: 0.21938000194478852
Fold 3 IBS: 0.20530300805717408
Fold 4 IBS: 0.22311578502650944
Fold 5 IBS: 0.20780067210384995
[I 2024-04-13 18:07:28,657] Trial 86 finished with value: 0.21853151807457039 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 302, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7162022295222917, 'min_weight_fraction_leaf': 0.1842957273625047}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23798090366751265
Fold 2 IBS: 0.21947291839956856
Fold 3 IBS: 0.2072184272517321
Fold 4 IBS: 0.22385467669715983
Fold 5 IBS: 0.20690325084134892
[I 2024-04-13 18:07:41,166] Trial 87 finished with value: 0.2190860353714644 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 298, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7693492945351396, 'min_weight_fraction_leaf': 0.13025024094881313}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.2368388275008215
Fold 2 IBS: 0.2193855222635841
Fold 3 IBS: 0.20536349150839933
Fold 4 IBS: 0.22301598241068915
Fold 5 IBS: 0.20804959246559787
[I 2024-04-13 18:07:53,467] Trial 88 finished with value: 0.2185306832298184 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7116913427696117, 'min_weight_fraction_leaf': 0.19026372034651004}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23694872131026606
Fold 2 IBS: 0.21935524065357095
Fold 3 IBS: 0.20576763462390152
Fold 4 IBS: 0.22301199290133028
Fold 5 IBS: 0.20810669911009236
[I 2024-04-13 18:08:06,939] Trial 89 finished with value: 0.21863805771983227 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 327, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7139844393284589, 'min_weight_fraction_leaf': 0.18909187879978934}. Best is trial 73 with value: 0.21838002210423152.

Fold 1 IBS: 0.237217800059635
Fold 2 IBS: 0.219560418627486
Fold 3 IBS: 0.2055584995526966
Fold 4 IBS: 0.22351950054338868
Fold 5 IBS: 0.20798078328178596
[I 2024-04-13 18:08:17,325] Trial 90 finished with value: 0.21876740041299841 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 306, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6578960771293777, 'min_weight_fraction_leaf': 0.16477439734294264}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.236951540585596
Fold 2 IBS: 0.21950546902732596
Fold 3 IBS: 0.20504430850227562
Fold 4 IBS: 0.22315671121676062
Fold 5 IBS: 0.20782359042139878
[I 2024-04-13 18:08:28,126] Trial 91 finished with value: 0.21849632395067142 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6954217194025099, 'min_weight_fraction_leaf': 0.18407738961451633}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.2366590015736694
Fold 2 IBS: 0.21937029886615486
Fold 3 IBS: 0.20566183543415947
Fold 4 IBS: 0.22301451578556367
Fold 5 IBS: 0.20767409548411542
[I 2024-04-13 18:08:40,058] Trial 92 finished with value: 0.21847594942873255 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 291, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7009588430592851, 'min_weight_fraction_leaf': 0.178489497157845}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23687600031261338
Fold 2 IBS: 0.21924088383926293
Fold 3 IBS: 0.2054016930393524
Fold 4 IBS: 0.22302835737032672
Fold 5 IBS: 0.2077489452850229
[I 2024-04-13 18:08:52,213] Trial 93 finished with value: 0.2184591759693157 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7172196194520072, 'min_weight_fraction_leaf': 0.18587233706768527}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23703019354236293
Fold 2 IBS: 0.21948639464154246
Fold 3 IBS: 0.2047505157929676
Fold 4 IBS: 0.2235047542533873
Fold 5 IBS: 0.20855863469046315
[I 2024-04-13 18:09:03,247] Trial 94 finished with value: 0.2186660985841447 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 292, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6219714175446479, 'min_weight_fraction_leaf': 0.18072151749890458}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23692361705128714
Fold 2 IBS: 0.21966953779580314
Fold 3 IBS: 0.20471111021867852
Fold 4 IBS: 0.22299044301485235
Fold 5 IBS: 0.20816654210822538
[I 2024-04-13 18:09:15,677] Trial 95 finished with value: 0.21849225003776934 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 317, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7079376941574543, 'min_weight_fraction_leaf': 0.205035720310988}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23653137028059623
Fold 2 IBS: 0.2197358793548492
Fold 3 IBS: 0.20502556689280826
Fold 4 IBS: 0.22583981363051878
Fold 5 IBS: 0.20976127923417956
[I 2024-04-13 18:09:28,126] Trial 96 finished with value: 0.2193787818785904 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5801992264153996, 'min_weight_fraction_leaf': 0.2036293513522096}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23691132713166155
Fold 2 IBS: 0.21934888168734706
Fold 3 IBS: 0.2060353520597031
Fold 4 IBS: 0.2230362471179694
Fold 5 IBS: 0.20779263064091014
[I 2024-04-13 18:09:41,349] Trial 97 finished with value: 0.21862488772751826 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 328, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.705642847473056, 'min_weight_fraction_leaf': 0.17148295318003226}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.237230513240583
Fold 2 IBS: 0.2192840978709365
Fold 3 IBS: 0.20624346451793507
Fold 4 IBS: 0.2233785003281718
Fold 5 IBS: 0.20807621679976449
[I 2024-04-13 18:09:54,549] Trial 98 finished with value: 0.21884255855147816 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 343, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6399955222854865, 'min_weight_fraction_leaf': 0.1529848101895856}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23707199815043145
Fold 2 IBS: 0.21927691514345446
Fold 3 IBS: 0.20538898879208908
Fold 4 IBS: 0.2230658739211438
Fold 5 IBS: 0.20786983407137138
[I 2024-04-13 18:10:05,763] Trial 99 finished with value: 0.21853472201569804 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 279, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7197685650294967, 'min_weight_fraction_leaf': 0.18553539660920623}. Best is trial 73 with value: 0.21838002210423152.


* Best trial for IBS:
 FrozenTrial(number=73, state=TrialState.COMPLETE, values=[0.21838002210423152], datetime_start=datetime.datetime(2024, 4, 13, 18, 4, 31, 955837), datetime_complete=datetime.datetime(2024, 4, 13, 18, 4, 50, 342316), params={'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 291, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7842377375661996, 'min_weight_fraction_leaf': 0.04843949872109438}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=73, value=None)


* Best Score for IBS:
 0.21838002210423152

In [81]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [82]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.748
train_ibs:  0.218

#### Test

In [83]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [84]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=11, max_leaf_nodes=17,
                   max_samples=0.8662742964997368, min_samples_leaf=1,
                   min_samples_split=19,
                   min_weight_fraction_leaf=0.0017689713740798967,
                   n_estimators=54, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.585

ExtraSurvivalTrees(max_depth=2, max_features='auto', max_leaf_nodes=20,
                   max_samples=0.7842377375661996, min_samples_leaf=19,
                   min_samples_split=19,
                   min_weight_fraction_leaf=0.04843949872109438,
                   n_estimators=291, oob_score=True, random_state=123)

IBS: 0.213

In [85]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [86]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 18:10:08,563] A new study created in memory with name: no-name-2768d6b9-f594-4426-a7f9-39cd2b8d57b2

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:11:14,882] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:11:49,189] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:12:22,934] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:13:12,985] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:13:32,929] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:13:38,337] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:14:27,982] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:14:45,044] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:14:46,744] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5796812749003984
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 18:16:55,971] Trial 9 finished with value: 0.6172849274886952 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6172849274886952.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 18:20:28,651] Trial 10 finished with value: 0.5915509861883201 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6172849274886952.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:24:20,421] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6172849274886952.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6234042553191489
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 18:27:52,717] Trial 12 finished with value: 0.6288581469840132 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.6288581469840132.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:29:25,626] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:31:44,272] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:33:44,213] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:34:58,355] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:37:26,000] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:41:14,663] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:41:22,613] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:42:36,988] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:45:15,567] Trial 21 finished with value: 0.5 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6182170542635659
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.6596958174904943
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 18:47:45,502] Trial 22 finished with value: 0.6233941406142943 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:49:45,900] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:51:32,807] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:52:35,958] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:54:50,686] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:57:09,437] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:59:10,314] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:00:36,688] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:02:17,517] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:05:35,477] Trial 31 finished with value: 0.5071713147410358 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:08:44,896] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:10:42,359] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:13:30,454] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:14:05,211] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:16:59,036] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:17:04,581] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 12 with value: 0.6288581469840132.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:18:14,771] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:20:14,003] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:23:14,120] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 19:23:14,633] Trial 41 finished with value: 0.6039152174760968 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6008583690987125
[I 2024-04-13 19:23:35,085] Trial 42 finished with value: 0.624004230389207 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:23:36,108] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8735505723796891, 'learning_rate': 0.013455915558851193, 'dropout_rate': 0.11585930219083569, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 1.1546454041172216, 'min_weight_fraction_leaf': 0.4571018098895751, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8650432234384267, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:24:33,140] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9479336661285427, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.25335630680617827, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.4126953497238681, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.9438667820963776, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 19:24:50,814] Trial 45 finished with value: 0.636916827084602 and parameters: {'subsample': 0.5852424762732177, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.027804703729289008, 'min_weight_fraction_leaf': 0.262143273989599, 'max_features': 0.1, 'min_impurity_decrease': 9.467252666446998e-07, 'validation_fraction': 0.7243304021069044, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 45 with value: 0.636916827084602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:24:55,482] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.0647255784094387, 'dropout_rate': 0.9694253886674298, 'n_estimators': 130, 'criterion': 'squared_error', 'ccp_alpha': 1.9903431110600875, 'min_weight_fraction_leaf': 0.2621149519999694, 'max_features': 0.1, 'min_impurity_decrease': 1.8213591543920705e-06, 'validation_fraction': 0.7149599360255287, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 45 with value: 0.636916827084602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:25:20,266] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.45583884600027197, 'learning_rate': 0.06333641179361332, 'dropout_rate': 0.19790330487666663, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.14638041253524992, 'max_features': 0.1, 'min_impurity_decrease': 9.138461248752069e-07, 'validation_fraction': 0.6499098781754827, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 45 with value: 0.636916827084602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:25:26,385] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.584713932884162, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.27951884808649285, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 1.4079486283020177, 'min_weight_fraction_leaf': 0.21342970007180673, 'max_features': 0.1, 'min_impurity_decrease': 2.4988708934303504e-06, 'validation_fraction': 0.5884862057231304, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 45 with value: 0.636916827084602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:25:48,151] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.5312512417393443, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3775922041148432, 'min_weight_fraction_leaf': 0.2316969754016241, 'max_features': 'log2', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.8162506488425402, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 45 with value: 0.636916827084602.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:26:01,566] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.052706271754983484, 'dropout_rate': 0.3787195779305788, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.077209816707269, 'min_weight_fraction_leaf': 0.31040829786124846, 'max_features': 0.1, 'min_impurity_decrease': 1.0106089337747014e-06, 'validation_fraction': 0.8835479481377899, 'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 45 with value: 0.636916827084602.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6298449612403101
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.6596958174904943
Fold 5 C-index: 0.6158798283261803
[I 2024-04-13 19:26:04,554] Trial 51 finished with value: 0.6419284038560863 and parameters: {'subsample': 0.9156545266266123, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.1404019935798118, 'n_estimators': 32, 'criterion': 'squared_error', 'ccp_alpha': 0.012243801070742757, 'min_weight_fraction_leaf': 0.377285576216956, 'max_features': 'sqrt', 'min_impurity_decrease': 2.1936100454733836e-07, 'validation_fraction': 0.855037228249073, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:26:09,253] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.7977865301378425, 'learning_rate': 0.07102079283153598, 'dropout_rate': 0.11294952687164567, 'n_estimators': 48, 'criterion': 'squared_error', 'ccp_alpha': 0.5430622755642927, 'min_weight_fraction_leaf': 0.36469952190521415, 'max_features': 'sqrt', 'min_impurity_decrease': 2.38579101418113e-07, 'validation_fraction': 0.7433547121677936, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6414728682170543
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.655893536121673
Fold 5 C-index: 0.5944206008583691
[I 2024-04-13 19:26:11,037] Trial 53 finished with value: 0.6383590963856938 and parameters: {'subsample': 0.7305170806182099, 'learning_rate': 0.05877903849297955, 'dropout_rate': 0.2158120114915196, 'n_estimators': 28, 'criterion': 'squared_error', 'ccp_alpha': 0.009781579144263263, 'min_weight_fraction_leaf': 0.33111548353893067, 'max_features': 'sqrt', 'min_impurity_decrease': 5.215208696037137e-07, 'validation_fraction': 0.8384582646351804, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:26:13,407] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.7254872738354575, 'learning_rate': 0.059834764453264265, 'dropout_rate': 0.22627998975411026, 'n_estimators': 34, 'criterion': 'squared_error', 'ccp_alpha': 1.6707664312736628, 'min_weight_fraction_leaf': 0.3401457696750657, 'max_features': 'sqrt', 'min_impurity_decrease': 3.9827268139860795e-07, 'validation_fraction': 0.8695162647266814, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:26:19,479] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8980684211151492, 'learning_rate': 0.04709963647359185, 'dropout_rate': 0.18274261049965285, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.40074886285106287, 'min_weight_fraction_leaf': 0.3370690002239194, 'max_features': 'sqrt', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8331902741865593, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:26:53,520] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.9221605118409517, 'learning_rate': 0.04145334122676535, 'dropout_rate': 0.13064667596279733, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 1.0261239696798017, 'min_weight_fraction_leaf': 0.37038285680105903, 'max_features': 'sqrt', 'min_impurity_decrease': 6.554786161716051e-07, 'validation_fraction': 0.9052955846887007, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.5968992248062015
Fold 3 C-index: 0.6914893617021277
Fold 4 C-index: 0.6254752851711026
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 19:27:02,260] Trial 57 finished with value: 0.6248260205783842 and parameters: {'subsample': 0.870116595720937, 'learning_rate': 0.05952554251828951, 'dropout_rate': 0.2654836627375681, 'n_estimators': 84, 'criterion': 'squared_error', 'ccp_alpha': 0.0019473494055538935, 'min_weight_fraction_leaf': 0.4506484646379062, 'max_features': 'sqrt', 'min_impurity_decrease': 5.171295766128041e-06, 'validation_fraction': 0.7918559073771259, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:27:13,532] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.7860091128392402, 'learning_rate': 0.05676463368504374, 'dropout_rate': 0.24877801421911805, 'n_estimators': 92, 'criterion': 'squared_error', 'ccp_alpha': 0.7470877807882045, 'min_weight_fraction_leaf': 0.26934786002389455, 'max_features': 'sqrt', 'min_impurity_decrease': 1.6503518520592255e-05, 'validation_fraction': 0.6918134851314997, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 19}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:27:15,497] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.8553450495189544, 'learning_rate': 0.07051651042781107, 'dropout_rate': 0.16583013538010005, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 8.349136570200802, 'min_weight_fraction_leaf': 0.47402646750752947, 'max_features': 'sqrt', 'min_impurity_decrease': 4.916228088258153e-06, 'validation_fraction': 0.779738812956857, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:27:19,236] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.8311606032672914, 'learning_rate': 0.049337793762293414, 'dropout_rate': 0.10027170450231424, 'n_estimators': 50, 'criterion': 'squared_error', 'ccp_alpha': 1.3119841524585854, 'min_weight_fraction_leaf': 0.3074767130493653, 'max_features': 'sqrt', 'min_impurity_decrease': 2.4188603560320107e-06, 'validation_fraction': 0.8209142444316069, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:27:29,815] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.8807242730119922, 'learning_rate': 0.06060509917723852, 'dropout_rate': 0.21540975433556148, 'n_estimators': 97, 'criterion': 'squared_error', 'ccp_alpha': 0.34104023788856364, 'min_weight_fraction_leaf': 0.4431847862340273, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1489427281229002e-06, 'validation_fraction': 0.889211406935275, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 18}. Best is trial 51 with value: 0.6419284038560863.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.655893536121673
Fold 5 C-index: 0.6115879828326181
[I 2024-04-13 19:27:35,735] Trial 62 finished with value: 0.6283268841578284 and parameters: {'subsample': 0.9543961448103062, 'learning_rate': 0.06789146011220368, 'dropout_rate': 0.3264939129108728, 'n_estimators': 71, 'criterion': 'squared_error', 'ccp_alpha': 0.022616672247981386, 'min_weight_fraction_leaf': 0.41165895476319747, 'max_features': 'sqrt', 'min_impurity_decrease': 5.069407900080354e-07, 'validation_fraction': 0.7859949287628765, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 18}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.674468085106383
Fold 4 C-index: 0.6444866920152091
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 19:27:49,933] Trial 63 finished with value: 0.6235672145293628 and parameters: {'subsample': 0.9469443427613207, 'learning_rate': 0.06801311498216697, 'dropout_rate': 0.32617131802248245, 'n_estimators': 119, 'criterion': 'squared_error', 'ccp_alpha': 0.017289191017379774, 'min_weight_fraction_leaf': 0.38230472306828395, 'max_features': 'sqrt', 'min_impurity_decrease': 5.596696905911145e-07, 'validation_fraction': 0.7322540972531445, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 18}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:27:57,798] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.9999291885743816, 'learning_rate': 0.06351690862369143, 'dropout_rate': 0.2603466948459836, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.4231489714125428, 'max_features': 'sqrt', 'min_impurity_decrease': 1.7375428501365761e-06, 'validation_fraction': 0.7799232691405718, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:28:03,432] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.731372773241202, 'learning_rate': 0.08483859461035387, 'dropout_rate': 0.42946028164369743, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.3522642153414066, 'min_weight_fraction_leaf': 0.4089858346066107, 'max_features': 'sqrt', 'min_impurity_decrease': 2.3880040801001446e-07, 'validation_fraction': 0.6774643261598785, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:28:05,413] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.9270510971818493, 'learning_rate': 0.07831921552372668, 'dropout_rate': 0.3690035704996783, 'n_estimators': 20, 'criterion': 'squared_error', 'ccp_alpha': 0.8895257611291668, 'min_weight_fraction_leaf': 0.38130779234883155, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00014974488025406402, 'validation_fraction': 0.8426595838965568, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:28:27,211] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8509816424016059, 'learning_rate': 0.09201698812616743, 'dropout_rate': 0.2891948392773582, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 0.29393333981111347, 'min_weight_fraction_leaf': 0.32926871585157824, 'max_features': None, 'min_impurity_decrease': 1.805737910528395e-07, 'validation_fraction': 0.7952722655013678, 'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:28:41,304] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.6619865463398119, 'learning_rate': 0.07383151588968451, 'dropout_rate': 0.1853296855049907, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.8385719579981664, 'min_weight_fraction_leaf': 0.47751000784675207, 'max_features': 1, 'min_impurity_decrease': 1.2986365360837672e-06, 'validation_fraction': 0.7538502794470011, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 18}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:28:59,593] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7692672682208916, 'learning_rate': 0.05773952075160269, 'dropout_rate': 0.2343529795568311, 'n_estimators': 135, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7491404886634039, 'min_weight_fraction_leaf': 0.20015949879955452, 'max_features': 'sqrt', 'min_impurity_decrease': 5.368270720109542e-07, 'validation_fraction': 0.9581706893807749, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 15}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.6444866920152091
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 19:29:11,028] Trial 70 finished with value: 0.6431464077499045 and parameters: {'subsample': 0.9672353591832252, 'learning_rate': 0.050642884595621745, 'dropout_rate': 0.13785096073945516, 'n_estimators': 88, 'criterion': 'squared_error', 'ccp_alpha': 0.010067956580931684, 'min_weight_fraction_leaf': 0.3551802773828724, 'max_features': 0.1, 'min_impurity_decrease': 7.713426989240967e-06, 'validation_fraction': 0.6901517483986648, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 19}. Best is trial 70 with value: 0.6431464077499045.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6007751937984496
Fold 3 C-index: 0.6829787234042554
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 19:29:19,087] Trial 71 finished with value: 0.647978353455525 and parameters: {'subsample': 0.9736544653699906, 'learning_rate': 0.05317196534413593, 'dropout_rate': 0.14303111133639826, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.35066087197674667, 'max_features': 0.1, 'min_impurity_decrease': 7.356647091617949e-06, 'validation_fraction': 0.6117331205297228, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:29:27,299] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.9701687645962381, 'learning_rate': 0.055147872123398556, 'dropout_rate': 0.14962137828220934, 'n_estimators': 80, 'criterion': 'squared_error', 'ccp_alpha': 0.30517658758579036, 'min_weight_fraction_leaf': 0.35173646760424715, 'max_features': 0.1, 'min_impurity_decrease': 7.987219995224915e-06, 'validation_fraction': 0.6095946706874, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:29:32,862] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.9050782920628282, 'learning_rate': 0.05199322380390804, 'dropout_rate': 0.17409435305677468, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 1.253410092850479, 'min_weight_fraction_leaf': 0.39707509838374494, 'max_features': 0.1, 'min_impurity_decrease': 1.5194516956030065e-05, 'validation_fraction': 0.6804519242126394, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:29:36,183] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.8170901637275931, 'learning_rate': 0.04465970891926194, 'dropout_rate': 0.2733411451160021, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 2.2209618984123054, 'min_weight_fraction_leaf': 0.28881136217710557, 'max_features': 0.1, 'min_impurity_decrease': 4.209901591206505e-06, 'validation_fraction': 0.565571701048534, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:29:44,652] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.9660009158555741, 'learning_rate': 0.06623664860709609, 'dropout_rate': 0.20553427844193914, 'n_estimators': 86, 'criterion': 'squared_error', 'ccp_alpha': 0.6610020768545956, 'min_weight_fraction_leaf': 0.4147865725732959, 'max_features': 0.1, 'min_impurity_decrease': 5.9734079360074814e-05, 'validation_fraction': 0.7190500576027261, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:29:45,275] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9260563831456721, 'learning_rate': 0.06047528137822334, 'dropout_rate': 0.13950292138275533, 'n_estimators': 3, 'criterion': 'squared_error', 'ccp_alpha': 0.30518351178979397, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 3.0635242894652526e-06, 'validation_fraction': 0.6370726022286737, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:29:46,776] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.6292281998520165, 'learning_rate': 0.05024404952833331, 'dropout_rate': 0.3126086948156713, 'n_estimators': 24, 'criterion': 'squared_error', 'ccp_alpha': 0.9547062307580542, 'min_weight_fraction_leaf': 0.3510321193946014, 'max_features': 0.1, 'min_impurity_decrease': 1.081678973071488e-05, 'validation_fraction': 0.7602747720774515, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6634980988593155
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 19:29:51,470] Trial 78 finished with value: 0.6353126486594283 and parameters: {'subsample': 0.8691738049495636, 'learning_rate': 0.06172743517601075, 'dropout_rate': 0.23315454705919414, 'n_estimators': 53, 'criterion': 'squared_error', 'ccp_alpha': 0.022575408770505685, 'min_weight_fraction_leaf': 0.3057970079002221, 'max_features': 0.1, 'min_impurity_decrease': 1.7520953196534605e-06, 'validation_fraction': 0.5037268926902503, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:29:54,829] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.88956690114416, 'learning_rate': 0.04130686635403637, 'dropout_rate': 0.8831816560103296, 'n_estimators': 57, 'criterion': 'squared_error', 'ccp_alpha': 0.5632856474666742, 'min_weight_fraction_leaf': 0.2996503291930464, 'max_features': 0.1, 'min_impurity_decrease': 2.4463737680399873e-06, 'validation_fraction': 0.4716515115237929, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:30:34,008] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.25430148678930137, 'learning_rate': 0.05535894045369185, 'dropout_rate': 0.684566586558272, 'n_estimators': 281, 'criterion': 'friedman_mse', 'ccp_alpha': 5.788139805041061, 'min_weight_fraction_leaf': 0.2499517824138018, 'max_features': 0.1, 'min_impurity_decrease': 1.796522128313966e-06, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 18}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 19:30:36,853] Trial 81 finished with value: 0.6307781380800804 and parameters: {'subsample': 0.8577485699653032, 'learning_rate': 0.061637170413557506, 'dropout_rate': 0.22634568349167175, 'n_estimators': 40, 'criterion': 'squared_error', 'ccp_alpha': 0.025375439967122704, 'min_weight_fraction_leaf': 0.3176895770453635, 'max_features': 0.1, 'min_impurity_decrease': 7.578956130507077e-06, 'validation_fraction': 0.3975706744446108, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:30:40,184] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.9813148642262436, 'learning_rate': 0.062245123119526666, 'dropout_rate': 0.22245189647227442, 'n_estimators': 42, 'criterion': 'squared_error', 'ccp_alpha': 0.24494931030471306, 'min_weight_fraction_leaf': 0.28129167307655356, 'max_features': 0.1, 'min_impurity_decrease': 2.116701877304566e-05, 'validation_fraction': 0.40489648109304005, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:30:41,490] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9499142623758436, 'learning_rate': 0.06606682685789786, 'dropout_rate': 0.1294422134091702, 'n_estimators': 17, 'criterion': 'squared_error', 'ccp_alpha': 0.20222023273899953, 'min_weight_fraction_leaf': 0.3184434511931986, 'max_features': 0.1, 'min_impurity_decrease': 8.590576083527748e-06, 'validation_fraction': 0.29115286333596435, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:30:43,737] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.9162531840390775, 'learning_rate': 0.06921777347051267, 'dropout_rate': 0.16964850157537764, 'n_estimators': 33, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.3317427757671296, 'max_features': 'log2', 'min_impurity_decrease': 3.8673317929388064e-05, 'validation_fraction': 0.40427407950001876, 'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:30:56,995] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.8559905830599279, 'learning_rate': 0.073450036806534, 'dropout_rate': 0.24007045832787577, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 0.7090566148541139, 'min_weight_fraction_leaf': 0.29987641169357954, 'max_features': 0.1, 'min_impurity_decrease': 8.743573121519345e-07, 'validation_fraction': 0.37827224876251, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 71 with value: 0.647978353455525.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:31:03,482] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.8229463564083213, 'learning_rate': 0.05354154925209642, 'dropout_rate': 0.18105225920404389, 'n_estimators': 69, 'criterion': 'squared_error', 'ccp_alpha': 1.4515009042573248, 'min_weight_fraction_leaf': 0.22575436425055093, 'max_features': 0.1, 'min_impurity_decrease': 4.6532667290211476e-07, 'validation_fraction': 0.4763814174163325, 'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:32:12,354] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.7337132044406884, 'learning_rate': 0.0483078966674454, 'dropout_rate': 0.2072955347245793, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.4342246419942306, 'min_weight_fraction_leaf': 0.341665255032293, 'max_features': 0.1, 'min_impurity_decrease': 3.4533033574953447e-06, 'validation_fraction': 0.5553002617274752, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:32:41,931] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.4281147617989565, 'learning_rate': 0.057668292702843474, 'dropout_rate': 0.29991250599365193, 'n_estimators': 173, 'criterion': 'squared_error', 'ccp_alpha': 1.1038407677376183, 'min_weight_fraction_leaf': 0.2720384326960418, 'max_features': 0.1, 'min_impurity_decrease': 0.08546129120562182, 'validation_fraction': 0.43622932617902443, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6158798283261803
[I 2024-04-13 19:32:43,025] Trial 89 finished with value: 0.6178740227922591 and parameters: {'subsample': 0.8869756572783157, 'learning_rate': 0.04455455099426123, 'dropout_rate': 0.1354867390651922, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.018791586505192352, 'min_weight_fraction_leaf': 0.25406844321469574, 'max_features': None, 'min_impurity_decrease': 3.2164803778484834e-07, 'validation_fraction': 0.5865831845086661, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:33:31,932] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.781156318466977, 'learning_rate': 0.006695820304041528, 'dropout_rate': 0.3320445224709127, 'n_estimators': 239, 'criterion': 'squared_error', 'ccp_alpha': 0.837158352801002, 'min_weight_fraction_leaf': 0.37074107443236604, 'max_features': 1, 'min_impurity_decrease': 1.2352569883229447e-06, 'validation_fraction': 0.29585084927667094, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6007751937984496
Fold 3 C-index: 0.6702127659574468
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 19:33:40,710] Trial 91 finished with value: 0.6331036326328527 and parameters: {'subsample': 0.9353573941382942, 'learning_rate': 0.06264501502966024, 'dropout_rate': 0.27046977102493674, 'n_estimators': 87, 'criterion': 'squared_error', 'ccp_alpha': 0.03786111729139331, 'min_weight_fraction_leaf': 0.35574723998417634, 'max_features': 'sqrt', 'min_impurity_decrease': 5.380131049753413e-06, 'validation_fraction': 0.7054955710261992, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:33:44,821] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.9692777812882016, 'learning_rate': 0.061855558095227366, 'dropout_rate': 0.35143637013904355, 'n_estimators': 54, 'criterion': 'squared_error', 'ccp_alpha': 0.20072657092263457, 'min_weight_fraction_leaf': 0.36014647758482426, 'max_features': 'sqrt', 'min_impurity_decrease': 1.3975982326313562e-05, 'validation_fraction': 0.6999911594682504, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:33:59,783] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.9369616346923534, 'learning_rate': 0.06630023579051483, 'dropout_rate': 0.2355177689627272, 'n_estimators': 111, 'criterion': 'squared_error', 'ccp_alpha': 0.5295497507503906, 'min_weight_fraction_leaf': 0.32195077645631737, 'max_features': 0.1, 'min_impurity_decrease': 5.784089080997864e-06, 'validation_fraction': 0.6211860587757073, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:34:03,181] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.49488295095968804, 'learning_rate': 0.07808338686371585, 'dropout_rate': 0.19914486856709368, 'n_estimators': 41, 'criterion': 'squared_error', 'ccp_alpha': 0.17721823221162922, 'min_weight_fraction_leaf': 0.3452780203306576, 'max_features': 'log2', 'min_impurity_decrease': 2.406520527524238e-06, 'validation_fraction': 0.6609732454629287, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:34:09,811] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.9088674838000037, 'learning_rate': 0.051473564556910295, 'dropout_rate': 0.15864268967517714, 'n_estimators': 73, 'criterion': 'squared_error', 'ccp_alpha': 0.5662134543657839, 'min_weight_fraction_leaf': 0.3087279762860713, 'max_features': 'sqrt', 'min_impurity_decrease': 7.802177640457686e-06, 'validation_fraction': 0.734306853058186, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 18}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:34:19,794] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.993220298193821, 'learning_rate': 0.06386578790331472, 'dropout_rate': 0.2728557965516078, 'n_estimators': 94, 'criterion': 'squared_error', 'ccp_alpha': 0.23611518017692762, 'min_weight_fraction_leaf': 0.398118898214648, 'max_features': 0.1, 'min_impurity_decrease': 6.932932254500803e-07, 'validation_fraction': 0.32386831053055254, 'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:34:22,428] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8439950412703551, 'learning_rate': 0.07169891244281298, 'dropout_rate': 0.25309805821661835, 'n_estimators': 32, 'criterion': 'friedman_mse', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.33178189795581936, 'max_features': 'sqrt', 'min_impurity_decrease': 3.941232420298443e-06, 'validation_fraction': 0.6710136077506228, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:34:27,614] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8752955195522896, 'learning_rate': 0.05568154932630848, 'dropout_rate': 0.21717204178559688, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.37049554846771593, 'max_features': 0.1, 'min_impurity_decrease': 2.02393880274831e-06, 'validation_fraction': 0.5229378594864895, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6659574468085107
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 19:34:28,487] Trial 99 finished with value: 0.6104297972213892 and parameters: {'subsample': 0.9501601982199268, 'learning_rate': 0.0684597170667179, 'dropout_rate': 0.11764001599415652, 'n_estimators': 5, 'criterion': 'squared_error', 'ccp_alpha': 0.004454392542064083, 'min_weight_fraction_leaf': 0.2967257830934646, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0344011415681455e-06, 'validation_fraction': 0.1604355124738367, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 14}. Best is trial 71 with value: 0.647978353455525.


* Best trial for C-index:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.647978353455525], datetime_start=datetime.datetime(2024, 4, 13, 19, 29, 11, 40505), datetime_complete=datetime.datetime(2024, 4, 13, 19, 29, 19, 86146), params={'subsample': 0.9736544653699906, 'learning_rate': 0.05317196534413593, 'dropout_rate': 0.14303111133639826, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.35066087197674667, 'max_features': 0.1, 'min_impurity_decrease': 7.356647091617949e-06, 'validation_fraction': 0.6117331205297228, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 19}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=71, value=None)


* Best Score for C-index:
 0.647978353455525

[I 2024-04-13 19:34:28,544] A new study created in memory with name: no-name-6820d292-a979-494a-9345-e1fe766fba51

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:35:35,755] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:36:15,141] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:36:51,276] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 19:37:49,700] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:38:17,623] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:38:25,347] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:39:21,927] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:39:39,298] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:39:42,165] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24685581184618258
Fold 2 IBS: 0.23174237938551043
Fold 3 IBS: 0.22869576829949326
Fold 4 IBS: 0.24182307569018754
Fold 5 IBS: 0.22901409570517067
[I 2024-04-13 19:42:03,771] Trial 9 finished with value: 0.2356262261853089 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24711653291675975
Fold 2 IBS: 0.23202162954629
Fold 3 IBS: 0.2289556964425975
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293716647928885
[I 2024-04-13 20:13:00,431] Trial 10 finished with value: 0.23588805903156138 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:16:23,814] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24719577573761148
Fold 2 IBS: 0.23199892761841134
Fold 3 IBS: 0.2289405059322678
Fold 4 IBS: 0.2419573801021639
Fold 5 IBS: 0.22934247219234205
[I 2024-04-13 20:19:02,686] Trial 12 finished with value: 0.23588701231655934 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:20:28,818] Trial 13 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:22:27,679] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:24:08,716] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:25:20,308] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:27:56,277] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:31:27,017] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:31:35,457] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:32:53,846] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:35:43,661] Trial 21 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24675710728069802
Fold 2 IBS: 0.23120128338106113

Fold 3 IBS: 0.22848569735194738
Fold 4 IBS: 0.24150141767716396
Fold 5 IBS: 0.22845766625525668
[I 2024-04-13 20:38:53,034] Trial 22 finished with value: 0.23528063438922545 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:41:01,678] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-13 20:42:44,029] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:43:46,470] Trial 25 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:45:58,568] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:48:07,859] Trial 27 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:49:50,521] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:51:13,146] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:52:45,220] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24723811107199292
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:55:33,301] Trial 31 finished with value: 0.23592604563741132 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:58:22,554] Trial 32 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:00:01,079] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:02:17,568] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:02:46,503] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:05:09,989] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:05:13,717] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:06:02,645] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:07:22,328] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:09:28,000] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.2472010209971281
Fold 2 IBS: 0.23197319933729893
Fold 3 IBS: 0.22887452934644678
Fold 4 IBS: 0.24191861956639799
Fold 5 IBS: 0.2293015642651888
[I 2024-04-13 21:09:28,491] Trial 41 finished with value: 0.23585378670249213 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.2459047520616606
Fold 2 IBS: 0.23020388607917422
Fold 3 IBS: 0.22657568837307415
Fold 4 IBS: 0.24022980115273948
Fold 5 IBS: 0.22694242307333995
[I 2024-04-13 21:09:44,026] Trial 42 finished with value: 0.2339713101479977 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:09:44,847] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8735505723796891, 'learning_rate': 0.013455915558851193, 'dropout_rate': 0.11585930219083569, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 1.1546454041172216, 'min_weight_fraction_leaf': 0.4571018098895751, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8650432234384267, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:10:18,544] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9479336661285427, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.25335630680617827, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.4126953497238681, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.9438667820963776, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24456420494605938
Fold 2 IBS: 0.2296322307721539
Fold 3 IBS: 0.22573775856516912
Fold 4 IBS: 0.23975108534236433
Fold 5 IBS: 0.22653026890442532
[I 2024-04-13 21:10:30,321] Trial 45 finished with value: 0.2332431097060344 and parameters: {'subsample': 0.5852424762732177, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.027804703729289008, 'min_weight_fraction_leaf': 0.262143273989599, 'max_features': 0.1, 'min_impurity_decrease': 9.467252666446998e-07, 'validation_fraction': 0.7243304021069044, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:10:33,171] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.0647255784094387, 'dropout_rate': 0.9694253886674298, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 1.980441868470768, 'min_weight_fraction_leaf': 0.3747732962598691, 'max_features': 0.1, 'min_impurity_decrease': 2.6164901943280044e-07, 'validation_fraction': 0.7149599360255287, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:10:55,326] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.45583884600027197, 'learning_rate': 0.06333641179361332, 'dropout_rate': 0.19790330487666663, 'n_estimators': 172, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.3462595663974316, 'max_features': 0.1, 'min_impurity_decrease': 9.138461248752069e-07, 'validation_fraction': 0.6499098781754827, 'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:11:00,457] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.584713932884162, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.10579627176846597, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 0.443834316760607, 'min_weight_fraction_leaf': 0.26066789839492466, 'max_features': 0.1, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.5884862057231304, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:11:01,117] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5232490206634685, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 9, 'criterion': 'friedman_mse', 'ccp_alpha': 1.370081088125734, 'min_weight_fraction_leaf': 0.3097478284829108, 'max_features': 0.1, 'min_impurity_decrease': 2.368978679128857e-06, 'validation_fraction': 0.8421492954769574, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:11:02,952] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.07076395585024155, 'dropout_rate': 0.14893065487391582, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 1.7468603849227415, 'min_weight_fraction_leaf': 0.4771102452497172, 'max_features': 'log2', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.6959936026682685, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24691186517673142
Fold 2 IBS: 0.23166083157852174
Fold 3 IBS: 0.22854484375938985
Fold 4 IBS: 0.24160811245105418
Fold 5 IBS: 0.2289571734476567
[I 2024-04-13 21:11:14,695] Trial 51 finished with value: 0.23553656528267078 and parameters: {'subsample': 0.7946888792311653, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.2196446942108301, 'n_estimators': 129, 'criterion': 'squared_error', 'ccp_alpha': 0.012243801070742757, 'min_weight_fraction_leaf': 0.22002902120871776, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0321764873923598e-06, 'validation_fraction': 0.8872414026388215, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24623497694375837
Fold 2 IBS: 0.23110463228852685
Fold 3 IBS: 0.22789301004466875
Fold 4 IBS: 0.24144064404347787
Fold 5 IBS: 0.22815882228252543
[I 2024-04-13 21:11:23,490] Trial 52 finished with value: 0.23496641712059146 and parameters: {'subsample': 0.7293363088819711, 'learning_rate': 0.021613492744160495, 'dropout_rate': 0.21988140341808987, 'n_estimators': 109, 'criterion': 'squared_error', 'ccp_alpha': 0.03659945835027755, 'min_weight_fraction_leaf': 0.21454208459463384, 'max_features': 'sqrt', 'min_impurity_decrease': 4.968003047339178e-07, 'validation_fraction': 0.7452334109475507, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:11:33,969] Trial 53 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7286313887376499, 'learning_rate': 0.057410108721501936, 'dropout_rate': 0.285096973056326, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.4512041233232864, 'min_weight_fraction_leaf': 0.2260580293041923, 'max_features': 'sqrt', 'min_impurity_decrease': 9.58735442301899e-07, 'validation_fraction': 0.810021403108459, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:11:42,862] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6569229035185145, 'learning_rate': 0.04372807230380943, 'dropout_rate': 0.21137526606647042, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 1.035069386526868, 'min_weight_fraction_leaf': 0.15200254659099177, 'max_features': 'sqrt', 'min_impurity_decrease': 3.9827268139860795e-07, 'validation_fraction': 0.7420090012406269, 'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:12:01,360] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.804828042321909, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.23926982708415356, 'n_estimators': 162, 'criterion': 'squared_error', 'ccp_alpha': 0.40074886285106287, 'min_weight_fraction_leaf': 0.2779066644542128, 'max_features': 'sqrt', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:12:24,168] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6106355356441384, 'learning_rate': 0.0175381503002972, 'dropout_rate': 0.1840399348615831, 'n_estimators': 188, 'criterion': 'squared_error', 'ccp_alpha': 1.2616701535027603, 'min_weight_fraction_leaf': 0.21267322167989086, 'max_features': 'sqrt', 'min_impurity_decrease': 4.6036201699627165e-06, 'validation_fraction': 0.6710340937437342, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:12:27,652] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7251306188899954, 'learning_rate': 0.031631325965124225, 'dropout_rate': 0.36858678707018233, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.8632300312068857, 'min_weight_fraction_leaf': 0.25226351016663784, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8530056448822852e-06, 'validation_fraction': 0.6117070368402964, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 20}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.2443681907556647
Fold 2 IBS: 0.22957645244381633
Fold 3 IBS: 0.22623065748764107
Fold 4 IBS: 0.24012884639533771
Fold 5 IBS: 0.2254898421162855
[I 2024-04-13 21:12:41,095] Trial 58 finished with value: 0.23315879783974905 and parameters: {'subsample': 0.8372135933826973, 'learning_rate': 0.0933118263896949, 'dropout_rate': 0.2698372192490325, 'n_estimators': 138, 'criterion': 'squared_error', 'ccp_alpha': 0.03851666886580376, 'min_weight_fraction_leaf': 0.19014956845126402, 'max_features': 'sqrt', 'min_impurity_decrease': 5.557667048245938e-07, 'validation_fraction': 0.8240957175887902, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 58 with value: 0.23315879783974905.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:12:57,071] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7770131468684633, 'learning_rate': 0.09661144110789328, 'dropout_rate': 0.13071901615025144, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.8838088337816697, 'min_weight_fraction_leaf': 0.20200402270044698, 'max_features': 'sqrt', 'min_impurity_decrease': 2.1058318453300297e-05, 'validation_fraction': 0.7834472079756201, 'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 10}. Best is trial 58 with value: 0.23315879783974905.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:13:22,225] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8387622269560421, 'learning_rate': 0.09288013525153278, 'dropout_rate': 0.4315539960531031, 'n_estimators': 222, 'criterion': 'squared_error', 'ccp_alpha': 7.88888123252141, 'min_weight_fraction_leaf': 0.18715715168296215, 'max_features': 'sqrt', 'min_impurity_decrease': 5.658911777133895e-07, 'validation_fraction': 0.8258586719391796, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 58 with value: 0.23315879783974905.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:13:28,662] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8935334956662829, 'learning_rate': 0.08303647143365385, 'dropout_rate': 0.31926072944032013, 'n_estimators': 90, 'criterion': 'squared_error', 'ccp_alpha': 0.3409580267399826, 'min_weight_fraction_leaf': 0.13431472354808824, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1489427281229002e-06, 'validation_fraction': 0.7271755608042784, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 58 with value: 0.23315879783974905.
Fold 1 IBS: 0.24428122846636707
Fold 2 IBS: 0.22873125379430995
Fold 3 IBS: 0.22501463857482426
Fold 4 IBS: 0.23913988463506086
Fold 5 IBS: 0.22514732721679961
[I 2024-04-13 21:13:41,232] Trial 62 finished with value: 0.23246286653747233 and parameters: {'subsample': 0.8243414389621114, 'learning_rate': 0.09071124103540035, 'dropout_rate': 0.27251764057548483, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.022616672247981386, 'min_weight_fraction_leaf': 0.2309588671101351, 'max_features': 'sqrt', 'min_impurity_decrease': 2.89800118435477e-07, 'validation_fraction': 0.876556500915509, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 62 with value: 0.23246286653747233.
Fold 1 IBS: 0.24427652287227705
Fold 2 IBS: 0.22837518871279563
Fold 3 IBS: 0.22481597447693613
Fold 4 IBS: 0.2386106110830185
Fold 5 IBS: 0.22511230961028517
[I 2024-04-13 21:13:52,731] Trial 63 finished with value: 0.23223812135106253 and parameters: {'subsample': 0.8336599603007587, 'learning_rate': 0.09031916747519456, 'dropout_rate': 0.2663787938573428, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 0.017289191017379774, 'min_weight_fraction_leaf': 0.1951981514595036, 'max_features': 'sqrt', 'min_impurity_decrease': 5.414928507269899e-07, 'validation_fraction': 0.8926228431876313, 'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:14:11,862] Trial 64 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8427195777663575, 'learning_rate': 0.08784542374582861, 'dropout_rate': 0.2603466948459836, 'n_estimators': 183, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.18631742994510192, 'max_features': 'sqrt', 'min_impurity_decrease': 2.8821254066618343e-07, 'validation_fraction': 0.8718245332193061, 'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:14:19,089] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9311291803826592, 'learning_rate': 0.09901078905928126, 'dropout_rate': 0.33807906387606884, 'n_estimators': 111, 'criterion': 'squared_error', 'ccp_alpha': 0.2833036261479952, 'min_weight_fraction_leaf': 0.15643365485923125, 'max_features': 'sqrt', 'min_impurity_decrease': 4.917940757661372e-07, 'validation_fraction': 0.7588166620798954, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:14:32,850] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9043457557527063, 'learning_rate': 0.08720647345857328, 'dropout_rate': 0.27193939046019544, 'n_estimators': 154, 'criterion': 'squared_error', 'ccp_alpha': 1.4111498627316026, 'min_weight_fraction_leaf': 0.23517339076530247, 'max_features': 'sqrt', 'min_impurity_decrease': 6.086951842225704e-07, 'validation_fraction': 0.9127218528145804, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:14:34,922] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8250695857763196, 'learning_rate': 0.0911086342832341, 'dropout_rate': 0.3723000690397865, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 2.319190851430798, 'min_weight_fraction_leaf': 0.10443241497369499, 'max_features': None, 'min_impurity_decrease': 2.261430377187218e-06, 'validation_fraction': 0.8216731421530759, 'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:15:18,953] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8643375099509361, 'learning_rate': 0.0792574273284101, 'dropout_rate': 0.17115105391870955, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.2964654702152873, 'min_weight_fraction_leaf': 0.2042624403156238, 'max_features': 1, 'min_impurity_decrease': 1.613957524750281e-07, 'validation_fraction': 0.8530531167865556, 'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 5}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:15:23,135] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7567410978430598, 'learning_rate': 0.049761024237604506, 'dropout_rate': 0.23019100638335152, 'n_estimators': 72, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7461388176327838, 'min_weight_fraction_leaf': 0.2677621074656332, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012116389221552239, 'validation_fraction': 0.7845892214091239, 'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24444133138826799
Fold 2 IBS: 0.22896095650109377
Fold 3 IBS: 0.22503353478571886
Fold 4 IBS: 0.23870623781069059
Fold 5 IBS: 0.22611346338092578
[I 2024-04-13 21:15:34,919] Trial 70 finished with value: 0.23265110477333942 and parameters: {'subsample': 0.7270958059780266, 'learning_rate': 0.09025955125786853, 'dropout_rate': 0.2983051130696582, 'n_estimators': 141, 'criterion': 'squared_error', 'ccp_alpha': 0.010268271623930566, 'min_weight_fraction_leaf': 0.17606622950083872, 'max_features': 0.1, 'min_impurity_decrease': 2.9199125301850487e-07, 'validation_fraction': 0.9704707284830002, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24458360687718095
Fold 2 IBS: 0.2299707901134013
Fold 3 IBS: 0.2261844041470423
Fold 4 IBS: 0.23998297132336502
Fold 5 IBS: 0.22661245458746127
[I 2024-04-13 21:15:46,593] Trial 71 finished with value: 0.23346684540969015 and parameters: {'subsample': 0.7304805982333465, 'learning_rate': 0.0892848077436604, 'dropout_rate': 0.30534098323418335, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.17968197273495315, 'max_features': 0.1, 'min_impurity_decrease': 3.204485364940275e-07, 'validation_fraction': 0.9097007997790482, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24433296043098846
Fold 2 IBS: 0.22891833926886082
Fold 3 IBS: 0.2251270028353668
Fold 4 IBS: 0.23873976524316162
Fold 5 IBS: 0.22617521331304977
[I 2024-04-13 21:15:59,882] Trial 72 finished with value: 0.23265865621828546 and parameters: {'subsample': 0.7283770413521057, 'learning_rate': 0.08910556443694609, 'dropout_rate': 0.30374750627529123, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 0.004871280381427739, 'min_weight_fraction_leaf': 0.18085760075572085, 'max_features': 0.1, 'min_impurity_decrease': 2.066775254108449e-07, 'validation_fraction': 0.968044786321844, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:16:11,025] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6821762273698422, 'learning_rate': 0.09045775488747818, 'dropout_rate': 0.3019452359314178, 'n_estimators': 136, 'criterion': 'squared_error', 'ccp_alpha': 0.6105532472732402, 'min_weight_fraction_leaf': 0.17703318401139306, 'max_features': 0.1, 'min_impurity_decrease': 2.0200798514974308e-07, 'validation_fraction': 0.9701149300219802, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:16:24,406] Trial 74 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7101241528292079, 'learning_rate': 0.09937320265602623, 'dropout_rate': 0.3524831319725679, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 0.9837183244747926, 'min_weight_fraction_leaf': 0.1523796655343799, 'max_features': 0.1, 'min_impurity_decrease': 1.0461061192135599e-07, 'validation_fraction': 0.9135026133191511, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 8}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:16:41,617] Trial 75 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7910155215343213, 'learning_rate': 0.08588418227292206, 'dropout_rate': 0.39919431914091363, 'n_estimators': 174, 'criterion': 'squared_error', 'ccp_alpha': 0.4044325808748982, 'min_weight_fraction_leaf': 0.12844710013372065, 'max_features': 0.1, 'min_impurity_decrease': 2.4870550227046503e-07, 'validation_fraction': 0.963542393044741, 'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:17:06,637] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6388870613170881, 'learning_rate': 0.09471280191500378, 'dropout_rate': 0.26923993869351254, 'n_estimators': 199, 'criterion': 'squared_error', 'ccp_alpha': 0.30266244779681034, 'min_weight_fraction_leaf': 0.10381952675877999, 'max_features': 0.1, 'min_impurity_decrease': 1.4510472528097585e-06, 'validation_fraction': 0.8960664882855555, 'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 6}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:17:11,735] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7428517276581355, 'learning_rate': 0.07706989744762442, 'dropout_rate': 0.4476209058480567, 'n_estimators': 91, 'criterion': 'squared_error', 'ccp_alpha': 1.5888723787914292, 'min_weight_fraction_leaf': 0.16206442611838873, 'max_features': 0.1, 'min_impurity_decrease': 3.33671674086432e-07, 'validation_fraction': 0.9402673106586569, 'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 9}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:17:24,642] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7715268987373948, 'learning_rate': 0.08985503754923349, 'dropout_rate': 0.5106424386694343, 'n_estimators': 163, 'criterion': 'squared_error', 'ccp_alpha': 0.6998187558649429, 'min_weight_fraction_leaf': 0.1441624791990044, 'max_features': 0.1, 'min_impurity_decrease': 6.786191098123249e-07, 'validation_fraction': 0.867999843487921, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24716969285660575
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22894393483975858
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:17:28,670] Trial 79 finished with value: 0.23590477534833018 and parameters: {'subsample': 0.8256021281450457, 'learning_rate': 0.08314261144569621, 'dropout_rate': 0.8831816560103296, 'n_estimators': 120, 'criterion': 'squared_error', 'ccp_alpha': 0.00580501385319391, 'min_weight_fraction_leaf': 0.19542362826311155, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9982863294620272, 'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 7}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809254
[I 2024-04-13 21:17:36,770] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6683452738089981, 'learning_rate': 0.07289104058957506, 'dropout_rate': 0.684566586558272, 'n_estimators': 139, 'criterion': 'squared_error', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.17162624287712744, 'max_features': 0.1, 'min_impurity_decrease': 1.7025620478865608e-07, 'validation_fraction': 0.8367688563996566, 'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 9}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:17:45,553] Trial 81 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7212629717230318, 'learning_rate': 0.09648863423607545, 'dropout_rate': 0.32380628722047555, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.23038409491076217, 'min_weight_fraction_leaf': 0.2340042122326562, 'max_features': 0.1, 'min_impurity_decrease': 4.883007455581965e-07, 'validation_fraction': 0.9187926479398427, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24390862233245375
Fold 2 IBS: 0.22838292702570365
Fold 3 IBS: 0.22427728469643368
Fold 4 IBS: 0.23883806806788913
Fold 5 IBS: 0.22487611642069374
[I 2024-04-13 21:17:54,810] Trial 82 finished with value: 0.23205660370863482 and parameters: {'subsample': 0.7424094275541511, 'learning_rate': 0.09321912358204075, 'dropout_rate': 0.2934062535264489, 'n_estimators': 114, 'criterion': 'squared_error', 'ccp_alpha': 0.01778369806197142, 'min_weight_fraction_leaf': 0.21126686784700288, 'max_features': 'log2', 'min_impurity_decrease': 3.4224047595443053e-07, 'validation_fraction': 0.9694941758991367, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:18:00,258] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6936370685985978, 'learning_rate': 0.07973196831123328, 'dropout_rate': 0.28615445184158467, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 1.129152915921092, 'min_weight_fraction_leaf': 0.18903520337674806, 'max_features': 'log2', 'min_impurity_decrease': 2.9795925135078545e-07, 'validation_fraction': 0.9720656242622133, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:18:03,099] Trial 84 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7766180104167335, 'learning_rate': 0.09249006200550622, 'dropout_rate': 0.305574256636177, 'n_estimators': 53, 'criterion': 'squared_error', 'ccp_alpha': 0.6566133054967586, 'min_weight_fraction_leaf': 0.24759719188654067, 'max_features': 'log2', 'min_impurity_decrease': 1.3396039034492153e-07, 'validation_fraction': 0.892099453138701, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.2289818680697771
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:18:19,765] Trial 85 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8541716599279708, 'learning_rate': 0.08839641653849994, 'dropout_rate': 0.24521378095924606, 'n_estimators': 156, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3309010043491877, 'min_weight_fraction_leaf': 0.17837522472890427, 'max_features': 'log2', 'min_impurity_decrease': 8.040870911608097e-07, 'validation_fraction': 0.9314770718841436, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:18:26,035] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8087595997030689, 'learning_rate': 0.08488131639682682, 'dropout_rate': 0.3757108201252311, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 0.8619058019946999, 'min_weight_fraction_leaf': 0.034374369575269015, 'max_features': 'log2', 'min_impurity_decrease': 1.9734264215079192e-07, 'validation_fraction': 0.8644333526627775, 'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:18:34,785] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7460732631507769, 'learning_rate': 0.09440704087578497, 'dropout_rate': 0.34429888870538994, 'n_estimators': 117, 'criterion': 'squared_error', 'ccp_alpha': 0.23605873926111243, 'min_weight_fraction_leaf': 0.20611127721053588, 'max_features': 0.1, 'min_impurity_decrease': 3.605164135559099e-07, 'validation_fraction': 0.9533190908371042, 'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:18:56,516] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6413430388178152, 'learning_rate': 0.0973528090376961, 'dropout_rate': 0.26912242502602596, 'n_estimators': 174, 'criterion': 'squared_error', 'ccp_alpha': 0.5807061908097002, 'min_weight_fraction_leaf': 0.16723537370276506, 'max_features': 0.1, 'min_impurity_decrease': 1.190634063232502e-06, 'validation_fraction': 0.8005899065401637, 'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24220714862378384
Fold 2 IBS: 0.22705284477038132
Fold 3 IBS: 0.22374120154251026
Fold 4 IBS: 0.23761138561741843
Fold 5 IBS: 0.22312495335199894
[I 2024-04-13 21:19:13,522] Trial 89 finished with value: 0.23074750678121858 and parameters: {'subsample': 0.38730242337646104, 'learning_rate': 0.08109800836387941, 'dropout_rate': 0.18122999434960108, 'n_estimators': 146, 'criterion': 'squared_error', 'ccp_alpha': 0.018794864735403906, 'min_weight_fraction_leaf': 0.14130782512257434, 'max_features': None, 'min_impurity_decrease': 6.04312953486063e-07, 'validation_fraction': 0.9728621916133924, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 89 with value: 0.23074750678121858.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:19:46,146] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4301287904403204, 'learning_rate': 0.08064135841350613, 'dropout_rate': 0.18182381147209734, 'n_estimators': 216, 'criterion': 'squared_error', 'ccp_alpha': 5.797253839038365, 'min_weight_fraction_leaf': 0.11344111466651854, 'max_features': 1, 'min_impurity_decrease': 2.7530646126399795e-06, 'validation_fraction': 0.9992764821735842, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 89 with value: 0.23074750678121858.
Fold 1 IBS: 0.2409482065148207
Fold 2 IBS: 0.22548074688500788
Fold 3 IBS: 0.22218016838847504
Fold 4 IBS: 0.23628101146650415
Fold 5 IBS: 0.22161830859386844
[I 2024-04-13 21:20:02,083] Trial 91 finished with value: 0.22930168836973525 and parameters: {'subsample': 0.3646963250854607, 'learning_rate': 0.09255241886126767, 'dropout_rate': 0.12363276406693596, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 0.03832008885345805, 'min_weight_fraction_leaf': 0.14198218649980035, 'max_features': None, 'min_impurity_decrease': 6.12703415921239e-07, 'validation_fraction': 0.965806971606102, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24720356529080675
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:20:18,391] Trial 92 finished with value: 0.23591913648117407 and parameters: {'subsample': 0.37023851203307184, 'learning_rate': 0.08893737188983004, 'dropout_rate': 0.20172874940955723, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.25929761360970466, 'min_weight_fraction_leaf': 0.14091910204137698, 'max_features': None, 'min_impurity_decrease': 1.670575123081423e-06, 'validation_fraction': 0.9646916032715627, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:20:34,151] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3393392217612321, 'learning_rate': 0.08484939828620154, 'dropout_rate': 0.1330785179258292, 'n_estimators': 141, 'criterion': 'squared_error', 'ccp_alpha': 0.5271800261864423, 'min_weight_fraction_leaf': 0.22342629975429745, 'max_features': None, 'min_impurity_decrease': 6.529634824832721e-07, 'validation_fraction': 0.9250469615937894, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:20:42,518] Trial 94 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.30155497875372905, 'learning_rate': 0.09226836699183699, 'dropout_rate': 0.16486788507480765, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 4.0703783464897505, 'min_weight_fraction_leaf': 0.08717516087188838, 'max_features': None, 'min_impurity_decrease': 4.324897116213418e-07, 'validation_fraction': 0.902599975518271, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:20:54,007] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.22711241501967083, 'learning_rate': 0.09399734029654892, 'dropout_rate': 0.23424050775181726, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.2155841604325495, 'min_weight_fraction_leaf': 0.1987273188587709, 'max_features': None, 'min_impurity_decrease': 0.0002775108319921543, 'validation_fraction': 0.9754822510610521, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 8}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24720275004054537
Fold 2 IBS: 0.23200270748604027
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:21:11,345] Trial 96 finished with value: 0.23591153802074527 and parameters: {'subsample': 0.5095341352345704, 'learning_rate': 0.08725364328306122, 'dropout_rate': 0.3223450290700977, 'n_estimators': 169, 'criterion': 'squared_error', 'ccp_alpha': 0.1763548129966652, 'min_weight_fraction_leaf': 0.18056333859719206, 'max_features': None, 'min_impurity_decrease': 8.711621987475722e-07, 'validation_fraction': 0.9501887884981254, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:21:31,852] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38054192896008343, 'learning_rate': 0.0907069703578099, 'dropout_rate': 0.29952255515083975, 'n_estimators': 185, 'criterion': 'squared_error', 'ccp_alpha': 0.8146747487056372, 'min_weight_fraction_leaf': 0.12179773041599615, 'max_features': None, 'min_impurity_decrease': 2.402128990085841e-07, 'validation_fraction': 0.8821221020751453, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:21:59,147] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.46077614751832996, 'learning_rate': 0.09701740438937595, 'dropout_rate': 0.25455243694522434, 'n_estimators': 199, 'criterion': 'friedman_mse', 'ccp_alpha': 4.816291450322713, 'min_weight_fraction_leaf': 0.14615364156535707, 'max_features': None, 'min_impurity_decrease': 1.4006375376158358e-07, 'validation_fraction': 0.9833042102806464, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 6}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24343373022583664
Fold 2 IBS: 0.2272980963057972
Fold 3 IBS: 0.22299173682453308

Fold 4 IBS: 0.23852342496708018
Fold 5 IBS: 0.22486084489133845
[I 2024-04-13 21:22:14,106] Trial 99 finished with value: 0.23142156664291713 and parameters: {'subsample': 0.40791967441342253, 'learning_rate': 0.07712333235501795, 'dropout_rate': 0.19859974199600133, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 0.004426170739568851, 'min_weight_fraction_leaf': 0.16314282359709542, 'max_features': 'log2', 'min_impurity_decrease': 5.353566353972388e-07, 'validation_fraction': 0.1604355124738367, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 91 with value: 0.22930168836973525.


* Best trial for IBS:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.22930168836973525], datetime_start=datetime.datetime(2024, 4, 13, 21, 19, 46, 152887), datetime_complete=datetime.datetime(2024, 4, 13, 21, 20, 2, 75653), params={'subsample': 0.3646963250854607, 'learning_rate': 0.09255241886126767, 'dropout_rate': 0.12363276406693596, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 0.03832008885345805, 'min_weight_fraction_leaf': 0.14198218649980035, 'max_features': None, 'min_impurity_decrease': 6.12703415921239e-07, 'validation_fraction': 0.965806971606102, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 4}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=91, value=None)


* Best Score for IBS:
 0.22930168836973525

In [87]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [88]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.648
train_ibs:  0.229

#### Test

In [89]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [90]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.02647951541473475,
                                 criterion='squared_error',
                                 dropout_rate=0.14303111133639826,
                                 learning_rate=0.05317196534413593,
                                 max_depth=19, max_features=0.1,
                                 max_leaf_nodes=15,
                                 min_impurity_decrease=7.356647091617949e-06,
                                 min_samples_leaf=17, min_samples_split=19,
                                 min_weight_fraction_leaf=0.35066087197674667,
                                 n_estimators=78, random_state=123,
                                 subsample=0.9736544653699906,
                                 validation_fraction=0.6117331205297228)

C-index score: 0.639

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03832008885345805,
                                 criterion='squared_error',
                                 dropout_rate=0.12363276406693596,
                                 learning_rate=0.09255241886126767, max_depth=4,
                                 max_leaf_nodes=15,
                                 min_impurity_decrease=6.12703415921239e-07,
                                 min_samples_leaf=16, min_samples_split=13,
                                 min_weight_fraction_leaf=0.14198218649980035,
                                 n_estimators=143, random_state=123,
                                 subsample=0.3646963250854607,
                                 validation_fraction=0.965806971606102)

IBS: 0.221

In [91]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [92]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [93]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 21:22:20,411] A new study created in memory with name: no-name-3ed9c695-297b-467d-b777-fea831c38bae

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.4903100775193798
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:22:22,460] Trial 0 finished with value: 0.5551603921344974 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.5551603921344974.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.48643410852713176
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 21:22:39,600] Trial 1 finished with value: 0.5552435674347602 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.5552435674347602.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 21:22:42,837] Trial 2 finished with value: 0.5726901291914885 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.5726901291914885.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:22:48,094] Trial 3 finished with value: 0.5804752810967445 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.5804752810967445.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5851063829787234
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:22:56,298] Trial 4 finished with value: 0.5870780207302427 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.5870780207302427.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.4941860465116279
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:23:04,001] Trial 5 finished with value: 0.5682590580021172 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.5870780207302427.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:23:07,409] Trial 6 finished with value: 0.5567107797313966 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.5870780207302427.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.501937984496124
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:23:08,156] Trial 7 finished with value: 0.5817752944710677 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.5870780207302427.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.4941860465116279
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:23:12,113] Trial 8 finished with value: 0.5719076301241136 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.5870780207302427.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:23:23,110] Trial 9 finished with value: 0.5768280838107797 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.5870780207302427.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:23:30,683] Trial 10 finished with value: 0.5960818646649336 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.5960818646649336.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:23:39,742] Trial 11 finished with value: 0.6167560789980233 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.6167560789980233.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:23:49,309] Trial 12 finished with value: 0.6175165352717875 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 21:23:59,651] Trial 13 finished with value: 0.5560482362825805 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:24:07,175] Trial 14 finished with value: 0.6050499063582693 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:24:14,382] Trial 15 finished with value: 0.590496886587242 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6191489361702127
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:24:29,250] Trial 16 finished with value: 0.6001270444823443 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5765957446808511
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:24:41,443] Trial 17 finished with value: 0.5878530875418574 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 416, 'learning_rate': 0.08639690405722114}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:24:47,129] Trial 18 finished with value: 0.583728016491877 and parameters: {'subsample': 0.35801092912005106, 'dropout_rate': 0.33602353085084236, 'n_estimators': 256, 'learning_rate': 0.08307767561539126}. Best is trial 12 with value: 0.6175165352717875.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6148936170212767
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:24:49,086] Trial 19 finished with value: 0.6141526576291104 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7254192287154788, 'n_estimators': 117, 'learning_rate': 0.09614402133777997}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:25:02,406] Trial 20 finished with value: 0.5935534492069844 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 423, 'learning_rate': 0.07788582119853761}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:25:02,819] Trial 21 finished with value: 0.6026037316418689 and parameters: {'subsample': 0.11001094780860332, 'dropout_rate': 0.7075879968118339, 'n_estimators': 12, 'learning_rate': 0.09417886707495288}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:25:04,285] Trial 22 finished with value: 0.6108026533907448 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.7646900707403661, 'n_estimators': 92, 'learning_rate': 0.09079561778768044}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:25:11,204] Trial 23 finished with value: 0.5945876973329671 and parameters: {'subsample': 0.18416659954432174, 'dropout_rate': 0.5772650959496687, 'n_estimators': 311, 'learning_rate': 0.06498100052925637}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5174418604651163
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:25:13,006] Trial 24 finished with value: 0.5953783595104187 and parameters: {'subsample': 0.2045297048439274, 'dropout_rate': 0.9686347225905483, 'n_estimators': 133, 'learning_rate': 0.07843777531541643}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:25:16,658] Trial 25 finished with value: 0.5749339647632178 and parameters: {'subsample': 0.4132414033804696, 'dropout_rate': 0.8139553387854312, 'n_estimators': 231, 'learning_rate': 0.09478486238393272}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.501937984496124
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:25:19,052] Trial 26 finished with value: 0.5786971129007709 and parameters: {'subsample': 0.2942732104482271, 'dropout_rate': 0.5707562654379044, 'n_estimators': 150, 'learning_rate': 0.08146277028320098}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 21:25:24,259] Trial 27 finished with value: 0.5560482362825805 and parameters: {'subsample': 0.9555788020080305, 'dropout_rate': 0.6426159203387378, 'n_estimators': 280, 'learning_rate': 0.04133902891970489}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.501937984496124
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:25:32,326] Trial 28 finished with value: 0.5764696148354316 and parameters: {'subsample': 0.6088999383640823, 'dropout_rate': 0.3080593480767576, 'n_estimators': 338, 'learning_rate': 0.09352800640830385}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:25:33,797] Trial 29 finished with value: 0.555189867183868 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.41533846889329507, 'n_estimators': 101, 'learning_rate': 0.06046208382653473}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6106382978723405
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:25:34,697] Trial 30 finished with value: 0.5994791115713787 and parameters: {'subsample': 0.1573472469684153, 'dropout_rate': 0.16903977002361698, 'n_estimators': 57, 'learning_rate': 0.016814619253793885}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:25:35,689] Trial 31 finished with value: 0.6081369385385844 and parameters: {'subsample': 0.10801177869921114, 'dropout_rate': 0.7903325524549772, 'n_estimators': 68, 'learning_rate': 0.08930186045801615}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6148936170212767
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:25:37,477] Trial 32 finished with value: 0.6133558448801064 and parameters: {'subsample': 0.102000681955651, 'dropout_rate': 0.759813023960115, 'n_estimators': 105, 'learning_rate': 0.09964450890539911}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5058139534883721
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:25:37,851] Trial 33 finished with value: 0.5839298380059927 and parameters: {'subsample': 0.22307046077094378, 'dropout_rate': 0.5183018271503333, 'n_estimators': 11, 'learning_rate': 0.09966997282956479}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.501937984496124
Fold 3 C-index: 0.5765957446808511
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:25:40,090] Trial 34 finished with value: 0.5808301520782413 and parameters: {'subsample': 0.31478192981222664, 'dropout_rate': 0.6285737999908603, 'n_estimators': 147, 'learning_rate': 0.07020090334404173}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:25:43,446] Trial 35 finished with value: 0.5960455081896939 and parameters: {'subsample': 0.16710472630778297, 'dropout_rate': 0.9998452404960969, 'n_estimators': 232, 'learning_rate': 0.07461987923632134}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:25:52,147] Trial 36 finished with value: 0.6035620662182873 and parameters: {'subsample': 0.14724321451633232, 'dropout_rate': 0.8447568264782302, 'n_estimators': 385, 'learning_rate': 0.0935291689238344}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5893617021276596
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:25:55,068] Trial 37 finished with value: 0.5919714041528037 and parameters: {'subsample': 0.23690750281044962, 'dropout_rate': 0.47096246897520044, 'n_estimators': 170, 'learning_rate': 0.0831463837563409}. Best is trial 12 with value: 0.6175165352717875.

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5893617021276596
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:25:56,795] Trial 38 finished with value: 0.5988918044910758 and parameters: {'subsample': 0.1504722419513361, 'dropout_rate': 0.9099198027137476, 'n_estimators': 123, 'learning_rate': 0.09639188175417894}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5765957446808511
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:26:00,593] Trial 39 finished with value: 0.5826194768749857 and parameters: {'subsample': 0.3126255482240327, 'dropout_rate': 0.29848665859072016, 'n_estimators': 198, 'learning_rate': 0.06892741183938003}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:26:07,454] Trial 40 finished with value: 0.5777155041158066 and parameters: {'subsample': 0.43117832251264454, 'dropout_rate': 0.7596070107352829, 'n_estimators': 333, 'learning_rate': 0.07740117663397339}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6106382978723405
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:26:08,877] Trial 41 finished with value: 0.6117806812517947 and parameters: {'subsample': 0.10471436370118233, 'dropout_rate': 0.7091273643578635, 'n_estimators': 97, 'learning_rate': 0.09138553464356945}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5765957446808511
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:26:10,127] Trial 42 finished with value: 0.5856976584452825 and parameters: {'subsample': 0.23532681149011603, 'dropout_rate': 0.6954623000860509, 'n_estimators': 88, 'learning_rate': 0.09047202117490553}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 21:26:10,711] Trial 43 finished with value: 0.6071330959810182 and parameters: {'subsample': 0.13840274528511398, 'dropout_rate': 0.6176715828207425, 'n_estimators': 37, 'learning_rate': 0.08500999116143078}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:26:17,044] Trial 44 finished with value: 0.6009709729125927 and parameters: {'subsample': 0.18980837503934622, 'dropout_rate': 0.13928344550648972, 'n_estimators': 276, 'learning_rate': 0.0963689949419925}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:26:19,782] Trial 45 finished with value: 0.5559503234576324 and parameters: {'subsample': 0.7937809606966539, 'dropout_rate': 0.7382636466048755, 'n_estimators': 175, 'learning_rate': 0.09048654208014131}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6106382978723405
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:26:21,290] Trial 46 finished with value: 0.6086661432062581 and parameters: {'subsample': 0.13247691307003695, 'dropout_rate': 0.8785760103056234, 'n_estimators': 108, 'learning_rate': 0.09913426791682374}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:26:22,349] Trial 47 finished with value: 0.6138808349610415 and parameters: {'subsample': 0.10379980363501204, 'dropout_rate': 0.6900330534879336, 'n_estimators': 77, 'learning_rate': 0.08063451221472408}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:26:23,040] Trial 48 finished with value: 0.5574712360051608 and parameters: {'subsample': 0.5990656023377149, 'dropout_rate': 0.19701471782839963, 'n_estimators': 33, 'learning_rate': 0.08106775275829065}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:26:24,011] Trial 49 finished with value: 0.5915531775068352 and parameters: {'subsample': 0.1861830169994726, 'dropout_rate': 0.8158866255073626, 'n_estimators': 69, 'learning_rate': 0.07376951860699396}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5851063829787234
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:26:33,745] Trial 50 finished with value: 0.5895552152014318 and parameters: {'subsample': 0.24408754305382246, 'dropout_rate': 0.5153152946770089, 'n_estimators': 393, 'learning_rate': 0.08623797291170951}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:26:34,981] Trial 51 finished with value: 0.6123235659382733 and parameters: {'subsample': 0.10367517605274414, 'dropout_rate': 0.675753894596219, 'n_estimators': 84, 'learning_rate': 0.09161415517119584}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:26:36,178] Trial 52 finished with value: 0.6061620765326722 and parameters: {'subsample': 0.13637380813559394, 'dropout_rate': 0.657652677382563, 'n_estimators': 81, 'learning_rate': 0.09634059940157354}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:26:42,171] Trial 53 finished with value: 0.5954387611627543 and parameters: {'subsample': 0.18567710820139163, 'dropout_rate': 0.6783241532776428, 'n_estimators': 294, 'learning_rate': 0.08805675888751904}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:26:44,124] Trial 54 finished with value: 0.6000509204773368 and parameters: {'subsample': 0.15652319358305927, 'dropout_rate': 0.6038861306290194, 'n_estimators': 127, 'learning_rate': 0.09897924103894118}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6659574468085107
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 21:26:44,754] Trial 55 finished with value: 0.6124303053314651 and parameters: {'subsample': 0.10775071783618476, 'dropout_rate': 0.12352453256561395, 'n_estimators': 27, 'learning_rate': 0.0929093594804002}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 21:26:45,317] Trial 56 finished with value: 0.5785107604013324 and parameters: {'subsample': 0.2696935295856255, 'dropout_rate': 0.13558418258547944, 'n_estimators': 20, 'learning_rate': 0.07984407076947674}. Best is trial 12 with value: 0.6175165352717875.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.6148936170212767
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:26:46,121] Trial 57 finished with value: 0.5888294222693785 and parameters: {'subsample': 0.20529604770448145, 'dropout_rate': 0.10681264065747736, 'n_estimators': 43, 'learning_rate': 0.08556232630713814}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6234042553191489
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:26:54,795] Trial 58 finished with value: 0.6074170533267986 and parameters: {'subsample': 0.13722391212638793, 'dropout_rate': 0.22037157727939666, 'n_estimators': 330, 'learning_rate': 0.056882148067127714}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6276595744680851
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:26:59,851] Trial 59 finished with value: 0.6104515731529304 and parameters: {'subsample': 0.10183265607410649, 'dropout_rate': 0.2645251087109975, 'n_estimators': 245, 'learning_rate': 0.047267601674035827}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:27:09,221] Trial 60 finished with value: 0.599177940840774 and parameters: {'subsample': 0.17450415280706522, 'dropout_rate': 0.14490942029526271, 'n_estimators': 355, 'learning_rate': 0.03723183452431825}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6234042553191489
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:27:10,293] Trial 61 finished with value: 0.6150579725396809 and parameters: {'subsample': 0.1260542958713624, 'dropout_rate': 0.7390307411312055, 'n_estimators': 74, 'learning_rate': 0.09318014872208186}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5213178294573644
Fold 3 C-index: 0.5893617021276596
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:27:11,084] Trial 62 finished with value: 0.587570962710176 and parameters: {'subsample': 0.21547317240133051, 'dropout_rate': 0.7603245381010786, 'n_estimators': 56, 'learning_rate': 0.09498514606175294}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:27:13,637] Trial 63 finished with value: 0.6043749313755203 and parameters: {'subsample': 0.1308716913944263, 'dropout_rate': 0.19092239897151958, 'n_estimators': 147, 'learning_rate': 0.09328992622526418}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6155378486055777
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6106382978723405
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:27:14,136] Trial 64 finished with value: 0.6063582527120556 and parameters: {'subsample': 0.15871808317716796, 'dropout_rate': 0.7964413437867793, 'n_estimators': 21, 'learning_rate': 0.08869152010497483}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6106382978723405
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:27:15,174] Trial 65 finished with value: 0.6054648489365444 and parameters: {'subsample': 0.12789522032437103, 'dropout_rate': 0.7438634569777361, 'n_estimators': 60, 'learning_rate': 0.09720155136602122}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5135658914728682
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:27:16,728] Trial 66 finished with value: 0.5922854404154366 and parameters: {'subsample': 0.20224988627357493, 'dropout_rate': 0.8318940602875312, 'n_estimators': 112, 'learning_rate': 0.08432788132165371}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5851063829787234
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:27:17,864] Trial 67 finished with value: 0.5911203403230165 and parameters: {'subsample': 0.1722029600635453, 'dropout_rate': 0.78024249360139, 'n_estimators': 74, 'learning_rate': 0.08794235702614157}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:27:33,714] Trial 68 finished with value: 0.5854447546893019 and parameters: {'subsample': 0.34136670543047176, 'dropout_rate': 0.3967866816504156, 'n_estimators': 496, 'learning_rate': 0.0267624773650322}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:27:42,107] Trial 69 finished with value: 0.5951944443599066 and parameters: {'subsample': 0.25273442131857526, 'dropout_rate': 0.11954140078035906, 'n_estimators': 312, 'learning_rate': 0.07654141068951228}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:27:43,394] Trial 70 finished with value: 0.6061458542550568 and parameters: {'subsample': 0.12205375954532723, 'dropout_rate': 0.9119661656090492, 'n_estimators': 49, 'learning_rate': 0.008127880939407618}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 21:27:43,820] Trial 71 finished with value: 0.6109302806054443 and parameters: {'subsample': 0.1076503841642071, 'dropout_rate': 0.6818481059966642, 'n_estimators': 6, 'learning_rate': 0.09233787195196133}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:27:45,481] Trial 72 finished with value: 0.6123235659382733 and parameters: {'subsample': 0.10290846695709172, 'dropout_rate': 0.7126088177050938, 'n_estimators': 84, 'learning_rate': 0.09998143844194028}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:27:58,757] Trial 73 finished with value: 0.6060319554205512 and parameters: {'subsample': 0.15167667226371728, 'dropout_rate': 0.5761260263802436, 'n_estimators': 444, 'learning_rate': 0.09312223531831598}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5213178294573644
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:27:59,405] Trial 74 finished with value: 0.6019769006865774 and parameters: {'subsample': 0.10099983845623818, 'dropout_rate': 0.1686608344062563, 'n_estimators': 29, 'learning_rate': 0.08236297867238868}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.48255813953488375
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:28:01,882] Trial 75 finished with value: 0.5528495482638339 and parameters: {'subsample': 0.6882223870109341, 'dropout_rate': 0.657765720071159, 'n_estimators': 159, 'learning_rate': 0.09651132721041242}. Best is trial 12 with value: 0.6175165352717875.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.5893617021276596
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:28:03,619] Trial 76 finished with value: 0.5894647346322438 and parameters: {'subsample': 0.21941832731063385, 'dropout_rate': 0.7379022283778469, 'n_estimators': 120, 'learning_rate': 0.09046290813175145}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:28:05,787] Trial 77 finished with value: 0.6024155915857273 and parameters: {'subsample': 0.1719995320308077, 'dropout_rate': 0.21059615104780455, 'n_estimators': 133, 'learning_rate': 0.09437706060700309}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6234042553191489
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:28:09,166] Trial 78 finished with value: 0.6063992150534295 and parameters: {'subsample': 0.1317370346799551, 'dropout_rate': 0.5471236869901268, 'n_estimators': 194, 'learning_rate': 0.08700162828835997}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:28:10,457] Trial 79 finished with value: 0.5953918153508962 and parameters: {'subsample': 0.18732705198763672, 'dropout_rate': 0.8749042812122334, 'n_estimators': 101, 'learning_rate': 0.0916483682301753}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:28:11,523] Trial 80 finished with value: 0.5822899321191175 and parameters: {'subsample': 0.29509125144368054, 'dropout_rate': 0.43677314308627263, 'n_estimators': 70, 'learning_rate': 0.09771641686265446}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:28:12,833] Trial 81 finished with value: 0.6030386214784456 and parameters: {'subsample': 0.11441080339464722, 'dropout_rate': 0.7191150406533591, 'n_estimators': 84, 'learning_rate': 0.09996307047280543}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:28:14,434] Trial 82 finished with value: 0.5997792247961027 and parameters: {'subsample': 0.15073611068215856, 'dropout_rate': 0.7071042547656076, 'n_estimators': 92, 'learning_rate': 0.09536192436050486}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.4941860465116279
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 21:28:15,618] Trial 83 finished with value: 0.5712450866752976 and parameters: {'subsample': 0.5104385117001161, 'dropout_rate': 0.6421886730626755, 'n_estimators': 49, 'learning_rate': 0.08951514749934482}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:28:17,890] Trial 84 finished with value: 0.6098754226733987 and parameters: {'subsample': 0.12244596355727522, 'dropout_rate': 0.6091907775171916, 'n_estimators': 110, 'learning_rate': 0.09810528642693209}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:28:19,242] Trial 85 finished with value: 0.6138808349610415 and parameters: {'subsample': 0.10222253727261364, 'dropout_rate': 0.6915522471714789, 'n_estimators': 77, 'learning_rate': 0.09255235463649004}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.5321888412017167
[I 2024-04-13 21:28:25,570] Trial 86 finished with value: 0.5490001447667268 and parameters: {'subsample': 0.992873343787547, 'dropout_rate': 0.6827782476058387, 'n_estimators': 293, 'learning_rate': 0.09232478733671803}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5135658914728682
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:28:27,821] Trial 87 finished with value: 0.5909239970425648 and parameters: {'subsample': 0.15727773639726633, 'dropout_rate': 0.7773069377675451, 'n_estimators': 60, 'learning_rate': 0.06559088056864305}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:28:35,325] Trial 88 finished with value: 0.6051589757839884 and parameters: {'subsample': 0.1255943095971866, 'dropout_rate': 0.8014171550401745, 'n_estimators': 343, 'learning_rate': 0.08248723201556751}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:28:35,769] Trial 89 finished with value: 0.5339413040925249 and parameters: {'subsample': 0.39515068349808363, 'dropout_rate': 0.16689331308725722, 'n_estimators': 2, 'learning_rate': 0.08527859235506666}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6148936170212767
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:28:49,100] Trial 90 finished with value: 0.6009164249755881 and parameters: {'subsample': 0.19697097879223446, 'dropout_rate': 0.10184332440552968, 'n_estimators': 375, 'learning_rate': 0.07917896871067848}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:28:50,723] Trial 91 finished with value: 0.5982510069796491 and parameters: {'subsample': 0.11285131492548771, 'dropout_rate': 0.7329397584264961, 'n_estimators': 99, 'learning_rate': 0.09985122447227965}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:28:52,172] Trial 92 finished with value: 0.6036485255862433 and parameters: {'subsample': 0.14328994842842419, 'dropout_rate': 0.6963711705192237, 'n_estimators': 80, 'learning_rate': 0.09568667934980632}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:29:00,038] Trial 93 finished with value: 0.6115906155297303 and parameters: {'subsample': 0.10116152477601234, 'dropout_rate': 0.7534589731560937, 'n_estimators': 322, 'learning_rate': 0.08928189227888794}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:29:02,812] Trial 94 finished with value: 0.6082808854971218 and parameters: {'subsample': 0.16584758448873732, 'dropout_rate': 0.1260789509040807, 'n_estimators': 134, 'learning_rate': 0.09452025606843689}. Best is trial 12 with value: 0.6175165352717875.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6106382978723405
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:29:04,427] Trial 95 finished with value: 0.6132652373240834 and parameters: {'subsample': 0.1005574092352955, 'dropout_rate': 0.666461440442464, 'n_estimators': 90, 'learning_rate': 0.09176980783048941}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:29:10,612] Trial 96 finished with value: 0.6055069653396162 and parameters: {'subsample': 0.1387541607512829, 'dropout_rate': 0.6344591426799427, 'n_estimators': 269, 'learning_rate': 0.0877084697048795}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5893617021276596
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:29:15,344] Trial 97 finished with value: 0.5887874536587424 and parameters: {'subsample': 0.22570028642335044, 'dropout_rate': 0.5915083285154504, 'n_estimators': 216, 'learning_rate': 0.09084167419579786}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5135658914728682
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:29:16,150] Trial 98 finished with value: 0.6029189329207655 and parameters: {'subsample': 0.18189849084470455, 'dropout_rate': 0.6579250386014912, 'n_estimators': 32, 'learning_rate': 0.0925379940978049}. Best is trial 12 with value: 0.6175165352717875.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6234042553191489
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:29:17,381] Trial 99 finished with value: 0.611707671445094 and parameters: {'subsample': 0.12400618462731627, 'dropout_rate': 0.5172981403759904, 'n_estimators': 73, 'learning_rate': 0.0974882145481635}. Best is trial 12 with value: 0.6175165352717875.


* Best trial for C-index:
 FrozenTrial(number=12, state=TrialState.COMPLETE, values=[0.6175165352717875], datetime_start=datetime.datetime(2024, 4, 13, 21, 23, 39, 750045), datetime_complete=datetime.datetime(2024, 4, 13, 21, 23, 49, 308735), params={'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=12, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}


* Best Score for C-index:
 0.6175165352717875

[I 2024-04-13 21:29:17,398] A new study created in memory with name: no-name-ef47f682-5cbd-4fb2-a16d-7ccdda33de3f

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2768605959166274
Fold 2 IBS: 0.3036581885611299
Fold 3 IBS: 0.2644264860571975
Fold 4 IBS: 0.28685443832135615
Fold 5 IBS: 0.23049650269649638
[I 2024-04-13 21:29:19,428] Trial 0 finished with value: 0.2724592423105615 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2724592423105615.
Fold 1 IBS: 0.3314083926697305
Fold 2 IBS: 0.46023211461621694
Fold 3 IBS: 0.32275947223526036
Fold 4 IBS: 0.39112351921928445
Fold 5 IBS: 0.339376702626222
[I 2024-04-13 21:29:35,388] Trial 1 finished with value: 0.36898004027334286 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2724592423105615.
Fold 1 IBS: 0.30914429913017866
Fold 2 IBS: 0.37637524794948946
Fold 3 IBS: 0.30561411095953644
Fold 4 IBS: 0.3285718471988962
Fold 5 IBS: 0.3100934076743383
[I 2024-04-13 21:29:38,419] Trial 2 finished with value: 0.32595978258248776 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2724592423105615.
Fold 1 IBS: 0.3078899769382786
Fold 2 IBS: 0.3570988873609887
Fold 3 IBS: 0.3035532777950627
Fold 4 IBS: 0.34514445112588066
Fold 5 IBS: 0.26650386822263317
[I 2024-04-13 21:29:43,376] Trial 3 finished with value: 0.3160380922885688 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2724592423105615.
Fold 1 IBS: 0.3071251323809744
Fold 2 IBS: 0.3567178250196466
Fold 3 IBS: 0.2989689105169528
Fold 4 IBS: 0.35416778435867347
Fold 5 IBS: 0.2812461385031304
[I 2024-04-13 21:29:50,076] Trial 4 finished with value: 0.3196451581558756 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2724592423105615.
Fold 1 IBS: 0.3328867486409142
Fold 2 IBS: 0.45737609071385643
Fold 3 IBS: 0.32083565149957505
Fold 4 IBS: 0.3706674002598403
Fold 5 IBS: 0.33923818447315957
[I 2024-04-13 21:29:58,613] Trial 5 finished with value: 0.3642008151174691 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2724592423105615.
Fold 1 IBS: 0.2583770894605203
Fold 2 IBS: 0.2857814818985479
Fold 3 IBS: 0.24143226956074204
Fold 4 IBS: 0.2793158367893892
Fold 5 IBS: 0.21760040361445157
[I 2024-04-13 21:30:02,093] Trial 6 finished with value: 0.2565014162647302 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2565014162647302.
Fold 1 IBS: 0.24415178034005855
Fold 2 IBS: 0.2412707825406151
Fold 3 IBS: 0.2179734305217783
Fold 4 IBS: 0.26619990250833797
Fold 5 IBS: 0.2141593818792363
[I 2024-04-13 21:30:02,850] Trial 7 finished with value: 0.23675105555800524 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.23675105555800524.
Fold 1 IBS: 0.27394902748358135
Fold 2 IBS: 0.3097473739416778
Fold 3 IBS: 0.2686587961464619
Fold 4 IBS: 0.2932983581596596
Fold 5 IBS: 0.22610047650933945
[I 2024-04-13 21:30:07,687] Trial 8 finished with value: 0.274350806448144 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.23675105555800524.
Fold 1 IBS: 0.3196633503952017
Fold 2 IBS: 0.4318764254294795
Fold 3 IBS: 0.3211305681955956
Fold 4 IBS: 0.38979528782039985
Fold 5 IBS: 0.3390240231257648
[I 2024-04-13 21:30:18,554] Trial 9 finished with value: 0.3602979309932883 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.23675105555800524.
Fold 1 IBS: 0.2470353461515696
Fold 2 IBS: 0.23221934841922323
Fold 3 IBS: 0.22841230778724064
Fold 4 IBS: 0.24171407848753257
Fold 5 IBS: 0.22906264846898927
[I 2024-04-13 21:30:19,169] Trial 10 finished with value: 0.23568874586291105 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.23568874586291105.
Fold 1 IBS: 0.24639976969987745
Fold 2 IBS: 0.2328507694823116
Fold 3 IBS: 0.22670631441579872
Fold 4 IBS: 0.24087071384643838
Fold 5 IBS: 0.2279748608955893
[I 2024-04-13 21:30:19,521] Trial 11 finished with value: 0.23496048566800312 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 11 with value: 0.23496048566800312.
Fold 1 IBS: 0.2664418388990431
Fold 2 IBS: 0.3076016489022325
Fold 3 IBS: 0.2511706524883229
Fold 4 IBS: 0.2453044981015664
Fold 5 IBS: 0.22893310831832445
[I 2024-04-13 21:30:20,361] Trial 12 finished with value: 0.25989034934189786 and parameters: {'subsample': 0.9876601507615164, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.23496048566800312.
Fold 1 IBS: 0.24713256528114305
Fold 2 IBS: 0.23213446241221616
Fold 3 IBS: 0.2286782010734839
Fold 4 IBS: 0.24183317728386672
Fold 5 IBS: 0.22921606612925213
[I 2024-04-13 21:30:20,751] Trial 13 finished with value: 0.2357988944359924 and parameters: {'subsample': 0.9944701185331792, 'dropout_rate': 0.7324371247382785, 'n_estimators': 3, 'learning_rate': 0.007730532223257889}. Best is trial 11 with value: 0.23496048566800312.
Fold 1 IBS: 0.31210193287371296
Fold 2 IBS: 0.3876307854293873
Fold 3 IBS: 0.29736322644688906
Fold 4 IBS: 0.3071453381172056
Fold 5 IBS: 0.3185545325624425
[I 2024-04-13 21:30:22,098] Trial 14 finished with value: 0.3245591630859275 and parameters: {'subsample': 0.8619663815733164, 'dropout_rate': 0.9788958362896205, 'n_estimators': 102, 'learning_rate': 0.09964313305557901}. Best is trial 11 with value: 0.23496048566800312.
Fold 1 IBS: 0.24711686891035045
Fold 2 IBS: 0.2321489778956536
Fold 3 IBS: 0.22862927980669817
Fold 4 IBS: 0.24203529698532833
Fold 5 IBS: 0.22919080235621078
[I 2024-04-13 21:30:22,653] Trial 15 finished with value: 0.23582424519084827 and parameters: {'subsample': 0.8897480564271555, 'dropout_rate': 0.7907695329663884, 'n_estimators': 13, 'learning_rate': 0.0020295313566686345}. Best is trial 11 with value: 0.23496048566800312.
Fold 1 IBS: 0.40550989741200144
Fold 2 IBS: 0.3775898202151131
Fold 3 IBS: 0.29786100106066715
Fold 4 IBS: 0.40810224788983107
Fold 5 IBS: 0.3223297694298426
[I 2024-04-13 21:30:28,970] Trial 16 finished with value: 0.3622785472014911 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.6024217769414767, 'n_estimators': 293, 'learning_rate': 0.08820363883892024}. Best is trial 11 with value: 0.23496048566800312.
Fold 1 IBS: 0.24434213337975622
Fold 2 IBS: 0.2478336004875271
Fold 3 IBS: 0.2185981020679547
Fold 4 IBS: 0.24390261097395033
Fold 5 IBS: 0.21803612526793476
[I 2024-04-13 21:30:30,452] Trial 17 finished with value: 0.23454251443542465 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 99, 'learning_rate': 0.017248404573838205}. Best is trial 17 with value: 0.23454251443542465.
Fold 1 IBS: 0.24574673829685983
Fold 2 IBS: 0.25584420273794534
Fold 3 IBS: 0.2214809322597928
Fold 4 IBS: 0.248145005883306
Fold 5 IBS: 0.2159754991992173
[I 2024-04-13 21:30:32,296] Trial 18 finished with value: 0.23743847567542425 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.5718325144718232, 'n_estimators': 118, 'learning_rate': 0.01932159806301243}. Best is trial 17 with value: 0.23454251443542465.
Fold 1 IBS: 0.24948601456571115
Fold 2 IBS: 0.261887332515597

Fold 3 IBS: 0.2310576012464029
Fold 4 IBS: 0.27807484048509085
Fold 5 IBS: 0.21327756550890814
[I 2024-04-13 21:30:33,541] Trial 19 finished with value: 0.24675667086434197 and parameters: {'subsample': 0.6477795744201034, 'dropout_rate': 0.8173815053858949, 'n_estimators': 85, 'learning_rate': 0.03825176355689751}. Best is trial 17 with value: 0.23454251443542465.
Fold 1 IBS: 0.3380735899374104
Fold 2 IBS: 0.46733373445003945
Fold 3 IBS: 0.3220159248771053
Fold 4 IBS: 0.34521401041600086
Fold 5 IBS: 0.339374865845405
[I 2024-04-13 21:30:41,361] Trial 20 finished with value: 0.36240242510519216 and parameters: {'subsample': 0.8995742447068862, 'dropout_rate': 0.6343004869297953, 'n_estimators': 339, 'learning_rate': 0.0817175642960023}. Best is trial 17 with value: 0.23454251443542465.
Fold 1 IBS: 0.2447785911159304
Fold 2 IBS: 0.23613502747193257
Fold 3 IBS: 0.22167477293944274
Fold 4 IBS: 0.23857201410507312
Fold 5 IBS: 0.22438334443070537
[I 2024-04-13 21:30:42,234] Trial 21 finished with value: 0.23310875001261683 and parameters: {'subsample': 0.952235198850602, 'dropout_rate': 0.7387107106890588, 'n_estimators': 49, 'learning_rate': 0.01359953789503817}. Best is trial 21 with value: 0.23310875001261683.
Fold 1 IBS: 0.24831926953129926
Fold 2 IBS: 0.26477300021357636
Fold 3 IBS: 0.22658756657873866
Fold 4 IBS: 0.2667943580725494
Fold 5 IBS: 0.21435548062335397
[I 2024-04-13 21:30:44,613] Trial 22 finished with value: 0.24416593500390354 and parameters: {'subsample': 0.8058542955394907, 'dropout_rate': 0.7767756613631548, 'n_estimators': 145, 'learning_rate': 0.019662361544767103}. Best is trial 21 with value: 0.23310875001261683.
Fold 1 IBS: 0.24445119390349518
Fold 2 IBS: 0.23747753917777153
Fold 3 IBS: 0.22048956838052922
Fold 4 IBS: 0.23802627260132783
Fold 5 IBS: 0.22327524261980575
[I 2024-04-13 21:30:45,848] Trial 23 finished with value: 0.2327439633365859 and parameters: {'subsample': 0.9258176878598726, 'dropout_rate': 0.5302631221947481, 'n_estimators': 60, 'learning_rate': 0.013693154749890787}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24451716644942814
Fold 2 IBS: 0.23589827020552984
Fold 3 IBS: 0.2198133834273393
Fold 4 IBS: 0.2506109893453921
Fold 5 IBS: 0.22248957015126306
[I 2024-04-13 21:30:47,204] Trial 24 finished with value: 0.23466587591579047 and parameters: {'subsample': 0.6368881287840327, 'dropout_rate': 0.5020521283337119, 'n_estimators': 68, 'learning_rate': 0.013615550674754407}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.2550153108166354
Fold 2 IBS: 0.28027469662222665
Fold 3 IBS: 0.23579863313513003
Fold 4 IBS: 0.26840542003661344
Fold 5 IBS: 0.2164969696614647
[I 2024-04-13 21:30:49,846] Trial 25 finished with value: 0.25119820605441406 and parameters: {'subsample': 0.8108782643219917, 'dropout_rate': 0.3809375097483464, 'n_estimators': 144, 'learning_rate': 0.026279937075960214}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24418529264711905
Fold 2 IBS: 0.23924723597731992
Fold 3 IBS: 0.21942520649357594
Fold 4 IBS: 0.23917616038532027
Fold 5 IBS: 0.22200399334218468
[I 2024-04-13 21:30:51,137] Trial 26 finished with value: 0.23280757776910396 and parameters: {'subsample': 0.9143958693305009, 'dropout_rate': 0.6435204139107441, 'n_estimators': 72, 'learning_rate': 0.013952706455335116}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24629294382906425
Fold 2 IBS: 0.25758327968650574
Fold 3 IBS: 0.22191999433675355
Fold 4 IBS: 0.24454108050855294
Fold 5 IBS: 0.21573007530794255
[I 2024-04-13 21:30:56,050] Trial 27 finished with value: 0.23721347473376383 and parameters: {'subsample': 0.916616484564507, 'dropout_rate': 0.3060837787360696, 'n_estimators': 240, 'learning_rate': 0.009943359350679432}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24422285207273461
Fold 2 IBS: 0.24434873020650563
Fold 3 IBS: 0.21832448406730917
Fold 4 IBS: 0.25132632331135785
Fold 5 IBS: 0.21857630352776244
[I 2024-04-13 21:30:56,974] Trial 28 finished with value: 0.23535973863713394 and parameters: {'subsample': 0.8081365013046181, 'dropout_rate': 0.6534038405071922, 'n_estimators': 50, 'learning_rate': 0.031981052358301974}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.27120115929779615
Fold 2 IBS: 0.3018629672893348
Fold 3 IBS: 0.259110894392544
Fold 4 IBS: 0.2849701350303179
Fold 5 IBS: 0.22181098633051757
[I 2024-04-13 21:30:59,168] Trial 29 finished with value: 0.26779122846810205 and parameters: {'subsample': 0.6939569686320268, 'dropout_rate': 0.4333462181613713, 'n_estimators': 135, 'learning_rate': 0.04257484944621456}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24616859279321998
Fold 2 IBS: 0.24968336643072614
Fold 3 IBS: 0.22303945004971243
Fold 4 IBS: 0.27114988109915394
Fold 5 IBS: 0.2136882386088067
[I 2024-04-13 21:31:00,410] Trial 30 finished with value: 0.2407459057963238 and parameters: {'subsample': 0.5936384513688024, 'dropout_rate': 0.5261731798514812, 'n_estimators': 80, 'learning_rate': 0.03181412140403385}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24432387141524028
Fold 2 IBS: 0.24729348180038843
Fold 3 IBS: 0.21850641164710435
Fold 4 IBS: 0.23781247410393683
Fold 5 IBS: 0.21827987070651658
[I 2024-04-13 21:31:02,169] Trial 31 finished with value: 0.23324322193463728 and parameters: {'subsample': 0.9224235906435598, 'dropout_rate': 0.5958295279973077, 'n_estimators': 115, 'learning_rate': 0.014632255569267809}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24591775429435098
Fold 2 IBS: 0.23355842434143126
Fold 3 IBS: 0.225227278426223
Fold 4 IBS: 0.2403148257523751
Fold 5 IBS: 0.2270801510549345
[I 2024-04-13 21:31:02,924] Trial 32 finished with value: 0.23441968677386296 and parameters: {'subsample': 0.9219413842768851, 'dropout_rate': 0.6566461012802023, 'n_estimators': 39, 'learning_rate': 0.007753245317823161}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24430230920122067
Fold 2 IBS: 0.24496257983899314
Fold 3 IBS: 0.21836952080859198
Fold 4 IBS: 0.2530736830136257
Fold 5 IBS: 0.21859224454529427
[I 2024-04-13 21:31:04,716] Trial 33 finished with value: 0.23586006748154514 and parameters: {'subsample': 0.7545154725236596, 'dropout_rate': 0.48095898939081394, 'n_estimators': 117, 'learning_rate': 0.013763151745852418}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.2579320203899932
Fold 2 IBS: 0.29029632071365297
Fold 3 IBS: 0.24073187143014788
Fold 4 IBS: 0.24430119147181045
Fold 5 IBS: 0.21928319001655486
[I 2024-04-13 21:31:07,462] Trial 34 finished with value: 0.2505089188044319 and parameters: {'subsample': 0.9540701374345302, 'dropout_rate': 0.5673732019603027, 'n_estimators': 169, 'learning_rate': 0.024734341677464432}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.2453533209716652
Fold 2 IBS: 0.2343056504619512
Fold 3 IBS: 0.2235967629488579
Fold 4 IBS: 0.2430021864664064
Fold 5 IBS: 0.22596961759761808
[I 2024-04-13 21:31:08,637] Trial 35 finished with value: 0.23444550768929978 and parameters: {'subsample': 0.8208972865110351, 'dropout_rate': 0.43975685710717877, 'n_estimators': 75, 'learning_rate': 0.006012470238739063}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24524518452634828
Fold 2 IBS: 0.23482831611964466
Fold 3 IBS: 0.22323400402764318
Fold 4 IBS: 0.23936880172929972
Fold 5 IBS: 0.2256595959778253
[I 2024-04-13 21:31:09,436] Trial 36 finished with value: 0.23366718047615223 and parameters: {'subsample': 0.9394883073111426, 'dropout_rate': 0.8510326267789226, 'n_estimators': 35, 'learning_rate': 0.014085608457898462}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.3077116665726827
Fold 2 IBS: 0.37659909230793037
Fold 3 IBS: 0.2954122581262868
Fold 4 IBS: 0.3063113502676235
Fold 5 IBS: 0.30163072090024173
[I 2024-04-13 21:31:12,043] Trial 37 finished with value: 0.317533017634953 and parameters: {'subsample': 0.7586020581768255, 'dropout_rate': 0.7621022900062648, 'n_estimators': 165, 'learning_rate': 0.059207327336158105}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.2557605469425986
Fold 2 IBS: 0.2643776261223914

Fold 3 IBS: 0.2440845459176938
Fold 4 IBS: 0.28704196088136535
Fold 5 IBS: 0.20403552363244765
[I 2024-04-13 21:31:16,131] Trial 38 finished with value: 0.2510600406992994 and parameters: {'subsample': 0.41067080060139016, 'dropout_rate': 0.13272164755980653, 'n_estimators': 201, 'learning_rate': 0.02608547591740891}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24615375587585303
Fold 2 IBS: 0.24628523701425167
Fold 3 IBS: 0.2216904625741465
Fold 4 IBS: 0.27532206054080466
Fold 5 IBS: 0.21337163612042237
[I 2024-04-13 21:31:17,176] Trial 39 finished with value: 0.24056463042509563 and parameters: {'subsample': 0.6989144624450092, 'dropout_rate': 0.19258304600442933, 'n_estimators': 68, 'learning_rate': 0.0365566709162643}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.29575602982638
Fold 2 IBS: 0.36104264601421143
Fold 3 IBS: 0.2828990010999088
Fold 4 IBS: 0.2724769770883033
Fold 5 IBS: 0.288539279086917
[I 2024-04-13 21:31:28,082] Trial 40 finished with value: 0.30014278662314414 and parameters: {'subsample': 0.9436681117152587, 'dropout_rate': 0.6846059333347766, 'n_estimators': 434, 'learning_rate': 0.018704127083104174}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24526837743273816
Fold 2 IBS: 0.23477333462384076
Fold 3 IBS: 0.2232690667888868
Fold 4 IBS: 0.23938331635679289
Fold 5 IBS: 0.2256878257107561
[I 2024-04-13 21:31:28,806] Trial 41 finished with value: 0.23367638418260298 and parameters: {'subsample': 0.9434181994487222, 'dropout_rate': 0.8574190551452411, 'n_estimators': 41, 'learning_rate': 0.011912281889032244}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24536521887001594
Fold 2 IBS: 0.2345750304242687
Fold 3 IBS: 0.223570699043449
Fold 4 IBS: 0.2412516113438583
Fold 5 IBS: 0.22588318264674348
[I 2024-04-13 21:31:29,425] Trial 42 finished with value: 0.23412914846566707 and parameters: {'subsample': 0.8567554287097063, 'dropout_rate': 0.9012770511877676, 'n_estimators': 30, 'learning_rate': 0.015172113012798522}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24569313836593856
Fold 2 IBS: 0.23390302884438655
Fold 3 IBS: 0.22456802348362775
Fold 4 IBS: 0.24012681762961
Fold 5 IBS: 0.22661437978478943
[I 2024-04-13 21:31:30,800] Trial 43 finished with value: 0.23418107762167045 and parameters: {'subsample': 0.9418414111909245, 'dropout_rate': 0.8279299799833902, 'n_estimators': 93, 'learning_rate': 0.00387937035532155}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24763999171753712
Fold 2 IBS: 0.2613529119833908
Fold 3 IBS: 0.22404948223403923
Fold 4 IBS: 0.25057192053084154
Fold 5 IBS: 0.21515712833235814
[I 2024-04-13 21:31:32,471] Trial 44 finished with value: 0.23975428695963336 and parameters: {'subsample': 0.8446256628186269, 'dropout_rate': 0.9730304485276166, 'n_estimators': 121, 'learning_rate': 0.02170958141666924}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24484690318688934
Fold 2 IBS: 0.23496305257810637
Fold 3 IBS: 0.2220226245678212
Fold 4 IBS: 0.2454019217459937
Fold 5 IBS: 0.22469160582638045
[I 2024-04-13 21:31:33,061] Trial 45 finished with value: 0.2343852215810382 and parameters: {'subsample': 0.766327220393395, 'dropout_rate': 0.6119263398830317, 'n_estimators': 22, 'learning_rate': 0.02837823520088345}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24500368155041724
Fold 2 IBS: 0.2354316864837795
Fold 3 IBS: 0.22242687509029122
Fold 4 IBS: 0.23981075616328817
Fold 5 IBS: 0.22502864792751912
[I 2024-04-13 21:31:33,958] Trial 46 finished with value: 0.23354032944305905 and parameters: {'subsample': 0.9107413478362655, 'dropout_rate': 0.9073586923635283, 'n_estimators': 55, 'learning_rate': 0.010520003726088172}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.2451899122308112
Fold 2 IBS: 0.23492960281706626
Fold 3 IBS: 0.22302765336166755
Fold 4 IBS: 0.2392084772714251
Fold 5 IBS: 0.2255341886346766
[I 2024-04-13 21:31:34,896] Trial 47 finished with value: 0.23357796686312934 and parameters: {'subsample': 0.9971238640668071, 'dropout_rate': 0.9300042878121526, 'n_estimators': 62, 'learning_rate': 0.008209618821055878}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.33014387303579296
Fold 2 IBS: 0.42959009526655934
Fold 3 IBS: 0.3133093419516811
Fold 4 IBS: 0.32599781815975126
Fold 5 IBS: 0.33709290487185645
[I 2024-04-13 21:31:39,337] Trial 48 finished with value: 0.3472268066571282 and parameters: {'subsample': 0.8930727912416064, 'dropout_rate': 0.5352324499175369, 'n_estimators': 220, 'learning_rate': 0.0676976230591121}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24721651092560276
Fold 2 IBS: 0.2320533846625717
Fold 3 IBS: 0.22894606125965944
Fold 4 IBS: 0.24205352983162173
Fold 5 IBS: 0.22936048535911288
[I 2024-04-13 21:31:39,743] Trial 49 finished with value: 0.23592599440771372 and parameters: {'subsample': 0.29019384436727425, 'dropout_rate': 0.6839238696788629, 'n_estimators': 2, 'learning_rate': 0.002306950599999049}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24408782434634738
Fold 2 IBS: 0.23979898299871286
Fold 3 IBS: 0.21874098171709516
Fold 4 IBS: 0.2505654125994441
Fold 5 IBS: 0.2210094143748787
[I 2024-04-13 21:31:41,341] Trial 50 finished with value: 0.23484052320729565 and parameters: {'subsample': 0.7832440825986409, 'dropout_rate': 0.7536913177758878, 'n_estimators': 100, 'learning_rate': 0.011454052767269103}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24517105623494087
Fold 2 IBS: 0.23498060791195838
Fold 3 IBS: 0.22296570832369186
Fold 4 IBS: 0.2391765504942904
Fold 5 IBS: 0.2254861842706204
[I 2024-04-13 21:31:42,334] Trial 51 finished with value: 0.23355602144710036 and parameters: {'subsample': 0.9948301170331095, 'dropout_rate': 0.9350816882371296, 'n_estimators': 64, 'learning_rate': 0.00805448905542702}. Best is trial 23 with value: 0.2327439633365859.
Fold 1 IBS: 0.24411272803384046
Fold 2 IBS: 0.2401727143861656
Fold 3 IBS: 0.2190271972789742
Fold 4 IBS: 0.23705206039179413
Fold 5 IBS: 0.22152423203607274
[I 2024-04-13 21:31:43,482] Trial 52 finished with value: 0.2323777864253694 and parameters: {'subsample': 0.9727421743845424, 'dropout_rate': 0.9487211527541741, 'n_estimators': 65, 'learning_rate': 0.016699203566727223}. Best is trial 52 with value: 0.2323777864253694.
Fold 1 IBS: 0.24500057121409152
Fold 2 IBS: 0.25218258298981383
Fold 3 IBS: 0.2196146289111288
Fold 4 IBS: 0.2356302477600731
Fold 5 IBS: 0.21697025526217073
[I 2024-04-13 21:31:45,155] Trial 53 finished with value: 0.2338796572274556 and parameters: {'subsample': 0.9652228328687099, 'dropout_rate': 0.9433356152175235, 'n_estimators': 90, 'learning_rate': 0.022221272203454483}. Best is trial 52 with value: 0.2323777864253694.
Fold 1 IBS: 0.24414949396583488
Fold 2 IBS: 0.23954060286316967
Fold 3 IBS: 0.21929854260182383
Fold 4 IBS: 0.24143235093113657
Fold 5 IBS: 0.22190102021206384
[I 2024-04-13 21:31:45,998] Trial 54 finished with value: 0.23326440211480576 and parameters: {'subsample': 0.9004286575229025, 'dropout_rate': 0.7963922669955619, 'n_estimators': 53, 'learning_rate': 0.019394663269743963}. Best is trial 52 with value: 0.2323777864253694.
Fold 1 IBS: 0.24569341959796828
Fold 2 IBS: 0.23390577814792382
Fold 3 IBS: 0.22468834259790216
Fold 4 IBS: 0.2418616173594227
Fold 5 IBS: 0.22668881102353627
[I 2024-04-13 21:31:46,540] Trial 55 finished with value: 0.23456759374535063 and parameters: {'subsample': 0.884575085244196, 'dropout_rate': 0.796671165590165, 'n_estimators': 22, 'learning_rate': 0.016111712169646346}. Best is trial 52 with value: 0.2323777864253694.
Fold 1 IBS: 0.24957066245733353
Fold 2 IBS: 0.2693111265048573
Fold 3 IBS: 0.22901350935953907
Fold 4 IBS: 0.2616318164072917
Fold 5 IBS: 0.21483171275685
[I 2024-04-13 21:31:48,179] Trial 56 finished with value: 0.24487176549717432 and parameters: {'subsample': 0.8367121385888528, 'dropout_rate': 0.7150070208775917, 'n_estimators': 110, 'learning_rate': 0.028352290264468318}. Best is trial 52 with value: 0.2323777864253694.
Fold 1 IBS: 0.24933381871591292
Fold 2 IBS: 0.26639850346923943
Fold 3 IBS: 0.22428224021574422

Fold 4 IBS: 0.2912921867679323
Fold 5 IBS: 0.19946843946475085
[I 2024-04-13 21:31:53,989] Trial 57 finished with value: 0.24615503772671596 and parameters: {'subsample': 0.13165605060453595, 'dropout_rate': 0.6215636969984726, 'n_estimators': 282, 'learning_rate': 0.020570994628935912}. Best is trial 52 with value: 0.2323777864253694.
Fold 1 IBS: 0.24587951428848268
Fold 2 IBS: 0.25635516225894356
Fold 3 IBS: 0.22117244118528198
Fold 4 IBS: 0.23565881966280566
Fold 5 IBS: 0.21621898647169846
[I 2024-04-13 21:31:55,979] Trial 58 finished with value: 0.2350569847734425 and parameters: {'subsample': 0.9631039053260466, 'dropout_rate': 0.5584119442683281, 'n_estimators': 130, 'learning_rate': 0.017546400044930882}. Best is trial 52 with value: 0.2323777864253694.
Fold 1 IBS: 0.2886758087821922
Fold 2 IBS: 0.34737050785244566
Fold 3 IBS: 0.27633386064263016
Fold 4 IBS: 0.2841361207078176
Fold 5 IBS: 0.2690903893143384
[I 2024-04-13 21:31:58,234] Trial 59 finished with value: 0.2931213374598848 and parameters: {'subsample': 0.9082910857086345, 'dropout_rate': 0.7419178190141217, 'n_estimators': 155, 'learning_rate': 0.047267601674035827}. Best is trial 52 with value: 0.2323777864253694.
Fold 1 IBS: 0.24547205692111124
Fold 2 IBS: 0.2343530084887515
Fold 3 IBS: 0.22381767063049776
Fold 4 IBS: 0.24122891437957322
Fold 5 IBS: 0.22612290102008842
[I 2024-04-13 21:31:59,498] Trial 60 finished with value: 0.23419891028800444 and parameters: {'subsample': 0.8798803169310448, 'dropout_rate': 0.5930577061684893, 'n_estimators': 85, 'learning_rate': 0.005009079996413106}. Best is trial 52 with value: 0.2323777864253694.
Fold 1 IBS: 0.2449662323425241
Fold 2 IBS: 0.23546670961314473
Fold 3 IBS: 0.2223187510604186
Fold 4 IBS: 0.2415997798372476
Fold 5 IBS: 0.22498021689170059
[I 2024-04-13 21:32:00,287] Trial 61 finished with value: 0.23386633794900713 and parameters: {'subsample': 0.9179461970855084, 'dropout_rate': 0.9982379929650159, 'n_estimators': 52, 'learning_rate': 0.011231109088700793}. Best is trial 52 with value: 0.2323777864253694.
Fold 1 IBS: 0.2441428845656568
Fold 2 IBS: 0.23969989111150874
Fold 3 IBS: 0.2192524126671902
Fold 4 IBS: 0.23787186571989713
Fold 5 IBS: 0.22182662351385726
[I 2024-04-13 21:32:01,142] Trial 62 finished with value: 0.232558735515622 and parameters: {'subsample': 0.9757814666568271, 'dropout_rate': 0.8958147587986927, 'n_estimators': 59, 'learning_rate': 0.0177390751443948}. Best is trial 52 with value: 0.2323777864253694.
Fold 1 IBS: 0.24529792008167065
Fold 2 IBS: 0.2347782782577701
Fold 3 IBS: 0.22339377121870382
Fold 4 IBS: 0.2393762606058351
Fold 5 IBS: 0.22570548449249017
[I 2024-04-13 21:32:01,679] Trial 63 finished with value: 0.23371034293129397 and parameters: {'subsample': 0.9640947895186319, 'dropout_rate': 0.8952525394080862, 'n_estimators': 20, 'learning_rate': 0.024003249638047962}. Best is trial 52 with value: 0.2323777864253694.
Fold 1 IBS: 0.24403893167293322
Fold 2 IBS: 0.2419502930728785
Fold 3 IBS: 0.21854579255339177
Fold 4 IBS: 0.23725191460096468
Fold 5 IBS: 0.2205738039105782
[I 2024-04-13 21:32:02,787] Trial 64 finished with value: 0.23247214716214928 and parameters: {'subsample': 0.9765609172831073, 'dropout_rate': 0.8192996951049057, 'n_estimators': 78, 'learning_rate': 0.016026997408142868}. Best is trial 52 with value: 0.2323777864253694.
Fold 1 IBS: 0.24405346596323454
Fold 2 IBS: 0.24121700586779285
Fold 3 IBS: 0.21872604026266326
Fold 4 IBS: 0.23676366818993647
Fold 5 IBS: 0.22087378490129167
[I 2024-04-13 21:32:03,906] Trial 65 finished with value: 0.23232679303698375 and parameters: {'subsample': 0.9712842797437069, 'dropout_rate': 0.8779048908531875, 'n_estimators': 74, 'learning_rate': 0.016037625960587432}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.2720074694421556
Fold 2 IBS: 0.31860632030813935
Fold 3 IBS: 0.2584206892574882
Fold 4 IBS: 0.2502001146138086
Fold 5 IBS: 0.23778152675198266
[I 2024-04-13 21:32:06,560] Trial 66 finished with value: 0.2674032240747149 and parameters: {'subsample': 0.9741092483513416, 'dropout_rate': 0.871921667461881, 'n_estimators': 184, 'learning_rate': 0.030654885831415846}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24405036119125137
Fold 2 IBS: 0.2413393589567707
Fold 3 IBS: 0.21868339432641862
Fold 4 IBS: 0.23676155111125644
Fold 5 IBS: 0.22089376645397157
[I 2024-04-13 21:32:07,654] Trial 67 finished with value: 0.2323456864079337 and parameters: {'subsample': 0.9900600584805936, 'dropout_rate': 0.8428878303707972, 'n_estimators': 76, 'learning_rate': 0.015709709365668442}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24796070283897434
Fold 2 IBS: 0.2644495140365613
Fold 3 IBS: 0.22487673790685966
Fold 4 IBS: 0.23614310067440503
Fold 5 IBS: 0.21548409937578944
[I 2024-04-13 21:32:08,810] Trial 68 finished with value: 0.23778283096651798 and parameters: {'subsample': 0.9983399167394857, 'dropout_rate': 0.8226139690349044, 'n_estimators': 77, 'learning_rate': 0.03557646010123462}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.2446238849246169
Fold 2 IBS: 0.2498346337741095
Fold 3 IBS: 0.21894074984774045
Fold 4 IBS: 0.23571411021421665
Fold 5 IBS: 0.21761131734340006
[I 2024-04-13 21:32:10,207] Trial 69 finished with value: 0.23334493922081673 and parameters: {'subsample': 0.9705169524509666, 'dropout_rate': 0.9490666653031774, 'n_estimators': 103, 'learning_rate': 0.017826564012360328}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.3162899479078266
Fold 2 IBS: 0.3991616758426275
Fold 3 IBS: 0.30204408382820835
Fold 4 IBS: 0.3115557818110236
Fold 5 IBS: 0.3243062248697771
[I 2024-04-13 21:32:19,618] Trial 70 finished with value: 0.33067154285189265 and parameters: {'subsample': 0.864290364463847, 'dropout_rate': 0.8762622348644886, 'n_estimators': 408, 'learning_rate': 0.027097599520038058}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24472107151117672
Fold 2 IBS: 0.23569287105975642
Fold 3 IBS: 0.21999035961976798
Fold 4 IBS: 0.2478457070640971
Fold 5 IBS: 0.2227873676826924
[I 2024-04-13 21:32:20,374] Trial 71 finished with value: 0.23420747538749814 and parameters: {'subsample': 0.5300843058226148, 'dropout_rate': 0.8411569003127316, 'n_estimators': 38, 'learning_rate': 0.023066474568749395}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24406883140831578
Fold 2 IBS: 0.2407355264119928
Fold 3 IBS: 0.21882196530144868
Fold 4 IBS: 0.23829705418463415
Fold 5 IBS: 0.22108284467969533
[I 2024-04-13 21:32:21,474] Trial 72 finished with value: 0.23260124439721735 and parameters: {'subsample': 0.9368782581501145, 'dropout_rate': 0.7780349289511279, 'n_estimators': 74, 'learning_rate': 0.015489066919755372}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24527179484044656
Fold 2 IBS: 0.2347223116473272
Fold 3 IBS: 0.223314241920934
Fold 4 IBS: 0.2396432556882703
Fold 5 IBS: 0.22567962327015648
[I 2024-04-13 21:32:22,471] Trial 73 finished with value: 0.23372624547342688 and parameters: {'subsample': 0.9445614435162396, 'dropout_rate': 0.7854160312923217, 'n_estimators': 74, 'learning_rate': 0.0065380799469092685}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24421285887835223
Fold 2 IBS: 0.24621969265969645
Fold 3 IBS: 0.21834527541198623
Fold 4 IBS: 0.2359792269184398
Fold 5 IBS: 0.21870348170129456
[I 2024-04-13 21:32:23,802] Trial 74 finished with value: 0.23269210711395383 and parameters: {'subsample': 0.9688365649195759, 'dropout_rate': 0.9724124462303555, 'n_estimators': 91, 'learning_rate': 0.017418476122667913}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24572310068474382
Fold 2 IBS: 0.2557909732574325
Fold 3 IBS: 0.22087870646877084
Fold 4 IBS: 0.235639315178226
Fold 5 IBS: 0.21632744619843966
[I 2024-04-13 21:32:25,754] Trial 75 finished with value: 0.23487190835752253 and parameters: {'subsample': 0.9725591143129679, 'dropout_rate': 0.956470219204862, 'n_estimators': 141, 'learning_rate': 0.015784754693355125}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24474168570495028
Fold 2 IBS: 0.25044393575617147
Fold 3 IBS: 0.21917746729750048

Fold 4 IBS: 0.23836292489739097
Fold 5 IBS: 0.21734062586140884
[I 2024-04-13 21:32:27,045] Trial 76 finished with value: 0.23401332790348445 and parameters: {'subsample': 0.9303178972102747, 'dropout_rate': 0.9996437200724101, 'n_estimators': 91, 'learning_rate': 0.020800331912285384}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.25110523525273676
Fold 2 IBS: 0.2739338359344842
Fold 3 IBS: 0.23026776767311077
Fold 4 IBS: 0.2373454159197639
Fold 5 IBS: 0.21574863218030504
[I 2024-04-13 21:32:34,894] Trial 77 finished with value: 0.24168017739208017 and parameters: {'subsample': 0.9980345772994771, 'dropout_rate': 0.9095068007760355, 'n_estimators': 337, 'learning_rate': 0.009675483731153595}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24405377784762752
Fold 2 IBS: 0.24310270490752364
Fold 3 IBS: 0.21832495383057882
Fold 4 IBS: 0.24115697900725427
Fold 5 IBS: 0.2198396021449846
[I 2024-04-13 21:32:37,085] Trial 78 finished with value: 0.2332956035475938 and parameters: {'subsample': 0.875791542586785, 'dropout_rate': 0.97187020738614, 'n_estimators': 109, 'learning_rate': 0.01246694499828066}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24623762915529918
Fold 2 IBS: 0.23309934862983722
Fold 3 IBS: 0.22611211249497065
Fold 4 IBS: 0.24276276117023182
Fold 5 IBS: 0.22766807401749248
[I 2024-04-13 21:32:37,845] Trial 79 finished with value: 0.23517598509356627 and parameters: {'subsample': 0.835666585281967, 'dropout_rate': 0.8803384724169618, 'n_estimators': 13, 'learning_rate': 0.01729067188312782}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24595047922777644
Fold 2 IBS: 0.25063971707651395
Fold 3 IBS: 0.2251918591446772
Fold 4 IBS: 0.2752269216925909
Fold 5 IBS: 0.21158022145067212
[I 2024-04-13 21:32:40,534] Trial 80 finished with value: 0.24171783971844613 and parameters: {'subsample': 0.45334769335248726, 'dropout_rate': 0.9177849803256122, 'n_estimators': 125, 'learning_rate': 0.022453907941983174}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24422764298289618
Fold 2 IBS: 0.23876962056717796
Fold 3 IBS: 0.21961039444126818
Fold 4 IBS: 0.23814717341023695
Fold 5 IBS: 0.2223183840018942
[I 2024-04-13 21:32:41,664] Trial 81 finished with value: 0.2326146430806947 and parameters: {'subsample': 0.9288631574018964, 'dropout_rate': 0.8157143334867067, 'n_estimators': 65, 'learning_rate': 0.014743442521168248}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.2441631921693662
Fold 2 IBS: 0.23934500474737683
Fold 3 IBS: 0.21932739410219912
Fold 4 IBS: 0.2380153688031621
Fold 5 IBS: 0.22193668023588
[I 2024-04-13 21:32:42,965] Trial 82 finished with value: 0.23255752801159685 and parameters: {'subsample': 0.9334704584722258, 'dropout_rate': 0.8534921023459305, 'n_estimators': 64, 'learning_rate': 0.015879854564248813}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24469568971039155
Fold 2 IBS: 0.2364231384551449
Fold 3 IBS: 0.22143345825210453
Fold 4 IBS: 0.23901669319800206
Fold 5 IBS: 0.22414278332997714
[I 2024-04-13 21:32:43,945] Trial 83 finished with value: 0.23314235258912402 and parameters: {'subsample': 0.9760136117100787, 'dropout_rate': 0.8116664824817401, 'n_estimators': 43, 'learning_rate': 0.016292743840617636}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24551183380541172
Fold 2 IBS: 0.25455912286881704
Fold 3 IBS: 0.2205092271919645
Fold 4 IBS: 0.23797471727183792
Fold 5 IBS: 0.21645114602056117
[I 2024-04-13 21:32:45,789] Trial 84 finished with value: 0.23500120943171848 and parameters: {'subsample': 0.9361099785187367, 'dropout_rate': 0.8772572115183148, 'n_estimators': 87, 'learning_rate': 0.024843293689492424}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24407469990170214
Fold 2 IBS: 0.2407489088104109
Fold 3 IBS: 0.21886093472541618
Fold 4 IBS: 0.23692097261871867
Fold 5 IBS: 0.2212070471177304
[I 2024-04-13 21:32:47,104] Trial 85 finished with value: 0.23236251263479563 and parameters: {'subsample': 0.9583252050473876, 'dropout_rate': 0.829339974129229, 'n_estimators': 60, 'learning_rate': 0.019017274419529433}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24495580593801616
Fold 2 IBS: 0.23553261798692235
Fold 3 IBS: 0.22228629247525103
Fold 4 IBS: 0.24077753621322268
Fold 5 IBS: 0.22490805047605802
[I 2024-04-13 21:32:48,237] Trial 86 finished with value: 0.23369206061789405 and parameters: {'subsample': 0.8967274136462003, 'dropout_rate': 0.8469442486040392, 'n_estimators': 63, 'learning_rate': 0.009313476604200871}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24676837071245403
Fold 2 IBS: 0.2604456934539031
Fold 3 IBS: 0.22276199548850453
Fold 4 IBS: 0.23576473427644595
Fold 5 IBS: 0.21576097067431435
[I 2024-04-13 21:32:48,879] Trial 87 finished with value: 0.23630035292112442 and parameters: {'subsample': 0.9521575512376059, 'dropout_rate': 0.773424170359988, 'n_estimators': 32, 'learning_rate': 0.07823986277139501}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24591594913391762
Fold 2 IBS: 0.2335368034030972
Fold 3 IBS: 0.22524392521145714
Fold 4 IBS: 0.24043382723781304
Fold 5 IBS: 0.22705343125392272
[I 2024-04-13 21:32:50,656] Trial 88 finished with value: 0.23443678724804157 and parameters: {'subsample': 0.924130590490637, 'dropout_rate': 0.8321178679311125, 'n_estimators': 79, 'learning_rate': 0.0038097509248209236}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24584128965119126
Fold 2 IBS: 0.23310428543308628
Fold 3 IBS: 0.225182911821644
Fold 4 IBS: 0.24151645263450894
Fold 5 IBS: 0.22697905589043016
[I 2024-04-13 21:32:51,242] Trial 89 finished with value: 0.23452479908617213 and parameters: {'subsample': 0.7238355245222015, 'dropout_rate': 0.8086040219512625, 'n_estimators': 10, 'learning_rate': 0.03018836844016616}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24403810990955524
Fold 2 IBS: 0.24283120081174278
Fold 3 IBS: 0.2183670549439897
Fold 4 IBS: 0.24062883557874087
Fold 5 IBS: 0.22007505998790025
[I 2024-04-13 21:32:52,313] Trial 90 finished with value: 0.23318805224638575 and parameters: {'subsample': 0.8490874925270363, 'dropout_rate': 0.8574605076285688, 'n_estimators': 67, 'learning_rate': 0.019672878031945003}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24403675410962417
Fold 2 IBS: 0.2425010800822108
Fold 3 IBS: 0.21844168837277175
Fold 4 IBS: 0.2365374739645747
Fold 5 IBS: 0.22030347671321696
[I 2024-04-13 21:32:53,718] Trial 91 finished with value: 0.23236409464847968 and parameters: {'subsample': 0.970104954829864, 'dropout_rate': 0.9251910245265789, 'n_estimators': 101, 'learning_rate': 0.012753823306042036}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24481928190349977
Fold 2 IBS: 0.23597416780037953
Fold 3 IBS: 0.22184653171164379
Fold 4 IBS: 0.23861517821299283
Fold 5 IBS: 0.22452815992482997
[I 2024-04-13 21:32:54,523] Trial 92 finished with value: 0.23315666391066917 and parameters: {'subsample': 0.9826735912394103, 'dropout_rate': 0.8880937438316231, 'n_estimators': 49, 'learning_rate': 0.013180865144223458}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24407869762631096
Fold 2 IBS: 0.24066247343267877
Fold 3 IBS: 0.21885363261711582
Fold 4 IBS: 0.23834333289353968
Fold 5 IBS: 0.22125368529061515
[I 2024-04-13 21:32:55,783] Trial 93 finished with value: 0.23263836437205207 and parameters: {'subsample': 0.9456594436186455, 'dropout_rate': 0.9271317012405188, 'n_estimators': 97, 'learning_rate': 0.011642527621898874}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24440600174803087
Fold 2 IBS: 0.23767285584127149
Fold 3 IBS: 0.2203651288879805
Fold 4 IBS: 0.23785429352726145
Fold 5 IBS: 0.22316815561636433
[I 2024-04-13 21:32:56,724] Trial 94 finished with value: 0.23269328712418172 and parameters: {'subsample': 0.9822082446075138, 'dropout_rate': 0.8395402830218756, 'n_estimators': 58, 'learning_rate': 0.014504876875556344}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24628930153277576
Fold 2 IBS: 0.23300882516417812
Fold 3 IBS: 0.22639132619773789
Fold 4 IBS: 0.2418558673842897

Fold 5 IBS: 0.22780690516678317
[I 2024-04-13 21:32:57,352] Trial 95 finished with value: 0.23507044508915292 and parameters: {'subsample': 0.8966428006054885, 'dropout_rate': 0.7704366422806366, 'n_estimators': 30, 'learning_rate': 0.006842064022804307}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.2750994816533384
Fold 2 IBS: 0.3245226002709321
Fold 3 IBS: 0.2624205253911892
Fold 4 IBS: 0.253501837617046
Fold 5 IBS: 0.24486023772313253
[I 2024-04-13 21:32:58,897] Trial 96 finished with value: 0.2720809365311277 and parameters: {'subsample': 0.9529075957415207, 'dropout_rate': 0.9154736896330417, 'n_estimators': 110, 'learning_rate': 0.054487916689644846}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.2442539674574584
Fold 2 IBS: 0.24666942629822483
Fold 3 IBS: 0.21837620002874783
Fold 4 IBS: 0.23594320426076265
Fold 5 IBS: 0.21864610721665617
[I 2024-04-13 21:32:59,987] Trial 97 finished with value: 0.23277778105237 and parameters: {'subsample': 0.9998374677574539, 'dropout_rate': 0.8593754993866138, 'n_estimators': 78, 'learning_rate': 0.02066235138394905}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24478665382193568
Fold 2 IBS: 0.23606616607219635
Fold 3 IBS: 0.22167559417887384
Fold 4 IBS: 0.23864650506461108
Fold 5 IBS: 0.22439073520548142
[I 2024-04-13 21:33:01,026] Trial 98 finished with value: 0.23311313086861968 and parameters: {'subsample': 0.9271201048489, 'dropout_rate': 0.806723597254699, 'n_estimators': 67, 'learning_rate': 0.009838967622738948}. Best is trial 65 with value: 0.23232679303698375.
Fold 1 IBS: 0.24439573343122253
Fold 2 IBS: 0.23782791191658337
Fold 3 IBS: 0.22025567003518223
Fold 4 IBS: 0.24162942775947618
Fold 5 IBS: 0.22303895968008755
[I 2024-04-13 21:33:01,796] Trial 99 finished with value: 0.23342954056451037 and parameters: {'subsample': 0.8722973433191177, 'dropout_rate': 0.7320589837036046, 'n_estimators': 45, 'learning_rate': 0.018980719247224092}. Best is trial 65 with value: 0.23232679303698375.


* Best trial for IBS:
 FrozenTrial(number=65, state=TrialState.COMPLETE, values=[0.23232679303698375], datetime_start=datetime.datetime(2024, 4, 13, 21, 32, 2, 792088), datetime_complete=datetime.datetime(2024, 4, 13, 21, 32, 3, 905996), params={'subsample': 0.9712842797437069, 'dropout_rate': 0.8779048908531875, 'n_estimators': 74, 'learning_rate': 0.016037625960587432}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=65, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.9712842797437069, 'dropout_rate': 0.8779048908531875, 'n_estimators': 74, 'learning_rate': 0.016037625960587432}


* Best Score for IBS:
 0.23232679303698375

In [94]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [95]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.618
train_ibs:  0.232

#### Test

In [96]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [97]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.10707700162921632,
                                              learning_rate=0.09635955935176935,
                                              n_estimators=311,
                                              random_state=123,
                                              subsample=0.11211713718471546)

C-index score: 0.562

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.8779048908531875,
                                              learning_rate=0.016037625960587432,
                                              n_estimators=74, random_state=123,
                                              subsample=0.9712842797437069)

IBS: 0.248

In [98]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

# Results

In [99]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.790   1.0
ExtraSurvivalTrees               0.748   2.0
GradientBoosting                 0.648   3.0
CoxPH                            0.638   4.5
CoxElastic                       0.638   4.5
CoxLasso                         0.636   6.0
ComponentwiseGradientBoosting    0.618   7.0
CoxRidge                         0.592   8.0

In [100]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.218   1.5
ExtraSurvivalTrees             0.218   1.5
CoxElastic                     0.226   3.0
GradientBoosting               0.229   4.0
CoxPH                          0.231   5.5
CoxLasso                       0.231   5.5
ComponentwiseGradientBoosting  0.232   7.0
CoxRidge                       0.236   8.0

In [101]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
GradientBoosting                 0.639   1.0
Randomsurvivalforest             0.603   2.0
ExtraSurvivalTrees               0.585   3.0
ComponentwiseGradientBoosting    0.562   4.0
CoxPH                            0.532   6.5
CoxRidge                         0.532   6.5
CoxLasso                         0.532   6.5
CoxElastic                       0.532   6.5

In [102]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.213   1.0
Randomsurvivalforest           0.215   2.0
GradientBoosting               0.221   3.0
CoxRidge                       0.229   4.0
CoxElastic                     0.234   5.0
ComponentwiseGradientBoosting  0.248   6.0
CoxLasso                       0.273   7.0
CoxPH                          0.276   8.0

In [103]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/dfs/standard/rent/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_dfs_standard_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [104]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-13