In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
from sklearn.preprocessing import RobustScaler
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D1 
clinical_train.isnull().sum().sum()

0

In [6]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

## Test dataset: MAASTRO

In [7]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [8]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [9]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [10]:
# Merge MAASTRO_D1 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG,DFS,DFS_event
0,1,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342,8.83,1.0
3,4,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979,19.73,1.0
4,6,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782,13.27,1.0
95,111,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212,72.07,0.0

In [11]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [16]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, DFS, DFS_event]
Index: []

In [17]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

In [18]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [19]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 14)
y_train:  (139,)

In [20]:
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [21]:
# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 16)

# Feature Selection: RENT

In [22]:
# Choose features from the result of RENT 
selected_features = ["hpv_related",
"pack_years",
"uicc8_III-IV",
"oropharynx",
"cavum_oris",
"TLG"]

In [23]:
X_rent = X.loc[:, selected_features]
X_new = X_rent.copy()

In [24]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, selected_features]

# Standardization

In [25]:
# Copy the original X for later 
original_X = X.copy()

In [26]:
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Standardize X_new, the new data with the selected features only 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = RobustScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [32]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[X_new.columns]

In [33]:
X_new

     hpv_related  pack_years  uicc8_III-IV  oropharynx  cavum_oris         TLG
0            0.0    0.000000           0.0           1           0   86.228420
1            0.0   27.404795           0.0           0           0    7.040100
2            0.0   41.019178           1.0           0           1   83.569669
3            0.0   37.500000           0.0           0           0    5.567091
4            0.0   53.000000           0.0           0           0   16.150550
..           ...         ...           ...         ...         ...         ...
134          1.0    0.000000           0.0           1           0   26.280140
135          1.0    0.000000           1.0           1           0  101.754834
136          1.0   39.498630           0.0           1           0   66.273201
137          1.0   71.527397           1.0           1           0   71.832443
138          1.0    2.250000           1.0           1           0   78.647696

[139 rows x 6 columns]

In [34]:
X_new_std

     hpv_related  pack_years  uicc8_III-IV  oropharynx  cavum_oris       TLG
0            0.0   -0.747766           0.0           1           0  0.231096
1            0.0    0.159774           0.0           0           0 -0.387041
2            0.0    0.610629           1.0           0           1  0.210342
3            0.0    0.494088           0.0           0           0 -0.398539
4            0.0    1.007387           0.0           0           0 -0.315926
..           ...         ...           ...         ...         ...       ...
134          1.0   -0.747766           0.0           1           0 -0.236855
135          1.0   -0.747766           1.0           1           0  0.352293
136          1.0    0.560275           0.0           1           0  0.075327
137          1.0    1.620942           1.0           1           0  0.118722
138          1.0   -0.673255           1.0           1           0  0.171921

[139 rows x 6 columns]

In [35]:
MAASTRO_new

    hpv_related  pack_years  uicc8_III-IV  oropharynx  cavum_oris         TLG
0             1           0             0           1           0  263.611623
1             0          20             1           1           0   36.980700
2             0           6             1           1           0   74.636342
3             0          45             1           0           0   46.791979
4             1          59             0           1           0  107.637514
..          ...         ...           ...         ...         ...         ...
94            0          55             1           0           0  144.490782
95            0         174             1           0           0   69.214868
96            1           0             1           1           0  102.594274
97            1           0             0           1           0  103.229492
98            0          40             1           0           0   28.553212

[99 rows x 6 columns]

In [36]:
MAASTRO_new_std

    hpv_related  pack_years  uicc8_III-IV  oropharynx  cavum_oris       TLG
0             1   -0.747766             0           1           0  1.615732
1             0   -0.085444             1           1           0 -0.153327
2             0   -0.549070             1           1           0  0.140609
3             0    0.742458             1           0           0 -0.076742
4             1    1.206084             0           1           0  0.398213
..          ...         ...           ...         ...         ...       ...
94            0    1.073619             1           0           0  0.685886
95            0    5.014436             1           0           0  0.098289
96            1   -0.747766             1           1           0  0.358846
97            1   -0.747766             0           1           0  0.363804
98            0    0.576878             1           0           0 -0.219112

[99 rows x 6 columns]

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [37]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:05:54,514] A new study created in memory with name: no-name-9d5c166a-8f66-4468-a513-b06ce9ad07dc

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-13 17:05:57,748] A new study created in memory with name: no-name-d35aed9f-d05e-40ae-ba12-700bc13b30b4

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:05:57,741] Trial 0 finished with value: 0.6380043211913705 and parameters: {}. Best is trial 0 with value: 0.6380043211913705.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6380043211913705], datetime_start=datetime.datetime(2024, 4, 13, 17, 5, 54, 597507), datetime_complete=datetime.datetime(2024, 4, 13, 17, 5, 57, 741269), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6380043211913705

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.23694732382610154
Fold 2 IBS: 0.2615158118717559
Fold 3 IBS: 0.17590965994359087
Fold 4 IBS: 0.28365588891632393
Fold 5 IBS: 0.19620686095559542
[I 2024-04-13 17:05:57,986] Trial 0 finished with value: 0.2308471091026735 and parameters: {}. Best is trial 0 with value: 0.2308471091026735.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2308471091026735], datetime_start=datetime.datetime(2024, 4, 13, 17, 5, 57, 785018), datetime_complete=datetime.datetime(2024, 4, 13, 17, 5, 57, 986232), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2308471091026735

In [38]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [39]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.638
train_ibs:  0.231

#### Test

In [40]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [41]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.532
IBS score: 0.276

In [42]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [43]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis

#### Train

In [44]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:05:58,153] A new study created in memory with name: no-name-d566a35a-304f-467c-a807-4242ecb30a95

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.4543726235741445
Fold 5 C-index: 0.6781115879828327
[I 2024-04-13 17:05:58,299] Trial 0 finished with value: 0.5826657539976539 and parameters: {}. Best is trial 0 with value: 0.5826657539976539.

[I 2024-04-13 17:05:58,310] A new study created in memory with name: no-name-5641e89e-761a-4b03-9f06-07d17940d160

* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5826657539976539], datetime_start=datetime.datetime(2024, 4, 13, 17, 5, 58, 186454), datetime_complete=datetime.datetime(2024, 4, 13, 17, 5, 58, 297694), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5826657539976539

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2472470947584011
Fold 2 IBS: 0.23203988427112568
Fold 3 IBS: 0.22898186356844594
Fold 4 IBS: 0.24197478455226282
Fold 5 IBS: 0.2293955853840956
[I 2024-04-13 17:05:58,494] Trial 0 finished with value: 0.23592784250686621 and parameters: {}. Best is trial 0 with value: 0.23592784250686621.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592784250686621], datetime_start=datetime.datetime(2024, 4, 13, 17, 5, 58, 360178), datetime_complete=datetime.datetime(2024, 4, 13, 17, 5, 58, 494313), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592784250686621

In [45]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [46]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.583
train_ibs:  0.236

#### Test

In [47]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [48]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.571

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [49]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [50]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:05:58,646] A new study created in memory with name: no-name-e8c0c485-a6c1-42ba-8e5d-159206d2be69

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923

[I 2024-04-13 17:05:58,929] A new study created in memory with name: no-name-b92377b2-fba8-432e-beea-a7f31a746f84

Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:05:58,923] Trial 0 finished with value: 0.6369089405587356 and parameters: {}. Best is trial 0 with value: 0.6369089405587356.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6369089405587356], datetime_start=datetime.datetime(2024, 4, 13, 17, 5, 58, 679566), datetime_complete=datetime.datetime(2024, 4, 13, 17, 5, 58, 923501), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6369089405587356

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.23861993031733617
Fold 2 IBS: 0.2596147966570129
Fold 3 IBS: 0.1774757774558778
Fold 4 IBS: 0.28226222126776673
Fold 5 IBS: 0.1964081480880089
[I 2024-04-13 17:05:59,199] Trial 0 finished with value: 0.23087617475720051 and parameters: {}. Best is trial 0 with value: 0.23087617475720051.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23087617475720051], datetime_start=datetime.datetime(2024, 4, 13, 17, 5, 58, 952466), datetime_complete=datetime.datetime(2024, 4, 13, 17, 5, 59, 199691), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23087617475720051

In [51]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [52]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.637
train_ibs:  0.231

#### Test

In [53]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [54]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.532

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.273

In [55]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [56]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:05:59,451] A new study created in memory with name: no-name-bc632e41-7f1c-440a-924a-6acb1e5c9a0f

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:05:59,732] Trial 0 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6369089405587356.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:05:59,930] Trial 1 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.6369089405587356.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:00,161] Trial 2 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.6369089405587356.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:00,373] Trial 3 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.6369089405587356.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:00,663] Trial 4 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.6369089405587356.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:00,892] Trial 5 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:01,135] Trial 6 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:01,358] Trial 7 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:01,591] Trial 8 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:01,851] Trial 9 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:06:01,971] Trial 10 finished with value: 0.5759543887566835 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:02,200] Trial 11 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3734960813237434}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:06:02,304] Trial 12 finished with value: 0.574252261097109 and parameters: {'l1_ratio': 0.11356797167713778}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:02,517] Trial 13 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4449202644507797}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:02,710] Trial 14 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.2893683497253}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:02,914] Trial 15 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.5663511759427868}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:06:02,999] Trial 16 finished with value: 0.5815863290804947 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:03,219] Trial 17 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.8244104217192855}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:03,433] Trial 18 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3798015106074873}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:03,621] Trial 19 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.608409044915716}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:03,832] Trial 20 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4060784267370561}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:04,051] Trial 21 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.33492971197046034}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:04,248] Trial 22 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.20350763212036774}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:04,502] Trial 23 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.4714090815951266}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979

Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:04,731] Trial 24 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.39872004425394175}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:04,911] Trial 25 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.2047855727725989}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:05,170] Trial 26 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3312072877416866}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:05,413] Trial 27 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.526404719543659}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:05,603] Trial 28 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.6276972916515388}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:05,742] Trial 29 finished with value: 0.5691020465048344 and parameters: {'l1_ratio': 0.1391392813300431}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:05,941] Trial 30 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.26103069374174487}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:06,156] Trial 31 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.42504378566334805}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:06,342] Trial 32 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.458175553098962}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:06,598] Trial 33 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.37611460801158947}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:06,835] Trial 34 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3354076016582036}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:07,055] Trial 35 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.5362926770936469}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:07,282] Trial 36 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.2793275313152833}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:07,529] Trial 37 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.8013809955909406}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:07,802] Trial 38 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4833931220556825}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:08,025] Trial 39 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.6150170777727786}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:08,288] Trial 40 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4519744885109723}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:08,528] Trial 41 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.35570753305688546}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:08,785] Trial 42 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3866860702944602}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:08,981] Trial 43 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.25330979530211034}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:09,193] Trial 44 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4334045752302572}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:09,418] Trial 45 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.30461389083829005}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:09,687] Trial 46 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.5222973322437542}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:09,893] Trial 47 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.17743643188336441}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475

Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:10,114] Trial 48 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.5683872043393509}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:10,326] Trial 49 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.6743720426532283}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:10,551] Trial 50 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.49233256947923487}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:10,858] Trial 51 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.40521233982766125}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:11,102] Trial 52 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.41939160999186104}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:11,313] Trial 53 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.3064215066196125}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:11,573] Trial 54 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3585902136455097}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:11,872] Trial 55 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.972687298645671}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:12,163] Trial 56 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.5709986873152662}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:12,403] Trial 57 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.5053183801208554}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:12,630] Trial 58 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.24011959880513192}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:12,876] Trial 59 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3775753899220385}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:13,146] Trial 60 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4571044327800308}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:13,370] Trial 61 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.31190430820376913}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:13,634] Trial 62 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3391438175774809}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:13,863] Trial 63 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.40202103007252166}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:14,093] Trial 64 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4309023678849314}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:14,307] Trial 65 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.2738106687571851}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:14,524] Trial 66 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3633470048578769}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:14,766] Trial 67 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3320959862884111}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:14,951] Trial 68 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.2167985361803884}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:15,153] Trial 69 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4874480836918814}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:15,343] Trial 70 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4499432109023757}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:15,556] Trial 71 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.392594342752872}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677

Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:15,768] Trial 72 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4036955121782878}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:15,984] Trial 73 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.35331599586922247}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:16,173] Trial 74 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.4423593034025186}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:16,359] Trial 75 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.46722902122608273}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:16,524] Trial 76 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.3048842220290057}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:16,745] Trial 77 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.378113284567051}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:16,930] Trial 78 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.5473511103431568}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:17,126] Trial 79 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.5082412261383403}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:17,337] Trial 80 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.42045883836883247}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:17,539] Trial 81 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3267004951503469}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:17,712] Trial 82 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.26825674309252845}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:06:17,779] Trial 83 finished with value: 0.5815863290804947 and parameters: {'l1_ratio': 0.018556673131907286}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:17,947] Trial 84 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3451676578929508}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:18,147] Trial 85 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3864138607940886}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:18,344] Trial 86 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.2878834846486873}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:18,533] Trial 87 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.18400364854976434}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:18,746] Trial 88 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.42450783403663783}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:18,945] Trial 89 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.47031977844659345}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:19,105] Trial 90 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.24434035399868184}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:19,340] Trial 91 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.40882776150379113}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:19,524] Trial 92 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3627094976426938}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:19,702] Trial 93 finished with value: 0.593660845779121 and parameters: {'l1_ratio': 0.31587944725028283}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:19,893] Trial 94 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.43609321324891326}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:20,081] Trial 95 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.37297551414304464}. Best is trial 5 with value: 0.6377673096574481.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:20,284] Trial 96 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.5140349934377278}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:20,489] Trial 97 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.3347236296168386}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:06:20,686] Trial 98 finished with value: 0.6369089405587356 and parameters: {'l1_ratio': 0.4790489538168324}. Best is trial 5 with value: 0.6377673096574481.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.7468085106382979

[I 2024-04-13 17:06:20,900] A new study created in memory with name: no-name-0e6c42b7-9b88-48ff-9ecb-2b693f09301f

Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:20,893] Trial 99 finished with value: 0.6377673096574481 and parameters: {'l1_ratio': 0.40781957803925883}. Best is trial 5 with value: 0.6377673096574481.


* Best trial for C-index:
 FrozenTrial(number=5, state=TrialState.COMPLETE, values=[0.6377673096574481], datetime_start=datetime.datetime(2024, 4, 13, 17, 6, 0, 667789), datetime_complete=datetime.datetime(2024, 4, 13, 17, 6, 0, 892107), params={'l1_ratio': 0.4231641494784485}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=5, value=None)


* Best Score for C-index:
 0.6377673096574481

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23844252456919102
Fold 2 IBS: 0.25962309452516086
Fold 3 IBS: 0.17756122520087697
Fold 4 IBS: 0.28222100167646247
Fold 5 IBS: 0.1963024150227557
[I 2024-04-13 17:06:21,206] Trial 0 finished with value: 0.23083005219888938 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.23083005219888938.
Fold 1 IBS: 0.23821227441764645
Fold 2 IBS: 0.259507281104852
Fold 3 IBS: 0.17748611076455306
Fold 4 IBS: 0.2711903560807151
Fold 5 IBS: 0.1961309053731986
[I 2024-04-13 17:06:21,423] Trial 1 finished with value: 0.22850538554819305 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.22850538554819305.
Fold 1 IBS: 0.2382318642303404
Fold 2 IBS: 0.2595942968590173
Fold 3 IBS: 0.1774558487970546
Fold 4 IBS: 0.2676448102491281
Fold 5 IBS: 0.19609818316114597
[I 2024-04-13 17:06:21,720] Trial 2 finished with value: 0.2278050006593373 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.2278050006593373.
Fold 1 IBS: 0.23836726194186905
Fold 2 IBS: 0.25952691776857867
Fold 3 IBS: 0.1774613440550027
Fold 4 IBS: 0.28231798107354306
Fold 5 IBS: 0.1962466194095111
[I 2024-04-13 17:06:22,064] Trial 3 finished with value: 0.23078402484970093 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.2278050006593373.
Fold 1 IBS: 0.23846829923776533
Fold 2 IBS: 0.25950884120841095
Fold 3 IBS: 0.17753652718138332
Fold 4 IBS: 0.2822606243206659
Fold 5 IBS: 0.19632046913506096
[I 2024-04-13 17:06:22,357] Trial 4 finished with value: 0.23081895221665727 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.2278050006593373.
Fold 1 IBS: 0.2382712203068737
Fold 2 IBS: 0.25954944290359583
Fold 3 IBS: 0.17753437586138898
Fold 4 IBS: 0.28224618338233
Fold 5 IBS: 0.19619332147644933
[I 2024-04-13 17:06:22,633] Trial 5 finished with value: 0.23075890878612756 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.2278050006593373.
Fold 1 IBS: 0.23860683393446186
Fold 2 IBS: 0.2595763823486608
Fold 3 IBS: 0.1774876532130211
Fold 4 IBS: 0.28223948499782775
Fold 5 IBS: 0.19640502840223184
[I 2024-04-13 17:06:22,906] Trial 6 finished with value: 0.23086307657924068 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.2278050006593373.
Fold 1 IBS: 0.23842876735638377
Fold 2 IBS: 0.25959223971850093
Fold 3 IBS: 0.1775743337104375
Fold 4 IBS: 0.28219998626617787
Fold 5 IBS: 0.19629954453073484
[I 2024-04-13 17:06:23,169] Trial 7 finished with value: 0.230818974316447 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.2278050006593373.
Fold 1 IBS: 0.2383152804436864
Fold 2 IBS: 0.25961673135561625
Fold 3 IBS: 0.1774327287058191
Fold 4 IBS: 0.28227756071650156
Fold 5 IBS: 0.1962183549655283
[I 2024-04-13 17:06:23,441] Trial 8 finished with value: 0.23077213123743032 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.2278050006593373.
Fold 1 IBS: 0.23827374068331347
Fold 2 IBS: 0.25958045602947644
Fold 3 IBS: 0.17746041450600714
Fold 4 IBS: 0.2822773285705168
Fold 5 IBS: 0.19617953215302839
[I 2024-04-13 17:06:23,742] Trial 9 finished with value: 0.23075429438846845 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.2278050006593373.
Fold 1 IBS: 0.238497932425193
Fold 2 IBS: 0.23205310545924115
Fold 3 IBS: 0.22600351176254066
Fold 4 IBS: 0.2534591588961836
Fold 5 IBS: 0.22480693439044025
[I 2024-04-13 17:06:23,903] Trial 10 finished with value: 0.23496412858671972 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.2278050006593373.
Fold 1 IBS: 0.23823642222925773
Fold 2 IBS: 0.2596145515366124
Fold 3 IBS: 0.17750620614308296
Fold 4 IBS: 0.2648987669985288
Fold 5 IBS: 0.19608246564169338
[I 2024-04-13 17:06:24,158] Trial 11 finished with value: 0.22726768250983503 and parameters: {'l1_ratio': 0.19077404209371474}. Best is trial 11 with value: 0.22726768250983503.
Fold 1 IBS: 0.2450022716884374
Fold 2 IBS: 0.23199817170919654
Fold 3 IBS: 0.22709507103311052
Fold 4 IBS: 0.24864217027769334
Fold 5 IBS: 0.22637827752092735
[I 2024-04-13 17:06:24,474] Trial 12 finished with value: 0.23582319244587305 and parameters: {'l1_ratio': 0.04835900598617554}. Best is trial 11 with value: 0.22726768250983503.
Fold 1 IBS: 0.23824435488541246
Fold 2 IBS: 0.25963344223414525
Fold 3 IBS: 0.1773922190069929
Fold 4 IBS: 0.2665299382386444
Fold 5 IBS: 0.19609299724113632
[I 2024-04-13 17:06:24,823] Trial 13 finished with value: 0.22757859032126623 and parameters: {'l1_ratio': 0.2114475350243538}. Best is trial 11 with value: 0.22726768250983503.
Fold 1 IBS: 0.2382729401814425
Fold 2 IBS: 0.25955431261750034
Fold 3 IBS: 0.17740578338162147
Fold 4 IBS: 0.26437783523950537
Fold 5 IBS: 0.19607605429302224
[I 2024-04-13 17:06:25,107] Trial 14 finished with value: 0.2271373851426184 and parameters: {'l1_ratio': 0.18459727307810245}. Best is trial 14 with value: 0.2271373851426184.
Fold 1 IBS: 0.2468840387657447
Fold 2 IBS: 0.23202428482608436
Fold 3 IBS: 0.22869225424992673
Fold 4 IBS: 0.24284320873850548
Fold 5 IBS: 0.22890624773345328
[I 2024-04-13 17:06:25,225] Trial 15 finished with value: 0.23587000686274293 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 14 with value: 0.2271373851426184.
Fold 1 IBS: 0.23824624770496455
Fold 2 IBS: 0.25947615237978183
Fold 3 IBS: 0.17745096458648735
Fold 4 IBS: 0.26374079952132073
Fold 5 IBS: 0.19607713499634477
[I 2024-04-13 17:06:25,454] Trial 16 finished with value: 0.22699825983777985 and parameters: {'l1_ratio': 0.1772909900515591}. Best is trial 16 with value: 0.22699825983777985.
Fold 1 IBS: 0.23824205552379293
Fold 2 IBS: 0.25955422112953425
Fold 3 IBS: 0.17750973683473248
Fold 4 IBS: 0.2822749472138929
Fold 5 IBS: 0.19614796261579134
[I 2024-04-13 17:06:25,748] Trial 17 finished with value: 0.23074578466354878 and parameters: {'l1_ratio': 0.32162557863487895}. Best is trial 16 with value: 0.22699825983777985.
Fold 1 IBS: 0.23831324268104856
Fold 2 IBS: 0.23229932960314265
Fold 3 IBS: 0.22429350645857657
Fold 4 IBS: 0.2616813774418752
Fold 5 IBS: 0.1960636422488178
[I 2024-04-13 17:06:25,939] Trial 18 finished with value: 0.23053021968669216 and parameters: {'l1_ratio': 0.1552967775121356}. Best is trial 16 with value: 0.22699825983777985.
Fold 1 IBS: 0.23840195900086414
Fold 2 IBS: 0.2321758832796911
Fold 3 IBS: 0.22496869934628413
Fold 4 IBS: 0.2584219651568769
Fold 5 IBS: 0.1960566588456689
[I 2024-04-13 17:06:26,126] Trial 19 finished with value: 0.23000503312587703 and parameters: {'l1_ratio': 0.12448321089289768}. Best is trial 16 with value: 0.22699825983777985.
Fold 1 IBS: 0.23834384886963006
Fold 2 IBS: 0.25961494972909877
Fold 3 IBS: 0.1775597239261713
Fold 4 IBS: 0.28224874099615976
Fold 5 IBS: 0.19626180432586768
[I 2024-04-13 17:06:26,374] Trial 20 finished with value: 0.2308058135693855 and parameters: {'l1_ratio': 0.5769941772022575}. Best is trial 16 with value: 0.22699825983777985.
Fold 1 IBS: 0.23822595405338357
Fold 2 IBS: 0.2595185754968719
Fold 3 IBS: 0.17752862232907632
Fold 4 IBS: 0.27260164271450943
Fold 5 IBS: 0.19614455811238413
[I 2024-04-13 17:06:26,595] Trial 21 finished with value: 0.2288038705412451 and parameters: {'l1_ratio': 0.31575517411659926}. Best is trial 16 with value: 0.22699825983777985.
Fold 1 IBS: 0.23825983642553286
Fold 2 IBS: 0.25961724210775733
Fold 3 IBS: 0.17747151392642552
Fold 4 IBS: 0.263459568392019
Fold 5 IBS: 0.19607495710506892
[I 2024-04-13 17:06:26,814] Trial 22 finished with value: 0.22697662359136075 and parameters: {'l1_ratio': 0.17414680029158525}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.2384475128197843
Fold 2 IBS: 0.23212942577152093
Fold 3 IBS: 0.22529001794035314
Fold 4 IBS: 0.25685762716625815
Fold 5 IBS: 0.2237762272637492
[I 2024-04-13 17:06:26,954] Trial 23 finished with value: 0.23530016219233313 and parameters: {'l1_ratio': 0.1110094659290024}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.23824484313243527
Fold 2 IBS: 0.2595966349144657
Fold 3 IBS: 0.17753465197983173
Fold 4 IBS: 0.27051087555351244
Fold 5 IBS: 0.1961294671519935
[I 2024-04-13 17:06:27,186] Trial 24 finished with value: 0.22840329454644773 and parameters: {'l1_ratio': 0.27339398018534206}. Best is trial 22 with value: 0.22697662359136075.

Fold 1 IBS: 0.23823371554597988
Fold 2 IBS: 0.25949207642311956
Fold 3 IBS: 0.17750328264248502
Fold 4 IBS: 0.2822220524726955
Fold 5 IBS: 0.19617109028285518
[I 2024-04-13 17:06:27,420] Trial 25 finished with value: 0.23072444347342702 and parameters: {'l1_ratio': 0.3747482470228898}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.246428105921172
Fold 2 IBS: 0.23200855633752734
Fold 3 IBS: 0.22831992202640738
Fold 4 IBS: 0.2440469761668376
Fold 5 IBS: 0.22829284237284164
[I 2024-04-13 17:06:27,535] Trial 26 finished with value: 0.23581928056495718 and parameters: {'l1_ratio': 0.015423757551295547}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.23825230025286467
Fold 2 IBS: 0.2594664300976646
Fold 3 IBS: 0.17742775329061594
Fold 4 IBS: 0.26805651991682033
Fold 5 IBS: 0.1961032427289488
[I 2024-04-13 17:06:27,755] Trial 27 finished with value: 0.22786124925738288 and parameters: {'l1_ratio': 0.2329675843966648}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.23859518509761807
Fold 2 IBS: 0.25954371672068427
Fold 3 IBS: 0.1774977584098765
Fold 4 IBS: 0.28222015123801575
Fold 5 IBS: 0.19640577668264544
[I 2024-04-13 17:06:27,972] Trial 28 finished with value: 0.230852517629768 and parameters: {'l1_ratio': 0.964957522585106}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.23833422913986446
Fold 2 IBS: 0.2595045900965986
Fold 3 IBS: 0.2241154917471393
Fold 4 IBS: 0.26251806672887396
Fold 5 IBS: 0.19607278707650924
[I 2024-04-13 17:06:28,146] Trial 29 finished with value: 0.23610903295779714 and parameters: {'l1_ratio': 0.1639557579125528}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.23842021827697685
Fold 2 IBS: 0.23203632598895868
Fold 3 IBS: 0.2262247470762127
Fold 4 IBS: 0.2524385008718367
Fold 5 IBS: 0.22511602824943758
[I 2024-04-13 17:06:28,263] Trial 30 finished with value: 0.23484716409268452 and parameters: {'l1_ratio': 0.07608773441859154}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.23829254594775579
Fold 2 IBS: 0.23231098904711564
Fold 3 IBS: 0.2242379774101676
Fold 4 IBS: 0.2619427977600114
Fold 5 IBS: 0.19606569301351634
[I 2024-04-13 17:06:28,436] Trial 31 finished with value: 0.23057000063571334 and parameters: {'l1_ratio': 0.1579645274939656}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.23821481988556575
Fold 2 IBS: 0.2595406454571173
Fold 3 IBS: 0.17748682045847688
Fold 4 IBS: 0.2671987040061091
Fold 5 IBS: 0.19609973465277375
[I 2024-04-13 17:06:28,658] Trial 32 finished with value: 0.22770814489200858 and parameters: {'l1_ratio': 0.2205876936887934}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.23826415041141505
Fold 2 IBS: 0.2596377540734708
Fold 3 IBS: 0.17751010565150172
Fold 4 IBS: 0.2708525024036514
Fold 5 IBS: 0.19612659536183785
[I 2024-04-13 17:06:28,873] Trial 33 finished with value: 0.22847822158037534 and parameters: {'l1_ratio': 0.27973537656150815}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.23828647561793154
Fold 2 IBS: 0.2595336607636054
Fold 3 IBS: 0.17741772302595105
Fold 4 IBS: 0.26420695526459376
Fold 5 IBS: 0.19607405605520273
[I 2024-04-13 17:06:29,227] Trial 34 finished with value: 0.2271037741454569 and parameters: {'l1_ratio': 0.18261152713949952}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.23827506921009048
Fold 2 IBS: 0.25962954870799393
Fold 3 IBS: 0.1774691321928263
Fold 4 IBS: 0.2823250452486038
Fold 5 IBS: 0.19615210791323331
[I 2024-04-13 17:06:29,486] Trial 35 finished with value: 0.23077018065454954 and parameters: {'l1_ratio': 0.3349958381129322}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.2383078633848886
Fold 2 IBS: 0.25962867095967695
Fold 3 IBS: 0.17749524717716503
Fold 4 IBS: 0.28229742630130084
Fold 5 IBS: 0.19620105024352
[I 2024-04-13 17:06:29,729] Trial 36 finished with value: 0.23078605161331028 and parameters: {'l1_ratio': 0.44150721567365603}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.2382521129295466
Fold 2 IBS: 0.25962655688772257
Fold 3 IBS: 0.17747252423884446
Fold 4 IBS: 0.26936466510756707
Fold 5 IBS: 0.19611402391199706
[I 2024-04-13 17:06:29,945] Trial 37 finished with value: 0.22816597661513555 and parameters: {'l1_ratio': 0.25348320941945107}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.23855363009428113
Fold 2 IBS: 0.2594995177987273
Fold 3 IBS: 0.1775615950622548
Fold 4 IBS: 0.28221440370847894
Fold 5 IBS: 0.19636526717519617
[I 2024-04-13 17:06:30,182] Trial 38 finished with value: 0.2308388827677877 and parameters: {'l1_ratio': 0.8598478847078105}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.23837437399997374
Fold 2 IBS: 0.2595438706214699
Fold 3 IBS: 0.17745439717207845
Fold 4 IBS: 0.2822025381840995
Fold 5 IBS: 0.19624811860120833
[I 2024-04-13 17:06:30,400] Trial 39 finished with value: 0.23076465971576599 and parameters: {'l1_ratio': 0.5561256026976026}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.23837997521795073
Fold 2 IBS: 0.2321510482000411
Fold 3 IBS: 0.22513358891088667
Fold 4 IBS: 0.2576176883344008
Fold 5 IBS: 0.19604455822667993
[I 2024-04-13 17:06:30,567] Trial 40 finished with value: 0.22986537177799185 and parameters: {'l1_ratio': 0.1174661876257988}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.23823123174435373
Fold 2 IBS: 0.25960378106118936
Fold 3 IBS: 0.17741015716160197
Fold 4 IBS: 0.26626332963526256
Fold 5 IBS: 0.19608976063702394
[I 2024-04-13 17:06:30,766] Trial 41 finished with value: 0.22751965204788632 and parameters: {'l1_ratio': 0.20791826923443552}. Best is trial 22 with value: 0.22697662359136075.
Fold 1 IBS: 0.2382606405283925
Fold 2 IBS: 0.2596160325999662
Fold 3 IBS: 0.1774722747481462
Fold 4 IBS: 0.26344925627468124
Fold 5 IBS: 0.1960748310378663
[I 2024-04-13 17:06:31,030] Trial 42 finished with value: 0.22697460703781053 and parameters: {'l1_ratio': 0.17403241938277308}. Best is trial 42 with value: 0.22697460703781053.
Fold 1 IBS: 0.23850400042926875
Fold 2 IBS: 0.23200945491742272
Fold 3 IBS: 0.22671963413045504
Fold 4 IBS: 0.25023259392912045
Fold 5 IBS: 0.22582376782672195
[I 2024-04-13 17:06:31,196] Trial 43 finished with value: 0.2346578902465978 and parameters: {'l1_ratio': 0.059820186386939866}. Best is trial 42 with value: 0.22697460703781053.
Fold 1 IBS: 0.23825505534418037
Fold 2 IBS: 0.2595622520137693
Fold 3 IBS: 0.17741582910214757
Fold 4 IBS: 0.282271100011185
Fold 5 IBS: 0.19616256568423052
[I 2024-04-13 17:06:31,477] Trial 44 finished with value: 0.23073336043110254 and parameters: {'l1_ratio': 0.3542224495105749}. Best is trial 42 with value: 0.22697460703781053.
Fold 1 IBS: 0.23831342277453135
Fold 2 IBS: 0.2595369313343504
Fold 3 IBS: 0.17738588581946274
Fold 4 IBS: 0.26277882559007665
Fold 5 IBS: 0.19607692666000273
[I 2024-04-13 17:06:31,752] Trial 45 finished with value: 0.22681839843568477 and parameters: {'l1_ratio': 0.16672866994677193}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23838284991542852
Fold 2 IBS: 0.23218317624660798
Fold 3 IBS: 0.2249228169450112
Fold 4 IBS: 0.2586461462457847
Fold 5 IBS: 0.19604744453864748
[I 2024-04-13 17:06:31,911] Trial 46 finished with value: 0.23003648677829597 and parameters: {'l1_ratio': 0.12647551093570325}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23823582809012536
Fold 2 IBS: 0.25955942176737423
Fold 3 IBS: 0.1774585162018019
Fold 4 IBS: 0.27158421507255953
Fold 5 IBS: 0.19613737284952842
[I 2024-04-13 17:06:32,128] Trial 47 finished with value: 0.2285950707962779 and parameters: {'l1_ratio': 0.2940324977232692}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.2384246692112937
Fold 2 IBS: 0.25958252765265644
Fold 3 IBS: 0.1774413981231296
Fold 4 IBS: 0.2823207741992294
Fold 5 IBS: 0.19629868366160902
[I 2024-04-13 17:06:32,354] Trial 48 finished with value: 0.23081361056958363 and parameters: {'l1_ratio': 0.6814395334066481}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.24572887823207373
Fold 2 IBS: 0.23199517704298836
Fold 3 IBS: 0.22773148395311632
Fold 4 IBS: 0.24613485516458328
Fold 5 IBS: 0.22735283160148717
[I 2024-04-13 17:06:32,453] Trial 49 finished with value: 0.2357886451988498 and parameters: {'l1_ratio': 0.030462829152348325}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23825725470502596

Fold 2 IBS: 0.25951865117334183
Fold 3 IBS: 0.17754931699399207
Fold 4 IBS: 0.28222615388072314
Fold 5 IBS: 0.19619038048128568
[I 2024-04-13 17:06:32,687] Trial 50 finished with value: 0.23074835144687372 and parameters: {'l1_ratio': 0.41653985858071785}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.2382357139485572
Fold 2 IBS: 0.2596101111858774
Fold 3 IBS: 0.17750899854071667
Fold 4 IBS: 0.26486067928576307
Fold 5 IBS: 0.1960820029155451
[I 2024-04-13 17:06:32,946] Trial 51 finished with value: 0.22725950117529187 and parameters: {'l1_ratio': 0.19031596268046638}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23829655493110996
Fold 2 IBS: 0.25956288920813936
Fold 3 IBS: 0.17750653577127826
Fold 4 IBS: 0.26299168854643207
Fold 5 IBS: 0.19606915721735552
[I 2024-04-13 17:06:33,156] Trial 52 finished with value: 0.22688536513486302 and parameters: {'l1_ratio': 0.16901987791340187}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23843118530284696
Fold 2 IBS: 0.2320649806257105
Fold 3 IBS: 0.225867421886965
Fold 4 IBS: 0.25409601437643703
Fold 5 IBS: 0.22460768703809245
[I 2024-04-13 17:06:33,286] Trial 53 finished with value: 0.2350134578460104 and parameters: {'l1_ratio': 0.08874233434471136}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23826012500133525
Fold 2 IBS: 0.25946971749761366
Fold 3 IBS: 0.17746208744922018
Fold 4 IBS: 0.26951559801287156
Fold 5 IBS: 0.1961158948831199
[I 2024-04-13 17:06:33,510] Trial 54 finished with value: 0.2281646845688321 and parameters: {'l1_ratio': 0.2559935367058386}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23833534822292687
Fold 2 IBS: 0.2322424809509403
Fold 3 IBS: 0.22458347297515857
Fold 4 IBS: 0.26030561703505883
Fold 5 IBS: 0.19605751087596548
[I 2024-04-13 17:06:33,661] Trial 55 finished with value: 0.23030488601201 and parameters: {'l1_ratio': 0.14177391802482384}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.2382746709016307
Fold 2 IBS: 0.25950273454139566
Fold 3 IBS: 0.17746856261247443
Fold 4 IBS: 0.2654213104166594
Fold 5 IBS: 0.19608749772958076
[I 2024-04-13 17:06:33,880] Trial 56 finished with value: 0.22735095524034818 and parameters: {'l1_ratio': 0.1971665406558995}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23852497568360942
Fold 2 IBS: 0.23202398949031403
Fold 3 IBS: 0.2264204561120801
Fold 4 IBS: 0.251552509203603
Fold 5 IBS: 0.22539274819745617
[I 2024-04-13 17:06:34,160] Trial 57 finished with value: 0.23478293573741255 and parameters: {'l1_ratio': 0.06948784225967945}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23822298342609535
Fold 2 IBS: 0.25956049566897305
Fold 3 IBS: 0.17751144490695453
Fold 4 IBS: 0.26880932035137617
Fold 5 IBS: 0.19611562486406386
[I 2024-04-13 17:06:34,433] Trial 58 finished with value: 0.2280439738434926 and parameters: {'l1_ratio': 0.2445118730462315}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23827412241105964
Fold 2 IBS: 0.25959705535676975
Fold 3 IBS: 0.17748503926064796
Fold 4 IBS: 0.26327679863226494
Fold 5 IBS: 0.19607271108692786
[I 2024-04-13 17:06:34,692] Trial 59 finished with value: 0.22694114534953402 and parameters: {'l1_ratio': 0.1721288873111529}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23826372479727542
Fold 2 IBS: 0.2596234232882927
Fold 3 IBS: 0.177423849673839
Fold 4 IBS: 0.2720851428238456
Fold 5 IBS: 0.1961376644546034
[I 2024-04-13 17:06:34,904] Trial 60 finished with value: 0.2287067610075712 and parameters: {'l1_ratio': 0.3044385856095998}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23829080778490613
Fold 2 IBS: 0.2595716808145087
Fold 3 IBS: 0.1775010049952184
Fold 4 IBS: 0.2630645131102804
Fold 5 IBS: 0.19607007088884182
[I 2024-04-13 17:06:35,167] Trial 61 finished with value: 0.2268996155187511 and parameters: {'l1_ratio': 0.16980957593047288}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.2384208438957826
Fold 2 IBS: 0.23211040985577833
Fold 3 IBS: 0.2254400049657939
Fold 4 IBS: 0.25613266845410537
Fold 5 IBS: 0.22398991424028294
[I 2024-04-13 17:06:35,313] Trial 62 finished with value: 0.23521876828234864 and parameters: {'l1_ratio': 0.10499460490216102}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.24723797470998207
Fold 2 IBS: 0.23203945737857318
Fold 3 IBS: 0.2289746450057727
Fold 4 IBS: 0.24199579728796697
Fold 5 IBS: 0.229383297346969
[I 2024-04-13 17:06:35,419] Trial 63 finished with value: 0.23592623434585275 and parameters: {'l1_ratio': 0.00016053750360278674}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23831318640788285
Fold 2 IBS: 0.23229936077531768
Fold 3 IBS: 0.22429335627166377
Fold 4 IBS: 0.2616820849654876
Fold 5 IBS: 0.1960636512544352
[I 2024-04-13 17:06:35,616] Trial 64 finished with value: 0.23053032793495745 and parameters: {'l1_ratio': 0.15530395297641922}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.2382219720552465
Fold 2 IBS: 0.25957083263558534
Fold 3 IBS: 0.17746933791746702
Fold 4 IBS: 0.2674484986926924
Fold 5 IBS: 0.19609574119866807
[I 2024-04-13 17:06:35,833] Trial 65 finished with value: 0.22776127649993186 and parameters: {'l1_ratio': 0.22411319658008202}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23825240023472613
Fold 2 IBS: 0.2596284036262594
Fold 3 IBS: 0.1774644925308023
Fold 4 IBS: 0.26355507231318975
Fold 5 IBS: 0.19607487821542335
[I 2024-04-13 17:06:36,059] Trial 66 finished with value: 0.22699504938408016 and parameters: {'l1_ratio': 0.17520915276783205}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23839822668803917
Fold 2 IBS: 0.25956230022452587
Fold 3 IBS: 0.17750758221874244
Fold 4 IBS: 0.2821983594380419
Fold 5 IBS: 0.19627217595844187
[I 2024-04-13 17:06:36,289] Trial 67 finished with value: 0.23078772890555826 and parameters: {'l1_ratio': 0.6153588335954362}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.24512888121695525
Fold 2 IBS: 0.23199621173403823
Fold 3 IBS: 0.2272078947448346
Fold 4 IBS: 0.24817974662914247
Fold 5 IBS: 0.2265478724480154
[I 2024-04-13 17:06:36,391] Trial 68 finished with value: 0.23581212135459717 and parameters: {'l1_ratio': 0.04505141347373601}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23835203298294694
Fold 2 IBS: 0.23223463179087153
Fold 3 IBS: 0.22462537207328606
Fold 4 IBS: 0.26010072462734074
Fold 5 IBS: 0.19605481001711342
[I 2024-04-13 17:06:36,574] Trial 69 finished with value: 0.23027351429831172 and parameters: {'l1_ratio': 0.13982889338931048}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23830290005227941
Fold 2 IBS: 0.25959098871541836
Fold 3 IBS: 0.17744490683207917
Fold 4 IBS: 0.28226113312491474
Fold 5 IBS: 0.19621574729961985
[I 2024-04-13 17:06:36,820] Trial 70 finished with value: 0.2307631352048623 and parameters: {'l1_ratio': 0.47412631369701846}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23828359493755644
Fold 2 IBS: 0.2595826770489051
Fold 3 IBS: 0.1774940866140478
Fold 4 IBS: 0.2631561246271832
Fold 5 IBS: 0.1960712144654963
[I 2024-04-13 17:06:37,048] Trial 71 finished with value: 0.22691753953863775 and parameters: {'l1_ratio': 0.1708072858867262}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23844111579523347
Fold 2 IBS: 0.23208234624679883
Fold 3 IBS: 0.22568962640715057
Fold 4 IBS: 0.2549371154296226
Fold 5 IBS: 0.2243491864073112
[I 2024-04-13 17:06:37,169] Trial 72 finished with value: 0.23509987805722332 and parameters: {'l1_ratio': 0.09534852295849916}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23830638456711167
Fold 2 IBS: 0.2595030153079256
Fold 3 IBS: 0.17743543816434834
Fold 4 IBS: 0.2639567873001939
Fold 5 IBS: 0.1960797287566516
[I 2024-04-13 17:06:37,380] Trial 73 finished with value: 0.22705627081924623 and parameters: {'l1_ratio': 0.17973895237395496}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.2382197758784565
Fold 2 IBS: 0.2595390445596543
Fold 3 IBS: 0.1774253214147816
Fold 4 IBS: 0.27005457605084454
Fold 5 IBS: 0.1961239950862486
[I 2024-04-13 17:06:37,603] Trial 74 finished with value: 0.2282725425979971 and parameters: {'l1_ratio': 0.26522684180008516}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23822476518800745

Fold 2 IBS: 0.25952472533669496
Fold 3 IBS: 0.1774960392545615
Fold 4 IBS: 0.2670682153268056
Fold 5 IBS: 0.19609819335409484
[I 2024-04-13 17:06:37,816] Trial 75 finished with value: 0.22768238769203286 and parameters: {'l1_ratio': 0.21877076880955348}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23829998453371104
Fold 2 IBS: 0.23230675325916297
Fold 3 IBS: 0.22425800264666115
Fold 4 IBS: 0.2618485639188856
Fold 5 IBS: 0.1960657581178909
[I 2024-04-13 17:06:37,971] Trial 76 finished with value: 0.23055581249526233 and parameters: {'l1_ratio': 0.15699904383686278}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23833259207918248
Fold 2 IBS: 0.23220358225358703
Fold 3 IBS: 0.22479972642178173
Fold 4 IBS: 0.2592480184868065
Fold 5 IBS: 0.1960543884558004
[I 2024-04-13 17:06:38,122] Trial 77 finished with value: 0.2301276615394316 and parameters: {'l1_ratio': 0.13190820156137945}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23824614926582016
Fold 2 IBS: 0.2596260604047333
Fold 3 IBS: 0.17743665203558096
Fold 4 IBS: 0.26792525589185184
Fold 5 IBS: 0.19610163850384385
[I 2024-04-13 17:06:38,336] Trial 78 finished with value: 0.22786715122036605 and parameters: {'l1_ratio': 0.23102208339460914}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23827245934523833
Fold 2 IBS: 0.2595995723922541
Fold 3 IBS: 0.1774834553196673
Fold 4 IBS: 0.2632980273891813
Fold 5 IBS: 0.19607297323620995
[I 2024-04-13 17:06:38,545] Trial 79 finished with value: 0.2269452975365102 and parameters: {'l1_ratio': 0.17236225768841104}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23822471127679976
Fold 2 IBS: 0.25949500067230097
Fold 3 IBS: 0.1774485105778632
Fold 4 IBS: 0.2822272092904367
Fold 5 IBS: 0.19615614523652458
[I 2024-04-13 17:06:38,781] Trial 80 finished with value: 0.23071031541078507 and parameters: {'l1_ratio': 0.3421920524994373}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23824973953299103
Fold 2 IBS: 0.2596323868787038
Fold 3 IBS: 0.1774619865962165
Fold 4 IBS: 0.2635893050930006
Fold 5 IBS: 0.19607529604506296
[I 2024-04-13 17:06:39,015] Trial 81 finished with value: 0.22700174282919497 and parameters: {'l1_ratio': 0.17559128724962475}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23822792709986354
Fold 2 IBS: 0.25959144349534063
Fold 3 IBS: 0.17741728990741934
Fold 4 IBS: 0.2661583712725269
Fold 5 IBS: 0.19608847546545402
[I 2024-04-13 17:06:39,262] Trial 82 finished with value: 0.2274967014481209 and parameters: {'l1_ratio': 0.20654591845729423}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.23836764561603863
Fold 2 IBS: 0.23212568000580275
Fold 3 IBS: 0.22531855471850487
Fold 4 IBS: 0.25671937639493414
Fold 5 IBS: 0.22381675226459147
[I 2024-04-13 17:06:39,398] Trial 83 finished with value: 0.2352696017999744 and parameters: {'l1_ratio': 0.10985200621899731}. Best is trial 45 with value: 0.22681839843568477.
Fold 1 IBS: 0.238323985253566
Fold 2 IBS: 0.25952055803054586
Fold 3 IBS: 0.17739535354388047
Fold 4 IBS: 0.2626462000995988
Fold 5 IBS: 0.19607433092244167
[I 2024-04-13 17:06:39,606] Trial 84 finished with value: 0.22679208557000657 and parameters: {'l1_ratio': 0.16531374004314667}. Best is trial 84 with value: 0.22679208557000657.
Fold 1 IBS: 0.2382451422767149
Fold 2 IBS: 0.2595972914188285
Fold 3 IBS: 0.17753427282024048
Fold 4 IBS: 0.2705161215579123
Fold 5 IBS: 0.19612952963879057
[I 2024-04-13 17:06:39,813] Trial 85 finished with value: 0.22840447154249738 and parameters: {'l1_ratio': 0.2734898513971819}. Best is trial 84 with value: 0.22679208557000657.
Fold 1 IBS: 0.2384865438766879
Fold 2 IBS: 0.2320550084651917
Fold 3 IBS: 0.22598074226818257
Fold 4 IBS: 0.25356526031597626
Fold 5 IBS: 0.22477351679693958
[I 2024-04-13 17:06:39,945] Trial 86 finished with value: 0.23497221434459564 and parameters: {'l1_ratio': 0.08464134329173442}. Best is trial 84 with value: 0.22679208557000657.
Fold 1 IBS: 0.23839373838735925
Fold 2 IBS: 0.23221595560216948
Fold 3 IBS: 0.22472851787504053
Fold 4 IBS: 0.259596327677869
Fold 5 IBS: 0.19605895534417547
[I 2024-04-13 17:06:40,104] Trial 87 finished with value: 0.23019869897732273 and parameters: {'l1_ratio': 0.13511067237603824}. Best is trial 84 with value: 0.22679208557000657.
Fold 1 IBS: 0.24533433271175678
Fold 2 IBS: 0.23199438301061356
Fold 3 IBS: 0.2273892131690962
Fold 4 IBS: 0.24745243279894502
Fold 5 IBS: 0.2268232913358331
[I 2024-04-13 17:06:40,188] Trial 88 finished with value: 0.23579873060524892 and parameters: {'l1_ratio': 0.039861000143975756}. Best is trial 84 with value: 0.22679208557000657.
Fold 1 IBS: 0.23826154343427897
Fold 2 IBS: 0.2595227458929831
Fold 3 IBS: 0.17745699826148623
Fold 4 IBS: 0.2655849025636698
Fold 5 IBS: 0.1960894327064085
[I 2024-04-13 17:06:40,381] Trial 89 finished with value: 0.2273831245717653 and parameters: {'l1_ratio': 0.19921053287599985}. Best is trial 84 with value: 0.22679208557000657.
Fold 1 IBS: 0.23849381035687744
Fold 2 IBS: 0.23201771276987607
Fold 3 IBS: 0.22653713658386926
Fold 4 IBS: 0.25103255230396415
Fold 5 IBS: 0.22555969794422778
[I 2024-04-13 17:06:40,550] Trial 90 finished with value: 0.2347281819917629 and parameters: {'l1_ratio': 0.06565837981125396}. Best is trial 84 with value: 0.22679208557000657.
Fold 1 IBS: 0.23829694127070894
Fold 2 IBS: 0.25956229725656016
Fold 3 IBS: 0.1775069081493383
Fold 4 IBS: 0.2629867985115391
Fold 5 IBS: 0.19606909571861877
[I 2024-04-13 17:06:40,818] Trial 91 finished with value: 0.22688440818135308 and parameters: {'l1_ratio': 0.16896695858966848}. Best is trial 84 with value: 0.22679208557000657.
Fold 1 IBS: 0.23822220915153128
Fold 2 IBS: 0.2595587785615611
Fold 3 IBS: 0.17751243678965883
Fold 4 IBS: 0.26879535076492866
Fold 5 IBS: 0.19611546178954486
[I 2024-04-13 17:06:41,056] Trial 92 finished with value: 0.22804084741144495 and parameters: {'l1_ratio': 0.24429137536805512}. Best is trial 84 with value: 0.22679208557000657.
Fold 1 IBS: 0.23832103142483843
Fold 2 IBS: 0.23229504244627247
Fold 3 IBS: 0.22431425238482494
Fold 4 IBS: 0.2615836208939495
Fold 5 IBS: 0.1960623937179058
[I 2024-04-13 17:06:41,221] Trial 93 finished with value: 0.23051526817355822 and parameters: {'l1_ratio': 0.15430766204091947}. Best is trial 84 with value: 0.22679208557000657.
Fold 1 IBS: 0.23841975181484307
Fold 2 IBS: 0.2321693162186475
Fold 3 IBS: 0.22501094860916115
Fold 4 IBS: 0.2582156585232103
Fold 5 IBS: 0.1960528826095749
[I 2024-04-13 17:06:41,372] Trial 94 finished with value: 0.22997371155508736 and parameters: {'l1_ratio': 0.12266412406362626}. Best is trial 84 with value: 0.22679208557000657.
Fold 1 IBS: 0.23823295396244326
Fold 2 IBS: 0.2595531089677326
Fold 3 IBS: 0.17746186260693483
Fold 4 IBS: 0.2715362648277165
Fold 5 IBS: 0.1961367734340335
[I 2024-04-13 17:06:41,579] Trial 95 finished with value: 0.22858419275977213 and parameters: {'l1_ratio': 0.29306386302391596}. Best is trial 84 with value: 0.22679208557000657.
Fold 1 IBS: 0.23823633538412187
Fold 2 IBS: 0.25961494874007124
Fold 3 IBS: 0.17740290569053196
Fold 4 IBS: 0.2663706483457897
Fold 5 IBS: 0.19609106824955697
[I 2024-04-13 17:06:41,796] Trial 96 finished with value: 0.22754318128201434 and parameters: {'l1_ratio': 0.20933136709298314}. Best is trial 84 with value: 0.22679208557000657.
Fold 1 IBS: 0.2382566290696941
Fold 2 IBS: 0.2596220615175769
Fold 3 IBS: 0.17746848226479667
Fold 4 IBS: 0.2635007300137693
Fold 5 IBS: 0.19607545953797353
[I 2024-04-13 17:06:42,003] Trial 97 finished with value: 0.2269846724807621 and parameters: {'l1_ratio': 0.1746039950717477}. Best is trial 84 with value: 0.22679208557000657.
Fold 1 IBS: 0.23851571957749132
Fold 2 IBS: 0.2596321406148718
Fold 3 IBS: 0.1775022126987342
Fold 4 IBS: 0.28220720348051376
Fold 5 IBS: 0.19633040952904773
[I 2024-04-13 17:06:42,223] Trial 98 finished with value: 0.23083753718013175 and parameters: {'l1_ratio': 0.7667338152719219}. Best is trial 84 with value: 0.22679208557000657.
Fold 1 IBS: 0.23822429459310168
Fold 2 IBS: 0.25956340333783995
Fold 3 IBS: 0.17750976527927578
Fold 4 IBS: 0.2688329950979255
Fold 5 IBS: 0.19611590104466295
[I 2024-04-13 17:06:42,428] Trial 99 finished with value: 0.22804927187056118 and parameters: {'l1_ratio': 0.24488612184505057}. Best is trial 84 with value: 0.22679208557000657.


* Best trial for IBS:
 FrozenTrial(number=84, state=TrialState.COMPLETE, values=[0.22679208557000657], datetime_start=datetime.datetime(2024, 4, 13, 17, 6, 39, 401013), datetime_complete=datetime.datetime(2024, 4, 13, 17, 6, 39, 606391), params={'l1_ratio': 0.16531374004314667}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=84, value=None)


* Best Score for IBS:
 0.22679208557000657

In [57]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [58]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.638
train_ibs:  0.227

#### Test

In [59]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [60]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.4231641494784485)

test_cindex : 0.532

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.16531374004314667)

test_ibs:  0.273

In [61]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [62]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:06:42,664] A new study created in memory with name: no-name-25a4f96d-46d5-48a2-81cb-510ba651dfce

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.575107296137339
[I 2024-04-13 17:06:44,514] Trial 0 finished with value: 0.6177885807850675 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6177885807850675.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:06:45,923] Trial 1 finished with value: 0.6402989429173871 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.6402989429173871.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.6008583690987125
[I 2024-04-13 17:06:47,012] Trial 2 finished with value: 0.6393357242915708 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.6402989429173871.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:06:47,773] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.6402989429173871.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:06:48,334] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.6402989429173871.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 17:06:50,141] Trial 5 finished with value: 0.6471658831186169 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6863117870722434
Fold 5 C-index: 0.6115879828326181
[I 2024-04-13 17:06:51,992] Trial 6 finished with value: 0.6344921146735147 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:06:52,918] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:06:55,735] Trial 8 finished with value: 0.5180257510729614 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.5968992248062015
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.5944206008583691
[I 2024-04-13 17:06:57,295] Trial 9 finished with value: 0.6262562593650948 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:06:57,622] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.6673003802281369
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 17:06:58,418] Trial 11 finished with value: 0.640537452234508 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11629432582260082, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.647410358565737
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.674468085106383
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6158798283261803
[I 2024-04-13 17:06:59,149] Trial 12 finished with value: 0.6472725256821195 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.8064195611120726, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10227389828304193, 'warm_start': False}. Best is trial 12 with value: 0.6472725256821195.
Fold 1 C-index: 0.6354581673306773
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.575107296137339
[I 2024-04-13 17:06:59,295] Trial 13 finished with value: 0.6354800902960902 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 7, 'oob_score': False, 'max_samples': 0.4941394758404661, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.008606277463368957, 'warm_start': False}. Best is trial 12 with value: 0.6472725256821195.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 17:06:59,880] Trial 14 finished with value: 0.7002369632470599 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 120, 'oob_score': True, 'max_samples': 0.8364130211722378, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10429920715486261, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6453488372093024
Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:07:00,305] Trial 15 finished with value: 0.6757811535432272 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 120, 'oob_score': True, 'max_samples': 0.9847369290686088, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17574628605071868, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.

Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 17:07:00,776] Trial 16 finished with value: 0.6771580986582885 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.962365055520953, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19037781478052387, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.6416309012875536
[I 2024-04-13 17:07:01,333] Trial 17 finished with value: 0.6714707475493069 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 180, 'oob_score': True, 'max_samples': 0.8699768148803853, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20705158222188405, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6195219123505976
Fold 2 C-index: 0.6414728682170543
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:07:01,572] Trial 18 finished with value: 0.6567223411334931 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 58, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.7425531914893617
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6373390557939914
[I 2024-04-13 17:07:02,024] Trial 19 finished with value: 0.671915912796344 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 153, 'oob_score': True, 'max_samples': 0.7093777033655436, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07770947342327489, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6195219123505976
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6502145922746781
[I 2024-04-13 17:07:02,333] Trial 20 finished with value: 0.68201262766852 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 89, 'oob_score': True, 'max_samples': 0.8574334183065578, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16825759122066408, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7425531914893617
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6459227467811158
[I 2024-04-13 17:07:02,596] Trial 21 finished with value: 0.6828780051799364 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 65, 'oob_score': True, 'max_samples': 0.8574739496774684, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1580984841046789, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 17:07:02,864] Trial 22 finished with value: 0.6954786045995129 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 67, 'oob_score': True, 'max_samples': 0.8339758748294697, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14609188473654175, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6824034334763949
[I 2024-04-13 17:07:03,002] Trial 23 finished with value: 0.6999767612780623 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 21, 'oob_score': True, 'max_samples': 0.7847143847565936, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13226034227314248, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6872340425531915
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6545064377682404
[I 2024-04-13 17:07:03,113] Trial 24 finished with value: 0.6577607816323275 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.7775916898124314, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.25150584936274806, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6545064377682404
[I 2024-04-13 17:07:03,285] Trial 25 finished with value: 0.6783623065010328 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 33, 'oob_score': True, 'max_samples': 0.6669213410828165, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13486370381501434, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6974248927038627
[I 2024-04-13 17:07:03,587] Trial 26 finished with value: 0.7005252977723723 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 91, 'oob_score': True, 'max_samples': 0.5349306463888053, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06566365555656244, 'warm_start': True}. Best is trial 26 with value: 0.7005252977723723.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7124463519313304
[I 2024-04-13 17:07:03,900] Trial 27 finished with value: 0.7061005790200177 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 90, 'oob_score': True, 'max_samples': 0.5366581083873809, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06208957998994368, 'warm_start': True}. Best is trial 27 with value: 0.7061005790200177.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6845493562231759
[I 2024-04-13 17:07:04,571] Trial 28 finished with value: 0.6887400143879626 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 224, 'oob_score': True, 'max_samples': 0.41379803894855116, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07805190635410612, 'warm_start': True}. Best is trial 27 with value: 0.7061005790200177.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.7253218884120172
[I 2024-04-13 17:07:05,076] Trial 29 finished with value: 0.7116053815973882 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 164, 'oob_score': True, 'max_samples': 0.5248192039443108, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0554252254423035, 'warm_start': True}. Best is trial 29 with value: 0.7116053815973882.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 17:07:05,605] Trial 30 finished with value: 0.7010446660346952 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 169, 'oob_score': True, 'max_samples': 0.5345414788093061, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03755841239520112, 'warm_start': True}. Best is trial 29 with value: 0.7116053815973882.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.7017167381974249
[I 2024-04-13 17:07:06,136] Trial 31 finished with value: 0.7000756268928836 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 171, 'oob_score': True, 'max_samples': 0.5019192620095752, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.050771418210883164, 'warm_start': True}. Best is trial 29 with value: 0.7116053815973882.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 17:07:06,814] Trial 32 finished with value: 0.7177295061567273 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 223, 'oob_score': True, 'max_samples': 0.563642711374241, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05266275392679234, 'warm_start': True}. Best is trial 32 with value: 0.7177295061567273.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 17:07:07,530] Trial 33 finished with value: 0.7049756930439305 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 234, 'oob_score': True, 'max_samples': 0.35232498791610145, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00379084860293024, 'warm_start': True}. Best is trial 32 with value: 0.7177295061567273.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.703862660944206
[I 2024-04-13 17:07:08,232] Trial 34 finished with value: 0.7010699790361788 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.3828093578201666, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0026062845432726807, 'warm_start': True}. Best is trial 32 with value: 0.7177295061567273.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.7042553191489361
Fold 4 C-index: 0.6825095057034221
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:07:08,861] Trial 35 finished with value: 0.6556598127697459 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 212, 'oob_score': True, 'max_samples': 0.26793001302903535, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0862146443224848, 'warm_start': True}. Best is trial 32 with value: 0.7177295061567273.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 17:07:09,842] Trial 36 finished with value: 0.7288309903966594 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 341, 'oob_score': True, 'max_samples': 0.3445095149903548, 'max_features': None, 'min_weight_fraction_leaf': 0.00052334394504433, 'warm_start': True}. Best is trial 36 with value: 0.7288309903966594.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8369098712446352
[I 2024-04-13 17:07:10,928] Trial 37 finished with value: 0.7549756456347672 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.5874006073245895, 'max_features': None, 'min_weight_fraction_leaf': 0.051378997578725064, 'warm_start': True}. Best is trial 37 with value: 0.7549756456347672.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7982832618025751
[I 2024-04-13 17:07:12,061] Trial 38 finished with value: 0.7411193039013269 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 378, 'oob_score': True, 'max_samples': 0.42872870036644545, 'max_features': None, 'min_weight_fraction_leaf': 0.03685839885089406, 'warm_start': True}. Best is trial 37 with value: 0.7549756456347672.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:07:13,324] Trial 39 finished with value: 0.7764777161516213 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.5898221765815288, 'max_features': None, 'min_weight_fraction_leaf': 0.0280794008099322, 'warm_start': True}. Best is trial 39 with value: 0.7764777161516213.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.8154506437768241
[I 2024-04-13 17:07:14,490] Trial 40 finished with value: 0.7453537247989861 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.44424040796819986, 'max_features': None, 'min_weight_fraction_leaf': 0.029813810847214628, 'warm_start': True}. Best is trial 39 with value: 0.7764777161516213.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 17:07:15,644] Trial 41 finished with value: 0.767706324749998 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.42993466896213306, 'max_features': None, 'min_weight_fraction_leaf': 0.02699423331352132, 'warm_start': True}. Best is trial 39 with value: 0.7764777161516213.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8369098712446352
[I 2024-04-13 17:07:16,831] Trial 42 finished with value: 0.7558493030880561 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.43835115795914964, 'max_features': None, 'min_weight_fraction_leaf': 0.03261747288898426, 'warm_start': True}. Best is trial 39 with value: 0.7764777161516213.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.871244635193133
[I 2024-04-13 17:07:18,082] Trial 43 finished with value: 0.7805052982197098 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.6182013697142779, 'max_features': None, 'min_weight_fraction_leaf': 0.02680908937928254, 'warm_start': True}. Best is trial 43 with value: 0.7805052982197098.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7893617021276595
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7467811158798283
[I 2024-04-13 17:07:19,475] Trial 44 finished with value: 0.7199270020227763 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 478, 'oob_score': True, 'max_samples': 0.6260162353120974, 'max_features': None, 'min_weight_fraction_leaf': 0.09652293104879651, 'warm_start': True}. Best is trial 43 with value: 0.7805052982197098.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:07:20,223] Trial 45 finished with value: 0.7876297777014609 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.6932069026339767, 'max_features': None, 'min_weight_fraction_leaf': 0.02673421337104168, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.5858369098712446
[I 2024-04-13 17:07:23,304] Trial 46 finished with value: 0.6175266138918902 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 421, 'oob_score': False, 'max_samples': 0.713175685335591, 'max_features': None, 'min_weight_fraction_leaf': 0.02263809195586287, 'warm_start': False}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 17:07:23,990] Trial 47 finished with value: 0.7024716099360828 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.6640283145362862, 'max_features': None, 'min_weight_fraction_leaf': 0.11937729206282155, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:07:25,800] Trial 48 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.4725841795598701, 'max_features': None, 'min_weight_fraction_leaf': 0.38812198780775825, 'warm_start': False}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:07:26,567] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.2076878129262199, 'max_features': None, 'min_weight_fraction_leaf': 0.4820963556426466, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.6492248062015504
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.6825095057034221
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 17:07:27,239] Trial 50 finished with value: 0.649042644861519 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.679318106876105, 'max_features': None, 'min_weight_fraction_leaf': 0.2758707435072836, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 17:07:27,867] Trial 51 finished with value: 0.7637338414488053 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 394, 'oob_score': False, 'max_samples': 0.5821155504207499, 'max_features': None, 'min_weight_fraction_leaf': 0.02422764197259524, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 17:07:28,503] Trial 52 finished with value: 0.7637338414488053 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.5780114655400654, 'max_features': None, 'min_weight_fraction_leaf': 0.019612908407631094, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.759656652360515
[I 2024-04-13 17:07:29,155] Trial 53 finished with value: 0.7330142244474321 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 445, 'oob_score': False, 'max_samples': 0.58647202928343, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.014895484544909543, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 17:07:29,739] Trial 54 finished with value: 0.7502209765566825 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.7451532491332802, 'max_features': None, 'min_weight_fraction_leaf': 0.08067250770106202, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8583690987124464
[I 2024-04-13 17:07:30,289] Trial 55 finished with value: 0.7747108750614803 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.6202755843283627, 'max_features': None, 'min_weight_fraction_leaf': 0.022470717574527028, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.6007751937984496
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.5836909871244635
[I 2024-04-13 17:07:31,992] Trial 56 finished with value: 0.617244798143204 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.6429003803329312, 'max_features': None, 'min_weight_fraction_leaf': 0.22757335863523978, 'warm_start': False}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8326180257510729
[I 2024-04-13 17:07:32,459] Trial 57 finished with value: 0.7539260229172815 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 267, 'oob_score': False, 'max_samples': 0.6226007657277326, 'max_features': None, 'min_weight_fraction_leaf': 0.038788044099769756, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 17:07:33,030] Trial 58 finished with value: 0.7099977128256824 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 361, 'oob_score': False, 'max_samples': 0.6932738670326789, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10056372049643875, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8454935622317596
[I 2024-04-13 17:07:33,514] Trial 59 finished with value: 0.7596304057836407 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 290, 'oob_score': False, 'max_samples': 0.7323761414424763, 'max_features': None, 'min_weight_fraction_leaf': 0.06672040150433087, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6234042553191489
Fold 4 C-index: 0.6977186311787072
Fold 5 C-index: 0.5815450643776824
[I 2024-04-13 17:07:36,097] Trial 60 finished with value: 0.6241729860798608 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.4903074221697629, 'max_features': None, 'min_weight_fraction_leaf': 0.11959785503226739, 'warm_start': False}. Best is trial 45 with value: 0.7876297777014609.

Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:07:36,761] Trial 61 finished with value: 0.7804185419955325 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.5775531242934729, 'max_features': None, 'min_weight_fraction_leaf': 0.014771588904444915, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:07:37,391] Trial 62 finished with value: 0.7818313762245508 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 430, 'oob_score': False, 'max_samples': 0.6120312661504053, 'max_features': None, 'min_weight_fraction_leaf': 0.01656914948618143, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8583690987124464
[I 2024-04-13 17:07:38,060] Trial 63 finished with value: 0.7763007762144775 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 433, 'oob_score': False, 'max_samples': 0.6357815970769084, 'max_features': None, 'min_weight_fraction_leaf': 0.04354887768929718, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8454935622317596
[I 2024-04-13 17:07:38,733] Trial 64 finished with value: 0.7579098162543703 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 429, 'oob_score': False, 'max_samples': 0.6127459487402497, 'max_features': None, 'min_weight_fraction_leaf': 0.04650833605121199, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8283261802575107
[I 2024-04-13 17:07:39,499] Trial 65 finished with value: 0.7444188242864717 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.6523889675617967, 'max_features': None, 'min_weight_fraction_leaf': 0.06842934943082835, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:07:40,215] Trial 66 finished with value: 0.7867565440912282 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 434, 'oob_score': False, 'max_samples': 0.6881590145066517, 'max_features': None, 'min_weight_fraction_leaf': 0.011806153077869749, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8798283261802575
[I 2024-04-13 17:07:40,941] Trial 67 finished with value: 0.7896209612521833 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 433, 'oob_score': False, 'max_samples': 0.7631123974277301, 'max_features': None, 'min_weight_fraction_leaf': 0.0022885590177692122, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:07:41,623] Trial 68 finished with value: 0.7837247575028984 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 459, 'oob_score': False, 'max_samples': 0.7615347181121479, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0024769456224402846, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8583690987124464
[I 2024-04-13 17:07:42,261] Trial 69 finished with value: 0.7778975587933437 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 417, 'oob_score': False, 'max_samples': 0.7726300856584892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01088116997697249, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:07:42,963] Trial 70 finished with value: 0.7838043518792469 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.9016742863309287, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.007729052885137196, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.871244635193133
[I 2024-04-13 17:07:43,620] Trial 71 finished with value: 0.7838875271795097 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.9017461575502412, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0068241563825637295, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:07:44,440] Trial 72 finished with value: 0.7790161865505592 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 495, 'oob_score': False, 'max_samples': 0.9009406869567084, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0021418267435436436, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.871244635193133
[I 2024-04-13 17:07:45,136] Trial 73 finished with value: 0.7830148443991681 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 456, 'oob_score': False, 'max_samples': 0.9085841532130327, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0030802629542528654, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8755364806866953
[I 2024-04-13 17:07:45,828] Trial 74 finished with value: 0.7831886272554539 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 455, 'oob_score': False, 'max_samples': 0.9228420326396749, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.005019150622141426, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:07:46,499] Trial 75 finished with value: 0.7757963034243145 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.9457439444265902, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0018763322411427912, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.

Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8111587982832618
[I 2024-04-13 17:07:47,396] Trial 76 finished with value: 0.7417173037889626 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'max_samples': 0.8983343226238335, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06474782967395624, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:07:48,073] Trial 77 finished with value: 0.7632234783399822 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 459, 'oob_score': False, 'max_samples': 0.8332435855398501, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.048186815269347504, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:07:48,732] Trial 78 finished with value: 0.7813702683223316 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.9259409338032202, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0014115169159075848, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6414728682170543
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 17:07:49,409] Trial 79 finished with value: 0.6518913485226081 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.8671236023505134, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.34696749792453063, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.5852713178294574
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 17:07:51,972] Trial 80 finished with value: 0.6287361870740857 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.7963493279897067, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03726915892555499, 'warm_start': False}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:07:52,614] Trial 81 finished with value: 0.7898421579172852 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 435, 'oob_score': False, 'max_samples': 0.9937352645069003, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.014733302673387358, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:07:53,277] Trial 82 finished with value: 0.787557081185243 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 441, 'oob_score': False, 'max_samples': 0.9926689295251143, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012807159371837533, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:07:53,914] Trial 83 finished with value: 0.7827942427178591 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 441, 'oob_score': False, 'max_samples': 0.9750237459208526, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01606804819012205, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8111587982832618
[I 2024-04-13 17:07:54,471] Trial 84 finished with value: 0.7401126651112803 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 364, 'oob_score': False, 'max_samples': 0.9913824226489636, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08946868256617803, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8454935622317596
[I 2024-04-13 17:07:55,125] Trial 85 finished with value: 0.7636828908699766 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 419, 'oob_score': False, 'max_samples': 0.9447103169089868, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0557070761228824, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:07:55,892] Trial 86 finished with value: 0.7779481019633775 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 486, 'oob_score': False, 'max_samples': 0.9606973339596948, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03905413442222396, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7382978723404255
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.6759656652360515
[I 2024-04-13 17:07:56,497] Trial 87 finished with value: 0.6830016680735692 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.883088751579364, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0725768406343007, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8583690987124464
[I 2024-04-13 17:07:57,198] Trial 88 finished with value: 0.7756663092990286 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.8207971016698734, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012051717505267413, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8540772532188842
[I 2024-04-13 17:07:57,876] Trial 89 finished with value: 0.7675503095124208 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.9996188810038052, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.030894883442076228, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.8111587982832618
[I 2024-04-13 17:07:58,487] Trial 90 finished with value: 0.7444043407354559 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 413, 'oob_score': False, 'max_samples': 0.7655917999374031, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.059853014276037855, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.

Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8798283261802575
[I 2024-04-13 17:07:59,205] Trial 91 finished with value: 0.7880273357541754 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.8546671993080971, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00043463511590633407, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7723404255319148
Fold 4 C-index: 0.7433460076045627
Fold 5 C-index: 0.703862660944206
[I 2024-04-13 17:07:59,883] Trial 92 finished with value: 0.7014810841424285 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 470, 'oob_score': False, 'max_samples': 0.9327128334728044, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.013208403993555372, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:08:00,631] Trial 93 finished with value: 0.7802990266542915 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.8426290761275549, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.030993362135028464, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8540772532188842
[I 2024-04-13 17:08:01,302] Trial 94 finished with value: 0.7714547788810922 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 392, 'oob_score': False, 'max_samples': 0.9169001665130876, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04427068760850137, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:08:02,102] Trial 95 finished with value: 0.7826429100639786 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 464, 'oob_score': False, 'max_samples': 0.9695736653081121, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02200415575270175, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.6394422310756972
Fold 2 C-index: 0.6647286821705426
Fold 3 C-index: 0.7042553191489361
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:08:02,727] Trial 96 finished with value: 0.6667466867766902 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.8866673994678815, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00010254419006395848, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6749049429657795
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:08:03,403] Trial 97 finished with value: 0.6585055548372436 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 18, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.743952091363973, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012121939934777472, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5775193798449613
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6115879828326181
[I 2024-04-13 17:08:05,851] Trial 98 finished with value: 0.627071900642681 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.8087130156519865, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.032634018282811726, 'warm_start': False}. Best is trial 81 with value: 0.7898421579172852.

[I 2024-04-13 17:08:06,517] A new study created in memory with name: no-name-7aa4d2fa-6a41-4ead-ba5a-dc032c2fad0b

Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8154506437768241
[I 2024-04-13 17:08:06,506] Trial 99 finished with value: 0.7500076372617474 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 452, 'oob_score': False, 'max_samples': 0.6902938777535903, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04784650401125385, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.


* Best trial for C-index:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.7898421579172852], datetime_start=datetime.datetime(2024, 4, 13, 17, 7, 51, 976661), datetime_complete=datetime.datetime(2024, 4, 13, 17, 7, 52, 614074), params={'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 435, 'oob_score': False, 'max_samples': 0.9937352645069003, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.014733302673387358, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=81, value=None)


* Best Score for C-index:
 0.7898421579172852

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23819032549148034
Fold 2 IBS: 0.23121788001563107
Fold 3 IBS: 0.21979369823749267
Fold 4 IBS: 0.2318228322973839
Fold 5 IBS: 0.21024821548260486
[I 2024-04-13 17:08:08,371] Trial 0 finished with value: 0.22625459030491854 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.22625459030491854.
Fold 1 IBS: 0.2327303554970621
Fold 2 IBS: 0.22773051352570262
Fold 3 IBS: 0.21684304094654686
Fold 4 IBS: 0.2287850855661341
Fold 5 IBS: 0.21336280816660322
[I 2024-04-13 17:08:08,805] Trial 1 finished with value: 0.22389036074040977 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.22389036074040977.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-13 17:08:09,146] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.22389036074040977.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-13 17:08:10,675] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.22389036074040977.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-13 17:08:11,756] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.22389036074040977.
Fold 1 IBS: 0.24195276719924078
Fold 2 IBS: 0.23158306192048977
Fold 3 IBS: 0.21085268504232352
Fold 4 IBS: 0.22590092577347623
Fold 5 IBS: 0.2158343974194969
[I 2024-04-13 17:08:13,379] Trial 5 finished with value: 0.22522476747100542 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.22389036074040977.
Fold 1 IBS: 0.23967841421337877
Fold 2 IBS: 0.22235525504764858
Fold 3 IBS: 0.21859475882848345
Fold 4 IBS: 0.2286576795074638
Fold 5 IBS: 0.2076537454704683
[I 2024-04-13 17:08:14,952] Trial 6 finished with value: 0.22338797061348856 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 6 with value: 0.22338797061348856.
Fold 1 IBS: 0.24345153214227594
Fold 2 IBS: 0.23065480198027405
Fold 3 IBS: 0.22931062857448625
Fold 4 IBS: 0.2384177765763348
Fold 5 IBS: 0.22787014183210574
[I 2024-04-13 17:08:16,794] Trial 7 finished with value: 0.2339409762210954 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 6 with value: 0.22338797061348856.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-13 17:08:19,519] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 6 with value: 0.22338797061348856.
Fold 1 IBS: 0.2320102439831575
Fold 2 IBS: 0.22451454416835206
Fold 3 IBS: 0.2177950757126267
Fold 4 IBS: 0.22911956144415363
Fold 5 IBS: 0.2109401120435157
[I 2024-04-13 17:08:20,092] Trial 9 finished with value: 0.2228759074703611 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 9 with value: 0.2228759074703611.
Fold 1 IBS: 0.246587342303552
Fold 2 IBS: 0.23212002973319837
Fold 3 IBS: 0.22961274657990574
Fold 4 IBS: 0.2413253549165465
Fold 5 IBS: 0.22920684798460136
[I 2024-04-13 17:08:21,166] Trial 10 finished with value: 0.2357704643035608 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1655981152594652}. Best is trial 9 with value: 0.2228759074703611.
Fold 1 IBS: 0.26024444970570754
Fold 2 IBS: 0.2216356331948992
Fold 3 IBS: 0.20646208866549096
Fold 4 IBS: 0.2236987194979317
Fold 5 IBS: 0.20823816667941644
[I 2024-04-13 17:08:21,289] Trial 11 finished with value: 0.22405581154868917 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.9904090680670613, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.31430530876132207}. Best is trial 9 with value: 0.2228759074703611.
Fold 1 IBS: 0.23302253676596166
Fold 2 IBS: 0.22350006799707825
Fold 3 IBS: 0.2117261996244006
Fold 4 IBS: 0.23014872528096708
Fold 5 IBS: 0.21131996892731336
[I 2024-04-13 17:08:22,383] Trial 12 finished with value: 0.2219434997191442 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.9777827337837477, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3324053831839262}. Best is trial 12 with value: 0.2219434997191442.
Fold 1 IBS: 0.2334167482692937
Fold 2 IBS: 0.22462815107178444
Fold 3 IBS: 0.21415254610318984
Fold 4 IBS: 0.22735181638107305
Fold 5 IBS: 0.20943018161274876
[I 2024-04-13 17:08:23,362] Trial 13 finished with value: 0.221795888687618 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 143, 'oob_score': False, 'max_samples': 0.9736995438315953, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21818725312797213}. Best is trial 13 with value: 0.221795888687618.
Fold 1 IBS: 0.23281845581582267
Fold 2 IBS: 0.22270871101965733
Fold 3 IBS: 0.21190072211209907
Fold 4 IBS: 0.22954507565286003
Fold 5 IBS: 0.2097789741690662
[I 2024-04-13 17:08:24,438] Trial 14 finished with value: 0.22135038775390106 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 160, 'oob_score': False, 'max_samples': 0.8117746868873079, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2645968579224677}. Best is trial 14 with value: 0.22135038775390106.
Fold 1 IBS: 0.23363330111712122
Fold 2 IBS: 0.22772251294499274
Fold 3 IBS: 0.21313363370892885
Fold 4 IBS: 0.2311943990289551
Fold 5 IBS: 0.2118872809428859
[I 2024-04-13 17:08:25,652] Trial 15 finished with value: 0.22351422554857675 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.8199794929905286, 'max_features': 'auto', 'min_weight_fraction_leaf': 9.233281859852283e-05}. Best is trial 14 with value: 0.22135038775390106.

Fold 1 IBS: 0.23309849867702975
Fold 2 IBS: 0.2238801862611814
Fold 3 IBS: 0.20957498925944693
Fold 4 IBS: 0.22916161954772554
Fold 5 IBS: 0.20966367383054058
[I 2024-04-13 17:08:27,131] Trial 16 finished with value: 0.22107579351518486 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 246, 'oob_score': False, 'max_samples': 0.7702473623171299, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.25854433873892946}. Best is trial 16 with value: 0.22107579351518486.
Fold 1 IBS: 0.23207571367115706
Fold 2 IBS: 0.22301648270111882
Fold 3 IBS: 0.20929958475920116
Fold 4 IBS: 0.22683443304818943
Fold 5 IBS: 0.20959031967828567
[I 2024-04-13 17:08:29,529] Trial 17 finished with value: 0.2201633067715904 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.7723653893351333, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26653765665911155}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.2463404995719331
Fold 2 IBS: 0.2321448856668435
Fold 3 IBS: 0.22959259113294117
Fold 4 IBS: 0.2415266314104949
Fold 5 IBS: 0.23024189043397938
[I 2024-04-13 17:08:32,389] Trial 18 finished with value: 0.2359692996432384 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 469, 'oob_score': True, 'max_samples': 0.7546903089061138, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38366131019449645}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.23303888011332288
Fold 2 IBS: 0.22300960933547007
Fold 3 IBS: 0.20920134919025463
Fold 4 IBS: 0.22816759153382105
Fold 5 IBS: 0.21046314793606172
[I 2024-04-13 17:08:34,242] Trial 19 finished with value: 0.22077611562178606 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 349, 'oob_score': False, 'max_samples': 0.6166062996487705, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13117892225993338}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.23835822553986638
Fold 2 IBS: 0.22799957337023416
Fold 3 IBS: 0.2255839289968672
Fold 4 IBS: 0.2347799777347254
Fold 5 IBS: 0.22413835268072815
[I 2024-04-13 17:08:36,713] Trial 20 finished with value: 0.23017201166448426 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.36221293246103303, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11290492399019064}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.23174517627510863
Fold 2 IBS: 0.22311183326872192
Fold 3 IBS: 0.2134752532935891
Fold 4 IBS: 0.22849974415037372
Fold 5 IBS: 0.21356235141371618
[I 2024-04-13 17:08:38,633] Trial 21 finished with value: 0.22207887168030188 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.6196799597483587, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2567596687243825}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.2332544171438238
Fold 2 IBS: 0.22319768331574052
Fold 3 IBS: 0.20996383118108564
Fold 4 IBS: 0.22670496467093834
Fold 5 IBS: 0.2102618867189479
[I 2024-04-13 17:08:40,237] Trial 22 finished with value: 0.22067655660610724 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 1, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.4546238642538813, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13974116057386782}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.2310699507275024
Fold 2 IBS: 0.22303094537287663
Fold 3 IBS: 0.21098495554623686
Fold 4 IBS: 0.22669642139137772
Fold 5 IBS: 0.2112926777812192
[I 2024-04-13 17:08:42,650] Trial 23 finished with value: 0.22061499016384256 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.4478983539583735, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1193442431038026}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.2322016436936384
Fold 2 IBS: 0.22349336637777067
Fold 3 IBS: 0.21006996461569238
Fold 4 IBS: 0.22527052958323776
Fold 5 IBS: 0.21049333696088765
[I 2024-04-13 17:08:45,061] Trial 24 finished with value: 0.2203057682462454 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.46113861699976405, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.020430563448902872}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.22991354874075207
Fold 2 IBS: 0.22444368768443465
Fold 3 IBS: 0.21207565297554787
Fold 4 IBS: 0.2262663752096743
Fold 5 IBS: 0.21145135976011514
[I 2024-04-13 17:08:47,625] Trial 25 finished with value: 0.22083012487410478 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 418, 'oob_score': False, 'max_samples': 0.2381911851795994, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.036226389884873186}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.23060883914260805
Fold 2 IBS: 0.22297755155674684
Fold 3 IBS: 0.2101589513975745
Fold 4 IBS: 0.22604712726802575
Fold 5 IBS: 0.21099290824592037
[I 2024-04-13 17:08:51,312] Trial 26 finished with value: 0.22015707552217512 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 440, 'oob_score': True, 'max_samples': 0.4704864355905733, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0010277467041755056}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23046923596128613
Fold 2 IBS: 0.2240015491036018
Fold 3 IBS: 0.21086502402097726
Fold 4 IBS: 0.226142024960214
Fold 5 IBS: 0.21088248515587224
[I 2024-04-13 17:08:54,439] Trial 27 finished with value: 0.22047206384039025 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 396, 'oob_score': True, 'max_samples': 0.27394238361068307, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.013617435329595393}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23471452628920897
Fold 2 IBS: 0.22673547857955847
Fold 3 IBS: 0.21103982953561207
Fold 4 IBS: 0.22446765617728826
Fold 5 IBS: 0.21450015223615418
[I 2024-04-13 17:08:58,928] Trial 28 finished with value: 0.2222915285635644 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.48498687769327536, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0641292220811886}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23136991564996087
Fold 2 IBS: 0.22204971565032036
Fold 3 IBS: 0.21300464981609682
Fold 4 IBS: 0.22675182096688823
Fold 5 IBS: 0.21182202421691915
[I 2024-04-13 17:09:02,647] Trial 29 finished with value: 0.22099962526003708 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.3571755626038756, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03807390698388844}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24606642350611257
Fold 2 IBS: 0.2321923882606996
Fold 3 IBS: 0.22988609347650055
Fold 4 IBS: 0.2412002464153435
Fold 5 IBS: 0.23034386795139541
[I 2024-04-13 17:09:05,789] Trial 30 finished with value: 0.2359378039220103 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.2172618637182342, 'max_features': None, 'min_weight_fraction_leaf': 0.19986328912293344}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23160771794643292
Fold 2 IBS: 0.22646129177037175
Fold 3 IBS: 0.21045869707390338
Fold 4 IBS: 0.22410007258120104

Fold 5 IBS: 0.2108108318582224
[I 2024-04-13 17:09:08,670] Trial 31 finished with value: 0.2206877222460263 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 396, 'oob_score': True, 'max_samples': 0.2868712535426494, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.021231453689495153}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24659836091991297
Fold 2 IBS: 0.23212875696426277
Fold 3 IBS: 0.23013831975076382
Fold 4 IBS: 0.24109773536375373
Fold 5 IBS: 0.22997643124737513
[I 2024-04-13 17:09:11,321] Trial 32 finished with value: 0.23598792084921366 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 323, 'oob_score': True, 'max_samples': 0.15457524910822473, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004932622259272009}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23197141083929648
Fold 2 IBS: 0.22199313349588728
Fold 3 IBS: 0.2125662998256947
Fold 4 IBS: 0.2269154171060468
Fold 5 IBS: 0.2125401699948321
[I 2024-04-13 17:09:15,111] Trial 33 finished with value: 0.22119728625235147 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 470, 'oob_score': True, 'max_samples': 0.3835202498388115, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09218354615163335}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23217381359662775
Fold 2 IBS: 0.22448808064455156
Fold 3 IBS: 0.20986169319903394
Fold 4 IBS: 0.22593776518550224
Fold 5 IBS: 0.210892650964984
[I 2024-04-13 17:09:18,990] Trial 34 finished with value: 0.22067080071813988 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 408, 'oob_score': True, 'max_samples': 0.5426821039862857, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04500199428375251}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23289853012973177
Fold 2 IBS: 0.228024993142558
Fold 3 IBS: 0.21255692441217353
Fold 4 IBS: 0.22694758734723536
Fold 5 IBS: 0.21091359093683118
[I 2024-04-13 17:09:23,177] Trial 35 finished with value: 0.22226832519370596 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 445, 'oob_score': True, 'max_samples': 0.6981514158760593, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16320167359786183}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2350546735426517
Fold 2 IBS: 0.236789743880471
Fold 3 IBS: 0.22212188563214683
Fold 4 IBS: 0.23185305826049626
Fold 5 IBS: 0.21752491954865782
[I 2024-04-13 17:09:27,938] Trial 36 finished with value: 0.22866885617288474 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 490, 'oob_score': True, 'max_samples': 0.49714834826170234, 'max_features': None, 'min_weight_fraction_leaf': 0.09979466708192791}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24022913171172267
Fold 2 IBS: 0.22874946375008556
Fold 3 IBS: 0.21290965440875198
Fold 4 IBS: 0.22557654547485015
Fold 5 IBS: 0.21565985272908825
[I 2024-04-13 17:09:31,384] Trial 37 finished with value: 0.22462492961489972 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 378, 'oob_score': True, 'max_samples': 0.6134779412492984, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.053624327533504934}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2325547869295493
Fold 2 IBS: 0.225529082398541
Fold 3 IBS: 0.21138715556254012
Fold 4 IBS: 0.22282613113953292
Fold 5 IBS: 0.21014751804243587
[I 2024-04-13 17:09:34,325] Trial 38 finished with value: 0.22048893481451987 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.29184797119319694, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.017087153731481407}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23561025683041087
Fold 2 IBS: 0.22941932225139652
Fold 3 IBS: 0.21631460646944745
Fold 4 IBS: 0.23234709305478357
Fold 5 IBS: 0.21076474347276042
[I 2024-04-13 17:09:37,749] Trial 39 finished with value: 0.22489120441575977 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.40430675587035536, 'max_features': None, 'min_weight_fraction_leaf': 0.08714563166723727}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24678613059437637
Fold 2 IBS: 0.2321725909539564
Fold 3 IBS: 0.22944195803388415
Fold 4 IBS: 0.24150527562231744
Fold 5 IBS: 0.230370380894624
[I 2024-04-13 17:09:39,382] Trial 40 finished with value: 0.23605526721983167 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.5739995513235784, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.41526515128052643}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23321286691758872
Fold 2 IBS: 0.2279849928934213
Fold 3 IBS: 0.2117308992197816
Fold 4 IBS: 0.2242204616828136
Fold 5 IBS: 0.20935348900548092
[I 2024-04-13 17:09:42,577] Trial 41 finished with value: 0.22130054194381726 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 333, 'oob_score': True, 'max_samples': 0.315246808599681, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02048652160594618}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2316766890229806
Fold 2 IBS: 0.22411125621421446
Fold 3 IBS: 0.21036674914110157
Fold 4 IBS: 0.22434994497665503
Fold 5 IBS: 0.21106333692808993
[I 2024-04-13 17:09:46,628] Trial 42 finished with value: 0.22031359525660835 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 8, 'n_estimators': 372, 'oob_score': True, 'max_samples': 0.26574428925186755, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.019168305255890875}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2459242180260377
Fold 2 IBS: 0.23217022029472845
Fold 3 IBS: 0.2300031028267955
Fold 4 IBS: 0.24121482096141833
Fold 5 IBS: 0.23030067078583316
[I 2024-04-13 17:09:50,544] Trial 43 finished with value: 0.23592260657896263 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 415, 'oob_score': True, 'max_samples': 0.22277971365249755, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24631410665989734
Fold 2 IBS: 0.23210802473720302
Fold 3 IBS: 0.2302521611117555
Fold 4 IBS: 0.2410435305102926
Fold 5 IBS: 0.23003859251113234
[I 2024-04-13 17:09:53,465] Trial 44 finished with value: 0.23595128310605612 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 360, 'oob_score': True, 'max_samples': 0.1383644314551697, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0686728787591377}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24617592132985935
Fold 2 IBS: 0.2322080714687311
Fold 3 IBS: 0.2295331673330916
Fold 4 IBS: 0.2414957007697489
Fold 5 IBS: 0.23031590144856742
[I 2024-04-13 17:09:57,590] Trial 45 finished with value: 0.23594575246999966 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 459, 'oob_score': True, 'max_samples': 0.5172890166610269, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30571763583075945}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23995673698361222
Fold 2 IBS: 0.22972034149382584
Fold 3 IBS: 0.2273789621853455
Fold 4 IBS: 0.2372388025033728
Fold 5 IBS: 0.2259009708948768
[I 2024-04-13 17:10:01,116] Trial 46 finished with value: 0.23203916281220663 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.1873692143114088, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03681920016521466}. Best is trial 26 with value: 0.22015707552217512.

Fold 1 IBS: 0.23103878287252402
Fold 2 IBS: 0.22628918231285983
Fold 3 IBS: 0.2133979486579942
Fold 4 IBS: 0.22430579562693312
Fold 5 IBS: 0.21153361401748674
[I 2024-04-13 17:10:04,667] Trial 47 finished with value: 0.22131306469755957 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 475, 'oob_score': False, 'max_samples': 0.43491671167283275, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07826676341691717}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2461442212529148
Fold 2 IBS: 0.23226781881803804
Fold 3 IBS: 0.22981312479103597
Fold 4 IBS: 0.24139414747597257
Fold 5 IBS: 0.2304782442201671
[I 2024-04-13 17:10:08,433] Trial 48 finished with value: 0.23601951131162568 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 19, 'max_depth': 6, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.2751094610735481, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24643065427838096
Fold 2 IBS: 0.23223464296746826
Fold 3 IBS: 0.22968175844773792
Fold 4 IBS: 0.2413651638178947
Fold 5 IBS: 0.23015719969071047
[I 2024-04-13 17:10:12,872] Trial 49 finished with value: 0.23597388384043844 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 406, 'oob_score': True, 'max_samples': 0.3426311861680858, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.37411897805446126}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23653547645771292
Fold 2 IBS: 0.23891649468883286
Fold 3 IBS: 0.22623605262377863
Fold 4 IBS: 0.23760952706404054
Fold 5 IBS: 0.21274600173139968
[I 2024-04-13 17:10:14,869] Trial 50 finished with value: 0.23040871051315293 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 14, 'n_estimators': 300, 'oob_score': False, 'max_samples': 0.91240298039898, 'max_features': None, 'min_weight_fraction_leaf': 0.0023139662763776523}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23205733305111126
Fold 2 IBS: 0.22540170926715883
Fold 3 IBS: 0.21136019029919015
Fold 4 IBS: 0.2235188735459925
Fold 5 IBS: 0.2104011228556449
[I 2024-04-13 17:10:17,874] Trial 51 finished with value: 0.22054784580381953 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 8, 'n_estimators': 365, 'oob_score': True, 'max_samples': 0.28310200045220396, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.018168221852795943}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2467425883724255
Fold 2 IBS: 0.23229207390802017
Fold 3 IBS: 0.229806458577059
Fold 4 IBS: 0.24117087537338566
Fold 5 IBS: 0.23029838496464933
[I 2024-04-13 17:10:21,165] Trial 52 finished with value: 0.23606207623910797 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.31519339436661903, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.23722810776929834}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23448850473409952
Fold 2 IBS: 0.22628680170858836
Fold 3 IBS: 0.2110553567502054
Fold 4 IBS: 0.2248272006707438
Fold 5 IBS: 0.21045438124734223
[I 2024-04-13 17:10:25,275] Trial 53 finished with value: 0.22142244902219588 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 343, 'oob_score': True, 'max_samples': 0.25208751122540896, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.028071010742289564}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2457543637764612
Fold 2 IBS: 0.23215641755689168
Fold 3 IBS: 0.23000347609635255
Fold 4 IBS: 0.24126499095998308
Fold 5 IBS: 0.2304832070970648
[I 2024-04-13 17:10:29,505] Trial 54 finished with value: 0.23593249109735065 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 431, 'oob_score': True, 'max_samples': 0.1944118385287112, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00865239972784028}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2468623556579978
Fold 2 IBS: 0.23219151424480894
Fold 3 IBS: 0.23027924136404326
Fold 4 IBS: 0.24093725814526556
Fold 5 IBS: 0.22930915051617384
[I 2024-04-13 17:10:32,283] Trial 55 finished with value: 0.23591590398565784 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 275, 'oob_score': True, 'max_samples': 0.10569714025611779, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.058450491403396476}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24642872356499093
Fold 2 IBS: 0.23205942594736154
Fold 3 IBS: 0.22994434058519342
Fold 4 IBS: 0.24150107878356789
Fold 5 IBS: 0.23008272411407127
[I 2024-04-13 17:10:32,775] Trial 56 finished with value: 0.23600325859903698 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 51, 'oob_score': False, 'max_samples': 0.569633571031224, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.28766369733548897}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2464642877720641
Fold 2 IBS: 0.23233994540501388
Fold 3 IBS: 0.22968667048933009
Fold 4 IBS: 0.24135786670781292
Fold 5 IBS: 0.23035458313442783
[I 2024-04-13 17:10:34,817] Trial 57 finished with value: 0.2360406707017298 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 215, 'oob_score': True, 'max_samples': 0.40454378901615895, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.23177764488631825}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23328570910599059
Fold 2 IBS: 0.22482997301632762
Fold 3 IBS: 0.21090048079749318
Fold 4 IBS: 0.2254130957827992
Fold 5 IBS: 0.21047905455719065
[I 2024-04-13 17:10:37,568] Trial 58 finished with value: 0.2209816626519603 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 355, 'oob_score': False, 'max_samples': 0.4555194020493191, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.045806106324310286}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24638937856742066
Fold 2 IBS: 0.23217903444274132
Fold 3 IBS: 0.22957970746983006
Fold 4 IBS: 0.24149329059953806
Fold 5 IBS: 0.23023771602212853
[I 2024-04-13 17:10:40,276] Trial 59 finished with value: 0.23597582542033174 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.6547993209148422, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3347027531859703}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2306118363998221
Fold 2 IBS: 0.22306141635246116
Fold 3 IBS: 0.21072669348877712
Fold 4 IBS: 0.22625181384713736
Fold 5 IBS: 0.21133732898704416
[I 2024-04-13 17:10:44,177] Trial 60 finished with value: 0.22039781781504839 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 478, 'oob_score': True, 'max_samples': 0.48271442117986096, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.178446120167478}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2311701429638268
Fold 2 IBS: 0.22477774454018215
Fold 3 IBS: 0.21109067313133456
Fold 4 IBS: 0.22467051654837508
Fold 5 IBS: 0.2120682587473275
[I 2024-04-13 17:10:48,558] Trial 61 finished with value: 0.22075546718620923 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 477, 'oob_score': True, 'max_samples': 0.5026627705946465, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14529793469682825}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2461928599463436
Fold 2 IBS: 0.23221691568783104
Fold 3 IBS: 0.22947567562670096
Fold 4 IBS: 0.24151671023331148

Fold 5 IBS: 0.23018854152461504
[I 2024-04-13 17:10:53,195] Trial 62 finished with value: 0.23591814060376043 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.4677262455345284, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2827349986373208}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24652405780792855
Fold 2 IBS: 0.2322152403880562
Fold 3 IBS: 0.22946718005561817
Fold 4 IBS: 0.2414651127800749
Fold 5 IBS: 0.23031058287471998
[I 2024-04-13 17:10:57,861] Trial 63 finished with value: 0.23599643478127957 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 499, 'oob_score': True, 'max_samples': 0.36524236153301975, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.19147391488941964}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23373423023692633
Fold 2 IBS: 0.22521393950806748
Fold 3 IBS: 0.2191306507991317
Fold 4 IBS: 0.23014767984329243
Fold 5 IBS: 0.22006146132051893
[I 2024-04-13 17:11:01,867] Trial 64 finished with value: 0.2256575923415874 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 426, 'oob_score': True, 'max_samples': 0.341317344596171, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.024163948190701435}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23110813901378655
Fold 2 IBS: 0.22625593796332996
Fold 3 IBS: 0.21344254276833136
Fold 4 IBS: 0.22403890746089866
Fold 5 IBS: 0.21112293233311893
[I 2024-04-13 17:11:06,670] Trial 65 finished with value: 0.2211936919078931 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 484, 'oob_score': True, 'max_samples': 0.4293920185141239, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10772017538104399}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23510485461556999
Fold 2 IBS: 0.2248386961406159
Fold 3 IBS: 0.20438305318368702
Fold 4 IBS: 0.22161474102841908
Fold 5 IBS: 0.20865703395071367
[I 2024-04-13 17:11:11,969] Trial 66 finished with value: 0.2189196757838011 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.7277222032902713, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00012424788420031775}. Best is trial 66 with value: 0.2189196757838011.
Fold 1 IBS: 0.23501226850054138
Fold 2 IBS: 0.22471431254299942
Fold 3 IBS: 0.20593000096178582
Fold 4 IBS: 0.22343494979422188
Fold 5 IBS: 0.20949072806237073
[I 2024-04-13 17:11:16,026] Trial 67 finished with value: 0.21971645197238385 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.7290936220221548, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07569575991727365}. Best is trial 66 with value: 0.2189196757838011.
Fold 1 IBS: 0.23233804701309263
Fold 2 IBS: 0.22733944531132327
Fold 3 IBS: 0.2130366337153433
Fold 4 IBS: 0.22697606576675997
Fold 5 IBS: 0.21055795261271074
[I 2024-04-13 17:11:20,174] Trial 68 finished with value: 0.222049628883846 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 465, 'oob_score': False, 'max_samples': 0.738982857579614, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17948323116159026}. Best is trial 66 with value: 0.2189196757838011.
Fold 1 IBS: 0.23738739866957145
Fold 2 IBS: 0.22468686012438713
Fold 3 IBS: 0.20171388324594125
Fold 4 IBS: 0.22142509500072
Fold 5 IBS: 0.20594012888505892
[I 2024-04-13 17:11:24,334] Trial 69 finished with value: 0.21823067318513573 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.7966473717734156, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.000754910732434978}. Best is trial 69 with value: 0.21823067318513573.
Fold 1 IBS: 0.23640466205485558
Fold 2 IBS: 0.22511627601864978
Fold 3 IBS: 0.20496467553113637
Fold 4 IBS: 0.22127678503888615
Fold 5 IBS: 0.20729334433212973
[I 2024-04-13 17:11:28,660] Trial 70 finished with value: 0.21901114859513152 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.7903378056871502, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0691368647018997}. Best is trial 69 with value: 0.21823067318513573.
Fold 1 IBS: 0.23750818984851968
Fold 2 IBS: 0.22426265927695213
Fold 3 IBS: 0.2016674228960865
Fold 4 IBS: 0.2211677375711476
Fold 5 IBS: 0.20609431335638406
[I 2024-04-13 17:11:31,979] Trial 71 finished with value: 0.21814006458981802 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.785271119394671, 'max_features': 'log2', 'min_weight_fraction_leaf': 8.074256882937306e-05}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23838492585055007
Fold 2 IBS: 0.22507214558163305
Fold 3 IBS: 0.20143767144413025
Fold 4 IBS: 0.22268918756548908
Fold 5 IBS: 0.2068563072044347
[I 2024-04-13 17:11:35,546] Trial 72 finished with value: 0.2188880475292474 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.8036876381737409, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0015918352811246476}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23843558191669362
Fold 2 IBS: 0.22493582433312012
Fold 3 IBS: 0.20129183641750387
Fold 4 IBS: 0.22279078455344045
Fold 5 IBS: 0.20681700555549176
[I 2024-04-13 17:11:39,144] Trial 73 finished with value: 0.21885420655524995 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.7999498893948669, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0005099629334644618}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23664162395062918
Fold 2 IBS: 0.2241356454982757
Fold 3 IBS: 0.20519783897054078
Fold 4 IBS: 0.22110736731436786
Fold 5 IBS: 0.2073382645860624
[I 2024-04-13 17:11:42,272] Trial 74 finished with value: 0.21888414806397516 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.8194617003412593, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0712695999375732}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23537805440745527
Fold 2 IBS: 0.22434344368362777
Fold 3 IBS: 0.20738548248880273
Fold 4 IBS: 0.22180433731709842
Fold 5 IBS: 0.20889031390025767
[I 2024-04-13 17:11:45,726] Trial 75 finished with value: 0.21956032635944833 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.8133524942001209, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08127549167715468}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23545525573147905
Fold 2 IBS: 0.22153659942623385
Fold 3 IBS: 0.2075449303933778
Fold 4 IBS: 0.2231528926555171
Fold 5 IBS: 0.2079749514693718
[I 2024-04-13 17:11:49,128] Trial 76 finished with value: 0.2191329259351959 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 405, 'oob_score': False, 'max_samples': 0.8231686578176318, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05240500541214905}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23575461528483777
Fold 2 IBS: 0.22187847432867439
Fold 3 IBS: 0.20868891108618615
Fold 4 IBS: 0.22380403297644932
Fold 5 IBS: 0.2079961384411151
[I 2024-04-13 17:11:52,753] Trial 77 finished with value: 0.21962443442345253 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 406, 'oob_score': False, 'max_samples': 0.8554946968969933, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.052809045001292264}. Best is trial 71 with value: 0.21814006458981802.

Fold 1 IBS: 0.24217247193439537
Fold 2 IBS: 0.2278793635566358
Fold 3 IBS: 0.20080078124083145
Fold 4 IBS: 0.22310960096298033
Fold 5 IBS: 0.2079672399605948
[I 2024-04-13 17:11:56,152] Trial 78 finished with value: 0.22038589153108754 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 418, 'oob_score': False, 'max_samples': 0.7742508336660989, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.033857990321958055}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2355555064593619
Fold 2 IBS: 0.22224942419207222
Fold 3 IBS: 0.20877935998830383
Fold 4 IBS: 0.22444536984656233
Fold 5 IBS: 0.2081228365598182
[I 2024-04-13 17:11:59,557] Trial 79 finished with value: 0.21983049940922367 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.8561349620215079, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0005195865801855532}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.24241429583579838
Fold 2 IBS: 0.22789447806360993
Fold 3 IBS: 0.20467685675034264
Fold 4 IBS: 0.22288907337161928
Fold 5 IBS: 0.20750330171816853
[I 2024-04-13 17:12:02,883] Trial 80 finished with value: 0.22107560114790772 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.7908246314613915, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04549184809342783}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23643091434190627
Fold 2 IBS: 0.2245035140221752
Fold 3 IBS: 0.2054229767526827
Fold 4 IBS: 0.22079340395882704
Fold 5 IBS: 0.20720357309992168
[I 2024-04-13 17:12:06,373] Trial 81 finished with value: 0.2188708764351026 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.82389908631297, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06682100879850736}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23784943286734053
Fold 2 IBS: 0.22299626441699782
Fold 3 IBS: 0.2051875205309834
Fold 4 IBS: 0.2219151954315832
Fold 5 IBS: 0.20639160499029274
[I 2024-04-13 17:12:10,849] Trial 82 finished with value: 0.21886800364743958 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 433, 'oob_score': False, 'max_samples': 0.907696191161797, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0649269059958972}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23481648213378556
Fold 2 IBS: 0.22399470395223586
Fold 3 IBS: 0.20839589700096056
Fold 4 IBS: 0.2246777750739523
Fold 5 IBS: 0.21000594947142526
[I 2024-04-13 17:12:15,098] Trial 83 finished with value: 0.22037816152647194 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.9163341718713127, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12259108267136748}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2334939533679607
Fold 2 IBS: 0.22607705247059665
Fold 3 IBS: 0.20757402674496309
Fold 4 IBS: 0.22531097361703065
Fold 5 IBS: 0.2109776338102316
[I 2024-04-13 17:12:19,852] Trial 84 finished with value: 0.22068672800215655 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.6964735539602778, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0983502057538686}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.24168961801227365
Fold 2 IBS: 0.22720531732946742
Fold 3 IBS: 0.2073627488337626
Fold 4 IBS: 0.22321443955217113
Fold 5 IBS: 0.20933627466281343
[I 2024-04-13 17:12:25,420] Trial 85 finished with value: 0.22176167967809762 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.8852611846969818, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06716376200543844}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2501102112818779
Fold 2 IBS: 0.23109915986172933
Fold 3 IBS: 0.2015627722369633
Fold 4 IBS: 0.22179451257247865
Fold 5 IBS: 0.21066046744033398
[I 2024-04-13 17:12:30,935] Trial 86 finished with value: 0.2230454246786766 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 471, 'oob_score': False, 'max_samples': 0.9556515545432857, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.032457057200294154}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23570787321457648
Fold 2 IBS: 0.22130640184705208
Fold 3 IBS: 0.2058533403920595
Fold 4 IBS: 0.2271720358186151
Fold 5 IBS: 0.20822086095930034
[I 2024-04-13 17:12:35,483] Trial 87 finished with value: 0.21965210244632072 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 486, 'oob_score': False, 'max_samples': 0.8392358634429405, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012615689337359539}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23506041233177796
Fold 2 IBS: 0.22676854768655463
Fold 3 IBS: 0.21426008705017613
Fold 4 IBS: 0.22869053791418748
Fold 5 IBS: 0.21289985376952034
[I 2024-04-13 17:12:39,745] Trial 88 finished with value: 0.22353588775044334 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.8803049631865397, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14660532598550163}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23714953265947813
Fold 2 IBS: 0.22436316613074966
Fold 3 IBS: 0.2020631925894465
Fold 4 IBS: 0.22124274581523004
Fold 5 IBS: 0.20620465624668038
[I 2024-04-13 17:12:44,054] Trial 89 finished with value: 0.21820465868831693 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 456, 'oob_score': False, 'max_samples': 0.7896846867879517, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03627962366130027}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23580014606596647
Fold 2 IBS: 0.2218875639554552
Fold 3 IBS: 0.20867976067748017
Fold 4 IBS: 0.22627294211995028
Fold 5 IBS: 0.20840927695622002
[I 2024-04-13 17:12:49,481] Trial 90 finished with value: 0.22020993795501442 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 463, 'oob_score': False, 'max_samples': 0.93720899494118, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03869745358932866}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2354589984552326
Fold 2 IBS: 0.22524001219031592
Fold 3 IBS: 0.20569095963108802
Fold 4 IBS: 0.22140761560731112
Fold 5 IBS: 0.20777808554956137
[I 2024-04-13 17:12:53,836] Trial 91 finished with value: 0.2191151342867018 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 452, 'oob_score': False, 'max_samples': 0.7965806938790612, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06322946729450632}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.24160797692372046
Fold 2 IBS: 0.22877573588171754
Fold 3 IBS: 0.20349956847846673
Fold 4 IBS: 0.22172366432250362
Fold 5 IBS: 0.20728746219361785
[I 2024-04-13 17:12:57,795] Trial 92 finished with value: 0.22057888156000524 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.7550788603038648, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01093866522527464}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23805383943188022
Fold 2 IBS: 0.22443950723251976
Fold 3 IBS: 0.20085521312077026
Fold 4 IBS: 0.22152045897596737

Fold 5 IBS: 0.2069805372099246
[I 2024-04-13 17:13:02,085] Trial 93 finished with value: 0.21836991119421248 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 436, 'oob_score': False, 'max_samples': 0.7876680525303928, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02818336790921719}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2481959844323671
Fold 2 IBS: 0.23173657169109757
Fold 3 IBS: 0.20201510994966232
Fold 4 IBS: 0.22255626189257152
Fold 5 IBS: 0.21061654425734486
[I 2024-04-13 17:13:06,288] Trial 94 finished with value: 0.22302409444460863 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 436, 'oob_score': False, 'max_samples': 0.8362507108284499, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.027504161893380293}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23915650996574608
Fold 2 IBS: 0.2234245394350635
Fold 3 IBS: 0.21293758807164273
Fold 4 IBS: 0.23523772004345975
Fold 5 IBS: 0.21283134069782997
[I 2024-04-13 17:13:10,647] Trial 95 finished with value: 0.2247175396427484 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.8837943797775261, 'max_features': None, 'min_weight_fraction_leaf': 0.012755690371205977}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23636458888864972
Fold 2 IBS: 0.22548005093935128
Fold 3 IBS: 0.20289781330297618
Fold 4 IBS: 0.22194388354495065
Fold 5 IBS: 0.20659782587399886
[I 2024-04-13 17:13:16,074] Trial 96 finished with value: 0.2186568325099853 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.7047963450216371, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.042649479114857974}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2368435830144382
Fold 2 IBS: 0.22787196721859507
Fold 3 IBS: 0.21053102229260984
Fold 4 IBS: 0.22497427988410976
Fold 5 IBS: 0.21388075327377432
[I 2024-04-13 17:13:20,858] Trial 97 finished with value: 0.2228203211367054 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 391, 'oob_score': False, 'max_samples': 0.695234381023326, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08812518101550153}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23461443359372502
Fold 2 IBS: 0.22206420895541035
Fold 3 IBS: 0.20600949221006296
Fold 4 IBS: 0.2225105168375799
Fold 5 IBS: 0.20798613510831773
[I 2024-04-13 17:13:26,088] Trial 98 finished with value: 0.21863695734101918 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 429, 'oob_score': False, 'max_samples': 0.7518465351355723, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04566737589752622}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23487790054634475
Fold 2 IBS: 0.22192356266132915
Fold 3 IBS: 0.206872333232792
Fold 4 IBS: 0.22206365342237452
Fold 5 IBS: 0.20811521327808374
[I 2024-04-13 17:13:31,136] Trial 99 finished with value: 0.21877053262818486 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 426, 'oob_score': False, 'max_samples': 0.7658401698686866, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04554148579618334}. Best is trial 71 with value: 0.21814006458981802.


* Best trial for IBS:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.21814006458981802], datetime_start=datetime.datetime(2024, 4, 13, 17, 11, 28, 671982), datetime_complete=datetime.datetime(2024, 4, 13, 17, 11, 31, 978854), params={'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.785271119394671, 'max_features': 'log2', 'min_weight_fraction_leaf': 8.074256882937306e-05}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=71, value=None)


* Best Score for IBS:
 0.21814006458981802

In [63]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [64]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.79
train_ibs:  0.218

#### Test

In [65]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [66]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=20, max_features='auto', max_leaf_nodes=12,
                     max_samples=0.9937352645069003, min_samples_leaf=1,
                     min_samples_split=5,
                     min_weight_fraction_leaf=0.014733302673387358,
                     n_estimators=435, random_state=123, warm_start=True)

test_cindex:  0.603

RandomSurvivalForest(max_depth=13, max_features='log2', max_leaf_nodes=3,
                     max_samples=0.785271119394671, min_samples_leaf=4,
                     min_samples_split=2,
                     min_weight_fraction_leaf=8.074256882937306e-05,
                     n_estimators=444, random_state=123)

test_ibs:  0.215

In [67]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [68]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [69]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:13:33,356] A new study created in memory with name: no-name-aac3f577-d5fc-403c-ba2e-77712697c30e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7382978723404255
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6909871244635193
[I 2024-04-13 17:13:34,352] Trial 0 finished with value: 0.6851000777443397 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:13:36,927] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.674468085106383
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:13:41,375] Trial 2 finished with value: 0.6471738109279814 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.647410358565737
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 17:13:41,794] Trial 3 finished with value: 0.6721233889975948 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:13:43,488] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:13:45,408] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:13:46,452] Trial 6 finished with value: 0.6775544862150437 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.575107296137339
[I 2024-04-13 17:13:48,820] Trial 7 finished with value: 0.6410571220283957 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:13:49,005] Trial 8 finished with value: 0.6602715482412723 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:13:54,734] Trial 9 finished with value: 0.6387388839144454 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:13:56,856] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6155378486055777
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 17:13:57,827] Trial 11 finished with value: 0.6702180836908557 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6995708154506438
[I 2024-04-13 17:13:59,066] Trial 12 finished with value: 0.6881534529891422 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 17:14:00,314] Trial 13 finished with value: 0.6646828847295456 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6298449612403101
Fold 3 C-index: 0.7
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 17:14:01,361] Trial 14 finished with value: 0.6594415746090991 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6158798283261803
[I 2024-04-13 17:14:02,105] Trial 15 finished with value: 0.6707959967448854 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.6881534529891422.

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.6977186311787072
Fold 5 C-index: 0.6094420600858369
[I 2024-04-13 17:14:03,342] Trial 16 finished with value: 0.656032749497523 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.5717131474103586
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7510638297872341
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:14:04,173] Trial 17 finished with value: 0.6664734494891689 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:14:05,523] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6502145922746781
[I 2024-04-13 17:14:06,492] Trial 19 finished with value: 0.6644257554322603 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 17:14:06,643] Trial 20 finished with value: 0.6567802711331774 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 17:14:07,718] Trial 21 finished with value: 0.6792348679372288 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6824034334763949
[I 2024-04-13 17:14:08,997] Trial 22 finished with value: 0.686029107776449 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6866952789699571
[I 2024-04-13 17:14:10,293] Trial 23 finished with value: 0.6906324467750945 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6180257510729614
[I 2024-04-13 17:14:11,435] Trial 24 finished with value: 0.6711203403150813 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7017167381974249
[I 2024-04-13 17:14:12,534] Trial 25 finished with value: 0.6858499860979521 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.572961373390558
[I 2024-04-13 17:14:17,697] Trial 26 finished with value: 0.6413704991472602 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6569767441860465
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 17:14:18,922] Trial 27 finished with value: 0.675049805218149 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.5836653386454184
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.7042553191489361
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.6673819742489271
[I 2024-04-13 17:14:19,665] Trial 28 finished with value: 0.6584670168145277 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6354581673306773
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 17:14:20,299] Trial 29 finished with value: 0.655897752553135 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6763565891472868
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 17:14:21,221] Trial 30 finished with value: 0.6821700950953665 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.6906324467750945.

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7017167381974249
[I 2024-04-13 17:14:22,182] Trial 31 finished with value: 0.6850747922995026 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6357896182918609, 'min_weight_fraction_leaf': 0.043457520259011145}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 17:14:23,491] Trial 32 finished with value: 0.6748268325865853 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.48963031975436294, 'min_weight_fraction_leaf': 0.054624644214656966}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6414728682170543
Fold 3 C-index: 0.7297872340425532
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 17:14:25,047] Trial 33 finished with value: 0.6546886869454311 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.527493679418052, 'min_weight_fraction_leaf': 0.11101292483370524}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 17:14:26,432] Trial 34 finished with value: 0.6855672055264954 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9202590430146967, 'min_weight_fraction_leaf': 0.07949057080337707}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 17:14:29,439] Trial 35 finished with value: 0.6957388726363694 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 474, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.678814039070356, 'min_weight_fraction_leaf': 0.028560781966745094}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.625968992248062
Fold 3 C-index: 0.674468085106383
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6008583690987125
[I 2024-04-13 17:14:36,003] Trial 36 finished with value: 0.6460431015306448 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 487, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7202769479752608, 'min_weight_fraction_leaf': 0.1272251175690979}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6531007751937985
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:14:38,468] Trial 37 finished with value: 0.6535992249876296 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 466, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8198785636142412, 'min_weight_fraction_leaf': 0.029014014591284436}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6337209302325582
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 17:14:40,951] Trial 38 finished with value: 0.655251518254536 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 437, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.002361340929773935}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.6787072243346007
Fold 5 C-index: 0.6180257510729614
[I 2024-04-13 17:14:45,757] Trial 39 finished with value: 0.645723528384093 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 397, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7691351859887788, 'min_weight_fraction_leaf': 0.06720870867946066}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:14:48,405] Trial 40 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 344, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5982912816250927, 'min_weight_fraction_leaf': 0.4492877633512613}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 17:14:49,943] Trial 41 finished with value: 0.6880044461642689 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6598304746211209, 'min_weight_fraction_leaf': 0.053447973833735035}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7510638297872341
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7081545064377682
[I 2024-04-13 17:14:53,088] Trial 42 finished with value: 0.7030860499704138 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 473, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5313336913856148, 'min_weight_fraction_leaf': 0.025352461449765364}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:14:56,340] Trial 43 finished with value: 0.679926602167664 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 482, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5364184962117242, 'min_weight_fraction_leaf': 0.05972934366832378}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:14:59,368] Trial 44 finished with value: 0.6845185041435788 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.687551258169526, 'min_weight_fraction_leaf': 0.09604207143003154}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7425531914893617
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.723175965665236
[I 2024-04-13 17:15:00,292] Trial 45 finished with value: 0.6928271133771465 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 144, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5586473886674701, 'min_weight_fraction_leaf': 0.021758007763963413}. Best is trial 42 with value: 0.7030860499704138.

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 17:15:01,275] Trial 46 finished with value: 0.6806840283474052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 138, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.4276865318481037, 'min_weight_fraction_leaf': 0.017191498668975277}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6298449612403101
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.6863117870722434
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 17:15:02,803] Trial 47 finished with value: 0.6406747019951217 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 93, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.36005786284820956, 'min_weight_fraction_leaf': 0.022894100109012182}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7124463519313304
[I 2024-04-13 17:15:04,251] Trial 48 finished with value: 0.6975026836324872 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 223, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.94082830351897, 'min_weight_fraction_leaf': 0.0031941216647066936}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:15:05,634] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 212, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5011407247227364, 'min_weight_fraction_leaf': 0.358441712753887}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6453488372093024
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 17:15:06,845] Trial 50 finished with value: 0.6804367470765946 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 171, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9312077054760161, 'min_weight_fraction_leaf': 0.12266310822518021}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 17:15:08,025] Trial 51 finished with value: 0.6746377989463979 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 170, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.957889367228467, 'min_weight_fraction_leaf': 0.0007314361594816486}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.759656652360515
[I 2024-04-13 17:15:09,494] Trial 52 finished with value: 0.7033308262791091 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 242, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8076761414867076, 'min_weight_fraction_leaf': 0.02370651531262462}. Best is trial 52 with value: 0.7033308262791091.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 17:15:10,761] Trial 53 finished with value: 0.6854416959540812 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 195, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7882374110234983, 'min_weight_fraction_leaf': 0.07355615073523727}. Best is trial 52 with value: 0.7033308262791091.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6995708154506438
[I 2024-04-13 17:15:12,223] Trial 54 finished with value: 0.6912653578936234 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 236, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8462634635234857, 'min_weight_fraction_leaf': 0.027695920994629177}. Best is trial 52 with value: 0.7033308262791091.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8068669527896996
[I 2024-04-13 17:15:13,783] Trial 55 finished with value: 0.7304019052983591 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 237, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8431949607994742, 'min_weight_fraction_leaf': 0.019689561001487742}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6995708154506438
[I 2024-04-13 17:15:15,433] Trial 56 finished with value: 0.6852121772640821 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 288, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8359750908740874, 'min_weight_fraction_leaf': 0.09275039490290456}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7339055793991416
[I 2024-04-13 17:15:16,942] Trial 57 finished with value: 0.7080313014605807 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 278, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.912592990524893, 'min_weight_fraction_leaf': 0.0210885099116659}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.6354581673306773
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 17:15:18,443] Trial 58 finished with value: 0.6555053283777668 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 292, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9091926669480035, 'min_weight_fraction_leaf': 0.2526413207446905}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5515021459227468
[I 2024-04-13 17:15:21,218] Trial 59 finished with value: 0.612482459269093 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 235, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.943040394432692, 'min_weight_fraction_leaf': 0.040329046437081434}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6995708154506438
[I 2024-04-13 17:15:22,601] Trial 60 finished with value: 0.6883778093095436 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 275, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.879697866755957, 'min_weight_fraction_leaf': 0.055451281420183546}. Best is trial 55 with value: 0.7304019052983591.

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7553191489361702
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7081545064377682
[I 2024-04-13 17:15:23,501] Trial 61 finished with value: 0.6882180229986123 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 131, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.801988873777292, 'min_weight_fraction_leaf': 0.017439688996287176}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7360515021459227
[I 2024-04-13 17:15:24,004] Trial 62 finished with value: 0.7109694649252425 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 79, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8617770804754492, 'min_weight_fraction_leaf': 0.014415763584492182}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7317596566523605
[I 2024-04-13 17:15:24,407] Trial 63 finished with value: 0.7183475356629161 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 59, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8664901703822724, 'min_weight_fraction_leaf': 0.0002705850447878577}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8133047210300429
[I 2024-04-13 17:15:24,983] Trial 64 finished with value: 0.7483307845911831 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 54, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8662742964997368, 'min_weight_fraction_leaf': 0.0017689713740798967}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6957364341085271
Fold 3 C-index: 0.7510638297872341
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7060085836909872
[I 2024-04-13 17:15:25,814] Trial 65 finished with value: 0.6998208548490268 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 61, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9996385846525305, 'min_weight_fraction_leaf': 0.04725744918321939}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:15:26,100] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 9, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8621588892289783, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5796812749003984
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6716738197424893
[I 2024-04-13 17:15:26,496] Trial 67 finished with value: 0.6849489036736089 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 36, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8924168531245312, 'min_weight_fraction_leaf': 0.07024991347750792}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.6075697211155379
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.7382978723404255
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 17:15:27,192] Trial 68 finished with value: 0.6860272317441234 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 94, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7570760952920621, 'min_weight_fraction_leaf': 0.08592463964216505}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7661596958174905
Fold 5 C-index: 0.6759656652360515
[I 2024-04-13 17:15:27,694] Trial 69 finished with value: 0.6949112962080065 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 62, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9037622964369387, 'min_weight_fraction_leaf': 0.014330365794333477}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6909871244635193
[I 2024-04-13 17:15:28,045] Trial 70 finished with value: 0.6910631381543316 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 34, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8093114050677033, 'min_weight_fraction_leaf': 0.03979626985401667}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6724806201550387
Fold 3 C-index: 0.7425531914893617
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7017167381974249
[I 2024-04-13 17:15:28,636] Trial 71 finished with value: 0.6957600898208183 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 70, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9952461586716469, 'min_weight_fraction_leaf': 0.05244870419935619}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8154506437768241
[I 2024-04-13 17:15:29,358] Trial 72 finished with value: 0.732867519325721 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 117, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9729286202250643, 'min_weight_fraction_leaf': 0.0007501905752557436}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 17:15:30,376] Trial 73 finished with value: 0.7128904943815512 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 116, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9537142578281173, 'min_weight_fraction_leaf': 0.012418975853445025}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7467811158798283
[I 2024-04-13 17:15:31,288] Trial 74 finished with value: 0.7191746692395198 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9697396627525858, 'min_weight_fraction_leaf': 0.011122539757406865}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7965779467680608
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 17:15:32,210] Trial 75 finished with value: 0.7129593862942667 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 117, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9611088438541834, 'min_weight_fraction_leaf': 0.00026629033599147274}. Best is trial 64 with value: 0.7483307845911831.

Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.5643776824034334
[I 2024-04-13 17:15:34,095] Trial 76 finished with value: 0.6073724889462218 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 108, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9582643703114411, 'min_weight_fraction_leaf': 0.015367528693973603}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7424892703862661
[I 2024-04-13 17:15:34,912] Trial 77 finished with value: 0.7128288110450078 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 126, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9494217636188305, 'min_weight_fraction_leaf': 0.0016737005937686057}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8111587982832618
[I 2024-04-13 17:15:35,692] Trial 78 finished with value: 0.7319548991462254 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 123, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9642227434197009, 'min_weight_fraction_leaf': 0.0021058685030657335}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7553191489361702
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 17:15:36,448] Trial 79 finished with value: 0.6999093844652243 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 117, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9695872781720767, 'min_weight_fraction_leaf': 0.03777743761503083}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.7103004291845494
[I 2024-04-13 17:15:37,337] Trial 80 finished with value: 0.6889680415739856 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 159, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9748962504778398, 'min_weight_fraction_leaf': 0.06439560013397327}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7424892703862661
[I 2024-04-13 17:15:38,153] Trial 81 finished with value: 0.7112568044975542 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 124, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9489094481266604, 'min_weight_fraction_leaf': 0.00837226306600549}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7489270386266095
[I 2024-04-13 17:15:38,853] Trial 82 finished with value: 0.7151598166699424 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 103, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8869701624411807, 'min_weight_fraction_leaf': 0.0009826312409484343}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.703862660944206
[I 2024-04-13 17:15:39,476] Trial 83 finished with value: 0.70260361739942 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 91, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9252815070211524, 'min_weight_fraction_leaf': 0.034454055596569985}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 17:15:40,232] Trial 84 finished with value: 0.664443908687675 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 19, 'n_estimators': 108, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8873964455419806, 'min_weight_fraction_leaf': 0.0001876274131405089}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.725531914893617
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 17:15:41,149] Trial 85 finished with value: 0.6873669920373484 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 151, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9765072725804504, 'min_weight_fraction_leaf': 0.013004742095931136}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6716738197424893
[I 2024-04-13 17:15:41,678] Trial 86 finished with value: 0.6868914200866229 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 78, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8698782711480478, 'min_weight_fraction_leaf': 0.03289779563895275}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6995708154506438
[I 2024-04-13 17:15:42,115] Trial 87 finished with value: 0.6948891539842074 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 50, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8345993194987964, 'min_weight_fraction_leaf': 0.051343068837458844}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.5910852713178295
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.5579399141630901
[I 2024-04-13 17:15:44,474] Trial 88 finished with value: 0.6097028070712147 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 194, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.924420980029357, 'min_weight_fraction_leaf': 0.010350197621313917}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6337209302325582
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.6749049429657795
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 17:15:44,724] Trial 89 finished with value: 0.6469835494137881 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 16, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9991858125788121, 'min_weight_fraction_leaf': 0.28976495050632306}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8175965665236051
[I 2024-04-13 17:15:45,684] Trial 90 finished with value: 0.729087779708108 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 168, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9119141145095422, 'min_weight_fraction_leaf': 0.03045835615518719}. Best is trial 64 with value: 0.7483307845911831.

Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8261802575107297
[I 2024-04-13 17:15:46,666] Trial 91 finished with value: 0.7301061688113683 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 172, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8965986548546552, 'min_weight_fraction_leaf': 0.032382398081057265}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6453488372093024
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 17:15:47,678] Trial 92 finished with value: 0.6654765723248192 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 175, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.25077855422842626, 'min_weight_fraction_leaf': 0.030475090955934078}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7808510638297872
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8218884120171673
[I 2024-04-13 17:15:48,694] Trial 93 finished with value: 0.723349516226648 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 184, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9007665079653875, 'min_weight_fraction_leaf': 0.04421727446740081}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8347639484978541
[I 2024-04-13 17:15:49,665] Trial 94 finished with value: 0.721176946423143 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 178, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.904130167714226, 'min_weight_fraction_leaf': 0.047285012436125234}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.7145922746781116
[I 2024-04-13 17:15:50,666] Trial 95 finished with value: 0.6926264721782838 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 184, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8559824051953817, 'min_weight_fraction_leaf': 0.10749281596606977}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7893617021276595
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.8369098712446352
[I 2024-04-13 17:15:51,603] Trial 96 finished with value: 0.7234863166632615 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 157, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9080663630381983, 'min_weight_fraction_leaf': 0.04614615882777642}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7553648068669528
[I 2024-04-13 17:15:52,550] Trial 97 finished with value: 0.7052353107898245 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 158, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9058530674494015, 'min_weight_fraction_leaf': 0.07474995134491569}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7680851063829788
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.7145922746781116
[I 2024-04-13 17:15:53,700] Trial 98 finished with value: 0.6808130386420753 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 205, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9313032187014408, 'min_weight_fraction_leaf': 0.16576392984791938}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.6937984496124031

[I 2024-04-13 17:15:54,685] A new study created in memory with name: no-name-1b37cec7-a4ca-4ff8-9e86-49d16a744dea

Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8240343347639485
[I 2024-04-13 17:15:54,675] Trial 99 finished with value: 0.7281519399606781 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 144, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9026987353436134, 'min_weight_fraction_leaf': 0.044978112106174015}. Best is trial 64 with value: 0.7483307845911831.


* Best trial for C-index:
 FrozenTrial(number=64, state=TrialState.COMPLETE, values=[0.7483307845911831], datetime_start=datetime.datetime(2024, 4, 13, 17, 15, 24, 425058), datetime_complete=datetime.datetime(2024, 4, 13, 17, 15, 24, 982932), params={'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 54, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8662742964997368, 'min_weight_fraction_leaf': 0.0017689713740798967}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=64, value=None)


* Best Score for C-index:
 0.7483307845911831

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23871639392045876
Fold 2 IBS: 0.22089740641981764
Fold 3 IBS: 0.20855935712684537
Fold 4 IBS: 0.22380699271581075
Fold 5 IBS: 0.20613806594659023
[I 2024-04-13 17:15:58,262] Trial 0 finished with value: 0.21962364322590452 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-13 17:16:03,236] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.2374084409354485
Fold 2 IBS: 0.21892351729489093
Fold 3 IBS: 0.21059085303920796
Fold 4 IBS: 0.22616820231302934
Fold 5 IBS: 0.21204655703132755
[I 2024-04-13 17:16:07,459] Trial 2 finished with value: 0.22102751412278088 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.23741407895783967
Fold 2 IBS: 0.21927599702285203
Fold 3 IBS: 0.21030069175680202
Fold 4 IBS: 0.22586626034487578
Fold 5 IBS: 0.21193073251533748
[I 2024-04-13 17:16:08,893] Trial 3 finished with value: 0.2209575521195414 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-13 17:16:12,879] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-13 17:16:14,930] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.23795541765613862
Fold 2 IBS: 0.21992985069618104
Fold 3 IBS: 0.2077002925377932
Fold 4 IBS: 0.2240482117618494
Fold 5 IBS: 0.20618770446779255
[I 2024-04-13 17:16:19,582] Trial 6 finished with value: 0.21916429542395094 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.23973193218549388
Fold 2 IBS: 0.21988145192818526
Fold 3 IBS: 0.20667039410505023
Fold 4 IBS: 0.22443830719746974
Fold 5 IBS: 0.20774030799163096
[I 2024-04-13 17:16:22,732] Trial 7 finished with value: 0.21969247868156602 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.2351732133658275
Fold 2 IBS: 0.22119237000388278
Fold 3 IBS: 0.21167563307535375
Fold 4 IBS: 0.22835359884410014
Fold 5 IBS: 0.21499909110450102
[I 2024-04-13 17:16:23,357] Trial 8 finished with value: 0.22227878127873302 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.23678701345213632
Fold 2 IBS: 0.2224692190085653
Fold 3 IBS: 0.2128128925717937
Fold 4 IBS: 0.22932300899141547
Fold 5 IBS: 0.21680976991247256
[I 2024-04-13 17:16:30,179] Trial 9 finished with value: 0.22364038078727666 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.24645397072894554
Fold 2 IBS: 0.23215165796624326
Fold 3 IBS: 0.2300072528605466
Fold 4 IBS: 0.24106162740477477
Fold 5 IBS: 0.23037976132987092
[I 2024-04-13 17:16:35,015] Trial 10 finished with value: 0.23601085405807623 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.2407112632523052
Fold 2 IBS: 0.22449406567870364
Fold 3 IBS: 0.21923219608031602
Fold 4 IBS: 0.23410601748321572
Fold 5 IBS: 0.22172302798577018
[I 2024-04-13 17:16:38,796] Trial 11 finished with value: 0.22805331409606217 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.2426583592791501
Fold 2 IBS: 0.22250934168617267
Fold 3 IBS: 0.2073988772356009
Fold 4 IBS: 0.22320546282719067
Fold 5 IBS: 0.20374832919376581
[I 2024-04-13 17:16:43,738] Trial 12 finished with value: 0.219904074044376 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.23681056601352704
Fold 2 IBS: 0.21942788812788447
Fold 3 IBS: 0.20647992664043885
Fold 4 IBS: 0.2235208106455191
Fold 5 IBS: 0.20836329684199373
[I 2024-04-13 17:16:47,883] Trial 13 finished with value: 0.21892049765387264 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6381530978163132, 'min_weight_fraction_leaf': 0.10302250602390595}. Best is trial 13 with value: 0.21892049765387264.
Fold 1 IBS: 0.24709076537787542
Fold 2 IBS: 0.23229758763044567
Fold 3 IBS: 0.22965399450652796
Fold 4 IBS: 0.2411751364309486
Fold 5 IBS: 0.23019081700505956
[I 2024-04-13 17:16:50,803] Trial 14 finished with value: 0.23608166019017146 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3469585144995889, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 13 with value: 0.21892049765387264.

Fold 1 IBS: 0.2364263642187732
Fold 2 IBS: 0.21964078635235235
Fold 3 IBS: 0.20489859443298694
Fold 4 IBS: 0.22388210534010178
Fold 5 IBS: 0.2090644999060323
[I 2024-04-13 17:16:55,467] Trial 15 finished with value: 0.2187824700500493 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6285201358789383, 'min_weight_fraction_leaf': 0.19381386025401764}. Best is trial 15 with value: 0.2187824700500493.
Fold 1 IBS: 0.24660428287886507
Fold 2 IBS: 0.2321257226396559
Fold 3 IBS: 0.22935330291437783
Fold 4 IBS: 0.24160728594857112
Fold 5 IBS: 0.23025975275058844
[I 2024-04-13 17:16:57,453] Trial 16 finished with value: 0.2359900694264117 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 175, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6923965021963807, 'min_weight_fraction_leaf': 0.35612645124522524}. Best is trial 15 with value: 0.2187824700500493.
Fold 1 IBS: 0.23684403651136585
Fold 2 IBS: 0.21959841448705122
Fold 3 IBS: 0.2056560421573172
Fold 4 IBS: 0.2233658304235327
Fold 5 IBS: 0.20846802289450317
[I 2024-04-13 17:17:01,367] Trial 17 finished with value: 0.21878646929475404 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 386, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6497544745873196, 'min_weight_fraction_leaf': 0.18481627132564235}. Best is trial 15 with value: 0.2187824700500493.
Fold 1 IBS: 0.23687920380677704
Fold 2 IBS: 0.21931414244607947
Fold 3 IBS: 0.20607205787956004
Fold 4 IBS: 0.22297392805924535
Fold 5 IBS: 0.2081887101022801
[I 2024-04-13 17:17:06,042] Trial 18 finished with value: 0.2186856084587884 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 20, 'n_estimators': 306, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8990048819755062, 'min_weight_fraction_leaf': 0.2019796911225918}. Best is trial 18 with value: 0.2186856084587884.
Fold 1 IBS: 0.23948146297755277
Fold 2 IBS: 0.22291910324934316
Fold 3 IBS: 0.21703121250088622
Fold 4 IBS: 0.23627081582775644
Fold 5 IBS: 0.2207432460911561
[I 2024-04-13 17:17:07,698] Trial 19 finished with value: 0.22728916812933891 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 111, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8794499855344343, 'min_weight_fraction_leaf': 0.4027720168515806}. Best is trial 18 with value: 0.2186856084587884.
Fold 1 IBS: 0.23688471445852777
Fold 2 IBS: 0.21913272259306837
Fold 3 IBS: 0.2059111669673491
Fold 4 IBS: 0.22283459872246641
Fold 5 IBS: 0.20816131265171223
[I 2024-04-13 17:17:11,956] Trial 20 finished with value: 0.21858490307862474 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 311, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9051233789152774, 'min_weight_fraction_leaf': 0.2509729370060225}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.23689478020829297
Fold 2 IBS: 0.21939083507476845
Fold 3 IBS: 0.20544637636114435
Fold 4 IBS: 0.22331937617631895
Fold 5 IBS: 0.20823609391962125
[I 2024-04-13 17:17:15,944] Trial 21 finished with value: 0.2186574923480292 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 307, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8936004056067098, 'min_weight_fraction_leaf': 0.2584106737011842}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.23702655392249034
Fold 2 IBS: 0.21934691338037202
Fold 3 IBS: 0.20599414039818612
Fold 4 IBS: 0.2232183658358969
Fold 5 IBS: 0.20818608847087738
[I 2024-04-13 17:17:20,200] Trial 22 finished with value: 0.21875441240156457 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 315, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9078735647156028, 'min_weight_fraction_leaf': 0.25581625155530263}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.2370523143627765
Fold 2 IBS: 0.2196008201014214
Fold 3 IBS: 0.2036559885615786
Fold 4 IBS: 0.22413209063537776
Fold 5 IBS: 0.20904466830379478
[I 2024-04-13 17:17:23,219] Trial 23 finished with value: 0.21869717639298983 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 233, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8927030957052547, 'min_weight_fraction_leaf': 0.2990139029425277}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.24203440231995213
Fold 2 IBS: 0.22554360580458416
Fold 3 IBS: 0.20628337998076055
Fold 4 IBS: 0.2289849237284239
Fold 5 IBS: 0.20599130514353636
[I 2024-04-13 17:17:27,923] Trial 24 finished with value: 0.22176752339545142 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 19, 'n_estimators': 295, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8693046937847292, 'min_weight_fraction_leaf': 0.24639043366252525}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.23623063868086489
Fold 2 IBS: 0.22005171287892328
Fold 3 IBS: 0.20422974897888901
Fold 4 IBS: 0.2262320541568372
Fold 5 IBS: 0.21001474317155738
[I 2024-04-13 17:17:31,071] Trial 25 finished with value: 0.21935177957341434 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 231, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.996738340265135, 'min_weight_fraction_leaf': 0.3690600107806249}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.23675440837764497
Fold 2 IBS: 0.22076702165491713
Fold 3 IBS: 0.20849128508971132
Fold 4 IBS: 0.22924365118701112
Fold 5 IBS: 0.2124099236622402
[I 2024-04-13 17:17:34,983] Trial 26 finished with value: 0.22153325799430493 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 1, 'n_estimators': 318, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7243128593918586, 'min_weight_fraction_leaf': 0.2941984778571687}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.2371660771729202
Fold 2 IBS: 0.2191483603239057
Fold 3 IBS: 0.20641747737853533
Fold 4 IBS: 0.22240690608445848
Fold 5 IBS: 0.20799076460934937
[I 2024-04-13 17:17:38,222] Trial 27 finished with value: 0.21862591711383378 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 261, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8361953498806727, 'min_weight_fraction_leaf': 0.22280258441739995}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.2463193986283167
Fold 2 IBS: 0.23207829291467785
Fold 3 IBS: 0.22966403015817585
Fold 4 IBS: 0.24154609978869193
Fold 5 IBS: 0.23030134578230163
[I 2024-04-13 17:17:39,807] Trial 28 finished with value: 0.2359818334544328 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 114, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8280204053136692, 'min_weight_fraction_leaf': 0.4367390598534441}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.23713924585846832
Fold 2 IBS: 0.21931758118462666
Fold 3 IBS: 0.20367479460476934
Fold 4 IBS: 0.22408618002403552
Fold 5 IBS: 0.20895070313530809
[I 2024-04-13 17:17:43,040] Trial 29 finished with value: 0.21863370096144158 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 260, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7271476705971293, 'min_weight_fraction_leaf': 0.23367475592947387}. Best is trial 20 with value: 0.21858490307862474.

Fold 1 IBS: 0.23738806550248728
Fold 2 IBS: 0.21993578889192347
Fold 3 IBS: 0.21089498091706652
Fold 4 IBS: 0.2272048730326933
Fold 5 IBS: 0.2132773803587104
[I 2024-04-13 17:17:46,524] Trial 30 finished with value: 0.2217402177405762 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 206, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7311100810851326, 'min_weight_fraction_leaf': 0.16969817682654836}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.2371472983744441
Fold 2 IBS: 0.2192317816045922
Fold 3 IBS: 0.2066273024000569
Fold 4 IBS: 0.2223268600858535
Fold 5 IBS: 0.20805506169911736
[I 2024-04-13 17:17:50,411] Trial 31 finished with value: 0.21867766083281284 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 3, 'n_estimators': 259, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8479425058967354, 'min_weight_fraction_leaf': 0.22878903104829593}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.24223910593371958
Fold 2 IBS: 0.2264118903341529
Fold 3 IBS: 0.20731329208194677
Fold 4 IBS: 0.2287610862946042
Fold 5 IBS: 0.20611174516637162
[I 2024-04-13 17:17:55,286] Trial 32 finished with value: 0.22216742396215902 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 339, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9446205451617458, 'min_weight_fraction_leaf': 0.2661809737444116}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.2370219997072243
Fold 2 IBS: 0.2193941053757161
Fold 3 IBS: 0.20373501168298777
Fold 4 IBS: 0.22393480585520856
Fold 5 IBS: 0.208682475587371
[I 2024-04-13 17:17:59,216] Trial 33 finished with value: 0.21855367964170153 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 275, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7377604544275241, 'min_weight_fraction_leaf': 0.22731537286697645}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23710344518730503
Fold 2 IBS: 0.2193601565250112
Fold 3 IBS: 0.20377799030194124
Fold 4 IBS: 0.2240022784938735
Fold 5 IBS: 0.20864844068886612
[I 2024-04-13 17:18:02,866] Trial 34 finished with value: 0.21857846223939942 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 271, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7374664327129382, 'min_weight_fraction_leaf': 0.23191073374208002}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23764750710635235
Fold 2 IBS: 0.22052485431514102
Fold 3 IBS: 0.2086989128573178
Fold 4 IBS: 0.22954355044719715
Fold 5 IBS: 0.21248255472686303
[I 2024-04-13 17:18:05,674] Trial 35 finished with value: 0.22177947589057428 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 212, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8058295418292518, 'min_weight_fraction_leaf': 0.3249726897940118}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23783380527100748
Fold 2 IBS: 0.2211380677742572
Fold 3 IBS: 0.21185207127663558
Fold 4 IBS: 0.22796138018690684
Fold 5 IBS: 0.2144294358021491
[I 2024-04-13 17:18:11,910] Trial 36 finished with value: 0.22264295206219123 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 279, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.5117163187171705, 'min_weight_fraction_leaf': 0.1607072150760065}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23677886144704816
Fold 2 IBS: 0.21955413132469867
Fold 3 IBS: 0.2059952807810265
Fold 4 IBS: 0.22795770153840889
Fold 5 IBS: 0.21078869878851952
[I 2024-04-13 17:18:14,824] Trial 37 finished with value: 0.22021493477594034 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 166, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5977432205420752, 'min_weight_fraction_leaf': 0.2121573650483426}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.24300840277727823
Fold 2 IBS: 0.22638067512276036
Fold 3 IBS: 0.20873415213457244
Fold 4 IBS: 0.22741267505514887
Fold 5 IBS: 0.20459574979480916
[I 2024-04-13 17:18:20,758] Trial 38 finished with value: 0.2220263309769138 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6852629549788185, 'min_weight_fraction_leaf': 0.11814667951535995}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23763664595441686
Fold 2 IBS: 0.21963674238171244
Fold 3 IBS: 0.20765975936600614
Fold 4 IBS: 0.22271331629056146
Fold 5 IBS: 0.20771351346868874
[I 2024-04-13 17:18:22,904] Trial 39 finished with value: 0.21907199549227713 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 131, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9480058935053208, 'min_weight_fraction_leaf': 0.07199443797246757}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23944651370037162
Fold 2 IBS: 0.22439860558737096
Fold 3 IBS: 0.21824376490286634
Fold 4 IBS: 0.2342014368701815
Fold 5 IBS: 0.22112013449236526
[I 2024-04-13 17:18:26,933] Trial 40 finished with value: 0.22748209111063114 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 228, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7703151429728522, 'min_weight_fraction_leaf': 0.3250233317588423}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23712006600581267
Fold 2 IBS: 0.21925666827113804
Fold 3 IBS: 0.20438121866317888
Fold 4 IBS: 0.22426221223278658
Fold 5 IBS: 0.2089755505545177
[I 2024-04-13 17:18:32,599] Trial 41 finished with value: 0.21879914314548676 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 252, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7128779131299335, 'min_weight_fraction_leaf': 0.22502514085583183}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23636287267696218
Fold 2 IBS: 0.21965157568819133
Fold 3 IBS: 0.20429145447374908
Fold 4 IBS: 0.2262599855613196
Fold 5 IBS: 0.21087596893375274
[I 2024-04-13 17:18:38,792] Trial 42 finished with value: 0.21948837146679495 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5, 'n_estimators': 276, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7533545355944256, 'min_weight_fraction_leaf': 0.27846129528158403}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.2366430134802846
Fold 2 IBS: 0.2194294067711963
Fold 3 IBS: 0.20575727644969144
Fold 4 IBS: 0.22313820960120131
Fold 5 IBS: 0.20834548638251957
[I 2024-04-13 17:18:44,134] Trial 43 finished with value: 0.21866267853697866 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 338, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8281942894155514, 'min_weight_fraction_leaf': 0.2362690293240371}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.2372930246571929
Fold 2 IBS: 0.22118755709584256
Fold 3 IBS: 0.21148108493389597
Fold 4 IBS: 0.22832759817438522
Fold 5 IBS: 0.21477380864590534
[I 2024-04-13 17:18:47,858] Trial 44 finished with value: 0.2226126147014444 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 244, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7654866467245561, 'min_weight_fraction_leaf': 0.1765984915124157}. Best is trial 33 with value: 0.21855367964170153.

Fold 1 IBS: 0.24647150063770518
Fold 2 IBS: 0.2324005238674857
Fold 3 IBS: 0.2295165680261027
Fold 4 IBS: 0.2413350176086155
Fold 5 IBS: 0.23048981014618952
[I 2024-04-13 17:18:50,498] Trial 45 finished with value: 0.2360426840572197 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 184, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.42889080150309455, 'min_weight_fraction_leaf': 0.30395190085793466}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23684554782082465
Fold 2 IBS: 0.21919333404974234
Fold 3 IBS: 0.2053013505980981
Fold 4 IBS: 0.22292477589597334
Fold 5 IBS: 0.20836678612341789
[I 2024-04-13 17:18:54,390] Trial 46 finished with value: 0.21852635889761127 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 6, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8006072320599792, 'min_weight_fraction_leaf': 0.13827431215955044}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2399589768301317
Fold 2 IBS: 0.21880138930071588
Fold 3 IBS: 0.20629667242484592
Fold 4 IBS: 0.22636534251393303
Fold 5 IBS: 0.20974876234700723
[I 2024-04-13 17:18:55,123] Trial 47 finished with value: 0.22023422868332676 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 5, 'n_estimators': 31, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9475835682044488, 'min_weight_fraction_leaf': 0.14470027059329618}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23734004410610962
Fold 2 IBS: 0.22033178260287098
Fold 3 IBS: 0.21077176125721195
Fold 4 IBS: 0.22656543896147213
Fold 5 IBS: 0.21330307068589224
[I 2024-04-13 17:18:59,399] Trial 48 finished with value: 0.2216624195227114 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 284, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7986195780539649, 'min_weight_fraction_leaf': 0.04617548779812293}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23625124939716474
Fold 2 IBS: 0.21928917010690835
Fold 3 IBS: 0.2063591757019585
Fold 4 IBS: 0.22331625230525182
Fold 5 IBS: 0.20765154418716986
[I 2024-04-13 17:19:05,890] Trial 49 finished with value: 0.21857347833969065 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 424, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6815323326726881, 'min_weight_fraction_leaf': 0.09131723435674605}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2371187672752822
Fold 2 IBS: 0.21915942871564578
Fold 3 IBS: 0.20721255481618547
Fold 4 IBS: 0.22373050792840368
Fold 5 IBS: 0.20722944561545947
[I 2024-04-13 17:19:13,357] Trial 50 finished with value: 0.21889014087019532 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 475, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5949002626903728, 'min_weight_fraction_leaf': 0.09564369461405195}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23657837413281252
Fold 2 IBS: 0.21921373961408827
Fold 3 IBS: 0.20641430152871024
Fold 4 IBS: 0.22325153046230709
Fold 5 IBS: 0.20771396879094767
[I 2024-04-13 17:19:19,544] Trial 51 finished with value: 0.21863438290577314 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 418, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6711715875812826, 'min_weight_fraction_leaf': 0.12567164193121433}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2357343048159532
Fold 2 IBS: 0.21949424689270622
Fold 3 IBS: 0.2062245962595048
Fold 4 IBS: 0.22302319513557203
Fold 5 IBS: 0.2082914380694619
[I 2024-04-13 17:19:26,000] Trial 52 finished with value: 0.21855355623463962 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 436, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8355484780724112, 'min_weight_fraction_leaf': 0.06356770563405467}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23588775448783578
Fold 2 IBS: 0.21960499379966134
Fold 3 IBS: 0.20560863855751482
Fold 4 IBS: 0.22328194893439646
Fold 5 IBS: 0.20844111520648279
[I 2024-04-13 17:19:32,198] Trial 53 finished with value: 0.21856489019717823 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 3, 'n_estimators': 445, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7933316926807014, 'min_weight_fraction_leaf': 0.0745088611285212}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2459142809877375
Fold 2 IBS: 0.23209907466514498
Fold 3 IBS: 0.23006719908315112
Fold 4 IBS: 0.2412636990636345
Fold 5 IBS: 0.22997918328901845
[I 2024-04-13 17:19:39,268] Trial 54 finished with value: 0.23586468741773733 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 471, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.1465843595834484, 'min_weight_fraction_leaf': 0.0717996537719882}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23562563262770414
Fold 2 IBS: 0.22039354813161444
Fold 3 IBS: 0.20584972692935538
Fold 4 IBS: 0.22772502361054814
Fold 5 IBS: 0.21102864376883282
[I 2024-04-13 17:19:45,394] Trial 55 finished with value: 0.220124515013611 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 2, 'n_estimators': 447, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6195893286059789, 'min_weight_fraction_leaf': 0.020919354828291575}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23563295735954615
Fold 2 IBS: 0.21981277016407383
Fold 3 IBS: 0.204989658791369
Fold 4 IBS: 0.22532191283924616
Fold 5 IBS: 0.20939381856897557
[I 2024-04-13 17:19:51,743] Trial 56 finished with value: 0.21903022354464213 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 446, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6675798400299233, 'min_weight_fraction_leaf': 0.05410607583171402}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.235618718908947
Fold 2 IBS: 0.21973289084248274
Fold 3 IBS: 0.20557239685044001
Fold 4 IBS: 0.2237231663542185
Fold 5 IBS: 0.20836154108703234
[I 2024-04-13 17:19:57,143] Trial 57 finished with value: 0.21860174280862413 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2, 'n_estimators': 415, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5287318340211359, 'min_weight_fraction_leaf': 0.07961343183750659}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.236519319875315
Fold 2 IBS: 0.21950443141544193
Fold 3 IBS: 0.2063407204825024
Fold 4 IBS: 0.22283999560765866
Fold 5 IBS: 0.2081772921338352
[I 2024-04-13 17:20:03,889] Trial 58 finished with value: 0.21867635190295065 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 378, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.803287559716288, 'min_weight_fraction_leaf': 0.027007649016910218}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2354748473353207
Fold 2 IBS: 0.21970210525532657
Fold 3 IBS: 0.20440838433289102
Fold 4 IBS: 0.22472430202794327
Fold 5 IBS: 0.20891913786948146
[I 2024-04-13 17:20:11,985] Trial 59 finished with value: 0.2186457553641926 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 3, 'n_estimators': 489, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7473762466460354, 'min_weight_fraction_leaf': 0.1132881773249865}. Best is trial 46 with value: 0.21852635889761127.

Fold 1 IBS: 0.2427874690307322
Fold 2 IBS: 0.22051307489638503
Fold 3 IBS: 0.21103171261194614
Fold 4 IBS: 0.22387533549578809
Fold 5 IBS: 0.2083271491005745
[I 2024-04-13 17:20:13,120] Trial 60 finished with value: 0.22130694822708522 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 74, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7017596527420207, 'min_weight_fraction_leaf': 0.09966382421080089}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23644800149579903
Fold 2 IBS: 0.2195369287078321
Fold 3 IBS: 0.20653996690015303
Fold 4 IBS: 0.22236489358251474
Fold 5 IBS: 0.20806793260763023
[I 2024-04-13 17:20:20,677] Trial 61 finished with value: 0.21859154465878583 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 357, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8453989714566266, 'min_weight_fraction_leaf': 0.0854881672929427}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23643029999972073
Fold 2 IBS: 0.21967560573705663
Fold 3 IBS: 0.20695855958876064
Fold 4 IBS: 0.22295379459110656
Fold 5 IBS: 0.20740851343462946
[I 2024-04-13 17:20:29,774] Trial 62 finished with value: 0.2186853546702548 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 405, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7864119714099438, 'min_weight_fraction_leaf': 0.03355471126999637}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23662020640249384
Fold 2 IBS: 0.22044682985730565
Fold 3 IBS: 0.2110430430738999
Fold 4 IBS: 0.22659401764816547
Fold 5 IBS: 0.21345170889609122
[I 2024-04-13 17:20:37,617] Trial 63 finished with value: 0.22163116117559117 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 452, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9253967049917359, 'min_weight_fraction_leaf': 0.13189925217057735}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23588117694688576
Fold 2 IBS: 0.21950400748600946
Fold 3 IBS: 0.20743744610362147
Fold 4 IBS: 0.2227219004724267
Fold 5 IBS: 0.20797214307427977
[I 2024-04-13 17:20:46,594] Trial 64 finished with value: 0.21870333481664464 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 18, 'max_depth': 10, 'n_estimators': 435, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8760174816172069, 'min_weight_fraction_leaf': 0.19634298369623576}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.24293657429451518
Fold 2 IBS: 0.22609344656173974
Fold 3 IBS: 0.20815359502812622
Fold 4 IBS: 0.22908562033306976
Fold 5 IBS: 0.20580516572696153
[I 2024-04-13 17:20:55,383] Trial 65 finished with value: 0.2224148803888825 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 390, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8550412886514629, 'min_weight_fraction_leaf': 0.06484834781781368}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.246326123904824
Fold 2 IBS: 0.2321429620809124
Fold 3 IBS: 0.2296037213979481
Fold 4 IBS: 0.24153389713884624
Fold 5 IBS: 0.2302471952197853
[I 2024-04-13 17:21:05,384] Trial 66 finished with value: 0.23597077994846322 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 462, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7546667172212993, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23707512834232153
Fold 2 IBS: 0.21930013195726877
Fold 3 IBS: 0.20789588893960737
Fold 4 IBS: 0.22277962404199228
Fold 5 IBS: 0.20734369610194425
[I 2024-04-13 17:21:14,003] Trial 67 finished with value: 0.21887889387662685 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 430, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8170420213592718, 'min_weight_fraction_leaf': 0.1494978367406185}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2462463594686935
Fold 2 IBS: 0.23217393417283155
Fold 3 IBS: 0.229993630453562
Fold 4 IBS: 0.24115987912128561
Fold 5 IBS: 0.23020109107235417
[I 2024-04-13 17:21:21,152] Trial 68 finished with value: 0.23595497885774538 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 368, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.22939188072225208, 'min_weight_fraction_leaf': 0.10857553018551594}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2368310555074388
Fold 2 IBS: 0.21920878877902486
Fold 3 IBS: 0.20679480272253697
Fold 4 IBS: 0.22280458336806014
Fold 5 IBS: 0.2080990839318608
[I 2024-04-13 17:21:26,960] Trial 69 finished with value: 0.21874766286178432 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 302, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9150371780503119, 'min_weight_fraction_leaf': 0.15865717014764769}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23586697340396454
Fold 2 IBS: 0.22032829223579578
Fold 3 IBS: 0.20643967315282094
Fold 4 IBS: 0.22766226779737594
Fold 5 IBS: 0.21151359247240697
[I 2024-04-13 17:21:31,921] Trial 70 finished with value: 0.22036215981247284 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 15, 'n_estimators': 327, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6977835794345164, 'min_weight_fraction_leaf': 0.269542416852923}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2364558746726569
Fold 2 IBS: 0.2194623320684367
Fold 3 IBS: 0.20706917788988619
Fold 4 IBS: 0.22248122115912292
Fold 5 IBS: 0.20803169557605336
[I 2024-04-13 17:21:38,290] Trial 71 finished with value: 0.21870006027323124 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 366, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8654671343704606, 'min_weight_fraction_leaf': 0.07738198203736042}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23647397626404196
Fold 2 IBS: 0.2193778137976921
Fold 3 IBS: 0.2067575067362915
Fold 4 IBS: 0.22269242363774733
Fold 5 IBS: 0.20796186727425015
[I 2024-04-13 17:21:44,358] Trial 72 finished with value: 0.2186527175420046 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 4, 'n_estimators': 350, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8467228912812281, 'min_weight_fraction_leaf': 0.09173299321647771}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23670700550925744
Fold 2 IBS: 0.2192987886199061
Fold 3 IBS: 0.20442982953084754
Fold 4 IBS: 0.223141013709078
Fold 5 IBS: 0.2083234731520686
[I 2024-04-13 17:21:49,297] Trial 73 finished with value: 0.21838002210423152 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 291, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7842377375661996, 'min_weight_fraction_leaf': 0.04843949872109438}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23699285632626652
Fold 2 IBS: 0.2193550533373929
Fold 3 IBS: 0.20452511359216702
Fold 4 IBS: 0.2231256237020124
Fold 5 IBS: 0.2084643072267637
[I 2024-04-13 17:21:54,418] Trial 74 finished with value: 0.2184925908369205 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7811091062956046, 'min_weight_fraction_leaf': 0.04068939245007144}. Best is trial 73 with value: 0.21838002210423152.

Fold 1 IBS: 0.23757083460058645
Fold 2 IBS: 0.21936835681341144
Fold 3 IBS: 0.2050586023900099
Fold 4 IBS: 0.2231460133461373
Fold 5 IBS: 0.20844072705559955
[I 2024-04-13 17:21:58,337] Trial 75 finished with value: 0.21871690684114892 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 220, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7803578114864529, 'min_weight_fraction_leaf': 0.017478919548903803}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23640141704565878
Fold 2 IBS: 0.2197885256064894
Fold 3 IBS: 0.20318516882698215
Fold 4 IBS: 0.22544681939994865
Fold 5 IBS: 0.20897452087659646
[I 2024-04-13 17:22:03,878] Trial 76 finished with value: 0.21875929035113512 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 3, 'n_estimators': 293, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7310311308084682, 'min_weight_fraction_leaf': 0.053169984941233435}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23741868189676912
Fold 2 IBS: 0.21959001344865917
Fold 3 IBS: 0.20405006070074652
Fold 4 IBS: 0.2243018125512366
Fold 5 IBS: 0.20899734290866995
[I 2024-04-13 17:22:09,102] Trial 77 finished with value: 0.21887158230121626 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 268, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.643528798832142, 'min_weight_fraction_leaf': 0.0035897778567450314}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.2371288491562036
Fold 2 IBS: 0.21921237425444545
Fold 3 IBS: 0.20589294929880203
Fold 4 IBS: 0.22345690243536823
Fold 5 IBS: 0.20790079002157127
[I 2024-04-13 17:22:13,632] Trial 78 finished with value: 0.21871837303327815 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 242, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7399586324559952, 'min_weight_fraction_leaf': 0.036709963240196763}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23718809155484707
Fold 2 IBS: 0.22092106114932006
Fold 3 IBS: 0.21060969393168538
Fold 4 IBS: 0.22820373722606627
Fold 5 IBS: 0.21420368130993808
[I 2024-04-13 17:22:17,278] Trial 79 finished with value: 0.22222525303437135 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 194, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7825507541105653, 'min_weight_fraction_leaf': 0.06153431383484739}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23685165015175644
Fold 2 IBS: 0.22068620321605817
Fold 3 IBS: 0.21160479990748687
Fold 4 IBS: 0.2270351319118709
Fold 5 IBS: 0.21394471822408284
[I 2024-04-13 17:22:26,624] Trial 80 finished with value: 0.22202450068225105 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 3, 'n_estimators': 498, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8206233780498613, 'min_weight_fraction_leaf': 0.01586721934758055}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23680935988687354
Fold 2 IBS: 0.21919210664973693
Fold 3 IBS: 0.2062865708031109
Fold 4 IBS: 0.22287903889466332
Fold 5 IBS: 0.20798592164828278
[I 2024-04-13 17:22:31,707] Trial 81 finished with value: 0.2186305995765335 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 286, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9683267170659943, 'min_weight_fraction_leaf': 0.24820532660386305}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.24167770220133805
Fold 2 IBS: 0.2258829783356682
Fold 3 IBS: 0.20506103877881593
Fold 4 IBS: 0.22848023645111828
Fold 5 IBS: 0.20603856384248168
[I 2024-04-13 17:22:37,137] Trial 82 finished with value: 0.22142810392188444 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 320, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8081851033669109, 'min_weight_fraction_leaf': 0.2131921119494233}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.237582647636615
Fold 2 IBS: 0.21884473486373132
Fold 3 IBS: 0.20742387029349543
Fold 4 IBS: 0.22292165310774673
Fold 5 IBS: 0.2070931524860315
[I 2024-04-13 17:22:41,475] Trial 83 finished with value: 0.21877321167752398 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 267, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8844309504688548, 'min_weight_fraction_leaf': 0.04798854332402432}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.241147785841093
Fold 2 IBS: 0.22383836423992348
Fold 3 IBS: 0.2177963735816699
Fold 4 IBS: 0.23542582564536244
Fold 5 IBS: 0.21963595295530872
[I 2024-04-13 17:22:46,568] Trial 84 finished with value: 0.2275688604526715 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 251, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6787600211894828, 'min_weight_fraction_leaf': 0.30903976828584095}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23734464582042714
Fold 2 IBS: 0.21899391617714345
Fold 3 IBS: 0.2064153028397821
Fold 4 IBS: 0.2224135340583663
Fold 5 IBS: 0.20678778466052464
[I 2024-04-13 17:22:52,408] Trial 85 finished with value: 0.21839103671124876 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 302, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7180827163665513, 'min_weight_fraction_leaf': 0.13602688437706084}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23705812324052997
Fold 2 IBS: 0.21938000194478852
Fold 3 IBS: 0.20530300805717408
Fold 4 IBS: 0.22311578502650944
Fold 5 IBS: 0.20780067210384995
[I 2024-04-13 17:22:57,882] Trial 86 finished with value: 0.21853151807457039 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 302, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7162022295222917, 'min_weight_fraction_leaf': 0.1842957273625047}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23798090366751265
Fold 2 IBS: 0.21947291839956856
Fold 3 IBS: 0.2072184272517321
Fold 4 IBS: 0.22385467669715983
Fold 5 IBS: 0.20690325084134892
[I 2024-04-13 17:23:02,801] Trial 87 finished with value: 0.2190860353714644 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 298, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7693492945351396, 'min_weight_fraction_leaf': 0.13025024094881313}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.2368388275008215
Fold 2 IBS: 0.2193855222635841
Fold 3 IBS: 0.20536349150839933
Fold 4 IBS: 0.22301598241068915
Fold 5 IBS: 0.20804959246559787
[I 2024-04-13 17:23:06,918] Trial 88 finished with value: 0.2185306832298184 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7116913427696117, 'min_weight_fraction_leaf': 0.19026372034651004}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23694872131026606
Fold 2 IBS: 0.21935524065357095
Fold 3 IBS: 0.20576763462390152
Fold 4 IBS: 0.22301199290133028
Fold 5 IBS: 0.20810669911009236
[I 2024-04-13 17:23:11,086] Trial 89 finished with value: 0.21863805771983227 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 327, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7139844393284589, 'min_weight_fraction_leaf': 0.18909187879978934}. Best is trial 73 with value: 0.21838002210423152.

Fold 1 IBS: 0.237217800059635
Fold 2 IBS: 0.219560418627486
Fold 3 IBS: 0.2055584995526966
Fold 4 IBS: 0.22351950054338868
Fold 5 IBS: 0.20798078328178596
[I 2024-04-13 17:23:15,144] Trial 90 finished with value: 0.21876740041299841 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 306, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6578960771293777, 'min_weight_fraction_leaf': 0.16477439734294264}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.236951540585596
Fold 2 IBS: 0.21950546902732596
Fold 3 IBS: 0.20504430850227562
Fold 4 IBS: 0.22315671121676062
Fold 5 IBS: 0.20782359042139878
[I 2024-04-13 17:23:18,706] Trial 91 finished with value: 0.21849632395067142 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6954217194025099, 'min_weight_fraction_leaf': 0.18407738961451633}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.2366590015736694
Fold 2 IBS: 0.21937029886615486
Fold 3 IBS: 0.20566183543415947
Fold 4 IBS: 0.22301451578556367
Fold 5 IBS: 0.20767409548411542
[I 2024-04-13 17:23:22,671] Trial 92 finished with value: 0.21847594942873255 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 291, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7009588430592851, 'min_weight_fraction_leaf': 0.178489497157845}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23687600031261338
Fold 2 IBS: 0.21924088383926293
Fold 3 IBS: 0.2054016930393524
Fold 4 IBS: 0.22302835737032672
Fold 5 IBS: 0.2077489452850229
[I 2024-04-13 17:23:27,042] Trial 93 finished with value: 0.2184591759693157 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7172196194520072, 'min_weight_fraction_leaf': 0.18587233706768527}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23703019354236293
Fold 2 IBS: 0.21948639464154246
Fold 3 IBS: 0.2047505157929676
Fold 4 IBS: 0.2235047542533873
Fold 5 IBS: 0.20855863469046315
[I 2024-04-13 17:23:31,533] Trial 94 finished with value: 0.2186660985841447 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 292, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6219714175446479, 'min_weight_fraction_leaf': 0.18072151749890458}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23692361705128714
Fold 2 IBS: 0.21966953779580314
Fold 3 IBS: 0.20471111021867852
Fold 4 IBS: 0.22299044301485235
Fold 5 IBS: 0.20816654210822538
[I 2024-04-13 17:23:35,440] Trial 95 finished with value: 0.21849225003776934 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 317, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7079376941574543, 'min_weight_fraction_leaf': 0.205035720310988}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23653137028059623
Fold 2 IBS: 0.2197358793548492
Fold 3 IBS: 0.20502556689280826
Fold 4 IBS: 0.22583981363051878
Fold 5 IBS: 0.20976127923417956
[I 2024-04-13 17:23:39,163] Trial 96 finished with value: 0.2193787818785904 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5801992264153996, 'min_weight_fraction_leaf': 0.2036293513522096}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23691132713166155
Fold 2 IBS: 0.21934888168734706
Fold 3 IBS: 0.2060353520597031
Fold 4 IBS: 0.2230362471179694
Fold 5 IBS: 0.20779263064091014
[I 2024-04-13 17:23:44,486] Trial 97 finished with value: 0.21862488772751826 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 328, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.705642847473056, 'min_weight_fraction_leaf': 0.17148295318003226}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.237230513240583
Fold 2 IBS: 0.2192840978709365
Fold 3 IBS: 0.20624346451793507
Fold 4 IBS: 0.2233785003281718
Fold 5 IBS: 0.20807621679976449
[I 2024-04-13 17:23:49,612] Trial 98 finished with value: 0.21884255855147816 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 343, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6399955222854865, 'min_weight_fraction_leaf': 0.1529848101895856}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23707199815043145
Fold 2 IBS: 0.21927691514345446
Fold 3 IBS: 0.20538898879208908
Fold 4 IBS: 0.2230658739211438
Fold 5 IBS: 0.20786983407137138
[I 2024-04-13 17:23:53,369] Trial 99 finished with value: 0.21853472201569804 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 279, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7197685650294967, 'min_weight_fraction_leaf': 0.18553539660920623}. Best is trial 73 with value: 0.21838002210423152.


* Best trial for IBS:
 FrozenTrial(number=73, state=TrialState.COMPLETE, values=[0.21838002210423152], datetime_start=datetime.datetime(2024, 4, 13, 17, 21, 44, 364451), datetime_complete=datetime.datetime(2024, 4, 13, 17, 21, 49, 288318), params={'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 291, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7842377375661996, 'min_weight_fraction_leaf': 0.04843949872109438}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=73, value=None)


* Best Score for IBS:
 0.21838002210423152

In [70]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [71]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.748
train_ibs:  0.218

#### Test

In [72]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [73]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=11, max_leaf_nodes=17,
                   max_samples=0.8662742964997368, min_samples_leaf=1,
                   min_samples_split=19,
                   min_weight_fraction_leaf=0.0017689713740798967,
                   n_estimators=54, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.585

ExtraSurvivalTrees(max_depth=2, max_features='auto', max_leaf_nodes=20,
                   max_samples=0.7842377375661996, min_samples_leaf=19,
                   min_samples_split=19,
                   min_weight_fraction_leaf=0.04843949872109438,
                   n_estimators=291, oob_score=True, random_state=123)

IBS: 0.213

In [74]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [75]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:23:54,731] A new study created in memory with name: no-name-56c55ad2-e968-4269-a63f-cbd3495e06a7

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:24:24,676] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:24:44,828] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:25:01,888] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:25:28,534] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:25:40,141] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:25:42,986] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:26:11,322] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:26:23,662] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:26:25,001] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5796812749003984
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 17:27:44,653] Trial 9 finished with value: 0.6172849274886952 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6172849274886952.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 17:29:47,620] Trial 10 finished with value: 0.5915509861883201 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6172849274886952.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:32:13,151] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6172849274886952.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6234042553191489
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 17:34:22,882] Trial 12 finished with value: 0.6288581469840132 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.6288581469840132.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:35:37,273] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:37:29,853] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:39:02,430] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:40:06,807] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:42:31,464] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:46:18,569] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:46:26,993] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:47:46,146] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:50:38,699] Trial 21 finished with value: 0.5 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6182170542635659
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.6596958174904943
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 17:53:36,229] Trial 22 finished with value: 0.6233941406142943 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:56:29,217] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:59:03,974] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:00:54,229] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:04:02,256] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:07:03,623] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:09:40,049] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:11:25,149] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:13:14,622] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:16:37,730] Trial 31 finished with value: 0.5071713147410358 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:20:08,750] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:22:16,543] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:25:36,138] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:26:18,838] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:29:10,288] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:29:15,012] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 12 with value: 0.6288581469840132.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:30:18,602] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:32:07,775] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:34:51,282] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 18:34:51,691] Trial 41 finished with value: 0.6039152174760968 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6008583690987125
[I 2024-04-13 18:35:08,070] Trial 42 finished with value: 0.624004230389207 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:35:08,969] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8735505723796891, 'learning_rate': 0.013455915558851193, 'dropout_rate': 0.11585930219083569, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 1.1546454041172216, 'min_weight_fraction_leaf': 0.4571018098895751, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8650432234384267, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:35:50,121] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9479336661285427, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.25335630680617827, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.4126953497238681, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.9438667820963776, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 18:36:08,123] Trial 45 finished with value: 0.636916827084602 and parameters: {'subsample': 0.5852424762732177, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.027804703729289008, 'min_weight_fraction_leaf': 0.262143273989599, 'max_features': 0.1, 'min_impurity_decrease': 9.467252666446998e-07, 'validation_fraction': 0.7243304021069044, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 45 with value: 0.636916827084602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:36:11,620] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.0647255784094387, 'dropout_rate': 0.9694253886674298, 'n_estimators': 130, 'criterion': 'squared_error', 'ccp_alpha': 1.9903431110600875, 'min_weight_fraction_leaf': 0.2621149519999694, 'max_features': 0.1, 'min_impurity_decrease': 1.8213591543920705e-06, 'validation_fraction': 0.7149599360255287, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 45 with value: 0.636916827084602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:36:30,126] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.45583884600027197, 'learning_rate': 0.06333641179361332, 'dropout_rate': 0.19790330487666663, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.14638041253524992, 'max_features': 0.1, 'min_impurity_decrease': 9.138461248752069e-07, 'validation_fraction': 0.6499098781754827, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 45 with value: 0.636916827084602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:36:35,645] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.584713932884162, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.27951884808649285, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 1.4079486283020177, 'min_weight_fraction_leaf': 0.21342970007180673, 'max_features': 0.1, 'min_impurity_decrease': 2.4988708934303504e-06, 'validation_fraction': 0.5884862057231304, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 45 with value: 0.636916827084602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:36:54,652] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.5312512417393443, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3775922041148432, 'min_weight_fraction_leaf': 0.2316969754016241, 'max_features': 'log2', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.8162506488425402, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 45 with value: 0.636916827084602.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:37:04,797] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.052706271754983484, 'dropout_rate': 0.3787195779305788, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.077209816707269, 'min_weight_fraction_leaf': 0.31040829786124846, 'max_features': 0.1, 'min_impurity_decrease': 1.0106089337747014e-06, 'validation_fraction': 0.8835479481377899, 'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 45 with value: 0.636916827084602.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6298449612403101
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.6596958174904943
Fold 5 C-index: 0.6158798283261803
[I 2024-04-13 18:37:06,701] Trial 51 finished with value: 0.6419284038560863 and parameters: {'subsample': 0.9156545266266123, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.1404019935798118, 'n_estimators': 32, 'criterion': 'squared_error', 'ccp_alpha': 0.012243801070742757, 'min_weight_fraction_leaf': 0.377285576216956, 'max_features': 'sqrt', 'min_impurity_decrease': 2.1936100454733836e-07, 'validation_fraction': 0.855037228249073, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:37:09,555] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.7977865301378425, 'learning_rate': 0.07102079283153598, 'dropout_rate': 0.11294952687164567, 'n_estimators': 48, 'criterion': 'squared_error', 'ccp_alpha': 0.5430622755642927, 'min_weight_fraction_leaf': 0.36469952190521415, 'max_features': 'sqrt', 'min_impurity_decrease': 2.38579101418113e-07, 'validation_fraction': 0.7433547121677936, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6414728682170543
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.655893536121673
Fold 5 C-index: 0.5944206008583691
[I 2024-04-13 18:37:10,989] Trial 53 finished with value: 0.6383590963856938 and parameters: {'subsample': 0.7305170806182099, 'learning_rate': 0.05877903849297955, 'dropout_rate': 0.2158120114915196, 'n_estimators': 28, 'criterion': 'squared_error', 'ccp_alpha': 0.009781579144263263, 'min_weight_fraction_leaf': 0.33111548353893067, 'max_features': 'sqrt', 'min_impurity_decrease': 5.215208696037137e-07, 'validation_fraction': 0.8384582646351804, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:37:12,807] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.7254872738354575, 'learning_rate': 0.059834764453264265, 'dropout_rate': 0.22627998975411026, 'n_estimators': 34, 'criterion': 'squared_error', 'ccp_alpha': 1.6707664312736628, 'min_weight_fraction_leaf': 0.3401457696750657, 'max_features': 'sqrt', 'min_impurity_decrease': 3.9827268139860795e-07, 'validation_fraction': 0.8695162647266814, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:37:18,067] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8980684211151492, 'learning_rate': 0.04709963647359185, 'dropout_rate': 0.18274261049965285, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.40074886285106287, 'min_weight_fraction_leaf': 0.3370690002239194, 'max_features': 'sqrt', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8331902741865593, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:37:47,523] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.9221605118409517, 'learning_rate': 0.04145334122676535, 'dropout_rate': 0.13064667596279733, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 1.0261239696798017, 'min_weight_fraction_leaf': 0.37038285680105903, 'max_features': 'sqrt', 'min_impurity_decrease': 6.554786161716051e-07, 'validation_fraction': 0.9052955846887007, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.5968992248062015
Fold 3 C-index: 0.6914893617021277
Fold 4 C-index: 0.6254752851711026
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 18:37:54,245] Trial 57 finished with value: 0.6248260205783842 and parameters: {'subsample': 0.870116595720937, 'learning_rate': 0.05952554251828951, 'dropout_rate': 0.2654836627375681, 'n_estimators': 84, 'criterion': 'squared_error', 'ccp_alpha': 0.0019473494055538935, 'min_weight_fraction_leaf': 0.4506484646379062, 'max_features': 'sqrt', 'min_impurity_decrease': 5.171295766128041e-06, 'validation_fraction': 0.7918559073771259, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:38:04,994] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.7860091128392402, 'learning_rate': 0.05676463368504374, 'dropout_rate': 0.24877801421911805, 'n_estimators': 92, 'criterion': 'squared_error', 'ccp_alpha': 0.7470877807882045, 'min_weight_fraction_leaf': 0.26934786002389455, 'max_features': 'sqrt', 'min_impurity_decrease': 1.6503518520592255e-05, 'validation_fraction': 0.6918134851314997, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 19}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:38:07,187] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.8553450495189544, 'learning_rate': 0.07051651042781107, 'dropout_rate': 0.16583013538010005, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 8.349136570200802, 'min_weight_fraction_leaf': 0.47402646750752947, 'max_features': 'sqrt', 'min_impurity_decrease': 4.916228088258153e-06, 'validation_fraction': 0.779738812956857, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:38:10,676] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.8311606032672914, 'learning_rate': 0.049337793762293414, 'dropout_rate': 0.10027170450231424, 'n_estimators': 50, 'criterion': 'squared_error', 'ccp_alpha': 1.3119841524585854, 'min_weight_fraction_leaf': 0.3074767130493653, 'max_features': 'sqrt', 'min_impurity_decrease': 2.4188603560320107e-06, 'validation_fraction': 0.8209142444316069, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:38:22,187] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.8807242730119922, 'learning_rate': 0.06060509917723852, 'dropout_rate': 0.21540975433556148, 'n_estimators': 97, 'criterion': 'squared_error', 'ccp_alpha': 0.34104023788856364, 'min_weight_fraction_leaf': 0.4431847862340273, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1489427281229002e-06, 'validation_fraction': 0.889211406935275, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 18}. Best is trial 51 with value: 0.6419284038560863.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.655893536121673
Fold 5 C-index: 0.6115879828326181
[I 2024-04-13 18:38:27,590] Trial 62 finished with value: 0.6283268841578284 and parameters: {'subsample': 0.9543961448103062, 'learning_rate': 0.06789146011220368, 'dropout_rate': 0.3264939129108728, 'n_estimators': 71, 'criterion': 'squared_error', 'ccp_alpha': 0.022616672247981386, 'min_weight_fraction_leaf': 0.41165895476319747, 'max_features': 'sqrt', 'min_impurity_decrease': 5.069407900080354e-07, 'validation_fraction': 0.7859949287628765, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 18}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.674468085106383
Fold 4 C-index: 0.6444866920152091
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 18:38:40,824] Trial 63 finished with value: 0.6235672145293628 and parameters: {'subsample': 0.9469443427613207, 'learning_rate': 0.06801311498216697, 'dropout_rate': 0.32617131802248245, 'n_estimators': 119, 'criterion': 'squared_error', 'ccp_alpha': 0.017289191017379774, 'min_weight_fraction_leaf': 0.38230472306828395, 'max_features': 'sqrt', 'min_impurity_decrease': 5.596696905911145e-07, 'validation_fraction': 0.7322540972531445, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 18}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:38:46,932] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.9999291885743816, 'learning_rate': 0.06351690862369143, 'dropout_rate': 0.2603466948459836, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.4231489714125428, 'max_features': 'sqrt', 'min_impurity_decrease': 1.7375428501365761e-06, 'validation_fraction': 0.7799232691405718, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:38:51,796] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.731372773241202, 'learning_rate': 0.08483859461035387, 'dropout_rate': 0.42946028164369743, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.3522642153414066, 'min_weight_fraction_leaf': 0.4089858346066107, 'max_features': 'sqrt', 'min_impurity_decrease': 2.3880040801001446e-07, 'validation_fraction': 0.6774643261598785, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:38:53,399] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.9270510971818493, 'learning_rate': 0.07831921552372668, 'dropout_rate': 0.3690035704996783, 'n_estimators': 20, 'criterion': 'squared_error', 'ccp_alpha': 0.8895257611291668, 'min_weight_fraction_leaf': 0.38130779234883155, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00014974488025406402, 'validation_fraction': 0.8426595838965568, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:39:15,576] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8509816424016059, 'learning_rate': 0.09201698812616743, 'dropout_rate': 0.2891948392773582, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 0.29393333981111347, 'min_weight_fraction_leaf': 0.32926871585157824, 'max_features': None, 'min_impurity_decrease': 1.805737910528395e-07, 'validation_fraction': 0.7952722655013678, 'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:39:27,374] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.6619865463398119, 'learning_rate': 0.07383151588968451, 'dropout_rate': 0.1853296855049907, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.8385719579981664, 'min_weight_fraction_leaf': 0.47751000784675207, 'max_features': 1, 'min_impurity_decrease': 1.2986365360837672e-06, 'validation_fraction': 0.7538502794470011, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 18}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:39:45,870] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7692672682208916, 'learning_rate': 0.05773952075160269, 'dropout_rate': 0.2343529795568311, 'n_estimators': 135, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7491404886634039, 'min_weight_fraction_leaf': 0.20015949879955452, 'max_features': 'sqrt', 'min_impurity_decrease': 5.368270720109542e-07, 'validation_fraction': 0.9581706893807749, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 15}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.6444866920152091
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 18:39:54,293] Trial 70 finished with value: 0.6431464077499045 and parameters: {'subsample': 0.9672353591832252, 'learning_rate': 0.050642884595621745, 'dropout_rate': 0.13785096073945516, 'n_estimators': 88, 'criterion': 'squared_error', 'ccp_alpha': 0.010067956580931684, 'min_weight_fraction_leaf': 0.3551802773828724, 'max_features': 0.1, 'min_impurity_decrease': 7.713426989240967e-06, 'validation_fraction': 0.6901517483986648, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 19}. Best is trial 70 with value: 0.6431464077499045.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6007751937984496
Fold 3 C-index: 0.6829787234042554
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 18:40:00,857] Trial 71 finished with value: 0.647978353455525 and parameters: {'subsample': 0.9736544653699906, 'learning_rate': 0.05317196534413593, 'dropout_rate': 0.14303111133639826, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.35066087197674667, 'max_features': 0.1, 'min_impurity_decrease': 7.356647091617949e-06, 'validation_fraction': 0.6117331205297228, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:40:07,435] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.9701687645962381, 'learning_rate': 0.055147872123398556, 'dropout_rate': 0.14962137828220934, 'n_estimators': 80, 'criterion': 'squared_error', 'ccp_alpha': 0.30517658758579036, 'min_weight_fraction_leaf': 0.35173646760424715, 'max_features': 0.1, 'min_impurity_decrease': 7.987219995224915e-06, 'validation_fraction': 0.6095946706874, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:40:12,929] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.9050782920628282, 'learning_rate': 0.05199322380390804, 'dropout_rate': 0.17409435305677468, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 1.253410092850479, 'min_weight_fraction_leaf': 0.39707509838374494, 'max_features': 0.1, 'min_impurity_decrease': 1.5194516956030065e-05, 'validation_fraction': 0.6804519242126394, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:40:15,782] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.8170901637275931, 'learning_rate': 0.04465970891926194, 'dropout_rate': 0.2733411451160021, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 2.2209618984123054, 'min_weight_fraction_leaf': 0.28881136217710557, 'max_features': 0.1, 'min_impurity_decrease': 4.209901591206505e-06, 'validation_fraction': 0.565571701048534, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:40:23,876] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.9660009158555741, 'learning_rate': 0.06623664860709609, 'dropout_rate': 0.20553427844193914, 'n_estimators': 86, 'criterion': 'squared_error', 'ccp_alpha': 0.6610020768545956, 'min_weight_fraction_leaf': 0.4147865725732959, 'max_features': 0.1, 'min_impurity_decrease': 5.9734079360074814e-05, 'validation_fraction': 0.7190500576027261, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:40:24,546] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9260563831456721, 'learning_rate': 0.06047528137822334, 'dropout_rate': 0.13950292138275533, 'n_estimators': 3, 'criterion': 'squared_error', 'ccp_alpha': 0.30518351178979397, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 3.0635242894652526e-06, 'validation_fraction': 0.6370726022286737, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:40:26,141] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.6292281998520165, 'learning_rate': 0.05024404952833331, 'dropout_rate': 0.3126086948156713, 'n_estimators': 24, 'criterion': 'squared_error', 'ccp_alpha': 0.9547062307580542, 'min_weight_fraction_leaf': 0.3510321193946014, 'max_features': 0.1, 'min_impurity_decrease': 1.081678973071488e-05, 'validation_fraction': 0.7602747720774515, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6634980988593155
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 18:40:30,128] Trial 78 finished with value: 0.6353126486594283 and parameters: {'subsample': 0.8691738049495636, 'learning_rate': 0.06172743517601075, 'dropout_rate': 0.23315454705919414, 'n_estimators': 53, 'criterion': 'squared_error', 'ccp_alpha': 0.022575408770505685, 'min_weight_fraction_leaf': 0.3057970079002221, 'max_features': 0.1, 'min_impurity_decrease': 1.7520953196534605e-06, 'validation_fraction': 0.5037268926902503, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:40:34,388] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.88956690114416, 'learning_rate': 0.04130686635403637, 'dropout_rate': 0.8831816560103296, 'n_estimators': 57, 'criterion': 'squared_error', 'ccp_alpha': 0.5632856474666742, 'min_weight_fraction_leaf': 0.2996503291930464, 'max_features': 0.1, 'min_impurity_decrease': 2.4463737680399873e-06, 'validation_fraction': 0.4716515115237929, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:41:06,295] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.25430148678930137, 'learning_rate': 0.05535894045369185, 'dropout_rate': 0.684566586558272, 'n_estimators': 281, 'criterion': 'friedman_mse', 'ccp_alpha': 5.788139805041061, 'min_weight_fraction_leaf': 0.2499517824138018, 'max_features': 0.1, 'min_impurity_decrease': 1.796522128313966e-06, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 18}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 18:41:09,072] Trial 81 finished with value: 0.6307781380800804 and parameters: {'subsample': 0.8577485699653032, 'learning_rate': 0.061637170413557506, 'dropout_rate': 0.22634568349167175, 'n_estimators': 40, 'criterion': 'squared_error', 'ccp_alpha': 0.025375439967122704, 'min_weight_fraction_leaf': 0.3176895770453635, 'max_features': 0.1, 'min_impurity_decrease': 7.578956130507077e-06, 'validation_fraction': 0.3975706744446108, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:41:12,078] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.9813148642262436, 'learning_rate': 0.062245123119526666, 'dropout_rate': 0.22245189647227442, 'n_estimators': 42, 'criterion': 'squared_error', 'ccp_alpha': 0.24494931030471306, 'min_weight_fraction_leaf': 0.28129167307655356, 'max_features': 0.1, 'min_impurity_decrease': 2.116701877304566e-05, 'validation_fraction': 0.40489648109304005, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:41:13,207] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9499142623758436, 'learning_rate': 0.06606682685789786, 'dropout_rate': 0.1294422134091702, 'n_estimators': 17, 'criterion': 'squared_error', 'ccp_alpha': 0.20222023273899953, 'min_weight_fraction_leaf': 0.3184434511931986, 'max_features': 0.1, 'min_impurity_decrease': 8.590576083527748e-06, 'validation_fraction': 0.29115286333596435, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:41:15,225] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.9162531840390775, 'learning_rate': 0.06921777347051267, 'dropout_rate': 0.16964850157537764, 'n_estimators': 33, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.3317427757671296, 'max_features': 'log2', 'min_impurity_decrease': 3.8673317929388064e-05, 'validation_fraction': 0.40427407950001876, 'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:41:25,906] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.8559905830599279, 'learning_rate': 0.073450036806534, 'dropout_rate': 0.24007045832787577, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 0.7090566148541139, 'min_weight_fraction_leaf': 0.29987641169357954, 'max_features': 0.1, 'min_impurity_decrease': 8.743573121519345e-07, 'validation_fraction': 0.37827224876251, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 71 with value: 0.647978353455525.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:41:31,035] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.8229463564083213, 'learning_rate': 0.05354154925209642, 'dropout_rate': 0.18105225920404389, 'n_estimators': 69, 'criterion': 'squared_error', 'ccp_alpha': 1.4515009042573248, 'min_weight_fraction_leaf': 0.22575436425055093, 'max_features': 0.1, 'min_impurity_decrease': 4.6532667290211476e-07, 'validation_fraction': 0.4763814174163325, 'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:42:27,775] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.7337132044406884, 'learning_rate': 0.0483078966674454, 'dropout_rate': 0.2072955347245793, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.4342246419942306, 'min_weight_fraction_leaf': 0.341665255032293, 'max_features': 0.1, 'min_impurity_decrease': 3.4533033574953447e-06, 'validation_fraction': 0.5553002617274752, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:42:51,443] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.4281147617989565, 'learning_rate': 0.057668292702843474, 'dropout_rate': 0.29991250599365193, 'n_estimators': 173, 'criterion': 'squared_error', 'ccp_alpha': 1.1038407677376183, 'min_weight_fraction_leaf': 0.2720384326960418, 'max_features': 0.1, 'min_impurity_decrease': 0.08546129120562182, 'validation_fraction': 0.43622932617902443, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6158798283261803
[I 2024-04-13 18:42:52,239] Trial 89 finished with value: 0.6178740227922591 and parameters: {'subsample': 0.8869756572783157, 'learning_rate': 0.04455455099426123, 'dropout_rate': 0.1354867390651922, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.018791586505192352, 'min_weight_fraction_leaf': 0.25406844321469574, 'max_features': None, 'min_impurity_decrease': 3.2164803778484834e-07, 'validation_fraction': 0.5865831845086661, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:43:30,968] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.781156318466977, 'learning_rate': 0.006695820304041528, 'dropout_rate': 0.3320445224709127, 'n_estimators': 239, 'criterion': 'squared_error', 'ccp_alpha': 0.837158352801002, 'min_weight_fraction_leaf': 0.37074107443236604, 'max_features': 1, 'min_impurity_decrease': 1.2352569883229447e-06, 'validation_fraction': 0.29585084927667094, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6007751937984496
Fold 3 C-index: 0.6702127659574468
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 18:43:37,661] Trial 91 finished with value: 0.6331036326328527 and parameters: {'subsample': 0.9353573941382942, 'learning_rate': 0.06264501502966024, 'dropout_rate': 0.27046977102493674, 'n_estimators': 87, 'criterion': 'squared_error', 'ccp_alpha': 0.03786111729139331, 'min_weight_fraction_leaf': 0.35574723998417634, 'max_features': 'sqrt', 'min_impurity_decrease': 5.380131049753413e-06, 'validation_fraction': 0.7054955710261992, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:43:40,804] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.9692777812882016, 'learning_rate': 0.061855558095227366, 'dropout_rate': 0.35143637013904355, 'n_estimators': 54, 'criterion': 'squared_error', 'ccp_alpha': 0.20072657092263457, 'min_weight_fraction_leaf': 0.36014647758482426, 'max_features': 'sqrt', 'min_impurity_decrease': 1.3975982326313562e-05, 'validation_fraction': 0.6999911594682504, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:43:51,656] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.9369616346923534, 'learning_rate': 0.06630023579051483, 'dropout_rate': 0.2355177689627272, 'n_estimators': 111, 'criterion': 'squared_error', 'ccp_alpha': 0.5295497507503906, 'min_weight_fraction_leaf': 0.32195077645631737, 'max_features': 0.1, 'min_impurity_decrease': 5.784089080997864e-06, 'validation_fraction': 0.6211860587757073, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:43:54,569] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.49488295095968804, 'learning_rate': 0.07808338686371585, 'dropout_rate': 0.19914486856709368, 'n_estimators': 41, 'criterion': 'squared_error', 'ccp_alpha': 0.17721823221162922, 'min_weight_fraction_leaf': 0.3452780203306576, 'max_features': 'log2', 'min_impurity_decrease': 2.406520527524238e-06, 'validation_fraction': 0.6609732454629287, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:44:00,953] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.9088674838000037, 'learning_rate': 0.051473564556910295, 'dropout_rate': 0.15864268967517714, 'n_estimators': 73, 'criterion': 'squared_error', 'ccp_alpha': 0.5662134543657839, 'min_weight_fraction_leaf': 0.3087279762860713, 'max_features': 'sqrt', 'min_impurity_decrease': 7.802177640457686e-06, 'validation_fraction': 0.734306853058186, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 18}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:44:08,561] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.993220298193821, 'learning_rate': 0.06386578790331472, 'dropout_rate': 0.2728557965516078, 'n_estimators': 94, 'criterion': 'squared_error', 'ccp_alpha': 0.23611518017692762, 'min_weight_fraction_leaf': 0.398118898214648, 'max_features': 0.1, 'min_impurity_decrease': 6.932932254500803e-07, 'validation_fraction': 0.32386831053055254, 'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:44:10,247] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8439950412703551, 'learning_rate': 0.07169891244281298, 'dropout_rate': 0.25309805821661835, 'n_estimators': 32, 'criterion': 'friedman_mse', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.33178189795581936, 'max_features': 'sqrt', 'min_impurity_decrease': 3.941232420298443e-06, 'validation_fraction': 0.6710136077506228, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:44:14,576] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8752955195522896, 'learning_rate': 0.05568154932630848, 'dropout_rate': 0.21717204178559688, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.37049554846771593, 'max_features': 0.1, 'min_impurity_decrease': 2.02393880274831e-06, 'validation_fraction': 0.5229378594864895, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6659574468085107
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 18:44:15,233] Trial 99 finished with value: 0.6104297972213892 and parameters: {'subsample': 0.9501601982199268, 'learning_rate': 0.0684597170667179, 'dropout_rate': 0.11764001599415652, 'n_estimators': 5, 'criterion': 'squared_error', 'ccp_alpha': 0.004454392542064083, 'min_weight_fraction_leaf': 0.2967257830934646, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0344011415681455e-06, 'validation_fraction': 0.1604355124738367, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 14}. Best is trial 71 with value: 0.647978353455525.


* Best trial for C-index:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.647978353455525], datetime_start=datetime.datetime(2024, 4, 13, 18, 39, 54, 300503), datetime_complete=datetime.datetime(2024, 4, 13, 18, 40, 0, 855684), params={'subsample': 0.9736544653699906, 'learning_rate': 0.05317196534413593, 'dropout_rate': 0.14303111133639826, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.35066087197674667, 'max_features': 0.1, 'min_impurity_decrease': 7.356647091617949e-06, 'validation_fraction': 0.6117331205297228, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 19}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=71, value=None)


* Best Score for C-index:
 0.647978353455525

[I 2024-04-13 18:44:15,308] A new study created in memory with name: no-name-09d53f15-3ffc-4a15-a791-553d46a5ee57

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:45:10,179] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:45:38,635] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:46:07,265] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 18:46:51,595] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:47:10,491] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:47:14,940] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:48:02,797] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:48:19,432] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:48:21,198] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24685581184618258
Fold 2 IBS: 0.23174237938551043
Fold 3 IBS: 0.22869576829949326
Fold 4 IBS: 0.24182307569018754
Fold 5 IBS: 0.22901409570517067
[I 2024-04-13 18:50:13,062] Trial 9 finished with value: 0.2356262261853089 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24711653291675975
Fold 2 IBS: 0.23202162954629
Fold 3 IBS: 0.2289556964425975
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293716647928885
[I 2024-04-13 18:53:02,843] Trial 10 finished with value: 0.23588805903156138 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 18:56:16,275] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24719577573761148
Fold 2 IBS: 0.23199892761841134
Fold 3 IBS: 0.2289405059322678
Fold 4 IBS: 0.2419573801021639
Fold 5 IBS: 0.22934247219234205
[I 2024-04-13 18:59:12,890] Trial 12 finished with value: 0.23588701231655934 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:00:43,987] Trial 13 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:02:52,138] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:04:52,457] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 19:06:07,458] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 19:08:48,939] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:12:22,045] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 19:12:30,386] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:13:45,478] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:16:45,465] Trial 21 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24675710728069802
Fold 2 IBS: 0.23120128338106113

Fold 3 IBS: 0.22848569735194738
Fold 4 IBS: 0.24150141767716396
Fold 5 IBS: 0.22845766625525668
[I 2024-04-13 19:19:58,771] Trial 22 finished with value: 0.23528063438922545 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:22:27,125] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-13 19:24:45,062] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:26:09,449] Trial 25 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 19:29:06,794] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:32:05,857] Trial 27 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:34:33,436] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:36:17,419] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 19:38:25,629] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24723811107199292
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:42:08,497] Trial 31 finished with value: 0.23592604563741132 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:13:03,633] Trial 32 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:15:05,257] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:17:34,624] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:18:02,694] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:20:35,486] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:20:40,965] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:21:40,688] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:23:06,610] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:25:31,714] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.2472010209971281
Fold 2 IBS: 0.23197319933729893
Fold 3 IBS: 0.22887452934644678
Fold 4 IBS: 0.24191861956639799
Fold 5 IBS: 0.2293015642651888
[I 2024-04-13 20:25:32,331] Trial 41 finished with value: 0.23585378670249213 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.2459047520616606
Fold 2 IBS: 0.23020388607917422
Fold 3 IBS: 0.22657568837307415
Fold 4 IBS: 0.24022980115273948
Fold 5 IBS: 0.22694242307333995
[I 2024-04-13 20:25:52,348] Trial 42 finished with value: 0.2339713101479977 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:25:53,316] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8735505723796891, 'learning_rate': 0.013455915558851193, 'dropout_rate': 0.11585930219083569, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 1.1546454041172216, 'min_weight_fraction_leaf': 0.4571018098895751, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8650432234384267, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:26:35,418] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9479336661285427, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.25335630680617827, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.4126953497238681, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.9438667820963776, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24456420494605938
Fold 2 IBS: 0.2296322307721539
Fold 3 IBS: 0.22573775856516912
Fold 4 IBS: 0.23975108534236433
Fold 5 IBS: 0.22653026890442532
[I 2024-04-13 20:26:50,271] Trial 45 finished with value: 0.2332431097060344 and parameters: {'subsample': 0.5852424762732177, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.027804703729289008, 'min_weight_fraction_leaf': 0.262143273989599, 'max_features': 0.1, 'min_impurity_decrease': 9.467252666446998e-07, 'validation_fraction': 0.7243304021069044, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:26:53,914] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.0647255784094387, 'dropout_rate': 0.9694253886674298, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 1.980441868470768, 'min_weight_fraction_leaf': 0.3747732962598691, 'max_features': 0.1, 'min_impurity_decrease': 2.6164901943280044e-07, 'validation_fraction': 0.7149599360255287, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:27:22,267] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.45583884600027197, 'learning_rate': 0.06333641179361332, 'dropout_rate': 0.19790330487666663, 'n_estimators': 172, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.3462595663974316, 'max_features': 0.1, 'min_impurity_decrease': 9.138461248752069e-07, 'validation_fraction': 0.6499098781754827, 'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:27:30,467] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.584713932884162, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.10579627176846597, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 0.443834316760607, 'min_weight_fraction_leaf': 0.26066789839492466, 'max_features': 0.1, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.5884862057231304, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:27:31,418] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5232490206634685, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 9, 'criterion': 'friedman_mse', 'ccp_alpha': 1.370081088125734, 'min_weight_fraction_leaf': 0.3097478284829108, 'max_features': 0.1, 'min_impurity_decrease': 2.368978679128857e-06, 'validation_fraction': 0.8421492954769574, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:27:33,806] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.07076395585024155, 'dropout_rate': 0.14893065487391582, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 1.7468603849227415, 'min_weight_fraction_leaf': 0.4771102452497172, 'max_features': 'log2', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.6959936026682685, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24691186517673142
Fold 2 IBS: 0.23166083157852174
Fold 3 IBS: 0.22854484375938985
Fold 4 IBS: 0.24160811245105418
Fold 5 IBS: 0.2289571734476567
[I 2024-04-13 20:27:49,387] Trial 51 finished with value: 0.23553656528267078 and parameters: {'subsample': 0.7946888792311653, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.2196446942108301, 'n_estimators': 129, 'criterion': 'squared_error', 'ccp_alpha': 0.012243801070742757, 'min_weight_fraction_leaf': 0.22002902120871776, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0321764873923598e-06, 'validation_fraction': 0.8872414026388215, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24623497694375837
Fold 2 IBS: 0.23110463228852685
Fold 3 IBS: 0.22789301004466875
Fold 4 IBS: 0.24144064404347787
Fold 5 IBS: 0.22815882228252543
[I 2024-04-13 20:28:01,827] Trial 52 finished with value: 0.23496641712059146 and parameters: {'subsample': 0.7293363088819711, 'learning_rate': 0.021613492744160495, 'dropout_rate': 0.21988140341808987, 'n_estimators': 109, 'criterion': 'squared_error', 'ccp_alpha': 0.03659945835027755, 'min_weight_fraction_leaf': 0.21454208459463384, 'max_features': 'sqrt', 'min_impurity_decrease': 4.968003047339178e-07, 'validation_fraction': 0.7452334109475507, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:28:14,959] Trial 53 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7286313887376499, 'learning_rate': 0.057410108721501936, 'dropout_rate': 0.285096973056326, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.4512041233232864, 'min_weight_fraction_leaf': 0.2260580293041923, 'max_features': 'sqrt', 'min_impurity_decrease': 9.58735442301899e-07, 'validation_fraction': 0.810021403108459, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:28:26,193] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6569229035185145, 'learning_rate': 0.04372807230380943, 'dropout_rate': 0.21137526606647042, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 1.035069386526868, 'min_weight_fraction_leaf': 0.15200254659099177, 'max_features': 'sqrt', 'min_impurity_decrease': 3.9827268139860795e-07, 'validation_fraction': 0.7420090012406269, 'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:28:51,124] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.804828042321909, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.23926982708415356, 'n_estimators': 162, 'criterion': 'squared_error', 'ccp_alpha': 0.40074886285106287, 'min_weight_fraction_leaf': 0.2779066644542128, 'max_features': 'sqrt', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:29:21,922] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6106355356441384, 'learning_rate': 0.0175381503002972, 'dropout_rate': 0.1840399348615831, 'n_estimators': 188, 'criterion': 'squared_error', 'ccp_alpha': 1.2616701535027603, 'min_weight_fraction_leaf': 0.21267322167989086, 'max_features': 'sqrt', 'min_impurity_decrease': 4.6036201699627165e-06, 'validation_fraction': 0.6710340937437342, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:29:26,148] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7251306188899954, 'learning_rate': 0.031631325965124225, 'dropout_rate': 0.36858678707018233, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.8632300312068857, 'min_weight_fraction_leaf': 0.25226351016663784, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8530056448822852e-06, 'validation_fraction': 0.6117070368402964, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 20}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.2443681907556647
Fold 2 IBS: 0.22957645244381633
Fold 3 IBS: 0.22623065748764107
Fold 4 IBS: 0.24012884639533771
Fold 5 IBS: 0.2254898421162855
[I 2024-04-13 20:29:42,358] Trial 58 finished with value: 0.23315879783974905 and parameters: {'subsample': 0.8372135933826973, 'learning_rate': 0.0933118263896949, 'dropout_rate': 0.2698372192490325, 'n_estimators': 138, 'criterion': 'squared_error', 'ccp_alpha': 0.03851666886580376, 'min_weight_fraction_leaf': 0.19014956845126402, 'max_features': 'sqrt', 'min_impurity_decrease': 5.557667048245938e-07, 'validation_fraction': 0.8240957175887902, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 58 with value: 0.23315879783974905.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:30:00,897] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7770131468684633, 'learning_rate': 0.09661144110789328, 'dropout_rate': 0.13071901615025144, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.8838088337816697, 'min_weight_fraction_leaf': 0.20200402270044698, 'max_features': 'sqrt', 'min_impurity_decrease': 2.1058318453300297e-05, 'validation_fraction': 0.7834472079756201, 'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 10}. Best is trial 58 with value: 0.23315879783974905.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:30:32,283] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8387622269560421, 'learning_rate': 0.09288013525153278, 'dropout_rate': 0.4315539960531031, 'n_estimators': 222, 'criterion': 'squared_error', 'ccp_alpha': 7.88888123252141, 'min_weight_fraction_leaf': 0.18715715168296215, 'max_features': 'sqrt', 'min_impurity_decrease': 5.658911777133895e-07, 'validation_fraction': 0.8258586719391796, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 58 with value: 0.23315879783974905.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:30:39,961] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8935334956662829, 'learning_rate': 0.08303647143365385, 'dropout_rate': 0.31926072944032013, 'n_estimators': 90, 'criterion': 'squared_error', 'ccp_alpha': 0.3409580267399826, 'min_weight_fraction_leaf': 0.13431472354808824, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1489427281229002e-06, 'validation_fraction': 0.7271755608042784, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 58 with value: 0.23315879783974905.
Fold 1 IBS: 0.24428122846636707
Fold 2 IBS: 0.22873125379430995
Fold 3 IBS: 0.22501463857482426
Fold 4 IBS: 0.23913988463506086
Fold 5 IBS: 0.22514732721679961
[I 2024-04-13 20:30:53,967] Trial 62 finished with value: 0.23246286653747233 and parameters: {'subsample': 0.8243414389621114, 'learning_rate': 0.09071124103540035, 'dropout_rate': 0.27251764057548483, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.022616672247981386, 'min_weight_fraction_leaf': 0.2309588671101351, 'max_features': 'sqrt', 'min_impurity_decrease': 2.89800118435477e-07, 'validation_fraction': 0.876556500915509, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 62 with value: 0.23246286653747233.
Fold 1 IBS: 0.24427652287227705
Fold 2 IBS: 0.22837518871279563
Fold 3 IBS: 0.22481597447693613
Fold 4 IBS: 0.2386106110830185
Fold 5 IBS: 0.22511230961028517
[I 2024-04-13 20:31:05,216] Trial 63 finished with value: 0.23223812135106253 and parameters: {'subsample': 0.8336599603007587, 'learning_rate': 0.09031916747519456, 'dropout_rate': 0.2663787938573428, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 0.017289191017379774, 'min_weight_fraction_leaf': 0.1951981514595036, 'max_features': 'sqrt', 'min_impurity_decrease': 5.414928507269899e-07, 'validation_fraction': 0.8926228431876313, 'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:31:32,271] Trial 64 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8427195777663575, 'learning_rate': 0.08784542374582861, 'dropout_rate': 0.2603466948459836, 'n_estimators': 183, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.18631742994510192, 'max_features': 'sqrt', 'min_impurity_decrease': 2.8821254066618343e-07, 'validation_fraction': 0.8718245332193061, 'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:31:43,269] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9311291803826592, 'learning_rate': 0.09901078905928126, 'dropout_rate': 0.33807906387606884, 'n_estimators': 111, 'criterion': 'squared_error', 'ccp_alpha': 0.2833036261479952, 'min_weight_fraction_leaf': 0.15643365485923125, 'max_features': 'sqrt', 'min_impurity_decrease': 4.917940757661372e-07, 'validation_fraction': 0.7588166620798954, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:32:01,699] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9043457557527063, 'learning_rate': 0.08720647345857328, 'dropout_rate': 0.27193939046019544, 'n_estimators': 154, 'criterion': 'squared_error', 'ccp_alpha': 1.4111498627316026, 'min_weight_fraction_leaf': 0.23517339076530247, 'max_features': 'sqrt', 'min_impurity_decrease': 6.086951842225704e-07, 'validation_fraction': 0.9127218528145804, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:32:04,430] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8250695857763196, 'learning_rate': 0.0911086342832341, 'dropout_rate': 0.3723000690397865, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 2.319190851430798, 'min_weight_fraction_leaf': 0.10443241497369499, 'max_features': None, 'min_impurity_decrease': 2.261430377187218e-06, 'validation_fraction': 0.8216731421530759, 'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:33:09,207] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8643375099509361, 'learning_rate': 0.0792574273284101, 'dropout_rate': 0.17115105391870955, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.2964654702152873, 'min_weight_fraction_leaf': 0.2042624403156238, 'max_features': 1, 'min_impurity_decrease': 1.613957524750281e-07, 'validation_fraction': 0.8530531167865556, 'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 5}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:33:15,217] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7567410978430598, 'learning_rate': 0.049761024237604506, 'dropout_rate': 0.23019100638335152, 'n_estimators': 72, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7461388176327838, 'min_weight_fraction_leaf': 0.2677621074656332, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012116389221552239, 'validation_fraction': 0.7845892214091239, 'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24444133138826799
Fold 2 IBS: 0.22896095650109377
Fold 3 IBS: 0.22503353478571886
Fold 4 IBS: 0.23870623781069059
Fold 5 IBS: 0.22611346338092578
[I 2024-04-13 20:33:31,585] Trial 70 finished with value: 0.23265110477333942 and parameters: {'subsample': 0.7270958059780266, 'learning_rate': 0.09025955125786853, 'dropout_rate': 0.2983051130696582, 'n_estimators': 141, 'criterion': 'squared_error', 'ccp_alpha': 0.010268271623930566, 'min_weight_fraction_leaf': 0.17606622950083872, 'max_features': 0.1, 'min_impurity_decrease': 2.9199125301850487e-07, 'validation_fraction': 0.9704707284830002, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24458360687718095
Fold 2 IBS: 0.2299707901134013
Fold 3 IBS: 0.2261844041470423
Fold 4 IBS: 0.23998297132336502
Fold 5 IBS: 0.22661245458746127
[I 2024-04-13 20:33:47,810] Trial 71 finished with value: 0.23346684540969015 and parameters: {'subsample': 0.7304805982333465, 'learning_rate': 0.0892848077436604, 'dropout_rate': 0.30534098323418335, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.17968197273495315, 'max_features': 0.1, 'min_impurity_decrease': 3.204485364940275e-07, 'validation_fraction': 0.9097007997790482, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24433296043098846
Fold 2 IBS: 0.22891833926886082
Fold 3 IBS: 0.2251270028353668
Fold 4 IBS: 0.23873976524316162
Fold 5 IBS: 0.22617521331304977
[I 2024-04-13 20:34:05,208] Trial 72 finished with value: 0.23265865621828546 and parameters: {'subsample': 0.7283770413521057, 'learning_rate': 0.08910556443694609, 'dropout_rate': 0.30374750627529123, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 0.004871280381427739, 'min_weight_fraction_leaf': 0.18085760075572085, 'max_features': 0.1, 'min_impurity_decrease': 2.066775254108449e-07, 'validation_fraction': 0.968044786321844, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:34:20,543] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6821762273698422, 'learning_rate': 0.09045775488747818, 'dropout_rate': 0.3019452359314178, 'n_estimators': 136, 'criterion': 'squared_error', 'ccp_alpha': 0.6105532472732402, 'min_weight_fraction_leaf': 0.17703318401139306, 'max_features': 0.1, 'min_impurity_decrease': 2.0200798514974308e-07, 'validation_fraction': 0.9701149300219802, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:34:40,061] Trial 74 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7101241528292079, 'learning_rate': 0.09937320265602623, 'dropout_rate': 0.3524831319725679, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 0.9837183244747926, 'min_weight_fraction_leaf': 0.1523796655343799, 'max_features': 0.1, 'min_impurity_decrease': 1.0461061192135599e-07, 'validation_fraction': 0.9135026133191511, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 8}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:35:01,593] Trial 75 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7910155215343213, 'learning_rate': 0.08588418227292206, 'dropout_rate': 0.39919431914091363, 'n_estimators': 174, 'criterion': 'squared_error', 'ccp_alpha': 0.4044325808748982, 'min_weight_fraction_leaf': 0.12844710013372065, 'max_features': 0.1, 'min_impurity_decrease': 2.4870550227046503e-07, 'validation_fraction': 0.963542393044741, 'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:35:34,619] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6388870613170881, 'learning_rate': 0.09471280191500378, 'dropout_rate': 0.26923993869351254, 'n_estimators': 199, 'criterion': 'squared_error', 'ccp_alpha': 0.30266244779681034, 'min_weight_fraction_leaf': 0.10381952675877999, 'max_features': 0.1, 'min_impurity_decrease': 1.4510472528097585e-06, 'validation_fraction': 0.8960664882855555, 'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 6}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:35:42,151] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7428517276581355, 'learning_rate': 0.07706989744762442, 'dropout_rate': 0.4476209058480567, 'n_estimators': 91, 'criterion': 'squared_error', 'ccp_alpha': 1.5888723787914292, 'min_weight_fraction_leaf': 0.16206442611838873, 'max_features': 0.1, 'min_impurity_decrease': 3.33671674086432e-07, 'validation_fraction': 0.9402673106586569, 'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 9}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:36:01,816] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7715268987373948, 'learning_rate': 0.08985503754923349, 'dropout_rate': 0.5106424386694343, 'n_estimators': 163, 'criterion': 'squared_error', 'ccp_alpha': 0.6998187558649429, 'min_weight_fraction_leaf': 0.1441624791990044, 'max_features': 0.1, 'min_impurity_decrease': 6.786191098123249e-07, 'validation_fraction': 0.867999843487921, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24716969285660575
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22894393483975858
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:36:06,876] Trial 79 finished with value: 0.23590477534833018 and parameters: {'subsample': 0.8256021281450457, 'learning_rate': 0.08314261144569621, 'dropout_rate': 0.8831816560103296, 'n_estimators': 120, 'criterion': 'squared_error', 'ccp_alpha': 0.00580501385319391, 'min_weight_fraction_leaf': 0.19542362826311155, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9982863294620272, 'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 7}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809254
[I 2024-04-13 20:36:19,058] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6683452738089981, 'learning_rate': 0.07289104058957506, 'dropout_rate': 0.684566586558272, 'n_estimators': 139, 'criterion': 'squared_error', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.17162624287712744, 'max_features': 0.1, 'min_impurity_decrease': 1.7025620478865608e-07, 'validation_fraction': 0.8367688563996566, 'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 9}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:36:29,851] Trial 81 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7212629717230318, 'learning_rate': 0.09648863423607545, 'dropout_rate': 0.32380628722047555, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.23038409491076217, 'min_weight_fraction_leaf': 0.2340042122326562, 'max_features': 0.1, 'min_impurity_decrease': 4.883007455581965e-07, 'validation_fraction': 0.9187926479398427, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24390862233245375
Fold 2 IBS: 0.22838292702570365
Fold 3 IBS: 0.22427728469643368
Fold 4 IBS: 0.23883806806788913
Fold 5 IBS: 0.22487611642069374
[I 2024-04-13 20:36:44,463] Trial 82 finished with value: 0.23205660370863482 and parameters: {'subsample': 0.7424094275541511, 'learning_rate': 0.09321912358204075, 'dropout_rate': 0.2934062535264489, 'n_estimators': 114, 'criterion': 'squared_error', 'ccp_alpha': 0.01778369806197142, 'min_weight_fraction_leaf': 0.21126686784700288, 'max_features': 'log2', 'min_impurity_decrease': 3.4224047595443053e-07, 'validation_fraction': 0.9694941758991367, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:36:54,447] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6936370685985978, 'learning_rate': 0.07973196831123328, 'dropout_rate': 0.28615445184158467, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 1.129152915921092, 'min_weight_fraction_leaf': 0.18903520337674806, 'max_features': 'log2', 'min_impurity_decrease': 2.9795925135078545e-07, 'validation_fraction': 0.9720656242622133, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:36:58,834] Trial 84 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7766180104167335, 'learning_rate': 0.09249006200550622, 'dropout_rate': 0.305574256636177, 'n_estimators': 53, 'criterion': 'squared_error', 'ccp_alpha': 0.6566133054967586, 'min_weight_fraction_leaf': 0.24759719188654067, 'max_features': 'log2', 'min_impurity_decrease': 1.3396039034492153e-07, 'validation_fraction': 0.892099453138701, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.2289818680697771
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:37:26,878] Trial 85 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8541716599279708, 'learning_rate': 0.08839641653849994, 'dropout_rate': 0.24521378095924606, 'n_estimators': 156, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3309010043491877, 'min_weight_fraction_leaf': 0.17837522472890427, 'max_features': 'log2', 'min_impurity_decrease': 8.040870911608097e-07, 'validation_fraction': 0.9314770718841436, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:37:36,841] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8087595997030689, 'learning_rate': 0.08488131639682682, 'dropout_rate': 0.3757108201252311, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 0.8619058019946999, 'min_weight_fraction_leaf': 0.034374369575269015, 'max_features': 'log2', 'min_impurity_decrease': 1.9734264215079192e-07, 'validation_fraction': 0.8644333526627775, 'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:37:49,419] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7460732631507769, 'learning_rate': 0.09440704087578497, 'dropout_rate': 0.34429888870538994, 'n_estimators': 117, 'criterion': 'squared_error', 'ccp_alpha': 0.23605873926111243, 'min_weight_fraction_leaf': 0.20611127721053588, 'max_features': 0.1, 'min_impurity_decrease': 3.605164135559099e-07, 'validation_fraction': 0.9533190908371042, 'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:38:19,956] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6413430388178152, 'learning_rate': 0.0973528090376961, 'dropout_rate': 0.26912242502602596, 'n_estimators': 174, 'criterion': 'squared_error', 'ccp_alpha': 0.5807061908097002, 'min_weight_fraction_leaf': 0.16723537370276506, 'max_features': 0.1, 'min_impurity_decrease': 1.190634063232502e-06, 'validation_fraction': 0.8005899065401637, 'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24220714862378384
Fold 2 IBS: 0.22705284477038132
Fold 3 IBS: 0.22374120154251026
Fold 4 IBS: 0.23761138561741843
Fold 5 IBS: 0.22312495335199894
[I 2024-04-13 20:38:43,138] Trial 89 finished with value: 0.23074750678121858 and parameters: {'subsample': 0.38730242337646104, 'learning_rate': 0.08109800836387941, 'dropout_rate': 0.18122999434960108, 'n_estimators': 146, 'criterion': 'squared_error', 'ccp_alpha': 0.018794864735403906, 'min_weight_fraction_leaf': 0.14130782512257434, 'max_features': None, 'min_impurity_decrease': 6.04312953486063e-07, 'validation_fraction': 0.9728621916133924, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 89 with value: 0.23074750678121858.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:39:24,820] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4301287904403204, 'learning_rate': 0.08064135841350613, 'dropout_rate': 0.18182381147209734, 'n_estimators': 216, 'criterion': 'squared_error', 'ccp_alpha': 5.797253839038365, 'min_weight_fraction_leaf': 0.11344111466651854, 'max_features': 1, 'min_impurity_decrease': 2.7530646126399795e-06, 'validation_fraction': 0.9992764821735842, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 89 with value: 0.23074750678121858.
Fold 1 IBS: 0.2409482065148207
Fold 2 IBS: 0.22548074688500788
Fold 3 IBS: 0.22218016838847504
Fold 4 IBS: 0.23628101146650415
Fold 5 IBS: 0.22161830859386844
[I 2024-04-13 20:39:49,115] Trial 91 finished with value: 0.22930168836973525 and parameters: {'subsample': 0.3646963250854607, 'learning_rate': 0.09255241886126767, 'dropout_rate': 0.12363276406693596, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 0.03832008885345805, 'min_weight_fraction_leaf': 0.14198218649980035, 'max_features': None, 'min_impurity_decrease': 6.12703415921239e-07, 'validation_fraction': 0.965806971606102, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24720356529080675
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:40:13,251] Trial 92 finished with value: 0.23591913648117407 and parameters: {'subsample': 0.37023851203307184, 'learning_rate': 0.08893737188983004, 'dropout_rate': 0.20172874940955723, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.25929761360970466, 'min_weight_fraction_leaf': 0.14091910204137698, 'max_features': None, 'min_impurity_decrease': 1.670575123081423e-06, 'validation_fraction': 0.9646916032715627, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:40:31,144] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3393392217612321, 'learning_rate': 0.08484939828620154, 'dropout_rate': 0.1330785179258292, 'n_estimators': 141, 'criterion': 'squared_error', 'ccp_alpha': 0.5271800261864423, 'min_weight_fraction_leaf': 0.22342629975429745, 'max_features': None, 'min_impurity_decrease': 6.529634824832721e-07, 'validation_fraction': 0.9250469615937894, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:40:40,847] Trial 94 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.30155497875372905, 'learning_rate': 0.09226836699183699, 'dropout_rate': 0.16486788507480765, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 4.0703783464897505, 'min_weight_fraction_leaf': 0.08717516087188838, 'max_features': None, 'min_impurity_decrease': 4.324897116213418e-07, 'validation_fraction': 0.902599975518271, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:40:52,541] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.22711241501967083, 'learning_rate': 0.09399734029654892, 'dropout_rate': 0.23424050775181726, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.2155841604325495, 'min_weight_fraction_leaf': 0.1987273188587709, 'max_features': None, 'min_impurity_decrease': 0.0002775108319921543, 'validation_fraction': 0.9754822510610521, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 8}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24720275004054537
Fold 2 IBS: 0.23200270748604027
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:41:12,381] Trial 96 finished with value: 0.23591153802074527 and parameters: {'subsample': 0.5095341352345704, 'learning_rate': 0.08725364328306122, 'dropout_rate': 0.3223450290700977, 'n_estimators': 169, 'criterion': 'squared_error', 'ccp_alpha': 0.1763548129966652, 'min_weight_fraction_leaf': 0.18056333859719206, 'max_features': None, 'min_impurity_decrease': 8.711621987475722e-07, 'validation_fraction': 0.9501887884981254, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:41:36,102] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38054192896008343, 'learning_rate': 0.0907069703578099, 'dropout_rate': 0.29952255515083975, 'n_estimators': 185, 'criterion': 'squared_error', 'ccp_alpha': 0.8146747487056372, 'min_weight_fraction_leaf': 0.12179773041599615, 'max_features': None, 'min_impurity_decrease': 2.402128990085841e-07, 'validation_fraction': 0.8821221020751453, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:42:05,612] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.46077614751832996, 'learning_rate': 0.09701740438937595, 'dropout_rate': 0.25455243694522434, 'n_estimators': 199, 'criterion': 'friedman_mse', 'ccp_alpha': 4.816291450322713, 'min_weight_fraction_leaf': 0.14615364156535707, 'max_features': None, 'min_impurity_decrease': 1.4006375376158358e-07, 'validation_fraction': 0.9833042102806464, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 6}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24343373022583664
Fold 2 IBS: 0.2272980963057972
Fold 3 IBS: 0.22299173682453308

Fold 4 IBS: 0.23852342496708018
Fold 5 IBS: 0.22486084489133845
[I 2024-04-13 20:42:22,257] Trial 99 finished with value: 0.23142156664291713 and parameters: {'subsample': 0.40791967441342253, 'learning_rate': 0.07712333235501795, 'dropout_rate': 0.19859974199600133, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 0.004426170739568851, 'min_weight_fraction_leaf': 0.16314282359709542, 'max_features': 'log2', 'min_impurity_decrease': 5.353566353972388e-07, 'validation_fraction': 0.1604355124738367, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 91 with value: 0.22930168836973525.


* Best trial for IBS:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.22930168836973525], datetime_start=datetime.datetime(2024, 4, 13, 20, 39, 24, 831303), datetime_complete=datetime.datetime(2024, 4, 13, 20, 39, 49, 113073), params={'subsample': 0.3646963250854607, 'learning_rate': 0.09255241886126767, 'dropout_rate': 0.12363276406693596, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 0.03832008885345805, 'min_weight_fraction_leaf': 0.14198218649980035, 'max_features': None, 'min_impurity_decrease': 6.12703415921239e-07, 'validation_fraction': 0.965806971606102, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 4}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=91, value=None)


* Best Score for IBS:
 0.22930168836973525

In [76]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [77]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.648
train_ibs:  0.229

#### Test

In [78]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [79]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.02647951541473475,
                                 criterion='squared_error',
                                 dropout_rate=0.14303111133639826,
                                 learning_rate=0.05317196534413593,
                                 max_depth=19, max_features=0.1,
                                 max_leaf_nodes=15,
                                 min_impurity_decrease=7.356647091617949e-06,
                                 min_samples_leaf=17, min_samples_split=19,
                                 min_weight_fraction_leaf=0.35066087197674667,
                                 n_estimators=78, random_state=123,
                                 subsample=0.9736544653699906,
                                 validation_fraction=0.6117331205297228)

C-index score: 0.639

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03832008885345805,
                                 criterion='squared_error',
                                 dropout_rate=0.12363276406693596,
                                 learning_rate=0.09255241886126767, max_depth=4,
                                 max_leaf_nodes=15,
                                 min_impurity_decrease=6.12703415921239e-07,
                                 min_samples_leaf=16, min_samples_split=13,
                                 min_weight_fraction_leaf=0.14198218649980035,
                                 n_estimators=143, random_state=123,
                                 subsample=0.3646963250854607,
                                 validation_fraction=0.965806971606102)

IBS: 0.221

In [80]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [81]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [82]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 20:42:27,329] A new study created in memory with name: no-name-7d3b3870-f3c9-4a92-a4f8-712a3e3eb8f7

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.501937984496124
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 20:42:29,632] Trial 0 finished with value: 0.5612882548986675 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.5612882548986675.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 20:42:48,458] Trial 1 finished with value: 0.5609458982840367 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.5612882548986675.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.501937984496124
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 20:42:52,113] Trial 2 finished with value: 0.5727048667161739 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.5727048667161739.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:42:56,680] Trial 3 finished with value: 0.5804752810967445 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.5804752810967445.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:43:03,967] Trial 4 finished with value: 0.5884599615556318 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.5884599615556318.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.48643410852713176
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 20:43:12,990] Trial 5 finished with value: 0.5705109517740391 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.5884599615556318.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.48643410852713176
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 20:43:17,040] Trial 6 finished with value: 0.5581874797048691 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.5884599615556318.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.501937984496124
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:43:17,919] Trial 7 finished with value: 0.5945939816993409 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.5945939816993409.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 20:43:22,553] Trial 8 finished with value: 0.574964192743856 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.5945939816993409.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.501937984496124
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:43:36,797] Trial 9 finished with value: 0.58147827192853 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.5945939816993409.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.5321888412017167
[I 2024-04-13 20:43:37,481] Trial 10 finished with value: 0.5490001447667268 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.5945939816993409.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6148936170212767
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:43:48,898] Trial 11 finished with value: 0.6046970873938551 and parameters: {'subsample': 0.1913192016083392, 'dropout_rate': 0.10580803679784617, 'n_estimators': 350, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.6046970873938551.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6276595744680851
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:43:57,506] Trial 12 finished with value: 0.6147821286703798 and parameters: {'subsample': 0.11615582976955166, 'dropout_rate': 0.7007608116967414, 'n_estimators': 331, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.6147821286703798.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6276595744680851
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:44:06,852] Trial 13 finished with value: 0.6139237595716674 and parameters: {'subsample': 0.10945381685168351, 'dropout_rate': 0.6867275669911717, 'n_estimators': 339, 'learning_rate': 0.09914998942829482}. Best is trial 12 with value: 0.6147821286703798.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6276595744680851
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:44:16,660] Trial 14 finished with value: 0.6139237595716674 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7082972363281074, 'n_estimators': 334, 'learning_rate': 0.09980885279701814}. Best is trial 12 with value: 0.6147821286703798.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 20:44:24,290] Trial 15 finished with value: 0.6193869827160372 and parameters: {'subsample': 0.10121574416505308, 'dropout_rate': 0.7949832737733025, 'n_estimators': 307, 'learning_rate': 0.08616677729964022}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5765957446808511
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:44:35,243] Trial 16 finished with value: 0.5924158251844429 and parameters: {'subsample': 0.29391461974521166, 'dropout_rate': 0.9733961081825167, 'n_estimators': 416, 'learning_rate': 0.08664241229927826}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:44:43,689] Trial 17 finished with value: 0.5856797638397391 and parameters: {'subsample': 0.36043621400324377, 'dropout_rate': 0.8264623285827045, 'n_estimators': 274, 'learning_rate': 0.08297745058468912}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:44:57,942] Trial 18 finished with value: 0.6072780186099809 and parameters: {'subsample': 0.21158798895447894, 'dropout_rate': 0.7754555164962194, 'n_estimators': 426, 'learning_rate': 0.08278758209333262}. Best is trial 15 with value: 0.6193869827160372.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:45:05,049] Trial 19 finished with value: 0.5849193075659749 and parameters: {'subsample': 0.3739805428810522, 'dropout_rate': 0.6293352695898036, 'n_estimators': 295, 'learning_rate': 0.09107738339755381}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:45:18,039] Trial 20 finished with value: 0.6089732648436864 and parameters: {'subsample': 0.179916923106687, 'dropout_rate': 0.5777838682216713, 'n_estimators': 416, 'learning_rate': 0.06551866052750378}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6319148936170212
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:45:25,104] Trial 21 finished with value: 0.6147748234014547 and parameters: {'subsample': 0.11005754745416128, 'dropout_rate': 0.7643383466786142, 'n_estimators': 305, 'learning_rate': 0.09628980606513493}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 20:45:32,821] Trial 22 finished with value: 0.6193869827160372 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.7872544899067938, 'n_estimators': 305, 'learning_rate': 0.09975973767452531}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.5851063829787234
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:45:42,651] Trial 23 finished with value: 0.6017372531063454 and parameters: {'subsample': 0.2605721969185794, 'dropout_rate': 0.8937330000941024, 'n_estimators': 384, 'learning_rate': 0.08013909093253938}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:45:47,183] Trial 24 finished with value: 0.6113599787456875 and parameters: {'subsample': 0.16824204654906352, 'dropout_rate': 0.9801732147191013, 'n_estimators': 231, 'learning_rate': 0.09013495546212062}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 20:45:53,653] Trial 25 finished with value: 0.5623048657967697 and parameters: {'subsample': 0.9684217810899436, 'dropout_rate': 0.8019147284879026, 'n_estimators': 309, 'learning_rate': 0.07892220112961018}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:45:56,200] Trial 26 finished with value: 0.594751445086519 and parameters: {'subsample': 0.3024492032892053, 'dropout_rate': 0.5961610240301278, 'n_estimators': 140, 'learning_rate': 0.09378524038489341}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.501937984496124
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:46:01,293] Trial 27 finished with value: 0.5777011904341774 and parameters: {'subsample': 0.41837107426637904, 'dropout_rate': 0.7410276122414056, 'n_estimators': 256, 'learning_rate': 0.07558633155455549}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.4941860465116279
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:46:12,547] Trial 28 finished with value: 0.575065631216432 and parameters: {'subsample': 0.6086868424612186, 'dropout_rate': 0.837863147308239, 'n_estimators': 447, 'learning_rate': 0.042023319062260985}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 20:46:21,008] Trial 29 finished with value: 0.5723980461685121 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.9192302232226586, 'n_estimators': 386, 'learning_rate': 0.06046208382653473}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5135658914728682
Fold 3 C-index: 0.5893617021276596
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:46:22,490] Trial 30 finished with value: 0.5943492376494438 and parameters: {'subsample': 0.23708665675308496, 'dropout_rate': 0.5333522330844954, 'n_estimators': 89, 'learning_rate': 0.08567246449251414}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:46:30,279] Trial 31 finished with value: 0.6168118754198998 and parameters: {'subsample': 0.10801177869921114, 'dropout_rate': 0.7744979175065152, 'n_estimators': 308, 'learning_rate': 0.09787723986909927}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:46:40,161] Trial 32 finished with value: 0.6136413475669802 and parameters: {'subsample': 0.1532767376991012, 'dropout_rate': 0.6254471986890558, 'n_estimators': 305, 'learning_rate': 0.0997039115213789}. Best is trial 15 with value: 0.6193869827160372.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 20:46:47,108] Trial 33 finished with value: 0.6209005899946404 and parameters: {'subsample': 0.10123848117934434, 'dropout_rate': 0.7834352067983904, 'n_estimators': 238, 'learning_rate': 0.0922728686600945}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:46:52,622] Trial 34 finished with value: 0.6113452412210021 and parameters: {'subsample': 0.16748998111629382, 'dropout_rate': 0.8077605099735469, 'n_estimators': 236, 'learning_rate': 0.06834561489591279}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:46:56,082] Trial 35 finished with value: 0.605877188667846 and parameters: {'subsample': 0.21727726641756584, 'dropout_rate': 0.47506925996386407, 'n_estimators': 156, 'learning_rate': 0.09220897886274729}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5765957446808511
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:47:01,611] Trial 36 finished with value: 0.5858319277454705 and parameters: {'subsample': 0.2848188009185534, 'dropout_rate': 0.933283456542877, 'n_estimators': 276, 'learning_rate': 0.0737315202731133}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:47:05,975] Trial 37 finished with value: 0.6112257094454996 and parameters: {'subsample': 0.15246931221741755, 'dropout_rate': 0.7621022900062648, 'n_estimators': 214, 'learning_rate': 0.0855880362644833}. Best is trial 33 with value: 0.6209005899946404.

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5765957446808511
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:47:10,073] Trial 38 finished with value: 0.5835757587986465 and parameters: {'subsample': 0.32929695725910635, 'dropout_rate': 0.3720991365773877, 'n_estimators': 188, 'learning_rate': 0.09321185753440044}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.5851063829787234
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:47:19,136] Trial 39 finished with value: 0.5994558842850526 and parameters: {'subsample': 0.2296067526961567, 'dropout_rate': 0.8600360752966183, 'n_estimators': 367, 'learning_rate': 0.0777390157253494}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6319148936170212
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:47:25,585] Trial 40 finished with value: 0.6164516241997255 and parameters: {'subsample': 0.10545006120121359, 'dropout_rate': 0.27073406810212547, 'n_estimators': 248, 'learning_rate': 0.07116265758675469}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6276595744680851
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 20:47:33,011] Trial 41 finished with value: 0.6204102176623453 and parameters: {'subsample': 0.1044600331519512, 'dropout_rate': 0.3148196375868446, 'n_estimators': 261, 'learning_rate': 0.07046237843845496}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:47:41,079] Trial 42 finished with value: 0.6075576973768662 and parameters: {'subsample': 0.15556873719503106, 'dropout_rate': 0.2678832413007815, 'n_estimators': 273, 'learning_rate': 0.08761707467936247}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:47:49,235] Trial 43 finished with value: 0.5998477895585153 and parameters: {'subsample': 0.20979862666572763, 'dropout_rate': 0.4306710267524951, 'n_estimators': 289, 'learning_rate': 0.05804821512668846}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 20:47:59,030] Trial 44 finished with value: 0.6184816678054667 and parameters: {'subsample': 0.13073724835614484, 'dropout_rate': 0.3089648723925339, 'n_estimators': 321, 'learning_rate': 0.06523605428553468}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5893617021276596
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:48:04,277] Trial 45 finished with value: 0.5894499971075584 and parameters: {'subsample': 0.25322516806014495, 'dropout_rate': 0.3110143452301946, 'n_estimators': 212, 'learning_rate': 0.07014383299755068}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 20:48:15,644] Trial 46 finished with value: 0.6159648327913446 and parameters: {'subsample': 0.14510105848230126, 'dropout_rate': 0.18881383698433007, 'n_estimators': 329, 'learning_rate': 0.06469273767108769}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.4941860465116279
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 20:48:21,099] Trial 47 finished with value: 0.5597378673017683 and parameters: {'subsample': 0.7072326294822995, 'dropout_rate': 0.22278285410811652, 'n_estimators': 237, 'learning_rate': 0.008209618821055878}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:48:32,639] Trial 48 finished with value: 0.5848465946154955 and parameters: {'subsample': 0.43887458137368346, 'dropout_rate': 0.33192723860369455, 'n_estimators': 374, 'learning_rate': 0.0494246576171421}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:48:39,319] Trial 49 finished with value: 0.6090243588436114 and parameters: {'subsample': 0.1861830169994726, 'dropout_rate': 0.4174112622772975, 'n_estimators': 261, 'learning_rate': 0.08162100006045118}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.501937984496124
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 20:48:49,792] Trial 50 finished with value: 0.5741278664387541 and parameters: {'subsample': 0.5299451000854026, 'dropout_rate': 0.5102004991470195, 'n_estimators': 357, 'learning_rate': 0.06437247677741277}. Best is trial 33 with value: 0.6209005899946404.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 20:48:59,212] Trial 51 finished with value: 0.6269927299463951 and parameters: {'subsample': 0.10803471257567032, 'dropout_rate': 0.10355008884313799, 'n_estimators': 308, 'learning_rate': 0.09604343153434695}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:49:09,120] Trial 52 finished with value: 0.615370981091776 and parameters: {'subsample': 0.13446553100787184, 'dropout_rate': 0.14876213644424657, 'n_estimators': 323, 'learning_rate': 0.05427331286220499}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6234042553191489
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:49:16,934] Trial 53 finished with value: 0.6079712216008831 and parameters: {'subsample': 0.18610631879410355, 'dropout_rate': 0.10945383672954265, 'n_estimators': 285, 'learning_rate': 0.09457469998905098}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:49:25,811] Trial 54 finished with value: 0.6128445348179763 and parameters: {'subsample': 0.14689046517517632, 'dropout_rate': 0.6688885474971952, 'n_estimators': 347, 'learning_rate': 0.09070753994171692}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 20:49:36,411] Trial 55 finished with value: 0.6186628829175126 and parameters: {'subsample': 0.1072818855403775, 'dropout_rate': 0.23524631734270562, 'n_estimators': 325, 'learning_rate': 0.07653796361771664}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.6159695817490495

Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 20:49:52,126] Trial 56 finished with value: 0.6022270712047562 and parameters: {'subsample': 0.19882445352995062, 'dropout_rate': 0.18638851640016268, 'n_estimators': 402, 'learning_rate': 0.0837762614019821}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:49:57,111] Trial 57 finished with value: 0.6218244937617421 and parameters: {'subsample': 0.10149799859003725, 'dropout_rate': 0.13926195162146968, 'n_estimators': 198, 'learning_rate': 0.0879106588019078}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:50:01,286] Trial 58 finished with value: 0.5999383971145382 and parameters: {'subsample': 0.2643452415507289, 'dropout_rate': 0.1258521170646615, 'n_estimators': 176, 'learning_rate': 0.08919278303661785}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 20:50:03,617] Trial 59 finished with value: 0.618724439267221 and parameters: {'subsample': 0.10171829498369382, 'dropout_rate': 0.1700187286716513, 'n_estimators': 114, 'learning_rate': 0.09559819199809876}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 20:50:07,384] Trial 60 finished with value: 0.5723980461685121 and parameters: {'subsample': 0.8369946074565486, 'dropout_rate': 0.7263246826189685, 'n_estimators': 196, 'learning_rate': 0.03136696153263342}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 20:50:09,396] Trial 61 finished with value: 0.6169898064642526 and parameters: {'subsample': 0.13300334074160353, 'dropout_rate': 0.174300107903655, 'n_estimators': 102, 'learning_rate': 0.09635552522756544}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:50:10,758] Trial 62 finished with value: 0.6065778273185016 and parameters: {'subsample': 0.10594163089135693, 'dropout_rate': 0.14619646800098027, 'n_estimators': 62, 'learning_rate': 0.09473079234787404}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:50:13,584] Trial 63 finished with value: 0.612142053970006 and parameters: {'subsample': 0.1750207648472254, 'dropout_rate': 0.2205178594196074, 'n_estimators': 139, 'learning_rate': 0.0869422767505364}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 20:50:19,543] Trial 64 finished with value: 0.6241952216541858 and parameters: {'subsample': 0.1018358506487617, 'dropout_rate': 0.10100490684909244, 'n_estimators': 221, 'learning_rate': 0.09940864834261755}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6191489361702127
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:50:25,597] Trial 65 finished with value: 0.6046897821249299 and parameters: {'subsample': 0.2162885983111256, 'dropout_rate': 0.1126613467366902, 'n_estimators': 224, 'learning_rate': 0.09880305806910028}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:50:34,172] Trial 66 finished with value: 0.5791986853520636 and parameters: {'subsample': 0.6194399591985713, 'dropout_rate': 0.1345298137166429, 'n_estimators': 252, 'learning_rate': 0.09045509190837346}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6191489361702127
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 20:50:38,565] Trial 67 finished with value: 0.6155935519572342 and parameters: {'subsample': 0.1365663510634085, 'dropout_rate': 0.8575727825093084, 'n_estimators': 164, 'learning_rate': 0.08133521219022932}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6191489361702127
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:50:44,545] Trial 68 finished with value: 0.6093504325924635 and parameters: {'subsample': 0.17362871439874694, 'dropout_rate': 0.20828183148523874, 'n_estimators': 219, 'learning_rate': 0.09251390819875019}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:50:51,437] Trial 69 finished with value: 0.5956389923783808 and parameters: {'subsample': 0.3256450971739503, 'dropout_rate': 0.10267185046614308, 'n_estimators': 206, 'learning_rate': 0.08403050744828938}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:51:01,546] Trial 70 finished with value: 0.5988445618229965 and parameters: {'subsample': 0.23623245310708774, 'dropout_rate': 0.2454372405517462, 'n_estimators': 292, 'learning_rate': 0.09933480139775945}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 20:51:04,357] Trial 71 finished with value: 0.622744292223328 and parameters: {'subsample': 0.10674228201966897, 'dropout_rate': 0.1629516940800281, 'n_estimators': 126, 'learning_rate': 0.09634631753895097}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:51:13,094] Trial 72 finished with value: 0.6169825011953274 and parameters: {'subsample': 0.13156602161722059, 'dropout_rate': 0.1635105371836204, 'n_estimators': 265, 'learning_rate': 0.08883012649286713}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.6977186311787072
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 20:51:13,639] Trial 73 finished with value: 0.5990606907664345 and parameters: {'subsample': 0.1974367025595512, 'dropout_rate': 0.8167021117096385, 'n_estimators': 8, 'learning_rate': 0.09689634546370388}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 20:51:20,659] Trial 74 finished with value: 0.6249641046949124 and parameters: {'subsample': 0.10087615233458334, 'dropout_rate': 0.2004423701492945, 'n_estimators': 245, 'learning_rate': 0.09387815341459589}. Best is trial 51 with value: 0.6269927299463951.

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:51:23,331] Trial 75 finished with value: 0.6065165678250144 and parameters: {'subsample': 0.16680826475977178, 'dropout_rate': 0.20160632622658736, 'n_estimators': 129, 'learning_rate': 0.09130758755124356}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 20:51:29,956] Trial 76 finished with value: 0.6204377235275664 and parameters: {'subsample': 0.12709038025046163, 'dropout_rate': 0.1407232886190834, 'n_estimators': 243, 'learning_rate': 0.08539081018200488}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:51:35,591] Trial 77 finished with value: 0.6231842648066858 and parameters: {'subsample': 0.12200195714646908, 'dropout_rate': 0.13428899694121602, 'n_estimators': 187, 'learning_rate': 0.07860454691096054}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 20:51:40,716] Trial 78 finished with value: 0.6186919341238271 and parameters: {'subsample': 0.12847312114369563, 'dropout_rate': 0.14463250890980353, 'n_estimators': 189, 'learning_rate': 0.08013451511992921}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:51:45,153] Trial 79 finished with value: 0.6143534396746281 and parameters: {'subsample': 0.15952544021800116, 'dropout_rate': 0.12780812163830024, 'n_estimators': 162, 'learning_rate': 0.09335796339639951}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:51:52,210] Trial 80 finished with value: 0.6035812093087027 and parameters: {'subsample': 0.19101593905581793, 'dropout_rate': 0.28314700149324157, 'n_estimators': 237, 'learning_rate': 0.08559752651370707}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 20:51:57,414] Trial 81 finished with value: 0.6148048051268148 and parameters: {'subsample': 0.12679424356035285, 'dropout_rate': 0.10148018404789075, 'n_estimators': 201, 'learning_rate': 0.08841383995251031}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:52:04,748] Trial 82 finished with value: 0.6126365744903682 and parameters: {'subsample': 0.154297944809695, 'dropout_rate': 0.1564598870030611, 'n_estimators': 245, 'learning_rate': 0.0745800895327701}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 20:52:11,075] Trial 83 finished with value: 0.6249567994259871 and parameters: {'subsample': 0.10220937805401217, 'dropout_rate': 0.18986331799396491, 'n_estimators': 225, 'learning_rate': 0.09669610049758684}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6574468085106383
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:52:15,619] Trial 84 finished with value: 0.6231083947753481 and parameters: {'subsample': 0.12301399133963181, 'dropout_rate': 0.17866925137999967, 'n_estimators': 183, 'learning_rate': 0.0971089217392421}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:52:20,349] Trial 85 finished with value: 0.6133970307641325 and parameters: {'subsample': 0.15981600660458395, 'dropout_rate': 0.18589750795940616, 'n_estimators': 178, 'learning_rate': 0.09732441713144231}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:52:23,517] Trial 86 finished with value: 0.5958642930776479 and parameters: {'subsample': 0.2173758627873696, 'dropout_rate': 0.19803560321406716, 'n_estimators': 148, 'learning_rate': 0.0999450961792915}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6319148936170212
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:52:29,432] Trial 87 finished with value: 0.619559280819393 and parameters: {'subsample': 0.10090459482917605, 'dropout_rate': 0.24561752806170253, 'n_estimators': 225, 'learning_rate': 0.09533718836110953}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 20:52:34,075] Trial 88 finished with value: 0.6257593721028231 and parameters: {'subsample': 0.12391951940697754, 'dropout_rate': 0.16622266183390416, 'n_estimators': 188, 'learning_rate': 0.09333199335304607}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:52:38,269] Trial 89 finished with value: 0.5928224679825909 and parameters: {'subsample': 0.24512732026361206, 'dropout_rate': 0.16798289514482762, 'n_estimators': 188, 'learning_rate': 0.09350708082025076}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6148936170212767
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 20:52:42,698] Trial 90 finished with value: 0.6147788446026867 and parameters: {'subsample': 0.17911662265150882, 'dropout_rate': 0.21792654485099588, 'n_estimators': 167, 'learning_rate': 0.097738045357274}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 20:52:47,912] Trial 91 finished with value: 0.6189726074019145 and parameters: {'subsample': 0.12150962886090355, 'dropout_rate': 0.12139233956773765, 'n_estimators': 209, 'learning_rate': 0.09184905964630961}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6106382978723405
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:52:53,080] Trial 92 finished with value: 0.6038460235640678 and parameters: {'subsample': 0.14430581086223349, 'dropout_rate': 0.28639225327403595, 'n_estimators': 225, 'learning_rate': 0.09598978211844207}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.6615969581749049

Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 20:52:56,313] Trial 93 finished with value: 0.6265345659012727 and parameters: {'subsample': 0.12099747974417865, 'dropout_rate': 0.16069341444613053, 'n_estimators': 151, 'learning_rate': 0.08981229190311496}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:52:58,957] Trial 94 finished with value: 0.6176039857469523 and parameters: {'subsample': 0.12379530779519904, 'dropout_rate': 0.177927489440208, 'n_estimators': 125, 'learning_rate': 0.08848797848518258}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:53:02,451] Trial 95 finished with value: 0.620631073317324 and parameters: {'subsample': 0.15173727377637627, 'dropout_rate': 0.23342035115234452, 'n_estimators': 151, 'learning_rate': 0.09383861934382617}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:53:07,268] Trial 96 finished with value: 0.5990947655405112 and parameters: {'subsample': 0.19395563043983238, 'dropout_rate': 0.15789920218215395, 'n_estimators': 194, 'learning_rate': 0.09007342891066017}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6574468085106383
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 20:53:11,817] Trial 97 finished with value: 0.6239667638740605 and parameters: {'subsample': 0.12228674024692533, 'dropout_rate': 0.12917514425752255, 'n_estimators': 177, 'learning_rate': 0.09768786530142967}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:53:16,530] Trial 98 finished with value: 0.6064623167442311 and parameters: {'subsample': 0.16692128768574055, 'dropout_rate': 0.2002801186536965, 'n_estimators': 182, 'learning_rate': 0.09765500835458799}. Best is trial 51 with value: 0.6269927299463951.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.6387832699619772

[I 2024-04-13 20:53:18,622] A new study created in memory with name: no-name-c8f19554-edc7-4354-ae18-91b776887c39

Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 20:53:18,603] Trial 99 finished with value: 0.6123001047904044 and parameters: {'subsample': 0.14531725751929345, 'dropout_rate': 0.12345824635691094, 'n_estimators': 94, 'learning_rate': 0.09505403708444224}. Best is trial 51 with value: 0.6269927299463951.


* Best trial for C-index:
 FrozenTrial(number=51, state=TrialState.COMPLETE, values=[0.6269927299463951], datetime_start=datetime.datetime(2024, 4, 13, 20, 48, 49, 801643), datetime_complete=datetime.datetime(2024, 4, 13, 20, 48, 59, 211793), params={'subsample': 0.10803471257567032, 'dropout_rate': 0.10355008884313799, 'n_estimators': 308, 'learning_rate': 0.09604343153434695}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=51, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.10803471257567032, 'dropout_rate': 0.10355008884313799, 'n_estimators': 308, 'learning_rate': 0.09604343153434695}


* Best Score for C-index:
 0.6269927299463951

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2768605959166274
Fold 2 IBS: 0.28392142909752927
Fold 3 IBS: 0.26390420137497594
Fold 4 IBS: 0.25349763354087507
Fold 5 IBS: 0.23049650269649638
[I 2024-04-13 20:53:20,865] Trial 0 finished with value: 0.26173607252530084 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.26173607252530084.
Fold 1 IBS: 0.3314083926697305
Fold 2 IBS: 0.4314078642168022
Fold 3 IBS: 0.32274777047798786
Fold 4 IBS: 0.31347938834448036
Fold 5 IBS: 0.339376702626222
[I 2024-04-13 20:53:39,444] Trial 1 finished with value: 0.3476840236670446 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.26173607252530084.
Fold 1 IBS: 0.3091855222340186
Fold 2 IBS: 0.3583277621663848
Fold 3 IBS: 0.3047589201819723
Fold 4 IBS: 0.3052677188060822
Fold 5 IBS: 0.3100934076743383
[I 2024-04-13 20:53:43,572] Trial 2 finished with value: 0.3175266662125592 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.26173607252530084.
Fold 1 IBS: 0.30788755683819485
Fold 2 IBS: 0.35725042965541515
Fold 3 IBS: 0.3028817068967989
Fold 4 IBS: 0.33590906138453525
Fold 5 IBS: 0.2665679761465616
[I 2024-04-13 20:53:48,538] Trial 3 finished with value: 0.31409934618430113 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.26173607252530084.
Fold 1 IBS: 0.3087039301353936
Fold 2 IBS: 0.35692712924779835
Fold 3 IBS: 0.29672717766595297
Fold 4 IBS: 0.3490232837728386
Fold 5 IBS: 0.2800074398407403
[I 2024-04-13 20:53:56,619] Trial 4 finished with value: 0.31827779213254476 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.26173607252530084.
Fold 1 IBS: 0.33292831395748784
Fold 2 IBS: 0.445013283923208
Fold 3 IBS: 0.32077526729505473
Fold 4 IBS: 0.32392889720844487
Fold 5 IBS: 0.33923818447315957
[I 2024-04-13 20:54:05,218] Trial 5 finished with value: 0.352376789371471 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.26173607252530084.
Fold 1 IBS: 0.2583770894605203
Fold 2 IBS: 0.2753174659918347
Fold 3 IBS: 0.24099846394278826
Fold 4 IBS: 0.24152759447093639
Fold 5 IBS: 0.21760040361445157
[I 2024-04-13 20:54:08,738] Trial 6 finished with value: 0.24676420349610625 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.24676420349610625.
Fold 1 IBS: 0.24449081430179984
Fold 2 IBS: 0.23999715690352616
Fold 3 IBS: 0.21729049888223848
Fold 4 IBS: 0.2425225050828824
Fold 5 IBS: 0.21429196147972912
[I 2024-04-13 20:54:09,762] Trial 7 finished with value: 0.2317185873300352 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.27473949169980044
Fold 2 IBS: 0.2956902991894394
Fold 3 IBS: 0.26687602440026015
Fold 4 IBS: 0.27029715420403405
Fold 5 IBS: 0.22610047650933945
[I 2024-04-13 20:54:14,470] Trial 8 finished with value: 0.2667406892005747 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.31944546154036996
Fold 2 IBS: 0.39612360699420396
Fold 3 IBS: 0.3210486304883838
Fold 4 IBS: 0.36711398518772687
Fold 5 IBS: 0.3390242043616515
[I 2024-04-13 20:54:27,327] Trial 9 finished with value: 0.3485511777144672 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.2470353461515696
Fold 2 IBS: 0.23221355449931666
Fold 3 IBS: 0.22841670741019104
Fold 4 IBS: 0.24171407848753257
Fold 5 IBS: 0.22906264846898927
[I 2024-04-13 20:54:28,117] Trial 10 finished with value: 0.2356884670035198 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.24639976969987745
Fold 2 IBS: 0.2328212998174295
Fold 3 IBS: 0.22672425069970245
Fold 4 IBS: 0.24087071384643838
Fold 5 IBS: 0.2279748608955893
[I 2024-04-13 20:54:28,678] Trial 11 finished with value: 0.23495817899180743 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.24413080243104615
Fold 2 IBS: 0.24779969645660976
Fold 3 IBS: 0.23043648738896053
Fold 4 IBS: 0.2571765664414322
Fold 5 IBS: 0.19571239045710312
[I 2024-04-13 20:54:29,963] Trial 12 finished with value: 0.23505118863503038 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.24595650697573987
Fold 2 IBS: 0.23340798693529763
Fold 3 IBS: 0.2254560651933552
Fold 4 IBS: 0.2402759194782458
Fold 5 IBS: 0.2271234075322375
[I 2024-04-13 20:54:30,635] Trial 13 finished with value: 0.23444397722297522 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.2491137823614784
Fold 2 IBS: 0.24963213433681666
Fold 3 IBS: 0.2287066169245228
Fold 4 IBS: 0.25685536326428804
Fold 5 IBS: 0.20604294163001227
[I 2024-04-13 20:54:33,098] Trial 14 finished with value: 0.23807016770342365 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.2782313985874612
Fold 2 IBS: 0.30331273692419
Fold 3 IBS: 0.2792205741927494
Fold 4 IBS: 0.29489094537314203
Fold 5 IBS: 0.22160154791207637
[I 2024-04-13 20:54:34,900] Trial 15 finished with value: 0.2754514405979238 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.2889337970599506
Fold 2 IBS: 0.3215330569598014
Fold 3 IBS: 0.25721207317626615
Fold 4 IBS: 0.307535063444838
Fold 5 IBS: 0.21069650481247676
[I 2024-04-13 20:54:41,997] Trial 16 finished with value: 0.27718209909066654 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.24417753569669493
Fold 2 IBS: 0.23864151945977902
Fold 3 IBS: 0.2193960669415668
Fold 4 IBS: 0.2373942868900049
Fold 5 IBS: 0.22198742696468415
[I 2024-04-13 20:54:43,319] Trial 17 finished with value: 0.23231936719054597 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.2546743281324155
Fold 2 IBS: 0.27884057313100086
Fold 3 IBS: 0.23627042307884064
Fold 4 IBS: 0.23899157625792516
Fold 5 IBS: 0.21624465931312048
[I 2024-04-13 20:54:52,908] Trial 18 finished with value: 0.2450043119826605 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.2462303932396379
Fold 2 IBS: 0.24894448856742532

Fold 3 IBS: 0.22471703387329683
Fold 4 IBS: 0.2514223976299201
Fold 5 IBS: 0.209166894601268
[I 2024-04-13 20:54:55,410] Trial 19 finished with value: 0.23609624158230963 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.2446002185537661
Fold 2 IBS: 0.23463757481110972
Fold 3 IBS: 0.2201655501901051
Fold 4 IBS: 0.23919942537593147
Fold 5 IBS: 0.22296335334244682
[I 2024-04-13 20:54:56,699] Trial 20 finished with value: 0.23231322445467187 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.24513654608372853
Fold 2 IBS: 0.23383949946417815
Fold 3 IBS: 0.22211599951175628
Fold 4 IBS: 0.24019573213746584
Fold 5 IBS: 0.22475950483168106
[I 2024-04-13 20:54:57,964] Trial 21 finished with value: 0.233209456405762 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.24410368410205424
Fold 2 IBS: 0.23922818428459294
Fold 3 IBS: 0.2189685113226666
Fold 4 IBS: 0.23709008023572514
Fold 5 IBS: 0.2214330028375883
[I 2024-04-13 20:54:59,228] Trial 22 finished with value: 0.23216469255652544 and parameters: {'subsample': 0.8615610863035676, 'dropout_rate': 0.7601905131808098, 'n_estimators': 57, 'learning_rate': 0.019334429052945145}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.2737584803514562
Fold 2 IBS: 0.2962265963960471
Fold 3 IBS: 0.26720566980255334
Fold 4 IBS: 0.2577874455040929
Fold 5 IBS: 0.2300268608745132
[I 2024-04-13 20:55:01,996] Trial 23 finished with value: 0.26500101058573255 and parameters: {'subsample': 0.606264195188851, 'dropout_rate': 0.7834449857046786, 'n_estimators': 150, 'learning_rate': 0.04186582141545488}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.24411524571610815
Fold 2 IBS: 0.24362878441020902
Fold 3 IBS: 0.21827769741639416
Fold 4 IBS: 0.23613720642433536
Fold 5 IBS: 0.219363390780544
[I 2024-04-13 20:55:03,072] Trial 24 finished with value: 0.23230446494951815 and parameters: {'subsample': 0.8798202199446898, 'dropout_rate': 0.9758883725345413, 'n_estimators': 56, 'learning_rate': 0.02602471758308239}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.24415748418865588
Fold 2 IBS: 0.23877610048174303
Fold 3 IBS: 0.21941301072278474
Fold 4 IBS: 0.23722624636099124
Fold 5 IBS: 0.22210573138822112
[I 2024-04-13 20:55:04,001] Trial 25 finished with value: 0.23233571462847918 and parameters: {'subsample': 0.8842379801842501, 'dropout_rate': 0.9897789595635863, 'n_estimators': 40, 'learning_rate': 0.025002990823540957}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.2575932455186338
Fold 2 IBS: 0.28166271702836304
Fold 3 IBS: 0.24167409178431157
Fold 4 IBS: 0.24010322106635126
Fold 5 IBS: 0.21773405615364316
[I 2024-04-13 20:55:05,457] Trial 26 finished with value: 0.24775346631026057 and parameters: {'subsample': 0.8177599597668942, 'dropout_rate': 0.9033888277148059, 'n_estimators': 92, 'learning_rate': 0.04553017387255954}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.26017096192566147
Fold 2 IBS: 0.29247806509111324
Fold 3 IBS: 0.24328018304319307
Fold 4 IBS: 0.24175297439873317
Fold 5 IBS: 0.22124625739762138
[I 2024-04-13 20:55:08,109] Trial 27 finished with value: 0.25178568837126447 and parameters: {'subsample': 0.924174019849744, 'dropout_rate': 0.9529267338967297, 'n_estimators': 145, 'learning_rate': 0.030307532796347948}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.24609491232601052
Fold 2 IBS: 0.23187924486144906
Fold 3 IBS: 0.22527979220132896
Fold 4 IBS: 0.24126297455427848
Fold 5 IBS: 0.2266225986426153
[I 2024-04-13 20:55:13,815] Trial 28 finished with value: 0.2342279045171365 and parameters: {'subsample': 0.19308358356170718, 'dropout_rate': 0.6465540546269559, 'n_estimators': 233, 'learning_rate': 0.0013435573889066937}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.26636834373608526
Fold 2 IBS: 0.28528787436612363
Fold 3 IBS: 0.2628250780262054
Fold 4 IBS: 0.2792422227082602
Fold 5 IBS: 0.21961165436335545
[I 2024-04-13 20:55:15,913] Trial 29 finished with value: 0.262667034640006 and parameters: {'subsample': 0.40393394585149023, 'dropout_rate': 0.7695165335542838, 'n_estimators': 108, 'learning_rate': 0.06046208382653473}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.2450740583978112
Fold 2 IBS: 0.23416217202441733
Fold 3 IBS: 0.22274506994460277
Fold 4 IBS: 0.239365506618308
Fold 5 IBS: 0.22528918181147692
[I 2024-04-13 20:55:16,782] Trial 30 finished with value: 0.23332719775932326 and parameters: {'subsample': 0.7123977768282804, 'dropout_rate': 0.9233285162661073, 'n_estimators': 29, 'learning_rate': 0.01867033902681412}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.24483755234929044
Fold 2 IBS: 0.23425580691051
Fold 3 IBS: 0.22067595774283094
Fold 4 IBS: 0.23890584606664683
Fold 5 IBS: 0.22340557179961376
[I 2024-04-13 20:55:18,117] Trial 31 finished with value: 0.23241614697377838 and parameters: {'subsample': 0.580266273279712, 'dropout_rate': 0.8341903320259118, 'n_estimators': 68, 'learning_rate': 0.011626902706171196}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.2460971281860441
Fold 2 IBS: 0.25160026933631613
Fold 3 IBS: 0.22169313222092743
Fold 4 IBS: 0.23575401804616658
Fold 5 IBS: 0.2154466540915284
[I 2024-04-13 20:55:19,535] Trial 32 finished with value: 0.2341182403761965 and parameters: {'subsample': 0.7954005053548306, 'dropout_rate': 0.7634466496920232, 'n_estimators': 81, 'learning_rate': 0.028963273611563294}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.2456535964520461
Fold 2 IBS: 0.2508944606264184
Fold 3 IBS: 0.22112867176813425
Fold 4 IBS: 0.235687695616833
Fold 5 IBS: 0.21560415999267402
[I 2024-04-13 20:55:21,614] Trial 33 finished with value: 0.23379371689122114 and parameters: {'subsample': 0.7934832943828889, 'dropout_rate': 0.8558211778724193, 'n_estimators': 121, 'learning_rate': 0.018486250017668196}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.2441138811557022
Fold 2 IBS: 0.23858139063100856
Fold 3 IBS: 0.21868944316926023
Fold 4 IBS: 0.2375730617053273
Fold 5 IBS: 0.22089087941462723
[I 2024-04-13 20:55:25,060] Trial 34 finished with value: 0.2319697312151851 and parameters: {'subsample': 0.7066975516296409, 'dropout_rate': 0.4887815215647413, 'n_estimators': 162, 'learning_rate': 0.00733291095660904}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.24406727673214432
Fold 2 IBS: 0.24308536086280563
Fold 3 IBS: 0.21831385078061338
Fold 4 IBS: 0.236293883924898
Fold 5 IBS: 0.21974284750283044
[I 2024-04-13 20:55:28,995] Trial 35 finished with value: 0.23230064396065836 and parameters: {'subsample': 0.9249221779250454, 'dropout_rate': 0.4731294957318265, 'n_estimators': 177, 'learning_rate': 0.007913246508691327}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.24413945650324773
Fold 2 IBS: 0.23817663465269598
Fold 3 IBS: 0.21887757918858072
Fold 4 IBS: 0.23787697903130572
Fold 5 IBS: 0.22121991444947345
[I 2024-04-13 20:55:32,853] Trial 36 finished with value: 0.23205811276506072 and parameters: {'subsample': 0.7083391301049273, 'dropout_rate': 0.4736730137738859, 'n_estimators': 175, 'learning_rate': 0.006453720059935313}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.24413539414880164
Fold 2 IBS: 0.2374694511870516
Fold 3 IBS: 0.21872612417814172
Fold 4 IBS: 0.23755724086220803
Fold 5 IBS: 0.22095091282411908
[I 2024-04-13 20:55:39,621] Trial 37 finished with value: 0.23176782464006443 and parameters: {'subsample': 0.70184852029998, 'dropout_rate': 0.3917773398227318, 'n_estimators': 252, 'learning_rate': 0.0046659881817414355}. Best is trial 7 with value: 0.2317185873300352.
Fold 1 IBS: 0.24412385276118398
Fold 2 IBS: 0.23932390774614795
Fold 3 IBS: 0.218294699514166

Fold 4 IBS: 0.23734359543462524
Fold 5 IBS: 0.2194438033958121
[I 2024-04-13 20:55:49,250] Trial 38 finished with value: 0.23170597177038704 and parameters: {'subsample': 0.6892895892485054, 'dropout_rate': 0.3454528205709918, 'n_estimators': 302, 'learning_rate': 0.00460239710283736}. Best is trial 38 with value: 0.23170597177038704.
Fold 1 IBS: 0.31972383764115336
Fold 2 IBS: 0.3786035551717951
Fold 3 IBS: 0.31938841247246336
Fold 4 IBS: 0.3506943227141584
Fold 5 IBS: 0.337145270635712
[I 2024-04-13 20:55:57,744] Trial 39 finished with value: 0.3411110797270564 and parameters: {'subsample': 0.5208265537491429, 'dropout_rate': 0.3158258870928942, 'n_estimators': 294, 'learning_rate': 0.07379222544900951}. Best is trial 38 with value: 0.23170597177038704.
Fold 1 IBS: 0.24434143323606985
Fold 2 IBS: 0.2415994203280167
Fold 3 IBS: 0.21847616164629763
Fold 4 IBS: 0.23711394107358877
Fold 5 IBS: 0.21776977306596226
[I 2024-04-13 20:56:09,928] Trial 40 finished with value: 0.23186014586998702 and parameters: {'subsample': 0.6714040169576785, 'dropout_rate': 0.39728110211848944, 'n_estimators': 372, 'learning_rate': 0.004607422511076958}. Best is trial 38 with value: 0.23170597177038704.
Fold 1 IBS: 0.24513041368480754
Fold 2 IBS: 0.24525242410259876
Fold 3 IBS: 0.2198784839404494
Fold 4 IBS: 0.23705659307169888
Fold 5 IBS: 0.2160284891292842
[I 2024-04-13 20:56:25,415] Trial 41 finished with value: 0.23266928078576776 and parameters: {'subsample': 0.6669422809649472, 'dropout_rate': 0.39104036057400765, 'n_estimators': 405, 'learning_rate': 0.005179364176894679}. Best is trial 38 with value: 0.23170597177038704.
Fold 1 IBS: 0.2642009009011145
Fold 2 IBS: 0.2834345863217113
Fold 3 IBS: 0.24912856264179908
Fold 4 IBS: 0.24660912022570175
Fold 5 IBS: 0.2200389242659822
[I 2024-04-13 20:56:38,300] Trial 42 finished with value: 0.25268241887126175 and parameters: {'subsample': 0.748334967317396, 'dropout_rate': 0.21904765963453648, 'n_estimators': 353, 'learning_rate': 0.014065213943513472}. Best is trial 38 with value: 0.23170597177038704.
Fold 1 IBS: 0.24438373976885924
Fold 2 IBS: 0.23492300387932946
Fold 3 IBS: 0.2195139682405863
Fold 4 IBS: 0.2386938265298039
Fold 5 IBS: 0.22207306984460906
[I 2024-04-13 20:56:52,526] Trial 43 finished with value: 0.2319175216526376 and parameters: {'subsample': 0.5547757606832024, 'dropout_rate': 0.4194373969301305, 'n_estimators': 398, 'learning_rate': 0.002425942974729615}. Best is trial 38 with value: 0.23170597177038704.
Fold 1 IBS: 0.24417366873135668
Fold 2 IBS: 0.23637590200056108
Fold 3 IBS: 0.21834500862018735
Fold 4 IBS: 0.23833874249790685
Fold 5 IBS: 0.21986741060380763
[I 2024-04-13 20:57:08,734] Trial 44 finished with value: 0.23142014649076392 and parameters: {'subsample': 0.566062639308101, 'dropout_rate': 0.3266493123672882, 'n_estimators': 425, 'learning_rate': 0.002991540253386229}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.3264598670747825
Fold 2 IBS: 0.38095071421680565
Fold 3 IBS: 0.32076885569513386
Fold 4 IBS: 0.3956960644600267
Fold 5 IBS: 0.33895739185985146
[I 2024-04-13 20:57:27,478] Trial 45 finished with value: 0.35256657866132 and parameters: {'subsample': 0.45140790222664723, 'dropout_rate': 0.3197656259561077, 'n_estimators': 457, 'learning_rate': 0.05795226464899621}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.24417083504159257
Fold 2 IBS: 0.23691260115612597
Fold 3 IBS: 0.21875926497902773
Fold 4 IBS: 0.23760504644550223
Fold 5 IBS: 0.2208698891488669
[I 2024-04-13 20:57:38,260] Trial 46 finished with value: 0.23166352735422308 and parameters: {'subsample': 0.6669528638545317, 'dropout_rate': 0.14648424644002478, 'n_estimators': 318, 'learning_rate': 0.0036472740925704294}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.32146674424576044
Fold 2 IBS: 0.37386955372799807
Fold 3 IBS: 0.31593100948299657
Fold 4 IBS: 0.35480632508652493
Fold 5 IBS: 0.3187542594584217
[I 2024-04-13 20:57:47,142] Trial 47 finished with value: 0.33696557840034036 and parameters: {'subsample': 0.5698226494608598, 'dropout_rate': 0.1240463473883398, 'n_estimators': 268, 'learning_rate': 0.08063451221472408}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.27115445553256773
Fold 2 IBS: 0.28098338188081534
Fold 3 IBS: 0.26362559232128524
Fold 4 IBS: 0.2808021289756962
Fold 5 IBS: 0.2157334720790196
[I 2024-04-13 20:57:57,589] Trial 48 finished with value: 0.2624598061578768 and parameters: {'subsample': 0.4495168889211802, 'dropout_rate': 0.19701471782839963, 'n_estimators': 323, 'learning_rate': 0.021502249107137786}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.3112038757933316
Fold 2 IBS: 0.3607772227127928
Fold 3 IBS: 0.3086732342408999
Fold 4 IBS: 0.3219462197971602
Fold 5 IBS: 0.31274398814453297
[I 2024-04-13 20:58:03,362] Trial 49 finished with value: 0.32306890813774347 and parameters: {'subsample': 0.5160375470256997, 'dropout_rate': 0.2855703765541635, 'n_estimators': 219, 'learning_rate': 0.06615495649623622}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.37068676480713936
Fold 2 IBS: 0.3748062833040722
Fold 3 IBS: 0.30638696582851915
Fold 4 IBS: 0.38758019265530486
Fold 5 IBS: 0.31608323401374067
[I 2024-04-13 20:58:20,165] Trial 50 finished with value: 0.3511086881217552 and parameters: {'subsample': 0.22472246171781585, 'dropout_rate': 0.17863180141815696, 'n_estimators': 433, 'learning_rate': 0.049118514462345504}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.24440909439422515
Fold 2 IBS: 0.24221839904250267
Fold 3 IBS: 0.21845170066856381
Fold 4 IBS: 0.23687454131571403
Fold 5 IBS: 0.2175425585669199
[I 2024-04-13 20:58:32,460] Trial 51 finished with value: 0.23189925879758513 and parameters: {'subsample': 0.663653169719907, 'dropout_rate': 0.3625096195986976, 'n_estimators': 398, 'learning_rate': 0.00441833867421715}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.25954135023731145
Fold 2 IBS: 0.26741506417435207
Fold 3 IBS: 0.24414289532664385
Fold 4 IBS: 0.24868585329548606
Fold 5 IBS: 0.2119052369289483
[I 2024-04-13 20:58:41,898] Trial 52 finished with value: 0.24633807999254836 and parameters: {'subsample': 0.6077158063581721, 'dropout_rate': 0.24676995880768837, 'n_estimators': 309, 'learning_rate': 0.015116795567933931}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.2537445944665345
Fold 2 IBS: 0.2685001273604072
Fold 3 IBS: 0.2342698124067437
Fold 4 IBS: 0.2390866221321241
Fold 5 IBS: 0.21369110894865098
[I 2024-04-13 20:58:52,996] Trial 53 finished with value: 0.24185845306289208 and parameters: {'subsample': 0.7646579678808466, 'dropout_rate': 0.34276296706017745, 'n_estimators': 370, 'learning_rate': 0.009903965993594312}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.24562954581119825
Fold 2 IBS: 0.2331370532831523
Fold 3 IBS: 0.22426272879297043
Fold 4 IBS: 0.24011249175544747
Fold 5 IBS: 0.2263896810793541
[I 2024-04-13 20:58:58,869] Trial 54 finished with value: 0.2339063001444245 and parameters: {'subsample': 0.68151974186745, 'dropout_rate': 0.42873451616248404, 'n_estimators': 254, 'learning_rate': 0.001547029587242473}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.24597929556670078
Fold 2 IBS: 0.2506603732478268
Fold 3 IBS: 0.22269634303284558
Fold 4 IBS: 0.23780713951418947
Fold 5 IBS: 0.2143299077147709
[I 2024-04-13 20:59:15,385] Trial 55 finished with value: 0.23429461181526673 and parameters: {'subsample': 0.6482273932744342, 'dropout_rate': 0.515910641067652, 'n_estimators': 493, 'learning_rate': 0.0049664861275623105}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.2539820179931347
Fold 2 IBS: 0.25795621362970206
Fold 3 IBS: 0.23664293437468534
Fold 4 IBS: 0.2486072485505156
Fold 5 IBS: 0.20960985461749831
[I 2024-04-13 20:59:27,646] Trial 56 finished with value: 0.24135965383310717 and parameters: {'subsample': 0.6000256177016021, 'dropout_rate': 0.11422813914236489, 'n_estimators': 376, 'learning_rate': 0.010730706346064009}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.2968454016609984
Fold 2 IBS: 0.34047502278569625
Fold 3 IBS: 0.29309284059405316

Fold 4 IBS: 0.3243986654312856
Fold 5 IBS: 0.26528172110872605
[I 2024-04-13 20:59:39,003] Trial 57 finished with value: 0.30401873031615184 and parameters: {'subsample': 0.2888110376335854, 'dropout_rate': 0.2718615358996285, 'n_estimators': 342, 'learning_rate': 0.03512375325073246}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.25755648343454
Fold 2 IBS: 0.2764498175883411
Fold 3 IBS: 0.24200617130873298
Fold 4 IBS: 0.2432893725992331
Fold 5 IBS: 0.21437684756519773
[I 2024-04-13 20:59:45,703] Trial 58 finished with value: 0.24673573849920896 and parameters: {'subsample': 0.6878065235587841, 'dropout_rate': 0.5792181458125746, 'n_estimators': 278, 'learning_rate': 0.01539553219464254}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.2450244777809273
Fold 2 IBS: 0.2459114617756686
Fold 3 IBS: 0.2196599956493579
Fold 4 IBS: 0.23673683057657782
Fold 5 IBS: 0.21651218141381678
[I 2024-04-13 20:59:51,199] Trial 59 finished with value: 0.2327689894392697 and parameters: {'subsample': 0.7307561292425406, 'dropout_rate': 0.40841266195335413, 'n_estimators': 239, 'learning_rate': 0.008520841858596882}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.24437713042507375
Fold 2 IBS: 0.241377409475432
Fold 3 IBS: 0.21856052712503812
Fold 4 IBS: 0.23662712156959342
Fold 5 IBS: 0.21725108451237315
[I 2024-04-13 21:00:05,453] Trial 60 finished with value: 0.23163865462150207 and parameters: {'subsample': 0.6316682286978249, 'dropout_rate': 0.37011290453439477, 'n_estimators': 431, 'learning_rate': 0.0041422453796255984}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.24494526715429507
Fold 2 IBS: 0.24385921867832552
Fold 3 IBS: 0.2196255821232836
Fold 4 IBS: 0.23666011927502267
Fold 5 IBS: 0.2159453845206328
[I 2024-04-13 21:00:19,355] Trial 61 finished with value: 0.23220711435031188 and parameters: {'subsample': 0.629028391178203, 'dropout_rate': 0.3602824255485478, 'n_estimators': 428, 'learning_rate': 0.004824534227251483}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.2704397545560472
Fold 2 IBS: 0.2840313769008704
Fold 3 IBS: 0.26293667780704655
Fold 4 IBS: 0.2651633951082924
Fold 5 IBS: 0.22257464236896563
[I 2024-04-13 21:00:36,672] Trial 62 finished with value: 0.2610291693482444 and parameters: {'subsample': 0.5388322001772096, 'dropout_rate': 0.294107597620086, 'n_estimators': 472, 'learning_rate': 0.013219093135397302}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.2457998142329553
Fold 2 IBS: 0.23332666389210374
Fold 3 IBS: 0.22493996099890987
Fold 4 IBS: 0.24016896546706976
Fold 5 IBS: 0.22688634075705205
[I 2024-04-13 21:00:45,517] Trial 63 finished with value: 0.23422434906961814 and parameters: {'subsample': 0.773587746796309, 'dropout_rate': 0.38170064841135914, 'n_estimators': 316, 'learning_rate': 0.0010473873299368958}. Best is trial 44 with value: 0.23142014649076392.
Fold 1 IBS: 0.24423427382222346
Fold 2 IBS: 0.23762025478371807
Fold 3 IBS: 0.21798750638642247
Fold 4 IBS: 0.23862695773468634
Fold 5 IBS: 0.21749019083793078
[I 2024-04-13 21:00:50,125] Trial 64 finished with value: 0.23119183671299623 and parameters: {'subsample': 0.48283267877461866, 'dropout_rate': 0.44250649532836367, 'n_estimators': 203, 'learning_rate': 0.007884714851766478}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.25706470179525026
Fold 2 IBS: 0.26170706318504056
Fold 3 IBS: 0.245426095536522
Fold 4 IBS: 0.27322857160375624
Fold 5 IBS: 0.2091011902736197
[I 2024-04-13 21:00:57,543] Trial 65 finished with value: 0.24930552447883775 and parameters: {'subsample': 0.3824609837651736, 'dropout_rate': 0.443051555375674, 'n_estimators': 293, 'learning_rate': 0.017218771535665593}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.2925093425881729
Fold 2 IBS: 0.32136030780330227
Fold 3 IBS: 0.2906309074787728
Fold 4 IBS: 0.3022083479817112
Fold 5 IBS: 0.2676004201780122
[I 2024-04-13 21:01:12,544] Trial 66 finished with value: 0.2948618652059943 and parameters: {'subsample': 0.4818292228070035, 'dropout_rate': 0.3265000872892265, 'n_estimators': 442, 'learning_rate': 0.021904291906889722}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.24397615881233045
Fold 2 IBS: 0.23893716311811983
Fold 3 IBS: 0.21790688207789483
Fold 4 IBS: 0.24390942364486476
Fold 5 IBS: 0.21418805379486405
[I 2024-04-13 21:01:16,902] Trial 67 finished with value: 0.2317835362896148 and parameters: {'subsample': 0.3589803612378964, 'dropout_rate': 0.6629226014101706, 'n_estimators': 210, 'learning_rate': 0.009604740212457396}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.27320130194263414
Fold 2 IBS: 0.2898716877952331
Fold 3 IBS: 0.2655803783925842
Fold 4 IBS: 0.2637026594461311
Fold 5 IBS: 0.22502334652911332
[I 2024-04-13 21:01:22,924] Trial 68 finished with value: 0.26347587482113916 and parameters: {'subsample': 0.5787726018471617, 'dropout_rate': 0.24389866317999087, 'n_estimators': 248, 'learning_rate': 0.0267624773650322}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.2459518327841126
Fold 2 IBS: 0.24436445575112709
Fold 3 IBS: 0.22216995304827147
Fold 4 IBS: 0.24369036601301028
Fold 5 IBS: 0.21216413377652585
[I 2024-04-13 21:01:27,069] Trial 69 finished with value: 0.23366814827460947 and parameters: {'subsample': 0.4349200361164294, 'dropout_rate': 0.5119390991234922, 'n_estimators': 205, 'learning_rate': 0.012755874118266418}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.24428942703108522
Fold 2 IBS: 0.2361395337424877
Fold 3 IBS: 0.2180606659222905
Fold 4 IBS: 0.241657429819406
Fold 5 IBS: 0.2166132892153272
[I 2024-04-13 21:01:32,699] Trial 70 finished with value: 0.23135206914611928 and parameters: {'subsample': 0.4896313202964777, 'dropout_rate': 0.14893361705763483, 'n_estimators': 227, 'learning_rate': 0.007655763654415794}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.24420519991801312
Fold 2 IBS: 0.23539756359020123
Fold 3 IBS: 0.2179413957203132
Fold 4 IBS: 0.2412124250983431
Fold 5 IBS: 0.21763989442174828
[I 2024-04-13 21:01:38,603] Trial 71 finished with value: 0.23127929574972378 and parameters: {'subsample': 0.4909229585214684, 'dropout_rate': 0.151117463899618, 'n_estimators': 229, 'learning_rate': 0.006859438762074238}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.2442796102324068
Fold 2 IBS: 0.23475177390817473
Fold 3 IBS: 0.2178318550080009
Fold 4 IBS: 0.2407282092987512
Fold 5 IBS: 0.2184855719900585
[I 2024-04-13 21:01:43,395] Trial 72 finished with value: 0.23121540408747845 and parameters: {'subsample': 0.4795372348594677, 'dropout_rate': 0.15938013093444328, 'n_estimators': 187, 'learning_rate': 0.007562864195062744}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.244273490178865
Fold 2 IBS: 0.2355486281632424
Fold 3 IBS: 0.21809856696794042
Fold 4 IBS: 0.24142630560532388
Fold 5 IBS: 0.21732565383114272
[I 2024-04-13 21:01:47,529] Trial 73 finished with value: 0.23133452894930287 and parameters: {'subsample': 0.4976280413949545, 'dropout_rate': 0.14671223023858476, 'n_estimators': 189, 'learning_rate': 0.008721393778220189}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.24429435089608179
Fold 2 IBS: 0.23609729132850021
Fold 3 IBS: 0.21805347090362004
Fold 4 IBS: 0.24175434445990457
Fold 5 IBS: 0.2167541192989602
[I 2024-04-13 21:01:52,831] Trial 74 finished with value: 0.23139071537741335 and parameters: {'subsample': 0.4912063851653933, 'dropout_rate': 0.14574454082055702, 'n_estimators': 223, 'learning_rate': 0.007824563491234577}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.2441933206100482
Fold 2 IBS: 0.23472843227649495
Fold 3 IBS: 0.2179324086955869
Fold 4 IBS: 0.24120682758183012
Fold 5 IBS: 0.21863827013966441
[I 2024-04-13 21:01:56,825] Trial 75 finished with value: 0.2313398518607249 and parameters: {'subsample': 0.4943444617937632, 'dropout_rate': 0.15624253605319807, 'n_estimators': 189, 'learning_rate': 0.007399034202440575}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.24422153332462285
Fold 2 IBS: 0.23506720968984623
Fold 3 IBS: 0.2180112185728526

Fold 4 IBS: 0.24101925396002535
Fold 5 IBS: 0.2179470573597778
[I 2024-04-13 21:02:01,253] Trial 76 finished with value: 0.23125325458142493 and parameters: {'subsample': 0.4955197477745412, 'dropout_rate': 0.16046855961245599, 'n_estimators': 195, 'learning_rate': 0.007706860559248215}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.24421634647346885
Fold 2 IBS: 0.23548728538557162
Fold 3 IBS: 0.21781247557561054
Fold 4 IBS: 0.2416619653489052
Fold 5 IBS: 0.21716988899584236
[I 2024-04-13 21:02:05,374] Trial 77 finished with value: 0.2312695923558797 and parameters: {'subsample': 0.4935643600806539, 'dropout_rate': 0.15685680514657221, 'n_estimators': 189, 'learning_rate': 0.008564077446745044}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.25044273628462804
Fold 2 IBS: 0.24911955068637429
Fold 3 IBS: 0.23186848614200992
Fold 4 IBS: 0.2564736956596988
Fold 5 IBS: 0.2063404965895953
[I 2024-04-13 21:02:09,557] Trial 78 finished with value: 0.23884899307246127 and parameters: {'subsample': 0.4172953003640497, 'dropout_rate': 0.18618406733756698, 'n_estimators': 190, 'learning_rate': 0.020620879155439833}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.24553976487048504
Fold 2 IBS: 0.24121648644140462
Fold 3 IBS: 0.22098090046947144
Fold 4 IBS: 0.24533053225609436
Fold 5 IBS: 0.21160979523850756
[I 2024-04-13 21:02:12,827] Trial 79 finished with value: 0.23293549585519263 and parameters: {'subsample': 0.4609474125668925, 'dropout_rate': 0.16814423385312532, 'n_estimators': 159, 'learning_rate': 0.016530945135386325}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.24484080746706824
Fold 2 IBS: 0.24173385823799196
Fold 3 IBS: 0.2203929891914199
Fold 4 IBS: 0.23893371715003275
Fold 5 IBS: 0.21341059481564165
[I 2024-04-13 21:02:17,102] Trial 80 finished with value: 0.23186239337243092 and parameters: {'subsample': 0.5105154770232885, 'dropout_rate': 0.2125863288479009, 'n_estimators': 198, 'learning_rate': 0.011736941228092141}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.24434308545816005
Fold 2 IBS: 0.23610606379048935
Fold 3 IBS: 0.21814450471428365
Fold 4 IBS: 0.24202181936598005
Fold 5 IBS: 0.21621281970724993
[I 2024-04-13 21:02:22,786] Trial 81 finished with value: 0.23136565860723263 and parameters: {'subsample': 0.48746940611488326, 'dropout_rate': 0.14000221203442242, 'n_estimators': 220, 'learning_rate': 0.008211114649864822}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.24411253938007324
Fold 2 IBS: 0.23550988134376377
Fold 3 IBS: 0.21788415553786733
Fold 4 IBS: 0.24011322225904327
Fold 5 IBS: 0.21875986888306023
[I 2024-04-13 21:02:27,758] Trial 82 finished with value: 0.23127593348076156 and parameters: {'subsample': 0.4726604451216062, 'dropout_rate': 0.10331730455584968, 'n_estimators': 189, 'learning_rate': 0.007373668361098687}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.24498766058876248
Fold 2 IBS: 0.24085838925492184
Fold 3 IBS: 0.2203963201479998
Fold 4 IBS: 0.2436737314743377
Fold 5 IBS: 0.2114277085418079
[I 2024-04-13 21:02:32,448] Trial 83 finished with value: 0.23226876200156593 and parameters: {'subsample': 0.42464250426664607, 'dropout_rate': 0.10340909770488527, 'n_estimators': 190, 'learning_rate': 0.013788256133141358}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.24424931100547967
Fold 2 IBS: 0.23607462987701716
Fold 3 IBS: 0.21768761764248523
Fold 4 IBS: 0.2395291073327117
Fold 5 IBS: 0.2185378402073585
[I 2024-04-13 21:02:35,432] Trial 84 finished with value: 0.23121570121301044 and parameters: {'subsample': 0.4734457831716731, 'dropout_rate': 0.22073744116378985, 'n_estimators': 137, 'learning_rate': 0.010631172195415237}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.24410312264265036
Fold 2 IBS: 0.23691392153219595
Fold 3 IBS: 0.2176588851835022
Fold 4 IBS: 0.23989970608879743
Fold 5 IBS: 0.21799560615709518
[I 2024-04-13 21:02:38,724] Trial 85 finished with value: 0.2313142483208482 and parameters: {'subsample': 0.46368083283470596, 'dropout_rate': 0.22234882353892188, 'n_estimators': 143, 'learning_rate': 0.010763755661323737}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.24485469513421446
Fold 2 IBS: 0.23814364954376707
Fold 3 IBS: 0.21835189583358317
Fold 4 IBS: 0.244612458762608
Fold 5 IBS: 0.21239882101737284
[I 2024-04-13 21:02:41,834] Trial 86 finished with value: 0.23167230405830913 and parameters: {'subsample': 0.4020455085596438, 'dropout_rate': 0.2227478295041273, 'n_estimators': 127, 'learning_rate': 0.018479743918336823}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.24490969209335725
Fold 2 IBS: 0.24082453581202792
Fold 3 IBS: 0.21888795564523403
Fold 4 IBS: 0.24147458414101805
Fold 5 IBS: 0.2135757155661808
[I 2024-04-13 21:02:44,920] Trial 87 finished with value: 0.2319344966515636 and parameters: {'subsample': 0.4669734103954893, 'dropout_rate': 0.12490567487939014, 'n_estimators': 143, 'learning_rate': 0.015518795983427154}. Best is trial 64 with value: 0.23119183671299623.
Fold 1 IBS: 0.24451051611863547
Fold 2 IBS: 0.2372761865773429
Fold 3 IBS: 0.21904450502449183
Fold 4 IBS: 0.23953737450201523
Fold 5 IBS: 0.2153856112835502
[I 2024-04-13 21:02:48,819] Trial 88 finished with value: 0.23115083870120712 and parameters: {'subsample': 0.5458000956144432, 'dropout_rate': 0.19387462740292366, 'n_estimators': 167, 'learning_rate': 0.011891550799981571}. Best is trial 88 with value: 0.23115083870120712.
Fold 1 IBS: 0.24442802215681897
Fold 2 IBS: 0.23708332811751004
Fold 3 IBS: 0.2189832324095505
Fold 4 IBS: 0.23938796210432653
Fold 5 IBS: 0.2158129982978235
[I 2024-04-13 21:02:53,066] Trial 89 finished with value: 0.23113910861720594 and parameters: {'subsample': 0.5436365564904176, 'dropout_rate': 0.20216010599453635, 'n_estimators': 169, 'learning_rate': 0.011235250666413975}. Best is trial 89 with value: 0.23113910861720594.
Fold 1 IBS: 0.252260851777795
Fold 2 IBS: 0.2543359280865786
Fold 3 IBS: 0.23744799362135607
Fold 4 IBS: 0.2450035481735711
Fold 5 IBS: 0.20822648881992442
[I 2024-04-13 21:02:57,852] Trial 90 finished with value: 0.239454962095845 and parameters: {'subsample': 0.5415280561108443, 'dropout_rate': 0.20607926568272922, 'n_estimators': 171, 'learning_rate': 0.024153037805690343}. Best is trial 89 with value: 0.23113910861720594.
Fold 1 IBS: 0.2439283805219454
Fold 2 IBS: 0.23744821400632818
Fold 3 IBS: 0.21786658810495654
Fold 4 IBS: 0.237683948056563
Fold 5 IBS: 0.21777556274630386
[I 2024-04-13 21:03:01,101] Trial 91 finished with value: 0.23094053868721942 and parameters: {'subsample': 0.5279987131107713, 'dropout_rate': 0.2314439741310604, 'n_estimators': 139, 'learning_rate': 0.011421014743335248}. Best is trial 91 with value: 0.23094053868721942.
Fold 1 IBS: 0.24445366726646764
Fold 2 IBS: 0.23737105368455597
Fold 3 IBS: 0.21836583186033523
Fold 4 IBS: 0.23992597364785573
Fold 5 IBS: 0.21547596846533293
[I 2024-04-13 21:03:04,838] Trial 92 finished with value: 0.2311184989849095 and parameters: {'subsample': 0.5274263805257551, 'dropout_rate': 0.16743107937007512, 'n_estimators': 161, 'learning_rate': 0.012071618382620504}. Best is trial 91 with value: 0.23094053868721942.
Fold 1 IBS: 0.24434805736643003
Fold 2 IBS: 0.23851539136957703
Fold 3 IBS: 0.21884180509580398
Fold 4 IBS: 0.23809593617846506
Fold 5 IBS: 0.21566343114467376
[I 2024-04-13 21:03:08,948] Trial 93 finished with value: 0.23109292423098995 and parameters: {'subsample': 0.5315832550496271, 'dropout_rate': 0.24363534422106686, 'n_estimators': 164, 'learning_rate': 0.011899376585522547}. Best is trial 91 with value: 0.23094053868721942.
Fold 1 IBS: 0.24406636964444411
Fold 2 IBS: 0.23840686301780176
Fold 3 IBS: 0.21824261713525678
Fold 4 IBS: 0.23849653113936017
Fold 5 IBS: 0.21632252874631824
[I 2024-04-13 21:03:12,620] Trial 94 finished with value: 0.2311069819366362 and parameters: {'subsample': 0.5183547258828601, 'dropout_rate': 0.2422877654043397, 'n_estimators': 156, 'learning_rate': 0.011804152559042807}. Best is trial 91 with value: 0.23094053868721942.
Fold 1 IBS: 0.24473782578181777
Fold 2 IBS: 0.23987663986708854

Fold 3 IBS: 0.21965424337510803
Fold 4 IBS: 0.238100479483417
Fold 5 IBS: 0.21419247900632338
[I 2024-04-13 21:03:15,161] Trial 95 finished with value: 0.23131233350275093 and parameters: {'subsample': 0.5287900994881528, 'dropout_rate': 0.24362538801389683, 'n_estimators': 114, 'learning_rate': 0.01918720977286184}. Best is trial 91 with value: 0.23094053868721942.
Fold 1 IBS: 0.24450793825144282
Fold 2 IBS: 0.23721942064100832
Fold 3 IBS: 0.2191361464016592
Fold 4 IBS: 0.23967108610942914
Fold 5 IBS: 0.21529353238617982
[I 2024-04-13 21:03:18,834] Trial 96 finished with value: 0.23116562475794383 and parameters: {'subsample': 0.5479763862885562, 'dropout_rate': 0.18732015009820935, 'n_estimators': 159, 'learning_rate': 0.012590794461904201}. Best is trial 91 with value: 0.23094053868721942.
Fold 1 IBS: 0.24460738141356492
Fold 2 IBS: 0.24083856752760174
Fold 3 IBS: 0.21870952652926662
Fold 4 IBS: 0.23884101095979912
Fold 5 IBS: 0.21590250993624882
[I 2024-04-13 21:03:22,805] Trial 97 finished with value: 0.23177979927329626 and parameters: {'subsample': 0.5537172223377405, 'dropout_rate': 0.25992393093302857, 'n_estimators': 160, 'learning_rate': 0.012112711402346307}. Best is trial 91 with value: 0.23094053868721942.
Fold 1 IBS: 0.24457341671407248
Fold 2 IBS: 0.23959640574816327
Fold 3 IBS: 0.2189250827843703
Fold 4 IBS: 0.23908539212481372
Fold 5 IBS: 0.21608986087996745
[I 2024-04-13 21:03:25,807] Trial 98 finished with value: 0.23165403165027745 and parameters: {'subsample': 0.5872814317390533, 'dropout_rate': 0.18543900239621744, 'n_estimators': 135, 'learning_rate': 0.014025152576528326}. Best is trial 91 with value: 0.23094053868721942.
Fold 1 IBS: 0.24618557190242069
Fold 2 IBS: 0.24692332540550258
Fold 3 IBS: 0.2232133279183081
Fold 4 IBS: 0.24141202572906104
Fold 5 IBS: 0.2123417319888404
[I 2024-04-13 21:03:29,079] Trial 99 finished with value: 0.23401519658882655 and parameters: {'subsample': 0.5181073555886543, 'dropout_rate': 0.29039284951821065, 'n_estimators': 153, 'learning_rate': 0.017404195756051073}. Best is trial 91 with value: 0.23094053868721942.


* Best trial for IBS:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.23094053868721942], datetime_start=datetime.datetime(2024, 4, 13, 21, 2, 57, 859399), datetime_complete=datetime.datetime(2024, 4, 13, 21, 3, 1, 100127), params={'subsample': 0.5279987131107713, 'dropout_rate': 0.2314439741310604, 'n_estimators': 139, 'learning_rate': 0.011421014743335248}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=91, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.5279987131107713, 'dropout_rate': 0.2314439741310604, 'n_estimators': 139, 'learning_rate': 0.011421014743335248}


* Best Score for IBS:
 0.23094053868721942

In [83]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [84]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.627
train_ibs:  0.231

#### Test

In [85]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [86]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.10355008884313799,
                                              learning_rate=0.09604343153434695,
                                              n_estimators=308,
                                              random_state=123,
                                              subsample=0.10803471257567032)

C-index score: 0.567

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.2314439741310604,
                                              learning_rate=0.011421014743335248,
                                              n_estimators=139,
                                              random_state=123,
                                              subsample=0.5279987131107713)

IBS: 0.243

In [87]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

# Results

In [88]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.790   1.0
ExtraSurvivalTrees               0.748   2.0
GradientBoosting                 0.648   3.0
CoxPH                            0.638   4.5
CoxElastic                       0.638   4.5
CoxLasso                         0.637   6.0
ComponentwiseGradientBoosting    0.627   7.0
CoxRidge                         0.583   8.0

In [89]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.218   1.5
ExtraSurvivalTrees             0.218   1.5
CoxElastic                     0.227   3.0
GradientBoosting               0.229   4.0
CoxPH                          0.231   6.0
CoxLasso                       0.231   6.0
ComponentwiseGradientBoosting  0.231   6.0
CoxRidge                       0.236   8.0

In [90]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
GradientBoosting                 0.639   1.0
Randomsurvivalforest             0.603   2.0
ExtraSurvivalTrees               0.585   3.0
CoxRidge                         0.571   4.0
ComponentwiseGradientBoosting    0.567   5.0
CoxPH                            0.532   7.0
CoxLasso                         0.532   7.0
CoxElastic                       0.532   7.0

In [91]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.213   1.0
Randomsurvivalforest           0.215   2.0
GradientBoosting               0.221   3.0
CoxRidge                       0.229   4.0
ComponentwiseGradientBoosting  0.243   5.0
CoxLasso                       0.273   6.5
CoxElastic                     0.273   6.5
CoxPH                          0.276   8.0

In [92]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/dfs/robust/rent/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_dfs_robust_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [93]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-13