In [1]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import RobustScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

In [6]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

### COX assumption in Train data

In [7]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                test_statistic    p  -log2(p)
MTV                       0.00 0.95      0.08
SUVpeak                   0.29 0.59      0.76
TLG                       0.22 0.64      0.65
age                       1.60 0.21      2.28
cavum_oris                0.00 1.00      0.01
charlson                  0.07 0.79      0.34
female                    0.17 0.68      0.56
histgrade_high            1.26 0.26      1.93
hpv_related               4.31 0.04      4.72
hypopharynx               0.00 0.99      0.01
larynx                    0.00 0.98      0.02
oropharynx                0.00 0.99      0.02
pack_years                0.71 0.40      1.32
uicc8_III-IV              0.45 0.50      0.99

In [8]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['hpv_related'], dtype='object')

In [9]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                test_statistic    p  -log2(p)
MTV                       0.02 0.88      0.18
SUVpeak                   0.56 0.46      1.13
TLG                       0.06 0.81      0.30
age                       1.58 0.21      2.26
cavum_oris                0.08 0.77      0.37
charlson                  0.03 0.86      0.22
female                    0.35 0.56      0.85
histgrade_high            0.95 0.33      1.60
hpv_related               3.02 0.08      3.60
hypopharynx               0.10 0.75      0.41
larynx                    1.46 0.23      2.14
oropharynx                0.96 0.33      1.61
pack_years                0.39 0.53      0.92
uicc8_III-IV              0.08 0.78      0.36

In [10]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index([], dtype='object')

###### penalizer values essentially result in same result

## Test dataset: MAASTRO

In [11]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [12]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [13]:
# need to choose patient_id from MAASTRO_D1 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [14]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG,DFS,DFS_event
0,1,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342,8.83,1.0
3,4,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979,19.73,1.0
4,6,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782,13.27,1.0
95,111,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212,72.07,0.0

In [15]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [16]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, DFS, DFS_event]
Index: []

In [17]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [18]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [19]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 14)
y_train:  (139,)

In [20]:
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [21]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 16)

In [22]:
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X.values, i) 
                          for i in range(len(X.columns))] 

vif_data

           feature        VIF
0              age   1.136852
1           female   1.197250
2       cavum_oris   7.993011
3       oropharynx  60.199385
4      hypopharynx  11.118710
5           larynx  14.183474
6   histgrade_high   1.150479
7      hpv_related   4.309385
8         charlson   1.302350
9       pack_years   1.647441
10    uicc8_III-IV   2.026695
11         SUVpeak   2.157147
12             MTV   5.247552
13             TLG   6.368452

# Standardization

In [23]:
original_X = X.copy()

In [24]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

## Standardize the data but not the categorical columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']
### Separate the categorical and non-categorical columns
X_categorical = X[categorical_columns]
X_numeric = X.drop(categorical_columns, axis=1)
X_numeric_columns = X_numeric.columns
X_numeric_index = X_numeric.index

### Standardize non-categorical and then concat with the categorical
scaler = RobustScaler()  
X_numeric_std = scaler.fit_transform(X_numeric)
X_numeric_std = pd.DataFrame(X_numeric_std, columns=X_numeric_columns, index=X_numeric_index)
X_std = pd.concat([X_categorical, X_numeric_std], axis=1)

## Sort the order of the columns as it was in the clinical train 
X_std = X_std[original_X.columns]

In [25]:
# Standardize X_MAASTRO 
MAASTRO_new = X_MAASTRO.copy()
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [26]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = MAASTRO_new_std

In [27]:
X_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,54.238356,1,0,1,0,0,1,0.0,0,0.000000,0.0,14.473272,7.934,86.228420
1,54.539726,0,0,0,0,1,0,0.0,1,27.404795,0.0,5.044678,1.656,7.040100
2,59.019178,0,1,0,0,0,1,0.0,1,41.019178,1.0,7.839043,14.502,83.569669
3,70.726027,0,0,0,0,1,0,0.0,1,37.500000,0.0,2.880631,2.440,5.567091
4,67.865753,0,0,0,0,1,0,0.0,1,53.000000,0.0,5.402006,3.668,16.150550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,60.435616,0,0,1,0,0,1,1.0,0,0.000000,0.0,9.290139,3.650,26.280140
135,68.794521,0,0,1,0,0,1,1.0,0,0.000000,1.0,7.172883,18.967,101.754834
136,57.498630,0,0,1,0,0,1,1.0,1,39.498630,0.0,13.873187,6.370,66.273201
137,65.684932,0,0,1,0,0,1,1.0,1,71.527397,1.0,7.507419,12.443,71.832443
138,61.676712,0,0,1,0,0,1,1.0,0,2.250000,1.0,13.053465,7.983,78.647696

In [28]:
X_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,-0.497635,1,0,1,0,0,1,0.0,0,-0.747766,0.0,0.600320,0.075008,0.231096
1,-0.473435,0,0,0,0,1,0,0.0,1,0.159774,0.0,-0.690705,-0.466877,-0.387041
2,-0.113739,0,1,0,0,0,1,0.0,1,0.610629,1.0,-0.308082,0.641923,0.210342
3,0.826312,0,0,0,0,1,0,0.0,1,0.494088,0.0,-0.987020,-0.399206,-0.398539
4,0.596634,0,0,0,0,1,0,0.0,1,1.007387,0.0,-0.641777,-0.293211,-0.315926
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,0.000000,0,0,1,0,0,1,1.0,0,-0.747766,0.0,-0.109388,-0.294765,-0.236855
135,0.671213,0,0,1,0,0,1,1.0,0,-0.747766,1.0,-0.399297,1.027319,0.352293
136,-0.235838,0,0,1,0,0,1,1.0,1,0.560275,0.0,0.518153,-0.059989,0.075327
137,0.421516,0,0,1,0,0,1,1.0,1,1.620942,1.0,-0.353490,0.464201,0.118722
138,0.099659,0,0,1,0,0,1,1.0,0,-0.673255,1.0,0.405911,0.079237,0.171921

In [29]:
MAASTRO_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623
1,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700
2,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342
3,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979
4,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782
95,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868
96,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274
97,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492
98,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212

In [30]:
MAASTRO_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,-0.436476,0,0,1,0,0,1,1,1,-0.747766,0,0.732497,1.361702,1.615732
1,-0.436476,0,0,1,0,0,0,0,0,-0.085444,1,-0.172482,-0.121272,-0.153327
2,-0.436476,0,0,1,0,0,0,0,1,-0.549070,1,0.463784,0.062665,0.140609
3,0.045320,1,0,0,0,1,1,0,1,0.742458,1,-0.199405,0.072763,-0.076742
4,0.768012,0,0,1,0,0,1,1,1,1.206084,0,-0.041772,0.705364,0.398213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0.446816,1,0,0,0,1,0,0,0,1.073619,1,2.909606,-0.082431,0.685886
95,0.205918,0,0,0,0,1,0,0,1,5.014436,1,0.404287,0.010099,0.098289
96,0.205918,0,0,1,0,0,1,1,1,-0.747766,1,-0.156713,0.812913,0.358846
97,-0.516775,0,0,1,0,0,1,1,0,-0.747766,0,0.560744,0.251694,0.363804
98,0.125619,0,0,0,1,0,1,0,0,0.576878,1,0.044615,-0.308144,-0.219112

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [31]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:01:31,223] A new study created in memory with name: no-name-4103015e-6f02-4a8e-a73a-f3af14f64981

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-13 17:01:31,375] A new study created in memory with name: no-name-3c8de404-5593-488e-8e3b-75c581a6123b

Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:01:31,372] Trial 0 finished with value: 0.6371137109369622 and parameters: {}. Best is trial 0 with value: 0.6371137109369622.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6371137109369622], datetime_start=datetime.datetime(2024, 4, 13, 17, 1, 31, 267340), datetime_complete=datetime.datetime(2024, 4, 13, 17, 1, 31, 372661), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6371137109369622

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.25671409350000224
Fold 2 IBS: 0.6067543088664037
Fold 3 IBS: 0.168829941254425
Fold 4 IBS: 0.295979507187782
Fold 5 IBS: 0.21043512284090146
[I 2024-04-13 17:01:31,495] Trial 0 finished with value: 0.30774259472990284 and parameters: {}. Best is trial 0 with value: 0.30774259472990284.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.30774259472990284], datetime_start=datetime.datetime(2024, 4, 13, 17, 1, 31, 386859), datetime_complete=datetime.datetime(2024, 4, 13, 17, 1, 31, 495863), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.30774259472990284

In [32]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [33]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.637
train_ibs:  0.308

#### Test

In [34]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [35]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.563
IBS score: 0.291

In [36]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [37]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [38]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:01:31,572] A new study created in memory with name: no-name-357fc2b2-f859-47d5-8d67-2f0b750fe619

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325

[I 2024-04-13 17:01:31,647] A new study created in memory with name: no-name-0d07a9a0-b6ca-4391-87e4-12d4b19f3d10

Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.4695817490494297
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:01:31,645] Trial 0 finished with value: 0.5657838405704052 and parameters: {}. Best is trial 0 with value: 0.5657838405704052.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5657838405704052], datetime_start=datetime.datetime(2024, 4, 13, 17, 1, 31, 587592), datetime_complete=datetime.datetime(2024, 4, 13, 17, 1, 31, 645205), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5657838405704052

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709360937505
Fold 2 IBS: 0.23203988427112568
Fold 3 IBS: 0.228981863568446
Fold 4 IBS: 0.24197478945971077
Fold 5 IBS: 0.2293955857787768
[I 2024-04-13 17:01:31,729] Trial 0 finished with value: 0.23592784333748687 and parameters: {}. Best is trial 0 with value: 0.23592784333748687.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592784333748687], datetime_start=datetime.datetime(2024, 4, 13, 17, 1, 31, 663132), datetime_complete=datetime.datetime(2024, 4, 13, 17, 1, 31, 729136), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592784333748687

In [39]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [40]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.566
train_ibs:  0.236

#### Test

In [41]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [42]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.584

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [43]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [44]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:01:31,853] A new study created in memory with name: no-name-a639e3e2-43c9-4ef6-a67e-26c1016899e4

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901

[I 2024-04-13 17:01:32,013] A new study created in memory with name: no-name-84ff22df-cee7-4181-8b91-0872ada49cf5

Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:01:32,011] Trial 0 finished with value: 0.6347812481157444 and parameters: {}. Best is trial 0 with value: 0.6347812481157444.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6347812481157444], datetime_start=datetime.datetime(2024, 4, 13, 17, 1, 31, 873570), datetime_complete=datetime.datetime(2024, 4, 13, 17, 1, 32, 11507), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6347812481157444

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.261310757127916
Fold 2 IBS: 0.2631821342546185
Fold 3 IBS: 0.17043677379023145
Fold 4 IBS: 0.29558039313374845
Fold 5 IBS: 0.2102637591042142
[I 2024-04-13 17:01:32,184] Trial 0 finished with value: 0.24015476348214576 and parameters: {}. Best is trial 0 with value: 0.24015476348214576.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.24015476348214576], datetime_start=datetime.datetime(2024, 4, 13, 17, 1, 32, 28436), datetime_complete=datetime.datetime(2024, 4, 13, 17, 1, 32, 184122), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.24015476348214576

In [45]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [46]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.635
train_ibs:  0.24

#### Test

In [47]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [48]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.566

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.288

In [49]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [50]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:01:32,378] A new study created in memory with name: no-name-442307e1-b18c-4acf-a31c-777856b27c42

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:01:32,524] Trial 0 finished with value: 0.635556441914194 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.635556441914194.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:32,660] Trial 1 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:32,798] Trial 2 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:01:32,929] Trial 3 finished with value: 0.6364148110129064 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:01:33,048] Trial 4 finished with value: 0.635556441914194 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:33,196] Trial 5 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:01:33,314] Trial 6 finished with value: 0.6347812481157444 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:01:33,436] Trial 7 finished with value: 0.635556441914194 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:01:33,567] Trial 8 finished with value: 0.6379720800356747 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:33,692] Trial 9 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:33,778] Trial 10 finished with value: 0.5657072459939985 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:33,861] Trial 11 finished with value: 0.5648561821642112 and parameters: {'l1_ratio': 0.10435988842665224}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:34,001] Trial 12 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.25848394608656616}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:34,138] Trial 13 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.23216328271690467}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:34,276] Trial 14 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.2652121201325421}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.4714828897338403
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:01:34,326] Trial 15 finished with value: 0.5737044246903527 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:34,458] Trial 16 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.3314184925703805}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:34,598] Trial 17 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.16511694733206428}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:01:34,744] Trial 18 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.5300759780628291}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.4714828897338403
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:01:34,791] Trial 19 finished with value: 0.5729076119413488 and parameters: {'l1_ratio': 0.013522847250075798}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:34,921] Trial 20 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.3350080673295819}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:35,052] Trial 21 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.437179985273821}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:01:35,182] Trial 22 finished with value: 0.635556441914194 and parameters: {'l1_ratio': 0.5917812085573658}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:35,312] Trial 23 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.3476267724368922}. Best is trial 1 with value: 0.6388304491343872.

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:35,454] Trial 24 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.16645977610301255}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:01:35,590] Trial 25 finished with value: 0.6379720800356747 and parameters: {'l1_ratio': 0.44908780975162055}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:35,727] Trial 26 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.2080204609486906}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:35,864] Trial 27 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.2972677334694329}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:01:35,984] Trial 28 finished with value: 0.6347812481157444 and parameters: {'l1_ratio': 0.964957522585106}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:01:36,110] Trial 29 finished with value: 0.635556441914194 and parameters: {'l1_ratio': 0.6080844889538715}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:36,243] Trial 30 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.39943410604828067}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:36,371] Trial 31 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.3695273894351256}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:36,513] Trial 32 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.3992968738641366}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:01:36,634] Trial 33 finished with value: 0.6347812481157444 and parameters: {'l1_ratio': 0.8602844507263662}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:01:36,760] Trial 34 finished with value: 0.6372116237619104 and parameters: {'l1_ratio': 0.4770138322209352}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:36,897] Trial 35 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.1806633199118713}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:36,979] Trial 36 finished with value: 0.5657072459939985 and parameters: {'l1_ratio': 0.1015778208871971}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:01:37,097] Trial 37 finished with value: 0.635556441914194 and parameters: {'l1_ratio': 0.6697205263544034}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:37,228] Trial 38 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.2799252299277851}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:01:37,348] Trial 39 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.5157351301291313}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:37,472] Trial 40 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.4144981991820652}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:37,603] Trial 41 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.26726685628462576}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:37,737] Trial 42 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.22918225621989}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:37,875] Trial 43 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.3058470858110508}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.4714828897338403
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:37,938] Trial 44 finished with value: 0.5649467897202343 and parameters: {'l1_ratio': 0.062069898702991955}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:38,040] Trial 45 finished with value: 0.6050697571176938 and parameters: {'l1_ratio': 0.14992535859099348}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:38,169] Trial 46 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.23151199792673188}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:38,301] Trial 47 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.346696712794244}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:01:38,426] Trial 48 finished with value: 0.6364148110129064 and parameters: {'l1_ratio': 0.5683872043393509}. Best is trial 1 with value: 0.6388304491343872.

Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:01:38,556] Trial 49 finished with value: 0.6372116237619104 and parameters: {'l1_ratio': 0.46569877065454696}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:38,684] Trial 50 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.374354691474329}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:38,820] Trial 51 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.24691530243536003}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:39,024] Trial 52 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.3110714730582038}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:39,126] Trial 53 finished with value: 0.6050697571176938 and parameters: {'l1_ratio': 0.1422586750152588}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:39,262] Trial 54 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.21324411525852566}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:39,440] Trial 55 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.27714116712834597}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:39,575] Trial 56 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.1862640519869659}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.4714828897338403
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:39,645] Trial 57 finished with value: 0.5657978535500213 and parameters: {'l1_ratio': 0.052696388185707044}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:39,727] Trial 58 finished with value: 0.5640051183344239 and parameters: {'l1_ratio': 0.13312766602554382}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:39,853] Trial 59 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.4319643417204989}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:39,979] Trial 60 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.3317824031689725}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:40,111] Trial 61 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.2558198544583058}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:40,242] Trial 62 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.1982281233625693}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:40,365] Trial 63 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.3810289172615642}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:40,490] Trial 64 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.3098620886569438}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:40,614] Trial 65 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.35801843510272}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:40,742] Trial 66 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.25211183842768015}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:40,863] Trial 67 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.43220106655433926}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:40,991] Trial 68 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.29171180912511996}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:01:41,114] Trial 69 finished with value: 0.6379720800356747 and parameters: {'l1_ratio': 0.4999761190055368}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:41,236] Trial 70 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.39722512164536367}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:41,361] Trial 71 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.3140065990053501}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:41,485] Trial 72 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.3286120105150903}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115

Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:41,615] Trial 73 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.20788143179679744}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:41,740] Trial 74 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.27951028159783387}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:41,873] Trial 75 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.23108018263957486}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:41,996] Trial 76 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.34958208811774705}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:42,128] Trial 77 finished with value: 0.6380336363853832 and parameters: {'l1_ratio': 0.17723235069643878}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:01:42,249] Trial 78 finished with value: 0.6372116237619104 and parameters: {'l1_ratio': 0.46804421268401275}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:01:42,364] Trial 79 finished with value: 0.635556441914194 and parameters: {'l1_ratio': 0.8187818034877232}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:42,484] Trial 80 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.41562611857011417}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:42,609] Trial 81 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.38010753640497846}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:42,733] Trial 82 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.32608036521927497}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:42,860] Trial 83 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.2658422796465507}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:42,940] Trial 84 finished with value: 0.5640051183344239 and parameters: {'l1_ratio': 0.11527502080989276}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:43,064] Trial 85 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.23912390413917411}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:43,193] Trial 86 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.3468463316595621}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:01:43,312] Trial 87 finished with value: 0.6364148110129064 and parameters: {'l1_ratio': 0.548864698196605}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:43,409] Trial 88 finished with value: 0.6058449509161434 and parameters: {'l1_ratio': 0.15957321792675105}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:43,531] Trial 89 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.28838462758806066}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:43,658] Trial 90 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.385766113129902}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:01:43,779] Trial 91 finished with value: 0.6379720800356747 and parameters: {'l1_ratio': 0.44578458491030076}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:43,902] Trial 92 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.4123771569460686}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:44,027] Trial 93 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.3641920999060202}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:01:44,147] Trial 94 finished with value: 0.6371752672866707 and parameters: {'l1_ratio': 0.5161118581306852}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:01:44,267] Trial 95 finished with value: 0.6379720800356747 and parameters: {'l1_ratio': 0.49088785607516083}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:44,395] Trial 96 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.225189918510303}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286

Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:44,522] Trial 97 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.30215064512282885}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:44,648] Trial 98 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.26529249237955993}. Best is trial 1 with value: 0.6388304491343872.
Fold 1 C-index: 0.5697211155378487

[I 2024-04-13 17:01:44,775] A new study created in memory with name: no-name-6ed15cab-af70-40a5-9e39-25b7d82f467a

Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:01:44,773] Trial 99 finished with value: 0.6388304491343872 and parameters: {'l1_ratio': 0.3339910928209391}. Best is trial 1 with value: 0.6388304491343872.


* Best trial for C-index:
 FrozenTrial(number=1, state=TrialState.COMPLETE, values=[0.6388304491343872], datetime_start=datetime.datetime(2024, 4, 13, 17, 1, 32, 526182), datetime_complete=datetime.datetime(2024, 4, 13, 17, 1, 32, 660342), params={'l1_ratio': 0.28621072101688444}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=1, value=None)


* Best Score for C-index:
 0.6388304491343872

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.26102620358767353
Fold 2 IBS: 0.26312657631566294
Fold 3 IBS: 0.1703241267537586
Fold 4 IBS: 0.29545196784653605
Fold 5 IBS: 0.21005729223038072
[I 2024-04-13 17:01:44,919] Trial 0 finished with value: 0.2399972333468024 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.2399972333468024.
Fold 1 IBS: 0.2588837003522285
Fold 2 IBS: 0.26303985644748085
Fold 3 IBS: 0.17022526620181144
Fold 4 IBS: 0.29526478881241885
Fold 5 IBS: 0.20973282979278876
[I 2024-04-13 17:01:45,057] Trial 1 finished with value: 0.23942928832134566 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.23942928832134566.
Fold 1 IBS: 0.2587173379871686
Fold 2 IBS: 0.2629671855344548
Fold 3 IBS: 0.1701580742235107
Fold 4 IBS: 0.29522557084537643
Fold 5 IBS: 0.20968044356486212
[I 2024-04-13 17:01:45,198] Trial 2 finished with value: 0.2393497224310745 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.2393497224310745.
Fold 1 IBS: 0.2607211266496292
Fold 2 IBS: 0.26310922661690794
Fold 3 IBS: 0.17029681400759036
Fold 4 IBS: 0.29537272159320005
Fold 5 IBS: 0.20995110132762665
[I 2024-04-13 17:01:45,329] Trial 3 finished with value: 0.23989019803899084 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.2393497224310745.
Fold 1 IBS: 0.2610655911709609
Fold 2 IBS: 0.26319503308188436
Fold 3 IBS: 0.1703073167257421
Fold 4 IBS: 0.29547232674577956
Fold 5 IBS: 0.21008188380523105
[I 2024-04-13 17:01:45,455] Trial 4 finished with value: 0.24002443030591958 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.2393497224310745.
Fold 1 IBS: 0.2590648120614187
Fold 2 IBS: 0.26299095982239107
Fold 3 IBS: 0.17033455879385287
Fold 4 IBS: 0.2953399560158399
Fold 5 IBS: 0.20983267136176742
[I 2024-04-13 17:01:45,588] Trial 5 finished with value: 0.23951259161105395 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.2393497224310745.
Fold 1 IBS: 0.2612917586165268
Fold 2 IBS: 0.2631448868151182
Fold 3 IBS: 0.1704461061973579
Fold 4 IBS: 0.2955703167451884
Fold 5 IBS: 0.210251598666525
[I 2024-04-13 17:01:45,712] Trial 6 finished with value: 0.2401409334081433 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.2393497224310745.
Fold 1 IBS: 0.2610052783022354
Fold 2 IBS: 0.2631041279023455
Fold 3 IBS: 0.1703333495015468
Fold 4 IBS: 0.29544114901938034
Fold 5 IBS: 0.21004386762783672
[I 2024-04-13 17:01:45,841] Trial 7 finished with value: 0.23998555447066897 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.2393497224310745.
Fold 1 IBS: 0.2592673810199399
Fold 2 IBS: 0.2630408360484983
Fold 3 IBS: 0.17024553356810554
Fold 4 IBS: 0.2953568727920893
Fold 5 IBS: 0.20988614501025893
[I 2024-04-13 17:01:45,974] Trial 8 finished with value: 0.2395593536877784 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.2393497224310745.
Fold 1 IBS: 0.25906372625973917
Fold 2 IBS: 0.2630584557276728
Fold 3 IBS: 0.17024603991801524
Fold 4 IBS: 0.2953585386599391
Fold 5 IBS: 0.20982711315956876
[I 2024-04-13 17:01:46,106] Trial 9 finished with value: 0.23951077474498703 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.2393497224310745.
Fold 1 IBS: 0.25791263164583694
Fold 2 IBS: 0.2320530936657206
Fold 3 IBS: 0.22600352369036084
Fold 4 IBS: 0.25573262246547557
Fold 5 IBS: 0.22494271305698404
[I 2024-04-13 17:01:46,181] Trial 10 finished with value: 0.23932891690487562 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.23932891690487562.
Fold 1 IBS: 0.24645720511843078
Fold 2 IBS: 0.23201343803036442
Fold 3 IBS: 0.2284504901344544
Fold 4 IBS: 0.24420820725177642
Fold 5 IBS: 0.2285485153889123
[I 2024-04-13 17:01:46,237] Trial 11 finished with value: 0.23593557118478764 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 11 with value: 0.23593557118478764.
Fold 1 IBS: 0.24568015841468535
Fold 2 IBS: 0.23199756282309542
Fold 3 IBS: 0.22790297886572866
Fold 4 IBS: 0.24669292930267472
Fold 5 IBS: 0.2276990186083789
[I 2024-04-13 17:01:46,296] Trial 12 finished with value: 0.2359945296029126 and parameters: {'l1_ratio': 0.025939717088620355}. Best is trial 11 with value: 0.23593557118478764.
Fold 1 IBS: 0.2469440117018254
Fold 2 IBS: 0.23202867878998662
Fold 3 IBS: 0.22878039678493542
Fold 4 IBS: 0.24279661755152676
Fold 5 IBS: 0.22907136479656717
[I 2024-04-13 17:01:46,351] Trial 13 finished with value: 0.2359242139249683 and parameters: {'l1_ratio': 0.004533947374774427}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2584323664564626
Fold 2 IBS: 0.23230332469734985
Fold 3 IBS: 0.22427413161536
Fold 4 IBS: 0.29514459697844203
Fold 5 IBS: 0.20956184217828136
[I 2024-04-13 17:01:46,465] Trial 14 finished with value: 0.24394325238517917 and parameters: {'l1_ratio': 0.15622422014607515}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24681335018424969
Fold 2 IBS: 0.23202425180115044
Fold 3 IBS: 0.22869234579215875
Fold 4 IBS: 0.24316373075850062
Fold 5 IBS: 0.22893219031666712
[I 2024-04-13 17:01:46,519] Trial 15 finished with value: 0.23592517377054537 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2588833252515829
Fold 2 IBS: 0.2630299238071986
Fold 3 IBS: 0.1702286273333022
Fold 4 IBS: 0.295261292355687
Fold 5 IBS: 0.20972927371954242
[I 2024-04-13 17:01:46,664] Trial 16 finished with value: 0.23942648849346262 and parameters: {'l1_ratio': 0.28499627491162527}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25843305656285304
Fold 2 IBS: 0.23230546437336863
Fold 3 IBS: 0.22426392584094554
Fold 4 IBS: 0.29514746145697196
Fold 5 IBS: 0.20956468627474065
[I 2024-04-13 17:01:46,771] Trial 17 finished with value: 0.24394291890177597 and parameters: {'l1_ratio': 0.15671420368983202}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.26129728845635364
Fold 2 IBS: 0.263156597690616
Fold 3 IBS: 0.1704433966901291
Fold 4 IBS: 0.29557322880331777
Fold 5 IBS: 0.21025513230109427
[I 2024-04-13 17:01:46,900] Trial 18 finished with value: 0.24014512878830213 and parameters: {'l1_ratio': 0.9862904274960449}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2582871116727416
Fold 2 IBS: 0.23217277475908432
Fold 3 IBS: 0.22498842178147324
Fold 4 IBS: 0.2601660300559746
Fold 5 IBS: 0.2095748903858093
[I 2024-04-13 17:01:46,990] Trial 19 finished with value: 0.23703784573101663 and parameters: {'l1_ratio': 0.12363244492728864}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25906201043197596
Fold 2 IBS: 0.2630337238687309
Fold 3 IBS: 0.17027957903072874
Fold 4 IBS: 0.29526725447365393
Fold 5 IBS: 0.20975575885062714
[I 2024-04-13 17:01:47,145] Trial 20 finished with value: 0.23947966533114334 and parameters: {'l1_ratio': 0.31598698424339017}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2466515879488575
Fold 2 IBS: 0.23201907902926708
Fold 3 IBS: 0.22858337526573258
Fold 4 IBS: 0.2436306942164895
Fold 5 IBS: 0.2287582714928026
[I 2024-04-13 17:01:47,203] Trial 21 finished with value: 0.23592860159062984 and parameters: {'l1_ratio': 0.009107838351343097}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2467059047979971
Fold 2 IBS: 0.23202076248225093
Fold 3 IBS: 0.22862025655475351
Fold 4 IBS: 0.24347250274085078
Fold 5 IBS: 0.22881673399063265
[I 2024-04-13 17:01:47,264] Trial 22 finished with value: 0.23592723211329697 and parameters: {'l1_ratio': 0.008242879725625268}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.258091934166642
Fold 2 IBS: 0.23208711137049082
Fold 3 IBS: 0.22564421348738073
Fold 4 IBS: 0.257361059583547
Fold 5 IBS: 0.20951092972601587
[I 2024-04-13 17:01:47,355] Trial 23 finished with value: 0.23653904966681524 and parameters: {'l1_ratio': 0.097070668839174}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2586960376648879
Fold 2 IBS: 0.26309233080896405
Fold 3 IBS: 0.17015776416797407
Fold 4 IBS: 0.2951863519894293
Fold 5 IBS: 0.20962227132590494
[I 2024-04-13 17:01:47,508] Trial 24 finished with value: 0.23935095119143207 and parameters: {'l1_ratio': 0.19621932764719313}. Best is trial 13 with value: 0.2359242139249683.

Fold 1 IBS: 0.2578444032559643
Fold 2 IBS: 0.2320308875725676
Fold 3 IBS: 0.2263064516043076
Fold 4 IBS: 0.2543205914847007
Fold 5 IBS: 0.2253616485058363
[I 2024-04-13 17:01:47,581] Trial 25 finished with value: 0.23917279648467532 and parameters: {'l1_ratio': 0.07330522822697523}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25866786192150326
Fold 2 IBS: 0.26317276643326787
Fold 3 IBS: 0.17012862694920441
Fold 4 IBS: 0.29521598225183937
Fold 5 IBS: 0.20965163859069955
[I 2024-04-13 17:01:47,729] Trial 26 finished with value: 0.2393673752293029 and parameters: {'l1_ratio': 0.20309774849254153}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25772258764105377
Fold 2 IBS: 0.23200587852032056
Fold 3 IBS: 0.22681478866412372
Fold 4 IBS: 0.25189660165357836
Fold 5 IBS: 0.22608260794741947
[I 2024-04-13 17:01:47,806] Trial 27 finished with value: 0.23890449288529916 and parameters: {'l1_ratio': 0.056847137315710346}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.26117600885426856
Fold 2 IBS: 0.2631688052920563
Fold 3 IBS: 0.17039958951229142
Fold 4 IBS: 0.29553073220309467
Fold 5 IBS: 0.2101534913748118
[I 2024-04-13 17:01:47,940] Trial 28 finished with value: 0.24008572544730455 and parameters: {'l1_ratio': 0.7951764349453078}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25888172317822683
Fold 2 IBS: 0.2631660542478868
Fold 3 IBS: 0.17021526698562847
Fold 4 IBS: 0.29521966037344877
Fold 5 IBS: 0.2096848989476173
[I 2024-04-13 17:01:48,086] Trial 29 finished with value: 0.2394335207465616 and parameters: {'l1_ratio': 0.24708024444665308}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24707211600501044
Fold 2 IBS: 0.23203326381205944
Fold 3 IBS: 0.2288660880975629
Fold 4 IBS: 0.2424431792675503
Fold 5 IBS: 0.2292089909375643
[I 2024-04-13 17:01:48,145] Trial 30 finished with value: 0.2359247276239495 and parameters: {'l1_ratio': 0.002591208849787703}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2472385162874404
Fold 2 IBS: 0.23203955006193974
Fold 3 IBS: 0.2289762152374779
Fold 4 IBS: 0.24199738975970717
Fold 5 IBS: 0.22938646503342036
[I 2024-04-13 17:01:48,202] Trial 31 finished with value: 0.2359276272759971 and parameters: {'l1_ratio': 0.00012562645093619398}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25820847168361993
Fold 2 IBS: 0.23216218160288843
Fold 3 IBS: 0.22505775339001893
Fold 4 IBS: 0.2598810699176566
Fold 5 IBS: 0.2095534885000207
[I 2024-04-13 17:01:48,298] Trial 32 finished with value: 0.23697259301884094 and parameters: {'l1_ratio': 0.12066622052430043}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25791426053251265
Fold 2 IBS: 0.2320567879389283
Fold 3 IBS: 0.22595967334084172
Fold 4 IBS: 0.2559342929644505
Fold 5 IBS: 0.22488277054524186
[I 2024-04-13 17:01:48,374] Trial 33 finished with value: 0.239349557064395 and parameters: {'l1_ratio': 0.08539796135807573}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25852230901752565
Fold 2 IBS: 0.2630114821494072
Fold 3 IBS: 0.1701514689483313
Fold 4 IBS: 0.2951496540710946
Fold 5 IBS: 0.20964528012234118
[I 2024-04-13 17:01:48,521] Trial 34 finished with value: 0.23929603886174 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25906560317292887
Fold 2 IBS: 0.26316985541992716
Fold 3 IBS: 0.1702360387711481
Fold 4 IBS: 0.29531365623577394
Fold 5 IBS: 0.2097461290244606
[I 2024-04-13 17:01:48,658] Trial 35 finished with value: 0.23950625652484775 and parameters: {'l1_ratio': 0.3349958381129322}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25887958458885574
Fold 2 IBS: 0.2631325858685251
Fold 3 IBS: 0.17022739004590712
Fold 4 IBS: 0.29520871939172544
Fold 5 IBS: 0.20967227039442224
[I 2024-04-13 17:01:48,803] Trial 36 finished with value: 0.2394241100578871 and parameters: {'l1_ratio': 0.24351510849404986}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.26078290133238474
Fold 2 IBS: 0.2632048154083435
Fold 3 IBS: 0.1702882715665923
Fold 4 IBS: 0.29540873247411703
Fold 5 IBS: 0.2099897448357291
[I 2024-04-13 17:01:48,938] Trial 37 finished with value: 0.23993489312343336 and parameters: {'l1_ratio': 0.5802102856643269}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2582957759413057
Fold 2 IBS: 0.23218437933694588
Fold 3 IBS: 0.2249151835540009
Fold 4 IBS: 0.26046384486998914
Fold 5 IBS: 0.2095967959898561
[I 2024-04-13 17:01:49,035] Trial 38 finished with value: 0.23709119593841957 and parameters: {'l1_ratio': 0.12680893872224136}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25763565659647386
Fold 2 IBS: 0.23199939014626972
Fold 3 IBS: 0.2270386850666873
Fold 4 IBS: 0.25081768452627357
Fold 5 IBS: 0.22640717996673496
[I 2024-04-13 17:01:49,113] Trial 39 finished with value: 0.23877971926048785 and parameters: {'l1_ratio': 0.050035165521521104}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.26112331736143213
Fold 2 IBS: 0.26326222297620727
Fold 3 IBS: 0.17037539832287826
Fold 4 IBS: 0.2954812865109621
Fold 5 IBS: 0.21016128088182645
[I 2024-04-13 17:01:49,248] Trial 40 finished with value: 0.24008070121066125 and parameters: {'l1_ratio': 0.8326964128984928}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24561517955702092
Fold 2 IBS: 0.23199678180827066
Fold 3 IBS: 0.22785603581565975
Fold 4 IBS: 0.24691233779969984
Fold 5 IBS: 0.2276272955623548
[I 2024-04-13 17:01:49,305] Trial 41 finished with value: 0.2360015261086012 and parameters: {'l1_ratio': 0.027165947903966002}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24570103185283307
Fold 2 IBS: 0.23199783316826267
Fold 3 IBS: 0.22791801991006733
Fold 4 IBS: 0.24662280358453964
Fold 5 IBS: 0.22772203679777403
[I 2024-04-13 17:01:49,360] Trial 42 finished with value: 0.23599234506269537 and parameters: {'l1_ratio': 0.025548686291035096}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24711938335249162
Fold 2 IBS: 0.23203501074063917
Fold 3 IBS: 0.2288974769376172
Fold 4 IBS: 0.2423151340107149
Fold 5 IBS: 0.22925950626861805
[I 2024-04-13 17:01:49,419] Trial 43 finished with value: 0.2359253022620162 and parameters: {'l1_ratio': 0.0018849190134430063}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2578470789090792
Fold 2 IBS: 0.23203409990354573
Fold 3 IBS: 0.22625737975269522
Fold 4 IBS: 0.2545513706759943
Fold 5 IBS: 0.2252932487930915
[I 2024-04-13 17:01:49,496] Trial 44 finished with value: 0.23919663560688117 and parameters: {'l1_ratio': 0.07497180028754816}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24707607727157418
Fold 2 IBS: 0.23203340901286662
Fold 3 IBS: 0.22886872189960686
Fold 4 IBS: 0.2424324054593742
Fold 5 IBS: 0.22921322750659237
[I 2024-04-13 17:01:49,554] Trial 45 finished with value: 0.23592476823000283 and parameters: {'l1_ratio': 0.0025318355521207446}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2583059895270013
Fold 2 IBS: 0.23220504671078906
Fold 3 IBS: 0.22479100203932995
Fold 4 IBS: 0.2609611309095303
Fold 5 IBS: 0.20956079796143315
[I 2024-04-13 17:01:49,646] Trial 46 finished with value: 0.23716479342961674 and parameters: {'l1_ratio': 0.1322985016863532}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25768021299982447
Fold 2 IBS: 0.23200407574957352
Fold 3 IBS: 0.22686861892880858
Fold 4 IBS: 0.25163749458402046
Fold 5 IBS: 0.22616025632013778
[I 2024-04-13 17:01:49,725] Trial 47 finished with value: 0.23887013171647292 and parameters: {'l1_ratio': 0.05518609830470697}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2607571635479472
Fold 2 IBS: 0.26317554843547636
Fold 3 IBS: 0.1702786264812531
Fold 4 IBS: 0.29539442654501386
Fold 5 IBS: 0.20997412360475684
[I 2024-04-13 17:01:49,855] Trial 48 finished with value: 0.23991597772288947 and parameters: {'l1_ratio': 0.5683872043393509}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2590582780021155
Fold 2 IBS: 0.2631201916063273
Fold 3 IBS: 0.17029659832714253
Fold 4 IBS: 0.29538251602468624
Fold 5 IBS: 0.20987651153817408
[I 2024-04-13 17:01:49,993] Trial 49 finished with value: 0.23954681909968914 and parameters: {'l1_ratio': 0.4477016529538363}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25856444498047715

Fold 2 IBS: 0.2630950559724324
Fold 3 IBS: 0.17012112790234593
Fold 4 IBS: 0.2951804917569898
Fold 5 IBS: 0.20960653389035813
[I 2024-04-13 17:01:50,145] Trial 50 finished with value: 0.23931353090052068 and parameters: {'l1_ratio': 0.1780409676995512}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24684804227027152
Fold 2 IBS: 0.23202540235002309
Fold 3 IBS: 0.22871579490331465
Fold 4 IBS: 0.2430652229173587
Fold 5 IBS: 0.22896941427316414
[I 2024-04-13 17:01:50,204] Trial 51 finished with value: 0.2359247753428264 and parameters: {'l1_ratio': 0.006012844952470507}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2579790079397853
Fold 2 IBS: 0.23206724896637737
Fold 3 IBS: 0.225842762182722
Fold 4 IBS: 0.2564681131417791
Fold 5 IBS: 0.20951696835839173
[I 2024-04-13 17:01:50,298] Trial 52 finished with value: 0.23637482011781108 and parameters: {'l1_ratio': 0.08964599767605695}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24717396337779457
Fold 2 IBS: 0.2320370664453876
Fold 3 IBS: 0.22893361689668706
Fold 4 IBS: 0.24216867342079934
Fold 5 IBS: 0.2293177359032219
[I 2024-04-13 17:01:50,359] Trial 53 finished with value: 0.2359262112087781 and parameters: {'l1_ratio': 0.001075229365676048}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24491921142100131
Fold 2 IBS: 0.23199470638119143
Fold 3 IBS: 0.22734157487757536
Fold 4 IBS: 0.24935832828413348
Fold 5 IBS: 0.22685293718520247
[I 2024-04-13 17:01:50,416] Trial 54 finished with value: 0.23609335162982079 and parameters: {'l1_ratio': 0.04121008262420096}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.258287530930302
Fold 2 IBS: 0.23217317118945857
Fold 3 IBS: 0.22498587451506757
Fold 4 IBS: 0.2601764437806928
Fold 5 IBS: 0.20957566419699455
[I 2024-04-13 17:01:50,510] Trial 55 finished with value: 0.2370397369225031 and parameters: {'l1_ratio': 0.1237421768512342}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2576804864183507
Fold 2 IBS: 0.23200448943161997
Fold 3 IBS: 0.2268558457872782
Fold 4 IBS: 0.2516990001899672
Fold 5 IBS: 0.22614180923304386
[I 2024-04-13 17:01:50,586] Trial 56 finished with value: 0.238876326212052 and parameters: {'l1_ratio': 0.05557888545754185}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2608903091830339
Fold 2 IBS: 0.26315191442829133
Fold 3 IBS: 0.1703768343564133
Fold 4 IBS: 0.29546131214565285
Fold 5 IBS: 0.21001101795165006
[I 2024-04-13 17:01:50,721] Trial 57 finished with value: 0.2399782776130083 and parameters: {'l1_ratio': 0.6269556745411495}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25809278738675456
Fold 2 IBS: 0.23208802596115505
Fold 3 IBS: 0.22563567538017013
Fold 4 IBS: 0.25739904649222
Fold 5 IBS: 0.20951397428784616
[I 2024-04-13 17:01:50,813] Trial 58 finished with value: 0.23654590190162922 and parameters: {'l1_ratio': 0.09739603238555941}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2590657031509424
Fold 2 IBS: 0.26312299222225144
Fold 3 IBS: 0.1703082536379818
Fold 4 IBS: 0.2953003248869398
Fold 5 IBS: 0.20981880841795925
[I 2024-04-13 17:01:50,952] Trial 59 finished with value: 0.23952321646321492 and parameters: {'l1_ratio': 0.3635438827822911}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25841361295249277
Fold 2 IBS: 0.2322536899197853
Fold 3 IBS: 0.22452414954136482
Fold 4 IBS: 0.29515573892486496
Fold 5 IBS: 0.20956565827001344
[I 2024-04-13 17:01:51,062] Trial 60 finished with value: 0.24398256992170425 and parameters: {'l1_ratio': 0.1445244531464486}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24712868327047205
Fold 2 IBS: 0.23203535811434808
Fold 3 IBS: 0.22890364279570796
Fold 4 IBS: 0.24229007270795336
Fold 5 IBS: 0.22926943569956376
[I 2024-04-13 17:01:51,119] Trial 61 finished with value: 0.23592543851760905 and parameters: {'l1_ratio': 0.0017465125752551772}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24525852787426644
Fold 2 IBS: 0.23199421194480857
Fold 3 IBS: 0.22759509488708068
Fold 4 IBS: 0.24814504592628917
Fold 5 IBS: 0.22723184555004072
[I 2024-04-13 17:01:51,174] Trial 62 finished with value: 0.23604494523649713 and parameters: {'l1_ratio': 0.03414717765066741}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24723960962056726
Fold 2 IBS: 0.23203959260844137
Fold 3 IBS: 0.22897693537252373
Fold 4 IBS: 0.2419945068744616
Fold 5 IBS: 0.22938762778565677
[I 2024-04-13 17:01:51,233] Trial 63 finished with value: 0.23592765445233016 and parameters: {'l1_ratio': 0.0001096174171489623}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2579859196165395
Fold 2 IBS: 0.2320785638711964
Fold 3 IBS: 0.22572640907772876
Fold 4 IBS: 0.2569935881624941
Fold 5 IBS: 0.20955851736868333
[I 2024-04-13 17:01:51,323] Trial 64 finished with value: 0.23646859961932845 and parameters: {'l1_ratio': 0.0939643366502645}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25767891448398533
Fold 2 IBS: 0.23200226690660392
Fold 3 IBS: 0.22692799545612113
Fold 4 IBS: 0.25135142590055765
Fold 5 IBS: 0.22624618974051738
[I 2024-04-13 17:01:51,403] Trial 65 finished with value: 0.2388413584975571 and parameters: {'l1_ratio': 0.053371161547616786}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24512247835700438
Fold 2 IBS: 0.2319940466673268
Fold 3 IBS: 0.22749407016880452
Fold 4 IBS: 0.2486271038700155
Fold 5 IBS: 0.22708022596910205
[I 2024-04-13 17:01:51,459] Trial 66 finished with value: 0.2360635850064506 and parameters: {'l1_ratio': 0.036927596488124284}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2612563271402599
Fold 2 IBS: 0.2632722653802868
Fold 3 IBS: 0.17031977087054073
Fold 4 IBS: 0.29554903179310804
Fold 5 IBS: 0.2102493893193896
[I 2024-04-13 17:01:51,590] Trial 67 finished with value: 0.24012935690071702 and parameters: {'l1_ratio': 0.9415445204645163}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2587197699305225
Fold 2 IBS: 0.2630582406542639
Fold 3 IBS: 0.1702093506551365
Fold 4 IBS: 0.29517388285909846
Fold 5 IBS: 0.20962804654443337
[I 2024-04-13 17:01:51,732] Trial 68 finished with value: 0.23935785812869095 and parameters: {'l1_ratio': 0.21354140760843326}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.258112705817196
Fold 2 IBS: 0.23210902954575227
Fold 3 IBS: 0.22545127422328565
Fold 4 IBS: 0.25821060773358784
Fold 5 IBS: 0.20957650405707887
[I 2024-04-13 17:01:51,830] Trial 69 finished with value: 0.2366920242753801 and parameters: {'l1_ratio': 0.10454960022487644}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25783781734146316
Fold 2 IBS: 0.23202444824576865
Fold 3 IBS: 0.22641234231749255
Fold 4 IBS: 0.2538202775759092
Fold 5 IBS: 0.2255099730666351
[I 2024-04-13 17:01:51,903] Trial 70 finished with value: 0.2391209717094537 and parameters: {'l1_ratio': 0.06975723835643693}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.246346045541839
Fold 2 IBS: 0.2320104866453893
Fold 3 IBS: 0.22837370569333915
Fold 4 IBS: 0.24454701205809865
Fold 5 IBS: 0.22842794719264742
[I 2024-04-13 17:01:51,961] Trial 71 finished with value: 0.2359410394262627 and parameters: {'l1_ratio': 0.014114435350334686}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2470913657235829
Fold 2 IBS: 0.23203397148104948
Fold 3 IBS: 0.22887888145717286
Fold 4 IBS: 0.24239089763862431
Fold 5 IBS: 0.2292295731651667
[I 2024-04-13 17:01:52,016] Trial 72 finished with value: 0.23592493789311925 and parameters: {'l1_ratio': 0.0023029984348619547}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24703629587447956
Fold 2 IBS: 0.23203196089349135
Fold 3 IBS: 0.2288422447419653
Fold 4 IBS: 0.24254095789070215
Fold 5 IBS: 0.22917065564661868
[I 2024-04-13 17:01:52,077] Trial 73 finished with value: 0.23592442300945143 and parameters: {'l1_ratio': 0.0031296198634026286}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2577849045950553
Fold 2 IBS: 0.232019189550553
Fold 3 IBS: 0.22650819377841253
Fold 4 IBS: 0.25336494001996374
Fold 5 IBS: 0.22564508535203828
[I 2024-04-13 17:01:52,153] Trial 74 finished with value: 0.23906446265920459 and parameters: {'l1_ratio': 0.06660130703424111}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25842634194176206
Fold 2 IBS: 0.23228598566150518
Fold 3 IBS: 0.2243584835887543

Fold 4 IBS: 0.295120472001801
Fold 5 IBS: 0.20961116135161323
[I 2024-04-13 17:01:52,270] Trial 75 finished with value: 0.24396048890908711 and parameters: {'l1_ratio': 0.15221237807038437}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2450599313994901
Fold 2 IBS: 0.23199413137287353
Fold 3 IBS: 0.2274473459644907
Fold 4 IBS: 0.2488507488904063
Fold 5 IBS: 0.22701038289912787
[I 2024-04-13 17:01:52,326] Trial 76 finished with value: 0.2360725081052777 and parameters: {'l1_ratio': 0.038228682177325266}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2589012977495234
Fold 2 IBS: 0.262979026769936
Fold 3 IBS: 0.1702531063542334
Fold 4 IBS: 0.29524255554919454
Fold 5 IBS: 0.20971018848551673
[I 2024-04-13 17:01:52,469] Trial 77 finished with value: 0.23941723498168083 and parameters: {'l1_ratio': 0.2786795986705474}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2581887635298997
Fold 2 IBS: 0.23212913543895755
Fold 3 IBS: 0.22529205984444553
Fold 4 IBS: 0.2588969769601329
Fold 5 IBS: 0.20955388902507285
[I 2024-04-13 17:01:52,561] Trial 78 finished with value: 0.2368121649597017 and parameters: {'l1_ratio': 0.11092660994073819}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24553223028681925
Fold 2 IBS: 0.23199592058441598
Fold 3 IBS: 0.22779584432914768
Fold 4 IBS: 0.2471948187906091
Fold 5 IBS: 0.22753558950649483
[I 2024-04-13 17:01:52,622] Trial 79 finished with value: 0.23601088069949738 and parameters: {'l1_ratio': 0.02875128467837897}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2585254480923548
Fold 2 IBS: 0.26304814349843103
Fold 3 IBS: 0.17013818092293165
Fold 4 IBS: 0.29516333355353763
Fold 5 IBS: 0.20958906247543227
[I 2024-04-13 17:01:52,768] Trial 80 finished with value: 0.23929283370853746 and parameters: {'l1_ratio': 0.17458199834018892}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2471072038144689
Fold 2 IBS: 0.23203455762081365
Fold 3 IBS: 0.22888939694513252
Fold 4 IBS: 0.24234802088280546
Fold 5 IBS: 0.22924649755016474
[I 2024-04-13 17:01:52,828] Trial 81 finished with value: 0.23592513536267706 and parameters: {'l1_ratio': 0.0020664579326007413}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25784305037711225
Fold 2 IBS: 0.23202945888706367
Fold 3 IBS: 0.226329022041749
Fold 4 IBS: 0.25421420888571894
Fold 5 IBS: 0.22539318053753266
[I 2024-04-13 17:01:52,903] Trial 82 finished with value: 0.23916178414583528 and parameters: {'l1_ratio': 0.07254348264924586}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24566322405607302
Fold 2 IBS: 0.23199735040910838
Fold 3 IBS: 0.22789076245497053
Fold 4 IBS: 0.24674994917307935
Fold 5 IBS: 0.2276803364641102
[I 2024-04-13 17:01:52,961] Trial 83 finished with value: 0.2359963245114683 and parameters: {'l1_ratio': 0.026257979024475277}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24705515576774872
Fold 2 IBS: 0.23203264463522086
Fold 3 IBS: 0.22885480471464734
Fold 4 IBS: 0.24248939609180628
Fold 5 IBS: 0.22919084558135247
[I 2024-04-13 17:01:53,016] Trial 84 finished with value: 0.23592456935815515 and parameters: {'l1_ratio': 0.0028457953476208274}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25772178170254495
Fold 2 IBS: 0.23200698768295216
Fold 3 IBS: 0.22678378966237012
Fold 4 IBS: 0.25204568319932563
Fold 5 IBS: 0.22603800469607513
[I 2024-04-13 17:01:53,093] Trial 85 finished with value: 0.2389192493886536 and parameters: {'l1_ratio': 0.057810499291771456}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.26065190706414404
Fold 2 IBS: 0.26321379287167374
Fold 3 IBS: 0.17034906505335004
Fold 4 IBS: 0.2954107704393926
Fold 5 IBS: 0.20994635683112994
[I 2024-04-13 17:01:53,223] Trial 86 finished with value: 0.23991437845193805 and parameters: {'l1_ratio': 0.5196302291802515}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25791295231520356
Fold 2 IBS: 0.23205363358619172
Fold 3 IBS: 0.22599702198256674
Fold 4 IBS: 0.2557625715919589
Fold 5 IBS: 0.22493381426043255
[I 2024-04-13 17:01:53,301] Trial 87 finished with value: 0.2393319987472707 and parameters: {'l1_ratio': 0.08405944781697436}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24595450226164678
Fold 2 IBS: 0.2320018428032026
Fold 3 IBS: 0.22809917860764137
Fold 4 IBS: 0.24578552598587902
Fold 5 IBS: 0.22800069520497854
[I 2024-04-13 17:01:53,357] Trial 88 finished with value: 0.23596834897266966 and parameters: {'l1_ratio': 0.02090880805288451}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24496373733099558
Fold 2 IBS: 0.23199446583952468
Fold 3 IBS: 0.2273751401444472
Fold 4 IBS: 0.24919707898465376
Fold 5 IBS: 0.22690280139320987
[I 2024-04-13 17:01:53,415] Trial 89 finished with value: 0.23608664473856625 and parameters: {'l1_ratio': 0.04025849344211467}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2582907941424519
Fold 2 IBS: 0.23217630609412573
Fold 3 IBS: 0.22496584666028102
Fold 4 IBS: 0.26025818266919165
Fold 5 IBS: 0.2095817180185462
[I 2024-04-13 17:01:53,505] Trial 90 finished with value: 0.23705456951691928 and parameters: {'l1_ratio': 0.12460681386718837}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24716873171074255
Fold 2 IBS: 0.23203686763032197
Fold 3 IBS: 0.2289301576422096
Fold 4 IBS: 0.24218264718354454
Fold 5 IBS: 0.2293121591080678
[I 2024-04-13 17:01:53,564] Trial 91 finished with value: 0.2359261126549773 and parameters: {'l1_ratio': 0.0011525697575287333}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24604516970968343
Fold 2 IBS: 0.2320035900309127
Fold 3 IBS: 0.22816331839588416
Fold 4 IBS: 0.24549264560582043
Fold 5 IBS: 0.22809998204254478
[I 2024-04-13 17:01:53,619] Trial 92 finished with value: 0.2359609411569691 and parameters: {'l1_ratio': 0.019296323645732062}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2576772843030978
Fold 2 IBS: 0.23200138566030729
Fold 3 IBS: 0.22695939887038946
Fold 4 IBS: 0.25120004384360356
Fold 5 IBS: 0.22629175907937532
[I 2024-04-13 17:01:53,696] Trial 93 finished with value: 0.2388259743513547 and parameters: {'l1_ratio': 0.0524184929467753}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25791405011817287
Fold 2 IBS: 0.23205601832903167
Fold 3 IBS: 0.22596868802423195
Fold 4 IBS: 0.2558928955587251
Fold 5 IBS: 0.22489507906268227
[I 2024-04-13 17:01:53,771] Trial 94 finished with value: 0.23934534621856876 and parameters: {'l1_ratio': 0.08507406903449975}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24710856406988654
Fold 2 IBS: 0.2320346081245935
Fold 3 IBS: 0.22889029962636329
Fold 4 IBS: 0.2423443442680578
Fold 5 IBS: 0.22924795067828618
[I 2024-04-13 17:01:53,832] Trial 95 finished with value: 0.23592515335343744 and parameters: {'l1_ratio': 0.0020461674314282887}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.24596291477404394
Fold 2 IBS: 0.23200199818218298
Fold 3 IBS: 0.22810514434360935
Fold 4 IBS: 0.24575820128189593
Fold 5 IBS: 0.22800991621815134
[I 2024-04-13 17:01:53,893] Trial 96 finished with value: 0.2359676349599767 and parameters: {'l1_ratio': 0.020758170351329628}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.25778566259579966
Fold 2 IBS: 0.23202063822814248
Fold 3 IBS: 0.2264807928380193
Fold 4 IBS: 0.2534953259063801
Fold 5 IBS: 0.22560637894337554
[I 2024-04-13 17:01:54,099] Trial 97 finished with value: 0.2390777597023434 and parameters: {'l1_ratio': 0.06749816721354181}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.258175904419489
Fold 2 IBS: 0.23211791265962659
Fold 3 IBS: 0.22537910634625477
Fold 4 IBS: 0.258523426635237
Fold 5 IBS: 0.20952513698984238
[I 2024-04-13 17:01:54,191] Trial 98 finished with value: 0.23674429741008995 and parameters: {'l1_ratio': 0.10741660909157803}. Best is trial 13 with value: 0.2359242139249683.
Fold 1 IBS: 0.2448123037246297
Fold 2 IBS: 0.23199551169276028
Fold 3 IBS: 0.22726061196669084
Fold 4 IBS: 0.24974781722449496
Fold 5 IBS: 0.22673304120467752
[I 2024-04-13 17:01:54,253] Trial 99 finished with value: 0.23610985716265068 and parameters: {'l1_ratio': 0.04352668173749673}. Best is trial 13 with value: 0.2359242139249683.


* Best trial for IBS:
 FrozenTrial(number=13, state=TrialState.COMPLETE, values=[0.2359242139249683], datetime_start=datetime.datetime(2024, 4, 13, 17, 1, 46, 296819), datetime_complete=datetime.datetime(2024, 4, 13, 17, 1, 46, 351315), params={'l1_ratio': 0.004533947374774427}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=13, value=None)


* Best Score for IBS:
 0.2359242139249683

In [51]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [52]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.639
train_ibs:  0.236

#### Test

In [53]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [54]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.28621072101688444)

test_cindex : 0.564

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.004533947374774427)

test_ibs:  0.229

In [55]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [56]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:01:54,338] A new study created in memory with name: no-name-dafbc98e-fec3-45b9-991e-681ff16002eb

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6201550387596899
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.6673003802281369
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:01:55,552] Trial 0 finished with value: 0.6187977301006736 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6187977301006736.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6094420600858369
[I 2024-04-13 17:01:56,384] Trial 1 finished with value: 0.6237488136710192 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:01:57,038] Trial 2 finished with value: 0.6229733658988998 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:01:57,277] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:01:57,595] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 17:01:58,683] Trial 5 finished with value: 0.6218270216571679 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6094420600858369
[I 2024-04-13 17:01:59,926] Trial 6 finished with value: 0.5995723609793941 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:02:00,485] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5214592274678111
[I 2024-04-13 17:02:02,196] Trial 8 finished with value: 0.5042918454935622 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:02:03,099] Trial 9 finished with value: 0.6124941831608247 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:02:03,234] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 17:02:03,750] Trial 11 finished with value: 0.6129332218211435 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.9250608990121825, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1579906038170908, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:02:04,347] Trial 12 finished with value: 0.6382167482744471 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.8206827027986038, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13254323337687263, 'warm_start': False}. Best is trial 12 with value: 0.6382167482744471.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6201550387596899
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 17:02:04,905] Trial 13 finished with value: 0.6155259268666031 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 114, 'oob_score': False, 'max_samples': 0.765021860726683, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12214947430735827, 'warm_start': False}. Best is trial 12 with value: 0.6382167482744471.
Fold 1 C-index: 0.5597609561752988
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.8021276595744681
Fold 4 C-index: 0.6406844106463878
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:02:04,990] Trial 14 finished with value: 0.661274162121231 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 24, 'oob_score': True, 'max_samples': 0.7873021337102564, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11396669613812715, 'warm_start': True}. Best is trial 14 with value: 0.661274162121231.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.687984496124031
Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:02:05,087] Trial 15 finished with value: 0.6815364844139735 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 32, 'oob_score': True, 'max_samples': 0.8219485202814404, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20648604556011108, 'warm_start': True}. Best is trial 15 with value: 0.6815364844139735.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:02:05,142] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 4, 'oob_score': True, 'max_samples': 0.44827686549014745, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.37909912926450273, 'warm_start': True}. Best is trial 15 with value: 0.6815364844139735.
Fold 1 C-index: 0.5697211155378487

Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6759656652360515
[I 2024-04-13 17:02:05,323] Trial 17 finished with value: 0.6895409260222489 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.9817072304699028, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2138706147057923, 'warm_start': True}. Best is trial 17 with value: 0.6895409260222489.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6824034334763949
[I 2024-04-13 17:02:05,533] Trial 18 finished with value: 0.6896987117465925 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 4, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2171200473956938, 'warm_start': True}. Best is trial 18 with value: 0.6896987117465925.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6647286821705426
Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:02:05,735] Trial 19 finished with value: 0.6732099075929641 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 101, 'oob_score': True, 'max_samples': 0.9946585698860816, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.42883326307517006, 'warm_start': True}. Best is trial 18 with value: 0.6896987117465925.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 17:02:05,945] Trial 20 finished with value: 0.6878047367558022 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 106, 'oob_score': True, 'max_samples': 0.9966629158836573, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2545762438232687, 'warm_start': True}. Best is trial 18 with value: 0.6896987117465925.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:02:06,153] Trial 21 finished with value: 0.6895651366973921 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 103, 'oob_score': True, 'max_samples': 0.9639969186184459, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2437877730150368, 'warm_start': True}. Best is trial 18 with value: 0.6896987117465925.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 17:02:06,310] Trial 22 finished with value: 0.6910745957879284 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 72, 'oob_score': True, 'max_samples': 0.8676148902984393, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22395371756309795, 'warm_start': True}. Best is trial 22 with value: 0.6910745957879284.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 17:02:06,587] Trial 23 finished with value: 0.6847876876921578 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 144, 'oob_score': True, 'max_samples': 0.8696699974194458, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27355128284391594, 'warm_start': True}. Best is trial 22 with value: 0.6910745957879284.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 17:02:06,771] Trial 24 finished with value: 0.7028777296239799 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 71, 'oob_score': True, 'max_samples': 0.8666873301180216, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18247394618931245, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 17:02:06,920] Trial 25 finished with value: 0.6862431761238705 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 59, 'oob_score': True, 'max_samples': 0.694473183989708, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17899438960638397, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:02:07,336] Trial 26 finished with value: 0.6908180514604075 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.8603105664937221, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08974480297156207, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:02:07,718] Trial 27 finished with value: 0.690879607810116 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 9, 'n_estimators': 211, 'oob_score': True, 'max_samples': 0.8480603313960683, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07826883989461175, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.6824034334763949
[I 2024-04-13 17:02:08,004] Trial 28 finished with value: 0.6834080957400726 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.5100409687730639, 'max_features': None, 'min_weight_fraction_leaf': 0.08406288592069039, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.703862660944206
[I 2024-04-13 17:02:08,887] Trial 29 finished with value: 0.6995571701409032 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': None, 'min_weight_fraction_leaf': 0.06357526719965571, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6824034334763949
[I 2024-04-13 17:02:09,572] Trial 30 finished with value: 0.6883010388853158 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.6919164029113454, 'max_features': None, 'min_weight_fraction_leaf': 0.18416154592106396, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 17:02:10,406] Trial 31 finished with value: 0.6991838537239718 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 15, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.7425407774406056, 'max_features': None, 'min_weight_fraction_leaf': 0.06755614270828253, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.

Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7510729613733905
[I 2024-04-13 17:02:11,247] Trial 32 finished with value: 0.71347233498625 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 482, 'oob_score': True, 'max_samples': 0.7213418356032232, 'max_features': None, 'min_weight_fraction_leaf': 0.005268431893676387, 'warm_start': True}. Best is trial 32 with value: 0.71347233498625.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7553648068669528
[I 2024-04-13 17:02:12,151] Trial 33 finished with value: 0.7143454416096479 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 497, 'oob_score': True, 'max_samples': 0.7317060450615778, 'max_features': None, 'min_weight_fraction_leaf': 0.00636445969534791, 'warm_start': True}. Best is trial 33 with value: 0.7143454416096479.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7253218884120172
[I 2024-04-13 17:02:13,003] Trial 34 finished with value: 0.7093070296808943 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 499, 'oob_score': True, 'max_samples': 0.6498478551106737, 'max_features': None, 'min_weight_fraction_leaf': 0.0026718173907039787, 'warm_start': True}. Best is trial 33 with value: 0.7143454416096479.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7682403433476395
[I 2024-04-13 17:02:13,788] Trial 35 finished with value: 0.7184092367318795 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.5526064129655602, 'max_features': None, 'min_weight_fraction_leaf': 0.003679699406838821, 'warm_start': True}. Best is trial 35 with value: 0.7184092367318795.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7725321888412017
[I 2024-04-13 17:02:14,599] Trial 36 finished with value: 0.7185651249826217 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 460, 'oob_score': True, 'max_samples': 0.5549344736260913, 'max_features': None, 'min_weight_fraction_leaf': 0.00052334394504433, 'warm_start': True}. Best is trial 36 with value: 0.7185651249826217.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7811158798283262
[I 2024-04-13 17:02:15,387] Trial 37 finished with value: 0.7202887446059156 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.5814176605200219, 'max_features': None, 'min_weight_fraction_leaf': 0.0015943254569678817, 'warm_start': True}. Best is trial 37 with value: 0.7202887446059156.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 17:02:16,054] Trial 38 finished with value: 0.7226139021582083 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.5457909141571613, 'max_features': None, 'min_weight_fraction_leaf': 0.03880080650528065, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7682403433476395
[I 2024-04-13 17:02:16,716] Trial 39 finished with value: 0.7201288515882028 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 364, 'oob_score': True, 'max_samples': 0.5368476716627143, 'max_features': None, 'min_weight_fraction_leaf': 0.038081261852135145, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7553648068669528
[I 2024-04-13 17:02:17,336] Trial 40 finished with value: 0.716032831744537 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 358, 'oob_score': True, 'max_samples': 0.40952146090981767, 'max_features': None, 'min_weight_fraction_leaf': 0.04061975291171849, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7424892703862661
[I 2024-04-13 17:02:18,044] Trial 41 finished with value: 0.712624555224156 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.551415472983159, 'max_features': None, 'min_weight_fraction_leaf': 0.03862016225559219, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7682403433476395
[I 2024-04-13 17:02:18,825] Trial 42 finished with value: 0.7192603005616668 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 443, 'oob_score': True, 'max_samples': 0.5470571389584655, 'max_features': None, 'min_weight_fraction_leaf': 0.040547589426843215, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7424892703862661
[I 2024-04-13 17:02:19,437] Trial 43 finished with value: 0.7117951103449232 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 323, 'oob_score': True, 'max_samples': 0.39343893459960555, 'max_features': None, 'min_weight_fraction_leaf': 0.037197106766703916, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7124463519313304
[I 2024-04-13 17:02:20,187] Trial 44 finished with value: 0.7068156485149109 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 426, 'oob_score': True, 'max_samples': 0.5037446232500291, 'max_features': None, 'min_weight_fraction_leaf': 0.10143753014282131, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7939914163090128
[I 2024-04-13 17:02:20,527] Trial 45 finished with value: 0.7377598119861252 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 383, 'oob_score': False, 'max_samples': 0.6224391250822676, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.051293485724493715, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6180257510729614
[I 2024-04-13 17:02:21,830] Trial 46 finished with value: 0.6313385118971416 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 397, 'oob_score': False, 'max_samples': 0.6010576387757552, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14147922592542847, 'warm_start': False}. Best is trial 45 with value: 0.7377598119861252.

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7682403433476395
[I 2024-04-13 17:02:22,152] Trial 47 finished with value: 0.7280606226030029 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.5032144797599873, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05574216570821283, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:02:23,340] Trial 48 finished with value: 0.6202653504726628 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 335, 'oob_score': False, 'max_samples': 0.6362652522405036, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.058749933389336956, 'warm_start': False}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 17:02:23,684] Trial 49 finished with value: 0.6868378352014417 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 378, 'oob_score': False, 'max_samples': 0.32446222096768196, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09999547019922148, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7510729613733905
[I 2024-04-13 17:02:23,949] Trial 50 finished with value: 0.7215489646378563 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 293, 'oob_score': False, 'max_samples': 0.49077652431354474, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.022511395342881692, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7424892703862661
[I 2024-04-13 17:02:24,193] Trial 51 finished with value: 0.7197673695887684 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.4799716025166624, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023356353978444662, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7424892703862661
[I 2024-04-13 17:02:24,465] Trial 52 finished with value: 0.7119295230662075 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 308, 'oob_score': False, 'max_samples': 0.4430397101533895, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05546859752674148, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 17:02:24,765] Trial 53 finished with value: 0.732052822868799 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.37699411471825023, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03181683271115842, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 17:02:24,990] Trial 54 finished with value: 0.7103906994788739 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 248, 'oob_score': False, 'max_samples': 0.35484298072023907, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02439879662210201, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 17:02:25,274] Trial 55 finished with value: 0.6658561927484276 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 340, 'oob_score': False, 'max_samples': 0.2601632974909122, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11812720872048674, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 17:02:26,205] Trial 56 finished with value: 0.6329785159428548 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 293, 'oob_score': False, 'max_samples': 0.5939163004492594, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07594467100316221, 'warm_start': False}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 17:02:26,556] Trial 57 finished with value: 0.7077567855050916 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 413, 'oob_score': False, 'max_samples': 0.417605389677477, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.022567886933550586, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7124463519313304
[I 2024-04-13 17:02:26,838] Trial 58 finished with value: 0.7084014179141025 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.36734352262627257, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0555217518283616, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:02:27,065] Trial 59 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.4820175814461636, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3544232433893524, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:02:28,160] Trial 60 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.13319246988341354, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1478483729810709, 'warm_start': False}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:02:28,487] Trial 61 finished with value: 0.694601867113741 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 365, 'oob_score': False, 'max_samples': 0.5242841615310458, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04056647502046609, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7725321888412017
[I 2024-04-13 17:02:28,807] Trial 62 finished with value: 0.7295239835677936 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 349, 'oob_score': False, 'max_samples': 0.5989938697881527, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02024218059654313, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7811158798283262
[I 2024-04-13 17:02:29,131] Trial 63 finished with value: 0.7265215450419994 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.5800886465458086, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01592409160248775, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7124463519313304
[I 2024-04-13 17:02:29,455] Trial 64 finished with value: 0.7057723563934031 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 352, 'oob_score': False, 'max_samples': 0.6306540419871571, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10134985371919171, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7982832618025751
[I 2024-04-13 17:02:29,767] Trial 65 finished with value: 0.744372793830748 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.48772656128152925, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02153233090954807, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 17:02:30,105] Trial 66 finished with value: 0.7304619470428545 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 384, 'oob_score': False, 'max_samples': 0.6592301391256026, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07213010958136569, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7725321888412017
[I 2024-04-13 17:02:30,414] Trial 67 finished with value: 0.7303245206618084 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.658332776835216, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0786225535507252, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7854077253218884
[I 2024-04-13 17:02:30,711] Trial 68 finished with value: 0.7350033461568455 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 324, 'oob_score': False, 'max_samples': 0.782951240419168, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07188437817902898, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 17:02:30,975] Trial 69 finished with value: 0.7114104838920958 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.7726300856584892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12841953214236906, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7253218884120172
[I 2024-04-13 17:02:31,287] Trial 70 finished with value: 0.7184151776246746 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.8023071029509282, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.088091229553206, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7682403433476395
[I 2024-04-13 17:02:31,599] Trial 71 finished with value: 0.7295204026438793 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.6597094598339149, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07494346044667374, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7854077253218884
[I 2024-04-13 17:02:31,906] Trial 72 finished with value: 0.7297450090921587 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.6507521187970767, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06813374716595723, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7896995708154506
[I 2024-04-13 17:02:32,208] Trial 73 finished with value: 0.7321026717878453 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.6812499544043293, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07039581398771254, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7467811158798283
[I 2024-04-13 17:02:32,494] Trial 74 finished with value: 0.7171593761887324 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 255, 'oob_score': False, 'max_samples': 0.6687532229099372, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0936898450129986, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7939914163090128
[I 2024-04-13 17:02:32,789] Trial 75 finished with value: 0.7369777367618064 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.706380565345059, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06787811748332337, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7339055793991416
[I 2024-04-13 17:02:33,015] Trial 76 finished with value: 0.7179195356062753 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.7085639969790332, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11414897284280093, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.

Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 17:02:33,302] Trial 77 finished with value: 0.7216353576071407 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.7541985504150174, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07972201398799938, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6763565891472868
Fold 3 C-index: 0.7851063829787234
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.6416309012875536
[I 2024-04-13 17:02:33,542] Trial 78 finished with value: 0.6803721565923366 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.7127152729708048, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.29205538265571684, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:02:33,887] Trial 79 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.6228120642786297, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.41958947955878745, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 17:02:34,858] Trial 80 finished with value: 0.6172257451314318 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6720088970814889, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10386652069615948, 'warm_start': False}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7896995708154506
[I 2024-04-13 17:02:35,157] Trial 81 finished with value: 0.7320120642318223 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 297, 'oob_score': False, 'max_samples': 0.7369273672792999, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06782159792325793, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7811158798283262
[I 2024-04-13 17:02:35,394] Trial 82 finished with value: 0.730229494509787 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.7952406802041782, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05094662429126583, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6738197424892703
[I 2024-04-13 17:02:35,699] Trial 83 finished with value: 0.6953812091002576 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 326, 'oob_score': False, 'max_samples': 0.7368333705955264, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1694628542086393, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7939914163090128
[I 2024-04-13 17:02:35,974] Trial 84 finished with value: 0.7392553812380884 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.8406178075999796, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06813421705074371, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 17:02:36,254] Trial 85 finished with value: 0.7302622700611123 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 293, 'oob_score': False, 'max_samples': 0.8306089170227028, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06578521283153765, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7939914163090128
[I 2024-04-13 17:02:36,509] Trial 86 finished with value: 0.7405771840680274 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 270, 'oob_score': False, 'max_samples': 0.9236490757653891, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04839348178619321, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7939914163090128
[I 2024-04-13 17:02:36,905] Trial 87 finished with value: 0.7440030583377307 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 276, 'oob_score': False, 'max_samples': 0.9426505941387808, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0458571199390998, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:02:37,140] Trial 88 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 270, 'oob_score': False, 'max_samples': 0.9045286625545784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4978507265200673, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 17:02:37,362] Trial 89 finished with value: 0.7387263199915111 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 210, 'oob_score': False, 'max_samples': 0.9605688356486618, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04938248319171276, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7854077253218884
[I 2024-04-13 17:02:37,558] Trial 90 finished with value: 0.7357164327756954 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 191, 'oob_score': False, 'max_samples': 0.9509590620645423, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04691631766264469, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7854077253218884
[I 2024-04-13 17:02:37,747] Trial 91 finished with value: 0.7350355708782796 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 186, 'oob_score': False, 'max_samples': 0.9470927951745665, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04725901659642619, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7756653992395437

Fold 5 C-index: 0.721030042918455
[I 2024-04-13 17:02:37,944] Trial 92 finished with value: 0.7237357652900573 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 199, 'oob_score': False, 'max_samples': 0.9504866379214324, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.053094099292765956, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 17:02:38,141] Trial 93 finished with value: 0.7350688972594961 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 198, 'oob_score': False, 'max_samples': 0.8969936953129258, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04367753331224559, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7017167381974249
[I 2024-04-13 17:02:38,318] Trial 94 finished with value: 0.7024901375378925 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 173, 'oob_score': False, 'max_samples': 0.9151949478759466, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012193068752189541, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7725321888412017
[I 2024-04-13 17:02:38,503] Trial 95 finished with value: 0.7365314105381744 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 180, 'oob_score': False, 'max_samples': 0.8802646337989153, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04987709925035067, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8154506437768241
[I 2024-04-13 17:02:38,701] Trial 96 finished with value: 0.7521018842180724 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.8757809738336038, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.026360410334294093, 'warm_start': True}. Best is trial 96 with value: 0.7521018842180724.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8111587982832618
[I 2024-04-13 17:02:38,880] Trial 97 finished with value: 0.7529735758912052 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 168, 'oob_score': False, 'max_samples': 0.9745319440587786, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02941204455344467, 'warm_start': True}. Best is trial 97 with value: 0.7529735758912052.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.5968992248062015
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:02:39,459] Trial 98 finished with value: 0.6180562707587932 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 163, 'oob_score': False, 'max_samples': 0.9694692468947707, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.027994915902686063, 'warm_start': False}. Best is trial 97 with value: 0.7529735758912052.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8340425531914893

[I 2024-04-13 17:02:39,679] A new study created in memory with name: no-name-984be2b3-fb9a-4b10-8c80-50ddb44fd99e

Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8283261802575107
[I 2024-04-13 17:02:39,676] Trial 99 finished with value: 0.7595658029056476 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.9313711932374781, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011633867937315842, 'warm_start': True}. Best is trial 99 with value: 0.7595658029056476.


* Best trial for C-index:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.7595658029056476], datetime_start=datetime.datetime(2024, 4, 13, 17, 2, 39, 460991), datetime_complete=datetime.datetime(2024, 4, 13, 17, 2, 39, 676408), params={'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.9313711932374781, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011633867937315842, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=99, value=None)


* Best Score for C-index:
 0.7595658029056476

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24174212688781635
Fold 2 IBS: 0.22837556031637174
Fold 3 IBS: 0.21925199037851104
Fold 4 IBS: 0.23387858646882115
Fold 5 IBS: 0.21192783289424028
[I 2024-04-13 17:02:40,943] Trial 0 finished with value: 0.2270352193891521 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.2270352193891521.
Fold 1 IBS: 0.24144275735387236
Fold 2 IBS: 0.22079642625239382
Fold 3 IBS: 0.2195858644892306
Fold 4 IBS: 0.2328787523585072
Fold 5 IBS: 0.21468068071692512
[I 2024-04-13 17:02:41,276] Trial 1 finished with value: 0.2258768962341858 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.2258768962341858.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-13 17:02:41,512] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.2258768962341858.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-13 17:02:42,424] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.2258768962341858.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-13 17:02:43,168] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.2258768962341858.
Fold 1 IBS: 0.2492022721662945
Fold 2 IBS: 0.2248156215657013
Fold 3 IBS: 0.21773271752809326
Fold 4 IBS: 0.2287247859937131
Fold 5 IBS: 0.21591178374347977
[I 2024-04-13 17:02:44,231] Trial 5 finished with value: 0.22727743619945642 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.2258768962341858.
Fold 1 IBS: 0.24345429173373118
Fold 2 IBS: 0.22177590887724122
Fold 3 IBS: 0.21900257819310728
Fold 4 IBS: 0.2300708478315454
Fold 5 IBS: 0.20857620825948778
[I 2024-04-13 17:02:45,270] Trial 6 finished with value: 0.2245759669790226 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24553997148168735
Fold 2 IBS: 0.23209632831596824
Fold 3 IBS: 0.22914599492354287
Fold 4 IBS: 0.24151189951584615
Fold 5 IBS: 0.22920646238220327
[I 2024-04-13 17:02:46,438] Trial 7 finished with value: 0.23550013132384956 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-13 17:02:48,294] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.23795187102456028
Fold 2 IBS: 0.22068804877472178
Fold 3 IBS: 0.21736841990005548
Fold 4 IBS: 0.23483534153305224
Fold 5 IBS: 0.2166813748058101
[I 2024-04-13 17:02:48,679] Trial 9 finished with value: 0.22550501120764 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24645571521465787
Fold 2 IBS: 0.23214351218858914
Fold 3 IBS: 0.23029990468218745
Fold 4 IBS: 0.24091247880712954
Fold 5 IBS: 0.22969387017589088
[I 2024-04-13 17:02:50,801] Trial 10 finished with value: 0.235901096213691 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3251129986182119}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.23821763800269524
Fold 2 IBS: 0.2206989405701499
Fold 3 IBS: 0.2183298733900689
Fold 4 IBS: 0.23435319377188557
Fold 5 IBS: 0.21624993612827711
[I 2024-04-13 17:02:51,294] Trial 11 finished with value: 0.22556991637261534 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 133, 'oob_score': False, 'max_samples': 0.9904090680670613, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17706129541113583}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.2390269025799132
Fold 2 IBS: 0.22093723784955296
Fold 3 IBS: 0.21614331470726378
Fold 4 IBS: 0.23568779668901688
Fold 5 IBS: 0.21706838561267935
[I 2024-04-13 17:02:51,844] Trial 12 finished with value: 0.2257727274876852 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.9777827337837477, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3324053831839262}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.28429571858174646
Fold 2 IBS: 0.291976143238516
Fold 3 IBS: 0.25971605676138104
Fold 4 IBS: 0.2911448075888225
Fold 5 IBS: 0.2421484554746106
[I 2024-04-13 17:02:52,002] Trial 13 finished with value: 0.27385623632901535 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.8358240113413322, 'max_features': None, 'min_weight_fraction_leaf': 0.0035697594234744834}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24072003207164025
Fold 2 IBS: 0.22931923287626255
Fold 3 IBS: 0.2206971081552678
Fold 4 IBS: 0.23441816780813163
Fold 5 IBS: 0.21155006913932226
[I 2024-04-13 17:02:53,056] Trial 14 finished with value: 0.22734092201012487 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.8213409911746509, 'max_features': None, 'min_weight_fraction_leaf': 0.2466431683648488}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24011905153998128
Fold 2 IBS: 0.22518763981988726
Fold 3 IBS: 0.22165869139663433
Fold 4 IBS: 0.2375480054269681
Fold 5 IBS: 0.21939984365433624
[I 2024-04-13 17:02:53,784] Trial 15 finished with value: 0.22878264636756143 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 15, 'n_estimators': 187, 'oob_score': False, 'max_samples': 0.8537410313073572, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3655886525927784}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.2392961564663636
Fold 2 IBS: 0.2209141876561904

Fold 3 IBS: 0.2197843622003885
Fold 4 IBS: 0.23449432140937404
Fold 5 IBS: 0.21510746016776658
[I 2024-04-13 17:02:54,195] Trial 16 finished with value: 0.2259192975800166 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 20, 'max_depth': 9, 'n_estimators': 101, 'oob_score': False, 'max_samples': 0.8978246151361277, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12075256052520705}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.23788710888494208
Fold 2 IBS: 0.22243680052846054
Fold 3 IBS: 0.21523716494988468
Fold 4 IBS: 0.2354635803357212
Fold 5 IBS: 0.21631738782405596
[I 2024-04-13 17:02:55,433] Trial 17 finished with value: 0.2254684085046129 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.741685896826822, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27799606575272795}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.23869855628325998
Fold 2 IBS: 0.22242767695758497
Fold 3 IBS: 0.2157055296703147
Fold 4 IBS: 0.23576281546540628
Fold 5 IBS: 0.2157448032649353
[I 2024-04-13 17:02:56,869] Trial 18 finished with value: 0.22566787632830027 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.7546903089061138, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2742435840937791}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24632840137946754
Fold 2 IBS: 0.23215399476522983
Fold 3 IBS: 0.22955396254585125
Fold 4 IBS: 0.24150521854716006
Fold 5 IBS: 0.23021366118499692
[I 2024-04-13 17:02:58,619] Trial 19 finished with value: 0.23595104768454114 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.6099910227680899, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3749437552159898}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24666575342744318
Fold 2 IBS: 0.23213825794648577
Fold 3 IBS: 0.2295175914696922
Fold 4 IBS: 0.24160807083199934
Fold 5 IBS: 0.23035609618327466
[I 2024-04-13 17:02:59,479] Trial 20 finished with value: 0.236057153971779 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.7619585591959509, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4532041395885572}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24238904514874957
Fold 2 IBS: 0.23445593643522006
Fold 3 IBS: 0.22631622026231327
Fold 4 IBS: 0.24260320628868504
Fold 5 IBS: 0.21291028085045807
[I 2024-04-13 17:03:01,031] Trial 21 finished with value: 0.2317349377970852 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 398, 'oob_score': False, 'max_samples': 0.9187552595429349, 'max_features': None, 'min_weight_fraction_leaf': 0.21197947565921343}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.23815659783121731
Fold 2 IBS: 0.22207749230002619
Fold 3 IBS: 0.21752970637890848
Fold 4 IBS: 0.23583123734864406
Fold 5 IBS: 0.2164629406223946
[I 2024-04-13 17:03:02,114] Trial 22 finished with value: 0.22601159489623815 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 295, 'oob_score': False, 'max_samples': 0.8060035003385533, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3067334006568516}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.2365247351332946
Fold 2 IBS: 0.22050557618201566
Fold 3 IBS: 0.21512045407281427
Fold 4 IBS: 0.2337779971213356
Fold 5 IBS: 0.2161481181306821
[I 2024-04-13 17:03:03,055] Trial 23 finished with value: 0.22441537612802845 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9051753762122661, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.23816787952025506}. Best is trial 23 with value: 0.22441537612802845.
Fold 1 IBS: 0.23561339472694814
Fold 2 IBS: 0.22133586039163214
Fold 3 IBS: 0.21447786302348743
Fold 4 IBS: 0.23400436966113364
Fold 5 IBS: 0.21612644313403398
[I 2024-04-13 17:03:03,978] Trial 24 finished with value: 0.22431158618744704 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 243, 'oob_score': False, 'max_samples': 0.9299177072569818, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2520392540669227}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.23734053455594875
Fold 2 IBS: 0.22238136978606352
Fold 3 IBS: 0.217109879798544
Fold 4 IBS: 0.23602786050229949
Fold 5 IBS: 0.21660878345157603
[I 2024-04-13 17:03:04,842] Trial 25 finished with value: 0.22589368561888637 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 239, 'oob_score': False, 'max_samples': 0.9932624357183849, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.36562561378195096}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.23719982212029692
Fold 2 IBS: 0.22044726520696664
Fold 3 IBS: 0.21486784959214336
Fold 4 IBS: 0.23273159700220875
Fold 5 IBS: 0.21646579110319986
[I 2024-04-13 17:03:05,680] Trial 26 finished with value: 0.2243424650049631 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 174, 'oob_score': True, 'max_samples': 0.9058902641802971, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.23696300699805542}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.2437963229547316
Fold 2 IBS: 0.22276653565660226
Fold 3 IBS: 0.21454006940897422
Fold 4 IBS: 0.23541573435802962
Fold 5 IBS: 0.2144905314321996
[I 2024-04-13 17:03:06,506] Trial 27 finished with value: 0.22620183876210748 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 164, 'oob_score': True, 'max_samples': 0.9377046402810433, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14696574200200033}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.2466592970927268
Fold 2 IBS: 0.2322006384871181
Fold 3 IBS: 0.2298545910321478
Fold 4 IBS: 0.24133288058090815
Fold 5 IBS: 0.230048552619906
[I 2024-04-13 17:03:07,530] Trial 28 finished with value: 0.23601919196256138 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 227, 'oob_score': True, 'max_samples': 0.26154064534881144, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22590607990715106}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.23758412825426514
Fold 2 IBS: 0.22297538914957787
Fold 3 IBS: 0.21638228130409853
Fold 4 IBS: 0.2349760943144391
Fold 5 IBS: 0.21663197350890054
[I 2024-04-13 17:03:08,492] Trial 29 finished with value: 0.22570997330625625 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 191, 'oob_score': True, 'max_samples': 0.6859458752534023, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24558091355365722}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.24245047612298046
Fold 2 IBS: 0.22271929119513714
Fold 3 IBS: 0.2181117133635492
Fold 4 IBS: 0.23245730057613723
Fold 5 IBS: 0.2186082238373671
[I 2024-04-13 17:03:09,272] Trial 30 finished with value: 0.22686940101903424 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 132, 'oob_score': True, 'max_samples': 0.4388997479034245, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11470501817805681}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.2399850896709501
Fold 2 IBS: 0.23006555677291446
Fold 3 IBS: 0.2217715118746403
Fold 4 IBS: 0.23484827509541154
Fold 5 IBS: 0.21133378408198586
[I 2024-04-13 17:03:10,358] Trial 31 finished with value: 0.22760084349918044 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 260, 'oob_score': False, 'max_samples': 0.8683795773714846, 'max_features': None, 'min_weight_fraction_leaf': 0.25607534090715667}. Best is trial 24 with value: 0.22431158618744704.

Fold 1 IBS: 0.2370347091364531
Fold 2 IBS: 0.21865616933268361
Fold 3 IBS: 0.2136904590169095
Fold 4 IBS: 0.2330616724900941
Fold 5 IBS: 0.21522492222501335
[I 2024-04-13 17:03:11,783] Trial 32 finished with value: 0.22353358644023075 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.8040571874379057, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18786523282060735}. Best is trial 32 with value: 0.22353358644023075.
Fold 1 IBS: 0.2369596498960518
Fold 2 IBS: 0.21919381104819285
Fold 3 IBS: 0.21367435784125732
Fold 4 IBS: 0.2331924481484345
Fold 5 IBS: 0.21510595787220624
[I 2024-04-13 17:03:13,301] Trial 33 finished with value: 0.22362524496122854 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 309, 'oob_score': True, 'max_samples': 0.7910445247744765, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18809103319338225}. Best is trial 32 with value: 0.22353358644023075.
Fold 1 IBS: 0.23672523561114803
Fold 2 IBS: 0.21905100495993393
Fold 3 IBS: 0.21428207375878827
Fold 4 IBS: 0.23334334259045397
Fold 5 IBS: 0.21462924819781068
[I 2024-04-13 17:03:15,075] Trial 34 finished with value: 0.22360618102362695 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 377, 'oob_score': True, 'max_samples': 0.7912137176760294, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18558593432482404}. Best is trial 32 with value: 0.22353358644023075.
Fold 1 IBS: 0.23686591677724925
Fold 2 IBS: 0.21880215905099826
Fold 3 IBS: 0.21348650762243437
Fold 4 IBS: 0.23350536986447867
Fold 5 IBS: 0.21453876729002655
[I 2024-04-13 17:03:16,755] Trial 35 finished with value: 0.22343974412103745 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 370, 'oob_score': True, 'max_samples': 0.7882412474357445, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18410738872353652}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.23712660831229618
Fold 2 IBS: 0.21936207956912226
Fold 3 IBS: 0.21377037949196134
Fold 4 IBS: 0.2353853780161964
Fold 5 IBS: 0.21604409087841447
[I 2024-04-13 17:03:18,493] Trial 36 finished with value: 0.22433770725359814 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 389, 'oob_score': True, 'max_samples': 0.6319734188794576, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18057866445401774}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.23985764041755697
Fold 2 IBS: 0.2203910722203549
Fold 3 IBS: 0.21615232998036504
Fold 4 IBS: 0.2324242099038112
Fold 5 IBS: 0.21377035023694235
[I 2024-04-13 17:03:20,371] Trial 37 finished with value: 0.2245191205518061 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 372, 'oob_score': True, 'max_samples': 0.7747419667382262, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14511659298967997}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.24676336973074187
Fold 2 IBS: 0.22400017565703165
Fold 3 IBS: 0.22050607510658007
Fold 4 IBS: 0.23160175255798512
Fold 5 IBS: 0.21460046142043543
[I 2024-04-13 17:03:22,849] Trial 38 finished with value: 0.22749436689455482 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 474, 'oob_score': True, 'max_samples': 0.708969650791409, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07841760859950192}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.24122790903542682
Fold 2 IBS: 0.22126564420108252
Fold 3 IBS: 0.21500814519153294
Fold 4 IBS: 0.23088715452854772
Fold 5 IBS: 0.21505297571279228
[I 2024-04-13 17:03:25,112] Trial 39 finished with value: 0.22468836573387643 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 436, 'oob_score': True, 'max_samples': 0.5567914809570165, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10107929772200888}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.2512512194499984
Fold 2 IBS: 0.23384119436207942
Fold 3 IBS: 0.21986209620007618
Fold 4 IBS: 0.2324052704281404
Fold 5 IBS: 0.21614780773365797
[I 2024-04-13 17:03:26,621] Trial 40 finished with value: 0.23070151763479047 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 313, 'oob_score': True, 'max_samples': 0.6360911606111228, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04797053004225782}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.2364825751273401
Fold 2 IBS: 0.21926467455871407
Fold 3 IBS: 0.21319128346432453
Fold 4 IBS: 0.2332830275103288
Fold 5 IBS: 0.21513344099462875
[I 2024-04-13 17:03:28,342] Trial 41 finished with value: 0.2234710003310673 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.7910648434560368, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.19044184409775022}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.23657216849211188
Fold 2 IBS: 0.21805180183232972
Fold 3 IBS: 0.2134098718971707
Fold 4 IBS: 0.2326760577782485
Fold 5 IBS: 0.21489772695679377
[I 2024-04-13 17:03:30,633] Trial 42 finished with value: 0.22312152539133093 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 363, 'oob_score': True, 'max_samples': 0.8069030132321051, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.19162190380727356}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23945616928698815
Fold 2 IBS: 0.22072840117287257
Fold 3 IBS: 0.2138390608089632
Fold 4 IBS: 0.23224317279049148
Fold 5 IBS: 0.21446628607960228
[I 2024-04-13 17:03:32,330] Trial 43 finished with value: 0.22414661802778352 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 354, 'oob_score': True, 'max_samples': 0.7256599857619218, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1528479024949021}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23649706067068324
Fold 2 IBS: 0.21941209208908452
Fold 3 IBS: 0.21295847947231347
Fold 4 IBS: 0.23594218559775645
Fold 5 IBS: 0.21615807717067265
[I 2024-04-13 17:03:34,323] Trial 44 finished with value: 0.2241935790001021 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 424, 'oob_score': True, 'max_samples': 0.6735879050942102, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2020053940682765}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23693251190244155
Fold 2 IBS: 0.2213288517310521
Fold 3 IBS: 0.21494689188039331
Fold 4 IBS: 0.23415254475273511
Fold 5 IBS: 0.21682890772894134
[I 2024-04-13 17:03:36,149] Trial 45 finished with value: 0.2248379415991127 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.5054965069088588, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16858288066901586}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.24197332198213933
Fold 2 IBS: 0.22046487286415592
Fold 3 IBS: 0.21586457052819402
Fold 4 IBS: 0.23223394094427516
Fold 5 IBS: 0.2132292438608055
[I 2024-04-13 17:03:38,373] Trial 46 finished with value: 0.224753190035914 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 454, 'oob_score': True, 'max_samples': 0.8105930895493332, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12622439487788628}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23556816618505033
Fold 2 IBS: 0.21943285786800518
Fold 3 IBS: 0.21472972925457443
Fold 4 IBS: 0.23233131562389348

Fold 5 IBS: 0.21452585999296125
[I 2024-04-13 17:03:40,060] Trial 47 finished with value: 0.22331758578489697 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 332, 'oob_score': True, 'max_samples': 0.8648447148686852, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19908924320632904}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23571677073756844
Fold 2 IBS: 0.21862106487993588
Fold 3 IBS: 0.21456356649548577
Fold 4 IBS: 0.23300957311771886
Fold 5 IBS: 0.2147097776323396
[I 2024-04-13 17:03:41,959] Trial 48 finished with value: 0.2233241505726097 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 339, 'oob_score': True, 'max_samples': 0.85048001681846, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21469064698337334}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23559067856645097
Fold 2 IBS: 0.21873875911929633
Fold 3 IBS: 0.21444282499967143
Fold 4 IBS: 0.2331433841346366
Fold 5 IBS: 0.21521373828133133
[I 2024-04-13 17:03:44,090] Trial 49 finished with value: 0.22342587702027733 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 349, 'oob_score': True, 'max_samples': 0.8608777099735355, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21409963196930723}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2354720485014348
Fold 2 IBS: 0.21908483698682585
Fold 3 IBS: 0.21419738362473992
Fold 4 IBS: 0.23286928627582323
Fold 5 IBS: 0.21554847437687882
[I 2024-04-13 17:03:46,190] Trial 50 finished with value: 0.2234344059531405 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 331, 'oob_score': True, 'max_samples': 0.8624774255144273, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2109347249153205}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23627193006876482
Fold 2 IBS: 0.21852946709881008
Fold 3 IBS: 0.2148469504923258
Fold 4 IBS: 0.23351001052284076
Fold 5 IBS: 0.21507169524249345
[I 2024-04-13 17:03:48,288] Trial 51 finished with value: 0.22364601068504694 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 339, 'oob_score': True, 'max_samples': 0.8695358762760744, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21582255489884755}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23548356533028544
Fold 2 IBS: 0.218725010588746
Fold 3 IBS: 0.21451762386354145
Fold 4 IBS: 0.23286275629435157
Fold 5 IBS: 0.21475783585840155
[I 2024-04-13 17:03:49,983] Trial 52 finished with value: 0.22326935838706521 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 348, 'oob_score': True, 'max_samples': 0.8462587816411291, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21547666896690265}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23613634094238448
Fold 2 IBS: 0.21848749437898204
Fold 3 IBS: 0.21292409617818456
Fold 4 IBS: 0.23567681901169757
Fold 5 IBS: 0.21518372968081823
[I 2024-04-13 17:03:51,705] Trial 53 finished with value: 0.22368169603841337 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.9631487042826314, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2887922839794046}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23665761244588207
Fold 2 IBS: 0.22117302572817424
Fold 3 IBS: 0.21340438192039934
Fold 4 IBS: 0.2344340217943337
Fold 5 IBS: 0.21637287825154097
[I 2024-04-13 17:03:53,135] Trial 54 finished with value: 0.2244083840280661 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 286, 'oob_score': True, 'max_samples': 0.8464063284466049, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2697118114658599}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23609369849161851
Fold 2 IBS: 0.22007777901922662
Fold 3 IBS: 0.215855484457008
Fold 4 IBS: 0.23438134550311407
Fold 5 IBS: 0.21573946841596092
[I 2024-04-13 17:03:54,614] Trial 55 finished with value: 0.2244295551773856 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 271, 'oob_score': True, 'max_samples': 0.879833085890255, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21383320692792412}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.24222956946122723
Fold 2 IBS: 0.22137697302616127
Fold 3 IBS: 0.21626516807485707
Fold 4 IBS: 0.23437496001734787
Fold 5 IBS: 0.21368603534260622
[I 2024-04-13 17:03:56,635] Trial 56 finished with value: 0.22558654118443994 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 354, 'oob_score': True, 'max_samples': 0.9448123317517924, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15922434069943384}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23566710868723995
Fold 2 IBS: 0.21815687589456226
Fold 3 IBS: 0.21374824567704823
Fold 4 IBS: 0.23516414343276787
Fold 5 IBS: 0.2155717168434672
[I 2024-04-13 17:03:58,699] Trial 57 finished with value: 0.2236616181070171 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 409, 'oob_score': True, 'max_samples': 0.8302783773614499, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2212917621096384}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23597677041833393
Fold 2 IBS: 0.21966309894338662
Fold 3 IBS: 0.2147789356113197
Fold 4 IBS: 0.2346364915456495
Fold 5 IBS: 0.21544052695772373
[I 2024-04-13 17:04:00,290] Trial 58 finished with value: 0.22409916469528265 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.8822727605099482, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.26404114905990445}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23687443879472495
Fold 2 IBS: 0.2196115034471744
Fold 3 IBS: 0.2144316176908922
Fold 4 IBS: 0.23394500800067253
Fold 5 IBS: 0.21552843402248026
[I 2024-04-13 17:04:01,914] Trial 59 finished with value: 0.22407820039118884 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 299, 'oob_score': True, 'max_samples': 0.9619605093804899, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3043109475953167}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23648824629467255
Fold 2 IBS: 0.22035324074970292
Fold 3 IBS: 0.21311491690305986
Fold 4 IBS: 0.23558874827891282
Fold 5 IBS: 0.2147764365302421
[I 2024-04-13 17:04:03,876] Trial 60 finished with value: 0.22406431775131805 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 389, 'oob_score': True, 'max_samples': 0.7432259190596778, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23401215359777172}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23534762568590942
Fold 2 IBS: 0.21918131507767896
Fold 3 IBS: 0.21348843313052338
Fold 4 IBS: 0.2345139591305208
Fold 5 IBS: 0.2147806291992252
[I 2024-04-13 17:04:05,629] Trial 61 finished with value: 0.22346239244477153 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 356, 'oob_score': True, 'max_samples': 0.8400984283316736, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20744391800378348}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23683459238973079
Fold 2 IBS: 0.2190589139081263
Fold 3 IBS: 0.21251768095507126
Fold 4 IBS: 0.23333473964097387
Fold 5 IBS: 0.21540218190074592
[I 2024-04-13 17:04:07,642] Trial 62 finished with value: 0.22342962175892964 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 413, 'oob_score': True, 'max_samples': 0.7146112288426298, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1673008720099634}. Best is trial 42 with value: 0.22312152539133093.

Fold 1 IBS: 0.24251844789708726
Fold 2 IBS: 0.2210411248095999
Fold 3 IBS: 0.2174884582534811
Fold 4 IBS: 0.23327796476633547
Fold 5 IBS: 0.21325865662478627
[I 2024-04-13 17:04:09,770] Trial 63 finished with value: 0.225516930470258 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 440, 'oob_score': True, 'max_samples': 0.8434390256503708, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13262761517233745}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.24154578994370174
Fold 2 IBS: 0.22210454661611326
Fold 3 IBS: 0.21614753754341642
Fold 4 IBS: 0.23303912664616094
Fold 5 IBS: 0.21337979688122055
[I 2024-04-13 17:04:11,926] Trial 64 finished with value: 0.2252433595261226 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 421, 'oob_score': True, 'max_samples': 0.9071936553420485, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1668837494665743}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23578396984973268
Fold 2 IBS: 0.21982751985915058
Fold 3 IBS: 0.2127907655486023
Fold 4 IBS: 0.23611774962723142
Fold 5 IBS: 0.21593645923354832
[I 2024-04-13 17:04:13,869] Trial 65 finished with value: 0.22409129282365306 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 407, 'oob_score': True, 'max_samples': 0.7091534179771193, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22490980526604287}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2465390297659536
Fold 2 IBS: 0.23217413632394113
Fold 3 IBS: 0.22957331555813507
Fold 4 IBS: 0.24145493115068345
Fold 5 IBS: 0.23026954015536694
[I 2024-04-13 17:04:15,352] Trial 66 finished with value: 0.236002190590816 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 320, 'oob_score': True, 'max_samples': 0.7513910467079336, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4904781810386246}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2360357412254428
Fold 2 IBS: 0.2187126930774909
Fold 3 IBS: 0.21351408679377545
Fold 4 IBS: 0.2329566459809213
Fold 5 IBS: 0.2152135771982376
[I 2024-04-13 17:04:16,983] Trial 67 finished with value: 0.22328654885517357 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 342, 'oob_score': True, 'max_samples': 0.8253291108475478, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20313220519951403}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.24065133829818755
Fold 2 IBS: 0.22649622349010287
Fold 3 IBS: 0.22286450107823114
Fold 4 IBS: 0.23931283464708142
Fold 5 IBS: 0.22158590387862978
[I 2024-04-13 17:04:18,799] Trial 68 finished with value: 0.23018216027844657 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.23482143077480938, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10469307170592539}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23857197966111204
Fold 2 IBS: 0.21969954436291245
Fold 3 IBS: 0.21312219615211478
Fold 4 IBS: 0.23141791617263682
Fold 5 IBS: 0.21602934314344477
[I 2024-04-13 17:04:20,654] Trial 69 finished with value: 0.22376819589844418 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 347, 'oob_score': True, 'max_samples': 0.5927472377062504, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1379977256731293}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23885528352241767
Fold 2 IBS: 0.21953869680569335
Fold 3 IBS: 0.2148775976903492
Fold 4 IBS: 0.23345908200176593
Fold 5 IBS: 0.21438276633195175
[I 2024-04-13 17:04:23,317] Trial 70 finished with value: 0.22422268527043557 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 470, 'oob_score': True, 'max_samples': 0.8292047043164549, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16367930540263453}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23680915897690014
Fold 2 IBS: 0.22008714306330915
Fold 3 IBS: 0.21622674732020958
Fold 4 IBS: 0.23269848004964874
Fold 5 IBS: 0.21476478864691187
[I 2024-04-13 17:04:25,175] Trial 71 finished with value: 0.2241172636113959 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.886809939325558, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2018241978642696}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23602132741932083
Fold 2 IBS: 0.21929352463181243
Fold 3 IBS: 0.21479463231545
Fold 4 IBS: 0.23487972856446335
Fold 5 IBS: 0.21569292472186188
[I 2024-04-13 17:04:26,656] Trial 72 finished with value: 0.22413642753058172 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.8633059632266107, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24563240525389668}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23756080896385787
Fold 2 IBS: 0.2198709901179539
Fold 3 IBS: 0.21607716703164753
Fold 4 IBS: 0.23444739602719725
Fold 5 IBS: 0.21515728419865568
[I 2024-04-13 17:04:28,037] Trial 73 finished with value: 0.22462272926786242 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.9365960110126715, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20402438062021583}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2439734659304091
Fold 2 IBS: 0.2178765152434605
Fold 3 IBS: 0.21637058574280912
Fold 4 IBS: 0.23265790035339595
Fold 5 IBS: 0.21509688786020262
[I 2024-04-13 17:04:28,507] Trial 74 finished with value: 0.22519507102605546 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 68, 'oob_score': True, 'max_samples': 0.7690209890280151, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17482878175722952}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.24167367619307714
Fold 2 IBS: 0.2321091666317781
Fold 3 IBS: 0.2254096772934718
Fold 4 IBS: 0.2412558098040841
Fold 5 IBS: 0.2112087474135227
[I 2024-04-13 17:04:30,597] Trial 75 finished with value: 0.23033141546718677 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 383, 'oob_score': True, 'max_samples': 0.9185869784489429, 'max_features': None, 'min_weight_fraction_leaf': 0.22786656653980156}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23643423760441268
Fold 2 IBS: 0.2189682190598761
Fold 3 IBS: 0.21316331155747148
Fold 4 IBS: 0.23551095785015766
Fold 5 IBS: 0.21530716431950858
[I 2024-04-13 17:04:32,392] Trial 76 finished with value: 0.22387677807828527 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 360, 'oob_score': True, 'max_samples': 0.8145758924117495, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.25894296074467726}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23649835615235615
Fold 2 IBS: 0.2202998367772717
Fold 3 IBS: 0.215849186186392
Fold 4 IBS: 0.23189510546241013
Fold 5 IBS: 0.21421820558824664
[I 2024-04-13 17:04:34,029] Trial 77 finished with value: 0.22375213803333532 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 325, 'oob_score': True, 'max_samples': 0.8574304723771203, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.19219578753985594}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23543043862820737
Fold 2 IBS: 0.21941172237656087
Fold 3 IBS: 0.21510969675644945
Fold 4 IBS: 0.23449274572109305

Fold 5 IBS: 0.21423498837277127
[I 2024-04-13 17:04:35,975] Trial 78 finished with value: 0.22373591837101642 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 346, 'oob_score': True, 'max_samples': 0.8854068847594949, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23765891161800223}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23570867974207424
Fold 2 IBS: 0.22060193373952594
Fold 3 IBS: 0.2144464193518562
Fold 4 IBS: 0.23476296957407278
Fold 5 IBS: 0.21578644913062256
[I 2024-04-13 17:04:37,409] Trial 79 finished with value: 0.22426129030763034 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.9991782770608287, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2796131771286568}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.25860616056552466
Fold 2 IBS: 0.247606837719613
Fold 3 IBS: 0.2319726248414201
Fold 4 IBS: 0.21372331996096558
Fold 5 IBS: 0.22292533572909917
[I 2024-04-13 17:04:37,504] Trial 80 finished with value: 0.23496685576332452 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 2, 'oob_score': True, 'max_samples': 0.7266137530392617, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15138133095624934}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2424425528776856
Fold 2 IBS: 0.23603790633519647
Fold 3 IBS: 0.22385508599506115
Fold 4 IBS: 0.2408498337269256
Fold 5 IBS: 0.21319653378514064
[I 2024-04-13 17:04:39,438] Trial 81 finished with value: 0.2312763825440019 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 367, 'oob_score': True, 'max_samples': 0.7784763388289013, 'max_features': None, 'min_weight_fraction_leaf': 0.1797361326491144}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2359333065359587
Fold 2 IBS: 0.2177740535675139
Fold 3 IBS: 0.21340554055264466
Fold 4 IBS: 0.23325957841825662
Fold 5 IBS: 0.21578220466559705
[I 2024-04-13 17:04:41,421] Trial 82 finished with value: 0.22323093674799416 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 415, 'oob_score': True, 'max_samples': 0.8175962542874978, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19766586115305992}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23601034698653564
Fold 2 IBS: 0.21748305842766855
Fold 3 IBS: 0.21304430322253315
Fold 4 IBS: 0.23308271498728148
Fold 5 IBS: 0.21565089781052826
[I 2024-04-13 17:04:43,509] Trial 83 finished with value: 0.22305426428690941 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 414, 'oob_score': True, 'max_samples': 0.8141450872491632, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1970991647731129}. Best is trial 83 with value: 0.22305426428690941.
Fold 1 IBS: 0.23612684478177634
Fold 2 IBS: 0.21748810056111387
Fold 3 IBS: 0.21296826834994675
Fold 4 IBS: 0.23300146461188564
Fold 5 IBS: 0.21553229839714166
[I 2024-04-13 17:04:45,709] Trial 84 finished with value: 0.22302339534037285 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.8096737689830545, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19628098798162147}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23647255696644645
Fold 2 IBS: 0.21812077297319524
Fold 3 IBS: 0.21276820303695784
Fold 4 IBS: 0.23345302877262153
Fold 5 IBS: 0.2159040770659359
[I 2024-04-13 17:04:48,234] Trial 85 finished with value: 0.22334372776303138 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 459, 'oob_score': True, 'max_samples': 0.811352649827629, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20105461655472903}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23613729090343752
Fold 2 IBS: 0.2179346998491405
Fold 3 IBS: 0.2129644243629255
Fold 4 IBS: 0.23394201782485338
Fold 5 IBS: 0.21572915695093184
[I 2024-04-13 17:04:51,124] Trial 86 finished with value: 0.22334151797825771 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 488, 'oob_score': True, 'max_samples': 0.8015324404528672, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19820833818823205}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23651644370953373
Fold 2 IBS: 0.2183132341743879
Fold 3 IBS: 0.2134129991132886
Fold 4 IBS: 0.2346203263183014
Fold 5 IBS: 0.21491522745649771
[I 2024-04-13 17:04:53,884] Trial 87 finished with value: 0.22355564615440188 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 496, 'oob_score': True, 'max_samples': 0.7613285087560672, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19051696011006752}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23671103316078027
Fold 2 IBS: 0.22284517298984777
Fold 3 IBS: 0.21466085140706787
Fold 4 IBS: 0.23693276256284146
Fold 5 IBS: 0.21629400773876842
[I 2024-04-13 17:04:56,779] Trial 88 finished with value: 0.22548876557186115 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 474, 'oob_score': True, 'max_samples': 0.6860019496673433, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2438001190871077}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.2463868285065531
Fold 2 IBS: 0.23214573353925852
Fold 3 IBS: 0.22952063623082164
Fold 4 IBS: 0.24149813996015929
Fold 5 IBS: 0.23026213720056213
[I 2024-04-13 17:04:59,712] Trial 89 finished with value: 0.23596269508747097 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 485, 'oob_score': True, 'max_samples': 0.8149680975480039, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.41549217555832835}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23557602986231588
Fold 2 IBS: 0.21894288091688477
Fold 3 IBS: 0.21263728838237342
Fold 4 IBS: 0.23680776315197954
Fold 5 IBS: 0.2158104954061969
[I 2024-04-13 17:05:02,433] Trial 90 finished with value: 0.22395489154395012 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 441, 'oob_score': True, 'max_samples': 0.7816843286867342, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.226633406438448}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.2361593385752497
Fold 2 IBS: 0.2180829122586363
Fold 3 IBS: 0.21264954315727935
Fold 4 IBS: 0.2333718311494117
Fold 5 IBS: 0.21516322407038282
[I 2024-04-13 17:05:05,058] Trial 91 finished with value: 0.22308536984219202 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 456, 'oob_score': True, 'max_samples': 0.8383779120700723, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19824639992469062}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23813486363436617
Fold 2 IBS: 0.21841882418390748
Fold 3 IBS: 0.21525721526950065
Fold 4 IBS: 0.23385192469312954
Fold 5 IBS: 0.2144863105931356
[I 2024-04-13 17:05:07,571] Trial 92 finished with value: 0.2240298276748079 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 448, 'oob_score': True, 'max_samples': 0.8371843344422779, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1793365451149834}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23656447575349918
Fold 2 IBS: 0.21820038163639136
Fold 3 IBS: 0.21281675876104583
Fold 4 IBS: 0.23387434885160996
Fold 5 IBS: 0.2155591110547076
[I 2024-04-13 17:05:10,542] Trial 93 finished with value: 0.22340301521145078 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 464, 'oob_score': True, 'max_samples': 0.7957196161977251, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19569167078239133}. Best is trial 84 with value: 0.22302339534037285.

Fold 1 IBS: 0.2364707434109151
Fold 2 IBS: 0.21910149125141531
Fold 3 IBS: 0.21420284080337593
Fold 4 IBS: 0.23438012728527638
Fold 5 IBS: 0.21479897289302796
[I 2024-04-13 17:05:13,287] Trial 94 finished with value: 0.22379083512880213 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 430, 'oob_score': True, 'max_samples': 0.892312681224388, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2167154554420358}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23950861114017571
Fold 2 IBS: 0.22006606579763324
Fold 3 IBS: 0.2159169717512573
Fold 4 IBS: 0.2336883258166932
Fold 5 IBS: 0.21371153072549798
[I 2024-04-13 17:05:16,034] Trial 95 finished with value: 0.22457830104625148 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 481, 'oob_score': True, 'max_samples': 0.8276360496389354, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15723641146991377}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23621930342339553
Fold 2 IBS: 0.2197693683012021
Fold 3 IBS: 0.212549877635375
Fold 4 IBS: 0.2356582021089957
Fold 5 IBS: 0.21528103181762887
[I 2024-04-13 17:05:17,843] Trial 96 finished with value: 0.22389555665731944 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.7367464108563165, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23193902254984444}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.24624060350675028
Fold 2 IBS: 0.2322034277468248
Fold 3 IBS: 0.22948763066493197
Fold 4 IBS: 0.24145111666189772
Fold 5 IBS: 0.23035506563166086
[I 2024-04-13 17:05:20,575] Trial 97 finished with value: 0.23594756884241314 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.521538664132392, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3938564682169779}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.24008462634911135
Fold 2 IBS: 0.23017081780056728
Fold 3 IBS: 0.22347056715802682
Fold 4 IBS: 0.2395816781582648
Fold 5 IBS: 0.21173964829758143
[I 2024-04-13 17:05:23,607] Trial 98 finished with value: 0.22900946755271034 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 448, 'oob_score': True, 'max_samples': 0.916008923653836, 'max_features': None, 'min_weight_fraction_leaf': 0.25397155497290275}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23762169677462724
Fold 2 IBS: 0.21844353189407748
Fold 3 IBS: 0.2134302825507703
Fold 4 IBS: 0.2336034074556809
Fold 5 IBS: 0.2145271402918729
[I 2024-04-13 17:05:26,052] Trial 99 finished with value: 0.22352521179340573 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.7611936700803305, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1748800349642079}. Best is trial 84 with value: 0.22302339534037285.


* Best trial for IBS:
 FrozenTrial(number=84, state=TrialState.COMPLETE, values=[0.22302339534037285], datetime_start=datetime.datetime(2024, 4, 13, 17, 4, 43, 511491), datetime_complete=datetime.datetime(2024, 4, 13, 17, 4, 45, 709570), params={'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.8096737689830545, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19628098798162147}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=84, value=None)


* Best Score for IBS:
 0.22302339534037285

In [57]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [58]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.76
train_ibs:  0.223

#### Test

In [59]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

In [60]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=5, max_leaf_nodes=8,
                     max_samples=0.9313711932374781, min_samples_split=12,
                     min_weight_fraction_leaf=0.011633867937315842,
                     n_estimators=214, random_state=123, warm_start=True)

test_cindex:  0.633

RandomSurvivalForest(max_depth=6, max_features='log2', max_leaf_nodes=20,
                     max_samples=0.8096737689830545, min_samples_leaf=2,
                     min_samples_split=11,
                     min_weight_fraction_leaf=0.19628098798162147,
                     n_estimators=453, oob_score=True, random_state=123)

test_ibs:  0.216

In [61]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [62]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [63]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:05:26,915] A new study created in memory with name: no-name-8cf49f5a-eb8b-49d8-9bc2-05e8ff684224

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:05:27,447] Trial 0 finished with value: 0.6810141068632278 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:05:28,367] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:05:30,282] Trial 2 finished with value: 0.6582254660871222 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:05:30,455] Trial 3 finished with value: 0.6744438961941063 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:05:31,152] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:05:32,052] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 17:05:32,519] Trial 6 finished with value: 0.6859283885370657 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:05:33,625] Trial 7 finished with value: 0.6556068669162063 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6545064377682404
[I 2024-04-13 17:05:33,697] Trial 8 finished with value: 0.6654991867539214 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 17:05:36,035] Trial 9 finished with value: 0.6603853489169398 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:05:36,900] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6787072243346007
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 17:05:37,355] Trial 11 finished with value: 0.6617606716684828 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6781115879828327
[I 2024-04-13 17:05:37,942] Trial 12 finished with value: 0.6867027610976928 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:05:38,513] Trial 13 finished with value: 0.6726878143099698 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638831587887255, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:05:38,981] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:05:39,311] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 268, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.33571048327918607, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 12 with value: 0.6867027610976928.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.6825095057034221
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 17:05:39,865] Trial 16 finished with value: 0.6718042314769685 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6535355702555379, 'min_weight_fraction_leaf': 0.1906011147608997}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.6453488372093024
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6825095057034221
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 17:05:40,342] Trial 17 finished with value: 0.6672980040406395 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.903993543626621, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.6375968992248062
Fold 3 C-index: 0.7978723404255319
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6373390557939914
[I 2024-04-13 17:05:40,537] Trial 18 finished with value: 0.6795670368174951 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.38500398118655316, 'min_weight_fraction_leaf': 0.0735015574561402}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:05:40,712] Trial 19 finished with value: 0.6806917145768351 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.639253673774636, 'min_weight_fraction_leaf': 0.037408326362835864}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:05:41,081] Trial 20 finished with value: 0.6744556768014014 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8892982712995542, 'min_weight_fraction_leaf': 0.18720118160246144}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 17:05:41,597] Trial 21 finished with value: 0.6816626070383462 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7247491835588253, 'min_weight_fraction_leaf': 0.10612931382459131}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 17:05:42,116] Trial 22 finished with value: 0.6768203176157102 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 447, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5833816310769062, 'min_weight_fraction_leaf': 0.10633258814265802}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6781115879828327
[I 2024-04-13 17:05:42,598] Trial 23 finished with value: 0.6861561520662033 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7310231778151053, 'min_weight_fraction_leaf': 0.013477785996217753}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 17:05:42,976] Trial 24 finished with value: 0.6783926045851235 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8534877389255904, 'min_weight_fraction_leaf': 0.013359081882411139}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:05:43,514] Trial 25 finished with value: 0.6823606592762896 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4743026143351115, 'min_weight_fraction_leaf': 0.05557982163590168}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:05:45,763] Trial 26 finished with value: 0.6371432881239313 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 410, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6941935959294678, 'min_weight_fraction_leaf': 0.026806923014800983}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.6863117870722434
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 17:05:46,242] Trial 27 finished with value: 0.6759366077958741 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 443, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5973500072561096, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7553648068669528
[I 2024-04-13 17:05:46,546] Trial 28 finished with value: 0.7175262582650991 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 204, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8562851117410581, 'min_weight_fraction_leaf': 0.07014867084326157}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7725321888412017
[I 2024-04-13 17:05:46,815] Trial 29 finished with value: 0.7156180788739028 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 206, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9207564519428275, 'min_weight_fraction_leaf': 0.07367160474295377}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7510729613733905
[I 2024-04-13 17:05:47,112] Trial 30 finished with value: 0.7115365161329625 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 207, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9237987532624947, 'min_weight_fraction_leaf': 0.08837761097303978}. Best is trial 28 with value: 0.7175262582650991.

Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7682403433476395
[I 2024-04-13 17:05:47,405] Trial 31 finished with value: 0.7161536582914563 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 207, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9402340730195752, 'min_weight_fraction_leaf': 0.07589392630375186}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 17:05:47,678] Trial 32 finished with value: 0.6961121726190391 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 207, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.855896173949004, 'min_weight_fraction_leaf': 0.08857520431614199}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7639484978540773
[I 2024-04-13 17:05:47,959] Trial 33 finished with value: 0.7153131837982872 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 199, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9327283887206919, 'min_weight_fraction_leaf': 0.07569748402462002}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.6375968992248062
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.6787072243346007
Fold 5 C-index: 0.6802575107296137
[I 2024-04-13 17:05:48,184] Trial 34 finished with value: 0.6664666881360952 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 156, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.835970866549261, 'min_weight_fraction_leaf': 0.23372934022685896}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7081545064377682
[I 2024-04-13 17:05:48,615] Trial 35 finished with value: 0.6882634234693772 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 162, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9271457960024162, 'min_weight_fraction_leaf': 0.130853317292017}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.5736434108527132
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6180257510729614
[I 2024-04-13 17:05:49,213] Trial 36 finished with value: 0.6191913617370259 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 124, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9489017093297756, 'min_weight_fraction_leaf': 0.05781516413223613}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.7124463519313304
[I 2024-04-13 17:05:49,535] Trial 37 finished with value: 0.6833092043963852 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8743715114186904, 'min_weight_fraction_leaf': 0.16627394422836966}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 17:05:49,817] Trial 38 finished with value: 0.6876697416391948 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 182, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.817264125566284, 'min_weight_fraction_leaf': 0.11814667951535995}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.5697674418604651
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 17:05:50,624] Trial 39 finished with value: 0.6172171145531613 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 102, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9887286618847455, 'min_weight_fraction_leaf': 0.07199443797246757}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.6787072243346007
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 17:05:50,976] Trial 40 finished with value: 0.66414330845729 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 285, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7565046460320802, 'min_weight_fraction_leaf': 0.24430703768925296}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 17:05:51,304] Trial 41 finished with value: 0.7066368021144237 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9048172691384212, 'min_weight_fraction_leaf': 0.08914857859645303}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8154506437768241
[I 2024-04-13 17:05:51,593] Trial 42 finished with value: 0.743465329768543 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9365468593171198, 'min_weight_fraction_leaf': 0.041208379854996445}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:05:51,833] Trial 43 finished with value: 0.6963198668263061 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 181, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8038316611821256, 'min_weight_fraction_leaf': 0.04529341869060194}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7982832618025751
[I 2024-04-13 17:05:52,147] Trial 44 finished with value: 0.7313319298416705 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 236, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9992719988890266, 'min_weight_fraction_leaf': 0.06592612651601726}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6569767441860465
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6459227467811158
[I 2024-04-13 17:05:52,446] Trial 45 finished with value: 0.6673320498489252 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 236, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9991832238100966, 'min_weight_fraction_leaf': 0.2989643862163749}. Best is trial 42 with value: 0.743465329768543.

Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7939914163090128
[I 2024-04-13 17:05:52,647] Trial 46 finished with value: 0.7383725397721712 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 132, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9470561026828803, 'min_weight_fraction_leaf': 0.03640088498403455}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6630901287553648
[I 2024-04-13 17:05:53,063] Trial 47 finished with value: 0.6598696288076124 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 89, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9628659202725078, 'min_weight_fraction_leaf': 0.03266964081324999}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 17:05:53,726] Trial 48 finished with value: 0.6843049998761438 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 269, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8730259684417422, 'min_weight_fraction_leaf': 0.1266834798944097}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6298449612403101
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6330472103004292
[I 2024-04-13 17:05:53,950] Trial 49 finished with value: 0.6590145940458656 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 136, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.957708632958839, 'min_weight_fraction_leaf': 0.027911042382701867}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 17:05:54,202] Trial 50 finished with value: 0.6897778948683545 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 175, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7837469252671783, 'min_weight_fraction_leaf': 0.1078843272541912}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8154506437768241
[I 2024-04-13 17:05:54,632] Trial 51 finished with value: 0.7441605217818494 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 222, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9978368210677339, 'min_weight_fraction_leaf': 0.05105168315138192}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7982832618025751
[I 2024-04-13 17:05:54,853] Trial 52 finished with value: 0.7320707671648804 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 81, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9693702623323143, 'min_weight_fraction_leaf': 0.05796340800499559}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8068669527896996
[I 2024-04-13 17:05:55,055] Trial 53 finished with value: 0.724572062991922 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 76, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9970270850713104, 'min_weight_fraction_leaf': 0.05198230424362128}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7896995708154506
[I 2024-04-13 17:05:55,237] Trial 54 finished with value: 0.7259167134190326 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 66, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9784142102515536, 'min_weight_fraction_leaf': 0.03905401729625176}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.703862660944206
[I 2024-04-13 17:05:55,414] Trial 55 finished with value: 0.7020258748504518 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 54, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9639066574288683, 'min_weight_fraction_leaf': 0.021327695456537624}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:05:55,544] Trial 56 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 25, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8965627067300803, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5876494023904383
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6781115879828327
[I 2024-04-13 17:05:55,634] Trial 57 finished with value: 0.6762686514862031 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 7, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.22469228024982557, 'min_weight_fraction_leaf': 0.05372431175834813}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 17:05:55,826] Trial 58 finished with value: 0.6970396573100552 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 77, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5320477532151755, 'min_weight_fraction_leaf': 0.03900243908413086}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 17:05:56,272] Trial 59 finished with value: 0.6519459902471118 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 55, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9630384668147912, 'min_weight_fraction_leaf': 6.788603062825999e-05}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.6634980988593155
Fold 5 C-index: 0.6158798283261803
[I 2024-04-13 17:05:56,536] Trial 60 finished with value: 0.6413474338179449 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 143, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9882157961126447, 'min_weight_fraction_leaf': 0.38500894227855625}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7829787234042553

Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 17:05:56,712] Trial 61 finished with value: 0.7225416362930333 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 66, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9943656688034969, 'min_weight_fraction_leaf': 0.04800870002967368}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7081545064377682
[I 2024-04-13 17:05:56,969] Trial 62 finished with value: 0.6897163220843844 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 107, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8946150126733304, 'min_weight_fraction_leaf': 0.10247641006595459}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7639484978540773
[I 2024-04-13 17:05:57,178] Trial 63 finished with value: 0.7196656386882508 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 38, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9438677546925018, 'min_weight_fraction_leaf': 0.024050857269544722}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7896995708154506
[I 2024-04-13 17:05:57,444] Trial 64 finished with value: 0.7327012293133587 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 125, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9946117477834561, 'min_weight_fraction_leaf': 0.056485434742474354}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7896995708154506
[I 2024-04-13 17:05:57,702] Trial 65 finished with value: 0.7433456281236541 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 122, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9063260887192888, 'min_weight_fraction_leaf': 0.012665422708896507}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:05:57,978] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 128, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8260977181471251, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7682403433476395
[I 2024-04-13 17:05:58,506] Trial 67 finished with value: 0.7327922342641481 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9104970128937423, 'min_weight_fraction_leaf': 0.007706755525859518}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7510729613733905
[I 2024-04-13 17:05:59,039] Trial 68 finished with value: 0.7224161877505806 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 295, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9198568568859149, 'min_weight_fraction_leaf': 0.00978704762960042}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7339055793991416
[I 2024-04-13 17:05:59,693] Trial 69 finished with value: 0.7244476068280288 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8797241290258244, 'min_weight_fraction_leaf': 0.01678703277254251}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:00,129] Trial 70 finished with value: 0.6745315468327391 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 253, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9113946680361682, 'min_weight_fraction_leaf': 0.03227851293056033}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7124463519313304
[I 2024-04-13 17:06:00,601] Trial 71 finished with value: 0.7075849752369485 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 219, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9418428735851675, 'min_weight_fraction_leaf': 0.06227247952613971}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 17:06:00,916] Trial 72 finished with value: 0.7027360570907633 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 171, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8489781434967721, 'min_weight_fraction_leaf': 0.08925369909603265}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 17:06:01,452] Trial 73 finished with value: 0.7683176307777926 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 274, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9666978302306899, 'min_weight_fraction_leaf': 0.0007431171546460995}. Best is trial 73 with value: 0.7683176307777926.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8111587982832618
[I 2024-04-13 17:06:01,946] Trial 74 finished with value: 0.753464799313606 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 253, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8740760642487182, 'min_weight_fraction_leaf': 0.01305076334530337}. Best is trial 73 with value: 0.7683176307777926.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7639484978540773
[I 2024-04-13 17:06:02,382] Trial 75 finished with value: 0.7267661356567718 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 275, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4065884568013973, 'min_weight_fraction_leaf': 0.00029874484326093687}. Best is trial 73 with value: 0.7683176307777926.

Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 17:06:04,763] Trial 76 finished with value: 0.6416338194920268 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 331, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8799754466378142, 'min_weight_fraction_leaf': 0.01810709499481526}. Best is trial 73 with value: 0.7683176307777926.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8412017167381974
[I 2024-04-13 17:06:05,231] Trial 77 finished with value: 0.7543780132055444 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9240429179776719, 'min_weight_fraction_leaf': 0.012643822634965579}. Best is trial 73 with value: 0.7683176307777926.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6909871244635193
[I 2024-04-13 17:06:05,713] Trial 78 finished with value: 0.6958045178573318 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7594151082635523, 'min_weight_fraction_leaf': 0.015234469209567447}. Best is trial 73 with value: 0.7683176307777926.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 17:06:06,119] Trial 79 finished with value: 0.7697774108186687 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 250, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8442545000898158, 'min_weight_fraction_leaf': 0.0004457953818449434}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8369098712446352
[I 2024-04-13 17:06:06,463] Trial 80 finished with value: 0.7583547716816389 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 193, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8057269821925708, 'min_weight_fraction_leaf': 0.032477063707157354}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7982832618025751
[I 2024-04-13 17:06:06,909] Trial 81 finished with value: 0.7385651919069479 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.832112782603648, 'min_weight_fraction_leaf': 0.04071400179748555}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8283261802575107
[I 2024-04-13 17:06:07,439] Trial 82 finished with value: 0.7510098175054138 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 246, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7294416952085367, 'min_weight_fraction_leaf': 0.02743234620004307}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8412017167381974
[I 2024-04-13 17:06:07,875] Trial 83 finished with value: 0.759259943171113 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 190, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8005603713498318, 'min_weight_fraction_leaf': 0.024887842810569518}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8197424892703863
[I 2024-04-13 17:06:08,356] Trial 84 finished with value: 0.7468373768005192 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6978238625237797, 'min_weight_fraction_leaf': 0.027202826299221203}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 17:06:08,740] Trial 85 finished with value: 0.6834829872526711 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 189, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7435224088611663, 'min_weight_fraction_leaf': 0.026900856768979266}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8454935622317596
[I 2024-04-13 17:06:09,180] Trial 86 finished with value: 0.7730627016264678 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 219, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6969352508494835, 'min_weight_fraction_leaf': 0.0016027914654294685}. Best is trial 86 with value: 0.7730627016264678.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8412017167381974
[I 2024-04-13 17:06:09,763] Trial 87 finished with value: 0.7744609253176357 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 262, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6910931457501369, 'min_weight_fraction_leaf': 0.0034957148487665163}. Best is trial 87 with value: 0.7744609253176357.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.5736434108527132
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 17:06:12,201] Trial 88 finished with value: 0.62249459003292 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 264, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6571074060623916, 'min_weight_fraction_leaf': 0.002587756834995009}. Best is trial 87 with value: 0.7744609253176357.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8025751072961373
[I 2024-04-13 17:06:12,781] Trial 89 finished with value: 0.7474274777067873 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 305, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6947330701336499, 'min_weight_fraction_leaf': 0.01811060590765391}. Best is trial 87 with value: 0.7744609253176357.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6180257510729614
[I 2024-04-13 17:06:13,252] Trial 90 finished with value: 0.6534956129908318 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7833034071663476, 'min_weight_fraction_leaf': 0.2732759857764308}. Best is trial 87 with value: 0.7744609253176357.

Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8025751072961373
[I 2024-04-13 17:06:13,846] Trial 91 finished with value: 0.7442871889568908 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 301, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6338574910210881, 'min_weight_fraction_leaf': 0.018245084195721045}. Best is trial 87 with value: 0.7744609253176357.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8454935622317596
[I 2024-04-13 17:06:14,354] Trial 92 finished with value: 0.7783542380855362 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7127170027641319, 'min_weight_fraction_leaf': 0.007255594364833751}. Best is trial 92 with value: 0.7783542380855362.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 17:06:14,863] Trial 93 finished with value: 0.773012031469599 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 275, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7126345666181687, 'min_weight_fraction_leaf': 0.01132491050397371}. Best is trial 92 with value: 0.7783542380855362.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:06:15,333] Trial 94 finished with value: 0.7914071396177732 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8020091028727125, 'min_weight_fraction_leaf': 0.002435943155287043}. Best is trial 94 with value: 0.7914071396177732.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8540772532188842
[I 2024-04-13 17:06:15,756] Trial 95 finished with value: 0.7656779799204749 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.805459261539753, 'min_weight_fraction_leaf': 0.0014206283717166004}. Best is trial 94 with value: 0.7914071396177732.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8583690987124464
[I 2024-04-13 17:06:16,230] Trial 96 finished with value: 0.7792303748029571 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 317, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.803528354509956, 'min_weight_fraction_leaf': 0.0027490549087902}. Best is trial 94 with value: 0.7914071396177732.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7939914163090128
[I 2024-04-13 17:06:16,698] Trial 97 finished with value: 0.7488547526042695 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6615256729229535, 'min_weight_fraction_leaf': 0.003268318092994542}. Best is trial 94 with value: 0.7914071396177732.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7939914163090128
[I 2024-04-13 17:06:17,131] Trial 98 finished with value: 0.7498258990394505 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 279, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6157099383260888, 'min_weight_fraction_leaf': 0.0006747748712030638}. Best is trial 94 with value: 0.7914071396177732.

[I 2024-04-13 17:06:17,633] A new study created in memory with name: no-name-d548fa96-3a0a-4c2f-8174-2d71f31ab460

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6909871244635193
[I 2024-04-13 17:06:17,627] Trial 99 finished with value: 0.6972890739296207 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 345, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7082106596673203, 'min_weight_fraction_leaf': 0.047918273005709944}. Best is trial 94 with value: 0.7914071396177732.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.7914071396177732], datetime_start=datetime.datetime(2024, 4, 13, 17, 6, 14, 866607), datetime_complete=datetime.datetime(2024, 4, 13, 17, 6, 15, 332573), params={'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8020091028727125, 'min_weight_fraction_leaf': 0.002435943155287043}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=94, value=None)


* Best Score for C-index:
 0.7914071396177732

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2376731560632284
Fold 2 IBS: 0.21418439969357622
Fold 3 IBS: 0.20583073428188067
Fold 4 IBS: 0.22566432866025307
Fold 5 IBS: 0.20768742813444407
[I 2024-04-13 17:06:19,348] Trial 0 finished with value: 0.2182080093666765 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-13 17:06:22,019] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.23822850327226391
Fold 2 IBS: 0.2206236163074506
Fold 3 IBS: 0.21714095783489826
Fold 4 IBS: 0.231585384136663
Fold 5 IBS: 0.21839284596456812
[I 2024-04-13 17:06:25,135] Trial 2 finished with value: 0.2251942615031688 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.23969391295516015
Fold 2 IBS: 0.22269581058919702
Fold 3 IBS: 0.21715327615258315
Fold 4 IBS: 0.23305972993486937
Fold 5 IBS: 0.21933565152070564
[I 2024-04-13 17:06:26,096] Trial 3 finished with value: 0.22638767623050304 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-13 17:06:28,062] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-13 17:06:29,227] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.23749741627181767
Fold 2 IBS: 0.21452695445742026
Fold 3 IBS: 0.2056873183383438
Fold 4 IBS: 0.22461247201663356
Fold 5 IBS: 0.20853691895247092
[I 2024-04-13 17:06:31,434] Trial 6 finished with value: 0.21817221600733724 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24029204437738358
Fold 2 IBS: 0.21830289871526046
Fold 3 IBS: 0.21554373414859246
Fold 4 IBS: 0.22777980675313916
Fold 5 IBS: 0.2123884851749296
[I 2024-04-13 17:06:32,883] Trial 7 finished with value: 0.22286139383386105 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24089922857013013
Fold 2 IBS: 0.22202813660146767
Fold 3 IBS: 0.21893220102332406
Fold 4 IBS: 0.2316324273038109
Fold 5 IBS: 0.2195150868165958
[I 2024-04-13 17:06:33,167] Trial 8 finished with value: 0.2266014160630657 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24074052614629513
Fold 2 IBS: 0.2266612039122537
Fold 3 IBS: 0.22147987410714284
Fold 4 IBS: 0.23635902242741375
Fold 5 IBS: 0.22338299988114635
[I 2024-04-13 17:06:36,188] Trial 9 finished with value: 0.22972472529485036 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24645397072894554
Fold 2 IBS: 0.23215165796624326
Fold 3 IBS: 0.2300072528605466
Fold 4 IBS: 0.24106162740477477
Fold 5 IBS: 0.23037976132987092
[I 2024-04-13 17:06:38,517] Trial 10 finished with value: 0.23601085405807623 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24194872801906908
Fold 2 IBS: 0.22653162527123616
Fold 3 IBS: 0.2214231768945529
Fold 4 IBS: 0.23736843207524794
Fold 5 IBS: 0.22258083713853571
[I 2024-04-13 17:06:40,297] Trial 11 finished with value: 0.22997055987972836 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24166386224310335
Fold 2 IBS: 0.21668275898081935
Fold 3 IBS: 0.21053766058256898
Fold 4 IBS: 0.22332329218058097
Fold 5 IBS: 0.20507124091541545
[I 2024-04-13 17:06:42,979] Trial 12 finished with value: 0.21945576298049763 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2351797092055412
Fold 2 IBS: 0.21809509235620259
Fold 3 IBS: 0.20720090287111972
Fold 4 IBS: 0.2272337876903696
Fold 5 IBS: 0.21352749156724554
[I 2024-04-13 17:06:44,952] Trial 13 finished with value: 0.22024739673809574 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6381530978163132, 'min_weight_fraction_leaf': 0.10302250602390595}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24709076537787542
Fold 2 IBS: 0.23229758763044567
Fold 3 IBS: 0.22965399450652796
Fold 4 IBS: 0.2411751364309486
Fold 5 IBS: 0.23019081700505956
[I 2024-04-13 17:06:46,393] Trial 14 finished with value: 0.23608166019017146 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3469585144995889, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 6 with value: 0.21817221600733724.

Fold 1 IBS: 0.2400719537573894
Fold 2 IBS: 0.21389198803292667
Fold 3 IBS: 0.20731598881412483
Fold 4 IBS: 0.2254024226576354
Fold 5 IBS: 0.2076527894088986
[I 2024-04-13 17:06:48,726] Trial 15 finished with value: 0.21886702853419499 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07436726243220565}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23503018438204812
Fold 2 IBS: 0.2154046167742676
Fold 3 IBS: 0.20556392106742435
Fold 4 IBS: 0.22806516746710437
Fold 5 IBS: 0.2112562209054064
[I 2024-04-13 17:06:50,468] Trial 16 finished with value: 0.2190640221192502 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.18687423911629308}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24669394452893645
Fold 2 IBS: 0.2321566246385927
Fold 3 IBS: 0.22939614692957794
Fold 4 IBS: 0.24141885307467398
Fold 5 IBS: 0.2302911553756569
[I 2024-04-13 17:06:51,546] Trial 17 finished with value: 0.23599134490948756 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 194, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5688392530311949, 'min_weight_fraction_leaf': 0.3862403774000863}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24801473011738637
Fold 2 IBS: 0.23336726698773866
Fold 3 IBS: 0.22984121679333408
Fold 4 IBS: 0.24176299307832128
Fold 5 IBS: 0.23015950059445994
[I 2024-04-13 17:06:51,825] Trial 18 finished with value: 0.23662914151424808 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.053773653856063974}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2464616995792693
Fold 2 IBS: 0.23218447499282707
Fold 3 IBS: 0.2297960999906114
Fold 4 IBS: 0.24126238252144364
Fold 5 IBS: 0.2299756977580421
[I 2024-04-13 17:06:52,454] Trial 19 finished with value: 0.2359360709684387 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4078786025735315, 'min_weight_fraction_leaf': 0.21750931502909437}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2356021274854339
Fold 2 IBS: 0.21736519916854574
Fold 3 IBS: 0.20646952344066247
Fold 4 IBS: 0.2281727318804719
Fold 5 IBS: 0.21322795644159553
[I 2024-04-13 17:06:54,030] Trial 20 finished with value: 0.22016750768334195 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 17, 'n_estimators': 310, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8887988952213425, 'min_weight_fraction_leaf': 0.16483895863649992}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2390208829210001
Fold 2 IBS: 0.21477636398758923
Fold 3 IBS: 0.2077575615094621
Fold 4 IBS: 0.22444376825518106
Fold 5 IBS: 0.20787997219697457
[I 2024-04-13 17:06:56,155] Trial 21 finished with value: 0.21877570977404143 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 416, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7050862172818282, 'min_weight_fraction_leaf': 0.08156751747114571}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2371332546390252
Fold 2 IBS: 0.21451079091509603
Fold 3 IBS: 0.20658616237101907
Fold 4 IBS: 0.2261028080781042
Fold 5 IBS: 0.20871606880123938
[I 2024-04-13 17:06:58,778] Trial 22 finished with value: 0.21860981696089682 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6873159527855055, 'min_weight_fraction_leaf': 0.10600930066685874}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24192493047866456
Fold 2 IBS: 0.21692042280147458
Fold 3 IBS: 0.20634554837219973
Fold 4 IBS: 0.22627161207172614
Fold 5 IBS: 0.20726148438799455
[I 2024-04-13 17:07:01,254] Trial 23 finished with value: 0.21974479962241192 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 459, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6015263103836297, 'min_weight_fraction_leaf': 0.028083898670301616}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23659856282659097
Fold 2 IBS: 0.2153141906947614
Fold 3 IBS: 0.2047151307497504
Fold 4 IBS: 0.22602716181430646
Fold 5 IBS: 0.21120163992617527
[I 2024-04-13 17:07:03,565] Trial 24 finished with value: 0.21877133720231692 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 495, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5266956821498789, 'min_weight_fraction_leaf': 0.09390422583252539}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23844194453158782
Fold 2 IBS: 0.22105165705465776
Fold 3 IBS: 0.2170232482052371
Fold 4 IBS: 0.23092368220074286
Fold 5 IBS: 0.2182289218147539
[I 2024-04-13 17:07:05,367] Trial 25 finished with value: 0.22513389076139587 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8933482791661949, 'min_weight_fraction_leaf': 0.13197369292803862}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23843041914620997
Fold 2 IBS: 0.21493453665123136
Fold 3 IBS: 0.2090168989775049
Fold 4 IBS: 0.2254910625046002
Fold 5 IBS: 0.20756991091332164
[I 2024-04-13 17:07:07,613] Trial 26 finished with value: 0.21908856563857357 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 347, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7414002668859774, 'min_weight_fraction_leaf': 0.026829572042154526}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2509863618363121
Fold 2 IBS: 0.22583805299486692
Fold 3 IBS: 0.21561349580190237
Fold 4 IBS: 0.23472261674578385
Fold 5 IBS: 0.20529371711830646
[I 2024-04-13 17:07:09,788] Trial 27 finished with value: 0.22649084889943433 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8390104664094136, 'min_weight_fraction_leaf': 0.10855414664475099}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2365772151298969
Fold 2 IBS: 0.22063815968102357
Fold 3 IBS: 0.2096147193508314
Fold 4 IBS: 0.23073997606593633
Fold 5 IBS: 0.21495122402474376
[I 2024-04-13 17:07:11,284] Trial 28 finished with value: 0.22250425885048636 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7007032081941286, 'min_weight_fraction_leaf': 0.26392524970352815}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24016407858058467
Fold 2 IBS: 0.2226945998414404
Fold 3 IBS: 0.1982935820263817
Fold 4 IBS: 0.22729610646127874
Fold 5 IBS: 0.20737931045192012
[I 2024-04-13 17:07:14,136] Trial 29 finished with value: 0.21916553547232112 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 410, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5262281274916285, 'min_weight_fraction_leaf': 0.17911878131541542}. Best is trial 6 with value: 0.21817221600733724.

Fold 1 IBS: 0.24654710532719232
Fold 2 IBS: 0.23226075421028072
Fold 3 IBS: 0.22941657391206893
Fold 4 IBS: 0.24156072638580853
Fold 5 IBS: 0.23017807225897458
[I 2024-04-13 17:07:15,366] Trial 30 finished with value: 0.235992646418865 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 225, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.46244718326068934, 'min_weight_fraction_leaf': 0.23846812660748434}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23751141455085345
Fold 2 IBS: 0.2151581315756588
Fold 3 IBS: 0.20565940925991258
Fold 4 IBS: 0.22542469872025206
Fold 5 IBS: 0.21030193870732267
[I 2024-04-13 17:07:17,868] Trial 31 finished with value: 0.2188111185627999 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5225620293165905, 'min_weight_fraction_leaf': 0.08868790596579997}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2381102203756688
Fold 2 IBS: 0.21526872502739017
Fold 3 IBS: 0.20815181349325143
Fold 4 IBS: 0.22568325207479042
Fold 5 IBS: 0.20752434700582614
[I 2024-04-13 17:07:20,289] Trial 32 finished with value: 0.2189476715953854 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 469, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6456061991595886, 'min_weight_fraction_leaf': 0.06162501081375873}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23538871189809704
Fold 2 IBS: 0.2182700935995022
Fold 3 IBS: 0.20730561342400977
Fold 4 IBS: 0.22803214159636556
Fold 5 IBS: 0.21291133753496125
[I 2024-04-13 17:07:22,986] Trial 33 finished with value: 0.22038157961058716 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 448, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.3962727024860553, 'min_weight_fraction_leaf': 0.11192391268789204}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23769165649579538
Fold 2 IBS: 0.21962693726644614
Fold 3 IBS: 0.21516823698710888
Fold 4 IBS: 0.22823472000435138
Fold 5 IBS: 0.21587988525872873
[I 2024-04-13 17:07:25,677] Trial 34 finished with value: 0.22332028720248612 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.48343209841746304, 'min_weight_fraction_leaf': 0.037167307803865623}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23862457868154657
Fold 2 IBS: 0.2142812234274352
Fold 3 IBS: 0.2071122831600512
Fold 4 IBS: 0.22647037485357482
Fold 5 IBS: 0.20820984278000723
[I 2024-04-13 17:07:27,848] Trial 35 finished with value: 0.218939660580523 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 394, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6000897439208172, 'min_weight_fraction_leaf': 0.0750146307727606}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23527534950071421
Fold 2 IBS: 0.21770457187441952
Fold 3 IBS: 0.20717349733261567
Fold 4 IBS: 0.22755601352686636
Fold 5 IBS: 0.21265069320216293
[I 2024-04-13 17:07:30,163] Trial 36 finished with value: 0.22007202508735574 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 442, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6131815692772876, 'min_weight_fraction_leaf': 0.1532744134723093}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24634031246577748
Fold 2 IBS: 0.23214260646544588
Fold 3 IBS: 0.2295950257561111
Fold 4 IBS: 0.24153927533138653
Fold 5 IBS: 0.2302443599910423
[I 2024-04-13 17:07:32,611] Trial 37 finished with value: 0.23597231600195262 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7619772249693068, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24216929138044868
Fold 2 IBS: 0.2271496608003459
Fold 3 IBS: 0.2224602263879355
Fold 4 IBS: 0.23789330129911662
Fold 5 IBS: 0.22532476564253662
[I 2024-04-13 17:07:35,652] Trial 38 finished with value: 0.23099944910207665 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 430, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6857951951640623, 'min_weight_fraction_leaf': 0.32409862457821353}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24627778387618462
Fold 2 IBS: 0.2322366961912888
Fold 3 IBS: 0.2296783065766575
Fold 4 IBS: 0.241413702842104
Fold 5 IBS: 0.2304581252108405
[I 2024-04-13 17:07:37,982] Trial 39 finished with value: 0.23601292293941506 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 481, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.2617193500766202, 'min_weight_fraction_leaf': 0.4166327790117036}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24943554696253312
Fold 2 IBS: 0.2275875045421105
Fold 3 IBS: 0.21215397389232193
Fold 4 IBS: 0.22982351135831186
Fold 5 IBS: 0.20097345883924955
[I 2024-04-13 17:07:39,792] Trial 40 finished with value: 0.22399479911890538 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 340, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5581919117237532, 'min_weight_fraction_leaf': 0.017165868694093697}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23914122142491184
Fold 2 IBS: 0.2147947351479995
Fold 3 IBS: 0.20776744684188206
Fold 4 IBS: 0.22457253880359845
Fold 5 IBS: 0.20865162921459607
[I 2024-04-13 17:07:41,935] Trial 41 finished with value: 0.2189855142865976 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 416, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7054883344953605, 'min_weight_fraction_leaf': 0.0896503362548107}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24271681884333898
Fold 2 IBS: 0.21620524856789322
Fold 3 IBS: 0.20723319617238797
Fold 4 IBS: 0.22507744594615037
Fold 5 IBS: 0.20484080364572635
[I 2024-04-13 17:07:44,008] Trial 42 finished with value: 0.21921470263509937 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 390, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8078708827436648, 'min_weight_fraction_leaf': 0.0480179528132343}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23614234446632862
Fold 2 IBS: 0.2146862138202214
Fold 3 IBS: 0.20617547040696596
Fold 4 IBS: 0.226976210049578
Fold 5 IBS: 0.2094767772998351
[I 2024-04-13 17:07:46,155] Trial 43 finished with value: 0.21869140320858582 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 434, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7262220752056259, 'min_weight_fraction_leaf': 0.12503295394556485}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23675493441717185
Fold 2 IBS: 0.2143052777671278
Fold 3 IBS: 0.20680963951540962
Fold 4 IBS: 0.22648948216139728
Fold 5 IBS: 0.20900398384520574
[I 2024-04-13 17:07:48,156] Trial 44 finished with value: 0.21867266354126244 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7563092184910359, 'min_weight_fraction_leaf': 0.12319485729503299}. Best is trial 6 with value: 0.21817221600733724.

Fold 1 IBS: 0.23579057506686668
Fold 2 IBS: 0.21781214726067985
Fold 3 IBS: 0.2066254011517932
Fold 4 IBS: 0.22753811203645144
Fold 5 IBS: 0.2131782901601682
[I 2024-04-13 17:07:50,034] Trial 45 finished with value: 0.22018890513519188 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 367, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7526038702156265, 'min_weight_fraction_leaf': 0.19723066794982302}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23864304620933718
Fold 2 IBS: 0.2216376067444548
Fold 3 IBS: 0.21798786862601383
Fold 4 IBS: 0.2317000936375164
Fold 5 IBS: 0.21855619191514636
[I 2024-04-13 17:07:51,970] Trial 46 finished with value: 0.2257049614264937 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 306, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8402191071167949, 'min_weight_fraction_leaf': 0.12410909471677475}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23563878904947858
Fold 2 IBS: 0.21424725828314625
Fold 3 IBS: 0.20539301573051336
Fold 4 IBS: 0.22686230831823445
Fold 5 IBS: 0.21106465433851035
[I 2024-04-13 17:07:53,257] Trial 47 finished with value: 0.2186412051439766 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 7, 'n_estimators': 256, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9648698685623813, 'min_weight_fraction_leaf': 0.16386048493715183}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23608296665281833
Fold 2 IBS: 0.21410238497896242
Fold 3 IBS: 0.20759570708434993
Fold 4 IBS: 0.22790237489945422
Fold 5 IBS: 0.21118066940259758
[I 2024-04-13 17:07:54,265] Trial 48 finished with value: 0.2193728206036365 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 188, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.964673069944489, 'min_weight_fraction_leaf': 0.15970031084197556}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23586798809596576
Fold 2 IBS: 0.2171901907305398
Fold 3 IBS: 0.20638917135134097
Fold 4 IBS: 0.22790269105933317
Fold 5 IBS: 0.2131331876876173
[I 2024-04-13 17:07:55,648] Trial 49 finished with value: 0.2200966457849594 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 257, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9370518091082483, 'min_weight_fraction_leaf': 0.2212372080269228}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23566720165017685
Fold 2 IBS: 0.21702158501775817
Fold 3 IBS: 0.20777305870793225
Fold 4 IBS: 0.2289923684746406
Fold 5 IBS: 0.2123285283685948
[I 2024-04-13 17:07:56,380] Trial 50 finished with value: 0.22035654844382052 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 131, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7996006309622741, 'min_weight_fraction_leaf': 0.17451620167795343}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23643320426918235
Fold 2 IBS: 0.21452872036487017
Fold 3 IBS: 0.2061667514710548
Fold 4 IBS: 0.22716532577885723
Fold 5 IBS: 0.2093136543684702
[I 2024-04-13 17:07:58,222] Trial 51 finished with value: 0.21872153125048693 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 369, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7348857113190044, 'min_weight_fraction_leaf': 0.12368563758615428}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23641193294091017
Fold 2 IBS: 0.21396216666253828
Fold 3 IBS: 0.205078775294875
Fold 4 IBS: 0.22790849339614294
Fold 5 IBS: 0.2096794545069518
[I 2024-04-13 17:07:59,874] Trial 52 finished with value: 0.21860816456028367 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 326, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8372294381144086, 'min_weight_fraction_leaf': 0.13938540553402562}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23760005782394428
Fold 2 IBS: 0.21366875869042135
Fold 3 IBS: 0.2069623183595147
Fold 4 IBS: 0.22721569193756555
Fold 5 IBS: 0.20902507159737838
[I 2024-04-13 17:08:01,393] Trial 53 finished with value: 0.21889437968176484 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 281, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.918667808078992, 'min_weight_fraction_leaf': 0.14156648297373461}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23620472019948477
Fold 2 IBS: 0.21446966517909544
Fold 3 IBS: 0.20562206377402104
Fold 4 IBS: 0.22725639394503946
Fold 5 IBS: 0.20996519098311808
[I 2024-04-13 17:08:02,591] Trial 54 finished with value: 0.21870360681615178 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8358880541378728, 'min_weight_fraction_leaf': 0.1455563484516374}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23778194706641292
Fold 2 IBS: 0.21478977024089968
Fold 3 IBS: 0.20765830208854946
Fold 4 IBS: 0.22627231039017479
Fold 5 IBS: 0.2078669168201539
[I 2024-04-13 17:08:04,379] Trial 55 finished with value: 0.21887384932123818 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 323, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7851303591277253, 'min_weight_fraction_leaf': 0.06284510067118923}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.238318805600092
Fold 2 IBS: 0.22036985262615907
Fold 3 IBS: 0.2165992463216147
Fold 4 IBS: 0.2309266992996685
Fold 5 IBS: 0.21739689485405828
[I 2024-04-13 17:08:06,790] Trial 56 finished with value: 0.2247222997403185 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 355, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8589971174200165, 'min_weight_fraction_leaf': 0.005571180329296155}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23762260324765577
Fold 2 IBS: 0.21419387527655073
Fold 3 IBS: 0.20857668730339252
Fold 4 IBS: 0.22634390477297547
Fold 5 IBS: 0.20826155026277154
[I 2024-04-13 17:08:08,444] Trial 57 finished with value: 0.2189997241726692 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 293, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9941137040048004, 'min_weight_fraction_leaf': 0.10935256889677493}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24142086672900914
Fold 2 IBS: 0.2243832837390074
Fold 3 IBS: 0.20244005121729616
Fold 4 IBS: 0.22860275074756728
Fold 5 IBS: 0.20676442441603726
[I 2024-04-13 17:08:10,177] Trial 58 finished with value: 0.22072227536978345 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 341, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6659973923607253, 'min_weight_fraction_leaf': 0.19865253699408333}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23558756630217798
Fold 2 IBS: 0.21872232455633453
Fold 3 IBS: 0.20756590838487826
Fold 4 IBS: 0.2282798830709085
Fold 5 IBS: 0.21390900413228608
[I 2024-04-13 17:08:11,739] Trial 59 finished with value: 0.2208129372893171 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 271, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9225473764084263, 'min_weight_fraction_leaf': 0.28011468219630264}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23905204688392212
Fold 2 IBS: 0.2187928517163343

Fold 3 IBS: 0.2102452041922602
Fold 4 IBS: 0.22890896945323644
Fold 5 IBS: 0.21433456345556318
[I 2024-04-13 17:08:12,181] Trial 60 finished with value: 0.22226672714026327 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 74, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9528336631358474, 'min_weight_fraction_leaf': 0.23484468684942653}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23541239037810044
Fold 2 IBS: 0.2157600681640186
Fold 3 IBS: 0.20665073702737224
Fold 4 IBS: 0.22705259747647938
Fold 5 IBS: 0.2114858383168534
[I 2024-04-13 17:08:14,345] Trial 61 finished with value: 0.21927232627256482 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 397, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6192920945584268, 'min_weight_fraction_leaf': 0.13261707538267872}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23553068478795697
Fold 2 IBS: 0.21690255883493398
Fold 3 IBS: 0.20634487576033259
Fold 4 IBS: 0.227390495160599
Fold 5 IBS: 0.21190307127879016
[I 2024-04-13 17:08:16,706] Trial 62 finished with value: 0.21961433716452256 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 444, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7228469890997942, 'min_weight_fraction_leaf': 0.16736170087898403}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23652120509947278
Fold 2 IBS: 0.21376852115432401
Fold 3 IBS: 0.20590736185366215
Fold 4 IBS: 0.22699281211564268
Fold 5 IBS: 0.2094937208444956
[I 2024-04-13 17:08:18,758] Trial 63 finished with value: 0.2185367242135195 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 380, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6675371718016896, 'min_weight_fraction_leaf': 0.10480172755123676}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23556228893011497
Fold 2 IBS: 0.22097929403924785
Fold 3 IBS: 0.20991652841690608
Fold 4 IBS: 0.2296617728771541
Fold 5 IBS: 0.21512411988151653
[I 2024-04-13 17:08:20,586] Trial 64 finished with value: 0.22224880082898793 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 3, 'n_estimators': 369, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6610936151946805, 'min_weight_fraction_leaf': 0.09922302854842845}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23828246171159492
Fold 2 IBS: 0.21557851298857106
Fold 3 IBS: 0.20938151683259248
Fold 4 IBS: 0.22533438744263723
Fold 5 IBS: 0.20920540651145889
[I 2024-04-13 17:08:22,227] Trial 65 finished with value: 0.21955645709737087 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 242, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.823446469666347, 'min_weight_fraction_leaf': 0.07059854704611815}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2364200039869531
Fold 2 IBS: 0.21438646307876086
Fold 3 IBS: 0.20573630300522222
Fold 4 IBS: 0.22702368533407957
Fold 5 IBS: 0.20961076514490226
[I 2024-04-13 17:08:24,645] Trial 66 finished with value: 0.2186354441099836 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 379, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5869176122888681, 'min_weight_fraction_leaf': 0.05075696238467242}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23639124735172928
Fold 2 IBS: 0.2145484268675974
Fold 3 IBS: 0.20522813470743728
Fold 4 IBS: 0.22671398387649164
Fold 5 IBS: 0.20934855998582716
[I 2024-04-13 17:08:27,119] Trial 67 finished with value: 0.21844607055781656 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 326, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6356340227566255, 'min_weight_fraction_leaf': 0.03968181972003887}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23657271370449404
Fold 2 IBS: 0.21804029729496446
Fold 3 IBS: 0.21045719072119984
Fold 4 IBS: 0.2270147984171555
Fold 5 IBS: 0.213512706028707
[I 2024-04-13 17:08:29,136] Trial 68 finished with value: 0.22111954123330416 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 315, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.574503516485792, 'min_weight_fraction_leaf': 0.0441948101443752}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23598252320933685
Fold 2 IBS: 0.21474373579441428
Fold 3 IBS: 0.20474033641872114
Fold 4 IBS: 0.22554630026453992
Fold 5 IBS: 0.21094491625082956
[I 2024-04-13 17:08:31,270] Trial 69 finished with value: 0.21839156238756835 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 330, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5838727235518294, 'min_weight_fraction_leaf': 0.024189353275833377}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23541761150477072
Fold 2 IBS: 0.21830744523559634
Fold 3 IBS: 0.2065414367985132
Fold 4 IBS: 0.22779205930266125
Fold 5 IBS: 0.21304401731614925
[I 2024-04-13 17:08:33,451] Trial 70 finished with value: 0.22022051403153814 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 335, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5116435605570427, 'min_weight_fraction_leaf': 0.025472119814750907}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2358050847465658
Fold 2 IBS: 0.21505617907633484
Fold 3 IBS: 0.20632041460134462
Fold 4 IBS: 0.2262324750390269
Fold 5 IBS: 0.20987569816898008
[I 2024-04-13 17:08:35,983] Trial 71 finished with value: 0.21865797032645046 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 385, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6369371661585259, 'min_weight_fraction_leaf': 0.011093571416785707}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23555223944807405
Fold 2 IBS: 0.21551046958229766
Fold 3 IBS: 0.2060538064107946
Fold 4 IBS: 0.2274823152167951
Fold 5 IBS: 0.21116980752977293
[I 2024-04-13 17:08:38,705] Trial 72 finished with value: 0.21915372763754687 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 407, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5939045307255605, 'min_weight_fraction_leaf': 0.034792886918428814}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23670318238684077
Fold 2 IBS: 0.2153132925145203
Fold 3 IBS: 0.20537237654935647
Fold 4 IBS: 0.2261310221764691
Fold 5 IBS: 0.21018749868962947
[I 2024-04-13 17:08:40,785] Trial 73 finished with value: 0.2187414744633632 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 304, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5785149488517107, 'min_weight_fraction_leaf': 0.05575349496200409}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23543448543686032
Fold 2 IBS: 0.21561006254005735
Fold 3 IBS: 0.20561005286053105
Fold 4 IBS: 0.22653019867698856
Fold 5 IBS: 0.21093122079808987
[I 2024-04-13 17:08:43,122] Trial 74 finished with value: 0.2188232040625054 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 327, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5392437858799007, 'min_weight_fraction_leaf': 0.020895543222114732}. Best is trial 6 with value: 0.21817221600733724.

Fold 1 IBS: 0.23749669116970254
Fold 2 IBS: 0.21417891364052918
Fold 3 IBS: 0.2066472918191204
Fold 4 IBS: 0.22577332010612122
Fold 5 IBS: 0.20791194308464916
[I 2024-04-13 17:08:45,796] Trial 75 finished with value: 0.2184016319640245 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 346, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6413926717278569, 'min_weight_fraction_leaf': 0.0007388507314896667}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23958121408927258
Fold 2 IBS: 0.21329051656876732
Fold 3 IBS: 0.20685348469946407
Fold 4 IBS: 0.2243628744610485
Fold 5 IBS: 0.2076885994354418
[I 2024-04-13 17:08:48,766] Trial 76 finished with value: 0.21835533785079883 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 356, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6743039221296488, 'min_weight_fraction_leaf': 0.07601195190861526}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24100163497067753
Fold 2 IBS: 0.21650889905387713
Fold 3 IBS: 0.21047274820869846
Fold 4 IBS: 0.22336649691832314
Fold 5 IBS: 0.20606715188435837
[I 2024-04-13 17:08:51,822] Trial 77 finished with value: 0.2194833862071869 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 358, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.632010203513251, 'min_weight_fraction_leaf': 0.001409785112660406}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23901813243753778
Fold 2 IBS: 0.21420034022703563
Fold 3 IBS: 0.20592138789952324
Fold 4 IBS: 0.2261656080238036
Fold 5 IBS: 0.20847447185713558
[I 2024-04-13 17:08:54,478] Trial 78 finished with value: 0.21875598808900715 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 323, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6857241761843896, 'min_weight_fraction_leaf': 0.0754366403965388}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23824458885708127
Fold 2 IBS: 0.21347939433681554
Fold 3 IBS: 0.2058991068238864
Fold 4 IBS: 0.2257803593854211
Fold 5 IBS: 0.20757894565473192
[I 2024-04-13 17:08:57,865] Trial 79 finished with value: 0.21819647901158726 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6608586112588376, 'min_weight_fraction_leaf': 0.08475815384047584}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2388143640724499
Fold 2 IBS: 0.21348020253653477
Fold 3 IBS: 0.20624726345211883
Fold 4 IBS: 0.22435505289042332
Fold 5 IBS: 0.208351275464022
[I 2024-04-13 17:09:00,903] Trial 80 finished with value: 0.2182496316831098 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 349, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5516495369043533, 'min_weight_fraction_leaf': 0.03371312562357193}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24069746455152283
Fold 2 IBS: 0.21539743059063785
Fold 3 IBS: 0.20826874922746164
Fold 4 IBS: 0.22473981003915017
Fold 5 IBS: 0.20649625442496652
[I 2024-04-13 17:09:03,767] Trial 81 finished with value: 0.21911994176674782 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 347, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6667332489251124, 'min_weight_fraction_leaf': 0.03652699788238737}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23772500283463666
Fold 2 IBS: 0.21351832416489283
Fold 3 IBS: 0.20551287071766666
Fold 4 IBS: 0.22528179451336483
Fold 5 IBS: 0.20855127007502566
[I 2024-04-13 17:09:06,526] Trial 82 finished with value: 0.2181178524611173 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 348, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4957463321896789, 'min_weight_fraction_leaf': 0.06535039686542465}. Best is trial 82 with value: 0.2181178524611173.
Fold 1 IBS: 0.24006097861784914
Fold 2 IBS: 0.21351296780007356
Fold 3 IBS: 0.20665204769701515
Fold 4 IBS: 0.22153407083328364
Fold 5 IBS: 0.20571739381784554
[I 2024-04-13 17:09:09,112] Trial 83 finished with value: 0.21749549175321342 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 351, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.44903497421134486, 'min_weight_fraction_leaf': 0.018023565445760347}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.24023569962199984
Fold 2 IBS: 0.21363622543199387
Fold 3 IBS: 0.2069585793435229
Fold 4 IBS: 0.2235635832191918
Fold 5 IBS: 0.2050944469518296
[I 2024-04-13 17:09:12,053] Trial 84 finished with value: 0.21789770691370763 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 354, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.44193402534807985, 'min_weight_fraction_leaf': 0.01787990099131466}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23894349587532945
Fold 2 IBS: 0.21620007594047472
Fold 3 IBS: 0.20751928103028916
Fold 4 IBS: 0.22372208334469412
Fold 5 IBS: 0.20582866480542367
[I 2024-04-13 17:09:15,028] Trial 85 finished with value: 0.2184427201992422 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 355, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.3945684829871626, 'min_weight_fraction_leaf': 0.018652438671265613}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23559845633067017
Fold 2 IBS: 0.21576618470285996
Fold 3 IBS: 0.20576607771200886
Fold 4 IBS: 0.22613316143073034
Fold 5 IBS: 0.21134237173993053
[I 2024-04-13 17:09:18,939] Trial 86 finished with value: 0.21892125038323998 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 397, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.44101859255864206, 'min_weight_fraction_leaf': 0.08385023506766573}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23685696539925846
Fold 2 IBS: 0.21480550862098527
Fold 3 IBS: 0.20596316091401243
Fold 4 IBS: 0.22582554770569668
Fold 5 IBS: 0.2089870418983674
[I 2024-04-13 17:09:22,921] Trial 87 finished with value: 0.2184876449076641 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 420, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.49032987293693886, 'min_weight_fraction_leaf': 0.06537420951395731}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.2372362315378745
Fold 2 IBS: 0.2141070051769487
Fold 3 IBS: 0.20515302733265592
Fold 4 IBS: 0.2254353766941232
Fold 5 IBS: 0.20982062489373873
[I 2024-04-13 17:09:25,853] Trial 88 finished with value: 0.2183504531270682 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 299, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.45867249639615437, 'min_weight_fraction_leaf': 0.055491708389874855}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23930793105990758
Fold 2 IBS: 0.21398355058184887
Fold 3 IBS: 0.2034152708638187
Fold 4 IBS: 0.22450497150068674
Fold 5 IBS: 0.20720970388342935
[I 2024-04-13 17:09:28,677] Trial 89 finished with value: 0.21768428557793826 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 294, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4321447624251241, 'min_weight_fraction_leaf': 0.05093978805292204}. Best is trial 83 with value: 0.21749549175321342.

Fold 1 IBS: 0.23843719064657817
Fold 2 IBS: 0.22064066243477068
Fold 3 IBS: 0.216117076423818
Fold 4 IBS: 0.23057174337958733
Fold 5 IBS: 0.21778600564999445
[I 2024-04-13 17:09:31,172] Trial 90 finished with value: 0.22471053570694974 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 274, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.42143690848778903, 'min_weight_fraction_leaf': 0.05305541913345835}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23636584853089593
Fold 2 IBS: 0.2160409129934387
Fold 3 IBS: 0.20518796152371307
Fold 4 IBS: 0.22686151762465062
Fold 5 IBS: 0.21138354158709388
[I 2024-04-13 17:09:33,895] Trial 91 finished with value: 0.21916795645195847 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 307, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.37885824272597207, 'min_weight_fraction_leaf': 0.0831355986175214}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23869477691909374
Fold 2 IBS: 0.21407356247574796
Fold 3 IBS: 0.2063518174852807
Fold 4 IBS: 0.22368052234862068
Fold 5 IBS: 0.20756617101134753
[I 2024-04-13 17:09:36,569] Trial 92 finished with value: 0.2180733700480181 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4717145746375765, 'min_weight_fraction_leaf': 0.031712424866108854}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23869477691909374
Fold 2 IBS: 0.21407356247574796
Fold 3 IBS: 0.2063518174852807
Fold 4 IBS: 0.2237085330935343
Fold 5 IBS: 0.20694772259468203
[I 2024-04-13 17:09:39,014] Trial 93 finished with value: 0.21795528251366775 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4672728524116875, 'min_weight_fraction_leaf': 0.011059612031062777}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23858095515316086
Fold 2 IBS: 0.21975164781209036
Fold 3 IBS: 0.21722961929030632
Fold 4 IBS: 0.23057130141512497
Fold 5 IBS: 0.21784545833330082
[I 2024-04-13 17:09:41,642] Trial 94 finished with value: 0.22479579640079664 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 315, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.34867843816025107, 'min_weight_fraction_leaf': 0.013031969056652583}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23786209898582975
Fold 2 IBS: 0.2150246994268266
Fold 3 IBS: 0.20529156517436606
Fold 4 IBS: 0.2250763776849818
Fold 5 IBS: 0.20845810397098258
[I 2024-04-13 17:09:45,182] Trial 95 finished with value: 0.21834256904859733 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 294, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4856085412705134, 'min_weight_fraction_leaf': 0.030125050021992245}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.25267952707924435
Fold 2 IBS: 0.22364036179533292
Fold 3 IBS: 0.21566522864655932
Fold 4 IBS: 0.2292360749986461
Fold 5 IBS: 0.20654056894732276
[I 2024-04-13 17:09:48,344] Trial 96 finished with value: 0.22555235229342108 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 286, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.432713162272765, 'min_weight_fraction_leaf': 0.038949501159838834}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23908189486059475
Fold 2 IBS: 0.21347457197868566
Fold 3 IBS: 0.2065066620897382
Fold 4 IBS: 0.22345877259235025
Fold 5 IBS: 0.20703900436678677
[I 2024-04-13 17:09:50,596] Trial 97 finished with value: 0.21791218117763114 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 245, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5036752163248778, 'min_weight_fraction_leaf': 0.009154320648984412}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.24118706264822834
Fold 2 IBS: 0.21292192130006443
Fold 3 IBS: 0.20750976633197557
Fold 4 IBS: 0.22523921978728415
Fold 5 IBS: 0.20766529155252064
[I 2024-04-13 17:09:52,145] Trial 98 finished with value: 0.21890465232401463 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 175, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5009566699282665, 'min_weight_fraction_leaf': 0.011093124694056673}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23852012019920124
Fold 2 IBS: 0.2149463648078171
Fold 3 IBS: 0.20528180370133903
Fold 4 IBS: 0.22528602680304402
Fold 5 IBS: 0.20818529472185981
[I 2024-04-13 17:09:54,324] Trial 99 finished with value: 0.21844392204665222 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 241, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4667379070625426, 'min_weight_fraction_leaf': 0.04638622319247108}. Best is trial 83 with value: 0.21749549175321342.


* Best trial for IBS:
 FrozenTrial(number=83, state=TrialState.COMPLETE, values=[0.21749549175321342], datetime_start=datetime.datetime(2024, 4, 13, 17, 9, 6, 531221), datetime_complete=datetime.datetime(2024, 4, 13, 17, 9, 9, 111909), params={'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 351, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.44903497421134486, 'min_weight_fraction_leaf': 0.018023565445760347}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=83, value=None)


* Best Score for IBS:
 0.21749549175321342

In [64]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [65]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.791
train_ibs:  0.217

#### Test

In [66]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [67]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=13, max_features=None, max_leaf_nodes=16,
                   max_samples=0.8020091028727125, min_samples_leaf=1,
                   min_samples_split=5,
                   min_weight_fraction_leaf=0.002435943155287043,
                   n_estimators=277, random_state=123, warm_start=True)

C-index score: 0.584

ExtraSurvivalTrees(max_depth=6, max_features='auto', max_leaf_nodes=16,
                   max_samples=0.44903497421134486, min_samples_leaf=4,
                   min_samples_split=9,
                   min_weight_fraction_leaf=0.018023565445760347,
                   n_estimators=351, oob_score=True, random_state=123)

IBS: 0.223

In [68]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [69]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:09:55,716] A new study created in memory with name: no-name-f4050f5c-e3ca-450d-8642-325b3a47b141

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:10:12,067] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:10:19,519] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:10:28,753] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:10:40,769] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:10:45,295] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:10:46,533] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:10:59,787] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:11:03,486] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:11:03,908] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6115879828326181
[I 2024-04-13 17:11:42,010] Trial 9 finished with value: 0.6015092457236193 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6015092457236193.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 17:12:43,353] Trial 10 finished with value: 0.5915509861883201 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6015092457236193.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:14:03,965] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6015092457236193.
Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6234042553191489
Fold 4 C-index: 0.5950570342205324
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 17:15:12,984] Trial 12 finished with value: 0.6059172111077464 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.6059172111077464.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:15:45,271] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:16:30,906] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:17:14,392] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:17:42,671] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:18:54,843] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:20:34,227] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:20:38,892] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:21:24,157] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:22:51,621] Trial 21 finished with value: 0.5 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5756972111553785
Fold 2 C-index: 0.6182170542635659
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.6596958174904943
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 17:24:08,657] Trial 22 finished with value: 0.6190116704947725 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:25:25,717] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:26:42,845] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:27:26,468] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:29:07,219] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:30:46,501] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:32:14,026] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:33:16,367] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:34:31,057] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:37:21,731] Trial 31 finished with value: 0.5071713147410358 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:39:55,966] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:41:51,397] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:44:57,994] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:45:25,726] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:48:14,760] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:48:19,682] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.6190116704947725.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:49:20,183] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:51:03,922] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:54:08,075] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 17:54:08,861] Trial 41 finished with value: 0.6039152174760968 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6008583690987125
[I 2024-04-13 17:54:33,691] Trial 42 finished with value: 0.624004230389207 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 42 with value: 0.624004230389207.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:54:34,651] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8735505723796891, 'learning_rate': 0.013455915558851193, 'dropout_rate': 0.11585930219083569, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 1.1546454041172216, 'min_weight_fraction_leaf': 0.4571018098895751, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8650432234384267, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 42 with value: 0.624004230389207.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:55:29,476] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9479336661285427, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.25335630680617827, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.4126953497238681, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.9438667820963776, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 42 with value: 0.624004230389207.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.6106382978723405
Fold 4 C-index: 0.6520912547528517
Fold 5 C-index: 0.6502145922746781
[I 2024-04-13 17:55:52,373] Trial 45 finished with value: 0.6250855089268532 and parameters: {'subsample': 0.5852424762732177, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.027804703729289008, 'min_weight_fraction_leaf': 0.262143273989599, 'max_features': 0.1, 'min_impurity_decrease': 9.467252666446998e-07, 'validation_fraction': 0.7243304021069044, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 45 with value: 0.6250855089268532.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:55:58,329] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.9097609675058456, 'learning_rate': 0.0647255784094387, 'dropout_rate': 0.9694253886674298, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 1.980441868470768, 'min_weight_fraction_leaf': 0.14203864492290658, 'max_features': 0.1, 'min_impurity_decrease': 2.8410487814192134e-06, 'validation_fraction': 0.7106683919659889, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 45 with value: 0.6250855089268532.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:56:36,108] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7952252972868074, 'learning_rate': 0.06333641179361332, 'dropout_rate': 0.20821540657294882, 'n_estimators': 172, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.38084444238994586, 'max_features': 0.1, 'min_impurity_decrease': 9.138461248752069e-07, 'validation_fraction': 0.8268165634838988, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 45 with value: 0.6250855089268532.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:56:46,156] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.5738829075301064, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.10579627176846597, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 0.443834316760607, 'min_weight_fraction_leaf': 0.2606631581830996, 'max_features': 0.1, 'min_impurity_decrease': 1.7788082392529892e-06, 'validation_fraction': 0.9003040994071866, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 17}. Best is trial 45 with value: 0.6250855089268532.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:56:46,961] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.84002245104845, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.17475217298119933, 'n_estimators': 9, 'criterion': 'friedman_mse', 'ccp_alpha': 1.370081088125734, 'min_weight_fraction_leaf': 0.21302024967189928, 'max_features': 0.1, 'min_impurity_decrease': 5.682612317450774e-06, 'validation_fraction': 0.8796670771312719, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 45 with value: 0.6250855089268532.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:56:50,260] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.9569410534968725, 'learning_rate': 0.07076395585024155, 'dropout_rate': 0.1405973314616702, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 1.7468603849227415, 'min_weight_fraction_leaf': 0.34344615267586504, 'max_features': 'log2', 'min_impurity_decrease': 1.89164645743038e-07, 'validation_fraction': 0.9611752371540778, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 45 with value: 0.6250855089268532.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:57:10,542] Trial 51 finished with value: 0.6344575916797196 and parameters: {'subsample': 0.4994582407940605, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.25361909697654017, 'n_estimators': 129, 'criterion': 'squared_error', 'ccp_alpha': 0.012243801070742757, 'min_weight_fraction_leaf': 0.30447335075613347, 'max_features': 'sqrt', 'min_impurity_decrease': 2.4617573739462015e-07, 'validation_fraction': 0.6627564435796373, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6520912547528517
Fold 5 C-index: 0.5815450643776824
[I 2024-04-13 17:57:24,867] Trial 52 finished with value: 0.6158557441321629 and parameters: {'subsample': 0.44756554166704604, 'learning_rate': 0.008555924871488166, 'dropout_rate': 0.22725206143365784, 'n_estimators': 109, 'criterion': 'squared_error', 'ccp_alpha': 0.03659945835027755, 'min_weight_fraction_leaf': 0.3136607614940329, 'max_features': 'sqrt', 'min_impurity_decrease': 2.38579101418113e-07, 'validation_fraction': 0.7452334109475507, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:57:44,207] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.45456603531105677, 'learning_rate': 0.057410108721501936, 'dropout_rate': 0.26583914946975784, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.4512041233232864, 'min_weight_fraction_leaf': 0.322074381929077, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0763963055081505e-06, 'validation_fraction': 0.6719316415566533, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:57:57,886] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.3984239460158819, 'learning_rate': 0.04823958197178553, 'dropout_rate': 0.37643214321044394, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 1.035069386526868, 'min_weight_fraction_leaf': 0.3013557556478156, 'max_features': 'sqrt', 'min_impurity_decrease': 2.871532477136697e-07, 'validation_fraction': 0.7420090012406269, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 9}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:58:13,955] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.5149754707590405, 'learning_rate': 0.006385731999605383, 'dropout_rate': 0.6373222391006226, 'n_estimators': 162, 'criterion': 'squared_error', 'ccp_alpha': 0.40074886285106287, 'min_weight_fraction_leaf': 0.22397272730341306, 'max_features': 'sqrt', 'min_impurity_decrease': 4.865634973369653e-07, 'validation_fraction': 0.7914357885759697, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:58:51,180] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.3411127486659095, 'learning_rate': 0.0223321562225781, 'dropout_rate': 0.23958844776950744, 'n_estimators': 188, 'criterion': 'squared_error', 'ccp_alpha': 1.2616701535027603, 'min_weight_fraction_leaf': 0.2741716094683543, 'max_features': 'sqrt', 'min_impurity_decrease': 2.219911700968688e-06, 'validation_fraction': 0.6090555519050711, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6596958174904943
Fold 5 C-index: 0.6180257510729614
[I 2024-04-13 17:59:01,263] Trial 57 finished with value: 0.6424069440095804 and parameters: {'subsample': 0.569175138136116, 'learning_rate': 0.09542136158814303, 'dropout_rate': 0.43613571687055647, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.0019473494055538935, 'min_weight_fraction_leaf': 0.36743918461462793, 'max_features': 'sqrt', 'min_impurity_decrease': 5.255459802548745e-07, 'validation_fraction': 0.7087056989518657, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 20}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:59:08,735] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.5648293474899495, 'learning_rate': 0.09980513755713626, 'dropout_rate': 0.5821753276684661, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.7470877807882045, 'min_weight_fraction_leaf': 0.33458212087172423, 'max_features': 'sqrt', 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.5649807819209639, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:59:29,260] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.43657835102234843, 'learning_rate': 0.08992223472821356, 'dropout_rate': 0.45063277335330026, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.8838088337816697, 'min_weight_fraction_leaf': 0.3051539123714827, 'max_features': 'sqrt', 'min_impurity_decrease': 6.123519561880064e-07, 'validation_fraction': 0.7025023924419704, 'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 20}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:59:37,940] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.49892638282698937, 'learning_rate': 0.0441252798316586, 'dropout_rate': 0.5171243893297963, 'n_estimators': 89, 'criterion': 'squared_error', 'ccp_alpha': 7.88888123252141, 'min_weight_fraction_leaf': 0.3630725265151832, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6800306990539567e-07, 'validation_fraction': 0.8258586719391796, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:59:40,842] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.2369113884490353, 'learning_rate': 0.08271570541393714, 'dropout_rate': 0.21451691891174118, 'n_estimators': 40, 'criterion': 'squared_error', 'ccp_alpha': 0.2307646041947069, 'min_weight_fraction_leaf': 0.26954907827809993, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1677029771075378e-06, 'validation_fraction': 0.7413035176238272, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 57 with value: 0.6424069440095804.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.6178707224334601
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:59:59,065] Trial 62 finished with value: 0.6243825724756604 and parameters: {'subsample': 0.5324319523145695, 'learning_rate': 0.01643486305639612, 'dropout_rate': 0.3264939129108728, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.022616672247981386, 'min_weight_fraction_leaf': 0.24162423168473884, 'max_features': 'sqrt', 'min_impurity_decrease': 5.949284725634976e-07, 'validation_fraction': 0.7732655768872577, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6254752851711026
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 18:00:18,299] Trial 63 finished with value: 0.6275044157901222 and parameters: {'subsample': 0.5420606625212961, 'learning_rate': 0.018319064135809617, 'dropout_rate': 0.3312179790226355, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 0.017289191017379774, 'min_weight_fraction_leaf': 0.2368022589799896, 'max_features': 'sqrt', 'min_impurity_decrease': 4.941106122111233e-07, 'validation_fraction': 0.7618939807885664, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:00:46,894] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.5922191157066728, 'learning_rate': 0.017442858716414014, 'dropout_rate': 0.3280178810362676, 'n_estimators': 137, 'criterion': 'squared_error', 'ccp_alpha': 0.3667438715407871, 'min_weight_fraction_leaf': 0.19573629323082295, 'max_features': 'sqrt', 'min_impurity_decrease': 5.391394394336536e-07, 'validation_fraction': 0.6858072881143848, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:01:42,301] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.48392926174632367, 'learning_rate': 0.04244875829612528, 'dropout_rate': 0.3644612457920643, 'n_estimators': 225, 'criterion': 'squared_error', 'ccp_alpha': 0.8992306864937782, 'min_weight_fraction_leaf': 0.2385628804937077, 'max_features': 'sqrt', 'min_impurity_decrease': 3.55046666349273e-07, 'validation_fraction': 0.6309388168212643, 'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:01:48,821] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.5415215192588256, 'learning_rate': 0.032278253162939315, 'dropout_rate': 0.2844754557689118, 'n_estimators': 60, 'criterion': 'squared_error', 'ccp_alpha': 1.407601455379467, 'min_weight_fraction_leaf': 0.2510619510668375, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00014974488025406402, 'validation_fraction': 0.7825933436627104, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:02:19,731] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.6358167678362362, 'learning_rate': 0.052737313658130634, 'dropout_rate': 0.4387694424787056, 'n_estimators': 188, 'criterion': 'squared_error', 'ccp_alpha': 2.352310671798754, 'min_weight_fraction_leaf': 0.4545757099622538, 'max_features': None, 'min_impurity_decrease': 1.818488684973112e-07, 'validation_fraction': 0.5736474971004745, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 13}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:03:22,610] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.5249117222273245, 'learning_rate': 0.02490094836729529, 'dropout_rate': 0.3029637523703682, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.761492090851228, 'min_weight_fraction_leaf': 0.4129240385085172, 'max_features': 1, 'min_impurity_decrease': 7.239759479397451e-07, 'validation_fraction': 0.845785642913146, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:03:43,351] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.4231153746657399, 'learning_rate': 0.08902302640166725, 'dropout_rate': 0.40768620718532717, 'n_estimators': 166, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2840361129928317, 'min_weight_fraction_leaf': 0.1815547729555989, 'max_features': 'sqrt', 'min_impurity_decrease': 2.2923196091933695e-06, 'validation_fraction': 0.7183772506352457, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 12}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.5680851063829787
Fold 4 C-index: 0.6863117870722434
Fold 5 C-index: 0.5643776824034334
[I 2024-04-13 18:03:48,752] Trial 70 finished with value: 0.6131109792873616 and parameters: {'subsample': 0.33926313482601156, 'learning_rate': 0.019557263454050858, 'dropout_rate': 0.49890266623764207, 'n_estimators': 82, 'criterion': 'squared_error', 'ccp_alpha': 0.010011659094920826, 'min_weight_fraction_leaf': 0.2259853620596431, 'max_features': 0.1, 'min_impurity_decrease': 1.094279318090133e-06, 'validation_fraction': 0.6723348434604305, 'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.6155378486055777
Fold 2 C-index: 0.6337209302325582
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.5793991416309013
[I 2024-04-13 18:04:02,355] Trial 71 finished with value: 0.6343473918763494 and parameters: {'subsample': 0.37769079309242687, 'learning_rate': 0.00898995266126416, 'dropout_rate': 0.18684567840646416, 'n_estimators': 111, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.2872834031528035, 'max_features': 'sqrt', 'min_impurity_decrease': 2.080456918420355e-07, 'validation_fraction': 0.7690867806326959, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:04:16,280] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.37701900413921136, 'learning_rate': 0.016833919347681435, 'dropout_rate': 0.18636370764084237, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 0.6310212945452622, 'min_weight_fraction_leaf': 0.2884483320093426, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0402177319970213e-07, 'validation_fraction': 0.7660591402491591, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:04:34,521] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.5806779434269143, 'learning_rate': 0.009384484820913017, 'dropout_rate': 0.2682030763817523, 'n_estimators': 135, 'criterion': 'squared_error', 'ccp_alpha': 0.3563872779387915, 'min_weight_fraction_leaf': 0.259787767977606, 'max_features': 'sqrt', 'min_impurity_decrease': 4.1043899443022785e-07, 'validation_fraction': 0.8108999742101972, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 9}. Best is trial 57 with value: 0.6424069440095804.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:04:53,117] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.6195349553052544, 'learning_rate': 0.01136765941654159, 'dropout_rate': 0.12372380197953392, 'n_estimators': 99, 'criterion': 'squared_error', 'ccp_alpha': 1.1402294929472836, 'min_weight_fraction_leaf': 0.37161644050250525, 'max_features': 'log2', 'min_impurity_decrease': 1.932478849268343e-07, 'validation_fraction': 0.7239713755732545, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5278884462151394
Fold 2 C-index: 0.5872093023255814
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.5722433460076045
Fold 5 C-index: 0.5493562231759657
[I 2024-04-13 18:05:14,279] Trial 75 finished with value: 0.5681905273746455 and parameters: {'subsample': 0.481615373319732, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.3420562942089014, 'n_estimators': 159, 'criterion': 'squared_error', 'ccp_alpha': 0.008766214931211122, 'min_weight_fraction_leaf': 0.47835629989654377, 'max_features': 'sqrt', 'min_impurity_decrease': 5.88233573662372e-07, 'validation_fraction': 0.8876968664466519, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:05:43,891] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.5506572145582509, 'learning_rate': 0.005104240606853081, 'dropout_rate': 0.19147377223567788, 'n_estimators': 146, 'criterion': 'squared_error', 'ccp_alpha': 0.6753331414033272, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'sqrt', 'min_impurity_decrease': 1.568348033519598e-07, 'validation_fraction': 0.6381650425348908, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:05:50,149] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.256547470779639, 'learning_rate': 0.02789039050974412, 'dropout_rate': 0.2363063686780326, 'n_estimators': 69, 'criterion': 'squared_error', 'ccp_alpha': 0.32932872552363307, 'min_weight_fraction_leaf': 0.34020173052241, 'max_features': 'sqrt', 'min_impurity_decrease': 3.0905215746242485e-07, 'validation_fraction': 0.8500050308736237, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 12}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:05:54,560] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.17121169705944425, 'learning_rate': 0.022303437932065042, 'dropout_rate': 0.16630563053057534, 'n_estimators': 52, 'criterion': 'squared_error', 'ccp_alpha': 0.9868372140949613, 'min_weight_fraction_leaf': 0.28173667841308647, 'max_features': None, 'min_impurity_decrease': 1.436695348567125e-06, 'validation_fraction': 0.7954229312058925, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:05:58,675] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.6599350427093886, 'learning_rate': 0.013036654559152646, 'dropout_rate': 0.8831816560103296, 'n_estimators': 93, 'criterion': 'squared_error', 'ccp_alpha': 1.6751129651593017, 'min_weight_fraction_leaf': 0.441581660587461, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.7645264662223318, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:06:37,983] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.29977879304875465, 'learning_rate': 0.006859503090223374, 'dropout_rate': 0.3089173374536066, 'n_estimators': 202, 'criterion': 'friedman_mse', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.20378735965998926, 'max_features': 1, 'min_impurity_decrease': 5.0310685705020145e-06, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 18:06:51,195] Trial 81 finished with value: 0.6360661153873227 and parameters: {'subsample': 0.4294410193691395, 'learning_rate': 0.010148818964253115, 'dropout_rate': 0.23189880344496897, 'n_estimators': 114, 'criterion': 'squared_error', 'ccp_alpha': 0.025429683198128432, 'min_weight_fraction_leaf': 0.30380613582651383, 'max_features': 'sqrt', 'min_impurity_decrease': 2.4552322822660376e-07, 'validation_fraction': 0.7348375063409944, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:07:04,542] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.41270161792979404, 'learning_rate': 0.02035005618998148, 'dropout_rate': 0.2741217489218166, 'n_estimators': 114, 'criterion': 'squared_error', 'ccp_alpha': 0.243253320453856, 'min_weight_fraction_leaf': 0.2674089734554558, 'max_features': 'sqrt', 'min_impurity_decrease': 4.57052340801651e-07, 'validation_fraction': 0.6937562552377796, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:07:35,801] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.5052537047036201, 'learning_rate': 0.010871661810425969, 'dropout_rate': 0.21433250003236387, 'n_estimators': 180, 'criterion': 'squared_error', 'ccp_alpha': 0.6352435481431712, 'min_weight_fraction_leaf': 0.24349664772118904, 'max_features': 'sqrt', 'min_impurity_decrease': 8.314878942494555e-07, 'validation_fraction': 0.6632105320618724, 'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:07:59,018] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.46801301624877634, 'learning_rate': 0.007281884918593935, 'dropout_rate': 0.386804997704391, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 0.2606549578206887, 'min_weight_fraction_leaf': 0.2996691407738805, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5246790132091148e-07, 'validation_fraction': 0.818415857489097, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6180257510729614
[I 2024-04-13 18:08:18,988] Trial 85 finished with value: 0.6408591126992382 and parameters: {'subsample': 0.5964612356115859, 'learning_rate': 0.015720448140553796, 'dropout_rate': 0.13380585132498796, 'n_estimators': 123, 'criterion': 'squared_error', 'ccp_alpha': 0.011079581402843635, 'min_weight_fraction_leaf': 0.3295331769680571, 'max_features': 'sqrt', 'min_impurity_decrease': 3.208077039170617e-07, 'validation_fraction': 0.919249699407904, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 11}. Best is trial 57 with value: 0.6424069440095804.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:08:41,645] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.3685613574811818, 'learning_rate': 0.014486753241218515, 'dropout_rate': 0.11824930345826798, 'n_estimators': 125, 'criterion': 'squared_error', 'ccp_alpha': 0.6245182410574106, 'min_weight_fraction_leaf': 0.35109736831509497, 'max_features': 'sqrt', 'min_impurity_decrease': 2.86238317813556e-07, 'validation_fraction': 0.7634725122712285, 'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 11}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:08:43,961] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.6044611085530311, 'learning_rate': 0.01765378612903628, 'dropout_rate': 0.1306535468432557, 'n_estimators': 29, 'criterion': 'squared_error', 'ccp_alpha': 3.8278844875001683, 'min_weight_fraction_leaf': 0.3290577310546589, 'max_features': 'sqrt', 'min_impurity_decrease': 1.3023259584270306e-07, 'validation_fraction': 0.7251193103463489, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:08:53,543] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.7305989887750208, 'learning_rate': 0.07565138947019595, 'dropout_rate': 0.16203184683029326, 'n_estimators': 76, 'criterion': 'squared_error', 'ccp_alpha': 0.8448837855218826, 'min_weight_fraction_leaf': 0.3098036049135862, 'max_features': 'sqrt', 'min_impurity_decrease': 2.1424217279362014e-07, 'validation_fraction': 0.8675111855922717, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:09:06,897] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.5376836855244629, 'learning_rate': 0.0401442321523931, 'dropout_rate': 0.24626353925068137, 'n_estimators': 101, 'criterion': 'squared_error', 'ccp_alpha': 6.012071113382355, 'min_weight_fraction_leaf': 0.3790584148504035, 'max_features': 'sqrt', 'min_impurity_decrease': 5.180798001423693e-07, 'validation_fraction': 0.6163739621016452, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:09:29,801] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.5603501314738726, 'learning_rate': 0.07155480696569975, 'dropout_rate': 0.19017023137156536, 'n_estimators': 129, 'criterion': 'squared_error', 'ccp_alpha': 0.25113716915357387, 'min_weight_fraction_leaf': 0.29008477768989605, 'max_features': 'log2', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8289185301981673, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 12}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 18:10:00,185] Trial 91 finished with value: 0.6369144725686089 and parameters: {'subsample': 0.5200014916305844, 'learning_rate': 0.004782889478178922, 'dropout_rate': 0.14625013043369223, 'n_estimators': 149, 'criterion': 'squared_error', 'ccp_alpha': 0.037948504220536555, 'min_weight_fraction_leaf': 0.32163517901334265, 'max_features': 0.1, 'min_impurity_decrease': 4.203506068959824e-07, 'validation_fraction': 0.928897907788923, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:10:19,009] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.516333042411373, 'learning_rate': 0.0032327242416098677, 'dropout_rate': 0.10130537225057253, 'n_estimators': 113, 'criterion': 'squared_error', 'ccp_alpha': 0.4942608677057209, 'min_weight_fraction_leaf': 0.31821001183548514, 'max_features': 0.1, 'min_impurity_decrease': 3.888780909297809e-07, 'validation_fraction': 0.9024177997549866, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5677290836653387
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 18:10:46,882] Trial 93 finished with value: 0.6306456063981358 and parameters: {'subsample': 0.4359031361693476, 'learning_rate': 0.004895517972361572, 'dropout_rate': 0.1441526685325705, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 0.047810054628039236, 'min_weight_fraction_leaf': 0.36100788200483613, 'max_features': 0.1, 'min_impurity_decrease': 7.26101398801591e-07, 'validation_fraction': 0.917180608138582, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:11:11,225] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.43676774220572834, 'learning_rate': 0.0014283823252091835, 'dropout_rate': 0.14353500981177236, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 0.23509570298593757, 'min_weight_fraction_leaf': 0.35954699845952287, 'max_features': 0.1, 'min_impurity_decrease': 9.183247049719965e-07, 'validation_fraction': 0.9236151177312523, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:11:20,149] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.5903496783457474, 'learning_rate': 0.005099830953329844, 'dropout_rate': 0.162877773773529, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 1.2276086602633303, 'min_weight_fraction_leaf': 0.29823606696595584, 'max_features': 0.1, 'min_impurity_decrease': 1.9705823014691884e-06, 'validation_fraction': 0.6868552600932708, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:11:50,942] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.48032209804466314, 'learning_rate': 0.009204991859439446, 'dropout_rate': 0.22878123115737428, 'n_estimators': 176, 'criterion': 'squared_error', 'ccp_alpha': 0.49661607876323316, 'min_weight_fraction_leaf': 0.335851906616388, 'max_features': 0.1, 'min_impurity_decrease': 6.786376565092662e-07, 'validation_fraction': 0.1680801488969631, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.5234042553191489
Fold 4 C-index: 0.5532319391634981
Fold 5 C-index: 0.5
[I 2024-04-13 18:12:13,251] Trial 97 finished with value: 0.5331566962608705 and parameters: {'subsample': 0.35982713220118606, 'learning_rate': 0.012532616836197621, 'dropout_rate': 0.2558374395640585, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.16939533233444498, 'min_weight_fraction_leaf': 0.22889025888481507, 'max_features': 0.1, 'min_impurity_decrease': 1.3919863121994274e-06, 'validation_fraction': 0.42127972174310685, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 57 with value: 0.6424069440095804.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:12:24,956] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.3929305772442687, 'learning_rate': 0.006887776697371318, 'dropout_rate': 0.19837547852725088, 'n_estimators': 102, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9847646950448454, 'min_weight_fraction_leaf': 0.2740519671350756, 'max_features': 0.1, 'min_impurity_decrease': 3.145177514431871e-06, 'validation_fraction': 0.9698443216047068, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.6330798479087453

[I 2024-04-13 18:12:37,334] A new study created in memory with name: no-name-ae3b0681-5e9c-4af0-bcc1-ab07312b3384

Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 18:12:37,234] Trial 99 finished with value: 0.6324701656733438 and parameters: {'subsample': 0.5315382628188576, 'learning_rate': 0.06087517452189459, 'dropout_rate': 0.3597460411167791, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 0.004509101673084638, 'min_weight_fraction_leaf': 0.3464439813387543, 'max_features': 0.1, 'min_impurity_decrease': 0.006030292379694477, 'validation_fraction': 0.5851189485426918, 'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.


* Best trial for C-index:
 FrozenTrial(number=57, state=TrialState.COMPLETE, values=[0.6424069440095804], datetime_start=datetime.datetime(2024, 4, 13, 17, 58, 51, 211610), datetime_complete=datetime.datetime(2024, 4, 13, 17, 59, 1, 250126), params={'subsample': 0.569175138136116, 'learning_rate': 0.09542136158814303, 'dropout_rate': 0.43613571687055647, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.0019473494055538935, 'min_weight_fraction_leaf': 0.36743918461462793, 'max_features': 'sqrt', 'min_impurity_decrease': 5.255459802548745e-07, 'validation_fraction': 0.7087056989518657, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 20}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=57, value=None)


* Best Score for C-index:
 0.6424069440095804

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:13:38,800] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:14:12,728] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:14:46,159] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 18:15:39,062] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:16:01,703] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:16:06,762] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:16:56,245] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:17:11,034] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:17:12,983] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.2468985899268434
Fold 2 IBS: 0.23174237938551043
Fold 3 IBS: 0.22871218710228966
Fold 4 IBS: 0.24178909744475294
Fold 5 IBS: 0.22900564758396305
[I 2024-04-13 18:19:31,699] Trial 9 finished with value: 0.23562958028867192 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24711653291675975
Fold 2 IBS: 0.23202162954629
Fold 3 IBS: 0.2289556964425975
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293716647928885
[I 2024-04-13 18:22:57,833] Trial 10 finished with value: 0.23588805903156138 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 18:27:22,140] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24719666836842055
Fold 2 IBS: 0.23199892761841134
Fold 3 IBS: 0.2289405059322678
Fold 4 IBS: 0.24195423740028718
Fold 5 IBS: 0.22934315929810337
[I 2024-04-13 18:30:35,126] Trial 12 finished with value: 0.23588669972349807 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:32:17,507] Trial 13 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:34:28,353] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:36:19,360] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 18:37:31,271] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 18:40:22,972] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:43:54,709] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 18:44:03,612] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:45:18,201] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:48:03,042] Trial 21 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24675967400526397
Fold 2 IBS: 0.23120128338106113

Fold 3 IBS: 0.22848569735194738
Fold 4 IBS: 0.24150141767716396
Fold 5 IBS: 0.22845766625525668
[I 2024-04-13 18:50:34,246] Trial 22 finished with value: 0.23528114773413863 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:52:31,677] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-13 18:54:17,957] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 18:55:23,370] Trial 25 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 18:57:45,548] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:00:20,081] Trial 27 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:02:25,071] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:04:04,211] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 19:05:43,786] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24723811107199292
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:09:00,431] Trial 31 finished with value: 0.23592604563741132 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 19:12:06,362] Trial 32 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:14:09,046] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:17:12,562] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:17:48,549] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:21:12,859] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:21:17,883] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:22:28,869] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 19:24:25,057] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:27:34,243] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.2472010209971281
Fold 2 IBS: 0.23197319933729893
Fold 3 IBS: 0.22887452934644678
Fold 4 IBS: 0.24191861956639799
Fold 5 IBS: 0.2293015642651888
[I 2024-04-13 19:27:35,020] Trial 41 finished with value: 0.23585378670249213 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.2459047520616606
Fold 2 IBS: 0.23020388607917422
Fold 3 IBS: 0.22657568837307415
Fold 4 IBS: 0.24022980115273948
Fold 5 IBS: 0.22694242307333995
[I 2024-04-13 19:27:56,336] Trial 42 finished with value: 0.2339713101479977 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:27:57,887] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8735505723796891, 'learning_rate': 0.013455915558851193, 'dropout_rate': 0.11585930219083569, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 1.1546454041172216, 'min_weight_fraction_leaf': 0.4571018098895751, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8650432234384267, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:28:52,987] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9479336661285427, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.25335630680617827, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.4126953497238681, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.9438667820963776, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24678393645753394
Fold 2 IBS: 0.23045362112354736
Fold 3 IBS: 0.22798640772703402
Fold 4 IBS: 0.24133177588235574
Fold 5 IBS: 0.22819468131537443
[I 2024-04-13 19:29:12,684] Trial 45 finished with value: 0.2349500845011691 and parameters: {'subsample': 0.5852424762732177, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.027804703729289008, 'min_weight_fraction_leaf': 0.262143273989599, 'max_features': 0.1, 'min_impurity_decrease': 9.467252666446998e-07, 'validation_fraction': 0.7243304021069044, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:29:17,468] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.0647255784094387, 'dropout_rate': 0.9694253886674298, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 1.980441868470768, 'min_weight_fraction_leaf': 0.3747732962598691, 'max_features': 0.1, 'min_impurity_decrease': 2.6164901943280044e-07, 'validation_fraction': 0.7149599360255287, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:29:46,628] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.45583884600027197, 'learning_rate': 0.06333641179361332, 'dropout_rate': 0.19790330487666663, 'n_estimators': 172, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.3462595663974316, 'max_features': 0.1, 'min_impurity_decrease': 9.138461248752069e-07, 'validation_fraction': 0.6499098781754827, 'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:29:56,719] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.584713932884162, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.10579627176846597, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 0.443834316760607, 'min_weight_fraction_leaf': 0.26066789839492466, 'max_features': 0.1, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.5884862057231304, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 19:29:57,693] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5232490206634685, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 9, 'criterion': 'friedman_mse', 'ccp_alpha': 1.370081088125734, 'min_weight_fraction_leaf': 0.3097478284829108, 'max_features': 0.1, 'min_impurity_decrease': 2.368978679128857e-06, 'validation_fraction': 0.8421492954769574, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 19:30:00,710] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.07076395585024155, 'dropout_rate': 0.14893065487391582, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 1.7468603849227415, 'min_weight_fraction_leaf': 0.4771102452497172, 'max_features': 'log2', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.6959936026682685, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24710183923742374
Fold 2 IBS: 0.23175516862597736
Fold 3 IBS: 0.22872726460533319
Fold 4 IBS: 0.24175918635636237
Fold 5 IBS: 0.22914324520488263
[I 2024-04-13 19:30:20,146] Trial 51 finished with value: 0.23569734080599586 and parameters: {'subsample': 0.7946888792311653, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.2196446942108301, 'n_estimators': 129, 'criterion': 'squared_error', 'ccp_alpha': 0.012243801070742757, 'min_weight_fraction_leaf': 0.22002902120871776, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0321764873923598e-06, 'validation_fraction': 0.8872414026388215, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.2467504042903887
Fold 2 IBS: 0.23152649383902565
Fold 3 IBS: 0.2284064999332893
Fold 4 IBS: 0.2415574346408676
Fold 5 IBS: 0.22865959236570862
[I 2024-04-13 19:30:34,511] Trial 52 finished with value: 0.23538008501385596 and parameters: {'subsample': 0.7293363088819711, 'learning_rate': 0.021613492744160495, 'dropout_rate': 0.21988140341808987, 'n_estimators': 109, 'criterion': 'squared_error', 'ccp_alpha': 0.03659945835027755, 'min_weight_fraction_leaf': 0.21454208459463384, 'max_features': 'sqrt', 'min_impurity_decrease': 4.968003047339178e-07, 'validation_fraction': 0.7452334109475507, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:30:50,277] Trial 53 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7286313887376499, 'learning_rate': 0.057410108721501936, 'dropout_rate': 0.285096973056326, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.4512041233232864, 'min_weight_fraction_leaf': 0.2260580293041923, 'max_features': 'sqrt', 'min_impurity_decrease': 9.58735442301899e-07, 'validation_fraction': 0.810021403108459, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:31:05,340] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6569229035185145, 'learning_rate': 0.04372807230380943, 'dropout_rate': 0.21137526606647042, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 1.035069386526868, 'min_weight_fraction_leaf': 0.15200254659099177, 'max_features': 'sqrt', 'min_impurity_decrease': 3.9827268139860795e-07, 'validation_fraction': 0.7420090012406269, 'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:31:32,346] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.804828042321909, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.23926982708415356, 'n_estimators': 162, 'criterion': 'squared_error', 'ccp_alpha': 0.40074886285106287, 'min_weight_fraction_leaf': 0.2779066644542128, 'max_features': 'sqrt', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:32:11,383] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6106355356441384, 'learning_rate': 0.0175381503002972, 'dropout_rate': 0.1840399348615831, 'n_estimators': 188, 'criterion': 'squared_error', 'ccp_alpha': 1.2616701535027603, 'min_weight_fraction_leaf': 0.21267322167989086, 'max_features': 'sqrt', 'min_impurity_decrease': 4.6036201699627165e-06, 'validation_fraction': 0.6710340937437342, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:32:16,782] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7251306188899954, 'learning_rate': 0.031631325965124225, 'dropout_rate': 0.36858678707018233, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.8632300312068857, 'min_weight_fraction_leaf': 0.25226351016663784, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8530056448822852e-06, 'validation_fraction': 0.6117070368402964, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 20}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.2456293079267213
Fold 2 IBS: 0.23038922499302464
Fold 3 IBS: 0.22713476978355554
Fold 4 IBS: 0.24079478344550373
Fold 5 IBS: 0.22706044770206701
[I 2024-04-13 19:32:38,104] Trial 58 finished with value: 0.23420170677017443 and parameters: {'subsample': 0.8372135933826973, 'learning_rate': 0.0933118263896949, 'dropout_rate': 0.2698372192490325, 'n_estimators': 138, 'criterion': 'squared_error', 'ccp_alpha': 0.03851666886580376, 'min_weight_fraction_leaf': 0.19014956845126402, 'max_features': 'sqrt', 'min_impurity_decrease': 5.557667048245938e-07, 'validation_fraction': 0.8240957175887902, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:33:21,739] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8351680604992443, 'learning_rate': 0.09222489059205219, 'dropout_rate': 0.32342587723509275, 'n_estimators': 216, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.20200402270044698, 'max_features': None, 'min_impurity_decrease': 5.478860708687417e-07, 'validation_fraction': 0.7661283095999878, 'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:33:41,544] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9139271726204243, 'learning_rate': 0.09814896745797415, 'dropout_rate': 0.2791298710059678, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.7777615027127565, 'min_weight_fraction_leaf': 0.18715715168296215, 'max_features': 'sqrt', 'min_impurity_decrease': 2.755622066697515e-07, 'validation_fraction': 0.8258586719391796, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 10}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:33:51,660] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7785463441250284, 'learning_rate': 0.08303647143365385, 'dropout_rate': 0.22635143149642775, 'n_estimators': 90, 'criterion': 'squared_error', 'ccp_alpha': 0.3409580267399826, 'min_weight_fraction_leaf': 0.13431472354808824, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1489427281229002e-06, 'validation_fraction': 0.7271755608042784, 'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24566332108161124
Fold 2 IBS: 0.2296487832881736
Fold 3 IBS: 0.22657619429377132
Fold 4 IBS: 0.2401398958324181
Fold 5 IBS: 0.22612790182462805
[I 2024-04-13 19:34:09,263] Trial 62 finished with value: 0.23363121926412048 and parameters: {'subsample': 0.8243414389621114, 'learning_rate': 0.09071124103540035, 'dropout_rate': 0.27251764057548483, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.022616672247981386, 'min_weight_fraction_leaf': 0.2309588671101351, 'max_features': 'sqrt', 'min_impurity_decrease': 5.801680351688828e-07, 'validation_fraction': 0.7943107726663929, 'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 62 with value: 0.23363121926412048.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 19:34:20,915] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8543251428514922, 'learning_rate': 0.09031916747519456, 'dropout_rate': 0.4465947499448344, 'n_estimators': 113, 'criterion': 'squared_error', 'ccp_alpha': 0.31975094212728505, 'min_weight_fraction_leaf': 0.2681954377550372, 'max_features': 'sqrt', 'min_impurity_decrease': 5.414928507269899e-07, 'validation_fraction': 0.7758979815787878, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 62 with value: 0.23363121926412048.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:34:55,020] Trial 64 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8301134299030771, 'learning_rate': 0.089407762408853, 'dropout_rate': 0.2603466948459836, 'n_estimators': 184, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.1898937646969936, 'max_features': 'sqrt', 'min_impurity_decrease': 1.69586486321652e-07, 'validation_fraction': 0.7972553997617144, 'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 62 with value: 0.23363121926412048.
Fold 1 IBS: 0.245287081913879
Fold 2 IBS: 0.2284909088203171
Fold 3 IBS: 0.22546650692785086
Fold 4 IBS: 0.2392357717231768
Fold 5 IBS: 0.2267792173870292
[I 2024-04-13 19:35:21,785] Trial 65 finished with value: 0.2330518973544506 and parameters: {'subsample': 0.7342676747848801, 'learning_rate': 0.09901078905928126, 'dropout_rate': 0.18564802790799603, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 0.0027779871092218425, 'min_weight_fraction_leaf': 0.23644250991622312, 'max_features': 1, 'min_impurity_decrease': 2.467126073460528e-06, 'validation_fraction': 0.6850220941695035, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.2289818680697771
Fold 4 IBS: 0.24197477145927113

Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 19:35:48,099] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7279386202897999, 'learning_rate': 0.09984676062907398, 'dropout_rate': 0.12777796849617917, 'n_estimators': 154, 'criterion': 'squared_error', 'ccp_alpha': 1.4111498627316026, 'min_weight_fraction_leaf': 0.23517339076530247, 'max_features': 1, 'min_impurity_decrease': 0.00014974488025406402, 'validation_fraction': 0.6772907402354433, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:35:51,943] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8919877355885673, 'learning_rate': 0.08526801927485488, 'dropout_rate': 0.1968183597819077, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 2.319190851430798, 'min_weight_fraction_leaf': 0.15676195463630516, 'max_features': 1, 'min_impurity_decrease': 2.2029012366645964e-06, 'validation_fraction': 0.8599691724113316, 'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:36:50,559] Trial 68 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6777349272083631, 'learning_rate': 0.09580178908012703, 'dropout_rate': 0.17115105391870955, 'n_estimators': 231, 'criterion': 'squared_error', 'ccp_alpha': 1.05959995392391, 'min_weight_fraction_leaf': 0.09188917533116, 'max_features': 1, 'min_impurity_decrease': 6.249998507081008e-07, 'validation_fraction': 0.8273349120190413, 'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 19:37:18,569] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7597991740864205, 'learning_rate': 0.08587936719454789, 'dropout_rate': 0.3768812120719428, 'n_estimators': 171, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2840361129928317, 'min_weight_fraction_leaf': 0.18119508212683702, 'max_features': 1, 'min_impurity_decrease': 3.259077755824971e-06, 'validation_fraction': 0.5558704457196845, 'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.2457156227613367
Fold 2 IBS: 0.2288747857381832
Fold 3 IBS: 0.225909093321197
Fold 4 IBS: 0.23949137658530797
Fold 5 IBS: 0.22670374234424326
[I 2024-04-13 19:37:29,929] Trial 70 finished with value: 0.23333892415005364 and parameters: {'subsample': 0.9323981201987828, 'learning_rate': 0.07861759448846455, 'dropout_rate': 0.12174461012962215, 'n_estimators': 89, 'criterion': 'squared_error', 'ccp_alpha': 0.010268271623930566, 'min_weight_fraction_leaf': 0.29906629929043166, 'max_features': 0.1, 'min_impurity_decrease': 1.3730886680414553e-06, 'validation_fraction': 0.7403543339118751, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.2460308029540508
Fold 2 IBS: 0.23075747711272837
Fold 3 IBS: 0.22719882472016173
Fold 4 IBS: 0.24096869520763853
Fold 5 IBS: 0.22665684264377603
[I 2024-04-13 19:37:55,473] Trial 71 finished with value: 0.2343225285276711 and parameters: {'subsample': 0.942796279417179, 'learning_rate': 0.07656513395335908, 'dropout_rate': 0.12688691191107251, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.30325824379899113, 'max_features': 0.1, 'min_impurity_decrease': 1.7123721653367992e-06, 'validation_fraction': 0.7399374904297116, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-13 19:38:08,959] Trial 72 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.958795520357544, 'learning_rate': 0.07365043020696545, 'dropout_rate': 0.12090349350270674, 'n_estimators': 86, 'criterion': 'squared_error', 'ccp_alpha': 0.739835755767842, 'min_weight_fraction_leaf': 0.29749032069002146, 'max_features': 0.1, 'min_impurity_decrease': 1.3599018494932217e-06, 'validation_fraction': 0.7791089756643332, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:39:28,018] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9298981705927085, 'learning_rate': 0.08058367392340021, 'dropout_rate': 0.16799910589376849, 'n_estimators': 271, 'criterion': 'squared_error', 'ccp_alpha': 0.3563872779387915, 'min_weight_fraction_leaf': 0.3350043101424622, 'max_features': 0.1, 'min_impurity_decrease': 5.28840107794154e-06, 'validation_fraction': 0.7118987767425609, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 19:39:53,681] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8916344680923031, 'learning_rate': 0.08793435060481841, 'dropout_rate': 0.10110413499313342, 'n_estimators': 142, 'criterion': 'squared_error', 'ccp_alpha': 0.955935636717823, 'min_weight_fraction_leaf': 0.3070562089185398, 'max_features': 0.1, 'min_impurity_decrease': 1.6710911545904498e-05, 'validation_fraction': 0.9115868102366969, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 12}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24452621315746922
Fold 2 IBS: 0.22810872891299785
Fold 3 IBS: 0.2241439542595457
Fold 4 IBS: 0.23949321798155498
Fold 5 IBS: 0.2257119410390271
[I 2024-04-13 19:40:22,155] Trial 75 finished with value: 0.23239681107011897 and parameters: {'subsample': 0.9998829056403309, 'learning_rate': 0.09420039979456486, 'dropout_rate': 0.1333613034046263, 'n_estimators': 141, 'criterion': 'squared_error', 'ccp_alpha': 0.008911991304216094, 'min_weight_fraction_leaf': 0.2444025476799629, 'max_features': 0.1, 'min_impurity_decrease': 2.4912576060277585e-06, 'validation_fraction': 0.6909543967814417, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:40:31,981] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9458222668472541, 'learning_rate': 0.07906848506975149, 'dropout_rate': 0.14266874960530737, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.6031748128205076, 'min_weight_fraction_leaf': 0.2411911402976509, 'max_features': 0.1, 'min_impurity_decrease': 2.563792903899382e-06, 'validation_fraction': 0.6884030004704251, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:40:54,937] Trial 77 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9912462777341369, 'learning_rate': 0.09452937387896818, 'dropout_rate': 0.13177704633811047, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 1.5888723787914292, 'min_weight_fraction_leaf': 0.2769591062921376, 'max_features': 0.1, 'min_impurity_decrease': 9.102476550268499e-06, 'validation_fraction': 0.6136526230702399, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 75 with value: 0.23239681107011897.

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:41:33,895] Trial 78 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9982285661999424, 'learning_rate': 0.09191504218778693, 'dropout_rate': 0.15698726385072695, 'n_estimators': 197, 'criterion': 'squared_error', 'ccp_alpha': 0.24807516981478814, 'min_weight_fraction_leaf': 0.20156232220196313, 'max_features': 0.1, 'min_impurity_decrease': 1.657879625668623e-05, 'validation_fraction': 0.743279291715464, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 11}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24690614034739003
Fold 2 IBS: 0.23156150181893284
Fold 3 IBS: 0.22844484931909595
Fold 4 IBS: 0.24167312234765576
Fold 5 IBS: 0.22876368497640898
[I 2024-04-13 19:41:39,209] Trial 79 finished with value: 0.23546985976189672 and parameters: {'subsample': 0.8578713422305235, 'learning_rate': 0.0970337469468135, 'dropout_rate': 0.8831816560103296, 'n_estimators': 120, 'criterion': 'squared_error', 'ccp_alpha': 0.00580501385319391, 'min_weight_fraction_leaf': 0.3274569717263011, 'max_features': 0.1, 'min_impurity_decrease': 1.7968062948599964e-06, 'validation_fraction': 0.567470377276655, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 14}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:41:44,573] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9640129259774958, 'learning_rate': 0.07781759349237542, 'dropout_rate': 0.684566586558272, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 0.7103134936897181, 'min_weight_fraction_leaf': 0.2530944848473559, 'max_features': 0.1, 'min_impurity_decrease': 4.17669457184032e-06, 'validation_fraction': 0.6634556365644301, 'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:42:07,450] Trial 81 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9095916255797919, 'learning_rate': 0.06970654000824406, 'dropout_rate': 0.18983665066947678, 'n_estimators': 161, 'criterion': 'squared_error', 'ccp_alpha': 0.23038409491076217, 'min_weight_fraction_leaf': 0.36124689664050524, 'max_features': 0.1, 'min_impurity_decrease': 7.661014914528512e-07, 'validation_fraction': 0.8089217409847281, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 12}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:59:30,856] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9338187920159751, 'learning_rate': 0.09334088664924992, 'dropout_rate': 0.16946680359086888, 'n_estimators': 139, 'criterion': 'squared_error', 'ccp_alpha': 0.528502047033471, 'min_weight_fraction_leaf': 0.22951409277417695, 'max_features': 'log2', 'min_impurity_decrease': 2.9556370206003056e-07, 'validation_fraction': 0.8432783558982909, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:59:35,483] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.883398032137881, 'learning_rate': 0.05042245528279666, 'dropout_rate': 0.12497508422054361, 'n_estimators': 76, 'criterion': 'squared_error', 'ccp_alpha': 0.19969398360318116, 'min_weight_fraction_leaf': 0.2656518803329823, 'max_features': 0.1, 'min_impurity_decrease': 1.4194947389027638e-06, 'validation_fraction': 0.633183021479895, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 19:59:53,658] Trial 84 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8552741665580803, 'learning_rate': 0.06709189419275205, 'dropout_rate': 0.23596409865551865, 'n_estimators': 177, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.2944874209342843, 'max_features': None, 'min_impurity_decrease': 7.691172257857441e-07, 'validation_fraction': 0.6968576998921013, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:11:22,074] Trial 85 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8223616874820779, 'learning_rate': 0.08843920709680371, 'dropout_rate': 0.10332840309562857, 'n_estimators': 98, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9490091297259651, 'min_weight_fraction_leaf': 0.24536912526579052, 'max_features': 0.1, 'min_impurity_decrease': 3.7435209342302184e-07, 'validation_fraction': 0.8704001971002521, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:11:49,059] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9096448812228937, 'learning_rate': 0.07363090940287254, 'dropout_rate': 0.1771840613769105, 'n_estimators': 199, 'criterion': 'squared_error', 'ccp_alpha': 1.2822592490338325, 'min_weight_fraction_leaf': 0.4080356436151848, 'max_features': 1, 'min_impurity_decrease': 3.0373401514275998e-06, 'validation_fraction': 0.49985049424795125, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.2466123733468312
Fold 2 IBS: 0.2308311526549613
Fold 3 IBS: 0.2278158354955089
Fold 4 IBS: 0.24119742239323982
Fold 5 IBS: 0.22757911535557646
[I 2024-04-13 20:11:51,642] Trial 87 finished with value: 0.23480717984922356 and parameters: {'subsample': 0.9651104076885627, 'learning_rate': 0.08682198289446316, 'dropout_rate': 0.26100822710445604, 'n_estimators': 52, 'criterion': 'squared_error', 'ccp_alpha': 0.017727608136126588, 'min_weight_fraction_leaf': 0.2841999178157146, 'max_features': 0.1, 'min_impurity_decrease': 1.0918108718029517e-06, 'validation_fraction': 0.7910600961676841, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:11:54,938] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9779973422636488, 'learning_rate': 0.08293741938674638, 'dropout_rate': 0.3068106697632987, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.5807061908097002, 'min_weight_fraction_leaf': 0.28610769971029604, 'max_features': 0.1, 'min_impurity_decrease': 0.08546129120562182, 'validation_fraction': 0.7618563886319779, 'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:11:56,579] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9483409389571185, 'learning_rate': 0.08684995291290751, 'dropout_rate': 0.261199231115212, 'n_estimators': 33, 'criterion': 'squared_error', 'ccp_alpha': 0.262026471967215, 'min_weight_fraction_leaf': 0.30628737845191195, 'max_features': 0.1, 'min_impurity_decrease': 6.315494653924259e-06, 'validation_fraction': 0.7881463591488752, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:12:08,538] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9683729112775776, 'learning_rate': 0.09017482809200965, 'dropout_rate': 0.3433400840232137, 'n_estimators': 130, 'criterion': 'squared_error', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.008931419075771496, 'max_features': 0.1, 'min_impurity_decrease': 1.8289805873296154e-06, 'validation_fraction': 0.7322157194498431, 'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:12:20,017] Trial 91 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9249680605301084, 'learning_rate': 0.09924448444168336, 'dropout_rate': 0.20864759543371797, 'n_estimators': 111, 'criterion': 'squared_error', 'ccp_alpha': 5.764943688998855, 'min_weight_fraction_leaf': 0.26522934614572513, 'max_features': 0.1, 'min_impurity_decrease': 1.0288742383976442e-06, 'validation_fraction': 0.8977628160008819, 'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.2451397278492685
Fold 2 IBS: 0.2300786103624261
Fold 3 IBS: 0.22666393768691476
Fold 4 IBS: 0.24040348182140334
Fold 5 IBS: 0.2268793016048305
[I 2024-04-13 20:12:26,015] Trial 92 finished with value: 0.23383301186496866 and parameters: {'subsample': 0.873531926988483, 'learning_rate': 0.061855558095227366, 'dropout_rate': 0.15093910401977667, 'n_estimators': 81, 'criterion': 'squared_error', 'ccp_alpha': 0.04541226279610616, 'min_weight_fraction_leaf': 0.33303097856460795, 'max_features': 'log2', 'min_impurity_decrease': 2.092935799209152e-07, 'validation_fraction': 0.8296323120743014, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24512293945752534
Fold 2 IBS: 0.23019011787590957
Fold 3 IBS: 0.22745233212008534
Fold 4 IBS: 0.2407062153709357
Fold 5 IBS: 0.22743511430929209
[I 2024-04-13 20:12:33,264] Trial 93 finished with value: 0.23418134382674963 and parameters: {'subsample': 0.8748499727077871, 'learning_rate': 0.061988251437343184, 'dropout_rate': 0.13470215178905942, 'n_estimators': 79, 'criterion': 'squared_error', 'ccp_alpha': 0.04707905003515399, 'min_weight_fraction_leaf': 0.3395270240874814, 'max_features': 'log2', 'min_impurity_decrease': 1.9022958194070687e-07, 'validation_fraction': 0.8312538979092482, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:12:39,611] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7897088889184067, 'learning_rate': 0.0614181390618931, 'dropout_rate': 0.14297431919224673, 'n_estimators': 82, 'criterion': 'squared_error', 'ccp_alpha': 0.4431921498459426, 'min_weight_fraction_leaf': 0.3709400302504709, 'max_features': 'log2', 'min_impurity_decrease': 2.0363582833272814e-07, 'validation_fraction': 0.8286157671013741, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:12:43,683] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8731203767321374, 'learning_rate': 0.05536040983667881, 'dropout_rate': 0.1240871979011556, 'n_estimators': 51, 'criterion': 'squared_error', 'ccp_alpha': 0.7753599411924459, 'min_weight_fraction_leaf': 0.33956869589479877, 'max_features': 'log2', 'min_impurity_decrease': 1.5672686530530854e-07, 'validation_fraction': 0.8067764812355601, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:12:45,448] Trial 96 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8504494801502642, 'learning_rate': 0.049177216429585946, 'dropout_rate': 0.16179906586528384, 'n_estimators': 25, 'criterion': 'squared_error', 'ccp_alpha': 0.2411230962228951, 'min_weight_fraction_leaf': 0.33128063878378733, 'max_features': 'log2', 'min_impurity_decrease': 1.3361955454797523e-07, 'validation_fraction': 0.18910891405175134, 'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 11}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:12:53,965] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9456655169820907, 'learning_rate': 0.09471262982827017, 'dropout_rate': 0.1384749743969657, 'n_estimators': 95, 'criterion': 'squared_error', 'ccp_alpha': 1.0633542811136496, 'min_weight_fraction_leaf': 0.31666557556149805, 'max_features': 'log2', 'min_impurity_decrease': 4.764875181793167e-07, 'validation_fraction': 0.7602248674870157, 'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:12:59,829] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8985855612192725, 'learning_rate': 0.04236620589530157, 'dropout_rate': 0.10133681434331297, 'n_estimators': 71, 'criterion': 'friedman_mse', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.3508714202084142, 'max_features': 'log2', 'min_impurity_decrease': 2.1425287177415118e-07, 'validation_fraction': 0.846288087406783, 'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24494631432468708
Fold 2 IBS: 0.228838334401351
Fold 3 IBS: 0.22532457276154536
Fold 4 IBS: 0.24000051436574654
Fold 5 IBS: 0.22609554166201715
[I 2024-04-13 20:13:11,311] Trial 99 finished with value: 0.23304105550306944 and parameters: {'subsample': 0.9788274478205877, 'learning_rate': 0.06087517452189459, 'dropout_rate': 0.18468364581870436, 'n_estimators': 106, 'criterion': 'squared_error', 'ccp_alpha': 0.004542076222843278, 'min_weight_fraction_leaf': 0.30062558075883816, 'max_features': 'log2', 'min_impurity_decrease': 3.1109850934465047e-07, 'validation_fraction': 0.8728143595545029, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 75 with value: 0.23239681107011897.


* Best trial for IBS:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.23239681107011897], datetime_start=datetime.datetime(2024, 4, 13, 19, 39, 53, 687644), datetime_complete=datetime.datetime(2024, 4, 13, 19, 40, 22, 154475), params={'subsample': 0.9998829056403309, 'learning_rate': 0.09420039979456486, 'dropout_rate': 0.1333613034046263, 'n_estimators': 141, 'criterion': 'squared_error', 'ccp_alpha': 0.008911991304216094, 'min_weight_fraction_leaf': 0.2444025476799629, 'max_features': 0.1, 'min_impurity_decrease': 2.4912576060277585e-06, 'validation_fraction': 0.6909543967814417, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 14}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for IBS:
 0.23239681107011897

In [70]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [71]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.642
train_ibs:  0.232

#### Test

In [72]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [73]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.0019473494055538935,
                                 criterion='squared_error',
                                 dropout_rate=0.43613571687055647,
                                 learning_rate=0.09542136158814303,
                                 max_depth=20, max_features='sqrt',
                                 max_leaf_nodes=20,
                                 min_impurity_decrease=5.255459802548745e-07,
                                 min_samples_leaf=15, min_samples_split=10,
                                 min_weight_fraction_leaf=0.36743918461462793,
                                 n_estimators=66, random_state=123,
                                 subsample=0.569175138136116,
                                 validation_fraction=0.7087056989518657)

C-index score: 0.669

GradientBoostingSurvivalAnalysis(ccp_alpha=0.008911991304216094,
                                 criterion='squared_error',
                                 dropout_rate=0.1333613034046263,
                                 learning_rate=0.09420039979456486,
                                 max_depth=14, max_features=0.1,
                                 max_leaf_nodes=19,
                                 min_impurity_decrease=2.4912576060277585e-06,
                                 min_samples_leaf=17, min_samples_split=7,
                                 min_weight_fraction_leaf=0.2444025476799629,
                                 n_estimators=141, random_state=123,
                                 subsample=0.9998829056403309,
                                 validation_fraction=0.6909543967814417)

IBS: 0.224

In [74]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [75]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [76]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 20:13:16,888] A new study created in memory with name: no-name-35a91697-7bed-48bc-b7a7-05c017d1b19a

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.501937984496124
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 20:13:19,991] Trial 0 finished with value: 0.559767342351139 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.559767342351139.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 20:13:42,875] Trial 1 finished with value: 0.5594249857365082 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.559767342351139.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.501937984496124
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 20:13:46,908] Trial 2 finished with value: 0.5749862355374666 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.5749862355374666.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:13:54,570] Trial 3 finished with value: 0.5814800541733564 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.5814800541733564.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:14:03,564] Trial 4 finished with value: 0.5872464675017527 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.5872464675017527.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.48643410852713176
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 20:14:14,567] Trial 5 finished with value: 0.5689900392265107 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.5872464675017527.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.48643410852713176
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 20:14:19,673] Trial 6 finished with value: 0.5566665671573405 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.5872464675017527.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.501937984496124
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:14:20,655] Trial 7 finished with value: 0.5824266813191127 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.5872464675017527.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 20:14:26,383] Trial 8 finished with value: 0.5742037364700918 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.5872464675017527.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.501937984496124
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:14:44,221] Trial 9 finished with value: 0.5807178156547657 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.5872464675017527.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 20:14:55,486] Trial 10 finished with value: 0.5986337412707516 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.5986337412707516.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 20:15:07,656] Trial 11 finished with value: 0.5985246289624812 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 10 with value: 0.5986337412707516.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 20:15:19,391] Trial 12 finished with value: 0.6024507172817068 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.6024507172817068.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.5321888412017167
[I 2024-04-13 20:15:34,779] Trial 13 finished with value: 0.5413955820290843 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.20904030306390659, 'n_estimators': 372, 'learning_rate': 0.007730532223257889}. Best is trial 12 with value: 0.6024507172817068.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:15:45,764] Trial 14 finished with value: 0.6064776215330693 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.28605856894907633, 'n_estimators': 309, 'learning_rate': 0.09964553963945819}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:15:58,672] Trial 15 finished with value: 0.5896910298427132 and parameters: {'subsample': 0.2913523637503245, 'dropout_rate': 0.2764445583790512, 'n_estimators': 355, 'learning_rate': 0.0994821444513409}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5174418604651163
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:16:13,872] Trial 16 finished with value: 0.5925881564871347 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.6585857848587966, 'n_estimators': 427, 'learning_rate': 0.08820363883892024}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:16:22,428] Trial 17 finished with value: 0.5848829510907351 and parameters: {'subsample': 0.39930407886471125, 'dropout_rate': 0.2588751280074848, 'n_estimators': 261, 'learning_rate': 0.09772435226236928}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:16:40,194] Trial 18 finished with value: 0.595616946180777 and parameters: {'subsample': 0.14033791495138467, 'dropout_rate': 0.3447914306565574, 'n_estimators': 428, 'learning_rate': 0.08431414303856807}. Best is trial 14 with value: 0.6064776215330693.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5058139534883721
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:16:42,354] Trial 19 finished with value: 0.5811290338880302 and parameters: {'subsample': 0.34314044045637715, 'dropout_rate': 0.6899537536342808, 'n_estimators': 106, 'learning_rate': 0.08294848495969458}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:16:59,615] Trial 20 finished with value: 0.5930736662113076 and parameters: {'subsample': 0.2628688080573812, 'dropout_rate': 0.19350037184585095, 'n_estimators': 415, 'learning_rate': 0.09794678439106413}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:17:10,358] Trial 21 finished with value: 0.5944429656829959 and parameters: {'subsample': 0.17280357806073138, 'dropout_rate': 0.12395834975058428, 'n_estimators': 315, 'learning_rate': 0.0016108337344105245}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5368217054263565
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 20:17:20,341] Trial 22 finished with value: 0.5992314346189507 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.10654253943742095, 'n_estimators': 295, 'learning_rate': 0.02287285135862388}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:17:27,751] Trial 23 finished with value: 0.5954572230324506 and parameters: {'subsample': 0.22005489424576896, 'dropout_rate': 0.2285163337344931, 'n_estimators': 247, 'learning_rate': 0.038399847397427314}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:17:37,243] Trial 24 finished with value: 0.6005125120112489 and parameters: {'subsample': 0.1003062325172735, 'dropout_rate': 0.30717265283127393, 'n_estimators': 290, 'learning_rate': 0.019745129742150442}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.5321888412017167
[I 2024-04-13 20:17:44,419] Trial 25 finished with value: 0.5413955820290843 and parameters: {'subsample': 0.9684217810899436, 'dropout_rate': 0.31711575718243923, 'n_estimators': 239, 'learning_rate': 0.017437187361754786}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:17:55,801] Trial 26 finished with value: 0.5997811069437992 and parameters: {'subsample': 0.10331607323083236, 'dropout_rate': 0.4262898459374778, 'n_estimators': 339, 'learning_rate': 0.06492312198748737}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5116279069767442
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:18:09,583] Trial 27 finished with value: 0.5839179552271065 and parameters: {'subsample': 0.4165251193156943, 'dropout_rate': 0.5697175944982166, 'n_estimators': 394, 'learning_rate': 0.07841180909513185}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:18:18,421] Trial 28 finished with value: 0.5961124612123413 and parameters: {'subsample': 0.20378016167426058, 'dropout_rate': 0.3080593480767576, 'n_estimators': 283, 'learning_rate': 0.09423108652838877}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.501937984496124
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 20:18:21,716] Trial 29 finished with value: 0.5602001795349578 and parameters: {'subsample': 0.6416717631966868, 'dropout_rate': 0.37840602508377813, 'n_estimators': 140, 'learning_rate': 0.04145107154604666}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5058139534883721
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 20:18:28,296] Trial 30 finished with value: 0.5614009052483011 and parameters: {'subsample': 0.8739790489864521, 'dropout_rate': 0.1887707361191721, 'n_estimators': 225, 'learning_rate': 0.05945860251883032}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:18:40,725] Trial 31 finished with value: 0.597213304916587 and parameters: {'subsample': 0.10801567352638314, 'dropout_rate': 0.43112581809075456, 'n_estimators': 325, 'learning_rate': 0.062795268442302}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:18:52,706] Trial 32 finished with value: 0.5888036095376861 and parameters: {'subsample': 0.29037066482540114, 'dropout_rate': 0.5590369262479858, 'n_estimators': 342, 'learning_rate': 0.08990374545168109}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:19:07,945] Trial 33 finished with value: 0.5985796171768034 and parameters: {'subsample': 0.16420935289576255, 'dropout_rate': 0.48095898939081394, 'n_estimators': 392, 'learning_rate': 0.06972596735960557}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:19:17,348] Trial 34 finished with value: 0.5982416661279027 and parameters: {'subsample': 0.23147450212788423, 'dropout_rate': 0.40100380978372174, 'n_estimators': 276, 'learning_rate': 0.07857724633962086}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:19:29,528] Trial 35 finished with value: 0.599318030656957 and parameters: {'subsample': 0.1705533285867683, 'dropout_rate': 0.5128764973438724, 'n_estimators': 340, 'learning_rate': 0.06798485272057093}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5680851063829787
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:19:39,742] Trial 36 finished with value: 0.5859187777571468 and parameters: {'subsample': 0.32951616895868197, 'dropout_rate': 0.3363167905297815, 'n_estimators': 305, 'learning_rate': 0.035039341590191925}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.5893536121673004

Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:20:04,850] Trial 37 finished with value: 0.5889632056991776 and parameters: {'subsample': 0.25024731314917675, 'dropout_rate': 0.16068871497947684, 'n_estimators': 478, 'learning_rate': 0.011979304832032835}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:20:10,659] Trial 38 finished with value: 0.5980968738897682 and parameters: {'subsample': 0.10048762833294078, 'dropout_rate': 0.2950640677363966, 'n_estimators': 190, 'learning_rate': 0.048252223497364057}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:20:14,949] Trial 39 finished with value: 0.5963082868622378 and parameters: {'subsample': 0.1910776884317828, 'dropout_rate': 0.43951101631790873, 'n_estimators': 159, 'learning_rate': 0.03111471331486717}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 20:20:27,503] Trial 40 finished with value: 0.572836533169388 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.7825497504780614, 'n_estimators': 379, 'learning_rate': 0.0926007252985458}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:20:41,753] Trial 41 finished with value: 0.6001763997556695 and parameters: {'subsample': 0.16224997918666884, 'dropout_rate': 0.5035496705862237, 'n_estimators': 341, 'learning_rate': 0.06648221232260701}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:20:52,390] Trial 42 finished with value: 0.5963304566426834 and parameters: {'subsample': 0.13702622030306183, 'dropout_rate': 0.9772717282714597, 'n_estimators': 342, 'learning_rate': 0.07538201022034376}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5290697674418605
Fold 3 C-index: 0.6
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:21:00,420] Trial 43 finished with value: 0.5966812732236122 and parameters: {'subsample': 0.13875280823850272, 'dropout_rate': 0.6176715828207425, 'n_estimators': 272, 'learning_rate': 0.055493758960739686}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 20:21:00,870] Trial 44 finished with value: 0.5524189342378344 and parameters: {'subsample': 0.3087080179108906, 'dropout_rate': 0.5020020877800176, 'n_estimators': 3, 'learning_rate': 0.06523605428553468}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 20:21:12,441] Trial 45 finished with value: 0.5598505176514019 and parameters: {'subsample': 0.7901683211371243, 'dropout_rate': 0.4102423420156518, 'n_estimators': 318, 'learning_rate': 0.08361016821919544}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:21:34,169] Trial 46 finished with value: 0.5959970776249058 and parameters: {'subsample': 0.14769766338995496, 'dropout_rate': 0.3590029346592782, 'n_estimators': 453, 'learning_rate': 0.04809232241299104}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:21:48,808] Trial 47 finished with value: 0.5993791631636094 and parameters: {'subsample': 0.19667393687722343, 'dropout_rate': 0.24024302199607747, 'n_estimators': 354, 'learning_rate': 0.07158768668349264}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:21:54,721] Trial 48 finished with value: 0.5872463405149179 and parameters: {'subsample': 0.2544273495519957, 'dropout_rate': 0.4763968311707486, 'n_estimators': 208, 'learning_rate': 0.05857266555983396}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:22:04,925] Trial 49 finished with value: 0.5883634670849421 and parameters: {'subsample': 0.3927717651164502, 'dropout_rate': 0.15540313965053826, 'n_estimators': 287, 'learning_rate': 0.02713079119975165}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:22:12,302] Trial 50 finished with value: 0.5986483089260507 and parameters: {'subsample': 0.13179690196820493, 'dropout_rate': 0.601695022808436, 'n_estimators': 255, 'learning_rate': 0.05211733700442702}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:22:26,336] Trial 51 finished with value: 0.5976949301095784 and parameters: {'subsample': 0.2028307525108225, 'dropout_rate': 0.2426928040540236, 'n_estimators': 367, 'learning_rate': 0.07046712653827243}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 20:22:40,391] Trial 52 finished with value: 0.5925235700434028 and parameters: {'subsample': 0.1850481257591581, 'dropout_rate': 0.2705822830737628, 'n_estimators': 350, 'learning_rate': 0.07425624997379439}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:22:56,869] Trial 53 finished with value: 0.59981801424893 and parameters: {'subsample': 0.10785967114690315, 'dropout_rate': 0.2181847765673067, 'n_estimators': 394, 'learning_rate': 0.0647102221579425}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:23:14,360] Trial 54 finished with value: 0.6010527904467604 and parameters: {'subsample': 0.149805272007383, 'dropout_rate': 0.1947914108786366, 'n_estimators': 411, 'learning_rate': 0.0641848531792715}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:23:35,059] Trial 55 finished with value: 0.600947572352887 and parameters: {'subsample': 0.15193096268202458, 'dropout_rate': 0.1783398280272528, 'n_estimators': 449, 'learning_rate': 0.09447789551796835}. Best is trial 14 with value: 0.6064776215330693.

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:23:54,376] Trial 56 finished with value: 0.5958227771380648 and parameters: {'subsample': 0.23353824999585454, 'dropout_rate': 0.1834244776724963, 'n_estimators': 431, 'learning_rate': 0.086859877951013}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:24:16,258] Trial 57 finished with value: 0.5959854971810786 and parameters: {'subsample': 0.2888110376335854, 'dropout_rate': 0.13714146987932704, 'n_estimators': 450, 'learning_rate': 0.09614022235539602}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:24:42,073] Trial 58 finished with value: 0.6001871160791227 and parameters: {'subsample': 0.14979718011191664, 'dropout_rate': 0.16876457136311146, 'n_estimators': 498, 'learning_rate': 0.07911589284552235}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:25:05,760] Trial 59 finished with value: 0.6009444152720288 and parameters: {'subsample': 0.14522006252948272, 'dropout_rate': 0.1592781206427018, 'n_estimators': 488, 'learning_rate': 0.09992162350954288}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:25:28,072] Trial 60 finished with value: 0.5976949301095784 and parameters: {'subsample': 0.223764605302758, 'dropout_rate': 0.1378882011241533, 'n_estimators': 460, 'learning_rate': 0.09217082630542689}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:25:55,742] Trial 61 finished with value: 0.6016610828147932 and parameters: {'subsample': 0.14402893998833405, 'dropout_rate': 0.17654377963170934, 'n_estimators': 497, 'learning_rate': 0.09919164456334614}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:26:19,055] Trial 62 finished with value: 0.6035765068867514 and parameters: {'subsample': 0.13265521035603417, 'dropout_rate': 0.10062691705071017, 'n_estimators': 481, 'learning_rate': 0.09930850453407239}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:26:43,490] Trial 63 finished with value: 0.5993281961505191 and parameters: {'subsample': 0.1795590721862888, 'dropout_rate': 0.10696529862276574, 'n_estimators': 476, 'learning_rate': 0.09946099078843709}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:27:03,835] Trial 64 finished with value: 0.6042726735730052 and parameters: {'subsample': 0.1313995970217997, 'dropout_rate': 0.19538184709803105, 'n_estimators': 437, 'learning_rate': 0.09607025301536322}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:27:25,197] Trial 65 finished with value: 0.6010817146662399 and parameters: {'subsample': 0.13570387779110304, 'dropout_rate': 0.20308211528557002, 'n_estimators': 411, 'learning_rate': 0.09404413377795745}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:27:45,064] Trial 66 finished with value: 0.5852503805929997 and parameters: {'subsample': 0.46480459806880037, 'dropout_rate': 0.21055062580048736, 'n_estimators': 417, 'learning_rate': 0.08715106104710812}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:28:07,937] Trial 67 finished with value: 0.6028276310568144 and parameters: {'subsample': 0.12543971622513173, 'dropout_rate': 0.12636140227137765, 'n_estimators': 442, 'learning_rate': 0.09083150707365487}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:28:31,615] Trial 68 finished with value: 0.601089273908835 and parameters: {'subsample': 0.12451506144150544, 'dropout_rate': 0.13471408687028302, 'n_estimators': 467, 'learning_rate': 0.08988180982021303}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:28:57,304] Trial 69 finished with value: 0.5975354609349217 and parameters: {'subsample': 0.2638372446587203, 'dropout_rate': 0.10157665184300901, 'n_estimators': 462, 'learning_rate': 0.09063594702233974}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:29:17,927] Trial 70 finished with value: 0.6004046876664084 and parameters: {'subsample': 0.1223279129506577, 'dropout_rate': 0.14803926971070164, 'n_estimators': 438, 'learning_rate': 0.0964737566239607}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 20:29:43,624] Trial 71 finished with value: 0.6002309048101226 and parameters: {'subsample': 0.12177816611746264, 'dropout_rate': 0.1295823626168223, 'n_estimators': 487, 'learning_rate': 0.09462932164360495}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:30:05,441] Trial 72 finished with value: 0.5949644080393522 and parameters: {'subsample': 0.2129627781184707, 'dropout_rate': 0.2629837187660929, 'n_estimators': 464, 'learning_rate': 0.08714297811016614}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:30:23,620] Trial 73 finished with value: 0.5961667122931246 and parameters: {'subsample': 0.1821306334918584, 'dropout_rate': 0.2188417404440295, 'n_estimators': 406, 'learning_rate': 0.08127053248679676}. Best is trial 14 with value: 0.6064776215330693.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:30:45,444] Trial 74 finished with value: 0.6021214258638333 and parameters: {'subsample': 0.1254074714599229, 'dropout_rate': 0.13553333600781797, 'n_estimators': 435, 'learning_rate': 0.09105813170150194}. Best is trial 14 with value: 0.6064776215330693.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:31:06,085] Trial 75 finished with value: 0.6070143854433381 and parameters: {'subsample': 0.10185920727711952, 'dropout_rate': 0.11467940028544912, 'n_estimators': 436, 'learning_rate': 0.09056873407930205}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:31:27,188] Trial 76 finished with value: 0.6017585717966852 and parameters: {'subsample': 0.17684685166426767, 'dropout_rate': 0.10065019420482439, 'n_estimators': 439, 'learning_rate': 0.09671548624542989}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:31:44,915] Trial 77 finished with value: 0.6045734204605537 and parameters: {'subsample': 0.1005221870301403, 'dropout_rate': 0.11661933475854054, 'n_estimators': 386, 'learning_rate': 0.08481420787978347}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:32:01,638] Trial 78 finished with value: 0.6021829822135418 and parameters: {'subsample': 0.102227349860528, 'dropout_rate': 0.11947316910166643, 'n_estimators': 382, 'learning_rate': 0.08486209037558219}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:32:18,800] Trial 79 finished with value: 0.6045588099227033 and parameters: {'subsample': 0.10763133007398282, 'dropout_rate': 0.11756862499630255, 'n_estimators': 378, 'learning_rate': 0.08527079351543332}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:32:39,290] Trial 80 finished with value: 0.5960218536563184 and parameters: {'subsample': 0.23782084746409804, 'dropout_rate': 0.23843390803729048, 'n_estimators': 390, 'learning_rate': 0.08110694155652488}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 20:32:56,493] Trial 81 finished with value: 0.6053411820032432 and parameters: {'subsample': 0.10952232575267778, 'dropout_rate': 0.12031658348820451, 'n_estimators': 370, 'learning_rate': 0.08733730794246773}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:33:13,728] Trial 82 finished with value: 0.6010233153973897 and parameters: {'subsample': 0.1665356587612243, 'dropout_rate': 0.1201755497054458, 'n_estimators': 365, 'learning_rate': 0.08865924827400361}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:33:26,870] Trial 83 finished with value: 0.6006473321413279 and parameters: {'subsample': 0.10242729705939135, 'dropout_rate': 0.15721367385871776, 'n_estimators': 327, 'learning_rate': 0.09330522963089109}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:33:43,878] Trial 84 finished with value: 0.5977676430600578 and parameters: {'subsample': 0.206208101505128, 'dropout_rate': 0.1750721090399811, 'n_estimators': 376, 'learning_rate': 0.08398411500093372}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:34:03,421] Trial 85 finished with value: 0.5970325136475972 and parameters: {'subsample': 0.16798645551035993, 'dropout_rate': 0.12110768148676332, 'n_estimators': 421, 'learning_rate': 0.07629530847441088}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 20:34:14,426] Trial 86 finished with value: 0.5629365553205149 and parameters: {'subsample': 0.992873343787547, 'dropout_rate': 0.10104917813239328, 'n_estimators': 302, 'learning_rate': 0.08563945318973394}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:34:35,510] Trial 87 finished with value: 0.6029797949625457 and parameters: {'subsample': 0.12489390321888963, 'dropout_rate': 0.15099673562192334, 'n_estimators': 406, 'learning_rate': 0.0966459814571714}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 20:34:53,940] Trial 88 finished with value: 0.6011432710159484 and parameters: {'subsample': 0.12301716786172386, 'dropout_rate': 0.2841978993020756, 'n_estimators': 405, 'learning_rate': 0.09695219076740375}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5368217054263565
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:35:11,395] Trial 89 finished with value: 0.6013171476597334 and parameters: {'subsample': 0.19180908169306027, 'dropout_rate': 0.15403610140215024, 'n_estimators': 393, 'learning_rate': 0.09199601439780584}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 20:35:30,206] Trial 90 finished with value: 0.5720760768956238 and parameters: {'subsample': 0.5542347092167768, 'dropout_rate': 0.7211266599729008, 'n_estimators': 445, 'learning_rate': 0.08143785893091621}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:35:54,738] Trial 91 finished with value: 0.6000854015559262 and parameters: {'subsample': 0.12091490033543417, 'dropout_rate': 0.20597128983544932, 'n_estimators': 426, 'learning_rate': 0.08933378958421026}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:36:03,653] Trial 92 finished with value: 0.6057134409142941 and parameters: {'subsample': 0.15810896390803064, 'dropout_rate': 0.14283459948856225, 'n_estimators': 231, 'learning_rate': 0.09532526874470451}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 20:36:12,490] Trial 93 finished with value: 0.6024610526446553 and parameters: {'subsample': 0.16183335120541767, 'dropout_rate': 0.191056960085066, 'n_estimators': 234, 'learning_rate': 0.09489785892140204}. Best is trial 75 with value: 0.6070143854433381.

Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5680851063829787
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 20:36:29,375] Trial 94 finished with value: 0.5789012942427565 and parameters: {'subsample': 0.6548932320082055, 'dropout_rate': 0.14701759414975424, 'n_estimators': 355, 'learning_rate': 0.09814327469572168}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:36:52,811] Trial 95 finished with value: 0.6013682748589942 and parameters: {'subsample': 0.10312183547900722, 'dropout_rate': 0.16509032145418462, 'n_estimators': 403, 'learning_rate': 0.09249191111247712}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 20:37:13,420] Trial 96 finished with value: 0.6026716158192371 and parameters: {'subsample': 0.156369990652763, 'dropout_rate': 0.12218422036612701, 'n_estimators': 381, 'learning_rate': 0.08810548931177169}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 20:37:44,012] Trial 97 finished with value: 0.6043121871291032 and parameters: {'subsample': 0.13383107475103168, 'dropout_rate': 0.22896654325360605, 'n_estimators': 479, 'learning_rate': 0.0958237676161481}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5290697674418605
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:38:12,303] Trial 98 finished with value: 0.594066525384542 and parameters: {'subsample': 0.20304336318014188, 'dropout_rate': 0.25249452600824324, 'n_estimators': 480, 'learning_rate': 0.09763512367752354}. Best is trial 75 with value: 0.6070143854433381.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5855513307984791

[I 2024-04-13 20:38:38,210] A new study created in memory with name: no-name-7cebd09c-e98a-4af9-82e7-6d51ecd4b056

Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 20:38:38,059] Trial 99 finished with value: 0.5621760990467507 and parameters: {'subsample': 0.9104218782867626, 'dropout_rate': 0.21861404010568622, 'n_estimators': 472, 'learning_rate': 0.09540915138907996}. Best is trial 75 with value: 0.6070143854433381.


* Best trial for C-index:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.6070143854433381], datetime_start=datetime.datetime(2024, 4, 13, 20, 30, 45, 451014), datetime_complete=datetime.datetime(2024, 4, 13, 20, 31, 6, 84616), params={'subsample': 0.10185920727711952, 'dropout_rate': 0.11467940028544912, 'n_estimators': 436, 'learning_rate': 0.09056873407930205}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=75, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.10185920727711952, 'dropout_rate': 0.11467940028544912, 'n_estimators': 436, 'learning_rate': 0.09056873407930205}


* Best Score for C-index:
 0.6070143854433381

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2768605959166274
Fold 2 IBS: 0.28392142909752927
Fold 3 IBS: 0.26390420137497594
Fold 4 IBS: 0.28511110366159176
Fold 5 IBS: 0.23049650269649638
[I 2024-04-13 20:38:42,590] Trial 0 finished with value: 0.26805876654944416 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.26805876654944416.
Fold 1 IBS: 0.3314083926697305
Fold 2 IBS: 0.4314078642168022
Fold 3 IBS: 0.32274777047798786
Fold 4 IBS: 0.4165285480110655
Fold 5 IBS: 0.339376702626222
[I 2024-04-13 20:39:06,896] Trial 1 finished with value: 0.3682938556003616 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.26805876654944416.
Fold 1 IBS: 0.3091855222340186
Fold 2 IBS: 0.3583277621663848
Fold 3 IBS: 0.3047589201819723
Fold 4 IBS: 0.3251564052484424
Fold 5 IBS: 0.3100934076743383
[I 2024-04-13 20:39:11,603] Trial 2 finished with value: 0.32150440350103127 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.26805876654944416.
Fold 1 IBS: 0.30788755683819485
Fold 2 IBS: 0.35725042965541515
Fold 3 IBS: 0.30287166895558215
Fold 4 IBS: 0.34378218433456925
Fold 5 IBS: 0.2665679761465616
[I 2024-04-13 20:39:17,661] Trial 3 finished with value: 0.3156719631860646 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.26805876654944416.
Fold 1 IBS: 0.3087039301353936
Fold 2 IBS: 0.35692712924779835
Fold 3 IBS: 0.3004132684893471
Fold 4 IBS: 0.3532160342964791
Fold 5 IBS: 0.2800074398407403
[I 2024-04-13 20:39:27,372] Trial 4 finished with value: 0.3198535604019517 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.26805876654944416.
Fold 1 IBS: 0.33292831395748784
Fold 2 IBS: 0.445013283923208
Fold 3 IBS: 0.32077526729505473
Fold 4 IBS: 0.37618612291914605
Fold 5 IBS: 0.33923818447315957
[I 2024-04-13 20:39:42,121] Trial 5 finished with value: 0.36282823451361124 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.26805876654944416.
Fold 1 IBS: 0.2583770894605203
Fold 2 IBS: 0.2753174659918347
Fold 3 IBS: 0.24099846394278826
Fold 4 IBS: 0.27370380884434886
Fold 5 IBS: 0.21760040361445157
[I 2024-04-13 20:39:47,515] Trial 6 finished with value: 0.2531994463707887 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2531994463707887.
Fold 1 IBS: 0.24449081430179984
Fold 2 IBS: 0.23999715690352616
Fold 3 IBS: 0.218745810531291
Fold 4 IBS: 0.2543921438290847
Fold 5 IBS: 0.21429196147972912
[I 2024-04-13 20:39:48,991] Trial 7 finished with value: 0.23438357740908616 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.23438357740908616.
Fold 1 IBS: 0.27473949169980044
Fold 2 IBS: 0.2956902991894394
Fold 3 IBS: 0.266701984975131
Fold 4 IBS: 0.2894036098116642
Fold 5 IBS: 0.22610047650933945
[I 2024-04-13 20:39:57,415] Trial 8 finished with value: 0.2705271724370749 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.23438357740908616.
Fold 1 IBS: 0.31944546154036996
Fold 2 IBS: 0.39612360699420396
Fold 3 IBS: 0.3210486304883838
Fold 4 IBS: 0.40208063720318327
Fold 5 IBS: 0.3390242043616515
[I 2024-04-13 20:40:14,267] Trial 9 finished with value: 0.3555445081175585 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.23438357740908616.
Fold 1 IBS: 0.2470353461515696
Fold 2 IBS: 0.23221355449931666
Fold 3 IBS: 0.22841670741019104
Fold 4 IBS: 0.24171407848753257
Fold 5 IBS: 0.22906264846898927
[I 2024-04-13 20:40:15,406] Trial 10 finished with value: 0.2356884670035198 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.23438357740908616.
Fold 1 IBS: 0.24639976969987745
Fold 2 IBS: 0.2328212998174295
Fold 3 IBS: 0.22672425069970245
Fold 4 IBS: 0.24087071384643838
Fold 5 IBS: 0.2279748608955893
[I 2024-04-13 20:40:15,913] Trial 11 finished with value: 0.23495817899180743 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.23438357740908616.
Fold 1 IBS: 0.24413080243104615
Fold 2 IBS: 0.2474170146380905
Fold 3 IBS: 0.22982485231243577
Fold 4 IBS: 0.2777577169265984
Fold 5 IBS: 0.19571239045710312
[I 2024-04-13 20:40:17,387] Trial 12 finished with value: 0.2389685553530548 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.23438357740908616.
Fold 1 IBS: 0.24595650697573987
Fold 2 IBS: 0.23340798693529763
Fold 3 IBS: 0.2254560651933552
Fold 4 IBS: 0.2402759194782458
Fold 5 IBS: 0.2271234075322375
[I 2024-04-13 20:40:18,167] Trial 13 finished with value: 0.23444397722297522 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.23438357740908616.
Fold 1 IBS: 0.2491137823614784
Fold 2 IBS: 0.24963213433681666
Fold 3 IBS: 0.2297106725072214
Fold 4 IBS: 0.2750128171706087
Fold 5 IBS: 0.20604294163001227
[I 2024-04-13 20:40:20,456] Trial 14 finished with value: 0.24190246960122747 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.23438357740908616.
Fold 1 IBS: 0.2782313985874612
Fold 2 IBS: 0.30331273692419
Fold 3 IBS: 0.28025489324819114
Fold 4 IBS: 0.29761190903473755
Fold 5 IBS: 0.22160154791207637
[I 2024-04-13 20:40:22,663] Trial 15 finished with value: 0.2762024971413312 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.23438357740908616.
Fold 1 IBS: 0.2907338039129263
Fold 2 IBS: 0.32153837931067125
Fold 3 IBS: 0.2636727201081902
Fold 4 IBS: 0.3135152928530487
Fold 5 IBS: 0.2106627513223751
[I 2024-04-13 20:40:30,398] Trial 16 finished with value: 0.28002458950144227 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.23438357740908616.
Fold 1 IBS: 0.24417753569669493
Fold 2 IBS: 0.23864151945977902
Fold 3 IBS: 0.2193960669415668
Fold 4 IBS: 0.2403548819478754
Fold 5 IBS: 0.22198742696468415
[I 2024-04-13 20:40:31,962] Trial 17 finished with value: 0.23291148620212007 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.2546743281324155
Fold 2 IBS: 0.27884057313100086
Fold 3 IBS: 0.23627042307884064
Fold 4 IBS: 0.2560327519574128
Fold 5 IBS: 0.21624465931312048
[I 2024-04-13 20:40:43,220] Trial 18 finished with value: 0.24841254712255806 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.2462303932396379
Fold 2 IBS: 0.24894448856742532

Fold 3 IBS: 0.22552825499814835
Fold 4 IBS: 0.2665867816858836
Fold 5 IBS: 0.209166894601268
[I 2024-04-13 20:40:46,554] Trial 19 finished with value: 0.23929136261847264 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.2446002185537661
Fold 2 IBS: 0.23463757481110972
Fold 3 IBS: 0.2201655501901051
Fold 4 IBS: 0.2439567647593348
Fold 5 IBS: 0.22296335334244682
[I 2024-04-13 20:40:48,070] Trial 20 finished with value: 0.23326469233135252 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.24513654608372853
Fold 2 IBS: 0.23383949946417815
Fold 3 IBS: 0.22211599951175628
Fold 4 IBS: 0.2430985991111111
Fold 5 IBS: 0.22475950483168106
[I 2024-04-13 20:40:49,481] Trial 21 finished with value: 0.233790029800491 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.24676894104572716
Fold 2 IBS: 0.23219799696075963
Fold 3 IBS: 0.2275588717402811
Fold 4 IBS: 0.2420998538089098
Fold 5 IBS: 0.22854475671534727
[I 2024-04-13 20:40:51,157] Trial 22 finished with value: 0.23543408405420502 and parameters: {'subsample': 0.6537769964653461, 'dropout_rate': 0.8093716219515759, 'n_estimators': 77, 'learning_rate': 0.0014039455806401802}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.24490905621214568
Fold 2 IBS: 0.25047638972431346
Fold 3 IBS: 0.21971857594936742
Fold 4 IBS: 0.24449559725852194
Fold 5 IBS: 0.21681196041619413
[I 2024-04-13 20:40:54,353] Trial 23 finished with value: 0.23528231591210855 and parameters: {'subsample': 0.8534306852041174, 'dropout_rate': 0.801007553345817, 'n_estimators': 146, 'learning_rate': 0.013693154749890787}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.24423622690142718
Fold 2 IBS: 0.23466790971984117
Fold 3 IBS: 0.21946355824650826
Fold 4 IBS: 0.24712302821630225
Fold 5 IBS: 0.22209682009858056
[I 2024-04-13 20:40:55,767] Trial 24 finished with value: 0.2335175086365319 and parameters: {'subsample': 0.6057018904919792, 'dropout_rate': 0.9862533241546715, 'n_estimators': 62, 'learning_rate': 0.01572471796157672}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.249850146996592
Fold 2 IBS: 0.2676138052755092
Fold 3 IBS: 0.22783542373258003
Fold 4 IBS: 0.24486706953708146
Fold 5 IBS: 0.21494656861182862
[I 2024-04-13 20:40:58,761] Trial 25 finished with value: 0.24102260283071825 and parameters: {'subsample': 0.8655825350862807, 'dropout_rate': 0.991151252373464, 'n_estimators': 145, 'learning_rate': 0.0210314188428598}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.2747420487553836
Fold 2 IBS: 0.30037058683875706
Fold 3 IBS: 0.26829249027461866
Fold 4 IBS: 0.2867204056339432
Fold 5 IBS: 0.23152562476944774
[I 2024-04-13 20:41:03,998] Trial 26 finished with value: 0.27233023125443007 and parameters: {'subsample': 0.5978333574014947, 'dropout_rate': 0.8982223660451839, 'n_estimators': 222, 'learning_rate': 0.029166999751579693}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.2446360248279642
Fold 2 IBS: 0.23553417901258736
Fold 3 IBS: 0.22135493729193806
Fold 4 IBS: 0.2428848452107294
Fold 5 IBS: 0.22412408102172918
[I 2024-04-13 20:41:05,239] Trial 27 finished with value: 0.23370681347298966 and parameters: {'subsample': 0.7973831324954838, 'dropout_rate': 0.9591162049738791, 'n_estimators': 39, 'learning_rate': 0.018143610116936895}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.24473645770003374
Fold 2 IBS: 0.23455678102298758
Fold 3 IBS: 0.220876429840608
Fold 4 IBS: 0.247047741480859
Fold 5 IBS: 0.22355537486256197
[I 2024-04-13 20:41:07,061] Trial 28 finished with value: 0.23415455698141008 and parameters: {'subsample': 0.5742192061348756, 'dropout_rate': 0.920234801468329, 'n_estimators': 86, 'learning_rate': 0.008921459414064498}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.26109329211485377
Fold 2 IBS: 0.2769983820191534
Fold 3 IBS: 0.24873752667185486
Fold 4 IBS: 0.2774880222938289
Fold 5 IBS: 0.2191916167333354
[I 2024-04-13 20:41:09,577] Trial 29 finished with value: 0.25670176796660527 and parameters: {'subsample': 0.6850952456167174, 'dropout_rate': 0.7643659553187094, 'n_estimators': 112, 'learning_rate': 0.04248605264426071}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.26161896430958
Fold 2 IBS: 0.2934701536946358
Fold 3 IBS: 0.24540411394886363
Fold 4 IBS: 0.2497317281389058
Fold 5 IBS: 0.22237679615468514
[I 2024-04-13 20:41:13,587] Trial 30 finished with value: 0.2545203512493341 and parameters: {'subsample': 0.9166631566118534, 'dropout_rate': 0.6038945600293156, 'n_estimators': 166, 'learning_rate': 0.027648893219016982}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.24484512431257702
Fold 2 IBS: 0.23505807526589614
Fold 3 IBS: 0.22219464714570406
Fold 4 IBS: 0.24366809108385815
Fold 5 IBS: 0.2247714564940444
[I 2024-04-13 20:41:14,496] Trial 31 finished with value: 0.23410747886041597 and parameters: {'subsample': 0.8069896584004299, 'dropout_rate': 0.962209410581427, 'n_estimators': 33, 'learning_rate': 0.018595308809269708}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.24415947075060926
Fold 2 IBS: 0.2380948696519026
Fold 3 IBS: 0.21938845612536706
Fold 4 IBS: 0.24317108553621516
Fold 5 IBS: 0.22211748045532953
[I 2024-04-13 20:41:16,060] Trial 32 finished with value: 0.23338627250388472 and parameters: {'subsample': 0.7878845579666447, 'dropout_rate': 0.9334475259375654, 'n_estimators': 63, 'learning_rate': 0.015821999327691336}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.24521569777692695
Fold 2 IBS: 0.23423224747651822
Fold 3 IBS: 0.22289078565921674
Fold 4 IBS: 0.24292805921405464
Fold 5 IBS: 0.22539920675986128
[I 2024-04-13 20:41:17,695] Trial 33 finished with value: 0.23413319937731555 and parameters: {'subsample': 0.731386412672128, 'dropout_rate': 0.8592057654150383, 'n_estimators': 74, 'learning_rate': 0.007128988064747212}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.24519324298666426
Fold 2 IBS: 0.24948098883976463
Fold 3 IBS: 0.2203710411914198
Fold 4 IBS: 0.25084114135181085
Fold 5 IBS: 0.21619556770855522
[I 2024-04-13 20:41:20,285] Trial 34 finished with value: 0.23641639641564294 and parameters: {'subsample': 0.780261540879776, 'dropout_rate': 0.90344159616093, 'n_estimators': 130, 'learning_rate': 0.016160179473353013}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.2458094291636763
Fold 2 IBS: 0.24453547619012966
Fold 3 IBS: 0.22203159138395198
Fold 4 IBS: 0.2625156230899512
Fold 5 IBS: 0.21354315889032652
[I 2024-04-13 20:41:36,781] Trial 35 finished with value: 0.23768705574360713 and parameters: {'subsample': 0.5458874231922135, 'dropout_rate': 0.43975685710717877, 'n_estimators': 422, 'learning_rate': 0.005826832206318818}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.2450799361887453
Fold 2 IBS: 0.23503956980258503
Fold 3 IBS: 0.22287799461521815
Fold 4 IBS: 0.24154677571125394
Fold 5 IBS: 0.22531140440588265
[I 2024-04-13 20:41:37,853] Trial 36 finished with value: 0.23397113614473702 and parameters: {'subsample': 0.9190234951369461, 'dropout_rate': 0.2795306755316796, 'n_estimators': 20, 'learning_rate': 0.027183675581612957}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.24948428846131115
Fold 2 IBS: 0.2514217457475341
Fold 3 IBS: 0.2322213138325259
Fold 4 IBS: 0.2663874851533491
Fold 5 IBS: 0.21094117484597974
[I 2024-04-13 20:41:39,560] Trial 37 finished with value: 0.24209120160813996 and parameters: {'subsample': 0.43420796750396373, 'dropout_rate': 0.7621022900062648, 'n_estimators': 61, 'learning_rate': 0.059207327336158105}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.25264719464003943
Fold 2 IBS: 0.25378842445640076

Fold 3 IBS: 0.2345343216426952
Fold 4 IBS: 0.27480342364574306
Fold 5 IBS: 0.20820368705343698
[I 2024-04-13 20:41:42,271] Trial 38 finished with value: 0.2447954102876631 and parameters: {'subsample': 0.703355276038254, 'dropout_rate': 0.13272164755980653, 'n_estimators': 113, 'learning_rate': 0.03521923736878125}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.25062091351496935
Fold 2 IBS: 0.25679440758337285
Fold 3 IBS: 0.23094671738894873
Fold 4 IBS: 0.2723938763086342
Fold 5 IBS: 0.21265849486129715
[I 2024-04-13 20:41:49,144] Trial 39 finished with value: 0.24468288193144444 and parameters: {'subsample': 0.628838778564896, 'dropout_rate': 0.48841341315505027, 'n_estimators': 243, 'learning_rate': 0.013931445007643331}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.25217715275845426
Fold 2 IBS: 0.2677872216513955
Fold 3 IBS: 0.23151320239683454
Fold 4 IBS: 0.2638382103949051
Fold 5 IBS: 0.21394023230043377
[I 2024-04-13 20:41:52,274] Trial 40 finished with value: 0.24585120390040466 and parameters: {'subsample': 0.7526208751778324, 'dropout_rate': 0.9367601241666426, 'n_estimators': 152, 'learning_rate': 0.022375472515760515}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.24436759319409987
Fold 2 IBS: 0.23670351686721558
Fold 3 IBS: 0.22024560064828375
Fold 4 IBS: 0.24291765151360042
Fold 5 IBS: 0.2231085438879694
[I 2024-04-13 20:41:53,620] Trial 41 finished with value: 0.23346858122223382 and parameters: {'subsample': 0.8321739625728432, 'dropout_rate': 0.9909972730201488, 'n_estimators': 53, 'learning_rate': 0.01598978921126944}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.24403736133472512
Fold 2 IBS: 0.2418940299665844
Fold 3 IBS: 0.21842976139212203
Fold 4 IBS: 0.24020711497137992
Fold 5 IBS: 0.2201548518482505
[I 2024-04-13 20:41:55,439] Trial 42 finished with value: 0.23294462390261242 and parameters: {'subsample': 0.9016791686746521, 'dropout_rate': 0.9924535191063116, 'n_estimators': 88, 'learning_rate': 0.014751729526281877}. Best is trial 17 with value: 0.23291148620212007.
Fold 1 IBS: 0.244413447176893
Fold 2 IBS: 0.2373260551167044
Fold 3 IBS: 0.22037598260010685
Fold 4 IBS: 0.23867493563759526
Fold 5 IBS: 0.22316917765813724
[I 2024-04-13 20:42:00,051] Trial 43 finished with value: 0.2327919196378873 and parameters: {'subsample': 0.9347772937074089, 'dropout_rate': 0.8736590224714996, 'n_estimators': 194, 'learning_rate': 0.004313941686211962}. Best is trial 43 with value: 0.2327919196378873.
Fold 1 IBS: 0.2448761872119347
Fold 2 IBS: 0.23554062117486158
Fold 3 IBS: 0.22201772919063686
Fold 4 IBS: 0.23932483147742753
Fold 5 IBS: 0.22467924748084117
[I 2024-04-13 20:42:04,481] Trial 44 finished with value: 0.23328772330714037 and parameters: {'subsample': 0.9243225982744891, 'dropout_rate': 0.8573033377127168, 'n_estimators': 194, 'learning_rate': 0.003211168549829839}. Best is trial 43 with value: 0.2327919196378873.
Fold 1 IBS: 0.24405554485233605
Fold 2 IBS: 0.24059991236122696
Fold 3 IBS: 0.21872653436173858
Fold 4 IBS: 0.23796923403728135
Fold 5 IBS: 0.22095937412066402
[I 2024-04-13 20:42:08,858] Trial 45 finished with value: 0.23246211994664936 and parameters: {'subsample': 0.9282317966118007, 'dropout_rate': 0.8669442762068573, 'n_estimators': 189, 'learning_rate': 0.0062326663164675895}. Best is trial 45 with value: 0.23246211994664936.
Fold 1 IBS: 0.2479871363110462
Fold 2 IBS: 0.26307991585465373
Fold 3 IBS: 0.22479865160679677
Fold 4 IBS: 0.23618449863838592
Fold 5 IBS: 0.21536091663847398
[I 2024-04-13 20:42:15,735] Trial 46 finished with value: 0.23748222380987133 and parameters: {'subsample': 0.9557813980997573, 'dropout_rate': 0.7500389383881887, 'n_estimators': 270, 'learning_rate': 0.010180453331315826}. Best is trial 45 with value: 0.23246211994664936.
Fold 1 IBS: 0.24408299970337088
Fold 2 IBS: 0.23972202712927773
Fold 3 IBS: 0.2189057746062749
Fold 4 IBS: 0.23900457751956797
Fold 5 IBS: 0.22129403354366503
[I 2024-04-13 20:42:19,921] Trial 47 finished with value: 0.2326018825004313 and parameters: {'subsample': 0.8958596057092121, 'dropout_rate': 0.6644531111795151, 'n_estimators': 177, 'learning_rate': 0.006348168505094296}. Best is trial 45 with value: 0.23246211994664936.
Fold 1 IBS: 0.24406045652734035
Fold 2 IBS: 0.2401678451826757
Fold 3 IBS: 0.21875368998085276
Fold 4 IBS: 0.23897590471625105
Fold 5 IBS: 0.22101582728221505
[I 2024-04-13 20:42:24,368] Trial 48 finished with value: 0.23259474473786698 and parameters: {'subsample': 0.8987769814674631, 'dropout_rate': 0.6604314111556595, 'n_estimators': 176, 'learning_rate': 0.00663929997038621}. Best is trial 45 with value: 0.23246211994664936.
Fold 1 IBS: 0.24406621151534189
Fold 2 IBS: 0.2401174438747437
Fold 3 IBS: 0.21882396338779597
Fold 4 IBS: 0.23903785013640585
Fold 5 IBS: 0.22113303974626236
[I 2024-04-13 20:42:30,158] Trial 49 finished with value: 0.23263570173210996 and parameters: {'subsample': 0.8946273714397041, 'dropout_rate': 0.6569849967915788, 'n_estimators': 220, 'learning_rate': 0.00524351186486742}. Best is trial 45 with value: 0.23246211994664936.
Fold 1 IBS: 0.24413093298815275
Fold 2 IBS: 0.2395249081119944
Fold 3 IBS: 0.21919147357036894
Fold 4 IBS: 0.23712639852712128
Fold 5 IBS: 0.22171892864110074
[I 2024-04-13 20:42:36,762] Trial 50 finished with value: 0.23233852836774763 and parameters: {'subsample': 0.9551649622007263, 'dropout_rate': 0.6636307256797472, 'n_estimators': 238, 'learning_rate': 0.004450462370602652}. Best is trial 50 with value: 0.23233852836774763.
Fold 1 IBS: 0.24404635963478039
Fold 2 IBS: 0.2410782626625587
Fold 3 IBS: 0.21865786984192478
Fold 4 IBS: 0.23671379598376244
Fold 5 IBS: 0.22080082383438915
[I 2024-04-13 20:42:42,901] Trial 51 finished with value: 0.23225942239148312 and parameters: {'subsample': 0.9621081176157638, 'dropout_rate': 0.6597193278206962, 'n_estimators': 227, 'learning_rate': 0.005325253180706122}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.2461099636321918
Fold 2 IBS: 0.23320730204774304
Fold 3 IBS: 0.22584263956749737
Fold 4 IBS: 0.2405134344696339
Fold 5 IBS: 0.22746436790625502
[I 2024-04-13 20:42:48,601] Trial 52 finished with value: 0.23462754152466422 and parameters: {'subsample': 0.9633118972894653, 'dropout_rate': 0.6602263398177919, 'n_estimators': 229, 'learning_rate': 0.0010962797112896647}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.24458331423830956
Fold 2 IBS: 0.24781804407568336
Fold 3 IBS: 0.21881829811768413
Fold 4 IBS: 0.23940142208766646
Fold 5 IBS: 0.21759465699755443
[I 2024-04-13 20:42:56,754] Trial 53 finished with value: 0.2336431471033796 and parameters: {'subsample': 0.8919211776269217, 'dropout_rate': 0.6826974609873503, 'n_estimators': 296, 'learning_rate': 0.006132545541703525}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.3368259708914299
Fold 2 IBS: 0.4575576860377951
Fold 3 IBS: 0.3199002048406866
Fold 4 IBS: 0.3180090703926233
Fold 5 IBS: 0.33931640173748734
[I 2024-04-13 20:43:03,533] Trial 54 finished with value: 0.3543218667800045 and parameters: {'subsample': 0.9691800942695185, 'dropout_rate': 0.6406682411660501, 'n_estimators': 258, 'learning_rate': 0.08152095528965622}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.24421129875298545
Fold 2 IBS: 0.2454742665972026
Fold 3 IBS: 0.2183170812420667
Fold 4 IBS: 0.2359975533711387
Fold 5 IBS: 0.2188408125954668
[I 2024-04-13 20:43:07,926] Trial 55 finished with value: 0.23256820251177204 and parameters: {'subsample': 0.9974931723693375, 'dropout_rate': 0.5812652970785014, 'n_estimators': 181, 'learning_rate': 0.008691620412125275}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.24418334013770496
Fold 2 IBS: 0.24517331713616722
Fold 3 IBS: 0.2182987357977064
Fold 4 IBS: 0.2360354292165404
Fold 5 IBS: 0.2189619218288221
[I 2024-04-13 20:43:12,072] Trial 56 finished with value: 0.2325305488233882 and parameters: {'subsample': 0.9960721454445686, 'dropout_rate': 0.5733256014599902, 'n_estimators': 175, 'learning_rate': 0.008850635191441128}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.3277227218063449
Fold 2 IBS: 0.42141486576995274

Fold 3 IBS: 0.31066778988567284
Fold 4 IBS: 0.2953220518192507
Fold 5 IBS: 0.33637252588000854
[I 2024-04-13 20:43:17,427] Trial 57 finished with value: 0.33829999103224595 and parameters: {'subsample': 0.9973261031802491, 'dropout_rate': 0.565616782693081, 'n_estimators': 204, 'learning_rate': 0.06795033768066108}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.24856912303953135
Fold 2 IBS: 0.2648811882881005
Fold 3 IBS: 0.22584711134343113
Fold 4 IBS: 0.23864085166272536
Fold 5 IBS: 0.21522732252870758
[I 2024-04-13 20:43:24,039] Trial 58 finished with value: 0.23863311937249918 and parameters: {'subsample': 0.9493350320664393, 'dropout_rate': 0.5038560979284157, 'n_estimators': 243, 'learning_rate': 0.011811490867438759}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.247706117411449
Fold 2 IBS: 0.2620466566474926
Fold 3 IBS: 0.22424657230600534
Fold 4 IBS: 0.23607552600936632
Fold 5 IBS: 0.21552378922282525
[I 2024-04-13 20:43:33,528] Trial 59 finished with value: 0.2371197323194277 and parameters: {'subsample': 0.9914976850634437, 'dropout_rate': 0.5666203477535927, 'n_estimators': 299, 'learning_rate': 0.008980706725985256}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.2523214743241097
Fold 2 IBS: 0.27257860103873294
Fold 3 IBS: 0.2333182305464914
Fold 4 IBS: 0.25645593321213883
Fold 5 IBS: 0.21523088611615765
[I 2024-04-13 20:43:37,998] Trial 60 finished with value: 0.24598102504752606 and parameters: {'subsample': 0.8319039507426439, 'dropout_rate': 0.6121214744948075, 'n_estimators': 172, 'learning_rate': 0.02053232134037576}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.2440510056055918
Fold 2 IBS: 0.24283366994168323
Fold 3 IBS: 0.2183466575755013
Fold 4 IBS: 0.23708229378072496
Fold 5 IBS: 0.21992084476921603
[I 2024-04-13 20:43:42,215] Trial 61 finished with value: 0.23244689433454346 and parameters: {'subsample': 0.9502203520505428, 'dropout_rate': 0.5310858617922151, 'n_estimators': 180, 'learning_rate': 0.00758592520087433}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.24501726905102486
Fold 2 IBS: 0.25108558852613694
Fold 3 IBS: 0.21947005888524482
Fold 4 IBS: 0.23688548755628855
Fold 5 IBS: 0.21711773180721539
[I 2024-04-13 20:43:46,775] Trial 62 finished with value: 0.23391522716518215 and parameters: {'subsample': 0.9593407269208336, 'dropout_rate': 0.42536348596108065, 'n_estimators': 187, 'learning_rate': 0.010655591469459436}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.24636944245735087
Fold 2 IBS: 0.23288311281868074
Fold 3 IBS: 0.22658757403050173
Fold 4 IBS: 0.2408674532400765
Fold 5 IBS: 0.22794825541831967
[I 2024-04-13 20:43:50,577] Trial 63 finished with value: 0.23493116759298588 and parameters: {'subsample': 0.996950977988305, 'dropout_rate': 0.5218474438287429, 'n_estimators': 161, 'learning_rate': 0.0011671173068120398}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.24242674842565665
Fold 2 IBS: 0.2350992722968954
Fold 3 IBS: 0.21614513699628474
Fold 4 IBS: 0.255974053100155
Fold 5 IBS: 0.2123647978656179
[I 2024-04-13 20:43:58,687] Trial 64 finished with value: 0.23240200173692194 and parameters: {'subsample': 0.1796848660781688, 'dropout_rate': 0.46702926828273594, 'n_estimators': 274, 'learning_rate': 0.007824798783694896}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.3168821748743595
Fold 2 IBS: 0.3493713728729633
Fold 3 IBS: 0.292591055602198
Fold 4 IBS: 0.34448112391725233
Fold 5 IBS: 0.27932591073856494
[I 2024-04-13 20:44:07,477] Trial 65 finished with value: 0.31653032760106764 and parameters: {'subsample': 0.1611790675513653, 'dropout_rate': 0.38855915636155713, 'n_estimators': 277, 'learning_rate': 0.04841446942458946}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.25321788253806693
Fold 2 IBS: 0.2602391628123962
Fold 3 IBS: 0.23871644563689232
Fold 4 IBS: 0.28596340561347117
Fold 5 IBS: 0.2046170447512756
[I 2024-04-13 20:44:13,409] Trial 66 finished with value: 0.24855078827042046 and parameters: {'subsample': 0.24560660258541234, 'dropout_rate': 0.47318238667763607, 'n_estimators': 209, 'learning_rate': 0.02473587458427584}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.25291130512666393
Fold 2 IBS: 0.2757614200588624
Fold 3 IBS: 0.2326258180507358
Fold 4 IBS: 0.2422459867925507
Fold 5 IBS: 0.21599821357707344
[I 2024-04-13 20:44:24,458] Trial 67 finished with value: 0.24390854872117726 and parameters: {'subsample': 0.9421861232086552, 'dropout_rate': 0.35021251364269124, 'n_estimators': 320, 'learning_rate': 0.01103444037765353}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.24423925099240734
Fold 2 IBS: 0.23832134751051942
Fold 3 IBS: 0.21960712402680369
Fold 4 IBS: 0.24135998942438316
Fold 5 IBS: 0.22234335347071843
[I 2024-04-13 20:44:30,902] Trial 68 finished with value: 0.23317421308496641 and parameters: {'subsample': 0.8502184820817186, 'dropout_rate': 0.5671629313665663, 'n_estimators': 234, 'learning_rate': 0.004133416036535664}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.2441308634822786
Fold 2 IBS: 0.23192365759263214
Fold 3 IBS: 0.21944365130261156
Fold 4 IBS: 0.24576219433740012
Fold 5 IBS: 0.22019703597667445
[I 2024-04-13 20:44:33,908] Trial 69 finished with value: 0.23229148053831938 and parameters: {'subsample': 0.18890607008448618, 'dropout_rate': 0.5358019630002284, 'n_estimators': 126, 'learning_rate': 0.008554399597688757}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.24309064059067714
Fold 2 IBS: 0.23587303704693552
Fold 3 IBS: 0.21521372468813954
Fold 4 IBS: 0.2573040229550249
Fold 5 IBS: 0.21020800091650518
[I 2024-04-13 20:44:37,353] Trial 70 finished with value: 0.23233788523945648 and parameters: {'subsample': 0.21276978748613773, 'dropout_rate': 0.4573808808370987, 'n_estimators': 127, 'learning_rate': 0.019387237599685414}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.24421321261010087
Fold 2 IBS: 0.23952358458438303
Fold 3 IBS: 0.2187482374113845
Fold 4 IBS: 0.2618800951565354
Fold 5 IBS: 0.2107359599544065
[I 2024-04-13 20:44:42,581] Trial 71 finished with value: 0.2350202179433621 and parameters: {'subsample': 0.27715061889188874, 'dropout_rate': 0.5229311136974948, 'n_estimators': 131, 'learning_rate': 0.01824440014939091}. Best is trial 51 with value: 0.23225942239148312.
Fold 1 IBS: 0.2438430323758313
Fold 2 IBS: 0.23269143305813828
Fold 3 IBS: 0.21646727972741536
Fold 4 IBS: 0.2490690379603018
Fold 5 IBS: 0.21667311827070776
[I 2024-04-13 20:44:47,368] Trial 72 finished with value: 0.23174878027847892 and parameters: {'subsample': 0.18547014033479986, 'dropout_rate': 0.4213428202829266, 'n_estimators': 135, 'learning_rate': 0.011521054358352012}. Best is trial 72 with value: 0.23174878027847892.
Fold 1 IBS: 0.24379679703780746
Fold 2 IBS: 0.233019734794759
Fold 3 IBS: 0.2159173143799065
Fold 4 IBS: 0.2495538325763788
Fold 5 IBS: 0.21620908788555687
[I 2024-04-13 20:44:51,435] Trial 73 finished with value: 0.23169935333488173 and parameters: {'subsample': 0.18597033136891927, 'dropout_rate': 0.34679371324769204, 'n_estimators': 137, 'learning_rate': 0.01202755209781522}. Best is trial 73 with value: 0.23169935333488173.
Fold 1 IBS: 0.24374881471161677
Fold 2 IBS: 0.23251296813410421
Fold 3 IBS: 0.21793794256082924
Fold 4 IBS: 0.2473374907015167
Fold 5 IBS: 0.2184691308713486
[I 2024-04-13 20:44:53,785] Trial 74 finished with value: 0.23200126939588311 and parameters: {'subsample': 0.1799378926827149, 'dropout_rate': 0.3257329068315404, 'n_estimators': 103, 'learning_rate': 0.013309284590066275}. Best is trial 73 with value: 0.23169935333488173.
Fold 1 IBS: 0.24381600053839586
Fold 2 IBS: 0.23295625860810643
Fold 3 IBS: 0.21558618509098157
Fold 4 IBS: 0.2507505054300787
Fold 5 IBS: 0.21608397081077613
[I 2024-04-13 20:44:56,871] Trial 75 finished with value: 0.23183858409566774 and parameters: {'subsample': 0.18447559086885507, 'dropout_rate': 0.2979389867392314, 'n_estimators': 127, 'learning_rate': 0.013121327005866842}. Best is trial 73 with value: 0.23169935333488173.
Fold 1 IBS: 0.24308737538155922

Fold 2 IBS: 0.23862969480175472
Fold 3 IBS: 0.21707217888229136
Fold 4 IBS: 0.2689140303226001
Fold 5 IBS: 0.20748843095039043
[I 2024-04-13 20:44:59,131] Trial 76 finished with value: 0.23503834206771917 and parameters: {'subsample': 0.21986786119949991, 'dropout_rate': 0.2640930463660313, 'n_estimators': 99, 'learning_rate': 0.03129844324263236}. Best is trial 73 with value: 0.23169935333488173.
Fold 1 IBS: 0.2402848847898735
Fold 2 IBS: 0.23438829712812412
Fold 3 IBS: 0.21121418177496804
Fold 4 IBS: 0.25933659550694627
Fold 5 IBS: 0.20938395486478042
[I 2024-04-13 20:45:02,215] Trial 77 finished with value: 0.23092158281293845 and parameters: {'subsample': 0.10027825939376077, 'dropout_rate': 0.3127569715361363, 'n_estimators': 132, 'learning_rate': 0.020102710084664722}. Best is trial 77 with value: 0.23092158281293845.
Fold 1 IBS: 0.2410805558867413
Fold 2 IBS: 0.23530499933287927
Fold 3 IBS: 0.21320884353140648
Fold 4 IBS: 0.2608386827506965
Fold 5 IBS: 0.2080759472906538
[I 2024-04-13 20:45:05,178] Trial 78 finished with value: 0.23170180575847543 and parameters: {'subsample': 0.129819978418774, 'dropout_rate': 0.31489286431722746, 'n_estimators': 121, 'learning_rate': 0.02101732490727643}. Best is trial 77 with value: 0.23092158281293845.
Fold 1 IBS: 0.24339695834218247
Fold 2 IBS: 0.24100778466957262
Fold 3 IBS: 0.21445264143854506
Fold 4 IBS: 0.2684524230740322
Fold 5 IBS: 0.20325848186083167
[I 2024-04-13 20:45:08,661] Trial 79 finished with value: 0.23411365787703278 and parameters: {'subsample': 0.10979480518597536, 'dropout_rate': 0.20163253193948308, 'n_estimators': 142, 'learning_rate': 0.024425793455055935}. Best is trial 77 with value: 0.23092158281293845.
Fold 1 IBS: 0.24406645276960148
Fold 2 IBS: 0.23260672952049827
Fold 3 IBS: 0.21748028296758162
Fold 4 IBS: 0.25202663447995516
Fold 5 IBS: 0.2175876770213378
[I 2024-04-13 20:45:11,233] Trial 80 finished with value: 0.2327535553517949 and parameters: {'subsample': 0.1607390139764502, 'dropout_rate': 0.31687427716830935, 'n_estimators': 113, 'learning_rate': 0.012641446842354414}. Best is trial 77 with value: 0.23092158281293845.
Fold 1 IBS: 0.24377410684723078
Fold 2 IBS: 0.23749771241373832
Fold 3 IBS: 0.21704367625456558
Fold 4 IBS: 0.2606893301243686
Fold 5 IBS: 0.20852177534154695
[I 2024-04-13 20:45:14,306] Trial 81 finished with value: 0.23350532019629006 and parameters: {'subsample': 0.2024116504698395, 'dropout_rate': 0.31720343483104585, 'n_estimators': 127, 'learning_rate': 0.020627527568966752}. Best is trial 77 with value: 0.23092158281293845.
Fold 1 IBS: 0.24240958279549288
Fold 2 IBS: 0.23365686332351096
Fold 3 IBS: 0.21332535798333474
Fold 4 IBS: 0.25647765872223055
Fold 5 IBS: 0.21052746450816842
[I 2024-04-13 20:45:17,514] Trial 82 finished with value: 0.23127938546654753 and parameters: {'subsample': 0.13620613428531245, 'dropout_rate': 0.21896207345309593, 'n_estimators': 123, 'learning_rate': 0.01851486397816474}. Best is trial 77 with value: 0.23092158281293845.
Fold 1 IBS: 0.2419278998973609
Fold 2 IBS: 0.23237540704382262
Fold 3 IBS: 0.2126453264577199
Fold 4 IBS: 0.25123163396013193
Fold 5 IBS: 0.2096221619171309
[I 2024-04-13 20:45:19,701] Trial 83 finished with value: 0.22956048585523323 and parameters: {'subsample': 0.13116331281670648, 'dropout_rate': 0.20545561467314005, 'n_estimators': 90, 'learning_rate': 0.02659218031349017}. Best is trial 83 with value: 0.22956048585523323.
Fold 1 IBS: 0.24237681495180063
Fold 2 IBS: 0.23466814923333063
Fold 3 IBS: 0.21163613086311722
Fold 4 IBS: 0.2572309027055423
Fold 5 IBS: 0.20899078915463432
[I 2024-04-13 20:45:21,859] Trial 84 finished with value: 0.230980557381685 and parameters: {'subsample': 0.13541974604238158, 'dropout_rate': 0.2192513443296181, 'n_estimators': 95, 'learning_rate': 0.026885379047763298}. Best is trial 83 with value: 0.22956048585523323.
Fold 1 IBS: 0.24236667958116453
Fold 2 IBS: 0.23621851727208545
Fold 3 IBS: 0.21109681519513065
Fold 4 IBS: 0.25866475829878705
Fold 5 IBS: 0.2059456452087338
[I 2024-04-13 20:45:23,823] Trial 85 finished with value: 0.23085848311118032 and parameters: {'subsample': 0.13668907106347158, 'dropout_rate': 0.20734256677937932, 'n_estimators': 87, 'learning_rate': 0.03538993546488931}. Best is trial 83 with value: 0.22956048585523323.
Fold 1 IBS: 0.24289161365476516
Fold 2 IBS: 0.2381658398336303
Fold 3 IBS: 0.21366474030933683
Fold 4 IBS: 0.2636313222837063
Fold 5 IBS: 0.20710623541139772
[I 2024-04-13 20:45:25,767] Trial 86 finished with value: 0.23309195029856725 and parameters: {'subsample': 0.13920218796207778, 'dropout_rate': 0.20145411167009108, 'n_estimators': 84, 'learning_rate': 0.03418255869637061}. Best is trial 83 with value: 0.22956048585523323.
Fold 1 IBS: 0.2437841992197141
Fold 2 IBS: 0.23558780499001292
Fold 3 IBS: 0.2132784469006752
Fold 4 IBS: 0.2639897678598649
Fold 5 IBS: 0.20183887651272692
[I 2024-04-13 20:45:27,960] Trial 87 finished with value: 0.23169581909659884 and parameters: {'subsample': 0.12273776593807287, 'dropout_rate': 0.21824315318005813, 'n_estimators': 90, 'learning_rate': 0.03857710295128833}. Best is trial 83 with value: 0.22956048585523323.
Fold 1 IBS: 0.242219262491466
Fold 2 IBS: 0.2299269806819967
Fold 3 IBS: 0.21605253327432475
Fold 4 IBS: 0.24714482937358884
Fold 5 IBS: 0.21473341216592187
[I 2024-04-13 20:45:29,365] Trial 88 finished with value: 0.23001540359745962 and parameters: {'subsample': 0.12398909519995861, 'dropout_rate': 0.2191334991913955, 'n_estimators': 44, 'learning_rate': 0.039753988755090286}. Best is trial 83 with value: 0.22956048585523323.
Fold 1 IBS: 0.24453493808430177
Fold 2 IBS: 0.23008743271396284
Fold 3 IBS: 0.22248613774862644
Fold 4 IBS: 0.24639928089590446
Fold 5 IBS: 0.22275861477947057
[I 2024-04-13 20:45:30,358] Trial 89 finished with value: 0.23325328084445324 and parameters: {'subsample': 0.10088651340211124, 'dropout_rate': 0.20582695587447114, 'n_estimators': 20, 'learning_rate': 0.03883351083255216}. Best is trial 83 with value: 0.22956048585523323.
Fold 1 IBS: 0.2424009189009271
Fold 2 IBS: 0.2301710771140026
Fold 3 IBS: 0.2162857609688077
Fold 4 IBS: 0.24735493493314203
Fold 5 IBS: 0.2152935892987845
[I 2024-04-13 20:45:31,597] Trial 90 finished with value: 0.2303012562431328 and parameters: {'subsample': 0.12415190878926574, 'dropout_rate': 0.2316342095000012, 'n_estimators': 42, 'learning_rate': 0.04036667309130201}. Best is trial 83 with value: 0.22956048585523323.
Fold 1 IBS: 0.24232010199583204
Fold 2 IBS: 0.23148942850157797
Fold 3 IBS: 0.21477633402271332
Fold 4 IBS: 0.2466967351434236
Fold 5 IBS: 0.21065623654581103
[I 2024-04-13 20:45:32,869] Trial 91 finished with value: 0.22918776724187162 and parameters: {'subsample': 0.12997376659838994, 'dropout_rate': 0.2315449509874271, 'n_estimators': 48, 'learning_rate': 0.046086009528404755}. Best is trial 91 with value: 0.22918776724187162.
Fold 1 IBS: 0.24227041423016546
Fold 2 IBS: 0.23107549083921536
Fold 3 IBS: 0.21684350225433688
Fold 4 IBS: 0.24623512607969492
Fold 5 IBS: 0.21229806749415903
[I 2024-04-13 20:45:33,919] Trial 92 finished with value: 0.2297445201795143 and parameters: {'subsample': 0.1281184356713573, 'dropout_rate': 0.23792161396660208, 'n_estimators': 38, 'learning_rate': 0.046425363696648306}. Best is trial 91 with value: 0.22918776724187162.
Fold 1 IBS: 0.24234167452533456
Fold 2 IBS: 0.23183489331593127
Fold 3 IBS: 0.2144504783994538
Fold 4 IBS: 0.24867207183799422
Fold 5 IBS: 0.21278001477947317
[I 2024-04-13 20:45:35,115] Trial 93 finished with value: 0.23001582657163738 and parameters: {'subsample': 0.14219177755906215, 'dropout_rate': 0.23000509176588702, 'n_estimators': 46, 'learning_rate': 0.04555605165562244}. Best is trial 91 with value: 0.22918776724187162.
Fold 1 IBS: 0.2423236141406431
Fold 2 IBS: 0.23160401514502368
Fold 3 IBS: 0.21565248774683116
Fold 4 IBS: 0.24886587712452427
Fold 5 IBS: 0.21193074293817196
[I 2024-04-13 20:45:36,269] Trial 94 finished with value: 0.23007534741903884 and parameters: {'subsample': 0.13697618480334708, 'dropout_rate': 0.23833744939699153, 'n_estimators': 39, 'learning_rate': 0.04711407358341917}. Best is trial 91 with value: 0.22918776724187162.

Fold 1 IBS: 0.2427492136521167
Fold 2 IBS: 0.23183948041552568
Fold 3 IBS: 0.21311208627262304
Fold 4 IBS: 0.25051259661582037
Fold 5 IBS: 0.21204976836178402
[I 2024-04-13 20:45:37,318] Trial 95 finished with value: 0.23005262906357396 and parameters: {'subsample': 0.15264452640327397, 'dropout_rate': 0.17030680435941772, 'n_estimators': 41, 'learning_rate': 0.04617763984593193}. Best is trial 91 with value: 0.22918776724187162.
Fold 1 IBS: 0.24543496525606437
Fold 2 IBS: 0.23140021504927716
Fold 3 IBS: 0.22560829397671991
Fold 4 IBS: 0.24490841093042917
Fold 5 IBS: 0.2256979875863117
[I 2024-04-13 20:45:38,086] Trial 96 finished with value: 0.23460997455976046 and parameters: {'subsample': 0.24358576777347152, 'dropout_rate': 0.14401520560687697, 'n_estimators': 8, 'learning_rate': 0.04481151765552657}. Best is trial 91 with value: 0.22918776724187162.
Fold 1 IBS: 0.24270476272257596
Fold 2 IBS: 0.23369089769487017
Fold 3 IBS: 0.21321195455178632
Fold 4 IBS: 0.24908496368563687
Fold 5 IBS: 0.21020213766648996
[I 2024-04-13 20:45:39,322] Trial 97 finished with value: 0.2297789432642719 and parameters: {'subsample': 0.15527463768442187, 'dropout_rate': 0.18128341634822331, 'n_estimators': 45, 'learning_rate': 0.05298485217217283}. Best is trial 91 with value: 0.22918776724187162.
Fold 1 IBS: 0.24313187885003235
Fold 2 IBS: 0.23350426026653684
Fold 3 IBS: 0.21476896617612806
Fold 4 IBS: 0.2470957439763147
Fold 5 IBS: 0.2125900487476966
[I 2024-04-13 20:45:40,576] Trial 98 finished with value: 0.2302181796033417 and parameters: {'subsample': 0.15665334251877835, 'dropout_rate': 0.17350824588288802, 'n_estimators': 37, 'learning_rate': 0.053944457119502756}. Best is trial 91 with value: 0.22918776724187162.
Fold 1 IBS: 0.24215254525423527
Fold 2 IBS: 0.23257407128779997
Fold 3 IBS: 0.21513198843279052
Fold 4 IBS: 0.2584482905843192
Fold 5 IBS: 0.2084755734942729
[I 2024-04-13 20:45:41,767] Trial 99 finished with value: 0.23135649381068357 and parameters: {'subsample': 0.1623641385527859, 'dropout_rate': 0.1020065862826505, 'n_estimators': 42, 'learning_rate': 0.054071713313873046}. Best is trial 91 with value: 0.22918776724187162.


* Best trial for IBS:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.22918776724187162], datetime_start=datetime.datetime(2024, 4, 13, 20, 45, 31, 608672), datetime_complete=datetime.datetime(2024, 4, 13, 20, 45, 32, 869310), params={'subsample': 0.12997376659838994, 'dropout_rate': 0.2315449509874271, 'n_estimators': 48, 'learning_rate': 0.046086009528404755}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=91, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.12997376659838994, 'dropout_rate': 0.2315449509874271, 'n_estimators': 48, 'learning_rate': 0.046086009528404755}


* Best Score for IBS:
 0.22918776724187162

In [77]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [78]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.607
train_ibs:  0.229

#### Test

In [79]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [80]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.11467940028544912,
                                              learning_rate=0.09056873407930205,
                                              n_estimators=436,
                                              random_state=123,
                                              subsample=0.10185920727711952)

C-index score: 0.575

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.2315449509874271,
                                              learning_rate=0.046086009528404755,
                                              n_estimators=48, random_state=123,
                                              subsample=0.12997376659838994)

IBS: 0.239

In [81]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [82]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
ExtraSurvivalTrees               0.791   1.0
Randomsurvivalforest             0.760   2.0
GradientBoosting                 0.642   3.0
CoxElastic                       0.639   4.0
CoxPH                            0.637   5.0
CoxLasso                         0.635   6.0
ComponentwiseGradientBoosting    0.607   7.0
CoxRidge                         0.566   8.0

In [83]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.217   1.0
Randomsurvivalforest           0.223   2.0
ComponentwiseGradientBoosting  0.229   3.0
GradientBoosting               0.232   4.0
CoxRidge                       0.236   5.5
CoxElastic                     0.236   5.5
CoxLasso                       0.240   7.0
CoxPH                          0.308   8.0

In [84]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
GradientBoosting                 0.669   1.0
Randomsurvivalforest             0.633   2.0
CoxRidge                         0.584   3.5
ExtraSurvivalTrees               0.584   3.5
ComponentwiseGradientBoosting    0.575   5.0
CoxLasso                         0.566   6.0
CoxElastic                       0.564   7.0
CoxPH                            0.563   8.0

In [85]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
Randomsurvivalforest           0.216   1.0
ExtraSurvivalTrees             0.223   2.0
GradientBoosting               0.224   3.0
CoxRidge                       0.229   4.5
CoxElastic                     0.229   4.5
ComponentwiseGradientBoosting  0.239   6.0
CoxLasso                       0.288   7.0
CoxPH                          0.291   8.0

In [86]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/dfs/robust/no_selection/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_dfs_robust_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [87]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-13