In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import RobustScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

## Test dataset: MAASTRO

In [6]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [7]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [8]:
# need to choose patient_id from MAASTRO_D1 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [9]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]

In [10]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [11]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, DFS, DFS_event]
Index: []

In [12]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [13]:
# Set lower, upper time point and times for IBS calculation later 

# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 14)
y_train:  (139,)

(99, 16)

# Feature Selection: PLSR

In [14]:
selected_features = [
"MTV",
"TLG",
"hpv_related",
"SUVpeak",
"uicc8_III-IV",
"oropharynx"
]

# Selecting features in the DataFrame
X_plsr = X[selected_features]
X_new = X_plsr.copy()

In [15]:
X_MAASTRO_plsr = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_plsr.copy()
# No need to standardize since all selected columns are binary
X_new_std = X_new
MAASTRO_new_std = MAASTRO_new

# Standardization

In [16]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = RobustScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 

# All the columns are binary meaning no scaler needed 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [17]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 

MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the MAASTRO_new, MAASTRO_new_std
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[X_new.columns]

In [18]:
X_new

        MTV         TLG  hpv_related    SUVpeak  uicc8_III-IV  oropharynx
0     7.934   86.228420          0.0  14.473272           0.0           1
1     1.656    7.040100          0.0   5.044678           0.0           0
2    14.502   83.569669          0.0   7.839043           1.0           0
3     2.440    5.567091          0.0   2.880631           0.0           0
4     3.668   16.150550          0.0   5.402006           0.0           0
..      ...         ...          ...        ...           ...         ...
134   3.650   26.280140          1.0   9.290139           0.0           1
135  18.967  101.754834          1.0   7.172883           1.0           1
136   6.370   66.273201          1.0  13.873187           0.0           1
137  12.443   71.832443          1.0   7.507419           1.0           1
138   7.983   78.647696          1.0  13.053465           1.0           1

[139 rows x 6 columns]

In [19]:
X_new_std

          MTV       TLG  hpv_related   SUVpeak  uicc8_III-IV  oropharynx
0    0.075008  0.231096          0.0  0.600320           0.0           1
1   -0.466877 -0.387041          0.0 -0.690705           0.0           0
2    0.641923  0.210342          0.0 -0.308082           1.0           0
3   -0.399206 -0.398539          0.0 -0.987020           0.0           0
4   -0.293211 -0.315926          0.0 -0.641777           0.0           0
..        ...       ...          ...       ...           ...         ...
134 -0.294765 -0.236855          1.0 -0.109388           0.0           1
135  1.027319  0.352293          1.0 -0.399297           1.0           1
136 -0.059989  0.075327          1.0  0.518153           0.0           1
137  0.464201  0.118722          1.0 -0.353490           1.0           1
138  0.079237  0.171921          1.0  0.405911           1.0           1

[139 rows x 6 columns]

In [20]:
MAASTRO_new

       MTV         TLG  hpv_related    SUVpeak  uicc8_III-IV  oropharynx
0   22.841  263.611623            1  15.438583             0           1
1    5.660   36.980700            0   8.829353             1           1
2    7.791   74.636342            0  13.476123             1           1
3    7.908   46.791979            0   8.632732             1           0
4   15.237  107.637514            1   9.783954             0           1
..     ...         ...          ...        ...           ...         ...
94   6.110  144.490782            0  31.338410             1           0
95   7.182   69.214868            0  13.041604             1           0
96  16.483  102.594274            1   8.944517             1           1
97   9.981  103.229492            1  14.184236             0           1
98   3.495   28.553212            0  10.414851             1           0

[99 rows x 6 columns]

In [21]:
MAASTRO_new_std

         MTV       TLG  hpv_related   SUVpeak  uicc8_III-IV  oropharynx
0   1.361702  1.615732            1  0.732497             0           1
1  -0.121272 -0.153327            0 -0.172482             1           1
2   0.062665  0.140609            0  0.463784             1           1
3   0.072763 -0.076742            0 -0.199405             1           0
4   0.705364  0.398213            1 -0.041772             0           1
..       ...       ...          ...       ...           ...         ...
94 -0.082431  0.685886            0  2.909606             1           0
95  0.010099  0.098289            0  0.404287             1           0
96  0.812913  0.358846            1 -0.156713             1           1
97  0.251694  0.363804            1  0.560744             0           1
98 -0.308144 -0.219112            0  0.044615             1           0

[99 rows x 6 columns]

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [22]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 14:51:54,768] A new study created in memory with name: no-name-dc9f2385-b4f3-4f07-888d-095b705329d2

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-18 14:51:59,765] A new study created in memory with name: no-name-40498129-8a74-448e-9a84-f02803c23593

Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:51:59,752] Trial 0 finished with value: 0.6314272435878002 and parameters: {}. Best is trial 0 with value: 0.6314272435878002.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6314272435878002], datetime_start=datetime.datetime(2024, 4, 18, 14, 51, 54, 856120), datetime_complete=datetime.datetime(2024, 4, 18, 14, 51, 59, 752382), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6314272435878002

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.25104063694870243
Fold 2 IBS: 0.23023130950396492
Fold 3 IBS: 0.1815270008194301
Fold 4 IBS: 0.28352164879300995
Fold 5 IBS: 0.2114703252261867
[I 2024-04-18 14:52:00,102] Trial 0 finished with value: 0.2315581842582588 and parameters: {}. Best is trial 0 with value: 0.2315581842582588.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2315581842582588], datetime_start=datetime.datetime(2024, 4, 18, 14, 51, 59, 800110), datetime_complete=datetime.datetime(2024, 4, 18, 14, 52, 0, 102253), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2315581842582588

In [23]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [24]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.631
train_ibs:  0.232

#### Test

In [25]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [26]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.593
IBS score: 0.253

In [27]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [28]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [29]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 14:52:00,273] A new study created in memory with name: no-name-b1c411f0-5690-492c-b63a-9cc046bf8c21

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5597609561752988
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6936170212765957

[I 2024-04-18 14:52:00,460] A new study created in memory with name: no-name-2ea39636-6c69-4965-b0f3-72b85290cdd4

Fold 4 C-index: 0.4695817490494297
Fold 5 C-index: 0.6180257510729614
[I 2024-04-18 14:52:00,452] Trial 0 finished with value: 0.5895149249722215 and parameters: {}. Best is trial 0 with value: 0.5895149249722215.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5895149249722215], datetime_start=datetime.datetime(2024, 4, 18, 14, 52, 0, 311348), datetime_complete=datetime.datetime(2024, 4, 18, 14, 52, 0, 452738), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5895149249722215

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709622633062
Fold 2 IBS: 0.23203988074395682
Fold 3 IBS: 0.22898186249434238
Fold 4 IBS: 0.24197478945971077
Fold 5 IBS: 0.2293955885877772
[I 2024-04-18 14:52:00,682] Trial 0 finished with value: 0.23592784350242355 and parameters: {}. Best is trial 0 with value: 0.23592784350242355.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592784350242355], datetime_start=datetime.datetime(2024, 4, 18, 14, 52, 0, 497104), datetime_complete=datetime.datetime(2024, 4, 18, 14, 52, 0, 682266), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592784350242355

In [30]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [31]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.59
train_ibs:  0.236

#### Test

In [32]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [33]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.642

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [34]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [35]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 14:52:00,825] A new study created in memory with name: no-name-4ace507b-3bf0-4833-afe6-fde2e1e8202b

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559

[I 2024-04-18 14:52:01,160] A new study created in memory with name: no-name-08295041-18cb-4146-be8a-e08517f626b1

Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:01,154] Trial 0 finished with value: 0.6304097021706524 and parameters: {}. Best is trial 0 with value: 0.6304097021706524.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6304097021706524], datetime_start=datetime.datetime(2024, 4, 18, 14, 52, 0, 858145), datetime_complete=datetime.datetime(2024, 4, 18, 14, 52, 1, 153853), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6304097021706524

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2498479051521125
Fold 2 IBS: 0.22915617228216204
Fold 3 IBS: 0.18245597547256243
Fold 4 IBS: 0.2823066179106044
Fold 5 IBS: 0.21084019909088417
[I 2024-04-18 14:52:01,510] Trial 0 finished with value: 0.23092137398166512 and parameters: {}. Best is trial 0 with value: 0.23092137398166512.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23092137398166512], datetime_start=datetime.datetime(2024, 4, 18, 14, 52, 1, 196933), datetime_complete=datetime.datetime(2024, 4, 18, 14, 52, 1, 510340), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23092137398166512

In [36]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [37]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.63
train_ibs:  0.231

#### Test

In [38]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [39]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.599

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.25

In [40]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [41]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 14:52:01,754] A new study created in memory with name: no-name-cbe9a5b9-15fb-469b-a63a-8dc09fe2d569

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:02,057] Trial 0 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:02,364] Trial 1 finished with value: 0.6287981820671009 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:02,716] Trial 2 finished with value: 0.6287981820671009 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:03,077] Trial 3 finished with value: 0.6287834445424155 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:03,345] Trial 4 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:03,657] Trial 5 finished with value: 0.6287834445424155 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:03,897] Trial 6 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:04,139] Trial 7 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:04,390] Trial 8 finished with value: 0.6287834445424155 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:04,643] Trial 9 finished with value: 0.6295586383408651 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:04,890] Trial 10 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:05,133] Trial 11 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.748312136386636}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:05,385] Trial 12 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.7236736559681478}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:05,632] Trial 13 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.8178071080614558}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.6094420600858369
[I 2024-04-18 14:52:05,768] Trial 14 finished with value: 0.584556401065921 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:06,020] Trial 15 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.5998716175293216}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:06,310] Trial 16 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.8431112134784231}. Best is trial 0 with value: 0.6304097021706524.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:06,577] Trial 17 finished with value: 0.6312607660004397 and parameters: {'l1_ratio': 0.6422698927560148}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:06,910] Trial 18 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.608004980950956}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:07,223] Trial 19 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.8475037169293791}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:07,495] Trial 20 finished with value: 0.6287981820671009 and parameters: {'l1_ratio': 0.31242295912387974}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:07,787] Trial 21 finished with value: 0.6312607660004397 and parameters: {'l1_ratio': 0.6462055416811876}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:08,057] Trial 22 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.6212770134355613}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:08,362] Trial 23 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.5200872363022372}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892

Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:08,654] Trial 24 finished with value: 0.6312607660004397 and parameters: {'l1_ratio': 0.6337782913213387}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:08,911] Trial 25 finished with value: 0.6295586383408651 and parameters: {'l1_ratio': 0.4420371910071116}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:09,158] Trial 26 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.9167426588025347}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:09,435] Trial 27 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.784569591468679}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:09,701] Trial 28 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.6611562814391995}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:09,969] Trial 29 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.5547858638724052}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:10,221] Trial 30 finished with value: 0.6287834445424155 and parameters: {'l1_ratio': 0.6553519380711575}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:10,516] Trial 31 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.7626777932818549}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:10,788] Trial 32 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.8863328406784581}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:11,061] Trial 33 finished with value: 0.6295586383408651 and parameters: {'l1_ratio': 0.3424665273099216}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6201550387596899
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:11,398] Trial 34 finished with value: 0.6303485696640001 and parameters: {'l1_ratio': 0.21553914253693035}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:11,666] Trial 35 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.5678159951036906}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:11,945] Trial 36 finished with value: 0.6287834445424155 and parameters: {'l1_ratio': 0.4696047719980405}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:12,236] Trial 37 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.6896753491801438}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:12,556] Trial 38 finished with value: 0.6304855722019901 and parameters: {'l1_ratio': 0.6259928081829811}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:12,836] Trial 39 finished with value: 0.6312607660004397 and parameters: {'l1_ratio': 0.6440471956950358}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:13,265] Trial 40 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.5204911496675979}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:13,581] Trial 41 finished with value: 0.6312607660004397 and parameters: {'l1_ratio': 0.6403467498813542}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:14,014] Trial 42 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.7024470862281567}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:14,444] Trial 43 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.5781042774461739}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:14,769] Trial 44 finished with value: 0.6287834445424155 and parameters: {'l1_ratio': 0.6557010601436859}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:15,102] Trial 45 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.7363904197730966}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:15,458] Trial 46 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.789809359106609}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:15,831] Trial 47 finished with value: 0.6287834445424155 and parameters: {'l1_ratio': 0.5085407160237889}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892

Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:16,200] Trial 48 finished with value: 0.6295586383408651 and parameters: {'l1_ratio': 0.4037678712864638}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.622093023255814
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.4714828897338403
Fold 5 C-index: 0.6266094420600858
[I 2024-04-18 14:52:16,344] Trial 49 finished with value: 0.5943142601258249 and parameters: {'l1_ratio': 0.005040986123852953}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:16,645] Trial 50 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.705282490444848}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:16,940] Trial 51 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.6216212424500833}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:17,254] Trial 52 finished with value: 0.6312607660004397 and parameters: {'l1_ratio': 0.6363621670512154}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:17,651] Trial 53 finished with value: 0.6287834445424155 and parameters: {'l1_ratio': 0.5476273884298484}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:18,007] Trial 54 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.6604535980728223}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:18,309] Trial 55 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.5957792010627521}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:18,641] Trial 56 finished with value: 0.6287834445424155 and parameters: {'l1_ratio': 0.469269489099795}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:18,964] Trial 57 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.7438342196349742}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:19,351] Trial 58 finished with value: 0.6312607660004397 and parameters: {'l1_ratio': 0.6358379290053233}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:19,782] Trial 59 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.6818203952555042}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:20,219] Trial 60 finished with value: 0.6287834445424155 and parameters: {'l1_ratio': 0.5473924796673119}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:20,689] Trial 61 finished with value: 0.6312607660004397 and parameters: {'l1_ratio': 0.6328071024404692}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:21,132] Trial 62 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.5964130562959213}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:21,603] Trial 63 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.7242439003945462}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:22,111] Trial 64 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.7789652360518166}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:22,647] Trial 65 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.8250348947228765}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:23,006] Trial 66 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.6762513393586917}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:23,350] Trial 67 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.5782995742251609}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:23,684] Trial 68 finished with value: 0.6312607660004397 and parameters: {'l1_ratio': 0.636363905708029}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:24,018] Trial 69 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.5308078427206672}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:24,447] Trial 70 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.71148849640433}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:24,790] Trial 71 finished with value: 0.6312607660004397 and parameters: {'l1_ratio': 0.6369815012379298}. Best is trial 17 with value: 0.6312607660004397.

Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:25,074] Trial 72 finished with value: 0.6287834445424155 and parameters: {'l1_ratio': 0.49293338486365623}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:25,346] Trial 73 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.6004908655888417}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:25,615] Trial 74 finished with value: 0.6312607660004397 and parameters: {'l1_ratio': 0.6373816689792423}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:25,885] Trial 75 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.665148618754291}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:26,162] Trial 76 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.7582869709922582}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:26,517] Trial 77 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.569282648016328}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:26,813] Trial 78 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.694069314367757}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:27,234] Trial 79 finished with value: 0.6295586383408651 and parameters: {'l1_ratio': 0.43816234396781106}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:27,688] Trial 80 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.6191629506966242}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:28,039] Trial 81 finished with value: 0.6312607660004397 and parameters: {'l1_ratio': 0.6397172602956901}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:28,355] Trial 82 finished with value: 0.6287834445424155 and parameters: {'l1_ratio': 0.6508432883731735}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:28,638] Trial 83 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.5920594321609193}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:28,917] Trial 84 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.6742749758026968}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:29,189] Trial 85 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.7249267813592151}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:29,466] Trial 86 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.5322933555815866}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:29,762] Trial 87 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.6156284399879514}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:30,159] Trial 88 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.5547025471087164}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:30,498] Trial 89 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.8023625616560591}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:30,822] Trial 90 finished with value: 0.6312607660004397 and parameters: {'l1_ratio': 0.6376291776495093}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:31,130] Trial 91 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.6938808332965585}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:31,529] Trial 92 finished with value: 0.6312607660004397 and parameters: {'l1_ratio': 0.640196769143251}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:31,836] Trial 93 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.5784549961939446}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:32,120] Trial 94 finished with value: 0.6296345083722028 and parameters: {'l1_ratio': 0.6038572379698918}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:32,526] Trial 95 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.6669037236031151}. Best is trial 17 with value: 0.6312607660004397.

Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:32,913] Trial 96 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.7132401836037802}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:33,327] Trial 97 finished with value: 0.6304855722019901 and parameters: {'l1_ratio': 0.6242322112672503}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:33,757] Trial 98 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.7613813362221115}. Best is trial 17 with value: 0.6312607660004397.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6124031007751938

[I 2024-04-18 14:52:34,074] A new study created in memory with name: no-name-ee2618ab-c727-478d-92aa-f3a7b6c67742

Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 14:52:34,068] Trial 99 finished with value: 0.6304097021706524 and parameters: {'l1_ratio': 0.741818173739903}. Best is trial 17 with value: 0.6312607660004397.


* Best trial for C-index:
 FrozenTrial(number=17, state=TrialState.COMPLETE, values=[0.6312607660004397], datetime_start=datetime.datetime(2024, 4, 18, 14, 52, 6, 313769), datetime_complete=datetime.datetime(2024, 4, 18, 14, 52, 6, 576884), params={'l1_ratio': 0.6422698927560148}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=17, value=None)


* Best Score for C-index:
 0.6312607660004397

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2501164038101084
Fold 2 IBS: 0.22906885747870007
Fold 3 IBS: 0.18261608331177717
Fold 4 IBS: 0.28246778346363743
Fold 5 IBS: 0.21082694034208624
[I 2024-04-18 14:52:34,467] Trial 0 finished with value: 0.23101921368126183 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.23101921368126183.
Fold 1 IBS: 0.25045127911107684
Fold 2 IBS: 0.2289033481961742
Fold 3 IBS: 0.182812646795246
Fold 4 IBS: 0.28267568254733594
Fold 5 IBS: 0.2107988601018046
[I 2024-04-18 14:52:35,159] Trial 1 finished with value: 0.23112836335032752 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.23101921368126183.
Fold 1 IBS: 0.25053506079926924
Fold 2 IBS: 0.22896299234243309
Fold 3 IBS: 0.18274008272267475
Fold 4 IBS: 0.282689020442975
Fold 5 IBS: 0.21077984327525492
[I 2024-04-18 14:52:35,904] Trial 2 finished with value: 0.2311413999165214 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.23101921368126183.
Fold 1 IBS: 0.2502240012280291
Fold 2 IBS: 0.22901829324705839
Fold 3 IBS: 0.18269755714803515
Fold 4 IBS: 0.2825460293305906
Fold 5 IBS: 0.21081742746254745
[I 2024-04-18 14:52:36,398] Trial 3 finished with value: 0.23106066168325215 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.23101921368126183.
Fold 1 IBS: 0.25002599010014603
Fold 2 IBS: 0.22910545082985403
Fold 3 IBS: 0.18259328006013734
Fold 4 IBS: 0.28248437000229015
Fold 5 IBS: 0.21084410116944424
[I 2024-04-18 14:52:36,758] Trial 4 finished with value: 0.23101063843237432 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 4 with value: 0.23101063843237432.
Fold 1 IBS: 0.2502779595937834
Fold 2 IBS: 0.22903922408844077
Fold 3 IBS: 0.1827263875669961
Fold 4 IBS: 0.2825697432966888
Fold 5 IBS: 0.21078715481027713
[I 2024-04-18 14:52:37,202] Trial 5 finished with value: 0.23108009387123726 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 4 with value: 0.23101063843237432.
Fold 1 IBS: 0.24985155353108784
Fold 2 IBS: 0.22913510203607465
Fold 3 IBS: 0.1824677000810762
Fold 4 IBS: 0.2822971992542625
Fold 5 IBS: 0.21083022910852067
[I 2024-04-18 14:52:37,538] Trial 6 finished with value: 0.23091635680220435 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.23091635680220435.
Fold 1 IBS: 0.2501188126578751
Fold 2 IBS: 0.2290512187367699
Fold 3 IBS: 0.18262896463960213
Fold 4 IBS: 0.2825512698001711
Fold 5 IBS: 0.2108178522001781
[I 2024-04-18 14:52:37,844] Trial 7 finished with value: 0.23103362360691926 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.23091635680220435.
Fold 1 IBS: 0.2503078886583304
Fold 2 IBS: 0.22896738293551996
Fold 3 IBS: 0.18270559310987286
Fold 4 IBS: 0.28255120645125226
Fold 5 IBS: 0.2108006387264672
[I 2024-04-18 14:52:38,193] Trial 8 finished with value: 0.23106654197628856 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.23091635680220435.
Fold 1 IBS: 0.2503465977131968
Fold 2 IBS: 0.22894805970302437
Fold 3 IBS: 0.1827978127768858
Fold 4 IBS: 0.28261423933758106
Fold 5 IBS: 0.21080317127851395
[I 2024-04-18 14:52:38,552] Trial 9 finished with value: 0.2311019761618404 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.23091635680220435.
Fold 1 IBS: 0.24985086929624392
Fold 2 IBS: 0.2291390950452251
Fold 3 IBS: 0.18246547831167018
Fold 4 IBS: 0.2822989888633858
Fold 5 IBS: 0.2108321175054459
[I 2024-04-18 14:52:38,875] Trial 10 finished with value: 0.23091730980439418 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.23091635680220435.
Fold 1 IBS: 0.24984842830935275
Fold 2 IBS: 0.22915318357335748
Fold 3 IBS: 0.18245763854966957
Fold 4 IBS: 0.28230527845197134
Fold 5 IBS: 0.21083878420317126
[I 2024-04-18 14:52:39,177] Trial 11 finished with value: 0.2309206626175045 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 6 with value: 0.23091635680220435.
Fold 1 IBS: 0.2498489234622385
Fold 2 IBS: 0.22915034491065375
Fold 3 IBS: 0.18245921811482357
Fold 4 IBS: 0.28230400622711854
Fold 5 IBS: 0.21083744057746753
[I 2024-04-18 14:52:39,483] Trial 12 finished with value: 0.23091998665846036 and parameters: {'l1_ratio': 0.9946087870438435}. Best is trial 6 with value: 0.23091635680220435.
Fold 1 IBS: 0.2499720976147465
Fold 2 IBS: 0.22908350899157245
Fold 3 IBS: 0.18247625368689438
Fold 4 IBS: 0.2823461884508439
Fold 5 IBS: 0.21081601486745824
[I 2024-04-18 14:52:39,798] Trial 13 finished with value: 0.2309388127223031 and parameters: {'l1_ratio': 0.8521165717679541}. Best is trial 6 with value: 0.23091635680220435.
Fold 1 IBS: 0.25069524942600935
Fold 2 IBS: 0.22908442903792928
Fold 3 IBS: 0.2245920855890506
Fold 4 IBS: 0.257876401543809
Fold 5 IBS: 0.2258676931527034
[I 2024-04-18 14:52:39,978] Trial 14 finished with value: 0.23762317174990036 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 6 with value: 0.23091635680220435.
Fold 1 IBS: 0.24996947770512318
Fold 2 IBS: 0.2291016526837275
Fold 3 IBS: 0.18246603599251213
Fold 4 IBS: 0.2823543449045886
Fold 5 IBS: 0.21082455452964582
[I 2024-04-18 14:52:40,275] Trial 15 finished with value: 0.23094321316311944 and parameters: {'l1_ratio': 0.8659212232095017}. Best is trial 6 with value: 0.23091635680220435.
Fold 1 IBS: 0.24997073511370976
Fold 2 IBS: 0.2290930023083902
Fold 3 IBS: 0.18247090762310994
Fold 4 IBS: 0.2823504562646909
Fold 5 IBS: 0.2108204812606731
[I 2024-04-18 14:52:40,569] Trial 16 finished with value: 0.23094111651411478 and parameters: {'l1_ratio': 0.8592866247617579}. Best is trial 6 with value: 0.23091635680220435.
Fold 1 IBS: 0.2500008696005131
Fold 2 IBS: 0.22903229900994226
Fold 3 IBS: 0.18250610886540808
Fold 4 IBS: 0.2824380068577732
Fold 5 IBS: 0.21085072277644273
[I 2024-04-18 14:52:40,874] Trial 17 finished with value: 0.2309656014220159 and parameters: {'l1_ratio': 0.8140829029918109}. Best is trial 6 with value: 0.23091635680220435.
Fold 1 IBS: 0.2502189245552598
Fold 2 IBS: 0.22896953774565643
Fold 3 IBS: 0.18265259923532742
Fold 4 IBS: 0.282574528228573
Fold 5 IBS: 0.21078789937038434
[I 2024-04-18 14:52:41,223] Trial 18 finished with value: 0.2310406978270402 and parameters: {'l1_ratio': 0.5819463953201167}. Best is trial 6 with value: 0.23091635680220435.
Fold 1 IBS: 0.24985679454892556
Fold 2 IBS: 0.22910384827627414
Fold 3 IBS: 0.18248508891777457
Fold 4 IBS: 0.2822831909415121
Fold 5 IBS: 0.21081546523790376
[I 2024-04-18 14:52:41,650] Trial 19 finished with value: 0.23090887758447803 and parameters: {'l1_ratio': 0.9535087433508003}. Best is trial 19 with value: 0.23090887758447803.
Fold 1 IBS: 0.25001325334543645
Fold 2 IBS: 0.2290903396832595
Fold 3 IBS: 0.1825351672556229
Fold 4 IBS: 0.28241670097908056
Fold 5 IBS: 0.21082851206261533
[I 2024-04-18 14:52:42,006] Trial 20 finished with value: 0.23097679466520296 and parameters: {'l1_ratio': 0.7800470520332179}. Best is trial 19 with value: 0.23090887758447803.
Fold 1 IBS: 0.24985838548574185
Fold 2 IBS: 0.22909411512185462
Fold 3 IBS: 0.18249049777076345
Fold 4 IBS: 0.2822788281263015
Fold 5 IBS: 0.2108108724041507
[I 2024-04-18 14:52:42,373] Trial 21 finished with value: 0.2309065397817624 and parameters: {'l1_ratio': 0.9453140545316446}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24996150876139916
Fold 2 IBS: 0.22915421233073793
Fold 3 IBS: 0.1825160150468808
Fold 4 IBS: 0.2823779617780859
Fold 5 IBS: 0.21084934822580326
[I 2024-04-18 14:52:42,682] Trial 22 finished with value: 0.23097180922858138 and parameters: {'l1_ratio': 0.9084391297728723}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24986143479526166
Fold 2 IBS: 0.2290768686314624
Fold 3 IBS: 0.18250106621445547
Fold 4 IBS: 0.2822703121434246
Fold 5 IBS: 0.2108608722942078
[I 2024-04-18 14:52:42,994] Trial 23 finished with value: 0.23091411081576235 and parameters: {'l1_ratio': 0.929701253282429}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.2500176038243342
Fold 2 IBS: 0.22906152780094896
Fold 3 IBS: 0.18255397698976933
Fold 4 IBS: 0.28240286420771815
Fold 5 IBS: 0.2108141606722238
[I 2024-04-18 14:52:43,284] Trial 24 finished with value: 0.23097002669899885 and parameters: {'l1_ratio': 0.7594214865564164}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.2501273879890977
Fold 2 IBS: 0.2290847464918728

Fold 3 IBS: 0.18257521722964518
Fold 4 IBS: 0.28252916082691065
Fold 5 IBS: 0.21078283746483825
[I 2024-04-18 14:52:43,586] Trial 25 finished with value: 0.23101987000047292 and parameters: {'l1_ratio': 0.6427594368859761}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24995997274999734
Fold 2 IBS: 0.22906065733451814
Fold 3 IBS: 0.1825100984425452
Fold 4 IBS: 0.2823823291034426
Fold 5 IBS: 0.21085394117755218
[I 2024-04-18 14:52:43,893] Trial 26 finished with value: 0.23095339976161106 and parameters: {'l1_ratio': 0.9167426588025347}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24660182408601464
Fold 2 IBS: 0.2314408429286839
Fold 3 IBS: 0.22809923849026004
Fold 4 IBS: 0.2449941414355088
Fold 5 IBS: 0.22868896852966641
[I 2024-04-18 14:52:44,039] Trial 27 finished with value: 0.23596500309402674 and parameters: {'l1_ratio': 0.016560941611969082}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24996010174254701
Fold 2 IBS: 0.2290597706568299
Fold 3 IBS: 0.18251059244193363
Fold 4 IBS: 0.2823819644896531
Fold 5 IBS: 0.21085355761621047
[I 2024-04-18 14:52:44,323] Trial 28 finished with value: 0.23095319738943482 and parameters: {'l1_ratio': 0.9160438397833989}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.25012462397074803
Fold 2 IBS: 0.22900121465144765
Fold 3 IBS: 0.18266217027459256
Fold 4 IBS: 0.2825398748849891
Fold 5 IBS: 0.2107948332061608
[I 2024-04-18 14:52:44,619] Trial 29 finished with value: 0.23102454339758763 and parameters: {'l1_ratio': 0.6564863747805005}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.25001772239234316
Fold 2 IBS: 0.2290606735164526
Fold 3 IBS: 0.18255450321454267
Fold 4 IBS: 0.2824024779090487
Fold 5 IBS: 0.21081375941665276
[I 2024-04-18 14:52:44,904] Trial 30 finished with value: 0.23096982728980797 and parameters: {'l1_ratio': 0.7588593268717845}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24986053405138176
Fold 2 IBS: 0.22908077727250062
Fold 3 IBS: 0.18249791771015905
Fold 4 IBS: 0.2822728493091012
Fold 5 IBS: 0.210863319089542
[I 2024-04-18 14:52:45,179] Trial 31 finished with value: 0.2309150794865369 and parameters: {'l1_ratio': 0.9343008524088953}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24995980471041643
Fold 2 IBS: 0.22906181101195827
Fold 3 IBS: 0.1825094556852711
Fold 4 IBS: 0.282382803504944
Fold 5 IBS: 0.21085444026206016
[I 2024-04-18 14:52:45,456] Trial 32 finished with value: 0.23095366303492998 and parameters: {'l1_ratio': 0.9176534349189551}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24997571303418903
Fold 2 IBS: 0.22905945156668084
Fold 3 IBS: 0.18249079832437765
Fold 4 IBS: 0.28233457484419794
Fold 5 IBS: 0.21080387080997523
[I 2024-04-18 14:52:45,738] Trial 33 finished with value: 0.23093288171588414 and parameters: {'l1_ratio': 0.8331745248158063}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24986133293910523
Fold 2 IBS: 0.2290775096803059
Fold 3 IBS: 0.18250070903659857
Fold 4 IBS: 0.2822705999739573
Fold 5 IBS: 0.21086114983829787
[I 2024-04-18 14:52:46,021] Trial 34 finished with value: 0.23091426029365297 and parameters: {'l1_ratio': 0.9302208759758195}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.2500016875706644
Fold 2 IBS: 0.2291326928296273
Fold 3 IBS: 0.182509098498635
Fold 4 IBS: 0.2824358158348105
Fold 5 IBS: 0.21084843553180846
[I 2024-04-18 14:52:46,304] Trial 35 finished with value: 0.23098554605310911 and parameters: {'l1_ratio': 0.8104517085280184}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.25002557566298117
Fold 2 IBS: 0.22910851395119516
Fold 3 IBS: 0.18259122265188119
Fold 4 IBS: 0.28248575821384003
Fold 5 IBS: 0.2107861966954942
[I 2024-04-18 14:52:46,588] Trial 36 finished with value: 0.23099945343507838 and parameters: {'l1_ratio': 0.7214880935680813}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.2499666599175336
Fold 2 IBS: 0.2291206694620837
Fold 3 IBS: 0.18253642989045127
Fold 4 IBS: 0.28236288650911695
Fold 5 IBS: 0.21083351632901595
[I 2024-04-18 14:52:46,872] Trial 37 finished with value: 0.2309640324216403 and parameters: {'l1_ratio': 0.8808567522730943}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24985781701345164
Fold 2 IBS: 0.2290976066778425
Fold 3 IBS: 0.1824885613336414
Fold 4 IBS: 0.28228039320667087
Fold 5 IBS: 0.21081251968263115
[I 2024-04-18 14:52:47,152] Trial 38 finished with value: 0.23090737958284752 and parameters: {'l1_ratio': 0.9482381748293426}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.2504468182388454
Fold 2 IBS: 0.22897687644586331
Fold 3 IBS: 0.18276739324704994
Fold 4 IBS: 0.28265559782835764
Fold 5 IBS: 0.21077924544837645
[I 2024-04-18 14:52:47,463] Trial 39 finished with value: 0.23112518624169853 and parameters: {'l1_ratio': 0.27690564740781887}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24985532670620966
Fold 2 IBS: 0.22911272421134313
Fold 3 IBS: 0.18248015078155452
Fold 4 IBS: 0.2822871693883229
Fold 5 IBS: 0.2108196558459572
[I 2024-04-18 14:52:47,747] Trial 40 finished with value: 0.23091100538667747 and parameters: {'l1_ratio': 0.9611010558640337}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24985701575192568
Fold 2 IBS: 0.22910250209274238
Fold 3 IBS: 0.1824858378532528
Fold 4 IBS: 0.282282587532884
Fold 5 IBS: 0.21081482985187902
[I 2024-04-18 14:52:48,101] Trial 41 finished with value: 0.23090855461653675 and parameters: {'l1_ratio': 0.9523672565736727}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24985664913915384
Fold 2 IBS: 0.22910473196607994
Fold 3 IBS: 0.18248459728378635
Fold 4 IBS: 0.28228358704210793
Fold 5 IBS: 0.21081588235835824
[I 2024-04-18 14:52:48,402] Trial 42 finished with value: 0.2309090895578972 and parameters: {'l1_ratio': 0.9542594860568294}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24985552648633672
Fold 2 IBS: 0.22911152191904088
Fold 3 IBS: 0.1824808196883936
Fold 4 IBS: 0.28228663049292385
Fold 5 IBS: 0.21081908807884572
[I 2024-04-18 14:52:48,719] Trial 43 finished with value: 0.23091071733310814 and parameters: {'l1_ratio': 0.9600658711919648}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.2499677071303652
Fold 2 IBS: 0.22911365995049637
Fold 3 IBS: 0.18254069486567742
Fold 4 IBS: 0.28235973586089635
Fold 5 IBS: 0.2108302118883095
[I 2024-04-18 14:52:49,033] Trial 44 finished with value: 0.23096240193914896 and parameters: {'l1_ratio': 0.8752945565953709}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.25000265054364335
Fold 2 IBS: 0.22912693118383348
Fold 3 IBS: 0.18251264614012383
Fold 4 IBS: 0.2824332155631413
Fold 5 IBS: 0.2108457220108775
[I 2024-04-18 14:52:49,352] Trial 45 finished with value: 0.2309842330883239 and parameters: {'l1_ratio': 0.8061825095621286}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.25027764547622805
Fold 2 IBS: 0.2290227023720746
Fold 3 IBS: 0.18273847014499947
Fold 4 IBS: 0.2825613284501782
Fold 5 IBS: 0.21077882294162045
[I 2024-04-18 14:52:49,665] Trial 46 finished with value: 0.23107579387702018 and parameters: {'l1_ratio': 0.41720751147142865}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24984842147680486
Fold 2 IBS: 0.2291532226758666
Fold 3 IBS: 0.18245761679107378
Fold 4 IBS: 0.28230529597675025
Fold 5 IBS: 0.21083880271313687
[I 2024-04-18 14:52:49,945] Trial 47 finished with value: 0.23092067192672644 and parameters: {'l1_ratio': 0.9972641789008958}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.25011301680498493
Fold 2 IBS: 0.22909502505601262
Fold 3 IBS: 0.1826002816397073
Fold 4 IBS: 0.2824796447926774
Fold 5 IBS: 0.21083920817605753
[I 2024-04-18 14:52:50,245] Trial 48 finished with value: 0.23102543529388794 and parameters: {'l1_ratio': 0.7127982691462118}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.2504079107751328
Fold 2 IBS: 0.22895125730263405
Fold 3 IBS: 0.18282471921574864
Fold 4 IBS: 0.2826423892316481
Fold 5 IBS: 0.21080714146056145
[I 2024-04-18 14:52:50,550] Trial 49 finished with value: 0.231126683597145 and parameters: {'l1_ratio': 0.355745098499332}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.2502232386956017
Fold 2 IBS: 0.22902848513140203

Fold 3 IBS: 0.18269021411781583
Fold 4 IBS: 0.2825506909005969
Fold 5 IBS: 0.21082218123065888
[I 2024-04-18 14:52:50,839] Trial 50 finished with value: 0.23106296201521506 and parameters: {'l1_ratio': 0.556147470734502}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24985451786514604
Fold 2 IBS: 0.22911757360111323
Fold 3 IBS: 0.18247745274466587
Fold 4 IBS: 0.28228934297583047
Fold 5 IBS: 0.210821944664204
[I 2024-04-18 14:52:51,195] Trial 51 finished with value: 0.23091216637019193 and parameters: {'l1_ratio': 0.9652982010146854}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24985561903272943
Fold 2 IBS: 0.22911096435706593
Fold 3 IBS: 0.18248112989225465
Fold 4 IBS: 0.2822863805799371
Fold 5 IBS: 0.21081882479087846
[I 2024-04-18 14:52:51,506] Trial 52 finished with value: 0.2309105837305731 and parameters: {'l1_ratio': 0.9595865292004943}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.2499664669296027
Fold 2 IBS: 0.22912195392996848
Fold 3 IBS: 0.18253564830931476
Fold 4 IBS: 0.28236346383885175
Fold 5 IBS: 0.2108341220022988
[I 2024-04-18 14:52:51,821] Trial 53 finished with value: 0.2309643310020073 and parameters: {'l1_ratio': 0.8818833490772311}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.249855918391452
Fold 2 IBS: 0.22910915815950444
Fold 3 IBS: 0.18248213477933717
Fold 4 IBS: 0.28228557099460766
Fold 5 IBS: 0.21081797193988305
[I 2024-04-18 14:52:52,162] Trial 54 finished with value: 0.23091015085295688 and parameters: {'l1_ratio': 0.9580368622927092}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24997291562865018
Fold 2 IBS: 0.2290777476341483
Fold 3 IBS: 0.18247949799020505
Fold 4 IBS: 0.28234359825270483
Fold 5 IBS: 0.21081330460986966
[I 2024-04-18 14:52:52,484] Trial 55 finished with value: 0.23093741282311558 and parameters: {'l1_ratio': 0.8478207034603297}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.2498491703709871
Fold 2 IBS: 0.22914892576780613
Fold 3 IBS: 0.18246000778582577
Fold 4 IBS: 0.2823033701945002
Fold 5 IBS: 0.21083676893730513
[I 2024-04-18 14:52:52,815] Trial 56 finished with value: 0.23091964861128486 and parameters: {'l1_ratio': 0.9933042895759677}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.25030736433214534
Fold 2 IBS: 0.22897864537949517
Fold 3 IBS: 0.18269751946369298
Fold 4 IBS: 0.28255645174057037
Fold 5 IBS: 0.21080586897903314
[I 2024-04-18 14:52:53,221] Trial 57 finished with value: 0.23106916997898738 and parameters: {'l1_ratio': 0.4854369177503025}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.2499634658012413
Fold 2 IBS: 0.22914164544073382
Fold 3 IBS: 0.18252366431921802
Fold 4 IBS: 0.2823723143080857
Fold 5 IBS: 0.21084341328134423
[I 2024-04-18 14:52:53,635] Trial 58 finished with value: 0.2309689006301246 and parameters: {'l1_ratio': 0.8979139665436123}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.2500065879696181
Fold 2 IBS: 0.2291028278389218
Fold 3 IBS: 0.18252748244553252
Fold 4 IBS: 0.2824223376640781
Fold 5 IBS: 0.21083438145193595
[I 2024-04-18 14:52:54,030] Trial 59 finished with value: 0.23097872347401732 and parameters: {'l1_ratio': 0.7887822986616795}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24997466009801333
Fold 2 IBS: 0.22906706177873026
Fold 3 IBS: 0.1824865066709762
Fold 4 IBS: 0.2823380020214866
Fold 5 IBS: 0.21080745242113758
[I 2024-04-18 14:52:54,381] Trial 60 finished with value: 0.2309347365980688 and parameters: {'l1_ratio': 0.8386797446261413}. Best is trial 21 with value: 0.2309065397817624.
Fold 1 IBS: 0.24985899865738595
Fold 2 IBS: 0.22909033166618062
Fold 3 IBS: 0.1824926025736938
Fold 4 IBS: 0.2822771321826494
Fold 5 IBS: 0.21080908778939608
[I 2024-04-18 14:52:54,725] Trial 61 finished with value: 0.23090563057386118 and parameters: {'l1_ratio': 0.9421648828497428}. Best is trial 61 with value: 0.23090563057386118.
Fold 1 IBS: 0.24985762695641947
Fold 2 IBS: 0.22909877058720182
Fold 3 IBS: 0.18248791381736615
Fold 4 IBS: 0.28228091492187984
Fold 5 IBS: 0.21081306887711562
[I 2024-04-18 14:52:55,074] Trial 62 finished with value: 0.2309076590319966 and parameters: {'l1_ratio': 0.9492167780236825}. Best is trial 61 with value: 0.23090563057386118.
Fold 1 IBS: 0.24985916735754893
Fold 2 IBS: 0.22908928754529542
Fold 3 IBS: 0.18249318343093648
Fold 4 IBS: 0.2822766641491405
Fold 5 IBS: 0.21080859536402088
[I 2024-04-18 14:52:55,407] Trial 63 finished with value: 0.23090537956938842 and parameters: {'l1_ratio': 0.9412993350277873}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24996497031272139
Fold 2 IBS: 0.22913183957064118
Fold 3 IBS: 0.1825296326206246
Fold 4 IBS: 0.282367906978604
Fold 5 IBS: 0.21083878495875336
[I 2024-04-18 14:52:55,785] Trial 64 finished with value: 0.2309666268882689 and parameters: {'l1_ratio': 0.8898616774236563}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.2498612698284391
Fold 2 IBS: 0.22907790661268082
Fold 3 IBS: 0.18250048787438336
Fold 4 IBS: 0.2822707781960961
Fold 5 IBS: 0.21086132169556324
[I 2024-04-18 14:52:56,125] Trial 65 finished with value: 0.23091435284143252 and parameters: {'l1_ratio': 0.9305429006482043}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.2506345795430773
Fold 2 IBS: 0.22893834934108112
Fold 3 IBS: 0.1827326434202604
Fold 4 IBS: 0.2827203479679894
Fold 5 IBS: 0.21077584730553625
[I 2024-04-18 14:52:56,547] Trial 66 finished with value: 0.2311603535155889 and parameters: {'l1_ratio': 0.16732626909512405}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24997200604961659
Fold 2 IBS: 0.22908415097629536
Fold 3 IBS: 0.18247589216923088
Fold 4 IBS: 0.2823464770693668
Fold 5 IBS: 0.21081631692623837
[I 2024-04-18 14:52:56,930] Trial 67 finished with value: 0.2309389686381496 and parameters: {'l1_ratio': 0.8525978360672721}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.2500193146575315
Fold 2 IBS: 0.22904907797797264
Fold 3 IBS: 0.1825616452132548
Fold 4 IBS: 0.2825057007905573
Fold 5 IBS: 0.21080831500817562
[I 2024-04-18 14:52:57,301] Trial 68 finished with value: 0.2309888107294984 and parameters: {'l1_ratio': 0.7513068273715421}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24984837213601058
Fold 2 IBS: 0.2291535049974449
Fold 3 IBS: 0.18245745969309882
Fold 4 IBS: 0.28230542250623925
Fold 5 IBS: 0.21083893635703457
[I 2024-04-18 14:52:57,658] Trial 69 finished with value: 0.23092073913796565 and parameters: {'l1_ratio': 0.9975254168287264}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24996210737914915
Fold 2 IBS: 0.22915039060767078
Fold 3 IBS: 0.18251834139475917
Fold 4 IBS: 0.2823762443724844
Fold 5 IBS: 0.21084754288740115
[I 2024-04-18 14:52:58,036] Trial 70 finished with value: 0.23097092532829294 and parameters: {'l1_ratio': 0.905213382561468}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24985878674155634
Fold 2 IBS: 0.22909164130205356
Fold 3 IBS: 0.1824918740038045
Fold 4 IBS: 0.28227771923262307
Fold 5 IBS: 0.21080970548575875
[I 2024-04-18 14:52:58,509] Trial 71 finished with value: 0.23090594535315923 and parameters: {'l1_ratio': 0.9432526894043739}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.2498599360269804
Fold 2 IBS: 0.22908451247403652
Fold 3 IBS: 0.182495839830895
Fold 4 IBS: 0.282274523674436
Fold 5 IBS: 0.21086493419020383
[I 2024-04-18 14:52:58,969] Trial 72 finished with value: 0.23091594923931033 and parameters: {'l1_ratio': 0.9373602317388401}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24985277183028004
Fold 2 IBS: 0.22912794376583692
Fold 3 IBS: 0.18247168296034197
Fold 4 IBS: 0.28229399095987306
Fold 5 IBS: 0.2108268448795301
[I 2024-04-18 14:52:59,382] Trial 73 finished with value: 0.23091464687917243 and parameters: {'l1_ratio': 0.97439236151151}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.2499629456282529
Fold 2 IBS: 0.2291450062305828
Fold 3 IBS: 0.18252161877407913
Fold 4 IBS: 0.28237382466758865
Fold 5 IBS: 0.2108450000497807
[I 2024-04-18 14:52:59,737] Trial 74 finished with value: 0.23096967907005683 and parameters: {'l1_ratio': 0.900705758715514}. Best is trial 63 with value: 0.23090537956938842.

Fold 1 IBS: 0.24997685100061245
Fold 2 IBS: 0.22905113084183792
Fold 3 IBS: 0.18249549042198562
Fold 4 IBS: 0.2824457869682151
Fold 5 IBS: 0.21080036692776385
[I 2024-04-18 14:53:00,128] Trial 75 finished with value: 0.230953925232083 and parameters: {'l1_ratio': 0.8272338246472453}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24996921705384784
Fold 2 IBS: 0.2291034328746273
Fold 3 IBS: 0.18250728530449697
Fold 4 IBS: 0.282355145135055
Fold 5 IBS: 0.21082539303666184
[I 2024-04-18 14:53:00,510] Trial 76 finished with value: 0.2309520946809378 and parameters: {'l1_ratio': 0.8672987568176258}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24985859132527408
Fold 2 IBS: 0.22909284704859992
Fold 3 IBS: 0.18249120322574033
Fold 4 IBS: 0.2822782597115513
Fold 5 IBS: 0.2108102742239355
[I 2024-04-18 14:53:00,868] Trial 77 finished with value: 0.2309062351070202 and parameters: {'l1_ratio': 0.9442563293619028}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.2498611862610325
Fold 2 IBS: 0.22907843189534147
Fold 3 IBS: 0.18250019519753863
Fold 4 IBS: 0.28227101404705696
Fold 5 IBS: 0.21086154912871988
[I 2024-04-18 14:53:01,239] Trial 78 finished with value: 0.23091447530593787 and parameters: {'l1_ratio': 0.9309693815554677}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24985152366597005
Fold 2 IBS: 0.22913527672737888
Fold 3 IBS: 0.182467602880986
Fold 4 IBS: 0.2822972775488963
Fold 5 IBS: 0.21083031171533453
[I 2024-04-18 14:53:01,620] Trial 79 finished with value: 0.23091639850771317 and parameters: {'l1_ratio': 0.9809226662400009}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24996891377347982
Fold 2 IBS: 0.22910549869551453
Fold 3 IBS: 0.18250605906418393
Fold 4 IBS: 0.2823560737504797
Fold 5 IBS: 0.21082636619040585
[I 2024-04-18 14:53:01,993] Trial 80 finished with value: 0.2309525822948128 and parameters: {'l1_ratio': 0.8689025803626756}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24985871118212083
Fold 2 IBS: 0.22909210773291216
Fold 3 IBS: 0.18249161452047447
Fold 4 IBS: 0.2822779283116817
Fold 5 IBS: 0.21080992549162533
[I 2024-04-18 14:53:02,397] Trial 81 finished with value: 0.2309060574477629 and parameters: {'l1_ratio': 0.9436406953202119}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24985942618103502
Fold 2 IBS: 0.2290876829368532
Fold 3 IBS: 0.1824940760895801
Fold 4 IBS: 0.2822759448706122
Fold 5 IBS: 0.21086630531611628
[I 2024-04-18 14:53:02,766] Trial 82 finished with value: 0.23091668707883936 and parameters: {'l1_ratio': 0.9399721183077996}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.2499644486503509
Fold 2 IBS: 0.22913525448854394
Fold 3 IBS: 0.1825275543783303
Fold 4 IBS: 0.2823694417612485
Fold 5 IBS: 0.21084039636533927
[I 2024-04-18 14:53:03,114] Trial 83 finished with value: 0.2309674191287626 and parameters: {'l1_ratio': 0.8926499487325421}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.2498629725587404
Fold 2 IBS: 0.22906712542521154
Fold 3 IBS: 0.1825064947823701
Fold 4 IBS: 0.2822659373885319
Fold 5 IBS: 0.21085665496402253
[I 2024-04-18 14:53:03,481] Trial 84 finished with value: 0.23091183702377532 and parameters: {'l1_ratio': 0.9218713441365886}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.25013351802944644
Fold 2 IBS: 0.2290289721987
Fold 3 IBS: 0.18261328943242894
Fold 4 IBS: 0.28250295763526795
Fold 5 IBS: 0.2108152556970318
[I 2024-04-18 14:53:03,881] Trial 85 finished with value: 0.23101879859857505 and parameters: {'l1_ratio': 0.6114164712527408}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24985279860147497
Fold 2 IBS: 0.2291277857606692
Fold 3 IBS: 0.18247177087352973
Fold 4 IBS: 0.2822939201420132
Fold 5 IBS: 0.2108267701950751
[I 2024-04-18 14:53:04,252] Trial 86 finished with value: 0.23091460911455242 and parameters: {'l1_ratio': 0.9742525678706415}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24985816072527087
Fold 2 IBS: 0.22909549744014088
Fold 3 IBS: 0.1824897347556535
Fold 4 IBS: 0.2822794477488001
Fold 5 IBS: 0.2108115245268831
[I 2024-04-18 14:53:04,613] Trial 87 finished with value: 0.23090687303934967 and parameters: {'l1_ratio': 0.946469658169697}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.25000492361343774
Fold 2 IBS: 0.22911312556363542
Fold 3 IBS: 0.18252114452435458
Fold 4 IBS: 0.2824269852866021
Fold 5 IBS: 0.2108392245566837
[I 2024-04-18 14:53:04,970] Trial 88 finished with value: 0.2309810807089427 and parameters: {'l1_ratio': 0.796127411922162}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.2499613655210759
Fold 2 IBS: 0.2291551239537038
Fold 3 IBS: 0.18251546011038386
Fold 4 IBS: 0.28237837143682265
Fold 5 IBS: 0.2108497789255088
[I 2024-04-18 14:53:05,357] Trial 89 finished with value: 0.23097201998949898 and parameters: {'l1_ratio': 0.9092118485870633}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24984833633287956
Fold 2 IBS: 0.22915370979824598
Fold 3 IBS: 0.1824573457314863
Fold 4 IBS: 0.28230551429277223
Fold 5 IBS: 0.21083903330593431
[I 2024-04-18 14:53:05,788] Trial 90 finished with value: 0.23092078789226367 and parameters: {'l1_ratio': 0.9977150053139332}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24985759874801453
Fold 2 IBS: 0.22909894319019072
Fold 3 IBS: 0.18248781779310086
Fold 4 IBS: 0.2822809922899387
Fold 5 IBS: 0.21081315032358341
[I 2024-04-18 14:53:06,214] Trial 91 finished with value: 0.23090770046896564 and parameters: {'l1_ratio': 0.9493620653781539}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24985619226787467
Fold 2 IBS: 0.22910750213741735
Fold 3 IBS: 0.18248305610920387
Fold 4 IBS: 0.28228482871763044
Fold 5 IBS: 0.21081719007778718
[I 2024-04-18 14:53:06,817] Trial 92 finished with value: 0.2309097538619827 and parameters: {'l1_ratio': 0.9566202446334778}. Best is trial 63 with value: 0.23090537956938842.
Fold 1 IBS: 0.24985928431917412
Fold 2 IBS: 0.2290885628321039
Fold 3 IBS: 0.18249358659634923
Fold 4 IBS: 0.2822763392911355
Fold 5 IBS: 0.21080825359050062
[I 2024-04-18 14:53:07,411] Trial 93 finished with value: 0.23090520532585268 and parameters: {'l1_ratio': 0.9406994609406157}. Best is trial 93 with value: 0.23090520532585268.
Fold 1 IBS: 0.24997709585692127
Fold 2 IBS: 0.22904932713048845
Fold 3 IBS: 0.18249650751093213
Fold 4 IBS: 0.28244504187585984
Fold 5 IBS: 0.21079951902581312
[I 2024-04-18 14:53:07,973] Trial 94 finished with value: 0.23095349828000294 and parameters: {'l1_ratio': 0.8259566973317382}. Best is trial 93 with value: 0.23090520532585268.
Fold 1 IBS: 0.24996013510268833
Fold 2 IBS: 0.22905954119088046
Fold 3 IBS: 0.18251072028518395
Fold 4 IBS: 0.2823818701294966
Fold 5 IBS: 0.2108534583558135
[I 2024-04-18 14:53:08,487] Trial 95 finished with value: 0.23095314501281256 and parameters: {'l1_ratio': 0.9158631560693823}. Best is trial 93 with value: 0.23090520532585268.
Fold 1 IBS: 0.24997049850077038
Fold 2 IBS: 0.22909463809638592
Fold 3 IBS: 0.18246998641568488
Fold 4 IBS: 0.28235119162362254
Fold 5 IBS: 0.21082125135936616
[I 2024-04-18 14:53:09,032] Trial 96 finished with value: 0.23094151319916598 and parameters: {'l1_ratio': 0.8605337605952325}. Best is trial 93 with value: 0.23090520532585268.
Fold 1 IBS: 0.24996605445777606
Fold 2 IBS: 0.22912469170495367
Fold 3 IBS: 0.18253398236964455
Fold 4 IBS: 0.2823646943706637
Fold 5 IBS: 0.21083541311401482
[I 2024-04-18 14:53:09,559] Trial 97 finished with value: 0.23096496720341056 and parameters: {'l1_ratio': 0.8840791501598179}. Best is trial 93 with value: 0.23090520532585268.
Fold 1 IBS: 0.24985274242804464
Fold 2 IBS: 0.22912811726422713
Fold 3 IBS: 0.18247158642674835
Fold 4 IBS: 0.2822940687217461
Fold 5 IBS: 0.21082692688797483
[I 2024-04-18 14:53:10,008] Trial 98 finished with value: 0.2309146883457482 and parameters: {'l1_ratio': 0.974545906897655}. Best is trial 93 with value: 0.23090520532585268.
Fold 1 IBS: 0.2498598061551906
Fold 2 IBS: 0.2290853212936204
Fold 3 IBS: 0.18249538988339228
Fold 4 IBS: 0.2822748862384322
Fold 5 IBS: 0.2108652839603144
[I 2024-04-18 14:53:10,597] Trial 99 finished with value: 0.23091613750618997 and parameters: {'l1_ratio': 0.9380252330100647}. Best is trial 93 with value: 0.23090520532585268.


* Best trial for IBS:
 FrozenTrial(number=93, state=TrialState.COMPLETE, values=[0.23090520532585268], datetime_start=datetime.datetime(2024, 4, 18, 14, 53, 6, 826773), datetime_complete=datetime.datetime(2024, 4, 18, 14, 53, 7, 411217), params={'l1_ratio': 0.9406994609406157}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=93, value=None)


* Best Score for IBS:
 0.23090520532585268

In [42]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [43]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.631
train_ibs:  0.231

#### Test

In [44]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [45]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.6422698927560148)

test_cindex : 0.599

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.9406994609406157)

test_ibs:  0.25

In [46]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [47]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 14:53:11,147] A new study created in memory with name: no-name-521d7482-4f7d-4cd3-ba32-d2f4cbc48b11

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5637450199203188
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.5579399141630901
[I 2024-04-18 14:53:16,199] Trial 0 finished with value: 0.6236873379146901 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6236873379146901.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.6137339055793991
[I 2024-04-18 14:53:19,803] Trial 1 finished with value: 0.6391578259478147 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.6391578259478147.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.5968992248062015
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6254752851711026
Fold 5 C-index: 0.6137339055793991
[I 2024-04-18 14:53:23,888] Trial 2 finished with value: 0.6222254976404582 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.6391578259478147.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 14:53:25,379] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.6391578259478147.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 14:53:27,374] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.6391578259478147.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6266094420600858
[I 2024-04-18 14:53:33,150] Trial 5 finished with value: 0.64308736820412 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.64308736820412.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6007751937984496
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.6137339055793991
[I 2024-04-18 14:53:37,678] Trial 6 finished with value: 0.6287227687473426 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.64308736820412.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 14:53:40,288] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.64308736820412.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.4313304721030043
[I 2024-04-18 14:53:48,455] Trial 8 finished with value: 0.48626609442060087 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.64308736820412.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:53:53,366] Trial 9 finished with value: 0.6368833150362707 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 5 with value: 0.64308736820412.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 14:53:54,043] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 5 with value: 0.64308736820412.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.5708154506437768
[I 2024-04-18 14:53:57,012] Trial 11 finished with value: 0.6385842492925254 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11629432582260082, 'warm_start': False}. Best is trial 5 with value: 0.64308736820412.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.5965665236051502
[I 2024-04-18 14:54:04,070] Trial 12 finished with value: 0.6481325757936397 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.48792003918647286, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10661539149160613, 'warm_start': False}. Best is trial 12 with value: 0.6481325757936397.
Fold 1 C-index: 0.5876494023904383
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.592274678111588
[I 2024-04-18 14:54:11,189] Trial 13 finished with value: 0.6220597178450147 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 490, 'oob_score': False, 'max_samples': 0.4760095384782845, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.008606277463368957, 'warm_start': False}. Best is trial 12 with value: 0.6481325757936397.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7893617021276595
Fold 4 C-index: 0.6711026615969582
Fold 5 C-index: 0.5987124463519313
[I 2024-04-18 14:54:13,981] Trial 14 finished with value: 0.6653577067449185 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.4939684434654238, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10493802079862766, 'warm_start': True}. Best is trial 14 with value: 0.6653577067449185.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 14:54:17,530] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 385, 'oob_score': True, 'max_samples': 0.3692598016141903, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18886845448542633, 'warm_start': True}. Best is trial 14 with value: 0.6653577067449185.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6437768240343348
[I 2024-04-18 14:54:22,616] Trial 16 finished with value: 0.7022584720759661 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.47618376614423075, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08910016992059805, 'warm_start': True}. Best is trial 16 with value: 0.7022584720759661.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.6996124031007752
Fold 3 C-index: 0.8148936170212766
Fold 4 C-index: 0.564638783269962
Fold 5 C-index: 0.575107296137339
[I 2024-04-18 14:54:26,812] Trial 17 finished with value: 0.6352328900253925 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 493, 'oob_score': True, 'max_samples': 0.1424705672746025, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07035180657094657, 'warm_start': True}. Best is trial 16 with value: 0.7022584720759661.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 14:54:30,986] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 431, 'oob_score': True, 'max_samples': 0.3182792897782868, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 16 with value: 0.7022584720759661.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6094420600858369
[I 2024-04-18 14:54:35,031] Trial 19 finished with value: 0.6710974631964393 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 448, 'oob_score': True, 'max_samples': 0.5412492865047388, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1549160802819755, 'warm_start': True}. Best is trial 16 with value: 0.7022584720759661.
Fold 1 C-index: 0.48804780876494025
Fold 2 C-index: 0.6647286821705426
Fold 3 C-index: 0.7893617021276595
Fold 4 C-index: 0.6026615969581749
Fold 5 C-index: 0.5493562231759657
[I 2024-04-18 14:54:35,298] Trial 20 finished with value: 0.6188312026394566 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 6, 'oob_score': True, 'max_samples': 0.4110662263998348, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17106374970541133, 'warm_start': True}. Best is trial 16 with value: 0.7022584720759661.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6763565891472868
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6051502145922747
[I 2024-04-18 14:54:39,750] Trial 21 finished with value: 0.6686670875502733 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.546386512688724, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14443114491291786, 'warm_start': True}. Best is trial 16 with value: 0.7022584720759661.
Fold 1 C-index: 0.5597609561752988
Fold 2 C-index: 0.6724806201550387
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6115879828326181
[I 2024-04-18 14:54:43,936] Trial 22 finished with value: 0.6658470541349939 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.5556781228914751, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22598024591584034, 'warm_start': True}. Best is trial 16 with value: 0.7022584720759661.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.687984496124031
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:54:47,656] Trial 23 finished with value: 0.6872131612516434 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 450, 'oob_score': True, 'max_samples': 0.670033360226311, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1710885179921677, 'warm_start': True}. Best is trial 16 with value: 0.7022584720759661.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6647286821705426
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6266094420600858
[I 2024-04-18 14:54:50,714] Trial 24 finished with value: 0.6737115332187834 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 415, 'oob_score': True, 'max_samples': 0.6787377214887289, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1934116142410442, 'warm_start': True}. Best is trial 16 with value: 0.7022584720759661.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6180257510729614
[I 2024-04-18 14:54:53,806] Trial 25 finished with value: 0.6758735136856701 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 413, 'oob_score': True, 'max_samples': 0.7058190656191217, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20307948537323212, 'warm_start': True}. Best is trial 16 with value: 0.7022584720759661.
Fold 1 C-index: 0.6075697211155379
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.7680851063829788
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.5836909871244635
[I 2024-04-18 14:54:56,526] Trial 26 finished with value: 0.6662450287541712 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 20, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.8072223328109674, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.254470861710628, 'warm_start': True}. Best is trial 16 with value: 0.7022584720759661.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6266094420600858
[I 2024-04-18 14:55:00,154] Trial 27 finished with value: 0.6818636796608628 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 15, 'n_estimators': 470, 'oob_score': True, 'max_samples': 0.810316318149708, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07045279619737542, 'warm_start': True}. Best is trial 16 with value: 0.7022584720759661.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.687984496124031
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 14:55:03,989] Trial 28 finished with value: 0.6954082184445287 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 467, 'oob_score': True, 'max_samples': 0.9797927134636605, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.061563422445184535, 'warm_start': True}. Best is trial 16 with value: 0.7022584720759661.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.6841085271317829
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6695278969957081
[I 2024-04-18 14:55:07,586] Trial 29 finished with value: 0.7042234143757383 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.8759158669512948, 'max_features': None, 'min_weight_fraction_leaf': 0.055212101437599685, 'warm_start': True}. Best is trial 29 with value: 0.7042234143757383.

Fold 1 C-index: 0.603585657370518
Fold 2 C-index: 0.6957364341085271
Fold 3 C-index: 0.7978723404255319
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.6630901287553648
[I 2024-04-18 14:55:11,068] Trial 30 finished with value: 0.7071899919798972 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 337, 'oob_score': True, 'max_samples': 0.9729345698205899, 'max_features': None, 'min_weight_fraction_leaf': 0.03900919066367596, 'warm_start': True}. Best is trial 30 with value: 0.7071899919798972.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.687984496124031
Fold 3 C-index: 0.7978723404255319
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.6630901287553648
[I 2024-04-18 14:55:14,122] Trial 31 finished with value: 0.7048427916339939 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 345, 'oob_score': True, 'max_samples': 0.9530293221459376, 'max_features': None, 'min_weight_fraction_leaf': 0.05067801563590064, 'warm_start': True}. Best is trial 30 with value: 0.7071899919798972.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6841085271317829
Fold 3 C-index: 0.7851063829787234
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 14:55:17,081] Trial 32 finished with value: 0.6847447870963912 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 340, 'oob_score': True, 'max_samples': 0.8814784689215808, 'max_features': None, 'min_weight_fraction_leaf': 0.0448180204188732, 'warm_start': True}. Best is trial 30 with value: 0.7071899919798972.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.687984496124031
Fold 3 C-index: 0.8148936170212766
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 14:55:19,069] Trial 33 finished with value: 0.7032870797103791 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 18, 'n_estimators': 219, 'oob_score': True, 'max_samples': 0.9939607790151206, 'max_features': None, 'min_weight_fraction_leaf': 0.004060940201152219, 'warm_start': True}. Best is trial 30 with value: 0.7071899919798972.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.687984496124031
Fold 3 C-index: 0.8021276595744681
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 14:55:21,012] Trial 34 finished with value: 0.6945411686051841 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 20, 'n_estimators': 232, 'oob_score': True, 'max_samples': 0.9912248083375867, 'max_features': None, 'min_weight_fraction_leaf': 0.002613044815809939, 'warm_start': True}. Best is trial 30 with value: 0.7071899919798972.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.6996124031007752
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6523605150214592
[I 2024-04-18 14:55:22,409] Trial 35 finished with value: 0.7011570672229386 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 18, 'n_estimators': 154, 'oob_score': True, 'max_samples': 0.8619960073820749, 'max_features': None, 'min_weight_fraction_leaf': 0.041799651789036885, 'warm_start': True}. Best is trial 30 with value: 0.7071899919798972.
Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.6724806201550387
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6545064377682404
[I 2024-04-18 14:55:24,552] Trial 36 finished with value: 0.6831950214042561 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 17, 'n_estimators': 260, 'oob_score': True, 'max_samples': 0.9168749920357635, 'max_features': None, 'min_weight_fraction_leaf': 0.1356469965470356, 'warm_start': True}. Best is trial 30 with value: 0.7071899919798972.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.8063829787234043
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6502145922746781
[I 2024-04-18 14:55:27,276] Trial 37 finished with value: 0.6974582803834443 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 19, 'n_estimators': 283, 'oob_score': True, 'max_samples': 0.9481697814073236, 'max_features': None, 'min_weight_fraction_leaf': 0.030553254373809173, 'warm_start': True}. Best is trial 30 with value: 0.7071899919798972.
Fold 1 C-index: 0.5717131474103586
Fold 2 C-index: 0.6763565891472868
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.5944206008583691
[I 2024-04-18 14:55:29,996] Trial 38 finished with value: 0.6626457901593618 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 332, 'oob_score': True, 'max_samples': 0.7594299714587174, 'max_features': None, 'min_weight_fraction_leaf': 0.08046975632749177, 'warm_start': True}. Best is trial 30 with value: 0.7071899919798972.
Fold 1 C-index: 0.603585657370518
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6909871244635193
[I 2024-04-18 14:55:31,824] Trial 39 finished with value: 0.7124535126615805 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 193, 'oob_score': True, 'max_samples': 0.8520315229721027, 'max_features': None, 'min_weight_fraction_leaf': 0.00396656774217272, 'warm_start': True}. Best is trial 39 with value: 0.7124535126615805.
Fold 1 C-index: 0.5637450199203188
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.8
Fold 4 C-index: 0.6977186311787072
Fold 5 C-index: 0.6180257510729614
[I 2024-04-18 14:55:33,603] Trial 40 finished with value: 0.6684560199692812 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 166, 'oob_score': True, 'max_samples': 0.8523620985176356, 'max_features': None, 'min_weight_fraction_leaf': 0.38462517942590646, 'warm_start': True}. Best is trial 39 with value: 0.7124535126615805.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7034883720930233
Fold 3 C-index: 0.8276595744680851
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6716738197424893
[I 2024-04-18 14:55:35,883] Trial 41 finished with value: 0.7137711458621767 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 15, 'n_estimators': 228, 'oob_score': True, 'max_samples': 0.9999406435215973, 'max_features': None, 'min_weight_fraction_leaf': 0.00032061073140142666, 'warm_start': True}. Best is trial 41 with value: 0.7137711458621767.
Fold 1 C-index: 0.603585657370518
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7978723404255319
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6652360515021459
[I 2024-04-18 14:55:38,068] Trial 42 finished with value: 0.701923123238364 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 242, 'oob_score': True, 'max_samples': 0.9404587646594021, 'max_features': None, 'min_weight_fraction_leaf': 0.034117520204287606, 'warm_start': True}. Best is trial 41 with value: 0.7137711458621767.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.687984496124031
Fold 3 C-index: 0.7936170212765957
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6545064377682404
[I 2024-04-18 14:55:40,020] Trial 43 finished with value: 0.6980379453882187 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 15, 'n_estimators': 200, 'oob_score': True, 'max_samples': 0.7630755401354222, 'max_features': None, 'min_weight_fraction_leaf': 0.05266231183563491, 'warm_start': True}. Best is trial 41 with value: 0.7137711458621767.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.7228682170542635
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7188841201716738
[I 2024-04-18 14:55:41,724] Trial 44 finished with value: 0.7183524947699149 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 116, 'oob_score': True, 'max_samples': 0.9026224597697206, 'max_features': None, 'min_weight_fraction_leaf': 0.023667861188109922, 'warm_start': True}. Best is trial 44 with value: 0.7183524947699149.

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7978723404255319
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.628755364806867
[I 2024-04-18 14:55:42,322] Trial 45 finished with value: 0.6925622410763188 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 90, 'oob_score': False, 'max_samples': 0.9104218782867626, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.014651378796517898, 'warm_start': True}. Best is trial 44 with value: 0.7183524947699149.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.655893536121673
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:44,400] Trial 46 finished with value: 0.6474315258883976 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.9625815464531211, 'max_features': None, 'min_weight_fraction_leaf': 0.09882567480173948, 'warm_start': False}. Best is trial 44 with value: 0.7183524947699149.
Fold 1 C-index: 0.603585657370518
Fold 2 C-index: 0.7073643410852714
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6652360515021459
[I 2024-04-18 14:55:45,226] Trial 47 finished with value: 0.7052283110351919 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.8428143530928882, 'max_features': None, 'min_weight_fraction_leaf': 0.02833889086638622, 'warm_start': True}. Best is trial 44 with value: 0.7183524947699149.
Fold 1 C-index: 0.603585657370518
Fold 2 C-index: 0.5697674418604651
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.6368821292775665
Fold 5 C-index: 0.6266094420600858
[I 2024-04-18 14:55:48,564] Trial 48 finished with value: 0.6329008490073441 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 172, 'oob_score': False, 'max_samples': 0.8275919164956825, 'max_features': None, 'min_weight_fraction_leaf': 0.02307368578502946, 'warm_start': False}. Best is trial 44 with value: 0.7183524947699149.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.7112403100775194
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:55:49,344] Trial 49 finished with value: 0.7040036174979905 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8973516930388812, 'max_features': None, 'min_weight_fraction_leaf': 0.0005889502785425258, 'warm_start': True}. Best is trial 44 with value: 0.7183524947699149.
Fold 1 C-index: 0.5756972111553785
Fold 2 C-index: 0.6647286821705426
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6051502145922747
[I 2024-04-18 14:55:50,005] Trial 50 finished with value: 0.663353551815821 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.7623535242377307, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13108155823075382, 'warm_start': True}. Best is trial 44 with value: 0.7183524947699149.
Fold 1 C-index: 0.603585657370518
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.7081545064377682
[I 2024-04-18 14:55:51,599] Trial 51 finished with value: 0.7182451058892547 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 295, 'oob_score': False, 'max_samples': 0.9550540174105672, 'max_features': None, 'min_weight_fraction_leaf': 0.031097718111434847, 'warm_start': True}. Best is trial 44 with value: 0.7183524947699149.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.6824034334763949
[I 2024-04-18 14:55:52,605] Trial 52 finished with value: 0.7055445796401207 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 186, 'oob_score': False, 'max_samples': 0.8406478529401548, 'max_features': None, 'min_weight_fraction_leaf': 0.08297575238112394, 'warm_start': True}. Best is trial 44 with value: 0.7183524947699149.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.7167381974248928
[I 2024-04-18 14:55:54,363] Trial 53 finished with value: 0.7260142171443418 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.9989296318282489, 'max_features': None, 'min_weight_fraction_leaf': 0.08640218611993272, 'warm_start': True}. Best is trial 53 with value: 0.7260142171443418.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7639484978540773
[I 2024-04-18 14:55:55,901] Trial 54 finished with value: 0.739512389968772 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 297, 'oob_score': False, 'max_samples': 0.9948001255439096, 'max_features': None, 'min_weight_fraction_leaf': 0.022748194838681752, 'warm_start': True}. Best is trial 54 with value: 0.739512389968772.
Fold 1 C-index: 0.5756972111553785
Fold 2 C-index: 0.6763565891472868
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6437768240343348
[I 2024-04-18 14:55:57,426] Trial 55 finished with value: 0.6723721761577488 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.9316484498227704, 'max_features': None, 'min_weight_fraction_leaf': 0.2886607381144328, 'warm_start': True}. Best is trial 54 with value: 0.739512389968772.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:56:02,628] Trial 56 finished with value: 0.6415803013412628 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.9181205921447908, 'max_features': None, 'min_weight_fraction_leaf': 0.11693488133794623, 'warm_start': False}. Best is trial 54 with value: 0.739512389968772.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.7339055793991416
[I 2024-04-18 14:56:04,060] Trial 57 finished with value: 0.7301322797816182 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 17, 'n_estimators': 265, 'oob_score': False, 'max_samples': 0.9991528403187265, 'max_features': None, 'min_weight_fraction_leaf': 0.01851673367639778, 'warm_start': True}. Best is trial 54 with value: 0.739512389968772.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 14:56:05,377] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 259, 'oob_score': False, 'max_samples': 0.9745668228618354, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 54 with value: 0.739512389968772.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7639484978540773
[I 2024-04-18 14:56:07,145] Trial 59 finished with value: 0.7378428944394264 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.9953876757422767, 'max_features': None, 'min_weight_fraction_leaf': 0.07197856933089326, 'warm_start': True}. Best is trial 54 with value: 0.739512389968772.

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5968992248062015
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:56:14,151] Trial 60 finished with value: 0.6383130485601036 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.8944568870011637, 'max_features': None, 'min_weight_fraction_leaf': 0.08705817390452884, 'warm_start': False}. Best is trial 54 with value: 0.739512389968772.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.776824034334764
[I 2024-04-18 14:56:15,643] Trial 61 finished with value: 0.7405302282421411 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 311, 'oob_score': False, 'max_samples': 0.9921267835587064, 'max_features': None, 'min_weight_fraction_leaf': 0.07154358373907602, 'warm_start': True}. Best is trial 61 with value: 0.7405302282421411.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7725321888412017
[I 2024-04-18 14:56:16,839] Trial 62 finished with value: 0.7396502401928744 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 269, 'oob_score': False, 'max_samples': 0.9498189615701634, 'max_features': None, 'min_weight_fraction_leaf': 0.07042741827330812, 'warm_start': True}. Best is trial 61 with value: 0.7405302282421411.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7854077253218884
[I 2024-04-18 14:56:18,323] Trial 63 finished with value: 0.7412257006774075 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 273, 'oob_score': False, 'max_samples': 0.929417586372101, 'max_features': None, 'min_weight_fraction_leaf': 0.06923323360905928, 'warm_start': True}. Best is trial 63 with value: 0.7412257006774075.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7553648068669528
[I 2024-04-18 14:56:20,318] Trial 64 finished with value: 0.7306722739493783 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.931119635578536, 'max_features': None, 'min_weight_fraction_leaf': 0.11978002971931007, 'warm_start': True}. Best is trial 63 with value: 0.7412257006774075.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7811158798283262
[I 2024-04-18 14:56:21,942] Trial 65 finished with value: 0.7404253070044889 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.933224852766038, 'max_features': None, 'min_weight_fraction_leaf': 0.06971903501734972, 'warm_start': True}. Best is trial 63 with value: 0.7412257006774075.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.759656652360515
[I 2024-04-18 14:56:23,541] Trial 66 finished with value: 0.7315669995233305 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 317, 'oob_score': False, 'max_samples': 0.9359059963347472, 'max_features': None, 'min_weight_fraction_leaf': 0.12115155187536888, 'warm_start': True}. Best is trial 63 with value: 0.7412257006774075.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7939914163090128
[I 2024-04-18 14:56:25,362] Trial 67 finished with value: 0.750790891168273 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.9565460360649312, 'max_features': None, 'min_weight_fraction_leaf': 0.06679516365853302, 'warm_start': True}. Best is trial 67 with value: 0.750790891168273.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7682403433476395
[I 2024-04-18 14:56:27,278] Trial 68 finished with value: 0.7473174609400077 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.9635380855756501, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06767743129344488, 'warm_start': True}. Best is trial 67 with value: 0.750790891168273.
Fold 1 C-index: 0.5239043824701195
Fold 2 C-index: 0.6569767441860465
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.6216730038022814
Fold 5 C-index: 0.5987124463519313
[I 2024-04-18 14:56:29,055] Trial 69 finished with value: 0.6436575706812246 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 384, 'oob_score': False, 'max_samples': 0.20333731221955026, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0976167196658406, 'warm_start': True}. Best is trial 67 with value: 0.750790891168273.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7339055793991416
[I 2024-04-18 14:56:30,702] Trial 70 finished with value: 0.7272609673349739 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 357, 'oob_score': False, 'max_samples': 0.8776823114891719, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.062443393007886774, 'warm_start': True}. Best is trial 67 with value: 0.750790891168273.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7854077253218884
[I 2024-04-18 14:56:32,820] Trial 71 finished with value: 0.7552594238966598 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 405, 'oob_score': False, 'max_samples': 0.9590314546469126, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05764515131374112, 'warm_start': True}. Best is trial 71 with value: 0.7552594238966598.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7167381974248928
[I 2024-04-18 14:56:34,615] Trial 72 finished with value: 0.7214260395134378 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.960624009976199, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1002121123511186, 'warm_start': True}. Best is trial 71 with value: 0.7552594238966598.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6866952789699571
[I 2024-04-18 14:56:36,736] Trial 73 finished with value: 0.7131461255078849 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 403, 'oob_score': False, 'max_samples': 0.7885450801854565, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06706867148431465, 'warm_start': True}. Best is trial 71 with value: 0.7552594238966598.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:56:38,656] Trial 74 finished with value: 0.6942973694328917 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.9660392944980287, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15510931843897013, 'warm_start': True}. Best is trial 71 with value: 0.7552594238966598.

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6781115879828327
[I 2024-04-18 14:56:41,014] Trial 75 finished with value: 0.7090031598523611 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 427, 'oob_score': False, 'max_samples': 0.8798704954981775, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04883920276687774, 'warm_start': True}. Best is trial 71 with value: 0.7552594238966598.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.759656652360515
[I 2024-04-18 14:56:42,454] Trial 76 finished with value: 0.7417109908985966 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 352, 'oob_score': False, 'max_samples': 0.927270030953106, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07399786977454262, 'warm_start': True}. Best is trial 71 with value: 0.7552594238966598.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6995708154506438
[I 2024-04-18 14:56:43,636] Trial 77 finished with value: 0.7189342345043981 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.9126935415750762, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07502104701718527, 'warm_start': True}. Best is trial 71 with value: 0.7552594238966598.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 14:56:44,828] Trial 78 finished with value: 0.7032004403179976 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.8150722960629895, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10589908999286238, 'warm_start': True}. Best is trial 71 with value: 0.7552594238966598.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 14:56:46,683] Trial 79 finished with value: 0.698099650801713 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 392, 'oob_score': False, 'max_samples': 0.8662930449029259, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1448453194567737, 'warm_start': True}. Best is trial 71 with value: 0.7552594238966598.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6829787234042554
Fold 4 C-index: 0.6102661596958175
Fold 5 C-index: 0.6266094420600858
[I 2024-04-18 14:56:53,038] Trial 80 finished with value: 0.6243581530891058 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 375, 'oob_score': False, 'max_samples': 0.9432929295828808, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1736526983902792, 'warm_start': False}. Best is trial 71 with value: 0.7552594238966598.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.7854077253218884
[I 2024-04-18 14:56:54,528] Trial 81 finished with value: 0.7514424050031531 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 323, 'oob_score': False, 'max_samples': 0.9728576808638062, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04463214943022961, 'warm_start': True}. Best is trial 71 with value: 0.7552594238966598.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7939914163090128
[I 2024-04-18 14:56:55,993] Trial 82 finished with value: 0.7508777743792852 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 322, 'oob_score': False, 'max_samples': 0.9221575643738086, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05131705756611819, 'warm_start': True}. Best is trial 71 with value: 0.7552594238966598.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6995708154506438
[I 2024-04-18 14:56:57,537] Trial 83 finished with value: 0.7140664747993621 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 325, 'oob_score': False, 'max_samples': 0.6153744430709406, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05518129920417096, 'warm_start': True}. Best is trial 71 with value: 0.7552594238966598.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.759656652360515
[I 2024-04-18 14:56:59,461] Trial 84 finished with value: 0.7471432542406656 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.9724080475692971, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05526637080501616, 'warm_start': True}. Best is trial 71 with value: 0.7552594238966598.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7081545064377682
[I 2024-04-18 14:57:00,924] Trial 85 finished with value: 0.7219906701373056 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.9003397868453019, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09153277339009787, 'warm_start': True}. Best is trial 71 with value: 0.7552594238966598.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7896995708154506
[I 2024-04-18 14:57:02,235] Trial 86 finished with value: 0.7568635117444511 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 311, 'oob_score': False, 'max_samples': 0.9742428617801581, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04869904172944702, 'warm_start': True}. Best is trial 86 with value: 0.7568635117444511.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7896995708154506
[I 2024-04-18 14:57:03,677] Trial 87 finished with value: 0.7562300195019496 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 329, 'oob_score': False, 'max_samples': 0.9613278894071772, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0458571199390998, 'warm_start': True}. Best is trial 86 with value: 0.7568635117444511.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7939914163090128
[I 2024-04-18 14:57:05,007] Trial 88 finished with value: 0.759326519520846 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 331, 'oob_score': False, 'max_samples': 0.9710529964061146, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04097542190019635, 'warm_start': True}. Best is trial 88 with value: 0.759326519520846.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7896995708154506
[I 2024-04-18 14:57:06,213] Trial 89 finished with value: 0.7547091069544211 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 327, 'oob_score': False, 'max_samples': 0.9732107743158388, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04646647897405329, 'warm_start': True}. Best is trial 88 with value: 0.759326519520846.

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.7939914163090128
[I 2024-04-18 14:57:07,364] Trial 90 finished with value: 0.7687890817345437 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 327, 'oob_score': False, 'max_samples': 0.9723538290337304, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04199664774884754, 'warm_start': True}. Best is trial 90 with value: 0.7687890817345437.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8025751072961373
[I 2024-04-18 14:57:08,858] Trial 91 finished with value: 0.7689996449091254 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 334, 'oob_score': False, 'max_samples': 0.9648546012474619, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.039324489061686424, 'warm_start': True}. Best is trial 91 with value: 0.7689996449091254.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8068669527896996
[I 2024-04-18 14:57:10,502] Trial 92 finished with value: 0.7652952763652523 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 331, 'oob_score': False, 'max_samples': 0.9702610402393874, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03936692814511585, 'warm_start': True}. Best is trial 91 with value: 0.7689996449091254.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8111587982832618
[I 2024-04-18 14:57:12,308] Trial 93 finished with value: 0.7659755874327769 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 327, 'oob_score': False, 'max_samples': 0.9734413836241833, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.033276650282121324, 'warm_start': True}. Best is trial 91 with value: 0.7689996449091254.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8068669527896996
[I 2024-04-18 14:57:13,998] Trial 94 finished with value: 0.7714152830306061 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.9676220641791112, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03612220578591122, 'warm_start': True}. Best is trial 94 with value: 0.7714152830306061.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8068669527896996
[I 2024-04-18 14:57:15,670] Trial 95 finished with value: 0.7704736116447959 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.897901881053174, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03675582881559987, 'warm_start': True}. Best is trial 94 with value: 0.7714152830306061.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8111587982832618
[I 2024-04-18 14:57:17,049] Trial 96 finished with value: 0.7753807414848334 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 305, 'oob_score': False, 'max_samples': 0.888855900476418, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.012473781631901167, 'warm_start': True}. Best is trial 96 with value: 0.7753807414848334.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8111587982832618
[I 2024-04-18 14:57:18,453] Trial 97 finished with value: 0.7761775542338374 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.8926185244164657, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014108821218422243, 'warm_start': True}. Best is trial 97 with value: 0.7761775542338374.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8283261802575107
[I 2024-04-18 14:57:19,868] Trial 98 finished with value: 0.7815560731711125 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.891767758010405, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01360705866922349, 'warm_start': True}. Best is trial 98 with value: 0.7815560731711125.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6463878326996197

[I 2024-04-18 14:57:25,585] A new study created in memory with name: no-name-a1881f66-f6ba-4010-90ce-b077b0945257

Fold 5 C-index: 0.6137339055793991
[I 2024-04-18 14:57:25,555] Trial 99 finished with value: 0.6373039582255651 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.8893140752738538, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.013723604983404435, 'warm_start': False}. Best is trial 98 with value: 0.7815560731711125.


* Best trial for C-index:
 FrozenTrial(number=98, state=TrialState.COMPLETE, values=[0.7815560731711125], datetime_start=datetime.datetime(2024, 4, 18, 14, 57, 18, 463894), datetime_complete=datetime.datetime(2024, 4, 18, 14, 57, 19, 868225), params={'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.891767758010405, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01360705866922349, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=98, value=None)


* Best Score for C-index:
 0.7815560731711125

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24053512749797898
Fold 2 IBS: 0.22488461898580406
Fold 3 IBS: 0.20294990912316815
Fold 4 IBS: 0.23642738808421396
Fold 5 IBS: 0.21218632285103187
[I 2024-04-18 14:57:32,157] Trial 0 finished with value: 0.22339667330843938 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.22339667330843938.
Fold 1 IBS: 0.23792140294154085
Fold 2 IBS: 0.2167388875764039
Fold 3 IBS: 0.20776843376473003
Fold 4 IBS: 0.24326670372212905
Fold 5 IBS: 0.22124673378778564
[I 2024-04-18 14:57:33,657] Trial 1 finished with value: 0.22538843235851788 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 0 with value: 0.22339667330843938.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-18 14:57:34,701] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 0 with value: 0.22339667330843938.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-18 14:57:38,200] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 0 with value: 0.22339667330843938.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-18 14:57:41,486] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 0 with value: 0.22339667330843938.
Fold 1 IBS: 0.2478415126392099
Fold 2 IBS: 0.22733499835026086
Fold 3 IBS: 0.21041093039068343
Fold 4 IBS: 0.2329023194029527
Fold 5 IBS: 0.21698208548357165
[I 2024-04-18 14:57:46,317] Trial 5 finished with value: 0.22709436925333568 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 0 with value: 0.22339667330843938.
Fold 1 IBS: 0.2439292393744578
Fold 2 IBS: 0.22266568201416273
Fold 3 IBS: 0.19970058101323257
Fold 4 IBS: 0.2369896709930087
Fold 5 IBS: 0.20946424401453986
[I 2024-04-18 14:57:51,026] Trial 6 finished with value: 0.22254988348188035 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 6 with value: 0.22254988348188035.
Fold 1 IBS: 0.2468511868826302
Fold 2 IBS: 0.23210906008494708
Fold 3 IBS: 0.22959891125842227
Fold 4 IBS: 0.24232463428497739
Fold 5 IBS: 0.23031696167514554
[I 2024-04-18 14:58:01,304] Trial 7 finished with value: 0.2362401508372245 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 6 with value: 0.22254988348188035.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-18 14:58:11,884] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 6 with value: 0.22254988348188035.
Fold 1 IBS: 0.2361275352325048
Fold 2 IBS: 0.21621939441960494
Fold 3 IBS: 0.206577685756085
Fold 4 IBS: 0.2391842767785599
Fold 5 IBS: 0.21756884230128604
[I 2024-04-18 14:58:13,845] Trial 9 finished with value: 0.22313554689760817 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 6 with value: 0.22254988348188035.
Fold 1 IBS: 0.24645571521465787
Fold 2 IBS: 0.23214351218858914
Fold 3 IBS: 0.23029990468218745
Fold 4 IBS: 0.24091247880712954
Fold 5 IBS: 0.22969387017589088
[I 2024-04-18 14:58:23,610] Trial 10 finished with value: 0.235901096213691 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3251129986182119}. Best is trial 6 with value: 0.22254988348188035.
Fold 1 IBS: 0.23523291514220976
Fold 2 IBS: 0.2161404434240995
Fold 3 IBS: 0.2060290609969013
Fold 4 IBS: 0.2392898740535063
Fold 5 IBS: 0.21695476225083588
[I 2024-04-18 14:58:26,011] Trial 11 finished with value: 0.22272941117351053 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 133, 'oob_score': False, 'max_samples': 0.9904090680670613, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17706129541113583}. Best is trial 6 with value: 0.22254988348188035.
Fold 1 IBS: 0.23663272143654904
Fold 2 IBS: 0.21704410256195597
Fold 3 IBS: 0.2066590894132215
Fold 4 IBS: 0.23709606293737745
Fold 5 IBS: 0.21531129497141535
[I 2024-04-18 14:58:28,766] Trial 12 finished with value: 0.22254865426410383 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.9971022097505926, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3199188245397474}. Best is trial 12 with value: 0.22254865426410383.
Fold 1 IBS: 0.24130058938333918
Fold 2 IBS: 0.22509855279320382
Fold 3 IBS: 0.21389153877603415
Fold 4 IBS: 0.2441204535559369
Fold 5 IBS: 0.22161453645903098
[I 2024-04-18 14:58:31,832] Trial 13 finished with value: 0.22920513419350902 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 178, 'oob_score': False, 'max_samples': 0.8358240113413322, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3571169521581675}. Best is trial 12 with value: 0.22254865426410383.
Fold 1 IBS: 0.2408658935738322
Fold 2 IBS: 0.22493166279614332
Fold 3 IBS: 0.20084125761262678
Fold 4 IBS: 0.23498011501984548
Fold 5 IBS: 0.20995723815492764
[I 2024-04-18 14:58:36,045] Trial 14 finished with value: 0.22231523343147508 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.8213409911746509, 'max_features': None, 'min_weight_fraction_leaf': 0.2748527673859612}. Best is trial 14 with value: 0.22231523343147508.
Fold 1 IBS: 0.236984312131135
Fold 2 IBS: 0.22083687662644685
Fold 3 IBS: 0.20428354962696793
Fold 4 IBS: 0.2546454813529583
Fold 5 IBS: 0.2189906242196662
[I 2024-04-18 14:58:36,523] Trial 15 finished with value: 0.22714816879143482 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 15, 'oob_score': False, 'max_samples': 0.9948421144790993, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2762403453179886}. Best is trial 14 with value: 0.22231523343147508.

Fold 1 IBS: 0.24016179150398123
Fold 2 IBS: 0.21992100103132842
Fold 3 IBS: 0.20319365008922521
Fold 4 IBS: 0.23973515566252093
Fold 5 IBS: 0.21503669660339733
[I 2024-04-18 14:58:41,794] Trial 16 finished with value: 0.22360965897809063 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.7702473623171299, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12075256052520705}. Best is trial 14 with value: 0.22231523343147508.
Fold 1 IBS: 0.25027168164193203
Fold 2 IBS: 0.23363638430106232
Fold 3 IBS: 0.21403472415826574
Fold 4 IBS: 0.22630118164926397
Fold 5 IBS: 0.2149761641609912
[I 2024-04-18 14:58:45,068] Trial 17 finished with value: 0.22784402718230307 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.9089642546533281, 'max_features': None, 'min_weight_fraction_leaf': 0.01482440801744872}. Best is trial 14 with value: 0.22231523343147508.
Fold 1 IBS: 0.23728348739902666
Fold 2 IBS: 0.22029824804782802
Fold 3 IBS: 0.20721927773632332
Fold 4 IBS: 0.24204712546171592
Fold 5 IBS: 0.2155090609670816
[I 2024-04-18 14:58:49,740] Trial 18 finished with value: 0.2244714399223951 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 17, 'n_estimators': 247, 'oob_score': True, 'max_samples': 0.7711529923280298, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2630324566026316}. Best is trial 14 with value: 0.22231523343147508.
Fold 1 IBS: 0.24310316719663957
Fold 2 IBS: 0.2225134857935221
Fold 3 IBS: 0.20477431845034183
Fold 4 IBS: 0.2409636409672938
Fold 5 IBS: 0.21341304155781848
[I 2024-04-18 14:58:55,284] Trial 19 finished with value: 0.22495353079312314 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.9119209747404678, 'max_features': None, 'min_weight_fraction_leaf': 0.40648916349098396}. Best is trial 14 with value: 0.22231523343147508.
Fold 1 IBS: 0.23792763496463584
Fold 2 IBS: 0.21860573969679273
Fold 3 IBS: 0.20734642184048904
Fold 4 IBS: 0.23945666305978316
Fold 5 IBS: 0.21501794944339547
[I 2024-04-18 14:58:59,350] Trial 20 finished with value: 0.22367088180101927 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 222, 'oob_score': False, 'max_samples': 0.9926035947056732, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22954243511476036}. Best is trial 14 with value: 0.22231523343147508.
Fold 1 IBS: 0.24224442699838503
Fold 2 IBS: 0.22286844250582932
Fold 3 IBS: 0.1991348083963014
Fold 4 IBS: 0.23821268580078098
Fold 5 IBS: 0.21167578326021913
[I 2024-04-18 14:59:03,841] Trial 21 finished with value: 0.22282722939230318 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.8202845563471131, 'max_features': None, 'min_weight_fraction_leaf': 0.34918243642298585}. Best is trial 14 with value: 0.22231523343147508.
Fold 1 IBS: 0.24197142452641582
Fold 2 IBS: 0.22499377558029768
Fold 3 IBS: 0.19853021992773434
Fold 4 IBS: 0.23532009065635007
Fold 5 IBS: 0.20827846923480015
[I 2024-04-18 14:59:10,840] Trial 22 finished with value: 0.2218187959851196 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.8568733757112759, 'max_features': None, 'min_weight_fraction_leaf': 0.3067334006568516}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.24046941820787435
Fold 2 IBS: 0.22563740659615086
Fold 3 IBS: 0.202781521168263
Fold 4 IBS: 0.23564836647035434
Fold 5 IBS: 0.2086605533351845
[I 2024-04-18 14:59:17,131] Trial 23 finished with value: 0.2226394531555654 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.9272445045117979, 'max_features': None, 'min_weight_fraction_leaf': 0.31189612373658676}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.2424663782630379
Fold 2 IBS: 0.22531461093754318
Fold 3 IBS: 0.20059783004364776
Fold 4 IBS: 0.23529666481009234
Fold 5 IBS: 0.20929309534008472
[I 2024-04-18 14:59:24,199] Trial 24 finished with value: 0.2225937158788812 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.751094422462103, 'max_features': None, 'min_weight_fraction_leaf': 0.24904577231573832}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.2465570204242158
Fold 2 IBS: 0.2321769281230286
Fold 3 IBS: 0.22951008036768533
Fold 4 IBS: 0.24146047032210644
Fold 5 IBS: 0.23032147532794853
[I 2024-04-18 14:59:29,350] Trial 25 finished with value: 0.23600519491299693 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 325, 'oob_score': False, 'max_samples': 0.6219587265298226, 'max_features': None, 'min_weight_fraction_leaf': 0.3835471958835807}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.24632631270066288
Fold 2 IBS: 0.23215802686383707
Fold 3 IBS: 0.22958036298559317
Fold 4 IBS: 0.24149011066399031
Fold 5 IBS: 0.23020718615552013
[I 2024-04-18 14:59:35,965] Trial 26 finished with value: 0.23595239987392072 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 387, 'oob_score': True, 'max_samples': 0.8412747621089902, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49009198618804073}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.246445725411069
Fold 2 IBS: 0.23225357506862682
Fold 3 IBS: 0.22966060272282596
Fold 4 IBS: 0.24135490310053823
Fold 5 IBS: 0.23014902720613523
[I 2024-04-18 14:59:41,091] Trial 27 finished with value: 0.23597276670183903 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.33755264727046935, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2961621963547894}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.24842115459575145
Fold 2 IBS: 0.23598695153466634
Fold 3 IBS: 0.23584906609596643
Fold 4 IBS: 0.25276552098985827
Fold 5 IBS: 0.23024164093930558
[I 2024-04-18 14:59:49,355] Trial 28 finished with value: 0.2406528668311096 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 497, 'oob_score': False, 'max_samples': 0.9191635715416451, 'max_features': None, 'min_weight_fraction_leaf': 0.4562458300512269}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.2422339995714561
Fold 2 IBS: 0.2248379949845398
Fold 3 IBS: 0.2028374793312637
Fold 4 IBS: 0.23619705355549916
Fold 5 IBS: 0.2101369103649299
[I 2024-04-18 14:59:53,812] Trial 29 finished with value: 0.22324868756153773 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 248, 'oob_score': False, 'max_samples': 0.7298184401810461, 'max_features': None, 'min_weight_fraction_leaf': 0.2379583104440125}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.23887265278765343
Fold 2 IBS: 0.22295210359060055
Fold 3 IBS: 0.21095676415818004
Fold 4 IBS: 0.24326798107106512
Fold 5 IBS: 0.21690234924506466
[I 2024-04-18 14:59:56,191] Trial 30 finished with value: 0.22659037017051276 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 160, 'oob_score': False, 'max_samples': 0.8117352232698498, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.32890627681753376}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.2434368464971525
Fold 2 IBS: 0.2225279298672003
Fold 3 IBS: 0.2004408771894173
Fold 4 IBS: 0.23768058491211716
Fold 5 IBS: 0.21159214932363807
[I 2024-04-18 15:00:00,154] Trial 31 finished with value: 0.22313567755790506 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 267, 'oob_score': False, 'max_samples': 0.8578464634949954, 'max_features': None, 'min_weight_fraction_leaf': 0.3688578317628544}. Best is trial 22 with value: 0.2218187959851196.

Fold 1 IBS: 0.2487809856154952
Fold 2 IBS: 0.2357126863122274
Fold 3 IBS: 0.23121879278633423
Fold 4 IBS: 0.252716871302657
Fold 5 IBS: 0.2300529842210826
[I 2024-04-18 15:00:04,595] Trial 32 finished with value: 0.23969646404755926 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 324, 'oob_score': False, 'max_samples': 0.684967894963397, 'max_features': None, 'min_weight_fraction_leaf': 0.33358217229374115}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.24085297329416872
Fold 2 IBS: 0.2345733046583843
Fold 3 IBS: 0.20759135963865943
Fold 4 IBS: 0.2365296995834454
Fold 5 IBS: 0.21299797485712868
[I 2024-04-18 15:00:10,611] Trial 33 finished with value: 0.22650906240635732 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 377, 'oob_score': False, 'max_samples': 0.86361376148645, 'max_features': None, 'min_weight_fraction_leaf': 0.2057199473422257}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.24556124759298648
Fold 2 IBS: 0.22210150964453557
Fold 3 IBS: 0.19691302865866053
Fold 4 IBS: 0.23930898930309796
Fold 5 IBS: 0.20856593680929064
[I 2024-04-18 15:00:12,676] Trial 34 finished with value: 0.22249014240171422 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 102, 'oob_score': False, 'max_samples': 0.9428576627469121, 'max_features': None, 'min_weight_fraction_leaf': 0.382395591818078}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.2395180159455458
Fold 2 IBS: 0.22381213434338212
Fold 3 IBS: 0.21189801290375046
Fold 4 IBS: 0.24346602846005183
Fold 5 IBS: 0.21805664894842655
[I 2024-04-18 15:00:14,523] Trial 35 finished with value: 0.22735016812023137 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 101, 'oob_score': True, 'max_samples': 0.9536728448516014, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3909359479764509}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.24605321793772314
Fold 2 IBS: 0.2320407780008997
Fold 3 IBS: 0.23012263014557482
Fold 4 IBS: 0.24145463919859217
Fold 5 IBS: 0.23004510526117777
[I 2024-04-18 15:00:15,305] Trial 36 finished with value: 0.23594327410879354 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 37, 'oob_score': False, 'max_samples': 0.5954498484101246, 'max_features': None, 'min_weight_fraction_leaf': 0.43719302942751936}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.24682586552552557
Fold 2 IBS: 0.23221376186586307
Fold 3 IBS: 0.22953767781645004
Fold 4 IBS: 0.2417611911040666
Fold 5 IBS: 0.23050648886742492
[I 2024-04-18 15:00:16,435] Trial 37 finished with value: 0.23616899703586602 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 57, 'oob_score': False, 'max_samples': 0.4792233788080467, 'max_features': None, 'min_weight_fraction_leaf': 0.3061039000862159}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.23747108050854404
Fold 2 IBS: 0.21457079937800544
Fold 3 IBS: 0.20631704791176148
Fold 4 IBS: 0.24272378808962958
Fold 5 IBS: 0.21727613263787443
[I 2024-04-18 15:00:17,621] Trial 38 finished with value: 0.22367176970516298 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 68, 'oob_score': False, 'max_samples': 0.9484457479991459, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26441342815682645}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.24300456383051364
Fold 2 IBS: 0.23225451179550374
Fold 3 IBS: 0.20799724977096867
Fold 4 IBS: 0.24165115142855859
Fold 5 IBS: 0.2148116788605213
[I 2024-04-18 15:00:20,329] Trial 39 finished with value: 0.2279438311372132 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 130, 'oob_score': True, 'max_samples': 0.6950804728385664, 'max_features': None, 'min_weight_fraction_leaf': 0.1398868795380276}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.24665904258904486
Fold 2 IBS: 0.23211099255304748
Fold 3 IBS: 0.22949309902967777
Fold 4 IBS: 0.24159099070214046
Fold 5 IBS: 0.23015685201935077
[I 2024-04-18 15:00:22,974] Trial 40 finished with value: 0.23600219537865225 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 205, 'oob_score': False, 'max_samples': 0.8039498104348345, 'max_features': None, 'min_weight_fraction_leaf': 0.43331565203772726}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.24199835726108834
Fold 2 IBS: 0.22322003089273013
Fold 3 IBS: 0.19945906735257313
Fold 4 IBS: 0.23675092771411643
Fold 5 IBS: 0.20948643408417658
[I 2024-04-18 15:00:26,129] Trial 41 finished with value: 0.2221829634609369 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 234, 'oob_score': False, 'max_samples': 0.8780572120262797, 'max_features': None, 'min_weight_fraction_leaf': 0.35821631216866767}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.24236494493251293
Fold 2 IBS: 0.2223759856043181
Fold 3 IBS: 0.20089985320501533
Fold 4 IBS: 0.2404030921400019
Fold 5 IBS: 0.21374618414789484
[I 2024-04-18 15:00:28,858] Trial 42 finished with value: 0.22395801200594861 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 191, 'oob_score': False, 'max_samples': 0.8715700658240412, 'max_features': None, 'min_weight_fraction_leaf': 0.3842914936018125}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.2426743563595264
Fold 2 IBS: 0.22496120281973608
Fold 3 IBS: 0.2015563347556901
Fold 4 IBS: 0.23526071666449372
Fold 5 IBS: 0.209069854564278
[I 2024-04-18 15:00:31,290] Trial 43 finished with value: 0.22270449303274487 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 143, 'oob_score': False, 'max_samples': 0.9567621055031488, 'max_features': None, 'min_weight_fraction_leaf': 0.3411572569773044}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.2371499490015321
Fold 2 IBS: 0.21863784976927145
Fold 3 IBS: 0.20790131315000557
Fold 4 IBS: 0.23777381191027766
Fold 5 IBS: 0.21471925897488758
[I 2024-04-18 15:00:34,422] Trial 44 finished with value: 0.22323643656119488 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 225, 'oob_score': False, 'max_samples': 0.8785997921903561, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2908961407044965}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.24719101157146442
Fold 2 IBS: 0.23209089309816136
Fold 3 IBS: 0.22948516992681076
Fold 4 IBS: 0.24093127738988068
Fold 5 IBS: 0.22951135916610954
[I 2024-04-18 15:00:36,135] Trial 45 finished with value: 0.23584194223048532 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 106, 'oob_score': False, 'max_samples': 0.10184332440552968, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3660425481482526}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.2464026341218028
Fold 2 IBS: 0.2320519505979722
Fold 3 IBS: 0.23003100312221977
Fold 4 IBS: 0.2411710262436864
Fold 5 IBS: 0.2295173824666538
[I 2024-04-18 15:00:37,913] Trial 46 finished with value: 0.23583479931046697 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.1873692143114088, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3223680169060047}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.24657606154512296
Fold 2 IBS: 0.23208028090448593
Fold 3 IBS: 0.2293728334402157
Fold 4 IBS: 0.2416544777489607
Fold 5 IBS: 0.23018413338659835
[I 2024-04-18 15:00:41,242] Trial 47 finished with value: 0.2359735574050767 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 162, 'oob_score': True, 'max_samples': 0.7933948011657994, 'max_features': None, 'min_weight_fraction_leaf': 0.40964100148661425}. Best is trial 22 with value: 0.2218187959851196.

Fold 1 IBS: 0.2345170711209011
Fold 2 IBS: 0.2158702876822272
Fold 3 IBS: 0.20549905429174378
Fold 4 IBS: 0.2402979166180355
Fold 5 IBS: 0.21392455626227205
[I 2024-04-18 15:00:49,143] Trial 48 finished with value: 0.2220217771950359 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 458, 'oob_score': False, 'max_samples': 0.9997930418100197, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.30064196242213814}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.24074271168077346
Fold 2 IBS: 0.22548053199748758
Fold 3 IBS: 0.2011822511428179
Fold 4 IBS: 0.23722082886916646
Fold 5 IBS: 0.21068234076308953
[I 2024-04-18 15:00:58,497] Trial 49 finished with value: 0.223061732890667 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 463, 'oob_score': False, 'max_samples': 0.651099051191656, 'max_features': None, 'min_weight_fraction_leaf': 0.20843388984638817}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.23891035545990014
Fold 2 IBS: 0.22824565488362372
Fold 3 IBS: 0.20741123384593138
Fold 4 IBS: 0.23594309007537445
Fold 5 IBS: 0.21124927820327508
[I 2024-04-18 15:01:13,252] Trial 50 finished with value: 0.22435192249362096 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 416, 'oob_score': False, 'max_samples': 0.896668542755986, 'max_features': None, 'min_weight_fraction_leaf': 0.2559558919229117}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.23475907539609286
Fold 2 IBS: 0.21558345384717276
Fold 3 IBS: 0.20530351557966267
Fold 4 IBS: 0.23983844060371262
Fold 5 IBS: 0.21469607263382368
[I 2024-04-18 15:01:26,488] Trial 51 finished with value: 0.22203611161209294 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.9684517077652335, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2818788547375587}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.23466480615320964
Fold 2 IBS: 0.21641605524378651
Fold 3 IBS: 0.2054520118950419
Fold 4 IBS: 0.23966466180049162
Fold 5 IBS: 0.2149297740307806
[I 2024-04-18 15:01:34,075] Trial 52 finished with value: 0.22222546182466205 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 468, 'oob_score': False, 'max_samples': 0.9586705181085473, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.29225270566742245}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.23405143324464364
Fold 2 IBS: 0.21583975604218558
Fold 3 IBS: 0.2052636558445444
Fold 4 IBS: 0.2394659239398278
Fold 5 IBS: 0.21476768602413637
[I 2024-04-18 15:01:41,709] Trial 53 finished with value: 0.22187769101906757 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 471, 'oob_score': False, 'max_samples': 0.9727025782861619, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.26886912257525214}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.23956491614417613
Fold 2 IBS: 0.21898277246746542
Fold 3 IBS: 0.2067506320863929
Fold 4 IBS: 0.23609748741458073
Fold 5 IBS: 0.2149507937560782
[I 2024-04-18 15:01:48,819] Trial 54 finished with value: 0.22326932037373867 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 479, 'oob_score': False, 'max_samples': 0.9720907739213143, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18369342906341113}. Best is trial 22 with value: 0.2218187959851196.
Fold 1 IBS: 0.23376115387806876
Fold 2 IBS: 0.21563142787342368
Fold 3 IBS: 0.20516484057572074
Fold 4 IBS: 0.23920675395055077
Fold 5 IBS: 0.21442580624471944
[I 2024-04-18 15:01:56,585] Trial 55 finished with value: 0.2216379965044967 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 463, 'oob_score': False, 'max_samples': 0.996217853311879, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27511172283654456}. Best is trial 55 with value: 0.2216379965044967.
Fold 1 IBS: 0.23498729331197404
Fold 2 IBS: 0.21739541882062957
Fold 3 IBS: 0.20664293247705548
Fold 4 IBS: 0.2398263626327344
Fold 5 IBS: 0.2146447562806913
[I 2024-04-18 15:02:02,662] Trial 56 finished with value: 0.22269935270461697 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.8970335110545464, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2793046007704463}. Best is trial 55 with value: 0.2216379965044967.
Fold 1 IBS: 0.23488857910751124
Fold 2 IBS: 0.2156329606859184
Fold 3 IBS: 0.2054236731374856
Fold 4 IBS: 0.2388541276841528
Fold 5 IBS: 0.2150814981247835
[I 2024-04-18 15:02:09,597] Trial 57 finished with value: 0.2219761677479703 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 19, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.9933085604514419, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23177764488631825}. Best is trial 55 with value: 0.2216379965044967.
Fold 1 IBS: 0.23493683998791057
Fold 2 IBS: 0.21593693652478502
Fold 3 IBS: 0.20530797208434462
Fold 4 IBS: 0.23902373480067063
Fold 5 IBS: 0.21459832713977517
[I 2024-04-18 15:02:17,142] Trial 58 finished with value: 0.22196076210749718 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 18, 'n_estimators': 411, 'oob_score': True, 'max_samples': 0.9962613241969719, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22403196913816004}. Best is trial 55 with value: 0.2216379965044967.
Fold 1 IBS: 0.23398213116732144
Fold 2 IBS: 0.21610023000499917
Fold 3 IBS: 0.20550459505876006
Fold 4 IBS: 0.23911488900345404
Fold 5 IBS: 0.2149498235084049
[I 2024-04-18 15:02:24,879] Trial 59 finished with value: 0.22193033374858792 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 18, 'n_estimators': 413, 'oob_score': True, 'max_samples': 0.9972846273620176, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22717020328937385}. Best is trial 55 with value: 0.2216379965044967.
Fold 1 IBS: 0.234054366694232
Fold 2 IBS: 0.2158044639877302
Fold 3 IBS: 0.2061233708542743
Fold 4 IBS: 0.23790835101575533
Fold 5 IBS: 0.2142607898219461
[I 2024-04-18 15:02:32,665] Trial 60 finished with value: 0.2216302684747876 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 18, 'n_estimators': 414, 'oob_score': True, 'max_samples': 0.934414367119912, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16285508057877365}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.23518292504983324
Fold 2 IBS: 0.21634510368614754
Fold 3 IBS: 0.20531534877558255
Fold 4 IBS: 0.23944794246510942
Fold 5 IBS: 0.21437333142514575
[I 2024-04-18 15:02:42,389] Trial 61 finished with value: 0.22213293028036368 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 18, 'n_estimators': 416, 'oob_score': True, 'max_samples': 0.9996646211339355, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16252992675440345}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.23462863436678708
Fold 2 IBS: 0.21565004264789076
Fold 3 IBS: 0.20615183461684988
Fold 4 IBS: 0.23878237976404856
Fold 5 IBS: 0.21440638236305762
[I 2024-04-18 15:02:49,633] Trial 62 finished with value: 0.22192385475172677 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 17, 'n_estimators': 372, 'oob_score': True, 'max_samples': 0.9278793495730275, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2253524449156451}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.2345049121753946
Fold 2 IBS: 0.21533933481857412
Fold 3 IBS: 0.206122425225538
Fold 4 IBS: 0.2387973126710511

Fold 5 IBS: 0.21467305705178563
[I 2024-04-18 15:02:57,647] Trial 63 finished with value: 0.2218874083884687 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 17, 'n_estimators': 397, 'oob_score': True, 'max_samples': 0.9302168042817908, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12589404086133016}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.23467329485216584
Fold 2 IBS: 0.2153250575930954
Fold 3 IBS: 0.20619628812969265
Fold 4 IBS: 0.23854415937650256
Fold 5 IBS: 0.21459253618191182
[I 2024-04-18 15:03:05,891] Trial 64 finished with value: 0.22186626722667366 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 17, 'n_estimators': 383, 'oob_score': True, 'max_samples': 0.9257891646726054, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09737330304950191}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.23465626444537765
Fold 2 IBS: 0.21586312043665584
Fold 3 IBS: 0.20641301153864616
Fold 4 IBS: 0.23914358299896268
Fold 5 IBS: 0.21460414704240885
[I 2024-04-18 15:03:13,424] Trial 65 finished with value: 0.22213602529241022 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 17, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.9284385922090833, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.082386588212711}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.23509975512278034
Fold 2 IBS: 0.2168614913909376
Fold 3 IBS: 0.20593883666211285
Fold 4 IBS: 0.24116945654132485
Fold 5 IBS: 0.21439917356362434
[I 2024-04-18 15:03:20,611] Trial 66 finished with value: 0.222693742656156 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 17, 'n_estimators': 350, 'oob_score': True, 'max_samples': 0.8400105454771931, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10622244000520055}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.23574774820214064
Fold 2 IBS: 0.21588938369184785
Fold 3 IBS: 0.2057599181597379
Fold 4 IBS: 0.23887574965000072
Fold 5 IBS: 0.21384282847621786
[I 2024-04-18 15:03:28,955] Trial 67 finished with value: 0.22202312563598897 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16, 'n_estimators': 393, 'oob_score': True, 'max_samples': 0.9210602836826983, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11450213418809524}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.23486224650551918
Fold 2 IBS: 0.21636083007459092
Fold 3 IBS: 0.20548576075005523
Fold 4 IBS: 0.23876961838455282
Fold 5 IBS: 0.21452250410281598
[I 2024-04-18 15:03:36,795] Trial 68 finished with value: 0.2220001919635068 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 20, 'n_estimators': 366, 'oob_score': True, 'max_samples': 0.8954086288264819, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13510714730422876}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.23645540992469685
Fold 2 IBS: 0.21692488243484442
Fold 3 IBS: 0.20453976978864574
Fold 4 IBS: 0.24022037498334464
Fold 5 IBS: 0.21525448008185202
[I 2024-04-18 15:03:43,719] Trial 69 finished with value: 0.22267898344267673 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 16, 'n_estimators': 337, 'oob_score': True, 'max_samples': 0.7779959229418714, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01443951359826845}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.23393456022795234
Fold 2 IBS: 0.21611922851497534
Fold 3 IBS: 0.20610856189793714
Fold 4 IBS: 0.23964491369952737
Fold 5 IBS: 0.21503414407432378
[I 2024-04-18 15:03:53,223] Trial 70 finished with value: 0.2221682816829432 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 17, 'n_estimators': 440, 'oob_score': True, 'max_samples': 0.9296404110287737, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03500576464569131}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.2342537695134965
Fold 2 IBS: 0.21605085600294124
Fold 3 IBS: 0.20597692185924485
Fold 4 IBS: 0.23799666695455238
Fold 5 IBS: 0.2146117546726179
[I 2024-04-18 15:04:01,377] Trial 71 finished with value: 0.22177799380057056 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 18, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.9620608625377209, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1606318107568227}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.2359751140646931
Fold 2 IBS: 0.21594072119819233
Fold 3 IBS: 0.20531221756226858
Fold 4 IBS: 0.23891745800848743
Fold 5 IBS: 0.2137811640925225
[I 2024-04-18 15:04:08,876] Trial 72 finished with value: 0.22198533498523276 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 398, 'oob_score': True, 'max_samples': 0.9628633561276311, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16099267866073308}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.23428227672815824
Fold 2 IBS: 0.21644922966225424
Fold 3 IBS: 0.2056767013034852
Fold 4 IBS: 0.2412856789217201
Fold 5 IBS: 0.21545116212569143
[I 2024-04-18 15:04:16,919] Trial 73 finished with value: 0.22262900974826186 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 17, 'n_estimators': 430, 'oob_score': True, 'max_samples': 0.8388810011761724, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07535123813961561}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.23539519292800273
Fold 2 IBS: 0.2165738507051562
Fold 3 IBS: 0.20654168785091848
Fold 4 IBS: 0.23864573085258464
Fold 5 IBS: 0.2143259671833914
[I 2024-04-18 15:04:22,781] Trial 74 finished with value: 0.22229648590401072 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 365, 'oob_score': True, 'max_samples': 0.8993869438488488, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1892941360644107}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.23427006830066133
Fold 2 IBS: 0.21575304096391373
Fold 3 IBS: 0.20527188489922127
Fold 4 IBS: 0.23834214284939004
Fold 5 IBS: 0.21458617710361613
[I 2024-04-18 15:04:30,874] Trial 75 finished with value: 0.2216446628233605 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 15, 'n_estimators': 452, 'oob_score': True, 'max_samples': 0.9347556162825816, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16622052993502082}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.2382912912253869
Fold 2 IBS: 0.21704280989491795
Fold 3 IBS: 0.20592943641899433
Fold 4 IBS: 0.23771698049778248
Fold 5 IBS: 0.2140350496685374
[I 2024-04-18 15:04:37,751] Trial 76 finished with value: 0.2226031135411238 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 15, 'n_estimators': 447, 'oob_score': True, 'max_samples': 0.9657274301391846, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0996176016883207}. Best is trial 60 with value: 0.2216302684747876.
Fold 1 IBS: 0.23499863523085068
Fold 2 IBS: 0.2130643213437488
Fold 3 IBS: 0.2046044826616254
Fold 4 IBS: 0.2393584343164469
Fold 5 IBS: 0.21471444698019088
[I 2024-04-18 15:04:48,820] Trial 77 finished with value: 0.2213480641065725 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 483, 'oob_score': True, 'max_samples': 0.9412925565225843, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1648569090893628}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.23475788572600081
Fold 2 IBS: 0.21531688668483412
Fold 3 IBS: 0.2052461184486799
Fold 4 IBS: 0.2407298507357472
Fold 5 IBS: 0.21506923730978791
[I 2024-04-18 15:05:10,420] Trial 78 finished with value: 0.22222399578101001 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 483, 'oob_score': True, 'max_samples': 0.8665936119194544, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16305480824993773}. Best is trial 77 with value: 0.2213480641065725.

Fold 1 IBS: 0.23840329527158535
Fold 2 IBS: 0.2240443733688464
Fold 3 IBS: 0.20985902553972755
Fold 4 IBS: 0.2414779454433706
Fold 5 IBS: 0.21993148705339322
[I 2024-04-18 15:05:19,646] Trial 79 finished with value: 0.22674322533538463 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.5136803098501763, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.044239866414212486}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.24167305181103554
Fold 2 IBS: 0.22408144386753678
Fold 3 IBS: 0.21862357706308283
Fold 4 IBS: 0.24304802780796642
Fold 5 IBS: 0.22308603875882582
[I 2024-04-18 15:05:27,856] Trial 80 finished with value: 0.2301024278616895 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 464, 'oob_score': True, 'max_samples': 0.37703659520841803, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14989649788396264}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.23576230414193008
Fold 2 IBS: 0.21546341092548824
Fold 3 IBS: 0.2052103233148488
Fold 4 IBS: 0.23886068393063603
Fold 5 IBS: 0.21352206814397084
[I 2024-04-18 15:05:34,523] Trial 81 finished with value: 0.2217637580913748 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 16, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.9442262398667775, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13508175836204445}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.23444324232055255
Fold 2 IBS: 0.21589711696469563
Fold 3 IBS: 0.20516915844749276
Fold 4 IBS: 0.23795146039161974
Fold 5 IBS: 0.21474885701754737
[I 2024-04-18 15:05:43,440] Trial 82 finished with value: 0.22164196702838163 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 14, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.9443114706299608, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09388371332845069}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.2345641663033495
Fold 2 IBS: 0.21589138232098248
Fold 3 IBS: 0.20530029027165297
Fold 4 IBS: 0.23780897421991395
Fold 5 IBS: 0.21467858748701402
[I 2024-04-18 15:05:50,960] Trial 83 finished with value: 0.2216486801205826 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 14, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.9438969478425715, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09647734026732344}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.2367401103430092
Fold 2 IBS: 0.21612272988285877
Fold 3 IBS: 0.20550712706892174
Fold 4 IBS: 0.23735564764420264
Fold 5 IBS: 0.2140836909389147
[I 2024-04-18 15:05:58,245] Trial 84 finished with value: 0.22196186117558142 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 14, 'n_estimators': 427, 'oob_score': True, 'max_samples': 0.9450624819042851, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1725640511401297}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.23494139779834347
Fold 2 IBS: 0.2159544895786822
Fold 3 IBS: 0.2045343532804873
Fold 4 IBS: 0.23948700732141828
Fold 5 IBS: 0.21473870328340827
[I 2024-04-18 15:06:07,180] Trial 85 finished with value: 0.22193119025246794 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 14, 'n_estimators': 457, 'oob_score': True, 'max_samples': 0.8878732569776979, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05643480717155791}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.2358074835918786
Fold 2 IBS: 0.21654052445233637
Fold 3 IBS: 0.2060213065968261
Fold 4 IBS: 0.23866771966689374
Fold 5 IBS: 0.21409925031669072
[I 2024-04-18 15:06:15,317] Trial 86 finished with value: 0.22222725692492512 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 15, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.9785320420243417, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14440609540853447}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.2381702921629681
Fold 2 IBS: 0.2173298218288217
Fold 3 IBS: 0.20568796615658394
Fold 4 IBS: 0.2393682090818654
Fold 5 IBS: 0.21468271902891253
[I 2024-04-18 15:06:22,553] Trial 87 finished with value: 0.22304780165183033 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 15, 'n_estimators': 446, 'oob_score': True, 'max_samples': 0.8521147887726246, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12931542176104396}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.2346629192732894
Fold 2 IBS: 0.21559877674732622
Fold 3 IBS: 0.20563463886396913
Fold 4 IBS: 0.23970324043239669
Fold 5 IBS: 0.21499703878771873
[I 2024-04-18 15:06:30,716] Trial 88 finished with value: 0.22211932282094002 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 16, 'n_estimators': 486, 'oob_score': True, 'max_samples': 0.9067281124861233, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2109952066508757}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.2341081655901169
Fold 2 IBS: 0.21573057598942072
Fold 3 IBS: 0.20594585963440168
Fold 4 IBS: 0.23835433237626852
Fold 5 IBS: 0.21469307528268206
[I 2024-04-18 15:06:36,902] Trial 89 finished with value: 0.22176640177457801 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 14, 'n_estimators': 406, 'oob_score': True, 'max_samples': 0.9461593939183752, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08734205277091801}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.23403130678559408
Fold 2 IBS: 0.21556644348461523
Fold 3 IBS: 0.20632956415041231
Fold 4 IBS: 0.23849011183803664
Fold 5 IBS: 0.21516052155815857
[I 2024-04-18 15:06:44,033] Trial 90 finished with value: 0.22191558956336338 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 426, 'oob_score': True, 'max_samples': 0.9466598294780547, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08242685561079405}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.23541206001625792
Fold 2 IBS: 0.21580899463646333
Fold 3 IBS: 0.20500579867496665
Fold 4 IBS: 0.23878663832926353
Fold 5 IBS: 0.21334088260671588
[I 2024-04-18 15:06:50,772] Trial 91 finished with value: 0.22167087485273346 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 14, 'n_estimators': 405, 'oob_score': True, 'max_samples': 0.9469932206828737, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11274686922590788}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.23540367387706523
Fold 2 IBS: 0.21534493021753942
Fold 3 IBS: 0.2048337856189113
Fold 4 IBS: 0.23923992096753088
Fold 5 IBS: 0.21413971639344584
[I 2024-04-18 15:06:58,590] Trial 92 finished with value: 0.22179240541489853 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14, 'n_estimators': 473, 'oob_score': True, 'max_samples': 0.9418246085016683, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09282392899403072}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.23477499815799616
Fold 2 IBS: 0.21597977457639267
Fold 3 IBS: 0.20584332069946926
Fold 4 IBS: 0.23833408549384621
Fold 5 IBS: 0.21483531709907397
[I 2024-04-18 15:07:05,552] Trial 93 finished with value: 0.22195349920535565 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 13, 'n_estimators': 437, 'oob_score': True, 'max_samples': 0.9758918155690618, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11240383039620322}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.24652814517026636
Fold 2 IBS: 0.23215562654264682
Fold 3 IBS: 0.22996899581175542
Fold 4 IBS: 0.2411486792805121

Fold 5 IBS: 0.23029690187765103
[I 2024-04-18 15:07:10,743] Trial 94 finished with value: 0.23601966973656635 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 14, 'n_estimators': 307, 'oob_score': True, 'max_samples': 0.22295672704529856, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06861072299069754}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.23464163108868474
Fold 2 IBS: 0.21657918908416698
Fold 3 IBS: 0.20594088914082598
Fold 4 IBS: 0.23877196303776577
Fold 5 IBS: 0.21486092621836406
[I 2024-04-18 15:07:17,700] Trial 95 finished with value: 0.2221589197139615 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 408, 'oob_score': True, 'max_samples': 0.9110191728407264, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1963462784654459}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.2351995544244154
Fold 2 IBS: 0.21563550424237765
Fold 3 IBS: 0.20501924347544556
Fold 4 IBS: 0.24049638627344125
Fold 5 IBS: 0.21485284478967925
[I 2024-04-18 15:07:25,435] Trial 96 finished with value: 0.22224070664107182 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 491, 'oob_score': True, 'max_samples': 0.8799556395147554, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1510518245780164}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.23525329617570856
Fold 2 IBS: 0.21552253781391803
Fold 3 IBS: 0.20515926767910508
Fold 4 IBS: 0.23855622895090306
Fold 5 IBS: 0.21378179610160175
[I 2024-04-18 15:07:33,079] Trial 97 finished with value: 0.2216546253442473 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.9452269865332174, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1201270975782226}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.2347161400673742
Fold 2 IBS: 0.21643827574729918
Fold 3 IBS: 0.20563437948769803
Fold 4 IBS: 0.23939112322136652
Fold 5 IBS: 0.21416595675274902
[I 2024-04-18 15:07:43,522] Trial 98 finished with value: 0.22206917505529739 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.910501504746955, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12013431725596155}. Best is trial 77 with value: 0.2213480641065725.
Fold 1 IBS: 0.23974067513170733
Fold 2 IBS: 0.2173968113317976
Fold 3 IBS: 0.20656348484276973
Fold 4 IBS: 0.23812424319878936
Fold 5 IBS: 0.21472891497383265
[I 2024-04-18 15:08:04,679] Trial 99 finished with value: 0.22331082589577936 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 473, 'oob_score': True, 'max_samples': 0.9796201781590204, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05305541913345835}. Best is trial 77 with value: 0.2213480641065725.


* Best trial for IBS:
 FrozenTrial(number=77, state=TrialState.COMPLETE, values=[0.2213480641065725], datetime_start=datetime.datetime(2024, 4, 18, 15, 4, 37, 756833), datetime_complete=datetime.datetime(2024, 4, 18, 15, 4, 48, 819467), params={'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 483, 'oob_score': True, 'max_samples': 0.9412925565225843, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1648569090893628}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=77, value=None)


* Best Score for IBS:
 0.2213480641065725

In [48]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [49]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.782
train_ibs:  0.221

#### Test

In [50]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [51]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=20, max_leaf_nodes=8,
                     max_samples=0.891767758010405, min_samples_leaf=1,
                     min_samples_split=5,
                     min_weight_fraction_leaf=0.01360705866922349,
                     n_estimators=306, random_state=123, warm_start=True)

test_cindex:  0.622

RandomSurvivalForest(max_depth=1, max_leaf_nodes=20,
                     max_samples=0.9412925565225843, min_samples_leaf=18,
                     min_samples_split=14,
                     min_weight_fraction_leaf=0.1648569090893628,
                     n_estimators=483, oob_score=True, random_state=123)

test_ibs:  0.214

In [52]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [53]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 15:08:07,579] A new study created in memory with name: no-name-f2350a36-c2db-4dd1-9ac2-816c844605ae

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.592274678111588
[I 2024-04-18 15:08:08,939] Trial 0 finished with value: 0.6732087706012029 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.6732087706012029.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:08:11,781] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.6732087706012029.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.5965665236051502
[I 2024-04-18 15:08:17,487] Trial 2 finished with value: 0.6469379708565062 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.6732087706012029.
Fold 1 C-index: 0.6075697211155379
Fold 2 C-index: 0.6492248062015504
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.5450643776824035
[I 2024-04-18 15:08:18,018] Trial 3 finished with value: 0.6486526644235695 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.6732087706012029.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:08:20,510] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.6732087706012029.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:08:22,929] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.6732087706012029.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.592274678111588
[I 2024-04-18 15:08:24,433] Trial 6 finished with value: 0.6679607827592847 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.6732087706012029.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.5965665236051502
[I 2024-04-18 15:08:27,849] Trial 7 finished with value: 0.6452989448877334 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.6732087706012029.
Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.6763565891472868
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.5429184549356223
[I 2024-04-18 15:08:28,060] Trial 8 finished with value: 0.6552971457779992 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.6732087706012029.
Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.6829787234042554
Fold 4 C-index: 0.6863117870722434
Fold 5 C-index: 0.5686695278969958
[I 2024-04-18 15:08:34,605] Trial 9 finished with value: 0.6264613365607052 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.6732087706012029.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:08:37,197] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.6732087706012029.
Fold 1 C-index: 0.6075697211155379
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.5901287553648069
[I 2024-04-18 15:08:38,867] Trial 11 finished with value: 0.656275139168363 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.6732087706012029.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6437768240343348
[I 2024-04-18 15:08:40,803] Trial 12 finished with value: 0.6812566420569242 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.6812566420569242.
Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.6569767441860465
Fold 3 C-index: 0.7510638297872341
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.5836909871244635
[I 2024-04-18 15:08:42,467] Trial 13 finished with value: 0.6550760472717355 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.6812566420569242.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6569767441860465
Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.5879828326180258
[I 2024-04-18 15:08:43,520] Trial 14 finished with value: 0.6587954066782887 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.6812566420569242.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6569767441860465
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.5815450643776824
[I 2024-04-18 15:08:44,394] Trial 15 finished with value: 0.6599525423580153 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.6812566420569242.

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6298449612403101
Fold 3 C-index: 0.7553191489361702
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 15:08:45,997] Trial 16 finished with value: 0.6456767664684027 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.6812566420569242.
Fold 1 C-index: 0.5756972111553785
Fold 2 C-index: 0.6492248062015504
Fold 3 C-index: 0.7680851063829788
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.628755364806867
[I 2024-04-18 15:08:47,286] Trial 17 finished with value: 0.6665578209032713 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.6812566420569242.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:08:48,934] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.6812566420569242.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.575107296137339
[I 2024-04-18 15:08:50,104] Trial 19 finished with value: 0.6605921637307934 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.6812566420569242.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5562015503875969
Fold 3 C-index: 0.6957446808510638
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6523605150214592
[I 2024-04-18 15:08:50,460] Trial 20 finished with value: 0.6466635397296572 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.6812566420569242.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.592274678111588
[I 2024-04-18 15:08:51,954] Trial 21 finished with value: 0.6681024843152328 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.6812566420569242.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6437768240343348
[I 2024-04-18 15:08:53,615] Trial 22 finished with value: 0.6775154931947552 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.6812566420569242.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6695278969957081
[I 2024-04-18 15:08:55,465] Trial 23 finished with value: 0.6975178627058407 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.5965665236051502
[I 2024-04-18 15:08:57,092] Trial 24 finished with value: 0.671011455060367 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6266094420600858
[I 2024-04-18 15:08:58,422] Trial 25 finished with value: 0.6857838444620926 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.5815450643776824
[I 2024-04-18 15:09:06,031] Trial 26 finished with value: 0.6466855736086958 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 497, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7226268366017338, 'min_weight_fraction_leaf': 0.14724522382749441}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6763565891472868
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6115879828326181
[I 2024-04-18 15:09:07,526] Trial 27 finished with value: 0.6625488014072757 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.0910755188453143}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6647286821705426
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.555793991416309
[I 2024-04-18 15:09:09,204] Trial 28 finished with value: 0.6502141501348364 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 465, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9159590537617217, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 15:09:11,028] Trial 29 finished with value: 0.6725350705516159 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 352, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8201511224658254, 'min_weight_fraction_leaf': 0.10380226349432521}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6437768240343348
[I 2024-04-18 15:09:11,934] Trial 30 finished with value: 0.6920315358579866 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 278, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.05879574792157449}. Best is trial 23 with value: 0.6975178627058407.

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6866952789699571
[I 2024-04-18 15:09:12,923] Trial 31 finished with value: 0.6917088415982304 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 281, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6298966865274057, 'min_weight_fraction_leaf': 0.05405927482118079}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6609442060085837
[I 2024-04-18 15:09:14,079] Trial 32 finished with value: 0.6918392469781028 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6165812460484145, 'min_weight_fraction_leaf': 0.06055744102335543}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7382978723404255
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 15:09:15,183] Trial 33 finished with value: 0.6696870178180222 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 295, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7504103077643619, 'min_weight_fraction_leaf': 0.07228058521385833}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.5879828326180258
[I 2024-04-18 15:09:16,254] Trial 34 finished with value: 0.6713807536800596 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 218, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5989032499375038, 'min_weight_fraction_leaf': 0.1126902739511941}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 15:09:19,207] Trial 35 finished with value: 0.6561873030564921 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 282, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5194210324342916, 'min_weight_fraction_leaf': 0.16733609036803293}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.622093023255814
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.5686695278969958
[I 2024-04-18 15:09:22,695] Trial 36 finished with value: 0.6325821309596834 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 211, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6884813256986372, 'min_weight_fraction_leaf': 0.05223373774757657}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6492248062015504
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.575107296137339
[I 2024-04-18 15:09:23,636] Trial 37 finished with value: 0.650550033398951 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 168, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.42965970231951245, 'min_weight_fraction_leaf': 0.12103866621890363}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6724806201550387
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6072961373390557
[I 2024-04-18 15:09:24,625] Trial 38 finished with value: 0.6651699903948971 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 231, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.630638031745976, 'min_weight_fraction_leaf': 0.22096529439752421}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.5450643776824035
[I 2024-04-18 15:09:27,791] Trial 39 finished with value: 0.6257384701150246 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 184, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5204645655829614, 'min_weight_fraction_leaf': 0.07994626083099707}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.725531914893617
Fold 4 C-index: 0.6825095057034221
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 15:09:28,431] Trial 40 finished with value: 0.6578008356685427 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 128, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8342428137029814, 'min_weight_fraction_leaf': 0.027601004831219272}. Best is trial 23 with value: 0.6975178627058407.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6695278969957081
[I 2024-04-18 15:09:29,728] Trial 41 finished with value: 0.6999408363903281 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7390667171210543, 'min_weight_fraction_leaf': 0.0650163823322461}. Best is trial 41 with value: 0.6999408363903281.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6952789699570815
[I 2024-04-18 15:09:30,886] Trial 42 finished with value: 0.7120342850582264 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.729750555169298, 'min_weight_fraction_leaf': 0.06134016294643}. Best is trial 42 with value: 0.7120342850582264.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.625968992248062
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 15:09:31,773] Trial 43 finished with value: 0.6471146183087679 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 241, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.734452514405344, 'min_weight_fraction_leaf': 0.27764552944355786}. Best is trial 42 with value: 0.7120342850582264.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-18 15:09:32,949] Trial 44 finished with value: 0.7248733216425769 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7080955434810914, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 44 with value: 0.7248733216425769.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7939914163090128
[I 2024-04-18 15:09:35,019] Trial 45 finished with value: 0.7393880586367663 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 347, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7734843967662439, 'min_weight_fraction_leaf': 0.025450449925392884}. Best is trial 45 with value: 0.7393880586367663.

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6223175965665236
[I 2024-04-18 15:09:36,398] Trial 46 finished with value: 0.6776277638552342 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 325, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7817261275732721, 'min_weight_fraction_leaf': 0.026329215781045807}. Best is trial 45 with value: 0.7393880586367663.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5622317596566524
[I 2024-04-18 15:09:41,699] Trial 47 finished with value: 0.6344740529360199 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 348, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.853793854299018, 'min_weight_fraction_leaf': 0.021091534508631493}. Best is trial 45 with value: 0.7393880586367663.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6918604651162791
Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.648068669527897
[I 2024-04-18 15:09:44,563] Trial 48 finished with value: 0.6902099794249102 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 393, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7986195780539649, 'min_weight_fraction_leaf': 0.09214618096817592}. Best is trial 45 with value: 0.7393880586367663.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:09:45,803] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 4, 'n_estimators': 306, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6691201418765357, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 45 with value: 0.7393880586367663.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6223175965665236
[I 2024-04-18 15:09:47,027] Trial 50 finished with value: 0.6830101210940869 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 340, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9275708031641993, 'min_weight_fraction_leaf': 0.1346406423395477}. Best is trial 45 with value: 0.7393880586367663.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.776824034334764
[I 2024-04-18 15:09:48,061] Trial 51 finished with value: 0.7321659038694752 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 265, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7259436470560829, 'min_weight_fraction_leaf': 0.01638059410748447}. Best is trial 45 with value: 0.7393880586367663.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7811158798283262
[I 2024-04-18 15:09:49,335] Trial 52 finished with value: 0.7306701911964154 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 361, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7595846706430971, 'min_weight_fraction_leaf': 0.014704208866398664}. Best is trial 45 with value: 0.7393880586367663.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7382978723404255
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 15:09:50,160] Trial 53 finished with value: 0.6841052746431403 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7542027698360013, 'min_weight_fraction_leaf': 0.015402470958792276}. Best is trial 45 with value: 0.7393880586367663.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8154506437768241
[I 2024-04-18 15:09:51,382] Trial 54 finished with value: 0.741945144340525 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 368, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7843368754715196, 'min_weight_fraction_leaf': 0.009588827396100553}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.6781115879828327
[I 2024-04-18 15:09:53,127] Trial 55 finished with value: 0.6999849219775494 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 368, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7796747987078805, 'min_weight_fraction_leaf': 0.0060474741933994255}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7553191489361702
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.5901287553648069
[I 2024-04-18 15:09:54,259] Trial 56 finished with value: 0.6598005953808261 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 313, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8342471258560027, 'min_weight_fraction_leaf': 0.017643242602125513}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6180257510729614
[I 2024-04-18 15:09:55,508] Trial 57 finished with value: 0.6726339441896914 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 366, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6788773528660181, 'min_weight_fraction_leaf': 0.0052004852259345275}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7939914163090128
[I 2024-04-18 15:09:56,870] Trial 58 finished with value: 0.7355372730847253 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 325, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7992482838583072, 'min_weight_fraction_leaf': 0.03727434590968434}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.5858369098712446
[I 2024-04-18 15:10:02,437] Trial 59 finished with value: 0.6474721603059995 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 331, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9398005896827547, 'min_weight_fraction_leaf': 0.3787205021140745}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.776824034334764
[I 2024-04-18 15:10:03,770] Trial 60 finished with value: 0.7280228112271164 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8563868260078542, 'min_weight_fraction_leaf': 0.03801602912395921}. Best is trial 54 with value: 0.741945144340525.

Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.776824034334764
[I 2024-04-18 15:10:05,306] Trial 61 finished with value: 0.7280228112271164 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 389, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8558165022931203, 'min_weight_fraction_leaf': 0.03846250006591097}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.776824034334764
[I 2024-04-18 15:10:06,617] Trial 62 finished with value: 0.7344688916413223 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8696356118478841, 'min_weight_fraction_leaf': 0.04017384953339455}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6866952789699571
[I 2024-04-18 15:10:08,167] Trial 63 finished with value: 0.7006942539573069 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9000179407695882, 'min_weight_fraction_leaf': 0.08526971929463023}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.5717131474103586
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7553191489361702
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.5901287553648069
[I 2024-04-18 15:10:09,982] Trial 64 finished with value: 0.6586053762573201 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.81615159307643, 'min_weight_fraction_leaf': 0.04186850510319069}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.630901287553648
[I 2024-04-18 15:10:11,122] Trial 65 finished with value: 0.6801992902274572 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9582520088213788, 'min_weight_fraction_leaf': 0.042505972150112564}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:10:12,412] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8785742992700427, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6137339055793991
[I 2024-04-18 15:10:13,859] Trial 67 finished with value: 0.6721335203204006 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7935217801830478, 'min_weight_fraction_leaf': 0.001027669864454038}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7433460076045627
Fold 5 C-index: 0.6566523605150214
[I 2024-04-18 15:10:15,272] Trial 68 finished with value: 0.6943565361293625 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 372, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7633951813928166, 'min_weight_fraction_leaf': 0.07871478677265946}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.5708154506437768
[I 2024-04-18 15:10:16,770] Trial 69 finished with value: 0.6638069144766598 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 433, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8536785924338663, 'min_weight_fraction_leaf': 0.09790619933849298}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7553191489361702
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.5901287553648069
[I 2024-04-18 15:10:17,938] Trial 70 finished with value: 0.6590037826318221 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 356, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8093114050677033, 'min_weight_fraction_leaf': 0.015046883612356425}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.776824034334764
[I 2024-04-18 15:10:19,120] Trial 71 finished with value: 0.7280228112271164 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 390, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8518348687200307, 'min_weight_fraction_leaf': 0.03713836885506635}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7553648068669528
[I 2024-04-18 15:10:20,462] Trial 72 finished with value: 0.7318692951559654 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 411, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8947208863718505, 'min_weight_fraction_leaf': 0.05518072654572625}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6781115879828327
[I 2024-04-18 15:10:21,807] Trial 73 finished with value: 0.6982276652569974 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 447, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8929725842378471, 'min_weight_fraction_leaf': 0.06856567932637421}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7682403433476395
[I 2024-04-18 15:10:23,311] Trial 74 finished with value: 0.7384500851476771 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 419, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.953259493493152, 'min_weight_fraction_leaf': 0.025448437987699295}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6652360515021459
[I 2024-04-18 15:10:25,057] Trial 75 finished with value: 0.6982530224123827 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9363563981903827, 'min_weight_fraction_leaf': 0.0005708794189513977}. Best is trial 54 with value: 0.741945144340525.

Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.5775193798449613
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6051502145922747
[I 2024-04-18 15:10:32,673] Trial 76 finished with value: 0.6324478056105975 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 481, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9234386193234704, 'min_weight_fraction_leaf': 0.05291469333856853}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7467811158798283
[I 2024-04-18 15:10:34,117] Trial 77 finished with value: 0.7255872294992495 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 411, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9607062639440394, 'min_weight_fraction_leaf': 0.02607943513754812}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6223175965665236
[I 2024-04-18 15:10:35,602] Trial 78 finished with value: 0.6816623543360266 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9975909059567761, 'min_weight_fraction_leaf': 0.05226723951020879}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:10:36,763] Trial 79 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 306, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.2170140247726947, 'min_weight_fraction_leaf': 0.10996627347005558}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 15:10:38,333] Trial 80 finished with value: 0.675411548741826 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 423, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9023825688367616, 'min_weight_fraction_leaf': 0.01408379971460351}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.811787072243346
Fold 5 C-index: 0.7682403433476395
[I 2024-04-18 15:10:39,717] Trial 81 finished with value: 0.7314524401359123 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8764796755634611, 'min_weight_fraction_leaf': 0.032394025804552376}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8155893536121673
Fold 5 C-index: 0.7811158798283262
[I 2024-04-18 15:10:40,946] Trial 82 finished with value: 0.7397210276713075 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 345, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9629820831842071, 'min_weight_fraction_leaf': 0.02822135646941601}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6995708154506438
[I 2024-04-18 15:10:42,005] Trial 83 finished with value: 0.7206179634568811 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 339, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9666917502020919, 'min_weight_fraction_leaf': 0.06919184137674372}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7510638297872341
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7575107296137339
[I 2024-04-18 15:10:43,056] Trial 84 finished with value: 0.7282401077043189 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 271, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8310505206486852, 'min_weight_fraction_leaf': 0.04926831572889708}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7854077253218884
[I 2024-04-18 15:10:44,591] Trial 85 finished with value: 0.7408363852206502 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 457, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8779463483666106, 'min_weight_fraction_leaf': 0.028653981274926858}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 15:10:45,889] Trial 86 finished with value: 0.6944830901773893 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 455, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9400703500120892, 'min_weight_fraction_leaf': 0.026701494729218518}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6459227467811158
[I 2024-04-18 15:10:47,517] Trial 87 finished with value: 0.6786370233926011 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9146071566193272, 'min_weight_fraction_leaf': 0.07887820592256027}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5697674418604651
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 15:10:54,978] Trial 88 finished with value: 0.6313794103073744 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 433, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9961313077361209, 'min_weight_fraction_leaf': 0.06114746224267124}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6394849785407726
[I 2024-04-18 15:10:56,297] Trial 89 finished with value: 0.6786340381190378 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 348, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7043732954617837, 'min_weight_fraction_leaf': 0.046481507194014365}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6531007751937985
Fold 3 C-index: 0.7553191489361702
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.592274678111588
[I 2024-04-18 15:10:57,560] Trial 90 finished with value: 0.656615675026955 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 321, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.970821045246039, 'min_weight_fraction_leaf': 0.2670200337544149}. Best is trial 54 with value: 0.741945144340525.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7889733840304183
Fold 5 C-index: 0.7510729613733905
[I 2024-04-18 15:10:58,935] Trial 91 finished with value: 0.7322101531578461 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 379, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8895456090935849, 'min_weight_fraction_leaf': 0.03119285511941705}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7854077253218884
[I 2024-04-18 15:11:00,160] Trial 92 finished with value: 0.7418175701625583 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8874695098318239, 'min_weight_fraction_leaf': 0.02949610788294267}. Best is trial 54 with value: 0.741945144340525.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7896995708154506
[I 2024-04-18 15:11:01,669] Trial 93 finished with value: 0.7448456488401389 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 375, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8738702823845352, 'min_weight_fraction_leaf': 0.01437923297820495}. Best is trial 93 with value: 0.7448456488401389.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7982832618025751
[I 2024-04-18 15:11:03,837] Trial 94 finished with value: 0.7459104329253661 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 377, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.949451910660598, 'min_weight_fraction_leaf': 0.030419386073469834}. Best is trial 94 with value: 0.7459104329253661.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6351931330472103
[I 2024-04-18 15:11:05,051] Trial 95 finished with value: 0.6828002752147894 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 377, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9431217563264052, 'min_weight_fraction_leaf': 0.010213993692684513}. Best is trial 94 with value: 0.7459104329253661.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7510638297872341
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.5879828326180258
[I 2024-04-18 15:11:06,165] Trial 96 finished with value: 0.6605020567353891 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9094955787828187, 'min_weight_fraction_leaf': 0.3157465264411285}. Best is trial 94 with value: 0.7459104329253661.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7339055793991416
[I 2024-04-18 15:11:07,240] Trial 97 finished with value: 0.7300085359938184 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.952198394697822, 'min_weight_fraction_leaf': 0.02425912474782705}. Best is trial 94 with value: 0.7459104329253661.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7927756653992395
Fold 5 C-index: 0.759656652360515
[I 2024-04-18 15:11:08,423] Trial 98 finished with value: 0.7338146648486936 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 361, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8736247987420667, 'min_weight_fraction_leaf': 0.0008819764050267062}. Best is trial 94 with value: 0.7459104329253661.

[I 2024-04-18 15:11:08,793] A new study created in memory with name: no-name-44889a2a-0e0e-4cf4-b5cf-b2ce42c073b1

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6523605150214592
[I 2024-04-18 15:11:08,778] Trial 99 finished with value: 0.6943745741560027 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 61, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9850691533194039, 'min_weight_fraction_leaf': 0.03391967634670573}. Best is trial 94 with value: 0.7459104329253661.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.7459104329253661], datetime_start=datetime.datetime(2024, 4, 18, 15, 11, 1, 694673), datetime_complete=datetime.datetime(2024, 4, 18, 15, 11, 3, 836233), params={'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 377, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.949451910660598, 'min_weight_fraction_leaf': 0.030419386073469834}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=94, value=None)


* Best Score for C-index:
 0.7459104329253661

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24002650043716148
Fold 2 IBS: 0.2195880327093307
Fold 3 IBS: 0.20516941152422555
Fold 4 IBS: 0.2261913389734586
Fold 5 IBS: 0.20661847199204225
[I 2024-04-18 15:11:12,568] Trial 0 finished with value: 0.2195187511272437 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.2195187511272437.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-18 15:11:18,467] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.2195187511272437.
Fold 1 IBS: 0.23854249773980493
Fold 2 IBS: 0.2182178818806611
Fold 3 IBS: 0.20966735785662594
Fold 4 IBS: 0.22833613545654952
Fold 5 IBS: 0.21311722037387135
[I 2024-04-18 15:11:24,039] Trial 2 finished with value: 0.22157621866150254 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.2195187511272437.
Fold 1 IBS: 0.23721456237673744
Fold 2 IBS: 0.21784727156163358
Fold 3 IBS: 0.21065701044628013
Fold 4 IBS: 0.22786809016918796
Fold 5 IBS: 0.21381173774052684
[I 2024-04-18 15:11:26,093] Trial 3 finished with value: 0.22147973445887317 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.2195187511272437.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-18 15:11:31,201] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.2195187511272437.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-18 15:11:33,664] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.2195187511272437.
Fold 1 IBS: 0.2392493751788932
Fold 2 IBS: 0.21902344247502362
Fold 3 IBS: 0.20527685255271813
Fold 4 IBS: 0.2271848827960798
Fold 5 IBS: 0.20721762452919096
[I 2024-04-18 15:11:38,334] Trial 6 finished with value: 0.21959043550638113 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.2195187511272437.
Fold 1 IBS: 0.2398410744268511
Fold 2 IBS: 0.21870238171662731
Fold 3 IBS: 0.20710747054081416
Fold 4 IBS: 0.22755865268415965
Fold 5 IBS: 0.2112745735010617
[I 2024-04-18 15:11:41,370] Trial 7 finished with value: 0.2208968305739028 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.2195187511272437.
Fold 1 IBS: 0.23957470227891445
Fold 2 IBS: 0.2162417166426307
Fold 3 IBS: 0.21174514922552365
Fold 4 IBS: 0.2300795169018546
Fold 5 IBS: 0.21607481578625806
[I 2024-04-18 15:11:42,018] Trial 8 finished with value: 0.22274318016703626 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.2195187511272437.
Fold 1 IBS: 0.23875665553923067
Fold 2 IBS: 0.2234567805267999
Fold 3 IBS: 0.21570959555440058
Fold 4 IBS: 0.23236763138600128
Fold 5 IBS: 0.21722446168309972
[I 2024-04-18 15:11:48,538] Trial 9 finished with value: 0.22550302493790647 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.2195187511272437.
Fold 1 IBS: 0.24672496618607107
Fold 2 IBS: 0.23224650601788785
Fold 3 IBS: 0.23004987749916536
Fold 4 IBS: 0.2412296281450331
Fold 5 IBS: 0.23015666331663637
[I 2024-04-18 15:11:53,387] Trial 10 finished with value: 0.23608152823295875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.2195187511272437.
Fold 1 IBS: 0.2380277652018022
Fold 2 IBS: 0.21697758226785982
Fold 3 IBS: 0.20333025336704522
Fold 4 IBS: 0.22432904020043967
Fold 5 IBS: 0.20891703440717016
[I 2024-04-18 15:11:58,180] Trial 11 finished with value: 0.21831633508886342 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.24197408743987364
Fold 2 IBS: 0.22462087547405188
Fold 3 IBS: 0.21697963441431892
Fold 4 IBS: 0.23244946495449173
Fold 5 IBS: 0.22332167810690245
[I 2024-04-18 15:12:02,063] Trial 12 finished with value: 0.2278691480779277 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.17085174271948028, 'min_weight_fraction_leaf': 0.07739259194541037}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.2413651929439054
Fold 2 IBS: 0.22563486805886987
Fold 3 IBS: 0.21913992576810085
Fold 4 IBS: 0.23404142096679692
Fold 5 IBS: 0.22068725395905678
[I 2024-04-18 15:12:07,012] Trial 13 finished with value: 0.22817373233934596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 11, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.33474644057405917, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.2466509665060547
Fold 2 IBS: 0.23228971279902047
Fold 3 IBS: 0.2296373269941608
Fold 4 IBS: 0.24136926563509062
Fold 5 IBS: 0.23015015291482488
[I 2024-04-18 15:12:13,146] Trial 14 finished with value: 0.23601948496983027 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3469585144995889, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 11 with value: 0.21831633508886342.

Fold 1 IBS: 0.23976286671489286
Fold 2 IBS: 0.22124251809724488
Fold 3 IBS: 0.20664541213591994
Fold 4 IBS: 0.22483381295863067
Fold 5 IBS: 0.20644172479241546
[I 2024-04-18 15:12:16,729] Trial 15 finished with value: 0.21978526693982076 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 191, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9428730581718685, 'min_weight_fraction_leaf': 0.10116500366378353}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.24650981388840468
Fold 2 IBS: 0.23213868861489242
Fold 3 IBS: 0.2302890634878654
Fold 4 IBS: 0.24093148821024132
Fold 5 IBS: 0.22974178688334831
[I 2024-04-18 15:12:24,977] Trial 16 finished with value: 0.23592216821695042 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.10043506002193597, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.2378383326617297
Fold 2 IBS: 0.21846091601420353
Fold 3 IBS: 0.20349517861653774
Fold 4 IBS: 0.22415860290883827
Fold 5 IBS: 0.20858565955630182
[I 2024-04-18 15:12:44,124] Trial 17 finished with value: 0.2185077379515222 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.680642613858846, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.24711462527586198
Fold 2 IBS: 0.23205610803263702
Fold 3 IBS: 0.2295214617789819
Fold 4 IBS: 0.2413788658274469
Fold 5 IBS: 0.2298759092685758
[I 2024-04-18 15:12:45,483] Trial 18 finished with value: 0.23598939403670074 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.37698225012457987, 'min_weight_fraction_leaf': 0.3468482674415689}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23656424148470453
Fold 2 IBS: 0.21933628682653783
Fold 3 IBS: 0.20609169715833275
Fold 4 IBS: 0.22519578600864715
Fold 5 IBS: 0.2099043542329279
[I 2024-04-18 15:12:47,674] Trial 19 finished with value: 0.21941847314223004 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6559030397076546, 'min_weight_fraction_leaf': 0.22320019337912467}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23786376082717395
Fold 2 IBS: 0.21836091647783393
Fold 3 IBS: 0.20372161282817405
Fold 4 IBS: 0.22447705444201024
Fold 5 IBS: 0.2082653436834445
[I 2024-04-18 15:12:52,767] Trial 20 finished with value: 0.21853773765172732 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 391, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6674617762374991, 'min_weight_fraction_leaf': 0.16209852212373996}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23774933024444164
Fold 2 IBS: 0.2184335100622743
Fold 3 IBS: 0.20362532595840235
Fold 4 IBS: 0.2242998726538231
Fold 5 IBS: 0.20842580562556162
[I 2024-04-18 15:12:58,014] Trial 21 finished with value: 0.21850676890890058 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 399, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6547034385443382, 'min_weight_fraction_leaf': 0.15905090414532833}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.2368785996003562
Fold 2 IBS: 0.21937717058679126
Fold 3 IBS: 0.203687146108178
Fold 4 IBS: 0.22555398751253808
Fold 5 IBS: 0.20916355069126247
[I 2024-04-18 15:13:02,227] Trial 22 finished with value: 0.2189320908998252 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8545720765125939, 'min_weight_fraction_leaf': 0.29929427874765735}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23787628626336965
Fold 2 IBS: 0.22095835226885344
Fold 3 IBS: 0.20885831620817125
Fold 4 IBS: 0.22866895863901376
Fold 5 IBS: 0.21438548733532256
[I 2024-04-18 15:13:07,256] Trial 23 finished with value: 0.22214948014294614 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 410, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4802933268447024, 'min_weight_fraction_leaf': 0.19745804017428042}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.2371384869108102
Fold 2 IBS: 0.2200918273691352
Fold 3 IBS: 0.20718329167859142
Fold 4 IBS: 0.22831232676696028
Fold 5 IBS: 0.21177404239667041
[I 2024-04-18 15:13:09,987] Trial 24 finished with value: 0.22089999502443353 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 225, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6816191290189925, 'min_weight_fraction_leaf': 0.26799785805866544}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23869055770451159
Fold 2 IBS: 0.22237095238345603
Fold 3 IBS: 0.2127297876562886
Fold 4 IBS: 0.23068331290820598
Fold 5 IBS: 0.2155941697012718
[I 2024-04-18 15:13:14,503] Trial 25 finished with value: 0.22401375607074678 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 14, 'n_estimators': 352, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5899443133604012, 'min_weight_fraction_leaf': 0.13197369292803862}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.24308190402317828
Fold 2 IBS: 0.22344410449496827
Fold 3 IBS: 0.20625423481293126
Fold 4 IBS: 0.22930740794391846
Fold 5 IBS: 0.20624959577489607
[I 2024-04-18 15:13:21,477] Trial 26 finished with value: 0.22166744940997846 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 465, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.26240649480368444, 'min_weight_fraction_leaf': 0.032491665401972535}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.24673462317853367
Fold 2 IBS: 0.23236995264995583
Fold 3 IBS: 0.229595612999019
Fold 4 IBS: 0.24136100286494802
Fold 5 IBS: 0.2303541415510534
[I 2024-04-18 15:13:24,779] Trial 27 finished with value: 0.236083066648702 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4178817585010918, 'min_weight_fraction_leaf': 0.2309140196266319}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23699293801610613
Fold 2 IBS: 0.21898298122697826
Fold 3 IBS: 0.20312912362583016
Fold 4 IBS: 0.22440333384818867
Fold 5 IBS: 0.20827457435233956
[I 2024-04-18 15:13:28,254] Trial 28 finished with value: 0.21835659021388856 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 17, 'n_estimators': 314, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8792056123150627, 'min_weight_fraction_leaf': 0.1768359166997542}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.2372564217669422
Fold 2 IBS: 0.21891901663353266
Fold 3 IBS: 0.2045257464114302
Fold 4 IBS: 0.22402370944040106
Fold 5 IBS: 0.20805695652933387
[I 2024-04-18 15:13:32,315] Trial 29 finished with value: 0.218556370156328 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 18, 'n_estimators': 309, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.920260035267285, 'min_weight_fraction_leaf': 0.0945511339426436}. Best is trial 11 with value: 0.21831633508886342.

Fold 1 IBS: 0.23788847993111656
Fold 2 IBS: 0.2180765411385516
Fold 3 IBS: 0.2046960039221167
Fold 4 IBS: 0.2247765505967664
Fold 5 IBS: 0.2077685664696797
[I 2024-04-18 15:13:36,700] Trial 30 finished with value: 0.2186412284116462 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 343, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.889360966245883, 'min_weight_fraction_leaf': 0.14458594432203747}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23712385212056705
Fold 2 IBS: 0.21925458444400572
Fold 3 IBS: 0.20321552597569
Fold 4 IBS: 0.2255422658404121
Fold 5 IBS: 0.20908692558988173
[I 2024-04-18 15:13:41,605] Trial 31 finished with value: 0.21884463079411134 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 17, 'n_estimators': 379, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.718836302991206, 'min_weight_fraction_leaf': 0.19660285202795294}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.2370242104297491
Fold 2 IBS: 0.21865797517539415
Fold 3 IBS: 0.20338018876961161
Fold 4 IBS: 0.22491283193485026
Fold 5 IBS: 0.2082895137123623
[I 2024-04-18 15:13:46,144] Trial 32 finished with value: 0.2184529440043935 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 416, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8390423977775334, 'min_weight_fraction_leaf': 0.2563335416263473}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.2368553907918382
Fold 2 IBS: 0.2189730321471961
Fold 3 IBS: 0.20397345671045067
Fold 4 IBS: 0.22496083767511524
Fold 5 IBS: 0.20875556637142914
[I 2024-04-18 15:13:51,329] Trial 33 finished with value: 0.21870365673920586 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 444, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8431022216447035, 'min_weight_fraction_leaf': 0.2605850870871364}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.2388826090971516
Fold 2 IBS: 0.2225614784678285
Fold 3 IBS: 0.21322078252715151
Fold 4 IBS: 0.232406926992934
Fold 5 IBS: 0.21603954302017592
[I 2024-04-18 15:13:55,626] Trial 34 finished with value: 0.2246222680210483 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 410, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7450307353594428, 'min_weight_fraction_leaf': 0.32730393018493636}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.2406105268625264
Fold 2 IBS: 0.22507403573120324
Fold 3 IBS: 0.21882151076649461
Fold 4 IBS: 0.23581181134919876
Fold 5 IBS: 0.2211012266389428
[I 2024-04-18 15:14:01,939] Trial 35 finished with value: 0.22828382226967317 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 495, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8341266639808844, 'min_weight_fraction_leaf': 0.35885640486434434}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.24076426284799998
Fold 2 IBS: 0.21923045266373134
Fold 3 IBS: 0.20024735394153786
Fold 4 IBS: 0.22924585508206394
Fold 5 IBS: 0.21046037704500223
[I 2024-04-18 15:14:06,687] Trial 36 finished with value: 0.21998966031606706 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 330, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5177964744982437, 'min_weight_fraction_leaf': 0.23348249869333368}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.24630754099764912
Fold 2 IBS: 0.23213528999695818
Fold 3 IBS: 0.2295263315323432
Fold 4 IBS: 0.2415033938568314
Fold 5 IBS: 0.23028940378327778
[I 2024-04-18 15:14:11,977] Trial 37 finished with value: 0.23595239203341195 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 449, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6219324477851398, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23882977528661037
Fold 2 IBS: 0.2182439147944572
Fold 3 IBS: 0.20558556893408764
Fold 4 IBS: 0.2252385618298528
Fold 5 IBS: 0.20685629457562732
[I 2024-04-18 15:14:15,372] Trial 38 finished with value: 0.21895082308412706 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 293, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7293831463584859, 'min_weight_fraction_leaf': 0.11814667951535995}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23983250896067831
Fold 2 IBS: 0.22347184310398796
Fold 3 IBS: 0.21605674389330978
Fold 4 IBS: 0.23350701060946966
Fold 5 IBS: 0.21850272303207727
[I 2024-04-18 15:14:19,384] Trial 39 finished with value: 0.22627416591990457 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 243, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9887286618847455, 'min_weight_fraction_leaf': 0.39549454808011786}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23790733224672606
Fold 2 IBS: 0.21929911067240893
Fold 3 IBS: 0.2113980864368226
Fold 4 IBS: 0.22900665481742277
Fold 5 IBS: 0.2150925225233949
[I 2024-04-18 15:14:24,017] Trial 40 finished with value: 0.22254074133935506 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 410, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8991573166321477, 'min_weight_fraction_leaf': 0.06754192760750999}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23792072889847088
Fold 2 IBS: 0.21844435853616387
Fold 3 IBS: 0.2031006332300606
Fold 4 IBS: 0.22423906078171646
Fold 5 IBS: 0.20886077759403016
[I 2024-04-18 15:14:29,447] Trial 41 finished with value: 0.21851311180808838 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6117960174406367, 'min_weight_fraction_leaf': 0.17427030969384627}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.2370951707282749
Fold 2 IBS: 0.21948590557950481
Fold 3 IBS: 0.20393605842012594
Fold 4 IBS: 0.22676395430462387
Fold 5 IBS: 0.2107997623236065
[I 2024-04-18 15:14:33,683] Trial 42 finished with value: 0.2196161702712272 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 365, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8078708827436648, 'min_weight_fraction_leaf': 0.2949507685726118}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23723284046649815
Fold 2 IBS: 0.2183412089701396
Fold 3 IBS: 0.20423599882039226
Fold 4 IBS: 0.22439298746117667
Fold 5 IBS: 0.20827972745456647
[I 2024-04-18 15:14:38,948] Trial 43 finished with value: 0.21849655263455459 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 430, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7716935541465594, 'min_weight_fraction_leaf': 0.21337170010935197}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23704523966640068
Fold 2 IBS: 0.21936356743136345
Fold 3 IBS: 0.20440668736778372
Fold 4 IBS: 0.2258894295495351
Fold 5 IBS: 0.20922519911938453
[I 2024-04-18 15:14:44,234] Trial 44 finished with value: 0.21918602462689346 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 467, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7670863193372683, 'min_weight_fraction_leaf': 0.25564312556078794}. Best is trial 11 with value: 0.21831633508886342.

Fold 1 IBS: 0.23747885558720908
Fold 2 IBS: 0.2182158397444273
Fold 3 IBS: 0.2051184817191784
Fold 4 IBS: 0.22477313569503773
Fold 5 IBS: 0.20779683491497394
[I 2024-04-18 15:14:49,271] Trial 45 finished with value: 0.2186766295321653 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 423, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8732282072435447, 'min_weight_fraction_leaf': 0.21737715090273346}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.24146274510328755
Fold 2 IBS: 0.22120633219111893
Fold 3 IBS: 0.20427581901257044
Fold 4 IBS: 0.2260424188972459
Fold 5 IBS: 0.20767896038910674
[I 2024-04-18 15:14:53,994] Trial 46 finished with value: 0.22013325511866594 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 436, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5368271784486555, 'min_weight_fraction_leaf': 0.03723655783815147}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.2383838497826796
Fold 2 IBS: 0.21869882648524927
Fold 3 IBS: 0.20573925124007544
Fold 4 IBS: 0.225982032008938
Fold 5 IBS: 0.20696975590638944
[I 2024-04-18 15:14:58,196] Trial 47 finished with value: 0.21915474308466631 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 339, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9297399622720337, 'min_weight_fraction_leaf': 0.1625947698183845}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23930942479557607
Fold 2 IBS: 0.21796227932876924
Fold 3 IBS: 0.2047287605757211
Fold 4 IBS: 0.22701029323770616
Fold 5 IBS: 0.20653950701586177
[I 2024-04-18 15:15:03,751] Trial 48 finished with value: 0.2191100529907269 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 401, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7986195780539649, 'min_weight_fraction_leaf': 0.11729084755029684}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23828933784867945
Fold 2 IBS: 0.22094698603523838
Fold 3 IBS: 0.2130508230460018
Fold 4 IBS: 0.2299870189577281
Fold 5 IBS: 0.21525500244259363
[I 2024-04-18 15:15:09,150] Trial 49 finished with value: 0.22350583366604826 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 15, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9677734401567635, 'min_weight_fraction_leaf': 0.28234553982051963}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23788436064528679
Fold 2 IBS: 0.2187022025132949
Fold 3 IBS: 0.2106688647984885
Fold 4 IBS: 0.22883365139986783
Fold 5 IBS: 0.21432411875104623
[I 2024-04-18 15:15:13,027] Trial 50 finished with value: 0.22208263962159686 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7139771520407627, 'min_weight_fraction_leaf': 0.152411049016055}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23665743329210834
Fold 2 IBS: 0.21947792121389778
Fold 3 IBS: 0.20523002829813347
Fold 4 IBS: 0.22682244180439892
Fold 5 IBS: 0.2099507160654557
[I 2024-04-18 15:15:17,955] Trial 51 finished with value: 0.21962770813479887 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 427, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6848140304375441, 'min_weight_fraction_leaf': 0.24369593288134817}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23737773171450746
Fold 2 IBS: 0.21921838144297848
Fold 3 IBS: 0.20381538349987743
Fold 4 IBS: 0.2256095404457682
Fold 5 IBS: 0.20934899164539686
[I 2024-04-18 15:15:22,790] Trial 52 finished with value: 0.21907400574970567 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 380, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6301578326873808, 'min_weight_fraction_leaf': 0.208464530420868}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23757189158548545
Fold 2 IBS: 0.21807573580367073
Fold 3 IBS: 0.20437321255760663
Fold 4 IBS: 0.22436923691227179
Fold 5 IBS: 0.20790132174215736
[I 2024-04-18 15:15:27,138] Trial 53 finished with value: 0.2184582797202384 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 324, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7673028557543038, 'min_weight_fraction_leaf': 0.17857938204264587}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.2382254071907699
Fold 2 IBS: 0.21785088898906105
Fold 3 IBS: 0.2054732596999084
Fold 4 IBS: 0.22508656273852526
Fold 5 IBS: 0.20786479950873096
[I 2024-04-18 15:15:30,728] Trial 54 finished with value: 0.21890018362539912 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 325, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8195360588375347, 'min_weight_fraction_leaf': 0.177470554244519}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23670989893400973
Fold 2 IBS: 0.2205826438990102
Fold 3 IBS: 0.20804220726174294
Fold 4 IBS: 0.23000342392448325
Fold 5 IBS: 0.2128585170945381
[I 2024-04-18 15:15:33,421] Trial 55 finished with value: 0.22163933822275683 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 263, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7700249992055866, 'min_weight_fraction_leaf': 0.31525249693090607}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.24731064146746431
Fold 2 IBS: 0.22129334575090867
Fold 3 IBS: 0.20488176231599486
Fold 4 IBS: 0.22640380294799475
Fold 5 IBS: 0.20611636851307832
[I 2024-04-18 15:15:36,540] Trial 56 finished with value: 0.22120118419908819 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 305, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.2590741226737293, 'min_weight_fraction_leaf': 0.017768508301368495}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23767670302371013
Fold 2 IBS: 0.2181974941139469
Fold 3 IBS: 0.20480910274739395
Fold 4 IBS: 0.2252921646675523
Fold 5 IBS: 0.2077942862444248
[I 2024-04-18 15:15:40,361] Trial 57 finished with value: 0.21875395015940563 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 358, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.872171296953472, 'min_weight_fraction_leaf': 0.08182367043940292}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.23791334080524068
Fold 2 IBS: 0.2181605349104258
Fold 3 IBS: 0.20438158162938022
Fold 4 IBS: 0.22538475302432953
Fold 5 IBS: 0.20801986691572547
[I 2024-04-18 15:15:45,647] Trial 58 finished with value: 0.21877201545702035 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 397, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7875104211228715, 'min_weight_fraction_leaf': 0.1797104825231977}. Best is trial 11 with value: 0.21831633508886342.
Fold 1 IBS: 0.24603887189817467
Fold 2 IBS: 0.23216627297804024
Fold 3 IBS: 0.22957933565799618
Fold 4 IBS: 0.24101137138446863
Fold 5 IBS: 0.23012103672884626
[I 2024-04-18 15:15:47,361] Trial 59 finished with value: 0.23578337772950517 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 182, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.19306239332224656, 'min_weight_fraction_leaf': 0.24500554153841198}. Best is trial 11 with value: 0.21831633508886342.

Fold 1 IBS: 0.2377052136548948
Fold 2 IBS: 0.21605965008867054
Fold 3 IBS: 0.20558825307293532
Fold 4 IBS: 0.2254323656319241
Fold 5 IBS: 0.2067921952642682
[I 2024-04-18 15:15:48,540] Trial 60 finished with value: 0.21831553554253857 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 102, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.2992752088637204, 'min_weight_fraction_leaf': 0.05635944811975884}. Best is trial 60 with value: 0.21831553554253857.
Fold 1 IBS: 0.23794023360294106
Fold 2 IBS: 0.2171601602160643
Fold 3 IBS: 0.2061252197645397
Fold 4 IBS: 0.22518242245675577
Fold 5 IBS: 0.20728448682330153
[I 2024-04-18 15:15:49,758] Trial 61 finished with value: 0.21873850457272045 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 97, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3418211965406646, 'min_weight_fraction_leaf': 0.0543792823934551}. Best is trial 60 with value: 0.21831553554253857.
Fold 1 IBS: 0.23829023968530796
Fold 2 IBS: 0.21743156658651058
Fold 3 IBS: 0.20483262429896448
Fold 4 IBS: 0.22638638087690802
Fold 5 IBS: 0.20722311265540172
[I 2024-04-18 15:15:51,142] Trial 62 finished with value: 0.21883278482061855 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 95, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.29484778697244785, 'min_weight_fraction_leaf': 0.002559168241068558}. Best is trial 60 with value: 0.21831553554253857.
Fold 1 IBS: 0.2378355800988657
Fold 2 IBS: 0.22764141423419662
Fold 3 IBS: 0.20098315042087478
Fold 4 IBS: 0.22036634785466527
Fold 5 IBS: 0.2093473467279067
[I 2024-04-18 15:15:51,480] Trial 63 finished with value: 0.2192347678673018 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.39403389452783044, 'min_weight_fraction_leaf': 0.052220008598216766}. Best is trial 60 with value: 0.21831553554253857.
Fold 1 IBS: 0.24578668876588725
Fold 2 IBS: 0.23215403695358455
Fold 3 IBS: 0.22999679833142675
Fold 4 IBS: 0.24122832299038308
Fold 5 IBS: 0.23038612839816675
[I 2024-04-18 15:15:56,202] Trial 64 finished with value: 0.23591039508788966 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 455, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17959921537819776, 'min_weight_fraction_leaf': 0.13292711749744568}. Best is trial 60 with value: 0.21831553554253857.
Fold 1 IBS: 0.2372501415025032
Fold 2 IBS: 0.21713357764891703
Fold 3 IBS: 0.20539990990574614
Fold 4 IBS: 0.22439453769432863
Fold 5 IBS: 0.20840355832639987
[I 2024-04-18 15:15:58,029] Trial 65 finished with value: 0.21851634501557898 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4530546432791985, 'min_weight_fraction_leaf': 0.023578028624282592}. Best is trial 60 with value: 0.21831553554253857.
Fold 1 IBS: 0.2468619696601002
Fold 2 IBS: 0.23225065705336476
Fold 3 IBS: 0.22986841907226022
Fold 4 IBS: 0.24119792827006323
Fold 5 IBS: 0.23023406249122996
[I 2024-04-18 15:16:00,703] Trial 66 finished with value: 0.2360826073094037 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.30029194568874296, 'min_weight_fraction_leaf': 0.2772702088742331}. Best is trial 60 with value: 0.21831553554253857.
Fold 1 IBS: 0.23706409994142683
Fold 2 IBS: 0.21867813671542305
Fold 3 IBS: 0.20331406959555864
Fold 4 IBS: 0.22385730267104728
Fold 5 IBS: 0.20825167266294356
[I 2024-04-18 15:16:04,579] Trial 67 finished with value: 0.2182330563172799 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 322, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7501323059528776, 'min_weight_fraction_leaf': 0.21276472095633941}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.2465763459553614
Fold 2 IBS: 0.23209890155281054
Fold 3 IBS: 0.23032655699267093
Fold 4 IBS: 0.24091171669708755
Fold 5 IBS: 0.22953618148031668
[I 2024-04-18 15:16:07,854] Trial 68 finished with value: 0.23588994053564943 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.12941000470259795, 'min_weight_fraction_leaf': 0.21681144274322522}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.24724427359000098
Fold 2 IBS: 0.232035738886148
Fold 3 IBS: 0.23019676815687193
Fold 4 IBS: 0.24120529128779483
Fold 5 IBS: 0.2295370913685405
[I 2024-04-18 15:16:08,908] Trial 69 finished with value: 0.23604383265787127 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 70, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.219941951969392, 'min_weight_fraction_leaf': 0.10951579239377879}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23748623977112815
Fold 2 IBS: 0.21808156139177012
Fold 3 IBS: 0.2048919532621076
Fold 4 IBS: 0.22454937466012256
Fold 5 IBS: 0.20788604181213943
[I 2024-04-18 15:16:14,202] Trial 70 finished with value: 0.21857903417945357 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 322, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9505457977379985, 'min_weight_fraction_leaf': 0.23208970653747668}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23806772975005824
Fold 2 IBS: 0.21803349577664738
Fold 3 IBS: 0.20559245885539992
Fold 4 IBS: 0.2243529415715472
Fold 5 IBS: 0.20786261953065804
[I 2024-04-18 15:16:17,491] Trial 71 finished with value: 0.21878184909686213 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 293, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8468971230211502, 'min_weight_fraction_leaf': 0.18812793170286762}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23785172076555972
Fold 2 IBS: 0.21798956211673767
Fold 3 IBS: 0.2051009422212171
Fold 4 IBS: 0.22473594742137984
Fold 5 IBS: 0.20820385793494775
[I 2024-04-18 15:16:21,774] Trial 72 finished with value: 0.2187764060919684 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 371, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7270099277411307, 'min_weight_fraction_leaf': 0.16176136715261633}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.2417924096634104
Fold 2 IBS: 0.22586546146053207
Fold 3 IBS: 0.20282843309835946
Fold 4 IBS: 0.22885127497389074
Fold 5 IBS: 0.2060847579126855
[I 2024-04-18 15:16:25,484] Trial 73 finished with value: 0.22108446742177562 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 340, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6975597256420069, 'min_weight_fraction_leaf': 0.2033592399075348}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23862508780445216
Fold 2 IBS: 0.21835333122212439
Fold 3 IBS: 0.20533591925705627
Fold 4 IBS: 0.22550923839756054
Fold 5 IBS: 0.20734985532957553
[I 2024-04-18 15:16:29,137] Trial 74 finished with value: 0.2190346864021538 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 348, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.753684596691122, 'min_weight_fraction_leaf': 0.13614243095115575}. Best is trial 67 with value: 0.2182330563172799.

Fold 1 IBS: 0.2380315443396539
Fold 2 IBS: 0.218584818434336
Fold 3 IBS: 0.2090327196956189
Fold 4 IBS: 0.22815174669205668
Fold 5 IBS: 0.2127482081129169
[I 2024-04-18 15:16:33,530] Trial 75 finished with value: 0.22130980745491646 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 420, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6496285186532654, 'min_weight_fraction_leaf': 0.09733418927981143}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23951407371043723
Fold 2 IBS: 0.2236154605317524
Fold 3 IBS: 0.21733512904776037
Fold 4 IBS: 0.23282386265018934
Fold 5 IBS: 0.21729889644220104
[I 2024-04-18 15:16:36,190] Trial 76 finished with value: 0.2261174844764681 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 16, 'n_estimators': 266, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5756844343562433, 'min_weight_fraction_leaf': 0.07601195190861526}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23715386631414168
Fold 2 IBS: 0.21848395042653124
Fold 3 IBS: 0.20561698544337584
Fold 4 IBS: 0.22462871012025884
Fold 5 IBS: 0.2079825963458529
[I 2024-04-18 15:16:39,331] Trial 77 finished with value: 0.21877322173003208 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 18, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8920726552446581, 'min_weight_fraction_leaf': 0.1910692737608619}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.2370568485411882
Fold 2 IBS: 0.21852601456643134
Fold 3 IBS: 0.2041890675682413
Fold 4 IBS: 0.22437216929868867
Fold 5 IBS: 0.2084314166765254
[I 2024-04-18 15:16:45,081] Trial 78 finished with value: 0.21851510333021498 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 489, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7470085472259564, 'min_weight_fraction_leaf': 0.21334377425133222}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23708398353054938
Fold 2 IBS: 0.21872856607600916
Fold 3 IBS: 0.2034099653425133
Fold 4 IBS: 0.22545278448326123
Fold 5 IBS: 0.2086606901530677
[I 2024-04-18 15:16:49,632] Trial 79 finished with value: 0.21866719791708014 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 401, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8243292884577901, 'min_weight_fraction_leaf': 0.26485970890668353}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.2441965629411085
Fold 2 IBS: 0.22954228978529972
Fold 3 IBS: 0.22447931059488316
Fold 4 IBS: 0.23749535126687155
Fold 5 IBS: 0.23025091515700558
[I 2024-04-18 15:16:53,386] Trial 80 finished with value: 0.2331928859490337 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 310, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3072572489293329, 'min_weight_fraction_leaf': 0.1522677065850861}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.2370804186069732
Fold 2 IBS: 0.21937362208710115
Fold 3 IBS: 0.2043330250510676
Fold 4 IBS: 0.22589041391224704
Fold 5 IBS: 0.2097951503716058
[I 2024-04-18 15:16:58,134] Trial 81 finished with value: 0.21929452600579896 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 434, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6558472647626825, 'min_weight_fraction_leaf': 0.2234766497945251}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23797885455307627
Fold 2 IBS: 0.21805281216340294
Fold 3 IBS: 0.20435697451148427
Fold 4 IBS: 0.22528145377029835
Fold 5 IBS: 0.20801347414000618
[I 2024-04-18 15:17:02,797] Trial 82 finished with value: 0.2187367138276536 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 382, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.787755636367892, 'min_weight_fraction_leaf': 0.16906548431533788}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23760491840195602
Fold 2 IBS: 0.21815286444951543
Fold 3 IBS: 0.2038934636344283
Fold 4 IBS: 0.22409095964508435
Fold 5 IBS: 0.2082681792282294
[I 2024-04-18 15:17:06,995] Trial 83 finished with value: 0.21840207707184273 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7028299773774797, 'min_weight_fraction_leaf': 0.18646846397344258}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.2368290898769815
Fold 2 IBS: 0.21927890296877176
Fold 3 IBS: 0.20403920592475572
Fold 4 IBS: 0.2255572011185585
Fold 5 IBS: 0.2097798017536435
[I 2024-04-18 15:17:11,783] Trial 84 finished with value: 0.21909684032854218 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6973894931062171, 'min_weight_fraction_leaf': 0.24289217834381915}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23725234626179395
Fold 2 IBS: 0.21934034440867287
Fold 3 IBS: 0.20364071226496688
Fold 4 IBS: 0.2250971548423093
Fold 5 IBS: 0.20961497350569375
[I 2024-04-18 15:17:15,975] Trial 85 finished with value: 0.21898910625668738 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 354, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5975841646767595, 'min_weight_fraction_leaf': 0.20273924787015346}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.2380226405085431
Fold 2 IBS: 0.21830800012150275
Fold 3 IBS: 0.20512691638541078
Fold 4 IBS: 0.22512414988644058
Fold 5 IBS: 0.2075011266583262
[I 2024-04-18 15:17:20,655] Trial 86 finished with value: 0.21881656671204466 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 321, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.912018342486184, 'min_weight_fraction_leaf': 0.1887993138456613}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23892171009199983
Fold 2 IBS: 0.21844887625335205
Fold 3 IBS: 0.20574319859564336
Fold 4 IBS: 0.2251783533296037
Fold 5 IBS: 0.20676098255353767
[I 2024-04-18 15:17:24,937] Trial 87 finished with value: 0.2190106241648273 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.867438251213195, 'min_weight_fraction_leaf': 0.1488572675762337}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23803613581768998
Fold 2 IBS: 0.2202729491677797
Fold 3 IBS: 0.21161646425367317
Fold 4 IBS: 0.22902552864035472
Fold 5 IBS: 0.21436495864363253
[I 2024-04-18 15:17:28,561] Trial 88 finished with value: 0.22266320730462602 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8132190195446829, 'min_weight_fraction_leaf': 0.22523477678020928}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23865039042519656
Fold 2 IBS: 0.21794059006922759
Fold 3 IBS: 0.203377729539853
Fold 4 IBS: 0.22384571104306056
Fold 5 IBS: 0.2087901209492878
[I 2024-04-18 15:17:32,738] Trial 89 finished with value: 0.2185209084053251 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3633190433617523, 'min_weight_fraction_leaf': 0.002952993327597124}. Best is trial 67 with value: 0.2182330563172799.

Fold 1 IBS: 0.24306418653288445
Fold 2 IBS: 0.22515153493924325
Fold 3 IBS: 0.1975215183442548
Fold 4 IBS: 0.22885063171920877
Fold 5 IBS: 0.20614416280161527
[I 2024-04-18 15:17:37,752] Trial 90 finished with value: 0.2201464068674413 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 456, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7361210166358332, 'min_weight_fraction_leaf': 0.2524918082691855}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23776347268963513
Fold 2 IBS: 0.21793810774310016
Fold 3 IBS: 0.2045185088977267
Fold 4 IBS: 0.22480630923293607
Fold 5 IBS: 0.20794858004520358
[I 2024-04-18 15:17:42,376] Trial 91 finished with value: 0.2185949957217203 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 391, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7668694233392135, 'min_weight_fraction_leaf': 0.18299422455098524}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23734770367984698
Fold 2 IBS: 0.21870364406804077
Fold 3 IBS: 0.20416119555306686
Fold 4 IBS: 0.2241398481442358
Fold 5 IBS: 0.2079597615528484
[I 2024-04-18 15:17:46,892] Trial 92 finished with value: 0.21846243059960777 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 413, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.674053508975249, 'min_weight_fraction_leaf': 0.16584488535594183}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23838968219636708
Fold 2 IBS: 0.21857949574048435
Fold 3 IBS: 0.20484658663296273
Fold 4 IBS: 0.2252133503326008
Fold 5 IBS: 0.20724525237636618
[I 2024-04-18 15:17:51,828] Trial 93 finished with value: 0.21885487345575622 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 415, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7081637196875243, 'min_weight_fraction_leaf': 0.1275254539045052}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23755530420514218
Fold 2 IBS: 0.218460260255504
Fold 3 IBS: 0.2045790700957653
Fold 4 IBS: 0.22419808016084275
Fold 5 IBS: 0.20813288999487464
[I 2024-04-18 15:17:57,756] Trial 94 finished with value: 0.21858512094242574 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 436, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6755360085300319, 'min_weight_fraction_leaf': 0.16372745252247656}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23809345234460833
Fold 2 IBS: 0.2225468510122206
Fold 3 IBS: 0.21431658472497037
Fold 4 IBS: 0.2314396435546642
Fold 5 IBS: 0.21620320324734163
[I 2024-04-18 15:18:02,673] Trial 95 finished with value: 0.224519946976761 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 17, 'n_estimators': 441, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6389083264803858, 'min_weight_fraction_leaf': 0.2084621937302656}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23784220561688135
Fold 2 IBS: 0.21800822041420892
Fold 3 IBS: 0.20454671411739295
Fold 4 IBS: 0.22497931450054906
Fold 5 IBS: 0.20780440447171422
[I 2024-04-18 15:18:06,697] Trial 96 finished with value: 0.21863617182414927 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7944015155593868, 'min_weight_fraction_leaf': 0.17580604962506094}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.2393970639883301
Fold 2 IBS: 0.22555454489210516
Fold 3 IBS: 0.21368466897982788
Fold 4 IBS: 0.2327101169822082
Fold 5 IBS: 0.21773861401936676
[I 2024-04-18 15:18:08,603] Trial 97 finished with value: 0.2258170017723676 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5343481602895627, 'min_weight_fraction_leaf': 0.23739837852538387}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.23742947434711864
Fold 2 IBS: 0.2185706165702874
Fold 3 IBS: 0.20507778951696268
Fold 4 IBS: 0.2244426787483098
Fold 5 IBS: 0.20815330004322988
[I 2024-04-18 15:18:13,184] Trial 98 finished with value: 0.21873477184518167 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 16, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8309368311045071, 'min_weight_fraction_leaf': 0.14209398360733708}. Best is trial 67 with value: 0.2182330563172799.
Fold 1 IBS: 0.24092775853215218
Fold 2 IBS: 0.2217038248699599
Fold 3 IBS: 0.20549445064088714
Fold 4 IBS: 0.2261180852586202
Fold 5 IBS: 0.20728509072799373
[I 2024-04-18 15:18:22,319] Trial 99 finished with value: 0.2203058420059226 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 479, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7748776458811619, 'min_weight_fraction_leaf': 0.01676397878674702}. Best is trial 67 with value: 0.2182330563172799.


* Best trial for IBS:
 FrozenTrial(number=67, state=TrialState.COMPLETE, values=[0.2182330563172799], datetime_start=datetime.datetime(2024, 4, 18, 15, 16, 0, 708169), datetime_complete=datetime.datetime(2024, 4, 18, 15, 16, 4, 578915), params={'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 322, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7501323059528776, 'min_weight_fraction_leaf': 0.21276472095633941}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=67, value=None)


* Best Score for IBS:
 0.2182330563172799

In [54]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [55]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.746
train_ibs:  0.218

#### Test

In [56]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [57]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=6, max_features=None, max_leaf_nodes=8,
                   max_samples=0.949451910660598, min_samples_leaf=4,
                   min_samples_split=15,
                   min_weight_fraction_leaf=0.030419386073469834,
                   n_estimators=377, random_state=123, warm_start=True)

C-index score: 0.6

ExtraSurvivalTrees(max_depth=8, max_features='log2', max_leaf_nodes=9,
                   max_samples=0.7501323059528776, min_samples_leaf=4,
                   min_weight_fraction_leaf=0.21276472095633941,
                   n_estimators=322, random_state=123, warm_start=True)

IBS: 0.213

In [58]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [59]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 15:18:24,809] A new study created in memory with name: no-name-d8d0d603-a840-43b7-8f40-738dc1e833dc

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:18:50,874] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:19:17,827] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:19:32,559] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:19:53,166] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:20:01,029] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:20:02,741] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:20:20,350] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:20:25,279] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:20:25,929] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.725531914893617
Fold 4 C-index: 0.6216730038022814
Fold 5 C-index: 0.6051502145922747
[I 2024-04-18 15:21:21,657] Trial 9 finished with value: 0.6257330792225687 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6257330792225687.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5
Fold 5 C-index: 0.592274678111588
[I 2024-04-18 15:23:02,387] Trial 10 finished with value: 0.5915509861883201 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6257330792225687.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:24:35,519] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6257330792225687.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.5950570342205324
Fold 5 C-index: 0.6158798283261803
[I 2024-04-18 15:25:56,159] Trial 12 finished with value: 0.606277093125476 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.6257330792225687.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:26:48,893] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.6257330792225687.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:27:36,095] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.6257330792225687.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:28:24,603] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.6257330792225687.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:28:54,474] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.6257330792225687.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:30:23,215] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.6257330792225687.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:32:08,583] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.6257330792225687.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:32:14,041] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6257330792225687.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:32:58,703] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.6257330792225687.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:35:08,616] Trial 21 finished with value: 0.5 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6257330792225687.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 15:37:10,968] Trial 22 finished with value: 0.6567802711331774 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:38:29,939] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:39:34,028] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

Fold 5 C-index: 0.5
[I 2024-04-18 15:40:00,241] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:41:08,144] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:42:17,492] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:43:25,843] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:44:14,505] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:45:31,034] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:47:22,044] Trial 31 finished with value: 0.5071713147410358 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:49:19,046] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:51:44,171] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:54:23,117] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:54:48,452] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:57:04,229] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:57:08,392] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.6567802711331774.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:58:06,632] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:59:56,116] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:02:51,415] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.592274678111588
[I 2024-04-18 16:02:51,973] Trial 41 finished with value: 0.6039152174760968 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 16:03:14,473] Trial 42 finished with value: 0.6470158275036256 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:03:17,205] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8735505723796891, 'learning_rate': 0.013455915558851193, 'dropout_rate': 0.11585930219083569, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 1.1546454041172216, 'min_weight_fraction_leaf': 0.4571018098895751, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8650432234384267, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:04:39,037] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9479336661285427, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.25335630680617827, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.4126953497238681, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.9438667820963776, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6453488372093024
Fold 3 C-index: 0.7510638297872341
Fold 4 C-index: 0.591254752851711
Fold 5 C-index: 0.575107296137339
[I 2024-04-18 16:04:57,544] Trial 45 finished with value: 0.630483230049707 and parameters: {'subsample': 0.5852424762732177, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.027804703729289008, 'min_weight_fraction_leaf': 0.262143273989599, 'max_features': 0.1, 'min_impurity_decrease': 9.467252666446998e-07, 'validation_fraction': 0.7243304021069044, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:05:02,188] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.0647255784094387, 'dropout_rate': 0.9694253886674298, 'n_estimators': 130, 'criterion': 'squared_error', 'ccp_alpha': 1.9903431110600875, 'min_weight_fraction_leaf': 0.2621149519999694, 'max_features': 0.1, 'min_impurity_decrease': 1.8213591543920705e-06, 'validation_fraction': 0.7149599360255287, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:05:28,133] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.45583884600027197, 'learning_rate': 0.06333641179361332, 'dropout_rate': 0.19790330487666663, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.14638041253524992, 'max_features': 0.1, 'min_impurity_decrease': 9.138461248752069e-07, 'validation_fraction': 0.6499098781754827, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:05:35,489] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.584713932884162, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.27951884808649285, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 1.4079486283020177, 'min_weight_fraction_leaf': 0.21342970007180673, 'max_features': 0.1, 'min_impurity_decrease': 2.4988708934303504e-06, 'validation_fraction': 0.5884862057231304, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:06:03,060] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.5312512417393443, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3775922041148432, 'min_weight_fraction_leaf': 0.2316969754016241, 'max_features': 'log2', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.8162506488425402, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 22 with value: 0.6567802711331774.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:06:19,195] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.052706271754983484, 'dropout_rate': 0.3787195779305788, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.077209816707269, 'min_weight_fraction_leaf': 0.31040829786124846, 'max_features': 0.1, 'min_impurity_decrease': 1.0106089337747014e-06, 'validation_fraction': 0.8835479481377899, 'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.5901287553648069
[I 2024-04-18 16:06:21,879] Trial 51 finished with value: 0.6433333125444612 and parameters: {'subsample': 0.9156545266266123, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.1404019935798118, 'n_estimators': 32, 'criterion': 'squared_error', 'ccp_alpha': 0.012243801070742757, 'min_weight_fraction_leaf': 0.377285576216956, 'max_features': 'sqrt', 'min_impurity_decrease': 2.1936100454733836e-07, 'validation_fraction': 0.855037228249073, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:06:25,878] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.7977865301378425, 'learning_rate': 0.07102079283153598, 'dropout_rate': 0.11294952687164567, 'n_estimators': 48, 'criterion': 'squared_error', 'ccp_alpha': 0.5430622755642927, 'min_weight_fraction_leaf': 0.36469952190521415, 'max_features': 'sqrt', 'min_impurity_decrease': 2.38579101418113e-07, 'validation_fraction': 0.7433547121677936, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.6567802711331774.
Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7978723404255319
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.5643776824034334
[I 2024-04-18 16:06:27,748] Trial 53 finished with value: 0.6628933010881953 and parameters: {'subsample': 0.7305170806182099, 'learning_rate': 0.05877903849297955, 'dropout_rate': 0.2158120114915196, 'n_estimators': 28, 'criterion': 'squared_error', 'ccp_alpha': 0.009781579144263263, 'min_weight_fraction_leaf': 0.33111548353893067, 'max_features': 'sqrt', 'min_impurity_decrease': 5.215208696037137e-07, 'validation_fraction': 0.8384582646351804, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:06:30,345] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.7318001610554563, 'learning_rate': 0.059834764453264265, 'dropout_rate': 0.22627998975411026, 'n_estimators': 34, 'criterion': 'squared_error', 'ccp_alpha': 1.6707664312736628, 'min_weight_fraction_leaf': 0.33394996198154614, 'max_features': 'sqrt', 'min_impurity_decrease': 2.245955307815471e-07, 'validation_fraction': 0.6843339575306756, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:06:36,597] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.6196699141179975, 'learning_rate': 0.04709963647359185, 'dropout_rate': 0.18274261049965285, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.40074886285106287, 'min_weight_fraction_leaf': 0.26615372199412923, 'max_features': 'sqrt', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8400930445837398, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:07:16,447] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.6763397575407665, 'learning_rate': 0.04145334122676535, 'dropout_rate': 0.13064667596279733, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 1.0261239696798017, 'min_weight_fraction_leaf': 0.2994820925344396, 'max_features': 'sqrt', 'min_impurity_decrease': 3.5012918843688916e-07, 'validation_fraction': 0.7796105590928633, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.5858369098712446
[I 2024-04-18 16:07:25,292] Trial 57 finished with value: 0.6463593087170008 and parameters: {'subsample': 0.5073324760285014, 'learning_rate': 0.05952554251828951, 'dropout_rate': 0.2654836627375681, 'n_estimators': 84, 'criterion': 'squared_error', 'ccp_alpha': 0.0019473494055538935, 'min_weight_fraction_leaf': 0.3388560781293413, 'max_features': 'sqrt', 'min_impurity_decrease': 5.608534822955176e-07, 'validation_fraction': 0.8254593382612642, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:07:36,930] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.48548339435100957, 'learning_rate': 0.05676463368504374, 'dropout_rate': 0.22541935640498023, 'n_estimators': 92, 'criterion': 'squared_error', 'ccp_alpha': 0.7470877807882045, 'min_weight_fraction_leaf': 0.37288789710000986, 'max_features': 'sqrt', 'min_impurity_decrease': 7.472674454205477e-07, 'validation_fraction': 0.8919967190005539, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:07:39,731] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.38439789354607845, 'learning_rate': 0.07051651042781107, 'dropout_rate': 0.15384466599852345, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 8.3580076573, 'min_weight_fraction_leaf': 0.3346841405410551, 'max_features': 'sqrt', 'min_impurity_decrease': 5.510646828280465e-07, 'validation_fraction': 0.8472906365905982, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:07:44,830] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.515111672082334, 'learning_rate': 0.049337793762293414, 'dropout_rate': 0.10027170450231424, 'n_estimators': 50, 'criterion': 'squared_error', 'ccp_alpha': 1.3119841524585854, 'min_weight_fraction_leaf': 0.41039796021220176, 'max_features': 'sqrt', 'min_impurity_decrease': 4.843478307909528e-06, 'validation_fraction': 0.8156959505174797, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:08:04,555] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.5854420924588365, 'learning_rate': 0.06060509917723852, 'dropout_rate': 0.1931168743317866, 'n_estimators': 97, 'criterion': 'squared_error', 'ccp_alpha': 0.3409580267399826, 'min_weight_fraction_leaf': 0.3409046773751395, 'max_features': 'sqrt', 'min_impurity_decrease': 1.7498299309748084e-07, 'validation_fraction': 0.7271755608042784, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 18}. Best is trial 53 with value: 0.6628933010881953.

Fold 1 C-index: 0.6155378486055777
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.5901287553648069
[I 2024-04-18 16:08:18,791] Trial 62 finished with value: 0.6424069188635239 and parameters: {'subsample': 0.44290548301326405, 'learning_rate': 0.06789146011220368, 'dropout_rate': 0.2749247707008632, 'n_estimators': 71, 'criterion': 'squared_error', 'ccp_alpha': 0.022616672247981386, 'min_weight_fraction_leaf': 0.3062226728120593, 'max_features': 'sqrt', 'min_impurity_decrease': 2.912632026661688e-07, 'validation_fraction': 0.6953024615902442, 'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5796812749003984
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.5815450643776824
[I 2024-04-18 16:08:44,078] Trial 63 finished with value: 0.6288672766868427 and parameters: {'subsample': 0.4184874537725248, 'learning_rate': 0.06801311498216697, 'dropout_rate': 0.2663787938573428, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 0.017289191017379774, 'min_weight_fraction_leaf': 0.38230472306828395, 'max_features': 'sqrt', 'min_impurity_decrease': 4.6281359281428735e-07, 'validation_fraction': 0.6923608583584608, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:08:52,457] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.5001898426754277, 'learning_rate': 0.06351690862369143, 'dropout_rate': 0.3202310976005634, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.34945909312765405, 'max_features': 'sqrt', 'min_impurity_decrease': 2.2785103316122237e-06, 'validation_fraction': 0.7799232691405718, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:08:57,662] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.36305517177190016, 'learning_rate': 0.08483859461035387, 'dropout_rate': 0.4323493915688078, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.3522642153414066, 'min_weight_fraction_leaf': 0.2805300869485019, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0427108595910258e-06, 'validation_fraction': 0.8906943279816728, 'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 20}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:08:59,284] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.33193068980985624, 'learning_rate': 0.07831921552372668, 'dropout_rate': 0.23314188732318072, 'n_estimators': 20, 'criterion': 'squared_error', 'ccp_alpha': 0.8895257611291668, 'min_weight_fraction_leaf': 0.30241657992833976, 'max_features': 'sqrt', 'min_impurity_decrease': 3.388691676477604e-07, 'validation_fraction': 0.8303743367744718, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:09:33,998] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.44026572125862806, 'learning_rate': 0.09201698812616743, 'dropout_rate': 0.20127636646999775, 'n_estimators': 165, 'criterion': 'squared_error', 'ccp_alpha': 0.29393333981111347, 'min_weight_fraction_leaf': 0.3217483036057763, 'max_features': None, 'min_impurity_decrease': 5.685253241181861e-07, 'validation_fraction': 0.7562797688791132, 'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 20}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:09:52,901] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.9033168367437221, 'learning_rate': 0.07383151588968451, 'dropout_rate': 0.16426696851201206, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 0.8385719579981664, 'min_weight_fraction_leaf': 0.45129500395728694, 'max_features': 1, 'min_impurity_decrease': 1.7426966555880043e-07, 'validation_fraction': 0.9061942397842376, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 18}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:10:18,268] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.5360295416604122, 'learning_rate': 0.05773952075160269, 'dropout_rate': 0.2647123387400674, 'n_estimators': 141, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7491404886634039, 'min_weight_fraction_leaf': 0.3728934316845417, 'max_features': 'sqrt', 'min_impurity_decrease': 1.2735383906868252e-06, 'validation_fraction': 0.8662473519732293, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 19}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5239043824701195
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5152091254752852
Fold 5 C-index: 0.5708154506437768
[I 2024-04-18 16:10:28,932] Trial 70 finished with value: 0.5811759616007326 and parameters: {'subsample': 0.78210799068914, 'learning_rate': 0.050642884595621745, 'dropout_rate': 0.3005367351686073, 'n_estimators': 88, 'criterion': 'squared_error', 'ccp_alpha': 0.010067956580931684, 'min_weight_fraction_leaf': 0.47297297256121384, 'max_features': 0.1, 'min_impurity_decrease': 2.924218316379527e-07, 'validation_fraction': 0.5990006072642565, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 14}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6829787234042554
Fold 4 C-index: 0.6406844106463878
Fold 5 C-index: 0.5579399141630901
[I 2024-04-18 16:10:45,198] Trial 71 finished with value: 0.6182582852967199 and parameters: {'subsample': 0.41815043382407524, 'learning_rate': 0.06701310566362872, 'dropout_rate': 0.25907190863852897, 'n_estimators': 112, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.3855933556612481, 'max_features': 'sqrt', 'min_impurity_decrease': 5.15155640878223e-07, 'validation_fraction': 0.6817272384530381, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:10:49,675] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.2542981956538244, 'learning_rate': 0.0678028723238307, 'dropout_rate': 0.35811138102077866, 'n_estimators': 58, 'criterion': 'squared_error', 'ccp_alpha': 0.3009734940358641, 'min_weight_fraction_leaf': 0.3809252535544685, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0402177319970213e-07, 'validation_fraction': 0.7030761926284793, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:10:57,204] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.44062988016762983, 'learning_rate': 0.07249664219937069, 'dropout_rate': 0.2820661962932272, 'n_estimators': 75, 'criterion': 'squared_error', 'ccp_alpha': 1.2618615048914792, 'min_weight_fraction_leaf': 0.4185147342679342, 'max_features': 'sqrt', 'min_impurity_decrease': 4.571877567924698e-07, 'validation_fraction': 0.7839428223142451, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 18}. Best is trial 53 with value: 0.6628933010881953.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:10:59,864] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.6505226780062375, 'learning_rate': 0.06170285651158168, 'dropout_rate': 0.13468368959893195, 'n_estimators': 34, 'criterion': 'squared_error', 'ccp_alpha': 2.223304520759608, 'min_weight_fraction_leaf': 0.3606542947715634, 'max_features': 'log2', 'min_impurity_decrease': 0.00020700246413734948, 'validation_fraction': 0.961974965744341, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 15}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.5815450643776824
[I 2024-04-18 16:11:15,198] Trial 75 finished with value: 0.6417450532314339 and parameters: {'subsample': 0.48141731201106763, 'learning_rate': 0.05498779577153248, 'dropout_rate': 0.21617828991833518, 'n_estimators': 107, 'criterion': 'squared_error', 'ccp_alpha': 0.008821026217081435, 'min_weight_fraction_leaf': 0.33060723195453456, 'max_features': 'sqrt', 'min_impurity_decrease': 1.6047458270784627e-06, 'validation_fraction': 0.809415403775678, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 20}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:11:15,983] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.46918756190743527, 'learning_rate': 0.0558935141377456, 'dropout_rate': 0.2163948160336765, 'n_estimators': 3, 'criterion': 'squared_error', 'ccp_alpha': 0.6753331414033272, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'sqrt', 'min_impurity_decrease': 1.7452506563877842e-06, 'validation_fraction': 0.8009317545961468, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:12:45,277] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.8421603089317946, 'learning_rate': 0.052198468606281634, 'dropout_rate': 0.17283928864419326, 'n_estimators': 273, 'criterion': 'squared_error', 'ccp_alpha': 0.3310343097412429, 'min_weight_fraction_leaf': 0.3283213459674796, 'max_features': 'sqrt', 'min_impurity_decrease': 1.537550292308847e-05, 'validation_fraction': 0.7499430430692478, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 19}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:13:09,169] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.5512277662903794, 'learning_rate': 0.07829540716686903, 'dropout_rate': 0.12480630225525567, 'n_estimators': 135, 'criterion': 'squared_error', 'ccp_alpha': 0.9893752659188716, 'min_weight_fraction_leaf': 0.3454993844155074, 'max_features': None, 'min_impurity_decrease': 1.8478417073647353e-07, 'validation_fraction': 0.8622907304925946, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:13:14,775] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.7095082441918694, 'learning_rate': 0.06523575139079239, 'dropout_rate': 0.8831816560103296, 'n_estimators': 104, 'criterion': 'squared_error', 'ccp_alpha': 0.559060211442491, 'min_weight_fraction_leaf': 0.31295711201233845, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9247223591961677, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:13:59,522] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.9314830554960072, 'learning_rate': 0.04227426762920904, 'dropout_rate': 0.684566586558272, 'n_estimators': 234, 'criterion': 'friedman_mse', 'ccp_alpha': 5.796978904591443, 'min_weight_fraction_leaf': 0.2747527170124504, 'max_features': 1, 'min_impurity_decrease': 7.310061167690763e-07, 'validation_fraction': 0.8254044367306117, 'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.5930232558139535
Fold 3 C-index: 0.6914893617021277
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.5622317596566524
[I 2024-04-18 16:14:44,597] Trial 81 finished with value: 0.6126433780325199 and parameters: {'subsample': 0.41593939298770427, 'learning_rate': 0.06853190536424945, 'dropout_rate': 0.32380628722047555, 'n_estimators': 164, 'criterion': 'squared_error', 'ccp_alpha': 0.025429683198128432, 'min_weight_fraction_leaf': 0.40354523568830447, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6387783037798784e-07, 'validation_fraction': 0.6770622148667619, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:14:55,224] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.49772396392056945, 'learning_rate': 0.05364300709406246, 'dropout_rate': 0.24256695972424472, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 0.24423439556641938, 'min_weight_fraction_leaf': 0.35361168404640414, 'max_features': 'sqrt', 'min_impurity_decrease': 4.3771631253899406e-07, 'validation_fraction': 0.5547516544290695, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 19}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:15:15,190] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.8865881877940764, 'learning_rate': 0.062055388948957485, 'dropout_rate': 0.20758613633595258, 'n_estimators': 125, 'criterion': 'squared_error', 'ccp_alpha': 0.7536678704746286, 'min_weight_fraction_leaf': 0.4390923035797472, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1606401191850459e-06, 'validation_fraction': 0.7290809331652955, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 18}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:15:18,516] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.3688613335305829, 'learning_rate': 0.05755976162305926, 'dropout_rate': 0.1793036142844516, 'n_estimators': 42, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.2926538668963413, 'max_features': 'sqrt', 'min_impurity_decrease': 1.3107508571467814e-07, 'validation_fraction': 0.618027593213997, 'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6051502145922747
[I 2024-04-18 16:15:20,189] Trial 85 finished with value: 0.6439960975732117 and parameters: {'subsample': 0.5718194253054419, 'learning_rate': 0.006388350247735505, 'dropout_rate': 0.2657316059631107, 'n_estimators': 24, 'criterion': 'squared_error', 'ccp_alpha': 0.011079581402843635, 'min_weight_fraction_leaf': 0.3793056654777442, 'max_features': 'sqrt', 'min_impurity_decrease': 3.1178899487080207e-06, 'validation_fraction': 0.9270932263104402, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 12}. Best is trial 53 with value: 0.6628933010881953.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:15:21,446] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.5972722867944386, 'learning_rate': 0.016585040528480463, 'dropout_rate': 0.1502720244156282, 'n_estimators': 17, 'criterion': 'squared_error', 'ccp_alpha': 0.2545736904364293, 'min_weight_fraction_leaf': 0.25056275264586786, 'max_features': 'log2', 'min_impurity_decrease': 3.0373401514275998e-06, 'validation_fraction': 0.9662873111713848, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:15:23,155] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.9602826608655313, 'learning_rate': 0.00589489476981797, 'dropout_rate': 0.23729504341518573, 'n_estimators': 24, 'criterion': 'squared_error', 'ccp_alpha': 0.589509436213437, 'min_weight_fraction_leaf': 0.3081975531716841, 'max_features': 'sqrt', 'min_impurity_decrease': 1.658609772420003e-06, 'validation_fraction': 0.9214621693429745, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 9}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:15:28,263] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.568104999288809, 'learning_rate': 0.010462607486803737, 'dropout_rate': 0.1763438438549606, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 1.3514751187507514, 'min_weight_fraction_leaf': 0.39494324091955935, 'max_features': 0.1, 'min_impurity_decrease': 6.599284807225922e-07, 'validation_fraction': 0.8789499281062639, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 7}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:15:29,652] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.5195764151381809, 'learning_rate': 0.006978828501220214, 'dropout_rate': 0.29460736159608514, 'n_estimators': 9, 'criterion': 'squared_error', 'ccp_alpha': 1.003427029356045, 'min_weight_fraction_leaf': 0.3188111812525572, 'max_features': 'sqrt', 'min_impurity_decrease': 9.111604953482023e-06, 'validation_fraction': 0.8014969995781313, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 11}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:15:34,098] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.7306151097727858, 'learning_rate': 0.021062786682506215, 'dropout_rate': 0.21352861854816949, 'n_estimators': 44, 'criterion': 'squared_error', 'ccp_alpha': 0.4622275726929073, 'min_weight_fraction_leaf': 0.34100487823395237, 'max_features': 'auto', 'min_impurity_decrease': 4.015920222763388e-06, 'validation_fraction': 0.9356975491815015, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 8}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5756972111553785
Fold 2 C-index: 0.563953488372093
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6030042918454935
[I 2024-04-18 16:15:49,871] Trial 91 finished with value: 0.6248969880812429 and parameters: {'subsample': 0.4785596130669323, 'learning_rate': 0.05942603206422252, 'dropout_rate': 0.2678537106682341, 'n_estimators': 106, 'criterion': 'squared_error', 'ccp_alpha': 0.037948504220536555, 'min_weight_fraction_leaf': 0.37734157847196353, 'max_features': 'sqrt', 'min_impurity_decrease': 2.921693084869851e-07, 'validation_fraction': 0.8454437705002774, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:15:59,070] Trial 92 finished with value: 0.5433274653324686 and parameters: {'subsample': 0.3330455991231642, 'learning_rate': 0.00867057775930988, 'dropout_rate': 0.2518210935894075, 'n_estimators': 70, 'criterion': 'squared_error', 'ccp_alpha': 0.19653285695487893, 'min_weight_fraction_leaf': 0.3631262930567506, 'max_features': 'sqrt', 'min_impurity_decrease': 5.367439447153962e-07, 'validation_fraction': 0.8968641739734867, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:16:40,286] Trial 93 finished with value: 0.5357446808510639 and parameters: {'subsample': 0.41089578955186357, 'learning_rate': 0.06564597900425295, 'dropout_rate': 0.31245121671227793, 'n_estimators': 186, 'criterion': 'squared_error', 'ccp_alpha': 0.20511132279062666, 'min_weight_fraction_leaf': 0.42307324359585885, 'max_features': 'sqrt', 'min_impurity_decrease': 9.638336281220888e-07, 'validation_fraction': 0.7690054087271422, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:16:50,724] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.4579890444469408, 'learning_rate': 0.05516493903283836, 'dropout_rate': 0.38141967355594375, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 0.5296713312706368, 'min_weight_fraction_leaf': 0.39901542922508865, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8817711015802655e-07, 'validation_fraction': 0.8011494490861214, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:17:17,993] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.43403127259437135, 'learning_rate': 0.0693717286077979, 'dropout_rate': 0.2729811398078729, 'n_estimators': 144, 'criterion': 'squared_error', 'ccp_alpha': 0.7777557952043127, 'min_weight_fraction_leaf': 0.33306796488095125, 'max_features': 'sqrt', 'min_impurity_decrease': 2.106337850292982e-06, 'validation_fraction': 0.8520314883957778, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6216730038022814
Fold 5 C-index: 0.592274678111588
[I 2024-04-18 16:17:21,146] Trial 96 finished with value: 0.634912648749405 and parameters: {'subsample': 0.5095341352345704, 'learning_rate': 0.012753363360499792, 'dropout_rate': 0.19158691760671076, 'n_estimators': 34, 'criterion': 'squared_error', 'ccp_alpha': 0.030410705364664944, 'min_weight_fraction_leaf': 0.4414769202250187, 'max_features': 'sqrt', 'min_impurity_decrease': 4.1927545208864417e-07, 'validation_fraction': 0.1680801488969631, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:17:24,472] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.5107366327732831, 'learning_rate': 0.023812569732190286, 'dropout_rate': 0.3420584442902486, 'n_estimators': 36, 'criterion': 'friedman_mse', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.48214426849329006, 'max_features': 0.1, 'min_impurity_decrease': 1.2789733336049512e-06, 'validation_fraction': 0.20636990782329961, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 14}. Best is trial 53 with value: 0.6628933010881953.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 16:17:27,159] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.6385887683523638, 'learning_rate': 0.012292049074487884, 'dropout_rate': 0.13385022246762845, 'n_estimators': 23, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.45241452129857374, 'max_features': 'auto', 'min_impurity_decrease': 3.566719884906998e-07, 'validation_fraction': 0.4045552816273396, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 53 with value: 0.6628933010881953.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-18 16:17:33,552] A new study created in memory with name: no-name-cb19a5e4-2ef6-4a9c-bf26-6308031371b4

Fold 5 C-index: 0.5
[I 2024-04-18 16:17:33,528] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.5527444339332354, 'learning_rate': 0.017877232319432945, 'dropout_rate': 0.10216550214025771, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.46362790070418536, 'min_weight_fraction_leaf': 0.43840629474088344, 'max_features': 'sqrt', 'min_impurity_decrease': 9.094689353932164e-07, 'validation_fraction': 0.1604355124738367, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 53 with value: 0.6628933010881953.


* Best trial for C-index:
 FrozenTrial(number=53, state=TrialState.COMPLETE, values=[0.6628933010881953], datetime_start=datetime.datetime(2024, 4, 18, 16, 6, 25, 883724), datetime_complete=datetime.datetime(2024, 4, 18, 16, 6, 27, 748197), params={'subsample': 0.7305170806182099, 'learning_rate': 0.05877903849297955, 'dropout_rate': 0.2158120114915196, 'n_estimators': 28, 'criterion': 'squared_error', 'ccp_alpha': 0.009781579144263263, 'min_weight_fraction_leaf': 0.33111548353893067, 'max_features': 'sqrt', 'min_impurity_decrease': 5.215208696037137e-07, 'validation_fraction': 0.8384582646351804, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 20}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=53, value=None)


* Best Score for C-index:
 0.6628933010881953

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:19:10,029] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:20:19,554] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:21:10,198] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 16:22:36,874] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:23:10,361] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:23:17,499] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:24:26,557] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:24:44,322] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:24:46,442] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.2468743712910688
Fold 2 IBS: 0.2317196463086139
Fold 3 IBS: 0.22855659334825087
Fold 4 IBS: 0.24179035697341097
Fold 5 IBS: 0.22902797154961482
[I 2024-04-18 16:27:55,885] Trial 9 finished with value: 0.2355937878941919 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2355937878941919.
Fold 1 IBS: 0.24711653291675975
Fold 2 IBS: 0.23202162954629
Fold 3 IBS: 0.2289556964425975
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293716647928885
[I 2024-04-18 16:33:29,458] Trial 10 finished with value: 0.23588805903156138 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2355937878941919.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 16:41:36,693] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2355937878941919.
Fold 1 IBS: 0.2471968746952769
Fold 2 IBS: 0.23199877150580914
Fold 3 IBS: 0.22891569844215137
Fold 4 IBS: 0.24195423740028718
Fold 5 IBS: 0.22934326468770277
[I 2024-04-18 16:49:22,629] Trial 12 finished with value: 0.23588176934624547 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2355937878941919.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:53:11,694] Trial 13 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2355937878941919.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 16:59:33,343] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2355937878941919.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 17:05:10,692] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.2355937878941919.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 17:08:51,257] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.2355937878941919.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 17:16:23,415] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.2355937878941919.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 17:26:57,573] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.2355937878941919.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 17:27:20,635] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2355937878941919.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 17:30:59,254] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.2355937878941919.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 17:38:49,033] Trial 21 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2355937878941919.
Fold 1 IBS: 0.24675710728069802
Fold 2 IBS: 0.2311845436565021

Fold 3 IBS: 0.2281691663158409
Fold 4 IBS: 0.24150261308436805
Fold 5 IBS: 0.22844204423296374
[I 2024-04-18 17:46:27,919] Trial 22 finished with value: 0.23521109491407458 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 17:52:24,996] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-18 17:57:38,835] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 18:01:03,792] Trial 25 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 18:08:07,911] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 18:15:24,452] Trial 27 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 18:21:09,256] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 18:25:07,374] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 18:29:55,533] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24723811107199292
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 18:39:02,755] Trial 31 finished with value: 0.23592604563741132 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 18:48:05,217] Trial 32 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 18:54:46,702] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 19:02:42,364] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 19:04:25,707] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 19:12:54,136] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 19:13:09,384] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 19:16:41,683] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 19:19:33,839] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 19:24:19,706] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.2472010209971281
Fold 2 IBS: 0.23197319933729893
Fold 3 IBS: 0.22887452934644678
Fold 4 IBS: 0.24191861956639799
Fold 5 IBS: 0.2293015642651888
[I 2024-04-18 19:24:20,487] Trial 41 finished with value: 0.23585378670249213 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23521109491407458.
Fold 1 IBS: 0.2459047520616606
Fold 2 IBS: 0.23020388607917422
Fold 3 IBS: 0.225854520422356
Fold 4 IBS: 0.24022980115273948
Fold 5 IBS: 0.22692490429984144
[I 2024-04-18 19:24:52,473] Trial 42 finished with value: 0.23382357280315436 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 42 with value: 0.23382357280315436.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 19:24:53,699] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8735505723796891, 'learning_rate': 0.013455915558851193, 'dropout_rate': 0.11585930219083569, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 1.1546454041172216, 'min_weight_fraction_leaf': 0.4571018098895751, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8650432234384267, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 42 with value: 0.23382357280315436.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 19:26:20,366] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9479336661285427, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.25335630680617827, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.4126953497238681, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.9438667820963776, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 42 with value: 0.23382357280315436.
Fold 1 IBS: 0.24547270538004826
Fold 2 IBS: 0.22973360080429686
Fold 3 IBS: 0.22526689281672038
Fold 4 IBS: 0.24053938814506792
Fold 5 IBS: 0.22738798252943648
[I 2024-04-18 19:26:54,274] Trial 45 finished with value: 0.23368011393511398 and parameters: {'subsample': 0.5852424762732177, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.027804703729289008, 'min_weight_fraction_leaf': 0.262143273989599, 'max_features': 0.1, 'min_impurity_decrease': 9.467252666446998e-07, 'validation_fraction': 0.7243304021069044, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 45 with value: 0.23368011393511398.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 19:27:02,568] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.0647255784094387, 'dropout_rate': 0.9694253886674298, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 1.980441868470768, 'min_weight_fraction_leaf': 0.3747732962598691, 'max_features': 0.1, 'min_impurity_decrease': 2.6164901943280044e-07, 'validation_fraction': 0.7149599360255287, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 45 with value: 0.23368011393511398.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:00:08,433] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.45583884600027197, 'learning_rate': 0.06333641179361332, 'dropout_rate': 0.19790330487666663, 'n_estimators': 172, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.3462595663974316, 'max_features': 0.1, 'min_impurity_decrease': 9.138461248752069e-07, 'validation_fraction': 0.6499098781754827, 'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 45 with value: 0.23368011393511398.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:32:47,572] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.584713932884162, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.10579627176846597, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 0.443834316760607, 'min_weight_fraction_leaf': 0.26066789839492466, 'max_features': 0.1, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.5884862057231304, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 45 with value: 0.23368011393511398.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 20:32:49,725] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5232490206634685, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 9, 'criterion': 'friedman_mse', 'ccp_alpha': 1.370081088125734, 'min_weight_fraction_leaf': 0.3097478284829108, 'max_features': 0.1, 'min_impurity_decrease': 2.368978679128857e-06, 'validation_fraction': 0.8421492954769574, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 45 with value: 0.23368011393511398.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 20:46:49,723] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.07076395585024155, 'dropout_rate': 0.14893065487391582, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 1.7468603849227415, 'min_weight_fraction_leaf': 0.4771102452497172, 'max_features': 'log2', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.6959936026682685, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 45 with value: 0.23368011393511398.
Fold 1 IBS: 0.24690843953494493
Fold 2 IBS: 0.23157597243494926
Fold 3 IBS: 0.22834563115508635
Fold 4 IBS: 0.24166310261080748
Fold 5 IBS: 0.229030990243366
[I 2024-04-18 20:47:25,830] Trial 51 finished with value: 0.2355048271958308 and parameters: {'subsample': 0.7946888792311653, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.2196446942108301, 'n_estimators': 129, 'criterion': 'squared_error', 'ccp_alpha': 0.012243801070742757, 'min_weight_fraction_leaf': 0.22002902120871776, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0321764873923598e-06, 'validation_fraction': 0.8872414026388215, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 45 with value: 0.23368011393511398.
Fold 1 IBS: 0.24620053664410949
Fold 2 IBS: 0.23102615696825635
Fold 3 IBS: 0.22743844141703545
Fold 4 IBS: 0.24131565465651125
Fold 5 IBS: 0.22837350904015727
[I 2024-04-18 20:47:54,867] Trial 52 finished with value: 0.23487085974521396 and parameters: {'subsample': 0.7293363088819711, 'learning_rate': 0.021613492744160495, 'dropout_rate': 0.21988140341808987, 'n_estimators': 109, 'criterion': 'squared_error', 'ccp_alpha': 0.03659945835027755, 'min_weight_fraction_leaf': 0.21454208459463384, 'max_features': 'sqrt', 'min_impurity_decrease': 4.968003047339178e-07, 'validation_fraction': 0.7452334109475507, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 45 with value: 0.23368011393511398.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:48:44,861] Trial 53 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7286313887376499, 'learning_rate': 0.057410108721501936, 'dropout_rate': 0.285096973056326, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.4512041233232864, 'min_weight_fraction_leaf': 0.2260580293041923, 'max_features': 'sqrt', 'min_impurity_decrease': 9.58735442301899e-07, 'validation_fraction': 0.810021403108459, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 45 with value: 0.23368011393511398.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:49:13,998] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6569229035185145, 'learning_rate': 0.04372807230380943, 'dropout_rate': 0.21137526606647042, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 1.035069386526868, 'min_weight_fraction_leaf': 0.15200254659099177, 'max_features': 'sqrt', 'min_impurity_decrease': 3.9827268139860795e-07, 'validation_fraction': 0.7420090012406269, 'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 45 with value: 0.23368011393511398.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:50:05,207] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.804828042321909, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.23926982708415356, 'n_estimators': 162, 'criterion': 'squared_error', 'ccp_alpha': 0.40074886285106287, 'min_weight_fraction_leaf': 0.2779066644542128, 'max_features': 'sqrt', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 45 with value: 0.23368011393511398.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:50:59,352] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6106355356441384, 'learning_rate': 0.0175381503002972, 'dropout_rate': 0.1840399348615831, 'n_estimators': 188, 'criterion': 'squared_error', 'ccp_alpha': 1.2616701535027603, 'min_weight_fraction_leaf': 0.21267322167989086, 'max_features': 'sqrt', 'min_impurity_decrease': 4.6036201699627165e-06, 'validation_fraction': 0.6710340937437342, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 45 with value: 0.23368011393511398.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:51:07,546] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7251306188899954, 'learning_rate': 0.031631325965124225, 'dropout_rate': 0.36858678707018233, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.8632300312068857, 'min_weight_fraction_leaf': 0.25226351016663784, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8530056448822852e-06, 'validation_fraction': 0.6117070368402964, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 20}. Best is trial 45 with value: 0.23368011393511398.
Fold 1 IBS: 0.24435719248762328
Fold 2 IBS: 0.2290557016045052
Fold 3 IBS: 0.22455381697850593
Fold 4 IBS: 0.2398964297207406
Fold 5 IBS: 0.225805329865206
[I 2024-04-18 20:51:36,846] Trial 58 finished with value: 0.23273369413131623 and parameters: {'subsample': 0.8372135933826973, 'learning_rate': 0.0933118263896949, 'dropout_rate': 0.2698372192490325, 'n_estimators': 138, 'criterion': 'squared_error', 'ccp_alpha': 0.03851666886580376, 'min_weight_fraction_leaf': 0.19014956845126402, 'max_features': 'sqrt', 'min_impurity_decrease': 5.557667048245938e-07, 'validation_fraction': 0.8240957175887902, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 58 with value: 0.23273369413131623.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:52:08,710] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7770131468684633, 'learning_rate': 0.09661144110789328, 'dropout_rate': 0.13071901615025144, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.8838088337816697, 'min_weight_fraction_leaf': 0.20200402270044698, 'max_features': 'sqrt', 'min_impurity_decrease': 2.1058318453300297e-05, 'validation_fraction': 0.7834472079756201, 'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 10}. Best is trial 58 with value: 0.23273369413131623.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:53:03,780] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8387622269560421, 'learning_rate': 0.09288013525153278, 'dropout_rate': 0.4315539960531031, 'n_estimators': 222, 'criterion': 'squared_error', 'ccp_alpha': 7.88888123252141, 'min_weight_fraction_leaf': 0.18715715168296215, 'max_features': 'sqrt', 'min_impurity_decrease': 5.658911777133895e-07, 'validation_fraction': 0.8258586719391796, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 58 with value: 0.23273369413131623.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:53:17,126] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8935334956662829, 'learning_rate': 0.08303647143365385, 'dropout_rate': 0.31926072944032013, 'n_estimators': 90, 'criterion': 'squared_error', 'ccp_alpha': 0.3409580267399826, 'min_weight_fraction_leaf': 0.13431472354808824, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1489427281229002e-06, 'validation_fraction': 0.7271755608042784, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 58 with value: 0.23273369413131623.
Fold 1 IBS: 0.24413249399988052
Fold 2 IBS: 0.22830607198400968
Fold 3 IBS: 0.2232727369456894
Fold 4 IBS: 0.23920395473634404
Fold 5 IBS: 0.22587816304485822
[I 2024-04-18 20:53:40,850] Trial 62 finished with value: 0.2321586841421564 and parameters: {'subsample': 0.8243414389621114, 'learning_rate': 0.09071124103540035, 'dropout_rate': 0.27251764057548483, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.022616672247981386, 'min_weight_fraction_leaf': 0.2309588671101351, 'max_features': 'sqrt', 'min_impurity_decrease': 2.89800118435477e-07, 'validation_fraction': 0.876556500915509, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 62 with value: 0.2321586841421564.
Fold 1 IBS: 0.2442494138178197
Fold 2 IBS: 0.227612258807393
Fold 3 IBS: 0.22260056212286702
Fold 4 IBS: 0.23883061592367216
Fold 5 IBS: 0.22584175053828046
[I 2024-04-18 20:54:02,437] Trial 63 finished with value: 0.23182692024200646 and parameters: {'subsample': 0.8336599603007587, 'learning_rate': 0.09031916747519456, 'dropout_rate': 0.2663787938573428, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 0.017289191017379774, 'min_weight_fraction_leaf': 0.1951981514595036, 'max_features': 'sqrt', 'min_impurity_decrease': 5.414928507269899e-07, 'validation_fraction': 0.8926228431876313, 'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:54:50,812] Trial 64 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8427195777663575, 'learning_rate': 0.08784542374582861, 'dropout_rate': 0.2603466948459836, 'n_estimators': 183, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.18631742994510192, 'max_features': 'sqrt', 'min_impurity_decrease': 2.8821254066618343e-07, 'validation_fraction': 0.8718245332193061, 'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:55:08,878] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9311291803826592, 'learning_rate': 0.09901078905928126, 'dropout_rate': 0.33807906387606884, 'n_estimators': 111, 'criterion': 'squared_error', 'ccp_alpha': 0.2833036261479952, 'min_weight_fraction_leaf': 0.15643365485923125, 'max_features': 'sqrt', 'min_impurity_decrease': 4.917940757661372e-07, 'validation_fraction': 0.7588166620798954, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:55:51,521] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9043457557527063, 'learning_rate': 0.08720647345857328, 'dropout_rate': 0.27193939046019544, 'n_estimators': 154, 'criterion': 'squared_error', 'ccp_alpha': 1.4111498627316026, 'min_weight_fraction_leaf': 0.23517339076530247, 'max_features': 'sqrt', 'min_impurity_decrease': 6.086951842225704e-07, 'validation_fraction': 0.9127218528145804, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:55:57,709] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8250695857763196, 'learning_rate': 0.0911086342832341, 'dropout_rate': 0.3723000690397865, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 2.319190851430798, 'min_weight_fraction_leaf': 0.10443241497369499, 'max_features': None, 'min_impurity_decrease': 2.261430377187218e-06, 'validation_fraction': 0.8216731421530759, 'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 20:58:11,266] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8643375099509361, 'learning_rate': 0.0792574273284101, 'dropout_rate': 0.17115105391870955, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.2964654702152873, 'min_weight_fraction_leaf': 0.2042624403156238, 'max_features': 1, 'min_impurity_decrease': 1.613957524750281e-07, 'validation_fraction': 0.8530531167865556, 'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 5}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 20:58:22,731] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7567410978430598, 'learning_rate': 0.049761024237604506, 'dropout_rate': 0.23019100638335152, 'n_estimators': 72, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7461388176327838, 'min_weight_fraction_leaf': 0.2677621074656332, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012116389221552239, 'validation_fraction': 0.7845892214091239, 'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24526210949130314
Fold 2 IBS: 0.22803696342201724
Fold 3 IBS: 0.2236661922824975
Fold 4 IBS: 0.23984304265037115
Fold 5 IBS: 0.22664488852004427
[I 2024-04-18 20:58:56,862] Trial 70 finished with value: 0.23269063927324668 and parameters: {'subsample': 0.7270958059780266, 'learning_rate': 0.09025955125786853, 'dropout_rate': 0.2983051130696582, 'n_estimators': 141, 'criterion': 'squared_error', 'ccp_alpha': 0.010268271623930566, 'min_weight_fraction_leaf': 0.17606622950083872, 'max_features': 0.1, 'min_impurity_decrease': 2.9199125301850487e-07, 'validation_fraction': 0.9704707284830002, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24555544280381003
Fold 2 IBS: 0.22962196916880484
Fold 3 IBS: 0.22498412561336031
Fold 4 IBS: 0.24043340247697495
Fold 5 IBS: 0.22693898618023614
[I 2024-04-18 20:59:27,338] Trial 71 finished with value: 0.23350678524863727 and parameters: {'subsample': 0.7304805982333465, 'learning_rate': 0.0892848077436604, 'dropout_rate': 0.30534098323418335, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.17968197273495315, 'max_features': 0.1, 'min_impurity_decrease': 3.204485364940275e-07, 'validation_fraction': 0.9097007997790482, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.2451600641687433
Fold 2 IBS: 0.22770586823148078
Fold 3 IBS: 0.22373738619745162
Fold 4 IBS: 0.23955957932901825
Fold 5 IBS: 0.22662577588064192
[I 2024-04-18 21:00:00,940] Trial 72 finished with value: 0.2325577347614672 and parameters: {'subsample': 0.7283770413521057, 'learning_rate': 0.08910556443694609, 'dropout_rate': 0.30374750627529123, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 0.004871280381427739, 'min_weight_fraction_leaf': 0.18085760075572085, 'max_features': 0.1, 'min_impurity_decrease': 2.066775254108449e-07, 'validation_fraction': 0.968044786321844, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:00:31,014] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6821762273698422, 'learning_rate': 0.09045775488747818, 'dropout_rate': 0.3019452359314178, 'n_estimators': 136, 'criterion': 'squared_error', 'ccp_alpha': 0.6105532472732402, 'min_weight_fraction_leaf': 0.17703318401139306, 'max_features': 0.1, 'min_impurity_decrease': 2.0200798514974308e-07, 'validation_fraction': 0.9701149300219802, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:01:02,018] Trial 74 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7101241528292079, 'learning_rate': 0.09937320265602623, 'dropout_rate': 0.3524831319725679, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 0.9837183244747926, 'min_weight_fraction_leaf': 0.1523796655343799, 'max_features': 0.1, 'min_impurity_decrease': 1.0461061192135599e-07, 'validation_fraction': 0.9135026133191511, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 8}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:01:42,103] Trial 75 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7910155215343213, 'learning_rate': 0.08588418227292206, 'dropout_rate': 0.39919431914091363, 'n_estimators': 174, 'criterion': 'squared_error', 'ccp_alpha': 0.4044325808748982, 'min_weight_fraction_leaf': 0.12844710013372065, 'max_features': 0.1, 'min_impurity_decrease': 2.4870550227046503e-07, 'validation_fraction': 0.963542393044741, 'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:02:39,535] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6388870613170881, 'learning_rate': 0.09471280191500378, 'dropout_rate': 0.26923993869351254, 'n_estimators': 199, 'criterion': 'squared_error', 'ccp_alpha': 0.30266244779681034, 'min_weight_fraction_leaf': 0.10381952675877999, 'max_features': 0.1, 'min_impurity_decrease': 1.4510472528097585e-06, 'validation_fraction': 0.8960664882855555, 'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 6}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:02:51,624] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7428517276581355, 'learning_rate': 0.07706989744762442, 'dropout_rate': 0.4476209058480567, 'n_estimators': 91, 'criterion': 'squared_error', 'ccp_alpha': 1.5888723787914292, 'min_weight_fraction_leaf': 0.16206442611838873, 'max_features': 0.1, 'min_impurity_decrease': 3.33671674086432e-07, 'validation_fraction': 0.9402673106586569, 'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 9}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:03:22,590] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7715268987373948, 'learning_rate': 0.08985503754923349, 'dropout_rate': 0.5106424386694343, 'n_estimators': 163, 'criterion': 'squared_error', 'ccp_alpha': 0.6998187558649429, 'min_weight_fraction_leaf': 0.1441624791990044, 'max_features': 0.1, 'min_impurity_decrease': 6.786191098123249e-07, 'validation_fraction': 0.867999843487921, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24718643853466915
Fold 2 IBS: 0.23202729565425148
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 21:03:31,020] Trial 79 finished with value: 0.23591319335321229 and parameters: {'subsample': 0.8256021281450457, 'learning_rate': 0.08314261144569621, 'dropout_rate': 0.8831816560103296, 'n_estimators': 120, 'criterion': 'squared_error', 'ccp_alpha': 0.00580501385319391, 'min_weight_fraction_leaf': 0.19542362826311155, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9982863294620272, 'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 7}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809254
[I 2024-04-18 21:03:48,066] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6683452738089981, 'learning_rate': 0.07289104058957506, 'dropout_rate': 0.684566586558272, 'n_estimators': 139, 'criterion': 'squared_error', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.17162624287712744, 'max_features': 0.1, 'min_impurity_decrease': 1.7025620478865608e-07, 'validation_fraction': 0.8367688563996566, 'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 9}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 21:04:05,818] Trial 81 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7212629717230318, 'learning_rate': 0.09648863423607545, 'dropout_rate': 0.32380628722047555, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.23038409491076217, 'min_weight_fraction_leaf': 0.2340042122326562, 'max_features': 0.1, 'min_impurity_decrease': 4.883007455581965e-07, 'validation_fraction': 0.9187926479398427, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 63 with value: 0.23182692024200646.
Fold 1 IBS: 0.24418640494705676
Fold 2 IBS: 0.22760678527391404
Fold 3 IBS: 0.2223760511259363
Fold 4 IBS: 0.23850028661999376
Fold 5 IBS: 0.2254762676960985
[I 2024-04-18 21:04:26,366] Trial 82 finished with value: 0.23162915913259985 and parameters: {'subsample': 0.7424094275541511, 'learning_rate': 0.09321912358204075, 'dropout_rate': 0.2934062535264489, 'n_estimators': 114, 'criterion': 'squared_error', 'ccp_alpha': 0.01778369806197142, 'min_weight_fraction_leaf': 0.21126686784700288, 'max_features': 'log2', 'min_impurity_decrease': 3.4224047595443053e-07, 'validation_fraction': 0.9694941758991367, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 82 with value: 0.23162915913259985.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-18 21:04:40,182] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6936370685985978, 'learning_rate': 0.07973196831123328, 'dropout_rate': 0.28615445184158467, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 1.129152915921092, 'min_weight_fraction_leaf': 0.18903520337674806, 'max_features': 'log2', 'min_impurity_decrease': 2.9795925135078545e-07, 'validation_fraction': 0.9720656242622133, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 82 with value: 0.23162915913259985.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:04:46,417] Trial 84 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7766180104167335, 'learning_rate': 0.09249006200550622, 'dropout_rate': 0.305574256636177, 'n_estimators': 53, 'criterion': 'squared_error', 'ccp_alpha': 0.6566133054967586, 'min_weight_fraction_leaf': 0.24759719188654067, 'max_features': 'log2', 'min_impurity_decrease': 1.3396039034492153e-07, 'validation_fraction': 0.892099453138701, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 82 with value: 0.23162915913259985.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.2289818680697771
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:05:25,122] Trial 85 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8541716599279708, 'learning_rate': 0.08839641653849994, 'dropout_rate': 0.24521378095924606, 'n_estimators': 156, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3309010043491877, 'min_weight_fraction_leaf': 0.17837522472890427, 'max_features': 'log2', 'min_impurity_decrease': 8.040870911608097e-07, 'validation_fraction': 0.9314770718841436, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 82 with value: 0.23162915913259985.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:05:40,251] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8087595997030689, 'learning_rate': 0.08488131639682682, 'dropout_rate': 0.3757108201252311, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 0.8619058019946999, 'min_weight_fraction_leaf': 0.034374369575269015, 'max_features': 'log2', 'min_impurity_decrease': 1.9734264215079192e-07, 'validation_fraction': 0.8644333526627775, 'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 82 with value: 0.23162915913259985.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:06:01,205] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7460732631507769, 'learning_rate': 0.09440704087578497, 'dropout_rate': 0.34429888870538994, 'n_estimators': 117, 'criterion': 'squared_error', 'ccp_alpha': 0.23605873926111243, 'min_weight_fraction_leaf': 0.20611127721053588, 'max_features': 0.1, 'min_impurity_decrease': 3.605164135559099e-07, 'validation_fraction': 0.9533190908371042, 'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 82 with value: 0.23162915913259985.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:06:45,768] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6413430388178152, 'learning_rate': 0.0973528090376961, 'dropout_rate': 0.26912242502602596, 'n_estimators': 174, 'criterion': 'squared_error', 'ccp_alpha': 0.5807061908097002, 'min_weight_fraction_leaf': 0.16723537370276506, 'max_features': 0.1, 'min_impurity_decrease': 1.190634063232502e-06, 'validation_fraction': 0.8005899065401637, 'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 82 with value: 0.23162915913259985.
Fold 1 IBS: 0.2433992658820838
Fold 2 IBS: 0.2267996492121836
Fold 3 IBS: 0.22140115508973934
Fold 4 IBS: 0.23912914067521288
Fold 5 IBS: 0.22390565225002362
[I 2024-04-18 21:07:22,324] Trial 89 finished with value: 0.23092697262184864 and parameters: {'subsample': 0.38730242337646104, 'learning_rate': 0.08109800836387941, 'dropout_rate': 0.18122999434960108, 'n_estimators': 146, 'criterion': 'squared_error', 'ccp_alpha': 0.018794864735403906, 'min_weight_fraction_leaf': 0.14130782512257434, 'max_features': None, 'min_impurity_decrease': 6.04312953486063e-07, 'validation_fraction': 0.9728621916133924, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 89 with value: 0.23092697262184864.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:08:36,923] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4301287904403204, 'learning_rate': 0.08064135841350613, 'dropout_rate': 0.18182381147209734, 'n_estimators': 216, 'criterion': 'squared_error', 'ccp_alpha': 5.797253839038365, 'min_weight_fraction_leaf': 0.11344111466651854, 'max_features': 1, 'min_impurity_decrease': 2.7530646126399795e-06, 'validation_fraction': 0.9992764821735842, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 89 with value: 0.23092697262184864.
Fold 1 IBS: 0.2423272622724235
Fold 2 IBS: 0.2254756617599079
Fold 3 IBS: 0.2200532597471123
Fold 4 IBS: 0.23872485905201588
Fold 5 IBS: 0.22247081295166632
[I 2024-04-18 21:09:14,186] Trial 91 finished with value: 0.2298103711566252 and parameters: {'subsample': 0.3646963250854607, 'learning_rate': 0.09255241886126767, 'dropout_rate': 0.12363276406693596, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 0.03832008885345805, 'min_weight_fraction_leaf': 0.14198218649980035, 'max_features': None, 'min_impurity_decrease': 6.12703415921239e-07, 'validation_fraction': 0.965806971606102, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 91 with value: 0.2298103711566252.
Fold 1 IBS: 0.24720356529080675
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:09:52,561] Trial 92 finished with value: 0.23591913648117407 and parameters: {'subsample': 0.37023851203307184, 'learning_rate': 0.08893737188983004, 'dropout_rate': 0.20172874940955723, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.25929761360970466, 'min_weight_fraction_leaf': 0.14091910204137698, 'max_features': None, 'min_impurity_decrease': 1.670575123081423e-06, 'validation_fraction': 0.9646916032715627, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 91 with value: 0.2298103711566252.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:10:27,747] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3393392217612321, 'learning_rate': 0.08484939828620154, 'dropout_rate': 0.1330785179258292, 'n_estimators': 141, 'criterion': 'squared_error', 'ccp_alpha': 0.5271800261864423, 'min_weight_fraction_leaf': 0.22342629975429745, 'max_features': None, 'min_impurity_decrease': 6.529634824832721e-07, 'validation_fraction': 0.9250469615937894, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 91 with value: 0.2298103711566252.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:10:46,864] Trial 94 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.30155497875372905, 'learning_rate': 0.09226836699183699, 'dropout_rate': 0.16486788507480765, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 4.0703783464897505, 'min_weight_fraction_leaf': 0.08717516087188838, 'max_features': None, 'min_impurity_decrease': 4.324897116213418e-07, 'validation_fraction': 0.902599975518271, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 91 with value: 0.2298103711566252.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:11:11,464] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.22711241501967083, 'learning_rate': 0.09399734029654892, 'dropout_rate': 0.23424050775181726, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.2155841604325495, 'min_weight_fraction_leaf': 0.1987273188587709, 'max_features': None, 'min_impurity_decrease': 0.0002775108319921543, 'validation_fraction': 0.9754822510610521, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 8}. Best is trial 91 with value: 0.2298103711566252.
Fold 1 IBS: 0.24720275004054537
Fold 2 IBS: 0.23200270748604027
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:11:50,868] Trial 96 finished with value: 0.23591153802074527 and parameters: {'subsample': 0.5095341352345704, 'learning_rate': 0.08725364328306122, 'dropout_rate': 0.3223450290700977, 'n_estimators': 169, 'criterion': 'squared_error', 'ccp_alpha': 0.1763548129966652, 'min_weight_fraction_leaf': 0.18056333859719206, 'max_features': None, 'min_impurity_decrease': 8.711621987475722e-07, 'validation_fraction': 0.9501887884981254, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 91 with value: 0.2298103711566252.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:12:39,486] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38054192896008343, 'learning_rate': 0.0907069703578099, 'dropout_rate': 0.29952255515083975, 'n_estimators': 185, 'criterion': 'squared_error', 'ccp_alpha': 0.8146747487056372, 'min_weight_fraction_leaf': 0.12179773041599615, 'max_features': None, 'min_impurity_decrease': 2.402128990085841e-07, 'validation_fraction': 0.8821221020751453, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 91 with value: 0.2298103711566252.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-18 21:13:37,940] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.46077614751832996, 'learning_rate': 0.09701740438937595, 'dropout_rate': 0.25455243694522434, 'n_estimators': 199, 'criterion': 'friedman_mse', 'ccp_alpha': 4.816291450322713, 'min_weight_fraction_leaf': 0.14615364156535707, 'max_features': None, 'min_impurity_decrease': 1.4006375376158358e-07, 'validation_fraction': 0.9833042102806464, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 6}. Best is trial 91 with value: 0.2298103711566252.
Fold 1 IBS: 0.2440724072945952
Fold 2 IBS: 0.22777645930988027
Fold 3 IBS: 0.22195355018009255

Fold 4 IBS: 0.23930587351662694
Fold 5 IBS: 0.22629676970219087
[I 2024-04-18 21:14:12,932] Trial 99 finished with value: 0.23188101200067718 and parameters: {'subsample': 0.40791967441342253, 'learning_rate': 0.07712333235501795, 'dropout_rate': 0.19859974199600133, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 0.004426170739568851, 'min_weight_fraction_leaf': 0.16314282359709542, 'max_features': 'log2', 'min_impurity_decrease': 5.353566353972388e-07, 'validation_fraction': 0.1604355124738367, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 91 with value: 0.2298103711566252.


* Best trial for IBS:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.2298103711566252], datetime_start=datetime.datetime(2024, 4, 18, 21, 8, 36, 933618), datetime_complete=datetime.datetime(2024, 4, 18, 21, 9, 14, 185559), params={'subsample': 0.3646963250854607, 'learning_rate': 0.09255241886126767, 'dropout_rate': 0.12363276406693596, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 0.03832008885345805, 'min_weight_fraction_leaf': 0.14198218649980035, 'max_features': None, 'min_impurity_decrease': 6.12703415921239e-07, 'validation_fraction': 0.965806971606102, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 4}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=91, value=None)


* Best Score for IBS:
 0.2298103711566252

In [60]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [61]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.663
train_ibs:  0.23

#### Test

In [62]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [63]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.009781579144263263,
                                 criterion='squared_error',
                                 dropout_rate=0.2158120114915196,
                                 learning_rate=0.05877903849297955,
                                 max_depth=20, max_features='sqrt',
                                 max_leaf_nodes=16,
                                 min_impurity_decrease=5.215208696037137e-07,
                                 min_samples_leaf=17, min_samples_split=17,
                                 min_weight_fraction_leaf=0.33111548353893067,
                                 n_estimators=28, random_state=123,
                                 subsample=0.7305170806182099,
                                 validation_fraction=0.8384582646351804)

C-index score: 0.622

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03832008885345805,
                                 criterion='squared_error',
                                 dropout_rate=0.12363276406693596,
                                 learning_rate=0.09255241886126767, max_depth=4,
                                 max_leaf_nodes=15,
                                 min_impurity_decrease=6.12703415921239e-07,
                                 min_samples_leaf=16, min_samples_split=13,
                                 min_weight_fraction_leaf=0.14198218649980035,
                                 n_estimators=143, random_state=123,
                                 subsample=0.3646963250854607,
                                 validation_fraction=0.965806971606102)

IBS: 0.221

In [64]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [65]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 21:14:21,150] A new study created in memory with name: no-name-a7d749c1-0c92-42f4-b129-f62146ad73ee

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:14:25,058] Trial 0 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:14:59,499] Trial 1 finished with value: 0.6202034782319725 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:15:06,926] Trial 2 finished with value: 0.6257455652032364 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:15:15,791] Trial 3 finished with value: 0.6185490505877318 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:15:29,096] Trial 4 finished with value: 0.6112085082564592 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:15:46,650] Trial 5 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:15:54,131] Trial 6 finished with value: 0.6202034782319725 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:15:55,625] Trial 7 finished with value: 0.6302727070202415 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:16:04,879] Trial 8 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:16:29,882] Trial 9 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:16:31,193] Trial 10 finished with value: 0.6138413578094634 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7165502912345604, 'n_estimators': 30, 'learning_rate': 0.0017980531969980576}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:16:47,366] Trial 11 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.7183546749251188, 'dropout_rate': 0.9718736866137505, 'n_estimators': 366, 'learning_rate': 0.09030046516637738}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:17:03,564] Trial 12 finished with value: 0.6070119888702704 and parameters: {'subsample': 0.9489391208353429, 'dropout_rate': 0.7771761699954475, 'n_estimators': 341, 'learning_rate': 0.09635955935176935}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:17:07,807] Trial 13 finished with value: 0.6309205129443722 and parameters: {'subsample': 0.659032396755593, 'dropout_rate': 0.21952474780075834, 'n_estimators': 109, 'learning_rate': 0.062325314922558224}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.5513307984790875
Fold 5 C-index: 0.6137339055793991
[I 2024-04-18 21:17:30,352] Trial 14 finished with value: 0.6168616791258004 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.34009363917849517, 'n_estimators': 363, 'learning_rate': 0.08149933787658604}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:17:33,990] Trial 15 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.6330374817454154, 'dropout_rate': 0.6228653975879225, 'n_estimators': 98, 'learning_rate': 0.03672044480839409}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:17:47,133] Trial 16 finished with value: 0.6070119888702704 and parameters: {'subsample': 0.8671553463800201, 'dropout_rate': 0.8450244458433167, 'n_estimators': 298, 'learning_rate': 0.05843666194696306}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:45:09,724] Trial 17 finished with value: 0.6202034782319725 and parameters: {'subsample': 0.8555980823022257, 'dropout_rate': 0.10343279737822575, 'n_estimators': 419, 'learning_rate': 0.02066217838758578}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:45:14,957] Trial 18 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.6278683610739599, 'dropout_rate': 0.3250809465499168, 'n_estimators': 118, 'learning_rate': 0.043144277652112456}. Best is trial 0 with value: 0.6325540758415343.

Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:45:31,022] Trial 19 finished with value: 0.6070119888702704 and parameters: {'subsample': 0.8350722272141606, 'dropout_rate': 0.5915597174096103, 'n_estimators': 299, 'learning_rate': 0.08697733590757546}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:46:00,654] Trial 20 finished with value: 0.6176146844708469 and parameters: {'subsample': 0.38161734041406226, 'dropout_rate': 0.7859448591953863, 'n_estimators': 408, 'learning_rate': 0.06348170552170027}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:46:19,715] Trial 21 finished with value: 0.6202034782319725 and parameters: {'subsample': 0.7327740419972562, 'dropout_rate': 0.9754161103921428, 'n_estimators': 382, 'learning_rate': 0.09060645610261484}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:46:37,703] Trial 22 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.614074566634308, 'dropout_rate': 0.9919342077975116, 'n_estimators': 334, 'learning_rate': 0.09960115837449297}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:47:02,565] Trial 23 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.7938640874322983, 'dropout_rate': 0.8928728763966429, 'n_estimators': 448, 'learning_rate': 0.08296216960279851}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:47:12,641] Trial 24 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.6960959679914406, 'dropout_rate': 0.9342982604461226, 'n_estimators': 252, 'learning_rate': 0.07423104209441139}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:47:30,014] Trial 25 finished with value: 0.6070119888702704 and parameters: {'subsample': 0.9161742397276466, 'dropout_rate': 0.8139553387854312, 'n_estimators': 286, 'learning_rate': 0.04499564959136668}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:47:49,421] Trial 26 finished with value: 0.6202034782319725 and parameters: {'subsample': 0.8011057787444668, 'dropout_rate': 0.7288366013952023, 'n_estimators': 325, 'learning_rate': 0.056622968241948714}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.592274678111588
[I 2024-04-18 21:47:50,113] Trial 27 finished with value: 0.5917883480838033 and parameters: {'subsample': 0.5786868436342061, 'dropout_rate': 0.8507339987761069, 'n_estimators': 1, 'learning_rate': 0.06450649236079735}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:48:01,793] Trial 28 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.6968612787224547, 'dropout_rate': 0.45930760333185244, 'n_estimators': 226, 'learning_rate': 0.07875451060836133}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:48:46,396] Trial 29 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.7443621528577677, 'dropout_rate': 0.528113503868086, 'n_estimators': 483, 'learning_rate': 0.0671437051756382}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6094420600858369
[I 2024-04-18 21:48:52,237] Trial 30 finished with value: 0.6179067130470883 and parameters: {'subsample': 0.4286525902513967, 'dropout_rate': 0.4003287988788521, 'n_estimators': 145, 'learning_rate': 0.09159118941184588}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:48:55,197] Trial 31 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.580266273279712, 'dropout_rate': 0.6126470208180593, 'n_estimators': 68, 'learning_rate': 0.03359972583177814}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:48:58,420] Trial 32 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.6511165263056896, 'dropout_rate': 0.6371413198960908, 'n_estimators': 87, 'learning_rate': 0.03472433825119976}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6008583690987125
[I 2024-04-18 21:49:02,976] Trial 33 finished with value: 0.621024535160318 and parameters: {'subsample': 0.5434708488432959, 'dropout_rate': 0.9413594559052736, 'n_estimators': 152, 'learning_rate': 0.013121224510458253}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:49:29,167] Trial 34 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.6937110834729925, 'dropout_rate': 0.5051054684842515, 'n_estimators': 394, 'learning_rate': 0.04049216942972346}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:49:55,850] Trial 35 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.7831737473691696, 'dropout_rate': 0.719937162920319, 'n_estimators': 434, 'learning_rate': 0.02811707529912722}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:50:03,438] Trial 36 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.6116946887762211, 'dropout_rate': 0.24408912236765595, 'n_estimators': 184, 'learning_rate': 0.07021273164335125}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:50:08,422] Trial 37 finished with value: 0.6257455652032364 and parameters: {'subsample': 0.5333277303408345, 'dropout_rate': 0.4217738975102757, 'n_estimators': 144, 'learning_rate': 0.0495373496433689}. Best is trial 0 with value: 0.6325540758415343.

Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:50:19,203] Trial 38 finished with value: 0.6070119888702704 and parameters: {'subsample': 0.8975124960092108, 'dropout_rate': 0.3454513035831812, 'n_estimators': 238, 'learning_rate': 0.050384430919465664}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:50:35,153] Trial 39 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.7415710071500535, 'dropout_rate': 0.8737909302085629, 'n_estimators': 357, 'learning_rate': 0.01715036845928685}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:50:37,158] Trial 40 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.4650174911826308, 'dropout_rate': 0.674714975151574, 'n_estimators': 55, 'learning_rate': 0.038425723625057744}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:50:41,402] Trial 41 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.6427223554233229, 'dropout_rate': 0.3148196375868446, 'n_estimators': 112, 'learning_rate': 0.0448815862007148}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:50:44,915] Trial 42 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.6873159527855055, 'dropout_rate': 0.26575019848008197, 'n_estimators': 113, 'learning_rate': 0.054798463027099974}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:50:45,953] Trial 43 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.5883178512692769, 'dropout_rate': 0.18169686917024963, 'n_estimators': 21, 'learning_rate': 0.027633234880330062}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:50:48,800] Trial 44 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.6363674494630207, 'dropout_rate': 0.3089648723925339, 'n_estimators': 89, 'learning_rate': 0.05954791205451325}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6137339055793991
[I 2024-04-18 21:50:56,178] Trial 45 finished with value: 0.6098346222272694 and parameters: {'subsample': 0.24265872160421625, 'dropout_rate': 0.5797329710353051, 'n_estimators': 192, 'learning_rate': 0.04136324743423657}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:51:00,800] Trial 46 finished with value: 0.6202034782319725 and parameters: {'subsample': 0.8243253194083316, 'dropout_rate': 0.3621784928717093, 'n_estimators': 128, 'learning_rate': 0.04763451436303346}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:51:03,360] Trial 47 finished with value: 0.6202034782319725 and parameters: {'subsample': 0.7705139729967041, 'dropout_rate': 0.43919468964115566, 'n_estimators': 75, 'learning_rate': 0.036942677895132066}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:51:04,637] Trial 48 finished with value: 0.6170637403119672 and parameters: {'subsample': 0.7242464074423646, 'dropout_rate': 0.9345590892238047, 'n_estimators': 36, 'learning_rate': 0.07413993460748093}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:51:10,178] Trial 49 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.6670806796685151, 'dropout_rate': 0.7615591362013137, 'n_estimators': 162, 'learning_rate': 0.029927806332180142}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:51:25,802] Trial 50 finished with value: 0.6248871961045239 and parameters: {'subsample': 0.513859571950082, 'dropout_rate': 0.14819890763032328, 'n_estimators': 278, 'learning_rate': 0.024647840655187776}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:51:54,139] Trial 51 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.7810658904829793, 'dropout_rate': 0.8712172334871933, 'n_estimators': 499, 'learning_rate': 0.08231205616604145}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:52:14,246] Trial 52 finished with value: 0.6202034782319725 and parameters: {'subsample': 0.720761810609788, 'dropout_rate': 0.9600633898082516, 'n_estimators': 425, 'learning_rate': 0.08785705885959356}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:52:36,584] Trial 53 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.8147785262415665, 'dropout_rate': 0.8947799323440281, 'n_estimators': 450, 'learning_rate': 0.052883670097135634}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:53:01,714] Trial 54 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.6174454213332293, 'dropout_rate': 0.832312827781733, 'n_estimators': 459, 'learning_rate': 0.09439488701396424}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:53:17,969] Trial 55 finished with value: 0.614616551607913 and parameters: {'subsample': 0.9830160676906303, 'dropout_rate': 0.9964839754742766, 'n_estimators': 375, 'learning_rate': 0.07804231421308218}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:53:37,964] Trial 56 finished with value: 0.6193625864798322 and parameters: {'subsample': 0.8521588139828619, 'dropout_rate': 0.8089689536098684, 'n_estimators': 397, 'learning_rate': 0.08479202142957024}. Best is trial 0 with value: 0.6325540758415343.

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:53:46,148] Trial 57 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.6727961695870968, 'dropout_rate': 0.9007493908859039, 'n_estimators': 215, 'learning_rate': 0.09963722720616296}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:54:03,450] Trial 58 finished with value: 0.6070119888702704 and parameters: {'subsample': 0.887299956828554, 'dropout_rate': 0.4755874956718547, 'n_estimators': 322, 'learning_rate': 0.06685832714451717}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:54:22,563] Trial 59 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.759183731911206, 'dropout_rate': 0.666857539645043, 'n_estimators': 349, 'learning_rate': 0.06087430164784785}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:54:39,391] Trial 60 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.5824539551117645, 'dropout_rate': 0.28096061710811554, 'n_estimators': 309, 'learning_rate': 0.07789150467655563}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:54:49,094] Trial 61 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.6828258922925482, 'dropout_rate': 0.9304799575179405, 'n_estimators': 262, 'learning_rate': 0.07262083665662476}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:54:58,197] Trial 62 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.7117099739062885, 'dropout_rate': 0.9570963623677565, 'n_estimators': 250, 'learning_rate': 0.08946618855252851}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:55:02,545] Trial 63 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.6267873753832041, 'dropout_rate': 0.8721216565187382, 'n_estimators': 131, 'learning_rate': 0.08199511995488454}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:55:05,428] Trial 64 finished with value: 0.6070119888702704 and parameters: {'subsample': 0.7849272411725753, 'dropout_rate': 0.9063585019719528, 'n_estimators': 95, 'learning_rate': 0.09379650501649425}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:55:14,244] Trial 65 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.5594387676592479, 'dropout_rate': 0.7663092025966229, 'n_estimators': 204, 'learning_rate': 0.07065057983222264}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:55:43,811] Trial 66 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.7118390326725491, 'dropout_rate': 0.389185593711486, 'n_estimators': 443, 'learning_rate': 0.0561115698647687}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:56:06,753] Trial 67 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.6620079461172257, 'dropout_rate': 0.9805787885243744, 'n_estimators': 471, 'learning_rate': 0.07574079045711918}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:56:23,281] Trial 68 finished with value: 0.6202034782319725 and parameters: {'subsample': 0.7410211707369196, 'dropout_rate': 0.9213220449992626, 'n_estimators': 371, 'learning_rate': 0.08467216345398305}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:56:29,612] Trial 69 finished with value: 0.61934510913326 and parameters: {'subsample': 0.8095767509901757, 'dropout_rate': 0.2125159172893392, 'n_estimators': 165, 'learning_rate': 0.06462152793264428}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:56:53,715] Trial 70 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.5586809921637486, 'dropout_rate': 0.5591054913245401, 'n_estimators': 408, 'learning_rate': 0.046622561588075984}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:56:55,748] Trial 71 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.6050487354893893, 'dropout_rate': 0.6155956933016893, 'n_estimators': 61, 'learning_rate': 0.0335458241132663}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:56:58,197] Trial 72 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.6460666568344867, 'dropout_rate': 0.6134779412492984, 'n_estimators': 66, 'learning_rate': 0.0408203129875815}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:57:01,299] Trial 73 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.4996489349127869, 'dropout_rate': 0.522228201630752, 'n_estimators': 100, 'learning_rate': 0.03672086700252718}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:57:05,624] Trial 74 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.5927255091424596, 'dropout_rate': 0.6924983012373931, 'n_estimators': 126, 'learning_rate': 0.04269863977375299}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:57:06,589] Trial 75 finished with value: 0.61934510913326 and parameters: {'subsample': 0.6978839887074411, 'dropout_rate': 0.8417765612548795, 'n_estimators': 16, 'learning_rate': 0.05380583064069127}. Best is trial 0 with value: 0.6325540758415343.

Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:57:08,287] Trial 76 finished with value: 0.6070119888702704 and parameters: {'subsample': 0.7607652101288103, 'dropout_rate': 0.7968814423811806, 'n_estimators': 46, 'learning_rate': 0.032744571647769144}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:57:11,042] Trial 77 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.45325869836184063, 'dropout_rate': 0.5002761437479046, 'n_estimators': 78, 'learning_rate': 0.0489201711994432}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:57:24,956] Trial 78 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.6460189001591354, 'dropout_rate': 0.9649150077778508, 'n_estimators': 337, 'learning_rate': 0.05823975157108323}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:57:28,897] Trial 79 finished with value: 0.6070119888702704 and parameters: {'subsample': 0.8443592972870718, 'dropout_rate': 0.7336388808725327, 'n_estimators': 121, 'learning_rate': 0.021847064249626545}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6201550387596899
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6137339055793991
[I 2024-04-18 21:57:33,914] Trial 80 finished with value: 0.6268411612983288 and parameters: {'subsample': 0.29509125144368054, 'dropout_rate': 0.6465587438795419, 'n_estimators': 140, 'learning_rate': 0.007039353779474462}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:57:36,500] Trial 81 finished with value: 0.6202034782319725 and parameters: {'subsample': 0.6642199031692865, 'dropout_rate': 0.5486797690512744, 'n_estimators': 78, 'learning_rate': 0.034793261594925}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:57:39,259] Trial 82 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.6289569098448298, 'dropout_rate': 0.608111837121786, 'n_estimators': 86, 'learning_rate': 0.030074952609499227}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:57:41,126] Trial 83 finished with value: 0.6202034782319725 and parameters: {'subsample': 0.6980309553644344, 'dropout_rate': 0.6421886730626755, 'n_estimators': 52, 'learning_rate': 0.03911324329108544}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:57:55,077] Trial 84 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.5682351503951868, 'dropout_rate': 0.7012896958141056, 'n_estimators': 295, 'learning_rate': 0.05193851257006166}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:57:58,965] Trial 85 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.5302119353473397, 'dropout_rate': 0.5688734185893739, 'n_estimators': 108, 'learning_rate': 0.03598165933013287}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:58:04,921] Trial 86 finished with value: 0.61934510913326 and parameters: {'subsample': 0.7312680469994587, 'dropout_rate': 0.7486393748914555, 'n_estimators': 175, 'learning_rate': 0.03893454162838445}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:58:06,086] Trial 87 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.6064438201021574, 'dropout_rate': 0.6368589729521499, 'n_estimators': 34, 'learning_rate': 0.043572565469196}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:58:11,959] Trial 88 finished with value: 0.6202034782319725 and parameters: {'subsample': 0.7896992411504821, 'dropout_rate': 0.3598759763655745, 'n_estimators': 155, 'learning_rate': 0.04647359430999269}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.5437262357414449
Fold 5 C-index: 0.6137339055793991
[I 2024-04-18 21:58:15,497] Trial 89 finished with value: 0.6145871917303765 and parameters: {'subsample': 0.13360665877080907, 'dropout_rate': 0.41019351438803264, 'n_estimators': 98, 'learning_rate': 0.025056796383218}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:58:28,157] Trial 90 finished with value: 0.61934510913326 and parameters: {'subsample': 0.7583749668266218, 'dropout_rate': 0.5881311216945275, 'n_estimators': 275, 'learning_rate': 0.030644450527956613}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:58:46,444] Trial 91 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.6744594921141702, 'dropout_rate': 0.8848847939946487, 'n_estimators': 388, 'learning_rate': 0.028997583607680788}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:59:11,516] Trial 92 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.707388038814098, 'dropout_rate': 0.6669864737778968, 'n_estimators': 432, 'learning_rate': 0.025248738935163963}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 21:59:37,406] Trial 93 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.7487607284228921, 'dropout_rate': 0.8601859095766408, 'n_estimators': 479, 'learning_rate': 0.019127674637257917}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 21:59:58,823] Trial 94 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.6449975300014051, 'dropout_rate': 0.82256435337291, 'n_estimators': 410, 'learning_rate': 0.08598974693815319}. Best is trial 0 with value: 0.6325540758415343.

Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 22:00:31,324] Trial 95 finished with value: 0.6202034782319725 and parameters: {'subsample': 0.724307842449545, 'dropout_rate': 0.304219832467762, 'n_estimators': 461, 'learning_rate': 0.026942112246182287}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 22:00:52,663] Trial 96 finished with value: 0.6325540758415343 and parameters: {'subsample': 0.8068351398456263, 'dropout_rate': 0.9155244695338658, 'n_estimators': 434, 'learning_rate': 0.08969168561119645}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6201716738197425
[I 2024-04-18 22:01:05,486] Trial 97 finished with value: 0.6316957067428218 and parameters: {'subsample': 0.6814967874839144, 'dropout_rate': 0.9336785403894107, 'n_estimators': 320, 'learning_rate': 0.032044042363125025}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 22:01:07,718] Trial 98 finished with value: 0.6202034782319725 and parameters: {'subsample': 0.7755502584585527, 'dropout_rate': 0.9482179959824033, 'n_estimators': 71, 'learning_rate': 0.09630535180671035}. Best is trial 0 with value: 0.6325540758415343.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5855513307984791

[I 2024-04-18 22:01:26,252] A new study created in memory with name: no-name-6efd89c4-d42d-49e8-ba01-217e23d8cd2a

Fold 5 C-index: 0.6244635193133047
[I 2024-04-18 22:01:26,240] Trial 99 finished with value: 0.6070119888702704 and parameters: {'subsample': 0.8317580400224254, 'dropout_rate': 0.6865858048512669, 'n_estimators': 360, 'learning_rate': 0.07949109819820412}. Best is trial 0 with value: 0.6325540758415343.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6325540758415343], datetime_start=datetime.datetime(2024, 4, 18, 21, 14, 21, 476391), datetime_complete=datetime.datetime(2024, 4, 18, 21, 14, 25, 58346), params={'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=0, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}


* Best Score for C-index:
 0.6325540758415343

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.27853337116308474
Fold 2 IBS: 0.2215528390328831
Fold 3 IBS: 0.20264770448336145
Fold 4 IBS: 0.2855088049869348
Fold 5 IBS: 0.2014656244155287
[I 2024-04-18 22:01:30,380] Trial 0 finished with value: 0.23794166881635853 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.23794166881635853.
Fold 1 IBS: 0.33825562269814186
Fold 2 IBS: 0.3039651241989302
Fold 3 IBS: 0.247828008187909
Fold 4 IBS: 0.4197515044438842
Fold 5 IBS: 0.23687849009592335
[I 2024-04-18 22:02:03,818] Trial 1 finished with value: 0.3093357499249577 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.23794166881635853.
Fold 1 IBS: 0.31729524653983654
Fold 2 IBS: 0.25679934623148076
Fold 3 IBS: 0.21659317755039947
Fold 4 IBS: 0.32675065409162607
Fold 5 IBS: 0.2099029681715522
[I 2024-04-18 22:02:10,054] Trial 2 finished with value: 0.265468278516979 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.23794166881635853.
Fold 1 IBS: 0.31549447805172687
Fold 2 IBS: 0.2622578238933627
Fold 3 IBS: 0.2167085621169721
Fold 4 IBS: 0.34458962867519843
Fold 5 IBS: 0.21433074681844114
[I 2024-04-18 22:02:18,998] Trial 3 finished with value: 0.2706762479111403 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.23794166881635853.
Fold 1 IBS: 0.3083482310245739
Fold 2 IBS: 0.2672028504482871
Fold 3 IBS: 0.20516924299197273
Fold 4 IBS: 0.3430602342154467
Fold 5 IBS: 0.2140907916105465
[I 2024-04-18 22:02:32,790] Trial 4 finished with value: 0.2675742700581654 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.23794166881635853.
Fold 1 IBS: 0.3355094998824222
Fold 2 IBS: 0.2898350421535593
Fold 3 IBS: 0.2423047753821743
Fold 4 IBS: 0.3800610939334704
Fold 5 IBS: 0.22731959827140763
[I 2024-04-18 22:02:49,007] Trial 5 finished with value: 0.29500600192460674 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.23794166881635853.
Fold 1 IBS: 0.2589955150907868
Fold 2 IBS: 0.21694712185454476
Fold 3 IBS: 0.20422787214805443
Fold 4 IBS: 0.2748113647251492
Fold 5 IBS: 0.204476606270151
[I 2024-04-18 22:02:56,098] Trial 6 finished with value: 0.23189169601773724 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.23189169601773724.
Fold 1 IBS: 0.24305483310248377
Fold 2 IBS: 0.2201567462995922
Fold 3 IBS: 0.20894341841112754
Fold 4 IBS: 0.2616159683848332
Fold 5 IBS: 0.21300960396571256
[I 2024-04-18 22:02:58,038] Trial 7 finished with value: 0.22935611403274986 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.22935611403274986.
Fold 1 IBS: 0.2787001791803599
Fold 2 IBS: 0.22527176931331588
Fold 3 IBS: 0.19879747309169105
Fold 4 IBS: 0.2883184755461564
Fold 5 IBS: 0.20126002601313872
[I 2024-04-18 22:03:07,059] Trial 8 finished with value: 0.23846958462893236 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.22935611403274986.
Fold 1 IBS: 0.32914141418178805
Fold 2 IBS: 0.29558947981965256
Fold 3 IBS: 0.23463019397963733
Fold 4 IBS: 0.4080366677435281
Fold 5 IBS: 0.2300122803429938
[I 2024-04-18 22:03:32,540] Trial 9 finished with value: 0.29948200721352 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.22935611403274986.
Fold 1 IBS: 0.2470353461515696
Fold 2 IBS: 0.23166509292012982
Fold 3 IBS: 0.22856182093970995
Fold 4 IBS: 0.24171407848753257
Fold 5 IBS: 0.22900918733397618
[I 2024-04-18 22:03:33,797] Trial 10 finished with value: 0.23559710516658364 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.22935611403274986.
Fold 1 IBS: 0.24687652993070414
Fold 2 IBS: 0.2311581012236425
Fold 3 IBS: 0.22803828196828552
Fold 4 IBS: 0.24151517366938874
Fold 5 IBS: 0.2286469874829567
[I 2024-04-18 22:03:34,587] Trial 11 finished with value: 0.23524701485499552 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.22935611403274986.
Fold 1 IBS: 0.29192782733146305
Fold 2 IBS: 0.24222065134800022
Fold 3 IBS: 0.19719551468337257
Fold 4 IBS: 0.30466346130184596
Fold 5 IBS: 0.20521680826259875
[I 2024-04-18 22:03:38,093] Trial 12 finished with value: 0.2482448525854561 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.22935611403274986.
Fold 1 IBS: 0.3066842143220508
Fold 2 IBS: 0.23401842282267074
Fold 3 IBS: 0.21233569023363008
Fold 4 IBS: 0.2915675582617538
Fold 5 IBS: 0.2038355228515873
[I 2024-04-18 22:03:53,556] Trial 13 finished with value: 0.24968828169833857 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.22935611403274986.
Fold 1 IBS: 0.24404114599530402
Fold 2 IBS: 0.22295870184744684
Fold 3 IBS: 0.2176668436693881
Fold 4 IBS: 0.24225761218981262
Fold 5 IBS: 0.21872786454713966
[I 2024-04-18 22:03:56,781] Trial 14 finished with value: 0.22913043364981825 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 14 with value: 0.22913043364981825.
Fold 1 IBS: 0.24569395723877502
Fold 2 IBS: 0.2300044855398841
Fold 3 IBS: 0.22603072882590156
Fold 4 IBS: 0.24340496070599763
Fold 5 IBS: 0.22673412001369328
[I 2024-04-18 22:03:59,348] Trial 15 finished with value: 0.2343736504648503 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 14 with value: 0.22913043364981825.
Fold 1 IBS: 0.24452125634882574
Fold 2 IBS: 0.22647571719832163
Fold 3 IBS: 0.2216511785523226
Fold 4 IBS: 0.2433884560591167
Fold 5 IBS: 0.2227044902566384
[I 2024-04-18 22:04:01,416] Trial 16 finished with value: 0.23174821968304501 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 14 with value: 0.22913043364981825.
Fold 1 IBS: 0.26424191505267974
Fold 2 IBS: 0.2173956523004484
Fold 3 IBS: 0.20424690516405927
Fold 4 IBS: 0.2629178340421786
Fold 5 IBS: 0.2029547490716599
[I 2024-04-18 22:04:05,756] Trial 17 finished with value: 0.2303514111262052 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 14 with value: 0.22913043364981825.
Fold 1 IBS: 0.25907301019719814
Fold 2 IBS: 0.21991873366286943
Fold 3 IBS: 0.19632464811133785
Fold 4 IBS: 0.28345520018551573
Fold 5 IBS: 0.20214301519041195
[I 2024-04-18 22:04:21,473] Trial 18 finished with value: 0.23218292146946662 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 14 with value: 0.22913043364981825.
Fold 1 IBS: 0.23855527403970428

Fold 2 IBS: 0.22156847431530372
Fold 3 IBS: 0.2084967358185174
Fold 4 IBS: 0.26598308545567084
Fold 5 IBS: 0.21358819750439922
[I 2024-04-18 22:04:23,324] Trial 19 finished with value: 0.2296383534267191 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 14 with value: 0.22913043364981825.
Fold 1 IBS: 0.24663727529252127
Fold 2 IBS: 0.21835663565155092
Fold 3 IBS: 0.2105256665576795
Fold 4 IBS: 0.24932331942924524
Fold 5 IBS: 0.21172241066007214
[I 2024-04-18 22:04:28,721] Trial 20 finished with value: 0.22731306151821382 and parameters: {'subsample': 0.8452240769714876, 'dropout_rate': 0.5558690358940764, 'n_estimators': 145, 'learning_rate': 0.017331004877487094}. Best is trial 20 with value: 0.22731306151821382.
Fold 1 IBS: 0.24576238490185268
Fold 2 IBS: 0.2188752760756841
Fold 3 IBS: 0.2117843863259187
Fold 4 IBS: 0.24706679820559785
Fold 5 IBS: 0.21313004630122903
[I 2024-04-18 22:04:33,961] Trial 21 finished with value: 0.22732377836205647 and parameters: {'subsample': 0.8572910585971787, 'dropout_rate': 0.5537934605115938, 'n_estimators': 146, 'learning_rate': 0.0155893359355838}. Best is trial 20 with value: 0.22731306151821382.
Fold 1 IBS: 0.24567450429264062
Fold 2 IBS: 0.2189617605996896
Fold 3 IBS: 0.21192117627499746
Fold 4 IBS: 0.24691499805757972
Fold 5 IBS: 0.213274853054251
[I 2024-04-18 22:04:39,163] Trial 22 finished with value: 0.22734945845583168 and parameters: {'subsample': 0.8615610863035676, 'dropout_rate': 0.5405657270190689, 'n_estimators': 146, 'learning_rate': 0.01541472996835073}. Best is trial 20 with value: 0.22731306151821382.
Fold 1 IBS: 0.24867241719245753
Fold 2 IBS: 0.2173626250085641
Fold 3 IBS: 0.20869967601366093
Fold 4 IBS: 0.2505871233406045
Fold 5 IBS: 0.20962772222580534
[I 2024-04-18 22:04:44,432] Trial 23 finished with value: 0.2269899127562185 and parameters: {'subsample': 0.8444366429088075, 'dropout_rate': 0.5654087459950417, 'n_estimators': 138, 'learning_rate': 0.021235376868914902}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.26799492093726646
Fold 2 IBS: 0.21860751975912418
Fold 3 IBS: 0.20414069442989963
Fold 4 IBS: 0.27607442640617696
Fold 5 IBS: 0.2023622997338595
[I 2024-04-18 22:04:53,778] Trial 24 finished with value: 0.23383597225326533 and parameters: {'subsample': 0.7985311218866021, 'dropout_rate': 0.5020521283337119, 'n_estimators': 224, 'learning_rate': 0.023613636689755815}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.24390728071258555
Fold 2 IBS: 0.22338988740199067
Fold 3 IBS: 0.21666002174319576
Fold 4 IBS: 0.25077883106220006
Fold 5 IBS: 0.2185056013474834
[I 2024-04-18 22:05:00,206] Trial 25 finished with value: 0.23064832445349107 and parameters: {'subsample': 0.6175484308420414, 'dropout_rate': 0.3125521697439868, 'n_estimators': 161, 'learning_rate': 0.008500348756543277}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.26878374377871533
Fold 2 IBS: 0.21760549372072943
Fold 3 IBS: 0.20413436502726134
Fold 4 IBS: 0.25429704993003077
Fold 5 IBS: 0.20261880386590284
[I 2024-04-18 22:05:11,360] Trial 26 finished with value: 0.22948789126452795 and parameters: {'subsample': 0.9255386028520951, 'dropout_rate': 0.5707562654379044, 'n_estimators': 256, 'learning_rate': 0.020984269103225307}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.2620643186826602
Fold 2 IBS: 0.21716978367607592
Fold 3 IBS: 0.2042378467227478
Fold 4 IBS: 0.2662274851601803
Fold 5 IBS: 0.20378627622077283
[I 2024-04-18 22:05:16,609] Trial 27 finished with value: 0.23069714209248743 and parameters: {'subsample': 0.8120565522935725, 'dropout_rate': 0.47110591236422056, 'n_estimators': 136, 'learning_rate': 0.03365612210209748}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.24599029224297014
Fold 2 IBS: 0.22979754483438405
Fold 3 IBS: 0.22633024334899435
Fold 4 IBS: 0.2406078726280722
Fold 5 IBS: 0.22696260776096458
[I 2024-04-18 22:05:27,880] Trial 28 finished with value: 0.23393771216307707 and parameters: {'subsample': 0.9250918854538261, 'dropout_rate': 0.18804677832052086, 'n_estimators': 226, 'learning_rate': 0.00124521835325761}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.2439924335187286
Fold 2 IBS: 0.22463077328200726
Fold 3 IBS: 0.2186912544487747
Fold 4 IBS: 0.2471452918448514
Fold 5 IBS: 0.22005138388086676
[I 2024-04-18 22:05:31,697] Trial 29 finished with value: 0.23090222739504576 and parameters: {'subsample': 0.7025722077826774, 'dropout_rate': 0.4175950896276197, 'n_estimators': 108, 'learning_rate': 0.010438890767613025}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.32551350407321283
Fold 2 IBS: 0.25271780050350673
Fold 3 IBS: 0.22532362151828703
Fold 4 IBS: 0.30899883985910165
Fold 5 IBS: 0.21116740562655165
[I 2024-04-18 22:05:47,494] Trial 30 finished with value: 0.264744234316132 and parameters: {'subsample': 0.9885210981191594, 'dropout_rate': 0.3183736233152148, 'n_estimators': 293, 'learning_rate': 0.0454248710019839}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.2502254652643324
Fold 2 IBS: 0.21688366159619504
Fold 3 IBS: 0.20759102734716708
Fold 4 IBS: 0.25349489919738544
Fold 5 IBS: 0.20839302866496034
[I 2024-04-18 22:05:53,449] Trial 31 finished with value: 0.22731761641400805 and parameters: {'subsample': 0.8364972308606371, 'dropout_rate': 0.54680467428975, 'n_estimators': 161, 'learning_rate': 0.019996174801938656}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.25323651613422615
Fold 2 IBS: 0.21738513407292417
Fold 3 IBS: 0.20641820719470322
Fold 4 IBS: 0.2644411245991167
Fold 5 IBS: 0.20664777880513482
[I 2024-04-18 22:06:00,811] Trial 32 finished with value: 0.229625752161221 and parameters: {'subsample': 0.7878845579666447, 'dropout_rate': 0.523408446151741, 'n_estimators': 181, 'learning_rate': 0.019921596908749617}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.24626967947688158
Fold 2 IBS: 0.21940895150556164
Fold 3 IBS: 0.21141364427478707
Fold 4 IBS: 0.261637917967439
Fold 5 IBS: 0.2125780673513178
[I 2024-04-18 22:06:03,737] Trial 33 finished with value: 0.2302616521151974 and parameters: {'subsample': 0.7337106220319078, 'dropout_rate': 0.4541172054940758, 'n_estimators': 83, 'learning_rate': 0.027997278046075002}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.24419997020481748
Fold 2 IBS: 0.22483706770757103
Fold 3 IBS: 0.22020643591742012
Fold 4 IBS: 0.24033403374714568
Fold 5 IBS: 0.221427070535628
[I 2024-04-18 22:06:08,853] Trial 34 finished with value: 0.23020091562251643 and parameters: {'subsample': 0.879175771199759, 'dropout_rate': 0.5875666668857409, 'n_estimators': 142, 'learning_rate': 0.007006489135311857}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.28075957518118405
Fold 2 IBS: 0.2223241371936366
Fold 3 IBS: 0.20524085851713497
Fold 4 IBS: 0.2817192945934226
Fold 5 IBS: 0.20136617846694335
[I 2024-04-18 22:06:15,912] Trial 35 finished with value: 0.23828200879046432 and parameters: {'subsample': 0.8213089277225901, 'dropout_rate': 0.7163368120498723, 'n_estimators': 178, 'learning_rate': 0.03716777466676148}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.33322889000097966
Fold 2 IBS: 0.2761029571453522
Fold 3 IBS: 0.23576125693558095
Fold 4 IBS: 0.3646772198363103
Fold 5 IBS: 0.22071349731186177
[I 2024-04-18 22:06:24,276] Trial 36 finished with value: 0.286096764246017 and parameters: {'subsample': 0.6589196551719204, 'dropout_rate': 0.44802940839198335, 'n_estimators': 200, 'learning_rate': 0.08793239753187249}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.2810895519401135
Fold 2 IBS: 0.22497913551086043
Fold 3 IBS: 0.20274611988030314
Fold 4 IBS: 0.28943927886467097
Fold 5 IBS: 0.2013205098470199
[I 2024-04-18 22:06:28,851] Trial 37 finished with value: 0.23991491920859356 and parameters: {'subsample': 0.5938237655012396, 'dropout_rate': 0.504039014281286, 'n_estimators': 117, 'learning_rate': 0.059207327336158105}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.24913260578831536

Fold 2 IBS: 0.2182215593937306
Fold 3 IBS: 0.20823493346801503
Fold 4 IBS: 0.2618867894566613
Fold 5 IBS: 0.2093390154585288
[I 2024-04-18 22:06:34,754] Trial 38 finished with value: 0.22936298071305022 and parameters: {'subsample': 0.7636971218212085, 'dropout_rate': 0.6483709169497328, 'n_estimators': 157, 'learning_rate': 0.019144317545493773}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.28103916288812086
Fold 2 IBS: 0.22171438039892677
Fold 3 IBS: 0.20500749397585746
Fold 4 IBS: 0.27630173359496024
Fold 5 IBS: 0.20128638585550865
[I 2024-04-18 22:06:46,677] Trial 39 finished with value: 0.2370698313426748 and parameters: {'subsample': 0.9093398198310482, 'dropout_rate': 0.35016062952952165, 'n_estimators': 241, 'learning_rate': 0.027420380756577795}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.33710682228256955
Fold 2 IBS: 0.3001823443008312
Fold 3 IBS: 0.24659723127721248
Fold 4 IBS: 0.3977251462922417
Fold 5 IBS: 0.2346436471139825
[I 2024-04-18 22:07:10,008] Trial 40 finished with value: 0.30325103825336747 and parameters: {'subsample': 0.7281909337674188, 'dropout_rate': 0.7825497504780614, 'n_estimators': 434, 'learning_rate': 0.06872337505060783}. Best is trial 23 with value: 0.2269899127562185.
Fold 1 IBS: 0.2455156658684153
Fold 2 IBS: 0.2192255861291408
Fold 3 IBS: 0.21224761644562298
Fold 4 IBS: 0.24370537113583216
Fold 5 IBS: 0.21362251975053054
[I 2024-04-18 22:07:15,287] Trial 41 finished with value: 0.22686335186590836 and parameters: {'subsample': 0.865022081447376, 'dropout_rate': 0.5499208660336358, 'n_estimators': 140, 'learning_rate': 0.01564020450524417}. Best is trial 41 with value: 0.22686335186590836.
Fold 1 IBS: 0.24480843252049106
Fold 2 IBS: 0.22036750900992863
Fold 3 IBS: 0.21374659498415688
Fold 4 IBS: 0.24495515685896588
Fold 5 IBS: 0.21498143156535768
[I 2024-04-18 22:07:22,224] Trial 42 finished with value: 0.22777182498778004 and parameters: {'subsample': 0.8404073884908283, 'dropout_rate': 0.5729087505412763, 'n_estimators': 181, 'learning_rate': 0.010696940812511076}. Best is trial 41 with value: 0.22686335186590836.
Fold 1 IBS: 0.26511774181296155
Fold 2 IBS: 0.21655572710297163
Fold 3 IBS: 0.2042553619700678
Fold 4 IBS: 0.2463439043442772
Fold 5 IBS: 0.20392139145558377
[I 2024-04-18 22:07:30,343] Trial 43 finished with value: 0.22723882533717238 and parameters: {'subsample': 0.9636423810916146, 'dropout_rate': 0.532743741755632, 'n_estimators': 201, 'learning_rate': 0.024725272462728674}. Best is trial 41 with value: 0.22686335186590836.
Fold 1 IBS: 0.26494015751387534
Fold 2 IBS: 0.21597666129350696
Fold 3 IBS: 0.2042863403566762
Fold 4 IBS: 0.24453340510526872
Fold 5 IBS: 0.20431825548173987
[I 2024-04-18 22:07:38,585] Trial 44 finished with value: 0.22681096395021338 and parameters: {'subsample': 0.9970638314347255, 'dropout_rate': 0.49727200549246, 'n_estimators': 201, 'learning_rate': 0.02454920460503046}. Best is trial 44 with value: 0.22681096395021338.
Fold 1 IBS: 0.2667638050868942
Fold 2 IBS: 0.21676610067466934
Fold 3 IBS: 0.20418571383161077
Fold 4 IBS: 0.2498889789324372
Fold 5 IBS: 0.20307471289586865
[I 2024-04-18 22:07:47,756] Trial 45 finished with value: 0.22813586228429603 and parameters: {'subsample': 0.9613612402816522, 'dropout_rate': 0.42225229666815806, 'n_estimators': 203, 'learning_rate': 0.02527901720704244}. Best is trial 44 with value: 0.22681096395021338.
Fold 1 IBS: 0.3090031162786983
Fold 2 IBS: 0.2341998480685489
Fold 3 IBS: 0.2135437870236706
Fold 4 IBS: 0.2763007460859121
Fold 5 IBS: 0.21253627180520349
[I 2024-04-18 22:08:00,928] Trial 46 finished with value: 0.2491167538524067 and parameters: {'subsample': 0.9938125346935734, 'dropout_rate': 0.684481269843097, 'n_estimators': 282, 'learning_rate': 0.03462389806943815}. Best is trial 44 with value: 0.22681096395021338.
Fold 1 IBS: 0.28777983472159707
Fold 2 IBS: 0.22420350526595603
Fold 3 IBS: 0.2062608561997086
Fold 4 IBS: 0.28043580660975237
Fold 5 IBS: 0.20162162568909983
[I 2024-04-18 22:08:11,723] Trial 47 finished with value: 0.24006032569722277 and parameters: {'subsample': 0.8997055499618302, 'dropout_rate': 0.48711947118966314, 'n_estimators': 243, 'learning_rate': 0.029840034438849757}. Best is trial 44 with value: 0.22681096395021338.
Fold 1 IBS: 0.30353361705529824
Fold 2 IBS: 0.23184439871163448
Fold 3 IBS: 0.21123909702434684
Fold 4 IBS: 0.28153833154795993
Fold 5 IBS: 0.20537828520091614
[I 2024-04-18 22:08:19,416] Trial 48 finished with value: 0.24670674590803113 and parameters: {'subsample': 0.95218690830408, 'dropout_rate': 0.6021367206211392, 'n_estimators': 198, 'learning_rate': 0.04578160032727594}. Best is trial 44 with value: 0.22681096395021338.
Fold 1 IBS: 0.24506660328814392
Fold 2 IBS: 0.22767707691237954
Fold 3 IBS: 0.22389028054118093
Fold 4 IBS: 0.23950940006032823
Fold 5 IBS: 0.2247837250347728
[I 2024-04-18 22:08:23,161] Trial 49 finished with value: 0.2321854171673611 and parameters: {'subsample': 0.9476188845943629, 'dropout_rate': 0.3751650594376542, 'n_estimators': 105, 'learning_rate': 0.005269660336964511}. Best is trial 44 with value: 0.22681096395021338.
Fold 1 IBS: 0.28174700005515796
Fold 2 IBS: 0.22779401883451889
Fold 3 IBS: 0.19577926952833968
Fold 4 IBS: 0.29126515366915384
Fold 5 IBS: 0.20160091938775432
[I 2024-04-18 22:08:38,793] Trial 50 finished with value: 0.23963727229498494 and parameters: {'subsample': 0.4370946895362843, 'dropout_rate': 0.633091953438621, 'n_estimators': 319, 'learning_rate': 0.023503853756755816}. Best is trial 44 with value: 0.22681096395021338.
Fold 1 IBS: 0.2509550733136643
Fold 2 IBS: 0.21763256137115533
Fold 3 IBS: 0.20726138974528321
Fold 4 IBS: 0.2640207611983941
Fold 5 IBS: 0.2078064040529802
[I 2024-04-18 22:08:45,116] Trial 51 finished with value: 0.22953523793629543 and parameters: {'subsample': 0.7755250498030826, 'dropout_rate': 0.5197702849125394, 'n_estimators': 163, 'learning_rate': 0.020351378335145588}. Best is trial 44 with value: 0.22681096395021338.
Fold 1 IBS: 0.24408078677335013
Fold 2 IBS: 0.22231496995640734
Fold 3 IBS: 0.2169421827881948
Fold 4 IBS: 0.23892301609153835
Fold 5 IBS: 0.21825980120175134
[I 2024-04-18 22:08:49,552] Trial 52 finished with value: 0.22810415136224838 and parameters: {'subsample': 0.896832438869532, 'dropout_rate': 0.5417150753548833, 'n_estimators': 125, 'learning_rate': 0.011505214036270051}. Best is trial 44 with value: 0.22681096395021338.
Fold 1 IBS: 0.24407808229460556
Fold 2 IBS: 0.22333641728263867
Fold 3 IBS: 0.21731456349283945
Fold 4 IBS: 0.24408492737368412
Fold 5 IBS: 0.2184551634856048
[I 2024-04-18 22:08:52,469] Trial 53 finished with value: 0.22945383078587453 and parameters: {'subsample': 0.824276740196252, 'dropout_rate': 0.4698626906230918, 'n_estimators': 81, 'learning_rate': 0.017242422008691888}. Best is trial 44 with value: 0.22681096395021338.
Fold 1 IBS: 0.2823637574966694
Fold 2 IBS: 0.223884305549478
Fold 3 IBS: 0.2037479104529697
Fold 4 IBS: 0.2881126589801557
Fold 5 IBS: 0.20126969951579032
[I 2024-04-18 22:09:01,810] Trial 54 finished with value: 0.23987566639901264 and parameters: {'subsample': 0.7050102269043423, 'dropout_rate': 0.6068280908446311, 'n_estimators': 219, 'learning_rate': 0.03095264658898532}. Best is trial 44 with value: 0.22681096395021338.
Fold 1 IBS: 0.2443455999680668
Fold 2 IBS: 0.22512957993051824
Fold 3 IBS: 0.22118190652865793
Fold 4 IBS: 0.23772872162611308
Fold 5 IBS: 0.2221944058431319
[I 2024-04-18 22:09:03,336] Trial 55 finished with value: 0.2301160427792976 and parameters: {'subsample': 0.9980793526485606, 'dropout_rate': 0.6770279274841706, 'n_estimators': 35, 'learning_rate': 0.025180726997684574}. Best is trial 44 with value: 0.22681096395021338.
Fold 1 IBS: 0.25696606739253064
Fold 2 IBS: 0.21562791660424535
Fold 3 IBS: 0.2053904839090569
Fold 4 IBS: 0.24328747635434092
Fold 5 IBS: 0.205777583211352
[I 2024-04-18 22:09:10,741] Trial 56 finished with value: 0.22540990549430515 and parameters: {'subsample': 0.9498348608100595, 'dropout_rate': 0.5558686850432644, 'n_estimators': 186, 'learning_rate': 0.02183977590220793}. Best is trial 56 with value: 0.22540990549430515.
Fold 1 IBS: 0.2868048273004324

Fold 2 IBS: 0.2234966644079048
Fold 3 IBS: 0.20593980844129078
Fold 4 IBS: 0.27519054629155376
Fold 5 IBS: 0.20167917402674448
[I 2024-04-18 22:09:19,335] Trial 57 finished with value: 0.23862220409358526 and parameters: {'subsample': 0.9320999261183475, 'dropout_rate': 0.4172035801671631, 'n_estimators': 196, 'learning_rate': 0.036525597651522655}. Best is trial 56 with value: 0.22540990549430515.
Fold 1 IBS: 0.25001648359878603
Fold 2 IBS: 0.21622148540985112
Fold 3 IBS: 0.20811978633565079
Fold 4 IBS: 0.23691774104033314
Fold 5 IBS: 0.2092644296246439
[I 2024-04-18 22:09:29,395] Trial 58 finished with value: 0.224107985201853 and parameters: {'subsample': 0.9586197943864213, 'dropout_rate': 0.5740168344366231, 'n_estimators': 232, 'learning_rate': 0.013408218059981283}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2516874301562455
Fold 2 IBS: 0.21553073521939023
Fold 3 IBS: 0.20726808939440847
Fold 4 IBS: 0.23795443014521295
Fold 5 IBS: 0.20905124507220235
[I 2024-04-18 22:09:40,480] Trial 59 finished with value: 0.2242983859974919 and parameters: {'subsample': 0.9652720139854304, 'dropout_rate': 0.7411003895095187, 'n_estimators': 268, 'learning_rate': 0.012522841841469406}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2440374311868831
Fold 2 IBS: 0.22320937804375754
Fold 3 IBS: 0.21801245666015756
Fold 4 IBS: 0.2394233609411069
Fold 5 IBS: 0.2191397703083953
[I 2024-04-18 22:09:52,701] Trial 60 finished with value: 0.22876447942806005 and parameters: {'subsample': 0.8877882559292194, 'dropout_rate': 0.7604007201578447, 'n_estimators': 279, 'learning_rate': 0.00466415089190159}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2518309903895484
Fold 2 IBS: 0.21542113504824933
Fold 3 IBS: 0.20719446055295826
Fold 4 IBS: 0.23826653471768652
Fold 5 IBS: 0.20944978842616072
[I 2024-04-18 22:10:03,588] Trial 61 finished with value: 0.22443258182692066 and parameters: {'subsample': 0.9751927529064672, 'dropout_rate': 0.8849323086186959, 'n_estimators': 269, 'learning_rate': 0.012553312929443144}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2580559356430994
Fold 2 IBS: 0.21525423212437986
Fold 3 IBS: 0.20522320874547026
Fold 4 IBS: 0.24141866624586059
Fold 5 IBS: 0.207141811490814
[I 2024-04-18 22:10:16,119] Trial 62 finished with value: 0.22541877084992484 and parameters: {'subsample': 0.9662399430154112, 'dropout_rate': 0.9468924328014086, 'n_estimators': 315, 'learning_rate': 0.01323711436683926}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2488648491432984
Fold 2 IBS: 0.2162957287559642
Fold 3 IBS: 0.2089990442858537
Fold 4 IBS: 0.23705041756364206
Fold 5 IBS: 0.2106476047496199
[I 2024-04-18 22:10:30,528] Trial 63 finished with value: 0.22437152889967565 and parameters: {'subsample': 0.9654966413811427, 'dropout_rate': 0.9883050010188703, 'n_estimators': 349, 'learning_rate': 0.008307772880083586}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.24781119176349092
Fold 2 IBS: 0.21673574704932538
Fold 3 IBS: 0.20980501726378856
Fold 4 IBS: 0.23652063574646404
Fold 5 IBS: 0.21150372425488168
[I 2024-04-18 22:10:42,920] Trial 64 finished with value: 0.2244752632155901 and parameters: {'subsample': 0.9650056910386597, 'dropout_rate': 0.9584054256924132, 'n_estimators': 314, 'learning_rate': 0.008624428297388652}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.25056113174377354
Fold 2 IBS: 0.21577180216850703
Fold 3 IBS: 0.20795014316972474
Fold 4 IBS: 0.23789427860871581
Fold 5 IBS: 0.20961950777345675
[I 2024-04-18 22:10:59,449] Trial 65 finished with value: 0.2243593726928356 and parameters: {'subsample': 0.9712842797437069, 'dropout_rate': 0.9678154303000257, 'n_estimators': 380, 'learning_rate': 0.008355289106183609}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2503538221744384
Fold 2 IBS: 0.2163931268043346
Fold 3 IBS: 0.20787502470080996
Fold 4 IBS: 0.2394748216317287
Fold 5 IBS: 0.20880062489306755
[I 2024-04-18 22:11:17,404] Trial 66 finished with value: 0.22457948404087585 and parameters: {'subsample': 0.920060540171943, 'dropout_rate': 0.8716429634117672, 'n_estimators': 375, 'learning_rate': 0.008424608924311848}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2515521889516478
Fold 2 IBS: 0.2161982430478331
Fold 3 IBS: 0.2072816195521366
Fold 4 IBS: 0.24274906238928662
Fold 5 IBS: 0.2079412534033638
[I 2024-04-18 22:11:37,955] Trial 67 finished with value: 0.2251444734688536 and parameters: {'subsample': 0.9149808376440253, 'dropout_rate': 0.8896976252714249, 'n_estimators': 411, 'learning_rate': 0.008125415521896094}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.24145685161318234
Fold 2 IBS: 0.222221310922633
Fold 3 IBS: 0.21258801595978405
Fold 4 IBS: 0.26191624076167175
Fold 5 IBS: 0.2172133252799244
[I 2024-04-18 22:11:55,056] Trial 68 finished with value: 0.23107914890743914 and parameters: {'subsample': 0.19794656962716917, 'dropout_rate': 0.9664047366299621, 'n_estimators': 367, 'learning_rate': 0.00458931028111126}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.24461678557957228
Fold 2 IBS: 0.2264266227767564
Fold 3 IBS: 0.22234363977745092
Fold 4 IBS: 0.2387240540628068
Fold 5 IBS: 0.2232906225847799
[I 2024-04-18 22:12:13,960] Trial 69 finished with value: 0.23108034495627328 and parameters: {'subsample': 0.9269373059525665, 'dropout_rate': 0.8610645583930226, 'n_estimators': 392, 'learning_rate': 0.0018712668715524221}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.24980699049135152
Fold 2 IBS: 0.2159129943201185
Fold 3 IBS: 0.20836225161713323
Fold 4 IBS: 0.23757551951760214
Fold 5 IBS: 0.2100186195017771
[I 2024-04-18 22:12:30,448] Trial 70 finished with value: 0.22433527508959647 and parameters: {'subsample': 0.9730597663357353, 'dropout_rate': 0.9298699987452733, 'n_estimators': 366, 'learning_rate': 0.008356457472714972}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.24996053051817851
Fold 2 IBS: 0.21586747319246127
Fold 3 IBS: 0.20826187454002767
Fold 4 IBS: 0.23766626874058747
Fold 5 IBS: 0.21024827389930717
[I 2024-04-18 22:12:46,076] Trial 71 finished with value: 0.22440088417811244 and parameters: {'subsample': 0.9738534290122554, 'dropout_rate': 0.930217107212676, 'n_estimators': 352, 'learning_rate': 0.008759924477847313}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2602374467993739
Fold 2 IBS: 0.21540055822594104
Fold 3 IBS: 0.2048298138507759
Fold 4 IBS: 0.24256134532990659
Fold 5 IBS: 0.20677086865766264
[I 2024-04-18 22:13:00,164] Trial 72 finished with value: 0.22596000657273202 and parameters: {'subsample': 0.9688251070518349, 'dropout_rate': 0.9370619651592799, 'n_estimators': 339, 'learning_rate': 0.01301721419424927}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2522300996227662
Fold 2 IBS: 0.21541271414109397
Fold 3 IBS: 0.20707710873695825
Fold 4 IBS: 0.23875941861756944
Fold 5 IBS: 0.20931752895315273
[I 2024-04-18 22:13:14,208] Trial 73 finished with value: 0.22455937401430814 and parameters: {'subsample': 0.9743569541841973, 'dropout_rate': 0.9951287953545447, 'n_estimators': 342, 'learning_rate': 0.01001628961606417}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.24560713117751337
Fold 2 IBS: 0.22904764144348624
Fold 3 IBS: 0.22540926590706145
Fold 4 IBS: 0.24067162709966133
Fold 5 IBS: 0.22613641821269378
[I 2024-04-18 22:13:24,083] Trial 74 finished with value: 0.2333744167680832 and parameters: {'subsample': 0.884452907212063, 'dropout_rate': 0.9137358572495864, 'n_estimators': 262, 'learning_rate': 0.0014674224126974}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2445417862289315
Fold 2 IBS: 0.22047119689711647
Fold 3 IBS: 0.2147903295056666
Fold 4 IBS: 0.23710241323832448
Fold 5 IBS: 0.21597943129183614
[I 2024-04-18 22:13:38,419] Trial 75 finished with value: 0.22657703143237504 and parameters: {'subsample': 0.9374363439652392, 'dropout_rate': 0.9631954147357524, 'n_estimators': 348, 'learning_rate': 0.005117661548862427}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2567106379350411
Fold 2 IBS: 0.21508706599517644

Fold 3 IBS: 0.2055220508619335
Fold 4 IBS: 0.2400446483858902
Fold 5 IBS: 0.20904869748033597
[I 2024-04-18 22:13:52,687] Trial 76 finished with value: 0.22528262013167547 and parameters: {'subsample': 0.9850530223586534, 'dropout_rate': 0.8436461076063504, 'n_estimators': 315, 'learning_rate': 0.01272054974228212}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2483081177028861
Fold 2 IBS: 0.21709564903157766
Fold 3 IBS: 0.20941684673788108
Fold 4 IBS: 0.242767563788497
Fold 5 IBS: 0.21032040763749132
[I 2024-04-18 22:14:10,793] Trial 77 finished with value: 0.22558171697966664 and parameters: {'subsample': 0.9014722175572065, 'dropout_rate': 0.9195364994175442, 'n_estimators': 394, 'learning_rate': 0.007105228355913655}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2866109326332082
Fold 2 IBS: 0.2278685488228803
Fold 3 IBS: 0.200404072315968
Fold 4 IBS: 0.2933783890804398
Fold 5 IBS: 0.20174961400213423
[I 2024-04-18 22:14:33,823] Trial 78 finished with value: 0.24200231137092607 and parameters: {'subsample': 0.5287437811396662, 'dropout_rate': 0.8221345539318206, 'n_estimators': 437, 'learning_rate': 0.01725794508022381}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2482479428757907
Fold 2 IBS: 0.2167316946594085
Fold 3 IBS: 0.20937933398270847
Fold 4 IBS: 0.23830762517045018
Fold 5 IBS: 0.2105115318066822
[I 2024-04-18 22:14:46,420] Trial 79 finished with value: 0.224635625699008 and parameters: {'subsample': 0.9425693298447977, 'dropout_rate': 0.8910687931385187, 'n_estimators': 299, 'learning_rate': 0.009377332004564882}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2693233541400068
Fold 2 IBS: 0.21691471441196677
Fold 3 IBS: 0.20413488548806752
Fold 4 IBS: 0.24830586454133138
Fold 5 IBS: 0.20594471567655956
[I 2024-04-18 22:15:01,493] Trial 80 finished with value: 0.22892470685158642 and parameters: {'subsample': 0.9723518481253051, 'dropout_rate': 0.9749383233391162, 'n_estimators': 355, 'learning_rate': 0.015105901751382747}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2536600670227251
Fold 2 IBS: 0.21524739045329427
Fold 3 IBS: 0.20647613544326285
Fold 4 IBS: 0.23953263267061448
Fold 5 IBS: 0.20884710194099898
[I 2024-04-18 22:15:14,652] Trial 81 finished with value: 0.22475266550617912 and parameters: {'subsample': 0.9744873146677288, 'dropout_rate': 0.9976812036990962, 'n_estimators': 328, 'learning_rate': 0.011052906596609641}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.24880456435861817
Fold 2 IBS: 0.2160932748216439
Fold 3 IBS: 0.20902011705006837
Fold 4 IBS: 0.23644269046782268
Fold 5 IBS: 0.21214065732879597
[I 2024-04-18 22:15:32,094] Trial 82 finished with value: 0.22450026080538982 and parameters: {'subsample': 0.9949081024200213, 'dropout_rate': 0.9379507117578167, 'n_estimators': 386, 'learning_rate': 0.007474421436655516}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.24642011953286222
Fold 2 IBS: 0.2173898077854278
Fold 3 IBS: 0.21126479839450693
Fold 4 IBS: 0.23574585643238916
Fold 5 IBS: 0.21380876387365208
[I 2024-04-18 22:28:57,447] Trial 83 finished with value: 0.22492586920376761 and parameters: {'subsample': 0.9919085011089366, 'dropout_rate': 0.9408789613881645, 'n_estimators': 380, 'learning_rate': 0.006309967329340597}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2442094080485511
Fold 2 IBS: 0.22179714417488386
Fold 3 IBS: 0.2160070624551183
Fold 4 IBS: 0.24062488665071055
Fold 5 IBS: 0.21726802194038214
[I 2024-04-18 22:29:36,931] Trial 84 finished with value: 0.22798130465392918 and parameters: {'subsample': 0.8764217271982961, 'dropout_rate': 0.816197844397807, 'n_estimators': 418, 'learning_rate': 0.0037736440149859327}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.28153210833542563
Fold 2 IBS: 0.22061634628596558
Fold 3 IBS: 0.20498731106237916
Fold 4 IBS: 0.2609598422337242
Fold 5 IBS: 0.20324303417061707
[I 2024-04-18 22:33:30,297] Trial 85 finished with value: 0.23426772841762236 and parameters: {'subsample': 0.9437440810292549, 'dropout_rate': 0.9173009006245891, 'n_estimators': 357, 'learning_rate': 0.018372767710837304}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2823481292390889
Fold 2 IBS: 0.22115078409867742
Fold 3 IBS: 0.20505756855586812
Fold 4 IBS: 0.26726492382050965
Fold 5 IBS: 0.20243148249221
[I 2024-04-18 22:33:56,274] Trial 86 finished with value: 0.23565057764127081 and parameters: {'subsample': 0.9170155344707267, 'dropout_rate': 0.9684185618217634, 'n_estimators': 470, 'learning_rate': 0.014157550359736058}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.24488924943788568
Fold 2 IBS: 0.21945535680451725
Fold 3 IBS: 0.21371027077975766
Fold 4 IBS: 0.23564348932509593
Fold 5 IBS: 0.21508039422117062
[I 2024-04-18 22:34:09,509] Trial 87 finished with value: 0.22575575211368543 and parameters: {'subsample': 0.9580266012502167, 'dropout_rate': 0.8773887610462885, 'n_estimators': 271, 'learning_rate': 0.007190805934355407}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.24412015550002117
Fold 2 IBS: 0.22381452328861395
Fold 3 IBS: 0.2197361702775311
Fold 4 IBS: 0.23709678303554732
Fold 5 IBS: 0.2209193427036495
[I 2024-04-18 22:34:48,115] Trial 88 finished with value: 0.2291373949610726 and parameters: {'subsample': 0.9990428112587949, 'dropout_rate': 0.9350171642385964, 'n_estimators': 299, 'learning_rate': 0.003565903495513581}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.24644159306584204
Fold 2 IBS: 0.2183875808171544
Fold 3 IBS: 0.21117085800067376
Fold 4 IBS: 0.24033137480797173
Fold 5 IBS: 0.21226228409104775
[I 2024-04-18 22:35:28,018] Trial 89 finished with value: 0.22571873815653792 and parameters: {'subsample': 0.9080329513018223, 'dropout_rate': 0.790060821866682, 'n_estimators': 249, 'learning_rate': 0.009709787398868483}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2679041648681114
Fold 2 IBS: 0.21928574115451596
Fold 3 IBS: 0.20402587879068054
Fold 4 IBS: 0.2751923250258911
Fold 5 IBS: 0.20236796235031088
[I 2024-04-18 22:36:16,923] Trial 90 finished with value: 0.23375521443790198 and parameters: {'subsample': 0.8615295051810605, 'dropout_rate': 0.10184332440552968, 'n_estimators': 326, 'learning_rate': 0.01650486434819319}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2533305489727741
Fold 2 IBS: 0.21528474304940623
Fold 3 IBS: 0.20662153887247897
Fold 4 IBS: 0.2393078674830213
Fold 5 IBS: 0.20889437283334916
[I 2024-04-18 22:36:53,063] Trial 91 finished with value: 0.22468781424220596 and parameters: {'subsample': 0.9743352458226496, 'dropout_rate': 0.9802799821783295, 'n_estimators': 342, 'learning_rate': 0.01045972997128578}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.26176982357924744
Fold 2 IBS: 0.21554247836063548
Fold 3 IBS: 0.2046079765088823
Fold 4 IBS: 0.24379982511819034
Fold 5 IBS: 0.20730489732657112
[I 2024-04-18 23:25:34,494] Trial 92 finished with value: 0.22660500017870536 and parameters: {'subsample': 0.9758450076103484, 'dropout_rate': 0.9912479003331257, 'n_estimators': 387, 'learning_rate': 0.011828119360348367}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.2520870942446833
Fold 2 IBS: 0.2160349822272325
Fold 3 IBS: 0.20718507686219564
Fold 4 IBS: 0.24173950412935447
Fold 5 IBS: 0.20785348820482769
[I 2024-04-18 23:29:48,712] Trial 93 finished with value: 0.22498002913365872 and parameters: {'subsample': 0.9341721399004266, 'dropout_rate': 0.9494867657487719, 'n_estimators': 401, 'learning_rate': 0.008474222019097463}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.3381930460754981
Fold 2 IBS: 0.2761182855902764
Fold 3 IBS: 0.24899332480599576
Fold 4 IBS: 0.3337252635331669
Fold 5 IBS: 0.2323907445512124
[I 2024-04-18 23:30:08,877] Trial 94 finished with value: 0.28588413291122994 and parameters: {'subsample': 0.9542636756481477, 'dropout_rate': 0.9033958113695965, 'n_estimators': 374, 'learning_rate': 0.08077924912008731}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.24454923647981563
Fold 2 IBS: 0.2259641670788187
Fold 3 IBS: 0.22213467946791526

Fold 4 IBS: 0.2383428523814535
Fold 5 IBS: 0.22304882189394717
[I 2024-04-18 23:30:21,650] Trial 95 finished with value: 0.23080795146039007 and parameters: {'subsample': 0.9761469148364865, 'dropout_rate': 0.9976109764514575, 'n_estimators': 310, 'learning_rate': 0.0024676593595529574}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.26782485208938583
Fold 2 IBS: 0.21701225468661342
Fold 3 IBS: 0.20414842345737763
Fold 4 IBS: 0.25182349910467233
Fold 5 IBS: 0.20356211708550198
[I 2024-04-18 23:30:40,009] Trial 96 finished with value: 0.2288742292847102 and parameters: {'subsample': 0.932574881679507, 'dropout_rate': 0.8491419147294211, 'n_estimators': 363, 'learning_rate': 0.014382672512565652}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.24422362832471908
Fold 2 IBS: 0.2208135515925996
Fold 3 IBS: 0.2160339018757797
Fold 4 IBS: 0.23597229499128605
Fold 5 IBS: 0.21768932618988893
[I 2024-04-18 23:30:50,260] Trial 97 finished with value: 0.22694654059485467 and parameters: {'subsample': 0.9993215143819714, 'dropout_rate': 0.9263488734601075, 'n_estimators': 285, 'learning_rate': 0.005553765576207407}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.24830945757906256
Fold 2 IBS: 0.21718169978172686
Fold 3 IBS: 0.20935291025744182
Fold 4 IBS: 0.24165248591998204
Fold 5 IBS: 0.21025163562081342
[I 2024-04-18 23:30:58,843] Trial 98 finished with value: 0.22534963783180534 and parameters: {'subsample': 0.8982638943292622, 'dropout_rate': 0.8930874708034484, 'n_estimators': 233, 'learning_rate': 0.012067331681770417}. Best is trial 58 with value: 0.224107985201853.
Fold 1 IBS: 0.3354379988206145
Fold 2 IBS: 0.262857522598689
Fold 3 IBS: 0.23934819174424765
Fold 4 IBS: 0.31500192414874617
Fold 5 IBS: 0.227884558782846
[I 2024-04-18 23:31:13,198] Trial 99 finished with value: 0.27610603921902865 and parameters: {'subsample': 0.956706371362489, 'dropout_rate': 0.9521096109552873, 'n_estimators': 350, 'learning_rate': 0.052443959168945425}. Best is trial 58 with value: 0.224107985201853.


* Best trial for IBS:
 FrozenTrial(number=58, state=TrialState.COMPLETE, values=[0.224107985201853], datetime_start=datetime.datetime(2024, 4, 18, 22, 9, 19, 342455), datetime_complete=datetime.datetime(2024, 4, 18, 22, 9, 29, 395417), params={'subsample': 0.9586197943864213, 'dropout_rate': 0.5740168344366231, 'n_estimators': 232, 'learning_rate': 0.013408218059981283}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=58, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.9586197943864213, 'dropout_rate': 0.5740168344366231, 'n_estimators': 232, 'learning_rate': 0.013408218059981283}


* Best Score for IBS:
 0.224107985201853

In [66]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [67]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.633
train_ibs:  0.224

#### Test

In [68]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [69]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.3575254014553415,
                                              learning_rate=0.05558016213920623,
                                              n_estimators=114,
                                              random_state=123,
                                              subsample=0.7268222670380755)

C-index score: 0.601

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.5740168344366231,
                                              learning_rate=0.013408218059981283,
                                              n_estimators=232,
                                              random_state=123,
                                              subsample=0.9586197943864213)

IBS: 0.214

In [70]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [71]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.782   1.0
ExtraSurvivalTrees               0.746   2.0
GradientBoosting                 0.663   3.0
ComponentwiseGradientBoosting    0.633   4.0
CoxPH                            0.631   5.5
CoxElastic                       0.631   5.5
CoxLasso                         0.630   7.0
CoxRidge                         0.590   8.0

In [72]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.218   1.0
Randomsurvivalforest           0.221   2.0
ComponentwiseGradientBoosting  0.224   3.0
GradientBoosting               0.230   4.0
CoxLasso                       0.231   5.5
CoxElastic                     0.231   5.5
CoxPH                          0.232   7.0
CoxRidge                       0.236   8.0

In [73]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
CoxRidge                         0.642   1.0
Randomsurvivalforest             0.622   2.5
GradientBoosting                 0.622   2.5
ComponentwiseGradientBoosting    0.601   4.0
ExtraSurvivalTrees               0.600   5.0
CoxLasso                         0.599   6.5
CoxElastic                       0.599   6.5
CoxPH                            0.593   8.0

In [74]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.213   1.0
Randomsurvivalforest           0.214   2.5
ComponentwiseGradientBoosting  0.214   2.5
GradientBoosting               0.221   4.0
CoxRidge                       0.229   5.0
CoxLasso                       0.250   6.5
CoxElastic                     0.250   6.5
CoxPH                          0.253   8.0

In [75]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/dfs/robust/plsr/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_dfs_robust_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [76]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-18