In [44]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
 
from sklearn.preprocessing import PowerTransformer

In [45]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [46]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [47]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

## Test dataset: MAASTRO

In [48]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [49]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [50]:
# need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [51]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,DFS,DFS_event
0,1,55,0,0,1,0,0,1,1,1,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,8.83,1.0
3,4,61,1,0,0,0,1,1,0,1,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,19.73,1.0
4,6,70,0,0,1,0,0,1,1,1,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,13.27,1.0
95,111,63,0,0,0,0,1,0,0,1,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [52]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [53]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [54]:
# Set X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# Set y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [55]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [56]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 388)
y_train:  (139,)

In [57]:
# Change the name of a column 'DFS_event' in the clincial_test 
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [58]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 390)

## Feature Selection

### COX PLSR

In [59]:
# Choose features from the result of Cox PLSR in R
selected_features = [
"first_order_Maximum_CT",
"LBP_201_PET",
"LBP_003_PET",
"LBP_102_PET",
"gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16",
"gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2",
]

In [60]:
X_plsr = X.loc[:, selected_features]
X_new = X_plsr.copy()

In [61]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, selected_features]

# Yeo-Johnson Transformation

In [62]:
# Copy the original X for later 
original_X = X.copy()

In [63]:
# Transform X_new 
# Set the categorical_columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Apply Yeo-Johnson transformation
pt = PowerTransformer(method='yeo-johnson')
X_new_numeric_transformed = pt.fit_transform(X_new_numeric)

# Create DataFrame with transformed numerical data
X_new_numeric_transformed = pd.DataFrame(X_new_numeric_transformed, 
                                         columns=X_new_numeric.columns, 
                                         index=X_new.index)

# Concatenate transformed numerical data with categorical data
X_new_std = pd.concat([X_new_numeric_transformed, X_new_categoric], axis=1)

# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the transformation for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = pt.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [64]:
X_new

,first_order_Maximum_CT,LBP_201_PET,LBP_003_PET,LBP_102_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2
0,1763.283818,0.000062,0.000123,0.000000,0.000416,0.000959
1,1432.109636,0.000349,0.000349,0.000000,0.001753,0.002776
2,1685.931373,0.000000,0.000000,0.000034,0.000230,0.001179
3,1329.347515,0.000000,0.000300,0.000000,0.000711,0.002748
4,1197.225910,0.000399,0.000000,0.000199,0.001033,0.002309
...,...,...,...,...,...,...
134,1267.959716,0.000000,0.000000,0.000000,0.000226,0.001347
135,1788.278096,0.000079,0.000039,0.000000,0.000183,0.000850
136,1478.297861,0.000000,0.000000,0.000000,0.000621,0.001111
137,1207.068493,0.000054,0.000000,0.000000,0.000265,0.000935
138,1368.499199,0.000000,0.000000,0.000000,0.000421,0.000629

In [65]:
X_new_std

,first_order_Maximum_CT,LBP_201_PET,LBP_003_PET,LBP_102_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2
0,1.022943,-0.074611,1.042615,-0.784694,-0.128003,-0.456825
1,0.072727,1.689445,1.929439,-0.784694,1.761655,1.829690
2,0.853782,-1.065926,-0.799521,0.236612,-0.861897,0.033412
3,-0.390532,-1.065926,1.846691,-0.784694,0.668885,1.814149
4,-1.187658,1.782787,-0.799521,1.784568,1.208077,1.522029
...,...,...,...,...,...,...
134,-0.727488,-1.065926,-0.799521,-0.784694,-0.877225,0.352487
135,1.072604,0.138716,-0.000653,-0.784694,-1.082845,-0.735470
136,0.247868,-1.065926,-0.799521,-0.784694,0.464990,-0.108155
137,-1.118344,-0.175482,-0.799521,-0.784694,-0.706059,-0.515193
138,-0.200688,-1.065926,-0.799521,-0.784694,-0.112899,-1.381293

In [66]:
MAASTRO_new

,first_order_Maximum_CT,LBP_201_PET,LBP_003_PET,LBP_102_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2
0,1226.795917,0.000026,0.000026,0.000026,0.000241,0.000768
1,1876.570382,0.000167,0.000056,0.000167,0.000621,0.001213
2,1269.217095,0.000000,0.000286,0.000057,0.000327,0.001176
3,1951.924395,0.000080,0.000160,0.000000,0.001419,0.001192
4,1646.853670,0.000035,0.000071,0.000000,0.000165,0.000766
...,...,...,...,...,...,...
94,2311.845731,0.000078,0.000000,0.000000,0.000739,0.001137
95,1299.857157,0.000054,0.000109,0.000000,0.001130,0.000962
96,1256.024949,0.000028,0.000000,0.000000,0.000226,0.000621
97,1668.742962,0.000000,0.000114,0.000000,0.000296,0.000947
98,1654.841840,0.000112,0.000000,0.000000,0.001394,0.001661

In [67]:
MAASTRO_new_std

,first_order_Maximum_CT,LBP_201_PET,LBP_003_PET,LBP_102_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2
0,-0.984802,-0.597387,-0.238970,0.033184,-0.811666,-0.960377
1,1.231237,0.946684,0.263801,1.682719,0.464229,0.101598
2,-0.720051,-1.065926,1.817599,0.693043,-0.453072,0.027699
3,1.348682,0.152800,1.314752,-0.784694,1.579512,0.060650
4,0.758335,-0.453142,0.471935,-0.784694,-1.171859,-0.967045
...,...,...,...,...,...,...
94,1.750433,0.126817,-0.799521,-0.784694,0.727222,-0.052777
95,-0.545966,-0.173978,0.907497,-0.784694,1.322893,-0.450240
96,-0.799285,-0.565019,-0.799521,-0.784694,-0.877027,-1.409205
97,0.812692,-1.065926,0.962590,-0.784694,-0.577241,-0.485449
98,0.778442,0.498900,-0.799521,-0.784694,1.561904,0.840017

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [68]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')

            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)

                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:45:26,676] A new study created in memory with name: no-name-5847f1d3-6746-42dd-ab6f-47146e9f256e
python(32902) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7872340425531915

[I 2024-04-16 20:45:37,829] A new study created in memory with name: no-name-100d6f6d-27a0-417f-b949-2f25b65f0198

Fold 4 C-index: 0.39923954372623577
Fold 5 C-index: 0.5450643776824035
[I 2024-04-16 20:45:37,806] Trial 0 finished with value: 0.5801041893518646 and parameters: {}. Best is trial 0 with value: 0.5801041893518646.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5801041893518646], datetime_start=datetime.datetime(2024, 4, 16, 20, 45, 27, 120085), datetime_complete=datetime.datetime(2024, 4, 16, 20, 45, 37, 804911), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5801041893518646

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2631227485062865
Fold 2 IBS: 0.21992045469997798
Fold 3 IBS: 0.18351218320743473
Fold 4 IBS: 0.3295941082344743
Fold 5 IBS: 0.25161822070737033
[I 2024-04-16 20:45:38,269] Trial 0 finished with value: 0.2495535430711088 and parameters: {}. Best is trial 0 with value: 0.2495535430711088.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2495535430711088], datetime_start=datetime.datetime(2024, 4, 16, 20, 45, 37, 870561), datetime_complete=datetime.datetime(2024, 4, 16, 20, 45, 38, 269409), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2495535430711088

In [69]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [70]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.58
train_ibs:  0.25

#### Test

In [71]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [72]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.553
IBS score: 0.246

In [73]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [74]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [75]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')

            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)

                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:45:38,592] A new study created in memory with name: no-name-f507e689-7430-41a3-8bfe-189fe30a1bf6

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-16 20:45:38,942] A new study created in memory with name: no-name-cedd67f3-44e1-4790-9e2b-ee32df04346d

Fold 1 C-index: 0.48804780876494025
Fold 2 C-index: 0.6918604651162791
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.4144486692015209
Fold 5 C-index: 0.5128755364806867
[I 2024-04-16 20:45:38,931] Trial 0 finished with value: 0.5848507512318343 and parameters: {}. Best is trial 0 with value: 0.5848507512318343.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5848507512318343], datetime_start=datetime.datetime(2024, 4, 16, 20, 45, 38, 625095), datetime_complete=datetime.datetime(2024, 4, 16, 20, 45, 38, 931292), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5848507512318343

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710126201854
Fold 2 IBS: 0.23203988007163143
Fold 3 IBS: 0.22898185146634253
Fold 4 IBS: 0.2419747781639664
Fold 5 IBS: 0.22939559565695583
[I 2024-04-16 20:45:39,346] Trial 0 finished with value: 0.23592784132418293 and parameters: {}. Best is trial 0 with value: 0.23592784132418293.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592784132418293], datetime_start=datetime.datetime(2024, 4, 16, 20, 45, 38, 980129), datetime_complete=datetime.datetime(2024, 4, 16, 20, 45, 39, 344932), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592784132418293

In [76]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [77]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.585
train_ibs:  0.236

#### Test

In [78]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [79]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.569

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [80]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [81]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')

            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)

                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:45:39,956] A new study created in memory with name: no-name-f535c884-5132-48e0-bd08-65a6fa32c5a6

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:40,367] Trial 0 finished with value: 0.5935639212572479 and parameters: {}. Best is trial 0 with value: 0.5935639212572479.

[I 2024-04-16 20:45:40,406] A new study created in memory with name: no-name-f1800494-6944-4373-a817-bb91eb4c929c

* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5935639212572479], datetime_start=datetime.datetime(2024, 4, 16, 20, 45, 40, 686), datetime_complete=datetime.datetime(2024, 4, 16, 20, 45, 40, 367287), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5935639212572479

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.262979850327254
Fold 2 IBS: 0.22664749640228837
Fold 3 IBS: 0.21369285752862316
Fold 4 IBS: 0.32792704532765343
Fold 5 IBS: 0.2513898907749928
[I 2024-04-16 20:45:40,996] Trial 0 finished with value: 0.25652742807216233 and parameters: {}. Best is trial 0 with value: 0.25652742807216233.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.25652742807216233], datetime_start=datetime.datetime(2024, 4, 16, 20, 45, 40, 517372), datetime_complete=datetime.datetime(2024, 4, 16, 20, 45, 40, 996707), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.25652742807216233

In [82]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [83]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.594
train_ibs:  0.257

#### Test

In [84]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [85]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.553

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.246

In [86]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [87]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')

            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)

                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:45:41,487] A new study created in memory with name: no-name-33e8053e-745c-4efc-af15-31590b2fca8e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:41,927] Trial 0 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:42,709] Trial 1 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:43,300] Trial 2 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:44,004] Trial 3 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:44,549] Trial 4 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:44,976] Trial 5 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:45,468] Trial 6 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:46,002] Trial 7 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:46,518] Trial 8 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:46,945] Trial 9 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:47,450] Trial 10 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5107296137339056
[I 2024-04-16 20:45:47,744] Trial 11 finished with value: 0.5844439566015824 and parameters: {'l1_ratio': 0.046971505265140434}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:48,185] Trial 12 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.21309581087335225}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:48,617] Trial 13 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.743964055575976}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:48,980] Trial 14 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.21599024455432275}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:49,355] Trial 15 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.820763570686791}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:49,736] Trial 16 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.5880713606511995}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:50,153] Trial 17 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.35870521424355084}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5150214592274678
[I 2024-04-16 20:45:50,452] Trial 18 finished with value: 0.585302325700295 and parameters: {'l1_ratio': 0.039318771596377255}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:50,820] Trial 19 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.608409044915716}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:51,118] Trial 20 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.8744063907908842}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:51,405] Trial 21 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.26843065456411686}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:51,751] Trial 22 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.13361135845786085}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:52,024] Trial 23 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.2976235432977797}. Best is trial 0 with value: 0.5935639212572479.

Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:52,483] Trial 24 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.15433706302991543}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:52,790] Trial 25 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.4626599986704694}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:53,069] Trial 26 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.3312072877416866}. Best is trial 0 with value: 0.5935639212572479.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:53,344] Trial 27 finished with value: 0.5944002475623498 and parameters: {'l1_ratio': 0.09486155085202524}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.51931330472103
[I 2024-04-16 20:45:53,551] Trial 28 finished with value: 0.5869211510727717 and parameters: {'l1_ratio': 0.07728121210428013}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:53,870] Trial 29 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.1400622484437714}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5107296137339056
[I 2024-04-16 20:45:54,219] Trial 30 finished with value: 0.5836687628031328 and parameters: {'l1_ratio': 0.001691868247779768}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:54,571] Trial 31 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.24354183082267372}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:54,923] Trial 32 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.5122461925030248}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:55,279] Trial 33 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.17847477181900862}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:55,594] Trial 34 finished with value: 0.5944002475623498 and parameters: {'l1_ratio': 0.09013565305997792}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:56,125] Trial 35 finished with value: 0.5920135336603487 and parameters: {'l1_ratio': 0.11492777215697396}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:56,496] Trial 36 finished with value: 0.5944002475623498 and parameters: {'l1_ratio': 0.09547317122920525}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:56,856] Trial 37 finished with value: 0.5944002475623498 and parameters: {'l1_ratio': 0.08702479999133529}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.51931330472103
[I 2024-04-16 20:45:57,281] Trial 38 finished with value: 0.5869211510727717 and parameters: {'l1_ratio': 0.0788162861613429}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5107296137339056
[I 2024-04-16 20:45:57,693] Trial 39 finished with value: 0.5836687628031328 and parameters: {'l1_ratio': 0.0013452165746168088}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:58,528] Trial 40 finished with value: 0.5944002475623498 and parameters: {'l1_ratio': 0.08815549415020946}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.51931330472103
[I 2024-04-16 20:45:59,168] Trial 41 finished with value: 0.5869211510727717 and parameters: {'l1_ratio': 0.07882784157474285}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:45:59,660] Trial 42 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.18301650200972253}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:00,199] Trial 43 finished with value: 0.5920135336603487 and parameters: {'l1_ratio': 0.11528287580091057}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5150214592274678
[I 2024-04-16 20:46:00,520] Trial 44 finished with value: 0.585302325700295 and parameters: {'l1_ratio': 0.03986488678946942}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:00,956] Trial 45 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.18605221983423223}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:01,341] Trial 46 finished with value: 0.5944002475623498 and parameters: {'l1_ratio': 0.09101876385772517}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:01,723] Trial 47 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.28046650579224897}. Best is trial 27 with value: 0.5944002475623498.

Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5107296137339056
[I 2024-04-16 20:46:02,138] Trial 48 finished with value: 0.5844439566015824 and parameters: {'l1_ratio': 0.04703679633024381}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:02,618] Trial 49 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.22788096176860018}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:03,204] Trial 50 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.16413311765389266}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:03,921] Trial 51 finished with value: 0.5944002475623498 and parameters: {'l1_ratio': 0.09611936723058973}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5150214592274678
[I 2024-04-16 20:46:04,176] Trial 52 finished with value: 0.585302325700295 and parameters: {'l1_ratio': 0.04274857604503267}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5107296137339056
[I 2024-04-16 20:46:04,466] Trial 53 finished with value: 0.5836687628031328 and parameters: {'l1_ratio': 0.0019595416110747416}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:04,961] Trial 54 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.1107183330489164}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.51931330472103
[I 2024-04-16 20:46:05,298] Trial 55 finished with value: 0.5869211510727717 and parameters: {'l1_ratio': 0.07563444601742447}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:06,131] Trial 56 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.20169627953148936}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:06,761] Trial 57 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.24094077443392953}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:07,347] Trial 58 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.14019595152332018}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:07,858] Trial 59 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.334510595395516}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5150214592274678
[I 2024-04-16 20:46:08,562] Trial 60 finished with value: 0.585302325700295 and parameters: {'l1_ratio': 0.03681305978714}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:08,986] Trial 61 finished with value: 0.5935491837325625 and parameters: {'l1_ratio': 0.09941199468221963}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:09,431] Trial 62 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.1528237645870896}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:09,805] Trial 63 finished with value: 0.5912129965663337 and parameters: {'l1_ratio': 0.08081808581527099}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:10,523] Trial 64 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.10616723450313563}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:10,947] Trial 65 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.6463081053454892}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:11,279] Trial 66 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.40728007636814917}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5150214592274678
[I 2024-04-16 20:46:11,604] Trial 67 finished with value: 0.5860627819740591 and parameters: {'l1_ratio': 0.05622199724476742}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:12,038] Trial 68 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.137170420207394}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5150214592274678
[I 2024-04-16 20:46:12,306] Trial 69 finished with value: 0.585302325700295 and parameters: {'l1_ratio': 0.025463989235052997}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:12,714] Trial 70 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.20339640293002198}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704

Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:13,062] Trial 71 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.8048795695679376}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:13,445] Trial 72 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.5097701679279178}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:13,843] Trial 73 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.9226870321846383}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:14,223] Trial 74 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.7226528234268521}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:14,542] Trial 75 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.5770858603761275}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:15,155] Trial 76 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.7946518030337633}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:15,767] Trial 77 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.45964552198646147}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.51931330472103
[I 2024-04-16 20:46:16,089] Trial 78 finished with value: 0.5869211510727717 and parameters: {'l1_ratio': 0.06844955758604547}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:16,614] Trial 79 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.10460005447621551}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:17,022] Trial 80 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.638447622905665}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:17,435] Trial 81 finished with value: 0.5920135336603487 and parameters: {'l1_ratio': 0.12921787767703008}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:17,847] Trial 82 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.1729377212186005}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:18,298] Trial 83 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.3701177481330249}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:18,717] Trial 84 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.26163619664641685}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5150214592274678
[I 2024-04-16 20:46:19,092] Trial 85 finished with value: 0.5845271319018452 and parameters: {'l1_ratio': 0.011213378964782153}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:19,606] Trial 86 finished with value: 0.5935639212572479 and parameters: {'l1_ratio': 0.3032070880652719}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:20,063] Trial 87 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.16213216215491277}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:20,430] Trial 88 finished with value: 0.5944002475623498 and parameters: {'l1_ratio': 0.09195272329948459}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:20,805] Trial 89 finished with value: 0.5935491837325625 and parameters: {'l1_ratio': 0.1006858470692526}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5150214592274678
[I 2024-04-16 20:46:21,070] Trial 90 finished with value: 0.5860627819740591 and parameters: {'l1_ratio': 0.056229121581996014}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5150214592274678
[I 2024-04-16 20:46:21,367] Trial 91 finished with value: 0.585302325700295 and parameters: {'l1_ratio': 0.02696107240708817}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:21,826] Trial 92 finished with value: 0.5920135336603487 and parameters: {'l1_ratio': 0.1213557389401123}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:22,228] Trial 93 finished with value: 0.5944002475623498 and parameters: {'l1_ratio': 0.08718586667626041}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:22,635] Trial 94 finished with value: 0.5912129965663337 and parameters: {'l1_ratio': 0.08249504845752878}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085

Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:22,927] Trial 95 finished with value: 0.5944002475623498 and parameters: {'l1_ratio': 0.08729377807531857}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:23,432] Trial 96 finished with value: 0.5944002475623498 and parameters: {'l1_ratio': 0.08795571478518775}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5150214592274678
[I 2024-04-16 20:46:23,672] Trial 97 finished with value: 0.5860627819740591 and parameters: {'l1_ratio': 0.05766427591916664}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:24,091] Trial 98 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.14344271299972577}. Best is trial 27 with value: 0.5944002475623498.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723

[I 2024-04-16 20:46:24,542] A new study created in memory with name: no-name-846ff98a-9425-4f82-ae56-4b2a3872a9c7

Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:46:24,519] Trial 99 finished with value: 0.5927887274587983 and parameters: {'l1_ratio': 0.185149505176735}. Best is trial 27 with value: 0.5944002475623498.


* Best trial for C-index:
 FrozenTrial(number=27, state=TrialState.COMPLETE, values=[0.5944002475623498], datetime_start=datetime.datetime(2024, 4, 16, 20, 45, 53, 81355), datetime_complete=datetime.datetime(2024, 4, 16, 20, 45, 53, 344636), params={'l1_ratio': 0.09486155085202524}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=27, value=None)


* Best Score for C-index:
 0.5944002475623498

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2629880548774616
Fold 2 IBS: 0.22682971587463843
Fold 3 IBS: 0.2142744333587882
Fold 4 IBS: 0.327962657160629
Fold 5 IBS: 0.2513930257838356
[I 2024-04-16 20:46:24,998] Trial 0 finished with value: 0.25668957741107057 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.25668957741107057.
Fold 1 IBS: 0.26302002003329694
Fold 2 IBS: 0.22767668645196562
Fold 3 IBS: 0.21651169127564762
Fold 4 IBS: 0.3278383802449254
Fold 5 IBS: 0.251406650001525
[I 2024-04-16 20:46:25,396] Trial 1 finished with value: 0.25729068560147217 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.25668957741107057.
Fold 1 IBS: 0.2630228044087859
Fold 2 IBS: 0.22799841306229704
Fold 3 IBS: 0.21729913336128845
Fold 4 IBS: 0.32770092293308273
Fold 5 IBS: 0.25140262266410585
[I 2024-04-16 20:46:25,954] Trial 2 finished with value: 0.25748477928591196 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.25668957741107057.
Fold 1 IBS: 0.2629969011839375
Fold 2 IBS: 0.2269923607740189
Fold 3 IBS: 0.21474386138438825
Fold 4 IBS: 0.3279127320535322
Fold 5 IBS: 0.25139927279095103
[I 2024-04-16 20:46:26,529] Trial 3 finished with value: 0.2568090256373656 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.25668957741107057.
Fold 1 IBS: 0.2629884250413984
Fold 2 IBS: 0.22681011544494728
Fold 3 IBS: 0.21421530185608112
Fold 4 IBS: 0.3279886437216722
Fold 5 IBS: 0.25139473618773356
[I 2024-04-16 20:46:27,117] Trial 4 finished with value: 0.2566794444503665 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 4 with value: 0.2566794444503665.
Fold 1 IBS: 0.26300934903692497
Fold 2 IBS: 0.2272267073132053
Fold 3 IBS: 0.21537492292294247
Fold 4 IBS: 0.3278046166507247
Fold 5 IBS: 0.25140071272716197
[I 2024-04-16 20:46:27,736] Trial 5 finished with value: 0.2569632617301919 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 4 with value: 0.2566794444503665.
Fold 1 IBS: 0.26297969342460326
Fold 2 IBS: 0.22665543707715302
Fold 3 IBS: 0.21372002520397734
Fold 4 IBS: 0.3280624833482397
Fold 5 IBS: 0.25138910240423384
[I 2024-04-16 20:46:28,214] Trial 6 finished with value: 0.25656134829164146 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.25656134829164146.
Fold 1 IBS: 0.262998999206237
Fold 2 IBS: 0.2268401594351892
Fold 3 IBS: 0.2143056773445727
Fold 4 IBS: 0.32794884917040606
Fold 5 IBS: 0.25139211498662456
[I 2024-04-16 20:46:28,795] Trial 7 finished with value: 0.2566971600286059 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.25656134829164146.
Fold 1 IBS: 0.2630013711422091
Fold 2 IBS: 0.2271063181537017
Fold 3 IBS: 0.21505584125034605
Fold 4 IBS: 0.32793726976141
Fold 5 IBS: 0.2513900889803554
[I 2024-04-16 20:46:29,227] Trial 8 finished with value: 0.25689817785760444 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.25656134829164146.
Fold 1 IBS: 0.26300786235325674
Fold 2 IBS: 0.22730451841434826
Fold 3 IBS: 0.21557675704611517
Fold 4 IBS: 0.3278831524098338
Fold 5 IBS: 0.25139474242807236
[I 2024-04-16 20:46:29,781] Trial 9 finished with value: 0.25703340653032525 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.25656134829164146.
Fold 1 IBS: 0.2629797232324828
Fold 2 IBS: 0.2266539287462221
Fold 3 IBS: 0.21371488096731925
Fold 4 IBS: 0.32806480538049276
Fold 5 IBS: 0.2513892519624306
[I 2024-04-16 20:46:30,313] Trial 10 finished with value: 0.2565605180577895 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 10 with value: 0.2565605180577895.
Fold 1 IBS: 0.2629798281311159
Fold 2 IBS: 0.22664861987560125
Fold 3 IBS: 0.21369671424956033
Fold 4 IBS: 0.32807299420132263
Fold 5 IBS: 0.25138977907913257
[I 2024-04-16 20:46:31,276] Trial 11 finished with value: 0.25655758710734655 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 11 with value: 0.25655758710734655.
Fold 1 IBS: 0.2629798087896683
Fold 2 IBS: 0.22664959882169813
Fold 3 IBS: 0.21370007131771432
Fold 4 IBS: 0.32807148230380556
Fold 5 IBS: 0.2513896817944014
[I 2024-04-16 20:46:31,937] Trial 12 finished with value: 0.25655812860545757 and parameters: {'l1_ratio': 0.9948264745658929}. Best is trial 11 with value: 0.25655758710734655.
Fold 1 IBS: 0.24753198932537265
Fold 2 IBS: 0.23086021480500257
Fold 3 IBS: 0.2249689107325677
Fold 4 IBS: 0.24394858826813087
Fold 5 IBS: 0.2300921751699403
[I 2024-04-16 20:46:32,281] Trial 13 finished with value: 0.2354803756602028 and parameters: {'l1_ratio': 0.03152521162798527}. Best is trial 13 with value: 0.2354803756602028.
Fold 1 IBS: 0.24747780651076226
Fold 2 IBS: 0.23104206718895165
Fold 3 IBS: 0.22554359946615712
Fold 4 IBS: 0.24361481191350393
Fold 5 IBS: 0.22998410436829272
[I 2024-04-16 20:46:32,800] Trial 14 finished with value: 0.23553247788953352 and parameters: {'l1_ratio': 0.025878608232183825}. Best is trial 13 with value: 0.2354803756602028.
Fold 1 IBS: 0.24730202688616884
Fold 2 IBS: 0.23175836566020294
Fold 3 IBS: 0.22795842876158018
Fold 4 IBS: 0.24240784929980255
Fold 5 IBS: 0.2295605750697452
[I 2024-04-16 20:46:33,062] Trial 15 finished with value: 0.23579744913549994 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 13 with value: 0.2354803756602028.
Fold 1 IBS: 0.2472797428249088
Fold 2 IBS: 0.23186788913946366
Fold 3 IBS: 0.22835134850838515
Fold 4 IBS: 0.24223656822306908
Fold 5 IBS: 0.22949656145138675
[I 2024-04-16 20:46:33,325] Trial 16 finished with value: 0.23584642202944267 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 13 with value: 0.2354803756602028.
Fold 1 IBS: 0.263040934571045
Fold 2 IBS: 0.228726498871251
Fold 3 IBS: 0.21908132037392447
Fold 4 IBS: 0.32770904053113636
Fold 5 IBS: 0.25140557856290613
[I 2024-04-16 20:46:33,813] Trial 17 finished with value: 0.25799267458205255 and parameters: {'l1_ratio': 0.14266305547235703}. Best is trial 13 with value: 0.2354803756602028.
Fold 1 IBS: 0.2630466714979138
Fold 2 IBS: 0.22913561465532756
Fold 3 IBS: 0.22010969046864273
Fold 4 IBS: 0.32766630093375276
Fold 5 IBS: 0.2514104319574775
[I 2024-04-16 20:46:34,394] Trial 18 finished with value: 0.25827374190262287 and parameters: {'l1_ratio': 0.11126547615576506}. Best is trial 13 with value: 0.2354803756602028.
Fold 1 IBS: 0.2630192207380907
Fold 2 IBS: 0.22771840852185357
Fold 3 IBS: 0.21661445892074782
Fold 4 IBS: 0.3277989860439487
Fold 5 IBS: 0.25140359925806555
[I 2024-04-16 20:46:34,926] Trial 19 finished with value: 0.25731093469654126 and parameters: {'l1_ratio': 0.2772818763114183}. Best is trial 13 with value: 0.2354803756602028.
Fold 1 IBS: 0.26304866507381597
Fold 2 IBS: 0.22904819724741587
Fold 3 IBS: 0.21988742709504544
Fold 4 IBS: 0.32774844660709906
Fold 5 IBS: 0.2514179989238659
[I 2024-04-16 20:46:35,419] Trial 20 finished with value: 0.25823014698944846 and parameters: {'l1_ratio': 0.11734182114004593}. Best is trial 13 with value: 0.2354803756602028.
Fold 1 IBS: 0.24732418986546695
Fold 2 IBS: 0.23165435347168964
Fold 3 IBS: 0.22759156217712187
Fold 4 IBS: 0.2425733669295518
Fold 5 IBS: 0.22962177985773313
[I 2024-04-16 20:46:35,889] Trial 21 finished with value: 0.2357530504603127 and parameters: {'l1_ratio': 0.009107838351343097}. Best is trial 13 with value: 0.2354803756602028.
Fold 1 IBS: 0.2478001034948882
Fold 2 IBS: 0.23012566269456705
Fold 3 IBS: 0.22278043467426153
Fold 4 IBS: 0.24543462921613937
Fold 5 IBS: 0.23052906565248021
[I 2024-04-16 20:46:36,240] Trial 22 finished with value: 0.23533397914646725 and parameters: {'l1_ratio': 0.05848653776400227}. Best is trial 22 with value: 0.23533397914646725.
Fold 1 IBS: 0.2630326345217701
Fold 2 IBS: 0.2283631607710481
Fold 3 IBS: 0.21818773169715477
Fold 4 IBS: 0.32770293197931266
Fold 5 IBS: 0.25141447797813
[I 2024-04-16 20:46:36,910] Trial 23 finished with value: 0.2577401873894831 and parameters: {'l1_ratio': 0.1786700635484893}. Best is trial 22 with value: 0.23533397914646725.
Fold 1 IBS: 0.24802856034427975
Fold 2 IBS: 0.22964468717330686
Fold 3 IBS: 0.22144521228344152
Fold 4 IBS: 0.2465532694579848
Fold 5 IBS: 0.25142116492904776
[I 2024-04-16 20:46:37,425] Trial 24 finished with value: 0.23941857883761214 and parameters: {'l1_ratio': 0.08102617470701373}. Best is trial 22 with value: 0.23533397914646725.
Fold 1 IBS: 0.26301478877700024
Fold 2 IBS: 0.22745703043364518
Fold 3 IBS: 0.21596484554596115

Fold 4 IBS: 0.32788853340548396
Fold 5 IBS: 0.2514031546088697
[I 2024-04-16 20:46:37,886] Trial 25 finished with value: 0.2571456705541921 and parameters: {'l1_ratio': 0.3418550839715946}. Best is trial 22 with value: 0.23533397914646725.
Fold 1 IBS: 0.26303018415882823
Fold 2 IBS: 0.22806664574073263
Fold 3 IBS: 0.21746526829451152
Fold 4 IBS: 0.32780607199164796
Fold 5 IBS: 0.25141701260574734
[I 2024-04-16 20:46:38,263] Trial 26 finished with value: 0.25755703655829354 and parameters: {'l1_ratio': 0.2166744240378211}. Best is trial 22 with value: 0.23533397914646725.
Fold 1 IBS: 0.24782330213255813
Fold 2 IBS: 0.23007189637973702
Fold 3 IBS: 0.22262771839375373
Fold 4 IBS: 0.24555328608314733
Fold 5 IBS: 0.23056099091292143
[I 2024-04-16 20:46:38,596] Trial 27 finished with value: 0.23532743878042353 and parameters: {'l1_ratio': 0.0607792618006927}. Best is trial 27 with value: 0.23532743878042353.
Fold 1 IBS: 0.24805481376325186
Fold 2 IBS: 0.22959547812194095
Fold 3 IBS: 0.221312268181628
Fold 4 IBS: 0.24667555229694696
Fold 5 IBS: 0.2514259205380711
[I 2024-04-16 20:46:39,094] Trial 28 finished with value: 0.23941280658036773 and parameters: {'l1_ratio': 0.0836222256104937}. Best is trial 27 with value: 0.23532743878042353.
Fold 1 IBS: 0.26303206467405954
Fold 2 IBS: 0.22839040571971275
Fold 3 IBS: 0.21825430836527546
Fold 4 IBS: 0.327677310829402
Fold 5 IBS: 0.25141243634439353
[I 2024-04-16 20:46:39,607] Trial 29 finished with value: 0.25775330518656864 and parameters: {'l1_ratio': 0.17562236909721204}. Best is trial 27 with value: 0.23532743878042353.
Fold 1 IBS: 0.26299813077288253
Fold 2 IBS: 0.22688959422060875
Fold 3 IBS: 0.21445130045385355
Fold 4 IBS: 0.32788377819563946
Fold 5 IBS: 0.25138780440602404
[I 2024-04-16 20:46:40,061] Trial 30 finished with value: 0.2567221216098017 and parameters: {'l1_ratio': 0.6348147138790865}. Best is trial 27 with value: 0.23532743878042353.
Fold 1 IBS: 0.24794602447981415
Fold 2 IBS: 0.2298068686871201
Fold 3 IBS: 0.2218879471974469
Fold 4 IBS: 0.2461610774382708
Fold 5 IBS: 0.23071807173235295
[I 2024-04-16 20:46:40,339] Trial 31 finished with value: 0.235303997907001 and parameters: {'l1_ratio': 0.07288162120739637}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.24793010404198648
Fold 2 IBS: 0.22983954773532608
Fold 3 IBS: 0.22197804111525288
Fold 4 IBS: 0.24608398322843597
Fold 5 IBS: 0.23069873356021717
[I 2024-04-16 20:46:40,705] Trial 32 finished with value: 0.23530608193624372 and parameters: {'l1_ratio': 0.0713123037303855}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.263012687464334
Fold 2 IBS: 0.2275661255622394
Fold 3 IBS: 0.21623784524201983
Fold 4 IBS: 0.32778139290200237
Fold 5 IBS: 0.25139494853587196
[I 2024-04-16 20:46:41,098] Trial 33 finished with value: 0.2571985999412935 and parameters: {'l1_ratio': 0.3122062236031381}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.2630300515867043
Fold 2 IBS: 0.22807354902517543
Fold 3 IBS: 0.21748207180629878
Fold 4 IBS: 0.3277998410842084
Fold 5 IBS: 0.25141652448399515
[I 2024-04-16 20:46:41,488] Trial 34 finished with value: 0.25756040759727644 and parameters: {'l1_ratio': 0.21567299652629962}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.24792434673113184
Fold 2 IBS: 0.22985148312735562
Fold 3 IBS: 0.22201102246210613
Fold 4 IBS: 0.2460559821696822
Fold 5 IBS: 0.23069166825672954
[I 2024-04-16 20:46:41,747] Trial 35 finished with value: 0.23530690054940107 and parameters: {'l1_ratio': 0.07074483679648741}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.2630259728049693
Fold 2 IBS: 0.2278361057215406
Fold 3 IBS: 0.2169031010744098
Fold 4 IBS: 0.3278520967300719
Fold 5 IBS: 0.2514144350307972
[I 2024-04-16 20:46:42,147] Trial 36 finished with value: 0.25740634227235776 and parameters: {'l1_ratio': 0.2542776170314243}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.2629904885054971
Fold 2 IBS: 0.22670288572748523
Fold 3 IBS: 0.2138782722750588
Fold 4 IBS: 0.3279903515555356
Fold 5 IBS: 0.2513844371028539
[I 2024-04-16 20:46:42,497] Trial 37 finished with value: 0.2565892870332861 and parameters: {'l1_ratio': 0.8808567522730943}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.26303129731760805
Fold 2 IBS: 0.22842633293240025
Fold 3 IBS: 0.2183421838487697
Fold 4 IBS: 0.32781347299152414
Fold 5 IBS: 0.25140969656040807
[I 2024-04-16 20:46:43,104] Trial 38 finished with value: 0.257804596730142 and parameters: {'l1_ratio': 0.17170042221189982}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.2630450159674505
Fold 2 IBS: 0.22888527208124418
Fold 3 IBS: 0.21947702088560153
Fold 4 IBS: 0.32773180504715427
Fold 5 IBS: 0.2514122530450349
[I 2024-04-16 20:46:43,610] Trial 39 finished with value: 0.2581102734052971 and parameters: {'l1_ratio': 0.12953444692515192}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.2630069189798648
Fold 2 IBS: 0.22735296604440342
Fold 3 IBS: 0.2157010068827694
Fold 4 IBS: 0.32783313975538597
Fold 5 IBS: 0.2513909568771458
[I 2024-04-16 20:46:44,011] Trial 40 finished with value: 0.25705699770791385 and parameters: {'l1_ratio': 0.3748636960351222}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.24787048158148867
Fold 2 IBS: 0.2299663133366955
Fold 3 IBS: 0.2223304697531824
Fold 4 IBS: 0.24579074586380678
Fold 5 IBS: 0.23062363253877444
[I 2024-04-16 20:46:44,293] Trial 41 finished with value: 0.23531632861478954 and parameters: {'l1_ratio': 0.06543501261859518}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.24792200882461782
Fold 2 IBS: 0.22985634789256457
Fold 3 IBS: 0.22202447717460358
Fold 4 IBS: 0.2460445929462506
Fold 5 IBS: 0.23068878813815924
[I 2024-04-16 20:46:44,591] Trial 42 finished with value: 0.23530724299523914 and parameters: {'l1_ratio': 0.07051440565341696}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.2630538112978838
Fold 2 IBS: 0.2294204217732412
Fold 3 IBS: 0.22084525122062543
Fold 4 IBS: 0.24712380065380887
Fold 5 IBS: 0.25142346106201985
[I 2024-04-16 20:46:44,981] Trial 43 finished with value: 0.24237334920151588 and parameters: {'l1_ratio': 0.0933793079352931}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.2630328451698033
Fold 2 IBS: 0.22835296473025773
Fold 3 IBS: 0.21816282914453694
Fold 4 IBS: 0.3277124391398751
Fold 5 IBS: 0.25141523422101275
[I 2024-04-16 20:46:45,325] Trial 44 finished with value: 0.2577352624810972 and parameters: {'l1_ratio': 0.17982744894639163}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.2630034257211958
Fold 2 IBS: 0.22705647674021215
Fold 3 IBS: 0.2149207631881634
Fold 4 IBS: 0.32783621896185905
Fold 5 IBS: 0.25139412732722016
[I 2024-04-16 20:46:45,830] Trial 45 finished with value: 0.25684220238773015 and parameters: {'l1_ratio': 0.5094973989214552}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.2629898025439599
Fold 2 IBS: 0.22674004621397598
Fold 3 IBS: 0.21399793036695344
Fold 4 IBS: 0.32793489208373966
Fold 5 IBS: 0.2513808245907843
[I 2024-04-16 20:46:46,275] Trial 46 finished with value: 0.25660869915988266 and parameters: {'l1_ratio': 0.8167652444349325}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.26302438736769895
Fold 2 IBS: 0.22791921309442573
Fold 3 IBS: 0.21710608899368314
Fold 4 IBS: 0.32777584703047014
Fold 5 IBS: 0.25140849584959524
[I 2024-04-16 20:46:46,670] Trial 47 finished with value: 0.25744680646717466 and parameters: {'l1_ratio': 0.23971145636476637}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.24771693191533264
Fold 2 IBS: 0.23032951505194804
Fold 3 IBS: 0.2233681133852637
Fold 4 IBS: 0.24499790837470964
Fold 5 IBS: 0.2304079091756293
[I 2024-04-16 20:46:46,972] Trial 48 finished with value: 0.23536407558057665 and parameters: {'l1_ratio': 0.05023478512873891}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.2630402123688535
Fold 2 IBS: 0.22875984336197866
Fold 3 IBS: 0.21916410879912776
Fold 4 IBS: 0.3276776900009187
Fold 5 IBS: 0.25142226806138523
[I 2024-04-16 20:46:47,300] Trial 49 finished with value: 0.2580128245184528 and parameters: {'l1_ratio': 0.1397932584741205}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.2629972950149041
Fold 2 IBS: 0.22693646191236325
Fold 3 IBS: 0.2145862663295694

Fold 4 IBS: 0.32797944019122877
Fold 5 IBS: 0.25138371061424253
[I 2024-04-16 20:46:47,646] Trial 50 finished with value: 0.2567766348124616 and parameters: {'l1_ratio': 0.5938078108685914}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.24768341105530375
Fold 2 IBS: 0.23041707644787301
Fold 3 IBS: 0.2236249361762146
Fold 4 IBS: 0.24481640722812334
Fold 5 IBS: 0.23035582265336363
[I 2024-04-16 20:46:47,951] Trial 51 finished with value: 0.23537953071217568 and parameters: {'l1_ratio': 0.04688889313970372}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.24806550919882117
Fold 2 IBS: 0.22957573980711704
Fold 3 IBS: 0.22125911791840489
Fold 4 IBS: 0.2467250479679731
Fold 5 IBS: 0.2514277712699898
[I 2024-04-16 20:46:48,245] Trial 52 finished with value: 0.2394106372324612 and parameters: {'l1_ratio': 0.08468086971959793}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.24774714762624245
Fold 2 IBS: 0.23025334582028947
Fold 3 IBS: 0.22314688637751195
Fold 4 IBS: 0.24515871515797905
Fold 5 IBS: 0.23045320270425984
[I 2024-04-16 20:46:48,498] Trial 53 finished with value: 0.23535185953725657 and parameters: {'l1_ratio': 0.05323965232957835}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.2630352181134238
Fold 2 IBS: 0.22862613627681316
Fold 3 IBS: 0.21883304288858238
Fold 4 IBS: 0.32780048314121113
Fold 5 IBS: 0.2514136691431565
[I 2024-04-16 20:46:49,522] Trial 54 finished with value: 0.25794170991263743 and parameters: {'l1_ratio': 0.1516975057896684}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.2473012638250201
Fold 2 IBS: 0.23176203612597351
Fold 3 IBS: 0.22797148303675638
Fold 4 IBS: 0.24240206424479907
Fold 5 IBS: 0.22955841751005676
[I 2024-04-16 20:46:49,939] Trial 55 finished with value: 0.23579905294852116 and parameters: {'l1_ratio': 0.006463941886365759}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.263029242848411
Fold 2 IBS: 0.2281150524057652
Fold 3 IBS: 0.2175830899184043
Fold 4 IBS: 0.32776213383232194
Fold 5 IBS: 0.2514135548144256
[I 2024-04-16 20:46:50,599] Trial 56 finished with value: 0.2575806147638656 and parameters: {'l1_ratio': 0.20978379635815708}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.2630455569852055
Fold 2 IBS: 0.22918212301599292
Fold 3 IBS: 0.2202285746834912
Fold 4 IBS: 0.32779156451282904
Fold 5 IBS: 0.25142556735914245
[I 2024-04-16 20:46:51,177] Trial 57 finished with value: 0.25833467731133225 and parameters: {'l1_ratio': 0.10815312472006447}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.24784897407834147
Fold 2 IBS: 0.23001383847188173
Fold 3 IBS: 0.22246384007502448
Fold 4 IBS: 0.2456831182983189
Fold 5 IBS: 0.23059544530148252
[I 2024-04-16 20:46:51,793] Trial 58 finished with value: 0.23532104324500983 and parameters: {'l1_ratio': 0.06331353702036904}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.2630460428565787
Fold 2 IBS: 0.22916206941827713
Fold 3 IBS: 0.2201772583254676
Fold 4 IBS: 0.3276398673376956
Fold 5 IBS: 0.25142722749890484
[I 2024-04-16 20:46:52,219] Trial 59 finished with value: 0.2582904930873848 and parameters: {'l1_ratio': 0.10948521962551908}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.24753885061805558
Fold 2 IBS: 0.23083818031117648
Fold 3 IBS: 0.22490023518148713
Fold 4 IBS: 0.24398986775165366
Fold 5 IBS: 0.23010527793778668
[I 2024-04-16 20:46:52,565] Trial 60 finished with value: 0.23547448236003188 and parameters: {'l1_ratio': 0.03223330916452351}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.24793403955034168
Fold 2 IBS: 0.22983142530085843
Fold 3 IBS: 0.22195561962612162
Fold 4 IBS: 0.2461030864640244
Fold 5 IBS: 0.23070354100833212
[I 2024-04-16 20:46:53,056] Trial 61 finished with value: 0.23530554238993567 and parameters: {'l1_ratio': 0.07170021612591407}. Best is trial 31 with value: 0.235303997907001.
Fold 1 IBS: 0.24796793290102478
Fold 2 IBS: 0.22976266088244296
Fold 3 IBS: 0.22176654980504856
Fold 4 IBS: 0.24626638038167636
Fold 5 IBS: 0.2307442160849793
[I 2024-04-16 20:46:53,290] Trial 62 finished with value: 0.23530154801103437 and parameters: {'l1_ratio': 0.07504174750370471}. Best is trial 62 with value: 0.23530154801103437.
Fold 1 IBS: 0.24724805543478978
Fold 2 IBS: 0.232034659996766
Fold 3 IBS: 0.22896245414934355
Fold 4 IBS: 0.24198261769124407
Fold 5 IBS: 0.22939864528875728
[I 2024-04-16 20:46:53,546] Trial 63 finished with value: 0.23592528651218014 and parameters: {'l1_ratio': 0.00011705527292023288}. Best is trial 62 with value: 0.23530154801103437.
Fold 1 IBS: 0.2630402032306678
Fold 2 IBS: 0.22876026010500808
Fold 3 IBS: 0.2191651445030499
Fold 4 IBS: 0.32767729321256145
Fold 5 IBS: 0.25142223610330805
[I 2024-04-16 20:46:54,061] Trial 64 finished with value: 0.25801302743091903 and parameters: {'l1_ratio': 0.13975778729410046}. Best is trial 62 with value: 0.23530154801103437.
Fold 1 IBS: 0.2630097567661121
Fold 2 IBS: 0.22720470856452385
Fold 3 IBS: 0.21531728560847635
Fold 4 IBS: 0.32782900076130533
Fold 5 IBS: 0.25140237824652495
[I 2024-04-16 20:46:54,455] Trial 65 finished with value: 0.2569526259893885 and parameters: {'l1_ratio': 0.43274160768176895}. Best is trial 62 with value: 0.23530154801103437.
Fold 1 IBS: 0.26305307315549925
Fold 2 IBS: 0.22945032670371104
Fold 3 IBS: 0.2209236783470748
Fold 4 IBS: 0.24704571199888534
Fold 5 IBS: 0.2514207218306402
[I 2024-04-16 20:46:54,826] Trial 66 finished with value: 0.24237870240716214 and parameters: {'l1_ratio': 0.09165168553926804}. Best is trial 62 with value: 0.23530154801103437.
Fold 1 IBS: 0.2630353274623186
Fold 2 IBS: 0.22822809242951342
Fold 3 IBS: 0.21785830413588778
Fold 4 IBS: 0.32782534239473093
Fold 5 IBS: 0.2514051459320867
[I 2024-04-16 20:46:55,331] Trial 67 finished with value: 0.2576704424709075 and parameters: {'l1_ratio': 0.1948010498627496}. Best is trial 62 with value: 0.23530154801103437.
Fold 1 IBS: 0.2630176447180584
Fold 2 IBS: 0.2277980084054719
Fold 3 IBS: 0.21680984660868785
Fold 4 IBS: 0.32772215290811113
Fold 5 IBS: 0.2513976302727721
[I 2024-04-16 20:46:55,969] Trial 68 finished with value: 0.25734905658262025 and parameters: {'l1_ratio': 0.2613968055636199}. Best is trial 62 with value: 0.23530154801103437.
Fold 1 IBS: 0.2630207161667273
Fold 2 IBS: 0.22763958472563323
Fold 3 IBS: 0.21642006018571908
Fold 4 IBS: 0.32787310066005404
Fold 5 IBS: 0.2514093203232039
[I 2024-04-16 20:46:56,474] Trial 69 finished with value: 0.25727255641226754 and parameters: {'l1_ratio': 0.2945361288002137}. Best is trial 62 with value: 0.23530154801103437.
Fold 1 IBS: 0.2630367922938966
Fold 2 IBS: 0.22855350658020399
Fold 3 IBS: 0.2186541385797114
Fold 4 IBS: 0.32769819035065056
Fold 5 IBS: 0.2514192249227546
[I 2024-04-16 20:46:56,871] Trial 70 finished with value: 0.25787237054544343 and parameters: {'l1_ratio': 0.15863691984382644}. Best is trial 62 with value: 0.23530154801103437.
Fold 1 IBS: 0.2478775621927116
Fold 2 IBS: 0.22995088236416208
Fold 3 IBS: 0.22228731368457655
Fold 4 IBS: 0.2458259576420574
Fold 5 IBS: 0.23063278122661487
[I 2024-04-16 20:46:57,212] Trial 71 finished with value: 0.2353148994220245 and parameters: {'l1_ratio': 0.06613319158063015}. Best is trial 62 with value: 0.23530154801103437.
Fold 1 IBS: 0.24752540010723115
Fold 2 IBS: 0.23088157610931428
Fold 3 IBS: 0.2250356823581577
Fold 4 IBS: 0.24390874603591367
Fold 5 IBS: 0.23007947414313745
[I 2024-04-16 20:46:57,554] Trial 72 finished with value: 0.23548617575075087 and parameters: {'l1_ratio': 0.030843832568305835}. Best is trial 62 with value: 0.23530154801103437.
Fold 1 IBS: 0.24797616358730273
Fold 2 IBS: 0.22974627508261827
Fold 3 IBS: 0.2217216917758899
Fold 4 IBS: 0.24630571111533525
Fold 5 IBS: 0.23075390167727003
[I 2024-04-16 20:46:57,837] Trial 73 finished with value: 0.23530074864768324 and parameters: {'l1_ratio': 0.07585352244108706}. Best is trial 73 with value: 0.23530074864768324.
Fold 1 IBS: 0.26304248705085276
Fold 2 IBS: 0.2289976056049314
Fold 3 IBS: 0.21975947317383213
Fold 4 IBS: 0.32779527689783966
Fold 5 IBS: 0.2514221694024328
[I 2024-04-16 20:46:58,238] Trial 74 finished with value: 0.2582034024259777 and parameters: {'l1_ratio': 0.12100151681304275}. Best is trial 73 with value: 0.23530074864768324.
Fold 1 IBS: 0.2480144603609062
Fold 2 IBS: 0.2296715727758492
Fold 3 IBS: 0.2215181144501606
Fold 4 IBS: 0.2464871202003832

Fold 5 IBS: 0.23079802205404368
[I 2024-04-16 20:46:58,476] Trial 75 finished with value: 0.23529785796826858 and parameters: {'l1_ratio': 0.07963322397579652}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.26305036827463507
Fold 2 IBS: 0.2292795705291077
Fold 3 IBS: 0.22047917914446627
Fold 4 IBS: 0.24750047636825534
Fold 5 IBS: 0.2514171371521248
[I 2024-04-16 20:46:58,783] Trial 76 finished with value: 0.24234534629371782 and parameters: {'l1_ratio': 0.1018844983216041}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.24752688572810783
Fold 2 IBS: 0.23087674258361573
Fold 3 IBS: 0.22502055681147848
Fold 4 IBS: 0.24391774622739776
Fold 5 IBS: 0.23008234793739007
[I 2024-04-16 20:46:59,107] Trial 77 finished with value: 0.23548485585759799 and parameters: {'l1_ratio': 0.030997576498634}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.2630449068239805
Fold 2 IBS: 0.22889032661881023
Fold 3 IBS: 0.2194896832312748
Fold 4 IBS: 0.3277270794526336
Fold 5 IBS: 0.251411832014967
[I 2024-04-16 20:46:59,465] Trial 78 finished with value: 0.25811276562833324 and parameters: {'l1_ratio': 0.1291377986320492}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.2630350728109428
Fold 2 IBS: 0.22824082590700798
Fold 3 IBS: 0.2178893252790341
Fold 4 IBS: 0.3278140970860882
Fold 5 IBS: 0.25140416772933544
[I 2024-04-16 20:46:59,875] Trial 79 finished with value: 0.2576766977624817 and parameters: {'l1_ratio': 0.19320273255552045}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.24798811706885157
Fold 2 IBS: 0.22972268929902606
Fold 3 IBS: 0.22165725268316458
Fold 4 IBS: 0.2463626125089542
Fold 5 IBS: 0.23076783829786213
[I 2024-04-16 20:47:00,135] Trial 80 finished with value: 0.23529970197157174 and parameters: {'l1_ratio': 0.07703277581569166}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.2630514511089211
Fold 2 IBS: 0.22951414239728574
Fold 3 IBS: 0.22109388234972782
Fold 4 IBS: 0.24688119079743356
Fold 5 IBS: 0.25141464545893427
[I 2024-04-16 20:47:00,471] Trial 81 finished with value: 0.2423910624224605 and parameters: {'l1_ratio': 0.08805067995123356}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.24749326097275398
Fold 2 IBS: 0.2309887119299565
Fold 3 IBS: 0.22537350134336837
Fold 4 IBS: 0.24371148779171156
Fold 5 IBS: 0.23001579799629618
[I 2024-04-16 20:47:00,699] Trial 82 finished with value: 0.2355165520068173 and parameters: {'l1_ratio': 0.02749983656210852}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.24793907337897994
Fold 2 IBS: 0.22982107855821915
Fold 3 IBS: 0.22192708542031686
Fold 4 IBS: 0.2461274771491694
Fold 5 IBS: 0.2307096640968407
[I 2024-04-16 20:47:00,945] Trial 83 finished with value: 0.23530487572070524 and parameters: {'l1_ratio': 0.07219640439074182}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.26304813417031214
Fold 2 IBS: 0.22907173727430655
Fold 3 IBS: 0.2199471299636032
Fold 4 IBS: 0.32772834866339673
Fold 5 IBS: 0.251416007467663
[I 2024-04-16 20:47:01,319] Trial 84 finished with value: 0.25824227150785634 and parameters: {'l1_ratio': 0.11567547433627133}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.2630361441373217
Fold 2 IBS: 0.22858386010135456
Fold 3 IBS: 0.21872883397421802
Fold 4 IBS: 0.3276695776128904
Fold 5 IBS: 0.25141693217071437
[I 2024-04-16 20:47:01,763] Trial 85 finished with value: 0.25788706959929975 and parameters: {'l1_ratio': 0.15569352404495507}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.24768736979475797
Fold 2 IBS: 0.2304065605489389
Fold 3 IBS: 0.22359394800791088
Fold 4 IBS: 0.24483801940811648
Fold 5 IBS: 0.23036207893627222
[I 2024-04-16 20:47:02,016] Trial 86 finished with value: 0.23537759533919927 and parameters: {'l1_ratio': 0.04728480024208365}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.24800535269612856
Fold 2 IBS: 0.22968911320600421
Fold 3 IBS: 0.22156577999954621
Fold 4 IBS: 0.24644421048161172
Fold 5 IBS: 0.23078766786675298
[I 2024-04-16 20:47:02,252] Trial 87 finished with value: 0.23529842485000874 and parameters: {'l1_ratio': 0.07873389471608488}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.2473943462115269
Fold 2 IBS: 0.23135399527896114
Fold 3 IBS: 0.22656403513530277
Fold 4 IBS: 0.24306927069332457
Fold 5 IBS: 0.22979914561726517
[I 2024-04-16 20:47:02,477] Trial 88 finished with value: 0.2356361585872761 and parameters: {'l1_ratio': 0.01693970908175991}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.26305126572379106
Fold 2 IBS: 0.22952119832539547
Fold 3 IBS: 0.22111276212014272
Fold 4 IBS: 0.24686317393536908
Fold 5 IBS: 0.25141395346205014
[I 2024-04-16 20:47:02,737] Trial 89 finished with value: 0.2423924707133497 and parameters: {'l1_ratio': 0.08765949152378154}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.2629883324194218
Fold 2 IBS: 0.22681502989633667
Fold 3 IBS: 0.2142301901597254
Fold 4 IBS: 0.32798211866946597
Fold 5 IBS: 0.2513943071726766
[I 2024-04-16 20:47:03,214] Trial 90 finished with value: 0.2566819956635253 and parameters: {'l1_ratio': 0.7135825642664739}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.2479255135927689
Fold 2 IBS: 0.22984905901569183
Fold 3 IBS: 0.22200432053438615
Fold 4 IBS: 0.2460616625492923
Fold 5 IBS: 0.23069310334178544
[I 2024-04-16 20:47:03,674] Trial 91 finished with value: 0.2353067318067849 and parameters: {'l1_ratio': 0.07085984685964188}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.2630394491634222
Fold 2 IBS: 0.22879421446255951
Fold 3 IBS: 0.21924961472295473
Fold 4 IBS: 0.32764466307874973
Fold 5 IBS: 0.25141960371511773
[I 2024-04-16 20:47:04,107] Trial 92 finished with value: 0.2580295090285608 and parameters: {'l1_ratio': 0.1368997991046293}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.247629838616078
Fold 2 IBS: 0.23056431451585283
Fold 3 IBS: 0.22406307317700366
Fold 4 IBS: 0.24451895855476496
Fold 5 IBS: 0.23026821200483827
[I 2024-04-16 20:47:04,437] Trial 93 finished with value: 0.23540887937370755 and parameters: {'l1_ratio': 0.04150731484428678}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.26303916571495256
Fold 2 IBS: 0.22843722479273673
Fold 3 IBS: 0.2183688445267598
Fold 4 IBS: 0.32780386134735845
Fold 5 IBS: 0.2514088550186737
[I 2024-04-16 20:47:05,121] Trial 94 finished with value: 0.25781159028009626 and parameters: {'l1_ratio': 0.1705325412860763}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.24800610467414114
Fold 2 IBS: 0.2296876597367941
Fold 3 IBS: 0.22156182711818026
Fold 4 IBS: 0.24644775868999005
Fold 5 IBS: 0.2307885259865012
[I 2024-04-16 20:47:05,451] Trial 95 finished with value: 0.23529837524112135 and parameters: {'l1_ratio': 0.07880813642065213}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.26304375091148857
Fold 2 IBS: 0.2289426902460557
Fold 3 IBS: 0.21962111667472575
Fold 4 IBS: 0.32767731262938243
Fold 5 IBS: 0.2514073855166556
[I 2024-04-16 20:47:06,283] Trial 96 finished with value: 0.2581384511956616 and parameters: {'l1_ratio': 0.12510035862637714}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.2630488710327112
Fold 2 IBS: 0.22934101439130686
Fold 3 IBS: 0.22063829356453069
Fold 4 IBS: 0.24733432035069236
Fold 5 IBS: 0.25141148971500854
[I 2024-04-16 20:47:06,832] Trial 97 finished with value: 0.24235479781084993 and parameters: {'l1_ratio': 0.0980972211864742}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.26298917711071784
Fold 2 IBS: 0.22677372662266196
Fold 3 IBS: 0.2141036262007801
Fold 4 IBS: 0.32788633234250836
Fold 5 IBS: 0.25139791797908645
[I 2024-04-16 20:47:07,360] Trial 98 finished with value: 0.2566301560511509 and parameters: {'l1_ratio': 0.7667338152719219}. Best is trial 75 with value: 0.23529785796826858.
Fold 1 IBS: 0.24725743349826912
Fold 2 IBS: 0.23198399630965136
Fold 3 IBS: 0.22877505045923216
Fold 4 IBS: 0.2420590457685721
Fold 5 IBS: 0.22942829192780612
[I 2024-04-16 20:47:07,646] Trial 99 finished with value: 0.23590076359270618 and parameters: {'l1_ratio': 0.0012603444274974784}. Best is trial 75 with value: 0.23529785796826858.


* Best trial for IBS:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.23529785796826858], datetime_start=datetime.datetime(2024, 4, 16, 20, 46, 58, 246245), datetime_complete=datetime.datetime(2024, 4, 16, 20, 46, 58, 476330), params={'l1_ratio': 0.07963322397579652}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=75, value=None)


* Best Score for IBS:
 0.23529785796826858

In [88]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [89]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.594
train_ibs:  0.235

#### Test

In [90]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [91]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.09486155085202524)

test_cindex : 0.568

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.07963322397579652)

test_ibs:  0.227

In [92]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [93]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:47:07,927] A new study created in memory with name: no-name-209d5f97-9322-4d32-bef7-20e26ed0b162

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.46215139442231074
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.4448669201520912
Fold 5 C-index: 0.49356223175965663
[I 2024-04-16 20:47:12,932] Trial 0 finished with value: 0.5602876415115751 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.5602876415115751.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.4144486692015209
Fold 5 C-index: 0.4678111587982833
[I 2024-04-16 20:47:16,627] Trial 1 finished with value: 0.5468154859536443 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.5602876415115751.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.4372623574144487
Fold 5 C-index: 0.4592274678111588
[I 2024-04-16 20:47:19,092] Trial 2 finished with value: 0.5421426378137205 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.5602876415115751.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:47:19,971] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.5602876415115751.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:47:21,071] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.5602876415115751.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5236051502145923
[I 2024-04-16 20:47:24,611] Trial 5 finished with value: 0.5723472035859377 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.5723472035859377.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.41825095057034223
Fold 5 C-index: 0.463519313304721
[I 2024-04-16 20:47:28,711] Trial 6 finished with value: 0.5518994187299625 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.5723472035859377.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:47:30,682] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.5723472035859377.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.4678111587982833
[I 2024-04-16 20:47:36,194] Trial 8 finished with value: 0.49356223175965663 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.5723472035859377.
Fold 1 C-index: 0.4581673306772908
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.38022813688212925
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:47:39,250] Trial 9 finished with value: 0.5731946423379088 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 9 with value: 0.5731946423379088.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:47:39,595] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.9610671372536813, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 9 with value: 0.5731946423379088.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.4524714828897338
Fold 5 C-index: 0.4291845493562232
[I 2024-04-16 20:47:40,841] Trial 11 finished with value: 0.5654935411118602 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 109, 'oob_score': False, 'max_samples': 0.11379276107227315, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018098423978521135, 'warm_start': False}. Best is trial 9 with value: 0.5731946423379088.
Fold 1 C-index: 0.4302788844621514
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5021459227467812
[I 2024-04-16 20:47:46,002] Trial 12 finished with value: 0.5641214136743333 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 498, 'oob_score': False, 'max_samples': 0.8392165520631284, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08506650508113567, 'warm_start': False}. Best is trial 9 with value: 0.5731946423379088.
Fold 1 C-index: 0.46613545816733065
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.8
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.4570815450643777
[I 2024-04-16 20:47:49,276] Trial 13 finished with value: 0.571483380603308 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.4760095384782845, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.008606277463368957, 'warm_start': False}. Best is trial 9 with value: 0.5731946423379088.
Fold 1 C-index: 0.4302788844621514
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 20:47:50,313] Trial 14 finished with value: 0.64172665454536 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 192, 'oob_score': True, 'max_samples': 0.7873021337102564, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1584235940276062, 'warm_start': True}. Best is trial 14 with value: 0.64172665454536.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.7403100775193798

Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 20:47:51,563] Trial 15 finished with value: 0.6480653508920432 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.8107341403225247, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16866630138034366, 'warm_start': True}. Best is trial 15 with value: 0.6480653508920432.
Fold 1 C-index: 0.46215139442231074
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.5836909871244635
[I 2024-04-16 20:47:52,791] Trial 16 finished with value: 0.6522634317487244 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.8029947290400248, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16939069998793121, 'warm_start': True}. Best is trial 16 with value: 0.6522634317487244.
Fold 1 C-index: 0.4581673306772908
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 20:47:54,099] Trial 17 finished with value: 0.6574745261453319 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 110, 'oob_score': True, 'max_samples': 0.8260002438359659, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20020395152945147, 'warm_start': True}. Best is trial 17 with value: 0.6574745261453319.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.7577519379844961
Fold 3 C-index: 0.8276595744680851
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.5686695278969958
[I 2024-04-16 20:47:54,501] Trial 18 finished with value: 0.6476007808055887 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 23, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 17 with value: 0.6574745261453319.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:47:55,904] Trial 19 finished with value: 0.6455954616897793 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 111, 'oob_score': True, 'max_samples': 0.7105420171094243, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21389275171746558, 'warm_start': True}. Best is trial 17 with value: 0.6574745261453319.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7267441860465116
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.5450643776824035
[I 2024-04-16 20:47:57,088] Trial 20 finished with value: 0.6292088850145593 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 120, 'oob_score': True, 'max_samples': 0.8687890539992851, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.40986407643825334, 'warm_start': True}. Best is trial 17 with value: 0.6574745261453319.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 20:47:58,315] Trial 21 finished with value: 0.6603064481769213 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 143, 'oob_score': True, 'max_samples': 0.8202382878015702, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1580984841046789, 'warm_start': True}. Best is trial 21 with value: 0.6603064481769213.
Fold 1 C-index: 0.4701195219123506
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.5386266094420601
[I 2024-04-16 20:47:58,775] Trial 22 finished with value: 0.6399801463502265 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 66, 'oob_score': True, 'max_samples': 0.6889849263379537, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20801284204453765, 'warm_start': True}. Best is trial 21 with value: 0.6603064481769213.
Fold 1 C-index: 0.4262948207171315
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.5965665236051502
[I 2024-04-16 20:47:59,630] Trial 23 finished with value: 0.6524996022065694 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 146, 'oob_score': True, 'max_samples': 0.5177579675071187, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11355950251192917, 'warm_start': True}. Best is trial 21 with value: 0.6603064481769213.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 20:48:00,534] Trial 24 finished with value: 0.6643709375501405 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 147, 'oob_score': True, 'max_samples': 0.49435111928536146, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1078239513863242, 'warm_start': True}. Best is trial 24 with value: 0.6643709375501405.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.5515021459227468
[I 2024-04-16 20:48:01,721] Trial 25 finished with value: 0.6384552390497558 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 232, 'oob_score': True, 'max_samples': 0.3656484979934084, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10417637838870025, 'warm_start': True}. Best is trial 24 with value: 0.6643709375501405.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6437768240343348
[I 2024-04-16 20:48:02,326] Trial 26 finished with value: 0.6863803462306775 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 82, 'oob_score': True, 'max_samples': 0.39546158937115405, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07021954285463353, 'warm_start': True}. Best is trial 26 with value: 0.6863803462306775.
Fold 1 C-index: 0.5278884462151394
Fold 2 C-index: 0.5581395348837209
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.5836501901140685
Fold 5 C-index: 0.43991416309012876
[I 2024-04-16 20:48:02,532] Trial 27 finished with value: 0.5631950626052924 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 1, 'oob_score': True, 'max_samples': 0.4077623470554984, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08184052164443809, 'warm_start': True}. Best is trial 26 with value: 0.6863803462306775.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 20:48:03,072] Trial 28 finished with value: 0.6605802763016559 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 59, 'oob_score': True, 'max_samples': 0.2459042923186604, 'max_features': None, 'min_weight_fraction_leaf': 0.05395455134723577, 'warm_start': True}. Best is trial 26 with value: 0.6863803462306775.
Fold 1 C-index: 0.4581673306772908
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 20:48:03,561] Trial 29 finished with value: 0.6475515602944306 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 67, 'oob_score': True, 'max_samples': 0.1999438233141558, 'max_features': None, 'min_weight_fraction_leaf': 0.06203534968033171, 'warm_start': True}. Best is trial 26 with value: 0.6863803462306775.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:48:04,253] Trial 30 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.29592576068651116, 'max_features': None, 'min_weight_fraction_leaf': 0.2486312042554125, 'warm_start': True}. Best is trial 26 with value: 0.6863803462306775.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:48:05,046] Trial 31 finished with value: 0.5 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 154, 'oob_score': True, 'max_samples': 0.18146034387964277, 'max_features': None, 'min_weight_fraction_leaf': 0.12332617972097551, 'warm_start': True}. Best is trial 26 with value: 0.6863803462306775.
Fold 1 C-index: 0.46215139442231074
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:48:05,380] Trial 32 finished with value: 0.7170538619002631 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 38, 'oob_score': True, 'max_samples': 0.5393941791884725, 'max_features': None, 'min_weight_fraction_leaf': 0.06003407471915119, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.46613545816733065
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:48:05,837] Trial 33 finished with value: 0.7130308518632981 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 35, 'oob_score': True, 'max_samples': 0.5397344365523784, 'max_features': None, 'min_weight_fraction_leaf': 0.0603714886359476, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.48804780876494025
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.823404255319149
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 20:48:06,142] Trial 34 finished with value: 0.675175765880471 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 22, 'oob_score': True, 'max_samples': 0.553726627344702, 'max_features': None, 'min_weight_fraction_leaf': 0.13120649213907576, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.46215139442231074
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6266094420600858
[I 2024-04-16 20:48:06,404] Trial 35 finished with value: 0.6564275084074629 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 28, 'oob_score': True, 'max_samples': 0.5773468798726945, 'max_features': None, 'min_weight_fraction_leaf': 0.12989362805818674, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.4243027888446215
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7936170212765957
Fold 4 C-index: 0.5513307984790875
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 20:48:06,551] Trial 36 finished with value: 0.6137213663552541 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 3, 'oob_score': True, 'max_samples': 0.42328242189308535, 'max_features': None, 'min_weight_fraction_leaf': 0.04800263700084323, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 20:48:06,846] Trial 37 finished with value: 0.7049112711527757 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 34, 'oob_score': True, 'max_samples': 0.5345722911782872, 'max_features': None, 'min_weight_fraction_leaf': 0.0796559128789132, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.4701195219123506
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 20:48:07,438] Trial 38 finished with value: 0.6856078015657463 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 88, 'oob_score': True, 'max_samples': 0.6475925530300135, 'max_features': None, 'min_weight_fraction_leaf': 0.07773991701512026, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.40239043824701193
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 20:48:07,803] Trial 39 finished with value: 0.6716312438198442 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 43, 'oob_score': True, 'max_samples': 0.3660594506190667, 'max_features': None, 'min_weight_fraction_leaf': 0.03679696597977278, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 20:48:08,381] Trial 40 finished with value: 0.647058144837844 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.53791276693917, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0017034391386908862, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 20:48:09,120] Trial 41 finished with value: 0.6838662873369088 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 88, 'oob_score': True, 'max_samples': 0.6400931247005563, 'max_features': None, 'min_weight_fraction_leaf': 0.07978816959154626, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.703862660944206
[I 2024-04-16 20:48:09,597] Trial 42 finished with value: 0.7090112693151225 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 46, 'oob_score': True, 'max_samples': 0.6236464814282915, 'max_features': None, 'min_weight_fraction_leaf': 0.07603709988713517, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.46215139442231074
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 20:48:10,151] Trial 43 finished with value: 0.6826122886197229 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.44972919088882307, 'max_features': None, 'min_weight_fraction_leaf': 0.0349349830201783, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.7017167381974249
[I 2024-04-16 20:48:10,684] Trial 44 finished with value: 0.6971155299109016 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 35, 'oob_score': True, 'max_samples': 0.6015038320028853, 'max_features': None, 'min_weight_fraction_leaf': 0.06427940541496399, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.

Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6630901287553648
[I 2024-04-16 20:48:11,004] Trial 45 finished with value: 0.6873248688513826 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 27, 'oob_score': False, 'max_samples': 0.6064451897907044, 'max_features': None, 'min_weight_fraction_leaf': 0.0958295530543601, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.3973384030418251
Fold 5 C-index: 0.47639484978540775
[I 2024-04-16 20:48:11,333] Trial 46 finished with value: 0.5615452651127004 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 7, 'oob_score': True, 'max_samples': 0.6745489979984765, 'max_features': None, 'min_weight_fraction_leaf': 0.14147922592542847, 'warm_start': False}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8404255319148937
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 20:48:11,852] Trial 47 finished with value: 0.6680395190155696 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 43, 'oob_score': False, 'max_samples': 0.7583998356055779, 'max_features': None, 'min_weight_fraction_leaf': 0.022437879339570886, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.46613545816733065
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.46387832699619774
Fold 5 C-index: 0.463519313304721
[I 2024-04-16 20:48:17,003] Trial 48 finished with value: 0.5620547971635493 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.5817371337689444, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18819490906895364, 'warm_start': False}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 20:48:19,338] Trial 49 finished with value: 0.6786974232999399 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 392, 'oob_score': True, 'max_samples': 0.5110541803447978, 'max_features': None, 'min_weight_fraction_leaf': 0.05534116281520947, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7577519379844961
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:48:19,586] Trial 50 finished with value: 0.6383543476722651 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 38, 'oob_score': False, 'max_samples': 0.6305330234587775, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.24018117873543227, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.46215139442231074
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8404255319148937
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6459227467811158
[I 2024-04-16 20:48:19,741] Trial 51 finished with value: 0.6738688856066569 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 20, 'oob_score': False, 'max_samples': 0.5955713843904026, 'max_features': None, 'min_weight_fraction_leaf': 0.1007051307171976, 'warm_start': True}. Best is trial 32 with value: 0.7170538619002631.
Fold 1 C-index: 0.46215139442231074
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 20:48:20,004] Trial 52 finished with value: 0.7171224266626754 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 59, 'oob_score': False, 'max_samples': 0.7318880788621756, 'max_features': None, 'min_weight_fraction_leaf': 0.0971061603863425, 'warm_start': True}. Best is trial 52 with value: 0.7171224266626754.
Fold 1 C-index: 0.4681274900398406
Fold 2 C-index: 0.7189922480620154
Fold 3 C-index: 0.8276595744680851
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 20:48:20,322] Trial 53 finished with value: 0.637639848871468 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.738385752455452, 'max_features': None, 'min_weight_fraction_leaf': 0.2958205315103815, 'warm_start': True}. Best is trial 52 with value: 0.7171224266626754.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7296137339055794
[I 2024-04-16 20:48:20,528] Trial 54 finished with value: 0.7133998931053275 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 50, 'oob_score': False, 'max_samples': 0.6761877184994437, 'max_features': None, 'min_weight_fraction_leaf': 0.00020883364634620427, 'warm_start': True}. Best is trial 52 with value: 0.7171224266626754.
Fold 1 C-index: 0.46215139442231074
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.7296137339055794
[I 2024-04-16 20:48:20,843] Trial 55 finished with value: 0.721375309430031 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 63, 'oob_score': False, 'max_samples': 0.6786949215915352, 'max_features': None, 'min_weight_fraction_leaf': 0.003349975452982869, 'warm_start': True}. Best is trial 55 with value: 0.721375309430031.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.38783269961977185
Fold 5 C-index: 0.5236051502145923
[I 2024-04-16 20:48:21,706] Trial 56 finished with value: 0.5701601666656788 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 61, 'oob_score': False, 'max_samples': 0.6740885042711195, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014520413557970187, 'warm_start': False}. Best is trial 55 with value: 0.721375309430031.
Fold 1 C-index: 0.4701195219123506
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7381974248927039
[I 2024-04-16 20:48:22,570] Trial 57 finished with value: 0.7277738932024878 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 129, 'oob_score': False, 'max_samples': 0.7576447336742066, 'max_features': None, 'min_weight_fraction_leaf': 0.030460159965636294, 'warm_start': True}. Best is trial 57 with value: 0.7277738932024878.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 20:48:23,370] Trial 58 finished with value: 0.6808893526236636 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 175, 'oob_score': False, 'max_samples': 0.7757669381125883, 'max_features': None, 'min_weight_fraction_leaf': 0.002392193532727061, 'warm_start': True}. Best is trial 57 with value: 0.7277738932024878.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.7682403433476395
[I 2024-04-16 20:48:23,905] Trial 59 finished with value: 0.734819862262061 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8639566890699188, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.036829232855921594, 'warm_start': True}. Best is trial 59 with value: 0.734819862262061.

Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.38022813688212925
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 20:48:27,232] Trial 60 finished with value: 0.5750924522262832 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 259, 'oob_score': False, 'max_samples': 0.909670859460795, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03674922710215599, 'warm_start': False}. Best is trial 59 with value: 0.734819862262061.
Fold 1 C-index: 0.4581673306772908
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 20:48:27,814] Trial 61 finished with value: 0.6840844761527574 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.7223414702447948, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.028359311786391225, 'warm_start': True}. Best is trial 59 with value: 0.734819862262061.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 20:48:28,527] Trial 62 finished with value: 0.7559305947696051 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.8765462175821326, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04288206977120261, 'warm_start': True}. Best is trial 62 with value: 0.7559305947696051.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 20:48:29,091] Trial 63 finished with value: 0.710330499424243 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 238, 'oob_score': False, 'max_samples': 0.8807825973929057, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023015002493072027, 'warm_start': True}. Best is trial 62 with value: 0.7559305947696051.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:48:29,608] Trial 64 finished with value: 0.6452330314656874 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 15, 'n_estimators': 185, 'oob_score': False, 'max_samples': 0.9215848848253488, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04345454042541086, 'warm_start': True}. Best is trial 62 with value: 0.7559305947696051.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.948936170212766
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8326180257510729
[I 2024-04-16 20:48:30,299] Trial 65 finished with value: 0.7787250758999609 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 203, 'oob_score': False, 'max_samples': 0.8513287443654974, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0020489700870839535, 'warm_start': True}. Best is trial 65 with value: 0.7787250758999609.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:48:30,910] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 225, 'oob_score': False, 'max_samples': 0.8551082716259159, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48319510296987256, 'warm_start': True}. Best is trial 65 with value: 0.7787250758999609.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8798283261802575
[I 2024-04-16 20:48:31,636] Trial 67 finished with value: 0.7949933478441326 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 206, 'oob_score': False, 'max_samples': 0.9690961253447149, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02090126509739247, 'warm_start': True}. Best is trial 67 with value: 0.7949933478441326.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 20:48:32,380] Trial 68 finished with value: 0.7512936022394402 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 194, 'oob_score': False, 'max_samples': 0.9970105223518552, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01752182607256768, 'warm_start': True}. Best is trial 67 with value: 0.7949933478441326.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8798283261802575
[I 2024-04-16 20:48:33,147] Trial 69 finished with value: 0.7955946153651998 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 198, 'oob_score': False, 'max_samples': 0.9588194036577512, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01582541457630438, 'warm_start': True}. Best is trial 69 with value: 0.7955946153651998.
Fold 1 C-index: 0.4262948207171315
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 20:48:33,868] Trial 70 finished with value: 0.7856457730944543 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 216, 'oob_score': False, 'max_samples': 0.9601911530137701, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.020253305972566197, 'warm_start': True}. Best is trial 69 with value: 0.7955946153651998.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8755364806866953
[I 2024-04-16 20:48:34,696] Trial 71 finished with value: 0.7955330590154914 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 210, 'oob_score': False, 'max_samples': 0.9961416717566756, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.021396710188165025, 'warm_start': True}. Best is trial 69 with value: 0.7955946153651998.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 20:48:35,520] Trial 72 finished with value: 0.7987780150293701 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 207, 'oob_score': False, 'max_samples': 0.9539884889104021, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01995315636053517, 'warm_start': True}. Best is trial 72 with value: 0.7987780150293701.
Fold 1 C-index: 0.4103585657370518
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.948936170212766
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8798283261802575
[I 2024-04-16 20:48:36,310] Trial 73 finished with value: 0.7933164036247653 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.9999539225716729, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.015121062896398554, 'warm_start': True}. Best is trial 72 with value: 0.7987780150293701.
Fold 1 C-index: 0.4262948207171315
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9531914893617022
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8841201716738197
[I 2024-04-16 20:48:37,252] Trial 74 finished with value: 0.8097378318532276 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.9611523071587961, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.017704571713004463, 'warm_start': True}. Best is trial 74 with value: 0.8097378318532276.

Fold 1 C-index: 0.4063745019920319
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9531914893617022
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 20:48:38,601] Trial 75 finished with value: 0.8058369434084705 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 276, 'oob_score': False, 'max_samples': 0.9527720021749413, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.020576517528715234, 'warm_start': True}. Best is trial 74 with value: 0.8097378318532276.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9574468085106383
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 20:48:40,096] Trial 76 finished with value: 0.8145470653025784 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 295, 'oob_score': False, 'max_samples': 0.9566855419974443, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.017888337982888625, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 20:48:41,216] Trial 77 finished with value: 0.7869102505956851 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 277, 'oob_score': False, 'max_samples': 0.9483122460065925, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05087748768166325, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.4302788844621514
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9574468085106383
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 20:48:42,105] Trial 78 finished with value: 0.8129897962798103 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.9711162112248388, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01161772015047945, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.7461240310077519
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.5386266094420601
[I 2024-04-16 20:48:42,959] Trial 79 finished with value: 0.644417071254929 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 293, 'oob_score': False, 'max_samples': 0.9755740570068591, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.34696749792453063, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.35361216730038025
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 20:48:46,859] Trial 80 finished with value: 0.5666248378062315 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 328, 'oob_score': False, 'max_samples': 0.9340121927888781, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0506719215219388, 'warm_start': False}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.4262948207171315
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8841201716738197
[I 2024-04-16 20:48:47,807] Trial 81 finished with value: 0.8011326476310334 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.896129209492607, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.016526704841346083, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.948936170212766
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 20:48:48,804] Trial 82 finished with value: 0.8081515116241448 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 246, 'oob_score': False, 'max_samples': 0.8913122163528459, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.013654576611249282, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.948936170212766
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 20:48:49,966] Trial 83 finished with value: 0.8081515116241448 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 248, 'oob_score': False, 'max_samples': 0.8895151606507152, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.011438464038286824, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.4302788844621514
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9531914893617022
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8927038626609443
[I 2024-04-16 20:48:50,871] Trial 84 finished with value: 0.8091948201799142 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 245, 'oob_score': False, 'max_samples': 0.9076883591301161, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.011328270198803307, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 20:48:51,790] Trial 85 finished with value: 0.7626117604161355 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 250, 'oob_score': False, 'max_samples': 0.8912714990936835, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06818691468259591, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.948936170212766
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8755364806866953
[I 2024-04-16 20:48:52,577] Trial 86 finished with value: 0.7994121850885978 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 285, 'oob_score': False, 'max_samples': 0.8987308726874508, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03302778209237474, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.948936170212766
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8755364806866953
[I 2024-04-16 20:48:53,467] Trial 87 finished with value: 0.7994121850885978 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.9036671414535438, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.035390942972743616, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7296137339055794
[I 2024-04-16 20:48:54,561] Trial 88 finished with value: 0.7143061826888453 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.8316808639824699, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09035198362333563, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 20:48:55,880] Trial 89 finished with value: 0.7667200385203546 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.7992718500171103, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.062431931991299386, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.

Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9531914893617022
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 20:48:56,774] Trial 90 finished with value: 0.8114431330279217 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.9327807850870604, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009585388141868895, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8755364806866953
[I 2024-04-16 20:48:57,674] Trial 91 finished with value: 0.787083906465136 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 264, 'oob_score': False, 'max_samples': 0.9100907894869323, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04721684482499071, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9531914893617022
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 20:48:58,460] Trial 92 finished with value: 0.7969935168730937 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 249, 'oob_score': False, 'max_samples': 0.9311865147445494, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00710532776164125, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 20:48:59,422] Trial 93 finished with value: 0.6553371947230227 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 11, 'n_estimators': 314, 'oob_score': False, 'max_samples': 0.8940191779807615, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03194915873084253, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 20:49:00,585] Trial 94 finished with value: 0.8105309366914824 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 286, 'oob_score': False, 'max_samples': 0.9424117530674854, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.011502262332478998, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 20:49:01,603] Trial 95 finished with value: 0.7980786912622582 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 272, 'oob_score': False, 'max_samples': 0.9393765739794387, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012026402428663003, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.871244635193133
[I 2024-04-16 20:49:02,581] Trial 96 finished with value: 0.7968516883303108 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.9214166854252394, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00012856516772978728, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.4581673306772908
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 20:49:03,540] Trial 97 finished with value: 0.6473158413992819 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 327, 'oob_score': False, 'max_samples': 0.9778017623623412, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.011740987240212162, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8412017167381974
[I 2024-04-16 20:49:04,599] Trial 98 finished with value: 0.7778343715272409 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 292, 'oob_score': False, 'max_samples': 0.8238962320063237, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0458262008873294, 'warm_start': True}. Best is trial 76 with value: 0.8145470653025784.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.40304182509505704

[I 2024-04-16 20:49:10,272] A new study created in memory with name: no-name-c400bb47-a8e1-422f-88d1-8e72e34250e9

Fold 5 C-index: 0.5450643776824035
[I 2024-04-16 20:49:10,186] Trial 99 finished with value: 0.5670263619468852 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.846506422628747, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.029241078040282475, 'warm_start': False}. Best is trial 76 with value: 0.8145470653025784.


* Best trial for C-index:
 FrozenTrial(number=76, state=TrialState.COMPLETE, values=[0.8145470653025784], datetime_start=datetime.datetime(2024, 4, 16, 20, 48, 38, 813223), datetime_complete=datetime.datetime(2024, 4, 16, 20, 48, 40, 95216), params={'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 295, 'oob_score': False, 'max_samples': 0.9566855419974443, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.017888337982888625, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=76, value=None)


* Best Score for C-index:
 0.8145470653025784

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.27591057322615914
Fold 2 IBS: 0.21498282640755723
Fold 3 IBS: 0.20683956543539583
Fold 4 IBS: 0.2957511925931797
Fold 5 IBS: 0.25383159229000757
[I 2024-04-16 20:49:15,686] Trial 0 finished with value: 0.2494631499904599 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.2494631499904599.
Fold 1 IBS: 0.261633145233298
Fold 2 IBS: 0.21964728182626142
Fold 3 IBS: 0.2114498123373743
Fold 4 IBS: 0.27487793965408813
Fold 5 IBS: 0.24970805398029405
[I 2024-04-16 20:49:17,919] Trial 1 finished with value: 0.24346324660626317 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.24346324660626317.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-16 20:49:18,935] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 2 with value: 0.23598130937636846.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-16 20:49:22,233] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 2 with value: 0.23598130937636846.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-16 20:49:25,786] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 2 with value: 0.23598130937636846.
Fold 1 IBS: 0.2741204811753351
Fold 2 IBS: 0.21404967710482206
Fold 3 IBS: 0.2025078618342307
Fold 4 IBS: 0.2952649761055189
Fold 5 IBS: 0.25162567422985566
[I 2024-04-16 20:49:31,358] Trial 5 finished with value: 0.24751373408995248 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 2 with value: 0.23598130937636846.
Fold 1 IBS: 0.2638278510353221
Fold 2 IBS: 0.21886618856353768
Fold 3 IBS: 0.2097674515360073
Fold 4 IBS: 0.2914571754277688
Fold 5 IBS: 0.25132194231418703
[I 2024-04-16 20:49:35,169] Trial 6 finished with value: 0.24704812177536456 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 2 with value: 0.23598130937636846.
Fold 1 IBS: 0.24633141125908567
Fold 2 IBS: 0.2304495788678225
Fold 3 IBS: 0.22726557483788215
Fold 4 IBS: 0.24654731238001293
Fold 5 IBS: 0.23385503870129784
[I 2024-04-16 20:49:39,478] Trial 7 finished with value: 0.23688978320922022 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 2 with value: 0.23598130937636846.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-16 20:49:47,471] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 2 with value: 0.23598130937636846.
Fold 1 IBS: 0.26405745059022856
Fold 2 IBS: 0.21949677116801874
Fold 3 IBS: 0.2127022400545261
Fold 4 IBS: 0.26210763275757726
Fold 5 IBS: 0.24434251582926322
[I 2024-04-16 20:49:48,878] Trial 9 finished with value: 0.24054132207992276 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 2 with value: 0.23598130937636846.
Fold 1 IBS: 0.24809090100396206
Fold 2 IBS: 0.23403312002124396
Fold 3 IBS: 0.23020053525699236
Fold 4 IBS: 0.24114558824022825
Fold 5 IBS: 0.22998198015401258
[I 2024-04-16 20:49:49,411] Trial 10 finished with value: 0.23669042493528783 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 24, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254}. Best is trial 2 with value: 0.23598130937636846.
Fold 1 IBS: 0.2465216736601881
Fold 2 IBS: 0.23232174110362433
Fold 3 IBS: 0.22943202824262382
Fold 4 IBS: 0.24151957596425144
Fold 5 IBS: 0.23040510847954718
[I 2024-04-16 20:49:52,167] Trial 11 finished with value: 0.23604002549004693 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 174, 'oob_score': True, 'max_samples': 0.45068880137564815, 'max_features': None, 'min_weight_fraction_leaf': 0.49621108970886574}. Best is trial 2 with value: 0.23598130937636846.
Fold 1 IBS: 0.24673937237416346
Fold 2 IBS: 0.23314351852236284
Fold 3 IBS: 0.22899172624820438
Fold 4 IBS: 0.2411637078795893
Fold 5 IBS: 0.23030247643640647
[I 2024-04-16 20:49:52,763] Trial 12 finished with value: 0.23606816029214528 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 13, 'oob_score': True, 'max_samples': 0.29054083545162357, 'max_features': None, 'min_weight_fraction_leaf': 0.393368859300429}. Best is trial 2 with value: 0.23598130937636846.
Fold 1 IBS: 0.24661335252581118
Fold 2 IBS: 0.23213768343536437
Fold 3 IBS: 0.2293353915925799
Fold 4 IBS: 0.24149256560770377
Fold 5 IBS: 0.23022569837586918
[I 2024-04-16 20:49:55,238] Trial 13 finished with value: 0.23596093830746567 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 140, 'oob_score': True, 'max_samples': 0.5363884112411305, 'max_features': None, 'min_weight_fraction_leaf': 0.3101758479586497}. Best is trial 13 with value: 0.23596093830746567.
Fold 1 IBS: 0.2578794926757812
Fold 2 IBS: 0.2225793529014824
Fold 3 IBS: 0.2172116391401558
Fold 4 IBS: 0.26051701523030113
Fold 5 IBS: 0.24749124555962018
[I 2024-04-16 20:49:56,987] Trial 14 finished with value: 0.24113574910146812 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 116, 'oob_score': True, 'max_samples': 0.7654699764252667, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.30147851863790587}. Best is trial 13 with value: 0.23596093830746567.
Fold 1 IBS: 0.27281700634913325
Fold 2 IBS: 0.21693571144484913
Fold 3 IBS: 0.2059033159114551
Fold 4 IBS: 0.30168041881628943
Fold 5 IBS: 0.2572091982660071
[I 2024-04-16 20:49:59,340] Trial 15 finished with value: 0.25090913015754684 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 145, 'oob_score': True, 'max_samples': 0.562866747944144, 'max_features': None, 'min_weight_fraction_leaf': 0.0010841286217123658}. Best is trial 13 with value: 0.23596093830746567.

Fold 1 IBS: 0.24755603358581668
Fold 2 IBS: 0.23205159952418142
Fold 3 IBS: 0.2301253182270117
Fold 4 IBS: 0.2411227622573078
Fold 5 IBS: 0.22992100653273725
[I 2024-04-16 20:50:00,597] Trial 16 finished with value: 0.236155344025411 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 65, 'oob_score': True, 'max_samples': 0.2918078051386826, 'max_features': None, 'min_weight_fraction_leaf': 0.3442186213071368}. Best is trial 13 with value: 0.23596093830746567.
Fold 1 IBS: 0.2841429393863762
Fold 2 IBS: 0.2124730057472524
Fold 3 IBS: 0.2056237868746477
Fold 4 IBS: 0.3065017781165334
Fold 5 IBS: 0.2550005517131933
[I 2024-04-16 20:50:11,343] Trial 17 finished with value: 0.2527484123676006 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 494, 'oob_score': True, 'max_samples': 0.9861686560685959, 'max_features': None, 'min_weight_fraction_leaf': 0.27505397396962133}. Best is trial 13 with value: 0.23596093830746567.
Fold 1 IBS: 0.24704234953183699
Fold 2 IBS: 0.23209467215746654
Fold 3 IBS: 0.229537398780774
Fold 4 IBS: 0.24163242585488176
Fold 5 IBS: 0.23016136339777157
[I 2024-04-16 20:50:12,745] Trial 18 finished with value: 0.23609364194454616 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 60, 'oob_score': True, 'max_samples': 0.440310454082397, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4585563725292718}. Best is trial 13 with value: 0.23596093830746567.
Fold 1 IBS: 0.2542544956211318
Fold 2 IBS: 0.22148846872518346
Fold 3 IBS: 0.2177711652386954
Fold 4 IBS: 0.25856923806078025
Fold 5 IBS: 0.24547358602364874
[I 2024-04-16 20:50:16,433] Trial 19 finished with value: 0.23951139073388794 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 166, 'oob_score': True, 'max_samples': 0.8049648831342424, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3499914076703204}. Best is trial 13 with value: 0.23596093830746567.
Fold 1 IBS: 0.24702999602613837
Fold 2 IBS: 0.23327278674549579
Fold 3 IBS: 0.22962135755568333
Fold 4 IBS: 0.24201997441075696
Fold 5 IBS: 0.23268795630493067
[I 2024-04-16 20:50:16,894] Trial 20 finished with value: 0.23692641420860103 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.14828382238444415, 'max_features': None, 'min_weight_fraction_leaf': 0.1334408043115633}. Best is trial 13 with value: 0.23596093830746567.
Fold 1 IBS: 0.24674110476795194
Fold 2 IBS: 0.23213835168278035
Fold 3 IBS: 0.2294033872426188
Fold 4 IBS: 0.24155778499246175
Fold 5 IBS: 0.23022113343196546
[I 2024-04-16 20:50:20,549] Trial 21 finished with value: 0.23601235242355564 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 223, 'oob_score': False, 'max_samples': 0.5735659589871008, 'max_features': None, 'min_weight_fraction_leaf': 0.42510552698448656}. Best is trial 13 with value: 0.23596093830746567.
Fold 1 IBS: 0.24673370298034342
Fold 2 IBS: 0.23211034095213506
Fold 3 IBS: 0.22942902202181462
Fold 4 IBS: 0.2415511583435631
Fold 5 IBS: 0.23025999531149838
[I 2024-04-16 20:50:24,052] Trial 22 finished with value: 0.23601684392187092 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.6253174831363093, 'max_features': None, 'min_weight_fraction_leaf': 0.4494032735541527}. Best is trial 13 with value: 0.23596093830746567.
Fold 1 IBS: 0.2465119659743507
Fold 2 IBS: 0.23215467728732703
Fold 3 IBS: 0.22930615237900612
Fold 4 IBS: 0.24154973581383393
Fold 5 IBS: 0.23019630003830047
[I 2024-04-16 20:50:26,015] Trial 23 finished with value: 0.23594376629856365 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.4902793084442386, 'max_features': None, 'min_weight_fraction_leaf': 0.38478138827402214}. Best is trial 23 with value: 0.23594376629856365.
Fold 1 IBS: 0.24658556745074403
Fold 2 IBS: 0.23211798687165475
Fold 3 IBS: 0.22923571347554025
Fold 4 IBS: 0.24160167856766873
Fold 5 IBS: 0.23000300538449397
[I 2024-04-16 20:50:29,117] Trial 24 finished with value: 0.23590879035002033 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 132, 'oob_score': True, 'max_samples': 0.48440769024143365, 'max_features': None, 'min_weight_fraction_leaf': 0.3782768598253548}. Best is trial 24 with value: 0.23590879035002033.
Fold 1 IBS: 0.24649434864723727
Fold 2 IBS: 0.23218534206006355
Fold 3 IBS: 0.22929483670191786
Fold 4 IBS: 0.24161099416122161
Fold 5 IBS: 0.2301674524242506
[I 2024-04-16 20:50:31,924] Trial 25 finished with value: 0.23595059479893815 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 139, 'oob_score': True, 'max_samples': 0.47557974651163437, 'max_features': None, 'min_weight_fraction_leaf': 0.3821467900857916}. Best is trial 24 with value: 0.23590879035002033.
Fold 1 IBS: 0.24691899865558378
Fold 2 IBS: 0.2322455509324119
Fold 3 IBS: 0.22966367247329358
Fold 4 IBS: 0.24122623187979636
Fold 5 IBS: 0.23047248181271177
[I 2024-04-16 20:50:35,645] Trial 26 finished with value: 0.23610538715075946 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 258, 'oob_score': False, 'max_samples': 0.37263656780952376, 'max_features': None, 'min_weight_fraction_leaf': 0.3691984830027632}. Best is trial 24 with value: 0.23590879035002033.
Fold 1 IBS: 0.2461523128715739
Fold 2 IBS: 0.23215045121735292
Fold 3 IBS: 0.22956853718737785
Fold 4 IBS: 0.24119897859704714
Fold 5 IBS: 0.2301070743574254
[I 2024-04-16 20:50:39,201] Trial 27 finished with value: 0.23583547084615547 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 178, 'oob_score': True, 'max_samples': 0.20101781561896936, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2509347349611349}. Best is trial 27 with value: 0.23583547084615547.
Fold 1 IBS: 0.24634328089203386
Fold 2 IBS: 0.23218803199868812
Fold 3 IBS: 0.23007994228549364
Fold 4 IBS: 0.24110665015305713
Fold 5 IBS: 0.23030337626505956
[I 2024-04-16 20:50:44,104] Trial 28 finished with value: 0.23600425631886646 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.1910565418778623, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2338963798170712}. Best is trial 27 with value: 0.23583547084615547.
Fold 1 IBS: 0.24635096056047007
Fold 2 IBS: 0.23220874518379464
Fold 3 IBS: 0.22947936135126243
Fold 4 IBS: 0.2411036737883754
Fold 5 IBS: 0.2301509404009982
[I 2024-04-16 20:50:47,763] Trial 29 finished with value: 0.23585873625698012 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 179, 'oob_score': False, 'max_samples': 0.2042798613790791, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.26065085559418405}. Best is trial 27 with value: 0.23583547084615547.
Fold 1 IBS: 0.24626102959185833
Fold 2 IBS: 0.23219117113132368
Fold 3 IBS: 0.22957327222043847
Fold 4 IBS: 0.24108313751432975
Fold 5 IBS: 0.23013698080280512
[I 2024-04-16 20:50:51,292] Trial 30 finished with value: 0.23584911825215107 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 179, 'oob_score': True, 'max_samples': 0.2172618637182342, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2496653661609492}. Best is trial 27 with value: 0.23583547084615547.
Fold 1 IBS: 0.24628507697960428
Fold 2 IBS: 0.23220768323630628
Fold 3 IBS: 0.22947399015541597
Fold 4 IBS: 0.24107241419463077
Fold 5 IBS: 0.23028080310502047
[I 2024-04-16 20:50:56,083] Trial 31 finished with value: 0.23586399353419557 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 181, 'oob_score': True, 'max_samples': 0.20356578170819345, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.200122183056397}. Best is trial 27 with value: 0.23583547084615547.

Fold 1 IBS: 0.246386460438482
Fold 2 IBS: 0.23218899742898796
Fold 3 IBS: 0.22946758410602397
Fold 4 IBS: 0.24118772219117468
Fold 5 IBS: 0.2303071920630508
[I 2024-04-16 20:50:58,547] Trial 32 finished with value: 0.2359075912455439 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 175, 'oob_score': True, 'max_samples': 0.20444340416617043, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19558060234973634}. Best is trial 27 with value: 0.23583547084615547.
Fold 1 IBS: 0.24684478929600995
Fold 2 IBS: 0.2322329224950302
Fold 3 IBS: 0.23005427140610996
Fold 4 IBS: 0.2412308304074783
Fold 5 IBS: 0.2301271605653773
[I 2024-04-16 20:51:01,553] Trial 33 finished with value: 0.23609799483400112 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.23980153995474307, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.26025002413271664}. Best is trial 27 with value: 0.23583547084615547.
Fold 1 IBS: 0.24629612202622034
Fold 2 IBS: 0.2321757763544079
Fold 3 IBS: 0.23020305840050656
Fold 4 IBS: 0.24096566947622064
Fold 5 IBS: 0.22940613099338275
[I 2024-04-16 20:51:04,791] Trial 34 finished with value: 0.23580935145014764 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 191, 'oob_score': True, 'max_samples': 0.10957555561869275, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1540534445996569}. Best is trial 34 with value: 0.23580935145014764.
Fold 1 IBS: 0.24642955212543458
Fold 2 IBS: 0.23210570063898123
Fold 3 IBS: 0.23011864741573268
Fold 4 IBS: 0.2409904228857144
Fold 5 IBS: 0.22972881811558774
[I 2024-04-16 20:51:13,178] Trial 35 finished with value: 0.2358746282362901 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 303, 'oob_score': True, 'max_samples': 0.135842653204343, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14055808314732887}. Best is trial 34 with value: 0.23580935145014764.
Fold 1 IBS: 0.24693908685849436
Fold 2 IBS: 0.23212132427021256
Fold 3 IBS: 0.22986181011849532
Fold 4 IBS: 0.24112943990465174
Fold 5 IBS: 0.22954611086329282
[I 2024-04-16 20:51:15,505] Trial 36 finished with value: 0.23591955440302934 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 91, 'oob_score': False, 'max_samples': 0.33904336431814686, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24229689234995383}. Best is trial 34 with value: 0.23580935145014764.
Fold 1 IBS: 0.2468826163960784
Fold 2 IBS: 0.23221184007541024
Fold 3 IBS: 0.23008935159168653
Fold 4 IBS: 0.24117012705297697
Fold 5 IBS: 0.23021360172798538
[I 2024-04-16 20:51:21,886] Trial 37 finished with value: 0.2361135073688275 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 259, 'oob_score': True, 'max_samples': 0.23925941642373869, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16380045695722578}. Best is trial 34 with value: 0.23580935145014764.
Fold 1 IBS: 0.24674409763207455
Fold 2 IBS: 0.23221242474003606
Fold 3 IBS: 0.2303653585217402
Fold 4 IBS: 0.24093955168004538
Fold 5 IBS: 0.22964407548926682
[I 2024-04-16 20:51:27,168] Trial 38 finished with value: 0.2359811016126326 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 387, 'oob_score': False, 'max_samples': 0.10212918533505765, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09186216902752373}. Best is trial 34 with value: 0.23580935145014764.
Fold 1 IBS: 0.24650679386380978
Fold 2 IBS: 0.23221695072489687
Fold 3 IBS: 0.23009604310825457
Fold 4 IBS: 0.24115551017310963
Fold 5 IBS: 0.23000027288213667
[I 2024-04-16 20:51:30,345] Trial 39 finished with value: 0.2359951141504415 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 195, 'oob_score': True, 'max_samples': 0.2542305123568164, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3185609866823583}. Best is trial 34 with value: 0.23580935145014764.
Fold 1 IBS: 0.24672885233318156
Fold 2 IBS: 0.23215014310762533
Fold 3 IBS: 0.2298820373117688
Fold 4 IBS: 0.2411215334000037
Fold 5 IBS: 0.22991976601816827
[I 2024-04-16 20:51:33,843] Trial 40 finished with value: 0.23596046643414953 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 247, 'oob_score': False, 'max_samples': 0.16382436256125943, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21808125507853632}. Best is trial 34 with value: 0.23580935145014764.
Fold 1 IBS: 0.24608260922320394
Fold 2 IBS: 0.23216321033729656
Fold 3 IBS: 0.22974491180828696
Fold 4 IBS: 0.24106526077618337
Fold 5 IBS: 0.2301669695248577
[I 2024-04-16 20:51:37,825] Trial 41 finished with value: 0.23584459233396568 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 188, 'oob_score': True, 'max_samples': 0.19790930529492065, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19029977199488543}. Best is trial 34 with value: 0.23580935145014764.
Fold 1 IBS: 0.25460331188610147
Fold 2 IBS: 0.2214016072545257
Fold 3 IBS: 0.21667268711864923
Fold 4 IBS: 0.25657255495667597
Fold 5 IBS: 0.24639303563148776
[I 2024-04-16 20:51:42,300] Trial 42 finished with value: 0.23912863936948803 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 197, 'oob_score': True, 'max_samples': 0.3786139592407123, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16204535136399997}. Best is trial 34 with value: 0.23580935145014764.
Fold 1 IBS: 0.2463168629325967
Fold 2 IBS: 0.2321626411934989
Fold 3 IBS: 0.2298720015070961
Fold 4 IBS: 0.24118324483372838
Fold 5 IBS: 0.23012989464337194
[I 2024-04-16 20:51:46,778] Trial 43 finished with value: 0.23593292902205837 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 227, 'oob_score': True, 'max_samples': 0.17936431274618084, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.26249449519233}. Best is trial 34 with value: 0.23580935145014764.
Fold 1 IBS: 0.24640073914234437
Fold 2 IBS: 0.23213928117557286
Fold 3 IBS: 0.2296575104762251
Fold 4 IBS: 0.24116792235136672
Fold 5 IBS: 0.2298507041804842
[I 2024-04-16 20:51:50,590] Trial 44 finished with value: 0.23584323146519864 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 160, 'oob_score': True, 'max_samples': 0.261387121326456, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21834670682604973}. Best is trial 34 with value: 0.23580935145014764.
Fold 1 IBS: 0.24661586387661988
Fold 2 IBS: 0.23209025526351867
Fold 3 IBS: 0.22979222553442066
Fold 4 IBS: 0.2412323335183369
Fold 5 IBS: 0.22981822522374332
[I 2024-04-16 20:51:52,866] Trial 45 finished with value: 0.23590978068332785 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 117, 'oob_score': True, 'max_samples': 0.266094272716378, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18485404335286146}. Best is trial 34 with value: 0.23580935145014764.
Fold 1 IBS: 0.24610534625214905
Fold 2 IBS: 0.2321042451172719
Fold 3 IBS: 0.2295330555227091
Fold 4 IBS: 0.2411820021801765
Fold 5 IBS: 0.22982121618562995
[I 2024-04-16 20:51:55,896] Trial 46 finished with value: 0.23574917305158732 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 162, 'oob_score': True, 'max_samples': 0.1328203375473852, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12670648749550079}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24612807553311816
Fold 2 IBS: 0.23210418555769743
Fold 3 IBS: 0.229560739352739
Fold 4 IBS: 0.24120415802751802

Fold 5 IBS: 0.22978676956550373
[I 2024-04-16 20:51:58,964] Trial 47 finished with value: 0.23575678560731528 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 160, 'oob_score': True, 'max_samples': 0.13434415907111946, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10612603041708193}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24757897353687755
Fold 2 IBS: 0.2320725752850252
Fold 3 IBS: 0.2299544780683508
Fold 4 IBS: 0.24154478404388094
Fold 5 IBS: 0.23016145399352744
[I 2024-04-16 20:52:00,714] Trial 48 finished with value: 0.2362624529855324 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 86, 'oob_score': True, 'max_samples': 0.12964207163685623, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10203918387448863}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24671151151924972
Fold 2 IBS: 0.2321161791284474
Fold 3 IBS: 0.22994471099962702
Fold 4 IBS: 0.2410725962212564
Fold 5 IBS: 0.22964203220655835
[I 2024-04-16 20:52:03,189] Trial 49 finished with value: 0.2358974060150278 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 158, 'oob_score': True, 'max_samples': 0.10070147818076881, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04963283899224618}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24691802806310317
Fold 2 IBS: 0.2320709415078913
Fold 3 IBS: 0.22947845863152067
Fold 4 IBS: 0.24148402255637752
Fold 5 IBS: 0.2296779141068973
[I 2024-04-16 20:52:05,108] Trial 50 finished with value: 0.23592587297315798 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 118, 'oob_score': True, 'max_samples': 0.1526608372265612, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12016333255543489}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.2645978648055397
Fold 2 IBS: 0.2184809740632038
Fold 3 IBS: 0.21027288212338024
Fold 4 IBS: 0.2666505815680693
Fold 5 IBS: 0.24804419587343163
[I 2024-04-16 20:52:09,749] Trial 51 finished with value: 0.2416092996867249 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 201, 'oob_score': True, 'max_samples': 0.3118403446536162, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05784687948424541}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24598329773765373
Fold 2 IBS: 0.232125961499039
Fold 3 IBS: 0.22952231419420538
Fold 4 IBS: 0.24106537779914364
Fold 5 IBS: 0.23006624518141236
[I 2024-04-16 20:52:12,883] Trial 52 finished with value: 0.2357526392822908 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 154, 'oob_score': True, 'max_samples': 0.1686189352946997, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17644568854512438}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24620398835440607
Fold 2 IBS: 0.23210852787513708
Fold 3 IBS: 0.22949444329285063
Fold 4 IBS: 0.24115741845241656
Fold 5 IBS: 0.2300264773853198
[I 2024-04-16 20:52:15,130] Trial 53 finished with value: 0.23579817107202605 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 157, 'oob_score': True, 'max_samples': 0.1374430922331848, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14917488142659044}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.2475605024742218
Fold 2 IBS: 0.23208992266327644
Fold 3 IBS: 0.22937123102158005
Fold 4 IBS: 0.24132790620284683
Fold 5 IBS: 0.23011542089021533
[I 2024-04-16 20:52:18,190] Trial 54 finished with value: 0.2360929966504281 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 8, 'n_estimators': 98, 'oob_score': True, 'max_samples': 0.13110894799770323, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11559837435683704}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24642653676263598
Fold 2 IBS: 0.23210259478187156
Fold 3 IBS: 0.22952378672295753
Fold 4 IBS: 0.24112263188124416
Fold 5 IBS: 0.2298842385660858
[I 2024-04-16 20:52:21,602] Trial 55 finished with value: 0.23581195774295902 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 158, 'oob_score': True, 'max_samples': 0.16015692264462092, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1491267404398542}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24646606953758576
Fold 2 IBS: 0.2320654072191846
Fold 3 IBS: 0.23060709747227148
Fold 4 IBS: 0.2411126477460008
Fold 5 IBS: 0.23007902617745937
[I 2024-04-16 20:52:23,158] Trial 56 finished with value: 0.2360660496305004 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 71, 'oob_score': True, 'max_samples': 0.16055021132100036, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15177796502908963}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24673581490776594
Fold 2 IBS: 0.23210319358201056
Fold 3 IBS: 0.22926023945371057
Fold 4 IBS: 0.24147431060227229
Fold 5 IBS: 0.22955727045527607
[I 2024-04-16 20:52:25,555] Trial 57 finished with value: 0.23582616580020713 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 127, 'oob_score': True, 'max_samples': 0.12317842482105201, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01985471324478305}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.2616410966956528
Fold 2 IBS: 0.21874696147800968
Fold 3 IBS: 0.21442058709508807
Fold 4 IBS: 0.2582554090529397
Fold 5 IBS: 0.2467112514462197
[I 2024-04-16 20:52:28,855] Trial 58 finished with value: 0.23995506115358198 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 159, 'oob_score': True, 'max_samples': 0.2800307741203458, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0742567118579938}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.2460008483350801
Fold 2 IBS: 0.23208672128092367
Fold 3 IBS: 0.23053857291847646
Fold 4 IBS: 0.24135581929046093
Fold 5 IBS: 0.23153718117579178
[I 2024-04-16 20:52:30,025] Trial 59 finished with value: 0.23630382860014656 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 40, 'oob_score': True, 'max_samples': 0.1689234860582833, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12219094122917895}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24664106826883345
Fold 2 IBS: 0.2322275336224368
Fold 3 IBS: 0.22998288147591256
Fold 4 IBS: 0.24116348977815077
Fold 5 IBS: 0.23015825145590965
[I 2024-04-16 20:52:35,012] Trial 60 finished with value: 0.23603464492024867 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.23225746100230737, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17392726755697085}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24672121134176211
Fold 2 IBS: 0.23211681745714727
Fold 3 IBS: 0.22937443583450978
Fold 4 IBS: 0.2414473189466378
Fold 5 IBS: 0.22956850082444494
[I 2024-04-16 20:52:38,007] Trial 61 finished with value: 0.23584565688090037 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 126, 'oob_score': True, 'max_samples': 0.1268771566483847, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14314854619030826}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24629488273131117
Fold 2 IBS: 0.23220524290819475
Fold 3 IBS: 0.22989429246507823
Fold 4 IBS: 0.2413315398582842
Fold 5 IBS: 0.22936425763000706
[I 2024-04-16 20:52:42,265] Trial 62 finished with value: 0.23581804311857507 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 145, 'oob_score': True, 'max_samples': 0.10482138032891447, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03301813413953483}. Best is trial 46 with value: 0.23574917305158732.

Fold 1 IBS: 0.24631928839139375
Fold 2 IBS: 0.23211332325251055
Fold 3 IBS: 0.22987340393724426
Fold 4 IBS: 0.24110794902474542
Fold 5 IBS: 0.2296571564179856
[I 2024-04-16 20:52:45,476] Trial 63 finished with value: 0.2358142242047759 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 150, 'oob_score': True, 'max_samples': 0.10056089265752739, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.026471209866795242}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24648722835656947
Fold 2 IBS: 0.23206092276817514
Fold 3 IBS: 0.22928811947466984
Fold 4 IBS: 0.24128731957110403
Fold 5 IBS: 0.22992351169818162
[I 2024-04-16 20:52:48,788] Trial 64 finished with value: 0.23580942037374003 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 104, 'oob_score': True, 'max_samples': 0.17392096150604247, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0930739163724094}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24631057274728077
Fold 2 IBS: 0.23205451525837573
Fold 3 IBS: 0.22978512305057056
Fold 4 IBS: 0.24115283389591882
Fold 5 IBS: 0.22979681715211225
[I 2024-04-16 20:52:50,526] Trial 65 finished with value: 0.23581997242085162 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 77, 'oob_score': True, 'max_samples': 0.17107362772793475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10175893677913037}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.26943912687984556
Fold 2 IBS: 0.21174756716440818
Fold 3 IBS: 0.20465241325169986
Fold 4 IBS: 0.30055645890539767
Fold 5 IBS: 0.2508702004724961
[I 2024-04-16 20:52:53,160] Trial 66 finished with value: 0.24745315333476947 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 111, 'oob_score': True, 'max_samples': 0.6763611194745864, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0878625292177529}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.2472039298413524
Fold 2 IBS: 0.23208106431613543
Fold 3 IBS: 0.22928351588488227
Fold 4 IBS: 0.24152032136424384
Fold 5 IBS: 0.23011527533122575
[I 2024-04-16 20:52:54,877] Trial 67 finished with value: 0.23604082134756793 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 103, 'oob_score': True, 'max_samples': 0.14794652241888864, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11356257365889996}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24690620032791402
Fold 2 IBS: 0.2321482505450385
Fold 3 IBS: 0.23015285546489336
Fold 4 IBS: 0.2414803375374937
Fold 5 IBS: 0.22949972068324231
[I 2024-04-16 20:52:56,564] Trial 68 finished with value: 0.23603747291171637 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 53, 'oob_score': True, 'max_samples': 0.22923550018270145, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13268201820783565}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.2671755842685229
Fold 2 IBS: 0.22225455871154093
Fold 3 IBS: 0.21091662326655963
Fold 4 IBS: 0.267686503159043
Fold 5 IBS: 0.2531456075742678
[I 2024-04-16 20:53:02,306] Trial 69 finished with value: 0.24423577539598681 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 214, 'oob_score': True, 'max_samples': 0.3299667116416029, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07614689830877314}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24667931532247925
Fold 2 IBS: 0.23213574238453918
Fold 3 IBS: 0.22987393105107073
Fold 4 IBS: 0.24108520250143287
Fold 5 IBS: 0.23023747567508301
[I 2024-04-16 20:53:07,077] Trial 70 finished with value: 0.236002333386921 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 275, 'oob_score': True, 'max_samples': 0.1812882340839396, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17712837921617589}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24636268985964108
Fold 2 IBS: 0.23213623681127737
Fold 3 IBS: 0.23002496741259343
Fold 4 IBS: 0.2409477801727153
Fold 5 IBS: 0.2296990652419028
[I 2024-04-16 20:53:11,551] Trial 71 finished with value: 0.23583414789962603 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 153, 'oob_score': True, 'max_samples': 0.10233196227899141, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.040285488126151056}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24631739197109698
Fold 2 IBS: 0.2321130520180829
Fold 3 IBS: 0.2294834450052571
Fold 4 IBS: 0.24134301433786842
Fold 5 IBS: 0.22983042684713995
[I 2024-04-16 20:53:14,779] Trial 72 finished with value: 0.23581746603588907 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 168, 'oob_score': True, 'max_samples': 0.14580074489872052, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.009380029468118847}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24634896545172297
Fold 2 IBS: 0.23214694684635853
Fold 3 IBS: 0.2294010289798943
Fold 4 IBS: 0.2412281420599597
Fold 5 IBS: 0.22992749692259257
[I 2024-04-16 20:53:17,881] Trial 73 finished with value: 0.23581051605210562 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.17825350603935688, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14738450745369192}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24644318776065868
Fold 2 IBS: 0.23207528160702445
Fold 3 IBS: 0.2295958933262806
Fold 4 IBS: 0.24131265359072862
Fold 5 IBS: 0.22992936618960708
[I 2024-04-16 20:53:20,984] Trial 74 finished with value: 0.2358712764948599 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 131, 'oob_score': True, 'max_samples': 0.22085306284032188, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15502502276374028}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24627387297436937
Fold 2 IBS: 0.23213890970498105
Fold 3 IBS: 0.2293775325384713
Fold 4 IBS: 0.2412826873500381
Fold 5 IBS: 0.22975477971345784
[I 2024-04-16 20:53:25,356] Trial 75 finished with value: 0.23576555645626351 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 139, 'oob_score': True, 'max_samples': 0.17191341885361489, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12808413949068023}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.26058101735468353
Fold 2 IBS: 0.22026408321436733
Fold 3 IBS: 0.21497934093882684
Fold 4 IBS: 0.2611923846155666
Fold 5 IBS: 0.24858655325876047
[I 2024-04-16 20:53:28,314] Trial 76 finished with value: 0.24112067587644095 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 136, 'oob_score': True, 'max_samples': 0.2963700269988302, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09770830717706375}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.2466314720661211
Fold 2 IBS: 0.23204046448870722
Fold 3 IBS: 0.23002255062363958
Fold 4 IBS: 0.24120701755906074
Fold 5 IBS: 0.22987785496461874
[I 2024-04-16 20:53:30,334] Trial 77 finished with value: 0.23595587194042947 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 87, 'oob_score': True, 'max_samples': 0.1824412591778118, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2065018698799328}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.27440595759417546
Fold 2 IBS: 0.21029273276821314
Fold 3 IBS: 0.2052435258483014
Fold 4 IBS: 0.2987061878769685

Fold 5 IBS: 0.2519163373802201
[I 2024-04-16 20:53:34,303] Trial 78 finished with value: 0.24811294829357572 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 171, 'oob_score': True, 'max_samples': 0.9147835512625551, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13257772422273512}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24630596960013934
Fold 2 IBS: 0.23202892604980208
Fold 3 IBS: 0.23058361904315297
Fold 4 IBS: 0.24129573617042252
Fold 5 IBS: 0.2301768553877985
[I 2024-04-16 20:53:35,358] Trial 79 finished with value: 0.2360782212502631 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 37, 'oob_score': True, 'max_samples': 0.2189744006895358, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17152888523323856}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24642825384745612
Fold 2 IBS: 0.23209436622155608
Fold 3 IBS: 0.22988099359228903
Fold 4 IBS: 0.24087305970531198
Fold 5 IBS: 0.22962862365600684
[I 2024-04-16 20:53:38,953] Trial 80 finished with value: 0.23578105940452398 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 192, 'oob_score': True, 'max_samples': 0.12737499566968374, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06259694169778296}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24614556557896328
Fold 2 IBS: 0.23209786267308252
Fold 3 IBS: 0.22993125984627258
Fold 4 IBS: 0.24083731830432825
Fold 5 IBS: 0.22978012700053185
[I 2024-04-16 20:53:42,270] Trial 81 finished with value: 0.23575842668063568 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 187, 'oob_score': True, 'max_samples': 0.129675346852471, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10946840852074628}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24621080158033185
Fold 2 IBS: 0.2321039565167422
Fold 3 IBS: 0.22991420482926572
Fold 4 IBS: 0.24087000476784493
Fold 5 IBS: 0.22980765617557308
[I 2024-04-16 20:53:47,103] Trial 82 finished with value: 0.23578132477395153 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 189, 'oob_score': True, 'max_samples': 0.12903796755729202, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08477664998566667}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.2468038757345519
Fold 2 IBS: 0.23219610488937897
Fold 3 IBS: 0.2300595599368323
Fold 4 IBS: 0.24102545528083852
Fold 5 IBS: 0.22974426574238857
[I 2024-04-16 20:53:52,284] Trial 83 finished with value: 0.23596585231679806 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 244, 'oob_score': True, 'max_samples': 0.12753948214990862, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06158909286175156}. Best is trial 46 with value: 0.23574917305158732.
Fold 1 IBS: 0.24590113989382267
Fold 2 IBS: 0.23209098147273544
Fold 3 IBS: 0.22980016182905577
Fold 4 IBS: 0.2409911884749795
Fold 5 IBS: 0.22982225569605497
[I 2024-04-16 20:53:58,170] Trial 84 finished with value: 0.23572114547332967 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 186, 'oob_score': True, 'max_samples': 0.1369774849788948, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07082006896114468}. Best is trial 84 with value: 0.23572114547332967.
Fold 1 IBS: 0.2463942282276576
Fold 2 IBS: 0.232107762620782
Fold 3 IBS: 0.2299393336184058
Fold 4 IBS: 0.24119171348512108
Fold 5 IBS: 0.2294953977229491
[I 2024-04-16 20:54:05,157] Trial 85 finished with value: 0.2358256871349831 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 218, 'oob_score': True, 'max_samples': 0.1405559883896458, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0718551609965387}. Best is trial 84 with value: 0.23572114547332967.
Fold 1 IBS: 0.2460980984675912
Fold 2 IBS: 0.2321684373411079
Fold 3 IBS: 0.22972335156288629
Fold 4 IBS: 0.24107166741564337
Fold 5 IBS: 0.23022634834812622
[I 2024-04-16 20:54:15,110] Trial 86 finished with value: 0.235857580627071 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 189, 'oob_score': True, 'max_samples': 0.19994266442881134, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10931290070655511}. Best is trial 84 with value: 0.23572114547332967.
Fold 1 IBS: 0.24653629458063012
Fold 2 IBS: 0.23212291068608318
Fold 3 IBS: 0.2302018017824057
Fold 4 IBS: 0.24096240860888807
Fold 5 IBS: 0.2294431444368806
[I 2024-04-16 20:54:20,532] Trial 87 finished with value: 0.23585331201897755 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 224, 'oob_score': True, 'max_samples': 0.12205674001650765, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08548090924162252}. Best is trial 84 with value: 0.23572114547332967.
Fold 1 IBS: 0.24632359174091117
Fold 2 IBS: 0.23213260712381326
Fold 3 IBS: 0.2297160472094284
Fold 4 IBS: 0.24113446853667636
Fold 5 IBS: 0.22964047777278074
[I 2024-04-16 20:54:24,092] Trial 88 finished with value: 0.23578943847672199 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 201, 'oob_score': True, 'max_samples': 0.14369409490324908, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1250257915245737}. Best is trial 84 with value: 0.23572114547332967.
Fold 1 IBS: 0.2607718730289167
Fold 2 IBS: 0.21963926343948023
Fold 3 IBS: 0.2152760478771772
Fold 4 IBS: 0.25607385060810667
Fold 5 IBS: 0.24690921380814876
[I 2024-04-16 20:54:27,279] Trial 89 finished with value: 0.2397340497523659 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 197, 'oob_score': False, 'max_samples': 0.20044521425304113, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05585471341259399}. Best is trial 84 with value: 0.23572114547332967.
Fold 1 IBS: 0.26700126283857545
Fold 2 IBS: 0.21665517895550312
Fold 3 IBS: 0.20895973505106094
Fold 4 IBS: 0.2706512186701332
Fold 5 IBS: 0.2504298258840599
[I 2024-04-16 20:54:31,786] Trial 90 finished with value: 0.24273944427986655 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 205, 'oob_score': True, 'max_samples': 0.2449606812809515, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04398906664078604}. Best is trial 84 with value: 0.23572114547332967.
Fold 1 IBS: 0.2461175636155624
Fold 2 IBS: 0.2321304576438652
Fold 3 IBS: 0.2296447636063996
Fold 4 IBS: 0.24126282751004344
Fold 5 IBS: 0.22998055381598687
[I 2024-04-16 20:54:35,638] Trial 91 finished with value: 0.23582723323837151 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 181, 'oob_score': True, 'max_samples': 0.155756138975178, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12467442104314795}. Best is trial 84 with value: 0.23572114547332967.
Fold 1 IBS: 0.24668314948745038
Fold 2 IBS: 0.23212970547179343
Fold 3 IBS: 0.23004878688143915
Fold 4 IBS: 0.24124960665817413
Fold 5 IBS: 0.22950624609879086
[I 2024-04-16 20:54:39,468] Trial 92 finished with value: 0.23592349891952963 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 231, 'oob_score': True, 'max_samples': 0.14057054183521206, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1079867101616769}. Best is trial 84 with value: 0.23572114547332967.
Fold 1 IBS: 0.24629109292358
Fold 2 IBS: 0.23219933047583366
Fold 3 IBS: 0.22995132169139357
Fold 4 IBS: 0.24114207374616886
Fold 5 IBS: 0.2299834347574954
[I 2024-04-16 20:54:41,752] Trial 93 finished with value: 0.2359134507188943 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 169, 'oob_score': True, 'max_samples': 0.1178515236643613, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08234910926040626}. Best is trial 84 with value: 0.23572114547332967.

Fold 1 IBS: 0.24603980142682666
Fold 2 IBS: 0.23212293756683253
Fold 3 IBS: 0.22980177266109972
Fold 4 IBS: 0.24117019375096946
Fold 5 IBS: 0.23000323031974987
[I 2024-04-16 20:54:46,192] Trial 94 finished with value: 0.23582758714509566 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 186, 'oob_score': True, 'max_samples': 0.15211446012016716, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1336981908011637}. Best is trial 84 with value: 0.23572114547332967.
Fold 1 IBS: 0.24609144860992238
Fold 2 IBS: 0.23210462726436726
Fold 3 IBS: 0.23027168009436597
Fold 4 IBS: 0.24100241364516664
Fold 5 IBS: 0.2300638162943246
[I 2024-04-16 20:54:57,781] Trial 95 finished with value: 0.23590679718162938 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 489, 'oob_score': True, 'max_samples': 0.12627955102410032, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07183569510085065}. Best is trial 84 with value: 0.23572114547332967.
Fold 1 IBS: 0.26567192382073307
Fold 2 IBS: 0.22006647538099325
Fold 3 IBS: 0.20929541869298876
Fold 4 IBS: 0.27907157279143174
Fold 5 IBS: 0.2505631045661274
[I 2024-04-16 20:55:02,549] Trial 96 finished with value: 0.24493369905045484 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 147, 'oob_score': True, 'max_samples': 0.5972550179693354, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12328949468415032}. Best is trial 84 with value: 0.23572114547332967.
Fold 1 IBS: 0.2671588425028553
Fold 2 IBS: 0.21629894535884495
Fold 3 IBS: 0.20886046198903815
Fold 4 IBS: 0.2771288645778696
Fold 5 IBS: 0.25285207206851973
[I 2024-04-16 20:55:07,623] Trial 97 finished with value: 0.24445983729942555 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 176, 'oob_score': True, 'max_samples': 0.521538664132392, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10248566096991005}. Best is trial 84 with value: 0.23572114547332967.
Fold 1 IBS: 0.25616726159872977
Fold 2 IBS: 0.2154884160533265
Fold 3 IBS: 0.21421549141438934
Fold 4 IBS: 0.2564391004813613
Fold 5 IBS: 0.24982775376766497
[I 2024-04-16 20:55:13,131] Trial 98 finished with value: 0.23842760466309437 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 164, 'oob_score': True, 'max_samples': 0.19036435349819633, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06711783150072304}. Best is trial 84 with value: 0.23572114547332967.
Fold 1 IBS: 0.24661134908718477
Fold 2 IBS: 0.2321769651711653
Fold 3 IBS: 0.22988003838628546
Fold 4 IBS: 0.2411328558768114
Fold 5 IBS: 0.2301770116338281
[I 2024-04-16 20:55:27,160] Trial 99 finished with value: 0.23599564403105502 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 240, 'oob_score': True, 'max_samples': 0.16755506074922272, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16117647863184062}. Best is trial 84 with value: 0.23572114547332967.


* Best trial for IBS:
 FrozenTrial(number=84, state=TrialState.COMPLETE, values=[0.23572114547332967], datetime_start=datetime.datetime(2024, 4, 16, 20, 53, 52, 290266), datetime_complete=datetime.datetime(2024, 4, 16, 20, 53, 58, 169324), params={'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 186, 'oob_score': True, 'max_samples': 0.1369774849788948, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07082006896114468}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=84, value=None)


* Best Score for IBS:
 0.23572114547332967

In [94]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [95]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.815
train_ibs:  0.236

#### Test

In [96]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [97]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=14, max_features='auto', max_leaf_nodes=19,
                     max_samples=0.9566855419974443, min_samples_leaf=1,
                     min_samples_split=7,
                     min_weight_fraction_leaf=0.017888337982888625,
                     n_estimators=295, random_state=123, warm_start=True)

test_cindex:  0.562

RandomSurvivalForest(max_depth=3, max_features='auto', max_leaf_nodes=11,
                     max_samples=0.1369774849788948, min_samples_leaf=2,
                     min_samples_split=20,
                     min_weight_fraction_leaf=0.07082006896114468,
                     n_estimators=186, oob_score=True, random_state=123)

test_ibs:  0.23

In [98]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [99]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [100]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:55:31,125] A new study created in memory with name: no-name-845c7c6b-c15f-4654-b7b9-f387db353881

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 20:55:35,057] Trial 0 finished with value: 0.6582032466680394 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.6582032466680394.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:55:41,665] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.6582032466680394.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.42585551330798477
Fold 5 C-index: 0.45064377682403434
[I 2024-04-16 20:55:52,861] Trial 2 finished with value: 0.5600339219357016 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.6582032466680394.
Fold 1 C-index: 0.4302788844621514
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 20:55:53,810] Trial 3 finished with value: 0.6267781716212525 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.6582032466680394.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:55:56,597] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.6582032466680394.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:55:59,235] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.6582032466680394.
Fold 1 C-index: 0.4302788844621514
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 20:56:00,801] Trial 6 finished with value: 0.6490885482944847 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.6582032466680394.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.42585551330798477
Fold 5 C-index: 0.5021459227467812
[I 2024-04-16 20:56:03,877] Trial 7 finished with value: 0.5866456981780037 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.6582032466680394.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.564638783269962
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 20:56:04,108] Trial 8 finished with value: 0.6306314902476274 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.6582032466680394.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.4714828897338403
Fold 5 C-index: 0.48497854077253216
[I 2024-04-16 20:56:12,789] Trial 9 finished with value: 0.5359721514986655 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.6582032466680394.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:56:15,162] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.6582032466680394.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.5475285171102662
Fold 5 C-index: 0.5150214592274678
[I 2024-04-16 20:56:16,265] Trial 11 finished with value: 0.6263645490136378 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.6582032466680394.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 20:56:17,866] Trial 12 finished with value: 0.6893948377364146 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.4302788844621514
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 20:56:20,029] Trial 13 finished with value: 0.6338259169512922 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 20:56:21,816] Trial 14 finished with value: 0.6311712317130679 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.6893948377364146.

Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 20:56:22,530] Trial 15 finished with value: 0.6300710658255483 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.7553191489361702
Fold 4 C-index: 0.5228136882129277
Fold 5 C-index: 0.5128755364806867
[I 2024-04-16 20:56:24,031] Trial 16 finished with value: 0.5818975887443021 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:56:25,093] Trial 17 finished with value: 0.631929081735865 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:56:26,683] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 20:56:28,329] Trial 19 finished with value: 0.6382991651318985 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.3944223107569721
Fold 2 C-index: 0.5658914728682171
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5494296577946768
Fold 5 C-index: 0.45493562231759654
[I 2024-04-16 20:56:28,475] Trial 20 finished with value: 0.5039996425347265 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.4302788844621514
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 20:56:30,004] Trial 21 finished with value: 0.6490665055008742 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 20:56:31,696] Trial 22 finished with value: 0.6416606727916666 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4780520239555279, 'min_weight_fraction_leaf': 0.01760516455314039}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6180257510729614
[I 2024-04-16 20:56:33,082] Trial 23 finished with value: 0.6531588009995293 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6423644985218102, 'min_weight_fraction_leaf': 0.07933617912675625}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 20:56:34,986] Trial 24 finished with value: 0.6526262516759991 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 361, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7479661339947506, 'min_weight_fraction_leaf': 0.09384728704326059}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.4581673306772908
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 20:56:36,057] Trial 25 finished with value: 0.6692336104687271 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.047956477383484165}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.4581673306772908
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.43346007604562736
Fold 5 C-index: 0.5064377682403434
[I 2024-04-16 20:56:39,193] Trial 26 finished with value: 0.5887537244203284 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 205, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8442650771414504, 'min_weight_fraction_leaf': 0.04311046725313979}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.4581673306772908
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 20:56:40,058] Trial 27 finished with value: 0.6362563090317197 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 291, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9296679330104113, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.8063829787234043
Fold 4 C-index: 0.5836501901140685
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 20:56:40,683] Trial 28 finished with value: 0.6225694809580979 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 208, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7294475749114913, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.7228682170542635
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.6026615969581749
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 20:56:42,290] Trial 29 finished with value: 0.6216127927559821 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 287, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5014355663623529, 'min_weight_fraction_leaf': 0.23367475592947387}. Best is trial 12 with value: 0.6893948377364146.

Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.5965665236051502
[I 2024-04-16 20:56:43,600] Trial 30 finished with value: 0.6456022193348552 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 343, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.3838693489032564, 'min_weight_fraction_leaf': 0.03868084640768137}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 20:56:46,889] Trial 31 finished with value: 0.6357636806730822 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 407, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6314547671110565, 'min_weight_fraction_leaf': 0.09694658331929079}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 20:56:48,902] Trial 32 finished with value: 0.6804123600499585 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6271698755222064, 'min_weight_fraction_leaf': 0.06517834975211964}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 20:56:52,591] Trial 33 finished with value: 0.6365786420012995 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 478, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7080829400212425, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 12 with value: 0.6893948377364146.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:56:54,656] Trial 34 finished with value: 0.7155356593482886 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 453, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8180483921418293, 'min_weight_fraction_leaf': 0.043888888043336766}. Best is trial 34 with value: 0.7155356593482886.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.7296137339055794
[I 2024-04-16 20:56:56,647] Trial 35 finished with value: 0.7201777209592911 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 469, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.823785697207309, 'min_weight_fraction_leaf': 0.04482567402015712}. Best is trial 35 with value: 0.7201777209592911.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8
Fold 4 C-index: 0.4372623574144487
Fold 5 C-index: 0.5364806866952789
[I 2024-04-16 20:57:02,025] Trial 36 finished with value: 0.5928288460127173 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 457, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8174883075150029, 'min_weight_fraction_leaf': 0.03258275290622702}. Best is trial 35 with value: 0.7201777209592911.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 20:57:03,459] Trial 37 finished with value: 0.7005384759232852 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9327267449020715, 'min_weight_fraction_leaf': 0.06259116043714735}. Best is trial 35 with value: 0.7201777209592911.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 20:57:04,620] Trial 38 finished with value: 0.6532412720347762 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 413, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9318415222011842, 'min_weight_fraction_leaf': 0.11814667951535995}. Best is trial 35 with value: 0.7201777209592911.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.4448669201520912
Fold 5 C-index: 0.5321888412017167
[I 2024-04-16 20:57:14,106] Trial 39 finished with value: 0.5965108143185953 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 499, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9315930595427037, 'min_weight_fraction_leaf': 0.023733775697961874}. Best is trial 35 with value: 0.7201777209592911.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 20:57:15,567] Trial 40 finished with value: 0.6332134763951922 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 468, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.837781093478085, 'min_weight_fraction_leaf': 0.16594433686505833}. Best is trial 35 with value: 0.7201777209592911.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:57:17,601] Trial 41 finished with value: 0.7107290321499047 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 457, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9543705464569276, 'min_weight_fraction_leaf': 0.0657454932274403}. Best is trial 35 with value: 0.7201777209592911.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:57:19,598] Trial 42 finished with value: 0.7083965693286869 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 449, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9475954940198432, 'min_weight_fraction_leaf': 0.06335625278080623}. Best is trial 35 with value: 0.7201777209592911.
Fold 1 C-index: 0.4581673306772908
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.721030042918455
[I 2024-04-16 20:57:21,493] Trial 43 finished with value: 0.7209093964346722 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 446, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9000973568009056, 'min_weight_fraction_leaf': 0.056305702529444654}. Best is trial 43 with value: 0.7209093964346722.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.5836909871244635
[I 2024-04-16 20:57:23,108] Trial 44 finished with value: 0.6478891980528484 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 416, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7954699014905364, 'min_weight_fraction_leaf': 0.12591169089602797}. Best is trial 43 with value: 0.7209093964346722.

Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 20:57:24,599] Trial 45 finished with value: 0.668498624477363 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 437, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.889094813384573, 'min_weight_fraction_leaf': 0.08103891634566349}. Best is trial 43 with value: 0.7209093964346722.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.5965665236051502
[I 2024-04-16 20:57:25,985] Trial 46 finished with value: 0.6576097095303036 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 447, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7711834009903045, 'min_weight_fraction_leaf': 0.10733046158745516}. Best is trial 43 with value: 0.7209093964346722.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.48068669527896996
[I 2024-04-16 20:57:30,322] Trial 47 finished with value: 0.5685430611790252 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 393, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8522031488865631, 'min_weight_fraction_leaf': 0.2765601881911346}. Best is trial 43 with value: 0.7209093964346722.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:57:32,884] Trial 48 finished with value: 0.6278944912550728 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9982403614933315, 'min_weight_fraction_leaf': 0.0530755289862218}. Best is trial 43 with value: 0.7209093964346722.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.7034883720930233
Fold 3 C-index: 0.7936170212765957
Fold 4 C-index: 0.5494296577946768
Fold 5 C-index: 0.5042918454935622
[I 2024-04-16 20:57:33,810] Trial 49 finished with value: 0.5994084072200179 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 351, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.942530060537976, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 43 with value: 0.7209093964346722.
Fold 1 C-index: 0.46613545816733065
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 20:57:35,355] Trial 50 finished with value: 0.6852241929422899 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9017439796465061, 'min_weight_fraction_leaf': 0.02637904231224953}. Best is trial 43 with value: 0.7209093964346722.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:57:37,848] Trial 51 finished with value: 0.7070537148123461 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.957889367228467, 'min_weight_fraction_leaf': 0.07039297189557424}. Best is trial 43 with value: 0.7209093964346722.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:57:39,216] Trial 52 finished with value: 0.7028595281700623 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 430, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9688992428720912, 'min_weight_fraction_leaf': 0.07350902992895046}. Best is trial 43 with value: 0.7209093964346722.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.5836909871244635
[I 2024-04-16 20:57:41,171] Trial 53 finished with value: 0.6406020923155824 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.811429400906098, 'min_weight_fraction_leaf': 0.14085805205722302}. Best is trial 43 with value: 0.7209093964346722.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 20:57:43,041] Trial 54 finished with value: 0.6853196333110925 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 481, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8580961059370431, 'min_weight_fraction_leaf': 0.08955049846016899}. Best is trial 43 with value: 0.7209093964346722.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 20:57:44,701] Trial 55 finished with value: 0.7015462756899271 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 453, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9107195281926364, 'min_weight_fraction_leaf': 0.0494183137557324}. Best is trial 43 with value: 0.7209093964346722.
Fold 1 C-index: 0.4103585657370518
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8063829787234043
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.5429184549356223
[I 2024-04-16 20:57:45,352] Trial 56 finished with value: 0.6169274312465631 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 141, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9749039106241505, 'min_weight_fraction_leaf': 0.3713883992399066}. Best is trial 43 with value: 0.7209093964346722.
Fold 1 C-index: 0.46613545816733065
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.7381974248927039
[I 2024-04-16 20:57:46,887] Trial 57 finished with value: 0.7229683608558997 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 377, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9541521788875019, 'min_weight_fraction_leaf': 0.018077632109095035}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.4581673306772908
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 20:57:48,684] Trial 58 finished with value: 0.6992470122630908 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 374, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8813451479355826, 'min_weight_fraction_leaf': 0.018535508507483717}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5064377682403434
[I 2024-04-16 20:58:00,362] Trial 59 finished with value: 0.5993658443412595 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 430, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7595102731583147, 'min_weight_fraction_leaf': 0.00015761268301821285}. Best is trial 57 with value: 0.7229683608558997.

Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 20:58:02,598] Trial 60 finished with value: 0.6297334780315407 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 401, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8255288729855027, 'min_weight_fraction_leaf': 0.0368391734181079}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.4581673306772908
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 20:58:04,507] Trial 61 finished with value: 0.7147352656753702 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 480, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9539912593414809, 'min_weight_fraction_leaf': 0.06135659994431437}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.7339055793991416
[I 2024-04-16 20:58:10,927] Trial 62 finished with value: 0.716575540415268 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9091655231538246, 'min_weight_fraction_leaf': 0.02009115242609827}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.4701195219123506
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 20:58:16,625] Trial 63 finished with value: 0.7031732275691517 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9053534707148779, 'min_weight_fraction_leaf': 0.012866603384629426}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.46613545816733065
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.7339055793991416
[I 2024-04-16 20:58:20,202] Trial 64 finished with value: 0.7198897554425467 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8635885229903125, 'min_weight_fraction_leaf': 0.02360422677500579}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.7510729613733905
[I 2024-04-16 20:58:22,905] Trial 65 finished with value: 0.7224615622367294 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 496, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8550412886514629, 'min_weight_fraction_leaf': 0.02655474803316548}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:58:26,117] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 495, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8659189626991826, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.703862660944206
[I 2024-04-16 20:58:27,958] Trial 67 finished with value: 0.7007568951966834 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 232, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7913270748335789, 'min_weight_fraction_leaf': 0.02958915222179802}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.5836909871244635
[I 2024-04-16 20:58:30,444] Trial 68 finished with value: 0.6379588605343504 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 427, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.22939188072225208, 'min_weight_fraction_leaf': 0.010269375709458538}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 20:58:33,332] Trial 69 finished with value: 0.6805890127571563 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 476, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8377038515230356, 'min_weight_fraction_leaf': 0.04388006948848686}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.43346007604562736
Fold 5 C-index: 0.48497854077253216
[I 2024-04-16 20:58:42,890] Trial 70 finished with value: 0.5634942961817113 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 324, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9092239382090552, 'min_weight_fraction_leaf': 0.016861496863972543}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 20:58:45,670] Trial 71 finished with value: 0.6925382835671692 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7225350838191404, 'min_weight_fraction_leaf': 0.0518675237163098}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.46215139442231074
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.721030042918455
[I 2024-04-16 20:58:49,647] Trial 72 finished with value: 0.7160586768410808 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8732117647451588, 'min_weight_fraction_leaf': 0.0007085578127863541}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.7296137339055794
[I 2024-04-16 20:58:52,699] Trial 73 finished with value: 0.7175362245006658 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8696654487921673, 'min_weight_fraction_leaf': 0.0006623586108428505}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.7253218884120172
[I 2024-04-16 20:58:54,381] Trial 74 finished with value: 0.7041760579099039 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8754998457286888, 'min_weight_fraction_leaf': 0.02819990284364924}. Best is trial 57 with value: 0.7229683608558997.

Fold 1 C-index: 0.46215139442231074
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 20:58:56,254] Trial 75 finished with value: 0.7009707588732197 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 467, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8628499129624474, 'min_weight_fraction_leaf': 0.00042461511325812135}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 20:58:58,658] Trial 76 finished with value: 0.6869775580228861 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7855036521095284, 'min_weight_fraction_leaf': 0.013262981049112567}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:59:00,637] Trial 77 finished with value: 0.709463022337849 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 440, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7378276418879555, 'min_weight_fraction_leaf': 0.02989226682987184}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.4262948207171315
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 20:59:02,300] Trial 78 finished with value: 0.6593595037010137 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 484, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6818438556543391, 'min_weight_fraction_leaf': 0.08794643626669672}. Best is trial 57 with value: 0.7229683608558997.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.7339055793991416
[I 2024-04-16 20:59:04,029] Trial 79 finished with value: 0.7245550884937771 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9247756553080357, 'min_weight_fraction_leaf': 0.00109030948921518}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.7253218884120172
[I 2024-04-16 20:59:05,603] Trial 80 finished with value: 0.7141099263879062 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 465, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9978341303899492, 'min_weight_fraction_leaf': 0.03933125497354244}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.7381974248927039
[I 2024-04-16 20:59:07,960] Trial 81 finished with value: 0.7214183806677952 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9172411478518057, 'min_weight_fraction_leaf': 0.01134017622108982}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.7424892703862661
[I 2024-04-16 20:59:09,486] Trial 82 finished with value: 0.71846661229887 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9141611456561967, 'min_weight_fraction_leaf': 0.023052799080087092}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:59:11,168] Trial 83 finished with value: 0.6246984094872932 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 419, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9232730054996355, 'min_weight_fraction_leaf': 0.2113346050152473}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 20:59:12,611] Trial 84 finished with value: 0.6903870358579972 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 389, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8899914756387842, 'min_weight_fraction_leaf': 0.05446020356493447}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 20:59:14,218] Trial 85 finished with value: 0.6400732509028015 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.84197837951497, 'min_weight_fraction_leaf': 0.016465288183517956}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 20:59:15,704] Trial 86 finished with value: 0.6968319249715014 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 457, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9728506989328927, 'min_weight_fraction_leaf': 0.03764615325756165}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.4302788844621514
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 20:59:19,310] Trial 87 finished with value: 0.6334097864763081 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 472, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.931086063403242, 'min_weight_fraction_leaf': 0.008603617131427946}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.46215139442231074
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.4296577946768061
Fold 5 C-index: 0.48068669527896996
[I 2024-04-16 20:59:43,809] Trial 88 finished with value: 0.5859654476986422 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 419, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8249311652176502, 'min_weight_fraction_leaf': 0.10570416936432725}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.721030042918455
[I 2024-04-16 20:59:48,475] Trial 89 finished with value: 0.7078440699785372 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 436, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6004059785495843, 'min_weight_fraction_leaf': 0.02664838168653724}. Best is trial 79 with value: 0.7245550884937771.

Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 20:59:53,404] Trial 90 finished with value: 0.6836967854660334 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 461, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.890974190277339, 'min_weight_fraction_leaf': 0.07989867791170116}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.7381974248927039
[I 2024-04-16 20:59:58,146] Trial 91 finished with value: 0.7197663723351985 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 484, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9194703662130209, 'min_weight_fraction_leaf': 0.021490539645012068}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 21:00:03,386] Trial 92 finished with value: 0.7071850974396072 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.92373035273093, 'min_weight_fraction_leaf': 0.04829892908211131}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.4262948207171315
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.7510729613733905
[I 2024-04-16 21:00:08,544] Trial 93 finished with value: 0.7222434233852911 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 489, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9570128754132096, 'min_weight_fraction_leaf': 0.02893435296125911}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.7296137339055794
[I 2024-04-16 21:00:12,532] Trial 94 finished with value: 0.7143922114057586 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 488, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9586348409527833, 'min_weight_fraction_leaf': 0.03784273693682792}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.4581673306772908
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.7253218884120172
[I 2024-04-16 21:00:16,686] Trial 95 finished with value: 0.7028174911959304 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 472, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9867911046777268, 'min_weight_fraction_leaf': 0.05781373809328407}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.4262948207171315
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.591254752851711
Fold 5 C-index: 0.5321888412017167
[I 2024-04-16 21:00:20,731] Trial 96 finished with value: 0.616383440829751 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 443, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9483960307276963, 'min_weight_fraction_leaf': 0.3157465264411285}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.4302788844621514
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.7296137339055794
[I 2024-04-16 21:00:22,262] Trial 97 finished with value: 0.6951174784632104 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 83, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9226317736984265, 'min_weight_fraction_leaf': 0.0247362851866672}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 21:00:26,999] Trial 98 finished with value: 0.6447643675269149 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 410, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5484418064662228, 'min_weight_fraction_leaf': 0.07652152644173904}. Best is trial 79 with value: 0.7245550884937771.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.7072243346007605

[I 2024-04-16 21:00:30,665] A new study created in memory with name: no-name-a4453a26-6861-46f2-b798-f869078c735e

Fold 5 C-index: 0.7553648068669528
[I 2024-04-16 21:00:30,650] Trial 99 finished with value: 0.728403367449799 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8031091419587425, 'min_weight_fraction_leaf': 0.011753369939040801}. Best is trial 99 with value: 0.728403367449799.


* Best trial for C-index:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.728403367449799], datetime_start=datetime.datetime(2024, 4, 16, 21, 0, 27, 30691), datetime_complete=datetime.datetime(2024, 4, 16, 21, 0, 30, 649438), params={'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8031091419587425, 'min_weight_fraction_leaf': 0.011753369939040801}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=99, value=None)


* Best Score for C-index:
 0.728403367449799

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2523044030612966
Fold 2 IBS: 0.22613053474997197
Fold 3 IBS: 0.22317668788468817
Fold 4 IBS: 0.24920157826474987
Fold 5 IBS: 0.23507249619495327
[I 2024-04-16 21:00:42,704] Trial 0 finished with value: 0.23717714003113194 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.23717714003113194.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-16 21:00:58,051] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.247572439641589
Fold 2 IBS: 0.2295395445809998
Fold 3 IBS: 0.22722918343052995
Fold 4 IBS: 0.24449217036210993
Fold 5 IBS: 0.23241393899181975
[I 2024-04-16 21:01:07,209] Trial 2 finished with value: 0.2362494554014097 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24874119330428937
Fold 2 IBS: 0.22927180415535067
Fold 3 IBS: 0.22642124783951784
Fold 4 IBS: 0.24460566130541014
Fold 5 IBS: 0.23198506246355813
[I 2024-04-16 21:01:09,920] Trial 3 finished with value: 0.23620499381362525 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-16 21:01:18,298] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-16 21:01:21,537] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.2502689949303993
Fold 2 IBS: 0.22579447064608305
Fold 3 IBS: 0.22285120956617252
Fold 4 IBS: 0.24954347262976592
Fold 5 IBS: 0.23516218184944976
[I 2024-04-16 21:01:30,240] Trial 6 finished with value: 0.23672406592437412 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.25056473147804087
Fold 2 IBS: 0.22650101050355892
Fold 3 IBS: 0.22292621906622476
Fold 4 IBS: 0.25011232757629326
Fold 5 IBS: 0.23253943771114105
[I 2024-04-16 21:01:34,364] Trial 7 finished with value: 0.23652874526705175 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24823995215681852
Fold 2 IBS: 0.23144521413956914
Fold 3 IBS: 0.2265916189355215
Fold 4 IBS: 0.24451571774503486
Fold 5 IBS: 0.23115898151468248
[I 2024-04-16 21:01:35,290] Trial 8 finished with value: 0.2363902968983253 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.2468911070208424
Fold 2 IBS: 0.23155496740562406
Fold 3 IBS: 0.22908544101709413
Fold 4 IBS: 0.241841961966157
Fold 5 IBS: 0.2308459447380027
[I 2024-04-16 21:01:41,537] Trial 9 finished with value: 0.2360438844295441 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24639132397748723
Fold 2 IBS: 0.2321219944682762
Fold 3 IBS: 0.23014778573227282
Fold 4 IBS: 0.24116652117316656
Fold 5 IBS: 0.230116455926593
[I 2024-04-16 21:01:48,717] Trial 10 finished with value: 0.23598881625555915 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.15405910406247975, 'min_weight_fraction_leaf': 0.2021365903921304}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.2467688537936637
Fold 2 IBS: 0.2322080681528202
Fold 3 IBS: 0.22938016078037413
Fold 4 IBS: 0.24136642947325676
Fold 5 IBS: 0.2301266413449486
[I 2024-04-16 21:01:51,543] Trial 11 finished with value: 0.23597003070901268 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 144, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.3672551683469005, 'min_weight_fraction_leaf': 0.347504116185509}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24668701023505918
Fold 2 IBS: 0.2323595568129782
Fold 3 IBS: 0.2296503062622209
Fold 4 IBS: 0.24114066271982323
Fold 5 IBS: 0.2301959531760908
[I 2024-04-16 21:01:54,331] Trial 12 finished with value: 0.23600669784123446 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 181, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.33206624840949195, 'min_weight_fraction_leaf': 0.36522772926169184}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.2464489821657019
Fold 2 IBS: 0.23223261427232628
Fold 3 IBS: 0.22938264987802112
Fold 4 IBS: 0.24158958929085741
Fold 5 IBS: 0.2302237614412814
[I 2024-04-16 21:01:59,317] Trial 13 finished with value: 0.23597551940963762 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 226, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.487038868572692, 'min_weight_fraction_leaf': 0.2457332095376356}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.2468197705625413
Fold 2 IBS: 0.23246569615555565
Fold 3 IBS: 0.23023576210104316
Fold 4 IBS: 0.24179332119652028
Fold 5 IBS: 0.2303585504128786
[I 2024-04-16 21:01:59,947] Trial 14 finished with value: 0.2363346200857078 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 15, 'n_estimators': 24, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.22675535883810688, 'min_weight_fraction_leaf': 0.480369012500421}. Best is trial 1 with value: 0.2359075685671228.

Fold 1 IBS: 0.24645568961257175
Fold 2 IBS: 0.2320726760403173
Fold 3 IBS: 0.22957370848897726
Fold 4 IBS: 0.24154601700547965
Fold 5 IBS: 0.23047757245393147
[I 2024-04-16 21:02:01,749] Trial 15 finished with value: 0.23602513272025546 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 89, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6110403757015994, 'min_weight_fraction_leaf': 0.3621456204936384}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24700810852760485
Fold 2 IBS: 0.23231105571551772
Fold 3 IBS: 0.22970522380546488
Fold 4 IBS: 0.24126258901196168
Fold 5 IBS: 0.23031025113742737
[I 2024-04-16 21:02:04,974] Trial 16 finished with value: 0.23611944563959528 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3805133081905424, 'min_weight_fraction_leaf': 0.29667293434523284}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.2479162561932448
Fold 2 IBS: 0.23053585822764866
Fold 3 IBS: 0.227567361504625
Fold 4 IBS: 0.24457236885329897
Fold 5 IBS: 0.2329889783677827
[I 2024-04-16 21:02:10,154] Trial 17 finished with value: 0.23671616462932005 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 377, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6669715022051161, 'min_weight_fraction_leaf': 0.1955307058552177}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24661202473996643
Fold 2 IBS: 0.23223776861789278
Fold 3 IBS: 0.2293959858366703
Fold 4 IBS: 0.24152749365684498
Fold 5 IBS: 0.23021456138439217
[I 2024-04-16 21:02:13,899] Trial 18 finished with value: 0.23599756684715337 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 218, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5044560440228212, 'min_weight_fraction_leaf': 0.4260162129851871}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24672336393407196
Fold 2 IBS: 0.2322151581030464
Fold 3 IBS: 0.22997867912136186
Fold 4 IBS: 0.24121143046301785
Fold 5 IBS: 0.23012883319734678
[I 2024-04-16 21:02:17,381] Trial 19 finished with value: 0.23605149296376898 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 321, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.23939048306191058, 'min_weight_fraction_leaf': 0.22042968834899193}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24796068297637433
Fold 2 IBS: 0.23053663005197006
Fold 3 IBS: 0.2282342015853389
Fold 4 IBS: 0.2436741288780896
Fold 5 IBS: 0.23095381953174052
[I 2024-04-16 21:02:18,670] Trial 20 finished with value: 0.23627189260470266 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 83, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8940752356356966, 'min_weight_fraction_leaf': 0.28881891871571913}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24651273230846144
Fold 2 IBS: 0.23227002202312041
Fold 3 IBS: 0.22948611123218873
Fold 4 IBS: 0.24131428853681886
Fold 5 IBS: 0.230312148231617
[I 2024-04-16 21:02:20,867] Trial 21 finished with value: 0.2359790604664413 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 147, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.3845772713884219, 'min_weight_fraction_leaf': 0.3430677365625254}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24634200609178666
Fold 2 IBS: 0.23225527457004838
Fold 3 IBS: 0.22959575397559612
Fold 4 IBS: 0.241385099589382
Fold 5 IBS: 0.23041703084827303
[I 2024-04-16 21:02:27,445] Trial 22 finished with value: 0.2359990330150173 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 500, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.28511182724612805, 'min_weight_fraction_leaf': 0.42245867866620096}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24655676776068486
Fold 2 IBS: 0.23223068806491856
Fold 3 IBS: 0.22936350567260294
Fold 4 IBS: 0.24150660794605994
Fold 5 IBS: 0.23013528304140687
[I 2024-04-16 21:02:29,289] Trial 23 finished with value: 0.23595857049713467 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 130, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.4261683218207644, 'min_weight_fraction_leaf': 0.3271930017983034}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24657661436458503
Fold 2 IBS: 0.232119153466986
Fold 3 IBS: 0.22961774292223822
Fold 4 IBS: 0.24139579879708112
Fold 5 IBS: 0.2298611619168921
[I 2024-04-16 21:02:30,951] Trial 24 finished with value: 0.23591409429355653 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 97, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.45022665925542166, 'min_weight_fraction_leaf': 0.31428636259409815}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.2468669911550118
Fold 2 IBS: 0.2321250658650567
Fold 3 IBS: 0.22961434233123096
Fold 4 IBS: 0.24135573766917465
Fold 5 IBS: 0.23002426376797278
[I 2024-04-16 21:02:32,332] Trial 25 finished with value: 0.23599728015768937 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 93, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4383434916134097, 'min_weight_fraction_leaf': 0.3947510297319428}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.25175562610994523
Fold 2 IBS: 0.22828201209844007
Fold 3 IBS: 0.22498262008178696
Fold 4 IBS: 0.24582945918679494
Fold 5 IBS: 0.2352734115943027
[I 2024-04-16 21:02:34,046] Trial 26 finished with value: 0.237224625814254 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 117, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5086741884038717, 'min_weight_fraction_leaf': 0.16863579271898874}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.2512325383873563
Fold 2 IBS: 0.23361327810697397
Fold 3 IBS: 0.22905869316631944
Fold 4 IBS: 0.2567350115015803
Fold 5 IBS: 0.23176847661492148
[I 2024-04-16 21:02:34,322] Trial 27 finished with value: 0.2404815995554303 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 1, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.42174302648688455, 'min_weight_fraction_leaf': 0.2577776508541947}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.2472684180717887
Fold 2 IBS: 0.23252576369213562
Fold 3 IBS: 0.22981968076744358
Fold 4 IBS: 0.2417470929457932
Fold 5 IBS: 0.23109358503110466
[I 2024-04-16 21:02:35,404] Trial 28 finished with value: 0.23649090810165316 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 56, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.12127186383647975, 'min_weight_fraction_leaf': 0.3094282214281603}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.2463481556243907
Fold 2 IBS: 0.23225140995324683
Fold 3 IBS: 0.22975160909816422
Fold 4 IBS: 0.24128648514120266
Fold 5 IBS: 0.23029277989085567
[I 2024-04-16 21:02:40,662] Trial 29 finished with value: 0.235986087941572 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 400, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.30415060878430844, 'min_weight_fraction_leaf': 0.25394856164220847}. Best is trial 1 with value: 0.2359075685671228.

Fold 1 IBS: 0.2466509090859412
Fold 2 IBS: 0.23214878301411424
Fold 3 IBS: 0.2293161545437167
Fold 4 IBS: 0.2416001168061908
Fold 5 IBS: 0.23029389935280453
[I 2024-04-16 21:02:42,825] Trial 30 finished with value: 0.2360019725605535 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 176, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6685390299837802, 'min_weight_fraction_leaf': 0.39443765410475895}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24658437242309666
Fold 2 IBS: 0.23217269485057873
Fold 3 IBS: 0.22938349245574668
Fold 4 IBS: 0.24142526486365426
Fold 5 IBS: 0.23026356293423877
[I 2024-04-16 21:02:45,147] Trial 31 finished with value: 0.23596587750546302 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 195, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561656740670345, 'min_weight_fraction_leaf': 0.3309492921313831}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24661864304625838
Fold 2 IBS: 0.23208376604718664
Fold 3 IBS: 0.22925305998337298
Fold 4 IBS: 0.2415015536554909
Fold 5 IBS: 0.2302083938510298
[I 2024-04-16 21:02:46,790] Trial 32 finished with value: 0.23593308331666774 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 130, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5852788933969724, 'min_weight_fraction_leaf': 0.3063123854832265}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.2465868826713895
Fold 2 IBS: 0.2314440999884863
Fold 3 IBS: 0.2291058680113181
Fold 4 IBS: 0.24201093272708563
Fold 5 IBS: 0.2304182939911737
[I 2024-04-16 21:02:48,332] Trial 33 finished with value: 0.23591321547789063 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 121, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6340846708253914, 'min_weight_fraction_leaf': 0.2703122206935469}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.2476158939723347
Fold 2 IBS: 0.23142861235577553
Fold 3 IBS: 0.22892318349504762
Fold 4 IBS: 0.2422265975680181
Fold 5 IBS: 0.2313049691858836
[I 2024-04-16 21:02:53,555] Trial 34 finished with value: 0.23629985131541192 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 293, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7070507976105774, 'min_weight_fraction_leaf': 0.26731370386754366}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.2467614860985147
Fold 2 IBS: 0.2319338563642958
Fold 3 IBS: 0.22921445722373726
Fold 4 IBS: 0.2418495491194906
Fold 5 IBS: 0.23040012568700285
[I 2024-04-16 21:02:56,197] Trial 35 finished with value: 0.23603189489860826 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 114, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5002207619348458, 'min_weight_fraction_leaf': 0.22714458854021177}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.24854391957225147
Fold 2 IBS: 0.22565863080615062
Fold 3 IBS: 0.22434290985447994
Fold 4 IBS: 0.24726071645466732
Fold 5 IBS: 0.23243497725411333
[I 2024-04-16 21:02:57,284] Trial 36 finished with value: 0.23564823078833252 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 62, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5983609201212154, 'min_weight_fraction_leaf': 0.0994844837891381}. Best is trial 36 with value: 0.23564823078833252.
Fold 1 IBS: 0.24777071030080602
Fold 2 IBS: 0.22464653203622276
Fold 3 IBS: 0.224083023711396
Fold 4 IBS: 0.24735932012709846
Fold 5 IBS: 0.23198106953937375
[I 2024-04-16 21:02:58,319] Trial 37 finished with value: 0.2351681311429794 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 62, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7121369439374119, 'min_weight_fraction_leaf': 0.10064020105997977}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.24949529778958293
Fold 2 IBS: 0.22772044572864156
Fold 3 IBS: 0.22249888681280092
Fold 4 IBS: 0.25105047724014173
Fold 5 IBS: 0.23275239122488395
[I 2024-04-16 21:02:59,200] Trial 38 finished with value: 0.2367034997592102 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 50, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8369328550650088, 'min_weight_fraction_leaf': 0.09363070020903308}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.2440148864505285
Fold 2 IBS: 0.22853027661519348
Fold 3 IBS: 0.2186017915580577
Fold 4 IBS: 0.2576783791605543
Fold 5 IBS: 0.23265711942922543
[I 2024-04-16 21:02:59,533] Trial 39 finished with value: 0.2362964906427119 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 8, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7449130098551711, 'min_weight_fraction_leaf': 0.05969646314471774}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.2485945290671692
Fold 2 IBS: 0.22855090241449386
Fold 3 IBS: 0.22516973392254228
Fold 4 IBS: 0.2488339109198692
Fold 5 IBS: 0.23226363410224732
[I 2024-04-16 21:03:00,282] Trial 40 finished with value: 0.23668254208526437 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 31, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6396180152873276, 'min_weight_fraction_leaf': 0.1285525853587552}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.2473831540402364
Fold 2 IBS: 0.22968742436191456
Fold 3 IBS: 0.22751359513100516
Fold 4 IBS: 0.24391930013682964
Fold 5 IBS: 0.23085214240989632
[I 2024-04-16 21:03:01,413] Trial 41 finished with value: 0.23587112321597642 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 68, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6177482052777868, 'min_weight_fraction_leaf': 0.10389324383557505}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.24837396599286762
Fold 2 IBS: 0.22977376116905335
Fold 3 IBS: 0.22721668252388538
Fold 4 IBS: 0.2433812950101447
Fold 5 IBS: 0.23049318047206152
[I 2024-04-16 21:03:02,637] Trial 42 finished with value: 0.23584777703360255 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 69, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7204109520940286, 'min_weight_fraction_leaf': 0.09264081723179494}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.2478671878303341
Fold 2 IBS: 0.2296135238738452
Fold 3 IBS: 0.22658445761870974
Fold 4 IBS: 0.24443961255671115
Fold 5 IBS: 0.23096763445657922
[I 2024-04-16 21:03:03,615] Trial 43 finished with value: 0.2358944832672359 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 59, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7282268189622885, 'min_weight_fraction_leaf': 0.09141881737779102}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.2480255050659437
Fold 2 IBS: 0.22934860588263975
Fold 3 IBS: 0.22679647769063016
Fold 4 IBS: 0.2438571076022416
Fold 5 IBS: 0.23071387991185646
[I 2024-04-16 21:03:04,999] Trial 44 finished with value: 0.2357483152306623 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 66, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.72001504969646, 'min_weight_fraction_leaf': 0.0905001485932517}. Best is trial 37 with value: 0.2351681311429794.

Fold 1 IBS: 0.2503238480535292
Fold 2 IBS: 0.22832308515260305
Fold 3 IBS: 0.22312583056505117
Fold 4 IBS: 0.24757766108141138
Fold 5 IBS: 0.2298732183504811
[I 2024-04-16 21:03:06,085] Trial 45 finished with value: 0.23584472864061518 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 75, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8505275653973254, 'min_weight_fraction_leaf': 0.010891498916606263}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.25423248317390557
Fold 2 IBS: 0.23009681280030897
Fold 3 IBS: 0.22359000801229995
Fold 4 IBS: 0.25495747346505554
Fold 5 IBS: 0.23097528293655295
[I 2024-04-16 21:03:06,864] Trial 46 finished with value: 0.23877041207762462 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 27, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8626577946229981, 'min_weight_fraction_leaf': 0.026285989554988252}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.2528807244138315
Fold 2 IBS: 0.2275123548801536
Fold 3 IBS: 0.2228232386976546
Fold 4 IBS: 0.24868997485827501
Fold 5 IBS: 0.2298834681714856
[I 2024-04-16 21:03:08,333] Trial 47 finished with value: 0.23635795220428008 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 75, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.987423813760983, 'min_weight_fraction_leaf': 0.058626187519869886}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.25383529554846124
Fold 2 IBS: 0.22489660891113203
Fold 3 IBS: 0.22321320929583838
Fold 4 IBS: 0.2569286677970014
Fold 5 IBS: 0.22867019926125984
[I 2024-04-16 21:03:09,102] Trial 48 finished with value: 0.23750879616273854 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 39, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7986195780539649, 'min_weight_fraction_leaf': 0.008283500149621842}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.24843103759082555
Fold 2 IBS: 0.22892612909102902
Fold 3 IBS: 0.22599760388840903
Fold 4 IBS: 0.24491337927310955
Fold 5 IBS: 0.23178009861010135
[I 2024-04-16 21:03:10,866] Trial 49 finished with value: 0.23600964969069488 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 164, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9125790912134019, 'min_weight_fraction_leaf': 0.1466508316835494}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.24807964294931859
Fold 2 IBS: 0.22914957327572263
Fold 3 IBS: 0.22744346754815134
Fold 4 IBS: 0.24370327134905811
Fold 5 IBS: 0.23121449283381926
[I 2024-04-16 21:03:12,721] Trial 50 finished with value: 0.235918089591214 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 102, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7064120732925062, 'min_weight_fraction_leaf': 0.07337232753560016}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.248626188965157
Fold 2 IBS: 0.23034190696924403
Fold 3 IBS: 0.22657784737950828
Fold 4 IBS: 0.24401864489406408
Fold 5 IBS: 0.23053908684031407
[I 2024-04-16 21:03:13,906] Trial 51 finished with value: 0.23602073500965748 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 70, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7663376938932135, 'min_weight_fraction_leaf': 0.10649336738085421}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.24744197531263565
Fold 2 IBS: 0.2297554101197567
Fold 3 IBS: 0.22702171549445802
Fold 4 IBS: 0.2440355508414557
Fold 5 IBS: 0.2305633773535828
[I 2024-04-16 21:03:15,047] Trial 52 finished with value: 0.23576360582437778 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 68, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5995221694301173, 'min_weight_fraction_leaf': 0.0396232863086937}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.24929575872318147
Fold 2 IBS: 0.2312816796712631
Fold 3 IBS: 0.2285343043968388
Fold 4 IBS: 0.24849387823919702
Fold 5 IBS: 0.23181311142670383
[I 2024-04-16 21:03:15,619] Trial 53 finished with value: 0.23788374649143687 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 20, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7013783844931945, 'min_weight_fraction_leaf': 0.03525729734720413}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.24876868974006414
Fold 2 IBS: 0.23065516965552696
Fold 3 IBS: 0.22494054504377015
Fold 4 IBS: 0.24555716180279177
Fold 5 IBS: 0.23238892905099726
[I 2024-04-16 21:03:16,603] Trial 54 finished with value: 0.23646209905863005 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 42, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9272655199904987, 'min_weight_fraction_leaf': 0.06899979362667291}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.2491474840996583
Fold 2 IBS: 0.22687803972416826
Fold 3 IBS: 0.2247161464529968
Fold 4 IBS: 0.2490227578053366
Fold 5 IBS: 0.23107658175729914
[I 2024-04-16 21:03:18,075] Trial 55 finished with value: 0.23616820196789182 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 78, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5954590169653899, 'min_weight_fraction_leaf': 0.0168780650319601}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.2503617383009278
Fold 2 IBS: 0.2281882903913592
Fold 3 IBS: 0.2235733823316234
Fold 4 IBS: 0.24763685574283775
Fold 5 IBS: 0.23062325158896738
[I 2024-04-16 21:03:19,512] Trial 56 finished with value: 0.23607670367114314 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 103, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8336144224039524, 'min_weight_fraction_leaf': 0.0448891217047451}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.24770295001231277
Fold 2 IBS: 0.23066217783121828
Fold 3 IBS: 0.2275074444923111
Fold 4 IBS: 0.244262707825068
Fold 5 IBS: 0.23185172939755
[I 2024-04-16 21:03:21,788] Trial 57 finished with value: 0.23639740191169203 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 148, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5401171970657141, 'min_weight_fraction_leaf': 0.16739592719148783}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.24822566177132505
Fold 2 IBS: 0.22962434558185033
Fold 3 IBS: 0.22711447399555174
Fold 4 IBS: 0.24451115178859248
Fold 5 IBS: 0.23159200406528274
[I 2024-04-16 21:03:22,741] Trial 58 finished with value: 0.23621352744052046 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 55, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6659973923607253, 'min_weight_fraction_leaf': 0.12002145637830286}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.2511984505075943
Fold 2 IBS: 0.22660738738680067
Fold 3 IBS: 0.22723307432595874
Fold 4 IBS: 0.24874546032724473
Fold 5 IBS: 0.22878112835983372
[I 2024-04-16 21:03:23,141] Trial 59 finished with value: 0.23651310018148647 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 14, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7481427278365822, 'min_weight_fraction_leaf': 0.00022174170041590335}. Best is trial 37 with value: 0.2351681311429794.

Fold 1 IBS: 0.24861024845564955
Fold 2 IBS: 0.22628374640473373
Fold 3 IBS: 0.22304190204035124
Fold 4 IBS: 0.24895737324177963
Fold 5 IBS: 0.23206607842779056
[I 2024-04-16 21:03:24,275] Trial 60 finished with value: 0.23579186971406094 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 85, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5421651479480726, 'min_weight_fraction_leaf': 0.08280808152330867}. Best is trial 37 with value: 0.2351681311429794.
Fold 1 IBS: 0.24827434177310634
Fold 2 IBS: 0.22497819527176266
Fold 3 IBS: 0.22107121877038577
Fold 4 IBS: 0.24897519780858499
Fold 5 IBS: 0.23171809515894556
[I 2024-04-16 21:03:25,369] Trial 61 finished with value: 0.23500340975655706 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 90, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5337001111989792, 'min_weight_fraction_leaf': 0.08081935175314843}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.2484391124574456
Fold 2 IBS: 0.22540696499328167
Fold 3 IBS: 0.22201786343158572
Fold 4 IBS: 0.2500818127477528
Fold 5 IBS: 0.23372342798931897
[I 2024-04-16 21:03:26,812] Trial 62 finished with value: 0.23593383632387693 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 95, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5578675182867163, 'min_weight_fraction_leaf': 0.07485880510286393}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.25600407460827207
Fold 2 IBS: 0.21796035941427094
Fold 3 IBS: 0.21731533187257573
Fold 4 IBS: 0.25275706504204054
Fold 5 IBS: 0.23555193214108008
[I 2024-04-16 21:03:27,307] Trial 63 finished with value: 0.23591775261564787 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 36, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5316734195128887, 'min_weight_fraction_leaf': 0.04151839959145128}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.24754225017185025
Fold 2 IBS: 0.22757364064299015
Fold 3 IBS: 0.22620700069595204
Fold 4 IBS: 0.24686962320972233
Fold 5 IBS: 0.23202909639808958
[I 2024-04-16 21:03:28,388] Trial 64 finished with value: 0.23604432222372088 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 88, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5922494869833886, 'min_weight_fraction_leaf': 0.14093370586791484}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.2556132992010361
Fold 2 IBS: 0.21724158141344446
Fold 3 IBS: 0.21370984286375252
Fold 4 IBS: 0.2673823465495639
Fold 5 IBS: 0.23641242003775703
[I 2024-04-16 21:03:29,755] Trial 65 finished with value: 0.23807189801311082 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 132, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4723398037619898, 'min_weight_fraction_leaf': 0.01999355461402527}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.2548851341148959
Fold 2 IBS: 0.22268859392323664
Fold 3 IBS: 0.21997813318197051
Fold 4 IBS: 0.25426768204947287
Fold 5 IBS: 0.23653983007276316
[I 2024-04-16 21:03:31,994] Trial 66 finished with value: 0.23767187466846784 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 230, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6858605331756779, 'min_weight_fraction_leaf': 0.05549641679841047}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.2518644052519374
Fold 2 IBS: 0.22152583739640472
Fold 3 IBS: 0.2216898331512857
Fold 4 IBS: 0.2568854371767988
Fold 5 IBS: 0.23453978660049055
[I 2024-04-16 21:03:33,173] Trial 67 finished with value: 0.23730105991538344 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 112, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.945996281904843, 'min_weight_fraction_leaf': 0.08084170543462411}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.2477464699534922
Fold 2 IBS: 0.22958236825127237
Fold 3 IBS: 0.22830847127672213
Fold 4 IBS: 0.2467658214638412
Fold 5 IBS: 0.23143367980075003
[I 2024-04-16 21:03:33,804] Trial 68 finished with value: 0.2367673621492156 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 51, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5232855484533638, 'min_weight_fraction_leaf': 0.16792869611866185}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.24740716585615008
Fold 2 IBS: 0.2299696426358062
Fold 3 IBS: 0.22616867503286203
Fold 4 IBS: 0.24463922203175298
Fold 5 IBS: 0.23095333777899704
[I 2024-04-16 21:03:34,691] Trial 69 finished with value: 0.23582760866711366 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 82, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6179331591403852, 'min_weight_fraction_leaf': 0.1219869641740862}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.24832320516670547
Fold 2 IBS: 0.22927427159647504
Fold 3 IBS: 0.22638345185354933
Fold 4 IBS: 0.24433242144036052
Fold 5 IBS: 0.2315656251888676
[I 2024-04-16 21:03:36,031] Trial 70 finished with value: 0.23597579504919158 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 136, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6341002899652868, 'min_weight_fraction_leaf': 0.11366205819150008}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.24714710435673642
Fold 2 IBS: 0.2299992918947307
Fold 3 IBS: 0.22736543867454895
Fold 4 IBS: 0.24438988450365348
Fold 5 IBS: 0.23102216140637732
[I 2024-04-16 21:03:37,055] Trial 71 finished with value: 0.23598477616720936 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 80, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5774000194155828, 'min_weight_fraction_leaf': 0.13849444035817793}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.24763877249053365
Fold 2 IBS: 0.22948398114359567
Fold 3 IBS: 0.22577935352875317
Fold 4 IBS: 0.2450889863930316
Fold 5 IBS: 0.2313018289213118
[I 2024-04-16 21:03:37,955] Trial 72 finished with value: 0.2358585844954452 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 64, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6135295480067948, 'min_weight_fraction_leaf': 0.08397295633578646}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.2500539846291156
Fold 2 IBS: 0.22766579945322615
Fold 3 IBS: 0.22508020645680873
Fold 4 IBS: 0.24801137457684888
Fold 5 IBS: 0.2325203292240118
[I 2024-04-16 21:03:39,720] Trial 73 finished with value: 0.23666633886800223 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 158, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6582701282005872, 'min_weight_fraction_leaf': 0.04876081924984827}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.24873364004515838
Fold 2 IBS: 0.22462450592113578
Fold 3 IBS: 0.22232386228490092
Fold 4 IBS: 0.25158341611436524
Fold 5 IBS: 0.23281054274297458
[I 2024-04-16 21:03:40,889] Trial 74 finished with value: 0.23601519342170696 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 105, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.47123388163591046, 'min_weight_fraction_leaf': 0.02729858688331159}. Best is trial 61 with value: 0.23500340975655706.

Fold 1 IBS: 0.2476186048371288
Fold 2 IBS: 0.22872664517046198
Fold 3 IBS: 0.22689052239411525
Fold 4 IBS: 0.24591981570934932
Fold 5 IBS: 0.23215103509735893
[I 2024-04-16 21:03:41,797] Trial 75 finished with value: 0.23626132464168284 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 82, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.546882037911445, 'min_weight_fraction_leaf': 0.15537264884677487}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.2484067040187848
Fold 2 IBS: 0.23025709083694096
Fold 3 IBS: 0.2273416756984175
Fold 4 IBS: 0.2444028493197838
Fold 5 IBS: 0.23289787879407822
[I 2024-04-16 21:03:44,973] Trial 76 finished with value: 0.23666123973360106 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 331, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6830175182967719, 'min_weight_fraction_leaf': 0.18905828900903313}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.2491729268465246
Fold 2 IBS: 0.2288838306092196
Fold 3 IBS: 0.2244966291077952
Fold 4 IBS: 0.24559281749271553
Fold 5 IBS: 0.23248379746334494
[I 2024-04-16 21:03:45,532] Trial 77 finished with value: 0.23612600030391998 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 41, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8299597876307446, 'min_weight_fraction_leaf': 0.1289598164349548}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.24777757755453794
Fold 2 IBS: 0.2294157415469648
Fold 3 IBS: 0.2267892914226937
Fold 4 IBS: 0.24476974863819226
Fold 5 IBS: 0.23124144717854428
[I 2024-04-16 21:03:47,268] Trial 78 finished with value: 0.23599876126818659 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 119, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6124904037727563, 'min_weight_fraction_leaf': 0.10335570071215829}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.24575430582733102
Fold 2 IBS: 0.22473873425868357
Fold 3 IBS: 0.22493915247326504
Fold 4 IBS: 0.25305638265328895
Fold 5 IBS: 0.23008149268619646
[I 2024-04-16 21:03:47,849] Trial 79 finished with value: 0.235714013579753 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 17, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7768345374933093, 'min_weight_fraction_leaf': 0.0648209769750793}. Best is trial 61 with value: 0.23500340975655706.
Fold 1 IBS: 0.24256465352626866
Fold 2 IBS: 0.22933462491340492
Fold 3 IBS: 0.22465906301052208
Fold 4 IBS: 0.24586134416553454
Fold 5 IBS: 0.2317987960242181
[I 2024-04-16 21:03:48,200] Trial 80 finished with value: 0.23484369632798968 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 9, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8069832056643363, 'min_weight_fraction_leaf': 0.06745642941538181}. Best is trial 80 with value: 0.23484369632798968.
Fold 1 IBS: 0.24249622911903032
Fold 2 IBS: 0.22655720272526775
Fold 3 IBS: 0.21937642140519134
Fold 4 IBS: 0.2452930572521113
Fold 5 IBS: 0.23247332316517602
[I 2024-04-16 21:03:48,474] Trial 81 finished with value: 0.23323924673335536 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7941950203899084, 'min_weight_fraction_leaf': 0.0647704116037696}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.2444510564501628
Fold 2 IBS: 0.22608125352302993
Fold 3 IBS: 0.22166671120548964
Fold 4 IBS: 0.24975019317194344
Fold 5 IBS: 0.2277543320907754
[I 2024-04-16 21:03:48,769] Trial 82 finished with value: 0.23394070928828023 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 3, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7919974615046973, 'min_weight_fraction_leaf': 0.06350985905035998}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.2391396536971552
Fold 2 IBS: 0.24455937237369532
Fold 3 IBS: 0.2631970448311286
Fold 4 IBS: 0.23333627334833823
Fold 5 IBS: 0.22596773313621324
[I 2024-04-16 21:03:48,968] Trial 83 finished with value: 0.24124001547730614 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 1, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8028782331636168, 'min_weight_fraction_leaf': 0.06442223548081907}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.2508115627959639
Fold 2 IBS: 0.22927660231465444
Fold 3 IBS: 0.22446059907231813
Fold 4 IBS: 0.24434937760426606
Fold 5 IBS: 0.22799874240007245
[I 2024-04-16 21:03:49,270] Trial 84 finished with value: 0.23537937683745497 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 17, 'n_estimators': 15, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7765188632346391, 'min_weight_fraction_leaf': 0.03296958371584946}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.25015940868159
Fold 2 IBS: 0.23051699891251345
Fold 3 IBS: 0.22575123466104924
Fold 4 IBS: 0.24830980903451727
Fold 5 IBS: 0.23187112235215784
[I 2024-04-16 21:03:49,658] Trial 85 finished with value: 0.23732171472836558 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 21, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7785222207044032, 'min_weight_fraction_leaf': 0.09774705283986003}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.2459412259963103
Fold 2 IBS: 0.2286925589118752
Fold 3 IBS: 0.22241251291013986
Fold 4 IBS: 0.24373138583592652
Fold 5 IBS: 0.228984637314713
[I 2024-04-16 21:03:49,911] Trial 86 finished with value: 0.23395246419379298 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 7, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8704970782833359, 'min_weight_fraction_leaf': 0.052800209594485836}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.24849764210693095
Fold 2 IBS: 0.2290684458433327
Fold 3 IBS: 0.22489154288974972
Fold 4 IBS: 0.24536134244867344
Fold 5 IBS: 0.22773355774297732
[I 2024-04-16 21:03:50,226] Trial 87 finished with value: 0.23511050620633284 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 12, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8941628296524573, 'min_weight_fraction_leaf': 0.032542096719715474}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.24577513103755172
Fold 2 IBS: 0.22906766783780658
Fold 3 IBS: 0.22343797291952205
Fold 4 IBS: 0.24352173806955618
Fold 5 IBS: 0.22923563427876864
[I 2024-04-16 21:03:50,529] Trial 88 finished with value: 0.23420762882864105 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 8, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8751804131450004, 'min_weight_fraction_leaf': 0.02823456837667611}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.24842224365169893
Fold 2 IBS: 0.2289315086467645
Fold 3 IBS: 0.22499143032813368
Fold 4 IBS: 0.24539391066614263
Fold 5 IBS: 0.22741985087714753
[I 2024-04-16 21:03:50,823] Trial 89 finished with value: 0.23503178883397746 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 17, 'n_estimators': 12, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8821027260753246, 'min_weight_fraction_leaf': 0.027667317103617597}. Best is trial 81 with value: 0.23323924673335536.

Fold 1 IBS: 0.2472898739458269
Fold 2 IBS: 0.22726208935373643
Fold 3 IBS: 0.22289296673786196
Fold 4 IBS: 0.2504906341074561
Fold 5 IBS: 0.23197377846213324
[I 2024-04-16 21:03:51,058] Trial 90 finished with value: 0.23598186852140293 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 18, 'n_estimators': 3, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.873448690418433, 'min_weight_fraction_leaf': 0.05305541913345835}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.25088821247966814
Fold 2 IBS: 0.22829990283554244
Fold 3 IBS: 0.22583027016783427
Fold 4 IBS: 0.24669491907386742
Fold 5 IBS: 0.2315666548174323
[I 2024-04-16 21:03:51,568] Trial 91 finished with value: 0.2366559918748689 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 17, 'n_estimators': 30, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8846557791063201, 'min_weight_fraction_leaf': 0.03343570454695601}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.24921827178070394
Fold 2 IBS: 0.2287510009263102
Fold 3 IBS: 0.22312241388440285
Fold 4 IBS: 0.24385926228829072
Fold 5 IBS: 0.22906030054978174
[I 2024-04-16 21:03:51,839] Trial 92 finished with value: 0.23480224988589787 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 18, 'n_estimators': 10, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9543292558011023, 'min_weight_fraction_leaf': 0.021837010201786994}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.24638780369780797
Fold 2 IBS: 0.22975747432480473
Fold 3 IBS: 0.22344789629608372
Fold 4 IBS: 0.24351948489380756
Fold 5 IBS: 0.23024084442626067
[I 2024-04-16 21:03:52,113] Trial 93 finished with value: 0.23467070072775292 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 18, 'n_estimators': 9, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9535894312529835, 'min_weight_fraction_leaf': 0.01912662608780027}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.24914840854421078
Fold 2 IBS: 0.22813443158563093
Fold 3 IBS: 0.22650049377280423
Fold 4 IBS: 0.24517097148958744
Fold 5 IBS: 0.22775029307393613
[I 2024-04-16 21:03:52,454] Trial 94 finished with value: 0.2353409196932339 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 11, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9593716838931644, 'min_weight_fraction_leaf': 0.01624330784864996}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.2497736134773388
Fold 2 IBS: 0.23002013935720875
Fold 3 IBS: 0.2267128356439495
Fold 4 IBS: 0.24726213418763193
Fold 5 IBS: 0.23226605315579943
[I 2024-04-16 21:03:52,920] Trial 95 finished with value: 0.2372069551643857 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19, 'n_estimators': 28, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9051869127401942, 'min_weight_fraction_leaf': 0.006790670600951239}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.25275491535572864
Fold 2 IBS: 0.22888024596414194
Fold 3 IBS: 0.23054041830134572
Fold 4 IBS: 0.24400921855775692
Fold 5 IBS: 0.23589099081415266
[I 2024-04-16 21:03:53,113] Trial 96 finished with value: 0.23841515779862518 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 18, 'n_estimators': 2, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9333121759524978, 'min_weight_fraction_leaf': 0.025094579825132673}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.24863421656726795
Fold 2 IBS: 0.22969456300587224
Fold 3 IBS: 0.22581252808525037
Fold 4 IBS: 0.24575210890609803
Fold 5 IBS: 0.23167984170852576
[I 2024-04-16 21:03:53,723] Trial 97 finished with value: 0.23631465165460286 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 20, 'n_estimators': 45, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8181952473384937, 'min_weight_fraction_leaf': 0.04777319604129934}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.25040084516611605
Fold 2 IBS: 0.22964276190292468
Fold 3 IBS: 0.22605711469524864
Fold 4 IBS: 0.24874413709322218
Fold 5 IBS: 0.23305424007733044
[I 2024-04-16 21:03:54,137] Trial 98 finished with value: 0.23757981978696838 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 25, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9636868869959563, 'min_weight_fraction_leaf': 0.0010477032420138574}. Best is trial 81 with value: 0.23323924673335536.
Fold 1 IBS: 0.2485394250465903
Fold 2 IBS: 0.22881666683471932
Fold 3 IBS: 0.2255481308266087
Fold 4 IBS: 0.24389507292356877
Fold 5 IBS: 0.2281729033269675
[I 2024-04-16 21:03:54,514] Trial 99 finished with value: 0.2349944397916909 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 19, 'n_estimators': 15, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8575579516658156, 'min_weight_fraction_leaf': 0.018245322513789658}. Best is trial 81 with value: 0.23323924673335536.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.23323924673335536], datetime_start=datetime.datetime(2024, 4, 16, 21, 3, 48, 205139), datetime_complete=datetime.datetime(2024, 4, 16, 21, 3, 48, 473389), params={'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7941950203899084, 'min_weight_fraction_leaf': 0.0647704116037696}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=81, value=None)


* Best Score for IBS:
 0.23323924673335536

In [101]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [102]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.728
train_ibs:  0.233

#### Test

In [103]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [104]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=15, max_features='auto', max_leaf_nodes=10,
                   max_samples=0.8031091419587425, min_samples_leaf=2,
                   min_weight_fraction_leaf=0.011753369939040801,
                   n_estimators=473, random_state=123, warm_start=True)

C-index score: 0.59

ExtraSurvivalTrees(max_depth=17, max_features='log2', max_leaf_nodes=20,
                   max_samples=0.7941950203899084, min_samples_leaf=10,
                   min_samples_split=15,
                   min_weight_fraction_leaf=0.0647704116037696, n_estimators=6,
                   random_state=123, warm_start=True)

IBS: 0.228

In [105]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [106]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 21:03:55,714] A new study created in memory with name: no-name-7ed0dc64-d63d-4b39-9e1d-9472c41476f4

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:04:17,920] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:04:30,986] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:04:45,188] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:05:08,071] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:05:16,047] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:05:17,990] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:05:41,903] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:05:48,689] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:05:49,763] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.4601593625498008
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7425531914893617
Fold 4 C-index: 0.46577946768060835
Fold 5 C-index: 0.4871244635193133
[I 2024-04-16 21:06:41,538] Trial 9 finished with value: 0.5532163203036308 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.4641434262948207
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:07:54,310] Trial 10 finished with value: 0.49282868525896417 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:08:35,530] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.8081282674845877, 'learning_rate': 0.03957576815132133, 'dropout_rate': 0.3592207054036807, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 9.74116027708086, 'min_weight_fraction_leaf': 0.365889927692422, 'max_features': 'log2', 'min_impurity_decrease': 1.459170836380829e-06, 'validation_fraction': 0.7986785049611014, 'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:09:19,376] Trial 12 finished with value: 0.5 and parameters: {'subsample': 0.3678235114093892, 'learning_rate': 0.04567946973839636, 'dropout_rate': 0.25727844951644346, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.3231056999503768, 'min_weight_fraction_leaf': 0.19696526950140963, 'max_features': 'auto', 'min_impurity_decrease': 1.6810148621356602e-06, 'validation_fraction': 0.8490366656238622, 'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 9 with value: 0.5532163203036308.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:09:24,030] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.7784830438231676, 'learning_rate': 0.02439641670004065, 'dropout_rate': 0.4821375662037144, 'n_estimators': 148, 'criterion': 'friedman_mse', 'ccp_alpha': 6.245821408640139, 'min_weight_fraction_leaf': 0.3469021849356369, 'max_features': 1, 'min_impurity_decrease': 0.002901900339595834, 'validation_fraction': 0.40492470595401014, 'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:10:05,635] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.5522283925781899, 'learning_rate': 0.010913227078192221, 'dropout_rate': 0.275468298707492, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.2209251544817152, 'max_features': 'log2', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.7267940764758692, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:10:53,885] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8321814107294574, 'learning_rate': 0.03462515781182537, 'dropout_rate': 0.10188162797857298, 'n_estimators': 375, 'criterion': 'friedman_mse', 'ccp_alpha': 5.585208670000242, 'min_weight_fraction_leaf': 0.3203472576334258, 'max_features': 0.1, 'min_impurity_decrease': 9.84228208509291e-05, 'validation_fraction': 0.9508448160253733, 'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:10:57,991] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.41637694759398924, 'learning_rate': 0.05102954371215744, 'dropout_rate': 0.4800989647660596, 'n_estimators': 119, 'criterion': 'squared_error', 'ccp_alpha': 9.356569787888832, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': None, 'min_impurity_decrease': 6.315552530348283e-07, 'validation_fraction': 0.6329472651499938, 'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 19}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:12:38,393] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.18427032297888507, 'learning_rate': 0.016160179473353013, 'dropout_rate': 0.2643467397617198, 'n_estimators': 500, 'criterion': 'friedman_mse', 'ccp_alpha': 1.767647956851031, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 'auto', 'min_impurity_decrease': 9.756988906280483e-06, 'validation_fraction': 0.460466512261803, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:12:50,693] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.29960178961969325, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.480521228562659, 'n_estimators': 234, 'criterion': 'friedman_mse', 'ccp_alpha': 6.571359927175668, 'min_weight_fraction_leaf': 0.3081685769690769, 'max_features': 'auto', 'min_impurity_decrease': 0.00017103826195115595, 'validation_fraction': 0.8334165513948124, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 7}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:13:00,329] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.6107103985877803, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.8022840901094805, 'n_estimators': 339, 'criterion': 'squared_error', 'ccp_alpha': 4.726491220462886, 'min_weight_fraction_leaf': 0.23723421649302917, 'max_features': None, 'min_impurity_decrease': 0.005573123702146452, 'validation_fraction': 0.733318779116827, 'min_samples_split': 15, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:13:37,830] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.7486596812728094, 'learning_rate': 0.030015766309112166, 'dropout_rate': 0.41862843505834413, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 8.442374914253744, 'min_weight_fraction_leaf': 0.43152288390795446, 'max_features': 0.1, 'min_impurity_decrease': 5.093079199752527e-07, 'validation_fraction': 0.485777565058473, 'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 17}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:13:51,915] Trial 21 finished with value: 0.5 and parameters: {'subsample': 0.6645352255107654, 'learning_rate': 0.09848488597888547, 'dropout_rate': 0.7687435120123771, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.841872183700346, 'min_weight_fraction_leaf': 0.12726799092659097, 'max_features': 'sqrt', 'min_impurity_decrease': 4.129428860721829e-05, 'validation_fraction': 0.26781949045355996, 'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 12}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:14:04,819] Trial 22 finished with value: 0.5 and parameters: {'subsample': 0.473874743610687, 'learning_rate': 0.08064716128589619, 'dropout_rate': 0.7441459115178709, 'n_estimators': 319, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7836160564934809, 'min_weight_fraction_leaf': 0.08573145040193865, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6571343171562185e-05, 'validation_fraction': 0.3666637457155964, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 9}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:14:09,921] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9031806207514874, 'learning_rate': 0.05231237416288583, 'dropout_rate': 0.9933061120594999, 'n_estimators': 376, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9734842724745505, 'min_weight_fraction_leaf': 0.18816784942881926, 'max_features': 'sqrt', 'min_impurity_decrease': 5.564325269330583e-05, 'validation_fraction': 0.22191224417069177, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 7}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:14:17,747] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.6032411000441751, 'learning_rate': 0.08510490014384028, 'dropout_rate': 0.8499447592488185, 'n_estimators': 264, 'criterion': 'friedman_mse', 'ccp_alpha': 2.564923335664723, 'min_weight_fraction_leaf': 0.2675376131769848, 'max_features': 'sqrt', 'min_impurity_decrease': 4.632626838690667e-06, 'validation_fraction': 0.5456395158226394, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:14:25,364] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7215349051479215, 'learning_rate': 0.04238950086330006, 'dropout_rate': 0.3050189841876249, 'n_estimators': 160, 'criterion': 'friedman_mse', 'ccp_alpha': 4.1944004294560635, 'min_weight_fraction_leaf': 0.31435920289715347, 'max_features': 'log2', 'min_impurity_decrease': 0.00032844478717469067, 'validation_fraction': 0.005916255331971709, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 10}. Best is trial 9 with value: 0.5532163203036308.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:14:57,473] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.8806073308147355, 'learning_rate': 0.022376976197093057, 'dropout_rate': 0.6881130985931054, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 2.7801390404743485, 'min_weight_fraction_leaf': 0.14826348238129222, 'max_features': 1, 'min_impurity_decrease': 3.2746646321179855e-06, 'validation_fraction': 0.654336976255422, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:16:57,478] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.6416570269538786, 'learning_rate': 0.08875752985571464, 'dropout_rate': 0.19627515205758927, 'n_estimators': 344, 'criterion': 'friedman_mse', 'ccp_alpha': 5.931957554140308, 'min_weight_fraction_leaf': 0.08440730068390215, 'max_features': 'sqrt', 'min_impurity_decrease': 4.19885324392308e-07, 'validation_fraction': 0.37029719014273693, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:17:40,540] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.497258076729488, 'learning_rate': 0.008892113552158437, 'dropout_rate': 0.5412836692874428, 'n_estimators': 228, 'criterion': 'squared_error', 'ccp_alpha': 7.112328377904401, 'min_weight_fraction_leaf': 0.22283394976693366, 'max_features': None, 'min_impurity_decrease': 0.0009606983262736196, 'validation_fraction': 0.7883279075003073, 'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 12}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:18:42,699] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6818794942229185, 'learning_rate': 0.05992326510937737, 'dropout_rate': 0.4279996334051157, 'n_estimators': 293, 'criterion': 'friedman_mse', 'ccp_alpha': 4.98367064023063, 'min_weight_fraction_leaf': 0.48609051334926223, 'max_features': 'auto', 'min_impurity_decrease': 2.7205182948043777e-05, 'validation_fraction': 0.8992753588751915, 'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 10}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:18:52,383] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.8339878628842677, 'learning_rate': 0.01736979095038719, 'dropout_rate': 0.9018920438096094, 'n_estimators': 205, 'criterion': 'friedman_mse', 'ccp_alpha': 8.526748409672111, 'min_weight_fraction_leaf': 0.061083375695457354, 'max_features': None, 'min_impurity_decrease': 4.064893428944893e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 4}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:19:13,244] Trial 31 finished with value: 0.5 and parameters: {'subsample': 0.7067650123833389, 'learning_rate': 0.010128712060556065, 'dropout_rate': 0.34778224400860064, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 5.487014966748448, 'min_weight_fraction_leaf': 0.39961580373240596, 'max_features': None, 'min_impurity_decrease': 1.0411120773977246e-05, 'validation_fraction': 0.308558812747987, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 14}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:19:23,868] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.6110503802842687, 'learning_rate': 0.027415486687298214, 'dropout_rate': 0.4231091261598614, 'n_estimators': 165, 'criterion': 'friedman_mse', 'ccp_alpha': 4.725664402361732, 'min_weight_fraction_leaf': 0.4578429432624628, 'max_features': None, 'min_impurity_decrease': 1.102268047930114e-07, 'validation_fraction': 0.6040860894665333, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:20:14,821] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.7527918357143221, 'learning_rate': 0.013800242549203569, 'dropout_rate': 0.21901675178661018, 'n_estimators': 343, 'criterion': 'friedman_mse', 'ccp_alpha': 4.336519464922468, 'min_weight_fraction_leaf': 0.49560720146678894, 'max_features': None, 'min_impurity_decrease': 0.00011658144802596447, 'validation_fraction': 0.5695864375011732, 'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 12}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:20:17,915] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.5550888124148649, 'learning_rate': 0.07031962025287278, 'dropout_rate': 0.609287527548691, 'n_estimators': 109, 'criterion': 'friedman_mse', 'ccp_alpha': 3.1886879010945073, 'min_weight_fraction_leaf': 0.35104146554842863, 'max_features': None, 'min_impurity_decrease': 1.4503905721935394e-05, 'validation_fraction': 0.1781977553519499, 'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:22:20,361] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.6647484092740189, 'learning_rate': 0.03716684708129065, 'dropout_rate': 0.32199768169248655, 'n_estimators': 267, 'criterion': 'friedman_mse', 'ccp_alpha': 6.677117818544033, 'min_weight_fraction_leaf': 0.0024719709736978485, 'max_features': None, 'min_impurity_decrease': 0.0003527658310127607, 'validation_fraction': 0.4303498724987228, 'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 8}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:28:25,105] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.5132724920534562, 'learning_rate': 0.05938980302581085, 'dropout_rate': 0.5454399629254872, 'n_estimators': 232, 'criterion': 'squared_error', 'ccp_alpha': 2.377008407008705, 'min_weight_fraction_leaf': 0.2560267496278468, 'max_features': 1, 'min_impurity_decrease': 1.611508696646605e-05, 'validation_fraction': 0.3206572028643662, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:28:58,902] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6133316469108037, 'learning_rate': 0.0192978405124231, 'dropout_rate': 0.3734539105394589, 'n_estimators': 209, 'criterion': 'squared_error', 'ccp_alpha': 7.974952733297302, 'min_weight_fraction_leaf': 0.2937726053633184, 'max_features': 'auto', 'min_impurity_decrease': 2.9025315549537875e-07, 'validation_fraction': 0.5215770496136994, 'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 13}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:29:24,228] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.9564449642405839, 'learning_rate': 0.0055035268399332106, 'dropout_rate': 0.15548835641172376, 'n_estimators': 278, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8766250077556945, 'min_weight_fraction_leaf': 0.37706312078571214, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0010896766592292972, 'validation_fraction': 0.6758418959443157, 'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 9 with value: 0.5532163203036308.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:29:48,679] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.43972351129566345, 'learning_rate': 0.06600221935919671, 'dropout_rate': 0.2199359809739201, 'n_estimators': 311, 'criterion': 'squared_error', 'ccp_alpha': 3.728373112411028, 'min_weight_fraction_leaf': 0.4354213118859305, 'max_features': 0.1, 'min_impurity_decrease': 6.240626814101929e-05, 'validation_fraction': 0.15340933394972178, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 9}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:29:56,175] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.7968754596525256, 'learning_rate': 0.033357301502402015, 'dropout_rate': 0.6498448126467091, 'n_estimators': 250, 'criterion': 'friedman_mse', 'ccp_alpha': 5.281445352241334, 'min_weight_fraction_leaf': 0.3381586418579516, 'max_features': 'auto', 'min_impurity_decrease': 6.661303017365454e-06, 'validation_fraction': 0.07579960633039973, 'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:29:56,442] Trial 41 finished with value: 0.5 and parameters: {'subsample': 0.7127655796244947, 'learning_rate': 0.07428645893623183, 'dropout_rate': 0.70485161120415, 'n_estimators': 1, 'criterion': 'friedman_mse', 'ccp_alpha': 9.861114809899185, 'min_weight_fraction_leaf': 0.12458170809215217, 'max_features': None, 'min_impurity_decrease': 1.662245720310093e-07, 'validation_fraction': 0.7267564157130575, 'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 18}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:30:26,761] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.7560260044979399, 'learning_rate': 0.025751385187231305, 'dropout_rate': 0.6346183377825835, 'n_estimators': 408, 'criterion': 'friedman_mse', 'ccp_alpha': 7.475073875167142, 'min_weight_fraction_leaf': 0.04609024675850246, 'max_features': None, 'min_impurity_decrease': 9.328966670608897e-07, 'validation_fraction': 0.6034991541241608, 'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 14}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:30:47,835] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5800218768698703, 'learning_rate': 0.060657130303905384, 'dropout_rate': 0.8315823321401684, 'n_estimators': 373, 'criterion': 'friedman_mse', 'ccp_alpha': 9.052626765771977, 'min_weight_fraction_leaf': 0.11245484624078364, 'max_features': 'log2', 'min_impurity_decrease': 2.7032867367744606e-06, 'validation_fraction': 0.7627780727404674, 'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 14}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:31:17,024] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.650007501014019, 'learning_rate': 0.042999799171261954, 'dropout_rate': 0.6859431566383477, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 9.255798461541156, 'min_weight_fraction_leaf': 0.19508406829791197, 'max_features': None, 'min_impurity_decrease': 1.803850310358625e-07, 'validation_fraction': 0.4932258209212708, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 16}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:31:34,104] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.8267526608162997, 'learning_rate': 0.013494375221622822, 'dropout_rate': 0.562451794592445, 'n_estimators': 329, 'criterion': 'friedman_mse', 'ccp_alpha': 7.951274135957477, 'min_weight_fraction_leaf': 0.15414208319180517, 'max_features': None, 'min_impurity_decrease': 0.02254931450703544, 'validation_fraction': 0.6904472538348748, 'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 11}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:32:02,347] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.6929864855836454, 'learning_rate': 0.007563282406611266, 'dropout_rate': 0.29094189233267964, 'n_estimators': 357, 'criterion': 'squared_error', 'ccp_alpha': 6.2062474416489986, 'min_weight_fraction_leaf': 0.2757251898825701, 'max_features': 'auto', 'min_impurity_decrease': 0.00020148550328401993, 'validation_fraction': 0.5782346210702172, 'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:32:25,030] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5253005441150441, 'learning_rate': 0.04837065116276148, 'dropout_rate': 0.40371810493552335, 'n_estimators': 298, 'criterion': 'friedman_mse', 'ccp_alpha': 0.424583130603446, 'min_weight_fraction_leaf': 0.24358906077310583, 'max_features': 1, 'min_impurity_decrease': 1.7170256007439695e-06, 'validation_fraction': 0.423183184019399, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 8}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:33:11,715] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.8553523642443996, 'learning_rate': 0.055123011100452285, 'dropout_rate': 0.11178105681173112, 'n_estimators': 398, 'criterion': 'friedman_mse', 'ccp_alpha': 8.808635181507519, 'min_weight_fraction_leaf': 0.2141846663477463, 'max_features': 0.1, 'min_impurity_decrease': 8.385166952734583e-07, 'validation_fraction': 0.8693234429106627, 'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 12}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:34:39,505] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.3427196246281643, 'learning_rate': 0.02181226739450172, 'dropout_rate': 0.25330085395937585, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 3.1260410279491686, 'min_weight_fraction_leaf': 0.09975982578242681, 'max_features': None, 'min_impurity_decrease': 3.2453997760645774e-07, 'validation_fraction': 0.64281654153714, 'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 15}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:34:46,990] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.12134026571324846, 'learning_rate': 0.030037341123185, 'dropout_rate': 0.476177268516495, 'n_estimators': 178, 'criterion': 'friedman_mse', 'ccp_alpha': 2.002448222737427, 'min_weight_fraction_leaf': 0.1675014656774081, 'max_features': 'sqrt', 'min_impurity_decrease': 2.614633035612604e-05, 'validation_fraction': 0.3148019982511154, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 10}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:34:48,812] Trial 51 finished with value: 0.5 and parameters: {'subsample': 0.22560952991832442, 'learning_rate': 0.07096865200025802, 'dropout_rate': 0.7403990506884194, 'n_estimators': 105, 'criterion': 'friedman_mse', 'ccp_alpha': 3.6955183727273386, 'min_weight_fraction_leaf': 0.033756448345697854, 'max_features': None, 'min_impurity_decrease': 0.00034438274690092334, 'validation_fraction': 0.8185501989107483, 'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 6}. Best is trial 9 with value: 0.5532163203036308.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:34:58,869] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.4078669152596949, 'learning_rate': 0.07972542806076426, 'dropout_rate': 0.5885469293985746, 'n_estimators': 258, 'criterion': 'friedman_mse', 'ccp_alpha': 4.196656708934098, 'min_weight_fraction_leaf': 0.06070449344498474, 'max_features': None, 'min_impurity_decrease': 0.0006522112972854332, 'validation_fraction': 0.6875552859786656, 'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:35:15,585] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.5780503682164675, 'learning_rate': 0.06351565920160718, 'dropout_rate': 0.5268425864933246, 'n_estimators': 284, 'criterion': 'friedman_mse', 'ccp_alpha': 5.912988737296398, 'min_weight_fraction_leaf': 0.2880138147880729, 'max_features': 'log2', 'min_impurity_decrease': 0.0023620162241031065, 'validation_fraction': 0.7386953311243849, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 4}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:35:25,286] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.771877515032402, 'learning_rate': 0.0879386461062289, 'dropout_rate': 0.6531928050964037, 'n_estimators': 243, 'criterion': 'friedman_mse', 'ccp_alpha': 6.749514129274708, 'min_weight_fraction_leaf': 0.010727427625077723, 'max_features': 'auto', 'min_impurity_decrease': 6.568909958494579e-05, 'validation_fraction': 0.5260231128653986, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 9}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:35:38,524] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.6352427224249186, 'learning_rate': 0.0018114229555726662, 'dropout_rate': 0.7780580098014175, 'n_estimators': 361, 'criterion': 'friedman_mse', 'ccp_alpha': 4.674374022230462, 'min_weight_fraction_leaf': 0.4028675241355946, 'max_features': None, 'min_impurity_decrease': 0.00015802436521782464, 'validation_fraction': 0.6116726877072444, 'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 6}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:35:44,245] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.7310159697721421, 'learning_rate': 0.09459281124929597, 'dropout_rate': 0.33513381234631495, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 9.504060286925714, 'min_weight_fraction_leaf': 0.07554400849922152, 'max_features': 'sqrt', 'min_impurity_decrease': 3.609461626813292e-05, 'validation_fraction': 0.45003037837116033, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:35:50,928] Trial 57 finished with value: 0.5 and parameters: {'subsample': 0.4496884297691718, 'learning_rate': 0.055717108591229025, 'dropout_rate': 0.7227843588112581, 'n_estimators': 184, 'criterion': 'friedman_mse', 'ccp_alpha': 3.477932962998816, 'min_weight_fraction_leaf': 0.3309371032482379, 'max_features': None, 'min_impurity_decrease': 6.805459531517676e-06, 'validation_fraction': 0.7746725177759497, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 20}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:36:03,917] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.5390990270834256, 'learning_rate': 0.08228345726531958, 'dropout_rate': 0.3867389328769052, 'n_estimators': 217, 'criterion': 'friedman_mse', 'ccp_alpha': 7.96887264775278, 'min_weight_fraction_leaf': 0.025824097286407145, 'max_features': 'auto', 'min_impurity_decrease': 2.1217250957605284e-07, 'validation_fraction': 0.7085899837169293, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:36:27,806] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.26995457899931047, 'learning_rate': 0.07839400629330891, 'dropout_rate': 0.44277207988197187, 'n_estimators': 329, 'criterion': 'friedman_mse', 'ccp_alpha': 5.190496612405482, 'min_weight_fraction_leaf': 0.18052310410291128, 'max_features': 'sqrt', 'min_impurity_decrease': 0.006646480686851006, 'validation_fraction': 0.36899118019789573, 'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:36:32,728] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.6821263907321534, 'learning_rate': 0.072006110155798, 'dropout_rate': 0.5000787935588615, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 2.878661154904403, 'min_weight_fraction_leaf': 0.13302043494927485, 'max_features': None, 'min_impurity_decrease': 1.6927874845319952e-05, 'validation_fraction': 0.649254298624334, 'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:36:35,816] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.47645185130049367, 'learning_rate': 0.06448712922727752, 'dropout_rate': 0.18066337573915892, 'n_estimators': 76, 'criterion': 'squared_error', 'ccp_alpha': 9.986171866114088, 'min_weight_fraction_leaf': 0.3016342642588235, 'max_features': 'auto', 'min_impurity_decrease': 2.135935478598492e-06, 'validation_fraction': 0.39240181900023485, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:36:37,840] Trial 62 finished with value: 0.5 and parameters: {'subsample': 0.5808153861385129, 'learning_rate': 0.0681246585307992, 'dropout_rate': 0.23730162924900122, 'n_estimators': 71, 'criterion': 'squared_error', 'ccp_alpha': 8.569241148604158, 'min_weight_fraction_leaf': 0.26373450314917496, 'max_features': 'auto', 'min_impurity_decrease': 7.545132996978128e-05, 'validation_fraction': 0.5445924537815071, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 17}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:36:58,484] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.6306507981955418, 'learning_rate': 0.05196613429356862, 'dropout_rate': 0.29459029024130556, 'n_estimators': 276, 'criterion': 'squared_error', 'ccp_alpha': 7.302937119968669, 'min_weight_fraction_leaf': 0.21346358926716819, 'max_features': 'auto', 'min_impurity_decrease': 8.99541018098363e-06, 'validation_fraction': 0.48617563689534593, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 6}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:37:54,233] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.6655843820171748, 'learning_rate': 0.0755078862846863, 'dropout_rate': 0.16477104886116545, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 1.4394908967284419, 'min_weight_fraction_leaf': 0.3561841078487707, 'max_features': 0.1, 'min_impurity_decrease': 0.00011982157410057435, 'validation_fraction': 0.26717204824424134, 'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 19}. Best is trial 9 with value: 0.5532163203036308.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:37:55,436] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.7929453548007699, 'learning_rate': 0.05703829829485283, 'dropout_rate': 0.26693346156697134, 'n_estimators': 40, 'criterion': 'friedman_mse', 'ccp_alpha': 9.622909679545497, 'min_weight_fraction_leaf': 0.3739817512639645, 'max_features': 1, 'min_impurity_decrease': 1.132537699639542e-06, 'validation_fraction': 0.5719114708143103, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:39:19,098] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.7297228220058729, 'learning_rate': 0.048039429864377176, 'dropout_rate': 0.13146807723463924, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 2.2139349489390074, 'min_weight_fraction_leaf': 0.22907689759626237, 'max_features': None, 'min_impurity_decrease': 3.649342411644349e-05, 'validation_fraction': 0.6184842144993817, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 12}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:39:37,079] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.5640799123153939, 'learning_rate': 0.013731811381943973, 'dropout_rate': 0.6010596795994926, 'n_estimators': 312, 'criterion': 'friedman_mse', 'ccp_alpha': 4.4267489755284135, 'min_weight_fraction_leaf': 0.24894174086156923, 'max_features': 'log2', 'min_impurity_decrease': 5.850812869882035e-07, 'validation_fraction': 0.20583470481171634, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:40:41,720] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.6103857042426706, 'learning_rate': 0.004499506882329311, 'dropout_rate': 0.20156861633079565, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 7.575686101065674, 'min_weight_fraction_leaf': 0.3201448672949048, 'max_features': 'auto', 'min_impurity_decrease': 2.0511672586731725e-05, 'validation_fraction': 0.9734477789916156, 'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 10}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:40:59,763] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.38208631321852893, 'learning_rate': 0.019445173055985306, 'dropout_rate': 0.3471760689409496, 'n_estimators': 221, 'criterion': 'squared_error', 'ccp_alpha': 8.23137310474947, 'min_weight_fraction_leaf': 0.46019349583797037, 'max_features': 'sqrt', 'min_impurity_decrease': 5.25007498558406e-06, 'validation_fraction': 0.6668478041329834, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 8}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.42015209125475284
Fold 5 C-index: 0.5321888412017167
[I 2024-04-16 21:41:19,849] Trial 70 finished with value: 0.48938994626072685 and parameters: {'subsample': 0.695791357845726, 'learning_rate': 0.0386121015837519, 'dropout_rate': 0.8772407730274028, 'n_estimators': 196, 'criterion': 'friedman_mse', 'ccp_alpha': 0.08521619959958793, 'min_weight_fraction_leaf': 0.2793514647088877, 'max_features': None, 'min_impurity_decrease': 1.0560662656413339e-07, 'validation_fraction': 0.4673552004275108, 'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:41:48,657] Trial 71 finished with value: 0.5 and parameters: {'subsample': 0.9662299811796573, 'learning_rate': 0.01164038123739791, 'dropout_rate': 0.321412539780468, 'n_estimators': 241, 'criterion': 'squared_error', 'ccp_alpha': 2.7363744708439626, 'min_weight_fraction_leaf': 0.3094930495366378, 'max_features': 1, 'min_impurity_decrease': 0.07623847919135997, 'validation_fraction': 0.05459866921819029, 'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:42:14,947] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.9332756029831538, 'learning_rate': 0.015938139376876125, 'dropout_rate': 0.36736806527349025, 'n_estimators': 293, 'criterion': 'squared_error', 'ccp_alpha': 4.082890018334233, 'min_weight_fraction_leaf': 0.43469490375145153, 'max_features': 1, 'min_impurity_decrease': 1.1995571160060368e-05, 'validation_fraction': 0.10933275804436388, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 13}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:42:23,483] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.9998538579949057, 'learning_rate': 0.023662144142811335, 'dropout_rate': 0.7858332386073074, 'n_estimators': 259, 'criterion': 'squared_error', 'ccp_alpha': 3.4094816073468452, 'min_weight_fraction_leaf': 0.259787767977606, 'max_features': 1, 'min_impurity_decrease': 0.03613678358083246, 'validation_fraction': 0.7570165302670715, 'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:42:41,699] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.49404609591635523, 'learning_rate': 0.027234278844566435, 'dropout_rate': 0.6745879515386936, 'n_estimators': 325, 'criterion': 'squared_error', 'ccp_alpha': 1.4270365682196633, 'min_weight_fraction_leaf': 0.4824501432585142, 'max_features': None, 'min_impurity_decrease': 0.004288650403469109, 'validation_fraction': 0.003459596709284918, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:42:55,475] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.8787380494208122, 'learning_rate': 0.032628921035686646, 'dropout_rate': 0.5764841163307408, 'n_estimators': 271, 'criterion': 'friedman_mse', 'ccp_alpha': 3.9336532270018973, 'min_weight_fraction_leaf': 0.2058851752087183, 'max_features': 1, 'min_impurity_decrease': 4.538725949258468e-05, 'validation_fraction': 0.5845629993146434, 'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:43:14,949] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.6564333051332562, 'learning_rate': 0.019080043212643245, 'dropout_rate': 0.44665306793328274, 'n_estimators': 299, 'criterion': 'squared_error', 'ccp_alpha': 1.0857337944683, 'min_weight_fraction_leaf': 0.23213073417093516, 'max_features': 'auto', 'min_impurity_decrease': 0.012307736133371867, 'validation_fraction': 0.5325168506541532, 'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 7}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:43:38,652] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.5420207671519734, 'learning_rate': 0.061959929671163, 'dropout_rate': 0.6262328871241918, 'n_estimators': 352, 'criterion': 'friedman_mse', 'ccp_alpha': 9.10894580882659, 'min_weight_fraction_leaf': 0.09906990149082096, 'max_features': None, 'min_impurity_decrease': 0.09820374198399477, 'validation_fraction': 0.3362692151795741, 'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 9}. Best is trial 9 with value: 0.5532163203036308.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:43:47,059] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.5878556647859374, 'learning_rate': 0.06711374023485273, 'dropout_rate': 0.2445997085847752, 'n_estimators': 163, 'criterion': 'squared_error', 'ccp_alpha': 4.92584565812761, 'min_weight_fraction_leaf': 0.33536928909095803, 'max_features': 'sqrt', 'min_impurity_decrease': 3.8390077329102796e-07, 'validation_fraction': 0.27076081694396725, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 13}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:43:47,535] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.772421040984131, 'learning_rate': 0.0739394606546838, 'dropout_rate': 0.30577466179677715, 'n_estimators': 20, 'criterion': 'friedman_mse', 'ccp_alpha': 6.9608869185530375, 'min_weight_fraction_leaf': 0.2890173575842872, 'max_features': 0.1, 'min_impurity_decrease': 4.271388332600321e-06, 'validation_fraction': 0.12354106940694709, 'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:43:53,343] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.6262588532566787, 'learning_rate': 0.007364213642980483, 'dropout_rate': 0.22782650220537706, 'n_estimators': 132, 'criterion': 'friedman_mse', 'ccp_alpha': 3.1362570843729256, 'min_weight_fraction_leaf': 0.05598078546941263, 'max_features': None, 'min_impurity_decrease': 0.0015997823675816406, 'validation_fraction': 0.7086216736572399, 'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:44:16,069] Trial 81 finished with value: 0.5 and parameters: {'subsample': 0.13004185664428597, 'learning_rate': 0.04319851444329214, 'dropout_rate': 0.2742668194686884, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 6.3975842513433205, 'min_weight_fraction_leaf': 0.019661744505459794, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00024181299362810094, 'validation_fraction': 0.030354933044682383, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 10}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:44:18,792] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.20732233430487482, 'learning_rate': 0.09448615861190351, 'dropout_rate': 0.9637262407510002, 'n_estimators': 229, 'criterion': 'squared_error', 'ccp_alpha': 5.493193545968569, 'min_weight_fraction_leaf': 0.08269791710039148, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000669121886047251, 'validation_fraction': 0.0879180882370175, 'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:44:23,011] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.326609309382988, 'learning_rate': 0.030635299392771213, 'dropout_rate': 0.9379794618218152, 'n_estimators': 255, 'criterion': 'squared_error', 'ccp_alpha': 5.858421509209595, 'min_weight_fraction_leaf': 0.2785010596713026, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0006395902705527272, 'validation_fraction': 0.20671628280437965, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:44:32,961] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.8200504843574723, 'learning_rate': 0.02225813211626105, 'dropout_rate': 0.821691123019113, 'n_estimators': 309, 'criterion': 'squared_error', 'ccp_alpha': 7.7811713777087075, 'min_weight_fraction_leaf': 0.03537409024063304, 'max_features': 'auto', 'min_impurity_decrease': 9.629285410278793e-05, 'validation_fraction': 0.14996645966549244, 'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:44:46,754] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.7344539898476983, 'learning_rate': 0.0363737079170678, 'dropout_rate': 0.5059962606176266, 'n_estimators': 207, 'criterion': 'friedman_mse', 'ccp_alpha': 8.853758560944817, 'min_weight_fraction_leaf': 0.00574456258879244, 'max_features': 'log2', 'min_impurity_decrease': 2.3193299506557292e-07, 'validation_fraction': 0.17295155991387712, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:44:58,485] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.17293960316308388, 'learning_rate': 0.015941982089878445, 'dropout_rate': 0.8625320880703877, 'n_estimators': 373, 'criterion': 'squared_error', 'ccp_alpha': 2.4891842623760496, 'min_weight_fraction_leaf': 0.17880882745231644, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00043212707845170355, 'validation_fraction': 0.04627871168518361, 'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:45:10,525] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.7075972726405854, 'learning_rate': 0.025495747044252892, 'dropout_rate': 0.9164080801290021, 'n_estimators': 337, 'criterion': 'friedman_mse', 'ccp_alpha': 8.20002370348434, 'min_weight_fraction_leaf': 0.04618376289979789, 'max_features': None, 'min_impurity_decrease': 7.976985736350699e-06, 'validation_fraction': 0.6226289516594348, 'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:45:13,075] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.660389174849776, 'learning_rate': 0.05789696984511753, 'dropout_rate': 0.9969370271173045, 'n_estimators': 241, 'criterion': 'squared_error', 'ccp_alpha': 7.084477957124831, 'min_weight_fraction_leaf': 0.1502372380149756, 'max_features': 1, 'min_impurity_decrease': 1.21810279769229e-05, 'validation_fraction': 0.8044607135364268, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 7}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:45:40,888] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.2836131146487435, 'learning_rate': 0.08499070433634016, 'dropout_rate': 0.20176133153261788, 'n_estimators': 291, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7258631676992413, 'min_weight_fraction_leaf': 0.39691440943727196, 'max_features': None, 'min_impurity_decrease': 2.5312430765889915e-05, 'validation_fraction': 0.5089000041945507, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 11}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:46:06,577] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.5127606348342963, 'learning_rate': 0.06868540970127159, 'dropout_rate': 0.38486198408276084, 'n_estimators': 316, 'criterion': 'friedman_mse', 'ccp_alpha': 4.468909640658013, 'min_weight_fraction_leaf': 0.4168799332898534, 'max_features': 'auto', 'min_impurity_decrease': 4.943166695208926e-05, 'validation_fraction': 0.5647231982723091, 'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 8}. Best is trial 9 with value: 0.5532163203036308.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:46:07,314] Trial 91 finished with value: 0.5 and parameters: {'subsample': 0.40079117047755053, 'learning_rate': 0.07761975543689428, 'dropout_rate': 0.6674453262944787, 'n_estimators': 40, 'criterion': 'squared_error', 'ccp_alpha': 3.5450960279763866, 'min_weight_fraction_leaf': 0.4500276802676531, 'max_features': 0.1, 'min_impurity_decrease': 0.033752326373165754, 'validation_fraction': 0.09381478020296691, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 10}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:46:10,723] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.6010310791835901, 'learning_rate': 0.08174080524828456, 'dropout_rate': 0.6173958578390156, 'n_estimators': 92, 'criterion': 'squared_error', 'ccp_alpha': 3.934246959257214, 'min_weight_fraction_leaf': 0.48058120129069476, 'max_features': 0.1, 'min_impurity_decrease': 0.009674057425500725, 'validation_fraction': 0.0662272783466388, 'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 9}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:46:11,705] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.2583949369171118, 'learning_rate': 0.08372015018698861, 'dropout_rate': 0.7087266143850187, 'n_estimators': 47, 'criterion': 'squared_error', 'ccp_alpha': 3.3032674710510435, 'min_weight_fraction_leaf': 0.49968903870360254, 'max_features': 0.1, 'min_impurity_decrease': 0.038054394076187645, 'validation_fraction': 0.12085044147330981, 'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 7}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:46:12,068] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.44087618613470847, 'learning_rate': 0.08900788202696326, 'dropout_rate': 0.5650043215993452, 'n_estimators': 16, 'criterion': 'squared_error', 'ccp_alpha': 1.8591480510149145, 'min_weight_fraction_leaf': 0.46540012003750114, 'max_features': 0.1, 'min_impurity_decrease': 0.05716954715745521, 'validation_fraction': 0.1454888110810409, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 11}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:47:05,372] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.4682083856787219, 'learning_rate': 0.010760752355551167, 'dropout_rate': 0.4078292725383645, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 2.9414907726063304, 'min_weight_fraction_leaf': 0.30182467770093624, 'max_features': None, 'min_impurity_decrease': 0.02679784311159001, 'validation_fraction': 0.23424746172333002, 'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:47:06,577] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.5638105776985176, 'learning_rate': 0.06472457155405788, 'dropout_rate': 0.7605049030015505, 'n_estimators': 71, 'criterion': 'friedman_mse', 'ccp_alpha': 2.1302802770582945, 'min_weight_fraction_leaf': 0.1336974981390665, 'max_features': 'sqrt', 'min_impurity_decrease': 1.4894860335591788e-07, 'validation_fraction': 0.6364631399735258, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:47:18,205] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.7492751287033583, 'learning_rate': 0.07233116225314724, 'dropout_rate': 0.6405087149655578, 'n_estimators': 268, 'criterion': 'squared_error', 'ccp_alpha': 3.641508108989198, 'min_weight_fraction_leaf': 0.4466142202394081, 'max_features': 'auto', 'min_impurity_decrease': 0.014963021229604866, 'validation_fraction': 0.027269214899444227, 'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:47:24,620] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.6812629725805999, 'learning_rate': 0.05397729950717226, 'dropout_rate': 0.5192108138448334, 'n_estimators': 183, 'criterion': 'friedman_mse', 'ccp_alpha': 8.709246893332534, 'min_weight_fraction_leaf': 0.35887955241768116, 'max_features': None, 'min_impurity_decrease': 0.0019689892423886755, 'validation_fraction': 0.5998005310811334, 'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 18}. Best is trial 9 with value: 0.5532163203036308.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-16 21:47:25,651] A new study created in memory with name: no-name-8b2f7d6d-5349-4b38-9cf3-cfb8d7f7c685

Fold 5 C-index: 0.5
[I 2024-04-16 21:47:25,627] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.35876827991429944, 'learning_rate': 0.020266385211182018, 'dropout_rate': 0.4577965489047534, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 2.6611204383385654, 'min_weight_fraction_leaf': 0.47195597459523597, 'max_features': 'sqrt', 'min_impurity_decrease': 3.141576706737268e-06, 'validation_fraction': 0.6630791267738267, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 9 with value: 0.5532163203036308.


* Best trial for C-index:
 FrozenTrial(number=9, state=TrialState.COMPLETE, values=[0.5532163203036308], datetime_start=datetime.datetime(2024, 4, 16, 21, 5, 49, 771989), datetime_complete=datetime.datetime(2024, 4, 16, 21, 6, 41, 536729), params={'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=9, value=None)


* Best Score for C-index:
 0.5532163203036308

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:47:44,266] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:47:55,268] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:48:06,209] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 21:48:23,041] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:48:31,022] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:48:32,686] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:48:49,110] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:48:53,541] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:48:54,013] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24739825876800792
Fold 2 IBS: 0.2319918234439918
Fold 3 IBS: 0.2289709628471152
Fold 4 IBS: 0.24221109186992024
Fold 5 IBS: 0.2294351347909475
[I 2024-04-16 21:50:16,309] Trial 9 finished with value: 0.23600145434399655 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:50:23,331] Trial 10 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.09930040119161188, 'dropout_rate': 0.9840465403588384, 'n_estimators': 464, 'criterion': 'friedman_mse', 'ccp_alpha': 6.889579121583325, 'min_weight_fraction_leaf': 0.1525596002146278, 'max_features': 'log2', 'min_impurity_decrease': 1.3494217040450704e-07, 'validation_fraction': 0.9983927524866523, 'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 17}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:51:05,238] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7990125137670133, 'learning_rate': 0.0439266186961535, 'dropout_rate': 0.11379276107227315, 'n_estimators': 366, 'criterion': 'friedman_mse', 'ccp_alpha': 9.952245263378543, 'min_weight_fraction_leaf': 0.38066914888027337, 'max_features': None, 'min_impurity_decrease': 1.4409213453974828e-06, 'validation_fraction': 0.8568777401008152, 'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:51:09,001] Trial 12 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8094511604072581, 'learning_rate': 0.05049118982367515, 'dropout_rate': 0.506681260540375, 'n_estimators': 140, 'criterion': 'friedman_mse', 'ccp_alpha': 9.371797696328212, 'min_weight_fraction_leaf': 0.16620671571282566, 'max_features': None, 'min_impurity_decrease': 1.7338556765963974e-06, 'validation_fraction': 0.7514714608290408, 'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 15}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:51:22,469] Trial 13 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7784830438231676, 'learning_rate': 0.03526446860297269, 'dropout_rate': 0.7527560343300005, 'n_estimators': 356, 'criterion': 'friedman_mse', 'ccp_alpha': 6.828264856961832, 'min_weight_fraction_leaf': 0.36442813361978627, 'max_features': None, 'min_impurity_decrease': 0.003174450361867868, 'validation_fraction': 0.4203977994955218, 'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 14, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:52:07,308] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3692598016141903, 'learning_rate': 0.05592898600934236, 'dropout_rate': 0.47167488200819974, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 8.59255877712454, 'min_weight_fraction_leaf': 0.197983218105045, 'max_features': 1, 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8695647082422235, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 5}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:52:10,178] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7326882263840526, 'learning_rate': 0.003935232787454848, 'dropout_rate': 0.7423954290041936, 'n_estimators': 141, 'criterion': 'friedman_mse', 'ccp_alpha': 6.113776090136422, 'min_weight_fraction_leaf': 0.0844181231732852, 'max_features': 'log2', 'min_impurity_decrease': 0.0001102320267737913, 'validation_fraction': 0.4733182802870096, 'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 13}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:52:25,373] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.45373090827392126, 'learning_rate': 0.037903138592295, 'dropout_rate': 0.6545308299808688, 'n_estimators': 333, 'criterion': 'friedman_mse', 'ccp_alpha': 8.2375746768047, 'min_weight_fraction_leaf': 0.35789839530318057, 'max_features': 0.1, 'min_impurity_decrease': 6.417264677752995e-07, 'validation_fraction': 0.5991745369732845, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 19}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 21:53:12,389] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8783131293076132, 'learning_rate': 0.05198005045180178, 'dropout_rate': 0.40513288908300327, 'n_estimators': 415, 'criterion': 'friedman_mse', 'ccp_alpha': 5.756491705316448, 'min_weight_fraction_leaf': 0.21968883820862695, 'max_features': None, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.7779494001823108, 'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:53:29,388] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.23557094034920928, 'learning_rate': 0.02692988041372099, 'dropout_rate': 0.25874474820742654, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 9.90931499921205, 'min_weight_fraction_leaf': 0.40791232836567476, 'max_features': None, 'min_impurity_decrease': 1.0008105265999655e-05, 'validation_fraction': 0.3525690267723217, 'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:53:32,226] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6889849263379537, 'learning_rate': 0.06157107261953758, 'dropout_rate': 0.839161936896032, 'n_estimators': 153, 'criterion': 'friedman_mse', 'ccp_alpha': 7.834745594217627, 'min_weight_fraction_leaf': 0.0862993019327169, 'max_features': None, 'min_impurity_decrease': 0.00012660448238274833, 'validation_fraction': 0.9918390024550794, 'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 18}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:54:01,864] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8798224730566231, 'learning_rate': 0.0848869134611167, 'dropout_rate': 0.52293850521399, 'n_estimators': 405, 'criterion': 'friedman_mse', 'ccp_alpha': 9.134114023551788, 'min_weight_fraction_leaf': 0.31895540883135826, 'max_features': 0.1, 'min_impurity_decrease': 5.008576286469488e-07, 'validation_fraction': 0.8373825922457974, 'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:54:12,399] Trial 21 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6359649504716143, 'learning_rate': 0.09662016874078937, 'dropout_rate': 0.7155732604559139, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 4.846392448988391, 'min_weight_fraction_leaf': 0.12726799092659097, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6846429975116493e-05, 'validation_fraction': 0.2474293202354665, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 12}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113

Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:54:20,572] Trial 22 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7213823590001637, 'learning_rate': 0.08376363128949735, 'dropout_rate': 0.8397794714633473, 'n_estimators': 313, 'criterion': 'friedman_mse', 'ccp_alpha': 1.73988804652919, 'min_weight_fraction_leaf': 0.0794155797294488, 'max_features': 'sqrt', 'min_impurity_decrease': 2.8943984691234026e-05, 'validation_fraction': 0.5059749590893529, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:54:33,391] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5525891887110783, 'learning_rate': 0.0441502775871349, 'dropout_rate': 0.6636895171886583, 'n_estimators': 257, 'criterion': 'friedman_mse', 'ccp_alpha': 3.881974260818861, 'min_weight_fraction_leaf': 0.19484972477567308, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0003076591327977347, 'validation_fraction': 0.22191224417069177, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:54:45,848] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6032411000441751, 'learning_rate': 0.08740584007633913, 'dropout_rate': 0.8270728452204542, 'n_estimators': 379, 'criterion': 'friedman_mse', 'ccp_alpha': 1.6603669815729107, 'min_weight_fraction_leaf': 0.12275859911568864, 'max_features': 'sqrt', 'min_impurity_decrease': 4.867591360503752e-06, 'validation_fraction': 0.39781859150531784, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 10}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:54:59,129] Trial 25 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7498931982127188, 'learning_rate': 0.07347104634444335, 'dropout_rate': 0.583189584152989, 'n_estimators': 285, 'criterion': 'friedman_mse', 'ccp_alpha': 5.8090355618495, 'min_weight_fraction_leaf': 0.23834756325638892, 'max_features': 'auto', 'min_impurity_decrease': 4.09925131309572e-05, 'validation_fraction': 0.005916255331971709, 'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:55:22,535] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4894288290548137, 'learning_rate': 0.06115096560586815, 'dropout_rate': 0.46889527228236716, 'n_estimators': 338, 'criterion': 'squared_error', 'ccp_alpha': 4.233740780727753, 'min_weight_fraction_leaf': 0.04772954749092495, 'max_features': 1, 'min_impurity_decrease': 3.4180638864928055e-06, 'validation_fraction': 0.6596122452584993, 'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:55:48,114] Trial 27 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.835623033509183, 'learning_rate': 0.0441170168532854, 'dropout_rate': 0.6760259030681605, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 7.2552747783571485, 'min_weight_fraction_leaf': 0.3266686718616028, 'max_features': 'log2', 'min_impurity_decrease': 0.001518193248466115, 'validation_fraction': 0.5256950774430104, 'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 20, 'max_depth': 12}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:56:03,085] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9817098677422906, 'learning_rate': 0.09126814351119288, 'dropout_rate': 0.11010235822181647, 'n_estimators': 216, 'criterion': 'friedman_mse', 'ccp_alpha': 2.7309255933459915, 'min_weight_fraction_leaf': 0.4450413047040915, 'max_features': 'sqrt', 'min_impurity_decrease': 4.1920185598971485e-07, 'validation_fraction': 0.7194539738747867, 'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:56:10,140] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6818794942229185, 'learning_rate': 0.018780840739766137, 'dropout_rate': 0.3979530324758697, 'n_estimators': 168, 'criterion': 'friedman_mse', 'ccp_alpha': 5.182042058932291, 'min_weight_fraction_leaf': 0.12196208279779484, 'max_features': None, 'min_impurity_decrease': 0.0003420472638265351, 'validation_fraction': 0.278058629014148, 'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 10}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:56:18,342] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6518366462886871, 'learning_rate': 0.07958823064123646, 'dropout_rate': 0.7861329826644626, 'n_estimators': 285, 'criterion': 'friedman_mse', 'ccp_alpha': 8.961030937537409, 'min_weight_fraction_leaf': 0.17142730171812812, 'max_features': None, 'min_impurity_decrease': 5.567360459262378e-05, 'validation_fraction': 0.6041079999402372, 'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:56:28,740] Trial 31 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38973199281967674, 'learning_rate': 0.012316052733254115, 'dropout_rate': 0.31463284390755775, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 4.398435812939903, 'min_weight_fraction_leaf': 0.48420640073227955, 'max_features': None, 'min_impurity_decrease': 1.0411120773977246e-05, 'validation_fraction': 0.308558812747987, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:56:36,625] Trial 32 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7007814084705936, 'learning_rate': 0.002615159418529127, 'dropout_rate': 0.6012511414599662, 'n_estimators': 207, 'criterion': 'friedman_mse', 'ccp_alpha': 3.180606095131633, 'min_weight_fraction_leaf': 0.42070012591802414, 'max_features': None, 'min_impurity_decrease': 1.850573708866098e-05, 'validation_fraction': 0.20214926538978073, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 12}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:56:53,503] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5649814924738961, 'learning_rate': 0.06614579056733322, 'dropout_rate': 0.21901675178661018, 'n_estimators': 238, 'criterion': 'friedman_mse', 'ccp_alpha': 6.303916214803626, 'min_weight_fraction_leaf': 0.49560720146678894, 'max_features': None, 'min_impurity_decrease': 5.86261582503216e-06, 'validation_fraction': 0.39397221422045464, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:56:56,750] Trial 34 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.762839428730288, 'learning_rate': 0.024171603029429424, 'dropout_rate': 0.3497916614952459, 'n_estimators': 109, 'criterion': 'squared_error', 'ccp_alpha': 5.219481136026895, 'min_weight_fraction_leaf': 0.29798954549689893, 'max_features': 'auto', 'min_impurity_decrease': 0.0001534107552204199, 'validation_fraction': 0.46670549693729513, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 21:56:58,248] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7569349126164451, 'learning_rate': 0.02298106265460148, 'dropout_rate': 0.44712044708614834, 'n_estimators': 69, 'criterion': 'squared_error', 'ccp_alpha': 5.319169908516011, 'min_weight_fraction_leaf': 0.3004242641290359, 'max_features': 'auto', 'min_impurity_decrease': 0.00015450906349067145, 'validation_fraction': 0.563386256707372, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:57:01,275] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8502508803841721, 'learning_rate': 0.03373150802422523, 'dropout_rate': 0.3412759407119442, 'n_estimators': 100, 'criterion': 'squared_error', 'ccp_alpha': 7.700093473274961, 'min_weight_fraction_leaf': 0.2625845403620596, 'max_features': 1, 'min_impurity_decrease': 0.0010069140673704322, 'validation_fraction': 0.4348133972223629, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:57:29,071] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9159417107084322, 'learning_rate': 0.013097678689382965, 'dropout_rate': 0.1828260082377628, 'n_estimators': 316, 'criterion': 'squared_error', 'ccp_alpha': 1.8057222980182885, 'min_weight_fraction_leaf': 0.24207650040670453, 'max_features': 'auto', 'min_impurity_decrease': 0.01153566532340136, 'validation_fraction': 0.6809905121266859, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 16}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:57:29,450] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6080985116044525, 'learning_rate': 0.0279506853314998, 'dropout_rate': 0.5648028308462839, 'n_estimators': 22, 'criterion': 'squared_error', 'ccp_alpha': 0.7333490231885107, 'min_weight_fraction_leaf': 0.00299611741143746, 'max_features': 'auto', 'min_impurity_decrease': 0.0004987292864822584, 'validation_fraction': 0.46716709462054906, 'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:57:53,512] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6597097236895602, 'learning_rate': 0.04077526665546945, 'dropout_rate': 0.1605781606783095, 'n_estimators': 276, 'criterion': 'squared_error', 'ccp_alpha': 4.34618503595772, 'min_weight_fraction_leaf': 0.3277651563969065, 'max_features': 'auto', 'min_impurity_decrease': 6.240626814101929e-05, 'validation_fraction': 0.3601568393703429, 'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:58:34,005] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7882628884530587, 'learning_rate': 0.018807981069822302, 'dropout_rate': 0.2644506942936918, 'n_estimators': 384, 'criterion': 'squared_error', 'ccp_alpha': 8.308430494250064, 'min_weight_fraction_leaf': 0.05137790008396559, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005690645774213972, 'validation_fraction': 0.5744490768246202, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 21:58:37,819] Trial 41 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5896811856054586, 'learning_rate': 0.006897032020611486, 'dropout_rate': 0.2925135696090373, 'n_estimators': 114, 'criterion': 'squared_error', 'ccp_alpha': 3.5715876408529175, 'min_weight_fraction_leaf': 0.28236690053164004, 'max_features': None, 'min_impurity_decrease': 0.00020453445075706457, 'validation_fraction': 0.33640812125405006, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:58:53,709] Trial 42 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10059484274276498, 'learning_rate': 0.009787686623297084, 'dropout_rate': 0.38883322011103294, 'n_estimators': 254, 'criterion': 'friedman_mse', 'ccp_alpha': 6.69531760522727, 'min_weight_fraction_leaf': 0.40800507129631197, 'max_features': 0.1, 'min_impurity_decrease': 1.562556906737373e-05, 'validation_fraction': 0.12712446134813293, 'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 8}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:59:03,110] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7169564278098908, 'learning_rate': 0.017408560747038428, 'dropout_rate': 0.35235020852257515, 'n_estimators': 182, 'criterion': 'squared_error', 'ccp_alpha': 4.77446442378793, 'min_weight_fraction_leaf': 0.3760214761601493, 'max_features': None, 'min_impurity_decrease': 1.0300171701986138e-07, 'validation_fraction': 0.7965826261709861, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 12}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:59:10,306] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5058009564188232, 'learning_rate': 0.03151218545170842, 'dropout_rate': 0.9215143335289598, 'n_estimators': 351, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9084009045981505, 'min_weight_fraction_leaf': 0.45683459439098056, 'max_features': 'log2', 'min_impurity_decrease': 2.554944700985409e-06, 'validation_fraction': 0.619970344333758, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:59:11,870] Trial 45 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6347814711411004, 'learning_rate': 0.024918730390022577, 'dropout_rate': 0.4346567206287487, 'n_estimators': 71, 'criterion': 'friedman_mse', 'ccp_alpha': 9.50847856451098, 'min_weight_fraction_leaf': 0.204461577134346, 'max_features': 'auto', 'min_impurity_decrease': 7.287535049264176e-05, 'validation_fraction': 0.296384154065476, 'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:59:14,858] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8011995442645217, 'learning_rate': 0.05268077829739719, 'dropout_rate': 0.5278765115889106, 'n_estimators': 106, 'criterion': 'friedman_mse', 'ccp_alpha': 5.5296900537491025, 'min_weight_fraction_leaf': 0.34243677413780516, 'max_features': None, 'min_impurity_decrease': 0.07686668865341359, 'validation_fraction': 0.17156981768811883, 'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 15}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:59:23,747] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7582468632632998, 'learning_rate': 0.07251164036892022, 'dropout_rate': 0.6251306290047342, 'n_estimators': 231, 'criterion': 'squared_error', 'ccp_alpha': 3.7919297533068916, 'min_weight_fraction_leaf': 0.1470590557444548, 'max_features': None, 'min_impurity_decrease': 2.601736822875968e-07, 'validation_fraction': 0.7147730789425082, 'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:59:24,009] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6686695983564828, 'learning_rate': 0.048486004108091035, 'dropout_rate': 0.22019834995107618, 'n_estimators': 8, 'criterion': 'friedman_mse', 'ccp_alpha': 7.110361429283924, 'min_weight_fraction_leaf': 0.2963365395784951, 'max_features': 1, 'min_impurity_decrease': 7.1550902019076964e-06, 'validation_fraction': 0.9209340174930422, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:59:34,759] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5122119836500785, 'learning_rate': 0.03775896985056163, 'dropout_rate': 0.7257175554103826, 'n_estimators': 298, 'criterion': 'friedman_mse', 'ccp_alpha': 2.441757016417564, 'min_weight_fraction_leaf': 0.09975982578242681, 'max_features': 0.1, 'min_impurity_decrease': 1.3263870509158408e-06, 'validation_fraction': 0.4797627165442462, 'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:00:02,502] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.05797874766608852, 'dropout_rate': 0.3131975552609067, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 7.739901702201918, 'min_weight_fraction_leaf': 0.43268316543422797, 'max_features': 'sqrt', 'min_impurity_decrease': 2.8892327118549273e-05, 'validation_fraction': 0.534354618020056, 'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 17}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:00:09,856] Trial 51 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.22560952991832442, 'learning_rate': 0.07096865200025802, 'dropout_rate': 0.7900436478485762, 'n_estimators': 267, 'criterion': 'friedman_mse', 'ccp_alpha': 6.370299107375747, 'min_weight_fraction_leaf': 0.033756448345697854, 'max_features': None, 'min_impurity_decrease': 0.002036125913328181, 'validation_fraction': 0.6696460830471146, 'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:00:14,323] Trial 52 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.31735822960188664, 'learning_rate': 0.06660337018121176, 'dropout_rate': 0.6858789237879177, 'n_estimators': 178, 'criterion': 'friedman_mse', 'ccp_alpha': 3.2743206766670854, 'min_weight_fraction_leaf': 0.06070449344498474, 'max_features': None, 'min_impurity_decrease': 0.00011560049595977731, 'validation_fraction': 0.7395037817101467, 'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 6}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:00:18,203] Trial 53 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4383432266229327, 'learning_rate': 0.07759786505911864, 'dropout_rate': 0.5573429528648267, 'n_estimators': 145, 'criterion': 'friedman_mse', 'ccp_alpha': 4.696919558845196, 'min_weight_fraction_leaf': 0.3940618917042797, 'max_features': None, 'min_impurity_decrease': 0.0002071032125772561, 'validation_fraction': 0.7753590595628017, 'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 8}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:00:26,124] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7122306134516864, 'learning_rate': 0.06259452993554729, 'dropout_rate': 0.6369371661585259, 'n_estimators': 229, 'criterion': 'friedman_mse', 'ccp_alpha': 8.614462489844437, 'min_weight_fraction_leaf': 0.010727427625077723, 'max_features': None, 'min_impurity_decrease': 1.5148638375023177e-05, 'validation_fraction': 0.4472855024052223, 'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 3}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:00:30,226] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6348775472738502, 'learning_rate': 0.056228391316513804, 'dropout_rate': 0.8859792395781099, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 4.112165064685058, 'min_weight_fraction_leaf': 0.10354114773642131, 'max_features': 'log2', 'min_impurity_decrease': 0.0007308982585580714, 'validation_fraction': 0.8223612867147001, 'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 10}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:00:52,448] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.2887765610954624, 'learning_rate': 0.09459281124929597, 'dropout_rate': 0.4973870333170236, 'n_estimators': 343, 'criterion': 'friedman_mse', 'ccp_alpha': 2.3090586149455574, 'min_weight_fraction_leaf': 0.16870893777683815, 'max_features': None, 'min_impurity_decrease': 9.555769670116001e-07, 'validation_fraction': 0.8832333189890804, 'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 12}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 22:01:04,307] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7386655194472563, 'learning_rate': 0.08121117574322781, 'dropout_rate': 0.7097006096530404, 'n_estimators': 297, 'criterion': 'friedman_mse', 'ccp_alpha': 5.957852004910091, 'min_weight_fraction_leaf': 0.22037101100241793, 'max_features': 'sqrt', 'min_impurity_decrease': 4.237895965249124e-05, 'validation_fraction': 0.08070850858210837, 'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:01:05,092] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5421361155985364, 'learning_rate': 0.01577504990627386, 'dropout_rate': 0.7808575683821485, 'n_estimators': 50, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0184193129742996, 'min_weight_fraction_leaf': 0.1448897720159938, 'max_features': 'auto', 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.6960105953283704, 'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 13}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 22:01:09,903] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9173150081420889, 'learning_rate': 0.08889578318918753, 'dropout_rate': 0.9990195141033984, 'n_estimators': 370, 'criterion': 'squared_error', 'ccp_alpha': 9.84909386240886, 'min_weight_fraction_leaf': 0.35649585411577134, 'max_features': None, 'min_impurity_decrease': 8.993948238274996e-05, 'validation_fraction': 0.6390229412303301, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:01:46,194] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7679906806819273, 'learning_rate': 0.04870683186528475, 'dropout_rate': 0.3725132984258097, 'n_estimators': 417, 'criterion': 'friedman_mse', 'ccp_alpha': 3.599289535080828, 'min_weight_fraction_leaf': 0.02984371041709362, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0003093291856244062, 'validation_fraction': 0.24274367156851218, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 8}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:01:51,012] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4548125492913564, 'learning_rate': 0.06448712922727752, 'dropout_rate': 0.23334660874567667, 'n_estimators': 133, 'criterion': 'squared_error', 'ccp_alpha': 8.964334512789016, 'min_weight_fraction_leaf': 0.2622650100185694, 'max_features': 'auto', 'min_impurity_decrease': 3.2955653349682502e-06, 'validation_fraction': 0.5404629517713617, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:01:53,335] Trial 62 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.5808153861385129, 'learning_rate': 0.06950913691175828, 'dropout_rate': 0.1757512405292175, 'n_estimators': 88, 'criterion': 'squared_error', 'ccp_alpha': 9.599946213836796, 'min_weight_fraction_leaf': 0.30242994742465446, 'max_features': 'auto', 'min_impurity_decrease': 1.1467299409915213e-05, 'validation_fraction': 0.49756991614341306, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 17}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:01:55,347] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5735960583854421, 'learning_rate': 0.06921871690519206, 'dropout_rate': 0.14792092532246684, 'n_estimators': 79, 'criterion': 'squared_error', 'ccp_alpha': 9.630425604848389, 'min_weight_fraction_leaf': 0.2975953374661007, 'max_features': 'auto', 'min_impurity_decrease': 2.1344882320172173e-05, 'validation_fraction': 0.3929941445683471, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 17}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:01:58,764] Trial 64 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6124644383021629, 'learning_rate': 0.0741886472045744, 'dropout_rate': 0.43760455187884917, 'n_estimators': 125, 'criterion': 'squared_error', 'ccp_alpha': 9.37802815720201, 'min_weight_fraction_leaf': 0.06830929280294362, 'max_features': 'auto', 'min_impurity_decrease': 9.631655021493124e-06, 'validation_fraction': 0.5119238499928501, 'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 15}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:02:05,803] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6866865494307903, 'learning_rate': 0.060595218129929865, 'dropout_rate': 0.2524482831244577, 'n_estimators': 161, 'criterion': 'squared_error', 'ccp_alpha': 8.058353014036605, 'min_weight_fraction_leaf': 0.3425352493768995, 'max_features': None, 'min_impurity_decrease': 2.3880040801001446e-07, 'validation_fraction': 0.5865579328652687, 'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 13}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 22:02:13,963] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5434532565542548, 'learning_rate': 0.09984676062907398, 'dropout_rate': 0.3240306189418186, 'n_estimators': 190, 'criterion': 'friedman_mse', 'ccp_alpha': 8.684978804280684, 'min_weight_fraction_leaf': 0.31175345150966083, 'max_features': 1, 'min_impurity_decrease': 4.0874786456452054e-05, 'validation_fraction': 0.3299439408250933, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 12}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113

Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:02:15,850] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6828521170655483, 'learning_rate': 0.022258646319799062, 'dropout_rate': 0.6010596795994926, 'n_estimators': 87, 'criterion': 'squared_error', 'ccp_alpha': 5.4909073156880295, 'min_weight_fraction_leaf': 0.1860826779096332, 'max_features': 'auto', 'min_impurity_decrease': 0.00019344127251504632, 'validation_fraction': 0.3679720810813184, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 4}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:02:28,583] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.640231117985754, 'learning_rate': 0.0690549249219706, 'dropout_rate': 0.7519380649315037, 'n_estimators': 327, 'criterion': 'friedman_mse', 'ccp_alpha': 9.12009910003986, 'min_weight_fraction_leaf': 0.2627526200978835, 'max_features': 0.1, 'min_impurity_decrease': 4.3218014913505305e-06, 'validation_fraction': 0.6464011636311578, 'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 18}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:02:29,920] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.07648476772005827, 'dropout_rate': 0.416809849228879, 'n_estimators': 43, 'criterion': 'friedman_mse', 'ccp_alpha': 2.148469142831279, 'min_weight_fraction_leaf': 0.23142866921839025, 'max_features': None, 'min_impurity_decrease': 2.352225655943636e-06, 'validation_fraction': 0.2673878320927428, 'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:02:49,088] Trial 70 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7200354041945723, 'learning_rate': 0.007328592908475291, 'dropout_rate': 0.2896039298188004, 'n_estimators': 270, 'criterion': 'squared_error', 'ccp_alpha': 0.8883541113847828, 'min_weight_fraction_leaf': 0.2793514647088877, 'max_features': 'log2', 'min_impurity_decrease': 7.696246558518335e-06, 'validation_fraction': 0.4838339609712339, 'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:02:50,388] Trial 71 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5804554450613806, 'learning_rate': 0.052936365364029264, 'dropout_rate': 0.1893187908540745, 'n_estimators': 57, 'criterion': 'squared_error', 'ccp_alpha': 8.392711834226818, 'min_weight_fraction_leaf': 0.3094930495366378, 'max_features': 'auto', 'min_impurity_decrease': 1.4216068822157589e-05, 'validation_fraction': 0.5585753704784745, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 19}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:02:53,335] Trial 72 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6150221216409391, 'learning_rate': 0.08375954393658622, 'dropout_rate': 0.1331042622870674, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 8.791515310254463, 'min_weight_fraction_leaf': 0.256549065048548, 'max_features': 'auto', 'min_impurity_decrease': 4.1215005351507693e-05, 'validation_fraction': 0.6095946706874, 'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:02:54,063] Trial 73 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.5357952273905564, 'learning_rate': 0.028520993648918358, 'dropout_rate': 0.19229546306662304, 'n_estimators': 33, 'criterion': 'squared_error', 'ccp_alpha': 7.493076578758362, 'min_weight_fraction_leaf': 0.33417065523588363, 'max_features': 'auto', 'min_impurity_decrease': 8.689548592877679e-05, 'validation_fraction': 0.41270773635713787, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 1}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:02:54,337] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3405532867912948, 'learning_rate': 0.027234278844566435, 'dropout_rate': 0.20603588866492492, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 3.0127172496611094, 'min_weight_fraction_leaf': 0.33695642883115534, 'max_features': 'auto', 'min_impurity_decrease': 9.456509351181723e-05, 'validation_fraction': 0.41533615265245255, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 1}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:02:54,785] Trial 75 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.467151621189721, 'learning_rate': 0.03062276757680384, 'dropout_rate': 0.10669711837748914, 'n_estimators': 22, 'criterion': 'squared_error', 'ccp_alpha': 4.524001441588014, 'min_weight_fraction_leaf': 0.36663568810686725, 'max_features': 'auto', 'min_impurity_decrease': 5.9734079360074814e-05, 'validation_fraction': 0.44287673257385307, 'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 6}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:03:10,368] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.731945803245246, 'learning_rate': 0.03682378614660771, 'dropout_rate': 0.48122305708106483, 'n_estimators': 285, 'criterion': 'friedman_mse', 'ccp_alpha': 6.862927088794954, 'min_weight_fraction_leaf': 0.2879278145391756, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0004591155005280019, 'validation_fraction': 0.49721264071035765, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:03:31,434] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6642130397871726, 'learning_rate': 0.04128077713454106, 'dropout_rate': 0.16568977822532893, 'n_estimators': 247, 'criterion': 'squared_error', 'ccp_alpha': 4.08425869069922, 'min_weight_fraction_leaf': 0.3864200962523344, 'max_features': None, 'min_impurity_decrease': 0.0009945527681046958, 'validation_fraction': 0.37599245434253115, 'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:03:32,025] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8197459694618823, 'learning_rate': 0.03360023079554672, 'dropout_rate': 0.6511401870586079, 'n_estimators': 29, 'criterion': 'friedman_mse', 'ccp_alpha': 7.394890156748451, 'min_weight_fraction_leaf': 0.1331354987056353, 'max_features': 'auto', 'min_impurity_decrease': 0.0001565490639462534, 'validation_fraction': 0.31563542391001165, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:03:45,131] Trial 79 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5239417471386933, 'learning_rate': 0.020324753076534783, 'dropout_rate': 0.25505231881333934, 'n_estimators': 219, 'criterion': 'squared_error', 'ccp_alpha': 8.06685235564664, 'min_weight_fraction_leaf': 0.10889477607680587, 'max_features': None, 'min_impurity_decrease': 2.113599021609697e-05, 'validation_fraction': 0.19421333161738485, 'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 10}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927107
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:04:00,704] Trial 80 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8725888660383272, 'learning_rate': 0.015944825589867328, 'dropout_rate': 0.684566586558272, 'n_estimators': 308, 'criterion': 'friedman_mse', 'ccp_alpha': 6.626754475193849, 'min_weight_fraction_leaf': 0.32490362597380895, 'max_features': 1, 'min_impurity_decrease': 3.189051140875929e-05, 'validation_fraction': 0.4647062299696245, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:04:15,374] Trial 81 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9851030735233897, 'learning_rate': 0.01617298889954381, 'dropout_rate': 0.6683098819549974, 'n_estimators': 297, 'criterion': 'friedman_mse', 'ccp_alpha': 6.580155442235007, 'min_weight_fraction_leaf': 0.31801803472675627, 'max_features': 1, 'min_impurity_decrease': 2.8088786642493616e-05, 'validation_fraction': 0.41663372167313234, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:04:25,867] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8801758245051483, 'learning_rate': 0.024733525195074157, 'dropout_rate': 0.7139558779665091, 'n_estimators': 311, 'criterion': 'friedman_mse', 'ccp_alpha': 9.997573572125102, 'min_weight_fraction_leaf': 0.08367564533286902, 'max_features': 1, 'min_impurity_decrease': 7.418590741023808e-05, 'validation_fraction': 0.47120252625356124, 'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:04:44,554] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9511629461490775, 'learning_rate': 0.010703799127539604, 'dropout_rate': 0.5850974519047862, 'n_estimators': 336, 'criterion': 'friedman_mse', 'ccp_alpha': 7.086201460434227, 'min_weight_fraction_leaf': 0.48188681004410056, 'max_features': 1, 'min_impurity_decrease': 0.00026485312270555883, 'validation_fraction': 0.4548697898107937, 'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:04:59,186] Trial 84 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7730054699183814, 'learning_rate': 0.006866392004688175, 'dropout_rate': 0.6818395627907664, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 7.642035659614569, 'min_weight_fraction_leaf': 0.3480539399393692, 'max_features': 1, 'min_impurity_decrease': 1.2025282543134035e-05, 'validation_fraction': 0.514932291069411, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 12}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:05:08,429] Trial 85 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8559905830599279, 'learning_rate': 0.013216767292928883, 'dropout_rate': 0.6269128853450063, 'n_estimators': 250, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997231176802016, 'min_weight_fraction_leaf': 0.3316790138756349, 'max_features': None, 'min_impurity_decrease': 3.410773491431381e-05, 'validation_fraction': 0.34782887139287255, 'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:05:17,151] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.41640653600385713, 'learning_rate': 0.029148850284472, 'dropout_rate': 0.3733362551819358, 'n_estimators': 198, 'criterion': 'friedman_mse', 'ccp_alpha': 3.8050830020464415, 'min_weight_fraction_leaf': 0.27176539102800523, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00013881465549369376, 'validation_fraction': 0.759045833375244, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:05:24,693] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7048418338219802, 'learning_rate': 0.024456935279411653, 'dropout_rate': 0.8053771471721777, 'n_estimators': 285, 'criterion': 'friedman_mse', 'ccp_alpha': 5.158436283745041, 'min_weight_fraction_leaf': 0.3683964225040034, 'max_features': 0.1, 'min_impurity_decrease': 5.606559903342241e-05, 'validation_fraction': 0.7024294040813014, 'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:05:28,000] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7925199188591967, 'learning_rate': 0.01943914587297941, 'dropout_rate': 0.696802829250291, 'n_estimators': 168, 'criterion': 'friedman_mse', 'ccp_alpha': 6.272481661598975, 'min_weight_fraction_leaf': 0.3249496622895373, 'max_features': None, 'min_impurity_decrease': 2.2154716492773994e-05, 'validation_fraction': 0.7362458905800392, 'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 17, 'max_depth': 12}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:05:30,982] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4803472549091154, 'learning_rate': 0.015239495678578295, 'dropout_rate': 0.33485949030843676, 'n_estimators': 116, 'criterion': 'squared_error', 'ccp_alpha': 5.5868763074523216, 'min_weight_fraction_leaf': 0.39691440943727196, 'max_features': 'auto', 'min_impurity_decrease': 0.0017382008281369356, 'validation_fraction': 0.42323889630065503, 'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 17}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:05:45,977] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7495496502041824, 'learning_rate': 0.0581528234960663, 'dropout_rate': 0.7348956640088382, 'n_estimators': 384, 'criterion': 'friedman_mse', 'ccp_alpha': 3.5249398640258107, 'min_weight_fraction_leaf': 0.3046819488123618, 'max_features': 'log2', 'min_impurity_decrease': 6.057529663822337e-06, 'validation_fraction': 0.2789829481077005, 'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:05:46,651] Trial 91 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5619495945045616, 'learning_rate': 0.06700515143766485, 'dropout_rate': 0.1903870588607519, 'n_estimators': 34, 'criterion': 'squared_error', 'ccp_alpha': 7.449087894461449, 'min_weight_fraction_leaf': 0.2457010669612629, 'max_features': 'auto', 'min_impurity_decrease': 1.150176474839188e-05, 'validation_fraction': 0.5390813237956885, 'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:05:48,308] Trial 92 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6020511348147951, 'learning_rate': 0.0751884312975214, 'dropout_rate': 0.289349498772935, 'n_estimators': 64, 'criterion': 'squared_error', 'ccp_alpha': 8.002481509673935, 'min_weight_fraction_leaf': 0.20821682842735198, 'max_features': 'auto', 'min_impurity_decrease': 0.00010766085474385088, 'validation_fraction': 0.5622210271975412, 'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:05:51,338] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6524389740821527, 'learning_rate': 0.07917267348387946, 'dropout_rate': 0.2310520175574847, 'n_estimators': 89, 'criterion': 'squared_error', 'ccp_alpha': 9.28482675594447, 'min_weight_fraction_leaf': 0.28834674865375826, 'max_features': 'auto', 'min_impurity_decrease': 8.136563093404637e-06, 'validation_fraction': 0.6250081009672765, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 16}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:06:11,033] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6243723676927855, 'learning_rate': 0.06455694684464759, 'dropout_rate': 0.1253103630165613, 'n_estimators': 264, 'criterion': 'squared_error', 'ccp_alpha': 9.807305538106032, 'min_weight_fraction_leaf': 0.3529259392744584, 'max_features': None, 'min_impurity_decrease': 4.431281353902667e-06, 'validation_fraction': 0.49514853532238395, 'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:06:41,624] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6928546434090421, 'learning_rate': 0.001289506649460169, 'dropout_rate': 0.16709484913917025, 'n_estimators': 347, 'criterion': 'squared_error', 'ccp_alpha': 7.0945003058216365, 'min_weight_fraction_leaf': 0.18538376079135516, 'max_features': 'auto', 'min_impurity_decrease': 1.6241563337834388e-05, 'validation_fraction': 0.6772438809462125, 'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 10}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:06:43,107] Trial 96 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5303406288830981, 'learning_rate': 0.06135973363662555, 'dropout_rate': 0.5398320786491974, 'n_estimators': 74, 'criterion': 'friedman_mse', 'ccp_alpha': 8.285413956208995, 'min_weight_fraction_leaf': 0.23025482457776003, 'max_features': 'sqrt', 'min_impurity_decrease': 8.586249314653986e-07, 'validation_fraction': 0.39469509063758046, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 15}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:07:04,148] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8201377508003859, 'learning_rate': 0.0714232885979629, 'dropout_rate': 0.2735097127218832, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 8.463198804661687, 'min_weight_fraction_leaf': 0.04410112884248296, 'max_features': 1, 'min_impurity_decrease': 3.464875024423582e-05, 'validation_fraction': 0.45989416649019765, 'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 4}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:07:05,054] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6725518895525195, 'learning_rate': 0.03240418416118321, 'dropout_rate': 0.20305434408241488, 'n_estimators': 46, 'criterion': 'squared_error', 'ccp_alpha': 7.42601105908029, 'min_weight_fraction_leaf': 0.2745945671460241, 'max_features': None, 'min_impurity_decrease': 0.0004100578862687958, 'validation_fraction': 0.5843913892304547, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 18}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:07:05,872] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4938599481005868, 'learning_rate': 0.06858460506990806, 'dropout_rate': 0.7640588788313373, 'n_estimators': 60, 'criterion': 'friedman_mse', 'ccp_alpha': 9.61532146334578, 'min_weight_fraction_leaf': 0.318855540432606, 'max_features': 'auto', 'min_impurity_decrease': 7.638035605998794e-05, 'validation_fraction': 0.5445317964399832, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.


* Best trial for IBS:
 FrozenTrial(number=3, state=TrialState.COMPLETE, values=[0.2359278435123307], datetime_start=datetime.datetime(2024, 4, 16, 21, 48, 6, 218810), datetime_complete=datetime.datetime(2024, 4, 16, 21, 48, 23, 40183), params={'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=3, value=None)


* Best Score for IBS:
 0.2359278435123307

In [107]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [108]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.553
train_ibs:  0.236

#### Test

In [109]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [110]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.07426378544613033,
                                 criterion='squared_error',
                                 dropout_rate=0.28125955124323376,
                                 learning_rate=0.013102111413618,
                                 max_features='auto', max_leaf_nodes=16,
                                 min_impurity_decrease=1.4994028685178666e-07,
                                 min_samples_leaf=10,
                                 min_weight_fraction_leaf=0.27579636299120275,
                                 n_estimators=406, random_state=123,
                                 subsample=0.6059965408578151,
                                 validation_fraction=0.6359003593513561)

C-index score: 0.573

GradientBoostingSurvivalAnalysis(ccp_alpha=7.636828414433382,
                                 dropout_rate=0.6624131518860399,
                                 learning_rate=0.059007718703659076,
                                 max_depth=14, max_leaf_nodes=5,
                                 min_impurity_decrease=1.2496121527731156e-07,
                                 min_samples_leaf=4, min_samples_split=12,
                                 min_weight_fraction_leaf=0.121833187268437,
                                 n_estimators=338, random_state=123,
                                 subsample=0.7023824046660451,
                                 validation_fraction=0.5944318794450425)

IBS: 0.229

In [111]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [112]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [113]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')

            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)

                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 22:07:17,820] A new study created in memory with name: no-name-ae39b9de-406b-4e5e-b47d-62e2ba553934

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 22:07:18,740] Trial 0 finished with value: 0.5743544316635039 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.5743544316635039.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 22:07:25,787] Trial 1 finished with value: 0.593817451925007 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.593817451925007.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.38783269961977185
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:07:27,090] Trial 2 finished with value: 0.5925466161081581 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 1 with value: 0.593817451925007.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.38783269961977185
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:07:29,031] Trial 3 finished with value: 0.5942234169064289 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.5942234169064289.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:07:32,146] Trial 4 finished with value: 0.5949080031488555 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.5949080031488555.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.39923954372623577
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 22:07:35,579] Trial 5 finished with value: 0.5938538084002467 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.5949080031488555.
Fold 1 C-index: 0.4800796812749004
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 22:07:36,952] Trial 6 finished with value: 0.5699104051942735 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.5949080031488555.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8
Fold 4 C-index: 0.39543726235741444
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:07:37,405] Trial 7 finished with value: 0.5915902071976624 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.5949080031488555.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 22:07:40,819] Trial 8 finished with value: 0.5938717030057903 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.5949080031488555.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.39543726235741444
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 22:07:47,119] Trial 9 finished with value: 0.5923507904582617 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.5949080031488555.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 22:07:50,866] Trial 10 finished with value: 0.5989530559794313 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 22:07:55,495] Trial 11 finished with value: 0.5875361372916753 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.39543726235741444
Fold 5 C-index: 0.5836909871244635
[I 2024-04-16 22:07:59,043] Trial 12 finished with value: 0.5959865500858207 and parameters: {'subsample': 0.12141266367187128, 'dropout_rate': 0.2495649826842376, 'n_estimators': 307, 'learning_rate': 0.003072947520444112}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.4800796812749004
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 22:08:03,661] Trial 13 finished with value: 0.5605487030666139 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24730256251618668, 'n_estimators': 369, 'learning_rate': 0.004617537511156582}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:08:06,949] Trial 14 finished with value: 0.5979820365310852 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.24613872338969223, 'n_estimators': 309, 'learning_rate': 0.0025916531369806137}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 22:08:09,569] Trial 15 finished with value: 0.5957444564407923 and parameters: {'subsample': 0.25820782722012925, 'dropout_rate': 0.6881221936703593, 'n_estimators': 283, 'learning_rate': 0.014974700856388605}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:08:15,728] Trial 16 finished with value: 0.5972652420014859 and parameters: {'subsample': 0.25470623831733574, 'dropout_rate': 0.10221540522327308, 'n_estimators': 417, 'learning_rate': 0.035045624947947794}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:08:20,640] Trial 17 finished with value: 0.5949549489607137 and parameters: {'subsample': 0.35331796904627844, 'dropout_rate': 0.22654987460299786, 'n_estimators': 415, 'learning_rate': 0.013958008989949866}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.4448669201520912
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 22:08:20,844] Trial 18 finished with value: 0.5951371619879549 and parameters: {'subsample': 0.1732298585045983, 'dropout_rate': 0.344601438832567, 'n_estimators': 7, 'learning_rate': 0.016306395588901297}. Best is trial 10 with value: 0.5989530559794313.

Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.38783269961977185
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 22:08:21,595] Trial 19 finished with value: 0.5934881605071334 and parameters: {'subsample': 0.3662035355915435, 'dropout_rate': 0.7186486309433362, 'n_estimators': 131, 'learning_rate': 0.001397855219367588}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 22:08:24,080] Trial 20 finished with value: 0.5943461057627897 and parameters: {'subsample': 0.19810816919434093, 'dropout_rate': 0.18129322567164805, 'n_estimators': 245, 'learning_rate': 0.02599747631629869}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.38783269961977185
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 22:08:30,006] Trial 21 finished with value: 0.5960629709470494 and parameters: {'subsample': 0.270399830992761, 'dropout_rate': 0.12395834975058428, 'n_estimators': 429, 'learning_rate': 0.027586822010459054}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 22:08:34,389] Trial 22 finished with value: 0.5961821230333975 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.10654253943742095, 'n_estimators': 353, 'learning_rate': 0.03912222676659999}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:08:41,301] Trial 23 finished with value: 0.5983665095487878 and parameters: {'subsample': 0.22105981974568623, 'dropout_rate': 0.34268749365634654, 'n_estimators': 439, 'learning_rate': 0.010496184153284481}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:08:47,758] Trial 24 finished with value: 0.5942556251936015 and parameters: {'subsample': 0.19912208936101786, 'dropout_rate': 0.3403805831949014, 'n_estimators': 454, 'learning_rate': 0.009932514714019739}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:08:52,187] Trial 25 finished with value: 0.5982290831677416 and parameters: {'subsample': 0.32449330640021046, 'dropout_rate': 0.2907443362596893, 'n_estimators': 376, 'learning_rate': 0.020445881460677832}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.38783269961977185
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:08:57,247] Trial 26 finished with value: 0.5933218099066077 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.44047275507375383, 'n_estimators': 397, 'learning_rate': 0.02012707613797083}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:09:02,161] Trial 27 finished with value: 0.5941255040814808 and parameters: {'subsample': 0.2934002033048555, 'dropout_rate': 0.3060837787360696, 'n_estimators': 379, 'learning_rate': 0.010074242775118288}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.38783269961977185
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:09:06,466] Trial 28 finished with value: 0.5941728737363949 and parameters: {'subsample': 0.4214619605509553, 'dropout_rate': 0.18804677832052086, 'n_estimators': 349, 'learning_rate': 0.019110163306456977}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8
Fold 4 C-index: 0.39543726235741444
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 22:09:12,185] Trial 29 finished with value: 0.5914454755476912 and parameters: {'subsample': 0.6286662525763652, 'dropout_rate': 0.5871085597788133, 'n_estimators': 455, 'learning_rate': 0.04277746375706198}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:09:14,624] Trial 30 finished with value: 0.5951356132428683 and parameters: {'subsample': 0.1825091012269287, 'dropout_rate': 0.3892024351052794, 'n_estimators': 239, 'learning_rate': 0.010151770110557245}. Best is trial 10 with value: 0.5989530559794313.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.39543726235741444
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:09:18,502] Trial 31 finished with value: 0.5998406032712931 and parameters: {'subsample': 0.15800410069223317, 'dropout_rate': 0.28336099180732266, 'n_estimators': 302, 'learning_rate': 0.006453802802861026}. Best is trial 31 with value: 0.5998406032712931.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:09:22,978] Trial 32 finished with value: 0.597453889369292 and parameters: {'subsample': 0.32555437263737985, 'dropout_rate': 0.30180343464344755, 'n_estimators': 331, 'learning_rate': 0.009282284292985932}. Best is trial 31 with value: 0.5998406032712931.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.5836909871244635
[I 2024-04-16 22:09:25,800] Trial 33 finished with value: 0.5975516752074054 and parameters: {'subsample': 0.20458951189411428, 'dropout_rate': 0.48095898939081394, 'n_estimators': 283, 'learning_rate': 0.029768176681194237}. Best is trial 31 with value: 0.5998406032712931.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 22:09:30,457] Trial 34 finished with value: 0.5983296022436568 and parameters: {'subsample': 0.1535800983425104, 'dropout_rate': 0.1929819810694428, 'n_estimators': 391, 'learning_rate': 0.02179748345750352}. Best is trial 31 with value: 0.5998406032712931.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:09:36,146] Trial 35 finished with value: 0.5974712331449444 and parameters: {'subsample': 0.1544894252395592, 'dropout_rate': 0.1763045476512009, 'n_estimators': 436, 'learning_rate': 0.00521652675757459}. Best is trial 31 with value: 0.5998406032712931.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 22:09:43,049] Trial 36 finished with value: 0.6006225515087767 and parameters: {'subsample': 0.23603126479946945, 'dropout_rate': 0.20615972652629336, 'n_estimators': 482, 'learning_rate': 0.08793239753187249}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.3916349809885932

Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:09:53,998] Trial 37 finished with value: 0.5975370646695548 and parameters: {'subsample': 0.21856492743694161, 'dropout_rate': 0.40697127631393737, 'n_estimators': 478, 'learning_rate': 0.0942551407730424}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.38783269961977185
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:10:02,782] Trial 38 finished with value: 0.5925466161081581 and parameters: {'subsample': 0.8179022915704841, 'dropout_rate': 0.1537716325192168, 'n_estimators': 497, 'learning_rate': 0.0802388198308747}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.38783269961977185
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:10:03,939] Trial 39 finished with value: 0.5949553728037698 and parameters: {'subsample': 0.40150962737591755, 'dropout_rate': 0.486386986465816, 'n_estimators': 145, 'learning_rate': 0.06068154266853375}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.39543726235741444
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 22:10:04,668] Trial 40 finished with value: 0.593998667037053 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.8118390494947172, 'n_estimators': 78, 'learning_rate': 0.06802323795644914}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:10:11,781] Trial 41 finished with value: 0.5956564551357364 and parameters: {'subsample': 0.15267318292912732, 'dropout_rate': 0.191294690409952, 'n_estimators': 453, 'learning_rate': 0.08347421577688115}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.39543726235741444
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 22:10:16,267] Trial 42 finished with value: 0.5932234732386032 and parameters: {'subsample': 0.2381484527880857, 'dropout_rate': 0.9772717282714597, 'n_estimators': 394, 'learning_rate': 0.008340019556721782}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.39923954372623577
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 22:10:23,484] Trial 43 finished with value: 0.5998404762844581 and parameters: {'subsample': 0.15339704269557206, 'dropout_rate': 0.21811733721056534, 'n_estimators': 495, 'learning_rate': 0.013431528379168172}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:10:31,329] Trial 44 finished with value: 0.5949006978799304 and parameters: {'subsample': 0.3079906499062095, 'dropout_rate': 0.2877344639768844, 'n_estimators': 487, 'learning_rate': 0.0146430213630084}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:10:33,145] Trial 45 finished with value: 0.5973411120328236 and parameters: {'subsample': 0.22833690589006653, 'dropout_rate': 0.2256632246435626, 'n_estimators': 206, 'learning_rate': 0.07070214514667335}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 22:10:39,924] Trial 46 finished with value: 0.5954901045352108 and parameters: {'subsample': 0.13036297849054782, 'dropout_rate': 0.14531446147958332, 'n_estimators': 465, 'learning_rate': 0.06109717043128143}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:10:46,870] Trial 47 finished with value: 0.5949006978799304 and parameters: {'subsample': 0.28066739780333383, 'dropout_rate': 0.3420945456751306, 'n_estimators': 497, 'learning_rate': 0.006441261056033493}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5364806866952789
[I 2024-04-16 22:10:50,266] Trial 48 finished with value: 0.5942374778857384 and parameters: {'subsample': 0.1010493867464251, 'dropout_rate': 0.5384779422583111, 'n_estimators': 277, 'learning_rate': 0.0989144674866266}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:10:52,781] Trial 49 finished with value: 0.5965558797276468 and parameters: {'subsample': 0.45293964487038113, 'dropout_rate': 0.21928085472004588, 'n_estimators': 224, 'learning_rate': 0.04897928524498507}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 22:10:59,413] Trial 50 finished with value: 0.5915903341844975 and parameters: {'subsample': 0.5199237619141068, 'dropout_rate': 0.26970374112897977, 'n_estimators': 433, 'learning_rate': 0.0011429766447839911}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:11:03,122] Trial 51 finished with value: 0.5965222564902088 and parameters: {'subsample': 0.15997338114196338, 'dropout_rate': 0.1460846894039211, 'n_estimators': 314, 'learning_rate': 0.023434901705376904}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:11:08,643] Trial 52 finished with value: 0.599608294159322 and parameters: {'subsample': 0.13776536253016766, 'dropout_rate': 0.20840019487303524, 'n_estimators': 400, 'learning_rate': 0.033962490267067845}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 22:11:14,049] Trial 53 finished with value: 0.596747557189476 and parameters: {'subsample': 0.2327099656432202, 'dropout_rate': 0.22528032731274408, 'n_estimators': 412, 'learning_rate': 0.03410759888742498}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:11:18,174] Trial 54 finished with value: 0.5996299131098765 and parameters: {'subsample': 0.13949780561400119, 'dropout_rate': 0.3130774538450596, 'n_estimators': 340, 'learning_rate': 0.012485990495562847}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 22:11:21,825] Trial 55 finished with value: 0.600549541702076 and parameters: {'subsample': 0.1372584548446454, 'dropout_rate': 0.259275383561657, 'n_estimators': 296, 'learning_rate': 0.017318596055582818}. Best is trial 36 with value: 0.6006225515087767.

Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 22:11:25,811] Trial 56 finished with value: 0.598771544011164 and parameters: {'subsample': 0.13823029599429779, 'dropout_rate': 0.2573924932384919, 'n_estimators': 338, 'learning_rate': 0.014897416548086101}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.39543726235741444
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:11:29,084] Trial 57 finished with value: 0.5974391518446065 and parameters: {'subsample': 0.19382346783724191, 'dropout_rate': 0.37338460559116476, 'n_estimators': 306, 'learning_rate': 0.025789855414925057}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 22:11:34,139] Trial 58 finished with value: 0.5992168955618489 and parameters: {'subsample': 0.1245221845988517, 'dropout_rate': 0.3170610023595931, 'n_estimators': 364, 'learning_rate': 0.03930223601657025}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.39543726235741444
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:11:37,300] Trial 59 finished with value: 0.5958960695166325 and parameters: {'subsample': 0.18505065482034147, 'dropout_rate': 0.4072999068164583, 'n_estimators': 251, 'learning_rate': 0.017515127863295277}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.4800796812749004
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.8
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 22:11:41,825] Trial 60 finished with value: 0.5690593413644862 and parameters: {'subsample': 0.9718433307655755, 'dropout_rate': 0.27095791162611155, 'n_estimators': 324, 'learning_rate': 0.03136696153263342}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 22:11:45,623] Trial 61 finished with value: 0.6003219316080631 and parameters: {'subsample': 0.12722757194347895, 'dropout_rate': 0.3234770907417588, 'n_estimators': 348, 'learning_rate': 0.0404030562714692}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 22:11:49,540] Trial 62 finished with value: 0.5994635625093507 and parameters: {'subsample': 0.13068386197244639, 'dropout_rate': 0.32201366345279775, 'n_estimators': 350, 'learning_rate': 0.04822045571065308}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.39923954372623577
Fold 5 C-index: 0.5836909871244635
[I 2024-04-16 22:11:52,801] Trial 63 finished with value: 0.5966711363282473 and parameters: {'subsample': 0.2613720543137052, 'dropout_rate': 0.21271183094680157, 'n_estimators': 297, 'learning_rate': 0.05203631745277128}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:11:55,248] Trial 64 finished with value: 0.5964859000149693 and parameters: {'subsample': 0.10583176265682888, 'dropout_rate': 0.2499472932815694, 'n_estimators': 258, 'learning_rate': 0.05650620786849369}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.39923954372623577
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:11:57,739] Trial 65 finished with value: 0.5990579772170833 and parameters: {'subsample': 0.17764734792165104, 'dropout_rate': 0.45078797225289446, 'n_estimators': 288, 'learning_rate': 0.04378585173868104}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:12:03,445] Trial 66 finished with value: 0.5973953631136067 and parameters: {'subsample': 0.1580573010152704, 'dropout_rate': 0.16082030955099214, 'n_estimators': 407, 'learning_rate': 0.03756289082110905}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.39543726235741444
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:12:07,241] Trial 67 finished with value: 0.595722710503403 and parameters: {'subsample': 0.24461387216949196, 'dropout_rate': 0.3636281274923132, 'n_estimators': 341, 'learning_rate': 0.012647333456084512}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 22:12:11,468] Trial 68 finished with value: 0.5751512444125078 and parameters: {'subsample': 0.785348199692441, 'dropout_rate': 0.2811900909765567, 'n_estimators': 371, 'learning_rate': 0.028216760064405957}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 22:12:14,378] Trial 69 finished with value: 0.59558113593429 and parameters: {'subsample': 0.20757332177604096, 'dropout_rate': 0.2059527325110123, 'n_estimators': 273, 'learning_rate': 0.006761483166808091}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:12:19,468] Trial 70 finished with value: 0.5948201288306345 and parameters: {'subsample': 0.13694645608413478, 'dropout_rate': 0.13030520803126538, 'n_estimators': 381, 'learning_rate': 0.017734551351431566}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5836909871244635
[I 2024-04-16 22:12:23,599] Trial 71 finished with value: 0.5991042452122153 and parameters: {'subsample': 0.12378084857567546, 'dropout_rate': 0.3257125487712347, 'n_estimators': 353, 'learning_rate': 0.04835987569718071}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 22:12:26,796] Trial 72 finished with value: 0.596478594746044 and parameters: {'subsample': 0.1034979778008531, 'dropout_rate': 0.3077045673251646, 'n_estimators': 317, 'learning_rate': 0.04644202343981972}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.4800796812749004
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.8
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 22:12:30,250] Trial 73 finished with value: 0.5706781667369629 and parameters: {'subsample': 0.9104698751711979, 'dropout_rate': 0.238778867793718, 'n_estimators': 335, 'learning_rate': 0.05711615167204167}. Best is trial 36 with value: 0.6006225515087767.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.39543726235741444
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 22:12:36,081] Trial 74 finished with value: 0.5975296324137946 and parameters: {'subsample': 0.1787460210321348, 'dropout_rate': 0.41370532181212294, 'n_estimators': 469, 'learning_rate': 0.03471229822615198}. Best is trial 36 with value: 0.6006225515087767.

Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 22:12:39,753] Trial 75 finished with value: 0.6022735851684262 and parameters: {'subsample': 0.14305853399792298, 'dropout_rate': 0.3678471747462695, 'n_estimators': 349, 'learning_rate': 0.039763754907327475}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 22:12:42,921] Trial 76 finished with value: 0.5946685157547942 and parameters: {'subsample': 0.6955258860128068, 'dropout_rate': 0.3643550653247036, 'n_estimators': 293, 'learning_rate': 0.04225040977333992}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:12:48,300] Trial 77 finished with value: 0.5957148544045867 and parameters: {'subsample': 0.205157691197205, 'dropout_rate': 0.17629353184919394, 'n_estimators': 420, 'learning_rate': 0.040360603478445146}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.39923954372623577
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:12:50,508] Trial 78 finished with value: 0.5981021191364789 and parameters: {'subsample': 0.16160239801918624, 'dropout_rate': 0.28665812804249907, 'n_estimators': 263, 'learning_rate': 0.012788474993417655}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 22:12:53,723] Trial 79 finished with value: 0.5988474140425015 and parameters: {'subsample': 0.14365421580511567, 'dropout_rate': 0.2566408457788282, 'n_estimators': 323, 'learning_rate': 0.02530285321254835}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:12:55,755] Trial 80 finished with value: 0.5941255040814808 and parameters: {'subsample': 0.29509125144368054, 'dropout_rate': 0.5030557784392189, 'n_estimators': 232, 'learning_rate': 0.032503205468983394}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:12:59,342] Trial 81 finished with value: 0.6005715844956866 and parameters: {'subsample': 0.13704903623386336, 'dropout_rate': 0.342342017886326, 'n_estimators': 354, 'learning_rate': 0.06552949907008851}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.39923954372623577
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:13:03,869] Trial 82 finished with value: 0.5957981566916845 and parameters: {'subsample': 0.17345853062169567, 'dropout_rate': 0.43019089541926653, 'n_estimators': 362, 'learning_rate': 0.07703134800478594}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 22:13:07,797] Trial 83 finished with value: 0.5908367593366022 and parameters: {'subsample': 0.22444518586244855, 'dropout_rate': 0.6202793429199533, 'n_estimators': 387, 'learning_rate': 0.08703683017563568}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 22:13:12,339] Trial 84 finished with value: 0.59670334461542 and parameters: {'subsample': 0.12267480337737759, 'dropout_rate': 0.3815729951337088, 'n_estimators': 401, 'learning_rate': 0.03691628210830792}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.39543726235741444
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 22:13:19,655] Trial 85 finished with value: 0.5948713498173944 and parameters: {'subsample': 0.19455697009439923, 'dropout_rate': 0.3409519367980083, 'n_estimators': 485, 'learning_rate': 0.06829383934450527}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 22:13:24,241] Trial 86 finished with value: 0.6006078139840914 and parameters: {'subsample': 0.14621038295753405, 'dropout_rate': 0.29914147656574785, 'n_estimators': 309, 'learning_rate': 0.06372583418560197}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 22:13:28,856] Trial 87 finished with value: 0.5964243436652608 and parameters: {'subsample': 0.1012640686852348, 'dropout_rate': 0.30494782274685633, 'n_estimators': 300, 'learning_rate': 0.06559088056864305}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.39923954372623577
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 22:13:34,931] Trial 88 finished with value: 0.5975148948891092 and parameters: {'subsample': 0.16675515522850998, 'dropout_rate': 0.35207815091820593, 'n_estimators': 447, 'learning_rate': 0.07454985677182703}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:13:38,159] Trial 89 finished with value: 0.5964900482030363 and parameters: {'subsample': 0.2516079832668957, 'dropout_rate': 0.23612959098012326, 'n_estimators': 307, 'learning_rate': 0.05896750548347325}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.39543726235741444
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 22:13:42,234] Trial 90 finished with value: 0.5983806962435818 and parameters: {'subsample': 0.2148204197866166, 'dropout_rate': 0.27372649602164045, 'n_estimators': 343, 'learning_rate': 0.06361363158102047}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5450643776824035
[I 2024-04-16 22:13:45,908] Trial 91 finished with value: 0.5881126452155916 and parameters: {'subsample': 0.144307107862969, 'dropout_rate': 0.1991956116270163, 'n_estimators': 330, 'learning_rate': 0.09259839478726366}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.41064638783269963
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:13:49,618] Trial 92 finished with value: 0.5988547193114269 and parameters: {'subsample': 0.14765967392819318, 'dropout_rate': 0.32617889980910253, 'n_estimators': 357, 'learning_rate': 0.04519337990737928}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:13:53,779] Trial 93 finished with value: 0.5958665944672619 and parameters: {'subsample': 0.12164782806711999, 'dropout_rate': 0.29284305457210164, 'n_estimators': 373, 'learning_rate': 0.05434881810819593}. Best is trial 75 with value: 0.6022735851684262.

Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 22:13:57,543] Trial 94 finished with value: 0.5972506314636354 and parameters: {'subsample': 0.17769103524019822, 'dropout_rate': 0.16553867449630594, 'n_estimators': 314, 'learning_rate': 0.004279106024937954}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 22:14:04,544] Trial 95 finished with value: 0.5948418747680237 and parameters: {'subsample': 0.18854063978170543, 'dropout_rate': 0.25584777150354415, 'n_estimators': 461, 'learning_rate': 0.052413017467542566}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 22:14:09,749] Trial 96 finished with value: 0.6014519963880096 and parameters: {'subsample': 0.14159458900744956, 'dropout_rate': 0.7884374875884069, 'n_estimators': 480, 'learning_rate': 0.007459681600112268}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.40304182509505704
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 22:14:14,711] Trial 97 finished with value: 0.5981236111001984 and parameters: {'subsample': 0.16152393951315713, 'dropout_rate': 0.8831368288669302, 'n_estimators': 479, 'learning_rate': 0.008952192772593785}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.3916349809885932
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 22:14:20,595] Trial 98 finished with value: 0.5949223168304847 and parameters: {'subsample': 0.26964683755567515, 'dropout_rate': 0.7965494949240809, 'n_estimators': 499, 'learning_rate': 0.021872397696973585}. Best is trial 75 with value: 0.6022735851684262.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.40304182509505704

[I 2024-04-16 22:14:23,127] A new study created in memory with name: no-name-57b69b3c-c903-45f1-b1e2-cc04fed0445d

Fold 5 C-index: 0.5450643776824035
[I 2024-04-16 22:14:23,111] Trial 99 finished with value: 0.5913109093912821 and parameters: {'subsample': 0.11476324910978145, 'dropout_rate': 0.654405477215362, 'n_estimators': 276, 'learning_rate': 0.004058218670512658}. Best is trial 75 with value: 0.6022735851684262.


* Best trial for C-index:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.6022735851684262], datetime_start=datetime.datetime(2024, 4, 16, 22, 12, 36, 92234), datetime_complete=datetime.datetime(2024, 4, 16, 22, 12, 39, 752876), params={'subsample': 0.14305853399792298, 'dropout_rate': 0.3678471747462695, 'n_estimators': 349, 'learning_rate': 0.039763754907327475}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=75, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.14305853399792298, 'dropout_rate': 0.3678471747462695, 'n_estimators': 349, 'learning_rate': 0.039763754907327475}


* Best Score for C-index:
 0.6022735851684262

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.3520675741941785
Fold 2 IBS: 0.2668815380356568
Fold 3 IBS: 0.1760621078453766
Fold 4 IBS: 0.41137986365343837
Fold 5 IBS: 0.2764353459358729
[I 2024-04-16 22:14:23,964] Trial 0 finished with value: 0.2965652859329046 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2965652859329046.
Fold 1 IBS: 0.40287832065024165
Fold 2 IBS: 0.40769869706001544
Fold 3 IBS: 0.17456125636520473
Fold 4 IBS: 0.5004561521908811
Fold 5 IBS: 0.33793703191358354
[I 2024-04-16 22:14:30,900] Trial 1 finished with value: 0.3647062916359853 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2965652859329046.
Fold 1 IBS: 0.3892299068545766
Fold 2 IBS: 0.3245733242980335
Fold 3 IBS: 0.16014341870439533
Fold 4 IBS: 0.4854588570700433
Fold 5 IBS: 0.32649827111608143
[I 2024-04-16 22:14:32,380] Trial 2 finished with value: 0.33718075560862604 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2965652859329046.
Fold 1 IBS: 0.39310663073980695
Fold 2 IBS: 0.314042337380128
Fold 3 IBS: 0.1622575070332053
Fold 4 IBS: 0.4917581006697975
Fold 5 IBS: 0.3341860741001524
[I 2024-04-16 22:14:34,219] Trial 3 finished with value: 0.33907012998461805 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2965652859329046.
Fold 1 IBS: 0.3970977489060107
Fold 2 IBS: 0.30135311453595365
Fold 3 IBS: 0.15926091317103813
Fold 4 IBS: 0.49071298528053425
Fold 5 IBS: 0.33980840388133965
[I 2024-04-16 22:14:36,728] Trial 4 finished with value: 0.3376466331549753 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2965652859329046.
Fold 1 IBS: 0.39783272957598065
Fold 2 IBS: 0.3855463074701259
Fold 3 IBS: 0.1602283048400997
Fold 4 IBS: 0.4961320340471077
Fold 5 IBS: 0.33590968691302986
[I 2024-04-16 22:14:40,089] Trial 5 finished with value: 0.3551298125692688 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2965652859329046.
Fold 1 IBS: 0.32177563409092536
Fold 2 IBS: 0.24096621733261378
Fold 3 IBS: 0.18676991828243494
Fold 4 IBS: 0.36572077235924466
Fold 5 IBS: 0.25505854668323125
[I 2024-04-16 22:14:41,522] Trial 6 finished with value: 0.27405821774968997 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.27405821774968997.
Fold 1 IBS: 0.2713897103344369
Fold 2 IBS: 0.2213223823356419
Fold 3 IBS: 0.20786311739780203
Fold 4 IBS: 0.29188176963014845
Fold 5 IBS: 0.23137719879830895
[I 2024-04-16 22:14:41,940] Trial 7 finished with value: 0.24476683569926766 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.24476683569926766.
Fold 1 IBS: 0.3570907985562397
Fold 2 IBS: 0.2705136869037388
Fold 3 IBS: 0.1727859732458536
Fold 4 IBS: 0.41656805884170456
Fold 5 IBS: 0.28250269577466347
[I 2024-04-16 22:14:43,811] Trial 8 finished with value: 0.29989224266444003 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.24476683569926766.
Fold 1 IBS: 0.4016769910674874
Fold 2 IBS: 0.38842339323626357
Fold 3 IBS: 0.15684276300663888
Fold 4 IBS: 0.5091153204796116
Fold 5 IBS: 0.33708342444669226
[I 2024-04-16 22:14:48,476] Trial 9 finished with value: 0.35862837844733875 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.24476683569926766.
Fold 1 IBS: 0.24749144321234912
Fold 2 IBS: 0.23167322289475598
Fold 3 IBS: 0.22843665677201186
Fold 4 IBS: 0.2427820002213163
Fold 5 IBS: 0.22926939923653816
[I 2024-04-16 22:14:48,826] Trial 10 finished with value: 0.2359305444673943 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.2359305444673943.
Fold 1 IBS: 0.24834013325939944
Fold 2 IBS: 0.23054446395736944
Fold 3 IBS: 0.22662248852317962
Fold 4 IBS: 0.245609600370183
Fold 5 IBS: 0.22893335715396343
[I 2024-04-16 22:14:49,068] Trial 11 finished with value: 0.23601000865281901 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 10 with value: 0.2359305444673943.
Fold 1 IBS: 0.33901834510576145
Fold 2 IBS: 0.2513474261727983
Fold 3 IBS: 0.19098705604290112
Fold 4 IBS: 0.3885349782394276
Fold 5 IBS: 0.26776341124287906
[I 2024-04-16 22:14:49,539] Trial 12 finished with value: 0.2875302433607535 and parameters: {'subsample': 0.9876601507615164, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 10 with value: 0.2359305444673943.
Fold 1 IBS: 0.24737415621917935
Fold 2 IBS: 0.23184355194867592
Fold 3 IBS: 0.22868202475273483
Fold 4 IBS: 0.24241648107662522
Fold 5 IBS: 0.22932756599320225
[I 2024-04-16 22:14:49,795] Trial 13 finished with value: 0.23592875599808352 and parameters: {'subsample': 0.9944701185331792, 'dropout_rate': 0.7324371247382785, 'n_estimators': 3, 'learning_rate': 0.007730532223257889}. Best is trial 13 with value: 0.23592875599808352.
Fold 1 IBS: 0.248937516204768
Fold 2 IBS: 0.22995017719566707
Fold 3 IBS: 0.2255815277906087
Fold 4 IBS: 0.24726357912122934
Fold 5 IBS: 0.22876649355871817
[I 2024-04-16 22:14:50,452] Trial 14 finished with value: 0.23609985877419826 and parameters: {'subsample': 0.8637836787170821, 'dropout_rate': 0.9788958362896205, 'n_estimators': 102, 'learning_rate': 0.0025916531369806137}. Best is trial 13 with value: 0.23592875599808352.
Fold 1 IBS: 0.24735760920529584
Fold 2 IBS: 0.23187324825307373
Fold 3 IBS: 0.22871379997706892
Fold 4 IBS: 0.24237034819641146
Fold 5 IBS: 0.22933460495739025
[I 2024-04-16 22:14:50,750] Trial 15 finished with value: 0.23592992211784805 and parameters: {'subsample': 0.8912920435266729, 'dropout_rate': 0.7994004963170612, 'n_estimators': 13, 'learning_rate': 0.0015537236853158376}. Best is trial 13 with value: 0.23592875599808352.
Fold 1 IBS: 0.3091692290714151
Fold 2 IBS: 0.215073738101963
Fold 3 IBS: 0.18813628426465498
Fold 4 IBS: 0.3538715538770663
Fold 5 IBS: 0.260542013647771
[I 2024-04-16 22:14:53,374] Trial 16 finished with value: 0.26535856379257405 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.8270228189409228, 'n_estimators': 315, 'learning_rate': 0.017212997372337172}. Best is trial 13 with value: 0.23592875599808352.
Fold 1 IBS: 0.2600524543054558
Fold 2 IBS: 0.22531043175306814
Fold 3 IBS: 0.21375553324926763
Fold 4 IBS: 0.27234093375370266
Fold 5 IBS: 0.2295270271487251
[I 2024-04-16 22:14:54,084] Trial 17 finished with value: 0.24019727604204388 and parameters: {'subsample': 0.8614054028098825, 'dropout_rate': 0.6004730897368156, 'n_estimators': 99, 'learning_rate': 0.01245288911484009}. Best is trial 13 with value: 0.23592875599808352.
Fold 1 IBS: 0.3196307233967578
Fold 2 IBS: 0.24076423286633336
Fold 3 IBS: 0.1889756420637952
Fold 4 IBS: 0.36515415519224104
Fold 5 IBS: 0.2560628760300728
[I 2024-04-16 22:14:54,935] Trial 18 finished with value: 0.27411752590984 and parameters: {'subsample': 0.8597800373764937, 'dropout_rate': 0.7964804939751499, 'n_estimators': 119, 'learning_rate': 0.03489214489588591}. Best is trial 13 with value: 0.23592875599808352.
Fold 1 IBS: 0.3307030068481523

Fold 2 IBS: 0.24471484981206823
Fold 3 IBS: 0.1838567017320815
Fold 4 IBS: 0.3810912888510208
Fold 5 IBS: 0.2589104839271485
[I 2024-04-16 22:14:58,218] Trial 19 finished with value: 0.27985526623409424 and parameters: {'subsample': 0.650899739648275, 'dropout_rate': 0.9954484919483726, 'n_estimators': 400, 'learning_rate': 0.011730584939170362}. Best is trial 13 with value: 0.23592875599808352.
Fold 1 IBS: 0.26865035103700036
Fold 2 IBS: 0.2248930841263748
Fold 3 IBS: 0.20869332419609296
Fold 4 IBS: 0.2874440317119254
Fold 5 IBS: 0.23152896013842253
[I 2024-04-16 22:14:58,704] Trial 20 finished with value: 0.2442419502419632 and parameters: {'subsample': 0.9010126869682862, 'dropout_rate': 0.6173032374045795, 'n_estimators': 67, 'learning_rate': 0.0257290746252228}. Best is trial 13 with value: 0.23592875599808352.
Fold 1 IBS: 0.24734112833834176
Fold 2 IBS: 0.2318949440751368
Fold 3 IBS: 0.22874717671047945
Fold 4 IBS: 0.24231017005455716
Fold 5 IBS: 0.22934262647544185
[I 2024-04-16 22:14:59,057] Trial 21 finished with value: 0.2359272091307914 and parameters: {'subsample': 0.9343846884001734, 'dropout_rate': 0.7514483038714346, 'n_estimators': 11, 'learning_rate': 0.0016108337344105245}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.2472622548616072
Fold 2 IBS: 0.23202003901112786
Fold 3 IBS: 0.228947227239391
Fold 4 IBS: 0.24202407918277447
Fold 5 IBS: 0.22938831994685865
[I 2024-04-16 22:14:59,362] Trial 22 finished with value: 0.23592838404835184 and parameters: {'subsample': 0.8051066436583272, 'dropout_rate': 0.7849083992914515, 'n_estimators': 2, 'learning_rate': 0.001288195328092727}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.26639840115796526
Fold 2 IBS: 0.2248786807893083
Fold 3 IBS: 0.20975737884697773
Fold 4 IBS: 0.2819712282947974
Fold 5 IBS: 0.23092157288354753
[I 2024-04-16 22:15:00,306] Trial 23 finished with value: 0.2427854523945193 and parameters: {'subsample': 0.7960032419366929, 'dropout_rate': 0.7647225723640668, 'n_estimators': 135, 'learning_rate': 0.011690418826121547}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.2593163183701348
Fold 2 IBS: 0.22502407181440606
Fold 3 IBS: 0.21581789825846254
Fold 4 IBS: 0.2673754368436218
Fold 5 IBS: 0.2287569399638171
[I 2024-04-16 22:15:00,893] Trial 24 finished with value: 0.23925813305008847 and parameters: {'subsample': 0.6159523319227614, 'dropout_rate': 0.8919984776035661, 'n_estimators': 60, 'learning_rate': 0.019745129742150442}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.24772175522864742
Fold 2 IBS: 0.23135479136945203
Fold 3 IBS: 0.22787400663293608
Fold 4 IBS: 0.2435893987695212
Fold 5 IBS: 0.2291543314557415
[I 2024-04-16 22:15:01,217] Trial 25 finished with value: 0.23593885669125964 and parameters: {'subsample': 0.9302723371622602, 'dropout_rate': 0.6164454236417651, 'n_estimators': 10, 'learning_rate': 0.008500348756543277}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.28192672017277953
Fold 2 IBS: 0.22649085424376855
Fold 3 IBS: 0.20367095925671555
Fold 4 IBS: 0.3080438550036508
Fold 5 IBS: 0.23623291258587473
[I 2024-04-16 22:15:01,719] Trial 26 finished with value: 0.2512730602525578 and parameters: {'subsample': 0.9410835899028251, 'dropout_rate': 0.9365425863488012, 'n_estimators': 72, 'learning_rate': 0.033335519665507754}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.35942967943060655
Fold 2 IBS: 0.2706112545864691
Fold 3 IBS: 0.17461003658142074
Fold 4 IBS: 0.42022531743623215
Fold 5 IBS: 0.2859441465829295
[I 2024-04-16 22:15:02,800] Trial 27 finished with value: 0.30216408692353164 and parameters: {'subsample': 0.8067838665321584, 'dropout_rate': 0.5288134738174257, 'n_estimators': 151, 'learning_rate': 0.043467308912439384}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.2492568209373902
Fold 2 IBS: 0.22976586061891663
Fold 3 IBS: 0.22518285218136808
Fold 4 IBS: 0.24797178391545102
Fold 5 IBS: 0.2287195262129117
[I 2024-04-16 22:15:03,174] Trial 28 finished with value: 0.23617936877320753 and parameters: {'subsample': 0.8072189290138386, 'dropout_rate': 0.6650172386686171, 'n_estimators': 33, 'learning_rate': 0.008840283601572695}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.26980603431655265
Fold 2 IBS: 0.22493954874877242
Fold 3 IBS: 0.20804776968302124
Fold 4 IBS: 0.2864925351037479
Fold 5 IBS: 0.23104068598547664
[I 2024-04-16 22:15:03,849] Trial 29 finished with value: 0.24406531476751417 and parameters: {'subsample': 0.6997683231046966, 'dropout_rate': 0.8464392486282114, 'n_estimators': 97, 'learning_rate': 0.018290562960426554}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.2647994810391976
Fold 2 IBS: 0.22451721230895144
Fold 3 IBS: 0.21065948078880053
Fold 4 IBS: 0.2765200257936732
Fold 5 IBS: 0.23006611790274067
[I 2024-04-16 22:15:05,810] Trial 30 finished with value: 0.2413124635666727 and parameters: {'subsample': 0.5936384513688024, 'dropout_rate': 0.7617601277562117, 'n_estimators': 248, 'learning_rate': 0.006154467049609045}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.24734442454838046
Fold 2 IBS: 0.2318985761694913
Fold 3 IBS: 0.22875695296748177
Fold 4 IBS: 0.2423226240379607
Fold 5 IBS: 0.22934311867226737
[I 2024-04-16 22:15:06,167] Trial 31 finished with value: 0.23593313927911633 and parameters: {'subsample': 0.9110614094922455, 'dropout_rate': 0.7887178087585408, 'n_estimators': 7, 'learning_rate': 0.002555164233159292}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.2480009217774202
Fold 2 IBS: 0.23099457402779514
Fold 3 IBS: 0.22728964036868662
Fold 4 IBS: 0.2444482344116481
Fold 5 IBS: 0.22905171072015437
[I 2024-04-16 22:15:06,804] Trial 32 finished with value: 0.2359570162611409 and parameters: {'subsample': 0.7710772224227727, 'dropout_rate': 0.6790785083649917, 'n_estimators': 80, 'learning_rate': 0.0015921545861661414}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.25028795564380574
Fold 2 IBS: 0.2288281917633002
Fold 3 IBS: 0.22350271441508224
Fold 4 IBS: 0.2511431666265598
Fold 5 IBS: 0.22856165988786287
[I 2024-04-16 22:15:07,161] Trial 33 finished with value: 0.23646473766732218 and parameters: {'subsample': 0.853322293488074, 'dropout_rate': 0.824201339213197, 'n_estimators': 25, 'learning_rate': 0.017073950548131694}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.2475005058193475
Fold 2 IBS: 0.23164884670041527
Fold 3 IBS: 0.22840717418803874
Fold 4 IBS: 0.242871486089357
Fold 5 IBS: 0.22926297077136354
[I 2024-04-16 22:15:07,596] Trial 34 finished with value: 0.23593819671370442 and parameters: {'subsample': 0.9457148899201493, 'dropout_rate': 0.9366074609916502, 'n_estimators': 2, 'learning_rate': 0.024734341677464432}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.24907545677270376
Fold 2 IBS: 0.2297031396065716
Fold 3 IBS: 0.22566836911473878
Fold 4 IBS: 0.24765836534334823
Fold 5 IBS: 0.2287349224668156
[I 2024-04-16 22:15:07,999] Trial 35 finished with value: 0.2361680506608356 and parameters: {'subsample': 0.7162957194905093, 'dropout_rate': 0.4895850417242549, 'n_estimators': 39, 'learning_rate': 0.007211129899269886}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.2700319369767295
Fold 2 IBS: 0.22494428237032388
Fold 3 IBS: 0.20838019916464987
Fold 4 IBS: 0.2885422346148938
Fold 5 IBS: 0.2319903156834075
[I 2024-04-16 22:15:08,908] Trial 36 finished with value: 0.2447777937620009 and parameters: {'subsample': 0.8948847932221162, 'dropout_rate': 0.7714979207760732, 'n_estimators': 129, 'learning_rate': 0.013786612045605471}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.29371728654607276
Fold 2 IBS: 0.22890159446027195
Fold 3 IBS: 0.1986025537445983
Fold 4 IBS: 0.32351703145816757
Fold 5 IBS: 0.2409892905296607
[I 2024-04-16 22:15:09,593] Trial 37 finished with value: 0.25714555134775424 and parameters: {'subsample': 0.9906833763979817, 'dropout_rate': 0.5912122690262406, 'n_estimators': 38, 'learning_rate': 0.07677405503763898}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.31781761241367673
Fold 2 IBS: 0.24234309221016676
Fold 3 IBS: 0.1845894566213129

Fold 4 IBS: 0.36238164279418583
Fold 5 IBS: 0.24860764869709162
[I 2024-04-16 22:15:10,399] Trial 38 finished with value: 0.2711478905472867 and parameters: {'subsample': 0.822360889083144, 'dropout_rate': 0.13272164755980653, 'n_estimators': 84, 'learning_rate': 0.060691705645777076}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.3201955917664464
Fold 2 IBS: 0.2341771425521463
Fold 3 IBS: 0.1886473281684259
Fold 4 IBS: 0.3660097798438394
Fold 5 IBS: 0.25014108036086385
[I 2024-04-16 22:15:11,497] Trial 39 finished with value: 0.2718341845383444 and parameters: {'subsample': 0.3972684667616401, 'dropout_rate': 0.8833943811644197, 'n_estimators': 159, 'learning_rate': 0.027825288019738728}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.28010588003020465
Fold 2 IBS: 0.22666590260107977
Fold 3 IBS: 0.2019086955339845
Fold 4 IBS: 0.30841973010009777
Fold 5 IBS: 0.23462207425601805
[I 2024-04-16 22:15:11,927] Trial 40 finished with value: 0.25034445650427695 and parameters: {'subsample': 0.7596420743421275, 'dropout_rate': 0.27073406810212547, 'n_estimators': 59, 'learning_rate': 0.041936016317294614}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.247494040947896
Fold 2 IBS: 0.23166962952932835
Fold 3 IBS: 0.2284105402739501
Fold 4 IBS: 0.24280559336306515
Fold 5 IBS: 0.2292632341454219
[I 2024-04-16 22:15:12,260] Trial 41 finished with value: 0.2359286076519323 and parameters: {'subsample': 0.9574238022949979, 'dropout_rate': 0.7256251191081852, 'n_estimators': 26, 'learning_rate': 0.0017180709761353205}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.2482855632047384
Fold 2 IBS: 0.2306553823126635
Fold 3 IBS: 0.2268178932542996
Fold 4 IBS: 0.24528086831827411
Fold 5 IBS: 0.22894215693265121
[I 2024-04-16 22:15:12,620] Trial 42 finished with value: 0.2359963728045254 and parameters: {'subsample': 0.9613763711419805, 'dropout_rate': 0.7349964359433082, 'n_estimators': 28, 'learning_rate': 0.006124096043443149}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.24796233622101635
Fold 2 IBS: 0.23104477519904285
Fold 3 IBS: 0.22743235750410573
Fold 4 IBS: 0.24435760725829764
Fold 5 IBS: 0.22906739839522794
[I 2024-04-16 22:15:12,932] Trial 43 finished with value: 0.23597289491553805 and parameters: {'subsample': 0.8915676699471965, 'dropout_rate': 0.6516629391956077, 'n_estimators': 21, 'learning_rate': 0.005729720439853833}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.24757421608169614
Fold 2 IBS: 0.23153479419962947
Fold 3 IBS: 0.22819379452340421
Fold 4 IBS: 0.2431233002192162
Fold 5 IBS: 0.22922225560018797
[I 2024-04-16 22:15:13,207] Trial 44 finished with value: 0.2359296721248268 and parameters: {'subsample': 0.9464145027143659, 'dropout_rate': 0.6996392201491086, 'n_estimators': 3, 'learning_rate': 0.020795878626984905}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.253873083942642
Fold 2 IBS: 0.22693697645216002
Fold 3 IBS: 0.21967380353921973
Fold 4 IBS: 0.2594242578490406
Fold 5 IBS: 0.2285522615178543
[I 2024-04-16 22:15:13,631] Trial 45 finished with value: 0.23769207666018333 and parameters: {'subsample': 0.9531087720006959, 'dropout_rate': 0.6878312504864506, 'n_estimators': 51, 'learning_rate': 0.015135950013739321}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.24749262016556747
Fold 2 IBS: 0.23165865423220539
Fold 3 IBS: 0.22840598593656442
Fold 4 IBS: 0.2428273629934245
Fold 5 IBS: 0.22926601348735445
[I 2024-04-16 22:15:13,864] Trial 46 finished with value: 0.23593012736302327 and parameters: {'subsample': 0.9947892138892012, 'dropout_rate': 0.7297936611246274, 'n_estimators': 2, 'learning_rate': 0.02246836132445744}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.27283831538376857
Fold 2 IBS: 0.2251117076362393
Fold 3 IBS: 0.20616013472552677
Fold 4 IBS: 0.2938138187027343
Fold 5 IBS: 0.232999166431349
[I 2024-04-16 22:15:15,126] Trial 47 finished with value: 0.24618462857592363 and parameters: {'subsample': 0.8437799481920595, 'dropout_rate': 0.8547005442264382, 'n_estimators': 190, 'learning_rate': 0.010152184398450047}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.26216821021226994
Fold 2 IBS: 0.22509555575876508
Fold 3 IBS: 0.21300221131687314
Fold 4 IBS: 0.2760345094573897
Fold 5 IBS: 0.2299350507218515
[I 2024-04-16 22:15:15,569] Trial 48 finished with value: 0.24124710749342987 and parameters: {'subsample': 0.9412129874260508, 'dropout_rate': 0.5758773874350814, 'n_estimators': 46, 'learning_rate': 0.02979653525837964}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.3337052622491848
Fold 2 IBS: 0.23020612297555504
Fold 3 IBS: 0.18218827796970655
Fold 4 IBS: 0.37812319585957305
Fold 5 IBS: 0.26692893891848973
[I 2024-04-16 22:15:18,362] Trial 49 finished with value: 0.2782303595945018 and parameters: {'subsample': 0.1861830169994726, 'dropout_rate': 0.6556782244001339, 'n_estimators': 301, 'learning_rate': 0.020155237665706507}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.25120830191089566
Fold 2 IBS: 0.22820717207025365
Fold 3 IBS: 0.22234404900123922
Fold 4 IBS: 0.25312679156089285
Fold 5 IBS: 0.2284958533300911
[I 2024-04-16 22:15:23,114] Trial 50 finished with value: 0.2366764335746745 and parameters: {'subsample': 0.909123929884357, 'dropout_rate': 0.42732372125147283, 'n_estimators': 433, 'learning_rate': 0.0012082809866883776}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.2478088266439355
Fold 2 IBS: 0.2312224583479275
Fold 3 IBS: 0.22770223846278634
Fold 4 IBS: 0.24389348321989798
Fold 5 IBS: 0.22912492014122152
[I 2024-04-16 22:15:23,453] Trial 51 finished with value: 0.23595038536315377 and parameters: {'subsample': 0.8788182606087853, 'dropout_rate': 0.8170778646524619, 'n_estimators': 23, 'learning_rate': 0.004278476510780966}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.25620179430803064
Fold 2 IBS: 0.22616486640461114
Fold 3 IBS: 0.21748251909051752
Fold 4 IBS: 0.2642414356318762
Fold 5 IBS: 0.2288011498296591
[I 2024-04-16 22:15:24,027] Trial 52 finished with value: 0.23857835305293892 and parameters: {'subsample': 0.9638755954753434, 'dropout_rate': 0.7442400087777848, 'n_estimators': 87, 'learning_rate': 0.010969275426782716}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.247332228082332
Fold 2 IBS: 0.2319258551104013
Fold 3 IBS: 0.2287975409775485
Fold 4 IBS: 0.24225247200363104
Fold 5 IBS: 0.22935321185325444
[I 2024-04-16 22:15:24,288] Trial 53 finished with value: 0.23593226160543343 and parameters: {'subsample': 0.831743289626897, 'dropout_rate': 0.7024060440588792, 'n_estimators': 1, 'learning_rate': 0.014323432398418696}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.26082171020192424
Fold 2 IBS: 0.22525795358709064
Fold 3 IBS: 0.21386995285116212
Fold 4 IBS: 0.27258779800053384
Fold 5 IBS: 0.22958366872628116
[I 2024-04-16 22:15:26,007] Trial 54 finished with value: 0.2404242166733984 and parameters: {'subsample': 0.9254357296962638, 'dropout_rate': 0.7815752755504023, 'n_estimators': 218, 'learning_rate': 0.005751277348586029}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.3222987276673667
Fold 2 IBS: 0.24073834849501916
Fold 3 IBS: 0.19859944168907614
Fold 4 IBS: 0.3646762624122252
Fold 5 IBS: 0.2563016840240858
[I 2024-04-16 22:15:26,835] Trial 55 finished with value: 0.2765228928575546 and parameters: {'subsample': 0.9971384391729257, 'dropout_rate': 0.7996184587932971, 'n_estimators': 110, 'learning_rate': 0.038088954016554544}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.24765573720686804
Fold 2 IBS: 0.23142780016035744
Fold 3 IBS: 0.22804034958976402
Fold 4 IBS: 0.2433630788056884
Fold 5 IBS: 0.2291914555540409
[I 2024-04-16 22:15:27,472] Trial 56 finished with value: 0.23593568426334377 and parameters: {'subsample': 0.8794913158572285, 'dropout_rate': 0.6387167841059217, 'n_estimators': 72, 'learning_rate': 0.0010043759807916914}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.25042066005931435
Fold 2 IBS: 0.2284203747058262
Fold 3 IBS: 0.22331708018419866
Fold 4 IBS: 0.2508177021691875
Fold 5 IBS: 0.22841729628977997
[I 2024-04-16 22:15:27,873] Trial 57 finished with value: 0.23627862268166133 and parameters: {'subsample': 0.5320074456160933, 'dropout_rate': 0.9453104125395029, 'n_estimators': 50, 'learning_rate': 0.009355213582474957}. Best is trial 21 with value: 0.2359272091307914.

Fold 1 IBS: 0.24890979703840563
Fold 2 IBS: 0.23003148247286287
Fold 3 IBS: 0.2254557529769063
Fold 4 IBS: 0.24728830711327457
Fold 5 IBS: 0.228782911842937
[I 2024-04-16 22:15:28,163] Trial 58 finished with value: 0.23609365028887724 and parameters: {'subsample': 0.7920490567025045, 'dropout_rate': 0.8710743587053082, 'n_estimators': 17, 'learning_rate': 0.01472286899228218}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.33137168930730976
Fold 2 IBS: 0.2439619426483204
Fold 3 IBS: 0.18985013201621057
Fold 4 IBS: 0.377785990019265
Fold 5 IBS: 0.25780738622080585
[I 2024-04-16 22:15:28,630] Trial 59 finished with value: 0.2801554280423823 and parameters: {'subsample': 0.4281699397350103, 'dropout_rate': 0.7082113893699592, 'n_estimators': 62, 'learning_rate': 0.08322655251020356}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.24823638249156682
Fold 2 IBS: 0.23073253702170793
Fold 3 IBS: 0.22695457812129097
Fold 4 IBS: 0.2451310203758235
Fold 5 IBS: 0.2289681409795339
[I 2024-04-16 22:15:28,966] Trial 60 finished with value: 0.23600453179798464 and parameters: {'subsample': 0.9718433307655755, 'dropout_rate': 0.8379883197559328, 'n_estimators': 36, 'learning_rate': 0.004513958771487467}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.24747998535714233
Fold 2 IBS: 0.23169287503041916
Fold 3 IBS: 0.22840408240521112
Fold 4 IBS: 0.24279531273679936
Fold 5 IBS: 0.22927132081617319
[I 2024-04-16 22:15:29,288] Trial 61 finished with value: 0.23592871526914902 and parameters: {'subsample': 0.9219467121753087, 'dropout_rate': 0.7442336775229345, 'n_estimators': 2, 'learning_rate': 0.0222314106018474}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.2516533154753326
Fold 2 IBS: 0.2280201963542809
Fold 3 IBS: 0.22183718712445905
Fold 4 IBS: 0.25435801909363914
Fold 5 IBS: 0.228484795915246
[I 2024-04-16 22:15:29,632] Trial 62 finished with value: 0.23687070279259154 and parameters: {'subsample': 0.9220102126141292, 'dropout_rate': 0.7439507430504526, 'n_estimators': 26, 'learning_rate': 0.0218351989628791}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.2480154982465775
Fold 2 IBS: 0.23095745796616937
Fold 3 IBS: 0.2272629259112075
Fold 4 IBS: 0.24464831560389652
Fold 5 IBS: 0.22904163208687153
[I 2024-04-16 22:15:29,916] Trial 63 finished with value: 0.23598516596294447 and parameters: {'subsample': 0.8679883843471251, 'dropout_rate': 0.8068153300526799, 'n_estimators': 15, 'learning_rate': 0.008810036009845952}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.251890878758281
Fold 2 IBS: 0.22636233553408788
Fold 3 IBS: 0.2204310201926011
Fold 4 IBS: 0.25591119156164377
Fold 5 IBS: 0.22831519060136687
[I 2024-04-16 22:15:30,341] Trial 64 finished with value: 0.2365821233295961 and parameters: {'subsample': 0.3217390836823398, 'dropout_rate': 0.9087239445600178, 'n_estimators': 42, 'learning_rate': 0.016910206787788276}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.3942698510543427
Fold 2 IBS: 0.3671978335205174
Fold 3 IBS: 0.18014133279094702
Fold 4 IBS: 0.48795697224988566
Fold 5 IBS: 0.3331473606575946
[I 2024-04-16 22:15:33,958] Trial 65 finished with value: 0.35254267005465745 and parameters: {'subsample': 0.918099364596505, 'dropout_rate': 0.7681104621573845, 'n_estimators': 360, 'learning_rate': 0.04841446942458946}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.2480488602001837
Fold 2 IBS: 0.2309416271763623
Fold 3 IBS: 0.22726442565264957
Fold 4 IBS: 0.24457859824803505
Fold 5 IBS: 0.22902338202450992
[I 2024-04-16 22:15:34,273] Trial 66 finished with value: 0.23597137866034812 and parameters: {'subsample': 0.967063619394265, 'dropout_rate': 0.6252829836444422, 'n_estimators': 12, 'learning_rate': 0.011410400390875196}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.24907933167451476
Fold 2 IBS: 0.22981233901508397
Fold 3 IBS: 0.22525295264672457
Fold 4 IBS: 0.24770914275853326
Fold 5 IBS: 0.228745602734477
[I 2024-04-16 22:15:34,795] Trial 67 finished with value: 0.23611987376586674 and parameters: {'subsample': 0.8377468058476737, 'dropout_rate': 0.7132901986763938, 'n_estimators': 65, 'learning_rate': 0.004350071699797672}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.3115593282835552
Fold 2 IBS: 0.2359811546845628
Fold 3 IBS: 0.19342365314035753
Fold 4 IBS: 0.35102567177097066
Fold 5 IBS: 0.2507003214553554
[I 2024-04-16 22:15:40,164] Trial 68 finished with value: 0.26853802586696035 and parameters: {'subsample': 0.9395446775759925, 'dropout_rate': 0.6803941026047632, 'n_estimators': 496, 'learning_rate': 0.007498146974592643}. Best is trial 21 with value: 0.2359272091307914.
Fold 1 IBS: 0.2473830926808694
Fold 2 IBS: 0.23181906183863246
Fold 3 IBS: 0.22862248679285974
Fold 4 IBS: 0.24245879300516687
Fold 5 IBS: 0.22932020273388978
[I 2024-04-16 22:15:40,420] Trial 69 finished with value: 0.2359207274102837 and parameters: {'subsample': 0.8944558508371752, 'dropout_rate': 0.754611445258178, 'n_estimators': 1, 'learning_rate': 0.026494394293458994}. Best is trial 69 with value: 0.2359207274102837.
Fold 1 IBS: 0.24771873615260478
Fold 2 IBS: 0.23158532743643828
Fold 3 IBS: 0.22806738754795428
Fold 4 IBS: 0.2434907453616817
Fold 5 IBS: 0.229195229501413
[I 2024-04-16 22:15:40,675] Trial 70 finished with value: 0.2360114852000184 and parameters: {'subsample': 0.7309856177946487, 'dropout_rate': 0.5593303159720544, 'n_estimators': 2, 'learning_rate': 0.03810779967203804}. Best is trial 69 with value: 0.2359207274102837.
Fold 1 IBS: 0.25555776214253473
Fold 2 IBS: 0.22629866180196662
Fold 3 IBS: 0.21787398789585175
Fold 4 IBS: 0.2632708079843249
Fold 5 IBS: 0.2287081430009015
[I 2024-04-16 22:15:41,040] Trial 71 finished with value: 0.2383418725651159 and parameters: {'subsample': 0.8815537118834056, 'dropout_rate': 0.7571905087825083, 'n_estimators': 34, 'learning_rate': 0.026987527393880818}. Best is trial 69 with value: 0.2359207274102837.
Fold 1 IBS: 0.250095979955006
Fold 2 IBS: 0.22899691652200493
Fold 3 IBS: 0.2239563763710396
Fold 4 IBS: 0.2505352085732147
Fold 5 IBS: 0.22858229328317947
[I 2024-04-16 22:15:41,390] Trial 72 finished with value: 0.23643335494088893 and parameters: {'subsample': 0.9045396157935386, 'dropout_rate': 0.7906385325177884, 'n_estimators': 20, 'learning_rate': 0.020142719543277086}. Best is trial 69 with value: 0.2359207274102837.
Fold 1 IBS: 0.24802715860476793
Fold 2 IBS: 0.23096380934876853
Fold 3 IBS: 0.22720523606425916
Fold 4 IBS: 0.24458780078029957
Fold 5 IBS: 0.22905530461372028
[I 2024-04-16 22:15:41,904] Trial 73 finished with value: 0.23596786188236307 and parameters: {'subsample': 0.7876014997340792, 'dropout_rate': 0.8383902437515699, 'n_estimators': 48, 'learning_rate': 0.002724281395905027}. Best is trial 69 with value: 0.2359207274102837.
Fold 1 IBS: 0.24838804049322588
Fold 2 IBS: 0.2305680348725696
Fold 3 IBS: 0.22667121549019278
Fold 4 IBS: 0.24550439607895388
Fold 5 IBS: 0.22892202214791454
[I 2024-04-16 22:15:42,278] Trial 74 finished with value: 0.23601074181657133 and parameters: {'subsample': 0.9658358514236638, 'dropout_rate': 0.6889228996077285, 'n_estimators': 15, 'learning_rate': 0.012262039263061152}. Best is trial 69 with value: 0.2359207274102837.
Fold 1 IBS: 0.25171899180425944
Fold 2 IBS: 0.22794769174780607
Fold 3 IBS: 0.22175497700649716
Fold 4 IBS: 0.2546962163485046
Fold 5 IBS: 0.2284831620144433
[I 2024-04-16 22:15:42,930] Trial 75 finished with value: 0.23692020778430214 and parameters: {'subsample': 0.8556216572443887, 'dropout_rate': 0.7466562588811925, 'n_estimators': 34, 'learning_rate': 0.017033882978020977}. Best is trial 69 with value: 0.2359207274102837.
Fold 1 IBS: 0.2792182111680425
Fold 2 IBS: 0.22586171070398273
Fold 3 IBS: 0.2041568565766499
Fold 4 IBS: 0.3034645749130366
Fold 5 IBS: 0.23513645546226355
[I 2024-04-16 22:15:43,886] Trial 76 finished with value: 0.24956756176479505 and parameters: {'subsample': 0.9367534757461361, 'dropout_rate': 0.7264897726493132, 'n_estimators': 93, 'learning_rate': 0.024215001255400232}. Best is trial 69 with value: 0.2359207274102837.
Fold 1 IBS: 0.27977739226628423
Fold 2 IBS: 0.22591071369134033
Fold 3 IBS: 0.2027250132662109

Fold 4 IBS: 0.3039939279331561
Fold 5 IBS: 0.23528769396515306
[I 2024-04-16 22:15:44,494] Trial 77 finished with value: 0.24953894822442893 and parameters: {'subsample': 0.8256210781433221, 'dropout_rate': 0.77514909005388, 'n_estimators': 74, 'learning_rate': 0.03072890021688105}. Best is trial 69 with value: 0.2359207274102837.
Fold 1 IBS: 0.3138835900465689
Fold 2 IBS: 0.23776002911750155
Fold 3 IBS: 0.19108475850581674
Fold 4 IBS: 0.3571181386469282
Fold 5 IBS: 0.25096187498366274
[I 2024-04-16 22:15:44,986] Trial 78 finished with value: 0.27016167826009563 and parameters: {'subsample': 0.8981621675854204, 'dropout_rate': 0.8182308606189214, 'n_estimators': 57, 'learning_rate': 0.06751738229506911}. Best is trial 69 with value: 0.2359207274102837.
Fold 1 IBS: 0.249960989092115
Fold 2 IBS: 0.22940983791440717
Fold 3 IBS: 0.22444822802920752
Fold 4 IBS: 0.25088958787309706
Fold 5 IBS: 0.2285465576559458
[I 2024-04-16 22:15:45,278] Trial 79 finished with value: 0.2366510401129545 and parameters: {'subsample': 0.6745068465882641, 'dropout_rate': 0.860727621197715, 'n_estimators': 11, 'learning_rate': 0.03515641095110257}. Best is trial 69 with value: 0.2359207274102837.
Fold 1 IBS: 0.24860337022854506
Fold 2 IBS: 0.23028422231568585
Fold 3 IBS: 0.22631578633559146
Fold 4 IBS: 0.24622815099566892
Fold 5 IBS: 0.2288611077353568
[I 2024-04-16 22:15:45,705] Trial 80 finished with value: 0.23605852752216966 and parameters: {'subsample': 0.9833248278795096, 'dropout_rate': 0.1835064275776629, 'n_estimators': 28, 'learning_rate': 0.007735106695369032}. Best is trial 69 with value: 0.2359207274102837.
Fold 1 IBS: 0.24736026978999584
Fold 2 IBS: 0.23184639265138315
Fold 3 IBS: 0.2286859106370892
Fold 4 IBS: 0.24237596007629028
Fold 5 IBS: 0.22933229573742708
[I 2024-04-16 22:15:45,969] Trial 81 finished with value: 0.2359201657784371 and parameters: {'subsample': 0.9544791688081666, 'dropout_rate': 0.7120491271209716, 'n_estimators': 1, 'learning_rate': 0.022969066082900873}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.2509700722212056
Fold 2 IBS: 0.22836066071589461
Fold 3 IBS: 0.2226487313509488
Fold 4 IBS: 0.2524814778737083
Fold 5 IBS: 0.22850315975129426
[I 2024-04-16 22:15:46,341] Trial 82 finished with value: 0.23659282038261034 and parameters: {'subsample': 0.9506713846430276, 'dropout_rate': 0.6660882139686143, 'n_estimators': 18, 'learning_rate': 0.02810584753044926}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.24726724583479692
Fold 2 IBS: 0.23201005186493776
Fold 3 IBS: 0.22892568615997433
Fold 4 IBS: 0.24204483455049638
Fold 5 IBS: 0.22938487072354985
[I 2024-04-16 22:15:46,591] Trial 83 finished with value: 0.23592653782675105 and parameters: {'subsample': 0.9194729875570777, 'dropout_rate': 0.7098129025634485, 'n_estimators': 1, 'learning_rate': 0.003958837155181948}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.24731953103552093
Fold 2 IBS: 0.23192680460378332
Fold 3 IBS: 0.22880945610376766
Fold 4 IBS: 0.24222782092604245
Fold 5 IBS: 0.22935620743119
[I 2024-04-16 22:15:46,850] Trial 84 finished with value: 0.2359279640200609 and parameters: {'subsample': 0.9953537914900923, 'dropout_rate': 0.7113205076563949, 'n_estimators': 3, 'learning_rate': 0.004440014717491184}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.24850061927486702
Fold 2 IBS: 0.23043708430870938
Fold 3 IBS: 0.22645950076036056
Fold 4 IBS: 0.24589660335873167
Fold 5 IBS: 0.22889009012420214
[I 2024-04-16 22:15:47,271] Trial 85 finished with value: 0.2360367795653741 and parameters: {'subsample': 0.9735802673152494, 'dropout_rate': 0.6426642446975073, 'n_estimators': 40, 'learning_rate': 0.004990375370958196}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.24726445481877438
Fold 2 IBS: 0.23201259158776885
Fold 3 IBS: 0.22894117840231995
Fold 4 IBS: 0.24203615705028877
Fold 5 IBS: 0.22938577381434963
[I 2024-04-16 22:15:47,557] Trial 86 finished with value: 0.23592803113470034 and parameters: {'subsample': 0.9957940338845829, 'dropout_rate': 0.6033368189919828, 'n_estimators': 1, 'learning_rate': 0.003319587302630657}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.24778285863343114
Fold 2 IBS: 0.23127273303200627
Fold 3 IBS: 0.22778025236285143
Fold 4 IBS: 0.24379882858993818
Fold 5 IBS: 0.22913558560097927
[I 2024-04-16 22:15:47,946] Trial 87 finished with value: 0.23595405164384128 and parameters: {'subsample': 0.9210530112691739, 'dropout_rate': 0.512450511852123, 'n_estimators': 29, 'learning_rate': 0.0032098742559250114}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.24839952812198152
Fold 2 IBS: 0.2305404963729431
Fold 3 IBS: 0.22673416768877314
Fold 4 IBS: 0.24553309698742895
Fold 5 IBS: 0.22892975082920244
[I 2024-04-16 22:15:48,385] Trial 88 finished with value: 0.23602740800006586 and parameters: {'subsample': 0.998829845773968, 'dropout_rate': 0.6053797561125808, 'n_estimators': 14, 'learning_rate': 0.013073327596389534}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.24725288004680054
Fold 2 IBS: 0.23203026105386798
Fold 3 IBS: 0.2289662688103081
Fold 4 IBS: 0.24199558542293476
Fold 5 IBS: 0.229392263974653
[I 2024-04-16 22:15:48,661] Trial 89 finished with value: 0.23592745186171288 and parameters: {'subsample': 0.899334157822306, 'dropout_rate': 0.5889020930052754, 'n_estimators': 1, 'learning_rate': 0.001146859226016428}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.2508004969857934
Fold 2 IBS: 0.22845907532244744
Fold 3 IBS: 0.2227500662309853
Fold 4 IBS: 0.2524518528044778
Fold 5 IBS: 0.228520804218065
[I 2024-04-16 22:15:49,863] Trial 90 finished with value: 0.23659645911235377 and parameters: {'subsample': 0.8659980910125572, 'dropout_rate': 0.5811262697265472, 'n_estimators': 50, 'learning_rate': 0.009767049593234042}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.24726406436062282
Fold 2 IBS: 0.23201170043213162
Fold 3 IBS: 0.22893616694549437
Fold 4 IBS: 0.24203580000856684
Fold 5 IBS: 0.22938585432389982
[I 2024-04-16 22:15:50,241] Trial 91 finished with value: 0.2359267172141431 and parameters: {'subsample': 0.8961006358184125, 'dropout_rate': 0.5362975603556047, 'n_estimators': 1, 'learning_rate': 0.003360755166622248}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.24763091072640178
Fold 2 IBS: 0.2314599162741914
Fold 3 IBS: 0.22806748237215507
Fold 4 IBS: 0.2432641806833199
Fold 5 IBS: 0.22919668347590286
[I 2024-04-16 22:15:50,970] Trial 92 finished with value: 0.2359238347063942 and parameters: {'subsample': 0.9547117904885637, 'dropout_rate': 0.46637559832227504, 'n_estimators': 24, 'learning_rate': 0.0028915695338975964}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.24765163197436424
Fold 2 IBS: 0.23144709050935344
Fold 3 IBS: 0.22804617854721648
Fold 4 IBS: 0.2432666684426549
Fold 5 IBS: 0.22919179712537452
[I 2024-04-16 22:15:51,261] Trial 93 finished with value: 0.23592067331979266 and parameters: {'subsample': 0.8916382375588622, 'dropout_rate': 0.46270111845563794, 'n_estimators': 11, 'learning_rate': 0.006283217722429004}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.24775900981585303
Fold 2 IBS: 0.23129599497153672
Fold 3 IBS: 0.22780977268552796
Fold 4 IBS: 0.24363825268138375
Fold 5 IBS: 0.22914118136483191
[I 2024-04-16 22:15:51,764] Trial 94 finished with value: 0.23592884230382666 and parameters: {'subsample': 0.885886002070849, 'dropout_rate': 0.45200009769171257, 'n_estimators': 12, 'learning_rate': 0.0072844897519780336}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.24813029933258937
Fold 2 IBS: 0.23080086528360846
Fold 3 IBS: 0.22700933995251713
Fold 4 IBS: 0.2448677448488557
Fold 5 IBS: 0.22899390133825895
[I 2024-04-16 22:15:52,145] Trial 95 finished with value: 0.2359604301511659 and parameters: {'subsample': 0.9040844279184398, 'dropout_rate': 0.40811021526149244, 'n_estimators': 37, 'learning_rate': 0.004060978222353054}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.2481687981830829
Fold 2 IBS: 0.23081072069679692
Fold 3 IBS: 0.22708171874116564
Fold 4 IBS: 0.244863831566896
Fold 5 IBS: 0.22899349198549604
[I 2024-04-16 22:15:52,491] Trial 96 finished with value: 0.2359837122346875 and parameters: {'subsample': 0.9806654498140575, 'dropout_rate': 0.5018880010898161, 'n_estimators': 23, 'learning_rate': 0.006562006449300262}. Best is trial 81 with value: 0.2359201657784371.

Fold 1 IBS: 0.24741169763879048
Fold 2 IBS: 0.2317895664300078
Fold 3 IBS: 0.22858459606339743
Fold 4 IBS: 0.24255845922196848
Fold 5 IBS: 0.2293051926134131
[I 2024-04-16 22:15:52,792] Trial 97 finished with value: 0.23592990239351544 and parameters: {'subsample': 0.93525187912044, 'dropout_rate': 0.5247006975414128, 'n_estimators': 9, 'learning_rate': 0.003396199225455108}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.24730327400164734
Fold 2 IBS: 0.23196284948715093
Fold 3 IBS: 0.22885037550107723
Fold 4 IBS: 0.24215795642981985
Fold 5 IBS: 0.2293664065113921
[I 2024-04-16 22:15:53,089] Trial 98 finished with value: 0.2359281723862175 and parameters: {'subsample': 0.8443630472097454, 'dropout_rate': 0.45029073287468846, 'n_estimators': 1, 'learning_rate': 0.009810701317067457}. Best is trial 81 with value: 0.2359201657784371.
Fold 1 IBS: 0.24760599763754257
Fold 2 IBS: 0.23149495327850178
Fold 3 IBS: 0.2282010641579017
Fold 4 IBS: 0.2431802635319715
Fold 5 IBS: 0.2292134697986741
[I 2024-04-16 22:15:53,572] Trial 99 finished with value: 0.2359391496809183 and parameters: {'subsample': 0.9997542955937178, 'dropout_rate': 0.37837909129557906, 'n_estimators': 45, 'learning_rate': 0.0014176791028688229}. Best is trial 81 with value: 0.2359201657784371.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.2359201657784371], datetime_start=datetime.datetime(2024, 4, 16, 22, 15, 45, 711222), datetime_complete=datetime.datetime(2024, 4, 16, 22, 15, 45, 968893), params={'subsample': 0.9544791688081666, 'dropout_rate': 0.7120491271209716, 'n_estimators': 1, 'learning_rate': 0.022969066082900873}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=81, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.9544791688081666, 'dropout_rate': 0.7120491271209716, 'n_estimators': 1, 'learning_rate': 0.022969066082900873}


* Best Score for IBS:
 0.2359201657784371

In [114]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [115]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.602
train_ibs:  0.236

#### Test

In [116]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [117]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.3678471747462695,
                                              learning_rate=0.039763754907327475,
                                              n_estimators=349,
                                              random_state=123,
                                              subsample=0.14305853399792298)

C-index score: 0.567

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.7120491271209716,
                                              learning_rate=0.022969066082900873,
                                              n_estimators=1, random_state=123,
                                              subsample=0.9544791688081666)

IBS: 0.229

In [118]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [119]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.815   1.0
ExtraSurvivalTrees               0.728   2.0
ComponentwiseGradientBoosting    0.602   3.0
CoxLasso                         0.594   4.5
CoxElastic                       0.594   4.5
CoxRidge                         0.585   6.0
CoxPH                            0.580   7.0
GradientBoosting                 0.553   8.0

In [120]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.233   1.0
CoxElastic                     0.235   2.0
CoxRidge                       0.236   4.5
Randomsurvivalforest           0.236   4.5
GradientBoosting               0.236   4.5
ComponentwiseGradientBoosting  0.236   4.5
CoxPH                          0.250   7.0
CoxLasso                       0.257   8.0

In [121]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ExtraSurvivalTrees               0.590   1.0
GradientBoosting                 0.573   2.0
CoxRidge                         0.569   3.0
CoxElastic                       0.568   4.0
ComponentwiseGradientBoosting    0.567   5.0
Randomsurvivalforest             0.562   6.0
CoxPH                            0.553   7.5
CoxLasso                         0.553   7.5

In [122]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
CoxElastic                     0.227   1.0
ExtraSurvivalTrees             0.228   2.0
CoxRidge                       0.229   4.0
GradientBoosting               0.229   4.0
ComponentwiseGradientBoosting  0.229   4.0
Randomsurvivalforest           0.230   6.0
CoxPH                          0.246   7.5
CoxLasso                       0.246   7.5

In [123]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/dfs/yeojohnson/plsr/'  # Folder path where you want to save the files

# Modify the file names to match the desired format
modified_file_names = ['d3_dfs_yeojohnson_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [124]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-16