In [26]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import PowerTransformer

In [27]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [28]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [29]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [30]:
# Check null values in D3 
clinical_train.isnull().sum().sum()

0

### COX assumption in Train data

In [31]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic    p  -log2(p)
LBP_003_CT                                                       0.01 0.91      0.13
LBP_003_PET                                                      0.00 0.98      0.03
LBP_012_CT                                                       0.00 0.95      0.08
LBP_012_PET                                                      0.00 0.97      0.04
LBP_021_CT                                                       0.00 0.97      0.05
LBP_021_PET                                                      0.01 0.92      0.12
LBP_030_CT                                                       0.00 0.99      0.02
LBP_030_PET                                                      0.00 0.99      0.01
LBP_102_CT                                                       0.00 0.99      0.02
LBP_102_PET                                                      0.01 0.94      0.09
LBP_111_CT                                                       0.01 0.94      0.09
LBP_111_PET                                                      0.02 0.90      0.16
LBP_120_CT                                                       0.01 0.93      0.10
LBP_120_PET                                                      0.00 0.97      0.05
LBP_201_CT                                                       0.01 0.94      0.09
LBP_201_PET                                                      0.00 0.99      0.01
LBP_210_CT                                                       0.00 0.98      0.03
LBP_210_PET                                                      0.00 0.97      0.05
LBP_300_CT                                                       0.00 0.98      0.03
LBP_300_PET                                                      0.00 0.98      0.02
MTV                                                              0.00 1.00      0.00
SUVpeak                                                          0.00 1.00      0.00
TLG                                                              0.00 1.00      0.00
age                                                              0.00 0.98      0.03
cavum_oris                                                       0.00 0.97      0.05
charlson                                                         0.00 0.95      0.08
female                                                           0.00 1.00      0.00
first_order_10Percentile_CT                                      0.00 0.97      0.05
first_order_10Percentile_PET                                     0.00 1.00      0.00
first_order_90Percentile_CT                                      0.00 0.96      0.05
first_order_90Percentile_PET                                     0.00 1.00      0.00
first_order_Energy_CT                                            0.00 1.00      0.01
first_order_Energy_PET                                           0.00 0.99      0.02
first_order_Entropy_CT_b20                                       0.00 0.99      0.02
first_order_Entropy_CT_c16                                       0.00 0.99      0.02
first_order_Entropy_PET_b2                                       0.00 1.00      0.01
first_order_Entropy_PET_c04                                      0.00 0.99      0.02
first_order_InterquartileRange_CT                                0.00 0.98      0.03
first_order_InterquartileRange_PET                               0.00 1.00      0.00
first_order_Kurtosis_CT                                          0.00 0.98      0.02
first_order_Kurtosis_PET                                         0.00 0.99      0.02
first_order_Maximum_CT                                           0.01 0.94      0.09
first_order_Maximum_PET                                          0.00 0.99      0.02
first_order_MeanAbsoluteDeviation_CT                             0.00 0.99      0.01
first_order_MeanAbsoluteDeviation_PET                            0.00 1.00      0.00
first_order_Mean_CT                                              0.00 1.00      0.01
first_order_Mean_PET                                             0.00 1.00      0.00
first_order_Median_CT                                            0.00 0.99      0.01
first_order_Median_PET                                           0.00 0.99      0.01
first_order_Minimum_CT                                           0.00 0.99      0.01
first_order_Minimum_PET                                          0.01 0.93      0.11
first_order_Range_CT                                             0.00 0.96      0.06
first_order_Range_PET                                            0.00 0.99      0.01
first_order_RobustMeanAbsoluteDeviation_CT                       0.00 0.96      0.07
first_order_RobustMeanAbsoluteDeviation_PET                      0.00 0.99      0.01
first_order_RootMeanSquared_CT                                   0.00 0.99      0.01
first_order_RootMeanSquared_PET                                  0.00 1.00      0.00
first_order_Skewness_CT                                          0.03 0.85      0.23
first_order_Skewness_PET                                         0.00 0.97      0.04
first_order_TotalEnergy_CT                                       0.00 1.00      0.01
first_order_TotalEnergy_PET                                      0.00 0.99      0.02
first_order_Uniformity_CT_b20                                    0.00 0.97      0.04
first_order_Uniformity_CT_c16                                    0.00 0.99      0.02
first_order_Uniformity_PET_b2                                    0.00 0.99      0.01
first_order_Uniformity_PET_c04                                   0.00 0.99      0.01
first_order_Variance_CT                                          0.00 0.99      0.02
first_order_Variance_PET                                         0.00 1.00      0.01
glcm_Autocorrelation_d_1_CT_b20                                  0.00 1.00      0.00
glcm_Autocorrelation_d_1_CT_c16                                  0.00 1.00      0.00
glcm_Autocorrelation_d_1_PET_b2                                  0.00 1.00      0.00
glcm_Autocorrelation_d_1_PET_c04                                 0.00 1.00      0.00
glcm_ClusterProminence_d_1_CT_b20                                0.00 1.00      0.00
glcm_ClusterProminence_d_1_CT_c16                                0.00 0.95      0.07
glcm_ClusterProminence_d_1_PET_b2                                0.00 1.00      0.00
glcm_ClusterProminence_d_1_PET_c04                               0.00 0.98      0.03
glcm_ClusterShade_d_1_CT_b20                                     0.00 0.94      0.08
glcm_ClusterShade_d_1_CT_c16                                     0.00 0.94      0.08
glcm_ClusterShade_d_1_PET_b2                                     0.00 0.97      0.04
glcm_ClusterShade_d_1_PET_c04                                    0.01 0.93      0.10
glcm_ClusterTendency_d_1_CT_b20                                  0.00 0.99      0.01
glcm_ClusterTendency_d_1_CT_c16                                  0.00 0.98      0.03
glcm_ClusterTendency_d_1_PET_b2                                  0.00 0.99      0.01
glcm_ClusterTendency_d_1_PET_c04                                 0.00 0.98      0.02
glcm_Contrast_d_1_CT_b20                                         0.00 0.99      0.02
glcm_Contrast_d_1_CT_c16                                         0.00 0.98      0.02
glcm_Contrast_d_1_PET_b2                                         0.00 1.00      0.00
glcm_Contrast_d_1_PET_c04                                        0.00 0.99      0.01
glcm_Correlation_d_1_CT_b20                                      0.00 0.97      0.05
glcm_Correlation_d_1_CT_c16                                      0.01 0.93      0.10
glcm_Correlation_d_1_PET_b2                                      0.00 0.99      0.01
glcm_Correlation_d_1_PET_c04                                     0.00 0.97      0.05
glcm_DifferenceAverage_d_1_CT_b20                                0.00 1.00      0.00
glcm_DifferenceAverage_d_1_CT_c16                                0.00 0.99      0.02
glcm_DifferenceAverage_d_1_PET_b2                                0.00 0.99      0.01
glcm_DifferenceAverage_d_1_PET_c04                               0.00 1.00      0.00
glcm_DifferenceEntropy_d_1_CT_b20                                0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_CT_c16                                0.00 0.99      0.02
glcm_DifferenceEntropy_d_1_PET_b2                                0.00 1.00      0.00
glcm_DifferenceEntropy_d_1_PET_c04                               0.00 0.99      0.01
glcm_DifferenceVariance_d_1_CT_b20                               0.00 0.99      0.02
glcm_DifferenceVariance_d_1_CT_c16                               0.00 0.97      0.04
glcm_DifferenceVariance_d_1_PET_b2                               0.00 1.00      0.00
glcm_DifferenceVariance_d_1_PET_c04                              0.00 1.00      0.01
glcm_Id_d_1_CT_b20                                               0.00 1.00      0.00
glcm_Id_d_1_CT_c16                                               0.00 0.99      0.02
glcm_Id_d_1_PET_b2                                               0.00 0.99      0.02
glcm_Id_d_1_PET_c04                                              0.00 1.00      0.00
glcm_Idm_d_1_CT_b20                                              0.00 1.00      0.00
glcm_Idm_d_1_CT_c16                                              0.00 0.99      0.02
glcm_Idm_d_1_PET_b2                                              0.00 0.99      0.01
glcm_Idm_d_1_PET_c04                                             0.00 1.00      0.00
glcm_Idmn_d_1_CT_b20                                             0.00 0.99      0.02
glcm_Idmn_d_1_CT_c16                                             0.00 0.99      0.02
glcm_Idmn_d_1_PET_b2                                             0.00 0.95      0.08
glcm_Idmn_d_1_PET_c04                                            0.00 0.99      0.01
glcm_Idn_d_1_CT_b20                                              0.00 1.00      0.00
glcm_Idn_d_1_CT_c16                                              0.00 0.99      0.02
glcm_Idn_d_1_PET_b2                                              0.00 0.98      0.03
glcm_Idn_d_1_PET_c04                                             0.00 1.00      0.00
glcm_Imc1_d_1_CT_b20                                             0.00 0.99      0.02
glcm_Imc1_d_1_CT_c16                                             0.00 0.99      0.01
glcm_Imc1_d_1_PET_b2                                             0.00 0.96      0.06
glcm_Imc1_d_1_PET_c04                                            0.00 1.00      0.01
glcm_Imc2_d_1_CT_b20                                             0.00 0.96      0.05
glcm_Imc2_d_1_CT_c16                                             0.00 0.97      0.05
glcm_Imc2_d_1_PET_b2                                             0.00 0.98      0.02
glcm_Imc2_d_1_PET_c04                                            0.00 0.97      0.04
glcm_InverseVariance_d_1_CT_b20                                  0.00 0.99      0.01
glcm_InverseVariance_d_1_CT_c16                                  0.00 0.98      0.03
glcm_InverseVariance_d_1_PET_b2                                  0.00 0.98      0.03
glcm_InverseVariance_d_1_PET_c04                                 0.00 1.00      0.01
glcm_JointAverage_d_1_CT_b20                                     0.00 0.99      0.01
glcm_JointAverage_d_1_CT_c16                                     0.00 0.99      0.01
glcm_JointAverage_d_1_PET_b2                                     0.00 0.99      0.01
glcm_JointAverage_d_1_PET_c04                                    0.00 1.00      0.00
glcm_JointEnergy_d_1_CT_b20                                      0.00 1.00      0.01
glcm_JointEnergy_d_1_CT_c16                                      0.00 1.00      0.01
glcm_JointEnergy_d_1_PET_b2                                      0.00 1.00      0.00
glcm_JointEnergy_d_1_PET_c04                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_CT_b20                                     0.00 0.99      0.02
glcm_JointEntropy_d_1_CT_c16                                     0.00 0.98      0.02
glcm_JointEntropy_d_1_PET_b2                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_PET_c04                                    0.00 1.00      0.00
glcm_MCC_d_1_CT_b20                                              0.01 0.93      0.10
glcm_MCC_d_1_CT_c16                                              0.00 0.99      0.02
glcm_MCC_d_1_PET_b2                                              0.00 0.97      0.05
glcm_MCC_d_1_PET_c04                                             0.00 0.99      0.01
glcm_MaximumProbability_d_1_CT_b20                               0.01 0.94      0.09
glcm_MaximumProbability_d_1_CT_c16                               0.00 0.99      0.01
glcm_MaximumProbability_d_1_PET_b2                               0.02 0.89      0.16
glcm_MaximumProbability_d_1_PET_c04                              0.00 0.98      0.02
glcm_SumAverage_d_1_CT_b20                                       0.00 0.99      0.01
glcm_SumAverage_d_1_CT_c16                                       0.00 0.99      0.01
glcm_SumAverage_d_1_PET_b2                                       0.00 0.99      0.01
glcm_SumAverage_d_1_PET_c04                                      0.00 1.00      0.00
glcm_SumEntropy_d_1_CT_b20                                       0.00 0.98      0.02
glcm_SumEntropy_d_1_CT_c16                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_PET_b2                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_PET_c04                                      0.00 0.99      0.01
glcm_SumSquares_d_1_CT_b20                                       0.00 0.99      0.01
glcm_SumSquares_d_1_CT_c16                                       0.00 0.99      0.02
glcm_SumSquares_d_1_PET_b2                                       0.00 0.99      0.01
glcm_SumSquares_d_1_PET_c04                                      0.00 0.98      0.02
gldm_DependenceEntropy_d_1_CT_b20                                0.00 0.96      0.06
gldm_DependenceEntropy_d_1_CT_c16                                0.00 0.98      0.03
gldm_DependenceEntropy_d_1_PET_b2                                0.00 0.98      0.03
gldm_DependenceEntropy_d_1_PET_c04                               0.00 0.96      0.05
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.00 0.97      0.05
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00 1.00      0.00
gldm_DependenceNonUniformity_d_1_CT_c16                          0.00 0.98      0.02
gldm_DependenceNonUniformity_d_1_PET_b2                          0.00 1.00      0.00
gldm_DependenceNonUniformity_d_1_PET_c04                         0.00 1.00      0.01
gldm_DependenceVariance_d_1_CT_b20                               0.00 0.99      0.01
gldm_DependenceVariance_d_1_CT_c16                               0.01 0.93      0.11
gldm_DependenceVariance_d_1_PET_b2                               0.00 0.96      0.05
gldm_DependenceVariance_d_1_PET_c04                              0.00 0.97      0.04
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.00 0.99      0.01
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.00 0.98      0.03
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.00 1.00      0.00
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00 1.00      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00 0.99      0.02
gldm_GrayLevelVariance_d_1_CT_c16                                0.00 0.97      0.05
gldm_GrayLevelVariance_d_1_PET_b2                                0.00 0.99      0.01
gldm_GrayLevelVariance_d_1_PET_c04                               0.00 1.00      0.01
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.00 1.00      0.01
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00 1.00      0.00
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00 1.00      0.00
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00 1.00      0.00
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.00 0.99      0.02
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.00 0.99      0.02
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.00 0.98      0.02
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00 1.00      0.00
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.99      0.02
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 1.00      0.01
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 1.00      0.00
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 1.00      0.00
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 1.00      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.96      0.06
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.99      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.00 0.99      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00 0.98      0.02
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.00 0.98      0.04
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.00 0.99      0.02
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00 0.99      0.02
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.00 0.98      0.02
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00 0.99      0.01
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.97      0.05
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.96      0.07
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 0.96      0.05
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.98      0.03
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.98      0.02
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 1.00      0.00
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.95      0.07
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.01 0.94      0.10
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.01 0.93      0.11
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.00 0.99      0.02
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00 0.98      0.02
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.00 0.99      0.01
glrlm_GrayLevelNonUniformity_CT_b20                              0.00 1.00      0.00
glrlm_GrayLevelNonUniformity_CT_c16                              0.00 0.99      0.01
glrlm_GrayLevelNonUniformity_PET_b2                              0.00 0.99      0.01
glrlm_GrayLevelNonUniformity_PET_c04                             0.00 0.98      0.03
glrlm_GrayLevelVariance_CT_b20                                   0.00 1.00      0.00
glrlm_GrayLevelVariance_CT_c16                                   0.00 1.00      0.00
glrlm_GrayLevelVariance_PET_b2                                   0.00 0.99      0.02

In [32]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index([], dtype='object')

In [33]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic      p  -log2(p)
LBP_003_CT                                                       0.06   0.81      0.31
LBP_003_PET                                                      0.76   0.38      1.38
LBP_012_CT                                                       0.13   0.72      0.48
LBP_012_PET                                                      0.27   0.60      0.73
LBP_021_CT                                                       0.56   0.45      1.14
LBP_021_PET                                                      0.00   0.97      0.04
LBP_030_CT                                                       0.04   0.83      0.26
LBP_030_PET                                                      0.06   0.81      0.30
LBP_102_CT                                                       0.00   1.00      0.00
LBP_102_PET                                                      0.02   0.90      0.15
LBP_111_CT                                                       0.14   0.71      0.49
LBP_111_PET                                                      0.51   0.47      1.08
LBP_120_CT                                                       0.51   0.47      1.08
LBP_120_PET                                                      0.14   0.71      0.50
LBP_201_CT                                                       0.27   0.61      0.72
LBP_201_PET                                                      0.70   0.40      1.31
LBP_210_CT                                                       1.25   0.26      1.92
LBP_210_PET                                                      0.00   1.00      0.00
LBP_300_CT                                                       0.01   0.91      0.14
LBP_300_PET                                                      0.01   0.93      0.10
MTV                                                              0.03   0.86      0.22
SUVpeak                                                          0.00   0.99      0.02
TLG                                                              0.13   0.72      0.48
age                                                              0.14   0.71      0.50
cavum_oris                                                       0.64   0.42      1.24
charlson                                                         7.69   0.01      7.49
female                                                           0.44   0.51      0.98
first_order_10Percentile_CT                                      0.00   0.98      0.03
first_order_10Percentile_PET                                     0.07   0.78      0.35
first_order_90Percentile_CT                                      2.21   0.14      2.87
first_order_90Percentile_PET                                     0.00   0.95      0.07
first_order_Energy_CT                                            0.01   0.94      0.09
first_order_Energy_PET                                           0.19   0.66      0.59
first_order_Entropy_CT_b20                                       0.00   0.96      0.05
first_order_Entropy_CT_c16                                       0.07   0.79      0.34
first_order_Entropy_PET_b2                                       0.00   0.98      0.04
first_order_Entropy_PET_c04                                      0.00   0.98      0.03
first_order_InterquartileRange_CT                                0.48   0.49      1.04
first_order_InterquartileRange_PET                               0.00   0.99      0.02
first_order_Kurtosis_CT                                          0.57   0.45      1.15
first_order_Kurtosis_PET                                         0.00   0.99      0.02
first_order_Maximum_CT                                           0.15   0.70      0.52
first_order_Maximum_PET                                          0.00   0.96      0.06
first_order_MeanAbsoluteDeviation_CT                             0.04   0.83      0.26
first_order_MeanAbsoluteDeviation_PET                            0.01   0.94      0.08
first_order_Mean_CT                                              0.00   0.98      0.03
first_order_Mean_PET                                             0.00   0.96      0.05
first_order_Median_CT                                            0.26   0.61      0.71
first_order_Median_PET                                           0.00   0.98      0.03
first_order_Minimum_CT                                           0.05   0.83      0.27
first_order_Minimum_PET                                          0.49   0.48      1.05
first_order_Range_CT                                             0.17   0.68      0.56
first_order_Range_PET                                            0.00   1.00      0.01
first_order_RobustMeanAbsoluteDeviation_CT                       0.05   0.82      0.29
first_order_RobustMeanAbsoluteDeviation_PET                      0.00   0.95      0.08
first_order_RootMeanSquared_CT                                   0.00   0.96      0.06
first_order_RootMeanSquared_PET                                  0.00   0.99      0.02
first_order_Skewness_CT                                          0.37   0.54      0.88
first_order_Skewness_PET                                         0.08   0.78      0.37
first_order_TotalEnergy_CT                                       0.01   0.94      0.09
first_order_TotalEnergy_PET                                      0.19   0.66      0.59
first_order_Uniformity_CT_b20                                    0.00   0.96      0.07
first_order_Uniformity_CT_c16                                    0.01   0.92      0.12
first_order_Uniformity_PET_b2                                    0.12   0.73      0.45
first_order_Uniformity_PET_c04                                   0.01   0.94      0.10
first_order_Variance_CT                                          0.00   1.00      0.00
first_order_Variance_PET                                         0.00   0.99      0.02
glcm_Autocorrelation_d_1_CT_b20                                  0.15   0.70      0.51
glcm_Autocorrelation_d_1_CT_c16                                  0.01   0.91      0.14
glcm_Autocorrelation_d_1_PET_b2                                  0.00   0.98      0.03
glcm_Autocorrelation_d_1_PET_c04                                 0.03   0.87      0.20
glcm_ClusterProminence_d_1_CT_b20                                0.00   0.94      0.08
glcm_ClusterProminence_d_1_CT_c16                                0.01   0.93      0.10
glcm_ClusterProminence_d_1_PET_b2                                0.10   0.75      0.41
glcm_ClusterProminence_d_1_PET_c04                               0.17   0.68      0.56
glcm_ClusterShade_d_1_CT_b20                                     0.98   0.32      1.63
glcm_ClusterShade_d_1_CT_c16                                     0.00   0.96      0.06
glcm_ClusterShade_d_1_PET_b2                                     0.75   0.39      1.37
glcm_ClusterShade_d_1_PET_c04                                    0.33   0.57      0.82
glcm_ClusterTendency_d_1_CT_b20                                  0.01   0.91      0.14
glcm_ClusterTendency_d_1_CT_c16                                  0.01   0.94      0.09
glcm_ClusterTendency_d_1_PET_b2                                  0.00   0.97      0.05
glcm_ClusterTendency_d_1_PET_c04                                 0.09   0.76      0.40
glcm_Contrast_d_1_CT_b20                                         0.00   0.95      0.07
glcm_Contrast_d_1_CT_c16                                         0.03   0.86      0.21
glcm_Contrast_d_1_PET_b2                                         0.04   0.83      0.26
glcm_Contrast_d_1_PET_c04                                        0.01   0.94      0.09
glcm_Correlation_d_1_CT_b20                                      0.44   0.51      0.98
glcm_Correlation_d_1_CT_c16                                      0.72   0.40      1.33
glcm_Correlation_d_1_PET_b2                                      0.04   0.85      0.23
glcm_Correlation_d_1_PET_c04                                     0.02   0.88      0.18
glcm_DifferenceAverage_d_1_CT_b20                                0.00   0.98      0.02
glcm_DifferenceAverage_d_1_CT_c16                                0.00   0.97      0.05
glcm_DifferenceAverage_d_1_PET_b2                                0.00   0.98      0.03
glcm_DifferenceAverage_d_1_PET_c04                               0.00   0.96      0.06
glcm_DifferenceEntropy_d_1_CT_b20                                0.01   0.92      0.12
glcm_DifferenceEntropy_d_1_CT_c16                                0.00   0.95      0.08
glcm_DifferenceEntropy_d_1_PET_b2                                0.04   0.83      0.26
glcm_DifferenceEntropy_d_1_PET_c04                               0.13   0.72      0.47
glcm_DifferenceVariance_d_1_CT_b20                               0.01   0.93      0.11
glcm_DifferenceVariance_d_1_CT_c16                               0.04   0.84      0.26
glcm_DifferenceVariance_d_1_PET_b2                               0.10   0.76      0.40
glcm_DifferenceVariance_d_1_PET_c04                              0.08   0.77      0.37
glcm_Id_d_1_CT_b20                                               0.00   0.95      0.07
glcm_Id_d_1_CT_c16                                               0.00   0.98      0.02
glcm_Id_d_1_PET_b2                                               0.00   0.96      0.05
glcm_Id_d_1_PET_c04                                              0.01   0.91      0.14
glcm_Idm_d_1_CT_b20                                              0.00   0.95      0.08
glcm_Idm_d_1_CT_c16                                              0.00   1.00      0.00
glcm_Idm_d_1_PET_b2                                              0.00   0.99      0.02
glcm_Idm_d_1_PET_c04                                             0.01   0.93      0.11
glcm_Idmn_d_1_CT_b20                                             0.02   0.90      0.16
glcm_Idmn_d_1_CT_c16                                             0.02   0.89      0.17
glcm_Idmn_d_1_PET_b2                                             0.02   0.89      0.17
glcm_Idmn_d_1_PET_c04                                            0.00   0.95      0.08
glcm_Idn_d_1_CT_b20                                              0.01   0.92      0.12
glcm_Idn_d_1_CT_c16                                              0.00   0.98      0.02
glcm_Idn_d_1_PET_b2                                              0.23   0.63      0.66
glcm_Idn_d_1_PET_c04                                             0.01   0.94      0.08
glcm_Imc1_d_1_CT_b20                                             0.80   0.37      1.43
glcm_Imc1_d_1_CT_c16                                             0.08   0.78      0.37
glcm_Imc1_d_1_PET_b2                                             0.10   0.76      0.41
glcm_Imc1_d_1_PET_c04                                            0.02   0.90      0.16
glcm_Imc2_d_1_CT_b20                                             0.03   0.86      0.22
glcm_Imc2_d_1_CT_c16                                             0.71   0.40      1.32
glcm_Imc2_d_1_PET_b2                                             0.08   0.78      0.36
glcm_Imc2_d_1_PET_c04                                            0.01   0.92      0.12
glcm_InverseVariance_d_1_CT_b20                                  0.02   0.88      0.19
glcm_InverseVariance_d_1_CT_c16                                  0.02   0.89      0.17
glcm_InverseVariance_d_1_PET_b2                                  0.04   0.85      0.23
glcm_InverseVariance_d_1_PET_c04                                 0.06   0.80      0.31
glcm_JointAverage_d_1_CT_b20                                     0.06   0.81      0.30
glcm_JointAverage_d_1_CT_c16                                     0.04   0.85      0.23
glcm_JointAverage_d_1_PET_b2                                     0.00   0.96      0.06
glcm_JointAverage_d_1_PET_c04                                    0.00   0.98      0.03
glcm_JointEnergy_d_1_CT_b20                                      0.03   0.87      0.20
glcm_JointEnergy_d_1_CT_c16                                      0.01   0.93      0.10
glcm_JointEnergy_d_1_PET_b2                                      0.16   0.69      0.53
glcm_JointEnergy_d_1_PET_c04                                     0.00   0.98      0.02
glcm_JointEntropy_d_1_CT_b20                                     0.01   0.90      0.15
glcm_JointEntropy_d_1_CT_c16                                     0.08   0.78      0.36
glcm_JointEntropy_d_1_PET_b2                                     0.00   0.96      0.06
glcm_JointEntropy_d_1_PET_c04                                    0.00   0.96      0.06
glcm_MCC_d_1_CT_b20                                              0.40   0.53      0.92
glcm_MCC_d_1_CT_c16                                              0.06   0.81      0.30
glcm_MCC_d_1_PET_b2                                              0.01   0.92      0.12
glcm_MCC_d_1_PET_c04                                             0.02   0.88      0.19
glcm_MaximumProbability_d_1_CT_b20                               0.04   0.85      0.23
glcm_MaximumProbability_d_1_CT_c16                               0.10   0.76      0.40
glcm_MaximumProbability_d_1_PET_b2                               0.13   0.71      0.49
glcm_MaximumProbability_d_1_PET_c04                              0.00   1.00      0.00
glcm_SumAverage_d_1_CT_b20                                       0.06   0.81      0.30
glcm_SumAverage_d_1_CT_c16                                       0.04   0.85      0.23
glcm_SumAverage_d_1_PET_b2                                       0.00   0.96      0.06
glcm_SumAverage_d_1_PET_c04                                      0.00   0.98      0.03
glcm_SumEntropy_d_1_CT_b20                                       0.00   0.99      0.02
glcm_SumEntropy_d_1_CT_c16                                       0.08   0.78      0.36
glcm_SumEntropy_d_1_PET_b2                                       0.00   0.97      0.05
glcm_SumEntropy_d_1_PET_c04                                      0.01   0.93      0.10
glcm_SumSquares_d_1_CT_b20                                       0.01   0.92      0.12
glcm_SumSquares_d_1_CT_c16                                       0.00   0.96      0.06
glcm_SumSquares_d_1_PET_b2                                       0.00   0.96      0.05
glcm_SumSquares_d_1_PET_c04                                      0.09   0.76      0.39
gldm_DependenceEntropy_d_1_CT_b20                                0.21   0.65      0.62
gldm_DependenceEntropy_d_1_CT_c16                                0.11   0.75      0.42
gldm_DependenceEntropy_d_1_PET_b2                                0.06   0.81      0.30
gldm_DependenceEntropy_d_1_PET_c04                               0.03   0.87      0.20
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.14   0.70      0.51
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.03   0.86      0.21
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.34   0.56      0.84
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.05   0.82      0.28
gldm_DependenceNonUniformity_d_1_CT_b20                          0.02   0.90      0.15
gldm_DependenceNonUniformity_d_1_CT_c16                          2.56   0.11      3.19
gldm_DependenceNonUniformity_d_1_PET_b2                          0.04   0.85      0.24
gldm_DependenceNonUniformity_d_1_PET_c04                         0.11   0.74      0.42
gldm_DependenceVariance_d_1_CT_b20                               0.83   0.36      1.47
gldm_DependenceVariance_d_1_CT_c16                               0.06   0.81      0.30
gldm_DependenceVariance_d_1_PET_b2                               0.28   0.60      0.75
gldm_DependenceVariance_d_1_PET_c04                              0.56   0.46      1.13
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.35   0.55      0.86
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.36   0.55      0.87
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.20   0.65      0.61
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00   0.99      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00   1.00      0.00
gldm_GrayLevelVariance_d_1_CT_c16                                0.00   1.00      0.01
gldm_GrayLevelVariance_d_1_PET_b2                                0.00   0.98      0.03
gldm_GrayLevelVariance_d_1_PET_c04                               0.04   0.84      0.24
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.16   0.69      0.54
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.01   0.91      0.14
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00   0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.04   0.85      0.24
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.01   0.91      0.14
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.02   0.89      0.16
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.05   0.82      0.28
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.02   0.89      0.17
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.69   0.41      1.30
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00   0.95      0.07
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.04   0.85      0.24
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00   0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.02   0.89      0.17
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.04   0.84      0.24
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.10   0.75      0.41
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.51   0.48      1.07
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.03   0.87      0.20
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00   0.97      0.04
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.01   0.94      0.09
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.50   0.48      1.06
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.01   0.91      0.14
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.10   0.75      0.42
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.10   0.76      0.40
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.03   0.87      0.20
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.27   0.60      0.74
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.03   0.87      0.20
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.05   0.82      0.28
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.01   0.92      0.12
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.02   0.88      0.19
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.20   0.66      0.61
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.03   0.87      0.19
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00   0.99      0.02
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.00   0.96      0.05
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.46   0.50      1.01
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.03   0.87      0.21
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.04   0.84      0.25
glrlm_GrayLevelNonUniformity_CT_b20                              0.01   0.93      0.10
glrlm_GrayLevelNonUniformity_CT_c16                              1.08   0.30      1.74

In [34]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['charlson', 'glszm_LargeAreaEmphasis_CT_c16',
       'glszm_LargeAreaLowGrayLevelEmphasis_CT_c16',
       'glszm_ZoneVariance_CT_c16', 'ngtdm_Busyness_d_1_PET_b2'],
      dtype='object')

## Test dataset: MAASTRO

In [35]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [36]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [37]:
# Need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [38]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,DFS,DFS_event
0,1,55,0,0,1,0,0,1,1,1,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,8.83,1.0
3,4,61,1,0,0,0,1,1,0,1,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,19.73,1.0
4,6,70,0,0,1,0,0,1,1,1,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,13.27,1.0
95,111,63,0,0,0,0,1,0,0,1,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [39]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [40]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [41]:
# Set X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# Set y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [42]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [43]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 388)
y_train:  (139,)

In [44]:
# Change the name of a column 'DFS_event' in the clincial_test 
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [45]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 390)

# Yeo-Johnson Transformation

In [46]:
# Copy the original X for later 
original_X = X.copy()

In [48]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

## Standardize the data but not the categorical columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']
### Separate the categorical and non-categorical columns
X_categorical = X[categorical_columns]
X_numeric = X.drop(categorical_columns, axis=1)
X_numeric_columns = X_numeric.columns
X_numeric_index = X_numeric.index

### Standardize non-categorical and then concat with the categorical
pt = PowerTransformer(method='yeo-johnson')
X_numeric_std = pt.fit_transform(X_numeric)
X_numeric_std = pd.DataFrame(X_numeric_std, columns=X_numeric_columns, index=X_numeric_index)
X_std = pd.concat([X_categorical, X_numeric_std], axis=1)

## Sort the order of the columns as it was in the clinical train 
X_std = X_std[original_X.columns]

In [49]:
# Standardize X_MAASTRO 
MAASTRO_new = X_MAASTRO.copy()
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns

MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = pt.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [51]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = MAASTRO_new_std

In [52]:
X_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,...,LBP_003_PET,LBP_012_PET,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET
0,54.238356,1,0,1,0,0,1,0.0,0,0.000000,...,0.000123,0.001172,0.029974,0.815962,0.000000,0.002035,0.140311,0.000062,0.009991,0.000370
1,54.539726,0,0,0,0,1,0,0.0,1,27.404795,...,0.000349,0.008383,0.059728,0.707300,0.000000,0.008732,0.191058,0.000349,0.023402,0.000699
2,59.019178,0,1,0,0,0,1,0.0,1,41.019178,...,0.000000,0.001759,0.039463,0.819828,0.000034,0.002518,0.126531,0.000000,0.009452,0.000414
3,70.726027,0,0,0,0,1,0,0.0,1,37.500000,...,0.000300,0.006892,0.061133,0.716212,0.000000,0.003296,0.192388,0.000000,0.018879,0.000899
4,67.865753,0,0,0,0,1,0,0.0,1,53.000000,...,0.000000,0.001993,0.058589,0.696493,0.000199,0.008968,0.202073,0.000399,0.029892,0.001395
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,60.435616,0,0,1,0,0,1,1.0,0,0.000000,...,0.000000,0.001562,0.029444,0.804831,0.000000,0.001442,0.152626,0.000000,0.009734,0.000361
135,68.794521,0,0,1,0,0,1,1.0,0,0.000000,...,0.000039,0.001968,0.046451,0.792151,0.000000,0.004094,0.142778,0.000079,0.011810,0.000630
136,57.498630,0,0,1,0,0,1,1.0,1,39.498630,...,0.000000,0.000326,0.016316,0.832202,0.000000,0.000914,0.140582,0.000000,0.009137,0.000522
137,65.684932,0,0,1,0,0,1,1.0,1,71.527397,...,0.000000,0.001030,0.038862,0.787588,0.000000,0.003144,0.156640,0.000054,0.011978,0.000705
138,61.676712,0,0,1,0,0,1,1.0,0,2.250000,...,0.000000,0.000082,0.011577,0.830670,0.000000,0.000978,0.147644,0.000000,0.008642,0.000408

In [53]:
X_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,...,LBP_003_PET,LBP_012_PET,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET
0,-0.785036,1,0,1,0,0,1,0.0,0,-1.533345,...,1.042615,-0.340702,-0.305657,0.622355,-0.784694,-0.404309,-0.370546,-0.074611,-0.654022,-0.325914
1,-0.746998,0,0,0,0,1,0,0.0,1,0.397233,...,1.929439,1.907148,0.939011,-1.489676,-0.784694,1.826912,1.188847,1.689445,1.560347,0.852496
2,-0.175256,0,1,0,0,0,1,0.0,1,0.830437,...,-0.799521,0.082511,0.147926,0.741227,0.236612,-0.110511,-1.026597,-1.065926,-0.824361,-0.125568
3,1.371631,0,0,0,0,1,0,0.0,1,0.727938,...,1.846691,1.751709,0.986180,-1.383365,-0.784694,0.301039,1.216712,-1.065926,1.122247,1.296177
4,0.987008,0,0,0,0,1,0,0.0,1,1.144253,...,-0.799521,0.230152,0.900131,-1.607406,1.784568,1.860059,1.405024,1.782787,1.919501,1.900963
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,0.007949,0,0,1,0,0,1,1.0,0,-1.533345,...,-0.799521,-0.050750,-0.332827,0.301629,-0.784694,-0.811377,0.115613,-1.065926,-0.733951,-0.371465
135,1.111443,0,0,1,0,0,1,1.0,0,-1.533345,...,-0.000653,0.215135,0.445866,-0.027763,-0.784694,0.654869,-0.266178,0.138716,-0.145951,0.659834
136,-0.370651,0,0,1,0,0,1,1.0,1,0.786825,...,-0.799521,-1.105445,-1.073694,1.149438,-0.784694,-1.222412,-0.358889,-1.065926,-0.928256,0.305804
137,0.696583,0,0,1,0,0,1,1.0,1,1.554125,...,-0.799521,-0.455330,0.120914,-0.137599,-0.784694,0.225798,0.256551,-0.175482,-0.103535,0.868321
138,0.169401,0,0,1,0,0,1,1.0,0,-1.110899,...,-0.799521,-1.367726,-1.376730,1.096510,-0.784694,-1.169521,-0.070856,-1.065926,-1.098939,-0.153446

In [54]:
MAASTRO_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,...,LBP_003_PET,LBP_012_PET,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET
0,55,0,0,1,0,0,1,1,1,0,...,0.000026,0.001181,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341
1,55,0,0,1,0,0,0,0,0,20,...,0.000056,0.002735,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335
2,55,0,0,1,0,0,0,0,1,6,...,0.000286,0.001888,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229
3,61,1,0,0,0,1,1,0,1,45,...,0.000160,0.003037,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240
4,70,0,0,1,0,0,1,1,1,59,...,0.000071,0.000881,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,66,1,0,0,0,1,0,0,0,55,...,0.000000,0.000544,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078
95,63,0,0,0,0,1,0,0,1,174,...,0.000109,0.000869,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489
96,63,0,0,1,0,0,1,1,1,0,...,0.000000,0.000734,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141
97,54,0,0,1,0,0,1,1,0,0,...,0.000114,0.001640,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038
98,62,0,0,0,1,0,1,0,0,40,...,0.000000,0.000225,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337

In [55]:
MAASTRO_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,...,LBP_003_PET,LBP_012_PET,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET
0,-0.688798,0,0,1,0,0,1,1,1,-1.533345,...,-0.238970,-0.333758,-0.365666,1.333829,0.033184,-0.624049,-1.260759,-0.597387,-1.225380,-0.467062
1,-0.688798,0,0,1,0,0,0,0,0,0.104884,...,0.263801,0.633163,0.571622,0.357306,1.682719,0.130792,-0.900442,0.946684,-1.278036,-0.498297
2,-0.688798,0,0,1,0,0,0,0,1,-0.713198,...,1.817599,0.165484,-0.880459,1.082861,0.693043,-0.538327,-0.503809,-1.065926,-1.099242,-1.088084
3,0.081262,1,0,0,0,1,1,0,1,0.940197,...,1.314752,0.772266,0.474304,-0.697526,-0.784694,0.441636,0.716866,0.152800,0.179520,-1.022290
4,1.273609,0,0,1,0,0,1,1,1,1.285347,...,0.471935,-0.580655,-0.106360,0.902157,-0.784694,-0.353231,-0.943409,-0.453142,-0.848088,0.330123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0.738387,1,0,0,0,1,0,0,0,1.192311,...,-0.799521,-0.888554,-1.001790,1.233343,-0.784694,-0.901046,-0.507763,0.126817,-1.076381,-2.149148
95,0.342484,0,0,0,0,1,0,0,1,3.094727,...,0.907497,-0.591523,-0.305416,0.791663,-0.784694,-1.541116,-0.488635,-0.173978,-1.006544,0.181649
96,0.342484,0,0,1,0,0,1,1,1,-1.533345,...,-0.799521,-0.711549,-1.010039,2.238796,-0.784694,-1.161970,-1.679560,-0.565019,-2.317743,-1.669244
97,-0.815082,0,0,1,0,0,1,1,0,-1.533345,...,0.962590,0.002735,-0.546695,1.734121,-0.784694,-0.778405,-1.524056,-1.065926,-2.289503,-2.477923
98,0.211597,0,0,0,1,0,1,0,0,0.801315,...,-0.799521,-1.211746,-0.917772,0.512678,-0.784694,-1.234339,0.266254,0.498900,-0.548452,-0.486336

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [56]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:49:40,550] A new study created in memory with name: no-name-465d94ad-28cd-45d5-8e15-4695103d03fc
python(33114) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

  0%|          | 0/1 [00:00<?, ?it/s]

[W 2024-04-16 20:49:43,982] Trial 0 failed with parameters: {} because of the following error: LinAlgError('Matrix is singular.').
Traceback (most recent call last):
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/var/folders/64/jkqp6xyx2hj50dmd2pqfm3780000gn/T/ipykernel_31603/3148227347.py", line 62, in objective
    model.fit(X_train_std, y_train)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/linear_model/coxph.py", line 449, in fit
    delta = solve(
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 220, in solve
    _solve_check(n, info)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 29, in _solve_check
    raise LinAlgError('Matrix is singular.')
numpy.linalg.LinAlgError: Matrix is singular.
[W 2024-04-16 20:49:43,992] Trial 0 failed with value None.

LinAlgError: Matrix is singular.

In [59]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

ValueError: No trials are completed yet.

In [60]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

ValueError: No trials are completed yet.

#### Test

In [61]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [62]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

LinAlgError: Matrix is singular.

In [63]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [64]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

NameError: name 'c_index' is not defined

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [65]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:49:57,834] A new study created in memory with name: no-name-a682c9c4-bd26-4db7-b9c7-411e96522584

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5756972111553785
Fold 2 C-index: 0.7073643410852714
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6653992395437263

[I 2024-04-16 20:50:08,080] A new study created in memory with name: no-name-f76268ca-2509-4569-a91f-237e1900b275

Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 20:50:08,063] Trial 0 finished with value: 0.635065183651369 and parameters: {}. Best is trial 0 with value: 0.635065183651369.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.635065183651369], datetime_start=datetime.datetime(2024, 4, 16, 20, 49, 57, 871851), datetime_complete=datetime.datetime(2024, 4, 16, 20, 50, 8, 62951), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.635065183651369

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709663544278
Fold 2 IBS: 0.23203988184644345
Fold 3 IBS: 0.22898186778522736
Fold 4 IBS: 0.24197476559442144
Fold 5 IBS: 0.22939558964342896
[I 2024-04-16 20:50:20,794] Trial 0 finished with value: 0.23592784030099279 and parameters: {}. Best is trial 0 with value: 0.23592784030099279.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592784030099279], datetime_start=datetime.datetime(2024, 4, 16, 20, 50, 8, 158709), datetime_complete=datetime.datetime(2024, 4, 16, 20, 50, 20, 793610), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592784030099279

In [66]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [67]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.635
train_ibs:  0.236

#### Test

In [68]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [69]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.53

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [70]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [71]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:50:21,121] A new study created in memory with name: no-name-73a33ba5-e856-4c27-9d7e-c3a5255bd1d5

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.4723404255319149
Fold 4 C-index: 0.623574144486692

[I 2024-04-16 20:50:35,487] A new study created in memory with name: no-name-c63a5ae8-e1bb-4960-8eb8-e945c00d0df3

Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 20:50:35,471] Trial 0 finished with value: 0.5828609695229361 and parameters: {}. Best is trial 0 with value: 0.5828609695229361.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5828609695229361], datetime_start=datetime.datetime(2024, 4, 16, 20, 50, 21, 151201), datetime_complete=datetime.datetime(2024, 4, 16, 20, 50, 35, 471518), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5828609695229361

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.39850056002671524
Fold 2 IBS: 0.28579825945985843
Fold 3 IBS: 0.40623214528565893
Fold 4 IBS: 0.35516159839951
Fold 5 IBS: 0.3204294572240529
[I 2024-04-16 20:50:50,424] Trial 0 finished with value: 0.3532244040791591 and parameters: {}. Best is trial 0 with value: 0.3532244040791591.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.3532244040791591], datetime_start=datetime.datetime(2024, 4, 16, 20, 50, 35, 521987), datetime_complete=datetime.datetime(2024, 4, 16, 20, 50, 50, 423562), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.3532244040791591

In [72]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [73]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.583
train_ibs:  0.353

#### Test

In [74]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [75]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.491

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.457

In [76]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [77]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:50:52,514] A new study created in memory with name: no-name-ab1b88e5-65e7-4213-bd4b-24589fd74fe1

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.5106382978723404
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.5836909871244635
[I 2024-04-16 20:51:03,626] Trial 0 finished with value: 0.5831220165507387 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.5831220165507387.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5234042553191489
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 20:51:20,443] Trial 1 finished with value: 0.5733962597028263 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.5831220165507387.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:51:32,528] Trial 2 finished with value: 0.5775498146949685 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.5831220165507387.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.5063829787234042
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 20:51:45,771] Trial 3 finished with value: 0.5764833945543295 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.5831220165507387.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.5106382978723404
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.5836909871244635
[I 2024-04-16 20:51:59,616] Trial 4 finished with value: 0.5861785791704811 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 4 with value: 0.5861785791704811.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.5063829787234042
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 20:52:11,816] Trial 5 finished with value: 0.5710511312122606 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 4 with value: 0.5861785791704811.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.46808510638297873
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 20:52:25,740] Trial 6 finished with value: 0.5789248426969831 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 4 with value: 0.5861785791704811.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.502127659574468
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 20:52:41,737] Trial 7 finished with value: 0.5790042507696835 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 4 with value: 0.5861785791704811.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.5106382978723404
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 20:52:55,823] Trial 8 finished with value: 0.5741835638633406 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 4 with value: 0.5861785791704811.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.5106382978723404
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 20:53:11,308] Trial 9 finished with value: 0.5711201198177291 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 4 with value: 0.5861785791704811.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.46808510638297873
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 20:53:27,700] Trial 10 finished with value: 0.5805184681949911 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 4 with value: 0.5861785791704811.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.5063829787234042
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.5836909871244635
[I 2024-04-16 20:53:41,068] Trial 11 finished with value: 0.5846034155421694 and parameters: {'l1_ratio': 0.748312136386636}. Best is trial 4 with value: 0.5861785791704811.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.5106382978723404
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.5836909871244635
[I 2024-04-16 20:53:58,827] Trial 12 finished with value: 0.5861785791704811 and parameters: {'l1_ratio': 0.7247092940361127}. Best is trial 4 with value: 0.5861785791704811.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.4978723404255319
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 20:54:21,700] Trial 13 finished with value: 0.5837812759318618 and parameters: {'l1_ratio': 0.8207229344041}. Best is trial 4 with value: 0.5861785791704811.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 20:54:33,360] Trial 14 finished with value: 0.6245823368515838 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 14 with value: 0.6245823368515838.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 20:54:42,489] Trial 15 finished with value: 0.6342027595164134 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 15 with value: 0.6342027595164134.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 20:54:56,950] Trial 16 finished with value: 0.6326818469688849 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 15 with value: 0.6342027595164134.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 20:55:14,490] Trial 17 finished with value: 0.6229635114791071 and parameters: {'l1_ratio': 0.10932144510738274}. Best is trial 15 with value: 0.6342027595164134.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 20:55:42,644] Trial 18 finished with value: 0.6357236720639419 and parameters: {'l1_ratio': 0.013003332120057056}. Best is trial 18 with value: 0.6357236720639419.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 20:55:58,377] Trial 19 finished with value: 0.6326818469688849 and parameters: {'l1_ratio': 0.004308240931741479}. Best is trial 18 with value: 0.6357236720639419.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5319148936170213
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:56:10,235] Trial 20 finished with value: 0.5735299617388614 and parameters: {'l1_ratio': 0.20815195211742094}. Best is trial 18 with value: 0.6357236720639419.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 20:56:21,253] Trial 21 finished with value: 0.6372445846114704 and parameters: {'l1_ratio': 0.021025450652628987}. Best is trial 21 with value: 0.6372445846114704.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 20:56:30,829] Trial 22 finished with value: 0.6246186933268236 and parameters: {'l1_ratio': 0.11529231222327557}. Best is trial 21 with value: 0.6372445846114704.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 20:56:40,659] Trial 23 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.06998585343854669}. Best is trial 23 with value: 0.6380665972349431.

Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5234042553191489
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 20:56:56,186] Trial 24 finished with value: 0.5741930724518303 and parameters: {'l1_ratio': 0.2985516395803664}. Best is trial 23 with value: 0.6380665972349431.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 20:57:05,039] Trial 25 finished with value: 0.6010697487146002 and parameters: {'l1_ratio': 0.1613975971413524}. Best is trial 23 with value: 0.6380665972349431.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 20:57:15,895] Trial 26 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.0715675035002228}. Best is trial 23 with value: 0.6380665972349431.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5234042553191489
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 20:57:27,465] Trial 27 finished with value: 0.5718026342048182 and parameters: {'l1_ratio': 0.3166033499880153}. Best is trial 23 with value: 0.6380665972349431.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 20:57:36,518] Trial 28 finished with value: 0.6245823368515838 and parameters: {'l1_ratio': 0.08708306912896363}. Best is trial 23 with value: 0.6380665972349431.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5361702127659574
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:57:48,385] Trial 29 finished with value: 0.5751778383176527 and parameters: {'l1_ratio': 0.21716775597268598}. Best is trial 23 with value: 0.6380665972349431.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 20:58:03,886] Trial 30 finished with value: 0.5803709775205533 and parameters: {'l1_ratio': 0.1644363726994409}. Best is trial 23 with value: 0.6380665972349431.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 20:58:27,094] Trial 31 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.07150304270146425}. Best is trial 23 with value: 0.6380665972349431.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 20:58:44,811] Trial 32 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.0713123037303855}. Best is trial 23 with value: 0.6380665972349431.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5276595744680851
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 20:59:00,577] Trial 33 finished with value: 0.5750077798063777 and parameters: {'l1_ratio': 0.2564774270891551}. Best is trial 23 with value: 0.6380665972349431.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 20:59:11,021] Trial 34 finished with value: 0.6389249663336555 and parameters: {'l1_ratio': 0.08145674611296568}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 20:59:30,134] Trial 35 finished with value: 0.5803094211708448 and parameters: {'l1_ratio': 0.1794297691813354}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.5106382978723404
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 21:00:07,529] Trial 36 finished with value: 0.5638653493544707 and parameters: {'l1_ratio': 0.3560663317983592}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.502127659574468
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 21:00:35,166] Trial 37 finished with value: 0.5772658936217043 and parameters: {'l1_ratio': 0.5802102856643269}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 21:00:59,326] Trial 38 finished with value: 0.600309292440836 and parameters: {'l1_ratio': 0.1570572542337432}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5276595744680851
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 21:01:16,561] Trial 39 finished with value: 0.5750077798063777 and parameters: {'l1_ratio': 0.2593235235530371}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:01:30,994] Trial 40 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.06302839741626033}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:01:40,502] Trial 41 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.06910923262667215}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:01:51,904] Trial 42 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.061570002912863145}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:02:02,834] Trial 43 finished with value: 0.6246186933268236 and parameters: {'l1_ratio': 0.11756086927260981}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 21:02:11,937] Trial 44 finished with value: 0.6012040180147882 and parameters: {'l1_ratio': 0.14039851697861694}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:02:20,929] Trial 45 finished with value: 0.6388270535087074 and parameters: {'l1_ratio': 0.05106945333988881}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5361702127659574
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 21:02:30,004] Trial 46 finished with value: 0.5743810255686487 and parameters: {'l1_ratio': 0.21133087403092338}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.5063829787234042
Fold 4 C-index: 0.5931558935361216

Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 21:02:39,651] Trial 47 finished with value: 0.5710363936875751 and parameters: {'l1_ratio': 0.46157256171761685}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.46808510638297873
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 21:02:48,570] Trial 48 finished with value: 0.5788701677731437 and parameters: {'l1_ratio': 0.908082736959313}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.5063829787234042
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 21:02:59,871] Trial 49 finished with value: 0.5756502253300858 and parameters: {'l1_ratio': 0.5349713871649028}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 21:03:08,831] Trial 50 finished with value: 0.6387654971589989 and parameters: {'l1_ratio': 0.04751224292215285}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 21:03:17,612] Trial 51 finished with value: 0.6387654971589989 and parameters: {'l1_ratio': 0.046946291137944934}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 21:03:26,134] Trial 52 finished with value: 0.6387654971589989 and parameters: {'l1_ratio': 0.04608883416837671}. Best is trial 34 with value: 0.6389249663336555.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:03:33,389] Trial 53 finished with value: 0.6396238662577114 and parameters: {'l1_ratio': 0.042355011843832266}. Best is trial 53 with value: 0.6396238662577114.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:03:40,832] Trial 54 finished with value: 0.6396238662577114 and parameters: {'l1_ratio': 0.03752352690241521}. Best is trial 53 with value: 0.6396238662577114.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:03:48,710] Trial 55 finished with value: 0.6396238662577114 and parameters: {'l1_ratio': 0.03493559105697867}. Best is trial 53 with value: 0.6396238662577114.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:03:56,304] Trial 56 finished with value: 0.6246186933268236 and parameters: {'l1_ratio': 0.114091963793568}. Best is trial 53 with value: 0.6396238662577114.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.502127659574468
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 21:04:06,280] Trial 57 finished with value: 0.5781969756708962 and parameters: {'l1_ratio': 0.6246196826499275}. Best is trial 53 with value: 0.6396238662577114.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:04:14,622] Trial 58 finished with value: 0.6405185918316635 and parameters: {'l1_ratio': 0.024791417584816372}. Best is trial 58 with value: 0.6405185918316635.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:04:22,751] Trial 59 finished with value: 0.6412790481054278 and parameters: {'l1_ratio': 0.02546295954223466}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 21:04:32,570] Trial 60 finished with value: 0.633442303242649 and parameters: {'l1_ratio': 0.006104181039009421}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:04:42,713] Trial 61 finished with value: 0.6412790481054278 and parameters: {'l1_ratio': 0.03308971029221893}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:04:52,761] Trial 62 finished with value: 0.6230614243040552 and parameters: {'l1_ratio': 0.1334635835821149}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:05:04,286] Trial 63 finished with value: 0.6412790481054278 and parameters: {'l1_ratio': 0.026916982996019967}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:05:12,221] Trial 64 finished with value: 0.6412790481054278 and parameters: {'l1_ratio': 0.026277067819073074}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 21:05:24,131] Trial 65 finished with value: 0.6319213906951207 and parameters: {'l1_ratio': 0.0012631262363742152}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:05:34,831] Trial 66 finished with value: 0.6237239677528713 and parameters: {'l1_ratio': 0.105822319679906}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 21:05:44,334] Trial 67 finished with value: 0.5803094211708448 and parameters: {'l1_ratio': 0.18184274787844787}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:05:57,079] Trial 68 finished with value: 0.6412790481054278 and parameters: {'l1_ratio': 0.028159068937878486}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:06:08,616] Trial 69 finished with value: 0.6405185918316635 and parameters: {'l1_ratio': 0.02479366600866093}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:06:17,737] Trial 70 finished with value: 0.6245823368515838 and parameters: {'l1_ratio': 0.09830224891258263}. Best is trial 59 with value: 0.6412790481054278.

Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:06:25,317] Trial 71 finished with value: 0.6412790481054278 and parameters: {'l1_ratio': 0.025838626616616955}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 21:06:32,204] Trial 72 finished with value: 0.6372445846114704 and parameters: {'l1_ratio': 0.020614025238032994}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 21:06:40,548] Trial 73 finished with value: 0.6326818469688849 and parameters: {'l1_ratio': 0.003688262003792672}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:06:52,091] Trial 74 finished with value: 0.6230614243040552 and parameters: {'l1_ratio': 0.1286813132494076}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:07:01,779] Trial 75 finished with value: 0.6245823368515838 and parameters: {'l1_ratio': 0.08907373276207284}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:07:09,979] Trial 76 finished with value: 0.6412790481054278 and parameters: {'l1_ratio': 0.02838772937033258}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5276595744680851
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 21:07:19,683] Trial 77 finished with value: 0.5727404542587827 and parameters: {'l1_ratio': 0.19328346899350535}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 21:07:27,798] Trial 78 finished with value: 0.6012040180147882 and parameters: {'l1_ratio': 0.1382600770925704}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:07:35,683] Trial 79 finished with value: 0.6245823368515838 and parameters: {'l1_ratio': 0.09243877747217458}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5361702127659574
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 21:07:44,062] Trial 80 finished with value: 0.5774955636141852 and parameters: {'l1_ratio': 0.23574261802313995}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:07:51,263] Trial 81 finished with value: 0.6412790481054278 and parameters: {'l1_ratio': 0.029745851153293923}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:07:57,768] Trial 82 finished with value: 0.6388634099839471 and parameters: {'l1_ratio': 0.023101448423929014}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:08:04,190] Trial 83 finished with value: 0.6389249663336555 and parameters: {'l1_ratio': 0.08271027469515925}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:08:10,424] Trial 84 finished with value: 0.6396238662577114 and parameters: {'l1_ratio': 0.035931745398650544}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 21:08:18,437] Trial 85 finished with value: 0.6319213906951207 and parameters: {'l1_ratio': 0.0006207778531381637}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 21:08:26,590] Trial 86 finished with value: 0.6011676615395484 and parameters: {'l1_ratio': 0.15379638007615046}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:08:32,993] Trial 87 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.06417715869125039}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:08:40,146] Trial 88 finished with value: 0.6237239677528713 and parameters: {'l1_ratio': 0.10574190593746689}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:08:47,084] Trial 89 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.06327453311398572}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:08:54,238] Trial 90 finished with value: 0.6396602227329511 and parameters: {'l1_ratio': 0.02403652677851508}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:09:03,917] Trial 91 finished with value: 0.6405185918316635 and parameters: {'l1_ratio': 0.024244470778024663}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.5063829787234042
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.5836909871244635
[I 2024-04-16 21:09:14,197] Trial 92 finished with value: 0.584588678017484 and parameters: {'l1_ratio': 0.7691118103095544}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:09:21,694] Trial 93 finished with value: 0.6389249663336555 and parameters: {'l1_ratio': 0.0803687696542218}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745

Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:09:29,106] Trial 94 finished with value: 0.6412790481054278 and parameters: {'l1_ratio': 0.028533689531648046}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:09:36,691] Trial 95 finished with value: 0.6389249663336555 and parameters: {'l1_ratio': 0.05391119127614202}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:09:45,550] Trial 96 finished with value: 0.6246186933268236 and parameters: {'l1_ratio': 0.11551554404160966}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:09:53,215] Trial 97 finished with value: 0.6396238662577114 and parameters: {'l1_ratio': 0.04259741592615914}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 21:10:00,851] Trial 98 finished with value: 0.6319213906951207 and parameters: {'l1_ratio': 0.0015828444660384265}. Best is trial 59 with value: 0.6412790481054278.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753

[I 2024-04-16 21:10:09,101] A new study created in memory with name: no-name-6fe99a76-c357-406f-96c1-e005367dac0a

Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:10:09,077] Trial 99 finished with value: 0.6245823368515838 and parameters: {'l1_ratio': 0.08592463668837769}. Best is trial 59 with value: 0.6412790481054278.


* Best trial for C-index:
 FrozenTrial(number=59, state=TrialState.COMPLETE, values=[0.6412790481054278], datetime_start=datetime.datetime(2024, 4, 16, 21, 4, 14, 629175), datetime_complete=datetime.datetime(2024, 4, 16, 21, 4, 22, 751344), params={'l1_ratio': 0.02546295954223466}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=59, value=None)


* Best Score for C-index:
 0.6412790481054278

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.3966465644914146
Fold 2 IBS: 0.28637185420169997
Fold 3 IBS: 0.4025192458137644
Fold 4 IBS: 0.32580492906293385
Fold 5 IBS: 0.29932384811304946
[I 2024-04-16 21:10:19,531] Trial 0 finished with value: 0.3421332883365724 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.3421332883365724.
Fold 1 IBS: 0.40259804979747177
Fold 2 IBS: 0.2265618087310044
Fold 3 IBS: 0.36724961425493335
Fold 4 IBS: 0.33390963573464383
Fold 5 IBS: 0.2705009693565652
[I 2024-04-16 21:10:28,911] Trial 1 finished with value: 0.3201640155749237 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.3201640155749237.
Fold 1 IBS: 0.4026433726024702
Fold 2 IBS: 0.22741753924120442
Fold 3 IBS: 0.35508264627336156
Fold 4 IBS: 0.3305784833519445
Fold 5 IBS: 0.2672392448991321
[I 2024-04-16 21:10:38,756] Trial 2 finished with value: 0.31659225727362256 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.31659225727362256.
Fold 1 IBS: 0.39773866349908654
Fold 2 IBS: 0.2743119777862917
Fold 3 IBS: 0.3961661307152118
Fold 4 IBS: 0.3296321075166942
Fold 5 IBS: 0.28422503781043656
[I 2024-04-16 21:10:48,297] Trial 3 finished with value: 0.3364147834655441 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.31659225727362256.
Fold 1 IBS: 0.39683250956936256
Fold 2 IBS: 0.28652657028378786
Fold 3 IBS: 0.4023919207619025
Fold 4 IBS: 0.32647824459606994
Fold 5 IBS: 0.30181048533051974
[I 2024-04-16 21:10:57,132] Trial 4 finished with value: 0.3428079461083285 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.31659225727362256.
Fold 1 IBS: 0.4000723875778648
Fold 2 IBS: 0.26444028962288274
Fold 3 IBS: 0.3864305985338133
Fold 4 IBS: 0.33382050988543943
Fold 5 IBS: 0.277738616173779
[I 2024-04-16 21:11:06,520] Trial 5 finished with value: 0.3325004803587558 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.31659225727362256.
Fold 1 IBS: 0.3953610543510329
Fold 2 IBS: 0.282330319084709
Fold 3 IBS: 0.4021644875063415
Fold 4 IBS: 0.3492003164977936
Fold 5 IBS: 0.3185436335197241
[I 2024-04-16 21:11:16,561] Trial 6 finished with value: 0.3495199621919202 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.31659225727362256.
Fold 1 IBS: 0.39675860622079756
Fold 2 IBS: 0.2859357871488773
Fold 3 IBS: 0.40267763025920994
Fold 4 IBS: 0.3260567880096057
Fold 5 IBS: 0.2980500697357925
[I 2024-04-16 21:11:29,288] Trial 7 finished with value: 0.3418957762748566 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.31659225727362256.
Fold 1 IBS: 0.3983981350335621
Fold 2 IBS: 0.26823191874755936
Fold 3 IBS: 0.3910374877065563
Fold 4 IBS: 0.3325696906848986
Fold 5 IBS: 0.28104424062156674
[I 2024-04-16 21:11:43,312] Trial 8 finished with value: 0.3342562945588286 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.31659225727362256.
Fold 1 IBS: 0.4004288493195767
Fold 2 IBS: 0.2621947663393821
Fold 3 IBS: 0.38327835210878863
Fold 4 IBS: 0.3345040051179568
Fold 5 IBS: 0.2761879716209747
[I 2024-04-16 21:12:07,336] Trial 9 finished with value: 0.3313187889013358 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.31659225727362256.
Fold 1 IBS: 0.38174205728887944
Fold 2 IBS: 0.23002167333173965
Fold 3 IBS: 0.22879704273681675
Fold 4 IBS: 0.23820909547246252
Fold 5 IBS: 0.22706312714542584
[I 2024-04-16 21:12:22,577] Trial 10 finished with value: 0.2611665991950648 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.2611665991950648.
Fold 1 IBS: 0.2468026820151547
Fold 2 IBS: 0.23171540001686725
Fold 3 IBS: 0.22894823619879978
Fold 4 IBS: 0.24126790542394344
Fold 5 IBS: 0.22899299963786818
[I 2024-04-16 21:12:30,449] Trial 11 finished with value: 0.23554544465852664 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 11 with value: 0.23554544465852664.
Fold 1 IBS: 0.24635438713032382
Fold 2 IBS: 0.23136622083619354
Fold 3 IBS: 0.22891360354458717
Fold 4 IBS: 0.24054637311783691
Fold 5 IBS: 0.22857493048709526
[I 2024-04-16 21:12:38,744] Trial 12 finished with value: 0.23515110302320735 and parameters: {'l1_ratio': 0.025939717088620355}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.2470774174000138
Fold 2 IBS: 0.2319186287389119
Fold 3 IBS: 0.22896914138963123
Fold 4 IBS: 0.2417093661502819
Fold 5 IBS: 0.22924306240682518
[I 2024-04-16 21:12:47,212] Trial 13 finished with value: 0.2357835232171328 and parameters: {'l1_ratio': 0.004533947374774427}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.39689764168490704
Fold 2 IBS: 0.2288302894133305
Fold 3 IBS: 0.22871971754050402
Fold 4 IBS: 0.319590259272256
Fold 5 IBS: 0.22580614705939556
[I 2024-04-16 21:12:54,346] Trial 14 finished with value: 0.2799688109940786 and parameters: {'l1_ratio': 0.14337364566668}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.24700380473252995
Fold 2 IBS: 0.23186513246037796
Fold 3 IBS: 0.22896358610284331
Fold 4 IBS: 0.24159162501985137
Fold 5 IBS: 0.22917630066438024
[I 2024-04-16 21:13:01,196] Trial 15 finished with value: 0.23572008979599657 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.4023655184451776
Fold 2 IBS: 0.22762971181087308
Fold 3 IBS: 0.35126243921582867
Fold 4 IBS: 0.32949784496435525
Fold 5 IBS: 0.26653013106458423
[I 2024-04-16 21:13:09,236] Trial 16 finished with value: 0.31545712910016377 and parameters: {'l1_ratio': 0.21332970570491078}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.4021181931549072
Fold 2 IBS: 0.2262075379083341
Fold 3 IBS: 0.37184050731559876
Fold 4 IBS: 0.3339664355264502
Fold 5 IBS: 0.27152952938348024
[I 2024-04-16 21:13:16,889] Trial 17 finished with value: 0.32113244065775415 and parameters: {'l1_ratio': 0.31307066649676046}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.3927553119799539
Fold 2 IBS: 0.22925367116567535
Fold 3 IBS: 0.22874408394796358
Fold 4 IBS: 0.2371550117840688
Fold 5 IBS: 0.22624782676386518
[I 2024-04-16 21:13:23,358] Trial 18 finished with value: 0.2628311811283054 and parameters: {'l1_ratio': 0.12120380780234859}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.38484296737504403
Fold 2 IBS: 0.2298538025614321
Fold 3 IBS: 0.2287845533218799
Fold 4 IBS: 0.23796625886665873
Fold 5 IBS: 0.226882896873239
[I 2024-04-16 21:13:31,381] Trial 19 finished with value: 0.2616660957996507 and parameters: {'l1_ratio': 0.09170436955756033}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.3969924629213248
Fold 2 IBS: 0.28621692662748216
Fold 3 IBS: 0.403357685352659
Fold 4 IBS: 0.34494367680452975
Fold 5 IBS: 0.3179504170502776
[I 2024-04-16 21:13:40,925] Trial 20 finished with value: 0.34989223375125467 and parameters: {'l1_ratio': 0.9656427853442138}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.24691227592009013
Fold 2 IBS: 0.23179785491571117
Fold 3 IBS: 0.2289566521237541
Fold 4 IBS: 0.24144547098197222
Fold 5 IBS: 0.22909278979404155
[I 2024-04-16 21:13:50,182] Trial 21 finished with value: 0.23564100874711383 and parameters: {'l1_ratio': 0.009107838351343097}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.2465763050941007
Fold 2 IBS: 0.2315418408025978
Fold 3 IBS: 0.22893081478850097
Fold 4 IBS: 0.2409084373886345
Fold 5 IBS: 0.22878344685247903
[I 2024-04-16 21:13:58,325] Trial 22 finished with value: 0.23534816898526262 and parameters: {'l1_ratio': 0.018997068950600285}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.40050501862493426
Fold 2 IBS: 0.22832798771922305
Fold 3 IBS: 0.2286956726158764
Fold 4 IBS: 0.32476471709856997
Fold 5 IBS: 0.2622138035663867
[I 2024-04-16 21:14:07,331] Trial 23 finished with value: 0.2889014399249981 and parameters: {'l1_ratio': 0.17128591911951985}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.40229195399571893
Fold 2 IBS: 0.22616850997652677
Fold 3 IBS: 0.37244843865116856
Fold 4 IBS: 0.33406141355438973
Fold 5 IBS: 0.27181329686582467
[I 2024-04-16 21:14:17,450] Trial 24 finished with value: 0.3213567226087258 and parameters: {'l1_ratio': 0.31612098478358897}. Best is trial 12 with value: 0.23515110302320735.

Fold 1 IBS: 0.38371001165015334
Fold 2 IBS: 0.22991305573774998
Fold 3 IBS: 0.22878890533246202
Fold 4 IBS: 0.23805110419288075
Fold 5 IBS: 0.22694636185590233
[I 2024-04-16 21:14:25,759] Trial 25 finished with value: 0.2614818877538297 and parameters: {'l1_ratio': 0.08890608406899088}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.40286382034066365
Fold 2 IBS: 0.22729127829046636
Fold 3 IBS: 0.35709880984522213
Fold 4 IBS: 0.33131391100887675
Fold 5 IBS: 0.26791531956834874
[I 2024-04-16 21:14:35,188] Trial 26 finished with value: 0.31729662781071555 and parameters: {'l1_ratio': 0.23521758130887002}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.3983048574647202
Fold 2 IBS: 0.29384151511158013
Fold 3 IBS: 0.41048543674537785
Fold 4 IBS: 0.33012863520732916
Fold 5 IBS: 0.31169105886780124
[I 2024-04-16 21:14:46,763] Trial 27 finished with value: 0.3488903006793617 and parameters: {'l1_ratio': 0.8345729974660353}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.24558302947229363
Fold 2 IBS: 0.2307136324356008
Fold 3 IBS: 0.22885352264482775
Fold 4 IBS: 0.23933987118637368
Fold 5 IBS: 0.22782502820921666
[I 2024-04-16 21:14:59,954] Trial 28 finished with value: 0.2344630167896625 and parameters: {'l1_ratio': 0.05293907552049415}. Best is trial 28 with value: 0.2344630167896625.
Fold 1 IBS: 0.396841306234471
Fold 2 IBS: 0.2786288550941939
Fold 3 IBS: 0.39800028724186237
Fold 4 IBS: 0.3279547686099267
Fold 5 IBS: 0.2888399763386184
[I 2024-04-16 21:15:10,941] Trial 29 finished with value: 0.3380530387038145 and parameters: {'l1_ratio': 0.5967051388615063}. Best is trial 28 with value: 0.2344630167896625.
Fold 1 IBS: 0.24494849865754695
Fold 2 IBS: 0.2301290908554374
Fold 3 IBS: 0.22880529056390944
Fold 4 IBS: 0.23836859800709898
Fold 5 IBS: 0.22717918075098062
[I 2024-04-16 21:15:35,341] Trial 30 finished with value: 0.2338861317669947 and parameters: {'l1_ratio': 0.07886834045222822}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24513344427327466
Fold 2 IBS: 0.23030374269744422
Fold 3 IBS: 0.2288191175119713
Fold 4 IBS: 0.238649165846887
Fold 5 IBS: 0.22736926005937755
[I 2024-04-16 21:16:19,862] Trial 31 finished with value: 0.23405494607779093 and parameters: {'l1_ratio': 0.07093726598033048}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.40099833998751705
Fold 2 IBS: 0.22820269243168786
Fold 3 IBS: 0.22869054385665208
Fold 4 IBS: 0.32576638212838605
Fold 5 IBS: 0.2631804824248817
[I 2024-04-16 21:16:52,500] Trial 32 finished with value: 0.289367688165825 and parameters: {'l1_ratio': 0.17854043677240342}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.38507242011024484
Fold 2 IBS: 0.22983982594679325
Fold 3 IBS: 0.2287835358209031
Fold 4 IBS: 0.23794638018681338
Fold 5 IBS: 0.22686794975252397
[I 2024-04-16 21:17:23,801] Trial 33 finished with value: 0.2617020223634557 and parameters: {'l1_ratio': 0.09236731347950938}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.40258125886284546
Fold 2 IBS: 0.22682729328210544
Fold 3 IBS: 0.36362722998285346
Fold 4 IBS: 0.33274166582427656
Fold 5 IBS: 0.269388578162038
[I 2024-04-16 21:17:56,882] Trial 34 finished with value: 0.31903320522282375 and parameters: {'l1_ratio': 0.2670118969882481}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24514081219715708
Fold 2 IBS: 0.23031062911015235
Fold 3 IBS: 0.2288196731147191
Fold 4 IBS: 0.23866044405898912
Fold 5 IBS: 0.2273768019382597
[I 2024-04-16 21:18:27,068] Trial 35 finished with value: 0.23406167208385548 and parameters: {'l1_ratio': 0.07062783658587385}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.39872962057212075
Fold 2 IBS: 0.22858679309236377
Fold 3 IBS: 0.22870737903742697
Fold 4 IBS: 0.3222553330822846
Fold 5 IBS: 0.22555431098068296
[I 2024-04-16 21:18:43,384] Trial 36 finished with value: 0.28076668735297583 and parameters: {'l1_ratio': 0.15667645398767704}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.4003788290002639
Fold 2 IBS: 0.2621271291887645
Fold 3 IBS: 0.38337847447877815
Fold 4 IBS: 0.3343967609033605
Fold 5 IBS: 0.27626803608343964
[I 2024-04-16 21:19:03,327] Trial 37 finished with value: 0.3313098459309213 and parameters: {'l1_ratio': 0.3955428254204711}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24528716536175832
Fold 2 IBS: 0.23044626408677757
Fold 3 IBS: 0.2288307746727856
Fold 4 IBS: 0.2388847319879204
Fold 5 IBS: 0.22752661044601727
[I 2024-04-16 21:19:16,388] Trial 38 finished with value: 0.23419510931105184 and parameters: {'l1_ratio': 0.06458318408815164}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.4012603112340106
Fold 2 IBS: 0.25841318455244183
Fold 3 IBS: 0.37794025431601436
Fold 4 IBS: 0.33395794236440984
Fold 5 IBS: 0.27358028856428407
[I 2024-04-16 21:19:30,238] Trial 39 finished with value: 0.3290303962062322 and parameters: {'l1_ratio': 0.35153102114871604}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.4025160326406887
Fold 2 IBS: 0.22753731969410154
Fold 3 IBS: 0.35276111953635814
Fold 4 IBS: 0.33009951251547587
Fold 5 IBS: 0.2668102932070434
[I 2024-04-16 21:19:44,590] Trial 40 finished with value: 0.3159448555187335 and parameters: {'l1_ratio': 0.21920161056929305}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24531025293335787
Fold 2 IBS: 0.2304674589760935
Fold 3 IBS: 0.22883253645209783
Fold 4 IBS: 0.2389201621472317
Fold 5 IBS: 0.22755011712049822
[I 2024-04-16 21:19:56,288] Trial 41 finished with value: 0.23421610552585587 and parameters: {'l1_ratio': 0.0636471141894898}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.39417872919819485
Fold 2 IBS: 0.22911090071764498
Fold 3 IBS: 0.22873546522679292
Fold 4 IBS: 0.236973588290887
Fold 5 IBS: 0.22609852596778068
[I 2024-04-16 21:20:07,029] Trial 42 finished with value: 0.2630194418802601 and parameters: {'l1_ratio': 0.1285481398109456}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24531684568268494
Fold 2 IBS: 0.2304735010807529
Fold 3 IBS: 0.2288330400145277
Fold 4 IBS: 0.2389302818717552
Fold 5 IBS: 0.22755682269301714
[I 2024-04-16 21:20:16,382] Trial 43 finished with value: 0.2342220982685476 and parameters: {'l1_ratio': 0.06338068170878226}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.40090311121010797
Fold 2 IBS: 0.22825259346733603
Fold 3 IBS: 0.22869254361956873
Fold 4 IBS: 0.32549955550254583
Fold 5 IBS: 0.2627241780059922
[I 2024-04-16 21:20:27,793] Trial 44 finished with value: 0.2892143963611101 and parameters: {'l1_ratio': 0.17563667169234978}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24540662920129078
Fold 2 IBS: 0.23055533327316544
Fold 3 IBS: 0.22883991768292566
Fold 4 IBS: 0.23906821143794535
Fold 5 IBS: 0.22764784004142619
[I 2024-04-16 21:22:06,379] Trial 45 finished with value: 0.23430358632735068 and parameters: {'l1_ratio': 0.05979028836034311}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.4025150553318858
Fold 2 IBS: 0.22691591342092246
Fold 3 IBS: 0.36249246496218573
Fold 4 IBS: 0.3322874584782998
Fold 5 IBS: 0.26929008347539435
[I 2024-04-16 21:22:28,110] Trial 46 finished with value: 0.31870019513373765 and parameters: {'l1_ratio': 0.2607709884409519}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.3989781843399096
Fold 2 IBS: 0.26696393218271514
Fold 3 IBS: 0.38934683991844204
Fold 4 IBS: 0.33294936087082094
Fold 5 IBS: 0.2798083764774972
[I 2024-04-16 21:28:30,347] Trial 47 finished with value: 0.333609338757877 and parameters: {'l1_ratio': 0.4610482911707774}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.39112840958521683
Fold 2 IBS: 0.22941110776485876
Fold 3 IBS: 0.22875404803782304
Fold 4 IBS: 0.2373599253115474
Fold 5 IBS: 0.22641323638175584
[I 2024-04-16 21:28:52,128] Trial 48 finished with value: 0.2626133454162404 and parameters: {'l1_ratio': 0.11325460052799155}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.4023793463989503
Fold 2 IBS: 0.22764020964966272
Fold 3 IBS: 0.35107641523364586
Fold 4 IBS: 0.32940663265197595
Fold 5 IBS: 0.266455371500264
[I 2024-04-16 21:29:11,054] Trial 49 finished with value: 0.3153915950868998 and parameters: {'l1_ratio': 0.21266731725822757}. Best is trial 30 with value: 0.2338861317669947.

Fold 1 IBS: 0.39768104529022175
Fold 2 IBS: 0.27478843392280616
Fold 3 IBS: 0.39610715327059925
Fold 4 IBS: 0.32930852997155785
Fold 5 IBS: 0.28466923297814606
[I 2024-04-16 21:29:17,955] Trial 50 finished with value: 0.3365108790866662 and parameters: {'l1_ratio': 0.556147470734502}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24527167584214757
Fold 2 IBS: 0.23043201333842706
Fold 3 IBS: 0.22882959418766094
Fold 4 IBS: 0.23886096933818587
Fold 5 IBS: 0.2275108188111229
[I 2024-04-16 21:29:24,367] Trial 51 finished with value: 0.23418101430350885 and parameters: {'l1_ratio': 0.06521384802113693}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24563902210807548
Fold 2 IBS: 0.23076318528471024
Fold 3 IBS: 0.228857861655577
Fold 4 IBS: 0.23942629816028696
Fold 5 IBS: 0.22788081987002892
[I 2024-04-16 21:29:29,964] Trial 52 finished with value: 0.2345134374157357 and parameters: {'l1_ratio': 0.05081950410384198}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.39316825376361525
Fold 2 IBS: 0.22920966718361796
Fold 3 IBS: 0.22874138478163542
Fold 4 IBS: 0.23709865971363686
Fold 5 IBS: 0.22620182493461968
[I 2024-04-16 21:29:36,368] Trial 53 finished with value: 0.26288395807542503 and parameters: {'l1_ratio': 0.12345350764209984}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24588206482898078
Fold 2 IBS: 0.2309743489968181
Fold 3 IBS: 0.22887677129367584
Fold 4 IBS: 0.2398026976439158
Fold 5 IBS: 0.22812049573090087
[I 2024-04-16 21:29:45,054] Trial 54 finished with value: 0.2347312756988583 and parameters: {'l1_ratio': 0.04191802294631253}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.4017024816993482
Fold 2 IBS: 0.22800891739207346
Fold 3 IBS: 0.22868332539730385
Fold 4 IBS: 0.32745794812554657
Fold 5 IBS: 0.264364982045845
[I 2024-04-16 21:29:51,684] Trial 55 finished with value: 0.2900435309320234 and parameters: {'l1_ratio': 0.19000268981738272}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24487630117444
Fold 2 IBS: 0.23005998909999223
Fold 3 IBS: 0.22879996205090686
Fold 4 IBS: 0.23826561048773492
Fold 5 IBS: 0.22710445523870026
[I 2024-04-16 21:29:59,686] Trial 56 finished with value: 0.23382126361035485 and parameters: {'l1_ratio': 0.0820512824935705}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.3891738464089421
Fold 2 IBS: 0.22957821255734792
Fold 3 IBS: 0.22876513907897691
Fold 4 IBS: 0.2375833449213778
Fold 5 IBS: 0.22658966414192405
[I 2024-04-16 21:30:07,737] Trial 57 finished with value: 0.26233804142171374 and parameters: {'l1_ratio': 0.10498380549952754}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.3980158740192718
Fold 2 IBS: 0.22869123089454899
Fold 3 IBS: 0.22871251684974334
Fold 4 IBS: 0.3212310152856946
Fold 5 IBS: 0.22566213037685862
[I 2024-04-16 21:30:16,839] Trial 58 finished with value: 0.2804625534852235 and parameters: {'l1_ratio': 0.15091949362265406}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.24696119391640517
Fold 2 IBS: 0.23183391703362632
Fold 3 IBS: 0.22896036158195493
Fold 4 IBS: 0.2415235813263066
Fold 5 IBS: 0.22913749166918668
[I 2024-04-16 21:30:27,155] Trial 59 finished with value: 0.2356833091054959 and parameters: {'l1_ratio': 0.007735984288532609}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.39655250268543946
Fold 2 IBS: 0.28653324028646754
Fold 3 IBS: 0.402599348203438
Fold 4 IBS: 0.3256868297418602
Fold 5 IBS: 0.300519369698263
[I 2024-04-16 21:30:43,015] Trial 60 finished with value: 0.34237825812309364 and parameters: {'l1_ratio': 0.7056326782501279}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.2449544685049419
Fold 2 IBS: 0.23013478176355218
Fold 3 IBS: 0.22880573302077792
Fold 4 IBS: 0.2383771415952901
Fold 5 IBS: 0.22718534603689539
[I 2024-04-16 21:30:52,072] Trial 61 finished with value: 0.2338914941842915 and parameters: {'l1_ratio': 0.0786073560111757}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.3852839123924755
Fold 2 IBS: 0.22983354113184987
Fold 3 IBS: 0.22878307941541867
Fold 4 IBS: 0.2379374579712239
Fold 5 IBS: 0.22686123133842037
[I 2024-04-16 21:30:59,149] Trial 62 finished with value: 0.26173984444987763 and parameters: {'l1_ratio': 0.09266577790133239}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.39605886399813145
Fold 2 IBS: 0.2289096970007676
Fold 3 IBS: 0.2287240105943408
Fold 4 IBS: 0.318764757756615
Fold 5 IBS: 0.2258886362141153
[I 2024-04-16 21:31:06,813] Trial 63 finished with value: 0.27966919311279403 and parameters: {'l1_ratio': 0.13912461982063118}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.24614213304821814
Fold 2 IBS: 0.2311931601074125
Fold 3 IBS: 0.22889706483937514
Fold 4 IBS: 0.24020806072796752
Fold 5 IBS: 0.2283725372934332
[I 2024-04-16 21:31:14,624] Trial 64 finished with value: 0.23496259120328128 and parameters: {'l1_ratio': 0.0329116162908697}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.24486542637889328
Fold 2 IBS: 0.2300495363842797
Fold 3 IBS: 0.22879916314344928
Fold 4 IBS: 0.238250151672611
Fold 5 IBS: 0.22709317337996893
[I 2024-04-16 21:31:22,251] Trial 65 finished with value: 0.2338114901918404 and parameters: {'l1_ratio': 0.08253500705829862}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.2472294817360726
Fold 2 IBS: 0.23202742671939489
Fold 3 IBS: 0.2289805519729031
Fold 4 IBS: 0.2419476118616087
Fold 5 IBS: 0.22937984332126538
[I 2024-04-16 21:31:28,840] Trial 66 finished with value: 0.23591298312224893 and parameters: {'l1_ratio': 0.00046316324187258007}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.39789400277016324
Fold 2 IBS: 0.29089944105745374
Fold 3 IBS: 0.4058587722878609
Fold 4 IBS: 0.3278804878322529
Fold 5 IBS: 0.30799360963657124
[I 2024-04-16 21:31:36,661] Trial 67 finished with value: 0.3461052627168604 and parameters: {'l1_ratio': 0.7965604964350725}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.38207928991807666
Fold 2 IBS: 0.2299983271442161
Fold 3 IBS: 0.22879527638559358
Fold 4 IBS: 0.23817486276027341
Fold 5 IBS: 0.22703798152095866
[I 2024-04-16 21:31:43,496] Trial 68 finished with value: 0.2612171475458237 and parameters: {'l1_ratio': 0.084913469611982}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.4019480535889712
Fold 2 IBS: 0.2279107459848376
Fold 3 IBS: 0.3473682508083695
Fold 4 IBS: 0.32801874414289844
Fold 5 IBS: 0.26492599595310207
[I 2024-04-16 21:31:50,503] Trial 69 finished with value: 0.31403435809563573 and parameters: {'l1_ratio': 0.19592562383994028}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.4025892485141384
Fold 2 IBS: 0.22704226979070136
Fold 3 IBS: 0.36076253147264054
Fold 4 IBS: 0.33220591813983996
Fold 5 IBS: 0.268751038843246
[I 2024-04-16 21:31:57,882] Trial 70 finished with value: 0.31827020135211326 and parameters: {'l1_ratio': 0.25201254783065224}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.24524831401051891
Fold 2 IBS: 0.2304104737544906
Fold 3 IBS: 0.22882781616090025
Fold 4 IBS: 0.23882514248722972
Fold 5 IBS: 0.22748700513163977
[I 2024-04-16 21:32:05,206] Trial 71 finished with value: 0.23415975030895586 and parameters: {'l1_ratio': 0.06616903992478125}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.2461529633894722
Fold 2 IBS: 0.231202110978217
Fold 3 IBS: 0.2288979097876805
Fold 4 IBS: 0.24022500767108396
Fold 5 IBS: 0.22838293577212765
[I 2024-04-16 21:32:14,316] Trial 72 finished with value: 0.23497218551971627 and parameters: {'l1_ratio': 0.0325477863280557}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.39762848967678505
Fold 2 IBS: 0.22874143621723084
Fold 3 IBS: 0.22871506956265172
Fold 4 IBS: 0.3207739054174677
Fold 5 IBS: 0.2257140636868955
[I 2024-04-16 21:32:22,803] Trial 73 finished with value: 0.2803145929122062 and parameters: {'l1_ratio': 0.14817957619214692}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.3898669880095656
Fold 2 IBS: 0.22952597100043157
Fold 3 IBS: 0.22876161553527383
Fold 4 IBS: 0.23751281846843927
Fold 5 IBS: 0.2265344060477725
[I 2024-04-16 21:32:30,549] Trial 74 finished with value: 0.2624403598122965 and parameters: {'l1_ratio': 0.1075513701449365}. Best is trial 65 with value: 0.2338114901918404.

Fold 1 IBS: 0.24502298791627394
Fold 2 IBS: 0.23019984637955831
Fold 3 IBS: 0.22881083058401447
Fold 4 IBS: 0.23848030996038092
Fold 5 IBS: 0.22725595943412547
[I 2024-04-16 21:32:37,088] Trial 75 finished with value: 0.23395398685487062 and parameters: {'l1_ratio': 0.07563581400941731}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.39470143336903885
Fold 2 IBS: 0.22905991597084543
Fold 3 IBS: 0.22873248532776408
Fold 4 IBS: 0.2369097692969695
Fold 5 IBS: 0.2260452207998657
[I 2024-04-16 21:32:43,736] Trial 76 finished with value: 0.2630897649528967 and parameters: {'l1_ratio': 0.13120285166575224}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.4022362600841385
Fold 2 IBS: 0.2263144117931058
Fold 3 IBS: 0.37046848132770543
Fold 4 IBS: 0.3338040954427133
Fold 5 IBS: 0.27147653458970394
[I 2024-04-16 21:32:51,672] Trial 77 finished with value: 0.32085995664747335 and parameters: {'l1_ratio': 0.3048122805041498}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.3837026756955222
Fold 2 IBS: 0.2299136541773637
Fold 3 IBS: 0.22878894960195015
Fold 4 IBS: 0.23805196586516209
Fold 5 IBS: 0.22694700365147447
[I 2024-04-16 21:32:59,733] Trial 78 finished with value: 0.2614808497982945 and parameters: {'l1_ratio': 0.08887792272875211}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.24624359124824416
Fold 2 IBS: 0.2312765043185076
Fold 3 IBS: 0.2289049767182452
Fold 4 IBS: 0.24036820381747587
Fold 5 IBS: 0.2284696479753556
[I 2024-04-16 21:33:07,347] Trial 79 finished with value: 0.2350525848155657 and parameters: {'l1_ratio': 0.029537618413726166}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.39628764965438684
Fold 2 IBS: 0.2819611402213368
Fold 3 IBS: 0.3999635931605525
Fold 4 IBS: 0.32715365611281555
Fold 5 IBS: 0.29303800550820847
[I 2024-04-16 21:33:16,878] Trial 80 finished with value: 0.3396808089314601 and parameters: {'l1_ratio': 0.641468837353442}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.24515065232860303
Fold 2 IBS: 0.23031981754355155
Fold 3 IBS: 0.2288204156650724
Fold 4 IBS: 0.238675508445124
Fold 5 IBS: 0.22738686932854985
[I 2024-04-16 21:33:36,300] Trial 81 finished with value: 0.23407065266218016 and parameters: {'l1_ratio': 0.07021535375765953}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.3996305230077916
Fold 2 IBS: 0.2284608459022606
Fold 3 IBS: 0.22870149737516768
Fold 4 IBS: 0.3234955340185905
Fold 5 IBS: 0.22542464334452236
[I 2024-04-16 21:33:54,536] Trial 82 finished with value: 0.28114260872966657 and parameters: {'l1_ratio': 0.16372407392678778}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.2450098475667694
Fold 2 IBS: 0.23018740480544045
Fold 3 IBS: 0.2288098503165454
Fold 4 IBS: 0.23846020707890095
Fold 5 IBS: 0.2272424388038213
[I 2024-04-16 21:34:09,697] Trial 83 finished with value: 0.23394194971429552 and parameters: {'l1_ratio': 0.07620228344148919}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.39169113548220624
Fold 2 IBS: 0.22935996975968273
Fold 3 IBS: 0.2287507593190964
Fold 4 IBS: 0.23729278948660673
Fold 5 IBS: 0.22635942785332522
[I 2024-04-16 21:34:18,876] Trial 84 finished with value: 0.26269081638018343 and parameters: {'l1_ratio': 0.11581970513962662}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.245070914203763
Fold 2 IBS: 0.23024507741977812
Fold 3 IBS: 0.2288144161808295
Fold 4 IBS: 0.23855365628101657
Fold 5 IBS: 0.22730521970613052
[I 2024-04-16 21:34:28,063] Trial 85 finished with value: 0.23399785675830356 and parameters: {'l1_ratio': 0.0735833348347236}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.24605330959186697
Fold 2 IBS: 0.23111926323241658
Fold 3 IBS: 0.22889013320742585
Fold 4 IBS: 0.240069279929389
Fold 5 IBS: 0.22828696300794135
[I 2024-04-16 21:34:35,639] Trial 86 finished with value: 0.23488378979380795 and parameters: {'l1_ratio': 0.03592901511061927}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.4015897163369197
Fold 2 IBS: 0.2280402739083491
Fold 3 IBS: 0.22868443382099882
Fold 4 IBS: 0.32722777547213006
Fold 5 IBS: 0.2640017694924091
[I 2024-04-16 21:34:43,782] Trial 87 finished with value: 0.28990879380616136 and parameters: {'l1_ratio': 0.18812747562021762}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.24485796940712803
Fold 2 IBS: 0.23004236218331026
Fold 3 IBS: 0.22879861590151068
Fold 4 IBS: 0.23823955951440573
Fold 5 IBS: 0.22708543331173908
[I 2024-04-16 21:34:51,197] Trial 88 finished with value: 0.2338047880636188 and parameters: {'l1_ratio': 0.08286735522305856}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.38983627197933146
Fold 2 IBS: 0.22952829696027713
Fold 3 IBS: 0.22876177133432515
Fold 4 IBS: 0.23751594517841412
Fold 5 IBS: 0.2265368642759217
[I 2024-04-16 21:34:58,123] Trial 89 finished with value: 0.26243582994565395 and parameters: {'l1_ratio': 0.10743670615366892}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.3987863563632677
Fold 2 IBS: 0.29515032654001966
Fold 3 IBS: 0.4101610717242091
Fold 4 IBS: 0.3393927204413599
Fold 5 IBS: 0.31798093760617757
[I 2024-04-16 21:35:08,062] Trial 90 finished with value: 0.3522942825350067 and parameters: {'l1_ratio': 0.9345250358538123}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.2450529620213023
Fold 2 IBS: 0.23022816184128844
Fold 3 IBS: 0.22881307122854827
Fold 4 IBS: 0.23852617747302599
Fold 5 IBS: 0.22728676309883497
[I 2024-04-16 21:35:16,321] Trial 91 finished with value: 0.2339814271326 and parameters: {'l1_ratio': 0.07434965932755738}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.39660777480166703
Fold 2 IBS: 0.2288556104020036
Fold 3 IBS: 0.22872107230154076
Fold 4 IBS: 0.3193462704256365
Fold 5 IBS: 0.2258324302422724
[I 2024-04-16 21:35:24,135] Trial 92 finished with value: 0.279872631634624 and parameters: {'l1_ratio': 0.14201406309306291}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.24653407405367828
Fold 2 IBS: 0.23150883900276614
Fold 3 IBS: 0.2289275481669748
Fold 4 IBS: 0.24083958522406043
Fold 5 IBS: 0.22874400522700003
[I 2024-04-16 21:35:30,964] Trial 93 finished with value: 0.23531081033489593 and parameters: {'l1_ratio': 0.02029171095338489}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.24579052639803933
Fold 2 IBS: 0.2308955700653028
Fold 3 IBS: 0.22886963796329246
Fold 4 IBS: 0.23966068067617854
Fold 5 IBS: 0.22803069901035003
[I 2024-04-16 21:35:38,765] Trial 94 finished with value: 0.23464942282263263 and parameters: {'l1_ratio': 0.04521438120033323}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.3832308203771165
Fold 2 IBS: 0.22993940507304436
Fold 3 IBS: 0.22879086047024366
Fold 4 IBS: 0.23808913493674821
Fold 5 IBS: 0.22697463596229936
[I 2024-04-16 21:35:47,214] Trial 95 finished with value: 0.2614049713638904 and parameters: {'l1_ratio': 0.08766803257022107}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.39338087454015325
Fold 2 IBS: 0.2291828809241768
Fold 3 IBS: 0.22873976031593662
Fold 4 IBS: 0.23706454827739398
Fold 5 IBS: 0.22617394584411757
[I 2024-04-16 21:35:56,396] Trial 96 finished with value: 0.26290840198035564 and parameters: {'l1_ratio': 0.12482900348100745}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.24567585887422888
Fold 2 IBS: 0.23079560157484277
Fold 3 IBS: 0.22886072056657633
Fold 4 IBS: 0.23948321316747923
Fold 5 IBS: 0.22791740649183762
[I 2024-04-16 21:36:05,601] Trial 97 finished with value: 0.23454656013499298 and parameters: {'l1_ratio': 0.04943931135909188}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.4003471368560914
Fold 2 IBS: 0.22836491712647833
Fold 3 IBS: 0.22869725209951716
Fold 4 IBS: 0.3243654948875677
Fold 5 IBS: 0.26199065086086337
[I 2024-04-16 21:36:13,337] Trial 98 finished with value: 0.2887530903661036 and parameters: {'l1_ratio': 0.1691706843036525}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.247199841363947
Fold 2 IBS: 0.23200639962237068
Fold 3 IBS: 0.22897833500605416
Fold 4 IBS: 0.24190171038601244
Fold 5 IBS: 0.2293533012639731
[I 2024-04-16 21:36:21,650] Trial 99 finished with value: 0.23588791752847146 and parameters: {'l1_ratio': 0.0012462919331408112}. Best is trial 88 with value: 0.2338047880636188.


* Best trial for IBS:
 FrozenTrial(number=88, state=TrialState.COMPLETE, values=[0.2338047880636188], datetime_start=datetime.datetime(2024, 4, 16, 21, 34, 43, 789290), datetime_complete=datetime.datetime(2024, 4, 16, 21, 34, 51, 196554), params={'l1_ratio': 0.08286735522305856}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=88, value=None)


* Best Score for IBS:
 0.2338047880636188

In [78]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [79]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.641
train_ibs:  0.234

#### Test

In [80]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [81]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.02546295954223466)

test_cindex : 0.527

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.08286735522305856)

test_ibs:  0.229

In [82]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [83]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 21:36:21,970] A new study created in memory with name: no-name-393da273-6c70-48cb-a6b7-e41ead23b7a3

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 21:36:48,796] Trial 0 finished with value: 0.6887600217317204 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.5321888412017167
[I 2024-04-16 21:36:53,431] Trial 1 finished with value: 0.6166380389955435 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 21:36:56,980] Trial 2 finished with value: 0.62549226208284 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:36:57,774] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:36:58,819] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 21:37:04,773] Trial 5 finished with value: 0.6152561447305711 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 21:37:26,993] Trial 6 finished with value: 0.6539398109744831 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:37:28,791] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.45493562231759654
[I 2024-04-16 21:37:36,035] Trial 8 finished with value: 0.4909871244635193 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.5064377682403434
[I 2024-04-16 21:37:41,323] Trial 9 finished with value: 0.5980152878848332 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:37:41,693] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 21:37:57,428] Trial 11 finished with value: 0.6475023250639829 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.4182289452010553, 'max_features': None, 'min_weight_fraction_leaf': 0.14354804402122565, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:38:04,233] Trial 12 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.4725186573284777, 'max_features': None, 'min_weight_fraction_leaf': 0.42991693404730996, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 21:38:15,412] Trial 13 finished with value: 0.6848917982857154 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 15, 'n_estimators': 140, 'oob_score': True, 'max_samples': 0.765021860726683, 'max_features': None, 'min_weight_fraction_leaf': 0.20108807339664914, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 21:38:16,056] Trial 14 finished with value: 0.7054382711677689 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.7873021337102564, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17530903073562382, 'warm_start': True}. Best is trial 14 with value: 0.7054382711677689.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 21:38:16,454] Trial 15 finished with value: 0.7004658341847222 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 45, 'oob_score': True, 'max_samples': 0.7842656506469521, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21467510010373286, 'warm_start': True}. Best is trial 14 with value: 0.7054382711677689.

Fold 1 C-index: 0.4203187250996016
Fold 2 C-index: 0.6996124031007752
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.564638783269962
Fold 5 C-index: 0.6330472103004292
[I 2024-04-16 21:38:16,868] Trial 16 finished with value: 0.6103319349924515 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 4, 'oob_score': True, 'max_samples': 0.8500299963488761, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3855568975046046, 'warm_start': True}. Best is trial 14 with value: 0.7054382711677689.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7467811158798283
[I 2024-04-16 21:38:17,877] Trial 17 finished with value: 0.7340377976614955 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 96, 'oob_score': True, 'max_samples': 0.9816256083986692, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10458249310616385, 'warm_start': True}. Best is trial 17 with value: 0.7340377976614955.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:38:18,708] Trial 18 finished with value: 0.6851322075080448 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09529552899934571, 'warm_start': True}. Best is trial 17 with value: 0.7340377976614955.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.759656652360515
[I 2024-04-16 21:38:19,689] Trial 19 finished with value: 0.7320533243959054 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.9945689686268684, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06762043908551946, 'warm_start': True}. Best is trial 17 with value: 0.7340377976614955.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 21:38:21,209] Trial 20 finished with value: 0.7515482174710945 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 171, 'oob_score': True, 'max_samples': 0.9966629277234803, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06330216271601999, 'warm_start': True}. Best is trial 20 with value: 0.7515482174710945.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 21:38:22,484] Trial 21 finished with value: 0.7546701877723911 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.9639969203071097, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07844908418015549, 'warm_start': True}. Best is trial 21 with value: 0.7546701877723911.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 21:38:24,164] Trial 22 finished with value: 0.7403034664958661 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 203, 'oob_score': True, 'max_samples': 0.8676148902287203, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.005137686000517033, 'warm_start': True}. Best is trial 21 with value: 0.7546701877723911.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.8025751072961373
[I 2024-04-16 21:38:25,692] Trial 23 finished with value: 0.7563113263464099 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 195, 'oob_score': True, 'max_samples': 0.869669997416516, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0023497522601186316, 'warm_start': True}. Best is trial 23 with value: 0.7563113263464099.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 21:38:27,286] Trial 24 finished with value: 0.7606536985757444 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 169, 'oob_score': True, 'max_samples': 0.8640315509178289, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07916170845060883, 'warm_start': True}. Best is trial 24 with value: 0.7606536985757444.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 21:38:29,338] Trial 25 finished with value: 0.7695297572413502 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 233, 'oob_score': True, 'max_samples': 0.8486986257893505, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0009444354266301414, 'warm_start': True}. Best is trial 25 with value: 0.7695297572413502.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8283261802575107
[I 2024-04-16 21:38:31,431] Trial 26 finished with value: 0.7733467661208285 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.6912922503777362, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030529967348810284, 'warm_start': True}. Best is trial 26 with value: 0.7733467661208285.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 21:38:33,746] Trial 27 finished with value: 0.7847011373516671 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 327, 'oob_score': True, 'max_samples': 0.6826933317259629, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04163461906296005, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 21:38:35,558] Trial 28 finished with value: 0.7626451966882999 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 233, 'oob_score': True, 'max_samples': 0.6790845875969467, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1346390093951372, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 21:38:37,660] Trial 29 finished with value: 0.7524072808207946 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 321, 'oob_score': True, 'max_samples': 0.5460873722581808, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04113891562651206, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 21:38:40,084] Trial 30 finished with value: 0.6881258758502385 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 359, 'oob_score': True, 'max_samples': 0.7127914138629038, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2486312042554125, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.

Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 21:38:41,736] Trial 31 finished with value: 0.7493720402953852 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.6565648650889025, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14061763521617526, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 21:38:43,484] Trial 32 finished with value: 0.7736293479949021 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 241, 'oob_score': True, 'max_samples': 0.717337635186249, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11772473625239274, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.9141630901287554
[I 2024-04-16 21:38:45,999] Trial 33 finished with value: 0.811548824267636 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 272, 'oob_score': True, 'max_samples': 0.7247276784505238, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03689864626175683, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8412017167381974
[I 2024-04-16 21:38:48,383] Trial 34 finished with value: 0.7829876832219352 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.7198178767085571, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11161272848170577, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 21:38:49,372] Trial 35 finished with value: 0.6912157648511975 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.5459623200293144, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18558790111621754, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8326180257510729
[I 2024-04-16 21:38:52,564] Trial 36 finished with value: 0.7867216702362756 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 326, 'oob_score': True, 'max_samples': 0.7338075895235944, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11281996673704411, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.721030042918455
[I 2024-04-16 21:38:54,199] Trial 37 finished with value: 0.7233721608611505 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 391, 'oob_score': False, 'max_samples': 0.6085366031970421, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16279221402739244, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.9012875536480687
[I 2024-04-16 21:38:56,618] Trial 38 finished with value: 0.8026868253099897 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.810357312668476, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10446792179794386, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 21:38:58,307] Trial 39 finished with value: 0.8315228203891329 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 317, 'oob_score': False, 'max_samples': 0.8176202594483816, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05127851337193651, 'warm_start': True}. Best is trial 39 with value: 0.8315228203891329.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 21:38:59,574] Trial 40 finished with value: 0.7216554226637257 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.7959580927210158, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2448692090849676, 'warm_start': True}. Best is trial 39 with value: 0.8315228203891329.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 21:39:01,334] Trial 41 finished with value: 0.835684247914353 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.8200079355774805, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.045375207069811796, 'warm_start': True}. Best is trial 41 with value: 0.835684247914353.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.9227467811158798
[I 2024-04-16 21:39:02,985] Trial 42 finished with value: 0.8179194749278222 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 305, 'oob_score': False, 'max_samples': 0.9273819199836401, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08150372432531681, 'warm_start': True}. Best is trial 41 with value: 0.835684247914353.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.944206008583691
[I 2024-04-16 21:39:04,626] Trial 43 finished with value: 0.8427105605974863 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.9388551492979577, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05266231183563491, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 21:39:06,254] Trial 44 finished with value: 0.8323518578595712 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 295, 'oob_score': False, 'max_samples': 0.9237895859439657, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05612306340851575, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 21:39:07,777] Trial 45 finished with value: 0.830280628369804 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 301, 'oob_score': False, 'max_samples': 0.9104218782867626, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06634160384660395, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.

Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 21:39:19,369] Trial 46 finished with value: 0.6286099736434962 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 383, 'oob_score': False, 'max_samples': 0.91240298039898, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05822950436150222, 'warm_start': False}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 21:39:21,270] Trial 47 finished with value: 0.8325077461103134 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 298, 'oob_score': False, 'max_samples': 0.9355514430804484, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.020042410067937978, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.46613545816733065
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 21:39:32,563] Trial 48 finished with value: 0.6009684370641499 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 427, 'oob_score': False, 'max_samples': 0.823645744803961, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01683251340101157, 'warm_start': False}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.944206008583691
[I 2024-04-16 21:39:35,235] Trial 49 finished with value: 0.8388530534749343 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.953849061764575, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.050119666582895114, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 21:39:38,059] Trial 50 finished with value: 0.7812978402712039 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 367, 'oob_score': False, 'max_samples': 0.944966006745767, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.026515719222611322, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.9184549356223176
[I 2024-04-16 21:39:39,630] Trial 51 finished with value: 0.8245657831536615 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.8927024859362178, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.050579232359344195, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.9227467811158798
[I 2024-04-16 21:39:41,455] Trial 52 finished with value: 0.8163869819364665 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.957013350431845, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08747379737293745, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 21:39:43,519] Trial 53 finished with value: 0.835655340129135 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 415, 'oob_score': False, 'max_samples': 0.9059004636526794, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02247138851000744, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 21:39:47,049] Trial 54 finished with value: 0.8325767347157822 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 471, 'oob_score': False, 'max_samples': 0.9045683245877397, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01863439664769996, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.927038626609442
[I 2024-04-16 21:39:51,908] Trial 55 finished with value: 0.8196868832821158 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.8913844051686941, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.020495893741253532, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.51931330472103
[I 2024-04-16 21:40:02,881] Trial 56 finished with value: 0.6133741946644458 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.959688406147559, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.29669443075161894, 'warm_start': False}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 21:40:05,948] Trial 57 finished with value: 0.8237721374995439 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 415, 'oob_score': False, 'max_samples': 0.7632151618163023, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01760206529138649, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:40:07,798] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 455, 'oob_score': False, 'max_samples': 0.8443244755845074, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 21:40:09,529] Trial 59 finished with value: 0.6869742749526709 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 477, 'oob_score': False, 'max_samples': 0.3824901058813928, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1265828087269749, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.46215139442231074
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 21:40:37,015] Trial 60 finished with value: 0.6218319311565197 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 426, 'oob_score': False, 'max_samples': 0.13319246988341354, 'max_features': None, 'min_weight_fraction_leaf': 0.00239012916342312, 'warm_start': False}. Best is trial 43 with value: 0.8427105605974863.

Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 21:40:39,741] Trial 61 finished with value: 0.831772489711018 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 393, 'oob_score': False, 'max_samples': 0.9227017110627658, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06216084192304142, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 21:40:42,217] Trial 62 finished with value: 0.8356736421434732 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.8850956833773682, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03863615331212726, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.944206008583691
[I 2024-04-16 21:40:46,162] Trial 63 finished with value: 0.8371544903050128 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.8853130778846439, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03966154422786905, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.9227467811158798
[I 2024-04-16 21:40:49,484] Trial 64 finished with value: 0.8196654077526582 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.8851895285643775, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09142295253878854, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.944206008583691
[I 2024-04-16 21:40:52,827] Trial 65 finished with value: 0.8474444748453905 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 441, 'oob_score': False, 'max_samples': 0.9873533850424658, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04287202412707603, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9484978540772532
[I 2024-04-16 21:40:57,419] Trial 66 finished with value: 0.8435072299253937 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.9947311488203058, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04006148809996164, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9527896995708155
[I 2024-04-16 21:42:06,580] Trial 67 finished with value: 0.8388932548617867 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 433, 'oob_score': False, 'max_samples': 0.993658937532094, 'max_features': None, 'min_weight_fraction_leaf': 0.040436540638610116, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9484978540772532
[I 2024-04-16 21:42:40,265] Trial 68 finished with value: 0.8382846820717941 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 438, 'oob_score': False, 'max_samples': 0.9994331375177823, 'max_features': None, 'min_weight_fraction_leaf': 0.07188437817902898, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9531914893617022
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 21:43:08,550] Trial 69 finished with value: 0.8375560102421463 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 438, 'oob_score': False, 'max_samples': 0.9996362451167412, 'max_features': None, 'min_weight_fraction_leaf': 0.07337892913174533, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9484978540772532
[I 2024-04-16 21:43:40,951] Trial 70 finished with value: 0.8382846820717941 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.9959834334340328, 'max_features': None, 'min_weight_fraction_leaf': 0.07185098947134154, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.948936170212766
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 21:44:10,497] Trial 71 finished with value: 0.836704946412359 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 442, 'oob_score': False, 'max_samples': 0.9969458887289653, 'max_features': None, 'min_weight_fraction_leaf': 0.07306969695088597, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 21:44:30,895] Trial 72 finished with value: 0.8428910714445162 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 403, 'oob_score': False, 'max_samples': 0.9705326205407735, 'max_features': None, 'min_weight_fraction_leaf': 0.09726369000634277, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9184549356223176
[I 2024-04-16 21:44:54,709] Trial 73 finished with value: 0.8347457235953728 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 403, 'oob_score': False, 'max_samples': 0.9622083984206554, 'max_features': None, 'min_weight_fraction_leaf': 0.10090208352548545, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8927038626609443
[I 2024-04-16 21:45:12,419] Trial 74 finished with value: 0.8233007612427727 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.9751692801795903, 'max_features': None, 'min_weight_fraction_leaf': 0.15896417018836817, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7553648068669528
[I 2024-04-16 21:45:19,298] Trial 75 finished with value: 0.7521199937305012 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 481, 'oob_score': False, 'max_samples': 0.9753592654341334, 'max_features': None, 'min_weight_fraction_leaf': 0.35481417747069804, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.927038626609442
[I 2024-04-16 21:45:44,516] Trial 76 finished with value: 0.8372771691473451 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.9488752737712128, 'max_features': None, 'min_weight_fraction_leaf': 0.0946162304034015, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.9055793991416309
[I 2024-04-16 21:46:03,402] Trial 77 finished with value: 0.8330617609492732 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.9819615930431459, 'max_features': None, 'min_weight_fraction_leaf': 0.12149124274513819, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 21:46:30,334] Trial 78 finished with value: 0.8366834708829012 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.9466630798470281, 'max_features': None, 'min_weight_fraction_leaf': 0.07869379995443634, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8927038626609443
[I 2024-04-16 21:46:50,444] Trial 79 finished with value: 0.8280562944412313 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.9762362824615723, 'max_features': None, 'min_weight_fraction_leaf': 0.1438601153670844, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 21:50:25,400] Trial 80 finished with value: 0.6335124296425151 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 498, 'oob_score': False, 'max_samples': 0.9981652642996742, 'max_features': None, 'min_weight_fraction_leaf': 0.05275254415427701, 'warm_start': False}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9484978540772532
[I 2024-04-16 21:50:55,180] Trial 81 finished with value: 0.8391141269510269 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.9979035111091495, 'max_features': None, 'min_weight_fraction_leaf': 0.0684721968600143, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 21:51:15,996] Trial 82 finished with value: 0.8390591716052278 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 430, 'oob_score': False, 'max_samples': 0.9394916145721695, 'max_features': None, 'min_weight_fraction_leaf': 0.08885679941630156, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.4701195219123506
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9656652360515021
[I 2024-04-16 21:51:51,320] Trial 83 finished with value: 0.8358037897038839 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 405, 'oob_score': False, 'max_samples': 0.9369494626132739, 'max_features': None, 'min_weight_fraction_leaf': 0.03228804063616034, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.948936170212766
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 21:52:11,422] Trial 84 finished with value: 0.8413843291575205 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.9632963350821008, 'max_features': None, 'min_weight_fraction_leaf': 0.08645608734851228, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.9227467811158798
[I 2024-04-16 21:52:28,356] Trial 85 finished with value: 0.8340869044915674 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.8445466446433496, 'max_features': None, 'min_weight_fraction_leaf': 0.09405144363135096, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 21:52:51,668] Trial 86 finished with value: 0.8372383598562632 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 350, 'oob_score': False, 'max_samples': 0.9593020592230249, 'max_features': None, 'min_weight_fraction_leaf': 0.062345011421902685, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.9184549356223176
[I 2024-04-16 21:53:14,008] Trial 87 finished with value: 0.830877610701941 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.9299549183842758, 'max_features': None, 'min_weight_fraction_leaf': 0.10663286795016572, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.927038626609442
[I 2024-04-16 21:53:33,148] Trial 88 finished with value: 0.8357167430437187 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 384, 'oob_score': False, 'max_samples': 0.8678400525803166, 'max_features': None, 'min_weight_fraction_leaf': 0.08562946203667166, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 21:53:42,290] Trial 89 finished with value: 0.7461891440711376 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.9666623619578044, 'max_features': None, 'min_weight_fraction_leaf': 0.13289751230356953, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 21:53:57,560] Trial 90 finished with value: 0.7721635506485307 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 361, 'oob_score': False, 'max_samples': 0.9143479302159204, 'max_features': None, 'min_weight_fraction_leaf': 0.04481644229535587, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.

Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9527896995708155
[I 2024-04-16 21:54:25,442] Trial 91 finished with value: 0.8446737781674148 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.9488468959302472, 'max_features': None, 'min_weight_fraction_leaf': 0.060774497145647054, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9527896995708155
[I 2024-04-16 21:54:54,984] Trial 92 finished with value: 0.8405269611800452 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 423, 'oob_score': False, 'max_samples': 0.94014101252894, 'max_features': None, 'min_weight_fraction_leaf': 0.0548113701472033, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.9527896995708155
[I 2024-04-16 21:55:15,588] Trial 93 finished with value: 0.8120089069227732 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.5075426217211035, 'max_features': None, 'min_weight_fraction_leaf': 0.0319777462255082, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.9108527131782945
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.944206008583691
[I 2024-04-16 21:56:02,085] Trial 94 finished with value: 0.8187892581947704 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.9227811582027634, 'max_features': None, 'min_weight_fraction_leaf': 0.00822735070118076, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9484978540772532
[I 2024-04-16 21:56:28,009] Trial 95 finished with value: 0.8407509903501437 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.9752306812643342, 'max_features': None, 'min_weight_fraction_leaf': 0.06347739998417412, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 21:56:34,111] Trial 96 finished with value: 0.797411102196824 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 14, 'n_estimators': 397, 'oob_score': False, 'max_samples': 0.9383924139197609, 'max_features': None, 'min_weight_fraction_leaf': 0.06205878427847117, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 21:56:57,165] Trial 97 finished with value: 0.8413305019197933 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.9752654941017508, 'max_features': None, 'min_weight_fraction_leaf': 0.08608757981910961, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 21:58:22,893] Trial 98 finished with value: 0.6673031775286545 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.9756872825157317, 'max_features': None, 'min_weight_fraction_leaf': 0.11068049094138749, 'warm_start': False}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8595744680851064

[I 2024-04-16 21:58:35,663] A new study created in memory with name: no-name-a3e101f5-a407-430f-bf03-6f249dbdb54c

Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.871244635193133
[I 2024-04-16 21:58:35,643] Trial 99 finished with value: 0.8113937137105396 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 467, 'oob_score': False, 'max_samples': 0.9056858572892185, 'max_features': None, 'min_weight_fraction_leaf': 0.20123851264921916, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.


* Best trial for C-index:
 FrozenTrial(number=65, state=TrialState.COMPLETE, values=[0.8474444748453905], datetime_start=datetime.datetime(2024, 4, 16, 21, 40, 49, 492052), datetime_complete=datetime.datetime(2024, 4, 16, 21, 40, 52, 827285), params={'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 441, 'oob_score': False, 'max_samples': 0.9873533850424658, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04287202412707603, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=65, value=None)


* Best Score for C-index:
 0.8474444748453905

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23042752124267438
Fold 2 IBS: 0.18839054215405548
Fold 3 IBS: 0.2293899661136923
Fold 4 IBS: 0.2169146460429805
Fold 5 IBS: 0.2142567055646754
[I 2024-04-16 21:59:00,430] Trial 0 finished with value: 0.21587587622361562 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.2508146115058545
Fold 2 IBS: 0.20305081069239997
Fold 3 IBS: 0.2125601518843403
Fold 4 IBS: 0.23802356391790935
Fold 5 IBS: 0.24031357707661585
[I 2024-04-16 21:59:01,780] Trial 1 finished with value: 0.228952543015424 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-16 21:59:02,720] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-16 21:59:05,406] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-16 21:59:07,394] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.2555512810814963
Fold 2 IBS: 0.20324441473182778
Fold 3 IBS: 0.20138344229687621
Fold 4 IBS: 0.24823005681755586
Fold 5 IBS: 0.23986172601998265
[I 2024-04-16 21:59:12,031] Trial 5 finished with value: 0.22965418418954772 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.22937230878310585
Fold 2 IBS: 0.19783748265063947
Fold 3 IBS: 0.24758962979639584
Fold 4 IBS: 0.2293592142258337
Fold 5 IBS: 0.21843413307330445
[I 2024-04-16 21:59:26,347] Trial 6 finished with value: 0.22451855370585588 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24645459314284615
Fold 2 IBS: 0.2284327655476503
Fold 3 IBS: 0.2269204476718718
Fold 4 IBS: 0.24193873418388995
Fold 5 IBS: 0.23242562407841813
[I 2024-04-16 21:59:30,312] Trial 7 finished with value: 0.23523443292493526 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-16 21:59:35,462] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.2514315797339687
Fold 2 IBS: 0.20486001394714717
Fold 3 IBS: 0.21413246491582993
Fold 4 IBS: 0.2488036649239709
Fold 5 IBS: 0.23916777605650416
[I 2024-04-16 21:59:36,892] Trial 9 finished with value: 0.23167909991548416 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24645571521465787
Fold 2 IBS: 0.23214351218858914
Fold 3 IBS: 0.23029990468218745
Fold 4 IBS: 0.24091247880712954
Fold 5 IBS: 0.22969387017589088
[I 2024-04-16 21:59:43,928] Trial 10 finished with value: 0.235901096213691 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27033688725897076}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.22505044010769915
Fold 2 IBS: 0.19169873975025706
Fold 3 IBS: 0.24355652039688175
Fold 4 IBS: 0.22456118368774855
Fold 5 IBS: 0.2199364923604279
[I 2024-04-16 22:00:07,763] Trial 11 finished with value: 0.2209606752606029 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.9485893528798968, 'max_features': None, 'min_weight_fraction_leaf': 0.34713111632234195}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.22641537530591904
Fold 2 IBS: 0.1856122448029484
Fold 3 IBS: 0.23970956613213612
Fold 4 IBS: 0.22689978521066698
Fold 5 IBS: 0.21984826293499948
[I 2024-04-16 22:00:35,888] Trial 12 finished with value: 0.219697046877334 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.99460329717513, 'max_features': None, 'min_weight_fraction_leaf': 0.3273519300270286}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24906566803157934
Fold 2 IBS: 0.1844522654087228
Fold 3 IBS: 0.22247964562583175
Fold 4 IBS: 0.2200365797335415
Fold 5 IBS: 0.21390292106525644
[I 2024-04-16 22:01:22,424] Trial 13 finished with value: 0.21798741597298638 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.7795899048785642, 'max_features': None, 'min_weight_fraction_leaf': 0.16534086975223722}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.25156447987348923
Fold 2 IBS: 0.20970424521303116
Fold 3 IBS: 0.20875877537891965
Fold 4 IBS: 0.24770150304574612
Fold 5 IBS: 0.24420033286537043
[I 2024-04-16 22:01:27,199] Trial 14 finished with value: 0.23238586727531133 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.7714173351535261, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1619227173876303}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.26683527729810225
Fold 2 IBS: 0.20435168056118677
Fold 3 IBS: 0.21099863333114646
Fold 4 IBS: 0.23944579683045827
Fold 5 IBS: 0.2220476423219148
[I 2024-04-16 22:01:59,903] Trial 15 finished with value: 0.22873580606856173 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.7857370506104712, 'max_features': None, 'min_weight_fraction_leaf': 9.381036713218549e-05}. Best is trial 0 with value: 0.21587587622361562.

Fold 1 IBS: 0.22884349745474517
Fold 2 IBS: 0.18834811375380564
Fold 3 IBS: 0.2312043647935247
Fold 4 IBS: 0.21471543299997775
Fold 5 IBS: 0.21368545250258145
[I 2024-04-16 22:02:18,226] Trial 16 finished with value: 0.21535937230092697 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 338, 'oob_score': False, 'max_samples': 0.7160627225800851, 'max_features': None, 'min_weight_fraction_leaf': 0.2245547459670535}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.23115054536847185
Fold 2 IBS: 0.19232972177370425
Fold 3 IBS: 0.2306960604186981
Fold 4 IBS: 0.2282864781982014
Fold 5 IBS: 0.22100826632463474
[I 2024-04-16 22:02:35,442] Trial 17 finished with value: 0.22069421441674208 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.6871243940599472, 'max_features': None, 'min_weight_fraction_leaf': 0.2285855344271941}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.2547124645596499
Fold 2 IBS: 0.21239240552877675
Fold 3 IBS: 0.20907384621625053
Fold 4 IBS: 0.2552638099119818
Fold 5 IBS: 0.239861875460518
[I 2024-04-16 22:02:38,276] Trial 18 finished with value: 0.2342608803354354 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 202, 'oob_score': True, 'max_samples': 0.3978019017721025, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08924573043815814}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.25153637815211566
Fold 2 IBS: 0.2130643844494364
Fold 3 IBS: 0.21653921536390197
Fold 4 IBS: 0.2515132161134549
Fold 5 IBS: 0.24551267392915996
[I 2024-04-16 22:02:40,253] Trial 19 finished with value: 0.2356331736016138 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.6061595584833309, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22791611456767383}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.24668838755067432
Fold 2 IBS: 0.2323223694774956
Fold 3 IBS: 0.22952287763530818
Fold 4 IBS: 0.24145505906170697
Fold 5 IBS: 0.23037434075470525
[I 2024-04-16 22:02:42,905] Trial 20 finished with value: 0.23607260689597806 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.4458729287336371, 'max_features': None, 'min_weight_fraction_leaf': 0.3007687013181908}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.25768407946447835
Fold 2 IBS: 0.18741993444051966
Fold 3 IBS: 0.21990359018458633
Fold 4 IBS: 0.22758690645744453
Fold 5 IBS: 0.2122845055529156
[I 2024-04-16 22:03:34,082] Trial 21 finished with value: 0.2209758032199889 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 399, 'oob_score': False, 'max_samples': 0.7968542041631069, 'max_features': None, 'min_weight_fraction_leaf': 0.14088312030047453}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.23994195701389592
Fold 2 IBS: 0.1880263620809246
Fold 3 IBS: 0.22200106857343152
Fold 4 IBS: 0.2333432594536798
Fold 5 IBS: 0.22313781821533352
[I 2024-04-16 22:04:11,480] Trial 22 finished with value: 0.22129009306745306 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.7333978805634859, 'max_features': None, 'min_weight_fraction_leaf': 0.2049420412000723}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.2625956010796006
Fold 2 IBS: 0.1928923730378316
Fold 3 IBS: 0.21796884204077038
Fold 4 IBS: 0.23320993234287188
Fold 5 IBS: 0.21762131459681405
[I 2024-04-16 22:04:53,244] Trial 23 finished with value: 0.22485761261957773 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.8558877999962695, 'max_features': None, 'min_weight_fraction_leaf': 0.12237281401289234}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.22276602783377017
Fold 2 IBS: 0.18341833821581766
Fold 3 IBS: 0.23515178773766685
Fold 4 IBS: 0.2158844598266772
Fold 5 IBS: 0.214498386011388
[I 2024-04-16 22:05:21,570] Trial 24 finished with value: 0.214343799925064 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.8436689400574193, 'max_features': None, 'min_weight_fraction_leaf': 0.244242289743401}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.2232033563663133
Fold 2 IBS: 0.18483011757148574
Fold 3 IBS: 0.2387458608845854
Fold 4 IBS: 0.21469399502353012
Fold 5 IBS: 0.21400836240416607
[I 2024-04-16 22:05:48,656] Trial 25 finished with value: 0.21509633845001613 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.8781861106771913, 'max_features': None, 'min_weight_fraction_leaf': 0.25578130205333305}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.2243469078613741
Fold 2 IBS: 0.18503556791629602
Fold 3 IBS: 0.239615094137992
Fold 4 IBS: 0.2128207476339741
Fold 5 IBS: 0.21343897546943888
[I 2024-04-16 22:06:23,144] Trial 26 finished with value: 0.21505145860381503 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 457, 'oob_score': True, 'max_samples': 0.8790368112638932, 'max_features': None, 'min_weight_fraction_leaf': 0.25879667379312365}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.24994978911265142
Fold 2 IBS: 0.20970593191211698
Fold 3 IBS: 0.21190261680704528
Fold 4 IBS: 0.24890297891386573
Fold 5 IBS: 0.24082074617028817
[I 2024-04-16 22:06:28,324] Trial 27 finished with value: 0.2322564125831935 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 463, 'oob_score': True, 'max_samples': 0.8959637112797967, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2611199851941091}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.2502142619626781
Fold 2 IBS: 0.2062960293780691
Fold 3 IBS: 0.20914331859862303
Fold 4 IBS: 0.24450110394780006
Fold 5 IBS: 0.23744852143309458
[I 2024-04-16 22:06:35,108] Trial 28 finished with value: 0.22952064706405295 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.957086450216675, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3146636471285875}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.2316496219569113
Fold 2 IBS: 0.20199211986849258
Fold 3 IBS: 0.25252580475553593
Fold 4 IBS: 0.23451794093985362
Fold 5 IBS: 0.22256455030066677
[I 2024-04-16 22:06:53,040] Trial 29 finished with value: 0.22865000756429205 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.8498266742400898, 'max_features': None, 'min_weight_fraction_leaf': 0.37494346942158263}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.2293501237092553
Fold 2 IBS: 0.1835103223875015
Fold 3 IBS: 0.23279207931646337
Fold 4 IBS: 0.21732583133116853
Fold 5 IBS: 0.2103061227472283
[I 2024-04-16 22:07:20,939] Trial 30 finished with value: 0.2146568958983234 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.9975403100242013, 'max_features': None, 'min_weight_fraction_leaf': 0.2599744768668571}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.22543889947738152
Fold 2 IBS: 0.1845289972063156
Fold 3 IBS: 0.23174838796536676
Fold 4 IBS: 0.2144936679622966
Fold 5 IBS: 0.21144518832087167
[I 2024-04-16 22:07:50,316] Trial 31 finished with value: 0.21353102818644648 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 303, 'oob_score': True, 'max_samples': 0.9626750941879966, 'max_features': None, 'min_weight_fraction_leaf': 0.26115274999390314}. Best is trial 31 with value: 0.21353102818644648.

Fold 1 IBS: 0.22149490022552124
Fold 2 IBS: 0.18466865634717505
Fold 3 IBS: 0.23548539432841317
Fold 4 IBS: 0.2113697424267566
Fold 5 IBS: 0.2119677581906565
[I 2024-04-16 22:08:14,837] Trial 32 finished with value: 0.2129972903037045 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.9673759674409311, 'max_features': None, 'min_weight_fraction_leaf': 0.27417727195073677}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.2567229873354098
Fold 2 IBS: 0.18854079292396503
Fold 3 IBS: 0.2249457788925835
Fold 4 IBS: 0.22508129343804778
Fold 5 IBS: 0.21386415001842546
[I 2024-04-16 22:08:47,016] Trial 33 finished with value: 0.2218310005216863 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 304, 'oob_score': True, 'max_samples': 0.9964442664551478, 'max_features': None, 'min_weight_fraction_leaf': 0.1855920796843306}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.22302338864627833
Fold 2 IBS: 0.18329215715895394
Fold 3 IBS: 0.23579844813453207
Fold 4 IBS: 0.21461565443498337
Fold 5 IBS: 0.21550729328840212
[I 2024-04-16 22:09:03,777] Trial 34 finished with value: 0.21444738833262997 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 234, 'oob_score': True, 'max_samples': 0.9279710918176601, 'max_features': None, 'min_weight_fraction_leaf': 0.2867300145495075}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.24931299863626957
Fold 2 IBS: 0.21399812944525917
Fold 3 IBS: 0.21838058951641673
Fold 4 IBS: 0.24989391243794642
Fold 5 IBS: 0.23922813868039394
[I 2024-04-16 22:09:07,064] Trial 35 finished with value: 0.23416275374325718 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.9536728448516014, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3909359479764509}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.23117720087911678
Fold 2 IBS: 0.20908991901846688
Fold 3 IBS: 0.2539101731203305
Fold 4 IBS: 0.24099766821400376
Fold 5 IBS: 0.2293088693612524
[I 2024-04-16 22:09:15,090] Trial 36 finished with value: 0.23289676611863408 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.9283967702859293, 'max_features': None, 'min_weight_fraction_leaf': 0.44701099039110287}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.2523224496304161
Fold 2 IBS: 0.21043432067224094
Fold 3 IBS: 0.2112721950288639
Fold 4 IBS: 0.24870441754756062
Fold 5 IBS: 0.23989403542441912
[I 2024-04-16 22:09:18,595] Trial 37 finished with value: 0.23252548366070017 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.8243905227087784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2901382904665285}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.24687665709365722
Fold 2 IBS: 0.23216047658482733
Fold 3 IBS: 0.22943470935389718
Fold 4 IBS: 0.24151119067690444
Fold 5 IBS: 0.23038863917402108
[I 2024-04-16 22:09:22,159] Trial 38 finished with value: 0.23607433457666147 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 266, 'oob_score': True, 'max_samples': 0.6365393674376216, 'max_features': None, 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.23138450633211288
Fold 2 IBS: 0.2012849705319908
Fold 3 IBS: 0.24592903460990817
Fold 4 IBS: 0.2321634541727149
Fold 5 IBS: 0.21646893363939826
[I 2024-04-16 22:09:30,842] Trial 39 finished with value: 0.225446179857225 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 178, 'oob_score': True, 'max_samples': 0.9213772884619962, 'max_features': None, 'min_weight_fraction_leaf': 0.3814300944091633}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.24772435188079012
Fold 2 IBS: 0.23218742086626878
Fold 3 IBS: 0.23060758736791892
Fold 4 IBS: 0.24175508770731288
Fold 5 IBS: 0.23204474443418183
[I 2024-04-16 22:09:31,304] Trial 40 finished with value: 0.2368638384512945 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 23, 'oob_score': True, 'max_samples': 0.16382436256125943, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.28669301454652507}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.23272078581366948
Fold 2 IBS: 0.18387215718777747
Fold 3 IBS: 0.2312356985823202
Fold 4 IBS: 0.21835974803092903
Fold 5 IBS: 0.2118508415801541
[I 2024-04-16 22:10:04,282] Trial 41 finished with value: 0.21560784623897006 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 309, 'oob_score': True, 'max_samples': 0.9968428823752321, 'max_features': None, 'min_weight_fraction_leaf': 0.24475563110472928}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.22762467376302845
Fold 2 IBS: 0.19292454667228245
Fold 3 IBS: 0.24232575060581318
Fold 4 IBS: 0.22605305899139677
Fold 5 IBS: 0.2183712075716998
[I 2024-04-16 22:10:20,606] Trial 42 finished with value: 0.2214598475208441 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 299, 'oob_score': True, 'max_samples': 0.8330638381230538, 'max_features': None, 'min_weight_fraction_leaf': 0.30703156935090925}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.22060072941583395
Fold 2 IBS: 0.1839788116163854
Fold 3 IBS: 0.2354589586695753
Fold 4 IBS: 0.2103428787902223
Fold 5 IBS: 0.21157714114706494
[I 2024-04-16 22:10:38,417] Trial 43 finished with value: 0.2123917039278164 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 222, 'oob_score': True, 'max_samples': 0.9591424672361251, 'max_features': None, 'min_weight_fraction_leaf': 0.2785655043553118}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2256927624531365
Fold 2 IBS: 0.19403171073899753
Fold 3 IBS: 0.24180178869616473
Fold 4 IBS: 0.22271987208962252
Fold 5 IBS: 0.21926725742571193
[I 2024-04-16 22:10:50,905] Trial 44 finished with value: 0.22070267828072665 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 219, 'oob_score': True, 'max_samples': 0.9395792767074951, 'max_features': None, 'min_weight_fraction_leaf': 0.35489094778373753}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2457081276764462
Fold 2 IBS: 0.2057089461106387
Fold 3 IBS: 0.2112006429304633
Fold 4 IBS: 0.2504179456089246
Fold 5 IBS: 0.2381093166637389
[I 2024-04-16 22:10:52,812] Trial 45 finished with value: 0.23022899579804235 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.8989588401372685, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.28207190827118556}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.246544080673752
Fold 2 IBS: 0.23213980573826468
Fold 3 IBS: 0.2295309513645431
Fold 4 IBS: 0.24164345141610383
Fold 5 IBS: 0.23038069732103597
[I 2024-04-16 22:10:56,447] Trial 46 finished with value: 0.23604779730273995 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 245, 'oob_score': True, 'max_samples': 0.9587168953650592, 'max_features': None, 'min_weight_fraction_leaf': 0.4987000897606556}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.24900574598687916
Fold 2 IBS: 0.200322207738425
Fold 3 IBS: 0.20666582272059178
Fold 4 IBS: 0.24160407963613872
Fold 5 IBS: 0.23964332065507346
[I 2024-04-16 22:10:59,596] Trial 47 finished with value: 0.22744823534742165 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 193, 'oob_score': True, 'max_samples': 0.8252659010917025, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.18709868233605237}. Best is trial 43 with value: 0.2123917039278164.

Fold 1 IBS: 0.23233061602902896
Fold 2 IBS: 0.20470776398952695
Fold 3 IBS: 0.24473722549758978
Fold 4 IBS: 0.23554082329183057
Fold 5 IBS: 0.22266798632628182
[I 2024-04-16 22:11:11,177] Trial 48 finished with value: 0.22799688302685164 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 277, 'oob_score': True, 'max_samples': 0.7486071388218823, 'max_features': None, 'min_weight_fraction_leaf': 0.3316489763494004}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22140751210407167
Fold 2 IBS: 0.18446093935852728
Fold 3 IBS: 0.23819663142832964
Fold 4 IBS: 0.21304733351095642
Fold 5 IBS: 0.21354093321412873
[I 2024-04-16 22:11:33,770] Trial 49 finished with value: 0.21413066992320276 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.9104681524496127, 'max_features': None, 'min_weight_fraction_leaf': 0.2085463208364724}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22233291067700658
Fold 2 IBS: 0.18478464545596854
Fold 3 IBS: 0.23971913759043886
Fold 4 IBS: 0.21278768542579282
Fold 5 IBS: 0.21478540299561258
[I 2024-04-16 22:11:54,597] Trial 50 finished with value: 0.2148819564289639 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 10, 'n_estimators': 370, 'oob_score': True, 'max_samples': 0.8824600753169473, 'max_features': None, 'min_weight_fraction_leaf': 0.21462027388465296}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22734559235093124
Fold 2 IBS: 0.18318936929294466
Fold 3 IBS: 0.23297167248730816
Fold 4 IBS: 0.21245702972369868
Fold 5 IBS: 0.21111254387628536
[I 2024-04-16 22:12:19,185] Trial 51 finished with value: 0.21341524154623365 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 357, 'oob_score': True, 'max_samples': 0.9625411717608587, 'max_features': None, 'min_weight_fraction_leaf': 0.23293844782753054}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22346864077437148
Fold 2 IBS: 0.18390840845858739
Fold 3 IBS: 0.23332464818299495
Fold 4 IBS: 0.2131988499365954
Fold 5 IBS: 0.21069690375604289
[I 2024-04-16 22:12:40,998] Trial 52 finished with value: 0.21291949022171847 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 352, 'oob_score': True, 'max_samples': 0.9641055300734946, 'max_features': None, 'min_weight_fraction_leaf': 0.23607641839390603}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22838038692070342
Fold 2 IBS: 0.18230534132767368
Fold 3 IBS: 0.2331843783263773
Fold 4 IBS: 0.21294291300198875
Fold 5 IBS: 0.21054265660575297
[I 2024-04-16 22:13:04,495] Trial 53 finished with value: 0.21347113523649922 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 355, 'oob_score': True, 'max_samples': 0.9631487042826314, 'max_features': None, 'min_weight_fraction_leaf': 0.17637754776024273}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2284275692142271
Fold 2 IBS: 0.18246107795839966
Fold 3 IBS: 0.23265587552703618
Fold 4 IBS: 0.2133213439680979
Fold 5 IBS: 0.21041220939694896
[I 2024-04-16 22:13:32,020] Trial 54 finished with value: 0.21345561521294196 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 359, 'oob_score': True, 'max_samples': 0.967029635289036, 'max_features': None, 'min_weight_fraction_leaf': 0.13017229949607742}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.24655826225731184
Fold 2 IBS: 0.23223212769483395
Fold 3 IBS: 0.2299109075503006
Fold 4 IBS: 0.24125502336117552
Fold 5 IBS: 0.23025881880809368
[I 2024-04-16 22:13:36,133] Trial 55 finished with value: 0.23604302793434312 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 10, 'n_estimators': 351, 'oob_score': True, 'max_samples': 0.26065411177594827, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13302957117693476}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2288773906468273
Fold 2 IBS: 0.182557427331127
Fold 3 IBS: 0.23247262815573858
Fold 4 IBS: 0.21385954181177394
Fold 5 IBS: 0.2108105644361973
[I 2024-04-16 22:14:00,159] Trial 56 finished with value: 0.2137155104763328 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 357, 'oob_score': True, 'max_samples': 0.975784426896677, 'max_features': None, 'min_weight_fraction_leaf': 0.10165017984714692}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2517864102395247
Fold 2 IBS: 0.21311790899482444
Fold 3 IBS: 0.21465108435997157
Fold 4 IBS: 0.25309517297336526
Fold 5 IBS: 0.2417203119244569
[I 2024-04-16 22:14:04,514] Trial 57 finished with value: 0.23487417769842858 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 326, 'oob_score': True, 'max_samples': 0.47523615475756226, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0456877909412422}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2243353112407589
Fold 2 IBS: 0.18266218635612108
Fold 3 IBS: 0.23393999495208184
Fold 4 IBS: 0.2149406342270133
Fold 5 IBS: 0.21045670202420302
[I 2024-04-16 22:14:32,325] Trial 58 finished with value: 0.21326696576003562 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 416, 'oob_score': True, 'max_samples': 0.9713216893041037, 'max_features': None, 'min_weight_fraction_leaf': 0.17261347912606032}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.24689331510957085
Fold 2 IBS: 0.20349936746264044
Fold 3 IBS: 0.20741536012216769
Fold 4 IBS: 0.24027185216325905
Fold 5 IBS: 0.23849175782634383
[I 2024-04-16 22:14:37,730] Trial 59 finished with value: 0.2273143305367964 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 10, 'n_estimators': 396, 'oob_score': True, 'max_samples': 0.9111341643808946, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15152628104819157}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.23161246102067778
Fold 2 IBS: 0.18315762337529268
Fold 3 IBS: 0.23355670246252003
Fold 4 IBS: 0.2141622801821901
Fold 5 IBS: 0.21203217214938297
[I 2024-04-16 22:15:04,304] Trial 60 finished with value: 0.2149042478380127 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 12, 'n_estimators': 416, 'oob_score': True, 'max_samples': 0.8718303197272472, 'max_features': None, 'min_weight_fraction_leaf': 0.23327466883167086}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22544682915255349
Fold 2 IBS: 0.1837835452877901
Fold 3 IBS: 0.2340793656204444
Fold 4 IBS: 0.2134652558712757
Fold 5 IBS: 0.21112250446162584
[I 2024-04-16 22:15:31,332] Trial 61 finished with value: 0.21357950007873788 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 434, 'oob_score': True, 'max_samples': 0.9574526723194436, 'max_features': None, 'min_weight_fraction_leaf': 0.16996612592674035}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.23566977171208375
Fold 2 IBS: 0.18355373888054702
Fold 3 IBS: 0.23122032354257444
Fold 4 IBS: 0.2166971166015121
Fold 5 IBS: 0.21225529499203713
[I 2024-04-16 22:15:56,236] Trial 62 finished with value: 0.2158792491457509 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 320, 'oob_score': True, 'max_samples': 0.9692513608661454, 'max_features': None, 'min_weight_fraction_leaf': 0.10901914015734161}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22018115372329825
Fold 2 IBS: 0.18426413954689186
Fold 3 IBS: 0.234485531054646
Fold 4 IBS: 0.2145039808669085
Fold 5 IBS: 0.21463282350485688
[I 2024-04-16 22:16:11,615] Trial 63 finished with value: 0.21361352573932027 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 13, 'n_estimators': 346, 'oob_score': True, 'max_samples': 0.8078307550305597, 'max_features': None, 'min_weight_fraction_leaf': 0.17457092877839805}. Best is trial 43 with value: 0.2123917039278164.

Fold 1 IBS: 0.2365430487443625
Fold 2 IBS: 0.18238280317098843
Fold 3 IBS: 0.2322276544017584
Fold 4 IBS: 0.21380685041046066
Fold 5 IBS: 0.21115528132467798
[I 2024-04-16 22:16:41,628] Trial 64 finished with value: 0.21522312761044962 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 405, 'oob_score': True, 'max_samples': 0.9369908825823273, 'max_features': None, 'min_weight_fraction_leaf': 0.19119487575645203}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2545794604503248
Fold 2 IBS: 0.18515187912067008
Fold 3 IBS: 0.22861527937785475
Fold 4 IBS: 0.22050482646274178
Fold 5 IBS: 0.2129134229864224
[I 2024-04-16 22:17:14,329] Trial 65 finished with value: 0.22035297367960277 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 362, 'oob_score': True, 'max_samples': 0.9998359499913109, 'max_features': None, 'min_weight_fraction_leaf': 0.1490943973635694}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22654845800464724
Fold 2 IBS: 0.18332141958706227
Fold 3 IBS: 0.2350631328838295
Fold 4 IBS: 0.21236321104852912
Fold 5 IBS: 0.21200214915706886
[I 2024-04-16 22:17:45,334] Trial 66 finished with value: 0.2138596741362274 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 10, 'n_estimators': 436, 'oob_score': True, 'max_samples': 0.8962905931034715, 'max_features': None, 'min_weight_fraction_leaf': 0.0680516900187007}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2314909050987209
Fold 2 IBS: 0.20249096930835778
Fold 3 IBS: 0.23980167405092054
Fold 4 IBS: 0.2353173847496087
Fold 5 IBS: 0.2224605814306102
[I 2024-04-16 22:17:54,452] Trial 67 finished with value: 0.22631230292764365 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 281, 'oob_score': True, 'max_samples': 0.576072702219687, 'max_features': None, 'min_weight_fraction_leaf': 0.23671139187646353}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.23493478177072255
Fold 2 IBS: 0.1839771658107539
Fold 3 IBS: 0.2327966378875902
Fold 4 IBS: 0.21470499176958288
Fold 5 IBS: 0.21135088245166292
[I 2024-04-16 22:18:46,663] Trial 68 finished with value: 0.21555289193806249 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 340, 'oob_score': True, 'max_samples': 0.9745293218944675, 'max_features': None, 'min_weight_fraction_leaf': 0.2208990376756659}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.24543506602157308
Fold 2 IBS: 0.20317035895085483
Fold 3 IBS: 0.20373744028936427
Fold 4 IBS: 0.2408108283305109
Fold 5 IBS: 0.23682283690526376
[I 2024-04-16 22:18:50,299] Trial 69 finished with value: 0.22599530609951338 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 12, 'n_estimators': 260, 'oob_score': True, 'max_samples': 0.8624070878492855, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1990248466441951}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2503935277219034
Fold 2 IBS: 0.20812254306242206
Fold 3 IBS: 0.2113368150498763
Fold 4 IBS: 0.249610089701322
Fold 5 IBS: 0.24046537193598522
[I 2024-04-16 22:18:54,435] Trial 70 finished with value: 0.2319856694943018 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9186596987029689, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11544109176287089}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.221575371693387
Fold 2 IBS: 0.18398808173473347
Fold 3 IBS: 0.23724504533105953
Fold 4 IBS: 0.214033992760505
Fold 5 IBS: 0.21096749762165287
[I 2024-04-16 22:19:21,603] Trial 71 finished with value: 0.2135619978282676 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.9723894444805646, 'max_features': None, 'min_weight_fraction_leaf': 0.2730206487158777}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22000227604484365
Fold 2 IBS: 0.1835976512867323
Fold 3 IBS: 0.23496758393840209
Fold 4 IBS: 0.2108901768233098
Fold 5 IBS: 0.21502432185948614
[I 2024-04-16 22:19:37,651] Trial 72 finished with value: 0.21289640199055476 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 283, 'oob_score': True, 'max_samples': 0.9429494364281713, 'max_features': None, 'min_weight_fraction_leaf': 0.26970631759176494}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22727419395708034
Fold 2 IBS: 0.1871701080786577
Fold 3 IBS: 0.2378340481827281
Fold 4 IBS: 0.2289741531942034
Fold 5 IBS: 0.22120111363123252
[I 2024-04-16 22:19:53,225] Trial 73 finished with value: 0.22049072340878037 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 361, 'oob_score': True, 'max_samples': 0.9341055458028956, 'max_features': None, 'min_weight_fraction_leaf': 0.31471941963288985}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22389252687104882
Fold 2 IBS: 0.18478568946187152
Fold 3 IBS: 0.23569319407407555
Fold 4 IBS: 0.21383105927421142
Fold 5 IBS: 0.21188816578028835
[I 2024-04-16 22:20:22,186] Trial 74 finished with value: 0.21401812709229912 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 476, 'oob_score': True, 'max_samples': 0.946932527578757, 'max_features': None, 'min_weight_fraction_leaf': 0.24504456019566914}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.21854302798549347
Fold 2 IBS: 0.18176372907932323
Fold 3 IBS: 0.23671374300002862
Fold 4 IBS: 0.21422935554752687
Fold 5 IBS: 0.21083967154267064
[I 2024-04-16 22:20:40,913] Trial 75 finished with value: 0.21241790543100855 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 288, 'oob_score': True, 'max_samples': 0.9803084469016909, 'max_features': None, 'min_weight_fraction_leaf': 0.13142931899110993}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2197445619216238
Fold 2 IBS: 0.18503554254500237
Fold 3 IBS: 0.23931664349279788
Fold 4 IBS: 0.21161636970789327
Fold 5 IBS: 0.2155020163620093
[I 2024-04-16 22:20:56,000] Trial 76 finished with value: 0.21424302680586535 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 10, 'n_estimators': 293, 'oob_score': True, 'max_samples': 0.8898157454998676, 'max_features': None, 'min_weight_fraction_leaf': 0.04187570620310249}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2327743668403808
Fold 2 IBS: 0.1821560057823301
Fold 3 IBS: 0.23089143622316666
Fold 4 IBS: 0.23577008510470598
Fold 5 IBS: 0.2235347877710858
[I 2024-04-16 22:21:09,924] Trial 77 finished with value: 0.22102533634433388 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 1, 'n_estimators': 277, 'oob_score': True, 'max_samples': 0.9879662653142723, 'max_features': None, 'min_weight_fraction_leaf': 0.2732568395879575}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22818707588004375
Fold 2 IBS: 0.19020975012058644
Fold 3 IBS: 0.23714209938276803
Fold 4 IBS: 0.2286788294533738
Fold 5 IBS: 0.21849469879449682
[I 2024-04-16 22:21:20,284] Trial 78 finished with value: 0.2205424907262538 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 14, 'n_estimators': 258, 'oob_score': True, 'max_samples': 0.8577519434160554, 'max_features': None, 'min_weight_fraction_leaf': 0.2950875024553569}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.23474728243730542
Fold 2 IBS: 0.1971796499722597
Fold 3 IBS: 0.22834092402557343
Fold 4 IBS: 0.23413287196690447
Fold 5 IBS: 0.2205931708782621
[I 2024-04-16 22:21:26,536] Trial 79 finished with value: 0.222998779856061 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 13, 'n_estimators': 224, 'oob_score': True, 'max_samples': 0.5125421624254995, 'max_features': None, 'min_weight_fraction_leaf': 0.09061426277200699}. Best is trial 43 with value: 0.2123917039278164.

Fold 1 IBS: 0.2511057207255618
Fold 2 IBS: 0.21572593535559278
Fold 3 IBS: 0.2149073004231141
Fold 4 IBS: 0.2472468833843753
Fold 5 IBS: 0.24247425822381166
[I 2024-04-16 22:21:29,895] Trial 80 finished with value: 0.23429201962249113 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 335, 'oob_score': True, 'max_samples': 0.3618038809495957, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15390327148267055}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22731065610063553
Fold 2 IBS: 0.18233470119562936
Fold 3 IBS: 0.23388585350331287
Fold 4 IBS: 0.21305351886000728
Fold 5 IBS: 0.21153134197254575
[I 2024-04-16 22:21:50,180] Trial 81 finished with value: 0.21362321432642614 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9436804929256887, 'max_features': None, 'min_weight_fraction_leaf': 0.12227771301430333}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2272092638449265
Fold 2 IBS: 0.18337145552397865
Fold 3 IBS: 0.23253451313019002
Fold 4 IBS: 0.2138892087318099
Fold 5 IBS: 0.21064394129949776
[I 2024-04-16 22:22:10,656] Trial 82 finished with value: 0.21352967650608057 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.9739450345174413, 'max_features': None, 'min_weight_fraction_leaf': 0.13403887256843836}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22274585720905865
Fold 2 IBS: 0.1844029972495469
Fold 3 IBS: 0.23578817469856042
Fold 4 IBS: 0.21351903584251283
Fold 5 IBS: 0.2127567489010132
[I 2024-04-16 22:22:33,419] Trial 83 finished with value: 0.2138425627801384 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 10, 'n_estimators': 415, 'oob_score': True, 'max_samples': 0.9124790440575847, 'max_features': None, 'min_weight_fraction_leaf': 0.16278108493661606}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2202096426617108
Fold 2 IBS: 0.18300193402384377
Fold 3 IBS: 0.23678774176994796
Fold 4 IBS: 0.21045698381793299
Fold 5 IBS: 0.21165170888809465
[I 2024-04-16 22:22:48,449] Trial 84 finished with value: 0.21242160223230605 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 272, 'oob_score': True, 'max_samples': 0.936102238020355, 'max_features': None, 'min_weight_fraction_leaf': 0.2119155188772585}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.21864119730769158
Fold 2 IBS: 0.18332295425049822
Fold 3 IBS: 0.23624932020049083
Fold 4 IBS: 0.21147766575005164
Fold 5 IBS: 0.21180476450696664
[I 2024-04-16 22:23:02,494] Trial 85 finished with value: 0.21229918040313978 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 268, 'oob_score': True, 'max_samples': 0.9290276329324785, 'max_features': None, 'min_weight_fraction_leaf': 0.20767416366171196}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.22157963241090176
Fold 2 IBS: 0.18471642393517332
Fold 3 IBS: 0.23692790272940076
Fold 4 IBS: 0.2129824811604961
Fold 5 IBS: 0.21206997240184605
[I 2024-04-16 22:23:13,157] Trial 86 finished with value: 0.21365528252756358 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 15, 'n_estimators': 202, 'oob_score': True, 'max_samples': 0.9228769430188052, 'max_features': None, 'min_weight_fraction_leaf': 0.21001587254602957}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.22291669368529446
Fold 2 IBS: 0.182919208879211
Fold 3 IBS: 0.2388503936972904
Fold 4 IBS: 0.2158328741690931
Fold 5 IBS: 0.21059528283696147
[I 2024-04-16 22:23:27,942] Trial 87 finished with value: 0.21422289065357009 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 14, 'n_estimators': 249, 'oob_score': True, 'max_samples': 0.9992791729154259, 'max_features': None, 'min_weight_fraction_leaf': 0.2508797456646947}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.25078768869857776
Fold 2 IBS: 0.2106109982817939
Fold 3 IBS: 0.21209311522476643
Fold 4 IBS: 0.2508930677647447
Fold 5 IBS: 0.2396844528546169
[I 2024-04-16 22:23:30,194] Trial 88 finished with value: 0.23281386456489997 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.8919471551124474, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2208845327776338}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.25097719650425315
Fold 2 IBS: 0.21314574899449434
Fold 3 IBS: 0.21417231974570053
Fold 4 IBS: 0.24960112806534465
Fold 5 IBS: 0.23897071968187011
[I 2024-04-16 22:23:32,921] Trial 89 finished with value: 0.23337342259833255 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 13, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.7625776406001812, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27140964339693613}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.2245068533940247
Fold 2 IBS: 0.18699761355556005
Fold 3 IBS: 0.23544042396212175
Fold 4 IBS: 0.21923587620229615
Fold 5 IBS: 0.21746532566897547
[I 2024-04-16 22:23:45,036] Trial 90 finished with value: 0.2167292185565956 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 14, 'n_estimators': 308, 'oob_score': True, 'max_samples': 0.8012706364382673, 'max_features': None, 'min_weight_fraction_leaf': 0.23491486759055114}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.2218234667655608
Fold 2 IBS: 0.18409612316964802
Fold 3 IBS: 0.23464760900884943
Fold 4 IBS: 0.2117828169055223
Fold 5 IBS: 0.2103391213040047
[I 2024-04-16 22:24:03,003] Trial 91 finished with value: 0.21253782743071703 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 272, 'oob_score': True, 'max_samples': 0.9410520587040254, 'max_features': None, 'min_weight_fraction_leaf': 0.1785736177001936}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.22650071929198848
Fold 2 IBS: 0.18423351453669495
Fold 3 IBS: 0.23455340947340386
Fold 4 IBS: 0.2132023845394669
Fold 5 IBS: 0.21079535139402752
[I 2024-04-16 22:24:32,309] Trial 92 finished with value: 0.21385707584711638 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 13, 'n_estimators': 218, 'oob_score': True, 'max_samples': 0.9462078683111473, 'max_features': None, 'min_weight_fraction_leaf': 0.18398630290568166}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.2206749867203408
Fold 2 IBS: 0.1845112548902161
Fold 3 IBS: 0.2346107050489519
Fold 4 IBS: 0.2108494294764449
Fold 5 IBS: 0.21185476519664903
[I 2024-04-16 22:24:58,698] Trial 93 finished with value: 0.21250022826652054 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 276, 'oob_score': True, 'max_samples': 0.9344189667836965, 'max_features': None, 'min_weight_fraction_leaf': 0.25854173047664814}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.21954476841343637
Fold 2 IBS: 0.18528849913355389
Fold 3 IBS: 0.2376539942951079
Fold 4 IBS: 0.21407967576842526
Fold 5 IBS: 0.21415642969000542
[I 2024-04-16 22:25:14,970] Trial 94 finished with value: 0.21414467346010574 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 273, 'oob_score': True, 'max_samples': 0.8713272061326163, 'max_features': None, 'min_weight_fraction_leaf': 0.2544497221932043}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.2208107209861332
Fold 2 IBS: 0.18302956342153184
Fold 3 IBS: 0.23391990270287968
Fold 4 IBS: 0.21268167805826516
Fold 5 IBS: 0.21308598369318132
[I 2024-04-16 22:25:32,156] Trial 95 finished with value: 0.21270556977239824 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 285, 'oob_score': True, 'max_samples': 0.9058370293437961, 'max_features': None, 'min_weight_fraction_leaf': 0.19807593185105676}. Best is trial 85 with value: 0.21229918040313978.

Fold 1 IBS: 0.21975345965751325
Fold 2 IBS: 0.1826687616539912
Fold 3 IBS: 0.23593232323623828
Fold 4 IBS: 0.21692323202986982
Fold 5 IBS: 0.2157946933853038
[I 2024-04-16 22:25:46,679] Trial 96 finished with value: 0.21421449399258327 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 296, 'oob_score': True, 'max_samples': 0.8401991280225705, 'max_features': None, 'min_weight_fraction_leaf': 0.20291905202477475}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.22595559817931396
Fold 2 IBS: 0.18811290557691393
Fold 3 IBS: 0.23790732230802805
Fold 4 IBS: 0.22652570350197412
Fold 5 IBS: 0.21929538367243218
[I 2024-04-16 22:26:02,326] Trial 97 finished with value: 0.21955938264773245 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 19, 'max_depth': 15, 'n_estimators': 270, 'oob_score': True, 'max_samples': 0.9001142343235446, 'max_features': None, 'min_weight_fraction_leaf': 0.3126608885366039}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.219856246176777
Fold 2 IBS: 0.18353273410232165
Fold 3 IBS: 0.2355137490033137
Fold 4 IBS: 0.21361316808033728
Fold 5 IBS: 0.2140273787654496
[I 2024-04-16 22:26:23,894] Trial 98 finished with value: 0.21330865522563985 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 285, 'oob_score': True, 'max_samples': 0.930993873060305, 'max_features': None, 'min_weight_fraction_leaf': 0.2803881279308147}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.25162904138051667
Fold 2 IBS: 0.21372129222801167
Fold 3 IBS: 0.21584553623530486
Fold 4 IBS: 0.24661972756352624
Fold 5 IBS: 0.2419641213954559
[I 2024-04-16 22:26:27,263] Trial 99 finished with value: 0.23395594376056308 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.7146385057934307, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2661847294368132}. Best is trial 85 with value: 0.21229918040313978.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.21229918040313978], datetime_start=datetime.datetime(2024, 4, 16, 22, 22, 48, 459520), datetime_complete=datetime.datetime(2024, 4, 16, 22, 23, 2, 492689), params={'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 268, 'oob_score': True, 'max_samples': 0.9290276329324785, 'max_features': None, 'min_weight_fraction_leaf': 0.20767416366171196}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=85, value=None)


* Best Score for IBS:
 0.21229918040313978

In [84]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [85]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.847
train_ibs:  0.212

#### Test

In [86]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

In [87]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=16, max_features='auto', max_leaf_nodes=14,
                     max_samples=0.9873533850424658, min_samples_leaf=4,
                     min_samples_split=8,
                     min_weight_fraction_leaf=0.04287202412707603,
                     n_estimators=441, random_state=123, warm_start=True)

test_cindex:  0.54

RandomSurvivalForest(max_depth=13, max_features=None, max_leaf_nodes=11,
                     max_samples=0.9290276329324785, min_samples_leaf=20,
                     min_samples_split=9,
                     min_weight_fraction_leaf=0.20767416366171196,
                     n_estimators=268, oob_score=True, random_state=123)

test_ibs:  0.262

In [88]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [89]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [90]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 22:26:38,298] A new study created in memory with name: no-name-2f9503b6-9730-421f-982f-6c84fe9fba58

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7381974248927039
[I 2024-04-16 22:26:40,073] Trial 0 finished with value: 0.716790225055755 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.716790225055755.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:26:42,397] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.716790225055755.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 22:26:47,591] Trial 2 finished with value: 0.637634842816299 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.716790225055755.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7811158798283262
[I 2024-04-16 22:26:48,122] Trial 3 finished with value: 0.7443588775438851 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:26:50,520] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:26:52,513] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 22:26:53,790] Trial 6 finished with value: 0.7034666689139027 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.5095057034220533
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 22:26:56,642] Trial 7 finished with value: 0.5777346993743705 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7467811158798283
[I 2024-04-16 22:26:56,885] Trial 8 finished with value: 0.7256957651909646 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.5321888412017167
[I 2024-04-16 22:27:02,074] Trial 9 finished with value: 0.6059266344558226 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:27:02,857] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.25578614141973877, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5159362549800797
Fold 2 C-index: 0.560077519379845
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 22:27:03,043] Trial 11 finished with value: 0.6662340928785145 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 4, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.15140395801593098}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 22:27:03,361] Trial 12 finished with value: 0.7197009443517154 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 63, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.16694541300368826}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.703862660944206
[I 2024-04-16 22:27:04,226] Trial 13 finished with value: 0.72821263434496 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8757004183768704, 'min_weight_fraction_leaf': 0.12942492296949484}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 22:27:04,792] Trial 14 finished with value: 0.7120489026779355 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 5, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9015509519801813, 'min_weight_fraction_leaf': 0.2319873930301426}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 22:27:05,464] Trial 15 finished with value: 0.7572849484519277 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 138, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6967810217991331, 'min_weight_fraction_leaf': 0.10514124205272785}. Best is trial 15 with value: 0.7572849484519277.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:27:06,135] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 231, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6778661833429002, 'min_weight_fraction_leaf': 0.35612645124522524}. Best is trial 15 with value: 0.7572849484519277.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 22:27:06,618] Trial 17 finished with value: 0.7059353800436845 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 100, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3861349103797888, 'min_weight_fraction_leaf': 0.08960575345471988}. Best is trial 15 with value: 0.7572849484519277.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:27:10,685] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 289, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.0015754650744169152}. Best is trial 15 with value: 0.7572849484519277.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 22:27:11,223] Trial 19 finished with value: 0.6786787744649703 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 187, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6687006907779914, 'min_weight_fraction_leaf': 0.2047592648179435}. Best is trial 15 with value: 0.7572849484519277.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 22:27:11,648] Trial 20 finished with value: 0.7839268317994365 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 89, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7175509123723454, 'min_weight_fraction_leaf': 0.10521853896660721}. Best is trial 20 with value: 0.7839268317994365.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 22:27:11,999] Trial 21 finished with value: 0.7300192593991303 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 79, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7031450748447657, 'min_weight_fraction_leaf': 0.09403903585726361}. Best is trial 20 with value: 0.7839268317994365.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8283261802575107
[I 2024-04-16 22:27:12,634] Trial 22 finished with value: 0.7824269267844081 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 152, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6098864513030943, 'min_weight_fraction_leaf': 0.12170977787094135}. Best is trial 20 with value: 0.7839268317994365.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 22:27:12,890] Trial 23 finished with value: 0.7877806145769775 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 21, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.612388364912981, 'min_weight_fraction_leaf': 0.04561569622889031}. Best is trial 23 with value: 0.7877806145769775.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 22:27:13,151] Trial 24 finished with value: 0.7999244832738667 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 28, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5945370691033937, 'min_weight_fraction_leaf': 0.053281515068204915}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.49203187250996017
Fold 2 C-index: 0.7616279069767442
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.6673003802281369
Fold 5 C-index: 0.48068669527896996
[I 2024-04-16 22:27:13,329] Trial 25 finished with value: 0.63181873270089 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 4, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4547673780685811, 'min_weight_fraction_leaf': 0.04996091221009652}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 22:27:14,178] Trial 26 finished with value: 0.6663763013235233 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 45, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.2871142790618468, 'min_weight_fraction_leaf': 0.037039062886846254}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 22:27:14,439] Trial 27 finished with value: 0.7922020480583813 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 28, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5158783707916587, 'min_weight_fraction_leaf': 0.06598691661059801}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:27:14,624] Trial 28 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 21, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5202420447021523, 'min_weight_fraction_leaf': 0.46961689585527955}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 22:27:15,732] Trial 29 finished with value: 0.7702942146882898 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3719168657740124, 'min_weight_fraction_leaf': 0.0713932172807959}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7510729613733905
[I 2024-04-16 22:27:15,972] Trial 30 finished with value: 0.718731646723884 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 40, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5897285086805036, 'min_weight_fraction_leaf': 0.021168508687250828}. Best is trial 24 with value: 0.7999244832738667.

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7424892703862661
[I 2024-04-16 22:27:16,310] Trial 31 finished with value: 0.7450836287108459 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 89, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6115041201105692, 'min_weight_fraction_leaf': 0.07529457384788989}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 22:27:16,715] Trial 32 finished with value: 0.7891534508186784 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 106, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5041709909476946, 'min_weight_fraction_leaf': 0.06275815026057982}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 22:27:17,011] Trial 33 finished with value: 0.7778383668899079 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 21, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5060458087305748, 'min_weight_fraction_leaf': 0.05994930115816848}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 22:27:17,341] Trial 34 finished with value: 0.7450364060708232 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 62, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3919948296728538, 'min_weight_fraction_leaf': 0.023576029209776687}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 22:27:18,039] Trial 35 finished with value: 0.6618125355016858 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 109, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4662710037037924, 'min_weight_fraction_leaf': 0.19476322320546924}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:27:18,414] Trial 36 finished with value: 0.5 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 28, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5268973035148778, 'min_weight_fraction_leaf': 0.38971770475262413}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 22:27:18,718] Trial 37 finished with value: 0.6460461608102859 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 74, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6401214919324493, 'min_weight_fraction_leaf': 0.2889936764724038}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7553648068669528
[I 2024-04-16 22:27:19,182] Trial 38 finished with value: 0.7517656861973904 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 124, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3198045057515263, 'min_weight_fraction_leaf': 0.06699213680332672}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.4903100775193798
Fold 3 C-index: 0.30425531914893617
Fold 4 C-index: 0.38022813688212925
Fold 5 C-index: 0.5364806866952789
[I 2024-04-16 22:27:19,364] Trial 39 finished with value: 0.45221500341169457 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 2, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5513036300755328, 'min_weight_fraction_leaf': 0.008478210005256219}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:27:20,366] Trial 40 finished with value: 0.5 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.43468184041368385, 'min_weight_fraction_leaf': 0.42733722871780283}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8025751072961373
[I 2024-04-16 22:27:20,756] Trial 41 finished with value: 0.786556444150027 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 94, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6273061563283064, 'min_weight_fraction_leaf': 0.10637509234156475}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 22:27:21,045] Trial 42 finished with value: 0.7790118129920596 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 56, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6164425687958124, 'min_weight_fraction_leaf': 0.039624372585458756}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7267441860465116
Fold 3 C-index: 0.8531914893617021
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 22:27:23,210] Trial 43 finished with value: 0.7182793874400513 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 43, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5600036197598728, 'min_weight_fraction_leaf': 0.08742449741166494}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.5278969957081545
[I 2024-04-16 22:27:25,230] Trial 44 finished with value: 0.6220741639573587 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 214, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4844175747650499, 'min_weight_fraction_leaf': 0.12204423321537092}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 22:27:26,089] Trial 45 finished with value: 0.7157517489250119 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 175, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7291844385738098, 'min_weight_fraction_leaf': 0.1516538096539411}. Best is trial 24 with value: 0.7999244832738667.

Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8927038626609443
[I 2024-04-16 22:27:26,804] Trial 46 finished with value: 0.7975395138249034 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 107, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7438723611436409, 'min_weight_fraction_leaf': 0.03993350527314018}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6180257510729614
[I 2024-04-16 22:27:27,385] Trial 47 finished with value: 0.6647065921586429 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 26, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.42581868302241566, 'min_weight_fraction_leaf': 0.03606885164861798}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8154506437768241
[I 2024-04-16 22:27:28,091] Trial 48 finished with value: 0.7398991153868522 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 116, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8248732462756444, 'min_weight_fraction_leaf': 0.05743142223461807}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 22:35:38,304] Trial 49 finished with value: 0.7740102565229516 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7375840189864764, 'min_weight_fraction_leaf': 0.02900897691743311}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 22:35:39,655] Trial 50 finished with value: 0.8061742964895082 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 350, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8580859398770397, 'min_weight_fraction_leaf': 0.14067466804198955}. Best is trial 50 with value: 0.8061742964895082.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.9141630901287554
[I 2024-04-16 22:35:41,258] Trial 51 finished with value: 0.8345109680877927 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 369, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8650780732103325, 'min_weight_fraction_leaf': 0.07836530237930157}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 22:35:43,257] Trial 52 finished with value: 0.8118997310422689 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 382, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9368700755827909, 'min_weight_fraction_leaf': 0.13447102711070466}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 22:35:44,185] Trial 53 finished with value: 0.801596270492346 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 347, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9333985785267058, 'min_weight_fraction_leaf': 0.17098721901271324}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 22:35:45,081] Trial 54 finished with value: 0.7883044323959387 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 354, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9223836761742507, 'min_weight_fraction_leaf': 0.18255482980599205}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 22:35:46,099] Trial 55 finished with value: 0.6482113869397063 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.850640872005829, 'min_weight_fraction_leaf': 0.22456808619691168}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 22:35:47,101] Trial 56 finished with value: 0.8045156871530021 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 312, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9504873149405666, 'min_weight_fraction_leaf': 0.14183520465682528}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 22:35:47,845] Trial 57 finished with value: 0.7476944411137867 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 335, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9549982016992005, 'min_weight_fraction_leaf': 0.1632420912078524}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 22:35:50,741] Trial 58 finished with value: 0.7041938058364086 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 289, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9955977767169721, 'min_weight_fraction_leaf': 0.139303061496208}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 22:35:51,933] Trial 59 finished with value: 0.6850776550936483 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 407, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9316447705416647, 'min_weight_fraction_leaf': 0.2770418832937534}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 22:35:52,817] Trial 60 finished with value: 0.7659333705752307 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.858061041207964, 'min_weight_fraction_leaf': 0.20492284757517695}. Best is trial 51 with value: 0.8345109680877927.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 22:35:53,647] Trial 61 finished with value: 0.8072715857181292 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.895774589556567, 'min_weight_fraction_leaf': 0.13260279061395738}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 22:35:54,423] Trial 62 finished with value: 0.8087820359158744 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 317, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8981332031409504, 'min_weight_fraction_leaf': 0.13337740856374872}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 22:35:55,278] Trial 63 finished with value: 0.8072173346373459 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.89018545929469, 'min_weight_fraction_leaf': 0.13345593137281736}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 22:35:56,042] Trial 64 finished with value: 0.8039397464932385 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8837514156336624, 'min_weight_fraction_leaf': 0.13743872464484008}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 22:35:56,761] Trial 65 finished with value: 0.8022232887177733 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 297, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7835122881802231, 'min_weight_fraction_leaf': 0.11229139643403509}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7253218884120172
[I 2024-04-16 22:35:57,409] Trial 66 finished with value: 0.7125273202159338 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 373, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8328417978438267, 'min_weight_fraction_leaf': 0.15095298703120333}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 22:35:58,227] Trial 67 finished with value: 0.8192305249719898 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8966863484745369, 'min_weight_fraction_leaf': 0.08534464991274132}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 22:35:58,788] Trial 68 finished with value: 0.7895818286565903 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.978346026643418, 'min_weight_fraction_leaf': 0.09273408393147946}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 22:35:59,677] Trial 69 finished with value: 0.8102956431944776 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 274, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.896331905162175, 'min_weight_fraction_leaf': 0.12035329094677631}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.871244635193133
[I 2024-04-16 22:36:00,491] Trial 70 finished with value: 0.8079169388264177 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 270, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9017688247437723, 'min_weight_fraction_leaf': 0.08377148583149059}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 22:36:01,268] Trial 71 finished with value: 0.7983010681646548 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 278, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.891832704671649, 'min_weight_fraction_leaf': 0.12184359415244413}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8927038626609443
[I 2024-04-16 22:36:02,035] Trial 72 finished with value: 0.8130993617058649 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 271, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9102780085257545, 'min_weight_fraction_leaf': 0.07813836666294671}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 22:36:02,712] Trial 73 finished with value: 0.7998076505962926 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 254, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9138857823629444, 'min_weight_fraction_leaf': 0.07760837137280302}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 22:36:03,333] Trial 74 finished with value: 0.8086401909388299 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7932478141389542, 'min_weight_fraction_leaf': 0.09585515657733794}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8669527896995708
[I 2024-04-16 22:36:03,958] Trial 75 finished with value: 0.8097308691495133 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 235, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.768048780360931, 'min_weight_fraction_leaf': 0.08472098125787089}. Best is trial 51 with value: 0.8345109680877927.

Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.5278969957081545
[I 2024-04-16 22:36:05,840] Trial 76 finished with value: 0.6077421067160182 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 229, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8075950318465789, 'min_weight_fraction_leaf': 0.10238704048789282}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 22:36:06,491] Trial 77 finished with value: 0.8053956752022688 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 237, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7673803604130273, 'min_weight_fraction_leaf': 0.11299645952197773}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.871244635193133
[I 2024-04-16 22:36:07,097] Trial 78 finished with value: 0.8088475970325533 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 202, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8265609743395299, 'min_weight_fraction_leaf': 0.09652130656141297}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:36:07,726] Trial 79 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 194, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9626257579282349, 'min_weight_fraction_leaf': 0.4970767359615762}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 22:36:09,822] Trial 80 finished with value: 0.7313420533362782 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 19, 'max_depth': 18, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8393510141017606, 'min_weight_fraction_leaf': 0.07992117300354869}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 22:36:10,950] Trial 81 finished with value: 0.812638992208535 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 246, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7918630780504825, 'min_weight_fraction_leaf': 0.10229656223682107}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 22:36:12,077] Trial 82 finished with value: 0.8097453262522389 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 300, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8756895757277906, 'min_weight_fraction_leaf': 0.11757230018978515}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 22:36:12,887] Trial 83 finished with value: 0.807919942472151 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8726637848385762, 'min_weight_fraction_leaf': 0.11382370857816454}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7725321888412017
[I 2024-04-16 22:36:13,690] Trial 84 finished with value: 0.7704249207701752 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 295, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8061519296879504, 'min_weight_fraction_leaf': 0.09515235358222952}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 22:36:14,218] Trial 85 finished with value: 0.7697903027420463 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 246, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7614101494119764, 'min_weight_fraction_leaf': 0.05368501986833329}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8369098712446352
[I 2024-04-16 22:36:14,822] Trial 86 finished with value: 0.7980794918103985 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8672025396777255, 'min_weight_fraction_leaf': 0.15838375423479073}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 22:36:15,852] Trial 87 finished with value: 0.8168764432002176 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 390, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.821099320531621, 'min_weight_fraction_leaf': 0.07219095881107078}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 22:36:18,629] Trial 88 finished with value: 0.6418944800226886 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 375, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9410457375171901, 'min_weight_fraction_leaf': 0.016074649059118228}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8841201716738197
[I 2024-04-16 22:36:19,797] Trial 89 finished with value: 0.8111823792625452 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9747877453952127, 'min_weight_fraction_leaf': 0.07239963989752378}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8669527896995708
[I 2024-04-16 22:36:20,563] Trial 90 finished with value: 0.8031613891936974 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9993570244260745, 'min_weight_fraction_leaf': 0.06937148653050808}. Best is trial 51 with value: 0.8345109680877927.

Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8927038626609443
[I 2024-04-16 22:36:21,836] Trial 91 finished with value: 0.8136959302089742 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9761926707915443, 'min_weight_fraction_leaf': 0.07539349300221282}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8841201716738197
[I 2024-04-16 22:36:23,244] Trial 92 finished with value: 0.8135443171331339 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 420, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9178848241272458, 'min_weight_fraction_leaf': 0.06881178939245426}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8969957081545065
[I 2024-04-16 22:41:41,258] Trial 93 finished with value: 0.8168871695376991 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 420, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9726464389425372, 'min_weight_fraction_leaf': 0.04860102614756785}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 22:41:42,880] Trial 94 finished with value: 0.8363648293898092 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 420, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9661961925179824, 'min_weight_fraction_leaf': 0.05044552883677316}. Best is trial 94 with value: 0.8363648293898092.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 22:41:44,781] Trial 95 finished with value: 0.8420040749825455 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 468, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9149322253821399, 'min_weight_fraction_leaf': 0.0472298750691944}. Best is trial 95 with value: 0.8420040749825455.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 22:41:47,177] Trial 96 finished with value: 0.8420072320634038 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 474, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9186714469202719, 'min_weight_fraction_leaf': 0.04956115599708024}. Best is trial 96 with value: 0.8420072320634038.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 22:41:48,491] Trial 97 finished with value: 0.8063263334084045 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 469, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.964556183783718, 'min_weight_fraction_leaf': 0.045349231505527596}. Best is trial 96 with value: 0.8420072320634038.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 22:41:49,230] Trial 98 finished with value: 0.8016468008219135 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 421, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9181873113334154, 'min_weight_fraction_leaf': 0.0021149043736411396}. Best is trial 96 with value: 0.8420072320634038.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9276595744680851

[I 2024-04-16 22:42:00,648] A new study created in memory with name: no-name-0317b728-8c08-480b-aed9-2ce2e794fc74

Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 22:42:00,590] Trial 99 finished with value: 0.833109564461272 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9775205205061748, 'min_weight_fraction_leaf': 0.025836771862969607}. Best is trial 96 with value: 0.8420072320634038.


* Best trial for C-index:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.8420072320634038], datetime_start=datetime.datetime(2024, 4, 16, 22, 41, 44, 787670), datetime_complete=datetime.datetime(2024, 4, 16, 22, 41, 47, 176657), params={'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 474, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9186714469202719, 'min_weight_fraction_leaf': 0.04956115599708024}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=96, value=None)


* Best Score for C-index:
 0.8420072320634038

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2458308290335683
Fold 2 IBS: 0.21843205852973288
Fold 3 IBS: 0.21441509219214497
Fold 4 IBS: 0.2444058540887671
Fold 5 IBS: 0.23326299386163582
[I 2024-04-16 22:42:02,920] Trial 0 finished with value: 0.2312693655411698 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.2312693655411698.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-16 22:42:05,708] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.2312693655411698.
Fold 1 IBS: 0.2422217804898227
Fold 2 IBS: 0.20604215939156156
Fold 3 IBS: 0.20536348887036088
Fold 4 IBS: 0.23816713819570307
Fold 5 IBS: 0.23443654693516552
[I 2024-04-16 22:42:08,183] Trial 2 finished with value: 0.22524622277652276 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 2 with value: 0.22524622277652276.
Fold 1 IBS: 0.23997737551317644
Fold 2 IBS: 0.20628917387182416
Fold 3 IBS: 0.19999308418823725
Fold 4 IBS: 0.2364990518088652
Fold 5 IBS: 0.2312952255166902
[I 2024-04-16 22:42:09,000] Trial 3 finished with value: 0.22281078217975864 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-16 22:42:11,081] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-16 22:42:12,109] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.2471773923605192
Fold 2 IBS: 0.21732133101414405
Fold 3 IBS: 0.21608483753650748
Fold 4 IBS: 0.2446264041325047
Fold 5 IBS: 0.2336320559523974
[I 2024-04-16 22:42:14,206] Trial 6 finished with value: 0.23176840419921457 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24753232495746105
Fold 2 IBS: 0.22863034299161297
Fold 3 IBS: 0.22780059870027192
Fold 4 IBS: 0.24525231645256226
Fold 5 IBS: 0.22980036498615944
[I 2024-04-16 22:42:15,458] Trial 7 finished with value: 0.23580318961761354 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24388792032844758
Fold 2 IBS: 0.20431268727524246
Fold 3 IBS: 0.20272723355028044
Fold 4 IBS: 0.2323397363347534
Fold 5 IBS: 0.24009730434274343
[I 2024-04-16 22:42:15,835] Trial 8 finished with value: 0.2246729763662935 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.2463750753680711
Fold 2 IBS: 0.23137427725039786
Fold 3 IBS: 0.22881548983290517
Fold 4 IBS: 0.24172449141228589
Fold 5 IBS: 0.23039951809375644
[I 2024-04-16 22:42:18,983] Trial 9 finished with value: 0.2357377703914833 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24657852287672213
Fold 2 IBS: 0.23206316112817363
Fold 3 IBS: 0.23003515681903183
Fold 4 IBS: 0.2412906026999272
Fold 5 IBS: 0.22957933452614643
[I 2024-04-16 22:42:19,858] Trial 10 finished with value: 0.2359093556100002 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.25578614141973877, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24957527092392598
Fold 2 IBS: 0.22095833564497003
Fold 3 IBS: 0.22451358571145658
Fold 4 IBS: 0.23060380529406801
Fold 5 IBS: 0.2239626552625768
[I 2024-04-16 22:42:20,048] Trial 11 finished with value: 0.22992273056739948 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 4, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.15140395801593098}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24023311319978927
Fold 2 IBS: 0.20654639843048508
Fold 3 IBS: 0.2105997477995539
Fold 4 IBS: 0.237375222973572
Fold 5 IBS: 0.22992356847238266
[I 2024-04-16 22:42:20,909] Trial 12 finished with value: 0.22493561017515656 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 63, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.16694541300368826}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.2397712237804985
Fold 2 IBS: 0.21059242308473916
Fold 3 IBS: 0.20295179527005874
Fold 4 IBS: 0.23391501821825889
Fold 5 IBS: 0.22771604186877867
[I 2024-04-16 22:42:23,922] Trial 13 finished with value: 0.2229893004444668 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8757004183768704, 'min_weight_fraction_leaf': 0.12942492296949484}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.23887694209074434
Fold 2 IBS: 0.2134098978318189
Fold 3 IBS: 0.20587933877935985
Fold 4 IBS: 0.23635078736680823
Fold 5 IBS: 0.22529646039343412
[I 2024-04-16 22:42:25,082] Trial 14 finished with value: 0.2239626852924331 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 5, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9015509519801813, 'min_weight_fraction_leaf': 0.2319873930301426}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.22839809695394112

Fold 2 IBS: 0.20514152743957886
Fold 3 IBS: 0.20092249425472394
Fold 4 IBS: 0.2267763825894776
Fold 5 IBS: 0.2165164172534966
[I 2024-04-16 22:42:26,136] Trial 15 finished with value: 0.21555098369824366 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 138, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6967810217991331, 'min_weight_fraction_leaf': 0.10514124205272785}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2467245753421851
Fold 2 IBS: 0.23215086227692838
Fold 3 IBS: 0.22944190979967086
Fold 4 IBS: 0.24159087177588787
Fold 5 IBS: 0.2303525764883273
[I 2024-04-16 22:42:27,293] Trial 16 finished with value: 0.2360521591365999 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 231, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6778661833429002, 'min_weight_fraction_leaf': 0.35612645124522524}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2388284357689523
Fold 2 IBS: 0.21255562783348272
Fold 3 IBS: 0.19795960994236278
Fold 4 IBS: 0.23366309896652035
Fold 5 IBS: 0.21908035151857583
[I 2024-04-16 22:42:28,057] Trial 17 finished with value: 0.22041742480597878 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 100, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3861349103797888, 'min_weight_fraction_leaf': 0.08960575345471988}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24132280104394047
Fold 2 IBS: 0.21269327432629742
Fold 3 IBS: 0.20049020592168434
Fold 4 IBS: 0.24087378277320573
Fold 5 IBS: 0.22425840634695127
[I 2024-04-16 22:42:29,029] Trial 18 finished with value: 0.22392769408241583 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 99, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.3311809976298237, 'min_weight_fraction_leaf': 0.0013669683957226175}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24688611571045718
Fold 2 IBS: 0.23219132054830785
Fold 3 IBS: 0.23027940191796936
Fold 4 IBS: 0.2409026395193649
Fold 5 IBS: 0.22930251676390168
[I 2024-04-16 22:42:30,535] Trial 19 finished with value: 0.23591239889200016 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.10730942678329708, 'min_weight_fraction_leaf': 0.21750931502909437}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24536664618236573
Fold 2 IBS: 0.2357094417147659
Fold 3 IBS: 0.21756007685466264
Fold 4 IBS: 0.2351394543483008
Fold 5 IBS: 0.2245456493888334
[I 2024-04-16 22:42:30,733] Trial 20 finished with value: 0.23166425369778568 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3772282506046544, 'min_weight_fraction_leaf': 0.08406658048281501}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2440283698606937
Fold 2 IBS: 0.21764096243387274
Fold 3 IBS: 0.21271440236923256
Fold 4 IBS: 0.23885081521770216
Fold 5 IBS: 0.2333205794826251
[I 2024-04-16 22:42:40,681] Trial 21 finished with value: 0.22931102587282526 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 184, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6547034385443382, 'min_weight_fraction_leaf': 0.11712848599628017}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.23989681726525797
Fold 2 IBS: 0.21257567014754183
Fold 3 IBS: 0.20496080476015688
Fold 4 IBS: 0.23573527504580374
Fold 5 IBS: 0.2401811583699638
[I 2024-04-16 22:42:41,267] Trial 22 finished with value: 0.22666994511774483 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 85, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6873159527855055, 'min_weight_fraction_leaf': 0.05847692406679354}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24662017777674988
Fold 2 IBS: 0.2321469807414623
Fold 3 IBS: 0.2297372799644881
Fold 4 IBS: 0.2412254547631197
Fold 5 IBS: 0.2298155591809165
[I 2024-04-16 22:42:42,085] Trial 23 finished with value: 0.2359090904853473 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 138, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.242935508884002, 'min_weight_fraction_leaf': 0.19289553221610561}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.23585018430451674
Fold 2 IBS: 0.20314428554405467
Fold 3 IBS: 0.1987071229364999
Fold 4 IBS: 0.2270924304194166
Fold 5 IBS: 0.2222151698718961
[I 2024-04-16 22:42:43,989] Trial 24 finished with value: 0.21740183861527682 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 221, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4214218271993085, 'min_weight_fraction_leaf': 0.1063490999450386}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.23764386500385992
Fold 2 IBS: 0.21572081027096882
Fold 3 IBS: 0.20688911926768339
Fold 4 IBS: 0.23390279551321708
Fold 5 IBS: 0.2244570150053522
[I 2024-04-16 22:42:45,956] Trial 25 finished with value: 0.22372272101221627 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 219, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.46423262855736735, 'min_weight_fraction_leaf': 0.03989016828055364}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2466435841775417
Fold 2 IBS: 0.23225630869945743
Fold 3 IBS: 0.22989986339484095
Fold 4 IBS: 0.24118506766749884
Fold 5 IBS: 0.2302270252070719
[I 2024-04-16 22:42:50,548] Trial 26 finished with value: 0.23604236982928217 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 308, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.2871142790618468, 'min_weight_fraction_leaf': 0.2830550434153414}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24581839690270998
Fold 2 IBS: 0.23209782103745266
Fold 3 IBS: 0.2301979993648951
Fold 4 IBS: 0.24136593180524166
Fold 5 IBS: 0.23032438582493162
[I 2024-04-16 22:42:50,958] Trial 27 finished with value: 0.23596090698704622 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 48, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.1729529760271648, 'min_weight_fraction_leaf': 0.09037604869015846}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24656075558902663
Fold 2 IBS: 0.23213951345883066
Fold 3 IBS: 0.23002825142879788
Fold 4 IBS: 0.2411104649641026
Fold 5 IBS: 0.22975811808319055
[I 2024-04-16 22:42:51,608] Trial 28 finished with value: 0.23591942070478966 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 99, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3965788725022428, 'min_weight_fraction_leaf': 0.46961689585527955}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24630859844407268
Fold 2 IBS: 0.2322956347000389
Fold 3 IBS: 0.22955007442663075
Fold 4 IBS: 0.24141130613962739
Fold 5 IBS: 0.23029996757106383
[I 2024-04-16 22:43:04,313] Trial 29 finished with value: 0.23597311625628672 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5102179166457144, 'min_weight_fraction_leaf': 0.41528561873840175}. Best is trial 15 with value: 0.21555098369824366.

Fold 1 IBS: 0.24189951983836425
Fold 2 IBS: 0.22116291305449884
Fold 3 IBS: 0.21713072638394984
Fold 4 IBS: 0.24023416048014104
Fold 5 IBS: 0.22691624187044754
[I 2024-04-16 22:43:05,381] Trial 30 finished with value: 0.2294687123254803 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 180, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5988223393644435, 'min_weight_fraction_leaf': 0.20241101766143602}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24364620279536037
Fold 2 IBS: 0.2205505651382432
Fold 3 IBS: 0.21184589055027794
Fold 4 IBS: 0.24142198209294274
Fold 5 IBS: 0.2268782233658812
[I 2024-04-16 22:43:06,351] Trial 31 finished with value: 0.22886857278854106 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 162, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4032327849321123, 'min_weight_fraction_leaf': 0.11708530604258689}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24661093959371452
Fold 2 IBS: 0.2301025933150535
Fold 3 IBS: 0.22780980093586722
Fold 4 IBS: 0.24300904078398428
Fold 5 IBS: 0.230890565198856
[I 2024-04-16 22:43:07,225] Trial 32 finished with value: 0.2356845879654951 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 140, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8550327764351591, 'min_weight_fraction_leaf': 0.09887734225836066}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2424013858898089
Fold 2 IBS: 0.22181355253513207
Fold 3 IBS: 0.21628743919777896
Fold 4 IBS: 0.2454744216544916
Fold 5 IBS: 0.23210919596554697
[I 2024-04-16 22:43:08,594] Trial 33 finished with value: 0.2316171990485517 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 9, 'n_estimators': 231, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7143311025567932, 'min_weight_fraction_leaf': 0.059053506325031944}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2343422980803409
Fold 2 IBS: 0.19726504628882152
Fold 3 IBS: 0.19589228360095498
Fold 4 IBS: 0.22148252413832495
Fold 5 IBS: 0.214706958088969
[I 2024-04-16 22:43:10,445] Trial 34 finished with value: 0.21273782203948227 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 206, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5121057659041139, 'min_weight_fraction_leaf': 0.09009257320408029}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.23551743581515994
Fold 2 IBS: 0.1988816220790032
Fold 3 IBS: 0.19713820389502454
Fold 4 IBS: 0.2194355626151018
Fold 5 IBS: 0.2139468393382114
[I 2024-04-16 22:43:15,366] Trial 35 finished with value: 0.2129839327485002 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5035601925130949, 'min_weight_fraction_leaf': 0.030526656384477324}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.23568872403345578
Fold 2 IBS: 0.19973786792004417
Fold 3 IBS: 0.19454987157876255
Fold 4 IBS: 0.2220374053163543
Fold 5 IBS: 0.21894163635279854
[I 2024-04-16 22:43:18,196] Trial 36 finished with value: 0.2141911010402831 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 295, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5262952246734235, 'min_weight_fraction_leaf': 0.0345815739535376}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.2448880936287523
Fold 2 IBS: 0.19358697937735503
Fold 3 IBS: 0.19135743911323064
Fold 4 IBS: 0.22209877079990858
Fold 5 IBS: 0.2136995510425158
[I 2024-04-16 22:43:33,074] Trial 37 finished with value: 0.21312616679235247 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 353, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5274918233702399, 'min_weight_fraction_leaf': 0.02265299373602317}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.2448767682487151
Fold 2 IBS: 0.1940286543150714
Fold 3 IBS: 0.19114962341732433
Fold 4 IBS: 0.22260340040871293
Fold 5 IBS: 0.2137471478793161
[I 2024-04-16 22:43:37,841] Trial 38 finished with value: 0.213281118853828 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 358, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5285575239051581, 'min_weight_fraction_leaf': 0.020652803664130342}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.25250559243829124
Fold 2 IBS: 0.2142865173352782
Fold 3 IBS: 0.2171359677193678
Fold 4 IBS: 0.24416225491761936
Fold 5 IBS: 0.23974411262472503
[I 2024-04-16 22:43:43,008] Trial 39 finished with value: 0.2335668890070563 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 366, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6097100988293976, 'min_weight_fraction_leaf': 0.019130885670483717}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.242901108432075
Fold 2 IBS: 0.19697988117930024
Fold 3 IBS: 0.19238091011496858
Fold 4 IBS: 0.22078058275151072
Fold 5 IBS: 0.21495218733382793
[I 2024-04-16 22:43:46,552] Trial 40 finished with value: 0.21359893396233648 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4791645577618608, 'min_weight_fraction_leaf': 0.0694663236398695}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.23908968735515912
Fold 2 IBS: 0.1947617350535389
Fold 3 IBS: 0.1930636406143849
Fold 4 IBS: 0.22123635288762244
Fold 5 IBS: 0.21467012929006576
[I 2024-04-16 22:43:50,467] Trial 41 finished with value: 0.2125643090401542 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4831314083966843, 'min_weight_fraction_leaf': 0.06563330905051376}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2396028413626137
Fold 2 IBS: 0.19718848617005288
Fold 3 IBS: 0.1948104348257847
Fold 4 IBS: 0.21837938467562384
Fold 5 IBS: 0.2149288714625758
[I 2024-04-16 22:43:55,428] Trial 42 finished with value: 0.21298200369933024 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 392, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5583443788864256, 'min_weight_fraction_leaf': 0.020815822054945837}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2396687176213861
Fold 2 IBS: 0.19612731372046435
Fold 3 IBS: 0.19260264364145704
Fold 4 IBS: 0.21936281835328128
Fold 5 IBS: 0.21697387881345614
[I 2024-04-16 22:44:00,443] Trial 43 finished with value: 0.212947074430009 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 398, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5930099345609534, 'min_weight_fraction_leaf': 0.0495559888649342}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2467168371470764
Fold 2 IBS: 0.23064557906926417
Fold 3 IBS: 0.2276870878947108
Fold 4 IBS: 0.24249203531915456
Fold 5 IBS: 0.2307608809971462
[I 2024-04-16 22:44:12,600] Trial 44 finished with value: 0.2356604840854704 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 394, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5868150496992739, 'min_weight_fraction_leaf': 0.05755833486941584}. Best is trial 41 with value: 0.2125643090401542.

Fold 1 IBS: 0.24970180838617465
Fold 2 IBS: 0.20711640796461644
Fold 3 IBS: 0.210622445605441
Fold 4 IBS: 0.2398038048480638
Fold 5 IBS: 0.23687430367329662
[I 2024-04-16 22:44:16,093] Trial 45 finished with value: 0.22882375409551847 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 481, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6241818506764952, 'min_weight_fraction_leaf': 0.003649071529300437}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.23201805390304453
Fold 2 IBS: 0.20002733588165444
Fold 3 IBS: 0.19908476397700547
Fold 4 IBS: 0.22074033459452136
Fold 5 IBS: 0.21494542822340232
[I 2024-04-16 22:44:22,474] Trial 46 finished with value: 0.2133631833159256 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 419, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5598513951057802, 'min_weight_fraction_leaf': 0.14065807022429982}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.25373498445062415
Fold 2 IBS: 0.19975024860475576
Fold 3 IBS: 0.18626200905063714
Fold 4 IBS: 0.23343402582868134
Fold 5 IBS: 0.2162436088485457
[I 2024-04-16 22:44:27,794] Trial 47 finished with value: 0.21788497535664883 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 401, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.456067991993716, 'min_weight_fraction_leaf': 0.04492679621107826}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.24471890993869544
Fold 2 IBS: 0.2177801752519796
Fold 3 IBS: 0.2138769702970347
Fold 4 IBS: 0.24414741845988078
Fold 5 IBS: 0.23442893665869308
[I 2024-04-16 22:44:43,187] Trial 48 finished with value: 0.23099048212125672 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 451, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7258961740431729, 'min_weight_fraction_leaf': 0.08041738051512136}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.25137663968626234
Fold 2 IBS: 0.20933386581443944
Fold 3 IBS: 0.2080886887712674
Fold 4 IBS: 0.2390514698710601
Fold 5 IBS: 0.23530782004401327
[I 2024-04-16 22:44:46,404] Trial 49 finished with value: 0.22863169683740853 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 329, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6352263471927108, 'min_weight_fraction_leaf': 0.06926131111849082}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2360626460552677
Fold 2 IBS: 0.20623441042932847
Fold 3 IBS: 0.20130662121469356
Fold 4 IBS: 0.22957511854007973
Fold 5 IBS: 0.2179557393265252
[I 2024-04-16 22:44:49,170] Trial 50 finished with value: 0.2182269071131789 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 261, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.49402812735141344, 'min_weight_fraction_leaf': 0.16186576022040558}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.25013784901547137
Fold 2 IBS: 0.195316535389084
Fold 3 IBS: 0.18808126103485753
Fold 4 IBS: 0.22936838612837893
Fold 5 IBS: 0.21349776174083104
[I 2024-04-16 22:44:55,922] Trial 51 finished with value: 0.2152803586617246 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 339, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5509334567262397, 'min_weight_fraction_leaf': 0.027839511211907052}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2427342211563647
Fold 2 IBS: 0.1958477826874508
Fold 3 IBS: 0.20028177886831744
Fold 4 IBS: 0.22985892846448394
Fold 5 IBS: 0.22177135601929956
[I 2024-04-16 22:44:59,012] Trial 52 finished with value: 0.2180988134391833 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 281, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4433955231058734, 'min_weight_fraction_leaf': 0.012876902678362334}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.24397581332160848
Fold 2 IBS: 0.19953500021907264
Fold 3 IBS: 0.18917458509628868
Fold 4 IBS: 0.22839776163972092
Fold 5 IBS: 0.21811042015429574
[I 2024-04-16 22:45:04,539] Trial 53 finished with value: 0.21583871608619729 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 445, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5100539037151481, 'min_weight_fraction_leaf': 0.046932235033188746}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2347988257753084
Fold 2 IBS: 0.19668752838656633
Fold 3 IBS: 0.19211546662321186
Fold 4 IBS: 0.21780908681113587
Fold 5 IBS: 0.21515744682466584
[I 2024-04-16 22:45:09,252] Trial 54 finished with value: 0.21131367088417768 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 388, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5670320468073893, 'min_weight_fraction_leaf': 0.031478107602535506}. Best is trial 54 with value: 0.21131367088417768.
Fold 1 IBS: 0.24677947770699765
Fold 2 IBS: 0.23053037304430873
Fold 3 IBS: 0.2275728132543721
Fold 4 IBS: 0.24233405204889266
Fold 5 IBS: 0.23106120652731021
[I 2024-04-16 22:45:12,162] Trial 55 finished with value: 0.23565558451637628 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 392, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5737647614035145, 'min_weight_fraction_leaf': 0.07423158709263047}. Best is trial 54 with value: 0.21131367088417768.
Fold 1 IBS: 0.23689214883150628
Fold 2 IBS: 0.2120673796940858
Fold 3 IBS: 0.20315541673905635
Fold 4 IBS: 0.23098032372176497
Fold 5 IBS: 0.22253237757409347
[I 2024-04-16 22:45:16,244] Trial 56 finished with value: 0.22112552931210136 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 418, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.35399595847912424, 'min_weight_fraction_leaf': 0.13287864045187167}. Best is trial 54 with value: 0.21131367088417768.
Fold 1 IBS: 0.2418042867685856
Fold 2 IBS: 0.20876050442208302
Fold 3 IBS: 0.20680932595685791
Fold 4 IBS: 0.23860265094248106
Fold 5 IBS: 0.23053544081685107
[I 2024-04-16 22:45:18,874] Trial 57 finished with value: 0.22530244178137168 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 323, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.649610303071809, 'min_weight_fraction_leaf': 0.042873000646334}. Best is trial 54 with value: 0.21131367088417768.
Fold 1 IBS: 0.2424078057014189
Fold 2 IBS: 0.19483239886955803
Fold 3 IBS: 0.1957006646954686
Fold 4 IBS: 0.22122367318862327
Fold 5 IBS: 0.21799729720859018
[I 2024-04-16 22:45:22,111] Trial 58 finished with value: 0.2144323679327318 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 305, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4329823869456646, 'min_weight_fraction_leaf': 0.05393151837123201}. Best is trial 54 with value: 0.21131367088417768.
Fold 1 IBS: 0.2318227492651181
Fold 2 IBS: 0.2004096906165338
Fold 3 IBS: 0.19250913676453307
Fold 4 IBS: 0.2145149387113131
Fold 5 IBS: 0.21608862724065606
[I 2024-04-16 22:45:24,993] Trial 59 finished with value: 0.21106902851963083 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 251, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.737660433782312, 'min_weight_fraction_leaf': 0.00011778406738288671}. Best is trial 59 with value: 0.21106902851963083.

Fold 1 IBS: 0.24516656524539981
Fold 2 IBS: 0.21062905264741455
Fold 3 IBS: 0.20928713648563754
Fold 4 IBS: 0.24177268946133224
Fold 5 IBS: 0.23349939521162735
[I 2024-04-16 22:45:28,133] Trial 60 finished with value: 0.2280709678102823 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 382, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7740796078428375, 'min_weight_fraction_leaf': 0.004254061138558238}. Best is trial 59 with value: 0.21106902851963083.
Fold 1 IBS: 0.23239287585025117
Fold 2 IBS: 0.19481155216054105
Fold 3 IBS: 0.19221809734433284
Fold 4 IBS: 0.21072513374212
Fold 5 IBS: 0.21430420045958357
[I 2024-04-16 22:45:47,850] Trial 61 finished with value: 0.20889037191136572 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 258, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7377275929061544, 'min_weight_fraction_leaf': 0.030622013808595125}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.23699492184296508
Fold 2 IBS: 0.20040108239906124
Fold 3 IBS: 0.19473792994851583
Fold 4 IBS: 0.2211524352297746
Fold 5 IBS: 0.21193828813811452
[I 2024-04-16 22:45:50,847] Trial 62 finished with value: 0.21304493151168624 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 252, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6744371054295076, 'min_weight_fraction_leaf': 0.016590925140165264}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.23928053090982188
Fold 2 IBS: 0.1936596610783976
Fold 3 IBS: 0.1908565913097194
Fold 4 IBS: 0.2136596034157615
Fold 5 IBS: 0.21619632218993348
[I 2024-04-16 22:45:58,965] Trial 63 finished with value: 0.21073054178072675 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 462, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7351622406813987, 'min_weight_fraction_leaf': 0.0003006902136090811}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.24020476969246154
Fold 2 IBS: 0.19629415252007748
Fold 3 IBS: 0.19025094185398114
Fold 4 IBS: 0.21475012076783115
Fold 5 IBS: 0.21301644327935212
[I 2024-04-16 22:46:13,421] Trial 64 finished with value: 0.21090328562274072 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 476, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7465470505675268, 'min_weight_fraction_leaf': 0.0023272127300384103}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.22993405190596755
Fold 2 IBS: 0.1998559263223298
Fold 3 IBS: 0.19199793628872658
Fold 4 IBS: 0.21593343290217692
Fold 5 IBS: 0.21578188257171663
[I 2024-04-16 22:46:20,141] Trial 65 finished with value: 0.2107006459981835 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 494, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7459236633132993, 'min_weight_fraction_leaf': 0.007694946674736216}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.24633591302363841
Fold 2 IBS: 0.23213986158018776
Fold 3 IBS: 0.2295520278725056
Fold 4 IBS: 0.24147959530165872
Fold 5 IBS: 0.2302765128959233
[I 2024-04-16 22:46:24,385] Trial 66 finished with value: 0.23595678213478277 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 495, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8287742581608164, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.24369000739500146
Fold 2 IBS: 0.21434232747391735
Fold 3 IBS: 0.21139458332988464
Fold 4 IBS: 0.24232956272573275
Fold 5 IBS: 0.2345267106479697
[I 2024-04-16 22:46:28,505] Trial 67 finished with value: 0.22925663831450116 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 454, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7522789839507332, 'min_weight_fraction_leaf': 0.000561806644931952}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.24455511870316463
Fold 2 IBS: 0.2267934884914344
Fold 3 IBS: 0.22466410581046875
Fold 4 IBS: 0.24050323119395856
Fold 5 IBS: 0.22915624250480857
[I 2024-04-16 22:46:32,272] Trial 68 finished with value: 0.23313443734076697 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 475, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7468960619194147, 'min_weight_fraction_leaf': 0.35364036783604025}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.2300787980001647
Fold 2 IBS: 0.19641627828017147
Fold 3 IBS: 0.19122863621161298
Fold 4 IBS: 0.21189349607756788
Fold 5 IBS: 0.21244170680598337
[I 2024-04-16 22:46:37,971] Trial 69 finished with value: 0.20841178307510008 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 493, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9133634021932744, 'min_weight_fraction_leaf': 0.03482005395654732}. Best is trial 69 with value: 0.20841178307510008.
Fold 1 IBS: 0.23082745033605492
Fold 2 IBS: 0.21258342376009118
Fold 3 IBS: 0.20163835694721952
Fold 4 IBS: 0.2224423063055546
Fold 5 IBS: 0.21255388838390268
[I 2024-04-16 23:02:19,039] Trial 70 finished with value: 0.21600908514656458 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 461, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9214187460767265, 'min_weight_fraction_leaf': 0.25717771363652614}. Best is trial 69 with value: 0.20841178307510008.
Fold 1 IBS: 0.23082723175570813
Fold 2 IBS: 0.20323092307506263
Fold 3 IBS: 0.19491966614269055
Fold 4 IBS: 0.2171154201350026
Fold 5 IBS: 0.216027037289287
[I 2024-04-16 23:03:39,795] Trial 71 finished with value: 0.2124240556795502 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 490, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7932890461516613, 'min_weight_fraction_leaf': 0.032131426880574826}. Best is trial 69 with value: 0.20841178307510008.
Fold 1 IBS: 0.23017369217350117
Fold 2 IBS: 0.20120230419550925
Fold 3 IBS: 0.193722336472291
Fold 4 IBS: 0.21617692077677259
Fold 5 IBS: 0.21617316312987098
[I 2024-04-16 23:03:45,000] Trial 72 finished with value: 0.211489683349589 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 496, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8066423104143661, 'min_weight_fraction_leaf': 0.034326469001936366}. Best is trial 69 with value: 0.20841178307510008.
Fold 1 IBS: 0.23070291890906766
Fold 2 IBS: 0.19797577360905477
Fold 3 IBS: 0.18899048202721042
Fold 4 IBS: 0.21031986359975194
Fold 5 IBS: 0.21398083574867297
[I 2024-04-16 23:03:56,331] Trial 73 finished with value: 0.20839397477875155 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 465, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9312721157462464, 'min_weight_fraction_leaf': 0.0012393034300419575}. Best is trial 73 with value: 0.20839397477875155.
Fold 1 IBS: 0.23615857055079026
Fold 2 IBS: 0.1966427796691383
Fold 3 IBS: 0.1929622046457027
Fold 4 IBS: 0.20870198205403534
Fold 5 IBS: 0.2125121533077471
[I 2024-04-16 23:04:03,685] Trial 74 finished with value: 0.20939553804548275 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 464, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9963604831342023, 'min_weight_fraction_leaf': 0.012116695798136328}. Best is trial 73 with value: 0.20839397477875155.

Fold 1 IBS: 0.23374241288259937
Fold 2 IBS: 0.19930439672774886
Fold 3 IBS: 0.18717738406829976
Fold 4 IBS: 0.20823176235963525
Fold 5 IBS: 0.21501371316102338
[I 2024-04-16 23:04:10,213] Trial 75 finished with value: 0.20869393383986132 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 435, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9528867121166885, 'min_weight_fraction_leaf': 0.0012590377645196535}. Best is trial 73 with value: 0.20839397477875155.
Fold 1 IBS: 0.24525891729558977
Fold 2 IBS: 0.21896003468791347
Fold 3 IBS: 0.21598508493564658
Fold 4 IBS: 0.24394612844374725
Fold 5 IBS: 0.2322350643210711
[I 2024-04-16 23:04:14,065] Trial 76 finished with value: 0.23127704593679366 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 11, 'n_estimators': 465, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9658026435569093, 'min_weight_fraction_leaf': 0.015592248007567035}. Best is trial 73 with value: 0.20839397477875155.
Fold 1 IBS: 0.23502608441142722
Fold 2 IBS: 0.19922817017063826
Fold 3 IBS: 0.1913519268015393
Fold 4 IBS: 0.207834087421465
Fold 5 IBS: 0.2143743871087013
[I 2024-04-16 23:04:19,929] Trial 77 finished with value: 0.2095629311827542 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 433, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9853092886561814, 'min_weight_fraction_leaf': 0.010625988750975616}. Best is trial 73 with value: 0.20839397477875155.
Fold 1 IBS: 0.24649287843030504
Fold 2 IBS: 0.2314585308300189
Fold 3 IBS: 0.2289401139897681
Fold 4 IBS: 0.2417606515795492
Fold 5 IBS: 0.2302679373267155
[I 2024-04-16 23:04:23,437] Trial 78 finished with value: 0.23578402243127136 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 432, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9996115065732951, 'min_weight_fraction_leaf': 0.41218066030994116}. Best is trial 73 with value: 0.20839397477875155.
Fold 1 IBS: 0.2320831075429349
Fold 2 IBS: 0.19874748876281936
Fold 3 IBS: 0.1868862737714415
Fold 4 IBS: 0.2088372674979119
Fold 5 IBS: 0.2146701772034217
[I 2024-04-16 23:04:29,515] Trial 79 finished with value: 0.20824486295570588 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 433, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9333351337148593, 'min_weight_fraction_leaf': 0.013312290067980048}. Best is trial 79 with value: 0.20824486295570588.
Fold 1 IBS: 0.2321051762336623
Fold 2 IBS: 0.19872958357290424
Fold 3 IBS: 0.1868058011919495
Fold 4 IBS: 0.20883435526793945
Fold 5 IBS: 0.21456058420717486
[I 2024-04-16 23:04:35,587] Trial 80 finished with value: 0.2082071000947261 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 434, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9378042438987818, 'min_weight_fraction_leaf': 0.015273006586386988}. Best is trial 80 with value: 0.2082071000947261.
Fold 1 IBS: 0.23313533084879992
Fold 2 IBS: 0.1981286213929884
Fold 3 IBS: 0.18691652009336918
Fold 4 IBS: 0.20977045296104274
Fold 5 IBS: 0.21423701428211908
[I 2024-04-16 23:04:42,027] Trial 81 finished with value: 0.20843758791566386 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 439, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9417972207458584, 'min_weight_fraction_leaf': 0.04295474256066548}. Best is trial 80 with value: 0.2082071000947261.
Fold 1 IBS: 0.23424681521074975
Fold 2 IBS: 0.19613148875309624
Fold 3 IBS: 0.18531675217461782
Fold 4 IBS: 0.21089939380355308
Fold 5 IBS: 0.21326941327667795
[I 2024-04-16 23:04:48,291] Trial 82 finished with value: 0.20797277264373898 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 431, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9407754324156289, 'min_weight_fraction_leaf': 0.04206241234084829}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23409773201844755
Fold 2 IBS: 0.19653382628018295
Fold 3 IBS: 0.1848127640243094
Fold 4 IBS: 0.21249359291139658
Fold 5 IBS: 0.21212141767021883
[I 2024-04-16 23:04:54,832] Trial 83 finished with value: 0.20801186658091106 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 407, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9384130833098913, 'min_weight_fraction_leaf': 0.04519634108137036}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.2329791447085086
Fold 2 IBS: 0.1967881823073177
Fold 3 IBS: 0.18728551841253535
Fold 4 IBS: 0.213032794231675
Fold 5 IBS: 0.21183681257533377
[I 2024-04-16 23:05:01,623] Trial 84 finished with value: 0.2083844904470741 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 411, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.925429012053495, 'min_weight_fraction_leaf': 0.05783142863073238}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.2447356385509223
Fold 2 IBS: 0.21001665735971864
Fold 3 IBS: 0.20948126396091446
Fold 4 IBS: 0.24093216180850846
Fold 5 IBS: 0.2324937799728014
[I 2024-04-16 23:05:05,695] Trial 85 finished with value: 0.22753190033057305 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 411, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9332004479717521, 'min_weight_fraction_leaf': 0.10710747728623181}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23246895566730055
Fold 2 IBS: 0.197925177609746
Fold 3 IBS: 0.18771443031867188
Fold 4 IBS: 0.21213172875001646
Fold 5 IBS: 0.2119327578096531
[I 2024-04-16 23:05:11,762] Trial 86 finished with value: 0.20843461003107758 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 440, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8874595645983381, 'min_weight_fraction_leaf': 0.06167441402952489}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23362791486913068
Fold 2 IBS: 0.19689264641068396
Fold 3 IBS: 0.18782225531230023
Fold 4 IBS: 0.21277906488160134
Fold 5 IBS: 0.2142720511235225
[I 2024-04-16 23:05:16,776] Trial 87 finished with value: 0.20907878651944775 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 441, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9017353280575152, 'min_weight_fraction_leaf': 0.08057063446482637}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.24405634920973077
Fold 2 IBS: 0.20958957820309626
Fold 3 IBS: 0.2098195749072522
Fold 4 IBS: 0.2397871849283553
Fold 5 IBS: 0.23205952756968465
[I 2024-04-16 23:05:19,832] Trial 88 finished with value: 0.22706244296362382 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 415, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8603916137186303, 'min_weight_fraction_leaf': 0.060569968472295434}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.2405934580650391
Fold 2 IBS: 0.20440412320775256
Fold 3 IBS: 0.19898625051637614
Fold 4 IBS: 0.2317675135857698
Fold 5 IBS: 0.21634911771450452
[I 2024-04-16 23:05:23,277] Trial 89 finished with value: 0.2184200926178884 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 406, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8837193202561466, 'min_weight_fraction_leaf': 0.04645664782974562}. Best is trial 82 with value: 0.20797277264373898.

Fold 1 IBS: 0.24308229605873613
Fold 2 IBS: 0.20243085243083073
Fold 3 IBS: 0.20257300733372727
Fold 4 IBS: 0.2350012477048381
Fold 5 IBS: 0.22812847237666628
[I 2024-04-16 23:05:26,584] Trial 90 finished with value: 0.2222431751809597 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 427, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9384169100812306, 'min_weight_fraction_leaf': 0.10055258156251395}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23494236000327381
Fold 2 IBS: 0.19851393414446025
Fold 3 IBS: 0.188316054669442
Fold 4 IBS: 0.20779679335240808
Fold 5 IBS: 0.21280969619087245
[I 2024-04-16 23:05:31,830] Trial 91 finished with value: 0.20847576767209133 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 442, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9619952733655167, 'min_weight_fraction_leaf': 0.040942271619228025}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23001265173746965
Fold 2 IBS: 0.1977150909325567
Fold 3 IBS: 0.19105114040885984
Fold 4 IBS: 0.21098586838673528
Fold 5 IBS: 0.2124489528575252
[I 2024-04-16 23:05:36,746] Trial 92 finished with value: 0.20844274086462936 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 449, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9098083130133213, 'min_weight_fraction_leaf': 0.055959244689231205}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23186934214354446
Fold 2 IBS: 0.19805339699670332
Fold 3 IBS: 0.1938995408571186
Fold 4 IBS: 0.21365134743523576
Fold 5 IBS: 0.213834084904634
[I 2024-04-16 23:05:41,744] Trial 93 finished with value: 0.21026154246744722 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 482, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9015170018833202, 'min_weight_fraction_leaf': 0.07022180710301966}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.2285498908935621
Fold 2 IBS: 0.20195173694905538
Fold 3 IBS: 0.1953268721154233
Fold 4 IBS: 0.21295922746705104
Fold 5 IBS: 0.2141875287765351
[I 2024-04-16 23:05:45,944] Trial 94 finished with value: 0.2105950512403254 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 419, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8354647860336294, 'min_weight_fraction_leaf': 0.055962542201087324}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23095232917209657
Fold 2 IBS: 0.1958865206360449
Fold 3 IBS: 0.18697181187731182
Fold 4 IBS: 0.21657103840856698
Fold 5 IBS: 0.21293289499416962
[I 2024-04-16 23:05:52,237] Trial 95 finished with value: 0.20866291901763798 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 452, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9126090538791146, 'min_weight_fraction_leaf': 0.09308205917407598}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23141696019440808
Fold 2 IBS: 0.1972469732359395
Fold 3 IBS: 0.19181384992497885
Fold 4 IBS: 0.2152661468482183
Fold 5 IBS: 0.21279056642111796
[I 2024-04-16 23:05:58,255] Trial 96 finished with value: 0.20970689932493256 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 469, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8661215594792465, 'min_weight_fraction_leaf': 0.023013782620960307}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23281842728585872
Fold 2 IBS: 0.1985355360657985
Fold 3 IBS: 0.1884611926825503
Fold 4 IBS: 0.21580615607654127
Fold 5 IBS: 0.2101267637405006
[I 2024-04-16 23:06:03,329] Trial 97 finished with value: 0.20914961517024988 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 379, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8846229014197279, 'min_weight_fraction_leaf': 0.07875220306861608}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.24376771737441366
Fold 2 IBS: 0.2156464818855228
Fold 3 IBS: 0.21470997467703382
Fold 4 IBS: 0.24506757753025096
Fold 5 IBS: 0.23431638494569054
[I 2024-04-16 23:06:06,878] Trial 98 finished with value: 0.23070162728258237 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 427, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9345235447965159, 'min_weight_fraction_leaf': 0.06398587825076422}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23157995819346658
Fold 2 IBS: 0.19882579261217193
Fold 3 IBS: 0.19153184528522163
Fold 4 IBS: 0.21524003658426155
Fold 5 IBS: 0.21412013270935618
[I 2024-04-16 23:06:12,142] Trial 99 finished with value: 0.2102595530768956 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.84377839218482, 'min_weight_fraction_leaf': 0.11311649789821646}. Best is trial 82 with value: 0.20797277264373898.


* Best trial for IBS:
 FrozenTrial(number=82, state=TrialState.COMPLETE, values=[0.20797277264373898], datetime_start=datetime.datetime(2024, 4, 16, 23, 4, 42, 43014), datetime_complete=datetime.datetime(2024, 4, 16, 23, 4, 48, 290447), params={'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 431, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9407754324156289, 'min_weight_fraction_leaf': 0.04206241234084829}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=82, value=None)


* Best Score for IBS:
 0.20797277264373898

In [91]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [92]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.842
train_ibs:  0.208

#### Test

In [93]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [94]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=16, max_features=None, max_leaf_nodes=10,
                   max_samples=0.9186714469202719, min_samples_leaf=2,
                   min_samples_split=3,
                   min_weight_fraction_leaf=0.04956115599708024,
                   n_estimators=474, random_state=123, warm_start=True)

C-index score: 0.567

ExtraSurvivalTrees(max_depth=12, max_features=None, max_leaf_nodes=9,
                   max_samples=0.9407754324156289, min_samples_leaf=9,
                   min_samples_split=2,
                   min_weight_fraction_leaf=0.04206241234084829,
                   n_estimators=431, oob_score=True, random_state=123)

IBS: 0.235

In [95]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [96]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 23:06:15,921] A new study created in memory with name: no-name-2745463c-8dd7-400a-8b0a-4145aad16972

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:06:34,487] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:06:42,481] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:06:52,763] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:07:15,930] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:07:23,713] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:07:25,845] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:07:38,962] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:07:42,263] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:07:42,712] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 23:08:22,247] Trial 9 finished with value: 0.6832201973708838 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6832201973708838.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7461240310077519
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 23:09:26,432] Trial 10 finished with value: 0.6712397937360077 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6832201973708838.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:10:38,951] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6832201973708838.
Fold 1 C-index: 0.6713147410358565
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:11:39,099] Trial 12 finished with value: 0.6841431930275611 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:12:06,350] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:12:44,425] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:13:24,117] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:13:43,599] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:14:27,719] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:15:24,630] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:15:28,178] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:15:54,374] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-16 23:16:46,172] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6244635193133047
[I 2024-04-16 23:17:39,623] Trial 22 finished with value: 0.619312795708334 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:18:31,275] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:19:08,665] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 12 with value: 0.6841431930275611.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:19:43,765] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:19:56,298] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:20:36,629] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:20:38,896] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:21:05,095] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:21:15,445] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5228136882129277
Fold 5 C-index: 0.6437768240343348
[I 2024-04-16 23:21:52,109] Trial 31 finished with value: 0.611786790783696 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:22:32,638] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:22:59,582] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:23:25,144] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.6553784860557769
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 23:23:42,901] Trial 35 finished with value: 0.6685420013231411 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:23:56,885] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 12 with value: 0.6841431930275611.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:24:12,472] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:24:23,425] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:24:34,658] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:24:46,131] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5255319148936171
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.6244635193133047
[I 2024-04-16 23:25:28,467] Trial 41 finished with value: 0.6093445399392414 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:25:57,424] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:26:26,976] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:26:36,652] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:27:01,701] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.463519313304721
[I 2024-04-16 23:27:05,352] Trial 46 finished with value: 0.5692906361531651 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:27:15,490] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.03176403693294541, 'dropout_rate': 0.3498118985606263, 'n_estimators': 311, 'criterion': 'squared_error', 'ccp_alpha': 1.661787786465391, 'min_weight_fraction_leaf': 0.3313569504524189, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0658502841058407e-06, 'validation_fraction': 0.9349106995677626, 'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 7}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:27:15,706] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.7795620265296891, 'learning_rate': 0.02031575704478572, 'dropout_rate': 0.1073207171648626, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.1386953090406989, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9933742654917034, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 12 with value: 0.6841431930275611.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:27:40,735] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.9838861069093487, 'learning_rate': 0.015139882774656225, 'dropout_rate': 0.29582807120816745, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'auto', 'min_impurity_decrease': 1.0677294357907833e-07, 'validation_fraction': 0.28616351261163725, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 12}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:27:51,635] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.0013062644622639785, 'dropout_rate': 0.24125576461922837, 'n_estimators': 291, 'criterion': 'squared_error', 'ccp_alpha': 2.2224019868292646, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'auto', 'min_impurity_decrease': 4.1535796547081375e-07, 'validation_fraction': 0.4330566028790252, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5170212765957447
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 23:28:19,814] Trial 51 finished with value: 0.6138143425937758 and parameters: {'subsample': 0.8717443631112737, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.17858790490895218, 'n_estimators': 439, 'criterion': 'squared_error', 'ccp_alpha': 0.012928318097826519, 'min_weight_fraction_leaf': 0.4658711277635662, 'max_features': 'auto', 'min_impurity_decrease': 3.7719550144765347e-07, 'validation_fraction': 0.8890948102888172, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:28:50,970] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.8600452143616768, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.18426490654900665, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.3268256777978031, 'min_weight_fraction_leaf': 0.4698482977463435, 'max_features': 'auto', 'min_impurity_decrease': 1.8970689457597929e-07, 'validation_fraction': 0.7907152055757274, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:29:19,826] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.9429985164193612, 'learning_rate': 0.01210259689637212, 'dropout_rate': 0.16709004215832246, 'n_estimators': 442, 'criterion': 'squared_error', 'ccp_alpha': 1.355930920770751, 'min_weight_fraction_leaf': 0.44688401918267284, 'max_features': 'auto', 'min_impurity_decrease': 1.3370772545900196e-06, 'validation_fraction': 0.8482207213921362, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:29:28,368] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8147206508663337, 'learning_rate': 0.043146549395218045, 'dropout_rate': 0.8266353856620614, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 0.4402476369193899, 'min_weight_fraction_leaf': 0.403465815144378, 'max_features': 'auto', 'min_impurity_decrease': 0.009274431072766336, 'validation_fraction': 0.9013663610610466, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:30:01,722] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9029355236435976, 'learning_rate': 0.0069862044003569015, 'dropout_rate': 0.2714637824563154, 'n_estimators': 493, 'criterion': 'squared_error', 'ccp_alpha': 0.7342456209458248, 'min_weight_fraction_leaf': 0.20205377440058656, 'max_features': 'auto', 'min_impurity_decrease': 5.480356851781927e-07, 'validation_fraction': 0.9611026002356494, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:30:20,023] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.9900310764127254, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.13035104784910678, 'n_estimators': 373, 'criterion': 'squared_error', 'ccp_alpha': 1.030013456919117, 'min_weight_fraction_leaf': 0.39532826999294124, 'max_features': 1, 'min_impurity_decrease': 1.6304555456718902e-07, 'validation_fraction': 0.6752987077694675, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 23:30:38,765] Trial 57 finished with value: 0.6916626606095264 and parameters: {'subsample': 0.7372794740983749, 'learning_rate': 0.07439616301612664, 'dropout_rate': 0.5891903890315894, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.0019551426651700787, 'min_weight_fraction_leaf': 0.3663477858006307, 'max_features': 'auto', 'min_impurity_decrease': 3.365152936571637e-07, 'validation_fraction': 0.9993820900191361, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:30:51,835] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.740417255833941, 'learning_rate': 0.08011510722272602, 'dropout_rate': 0.6195846181212514, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 5.929975119025805, 'min_weight_fraction_leaf': 0.311339954548064, 'max_features': 0.1, 'min_impurity_decrease': 2.1554900690561924e-06, 'validation_fraction': 0.9698819721425359, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:31:09,200] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.6313932742304071, 'learning_rate': 0.08675370704859038, 'dropout_rate': 0.5460527407257292, 'n_estimators': 487, 'criterion': 'friedman_mse', 'ccp_alpha': 1.8542659560131192, 'min_weight_fraction_leaf': 0.3698106479709166, 'max_features': 'log2', 'min_impurity_decrease': 7.380740444731775e-07, 'validation_fraction': 0.9977032043603392, 'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:31:12,584] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.6791716844984723, 'learning_rate': 0.08763134010262277, 'dropout_rate': 0.6506047265765441, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 1.3887836841387762, 'min_weight_fraction_leaf': 0.3542140149719947, 'max_features': 'auto', 'min_impurity_decrease': 5.3774251612153256e-05, 'validation_fraction': 0.9294449799181549, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 57 with value: 0.6916626606095264.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:31:35,090] Trial 61 finished with value: 0.5127659574468085 and parameters: {'subsample': 0.5777054240152439, 'learning_rate': 0.0043890144447948955, 'dropout_rate': 0.2238557425834033, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.22729228144381666, 'min_weight_fraction_leaf': 0.4847667891453218, 'max_features': 'auto', 'min_impurity_decrease': 3.121762528354459e-07, 'validation_fraction': 0.8794060911772942, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.5851063829787234
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6845493562231759
[I 2024-04-16 23:32:04,863] Trial 62 finished with value: 0.6671051444586171 and parameters: {'subsample': 0.8280927356694872, 'learning_rate': 0.012941968520404364, 'dropout_rate': 0.16851713525090162, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 0.022717462020606087, 'min_weight_fraction_leaf': 0.41782991757217913, 'max_features': 'auto', 'min_impurity_decrease': 1.6297128321880156e-07, 'validation_fraction': 0.8216047754912434, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:32:24,875] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.8179794453140475, 'learning_rate': 0.07155184022383326, 'dropout_rate': 0.5059523129078595, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.733686110808502, 'min_weight_fraction_leaf': 0.4266346533719304, 'max_features': 'auto', 'min_impurity_decrease': 1.456573145641989e-07, 'validation_fraction': 0.8226670106263154, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:32:49,363] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.7257892105627847, 'learning_rate': 0.02248195835921648, 'dropout_rate': 0.449913369550909, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4337068311554637, 'min_weight_fraction_leaf': 0.40949100256777493, 'max_features': 'auto', 'min_impurity_decrease': 2.3829259538917073e-07, 'validation_fraction': 0.9264223190540628, 'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:33:03,488] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.789360221844535, 'learning_rate': 0.011722172098720455, 'dropout_rate': 0.5832565770529121, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.9257201840062063, 'min_weight_fraction_leaf': 0.3826221056999394, 'max_features': 'auto', 'min_impurity_decrease': 0.00018567504305581884, 'validation_fraction': 0.7684528850780882, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:33:27,154] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.9423465114553011, 'learning_rate': 0.026890895479547216, 'dropout_rate': 0.27005657366012886, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.3406131595034317, 'min_weight_fraction_leaf': 0.273466592831212, 'max_features': 'sqrt', 'min_impurity_decrease': 5.724092120969544e-07, 'validation_fraction': 0.8663542646961032, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:33:52,901] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8509816424016059, 'learning_rate': 0.018962435344391418, 'dropout_rate': 0.12106779245577974, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 1.1793178188167732, 'min_weight_fraction_leaf': 0.32971711200084314, 'max_features': None, 'min_impurity_decrease': 1.1734866199377895e-06, 'validation_fraction': 0.9601204189934851, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:34:23,436] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.8877022924129648, 'learning_rate': 0.035301196481135985, 'dropout_rate': 0.21544296697082643, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.29598676708348526, 'min_weight_fraction_leaf': 0.437656675029897, 'max_features': 'auto', 'min_impurity_decrease': 1.3568513606672929e-07, 'validation_fraction': 0.7065228184822674, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:34:42,950] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.5085409566716843, 'learning_rate': 0.07146375849643816, 'dropout_rate': 0.15565815102593683, 'n_estimators': 381, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7384677513512519, 'min_weight_fraction_leaf': 0.16528005308216742, 'max_features': 'auto', 'min_impurity_decrease': 3.4966343506407575e-07, 'validation_fraction': 0.5407783460399488, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.4765957446808511
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:34:59,735] Trial 70 finished with value: 0.6699861139528519 and parameters: {'subsample': 0.8427091117621403, 'learning_rate': 0.014080040753655973, 'dropout_rate': 0.7041903400301625, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.010117153579154908, 'min_weight_fraction_leaf': 0.23888457853481262, 'max_features': 'auto', 'min_impurity_decrease': 1.0665064545447388e-07, 'validation_fraction': 0.8311901171171172, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 9}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.49361702127659574
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 23:35:16,859] Trial 71 finished with value: 0.6705113277133752 and parameters: {'subsample': 0.837820165625454, 'learning_rate': 0.009162835586660466, 'dropout_rate': 0.7157677225693142, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.027818996011453684, 'min_weight_fraction_leaf': 0.2238024810121353, 'max_features': 'auto', 'min_impurity_decrease': 1.6903767334797878e-07, 'validation_fraction': 0.9136175276841315, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 9}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.49361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 23:35:34,210] Trial 72 finished with value: 0.6704965901886897 and parameters: {'subsample': 0.8320550512705249, 'learning_rate': 0.015250213313703867, 'dropout_rate': 0.7084704325292757, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.0047914300176533624, 'min_weight_fraction_leaf': 0.22496831177560328, 'max_features': 'auto', 'min_impurity_decrease': 1.043158296301398e-07, 'validation_fraction': 0.8315500117499774, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 10}. Best is trial 57 with value: 0.6916626606095264.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:35:51,869] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.7522550686139352, 'learning_rate': 0.01549395863927688, 'dropout_rate': 0.7193234731509487, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.6105254483380164, 'min_weight_fraction_leaf': 0.23084281559796668, 'max_features': 'auto', 'min_impurity_decrease': 1.1425726740224786e-07, 'validation_fraction': 0.9089610037492091, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 9}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:36:05,227] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.6901097639595143, 'learning_rate': 0.009706466282346518, 'dropout_rate': 0.8289978122630015, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.32830586032225173, 'min_weight_fraction_leaf': 0.19648377877761647, 'max_features': 'auto', 'min_impurity_decrease': 1.0237452134280835e-07, 'validation_fraction': 0.6403761250010531, 'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 10}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:36:21,618] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.9243190445711414, 'learning_rate': 0.0038617948288836557, 'dropout_rate': 0.7224884343850821, 'n_estimators': 417, 'criterion': 'squared_error', 'ccp_alpha': 1.5692251904189567, 'min_weight_fraction_leaf': 0.2446666417975855, 'max_features': None, 'min_impurity_decrease': 3.073066227115244e-07, 'validation_fraction': 0.9980785900823812, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:36:38,780] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.7974068669958387, 'learning_rate': 0.062047343259982284, 'dropout_rate': 0.6720237281802866, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.8485875561540186, 'min_weight_fraction_leaf': 0.2177983483250821, 'max_features': 'auto', 'min_impurity_decrease': 2.1896409704067416e-07, 'validation_fraction': 0.8579309717242278, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:36:51,613] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.8422997308078775, 'learning_rate': 0.017766566895921525, 'dropout_rate': 0.6384272449487696, 'n_estimators': 481, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5531698468613242, 'min_weight_fraction_leaf': 0.17978584394296698, 'max_features': 1, 'min_impurity_decrease': 1.6942780866930195e-07, 'validation_fraction': 0.9713474660357939, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 8}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:37:13,259] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.6517834016017484, 'learning_rate': 0.002407235870294221, 'dropout_rate': 0.5816105806888315, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 1.1587287440372196, 'min_weight_fraction_leaf': 0.2981694522309396, 'max_features': 'auto', 'min_impurity_decrease': 5.608281082695417e-07, 'validation_fraction': 0.4642012910381656, 'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 10}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:37:17,582] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.7102653479652419, 'learning_rate': 0.00926581670466016, 'dropout_rate': 0.8340744983902122, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.244213895373325, 'min_weight_fraction_leaf': 0.26516890393090514, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9441925364897708, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:37:28,970] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.5834757737011464, 'learning_rate': 0.026745879030501164, 'dropout_rate': 0.702176827465796, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.22999987323735258, 'max_features': 'log2', 'min_impurity_decrease': 2.3792015344208368e-07, 'validation_fraction': 0.3551379508028982, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 9}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.7131474103585658
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.4808510638297872
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6587982832618026
[I 2024-04-16 23:37:45,207] Trial 81 finished with value: 0.6730234656174222 and parameters: {'subsample': 0.8325293669317142, 'learning_rate': 0.011806037995297227, 'dropout_rate': 0.7551006664918564, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.04034911069069444, 'min_weight_fraction_leaf': 0.25447319867295237, 'max_features': 'auto', 'min_impurity_decrease': 1.5172002134087317e-07, 'validation_fraction': 0.9114851981025106, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:38:01,103] Trial 82 finished with value: 0.698879373414812 and parameters: {'subsample': 0.7574564379023108, 'learning_rate': 0.014548313409933181, 'dropout_rate': 0.7388190394293348, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.017672701019498645, 'min_weight_fraction_leaf': 0.18953464920787744, 'max_features': 'auto', 'min_impurity_decrease': 1.4736811730220929e-07, 'validation_fraction': 0.9118325083710781, 'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:38:17,745] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.7686876073989469, 'learning_rate': 0.013838758072384357, 'dropout_rate': 0.7911803425652506, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.6372477576434026, 'min_weight_fraction_leaf': 0.19053597558098956, 'max_features': 'auto', 'min_impurity_decrease': 1.044261661000394e-07, 'validation_fraction': 0.9081833240552606, 'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:38:35,670] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.8417391470557727, 'learning_rate': 0.02022963558253854, 'dropout_rate': 0.7549313249685682, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 0.21448418173643904, 'min_weight_fraction_leaf': 0.14529026645886883, 'max_features': 'auto', 'min_impurity_decrease': 1.644017634935428e-07, 'validation_fraction': 0.7522154789012329, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 82 with value: 0.698879373414812.

Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5148936170212766
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:38:48,086] Trial 85 finished with value: 0.6764106721092568 and parameters: {'subsample': 0.7354973785260009, 'learning_rate': 0.016077297348185124, 'dropout_rate': 0.7998038530392593, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.011704477637461151, 'min_weight_fraction_leaf': 0.25414654453375674, 'max_features': 'auto', 'min_impurity_decrease': 4.3624226956840624e-07, 'validation_fraction': 0.8473925109174445, 'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 13}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:38:50,079] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.7408782122857952, 'learning_rate': 0.008176338925322723, 'dropout_rate': 0.8784853674438767, 'n_estimators': 110, 'criterion': 'squared_error', 'ccp_alpha': 0.8792495785897113, 'min_weight_fraction_leaf': 0.21067569979765627, 'max_features': 'auto', 'min_impurity_decrease': 8.838933091327168e-07, 'validation_fraction': 0.976898355040724, 'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 14}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:39:03,111] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.7919841956110775, 'learning_rate': 0.016800285566641673, 'dropout_rate': 0.8053771471721777, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 6.848676757092456, 'min_weight_fraction_leaf': 0.25627475842564307, 'max_features': 'auto', 'min_impurity_decrease': 4.4582432432077124e-07, 'validation_fraction': 0.567887901649637, 'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:39:13,836] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.7637017957134666, 'learning_rate': 0.0046996483876466065, 'dropout_rate': 0.8619792930233291, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 0.4746488265956075, 'min_weight_fraction_leaf': 0.28109817636901246, 'max_features': 'auto', 'min_impurity_decrease': 6.846032299820816e-07, 'validation_fraction': 0.8020692816016028, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 14}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:39:36,271] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.9623924871310936, 'learning_rate': 0.0015527825801297172, 'dropout_rate': 0.7519223066786315, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 1.2232438573199316, 'min_weight_fraction_leaf': 0.15271636525917553, 'max_features': 'auto', 'min_impurity_decrease': 3.1868906706070215e-07, 'validation_fraction': 0.9409810619692617, 'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:39:42,046] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.8745132816034922, 'learning_rate': 0.024313584301659426, 'dropout_rate': 0.8788019303444206, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.2487952428061195, 'min_weight_fraction_leaf': 0.008931419075771496, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5174531590387773e-06, 'validation_fraction': 0.8951588805626794, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 14, 'max_depth': 15}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.7131474103585658
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.4851063829787234
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6630901287553648
[I 2024-04-16 23:39:58,585] Trial 91 finished with value: 0.6731825109490227 and parameters: {'subsample': 0.8354990297039531, 'learning_rate': 0.0138293831902292, 'dropout_rate': 0.7281039467319077, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.03758540364708225, 'min_weight_fraction_leaf': 0.2530637808301116, 'max_features': 'auto', 'min_impurity_decrease': 1.5118979817918927e-07, 'validation_fraction': 0.8408512373546821, 'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 11}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:40:13,910] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.8085365523165823, 'learning_rate': 0.010756482814232722, 'dropout_rate': 0.7444483338307321, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.49447471804458437, 'min_weight_fraction_leaf': 0.25064996426719116, 'max_features': 'auto', 'min_impurity_decrease': 2.0676851144372516e-07, 'validation_fraction': 0.8390132957951739, 'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:40:29,658] Trial 93 finished with value: 0.6881273036948009 and parameters: {'subsample': 0.7453329553993305, 'learning_rate': 0.021174166394019457, 'dropout_rate': 0.7793451155626762, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04746460613674034, 'min_weight_fraction_leaf': 0.2093766049536608, 'max_features': 'auto', 'min_impurity_decrease': 4.3263336279630515e-07, 'validation_fraction': 0.7761975833676429, 'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 11}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:40:45,164] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.7279707912652753, 'learning_rate': 0.021608355611700266, 'dropout_rate': 0.7346078225406316, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.7086041731588438, 'min_weight_fraction_leaf': 0.20875637228664023, 'max_features': 'auto', 'min_impurity_decrease': 4.696900773859783e-07, 'validation_fraction': 0.7825380103331964, 'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 11}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:40:53,140] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.41059605701997526, 'learning_rate': 0.008265328833970157, 'dropout_rate': 0.7833536187763309, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 0.9761780021039411, 'min_weight_fraction_leaf': 0.26909043908757685, 'max_features': 'auto', 'min_impurity_decrease': 2.7953622898255886e-07, 'validation_fraction': 0.8675625663624191, 'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 13}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:41:14,562] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.7807484083766505, 'learning_rate': 0.019136234077479226, 'dropout_rate': 0.6797290416912756, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.2137190515453802, 'min_weight_fraction_leaf': 0.1836345173241593, 'max_features': 'auto', 'min_impurity_decrease': 1.5053955435348267e-07, 'validation_fraction': 0.9141346557445693, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 15}. Best is trial 82 with value: 0.698879373414812.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:41:29,484] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.6692392383366766, 'learning_rate': 0.005703846641879013, 'dropout_rate': 0.778639362865728, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.4660418580309801, 'min_weight_fraction_leaf': 0.19771711093861588, 'max_features': 'auto', 'min_impurity_decrease': 0.0032862083702029487, 'validation_fraction': 0.9476450583671194, 'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:41:40,254] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.7074353323873224, 'learning_rate': 0.012490550235605942, 'dropout_rate': 0.8460634884916687, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 4.816291450322713, 'min_weight_fraction_leaf': 0.2365858465049468, 'max_features': 'auto', 'min_impurity_decrease': 9.113797265483529e-07, 'validation_fraction': 0.9834615394391507, 'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 12}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.7604562737642585

[I 2024-04-16 23:41:56,880] A new study created in memory with name: no-name-7f8d3545-f2d0-41d0-85e9-77b52214a117

Fold 5 C-index: 0.6802575107296137
[I 2024-04-16 23:41:56,872] Trial 99 finished with value: 0.6997238381485732 and parameters: {'subsample': 0.8597838031871279, 'learning_rate': 0.010888929954369636, 'dropout_rate': 0.8022681311855436, 'n_estimators': 443, 'criterion': 'squared_error', 'ccp_alpha': 0.004507507039685693, 'min_weight_fraction_leaf': 0.1685851039915477, 'max_features': 'auto', 'min_impurity_decrease': 4.0700060224631717e-07, 'validation_fraction': 0.8827408742810589, 'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 99 with value: 0.6997238381485732.


* Best trial for C-index:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.6997238381485732], datetime_start=datetime.datetime(2024, 4, 16, 23, 41, 40, 257324), datetime_complete=datetime.datetime(2024, 4, 16, 23, 41, 56, 872246), params={'subsample': 0.8597838031871279, 'learning_rate': 0.010888929954369636, 'dropout_rate': 0.8022681311855436, 'n_estimators': 443, 'criterion': 'squared_error', 'ccp_alpha': 0.004507507039685693, 'min_weight_fraction_leaf': 0.1685851039915477, 'max_features': 'auto', 'min_impurity_decrease': 4.0700060224631717e-07, 'validation_fraction': 0.8827408742810589, 'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 12}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=99, value=None)


* Best Score for C-index:
 0.6997238381485732

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:42:06,722] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:42:11,415] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:42:17,589] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:42:31,047] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:42:35,619] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:42:36,863] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:42:43,170] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:42:44,958] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:42:45,220] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24611646824848502
Fold 2 IBS: 0.23045314613284576
Fold 3 IBS: 0.22864908069318055
Fold 4 IBS: 0.24088343083773206
Fold 5 IBS: 0.2286067880417571
[I 2024-04-16 23:43:06,356] Trial 9 finished with value: 0.23494178279080008 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.23166000859087926
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164904353219824
Fold 5 IBS: 0.2291762528827903
[I 2024-04-16 23:43:37,618] Trial 10 finished with value: 0.23563423441371983 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:44:13,043] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.2471389609167843
Fold 2 IBS: 0.23185194695073053
Fold 3 IBS: 0.2289550691998775
Fold 4 IBS: 0.2418709994354467
Fold 5 IBS: 0.22931414809995274
[I 2024-04-16 23:44:45,718] Trial 12 finished with value: 0.23582622492055835 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:44:57,805] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:45:27,809] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:45:46,217] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:45:56,719] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:46:23,608] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:46:36,672] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:46:39,441] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:47:07,201] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.2470758782497334
Fold 2 IBS: 0.2319847418263816
Fold 3 IBS: 0.2289216878375815
Fold 4 IBS: 0.24189505261981767
Fold 5 IBS: 0.22923216203360366
[I 2024-04-16 23:47:40,062] Trial 21 finished with value: 0.23582190451342355 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.2464930115110139
Fold 2 IBS: 0.23084795543166578

Fold 3 IBS: 0.22877023826826642
Fold 4 IBS: 0.24122503350572105
Fold 5 IBS: 0.22878079391093029
[I 2024-04-16 23:48:15,260] Trial 22 finished with value: 0.2352234065255195 and parameters: {'subsample': 0.7705970564002892, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2556338272384969, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.1819352198113874, 'max_features': 'auto', 'min_impurity_decrease': 2.8455032461612084e-06, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-16 23:48:46,916] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7836311463570909, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.19187858926690976, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.1238520089163157, 'max_features': 'auto', 'min_impurity_decrease': 3.0522262999316147e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:49:07,191] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7587811397980595, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.38790491264114013, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.9382331620898647, 'min_weight_fraction_leaf': 0.3092505738893419, 'max_features': 'auto', 'min_impurity_decrease': 1.835773315341181e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:49:26,561] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.7972724799167636, 'min_weight_fraction_leaf': 0.06342723550175844, 'max_features': 'auto', 'min_impurity_decrease': 4.2810579358018096e-07, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:49:41,916] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926412059695023, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.5288432021501348, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.3654495948602763, 'max_features': 1, 'min_impurity_decrease': 5.7767867868391535e-06, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:49:43,912] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.7199879736775374, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:49:48,738] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5982471609501279, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.7580627673470397, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.17979234805851085, 'max_features': 0.1, 'min_impurity_decrease': 2.8766461228225205e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:50:07,914] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.1613885275758775, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:50:40,216] Trial 30 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.3265580511017444, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 2.031090116944395e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24669611373458267
Fold 2 IBS: 0.23161054906241668
Fold 3 IBS: 0.22885749682655868
Fold 4 IBS: 0.2415375526987621
Fold 5 IBS: 0.22900046780800146
[I 2024-04-16 23:51:12,481] Trial 31 finished with value: 0.2355404360260643 and parameters: {'subsample': 0.9344383405023591, 'learning_rate': 0.006524518316879135, 'dropout_rate': 0.26649573367142365, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 4.351117867352206e-06, 'validation_fraction': 0.9601957444024036, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24559061103708343
Fold 2 IBS: 0.23024033663487284
Fold 3 IBS: 0.2293974925753989
Fold 4 IBS: 0.24024323071520023
Fold 5 IBS: 0.2284489804567101
[I 2024-04-16 23:51:45,121] Trial 32 finished with value: 0.2347841302838531 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2287495679714313, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.23002205018404465, 'max_features': 'auto', 'min_impurity_decrease': 5.685341128394722e-05, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:52:04,253] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9177537861930692, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.3914970241753336, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.0507266620441584, 'min_weight_fraction_leaf': 0.23926229900744406, 'max_features': 'auto', 'min_impurity_decrease': 0.00011709565626556463, 'validation_fraction': 0.8393388494663446, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:52:27,216] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6819681800793775, 'learning_rate': 0.014932417117098078, 'dropout_rate': 0.2500240325464975, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 1.9765936590363733, 'min_weight_fraction_leaf': 0.13771184392949654, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9172090645295194, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:52:35,283] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7476638601677043, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.30101053387291227, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 0.44652508735115226, 'min_weight_fraction_leaf': 0.10093795447298021, 'max_features': None, 'min_impurity_decrease': 4.406156675878729e-05, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:52:59,500] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.42230497047334825, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.26995461743933613, 'max_features': 'auto', 'min_impurity_decrease': 1.3215601521076594e-05, 'validation_fraction': 0.7818001985604904, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:53:03,108] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.21915428448310503, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 1.4358936193715688, 'min_weight_fraction_leaf': 0.23268483668726153, 'max_features': None, 'min_impurity_decrease': 0.00032393590103416044, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:53:13,924] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8672504967337782, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.7673236646699829, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6556730327214771, 'min_weight_fraction_leaf': 0.18834697224411925, 'max_features': 'auto', 'min_impurity_decrease': 0.00023363839115037033, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:53:28,933] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8156280794845335, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.3466374755180119, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.2802748909834897, 'max_features': 1, 'min_impurity_decrease': 0.001895508491501562, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:53:50,399] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.518652974052727, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 3.416581893752396, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 1.186294852384206e-05, 'validation_fraction': 0.6514426016998515, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24564975054404245
Fold 2 IBS: 0.22980985720122352
Fold 3 IBS: 0.22862944699148766
Fold 4 IBS: 0.24019850838895782
Fold 5 IBS: 0.22847935077439893
[I 2024-04-16 23:54:26,597] Trial 41 finished with value: 0.23455338278002208 and parameters: {'subsample': 0.9932038385002909, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.1573621124822965, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.13954813567569782, 'max_features': 'auto', 'min_impurity_decrease': 7.535700463117119e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24577893568533524
Fold 2 IBS: 0.2300168763545233
Fold 3 IBS: 0.2283274561934457
Fold 4 IBS: 0.24018944863835465
Fold 5 IBS: 0.2284694599346158
[I 2024-04-16 23:55:03,784] Trial 42 finished with value: 0.23455643536125495 and parameters: {'subsample': 0.964697700266936, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.18073816214366334, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327291371346121, 'min_weight_fraction_leaf': 0.1501825213718253, 'max_features': 'auto', 'min_impurity_decrease': 7.389724453793971e-07, 'validation_fraction': 0.9438929489105444, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:55:47,814] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9828290729869368, 'learning_rate': 0.005440117267094092, 'dropout_rate': 0.16429624388711278, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.1638059032250418, 'min_weight_fraction_leaf': 0.14400744495905113, 'max_features': 'auto', 'min_impurity_decrease': 7.160819992467899e-07, 'validation_fraction': 0.8682784817018523, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:56:21,668] Trial 44 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9992871622667048, 'learning_rate': 0.012272887594565313, 'dropout_rate': 0.11965546339368549, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.5504303626596221, 'min_weight_fraction_leaf': 0.10316812300893248, 'max_features': 'auto', 'min_impurity_decrease': 2.2780695231073978e-06, 'validation_fraction': 0.8946516967835402, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:56:30,592] Trial 45 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8888336111822305, 'learning_rate': 0.022080051602678542, 'dropout_rate': 0.2121382569959027, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.41647456900543567, 'min_weight_fraction_leaf': 0.045210542223651826, 'max_features': 0.1, 'min_impurity_decrease': 2.0256548340178764e-07, 'validation_fraction': 0.943601584155436, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24711436282531865
Fold 2 IBS: 0.23189796599325815
Fold 3 IBS: 0.2289389886288917
Fold 4 IBS: 0.2418829980148295
Fold 5 IBS: 0.22932341012264723
[I 2024-04-16 23:56:55,388] Trial 46 finished with value: 0.23583154511698906 and parameters: {'subsample': 0.7744813929591432, 'learning_rate': 0.008102046534903828, 'dropout_rate': 0.1797794592098615, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.08495175216102194, 'min_weight_fraction_leaf': 0.15177154165796414, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1313197537973378e-06, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:57:10,333] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7017637733903979, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.7022058348677743, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 1.7224181899716802, 'min_weight_fraction_leaf': 0.18604464195331838, 'max_features': 'auto', 'min_impurity_decrease': 6.985840903306681e-07, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:57:10,539] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5605970169273662, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.10447148486096186, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.2080122998414906, 'max_features': None, 'min_impurity_decrease': 2.1520342389791543e-07, 'validation_fraction': 0.9548943163211767, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:57:18,173] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8470287699338075, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.1456275761236044, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2223686585045759, 'min_weight_fraction_leaf': 0.12204787996041808, 'max_features': 'log2', 'min_impurity_decrease': 0.0008845692122216605, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:57:37,585] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9497672382316631, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.23703345601437922, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 0.4773369462462276, 'min_weight_fraction_leaf': 0.25645611863450213, 'max_features': 'auto', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.7876099760634406, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.2462802649053173
Fold 2 IBS: 0.23090518019736747
Fold 3 IBS: 0.22910230952131883
Fold 4 IBS: 0.24089201571280294
Fold 5 IBS: 0.22880129355386447
[I 2024-04-16 23:58:10,528] Trial 51 finished with value: 0.23519621277813424 and parameters: {'subsample': 0.9480276186148049, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.2856033525481214, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.22461792037583256, 'max_features': 'auto', 'min_impurity_decrease': 3.3864756991240473e-06, 'validation_fraction': 0.959807845534086, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24650272034345022
Fold 2 IBS: 0.23102415353022362
Fold 3 IBS: 0.22863881664006155
Fold 4 IBS: 0.2411028633234996
Fold 5 IBS: 0.22892412673294307
[I 2024-04-16 23:58:42,651] Trial 52 finished with value: 0.2352385361140356 and parameters: {'subsample': 0.9690886547521121, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.29098664360409054, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.03660199451993653, 'min_weight_fraction_leaf': 0.17297727640490082, 'max_features': 'auto', 'min_impurity_decrease': 3.049559112525484e-06, 'validation_fraction': 0.9718410393680599, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:59:14,076] Trial 53 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8920228452074053, 'learning_rate': 0.010335997729310374, 'dropout_rate': 0.32661371595674515, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.2945173805852883, 'max_features': 'auto', 'min_impurity_decrease': 7.833227343851573e-07, 'validation_fraction': 0.9011349602609936, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:59:46,225] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9472264097624746, 'learning_rate': 0.01762169753824272, 'dropout_rate': 0.1508637651435515, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.4362560228385305, 'min_weight_fraction_leaf': 0.22035807288061335, 'max_features': 'auto', 'min_impurity_decrease': 0.015305241535958306, 'validation_fraction': 0.9995106443638909, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 00:00:10,614] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.809323041898869, 'learning_rate': 0.0040826970179266685, 'dropout_rate': 0.36065535241543395, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.5126136571072866, 'min_weight_fraction_leaf': 0.2002957617254777, 'max_features': 'auto', 'min_impurity_decrease': 2.0868015436948727e-05, 'validation_fraction': 0.8814649292460881, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 00:00:29,934] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.2818850250060197, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.23297170241739207, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 2.3897427065099115, 'min_weight_fraction_leaf': 0.2552507873943692, 'max_features': 'auto', 'min_impurity_decrease': 1.4962235814136573e-06, 'validation_fraction': 0.5010775717552909, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:00:51,168] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8654402967188083, 'learning_rate': 0.0010994123129714779, 'dropout_rate': 0.5925056825473531, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 3.0806403612284923, 'min_weight_fraction_leaf': 0.3388560781293413, 'max_features': 'auto', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.9457965904141827, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:01:14,586] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.02418028639032989, 'dropout_rate': 0.20247794507096373, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 6.734647887782943, 'min_weight_fraction_leaf': 0.13686113855005327, 'max_features': 1, 'min_impurity_decrease': 5.6056583988076206e-05, 'validation_fraction': 0.7164235243058807, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:01:34,979] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5273941310970662, 'learning_rate': 0.013269545795309803, 'dropout_rate': 0.27120464223149515, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.08408118413163579, 'max_features': 0.1, 'min_impurity_decrease': 4.3252557742868694e-07, 'validation_fraction': 0.8195507001084924, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:01:50,139] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4687193173806922, 'learning_rate': 0.0299620116966956, 'dropout_rate': 0.40652994108993334, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 1.7110338383890442, 'min_weight_fraction_leaf': 0.1707925110352551, 'max_features': 'auto', 'min_impurity_decrease': 2.777282902745793e-06, 'validation_fraction': 0.8559576979556259, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.246792274967983
Fold 2 IBS: 0.23161964216377484
Fold 3 IBS: 0.22888176928337703
Fold 4 IBS: 0.24155890986096298
Fold 5 IBS: 0.22907544730443408
[I 2024-04-17 00:02:24,609] Trial 61 finished with value: 0.2355856087161064 and parameters: {'subsample': 0.9918985385533109, 'learning_rate': 0.005743016439014149, 'dropout_rate': 0.28747233681343587, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.08369853910029246, 'min_weight_fraction_leaf': 0.16038675829082302, 'max_features': 'auto', 'min_impurity_decrease': 2.9513412376244623e-06, 'validation_fraction': 0.9751691260171886, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24556197891151196
Fold 2 IBS: 0.22972947118075088
Fold 3 IBS: 0.22847603444167852
Fold 4 IBS: 0.23983661807749995
Fold 5 IBS: 0.22821417993674387
[I 2024-04-17 00:02:57,111] Trial 62 finished with value: 0.23436365650963703 and parameters: {'subsample': 0.9574333176186867, 'learning_rate': 0.008574233182053305, 'dropout_rate': 0.18564670695369828, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.1963819185824203, 'max_features': 'auto', 'min_impurity_decrease': 7.301362864132341e-06, 'validation_fraction': 0.9275594296798731, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:03:07,085] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9611556459137681, 'learning_rate': 0.009885633504393494, 'dropout_rate': 0.8555425487679464, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.40714661625851756, 'min_weight_fraction_leaf': 0.19157478425569488, 'max_features': 'auto', 'min_impurity_decrease': 1.0767504332570267e-06, 'validation_fraction': 0.9184663621892178, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:03:31,291] Trial 64 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9996724029846231, 'learning_rate': 0.02055321577299183, 'dropout_rate': 0.19552211208698841, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.21641604442433082, 'max_features': 'log2', 'min_impurity_decrease': 7.250192360253865e-06, 'validation_fraction': 0.9272295835693174, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.2289818680697771
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:04:03,761] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.919652344200739, 'learning_rate': 0.014473083324943868, 'dropout_rate': 0.16799591889422819, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.351957844105687, 'min_weight_fraction_leaf': 0.0025378122397684832, 'max_features': 'auto', 'min_impurity_decrease': 1.7045397927378775e-05, 'validation_fraction': 0.7413345803433677, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658996

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:04:33,454] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8489175059797514, 'learning_rate': 0.008448226967076113, 'dropout_rate': 0.12725750793823018, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 0.893877768639663, 'min_weight_fraction_leaf': 0.2702972473075093, 'max_features': 'auto', 'min_impurity_decrease': 7.586810829424823e-05, 'validation_fraction': 0.8971088342813041, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:04:54,471] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9594402941587806, 'learning_rate': 0.0039206688180527, 'dropout_rate': 0.25338876644885766, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 1.1787054950134963, 'min_weight_fraction_leaf': 0.29081789854917856, 'max_features': 'sqrt', 'min_impurity_decrease': 6.005146223539456e-06, 'validation_fraction': 0.9662549030476638, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:05:24,412] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.885928079608526, 'learning_rate': 0.01958784726286755, 'dropout_rate': 0.3188313005563145, 'n_estimators': 463, 'criterion': 'friedman_mse', 'ccp_alpha': 8.846039028998158, 'min_weight_fraction_leaf': 0.24383256255051056, 'max_features': 'auto', 'min_impurity_decrease': 3.057918866616863e-07, 'validation_fraction': 0.99982951588149, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724158711521824
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:05:53,980] Trial 69 finished with value: 0.23592674084605642 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.011561561592981577, 'dropout_rate': 0.2251092355441408, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.30419922755720963, 'min_weight_fraction_leaf': 0.1929901790072115, 'max_features': 'auto', 'min_impurity_decrease': 1.6729804035130242e-06, 'validation_fraction': 0.8450602738806452, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 12}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24516581707410637
Fold 2 IBS: 0.229362987548221
Fold 3 IBS: 0.2285150856495683
Fold 4 IBS: 0.2397404288488306
Fold 5 IBS: 0.22776390319047718
[I 2024-04-17 00:06:18,213] Trial 70 finished with value: 0.23410964446224067 and parameters: {'subsample': 0.7327319228005876, 'learning_rate': 0.016866948400001296, 'dropout_rate': 0.17898373444054652, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.01005746855001105, 'min_weight_fraction_leaf': 0.3640638074298326, 'max_features': None, 'min_impurity_decrease': 9.787021311876353e-06, 'validation_fraction': 0.7926074734474466, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.2454369019344366
Fold 2 IBS: 0.23016772493855195
Fold 3 IBS: 0.22866734075144848
Fold 4 IBS: 0.2406555824750769
Fold 5 IBS: 0.22795295445317568
[I 2024-04-17 00:06:39,225] Trial 71 finished with value: 0.2345761009105379 and parameters: {'subsample': 0.6580825781997457, 'learning_rate': 0.016629440896307336, 'dropout_rate': 0.17328978363215145, 'n_estimators': 380, 'criterion': 'squared_error', 'ccp_alpha': 0.06024274183448569, 'min_weight_fraction_leaf': 0.4078164122376511, 'max_features': None, 'min_impurity_decrease': 3.981143358338061e-06, 'validation_fraction': 0.9287047300321795, 'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.2455804604771737
Fold 2 IBS: 0.23015122616770395
Fold 3 IBS: 0.22864882824644148
Fold 4 IBS: 0.2406032444136894
Fold 5 IBS: 0.22814137040371196
[I 2024-04-17 00:06:57,586] Trial 72 finished with value: 0.2346250259417441 and parameters: {'subsample': 0.6433252951647072, 'learning_rate': 0.015406216424115876, 'dropout_rate': 0.174165060267479, 'n_estimators': 372, 'criterion': 'squared_error', 'ccp_alpha': 0.004831359506118816, 'min_weight_fraction_leaf': 0.4068999670923105, 'max_features': None, 'min_impurity_decrease': 9.143853678722166e-06, 'validation_fraction': 0.8050869160635631, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 00:07:20,055] Trial 73 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6415805639130162, 'learning_rate': 0.016957190070749008, 'dropout_rate': 0.1022557442615895, 'n_estimators': 380, 'criterion': 'squared_error', 'ccp_alpha': 0.7340527434897883, 'min_weight_fraction_leaf': 0.41441154927232665, 'max_features': None, 'min_impurity_decrease': 2.8366918098535655e-05, 'validation_fraction': 0.8120762455660575, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:07:43,338] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5890037439982243, 'learning_rate': 0.02388572819447024, 'dropout_rate': 0.14309816759091956, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 0.33550183960235097, 'min_weight_fraction_leaf': 0.4824501432585142, 'max_features': None, 'min_impurity_decrease': 1.1962100920927531e-05, 'validation_fraction': 0.6568048355299513, 'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 17}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 00:08:01,524] Trial 75 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6875143177223235, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.18219557324018512, 'n_estimators': 365, 'criterion': 'squared_error', 'ccp_alpha': 0.6626240923578504, 'min_weight_fraction_leaf': 0.3667876525646178, 'max_features': None, 'min_impurity_decrease': 8.996538110684365e-06, 'validation_fraction': 0.7854387247082943, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:08:23,385] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6310903661182281, 'learning_rate': 0.0558935141377456, 'dropout_rate': 0.16070017323462005, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.43428922098282363, 'max_features': None, 'min_impurity_decrease': 4.880048865700701e-06, 'validation_fraction': 0.7567620429516432, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 00:08:36,895] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7234820637720293, 'learning_rate': 0.04128077713454106, 'dropout_rate': 0.19884799526452568, 'n_estimators': 302, 'criterion': 'squared_error', 'ccp_alpha': 1.2832467794713243, 'min_weight_fraction_leaf': 0.4027406894595495, 'max_features': None, 'min_impurity_decrease': 5.35591590419612e-07, 'validation_fraction': 0.8758106078120852, 'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:08:52,972] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6708593402641205, 'learning_rate': 0.02742354559286264, 'dropout_rate': 0.12642193192647372, 'n_estimators': 329, 'criterion': 'squared_error', 'ccp_alpha': 0.2456295975030462, 'min_weight_fraction_leaf': 0.3629864105918121, 'max_features': None, 'min_impurity_decrease': 0.00015140034318578482, 'validation_fraction': 0.6173345703129903, 'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.241851651618776
Fold 2 IBS: 0.225082141185961
Fold 3 IBS: 0.22886330137755048
Fold 4 IBS: 0.23945272971544493
Fold 5 IBS: 0.225546678965891
[I 2024-04-17 00:09:16,384] Trial 79 finished with value: 0.2321593005727247 and parameters: {'subsample': 0.6068487747881667, 'learning_rate': 0.08690058608305122, 'dropout_rate': 0.2202274723306249, 'n_estimators': 422, 'criterion': 'squared_error', 'ccp_alpha': 0.0067848986270052205, 'min_weight_fraction_leaf': 0.442958513823715, 'max_features': None, 'min_impurity_decrease': 3.159003046563375e-05, 'validation_fraction': 0.6916250922837899, 'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 79 with value: 0.2321593005727247.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:09:40,116] Trial 80 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7431452433208791, 'learning_rate': 0.07289104058957506, 'dropout_rate': 0.22085807342340602, 'n_estimators': 416, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0208718228969498, 'min_weight_fraction_leaf': 0.4578321580005691, 'max_features': None, 'min_impurity_decrease': 6.219311571999601e-05, 'validation_fraction': 0.8063818584332632, 'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 1}. Best is trial 79 with value: 0.2321593005727247.
Fold 1 IBS: 0.24040275609642484
Fold 2 IBS: 0.22344468173586884
Fold 3 IBS: 0.22846224162930656
Fold 4 IBS: 0.23645999283112776
Fold 5 IBS: 0.22436389610083335
[I 2024-04-17 00:10:05,585] Trial 81 finished with value: 0.23062671367871226 and parameters: {'subsample': 0.6143582554906275, 'learning_rate': 0.09196546766753708, 'dropout_rate': 0.17154122956253648, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 0.025343486133480444, 'min_weight_fraction_leaf': 0.422923580742715, 'max_features': None, 'min_impurity_decrease': 3.0516618185477245e-05, 'validation_fraction': 0.6839523176227551, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:10:23,398] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6156671358096751, 'learning_rate': 0.09024426530842436, 'dropout_rate': 0.17324784818426983, 'n_estimators': 352, 'criterion': 'squared_error', 'ccp_alpha': 0.5340758841421452, 'min_weight_fraction_leaf': 0.44660441203015316, 'max_features': None, 'min_impurity_decrease': 3.596173256287884e-05, 'validation_fraction': 0.6862764853454645, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:10:50,133] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.59035693752921, 'learning_rate': 0.08769222490327029, 'dropout_rate': 0.13695127070120913, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.29851318725213727, 'min_weight_fraction_leaf': 0.4224884983147852, 'max_features': None, 'min_impurity_decrease': 1.7043338510624665e-05, 'validation_fraction': 0.708718433392457, 'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 1}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:11:13,546] Trial 84 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5692772731117001, 'learning_rate': 0.09337007500374273, 'dropout_rate': 0.19406549234317277, 'n_estimators': 428, 'criterion': 'squared_error', 'ccp_alpha': 0.7908292561402825, 'min_weight_fraction_leaf': 0.3834871581332913, 'max_features': None, 'min_impurity_decrease': 2.8122570662289344e-05, 'validation_fraction': 0.9095186934735143, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24230603015357494
Fold 2 IBS: 0.22627075094258225
Fold 3 IBS: 0.22794332453533264
Fold 4 IBS: 0.2379855545919495
Fold 5 IBS: 0.22601443786759767
[I 2024-04-17 00:11:17,059] Trial 85 finished with value: 0.23210401961820742 and parameters: {'subsample': 0.6445419753261435, 'learning_rate': 0.06087928731142127, 'dropout_rate': 0.24518342938103005, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.011216734292662366, 'min_weight_fraction_leaf': 0.4043905469812696, 'max_features': None, 'min_impurity_decrease': 1.493590751470447e-05, 'validation_fraction': 0.5742595190050698, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 00:11:20,621] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5345448615448432, 'learning_rate': 0.06299476346040861, 'dropout_rate': 0.16060697827295928, 'n_estimators': 138, 'criterion': 'squared_error', 'ccp_alpha': 0.62448544277789, 'min_weight_fraction_leaf': 0.4834818041059262, 'max_features': None, 'min_impurity_decrease': 1.4511890623038534e-05, 'validation_fraction': 0.531307128627143, 'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 3}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24187291146832404
Fold 2 IBS: 0.2251821854583426
Fold 3 IBS: 0.2280766922101586
Fold 4 IBS: 0.2375222631191458
Fold 5 IBS: 0.22529950757040032
[I 2024-04-17 00:11:38,616] Trial 87 finished with value: 0.2315907119652743 and parameters: {'subsample': 0.6482886513725954, 'learning_rate': 0.08056151243791008, 'dropout_rate': 0.2600398597942537, 'n_estimators': 374, 'criterion': 'squared_error', 'ccp_alpha': 0.01745937818789605, 'min_weight_fraction_leaf': 0.40356411913419793, 'max_features': None, 'min_impurity_decrease': 9.949241277389102e-06, 'validation_fraction': 0.5582433992805256, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 00:11:40,060] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6879348852579991, 'learning_rate': 0.08209035744510738, 'dropout_rate': 0.24522201083374043, 'n_estimators': 84, 'criterion': 'squared_error', 'ccp_alpha': 0.2983993026610602, 'min_weight_fraction_leaf': 0.3774672254272644, 'max_features': None, 'min_impurity_decrease': 5.4011226362110275e-06, 'validation_fraction': 0.568843188657281, 'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 11}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:11:42,875] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6555693108457097, 'learning_rate': 0.08348043724232247, 'dropout_rate': 0.1018982518393906, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 5.474477626804302, 'min_weight_fraction_leaf': 0.3922659564335438, 'max_features': None, 'min_impurity_decrease': 1.84353439530822e-05, 'validation_fraction': 0.4550485507485021, 'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:11:48,157] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6142534760575815, 'learning_rate': 0.07977183656340979, 'dropout_rate': 0.21675268812215465, 'n_estimators': 191, 'criterion': 'squared_error', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.43931856433894717, 'max_features': None, 'min_impurity_decrease': 4.509029295159726e-05, 'validation_fraction': 0.6255054030515286, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 8}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24033659095145252
Fold 2 IBS: 0.22271607873274998
Fold 3 IBS: 0.22784490354997913
Fold 4 IBS: 0.23529399067272844
Fold 5 IBS: 0.22413051884016097
[I 2024-04-17 00:12:05,711] Trial 91 finished with value: 0.2300644165494142 and parameters: {'subsample': 0.579213280645811, 'learning_rate': 0.09426091382038485, 'dropout_rate': 0.18479264516541616, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 0.03787089343697578, 'min_weight_fraction_leaf': 0.4036747584607865, 'max_features': None, 'min_impurity_decrease': 7.4293259533530295e-06, 'validation_fraction': 0.5325834925366492, 'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24714728680988468
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22893463205005193
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22935673483794422
[I 2024-04-17 00:12:21,919] Trial 92 finished with value: 0.235890661939015 and parameters: {'subsample': 0.5057005214243391, 'learning_rate': 0.09883062819528839, 'dropout_rate': 0.2685922627272655, 'n_estimators': 396, 'criterion': 'squared_error', 'ccp_alpha': 0.19747740396734947, 'min_weight_fraction_leaf': 0.4679716753672616, 'max_features': None, 'min_impurity_decrease': 1.0671241077127033e-05, 'validation_fraction': 0.5950373519486988, 'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:12:41,296] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5538299448336005, 'learning_rate': 0.0868661642219975, 'dropout_rate': 0.20334468934521452, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.5267007889739713, 'min_weight_fraction_leaf': 0.42336750014808644, 'max_features': None, 'min_impurity_decrease': 8.867094040313709e-05, 'validation_fraction': 0.520690018337254, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:12:45,372] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5702665640439277, 'learning_rate': 0.09449632562825357, 'dropout_rate': 0.13870793304287105, 'n_estimators': 169, 'criterion': 'squared_error', 'ccp_alpha': 0.8492587817200913, 'min_weight_fraction_leaf': 0.348550363613902, 'max_features': None, 'min_impurity_decrease': 6.826272330503328e-06, 'validation_fraction': 0.5659130589721448, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 12}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:13:00,098] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7076939032161012, 'learning_rate': 0.09136733918164754, 'dropout_rate': 0.18672112900745633, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 0.561945255260577, 'min_weight_fraction_leaf': 0.40234945062950195, 'max_features': None, 'min_impurity_decrease': 2.5588389290979514e-05, 'validation_fraction': 0.4537896994588092, 'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:13:12,776] Trial 96 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6655863757457166, 'learning_rate': 0.08941626520289533, 'dropout_rate': 0.2411336203156454, 'n_estimators': 339, 'criterion': 'squared_error', 'ccp_alpha': 0.23565160101206817, 'min_weight_fraction_leaf': 0.42995214161407835, 'max_features': None, 'min_impurity_decrease': 3.937366373268103e-06, 'validation_fraction': 0.6733503587022674, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 16}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 00:13:13,126] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5830397464244746, 'learning_rate': 0.09649030637314325, 'dropout_rate': 0.1548001251941624, 'n_estimators': 44, 'criterion': 'squared_error', 'ccp_alpha': 1.0632556006826448, 'min_weight_fraction_leaf': 0.4466142202394081, 'max_features': 1, 'min_impurity_decrease': 9.319522810040033e-06, 'validation_fraction': 0.49048790135092346, 'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:13:29,031] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6220799571230118, 'learning_rate': 0.08529012031921517, 'dropout_rate': 0.2588962329024949, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3323104826759427, 'min_weight_fraction_leaf': 0.4570033067989539, 'max_features': None, 'min_impurity_decrease': 1.5778942534009964e-05, 'validation_fraction': 0.5403544212495923, 'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 3}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 00:13:34,563] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4750010457704055, 'learning_rate': 0.07813501740629669, 'dropout_rate': 0.30318261654818046, 'n_estimators': 242, 'criterion': 'squared_error', 'ccp_alpha': 1.7079733343503498, 'min_weight_fraction_leaf': 0.32269779176244495, 'max_features': 0.1, 'min_impurity_decrease': 1.276230329676773e-06, 'validation_fraction': 0.36954438153697, 'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 91 with value: 0.2300644165494142.


* Best trial for IBS:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.2300644165494142], datetime_start=datetime.datetime(2024, 4, 17, 0, 11, 48, 159403), datetime_complete=datetime.datetime(2024, 4, 17, 0, 12, 5, 711292), params={'subsample': 0.579213280645811, 'learning_rate': 0.09426091382038485, 'dropout_rate': 0.18479264516541616, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 0.03787089343697578, 'min_weight_fraction_leaf': 0.4036747584607865, 'max_features': None, 'min_impurity_decrease': 7.4293259533530295e-06, 'validation_fraction': 0.5325834925366492, 'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=91, value=None)


* Best Score for IBS:
 0.2300644165494142

In [97]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [98]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.7
train_ibs:  0.23

#### Test

In [99]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [100]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.004507507039685693,
                                 criterion='squared_error',
                                 dropout_rate=0.8022681311855436,
                                 learning_rate=0.010888929954369636,
                                 max_depth=12, max_features='auto',
                                 max_leaf_nodes=3,
                                 min_impurity_decrease=4.0700060224631717e-07,
                                 min_samples_leaf=10, min_samples_split=19,
                                 min_weight_fraction_leaf=0.1685851039915477,
                                 n_estimators=443, random_state=123,
                                 subsample=0.8597838031871279,
                                 validation_fraction=0.8827408742810589)

C-index score: 0.516

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03787089343697578,
                                 criterion='squared_error',
                                 dropout_rate=0.18479264516541616,
                                 learning_rate=0.09426091382038485, max_depth=2,
                                 max_leaf_nodes=6,
                                 min_impurity_decrease=7.4293259533530295e-06,
                                 min_samples_leaf=7, min_samples_split=18,
                                 min_weight_fraction_leaf=0.4036747584607865,
                                 n_estimators=390, random_state=123,
                                 subsample=0.579213280645811,
                                 validation_fraction=0.5325834925366492)

IBS: 0.228

In [101]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [102]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [103]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 00:13:42,362] A new study created in memory with name: no-name-254a1012-5239-41ed-83ef-cdb877a6703b

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:13:46,934] Trial 0 finished with value: 0.6423526693826518 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6423526693826518.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:13:59,998] Trial 1 finished with value: 0.6456489898043869 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:14:05,982] Trial 2 finished with value: 0.6398895181851605 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 00:14:12,409] Trial 3 finished with value: 0.6410622977559646 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 00:14:20,617] Trial 4 finished with value: 0.6410296656257357 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:14:30,959] Trial 5 finished with value: 0.6456489898043869 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:14:36,736] Trial 6 finished with value: 0.6456489898043869 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6566523605150214
[I 2024-04-17 00:14:39,983] Trial 7 finished with value: 0.6499035318694023 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:14:46,561] Trial 8 finished with value: 0.6438735819301804 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:14:58,740] Trial 9 finished with value: 0.6423526693826518 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:15:01,617] Trial 10 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6566523605150214
[I 2024-04-17 00:15:14,071] Trial 11 finished with value: 0.6418664157738938 and parameters: {'subsample': 0.1913192016083392, 'dropout_rate': 0.653844054640545, 'n_estimators': 479, 'learning_rate': 0.09497904560009218}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6566523605150214
[I 2024-04-17 00:15:23,652] Trial 12 finished with value: 0.6413056364818717 and parameters: {'subsample': 0.3353880007200528, 'dropout_rate': 0.7264534851333669, 'n_estimators': 349, 'learning_rate': 0.03172136900447732}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:15:26,471] Trial 13 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.9449452743225262, 'dropout_rate': 0.5772994600940633, 'n_estimators': 5, 'learning_rate': 0.09434482881678866}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-17 00:15:36,953] Trial 14 finished with value: 0.6450971850929782 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.8070186117174272, 'n_estimators': 378, 'learning_rate': 0.07350404709311845}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 00:15:41,122] Trial 15 finished with value: 0.6419534424060024 and parameters: {'subsample': 0.3793977474066647, 'dropout_rate': 0.5432207672870106, 'n_estimators': 89, 'learning_rate': 0.03777863375701947}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:15:49,325] Trial 16 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.8245070470446283, 'dropout_rate': 0.9733961081825167, 'n_estimators': 300, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:16:00,621] Trial 17 finished with value: 0.6463367331276717 and parameters: {'subsample': 0.6278318159798674, 'dropout_rate': 0.44488289175405504, 'n_estimators': 423, 'learning_rate': 0.04142804288610771}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:16:12,236] Trial 18 finished with value: 0.6423526693826518 and parameters: {'subsample': 0.6223271642238412, 'dropout_rate': 0.2484669514167454, 'n_estimators': 430, 'learning_rate': 0.03935603162728128}. Best is trial 7 with value: 0.6499035318694023.

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:16:16,448] Trial 19 finished with value: 0.6443942804019518 and parameters: {'subsample': 0.38793667853472646, 'dropout_rate': 0.7077875554849441, 'n_estimators': 85, 'learning_rate': 0.04269105711861253}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:16:25,778] Trial 20 finished with value: 0.6471335458766757 and parameters: {'subsample': 0.6004927729383457, 'dropout_rate': 0.608992508329216, 'n_estimators': 310, 'learning_rate': 0.02073176682253709}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:16:37,005] Trial 21 finished with value: 0.6471335458766757 and parameters: {'subsample': 0.6024584846948889, 'dropout_rate': 0.617775702073121, 'n_estimators': 410, 'learning_rate': 0.02243634436579768}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:16:45,914] Trial 22 finished with value: 0.6471699023519155 and parameters: {'subsample': 0.5584709618699464, 'dropout_rate': 0.6014397310146338, 'n_estimators': 307, 'learning_rate': 0.017446813011032656}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 00:16:54,478] Trial 23 finished with value: 0.6436924938049693 and parameters: {'subsample': 0.43791928961446275, 'dropout_rate': 0.8014372139995105, 'n_estimators': 311, 'learning_rate': 0.008919877679902218}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6566523605150214
[I 2024-04-17 00:17:01,846] Trial 24 finished with value: 0.6460354189759705 and parameters: {'subsample': 0.30544113046891047, 'dropout_rate': 0.6537883290687992, 'n_estimators': 252, 'learning_rate': 0.019745129742150442}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:17:10,268] Trial 25 finished with value: 0.6471335458766757 and parameters: {'subsample': 0.5821550035835038, 'dropout_rate': 0.7920018989193829, 'n_estimators': 311, 'learning_rate': 0.013287182579533728}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:17:15,420] Trial 26 finished with value: 0.6448885335306227 and parameters: {'subsample': 0.867224185897017, 'dropout_rate': 0.524159118998949, 'n_estimators': 140, 'learning_rate': 0.030380762890188803}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 00:17:23,688] Trial 27 finished with value: 0.6436924938049693 and parameters: {'subsample': 0.4283418725935132, 'dropout_rate': 0.6054847715047298, 'n_estimators': 276, 'learning_rate': 0.0018982151266466758}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 00:17:30,765] Trial 28 finished with value: 0.6402986844013421 and parameters: {'subsample': 0.23131169694169362, 'dropout_rate': 0.6759556339789096, 'n_estimators': 226, 'learning_rate': 0.01722458658460315}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:17:40,409] Trial 29 finished with value: 0.6423890258578916 and parameters: {'subsample': 0.5445078393070778, 'dropout_rate': 0.39009335662541156, 'n_estimators': 345, 'learning_rate': 0.025782557435654437}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:17:43,626] Trial 30 finished with value: 0.6487271713746836 and parameters: {'subsample': 0.740594251581977, 'dropout_rate': 0.7457374535389898, 'n_estimators': 47, 'learning_rate': 0.04533396343210069}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:17:46,937] Trial 31 finished with value: 0.6486908148994439 and parameters: {'subsample': 0.6672644585179881, 'dropout_rate': 0.7515705829262332, 'n_estimators': 54, 'learning_rate': 0.06132980546832587}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:17:50,255] Trial 32 finished with value: 0.6487271713746836 and parameters: {'subsample': 0.7327275461586737, 'dropout_rate': 0.7664797479900043, 'n_estimators': 50, 'learning_rate': 0.062230833336482765}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:17:53,751] Trial 33 finished with value: 0.6471699023519155 and parameters: {'subsample': 0.7052899554363676, 'dropout_rate': 0.7535878954485298, 'n_estimators': 63, 'learning_rate': 0.0647797242442408}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:17:56,896] Trial 34 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.7962466562568574, 'dropout_rate': 0.8730575581455766, 'n_estimators': 47, 'learning_rate': 0.08157053839647124}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:18:01,775] Trial 35 finished with value: 0.6448521770553829 and parameters: {'subsample': 0.689136943535989, 'dropout_rate': 0.9381981821357201, 'n_estimators': 131, 'learning_rate': 0.06090286210752555}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:18:05,974] Trial 36 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.8850788886344975, 'dropout_rate': 0.8497284849319764, 'n_estimators': 97, 'learning_rate': 0.047740198862003314}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:18:09,398] Trial 37 finished with value: 0.6471699023519155 and parameters: {'subsample': 0.7465974928938772, 'dropout_rate': 0.762528132423257, 'n_estimators': 41, 'learning_rate': 0.05621431261796065}. Best is trial 7 with value: 0.6499035318694023.

Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:18:11,849] Trial 38 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.7910265829012886, 'dropout_rate': 0.8201500943507289, 'n_estimators': 1, 'learning_rate': 0.0802388198308747}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:18:17,538] Trial 39 finished with value: 0.6471335458766757 and parameters: {'subsample': 0.6483381968153921, 'dropout_rate': 0.6826761322925258, 'n_estimators': 159, 'learning_rate': 0.04656913718567279}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:18:21,229] Trial 40 finished with value: 0.6471699023519155 and parameters: {'subsample': 0.7217274689422681, 'dropout_rate': 0.8887286631915676, 'n_estimators': 67, 'learning_rate': 0.056831039369223575}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:18:25,758] Trial 41 finished with value: 0.6447431076296637 and parameters: {'subsample': 0.5499101555113013, 'dropout_rate': 0.7437832936105103, 'n_estimators': 114, 'learning_rate': 0.06632641686558935}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:18:28,800] Trial 42 finished with value: 0.6392017748618757 and parameters: {'subsample': 0.5017415876482066, 'dropout_rate': 0.6416417766093212, 'n_estimators': 38, 'learning_rate': 0.05134611734790604}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:18:31,666] Trial 43 finished with value: 0.6502480839222122 and parameters: {'subsample': 0.6688819035008029, 'dropout_rate': 0.6964999563725005, 'n_estimators': 21, 'learning_rate': 0.0692844085215762}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:18:34,433] Trial 44 finished with value: 0.6463730896029115 and parameters: {'subsample': 0.7759951791574855, 'dropout_rate': 0.6951159000675758, 'n_estimators': 18, 'learning_rate': 0.06972781553702145}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:18:37,992] Trial 45 finished with value: 0.6448885335306227 and parameters: {'subsample': 0.856068539007671, 'dropout_rate': 0.4938268622013002, 'n_estimators': 67, 'learning_rate': 0.07719198392856119}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:18:42,586] Trial 46 finished with value: 0.6487271713746836 and parameters: {'subsample': 0.6784742045939507, 'dropout_rate': 0.7675812228380298, 'n_estimators': 109, 'learning_rate': 0.060899749572876916}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:18:45,383] Trial 47 finished with value: 0.6471335458766757 and parameters: {'subsample': 0.7439187554546609, 'dropout_rate': 0.8319581886344798, 'n_estimators': 25, 'learning_rate': 0.05462436851714732}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:18:49,722] Trial 48 finished with value: 0.6471335458766757 and parameters: {'subsample': 0.6581550458916713, 'dropout_rate': 0.7770084027642782, 'n_estimators': 108, 'learning_rate': 0.08692259516675999}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:18:53,753] Trial 49 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.9362857595964282, 'dropout_rate': 0.9312088199153865, 'n_estimators': 81, 'learning_rate': 0.06977049657841096}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:18:59,874] Trial 50 finished with value: 0.6456126333291472 and parameters: {'subsample': 0.7212803665834485, 'dropout_rate': 0.5694009859561241, 'n_estimators': 178, 'learning_rate': 0.036450919161848463}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:19:03,241] Trial 51 finished with value: 0.6486908148994439 and parameters: {'subsample': 0.6732576368661897, 'dropout_rate': 0.7323084196301786, 'n_estimators': 54, 'learning_rate': 0.0616255895146821}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:19:06,026] Trial 52 finished with value: 0.6471335458766757 and parameters: {'subsample': 0.820418921570172, 'dropout_rate': 0.7289927847727031, 'n_estimators': 25, 'learning_rate': 0.05984777875916728}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:19:10,907] Trial 53 finished with value: 0.6471699023519155 and parameters: {'subsample': 0.6821912327729229, 'dropout_rate': 0.7717844713363854, 'n_estimators': 138, 'learning_rate': 0.0455458456849779}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6566523605150214
[I 2024-04-17 00:19:14,616] Trial 54 finished with value: 0.6411670920067818 and parameters: {'subsample': 0.6335813528459866, 'dropout_rate': 0.1464738011208001, 'n_estimators': 71, 'learning_rate': 0.06485852546285992}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:19:17,074] Trial 55 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.7684220673327675, 'dropout_rate': 0.6875305359978694, 'n_estimators': 2, 'learning_rate': 0.05114560278593602}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:19:21,724] Trial 56 finished with value: 0.6431858386068956 and parameters: {'subsample': 0.5773668103492899, 'dropout_rate': 0.6555870719053609, 'n_estimators': 100, 'learning_rate': 0.07275479081141786}. Best is trial 43 with value: 0.6502480839222122.

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6652360515021459
[I 2024-04-17 00:19:24,763] Trial 57 finished with value: 0.648142734533046 and parameters: {'subsample': 0.13165605060453595, 'dropout_rate': 0.8409230984897413, 'n_estimators': 37, 'learning_rate': 0.05761113460853838}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:19:28,707] Trial 58 finished with value: 0.6415922131088876 and parameters: {'subsample': 0.5172821771928281, 'dropout_rate': 0.799982532961026, 'n_estimators': 87, 'learning_rate': 0.0627895261503993}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:19:33,591] Trial 59 finished with value: 0.6448521770553829 and parameters: {'subsample': 0.7006807541937076, 'dropout_rate': 0.7349122456506434, 'n_estimators': 124, 'learning_rate': 0.0439747401497207}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:19:39,982] Trial 60 finished with value: 0.6471335458766757 and parameters: {'subsample': 0.6072642743793563, 'dropout_rate': 0.6402301467429573, 'n_estimators': 202, 'learning_rate': 0.03506760456906887}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:19:43,400] Trial 61 finished with value: 0.6486908148994439 and parameters: {'subsample': 0.6675213716233955, 'dropout_rate': 0.7478105639832524, 'n_estimators': 53, 'learning_rate': 0.0677827896370905}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:19:46,710] Trial 62 finished with value: 0.6448521770553829 and parameters: {'subsample': 0.8218620886198889, 'dropout_rate': 0.7068444248710961, 'n_estimators': 54, 'learning_rate': 0.05272223912680717}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:19:49,413] Trial 63 finished with value: 0.64789400215044 and parameters: {'subsample': 0.47161214538021584, 'dropout_rate': 0.7154633387176613, 'n_estimators': 21, 'learning_rate': 0.048604259844136494}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:19:52,035] Trial 64 finished with value: 0.6463730896029115 and parameters: {'subsample': 0.7406729558363441, 'dropout_rate': 0.7865831704791059, 'n_estimators': 16, 'learning_rate': 0.05841729462196311}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:19:57,637] Trial 65 finished with value: 0.6455762768539075 and parameters: {'subsample': 0.6448890403707446, 'dropout_rate': 0.668627976603947, 'n_estimators': 160, 'learning_rate': 0.061809617685827274}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:01,523] Trial 66 finished with value: 0.6471699023519155 and parameters: {'subsample': 0.6796615843390252, 'dropout_rate': 0.5812477282027548, 'n_estimators': 80, 'learning_rate': 0.07182329182875007}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:04,577] Trial 67 finished with value: 0.6499719696449797 and parameters: {'subsample': 0.29121921398342737, 'dropout_rate': 0.8586425932371581, 'n_estimators': 40, 'learning_rate': 0.04087325894113451}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6566523605150214
[I 2024-04-17 00:20:07,706] Trial 68 finished with value: 0.6435575302537938 and parameters: {'subsample': 0.30923418377168843, 'dropout_rate': 0.9192075913805955, 'n_estimators': 42, 'learning_rate': 0.04203361286905793}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:10,661] Trial 69 finished with value: 0.6545494448122506 and parameters: {'subsample': 0.2673314591434677, 'dropout_rate': 0.9825635984118792, 'n_estimators': 27, 'learning_rate': 0.039119840370021815}. Best is trial 69 with value: 0.6545494448122506.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 00:20:13,702] Trial 70 finished with value: 0.6490235438201355 and parameters: {'subsample': 0.24788113029065706, 'dropout_rate': 0.9969638279429532, 'n_estimators': 33, 'learning_rate': 0.029174699028034295}. Best is trial 69 with value: 0.6545494448122506.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6566523605150214
[I 2024-04-17 00:20:16,567] Trial 71 finished with value: 0.6490703626451586 and parameters: {'subsample': 0.20284283527419028, 'dropout_rate': 0.9400140232898505, 'n_estimators': 31, 'learning_rate': 0.027756418017763594}. Best is trial 69 with value: 0.6545494448122506.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:19,139] Trial 72 finished with value: 0.6504199551662718 and parameters: {'subsample': 0.24397158143382094, 'dropout_rate': 0.9771341421393184, 'n_estimators': 14, 'learning_rate': 0.026027501982076335}. Best is trial 69 with value: 0.6545494448122506.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:21,705] Trial 73 finished with value: 0.6443510425008431 and parameters: {'subsample': 0.23743418959132587, 'dropout_rate': 0.9937562571742921, 'n_estimators': 12, 'learning_rate': 0.027976131815278027}. Best is trial 69 with value: 0.6545494448122506.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6652360515021459
[I 2024-04-17 00:20:24,601] Trial 74 finished with value: 0.6538141884129551 and parameters: {'subsample': 0.19091815588432656, 'dropout_rate': 0.962070234548635, 'n_estimators': 27, 'learning_rate': 0.03471229822615198}. Best is trial 69 with value: 0.6545494448122506.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:27,526] Trial 75 finished with value: 0.6459662869494054 and parameters: {'subsample': 0.17697962028685707, 'dropout_rate': 0.9536750685000116, 'n_estimators': 33, 'learning_rate': 0.03386138995721465}. Best is trial 69 with value: 0.6545494448122506.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:30,137] Trial 76 finished with value: 0.6568455511582287 and parameters: {'subsample': 0.2709524394215125, 'dropout_rate': 0.9977383403977458, 'n_estimators': 9, 'learning_rate': 0.03939657254297782}. Best is trial 76 with value: 0.6568455511582287.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:32,628] Trial 77 finished with value: 0.6427790359533895 and parameters: {'subsample': 0.20347186296054398, 'dropout_rate': 0.9681548012999975, 'n_estimators': 8, 'learning_rate': 0.03785529116421354}. Best is trial 76 with value: 0.6568455511582287.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:35,402] Trial 78 finished with value: 0.6547528461390036 and parameters: {'subsample': 0.28157566668981593, 'dropout_rate': 0.9035461240491109, 'n_estimators': 24, 'learning_rate': 0.026165727680464605}. Best is trial 76 with value: 0.6568455511582287.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:37,770] Trial 79 finished with value: 0.662475309074129 and parameters: {'subsample': 0.29526084754361154, 'dropout_rate': 0.8803384724169618, 'n_estimators': 2, 'learning_rate': 0.03924229571145153}. Best is trial 79 with value: 0.662475309074129.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:40,394] Trial 80 finished with value: 0.6555280399374532 and parameters: {'subsample': 0.28050247338247336, 'dropout_rate': 0.9028221658295956, 'n_estimators': 12, 'learning_rate': 0.04027950354554023}. Best is trial 79 with value: 0.662475309074129.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:42,854] Trial 81 finished with value: 0.6563769213593296 and parameters: {'subsample': 0.28756409341411227, 'dropout_rate': 0.9075582848989724, 'n_estimators': 4, 'learning_rate': 0.03240926153881519}. Best is trial 79 with value: 0.662475309074129.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:45,454] Trial 82 finished with value: 0.6486691959488896 and parameters: {'subsample': 0.34473740008813336, 'dropout_rate': 0.8797244968987787, 'n_estimators': 10, 'learning_rate': 0.024643485671596223}. Best is trial 79 with value: 0.662475309074129.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:47,912] Trial 83 finished with value: 0.6685884343136138 and parameters: {'subsample': 0.275865027485883, 'dropout_rate': 0.9005812407751342, 'n_estimators': 2, 'learning_rate': 0.032760100014415844}. Best is trial 83 with value: 0.6685884343136138.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:50,307] Trial 84 finished with value: 0.6609543965266005 and parameters: {'subsample': 0.2732319133565972, 'dropout_rate': 0.912514950065521, 'n_estimators': 3, 'learning_rate': 0.03328188769850406}. Best is trial 83 with value: 0.6685884343136138.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:53,011] Trial 85 finished with value: 0.6594187464543866 and parameters: {'subsample': 0.2763202974709952, 'dropout_rate': 0.8954831681411434, 'n_estimators': 4, 'learning_rate': 0.03207990434181705}. Best is trial 83 with value: 0.6685884343136138.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:55,520] Trial 86 finished with value: 0.6699472340896035 and parameters: {'subsample': 0.2748398992643779, 'dropout_rate': 0.9036811565813793, 'n_estimators': 1, 'learning_rate': 0.03163367036018912}. Best is trial 86 with value: 0.6699472340896035.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:20:58,161] Trial 87 finished with value: 0.6623721464013316 and parameters: {'subsample': 0.2789298231363632, 'dropout_rate': 0.905205062379609, 'n_estimators': 10, 'learning_rate': 0.03198634957549082}. Best is trial 86 with value: 0.6699472340896035.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:21:00,645] Trial 88 finished with value: 0.6484363195727659 and parameters: {'subsample': 0.3243701054601682, 'dropout_rate': 0.908363148108989, 'n_estimators': 8, 'learning_rate': 0.032869247220934934}. Best is trial 86 with value: 0.6699472340896035.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:21:03,008] Trial 89 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.3895210085290416, 'dropout_rate': 0.873741955440528, 'n_estimators': 1, 'learning_rate': 0.03119403066327422}. Best is trial 86 with value: 0.6699472340896035.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:21:05,375] Trial 90 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.3587830031133674, 'dropout_rate': 0.10184332440552968, 'n_estimators': 2, 'learning_rate': 0.0216454887422428}. Best is trial 86 with value: 0.6699472340896035.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:21:08,051] Trial 91 finished with value: 0.6555496588880076 and parameters: {'subsample': 0.27836780615714424, 'dropout_rate': 0.8975503631666281, 'n_estimators': 16, 'learning_rate': 0.03143739107010649}. Best is trial 86 with value: 0.6699472340896035.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 00:21:11,550] Trial 92 finished with value: 0.6434495789221184 and parameters: {'subsample': 0.2211041328850526, 'dropout_rate': 0.9015005738621126, 'n_estimators': 59, 'learning_rate': 0.03667273587285608}. Best is trial 86 with value: 0.6699472340896035.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:21:14,212] Trial 93 finished with value: 0.6528103934132837 and parameters: {'subsample': 0.2638454061175659, 'dropout_rate': 0.9300231562353473, 'n_estimators': 13, 'learning_rate': 0.03185741017583375}. Best is trial 86 with value: 0.6699472340896035.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:21:17,023] Trial 94 finished with value: 0.6525078337929506 and parameters: {'subsample': 0.30394107269394416, 'dropout_rate': 0.8929693877771203, 'n_estimators': 18, 'learning_rate': 0.04083383912419561}. Best is trial 86 with value: 0.6699472340896035.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 00:21:20,760] Trial 95 finished with value: 0.6474947751737906 and parameters: {'subsample': 0.32960406760215655, 'dropout_rate': 0.855307266501353, 'n_estimators': 73, 'learning_rate': 0.030121687462672537}. Best is trial 86 with value: 0.6699472340896035.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:21:23,919] Trial 96 finished with value: 0.6513179812421787 and parameters: {'subsample': 0.15662896488540057, 'dropout_rate': 0.817765538476646, 'n_estimators': 44, 'learning_rate': 0.03868189022086707}. Best is trial 86 with value: 0.6699472340896035.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:21:26,314] Trial 97 finished with value: 0.6609543965266005 and parameters: {'subsample': 0.2790335408535727, 'dropout_rate': 0.31372183756474226, 'n_estimators': 3, 'learning_rate': 0.03542496412269238}. Best is trial 86 with value: 0.6699472340896035.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:21:28,657] Trial 98 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.39994906708509187, 'dropout_rate': 0.22396087436354034, 'n_estimators': 1, 'learning_rate': 0.01850818844111066}. Best is trial 86 with value: 0.6699472340896035.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654

[I 2024-04-17 00:21:31,743] A new study created in memory with name: no-name-82a21973-61ce-4cfe-828a-8d86a72226f2

Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 00:21:31,736] Trial 99 finished with value: 0.6434743549535309 and parameters: {'subsample': 0.35577334839441305, 'dropout_rate': 0.44289810985469763, 'n_estimators': 31, 'learning_rate': 0.023119646100558756}. Best is trial 86 with value: 0.6699472340896035.


* Best trial for C-index:
 FrozenTrial(number=86, state=TrialState.COMPLETE, values=[0.6699472340896035], datetime_start=datetime.datetime(2024, 4, 17, 0, 20, 53, 13053), datetime_complete=datetime.datetime(2024, 4, 17, 0, 20, 55, 520526), params={'subsample': 0.2748398992643779, 'dropout_rate': 0.9036811565813793, 'n_estimators': 1, 'learning_rate': 0.03163367036018912}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=86, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.2748398992643779, 'dropout_rate': 0.9036811565813793, 'n_estimators': 1, 'learning_rate': 0.03163367036018912}


* Best Score for C-index:
 0.6699472340896035

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2535208184290341
Fold 2 IBS: 0.23694039312201395
Fold 3 IBS: 0.3183278645100559
Fold 4 IBS: 0.2785272332047015
Fold 5 IBS: 0.26959701773388006
[I 2024-04-17 00:21:36,213] Trial 0 finished with value: 0.27138266539993705 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.4379931381955231
Fold 2 IBS: 0.38220982923025065
Fold 3 IBS: 0.3920321662913435
Fold 4 IBS: 0.3412768011671995
Fold 5 IBS: 0.33941908574786966
[I 2024-04-17 00:21:49,525] Trial 1 finished with value: 0.3785862041264373 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.3324678077695315
Fold 2 IBS: 0.277934644896449
Fold 3 IBS: 0.37028973305297364
Fold 4 IBS: 0.29747016904097373
Fold 5 IBS: 0.30753782579260386
[I 2024-04-17 00:21:55,392] Trial 2 finished with value: 0.31714003611050634 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.31819805240780114
Fold 2 IBS: 0.2752541423102686
Fold 3 IBS: 0.37171315150390805
Fold 4 IBS: 0.2766993729668638
Fold 5 IBS: 0.3220161766839568
[I 2024-04-17 00:22:02,033] Trial 3 finished with value: 0.3127761791745597 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.32511222009503676
Fold 2 IBS: 0.28040366583530113
Fold 3 IBS: 0.3759516970841758
Fold 4 IBS: 0.2831367343962378
Fold 5 IBS: 0.3211661754469021
[I 2024-04-17 00:22:10,229] Trial 4 finished with value: 0.31715409857153076 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.43183877461465453
Fold 2 IBS: 0.3462655068788492
Fold 3 IBS: 0.3901822518832906
Fold 4 IBS: 0.3158040918671078
Fold 5 IBS: 0.3240588862506669
[I 2024-04-17 00:22:20,062] Trial 5 finished with value: 0.36162990229891384 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.23162026538239194
Fold 2 IBS: 0.2130450924041672
Fold 3 IBS: 0.2929798151511939
Fold 4 IBS: 0.2602468384417057
Fold 5 IBS: 0.24596662301082522
[I 2024-04-17 00:22:26,147] Trial 6 finished with value: 0.2487717268780568 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2487717268780568.
Fold 1 IBS: 0.2219624571251742
Fold 2 IBS: 0.20191698224064816
Fold 3 IBS: 0.2554464703379466
Fold 4 IBS: 0.22028035730313134
Fold 5 IBS: 0.21397872069101548
[I 2024-04-17 00:22:29,354] Trial 7 finished with value: 0.22271699753958316 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.26135001657957846
Fold 2 IBS: 0.24282456049458448
Fold 3 IBS: 0.326134406423236
Fold 4 IBS: 0.27402360123646585
Fold 5 IBS: 0.2768152873434484
[I 2024-04-17 00:22:35,784] Trial 8 finished with value: 0.27622957441546264 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.438775036769916
Fold 2 IBS: 0.35568555286291453
Fold 3 IBS: 0.390909578851063
Fold 4 IBS: 0.31218235322033017
Fold 5 IBS: 0.32722373811786437
[I 2024-04-17 00:22:48,014] Trial 9 finished with value: 0.3649552519644176 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.2460224099705921
Fold 2 IBS: 0.23086098108808756
Fold 3 IBS: 0.2288453379547681
Fold 4 IBS: 0.24136765896018506
Fold 5 IBS: 0.2281543805010059
[I 2024-04-17 00:22:50,785] Trial 10 finished with value: 0.23505015369492774 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.24222241773116046
Fold 2 IBS: 0.22722173122509534
Fold 3 IBS: 0.2286593447825781
Fold 4 IBS: 0.2395148036138026
Fold 5 IBS: 0.22443221144275918
[I 2024-04-17 00:22:53,166] Trial 11 finished with value: 0.23241010175907917 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.2405557113130908
Fold 2 IBS: 0.21491858221804258
Fold 3 IBS: 0.30499365850510085
Fold 4 IBS: 0.23566664215634284
Fold 5 IBS: 0.24475205448274662
[I 2024-04-17 00:22:56,638] Trial 12 finished with value: 0.24817732973506476 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.23944832000588395
Fold 2 IBS: 0.22451123143312443
Fold 3 IBS: 0.22879762094537542
Fold 4 IBS: 0.23820765139553346
Fold 5 IBS: 0.22173810615143869
[I 2024-04-17 00:22:59,234] Trial 13 finished with value: 0.23054058598627117 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22826207452412578
Fold 2 IBS: 0.20708009192406637
Fold 3 IBS: 0.2838897565833488
Fold 4 IBS: 0.2304990846646447
Fold 5 IBS: 0.23613357206494798
[I 2024-04-17 00:23:03,901] Trial 14 finished with value: 0.23717291595222673 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.275392871065553
Fold 2 IBS: 0.2585619199470001
Fold 3 IBS: 0.34359360523637944
Fold 4 IBS: 0.2695300185359706
Fold 5 IBS: 0.2900236218757005
[I 2024-04-17 00:23:08,166] Trial 15 finished with value: 0.28742040733212076 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.298014889246324
Fold 2 IBS: 0.2734525470258891
Fold 3 IBS: 0.35392032573580473
Fold 4 IBS: 0.2781375154015373
Fold 5 IBS: 0.30449340223416854
[I 2024-04-17 00:23:16,292] Trial 16 finished with value: 0.3016037359287448 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22571204260462702
Fold 2 IBS: 0.21029571932609178
Fold 3 IBS: 0.23477013659701168
Fold 4 IBS: 0.23294813806507536
Fold 5 IBS: 0.2112667744029953
[I 2024-04-17 00:23:20,127] Trial 17 finished with value: 0.2229985621991602 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22749628705840008
Fold 2 IBS: 0.208593559309439
Fold 3 IBS: 0.2860837988705294
Fold 4 IBS: 0.255694330022353
Fold 5 IBS: 0.23961625820762958
[I 2024-04-17 00:23:29,785] Trial 18 finished with value: 0.24349684669367022 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22458664776493728
Fold 2 IBS: 0.20232195896375377

Fold 3 IBS: 0.27412770407771303
Fold 4 IBS: 0.2250727043053573
Fold 5 IBS: 0.2280063139706162
[I 2024-04-17 00:23:34,631] Trial 19 finished with value: 0.23082306581647552 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22813963029627435
Fold 2 IBS: 0.21261919492535192
Fold 3 IBS: 0.2328032377684259
Fold 4 IBS: 0.23177471930860935
Fold 5 IBS: 0.21241390693232276
[I 2024-04-17 00:23:38,158] Trial 20 finished with value: 0.22355013784619687 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.23294882482388735
Fold 2 IBS: 0.2172731528360657
Fold 3 IBS: 0.23037554967791973
Fold 4 IBS: 0.23393962524579212
Fold 5 IBS: 0.21554329357937044
[I 2024-04-17 00:23:41,848] Trial 21 finished with value: 0.22601608923260708 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22457381812654392
Fold 2 IBS: 0.20893564288887
Fold 3 IBS: 0.23611424341865672
Fold 4 IBS: 0.23267189537604366
Fold 5 IBS: 0.21078105893610707
[I 2024-04-17 00:23:45,278] Trial 22 finished with value: 0.22261533174924425 and parameters: {'subsample': 0.8615610863035676, 'dropout_rate': 0.7601905131808098, 'n_estimators': 57, 'learning_rate': 0.019334429052945145}. Best is trial 22 with value: 0.22261533174924425.
Fold 1 IBS: 0.2719235052333098
Fold 2 IBS: 0.23764489493573734
Fold 3 IBS: 0.3193018171397408
Fold 4 IBS: 0.2836424571696349
Fold 5 IBS: 0.2702613255072474
[I 2024-04-17 00:23:50,474] Trial 23 finished with value: 0.27655479999713406 and parameters: {'subsample': 0.8557281003254902, 'dropout_rate': 0.618865896035061, 'n_estimators': 150, 'learning_rate': 0.04186582141545488}. Best is trial 22 with value: 0.22261533174924425.
Fold 1 IBS: 0.22147474510826237
Fold 2 IBS: 0.2056747916191557
Fold 3 IBS: 0.24049201615940596
Fold 4 IBS: 0.23256814236182405
Fold 5 IBS: 0.21033940163812648
[I 2024-04-17 00:23:54,075] Trial 24 finished with value: 0.22210981937735488 and parameters: {'subsample': 0.8736292350257677, 'dropout_rate': 0.9758883725345413, 'n_estimators': 56, 'learning_rate': 0.02427957701685606}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.2294989380094321
Fold 2 IBS: 0.21191311870816967
Fold 3 IBS: 0.23574856019681506
Fold 4 IBS: 0.22643183601188832
Fold 5 IBS: 0.21142162434179954
[I 2024-04-17 00:23:57,711] Trial 25 finished with value: 0.22300281545362094 and parameters: {'subsample': 0.19468056412788132, 'dropout_rate': 0.9897789595635863, 'n_estimators': 40, 'learning_rate': 0.025002990823540957}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.23333397090317404
Fold 2 IBS: 0.21300462246331686
Fold 3 IBS: 0.2919265248430093
Fold 4 IBS: 0.26141154567737246
Fold 5 IBS: 0.24514756200998605
[I 2024-04-17 00:24:02,115] Trial 26 finished with value: 0.24896484517937173 and parameters: {'subsample': 0.9043940009344528, 'dropout_rate': 0.9033888277148059, 'n_estimators': 92, 'learning_rate': 0.04553017387255954}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.23638591525082767
Fold 2 IBS: 0.21516306172620478
Fold 3 IBS: 0.2951885661305264
Fold 4 IBS: 0.2637815004845914
Fold 5 IBS: 0.2478693530817822
[I 2024-04-17 00:24:07,266] Trial 27 finished with value: 0.25167767933478646 and parameters: {'subsample': 0.8218236648644409, 'dropout_rate': 0.7846036392151594, 'n_estimators': 145, 'learning_rate': 0.030307532796347948}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.24064419834309675
Fold 2 IBS: 0.22415587169214657
Fold 3 IBS: 0.22881420079591844
Fold 4 IBS: 0.23693120040178806
Fold 5 IBS: 0.22166322813485473
[I 2024-04-17 00:24:14,202] Trial 28 finished with value: 0.2304417398735609 and parameters: {'subsample': 0.3907993998263619, 'dropout_rate': 0.9279548799256215, 'n_estimators': 233, 'learning_rate': 0.001303388577036546}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.21842977369684194
Fold 2 IBS: 0.2011107725842906
Fold 3 IBS: 0.25384448921376923
Fold 4 IBS: 0.232211579011124
Fold 5 IBS: 0.2157044751662694
[I 2024-04-17 00:24:18,626] Trial 29 finished with value: 0.22426021793445905 and parameters: {'subsample': 0.5790219222156496, 'dropout_rate': 0.7695165335542838, 'n_estimators': 108, 'learning_rate': 0.01903980772031594}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.22163880438788114
Fold 2 IBS: 0.2060581683786993
Fold 3 IBS: 0.2396778541303928
Fold 4 IBS: 0.22756268731638724
Fold 5 IBS: 0.21031352296982186
[I 2024-04-17 00:24:21,520] Trial 30 finished with value: 0.22105020743663645 and parameters: {'subsample': 0.7079769658545929, 'dropout_rate': 0.8498048136204235, 'n_estimators': 29, 'learning_rate': 0.046221173886982825}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2200724127940874
Fold 2 IBS: 0.20420688373140491
Fold 3 IBS: 0.2434279631041286
Fold 4 IBS: 0.23088381472023015
Fold 5 IBS: 0.2107203802256644
[I 2024-04-17 00:24:24,331] Trial 31 finished with value: 0.22186229091510307 and parameters: {'subsample': 0.7782166094867763, 'dropout_rate': 0.8526511128221191, 'n_estimators': 26, 'learning_rate': 0.05869348626309983}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2220192442415896
Fold 2 IBS: 0.20656029859231154
Fold 3 IBS: 0.23956067627789562
Fold 4 IBS: 0.23254630069491217
Fold 5 IBS: 0.21031393154503805
[I 2024-04-17 00:24:27,075] Trial 32 finished with value: 0.22220009027034937 and parameters: {'subsample': 0.7878845579666447, 'dropout_rate': 0.8560240225148643, 'n_estimators': 22, 'learning_rate': 0.05967077858339052}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2291078679995047
Fold 2 IBS: 0.21341140636860573
Fold 3 IBS: 0.23192802809417654
Fold 4 IBS: 0.23402147506607907
Fold 5 IBS: 0.21317832146276416
[I 2024-04-17 00:24:29,642] Trial 33 finished with value: 0.22432941979822604 and parameters: {'subsample': 0.7794604399156984, 'dropout_rate': 0.9504625799325089, 'n_estimators': 13, 'learning_rate': 0.06055914650999865}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.25430560739242225
Fold 2 IBS: 0.2284133753114856
Fold 3 IBS: 0.3090625406037944
Fold 4 IBS: 0.2732154551860483
Fold 5 IBS: 0.2621904177585131
[I 2024-04-17 00:24:33,598] Trial 34 finished with value: 0.2654374792504527 and parameters: {'subsample': 0.6982462018109117, 'dropout_rate': 0.8639367030524437, 'n_estimators': 84, 'learning_rate': 0.0649821776613948}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.21768018948179807
Fold 2 IBS: 0.20112990863142238
Fold 3 IBS: 0.2547679190320581
Fold 4 IBS: 0.2359778319362916
Fold 5 IBS: 0.21519795791889573
[I 2024-04-17 00:24:36,531] Trial 35 finished with value: 0.22495076140009318 and parameters: {'subsample': 0.7880243815860887, 'dropout_rate': 0.999943957221368, 'n_estimators': 27, 'learning_rate': 0.07675979779302834}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2977141155977322
Fold 2 IBS: 0.24775644913124664
Fold 3 IBS: 0.3306511114108861
Fold 4 IBS: 0.2923888275212842
Fold 5 IBS: 0.28032513089432576
[I 2024-04-17 00:24:41,386] Trial 36 finished with value: 0.28976712691109496 and parameters: {'subsample': 0.9189450187030327, 'dropout_rate': 0.8476672993402941, 'n_estimators': 129, 'learning_rate': 0.05573723451692966}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.3811658445880461
Fold 2 IBS: 0.2758127038773145
Fold 3 IBS: 0.36709218055056614
Fold 4 IBS: 0.30550730104285034
Fold 5 IBS: 0.3067044688141932
[I 2024-04-17 00:24:46,978] Trial 37 finished with value: 0.3272564997745941 and parameters: {'subsample': 0.739264920272442, 'dropout_rate': 0.8927843858195293, 'n_estimators': 169, 'learning_rate': 0.06888028701406422}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2264971103333118
Fold 2 IBS: 0.20135233326855248
Fold 3 IBS: 0.2526241904073602

Fold 4 IBS: 0.22761235729593224
Fold 5 IBS: 0.21391136761511492
[I 2024-04-17 00:24:49,806] Trial 38 finished with value: 0.22439947178405434 and parameters: {'subsample': 0.9323458933659868, 'dropout_rate': 0.13272164755980653, 'n_estimators': 28, 'learning_rate': 0.0802388198308747}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.22935008117918856
Fold 2 IBS: 0.21153618549256686
Fold 3 IBS: 0.29072451950301204
Fold 4 IBS: 0.2586656669929489
Fold 5 IBS: 0.24321840787686647
[I 2024-04-17 00:24:53,662] Trial 39 finished with value: 0.24669897220891657 and parameters: {'subsample': 0.7076071631229807, 'dropout_rate': 0.36113352605756727, 'n_estimators': 75, 'learning_rate': 0.05598015324329953}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.4295827306814518
Fold 2 IBS: 0.33729766730917193
Fold 3 IBS: 0.38924638966253877
Fold 4 IBS: 0.31325291352447
Fold 5 IBS: 0.32175848063875884
[I 2024-04-17 00:25:05,734] Trial 40 finished with value: 0.35822763636327826 and parameters: {'subsample': 0.8123581601061346, 'dropout_rate': 0.27073406810212547, 'n_estimators': 434, 'learning_rate': 0.050770250632636425}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.21843232747192648
Fold 2 IBS: 0.20124696623375102
Fold 3 IBS: 0.26589789731233937
Fold 4 IBS: 0.23953030936979589
Fold 5 IBS: 0.22339485398021788
[I 2024-04-17 00:25:09,078] Trial 41 finished with value: 0.22970047087360612 and parameters: {'subsample': 0.7485948672215855, 'dropout_rate': 0.827821271771765, 'n_estimators': 44, 'learning_rate': 0.06100155441044479}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.24545977554153506
Fold 2 IBS: 0.2302404349481251
Fold 3 IBS: 0.228814223366646
Fold 4 IBS: 0.24097498117887786
Fold 5 IBS: 0.22762304438597
[I 2024-04-17 00:25:11,434] Trial 42 finished with value: 0.2346224918842308 and parameters: {'subsample': 0.6600001822368337, 'dropout_rate': 0.7512215971522175, 'n_estimators': 1, 'learning_rate': 0.06911254892370094}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2177286772534359
Fold 2 IBS: 0.20073314902484793
Fold 3 IBS: 0.2599125036038046
Fold 4 IBS: 0.23844492228389882
Fold 5 IBS: 0.21818700490217124
[I 2024-04-17 00:25:14,645] Trial 43 finished with value: 0.2270012514136317 and parameters: {'subsample': 0.8163078290274218, 'dropout_rate': 0.939553917830419, 'n_estimators': 49, 'learning_rate': 0.047734596204521335}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.23079869739063893
Fold 2 IBS: 0.21524619860909036
Fold 3 IBS: 0.23135881430740626
Fold 4 IBS: 0.23215245196525136
Fold 5 IBS: 0.21397390753677142
[I 2024-04-17 00:25:17,473] Trial 44 finished with value: 0.22470601396183168 and parameters: {'subsample': 0.5793955243729101, 'dropout_rate': 0.8902546449865933, 'n_estimators': 25, 'learning_rate': 0.02941573453153995}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.23463938291343403
Fold 2 IBS: 0.21378641058446565
Fold 3 IBS: 0.2936585740423683
Fold 4 IBS: 0.2623275744743812
Fold 5 IBS: 0.24681085413233397
[I 2024-04-17 00:25:22,233] Trial 45 finished with value: 0.2502445592293966 and parameters: {'subsample': 0.9427673116011092, 'dropout_rate': 0.817057053206203, 'n_estimators': 116, 'learning_rate': 0.0370342562578839}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.40086920822949945
Fold 2 IBS: 0.28091448436473726
Fold 3 IBS: 0.3720791128836979
Fold 4 IBS: 0.307109292579857
Fold 5 IBS: 0.308674520431342
[I 2024-04-17 00:25:28,510] Trial 46 finished with value: 0.3339293236978267 and parameters: {'subsample': 0.8772929906687839, 'dropout_rate': 0.9519780159701515, 'n_estimators': 194, 'learning_rate': 0.06489928133343151}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.232466351187792
Fold 2 IBS: 0.21715839919246133
Fold 3 IBS: 0.23045465132815326
Fold 4 IBS: 0.23505329955231874
Fold 5 IBS: 0.21545322244115622
[I 2024-04-17 00:25:32,429] Trial 47 finished with value: 0.22611718474037631 and parameters: {'subsample': 0.7741938008338972, 'dropout_rate': 0.7343720546814592, 'n_estimators': 75, 'learning_rate': 0.008209618821055878}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.21928772309722075
Fold 2 IBS: 0.20290025316680066
Fold 3 IBS: 0.24625852536625306
Fold 4 IBS: 0.22756184240178828
Fold 5 IBS: 0.21155714687356678
[I 2024-04-17 00:25:35,419] Trial 48 finished with value: 0.2215130981811259 and parameters: {'subsample': 0.6902001509321368, 'dropout_rate': 0.6604314111556595, 'n_estimators': 33, 'learning_rate': 0.052217916997002886}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.22864268464482704
Fold 2 IBS: 0.20618701072642076
Fold 3 IBS: 0.23974348161514325
Fold 4 IBS: 0.22902300059149802
Fold 5 IBS: 0.21031693369470345
[I 2024-04-17 00:25:38,388] Trial 49 finished with value: 0.22278262225451853 and parameters: {'subsample': 0.5246256412363035, 'dropout_rate': 0.444654827003804, 'n_estimators': 26, 'learning_rate': 0.05201530493205449}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.4256560799384403
Fold 2 IBS: 0.3151221688354275
Fold 3 IBS: 0.3860413488667417
Fold 4 IBS: 0.3089178353626252
Fold 5 IBS: 0.317098910141038
[I 2024-04-17 00:25:48,896] Trial 50 finished with value: 0.3505672686288545 and parameters: {'subsample': 0.6713843248996562, 'dropout_rate': 0.6491522181398676, 'n_estimators': 379, 'learning_rate': 0.04745080772448178}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2192431668518127
Fold 2 IBS: 0.20189468163918148
Fold 3 IBS: 0.26982441152732806
Fold 4 IBS: 0.23613925370649705
Fold 5 IBS: 0.2256653604972261
[I 2024-04-17 00:25:52,187] Trial 51 finished with value: 0.23055337484440908 and parameters: {'subsample': 0.7172193716930169, 'dropout_rate': 0.6709427179664875, 'n_estimators': 48, 'learning_rate': 0.05997708252875927}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2410305123087452
Fold 2 IBS: 0.2195671978090868
Fold 3 IBS: 0.2993407314297869
Fold 4 IBS: 0.26849472696514515
Fold 5 IBS: 0.25209231830194867
[I 2024-04-17 00:25:56,355] Trial 52 finished with value: 0.25610509736294257 and parameters: {'subsample': 0.8289606252433972, 'dropout_rate': 0.7512811922273754, 'n_estimators': 84, 'learning_rate': 0.05632002652421048}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.24612203266949853
Fold 2 IBS: 0.23087751124769623
Fold 3 IBS: 0.22885621209387846
Fold 4 IBS: 0.24139543456033377
Fold 5 IBS: 0.22821141204302334
[I 2024-04-17 00:25:58,763] Trial 53 finished with value: 0.23509252052288607 and parameters: {'subsample': 0.9644210790375523, 'dropout_rate': 0.6894833612317082, 'n_estimators': 1, 'learning_rate': 0.04185368229372562}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.22818239059764914
Fold 2 IBS: 0.20984620997622416
Fold 3 IBS: 0.2867822539050355
Fold 4 IBS: 0.25462805104656905
Fold 5 IBS: 0.24007539469996075
[I 2024-04-17 00:26:02,195] Trial 54 finished with value: 0.2439028600450877 and parameters: {'subsample': 0.7754401293458196, 'dropout_rate': 0.8581787213295002, 'n_estimators': 59, 'learning_rate': 0.06494770180873123}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.22257503395436767
Fold 2 IBS: 0.20677739071945617
Fold 3 IBS: 0.23796734142055684
Fold 4 IBS: 0.22680201011024181
Fold 5 IBS: 0.2103640282316372
[I 2024-04-17 00:26:05,166] Trial 55 finished with value: 0.22089716088725195 and parameters: {'subsample': 0.6046650456267857, 'dropout_rate': 0.8107431542120329, 'n_estimators': 36, 'learning_rate': 0.035281924830240646}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2341460554286086
Fold 2 IBS: 0.21898083332700824
Fold 3 IBS: 0.22984714409801585
Fold 4 IBS: 0.23206905279076265
Fold 5 IBS: 0.21732092597900418
[I 2024-04-17 00:26:07,807] Trial 56 finished with value: 0.2264728023246799 and parameters: {'subsample': 0.6148929150329211, 'dropout_rate': 0.9112147525268226, 'n_estimators': 16, 'learning_rate': 0.033986625231595756}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.28505309347602925
Fold 2 IBS: 0.24760499505067732
Fold 3 IBS: 0.3301622822216491
Fold 4 IBS: 0.2894327690728538

Fold 5 IBS: 0.28019979914084864
[I 2024-04-17 00:26:15,910] Trial 57 finished with value: 0.28649058779241166 and parameters: {'subsample': 0.6825327446543555, 'dropout_rate': 0.5208726510676236, 'n_estimators': 282, 'learning_rate': 0.025565265724993874}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2214507245251379
Fold 2 IBS: 0.20506568938296435
Fold 3 IBS: 0.24075353489551313
Fold 4 IBS: 0.2288359521484131
Fold 5 IBS: 0.2104012829571286
[I 2024-04-17 00:26:19,034] Trial 58 finished with value: 0.22130143678183142 and parameters: {'subsample': 0.5793765216559574, 'dropout_rate': 0.869359581862351, 'n_estimators': 38, 'learning_rate': 0.03754893539001649}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22332388143407295
Fold 2 IBS: 0.20363163283585628
Fold 3 IBS: 0.24449748198927226
Fold 4 IBS: 0.22907918428885007
Fold 5 IBS: 0.21077017722074096
[I 2024-04-17 00:26:22,292] Trial 59 finished with value: 0.22226047155375853 and parameters: {'subsample': 0.4535266512643318, 'dropout_rate': 0.9611194785854935, 'n_estimators': 40, 'learning_rate': 0.038908657923000085}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2426474010909224
Fold 2 IBS: 0.22436959888835237
Fold 3 IBS: 0.3051332800511575
Fold 4 IBS: 0.26525378607334044
Fold 5 IBS: 0.25799073524428723
[I 2024-04-17 00:26:27,143] Trial 60 finished with value: 0.25907896026961197 and parameters: {'subsample': 0.5592773031153138, 'dropout_rate': 0.805892721742462, 'n_estimators': 118, 'learning_rate': 0.04300303133619651}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.23322262418938672
Fold 2 IBS: 0.21780502341126942
Fold 3 IBS: 0.23021413524283157
Fold 4 IBS: 0.2317083947092564
Fold 5 IBS: 0.21648635752240689
[I 2024-04-17 00:26:29,911] Trial 61 finished with value: 0.22588730701503024 and parameters: {'subsample': 0.6197162239153043, 'dropout_rate': 0.897755135761733, 'n_estimators': 18, 'learning_rate': 0.033093783201145574}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22321650757486647
Fold 2 IBS: 0.2028003645937837
Fold 3 IBS: 0.24711601825710883
Fold 4 IBS: 0.22957583498652415
Fold 5 IBS: 0.2113955496138467
[I 2024-04-17 00:26:32,900] Trial 62 finished with value: 0.22282085500522597 and parameters: {'subsample': 0.5148326884231843, 'dropout_rate': 0.8753399354683069, 'n_estimators': 35, 'learning_rate': 0.048706108725934165}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.21864755972668926
Fold 2 IBS: 0.2016225251367432
Fold 3 IBS: 0.2509189112353247
Fold 4 IBS: 0.23100076284482912
Fold 5 IBS: 0.2136479732966466
[I 2024-04-17 00:26:36,591] Trial 63 finished with value: 0.22316754644804657 and parameters: {'subsample': 0.6487668076796561, 'dropout_rate': 0.8232768248813066, 'n_estimators': 70, 'learning_rate': 0.027357634359371004}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22030711444046622
Fold 2 IBS: 0.2028872132298813
Fold 3 IBS: 0.2723990807024937
Fold 4 IBS: 0.23234983693422795
Fold 5 IBS: 0.22892547385548054
[I 2024-04-17 00:26:39,949] Trial 64 finished with value: 0.23137374383250994 and parameters: {'subsample': 0.5975058672190523, 'dropout_rate': 0.7823037659988256, 'n_estimators': 56, 'learning_rate': 0.05410979520775479}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2246485985201335
Fold 2 IBS: 0.2058825400782259
Fold 3 IBS: 0.2824399132357561
Fold 4 IBS: 0.23828761615189975
Fold 5 IBS: 0.23650207193611295
[I 2024-04-17 00:26:43,929] Trial 65 finished with value: 0.23755214798442564 and parameters: {'subsample': 0.45888887591206007, 'dropout_rate': 0.9190970086086071, 'n_estimators': 90, 'learning_rate': 0.038689837069848146}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.23273965002953717
Fold 2 IBS: 0.21725871845559455
Fold 3 IBS: 0.23057552835557654
Fold 4 IBS: 0.2346983844695266
Fold 5 IBS: 0.21547730446319574
[I 2024-04-17 00:26:46,500] Trial 66 finished with value: 0.22614991715468613 and parameters: {'subsample': 0.7326959870204457, 'dropout_rate': 0.8441970079444766, 'n_estimators': 14, 'learning_rate': 0.04501243637315829}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2531769237494069
Fold 2 IBS: 0.23296920068260224
Fold 3 IBS: 0.3140245626406833
Fold 4 IBS: 0.2699122978070452
Fold 5 IBS: 0.26615389994000355
[I 2024-04-17 00:26:51,072] Trial 67 finished with value: 0.2672473769639482 and parameters: {'subsample': 0.5471917580520336, 'dropout_rate': 0.9769821442118126, 'n_estimators': 99, 'learning_rate': 0.057929390501509886}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2182645606215572
Fold 2 IBS: 0.20076151212811258
Fold 3 IBS: 0.26082805345729165
Fold 4 IBS: 0.23236316881117391
Fold 5 IBS: 0.21885563811795794
[I 2024-04-17 00:26:54,164] Trial 68 finished with value: 0.22621458662721866 and parameters: {'subsample': 0.6946889669430717, 'dropout_rate': 0.583662202262188, 'n_estimators': 34, 'learning_rate': 0.07261636225834231}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2205185249303166
Fold 2 IBS: 0.2039865579628996
Fold 3 IBS: 0.24377138068999496
Fold 4 IBS: 0.2298605380624899
Fold 5 IBS: 0.2109444943185319
[I 2024-04-17 00:26:58,089] Trial 69 finished with value: 0.2218162991928466 and parameters: {'subsample': 0.6454763362460977, 'dropout_rate': 0.720522833073103, 'n_estimators': 72, 'learning_rate': 0.021510860950056627}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22195649096735395
Fold 2 IBS: 0.2057796473545906
Fold 3 IBS: 0.24047621118241896
Fold 4 IBS: 0.22883745019976204
Fold 5 IBS: 0.21040296604701988
[I 2024-04-17 00:27:02,024] Trial 70 finished with value: 0.22149055315022909 and parameters: {'subsample': 0.5867802742615672, 'dropout_rate': 0.7164929446280183, 'n_estimators': 74, 'learning_rate': 0.01836623067581729}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2224574115110653
Fold 2 IBS: 0.20624684542359964
Fold 3 IBS: 0.23963014108905373
Fold 4 IBS: 0.22900785656242212
Fold 5 IBS: 0.210325868066254
[I 2024-04-17 00:27:05,725] Trial 71 finished with value: 0.22153362453047895 and parameters: {'subsample': 0.5943758778419203, 'dropout_rate': 0.7178705789257822, 'n_estimators': 75, 'learning_rate': 0.01747576819572829}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.21907570074462793
Fold 2 IBS: 0.20169546621039425
Fold 3 IBS: 0.25033163822633475
Fold 4 IBS: 0.23075068452470274
Fold 5 IBS: 0.213686630109571
[I 2024-04-17 00:27:09,740] Trial 72 finished with value: 0.2231080239631261 and parameters: {'subsample': 0.5766850407934205, 'dropout_rate': 0.6867676859247152, 'n_estimators': 90, 'learning_rate': 0.02089435843239119}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.21942878302413968
Fold 2 IBS: 0.20183778716815864
Fold 3 IBS: 0.2501366496560795
Fold 4 IBS: 0.2315135061719935
Fold 5 IBS: 0.21360678712048178
[I 2024-04-17 00:27:14,979] Trial 73 finished with value: 0.22330470262817062 and parameters: {'subsample': 0.6350981564062819, 'dropout_rate': 0.724091326177061, 'n_estimators': 144, 'learning_rate': 0.013043210125809303}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.23786360690225444
Fold 2 IBS: 0.22245402837048767
Fold 3 IBS: 0.22903028955483665
Fold 4 IBS: 0.23621957174006056
Fold 5 IBS: 0.21976820761106206
[I 2024-04-17 00:27:18,772] Trial 74 finished with value: 0.22906714083574026 and parameters: {'subsample': 0.601523470567797, 'dropout_rate': 0.6566427706952908, 'n_estimators': 74, 'learning_rate': 0.005080429459703627}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2214943627310797
Fold 2 IBS: 0.20164308069300232
Fold 3 IBS: 0.25169555993234316
Fold 4 IBS: 0.22841371586916473
Fold 5 IBS: 0.21416681676848298
[I 2024-04-17 00:27:23,226] Trial 75 finished with value: 0.22348270719881458 and parameters: {'subsample': 0.49319069081038364, 'dropout_rate': 0.7076570957071591, 'n_estimators': 105, 'learning_rate': 0.01824490640855918}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2328946499056936
Fold 2 IBS: 0.2170979257337216
Fold 3 IBS: 0.23040550426683937
Fold 4 IBS: 0.2332389132664599
Fold 5 IBS: 0.2156801492109445
[I 2024-04-17 00:27:26,522] Trial 76 finished with value: 0.2258634284767318 and parameters: {'subsample': 0.6388046490330901, 'dropout_rate': 0.618911653541915, 'n_estimators': 42, 'learning_rate': 0.014880869357715765}. Best is trial 55 with value: 0.22089716088725195.

Fold 1 IBS: 0.22462298117263793
Fold 2 IBS: 0.2073982536472491
Fold 3 IBS: 0.28361457332876805
Fold 4 IBS: 0.24675247717794
Fold 5 IBS: 0.2381675349082399
[I 2024-04-17 00:27:32,298] Trial 77 finished with value: 0.240111164046967 and parameters: {'subsample': 0.541487090871485, 'dropout_rate': 0.7704979082473631, 'n_estimators': 165, 'learning_rate': 0.02189762732192369}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22365763185049595
Fold 2 IBS: 0.20591143440013582
Fold 3 IBS: 0.280976248290565
Fold 4 IBS: 0.24848562445786387
Fold 5 IBS: 0.23615081501710733
[I 2024-04-17 00:27:37,119] Trial 78 finished with value: 0.2390363508032336 and parameters: {'subsample': 0.6733814576309736, 'dropout_rate': 0.7358591929789065, 'n_estimators': 128, 'learning_rate': 0.02725879214599771}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22811684389438022
Fold 2 IBS: 0.21004117151133037
Fold 3 IBS: 0.23552715888942047
Fold 4 IBS: 0.22642754442179203
Fold 5 IBS: 0.2109726578133541
[I 2024-04-17 00:27:40,588] Trial 79 finished with value: 0.22221707530605544 and parameters: {'subsample': 0.4590324206086437, 'dropout_rate': 0.5730916522393441, 'n_estimators': 62, 'learning_rate': 0.016584715438210443}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.21914807252926094
Fold 2 IBS: 0.20152400712862856
Fold 3 IBS: 0.2680973864145784
Fold 4 IBS: 0.2372703504251833
Fold 5 IBS: 0.22464173105960364
[I 2024-04-17 00:27:50,062] Trial 80 finished with value: 0.23013630951145098 and parameters: {'subsample': 0.5700298173994884, 'dropout_rate': 0.7963649913222645, 'n_estimators': 327, 'learning_rate': 0.008427919156244693}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22077348750169198
Fold 2 IBS: 0.20465087956377137
Fold 3 IBS: 0.24199806863414064
Fold 4 IBS: 0.22642953767379848
Fold 5 IBS: 0.2105996070892919
[I 2024-04-17 00:27:53,433] Trial 81 finished with value: 0.2208903160925389 and parameters: {'subsample': 0.5967091670188371, 'dropout_rate': 0.8767395889398294, 'n_estimators': 48, 'learning_rate': 0.030725485144314495}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.2181890289575755
Fold 2 IBS: 0.20085037679728737
Fold 3 IBS: 0.2628056745478857
Fold 4 IBS: 0.2329689235642938
Fold 5 IBS: 0.22111819009301079
[I 2024-04-17 00:27:57,568] Trial 82 finished with value: 0.22718643879201061 and parameters: {'subsample': 0.591713415609599, 'dropout_rate': 0.8271461226738561, 'n_estimators': 81, 'learning_rate': 0.03066131851432999}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.23796348921996144
Fold 2 IBS: 0.22231306926597583
Fold 3 IBS: 0.22917826331147176
Fold 4 IBS: 0.23592312507334565
Fold 5 IBS: 0.2199694633866284
[I 2024-04-17 00:28:00,179] Trial 83 finished with value: 0.22906948205147662 and parameters: {'subsample': 0.5104385117001161, 'dropout_rate': 0.8678063293886515, 'n_estimators': 11, 'learning_rate': 0.03618620932286212}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22381030523700307
Fold 2 IBS: 0.20720978403751017
Fold 3 IBS: 0.237911829205767
Fold 4 IBS: 0.22792947965938568
Fold 5 IBS: 0.2104040102787604
[I 2024-04-17 00:28:03,494] Trial 84 finished with value: 0.22145308168368527 and parameters: {'subsample': 0.6572552519386883, 'dropout_rate': 0.6327349414747185, 'n_estimators': 44, 'learning_rate': 0.028170869846693994}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.21850846200789092
Fold 2 IBS: 0.20113172065685006
Fold 3 IBS: 0.25393815497147415
Fold 4 IBS: 0.2312989153770497
Fold 5 IBS: 0.2150707094266202
[I 2024-04-17 00:28:07,001] Trial 85 finished with value: 0.22398959248797704 and parameters: {'subsample': 0.6586093577814823, 'dropout_rate': 0.6202710354222771, 'n_estimators': 64, 'learning_rate': 0.032423376680946865}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22379912941339913
Fold 2 IBS: 0.2076089237823684
Fold 3 IBS: 0.23713925842702915
Fold 4 IBS: 0.22881038613184393
Fold 5 IBS: 0.21049278014865697
[I 2024-04-17 00:28:10,144] Trial 86 finished with value: 0.22157009558065952 and parameters: {'subsample': 0.6201193355845069, 'dropout_rate': 0.6727758765974591, 'n_estimators': 44, 'learning_rate': 0.027328093031043253}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.2227310338564416
Fold 2 IBS: 0.2064729770871324
Fold 3 IBS: 0.2387097684726459
Fold 4 IBS: 0.22860683668930395
Fold 5 IBS: 0.21031777945117824
[I 2024-04-17 00:28:13,430] Trial 87 finished with value: 0.22136767911134042 and parameters: {'subsample': 0.6137923043677187, 'dropout_rate': 0.6578608395909092, 'n_estimators': 46, 'learning_rate': 0.028228844589449218}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.3155249490793188
Fold 2 IBS: 0.2640250973483872
Fold 3 IBS: 0.35150740047903567
Fold 4 IBS: 0.29465926108505686
Fold 5 IBS: 0.29664399307292966
[I 2024-04-17 00:28:20,796] Trial 88 finished with value: 0.30447214021294566 and parameters: {'subsample': 0.5563453956745567, 'dropout_rate': 0.635509892730024, 'n_estimators': 227, 'learning_rate': 0.041042651352224235}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.21882804040039408
Fold 2 IBS: 0.2021257239375794
Fold 3 IBS: 0.2488925553100117
Fold 4 IBS: 0.2299136957400707
Fold 5 IBS: 0.21258997349908584
[I 2024-04-17 00:28:24,373] Trial 89 finished with value: 0.22246999777742835 and parameters: {'subsample': 0.7174443932842023, 'dropout_rate': 0.5932177411632202, 'n_estimators': 52, 'learning_rate': 0.03497836260796343}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22508455000645972
Fold 2 IBS: 0.2093506081973267
Fold 3 IBS: 0.23545916578671205
Fold 4 IBS: 0.2296620341827449
Fold 5 IBS: 0.210956430784988
[I 2024-04-17 00:28:27,386] Trial 90 finished with value: 0.22210255779164628 and parameters: {'subsample': 0.6885792506232654, 'dropout_rate': 0.5581493449312643, 'n_estimators': 36, 'learning_rate': 0.030149768812526692}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22350570792154217
Fold 2 IBS: 0.20710675637673007
Fold 3 IBS: 0.2377890064398362
Fold 4 IBS: 0.22866334718906384
Fold 5 IBS: 0.2103837931115841
[I 2024-04-17 00:28:30,558] Trial 91 finished with value: 0.2214897222077513 and parameters: {'subsample': 0.6252518157333167, 'dropout_rate': 0.6768103250965768, 'n_estimators': 45, 'learning_rate': 0.027532898640914117}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.2413589052700756
Fold 2 IBS: 0.22663761168748628
Fold 3 IBS: 0.22866863477272367
Fold 4 IBS: 0.23745690563602184
Fold 5 IBS: 0.2237298644365178
[I 2024-04-17 00:28:33,080] Trial 92 finished with value: 0.23157038436056504 and parameters: {'subsample': 0.6080039360699264, 'dropout_rate': 0.6989466017172343, 'n_estimators': 9, 'learning_rate': 0.024367473936345387}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22723131937890337
Fold 2 IBS: 0.2113640306874193
Fold 3 IBS: 0.23373445637933926
Fold 4 IBS: 0.22846157368512096
Fold 5 IBS: 0.21172162311351986
[I 2024-04-17 00:28:35,908] Trial 93 finished with value: 0.22250260064886057 and parameters: {'subsample': 0.5869718752556726, 'dropout_rate': 0.515780662916985, 'n_estimators': 26, 'learning_rate': 0.03696817721869061}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22073632727273912
Fold 2 IBS: 0.20388324986594278
Fold 3 IBS: 0.2433710156727303
Fold 4 IBS: 0.22887009757913981
Fold 5 IBS: 0.2108449986568362
[I 2024-04-17 00:28:39,251] Trial 94 finished with value: 0.22154113780947765 and parameters: {'subsample': 0.632517730042522, 'dropout_rate': 0.6542832786756084, 'n_estimators': 53, 'learning_rate': 0.02920357901679212}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22798047230982416
Fold 2 IBS: 0.21148788850219047
Fold 3 IBS: 0.23356421385825749
Fold 4 IBS: 0.23007244409198496
Fold 5 IBS: 0.2120154922159216
[I 2024-04-17 00:28:42,350] Trial 95 finished with value: 0.22302410219563576 and parameters: {'subsample': 0.6639608403709552, 'dropout_rate': 0.7566876692486192, 'n_estimators': 36, 'learning_rate': 0.026071370321176603}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.2179012967955125

Fold 2 IBS: 0.20078159037918683
Fold 3 IBS: 0.26110289322293423
Fold 4 IBS: 0.23412808505560326
Fold 5 IBS: 0.21973897733190245
[I 2024-04-17 00:28:45,871] Trial 96 finished with value: 0.22673056855702786 and parameters: {'subsample': 0.7054650333977128, 'dropout_rate': 0.6262161752789943, 'n_estimators': 61, 'learning_rate': 0.03998698220337849}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.21963880593620028
Fold 2 IBS: 0.20092268436766023
Fold 3 IBS: 0.2648475542088438
Fold 4 IBS: 0.2331055121729352
Fold 5 IBS: 0.22220093036998428
[I 2024-04-17 00:28:49,773] Trial 97 finished with value: 0.22814309741112476 and parameters: {'subsample': 0.531829760385333, 'dropout_rate': 0.6847533776104763, 'n_estimators': 79, 'learning_rate': 0.03223905987322316}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.2466414230044532
Fold 2 IBS: 0.23146700010719856
Fold 3 IBS: 0.2289119634694628
Fold 4 IBS: 0.24164291053866815
Fold 5 IBS: 0.2288108925224838
[I 2024-04-17 00:28:52,143] Trial 98 finished with value: 0.2354948379284533 and parameters: {'subsample': 0.5618605706633095, 'dropout_rate': 0.2002801186536965, 'n_estimators': 1, 'learning_rate': 0.022985459193691663}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.21844021664292554
Fold 2 IBS: 0.2014998540928507
Fold 3 IBS: 0.25108301890771456
Fold 4 IBS: 0.2341234904146111
Fold 5 IBS: 0.21405157380858064
[I 2024-04-17 00:28:56,481] Trial 99 finished with value: 0.2238396307733365 and parameters: {'subsample': 0.7589069007873921, 'dropout_rate': 0.8823172392191718, 'n_estimators': 97, 'learning_rate': 0.01992182696731529}. Best is trial 81 with value: 0.2208903160925389.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.2208903160925389], datetime_start=datetime.datetime(2024, 4, 17, 0, 27, 50, 63927), datetime_complete=datetime.datetime(2024, 4, 17, 0, 27, 53, 433635), params={'subsample': 0.5967091670188371, 'dropout_rate': 0.8767395889398294, 'n_estimators': 48, 'learning_rate': 0.030725485144314495}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=81, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.5967091670188371, 'dropout_rate': 0.8767395889398294, 'n_estimators': 48, 'learning_rate': 0.030725485144314495}


* Best Score for IBS:
 0.2208903160925389

In [104]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [105]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.67
train_ibs:  0.221

#### Test

In [106]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [107]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.9036811565813793,
                                              learning_rate=0.03163367036018912,
                                              n_estimators=1, random_state=123,
                                              subsample=0.2748398992643779)

C-index score: 0.521

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.8767395889398294,
                                              learning_rate=0.030725485144314495,
                                              n_estimators=48, random_state=123,
                                              subsample=0.5967091670188371)

IBS: 0.239

In [108]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [109]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.847   1.0
ExtraSurvivalTrees               0.842   2.0
GradientBoosting                 0.700   3.0
ComponentwiseGradientBoosting    0.670   4.0
CoxElastic                       0.641   5.0
CoxRidge                         0.635   6.0
CoxLasso                         0.583   7.0

In [110]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.208   1.0
Randomsurvivalforest           0.212   2.0
ComponentwiseGradientBoosting  0.221   3.0
GradientBoosting               0.230   4.0
CoxElastic                     0.234   5.0
CoxRidge                       0.236   6.0
CoxLasso                       0.353   7.0

In [111]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ExtraSurvivalTrees               0.567   1.0
Randomsurvivalforest             0.540   2.0
CoxRidge                         0.530   3.0
CoxElastic                       0.527   4.0
ComponentwiseGradientBoosting    0.521   5.0
GradientBoosting                 0.516   6.0
CoxLasso                         0.491   7.0

In [112]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
GradientBoosting               0.228   1.0
CoxRidge                       0.229   2.5
CoxElastic                     0.229   2.5
ExtraSurvivalTrees             0.235   4.0
ComponentwiseGradientBoosting  0.239   5.0
Randomsurvivalforest           0.262   6.0
CoxLasso                       0.457   7.0

In [113]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/dfs/yeojohnson/no_selection/'  # Folder path where you want to save the files

# List of corresponding file namess
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_dfs_yeojohnson_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [114]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-17