In [6]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import StandardScaler

In [7]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [8]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [9]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [10]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

## Test dataset: MAASTRO

In [11]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [12]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [13]:
# need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [14]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,DFS,DFS_event
0,1,55,0,0,1,0,0,1,1,1,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,8.83,1.0
3,4,61,1,0,0,0,1,1,0,1,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,19.73,1.0
4,6,70,0,0,1,0,0,1,1,1,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,13.27,1.0
95,111,63,0,0,0,0,1,0,0,1,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [15]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [16]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [17]:
# Set X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# Set y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [18]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [19]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 388)
y_train:  (139,)

In [20]:
# Change the name of a column 'DFS_event' in the clincial_test 
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [21]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 390)

## Feature Selection

### COX PLSR

In [22]:
# Choose features from the result of Cox PLSR in R
selected_features = [
"hpv_related",
"uicc8_III-IV",
"cavum_oris",
"shape_MajorAxisLength",
"female",
"shape_Elongation",
"shape_Sphericity"
]

In [23]:
X_plsr = X.loc[:, selected_features]
X_new = X_plsr.copy()

In [24]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, plsr]

# Standardization

In [25]:
# Copy the original X for later 
original_X = X.copy()

In [26]:
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Standardize X_new, the new data with the selected features only 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = StandardScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [27]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns

MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [28]:
X_new

,hpv_related,uicc8_III-IV,cavum_oris,shape_MajorAxisLength,female,shape_Elongation,shape_Sphericity
0,0.0,0.0,0,42.073251,1,0.600926,0.761164
1,0.0,0.0,0,24.613845,0,0.841579,0.697049
2,0.0,1.0,1,48.030294,0,0.772821,0.565792
3,0.0,0.0,0,25.589900,0,0.847727,0.684364
4,0.0,0.0,0,34.684750,0,0.831483,0.503142
...,...,...,...,...,...,...,...
134,1.0,0.0,0,33.069705,0,0.680294,0.742102
135,1.0,1.0,0,41.043692,0,0.758193,0.722918
136,1.0,0.0,0,36.618802,0,0.770113,0.652963
137,1.0,1.0,0,45.870392,0,0.628897,0.724255
138,1.0,1.0,0,30.363259,0,0.892637,0.722633

In [29]:
X_new_std

,hpv_related,uicc8_III-IV,cavum_oris,shape_MajorAxisLength,female,shape_Elongation,shape_Sphericity
0,0.0,0.0,0,-0.098422,1,-0.681983,1.075042
1,0.0,0.0,0,-1.209119,0,1.006304,0.242767
2,0.0,1.0,1,0.280542,0,0.523938,-1.461057
3,0.0,0.0,0,-1.147026,0,1.049432,0.078112
4,0.0,0.0,0,-0.568449,0,0.935477,-2.274305
...,...,...,...,...,...,...,...
134,1.0,0.0,0,-0.671191,0,-0.125182,0.827589
135,1.0,1.0,0,-0.163918,0,0.421312,0.578577
136,1.0,0.0,0,-0.445412,0,0.504939,-0.329498
137,1.0,1.0,0,0.143137,0,-0.485754,0.595927
138,1.0,1.0,0,-0.843364,0,1.364493,0.574872

In [30]:
MAASTRO_new

,hpv_related,uicc8_III-IV,cavum_oris,shape_MajorAxisLength,female,shape_Elongation,shape_Sphericity
0,1,0,0,50.002093,0,0.765178,0.668072
1,0,1,0,41.753334,0,0.776540,0.669961
2,0,1,0,44.375483,0,0.697164,0.624081
3,0,1,0,46.115989,1,0.574636,0.577624
4,1,0,0,54.394967,0,0.633419,0.630933
...,...,...,...,...,...,...,...
94,0,1,0,34.218615,1,0.882411,0.671754
95,0,1,0,51.046869,0,0.535802,0.632189
96,1,1,0,50.417953,0,0.716610,0.645548
97,1,0,0,44.901412,0,0.665145,0.727488
98,0,1,0,36.574294,0,0.616262,0.672838

In [31]:
MAASTRO_new_std

,hpv_related,uicc8_III-IV,cavum_oris,shape_MajorAxisLength,female,shape_Elongation,shape_Sphericity
0,1,0,0,0.405980,0,0.470316,-0.133381
1,0,1,0,-0.118774,0,0.550025,-0.108854
2,0,1,0,0.048037,0,-0.006831,-0.704414
3,0,1,0,0.158761,1,-0.866418,-1.307469
4,1,0,0,0.685437,0,-0.454030,-0.615466
...,...,...,...,...,...,...,...
94,0,1,0,-0.598102,1,1.292755,-0.085581
95,0,1,0,0.472444,0,-1.138850,-0.599161
96,1,1,0,0.432435,0,0.129595,-0.425762
97,1,0,0,0.081495,0,-0.231458,0.637891
98,0,1,0,-0.448243,0,-0.574392,-0.071514

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [32]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:17:45,871] A new study created in memory with name: no-name-6b8808d0-c28f-4ba8-927d-cd81bcc9d0ca
python(31267) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-16 20:17:49,649] A new study created in memory with name: no-name-45b4b325-7361-4e45-8653-a4aa8845b7e7

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7253218884120172
[I 2024-04-16 20:17:49,641] Trial 0 finished with value: 0.7095063198916233 and parameters: {}. Best is trial 0 with value: 0.7095063198916233.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7095063198916233], datetime_start=datetime.datetime(2024, 4, 16, 20, 17, 46, 3909), datetime_complete=datetime.datetime(2024, 4, 16, 20, 17, 49, 640700), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7095063198916233

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24547621902232983
Fold 2 IBS: 0.18646691736393076
Fold 3 IBS: 0.19716544700257893
Fold 4 IBS: 0.19436890362488465
Fold 5 IBS: 0.18028846636930945
[I 2024-04-16 20:17:49,893] Trial 0 finished with value: 0.20075319067660674 and parameters: {}. Best is trial 0 with value: 0.20075319067660674.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.20075319067660674], datetime_start=datetime.datetime(2024, 4, 16, 20, 17, 49, 682222), datetime_complete=datetime.datetime(2024, 4, 16, 20, 17, 49, 893241), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.20075319067660674

In [33]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [34]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.71
train_ibs:  0.201

#### Test

In [35]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [36]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.565
IBS score: 0.265

In [37]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [38]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [39]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:17:50,075] A new study created in memory with name: no-name-f7782328-b24a-4dc5-8554-aaf610609497

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.7286821705426356

[I 2024-04-16 20:17:50,258] A new study created in memory with name: no-name-5f576437-c7be-4862-8d7b-2bbe012a6ec8

Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 20:17:50,254] Trial 0 finished with value: 0.6553572675308125 and parameters: {}. Best is trial 0 with value: 0.6553572675308125.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6553572675308125], datetime_start=datetime.datetime(2024, 4, 16, 20, 17, 50, 111454), datetime_complete=datetime.datetime(2024, 4, 16, 20, 17, 50, 254369), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6553572675308125

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709428728842
Fold 2 IBS: 0.23203987166610096
Fold 3 IBS: 0.22898186706001508
Fold 4 IBS: 0.2419747601009159
Fold 5 IBS: 0.22939558449397743
[I 2024-04-16 20:17:50,448] Trial 0 finished with value: 0.23592783552165955 and parameters: {}. Best is trial 0 with value: 0.23592783552165955.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592783552165955], datetime_start=datetime.datetime(2024, 4, 16, 20, 17, 50, 294589), datetime_complete=datetime.datetime(2024, 4, 16, 20, 17, 50, 448409), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592783552165955

In [40]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [41]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.655
train_ibs:  0.236

#### Test

In [42]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [43]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.537

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [44]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [45]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:17:50,619] A new study created in memory with name: no-name-d2a3f5cb-508c-493e-b2e6-95b138507ff9

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876

[I 2024-04-16 20:17:50,902] A new study created in memory with name: no-name-1639a0e6-a8bf-4129-acd2-ad0aab0e2fbf

Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:50,896] Trial 0 finished with value: 0.7094195636674461 and parameters: {}. Best is trial 0 with value: 0.7094195636674461.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7094195636674461], datetime_start=datetime.datetime(2024, 4, 16, 20, 17, 50, 662905), datetime_complete=datetime.datetime(2024, 4, 16, 20, 17, 50, 896345), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7094195636674461

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24339534410179192
Fold 2 IBS: 0.185182554310044
Fold 3 IBS: 0.19735806201590553
Fold 4 IBS: 0.19425154567068226
Fold 5 IBS: 0.17858505650283987
[I 2024-04-16 20:17:51,197] Trial 0 finished with value: 0.19975451252025272 and parameters: {}. Best is trial 0 with value: 0.19975451252025272.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.19975451252025272], datetime_start=datetime.datetime(2024, 4, 16, 20, 17, 50, 941477), datetime_complete=datetime.datetime(2024, 4, 16, 20, 17, 51, 197070), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.19975451252025272

In [46]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [47]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.709
train_ibs:  0.2

#### Test

In [48]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [49]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.566

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.264

In [50]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [51]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:17:51,437] A new study created in memory with name: no-name-654568bd-1c78-4798-9db9-ad7fec03d660

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:51,701] Trial 0 finished with value: 0.7094195636674461 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7094195636674461.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:51,945] Trial 1 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.7094195636674461.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:52,200] Trial 2 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:52,436] Trial 3 finished with value: 0.7094195636674461 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:52,660] Trial 4 finished with value: 0.7094195636674461 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:52,878] Trial 5 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:53,132] Trial 6 finished with value: 0.7094195636674461 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:53,361] Trial 7 finished with value: 0.7094195636674461 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:53,611] Trial 8 finished with value: 0.7094195636674461 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:53,911] Trial 9 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:54,187] Trial 10 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 20:17:54,298] Trial 11 finished with value: 0.6568788875534735 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:54,928] Trial 12 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:55,388] Trial 13 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.18977351772466045}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:55,754] Trial 14 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.187901372232152}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:56,075] Trial 15 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.187063776657101}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 20:17:56,191] Trial 16 finished with value: 0.658581015213048 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:56,518] Trial 17 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.32086883765249574}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:56,814] Trial 18 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.11915385898218006}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:57,142] Trial 19 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.2771695014618133}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:57,447] Trial 20 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.5914245950308872}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:57,744] Trial 21 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.09692756484188994}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:58,064] Trial 22 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.1016291706752447}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:58,398] Trial 23 finished with value: 0.6745801977269528 and parameters: {'l1_ratio': 0.07121140617310368}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012

Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:58,632] Trial 24 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.2193939366669308}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:58,889] Trial 25 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.36991167247338663}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 20:17:59,215] Trial 26 finished with value: 0.708615445649517 and parameters: {'l1_ratio': 0.13147141129458395}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:59,444] Trial 27 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.2476371906175866}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 20:17:59,591] Trial 28 finished with value: 0.6576609627777922 and parameters: {'l1_ratio': 0.03946903368281641}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:17:59,793] Trial 29 finished with value: 0.7094195636674461 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:00,024] Trial 30 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.15797333971744226}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:00,287] Trial 31 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.21877470629337237}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:00,699] Trial 32 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.30578552234538414}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:01,026] Trial 33 finished with value: 0.6639338098942531 and parameters: {'l1_ratio': 0.06734364197760204}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:01,390] Trial 34 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.16331837288086035}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:01,666] Trial 35 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.3349958381129322}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:01,953] Trial 36 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.4465889630148597}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:02,244] Trial 37 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.2569651106668939}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:02,559] Trial 38 finished with value: 0.7094195636674461 and parameters: {'l1_ratio': 0.5638551523074651}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 20:18:02,730] Trial 39 finished with value: 0.6576609627777922 and parameters: {'l1_ratio': 0.04032884745061077}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:02,969] Trial 40 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.13565981873382177}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:03,198] Trial 41 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.2202828602261332}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:03,606] Trial 42 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.18036444641568772}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:04,057] Trial 43 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.19326394378948358}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:04,685] Trial 44 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.36648236422479696}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 20:18:04,774] Trial 45 finished with value: 0.6568788875534735 and parameters: {'l1_ratio': 0.007238804895064288}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:05,394] Trial 46 finished with value: 0.6745801977269528 and parameters: {'l1_ratio': 0.07361465903605298}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:05,642] Trial 47 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.5063994947206192}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212

Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:05,877] Trial 48 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.7768768486379835}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:06,135] Trial 49 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.2758853961660157}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:06,356] Trial 50 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.12640640297302158}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:06,738] Trial 51 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.1711793793118373}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:07,031] Trial 52 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.0892823815882977}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:07,323] Trial 53 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.23886269761807474}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:07,627] Trial 54 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.18507681391491007}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:07,901] Trial 55 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.2956623629125545}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:08,110] Trial 56 finished with value: 0.6647090036927027 and parameters: {'l1_ratio': 0.05025221403774699}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:08,342] Trial 57 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.12298559808628556}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:08,535] Trial 58 finished with value: 0.7094195636674461 and parameters: {'l1_ratio': 0.655048728516688}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:08,752] Trial 59 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.4258059048102031}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:08,964] Trial 60 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.14449873047424402}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:09,206] Trial 61 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.10355254335682418}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:09,418] Trial 62 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.19492137524540426}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 20:18:09,509] Trial 63 finished with value: 0.6561036937550239 and parameters: {'l1_ratio': 0.026855707230091203}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:09,731] Trial 64 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.09981777849141175}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:09,930] Trial 65 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.21957930641530757}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:10,121] Trial 66 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.26303129082720844}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:10,288] Trial 67 finished with value: 0.6631733536204889 and parameters: {'l1_ratio': 0.05875238207258411}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:10,498] Trial 68 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.14777275930847628}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:10,693] Trial 69 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.3471066882300928}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:10,906] Trial 70 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.1076225216519491}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:11,094] Trial 71 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.3150544087339543}. Best is trial 2 with value: 0.7094738147482293.

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:11,291] Trial 72 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.2293378329848922}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:11,469] Trial 73 finished with value: 0.7094195636674461 and parameters: {'l1_ratio': 0.992464045531057}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:11,651] Trial 74 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.2848197319636719}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:11,960] Trial 75 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.19064780833161452}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:12,347] Trial 76 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.16003042699241884}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:12,545] Trial 77 finished with value: 0.6745801977269528 and parameters: {'l1_ratio': 0.07532694548663663}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 20:18:12,634] Trial 78 finished with value: 0.658581015213048 and parameters: {'l1_ratio': 0.0008715126933852568}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:12,884] Trial 79 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.24905305780604126}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:13,132] Trial 80 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.2056095984358056}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:13,374] Trial 81 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.12286530446146894}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:13,649] Trial 82 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.1614324445694402}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 20:18:13,729] Trial 83 finished with value: 0.6568641500287882 and parameters: {'l1_ratio': 0.034091095883118816}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:14,135] Trial 84 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.08547642479537962}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:14,512] Trial 85 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.13257827709423287}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:14,836] Trial 86 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.17930413949206525}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:15,140] Trial 87 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.10834897155248714}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:15,392] Trial 88 finished with value: 0.7086227509184421 and parameters: {'l1_ratio': 0.3862088249834403}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:15,743] Trial 89 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.21330899179957263}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 20:18:15,875] Trial 90 finished with value: 0.6561036937550239 and parameters: {'l1_ratio': 0.027040368081291698}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:16,103] Trial 91 finished with value: 0.6745801977269528 and parameters: {'l1_ratio': 0.07557004568325106}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:16,230] Trial 92 finished with value: 0.6647090036927027 and parameters: {'l1_ratio': 0.05050866931223307}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:16,475] Trial 93 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.14534310475854614}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:16,688] Trial 94 finished with value: 0.7094195636674461 and parameters: {'l1_ratio': 0.9094578869039874}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:16,876] Trial 95 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.27227096650199595}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876

Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:17,083] Trial 96 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.11172016921401098}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:17,274] Trial 97 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.2367441530189508}. Best is trial 2 with value: 0.7094738147482293.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:17,469] Trial 98 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.17104670599160715}. Best is trial 2 with value: 0.7094738147482293.

[I 2024-04-16 20:18:17,728] A new study created in memory with name: no-name-46c33af9-7624-47c0-99f5-5b6e483f0325

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:18:17,718] Trial 99 finished with value: 0.7094738147482293 and parameters: {'l1_ratio': 0.08331058432985729}. Best is trial 2 with value: 0.7094738147482293.


* Best trial for C-index:
 FrozenTrial(number=2, state=TrialState.COMPLETE, values=[0.7094738147482293], datetime_start=datetime.datetime(2024, 4, 16, 20, 17, 51, 948462), datetime_complete=datetime.datetime(2024, 4, 16, 20, 17, 52, 199905), params={'l1_ratio': 0.22692876841884668}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=2, value=None)


* Best Score for C-index:
 0.7094738147482293

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24353047233571218
Fold 2 IBS: 0.18505548303484637
Fold 3 IBS: 0.19730689652689593
Fold 4 IBS: 0.19422737036147178
Fold 5 IBS: 0.17851015969988163
[I 2024-04-16 20:18:18,024] Trial 0 finished with value: 0.19972607639176157 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.19972607639176157.
Fold 1 IBS: 0.24360127705755819
Fold 2 IBS: 0.185007449755265
Fold 3 IBS: 0.19721867191474393
Fold 4 IBS: 0.19415153821706493
Fold 5 IBS: 0.17850233659697254
[I 2024-04-16 20:18:18,298] Trial 1 finished with value: 0.19969625470832092 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.19969625470832092.
Fold 1 IBS: 0.24351257107264307
Fold 2 IBS: 0.18501447211139116
Fold 3 IBS: 0.19712891614318392
Fold 4 IBS: 0.1941210385253576
Fold 5 IBS: 0.17852330815931183
[I 2024-04-16 20:18:18,555] Trial 2 finished with value: 0.1996600612023775 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.1996600612023775.
Fold 1 IBS: 0.24353210606265968
Fold 2 IBS: 0.18511755000751726
Fold 3 IBS: 0.19728256250867132
Fold 4 IBS: 0.1942116156884127
Fold 5 IBS: 0.17849440901325325
[I 2024-04-16 20:18:18,870] Trial 3 finished with value: 0.19972764865610287 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.1996600612023775.
Fold 1 IBS: 0.2435521282475526
Fold 2 IBS: 0.18508023434219373
Fold 3 IBS: 0.1973123741040529
Fold 4 IBS: 0.19423097810199827
Fold 5 IBS: 0.17850407083979247
[I 2024-04-16 20:18:19,217] Trial 4 finished with value: 0.199735957127118 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.1996600612023775.
Fold 1 IBS: 0.2434841255302834
Fold 2 IBS: 0.1850112654891598
Fold 3 IBS: 0.19727068394587188
Fold 4 IBS: 0.19418752116544755
Fold 5 IBS: 0.1784571364870793
[I 2024-04-16 20:18:19,453] Trial 5 finished with value: 0.1996821465235684 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.1996600612023775.
Fold 1 IBS: 0.2433843154616134
Fold 2 IBS: 0.1851706131993703
Fold 3 IBS: 0.1973558025131924
Fold 4 IBS: 0.19424991051687043
Fold 5 IBS: 0.1785184802983434
[I 2024-04-16 20:18:19,672] Trial 6 finished with value: 0.199735824397878 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.1996600612023775.
Fold 1 IBS: 0.24351899717857992
Fold 2 IBS: 0.18504236824215162
Fold 3 IBS: 0.19732190111792214
Fold 4 IBS: 0.19422544831123748
Fold 5 IBS: 0.17851340226025683
[I 2024-04-16 20:18:19,926] Trial 7 finished with value: 0.1997244234220296 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.1996600612023775.
Fold 1 IBS: 0.24359048800317526
Fold 2 IBS: 0.18500069322790905
Fold 3 IBS: 0.19727472875169286
Fold 4 IBS: 0.1941920017454862
Fold 5 IBS: 0.1784640247105945
[I 2024-04-16 20:18:20,139] Trial 8 finished with value: 0.19970438728777157 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.1996600612023775.
Fold 1 IBS: 0.24358201619270317
Fold 2 IBS: 0.18506586649920503
Fold 3 IBS: 0.19725274984321817
Fold 4 IBS: 0.19417466697569957
Fold 5 IBS: 0.17847967531073858
[I 2024-04-16 20:18:20,347] Trial 9 finished with value: 0.19971099496431294 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.1996600612023775.
Fold 1 IBS: 0.24365815949986952
Fold 2 IBS: 0.18498362029203877
Fold 3 IBS: 0.1967870679831396
Fold 4 IBS: 0.19405117373904532
Fold 5 IBS: 0.17859533534727373
[I 2024-04-16 20:18:20,577] Trial 10 finished with value: 0.19961507137227338 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.19961507137227338.
Fold 1 IBS: 0.2465209494477647
Fold 2 IBS: 0.23051526885650084
Fold 3 IBS: 0.22888129840003638
Fold 4 IBS: 0.2406368338651429
Fold 5 IBS: 0.22838578057464493
[I 2024-04-16 20:18:20,666] Trial 11 finished with value: 0.23498802622881793 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.19961507137227338.
Fold 1 IBS: 0.24365677916877088
Fold 2 IBS: 0.1849823541088991
Fold 3 IBS: 0.19678649155141847
Fold 4 IBS: 0.19405083700955647
Fold 5 IBS: 0.1785957155242131
[I 2024-04-16 20:18:20,895] Trial 12 finished with value: 0.1996144354725716 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 12 with value: 0.1996144354725716.
Fold 1 IBS: 0.24705210330097865
Fold 2 IBS: 0.2316317456738536
Fold 3 IBS: 0.22895090100289822
Fold 4 IBS: 0.24161522496630328
Fold 5 IBS: 0.22912468005824393
[I 2024-04-16 20:18:20,993] Trial 13 finished with value: 0.2356749310004555 and parameters: {'l1_ratio': 0.0031985064812224406}. Best is trial 12 with value: 0.1996144354725716.
Fold 1 IBS: 0.24359920858190917
Fold 2 IBS: 0.18500255366059223
Fold 3 IBS: 0.19694016394280278
Fold 4 IBS: 0.1940997488263979
Fold 5 IBS: 0.17856163478351966
[I 2024-04-16 20:18:21,205] Trial 14 finished with value: 0.19964066195904434 and parameters: {'l1_ratio': 0.14354731809284052}. Best is trial 12 with value: 0.1996144354725716.
Fold 1 IBS: 0.24361562523281372
Fold 2 IBS: 0.18501777345812806
Fold 3 IBS: 0.19694725305920557
Fold 4 IBS: 0.1941033058983621
Fold 5 IBS: 0.17855705565377247
[I 2024-04-16 20:18:21,425] Trial 15 finished with value: 0.19964820266045638 and parameters: {'l1_ratio': 0.14547377630010583}. Best is trial 12 with value: 0.1996144354725716.
Fold 1 IBS: 0.2435179046646918
Fold 2 IBS: 0.18492707232396352
Fold 3 IBS: 0.19690401288760717
Fold 4 IBS: 0.19408191597191285
Fold 5 IBS: 0.17858452964442875
[I 2024-04-16 20:18:21,648] Trial 16 finished with value: 0.19960308709852081 and parameters: {'l1_ratio': 0.13463318817607284}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.24359829645667194
Fold 2 IBS: 0.18500442009060572
Fold 3 IBS: 0.19721782107370228
Fold 4 IBS: 0.1941509315397553
Fold 5 IBS: 0.17850325887411597
[I 2024-04-16 20:18:21,857] Trial 17 finished with value: 0.19969494560697026 and parameters: {'l1_ratio': 0.2853691373958437}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.24360655146559146
Fold 2 IBS: 0.18495112427476965
Fold 3 IBS: 0.1970982379556207
Fold 4 IBS: 0.19412972122368768
Fold 5 IBS: 0.17854259736095396
[I 2024-04-16 20:18:22,079] Trial 18 finished with value: 0.1996656464561247 and parameters: {'l1_ratio': 0.21416053383156064}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.24357452964438525
Fold 2 IBS: 0.18501683829273236
Fold 3 IBS: 0.19723018470923634
Fold 4 IBS: 0.19415910778620907
Fold 5 IBS: 0.17848613158854174
[I 2024-04-16 20:18:22,285] Trial 19 finished with value: 0.19969335840422095 and parameters: {'l1_ratio': 0.32722716564021426}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.2435420621938388
Fold 2 IBS: 0.1851441457810527
Fold 3 IBS: 0.1973507598911095
Fold 4 IBS: 0.19424626510541865
Fold 5 IBS: 0.17852469406772084
[I 2024-04-16 20:18:22,487] Trial 20 finished with value: 0.19976158540782812 and parameters: {'l1_ratio': 0.9405325330891504}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.24359843313915983
Fold 2 IBS: 0.1849540718599613
Fold 3 IBS: 0.19682131441408435
Fold 4 IBS: 0.19407808500783016
Fold 5 IBS: 0.17859478687462743
[I 2024-04-16 20:18:22,705] Trial 21 finished with value: 0.19960933825913263 and parameters: {'l1_ratio': 0.10039375875562537}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.2435549139594712
Fold 2 IBS: 0.18503789146334684
Fold 3 IBS: 0.19680279829335545
Fold 4 IBS: 0.1940683699208228
Fold 5 IBS: 0.17857447057326767
[I 2024-04-16 20:18:22,923] Trial 22 finished with value: 0.1996076888420528 and parameters: {'l1_ratio': 0.09719212464432796}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.24363840681019416
Fold 2 IBS: 0.18502021080927772
Fold 3 IBS: 0.19688859620080063
Fold 4 IBS: 0.19407406615177775
Fold 5 IBS: 0.17856282644249466
[I 2024-04-16 20:18:23,131] Trial 23 finished with value: 0.19963682128290897 and parameters: {'l1_ratio': 0.13106172654563228}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.24362294255200387
Fold 2 IBS: 0.18496763199301483
Fold 3 IBS: 0.1971062424630858
Fold 4 IBS: 0.19413314670148757
Fold 5 IBS: 0.1785375493709759
[I 2024-04-16 20:18:23,328] Trial 24 finished with value: 0.19967350261611358 and parameters: {'l1_ratio': 0.21736087814603194}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.243574809405095
Fold 2 IBS: 0.1850131168242899
Fold 3 IBS: 0.2287541906279446
Fold 4 IBS: 0.23606398685001703

Fold 5 IBS: 0.178598053564367
[I 2024-04-16 20:18:23,503] Trial 25 finished with value: 0.21440083145434272 and parameters: {'l1_ratio': 0.06349940013770836}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.24351366760725107
Fold 2 IBS: 0.18496422300962823
Fold 3 IBS: 0.19700342856991873
Fold 4 IBS: 0.1940991769035908
Fold 5 IBS: 0.17855757385038704
[I 2024-04-16 20:18:23,698] Trial 26 finished with value: 0.19962761398815518 and parameters: {'l1_ratio': 0.17279016655324594}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.24357562966361976
Fold 2 IBS: 0.18504134792632615
Fold 3 IBS: 0.1972939882535071
Fold 4 IBS: 0.1942054655303824
Fold 5 IBS: 0.17848191293841448
[I 2024-04-16 20:18:23,888] Trial 27 finished with value: 0.19971966886245 and parameters: {'l1_ratio': 0.58416616744615}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.24349097130911254
Fold 2 IBS: 0.18497216691709234
Fold 3 IBS: 0.19725200652728428
Fold 4 IBS: 0.19417470404345746
Fold 5 IBS: 0.178485108323071
[I 2024-04-16 20:18:24,098] Trial 28 finished with value: 0.19967499142400352 and parameters: {'l1_ratio': 0.355721226193779}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.24356721718953805
Fold 2 IBS: 0.18497282129677142
Fold 3 IBS: 0.1972090261261611
Fold 4 IBS: 0.19414457545235056
Fold 5 IBS: 0.17851290886944368
[I 2024-04-16 20:18:24,303] Trial 29 finished with value: 0.19968130978685297 and parameters: {'l1_ratio': 0.2768522384590832}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.2436546873316427
Fold 2 IBS: 0.22600372196195645
Fold 3 IBS: 0.22877204145032284
Fold 4 IBS: 0.23677124909879532
Fold 5 IBS: 0.17863780361854226
[I 2024-04-16 20:18:24,460] Trial 30 finished with value: 0.2227679006922519 and parameters: {'l1_ratio': 0.05440499076023005}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.24362935057316035
Fold 2 IBS: 0.18498168881104324
Fold 3 IBS: 0.19683441903667281
Fold 4 IBS: 0.19408492520506423
Fold 5 IBS: 0.1785861902319158
[I 2024-04-16 20:18:24,682] Trial 31 finished with value: 0.1996233147715713 and parameters: {'l1_ratio': 0.1027818981982221}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.2436073651441948
Fold 2 IBS: 0.18505167347397955
Fold 3 IBS: 0.19703297207420795
Fold 4 IBS: 0.19411931640063784
Fold 5 IBS: 0.1785602324775625
[I 2024-04-16 20:18:24,887] Trial 32 finished with value: 0.1996743119141165 and parameters: {'l1_ratio': 0.18693211991516345}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.24689893523646772
Fold 2 IBS: 0.23131069723767542
Fold 3 IBS: 0.22892891489258985
Fold 4 IBS: 0.24133300384871936
Fold 5 IBS: 0.22891177149092698
[I 2024-04-16 20:18:24,973] Trial 33 finished with value: 0.23547666454127586 and parameters: {'l1_ratio': 0.005758632231171887}. Best is trial 16 with value: 0.19960308709852081.
Fold 1 IBS: 0.24358716182724272
Fold 2 IBS: 0.18493082554082443
Fold 3 IBS: 0.19678473479832131
Fold 4 IBS: 0.19406958900417273
Fold 5 IBS: 0.1785745065445695
[I 2024-04-16 20:18:25,180] Trial 34 finished with value: 0.19958936354302614 and parameters: {'l1_ratio': 0.08888945657798078}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24360122111552326
Fold 2 IBS: 0.18497478462114603
Fold 3 IBS: 0.19716923609565082
Fold 4 IBS: 0.19413959299348837
Fold 5 IBS: 0.1785243965385384
[I 2024-04-16 20:18:25,416] Trial 35 finished with value: 0.1996818462728694 and parameters: {'l1_ratio': 0.24596265983906013}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24348553573149687
Fold 2 IBS: 0.18507872247761822
Fold 3 IBS: 0.197338105112355
Fold 4 IBS: 0.194237128732929
Fold 5 IBS: 0.1785402519425343
[I 2024-04-16 20:18:25,607] Trial 36 finished with value: 0.19973594879938666 and parameters: {'l1_ratio': 0.8532956215563254}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24364225062549347
Fold 2 IBS: 0.18493770625621428
Fold 3 IBS: 0.19699081344180538
Fold 4 IBS: 0.1940929849448242
Fold 5 IBS: 0.17856566424670903
[I 2024-04-16 20:18:25,806] Trial 37 finished with value: 0.19964588390300927 and parameters: {'l1_ratio': 0.16887660404179283}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24366276708278953
Fold 2 IBS: 0.22649515949486257
Fold 3 IBS: 0.2287839636773971
Fold 4 IBS: 0.23718498623032408
Fold 5 IBS: 0.17865107005621544
[I 2024-04-16 20:18:25,945] Trial 38 finished with value: 0.22295558930831771 and parameters: {'l1_ratio': 0.04931502618585465}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24354070973831168
Fold 2 IBS: 0.18506992681457995
Fold 3 IBS: 0.1972634071711475
Fold 4 IBS: 0.19418182833377517
Fold 5 IBS: 0.17847945680861976
[I 2024-04-16 20:18:26,168] Trial 39 finished with value: 0.1997070657732868 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24345543440509104
Fold 2 IBS: 0.18506299515374547
Fold 3 IBS: 0.19724282034480967
Fold 4 IBS: 0.1941681365784101
Fold 5 IBS: 0.17849640533107936
[I 2024-04-16 20:18:26,358] Trial 40 finished with value: 0.19968515836262712 and parameters: {'l1_ratio': 0.3431139020763936}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24363271415702384
Fold 2 IBS: 0.18499907861099402
Fold 3 IBS: 0.19687220543117964
Fold 4 IBS: 0.19406480975782778
Fold 5 IBS: 0.17857535048637732
[I 2024-04-16 20:18:26,570] Trial 41 finished with value: 0.19962883168868054 and parameters: {'l1_ratio': 0.11577418005988488}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24363658798590926
Fold 2 IBS: 0.18496382706276715
Fold 3 IBS: 0.19677675880539208
Fold 4 IBS: 0.19407518062632287
Fold 5 IBS: 0.17858829538562018
[I 2024-04-16 20:18:26,781] Trial 42 finished with value: 0.19960812997320232 and parameters: {'l1_ratio': 0.0824848724549698}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24357826048688408
Fold 2 IBS: 0.18495155377485828
Fold 3 IBS: 0.19715779759599586
Fold 4 IBS: 0.19413483001763226
Fold 5 IBS: 0.17853150976766946
[I 2024-04-16 20:18:26,975] Trial 43 finished with value: 0.199670790328608 and parameters: {'l1_ratio': 0.24076589602781384}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24359576144165102
Fold 2 IBS: 0.2271772408187653
Fold 3 IBS: 0.22880227192025268
Fold 4 IBS: 0.237762356808952
Fold 5 IBS: 0.22619996272436285
[I 2024-04-16 20:18:27,091] Trial 44 finished with value: 0.23270751874279677 and parameters: {'l1_ratio': 0.04247396437940232}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.2435054564136891
Fold 2 IBS: 0.1850896718072718
Fold 3 IBS: 0.19729577168614454
Fold 4 IBS: 0.1942069947870263
Fold 5 IBS: 0.17850213787255864
[I 2024-04-16 20:18:27,278] Trial 45 finished with value: 0.19972000651333807 and parameters: {'l1_ratio': 0.532905188903257}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24353406420679827
Fold 2 IBS: 0.1850199892308824
Fold 3 IBS: 0.19679389797119903
Fold 4 IBS: 0.19406367935221144
Fold 5 IBS: 0.17857980834857495
[I 2024-04-16 20:18:27,491] Trial 46 finished with value: 0.1995982878219332 and parameters: {'l1_ratio': 0.09572051950897736}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24353058554446208
Fold 2 IBS: 0.1849800303944839
Fold 3 IBS: 0.1970109381982662
Fold 4 IBS: 0.1941028491813571
Fold 5 IBS: 0.178552769267925
[I 2024-04-16 20:18:27,688] Trial 47 finished with value: 0.19963543451729887 and parameters: {'l1_ratio': 0.17520136554399265}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24351555404874353
Fold 2 IBS: 0.18503843321983426
Fold 3 IBS: 0.19732109463373315
Fold 4 IBS: 0.1942248701963153
Fold 5 IBS: 0.17851437737836648
[I 2024-04-16 20:18:27,872] Trial 48 finished with value: 0.19972286589539853 and parameters: {'l1_ratio': 0.6814395334066481}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24355991396799062
Fold 2 IBS: 0.1849485476385254
Fold 3 IBS: 0.19687904558042585
Fold 4 IBS: 0.19408329421062492
Fold 5 IBS: 0.178584741850696
[I 2024-04-16 20:18:28,083] Trial 49 finished with value: 0.1996111086496526 and parameters: {'l1_ratio': 0.1232065672476511}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24520328385684018
Fold 2 IBS: 0.22770618905450113
Fold 3 IBS: 0.22881024487041626
Fold 4 IBS: 0.23821253720490665
Fold 5 IBS: 0.22654390392000484
[I 2024-04-16 20:18:28,166] Trial 50 finished with value: 0.2332952317813338 and parameters: {'l1_ratio': 0.03733824046318075}. Best is trial 34 with value: 0.19958936354302614.

Fold 1 IBS: 0.24366600858696846
Fold 2 IBS: 0.1849908193564825
Fold 3 IBS: 0.19675372997116544
Fold 4 IBS: 0.19405308641009722
Fold 5 IBS: 0.17859317541288244
[I 2024-04-16 20:18:28,378] Trial 51 finished with value: 0.19961136394751922 and parameters: {'l1_ratio': 0.08432532131440844}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24355149972756562
Fold 2 IBS: 0.18503496094507124
Fold 3 IBS: 0.19680134213895506
Fold 4 IBS: 0.1940676034270465
Fold 5 IBS: 0.1785753431827489
[I 2024-04-16 20:18:28,598] Trial 52 finished with value: 0.19960614988427744 and parameters: {'l1_ratio': 0.09694846336288854}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24711925423645356
Fold 2 IBS: 0.23177243954176463
Fold 3 IBS: 0.22896133689875584
Fold 4 IBS: 0.24173903126704263
Fold 5 IBS: 0.2292179967456121
[I 2024-04-16 20:18:28,686] Trial 53 finished with value: 0.23576201173792577 and parameters: {'l1_ratio': 0.0020896128570487976}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24363524715113374
Fold 2 IBS: 0.18503494075001642
Fold 3 IBS: 0.19693461801523485
Fold 4 IBS: 0.1940819327679283
Fold 5 IBS: 0.17858242540932232
[I 2024-04-16 20:18:28,884] Trial 54 finished with value: 0.19965383281872712 and parameters: {'l1_ratio': 0.1478369065382741}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24354459283240337
Fold 2 IBS: 0.18501740187816587
Fold 3 IBS: 0.19707679110002055
Fold 4 IBS: 0.19411663705567317
Fold 5 IBS: 0.1785324027178681
[I 2024-04-16 20:18:29,093] Trial 55 finished with value: 0.1996575651168262 and parameters: {'l1_ratio': 0.20278745312349356}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24361918411615277
Fold 2 IBS: 0.18494784923149923
Fold 3 IBS: 0.22873109313727535
Fold 4 IBS: 0.1940712996216362
Fold 5 IBS: 0.17858045108259893
[I 2024-04-16 20:18:29,304] Trial 56 finished with value: 0.20598997543783248 and parameters: {'l1_ratio': 0.08142880856715379}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24356986060369618
Fold 2 IBS: 0.18497550945727564
Fold 3 IBS: 0.19720975046531997
Fold 4 IBS: 0.19414511820650884
Fold 5 IBS: 0.17851208573678273
[I 2024-04-16 20:18:29,502] Trial 57 finished with value: 0.19968246489391667 and parameters: {'l1_ratio': 0.2775587807643247}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24361133671074456
Fold 2 IBS: 0.1850137982841045
Fold 3 IBS: 0.1969454022826334
Fold 4 IBS: 0.19410237809512734
Fold 5 IBS: 0.17855825044675316
[I 2024-04-16 20:18:29,710] Trial 58 finished with value: 0.1996462331638726 and parameters: {'l1_ratio': 0.1449661508234822}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24355101248986064
Fold 2 IBS: 0.22730582261810492
Fold 3 IBS: 0.2288059428656043
Fold 4 IBS: 0.23787159794463952
Fold 5 IBS: 0.2262834834368775
[I 2024-04-16 20:18:29,830] Trial 59 finished with value: 0.23276357187101734 and parameters: {'l1_ratio': 0.04121224820067035}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.2435158345363197
Fold 2 IBS: 0.1849568067236919
Fold 3 IBS: 0.1972394217624516
Fold 4 IBS: 0.1941471980186775
Fold 5 IBS: 0.17850450941582782
[I 2024-04-16 20:18:30,027] Trial 60 finished with value: 0.1996727540913937 and parameters: {'l1_ratio': 0.3084737217475788}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24365692309115777
Fold 2 IBS: 0.18500707051510365
Fold 3 IBS: 0.19681584132739363
Fold 4 IBS: 0.194063442131959
Fold 5 IBS: 0.17857856641558228
[I 2024-04-16 20:18:30,246] Trial 61 finished with value: 0.19962436869623926 and parameters: {'l1_ratio': 0.1049968016057018}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24362438805976286
Fold 2 IBS: 0.1849642454028253
Fold 3 IBS: 0.1968004466952566
Fold 4 IBS: 0.1940778900543805
Fold 5 IBS: 0.17859653795771258
[I 2024-04-16 20:18:30,469] Trial 62 finished with value: 0.19961270163398756 and parameters: {'l1_ratio': 0.09138372381958294}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24363933648264577
Fold 2 IBS: 0.18503872882889122
Fold 3 IBS: 0.19693654662976826
Fold 4 IBS: 0.19408290095969424
Fold 5 IBS: 0.1785811754598706
[I 2024-04-16 20:18:30,680] Trial 63 finished with value: 0.199655737672174 and parameters: {'l1_ratio': 0.1483379421267567}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24361149782204009
Fold 2 IBS: 0.18493031171489793
Fold 3 IBS: 0.22874056675242468
Fold 4 IBS: 0.19406460846202567
Fold 5 IBS: 0.17858822922925618
[I 2024-04-16 20:18:30,877] Trial 64 finished with value: 0.20598704279612892 and parameters: {'l1_ratio': 0.07257906491804186}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24356873226363313
Fold 2 IBS: 0.18494191115657485
Fold 3 IBS: 0.19715305471147135
Fold 4 IBS: 0.19413284473212977
Fold 5 IBS: 0.1785344711977242
[I 2024-04-16 20:18:31,080] Trial 65 finished with value: 0.19966620281230668 and parameters: {'l1_ratio': 0.23866663351653747}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24358616633616434
Fold 2 IBS: 0.1850701346435988
Fold 3 IBS: 0.19725388734701363
Fold 4 IBS: 0.1941754818775704
Fold 5 IBS: 0.17847825024254088
[I 2024-04-16 20:18:31,280] Trial 66 finished with value: 0.19971278408937762 and parameters: {'l1_ratio': 0.39400165260425674}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24355683594672123
Fold 2 IBS: 0.18494569652702492
Fold 3 IBS: 0.19687771762581208
Fold 4 IBS: 0.19408261350441622
Fold 5 IBS: 0.17858560802923215
[I 2024-04-16 20:18:31,493] Trial 67 finished with value: 0.19960969432664133 and parameters: {'l1_ratio': 0.12291539195031345}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24351580189164182
Fold 2 IBS: 0.18499042157489182
Fold 3 IBS: 0.19706388015592674
Fold 4 IBS: 0.19411048369839104
Fold 5 IBS: 0.17854057113009283
[I 2024-04-16 20:18:31,702] Trial 68 finished with value: 0.19964423169018883 and parameters: {'l1_ratio': 0.19786127936280612}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24364305313813456
Fold 2 IBS: 0.22703485588284744
Fold 3 IBS: 0.22879828673049277
Fold 4 IBS: 0.23764153499408536
Fold 5 IBS: 0.22610754258667487
[I 2024-04-16 20:18:31,818] Trial 69 finished with value: 0.232645054666447 and parameters: {'l1_ratio': 0.04388128327872083}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24359111889588328
Fold 2 IBS: 0.18501466061799773
Fold 3 IBS: 0.19698471627909597
Fold 4 IBS: 0.19410653552156423
Fold 5 IBS: 0.17855051873332467
[I 2024-04-16 20:18:32,089] Trial 70 finished with value: 0.19964951000957315 and parameters: {'l1_ratio': 0.1617630363237179}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24365318751479778
Fold 2 IBS: 0.1850179597081775
Fold 3 IBS: 0.1968526958304697
Fold 4 IBS: 0.19406973011131673
Fold 5 IBS: 0.17856968598224754
[I 2024-04-16 20:18:32,377] Trial 71 finished with value: 0.19963265182940185 and parameters: {'l1_ratio': 0.1176606882158899}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24595094314506413
Fold 2 IBS: 0.22930753186867772
Fold 3 IBS: 0.22883101157700897
Fold 4 IBS: 0.2395878222223208
Fold 5 IBS: 0.22759081385646623
[I 2024-04-16 20:18:32,482] Trial 72 finished with value: 0.23425362453390758 and parameters: {'l1_ratio': 0.02261851641548497}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.2436715203528324
Fold 2 IBS: 0.18498532145790475
Fold 3 IBS: 0.2287366354474198
Fold 4 IBS: 0.19404896162466054
Fold 5 IBS: 0.17859903820930756
[I 2024-04-16 20:18:32,698] Trial 73 finished with value: 0.20600829541842502 and parameters: {'l1_ratio': 0.07585352244108706}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.2435948181060302
Fold 2 IBS: 0.18496501269316815
Fold 3 IBS: 0.19685501102940398
Fold 4 IBS: 0.19408382377141167
Fold 5 IBS: 0.17858589455907828
[I 2024-04-16 20:18:32,937] Trial 74 finished with value: 0.19961691203181844 and parameters: {'l1_ratio': 0.1124189783298729}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24363002758159238
Fold 2 IBS: 0.18497476621126394
Fold 3 IBS: 0.19710969944016107
Fold 4 IBS: 0.1941120549014196
Fold 5 IBS: 0.17853537244174814
[I 2024-04-16 20:18:33,196] Trial 75 finished with value: 0.19967238411523702 and parameters: {'l1_ratio': 0.21877076880955348}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24354504885498812
Fold 2 IBS: 0.1849935382428986

Fold 3 IBS: 0.1970173491910116
Fold 4 IBS: 0.19410597606698898
Fold 5 IBS: 0.17854867444748423
[I 2024-04-16 20:18:33,424] Trial 76 finished with value: 0.1996421173606743 and parameters: {'l1_ratio': 0.17731016579466904}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.2435525817207568
Fold 2 IBS: 0.22582879659192498
Fold 3 IBS: 0.22876806601582172
Fold 4 IBS: 0.23662444816242606
Fold 5 IBS: 0.17868124670242194
[I 2024-04-16 20:18:33,577] Trial 77 finished with value: 0.22269102783867029 and parameters: {'l1_ratio': 0.05625072097962939}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24358639906882854
Fold 2 IBS: 0.18497307008813196
Fold 3 IBS: 0.19689045550507653
Fold 4 IBS: 0.19408913016201246
Fold 5 IBS: 0.1785773099461362
[I 2024-04-16 20:18:33,810] Trial 78 finished with value: 0.19962327295403715 and parameters: {'l1_ratio': 0.1257627141847904}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24626114167923135
Fold 2 IBS: 0.2299660725234959
Fold 3 IBS: 0.2288550020822243
Fold 4 IBS: 0.24015859737969028
Fold 5 IBS: 0.22802372635909307
[I 2024-04-16 20:18:33,897] Trial 79 finished with value: 0.23465290800474697 and parameters: {'l1_ratio': 0.016897608421353322}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24354680917187338
Fold 2 IBS: 0.18503093425900755
Fold 3 IBS: 0.19679934080311778
Fold 4 IBS: 0.19406654937403853
Fold 5 IBS: 0.17857654293506703
[I 2024-04-16 20:18:34,137] Trial 80 finished with value: 0.19960403530862086 and parameters: {'l1_ratio': 0.09661544077725748}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24351881754596036
Fold 2 IBS: 0.18500688834197226
Fold 3 IBS: 0.1967873773400089
Fold 4 IBS: 0.19406023444371454
Fold 5 IBS: 0.17858372530308125
[I 2024-04-16 20:18:34,399] Trial 81 finished with value: 0.19959140859494745 and parameters: {'l1_ratio': 0.09466866078821527}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.2435909996113578
Fold 2 IBS: 0.184947219983378
Fold 3 IBS: 0.19681815750136883
Fold 4 IBS: 0.19407643277502992
Fold 5 IBS: 0.1785968613833155
[I 2024-04-16 20:18:34,619] Trial 82 finished with value: 0.19960593425089002 and parameters: {'l1_ratio': 0.09983397706377614}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24360586409393276
Fold 2 IBS: 0.1849259026020093
Fold 3 IBS: 0.2287409456482157
Fold 4 IBS: 0.1940633404111475
Fold 5 IBS: 0.1785856981921891
[I 2024-04-16 20:18:34,817] Trial 83 finished with value: 0.20598435018949884 and parameters: {'l1_ratio': 0.07228433589359468}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24366091039261864
Fold 2 IBS: 0.18499781107734672
Fold 3 IBS: 0.1967828556858145
Fold 4 IBS: 0.19405784143271762
Fold 5 IBS: 0.17858644453581002
[I 2024-04-16 20:18:35,041] Trial 84 finished with value: 0.1996171726248615 and parameters: {'l1_ratio': 0.09395190709932545}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24343727975107907
Fold 2 IBS: 0.18507849149982958
Fold 3 IBS: 0.19730249806073316
Fold 4 IBS: 0.19421155221786157
Fold 5 IBS: 0.17847258448641118
[I 2024-04-16 20:18:35,232] Trial 85 finished with value: 0.19970048120318293 and parameters: {'l1_ratio': 0.6114164712527408}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24349335535659491
Fold 2 IBS: 0.18496937122250987
Fold 3 IBS: 0.19705379201156004
Fold 4 IBS: 0.19410515744717416
Fold 5 IBS: 0.17854697201624006
[I 2024-04-16 20:18:35,451] Trial 86 finished with value: 0.1996337296108158 and parameters: {'l1_ratio': 0.19416541239839968}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24356615437044535
Fold 2 IBS: 0.18499143835949994
Fold 3 IBS: 0.19697312411329912
Fold 4 IBS: 0.19410113789111605
Fold 5 IBS: 0.17855752577426104
[I 2024-04-16 20:18:35,664] Trial 87 finished with value: 0.1996378761017243 and parameters: {'l1_ratio': 0.15847955318377355}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24572222562988152
Fold 2 IBS: 0.2288198725317634
Fold 3 IBS: 0.22881883869056904
Fold 4 IBS: 0.23916707735750148
Fold 5 IBS: 0.22727111585010515
[I 2024-04-16 20:18:35,749] Trial 88 finished with value: 0.2339598260119641 and parameters: {'l1_ratio': 0.026975696361528953}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24349333036749604
Fold 2 IBS: 0.18502666693000425
Fold 3 IBS: 0.1971964745083337
Fold 4 IBS: 0.19412924281396596
Fold 5 IBS: 0.1785086180759256
[I 2024-04-16 20:18:35,934] Trial 89 finished with value: 0.19967086653914512 and parameters: {'l1_ratio': 0.25833215998274794}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24366116387210665
Fold 2 IBS: 0.18495768810233032
Fold 3 IBS: 0.22875918320537802
Fold 4 IBS: 0.23627570709055626
Fold 5 IBS: 0.17863260061394395
[I 2024-04-16 20:18:36,119] Trial 90 finished with value: 0.21445726857686304 and parameters: {'l1_ratio': 0.06072259126647666}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24361824758876938
Fold 2 IBS: 0.18497232891283252
Fold 3 IBS: 0.1968297176701934
Fold 4 IBS: 0.19408247465618642
Fold 5 IBS: 0.17858927160218083
[I 2024-04-16 20:18:36,334] Trial 91 finished with value: 0.19961840808603254 and parameters: {'l1_ratio': 0.10191296073883455}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24358552110316004
Fold 2 IBS: 0.18498985858530906
Fold 3 IBS: 0.1969334172193769
Fold 4 IBS: 0.19409677190866573
Fold 5 IBS: 0.17856546386556613
[I 2024-04-16 20:18:36,570] Trial 92 finished with value: 0.19963420653641556 and parameters: {'l1_ratio': 0.1419751678519491}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24365000415141622
Fold 2 IBS: 0.1849877913584714
Fold 3 IBS: 0.19681243694220946
Fold 4 IBS: 0.19405519413988398
Fold 5 IBS: 0.17858945125288941
[I 2024-04-16 20:18:36,785] Trial 93 finished with value: 0.19961897556897407 and parameters: {'l1_ratio': 0.09317191765815475}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24349074079266253
Fold 2 IBS: 0.1850847462586338
Fold 3 IBS: 0.1973392816454048
Fold 4 IBS: 0.19423797745846588
Fold 5 IBS: 0.17853880762500338
[I 2024-04-16 20:18:36,966] Trial 94 finished with value: 0.19973831075603407 and parameters: {'l1_ratio': 0.8606850154038875}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24364642640350662
Fold 2 IBS: 0.18502762180336482
Fold 3 IBS: 0.1968923453881898
Fold 4 IBS: 0.19407597896512288
Fold 5 IBS: 0.17856060604394755
[I 2024-04-16 20:18:37,219] Trial 95 finished with value: 0.19964059572082632 and parameters: {'l1_ratio': 0.13191383620003239}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.2454637694351678
Fold 2 IBS: 0.22826651447232432
Fold 3 IBS: 0.22881111423310851
Fold 4 IBS: 0.2386916763346286
Fold 5 IBS: 0.22690927467127173
[I 2024-04-16 20:18:37,304] Trial 96 finished with value: 0.23362846982930016 and parameters: {'l1_ratio': 0.03205069556460069}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.2435722166666429
Fold 2 IBS: 0.22575672429231303
Fold 3 IBS: 0.2287664700617641
Fold 4 IBS: 0.23656403596556222
Fold 5 IBS: 0.17869337799408064
[I 2024-04-16 20:18:37,445] Trial 97 finished with value: 0.22267056499607257 and parameters: {'l1_ratio': 0.05701650860846961}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24702540605860662
Fold 2 IBS: 0.23157576736196353
Fold 3 IBS: 0.22894681972514333
Fold 4 IBS: 0.241566006017055
Fold 5 IBS: 0.22908757321765433
[I 2024-04-16 20:18:37,536] Trial 98 finished with value: 0.23564031447608458 and parameters: {'l1_ratio': 0.0036415712723664034}. Best is trial 34 with value: 0.19958936354302614.
Fold 1 IBS: 0.24354493159919716
Fold 2 IBS: 0.18499342875562194
Fold 3 IBS: 0.19701729724976735
Fold 4 IBS: 0.19410595076351722
Fold 5 IBS: 0.17854870759779934
[I 2024-04-16 20:18:37,736] Trial 99 finished with value: 0.19964206319318062 and parameters: {'l1_ratio': 0.17729288964740325}. Best is trial 34 with value: 0.19958936354302614.


* Best trial for IBS:
 FrozenTrial(number=34, state=TrialState.COMPLETE, values=[0.19958936354302614], datetime_start=datetime.datetime(2024, 4, 16, 20, 18, 24, 974366), datetime_complete=datetime.datetime(2024, 4, 16, 20, 18, 25, 180411), params={'l1_ratio': 0.08888945657798078}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=34, value=None)


* Best Score for IBS:
 0.19958936354302614

In [52]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [53]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.709
train_ibs:  0.2

#### Test

In [54]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [55]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.22692876841884668)

test_cindex : 0.565

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.08888945657798078)

test_ibs:  0.264

In [56]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [57]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:18:37,928] A new study created in memory with name: no-name-9dca24b4-2b75-41b9-9843-0397bcde30dc

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 20:18:40,404] Trial 0 finished with value: 0.6981078971834117 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6981078971834117.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.7927756653992395
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 20:18:42,080] Trial 1 finished with value: 0.7168121053676654 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7168121053676654.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7889733840304183
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 20:18:43,199] Trial 2 finished with value: 0.721042521498354 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 2 with value: 0.721042521498354.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:18:43,617] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 2 with value: 0.721042521498354.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:18:44,309] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 2 with value: 0.721042521498354.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.811787072243346
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 20:18:46,100] Trial 5 finished with value: 0.7117150237621301 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 2 with value: 0.721042521498354.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.7775665399239544
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 20:18:48,840] Trial 6 finished with value: 0.6993555556783448 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 2 with value: 0.721042521498354.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:18:50,584] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 2 with value: 0.721042521498354.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 20:18:54,342] Trial 8 finished with value: 0.5390557939914162 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 2 with value: 0.721042521498354.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.8003802281368821
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 20:18:56,085] Trial 9 finished with value: 0.7087632553932048 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 2 with value: 0.721042521498354.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:18:56,269] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 26, 'oob_score': True, 'max_samples': 0.9607577284547746, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 2 with value: 0.721042521498354.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.785171102661597
Fold 5 C-index: 0.703862660944206
[I 2024-04-16 20:18:57,243] Trial 11 finished with value: 0.7219914981530895 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1579906038170908, 'warm_start': False}. Best is trial 11 with value: 0.7219914981530895.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.7927756653992395
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 20:18:58,474] Trial 12 finished with value: 0.7161633247705873 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 147, 'oob_score': False, 'max_samples': 0.8619834498485652, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1611753146667314, 'warm_start': False}. Best is trial 11 with value: 0.7219914981530895.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:18:59,305] Trial 13 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.10013306718236009, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1567471583060459, 'warm_start': False}. Best is trial 11 with value: 0.7219914981530895.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8498098859315589
Fold 5 C-index: 0.8326180257510729
[I 2024-04-16 20:19:00,155] Trial 14 finished with value: 0.780987764930577 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 204, 'oob_score': True, 'max_samples': 0.8364130211722378, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1306449501762567, 'warm_start': True}. Best is trial 14 with value: 0.780987764930577.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7693798449612403
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7832699619771863

Fold 5 C-index: 0.759656652360515
[I 2024-04-16 20:19:00,606] Trial 15 finished with value: 0.7542609019301453 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 92, 'oob_score': True, 'max_samples': 0.792913180904143, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09179883523732954, 'warm_start': True}. Best is trial 14 with value: 0.780987764930577.
Fold 1 C-index: 0.5517928286852589
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.723175965665236
[I 2024-04-16 20:19:00,743] Trial 16 finished with value: 0.7212623367742224 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 5, 'oob_score': True, 'max_samples': 0.44827686549014745, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07731335546121543, 'warm_start': True}. Best is trial 14 with value: 0.780987764930577.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8307984790874525
Fold 5 C-index: 0.8283261802575107
[I 2024-04-16 20:19:01,112] Trial 17 finished with value: 0.7793189800864806 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 74, 'oob_score': True, 'max_samples': 0.7596776691971983, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10327357472994507, 'warm_start': True}. Best is trial 14 with value: 0.780987764930577.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.7639484978540773
[I 2024-04-16 20:19:01,544] Trial 18 finished with value: 0.7440468837830455 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 101, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.780987764930577.
Fold 1 C-index: 0.651394422310757
Fold 2 C-index: 0.7616279069767442
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7639484978540773
[I 2024-04-16 20:19:01,840] Trial 19 finished with value: 0.7529898292095631 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 54, 'oob_score': True, 'max_samples': 0.6940275054919826, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2171861810731355, 'warm_start': True}. Best is trial 14 with value: 0.780987764930577.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7927756653992395
Fold 5 C-index: 0.7811158798283262
[I 2024-04-16 20:19:02,705] Trial 20 finished with value: 0.7549162629202664 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 220, 'oob_score': True, 'max_samples': 0.5018171832362744, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11709282828400099, 'warm_start': True}. Best is trial 14 with value: 0.780987764930577.
Fold 1 C-index: 0.651394422310757
Fold 2 C-index: 0.7538759689922481
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 20:19:03,735] Trial 21 finished with value: 0.7503352835466436 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 18, 'n_estimators': 163, 'oob_score': True, 'max_samples': 0.501303850313382, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12282305019689495, 'warm_start': True}. Best is trial 14 with value: 0.780987764930577.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:19:04,844] Trial 22 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 213, 'oob_score': True, 'max_samples': 0.39123396977027813, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21275742182947582, 'warm_start': True}. Best is trial 14 with value: 0.780987764930577.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.811787072243346
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 20:19:05,832] Trial 23 finished with value: 0.7741874977718336 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 226, 'oob_score': True, 'max_samples': 0.8440676043170373, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0023497522601186316, 'warm_start': True}. Best is trial 14 with value: 0.780987764930577.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8041825095057035
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 20:19:06,491] Trial 24 finished with value: 0.7749921666196539 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 140, 'oob_score': True, 'max_samples': 0.839996573192809, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.003269976302471944, 'warm_start': True}. Best is trial 14 with value: 0.780987764930577.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8498098859315589
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 20:19:07,077] Trial 25 finished with value: 0.7791331929433113 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 128, 'oob_score': True, 'max_samples': 0.8788184468088565, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.054745429968712934, 'warm_start': True}. Best is trial 14 with value: 0.780987764930577.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8536121673003803
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 20:19:07,411] Trial 26 finished with value: 0.7780394846386047 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 61, 'oob_score': True, 'max_samples': 0.6948945011504787, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05058696770992366, 'warm_start': True}. Best is trial 14 with value: 0.780987764930577.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8536121673003803
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 20:19:07,865] Trial 27 finished with value: 0.7886806158154684 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 114, 'oob_score': True, 'max_samples': 0.8949569031566396, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07079832222777067, 'warm_start': True}. Best is trial 27 with value: 0.7886806158154684.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8231939163498099
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 20:19:08,283] Trial 28 finished with value: 0.7768778452343098 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 64, 'oob_score': True, 'max_samples': 0.9976871416646873, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18601485458868533, 'warm_start': True}. Best is trial 27 with value: 0.7886806158154684.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7693798449612403
Fold 3 C-index: 0.7808510638297872
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.7725321888412017
[I 2024-04-16 20:19:09,715] Trial 29 finished with value: 0.7570813638646823 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 176, 'oob_score': True, 'max_samples': 0.7488754310335448, 'max_features': None, 'min_weight_fraction_leaf': 0.25087036098392035, 'warm_start': True}. Best is trial 27 with value: 0.7886806158154684.

Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8612167300380228
Fold 5 C-index: 0.8154506437768241
[I 2024-04-16 20:19:10,232] Trial 30 finished with value: 0.7884814896636174 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 108, 'oob_score': True, 'max_samples': 0.6618240078421601, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08976817948926405, 'warm_start': True}. Best is trial 27 with value: 0.7886806158154684.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8498098859315589
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 20:19:10,788] Trial 31 finished with value: 0.7886920528381992 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 112, 'oob_score': True, 'max_samples': 0.6801708526773039, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08737360579685344, 'warm_start': True}. Best is trial 31 with value: 0.7886920528381992.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8574144486692015
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 20:19:11,275] Trial 32 finished with value: 0.7856596989857166 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 121, 'oob_score': True, 'max_samples': 0.6651666888285306, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0786417979301093, 'warm_start': True}. Best is trial 31 with value: 0.7886920528381992.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8536121673003803
Fold 5 C-index: 0.8326180257510729
[I 2024-04-16 20:19:11,882] Trial 33 finished with value: 0.7857649170795901 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 118, 'oob_score': True, 'max_samples': 0.6629951073841054, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07903088974744935, 'warm_start': True}. Best is trial 31 with value: 0.7886920528381992.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8155893536121673
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 20:19:12,076] Trial 34 finished with value: 0.7631728297345168 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 24, 'oob_score': True, 'max_samples': 0.559657028759316, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0771152941887649, 'warm_start': True}. Best is trial 31 with value: 0.7886920528381992.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8802281368821293
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 20:19:12,584] Trial 35 finished with value: 0.8018995975402999 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.6103161838422714, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.041799651789036885, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8498098859315589
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 20:19:13,422] Trial 36 finished with value: 0.7789778555224602 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 248, 'oob_score': True, 'max_samples': 0.5758974610546623, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.038549206184003613, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8003875968992248
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8155893536121673
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 20:19:13,635] Trial 37 finished with value: 0.7734677769497383 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 38, 'oob_score': True, 'max_samples': 0.6101076076880284, 'max_features': None, 'min_weight_fraction_leaf': 0.1380110824179854, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7655038759689923
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8079847908745247
Fold 5 C-index: 0.8025751072961373
[I 2024-04-16 20:19:14,310] Trial 38 finished with value: 0.7725358030605324 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 180, 'oob_score': True, 'max_samples': 0.726737616931393, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18506717673116782, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8422053231939164
Fold 5 C-index: 0.8154506437768241
[I 2024-04-16 20:19:15,286] Trial 39 finished with value: 0.7758596095661745 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 366, 'oob_score': True, 'max_samples': 0.5151837063346413, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03246839013755631, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7461240310077519
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.8079847908745247
Fold 5 C-index: 0.7424892703862661
[I 2024-04-16 20:19:17,152] Trial 40 finished with value: 0.7434240517842163 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 6, 'n_estimators': 497, 'oob_score': True, 'max_samples': 0.9160550266640065, 'max_features': None, 'min_weight_fraction_leaf': 0.38462517942590646, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.876425855513308
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:19:17,715] Trial 41 finished with value: 0.7986145771404323 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 121, 'oob_score': True, 'max_samples': 0.6276170642551812, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.058304392917417125, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8612167300380228
Fold 5 C-index: 0.8412017167381974
[I 2024-04-16 20:19:18,187] Trial 42 finished with value: 0.7898536316543308 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 91, 'oob_score': True, 'max_samples': 0.6236464814282915, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06338346916999713, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8650190114068441
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 20:19:18,591] Trial 43 finished with value: 0.7892668653898907 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 84, 'oob_score': True, 'max_samples': 0.426499621761955, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05884824692432198, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8307984790874525
Fold 5 C-index: 0.7682403433476395
[I 2024-04-16 20:19:18,909] Trial 44 finished with value: 0.7712426385484175 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 86, 'oob_score': True, 'max_samples': 0.3368204698190736, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.021838238803210286, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.8250950570342205

Fold 5 C-index: 0.7875536480686696
[I 2024-04-16 20:19:18,984] Trial 45 finished with value: 0.7257117351289212 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.6064451897907044, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06131578730937154, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 20:19:19,352] Trial 46 finished with value: 0.7188699748801566 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 39, 'oob_score': True, 'max_samples': 0.4425345107430515, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1067722201468298, 'warm_start': False}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8041825095057035
Fold 5 C-index: 0.8025751072961373
[I 2024-04-16 20:19:19,680] Trial 47 finished with value: 0.7681246288601897 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 146, 'oob_score': False, 'max_samples': 0.21847092350101632, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03857556224139366, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:19:20,647] Trial 48 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.5490595027260221, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.491438551581221, 'warm_start': False}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8574144486692015
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 20:19:21,862] Trial 49 finished with value: 0.7912194771889396 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 180, 'oob_score': True, 'max_samples': 0.38678309243508646, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0009598234237258654, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8498098859315589
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 20:19:22,377] Trial 50 finished with value: 0.7811330815503128 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 177, 'oob_score': False, 'max_samples': 0.38072363795405095, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.006714393941094581, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8193916349809885
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 20:19:22,993] Trial 51 finished with value: 0.7735066458884461 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 133, 'oob_score': True, 'max_samples': 0.261085252461408, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.050579232359344195, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 20:19:23,799] Trial 52 finished with value: 0.79503291131274 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 194, 'oob_score': True, 'max_samples': 0.6168515939951056, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023771448131791162, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 20:19:24,783] Trial 53 finished with value: 0.8005155744037464 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 240, 'oob_score': True, 'max_samples': 0.6258766158338841, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.015706104441955023, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:19:26,028] Trial 54 finished with value: 0.7974696011206224 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 287, 'oob_score': True, 'max_samples': 0.6365524404665521, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.020088166802463423, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 20:19:27,214] Trial 55 finished with value: 0.7968650330976004 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 298, 'oob_score': True, 'max_samples': 0.5492401660649442, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.018876735657307187, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 20:19:30,049] Trial 56 finished with value: 0.7140441722215732 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 313, 'oob_score': True, 'max_samples': 0.535319763778926, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.026236111201433994, 'warm_start': False}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 20:19:31,119] Trial 57 finished with value: 0.7952639753438323 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 283, 'oob_score': True, 'max_samples': 0.5818268637936542, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01924167385811952, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 20:19:32,347] Trial 58 finished with value: 0.7935188801910804 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 337, 'oob_score': True, 'max_samples': 0.4793770534896546, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.040880296485497084, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:19:32,904] Trial 59 finished with value: 0.7968508464028062 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 271, 'oob_score': False, 'max_samples': 0.5742732608137732, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.019185605894392187, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.

Fold 1 C-index: 0.6354581673306773
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 20:19:34,404] Trial 60 finished with value: 0.7136578832609695 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.7117531457303862, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2884043121771884, 'warm_start': False}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 20:19:34,885] Trial 61 finished with value: 0.7976870457210731 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.5848644872606624, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.014275642039175395, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 20:19:35,496] Trial 62 finished with value: 0.7911609470874625 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 308, 'oob_score': False, 'max_samples': 0.6450169706176654, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012779996111530242, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 20:19:36,166] Trial 63 finished with value: 0.7958656566939275 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.5232272070325166, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04028100254598046, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8460076045627376
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 20:19:36,860] Trial 64 finished with value: 0.7734617390634024 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.5725608317320592, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10415283732963354, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:19:37,395] Trial 65 finished with value: 0.792693016235762 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6355727297962999, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01613335630495155, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:19:37,872] Trial 66 finished with value: 0.7958765428867671 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 264, 'oob_score': False, 'max_samples': 0.5908680888311725, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04866322761773802, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8326180257510729
[I 2024-04-16 20:19:38,546] Trial 67 finished with value: 0.7830880153325771 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 399, 'oob_score': False, 'max_samples': 0.47166049079842903, 'max_features': None, 'min_weight_fraction_leaf': 0.03258421286086256, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 20:19:38,966] Trial 68 finished with value: 0.7984264503084357 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.7666742893033657, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0025709596055121936, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.876425855513308
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 20:19:39,327] Trial 69 finished with value: 0.7955827741178408 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.795428430557572, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07073121542667885, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8574144486692015
Fold 5 C-index: 0.8369098712446352
[I 2024-04-16 20:19:39,681] Trial 70 finished with value: 0.7889557489995204 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 231, 'oob_score': False, 'max_samples': 0.7730347953502961, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09472741493957117, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 20:19:40,093] Trial 71 finished with value: 0.7977523099815309 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 267, 'oob_score': False, 'max_samples': 0.7247247012833545, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00820932194445243, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8669527896995708
[I 2024-04-16 20:19:40,622] Trial 72 finished with value: 0.7991146174747767 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 291, 'oob_score': False, 'max_samples': 0.7417264428889381, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.002608902291688857, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 20:19:41,117] Trial 73 finished with value: 0.7951849482316364 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 324, 'oob_score': False, 'max_samples': 0.7337839883333517, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0030579939157153895, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 20:19:41,497] Trial 74 finished with value: 0.799143244838035 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 261, 'oob_score': False, 'max_samples': 0.7060061286842817, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.047622241222910824, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 20:19:41,876] Trial 75 finished with value: 0.7957823544068298 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.699892605550188, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05028553273569978, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8460076045627376
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 20:19:42,230] Trial 76 finished with value: 0.7800499448766125 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.8157866085949504, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14163119849625333, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8369098712446352
[I 2024-04-16 20:19:42,675] Trial 77 finished with value: 0.7893401088902079 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 273, 'oob_score': False, 'max_samples': 0.7671015536474619, 'max_features': None, 'min_weight_fraction_leaf': 0.0018321497038652143, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:19:43,006] Trial 78 finished with value: 0.7928020856614812 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.6743005622797104, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03618107765260176, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8688212927756654
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 20:19:43,379] Trial 79 finished with value: 0.7957459676375084 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 243, 'oob_score': False, 'max_samples': 0.7178688513973288, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06500779154038594, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 20:19:45,174] Trial 80 finished with value: 0.7084219899825296 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.7525446823236868, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03192335037468508, 'warm_start': False}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:19:45,593] Trial 81 finished with value: 0.7959671504427901 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 293, 'oob_score': False, 'max_samples': 0.6437287338900735, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009282006978553546, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:19:46,007] Trial 82 finished with value: 0.7958765428867671 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.6833905434664187, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04789621933973127, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 20:19:46,462] Trial 83 finished with value: 0.7989698858248053 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.7372714466437177, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.026674164270992944, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8688212927756654
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 20:19:46,727] Trial 84 finished with value: 0.791530289031505 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 161, 'oob_score': False, 'max_samples': 0.8165695024214783, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08604180920310056, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:19:47,169] Trial 85 finished with value: 0.800725840722107 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.7868074337823069, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06208966089188629, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:19:47,616] Trial 86 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 317, 'oob_score': False, 'max_samples': 0.7330094472721614, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3635551959165382, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8412017167381974
[I 2024-04-16 20:19:48,164] Trial 87 finished with value: 0.7942352508776236 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.8363010111447975, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.061564366501586185, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8802281368821293
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:19:48,608] Trial 88 finished with value: 0.799516167705992 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 300, 'oob_score': False, 'max_samples': 0.7860550327573047, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07020753081716193, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8574144486692015
Fold 5 C-index: 0.8326180257510729
[I 2024-04-16 20:19:49,196] Trial 89 finished with value: 0.7866665076451498 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 381, 'oob_score': False, 'max_samples': 0.7846539262714959, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07601794232000327, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8612167300380228
Fold 5 C-index: 0.8412017167381974
[I 2024-04-16 20:19:49,751] Trial 90 finished with value: 0.788216768255214 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.8528846220313682, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09717014725053419, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 20:19:50,373] Trial 91 finished with value: 0.7997918984482781 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 259, 'oob_score': False, 'max_samples': 0.7411369405679075, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.031578654956156915, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8498098859315589
Fold 5 C-index: 0.8154506437768241
[I 2024-04-16 20:19:51,059] Trial 92 finished with value: 0.7799231078321848 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 340, 'oob_score': False, 'max_samples': 0.7607145652981907, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1133048877854256, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 20:19:51,607] Trial 93 finished with value: 0.7984374634881102 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 321, 'oob_score': False, 'max_samples': 0.6972567586928843, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04482417766391582, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8688212927756654
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 20:19:52,152] Trial 94 finished with value: 0.7914434058204929 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.6574413394161338, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06922021746808385, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:19:52,736] Trial 95 finished with value: 0.7990384505872179 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.706680283206331, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.054043714140949876, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 20:19:53,104] Trial 96 finished with value: 0.7975212459504386 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 196, 'oob_score': False, 'max_samples': 0.8132235301605945, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.055640448698215716, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.785171102661597
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 20:19:54,828] Trial 97 finished with value: 0.7282609090380829 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 304, 'oob_score': False, 'max_samples': 0.7377667387696466, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.23287394451224314, 'warm_start': False}. Best is trial 35 with value: 0.8018995975402999.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8307984790874525
Fold 5 C-index: 0.8154506437768241
[I 2024-04-16 20:19:55,369] Trial 98 finished with value: 0.7758601768303272 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.7070010699512933, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12374979636578538, 'warm_start': True}. Best is trial 35 with value: 0.8018995975402999.

[I 2024-04-16 20:19:55,917] A new study created in memory with name: no-name-6bfd86dd-03d1-4da1-8815-ea58c65d9c14

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 20:19:55,905] Trial 99 finished with value: 0.8054085339832513 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.8893723590453224, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029301059641382382, 'warm_start': True}. Best is trial 99 with value: 0.8054085339832513.


* Best trial for C-index:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.8054085339832513], datetime_start=datetime.datetime(2024, 4, 16, 20, 19, 55, 373617), datetime_complete=datetime.datetime(2024, 4, 16, 20, 19, 55, 905066), params={'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.8893723590453224, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029301059641382382, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=99, value=None)


* Best Score for C-index:
 0.8054085339832513

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21263876975933696
Fold 2 IBS: 0.17794321625197576
Fold 3 IBS: 0.2370611144935792
Fold 4 IBS: 0.21414410919393193
Fold 5 IBS: 0.22010020340035819
[I 2024-04-16 20:19:58,077] Trial 0 finished with value: 0.2123774826198364 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.2123774826198364.
Fold 1 IBS: 0.21458406238444913
Fold 2 IBS: 0.18752997909308472
Fold 3 IBS: 0.20009930142414203
Fold 4 IBS: 0.2044001304575593
Fold 5 IBS: 0.19457782357479128
[I 2024-04-16 20:19:58,625] Trial 1 finished with value: 0.20023825938680528 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.20023825938680528.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-16 20:19:59,023] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.20023825938680528.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-16 20:20:00,703] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.20023825938680528.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-16 20:20:01,976] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.20023825938680528.
Fold 1 IBS: 0.22838421372660472
Fold 2 IBS: 0.17239315725523094
Fold 3 IBS: 0.20023195093017002
Fold 4 IBS: 0.18938161908002712
Fold 5 IBS: 0.19848750959417513
[I 2024-04-16 20:20:03,596] Trial 5 finished with value: 0.19777569011724158 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.19777569011724158.
Fold 1 IBS: 0.21062274139651044
Fold 2 IBS: 0.19012446633012922
Fold 3 IBS: 0.25362762627687513
Fold 4 IBS: 0.20312530490300412
Fold 5 IBS: 0.21324487928589062
[I 2024-04-16 20:20:05,203] Trial 6 finished with value: 0.21414900363848188 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.19777569011724158.
Fold 1 IBS: 0.2417759530513164
Fold 2 IBS: 0.2243890110847975
Fold 3 IBS: 0.22463553553135543
Fold 4 IBS: 0.23563171920975698
Fold 5 IBS: 0.22428558294357817
[I 2024-04-16 20:20:07,017] Trial 7 finished with value: 0.23014356036416092 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.19777569011724158.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-16 20:20:10,843] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.19777569011724158.
Fold 1 IBS: 0.21594729591251147
Fold 2 IBS: 0.19120309286355594
Fold 3 IBS: 0.19494355905231225
Fold 4 IBS: 0.20745636315157934
Fold 5 IBS: 0.20111398670191788
[I 2024-04-16 20:20:11,545] Trial 9 finished with value: 0.2021328595363754 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.19777569011724158.
Fold 1 IBS: 0.24645571521465787
Fold 2 IBS: 0.23214351218858914
Fold 3 IBS: 0.23029990468218745
Fold 4 IBS: 0.24091247880712954
Fold 5 IBS: 0.22969387017589088
[I 2024-04-16 20:20:14,958] Trial 10 finished with value: 0.235901096213691 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.19777569011724158.
Fold 1 IBS: 0.22566289308676166
Fold 2 IBS: 0.1901642049430949
Fold 3 IBS: 0.19513598938835125
Fold 4 IBS: 0.20445365828964382
Fold 5 IBS: 0.1983587497572364
[I 2024-04-16 20:20:15,803] Trial 11 finished with value: 0.2027550990930176 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12378097340613392}. Best is trial 5 with value: 0.19777569011724158.
Fold 1 IBS: 0.22580192277807298
Fold 2 IBS: 0.16771899717640854
Fold 3 IBS: 0.19983633456508468
Fold 4 IBS: 0.1980235110195178
Fold 5 IBS: 0.19593574989020948
[I 2024-04-16 20:20:15,999] Trial 12 finished with value: 0.1974633030858587 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.7642078791940475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13207155531457032}. Best is trial 12 with value: 0.1974633030858587.
Fold 1 IBS: 0.22401435214086382
Fold 2 IBS: 0.171973111469291
Fold 3 IBS: 0.22073097796161276
Fold 4 IBS: 0.20174854243010945
Fold 5 IBS: 0.19970884176500928
[I 2024-04-16 20:20:16,197] Trial 13 finished with value: 0.20363516515337726 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 14, 'oob_score': False, 'max_samples': 0.8293737737164385, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09633845721802128}. Best is trial 12 with value: 0.1974633030858587.
Fold 1 IBS: 0.23711385121503972
Fold 2 IBS: 0.17409336929797803
Fold 3 IBS: 0.1995274010046252
Fold 4 IBS: 0.18807619294070863
Fold 5 IBS: 0.19799573412689978
[I 2024-04-16 20:20:17,871] Trial 14 finished with value: 0.19936130971705027 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.6604916334814492, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02382938621825248}. Best is trial 12 with value: 0.1974633030858587.
Fold 1 IBS: 0.2154246757336862
Fold 2 IBS: 0.18858046164302683
Fold 3 IBS: 0.20034383203185166
Fold 4 IBS: 0.20257721375249338
Fold 5 IBS: 0.20064742633667446
[I 2024-04-16 20:20:19,081] Trial 15 finished with value: 0.2015147218995465 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.9932150048245644, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2762403453179886}. Best is trial 12 with value: 0.1974633030858587.

Fold 1 IBS: 0.2217020346118366
Fold 2 IBS: 0.19663476200242688
Fold 3 IBS: 0.20389940943734078
Fold 4 IBS: 0.2087600858399502
Fold 5 IBS: 0.2011853081455008
[I 2024-04-16 20:20:20,729] Trial 16 finished with value: 0.20643632000741102 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.3880731320622045, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14354526791362227}. Best is trial 12 with value: 0.1974633030858587.
Fold 1 IBS: 0.22369312009701028
Fold 2 IBS: 0.17603782678492705
Fold 3 IBS: 0.20133246245480546
Fold 4 IBS: 0.18641409555333716
Fold 5 IBS: 0.20027377176843306
[I 2024-04-16 20:20:21,957] Trial 17 finished with value: 0.19755025533170262 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 250, 'oob_score': False, 'max_samples': 0.7684587619660335, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07846592181777899}. Best is trial 12 with value: 0.1974633030858587.
Fold 1 IBS: 0.21763680161168972
Fold 2 IBS: 0.1819265470010227
Fold 3 IBS: 0.19905648468105003
Fold 4 IBS: 0.19818715712560084
Fold 5 IBS: 0.1988737253288157
[I 2024-04-16 20:20:24,725] Trial 18 finished with value: 0.19913614314963582 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.8165138000494551, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.20223993640525578}. Best is trial 12 with value: 0.1974633030858587.
Fold 1 IBS: 0.23826305188430366
Fold 2 IBS: 0.1696077984350761
Fold 3 IBS: 0.19621769207397732
Fold 4 IBS: 0.20818960643144035
Fold 5 IBS: 0.20928806336835604
[I 2024-04-16 20:20:24,860] Trial 19 finished with value: 0.2043132424386307 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 10, 'oob_score': False, 'max_samples': 0.9292044173196737, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05391423417260216}. Best is trial 12 with value: 0.1974633030858587.
Fold 1 IBS: 0.22037462335165278
Fold 2 IBS: 0.1802778477377455
Fold 3 IBS: 0.19436294882795083
Fold 4 IBS: 0.19712893539971643
Fold 5 IBS: 0.19634099777996109
[I 2024-04-16 20:20:25,666] Trial 20 finished with value: 0.1976970706194053 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 147, 'oob_score': False, 'max_samples': 0.7582346516216052, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1481708053054655}. Best is trial 12 with value: 0.1974633030858587.
Fold 1 IBS: 0.22103504276848154
Fold 2 IBS: 0.1793773727984745
Fold 3 IBS: 0.1948805628137699
Fold 4 IBS: 0.19633664913997345
Fold 5 IBS: 0.19742832843346658
[I 2024-04-16 20:20:26,548] Trial 21 finished with value: 0.1978115911908332 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.7636774062113323, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14915714846088535}. Best is trial 12 with value: 0.1974633030858587.
Fold 1 IBS: 0.21773056579436156
Fold 2 IBS: 0.17961387741249069
Fold 3 IBS: 0.20124148173893075
Fold 4 IBS: 0.19631200359503378
Fold 5 IBS: 0.19396446535800385
[I 2024-04-16 20:20:27,140] Trial 22 finished with value: 0.19777247877976412 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 111, 'oob_score': False, 'max_samples': 0.5860032490734787, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1089853643297641}. Best is trial 12 with value: 0.1974633030858587.
Fold 1 IBS: 0.22051581754380947
Fold 2 IBS: 0.1813419555568541
Fold 3 IBS: 0.19140760985717806
Fold 4 IBS: 0.20089374718178785
Fold 5 IBS: 0.20039117766432152
[I 2024-04-16 20:20:27,523] Trial 23 finished with value: 0.19891006156079022 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 56, 'oob_score': False, 'max_samples': 0.7983055556240619, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17807138804737838}. Best is trial 12 with value: 0.1974633030858587.
Fold 1 IBS: 0.2179571527123336
Fold 2 IBS: 0.1860325294844968
Fold 3 IBS: 0.1985581072873223
Fold 4 IBS: 0.2013121784355901
Fold 5 IBS: 0.1997891542937473
[I 2024-04-16 20:20:28,994] Trial 24 finished with value: 0.200729824442698 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9384310197213468, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2492156163648213}. Best is trial 12 with value: 0.1974633030858587.
Fold 1 IBS: 0.22542916397565654
Fold 2 IBS: 0.17647805681593204
Fold 3 IBS: 0.19511476790317053
Fold 4 IBS: 0.1915398549387354
Fold 5 IBS: 0.19601847192706096
[I 2024-04-16 20:20:30,695] Trial 25 finished with value: 0.1969160631121111 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.6219587265298226, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04150205593813106}. Best is trial 25 with value: 0.1969160631121111.
Fold 1 IBS: 0.2231512222296304
Fold 2 IBS: 0.17374314374377825
Fold 3 IBS: 0.1970097623619077
Fold 4 IBS: 0.18795401327887085
Fold 5 IBS: 0.1966828957024163
[I 2024-04-16 20:20:32,566] Trial 26 finished with value: 0.19570820746332068 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.4704864355905733, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0006764202811209152}. Best is trial 26 with value: 0.19570820746332068.
Fold 1 IBS: 0.216840305156087
Fold 2 IBS: 0.19144737241809384
Fold 3 IBS: 0.2023940455135519
Fold 4 IBS: 0.20426034342507843
Fold 5 IBS: 0.20109304800059288
[I 2024-04-16 20:20:35,909] Trial 27 finished with value: 0.20320702290268078 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 397, 'oob_score': True, 'max_samples': 0.42986872509169843, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008408299739211714}. Best is trial 26 with value: 0.19570820746332068.
Fold 1 IBS: 0.21767847698514867
Fold 2 IBS: 0.1790685601460637
Fold 3 IBS: 0.19371494564458674
Fold 4 IBS: 0.1943494531998045
Fold 5 IBS: 0.19372943000064993
[I 2024-04-16 20:20:37,867] Trial 28 finished with value: 0.1957081731952507 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 248, 'oob_score': True, 'max_samples': 0.26154064534881144, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04129051895687466}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.2172026647015326
Fold 2 IBS: 0.1824083715105139
Fold 3 IBS: 0.19562668794317245
Fold 4 IBS: 0.1961601047009392
Fold 5 IBS: 0.19408636190022244
[I 2024-04-16 20:20:39,951] Trial 29 finished with value: 0.1970968381512761 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 248, 'oob_score': True, 'max_samples': 0.2235833480807206, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04992822284127603}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.2184153471788204
Fold 2 IBS: 0.17906023393500314
Fold 3 IBS: 0.19905983433643076
Fold 4 IBS: 0.19844544979826273
Fold 5 IBS: 0.19492190247440963
[I 2024-04-16 20:20:42,116] Trial 30 finished with value: 0.19798055354458532 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 316, 'oob_score': True, 'max_samples': 0.248038082278575, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0013270708569045296}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.22278102445798328
Fold 2 IBS: 0.1953302966937715
Fold 3 IBS: 0.20032164245764747
Fold 4 IBS: 0.20925262287388577
Fold 5 IBS: 0.20024473686300104
[I 2024-04-16 20:20:43,774] Trial 31 finished with value: 0.20558606466925783 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 246, 'oob_score': True, 'max_samples': 0.15268111765956288, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04969909669290266}. Best is trial 28 with value: 0.1957081731952507.

Fold 1 IBS: 0.21696087705123832
Fold 2 IBS: 0.18051846494326523
Fold 3 IBS: 0.19858268230981502
Fold 4 IBS: 0.19548842415207185
Fold 5 IBS: 0.1939615595663194
[I 2024-04-16 20:20:45,275] Trial 32 finished with value: 0.19710240160454198 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 242, 'oob_score': True, 'max_samples': 0.24335177937454738, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0403634329485552}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.22607044337199272
Fold 2 IBS: 0.19854056368445666
Fold 3 IBS: 0.2066706312720571
Fold 4 IBS: 0.2127158757656954
Fold 5 IBS: 0.20132348644962628
[I 2024-04-16 20:20:47,276] Trial 33 finished with value: 0.2090642001087656 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 308, 'oob_score': True, 'max_samples': 0.2205178594196074, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.036244051576231465}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.21750530318182348
Fold 2 IBS: 0.18918045173258685
Fold 3 IBS: 0.20031589048665507
Fold 4 IBS: 0.20247256069184819
Fold 5 IBS: 0.1952153770874812
[I 2024-04-16 20:20:49,270] Trial 34 finished with value: 0.20093791663607896 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 223, 'oob_score': True, 'max_samples': 0.3346755449746845, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09490412358837126}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.24854476172694717
Fold 2 IBS: 0.17489554412796285
Fold 3 IBS: 0.21833386821595754
Fold 4 IBS: 0.2028963609383431
Fold 5 IBS: 0.21048768441058666
[I 2024-04-16 20:20:52,701] Trial 35 finished with value: 0.21103164388395945 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.5033619047961488, 'max_features': None, 'min_weight_fraction_leaf': 0.05900534027408325}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.23229698798139803
Fold 2 IBS: 0.17436410438007208
Fold 3 IBS: 0.20069313377660525
Fold 4 IBS: 0.18806012012550025
Fold 5 IBS: 0.2014026587551303
[I 2024-04-16 20:20:55,231] Trial 36 finished with value: 0.19936340100374117 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 271, 'oob_score': True, 'max_samples': 0.6188610431913953, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02649818210751271}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.22030364296555408
Fold 2 IBS: 0.1805401596985861
Fold 3 IBS: 0.19838122426314858
Fold 4 IBS: 0.19421860320107534
Fold 5 IBS: 0.1938352824986055
[I 2024-04-16 20:20:56,980] Trial 37 finished with value: 0.19745578252539392 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 186, 'oob_score': True, 'max_samples': 0.4615372347574561, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0871084730300059}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.24668846098645317
Fold 2 IBS: 0.232261309490938
Fold 3 IBS: 0.22989383364191868
Fold 4 IBS: 0.24111307725231002
Fold 5 IBS: 0.23033424932668087
[I 2024-04-16 20:20:59,812] Trial 38 finished with value: 0.23605818613966015 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 299, 'oob_score': True, 'max_samples': 0.2962876784514671, 'max_features': None, 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.2254574063946436
Fold 2 IBS: 0.19933527677810936
Fold 3 IBS: 0.20925088085154536
Fold 4 IBS: 0.21444288705001782
Fold 5 IBS: 0.20470553067052022
[I 2024-04-16 20:21:02,344] Trial 39 finished with value: 0.21063839634896725 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 266, 'oob_score': True, 'max_samples': 0.1720359313861365, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06899292804891201}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.24401771794888427
Fold 2 IBS: 0.17308591965059672
Fold 3 IBS: 0.2170260725316364
Fold 4 IBS: 0.21909370935633762
Fold 5 IBS: 0.2174862688549036
[I 2024-04-16 20:21:04,129] Trial 40 finished with value: 0.21414193766847173 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 224, 'oob_score': True, 'max_samples': 0.5181938821717336, 'max_features': None, 'min_weight_fraction_leaf': 0.11012399275565876}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.21793961633123113
Fold 2 IBS: 0.17929970803523393
Fold 3 IBS: 0.19611410544242514
Fold 4 IBS: 0.19427082019698114
Fold 5 IBS: 0.1961404811509673
[I 2024-04-16 20:21:06,488] Trial 41 finished with value: 0.19675294623136771 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.2762197125581253, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.037684133891305927}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.22482978436164372
Fold 2 IBS: 0.17922044216185368
Fold 3 IBS: 0.1924822134727722
Fold 4 IBS: 0.19268618582931546
Fold 5 IBS: 0.1937086959480894
[I 2024-04-16 20:21:08,085] Trial 42 finished with value: 0.1965854643547349 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 201, 'oob_score': True, 'max_samples': 0.35411974100471344, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02908331763454295}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.24686392334609034
Fold 2 IBS: 0.23235685740999587
Fold 3 IBS: 0.22959308320810784
Fold 4 IBS: 0.24126492172417696
Fold 5 IBS: 0.23015020852832938
[I 2024-04-16 20:21:09,732] Trial 43 finished with value: 0.23604579884334007 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 202, 'oob_score': True, 'max_samples': 0.36202851108062717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.24647033075756955
Fold 2 IBS: 0.232206380853674
Fold 3 IBS: 0.2296752046557258
Fold 4 IBS: 0.24113331082803802
Fold 5 IBS: 0.23029553519409712
[I 2024-04-16 20:21:10,950] Trial 44 finished with value: 0.23595615245782092 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 156, 'oob_score': True, 'max_samples': 0.27782050221859245, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4341050766852402}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.2224720279945592
Fold 2 IBS: 0.1793425107773019
Fold 3 IBS: 0.195138803605169
Fold 4 IBS: 0.1923081372039151
Fold 5 IBS: 0.19382264263275412
[I 2024-04-16 20:21:11,895] Trial 45 finished with value: 0.19661682444273984 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.446962163236712, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.016578585102308162}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.217513372294539
Fold 2 IBS: 0.1810748574218823
Fold 3 IBS: 0.20013437706613885
Fold 4 IBS: 0.19814993119034283
Fold 5 IBS: 0.19328625902989183
[I 2024-04-16 20:21:12,802] Trial 46 finished with value: 0.19803175940055898 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 111, 'oob_score': True, 'max_samples': 0.4605070487447076, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.003285618803334946}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.2177738568530383
Fold 2 IBS: 0.18353184726579072
Fold 3 IBS: 0.19858223500797662
Fold 4 IBS: 0.19447349769516747
Fold 5 IBS: 0.19694030427326667
[I 2024-04-16 20:21:13,825] Trial 47 finished with value: 0.19826034821904798 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 125, 'oob_score': True, 'max_samples': 0.3614862445363626, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.023320840388323914}. Best is trial 28 with value: 0.1957081731952507.

Fold 1 IBS: 0.2227666955281551
Fold 2 IBS: 0.19165948973828925
Fold 3 IBS: 0.19545544746225493
Fold 4 IBS: 0.2051264434970915
Fold 5 IBS: 0.1988943998981424
[I 2024-04-16 20:21:14,403] Trial 48 finished with value: 0.20278049522478664 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 76, 'oob_score': True, 'max_samples': 0.3886019184666001, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06837241646154979}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.2329000315417291
Fold 2 IBS: 0.21266089545946018
Fold 3 IBS: 0.21523301311412954
Fold 4 IBS: 0.22365785685511483
Fold 5 IBS: 0.2105763226381107
[I 2024-04-16 20:21:15,765] Trial 49 finished with value: 0.21900562392170891 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 20, 'max_depth': 5, 'n_estimators': 187, 'oob_score': True, 'max_samples': 0.4696154766839547, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024088316670212995}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.2153002004812396
Fold 2 IBS: 0.18980244103670488
Fold 3 IBS: 0.19884280173330135
Fold 4 IBS: 0.20791145649965073
Fold 5 IBS: 0.19673639915478278
[I 2024-04-16 20:21:16,566] Trial 50 finished with value: 0.20171865978113587 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.3393887504143596, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1067722201468298}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.22387970281132383
Fold 2 IBS: 0.17689313965073344
Fold 3 IBS: 0.19509982018502095
Fold 4 IBS: 0.19069353286826382
Fold 5 IBS: 0.1967811867065249
[I 2024-04-16 20:21:19,001] Trial 51 finished with value: 0.19666947644437338 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 265, 'oob_score': True, 'max_samples': 0.5854912780883943, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0367459112428075}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.2217789090967994
Fold 2 IBS: 0.17634293865764214
Fold 3 IBS: 0.19841425809998925
Fold 4 IBS: 0.19088691535570335
Fold 5 IBS: 0.19521425707252416
[I 2024-04-16 20:21:20,813] Trial 52 finished with value: 0.19652745565653165 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.41264051301416904, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0028580892559701837}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.22576742546372566
Fold 2 IBS: 0.17420061928915054
Fold 3 IBS: 0.20025605249951328
Fold 4 IBS: 0.18911627355675306
Fold 5 IBS: 0.19849444251734566
[I 2024-04-16 20:21:23,108] Trial 53 finished with value: 0.19756696266529766 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.5563485288188155, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0018738129090539457}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.22135103721136293
Fold 2 IBS: 0.18704858404931116
Fold 3 IBS: 0.19896089069227468
Fold 4 IBS: 0.2013210991169169
Fold 5 IBS: 0.19826144847917412
[I 2024-04-16 20:21:25,760] Trial 54 finished with value: 0.20138861190980797 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.4201926857401609, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08255283895951362}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.21819876541007086
Fold 2 IBS: 0.18213113193221098
Fold 3 IBS: 0.19780528445048415
Fold 4 IBS: 0.19525304042429614
Fold 5 IBS: 0.1954376323954213
[I 2024-04-16 20:21:27,877] Trial 55 finished with value: 0.1977651709224967 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 198, 'oob_score': True, 'max_samples': 0.4972839143350145, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.019752280987738666}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.22879423263577645
Fold 2 IBS: 0.17061464366905144
Fold 3 IBS: 0.1979817006979473
Fold 4 IBS: 0.18865881523512773
Fold 5 IBS: 0.19643172955646357
[I 2024-04-16 20:21:29,672] Trial 56 finished with value: 0.19649622435887332 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 176, 'oob_score': True, 'max_samples': 0.6882525064531181, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06272940447711652}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.23687378121260508
Fold 2 IBS: 0.21558937039945297
Fold 3 IBS: 0.21396491422458466
Fold 4 IBS: 0.2270111799112219
Fold 5 IBS: 0.2098332610483187
[I 2024-04-16 20:21:31,186] Trial 57 finished with value: 0.22065450135923664 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 4, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.40679831402444333, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06863691556024365}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.21764180103179395
Fold 2 IBS: 0.18287049037438516
Fold 3 IBS: 0.22497694911521351
Fold 4 IBS: 0.21426609813131237
Fold 5 IBS: 0.21602354933161486
[I 2024-04-16 20:21:33,309] Trial 58 finished with value: 0.211155777596864 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 154, 'oob_score': True, 'max_samples': 0.3712600649081825, 'max_features': None, 'min_weight_fraction_leaf': 0.11938357844052232}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.21673352994088718
Fold 2 IBS: 0.1856201269955706
Fold 3 IBS: 0.2002185405683332
Fold 4 IBS: 0.20131095804030774
Fold 5 IBS: 0.19603502353275506
[I 2024-04-16 20:21:35,575] Trial 59 finished with value: 0.19998363581557074 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.706317491452594, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1724920317313142}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.22961441241583233
Fold 2 IBS: 0.17612339889225392
Fold 3 IBS: 0.2025997883937135
Fold 4 IBS: 0.18937528220789238
Fold 5 IBS: 0.1918892447719506
[I 2024-04-16 20:21:37,448] Trial 60 finished with value: 0.19792042533632853 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.44459741638472783, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.017555046425675864}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.22500029974654043
Fold 2 IBS: 0.17550644192443124
Fold 3 IBS: 0.19470410947021588
Fold 4 IBS: 0.19102120961406058
Fold 5 IBS: 0.1963235045479398
[I 2024-04-16 20:21:40,044] Trial 61 finished with value: 0.19651111306063757 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 265, 'oob_score': True, 'max_samples': 0.6337877482803385, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05194801721003342}. Best is trial 28 with value: 0.1957081731952507.
Fold 1 IBS: 0.224251142031788
Fold 2 IBS: 0.1724494721072299
Fold 3 IBS: 0.1970403240491892
Fold 4 IBS: 0.18857093397793814
Fold 5 IBS: 0.19536595905934825
[I 2024-04-16 20:21:42,754] Trial 62 finished with value: 0.19553556624509869 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.689383772643782, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04852874808590733}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22462451570538552
Fold 2 IBS: 0.17443456918114128
Fold 3 IBS: 0.20034203302033585
Fold 4 IBS: 0.18715719799378225
Fold 5 IBS: 0.19479941310406484
[I 2024-04-16 20:21:45,547] Trial 63 finished with value: 0.19627154580094194 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 223, 'oob_score': True, 'max_samples': 0.6382504492131043, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05547383035537368}. Best is trial 62 with value: 0.19553556624509869.

Fold 1 IBS: 0.22424195411650993
Fold 2 IBS: 0.1733452077865647
Fold 3 IBS: 0.1987495278992841
Fold 4 IBS: 0.18771842316860926
Fold 5 IBS: 0.19559796363556234
[I 2024-04-16 20:21:48,179] Trial 64 finished with value: 0.1959306153213061 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 224, 'oob_score': True, 'max_samples': 0.6854054895166218, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0574508751550857}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.21880885831421684
Fold 2 IBS: 0.1800713612968455
Fold 3 IBS: 0.19937666972389528
Fold 4 IBS: 0.1948820181683657
Fold 5 IBS: 0.19924258390235944
[I 2024-04-16 20:21:51,414] Trial 65 finished with value: 0.19847629828113655 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 282, 'oob_score': True, 'max_samples': 0.6872539783987465, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13515710653179946}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.2176623011814154
Fold 2 IBS: 0.18013567315879261
Fold 3 IBS: 0.19696621508230275
Fold 4 IBS: 0.1969498844889927
Fold 5 IBS: 0.1949055958385231
[I 2024-04-16 20:21:53,575] Trial 66 finished with value: 0.1973239339500053 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 178, 'oob_score': True, 'max_samples': 0.6382313863885496, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06157162161768737}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22211864494819247
Fold 2 IBS: 0.17718430280863043
Fold 3 IBS: 0.20048124228880193
Fold 4 IBS: 0.19233922566087577
Fold 5 IBS: 0.194740698590468
[I 2024-04-16 20:21:56,927] Trial 67 finished with value: 0.19737282285939375 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 258, 'oob_score': True, 'max_samples': 0.6561375454331035, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09437042274278865}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22549392665725407
Fold 2 IBS: 0.17392132537374835
Fold 3 IBS: 0.1990944159503999
Fold 4 IBS: 0.1888062071431616
Fold 5 IBS: 0.19773574124357168
[I 2024-04-16 20:21:59,141] Trial 68 finished with value: 0.1970103232736271 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.737865878749729, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07929972139426132}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.2211178875512389
Fold 2 IBS: 0.17843289212428712
Fold 3 IBS: 0.1977907112659428
Fold 4 IBS: 0.19350503716426232
Fold 5 IBS: 0.19933616231111284
[I 2024-04-16 20:22:01,328] Trial 69 finished with value: 0.1980365380833688 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 276, 'oob_score': True, 'max_samples': 0.5971951587348806, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.053553779545423896}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.21899449555892517
Fold 2 IBS: 0.19615933477140451
Fold 3 IBS: 0.200603176687677
Fold 4 IBS: 0.20743636339229984
Fold 5 IBS: 0.19938107212687792
[I 2024-04-16 20:22:03,216] Trial 70 finished with value: 0.2045148885074369 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.6863373588171012, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.23149218555433793}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22630325368775592
Fold 2 IBS: 0.1720215292962424
Fold 3 IBS: 0.1984905539029088
Fold 4 IBS: 0.18686815902590123
Fold 5 IBS: 0.1948275470676199
[I 2024-04-16 20:22:04,996] Trial 71 finished with value: 0.19570220859608564 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 213, 'oob_score': True, 'max_samples': 0.7138394785353019, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04879498500472522}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22646396565914925
Fold 2 IBS: 0.17219990486403383
Fold 3 IBS: 0.19992051314639406
Fold 4 IBS: 0.1875564350253358
Fold 5 IBS: 0.19570501626665565
[I 2024-04-16 20:22:06,802] Trial 72 finished with value: 0.19636916699231372 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.7313381528866988, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04789846128091917}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.2270969728435868
Fold 2 IBS: 0.17438006303989753
Fold 3 IBS: 0.1982704298229626
Fold 4 IBS: 0.18875167727653028
Fold 5 IBS: 0.19686414416314718
[I 2024-04-16 20:22:08,696] Trial 73 finished with value: 0.1970726574292249 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 209, 'oob_score': True, 'max_samples': 0.8533502736900729, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07167500860220864}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.2260637485161343
Fold 2 IBS: 0.1757609384035957
Fold 3 IBS: 0.19857024722694022
Fold 4 IBS: 0.1905844343122372
Fold 5 IBS: 0.1955579425444304
[I 2024-04-16 20:22:10,328] Trial 74 finished with value: 0.19730746220066758 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 190, 'oob_score': True, 'max_samples': 0.801828912161208, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10435587146022479}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.2214225808638586
Fold 2 IBS: 0.1764013955883307
Fold 3 IBS: 0.1979396832992639
Fold 4 IBS: 0.1948808592925685
Fold 5 IBS: 0.19521570974069108
[I 2024-04-16 20:22:12,204] Trial 75 finished with value: 0.19717204575694253 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 167, 'oob_score': True, 'max_samples': 0.7137642830680948, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.045941470231996594}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.2280242046090806
Fold 2 IBS: 0.20541638243483268
Fold 3 IBS: 0.20866142394794845
Fold 4 IBS: 0.217802490511081
Fold 5 IBS: 0.20537076520974526
[I 2024-04-16 20:22:14,194] Trial 76 finished with value: 0.21305505334253763 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 211, 'oob_score': True, 'max_samples': 0.744232322394408, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.32041444551979115}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.25660845586689124
Fold 2 IBS: 0.1836573335251637
Fold 3 IBS: 0.22836449063730882
Fold 4 IBS: 0.19646299265034597
Fold 5 IBS: 0.2132634402753012
[I 2024-04-16 20:22:16,536] Trial 77 finished with value: 0.21567134259100218 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 249, 'oob_score': True, 'max_samples': 0.7779579422426659, 'max_features': None, 'min_weight_fraction_leaf': 0.08281274341334385}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.2245307136002825
Fold 2 IBS: 0.18770968743332375
Fold 3 IBS: 0.19769177545801606
Fold 4 IBS: 0.20245762789691724
Fold 5 IBS: 0.1985047435804298
[I 2024-04-16 20:22:18,415] Trial 78 finished with value: 0.20217890959379387 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 222, 'oob_score': True, 'max_samples': 0.6972842584193659, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12387366686583999}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22699738865256627
Fold 2 IBS: 0.17187575923110934
Fold 3 IBS: 0.19988514762167126
Fold 4 IBS: 0.18748998178552767

Fold 5 IBS: 0.19489331507182253
[I 2024-04-16 20:22:20,221] Trial 79 finished with value: 0.1962283184725394 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 197, 'oob_score': True, 'max_samples': 0.7204334120135304, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06182087800738387}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.2215575415781244
Fold 2 IBS: 0.17551831064016074
Fold 3 IBS: 0.2003450191188829
Fold 4 IBS: 0.1893570876676837
Fold 5 IBS: 0.19512179731350374
[I 2024-04-16 20:22:22,576] Trial 80 finished with value: 0.19637995126367108 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 238, 'oob_score': True, 'max_samples': 0.660392551614857, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03604081814743047}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22275825379076
Fold 2 IBS: 0.17393253695007663
Fold 3 IBS: 0.19849601867837205
Fold 4 IBS: 0.18842207825227167
Fold 5 IBS: 0.19549950549740225
[I 2024-04-16 20:22:24,688] Trial 81 finished with value: 0.1958216786337765 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 237, 'oob_score': True, 'max_samples': 0.6674618322742394, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04052399148153969}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.24671838763541828
Fold 2 IBS: 0.23212692518894396
Fold 3 IBS: 0.22951195815805076
Fold 4 IBS: 0.2415247985851926
Fold 5 IBS: 0.23030738027311604
[I 2024-04-16 20:22:27,273] Trial 82 finished with value: 0.23603788996814434 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 204, 'oob_score': True, 'max_samples': 0.7329022639775774, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.37875540676023556}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.2223495383052312
Fold 2 IBS: 0.17892609362112982
Fold 3 IBS: 0.1977184666236955
Fold 4 IBS: 0.19401219325106425
Fold 5 IBS: 0.19583220122071107
[I 2024-04-16 20:22:29,093] Trial 83 finished with value: 0.19776769860436635 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 193, 'oob_score': True, 'max_samples': 0.6038209456551556, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04787957256878766}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.2257898854411691
Fold 2 IBS: 0.17421570462339156
Fold 3 IBS: 0.20171920798396012
Fold 4 IBS: 0.1864126436757337
Fold 5 IBS: 0.20004521364198724
[I 2024-04-16 20:22:31,207] Trial 84 finished with value: 0.19763653107324836 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 254, 'oob_score': True, 'max_samples': 0.5689248630294904, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.031559470971598634}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22632142337087569
Fold 2 IBS: 0.17512237896615096
Fold 3 IBS: 0.195866194537824
Fold 4 IBS: 0.18910843146788622
Fold 5 IBS: 0.19620009507921357
[I 2024-04-16 20:22:33,485] Trial 85 finished with value: 0.1965237046843901 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 214, 'oob_score': True, 'max_samples': 0.7804072204997599, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09515588781319095}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22563190460210672
Fold 2 IBS: 0.1760490779697624
Fold 3 IBS: 0.20033417644035525
Fold 4 IBS: 0.19120918230118245
Fold 5 IBS: 0.19618772050112698
[I 2024-04-16 20:22:37,337] Trial 86 finished with value: 0.19788241236290677 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 296, 'oob_score': True, 'max_samples': 0.6471280941405515, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014427003476889563}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22711085497710773
Fold 2 IBS: 0.17352940628818583
Fold 3 IBS: 0.20121570711800363
Fold 4 IBS: 0.18760032118229633
Fold 5 IBS: 0.20158051803344285
[I 2024-04-16 20:22:40,349] Trial 87 finished with value: 0.19820736151980728 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.8333469816259349, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05909485681539679}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.23079011135497285
Fold 2 IBS: 0.17288066311834152
Fold 3 IBS: 0.19844289119132622
Fold 4 IBS: 0.18606071474325836
Fold 5 IBS: 0.19399952384129493
[I 2024-04-16 20:22:42,014] Trial 88 finished with value: 0.19643478084983876 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 161, 'oob_score': False, 'max_samples': 0.7263559585164437, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03819795279295879}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22418752818425913
Fold 2 IBS: 0.17418629374527933
Fold 3 IBS: 0.20005638803114537
Fold 4 IBS: 0.19057258542448982
Fold 5 IBS: 0.1987536703799511
[I 2024-04-16 20:22:51,363] Trial 89 finished with value: 0.19755129315302494 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 464, 'oob_score': True, 'max_samples': 0.6721409819281476, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.079837761812237}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22124400799078184
Fold 2 IBS: 0.17771411035192813
Fold 3 IBS: 0.19900602162148298
Fold 4 IBS: 0.19461219286551987
Fold 5 IBS: 0.19834420389027055
[I 2024-04-16 20:22:58,539] Trial 90 finished with value: 0.19818410734399666 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 316, 'oob_score': True, 'max_samples': 0.6140706673919256, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01226744000278044}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22198827203120924
Fold 2 IBS: 0.17429161933137194
Fold 3 IBS: 0.19836060217661075
Fold 4 IBS: 0.18830479532408753
Fold 5 IBS: 0.19584811044546166
[I 2024-04-16 20:23:11,720] Trial 91 finished with value: 0.19575867986174822 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 238, 'oob_score': True, 'max_samples': 0.6687056137644221, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030515503277526664}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22743842167305234
Fold 2 IBS: 0.17695482102829851
Fold 3 IBS: 0.19880446860371798
Fold 4 IBS: 0.18797133912711178
Fold 5 IBS: 0.19815871091935341
[I 2024-04-16 20:23:22,843] Trial 92 finished with value: 0.19786555227030683 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 222, 'oob_score': True, 'max_samples': 0.7550788603038648, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04348587110349451}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.2228522863095777
Fold 2 IBS: 0.17301373141540916
Fold 3 IBS: 0.1992998517661519
Fold 4 IBS: 0.18769238838518093
Fold 5 IBS: 0.19616219884675637
[I 2024-04-16 20:23:28,210] Trial 93 finished with value: 0.1958040913446152 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 249, 'oob_score': True, 'max_samples': 0.7107113700808502, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.028443986613722088}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22453347980267724
Fold 2 IBS: 0.17366290008139224
Fold 3 IBS: 0.19814808681601062
Fold 4 IBS: 0.18431650218523352
Fold 5 IBS: 0.1979824610365913
[I 2024-04-16 20:23:31,961] Trial 94 finished with value: 0.195728685984381 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 257, 'oob_score': True, 'max_samples': 0.7100138371659813, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02907242215090756}. Best is trial 62 with value: 0.19553556624509869.

Fold 1 IBS: 0.22327215911654924
Fold 2 IBS: 0.17181605634099717
Fold 3 IBS: 0.19891371164541044
Fold 4 IBS: 0.18858035986472774
Fold 5 IBS: 0.19936010551066077
[I 2024-04-16 20:23:35,801] Trial 95 finished with value: 0.19638847849566907 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 276, 'oob_score': True, 'max_samples': 0.6710713752997685, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03072314044967749}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22416864686613788
Fold 2 IBS: 0.17494700128364413
Fold 3 IBS: 0.20002311392349784
Fold 4 IBS: 0.18561514214063585
Fold 5 IBS: 0.1983466242333223
[I 2024-04-16 20:23:39,146] Trial 96 finished with value: 0.1966201056894476 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 259, 'oob_score': True, 'max_samples': 0.7160954347987437, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.012340082750765223}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.22138508805952858
Fold 2 IBS: 0.17784960836917407
Fold 3 IBS: 0.19823327957407358
Fold 4 IBS: 0.19015473312514286
Fold 5 IBS: 0.1976583203337911
[I 2024-04-16 20:23:41,469] Trial 97 finished with value: 0.19705620589234205 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.5278853162017928, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02604372276746115}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.2589387148770239
Fold 2 IBS: 0.1806652968183402
Fold 3 IBS: 0.22831091951689433
Fold 4 IBS: 0.19793976651872397
Fold 5 IBS: 0.2155914390122715
[I 2024-04-16 20:23:45,692] Trial 98 finished with value: 0.2162892273486508 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 287, 'oob_score': True, 'max_samples': 0.7852107821300729, 'max_features': None, 'min_weight_fraction_leaf': 0.07110550569699323}. Best is trial 62 with value: 0.19553556624509869.
Fold 1 IBS: 0.24678475830212923
Fold 2 IBS: 0.23210769845440965
Fold 3 IBS: 0.2303412213989482
Fold 4 IBS: 0.2408887720772729
Fold 5 IBS: 0.22965252272664638
[I 2024-04-16 20:23:48,519] Trial 99 finished with value: 0.2359549945918813 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 270, 'oob_score': False, 'max_samples': 0.12206761171117411, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0007779321971163426}. Best is trial 62 with value: 0.19553556624509869.


* Best trial for IBS:
 FrozenTrial(number=62, state=TrialState.COMPLETE, values=[0.19553556624509869], datetime_start=datetime.datetime(2024, 4, 16, 20, 21, 40, 49589), datetime_complete=datetime.datetime(2024, 4, 16, 20, 21, 42, 753047), params={'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.689383772643782, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04852874808590733}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=62, value=None)


* Best Score for IBS:
 0.19553556624509869

In [58]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [59]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.805
train_ibs:  0.196

#### Test

In [60]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [61]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=7, max_leaf_nodes=9,
                     max_samples=0.8893723590453224, min_samples_split=11,
                     min_weight_fraction_leaf=0.029301059641382382,
                     n_estimators=299, random_state=123, warm_start=True)

test_cindex:  0.579

RandomSurvivalForest(max_depth=3, max_leaf_nodes=11,
                     max_samples=0.689383772643782, min_samples_leaf=7,
                     min_samples_split=14,
                     min_weight_fraction_leaf=0.04852874808590733,
                     n_estimators=230, oob_score=True, random_state=123)

test_ibs:  0.247

In [62]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [63]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [64]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:23:49,882] A new study created in memory with name: no-name-590d4d3c-fd15-410b-98ae-9e4ec2df1dfd

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:23:50,567] Trial 0 finished with value: 0.7350162387199729 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7350162387199729.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:23:52,235] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7350162387199729.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 20:23:55,821] Trial 2 finished with value: 0.7100090405671899 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7350162387199729.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 20:23:56,114] Trial 3 finished with value: 0.7115659357113122 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7350162387199729.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:23:57,347] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7350162387199729.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:23:58,879] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7350162387199729.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 20:23:59,847] Trial 6 finished with value: 0.7284503296740432 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7350162387199729.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.721030042918455
[I 2024-04-16 20:24:01,654] Trial 7 finished with value: 0.7275921468789786 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7350162387199729.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.7424892703862661
[I 2024-04-16 20:24:01,778] Trial 8 finished with value: 0.7240896313045253 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7350162387199729.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6918604651162791
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 20:24:05,911] Trial 9 finished with value: 0.6997484411344755 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7350162387199729.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:24:07,230] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7350162387199729.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7547528517110266
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 20:24:08,122] Trial 11 finished with value: 0.7228372914972458 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.7350162387199729.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7553648068669528
[I 2024-04-16 20:24:09,103] Trial 12 finished with value: 0.753153713469314 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.753153713469314.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7034883720930233
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 20:24:10,442] Trial 13 finished with value: 0.7248571633302027 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.753153713469314.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7073643410852714
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.703862660944206
[I 2024-04-16 20:24:11,487] Trial 14 finished with value: 0.7271863420837275 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.753153713469314.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6996124031007752
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 20:24:11,917] Trial 15 finished with value: 0.7224744706294337 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.753153713469314.

Fold 1 C-index: 0.6155378486055777
Fold 2 C-index: 0.6918604651162791
Fold 3 C-index: 0.7978723404255319
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7145922746781116
[I 2024-04-16 20:24:12,691] Trial 16 finished with value: 0.7069383652327806 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.753153713469314.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7073643410852714
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7547528517110266
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 20:24:13,146] Trial 17 finished with value: 0.7188242438851208 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.753153713469314.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:24:14,159] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.753153713469314.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7073643410852714
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 20:24:15,135] Trial 19 finished with value: 0.7279248825507161 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.753153713469314.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 20:24:15,239] Trial 20 finished with value: 0.6854964411223841 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.753153713469314.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 20:24:16,021] Trial 21 finished with value: 0.7292471424230472 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.753153713469314.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 20:24:16,683] Trial 22 finished with value: 0.7333284247420278 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.753153713469314.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 20:24:17,942] Trial 23 finished with value: 0.7630219866907638 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.7630219866907638.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7775665399239544
Fold 5 C-index: 0.703862660944206
[I 2024-04-16 20:24:19,871] Trial 24 finished with value: 0.7341253644778666 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 468, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7479661339947506, 'min_weight_fraction_leaf': 0.09384728704326059}. Best is trial 23 with value: 0.7630219866907638.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 20:24:20,604] Trial 25 finished with value: 0.7518715940648593 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8403486805338629, 'min_weight_fraction_leaf': 0.047956477383484165}. Best is trial 23 with value: 0.7630219866907638.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7253218884120172
[I 2024-04-16 20:24:23,387] Trial 26 finished with value: 0.7262085640197429 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 293, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9080689581951225, 'min_weight_fraction_leaf': 0.047587407578096305}. Best is trial 23 with value: 0.7630219866907638.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7547528517110266
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 20:24:24,133] Trial 27 finished with value: 0.7213302523540288 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8371227222322273, 'min_weight_fraction_leaf': 0.15579279440144034}. Best is trial 23 with value: 0.7630219866907638.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 20:24:25,163] Trial 28 finished with value: 0.7130835806254091 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 465, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9054396864116818, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.7630219866907638.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 20:24:26,024] Trial 29 finished with value: 0.7318438686697389 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 345, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7319717987943724, 'min_weight_fraction_leaf': 0.10380226349432521}. Best is trial 23 with value: 0.7630219866907638.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8422053231939164
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 20:24:26,494] Trial 30 finished with value: 0.77590596166559 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.07504341894083728}. Best is trial 30 with value: 0.77590596166559.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 20:24:27,091] Trial 31 finished with value: 0.8106224444505938 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8236838576576057, 'min_weight_fraction_leaf': 0.03249179180997831}. Best is trial 31 with value: 0.8106224444505938.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:24:27,569] Trial 32 finished with value: 0.8103871052445996 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9443878200613953, 'min_weight_fraction_leaf': 0.027416055450601745}. Best is trial 31 with value: 0.8106224444505938.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 20:24:27,983] Trial 33 finished with value: 0.7867275170107588 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 206, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9298270958993008, 'min_weight_fraction_leaf': 0.07444789834770839}. Best is trial 31 with value: 0.8106224444505938.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8422053231939164
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 20:24:28,397] Trial 34 finished with value: 0.7799189496300895 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 206, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.08308222275275509}. Best is trial 31 with value: 0.8106224444505938.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7775665399239544
Fold 5 C-index: 0.7339055793991416
[I 2024-04-16 20:24:29,002] Trial 35 finished with value: 0.7432563423132066 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 161, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9350366951971597, 'min_weight_fraction_leaf': 0.11802881514192083}. Best is trial 31 with value: 0.8106224444505938.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 20:24:30,559] Trial 36 finished with value: 0.7212476208017986 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 211, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.936140510899361, 'min_weight_fraction_leaf': 0.07561034338558603}. Best is trial 31 with value: 0.8106224444505938.
Fold 1 C-index: 0.6394422310756972
Fold 2 C-index: 0.6957364341085271
Fold 3 C-index: 0.8148936170212766
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6888412017167382
[I 2024-04-16 20:24:30,887] Trial 37 finished with value: 0.718353038989771 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 152, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.816223066281635, 'min_weight_fraction_leaf': 0.028128305729665185}. Best is trial 31 with value: 0.8106224444505938.
Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.6918604651162791
Fold 3 C-index: 0.8106382978723404
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 20:24:31,272] Trial 38 finished with value: 0.7104487488579871 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 173, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.48791124460782864, 'min_weight_fraction_leaf': 0.22752773294338688}. Best is trial 31 with value: 0.8106224444505938.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7034883720930233
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 20:24:32,502] Trial 39 finished with value: 0.7022441542177325 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 124, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9322259779119899, 'min_weight_fraction_leaf': 0.1306417196973839}. Best is trial 31 with value: 0.8106224444505938.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 20:24:32,979] Trial 40 finished with value: 0.7197830218379878 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 230, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7822399806135087, 'min_weight_fraction_leaf': 0.16441302808811303}. Best is trial 31 with value: 0.8106224444505938.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 20:24:33,567] Trial 41 finished with value: 0.788404301374768 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 281, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8662811880518684, 'min_weight_fraction_leaf': 0.06806651518168289}. Best is trial 31 with value: 0.8106224444505938.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.871244635193133
[I 2024-04-16 20:24:34,307] Trial 42 finished with value: 0.8284126877195248 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 295, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9472190426148268, 'min_weight_fraction_leaf': 0.024434089430187326}. Best is trial 42 with value: 0.8284126877195248.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8412017167381974
[I 2024-04-16 20:24:34,988] Trial 43 finished with value: 0.801550856991313 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 284, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8629344589062246, 'min_weight_fraction_leaf': 0.024055214828791686}. Best is trial 42 with value: 0.8284126877195248.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 20:24:35,567] Trial 44 finished with value: 0.7630544918341579 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 287, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8649193302049866, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 42 with value: 0.8284126877195248.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.871244635193133
[I 2024-04-16 20:24:36,222] Trial 45 finished with value: 0.826688941109396 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 284, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9984298442600046, 'min_weight_fraction_leaf': 0.022374165634060222}. Best is trial 42 with value: 0.8284126877195248.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.8669527896995708
[I 2024-04-16 20:24:36,847] Trial 46 finished with value: 0.8258669284859235 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 239, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9943766110167936, 'min_weight_fraction_leaf': 0.021162297830687564}. Best is trial 42 with value: 0.8284126877195248.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:24:38,702] Trial 47 finished with value: 0.7183172148353163 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 240, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.995985337375063, 'min_weight_fraction_leaf': 0.012962504297749795}. Best is trial 42 with value: 0.8284126877195248.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8412017167381974
[I 2024-04-16 20:24:39,489] Trial 48 finished with value: 0.7999572314933051 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 179, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.95684993224688, 'min_weight_fraction_leaf': 0.05267979036896688}. Best is trial 42 with value: 0.8284126877195248.
Fold 1 C-index: 0.6195219123505976
Fold 2 C-index: 0.7034883720930233
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7017167381974249
[I 2024-04-16 20:24:40,029] Trial 49 finished with value: 0.7110436166469698 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9632054367318283, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 42 with value: 0.8284126877195248.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7661596958174905
Fold 5 C-index: 0.721030042918455
[I 2024-04-16 20:24:40,599] Trial 50 finished with value: 0.7295802674671547 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 302, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9968184548206992, 'min_weight_fraction_leaf': 0.1127672567358647}. Best is trial 42 with value: 0.8284126877195248.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 20:24:41,140] Trial 51 finished with value: 0.7924134380074218 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3788165702714287, 'min_weight_fraction_leaf': 0.026040309700959052}. Best is trial 42 with value: 0.8284126877195248.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.871244635193133
[I 2024-04-16 20:24:42,148] Trial 52 finished with value: 0.8273123948451703 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 324, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8981006325450593, 'min_weight_fraction_leaf': 0.001728246405320745}. Best is trial 42 with value: 0.8284126877195248.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.9391634980988594
Fold 5 C-index: 0.8798283261802575
[I 2024-04-16 20:24:42,875] Trial 53 finished with value: 0.8346457685775684 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 322, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8984329851688493, 'min_weight_fraction_leaf': 0.0010312054923344999}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.935361216730038
Fold 5 C-index: 0.8755364806866953
[I 2024-04-16 20:24:43,550] Trial 54 finished with value: 0.8256818620420315 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 323, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9008927404431284, 'min_weight_fraction_leaf': 0.009041310354208444}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 20:24:44,150] Trial 55 finished with value: 0.8112669498727699 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9008565451842212, 'min_weight_fraction_leaf': 0.005006155780581138}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6195219123505976
Fold 2 C-index: 0.7034883720930233
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 20:24:44,799] Trial 56 finished with value: 0.7133552134489008 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 326, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7888259067335379, 'min_weight_fraction_leaf': 0.3230607190970375}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 20:24:45,412] Trial 57 finished with value: 0.7647129577495674 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 312, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9631574249727254, 'min_weight_fraction_leaf': 0.055993606276380725}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 20:24:46,162] Trial 58 finished with value: 0.7300439551720512 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 14, 'n_estimators': 347, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9988254762013485, 'min_weight_fraction_leaf': 0.01485421398071568}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.703862660944206
[I 2024-04-16 20:24:49,980] Trial 59 finished with value: 0.7154414737786453 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 381, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9029700015972615, 'min_weight_fraction_leaf': 5.332578809405519e-05}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 20:24:50,515] Trial 60 finished with value: 0.7267371888347942 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.18936305585490176, 'min_weight_fraction_leaf': 0.04465663742742738}. Best is trial 53 with value: 0.8346457685775684.

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 20:24:51,389] Trial 61 finished with value: 0.8088581931771582 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9064318255780021, 'min_weight_fraction_leaf': 0.00047658399092015066}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 20:24:52,317] Trial 62 finished with value: 0.8055231968714093 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 312, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8903065669259559, 'min_weight_fraction_leaf': 0.011549304263918102}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 20:24:53,687] Trial 63 finished with value: 0.7709935516836215 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 397, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9592677141384884, 'min_weight_fraction_leaf': 0.060419566644964874}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.703862660944206
[I 2024-04-16 20:24:54,606] Trial 64 finished with value: 0.7334981863970814 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 266, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.85605693686184, 'min_weight_fraction_leaf': 0.09421775637166263}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 20:24:55,655] Trial 65 finished with value: 0.756539676788153 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 348, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8056929496240546, 'min_weight_fraction_leaf': 0.04547368087765696}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:24:56,401] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 365, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9148000220858699, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 20:24:57,160] Trial 67 finished with value: 0.8041039214938397 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 326, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9723643763917946, 'min_weight_fraction_leaf': 0.01692353768746812}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8369098712446352
[I 2024-04-16 20:24:57,870] Trial 68 finished with value: 0.7996786708204636 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 300, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7562530054761669, 'min_weight_fraction_leaf': 0.03644822148641352}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8412017167381974
[I 2024-04-16 20:24:58,552] Trial 69 finished with value: 0.8014302071217667 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 272, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8822878763817784, 'min_weight_fraction_leaf': 0.013071597564410203}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8283261802575107
[I 2024-04-16 20:24:59,201] Trial 70 finished with value: 0.7982190177664222 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 302, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9169764237839448, 'min_weight_fraction_leaf': 0.062309635474311904}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 20:24:59,836] Trial 71 finished with value: 0.7998228352062823 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 244, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8162706320837895, 'min_weight_fraction_leaf': 0.04091010771889886}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.8412017167381974
[I 2024-04-16 20:25:00,777] Trial 72 finished with value: 0.8038463960731385 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 188, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8381139152846885, 'min_weight_fraction_leaf': 0.0007512561356028888}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8369098712446352
[I 2024-04-16 20:25:01,366] Trial 73 finished with value: 0.8007467389733838 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 231, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6383145217663746, 'min_weight_fraction_leaf': 0.03112338964449133}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8106382978723404
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 20:25:02,220] Trial 74 finished with value: 0.718735214869527 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 335, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9522914331767875, 'min_weight_fraction_leaf': 0.28825667881199585}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:25:02,811] Trial 75 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 262, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5929773161110014, 'min_weight_fraction_leaf': 0.38708248744169227}. Best is trial 53 with value: 0.8346457685775684.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7661596958174905
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 20:25:07,123] Trial 76 finished with value: 0.7146852926797831 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 317, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8215042689122048, 'min_weight_fraction_leaf': 0.037687512779379005}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:25:07,995] Trial 77 finished with value: 0.7366531021190896 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 356, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7022478175691036, 'min_weight_fraction_leaf': 0.08275928141240774}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 20:25:08,882] Trial 78 finished with value: 0.7812966148387781 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 293, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8877523732883843, 'min_weight_fraction_leaf': 0.02077446558681443}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8369098712446352
[I 2024-04-16 20:25:10,971] Trial 79 finished with value: 0.7967337674431458 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9743522481362327, 'min_weight_fraction_leaf': 0.05779293939241043}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 20:25:11,687] Trial 80 finished with value: 0.7929675721416329 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 228, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5095861562397511, 'min_weight_fraction_leaf': 0.03419285446684074}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:25:12,203] Trial 81 finished with value: 0.8127738191466006 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 190, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9429392420417135, 'min_weight_fraction_leaf': 0.017007422350542367}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:25:12,746] Trial 82 finished with value: 0.8064431223198302 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 129, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9359915491588569, 'min_weight_fraction_leaf': 0.0129530754182389}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.871244635193133
[I 2024-04-16 20:25:13,417] Trial 83 finished with value: 0.8260949624229923 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 193, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9200250656316803, 'min_weight_fraction_leaf': 0.02110588195495102}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.935361216730038
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 20:25:13,934] Trial 84 finished with value: 0.8223858120282278 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 150, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9819084190254119, 'min_weight_fraction_leaf': 0.00027845609942071803}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.8669527896995708
[I 2024-04-16 20:25:14,438] Trial 85 finished with value: 0.8267653619706248 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 197, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9804328336682242, 'min_weight_fraction_leaf': 0.018613973247952394}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8283261802575107
[I 2024-04-16 20:25:14,826] Trial 86 finished with value: 0.7967560806446878 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 149, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9810988712066354, 'min_weight_fraction_leaf': 0.06846225677255877}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 20:25:15,082] Trial 87 finished with value: 0.8070452439472431 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 50, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9775493113834515, 'min_weight_fraction_leaf': 0.050217698471732956}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 20:25:16,164] Trial 88 finished with value: 0.7181696065264467 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 100, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9200910634951033, 'min_weight_fraction_leaf': 0.0240276900245316}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 20:25:16,649] Trial 89 finished with value: 0.7797704797752872 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 165, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9979975876472696, 'min_weight_fraction_leaf': 0.09218656216568451}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 20:25:17,007] Trial 90 finished with value: 0.7619168513773548 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 136, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9540128371203678, 'min_weight_fraction_leaf': 0.038024395705629405}. Best is trial 53 with value: 0.8346457685775684.

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:25:17,467] Trial 91 finished with value: 0.8128101756218404 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 192, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.941852157056118, 'min_weight_fraction_leaf': 0.017371663923730164}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 20:25:17,947] Trial 92 finished with value: 0.8194925699149879 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 195, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9209548088430017, 'min_weight_fraction_leaf': 0.00966791516546487}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 20:25:18,281] Trial 93 finished with value: 0.8209920069330586 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 102, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8552357750831439, 'min_weight_fraction_leaf': 0.007947675031673557}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8326180257510729
[I 2024-04-16 20:25:18,562] Trial 94 finished with value: 0.8029728656066843 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 64, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8526159461543885, 'min_weight_fraction_leaf': 0.028210209056922803}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9315589353612167
Fold 5 C-index: 0.871244635193133
[I 2024-04-16 20:25:18,906] Trial 95 finished with value: 0.8338528071604102 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 103, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8772063791914861, 'min_weight_fraction_leaf': 0.0017716238828261732}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 20:25:19,264] Trial 96 finished with value: 0.79085187737549 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 81, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8787645966935116, 'min_weight_fraction_leaf': 0.04901593285729107}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:25:19,595] Trial 97 finished with value: 0.8041006209918852 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 115, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.97255654335083, 'min_weight_fraction_leaf': 0.003275940625582616}. Best is trial 53 with value: 0.8346457685775684.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 20:25:20,124] Trial 98 finished with value: 0.7333722134730275 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 222, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8952374324597538, 'min_weight_fraction_leaf': 0.025928338255348883}. Best is trial 53 with value: 0.8346457685775684.

[I 2024-04-16 20:25:20,511] A new study created in memory with name: no-name-41a74a0d-9fca-4b89-a66b-95f9def52e69

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.785171102661597
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 20:25:20,497] Trial 99 finished with value: 0.7373263870682986 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 164, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9976780640499923, 'min_weight_fraction_leaf': 0.06858821562424904}. Best is trial 53 with value: 0.8346457685775684.


* Best trial for C-index:
 FrozenTrial(number=53, state=TrialState.COMPLETE, values=[0.8346457685775684], datetime_start=datetime.datetime(2024, 4, 16, 20, 24, 42, 154926), datetime_complete=datetime.datetime(2024, 4, 16, 20, 24, 42, 874287), params={'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 322, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8984329851688493, 'min_weight_fraction_leaf': 0.0010312054923344999}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=53, value=None)


* Best Score for C-index:
 0.8346457685775684

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.22726333663078643
Fold 2 IBS: 0.20420639878039942
Fold 3 IBS: 0.19393655250118852
Fold 4 IBS: 0.20858696885120717
Fold 5 IBS: 0.19719102551213896
[I 2024-04-16 20:25:23,184] Trial 0 finished with value: 0.20623685645514409 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.20623685645514409.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-16 20:25:27,596] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.20623685645514409.
Fold 1 IBS: 0.23522274011387503
Fold 2 IBS: 0.21516010346909592
Fold 3 IBS: 0.20790195836434527
Fold 4 IBS: 0.2237724885581968
Fold 5 IBS: 0.21113475310930832
[I 2024-04-16 20:25:31,683] Trial 2 finished with value: 0.2186384087229643 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.20623685645514409.
Fold 1 IBS: 0.23894315030323857
Fold 2 IBS: 0.21550554322237145
Fold 3 IBS: 0.20874456705228142
Fold 4 IBS: 0.2260002013731439
Fold 5 IBS: 0.21236671207749172
[I 2024-04-16 20:25:32,698] Trial 3 finished with value: 0.2203120348057054 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.20623685645514409.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-16 20:25:35,118] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.20623685645514409.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-16 20:25:36,412] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.20623685645514409.
Fold 1 IBS: 0.22693409842540993
Fold 2 IBS: 0.2063474460192293
Fold 3 IBS: 0.1942705587350472
Fold 4 IBS: 0.21027011722576705
Fold 5 IBS: 0.19756281265292247
[I 2024-04-16 20:25:39,651] Trial 6 finished with value: 0.20707700661167522 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.20623685645514409.
Fold 1 IBS: 0.23382221631859426
Fold 2 IBS: 0.20282054856624102
Fold 3 IBS: 0.2025766290240923
Fold 4 IBS: 0.21357560232070857
Fold 5 IBS: 0.1994478098476711
[I 2024-04-16 20:25:41,523] Trial 7 finished with value: 0.21044856121546146 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.20623685645514409.
Fold 1 IBS: 0.23871097231974225
Fold 2 IBS: 0.21148350271911914
Fold 3 IBS: 0.21030694898753644
Fold 4 IBS: 0.22291701772987896
Fold 5 IBS: 0.21057577947290923
[I 2024-04-16 20:25:42,208] Trial 8 finished with value: 0.2187988442458372 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.20623685645514409.
Fold 1 IBS: 0.23768191925967555
Fold 2 IBS: 0.22280579840467496
Fold 3 IBS: 0.21547915915634958
Fold 4 IBS: 0.23213572839335642
Fold 5 IBS: 0.21857193921430176
[I 2024-04-16 20:25:49,968] Trial 9 finished with value: 0.22533490888567168 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.20623685645514409.
Fold 1 IBS: 0.24672496618607107
Fold 2 IBS: 0.23224650601788785
Fold 3 IBS: 0.23004987749916536
Fold 4 IBS: 0.2412296281450331
Fold 5 IBS: 0.23015666331663637
[I 2024-04-16 20:25:55,197] Trial 10 finished with value: 0.23608152823295875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.20623685645514409.
Fold 1 IBS: 0.23107189692699442
Fold 2 IBS: 0.21357436254060172
Fold 3 IBS: 0.2034310195710483
Fold 4 IBS: 0.220483111772843
Fold 5 IBS: 0.20853655114137268
[I 2024-04-16 20:25:58,862] Trial 11 finished with value: 0.215419388390572 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.20623685645514409.
Fold 1 IBS: 0.22766425665737872
Fold 2 IBS: 0.19982377644357147
Fold 3 IBS: 0.1903129391575444
Fold 4 IBS: 0.2015867967307079
Fold 5 IBS: 0.191108129653369
[I 2024-04-16 20:26:03,335] Trial 12 finished with value: 0.20209917972851432 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.23027753987776614
Fold 2 IBS: 0.21072522127288565
Fold 3 IBS: 0.1974996198453701
Fold 4 IBS: 0.2180027932725221
Fold 5 IBS: 0.2041981309114328
[I 2024-04-16 20:26:07,955] Trial 13 finished with value: 0.21214066103599533 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.23060143959102872
Fold 2 IBS: 0.21210772405193815
Fold 3 IBS: 0.19966927284775476
Fold 4 IBS: 0.22042147986253144
Fold 5 IBS: 0.20572644900690068
[I 2024-04-16 20:26:11,597] Trial 14 finished with value: 0.21370527307203074 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.20209917972851432.

Fold 1 IBS: 0.23099085523394208
Fold 2 IBS: 0.21119014883602014
Fold 3 IBS: 0.20053080197163506
Fold 4 IBS: 0.2199439215088582
Fold 5 IBS: 0.20504248093236174
[I 2024-04-16 20:26:13,912] Trial 15 finished with value: 0.21353964169656345 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.2419422713253944
Fold 2 IBS: 0.22566663395847075
Fold 3 IBS: 0.22020955325969627
Fold 4 IBS: 0.2370945394616854
Fold 5 IBS: 0.22155508336351865
[I 2024-04-16 20:26:18,074] Trial 16 finished with value: 0.2292936162737531 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.23105092935662366
Fold 2 IBS: 0.21622625004489007
Fold 3 IBS: 0.19653722406368648
Fold 4 IBS: 0.22033324408010915
Fold 5 IBS: 0.20117731567705602
[I 2024-04-16 20:26:20,910] Trial 17 finished with value: 0.21306499264447307 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.24679929991389535
Fold 2 IBS: 0.23208761806557146
Fold 3 IBS: 0.2295482436451861
Fold 4 IBS: 0.24111555931482462
Fold 5 IBS: 0.22939893490285035
[I 2024-04-16 20:26:22,045] Trial 18 finished with value: 0.23578993116846556 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.23038126712712734
Fold 2 IBS: 0.21059363268542494
Fold 3 IBS: 0.1988529850164077
Fold 4 IBS: 0.21864436031461532
Fold 5 IBS: 0.20412676643942085
[I 2024-04-16 20:26:25,214] Trial 19 finished with value: 0.21251980231659923 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.23665088334113835
Fold 2 IBS: 0.2247788859540599
Fold 3 IBS: 0.20743581620925808
Fold 4 IBS: 0.23046069215376394
Fold 5 IBS: 0.2216657760455366
[I 2024-04-16 20:26:25,465] Trial 20 finished with value: 0.22419841074075136 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.22705675535695352
Fold 2 IBS: 0.20646640601959593
Fold 3 IBS: 0.19459504778319872
Fold 4 IBS: 0.21035024053687512
Fold 5 IBS: 0.19791906158490213
[I 2024-04-16 20:26:28,847] Trial 21 finished with value: 0.2072775022563051 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.22634646231406513
Fold 2 IBS: 0.20754300639944293
Fold 3 IBS: 0.19457066065993794
Fold 4 IBS: 0.2104306212877833
Fold 5 IBS: 0.1976405551375637
[I 2024-04-16 20:26:31,563] Trial 22 finished with value: 0.20730626115975861 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4780520239555279, 'min_weight_fraction_leaf': 0.01760516455314039}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.22687599210332582
Fold 2 IBS: 0.2050919530428643
Fold 3 IBS: 0.1935657371770361
Fold 4 IBS: 0.2091955517406826
Fold 5 IBS: 0.19702599289589223
[I 2024-04-16 20:26:34,959] Trial 23 finished with value: 0.2063510453919602 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6423644985218102, 'min_weight_fraction_leaf': 0.07933617912675625}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.22709868466649616
Fold 2 IBS: 0.20467329118721658
Fold 3 IBS: 0.1937065027439534
Fold 4 IBS: 0.20902338723180766
Fold 5 IBS: 0.1978179207194132
[I 2024-04-16 20:26:37,495] Trial 24 finished with value: 0.20646395730977743 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 361, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7479661339947506, 'min_weight_fraction_leaf': 0.09384728704326059}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.23439061002604408
Fold 2 IBS: 0.20579512928450833
Fold 3 IBS: 0.20277658366798326
Fold 4 IBS: 0.2161941910902373
Fold 5 IBS: 0.20227286419828153
[I 2024-04-16 20:26:39,944] Trial 25 finished with value: 0.2122858756534109 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.047956477383484165}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.22931016126677914
Fold 2 IBS: 0.2110556512026802
Fold 3 IBS: 0.1980475527673658
Fold 4 IBS: 0.21707375996432643
Fold 5 IBS: 0.2037531130644041
[I 2024-04-16 20:26:44,016] Trial 26 finished with value: 0.21184804765311113 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 405, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8454924050883471, 'min_weight_fraction_leaf': 0.16863579271898874}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.23070170795505465
Fold 2 IBS: 0.21368844382793264
Fold 3 IBS: 0.20139525269095607
Fold 4 IBS: 0.22232703281704042
Fold 5 IBS: 0.20819139830128802
[I 2024-04-16 20:26:45,428] Trial 27 finished with value: 0.21526076711845438 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9296679330104113, 'min_weight_fraction_leaf': 0.24207301181705376}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.2303719789985383
Fold 2 IBS: 0.21946961414464153
Fold 3 IBS: 0.19798471523921043
Fold 4 IBS: 0.2222257131099442
Fold 5 IBS: 0.20132274154417665
[I 2024-04-16 20:26:48,212] Trial 28 finished with value: 0.21427495260730223 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7294475749114913, 'min_weight_fraction_leaf': 0.10561943508937117}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.23638485025551806
Fold 2 IBS: 0.217212004717022
Fold 3 IBS: 0.2010174291852089
Fold 4 IBS: 0.22710240397469977
Fold 5 IBS: 0.21390984205920294
[I 2024-04-16 20:26:51,350] Trial 29 finished with value: 0.21912530603833033 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 351, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5014355663623529, 'min_weight_fraction_leaf': 0.23367475592947387}. Best is trial 12 with value: 0.20209917972851432.

Fold 1 IBS: 0.23023776941861945
Fold 2 IBS: 0.213511288827196
Fold 3 IBS: 0.20032100930462735
Fold 4 IBS: 0.21902572357015324
Fold 5 IBS: 0.20678699212033239
[I 2024-04-16 20:26:56,982] Trial 30 finished with value: 0.2139765566481857 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 457, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3838693489032564, 'min_weight_fraction_leaf': 0.03868084640768137}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.22785913525596427
Fold 2 IBS: 0.20385621569535622
Fold 3 IBS: 0.19317864058913928
Fold 4 IBS: 0.20830386583117433
Fold 5 IBS: 0.19648625224253355
[I 2024-04-16 20:27:01,884] Trial 31 finished with value: 0.20593682192283352 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7359152304070016, 'min_weight_fraction_leaf': 0.08655997300539783}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.2272845139357425
Fold 2 IBS: 0.20523752336583997
Fold 3 IBS: 0.19355573654562025
Fold 4 IBS: 0.20984653376612813
Fold 5 IBS: 0.19734426977657477
[I 2024-04-16 20:27:07,231] Trial 32 finished with value: 0.20665371547798114 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 411, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.618283894727248, 'min_weight_fraction_leaf': 0.07716716290582956}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.2359668650160156
Fold 2 IBS: 0.21497044130847268
Fold 3 IBS: 0.20902077010310943
Fold 4 IBS: 0.22425426834341505
Fold 5 IBS: 0.21122918955042164
[I 2024-04-16 20:27:14,862] Trial 33 finished with value: 0.21908830686428687 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 395, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8125920153130402, 'min_weight_fraction_leaf': 0.12995854366525855}. Best is trial 12 with value: 0.20209917972851432.
Fold 1 IBS: 0.2284156964355085
Fold 2 IBS: 0.19627836259730908
Fold 3 IBS: 0.18856857186511872
Fold 4 IBS: 0.20393985166064643
Fold 5 IBS: 0.18957225618999377
[I 2024-04-16 20:27:18,049] Trial 34 finished with value: 0.20135494774971532 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 300, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6862833758870215, 'min_weight_fraction_leaf': 0.03963928663346105}. Best is trial 34 with value: 0.20135494774971532.
Fold 1 IBS: 0.22921744185487292
Fold 2 IBS: 0.19579395252211176
Fold 3 IBS: 0.18710254206388566
Fold 4 IBS: 0.20294244605210798
Fold 5 IBS: 0.18611971614233042
[I 2024-04-16 20:27:21,714] Trial 35 finished with value: 0.20023521972706174 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 285, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7219903277747529, 'min_weight_fraction_leaf': 0.02820934588758598}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.23219880511151064
Fold 2 IBS: 0.1943507136844928
Fold 3 IBS: 0.18615367067816568
Fold 4 IBS: 0.2052926198039454
Fold 5 IBS: 0.18738654550511274
[I 2024-04-16 20:27:24,285] Trial 36 finished with value: 0.20107647095664544 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 222, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7254428448400148, 'min_weight_fraction_leaf': 0.033894921765957445}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.2326474385752269
Fold 2 IBS: 0.19439989919783232
Fold 3 IBS: 0.1860655527819328
Fold 4 IBS: 0.20589163678138767
Fold 5 IBS: 0.18825034392944143
[I 2024-04-16 20:27:26,759] Trial 37 finished with value: 0.20145097425316422 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 209, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6975546912981953, 'min_weight_fraction_leaf': 0.030440421568832744}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.2313186401111735
Fold 2 IBS: 0.19651788707273113
Fold 3 IBS: 0.18764284087849598
Fold 4 IBS: 0.20597153367228224
Fold 5 IBS: 0.1902046745254814
[I 2024-04-16 20:27:29,744] Trial 38 finished with value: 0.20233111525203284 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 214, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6653914327196222, 'min_weight_fraction_leaf': 0.04385319127058404}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.2370923160906493
Fold 2 IBS: 0.20482362017854028
Fold 3 IBS: 0.19999907208589882
Fold 4 IBS: 0.21611506650740303
Fold 5 IBS: 0.19955116934475106
[I 2024-04-16 20:27:32,798] Trial 39 finished with value: 0.2115162488414485 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 152, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.5209979873972976, 'min_weight_fraction_leaf': 0.032051064126489524}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.2300864520293982
Fold 2 IBS: 0.20746681231515002
Fold 3 IBS: 0.19400545873403816
Fold 4 IBS: 0.21602830990772842
Fold 5 IBS: 0.20141243510481885
[I 2024-04-16 20:27:36,485] Trial 40 finished with value: 0.20979989361822673 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 169, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7031549425639906, 'min_weight_fraction_leaf': 0.11728395495679868}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.23044515561008364
Fold 2 IBS: 0.19839156680041148
Fold 3 IBS: 0.1904164845113427
Fold 4 IBS: 0.2046302190556747
Fold 5 IBS: 0.19169585874534914
[I 2024-04-16 20:27:39,993] Trial 41 finished with value: 0.2031158569445723 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 233, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8167494567095457, 'min_weight_fraction_leaf': 0.05785299024344398}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.23006462076653844
Fold 2 IBS: 0.19524634190501836
Fold 3 IBS: 0.18721519580338886
Fold 4 IBS: 0.20490445049353753
Fold 5 IBS: 0.18786401520647192
[I 2024-04-16 20:27:42,872] Trial 42 finished with value: 0.20105892483499105 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 279, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.597620259089519, 'min_weight_fraction_leaf': 0.024027915311439926}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.2297468394311795
Fold 2 IBS: 0.19655538996807678
Fold 3 IBS: 0.18756687806080838
Fold 4 IBS: 0.20522659615465458
Fold 5 IBS: 0.1882977577692823
[I 2024-04-16 20:27:46,350] Trial 43 finished with value: 0.2014786922768003 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 284, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5999160200390568, 'min_weight_fraction_leaf': 0.025460784920656652}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.2362265962007559
Fold 2 IBS: 0.21206606880850032
Fold 3 IBS: 0.20733589241533637
Fold 4 IBS: 0.22100807306856066
Fold 5 IBS: 0.2081478210011161
[I 2024-04-16 20:27:49,645] Trial 44 finished with value: 0.21695689029885384 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 283, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5421218287934871, 'min_weight_fraction_leaf': 0.06481899794214628}. Best is trial 35 with value: 0.20023521972706174.

Fold 1 IBS: 0.23166436341307534
Fold 2 IBS: 0.1970282792781475
Fold 3 IBS: 0.18846658654338827
Fold 4 IBS: 0.2040824853956187
Fold 5 IBS: 0.18804555441980503
[I 2024-04-16 20:27:53,258] Trial 45 finished with value: 0.20185745381000694 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 239, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7884699835044351, 'min_weight_fraction_leaf': 0.02308271139521288}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.23259234371889384
Fold 2 IBS: 0.19671333504216923
Fold 3 IBS: 0.18808153790553353
Fold 4 IBS: 0.20560000019106228
Fold 5 IBS: 0.19051350976162718
[I 2024-04-16 20:27:55,908] Trial 46 finished with value: 0.20270014532385722 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 166, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.721983409821092, 'min_weight_fraction_leaf': 0.05113898389270553}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.23462232941151187
Fold 2 IBS: 0.2210240353902817
Fold 3 IBS: 0.2088420795692477
Fold 4 IBS: 0.23007125155137625
Fold 5 IBS: 0.21517498781019412
[I 2024-04-16 20:27:58,284] Trial 47 finished with value: 0.22194693674652233 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 190, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.42407998385661483, 'min_weight_fraction_leaf': 0.1625947698183845}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.24654888057856317
Fold 2 IBS: 0.23224599406343366
Fold 3 IBS: 0.22953488983838657
Fold 4 IBS: 0.24140007589572157
Fold 5 IBS: 0.23026882306655047
[I 2024-04-16 20:28:04,216] Trial 48 finished with value: 0.23599973268853108 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 307, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.555402690777645, 'min_weight_fraction_leaf': 0.3098199009921797}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.2466876101259161
Fold 2 IBS: 0.23213866379618514
Fold 3 IBS: 0.22952299838126303
Fold 4 IBS: 0.24153976875457864
Fold 5 IBS: 0.2302724122274235
[I 2024-04-16 20:28:09,580] Trial 49 finished with value: 0.23603229065707326 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 13, 'n_estimators': 268, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7624515768197179, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.2359539856541732
Fold 2 IBS: 0.19640947982453041
Fold 3 IBS: 0.1846432247904979
Fold 4 IBS: 0.20486500858493553
Fold 5 IBS: 0.18768993807137113
[I 2024-04-16 20:28:11,570] Trial 50 finished with value: 0.20191232738510162 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 131, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6525716962740098, 'min_weight_fraction_leaf': 0.003735729668167747}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.22964538887449826
Fold 2 IBS: 0.19622424885641904
Fold 3 IBS: 0.18680129427878484
Fold 4 IBS: 0.20502055930906296
Fold 5 IBS: 0.18866269511057918
[I 2024-04-16 20:28:14,435] Trial 51 finished with value: 0.20127083728586884 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 328, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5955261479749379, 'min_weight_fraction_leaf': 0.026069679633803584}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.22963081885535236
Fold 2 IBS: 0.19763933902667505
Fold 3 IBS: 0.18906741542386368
Fold 4 IBS: 0.2039264964316652
Fold 5 IBS: 0.18914996718407046
[I 2024-04-16 20:28:17,527] Trial 52 finished with value: 0.20188280738432535 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 327, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6184989118204166, 'min_weight_fraction_leaf': 0.029394240622110362}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.22996696340550415
Fold 2 IBS: 0.2005856045255914
Fold 3 IBS: 0.19062287297920696
Fold 4 IBS: 0.20710020218849573
Fold 5 IBS: 0.1944398212833525
[I 2024-04-16 20:28:19,646] Trial 53 finished with value: 0.20454309287643016 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 236, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6792702460427962, 'min_weight_fraction_leaf': 0.06862212558084059}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.22805817041723034
Fold 2 IBS: 0.20824607439965787
Fold 3 IBS: 0.196272705812451
Fold 4 IBS: 0.2157415205564656
Fold 5 IBS: 0.2019387855190448
[I 2024-04-16 20:28:23,507] Trial 54 finished with value: 0.21005145134096992 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 298, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5881880899958672, 'min_weight_fraction_leaf': 0.10406129559865943}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.23370567790276914
Fold 2 IBS: 0.20460274673374654
Fold 3 IBS: 0.2018732827072181
Fold 4 IBS: 0.2127539790686979
Fold 5 IBS: 0.19887602025179324
[I 2024-04-16 20:28:28,565] Trial 55 finished with value: 0.21036234133284495 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 345, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7036648796610401, 'min_weight_fraction_leaf': 0.018562911005901513}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.23051849621100295
Fold 2 IBS: 0.19744481389149082
Fold 3 IBS: 0.18823574179123395
Fold 4 IBS: 0.20142524315498267
Fold 5 IBS: 0.19001426569359872
[I 2024-04-16 20:28:31,726] Trial 56 finished with value: 0.20152771214846182 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 270, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7688232308168604, 'min_weight_fraction_leaf': 0.04818049607819711}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.22733566573945013
Fold 2 IBS: 0.20947454018628184
Fold 3 IBS: 0.19732847776776807
Fold 4 IBS: 0.21519915200166304
Fold 5 IBS: 0.20052251898155654
[I 2024-04-16 20:28:34,801] Trial 57 finished with value: 0.20997207093534392 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 252, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6174952267285679, 'min_weight_fraction_leaf': 0.015568016592661799}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.23089075324141448
Fold 2 IBS: 0.2120760756098424
Fold 3 IBS: 0.1995378965085781
Fold 4 IBS: 0.22059866283807036
Fold 5 IBS: 0.2054006781077247
[I 2024-04-16 20:28:37,633] Trial 58 finished with value: 0.213700813261126 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 188, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5389598332282572, 'min_weight_fraction_leaf': 0.11825056227123366}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.246593234506542
Fold 2 IBS: 0.2322454979233258
Fold 3 IBS: 0.2294001175041716
Fold 4 IBS: 0.24154547943172278
Fold 5 IBS: 0.23016004616993838
[I 2024-04-16 20:28:41,094] Trial 59 finished with value: 0.23598887510714012 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 223, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4628065260790761, 'min_weight_fraction_leaf': 0.3787205021140745}. Best is trial 35 with value: 0.20023521972706174.

Fold 1 IBS: 0.23218744117894213
Fold 2 IBS: 0.195817634720557
Fold 3 IBS: 0.1883733812292164
Fold 4 IBS: 0.20331460709002558
Fold 5 IBS: 0.18807061354020613
[I 2024-04-16 20:28:45,253] Trial 60 finished with value: 0.20155273555178943 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 332, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8377294618227489, 'min_weight_fraction_leaf': 0.0022038644175106023}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.2289831783698531
Fold 2 IBS: 0.1974503679208846
Fold 3 IBS: 0.18936728070713474
Fold 4 IBS: 0.20610193104790206
Fold 5 IBS: 0.18917988658494733
[I 2024-04-16 20:28:48,805] Trial 61 finished with value: 0.20221652892614433 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 277, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5830833411571541, 'min_weight_fraction_leaf': 0.030191587585166924}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.22817599910974767
Fold 2 IBS: 0.2013209019151451
Fold 3 IBS: 0.1899553268290837
Fold 4 IBS: 0.20751438731218833
Fold 5 IBS: 0.193243658792664
[I 2024-04-16 20:28:52,873] Trial 62 finished with value: 0.20404205479176576 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 310, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.623683602171795, 'min_weight_fraction_leaf': 0.06003367785416859}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.22866123862324858
Fold 2 IBS: 0.19857693626086306
Fold 3 IBS: 0.18926618081456273
Fold 4 IBS: 0.20750060528689568
Fold 5 IBS: 0.18895710562869655
[I 2024-04-16 20:28:56,425] Trial 63 finished with value: 0.2025924133228533 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 256, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5934955443956987, 'min_weight_fraction_leaf': 0.034410851572920176}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.22686726947774555
Fold 2 IBS: 0.2049761209743069
Fold 3 IBS: 0.19463389277011472
Fold 4 IBS: 0.21110839891232352
Fold 5 IBS: 0.19937680046405773
[I 2024-04-16 20:29:00,194] Trial 64 finished with value: 0.20739249651970967 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 292, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.669507019046537, 'min_weight_fraction_leaf': 0.09028356913738544}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.22809252640380376
Fold 2 IBS: 0.19939480814406935
Fold 3 IBS: 0.1914675366994108
Fold 4 IBS: 0.20465054516704623
Fold 5 IBS: 0.19163858872791484
[I 2024-04-16 20:29:04,863] Trial 65 finished with value: 0.20304880102844897 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 324, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7062363500067299, 'min_weight_fraction_leaf': 0.018671510169341956}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.24665093026646434
Fold 2 IBS: 0.23228120679329808
Fold 3 IBS: 0.2293918072467148
Fold 4 IBS: 0.24147197776316284
Fold 5 IBS: 0.2304738582357575
[I 2024-04-16 20:29:08,332] Trial 66 finished with value: 0.23605395606107954 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 245, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5051302167187507, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.22955779772621637
Fold 2 IBS: 0.20438705507659796
Fold 3 IBS: 0.19139000776884113
Fold 4 IBS: 0.21064840626216108
Fold 5 IBS: 0.1966716276380374
[I 2024-04-16 20:29:13,007] Trial 67 finished with value: 0.20653097889437083 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6418462812480262, 'min_weight_fraction_leaf': 0.07341581995765144}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.23013478844657356
Fold 2 IBS: 0.21200047378987238
Fold 3 IBS: 0.20129706471861336
Fold 4 IBS: 0.22029075359348202
Fold 5 IBS: 0.20649612410561982
[I 2024-04-16 20:29:18,483] Trial 68 finished with value: 0.21404384093083223 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 368, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.18504146569474889, 'min_weight_fraction_leaf': 0.04389083623494748}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.23239730125937724
Fold 2 IBS: 0.18828603317156434
Fold 3 IBS: 0.1980943249699332
Fold 4 IBS: 0.1984979944597933
Fold 5 IBS: 0.18946712448931688
[I 2024-04-16 20:29:21,635] Trial 69 finished with value: 0.201348555669997 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 342, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6797516614281078, 'min_weight_fraction_leaf': 0.016436675093167825}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.2306696718307236
Fold 2 IBS: 0.2185247407287407
Fold 3 IBS: 0.19799650736856134
Fold 4 IBS: 0.22181405057148826
Fold 5 IBS: 0.20150823471521206
[I 2024-04-16 20:29:25,743] Trial 70 finished with value: 0.21410264104294524 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 338, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7431851657851659, 'min_weight_fraction_leaf': 0.22065426841822414}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.2367483600571716
Fold 2 IBS: 0.1854205469135978
Fold 3 IBS: 0.19586131193043463
Fold 4 IBS: 0.19970764613066105
Fold 5 IBS: 0.1887082080870358
[I 2024-04-16 20:29:28,794] Trial 71 finished with value: 0.2012892146237802 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 306, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6808405757480631, 'min_weight_fraction_leaf': 0.015423959031535223}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.2334043057323136
Fold 2 IBS: 0.1880245325375413
Fold 3 IBS: 0.19589787536159634
Fold 4 IBS: 0.20147218442088577
Fold 5 IBS: 0.18922364179334064
[I 2024-04-16 20:29:31,839] Trial 72 finished with value: 0.20160450796913554 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 303, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.667157845822211, 'min_weight_fraction_leaf': 0.0009052543547795056}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.22964062535033372
Fold 2 IBS: 0.1895517391055209
Fold 3 IBS: 0.19398261964972882
Fold 4 IBS: 0.20378657710256748
Fold 5 IBS: 0.19132409452753057
[I 2024-04-16 20:29:34,905] Trial 73 finished with value: 0.2016571311471363 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 312, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7193494805573467, 'min_weight_fraction_leaf': 0.05088915701838995}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.23589335882869736
Fold 2 IBS: 0.18564330904753484
Fold 3 IBS: 0.19849850815979347
Fold 4 IBS: 0.19783360192973465
Fold 5 IBS: 0.18989712334829614
[I 2024-04-16 20:29:38,914] Trial 74 finished with value: 0.2015531802628113 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 358, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6848647893954268, 'min_weight_fraction_leaf': 0.016116408964858102}. Best is trial 35 with value: 0.20023521972706174.

Fold 1 IBS: 0.23325700465373614
Fold 2 IBS: 0.18941006365861973
Fold 3 IBS: 0.19777227345442108
Fold 4 IBS: 0.20367365815974922
Fold 5 IBS: 0.19257707911996447
[I 2024-04-16 20:29:41,410] Trial 75 finished with value: 0.20333801580929817 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 264, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7937577980359053, 'min_weight_fraction_leaf': 0.03875275975124326}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.23017168335686908
Fold 2 IBS: 0.1910769217553898
Fold 3 IBS: 0.19558186536350308
Fold 4 IBS: 0.19877865552249777
Fold 5 IBS: 0.1933197348980885
[I 2024-04-16 20:29:44,982] Trial 76 finished with value: 0.2017857721792696 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 350, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7531409318040957, 'min_weight_fraction_leaf': 0.0615095079009219}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.22754846915204194
Fold 2 IBS: 0.20004569494378804
Fold 3 IBS: 0.19653062369015603
Fold 4 IBS: 0.20606806297917862
Fold 5 IBS: 0.1948515997350992
[I 2024-04-16 20:29:49,523] Trial 77 finished with value: 0.20500889010005277 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 381, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.563154795085684, 'min_weight_fraction_leaf': 0.08121938108774102}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.23805897659835815
Fold 2 IBS: 0.21565329692864202
Fold 3 IBS: 0.2110050351134941
Fold 4 IBS: 0.22541498008099145
Fold 5 IBS: 0.21114999845407753
[I 2024-04-16 20:29:51,774] Trial 78 finished with value: 0.22025645743511263 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 215, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6878863980194042, 'min_weight_fraction_leaf': 0.09537068971624801}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.2329364159881226
Fold 2 IBS: 0.19547758363127585
Fold 3 IBS: 0.18932113057467384
Fold 4 IBS: 0.20415799381737906
Fold 5 IBS: 0.19039910959900772
[I 2024-04-16 20:29:56,109] Trial 79 finished with value: 0.2024584467220918 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 321, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6502743742393025, 'min_weight_fraction_leaf': 0.015456054929809573}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.23327547725518033
Fold 2 IBS: 0.2188169292971463
Fold 3 IBS: 0.20499833867520398
Fold 4 IBS: 0.22631466824965116
Fold 5 IBS: 0.21170052911203563
[I 2024-04-16 20:29:59,000] Trial 80 finished with value: 0.21902118851784352 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 225, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7215838770771842, 'min_weight_fraction_leaf': 0.2578980132057934}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.22870132277410526
Fold 2 IBS: 0.19814060118265472
Fold 3 IBS: 0.18890660759887695
Fold 4 IBS: 0.20576550719120815
Fold 5 IBS: 0.1891350538939281
[I 2024-04-16 20:30:03,016] Trial 81 finished with value: 0.20212981852815465 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 279, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5962291644376722, 'min_weight_fraction_leaf': 0.029252698232740806}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.22939865621517658
Fold 2 IBS: 0.19725943942756338
Fold 3 IBS: 0.18892498248998246
Fold 4 IBS: 0.20387200705918385
Fold 5 IBS: 0.1902524370249009
[I 2024-04-16 20:30:06,062] Trial 82 finished with value: 0.20194150444336145 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 288, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6268918786105491, 'min_weight_fraction_leaf': 0.03710518672213082}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.22820063063053922
Fold 2 IBS: 0.19431914072899176
Fold 3 IBS: 0.1950648975546584
Fold 4 IBS: 0.20402621531280493
Fold 5 IBS: 0.1934571091842334
[I 2024-04-16 20:30:08,456] Trial 83 finished with value: 0.20301359868224553 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 297, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5746441018674969, 'min_weight_fraction_leaf': 0.056113087023898875}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.23093982536428945
Fold 2 IBS: 0.1962470977953042
Fold 3 IBS: 0.18952049716446082
Fold 4 IBS: 0.20525747919942486
Fold 5 IBS: 0.18699617898656729
[I 2024-04-16 20:30:10,542] Trial 84 finished with value: 0.20179221570200934 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 250, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6065343258035076, 'min_weight_fraction_leaf': 0.009989575687200006}. Best is trial 35 with value: 0.20023521972706174.
Fold 1 IBS: 0.23289656081092014
Fold 2 IBS: 0.19350342980318863
Fold 3 IBS: 0.18840547770809457
Fold 4 IBS: 0.20083852354884263
Fold 5 IBS: 0.18518719787242016
[I 2024-04-16 20:30:13,309] Trial 85 finished with value: 0.2001662379486932 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 335, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7826055646036428, 'min_weight_fraction_leaf': 0.024017538629521877}. Best is trial 85 with value: 0.2001662379486932.
Fold 1 IBS: 0.23132308268936594
Fold 2 IBS: 0.1967460262158263
Fold 3 IBS: 0.18925018179974507
Fold 4 IBS: 0.20218610283280433
Fold 5 IBS: 0.18849930155752634
[I 2024-04-16 20:30:18,198] Trial 86 finished with value: 0.20160093901905357 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 344, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7694889965951872, 'min_weight_fraction_leaf': 0.0436694823463911}. Best is trial 85 with value: 0.2001662379486932.
Fold 1 IBS: 0.2313900105624617
Fold 2 IBS: 0.21352856949693175
Fold 3 IBS: 0.2018414407236506
Fold 4 IBS: 0.2217110387658538
Fold 5 IBS: 0.20629051820159824
[I 2024-04-16 20:30:22,358] Trial 87 finished with value: 0.2149523155500992 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 16, 'n_estimators': 371, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8165595429937568, 'min_weight_fraction_leaf': 0.07269336741508983}. Best is trial 85 with value: 0.2001662379486932.
Fold 1 IBS: 0.23353160387940405
Fold 2 IBS: 0.1928704629566503
Fold 3 IBS: 0.18822583429421014
Fold 4 IBS: 0.1987525558402159
Fold 5 IBS: 0.18395667903112767
[I 2024-04-16 20:30:26,503] Trial 88 finished with value: 0.1994674272003216 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 315, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8481286362392372, 'min_weight_fraction_leaf': 0.021089214181983423}. Best is trial 88 with value: 0.1994674272003216.
Fold 1 IBS: 0.2339682113185189
Fold 2 IBS: 0.1892156756800311
Fold 3 IBS: 0.19880522897958114
Fold 4 IBS: 0.19715625360283107
Fold 5 IBS: 0.19350622838896409
[I 2024-04-16 20:30:30,167] Trial 89 finished with value: 0.20253031959398524 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 317, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9215756271153378, 'min_weight_fraction_leaf': 0.0010679824351476751}. Best is trial 88 with value: 0.1994674272003216.

Fold 1 IBS: 0.23321083009190172
Fold 2 IBS: 0.19313426544526122
Fold 3 IBS: 0.1867653770716483
Fold 4 IBS: 0.19682621420661314
Fold 5 IBS: 0.1851399199104335
[I 2024-04-16 20:30:33,360] Trial 90 finished with value: 0.19901532134517158 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 300, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8499279955582367, 'min_weight_fraction_leaf': 0.022961915401987498}. Best is trial 90 with value: 0.19901532134517158.
Fold 1 IBS: 0.23178429607030182
Fold 2 IBS: 0.19405045604401192
Fold 3 IBS: 0.1863782097469378
Fold 4 IBS: 0.19756230007653738
Fold 5 IBS: 0.18523135334419819
[I 2024-04-16 20:30:36,679] Trial 91 finished with value: 0.19900132305639742 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8577916709081421, 'min_weight_fraction_leaf': 0.024195416081889975}. Best is trial 91 with value: 0.19900132305639742.
Fold 1 IBS: 0.23145154751359898
Fold 2 IBS: 0.19391722994868021
Fold 3 IBS: 0.18837226376469973
Fold 4 IBS: 0.1965609093790266
Fold 5 IBS: 0.1844908374784456
[I 2024-04-16 20:30:39,788] Trial 92 finished with value: 0.19895855761689024 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8605114309825739, 'min_weight_fraction_leaf': 0.026263027594593823}. Best is trial 92 with value: 0.19895855761689024.
Fold 1 IBS: 0.22963065874206584
Fold 2 IBS: 0.19581412593144762
Fold 3 IBS: 0.18882781770319046
Fold 4 IBS: 0.20097248768844664
Fold 5 IBS: 0.18863032905058652
[I 2024-04-16 20:30:43,488] Trial 93 finished with value: 0.2007750838231474 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 331, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8574799925354818, 'min_weight_fraction_leaf': 0.05315421693063238}. Best is trial 92 with value: 0.19895855761689024.
Fold 1 IBS: 0.2317626543166403
Fold 2 IBS: 0.1915013519887576
Fold 3 IBS: 0.18618433072569693
Fold 4 IBS: 0.19729461166111334
Fold 5 IBS: 0.18390442170276022
[I 2024-04-16 20:30:47,472] Trial 94 finished with value: 0.19812947407899367 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8714089894245162, 'min_weight_fraction_leaf': 0.025634903535808776}. Best is trial 94 with value: 0.19812947407899367.
Fold 1 IBS: 0.2280118906431732
Fold 2 IBS: 0.1982182039367578
Fold 3 IBS: 0.1909578486436887
Fold 4 IBS: 0.20083715500965169
Fold 5 IBS: 0.1906742995842916
[I 2024-04-16 20:30:50,765] Trial 95 finished with value: 0.20173987956351258 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 356, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8614304446417951, 'min_weight_fraction_leaf': 0.05561715946520421}. Best is trial 94 with value: 0.19812947407899367.
Fold 1 IBS: 0.23164986226708426
Fold 2 IBS: 0.21621087664295432
Fold 3 IBS: 0.20428261333461212
Fold 4 IBS: 0.22401174308716926
Fold 5 IBS: 0.20898186121887652
[I 2024-04-16 20:30:53,719] Trial 96 finished with value: 0.21702739131013932 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 18, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9065137606156981, 'min_weight_fraction_leaf': 0.06464631823085028}. Best is trial 94 with value: 0.19812947407899367.
Fold 1 IBS: 0.23408959637923824
Fold 2 IBS: 0.19144709170008894
Fold 3 IBS: 0.18655268441613046
Fold 4 IBS: 0.19525814848482517
Fold 5 IBS: 0.18443863403535027
[I 2024-04-16 20:30:56,782] Trial 97 finished with value: 0.1983572310031266 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 274, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8411269288995784, 'min_weight_fraction_leaf': 0.02544402057124564}. Best is trial 94 with value: 0.19812947407899367.
Fold 1 IBS: 0.23074435757350792
Fold 2 IBS: 0.194708477064389
Fold 3 IBS: 0.1870797159082396
Fold 4 IBS: 0.19727200894745536
Fold 5 IBS: 0.1874956419105481
[I 2024-04-16 20:31:02,375] Trial 98 finished with value: 0.199460040280828 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 391, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9550916619862787, 'min_weight_fraction_leaf': 0.05025932069885396}. Best is trial 94 with value: 0.19812947407899367.
Fold 1 IBS: 0.23075459525239328
Fold 2 IBS: 0.19476529121303152
Fold 3 IBS: 0.18705976937611826
Fold 4 IBS: 0.19727644362493713
Fold 5 IBS: 0.1875345397621382
[I 2024-04-16 20:31:06,730] Trial 99 finished with value: 0.19947812784572366 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 395, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9542283936173847, 'min_weight_fraction_leaf': 0.047791588383610764}. Best is trial 94 with value: 0.19812947407899367.


* Best trial for IBS:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.19812947407899367], datetime_start=datetime.datetime(2024, 4, 16, 20, 30, 43, 494444), datetime_complete=datetime.datetime(2024, 4, 16, 20, 30, 47, 469432), params={'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8714089894245162, 'min_weight_fraction_leaf': 0.025634903535808776}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=94, value=None)


* Best Score for IBS:
 0.19812947407899367

In [65]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [66]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.835
train_ibs:  0.198

#### Test

In [67]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [68]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=13, max_features=None, max_leaf_nodes=19,
                   max_samples=0.8984329851688493, min_samples_leaf=1,
                   min_samples_split=4,
                   min_weight_fraction_leaf=0.0010312054923344999,
                   n_estimators=322, random_state=123, warm_start=True)

C-index score: 0.581

ExtraSurvivalTrees(max_depth=19, max_features='log2', max_leaf_nodes=10,
                   max_samples=0.8714089894245162, min_samples_leaf=1,
                   min_samples_split=11,
                   min_weight_fraction_leaf=0.025634903535808776,
                   n_estimators=334, random_state=123, warm_start=True)

IBS: 0.234

In [69]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [70]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:31:08,599] A new study created in memory with name: no-name-f83deed5-a57c-4dfa-9c4f-a5f92db796b0

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:31:28,690] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:31:41,005] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:31:50,953] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:32:09,516] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:32:17,491] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:32:19,791] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:32:36,263] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:32:41,273] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:32:41,747] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6630901287553648
[I 2024-04-16 20:33:16,916] Trial 9 finished with value: 0.6963599701922215 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7306201550387597
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 20:34:22,388] Trial 10 finished with value: 0.67004015922662 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:35:47,923] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7693798449612403
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6888412017167382
[I 2024-04-16 20:37:20,812] Trial 12 finished with value: 0.6902397599863217 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.6963599701922215.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:37:48,880] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:38:28,094] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:39:01,531] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:39:29,302] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:40:21,922] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:41:43,086] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:41:45,849] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:42:14,365] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-16 20:43:10,485] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7151162790697675
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6437768240343348
[I 2024-04-16 20:44:05,310] Trial 22 finished with value: 0.6616369238370471 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:45:36,949] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:46:31,935] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:47:30,163] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:47:53,902] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:49:09,895] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:49:14,623] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:50:17,844] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:50:38,421] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.647410358565737
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 20:52:05,675] Trial 31 finished with value: 0.6067157957226358 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:53:51,527] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:55:30,926] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:56:47,111] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6888412017167382
[I 2024-04-16 20:57:30,211] Trial 35 finished with value: 0.6720678122425536 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:58:14,471] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:58:58,030] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:59:17,312] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:00:24,711] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:01:11,913] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.6553784860557769
Fold 2 C-index: 0.7034883720930233
Fold 3 C-index: 0.5297872340425532
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6330472103004292
[I 2024-04-16 21:02:36,102] Trial 41 finished with value: 0.6495874087873299 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:03:28,304] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:04:26,370] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:04:48,707] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:06:14,079] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 9 with value: 0.6963599701922215.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 21:06:23,061] Trial 46 finished with value: 0.7302327934888235 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:06:35,590] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.053196394932185635, 'dropout_rate': 0.70275818612764, 'n_estimators': 311, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7367392845248242, 'min_weight_fraction_leaf': 0.36842596123645754, 'max_features': 'log2', 'min_impurity_decrease': 2.2130001167649176e-06, 'validation_fraction': 0.8419754547666245, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:06:35,849] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9854905905033491, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.8195624802251275, 'n_estimators': 8, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.32965788605028784, 'max_features': 'log2', 'min_impurity_decrease': 1.2225255641975854e-06, 'validation_fraction': 0.8455422941346799, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:06:46,843] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7928982153787437, 'learning_rate': 0.0628925305235457, 'dropout_rate': 0.9570755199206264, 'n_estimators': 410, 'criterion': 'friedman_mse', 'ccp_alpha': 6.659192684443452, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'log2', 'min_impurity_decrease': 1.743578448308132e-07, 'validation_fraction': 0.42748211202843867, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:07:26,669] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8511494628607659, 'learning_rate': 0.04091234090749085, 'dropout_rate': 0.6291546211472798, 'n_estimators': 480, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3913441236862976, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'log2', 'min_impurity_decrease': 2.274738198457575e-05, 'validation_fraction': 0.5545404177484662, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 7}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.6792828685258964
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7042553191489361
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6888412017167382
[I 2024-04-16 21:07:59,741] Trial 51 finished with value: 0.7015392787095106 and parameters: {'subsample': 0.9115121046901732, 'learning_rate': 0.05845917620681425, 'dropout_rate': 0.5540004810661991, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04660345139175148, 'min_weight_fraction_leaf': 0.40812087314396844, 'max_features': 'sqrt', 'min_impurity_decrease': 7.767904466636394e-05, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:08:16,109] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9606972190963244, 'learning_rate': 0.058532095704419335, 'dropout_rate': 0.8655167247735727, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42267254326215464, 'min_weight_fraction_leaf': 0.35711614532127833, 'max_features': 'sqrt', 'min_impurity_decrease': 0.003049302929929116, 'validation_fraction': 0.985072081707868, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.6792828685258964
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7382978723404255
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.7060085836909872
[I 2024-04-16 21:08:51,898] Trial 53 finished with value: 0.7244319569325659 and parameters: {'subsample': 0.924085737836479, 'learning_rate': 0.05191355349770248, 'dropout_rate': 0.5292561748188663, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.009828495801242839, 'min_weight_fraction_leaf': 0.3940618917042797, 'max_features': 'sqrt', 'min_impurity_decrease': 5.891874821169929e-05, 'validation_fraction': 0.9257611975304009, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:09:29,196] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8842518374616221, 'learning_rate': 0.053258307688877335, 'dropout_rate': 0.5787056799551111, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 0.38565717736646804, 'min_weight_fraction_leaf': 0.39749144390795427, 'max_features': 'sqrt', 'min_impurity_decrease': 6.674900997744521e-05, 'validation_fraction': 0.8843751202328924, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:09:35,650] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.7287654482320323, 'learning_rate': 0.045017508094901654, 'dropout_rate': 0.8859792395781099, 'n_estimators': 289, 'criterion': 'squared_error', 'ccp_alpha': 0.7342456209458248, 'min_weight_fraction_leaf': 0.15390921956023235, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00018865565560969203, 'validation_fraction': 0.7838592561027189, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:10:12,116] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.23423646323682273, 'learning_rate': 0.07231303541927657, 'dropout_rate': 0.534386653988483, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 2.053064831619942, 'min_weight_fraction_leaf': 0.33405673650554374, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012611033221339828, 'validation_fraction': 0.6860217015765494, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.6713147410358565
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.785171102661597
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 21:10:17,922] Trial 57 finished with value: 0.7290532761071233 and parameters: {'subsample': 0.4065884568013973, 'learning_rate': 0.050487991666858245, 'dropout_rate': 0.997784793728882, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 0.001956726907500393, 'min_weight_fraction_leaf': 0.20436269339736532, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00033059213660683115, 'validation_fraction': 0.8254593382612642, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:10:23,261] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.3508301340402865, 'learning_rate': 0.09011651240953941, 'dropout_rate': 0.9967495872781945, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.1290450838056185, 'min_weight_fraction_leaf': 0.20680480896575482, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005537548403589421, 'validation_fraction': 0.8192112766928122, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:10:32,073] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.38439789354607845, 'learning_rate': 0.06139147262733905, 'dropout_rate': 0.9474892480356638, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.23145092940437437, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00021385037088054892, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:10:40,277] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.9260093630094106, 'learning_rate': 0.04877472827527357, 'dropout_rate': 0.9841116957888287, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.7893894780964769, 'min_weight_fraction_leaf': 0.18154324685428969, 'max_features': 'sqrt', 'min_impurity_decrease': 6.668735628479151e-05, 'validation_fraction': 0.6488296420582099, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 46 with value: 0.7302327934888235.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:10:50,097] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.8388194022639991, 'learning_rate': 0.05667950785553603, 'dropout_rate': 0.9141007682217919, 'n_estimators': 392, 'criterion': 'friedman_mse', 'ccp_alpha': 0.22684324682430845, 'min_weight_fraction_leaf': 0.1921565591082464, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00041666520721794905, 'validation_fraction': 0.8546947848451162, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.785171102661597
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 21:11:11,400] Trial 62 finished with value: 0.7276953037412677 and parameters: {'subsample': 0.45214538811231725, 'learning_rate': 0.0513322635401625, 'dropout_rate': 0.8285090704895912, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.3101145382804477, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.9071319756271838, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 21:11:37,280] Trial 63 finished with value: 0.7272534889605955 and parameters: {'subsample': 0.423629566204322, 'learning_rate': 0.03438070971435433, 'dropout_rate': 0.8555425487679464, 'n_estimators': 482, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.2737163567412147, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07017568466241592, 'validation_fraction': 0.9620208724483128, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:12:22,937] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.4297477654076297, 'learning_rate': 0.043910428099002294, 'dropout_rate': 0.8352402756430523, 'n_estimators': 488, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4263511298787651, 'min_weight_fraction_leaf': 0.3160966031078735, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07065062649817302, 'validation_fraction': 0.9463535838530875, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.7433460076045627
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 21:12:49,768] Trial 65 finished with value: 0.6927868956890011 and parameters: {'subsample': 0.30781242416514565, 'learning_rate': 0.05113323137902576, 'dropout_rate': 0.7239851485767856, 'n_estimators': 454, 'criterion': 'friedman_mse', 'ccp_alpha': 0.0027463439227063506, 'min_weight_fraction_leaf': 0.26877432545564617, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0017887993094304819, 'validation_fraction': 0.761339316000577, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:13:00,093] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.48922080655608885, 'learning_rate': 0.035347527077929, 'dropout_rate': 0.8893092269739165, 'n_estimators': 417, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5356537836856377, 'min_weight_fraction_leaf': 0.29863354085488475, 'max_features': 'sqrt', 'min_impurity_decrease': 0.012061434840147687, 'validation_fraction': 0.9051978098851384, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:13:17,071] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.4210285565476828, 'learning_rate': 0.06591045167415374, 'dropout_rate': 0.8060412975360456, 'n_estimators': 438, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7762639994874865, 'min_weight_fraction_leaf': 0.25473199100313054, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00610717642726731, 'validation_fraction': 0.8093169248034847, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:13:24,260] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.36755564370451066, 'learning_rate': 0.05068902572826714, 'dropout_rate': 0.9726834213374217, 'n_estimators': 481, 'criterion': 'friedman_mse', 'ccp_alpha': 1.1308236536377811, 'min_weight_fraction_leaf': 0.3065580571022596, 'max_features': 'sqrt', 'min_impurity_decrease': 0.021693222709295752, 'validation_fraction': 0.715818151257265, 'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:13:36,221] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.5142803470563067, 'learning_rate': 0.03243373478476426, 'dropout_rate': 0.9137837647742049, 'n_estimators': 459, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28985235680036014, 'min_weight_fraction_leaf': 0.4054829396615446, 'max_features': 'sqrt', 'min_impurity_decrease': 0.001581139753892363, 'validation_fraction': 0.329118980782965, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:13:53,738] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.45559432833731667, 'learning_rate': 0.0700250470025932, 'dropout_rate': 0.8524549437406417, 'n_estimators': 426, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6643601052078473, 'min_weight_fraction_leaf': 0.2388136010393243, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00031481444052736005, 'validation_fraction': 0.9166648433104408, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 21:14:19,714] Trial 71 finished with value: 0.6952494796223398 and parameters: {'subsample': 0.3096152191637527, 'learning_rate': 0.05014029765368843, 'dropout_rate': 0.72942553198655, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.027173150322083957, 'min_weight_fraction_leaf': 0.28439521854539385, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002459385698607316, 'validation_fraction': 0.9631122514300272, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:14:56,543] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.2984794016129376, 'learning_rate': 0.04184406116938292, 'dropout_rate': 0.6550072165726977, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.004791436061459352, 'min_weight_fraction_leaf': 0.28556030062342436, 'max_features': 'sqrt', 'min_impurity_decrease': 4.3401892914387e-05, 'validation_fraction': 0.9667204228379752, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 46 with value: 0.7302327934888235.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:15:02,662] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.24177977569589332, 'learning_rate': 0.06081438305266998, 'dropout_rate': 0.7352912026497521, 'n_estimators': 178, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3565493126455575, 'min_weight_fraction_leaf': 0.2641618003854867, 'max_features': 'sqrt', 'min_impurity_decrease': 0.005565263987110645, 'validation_fraction': 0.8591928424609534, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:15:36,395] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.41766913987966564, 'learning_rate': 0.04837445328457708, 'dropout_rate': 0.7848778465425879, 'n_estimators': 370, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9796884706123067, 'min_weight_fraction_leaf': 0.3487238233672823, 'max_features': 0.1, 'min_impurity_decrease': 0.060142707029694174, 'validation_fraction': 0.9742035251830021, 'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:16:45,081] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.14697123662254313, 'learning_rate': 0.056288895309512615, 'dropout_rate': 0.9249274443508626, 'n_estimators': 491, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3014105775868996, 'min_weight_fraction_leaf': 0.2756234570388064, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5125842579708578e-05, 'validation_fraction': 0.9436471609372878, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:18:53,150] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.33597481611005453, 'learning_rate': 0.03785525432874416, 'dropout_rate': 0.5640100673453201, 'n_estimators': 465, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6095307820420031, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'log2', 'min_impurity_decrease': 0.009484910777116757, 'validation_fraction': 0.9018697914265744, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:19:55,570] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.3970316343863033, 'learning_rate': 0.02702816788183442, 'dropout_rate': 0.44124671276745586, 'n_estimators': 411, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2997944075240355, 'min_weight_fraction_leaf': 0.38254401959264994, 'max_features': 1, 'min_impurity_decrease': 0.0031143423876080715, 'validation_fraction': 0.9903409642142473, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7547528517110266
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 21:22:25,621] Trial 78 finished with value: 0.7051904393459792 and parameters: {'subsample': 0.22930387168853233, 'learning_rate': 0.05145553889741248, 'dropout_rate': 0.5044517635709308, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.02270996969784733, 'min_weight_fraction_leaf': 0.24788146923782178, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010045782837561419, 'validation_fraction': 0.8244464183531952, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:29:26,088] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.5787844954317829, 'learning_rate': 0.046320469166095994, 'dropout_rate': 0.4903660577547442, 'n_estimators': 481, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8369274241395267, 'min_weight_fraction_leaf': 0.3217471182217138, 'max_features': 'sqrt', 'min_impurity_decrease': 6.262467662262306e-05, 'validation_fraction': 0.822046932546052, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:29:51,683] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.25430148678930137, 'learning_rate': 0.04349582782163459, 'dropout_rate': 0.6081624319156314, 'n_estimators': 427, 'criterion': 'friedman_mse', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.20197769506016003, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010150765068526006, 'validation_fraction': 0.7818118403834172, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:30:24,188] Trial 81 finished with value: 0.5 and parameters: {'subsample': 0.18443408707190798, 'learning_rate': 0.05259966681355033, 'dropout_rate': 0.6449369275082966, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.23050623823206434, 'min_weight_fraction_leaf': 0.25144155938407586, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0013502467549795782, 'validation_fraction': 0.8730600269587929, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:31:13,966] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.21084564139781542, 'learning_rate': 0.0557198718851306, 'dropout_rate': 0.5142046015087244, 'n_estimators': 464, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017868752517803354, 'min_weight_fraction_leaf': 0.22672177077398445, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00028049277519258663, 'validation_fraction': 0.9277470449701044, 'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:31:33,437] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.4945458790853893, 'learning_rate': 0.05895862835575055, 'dropout_rate': 0.7558273871774451, 'n_estimators': 438, 'criterion': 'friedman_mse', 'ccp_alpha': 0.501498258850682, 'min_weight_fraction_leaf': 0.28306768635206997, 'max_features': 'sqrt', 'min_impurity_decrease': 0.04144166385519717, 'validation_fraction': 0.8951513356732839, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5637450199203188
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 21:32:01,950] Trial 84 finished with value: 0.5443589026234574 and parameters: {'subsample': 0.3659778071469274, 'learning_rate': 0.0502270627847683, 'dropout_rate': 0.6818395627907664, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2606567709484204, 'min_weight_fraction_leaf': 0.2982881980338302, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0006662326950079798, 'validation_fraction': 0.8368533116927852, 'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:32:31,398] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.26399210031385845, 'learning_rate': 0.04714737148720377, 'dropout_rate': 0.5847508382404618, 'n_estimators': 406, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9671659583078602, 'min_weight_fraction_leaf': 0.24391254579161395, 'max_features': 'log2', 'min_impurity_decrease': 0.000147849817010694, 'validation_fraction': 0.9991453937475061, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:32:34,396] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.10060967717953817, 'learning_rate': 0.020768593047903114, 'dropout_rate': 0.4508818797021682, 'n_estimators': 110, 'criterion': 'squared_error', 'ccp_alpha': 0.625182110561999, 'min_weight_fraction_leaf': 0.2761510567632799, 'max_features': 1, 'min_impurity_decrease': 0.0023479607608161597, 'validation_fraction': 0.7423283408922972, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5319148936170213
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5858369098712446
[I 2024-04-16 21:33:41,671] Trial 87 finished with value: 0.5235503606976531 and parameters: {'subsample': 0.43950121810340115, 'learning_rate': 0.0648732804536445, 'dropout_rate': 0.34957168713474945, 'n_estimators': 475, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2369430535237365, 'min_weight_fraction_leaf': 0.3096474641971687, 'max_features': 0.1, 'min_impurity_decrease': 4.850175263275894e-05, 'validation_fraction': 0.951557506428991, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:34:08,266] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.21193910478383937, 'learning_rate': 0.06177410341848358, 'dropout_rate': 0.8846843251251039, 'n_estimators': 417, 'criterion': 'squared_error', 'ccp_alpha': 1.2807191828912141, 'min_weight_fraction_leaf': 0.36091713798964337, 'max_features': 'sqrt', 'min_impurity_decrease': 3.0185550531810504e-05, 'validation_fraction': 0.8545724907452001, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:34:36,209] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.3182195088282702, 'learning_rate': 0.038485790496188235, 'dropout_rate': 0.5004748125823506, 'n_estimators': 350, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5179293303896771, 'min_weight_fraction_leaf': 0.3315564489154308, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00046699939753012373, 'validation_fraction': 0.9294234431035183, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:35:03,104] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.2762755336662733, 'learning_rate': 0.05273046932737523, 'dropout_rate': 0.5437417743878508, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 0.8405822272736876, 'min_weight_fraction_leaf': 0.43576713073659407, 'max_features': 'log2', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8767498848039622, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 21:35:28,529] Trial 91 finished with value: 0.700117112340541 and parameters: {'subsample': 0.3126184078929269, 'learning_rate': 0.051134988454074756, 'dropout_rate': 0.7292690956696949, 'n_estimators': 456, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03786277950879616, 'min_weight_fraction_leaf': 0.2673649069566119, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0009910717111428719, 'validation_fraction': 0.7562406049799346, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 21:35:37,642] Trial 92 finished with value: 0.7024960971305607 and parameters: {'subsample': 0.335844111701364, 'learning_rate': 0.05038873458029908, 'dropout_rate': 0.9571283850291226, 'n_estimators': 449, 'criterion': 'friedman_mse', 'ccp_alpha': 0.046820443269266425, 'min_weight_fraction_leaf': 0.2690679137012573, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0008839215080019705, 'validation_fraction': 0.6636818720897245, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:35:48,871] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.33719220910486725, 'learning_rate': 0.05705464633480763, 'dropout_rate': 0.9535384595922254, 'n_estimators': 458, 'criterion': 'friedman_mse', 'ccp_alpha': 0.46107702292048336, 'min_weight_fraction_leaf': 0.21683645486742856, 'max_features': 'sqrt', 'min_impurity_decrease': 6.862155169827754e-06, 'validation_fraction': 0.6649080237925696, 'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5148936170212766
Fold 4 C-index: 0.5
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 21:35:56,203] Trial 94 finished with value: 0.5399159530265387 and parameters: {'subsample': 0.3795391698153348, 'learning_rate': 0.05424992354992036, 'dropout_rate': 0.998020448184449, 'n_estimators': 483, 'criterion': 'friedman_mse', 'ccp_alpha': 0.25606469361498857, 'min_weight_fraction_leaf': 0.41683364220226815, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0002584853980433294, 'validation_fraction': 0.7006781615049952, 'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:36:07,558] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.8984320859036168, 'learning_rate': 0.04600776760199582, 'dropout_rate': 0.9375007175299167, 'n_estimators': 432, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6620944039517677, 'min_weight_fraction_leaf': 0.25977850599919555, 'max_features': 'sqrt', 'min_impurity_decrease': 0.001020092546254454, 'validation_fraction': 0.5743893910381555, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:36:15,918] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.9444669238877774, 'learning_rate': 0.03476407177203711, 'dropout_rate': 0.9688789578178828, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5985394199987468, 'min_weight_fraction_leaf': 0.4570304925648464, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0009757952163430444, 'validation_fraction': 0.7662521699162499, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 46 with value: 0.7302327934888235.

Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7461240310077519
Fold 3 C-index: 0.6659574468085107
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 21:36:30,731] Trial 97 finished with value: 0.6962555777075096 and parameters: {'subsample': 0.40802503425948106, 'learning_rate': 0.060600248591443, 'dropout_rate': 0.8994280356510341, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.16755337346680707, 'min_weight_fraction_leaf': 0.24511190648995798, 'max_features': 'sqrt', 'min_impurity_decrease': 8.96572949971136e-05, 'validation_fraction': 0.627628127325836, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:37:10,950] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.4753398503091408, 'learning_rate': 0.042851702941042756, 'dropout_rate': 0.4097545787205149, 'n_estimators': 422, 'criterion': 'friedman_mse', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.22954018766820677, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0006718591849438628, 'validation_fraction': 0.7879666515524516, 'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 46 with value: 0.7302327934888235.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-16 21:37:28,448] A new study created in memory with name: no-name-85623565-c9d8-4cdf-906a-95651955e9dc

Fold 5 C-index: 0.5
[I 2024-04-16 21:37:28,418] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.538903142828151, 'learning_rate': 0.08016115293851586, 'dropout_rate': 0.8495524343938528, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 1.062650498155627, 'min_weight_fraction_leaf': 0.266932632335787, 'max_features': 'log2', 'min_impurity_decrease': 0.00015837847703956763, 'validation_fraction': 0.806274737250757, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 46 with value: 0.7302327934888235.


* Best trial for C-index:
 FrozenTrial(number=46, state=TrialState.COMPLETE, values=[0.7302327934888235], datetime_start=datetime.datetime(2024, 4, 16, 21, 6, 14, 90578), datetime_complete=datetime.datetime(2024, 4, 16, 21, 6, 23, 60398), params={'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=46, value=None)


* Best Score for C-index:
 0.7302327934888235

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:37:51,998] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:38:04,105] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:38:16,183] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 21:38:35,877] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:38:42,956] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:38:44,922] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:39:03,249] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:39:07,737] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:39:08,789] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.2460286977611154
Fold 2 IBS: 0.2303821231845217
Fold 3 IBS: 0.228604705799191
Fold 4 IBS: 0.24083601386283238
Fold 5 IBS: 0.22855615875606775
[I 2024-04-16 21:40:03,524] Trial 9 finished with value: 0.23488153987274565 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.23488153987274565.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.23165805889260804
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164907810183034
Fold 5 IBS: 0.2291762528827903
[I 2024-04-16 21:42:07,375] Trial 10 finished with value: 0.235633851387992 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23488153987274565.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 21:43:32,226] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23488153987274565.
Fold 1 IBS: 0.24715489611868932
Fold 2 IBS: 0.23184689320114124
Fold 3 IBS: 0.2289550256511867
Fold 4 IBS: 0.24186707989824685
Fold 5 IBS: 0.2293129447586724
[I 2024-04-16 21:44:42,172] Trial 12 finished with value: 0.23582736792558728 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23488153987274565.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:45:20,773] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.23488153987274565.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:46:27,305] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.23488153987274565.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:47:20,427] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.23488153987274565.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:47:46,171] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.23488153987274565.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:48:50,148] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.23488153987274565.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:49:59,702] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.23488153987274565.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:50:08,527] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.23488153987274565.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:51:06,197] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.23488153987274565.
Fold 1 IBS: 0.24710981631467982
Fold 2 IBS: 0.23198582071341375
Fold 3 IBS: 0.22892152217671352
Fold 4 IBS: 0.2418944853641206
Fold 5 IBS: 0.2292311905787679
[I 2024-04-16 21:52:06,069] Trial 21 finished with value: 0.2358285670295391 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23488153987274565.
Fold 1 IBS: 0.24614704791458872
Fold 2 IBS: 0.2300604471828938

Fold 3 IBS: 0.22851491885777983
Fold 4 IBS: 0.24077720544650574
Fold 5 IBS: 0.22862475643139354
[I 2024-04-16 21:53:24,638] Trial 22 finished with value: 0.23482487516663234 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:54:20,093] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:54:58,533] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:55:32,664] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:56:22,709] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:56:28,637] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 21:56:47,683] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:57:33,402] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 21:57:54,107] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24695000891576355
Fold 2 IBS: 0.23168626242435933
Fold 3 IBS: 0.22889748884171018
Fold 4 IBS: 0.24165979501668006
Fold 5 IBS: 0.22912802638333987
[I 2024-04-16 21:58:56,518] Trial 31 finished with value: 0.2356643163163706 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24603429542128458
Fold 2 IBS: 0.2302845539630394
Fold 3 IBS: 0.22852158960217014
Fold 4 IBS: 0.24075894829353398
Fold 5 IBS: 0.2286298290337006
[I 2024-04-16 21:59:58,063] Trial 32 finished with value: 0.23484584326274574 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:00:41,042] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:01:29,214] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 22:01:38,230] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:02:34,155] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:02:36,184] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 22:03:04,702] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:03:45,656] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:04:27,077] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24647740013347003
Fold 2 IBS: 0.23088361900489293
Fold 3 IBS: 0.2286335921023464
Fold 4 IBS: 0.24117284377382972
Fold 5 IBS: 0.22886225283651718
[I 2024-04-16 22:05:20,788] Trial 41 finished with value: 0.23520594157021124 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.2460714278674264
Fold 2 IBS: 0.2303684346732453
Fold 3 IBS: 0.22846426517405946
Fold 4 IBS: 0.24081589071914775
Fold 5 IBS: 0.22860696956566312
[I 2024-04-16 22:06:15,892] Trial 42 finished with value: 0.23486539759990843 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:07:17,030] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:08:06,297] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24691525413796903
Fold 2 IBS: 0.23158138152181637
Fold 3 IBS: 0.2286649673748319
Fold 4 IBS: 0.2415963441558337
Fold 5 IBS: 0.22911324854314402
[I 2024-04-16 22:08:48,259] Trial 45 finished with value: 0.235574239146719 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:09:28,573] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:09:46,563] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:09:46,929] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 22:10:00,620] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:10:50,763] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.2469454998116223
Fold 2 IBS: 0.23161193376707992
Fold 3 IBS: 0.2286601342962246
Fold 4 IBS: 0.24159474787931629
Fold 5 IBS: 0.22911662368308477
[I 2024-04-16 22:11:31,445] Trial 51 finished with value: 0.2355857878874656 and parameters: {'subsample': 0.8432391250804372, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.42932457769018856, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.012243529086999924, 'min_weight_fraction_leaf': 0.13427213537405694, 'max_features': 0.1, 'min_impurity_decrease': 7.107322942000855e-07, 'validation_fraction': 0.7779173644820415, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:12:21,887] Trial 52 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8647416200425169, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.27204051720793454, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.32951036616207574, 'min_weight_fraction_leaf': 0.0696136715803943, 'max_features': 0.1, 'min_impurity_decrease': 1.0411636207736935e-06, 'validation_fraction': 0.6649885450408526, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24645811064739673
Fold 2 IBS: 0.2307486275384718
Fold 3 IBS: 0.22803394622568862
Fold 4 IBS: 0.24092841602192167
Fold 5 IBS: 0.22862507369945048
[I 2024-04-16 22:12:56,584] Trial 53 finished with value: 0.23495883482658586 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.35255575108470655, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.15399525160080688, 'max_features': 0.1, 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9519356083737385, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 22:13:43,853] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9637771314277555, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18483741622154692, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.16826656130652193, 'max_features': 0.1, 'min_impurity_decrease': 1.891916944791205e-07, 'validation_fraction': 0.9592695072789675, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 22:14:21,972] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.918589848048704, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.1366452847323028, 'n_estimators': 388, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.18967222528443176, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 18}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:15:00,745] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7513175598857118, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.35760497570906596, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.29279606045526263, 'max_features': 'auto', 'min_impurity_decrease': 1.1427991588661997e-07, 'validation_fraction': 0.9992935111116187, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:15:36,257] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9629672876565945, 'learning_rate': 0.03044321993695316, 'dropout_rate': 0.2654836627375681, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.3309371032482379, 'max_features': 0.1, 'min_impurity_decrease': 4.889527309942819e-07, 'validation_fraction': 0.8335980560573747, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:16:29,524] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9051869988846165, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.2230573971097521, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.46721256406858613, 'min_weight_fraction_leaf': 0.24217068500219807, 'max_features': 1, 'min_impurity_decrease': 3.3273145847446367e-06, 'validation_fraction': 0.9559266299158219, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:17:15,581] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.019139926132660745, 'dropout_rate': 0.3062756368166816, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.21472425517002308, 'max_features': 'auto', 'min_impurity_decrease': 3.097931869672697e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:17:42,019] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7996511669090498, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.47747471244727363, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2543538004837033, 'min_weight_fraction_leaf': 0.10444758350906072, 'max_features': 'log2', 'min_impurity_decrease': 1.4854430366731937e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 14}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 22:18:44,269] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8595582024746382, 'learning_rate': 0.009662456499934472, 'dropout_rate': 0.4098250163413181, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.2074917467600883, 'min_weight_fraction_leaf': 0.15724667461688366, 'max_features': 0.1, 'min_impurity_decrease': 7.257266102562462e-07, 'validation_fraction': 0.9258995897425243, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24679260086369065
Fold 2 IBS: 0.23133920721089904
Fold 3 IBS: 0.22847505698111184
Fold 4 IBS: 0.24138521369662638
Fold 5 IBS: 0.22894340143873776
[I 2024-04-16 22:19:13,552] Trial 62 finished with value: 0.23538709603821312 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.01537203137740326, 'dropout_rate': 0.5939902455485113, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.006733098283166955, 'max_features': 0.1, 'min_impurity_decrease': 1.7338007602824288e-07, 'validation_fraction': 0.7998452500875314, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:19:43,945] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9881778214681738, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.505857528523121, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.012712121434543151, 'max_features': 0.1, 'min_impurity_decrease': 1.7159806179406314e-07, 'validation_fraction': 0.8999002791146725, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24636138058557341
Fold 2 IBS: 0.23067753464118712
Fold 3 IBS: 0.2281212721157159
Fold 4 IBS: 0.24112777926750717
Fold 5 IBS: 0.22864345214118942
[I 2024-04-16 22:20:10,324] Trial 64 finished with value: 0.23498628375023461 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.04209806464905699, 'dropout_rate': 0.6515053075848445, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.04245308337653099, 'min_weight_fraction_leaf': 0.044350095557314374, 'max_features': 0.1, 'min_impurity_decrease': 4.491377932515504e-07, 'validation_fraction': 0.9610335014089881, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-16 22:20:37,018] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9388732674648854, 'learning_rate': 0.04244875829612528, 'dropout_rate': 0.6822179842512692, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 1.1144766988816432, 'min_weight_fraction_leaf': 0.08731759636169496, 'max_features': 'auto', 'min_impurity_decrease': 4.028739847312721e-07, 'validation_fraction': 0.9616704158537814, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:21:06,294] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8952643616873973, 'learning_rate': 0.05359198006915804, 'dropout_rate': 0.6509686174553241, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.713342732410399, 'min_weight_fraction_leaf': 0.037327349410482574, 'max_features': 'auto', 'min_impurity_decrease': 2.2946753237767036e-06, 'validation_fraction': 0.8670144195682054, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:21:23,664] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9559398584951578, 'learning_rate': 0.001312025546225645, 'dropout_rate': 0.8046607423826502, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.04508345598854374, 'max_features': 'sqrt', 'min_impurity_decrease': 5.750753876092619e-06, 'validation_fraction': 0.9116952163053982, 'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:22:03,693] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9243406312878238, 'learning_rate': 0.058088208137035593, 'dropout_rate': 0.19698157671040928, 'n_estimators': 426, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997767788709036, 'min_weight_fraction_leaf': 0.2604144011776313, 'max_features': 0.1, 'min_impurity_decrease': 1.1827988873109092e-06, 'validation_fraction': 0.9998742352056981, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:22:37,520] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8260339189937393, 'learning_rate': 0.08587936719454789, 'dropout_rate': 0.23558185081536823, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.2330662826063859, 'max_features': 'auto', 'min_impurity_decrease': 6.006710681053735e-05, 'validation_fraction': 0.9704861722747272, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:23:04,354] Trial 70 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.027514255341309163, 'dropout_rate': 0.5905404972480945, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.12615077879430528, 'max_features': None, 'min_impurity_decrease': 5.222228681732963e-07, 'validation_fraction': 0.8455426922265927, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24681290005426243
Fold 2 IBS: 0.23133517592428143
Fold 3 IBS: 0.22852851907340835
Fold 4 IBS: 0.24139413215073746
Fold 5 IBS: 0.22897741306002092
[I 2024-04-16 22:23:29,998] Trial 71 finished with value: 0.23540962805254212 and parameters: {'subsample': 0.9998892193300933, 'learning_rate': 0.015392294492197107, 'dropout_rate': 0.5823696005202688, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.06445986479432256, 'max_features': 0.1, 'min_impurity_decrease': 2.7569586568543097e-07, 'validation_fraction': 0.9287673956828812, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24698547695488213
Fold 2 IBS: 0.231640387768433
Fold 3 IBS: 0.22867580440576513
Fold 4 IBS: 0.24161301756660888
Fold 5 IBS: 0.22915668642448656
[I 2024-04-16 22:23:48,893] Trial 72 finished with value: 0.23561427462403514 and parameters: {'subsample': 0.9695012667210274, 'learning_rate': 0.009880743240604978, 'dropout_rate': 0.7234474037831898, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.004793672160551997, 'min_weight_fraction_leaf': 0.0006344109437541792, 'max_features': 0.1, 'min_impurity_decrease': 1.0311442565316877e-07, 'validation_fraction': 0.7967022266516048, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 22:23:52,135] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9999520023767101, 'learning_rate': 0.022493973992953744, 'dropout_rate': 0.6438577663377525, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.019994854935207237, 'max_features': 0.1, 'min_impurity_decrease': 1.5918517921458393e-07, 'validation_fraction': 0.9395376003114264, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:25:23,708] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9393704884452911, 'learning_rate': 0.005281947478642466, 'dropout_rate': 0.12943958636926897, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.3686824833949447, 'min_weight_fraction_leaf': 0.053815083102964845, 'max_features': 0.1, 'min_impurity_decrease': 2.539937499874641e-07, 'validation_fraction': 0.8777634783146918, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 17}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:25:48,325] Trial 75 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8731051806028837, 'learning_rate': 0.019330707767774714, 'dropout_rate': 0.6082487085608025, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 1.3248769325723149, 'min_weight_fraction_leaf': 0.2959887591923328, 'max_features': 'auto', 'min_impurity_decrease': 4.7652746848926277e-07, 'validation_fraction': 0.9771406523907726, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:26:28,842] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9712736025274701, 'learning_rate': 0.01258123741877497, 'dropout_rate': 0.5558253337837517, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.2663511381103464, 'max_features': 0.1, 'min_impurity_decrease': 1.131669404349593e-05, 'validation_fraction': 0.687477001647036, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 22:27:19,090] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9040601608260395, 'learning_rate': 0.008028762030775153, 'dropout_rate': 0.1661055390191164, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.5920167940309409, 'min_weight_fraction_leaf': 0.20760648939509768, 'max_features': 1, 'min_impurity_decrease': 1.2858411523836384e-06, 'validation_fraction': 0.7519570151291436, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:35:48,148] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9412481314247185, 'learning_rate': 0.003888190949209832, 'dropout_rate': 0.6251655088821374, 'n_estimators': 382, 'criterion': 'squared_error', 'ccp_alpha': 0.9892893740980914, 'min_weight_fraction_leaf': 0.033793930334568206, 'max_features': 'auto', 'min_impurity_decrease': 0.0002118263312796081, 'validation_fraction': 0.6158958959698865, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927107
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:36:16,454] Trial 79 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.5431112126281161, 'learning_rate': 0.030593840345293603, 'dropout_rate': 0.28940296100102497, 'n_estimators': 452, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28778903589913546, 'min_weight_fraction_leaf': 0.17610538826721606, 'max_features': 'auto', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.8300457615159439, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:41:44,607] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9189279907539, 'learning_rate': 0.016793358093448018, 'dropout_rate': 0.3388723042222102, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.3543882746154796, 'max_features': 'log2', 'min_impurity_decrease': 1.4631830515812678e-07, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24678706859703695
Fold 2 IBS: 0.23130756583166284
Fold 3 IBS: 0.22849556472396068
Fold 4 IBS: 0.24136692195891205
Fold 5 IBS: 0.22895093271399847
[I 2024-04-16 22:42:13,057] Trial 81 finished with value: 0.23538161076511424 and parameters: {'subsample': 0.9965114629683737, 'learning_rate': 0.015327246809846502, 'dropout_rate': 0.5609953054435709, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.06929483396903219, 'max_features': 0.1, 'min_impurity_decrease': 2.622082619894755e-07, 'validation_fraction': 0.9164477820882341, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:42:43,458] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9805053749629268, 'learning_rate': 0.010886411260799844, 'dropout_rate': 0.5683084429638622, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.2901659063159545, 'min_weight_fraction_leaf': 0.00019462069720194673, 'max_features': 0.1, 'min_impurity_decrease': 6.285047241123457e-07, 'validation_fraction': 0.9118209657927552, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:43:31,108] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6438413298708685, 'learning_rate': 0.02471644851386544, 'dropout_rate': 0.5202192733555178, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.6302736024968735, 'min_weight_fraction_leaf': 0.08484719071542221, 'max_features': 0.1, 'min_impurity_decrease': 3.0720666780466816e-07, 'validation_fraction': 0.8846072833938841, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 15}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22897974854325906
Fold 4 IBS: 0.2419722638357615
Fold 5 IBS: 0.22939446473823125
[I 2024-04-16 22:43:46,755] Trial 84 finished with value: 0.23592669242035297 and parameters: {'subsample': 0.411624430892823, 'learning_rate': 0.014346557003820789, 'dropout_rate': 0.6984815756762216, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.214835028703023, 'min_weight_fraction_leaf': 0.0519525894881867, 'max_features': 0.1, 'min_impurity_decrease': 3.906058893074947e-07, 'validation_fraction': 0.939166800936518, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 22 with value: 0.23482487516663234.
Fold 1 IBS: 0.24536338744008138
Fold 2 IBS: 0.2276900964220227
Fold 3 IBS: 0.22690969972656885
Fold 4 IBS: 0.23917874206080889
Fold 5 IBS: 0.2275401578530729
[I 2024-04-16 22:44:27,132] Trial 85 finished with value: 0.23333641670051097 and parameters: {'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 85 with value: 0.23333641670051097.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:45:12,662] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8921917646046833, 'learning_rate': 0.03493887873396886, 'dropout_rate': 0.20248417164561996, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.8648012196087868, 'min_weight_fraction_leaf': 0.02811592341251499, 'max_features': 'auto', 'min_impurity_decrease': 9.529217204035409e-07, 'validation_fraction': 0.9780308436827329, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 12}. Best is trial 85 with value: 0.23333641670051097.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:45:25,031] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9521381251132186, 'learning_rate': 0.007217130157082901, 'dropout_rate': 0.2326599983541061, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.4347343354489257, 'min_weight_fraction_leaf': 0.25406866786837123, 'max_features': 'auto', 'min_impurity_decrease': 2.642399797861587e-06, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 85 with value: 0.23333641670051097.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 22:46:29,889] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8783477148356468, 'learning_rate': 0.019145642246983192, 'dropout_rate': 0.2500967923284591, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.2742275973203492, 'min_weight_fraction_leaf': 0.11068414611763369, 'max_features': 'auto', 'min_impurity_decrease': 0.0011701047770450368, 'validation_fraction': 0.9552938036430088, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 4}. Best is trial 85 with value: 0.23333641670051097.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:03:59,685] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9225585795675643, 'learning_rate': 0.0028206049164217276, 'dropout_rate': 0.16604269499086277, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 1.572109186144046, 'min_weight_fraction_leaf': 0.27088299579805813, 'max_features': 'auto', 'min_impurity_decrease': 1.8368798466082297e-06, 'validation_fraction': 0.905787363075094, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 85 with value: 0.23333641670051097.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:04:36,222] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3053150575440778, 'learning_rate': 0.00911659038630352, 'dropout_rate': 0.38100622127956474, 'n_estimators': 498, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.09273837444215938, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8657908240711146, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 85 with value: 0.23333641670051097.
Fold 1 IBS: 0.24616813349639136
Fold 2 IBS: 0.23031403353059005
Fold 3 IBS: 0.2279367260784865
Fold 4 IBS: 0.24073043270907032
Fold 5 IBS: 0.22849793736074164
[I 2024-04-16 23:05:14,069] Trial 91 finished with value: 0.23472945263505599 and parameters: {'subsample': 0.9762027146117168, 'learning_rate': 0.021129279003315533, 'dropout_rate': 0.2673714840258141, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.012296492316215053, 'max_features': 0.1, 'min_impurity_decrease': 2.2249919821233818e-07, 'validation_fraction': 0.9309517539709111, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 14}. Best is trial 85 with value: 0.23333641670051097.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:05:45,126] Trial 92 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.970200161496241, 'learning_rate': 0.02241134247478034, 'dropout_rate': 0.2583752131981347, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.4943670196310161, 'min_weight_fraction_leaf': 0.022776576304230935, 'max_features': 'auto', 'min_impurity_decrease': 9.135609514383116e-07, 'validation_fraction': 0.929257109542098, 'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 85 with value: 0.23333641670051097.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:06:15,942] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9562310140378132, 'learning_rate': 0.017182645082053097, 'dropout_rate': 0.30303355573944185, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.20362952808416507, 'min_weight_fraction_leaf': 0.06487551572722715, 'max_features': 'auto', 'min_impurity_decrease': 2.2745718823187047e-07, 'validation_fraction': 0.979813726530939, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 14}. Best is trial 85 with value: 0.23333641670051097.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:06:44,835] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9803432784281702, 'learning_rate': 0.011448180194224972, 'dropout_rate': 0.28058975756978766, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.6843293477116347, 'min_weight_fraction_leaf': 0.1982598024964269, 'max_features': None, 'min_impurity_decrease': 5.981184732872339e-07, 'validation_fraction': 0.9454695844953723, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 85 with value: 0.23333641670051097.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:07:19,834] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9455952167309377, 'learning_rate': 0.03849480232107322, 'dropout_rate': 0.3201948574529592, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 0.9601205383555245, 'min_weight_fraction_leaf': 0.2390619554248597, 'max_features': 0.1, 'min_impurity_decrease': 3.7935126700511503e-07, 'validation_fraction': 0.9999690268176494, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 15}. Best is trial 85 with value: 0.23333641670051097.
Fold 1 IBS: 0.24556839577871034
Fold 2 IBS: 0.22843970491403545
Fold 3 IBS: 0.22857626753138371
Fold 4 IBS: 0.2400598315906517
Fold 5 IBS: 0.2279355389988583
[I 2024-04-16 23:07:47,343] Trial 96 finished with value: 0.23411594776272787 and parameters: {'subsample': 0.9088634226642077, 'learning_rate': 0.02041047784766359, 'dropout_rate': 0.22112152895475082, 'n_estimators': 396, 'criterion': 'squared_error', 'ccp_alpha': 0.03063069674161246, 'min_weight_fraction_leaf': 0.2253662010001949, 'max_features': 'auto', 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.32386831053055254, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 85 with value: 0.23333641670051097.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:08:17,012] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8201377508003859, 'learning_rate': 0.026783144722107532, 'dropout_rate': 0.18321575541765564, 'n_estimators': 399, 'criterion': 'squared_error', 'ccp_alpha': 0.43549519886063537, 'min_weight_fraction_leaf': 0.22023393103598612, 'max_features': 'auto', 'min_impurity_decrease': 1.3568805622065066e-07, 'validation_fraction': 0.31617010634192105, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 85 with value: 0.23333641670051097.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:08:40,755] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7743094980751969, 'learning_rate': 0.020410071578111352, 'dropout_rate': 0.21292319653614647, 'n_estimators': 354, 'criterion': 'squared_error', 'ccp_alpha': 1.1387001784940558, 'min_weight_fraction_leaf': 0.22558745505753475, 'max_features': 'auto', 'min_impurity_decrease': 3.4044321201945537e-06, 'validation_fraction': 0.1600852440936258, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 85 with value: 0.23333641670051097.
Fold 1 IBS: 0.24724710044658998

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:09:22,504] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9084360842440081, 'learning_rate': 0.013060448266216875, 'dropout_rate': 0.25443633448028735, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.2223066295281712, 'min_weight_fraction_leaf': 0.25005462596245476, 'max_features': 'auto', 'min_impurity_decrease': 2.1305992007975229e-07, 'validation_fraction': 0.4189919199463679, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 85 with value: 0.23333641670051097.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.23333641670051097], datetime_start=datetime.datetime(2024, 4, 16, 22, 43, 46, 766968), datetime_complete=datetime.datetime(2024, 4, 16, 22, 44, 27, 130503), params={'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=85, value=None)


* Best Score for IBS:
 0.23333641670051097

In [71]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [72]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.73
train_ibs:  0.233

#### Test

In [73]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [74]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03525202624769574,
                                 dropout_rate=0.9694253886674298,
                                 learning_rate=0.05377375104309677, max_depth=4,
                                 max_features='log2', max_leaf_nodes=15,
                                 min_impurity_decrease=2.482390348219561e-06,
                                 min_samples_leaf=15, min_samples_split=19,
                                 min_weight_fraction_leaf=0.3666298089106992,
                                 n_estimators=450, random_state=123,
                                 subsample=0.9035029991499002,
                                 validation_fraction=0.8472602359999014)

C-index score: 0.591

GradientBoostingSurvivalAnalysis(ccp_alpha=0.01138981446692314,
                                 criterion='squared_error',
                                 dropout_rate=0.2479619862207481,
                                 learning_rate=0.02022975259096714, max_depth=8,
                                 max_features='auto', max_leaf_nodes=20,
                                 min_impurity_decrease=9.61920586779085e-07,
                                 min_samples_leaf=18, min_samples_split=14,
                                 min_weight_fraction_leaf=0.026767353450782638,
                                 n_estimators=438, random_state=123,
                                 subsample=0.9481727373988897,
                                 validation_fraction=0.973754058089352)

IBS: 0.229

In [75]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [76]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [77]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 23:09:32,717] A new study created in memory with name: no-name-e22d06e7-b2e1-4a19-a4ca-855f553d5075

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 23:09:33,594] Trial 0 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6249682148055231.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 23:09:39,339] Trial 1 finished with value: 0.6241098457068107 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6249682148055231.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:09:40,759] Trial 2 finished with value: 0.6290789721738743 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6290789721738743.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:09:42,273] Trial 3 finished with value: 0.6321935102194108 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.6321935102194108.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:09:44,375] Trial 4 finished with value: 0.635384342139341 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.635384342139341.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 23:09:47,207] Trial 5 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.635384342139341.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 23:09:48,336] Trial 6 finished with value: 0.6223931075093858 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.635384342139341.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 23:09:48,574] Trial 7 finished with value: 0.6289447028736863 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.635384342139341.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 23:09:49,862] Trial 8 finished with value: 0.6265038648777369 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.635384342139341.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 23:09:53,696] Trial 9 finished with value: 0.6256454957790245 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.635384342139341.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:09:56,332] Trial 10 finished with value: 0.6407802490061704 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.6407802490061704.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 23:09:59,600] Trial 11 finished with value: 0.6592329087370825 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:10:02,704] Trial 12 finished with value: 0.6567193577906536 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:10:06,718] Trial 13 finished with value: 0.6284016912003729 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:10:09,855] Trial 14 finished with value: 0.6512466062195393 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:10:12,631] Trial 15 finished with value: 0.6391614236336937 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:10:17,549] Trial 16 finished with value: 0.6485959257482857 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:10:21,975] Trial 17 finished with value: 0.6338270731165728 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 416, 'learning_rate': 0.08639690405722114}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:10:24,119] Trial 18 finished with value: 0.6306830600216656 and parameters: {'subsample': 0.35801092912005106, 'dropout_rate': 0.33602353085084236, 'n_estimators': 256, 'learning_rate': 0.08307767561539126}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283

Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:10:24,751] Trial 19 finished with value: 0.6456442843661956 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7254192287154788, 'n_estimators': 117, 'learning_rate': 0.09614402133777997}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:10:29,606] Trial 20 finished with value: 0.6399513549568285 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 423, 'learning_rate': 0.07788582119853761}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:10:32,276] Trial 21 finished with value: 0.6503955423897523 and parameters: {'subsample': 0.11062421192073678, 'dropout_rate': 0.7075879968118339, 'n_estimators': 348, 'learning_rate': 0.09588015704350664}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:10:34,356] Trial 22 finished with value: 0.6401029680326689 and parameters: {'subsample': 0.17037433318378448, 'dropout_rate': 0.764223918656215, 'n_estimators': 305, 'learning_rate': 0.09979249643444077}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:10:37,045] Trial 23 finished with value: 0.6408997807816729 and parameters: {'subsample': 0.1882001920901971, 'dropout_rate': 0.5767392416088596, 'n_estimators': 339, 'learning_rate': 0.09228487500058613}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:10:39,620] Trial 24 finished with value: 0.6513445190444875 and parameters: {'subsample': 0.10032123431548137, 'dropout_rate': 0.9684931648209879, 'n_estimators': 388, 'learning_rate': 0.0802723125714484}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 23:10:42,215] Trial 25 finished with value: 0.6282206030751618 and parameters: {'subsample': 0.4133596270549855, 'dropout_rate': 0.9814337999737701, 'n_estimators': 405, 'learning_rate': 0.07897720038644866}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:10:44,004] Trial 26 finished with value: 0.6329687040178604 and parameters: {'subsample': 0.29436693962013616, 'dropout_rate': 0.30720738642318285, 'n_estimators': 245, 'learning_rate': 0.06349383809213646}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 23:10:48,258] Trial 27 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.9555788020080305, 'dropout_rate': 0.6087801618108066, 'n_estimators': 456, 'learning_rate': 0.06676860919367211}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 23:10:51,057] Trial 28 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6088999383640823, 'dropout_rate': 0.8192295755232234, 'n_estimators': 384, 'learning_rate': 0.08078072275147408}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 23:10:53,620] Trial 29 finished with value: 0.626684953002948 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.41533846889329507, 'n_estimators': 322, 'learning_rate': 0.0892538312157202}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:10:55,741] Trial 30 finished with value: 0.639216098557533 and parameters: {'subsample': 0.21797436717278929, 'dropout_rate': 0.16903977002361698, 'n_estimators': 283, 'learning_rate': 0.044040119088987244}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:10:58,347] Trial 31 finished with value: 0.6470276435458431 and parameters: {'subsample': 0.12927234629827838, 'dropout_rate': 0.9690972067181969, 'n_estimators': 383, 'learning_rate': 0.09233052029041879}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:11:02,511] Trial 32 finished with value: 0.6521197128429372 and parameters: {'subsample': 0.10197013154249483, 'dropout_rate': 0.9006234235846082, 'n_estimators': 449, 'learning_rate': 0.09214772080187031}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:11:06,602] Trial 33 finished with value: 0.6400197927324061 and parameters: {'subsample': 0.16421336528135802, 'dropout_rate': 0.9268713272970187, 'n_estimators': 453, 'learning_rate': 0.07794503671868204}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:11:11,387] Trial 34 finished with value: 0.6369052546868696 and parameters: {'subsample': 0.23087858755854718, 'dropout_rate': 0.8311198269799329, 'n_estimators': 477, 'learning_rate': 0.07104054321866782}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:11:12,706] Trial 35 finished with value: 0.6297883344477134 and parameters: {'subsample': 0.29440822025230656, 'dropout_rate': 0.9999753567840282, 'n_estimators': 232, 'learning_rate': 0.09340164470114515}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:11:18,769] Trial 36 finished with value: 0.6440689937510489 and parameters: {'subsample': 0.1472825644233607, 'dropout_rate': 0.45922216511134195, 'n_estimators': 490, 'learning_rate': 0.07364671948774787}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:11:23,130] Trial 37 finished with value: 0.6376657109606338 and parameters: {'subsample': 0.22877221290518623, 'dropout_rate': 0.5102437401048863, 'n_estimators': 437, 'learning_rate': 0.059207327336158105}. Best is trial 11 with value: 0.6592329087370825.

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 23:11:26,119] Trial 38 finished with value: 0.6280863337749738 and parameters: {'subsample': 0.3297325755614151, 'dropout_rate': 0.8867789132968811, 'n_estimators': 392, 'learning_rate': 0.08480908032505553}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:11:27,051] Trial 39 finished with value: 0.6408313430060953 and parameters: {'subsample': 0.1910828860959901, 'dropout_rate': 0.29848665859072016, 'n_estimators': 145, 'learning_rate': 0.06892741183938003}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 23:11:27,320] Trial 40 finished with value: 0.6274601468013976 and parameters: {'subsample': 0.43117832251264454, 'dropout_rate': 0.7942402623613096, 'n_estimators': 44, 'learning_rate': 0.09083529332655457}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:11:29,745] Trial 41 finished with value: 0.6513297815198023 and parameters: {'subsample': 0.10471436370118233, 'dropout_rate': 0.9432108264211424, 'n_estimators': 354, 'learning_rate': 0.0993939723603888}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:11:32,063] Trial 42 finished with value: 0.6497725124970339 and parameters: {'subsample': 0.10319905773816981, 'dropout_rate': 0.9428165272301137, 'n_estimators': 279, 'learning_rate': 0.09477321051183016}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:11:34,642] Trial 43 finished with value: 0.6392914177589797 and parameters: {'subsample': 0.1582430717253308, 'dropout_rate': 0.8684114133163081, 'n_estimators': 331, 'learning_rate': 0.0844262120808547}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 23:11:34,792] Trial 44 finished with value: 0.6319449589915695 and parameters: {'subsample': 0.24718870034059304, 'dropout_rate': 0.9241820789065098, 'n_estimators': 3, 'learning_rate': 0.08951219679204844}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 23:11:38,429] Trial 45 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.7937809606966539, 'dropout_rate': 0.20601602290044557, 'n_estimators': 362, 'learning_rate': 0.02274904980797578}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:11:40,904] Trial 46 finished with value: 0.6520001810674346 and parameters: {'subsample': 0.13247691307003695, 'dropout_rate': 0.14648424644002478, 'n_estimators': 281, 'learning_rate': 0.07635421514953118}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:11:42,565] Trial 47 finished with value: 0.6534600880951459 and parameters: {'subsample': 0.14373605878506748, 'dropout_rate': 0.13054548795135493, 'n_estimators': 215, 'learning_rate': 0.0761677554677633}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:11:44,275] Trial 48 finished with value: 0.6456120760790227 and parameters: {'subsample': 0.19286527393095337, 'dropout_rate': 0.12488098709371304, 'n_estimators': 212, 'learning_rate': 0.07434842044714275}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:11:45,530] Trial 49 finished with value: 0.6477375566495732 and parameters: {'subsample': 0.14597752026303154, 'dropout_rate': 0.1304931000922671, 'n_estimators': 186, 'learning_rate': 0.06553363235401288}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:11:47,202] Trial 50 finished with value: 0.635384342139341 and parameters: {'subsample': 0.30761800010369206, 'dropout_rate': 0.19987153451840467, 'n_estimators': 233, 'learning_rate': 0.05378378517676694}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:11:50,009] Trial 51 finished with value: 0.6511054554934825 and parameters: {'subsample': 0.14401662921117867, 'dropout_rate': 0.15451447610093666, 'n_estimators': 285, 'learning_rate': 0.08211289291272768}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:11:53,185] Trial 52 finished with value: 0.6469739432949508 and parameters: {'subsample': 0.1999908428792416, 'dropout_rate': 0.13211371506312394, 'n_estimators': 301, 'learning_rate': 0.07653114284553496}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:11:55,261] Trial 53 finished with value: 0.627521703151106 and parameters: {'subsample': 0.5690120024759672, 'dropout_rate': 0.28586431194579437, 'n_estimators': 262, 'learning_rate': 0.05951053705344814}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:11:56,854] Trial 54 finished with value: 0.6560204578665978 and parameters: {'subsample': 0.13424493836506077, 'dropout_rate': 0.10245911170083005, 'n_estimators': 202, 'learning_rate': 0.0814788871905445}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:11:57,766] Trial 55 finished with value: 0.6391545422078246 and parameters: {'subsample': 0.2525262633304453, 'dropout_rate': 0.21927377650904512, 'n_estimators': 140, 'learning_rate': 0.08641414429189137}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6920152091254753

Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 23:11:59,101] Trial 56 finished with value: 0.6577878662208916 and parameters: {'subsample': 0.13601361161349443, 'dropout_rate': 0.107333010007094, 'n_estimators': 169, 'learning_rate': 0.09629945800649439}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:12:00,243] Trial 57 finished with value: 0.6528876013724616 and parameters: {'subsample': 0.17573640157773612, 'dropout_rate': 0.10681264065747736, 'n_estimators': 153, 'learning_rate': 0.09617315401500287}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:12:01,348] Trial 58 finished with value: 0.652112407574012 and parameters: {'subsample': 0.17872819351209274, 'dropout_rate': 0.10187905549888307, 'n_estimators': 155, 'learning_rate': 0.0959528063113989}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 23:12:01,997] Trial 59 finished with value: 0.626684953002948 and parameters: {'subsample': 0.6869904791039767, 'dropout_rate': 0.2645251087109975, 'n_estimators': 103, 'learning_rate': 0.09670820913112874}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:12:03,424] Trial 60 finished with value: 0.6298030719723988 and parameters: {'subsample': 0.4010608863200944, 'dropout_rate': 0.18502656442051676, 'n_estimators': 191, 'learning_rate': 0.03136696153263342}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:12:04,161] Trial 61 finished with value: 0.6518989841747934 and parameters: {'subsample': 0.13316352431570933, 'dropout_rate': 0.16206963982225375, 'n_estimators': 111, 'learning_rate': 0.08787837544469908}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:12:05,561] Trial 62 finished with value: 0.6528876013724616 and parameters: {'subsample': 0.16422303726919274, 'dropout_rate': 0.10031838270385514, 'n_estimators': 160, 'learning_rate': 0.09101177249966563}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:12:06,898] Trial 63 finished with value: 0.6478138505239672 and parameters: {'subsample': 0.21781522049624352, 'dropout_rate': 0.10361841383755307, 'n_estimators': 169, 'learning_rate': 0.09700677893035418}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:12:08,514] Trial 64 finished with value: 0.6468612929453174 and parameters: {'subsample': 0.1711431343591786, 'dropout_rate': 0.18377072064689087, 'n_estimators': 203, 'learning_rate': 0.08333326003768003}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:12:09,812] Trial 65 finished with value: 0.6440837312757342 and parameters: {'subsample': 0.20047545316184032, 'dropout_rate': 0.25087525419938894, 'n_estimators': 167, 'learning_rate': 0.08975449043059357}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:12:10,288] Trial 66 finished with value: 0.6463188321018949 and parameters: {'subsample': 0.25862636503118125, 'dropout_rate': 0.14124814423428333, 'n_estimators': 73, 'learning_rate': 0.09350287892660586}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:12:12,218] Trial 67 finished with value: 0.6470675809449971 and parameters: {'subsample': 0.12695427941826193, 'dropout_rate': 0.35021251364269124, 'n_estimators': 222, 'learning_rate': 0.08737907363177463}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:12:13,067] Trial 68 finished with value: 0.6471329886265513 and parameters: {'subsample': 0.17246440371575278, 'dropout_rate': 0.22547873435201304, 'n_estimators': 122, 'learning_rate': 0.08110008595129617}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:12:14,317] Trial 69 finished with value: 0.6536011118343679 and parameters: {'subsample': 0.1547899152719588, 'dropout_rate': 0.10133439716419981, 'n_estimators': 178, 'learning_rate': 0.09853069608350322}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:12:16,221] Trial 70 finished with value: 0.6438194678502602 and parameters: {'subsample': 0.23541708391482083, 'dropout_rate': 0.1638212757370785, 'n_estimators': 248, 'learning_rate': 0.09948209459124774}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:12:17,411] Trial 71 finished with value: 0.6479728958555676 and parameters: {'subsample': 0.15629130511782707, 'dropout_rate': 0.11979723656720265, 'n_estimators': 177, 'learning_rate': 0.09176204056646853}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:12:18,269] Trial 72 finished with value: 0.6446852692047329 and parameters: {'subsample': 0.27398140809987526, 'dropout_rate': 0.10526093941163973, 'n_estimators': 136, 'learning_rate': 0.09457413414496828}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:12:19,779] Trial 73 finished with value: 0.6536048197451171 and parameters: {'subsample': 0.12526978721686902, 'dropout_rate': 0.1923985163654363, 'n_estimators': 206, 'learning_rate': 0.09705200300053905}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:12:21,271] Trial 74 finished with value: 0.6568320081402872 and parameters: {'subsample': 0.1261181183298701, 'dropout_rate': 0.18356410752263502, 'n_estimators': 199, 'learning_rate': 0.09763285049767803}. Best is trial 11 with value: 0.6592329087370825.

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:12:22,742] Trial 75 finished with value: 0.6551984452431251 and parameters: {'subsample': 0.1243386676766662, 'dropout_rate': 0.1896529687986803, 'n_estimators': 200, 'learning_rate': 0.09807934138441919}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:12:24,187] Trial 76 finished with value: 0.6487154575237883 and parameters: {'subsample': 0.12503607856505333, 'dropout_rate': 0.3852492115634457, 'n_estimators': 205, 'learning_rate': 0.09811759711025957}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 23:12:25,697] Trial 77 finished with value: 0.6577731286962062 and parameters: {'subsample': 0.10013660169282763, 'dropout_rate': 0.19221508758380867, 'n_estimators': 191, 'learning_rate': 0.09977961246174587}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:12:27,003] Trial 78 finished with value: 0.6503417151520252 and parameters: {'subsample': 0.12085027038378883, 'dropout_rate': 0.27253483720171706, 'n_estimators': 192, 'learning_rate': 0.09419600843697323}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:12:28,928] Trial 79 finished with value: 0.6440005559754713 and parameters: {'subsample': 0.21833630659079414, 'dropout_rate': 0.2025758278217061, 'n_estimators': 233, 'learning_rate': 0.08954262015241707}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:12:31,098] Trial 80 finished with value: 0.6544590570900242 and parameters: {'subsample': 0.10249576304451584, 'dropout_rate': 0.24493354811028714, 'n_estimators': 264, 'learning_rate': 0.007039353779474462}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:12:34,186] Trial 81 finished with value: 0.6486828253935595 and parameters: {'subsample': 0.11441080339464722, 'dropout_rate': 0.17989222885623662, 'n_estimators': 312, 'learning_rate': 0.012243494963687634}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:12:36,334] Trial 82 finished with value: 0.6512175550132249 and parameters: {'subsample': 0.10314091938429541, 'dropout_rate': 0.31524883090073247, 'n_estimators': 265, 'learning_rate': 0.039409325995905006}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:12:38,118] Trial 83 finished with value: 0.6504645309952208 and parameters: {'subsample': 0.12829175664866302, 'dropout_rate': 0.24307968677869796, 'n_estimators': 224, 'learning_rate': 0.09971855853680746}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:12:40,148] Trial 84 finished with value: 0.6368073418619213 and parameters: {'subsample': 0.20610676674191558, 'dropout_rate': 0.22567934002533935, 'n_estimators': 248, 'learning_rate': 0.009052539154175743}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:12:41,720] Trial 85 finished with value: 0.6454119752542244 and parameters: {'subsample': 0.14176314305333207, 'dropout_rate': 0.1460671641101797, 'n_estimators': 203, 'learning_rate': 0.046118625370362286}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:12:44,804] Trial 86 finished with value: 0.6400813490821144 and parameters: {'subsample': 0.18501146133150453, 'dropout_rate': 0.1901305296354311, 'n_estimators': 328, 'learning_rate': 0.0019216579476519216}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:12:46,800] Trial 87 finished with value: 0.6575014330149722 and parameters: {'subsample': 0.10110074646430062, 'dropout_rate': 0.15827733877496178, 'n_estimators': 240, 'learning_rate': 0.08595270502309552}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:12:49,279] Trial 88 finished with value: 0.6591349959121343 and parameters: {'subsample': 0.10184392592322274, 'dropout_rate': 0.1658909161206308, 'n_estimators': 292, 'learning_rate': 0.08611040743098104}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:12:51,687] Trial 89 finished with value: 0.6346602423408165 and parameters: {'subsample': 0.5132134792119997, 'dropout_rate': 0.16689331308725722, 'n_estimators': 292, 'learning_rate': 0.0930353905354716}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:12:54,701] Trial 90 finished with value: 0.6486281340354585 and parameters: {'subsample': 0.15203240268127038, 'dropout_rate': 0.1485198372703196, 'n_estimators': 339, 'learning_rate': 0.08503437017893135}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:12:57,354] Trial 91 finished with value: 0.6569078781716248 and parameters: {'subsample': 0.11280418308413018, 'dropout_rate': 0.2119841913213923, 'n_estimators': 313, 'learning_rate': 0.08646725911666892}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:13:00,139] Trial 92 finished with value: 0.6454235556980517 and parameters: {'subsample': 0.18684236281515304, 'dropout_rate': 0.21618353986100683, 'n_estimators': 314, 'learning_rate': 0.0865950741205122}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772

Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:13:03,224] Trial 93 finished with value: 0.6307705104968304 and parameters: {'subsample': 0.99766016156918, 'dropout_rate': 0.131246129187047, 'n_estimators': 345, 'learning_rate': 0.08858758771275754}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 23:13:05,433] Trial 94 finished with value: 0.656962002265573 and parameters: {'subsample': 0.10191381512789852, 'dropout_rate': 0.16965708610753913, 'n_estimators': 272, 'learning_rate': 0.08286808932694124}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 23:13:07,604] Trial 95 finished with value: 0.6585340088130266 and parameters: {'subsample': 0.1005555670555405, 'dropout_rate': 0.16277052568539307, 'n_estimators': 274, 'learning_rate': 0.07954618993412288}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 23:13:09,787] Trial 96 finished with value: 0.6585340088130266 and parameters: {'subsample': 0.10074919088969263, 'dropout_rate': 0.16519295901487138, 'n_estimators': 274, 'learning_rate': 0.0801524070565027}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:13:11,546] Trial 97 finished with value: 0.6505988002954087 and parameters: {'subsample': 0.10832861671712163, 'dropout_rate': 0.6519942420501896, 'n_estimators': 269, 'learning_rate': 0.07976945516968055}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:13:13,656] Trial 98 finished with value: 0.6476691188739958 and parameters: {'subsample': 0.15693005753525174, 'dropout_rate': 0.1689516411147559, 'n_estimators': 274, 'learning_rate': 0.08390702814839254}. Best is trial 11 with value: 0.6592329087370825.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6920152091254753

[I 2024-04-16 23:13:16,106] A new study created in memory with name: no-name-1f4ee931-c75a-4ed4-aefb-6498e331994d

Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 23:13:16,090] Trial 99 finished with value: 0.653785484027272 and parameters: {'subsample': 0.10060679808706854, 'dropout_rate': 0.20937514939932475, 'n_estimators': 298, 'learning_rate': 0.07065740945595554}. Best is trial 11 with value: 0.6592329087370825.


* Best trial for C-index:
 FrozenTrial(number=11, state=TrialState.COMPLETE, values=[0.6592329087370825], datetime_start=datetime.datetime(2024, 4, 16, 23, 9, 56, 336514), datetime_complete=datetime.datetime(2024, 4, 16, 23, 9, 59, 600192), params={'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=11, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}


* Best Score for C-index:
 0.6592329087370825

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.325676523044078
Fold 2 IBS: 0.24304825871263852
Fold 3 IBS: 0.32959725402563417
Fold 4 IBS: 0.28525857993950676
Fold 5 IBS: 0.27275166189156874
[I 2024-04-16 23:13:16,743] Trial 0 finished with value: 0.29126645552268526 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.4243468471583305
Fold 2 IBS: 0.3901688969230736
Fold 3 IBS: 0.3925037735733181
Fold 4 IBS: 0.37084045783124014
Fold 5 IBS: 0.34079939992495495
[I 2024-04-16 23:13:21,763] Trial 1 finished with value: 0.3837318750821835 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.388663470563614
Fold 2 IBS: 0.30068109749088767
Fold 3 IBS: 0.37991021668413694
Fold 4 IBS: 0.31125225156593306
Fold 5 IBS: 0.33025000236569196
[I 2024-04-16 23:13:22,701] Trial 2 finished with value: 0.3421514077340527 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.39180502103928067
Fold 2 IBS: 0.2723339174348366
Fold 3 IBS: 0.3810564835553453
Fold 4 IBS: 0.31083880707894046
Fold 5 IBS: 0.32302330983004995
[I 2024-04-16 23:13:24,054] Trial 3 finished with value: 0.3358115077876906 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.3942661310659211
Fold 2 IBS: 0.2772049604694292
Fold 3 IBS: 0.38328189502302645
Fold 4 IBS: 0.30946013671851486
Fold 5 IBS: 0.3384957344918201
[I 2024-04-16 23:13:26,013] Trial 4 finished with value: 0.3405417715537423 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.4122519263817958
Fold 2 IBS: 0.37802969684822957
Fold 3 IBS: 0.39159093324564376
Fold 4 IBS: 0.3474683993736778
Fold 5 IBS: 0.331005424885477
[I 2024-04-16 23:13:28,364] Trial 5 finished with value: 0.3720692761469648 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.29828726911528397
Fold 2 IBS: 0.21645133017694293
Fold 3 IBS: 0.29703048020856426
Fold 4 IBS: 0.2630471709724218
Fold 5 IBS: 0.24865969387198464
[I 2024-04-16 23:13:29,468] Trial 6 finished with value: 0.26469518886903953 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.26469518886903953.
Fold 1 IBS: 0.2557242083039886
Fold 2 IBS: 0.20086012542584775
Fold 3 IBS: 0.2559954533104581
Fold 4 IBS: 0.22842064037634063
Fold 5 IBS: 0.21078271864122022
[I 2024-04-16 23:13:29,708] Trial 7 finished with value: 0.23035662921157102 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.3320623714087893
Fold 2 IBS: 0.24778879382834276
Fold 3 IBS: 0.33914263875054795
Fold 4 IBS: 0.28890146090534946
Fold 5 IBS: 0.2812784361061495
[I 2024-04-16 23:13:30,961] Trial 8 finished with value: 0.2978347401998358 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.41355256605441043
Fold 2 IBS: 0.3803418251430308
Fold 3 IBS: 0.391840649836237
Fold 4 IBS: 0.35131804113613163
Fold 5 IBS: 0.3420174736572878
[I 2024-04-16 23:13:34,623] Trial 9 finished with value: 0.3758141111654195 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.24688672048424357
Fold 2 IBS: 0.23091253666135533
Fold 3 IBS: 0.22886383485395365
Fold 4 IBS: 0.2411627533361748
Fold 5 IBS: 0.22809345046771862
[I 2024-04-16 23:13:34,831] Trial 10 finished with value: 0.23518385916068918 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.24591184955753378
Fold 2 IBS: 0.22742364641206644
Fold 3 IBS: 0.22872479609872584
Fold 4 IBS: 0.23866162133190572
Fold 5 IBS: 0.22419206168941844
[I 2024-04-16 23:13:34,983] Trial 11 finished with value: 0.23298279501793004 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.2790631388372713
Fold 2 IBS: 0.20419323431705205
Fold 3 IBS: 0.2966943364224721
Fold 4 IBS: 0.25885632591202035
Fold 5 IBS: 0.24364787189121276
[I 2024-04-16 23:13:35,304] Trial 12 finished with value: 0.2564909814760057 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.24533484626464844
Fold 2 IBS: 0.22482603295491327
Fold 3 IBS: 0.2288900501286023
Fold 4 IBS: 0.2368692484235475
Fold 5 IBS: 0.22138571816323843
[I 2024-04-16 23:13:35,452] Trial 13 finished with value: 0.23146117918699 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.2838507400334174
Fold 2 IBS: 0.20578215313875153
Fold 3 IBS: 0.2862860280530503
Fold 4 IBS: 0.24790860860459804
Fold 5 IBS: 0.23314936884966506
[I 2024-04-16 23:13:35,995] Trial 14 finished with value: 0.2513953797358965 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.35006944344323987
Fold 2 IBS: 0.2540800090557494
Fold 3 IBS: 0.35764903579940016
Fold 4 IBS: 0.2961404203062488
Fold 5 IBS: 0.30092599232489686
[I 2024-04-16 23:13:36,528] Trial 15 finished with value: 0.311772980185907 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.35811636725816814
Fold 2 IBS: 0.2378198759358266
Fold 3 IBS: 0.3603550399452726
Fold 4 IBS: 0.2872889040643561
Fold 5 IBS: 0.3136331814440489
[I 2024-04-16 23:13:38,307] Trial 16 finished with value: 0.3114426737295345 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.24637560220536686
Fold 2 IBS: 0.21110503456978988
Fold 3 IBS: 0.23491938690940084
Fold 4 IBS: 0.22943718629070567
Fold 5 IBS: 0.21121348311812857
[I 2024-04-16 23:13:38,641] Trial 17 finished with value: 0.22661013861867835 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.291291305025286
Fold 2 IBS: 0.21140388138900232
Fold 3 IBS: 0.28863212236387226
Fold 4 IBS: 0.2563863518782749
Fold 5 IBS: 0.24311757382074356
[I 2024-04-16 23:13:41,194] Trial 18 finished with value: 0.2581662468954358 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2734286915536386
Fold 2 IBS: 0.20097901536547996
Fold 3 IBS: 0.2756019255493613

Fold 4 IBS: 0.2426706185564074
Fold 5 IBS: 0.22283081379821795
[I 2024-04-16 23:13:41,906] Trial 19 finished with value: 0.24310221296462103 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24550608887605468
Fold 2 IBS: 0.2133505584021398
Fold 3 IBS: 0.23294747738469943
Fold 4 IBS: 0.23024731593258208
Fold 5 IBS: 0.2123372739360029
[I 2024-04-16 23:13:42,321] Trial 20 finished with value: 0.22687774290629575 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2448259892509062
Fold 2 IBS: 0.21786672573833757
Fold 3 IBS: 0.23050391968540718
Fold 4 IBS: 0.23249100529840805
Fold 5 IBS: 0.215533050087791
[I 2024-04-16 23:13:42,661] Trial 21 finished with value: 0.22824413801216997 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24640086873642586
Fold 2 IBS: 0.2292326597688009
Fold 3 IBS: 0.22875342577755223
Fold 4 IBS: 0.23993607277337323
Fold 5 IBS: 0.22642423701728293
[I 2024-04-16 23:13:43,115] Trial 22 finished with value: 0.23414945281468702 and parameters: {'subsample': 0.6537769964653461, 'dropout_rate': 0.8093716219515759, 'n_estimators': 77, 'learning_rate': 0.0014039455806401802}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2589848196302069
Fold 2 IBS: 0.2024618720492697
Fold 3 IBS: 0.25302707950360914
Fold 4 IBS: 0.23227378691244918
Fold 5 IBS: 0.21704698047063445
[I 2024-04-16 23:13:43,879] Trial 23 finished with value: 0.23275890771323388 and parameters: {'subsample': 0.8534306852041174, 'dropout_rate': 0.801007553345817, 'n_estimators': 146, 'learning_rate': 0.013693154749890787}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24622272418585897
Fold 2 IBS: 0.211517231301511
Fold 3 IBS: 0.23465708353277137
Fold 4 IBS: 0.22958311755255775
Fold 5 IBS: 0.21133338172755428
[I 2024-04-16 23:13:44,192] Trial 24 finished with value: 0.2266627076600507 and parameters: {'subsample': 0.6057018904919792, 'dropout_rate': 0.9862533241546715, 'n_estimators': 62, 'learning_rate': 0.01572471796157672}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.27824402320018216
Fold 2 IBS: 0.20485085384499563
Fold 3 IBS: 0.2745783058664053
Fold 4 IBS: 0.24546543206826768
Fold 5 IBS: 0.23263373515357302
[I 2024-04-16 23:13:44,838] Trial 25 finished with value: 0.24715447002668472 and parameters: {'subsample': 0.8655825350862807, 'dropout_rate': 0.991151252373464, 'n_estimators': 145, 'learning_rate': 0.0210314188428598}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.33014689072398445
Fold 2 IBS: 0.24720038348309642
Fold 3 IBS: 0.3344515997942725
Fold 4 IBS: 0.28780550809923416
Fold 5 IBS: 0.2783585358589275
[I 2024-04-16 23:13:46,068] Trial 26 finished with value: 0.295592583591903 and parameters: {'subsample': 0.5978333574014947, 'dropout_rate': 0.8982223660451839, 'n_estimators': 222, 'learning_rate': 0.029166999751579693}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24499219484414198
Fold 2 IBS: 0.21624851273382031
Fold 3 IBS: 0.2314723911058174
Fold 4 IBS: 0.23142113333280664
Fold 5 IBS: 0.21391217014232608
[I 2024-04-16 23:13:46,354] Trial 27 finished with value: 0.2276092804317825 and parameters: {'subsample': 0.7973831324954838, 'dropout_rate': 0.9591162049738791, 'n_estimators': 39, 'learning_rate': 0.018143610116936895}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24515366399581964
Fold 2 IBS: 0.21501049991641955
Fold 3 IBS: 0.23211607481589766
Fold 4 IBS: 0.23087262715339726
Fold 5 IBS: 0.2134002972589192
[I 2024-04-16 23:13:46,756] Trial 28 finished with value: 0.22731063262809065 and parameters: {'subsample': 0.5742192061348756, 'dropout_rate': 0.920234801468329, 'n_estimators': 86, 'learning_rate': 0.008921459414064498}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.3063594897860022
Fold 2 IBS: 0.22365458368515215
Fold 3 IBS: 0.3055669075377605
Fold 4 IBS: 0.2699993099904004
Fold 5 IBS: 0.25609676833722445
[I 2024-04-16 23:13:47,292] Trial 29 finished with value: 0.2723354118673079 and parameters: {'subsample': 0.6850952456167174, 'dropout_rate': 0.7643659553187094, 'n_estimators': 112, 'learning_rate': 0.04248605264426071}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.3037100708108595
Fold 2 IBS: 0.22137743897919782
Fold 3 IBS: 0.3028696552655383
Fold 4 IBS: 0.2673327822795468
Fold 5 IBS: 0.253763234707761
[I 2024-04-16 23:13:48,208] Trial 30 finished with value: 0.2698106364085807 and parameters: {'subsample': 0.9166631566118534, 'dropout_rate': 0.6038945600293156, 'n_estimators': 166, 'learning_rate': 0.027648893219016982}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2449141797735416
Fold 2 IBS: 0.21676885376764835
Fold 3 IBS: 0.23117242159093349
Fold 4 IBS: 0.2319218743035483
Fold 5 IBS: 0.2146636746811494
[I 2024-04-16 23:13:48,677] Trial 31 finished with value: 0.2278882008233642 and parameters: {'subsample': 0.580266273279712, 'dropout_rate': 0.9271779254835972, 'n_estimators': 89, 'learning_rate': 0.007554955553126899}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24480968404806477
Fold 2 IBS: 0.21840173072243738
Fold 3 IBS: 0.2303084891481403
Fold 4 IBS: 0.23294002575148984
Fold 5 IBS: 0.21611746639599275
[I 2024-04-16 23:13:49,000] Trial 32 finished with value: 0.22851547921322504 and parameters: {'subsample': 0.7276466032162393, 'dropout_rate': 0.8648618701493432, 'n_estimators': 37, 'learning_rate': 0.015821999327691336}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24444290623218176
Fold 2 IBS: 0.22003318344553727
Fold 3 IBS: 0.23004295934041907
Fold 4 IBS: 0.23318439942131822
Fold 5 IBS: 0.21729227081764876
[I 2024-04-16 23:13:49,366] Trial 33 finished with value: 0.228999143851421 and parameters: {'subsample': 0.42583224460357205, 'dropout_rate': 0.9322585736914469, 'n_estimators': 74, 'learning_rate': 0.007128988064747212}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2599735862383478
Fold 2 IBS: 0.20223791307592695
Fold 3 IBS: 0.25497930340177116
Fold 4 IBS: 0.23208609347398076
Fold 5 IBS: 0.2141781691601287
[I 2024-04-16 23:13:50,017] Trial 34 finished with value: 0.2326910130700311 and parameters: {'subsample': 0.5577914444927095, 'dropout_rate': 0.9877256275541959, 'n_estimators': 127, 'learning_rate': 0.016160179473353013}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24663201725543496
Fold 2 IBS: 0.2300001255908101
Fold 3 IBS: 0.22880051556212538
Fold 4 IBS: 0.2405667786146309
Fold 5 IBS: 0.2271226637337803
[I 2024-04-16 23:13:50,243] Trial 35 finished with value: 0.23462442015135632 and parameters: {'subsample': 0.7803178043419461, 'dropout_rate': 0.43975685710717877, 'n_estimators': 13, 'learning_rate': 0.005826832206318818}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.367577937922695
Fold 2 IBS: 0.27682015096192025
Fold 3 IBS: 0.3682948275396474
Fold 4 IBS: 0.30452048859388936
Fold 5 IBS: 0.31541637422362634
[I 2024-04-16 23:13:54,392] Trial 36 finished with value: 0.32652595584835564 and parameters: {'subsample': 0.5171903924633928, 'dropout_rate': 0.2795306755316796, 'n_estimators': 421, 'learning_rate': 0.0238218995141648}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.39841893189624056
Fold 2 IBS: 0.32060019829104597
Fold 3 IBS: 0.3852983569562301
Fold 4 IBS: 0.31620276009532605
Fold 5 IBS: 0.33770453446230725
[I 2024-04-16 23:13:55,851] Trial 37 finished with value: 0.35164495634023 and parameters: {'subsample': 0.43420796750396373, 'dropout_rate': 0.7621022900062648, 'n_estimators': 241, 'learning_rate': 0.059207327336158105}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2614340968260537
Fold 2 IBS: 0.2021120088730102
Fold 3 IBS: 0.2566141669263308
Fold 4 IBS: 0.23453614765450895

Fold 5 IBS: 0.2122914778844625
[I 2024-04-16 23:13:56,944] Trial 38 finished with value: 0.2333975796328732 and parameters: {'subsample': 0.605229739689187, 'dropout_rate': 0.13272164755980653, 'n_estimators': 176, 'learning_rate': 0.01283698591663533}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2943463281154152
Fold 2 IBS: 0.21435275898375683
Fold 3 IBS: 0.292776623523439
Fold 4 IBS: 0.2606234117164125
Fold 5 IBS: 0.24191548716779984
[I 2024-04-16 23:13:57,274] Trial 39 finished with value: 0.26080292190136467 and parameters: {'subsample': 0.6970162917669863, 'dropout_rate': 0.48841341315505027, 'n_estimators': 59, 'learning_rate': 0.06892741183938003}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2956705905294083
Fold 2 IBS: 0.21430445848659016
Fold 3 IBS: 0.2928588854990794
Fold 4 IBS: 0.2596622123064148
Fold 5 IBS: 0.24678618384472736
[I 2024-04-16 23:13:57,904] Trial 40 finished with value: 0.261856466133244 and parameters: {'subsample': 0.8054982836102402, 'dropout_rate': 0.876813469756125, 'n_estimators': 112, 'learning_rate': 0.035912260209657}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2455156591195911
Fold 2 IBS: 0.2134495272871624
Fold 3 IBS: 0.23298021917302758
Fold 4 IBS: 0.2302623346190742
Fold 5 IBS: 0.21228868131417766
[I 2024-04-16 23:13:58,230] Trial 41 finished with value: 0.22689928430260659 and parameters: {'subsample': 0.9180988510314624, 'dropout_rate': 0.9438179242085731, 'n_estimators': 49, 'learning_rate': 0.017446250508837573}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2448957834513211
Fold 2 IBS: 0.2170005935741622
Fold 3 IBS: 0.2310161992206827
Fold 4 IBS: 0.23202460062538527
Fold 5 IBS: 0.21439769364800865
[I 2024-04-16 23:13:58,500] Trial 42 finished with value: 0.22786697410391196 and parameters: {'subsample': 0.9464169664396729, 'dropout_rate': 0.9430136432098365, 'n_estimators': 33, 'learning_rate': 0.020048086949614748}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2658273736705565
Fold 2 IBS: 0.2020524405250075
Fold 3 IBS: 0.2606080098559383
Fold 4 IBS: 0.23638269291325226
Fold 5 IBS: 0.2218591947364019
[I 2024-04-16 23:13:59,065] Trial 43 finished with value: 0.23734594234023126 and parameters: {'subsample': 0.8926693439285954, 'dropout_rate': 0.8370454250738812, 'n_estimators': 86, 'learning_rate': 0.027633234880330062}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24553832608292522
Fold 2 IBS: 0.22567851914167422
Fold 3 IBS: 0.22880097138904068
Fold 4 IBS: 0.23740161794197437
Fold 5 IBS: 0.22252686111769712
[I 2024-04-16 23:13:59,512] Trial 44 finished with value: 0.2319892591346623 and parameters: {'subsample': 0.7574766140068628, 'dropout_rate': 0.9209040458467185, 'n_estimators': 56, 'learning_rate': 0.004536994661454437}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24514475725184326
Fold 2 IBS: 0.2232932452954966
Fold 3 IBS: 0.229031285656079
Fold 4 IBS: 0.23565641281785177
Fold 5 IBS: 0.2206722434927271
[I 2024-04-16 23:13:59,781] Trial 45 finished with value: 0.23075958890279952 and parameters: {'subsample': 0.6254432766833774, 'dropout_rate': 0.7565492792792287, 'n_estimators': 25, 'learning_rate': 0.014308783844555807}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.34556775223404884
Fold 2 IBS: 0.26003024903765853
Fold 3 IBS: 0.35086044091810686
Fold 4 IBS: 0.29629520252719266
Fold 5 IBS: 0.2940333944770714
[I 2024-04-16 23:14:00,744] Trial 46 finished with value: 0.30935740783881566 and parameters: {'subsample': 0.5454269842024818, 'dropout_rate': 0.8816321250931852, 'n_estimators': 160, 'learning_rate': 0.048014785607437535}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2540323022244742
Fold 2 IBS: 0.19710437688289817
Fold 3 IBS: 0.25415324167744757
Fold 4 IBS: 0.22627491702741187
Fold 5 IBS: 0.21162765491344585
[I 2024-04-16 23:14:01,177] Trial 47 finished with value: 0.22863849854513557 and parameters: {'subsample': 0.2385519301616531, 'dropout_rate': 0.9917631969393944, 'n_estimators': 81, 'learning_rate': 0.02513395893947125}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.25728763936252025
Fold 2 IBS: 0.20231216512367317
Fold 3 IBS: 0.25262795298766366
Fold 4 IBS: 0.23138017803988314
Fold 5 IBS: 0.21120324156934484
[I 2024-04-16 23:14:02,616] Trial 48 finished with value: 0.23096223541661703 and parameters: {'subsample': 0.47852228408162223, 'dropout_rate': 0.19701471782839963, 'n_estimators': 193, 'learning_rate': 0.010411009503204737}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24673307008984274
Fold 2 IBS: 0.23042055290160676
Fold 3 IBS: 0.22882596707663166
Fold 4 IBS: 0.2408186354309607
Fold 5 IBS: 0.22754159795832032
[I 2024-04-16 23:14:02,778] Trial 49 finished with value: 0.23486796469147248 and parameters: {'subsample': 0.9361198918736817, 'dropout_rate': 0.6584903001856733, 'n_estimators': 2, 'learning_rate': 0.031855435969108184}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2703393986257053
Fold 2 IBS: 0.20257051463406026
Fold 3 IBS: 0.2660776078398826
Fold 4 IBS: 0.23954054354969337
Fold 5 IBS: 0.22554209413235315
[I 2024-04-16 23:14:03,572] Trial 50 finished with value: 0.24081403175633892 and parameters: {'subsample': 0.7006430134270305, 'dropout_rate': 0.8318264141869088, 'n_estimators': 134, 'learning_rate': 0.019642786526356794}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24526003850914455
Fold 2 IBS: 0.21467902770255018
Fold 3 IBS: 0.23231863109009884
Fold 4 IBS: 0.23070537111335643
Fold 5 IBS: 0.2129056406944009
[I 2024-04-16 23:14:03,859] Trial 51 finished with value: 0.2271737418219102 and parameters: {'subsample': 0.7994296496769766, 'dropout_rate': 0.9513190706056927, 'n_estimators': 45, 'learning_rate': 0.017594085400454734}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2465932017623929
Fold 2 IBS: 0.2299268996974446
Fold 3 IBS: 0.22878875620635092
Fold 4 IBS: 0.24043322363238803
Fold 5 IBS: 0.22699010755245638
[I 2024-04-16 23:14:04,223] Trial 52 finished with value: 0.23454643777020653 and parameters: {'subsample': 0.9522184225974055, 'dropout_rate': 0.9540184058192569, 'n_estimators': 65, 'learning_rate': 0.00125014832336073}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24483084636350344
Fold 2 IBS: 0.21994268306656278
Fold 3 IBS: 0.2298159042727
Fold 4 IBS: 0.23377868427496837
Fold 5 IBS: 0.217018869345563
[I 2024-04-16 23:14:04,509] Trial 53 finished with value: 0.22907739746465952 and parameters: {'subsample': 0.843494929630295, 'dropout_rate': 0.915585413735216, 'n_estimators': 46, 'learning_rate': 0.011064278636511417}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2542837578406007
Fold 2 IBS: 0.20408105962436318
Fold 3 IBS: 0.24632166462762337
Fold 4 IBS: 0.2299345290491981
Fold 5 IBS: 0.20927255603620012
[I 2024-04-16 23:14:04,733] Trial 54 finished with value: 0.2287787134355971 and parameters: {'subsample': 0.8204677487117119, 'dropout_rate': 0.3571755626038756, 'n_estimators': 21, 'learning_rate': 0.08270475242185228}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2534849870495454
Fold 2 IBS: 0.2041508121560885
Fold 3 IBS: 0.24576477799133983
Fold 4 IBS: 0.22971527127754243
Fold 5 IBS: 0.21306295114857882
[I 2024-04-16 23:14:05,263] Trial 55 finished with value: 0.229235759924619 and parameters: {'subsample': 0.8887421810659816, 'dropout_rate': 0.8993071903534846, 'n_estimators': 99, 'learning_rate': 0.01667266938646207}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24660568247659428
Fold 2 IBS: 0.21064080007395522
Fold 3 IBS: 0.23535116446600424
Fold 4 IBS: 0.22928161830063465
Fold 5 IBS: 0.21108618854351036
[I 2024-04-16 23:14:05,558] Trial 56 finished with value: 0.22659309077213977 and parameters: {'subsample': 0.7632340729628572, 'dropout_rate': 0.9968061240868161, 'n_estimators': 47, 'learning_rate': 0.0219993213211057}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.32634594317205234
Fold 2 IBS: 0.2441074249846434
Fold 3 IBS: 0.33090013102352434
Fold 4 IBS: 0.28596472610806994
Fold 5 IBS: 0.27461860801929316
[I 2024-04-16 23:14:07,258] Trial 57 finished with value: 0.29238736666151666 and parameters: {'subsample': 0.763955514973389, 'dropout_rate': 0.9964559295946985, 'n_estimators': 282, 'learning_rate': 0.02203371126489022}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2524958013314946
Fold 2 IBS: 0.20467957580837548

Fold 3 IBS: 0.24466604990129345
Fold 4 IBS: 0.22951388023914565
Fold 5 IBS: 0.21232254648299242
[I 2024-04-16 23:14:07,570] Trial 58 finished with value: 0.22873557075266032 and parameters: {'subsample': 0.8210665501105633, 'dropout_rate': 0.9557982366790785, 'n_estimators': 50, 'learning_rate': 0.03153701184110286}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2450766728615442
Fold 2 IBS: 0.21570571438138603
Fold 3 IBS: 0.23170031253784298
Fold 4 IBS: 0.23100841297079955
Fold 5 IBS: 0.21387190006582926
[I 2024-04-16 23:14:07,783] Trial 59 finished with value: 0.2274726025634804 and parameters: {'subsample': 0.7169412850975417, 'dropout_rate': 0.7863461136932807, 'n_estimators': 20, 'learning_rate': 0.03702429542217137}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2799925625848654
Fold 2 IBS: 0.20541721127231735
Fold 3 IBS: 0.27641891339421315
Fold 4 IBS: 0.24728738758668545
Fold 5 IBS: 0.231501204035336
[I 2024-04-16 23:14:08,391] Trial 60 finished with value: 0.24812345577468348 and parameters: {'subsample': 0.6580853749310097, 'dropout_rate': 0.8504207080106669, 'n_estimators': 120, 'learning_rate': 0.026233120654123206}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24506114552036967
Fold 2 IBS: 0.2227391563952413
Fold 3 IBS: 0.22917592951399726
Fold 4 IBS: 0.23541036546351077
Fold 5 IBS: 0.21951860445014307
[I 2024-04-16 23:14:08,806] Trial 61 finished with value: 0.23038104026865242 and parameters: {'subsample': 0.7368242492609791, 'dropout_rate': 0.9633166813429076, 'n_estimators': 74, 'learning_rate': 0.0051620199911569815}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.25624845596017926
Fold 2 IBS: 0.2031140844165004
Fold 3 IBS: 0.24945076411968525
Fold 4 IBS: 0.2308386419236711
Fold 5 IBS: 0.21467054375030795
[I 2024-04-16 23:14:09,374] Trial 62 finished with value: 0.23086449803406878 and parameters: {'subsample': 0.9008804237198612, 'dropout_rate': 0.8972785584562114, 'n_estimators': 99, 'learning_rate': 0.018480727132717638}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24525813986654407
Fold 2 IBS: 0.22394706204039122
Fold 3 IBS: 0.22893913491420798
Fold 4 IBS: 0.23632535189099202
Fold 5 IBS: 0.2214331425247103
[I 2024-04-16 23:14:09,622] Trial 63 finished with value: 0.2311805662473691 and parameters: {'subsample': 0.6297164279405434, 'dropout_rate': 0.5823907068184614, 'n_estimators': 34, 'learning_rate': 0.009594140607425444}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2456393866366244
Fold 2 IBS: 0.21299153169174545
Fold 3 IBS: 0.23361997509095692
Fold 4 IBS: 0.22975030626215406
Fold 5 IBS: 0.21253431380250287
[I 2024-04-16 23:14:09,963] Trial 64 finished with value: 0.22690710269679676 and parameters: {'subsample': 0.5245480196355067, 'dropout_rate': 0.9413786510901908, 'n_estimators': 62, 'learning_rate': 0.014230389833347484}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24436030005286818
Fold 2 IBS: 0.21456927917072746
Fold 3 IBS: 0.23251529067371102
Fold 4 IBS: 0.23061435502797772
Fold 5 IBS: 0.21371928695614437
[I 2024-04-16 23:14:10,305] Trial 65 finished with value: 0.22715570237628574 and parameters: {'subsample': 0.45473842457833824, 'dropout_rate': 0.9696337973251744, 'n_estimators': 60, 'learning_rate': 0.013175688908273541}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24425791895146917
Fold 2 IBS: 0.2144102132061209
Fold 3 IBS: 0.2326749313963326
Fold 4 IBS: 0.23050958085920942
Fold 5 IBS: 0.213580757387187
[I 2024-04-16 23:14:10,636] Trial 66 finished with value: 0.22708668036006383 and parameters: {'subsample': 0.4538390106754839, 'dropout_rate': 0.9973222357307537, 'n_estimators': 64, 'learning_rate': 0.012590689815234278}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.30111629951862323
Fold 2 IBS: 0.22040932376290737
Fold 3 IBS: 0.3017744714900754
Fold 4 IBS: 0.2662157921914366
Fold 5 IBS: 0.24893153605233173
[I 2024-04-16 23:14:12,670] Trial 67 finished with value: 0.26768948460307485 and parameters: {'subsample': 0.5164456222127641, 'dropout_rate': 0.9957101474211375, 'n_estimators': 321, 'learning_rate': 0.014042638169425688}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.37509937493932133
Fold 2 IBS: 0.28346838116750256
Fold 3 IBS: 0.3742704223614346
Fold 4 IBS: 0.3062111301277816
Fold 5 IBS: 0.32272587873763087
[I 2024-04-16 23:14:17,033] Trial 68 finished with value: 0.3323550374667342 and parameters: {'subsample': 0.396894830548818, 'dropout_rate': 0.8751386316641768, 'n_estimators': 496, 'learning_rate': 0.02170877428217187}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24693470011980795
Fold 2 IBS: 0.2311270655102999
Fold 3 IBS: 0.2288788081398321
Fold 4 IBS: 0.2412571776298174
Fold 5 IBS: 0.22851254319260392
[I 2024-04-16 23:14:17,244] Trial 69 finished with value: 0.2353420589184722 and parameters: {'subsample': 0.5321088311619213, 'dropout_rate': 0.6850428736307019, 'n_estimators': 11, 'learning_rate': 0.0033430171272597013}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.3852859364739752
Fold 2 IBS: 0.28723897149572053
Fold 3 IBS: 0.380296259387064
Fold 4 IBS: 0.3073003186028882
Fold 5 IBS: 0.3331257805315763
[I 2024-04-16 23:14:21,529] Trial 70 finished with value: 0.33864945329824486 and parameters: {'subsample': 0.29831657136945555, 'dropout_rate': 0.7160048016307664, 'n_estimators': 408, 'learning_rate': 0.030184746562878957}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2447983751594558
Fold 2 IBS: 0.21391212397472412
Fold 3 IBS: 0.2330229517211651
Fold 4 IBS: 0.23018009501747053
Fold 5 IBS: 0.21284182693141118
[I 2024-04-16 23:14:21,882] Trial 71 finished with value: 0.22695107456084535 and parameters: {'subsample': 0.4656561384348985, 'dropout_rate': 0.9607291922995583, 'n_estimators': 67, 'learning_rate': 0.012470692352433808}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24442739217118456
Fold 2 IBS: 0.2202080752130095
Fold 3 IBS: 0.22992449606500545
Fold 4 IBS: 0.23367467424256175
Fold 5 IBS: 0.21734687615024553
[I 2024-04-16 23:14:22,255] Trial 72 finished with value: 0.22911630276840134 and parameters: {'subsample': 0.44632544286302367, 'dropout_rate': 0.940927063465276, 'n_estimators': 66, 'learning_rate': 0.007736153984692023}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24873206449656773
Fold 2 IBS: 0.20714960221304482
Fold 3 IBS: 0.2391494048288076
Fold 4 IBS: 0.22844134347141637
Fold 5 IBS: 0.20990424423992582
[I 2024-04-16 23:14:22,782] Trial 73 finished with value: 0.2266753318499525 and parameters: {'subsample': 0.47075831672242574, 'dropout_rate': 0.9113190760145863, 'n_estimators': 107, 'learning_rate': 0.011745458975142266}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.255704669484436
Fold 2 IBS: 0.20256586151204847
Fold 3 IBS: 0.24898577012417628
Fold 4 IBS: 0.2304554628587353
Fold 5 IBS: 0.2113616322548472
[I 2024-04-16 23:14:23,317] Trial 74 finished with value: 0.22981467924684865 and parameters: {'subsample': 0.48487077302079995, 'dropout_rate': 0.818126846171267, 'n_estimators': 107, 'learning_rate': 0.01659395710476026}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.26069403640186745
Fold 2 IBS: 0.2002858960044775
Fold 3 IBS: 0.2590273478317007
Fold 4 IBS: 0.23277903197261338
Fold 5 IBS: 0.2129658995167273
[I 2024-04-16 23:14:23,780] Trial 75 finished with value: 0.23315044234547727 and parameters: {'subsample': 0.3931286314918456, 'dropout_rate': 0.9058514756642456, 'n_estimators': 93, 'learning_rate': 0.024132850675330414}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2449207774729007
Fold 2 IBS: 0.2164741146584261
Fold 3 IBS: 0.23115475964699578
Fold 4 IBS: 0.2318272715320025
Fold 5 IBS: 0.21495710360760373
[I 2024-04-16 23:14:24,017] Trial 76 finished with value: 0.22786680538358572 and parameters: {'subsample': 0.5683268745859826, 'dropout_rate': 0.8653081987830238, 'n_estimators': 34, 'learning_rate': 0.020347121996093395}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2506811440240583
Fold 2 IBS: 0.2053539697592853

Fold 3 IBS: 0.2432701864482772
Fold 4 IBS: 0.2284683602008423
Fold 5 IBS: 0.21006566848816424
[I 2024-04-16 23:14:24,856] Trial 77 finished with value: 0.22756786578412544 and parameters: {'subsample': 0.5096986308003991, 'dropout_rate': 0.49881327862855496, 'n_estimators': 145, 'learning_rate': 0.010267257888313383}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24728609182637104
Fold 2 IBS: 0.20948456237788454
Fold 3 IBS: 0.2367879689804507
Fold 4 IBS: 0.22900068533758589
Fold 5 IBS: 0.21042389725248523
[I 2024-04-16 23:14:25,273] Trial 78 finished with value: 0.2265966411549555 and parameters: {'subsample': 0.5939500427136554, 'dropout_rate': 0.7406477151463077, 'n_estimators': 73, 'learning_rate': 0.015420072941943445}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2491522359439618
Fold 2 IBS: 0.20720785646863638
Fold 3 IBS: 0.23970965460068624
Fold 4 IBS: 0.22880108027481874
Fold 5 IBS: 0.2102336161969871
[I 2024-04-16 23:14:25,752] Trial 79 finished with value: 0.22702088869701803 and parameters: {'subsample': 0.6723788047810191, 'dropout_rate': 0.7413305472330791, 'n_estimators': 82, 'learning_rate': 0.01601211448054851}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24520954400807898
Fold 2 IBS: 0.2238125298457514
Fold 3 IBS: 0.22900572731692778
Fold 4 IBS: 0.2362826500145415
Fold 5 IBS: 0.22138753922008994
[I 2024-04-16 23:14:26,042] Trial 80 finished with value: 0.23113959808107792 and parameters: {'subsample': 0.5472725501406392, 'dropout_rate': 0.7943244209025906, 'n_estimators': 49, 'learning_rate': 0.006807484156131071}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24699041341064157
Fold 2 IBS: 0.20997334219713817
Fold 3 IBS: 0.23605719801087272
Fold 4 IBS: 0.22913034206464886
Fold 5 IBS: 0.21064802263090768
[I 2024-04-16 23:14:26,502] Trial 81 finished with value: 0.2265598636628418 and parameters: {'subsample': 0.6070545538128025, 'dropout_rate': 0.6341528845468055, 'n_estimators': 76, 'learning_rate': 0.014291926646619518}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.26424067842199594
Fold 2 IBS: 0.2020280704264556
Fold 3 IBS: 0.2598748714749781
Fold 4 IBS: 0.2359141284498117
Fold 5 IBS: 0.21842360306513237
[I 2024-04-16 23:14:27,118] Trial 82 finished with value: 0.23609627036767472 and parameters: {'subsample': 0.5922453928972238, 'dropout_rate': 0.6191715075378723, 'n_estimators': 120, 'learning_rate': 0.019313878373930102}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24781953444770255
Fold 2 IBS: 0.20853906349093898
Fold 3 IBS: 0.23756791720192394
Fold 4 IBS: 0.22887020018619814
Fold 5 IBS: 0.21041983371444753
[I 2024-04-16 23:14:27,530] Trial 83 finished with value: 0.22664330980824224 and parameters: {'subsample': 0.6146609519724093, 'dropout_rate': 0.6421886730626755, 'n_estimators': 78, 'learning_rate': 0.015223953623176103}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.25409839780204135
Fold 2 IBS: 0.20375347292509463
Fold 3 IBS: 0.2467636455182986
Fold 4 IBS: 0.2300581935658389
Fold 5 IBS: 0.21199853281475728
[I 2024-04-16 23:14:27,928] Trial 84 finished with value: 0.22933444852520615 and parameters: {'subsample': 0.6143777540837653, 'dropout_rate': 0.5703883223273155, 'n_estimators': 78, 'learning_rate': 0.02181695324241678}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.2454340835099757
Fold 2 IBS: 0.2136961772818287
Fold 3 IBS: 0.23273056567389488
Fold 4 IBS: 0.23041441332302406
Fold 5 IBS: 0.21235879524348852
[I 2024-04-16 23:14:28,373] Trial 85 finished with value: 0.22692680700644238 and parameters: {'subsample': 0.6445770962436083, 'dropout_rate': 0.6275050227423727, 'n_estimators': 92, 'learning_rate': 0.009130620696524702}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24639926921114977
Fold 2 IBS: 0.22928356450634207
Fold 3 IBS: 0.228754183334704
Fold 4 IBS: 0.2399932817551604
Fold 5 IBS: 0.22623158679105324
[I 2024-04-16 23:14:28,584] Trial 86 finished with value: 0.23413237711968188 and parameters: {'subsample': 0.973596102528499, 'dropout_rate': 0.6913304253389554, 'n_estimators': 30, 'learning_rate': 0.003578120462130444}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.2781927071106972
Fold 2 IBS: 0.2046340904187838
Fold 3 IBS: 0.2743538100055575
Fold 4 IBS: 0.24537628788578655
Fold 5 IBS: 0.22685278282223925
[I 2024-04-16 23:14:29,212] Trial 87 finished with value: 0.24588193564861288 and parameters: {'subsample': 0.5848767613231778, 'dropout_rate': 0.5581423348405448, 'n_estimators': 110, 'learning_rate': 0.0276271691730997}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24497452272007741
Fold 2 IBS: 0.21606979660825898
Fold 3 IBS: 0.23139670442225413
Fold 4 IBS: 0.2314990720998036
Fold 5 IBS: 0.2141402661253793
[I 2024-04-16 23:14:29,487] Trial 88 finished with value: 0.22761607239515466 and parameters: {'subsample': 0.6722249946799236, 'dropout_rate': 0.6479045648592634, 'n_estimators': 46, 'learning_rate': 0.01557167084756894}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.26516278956994344
Fold 2 IBS: 0.20203982539169615
Fold 3 IBS: 0.2600655154320181
Fold 4 IBS: 0.23608038055976957
Fold 5 IBS: 0.21836273665359834
[I 2024-04-16 23:14:30,159] Trial 89 finished with value: 0.2363422495214051 and parameters: {'subsample': 0.6016440183315196, 'dropout_rate': 0.5918885750046846, 'n_estimators': 128, 'learning_rate': 0.018267143567723715}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24573908001820546
Fold 2 IBS: 0.2267737594491462
Fold 3 IBS: 0.22873715282488816
Fold 4 IBS: 0.23814825000178638
Fold 5 IBS: 0.22350505658163744
[I 2024-04-16 23:14:30,293] Trial 90 finished with value: 0.23258065977513276 and parameters: {'subsample': 0.7078102048337904, 'dropout_rate': 0.6730763431068749, 'n_estimators': 9, 'learning_rate': 0.02340866249635589}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24723648683966212
Fold 2 IBS: 0.2097930026030373
Fold 3 IBS: 0.23695352163573088
Fold 4 IBS: 0.22904234996289285
Fold 5 IBS: 0.21058878491646402
[I 2024-04-16 23:14:30,711] Trial 91 finished with value: 0.22672282919155742 and parameters: {'subsample': 0.5313026641418505, 'dropout_rate': 0.5328649004247455, 'n_estimators': 76, 'learning_rate': 0.014627227900695133}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24577407492517803
Fold 2 IBS: 0.21257383264762358
Fold 3 IBS: 0.23379619719392244
Fold 4 IBS: 0.2299460468627917
Fold 5 IBS: 0.21208238643358707
[I 2024-04-16 23:14:31,138] Trial 92 finished with value: 0.22683450761262053 and parameters: {'subsample': 0.5720522744908453, 'dropout_rate': 0.5211260831534085, 'n_estimators': 76, 'learning_rate': 0.011981813096347545}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.2464934086281741
Fold 2 IBS: 0.2109727784624746
Fold 3 IBS: 0.23508367038465994
Fold 4 IBS: 0.22944836247402864
Fold 5 IBS: 0.21128845087097128
[I 2024-04-16 23:14:31,610] Trial 93 finished with value: 0.22665733416406172 and parameters: {'subsample': 0.4994903777603958, 'dropout_rate': 0.5262836252450818, 'n_estimators': 87, 'learning_rate': 0.011492132047389617}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24588199063218563
Fold 2 IBS: 0.2125930156354007
Fold 3 IBS: 0.23390337282832738
Fold 4 IBS: 0.22995057861580706
Fold 5 IBS: 0.21216121330590818
[I 2024-04-16 23:14:32,052] Trial 94 finished with value: 0.22689803420352578 and parameters: {'subsample': 0.49968900942877426, 'dropout_rate': 0.523020546752894, 'n_estimators': 82, 'learning_rate': 0.011066289138468185}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24490369228481912
Fold 2 IBS: 0.2167329842481149
Fold 3 IBS: 0.23111158091166403
Fold 4 IBS: 0.23195611702074945
Fold 5 IBS: 0.21507941572440312
[I 2024-04-16 23:14:32,586] Trial 95 finished with value: 0.22795675803795015 and parameters: {'subsample': 0.5665760978972413, 'dropout_rate': 0.4628605993177724, 'n_estimators': 100, 'learning_rate': 0.006666098315025223}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.3528807852002724
Fold 2 IBS: 0.26163876419301324
Fold 3 IBS: 0.35927296600690356

Fold 4 IBS: 0.2978922662575483
Fold 5 IBS: 0.3041795583962892
[I 2024-04-16 23:14:33,535] Trial 96 finished with value: 0.31517286801080535 and parameters: {'subsample': 0.41313939490511475, 'dropout_rate': 0.5213109482382285, 'n_estimators': 158, 'learning_rate': 0.054487916689644846}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24708172105946397
Fold 2 IBS: 0.21005062605084635
Fold 3 IBS: 0.23658239945020892
Fold 4 IBS: 0.2291089640988238
Fold 5 IBS: 0.2105403389046395
[I 2024-04-16 23:14:33,968] Trial 97 finished with value: 0.2266728099127965 and parameters: {'subsample': 0.5389995281019297, 'dropout_rate': 0.6077476353900257, 'n_estimators': 73, 'learning_rate': 0.014931416501109941}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.26183286577938214
Fold 2 IBS: 0.20183342233582774
Fold 3 IBS: 0.2575253907596287
Fold 4 IBS: 0.23417362585495322
Fold 5 IBS: 0.21506795896798186
[I 2024-04-16 23:14:34,890] Trial 98 finished with value: 0.23408665273955473 and parameters: {'subsample': 0.545068613650571, 'dropout_rate': 0.5497522480626178, 'n_estimators': 139, 'learning_rate': 0.01569072107683937}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24506962981870725
Fold 2 IBS: 0.2156886398952901
Fold 3 IBS: 0.23166204482631356
Fold 4 IBS: 0.2313740373654556
Fold 5 IBS: 0.2142704544460028
[I 2024-04-16 23:14:35,446] Trial 99 finished with value: 0.22761296127035385 and parameters: {'subsample': 0.4999064806675035, 'dropout_rate': 0.6190205560651515, 'n_estimators': 90, 'learning_rate': 0.00800890927792778}. Best is trial 81 with value: 0.2265598636628418.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.2265598636628418], datetime_start=datetime.datetime(2024, 4, 16, 23, 14, 26, 46237), datetime_complete=datetime.datetime(2024, 4, 16, 23, 14, 26, 501704), params={'subsample': 0.6070545538128025, 'dropout_rate': 0.6341528845468055, 'n_estimators': 76, 'learning_rate': 0.014291926646619518}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=81, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.6070545538128025, 'dropout_rate': 0.6341528845468055, 'n_estimators': 76, 'learning_rate': 0.014291926646619518}


* Best Score for IBS:
 0.2265598636628418

In [78]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [79]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.659
train_ibs:  0.227

#### Test

In [80]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [81]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.10580803679784617,
                                              learning_rate=0.08933703080421439,
                                              n_estimators=324,
                                              random_state=123,
                                              subsample=0.11557957726835853)

C-index score: 0.536

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.6341528845468055,
                                              learning_rate=0.014291926646619518,
                                              n_estimators=76, random_state=123,
                                              subsample=0.6070545538128025)

IBS: 0.234

In [82]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [83]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
ExtraSurvivalTrees               0.835   1.0
Randomsurvivalforest             0.805   2.0
GradientBoosting                 0.730   3.0
CoxPH                            0.710   4.0
CoxLasso                         0.709   5.5
CoxElastic                       0.709   5.5
ComponentwiseGradientBoosting    0.659   7.0
CoxRidge                         0.655   8.0

In [84]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.196   1.0
ExtraSurvivalTrees             0.198   2.0
CoxLasso                       0.200   3.5
CoxElastic                     0.200   3.5
CoxPH                          0.201   5.0
ComponentwiseGradientBoosting  0.227   6.0
GradientBoosting               0.233   7.0
CoxRidge                       0.236   8.0

In [85]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
GradientBoosting                 0.591   1.0
ExtraSurvivalTrees               0.581   2.0
Randomsurvivalforest             0.579   3.0
CoxLasso                         0.566   4.0
CoxPH                            0.565   5.5
CoxElastic                       0.565   5.5
CoxRidge                         0.537   7.0
ComponentwiseGradientBoosting    0.536   8.0

In [86]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
CoxRidge                       0.229   1.5
GradientBoosting               0.229   1.5
ExtraSurvivalTrees             0.234   3.5
ComponentwiseGradientBoosting  0.234   3.5
Randomsurvivalforest           0.247   5.0
CoxLasso                       0.264   6.5
CoxElastic                     0.264   6.5
CoxPH                          0.265   8.0

In [87]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/dfs/standard/plsr/'  # Folder path where you want to save the files

# List of corresponding file namess
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_dfs_standard_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [88]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-16