In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from lifelines import CoxPHFitter
from sklearn.preprocessing import StandardScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
response_OUS.isna().sum().sum()

0

In [4]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [5]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [6]:
# Check null values in D3
clinical_train.isnull().sum().sum()

0

In [7]:
clinical_train

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,DFS,event_DFS
0,54.238356,1,0,1,0,0,1,0.0,0,0.000000,...,0.029974,0.815962,0.000000,0.002035,0.140311,0.000062,0.009991,0.000370,32.909589,0
1,54.539726,0,0,0,0,1,0,0.0,1,27.404795,...,0.059728,0.707300,0.000000,0.008732,0.191058,0.000349,0.023402,0.000699,27.715068,0
2,59.019178,0,1,0,0,0,1,0.0,1,41.019178,...,0.039463,0.819828,0.000034,0.002518,0.126531,0.000000,0.009452,0.000414,43.101370,1
3,70.726027,0,0,0,0,1,0,0.0,1,37.500000,...,0.061133,0.716212,0.000000,0.003296,0.192388,0.000000,0.018879,0.000899,17.589041,1
4,67.865753,0,0,0,0,1,0,0.0,1,53.000000,...,0.058589,0.696493,0.000199,0.008968,0.202073,0.000399,0.029892,0.001395,47.473973,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,60.435616,0,0,1,0,0,1,1.0,0,0.000000,...,0.029444,0.804831,0.000000,0.001442,0.152626,0.000000,0.009734,0.000361,41.490411,0
135,68.794521,0,0,1,0,0,1,1.0,0,0.000000,...,0.046451,0.792151,0.000000,0.004094,0.142778,0.000079,0.011810,0.000630,36.821918,0
136,57.498630,0,0,1,0,0,1,1.0,1,39.498630,...,0.016316,0.832202,0.000000,0.000914,0.140582,0.000000,0.009137,0.000522,40.043836,0
137,65.684932,0,0,1,0,0,1,1.0,1,71.527397,...,0.038862,0.787588,0.000000,0.003144,0.156640,0.000054,0.011978,0.000705,40.964384,0
138,61.676712,0,0,1,0,0,1,1.0,0,2.250000,...,0.011577,0.830670,0.000000,0.000978,0.147644,0.000000,0.008642,0.000408,30.608219,0

## Test dataset: MAASTRO

In [8]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [9]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [10]:
rows_with_nan = response_MAASTRO[response_MAASTRO.isna().any(axis=1)]

print("Rows with NaN values:")
print(rows_with_nan)

Rows with NaN values:
    patient_id  OS  OS_event  LRC  LRC_event  DFS  DFS_event
10          11 NaN       NaN  NaN        NaN  NaN        NaN
20          21 NaN       NaN  NaN        NaN  NaN        NaN
31          32 NaN       NaN  NaN        NaN  NaN        NaN
51          52 NaN       NaN  NaN        NaN  NaN        NaN
83          84 NaN       NaN  NaN        NaN  NaN        NaN
86          87 NaN       NaN  NaN        NaN  NaN        NaN

In [11]:
# Assuming your data is stored in a list or a pandas DataFrame/Series
# Convert data to a set for faster membership checking
data_set = set(list(response_MAASTRO['patient_id']))

# Find numbers from 1 to 114 not present in data
missing_numbers = set(range(1, 115)) - data_set

# Convert missing_numbers back to a sorted list
missing_numbers_list = sorted(missing_numbers)

print("Numbers from 1 to 114 not present in data:", missing_numbers_list)

Numbers from 1 to 114 not present in data: []

In [12]:
MAASTRO_D3

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_003_PET,LBP_012_PET,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET
0,1,55,0,0,1,0,0,1,1,1,...,0.000026,0.001181,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341
1,2,55,0,0,1,0,0,0,0,0,...,0.000056,0.002735,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335
2,3,55,0,0,1,0,0,0,0,1,...,0.000286,0.001888,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229
3,4,61,1,0,0,0,1,1,0,1,...,0.000160,0.003037,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240
4,6,70,0,0,1,0,0,1,1,1,...,0.000071,0.000881,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.000000,0.000544,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078
95,111,63,0,0,0,0,1,0,0,1,...,0.000109,0.000869,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489
96,112,63,0,0,1,0,0,1,1,1,...,0.000000,0.000734,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141
97,113,54,0,0,1,0,0,1,1,0,...,0.000114,0.001640,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038
98,114,62,0,0,0,1,0,1,0,0,...,0.000000,0.000225,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337

In [13]:
# Assuming your data is stored in a list or a pandas DataFrame/Series
# Convert data to a set for faster membership checking
data_set = set(list(MAASTRO_D3['patient_id']))

# Find numbers from 1 to 114 not present in data
missing_numbers = set(range(1, 115)) - data_set

# Convert missing_numbers back to a sorted list
missing_numbers_list = sorted(missing_numbers)

print("Numbers from 1 to 114 not present in data:", missing_numbers_list)

Numbers from 1 to 114 not present in data: [5, 9, 11, 21, 32, 36, 46, 52, 65, 76, 78, 81, 84, 87, 92]

In [14]:
# Assuming your data is stored in a list or a pandas DataFrame/Series
# Convert data to a set for faster membership checking
data_set = set(list(response_MAASTRO['patient_id']))

# Find numbers from 1 to 114 not present in data
missing_numbers = set(range(1, 115)) - data_set

# Convert missing_numbers back to a sorted list
missing_numbers_list = sorted(missing_numbers)

print("Numbers from 1 to 114 not present in data:", missing_numbers_list)

Numbers from 1 to 114 not present in data: []

In [15]:
# need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [16]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]

In [17]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [18]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [19]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [20]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 388)
y_train:  (139,)

(99, 390)

# Feature Selection: RENT

In [21]:
selected_features = [
"shape_Sphericity",
"hpv_related",
"glszm_SmallAreaLowGrayLevelEmphasis_CT_c16",
"LBP_102_PET",
"shape_Flatness",
"shape_Elongation",
"uicc8_III-IV",
"shape_MajorAxisLength",
"glrlm_HighGrayLevelRunEmphasis_PET_c04"]

# Selecting features in the DataFrame
X_rent = X[selected_features]
X_new = X_rent.copy()

X_MAASTRO_rent = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_rent.copy()

# Standardization

In [22]:
original_X = X.copy()

In [23]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = StandardScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [24]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns

MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [25]:
X_new

,shape_Sphericity,hpv_related,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,LBP_102_PET,shape_Flatness,shape_Elongation,uicc8_III-IV,shape_MajorAxisLength,glrlm_HighGrayLevelRunEmphasis_PET_c04
0,0.761164,0.0,0.029425,0.000000,0.535140,0.600926,0.0,42.073251,16.969770
1,0.697049,0.0,0.037915,0.000000,0.367109,0.841579,0.0,24.613845,15.598394
2,0.565792,0.0,0.008009,0.000034,0.597785,0.772821,1.0,48.030294,17.334294
3,0.684364,0.0,0.018398,0.000000,0.405730,0.847727,0.0,25.589900,14.009277
4,0.503142,0.0,0.013051,0.000199,0.442406,0.831483,0.0,34.684750,21.202180
...,...,...,...,...,...,...,...,...,...
134,0.742102,1.0,0.014938,0.000000,0.523608,0.680294,0.0,33.069705,16.110383
135,0.722918,1.0,0.011441,0.000000,0.735524,0.758193,1.0,41.043692,21.249575
136,0.652963,1.0,0.020431,0.000000,0.648063,0.770113,0.0,36.618802,14.873884
137,0.724255,1.0,0.019663,0.000000,0.492193,0.628897,1.0,45.870392,21.648860
138,0.722633,1.0,0.013864,0.000000,0.756267,0.892637,1.0,30.363259,20.191288

In [26]:
X_new_std

,shape_Sphericity,hpv_related,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,LBP_102_PET,shape_Flatness,shape_Elongation,uicc8_III-IV,shape_MajorAxisLength,glrlm_HighGrayLevelRunEmphasis_PET_c04
0,1.075042,0.0,1.274405,-0.562251,0.072232,-0.681983,0.0,-0.098422,0.081641
1,0.242767,0.0,2.273964,-0.562251,-1.302158,1.006304,0.0,-1.209119,-0.395928
2,-1.461057,0.0,-1.246890,-0.202838,0.584632,0.523938,1.0,0.280542,0.208583
3,0.078112,0.0,-0.023759,-0.562251,-0.986261,1.049432,0.0,-1.147026,-0.949323
4,-2.274305,0.0,-0.653294,1.514080,-0.686277,0.935477,0.0,-0.568449,1.555538
...,...,...,...,...,...,...,...,...,...
134,0.827589,1.0,-0.431120,-0.562251,-0.022089,-0.125182,0.0,-0.671191,-0.217633
135,0.578577,1.0,-0.842806,-0.562251,1.711257,0.421312,1.0,-0.163918,1.572043
136,-0.329498,1.0,0.215575,-0.562251,0.995873,0.504939,0.0,-0.445412,-0.648232
137,0.595927,1.0,0.125178,-0.562251,-0.279046,-0.485754,1.0,0.143137,1.711090
138,0.574872,1.0,-0.557574,-0.562251,1.880915,1.364493,1.0,-0.843364,1.203504

In [27]:
MAASTRO_new

,shape_Sphericity,hpv_related,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,LBP_102_PET,shape_Flatness,shape_Elongation,uicc8_III-IV,shape_MajorAxisLength,glrlm_HighGrayLevelRunEmphasis_PET_c04
0,0.668072,1,0.010495,0.000026,0.610062,0.765178,0,50.002093,19.034156
1,0.669961,0,0.035018,0.000167,0.504616,0.776540,1,41.753334,11.392444
2,0.624081,0,0.012819,0.000057,0.478604,0.697164,1,44.375483,14.567421
3,0.577624,0,0.029974,0.000000,0.446059,0.574636,1,46.115989,13.477331
4,0.630933,1,0.013458,0.000000,0.480378,0.633419,0,54.394967,16.365554
...,...,...,...,...,...,...,...,...,...
94,0.671754,0,0.039092,0.000000,0.577884,0.882411,1,34.218615,17.492295
95,0.632189,0,0.015831,0.000000,0.455642,0.535802,1,51.046869,14.267900
96,0.645548,1,0.011031,0.000000,0.631485,0.716610,1,50.417953,12.143752
97,0.727488,1,0.019801,0.000000,0.628338,0.665145,0,44.901412,15.300229
98,0.672838,0,0.015813,0.000000,0.469139,0.616262,1,36.574294,13.850774

In [28]:
MAASTRO_new_std

,shape_Sphericity,hpv_related,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,LBP_102_PET,shape_Flatness,shape_Elongation,uicc8_III-IV,shape_MajorAxisLength,glrlm_HighGrayLevelRunEmphasis_PET_c04
0,-0.133381,1,-0.954258,-0.288893,0.685053,0.470316,0,0.405980,0.800544
1,-0.108854,0,1.932841,1.182201,-0.177437,0.550025,1,-0.118774,-1.860610
2,-0.704414,0,-0.680666,0.033974,-0.390198,-0.006831,1,0.048037,-0.754955
3,-1.307469,0,1.338998,-0.562251,-0.656393,-0.866418,1,0.158761,-1.134568
4,-0.615466,1,-0.605333,-0.562251,-0.375685,-0.454030,0,0.685437,-0.128772
...,...,...,...,...,...,...,...,...,...
94,-0.085581,0,2.412550,-0.562251,0.421853,1.292755,1,-0.598102,0.263605
95,-0.599161,0,-0.326069,-0.562251,-0.578011,-1.138850,1,0.472444,-0.859260
96,-0.425762,1,-0.891107,-0.562251,0.860275,0.129595,1,0.432435,-1.598975
97,0.637891,1,0.141405,-0.562251,0.834539,-0.231458,0,0.081495,-0.499761
98,-0.071514,0,-0.328119,-0.562251,-0.467616,-0.574392,1,-0.448243,-1.004520

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [29]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-22 02:38:37,858] A new study created in memory with name: no-name-680b2ea9-9c52-4326-a1ce-b8ea4312af19

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-22 02:38:41,727] A new study created in memory with name: no-name-3e24e95d-5d3b-4bb8-809a-f8721811c38b

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.759656652360515
[I 2024-04-22 02:38:41,717] Trial 0 finished with value: 0.72444161978659 and parameters: {}. Best is trial 0 with value: 0.72444161978659.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.72444161978659], datetime_start=datetime.datetime(2024, 4, 22, 2, 38, 37, 919489), datetime_complete=datetime.datetime(2024, 4, 22, 2, 38, 41, 717502), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.72444161978659

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.22218111763385023
Fold 2 IBS: 0.18214519470787685
Fold 3 IBS: 0.19943058215780188
Fold 4 IBS: 0.2249881896341225
Fold 5 IBS: 0.17079109178266783
[I 2024-04-22 02:38:42,006] Trial 0 finished with value: 0.19990723518326386 and parameters: {}. Best is trial 0 with value: 0.19990723518326386.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.19990723518326386], datetime_start=datetime.datetime(2024, 4, 22, 2, 38, 41, 764006), datetime_complete=datetime.datetime(2024, 4, 22, 2, 38, 42, 6773), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.19990723518326386

In [30]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [31]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.724
train_ibs:  0.2

#### Test

In [32]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [33]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.562
IBS score: 0.29

In [34]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [35]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [36]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-22 02:38:42,184] A new study created in memory with name: no-name-2069cc69-37ff-4e7f-9150-06ec6ee3aaff

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.687984496124031

[I 2024-04-22 02:38:42,366] A new study created in memory with name: no-name-b353f750-ff02-41c0-b21b-481f53d9bc02

Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6759656652360515
[I 2024-04-22 02:38:42,361] Trial 0 finished with value: 0.6487951905080959 and parameters: {}. Best is trial 0 with value: 0.6487951905080959.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6487951905080959], datetime_start=datetime.datetime(2024, 4, 22, 2, 38, 42, 223786), datetime_complete=datetime.datetime(2024, 4, 22, 2, 38, 42, 361797), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6487951905080959

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709395077762
Fold 2 IBS: 0.2320398710570518
Fold 3 IBS: 0.22898186727039924
Fold 4 IBS: 0.24197476010091573
Fold 5 IBS: 0.2293955839675724
[I 2024-04-22 02:38:42,545] Trial 0 finished with value: 0.23592783526934333 and parameters: {}. Best is trial 0 with value: 0.23592783526934333.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592783526934333], datetime_start=datetime.datetime(2024, 4, 22, 2, 38, 42, 401852), datetime_complete=datetime.datetime(2024, 4, 22, 2, 38, 42, 544812), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592783526934333

In [37]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [38]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.649
train_ibs:  0.236

#### Test

In [39]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [40]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.537

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [41]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [42]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-22 02:38:42,698] A new study created in memory with name: no-name-66faff4f-994a-4d46-8563-6168b12e8155

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-22 02:38:43,010] Trial 0 finished with value: 0.7253468077103257 and parameters: {}. Best is trial 0 with value: 0.7253468077103257.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7253468077103257], datetime_start=datetime.datetime(2024, 4, 22, 2, 38, 42, 749705), datetime_complete=datetime.datetime(2024, 4, 22, 2, 38, 43, 10071), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7253468077103257

[I 2024-04-22 02:38:43,017] A new study created in memory with name: no-name-3f287d3a-0196-400d-af7f-115e5a37602b

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.22246158311007141
Fold 2 IBS: 0.18207907101733628
Fold 3 IBS: 0.19834248653978906
Fold 4 IBS: 0.22386774528137604
Fold 5 IBS: 0.16849199829394998
[I 2024-04-22 02:38:43,343] Trial 0 finished with value: 0.19904857684850458 and parameters: {}. Best is trial 0 with value: 0.19904857684850458.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.19904857684850458], datetime_start=datetime.datetime(2024, 4, 22, 2, 38, 43, 46763), datetime_complete=datetime.datetime(2024, 4, 22, 2, 38, 43, 343755), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.19904857684850458

In [43]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [44]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.725
train_ibs:  0.199

#### Test

In [45]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [46]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.561

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.289

In [47]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [48]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-22 02:38:43,543] A new study created in memory with name: no-name-29bcb60f-f875-4e96-8340-dd802b09beeb

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-22 02:38:43,937] Trial 0 finished with value: 0.7246474839432138 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7246474839432138.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:44,450] Trial 1 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:44,852] Trial 2 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:45,179] Trial 3 finished with value: 0.7246401786742884 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:45,476] Trial 4 finished with value: 0.722938051014714 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:45,859] Trial 5 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-22 02:38:46,228] Trial 6 finished with value: 0.7245716139118761 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 1 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-22 02:38:46,722] Trial 7 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 7 with value: 0.7254985477730008.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:47,132] Trial 8 finished with value: 0.7246401786742884 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 7 with value: 0.7254985477730008.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:47,441] Trial 9 finished with value: 0.7246401786742884 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 7 with value: 0.7254985477730008.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-22 02:38:47,668] Trial 10 finished with value: 0.7245716139118761 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 7 with value: 0.7254985477730008.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 02:38:47,747] Trial 11 finished with value: 0.638644863723714 and parameters: {'l1_ratio': 0.016444541243212374}. Best is trial 7 with value: 0.7254985477730008.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:48,063] Trial 12 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.21060026289682426}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 02:38:48,167] Trial 13 finished with value: 0.638644863723714 and parameters: {'l1_ratio': 0.005422066512732082}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:48,417] Trial 14 finished with value: 0.722938051014714 and parameters: {'l1_ratio': 0.6477687639749772}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-22 02:38:48,641] Trial 15 finished with value: 0.7246474839432138 and parameters: {'l1_ratio': 0.813973385171977}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:48,925] Trial 16 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.20258780980203966}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:49,228] Trial 17 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.14830506997108067}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:49,546] Trial 18 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.16713586918474027}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:49,951] Trial 19 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.347817720976353}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:50,359] Trial 20 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.10500472511016506}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:50,633] Trial 21 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.10457346814139208}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:50,885] Trial 22 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.26691967178375753}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:51,152] Trial 23 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.08462445338975066}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202

Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:51,395] Trial 24 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.21736087814603194}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:51,629] Trial 25 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.29520653393380936}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:51,828] Trial 26 finished with value: 0.6825802991707988 and parameters: {'l1_ratio': 0.06710037827301571}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:52,075] Trial 27 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.16547991235095477}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:52,299] Trial 28 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.355721226193779}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:52,588] Trial 29 finished with value: 0.7237891148445013 and parameters: {'l1_ratio': 0.5053531106326796}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:53,001] Trial 30 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.22613449849828293}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:53,358] Trial 31 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.10600692669306111}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:53,615] Trial 32 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.11836170503838453}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 02:38:53,699] Trial 33 finished with value: 0.6401626191903844 and parameters: {'l1_ratio': 0.031740267371820785}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:53,931] Trial 34 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.18540210140308402}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:54,176] Trial 35 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.3184485316780069}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:54,427] Trial 36 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.25775414301238114}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:54,621] Trial 37 finished with value: 0.6825802991707988 and parameters: {'l1_ratio': 0.061139250357173706}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:54,866] Trial 38 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.1161458251407331}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:55,095] Trial 39 finished with value: 0.7237891148445013 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:55,339] Trial 40 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.19090712345887903}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:55,604] Trial 41 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.08921283756765928}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:55,853] Trial 42 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.13628382653067045}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:56,052] Trial 43 finished with value: 0.6825802991707988 and parameters: {'l1_ratio': 0.059820186386939866}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 02:38:56,140] Trial 44 finished with value: 0.638644863723714 and parameters: {'l1_ratio': 0.0035689579284504114}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:56,379] Trial 45 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.26266589294633014}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:56,623] Trial 46 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.2136271539561408}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:56,898] Trial 47 finished with value: 0.7246401786742884 and parameters: {'l1_ratio': 0.5788602624367147}. Best is trial 12 with value: 0.72551286145463.

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-22 02:38:57,284] Trial 48 finished with value: 0.7237964201134265 and parameters: {'l1_ratio': 0.8619031648167028}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:57,637] Trial 49 finished with value: 0.7246401786742884 and parameters: {'l1_ratio': 0.3922995546354239}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:57,915] Trial 50 finished with value: 0.6825802991707988 and parameters: {'l1_ratio': 0.04929515585590637}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:58,276] Trial 51 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.14162684318794988}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:58,540] Trial 52 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.2225918073443785}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:58,872] Trial 53 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.19038495080367193}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:59,145] Trial 54 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.3207998617987887}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:59,464] Trial 55 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.09112751232466239}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:59,743] Trial 56 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.25436130616837704}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:00,020] Trial 57 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.1485457322726335}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:00,390] Trial 58 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.29524267417418004}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:00,773] Trial 59 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.09225315805063539}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:01,232] Trial 60 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.209512620319745}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:01,629] Trial 61 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.11056788873336157}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:01,998] Trial 62 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.16388710501518833}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 02:39:02,133] Trial 63 finished with value: 0.6409230754641486 and parameters: {'l1_ratio': 0.03473038863777376}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:02,801] Trial 64 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.0774533709140903}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:03,353] Trial 65 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.11584380757147564}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 02:39:03,517] Trial 66 finished with value: 0.638644863723714 and parameters: {'l1_ratio': 0.0010874063687122681}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:03,949] Trial 67 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.24056123634979776}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:04,424] Trial 68 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.1884562888068153}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:04,902] Trial 69 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.1382183825765909}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 02:39:05,173] Trial 70 finished with value: 0.6480943902051844 and parameters: {'l1_ratio': 0.03637366051884443}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:05,585] Trial 71 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.12149447850747198}. Best is trial 12 with value: 0.72551286145463.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:05,938] Trial 72 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.10132793302259019}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:06,273] Trial 73 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.1699357562942031}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:06,536] Trial 74 finished with value: 0.6825802991707988 and parameters: {'l1_ratio': 0.05345229134957362}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:06,827] Trial 75 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.2786772376054203}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:07,181] Trial 76 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.0803766538243207}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:07,510] Trial 77 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.16560067622044106}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:07,827] Trial 78 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.20679508261313598}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:08,162] Trial 79 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.13004156248864981}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-22 02:39:08,663] Trial 80 finished with value: 0.7237964201134265 and parameters: {'l1_ratio': 0.7625136716954102}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:09,073] Trial 81 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.11327828640166782}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 02:39:09,197] Trial 82 finished with value: 0.6385906126429308 and parameters: {'l1_ratio': 0.022830639942937422}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:09,469] Trial 83 finished with value: 0.6833771119198027 and parameters: {'l1_ratio': 0.06889959311151655}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:09,781] Trial 84 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.23034483875501793}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:10,193] Trial 85 finished with value: 0.7237891148445013 and parameters: {'l1_ratio': 0.6114164712527408}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:10,586] Trial 86 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.14890415839753526}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:10,979] Trial 87 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.1782405362042262}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:11,426] Trial 88 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.11096441515184843}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:11,842] Trial 89 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.3129275351006697}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:12,207] Trial 90 finished with value: 0.6825802991707988 and parameters: {'l1_ratio': 0.051348179038784345}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:12,723] Trial 91 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.243942659540539}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:13,305] Trial 92 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.20167520010808507}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:13,861] Trial 93 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.1520283931179556}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-22 02:39:14,460] Trial 94 finished with value: 0.7237964201134265 and parameters: {'l1_ratio': 0.9094578869039874}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:14,929] Trial 95 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.1275899400938891}. Best is trial 12 with value: 0.72551286145463.

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:15,267] Trial 96 finished with value: 0.724716048705626 and parameters: {'l1_ratio': 0.1838381586525182}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:15,602] Trial 97 finished with value: 0.7246401786742884 and parameters: {'l1_ratio': 0.4965881146918674}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:15,895] Trial 98 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.36675317639430205}. Best is trial 12 with value: 0.72551286145463.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012

[I 2024-04-22 02:39:16,260] A new study created in memory with name: no-name-89a5560d-0056-4250-a5b3-06bd2038f160

Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:16,253] Trial 99 finished with value: 0.72551286145463 and parameters: {'l1_ratio': 0.09596436362256448}. Best is trial 12 with value: 0.72551286145463.


* Best trial for C-index:
 FrozenTrial(number=12, state=TrialState.COMPLETE, values=[0.72551286145463], datetime_start=datetime.datetime(2024, 4, 22, 2, 38, 47, 748448), datetime_complete=datetime.datetime(2024, 4, 22, 2, 38, 48, 62721), params={'l1_ratio': 0.21060026289682426}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=12, value=None)


* Best Score for C-index:
 0.72551286145463

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.22257178566632613
Fold 2 IBS: 0.1820993520215423
Fold 3 IBS: 0.19824420949810542
Fold 4 IBS: 0.2237600380590431
Fold 5 IBS: 0.16835053901639
[I 2024-04-22 02:39:16,602] Trial 0 finished with value: 0.19900518485228139 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.19900518485228139.
Fold 1 IBS: 0.2227354190136121
Fold 2 IBS: 0.18213858361607235
Fold 3 IBS: 0.19817288921098417
Fold 4 IBS: 0.223810434637058
Fold 5 IBS: 0.168114353842255
[I 2024-04-22 02:39:16,923] Trial 1 finished with value: 0.19899433606399633 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.19899433606399633.
Fold 1 IBS: 0.22281124531110838
Fold 2 IBS: 0.1821437908934777
Fold 3 IBS: 0.19816656925728893
Fold 4 IBS: 0.2238096257112818
Fold 5 IBS: 0.16807007886952047
[I 2024-04-22 02:39:17,282] Trial 2 finished with value: 0.19900026200853546 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.19899433606399633.
Fold 1 IBS: 0.22263814890151476
Fold 2 IBS: 0.18211225930852412
Fold 3 IBS: 0.19818839773077662
Fold 4 IBS: 0.22381490989165742
Fold 5 IBS: 0.16828301434914938
[I 2024-04-22 02:39:17,614] Trial 3 finished with value: 0.19900734603632447 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.19899433606399633.
Fold 1 IBS: 0.22255767995045467
Fold 2 IBS: 0.18209772164678079
Fold 3 IBS: 0.19826340514368707
Fold 4 IBS: 0.22378204622672884
Fold 5 IBS: 0.168372873835193
[I 2024-04-22 02:39:17,930] Trial 4 finished with value: 0.1990147453605689 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.19899433606399633.
Fold 1 IBS: 0.22267955680338972
Fold 2 IBS: 0.18212405639006687
Fold 3 IBS: 0.19819481138174197
Fold 4 IBS: 0.22382605710912212
Fold 5 IBS: 0.16820539639880297
[I 2024-04-22 02:39:18,249] Trial 5 finished with value: 0.19900597561662473 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.19899433606399633.
Fold 1 IBS: 0.22246868969248
Fold 2 IBS: 0.18207995519171555
Fold 3 IBS: 0.19833322207414403
Fold 4 IBS: 0.22385768824919444
Fold 5 IBS: 0.16848759908928002
[I 2024-04-22 02:39:18,566] Trial 6 finished with value: 0.19904543085936283 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 1 with value: 0.19899433606399633.
Fold 1 IBS: 0.22257924169845975
Fold 2 IBS: 0.1821002158099212
Fold 3 IBS: 0.19823333207780275
Fold 4 IBS: 0.22374831781834717
Fold 5 IBS: 0.16834657791399912
[I 2024-04-22 02:39:18,893] Trial 7 finished with value: 0.199001537063706 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 1 with value: 0.19899433606399633.
Fold 1 IBS: 0.2226616743010439
Fold 2 IBS: 0.18211812433168464
Fold 3 IBS: 0.19819104384325545
Fold 4 IBS: 0.2238198085475922
Fold 5 IBS: 0.16824178829262804
[I 2024-04-22 02:39:19,243] Trial 8 finished with value: 0.19900648786324085 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 1 with value: 0.19899433606399633.
Fold 1 IBS: 0.22271702912777144
Fold 2 IBS: 0.18212642536439533
Fold 3 IBS: 0.1982380964980653
Fold 4 IBS: 0.22376203849068496
Fold 5 IBS: 0.16818507545523134
[I 2024-04-22 02:39:19,658] Trial 9 finished with value: 0.19900573298722968 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 1 with value: 0.19899433606399633.
Fold 1 IBS: 0.22292486673417503
Fold 2 IBS: 0.18215386254126925
Fold 3 IBS: 0.1980390467757735
Fold 4 IBS: 0.223818560092761
Fold 5 IBS: 0.1679814137478751
[I 2024-04-22 02:39:20,111] Trial 10 finished with value: 0.1989835499783708 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 10 with value: 0.1989835499783708.
Fold 1 IBS: 0.24623594048778857
Fold 2 IBS: 0.22994814297114965
Fold 3 IBS: 0.22889207161978525
Fold 4 IBS: 0.2402047040473762
Fold 5 IBS: 0.2279808538758689
[I 2024-04-22 02:39:20,421] Trial 11 finished with value: 0.23465234260039375 and parameters: {'l1_ratio': 0.016444541243212374}. Best is trial 10 with value: 0.1989835499783708.
Fold 1 IBS: 0.2228795555361651
Fold 2 IBS: 0.18215496432402492
Fold 3 IBS: 0.19801965882713443
Fold 4 IBS: 0.22380152075309812
Fold 5 IBS: 0.16796976235650646
[I 2024-04-22 02:39:21,266] Trial 12 finished with value: 0.1989650923593858 and parameters: {'l1_ratio': 0.0873928389796849}. Best is trial 12 with value: 0.1989650923593858.
Fold 1 IBS: 0.24703873580680735
Fold 2 IBS: 0.23160786897354574
Fold 3 IBS: 0.22895765184984243
Fold 4 IBS: 0.24161033394883666
Fold 5 IBS: 0.22910425434997894
[I 2024-04-22 02:39:21,479] Trial 13 finished with value: 0.23566376898580224 and parameters: {'l1_ratio': 0.003240751291247554}. Best is trial 12 with value: 0.1989650923593858.
Fold 1 IBS: 0.22286062318181205
Fold 2 IBS: 0.18215125063635013
Fold 3 IBS: 0.19813024792225187
Fold 4 IBS: 0.2237840809914024
Fold 5 IBS: 0.1679979628774174
[I 2024-04-22 02:39:21,898] Trial 14 finished with value: 0.19898483312184678 and parameters: {'l1_ratio': 0.14334023675256088}. Best is trial 12 with value: 0.1989650923593858.
Fold 1 IBS: 0.22285044103516718
Fold 2 IBS: 0.18215037067485793
Fold 3 IBS: 0.1980379720263535
Fold 4 IBS: 0.22380984020860314
Fold 5 IBS: 0.16800465448903426
[I 2024-04-22 02:39:22,360] Trial 15 finished with value: 0.19897065568680322 and parameters: {'l1_ratio': 0.14686204034367636}. Best is trial 12 with value: 0.1989650923593858.
Fold 1 IBS: 0.22276938783872988
Fold 2 IBS: 0.18213915440186298
Fold 3 IBS: 0.19810999126489554
Fold 4 IBS: 0.2237521534343332
Fold 5 IBS: 0.16809746005163367
[I 2024-04-22 02:39:22,720] Trial 16 finished with value: 0.19897362939829105 and parameters: {'l1_ratio': 0.26862840316492054}. Best is trial 12 with value: 0.1989650923593858.
Fold 1 IBS: 0.22284161698108365
Fold 2 IBS: 0.1821508636144355
Fold 3 IBS: 0.19805817751518418
Fold 4 IBS: 0.2237154560537881
Fold 5 IBS: 0.16799707486549664
[I 2024-04-22 02:39:23,120] Trial 17 finished with value: 0.19895263780599762 and parameters: {'l1_ratio': 0.13474554059223504}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22274638836160696
Fold 2 IBS: 0.18213148805249385
Fold 3 IBS: 0.19821950910185426
Fold 4 IBS: 0.2237443290288665
Fold 5 IBS: 0.1681486774599808
[I 2024-04-22 02:39:23,511] Trial 18 finished with value: 0.19899807840096048 and parameters: {'l1_ratio': 0.33883882709417557}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22281514618942658
Fold 2 IBS: 0.18214509849418073
Fold 3 IBS: 0.1980670751193884
Fold 4 IBS: 0.22382788346456517
Fold 5 IBS: 0.16805615925447256
[I 2024-04-22 02:39:23,941] Trial 19 finished with value: 0.1989822725044067 and parameters: {'l1_ratio': 0.20673426755385987}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22292049906311093
Fold 2 IBS: 0.1821541230375329
Fold 3 IBS: 0.19805436126981307
Fold 4 IBS: 0.22371719073444005
Fold 5 IBS: 0.16797707899821773
[I 2024-04-22 02:39:24,366] Trial 20 finished with value: 0.19896465062062293 and parameters: {'l1_ratio': 0.08981130083486043}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2229181830704498
Fold 2 IBS: 0.18215353064703746
Fold 3 IBS: 0.19805231411975766
Fold 4 IBS: 0.22371547620496607
Fold 5 IBS: 0.1679842218465455
[I 2024-04-22 02:39:24,781] Trial 21 finished with value: 0.19896474517775128 and parameters: {'l1_ratio': 0.09903825404401484}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2228979667837165
Fold 2 IBS: 0.18215663802711685
Fold 3 IBS: 0.22887023622145553
Fold 4 IBS: 0.22377986812186426
Fold 5 IBS: 0.16795084667318547
[I 2024-04-22 02:39:25,177] Trial 22 finished with value: 0.20513111116546773 and parameters: {'l1_ratio': 0.07027471624749185}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.222801169991859
Fold 2 IBS: 0.18214415655836674
Fold 3 IBS: 0.198094314896572
Fold 4 IBS: 0.22374275758887774
Fold 5 IBS: 0.16805145055827053
[I 2024-04-22 02:39:25,562] Trial 23 finished with value: 0.1989667699187892 and parameters: {'l1_ratio': 0.21189845023299922}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22285873193152714
Fold 2 IBS: 0.18214916133475637
Fold 3 IBS: 0.19811727581045627
Fold 4 IBS: 0.22376741612696843
Fold 5 IBS: 0.16802293962882087
[I 2024-04-22 02:39:25,972] Trial 24 finished with value: 0.19898310496650579 and parameters: {'l1_ratio': 0.17460955169109116}. Best is trial 17 with value: 0.19895263780599762.

Fold 1 IBS: 0.22276760247931948
Fold 2 IBS: 0.18213554366252352
Fold 3 IBS: 0.19820478433293948
Fold 4 IBS: 0.22373156244662298
Fold 5 IBS: 0.16811705989773507
[I 2024-04-22 02:39:26,607] Trial 25 finished with value: 0.19899131056382807 and parameters: {'l1_ratio': 0.29603955452978525}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22292920550164558
Fold 2 IBS: 0.1821559687414617
Fold 3 IBS: 0.2288717925709272
Fold 4 IBS: 0.2362661042284526
Fold 5 IBS: 0.16801617794830886
[I 2024-04-22 02:39:26,972] Trial 26 finished with value: 0.20764784979815923 and parameters: {'l1_ratio': 0.06084361560373101}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22261093088211753
Fold 2 IBS: 0.18210937093302623
Fold 3 IBS: 0.19823058061874096
Fold 4 IBS: 0.2237467678392062
Fold 5 IBS: 0.16829739322937062
[I 2024-04-22 02:39:27,339] Trial 27 finished with value: 0.1989990087004923 and parameters: {'l1_ratio': 0.58416616744615}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22247472130547077
Fold 2 IBS: 0.1820807058448089
Fold 3 IBS: 0.19832532255411406
Fold 4 IBS: 0.2238491118410043
Fold 5 IBS: 0.16845960332226154
[I 2024-04-22 02:39:27,673] Trial 28 finished with value: 0.19903789297353192 and parameters: {'l1_ratio': 0.964957522585106}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22272297865666943
Fold 2 IBS: 0.1821297155057711
Fold 3 IBS: 0.19814742428211443
Fold 4 IBS: 0.22378230536885702
Fold 5 IBS: 0.16815963996675887
[I 2024-04-22 02:39:28,048] Trial 29 finished with value: 0.19898841275603416 and parameters: {'l1_ratio': 0.3532703801041919}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22289528474411904
Fold 2 IBS: 0.18215119140599004
Fold 3 IBS: 0.19808144941118655
Fold 4 IBS: 0.22373962636178787
Fold 5 IBS: 0.16799128742474898
[I 2024-04-22 02:39:28,474] Trial 30 finished with value: 0.1989717678695665 and parameters: {'l1_ratio': 0.12405952050715788}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.24723799291059922
Fold 2 IBS: 0.23202098430511844
Fold 3 IBS: 0.2289807499798993
Fold 4 IBS: 0.24195884615215713
Fold 5 IBS: 0.22938286147296194
[I 2024-04-22 02:39:28,640] Trial 31 finished with value: 0.2359162869641472 and parameters: {'l1_ratio': 0.00014026861561389214}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22293793770152906
Fold 2 IBS: 0.18215573542279664
Fold 3 IBS: 0.22887033045986613
Fold 4 IBS: 0.22381360197932387
Fold 5 IBS: 0.16795990132708738
[I 2024-04-22 02:39:29,005] Trial 32 finished with value: 0.20514750137812063 and parameters: {'l1_ratio': 0.07239936053029342}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22276892005667578
Fold 2 IBS: 0.18213912002161622
Fold 3 IBS: 0.19811086503652117
Fold 4 IBS: 0.2237529930914519
Fold 5 IBS: 0.16809769097176733
[I 2024-04-22 02:39:29,468] Trial 33 finished with value: 0.19897391783560647 and parameters: {'l1_ratio': 0.26885785665723927}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22286786631278427
Fold 2 IBS: 0.18214722044426518
Fold 3 IBS: 0.19810030560766084
Fold 4 IBS: 0.22375122052437865
Fold 5 IBS: 0.16801873107993423
[I 2024-04-22 02:39:29,863] Trial 34 finished with value: 0.19897706879380467 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22289328113536327
Fold 2 IBS: 0.1821548033480209
Fold 3 IBS: 0.19810137406156947
Fold 4 IBS: 0.22376208176098944
Fold 5 IBS: 0.16797656086888085
[I 2024-04-22 02:39:30,256] Trial 35 finished with value: 0.19897762023496476 and parameters: {'l1_ratio': 0.10309534739192076}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22251627736738153
Fold 2 IBS: 0.1820862672340182
Fold 3 IBS: 0.19827139575756694
Fold 4 IBS: 0.22378900066217777
Fold 5 IBS: 0.16843578414765983
[I 2024-04-22 02:39:30,620] Trial 36 finished with value: 0.19901974503376085 and parameters: {'l1_ratio': 0.867380700139649}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22278232272138673
Fold 2 IBS: 0.18214319340234736
Fold 3 IBS: 0.19812225981508197
Fold 4 IBS: 0.223767250113703
Fold 5 IBS: 0.16805857398740717
[I 2024-04-22 02:39:31,006] Trial 37 finished with value: 0.19897472000798525 and parameters: {'l1_ratio': 0.21747007802204765}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22296133598826592
Fold 2 IBS: 0.2269627723676956
Fold 3 IBS: 0.22888375189117455
Fold 4 IBS: 0.23765896786911325
Fold 5 IBS: 0.22594503498370172
[I 2024-04-22 02:39:31,235] Trial 38 finished with value: 0.22848237261999021 and parameters: {'l1_ratio': 0.04367588573103746}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2226479623468935
Fold 2 IBS: 0.18212098614051114
Fold 3 IBS: 0.1982470011922957
Fold 4 IBS: 0.2237688486422875
Fold 5 IBS: 0.16822201765003184
[I 2024-04-22 02:39:31,695] Trial 39 finished with value: 0.19900136319440392 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22274793072167762
Fold 2 IBS: 0.18213405317525075
Fold 3 IBS: 0.19812768051130925
Fold 4 IBS: 0.22376621717835765
Fold 5 IBS: 0.16812675938504107
[I 2024-04-22 02:39:32,078] Trial 40 finished with value: 0.19898052819432727 and parameters: {'l1_ratio': 0.30694418829932546}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2228143920513812
Fold 2 IBS: 0.18214504741299903
Fold 3 IBS: 0.19806854994579687
Fold 4 IBS: 0.22371808378963512
Fold 5 IBS: 0.16805651203057353
[I 2024-04-22 02:39:32,605] Trial 41 finished with value: 0.19896051704607715 and parameters: {'l1_ratio': 0.20700744989269948}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2229005538312161
Fold 2 IBS: 0.18215521833258017
Fold 3 IBS: 0.19808710762835716
Fold 4 IBS: 0.22374854113832454
Fold 5 IBS: 0.167973341895035
[I 2024-04-22 02:39:33,151] Trial 42 finished with value: 0.19897295256510258 and parameters: {'l1_ratio': 0.10188219823404308}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22280539458486628
Fold 2 IBS: 0.1821418346772312
Fold 3 IBS: 0.19815948982599865
Fold 4 IBS: 0.22380027032230046
Fold 5 IBS: 0.16808837360699336
[I 2024-04-22 02:39:33,567] Trial 43 finished with value: 0.198999072603478 and parameters: {'l1_ratio': 0.2518946649765156}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22283464321751162
Fold 2 IBS: 0.18214756613801672
Fold 3 IBS: 0.19816165569605823
Fold 4 IBS: 0.22380970289052182
Fold 5 IBS: 0.16803411455849276
[I 2024-04-22 02:39:34,008] Trial 44 finished with value: 0.19899753650012025 and parameters: {'l1_ratio': 0.18188247613428807}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22261331915904803
Fold 2 IBS: 0.18211306258345017
Fold 3 IBS: 0.19826858827100938
Fold 4 IBS: 0.22378940604985564
Fold 5 IBS: 0.16827432927248667
[I 2024-04-22 02:39:34,343] Trial 45 finished with value: 0.19901174106716996 and parameters: {'l1_ratio': 0.532905188903257}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22295101747037732
Fold 2 IBS: 0.22729180754316497
Fold 3 IBS: 0.22888748385137972
Fold 4 IBS: 0.2379401960571237
Fold 5 IBS: 0.22617014349197545
[I 2024-04-22 02:39:34,629] Trial 46 finished with value: 0.22864812968280424 and parameters: {'l1_ratio': 0.04042382084036109}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22288942271650516
Fold 2 IBS: 0.18215038194299785
Fold 3 IBS: 0.1980753357396461
Fold 4 IBS: 0.2237318174626926
Fold 5 IBS: 0.16800099207236757
[I 2024-04-22 02:39:35,020] Trial 47 finished with value: 0.19896958998684186 and parameters: {'l1_ratio': 0.13669806689804087}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22271950333962234
Fold 2 IBS: 0.18212663544984714
Fold 3 IBS: 0.19823417992197362
Fold 4 IBS: 0.22375790352459302
Fold 5 IBS: 0.1681838541039843
[I 2024-04-22 02:39:35,587] Trial 48 finished with value: 0.19900441526800408 and parameters: {'l1_ratio': 0.39033623695293396}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2227880614354531
Fold 2 IBS: 0.18214214657635955
Fold 3 IBS: 0.1980939491597786
Fold 4 IBS: 0.22373963429688037
Fold 5 IBS: 0.16807122635685645
[I 2024-04-22 02:39:35,959] Trial 49 finished with value: 0.19896700356506564 and parameters: {'l1_ratio': 0.236420559222994}. Best is trial 17 with value: 0.19895263780599762.

Fold 1 IBS: 0.22259390568462686
Fold 2 IBS: 0.18210751576992903
Fold 3 IBS: 0.1982566064103785
Fold 4 IBS: 0.22377442069288553
Fold 5 IBS: 0.1683168168243539
[I 2024-04-22 02:39:36,329] Trial 50 finished with value: 0.19900985307643476 and parameters: {'l1_ratio': 0.6064718647459368}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22284765568252515
Fold 2 IBS: 0.18214842371985313
Fold 3 IBS: 0.198137752364713
Fold 4 IBS: 0.22378693605406708
Fold 5 IBS: 0.16802806434961035
[I 2024-04-22 02:39:36,760] Trial 51 finished with value: 0.19898976643415373 and parameters: {'l1_ratio': 0.1778917020771571}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2228978928621057
Fold 2 IBS: 0.18215506607257112
Fold 3 IBS: 0.19809233332009074
Fold 4 IBS: 0.2237535021189615
Fold 5 IBS: 0.16797451868082638
[I 2024-04-22 02:39:37,170] Trial 52 finished with value: 0.19897466261091107 and parameters: {'l1_ratio': 0.10232328574307577}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2227856704661892
Fold 2 IBS: 0.1821434161653403
Fold 3 IBS: 0.19811578876754088
Fold 4 IBS: 0.22376105409052094
Fold 5 IBS: 0.16805691541551573
[I 2024-04-22 02:39:37,536] Trial 53 finished with value: 0.1989725689810214 and parameters: {'l1_ratio': 0.2161540868975238}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22287856842364748
Fold 2 IBS: 0.18214878288636577
Fold 3 IBS: 0.19809190350390368
Fold 4 IBS: 0.2237454772306094
Fold 5 IBS: 0.16801707722509424
[I 2024-04-22 02:39:37,899] Trial 54 finished with value: 0.19897636185392412 and parameters: {'l1_ratio': 0.1537400678550696}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.24576824037400177
Fold 2 IBS: 0.22898373318497842
Fold 3 IBS: 0.2288765854536239
Fold 4 IBS: 0.23938418927026198
Fold 5 IBS: 0.22732503273796714
[I 2024-04-22 02:39:38,064] Trial 55 finished with value: 0.23406755620416667 and parameters: {'l1_ratio': 0.024711693103081855}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22272039263019416
Fold 2 IBS: 0.1821335510870052
Fold 3 IBS: 0.19817737650639358
Fold 4 IBS: 0.22381201152105692
Fold 5 IBS: 0.16814047491984518
[I 2024-04-22 02:39:38,535] Trial 56 finished with value: 0.198996761332899 and parameters: {'l1_ratio': 0.32341475168304346}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22293900940444766
Fold 2 IBS: 0.18215578520788406
Fold 3 IBS: 0.22887032083457273
Fold 4 IBS: 0.2238117179755251
Fold 5 IBS: 0.16795884241740772
[I 2024-04-22 02:39:39,010] Trial 57 finished with value: 0.20514713516796745 and parameters: {'l1_ratio': 0.0722779279284854}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22284828909078966
Fold 2 IBS: 0.18214737335356673
Fold 3 IBS: 0.1981232165422161
Fold 4 IBS: 0.22377069815666398
Fold 5 IBS: 0.16804075681041006
[I 2024-04-22 02:39:39,561] Trial 58 finished with value: 0.1989860667907293 and parameters: {'l1_ratio': 0.1953040218129638}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22287803752693472
Fold 2 IBS: 0.18215276825171114
Fold 3 IBS: 0.19811467452616566
Fold 4 IBS: 0.22377122013400802
Fold 5 IBS: 0.16799891038201278
[I 2024-04-22 02:39:40,050] Trial 59 finished with value: 0.19898312216416647 and parameters: {'l1_ratio': 0.12761296203646663}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2227081189095051
Fold 2 IBS: 0.18212991904602877
Fold 3 IBS: 0.1981726858172653
Fold 4 IBS: 0.22380746746988073
Fold 5 IBS: 0.16816704365710985
[I 2024-04-22 02:39:40,492] Trial 60 finished with value: 0.19899704697995796 and parameters: {'l1_ratio': 0.36354862584154113}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2227759200432133
Fold 2 IBS: 0.18214129568947376
Fold 3 IBS: 0.1981171019777758
Fold 4 IBS: 0.2237618309022943
Fold 5 IBS: 0.1680772176343367
[I 2024-04-22 02:39:40,925] Trial 61 finished with value: 0.19897467324941878 and parameters: {'l1_ratio': 0.2416652965195859}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2227870697738751
Fold 2 IBS: 0.18214207682079328
Fold 3 IBS: 0.19809584563695096
Fold 4 IBS: 0.22374145336685136
Fold 5 IBS: 0.16807171442199564
[I 2024-04-22 02:39:41,358] Trial 62 finished with value: 0.19896763200409326 and parameters: {'l1_ratio': 0.23684160828718387}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22293384716796347
Fold 2 IBS: 0.182155179008791
Fold 3 IBS: 0.1980335458693618
Fold 4 IBS: 0.22381482611109044
Fold 5 IBS: 0.16796576791520446
[I 2024-04-22 02:39:41,895] Trial 63 finished with value: 0.19898063321448226 and parameters: {'l1_ratio': 0.08004418040882527}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22277809064840007
Fold 2 IBS: 0.1821363490559237
Fold 3 IBS: 0.1981869461754426
Fold 4 IBS: 0.2238239243957918
Fold 5 IBS: 0.16811820658268742
[I 2024-04-22 02:39:42,326] Trial 64 finished with value: 0.1990087033716491 and parameters: {'l1_ratio': 0.29046066557445915}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22284280792050706
Fold 2 IBS: 0.18214996344990217
Fold 3 IBS: 0.1980517395183546
Fold 4 IBS: 0.22382181032175338
Fold 5 IBS: 0.16800779755338466
[I 2024-04-22 02:39:42,777] Trial 65 finished with value: 0.1989748237527804 and parameters: {'l1_ratio': 0.14855931770875044}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2228930870505403
Fold 2 IBS: 0.18215426757944275
Fold 3 IBS: 0.19809411059161605
Fold 4 IBS: 0.22375349945128983
Fold 5 IBS: 0.16798408218696553
[I 2024-04-22 02:39:43,265] Trial 66 finished with value: 0.1989758093719709 and parameters: {'l1_ratio': 0.11330590788739094}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2225461919581715
Fold 2 IBS: 0.18209639619754947
Fold 3 IBS: 0.1982799069234142
Fold 4 IBS: 0.22379981154786244
Fold 5 IBS: 0.16837941005700338
[I 2024-04-22 02:39:43,668] Trial 67 finished with value: 0.19902034333680022 and parameters: {'l1_ratio': 0.7392393754397737}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.24547534796879825
Fold 2 IBS: 0.22838013319481523
Fold 3 IBS: 0.22887645041426624
Fold 4 IBS: 0.2388695737508168
Fold 5 IBS: 0.22691359431003372
[I 2024-04-22 02:39:43,847] Trial 68 finished with value: 0.23370301992774606 and parameters: {'l1_ratio': 0.03013162937450721}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.222835970267234
Fold 2 IBS: 0.18214652085710364
Fold 3 IBS: 0.198145616780051
Fold 4 IBS: 0.22379208735474032
Fold 5 IBS: 0.168046458339551
[I 2024-04-22 02:39:44,289] Trial 69 finished with value: 0.198993330719736 and parameters: {'l1_ratio': 0.1994251299009083}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22277229815036956
Fold 2 IBS: 0.18213936851467905
Fold 3 IBS: 0.19810455024807136
Fold 4 IBS: 0.22374692408805266
Fold 5 IBS: 0.16809602447586378
[I 2024-04-22 02:39:44,698] Trial 70 finished with value: 0.19897183309540728 and parameters: {'l1_ratio': 0.26720835214083183}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22279716858154353
Fold 2 IBS: 0.18214278938263304
Fold 3 IBS: 0.19807647661446906
Fold 4 IBS: 0.2237228772525878
Fold 5 IBS: 0.16807665822172352
[I 2024-04-22 02:39:45,154] Trial 71 finished with value: 0.19896319401059137 and parameters: {'l1_ratio': 0.23261271415076903}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22288383221913577
Fold 2 IBS: 0.1821490746918453
Fold 3 IBS: 0.19808194165934276
Fold 4 IBS: 0.22373597460557682
Fold 5 IBS: 0.16801476016995937
[I 2024-04-22 02:39:45,578] Trial 72 finished with value: 0.198973116669172 and parameters: {'l1_ratio': 0.15242203779001623}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22292256620628573
Fold 2 IBS: 0.18215862840567823
Fold 3 IBS: 0.22887712560640544
Fold 4 IBS: 0.23704765783635484
Fold 5 IBS: 0.16806165806569046
[I 2024-04-22 02:39:45,948] Trial 73 finished with value: 0.20781352722408294 and parameters: {'l1_ratio': 0.05098413475215021}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22291272377948948
Fold 2 IBS: 0.18215674045365945
Fold 3 IBS: 0.19807595944666515
Fold 4 IBS: 0.2237391786547653
Fold 5 IBS: 0.16800751466712854
[I 2024-04-22 02:39:46,394] Trial 74 finished with value: 0.1989784234003416 and parameters: {'l1_ratio': 0.0827761592143243}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22277904780631913

Fold 2 IBS: 0.18214532413755527
Fold 3 IBS: 0.19812857941594306
Fold 4 IBS: 0.22377329930093534
Fold 5 IBS: 0.16806019902960562
[I 2024-04-22 02:39:46,793] Trial 75 finished with value: 0.19897728993807168 and parameters: {'l1_ratio': 0.21877076880955348}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22282224329850292
Fold 2 IBS: 0.18214780331796535
Fold 3 IBS: 0.19808138724048155
Fold 4 IBS: 0.2237331498149861
Fold 5 IBS: 0.16802815272447058
[I 2024-04-22 02:39:47,203] Trial 76 finished with value: 0.19896254727928128 and parameters: {'l1_ratio': 0.16913687383798529}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22281896378671234
Fold 2 IBS: 0.18214760066133354
Fold 3 IBS: 0.1980879571489982
Fold 4 IBS: 0.22373942725583468
Fold 5 IBS: 0.16802969603156295
[I 2024-04-22 02:39:47,629] Trial 77 finished with value: 0.19896472897688836 and parameters: {'l1_ratio': 0.17011313497289468}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.24721217357844263
Fold 2 IBS: 0.23196741185200853
Fold 3 IBS: 0.22897760956645086
Fold 4 IBS: 0.2419136968561053
Fold 5 IBS: 0.22934676691721614
[I 2024-04-22 02:39:47,821] Trial 78 finished with value: 0.2358835317540447 and parameters: {'l1_ratio': 0.0005386017723346126}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22281803484910154
Fold 2 IBS: 0.18214754336463143
Fold 3 IBS: 0.1980898161477487
Fold 4 IBS: 0.2237412031218162
Fold 5 IBS: 0.16803013354358753
[I 2024-04-22 02:39:48,325] Trial 79 finished with value: 0.1989653462053771 and parameters: {'l1_ratio': 0.17039140567536315}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22287928645064012
Fold 2 IBS: 0.18215284322715153
Fold 3 IBS: 0.19811227805406412
Fold 4 IBS: 0.2237689431007465
Fold 5 IBS: 0.16799835684741504
[I 2024-04-22 02:39:48,960] Trial 80 finished with value: 0.19898234153600344 and parameters: {'l1_ratio': 0.12734994317872292}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22286928777713708
Fold 2 IBS: 0.18215077800769977
Fold 3 IBS: 0.19810940338260538
Fold 4 IBS: 0.22376215903564792
Fold 5 IBS: 0.16800623741810986
[I 2024-04-22 02:39:49,416] Trial 81 finished with value: 0.19897957312424 and parameters: {'l1_ratio': 0.1561109206241973}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22286653835818301
Fold 2 IBS: 0.182147144435057
Fold 3 IBS: 0.19810277763138817
Fold 4 IBS: 0.22375358055006223
Fold 5 IBS: 0.1680193419151898
[I 2024-04-22 02:39:49,928] Trial 82 finished with value: 0.19897787657797603 and parameters: {'l1_ratio': 0.1723569673605199}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2228641363835105
Fold 2 IBS: 0.182153176069741
Fold 3 IBS: 0.19803792929798242
Fold 4 IBS: 0.2238159048151519
Fold 5 IBS: 0.1679895444741586
[I 2024-04-22 02:39:50,327] Trial 83 finished with value: 0.19897213820810886 and parameters: {'l1_ratio': 0.10820936455817852}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22280427773534875
Fold 2 IBS: 0.18214560078245026
Fold 3 IBS: 0.1981034734181358
Fold 4 IBS: 0.22375182705372818
Fold 5 IBS: 0.1680357846824455
[I 2024-04-22 02:39:50,701] Trial 84 finished with value: 0.1989681927344217 and parameters: {'l1_ratio': 0.19180970902310174}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2228988548103979
Fold 2 IBS: 0.1821559883527864
Fold 3 IBS: 0.1981035750830367
Fold 4 IBS: 0.22376539226143136
Fold 5 IBS: 0.16796116086801463
[I 2024-04-22 02:39:51,109] Trial 85 finished with value: 0.19897699427513338 and parameters: {'l1_ratio': 0.08465565774407888}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2227636379647839
Fold 2 IBS: 0.18213873246836793
Fold 3 IBS: 0.1981207242599852
Fold 4 IBS: 0.2237624576238138
Fold 5 IBS: 0.16810030184730232
[I 2024-04-22 02:39:51,486] Trial 86 finished with value: 0.1989771708328506 and parameters: {'l1_ratio': 0.2714722677824921}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22295889293032664
Fold 2 IBS: 0.18215729252445392
Fold 3 IBS: 0.22887288664989497
Fold 4 IBS: 0.23647985119714904
Fold 5 IBS: 0.16811776964066494
[I 2024-04-22 02:39:51,879] Trial 87 finished with value: 0.20771733858849792 and parameters: {'l1_ratio': 0.058086345926328595}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22287980953522832
Fold 2 IBS: 0.18215287465893293
Fold 3 IBS: 0.1981112739053511
Fold 4 IBS: 0.2237679889164414
Fold 5 IBS: 0.16799812508205705
[I 2024-04-22 02:39:52,506] Trial 88 finished with value: 0.19898201441960217 and parameters: {'l1_ratio': 0.12724005364348812}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22283042556367333
Fold 2 IBS: 0.18214831152639396
Fold 3 IBS: 0.19806494851715703
Fold 4 IBS: 0.2237198206364204
Fold 5 IBS: 0.1680243109792499
[I 2024-04-22 02:39:52,886] Trial 89 finished with value: 0.1989575634445789 and parameters: {'l1_ratio': 0.16674212468642005}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22289967602988975
Fold 2 IBS: 0.18215562455643686
Fold 3 IBS: 0.1980957014284926
Fold 4 IBS: 0.223758256992686
Fold 5 IBS: 0.16796695810977183
[I 2024-04-22 02:39:53,297] Trial 90 finished with value: 0.1989752434234554 and parameters: {'l1_ratio': 0.09286981361007436}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22285723641717364
Fold 2 IBS: 0.1821500036557657
Fold 3 IBS: 0.19813201054428667
Fold 4 IBS: 0.22378368390549944
Fold 5 IBS: 0.16801181039453725
[I 2024-04-22 02:39:53,667] Trial 91 finished with value: 0.19898694898345254 and parameters: {'l1_ratio': 0.15928248392213346}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2228140663434083
Fold 2 IBS: 0.18214502536043456
Fold 3 IBS: 0.19806918673846977
Fold 4 IBS: 0.22371869398746833
Fold 5 IBS: 0.1680566644238284
[I 2024-04-22 02:39:54,038] Trial 92 finished with value: 0.19896072737072187 and parameters: {'l1_ratio': 0.20712562509593152}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2228287156690277
Fold 2 IBS: 0.18214602271283592
Fold 3 IBS: 0.1981587416189549
Fold 4 IBS: 0.22380460914584654
Fold 5 IBS: 0.16804982900915116
[I 2024-04-22 02:39:54,401] Trial 93 finished with value: 0.1989975836311632 and parameters: {'l1_ratio': 0.2019211924071127}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22288465966770568
Fold 2 IBS: 0.18215012639710665
Fold 3 IBS: 0.19808447011178085
Fold 4 IBS: 0.22374052189017568
Fold 5 IBS: 0.1680030895251049
[I 2024-04-22 02:39:54,839] Trial 94 finished with value: 0.19897257351837477 and parameters: {'l1_ratio': 0.13776049259185186}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2227976443917204
Fold 2 IBS: 0.1821412493735767
Fold 3 IBS: 0.1981730943211523
Fold 4 IBS: 0.22381329837556
Fold 5 IBS: 0.16809200617205286
[I 2024-04-22 02:39:55,305] Trial 95 finished with value: 0.19900345852681245 and parameters: {'l1_ratio': 0.2553637683973989}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22274815008767737
Fold 2 IBS: 0.18213406971877963
Fold 3 IBS: 0.19812728168297533
Fold 4 IBS: 0.22376583305625453
Fold 5 IBS: 0.16812665076681232
[I 2024-04-22 02:39:55,760] Trial 96 finished with value: 0.19898039706249984 and parameters: {'l1_ratio': 0.30681880522760563}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22282074860080284
Fold 2 IBS: 0.18214666080082548
Fold 3 IBS: 0.19807093180354593
Fold 4 IBS: 0.22372303127336396
Fold 5 IBS: 0.1680406097027165
[I 2024-04-22 02:39:56,205] Trial 97 finished with value: 0.19896039643625096 and parameters: {'l1_ratio': 0.18631365009189393}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.2228051967483733
Fold 2 IBS: 0.18214335936032347
Fold 3 IBS: 0.19817728957299885
Fold 4 IBS: 0.22381986494507286
Fold 5 IBS: 0.1680729016000671
[I 2024-04-22 02:39:56,592] Trial 98 finished with value: 0.19900372244536713 and parameters: {'l1_ratio': 0.2293418176170819}. Best is trial 17 with value: 0.19895263780599762.
Fold 1 IBS: 0.22281527679689472
Fold 2 IBS: 0.18214630713864036
Fold 3 IBS: 0.19808177034519514
Fold 4 IBS: 0.22373339304128761
Fold 5 IBS: 0.16804317725474585
[I 2024-04-22 02:39:56,978] Trial 99 finished with value: 0.19896398491535272 and parameters: {'l1_ratio': 0.18810913322008121}. Best is trial 17 with value: 0.19895263780599762.


* Best trial for IBS:
 FrozenTrial(number=17, state=TrialState.COMPLETE, values=[0.19895263780599762], datetime_start=datetime.datetime(2024, 4, 22, 2, 39, 22, 723479), datetime_complete=datetime.datetime(2024, 4, 22, 2, 39, 23, 119820), params={'l1_ratio': 0.13474554059223504}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=17, value=None)


* Best Score for IBS:
 0.19895263780599762

In [49]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [50]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.726
train_ibs:  0.199

#### Test

In [51]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [52]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.21060026289682426)

test_cindex : 0.559

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.13474554059223504)

test_ibs:  0.29

In [53]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [54]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-22 02:39:57,315] A new study created in memory with name: no-name-4e9ef5c9-1cb2-4772-b20c-d2648f420393

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 02:40:01,577] Trial 0 finished with value: 0.6991621322401306 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6991621322401306.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7510729613733905
[I 2024-04-22 02:40:04,339] Trial 1 finished with value: 0.7355301592065651 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7339055793991416
[I 2024-04-22 02:40:06,380] Trial 2 finished with value: 0.7272289231066792 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:40:07,108] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:40:08,052] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7510729613733905
[I 2024-04-22 02:40:11,346] Trial 5 finished with value: 0.7346380398835799 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7339055793991416
[I 2024-04-22 02:40:15,675] Trial 6 finished with value: 0.7176325154358497 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:40:18,494] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6695278969957081
[I 2024-04-22 02:40:24,475] Trial 8 finished with value: 0.5339055793991416 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7510729613733905
[I 2024-04-22 02:40:27,327] Trial 9 finished with value: 0.7297749791965019 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:40:27,732] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7167381974248928
[I 2024-04-22 02:40:29,081] Trial 11 finished with value: 0.7275011596037759 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11629432582260082, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.7339055793991416
[I 2024-04-22 02:40:32,671] Trial 12 finished with value: 0.7312271571122319 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.48792003918647286, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10661539149160613, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7124463519313304
[I 2024-04-22 02:40:37,450] Trial 13 finished with value: 0.7285078854302759 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 490, 'oob_score': False, 'max_samples': 0.765021860726683, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.017530569165213797, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.776824034334764
[I 2024-04-22 02:40:38,182] Trial 14 finished with value: 0.7726196368380054 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.48589405900235655, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17488909350671974, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7446808510638298

Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.759656652360515
[I 2024-04-22 02:40:38,833] Trial 15 finished with value: 0.7430557612306835 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 114, 'oob_score': True, 'max_samples': 0.3692598016141903, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17993556917544976, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:40:38,993] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 6, 'oob_score': True, 'max_samples': 0.36871324569404207, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1937382585942945, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:40:39,726] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3, 'n_estimators': 123, 'oob_score': True, 'max_samples': 0.21593809517049486, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3637168382811743, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7939914163090128
[I 2024-04-22 02:40:40,420] Trial 18 finished with value: 0.7670383225171615 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 113, 'oob_score': True, 'max_samples': 0.44482585532317004, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17047935743788273, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:40:40,882] Trial 19 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 68, 'oob_score': True, 'max_samples': 0.4891559132906001, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.42883326307517006, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:40:42,475] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 184, 'oob_score': True, 'max_samples': 0.4189734961049175, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2519967097606023, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:40:43,209] Trial 21 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.31767468948360755, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16572240592344814, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7725321888412017
[I 2024-04-22 02:40:43,810] Trial 22 finished with value: 0.7691752300964144 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.5356189047828304, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2038631927701136, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8326180257510729
[I 2024-04-22 02:40:44,376] Trial 23 finished with value: 0.8046827761584172 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 68, 'oob_score': True, 'max_samples': 0.5413453585840211, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07940861604666782, 'warm_start': True}. Best is trial 23 with value: 0.8046827761584172.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8068669527896996
[I 2024-04-22 02:40:44,585] Trial 24 finished with value: 0.7968628519610398 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 12, 'oob_score': True, 'max_samples': 0.5434778837030446, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08417649111696884, 'warm_start': True}. Best is trial 23 with value: 0.8046827761584172.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.812015503875969
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.7253218884120172
[I 2024-04-22 02:40:44,773] Trial 25 finished with value: 0.781126535297143 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 7, 'oob_score': True, 'max_samples': 0.6669213410828165, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07045653823703169, 'warm_start': True}. Best is trial 23 with value: 0.8046827761584172.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8412017167381974
[I 2024-04-22 02:40:45,016] Trial 26 finished with value: 0.8041494497509662 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.6794016704774145, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08974480297156207, 'warm_start': True}. Best is trial 23 with value: 0.8046827761584172.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8412017167381974
[I 2024-04-22 02:40:45,412] Trial 27 finished with value: 0.8126094014577081 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 38, 'oob_score': True, 'max_samples': 0.8630402705028295, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07610225238763382, 'warm_start': True}. Best is trial 27 with value: 0.8126094014577081.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8454935622317596
[I 2024-04-22 02:40:45,913] Trial 28 finished with value: 0.8020961148667425 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 42, 'oob_score': True, 'max_samples': 0.9854572776620717, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1322471380695946, 'warm_start': True}. Best is trial 27 with value: 0.8126094014577081.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8927038626609443
[I 2024-04-22 02:40:47,041] Trial 29 finished with value: 0.839683794009181 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 163, 'oob_score': True, 'max_samples': 0.8309193149442771, 'max_features': None, 'min_weight_fraction_leaf': 0.061461466531914734, 'warm_start': True}. Best is trial 29 with value: 0.839683794009181.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.9012875536480687
[I 2024-04-22 02:40:48,080] Trial 30 finished with value: 0.8471808956568762 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 162, 'oob_score': True, 'max_samples': 0.8384725652873207, 'max_features': None, 'min_weight_fraction_leaf': 0.03824151200409104, 'warm_start': True}. Best is trial 30 with value: 0.8471808956568762.

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8969957081545065
[I 2024-04-22 02:40:49,243] Trial 31 finished with value: 0.8438452051001395 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 166, 'oob_score': True, 'max_samples': 0.8383718236388968, 'max_features': None, 'min_weight_fraction_leaf': 0.05349821135610229, 'warm_start': True}. Best is trial 30 with value: 0.8471808956568762.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8969957081545065
[I 2024-04-22 02:40:50,452] Trial 32 finished with value: 0.8463115133784891 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.844850651135347, 'max_features': None, 'min_weight_fraction_leaf': 0.047131601168288385, 'warm_start': True}. Best is trial 30 with value: 0.8471808956568762.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.8969957081545065
[I 2024-04-22 02:40:51,974] Trial 33 finished with value: 0.8477634373205489 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 232, 'oob_score': True, 'max_samples': 0.8400958521101125, 'max_features': None, 'min_weight_fraction_leaf': 0.003787219752160495, 'warm_start': True}. Best is trial 33 with value: 0.8477634373205489.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8798283261802575
[I 2024-04-22 02:40:53,569] Trial 34 finished with value: 0.8348953318242721 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.7437347513388699, 'max_features': None, 'min_weight_fraction_leaf': 0.002606193898855683, 'warm_start': True}. Best is trial 33 with value: 0.8477634373205489.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9098712446351931
[I 2024-04-22 02:40:55,006] Trial 35 finished with value: 0.8513492046079651 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.8867083209187331, 'max_features': None, 'min_weight_fraction_leaf': 0.041799651789036885, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8927038626609443
[I 2024-04-22 02:40:56,438] Trial 36 finished with value: 0.8327544194780486 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 225, 'oob_score': True, 'max_samples': 0.9510497756961918, 'max_features': None, 'min_weight_fraction_leaf': 0.03820571175421267, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9184549356223176
[I 2024-04-22 02:40:58,309] Trial 37 finished with value: 0.8513421961952613 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 256, 'oob_score': True, 'max_samples': 0.8905785303043968, 'max_features': None, 'min_weight_fraction_leaf': 0.0015959813648095014, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8669527896995708
[I 2024-04-22 02:40:59,755] Trial 38 finished with value: 0.8036433012288817 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 264, 'oob_score': True, 'max_samples': 0.8788883038694885, 'max_features': None, 'min_weight_fraction_leaf': 0.002532290324689703, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:41:01,461] Trial 39 finished with value: 0.7672578212055718 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 332, 'oob_score': True, 'max_samples': 0.9144710105629309, 'max_features': None, 'min_weight_fraction_leaf': 0.12930362433818024, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8884120171673819
[I 2024-04-22 02:41:03,296] Trial 40 finished with value: 0.8277166012617376 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.9980478663893719, 'max_features': None, 'min_weight_fraction_leaf': 0.029813810847214628, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9098712446351931
[I 2024-04-22 02:41:04,450] Trial 41 finished with value: 0.8520485283750772 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 207, 'oob_score': True, 'max_samples': 0.8024276641096046, 'max_features': None, 'min_weight_fraction_leaf': 0.041434068575410196, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9012875536480687
[I 2024-04-22 02:41:05,684] Trial 42 finished with value: 0.8479087198004114 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.7648836348187944, 'max_features': None, 'min_weight_fraction_leaf': 0.033423986218882616, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9012875536480687
[I 2024-04-22 02:41:06,809] Trial 43 finished with value: 0.8496540853610947 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 205, 'oob_score': True, 'max_samples': 0.7796080313426239, 'max_features': None, 'min_weight_fraction_leaf': 0.014857830524255941, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8454935622317596
[I 2024-04-22 02:41:07,953] Trial 44 finished with value: 0.8078917831058507 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.7797897259787169, 'max_features': None, 'min_weight_fraction_leaf': 0.10143753014282131, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8240343347639485
[I 2024-04-22 02:41:08,781] Trial 45 finished with value: 0.7904418608687293 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.7138201818624347, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14694492074117838, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:41:13,161] Trial 46 finished with value: 0.7254981239299447 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 284, 'oob_score': True, 'max_samples': 0.8992746801558931, 'max_features': None, 'min_weight_fraction_leaf': 0.028181408583194678, 'warm_start': False}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.9012875536480687
[I 2024-04-22 02:41:14,061] Trial 47 finished with value: 0.8365327725015698 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 200, 'oob_score': False, 'max_samples': 0.7205133550183166, 'max_features': None, 'min_weight_fraction_leaf': 0.05574216570821283, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6952789699570815
[I 2024-04-22 02:41:20,343] Trial 48 finished with value: 0.7086009095296246 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.8036505209305815, 'max_features': None, 'min_weight_fraction_leaf': 0.22178657477496955, 'warm_start': False}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8369098712446352
[I 2024-04-22 02:41:22,396] Trial 49 finished with value: 0.7960271358026422 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 389, 'oob_score': True, 'max_samples': 0.610884224629099, 'max_features': None, 'min_weight_fraction_leaf': 0.10220826251839069, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7939914163090128
[I 2024-04-22 02:41:23,220] Trial 50 finished with value: 0.7854372155985099 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.9361939014586368, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.28018530821993104, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7939914163090128
[I 2024-04-22 02:41:24,980] Trial 51 finished with value: 0.7756710134041036 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.7993151610130277, 'max_features': None, 'min_weight_fraction_leaf': 0.0005063458363507817, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9141630901287554
[I 2024-04-22 02:41:26,900] Trial 52 finished with value: 0.8535946407970745 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 220, 'oob_score': True, 'max_samples': 0.8921259102671709, 'max_features': None, 'min_weight_fraction_leaf': 0.018293305903393637, 'warm_start': True}. Best is trial 52 with value: 0.8535946407970745.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.9069767441860465
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.927038626609442
[I 2024-04-22 02:41:28,499] Trial 53 finished with value: 0.8585132240941041 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.9658618134365592, 'max_features': None, 'min_weight_fraction_leaf': 0.014650326015013641, 'warm_start': True}. Best is trial 53 with value: 0.8585132240941041.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.9147286821705426
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:41:29,925] Trial 54 finished with value: 0.8632581679559443 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 189, 'oob_score': True, 'max_samples': 0.9625534179904701, 'max_features': None, 'min_weight_fraction_leaf': 0.019842323563345525, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.9186046511627907
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:41:31,213] Trial 55 finished with value: 0.8631822979246067 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 183, 'oob_score': True, 'max_samples': 0.9637396879166721, 'max_features': None, 'min_weight_fraction_leaf': 0.02006130607634453, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.759656652360515
[I 2024-04-22 02:41:33,749] Trial 56 finished with value: 0.7258200494907298 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 141, 'oob_score': True, 'max_samples': 0.9627981016911359, 'max_features': None, 'min_weight_fraction_leaf': 0.05237976583817004, 'warm_start': False}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.9147286821705426
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.927038626609442
[I 2024-04-22 02:41:35,033] Trial 57 finished with value: 0.8624540499380153 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 187, 'oob_score': True, 'max_samples': 0.969742549381378, 'max_features': None, 'min_weight_fraction_leaf': 0.023371324683680833, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:41:36,076] Trial 58 finished with value: 0.8623951162735353 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 181, 'oob_score': True, 'max_samples': 0.9690133939480812, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021524357754764783, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:41:36,696] Trial 59 finished with value: 0.8623951162735353 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.9702801247369853, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01939288260546853, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7167381974248928
[I 2024-04-22 02:41:38,721] Trial 60 finished with value: 0.7174226465122555 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 186, 'oob_score': False, 'max_samples': 0.9713481779848987, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.354956875935207, 'warm_start': False}. Best is trial 54 with value: 0.8632581679559443.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9277566539923955
Fold 5 C-index: 0.9356223175965666
[I 2024-04-22 02:41:39,246] Trial 61 finished with value: 0.863249761027237 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.9315899812443563, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.023014102784859193, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9055793991416309
[I 2024-04-22 02:41:39,600] Trial 62 finished with value: 0.8405373371031004 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.9238731528894242, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06716848446483438, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7682403433476395
[I 2024-04-22 02:41:40,069] Trial 63 finished with value: 0.7482015307786698 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 156, 'oob_score': False, 'max_samples': 0.949454174371522, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42582787243459574, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8798283261802575
[I 2024-04-22 02:41:40,526] Trial 64 finished with value: 0.8273796413200459 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 142, 'oob_score': False, 'max_samples': 0.9917921798289998, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09031712086014251, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:41:41,115] Trial 65 finished with value: 0.8592294842280737 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.9240040548597519, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02047626469173783, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9012875536480687
[I 2024-04-22 02:41:41,698] Trial 66 finished with value: 0.8394945958114837 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.9229156191863954, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06380717535025415, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8412017167381974
[I 2024-04-22 02:41:42,256] Trial 67 finished with value: 0.7955811892681643 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.995009976038662, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02429896250829207, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.8884120171673819
[I 2024-04-22 02:41:42,646] Trial 68 finished with value: 0.8338770961561366 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.9428503920721849, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07188437817902898, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8583690987124464
[I 2024-04-22 02:41:43,134] Trial 69 finished with value: 0.8069246578719019 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 146, 'oob_score': False, 'max_samples': 0.8666896988471977, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.124823245098527, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8154506437768241
[I 2024-04-22 02:41:43,554] Trial 70 finished with value: 0.7945878301699866 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 130, 'oob_score': False, 'max_samples': 0.12462860681265314, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02126228748040546, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:41:44,180] Trial 71 finished with value: 0.859189970671976 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 192, 'oob_score': False, 'max_samples': 0.9740624334770935, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.016292071205830195, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.927038626609442
[I 2024-04-22 02:41:44,729] Trial 72 finished with value: 0.8567849383213751 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 175, 'oob_score': False, 'max_samples': 0.9162488213949347, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05261359898316401, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9356223175965666
[I 2024-04-22 02:41:45,374] Trial 73 finished with value: 0.8633946196640432 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 194, 'oob_score': False, 'max_samples': 0.9999354575629575, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.031604961665606564, 'warm_start': True}. Best is trial 73 with value: 0.8633946196640432.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9277566539923955
Fold 5 C-index: 0.9356223175965666
[I 2024-04-22 02:41:45,879] Trial 74 finished with value: 0.8649624944576914 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 148, 'oob_score': False, 'max_samples': 0.9395463682850804, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03591904730025234, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.8884120171673819
[I 2024-04-22 02:41:46,468] Trial 75 finished with value: 0.8291758140384612 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 151, 'oob_score': False, 'max_samples': 0.9558720298384755, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08775783727116993, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9574468085106383
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9356223175965666
[I 2024-04-22 02:41:46,915] Trial 76 finished with value: 0.8644300556867346 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 102, 'oob_score': False, 'max_samples': 0.993930256699719, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0398572345294084, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8927038626609443
[I 2024-04-22 02:41:47,338] Trial 77 finished with value: 0.8340113654563247 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.9913390641588559, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04234216642710123, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8884120171673819
[I 2024-04-22 02:41:47,824] Trial 78 finished with value: 0.8409578033411496 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 109, 'oob_score': False, 'max_samples': 0.8630045149985799, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0609070149180181, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8540772532188842
[I 2024-04-22 02:41:48,325] Trial 79 finished with value: 0.8035852429701545 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 127, 'oob_score': False, 'max_samples': 0.9045813350723169, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07865274171241976, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7081545064377682
[I 2024-04-22 02:41:49,420] Trial 80 finished with value: 0.7261480403266783 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 14, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.9452700606717033, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03478111510727396, 'warm_start': False}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.9227467811158798
[I 2024-04-22 02:41:50,045] Trial 81 finished with value: 0.8600881237347175 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 169, 'oob_score': False, 'max_samples': 0.9701774756059413, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.009387333105181828, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9356223175965666
[I 2024-04-22 02:41:50,702] Trial 82 finished with value: 0.8634130815337395 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 199, 'oob_score': False, 'max_samples': 0.9740317203146824, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.031105510537608762, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:41:51,327] Trial 83 finished with value: 0.855212788352825 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 195, 'oob_score': False, 'max_samples': 0.9452433661930899, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.046861909789421494, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9227467811158798
[I 2024-04-22 02:41:51,818] Trial 84 finished with value: 0.85060280804216 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 138, 'oob_score': False, 'max_samples': 0.991804397125127, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03327645272133899, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8626609442060086
[I 2024-04-22 02:41:52,310] Trial 85 finished with value: 0.8142802013847452 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.9999498552793648, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11550818315944608, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.935361216730038
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:41:52,711] Trial 86 finished with value: 0.8662268726917273 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 113, 'oob_score': False, 'max_samples': 0.8746458616251406, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030922977401692878, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8841201716738197
[I 2024-04-22 02:41:53,128] Trial 87 finished with value: 0.840718756224406 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 111, 'oob_score': False, 'max_samples': 0.8654172382794998, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06452241723435258, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.871244635193133
[I 2024-04-22 02:41:53,414] Trial 88 finished with value: 0.8168442790669467 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 61, 'oob_score': False, 'max_samples': 0.9315642015297859, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0949696957319068, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9184549356223176
[I 2024-04-22 02:41:53,903] Trial 89 finished with value: 0.8558359452323782 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 125, 'oob_score': False, 'max_samples': 0.9038308798666062, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.044442422879351094, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:41:54,113] Trial 90 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 29, 'oob_score': False, 'max_samples': 0.8757558739983621, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4966080828658863, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9399141630901288
[I 2024-04-22 02:41:54,864] Trial 91 finished with value: 0.8626884309053237 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 246, 'oob_score': False, 'max_samples': 0.9776306114812428, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.028839161868997508, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:41:55,579] Trial 92 finished with value: 0.8560280629715251 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 243, 'oob_score': False, 'max_samples': 0.9311993321115322, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030551566023909363, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9227467811158798
[I 2024-04-22 02:41:56,197] Trial 93 finished with value: 0.8541564276305669 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 200, 'oob_score': False, 'max_samples': 0.9091701552343036, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.009137289628038645, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9356223175965666
[I 2024-04-22 02:41:56,909] Trial 94 finished with value: 0.85451761277378 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 169, 'oob_score': False, 'max_samples': 0.9564057018609697, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05197512631502196, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8798283261802575
[I 2024-04-22 02:41:57,891] Trial 95 finished with value: 0.8337498517029143 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8876723605013093, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07696236087701544, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9055793991416309
[I 2024-04-22 02:41:58,539] Trial 96 finished with value: 0.843083647166593 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.9760183262225188, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00019495076365802846, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9399141630901288
[I 2024-04-22 02:41:59,309] Trial 97 finished with value: 0.8633118846410982 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 210, 'oob_score': False, 'max_samples': 0.8197716452211096, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03271483017646171, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7811158798283262
[I 2024-04-22 02:42:02,146] Trial 98 finished with value: 0.7399225237760426 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.8315355201803293, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03474288685672425, 'warm_start': False}. Best is trial 86 with value: 0.8662268726917273.

[I 2024-04-22 02:42:02,881] A new study created in memory with name: no-name-138c90ff-4caa-4b65-a0e8-67a5105e2805

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.9356223175965666
[I 2024-04-22 02:42:02,863] Trial 99 finished with value: 0.8552780690475444 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 219, 'oob_score': False, 'max_samples': 0.9381470917280882, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.058903635501878514, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.


* Best trial for C-index:
 FrozenTrial(number=86, state=TrialState.COMPLETE, values=[0.8662268726917273], datetime_start=datetime.datetime(2024, 4, 22, 2, 41, 52, 313766), datetime_complete=datetime.datetime(2024, 4, 22, 2, 41, 52, 711091), params={'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 113, 'oob_score': False, 'max_samples': 0.8746458616251406, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030922977401692878, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=86, value=None)


* Best Score for C-index:
 0.8662268726917273

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21762433179841878
Fold 2 IBS: 0.18195020133812084
Fold 3 IBS: 0.2361143230502189
Fold 4 IBS: 0.2073285062122392
Fold 5 IBS: 0.21392727346918483
[I 2024-04-22 02:42:06,830] Trial 0 finished with value: 0.21138892717363653 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21138892717363653.
Fold 1 IBS: 0.21581044184076711
Fold 2 IBS: 0.17697992286624134
Fold 3 IBS: 0.20953123826339945
Fold 4 IBS: 0.19758108917721037
Fold 5 IBS: 0.20179307042175074
[I 2024-04-22 02:42:07,903] Trial 1 finished with value: 0.2003391525138738 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.2003391525138738.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-22 02:42:08,511] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.2003391525138738.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-22 02:42:10,797] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.2003391525138738.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-22 02:42:12,538] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.2003391525138738.
Fold 1 IBS: 0.221854155851065
Fold 2 IBS: 0.17690263638724796
Fold 3 IBS: 0.1967547177467275
Fold 4 IBS: 0.18843430540942496
Fold 5 IBS: 0.18075314399111414
[I 2024-04-22 02:42:15,153] Trial 5 finished with value: 0.1929397918771159 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.2131217857918839
Fold 2 IBS: 0.19307243279090222
Fold 3 IBS: 0.25137354374382015
Fold 4 IBS: 0.20218154161317498
Fold 5 IBS: 0.2126608840238083
[I 2024-04-22 02:42:17,981] Trial 6 finished with value: 0.2144820375927179 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.2388433246721578
Fold 2 IBS: 0.22464552665811907
Fold 3 IBS: 0.22584090572561383
Fold 4 IBS: 0.231868515757187
Fold 5 IBS: 0.22190410121033288
[I 2024-04-22 02:42:21,560] Trial 7 finished with value: 0.22862047480468214 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-22 02:42:26,076] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.21807767436739164
Fold 2 IBS: 0.18501717466232873
Fold 3 IBS: 0.19984578577268608
Fold 4 IBS: 0.2107172403878465
Fold 5 IBS: 0.20405390685508257
[I 2024-04-22 02:42:27,224] Trial 9 finished with value: 0.20354235640906712 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.24645571521465787
Fold 2 IBS: 0.23214351218858914
Fold 3 IBS: 0.23029990468218745
Fold 4 IBS: 0.24091247880712954
Fold 5 IBS: 0.22969387017589088
[I 2024-04-22 02:42:32,499] Trial 10 finished with value: 0.235901096213691 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.22667865765971248
Fold 2 IBS: 0.18386911210968868
Fold 3 IBS: 0.19650770014771463
Fold 4 IBS: 0.20835591158437963
Fold 5 IBS: 0.203472559428523
[I 2024-04-22 02:42:34,184] Trial 11 finished with value: 0.20377678818600367 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12378097340613392}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.23112230630238642
Fold 2 IBS: 0.1674454512633998
Fold 3 IBS: 0.19855471836895786
Fold 4 IBS: 0.1938632953802893
Fold 5 IBS: 0.18962922951564953
[I 2024-04-22 02:42:34,556] Trial 12 finished with value: 0.1961230001661366 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.7642078791940475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13207155531457032}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.2413073544619049
Fold 2 IBS: 0.1811958871683442
Fold 3 IBS: 0.22244250686987974
Fold 4 IBS: 0.19750724899733643
Fold 5 IBS: 0.18232843513858982
[I 2024-04-22 02:42:34,926] Trial 13 finished with value: 0.20495628652721104 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 14, 'oob_score': False, 'max_samples': 0.8293737737164385, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09633845721802128}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.2242647329441179
Fold 2 IBS: 0.17883999941146664
Fold 3 IBS: 0.1918443810565798
Fold 4 IBS: 0.19214931253213374
Fold 5 IBS: 0.1731968530886853
[I 2024-04-22 02:42:37,986] Trial 14 finished with value: 0.19205905580659666 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.6604916334814492, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02382938621825248}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.2288883257443599
Fold 2 IBS: 0.1738046533368976
Fold 3 IBS: 0.1959496843821166
Fold 4 IBS: 0.19095725701045163
Fold 5 IBS: 0.18213576812388554
[I 2024-04-22 02:42:40,776] Trial 15 finished with value: 0.19434713771954226 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.9870260431565661, 'max_features': 'log2', 'min_weight_fraction_leaf': 2.174000731099135e-05}. Best is trial 14 with value: 0.19205905580659666.

Fold 1 IBS: 0.221052045952944
Fold 2 IBS: 0.17864590278571793
Fold 3 IBS: 0.20121068717993237
Fold 4 IBS: 0.19156051442456593
Fold 5 IBS: 0.18700261900559814
[I 2024-04-22 02:42:44,805] Trial 16 finished with value: 0.19589435386975168 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.6248405086569909, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.054994509022204895}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.24661458596136437
Fold 2 IBS: 0.23231122477788718
Fold 3 IBS: 0.229689256646579
Fold 4 IBS: 0.2413341340131506
Fold 5 IBS: 0.2302248378800009
[I 2024-04-22 02:42:46,959] Trial 17 finished with value: 0.23603480785579642 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 225, 'oob_score': False, 'max_samples': 0.39119490979325144, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27799606575272795}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.222887661575006
Fold 2 IBS: 0.18421435942452744
Fold 3 IBS: 0.19421453594382496
Fold 4 IBS: 0.19981786115023864
Fold 5 IBS: 0.1912096155424649
[I 2024-04-22 02:42:49,040] Trial 18 finished with value: 0.1984688067272124 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 156, 'oob_score': True, 'max_samples': 0.21062982570611943, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05734145926999751}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22047405758964184
Fold 2 IBS: 0.1966030079539471
Fold 3 IBS: 0.21350757148135177
Fold 4 IBS: 0.20455158700455836
Fold 5 IBS: 0.2019153339379839
[I 2024-04-22 02:42:51,835] Trial 19 finished with value: 0.20741031159349657 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.4386108822397098, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17720383372155285}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.2203832582181566
Fold 2 IBS: 0.19931517540854854
Fold 3 IBS: 0.21442829878986364
Fold 4 IBS: 0.2069356513930878
Fold 5 IBS: 0.20374628014066523
[I 2024-04-22 02:42:55,298] Trial 20 finished with value: 0.20896173279006436 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.6164262808144682, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24472699218520227}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.2275442075846795
Fold 2 IBS: 0.17484137550996653
Fold 3 IBS: 0.19334185644794946
Fold 4 IBS: 0.19132538175744745
Fold 5 IBS: 0.18115113844013128
[I 2024-04-22 02:42:58,012] Trial 21 finished with value: 0.19364079194803485 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.9621081290297763, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01052588707306133}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.23054333285986953
Fold 2 IBS: 0.1724746302154596
Fold 3 IBS: 0.20261710681612344
Fold 4 IBS: 0.1926073795425933
Fold 5 IBS: 0.18185095277627958
[I 2024-04-22 02:43:00,192] Trial 22 finished with value: 0.1960186804420651 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.9874289067540774, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012068014135528271}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22601236961439128
Fold 2 IBS: 0.17969996069427818
Fold 3 IBS: 0.19876167471795514
Fold 4 IBS: 0.196787842235057
Fold 5 IBS: 0.18785036721027695
[I 2024-04-22 02:43:02,632] Trial 23 finished with value: 0.19782244289439171 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 308, 'oob_score': False, 'max_samples': 0.8598545784448618, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08754103994167567}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22736870474237106
Fold 2 IBS: 0.17759080498432794
Fold 3 IBS: 0.1907220147867818
Fold 4 IBS: 0.19684291499550113
Fold 5 IBS: 0.173335537233157
[I 2024-04-22 02:43:04,141] Trial 24 finished with value: 0.19317199534842777 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 171, 'oob_score': False, 'max_samples': 0.7977844441295365, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03359112238003443}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22154369312237301
Fold 2 IBS: 0.17529814117915438
Fold 3 IBS: 0.19940916065427428
Fold 4 IBS: 0.19644777061534635
Fold 5 IBS: 0.18432305180010988
[I 2024-04-22 02:43:05,862] Trial 25 finished with value: 0.19540436347425158 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 172, 'oob_score': False, 'max_samples': 0.7991522227764232, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11631986143324591}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.21676007374411307
Fold 2 IBS: 0.17824797677237728
Fold 3 IBS: 0.20701000107269518
Fold 4 IBS: 0.19291445170373886
Fold 5 IBS: 0.19374462748985236
[I 2024-04-22 02:43:08,457] Trial 26 finished with value: 0.19773542615655534 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 182, 'oob_score': True, 'max_samples': 0.6679645097491387, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.038185359995283503}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.21502992986795352
Fold 2 IBS: 0.1870308796226911
Fold 3 IBS: 0.2076665120334582
Fold 4 IBS: 0.19610467365474676
Fold 5 IBS: 0.2006394525445189
[I 2024-04-22 02:43:12,203] Trial 27 finished with value: 0.2012942895446737 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 402, 'oob_score': False, 'max_samples': 0.4929150044278433, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15117671554446085}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22061913161771582
Fold 2 IBS: 0.1760211535374804
Fold 3 IBS: 0.1985451645372839
Fold 4 IBS: 0.1895387815583719
Fold 5 IBS: 0.18196669319802622
[I 2024-04-22 02:43:14,323] Trial 28 finished with value: 0.19333818488977564 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 238, 'oob_score': False, 'max_samples': 0.7046067597565696, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08480904388715302}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.21738957168254863
Fold 2 IBS: 0.18629216965440445
Fold 3 IBS: 0.23966304898222662
Fold 4 IBS: 0.21639319543648572
Fold 5 IBS: 0.21400347731487693
[I 2024-04-22 02:43:15,412] Trial 29 finished with value: 0.2147482926141085 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 114, 'oob_score': False, 'max_samples': 0.6118767285087061, 'max_features': None, 'min_weight_fraction_leaf': 0.21149318025001101}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22758569118959
Fold 2 IBS: 0.1745807047630518
Fold 3 IBS: 0.19331240272244285
Fold 4 IBS: 0.19188841853726443
Fold 5 IBS: 0.17272789020296123
[I 2024-04-22 02:43:19,971] Trial 30 finished with value: 0.19201902148306207 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.770559095997367, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.027011468511437653}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.22584092896742133
Fold 2 IBS: 0.17585075081924822
Fold 3 IBS: 0.1972070156814071
Fold 4 IBS: 0.18881994130282825

Fold 5 IBS: 0.17585992091527558
[I 2024-04-22 02:43:23,359] Trial 31 finished with value: 0.19271571153723607 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.7600957156160437, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.045073432551245296}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.22236771464371266
Fold 2 IBS: 0.17701546684229433
Fold 3 IBS: 0.19851905347240079
Fold 4 IBS: 0.18732302760178435
Fold 5 IBS: 0.18167933628393707
[I 2024-04-22 02:43:26,569] Trial 32 finished with value: 0.19338091976882582 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 394, 'oob_score': False, 'max_samples': 0.6752379846937863, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07718385932974292}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.2270170034083123
Fold 2 IBS: 0.1795970779202372
Fold 3 IBS: 0.19695809379393509
Fold 4 IBS: 0.1963645526898038
Fold 5 IBS: 0.18960590139682051
[I 2024-04-22 02:43:29,383] Trial 33 finished with value: 0.19790852584182178 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 319, 'oob_score': False, 'max_samples': 0.7392038686189389, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.050681546729188336}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.22913107555986495
Fold 2 IBS: 0.1713200021524253
Fold 3 IBS: 0.20174276009751624
Fold 4 IBS: 0.19170526770572746
Fold 5 IBS: 0.18122337614028983
[I 2024-04-22 02:43:32,694] Trial 34 finished with value: 0.19502449633116475 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.8878735229014442, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10769272272367647}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.2263994177575451
Fold 2 IBS: 0.1782493853587001
Fold 3 IBS: 0.19967435367391417
Fold 4 IBS: 0.18957084972922195
Fold 5 IBS: 0.1806713908816942
[I 2024-04-22 02:43:38,077] Trial 35 finished with value: 0.1949130794802151 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 474, 'oob_score': True, 'max_samples': 0.5635984815237928, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.031068687969102886}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.2140834251920096
Fold 2 IBS: 0.18302541234920544
Fold 3 IBS: 0.20583049051646687
Fold 4 IBS: 0.19225672545423975
Fold 5 IBS: 0.1950395683265298
[I 2024-04-22 02:43:41,394] Trial 36 finished with value: 0.19804712436769029 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.6797083197848384, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16437366905173617}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.2232352512407339
Fold 2 IBS: 0.1768499163180223
Fold 3 IBS: 0.20266000918435328
Fold 4 IBS: 0.19138188589544256
Fold 5 IBS: 0.18665967315448365
[I 2024-04-22 02:43:45,174] Trial 37 finished with value: 0.19615734715860716 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.7779331709919757, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13312369867225185}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.24610665966261314
Fold 2 IBS: 0.23223155236224916
Fold 3 IBS: 0.22952300914119636
Fold 4 IBS: 0.2414811194823906
Fold 5 IBS: 0.23018872339055935
[I 2024-04-22 02:43:49,920] Trial 38 finished with value: 0.23590621280780172 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 422, 'oob_score': True, 'max_samples': 0.48580268101444124, 'max_features': None, 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.22481799036239483
Fold 2 IBS: 0.17685147774699653
Fold 3 IBS: 0.20049010291951425
Fold 4 IBS: 0.18982857043914958
Fold 5 IBS: 0.18254203063054433
[I 2024-04-22 02:43:53,931] Trial 39 finished with value: 0.1949060344197199 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.5843062137973745, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07067430477200148}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.2466142294056291
Fold 2 IBS: 0.23220067379443807
Fold 3 IBS: 0.22953256065286004
Fold 4 IBS: 0.24149352725075382
Fold 5 IBS: 0.23034005575836422
[I 2024-04-22 02:43:56,642] Trial 40 finished with value: 0.23603620937240904 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 327, 'oob_score': False, 'max_samples': 0.6533926233121279, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3997341974880029}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.22008661582176534
Fold 2 IBS: 0.17191458989661332
Fold 3 IBS: 0.19041182470823828
Fold 4 IBS: 0.1994085393279668
Fold 5 IBS: 0.17049962251252426
[I 2024-04-22 02:43:58,602] Trial 41 finished with value: 0.19046423845342159 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 196, 'oob_score': False, 'max_samples': 0.8079255109979475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03389223938021847}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.22280111750039264
Fold 2 IBS: 0.17796243072588608
Fold 3 IBS: 0.18962417076714974
Fold 4 IBS: 0.19463536301610113
Fold 5 IBS: 0.17836205501155145
[I 2024-04-22 02:44:00,397] Trial 42 finished with value: 0.19267702740421622 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 204, 'oob_score': False, 'max_samples': 0.7310718829833422, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.029447700275051822}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.24650381632587262
Fold 2 IBS: 0.23211797085492242
Fold 3 IBS: 0.22955740353559057
Fold 4 IBS: 0.24157053900567507
Fold 5 IBS: 0.23027910552347802
[I 2024-04-22 02:44:01,969] Trial 43 finished with value: 0.23600576704910775 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 202, 'oob_score': False, 'max_samples': 0.9068225316738959, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.2272741837619837
Fold 2 IBS: 0.18010040335739258
Fold 3 IBS: 0.18917888351764922
Fold 4 IBS: 0.19497471406918135
Fold 5 IBS: 0.17759835230906024
[I 2024-04-22 02:44:04,430] Trial 44 finished with value: 0.19382530740305343 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.8278518214882832, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.032724850462757596}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.21818859674129706
Fold 2 IBS: 0.19182889723265809
Fold 3 IBS: 0.20645079219948698
Fold 4 IBS: 0.2039075995565362
Fold 5 IBS: 0.20251751001463825
[I 2024-04-22 02:44:05,994] Trial 45 finished with value: 0.2045786791489233 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 2, 'n_estimators': 194, 'oob_score': False, 'max_samples': 0.7211266599729008, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0184904067184055}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.24605956999356746
Fold 2 IBS: 0.1715522843932026
Fold 3 IBS: 0.22997512987796287
Fold 4 IBS: 0.2114434138594334
Fold 5 IBS: 0.20680985045195013
[I 2024-04-22 02:44:09,252] Trial 46 finished with value: 0.2131680497152233 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 376, 'oob_score': False, 'max_samples': 0.8319888092703853, 'max_features': None, 'min_weight_fraction_leaf': 0.0015300457559763413}. Best is trial 41 with value: 0.19046423845342159.

Fold 1 IBS: 0.22670665484519142
Fold 2 IBS: 0.175184981867077
Fold 3 IBS: 0.20276219990812896
Fold 4 IBS: 0.19658107727261281
Fold 5 IBS: 0.17640448174832232
[I 2024-04-22 02:44:11,426] Trial 47 finished with value: 0.1955278791282665 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.7533756239183884, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05433383705425634}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.21833683794653208
Fold 2 IBS: 0.16845072186321247
Fold 3 IBS: 0.20168040343516955
Fold 4 IBS: 0.1937674426294509
Fold 5 IBS: 0.19051837676249267
[I 2024-04-22 02:44:12,242] Trial 48 finished with value: 0.19455075652737155 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 82, 'oob_score': False, 'max_samples': 0.7075209195984526, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10074510594123325}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.22242522647319046
Fold 2 IBS: 0.17089945636142403
Fold 3 IBS: 0.195613872409514
Fold 4 IBS: 0.18922142541007175
Fold 5 IBS: 0.17303791504234847
[I 2024-04-22 02:44:14,341] Trial 49 finished with value: 0.19023957913930975 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 215, 'oob_score': False, 'max_samples': 0.7890788621794695, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04458702793409107}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22555617401744368
Fold 2 IBS: 0.17741085594825706
Fold 3 IBS: 0.20242485916185912
Fold 4 IBS: 0.19387487722329108
Fold 5 IBS: 0.18754644311102073
[I 2024-04-22 02:44:16,224] Trial 50 finished with value: 0.19736264189237435 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 220, 'oob_score': False, 'max_samples': 0.8555734953303252, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14147922592542847}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.21627803680039687
Fold 2 IBS: 0.18166264021393835
Fold 3 IBS: 0.2092710829548924
Fold 4 IBS: 0.19595939612381622
Fold 5 IBS: 0.2011472544518922
[I 2024-04-22 02:44:18,718] Trial 51 finished with value: 0.20086368210898717 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.792480439746047, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04337189753109918}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22826690607978067
Fold 2 IBS: 0.17514993464852044
Fold 3 IBS: 0.19499180688840081
Fold 4 IBS: 0.19607308855822925
Fold 5 IBS: 0.1785126372364033
[I 2024-04-22 02:44:21,063] Trial 52 finished with value: 0.1945988746822669 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 216, 'oob_score': False, 'max_samples': 0.7551979832732026, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0695275941074916}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2272968554576038
Fold 2 IBS: 0.1698341110510439
Fold 3 IBS: 0.19814117513373936
Fold 4 IBS: 0.20422983853085452
Fold 5 IBS: 0.16857687543461305
[I 2024-04-22 02:44:22,837] Trial 53 finished with value: 0.19361577112157094 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 145, 'oob_score': False, 'max_samples': 0.9323805201970561, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024719341884636734}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22481757046708095
Fold 2 IBS: 0.17677433524674352
Fold 3 IBS: 0.19744731736557988
Fold 4 IBS: 0.1900684049643577
Fold 5 IBS: 0.17563795002659072
[I 2024-04-22 02:44:25,541] Trial 54 finished with value: 0.19294911561407058 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 291, 'oob_score': False, 'max_samples': 0.7054751660094117, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05861070426347463}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22109268216759362
Fold 2 IBS: 0.1795317897821966
Fold 3 IBS: 0.19864062457744264
Fold 4 IBS: 0.1887540514309438
Fold 5 IBS: 0.18579795261641194
[I 2024-04-22 02:44:27,878] Trial 55 finished with value: 0.1947634201149177 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.6301567839071449, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08753416190089439}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.23313488896504717
Fold 2 IBS: 0.19865251149482616
Fold 3 IBS: 0.20707690430687525
Fold 4 IBS: 0.20382506127552455
Fold 5 IBS: 0.20806640771791665
[I 2024-04-22 02:44:31,411] Trial 56 finished with value: 0.21015115475203797 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 415, 'oob_score': False, 'max_samples': 0.8215366083160163, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.021781106435660526}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.251405085227788
Fold 2 IBS: 0.17971245840591804
Fold 3 IBS: 0.20892416859276688
Fold 4 IBS: 0.2096604234179674
Fold 5 IBS: 0.18424709009072612
[I 2024-04-22 02:44:34,527] Trial 57 finished with value: 0.20678984514703327 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 270, 'oob_score': False, 'max_samples': 0.8705287129013517, 'max_features': None, 'min_weight_fraction_leaf': 0.04455613136763016}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22775475401909703
Fold 2 IBS: 0.17495565316697842
Fold 3 IBS: 0.20607913041505693
Fold 4 IBS: 0.19159948662275345
Fold 5 IBS: 0.18048871793748186
[I 2024-04-22 02:44:36,586] Trial 58 finished with value: 0.19617554843227353 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 184, 'oob_score': True, 'max_samples': 0.9463423717095281, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1156031725017496}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22758477258081827
Fold 2 IBS: 0.17158899508130857
Fold 3 IBS: 0.19616659435415607
Fold 4 IBS: 0.19199468063765252
Fold 5 IBS: 0.17000810523027976
[I 2024-04-22 02:44:39,207] Trial 59 finished with value: 0.19146862957684302 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 297, 'oob_score': False, 'max_samples': 0.7604421792719349, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.003738110192922882}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22873607517785616
Fold 2 IBS: 0.17390045472096774
Fold 3 IBS: 0.19717465713467122
Fold 4 IBS: 0.19069798125902654
Fold 5 IBS: 0.16839044559038258
[I 2024-04-22 02:44:41,808] Trial 60 finished with value: 0.19177992277658085 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 297, 'oob_score': False, 'max_samples': 0.8025318592826676, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0035012585111243765}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.23001446011337487
Fold 2 IBS: 0.17351898966358764
Fold 3 IBS: 0.19693929350409167
Fold 4 IBS: 0.19025194043534524
Fold 5 IBS: 0.16918574368972547
[I 2024-04-22 02:44:44,498] Trial 61 finished with value: 0.19198208548122497 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 304, 'oob_score': False, 'max_samples': 0.7900678450377102, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00572289564152078}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22738806352311317
Fold 2 IBS: 0.17362132403038696
Fold 3 IBS: 0.19727565424618765
Fold 4 IBS: 0.19024256592293678

Fold 5 IBS: 0.16839194066878888
[I 2024-04-22 02:44:47,192] Trial 62 finished with value: 0.1913839096782827 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 298, 'oob_score': False, 'max_samples': 0.8075940187858324, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0028869935676452026}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22802304509837604
Fold 2 IBS: 0.17093887708958988
Fold 3 IBS: 0.19997810028764312
Fold 4 IBS: 0.19416891669551373
Fold 5 IBS: 0.16864914160971897
[I 2024-04-22 02:44:50,692] Trial 63 finished with value: 0.19235161615616833 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 305, 'oob_score': False, 'max_samples': 0.899801190989709, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0075083578814244606}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22706249643509485
Fold 2 IBS: 0.1740741132334453
Fold 3 IBS: 0.1982770517299122
Fold 4 IBS: 0.1942932217810348
Fold 5 IBS: 0.17209778370511547
[I 2024-04-22 02:44:55,212] Trial 64 finished with value: 0.1931609333769205 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.8279032572597822, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0005239520819106591}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2249627623000506
Fold 2 IBS: 0.17734214004526475
Fold 3 IBS: 0.20042821363889923
Fold 4 IBS: 0.19132512948604202
Fold 5 IBS: 0.17992503554600825
[I 2024-04-22 02:44:58,127] Trial 65 finished with value: 0.19479665620325298 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 8, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7929889902503702, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0003379495295398175}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2258580567600176
Fold 2 IBS: 0.1725987117538336
Fold 3 IBS: 0.19691363075454665
Fold 4 IBS: 0.19294818573115283
Fold 5 IBS: 0.16674549590339433
[I 2024-04-22 02:45:01,720] Trial 66 finished with value: 0.191012816180589 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 300, 'oob_score': False, 'max_samples': 0.8542677970427669, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02018893978213555}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22715985053253537
Fold 2 IBS: 0.175194067127973
Fold 3 IBS: 0.20235598060063445
Fold 4 IBS: 0.1915473606751296
Fold 5 IBS: 0.17533957463955674
[I 2024-04-22 02:45:04,585] Trial 67 finished with value: 0.19431936671516584 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 296, 'oob_score': False, 'max_samples': 0.8537028925191168, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06691183155682784}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2276240233573705
Fold 2 IBS: 0.17466029156341425
Fold 3 IBS: 0.19585094966145308
Fold 4 IBS: 0.1956019894346285
Fold 5 IBS: 0.17236600002537372
[I 2024-04-22 02:45:06,748] Trial 68 finished with value: 0.19322065080844802 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.8153568706687296, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.020589797791063878}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2300113020332438
Fold 2 IBS: 0.1687511692442822
Fold 3 IBS: 0.200433873197082
Fold 4 IBS: 0.19350383522262551
Fold 5 IBS: 0.1749683856491631
[I 2024-04-22 02:45:10,094] Trial 69 finished with value: 0.1935337130692793 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 357, 'oob_score': False, 'max_samples': 0.9627183310414489, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04180485598378051}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.21313163321533152
Fold 2 IBS: 0.18353505015435204
Fold 3 IBS: 0.21120737776495918
Fold 4 IBS: 0.19490170617054509
Fold 5 IBS: 0.19862473265977015
[I 2024-04-22 02:45:13,111] Trial 70 finished with value: 0.2002800999929916 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.9259785083383683, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.26527703823768367}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22671408988493402
Fold 2 IBS: 0.17109357051379762
Fold 3 IBS: 0.19869894342562636
Fold 4 IBS: 0.1930683536390453
Fold 5 IBS: 0.1684970080938331
[I 2024-04-22 02:45:15,975] Trial 71 finished with value: 0.19161439311144726 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 231, 'oob_score': False, 'max_samples': 0.8750321012509876, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.016570826484099625}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22688669905527847
Fold 2 IBS: 0.17075390562804646
Fold 3 IBS: 0.1985253537047414
Fold 4 IBS: 0.19308404898587175
Fold 5 IBS: 0.16784784499547226
[I 2024-04-22 02:45:19,029] Trial 72 finished with value: 0.19141957047388206 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 232, 'oob_score': False, 'max_samples': 0.8727329170058532, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014958115304314575}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22972629414025617
Fold 2 IBS: 0.1714974106484998
Fold 3 IBS: 0.19533970259706934
Fold 4 IBS: 0.19369830153535858
Fold 5 IBS: 0.17274176927442175
[I 2024-04-22 02:45:23,111] Trial 73 finished with value: 0.19260069563912113 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 271, 'oob_score': False, 'max_samples': 0.8762219604530712, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.017456169974200266}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22245678083193057
Fold 2 IBS: 0.17710628298553246
Fold 3 IBS: 0.2034119116741666
Fold 4 IBS: 0.19479658460004864
Fold 5 IBS: 0.19147425591218886
[I 2024-04-22 02:45:25,800] Trial 74 finished with value: 0.19784916320077342 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 235, 'oob_score': False, 'max_samples': 0.8496697690131644, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06167959702360663}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22047766774477437
Fold 2 IBS: 0.19344669693934774
Fold 3 IBS: 0.21000391860404677
Fold 4 IBS: 0.20477338938353398
Fold 5 IBS: 0.20541683976071617
[I 2024-04-22 02:45:28,192] Trial 75 finished with value: 0.2068237024864838 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 228, 'oob_score': False, 'max_samples': 0.890700122872072, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3160611948377179}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22684996172732363
Fold 2 IBS: 0.17136700641226504
Fold 3 IBS: 0.20076384707932607
Fold 4 IBS: 0.19600823288434543
Fold 5 IBS: 0.17509643852531095
[I 2024-04-22 02:45:31,639] Trial 76 finished with value: 0.19401709732571423 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 250, 'oob_score': True, 'max_samples': 0.963490685502655, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03671779555332485}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22243091080935176
Fold 2 IBS: 0.17909250139952151
Fold 3 IBS: 0.2011051393467259
Fold 4 IBS: 0.1920426126768079
Fold 5 IBS: 0.19402260004185645
[I 2024-04-22 02:45:33,300] Trial 77 finished with value: 0.1977387528548527 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.331919983653197, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07824582320277648}. Best is trial 49 with value: 0.19023957913930975.

Fold 1 IBS: 0.22661384896598818
Fold 2 IBS: 0.20671937958697834
Fold 3 IBS: 0.22631312111115084
Fold 4 IBS: 0.21497952798665046
Fold 5 IBS: 0.21282749449450544
[I 2024-04-22 02:45:35,672] Trial 78 finished with value: 0.21749067442905465 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.9147835512625551, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.43785214928176214}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.23052477127318172
Fold 2 IBS: 0.16982397129659127
Fold 3 IBS: 0.197745679074635
Fold 4 IBS: 0.19675496948041768
Fold 5 IBS: 0.1770213286573074
[I 2024-04-22 02:45:38,793] Trial 79 finished with value: 0.1943741439564266 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 275, 'oob_score': False, 'max_samples': 0.9974228392350986, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.013882614482266749}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.21778031450040175
Fold 2 IBS: 0.18157476210786558
Fold 3 IBS: 0.20901936393117487
Fold 4 IBS: 0.19843253192688598
Fold 5 IBS: 0.20260500447363683
[I 2024-04-22 02:45:40,518] Trial 80 finished with value: 0.201882395387993 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 196, 'oob_score': False, 'max_samples': 0.8074163719785258, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2343729610964786}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.23020712569648552
Fold 2 IBS: 0.17016574705246248
Fold 3 IBS: 0.19437724163558126
Fold 4 IBS: 0.19048729146333454
Fold 5 IBS: 0.16923782983271543
[I 2024-04-22 02:45:43,564] Trial 81 finished with value: 0.19089504713611585 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.7784763388289013, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.010595244727030426}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22633537924660144
Fold 2 IBS: 0.17245435825621444
Fold 3 IBS: 0.198261807277501
Fold 4 IBS: 0.19375808006799025
Fold 5 IBS: 0.17259241286993124
[I 2024-04-22 02:45:46,649] Trial 82 finished with value: 0.19268040754364765 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.8431704918534557, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.051048753251538945}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22652319655125724
Fold 2 IBS: 0.17122256301203548
Fold 3 IBS: 0.19686503258087146
Fold 4 IBS: 0.1924915525324402
Fold 5 IBS: 0.16992775902187662
[I 2024-04-22 02:45:48,641] Trial 83 finished with value: 0.1914060207396962 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 211, 'oob_score': False, 'max_samples': 0.8754608137046987, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.015226300624484834}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22719481979011316
Fold 2 IBS: 0.17681042979834713
Fold 3 IBS: 0.19352861064606583
Fold 4 IBS: 0.19070454017783864
Fold 5 IBS: 0.17349666127523256
[I 2024-04-22 02:45:52,767] Trial 84 finished with value: 0.19234701233751947 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 217, 'oob_score': False, 'max_samples': 0.8790183350095053, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0330313828916208}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2284060883547397
Fold 2 IBS: 0.17419251077518969
Fold 3 IBS: 0.19970363198080762
Fold 4 IBS: 0.19473581568220244
Fold 5 IBS: 0.176828897729793
[I 2024-04-22 02:45:55,330] Trial 85 finished with value: 0.19477338890454649 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 249, 'oob_score': False, 'max_samples': 0.7631874187375279, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01872628122372143}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22305736755182187
Fold 2 IBS: 0.17574939085892582
Fold 3 IBS: 0.19568084111601947
Fold 4 IBS: 0.19164045666660487
Fold 5 IBS: 0.1705187427582713
[I 2024-04-22 02:45:57,149] Trial 86 finished with value: 0.19132935979032867 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.74503188520459, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.049354259957534494}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2240633369122398
Fold 2 IBS: 0.17538320131641633
Fold 3 IBS: 0.19866223365506058
Fold 4 IBS: 0.19055945999140522
Fold 5 IBS: 0.17899242470900267
[I 2024-04-22 02:45:58,760] Trial 87 finished with value: 0.19353213131682495 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 188, 'oob_score': False, 'max_samples': 0.7394132698699142, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09171826513128181}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22531436049097633
Fold 2 IBS: 0.17338649398202335
Fold 3 IBS: 0.19541984829438955
Fold 4 IBS: 0.19633643985222626
Fold 5 IBS: 0.17132056753628644
[I 2024-04-22 02:46:01,291] Trial 88 finished with value: 0.19235554203118038 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.7818271131584801, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04741359111187626}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.24634541122033987
Fold 2 IBS: 0.2321226179655187
Fold 3 IBS: 0.22957248320549392
Fold 4 IBS: 0.24133401177007524
Fold 5 IBS: 0.22999623321892046
[I 2024-04-22 02:46:03,089] Trial 89 finished with value: 0.23587415147606966 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.15094844814066605, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18451336087256687}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22279933131837096
Fold 2 IBS: 0.17181835390229477
Fold 3 IBS: 0.2007160874798753
Fold 4 IBS: 0.197203380481848
Fold 5 IBS: 0.17515803600889934
[I 2024-04-22 02:46:04,441] Trial 90 finished with value: 0.19353903783825768 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 129, 'oob_score': False, 'max_samples': 0.7242871632922839, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06749203999049488}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22424300030428562
Fold 2 IBS: 0.17328433759407055
Fold 3 IBS: 0.19523917924376888
Fold 4 IBS: 0.19315716958653814
Fold 5 IBS: 0.1704614508554719
[I 2024-04-22 02:46:06,760] Trial 91 finished with value: 0.19127702751682701 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.8334209164391518, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014138517009539523}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22184929782482737
Fold 2 IBS: 0.17627486877830942
Fold 3 IBS: 0.1943876201108137
Fold 4 IBS: 0.19108122099131164
Fold 5 IBS: 0.17147705560864723
[I 2024-04-22 02:46:09,957] Trial 92 finished with value: 0.19101401266278187 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.6946552112995523, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03125200733960136}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2239870857063055
Fold 2 IBS: 0.17944345181206486
Fold 3 IBS: 0.1900538617099537
Fold 4 IBS: 0.19293425732594438

Fold 5 IBS: 0.16901501941163646
[I 2024-04-22 02:46:11,875] Trial 93 finished with value: 0.19108673519318098 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 179, 'oob_score': False, 'max_samples': 0.8387093701884653, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030817946786640082}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22184856220737365
Fold 2 IBS: 0.17312992964385657
Fold 3 IBS: 0.1948930255496256
Fold 4 IBS: 0.1925411854591036
Fold 5 IBS: 0.1730631403095586
[I 2024-04-22 02:46:13,589] Trial 94 finished with value: 0.1910951686339036 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.688472014648766, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03451598429298541}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.24047052597810953
Fold 2 IBS: 0.17250441339722747
Fold 3 IBS: 0.20953833222155935
Fold 4 IBS: 0.2100206291818941
Fold 5 IBS: 0.17584248631889507
[I 2024-04-22 02:46:15,651] Trial 95 finished with value: 0.2016752774195371 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.6970192006469513, 'max_features': None, 'min_weight_fraction_leaf': 0.03192478980412634}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2258454786784926
Fold 2 IBS: 0.17622029117710752
Fold 3 IBS: 0.19704459447649766
Fold 4 IBS: 0.18859439451234322
Fold 5 IBS: 0.17741716444849034
[I 2024-04-22 02:46:18,756] Trial 96 finished with value: 0.19302438465858626 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.6860275498472574, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05374102069256326}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22481323122042657
Fold 2 IBS: 0.17216098643824315
Fold 3 IBS: 0.19306385345921517
Fold 4 IBS: 0.19583934030263228
Fold 5 IBS: 0.17882594481487218
[I 2024-04-22 02:46:20,396] Trial 97 finished with value: 0.19294067124707787 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.6513894290159268, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04184810194054517}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2281068681622065
Fold 2 IBS: 0.17408803145260857
Fold 3 IBS: 0.19824195355773988
Fold 4 IBS: 0.1904600456326597
Fold 5 IBS: 0.17922094521554732
[I 2024-04-22 02:46:24,171] Trial 98 finished with value: 0.1940235688041524 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.7342462417517636, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07703075927677872}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2259945894827042
Fold 2 IBS: 0.17396367577577646
Fold 3 IBS: 0.2055533021506421
Fold 4 IBS: 0.1955608834617829
Fold 5 IBS: 0.1805672129301506
[I 2024-04-22 02:46:25,940] Trial 99 finished with value: 0.19632793276021127 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 153, 'oob_score': False, 'max_samples': 0.8324527674106177, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09813787485590943}. Best is trial 49 with value: 0.19023957913930975.


* Best trial for IBS:
 FrozenTrial(number=49, state=TrialState.COMPLETE, values=[0.19023957913930975], datetime_start=datetime.datetime(2024, 4, 22, 2, 44, 12, 249347), datetime_complete=datetime.datetime(2024, 4, 22, 2, 44, 14, 341317), params={'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 215, 'oob_score': False, 'max_samples': 0.7890788621794695, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04458702793409107}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=49, value=None)


* Best Score for IBS:
 0.19023957913930975

In [55]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [56]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.866
train_ibs:  0.19

#### Test

In [57]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [58]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=10, max_leaf_nodes=14,
                     max_samples=0.8746458616251406, min_samples_leaf=2,
                     min_weight_fraction_leaf=0.030922977401692878,
                     n_estimators=113, random_state=123, warm_start=True)

test_cindex:  0.546

RandomSurvivalForest(max_depth=8, max_leaf_nodes=17,
                     max_samples=0.7890788621794695, min_samples_leaf=2,
                     min_samples_split=2,
                     min_weight_fraction_leaf=0.04458702793409107,
                     n_estimators=215, random_state=123)

test_ibs:  0.263

In [59]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [86]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [87]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-22 09:25:08,166] A new study created in memory with name: no-name-c0213e53-6473-4df9-a859-e07e85248eb4

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 09:25:09,031] Trial 0 finished with value: 0.7623102721396274 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 09:25:10,678] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6952789699570815
[I 2024-04-22 09:25:13,897] Trial 2 finished with value: 0.7156366754220176 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7253218884120172
[I 2024-04-22 09:25:14,249] Trial 3 finished with value: 0.7402725229380251 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 09:25:15,462] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 09:25:17,004] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7381974248927039
[I 2024-04-22 09:25:17,841] Trial 6 finished with value: 0.7499745725457844 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7896995708154506
[I 2024-04-22 09:25:19,682] Trial 7 finished with value: 0.744770291905024 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7296137339055794
[I 2024-04-22 09:25:19,788] Trial 8 finished with value: 0.7197332454598995 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 09:25:23,108] Trial 9 finished with value: 0.7117523204127156 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 09:25:24,375] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6995708154506438
[I 2024-04-22 09:25:24,994] Trial 11 finished with value: 0.7295841326588206 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8111587982832618
[I 2024-04-22 09:25:25,808] Trial 12 finished with value: 0.7867972827001483 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6995708154506438
[I 2024-04-22 09:25:26,594] Trial 13 finished with value: 0.7316705235163293 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.703862660944206
[I 2024-04-22 09:25:27,208] Trial 14 finished with value: 0.7390987799796523 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6995708154506438
[I 2024-04-22 09:25:27,644] Trial 15 finished with value: 0.7406634812581807 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7867972827001483.

Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6759656652360515
[I 2024-04-22 09:25:28,399] Trial 16 finished with value: 0.7032137338705444 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 09:25:28,929] Trial 17 finished with value: 0.731554986493769 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 09:25:29,752] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.6952789699570815
[I 2024-04-22 09:25:30,368] Trial 19 finished with value: 0.7358463917100135 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8361702127659575
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6630901287553648
[I 2024-04-22 09:25:30,458] Trial 20 finished with value: 0.7074965456605569 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7381974248927039
[I 2024-04-22 09:25:31,136] Trial 21 finished with value: 0.7550267044437244 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.759656652360515
[I 2024-04-22 09:25:31,834] Trial 22 finished with value: 0.7661315662080361 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8197424892703863
[I 2024-04-22 09:25:32,617] Trial 23 finished with value: 0.7937218312264874 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7424892703862661
[I 2024-04-22 09:25:33,370] Trial 24 finished with value: 0.7580764020718593 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8068669527896996
[I 2024-04-22 09:25:34,025] Trial 25 finished with value: 0.762803163214613 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 09:25:37,423] Trial 26 finished with value: 0.7223549195144154 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.703862660944206
[I 2024-04-22 09:25:38,231] Trial 27 finished with value: 0.7342711010948667 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7112403100775194
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 09:25:38,841] Trial 28 finished with value: 0.7193098171027112 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6952789699570815
[I 2024-04-22 09:25:39,255] Trial 29 finished with value: 0.7198566127686613 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.759656652360515
[I 2024-04-22 09:25:39,861] Trial 30 finished with value: 0.7622850722651587 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.7937218312264874.

Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8068669527896996
[I 2024-04-22 09:25:40,509] Trial 31 finished with value: 0.7651208885111453 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6357896182918609, 'min_weight_fraction_leaf': 0.043457520259011145}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7553648068669528
[I 2024-04-22 09:25:41,179] Trial 32 finished with value: 0.7493192073790584 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4847410905891233, 'min_weight_fraction_leaf': 0.054624644214656966}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.703862660944206
[I 2024-04-22 09:25:41,923] Trial 33 finished with value: 0.7351654028257627 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.527493679418052, 'min_weight_fraction_leaf': 0.11101292483370524}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.8111587982832618
[I 2024-04-22 09:25:42,625] Trial 34 finished with value: 0.760702458675475 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9202590430146967, 'min_weight_fraction_leaf': 0.07023282430953717}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7939914163090128
[I 2024-04-22 09:25:44,635] Trial 35 finished with value: 0.7624993862330411 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 474, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6140705076527802, 'min_weight_fraction_leaf': 0.02925664606041241}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.6995708154506438
[I 2024-04-22 09:25:47,315] Trial 36 finished with value: 0.719921700077874 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 349, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6785531388726883, 'min_weight_fraction_leaf': 0.1272251175690979}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 09:25:48,148] Trial 37 finished with value: 0.5 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8050041507306814, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 09:25:49,033] Trial 38 finished with value: 0.7247202242856303 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 435, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.05649565215079118}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.703862660944206
[I 2024-04-22 09:25:54,029] Trial 39 finished with value: 0.7213553719700059 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 472, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.5401322211198275, 'min_weight_fraction_leaf': 0.09113105544483305}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8197424892703863
[I 2024-04-22 09:25:54,583] Trial 40 finished with value: 0.7770575045494358 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 300, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7399942977302993, 'min_weight_fraction_leaf': 0.025013264992292644}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8497854077253219
[I 2024-04-22 09:25:55,100] Trial 41 finished with value: 0.7896617263093931 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7332367119565565, 'min_weight_fraction_leaf': 0.0016561031617871522}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8326180257510729
[I 2024-04-22 09:25:55,533] Trial 42 finished with value: 0.780595334917785 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 155, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7291601013114538, 'min_weight_fraction_leaf': 0.0015116719780719767}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8369098712446352
[I 2024-04-22 09:25:56,011] Trial 43 finished with value: 0.7901642333193999 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 162, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7528934931474498, 'min_weight_fraction_leaf': 0.007759295188642418}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8454935622317596
[I 2024-04-22 09:25:56,364] Trial 44 finished with value: 0.7872592837754979 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 156, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8327721232082076, 'min_weight_fraction_leaf': 0.01305046995423322}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8369098712446352
[I 2024-04-22 09:25:56,694] Trial 45 finished with value: 0.777513445436739 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 157, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8255054025331079, 'min_weight_fraction_leaf': 0.0031249321027524285}. Best is trial 23 with value: 0.7937218312264874.

Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8326180257510729
[I 2024-04-22 09:25:57,083] Trial 46 finished with value: 0.7917141970732431 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 198, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9257094805962044, 'min_weight_fraction_leaf': 0.022307192777154376}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7682403433476395
[I 2024-04-22 09:25:58,327] Trial 47 finished with value: 0.7453719568208577 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 196, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9265198018232372, 'min_weight_fraction_leaf': 0.05973916326993964}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7034883720930233
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7167381974248928
[I 2024-04-22 09:25:58,895] Trial 48 finished with value: 0.7193712893481361 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 121, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7632274813615122, 'min_weight_fraction_leaf': 0.3078000969326991}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6996124031007752
Fold 3 C-index: 0.8148936170212766
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6802575107296137
[I 2024-04-22 09:25:59,319] Trial 49 finished with value: 0.7112005967373427 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 221, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9454880021924575, 'min_weight_fraction_leaf': 0.3739970568853183}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.8154506437768241
[I 2024-04-22 09:25:59,590] Trial 50 finished with value: 0.763269836859631 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 117, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.843804589889048, 'min_weight_fraction_leaf': 0.0873347394612367}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8497854077253219
[I 2024-04-22 09:25:59,949] Trial 51 finished with value: 0.7911199644131695 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 179, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.957889367228467, 'min_weight_fraction_leaf': 0.025973798263736272}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8326180257510729
[I 2024-04-22 09:26:00,326] Trial 52 finished with value: 0.7867595541571949 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 180, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7903103587545204, 'min_weight_fraction_leaf': 0.023179220994950622}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8240343347639485
[I 2024-04-22 09:26:00,536] Trial 53 finished with value: 0.7789155204597524 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 78, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9463423717095281, 'min_weight_fraction_leaf': 0.01957247755969179}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8111587982832618
[I 2024-04-22 09:26:00,988] Trial 54 finished with value: 0.7748590141721845 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8980357949184589, 'min_weight_fraction_leaf': 0.04833675638502302}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8068669527896996
[I 2024-04-22 09:26:01,334] Trial 55 finished with value: 0.7810021652909311 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 177, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8672614385579406, 'min_weight_fraction_leaf': 0.07284912883734934}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8326180257510729
[I 2024-04-22 09:26:01,636] Trial 56 finished with value: 0.7813968466847471 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 141, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8280080010077513, 'min_weight_fraction_leaf': 0.014205042834379285}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7081545064377682
[I 2024-04-22 09:26:02,078] Trial 57 finished with value: 0.7352517352068838 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 247, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7559818229866901, 'min_weight_fraction_leaf': 0.12105610192383184}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7854077253218884
[I 2024-04-22 09:26:03,471] Trial 58 finished with value: 0.7495185198345575 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 223, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6819194445137657, 'min_weight_fraction_leaf': 0.0412960148860697}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8454935622317596
[I 2024-04-22 09:26:04,458] Trial 59 finished with value: 0.8084662710816808 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 271, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.964838395481847, 'min_weight_fraction_leaf': 4.407900941855603e-05}. Best is trial 59 with value: 0.8084662710816808.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 09:26:05,450] Trial 60 finished with value: 0.7300297987713386 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 274, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9553308503405183, 'min_weight_fraction_leaf': 0.2583710069782479}. Best is trial 59 with value: 0.8084662710816808.

Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8454935622317596
[I 2024-04-22 09:26:06,180] Trial 61 finished with value: 0.8006710951960759 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 191, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.99214746221766, 'min_weight_fraction_leaf': 0.00034340752043091755}. Best is trial 59 with value: 0.8084662710816808.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8326180257510729
[I 2024-04-22 09:26:06,912] Trial 62 finished with value: 0.7829099031334593 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 194, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.995392611213117, 'min_weight_fraction_leaf': 0.03766384718061227}. Best is trial 59 with value: 0.8084662710816808.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8540772532188842
[I 2024-04-22 09:26:07,833] Trial 63 finished with value: 0.8166801836932367 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 231, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9159857443892336, 'min_weight_fraction_leaf': 0.000272750956431346}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8369098712446352
[I 2024-04-22 09:26:08,485] Trial 64 finished with value: 0.800657051922378 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 181, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9104584386149728, 'min_weight_fraction_leaf': 0.05591333445734158}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8283261802575107
[I 2024-04-22 09:26:09,316] Trial 65 finished with value: 0.7934970372032099 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 208, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9648986760030055, 'min_weight_fraction_leaf': 0.06680538576359879}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8240343347639485
[I 2024-04-22 09:26:10,114] Trial 66 finished with value: 0.7878220023993864 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 203, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9095982739365324, 'min_weight_fraction_leaf': 0.06752219873139698}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7896995708154506
[I 2024-04-22 09:26:11,067] Trial 67 finished with value: 0.7729438440738962 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 271, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8746455577810428, 'min_weight_fraction_leaf': 0.09750609016881821}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8283261802575107
[I 2024-04-22 09:26:11,942] Trial 68 finished with value: 0.7972745425406186 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 240, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.968180725622439, 'min_weight_fraction_leaf': 0.054110870458248334}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7296137339055794
[I 2024-04-22 09:26:12,781] Trial 69 finished with value: 0.7490725417029068 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 232, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.995297083745019, 'min_weight_fraction_leaf': 0.16115376582527763}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7682403433476395
[I 2024-04-22 09:26:15,394] Trial 70 finished with value: 0.7431377642689725 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 323, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9769199467223223, 'min_weight_fraction_leaf': 0.055426720208080725}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8283261802575107
[I 2024-04-22 09:26:16,488] Trial 71 finished with value: 0.8004580691916237 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 208, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9375782206126794, 'min_weight_fraction_leaf': 0.04507778368190728}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8240343347639485
[I 2024-04-22 09:26:17,647] Trial 72 finished with value: 0.7916358642120349 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 239, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9676798282975951, 'min_weight_fraction_leaf': 0.0787773084868472}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7424892703862661
[I 2024-04-22 09:26:18,684] Trial 73 finished with value: 0.7571821003409633 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 212, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8950935256166086, 'min_weight_fraction_leaf': 0.11229900026623069}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8283261802575107
[I 2024-04-22 09:26:19,894] Trial 74 finished with value: 0.795695654567296 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 260, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9359651513439894, 'min_weight_fraction_leaf': 0.05058223539315274}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8240343347639485
[I 2024-04-22 09:26:21,116] Trial 75 finished with value: 0.7939103516074585 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 260, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9343716260288816, 'min_weight_fraction_leaf': 0.043108638690303853}. Best is trial 63 with value: 0.8166801836932367.

Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7939914163090128
[I 2024-04-22 09:26:22,674] Trial 76 finished with value: 0.7784671388150444 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 286, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9321739716438541, 'min_weight_fraction_leaf': 0.03655310676155976}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8197424892703863
[I 2024-04-22 09:26:24,016] Trial 77 finished with value: 0.7875133994130215 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 254, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8655648399730119, 'min_weight_fraction_leaf': 0.04756050968696869}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7982832618025751
[I 2024-04-22 09:26:25,274] Trial 78 finished with value: 0.7817849347662374 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 269, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9999098672482281, 'min_weight_fraction_leaf': 0.0863331818418738}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7253218884120172
[I 2024-04-22 09:26:26,713] Trial 79 finished with value: 0.7456694044778016 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 303, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.2170140247726947, 'min_weight_fraction_leaf': 0.034493408415334006}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7339055793991416
[I 2024-04-22 09:26:27,890] Trial 80 finished with value: 0.753005935291058 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 260, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9098917820806076, 'min_weight_fraction_leaf': 0.13389187501653388}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8283261802575107
[I 2024-04-22 09:26:28,584] Trial 81 finished with value: 0.8051772459148425 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 137, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9424018134336887, 'min_weight_fraction_leaf': 0.05108896602934009}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8497854077253219
[I 2024-04-22 09:26:29,754] Trial 82 finished with value: 0.809469091408405 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 282, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9410740612472716, 'min_weight_fraction_leaf': 0.012322578348389443}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8540772532188842
[I 2024-04-22 09:26:30,794] Trial 83 finished with value: 0.8167597780695852 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 285, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8871550861115998, 'min_weight_fraction_leaf': 0.013985838803987693}. Best is trial 83 with value: 0.8167597780695852.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8412017167381974
[I 2024-04-22 09:26:31,383] Trial 84 finished with value: 0.812474687015057 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 138, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8841264487793694, 'min_weight_fraction_leaf': 0.016386251952087417}. Best is trial 83 with value: 0.8167597780695852.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8540772532188842
[I 2024-04-22 09:26:31,956] Trial 85 finished with value: 0.8158908196342545 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 141, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.888479352560009, 'min_weight_fraction_leaf': 0.012716341560856033}. Best is trial 83 with value: 0.8167597780695852.
Fold 1 C-index: 0.6972111553784861
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8841201716738197
[I 2024-04-22 09:26:32,513] Trial 86 finished with value: 0.8257675162186733 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 137, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8608986608214496, 'min_weight_fraction_leaf': 0.013300177959391254}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7081545064377682
[I 2024-04-22 09:26:32,917] Trial 87 finished with value: 0.7417472944772566 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 91, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8607992629190876, 'min_weight_fraction_leaf': 0.01139343678306486}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.8025751072961373
[I 2024-04-22 09:26:33,696] Trial 88 finished with value: 0.7421126194553279 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 84, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8099246282391572, 'min_weight_fraction_leaf': 0.013604529607415802}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.701195219123506
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8626609442060086
[I 2024-04-22 09:26:34,263] Trial 89 finished with value: 0.8246591973761161 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 139, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8911664954143093, 'min_weight_fraction_leaf': 0.0010890713950365803}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8369098712446352
[I 2024-04-22 09:26:34,830] Trial 90 finished with value: 0.8093017497006703 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 137, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8846592522748477, 'min_weight_fraction_leaf': 0.027028995364682774}. Best is trial 86 with value: 0.8257675162186733.

Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8283261802575107
[I 2024-04-22 09:26:35,381] Trial 91 finished with value: 0.8083385863511406 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 133, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8818337195376095, 'min_weight_fraction_leaf': 0.029196432033481958}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7296137339055794
[I 2024-04-22 09:26:35,931] Trial 92 finished with value: 0.7552483413861439 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 135, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.887423031596968, 'min_weight_fraction_leaf': 0.025844049706309193}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8283261802575107
[I 2024-04-22 09:26:36,256] Trial 93 finished with value: 0.8059160832380525 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 66, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8488078188965495, 'min_weight_fraction_leaf': 0.013011220287553072}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8326180257510729
[I 2024-04-22 09:26:36,726] Trial 94 finished with value: 0.8092765498262015 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 111, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7853435226199493, 'min_weight_fraction_leaf': 0.02738269110214168}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8755364806866953
[I 2024-04-22 09:26:37,173] Trial 95 finished with value: 0.826448505102924 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 105, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8161032428574773, 'min_weight_fraction_leaf': 0.001106761767719347}. Best is trial 95 with value: 0.826448505102924.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8154506437768241
[I 2024-04-22 09:26:37,663] Trial 96 finished with value: 0.7842940671166678 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 113, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7755580189933128, 'min_weight_fraction_leaf': 0.015997371825892767}. Best is trial 95 with value: 0.826448505102924.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.759656652360515
[I 2024-04-22 09:26:37,906] Trial 97 finished with value: 0.7672112148047836 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 39, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8147988676493763, 'min_weight_fraction_leaf': 0.0308224860074267}. Best is trial 95 with value: 0.826448505102924.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7124463519313304
[I 2024-04-22 09:26:38,325] Trial 98 finished with value: 0.7385526112254805 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 97, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7875371195797898, 'min_weight_fraction_leaf': 0.20718461376465755}. Best is trial 95 with value: 0.826448505102924.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.6957364341085271
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.720532319391635

[I 2024-04-22 09:26:38,839] A new study created in memory with name: no-name-f1b5a66f-ba5b-4fbe-8ec4-9c71ec4bcf7b

Fold 5 C-index: 0.6459227467811158
[I 2024-04-22 09:26:38,833] Trial 99 finished with value: 0.6919788612158724 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 126, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8515495175736911, 'min_weight_fraction_leaf': 0.4077588868802398}. Best is trial 95 with value: 0.826448505102924.


* Best trial for C-index:
 FrozenTrial(number=95, state=TrialState.COMPLETE, values=[0.826448505102924], datetime_start=datetime.datetime(2024, 4, 22, 9, 26, 36, 729466), datetime_complete=datetime.datetime(2024, 4, 22, 9, 26, 37, 172921), params={'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 105, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8161032428574773, 'min_weight_fraction_leaf': 0.001106761767719347}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=95, value=None)


* Best Score for C-index:
 0.826448505102924

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2216883708385238
Fold 2 IBS: 0.20116513124707355
Fold 3 IBS: 0.18963496960925966
Fold 4 IBS: 0.20548033840998792
Fold 5 IBS: 0.18750823813035528
[I 2024-04-22 09:26:41,037] Trial 0 finished with value: 0.20109540964704004 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-22 09:26:44,360] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.23328845550406502
Fold 2 IBS: 0.21810066709735482
Fold 3 IBS: 0.2100774317752478
Fold 4 IBS: 0.22329553132649185
Fold 5 IBS: 0.2114469499436477
[I 2024-04-22 09:26:47,970] Trial 2 finished with value: 0.21924180712936142 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.2351174850348692
Fold 2 IBS: 0.219828345872527
Fold 3 IBS: 0.21173255582990505
Fold 4 IBS: 0.22584022524964367
Fold 5 IBS: 0.21387778959798523
[I 2024-04-22 09:26:49,280] Trial 3 finished with value: 0.22127928031698602 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-22 09:26:52,444] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-22 09:26:54,068] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.22285591564464766
Fold 2 IBS: 0.20324049199979516
Fold 3 IBS: 0.19028540014692436
Fold 4 IBS: 0.2090397510159576
Fold 5 IBS: 0.1897288358797867
[I 2024-04-22 09:26:57,248] Trial 6 finished with value: 0.20303007893742228 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.22779745048944502
Fold 2 IBS: 0.21116263533467225
Fold 3 IBS: 0.20158439716136908
Fold 4 IBS: 0.21503406407606104
Fold 5 IBS: 0.2009534751387103
[I 2024-04-22 09:26:59,053] Trial 7 finished with value: 0.21130640444005158 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.2336849435018476
Fold 2 IBS: 0.21699322646377178
Fold 3 IBS: 0.20944474413453934
Fold 4 IBS: 0.22497867659365728
Fold 5 IBS: 0.21355042601743562
[I 2024-04-22 09:26:59,423] Trial 8 finished with value: 0.21973040334225033 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.23735614317408008
Fold 2 IBS: 0.22250970142913065
Fold 3 IBS: 0.21632908896013436
Fold 4 IBS: 0.23142974084173232
Fold 5 IBS: 0.21892814505251118
[I 2024-04-22 09:27:02,942] Trial 9 finished with value: 0.22531056389151768 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.24672496618607107
Fold 2 IBS: 0.23224650601788785
Fold 3 IBS: 0.23004987749916536
Fold 4 IBS: 0.2412296281450331
Fold 5 IBS: 0.23015666331663637
[I 2024-04-22 09:27:05,516] Trial 10 finished with value: 0.23608152823295875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.23022250449663892
Fold 2 IBS: 0.20809523912377517
Fold 3 IBS: 0.19803303843460215
Fold 4 IBS: 0.21550808264334878
Fold 5 IBS: 0.20218737765773626
[I 2024-04-22 09:27:07,641] Trial 11 finished with value: 0.21080924847122023 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.21613989052002444
Fold 2 IBS: 0.1966321312406504
Fold 3 IBS: 0.18848837574478716
Fold 4 IBS: 0.20253748024407425
Fold 5 IBS: 0.18190788145678702
[I 2024-04-22 09:27:10,687] Trial 12 finished with value: 0.19714115184126466 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.22624638824497345
Fold 2 IBS: 0.208132783074928
Fold 3 IBS: 0.1957266434056336
Fold 4 IBS: 0.21533929207751132
Fold 5 IBS: 0.19842738811030086
[I 2024-04-22 09:27:13,729] Trial 13 finished with value: 0.20877449898266948 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.22734034749345805
Fold 2 IBS: 0.20875433795400827
Fold 3 IBS: 0.19554481462030096
Fold 4 IBS: 0.217258375641282
Fold 5 IBS: 0.19872227743792803
[I 2024-04-22 09:27:16,015] Trial 14 finished with value: 0.20952403062939545 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.19714115184126466.

Fold 1 IBS: 0.2285622101008634
Fold 2 IBS: 0.20843529070864095
Fold 3 IBS: 0.19501846306370746
Fold 4 IBS: 0.21559689896401366
Fold 5 IBS: 0.19971924614220493
[I 2024-04-22 09:27:17,621] Trial 15 finished with value: 0.20946642179588607 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.2404239471321595
Fold 2 IBS: 0.22515713522164824
Fold 3 IBS: 0.21747041451130297
Fold 4 IBS: 0.23590557558587374
Fold 5 IBS: 0.2189832067887446
[I 2024-04-22 09:27:21,667] Trial 16 finished with value: 0.2275880558479458 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.2265766966093104
Fold 2 IBS: 0.21304461762010127
Fold 3 IBS: 0.19686726071348115
Fold 4 IBS: 0.21529218618416335
Fold 5 IBS: 0.19893026398098457
[I 2024-04-22 09:27:23,991] Trial 17 finished with value: 0.21014220502160813 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.24679929991389535
Fold 2 IBS: 0.23208761806557146
Fold 3 IBS: 0.2295482436451861
Fold 4 IBS: 0.24111555931482462
Fold 5 IBS: 0.22939893490285035
[I 2024-04-22 09:27:24,934] Trial 18 finished with value: 0.23578993116846556 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.226522202989843
Fold 2 IBS: 0.20703960609508038
Fold 3 IBS: 0.1942721352571641
Fold 4 IBS: 0.21479270879307474
Fold 5 IBS: 0.19770773184290516
[I 2024-04-22 09:27:27,338] Trial 19 finished with value: 0.2080668769956135 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.22860530313751873
Fold 2 IBS: 0.2197286802115928
Fold 3 IBS: 0.20141531822386521
Fold 4 IBS: 0.23000502351334556
Fold 5 IBS: 0.20897153269462923
[I 2024-04-22 09:27:27,535] Trial 20 finished with value: 0.2177451715561903 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.22277384041815695
Fold 2 IBS: 0.20334257879097034
Fold 3 IBS: 0.19030809415067831
Fold 4 IBS: 0.2080413933204737
Fold 5 IBS: 0.18916272546530452
[I 2024-04-22 09:27:30,955] Trial 21 finished with value: 0.20272572642911676 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.22001622035995086
Fold 2 IBS: 0.20143159104176697
Fold 3 IBS: 0.18930871547839062
Fold 4 IBS: 0.20556188928342486
Fold 5 IBS: 0.18618950630512082
[I 2024-04-22 09:27:34,232] Trial 22 finished with value: 0.20050158449373084 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.21613582256339794
Fold 2 IBS: 0.19387991553904665
Fold 3 IBS: 0.18688212496978923
Fold 4 IBS: 0.19909456369999257
Fold 5 IBS: 0.1769669671210479
[I 2024-04-22 09:27:37,751] Trial 23 finished with value: 0.19459187877865486 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.22098376153714128
Fold 2 IBS: 0.2017790967079455
Fold 3 IBS: 0.18977869471880326
Fold 4 IBS: 0.20562300123773503
Fold 5 IBS: 0.1895750781822595
[I 2024-04-22 09:27:40,625] Trial 24 finished with value: 0.2015479264767769 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.2283056563231173
Fold 2 IBS: 0.21007958258826712
Fold 3 IBS: 0.20299281229435043
Fold 4 IBS: 0.21313667345754783
Fold 5 IBS: 0.20072093838312854
[I 2024-04-22 09:27:43,133] Trial 25 finished with value: 0.21104713260928226 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.22547573656030792
Fold 2 IBS: 0.2067128508655798
Fold 3 IBS: 0.1939155139277123
Fold 4 IBS: 0.21316063898492277
Fold 5 IBS: 0.1966361463030427
[I 2024-04-22 09:27:47,039] Trial 26 finished with value: 0.20718017732831312 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.22651286012786861
Fold 2 IBS: 0.2071828931412121
Fold 3 IBS: 0.19383543230944772
Fold 4 IBS: 0.21404492643798378
Fold 5 IBS: 0.1965677671793665
[I 2024-04-22 09:27:50,366] Trial 27 finished with value: 0.20762877583917572 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.2296162488525048
Fold 2 IBS: 0.21553963633321688
Fold 3 IBS: 0.19785601697252495
Fold 4 IBS: 0.2188768233602731
Fold 5 IBS: 0.20093600143211168
[I 2024-04-22 09:27:52,656] Trial 28 finished with value: 0.2125649453901263 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.2320037319505613
Fold 2 IBS: 0.21529282635362382
Fold 3 IBS: 0.20073796574461872
Fold 4 IBS: 0.22374477453593242
Fold 5 IBS: 0.20919202181500016
[I 2024-04-22 09:27:54,506] Trial 29 finished with value: 0.2161942640799473 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.19459187877865486.

Fold 1 IBS: 0.2233579319393271
Fold 2 IBS: 0.20096408163499427
Fold 3 IBS: 0.19049881866793233
Fold 4 IBS: 0.20774755146340546
Fold 5 IBS: 0.19123419554925844
[I 2024-04-22 09:27:56,893] Trial 30 finished with value: 0.20276051585098354 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.2179837541713329
Fold 2 IBS: 0.19996868148399857
Fold 3 IBS: 0.18950194352113112
Fold 4 IBS: 0.20402491486791338
Fold 5 IBS: 0.18472430994108335
[I 2024-04-22 09:27:59,279] Trial 31 finished with value: 0.19924072079709187 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.923666057752446, 'min_weight_fraction_leaf': 0.09694658331929079}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.2165115875368992
Fold 2 IBS: 0.19730089666900102
Fold 3 IBS: 0.18932681429498213
Fold 4 IBS: 0.2026285347669489
Fold 5 IBS: 0.18129650151368074
[I 2024-04-22 09:28:01,878] Trial 32 finished with value: 0.1974128669563024 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.939007534925735, 'min_weight_fraction_leaf': 0.056106269226335825}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.22215223881932283
Fold 2 IBS: 0.20404673534195444
Fold 3 IBS: 0.19059256536590438
Fold 4 IBS: 0.20867030880038456
Fold 5 IBS: 0.1902323613350749
[I 2024-04-22 09:28:04,783] Trial 33 finished with value: 0.20313884193252824 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 394, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9138848353483187, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.21571300333932517
Fold 2 IBS: 0.1845951559627474
Fold 3 IBS: 0.18880163665481287
Fold 4 IBS: 0.1949110082696481
Fold 5 IBS: 0.17373428623842993
[I 2024-04-22 09:28:08,193] Trial 34 finished with value: 0.1915510180929927 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.06204686171902169}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21454541287943435
Fold 2 IBS: 0.18693346330112653
Fold 3 IBS: 0.19102421355153448
Fold 4 IBS: 0.19551337596236062
Fold 5 IBS: 0.1761961240257905
[I 2024-04-22 09:28:12,031] Trial 35 finished with value: 0.1928425179440493 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 465, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8327847526324277, 'min_weight_fraction_leaf': 0.055940476394666754}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21421473813611983
Fold 2 IBS: 0.18781798129221267
Fold 3 IBS: 0.19253146542248586
Fold 4 IBS: 0.19760463791446536
Fold 5 IBS: 0.17599130386074804
[I 2024-04-22 09:28:15,585] Trial 36 finished with value: 0.19363202532520635 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 456, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.827098326399153, 'min_weight_fraction_leaf': 0.06897665469252873}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.220989467263724
Fold 2 IBS: 0.19890804921057023
Fold 3 IBS: 0.1955995866337726
Fold 4 IBS: 0.20347488198691915
Fold 5 IBS: 0.18652218714210275
[I 2024-04-22 09:28:19,021] Trial 37 finished with value: 0.20109883444741775 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8333567609683693, 'min_weight_fraction_leaf': 0.12103866621890363}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21403271727225354
Fold 2 IBS: 0.1880480951062635
Fold 3 IBS: 0.1927275263843754
Fold 4 IBS: 0.19690061622051883
Fold 5 IBS: 0.17593442460775408
[I 2024-04-22 09:28:22,118] Trial 38 finished with value: 0.19352867591823306 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 345, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8095186934535692, 'min_weight_fraction_leaf': 0.06981260769852976}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.228306499716191
Fold 2 IBS: 0.211502363047124
Fold 3 IBS: 0.19915744044493738
Fold 4 IBS: 0.21580761059677792
Fold 5 IBS: 0.19923517798027957
[I 2024-04-22 09:28:25,280] Trial 39 finished with value: 0.21080181835706197 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8235915436715224, 'min_weight_fraction_leaf': 0.2150204152808745}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.22009212142996487
Fold 2 IBS: 0.20235485246883128
Fold 3 IBS: 0.19662068942862213
Fold 4 IBS: 0.20713783696954896
Fold 5 IBS: 0.18874034333226591
[I 2024-04-22 09:28:26,599] Trial 40 finished with value: 0.20298916872584663 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 166, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7763291518258434, 'min_weight_fraction_leaf': 0.1415885205487063}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21512726209197802
Fold 2 IBS: 0.19166650395727697
Fold 3 IBS: 0.19078575336790274
Fold 4 IBS: 0.19733338482496118
Fold 5 IBS: 0.1785081121582588
[I 2024-04-22 09:28:30,055] Trial 41 finished with value: 0.19468420328007555 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 470, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7318083142370735, 'min_weight_fraction_leaf': 0.06567312882813131}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21532149949188067
Fold 2 IBS: 0.1847817766100537
Fold 3 IBS: 0.18879463768311291
Fold 4 IBS: 0.19584692384132116
Fold 5 IBS: 0.17539535562149766
[I 2024-04-22 09:28:33,573] Trial 42 finished with value: 0.19202803864957324 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 443, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8078708827436648, 'min_weight_fraction_leaf': 0.0507620305497474}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21471296520718855
Fold 2 IBS: 0.19373402376691015
Fold 3 IBS: 0.1935782510317697
Fold 4 IBS: 0.19816815937172588
Fold 5 IBS: 0.18130190427253323
[I 2024-04-22 09:28:36,950] Trial 43 finished with value: 0.1962990607300255 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 437, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8055193729946044, 'min_weight_fraction_leaf': 0.08265746982147082}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.22368717006762112
Fold 2 IBS: 0.20588683903754684
Fold 3 IBS: 0.19891768749780012
Fold 4 IBS: 0.20962858279474328
Fold 5 IBS: 0.1937212074562581
[I 2024-04-22 09:28:39,831] Trial 44 finished with value: 0.20636829737079393 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 292, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7663562356315471, 'min_weight_fraction_leaf': 0.16789080732305503}. Best is trial 34 with value: 0.1915510180929927.

Fold 1 IBS: 0.22018361682359297
Fold 2 IBS: 0.19767576801393197
Fold 3 IBS: 0.19421270363305465
Fold 4 IBS: 0.20406059613721392
Fold 5 IBS: 0.1854331539519078
[I 2024-04-22 09:28:43,976] Trial 45 finished with value: 0.20031316771194024 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 477, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8420791678401572, 'min_weight_fraction_leaf': 0.1114478053387663}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.22677495195617972
Fold 2 IBS: 0.20938982706068335
Fold 3 IBS: 0.20301008325030304
Fold 4 IBS: 0.21538736174154596
Fold 5 IBS: 0.2016448459853074
[I 2024-04-22 09:28:47,512] Trial 46 finished with value: 0.21124141399880392 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 432, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9457056327934814, 'min_weight_fraction_leaf': 0.062092086072191535}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.22930830715400474
Fold 2 IBS: 0.21438051208781905
Fold 3 IBS: 0.20096996720018
Fold 4 IBS: 0.21969610541253728
Fold 5 IBS: 0.20049850908169184
[I 2024-04-22 09:28:50,146] Trial 47 finished with value: 0.21297068018724657 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 353, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8736971337878316, 'min_weight_fraction_leaf': 0.026438797227417946}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.213913284691646
Fold 2 IBS: 0.19365644684493624
Fold 3 IBS: 0.19264144608983128
Fold 4 IBS: 0.1978352759197991
Fold 5 IBS: 0.1792186928752932
[I 2024-04-22 09:28:54,394] Trial 48 finished with value: 0.19545302928430117 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 411, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7979948724878182, 'min_weight_fraction_leaf': 0.08705758256253036}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.23833976091790518
Fold 2 IBS: 0.21548114767509935
Fold 3 IBS: 0.2019224001063648
Fold 4 IBS: 0.22951033126413029
Fold 5 IBS: 0.2066617134943696
[I 2024-04-22 09:28:57,118] Trial 49 finished with value: 0.21838307069157384 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 332, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.944869727275161, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.2248852208588708
Fold 2 IBS: 0.2086945344469891
Fold 3 IBS: 0.19533980848254817
Fold 4 IBS: 0.2116409132896753
Fold 5 IBS: 0.19616008958660672
[I 2024-04-22 09:29:00,640] Trial 50 finished with value: 0.20734411333293803 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 482, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5323261217237781, 'min_weight_fraction_leaf': 0.1346406423395477}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.2139844395487544
Fold 2 IBS: 0.18914728968054922
Fold 3 IBS: 0.18993424334874043
Fold 4 IBS: 0.19861945136516718
Fold 5 IBS: 0.17532292501761673
[I 2024-04-22 09:29:04,010] Trial 51 finished with value: 0.19340166979216558 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 448, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6952532733159762, 'min_weight_fraction_leaf': 0.05105168315138192}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21359431074388344
Fold 2 IBS: 0.18845827623129896
Fold 3 IBS: 0.18920811875796045
Fold 4 IBS: 0.19741430133274535
Fold 5 IBS: 0.17472384859961296
[I 2024-04-22 09:29:07,428] Trial 52 finished with value: 0.19267977113310025 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 449, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6895352885746311, 'min_weight_fraction_leaf': 0.05243800385790333}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.2116998447565635
Fold 2 IBS: 0.18628912985639196
Fold 3 IBS: 0.18838500488320775
Fold 4 IBS: 0.19561139573019
Fold 5 IBS: 0.17448408339296287
[I 2024-04-22 09:29:10,781] Trial 53 finished with value: 0.1912938917238632 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 445, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7530104333187604, 'min_weight_fraction_leaf': 0.04825576822079568}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.21465186773648143
Fold 2 IBS: 0.18855005015058893
Fold 3 IBS: 0.18511049876087637
Fold 4 IBS: 0.19705279145523985
Fold 5 IBS: 0.17274909831863947
[I 2024-04-22 09:29:14,301] Trial 54 finished with value: 0.1916228612843652 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 380, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6854242983573284, 'min_weight_fraction_leaf': 0.016297809364208576}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.22796071086903075
Fold 2 IBS: 0.20969832304654898
Fold 3 IBS: 0.20267836033689163
Fold 4 IBS: 0.21278935271450855
Fold 5 IBS: 0.20040468065389563
[I 2024-04-22 09:29:17,968] Trial 55 finished with value: 0.2107062855241751 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 377, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6628876016595922, 'min_weight_fraction_leaf': 0.01845633424767698}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.24625934471253716
Fold 2 IBS: 0.23214786228629494
Fold 3 IBS: 0.2295871449534552
Fold 4 IBS: 0.24147697769672616
Fold 5 IBS: 0.23025545386023222
[I 2024-04-22 09:29:21,747] Trial 56 finished with value: 0.23594535670184916 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 425, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6032533491002975, 'min_weight_fraction_leaf': 0.3230607190970375}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.22111769895311692
Fold 2 IBS: 0.204017488716264
Fold 3 IBS: 0.19621805096093797
Fold 4 IBS: 0.20670229645207078
Fold 5 IBS: 0.1917979613090219
[I 2024-04-22 09:29:26,345] Trial 57 finished with value: 0.20397069927828232 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 485, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7531615546706312, 'min_weight_fraction_leaf': 0.005684521692916746}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.22003274498373035
Fold 2 IBS: 0.1998660068050171
Fold 3 IBS: 0.1881698580726066
Fold 4 IBS: 0.20239036180242276
Fold 5 IBS: 0.18399424930109848
[I 2024-04-22 09:29:29,349] Trial 58 finished with value: 0.19889064419297506 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 391, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5394996653270911, 'min_weight_fraction_leaf': 0.023602592097570048}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.21789189671655823
Fold 2 IBS: 0.1830618664362058
Fold 3 IBS: 0.192172012950134
Fold 4 IBS: 0.1957675158574896
Fold 5 IBS: 0.16932510927863137
[I 2024-04-22 09:29:33,028] Trial 59 finished with value: 0.19164368024780382 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8661967641372095, 'min_weight_fraction_leaf': 0.039584340366555525}. Best is trial 53 with value: 0.1912938917238632.

Fold 1 IBS: 0.21476513837056027
Fold 2 IBS: 0.18143050987640613
Fold 3 IBS: 0.1908356407571883
Fold 4 IBS: 0.19427180424062881
Fold 5 IBS: 0.16683442835564766
[I 2024-04-22 09:29:36,677] Trial 60 finished with value: 0.18962750432008624 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 439, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8952499671372233, 'min_weight_fraction_leaf': 0.036398817545426995}. Best is trial 60 with value: 0.18962750432008624.
Fold 1 IBS: 0.21627361369698
Fold 2 IBS: 0.1817225137067132
Fold 3 IBS: 0.19073393689024337
Fold 4 IBS: 0.19494098781318964
Fold 5 IBS: 0.16750297353174665
[I 2024-04-22 09:29:40,190] Trial 61 finished with value: 0.19023480512777455 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 438, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8757721856898264, 'min_weight_fraction_leaf': 0.04046785921890601}. Best is trial 60 with value: 0.18962750432008624.
Fold 1 IBS: 0.21569547676030276
Fold 2 IBS: 0.19406435056789098
Fold 3 IBS: 0.18599781327998668
Fold 4 IBS: 0.19890833105526054
Fold 5 IBS: 0.17390689345537047
[I 2024-04-22 09:29:43,504] Trial 62 finished with value: 0.19371457302376227 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 422, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9066387670860593, 'min_weight_fraction_leaf': 0.03189756237329784}. Best is trial 60 with value: 0.18962750432008624.
Fold 1 IBS: 0.21402139447730326
Fold 2 IBS: 0.18083663656728602
Fold 3 IBS: 0.18753380129692818
Fold 4 IBS: 0.19255745305291946
Fold 5 IBS: 0.1667002799097155
[I 2024-04-22 09:29:46,512] Trial 63 finished with value: 0.1883299130608305 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 373, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8664901703822724, 'min_weight_fraction_leaf': 0.0002786019075411844}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2139897789072574
Fold 2 IBS: 0.18091332402839688
Fold 3 IBS: 0.1877363493532483
Fold 4 IBS: 0.1926457442603295
Fold 5 IBS: 0.16686510313910077
[I 2024-04-22 09:29:49,495] Trial 64 finished with value: 0.18843005993766654 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 370, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8662742964997368, 'min_weight_fraction_leaf': 0.002799383925114314}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21356453199756695
Fold 2 IBS: 0.18414337595624433
Fold 3 IBS: 0.19135848396732294
Fold 4 IBS: 0.19567506298543985
Fold 5 IBS: 0.16902410400423407
[I 2024-04-22 09:29:53,194] Trial 65 finished with value: 0.19075311178216164 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 368, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9996741200655364, 'min_weight_fraction_leaf': 0.013343672274008771}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.24654787550564836
Fold 2 IBS: 0.23215877749004982
Fold 3 IBS: 0.22951426045636053
Fold 4 IBS: 0.2415490288777898
Fold 5 IBS: 0.23029214299076572
[I 2024-04-22 09:29:56,420] Trial 66 finished with value: 0.23601241706412285 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 321, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9697511853457705, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2266323511377712
Fold 2 IBS: 0.2071535974555395
Fold 3 IBS: 0.20048051366340186
Fold 4 IBS: 0.21211123932933376
Fold 5 IBS: 0.197924092034569
[I 2024-04-22 09:29:59,758] Trial 67 finished with value: 0.20886035872412304 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 363, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8902348249567581, 'min_weight_fraction_leaf': 0.0005656859239113344}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21760444020822703
Fold 2 IBS: 0.19984684424100796
Fold 3 IBS: 0.1923024665200439
Fold 4 IBS: 0.2028177913477314
Fold 5 IBS: 0.18410276014280125
[I 2024-04-22 09:30:02,214] Trial 68 finished with value: 0.1993348604919623 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 293, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9860764994598216, 'min_weight_fraction_leaf': 0.022286815780540634}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2365591490720433
Fold 2 IBS: 0.22131703584518395
Fold 3 IBS: 0.21468130634418622
Fold 4 IBS: 0.22918783390849085
Fold 5 IBS: 0.2181320987477092
[I 2024-04-22 09:30:04,143] Trial 69 finished with value: 0.2239754847835227 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 236, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9608682699921427, 'min_weight_fraction_leaf': 0.2864016846718066}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2141001980700463
Fold 2 IBS: 0.18008333278426925
Fold 3 IBS: 0.1879725741810636
Fold 4 IBS: 0.19498909793486166
Fold 5 IBS: 0.16584373802214583
[I 2024-04-22 09:30:07,284] Trial 70 finished with value: 0.18859778819847733 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9969480236364259, 'min_weight_fraction_leaf': 0.013812205414924436}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2140966903857263
Fold 2 IBS: 0.18072561052771724
Fold 3 IBS: 0.18882252022842136
Fold 4 IBS: 0.19597566403934094
Fold 5 IBS: 0.16539717562089074
[I 2024-04-22 09:30:10,470] Trial 71 finished with value: 0.18900353216041932 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9918558396160204, 'min_weight_fraction_leaf': 0.0068952357522586456}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21603071934692913
Fold 2 IBS: 0.18199677410478105
Fold 3 IBS: 0.18857834975768964
Fold 4 IBS: 0.1931833546739912
Fold 5 IBS: 0.16659700790160611
[I 2024-04-22 09:30:13,649] Trial 72 finished with value: 0.18927724115699943 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9121256508534055, 'min_weight_fraction_leaf': 0.0005212216954084261}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21375162072413798
Fold 2 IBS: 0.18715392969930847
Fold 3 IBS: 0.19203353721517546
Fold 4 IBS: 0.19646864440812928
Fold 5 IBS: 0.17158213719923593
[I 2024-04-22 09:30:16,781] Trial 73 finished with value: 0.1921979738491974 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9980006295053775, 'min_weight_fraction_leaf': 0.0006603867898888157}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21401318872018266
Fold 2 IBS: 0.18291770353148368
Fold 3 IBS: 0.1878785582518727
Fold 4 IBS: 0.1915900349059854
Fold 5 IBS: 0.16636063217999533
[I 2024-04-22 09:30:19,459] Trial 74 finished with value: 0.18855202351790395 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 372, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9034857567027796, 'min_weight_fraction_leaf': 0.013280468186275795}. Best is trial 63 with value: 0.1883299130608305.

Fold 1 IBS: 0.21657675292627207
Fold 2 IBS: 0.18996174454319362
Fold 3 IBS: 0.18393478555155848
Fold 4 IBS: 0.19722264590644567
Fold 5 IBS: 0.17340727825186003
[I 2024-04-22 09:30:22,125] Trial 75 finished with value: 0.19222064143586598 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 391, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9086795540810024, 'min_weight_fraction_leaf': 0.03284410208925504}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21374362171322053
Fold 2 IBS: 0.1809837734102344
Fold 3 IBS: 0.1928804193379134
Fold 4 IBS: 0.19389862294434004
Fold 5 IBS: 0.16641872761123616
[I 2024-04-22 09:30:25,853] Trial 76 finished with value: 0.1895850330033889 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 417, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8605344738061455, 'min_weight_fraction_leaf': 0.0132289654357266}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2136263783710042
Fold 2 IBS: 0.1797844883476793
Fold 3 IBS: 0.19019941306366508
Fold 4 IBS: 0.19332643220320936
Fold 5 IBS: 0.16540838604898453
[I 2024-04-22 09:30:28,739] Trial 77 finished with value: 0.18846901960690848 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 340, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8553757827166253, 'min_weight_fraction_leaf': 0.01267833398506176}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21394057344768827
Fold 2 IBS: 0.18063564607564772
Fold 3 IBS: 0.19110178366055228
Fold 4 IBS: 0.1933325146794154
Fold 5 IBS: 0.165642771743641
[I 2024-04-22 09:30:31,863] Trial 78 finished with value: 0.1889306579213889 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 371, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8575353599751615, 'min_weight_fraction_leaf': 0.011808738308151196}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2126262135430542
Fold 2 IBS: 0.18696373447968684
Fold 3 IBS: 0.1916799280019377
Fold 4 IBS: 0.19683095724446073
Fold 5 IBS: 0.17241956982191808
[I 2024-04-22 09:30:34,369] Trial 79 finished with value: 0.19210408061821152 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 333, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9589922281293288, 'min_weight_fraction_leaf': 0.00023409421845237187}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2153469063453449
Fold 2 IBS: 0.18778468182940314
Fold 3 IBS: 0.1866708606567345
Fold 4 IBS: 0.19691516821506336
Fold 5 IBS: 0.17754995961266154
[I 2024-04-22 09:30:36,550] Trial 80 finished with value: 0.1928535153318415 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 275, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.2869597372530869, 'min_weight_fraction_leaf': 0.015545952867167576}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.20902792603358883
Fold 2 IBS: 0.18006042053021734
Fold 3 IBS: 0.18911702889503695
Fold 4 IBS: 0.19734675827568018
Fold 5 IBS: 0.16680814632667756
[I 2024-04-22 09:30:38,767] Trial 81 finished with value: 0.1884720560122402 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 309, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9259652503609331, 'min_weight_fraction_leaf': 0.011333713500102472}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.20965756514521555
Fold 2 IBS: 0.1814081067821129
Fold 3 IBS: 0.1896445243994355
Fold 4 IBS: 0.19634790225481819
Fold 5 IBS: 0.1667849972674436
[I 2024-04-22 09:30:41,215] Trial 82 finished with value: 0.1887686191698051 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9323699691639797, 'min_weight_fraction_leaf': 0.02308562555518695}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2153817227869837
Fold 2 IBS: 0.19064494420871675
Fold 3 IBS: 0.1928363140916346
Fold 4 IBS: 0.19848435688688135
Fold 5 IBS: 0.17685355407979692
[I 2024-04-22 09:30:43,380] Trial 83 finished with value: 0.19484017841080264 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 311, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9339793672931662, 'min_weight_fraction_leaf': 0.022004474344811363}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.24653067306998416
Fold 2 IBS: 0.23215271642663415
Fold 3 IBS: 0.23010902544257975
Fold 4 IBS: 0.24116005900490298
Fold 5 IBS: 0.23000207632521744
[I 2024-04-22 09:30:45,619] Trial 84 finished with value: 0.2359909100538637 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 342, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.1443115068222393, 'min_weight_fraction_leaf': 0.07505434810839277}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.23013207588924356
Fold 2 IBS: 0.21649686531732093
Fold 3 IBS: 0.20821441289778195
Fold 4 IBS: 0.22098308423517524
Fold 5 IBS: 0.20804654146185125
[I 2024-04-22 09:30:47,675] Trial 85 finished with value: 0.21677459596027457 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 311, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9650657834803271, 'min_weight_fraction_leaf': 0.035745447715905855}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.23776519245318667
Fold 2 IBS: 0.21599806462497675
Fold 3 IBS: 0.19854293183949293
Fold 4 IBS: 0.22768263426905036
Fold 5 IBS: 0.20526222555074036
[I 2024-04-22 09:30:50,080] Trial 86 finished with value: 0.2170502097474894 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8552680427767512, 'min_weight_fraction_leaf': 0.381622326839403}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.22498794680095857
Fold 2 IBS: 0.20871296427131997
Fold 3 IBS: 0.1986932860108566
Fold 4 IBS: 0.21342471202843274
Fold 5 IBS: 0.19611500802990536
[I 2024-04-22 09:30:52,266] Trial 87 finished with value: 0.20838678342829464 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 322, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9346631200415512, 'min_weight_fraction_leaf': 0.011829639629513685}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2162799881668905
Fold 2 IBS: 0.19232899542734697
Fold 3 IBS: 0.18648368909793978
Fold 4 IBS: 0.19899335757357461
Fold 5 IBS: 0.17300447570342775
[I 2024-04-22 09:30:55,239] Trial 88 finished with value: 0.19341810119383593 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 377, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8961097715415979, 'min_weight_fraction_leaf': 0.025293850990263902}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21685001465299827
Fold 2 IBS: 0.1961691885413081
Fold 3 IBS: 0.19377583257578665
Fold 4 IBS: 0.19986684493416645
Fold 5 IBS: 0.17774512608127138
[I 2024-04-22 09:30:57,980] Trial 89 finished with value: 0.1968814013571062 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 339, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9273501023983637, 'min_weight_fraction_leaf': 0.04735901557972175}. Best is trial 63 with value: 0.1883299130608305.

Fold 1 IBS: 0.21649654230068696
Fold 2 IBS: 0.1994536066038553
Fold 3 IBS: 0.1910443715333566
Fold 4 IBS: 0.20311940988854024
Fold 5 IBS: 0.18412454653280888
[I 2024-04-22 09:31:00,193] Trial 90 finished with value: 0.1988476953718496 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 305, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9531106840561406, 'min_weight_fraction_leaf': 0.09026278115621361}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21417020956953955
Fold 2 IBS: 0.18221070479947724
Fold 3 IBS: 0.1876123093586995
Fold 4 IBS: 0.1945453292939215
Fold 5 IBS: 0.1658337819099612
[I 2024-04-22 09:31:03,452] Trial 91 finished with value: 0.1888744669863198 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 390, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9155821930769641, 'min_weight_fraction_leaf': 0.0071593216081176705}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21334772506121008
Fold 2 IBS: 0.1816182181383867
Fold 3 IBS: 0.18952956072516672
Fold 4 IBS: 0.19750128460117958
Fold 5 IBS: 0.1685827762577281
[I 2024-04-22 09:31:06,151] Trial 92 finished with value: 0.19011591295673422 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.97798257382931, 'min_weight_fraction_leaf': 0.009783759359771677}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21517609409586363
Fold 2 IBS: 0.1821811797549699
Fold 3 IBS: 0.1870785183222405
Fold 4 IBS: 0.19102878902606021
Fold 5 IBS: 0.17067480247963093
[I 2024-04-22 09:31:08,916] Trial 93 finished with value: 0.18922787673575306 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 387, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8774391513202735, 'min_weight_fraction_leaf': 0.033797847017769014}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21137091510190062
Fold 2 IBS: 0.18839244695486237
Fold 3 IBS: 0.18742029037727956
Fold 4 IBS: 0.19491638605970943
Fold 5 IBS: 0.17114179611166253
[I 2024-04-22 09:31:11,580] Trial 94 finished with value: 0.19064836692108292 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.3830871059653363, 'min_weight_fraction_leaf': 0.02515706968561085}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2138966882370574
Fold 2 IBS: 0.1844877510679235
Fold 3 IBS: 0.19259781557758243
Fold 4 IBS: 0.1952141807236525
Fold 5 IBS: 0.16975439013355925
[I 2024-04-22 09:31:13,880] Trial 95 finished with value: 0.191190165147955 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 331, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.853090178217675, 'min_weight_fraction_leaf': 0.012155059432012595}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2278103724303231
Fold 2 IBS: 0.20998652770068607
Fold 3 IBS: 0.2016895045401415
Fold 4 IBS: 0.2145197300147786
Fold 5 IBS: 0.20079551362441908
[I 2024-04-22 09:31:16,378] Trial 96 finished with value: 0.21096032966206962 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 376, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9196471588164407, 'min_weight_fraction_leaf': 0.04764222809243661}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2129544257256905
Fold 2 IBS: 0.188757190081597
Fold 3 IBS: 0.1913596765199584
Fold 4 IBS: 0.19299294688332613
Fold 5 IBS: 0.16956267469915398
[I 2024-04-22 09:31:18,974] Trial 97 finished with value: 0.19112538278194519 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 373, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7906318813789162, 'min_weight_fraction_leaf': 0.05576114935877039}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21517779568864578
Fold 2 IBS: 0.18674501277395147
Fold 3 IBS: 0.19147087886044026
Fold 4 IBS: 0.1973182121218361
Fold 5 IBS: 0.170619113683073
[I 2024-04-22 09:31:20,965] Trial 98 finished with value: 0.19226620262558933 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 272, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8265091641061248, 'min_weight_fraction_leaf': 0.06956660551772675}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21291524232383788
Fold 2 IBS: 0.17927405181896092
Fold 3 IBS: 0.19353115438588406
Fold 4 IBS: 0.19297220466886353
Fold 5 IBS: 0.17269237403404555
[I 2024-04-22 09:31:21,767] Trial 99 finished with value: 0.1902770054463184 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 101, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.88561888536106, 'min_weight_fraction_leaf': 0.028367714803137684}. Best is trial 63 with value: 0.1883299130608305.


* Best trial for IBS:
 FrozenTrial(number=63, state=TrialState.COMPLETE, values=[0.1883299130608305], datetime_start=datetime.datetime(2024, 4, 22, 9, 29, 43, 509216), datetime_complete=datetime.datetime(2024, 4, 22, 9, 29, 46, 512185), params={'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 373, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8664901703822724, 'min_weight_fraction_leaf': 0.0002786019075411844}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=63, value=None)


* Best Score for IBS:
 0.1883299130608305

In [88]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [89]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.826
train_ibs:  0.188

#### Test

In [90]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [91]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=6, max_leaf_nodes=18,
                   max_samples=0.8161032428574773, min_samples_leaf=2,
                   min_samples_split=11,
                   min_weight_fraction_leaf=0.001106761767719347,
                   n_estimators=105, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.607

ExtraSurvivalTrees(max_depth=10, max_features=None, max_leaf_nodes=12,
                   max_samples=0.8664901703822724, min_samples_split=13,
                   min_weight_fraction_leaf=0.0002786019075411844,
                   n_estimators=373, oob_score=True, random_state=123)

IBS: 0.252

In [92]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [67]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-22 02:56:57,588] A new study created in memory with name: no-name-9f783f1b-e69e-4451-a4e0-312e861a38aa

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:57:31,250] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:57:49,205] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:58:11,618] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:58:42,147] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:58:53,167] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:58:56,200] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:59:21,799] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:59:29,823] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:59:30,786] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 03:00:35,745] Trial 9 finished with value: 0.7053891693443892 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7461240310077519
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6051502145922747
[I 2024-04-22 03:02:07,982] Trial 10 finished with value: 0.6731409344204184 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:03:46,475] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7771317829457365
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6888412017167382
[I 2024-04-22 03:05:17,946] Trial 12 finished with value: 0.6892369560938594 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:06:06,582] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:07:07,590] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:07:55,797] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:08:25,722] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:09:18,081] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:10:15,396] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:10:17,534] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:10:36,434] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-22 03:11:19,579] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7577519379844961
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6437768240343348
[I 2024-04-22 03:11:59,563] Trial 22 finished with value: 0.6634639504505081 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:12:41,934] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:13:13,697] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:13:51,808] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:14:10,603] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:15:04,895] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:15:07,724] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:15:42,121] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:15:53,252] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.647410358565737
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5
Fold 5 C-index: 0.648068669527897
[I 2024-04-22 03:16:37,091] Trial 31 finished with value: 0.6148553306063567 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:17:26,862] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:18:02,881] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:18:36,735] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6888412017167382
[I 2024-04-22 03:19:00,053] Trial 35 finished with value: 0.6720678122425536 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:19:17,102] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:19:31,482] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:19:41,194] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:19:52,866] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:20:06,937] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7422480620155039
Fold 3 C-index: 0.5255319148936171
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6330472103004292
[I 2024-04-22 03:20:50,992] Trial 41 finished with value: 0.6603814554989593 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:21:24,250] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:22:03,924] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:22:15,919] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:22:59,830] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6593625498007968
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 03:23:05,858] Trial 46 finished with value: 0.7270154738948459 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:23:14,989] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.053196394932185635, 'dropout_rate': 0.70275818612764, 'n_estimators': 311, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7367392845248242, 'min_weight_fraction_leaf': 0.36842596123645754, 'max_features': 'log2', 'min_impurity_decrease': 2.2130001167649176e-06, 'validation_fraction': 0.8419754547666245, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:23:15,163] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9854905905033491, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.8195624802251275, 'n_estimators': 8, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.32965788605028784, 'max_features': 'log2', 'min_impurity_decrease': 1.2225255641975854e-06, 'validation_fraction': 0.8455422941346799, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:23:20,425] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7928982153787437, 'learning_rate': 0.0628925305235457, 'dropout_rate': 0.9570755199206264, 'n_estimators': 410, 'criterion': 'friedman_mse', 'ccp_alpha': 6.659192684443452, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'log2', 'min_impurity_decrease': 1.743578448308132e-07, 'validation_fraction': 0.42748211202843867, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:23:46,325] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8511494628607659, 'learning_rate': 0.04091234090749085, 'dropout_rate': 0.6291546211472798, 'n_estimators': 480, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3913441236862976, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'log2', 'min_impurity_decrease': 2.274738198457575e-05, 'validation_fraction': 0.5545404177484662, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 7}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.6593625498007968
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7433460076045627
Fold 5 C-index: 0.703862660944206
[I 2024-04-22 03:24:11,786] Trial 51 finished with value: 0.6957971729128621 and parameters: {'subsample': 0.9115121046901732, 'learning_rate': 0.05845917620681425, 'dropout_rate': 0.5540004810661991, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04660345139175148, 'min_weight_fraction_leaf': 0.40812087314396844, 'max_features': 'sqrt', 'min_impurity_decrease': 7.767904466636394e-05, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:24:24,523] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9606972190963244, 'learning_rate': 0.058532095704419335, 'dropout_rate': 0.8655167247735727, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42267254326215464, 'min_weight_fraction_leaf': 0.35711614532127833, 'max_features': 'sqrt', 'min_impurity_decrease': 0.003049302929929116, 'validation_fraction': 0.985072081707868, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.6792828685258964
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6995708154506438
[I 2024-04-22 03:24:52,312] Trial 53 finished with value: 0.7166400375279826 and parameters: {'subsample': 0.924085737836479, 'learning_rate': 0.05191355349770248, 'dropout_rate': 0.5292561748188663, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.009828495801242839, 'min_weight_fraction_leaf': 0.3940618917042797, 'max_features': 'sqrt', 'min_impurity_decrease': 5.891874821169929e-05, 'validation_fraction': 0.9257611975304009, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:25:15,675] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8842518374616221, 'learning_rate': 0.04642759977764528, 'dropout_rate': 0.5787056799551111, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.8043967529855988, 'min_weight_fraction_leaf': 0.39749144390795427, 'max_features': 'sqrt', 'min_impurity_decrease': 6.674900997744521e-05, 'validation_fraction': 0.9987906743578988, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:25:25,497] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9338509253358491, 'learning_rate': 0.05026798356278357, 'dropout_rate': 0.8859792395781099, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 2.0925706859481137, 'min_weight_fraction_leaf': 0.15390921956023235, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00018865565560969203, 'validation_fraction': 0.9220343002247878, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:25:56,165] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.8543724704763108, 'learning_rate': 0.07231303541927657, 'dropout_rate': 0.534386653988483, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.3004273858397456, 'min_weight_fraction_leaf': 0.19369329911983815, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012611033221339828, 'validation_fraction': 0.6860217015765494, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7124463519313304
[I 2024-04-22 03:25:59,978] Trial 57 finished with value: 0.71352028974883 and parameters: {'subsample': 0.9087026240599475, 'learning_rate': 0.08124746006044987, 'dropout_rate': 0.997784793728882, 'n_estimators': 391, 'criterion': 'squared_error', 'ccp_alpha': 0.001956726907500393, 'min_weight_fraction_leaf': 0.410591151226506, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00033059213660683115, 'validation_fraction': 0.8063875242325604, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:26:03,419] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.8212698530092863, 'learning_rate': 0.09011651240953941, 'dropout_rate': 0.9967495872781945, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.181840851947653, 'min_weight_fraction_leaf': 0.4057697411163346, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005537548403589421, 'validation_fraction': 0.8125246339086644, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 20, 'max_depth': 5}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:26:08,402] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9193087392842657, 'learning_rate': 0.0872713586054678, 'dropout_rate': 0.9474892480356638, 'n_estimators': 380, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.3337975605954647, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00021385037088054892, 'validation_fraction': 0.7937489212794213, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:26:09,702] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.7446094350786215, 'learning_rate': 0.09733264341118891, 'dropout_rate': 0.9841116957888287, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.6816514323618716, 'min_weight_fraction_leaf': 0.21423049941460018, 'max_features': 'sqrt', 'min_impurity_decrease': 6.668735628479151e-05, 'validation_fraction': 0.7693486777346097, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 46 with value: 0.7270154738948459.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:26:18,503] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.079755577636651, 'dropout_rate': 0.9141007682217919, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.3409580267399826, 'min_weight_fraction_leaf': 0.3860962100040052, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00041666520721794905, 'validation_fraction': 0.960062895620913, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.7461240310077519
Fold 3 C-index: 0.6148936170212767
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6545064377682404
[I 2024-04-22 03:26:31,084] Trial 62 finished with value: 0.6738863298917944 and parameters: {'subsample': 0.9950153281899117, 'learning_rate': 0.08115591715872426, 'dropout_rate': 0.8285090704895912, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.46340528439350875, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.8636512797881153, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5297872340425532
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5836909871244635
[I 2024-04-22 03:26:41,556] Trial 63 finished with value: 0.5422175565840008 and parameters: {'subsample': 0.9879857181271309, 'learning_rate': 0.08167353877257796, 'dropout_rate': 0.8555425487679464, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.4732508331244123, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07017568466241592, 'validation_fraction': 0.8698220228130342, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:26:49,241] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.9998194099499076, 'learning_rate': 0.08518105894428284, 'dropout_rate': 0.9084790128000951, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.43893162961234394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0018957941321912743, 'validation_fraction': 0.6573317669908815, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:27:08,472] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.8863506781235784, 'learning_rate': 0.09077517237486941, 'dropout_rate': 0.7155053041594167, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 1.0503703250594787, 'min_weight_fraction_leaf': 0.41623993393470454, 'max_features': 'sqrt', 'min_impurity_decrease': 5.4764171179088326e-05, 'validation_fraction': 0.7243703387674565, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:27:23,009] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.9116050534419412, 'learning_rate': 0.07264703745168608, 'dropout_rate': 0.8194893498338957, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 1.5401195366715463, 'min_weight_fraction_leaf': 0.45613333197683914, 'max_features': 'sqrt', 'min_impurity_decrease': 0.013056447447707517, 'validation_fraction': 0.9169313175992941, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:27:26,955] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.2507118299802445, 'learning_rate': 0.036515998728865476, 'dropout_rate': 0.9726102863603132, 'n_estimators': 371, 'criterion': 'squared_error', 'ccp_alpha': 0.29393333981111347, 'min_weight_fraction_leaf': 0.48294812651480895, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0016007967193364127, 'validation_fraction': 0.8429859516851567, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:27:46,078] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.8371795305913793, 'learning_rate': 0.04255428671400532, 'dropout_rate': 0.633247084204052, 'n_estimators': 400, 'criterion': 'squared_error', 'ccp_alpha': 0.8386209432307415, 'min_weight_fraction_leaf': 0.43086676861494394, 'max_features': 1, 'min_impurity_decrease': 0.006343103938039445, 'validation_fraction': 0.8911962268662544, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:27:53,202] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.9464359352204211, 'learning_rate': 0.06174138905299288, 'dropout_rate': 0.9285880327607973, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.45960319442458425, 'min_weight_fraction_leaf': 0.23985000065202236, 'max_features': 'log2', 'min_impurity_decrease': 0.00030338628790529525, 'validation_fraction': 0.329118980782965, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7896995708154506
[I 2024-04-22 03:28:17,854] Trial 70 finished with value: 0.7584899292280459 and parameters: {'subsample': 0.7868009537469239, 'learning_rate': 0.06760822881110454, 'dropout_rate': 0.4501645913744281, 'n_estimators': 391, 'criterion': 'squared_error', 'ccp_alpha': 0.010068295219290181, 'min_weight_fraction_leaf': 0.31623455708072684, 'max_features': 0.1, 'min_impurity_decrease': 1.7127716189044953e-05, 'validation_fraction': 0.773508933151765, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 70 with value: 0.7584899292280459.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7553648068669528
[I 2024-04-22 03:28:42,119] Trial 71 finished with value: 0.7490850897378227 and parameters: {'subsample': 0.8731481729382106, 'learning_rate': 0.06824697098399125, 'dropout_rate': 0.44693614056417824, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.3047914794183888, 'max_features': 0.1, 'min_impurity_decrease': 3.976633059647162e-05, 'validation_fraction': 0.7895458945773391, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 70 with value: 0.7584899292280459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:29:04,794] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.7823514804378748, 'learning_rate': 0.05594196279186142, 'dropout_rate': 0.4470080666838303, 'n_estimators': 388, 'criterion': 'squared_error', 'ccp_alpha': 0.3009753821860147, 'min_weight_fraction_leaf': 0.3059540589853319, 'max_features': 0.1, 'min_impurity_decrease': 1.5867418332223817e-05, 'validation_fraction': 0.7793460995771967, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 70 with value: 0.7584899292280459.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:29:32,302] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.8663908775735847, 'learning_rate': 0.06632362371857915, 'dropout_rate': 0.5067723878896389, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.618560685045426, 'min_weight_fraction_leaf': 0.31460076590199093, 'max_features': 0.1, 'min_impurity_decrease': 8.328437416038891e-06, 'validation_fraction': 0.7008907913024036, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 7}. Best is trial 70 with value: 0.7584899292280459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:30:02,396] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.8288686373854733, 'learning_rate': 0.05998088897970471, 'dropout_rate': 0.35479137028960395, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 0.9759418026741545, 'min_weight_fraction_leaf': 0.2773249572889655, 'max_features': 0.1, 'min_impurity_decrease': 5.198140001660516e-05, 'validation_fraction': 0.7466111961316684, 'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 70 with value: 0.7584899292280459.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7510729613733905
[I 2024-04-22 03:30:18,083] Trial 75 finished with value: 0.7593045273013703 and parameters: {'subsample': 0.9197287558651637, 'learning_rate': 0.05159117661647313, 'dropout_rate': 0.5604101432191428, 'n_estimators': 350, 'criterion': 'squared_error', 'ccp_alpha': 0.008821356078039954, 'min_weight_fraction_leaf': 0.26023745967507866, 'max_features': 0.1, 'min_impurity_decrease': 9.803482393630746e-05, 'validation_fraction': 0.8247616419720114, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:30:33,815] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.90806151385064, 'learning_rate': 0.06937411702873973, 'dropout_rate': 0.5775100962015742, 'n_estimators': 352, 'criterion': 'squared_error', 'ccp_alpha': 0.3026218647170148, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 3.1759196242669716e-05, 'validation_fraction': 0.8054405672668666, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:30:45,930] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.8021858195531186, 'learning_rate': 0.052009701795490706, 'dropout_rate': 0.4930834587163687, 'n_estimators': 291, 'criterion': 'squared_error', 'ccp_alpha': 1.2997944075240355, 'min_weight_fraction_leaf': 0.25797282688791734, 'max_features': 0.1, 'min_impurity_decrease': 8.194270761449124e-05, 'validation_fraction': 0.8191017051978536, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7553648068669528
[I 2024-04-22 03:31:05,754] Trial 78 finished with value: 0.7529889918423416 and parameters: {'subsample': 0.692374586728691, 'learning_rate': 0.05690511629279836, 'dropout_rate': 0.5670668275300401, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 0.02270996969784733, 'min_weight_fraction_leaf': 0.3008453270284027, 'max_features': 0.1, 'min_impurity_decrease': 9.997537740252558e-05, 'validation_fraction': 0.634085956732461, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:31:25,520] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.7354140786592815, 'learning_rate': 0.04969314557779707, 'dropout_rate': 0.44525279135712004, 'n_estimators': 366, 'criterion': 'squared_error', 'ccp_alpha': 0.5591541411162989, 'min_weight_fraction_leaf': 0.27054049814219927, 'max_features': 0.1, 'min_impurity_decrease': 0.0001332335562751616, 'validation_fraction': 0.6322159428309632, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:31:50,002] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.6390433213205666, 'learning_rate': 0.04349582782163459, 'dropout_rate': 0.4097359359491849, 'n_estimators': 387, 'criterion': 'squared_error', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.2916012333412588, 'max_features': 0.1, 'min_impurity_decrease': 3.446222542448271e-05, 'validation_fraction': 0.658619742124138, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7339055793991416
[I 2024-04-22 03:32:04,188] Trial 81 finished with value: 0.7481542616623006 and parameters: {'subsample': 0.8900437147371856, 'learning_rate': 0.05732267025618887, 'dropout_rate': 0.5675964787359803, 'n_estimators': 338, 'criterion': 'squared_error', 'ccp_alpha': 0.02537647186946867, 'min_weight_fraction_leaf': 0.3203794260312518, 'max_features': 0.1, 'min_impurity_decrease': 0.00011928163703594395, 'validation_fraction': 0.5473179941373633, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 6}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:32:20,176] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.674646944161499, 'learning_rate': 0.06428673292745038, 'dropout_rate': 0.5603615855034783, 'n_estimators': 347, 'criterion': 'squared_error', 'ccp_alpha': 0.28819151280834227, 'min_weight_fraction_leaf': 0.30301215361806194, 'max_features': 0.1, 'min_impurity_decrease': 0.00011381045599980596, 'validation_fraction': 0.5688457919188374, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:32:32,755] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.7076615576312072, 'learning_rate': 0.056710204467247914, 'dropout_rate': 0.6033560518396526, 'n_estimators': 335, 'criterion': 'squared_error', 'ccp_alpha': 0.8202792651285943, 'min_weight_fraction_leaf': 0.31878503420088733, 'max_features': 0.1, 'min_impurity_decrease': 0.0002767446387407935, 'validation_fraction': 0.51243688588132, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 6}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:32:51,788] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.8885223542936614, 'learning_rate': 0.07000519724522539, 'dropout_rate': 0.5288642574811846, 'n_estimators': 373, 'criterion': 'squared_error', 'ccp_alpha': 0.5149081571445734, 'min_weight_fraction_leaf': 0.34755924952935247, 'max_features': 0.1, 'min_impurity_decrease': 1.6951185184740712e-05, 'validation_fraction': 0.4777741397542481, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7896995708154506
[I 2024-04-22 03:33:07,414] Trial 85 finished with value: 0.7550455930886464 and parameters: {'subsample': 0.8605990508338958, 'learning_rate': 0.052056821807615235, 'dropout_rate': 0.4591414560091507, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 0.011402478584663527, 'min_weight_fraction_leaf': 0.33201592938914204, 'max_features': 0.1, 'min_impurity_decrease': 4.500909928644848e-05, 'validation_fraction': 0.585795551959921, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:33:23,405] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.8602325771048466, 'learning_rate': 0.060666799241958703, 'dropout_rate': 0.4544018342257149, 'n_estimators': 320, 'criterion': 'squared_error', 'ccp_alpha': 0.22931497714889953, 'min_weight_fraction_leaf': 0.36106190454255527, 'max_features': 0.1, 'min_impurity_decrease': 0.0001528555634091728, 'validation_fraction': 0.5817279039264187, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 6}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:33:35,978] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.7587617437729911, 'learning_rate': 0.04761165440524907, 'dropout_rate': 0.4957903377584335, 'n_estimators': 300, 'criterion': 'squared_error', 'ccp_alpha': 1.080975311316525, 'min_weight_fraction_leaf': 0.3363100713943507, 'max_features': 0.1, 'min_impurity_decrease': 0.00046289489298800726, 'validation_fraction': 0.5377854514350624, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:33:46,547] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9306795844790319, 'learning_rate': 0.051627622421456736, 'dropout_rate': 0.4234035172725829, 'n_estimators': 252, 'criterion': 'squared_error', 'ccp_alpha': 0.7265789482493736, 'min_weight_fraction_leaf': 0.3769812431626508, 'max_features': 0.1, 'min_impurity_decrease': 4.642862113005286e-05, 'validation_fraction': 0.4739493451385479, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7510729613733905
[I 2024-04-22 03:34:00,206] Trial 89 finished with value: 0.7451295099349646 and parameters: {'subsample': 0.8391283049189849, 'learning_rate': 0.055724086293807554, 'dropout_rate': 0.6569553700677857, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.01877120542983873, 'min_weight_fraction_leaf': 0.32461639571647416, 'max_features': 0.1, 'min_impurity_decrease': 8.851047050185397e-05, 'validation_fraction': 0.6010087752598334, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:34:19,391] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.826829689860655, 'learning_rate': 0.05508607313298636, 'dropout_rate': 0.4747673828195568, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 0.46861411786043294, 'min_weight_fraction_leaf': 0.3271740396549214, 'max_features': 0.1, 'min_impurity_decrease': 9.545901155149427e-05, 'validation_fraction': 0.5913771141991949, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.6995708154506438
[I 2024-04-22 03:34:36,170] Trial 91 finished with value: 0.7237191125293256 and parameters: {'subsample': 0.9670051193547057, 'learning_rate': 0.05358528744281843, 'dropout_rate': 0.658599767424636, 'n_estimators': 393, 'criterion': 'squared_error', 'ccp_alpha': 0.037871277159682165, 'min_weight_fraction_leaf': 0.28864883630713, 'max_features': 0.1, 'min_impurity_decrease': 0.00022284757650732192, 'validation_fraction': 0.6230196429197797, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:34:47,220] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.970200161496241, 'learning_rate': 0.04507048157049061, 'dropout_rate': 0.6619274742089222, 'n_estimators': 319, 'criterion': 'squared_error', 'ccp_alpha': 0.1977251065362092, 'min_weight_fraction_leaf': 0.2997333226617717, 'max_features': 0.1, 'min_impurity_decrease': 3.110697272043209e-05, 'validation_fraction': 0.7057224083251947, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:35:00,670] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.8713442146116508, 'learning_rate': 0.056893055161794756, 'dropout_rate': 0.6240038144153928, 'n_estimators': 339, 'criterion': 'squared_error', 'ccp_alpha': 0.2020936997276668, 'min_weight_fraction_leaf': 0.27879305118961123, 'max_features': 0.1, 'min_impurity_decrease': 0.0002253362395408032, 'validation_fraction': 0.5411649201375784, 'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 7}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:35:17,266] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.846552766071321, 'learning_rate': 0.05225166033787123, 'dropout_rate': 0.5466158596699147, 'n_estimators': 343, 'criterion': 'squared_error', 'ccp_alpha': 0.5371670207357605, 'min_weight_fraction_leaf': 0.25551392419012386, 'max_features': 0.1, 'min_impurity_decrease': 1.9306777571724905e-05, 'validation_fraction': 0.612298406876781, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:35:34,428] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.7863806056473801, 'learning_rate': 0.06528678713702542, 'dropout_rate': 0.5828268476051283, 'n_estimators': 377, 'criterion': 'squared_error', 'ccp_alpha': 0.9669214947186134, 'min_weight_fraction_leaf': 0.31565449545198027, 'max_features': 0.1, 'min_impurity_decrease': 9.721858189938487e-05, 'validation_fraction': 0.6404170541911562, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 6}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7680851063829788
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7167381974248928
[I 2024-04-22 03:35:53,221] Trial 96 finished with value: 0.7361464780146243 and parameters: {'subsample': 0.8988051132134279, 'learning_rate': 0.06223070527189957, 'dropout_rate': 0.5156283651894482, 'n_estimators': 355, 'criterion': 'squared_error', 'ccp_alpha': 0.03101134846799354, 'min_weight_fraction_leaf': 0.34626128365000786, 'max_features': 0.1, 'min_impurity_decrease': 1.3094627017216677e-05, 'validation_fraction': 0.6632572619204413, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:36:00,971] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8930015289701463, 'learning_rate': 0.06902066318585262, 'dropout_rate': 0.6637119170834406, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5827663286593292, 'min_weight_fraction_leaf': 0.34069712252087353, 'max_features': 0.1, 'min_impurity_decrease': 1.0966163456816475e-05, 'validation_fraction': 0.6202090272853855, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:36:11,471] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8120824030153192, 'learning_rate': 0.06065076232609097, 'dropout_rate': 0.750396388680249, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.2855531941206882, 'max_features': 0.1, 'min_impurity_decrease': 6.3587125691091546e-06, 'validation_fraction': 0.565884480208947, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 3}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-22 03:36:27,003] A new study created in memory with name: no-name-db9c5829-a923-43fa-ba48-d5031864e344

Fold 5 C-index: 0.5
[I 2024-04-22 03:36:26,991] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.9759866968226103, 'learning_rate': 0.06186324982491159, 'dropout_rate': 0.38086979950007127, 'n_estimators': 296, 'criterion': 'squared_error', 'ccp_alpha': 1.2268388380947401, 'min_weight_fraction_leaf': 0.32648395112982853, 'max_features': 0.1, 'min_impurity_decrease': 4.1512935010412314e-05, 'validation_fraction': 0.669722021056952, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.


* Best trial for C-index:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.7593045273013703], datetime_start=datetime.datetime(2024, 4, 22, 3, 30, 2, 403451), datetime_complete=datetime.datetime(2024, 4, 22, 3, 30, 18, 82641), params={'subsample': 0.9197287558651637, 'learning_rate': 0.05159117661647313, 'dropout_rate': 0.5604101432191428, 'n_estimators': 350, 'criterion': 'squared_error', 'ccp_alpha': 0.008821356078039954, 'min_weight_fraction_leaf': 0.26023745967507866, 'max_features': 0.1, 'min_impurity_decrease': 9.803482393630746e-05, 'validation_fraction': 0.8247616419720114, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 4}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for C-index:
 0.7593045273013703

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:36:40,971] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:36:49,787] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:36:57,622] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 03:37:09,211] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:37:14,557] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:37:15,797] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:37:28,123] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:37:31,813] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:37:32,255] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24608005079919942
Fold 2 IBS: 0.23042815803611094
Fold 3 IBS: 0.22863801065607092
Fold 4 IBS: 0.24084051984701824
Fold 5 IBS: 0.22855540564358753
[I 2024-04-22 03:38:05,312] Trial 9 finished with value: 0.2349084289963974 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.23166000859087926
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164907810183034
Fold 5 IBS: 0.2291762528827903
[I 2024-04-22 03:38:55,743] Trial 10 finished with value: 0.23563424132764627 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 03:39:51,130] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24715489611868932
Fold 2 IBS: 0.23185086387290396
Fold 3 IBS: 0.2289550691998775
Fold 4 IBS: 0.24186707989824685
Fold 5 IBS: 0.2293129447586724
[I 2024-04-22 03:40:37,800] Trial 12 finished with value: 0.23582817076967802 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:41:00,912] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:41:40,748] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:42:15,875] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:42:35,320] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:43:21,775] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:43:45,135] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:43:50,023] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:44:33,620] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24710981631467982
Fold 2 IBS: 0.23198582071341375
Fold 3 IBS: 0.2289216878375815
Fold 4 IBS: 0.2418944853641206
Fold 5 IBS: 0.2292311905787679
[I 2024-04-22 03:45:20,763] Trial 21 finished with value: 0.2358286001617127 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.2460949705832435
Fold 2 IBS: 0.23011947144053765
Fold 3 IBS: 0.22852853905222809

Fold 4 IBS: 0.24075460977388422
Fold 5 IBS: 0.22861261428074
[I 2024-04-22 03:46:13,070] Trial 22 finished with value: 0.23482204102612672 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:46:56,155] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:47:23,835] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:47:48,673] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:48:28,008] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:48:31,927] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 03:48:45,218] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:49:19,751] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:49:35,275] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24695000891576355
Fold 2 IBS: 0.23168626242435933
Fold 3 IBS: 0.22889748884171018
Fold 4 IBS: 0.24165979501668006
Fold 5 IBS: 0.22912802638333987
[I 2024-04-22 03:50:19,718] Trial 31 finished with value: 0.2356643163163706 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24623846601283667
Fold 2 IBS: 0.23034600631535648
Fold 3 IBS: 0.22852247093857828
Fold 4 IBS: 0.24075522979606004
Fold 5 IBS: 0.22871472601162812
[I 2024-04-22 03:51:04,061] Trial 32 finished with value: 0.23491537981489188 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:51:37,221] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:52:12,947] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 03:52:20,567] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:53:08,048] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:53:09,362] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 03:53:32,315] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:54:01,138] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:54:29,701] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.2466243968963398
Fold 2 IBS: 0.230928831475849
Fold 3 IBS: 0.22863585294540403
Fold 4 IBS: 0.24117285713517794
Fold 5 IBS: 0.22893530922896765
[I 2024-04-22 03:55:12,960] Trial 41 finished with value: 0.23525944953634767 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24629176115681264
Fold 2 IBS: 0.23044441839041935
Fold 3 IBS: 0.22846692796424145
Fold 4 IBS: 0.2408165395500078
Fold 5 IBS: 0.22873017992338907
[I 2024-04-22 03:55:59,849] Trial 42 finished with value: 0.23494996539697408 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:56:52,126] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:57:28,656] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24690838091318074
Fold 2 IBS: 0.231606265379147
Fold 3 IBS: 0.22862607626808185
Fold 4 IBS: 0.24158411302700467
Fold 5 IBS: 0.22903582211104476
[I 2024-04-22 03:58:05,449] Trial 45 finished with value: 0.2355521315396918 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:58:39,493] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:58:53,559] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:58:53,801] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 03:59:02,107] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:59:43,188] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24692974063860446
Fold 2 IBS: 0.23163323773848501
Fold 3 IBS: 0.2286226342984277
Fold 4 IBS: 0.24159022036393826
Fold 5 IBS: 0.22903704159821506
[I 2024-04-22 04:00:16,591] Trial 51 finished with value: 0.23556257492753413 and parameters: {'subsample': 0.8432391250804372, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.42932457769018856, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.012243529086999924, 'min_weight_fraction_leaf': 0.13427213537405694, 'max_features': 0.1, 'min_impurity_decrease': 7.107322942000855e-07, 'validation_fraction': 0.7779173644820415, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:00:59,330] Trial 52 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8647416200425169, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.27204051720793454, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.32951036616207574, 'min_weight_fraction_leaf': 0.0696136715803943, 'max_features': 0.1, 'min_impurity_decrease': 1.0411636207736935e-06, 'validation_fraction': 0.6649885450408526, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.2464290885826847
Fold 2 IBS: 0.23073960203048824
Fold 3 IBS: 0.2279244913585667
Fold 4 IBS: 0.2408200570354747
Fold 5 IBS: 0.22834887416862718
[I 2024-04-22 04:01:32,579] Trial 53 finished with value: 0.2348524226351683 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.35255575108470655, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.15399525160080688, 'max_features': 0.1, 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9519356083737385, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 04:02:11,641] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9637771314277555, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18483741622154692, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.16826656130652193, 'max_features': 0.1, 'min_impurity_decrease': 1.891916944791205e-07, 'validation_fraction': 0.9592695072789675, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 04:02:45,700] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.918589848048704, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.1366452847323028, 'n_estimators': 388, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.18967222528443176, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 18}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:03:21,802] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7513175598857118, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.35760497570906596, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.29279606045526263, 'max_features': 'auto', 'min_impurity_decrease': 1.1427991588661997e-07, 'validation_fraction': 0.9992935111116187, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:03:54,101] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9629672876565945, 'learning_rate': 0.03044321993695316, 'dropout_rate': 0.2654836627375681, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.3309371032482379, 'max_features': 0.1, 'min_impurity_decrease': 4.889527309942819e-07, 'validation_fraction': 0.8335980560573747, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:04:42,513] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9051869988846165, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.2230573971097521, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.46721256406858613, 'min_weight_fraction_leaf': 0.24217068500219807, 'max_features': 1, 'min_impurity_decrease': 3.3273145847446367e-06, 'validation_fraction': 0.9559266299158219, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:05:23,627] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.019139926132660745, 'dropout_rate': 0.3062756368166816, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.21472425517002308, 'max_features': 'auto', 'min_impurity_decrease': 3.097931869672697e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:05:43,097] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7996511669090498, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.47747471244727363, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2543538004837033, 'min_weight_fraction_leaf': 0.10444758350906072, 'max_features': 'log2', 'min_impurity_decrease': 1.4854430366731937e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 14}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 04:06:12,043] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8595582024746382, 'learning_rate': 0.009662456499934472, 'dropout_rate': 0.4098250163413181, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.2074917467600883, 'min_weight_fraction_leaf': 0.15724667461688366, 'max_features': 0.1, 'min_impurity_decrease': 7.257266102562462e-07, 'validation_fraction': 0.9258995897425243, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24682210218858872
Fold 2 IBS: 0.2313482899879881
Fold 3 IBS: 0.2284490764743384
Fold 4 IBS: 0.24135605392900966
Fold 5 IBS: 0.22883648614819466
[I 2024-04-22 04:06:37,241] Trial 62 finished with value: 0.2353624017456239 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.01537203137740326, 'dropout_rate': 0.5939902455485113, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.006733098283166955, 'max_features': 0.1, 'min_impurity_decrease': 1.7338007602824288e-07, 'validation_fraction': 0.7998452500875314, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:07:04,835] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9881778214681738, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.505857528523121, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.012712121434543151, 'max_features': 0.1, 'min_impurity_decrease': 1.7159806179406314e-07, 'validation_fraction': 0.8999002791146725, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24645999930951334
Fold 2 IBS: 0.23079036542305653
Fold 3 IBS: 0.22815699680939372
Fold 4 IBS: 0.24117712757037893
Fold 5 IBS: 0.22868044791806658
[I 2024-04-22 04:07:30,107] Trial 64 finished with value: 0.23505298740608183 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.04209806464905699, 'dropout_rate': 0.6515053075848445, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.04245308337653099, 'min_weight_fraction_leaf': 0.044350095557314374, 'max_features': 0.1, 'min_impurity_decrease': 4.491377932515504e-07, 'validation_fraction': 0.9610335014089881, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-22 04:07:54,276] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9388732674648854, 'learning_rate': 0.04244875829612528, 'dropout_rate': 0.6822179842512692, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 1.1144766988816432, 'min_weight_fraction_leaf': 0.08731759636169496, 'max_features': 'auto', 'min_impurity_decrease': 4.028739847312721e-07, 'validation_fraction': 0.9616704158537814, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:08:21,903] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8952643616873973, 'learning_rate': 0.05359198006915804, 'dropout_rate': 0.6509686174553241, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.713342732410399, 'min_weight_fraction_leaf': 0.037327349410482574, 'max_features': 'auto', 'min_impurity_decrease': 2.2946753237767036e-06, 'validation_fraction': 0.8670144195682054, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:08:37,060] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9559398584951578, 'learning_rate': 0.001312025546225645, 'dropout_rate': 0.8046607423826502, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.04508345598854374, 'max_features': 'sqrt', 'min_impurity_decrease': 5.750753876092619e-06, 'validation_fraction': 0.9116952163053982, 'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:09:17,545] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9243406312878238, 'learning_rate': 0.058088208137035593, 'dropout_rate': 0.19698157671040928, 'n_estimators': 426, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997767788709036, 'min_weight_fraction_leaf': 0.2604144011776313, 'max_features': 0.1, 'min_impurity_decrease': 1.1827988873109092e-06, 'validation_fraction': 0.9998742352056981, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:09:50,160] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8260339189937393, 'learning_rate': 0.08587936719454789, 'dropout_rate': 0.23558185081536823, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.2330662826063859, 'max_features': 'auto', 'min_impurity_decrease': 6.006710681053735e-05, 'validation_fraction': 0.9704861722747272, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:10:17,918] Trial 70 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.027514255341309163, 'dropout_rate': 0.5905404972480945, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.12615077879430528, 'max_features': None, 'min_impurity_decrease': 5.222228681732963e-07, 'validation_fraction': 0.8455426922265927, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.2468431050789432
Fold 2 IBS: 0.23139350861857055
Fold 3 IBS: 0.2284780982446439
Fold 4 IBS: 0.24138770464805553
Fold 5 IBS: 0.22885953849816865
[I 2024-04-22 04:10:42,530] Trial 71 finished with value: 0.23539239101767637 and parameters: {'subsample': 0.9998892193300933, 'learning_rate': 0.015392294492197107, 'dropout_rate': 0.5823696005202688, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.06445986479432256, 'max_features': 0.1, 'min_impurity_decrease': 2.7569586568543097e-07, 'validation_fraction': 0.9287673956828812, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24699749437820576
Fold 2 IBS: 0.23165218847082278
Fold 3 IBS: 0.22865219650261898
Fold 4 IBS: 0.24159606345259071
Fold 5 IBS: 0.229036727569616
[I 2024-04-22 04:11:01,259] Trial 72 finished with value: 0.2355869340747708 and parameters: {'subsample': 0.9695012667210274, 'learning_rate': 0.009880743240604978, 'dropout_rate': 0.7234474037831898, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.004793672160551997, 'min_weight_fraction_leaf': 0.0006344109437541792, 'max_features': 0.1, 'min_impurity_decrease': 1.0311442565316877e-07, 'validation_fraction': 0.7967022266516048, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 04:11:05,069] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9999520023767101, 'learning_rate': 0.022493973992953744, 'dropout_rate': 0.6438577663377525, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.019994854935207237, 'max_features': 0.1, 'min_impurity_decrease': 1.5918517921458393e-07, 'validation_fraction': 0.9395376003114264, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:11:57,883] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9393704884452911, 'learning_rate': 0.005281947478642466, 'dropout_rate': 0.12943958636926897, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.3686824833949447, 'min_weight_fraction_leaf': 0.053815083102964845, 'max_features': 0.1, 'min_impurity_decrease': 2.539937499874641e-07, 'validation_fraction': 0.8777634783146918, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:12:20,063] Trial 75 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8731051806028837, 'learning_rate': 0.019330707767774714, 'dropout_rate': 0.6082487085608025, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 1.3248769325723149, 'min_weight_fraction_leaf': 0.2959887591923328, 'max_features': 'auto', 'min_impurity_decrease': 4.7652746848926277e-07, 'validation_fraction': 0.9771406523907726, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:12:46,976] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9712736025274701, 'learning_rate': 0.01258123741877497, 'dropout_rate': 0.5558253337837517, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.2663511381103464, 'max_features': 0.1, 'min_impurity_decrease': 1.131669404349593e-05, 'validation_fraction': 0.687477001647036, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 04:13:24,633] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9040601608260395, 'learning_rate': 0.008028762030775153, 'dropout_rate': 0.1661055390191164, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.5920167940309409, 'min_weight_fraction_leaf': 0.20760648939509768, 'max_features': 1, 'min_impurity_decrease': 1.2858411523836384e-06, 'validation_fraction': 0.7519570151291436, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:13:41,094] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9412481314247185, 'learning_rate': 0.003888190949209832, 'dropout_rate': 0.6251655088821374, 'n_estimators': 382, 'criterion': 'squared_error', 'ccp_alpha': 0.9892893740980914, 'min_weight_fraction_leaf': 0.033793930334568206, 'max_features': 'auto', 'min_impurity_decrease': 0.0002118263312796081, 'validation_fraction': 0.6158958959698865, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927107
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:14:19,892] Trial 79 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.5431112126281161, 'learning_rate': 0.030593840345293603, 'dropout_rate': 0.28940296100102497, 'n_estimators': 452, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28778903589913546, 'min_weight_fraction_leaf': 0.17610538826721606, 'max_features': 'auto', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.8300457615159439, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:14:36,334] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9189279907539, 'learning_rate': 0.016793358093448018, 'dropout_rate': 0.3388723042222102, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.3543882746154796, 'max_features': 'log2', 'min_impurity_decrease': 1.4631830515812678e-07, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24681345447018593
Fold 2 IBS: 0.2313872832399048
Fold 3 IBS: 0.22845032192169396
Fold 4 IBS: 0.24137509385879735
Fold 5 IBS: 0.22882473993565516
[I 2024-04-22 04:15:02,599] Trial 81 finished with value: 0.23537017868524743 and parameters: {'subsample': 0.9965114629683737, 'learning_rate': 0.015327246809846502, 'dropout_rate': 0.5609953054435709, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.06929483396903219, 'max_features': 0.1, 'min_impurity_decrease': 2.622082619894755e-07, 'validation_fraction': 0.9164477820882341, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:15:31,263] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9805053749629268, 'learning_rate': 0.010886411260799844, 'dropout_rate': 0.5683084429638622, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.2901659063159545, 'min_weight_fraction_leaf': 0.00019462069720194673, 'max_features': 0.1, 'min_impurity_decrease': 6.285047241123457e-07, 'validation_fraction': 0.9118209657927552, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:16:03,078] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6438413298708685, 'learning_rate': 0.02471644851386544, 'dropout_rate': 0.5202192733555178, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.6302736024968735, 'min_weight_fraction_leaf': 0.08484719071542221, 'max_features': 0.1, 'min_impurity_decrease': 3.0720666780466816e-07, 'validation_fraction': 0.8846072833938841, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 15}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898042024574092
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293926775107472
[I 2024-04-22 04:16:19,372] Trial 84 finished with value: 0.23592697084005448 and parameters: {'subsample': 0.411624430892823, 'learning_rate': 0.014346557003820789, 'dropout_rate': 0.6984815756762216, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.214835028703023, 'min_weight_fraction_leaf': 0.0519525894881867, 'max_features': 0.1, 'min_impurity_decrease': 3.906058893074947e-07, 'validation_fraction': 0.939166800936518, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.2453657442225769
Fold 2 IBS: 0.22798116508039243
Fold 3 IBS: 0.22690390767406562
Fold 4 IBS: 0.2389258130051501
Fold 5 IBS: 0.22739074180659022
[I 2024-04-22 04:16:59,949] Trial 85 finished with value: 0.23331347435775504 and parameters: {'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:17:39,944] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8908016266221349, 'learning_rate': 0.020782252048892114, 'dropout_rate': 0.20248417164561996, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 0.8648012196087868, 'min_weight_fraction_leaf': 0.025928909209021245, 'max_features': 'auto', 'min_impurity_decrease': 9.529217204035409e-07, 'validation_fraction': 0.9780308436827329, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:17:54,748] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.953409887733455, 'learning_rate': 0.007217130157082901, 'dropout_rate': 0.2326599983541061, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.4347343354489257, 'min_weight_fraction_leaf': 0.25406866786837123, 'max_features': 'auto', 'min_impurity_decrease': 2.642399797861587e-06, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:18:40,155] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7762725560789899, 'learning_rate': 0.0030671608519508686, 'dropout_rate': 0.2500967923284591, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.2742275973203492, 'min_weight_fraction_leaf': 0.27772784044341225, 'max_features': 'auto', 'min_impurity_decrease': 0.0011701047770450368, 'validation_fraction': 0.9552938036430088, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:19:22,401] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9240076064991638, 'learning_rate': 0.036372907201929795, 'dropout_rate': 0.16604269499086277, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.6288732373244443, 'min_weight_fraction_leaf': 0.1967537060613447, 'max_features': 'auto', 'min_impurity_decrease': 1.8368798466082297e-06, 'validation_fraction': 0.8456629128553931, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:20:05,109] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3053150575440778, 'learning_rate': 0.00911659038630352, 'dropout_rate': 0.38100622127956474, 'n_estimators': 498, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.22333957383529762, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8011498496617241, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 14}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24645393673926166
Fold 2 IBS: 0.23072722650379557
Fold 3 IBS: 0.22798170496299774
Fold 4 IBS: 0.240998787435527
Fold 5 IBS: 0.22853988200436828
[I 2024-04-22 04:20:47,184] Trial 91 finished with value: 0.23494030752919004 and parameters: {'subsample': 0.9762027146117168, 'learning_rate': 0.01642165444052923, 'dropout_rate': 0.2673714840258141, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.012296492316215053, 'max_features': 0.1, 'min_impurity_decrease': 2.2249919821233818e-07, 'validation_fraction': 0.901410266511097, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:21:29,106] Trial 92 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.970200161496241, 'learning_rate': 0.012238074680872561, 'dropout_rate': 0.2583752131981347, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.20177590902847325, 'min_weight_fraction_leaf': 0.022776576304230935, 'max_features': 'auto', 'min_impurity_decrease': 2.0262506829884978e-07, 'validation_fraction': 0.9761923045843292, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:22:12,538] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9444060832329966, 'learning_rate': 0.017856303491279684, 'dropout_rate': 0.30303355573944185, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.4632988607005709, 'min_weight_fraction_leaf': 0.011908761872398903, 'max_features': 'auto', 'min_impurity_decrease': 6.055732421263935e-07, 'validation_fraction': 0.864284511598723, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:22:47,915] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8821760782294449, 'learning_rate': 0.005785552173633914, 'dropout_rate': 0.28058975756978766, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 0.8506324992317083, 'min_weight_fraction_leaf': 0.04622694094641695, 'max_features': None, 'min_impurity_decrease': 1.3402986834437386e-07, 'validation_fraction': 0.8985100287316004, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 18}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 04:23:30,218] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9761707513926794, 'learning_rate': 0.019567902784876703, 'dropout_rate': 0.3201948574529592, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 1.0386964570043107, 'min_weight_fraction_leaf': 0.2390619554248597, 'max_features': 0.1, 'min_impurity_decrease': 7.882358999259736e-07, 'validation_fraction': 0.9417888137501867, 'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.246384587613419
Fold 2 IBS: 0.22951287202587697
Fold 3 IBS: 0.22811619002717504
Fold 4 IBS: 0.2407635260296621
Fold 5 IBS: 0.22839097135136704
[I 2024-04-22 04:24:05,285] Trial 96 finished with value: 0.23463362940950003 and parameters: {'subsample': 0.9088634226642077, 'learning_rate': 0.01055205151962401, 'dropout_rate': 0.22112152895475082, 'n_estimators': 396, 'criterion': 'squared_error', 'ccp_alpha': 0.03063069674161246, 'min_weight_fraction_leaf': 0.09708890262536518, 'max_features': 'auto', 'min_impurity_decrease': 3.7395479538673736e-07, 'validation_fraction': 0.992337544991608, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:24:40,434] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8201377508003859, 'learning_rate': 0.010954886262406833, 'dropout_rate': 0.18321575541765564, 'n_estimators': 399, 'criterion': 'squared_error', 'ccp_alpha': 1.603167122698403, 'min_weight_fraction_leaf': 0.06013220413302209, 'max_features': 'auto', 'min_impurity_decrease': 3.972456306049239e-07, 'validation_fraction': 0.9976245698846969, 'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:25:08,560] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8505038223267275, 'learning_rate': 0.013402809510359784, 'dropout_rate': 0.21292319653614647, 'n_estimators': 354, 'criterion': 'squared_error', 'ccp_alpha': 0.25666428673598457, 'min_weight_fraction_leaf': 0.1129024126904408, 'max_features': 'auto', 'min_impurity_decrease': 3.4044321201945537e-06, 'validation_fraction': 0.9625603744870045, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 04:25:50,010] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9084360842440081, 'learning_rate': 0.06808689488183181, 'dropout_rate': 0.25443633448028735, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.5386043790221791, 'min_weight_fraction_leaf': 0.03403879613376609, 'max_features': 'auto', 'min_impurity_decrease': 8.69596280226011e-07, 'validation_fraction': 0.9221483446288596, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 85 with value: 0.23331347435775504.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.23331347435775504], datetime_start=datetime.datetime(2024, 4, 22, 4, 16, 19, 377434), datetime_complete=datetime.datetime(2024, 4, 22, 4, 16, 59, 948312), params={'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=85, value=None)


* Best Score for IBS:
 0.23331347435775504

In [68]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [69]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.759
train_ibs:  0.233

#### Test

In [70]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [71]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.008821356078039954,
                                 criterion='squared_error',
                                 dropout_rate=0.5604101432191428,
                                 learning_rate=0.05159117661647313, max_depth=4,
                                 max_features=0.1, max_leaf_nodes=18,
                                 min_impurity_decrease=9.803482393630746e-05,
                                 min_samples_leaf=7, min_samples_split=8,
                                 min_weight_fraction_leaf=0.26023745967507866,
                                 n_estimators=350, random_state=123,
                                 subsample=0.9197287558651637,
                                 validation_fraction=0.8247616419720114)

C-index score: 0.586

GradientBoostingSurvivalAnalysis(ccp_alpha=0.01138981446692314,
                                 criterion='squared_error',
                                 dropout_rate=0.2479619862207481,
                                 learning_rate=0.02022975259096714, max_depth=8,
                                 max_features='auto', max_leaf_nodes=20,
                                 min_impurity_decrease=9.61920586779085e-07,
                                 min_samples_leaf=18, min_samples_split=14,
                                 min_weight_fraction_leaf=0.026767353450782638,
                                 n_estimators=438, random_state=123,
                                 subsample=0.9481727373988897,
                                 validation_fraction=0.973754058089352)

IBS: 0.228

In [72]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [73]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [74]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-22 04:26:01,694] A new study created in memory with name: no-name-62a2374e-892f-4ac4-bb03-f70c39255f9c

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:26:02,446] Trial 0 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6249682148055231.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6566523605150214
[I 2024-04-22 04:26:08,267] Trial 1 finished with value: 0.6241098457068107 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6249682148055231.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:26:09,544] Trial 2 finished with value: 0.6290789721738743 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6290789721738743.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:26:11,196] Trial 3 finished with value: 0.6321935102194108 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.6321935102194108.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:26:14,217] Trial 4 finished with value: 0.6337580845111042 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.6337580845111042.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-22 04:26:17,312] Trial 5 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.6337580845111042.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.648068669527897
[I 2024-04-22 04:26:18,721] Trial 6 finished with value: 0.6223931075093858 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.6337580845111042.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-22 04:26:19,010] Trial 7 finished with value: 0.6289447028736863 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.6337580845111042.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:26:20,588] Trial 8 finished with value: 0.6265038648777369 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.6337580845111042.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6566523605150214
[I 2024-04-22 04:26:24,896] Trial 9 finished with value: 0.6256454957790245 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.6337580845111042.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:26:27,781] Trial 10 finished with value: 0.6383103598039064 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.6383103598039064.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 04:26:31,100] Trial 11 finished with value: 0.6546369717001154 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 04:26:34,514] Trial 12 finished with value: 0.6545137320138635 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:26:38,557] Trial 13 finished with value: 0.6284016912003729 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:26:41,519] Trial 14 finished with value: 0.6461875928957304 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:26:44,808] Trial 15 finished with value: 0.6391614236336937 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 04:26:50,284] Trial 16 finished with value: 0.6487011438421592 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:26:55,187] Trial 17 finished with value: 0.6346022669150224 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 416, 'learning_rate': 0.08639690405722114}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:26:57,250] Trial 18 finished with value: 0.6306830600216656 and parameters: {'subsample': 0.35801092912005106, 'dropout_rate': 0.33602353085084236, 'n_estimators': 256, 'learning_rate': 0.08307767561539126}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084

Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:26:57,923] Trial 19 finished with value: 0.6399834362571664 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7254192287154788, 'n_estimators': 117, 'learning_rate': 0.09614402133777997}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:27:02,783] Trial 20 finished with value: 0.6375499035301421 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 423, 'learning_rate': 0.07788582119853761}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 04:27:08,553] Trial 21 finished with value: 0.6488064889228674 and parameters: {'subsample': 0.19686631492543752, 'dropout_rate': 0.12395834975058428, 'n_estimators': 431, 'learning_rate': 0.09000255639604265}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:27:11,575] Trial 22 finished with value: 0.6446556671685272 and parameters: {'subsample': 0.18443217486865215, 'dropout_rate': 0.2970189594128161, 'n_estimators': 321, 'learning_rate': 0.09335998424883366}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:27:16,058] Trial 23 finished with value: 0.6486322822235255 and parameters: {'subsample': 0.1529963084044875, 'dropout_rate': 0.1714923229584688, 'n_estimators': 392, 'learning_rate': 0.06498100052925637}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:27:22,487] Trial 24 finished with value: 0.6391002911270414 and parameters: {'subsample': 0.30544113046891047, 'dropout_rate': 0.16550473543623023, 'n_estimators': 454, 'learning_rate': 0.0805167394906014}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:27:25,924] Trial 25 finished with value: 0.6485711497168731 and parameters: {'subsample': 0.21578783290493656, 'dropout_rate': 0.11261425324062513, 'n_estimators': 330, 'learning_rate': 0.09163056701298726}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6695278969957081
[I 2024-04-22 04:27:28,102] Trial 26 finished with value: 0.6274237903261579 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.4358710230551022, 'n_estimators': 256, 'learning_rate': 0.037893735810538676}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 04:27:30,106] Trial 27 finished with value: 0.6503200962014708 and parameters: {'subsample': 0.10030534830333891, 'dropout_rate': 0.9861686560685959, 'n_estimators': 294, 'learning_rate': 0.08000489021783491}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 04:27:32,231] Trial 28 finished with value: 0.6495959964029463 and parameters: {'subsample': 0.10146809971965022, 'dropout_rate': 0.8178252892822001, 'n_estimators': 290, 'learning_rate': 0.07770957646628725}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:27:33,807] Trial 29 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.5985349208985528, 'n_estimators': 215, 'learning_rate': 0.06046208382653473}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6695278969957081
[I 2024-04-22 04:27:35,783] Trial 30 finished with value: 0.626684953002948 and parameters: {'subsample': 0.6496340242271839, 'dropout_rate': 0.3577780272974884, 'n_estimators': 233, 'learning_rate': 0.06770814359693789}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:27:37,893] Trial 31 finished with value: 0.6486033580040459 and parameters: {'subsample': 0.10793925840929003, 'dropout_rate': 0.9925382852879747, 'n_estimators': 297, 'learning_rate': 0.07829470270101738}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:27:39,937] Trial 32 finished with value: 0.6400050552077208 and parameters: {'subsample': 0.15588315806842334, 'dropout_rate': 0.8490702762086779, 'n_estimators': 287, 'learning_rate': 0.07216031707143393}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 04:27:42,415] Trial 33 finished with value: 0.6511784653001833 and parameters: {'subsample': 0.10119572499894987, 'dropout_rate': 0.938709782637818, 'n_estimators': 335, 'learning_rate': 0.08080565390746011}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:27:44,920] Trial 34 finished with value: 0.6369125599557949 and parameters: {'subsample': 0.23419761201309758, 'dropout_rate': 0.9877201525163405, 'n_estimators': 341, 'learning_rate': 0.09351360578393325}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-22 04:27:47,863] Trial 35 finished with value: 0.6281695090752366 and parameters: {'subsample': 0.29440822025230656, 'dropout_rate': 0.9444524590574302, 'n_estimators': 386, 'learning_rate': 0.084429898902304}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:27:48,597] Trial 36 finished with value: 0.6415843670240996 and parameters: {'subsample': 0.14727924050650143, 'dropout_rate': 0.7965859837836483, 'n_estimators': 129, 'learning_rate': 0.07248979611488705}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:27:48,702] Trial 37 finished with value: 0.6508237281135079 and parameters: {'subsample': 0.23658791238378318, 'dropout_rate': 0.9226586817305168, 'n_estimators': 1, 'learning_rate': 0.059207327336158105}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745

Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:27:48,984] Trial 38 finished with value: 0.6382987793600792 and parameters: {'subsample': 0.23557094034920928, 'dropout_rate': 0.7668386839679121, 'n_estimators': 46, 'learning_rate': 0.06351044805702724}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-22 04:27:49,975] Trial 39 finished with value: 0.6297198966721359 and parameters: {'subsample': 0.3132356181950913, 'dropout_rate': 0.5267513165392328, 'n_estimators': 159, 'learning_rate': 0.05598015324329953}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:27:50,376] Trial 40 finished with value: 0.6265038648777369 and parameters: {'subsample': 0.4350887299116774, 'dropout_rate': 0.9022040110041715, 'n_estimators': 78, 'learning_rate': 0.01794138033227278}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:27:52,175] Trial 41 finished with value: 0.6444166036175221 and parameters: {'subsample': 0.13920009866686117, 'dropout_rate': 0.9370979561822335, 'n_estimators': 271, 'learning_rate': 0.07016156385148511}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-22 04:27:52,315] Trial 42 finished with value: 0.6436989614018105 and parameters: {'subsample': 0.17140272493416953, 'dropout_rate': 0.6132750054890997, 'n_estimators': 11, 'learning_rate': 0.047396896123616486}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-22 04:27:55,176] Trial 43 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.606902356803378, 'dropout_rate': 0.8855852483698572, 'n_estimators': 347, 'learning_rate': 0.08120277792367413}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:27:56,913] Trial 44 finished with value: 0.6368289608124758 and parameters: {'subsample': 0.18950061028680848, 'dropout_rate': 0.9493495600820271, 'n_estimators': 234, 'learning_rate': 0.0963689949419925}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:27:58,072] Trial 45 finished with value: 0.6453361052228869 and parameters: {'subsample': 0.13090985020029522, 'dropout_rate': 0.9960129943900056, 'n_estimators': 188, 'learning_rate': 0.089155313391396}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:28:01,199] Trial 46 finished with value: 0.6321644590130961 and parameters: {'subsample': 0.24957639163897338, 'dropout_rate': 0.8407346173348479, 'n_estimators': 367, 'learning_rate': 0.0748007405501974}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-22 04:28:04,115] Trial 47 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.7961983953812717, 'dropout_rate': 0.4755162576313925, 'n_estimators': 311, 'learning_rate': 0.05789762140502734}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:28:05,372] Trial 48 finished with value: 0.6423232043473094 and parameters: {'subsample': 0.19286527393095337, 'dropout_rate': 0.19701471782839963, 'n_estimators': 155, 'learning_rate': 0.05238884382255915}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:28:07,417] Trial 49 finished with value: 0.6298030719723988 and parameters: {'subsample': 0.3239187171565111, 'dropout_rate': 0.923913693962182, 'n_estimators': 272, 'learning_rate': 0.04235005878192231}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:28:10,896] Trial 50 finished with value: 0.6438837574377707 and parameters: {'subsample': 0.13143491025138906, 'dropout_rate': 0.7535976723443017, 'n_estimators': 393, 'learning_rate': 0.09940058921163343}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:28:12,949] Trial 51 finished with value: 0.6469554814252547 and parameters: {'subsample': 0.10948169747492852, 'dropout_rate': 0.8401417311455619, 'n_estimators': 286, 'learning_rate': 0.07672564537412481}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:28:15,533] Trial 52 finished with value: 0.6399871606021772 and parameters: {'subsample': 0.1749064915435798, 'dropout_rate': 0.8116115290471001, 'n_estimators': 327, 'learning_rate': 0.08488781688059097}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:28:18,007] Trial 53 finished with value: 0.6453076048464634 and parameters: {'subsample': 0.10859852551623499, 'dropout_rate': 0.6742623198182025, 'n_estimators': 308, 'learning_rate': 0.08152773384700819}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:28:20,756] Trial 54 finished with value: 0.6360793907315511 and parameters: {'subsample': 0.2207918666716201, 'dropout_rate': 0.8786652052066343, 'n_estimators': 360, 'learning_rate': 0.06636008872095478}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6523605150214592
[I 2024-04-22 04:28:22,194] Trial 55 finished with value: 0.6240119328818624 and parameters: {'subsample': 0.5460014539035196, 'dropout_rate': 0.9635452032497741, 'n_estimators': 240, 'learning_rate': 0.09503580650346778}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 04:28:25,354] Trial 56 finished with value: 0.6478500800123719 and parameters: {'subsample': 0.1444623192750493, 'dropout_rate': 0.296922267125389, 'n_estimators': 335, 'learning_rate': 0.0880385547236345}. Best is trial 11 with value: 0.6546369717001154.

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 04:28:27,303] Trial 57 finished with value: 0.6479844762993948 and parameters: {'subsample': 0.10148816840464371, 'dropout_rate': 0.9166121751621753, 'n_estimators': 282, 'learning_rate': 0.07586937026396535}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 04:28:34,768] Trial 58 finished with value: 0.6463407479086706 and parameters: {'subsample': 0.26259879601440506, 'dropout_rate': 0.1335365954180555, 'n_estimators': 498, 'learning_rate': 0.09225887035133493}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:28:37,232] Trial 59 finished with value: 0.6406864843692891 and parameters: {'subsample': 0.20433273544106517, 'dropout_rate': 0.20704245528611398, 'n_estimators': 253, 'learning_rate': 0.06991757866207834}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:28:38,822] Trial 60 finished with value: 0.6406280851004389 and parameters: {'subsample': 0.17456755810273322, 'dropout_rate': 0.8100419869454891, 'n_estimators': 212, 'learning_rate': 0.0784110065822148}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 04:28:44,492] Trial 61 finished with value: 0.6486395874924507 and parameters: {'subsample': 0.13226338582400193, 'dropout_rate': 0.12666752739579462, 'n_estimators': 448, 'learning_rate': 0.08735412463201261}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:28:50,381] Trial 62 finished with value: 0.6407407354500724 and parameters: {'subsample': 0.21207118757050358, 'dropout_rate': 0.2628316670327197, 'n_estimators': 481, 'learning_rate': 0.09059646264718506}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 04:28:53,133] Trial 63 finished with value: 0.6511169089504748 and parameters: {'subsample': 0.1631042774015884, 'dropout_rate': 0.14213818814606993, 'n_estimators': 299, 'learning_rate': 0.09699892365443433}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6952789699570815
[I 2024-04-22 04:28:55,979] Trial 64 finished with value: 0.6503889578201044 and parameters: {'subsample': 0.15853710931864923, 'dropout_rate': 0.15363732780273048, 'n_estimators': 306, 'learning_rate': 0.09947274580929129}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 04:28:58,924] Trial 65 finished with value: 0.6486722196226796 and parameters: {'subsample': 0.16031747566028584, 'dropout_rate': 0.15254500794647013, 'n_estimators': 312, 'learning_rate': 0.09720155136602122}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:29:02,795] Trial 66 finished with value: 0.6415917992798597 and parameters: {'subsample': 0.27682211757970554, 'dropout_rate': 0.21506694947563737, 'n_estimators': 374, 'learning_rate': 0.09972091468993854}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:29:06,882] Trial 67 finished with value: 0.6422226852713941 and parameters: {'subsample': 0.24491837796398347, 'dropout_rate': 0.16716863716781255, 'n_estimators': 350, 'learning_rate': 0.09490401293367616}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:29:10,442] Trial 68 finished with value: 0.6414717166744659 and parameters: {'subsample': 0.17246440371575278, 'dropout_rate': 0.23687261913896357, 'n_estimators': 320, 'learning_rate': 0.0267624773650322}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:29:12,862] Trial 69 finished with value: 0.6439321181998938 and parameters: {'subsample': 0.38886832089021417, 'dropout_rate': 0.10182438892486032, 'n_estimators': 264, 'learning_rate': 0.08403050744828938}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:29:17,393] Trial 70 finished with value: 0.6284016912003729 and parameters: {'subsample': 0.9847790608248583, 'dropout_rate': 0.2786883388291751, 'n_estimators': 408, 'learning_rate': 0.09213572156849137}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:29:19,424] Trial 71 finished with value: 0.6452749727162346 and parameters: {'subsample': 0.13098377437646294, 'dropout_rate': 0.9714899905465195, 'n_estimators': 295, 'learning_rate': 0.09671619070431894}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 04:29:22,178] Trial 72 finished with value: 0.6519241840492621 and parameters: {'subsample': 0.10516314573861865, 'dropout_rate': 0.15030037357665654, 'n_estimators': 297, 'learning_rate': 0.086493193389562}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 04:29:25,503] Trial 73 finished with value: 0.650236793914373 and parameters: {'subsample': 0.15183688923409344, 'dropout_rate': 0.15513913196739304, 'n_estimators': 335, 'learning_rate': 0.08976652279422788}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:29:28,294] Trial 74 finished with value: 0.6478138505239672 and parameters: {'subsample': 0.1242861669165112, 'dropout_rate': 0.18290930559198426, 'n_estimators': 303, 'learning_rate': 0.08666794440580619}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654

Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 04:29:30,751] Trial 75 finished with value: 0.6502115940399043 and parameters: {'subsample': 0.19726796751360348, 'dropout_rate': 0.1375605008259939, 'n_estimators': 278, 'learning_rate': 0.08196341047971258}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 04:29:33,670] Trial 76 finished with value: 0.6502226072195788 and parameters: {'subsample': 0.10181600487014592, 'dropout_rate': 0.3852492115634457, 'n_estimators': 322, 'learning_rate': 0.09323585336004614}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:29:35,827] Trial 77 finished with value: 0.6478354694745215 and parameters: {'subsample': 0.2244960438075131, 'dropout_rate': 0.10440159877217844, 'n_estimators': 244, 'learning_rate': 0.09628126109398893}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:29:40,319] Trial 78 finished with value: 0.6501679322957393 and parameters: {'subsample': 0.1536410597275497, 'dropout_rate': 0.18439976776709677, 'n_estimators': 348, 'learning_rate': 0.07946261455314468}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:29:42,337] Trial 79 finished with value: 0.6431494921456841 and parameters: {'subsample': 0.18565898028204447, 'dropout_rate': 0.33365763800116394, 'n_estimators': 224, 'learning_rate': 0.09051900686079285}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6695278969957081
[I 2024-04-22 04:29:45,175] Trial 80 finished with value: 0.6274237903261579 and parameters: {'subsample': 0.45334769335248726, 'dropout_rate': 0.14030017497322128, 'n_estimators': 295, 'learning_rate': 0.007039353779474462}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 04:29:49,538] Trial 81 finished with value: 0.6485963495913419 and parameters: {'subsample': 0.15570152368400786, 'dropout_rate': 0.16445001649085195, 'n_estimators': 377, 'learning_rate': 0.08916739252971367}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 04:29:52,617] Trial 82 finished with value: 0.6487480896540172 and parameters: {'subsample': 0.13077855237496497, 'dropout_rate': 0.22243481649921315, 'n_estimators': 323, 'learning_rate': 0.08378386388736253}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:29:55,925] Trial 83 finished with value: 0.6353990796640264 and parameters: {'subsample': 0.5104385117001161, 'dropout_rate': 0.15506791319042146, 'n_estimators': 336, 'learning_rate': 0.09858795058468145}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 04:29:58,156] Trial 84 finished with value: 0.6494474134211292 and parameters: {'subsample': 0.1549434562291307, 'dropout_rate': 0.1916309874260323, 'n_estimators': 264, 'learning_rate': 0.09242476936402379}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 04:30:01,780] Trial 85 finished with value: 0.650327401470396 and parameters: {'subsample': 0.12907161079411544, 'dropout_rate': 0.1304191463181218, 'n_estimators': 355, 'learning_rate': 0.09469590297156438}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:30:05,498] Trial 86 finished with value: 0.652811731341124 and parameters: {'subsample': 0.11918286874044434, 'dropout_rate': 0.11543197286879031, 'n_estimators': 357, 'learning_rate': 0.08611904547944813}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:30:09,668] Trial 87 finished with value: 0.6393399055079376 and parameters: {'subsample': 0.578448001711966, 'dropout_rate': 0.12328936723311547, 'n_estimators': 358, 'learning_rate': 0.0859435567445048}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 04:30:14,166] Trial 88 finished with value: 0.6502515314390583 and parameters: {'subsample': 0.12059552445100773, 'dropout_rate': 0.25094214913667323, 'n_estimators': 398, 'learning_rate': 0.09425970178006793}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6695278969957081
[I 2024-04-22 04:30:14,309] Trial 89 finished with value: 0.626684953002948 and parameters: {'subsample': 0.3366985085088288, 'dropout_rate': 0.11582199980227537, 'n_estimators': 3, 'learning_rate': 0.09745817730537755}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:30:18,926] Trial 90 finished with value: 0.6425238560019988 and parameters: {'subsample': 0.7147405584008215, 'dropout_rate': 0.10184332440552968, 'n_estimators': 381, 'learning_rate': 0.09987279586280831}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 04:30:21,777] Trial 91 finished with value: 0.6502511075960021 and parameters: {'subsample': 0.1197292819318041, 'dropout_rate': 0.1435742442817984, 'n_estimators': 302, 'learning_rate': 0.087798531215061}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:30:25,149] Trial 92 finished with value: 0.6391903478531732 and parameters: {'subsample': 0.18156969228948044, 'dropout_rate': 0.514832652843558, 'n_estimators': 358, 'learning_rate': 0.08287107241852493}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:30:25,674] Trial 93 finished with value: 0.6530324600092678 and parameters: {'subsample': 0.10116363782376565, 'dropout_rate': 0.20687989385475763, 'n_estimators': 86, 'learning_rate': 0.09485010048542766}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5776892430278885

Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 04:30:26,161] Trial 94 finished with value: 0.6494547186900543 and parameters: {'subsample': 0.14083612378096988, 'dropout_rate': 0.202574595508387, 'n_estimators': 81, 'learning_rate': 0.09452025606843689}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 04:30:26,376] Trial 95 finished with value: 0.6462017795905245 and parameters: {'subsample': 0.2023175387081446, 'dropout_rate': 0.17224087270598065, 'n_estimators': 32, 'learning_rate': 0.09223180868873032}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 04:30:26,825] Trial 96 finished with value: 0.6440110183252548 and parameters: {'subsample': 0.1670558100118433, 'dropout_rate': 0.12453791775883809, 'n_estimators': 74, 'learning_rate': 0.09781494465778756}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:30:27,621] Trial 97 finished with value: 0.6437462040698897 and parameters: {'subsample': 0.11842111322304441, 'dropout_rate': 0.5915083285154504, 'n_estimators': 134, 'learning_rate': 0.0907120072888149}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:30:27,974] Trial 98 finished with value: 0.645257078110691 and parameters: {'subsample': 0.14327389009583819, 'dropout_rate': 0.22396087436354034, 'n_estimators': 56, 'learning_rate': 0.037970790455906664}. Best is trial 11 with value: 0.6546369717001154.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772

[I 2024-04-22 04:30:30,839] A new study created in memory with name: no-name-439e2688-3487-45b3-a32a-b2fde7be9925

Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:30:30,831] Trial 99 finished with value: 0.6315457042952801 and parameters: {'subsample': 0.9104218782867626, 'dropout_rate': 0.14627927054545292, 'n_estimators': 314, 'learning_rate': 0.09500969629381512}. Best is trial 11 with value: 0.6546369717001154.


* Best trial for C-index:
 FrozenTrial(number=11, state=TrialState.COMPLETE, values=[0.6546369717001154], datetime_start=datetime.datetime(2024, 4, 22, 4, 26, 27, 784849), datetime_complete=datetime.datetime(2024, 4, 22, 4, 26, 31, 100586), params={'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=11, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}


* Best Score for C-index:
 0.6546369717001154

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.325676523044078
Fold 2 IBS: 0.24304825871263852
Fold 3 IBS: 0.32959725402563417
Fold 4 IBS: 0.28525857993950676
Fold 5 IBS: 0.27275166189156874
[I 2024-04-22 04:30:31,520] Trial 0 finished with value: 0.29126645552268526 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.4243468471583305
Fold 2 IBS: 0.3901688969230736
Fold 3 IBS: 0.3925037735733181
Fold 4 IBS: 0.37084045783124014
Fold 5 IBS: 0.34079939992495495
[I 2024-04-22 04:30:36,989] Trial 1 finished with value: 0.3837318750821835 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.388663470563614
Fold 2 IBS: 0.30068109749088767
Fold 3 IBS: 0.37991021668413694
Fold 4 IBS: 0.31125225156593306
Fold 5 IBS: 0.33025000236569196
[I 2024-04-22 04:30:38,198] Trial 2 finished with value: 0.3421514077340527 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.39180502103928067
Fold 2 IBS: 0.2723339174348366
Fold 3 IBS: 0.3810564835553453
Fold 4 IBS: 0.31083880707894046
Fold 5 IBS: 0.32302330983004995
[I 2024-04-22 04:30:39,816] Trial 3 finished with value: 0.3358115077876906 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.3942661310659211
Fold 2 IBS: 0.2786887228590945
Fold 3 IBS: 0.38453417136199225
Fold 4 IBS: 0.30946013671851486
Fold 5 IBS: 0.3380956170278929
[I 2024-04-22 04:30:42,051] Trial 4 finished with value: 0.3410089558066831 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.4122519263817958
Fold 2 IBS: 0.37802969684822957
Fold 3 IBS: 0.39159093324564376
Fold 4 IBS: 0.3474683993736778
Fold 5 IBS: 0.331005424885477
[I 2024-04-22 04:30:44,689] Trial 5 finished with value: 0.3720692761469648 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.29828726911528397
Fold 2 IBS: 0.21645133017694293
Fold 3 IBS: 0.29703048020856426
Fold 4 IBS: 0.2630471709724218
Fold 5 IBS: 0.24865969387198464
[I 2024-04-22 04:30:45,869] Trial 6 finished with value: 0.26469518886903953 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.26469518886903953.
Fold 1 IBS: 0.2557242083039886
Fold 2 IBS: 0.20086012542584775
Fold 3 IBS: 0.2559954533104581
Fold 4 IBS: 0.22842064037634063
Fold 5 IBS: 0.21078271864122022
[I 2024-04-22 04:30:46,211] Trial 7 finished with value: 0.23035662921157102 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.3320623714087893
Fold 2 IBS: 0.24778879382834276
Fold 3 IBS: 0.33914263875054795
Fold 4 IBS: 0.28890146090534946
Fold 5 IBS: 0.2812784361061495
[I 2024-04-22 04:30:48,352] Trial 8 finished with value: 0.2978347401998358 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.41355256605441043
Fold 2 IBS: 0.3803418251430308
Fold 3 IBS: 0.391840649836237
Fold 4 IBS: 0.35131804113613163
Fold 5 IBS: 0.3420174736572878
[I 2024-04-22 04:30:52,709] Trial 9 finished with value: 0.3758141111654195 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.24688672048424357
Fold 2 IBS: 0.23091253666135533
Fold 3 IBS: 0.22886383485395365
Fold 4 IBS: 0.2411627533361748
Fold 5 IBS: 0.22809345046771862
[I 2024-04-22 04:30:52,921] Trial 10 finished with value: 0.23518385916068918 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.24591184955753378
Fold 2 IBS: 0.22742364641206644
Fold 3 IBS: 0.22872479609872584
Fold 4 IBS: 0.23866162133190572
Fold 5 IBS: 0.22419206168941844
[I 2024-04-22 04:30:53,058] Trial 11 finished with value: 0.23298279501793004 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.27793099862360215
Fold 2 IBS: 0.206421201549277
Fold 3 IBS: 0.3033964040369018
Fold 4 IBS: 0.25885632591202035
Fold 5 IBS: 0.24036670243462674
[I 2024-04-22 04:30:53,421] Trial 12 finished with value: 0.2573943265112856 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.24533484626464844
Fold 2 IBS: 0.22482603295491327
Fold 3 IBS: 0.2288900501286023
Fold 4 IBS: 0.2368692484235475
Fold 5 IBS: 0.22138571816323843
[I 2024-04-22 04:30:53,573] Trial 13 finished with value: 0.23146117918699 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.2838507400334174
Fold 2 IBS: 0.2064642223133477
Fold 3 IBS: 0.2862860280530503
Fold 4 IBS: 0.24790860860459804
Fold 5 IBS: 0.23314936884966506
[I 2024-04-22 04:30:54,180] Trial 14 finished with value: 0.25153179357081573 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.35006944344323987
Fold 2 IBS: 0.2558059352575901
Fold 3 IBS: 0.35764903579940016
Fold 4 IBS: 0.2961404203062488
Fold 5 IBS: 0.30092599232489686
[I 2024-04-22 04:30:54,746] Trial 15 finished with value: 0.31211816542627513 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.35631365801715226
Fold 2 IBS: 0.25161964253518077
Fold 3 IBS: 0.369571444037457
Fold 4 IBS: 0.2888851792263117
Fold 5 IBS: 0.30610042125310616
[I 2024-04-22 04:30:56,753] Trial 16 finished with value: 0.3144980690138416 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.24637560220536686
Fold 2 IBS: 0.21110503456978988
Fold 3 IBS: 0.23491938690940084
Fold 4 IBS: 0.22943718629070567
Fold 5 IBS: 0.21121348311812857
[I 2024-04-22 04:30:57,206] Trial 17 finished with value: 0.22661013861867835 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.291291305025286
Fold 2 IBS: 0.21140388138900232
Fold 3 IBS: 0.28863212236387226
Fold 4 IBS: 0.2563863518782749
Fold 5 IBS: 0.24311757382074356
[I 2024-04-22 04:30:59,966] Trial 18 finished with value: 0.2581662468954358 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2734286915536386
Fold 2 IBS: 0.20097901536547996
Fold 3 IBS: 0.2756019255493613

Fold 4 IBS: 0.2426706185564074
Fold 5 IBS: 0.22283081379821795
[I 2024-04-22 04:31:00,772] Trial 19 finished with value: 0.24310221296462103 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24550608887605468
Fold 2 IBS: 0.2133505584021398
Fold 3 IBS: 0.23294747738469943
Fold 4 IBS: 0.23024731593258208
Fold 5 IBS: 0.2123372739360029
[I 2024-04-22 04:31:01,157] Trial 20 finished with value: 0.22687774290629575 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2448259892509062
Fold 2 IBS: 0.21786672573833757
Fold 3 IBS: 0.23050391968540718
Fold 4 IBS: 0.23249100529840805
Fold 5 IBS: 0.215533050087791
[I 2024-04-22 04:31:01,529] Trial 21 finished with value: 0.22824413801216997 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24640086873642586
Fold 2 IBS: 0.2292326597688009
Fold 3 IBS: 0.22875342577755223
Fold 4 IBS: 0.23993607277337323
Fold 5 IBS: 0.22642423701728293
[I 2024-04-22 04:31:01,949] Trial 22 finished with value: 0.23414945281468702 and parameters: {'subsample': 0.6537769964653461, 'dropout_rate': 0.8093716219515759, 'n_estimators': 77, 'learning_rate': 0.0014039455806401802}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2589848196302069
Fold 2 IBS: 0.2024618720492697
Fold 3 IBS: 0.25302707950360914
Fold 4 IBS: 0.23227378691244918
Fold 5 IBS: 0.21704698047063445
[I 2024-04-22 04:31:02,753] Trial 23 finished with value: 0.23275890771323388 and parameters: {'subsample': 0.8534306852041174, 'dropout_rate': 0.801007553345817, 'n_estimators': 146, 'learning_rate': 0.013693154749890787}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24622272418585897
Fold 2 IBS: 0.211517231301511
Fold 3 IBS: 0.23465708353277137
Fold 4 IBS: 0.22958311755255775
Fold 5 IBS: 0.21133338172755428
[I 2024-04-22 04:31:03,096] Trial 24 finished with value: 0.2266627076600507 and parameters: {'subsample': 0.6057018904919792, 'dropout_rate': 0.9862533241546715, 'n_estimators': 62, 'learning_rate': 0.01572471796157672}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.27824402320018216
Fold 2 IBS: 0.20485085384499563
Fold 3 IBS: 0.2745783058664053
Fold 4 IBS: 0.24546543206826768
Fold 5 IBS: 0.23263373515357302
[I 2024-04-22 04:31:03,848] Trial 25 finished with value: 0.24715447002668472 and parameters: {'subsample': 0.8655825350862807, 'dropout_rate': 0.991151252373464, 'n_estimators': 145, 'learning_rate': 0.0210314188428598}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.33014689072398445
Fold 2 IBS: 0.24720038348309642
Fold 3 IBS: 0.3344515997942725
Fold 4 IBS: 0.28780550809923416
Fold 5 IBS: 0.2783585358589275
[I 2024-04-22 04:31:05,173] Trial 26 finished with value: 0.295592583591903 and parameters: {'subsample': 0.5978333574014947, 'dropout_rate': 0.8982223660451839, 'n_estimators': 222, 'learning_rate': 0.029166999751579693}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24499219484414198
Fold 2 IBS: 0.21624851273382031
Fold 3 IBS: 0.2314723911058174
Fold 4 IBS: 0.23142113333280664
Fold 5 IBS: 0.21391217014232608
[I 2024-04-22 04:31:05,440] Trial 27 finished with value: 0.2276092804317825 and parameters: {'subsample': 0.7973831324954838, 'dropout_rate': 0.9591162049738791, 'n_estimators': 39, 'learning_rate': 0.018143610116936895}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24515366399581964
Fold 2 IBS: 0.21501049991641955
Fold 3 IBS: 0.23211607481589766
Fold 4 IBS: 0.23087262715339726
Fold 5 IBS: 0.2134002972589192
[I 2024-04-22 04:31:05,899] Trial 28 finished with value: 0.22731063262809065 and parameters: {'subsample': 0.5742192061348756, 'dropout_rate': 0.920234801468329, 'n_estimators': 86, 'learning_rate': 0.008921459414064498}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.3063594897860022
Fold 2 IBS: 0.22365458368515215
Fold 3 IBS: 0.3055669075377605
Fold 4 IBS: 0.2699993099904004
Fold 5 IBS: 0.25609676833722445
[I 2024-04-22 04:31:06,518] Trial 29 finished with value: 0.2723354118673079 and parameters: {'subsample': 0.6850952456167174, 'dropout_rate': 0.7643659553187094, 'n_estimators': 112, 'learning_rate': 0.04248605264426071}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.3037100708108595
Fold 2 IBS: 0.22137743897919782
Fold 3 IBS: 0.3028696552655383
Fold 4 IBS: 0.2673327822795468
Fold 5 IBS: 0.253763234707761
[I 2024-04-22 04:31:07,701] Trial 30 finished with value: 0.2698106364085807 and parameters: {'subsample': 0.9166631566118534, 'dropout_rate': 0.6038945600293156, 'n_estimators': 166, 'learning_rate': 0.027648893219016982}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2449141797735416
Fold 2 IBS: 0.21676885376764835
Fold 3 IBS: 0.23117242159093349
Fold 4 IBS: 0.2319218743035483
Fold 5 IBS: 0.2146636746811494
[I 2024-04-22 04:31:08,260] Trial 31 finished with value: 0.2278882008233642 and parameters: {'subsample': 0.580266273279712, 'dropout_rate': 0.9271779254835972, 'n_estimators': 89, 'learning_rate': 0.007554955553126899}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24480968404806477
Fold 2 IBS: 0.21840173072243738
Fold 3 IBS: 0.2303084891481403
Fold 4 IBS: 0.23294002575148984
Fold 5 IBS: 0.21611746639599275
[I 2024-04-22 04:31:08,545] Trial 32 finished with value: 0.22851547921322504 and parameters: {'subsample': 0.7276466032162393, 'dropout_rate': 0.8648618701493432, 'n_estimators': 37, 'learning_rate': 0.015821999327691336}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24444290623218176
Fold 2 IBS: 0.22003318344553727
Fold 3 IBS: 0.23004295934041907
Fold 4 IBS: 0.23318439942131822
Fold 5 IBS: 0.21729227081764876
[I 2024-04-22 04:31:09,009] Trial 33 finished with value: 0.228999143851421 and parameters: {'subsample': 0.42583224460357205, 'dropout_rate': 0.9322585736914469, 'n_estimators': 74, 'learning_rate': 0.007128988064747212}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2599735862383478
Fold 2 IBS: 0.20223791307592695
Fold 3 IBS: 0.25497930340177116
Fold 4 IBS: 0.23208609347398076
Fold 5 IBS: 0.2141781691601287
[I 2024-04-22 04:31:09,820] Trial 34 finished with value: 0.2326910130700311 and parameters: {'subsample': 0.5577914444927095, 'dropout_rate': 0.9877256275541959, 'n_estimators': 127, 'learning_rate': 0.016160179473353013}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24663201725543496
Fold 2 IBS: 0.2300001255908101
Fold 3 IBS: 0.22880051556212538
Fold 4 IBS: 0.2405667786146309
Fold 5 IBS: 0.2271226637337803
[I 2024-04-22 04:31:10,024] Trial 35 finished with value: 0.23462442015135632 and parameters: {'subsample': 0.7803178043419461, 'dropout_rate': 0.43975685710717877, 'n_estimators': 13, 'learning_rate': 0.005826832206318818}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.367577937922695
Fold 2 IBS: 0.27682015096192025
Fold 3 IBS: 0.3682948275396474
Fold 4 IBS: 0.30452048859388936
Fold 5 IBS: 0.31541637422362634
[I 2024-04-22 04:31:14,601] Trial 36 finished with value: 0.32652595584835564 and parameters: {'subsample': 0.5171903924633928, 'dropout_rate': 0.2795306755316796, 'n_estimators': 421, 'learning_rate': 0.0238218995141648}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.39841893189624056
Fold 2 IBS: 0.32060019829104597
Fold 3 IBS: 0.3852983569562301
Fold 4 IBS: 0.31620276009532605
Fold 5 IBS: 0.33770453446230725
[I 2024-04-22 04:31:16,203] Trial 37 finished with value: 0.35164495634023 and parameters: {'subsample': 0.43420796750396373, 'dropout_rate': 0.7621022900062648, 'n_estimators': 241, 'learning_rate': 0.059207327336158105}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2614340968260537
Fold 2 IBS: 0.2021120088730102
Fold 3 IBS: 0.2566141669263308

Fold 4 IBS: 0.23453614765450895
Fold 5 IBS: 0.2122914778844625
[I 2024-04-22 04:31:17,584] Trial 38 finished with value: 0.2333975796328732 and parameters: {'subsample': 0.605229739689187, 'dropout_rate': 0.13272164755980653, 'n_estimators': 176, 'learning_rate': 0.01283698591663533}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2943463281154152
Fold 2 IBS: 0.21435275898375683
Fold 3 IBS: 0.292776623523439
Fold 4 IBS: 0.2606234117164125
Fold 5 IBS: 0.24191548716779984
[I 2024-04-22 04:31:17,957] Trial 39 finished with value: 0.26080292190136467 and parameters: {'subsample': 0.6970162917669863, 'dropout_rate': 0.48841341315505027, 'n_estimators': 59, 'learning_rate': 0.06892741183938003}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2956705905294083
Fold 2 IBS: 0.21430445848659016
Fold 3 IBS: 0.2928588854990794
Fold 4 IBS: 0.2596622123064148
Fold 5 IBS: 0.24678618384472736
[I 2024-04-22 04:31:18,559] Trial 40 finished with value: 0.261856466133244 and parameters: {'subsample': 0.8054982836102402, 'dropout_rate': 0.876813469756125, 'n_estimators': 112, 'learning_rate': 0.035912260209657}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2455156591195911
Fold 2 IBS: 0.2134495272871624
Fold 3 IBS: 0.23298021917302758
Fold 4 IBS: 0.2302623346190742
Fold 5 IBS: 0.21228868131417766
[I 2024-04-22 04:31:18,860] Trial 41 finished with value: 0.22689928430260659 and parameters: {'subsample': 0.9180988510314624, 'dropout_rate': 0.9438179242085731, 'n_estimators': 49, 'learning_rate': 0.017446250508837573}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2448957834513211
Fold 2 IBS: 0.2170005935741622
Fold 3 IBS: 0.2310161992206827
Fold 4 IBS: 0.23202460062538527
Fold 5 IBS: 0.21439769364800865
[I 2024-04-22 04:31:19,108] Trial 42 finished with value: 0.22786697410391196 and parameters: {'subsample': 0.9464169664396729, 'dropout_rate': 0.9430136432098365, 'n_estimators': 33, 'learning_rate': 0.020048086949614748}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2658273736705565
Fold 2 IBS: 0.2020524405250075
Fold 3 IBS: 0.2606080098559383
Fold 4 IBS: 0.23638269291325226
Fold 5 IBS: 0.2218591947364019
[I 2024-04-22 04:31:19,573] Trial 43 finished with value: 0.23734594234023126 and parameters: {'subsample': 0.8926693439285954, 'dropout_rate': 0.8370454250738812, 'n_estimators': 86, 'learning_rate': 0.027633234880330062}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24553832608292522
Fold 2 IBS: 0.22567851914167422
Fold 3 IBS: 0.22880097138904068
Fold 4 IBS: 0.23740161794197437
Fold 5 IBS: 0.22252686111769712
[I 2024-04-22 04:31:19,898] Trial 44 finished with value: 0.2319892591346623 and parameters: {'subsample': 0.7574766140068628, 'dropout_rate': 0.9209040458467185, 'n_estimators': 56, 'learning_rate': 0.004536994661454437}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24514475725184326
Fold 2 IBS: 0.2232932452954966
Fold 3 IBS: 0.229031285656079
Fold 4 IBS: 0.23565641281785177
Fold 5 IBS: 0.2206722434927271
[I 2024-04-22 04:31:20,118] Trial 45 finished with value: 0.23075958890279952 and parameters: {'subsample': 0.6254432766833774, 'dropout_rate': 0.7565492792792287, 'n_estimators': 25, 'learning_rate': 0.014308783844555807}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.34556775223404884
Fold 2 IBS: 0.26003024903765853
Fold 3 IBS: 0.35086044091810686
Fold 4 IBS: 0.29629520252719266
Fold 5 IBS: 0.2940333944770714
[I 2024-04-22 04:31:21,022] Trial 46 finished with value: 0.30935740783881566 and parameters: {'subsample': 0.5454269842024818, 'dropout_rate': 0.8816321250931852, 'n_estimators': 160, 'learning_rate': 0.048014785607437535}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2540323022244742
Fold 2 IBS: 0.19805028914151954
Fold 3 IBS: 0.25415324167744757
Fold 4 IBS: 0.22627491702741187
Fold 5 IBS: 0.2109899988311474
[I 2024-04-22 04:31:21,463] Trial 47 finished with value: 0.22870014978040012 and parameters: {'subsample': 0.2385519301616531, 'dropout_rate': 0.9917631969393944, 'n_estimators': 81, 'learning_rate': 0.02513395893947125}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.25728763936252025
Fold 2 IBS: 0.20231216512367317
Fold 3 IBS: 0.25262795298766366
Fold 4 IBS: 0.23138017803988314
Fold 5 IBS: 0.21120324156934484
[I 2024-04-22 04:31:23,041] Trial 48 finished with value: 0.23096223541661703 and parameters: {'subsample': 0.47852228408162223, 'dropout_rate': 0.19701471782839963, 'n_estimators': 193, 'learning_rate': 0.010411009503204737}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24673307008984274
Fold 2 IBS: 0.23042055290160676
Fold 3 IBS: 0.22882596707663166
Fold 4 IBS: 0.2408186354309607
Fold 5 IBS: 0.22754159795832032
[I 2024-04-22 04:31:23,217] Trial 49 finished with value: 0.23486796469147248 and parameters: {'subsample': 0.9361198918736817, 'dropout_rate': 0.6584903001856733, 'n_estimators': 2, 'learning_rate': 0.031855435969108184}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2703393986257053
Fold 2 IBS: 0.20257051463406026
Fold 3 IBS: 0.2660776078398826
Fold 4 IBS: 0.23954054354969337
Fold 5 IBS: 0.22554209413235315
[I 2024-04-22 04:31:24,075] Trial 50 finished with value: 0.24081403175633892 and parameters: {'subsample': 0.7006430134270305, 'dropout_rate': 0.8318264141869088, 'n_estimators': 134, 'learning_rate': 0.019642786526356794}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24526003850914455
Fold 2 IBS: 0.21467902770255018
Fold 3 IBS: 0.23231863109009884
Fold 4 IBS: 0.23070537111335643
Fold 5 IBS: 0.2129056406944009
[I 2024-04-22 04:31:24,402] Trial 51 finished with value: 0.2271737418219102 and parameters: {'subsample': 0.7994296496769766, 'dropout_rate': 0.9513190706056927, 'n_estimators': 45, 'learning_rate': 0.017594085400454734}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2465932017623929
Fold 2 IBS: 0.2299268996974446
Fold 3 IBS: 0.22878875620635092
Fold 4 IBS: 0.24043322363238803
Fold 5 IBS: 0.22699010755245638
[I 2024-04-22 04:31:24,842] Trial 52 finished with value: 0.23454643777020653 and parameters: {'subsample': 0.9522184225974055, 'dropout_rate': 0.9540184058192569, 'n_estimators': 65, 'learning_rate': 0.00125014832336073}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24483084636350344
Fold 2 IBS: 0.21994268306656278
Fold 3 IBS: 0.2298159042727
Fold 4 IBS: 0.23377868427496837
Fold 5 IBS: 0.217018869345563
[I 2024-04-22 04:31:25,199] Trial 53 finished with value: 0.22907739746465952 and parameters: {'subsample': 0.843494929630295, 'dropout_rate': 0.915585413735216, 'n_estimators': 46, 'learning_rate': 0.011064278636511417}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2542837578406007
Fold 2 IBS: 0.20408105962436318
Fold 3 IBS: 0.24632166462762337
Fold 4 IBS: 0.2299345290491981
Fold 5 IBS: 0.20927255603620012
[I 2024-04-22 04:31:25,435] Trial 54 finished with value: 0.2287787134355971 and parameters: {'subsample': 0.8204677487117119, 'dropout_rate': 0.3571755626038756, 'n_estimators': 21, 'learning_rate': 0.08270475242185228}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2534849870495454
Fold 2 IBS: 0.2041508121560885
Fold 3 IBS: 0.24576477799133983
Fold 4 IBS: 0.22971527127754243
Fold 5 IBS: 0.21306295114857882
[I 2024-04-22 04:31:25,978] Trial 55 finished with value: 0.229235759924619 and parameters: {'subsample': 0.8887421810659816, 'dropout_rate': 0.8993071903534846, 'n_estimators': 99, 'learning_rate': 0.01667266938646207}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24660568247659428
Fold 2 IBS: 0.21064080007395522
Fold 3 IBS: 0.23535116446600424
Fold 4 IBS: 0.22928161830063465
Fold 5 IBS: 0.21108618854351036
[I 2024-04-22 04:31:26,259] Trial 56 finished with value: 0.22659309077213977 and parameters: {'subsample': 0.7632340729628572, 'dropout_rate': 0.9968061240868161, 'n_estimators': 47, 'learning_rate': 0.0219993213211057}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.32634594317205234
Fold 2 IBS: 0.2441074249846434
Fold 3 IBS: 0.33090013102352434
Fold 4 IBS: 0.28596472610806994

Fold 5 IBS: 0.27461860801929316
[I 2024-04-22 04:31:28,033] Trial 57 finished with value: 0.29238736666151666 and parameters: {'subsample': 0.763955514973389, 'dropout_rate': 0.9964559295946985, 'n_estimators': 282, 'learning_rate': 0.02203371126489022}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2524958013314946
Fold 2 IBS: 0.20467957580837548
Fold 3 IBS: 0.24466604990129345
Fold 4 IBS: 0.22951388023914565
Fold 5 IBS: 0.21232254648299242
[I 2024-04-22 04:31:28,356] Trial 58 finished with value: 0.22873557075266032 and parameters: {'subsample': 0.8210665501105633, 'dropout_rate': 0.9557982366790785, 'n_estimators': 50, 'learning_rate': 0.03153701184110286}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2450766728615442
Fold 2 IBS: 0.21570571438138603
Fold 3 IBS: 0.23170031253784298
Fold 4 IBS: 0.23100841297079955
Fold 5 IBS: 0.21387190006582926
[I 2024-04-22 04:31:28,572] Trial 59 finished with value: 0.2274726025634804 and parameters: {'subsample': 0.7169412850975417, 'dropout_rate': 0.7863461136932807, 'n_estimators': 20, 'learning_rate': 0.03702429542217137}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2799925625848654
Fold 2 IBS: 0.20541721127231735
Fold 3 IBS: 0.27641891339421315
Fold 4 IBS: 0.24728738758668545
Fold 5 IBS: 0.231501204035336
[I 2024-04-22 04:31:29,251] Trial 60 finished with value: 0.24812345577468348 and parameters: {'subsample': 0.6580853749310097, 'dropout_rate': 0.8504207080106669, 'n_estimators': 120, 'learning_rate': 0.026233120654123206}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24506114552036967
Fold 2 IBS: 0.2227391563952413
Fold 3 IBS: 0.22917592951399726
Fold 4 IBS: 0.23541036546351077
Fold 5 IBS: 0.21951860445014307
[I 2024-04-22 04:31:29,676] Trial 61 finished with value: 0.23038104026865242 and parameters: {'subsample': 0.7368242492609791, 'dropout_rate': 0.9633166813429076, 'n_estimators': 74, 'learning_rate': 0.0051620199911569815}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.25624845596017926
Fold 2 IBS: 0.2031140844165004
Fold 3 IBS: 0.24945076411968525
Fold 4 IBS: 0.2308386419236711
Fold 5 IBS: 0.21467054375030795
[I 2024-04-22 04:31:30,226] Trial 62 finished with value: 0.23086449803406878 and parameters: {'subsample': 0.9008804237198612, 'dropout_rate': 0.8972785584562114, 'n_estimators': 99, 'learning_rate': 0.018480727132717638}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24525813986654407
Fold 2 IBS: 0.22394706204039122
Fold 3 IBS: 0.22893913491420798
Fold 4 IBS: 0.23632535189099202
Fold 5 IBS: 0.2214331425247103
[I 2024-04-22 04:31:30,497] Trial 63 finished with value: 0.2311805662473691 and parameters: {'subsample': 0.6297164279405434, 'dropout_rate': 0.5823907068184614, 'n_estimators': 34, 'learning_rate': 0.009594140607425444}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2456393866366244
Fold 2 IBS: 0.21299153169174545
Fold 3 IBS: 0.23361997509095692
Fold 4 IBS: 0.22975030626215406
Fold 5 IBS: 0.21253431380250287
[I 2024-04-22 04:31:30,870] Trial 64 finished with value: 0.22690710269679676 and parameters: {'subsample': 0.5245480196355067, 'dropout_rate': 0.9413786510901908, 'n_estimators': 62, 'learning_rate': 0.014230389833347484}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24436030005286818
Fold 2 IBS: 0.21456927917072746
Fold 3 IBS: 0.23251529067371102
Fold 4 IBS: 0.23061435502797772
Fold 5 IBS: 0.21371928695614437
[I 2024-04-22 04:31:31,266] Trial 65 finished with value: 0.22715570237628574 and parameters: {'subsample': 0.45473842457833824, 'dropout_rate': 0.9696337973251744, 'n_estimators': 60, 'learning_rate': 0.013175688908273541}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24425791895146917
Fold 2 IBS: 0.2144102132061209
Fold 3 IBS: 0.2326749313963326
Fold 4 IBS: 0.23050958085920942
Fold 5 IBS: 0.213580757387187
[I 2024-04-22 04:31:31,722] Trial 66 finished with value: 0.22708668036006383 and parameters: {'subsample': 0.4538390106754839, 'dropout_rate': 0.9973222357307537, 'n_estimators': 64, 'learning_rate': 0.012590689815234278}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.30111629951862323
Fold 2 IBS: 0.22040932376290737
Fold 3 IBS: 0.3017744714900754
Fold 4 IBS: 0.2662157921914366
Fold 5 IBS: 0.24893153605233173
[I 2024-04-22 04:31:33,802] Trial 67 finished with value: 0.26768948460307485 and parameters: {'subsample': 0.5164456222127641, 'dropout_rate': 0.9957101474211375, 'n_estimators': 321, 'learning_rate': 0.014042638169425688}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.37509937493932133
Fold 2 IBS: 0.28368774613275377
Fold 3 IBS: 0.3742704223614346
Fold 4 IBS: 0.3062111301277816
Fold 5 IBS: 0.32272587873763087
[I 2024-04-22 04:31:38,464] Trial 68 finished with value: 0.3323989104597844 and parameters: {'subsample': 0.396894830548818, 'dropout_rate': 0.8751386316641768, 'n_estimators': 496, 'learning_rate': 0.02170877428217187}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24693470011980795
Fold 2 IBS: 0.2311270655102999
Fold 3 IBS: 0.2288788081398321
Fold 4 IBS: 0.2412571776298174
Fold 5 IBS: 0.22851254319260392
[I 2024-04-22 04:31:38,660] Trial 69 finished with value: 0.2353420589184722 and parameters: {'subsample': 0.5321088311619213, 'dropout_rate': 0.6850428736307019, 'n_estimators': 11, 'learning_rate': 0.0033430171272597013}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.3852859364739752
Fold 2 IBS: 0.2874373793502864
Fold 3 IBS: 0.38033520143731914
Fold 4 IBS: 0.3073003186028882
Fold 5 IBS: 0.3319997062353503
[I 2024-04-22 04:31:42,555] Trial 70 finished with value: 0.3384717084199639 and parameters: {'subsample': 0.29831657136945555, 'dropout_rate': 0.7160048016307664, 'n_estimators': 408, 'learning_rate': 0.030184746562878957}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2447983751594558
Fold 2 IBS: 0.21391212397472412
Fold 3 IBS: 0.2330229517211651
Fold 4 IBS: 0.23018009501747053
Fold 5 IBS: 0.21284182693141118
[I 2024-04-22 04:31:42,932] Trial 71 finished with value: 0.22695107456084535 and parameters: {'subsample': 0.4656561384348985, 'dropout_rate': 0.9607291922995583, 'n_estimators': 67, 'learning_rate': 0.012470692352433808}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24442739217118456
Fold 2 IBS: 0.2202080752130095
Fold 3 IBS: 0.22992449606500545
Fold 4 IBS: 0.23367467424256175
Fold 5 IBS: 0.21734687615024553
[I 2024-04-22 04:31:43,313] Trial 72 finished with value: 0.22911630276840134 and parameters: {'subsample': 0.44632544286302367, 'dropout_rate': 0.940927063465276, 'n_estimators': 66, 'learning_rate': 0.007736153984692023}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24873206449656773
Fold 2 IBS: 0.20714960221304482
Fold 3 IBS: 0.2391494048288076
Fold 4 IBS: 0.22844134347141637
Fold 5 IBS: 0.20990424423992582
[I 2024-04-22 04:31:43,868] Trial 73 finished with value: 0.2266753318499525 and parameters: {'subsample': 0.47075831672242574, 'dropout_rate': 0.9113190760145863, 'n_estimators': 107, 'learning_rate': 0.011745458975142266}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.255704669484436
Fold 2 IBS: 0.20256586151204847
Fold 3 IBS: 0.24898577012417628
Fold 4 IBS: 0.2304554628587353
Fold 5 IBS: 0.2113616322548472
[I 2024-04-22 04:31:44,460] Trial 74 finished with value: 0.22981467924684865 and parameters: {'subsample': 0.48487077302079995, 'dropout_rate': 0.818126846171267, 'n_estimators': 107, 'learning_rate': 0.01659395710476026}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.26069403640186745
Fold 2 IBS: 0.2002858960044775
Fold 3 IBS: 0.2590273478317007
Fold 4 IBS: 0.23277903197261338
Fold 5 IBS: 0.2129658995167273
[I 2024-04-22 04:31:44,961] Trial 75 finished with value: 0.23315044234547727 and parameters: {'subsample': 0.3931286314918456, 'dropout_rate': 0.9058514756642456, 'n_estimators': 93, 'learning_rate': 0.024132850675330414}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2449207774729007
Fold 2 IBS: 0.2164741146584261
Fold 3 IBS: 0.23115475964699578
Fold 4 IBS: 0.2318272715320025
Fold 5 IBS: 0.21495710360760373
[I 2024-04-22 04:31:45,215] Trial 76 finished with value: 0.22786680538358572 and parameters: {'subsample': 0.5683268745859826, 'dropout_rate': 0.8653081987830238, 'n_estimators': 34, 'learning_rate': 0.020347121996093395}. Best is trial 56 with value: 0.22659309077213977.

Fold 1 IBS: 0.2506811440240583
Fold 2 IBS: 0.2053539697592853
Fold 3 IBS: 0.2432701864482772
Fold 4 IBS: 0.2284683602008423
Fold 5 IBS: 0.21006566848816424
[I 2024-04-22 04:31:46,127] Trial 77 finished with value: 0.22756786578412544 and parameters: {'subsample': 0.5096986308003991, 'dropout_rate': 0.49881327862855496, 'n_estimators': 145, 'learning_rate': 0.010267257888313383}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24728609182637104
Fold 2 IBS: 0.20948456237788454
Fold 3 IBS: 0.2367879689804507
Fold 4 IBS: 0.22900068533758589
Fold 5 IBS: 0.21042389725248523
[I 2024-04-22 04:31:46,541] Trial 78 finished with value: 0.2265966411549555 and parameters: {'subsample': 0.5939500427136554, 'dropout_rate': 0.7406477151463077, 'n_estimators': 73, 'learning_rate': 0.015420072941943445}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2491522359439618
Fold 2 IBS: 0.20720785646863638
Fold 3 IBS: 0.23970965460068624
Fold 4 IBS: 0.22880108027481874
Fold 5 IBS: 0.2102336161969871
[I 2024-04-22 04:31:47,074] Trial 79 finished with value: 0.22702088869701803 and parameters: {'subsample': 0.6723788047810191, 'dropout_rate': 0.7413305472330791, 'n_estimators': 82, 'learning_rate': 0.01601211448054851}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24520954400807898
Fold 2 IBS: 0.2238125298457514
Fold 3 IBS: 0.22900572731692778
Fold 4 IBS: 0.2362826500145415
Fold 5 IBS: 0.22138753922008994
[I 2024-04-22 04:31:47,467] Trial 80 finished with value: 0.23113959808107792 and parameters: {'subsample': 0.5472725501406392, 'dropout_rate': 0.7943244209025906, 'n_estimators': 49, 'learning_rate': 0.006807484156131071}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24699041341064157
Fold 2 IBS: 0.20997334219713817
Fold 3 IBS: 0.23605719801087272
Fold 4 IBS: 0.22913034206464886
Fold 5 IBS: 0.21064802263090768
[I 2024-04-22 04:31:47,928] Trial 81 finished with value: 0.2265598636628418 and parameters: {'subsample': 0.6070545538128025, 'dropout_rate': 0.6341528845468055, 'n_estimators': 76, 'learning_rate': 0.014291926646619518}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.26424067842199594
Fold 2 IBS: 0.2020280704264556
Fold 3 IBS: 0.2598748714749781
Fold 4 IBS: 0.2359141284498117
Fold 5 IBS: 0.21842360306513237
[I 2024-04-22 04:31:48,621] Trial 82 finished with value: 0.23609627036767472 and parameters: {'subsample': 0.5922453928972238, 'dropout_rate': 0.6191715075378723, 'n_estimators': 120, 'learning_rate': 0.019313878373930102}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24781953444770255
Fold 2 IBS: 0.20853906349093898
Fold 3 IBS: 0.23756791720192394
Fold 4 IBS: 0.22887020018619814
Fold 5 IBS: 0.21041983371444753
[I 2024-04-22 04:31:49,066] Trial 83 finished with value: 0.22664330980824224 and parameters: {'subsample': 0.6146609519724093, 'dropout_rate': 0.6421886730626755, 'n_estimators': 78, 'learning_rate': 0.015223953623176103}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.25409839780204135
Fold 2 IBS: 0.20375347292509463
Fold 3 IBS: 0.2467636455182986
Fold 4 IBS: 0.2300581935658389
Fold 5 IBS: 0.21199853281475728
[I 2024-04-22 04:31:49,567] Trial 84 finished with value: 0.22933444852520615 and parameters: {'subsample': 0.6143777540837653, 'dropout_rate': 0.5703883223273155, 'n_estimators': 78, 'learning_rate': 0.02181695324241678}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.2454340835099757
Fold 2 IBS: 0.2136961772818287
Fold 3 IBS: 0.23273056567389488
Fold 4 IBS: 0.23041441332302406
Fold 5 IBS: 0.21235879524348852
[I 2024-04-22 04:31:50,105] Trial 85 finished with value: 0.22692680700644238 and parameters: {'subsample': 0.6445770962436083, 'dropout_rate': 0.6275050227423727, 'n_estimators': 92, 'learning_rate': 0.009130620696524702}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24639926921114977
Fold 2 IBS: 0.22928356450634207
Fold 3 IBS: 0.228754183334704
Fold 4 IBS: 0.2399932817551604
Fold 5 IBS: 0.22623158679105324
[I 2024-04-22 04:31:50,347] Trial 86 finished with value: 0.23413237711968188 and parameters: {'subsample': 0.973596102528499, 'dropout_rate': 0.6913304253389554, 'n_estimators': 30, 'learning_rate': 0.003578120462130444}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.2781927071106972
Fold 2 IBS: 0.2046340904187838
Fold 3 IBS: 0.2743538100055575
Fold 4 IBS: 0.24537628788578655
Fold 5 IBS: 0.22685278282223925
[I 2024-04-22 04:31:50,988] Trial 87 finished with value: 0.24588193564861288 and parameters: {'subsample': 0.5848767613231778, 'dropout_rate': 0.5581423348405448, 'n_estimators': 110, 'learning_rate': 0.0276271691730997}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24497452272007741
Fold 2 IBS: 0.21606979660825898
Fold 3 IBS: 0.23139670442225413
Fold 4 IBS: 0.2314990720998036
Fold 5 IBS: 0.2141402661253793
[I 2024-04-22 04:31:51,292] Trial 88 finished with value: 0.22761607239515466 and parameters: {'subsample': 0.6722249946799236, 'dropout_rate': 0.6479045648592634, 'n_estimators': 46, 'learning_rate': 0.01557167084756894}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.26516278956994344
Fold 2 IBS: 0.20203982539169615
Fold 3 IBS: 0.2600655154320181
Fold 4 IBS: 0.23608038055976957
Fold 5 IBS: 0.21836273665359834
[I 2024-04-22 04:31:52,037] Trial 89 finished with value: 0.2363422495214051 and parameters: {'subsample': 0.6016440183315196, 'dropout_rate': 0.5918885750046846, 'n_estimators': 128, 'learning_rate': 0.018267143567723715}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24573908001820546
Fold 2 IBS: 0.2267737594491462
Fold 3 IBS: 0.22873715282488816
Fold 4 IBS: 0.23814825000178638
Fold 5 IBS: 0.22350505658163744
[I 2024-04-22 04:31:52,204] Trial 90 finished with value: 0.23258065977513276 and parameters: {'subsample': 0.7078102048337904, 'dropout_rate': 0.6730763431068749, 'n_estimators': 9, 'learning_rate': 0.02340866249635589}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24723648683966212
Fold 2 IBS: 0.2097930026030373
Fold 3 IBS: 0.23695352163573088
Fold 4 IBS: 0.22904234996289285
Fold 5 IBS: 0.21058878491646402
[I 2024-04-22 04:31:52,650] Trial 91 finished with value: 0.22672282919155742 and parameters: {'subsample': 0.5313026641418505, 'dropout_rate': 0.5328649004247455, 'n_estimators': 76, 'learning_rate': 0.014627227900695133}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24577407492517803
Fold 2 IBS: 0.21257383264762358
Fold 3 IBS: 0.23379619719392244
Fold 4 IBS: 0.2299460468627917
Fold 5 IBS: 0.21208238643358707
[I 2024-04-22 04:31:53,100] Trial 92 finished with value: 0.22683450761262053 and parameters: {'subsample': 0.5720522744908453, 'dropout_rate': 0.5211260831534085, 'n_estimators': 76, 'learning_rate': 0.011981813096347545}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.2464934086281741
Fold 2 IBS: 0.2109727784624746
Fold 3 IBS: 0.23508367038465994
Fold 4 IBS: 0.22944836247402864
Fold 5 IBS: 0.21128845087097128
[I 2024-04-22 04:31:53,626] Trial 93 finished with value: 0.22665733416406172 and parameters: {'subsample': 0.4994903777603958, 'dropout_rate': 0.5262836252450818, 'n_estimators': 87, 'learning_rate': 0.011492132047389617}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24588199063218563
Fold 2 IBS: 0.2125930156354007
Fold 3 IBS: 0.23390337282832738
Fold 4 IBS: 0.22995057861580706
Fold 5 IBS: 0.21216121330590818
[I 2024-04-22 04:31:54,130] Trial 94 finished with value: 0.22689803420352578 and parameters: {'subsample': 0.49968900942877426, 'dropout_rate': 0.523020546752894, 'n_estimators': 82, 'learning_rate': 0.011066289138468185}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24490369228481912
Fold 2 IBS: 0.2167329842481149
Fold 3 IBS: 0.23111158091166403
Fold 4 IBS: 0.23195611702074945
Fold 5 IBS: 0.21507941572440312
[I 2024-04-22 04:31:54,739] Trial 95 finished with value: 0.22795675803795015 and parameters: {'subsample': 0.5665760978972413, 'dropout_rate': 0.4628605993177724, 'n_estimators': 100, 'learning_rate': 0.006666098315025223}. Best is trial 81 with value: 0.2265598636628418.

Fold 1 IBS: 0.3528807852002724
Fold 2 IBS: 0.26163876419301324
Fold 3 IBS: 0.35927296600690356
Fold 4 IBS: 0.2978922662575483
Fold 5 IBS: 0.3041795583962892
[I 2024-04-22 04:31:55,721] Trial 96 finished with value: 0.31517286801080535 and parameters: {'subsample': 0.41313939490511475, 'dropout_rate': 0.5213109482382285, 'n_estimators': 158, 'learning_rate': 0.054487916689644846}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24708172105946397
Fold 2 IBS: 0.21005062605084635
Fold 3 IBS: 0.23658239945020892
Fold 4 IBS: 0.2291089640988238
Fold 5 IBS: 0.2105403389046395
[I 2024-04-22 04:31:56,148] Trial 97 finished with value: 0.2266728099127965 and parameters: {'subsample': 0.5389995281019297, 'dropout_rate': 0.6077476353900257, 'n_estimators': 73, 'learning_rate': 0.014931416501109941}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.26183286577938214
Fold 2 IBS: 0.20183342233582774
Fold 3 IBS: 0.2575253907596287
Fold 4 IBS: 0.23417362585495322
Fold 5 IBS: 0.21506795896798186
[I 2024-04-22 04:31:57,149] Trial 98 finished with value: 0.23408665273955473 and parameters: {'subsample': 0.545068613650571, 'dropout_rate': 0.5497522480626178, 'n_estimators': 139, 'learning_rate': 0.01569072107683937}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24506962981870725
Fold 2 IBS: 0.2156886398952901
Fold 3 IBS: 0.23166204482631356
Fold 4 IBS: 0.2313740373654556
Fold 5 IBS: 0.2142704544460028
[I 2024-04-22 04:31:57,785] Trial 99 finished with value: 0.22761296127035385 and parameters: {'subsample': 0.4999064806675035, 'dropout_rate': 0.6190205560651515, 'n_estimators': 90, 'learning_rate': 0.00800890927792778}. Best is trial 81 with value: 0.2265598636628418.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.2265598636628418], datetime_start=datetime.datetime(2024, 4, 22, 4, 31, 47, 471617), datetime_complete=datetime.datetime(2024, 4, 22, 4, 31, 47, 927963), params={'subsample': 0.6070545538128025, 'dropout_rate': 0.6341528845468055, 'n_estimators': 76, 'learning_rate': 0.014291926646619518}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=81, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.6070545538128025, 'dropout_rate': 0.6341528845468055, 'n_estimators': 76, 'learning_rate': 0.014291926646619518}


* Best Score for IBS:
 0.2265598636628418

In [75]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [76]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.655
train_ibs:  0.227

#### Test

In [77]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [78]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.10580803679784617,
                                              learning_rate=0.08933703080421439,
                                              n_estimators=324,
                                              random_state=123,
                                              subsample=0.11557957726835853)

C-index score: 0.536

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.6341528845468055,
                                              learning_rate=0.014291926646619518,
                                              n_estimators=76, random_state=123,
                                              subsample=0.6070545538128025)

IBS: 0.234

In [79]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [93]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.866   1.0
ExtraSurvivalTrees               0.826   2.0
GradientBoosting                 0.759   3.0
CoxElastic                       0.726   4.0
CoxLasso                         0.725   5.0
CoxPH                            0.724   6.0
ComponentwiseGradientBoosting    0.655   7.0
CoxRidge                         0.649   8.0

In [94]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.188   1.0
Randomsurvivalforest           0.190   2.0
CoxLasso                       0.199   3.5
CoxElastic                     0.199   3.5
CoxPH                          0.200   5.0
ComponentwiseGradientBoosting  0.227   6.0
GradientBoosting               0.233   7.0
CoxRidge                       0.236   8.0

In [95]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ExtraSurvivalTrees               0.607   1.0
GradientBoosting                 0.586   2.0
CoxPH                            0.562   3.0
CoxLasso                         0.561   4.0
CoxElastic                       0.559   5.0
Randomsurvivalforest             0.546   6.0
CoxRidge                         0.537   7.0
ComponentwiseGradientBoosting    0.536   8.0

In [96]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
GradientBoosting               0.228   1.0
CoxRidge                       0.229   2.0
ComponentwiseGradientBoosting  0.234   3.0
ExtraSurvivalTrees             0.252   4.0
Randomsurvivalforest           0.263   5.0
CoxLasso                       0.289   6.0
CoxPH                          0.290   7.5
CoxElastic                     0.290   7.5

In [97]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/dfs/standard/rent/'  # Folder path where you want to save the files

# List of corresponding file namess
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_dfs_standard_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [98]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-22